### PR TITLE
v4/presign: Fix presign requests when there are more signed headers.

### LINKED ISSUE #3217: Single-part upload using pre-signed url failed with response status 400
Attempt to upload a small file to a pre-signed failed with http response status 400.

## Expected Behavior

Uploading a small file (<5 MB, so no multi-part upload was used) to a bucket using a pre-signed url should succeed.  Because it works with aws S3.

## Current Behavior

It doesn't work with minio server.

## Possible Solution

For single-part upload, there is no upload ID.  So minio server should just save the file into the specified bucket. 

## Steps to Reproduce (for bugs)

1. Generate a request using s3 api S3.PutObjectRequest
2. Get a pre-signed url using s3 api Request.Presign
3. Send the file to the pre-signed url using http PUT
4. Now you will get http response with status 400

## Context

For small files, we don't use multi-part upload, which is intended for big files.

## Your Environment

* Version used:
We build minio server from source code downloaded on 11/09/2016 using go get -u github.com/minio/minio

* Environment name and version (e.g. nginx 1.9.1):
* Server type and version:
minio server, no SSL, 

* Operating System and version:
Ubuntu 16.04

* Link to your project:

### PR DESCRIPTION
**Pull request by harshavardhana**
## Description
This fix removes a wrong logic which fails for requests which
have more signed headers in a presign request.

## Motivation and Context
Fixes #3217

## How Has This Been Tested?
Manually and using aws-sdk-go. 

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Review by fwessels — COMMENTED** [review]
LGTM

**Review by krishnasrinivas — COMMENTED** [review]
Looks good but needs a test case.

**Comment by harshavardhana** [comment]
> Looks good but needs a test case.

Added a test case @krishnasrinivas

File: cmd/signature-v4-utils.go [hunk 1]
```diff
@@ -115,11 +121,14 @@ func extractSignedHeaders(signedHeaders []string, reqHeaders http.Header) (http.
 	if errCode != ErrNone {
 		return nil, errCode
 	}
+	// With only one signed header, we don't need to look for any other headers.
+	if len(signedHeaders) == 1 {
+		return nil, ErrNone
+	}
```
Comment (krishnasrinivas) [inline cmd/signature-v4-utils.go:122]: actually findHost function can be removed and this above change `if len(signedHeaders) == 1 {` is not needed.

i.e here:

```
if !contains(signedHeaders, "host") {
    // host header signing is mandatory.
    return ErrUnsignedHeaders
}
```

can be done

**Review by krishnasrinivas — APPROVED** [review]
Added one comment about removal of findHost though.
