### PR TITLE
fix: KES http2.0 communication support

### LINKED ISSUE #10326: [resolved] KES requests fail with HTTP Version Not Supported (S3 gateway)
## Expected Behavior
S3 gateway configured for single encryption and KES should encrypt data when calling PutObject with SSE-S3

## Current Behavior
minio fails with a 500 and following logs:
```
API: PutObject(bucket=tsufeki-k8s-backup-2, object=foo9)
Time: 23:24:58 UTC 08/21/2020
DeploymentID: 70502bde-97ae-4469-b913-dcca8320e6dd
RequestID: 162D6C19314A2974
RemoteHost: 127.0.0.1
Host: 127.0.0.1:9000
UserAgent: aws-cli/1.18.111 Python/3.8.5 Linux/5.7.0-2-amd64 botocore/1.17.22
Error: HTTP Version Not Supported
       6: cmd/api-errors.go:1980:cmd.toAPIErrorCode()
       5: cmd/api-errors.go:2005:cmd.toAPIError()
       4: cmd/object-handlers.go:1535:cmd.objectAPIHandlers.PutObjectHandler()
       3: cmd/http-tracer.go:128:cmd.Trace()
       2: cmd/handler-utils.go:365:cmd.httpTraceHdrs.func1()
       1: net/http/server.go:2041:http.HandlerFunc.ServeHTTP()
```

## Possible Solution

Downgrading KES to 0.8.1 (last version not enforcing HTTP/2) is a working workaround - suggesting that for some reason minio may be using HTTP/1 not 2 to make requests to KES.

## Steps to Reproduce (for bugs)

1. Configure KES as in https://github.com/minio/kes/wiki/MinIO-Object-Storage (self-signed certs)
2. Start `minio gateway s3` with appropriate KMS env vars
3. Run `aws --endpoint-url http://127.0.0.1:9000 s3 cp ./foo s3://some-bucket/foo --sse`

## Context
I'm trying to encrypt Velero backups in Kubernetes.

## Your Environment

* Version used (`minio --version`): RELEASE.2020-08-18T19-41-00Z (docker image)
* KES version: 0.11.0
* Server setup and configuration: small kubernetes cluster ([k3s](https://k3s.io/), both minio and kes are simple deployments and ClusterIP services, they are not behind any proxies or ingresses.
* Operating System and version (`uname -a`): `Linux zeruel1 5.7.0-2-amd64 #1 SMP Debian 5.7.10-1 (2020-07-26) x86_64 GNU/Linux`

### PR DESCRIPTION
**Pull request by harshavardhana**
## Description
fix: KES http2.0 communication support

## Motivation and Context
resolves #10326 

## How to test this PR?
As per the reproducer mentioned in the #10326 

## Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [ ] Fixes a regression (If yes, please add `commit-id` or `PR #` here)
- [ ] Documentation needed
- [ ] Unit tests needed

### CODE REVIEW

**Comment by minio-trusted** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-s3.sh | :heavy_check_mark: |
| mint-erasure.sh | :heavy_check_mark: |
| mint-dist-erasure.sh | :heavy_check_mark: |
| mint-zoned.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-gateway-azure.sh | :x: [more...](#f60d6a44-239a-40f8-94a4-826715daf917) |
<a name="f60d6a44-239a-40f8-94a4-826715daf917"></a>
### 10341-2eeeb98/mint-gateway-azure.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-dev7.minio.io:30751
ACCESS_KEY:           minioazure
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 105225e9c5f2:/mint/log /tmp/mint-logs'

(1/15) Running aws-sdk-go tests ... done in 7 seconds
(2/15) Running aws-sdk-java tests ... done in 2 seconds
(3/15) Running aws-sdk-php tests ... done in 5 minutes and 11 seconds
(4/15) Running aws-sdk-ruby tests ... done in 17 seconds
(5/15) Running awscli tests ... done in 2 minutes and 36 seconds
(6/15) Running healthcheck tests ... done in 1 seconds
(7/15) Running mc tests ... done in 3 minutes and 19 seconds
(8/15) Running minio-dotnet tests ... done in 1 minutes and 41 seconds
(9/15) Running minio-go tests ... FAILED in 5 minutes and 10 seconds
{
  "args": {},
  "duration": 1314,
  "error": "The specified multipart upload does not exist. The upload ID may be invalid, or the upload may have been aborted or completed.",
  "function": "CopyObjectPart(destination, source)",
  "message": "CompleteMultipartUpload call failed",
  "name": "minio-go: testUnencryptedToSSES3CopyObjectPart",
  "status": "FAIL"
}
(9/15) Running minio-java tests ... done in 5 minutes and 45 seconds
(10/15) Running minio-js tests ... done in 2 minutes and 49 seconds
(11/15) Running minio-py tests ... done in 10 minutes and 14 seconds
(12/15) Running s3cmd tests ... done in 1 minutes and 35 seconds
(13/15) Running s3select tests ... done in 50 seconds
(14/15) Running security tests ... done in 0 seconds

Executed 14 out of 15 tests successfully.
```
Deleting image on docker hub
Deleting image locally
Error: No such image: minio/minio:10341-2eeeb98

File: cmd/crypto/kes.go [hunk 1]
```diff
@@ -115,15 +116,32 @@ func NewKes(cfg KesConfig) (KMS, error) {
...
-	cfg.Transport.TLSClientConfig = &tls.Config{
-		Certificates: []tls.Certificate{cert},
-		RootCAs:      certPool,
+	if cfg.Transport.TLSClientConfig != nil {
+		if err = loadCACertificates(cfg.CAPath,
+			cfg.Transport.TLSClientConfig.RootCAs); err != nil {
+			return nil, err
+		}
+		cfg.Transport.TLSClientConfig.Certificates = append(
+			cfg.Transport.TLSClientConfig.Certificates, cert)
```
Comment (aead) [inline cmd/crypto/kes.go]:
```suggestion
cfg.Transport.TLSClientConfig.Certificates = cert
```

KES requires that the client sends only one client certificate. Otherwise, KES cannot determine what policy to apply.

**Review by aead — COMMENTED** [review]
I guess this needs some more documentation / explanation (commit msg / comments) what the issue is and/or why this PR fixes it. This context information has to be captured.

**Review by aead — APPROVED** [review]
LGTM. However, will investigate the exact root cause and send a separate PR documenting it

**Review by kannappanr — APPROVED** [review]
LGTM

**Comment by minio-trusted** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-s3.sh | :heavy_check_mark: |
| mint-erasure.sh | :heavy_check_mark: |
| mint-dist-erasure.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-gateway-azure.sh | :x: [more...](#f95e00a4-2918-426d-b7f4-0708b2c897d7) |
| mint-zoned.sh | :x: [more...](#b7bd67e5-478d-46ac-ba87-8b76784054d2) |
<a name="b7bd67e5-478d-46ac-ba87-8b76784054d2"></a>
### 10341-e71f72c/mint-zoned.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-c3.minio.io:32240
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 78de65187d16:/mint/log /tmp/mint-logs'

(1/15) Running aws-sdk-go tests ... done in 2 seconds
(2/15) Running aws-sdk-java tests ... done in 1 seconds
(3/15) Running aws-sdk-php tests ... done in 44 seconds
(4/15) Running aws-sdk-ruby tests ... done in 5 seconds
(5/15) Running awscli tests ... done in 2 minutes and 11 seconds
(6/15) Running healthcheck tests ... done in 0 seconds
(7/15) Running mc tests ... done in 49 seconds
(8/15) Running minio-dotnet tests ... done in 50 seconds
(9/15) Running minio-go tests ... done in 2 minutes and 2 seconds
(10/15) Running minio-java tests ... done in 1 minutes and 31 seconds
(11/15) Running minio-js tests ... done in 49 seconds
(12/15) Running minio-py tests ... done in 3 minutes and 44 seconds
(13/15) Running s3cmd tests ... FAILED in 20 seconds
{
  "name": "s3cmd",
  "duration": "8310",
  "function": "test_sync_list_objects",
  "status": "FAIL",
  "error": "WARNING: Bucket is not empty. Removing all the objects from it first. This may take some time...\nERROR: S3 error: 404 (Not Found)"
}
(13/15) Running s3select tests ... done in 7 seconds
(14/15) Running security tests ... done in 0 seconds

Executed 14 out of 15 tests successfully.
```
<a name="f95e00a4-2918-426d-b7f4-0708b2c897d7"></a>
### 10341-e71f72c/mint-gateway-azure.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-dev7.minio.io:32533
ACCESS_KEY:           minioazure
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp e0d9793bb281:/mint/log /tmp/mint-logs'

(1/15) Running aws-sdk-go tests ... done in 8 seconds
(2/15) Running aws-sdk-java tests ... done in 1 seconds
(3/15) Running aws-sdk-php tests ... done in 5 minutes and 29 seconds
(4/15) Running aws-sdk-ruby tests ... done in 23 seconds
(5/15) Running awscli tests ... done in 2 minutes and 41 seconds
(6/15) Running healthcheck tests ... done in 0 seconds
(7/15) Running mc tests ... done in 3 minutes and 17 seconds
(8/15) Running minio-dotnet tests ... done in 1 minutes and 19 seconds
(9/15) Running minio-go tests ... FAILED in 1 minutes and 43 seconds
{
  "args": {
    "bucketName": "minio-go-test-ubgt01cmergyf4iv",
    "objectName": "test-object",
    "opts": "",
    "size": -1
  },
  "duration": 677,
  "function": "PutObject(bucketName, objectName, reader,size,opts)",
  "message": "Unexpected size",
  "name": "minio-go: testPutObjectStreaming",
  "status": "FAIL"
}
(9/15) Running minio-java tests ... done in 5 minutes and 49 seconds
(10/15) Running minio-js tests ... FAILED in 46 seconds
{
  "name": "minio-js",
  "function": "\"after all\" hook in \"functional tests\"",
  "duration": 75,
  "status": "FAIL",
  "error": "S3Error: The bucket you tried to delete is not empty at Object.parseError (node_modules/minio/dist/main/xml-parsers.js:86:11) at /mint/run/core/minio-js/node_modules/minio/dist/main/transformers.js:156:22 at DestroyableTransform._flush (node_modules/minio/dist/main/transformers.js:80:10) at DestroyableTransform.prefinish (node_modules/readable-stream/lib/_stream_transform.js:129:10) at prefinish (node_modules/readable-stream/lib/_stream_writable.js:611:14) at finishMaybe (node_modules/readable-stream/lib/_stream_writable.js:620:5) at endWritable (node_modules/readable-stream/lib/_stream_writable.js:643:3) at DestroyableTransform.Writable.end (node_modules/readable-stream/lib/_stream_writable.js:571:22) at IncomingMessage.onend (_stream_readable.js:678:10) at endReadableNT (_stream_readable.js:1244:12) at processTicksAndRejections (internal/process/task_queues.js:80:21)"
}
(10/15) Running minio-py tests ... done in 9 minutes and 51 seconds
(11/15) Running s3cmd tests ... done in 1 minutes and 36 seconds
(12/15) Running s3select tests ... done in 32 seconds
(13/15) Running security tests ... done in 0 seconds

Executed 13 out of 15 tests successfully.
```
Deleting image on docker hub
Deleting image locally
Error: No such image: minio/minio:10341-e71f72c

**Comment by minio-trusted** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-s3.sh | :heavy_check_mark: |
| mint-erasure.sh | :heavy_check_mark: |
| mint-dist-erasure.sh | :heavy_check_mark: |
| mint-zoned.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-gateway-azure.sh | :x: [more...](#f0b71a7d-4e43-4234-bc24-edb47c1924ee) |
<a name="f0b71a7d-4e43-4234-bc24-edb47c1924ee"></a>
### 10341-7c851d9/mint-gateway-azure.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-dev8.minio.io:31912
ACCESS_KEY:           minioazure
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 5d4a46917718:/mint/log /tmp/mint-logs'

(1/15) Running aws-sdk-go tests ... done in 7 seconds
(2/15) Running aws-sdk-java tests ... done in 1 seconds
(3/15) Running aws-sdk-php tests ... done in 5 minutes and 36 seconds
(4/15) Running aws-sdk-ruby tests ... done in 18 seconds
(5/15) Running awscli tests ... done in 2 minutes and 10 seconds
(6/15) Running healthcheck tests ... done in 0 seconds
(7/15) Running mc tests ... done in 3 minutes and 26 seconds
(8/15) Running minio-dotnet tests ... done in 1 minutes and 32 seconds
(9/15) Running minio-go tests ... FAILED in 5 minutes and 15 seconds
{
  "args": {},
  "duration": 1346,
  "error": "The specified multipart upload does not exist. The upload ID may be invalid, or the upload may have been aborted or completed.",
  "function": "CopyObjectPart(destination, source)",
  "message": "CompleteMultipartUpload call failed",
  "name": "minio-go: testUnencryptedToSSES3CopyObjectPart",
  "status": "FAIL"
}
(9/15) Running minio-java tests ... done in 5 minutes and 55 seconds
(10/15) Running minio-js tests ... done in 2 minutes and 33 seconds
(11/15) Running minio-py tests ... done in 11 minutes and 2 seconds
(12/15) Running s3cmd tests ... done in 1 minutes and 23 seconds
(13/15) Running s3select tests ... done in 48 seconds
(14/15) Running security tests ... done in 0 seconds

Executed 14 out of 15 tests successfully.
```
Deleting image on docker hub
Deleting image locally
