### PR TITLE
fix: unable to get net.Interface cause panic

### LINKED ISSUE #21267: `minio` panic because of `net.Interfaces()` under android
## NOTE
If this case is urgent, please subscribe to [Subnet](https://min.io/pricing) so that our 24/7 support team may help you faster.

## Expected Behavior

`minio` should not panic under android

## Current Behavior

`minio` panic because of `net.Interfaces()` under android

## Possible Solution

- Properly handle `net.Interfaces()` under android

https://github.com/minio/minio/blob/RELEASE.2025-04-22T22-12-26Z/cmd/net.go#L56

- Workaround `net.Interfaces()` under android, like termux minio patch

https://github.com/termux/termux-packages/blob/master/packages/minio/cmd-net.go.patch

```sh
~ $ pkg install minio >/dev/null 2>/dev/null && minio --help >/dev/null && echo OK
OK
```

- Or provide cli option or configuration option or environment option to not panic

```sh
$ export MINIO_NOT_PANIC_FOR_ISSUE_21267=1
$ minio --help
...
```

## Steps to Reproduce (for bugs)

1. install termux
2. install proot-distro archlinux
3. install minio

<details>
<summary>Click to view code</summary>

```sh
~ $ proot-distro remove archlinux; proot-distro install archlinux && proot-distro login archlinux                                                                                          
[*] Wiping the rootfs of Arch Linux...
[*] Finished.
[*] Installing Arch Linux...
[*] Creating directory '/data/data/com.termux/files/usr/var/lib/proot-distro/installed-rootfs/archlinux'...
[*] Creating directory '/data/data/com.termux/files/usr/var/lib/proot-distro/installed-rootfs/archlinux/.l2s'...
[*] Using cached rootfs tarball...
[*] Checking integrity, please wait...
[*] Extracting rootfs, please wait...
[*] Writing file '/data/data/com.termux/files/usr/var/lib/proot-distro/installed-rootfs/archlinux/etc/environment'...
[*] Updating PATH in '/data/data/com.termux/files/usr/var/lib/proot-distro/installed-rootfs/archlinux/etc/bash.bashrc' if needed...
[*] Updating PATH in '/data/data/com.termux/files/usr/var/lib/proot-distro/installed-rootfs/archlinux/etc/profile' if needed...
[*] Updating PATH in '/data/data/com.termux/files/usr/var/lib/proot-distro/installed-rootfs/archlinux/etc/login.defs' if needed...
[*] Creating file '/data/data/com.termux/files/usr/var/lib/proot-distro/installed-rootfs/archlinux/etc/resolv.conf'...
[*] Creating file '/data/data/com.termux/files/usr/var/lib/proot-distro/installed-rootfs/archlinux/etc/hosts'...
[*] Registering Android-specific UIDs and GIDs...
[*] Running distribution-specific configuration steps...
Generating locales...
  en_US.UTF-8... done
Generation complete.
[*] Finished.

Log in with: proot-distro login archlinux

[root@localhost ~]# pacman -Syu --noconfirm
...
[root@localhost ~]# pacman -S --noconfirm minio
warning: minio-2025.04.22-1 is up to date -- reinstalling
resolving dependencies...
looking for conflicting packages...

Packages (1) minio-2025.04.22-1

Total Installed Size:  117.32 MiB
Net Upgrade Size:        0.00 MiB

:: Proceed with installation? [Y/n] 
(1/1) checking keys in keyring                                                                                    [####################################################################] 100%
(1/1) checking package integrity                                                                                  [####################################################################] 100%
(1/1) loading package files                                                                                       [####################################################################] 100%
(1/1) checking for file conflicts                                                                                 [####################################################################] 100%
(1/1) checking available disk space                                                                               [####################################################################] 100%
:: Processing package changes...
(1/1) reinstalling minio                                                                                          [####################################################################] 100%
:: Running post-transaction hooks...
(1/4) Creating system user accounts...
(2/4) Reloading system manager configuration...
Failed to check for chroot() environment: Function not implemented
  Skipped: Current root is not booted.
(3/4) Restarting marked services...
Failed to check for chroot() environment: Function not implemented
  Skipped: Current root is not booted.
(4/4) Arming ConditionNeedsUpdate...
```

</details>

---

`minio` panic under `proot-distro` archlinux under `termux`

```sh
[root@localhost ~]# minio --help
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x300130489c]

goroutine 1 [running]:
github.com/minio/minio/internal/logger.fatal({0x300578be40, 0x40001acd70}, {0x3002e93a63?, 0x30009957ec?}, {0x0?, 0x4000df58c0?, 0x4000083ad8?})
        github.com/minio/minio/internal/logger/console.go:81 +0x9c
github.com/minio/minio/internal/logger.FatalIf(...)
        github.com/minio/minio/internal/logger/logger.go:456
github.com/minio/minio/cmd.mustGetLocalIPs()
        github.com/minio/minio/cmd/net.go:57 +0x58
github.com/minio/minio/cmd.mustGetLocalIP4()
        github.com/minio/minio/cmd/net.go:97 +0x28
github.com/minio/minio/cmd.init()
        github.com/minio/minio/cmd/net.go:36 +0x2160
```

## Context

Use termux to turn old phone into archlinux server for multiple usage, including minio.

## Your Environment

* Version used (`minio --version`): minio-2025.04.22-1
* Server setup and configuration: `proot-distro install archlinux`
* Operating System and version (`uname -a`): `Linux localhost 6.2.1-PRoot-Distro #1 SMP PREEMPT Wed Feb  7 03:56:40 UTC 2024 aarch64 GNU/Linux`

### PR DESCRIPTION
**Pull request by jiuker**
fix: unable to get net.Interface cause panic

## Community Contribution License
All community contributions in this pull request are licensed to the project maintainers
under the terms of the [Apache 2 license](https://www.apache.org/licenses/LICENSE-2.0). 
By creating this pull request I represent that I have the right to license the 
contributions to the project maintainers under the Apache 2 license.

## Description

fix: #21267 
unable to get iplist will panic 
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x300130489c]

goroutine 1 [running]:
github.com/minio/minio/internal/logger.fatal({0x300578be40, 0x40001acd70}, {0x3002e93a63?, 0x30009957ec?}, {0x0?, 0x4000df58c0?, 0x4000083ad8?})
        github.com/minio/minio/internal/logger/console.go:81 +0x9c
github.com/minio/minio/internal/logger.FatalIf(...)
        github.com/minio/minio/internal/logger/logger.go:456
github.com/minio/minio/cmd.mustGetLocalIPs()
        github.com/minio/minio/cmd/net.go:57 +0x58
github.com/minio/minio/cmd.mustGetLocalIP4()
        github.com/minio/minio/cmd/net.go:97 +0x28
github.com/minio/minio/cmd.init()
        github.com/minio/minio/cmd/net.go:36 +0x2160
```

Now show this:
```
~ $ ./minio server ./data
FATAL Unable to get IP addresses of this host: Insufficient permissions to use specified port
      > Please ensure MinIO binary has 'cap_net_bind_service=+ep' permissions
      HINT:
        Use 'sudo setcap cap_net_bind_service=+ep /path/to/minio' to provide sufficient permissions
```

## Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Optimization (provides speedup with no functional changes)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [ ] Fixes a regression (If yes, please add `commit-id` or `PR #` here)
- [ ] Unit tests added/updated
- [ ] Internal documentation updated
- [ ] Create a documentation update request [here](https://github.com/minio/docs/issues/new?label=doc-change,title=Doc+Updated+Needed+For+PR+github.com%2fminio%2fminio%2fpull%2fNNNNN)

### CODE REVIEW

**Comment by loynoir** [comment]
Would be nice to provide config similar to termux patch, let minio run under non rooted android

https://github.com/termux/termux-packages/blob/master/packages/minio/cmd-net.go.patch

File: internal/logger/console.go [hunk 1]
```diff
@@ -78,6 +79,10 @@ func fatal(err error, msg string, data ...interface{}) {
 	} else {
 		msg = fmt.Sprintf(msg, data...)
 	}
+	if errorFmtFunc == nil {
```
Comment (klauspost) [inline internal/logger/console.go]: Can't you just initialize it to a reasonable default? (while not including config)

Comment (jiuker) [reply internal/logger/console.go]: Issue can be simply like this:
```golang
package cmd
var localIPV4 = mustGetLocalIPV4()

func init(){
   errorFmtFunc = config.FmtError
}
```
Hi, @klauspost  Where can be first run before the init?

Comment (klauspost) [reply internal/logger/console.go]: @jiuker When declaring

```
var errorFmtFunc = func(msg string, err error, isFatal bool) string {...}
```

File: internal/logger/logger.go [hunk 2]
```diff
@@ -75,7 +76,8 @@ var matchingFuncNames = [...]string{
 var (
 	quietFlag, jsonFlag, anonFlag bool
 	// Custom function to format error
-	errorFmtFunc func(string, error, bool) string
+	// can be registered by RegisterError
+	errorFmtFunc = config.FmtError
```
Comment (klauspost) [inline internal/logger/logger.go]: Can't you make this work without adding an import of config?

It will annoying that config will not be able to import "logging".

Comment (jiuker) [reply internal/logger/logger.go]: How about now @klauspost

**Review by klauspost — APPROVED** [review]

File: internal/logger/logger.go (hunk 2 above)
Comment (klauspost) [reply internal/logger/logger.go]: Perfect!

**Review by harshavardhana — APPROVED** [review]

File: internal/logger/logger.go [hunk 3]
```diff
@@ -75,7 +75,10 @@ var matchingFuncNames = [...]string{
 var (
 	quietFlag, jsonFlag, anonFlag bool
 	// Custom function to format error
-	errorFmtFunc func(string, error, bool) string
+	// can be registered by RegisterError
+	errorFmtFunc = func(introMsg string, err error, jsonFlag bool) string {
```
Comment (shtripat) [inline internal/logger/logger.go:79]: `jsonFlag` attr not used in function. Do we plan to use later?

Comment (jiuker) [reply internal/logger/logger.go:79]: We will replace it by `RegisterError` later. Here just a init state. @shtripat

**Review by shtripat — APPROVED** [review]
