### PR TITLE
erasure-readfile: write to given Writer than returning buffer.

### LINKED ISSUE #1889: XL: Read of a large part will cause out of memory error
```
98                  var buffer []byte                                                                                                                                             
99                  buffer, err = erasureReadFile(onlineDisks, bucket, pathJoin(object, partName), partName, partSize, eInfos)                                                    
100                 if err != nil {                                                                                                                                               
101                         return err                                                                                                                                            
102                 }
```

If it was a PUT operation of a large file (for example a 4G file on a VM with 3G RAM) this operation will fail with oom error.
@harshavardhana  Was it a conscious decision to do it this way?

### PR DESCRIPTION
**Pull request by balamurugana**
Fixes #1889

### CODE REVIEW

File: erasure-readfile.go [hunk 1]
```diff
@@ -97,25 +99,34 @@ func erasureReadFile(disks []StorageAPI, volume string, path string, partName st
...
+			return bytesWritten, err
 		}
 
 		// Copy data blocks.
-		buffer = append(buffer, dataBlocks...)
+		var n int64
+		if offset > 0 {
+			n, err = io.Copy(writer, bytes.NewBuffer(dataBlocks[offset:]))
+		} else {
+			n, err = io.Copy(writer, bytes.NewBuffer(dataBlocks))
```
Comment (harshavardhana) [inline erasure-readfile.go]: Use bytes.NewReader()

File: erasure-readfile.go [hunk 2]
```diff
@@ -97,25 +99,34 @@ func erasureReadFile(disks []StorageAPI, volume string, path string, partName st
...
+		}
+		bytesWritten += int64(n)
+		if err != nil {
+			return bytesWritten, err
```
Comment (harshavardhana) [inline erasure-readfile.go:136]: Another problem is you are not taking in the 'length' requirement you are writing more than requested.

File: xl-v1-object.go [hunk 3]
```diff
@@ -95,26 +94,16 @@ func (xl xlObjects) GetObject(bucket, object string, startOffset int64, length i
...
-			var m int64
-			m, err = io.Copy(writer, bytes.NewReader(buffer[partOffset:]))
-			if err != nil {
-				return err
-			}
-			length -= m
+		if length > n {
+			length -= n
 		} else {
-			_, err = io.CopyN(writer, bytes.NewReader(buffer[partOffset:]), length)
```
Comment (harshavardhana) [inline xl-v1-object.go:108]: This case in not handled inside erasureReadFile()

File: erasure-readfile.go (hunk 1 above)
Comment (balamurugana) [inline erasure-readfile.go]: Done

File: erasure-readfile.go (hunk 2 above)
Comment (balamurugana) [inline erasure-readfile.go:136]: Done. Fixing it.

File: xl-v1-object.go (hunk 3 above)
Comment (balamurugana) [inline xl-v1-object.go:108]: Done. Fixing it.

File: erasure-readfile.go [hunk 4]
```diff
@@ -17,54 +17,47 @@
...
 	"errors"
+	"io"
 
 	"github.com/klauspost/reedsolomon"
 )
 
-// erasureReadFile - read an entire erasure coded file at into a byte
-// array. Erasure coded parts are often few mega bytes in size and it
-// is convenient to return them as byte slice. This function also
-// supports bit-rot detection by verifying checksum of individual
```
Comment (harshavardhana) [inline erasure-readfile.go:29]: Why this comment is removed? - does this function remove bit-rot detection?

File: erasure-readfile.go [hunk 5]
```diff
@@ -74,13 +67,33 @@ func erasureReadFile(disks []StorageAPI, volume string, path string, partName st
...
+
+			// Remember bytes read at first time.
+			if lastReadSize == 0 {
+				lastReadSize = n
+			}
+
+			// TODO: In a suitation, there may be very few corrupted shards among total shards
+			// ie in 16 disks setup, there may be size mismatching corrupted shards
+			// (assume first three shards are invalid).  This is still valid to retrieve
+			// the data by reconstruct without those shards.
```
Comment (harshavardhana) [inline erasure-readfile.go]: Do not call shards, call 'blocks' as consistently used everywhere.

File: erasure-readfile.go [hunk 6]
```diff
@@ -17,54 +17,47 @@
...
-	for totalSizeLeft > 0 {
-		// Calculate the proper block size.
-		var curBlockSize int64
-		if eInfo.BlockSize < totalSizeLeft {
-			curBlockSize = eInfo.BlockSize
-		} else {
-			curBlockSize = totalSizeLeft
-		}
+	// Calculate start block for given offset and how many bytes to skip to get the offset.
+	startBlock := offset / eInfo.BlockSize
```
Comment (harshavardhana) [inline erasure-readfile.go]: Move these into a function so that it's useful when we bring in healing code.

File: erasure-readfile.go [hunk 7]
```diff
@@ -17,54 +17,47 @@
...
+	for block := startBlock; block <= endBlock; block++ {
 		// Allocate encoded blocks up to storage disks.
 		enBlocks := make([][]byte, len(disks))
 
 		// Counter to keep success data blocks.
 		var successDataBlocksCount = 0
 		var noReconstruct bool // Set for no reconstruction.
 
+		// Keep how many bytes are read for this block.
+		// In most cases, last block in the file is short than eInfo.BlockSize
```
Comment (harshavardhana) [inline erasure-readfile.go]: s/'last block in the file is short than'/'last block in the file is shorter than'

File: erasure-readfile.go [hunk 8]
```diff
@@ -74,13 +67,33 @@ func erasureReadFile(disks []StorageAPI, volume string, path string, partName st
...
+				// As the data we got is smaller than eInfo.BlockSize, keep only required shard slice
+				enBlocks[blockIndex] = append([]byte{}, enBlocks[blockIndex][:n]...)
+			}
+
+			// Remember bytes read at first time.
+			if lastReadSize == 0 {
+				lastReadSize = n
+			}
+
+			// TODO: In a suitation, there may be very few corrupted shards among total shards
```
Comment (harshavardhana) [inline erasure-readfile.go]: can you open a bug on this and explain the situation there? - need to see how this plays out, since a corrupted block would have been skipped by now after the `isValidBlock`. Only situation is a small window where other disks also get corrupted after the sha512 validation.

File: erasure-readfile.go (hunk 4 above)
Comment (balamurugana) [inline erasure-readfile.go:29]: > does this function remove bit-rot detection?

No change is made wrt block verification.  Adding the comment again.

File: erasure-readfile.go (hunk 6 above)
Comment (balamurugana) [inline erasure-readfile.go]: Are you talking about moving start/end block calculation into a separate function?

File: erasure-readfile.go (hunk 7 above)
Comment (balamurugana) [inline erasure-readfile.go]: Done

File: erasure-readfile.go (hunk 8 above)
Comment (balamurugana) [inline erasure-readfile.go]: Done.

File: erasure-readfile.go (hunk 5 above)
Comment (balamurugana) [inline erasure-readfile.go]: Done.

**Comment by harshavardhana** [comment]
> Are you talking about moving start/end block calculation into a separate function?

Yeah
