### PR TITLE
Make PutObject a nop for an object which ends with "/" and size is '0'

### LINKED ISSUE #2965: ecosystem: Validate all spark and hadoop supported s3 connectors
## Expected behaviour

I want to use spark-shell (v2.0.1) to connect to minio local to read input data and write back output data. 
## Actual behaviour

Attempting a simple read of a text file (json in this case) results in the error:

```
com.amazonaws.services.s3.model.AmazonS3Exception: Status Code: 400, AWS Service: Amazon S3, AWS Request ID: null, AWS Error Code: null, AWS Error Message: Bad Request
```

   (full stack will be below)
## Steps to reproduce the behaviour

Install Oracle Java 8 (1.8.0_71)
Install Scala 2.11.8
Minio installed by Home Brew
Install Spark 2.0.1

Start the minio server local, log into the browser UI, create a bucket named `data` and upload a small json file to it (e.g. bacon_tiny.json).  

```
{ "bacon": {
    "isCrispy": true,
    "isDelicious": true,
    "isVegan": false
    }
}
```

Relevant bits of spark-env.sh (all other bits left to default):

```
HADOOP_CONF_DIR=/Users/bkarels/hadoop/hadoop-2.7.3/etc/hadoop
SPARK_LOCAL_IP="127.0.0.1"
SPARK_MASTER_HOST="localhost"
SPARK_MASTER_WEBUI_PORT=8080
SPARK_MASTER_PORT=7077
SPARK_DAEMON_JAVA_OPTS="-Djava.net.preferIPv4Stack=true -Dcom.amazonaws.services.s3.enableV4=true"
```

core-site.xml (from ~/hadoop/hadoop-2.7.3/etc/hadoop):

```
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="configuration.xsl"?>

<configuration>
  <property>
    <name>fs.s3a.endpoint</name>
    <value>http://127.0.0.1:9000</value>
  </property>

  <property>
    <name>fs.s3a.access.key</name>
    <description>AWS access key ID.</description>
    <value>*************************</value>
  </property>

  <property>
    <name>fs.s3a.secret.key</name>
    <description>AWS secret key.</description>
    <value>*********************************************</value>
  </property>

</configuration>
```
### Starting the spark-shell

```
$ ./bin/spark-shell --master local[4] --jars "./bin/hadoop-aws-2.7.1.jar,./bin/aws-java-sdk-1.7.4.jar"
scala> val bacon = sc.textFile("s3a://data/bacon_tiny.json").first
```

```
com.amazonaws.services.s3.model.AmazonS3Exception: Status Code: 400, AWS Service: Amazon S3, AWS Request ID: null, AWS Error Code: null, AWS Error Message: Bad Request
  at com.amazonaws.http.AmazonHttpClient.handleErrorResponse(AmazonHttpClient.java:798)
  at com.amazonaws.http.AmazonHttpClient.executeHelper(AmazonHttpClient.java:421)
  at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:232)
  at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:3528)
  at com.amazonaws.services.s3.AmazonS3Client.headBucket(AmazonS3Client.java:1031)
  at com.amazonaws.services.s3.AmazonS3Client.doesBucketExist(AmazonS3Client.java:994)
  at org.apache.hadoop.fs.s3a.S3AFileSystem.initialize(S3AFileSystem.java:297)
  at org.apache.hadoop.fs.FileSystem.createFileSystem(FileSystem.java:2669)
  at org.apache.hadoop.fs.FileSystem.access$200(FileSystem.java:94)
  at org.apache.hadoop.fs.FileSystem$Cache.getInternal(FileSystem.java:2703)
  at org.apache.hadoop.fs.FileSystem$Cache.get(FileSystem.java:2685)
  at org.apache.hadoop.fs.FileSystem.get(FileSystem.java:373)
  at org.apache.hadoop.fs.Path.getFileSystem(Path.java:295)
  at org.apache.hadoop.mapred.FileInputFormat.singleThreadedListStatus(FileInputFormat.java:258)
  at org.apache.hadoop.mapred.FileInputFormat.listStatus(FileInputFormat.java:229)
  at org.apache.hadoop.mapred.FileInputFormat.getSplits(FileInputFormat.java:315)
  at org.apache.spark.rdd.HadoopRDD.getPartitions(HadoopRDD.scala:199)
  at org.apache.spark.rdd.RDD$$anonfun$partitions$2.apply(RDD.scala:248)
  at org.apache.spark.rdd.RDD$$anonfun$partitions$2.apply(RDD.scala:246)
  at scala.Option.getOrElse(Option.scala:121)
  at org.apache.spark.rdd.RDD.partitions(RDD.scala:246)
  at org.apache.spark.rdd.MapPartitionsRDD.getPartitions(MapPartitionsRDD.scala:35)
  at org.apache.spark.rdd.RDD$$anonfun$partitions$2.apply(RDD.scala:248)
  at org.apache.spark.rdd.RDD$$anonfun$partitions$2.apply(RDD.scala:246)
  at scala.Option.getOrElse(Option.scala:121)
  at org.apache.spark.rdd.RDD.partitions(RDD.scala:246)
  at org.apache.spark.rdd.RDD$$anonfun$take$1.apply(RDD.scala:1303)
  at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:151)
  at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:112)
  at org.apache.spark.rdd.RDD.withScope(RDD.scala:358)
  at org.apache.spark.rdd.RDD.take(RDD.scala:1298)
  at org.apache.spark.rdd.RDD$$anonfun$first$1.apply(RDD.scala:1338)
  at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:151)
  at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:112)
  at org.apache.spark.rdd.RDD.withScope(RDD.scala:358)
  at org.apache.spark.rdd.RDD.first(RDD.scala:1337)
  ... 48 elided
```

All else being equal, I can adjust core-site.xml to point to an actual s3 instance and things work which is what has me thinking this might be a Minio issue.
## Minio version

```
Version: 2016-09-11T17:42:18Z
Release-Tag: RELEASE.2016-09-11T17-42-18Z
Commit-ID: 85e2d886bcb005d49f3876d6849a2b5a55e03cd3
```
## System information

```
Running on OSX 10.11.6
MacBook Pro (Retina, 15-inch, Mid 2015)
2.5 GHz Intel Core i7
16 GB 1600 MHz DDR3
```

### PR DESCRIPTION
**Pull request by harshavardhana**
## Description
Make PutObject a nop for an object which ends with "/" and size is '0'

## Motivation and Context
This helps majority of S3 compatible applications while not returning
an error upon directory create request.

Fixes #2965 

## How Has This Been Tested?
Manually

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by vadmeste** [comment]
I think this can confuse users, they could be listing that empty directory just after creating it.

Can't we just put a "hidden" object inside that empty directory ?  This doesn't break the current existing backend since we did never support empty directories before.

**Comment by harshavardhana** [comment]
No we cannot do that @vadmeste hidden files means they need to be specially handled in listObjects . Usually this is faked beacuse for a reason and also the most part a file is uploaded after this operation. This is for such applications alone.

File: cmd/object-handlers.go [hunk 1]
```diff
@@ -409,7 +409,7 @@ func (api objectAPIHandlers) PutObjectHandler(w http.ResponseWriter, r *http.Req
 			return
 		}
 	}
-	if size == -1 && !contains(r.TransferEncoding, "chunked") {
+	if size == -1 {
```
Comment (vadmeste) [inline cmd/object-handlers.go:412]: :+1:

**Comment by vadmeste** [comment]
> No we cannot do that @vadmeste hidden files means they need to be specially handled in listObjects . Usually this is faked beacuse for a reason and also the most part a file is uploaded after this operation. This is for such applications alone.

Okay. I see now we are still better with this PR.

**Review by vadmeste — APPROVED** [review]
