### PR TITLE
fix: implement generic Walk for gateway

### LINKED ISSUE #9891: [resolved] File deletion from MinIO browser throws meaningless error (master branch)
When deleting files (on master branch) in S3 gateway mode from the minio browser, the file deletes properly by an error message is always shown: Functionality not implemented. Looking to fix this myself. Feel free to assign to me.

## Expected Behavior

No error should be shown

## Current Behavior

An error message appears

Error message should not appear

## Steps to Reproduce (for bugs)

1. Launch Minio in S3 gateway mode
2. Upload a file
3. Delete the file
4.

## Context

I encountered the problem when looking into a different issue. I intend to fix this myself.

## Your Environment

* Version used (`minio version`): current master branch
* Environment name and version (e.g. nginx 1.9.1): AWS S3
* Server type and version: ec2 host
* Operating System and version (`uname -a`): amazon linux
* Link to your project:

### PR DESCRIPTION
**Pull request by harshavardhana**
## Description
fix: implement generic Walk for gateway

## Motivation and Context
Walk() functionality was missing on gateway
implementations leading to missing functionality
for the browser UI such as remove multiple objects,
download as zip file etc.

This PR brings a generic implementation across
all gateway's, it is not required to repeat the
same code in all gateway's

Fixes #9891 

## How to test this PR?
With S3 gateway test for DownloadAsZip, RemoveMultipleObjects from WebUI

## Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [x] Fixes a regression yes for some time now since we moved to Walk() implementation for web-handlers.go
- [ ] Documentation needed
- [ ] Unit tests needed
- [ ] Functional tests needed (If yes, add [mint](https://github.com/minio/mint) PR # here: )

### CODE REVIEW

**Comment by minio-trusted** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-s3.sh | :heavy_check_mark: |
| mint-gateway-azure.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-xl.sh | :x: [more...](#0726eeac-c842-413c-8388-ccc2a5311edd) |
| mint-large-bucket.sh | :x: [more...](#3854ecf0-b0a7-4e80-88c0-d26686ba7ef2) |
| mint-dist-xl.sh | :x: [more...](#2a54e02a-5b22-44e4-8888-12768d4af1c4) |
| mint-zoned.sh | :x: [more...](#ea00064d-7071-41be-aa69-f03711069183) |
<a name="3854ecf0-b0a7-4e80-88c0-d26686ba7ef2"></a>
### 9938-ce10b01/mint-large-bucket.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-c3.minio.io:31380
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 857cbb999d61:/mint/log /tmp/mint-logs'

(1/15) Running aws-sdk-go tests ... done in 59 seconds
(2/15) Running aws-sdk-java tests ... done in 9 seconds
(3/15) Running aws-sdk-php tests ... done in 1 minutes and 34 seconds
(4/15) Running aws-sdk-ruby tests ... done in 1 minutes and 56 seconds
(5/15) Running awscli tests ... done in 4 minutes and 5 seconds
(6/15) Running healthcheck tests ... done in 0 seconds
(7/15) Running mc tests ... done in 1 minutes and 35 seconds
(8/15) Running minio-dotnet tests ... done in 7 minutes and 19 seconds
(9/15) Running minio-go tests ... FAILED in 9 minutes and 57 seconds
{
  "args": {
    "bucketName": "minio-go-test-cgftvdqu3e9y9cvo",
    "objectName": "uf3lpm6akejkypkv14665qhb9rqyyf",
    "objectPrefix": "",
    "recursive": "true"
  },
  "duration": 10278,
  "error": "The bucket you tried to delete is not empty. You must delete all versions in the bucket.",
  "function": "RemoveObjectsWithOptions(bucketName, objectsCh, opts)",
  "message": "Cleanup failed",
  "name": "minio-go: testRemoveObjectsWithOptions",
  "status": "FAIL"
}
(9/15) Running minio-java tests ... FAILED in 14 minutes and 42 seconds
{
  "name": "minio-java",
  "function": "enableObjectLegalHold(String bucketName, String objectName, String versionId)",
  "duration": 4328,
  "status": "FAIL",
  "error": "error occurred\nErrorResponse(code = BucketNotEmpty, message = The bucket you tried to delete is not empty. You must delete all versions in the bucket., bucketName = minio-java-test-7f2inm, objectName = null, resource = /minio-java-test-7f2inm, requestId = 161D1851DE03AAFB, hostId = 49607690-5768-40dc-91eb-55fa5124cfa5)\nrequest={method=DELETE, url=http://minio-c3.minio.io:31380/minio-java-test-7f2inm, headers=Host: minio-c3.minio.io:31380\nAccept-Encoding: identity\nUser-Agent: MinIO (amd64; amd64) minio-java/dev\nContent-MD5: 1B2M2Y8AsgTpgAmY7PhCfg==\nx-amz-content-sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855\nx-amz-date: 20200629T184943Z\nAuthorization: AWS4-HMAC-SHA256 Credential=*REDACTED*/20200629/us-east-1/s3/aws4_request, SignedHeaders=accept-encoding;content-md5;host;x-amz-content-sha256;x-amz-date, Signature=*REDACTED*\n}\nresponse={code=409, headers=Accept-Ranges: bytes\nContent-Length: 371\nContent-Security-Policy: block-all-mixed-content\nContent-Type: application/xml\nServer: MinIO/DEVELOPMENT.2020-06-29T18-01-16Z\nVary: Origin\nX-Amz-Request-Id: 161D1851DE03AAFB\nX-Xss-Protection: 1; mode=block\nDate: Mon, 29 Jun 2020 18:49:43 GMT\n}\n >>> [io.minio.MinioClient.execute(MinioClient.java:1211), io.minio.MinioClient.execute(MinioClient.java:1236), io.minio.MinioClient.executeDelete(MinioClient.java:1366), io.minio.MinioClient.removeBucket(MinioClient.java:3686), FunctionalTest.enableObjectLegalHold_test(FunctionalTest.java:3314), FunctionalTest.runTests(FunctionalTest.java:4079), FunctionalTest.main(FunctionalTest.java:4192)]"
}
(9/15) Running minio-js tests ... done in 1 minutes and 41 seconds
(10/15) Running minio-py tests ... done in 22 minutes and 11 seconds
(11/15) Running s3cmd tests ... done in 53 seconds
(12/15) Running s3select tests ... done in 1 minutes and 31 seconds
(13/15) Running security tests ... done in 0 seconds

Executed 13 out of 15 tests successfully.
```
<a name="0726eeac-c842-413c-8388-ccc2a5311edd"></a>
### 9938-ce10b01/mint-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-dev6.minio.io:30970
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp e58c4666295d:/mint/log /tmp/mint-logs'

(1/15) Running aws-sdk-go tests ... done in 1 seconds
(2/15) Running aws-sdk-java tests ... done in 3 seconds
(3/15) Running aws-sdk-php tests ... done in 43 seconds
(4/15) Running aws-sdk-ruby tests ... done in 3 seconds
(5/15) Running awscli tests ... done in 1 minutes and 24 seconds
(6/15) Running healthcheck tests ... done in 0 seconds
(7/15) Running mc tests ... done in 24 seconds
(8/15) Running minio-dotnet tests ... done in 33 seconds
(9/15) Running minio-go tests ... FAILED in 44 seconds
{
  "args": {
    "bucketName": "minio-go-test-bnyxj9yoc16zotfa",
    "objectName": "tdldts34psz56osd65adgtb20ue9ab",
    "objectPrefix": "",
    "recursive": "true"
  },
  "duration": 3150,
  "error": "The bucket you tried to delete is not empty. You must delete all versions in the bucket.",
  "function": "RemoveObjectsWithOptions(bucketName, objectsCh, opts)",
  "message": "Cleanup failed",
  "name": "minio-go: testRemoveObjectsWithOptions",
  "status": "FAIL"
}
(9/15) Running minio-java tests ... FAILED in 1 minutes and 41 seconds
{
  "name": "minio-java",
  "function": "enableObjectLegalHold(String bucketName, String objectName, String versionId)",
  "duration": 206,
  "status": "FAIL",
  "error": "error occurred\nErrorResponse(code = BucketNotEmpty, message = The bucket you tried to delete is not empty. You must delete all versions in the bucket., bucketName = minio-java-test-qar362, objectName = null, resource = /minio-java-test-qar362, requestId = 161D165187A07375, hostId = d6a1242e-cd39-49bd-adff-b1c572af60a0)\nrequest={method=DELETE, url=http://minio-dev6.minio.io:30970/minio-java-test-qar362, headers=Host: minio-dev6.minio.io:30970\nAccept-Encoding: identity\nUser-Agent: MinIO (amd64; amd64) minio-java/dev\nContent-MD5: 1B2M2Y8AsgTpgAmY7PhCfg==\nx-amz-content-sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855\nx-amz-date: 20200629T181302Z\nAuthorization: AWS4-HMAC-SHA256 Credential=*REDACTED*/20200629/us-east-1/s3/aws4_request, SignedHeaders=accept-encoding;content-md5;host;x-amz-content-sha256;x-amz-date, Signature=*REDACTED*\n}\nresponse={code=409, headers=Accept-Ranges: bytes\nContent-Length: 371\nContent-Security-Policy: block-all-mixed-content\nContent-Type: application/xml\nServer: MinIO/DEVELOPMENT.2020-06-29T18-01-16Z\nVary: Origin\nX-Amz-Request-Id: 161D165187A07375\nX-Xss-Protection: 1; mode=block\nDate: Mon, 29 Jun 2020 18:13:02 GMT\n}\n >>> [io.minio.MinioClient.execute(MinioClient.java:1211), io.minio.MinioClient.execute(MinioClient.java:1236), io.minio.MinioClient.executeDelete(MinioClient.java:1366), io.minio.MinioClient.removeBucket(MinioClient.java:3686), FunctionalTest.enableObjectLegalHold_test(FunctionalTest.java:3314), FunctionalTest.runTests(FunctionalTest.java:4079), FunctionalTest.main(FunctionalTest.java:4192)]"
}
(9/15) Running minio-js tests ... done in 52 seconds
(10/15) Running minio-py tests ... done in 2 minutes and 11 seconds
(11/15) Running s3cmd tests ... done in 33 seconds
(12/15) Running s3select tests ... done in 5 seconds
(13/15) Running security tests ... done in 0 seconds

Executed 13 out of 15 tests successfully.
```
<a name="2a54e02a-5b22-44e4-8888-12768d4af1c4"></a>
### 9938-ce10b01/mint-dist-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-c3.minio.io:30616
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 8f84717e5cce:/mint/log /tmp/mint-logs'

(1/15) Running aws-sdk-go tests ... done in 8 seconds
(2/15) Running aws-sdk-java tests ... done in 3 seconds
(3/15) Running aws-sdk-php tests ... done in 43 seconds
(4/15) Running aws-sdk-ruby tests ... done in 5 seconds
(5/15) Running awscli tests ... done in 3 minutes and 3 seconds
(6/15) Running healthcheck tests ... done in 0 seconds
(7/15) Running mc tests ... done in 1 minutes and 45 seconds
(8/15) Running minio-dotnet tests ... done in 2 minutes and 20 seconds
(9/15) Running minio-go tests ... FAILED in 2 minutes and 5 seconds
{
  "args": {
    "bucketName": "minio-go-test-1w5xh335zyt2kod9",
    "objectName": "bzmrmr44ut9knqwc6udbmkf2yby3xy",
    "objectPrefix": "",
    "recursive": "true"
  },
  "duration": 3316,
  "error": "The bucket you tried to delete is not empty. You must delete all versions in the bucket.",
  "function": "RemoveObjectsWithOptions(bucketName, objectsCh, opts)",
  "message": "Cleanup failed",
  "name": "minio-go: testRemoveObjectsWithOptions",
  "status": "FAIL"
}
(9/15) Running minio-java tests ... FAILED in 2 minutes and 47 seconds
{
  "name": "minio-java",
  "function": "enableObjectLegalHold(String bucketName, String objectName, String versionId)",
  "duration": 444,
  "status": "FAIL",
  "error": "error occurred\nErrorResponse(code = BucketNotEmpty, message = The bucket you tried to delete is not empty. You must delete all versions in the bucket., bucketName = minio-java-test-31v0jmv, objectName = null, resource = /minio-java-test-31v0jmv, requestId = 161D16B8AAEEEB7A, hostId = 9a4a4f2e-db3e-43e6-97c4-1a1d7d9456cc)\nrequest={method=DELETE, url=http://minio-c3.minio.io:30616/minio-java-test-31v0jmv, headers=Host: minio-c3.minio.io:30616\nAccept-Encoding: identity\nUser-Agent: MinIO (amd64; amd64) minio-java/dev\nContent-MD5: 1B2M2Y8AsgTpgAmY7PhCfg==\nx-amz-content-sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855\nx-amz-date: 20200629T182025Z\nAuthorization: AWS4-HMAC-SHA256 Credential=*REDACTED*/20200629/us-east-1/s3/aws4_request, SignedHeaders=accept-encoding;content-md5;host;x-amz-content-sha256;x-amz-date, Signature=*REDACTED*\n}\nresponse={code=409, headers=Accept-Ranges: bytes\nContent-Length: 373\nContent-Security-Policy: block-all-mixed-content\nContent-Type: application/xml\nServer: MinIO/DEVELOPMENT.2020-06-29T18-01-16Z\nVary: Origin\nX-Amz-Request-Id: 161D16B8AAEEEB7A\nX-Xss-Protection: 1; mode=block\nDate: Mon, 29 Jun 2020 18:20:25 GMT\n}\n >>> [io.minio.MinioClient.execute(MinioClient.java:1211), io.minio.MinioClient.execute(MinioClient.java:1236), io.minio.MinioClient.executeDelete(MinioClient.java:1366), io.minio.MinioClient.removeBucket(MinioClient.java:3686), FunctionalTest.enableObjectLegalHold_test(FunctionalTest.java:3314), FunctionalTest.runTests(FunctionalTest.java:4079), FunctionalTest.main(FunctionalTest.java:4192)]"
}
(9/15) Running minio-js tests ... done in 1 minutes and 2 seconds
(10/15) Running minio-py tests ... done in 3 minutes and 22 seconds
(11/15) Running s3cmd tests ... done in 21 seconds
(12/15) Running s3select tests ... done in 7 seconds
(13/15) Running security tests ... done in 0 seconds

Executed 13 out of 15 tests successfully.
```
<a name="ea00064d-7071-41be-aa69-f03711069183"></a>
### 9938-ce10b01/mint-zoned.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-dev3.minio.io:30790
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 7ccd9b425aec:/mint/log /tmp/mint-logs'

(1/15) Running aws-sdk-go tests ... FAILED in 1 minutes and 26 seconds
{
  "alert": "",
  "args": {
    "bucketName": "aws-sdk-go-test-gz4fjtx1t533mq",
    "objectName": "1gs3sdsma5hlvqw6l1izqm3os461ly"
  },
  "duration": 11350,
  "error": "NoSuchKey: The specified key does not exist.\n\tstatus code: 404, request id: 161D16176889FB05, host id: ",
  "function": "testObjectTagging",
  "message": "AWS SDK Go PUTObjectTagging expected to success but got NoSuchKey",
  "name": "aws-sdk-go",
  "status": "FAIL"
}
(1/15) Running aws-sdk-java tests ... done in 11 seconds
(2/15) Running aws-sdk-php tests ... done in 2 minutes and 10 seconds
(3/15) Running aws-sdk-ruby tests ... done in 3 minutes and 29 seconds
(4/15) Running awscli tests ... done in 5 minutes and 34 seconds
(5/15) Running healthcheck tests ... done in 0 seconds
(6/15) Running mc tests ... done in 2 minutes and 28 seconds
(7/15) Running minio-dotnet tests ... done in 11 minutes and 58 seconds
(8/15) Running minio-go tests ... FAILED in 15 minutes and 2 seconds
{
  "args": {},
  "duration": 113934,
  "error": "Please reduce your request",
  "function": "testStorageClassMetadataCopyObject()",
  "message": "CopyObject failed on RRS",
  "name": "minio-go: testStorageClassMetadataCopyObject",
  "status": "FAIL"
}
(8/15) Running minio-java tests ... FAILED in 28 minutes and 30 seconds
{
  "name": "minio-java",
  "function": "enableObjectLegalHold(String bucketName, String objectName, String versionId)",
  "duration": 8031,
  "status": "FAIL",
  "error": "error occurred\nErrorResponse(code = BucketNotEmpty, message = The bucket you tried to delete is not empty. You must delete all versions in the bucket., bucketName = minio-java-test-2tjqs4d, objectName = null, resource = /minio-java-test-2tjqs4d, requestId = 161D19E052DB536F, hostId = 2c7dce71-22c1-4925-80bc-67dbe25ce9b2)\nrequest={method=DELETE, url=http://minio-dev3.minio.io:30790/minio-java-test-2tjqs4d, headers=Host: minio-dev3.minio.io:30790\nAccept-Encoding: identity\nUser-Agent: MinIO (amd64; amd64) minio-java/dev\nContent-MD5: 1B2M2Y8AsgTpgAmY7PhCfg==\nx-amz-content-sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855\nx-amz-date: 20200629T191814Z\nAuthorization: AWS4-HMAC-SHA256 Credential=*REDACTED*/20200629/us-east-1/s3/aws4_request, SignedHeaders=accept-encoding;content-md5;host;x-amz-content-sha256;x-amz-date, Signature=*REDACTED*\n}\nresponse={code=409, headers=Accept-Ranges: bytes\nContent-Length: 373\nContent-Security-Policy: block-all-mixed-content\nContent-Type: application/xml\nServer: MinIO/DEVELOPMENT.2020-06-29T18-01-16Z\nVary: Origin\nX-Amz-Request-Id: 161D19E052DB536F\nX-Xss-Protection: 1; mode=block\nDate: Mon, 29 Jun 2020 19:18:14 GMT\n}\n >>> [io.minio.MinioClient.execute(MinioClient.java:1211), io.minio.MinioClient.execute(MinioClient.java:1236), io.minio.MinioClient.executeDelete(MinioClient.java:1366), io.minio.MinioClient.removeBucket(MinioClient.java:3686), FunctionalTest.enableObjectLegalHold_test(FunctionalTest.java:3314), FunctionalTest.runTests(FunctionalTest.java:4079), FunctionalTest.main(FunctionalTest.java:4192)]"
}
(8/15) Running minio-js tests ... done in 1 minutes and 45 seconds
(9/15) Running minio-py tests ... done in 27 minutes and 51 seconds
(10/15) Running s3cmd tests ... done in 57 seconds
(11/15) Running s3select tests ... done in 1 minutes and 51 seconds
(12/15) Running security tests ... done in 0 seconds

Executed 12 out of 15 tests successfully.
```
Deleting image on docker hub
Deleting image locally

File: cmd/gateway-main.go [hunk 1]
```diff
@@ -45,6 +45,57 @@ var (
...
+	return l.nsMutex.NewNSLock(ctx, nil, bucket, objects...)
+}
+
+// Walk - implements common gateway level Walker, to walk on all objects recursively at a prefix
+func (l *GatewayLocker) Walk(ctx context.Context, bucket, prefix string, results chan<- ObjectInfo) error {
+	walk := func(ctx context.Context, bucket, prefix string, results chan<- ObjectInfo) error {
+		var marker string
+		for {
+			// set maxKeys to '0' to list maximum possible objects in single call.
+			loi, err := l.ObjectLayer.ListObjects(ctx, bucket, prefix, marker, "", 0)
```
Comment (poornas) [inline cmd/gateway-main.go:65]: when maxKeys is set to 0, s3 returns an empty list even if bucket has objects. maxKeys should be set to 1000 unless it is NAS, imo

File: cmd/gateway-main.go [hunk 2]
```diff
@@ -45,6 +45,57 @@ var (
 	}
 )
 
+// GatewayLocker implements custom NeNSLock implementation
```
Comment (poornas) [inline cmd/gateway-main.go]:
```suggestion
// GatewayLocker implements custom NewNSLock implementation
```

**Review by poornas — CHANGES_REQUESTED** [review]

File: cmd/gateway-main.go (hunk 1 above)
Comment (harshavardhana) [reply cmd/gateway-main.go:65]: Looks like a minio-go bug @poornas if maxKeys is set to 0 it should return 1000 keys. 

```
        // Set max keys.
        if maxkeys > 0 {
                urlValues.Set("max-keys", fmt.Sprintf("%d", maxkeys))
        }
```

**Review by poornas — APPROVED** [review]
LGTM

**Review by kannappanr — APPROVED** [review]
LGTM

**Comment by minio-trusted** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-s3.sh | :heavy_check_mark: |
| mint-gateway-azure.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-xl.sh | :x: [more...](#26d69496-6f00-49ba-9f34-321eea65970c) |
| mint-large-bucket.sh | :x: [more...](#3b5d5710-56c0-4162-9628-79552199e3f9) |
| mint-dist-xl.sh | :x: [more...](#015f6a10-d583-441c-bff5-58750b96cdbb) |
| mint-zoned.sh | :x: [more...](#6318146b-dbfd-4033-9653-1471b476ed12) |
<a name="015f6a10-d583-441c-bff5-58750b96cdbb"></a>
### 9938-d6356da/mint-dist-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-c3.minio.io:30038
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 85fe2c189e46:/mint/log /tmp/mint-logs'

(1/15) Running aws-sdk-go tests ... done in 6 minutes and 49 seconds
(2/15) Running aws-sdk-java tests ... FAILED in 2 seconds
Jun 30, 2020 1:04:18 AM com.amazonaws.util.Base64 warn
WARNING: JAXB is unavailable. Will fallback to SDK implementation which may be less performant.If you are using Java 9+, you will need to include javax.xml.bind:jaxb-api as a dependency.
com.amazonaws.services.s3.model.AmazonS3Exception: Server not initialized, please try again. (Service: Amazon S3; Status Code: 503; Error Code: XMinioServerNotInitialized; Request ID: 161D2CC2FB49D106; S3 Extended Request ID: b154c1c4-665d-40fe-b736-f57c80e20855), S3 Extended Request ID: b154c1c4-665d-40fe-b736-f57c80e20855
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.handleErrorResponse(AmazonHttpClient.java:1742)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.handleServiceErrorResponse(AmazonHttpClient.java:1371)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeOneRequest(AmazonHttpClient.java:1347)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeHelper(AmazonHttpClient.java:1127)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.doExecute(AmazonHttpClient.java:784)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeWithTimer(AmazonHttpClient.java:752)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.execute(AmazonHttpClient.java:726)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.access$500(AmazonHttpClient.java:686)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutionBuilderImpl.execute(AmazonHttpClient.java:668)
	at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:532)
	at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:512)
	at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:5052)
	at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:4998)
	at com.amazonaws.services.s3.AmazonS3Client.createBucket(AmazonS3Client.java:1094)
	at io.minio.awssdk.tests.FunctionalTests.initTests(Unknown Source)
	at io.minio.awssdk.tests.FunctionalTests.main(Unknown Source)
(2/15) Running aws-sdk-php tests ... FAILED in 0 seconds
PHP Fatal error:  Uncaught exception 'Aws\S3\Exception\S3Exception' with message 'Error executing "DeleteObject" on "http://minio-c3.minio.io:30038/aws-sdk-php-5efa8f9350515/obj1"; AWS HTTP error: Server error: `DELETE http://minio-c3.minio.io:30038/aws-sdk-php-5efa8f9350515/obj1` resulted in a `503 Service Unavailable` response:
<?xml version="1.0" encoding="UTF-8"?>
<Error><Code>XMinioServerNotInitialized</Code><Message>Server not initialized, pl (truncated...)
 XMinioServerNotInitialized (server): Server not initialized, please try again. - <?xml version="1.0" encoding="UTF-8"?>
<Error><Code>XMinioServerNotInitialized</Code><Message>Server not initialized, please try again.</Message><Key>obj1</Key><BucketName>aws-sdk-php-5efa8f9350515</BucketName><Resource>/aws-sdk-php-5efa8f9350515/obj1</Resource><RequestId>161D2CC31A5C6B51</RequestId><HostId>b154c1c4-665d-40fe-b736-f57c80e20855</HostId></Error>'

GuzzleHttp\Exception\ServerException: Server error: `PUT http://minio-c3.minio.io:30038/aws-sdk-php-5efa8f9350515` resulted in  in /mint/run/core/aws-sdk-php/vendor/aws/aws-sdk-php/src/WrappedHttpHandler.php on line 195
(2/15) Running aws-sdk-ruby tests ... FAILED in 3 seconds
{
  "name": "aws-sdk-ruby",
  "function": "listBuckets",
  "args": {},
  "duration": 2130.81,
  "error": "Server not initialized, please try again.",
  "status": "FAIL"
}
(2/15) Running awscli tests ... FAILED in 27 seconds
{
  "name": "awscli",
  "duration": 24713,
  "function": "aws --endpoint-url http://minio-c3.minio.io:30038 s3api head-bucket --bucket awscli-mint-test-bucket-12516\n",
  "status": "FAIL",
  "error": "awscli-mint-test-bucket-12516"
}
(2/15) Running healthcheck tests ... done in 0 seconds
(3/15) Running mc tests ... FAILED in 1 minutes and 41 seconds
{
  "name": "mc",
  "duration": "100033",
  "function": "test_make_bucket",
  "status": "FAIL",
  "error": "/mint/run/core/mc/mc --config-dir /tmp/.mc-27240 --quiet --no-color mb myminio/mc-test-bucket-4114  >>> \nmc: <ERROR> Unable to make bucket `myminio/mc-test-bucket-4114`. Server not initialized, please try again."
}
(3/15) Running minio-dotnet tests ... done in 43 seconds
(4/15) Running minio-go tests ... FAILED in 1 minutes and 38 seconds
{
  "args": {
    "bucketName": "minio-go-test-9c0m3jmixkz9rxl4",
    "fileName": "",
    "objectName": "",
    "opts": ""
  },
  "duration": 94813,
  "error": "Server not initialized, please try again.",
  "function": "FPutObject(bucketName, objectName, fileName, opts)",
  "message": "MakeBucket failed",
  "name": "minio-go: testFPutObjectV2",
  "status": "FAIL"
}
(4/15) Running minio-java tests ... FAILED in 4 minutes and 25 seconds
{
  "name": "minio-java",
  "function": "presignedGetObject(String bucketName, String objectName, Integer expires)",
  "duration": 239,
  "status": "FAIL",
  "error": "java.lang.Exception: failed to read object. Response: Response{protocol=http/1.1, code=503, message=Service Unavailable, url=http://minio-c3.minio.io:30038/minio-java-test-37eh95d/minio-java-test-26h3ieb?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=minio%2F20200630%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20200630T011316Z&X-Amz-Expires=3600&X-Amz-SignedHeaders=host&X-Amz-Signature=5f047ccd9331dd200a820d0eb1959967fc486ffe7a496fe557853d4c1b192481}, Response body: <?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<Error><Code>XMinioServerNotInitialized</Code><Message>Server not initialized, please try again.</Message><Key>minio-java-test-26h3ieb</Key><BucketName>minio-java-test-37eh95d</BucketName><Resource>/minio-java-test-37eh95d/minio-java-test-26h3ieb</Resource><RequestId>161D2D400D08CFF7</RequestId><HostId>b154c1c4-665d-40fe-b736-f57c80e20855</HostId></Error> >>> [FunctionalTest.readObject(FunctionalTest.java:190), FunctionalTest.presignedGetObject_test2(FunctionalTest.java:1967), FunctionalTest.runTests(FunctionalTest.java:4058), FunctionalTest.main(FunctionalTest.java:4192)]"
}
(4/15) Running minio-js tests ... FAILED in 1 seconds
{
  "name": "minio-js",
  "function": "\"after all\" hook in \"functional tests\"",
  "duration": 7,
  "status": "FAIL",
  "error": "S3Error: Server not initialized, please try again. at Object.parseError (node_modules/minio/dist/main/xml-parsers.js:86:11) at /mint/run/core/minio-js/node_modules/minio/dist/main/transformers.js:156:22 at DestroyableTransform._flush (node_modules/minio/dist/main/transformers.js:80:10) at DestroyableTransform.prefinish (node_modules/readable-stream/lib/_stream_transform.js:129:10) at prefinish (node_modules/readable-stream/lib/_stream_writable.js:611:14) at finishMaybe (node_modules/readable-stream/lib/_stream_writable.js:620:5) at endWritable (node_modules/readable-stream/lib/_stream_writable.js:643:3) at DestroyableTransform.Writable.end (node_modules/readable-stream/lib/_stream_writable.js:571:22) at IncomingMessage.onend (_stream_readable.js:673:10) at endReadableNT (_stream_readable.js:1201:12) at processTicksAndRejections (internal/process/task_queues.js:84:21)"
}
(4/15) Running minio-py tests ... FAILED in 10 minutes and 6 seconds
{
  "name": "minio-py:test_presigned_get_object_default_expiry",
  "function": "presigned_get_object(bucket_name, object_name, expires, response_headers, request_date)",
  "args": {
    "bucket_name": "minio-py-test-3eb3ccfd-f100-4d6e-a5bc-187defc76a58",
    "object_name": "7fc99f19-5ff8-4a83-a6b7-68e1ebd6b06a"
  },
  "duration": 361142,
  "message": "ResponseError: code: XMinioServerNotInitialized, message: Server not initialized, please try again., bucket_name: minio-py-test-3eb3ccfd-f100-4d6e-a5bc-187defc76a58, object_name: 7fc99f19-5ff8-4a83-a6b7-68e1ebd6b06a, request_id: 161D2DCD500CC4F6, host_id: b154c1c4-665d-40fe-b736-f57c80e20855, region: ",
  "error": "Traceback (most recent call last):\n  File \"/mint/run/core/minio-py/tests.py\", line 1322, in test_presigned_get_object_default_expiry\n    object_name).get_exception()\nminio.error.ResponseError: ResponseError: code: XMinioServerNotInitialized, message: Server not initialized, please try again., bucket_name: minio-py-test-3eb3ccfd-f100-4d6e-a5bc-187defc76a58, object_name: 7fc99f19-5ff8-4a83-a6b7-68e1ebd6b06a, request_id: 161D2DCD500CC4F6, host_id: b154c1c4-665d-40fe-b736-f57c80e20855, region: \n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"/mint/run/core/minio-py/tests.py\", line 2105, in main\n    test_presigned_get_object_default_expiry(client, log_output)\n  File \"/mint/run/core/minio-py/tests.py\", line 1324, in test_presigned_get_object_default_expiry\n    raise Exception(err)\nException: ResponseError: code: XMinioServerNotInitialized, message: Server not initialized, please try again., bucket_name: minio-py-test-3eb3ccfd-f100-4d6e-a5bc-187defc76a58, object_name: 7fc99f19-5ff8-4a83-a6b7-68e1ebd6b06a, request_id: 161D2DCD500CC4F6, host_id: b154c1c4-665d-40fe-b736-f57c80e20855, region: \n",
  "status": "FAIL"
}
(4/15) Running s3cmd tests ... FAILED in 45 seconds
{
  "name": "s3cmd",
  "duration": "45508",
  "function": "test_make_bucket",
  "status": "FAIL",
  "error": "WARNING: Retrying failed request: / (503 (XMinioServerNotInitialized): Server not initialized, please try again.)\nWARNING: Waiting 3 sec...\nWARNING: Retrying failed request: / (503 (XMinioServerNotInitialized): Server not initialized, please try again.)\nWARNING: Waiting 6 sec...\nWARNING: Retrying failed request: / (503 (XMinioServerNotInitialized): Server not initialized, please try again.)\nWARNING: Waiting 9 sec...\nWARNING: Retrying failed request: / (503 (XMinioServerNotInitialized): Server not initialized, please try again.)\nWARNING: Waiting 12 sec...\nWARNING: Retrying failed request: / (503 (XMinioServerNotInitialized): Server not initialized, please try again.)\nWARNING: Waiting 15 sec...\nERROR: S3 error: 503 (XMinioServerNotInitialized): Server not initialized, please try again."
}
(4/15) Running s3select tests ... FAILED in 1 hours 20 minutes and 7 seconds
{
  "name": "s3select:test_sql_operators",
  "function": "select_object_content(bucket_name, object_name, opts)",
  "args": {
    "total_tests": 20,
    "total_success": 11
  },
  "duration": 4804164,
  "message": "HTTPConnectionPool(host='minio-c3.minio.io', port=30038): Max retries exceeded with url: /s3select-test-74a0eedf-c61e-491c-876c-85a889f50c0a/ (Caused by ResponseError('too many 503 error responses',))",
  "error": "Traceback (most recent call last):\n  File \"./tests.py\", line 51, in main\n    test_sql_operators(client, log_output)\n  File \"/mint/run/core/s3select/sql_ops.py\", line 131, in test_sql_operators\n    raise select_err\n  File \"/mint/run/core/s3select/sql_ops.py\", line 129, in test_sql_operators\n    test_sql_expressions(client, json_testfile, tests, log_output)\n  File \"/mint/run/core/s3select/sql_ops.py\", line 89, in test_sql_expressions\n    input_serialization, output_serialization, tests, log_output)\n  File \"/mint/run/core/s3select/sql_ops.py\", line 75, in test_sql_expressions_custom_input_output\n    client.remove_bucket(bucket_name)\n  File \"/usr/local/lib/python3.6/dist-packages/minio/api.py\", line 446, in remove_bucket\n    self._url_open('DELETE', bucket_name=bucket_name)\n  File \"/usr/local/lib/python3.6/dist-packages/minio/api.py\", line 2000, in _url_open\n    preload_content=preload_content)\n  File \"/usr/local/lib/python3.6/dist-packages/urllib3/poolmanager.py\", line 336, in urlopen\n    response = conn.urlopen(method, u.request_uri, **kw)\n  File \"/usr/local/lib/python3.6/dist-packages/urllib3/connectionpool.py\", line 828, in urlopen\n    **response_kw\n  File \"/usr/local/lib/python3.6/dist-packages/urllib3/connectionpool.py\", line 828, in urlopen\n    **response_kw\n  File \"/usr/local/lib/python3.6/dist-packages/urllib3/connectionpool.py\", line 828, in urlopen\n    **response_kw\n  [Previous line repeated 2 more times]\n  File \"/usr/local/lib/python3.6/dist-packages/urllib3/connectionpool.py\", line 805, in urlopen\n    retries = retries.increment(method, url, response=response, _pool=self)\n  File \"/usr/local/lib/python3.6/dist-packages/urllib3/util/retry.py\", line 439, in increment\n    raise MaxRetryError(_pool, url, error or ResponseError(cause))\nurllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='minio-c3.minio.io', port=30038): Max retries exceeded with url: /s3select-test-74a0eedf-c61e-491c-876c-85a889f50c0a/ (Caused by ResponseError('too many 503 error responses',))\n",
  "status": "FAIL"
}
(4/15) Running security tests ... done in 0 seconds

Executed 4 out of 15 tests successfully.
```
<a name="3b5d5710-56c0-4162-9628-79552199e3f9"></a>
### 9938-d6356da/mint-large-bucket.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-dev4.minio.io:32720
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp c25225d42286:/mint/log /tmp/mint-logs'

(1/15) Running aws-sdk-go tests ... done in 57 seconds
(2/15) Running aws-sdk-java tests ... done in 7 seconds
(3/15) Running aws-sdk-php tests ... done in 1 minutes and 45 seconds
(4/15) Running aws-sdk-ruby tests ... done in 2 minutes and 40 seconds
(5/15) Running awscli tests ... done in 3 minutes and 49 seconds
(6/15) Running healthcheck tests ... done in 0 seconds
(7/15) Running mc tests ... done in 1 minutes and 14 seconds
(8/15) Running minio-dotnet tests ... done in 6 minutes and 5 seconds
(9/15) Running minio-go tests ... FAILED in 8 minutes and 0 seconds
{
  "args": {
    "bucketName": "minio-go-test-orwkw6dsin2jpe6s",
    "objectName": "v4o33m0ljyvn9v96ti0t90kkjtixzc",
    "objectPrefix": "",
    "recursive": "true"
  },
  "duration": 10816,
  "error": "The bucket you tried to delete is not empty. You must delete all versions in the bucket.",
  "function": "RemoveObjectsWithOptions(bucketName, objectsCh, opts)",
  "message": "Cleanup failed",
  "name": "minio-go: testRemoveObjectsWithOptions",
  "status": "FAIL"
}
(9/15) Running minio-java tests ... FAILED in 14 minutes and 23 seconds
{
  "name": "minio-java",
  "function": "enableObjectLegalHold(String bucketName, String objectName, String versionId)",
  "duration": 5080,
  "status": "FAIL",
  "error": "error occurred\nErrorResponse(code = BucketNotEmpty, message = The bucket you tried to delete is not empty. You must delete all versions in the bucket., bucketName = minio-java-test-36uicej, objectName = null, resource = /minio-java-test-36uicej, requestId = 161D2E840E449F23, hostId = 157f276a-6063-401f-8f97-9ee1b766f11d)\nrequest={method=DELETE, url=http://minio-dev4.minio.io:32720/minio-java-test-36uicej, headers=Host: minio-dev4.minio.io:32720\nAccept-Encoding: identity\nUser-Agent: MinIO (amd64; amd64) minio-java/dev\nContent-MD5: 1B2M2Y8AsgTpgAmY7PhCfg==\nx-amz-content-sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855\nx-amz-date: 20200630T013627Z\nAuthorization: AWS4-HMAC-SHA256 Credential=*REDACTED*/20200630/us-east-1/s3/aws4_request, SignedHeaders=accept-encoding;content-md5;host;x-amz-content-sha256;x-amz-date, Signature=*REDACTED*\n}\nresponse={code=409, headers=Accept-Ranges: bytes\nContent-Length: 373\nContent-Security-Policy: block-all-mixed-content\nContent-Type: application/xml\nServer: MinIO/DEVELOPMENT.2020-06-30T00-51-35Z\nVary: Origin\nX-Amz-Request-Id: 161D2E840E449F23\nX-Xss-Protection: 1; mode=block\nDate: Tue, 30 Jun 2020 01:36:27 GMT\n}\n >>> [io.minio.MinioClient.execute(MinioClient.java:1211), io.minio.MinioClient.execute(MinioClient.java:1236), io.minio.MinioClient.executeDelete(MinioClient.java:1366), io.minio.MinioClient.removeBucket(MinioClient.java:3686), FunctionalTest.enableObjectLegalHold_test(FunctionalTest.java:3314), FunctionalTest.runTests(FunctionalTest.java:4079), FunctionalTest.main(FunctionalTest.java:4192)]"
}
(9/15) Running minio-js tests ... done in 1 minutes and 32 seconds
(10/15) Running minio-py tests ... done in 20 minutes and 54 seconds
(11/15) Running s3cmd tests ... done in 52 seconds
(12/15) Running s3select tests ... done in 1 minutes and 21 seconds
(13/15) Running security tests ... done in 0 seconds

Executed 13 out of 15 tests successfully.
```
<a name="26d69496-6f00-49ba-9f34-321eea65970c"></a>
### 9938-d6356da/mint-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-dev4.minio.io:31506
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 21b1e427eeb6:/mint/log /tmp/mint-logs'

(1/15) Running aws-sdk-go tests ... done in 8 seconds
(2/15) Running aws-sdk-java tests ... done in 2 seconds
(3/15) Running aws-sdk-php tests ... done in 44 seconds
(4/15) Running aws-sdk-ruby tests ... done in 5 seconds
(5/15) Running awscli tests ... done in 2 minutes and 29 seconds
(6/15) Running healthcheck tests ... done in 0 seconds
(7/15) Running mc tests ... done in 1 minutes and 32 seconds
(8/15) Running minio-dotnet tests ... done in 1 minutes and 51 seconds
(9/15) Running minio-go tests ... FAILED in 1 minutes and 58 seconds
{
  "args": {
    "bucketName": "minio-go-test-bkvxvbtdwu6mbtlm",
    "objectName": "oz62p2iolqn65lskotik9kd6kkiz3j",
    "objectPrefix": "",
    "recursive": "true"
  },
  "duration": 2966,
  "error": "The bucket you tried to delete is not empty. You must delete all versions in the bucket.",
  "function": "RemoveObjectsWithOptions(bucketName, objectsCh, opts)",
  "message": "Cleanup failed",
  "name": "minio-go: testRemoveObjectsWithOptions",
  "status": "FAIL"
}
(9/15) Running minio-java tests ... FAILED in 3 minutes and 17 seconds
{
  "name": "minio-java",
  "function": "enableObjectLegalHold(String bucketName, String objectName, String versionId)",
  "duration": 458,
  "status": "FAIL",
  "error": "error occurred\nErrorResponse(code = BucketNotEmpty, message = The bucket you tried to delete is not empty. You must delete all versions in the bucket., bucketName = minio-java-test-1n02qun, objectName = null, resource = /minio-java-test-1n02qun, requestId = 161D2D0C7C987A4C, hostId = c159dac5-780d-41bc-9967-339c1a738701)\nrequest={method=DELETE, url=http://minio-dev4.minio.io:31506/minio-java-test-1n02qun, headers=Host: minio-dev4.minio.io:31506\nAccept-Encoding: identity\nUser-Agent: MinIO (amd64; amd64) minio-java/dev\nContent-MD5: 1B2M2Y8AsgTpgAmY7PhCfg==\nx-amz-content-sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855\nx-amz-date: 20200630T010934Z\nAuthorization: AWS4-HMAC-SHA256 Credential=*REDACTED*/20200630/us-east-1/s3/aws4_request, SignedHeaders=accept-encoding;content-md5;host;x-amz-content-sha256;x-amz-date, Signature=*REDACTED*\n}\nresponse={code=409, headers=Accept-Ranges: bytes\nContent-Length: 373\nContent-Security-Policy: block-all-mixed-content\nContent-Type: application/xml\nServer: MinIO/DEVELOPMENT.2020-06-30T00-51-35Z\nVary: Origin\nX-Amz-Request-Id: 161D2D0C7C987A4C\nX-Xss-Protection: 1; mode=block\nDate: Tue, 30 Jun 2020 01:09:34 GMT\n}\n >>> [io.minio.MinioClient.execute(MinioClient.java:1211), io.minio.MinioClient.execute(MinioClient.java:1236), io.minio.MinioClient.executeDelete(MinioClient.java:1366), io.minio.MinioClient.removeBucket(MinioClient.java:3686), FunctionalTest.enableObjectLegalHold_test(FunctionalTest.java:3314), FunctionalTest.runTests(FunctionalTest.java:4079), FunctionalTest.main(FunctionalTest.java:4192)]"
}
(9/15) Running minio-js tests ... done in 52 seconds
(10/15) Running minio-py tests ... done in 5 minutes and 20 seconds
(11/15) Running s3cmd tests ... done in 22 seconds
(12/15) Running s3select tests ... done in 9 seconds
(13/15) Running security tests ... done in 0 seconds

Executed 13 out of 15 tests successfully.
```
<a name="6318146b-dbfd-4033-9653-1471b476ed12"></a>
### 9938-d6356da/mint-zoned.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-dev3.minio.io:31412
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 33343e4ee9c6:/mint/log /tmp/mint-logs'

(1/15) Running aws-sdk-go tests ... done in 1 minutes and 34 seconds
(2/15) Running aws-sdk-java tests ... done in 16 seconds
(3/15) Running aws-sdk-php tests ... done in 1 minutes and 52 seconds
(4/15) Running aws-sdk-ruby tests ... done in 3 minutes and 33 seconds
(5/15) Running awscli tests ... FAILED in 2 minutes and 22 seconds
{
  "name": "awscli",
  "duration": 31495,
  "function": "aws --endpoint-url http://minio-dev3.minio.io:31412 s3api copy-object --bucket awscli-mint-test-bucket-27845 --storage-class REDUCED_REDUNDANCY --key datafile-1-kB-copy --copy-source awscli-mint-test-bucket-27845/datafile-1-kB\n",
  "status": "FAIL",
  "error": "An error occurred (SlowDown) when calling the CopyObject operation (reached max retries: 4): Please reduce your request"
}
(5/15) Running healthcheck tests ... done in 1 seconds
(6/15) Running mc tests ... FAILED in 3 minutes and 5 seconds
{
  "name": "mc",
  "duration": "95235",
  "function": "test_mirror_list_objects_storage_class",
  "status": "FAIL",
  "error": "/mint/run/core/mc/mc --config-dir /tmp/.mc-30163 --quiet --no-color mirror --storage-class REDUCED_REDUNDANCY /mint/data myminio/mc-test-bucket-29067  >>> \n`/mint/data/datafile-1-MB` -> `myminio/mc-test-bucket-29067/datafile-1-MB`\n`/mint/data/datafile-0-b` -> `myminio/mc-test-bucket-29067/datafile-0-b`\n`/mint/data/datafile-1-b` -> `myminio/mc-test-bucket-29067/datafile-1-b`\n`/mint/data/datafile-1-kB` -> `myminio/mc-test-bucket-29067/datafile-1-kB`\n`/mint/data/datafile-1.03-MB` -> `myminio/mc-test-bucket-29067/datafile-1.03-MB`\n`/mint/data/datafile-10-MB` -> `myminio/mc-test-bucket-29067/datafile-10-MB`\n`/mint/data/datafile-100-kB` -> `myminio/mc-test-bucket-29067/datafile-100-kB`\n`/mint/data/datafile-10-kB` -> `myminio/mc-test-bucket-29067/datafile-10-kB`\n`/mint/data/datafile-33-kB` -> `myminio/mc-test-bucket-29067/datafile-33-kB`\n`/mint/data/datafile-129-MB` -> `myminio/mc-test-bucket-29067/datafile-129-MB`\n`/mint/data/datafile-5243880-b` -> `myminio/mc-test-bucket-29067/datafile-5243880-b`\n`/mint/data/datafile-5-MB` -> `myminio/mc-test-bucket-29067/datafile-5-MB`\n`/mint/data/datafile-11-MB` -> `myminio/mc-test-bucket-29067/datafile-11-MB`\n`/mint/data/datafile-65-MB` -> `myminio/mc-test-bucket-29067/datafile-65-MB`\n`/mint/data/datafile-6-MB` -> `myminio/mc-test-bucket-29067/datafile-6-MB`\nmc: <ERROR> Failed to copy `/mint/data/datafile-0-b`. Please reduce your request\nTotal: 0 B, Transferred: 544.16 MiB, Speed: 6.24 MiB/s"
}
(6/15) Running minio-dotnet tests ... done in 9 minutes and 18 seconds
(7/15) Running minio-go tests ... FAILED in 12 minutes and 7 seconds
{
  "args": {
    "bucketName": "minio-go-test-9ohhla1t3mu5o9lh",
    "objectName": "kjq19izz10ldvkfclt9qbn9i6sg999",
    "objectPrefix": "",
    "recursive": "true"
  },
  "duration": 11161,
  "error": "The bucket you tried to delete is not empty. You must delete all versions in the bucket.",
  "function": "RemoveObjectsWithOptions(bucketName, objectsCh, opts)",
  "message": "Cleanup failed",
  "name": "minio-go: testRemoveObjectsWithOptions",
  "status": "FAIL"
}
(7/15) Running minio-java tests ... FAILED in 45 seconds
{
  "name": "minio-java",
  "function": "putObject(String bucketName, String objectName, InputStream stream, PutObjectOptions options)",
  "args": "X-Amz-Storage-Class: REDUCED_REDUNDANCY",
  "duration": 593,
  "status": "FAIL",
  "error": "error occurred\nErrorResponse(code = SlowDown, message = Please reduce your request, bucketName = minio-java-test-glh5o0, objectName = minio-java-test-8g8ddq, resource = /minio-java-test-glh5o0/minio-java-test-8g8ddq, requestId = 161D2E4A4A3495ED, hostId = e7d04a96-ac33-426b-9552-8b364ba740e3)\nrequest={method=POST, url=http://minio-dev3.minio.io:31412/minio-java-test-glh5o0/minio-java-test-8g8ddq?uploads=, headers=X-Amz-Storage-Class: REDUCED_REDUNDANCY\nContent-Type: application/octet-stream\nHost: minio-dev3.minio.io:31412\nAccept-Encoding: identity\nUser-Agent: MinIO (amd64; amd64) minio-java/dev\nContent-MD5: 1B2M2Y8AsgTpgAmY7PhCfg==\nx-amz-content-sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855\nx-amz-date: 20200630T013219Z\nAuthorization: AWS4-HMAC-SHA256 Credential=*REDACTED*/20200630/us-east-1/s3/aws4_request, SignedHeaders=accept-encoding;content-md5;host;x-amz-content-sha256;x-amz-date;x-amz-storage-class, Signature=*REDACTED*\n}\nresponse={code=503, headers=Accept-Ranges: bytes\nContent-Length: 359\nContent-Security-Policy: block-all-mixed-content\nContent-Type: application/xml\nRetry-After: 120\nServer: MinIO/DEVELOPMENT.2020-06-30T00-51-35Z\nVary: Origin\nX-Amz-Request-Id: 161D2E4A4A3495ED\nX-Xss-Protection: 1; mode=block\nDate: Tue, 30 Jun 2020 01:32:20 GMT\n}\n >>> [io.minio.MinioClient.execute(MinioClient.java:1211), io.minio.MinioClient.execute(MinioClient.java:1236), io.minio.MinioClient.executePost(MinioClient.java:1388), io.minio.MinioClient.createMultipartUpload(MinioClient.java:5092), io.minio.MinioClient.putObject(MinioClient.java:3708), io.minio.MinioClient.putObject(MinioClient.java:3870), FunctionalTest.putObject_test9(FunctionalTest.java:697), FunctionalTest.runTests(FunctionalTest.java:4027), FunctionalTest.main(FunctionalTest.java:4192)]"
}
(7/15) Running minio-js tests ... done in 1 minutes and 57 seconds
(8/15) Running minio-py tests ... done in 31 minutes and 1 seconds
(9/15) Running s3cmd tests ... done in 46 seconds
(10/15) Running s3select tests ... done in 1 minutes and 18 seconds
(11/15) Running security tests ... done in 0 seconds

Executed 11 out of 15 tests successfully.
```
Deleting image on docker hub
Deleting image locally
