### PR TITLE
getCertsPath should use getConfigPath instead of defaulting to users homedir.

### LINKED ISSUE #2028: Different certificates directory for differents '-config-dir' are not working.
## Expected behaviour

I set -config-dir=${APP_CONFIG_DIR}, then I suppose that ${APP_CONFIG_DIR}/certs should be the certificates directory of Minio.
## Actual behaviour

But It Always point to ${HOME_DIR}/.minio/certs
## Steps to reproduce the behaviour

Set your certificates in ~/.minio/certs (private.key and public.crt)
Put two minio servers working at same time passing a different config-dir to one of them.

Both of them will use the certificates in ~/.minio/certs
## System information

Windows 10 64-bit. Go 1.6.2

### PR DESCRIPTION
**Pull request by dnp1**
Considering that "-certs-path' is not a flag, I assume that it is always a subpath from '-config-dir', so I changed getCertsPath to call getConfigPath instead of homeDir directly.

### CODE REVIEW

File: globals.go [hunk 1]
```diff
@@ -33,6 +33,7 @@ const (
 	globalMinioConfigFile    = "config.json"
 	globalMinioProfilePath   = "profile"
 	// Add new global values here.
+	globalMinioCertsDirname = "certs"
```
Comment (harshavardhana) [inline globals.go]: You could use 'globalMinioCertsDir' which is already defined.

**Comment by harshavardhana** [comment]
LGTM, Thanks :+1:
