### PR TITLE
xl: CompleteMultipartUpload make sure to delete uploads.json

### LINKED ISSUE #1537: Rare bug: uploaded file is corrupted
```
~/w/gospace/src/github.com/minio/mc $ mc rm myminio/bucket1/1gb.bin
Removed ‘myminio/bucket1/1gb.bin’.
~/w/gospace/src/github.com/minio/mc $ mc session resume TGbiAkQk
mc: <ERROR> Session ‘TGbiAkQk’ not found. 
~/w/gospace/src/github.com/minio/mc $ mc cp 1gb.bin myminio/bucket1
mc: <ERROR> Failed to copy ‘1gb.bin’. Object key is missing, object key cannot be empty
1gb.bin:                             1024.00 MB / 1024.00 MB ┃▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓┃ 100.00 % 24.54 MB41s
~/w/gospace/src/github.com/minio/mc $ mc ls myminio/bucket1/
[2016-05-08 20:17:06 CET] 4.0GiB 4gb.bin
[2016-05-08 20:05:54 CET] 8.0GiB 8gb.bin
[2016-05-08 20:32:48 CET]     0B 1gb.bin/
~/w/gospace/src/github.com/minio/mc $ mc ls myminio/bucket1/1gb.bin/
mc: <ERROR> Unable to stat ‘myminio/bucket1/1gb.bin/’. Requested file ‘/bucket1/1gb.bin/’ not found
~/w/gospace/src/github.com/minio/mc $ 
```

I didn't touch anything after this bug so we can be sure when we debug

### PR DESCRIPTION
**Pull request by harshavardhana**
Fixes #1537

### CODE REVIEW

File: xl-objects-multipart.go [hunk 1]
```diff
@@ -222,22 +220,20 @@ func (xl xlObjects) CompleteMultipartUpload(bucket string, object string, upload
...
 			return "", toObjectErr(err, minioMetaBucket, tempUploadIDPath)
 		}
-		return s3MD5, nil
-	}
-	// Rename if failed attempt to delete the original file.
-	err = xl.storage.DeleteFile(minioMetaBucket, uploadIDPath)
-	if err != nil {
-		return "", toObjectErr(err, minioMetaBucket, uploadIDPath)
+	} else {
+		// If Rename failed control reaches here, delete the original file.
```
Comment (krishnasrinivas) [inline xl-objects-multipart.go]: If rename from orig->tmp failed we are supposed to rename it back tmp->orig right?

**Comment by harshavardhana** [comment]
> If rename from orig->tmp failed we are supposed to rename it back tmp->orig right?

Rename failed means it failed, i don't know tmp->orig makes sense.  That would throw errFileNotFound.  Assumption is Rename is atomic.

**Comment by harshavardhana** [comment]
> If rename from orig->tmp failed we are supposed to rename it back tmp->orig right?
> Rename failed means it failed, i don't know tmp->orig makes sense. That would throw errFileNotFound. Assumption is Rename is atomic.

Atleast from the code point of view, it is assumed here that all parts have been moved successfully. This is only to remove the placeholder file which is not needed anymore.

File: xl-objects-multipart.go [hunk 2]
```diff
@@ -222,22 +222,20 @@ func (xl xlObjects) CompleteMultipartUpload(bucket string, object string, upload
...
-	}
-	// Rename if failed attempt to delete the original file.
 	err = xl.storage.DeleteFile(minioMetaBucket, uploadIDPath)
 	if err != nil {
 		return "", toObjectErr(err, minioMetaBucket, uploadIDPath)
 	}
 
+	// Validate if there are other incomplete upload-id's present for
+	// the object, if yes do not attempt to delete 'uploads.json'.
+	if entries, err := xl.storage.ListDir(minioMetaBucket, path.Join(mpartMetaPrefix, bucket, object)); err == nil {
```
Comment (krishnasrinivas) [inline xl-objects-multipart.go]: need to hold a lock because just after ListDir someone might have done initiate-new-multipart-upload

File: xl-objects-multipart.go [hunk 3]
```diff
@@ -187,6 +173,27 @@ func (xl xlObjects) CompleteMultipartUpload(bucket string, object string, upload
...
+	err = xl.storage.DeleteFile(minioMetaBucket, uploadIDPath)
+	if err != nil {
+		return "", toObjectErr(err, minioMetaBucket, uploadIDPath)
+	}
+
+	// Validate if there are other incomplete upload-id's present for
+	// the object, if yes do not attempt to delete 'uploads.json'.
+	var entries []string
+	if entries, err = xl.storage.ListDir(minioMetaBucket, path.Join(mpartMetaPrefix, bucket, object)); err == nil {
+		if len(entries) > 1 {
```
Comment (krishnasrinivas) [inline xl-objects-multipart.go:225]: `multipartMetaFile` should be created at the original location before returning.

**Comment by harshavardhana** [comment]
> multipartMetaFile should be created at the original location before returning.

why? should we create for error conditions - only if CompleteMultipart is successful we should.

**Comment by krishnasrinivas** [comment]
> > multipartMetaFile should be created at the original location before returning.
> > why? should we create for error conditions - only if CompleteMultipart is successful we should.

not for error conditions, but when you return here:

```
+   if entries, err = xl.storage.ListDir(minioMetaBucket, path.Join(mpartMetaPrefix, bucket, object)); err == nil {
+       if len(entries) > 1 {
```

i.e even if there are other multipart uploads for the same object going on, this CompleteMultipartUpload should create the `multipartMetaFile` metadata file as it has successfully completed its operation.

**Comment by harshavardhana** [comment]
> not for error conditions, but when you return here:
> -   if entries, err = xl.storage.ListDir(minioMetaBucket, path.Join(mpartMetaPrefix, bucket, object)); err == nil {
> -       if len(entries) > 1 {
>   i.e even if there are other multipart uploads for the same object going on, this CompleteMultipartUpload should create the multipartMetaFile metadata file as it has successfully completed its operation.

Moved it up! as the first thing to finish before even renaming so that we can see if it's corrupted and be able to delete it.

**Comment by krishnasrinivas** [comment]
@harshavardhana you forgot to push the changes i think
