### PR TITLE
Avoid duplicate object holding locks

### LINKED ISSUE #9866: DeleteObjects API times out for deleting object versions
When running below `minio-java` test, server fails to return response and make the test timing out.

```java
import io.minio.*;
import io.minio.messages.*;
import java.io.*;
import java.util.*;

public class Check {
  public static void main(String[] args) throws Exception {
    MinioClient client = new MinioClient(args[0], args[1], args[2]);

    client.makeBucket(MakeBucketArgs.builder().bucket("bala-test-bucket2").build());
    client.enableVersioning(EnableVersioningArgs.builder().bucket("bala-test-bucket2").build());

    ObjectWriteResponse v1 =
        client.putObject(
            PutObjectArgs.builder().bucket("bala-test-bucket2").object("my-object").stream(
                    new ByteArrayInputStream(new byte[] {'a'}), 1, -1)
                .build());

    ObjectWriteResponse v2 =
        client.putObject(
            PutObjectArgs.builder().bucket("bala-test-bucket2").object("my-object").stream(
                    new ByteArrayInputStream(new byte[] {'b'}), 1, -1)
                .build());

    List<DeleteObject> objects = new LinkedList<>();
    objects.add(new DeleteObject("my-object", v1.versionId()));
    objects.add(new DeleteObject("my-object", v2.versionId()));

    System.out.println(
        "Removing my-object and it's versions [" + v1.versionId() + ", " + v2.versionId() + "]");

    for (Result<DeleteError> result :
        client.removeObjects(
            RemoveObjectsArgs.builder().bucket("bala-test-bucket2").objects(objects).build())) {
      DeleteError error = result.get();
      System.out.println("Error in deleting object " + error.objectName() + "; " + error.message());
    }

    client.removeBucket(RemoveBucketArgs.builder().bucket("bala-test-bucket2").build());
  }
}
```
```java
Removing my-object and it's versions [5149ee3a-0388-4dd6-887c-3cf669075e02, 2df77c34-2ab9-4bad-b802-92b76c094ba5]
Exception in thread "main" java.net.SocketTimeoutException: timeout
	at okio.Okio$4.newTimeoutException(Okio.java:232)
	at okio.AsyncTimeout.exit(AsyncTimeout.java:286)
	at okio.AsyncTimeout$2.read(AsyncTimeout.java:241)
	at okio.RealBufferedSource.indexOf(RealBufferedSource.java:358)
	at okio.RealBufferedSource.readUtf8LineStrict(RealBufferedSource.java:230)
	at okhttp3.internal.http1.Http1ExchangeCodec.readHeaderLine(Http1ExchangeCodec.java:242)
	at okhttp3.internal.http1.Http1ExchangeCodec.readResponseHeaders(Http1ExchangeCodec.java:213)
	at okhttp3.internal.connection.Exchange.readResponseHeaders(Exchange.java:115)
	at okhttp3.internal.http.CallServerInterceptor.intercept(CallServerInterceptor.java:94)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
	at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:43)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117)
	at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:94)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117)
	at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
	at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:88)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117)
	at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:229)
	at okhttp3.RealCall.execute(RealCall.java:81)
	at io.minio.MinioClient.execute(MinioClient.java:1258)
	at io.minio.MinioClient.execute(MinioClient.java:1406)
	at io.minio.MinioClient.executePost(MinioClient.java:1574)
	at io.minio.MinioClient.deleteObjects(MinioClient.java:7629)
	at io.minio.MinioClient$1$1.populate(MinioClient.java:3320)
	at io.minio.MinioClient$1$1.hasNext(MinioClient.java:3352)
	at Check.main(Check.java:33)
Caused by: java.net.SocketException: Socket closed
	at java.net.SocketInputStream.read(SocketInputStream.java:204)
	at java.net.SocketInputStream.read(SocketInputStream.java:141)
	at okio.Okio$2.read(Okio.java:140)
	at okio.AsyncTimeout$2.read(AsyncTimeout.java:237)
	... 27 more
```

The same test works fine with AWS S3.

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Version used (`minio version`): Development build using commit id `72743d15902717bbf656e4b7159c5e894b8c5312`
* Environment name and version (e.g. nginx 1.9.1):
* Server type and version: `rm -fr ~/tmp/ed{1..4}; MINIO_ACCESS_KEY=minio MINIO_SECRET_KEY=minio123 ./minio server ~/tmp/ed{1..4}`
* Operating System and version (`uname -a`):
* Link to your project:

### PR DESCRIPTION
**Pull request by harshavardhana**
## Description
Avoid duplicate object holding locks

## Motivation and Context
Fixes #9866

## How to test this PR?
As mentioned in the issue #9866 

## Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [ ] Fixes a regression (If yes, please add `commit-id` or `PR #` here)
- [ ] Documentation needed
- [ ] Unit tests needed
- [ ] Functional tests needed (If yes, add [mint](https://github.com/minio/mint) PR # here: )

### CODE REVIEW

**Comment by minio-trusted** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-s3.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-xl.sh | :x: [more...](#79815e3d-fa88-4b3c-9d49-f1a5cbd5a19c) |
| mint-large-bucket.sh | :x: [more...](#b926d41a-f037-436c-be5f-ee19b777c516) |
| mint-dist-xl.sh | :x: [more...](#3adc26fc-8191-40c1-9136-b250e49c6f63) |
| mint-gateway-azure.sh | :x: [more...](#b885a9e3-829a-401c-92ba-7c917afecc6b) |
<a name="3adc26fc-8191-40c1-9136-b250e49c6f63"></a>
### 9867-19eec7e/mint-dist-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-dev6.minio.io:30797
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 9e7180e687e7:/mint/log /tmp/mint-logs'

(1/15) Running aws-sdk-go tests ... done in 2 seconds
(2/15) Running aws-sdk-java tests ... done in 1 seconds
(3/15) Running aws-sdk-php tests ... done in 43 seconds
(4/15) Running aws-sdk-ruby tests ... done in 3 seconds
(5/15) Running awscli tests ... done in 1 minutes and 27 seconds
(6/15) Running healthcheck tests ... done in 0 seconds
(7/15) Running mc tests ... done in 33 seconds
(8/15) Running minio-dotnet tests ... done in 51 seconds
(9/15) Running minio-go tests ... FAILED in 1 minutes and 55 seconds
{
  "args": {
    "bucketName": "minio-go-test-060x2xpnj61eqt6d",
    "objectName": "vu43d9q9n0zix3dz5ch54f5hj6vjad",
    "objectPrefix": "",
    "recursive": "true"
  },
  "duration": 3633,
  "error": "The bucket you tried to delete is not empty. You must delete all versions in the bucket.",
  "function": "RemoveObjectsWithOptions(bucketName, objectsCh, opts)",
  "message": "Cleanup failed",
  "name": "minio-go: testRemoveObjectsWithOptions",
  "status": "FAIL"
}
(9/15) Running minio-java tests ... FAILED in 2 minutes and 25 seconds
{
  "name": "minio-java",
  "function": "enableObjectLegalHold(String bucketName, String objectName, String versionId)",
  "duration": 279,
  "status": "FAIL",
  "error": "error occurred\nErrorResponse(code = BucketNotEmpty, message = The bucket you tried to delete is not empty. You must delete all versions in the bucket., bucketName = minio-java-test-2eqf3jt, objectName = null, resource = /minio-java-test-2eqf3jt, requestId = 16198B8C92771926, hostId = d373883f-7c65-446c-b0e3-7cd0df07da26)\nrequest={method=DELETE, url=http://minio-dev6.minio.io:30797/minio-java-test-2eqf3jt, headers=Host: minio-dev6.minio.io:30797\nAccept-Encoding: identity\nUser-Agent: MinIO (amd64; amd64) minio-java/dev\nContent-MD5: 1B2M2Y8AsgTpgAmY7PhCfg==\nx-amz-content-sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855\nx-amz-date: 20200618T051619Z\nAuthorization: AWS4-HMAC-SHA256 Credential=*REDACTED*/20200618/us-east-1/s3/aws4_request, SignedHeaders=accept-encoding;content-md5;host;x-amz-content-sha256;x-amz-date, Signature=*REDACTED*\n}\nresponse={code=409, headers=Accept-Ranges: bytes\nContent-Length: 373\nContent-Security-Policy: block-all-mixed-content\nContent-Type: application/xml\nServer: MinIO/DEVELOPMENT.2020-06-18T05-02-21Z\nVary: Origin\nX-Amz-Request-Id: 16198B8C92771926\nX-Xss-Protection: 1; mode=block\nDate: Thu, 18 Jun 2020 05:16:19 GMT\n}\n >>> [io.minio.MinioClient.execute(MinioClient.java:1211), io.minio.MinioClient.execute(MinioClient.java:1236), io.minio.MinioClient.executeDelete(MinioClient.java:1366), io.minio.MinioClient.removeBucket(MinioClient.java:3686), FunctionalTest.enableObjectLegalHold_test(FunctionalTest.java:3314), FunctionalTest.runTests(FunctionalTest.java:4079), FunctionalTest.main(FunctionalTest.java:4192)]"
}
(9/15) Running minio-js tests ... done in 49 seconds
(10/15) Running minio-py tests ... done in 2 minutes and 25 seconds
(11/15) Running s3cmd tests ... done in 22 seconds
(12/15) Running s3select tests ... done in 5 seconds
(13/15) Running security tests ... done in 0 seconds

Executed 13 out of 15 tests successfully.
```
<a name="79815e3d-fa88-4b3c-9d49-f1a5cbd5a19c"></a>
### 9867-19eec7e/mint-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-c3.minio.io:32588
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 8fb77e1db774:/mint/log /tmp/mint-logs'

(1/15) Running aws-sdk-go tests ... done in 0 seconds
(2/15) Running aws-sdk-java tests ... done in 2 seconds
(3/15) Running aws-sdk-php tests ... done in 41 seconds
(4/15) Running aws-sdk-ruby tests ... done in 3 seconds
(5/15) Running awscli tests ... done in 2 minutes and 18 seconds
(6/15) Running healthcheck tests ... done in 0 seconds
(7/15) Running mc tests ... done in 53 seconds
(8/15) Running minio-dotnet tests ... done in 35 seconds
(9/15) Running minio-go tests ... FAILED in 1 minutes and 10 seconds
{
  "args": {
    "bucketName": "minio-go-test-5gzqad6z9oppwv2f",
    "objectName": "x6vozzd4opnflrni14dmaon4d02ns3",
    "objectPrefix": "",
    "recursive": "true"
  },
  "duration": 4352,
  "error": "The bucket you tried to delete is not empty. You must delete all versions in the bucket.",
  "function": "RemoveObjectsWithOptions(bucketName, objectsCh, opts)",
  "message": "Cleanup failed",
  "name": "minio-go: testRemoveObjectsWithOptions",
  "status": "FAIL"
}
(9/15) Running minio-java tests ... FAILED in 51 seconds
{
  "name": "minio-java",
  "function": "enableObjectLegalHold(String bucketName, String objectName, String versionId)",
  "duration": 104,
  "status": "FAIL",
  "error": "error occurred\nErrorResponse(code = BucketNotEmpty, message = The bucket you tried to delete is not empty. You must delete all versions in the bucket., bucketName = minio-java-test-2at5dfc, objectName = null, resource = /minio-java-test-2at5dfc, requestId = 16198B785414CFA7, hostId = 2832cc44-144d-4bb1-a48e-b434d005b1d7)\nrequest={method=DELETE, url=http://minio-c3.minio.io:32588/minio-java-test-2at5dfc, headers=Host: minio-c3.minio.io:32588\nAccept-Encoding: identity\nUser-Agent: MinIO (amd64; amd64) minio-java/dev\nContent-MD5: 1B2M2Y8AsgTpgAmY7PhCfg==\nx-amz-content-sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855\nx-amz-date: 20200618T051452Z\nAuthorization: AWS4-HMAC-SHA256 Credential=*REDACTED*/20200618/us-east-1/s3/aws4_request, SignedHeaders=accept-encoding;content-md5;host;x-amz-content-sha256;x-amz-date, Signature=*REDACTED*\n}\nresponse={code=409, headers=Accept-Ranges: bytes\nContent-Length: 373\nContent-Security-Policy: block-all-mixed-content\nContent-Type: application/xml\nServer: MinIO/DEVELOPMENT.2020-06-18T05-02-21Z\nVary: Origin\nX-Amz-Request-Id: 16198B785414CFA7\nX-Xss-Protection: 1; mode=block\nDate: Thu, 18 Jun 2020 05:14:52 GMT\n}\n >>> [io.minio.MinioClient.execute(MinioClient.java:1211), io.minio.MinioClient.execute(MinioClient.java:1236), io.minio.MinioClient.executeDelete(MinioClient.java:1366), io.minio.MinioClient.removeBucket(MinioClient.java:3686), FunctionalTest.enableObjectLegalHold_test(FunctionalTest.java:3314), FunctionalTest.runTests(FunctionalTest.java:4079), FunctionalTest.main(FunctionalTest.java:4192)]"
}
(9/15) Running minio-js tests ... done in 45 seconds
(10/15) Running minio-py tests ... done in 1 minutes and 22 seconds
(11/15) Running s3cmd tests ... done in 25 seconds
(12/15) Running s3select tests ... done in 2 seconds
(13/15) Running security tests ... done in 0 seconds

Executed 13 out of 15 tests successfully.
```
<a name="b926d41a-f037-436c-be5f-ee19b777c516"></a>
### 9867-19eec7e/mint-large-bucket.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-dev4.minio.io:31471
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 58aee7a5e953:/mint/log /tmp/mint-logs'

(1/15) Running aws-sdk-go tests ... done in 5 seconds
(2/15) Running aws-sdk-java tests ... done in 2 seconds
(3/15) Running aws-sdk-php tests ... done in 47 seconds
(4/15) Running aws-sdk-ruby tests ... done in 9 seconds
(5/15) Running awscli tests ... done in 2 minutes and 34 seconds
(6/15) Running healthcheck tests ... done in 0 seconds
(7/15) Running mc tests ... done in 59 seconds
(8/15) Running minio-dotnet tests ... done in 1 minutes and 16 seconds
(9/15) Running minio-go tests ... FAILED in 1 minutes and 47 seconds
{
  "args": {
    "bucketName": "minio-go-test-immb5eun0cwi2ky6",
    "objectName": "2grw60yrqa9ksxxnv95ezfd9s3qomr",
    "objectPrefix": "",
    "recursive": "true"
  },
  "duration": 3618,
  "error": "The bucket you tried to delete is not empty. You must delete all versions in the bucket.",
  "function": "RemoveObjectsWithOptions(bucketName, objectsCh, opts)",
  "message": "Cleanup failed",
  "name": "minio-go: testRemoveObjectsWithOptions",
  "status": "FAIL"
}
(9/15) Running minio-java tests ... FAILED in 7 minutes and 0 seconds
{
  "name": "minio-java",
  "function": "enableObjectLegalHold(String bucketName, String objectName, String versionId)",
  "duration": 820,
  "status": "FAIL",
  "error": "error occurred\nErrorResponse(code = BucketNotEmpty, message = The bucket you tried to delete is not empty. You must delete all versions in the bucket., bucketName = minio-java-test-23gn4d5, objectName = null, resource = /minio-java-test-23gn4d5, requestId = 16198BE97E96CCE7, hostId = ed1b5558-fc3a-4543-af0f-c1e00ac4d1a8)\nrequest={method=DELETE, url=http://minio-dev4.minio.io:31471/minio-java-test-23gn4d5, headers=Host: minio-dev4.minio.io:31471\nAccept-Encoding: identity\nUser-Agent: MinIO (amd64; amd64) minio-java/dev\nContent-MD5: 1B2M2Y8AsgTpgAmY7PhCfg==\nx-amz-content-sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855\nx-amz-date: 20200618T052258Z\nAuthorization: AWS4-HMAC-SHA256 Credential=*REDACTED*/20200618/us-east-1/s3/aws4_request, SignedHeaders=accept-encoding;content-md5;host;x-amz-content-sha256;x-amz-date, Signature=*REDACTED*\n}\nresponse={code=409, headers=Accept-Ranges: bytes\nContent-Length: 373\nContent-Security-Policy: block-all-mixed-content\nContent-Type: application/xml\nServer: MinIO/DEVELOPMENT.2020-06-18T05-02-21Z\nVary: Origin\nX-Amz-Request-Id: 16198BE97E96CCE7\nX-Xss-Protection: 1; mode=block\nDate: Thu, 18 Jun 2020 05:22:58 GMT\n}\n >>> [io.minio.MinioClient.execute(MinioClient.java:1211), io.minio.MinioClient.execute(MinioClient.java:1236), io.minio.MinioClient.executeDelete(MinioClient.java:1366), io.minio.MinioClient.removeBucket(MinioClient.java:3686), FunctionalTest.enableObjectLegalHold_test(FunctionalTest.java:3314), FunctionalTest.runTests(FunctionalTest.java:4079), FunctionalTest.main(FunctionalTest.java:4192)]"
}
(9/15) Running minio-js tests ... done in 55 seconds
(10/15) Running minio-py tests ... done in 5 minutes and 14 seconds
(11/15) Running s3cmd tests ... done in 28 seconds
(12/15) Running s3select tests ... done in 15 seconds
(13/15) Running security tests ... done in 0 seconds

Executed 13 out of 15 tests successfully.
```
<a name="b885a9e3-829a-401c-92ba-7c917afecc6b"></a>
### 9867-19eec7e/mint-gateway-azure.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-dev7.minio.io:30450
ACCESS_KEY:           minioazure
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp b020da15afa2:/mint/log /tmp/mint-logs'

(1/15) Running aws-sdk-go tests ... done in 8 seconds
(2/15) Running aws-sdk-java tests ... done in 2 seconds
(3/15) Running aws-sdk-php tests ... done in 1 minutes and 45 seconds
(4/15) Running aws-sdk-ruby tests ... done in 16 seconds
(5/15) Running awscli tests ... FAILED in 11 seconds
{
  "name": "awscli",
  "duration": 1527,
  "function": "make_bucket\n",
  "status": "FAIL",
  "error": "An error occurred (BucketAlreadyOwnedByYou) when calling the CreateBucket operation: Your previous request to create the named bucket succeeded and you already own it."
}
(5/15) Running healthcheck tests ... done in 0 seconds
(6/15) Running mc tests ... done in 3 minutes and 21 seconds
(7/15) Running minio-dotnet tests ... done in 1 minutes and 35 seconds
(8/15) Running minio-go tests ... done in 6 minutes and 20 seconds
(9/15) Running minio-java tests ... done in 26 minutes and 41 seconds
(10/15) Running minio-js tests ... done in 2 minutes and 54 seconds
(11/15) Running minio-py tests ... done in 10 minutes and 14 seconds
(12/15) Running s3cmd tests ... done in 1 minutes and 27 seconds
(13/15) Running s3select tests ... done in 1 minutes and 3 seconds
(14/15) Running security tests ... done in 0 seconds

Executed 14 out of 15 tests successfully.
```
Deleting image on docker hub
Deleting image locally

**Review by balamurugana — COMMENTED** [review]
Tested; LGTM

**Review by klauspost — APPROVED** [review]

File: cmd/erasure-zones.go [hunk 1]
```diff
@@ -542,14 +543,14 @@ func (z *erasureZones) DeleteObject(ctx context.Context, bucket string, object s
 func (z *erasureZones) DeleteObjects(ctx context.Context, bucket string, objects []ObjectToDelete, opts ObjectOptions) ([]DeletedObject, []error) {
 	derrs := make([]error, len(objects))
 	dobjects := make([]DeletedObject, len(objects))
-	objNames := make([]string, len(objects))
+	objSets := set.NewStringSet()
 	for i := range derrs {
 		derrs[i] = checkDelObjArgs(ctx, bucket, objects[i].ObjectName)
-		objNames[i] = objects[i].ObjectName
+		objSets.Add(objects[i].ObjectName)
```
Comment (klauspost) [inline cmd/erasure-zones.go:549]: So both requests will go through?

With versioning where things are not actually deleted that seems problematic.

Shouldn't the second one be rejected?

**Review by klauspost — DISMISSED** [review]
PTAL before merge.

File: cmd/erasure-zones.go (hunk 1 above)
Comment (harshavardhana) [reply cmd/erasure-zones.go:549]: what both requests? we only hold locks for object name @klauspost if things can be deleted or not is already filtered in the top layer for object locking. 

If it can't be deleted it is rejected but the point locks are held for object names not duplicate names.
