### PR TITLE
Increase response header timeout for gateway

### LINKED ISSUE #9295: [resolved] Your socket connection to the server was not read from or written to within the timeout period
I'm using Minio as gateway to S3 behind Nextcloud. Everything works fine for uploads to say 2Gb, but from there, i'm getting errors.

## Current Behavior
While uploading large files trough S3 Gateway, i'm getting these errors:

```
API: PutObjectPart(bucket=big_files, object=urn:oid:4960)
Time: 10:07:22 CEST 04/08/2020
DeploymentID: 83469368-6bdf-4490-853a-54ff4aad33c9
RequestID: 1603C9AB812D9807
RemoteHost: 10.1.0.5
Host: 10.1.0.2:8080
UserAgent: aws-sdk-php/3.93.9 GuzzleHttp/6.3.3 curl/7.58.0 PHP/7.3.16-1+ubuntu18.04.1+deb.sury.org+1
Error: Your socket connection to the server was not read from or written to within the timeout period.
       4: github.com/minio/minio@/cmd/api-errors.go:1807:cmd.toAPIErrorCode()
       3: github.com/minio/minio@/cmd/api-errors.go:1832:cmd.toAPIError()
       2: github.com/minio/minio@/cmd/object-handlers.go:2121:cmd.objectAPIHandlers.PutObjectPartHandler()
       1: net/http/server.go:2007:http.HandlerFunc.ServeHTTP()
```

## Your Environment

* Version used (`minio version`): `RELEASE.2020-04-04T05-39-31Z`
* Environment name and version (e.g. nginx 1.9.1): `aws-sdk-php/3.93.9 GuzzleHttp/6.3.3 curl/7.58.0 PHP/7.3.16`
* Operating System and version (`uname -a`): `Ubuntu 18.0.4  4.18.0-25-generic`

### PR DESCRIPTION
**Pull request by poornas**
Fixes: #9295

## Motivation and Context
See issue #9295 - Response header timeouts were introduced in RELEASE.2020-03-25T07-03-04Z which seems to be overly aggressive in timing out longer gateway operations. This PR bumps up the timeout to 60 seconds

## Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [ ] Fixes a regression (If yes, please add `commit-id` or `PR #` here)
- [ ] Documentation needed
- [ ] Unit tests needed
- [ ] Functional tests needed (If yes, add [mint](https://github.com/minio/mint) PR # here: )

### CODE REVIEW

File: cmd/utils.go [hunk 1]
```diff
@@ -495,7 +495,7 @@ func NewGatewayHTTPTransport() *http.Transport {
 		RootCAs: globalRootCAs,
 	}, defaultDialTimeout)()
 	// Set aggressive timeouts for gateway
-	tr.ResponseHeaderTimeout = 30 * time.Second
+	tr.ResponseHeaderTimeout = 60 * time.Second
```
Comment (harshavardhana) [inline cmd/utils.go]: 1 * time.Minute @poornas  is better

**Review by harshavardhana — CHANGES_REQUESTED** [review]

**Comment by minio-trusted** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-xl.sh | :heavy_check_mark: |
| mint-worm.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-dist-xl.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :x: [more...](#8abee11e-16d8-41ed-adb5-103ad2682316) |
| mint-gateway-azure.sh | :x: [more...](#3693eaf2-4bcd-4368-a54c-4a1f588416d9) |
| mint-gateway-nas.sh | :x: [more...](#6d683f8e-a18a-46b6-b550-18d59ebe61a9) |
<a name="6d683f8e-a18a-46b6-b550-18d59ebe61a9"></a>
### 9400-fb3c89c/mint-gateway-nas.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-dev4.minio.io:30712
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp f1104a7d6064:/mint/log /tmp/mint-logs'

(1/15) Running aws-sdk-go tests ... done in 0 seconds
(2/15) Running aws-sdk-java tests ... done in 2 seconds
(3/15) Running aws-sdk-php tests ... done in 40 seconds
(4/15) Running aws-sdk-ruby tests ... done in 1 seconds
(5/15) Running awscli tests ... done in 2 minutes and 12 seconds
(6/15) Running healthcheck tests ... done in 0 seconds
(7/15) Running mc tests ... done in 32 seconds
(8/15) Running minio-dotnet tests ... done in 30 seconds
(9/15) Running minio-go tests ... FAILED in 24 seconds
{}

Executed 8 out of 15 tests successfully.
```
<a name="8abee11e-16d8-41ed-adb5-103ad2682316"></a>
### 9400-fb3c89c/mint-large-bucket.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-c3.minio.io:30165
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 6494a71bfee7:/mint/log /tmp/mint-logs'

(1/15) Running aws-sdk-go tests ... FAILED in 6 minutes and 6 seconds
{
  "alert": "",
  "args": {
    "bucketName": "aws-sdk-go-test-qfrg6ycy3609fw",
    "expiry": 60000000000,
    "objectName": "presignedTest"
  },
  "duration": 366107,
  "error": "XMinioServerNotInitialized: Server not initialized, please try again.\n\tstatus code: 503, request id: 1607C1F80D1ADB90, host id: ",
  "function": "PresignedPut",
  "message": "AWS SDK Go CreateBucket Failed",
  "name": "aws-sdk-go",
  "status": "FAIL"
}

Executed 0 out of 15 tests successfully.
```
<a name="3693eaf2-4bcd-4368-a54c-4a1f588416d9"></a>
### 9400-fb3c89c/mint-gateway-azure.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-dev7.minio.io:30336
ACCESS_KEY:           minioazure
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp eeb0c885140a:/mint/log /tmp/mint-logs'

(1/15) Running aws-sdk-go tests ... done in 7 seconds
(2/15) Running aws-sdk-java tests ... done in 1 seconds
(3/15) Running aws-sdk-php tests ... done in 1 minutes and 5 seconds
(4/15) Running aws-sdk-ruby tests ... done in 15 seconds
(5/15) Running awscli tests ... FAILED in 57 seconds
{
  "name": "awscli",
  "duration": 4210,
  "function": "aws --endpoint-url http://minio-dev7.minio.io:30336 s3api copy-object --bucket awscli-mint-test-bucket-27038 --storage-class REDUCED_REDUNDANCY --key datafile-1-kB-copy --copy-source awscli-mint-test-bucket-27038/datafile-1-kB\n",
  "status": "FAIL",
  "error": "An error occurred (NotImplemented) when calling the CopyObject operation: A header you provided implies functionality that is not implemented"
}

Executed 4 out of 15 tests successfully.
```
Deleting image on docker hub
Deleting image locally

**Review by harshavardhana — APPROVED** [review]

**Comment by minio-trusted** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-xl.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-worm.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-dist-xl.sh | :heavy_check_mark: |
| mint-gateway-azure.sh | :x: [more...](#2a48a720-8cd1-47c6-be9e-b695b5c6b2e3) |
| mint-gateway-nas.sh | :x: [more...](#6615df82-10e7-40ed-a330-695d0a47dee2) |
<a name="2a48a720-8cd1-47c6-be9e-b695b5c6b2e3"></a>
### 9400-1df77ed/mint-gateway-azure.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-c3.minio.io:30308
ACCESS_KEY:           minioazure
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 41d23b2ad887:/mint/log /tmp/mint-logs'

(1/15) Running aws-sdk-go tests ... done in 8 seconds
(2/15) Running aws-sdk-java tests ... done in 1 seconds
(3/15) Running aws-sdk-php tests ... done in 1 minutes and 4 seconds
(4/15) Running aws-sdk-ruby tests ... done in 14 seconds
(5/15) Running awscli tests ... FAILED in 54 seconds
{
  "name": "awscli",
  "duration": 3803,
  "function": "aws --endpoint-url http://minio-c3.minio.io:30308 s3api copy-object --bucket awscli-mint-test-bucket-11290 --storage-class REDUCED_REDUNDANCY --key datafile-1-kB-copy --copy-source awscli-mint-test-bucket-11290/datafile-1-kB\n",
  "status": "FAIL",
  "error": "An error occurred (NotImplemented) when calling the CopyObject operation: A header you provided implies functionality that is not implemented"
}

Executed 4 out of 15 tests successfully.
```
<a name="6615df82-10e7-40ed-a330-695d0a47dee2"></a>
### 9400-1df77ed/mint-gateway-nas.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-dev6.minio.io:30116
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 5aae2eeb04a6:/mint/log /tmp/mint-logs'

(1/15) Running aws-sdk-go tests ... done in 0 seconds
(2/15) Running aws-sdk-java tests ... done in 2 seconds
(3/15) Running aws-sdk-php tests ... done in 41 seconds
(4/15) Running aws-sdk-ruby tests ... done in 1 seconds
(5/15) Running awscli tests ... done in 2 minutes and 10 seconds
(6/15) Running healthcheck tests ... done in 1 seconds
(7/15) Running mc tests ... done in 32 seconds
(8/15) Running minio-dotnet tests ... done in 30 seconds
(9/15) Running minio-go tests ... FAILED in 34 seconds
{}

Executed 8 out of 15 tests successfully.
```
Deleting image on docker hub
Deleting image locally
