### PR TITLE
FS/XL: Return IncompleteBody{} error for short writes

### LINKED ISSUE #2221: fs/xl: PutObject should return IncompleteBody when request.Body fewer than specified bytes
## Expected behaviour

if request.Body has fewer bytes than the size provided in Content-length field in the request header, PutObject should fail with `IncompleteBody` error.
## Actual behaviour

fs: Object is not created and no error is returned.
xl: Object is created successfully.
## Steps to reproduce the behaviour

Found while performing unit test at the xl/fs object layer. 
## Minio version

commit id `27a5b61`

### PR DESCRIPTION
**Pull request by krisis**
Fixes #2221

### CODE REVIEW

File: erasure-createfile.go [hunk 1]
```diff
@@ -44,10 +44,15 @@ func erasureCreateFile(disks []StorageAPI, volume, path string, reader io.Reader
 			return 0, nil, rErr
 		}
 		if rErr == io.EOF {
+			// Should return IncompleteBody when reader contains
+			// fewer than specified bytes
+			if bytesWritten < size {
+				return bytesWritten, nil, io.ErrShortWrite
```
Comment (harshavardhana) [inline erasure-createfile.go]: why can't we handle this outside of 'erasureCreateFile' ? at the object layer?

File: fs-v1-multipart.go [hunk 2]
```diff
@@ -321,23 +321,26 @@ func (fs fsObjects) PutObjectPart(bucket, object, uploadID string, partID int, s
...
+	bytesWritten := int64(0)
+	// Read the buffer till io.EOF and append the read data to the temporary file.
 	for {
-		n, err := io.ReadFull(limitDataReader, buf)
-		if err == io.EOF {
-			break
-		}
-		if err != nil && err != io.ErrUnexpectedEOF {
-			return "", toObjectErr(err, bucket, object)
+		n, rErr := limitDataReader.Read(buf)
```
Comment (harshavardhana) [inline fs-v1-multipart.go]: .Read is not efficient for us, it will lead to many more calls since Read also doesn't return full 'buf' bytes.  io.ReadFull was used for this purpose only. 

Also move this into separate function as 'fs-createfile.go'

Comment (harshavardhana) [inline fs-v1-multipart.go]: > .Read is not efficient for us, it will lead to many more calls since Read also doesn't return full 'buf' bytes. io.ReadFull was used for this purpose only.

Actually wait .Read is fine, my bad. 

> Also move this into separate function as 'fs-createfile.go'

Just that move this into separate file / function. use it also in PutObject()

File: erasure-createfile.go (hunk 1 above)
Comment (krisis) [inline erasure-createfile.go]: @harshavardhana Nothing stops us from handling it at the object layer. I shall update the PR handling it at the object layer for XL.

**Comment by krisis** [comment]
> you could delete the tmp file too.
> @krishnasrinivas so, there are other such places in xl-v1-object.go where we don't delete the temp object. Should I fix all those too in this PR?

**Comment by krishnasrinivas** [comment]
> @krishnasrinivas so, there are other such places in xl-v1-object.go where we don't delete the temp object. Should I fix all those too in this PR?

oh! if there are a quite a few places where we leave tmp files without deleting then it's better to have a separate 'tmp file cleanup' PR and not mix with this PR

**Comment by harshavardhana** [comment]
> @krishnasrinivas so, there are other such places in xl-v1-object.go where we don't delete the temp object. Should I fix all those too in this PR?
> oh! if there are a quite a few places where we leave tmp files without deleting then it's better to have a separate 'tmp file cleanup' PR and not mix with this PR

@krisis can you show where are these places where are not deleting tmp files?
