### PR TITLE
s3/zip: extract metadata properly for Zipped objects

### LINKED ISSUE #15121: 500 Internal Server Error for "mc ls --zip --recursive"
In the article https://blog.min.io/small-file-archives / describes how to view the contents of zip archives. In one of the minio installations, we use this feature (Version: 2022-01-08T03:11:54 I, 4-node cluster). And everything works fine.

We recently deployed another installation (Version: 2022-01-08T03:11:54Z, 1-node). When trying to view the contents of the archive, minio writes an error:

`mcli admin trace -a -v l1`

```
API: ListObjectsV2(bucket=test1)
Time: 19:34:44 UTC 06/20/2022
DeploymentID: e9c3c0f2-859b-42f9-80ef-251303f58029
RequestID: 16FA6B34114EFC08
RemoteHost: 172.17.0.1
Host: 127.0.0.1:9000
UserAgent: MinIO (darwin; amd64) minio-go/v7.0.24 mcli/RELEASE.2022-04-16T21-11-21Z
Error: unknown version (*errors.errorString)
       4: cmd/api-errors.go:2103:cmd.toAPIErrorCode()
       3: cmd/api-errors.go:2128:cmd.toAPIError()
       2: cmd/bucket-listobjects-handlers.go:252:cmd.objectAPIHandlers.ListObjectsV2Handler()
       1: net/http/server.go:2047:http.HandlerFunc.ServeHTTP()

...
REPEATED 8 TIMES
...

API: ListObjectsV2(bucket=test1)
Time: 19:34:48 UTC 06/20/2022
DeploymentID: e9c3c0f2-859b-42f9-80ef-251303f58029
RequestID: 16FA6B3508AA8C4C
RemoteHost: 172.17.0.1
Host: 127.0.0.1:9000
UserAgent: MinIO (darwin; amd64) minio-go/v7.0.24 mcli/RELEASE.2022-04-16T21-11-21Z
Error: unknown version (*errors.errorString)
       4: cmd/api-errors.go:2103:cmd.toAPIErrorCode()
       3: cmd/api-errors.go:2128:cmd.toAPIError()
       2: cmd/bucket-listobjects-handlers.go:252:cmd.objectAPIHandlers.ListObjectsV2Handler()
       1: net/http/server.go:2047:http.HandlerFunc.ServeHTTP()
```

The client outputs an error
```
mcli: <ERROR> Unable to list folder. We encountered an internal error, please try again.: cause(unknown version)
```

## Expected Behavior
Returning the list of files in the archive. Moreover, if you fill in the archive again, then you can again list the files inside it. But only 1 time

## Current Behavior
Error, after the first output of the file list.

## Steps to Reproduce (for bugs)
```
$ docker pull minio/minio:RELEASE.2022-06-17T02-00-35Z
# OR
docker pull minio/minio:RELEASE.2022-01-08T03-11-54Z
$ mkdir -p minio-data
$ docker run -it --rm --name m1 -p 9000:9000 -p 9001:9001 -v $(pwd)/minio-data:/data -e MINIO_ROOT_USER=minio -e $ MINIO_ROOT_PASSWORD=miniominio minio/minio:RELEASE.2022-01-08T03-11-54Z server /data --console-address ":9001"
$ mcli alias set l1 http://127.0.0.1:9000 minio miniominio
$ mcli mb l1/test1
# create zip-file archive.zip with several files
$ FILE="err.zip"
$ mcli cp $FILE l1/test1/$FILE
$ mcli ls --zip -r l1/test1/$FILE
[2022-06-20 21:35:45 MSK]  26KiB STANDARD err.zip/err.txt
[2022-06-20 21:35:45 MSK]  16KiB STANDARD err.zip/err1.txt
$ mcli ls --zip -r l1/test1/$FILE
mcli: <ERROR> Unable to list folder. We encountered an internal error, please try again.: cause(unknown version)
```

## Context
Storing a list of files for 1 day (for archived data) not as a set of individual files, but as a zip archive. If necessary, a list of files is obtained and the user is provided with a link to a specific file from the archive

## Regression
We assumed that such an error occurs only in new versions, so we deployed exactly the same version as on an already running cluster. But it didn't help. The next difference is that on a 4-node instance, minio is running without a container, and on a 1-node instance in a container. We tried to run a 1-node without a container, but it also didn't work.
Perhaps the reason is the number of nodes?

## Your Environment

* Version used (`minio --version`):
  * 2022-01-08T03:11:54Z
  * 2022-06-17T02:00:35Z
* Server setup and configuration:
* Operating System and version (`uname -a`): 
  * Linux test-polygon 5.4.0-88-generic #99-Ubuntu SMP Thu Sep 23 17:29:00 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux (Docker version 20.10.8, build 3967b7d)
  * Darwin iMac-Serg.local 20.5.0 Darwin Kernel Version 20.5.0: Sat May  8 05:10:33 PDT 2021; root:xnu-7195.121.3~9/RELEASE_X86_64 x86_64 (Docker version 20.10.16, build aa7e414)

### PR DESCRIPTION
**Pull request by harshavardhana**
## Description
s3/zip: extract metadata properly for Zipped objects

## Motivation and Context
fixes #15121

## How to test this PR?
As per #15121 (this only affects single node-setups)

## Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Optimization (provides speedup with no functional changes)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [ ] Fixes a regression (If yes, please add `commit-id` or `PR #` here)
- [ ] Documentation updated
- [ ] Unit tests added/updated

### CODE REVIEW

**Comment by minio-trusted** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-gateway-s3.sh | :heavy_check_mark: |
| mint-erasure.sh | :heavy_check_mark: |
| mint-dist-erasure.sh | :heavy_check_mark: |
| mint-compress-encrypt-dist-erasure.sh | :heavy_check_mark: |
| mint-pools.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :x: [more...](#554b7d86-265f-4fab-bf7d-04e540482a1f) |
| mint-fs.sh | :x: [more...](#508afaa1-7b77-4a85-bb81-5491111c1178) |
<a name="554b7d86-265f-4fab-bf7d-04e540482a1f"></a>
### 15123-6669345/mint-large-bucket.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-k8s1:30186
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0
RUN_ON_FAIL:          0

To get logs, run 'docker cp :/mint/log /tmp/mint-logs'

(1/15) Running aws-sdk-go tests ... done in 8 seconds
(2/15) Running aws-sdk-java tests ... done in 1 seconds
(3/15) Running aws-sdk-php tests ... done in 44 seconds
(4/15) Running aws-sdk-ruby tests ... done in 7 seconds
(5/15) Running awscli tests ... done in 56 seconds
(6/15) Running healthcheck tests ... done in 0 seconds
(7/15) Running mc tests ... done in 30 seconds
(8/15) Running minio-dotnet tests ... done in 6 minutes and 18 seconds
(9/15) Running minio-go tests ... FAILED in 1 minutes and 29 seconds
{
  "args": {
    "bucketName": "minio-go-test-nkk4uot4hpgzxyhg",
    "expires": 3600000000000,
    "objectName": "minio-go-test-nkk4uot4hpgzxyhgunique",
    "reqParams": {
      "response-content-disposition": [
        "attachment; filename=\"test.txt\""
      ]
    }
  },
  "duration": 41446,
  "error": "Get \"http://minio-k8s1:30186/minio-go-test-nkk4uot4hpgzxyhg/minio-go-test-nkk4uot4hpgzxyhgunique?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=minio%2F20220621%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20220621T012403Z&X-Amz-Expires=3600&X-Amz-SignedHeaders=host&response-content-disposition=attachment%3B%20filename%3D%22test.txt%22&X-Amz-Signature=12571c4ae4e9d2ea02561d4d5aca848823f3ecbc804f0184623613806a478438\": context deadline exceeded (Client.Timeout exceeded while awaiting headers)",
  "function": "PresignedGetObject(bucketName, objectName, expires, reqParams)",
  "message": "PresignedGetObject response incorrect",
  "name": "minio-go: testFunctional",
  "status": "FAIL"
}
(9/15) Running minio-java tests ... done in 33 seconds
(10/15) Running minio-js tests ... done in 1 minutes and 3 seconds
(11/15) Running minio-py tests ... done in 1 minutes and 24 seconds
(12/15) Running s3cmd tests ... done in 25 seconds
(13/15) Running s3select tests ... done in 4 seconds
(14/15) Running versioning tests ... done in 3 minutes and 4 seconds

Executed 14 out of 15 tests successfully.
```
<a name="508afaa1-7b77-4a85-bb81-5491111c1178"></a>
### 15123-6669345/mint-fs.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-k8s6:30786
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0
RUN_ON_FAIL:          0

To get logs, run 'docker cp :/mint/log /tmp/mint-logs'

(1/15) Running aws-sdk-go tests ... done in 0 seconds
(2/15) Running aws-sdk-java tests ... done in 1 seconds
(3/15) Running aws-sdk-php tests ... done in 42 seconds
(4/15) Running aws-sdk-ruby tests ... done in 5 seconds
(5/15) Running awscli tests ... done in 53 seconds
(6/15) Running healthcheck tests ... done in 0 seconds
(7/15) Running mc tests ... done in 22 seconds
(8/15) Running minio-dotnet tests ... done in 6 minutes and 12 seconds
(9/15) Running minio-go tests ... done in 59 seconds
(10/15) Running minio-java tests ... done in 18 seconds
(11/15) Running minio-js tests ... FAILED in 2 minutes and 39 seconds
{
  "name": "minio-js",
  "function": "\"after all\" hook in \"functional tests\"",
  "duration": 3,
  "status": "FAIL",
  "error": "Error: read ECONNRESET at TCP.onStreamRead (internal/stream_base_commons.js:209:20)"
}
(11/15) Running minio-py tests ... done in 47 seconds
(12/15) Running s3cmd tests ... done in 23 seconds
(13/15) Running s3select tests ... done in 1 seconds
(14/15) Running versioning tests ... done in 3 minutes and 1 seconds

Executed 14 out of 15 tests successfully.
```
Deleting image on docker hub
Deleting image locally

File: cmd/object-api-datatypes.go [hunk 1]
```diff
@@ -178,6 +179,22 @@ type ObjectInfo struct {
...
+	}
+	z, ok := o.UserDefined[archiveInfoMetadataKey]
+	if !ok {
+		return nil
+	}
+	zipInfo, err := base64.StdEncoding.DecodeString(z)
+	if err != nil {
+		zipInfo = []byte(z)
+	}
+	return zipInfo
```
Comment (klauspost) [inline cmd/object-api-datatypes.go]: First byte will currently be 1,2 or 3, but may be higher in the future. Use that as a faster and safer check:

```suggestion
	// FS/gateway mode does base64 encoding on roundtrip.
	// zipindex has version as first byte, which is below any base64 value.
	if len(z) > 0 && z[0] >= 32 {
		if zipInfo, err := base64.StdEncoding.DecodeString(z); err == nil {
			return zipInfo
		}
	}
	return []byte(z)
```

**Review by klauspost — CHANGES_REQUESTED** [review]

**Comment by minio-trusted** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-large-bucket.sh | :x: [more...](#ceb28726-42ce-42e2-8158-7227a81d1e34) |
| mint-fs.sh | :x: [more...](#d9da6453-3e97-4e86-94ec-b19f7d32c2e4) |
| mint-gateway-s3.sh | :x: [more...](#cb08582f-cede-4ff9-80f1-e13c42edfdad) |
| mint-erasure.sh | :x: [more...](#de8cb532-d07d-4134-bb1e-58d596164315) |
| mint-dist-erasure.sh | :x: [more...](#8ef7167e-78af-400e-b58b-54f5b02970bc) |
| mint-compress-encrypt-dist-erasure.sh | :x: [more...](#b9569afe-5076-4a00-9db8-14baec6062e6) |
| mint-pools.sh | :x: [more...](#75dde743-f76b-4793-a975-03a398b30df2) |
<a name="75dde743-f76b-4793-a975-03a398b30df2"></a>
### 15123-8fef517/mint-pools.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-k8s3:30601
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0
RUN_ON_FAIL:          0

To get logs, run 'docker cp :/mint/log /tmp/mint-logs'

(1/15) Running aws-sdk-go tests ... done in 1 seconds
(2/15) Running aws-sdk-java tests ... done in 2 seconds
(3/15) Running aws-sdk-php tests ... done in 43 seconds
(4/15) Running aws-sdk-ruby tests ... done in 7 seconds
(5/15) Running awscli tests ... done in 56 seconds
(6/15) Running healthcheck tests ... done in 1 seconds
(7/15) Running mc tests ... done in 30 seconds
FAILED in 2 minutes and 49 seconds
Unhandled exception. System.AggregateException: One or more errors occurred. (A task was canceled.)
 ---> System.Threading.Tasks.TaskCanceledException: A task was canceled.
   at System.Threading.Tasks.Task.GetExceptions(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.Wait()
   at Minio.Functional.Tests.Program.Main(String[] args) in /mint/run/core/minio-dotnet/temp/Minio.Functional.Tests/Program.cs:line 141
--- End of stack trace from previous location ---

   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.Wait()
   at Minio.Functional.Tests.Program.Main(String[] args) in /mint/run/core/minio-dotnet/temp/Minio.Functional.Tests/Program.cs:line 141
(8/15) Running minio-go tests ... done in 1 minutes and 38 seconds
(9/15) Running minio-java tests ... done in 37 seconds
(10/15) Running minio-js tests ... done in 1 minutes and 6 seconds
(11/15) Running minio-py tests ... done in 1 minutes and 40 seconds
(12/15) Running s3cmd tests ... done in 26 seconds
(13/15) Running s3select tests ... done in 4 seconds
(14/15) Running versioning tests ... done in 3 minutes and 6 seconds

Executed 14 out of 15 tests successfully.
```
<a name="ceb28726-42ce-42e2-8158-7227a81d1e34"></a>
### 15123-8fef517/mint-large-bucket.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-k8s3:31956
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0
RUN_ON_FAIL:          0

To get logs, run 'docker cp :/mint/log /tmp/mint-logs'

(1/15) Running aws-sdk-go tests ... done in 1 seconds
(2/15) Running aws-sdk-java tests ... done in 1 seconds
(3/15) Running aws-sdk-php tests ... done in 44 seconds
(4/15) Running aws-sdk-ruby tests ... done in 7 seconds
(5/15) Running awscli tests ... done in 54 seconds
(6/15) Running healthcheck tests ... done in 0 seconds
(7/15) Running mc tests ... done in 28 seconds
FAILED in 3 minutes and 5 seconds
Unhandled exception. System.AggregateException: One or more errors occurred. (A task was canceled.)
 ---> System.Threading.Tasks.TaskCanceledException: A task was canceled.
   at System.Threading.Tasks.Task.GetExceptions(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.Wait()
   at Minio.Functional.Tests.Program.Main(String[] args) in /mint/run/core/minio-dotnet/temp/Minio.Functional.Tests/Program.cs:line 151
--- End of stack trace from previous location ---

   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.Wait()
   at Minio.Functional.Tests.Program.Main(String[] args) in /mint/run/core/minio-dotnet/temp/Minio.Functional.Tests/Program.cs:line 151
(8/15) Running minio-go tests ... done in 1 minutes and 15 seconds
(9/15) Running minio-java tests ... done in 34 seconds
(10/15) Running minio-js tests ... done in 1 minutes and 5 seconds
(11/15) Running minio-py tests ... done in 1 minutes and 21 seconds
(12/15) Running s3cmd tests ... done in 27 seconds
(13/15) Running s3select tests ... done in 3 seconds
(14/15) Running versioning tests ... done in 3 minutes and 5 seconds

Executed 14 out of 15 tests successfully.
```
<a name="8ef7167e-78af-400e-b58b-54f5b02970bc"></a>
### 15123-8fef517/mint-dist-erasure.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-k8s2:32297
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0
RUN_ON_FAIL:          0

To get logs, run 'docker cp :/mint/log /tmp/mint-logs'

(1/15) Running aws-sdk-go tests ... done in 8 seconds
(2/15) Running aws-sdk-java tests ... done in 2 seconds
(3/15) Running aws-sdk-php tests ... done in 42 seconds
(4/15) Running aws-sdk-ruby tests ... done in 7 seconds
(5/15) Running awscli tests ... done in 57 seconds
(6/15) Running healthcheck tests ... done in 0 seconds
(7/15) Running mc tests ... done in 30 seconds
FAILED in 2 minutes and 44 seconds
Unhandled exception. System.AggregateException: One or more errors occurred. (A task was canceled.)
 ---> System.Threading.Tasks.TaskCanceledException: A task was canceled.
   at System.Threading.Tasks.Task.GetExceptions(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.Wait()
   at Minio.Functional.Tests.Program.Main(String[] args) in /mint/run/core/minio-dotnet/temp/Minio.Functional.Tests/Program.cs:line 141
--- End of stack trace from previous location ---

   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.Wait()
   at Minio.Functional.Tests.Program.Main(String[] args) in /mint/run/core/minio-dotnet/temp/Minio.Functional.Tests/Program.cs:line 141
(8/15) Running minio-go tests ... done in 1 minutes and 40 seconds
(9/15) Running minio-java tests ... done in 30 seconds
(10/15) Running minio-js tests ... done in 1 minutes and 4 seconds
(11/15) Running minio-py tests ... done in 1 minutes and 17 seconds
(12/15) Running s3cmd tests ... done in 25 seconds
(13/15) Running s3select tests ... done in 4 seconds
(14/15) Running versioning tests ... done in 3 minutes and 4 seconds

Executed 14 out of 15 tests successfully.
```
<a name="cb08582f-cede-4ff9-80f1-e13c42edfdad"></a>
### 15123-8fef517/mint-gateway-s3.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-k8s1:30558
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0
RUN_ON_FAIL:          0

To get logs, run 'docker cp :/mint/log /tmp/mint-logs'

(1/15) Running aws-sdk-go tests ... done in 0 seconds
(2/15) Running aws-sdk-java tests ... done in 2 seconds
(3/15) Running aws-sdk-php tests ... done in 42 seconds
(4/15) Running aws-sdk-ruby tests ... done in 6 seconds
(5/15) Running awscli tests ... done in 52 seconds
(6/15) Running healthcheck tests ... done in 0 seconds
(7/15) Running mc tests ... done in 20 seconds
FAILED in 2 minutes and 48 seconds
Unhandled exception. System.AggregateException: One or more errors occurred. (A task was canceled.)
 ---> System.Threading.Tasks.TaskCanceledException: A task was canceled.
   at System.Threading.Tasks.Task.GetExceptions(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.Wait()
   at Minio.Functional.Tests.Program.Main(String[] args) in /mint/run/core/minio-dotnet/temp/Minio.Functional.Tests/Program.cs:line 141
--- End of stack trace from previous location ---

   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.Wait()
   at Minio.Functional.Tests.Program.Main(String[] args) in /mint/run/core/minio-dotnet/temp/Minio.Functional.Tests/Program.cs:line 141
(8/15) Running minio-go tests ... done in 35 seconds
(9/15) Running minio-java tests ... done in 30 seconds
(10/15) Running minio-js tests ... done in 40 seconds
(11/15) Running minio-py tests ... done in 56 seconds
(12/15) Running s3cmd tests ... done in 1 minutes and 5 seconds
(13/15) Running s3select tests ... done in 3 seconds
(14/15) Running versioning tests ... done in 0 seconds

Executed 14 out of 15 tests successfully.
```
<a name="d9da6453-3e97-4e86-94ec-b19f7d32c2e4"></a>
### 15123-8fef517/mint-fs.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-k8s1:30226
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0
RUN_ON_FAIL:          0

To get logs, run 'docker cp :/mint/log /tmp/mint-logs'

(1/15) Running aws-sdk-go tests ... done in 0 seconds
(2/15) Running aws-sdk-java tests ... done in 1 seconds
(3/15) Running aws-sdk-php tests ... done in 42 seconds
(4/15) Running aws-sdk-ruby tests ... done in 5 seconds
(5/15) Running awscli tests ... done in 51 seconds
(6/15) Running healthcheck tests ... done in 0 seconds
(7/15) Running mc tests ... done in 24 seconds
FAILED in 3 minutes and 6 seconds
{
  "name": "minio-dotnet : ListObjects_Test1",
  "function": "IObservable<Item> ListObjectsAsync(string bucketName, string prefix = null, bool recursive = false, CancellationToken cancellationToken = default(CancellationToken))",
  "args": {
    "bucketName": "minio-dotnet-example-sollzrnql457dgy",
    "objectName": "minixminio-dotnet-example-vvafks5qsc",
    "prefix": "minix",
    "recursive": "false"
  },
  "duration": 100013,
  "status": "FAIL",
  "alert": "The request was canceled due to the configured HttpClient.Timeout of 100 seconds elapsing.",
  "message": "System.Threading.Tasks.TaskCanceledException: The request was canceled due to the configured HttpClient.Timeout of 100 seconds elapsing.\n ---> System.TimeoutException: The operation was canceled.\n ---> System.Threading.Tasks.TaskCanceledException: The operation was canceled.\n ---> System.IO.IOException: Unable to read data from the transport connection: Operation canceled.\n ---> System.Net.Sockets.SocketException (125): Operation canceled\n   --- End of inner exception stack trace ---\n   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)\n   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource<System.Int32>.GetResult(Int16 token)\n   at System.Net.Http.HttpConnection.InitialFillAsync(Boolean async)\n   at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)\n   --- End of inner exception stack trace ---\n   at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)\n   at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)\n   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)\n   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)\n   --- End of inner exception stack trace ---\n   --- End of inner exception stack trace ---\n   at System.Net.Http.HttpClient.HandleFailure(Exception e, Boolean telemetryStarted, HttpResponseMessage response, CancellationTokenSource cts, CancellationToken cancellationToken, CancellationTokenSource pendingRequestsCts)\n   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)\n   at Minio.MinioClient.ExecuteTaskCoreAsync(IEnumerable`1 errorHandlers, HttpRequestMessageBuilder requestMessageBuilder, CancellationToken cancellationToken, Boolean isSts) in /mint/run/core/minio-dotnet/temp/Minio/MinioClient.cs:line 526\n   at Minio.MinioClient.PutObjectSinglePartAsync(PutObjectArgs args, CancellationToken cancellationToken) in /mint/run/core/minio-dotnet/temp/Minio/ApiEndpoints/ObjectOperations.cs:line 1162\n   at Minio.MinioClient.PutObjectAsync(PutObjectArgs args, CancellationToken cancellationToken) in /mint/run/core/minio-dotnet/temp/Minio/ApiEndpoints/ObjectOperations.cs:line 655\n   at Minio.Functional.Tests.FunctionalTest.PutObject_Task(MinioClient minio, String bucketName, String objectName, String fileName, String contentType, Int64 size, Dictionary`2 metaData, MemoryStream mstream) in /mint/run/core/minio-dotnet/temp/Minio.Functional.Tests/FunctionalTest.cs:line 865\n   at Minio.Functional.Tests.FunctionalTest.ListObjects_Test1(MinioClient minio) in /mint/run/core/minio-dotnet/temp/Minio.Functional.Tests/FunctionalTest.cs:line 4458"
}
(8/15) Running minio-go tests ... done in 57 seconds
(9/15) Running minio-java tests ... done in 18 seconds
(10/15) Running minio-js tests ... done in 1 minutes and 0 seconds
(11/15) Running minio-py tests ... done in 45 seconds
(12/15) Running s3cmd tests ... done in 22 seconds
(13/15) Running s3select tests ... done in 2 seconds
(14/15) Running versioning tests ... done in 3 minutes and 1 seconds

Executed 14 out of 15 tests successfully.
```
<a name="b9569afe-5076-4a00-9db8-14baec6062e6"></a>
### 15123-8fef517/mint-compress-encrypt-dist-erasure.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-k8s7:30449
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0
RUN_ON_FAIL:          0

To get logs, run 'docker cp :/mint/log /tmp/mint-logs'

(1/15) Running aws-sdk-go tests ... done in 1 seconds
(2/15) Running aws-sdk-java tests ... done in 1 seconds
(3/15) Running aws-sdk-php tests ... done in 44 seconds
(4/15) Running aws-sdk-ruby tests ... done in 6 seconds
(5/15) Running awscli tests ... done in 53 seconds
(6/15) Running healthcheck tests ... done in 1 seconds
(7/15) Running mc tests ... done in 25 seconds
FAILED in 2 minutes and 59 seconds
Unhandled exception. System.AggregateException: One or more errors occurred. (A task was canceled.)
 ---> System.Threading.Tasks.TaskCanceledException: A task was canceled.
   at System.Threading.Tasks.Task.GetExceptions(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.Wait()
   at Minio.Functional.Tests.Program.Main(String[] args) in /mint/run/core/minio-dotnet/temp/Minio.Functional.Tests/Program.cs:line 145
--- End of stack trace from previous location ---

   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.Wait()
   at Minio.Functional.Tests.Program.Main(String[] args) in /mint/run/core/minio-dotnet/temp/Minio.Functional.Tests/Program.cs:line 145
(8/15) Running minio-go tests ... done in 1 minutes and 7 seconds
(9/15) Running minio-java tests ... done in 31 seconds
(10/15) Running minio-js tests ... done in 1 minutes and 6 seconds
(11/15) Running minio-py tests ... done in 1 minutes and 18 seconds
(12/15) Running s3cmd tests ... done in 24 seconds
(13/15) Running s3select tests ... done in 3 seconds
(14/15) Running versioning tests ... done in 3 minutes and 4 seconds

Executed 14 out of 15 tests successfully.
```
<a name="de8cb532-d07d-4134-bb1e-58d596164315"></a>
### 15123-8fef517/mint-erasure.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-k8s4:32465
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0
RUN_ON_FAIL:          0

To get logs, run 'docker cp :/mint/log /tmp/mint-logs'

(1/15) Running aws-sdk-go tests ... done in 7 seconds
(2/15) Running aws-sdk-java tests ... done in 1 seconds
(3/15) Running aws-sdk-php tests ... done in 43 seconds
(4/15) Running aws-sdk-ruby tests ... done in 5 seconds
(5/15) Running awscli tests ... done in 54 seconds
(6/15) Running healthcheck tests ... done in 0 seconds
(7/15) Running mc tests ... done in 25 seconds
FAILED in 2 minutes and 34 seconds
Unhandled exception. System.AggregateException: One or more errors occurred. (A task was canceled.)
 ---> System.Threading.Tasks.TaskCanceledException: A task was canceled.
   at System.Threading.Tasks.Task.GetExceptions(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.Wait()
   at Minio.Functional.Tests.Program.Main(String[] args) in /mint/run/core/minio-dotnet/temp/Minio.Functional.Tests/Program.cs:line 136
--- End of stack trace from previous location ---

   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.Wait()
   at Minio.Functional.Tests.Program.Main(String[] args) in /mint/run/core/minio-dotnet/temp/Minio.Functional.Tests/Program.cs:line 136
(8/15) Running minio-go tests ... done in 53 seconds
(9/15) Running minio-java tests ... done in 21 seconds
(10/15) Running minio-js tests ... done in 1 minutes and 0 seconds
(11/15) Running minio-py tests ... done in 51 seconds
(12/15) Running s3cmd tests ... done in 24 seconds
(13/15) Running s3select tests ... done in 1 seconds
(14/15) Running versioning tests ... done in 3 minutes and 2 seconds

Executed 14 out of 15 tests successfully.
```
Deleting image on docker hub
Deleting image locally

**Review by klauspost — APPROVED** [review]

**Comment by minio-trusted** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-erasure.sh | :heavy_check_mark: |
| mint-compress-encrypt-dist-erasure.sh | :heavy_check_mark: |
| mint-fs.sh | :x: [more...](#15064a9d-5d4a-42b7-9ac6-c2f7bcee7b6b) |
| mint-gateway-s3.sh | :x: [more...](#9aa1fea7-b11e-458c-8dfe-8c3487d51f57) |
| mint-dist-erasure.sh | :x: [more...](#f8ecfb89-d58a-48e5-9624-a85350cb2485) |
| mint-pools.sh | :x: [more...](#3cbf9795-7f92-486b-a22e-a8c073efe936) |
<a name="15064a9d-5d4a-42b7-9ac6-c2f7bcee7b6b"></a>
### 15123-31425c3/mint-fs.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-k8s4:32538
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0
RUN_ON_FAIL:          0

To get logs, run 'docker cp :/mint/log /tmp/mint-logs'

(1/15) Running aws-sdk-go tests ... done in 7 seconds
(2/15) Running aws-sdk-java tests ... done in 1 seconds
(3/15) Running aws-sdk-php tests ... done in 43 seconds
(4/15) Running aws-sdk-ruby tests ... done in 5 seconds
(5/15) Running awscli tests ... done in 51 seconds
(6/15) Running healthcheck tests ... done in 0 seconds
(7/15) Running mc tests ... done in 23 seconds
FAILED in 3 minutes and 27 seconds
Unhandled exception. System.AggregateException: One or more errors occurred. (A task was canceled.)
 ---> System.Threading.Tasks.TaskCanceledException: A task was canceled.
   at System.Threading.Tasks.Task.GetExceptions(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.Wait()
   at Minio.Functional.Tests.Program.Main(String[] args) in /mint/run/core/minio-dotnet/temp/Minio.Functional.Tests/Program.cs:line 154
--- End of stack trace from previous location ---

   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.Wait()
   at Minio.Functional.Tests.Program.Main(String[] args) in /mint/run/core/minio-dotnet/temp/Minio.Functional.Tests/Program.cs:line 154
(8/15) Running minio-go tests ... done in 55 seconds
(9/15) Running minio-java tests ... done in 17 seconds
(10/15) Running minio-js tests ... done in 1 minutes and 0 seconds
(11/15) Running minio-py tests ... done in 42 seconds
(12/15) Running s3cmd tests ... done in 23 seconds
(13/15) Running s3select tests ... done in 1 seconds
(14/15) Running versioning tests ... done in 3 minutes and 1 seconds

Executed 14 out of 15 tests successfully.
```
<a name="9aa1fea7-b11e-458c-8dfe-8c3487d51f57"></a>
### 15123-31425c3/mint-gateway-s3.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-k8s4:31703
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0
RUN_ON_FAIL:          0

To get logs, run 'docker cp :/mint/log /tmp/mint-logs'

(1/15) Running aws-sdk-go tests ... done in 0 seconds
(2/15) Running aws-sdk-java tests ... done in 1 seconds
(3/15) Running aws-sdk-php tests ... done in 42 seconds
(4/15) Running aws-sdk-ruby tests ... done in 6 seconds
(5/15) Running awscli tests ... done in 50 seconds
(6/15) Running healthcheck tests ... done in 0 seconds
(7/15) Running mc tests ... done in 24 seconds
FAILED in 3 minutes and 1 seconds
Unhandled exception. System.AggregateException: One or more errors occurred. (A task was canceled.)
 ---> System.Threading.Tasks.TaskCanceledException: A task was canceled.
   at System.Threading.Tasks.Task.GetExceptions(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.Wait()
   at Minio.Functional.Tests.Program.Main(String[] args) in /mint/run/core/minio-dotnet/temp/Minio.Functional.Tests/Program.cs:line 148
--- End of stack trace from previous location ---

   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.Wait()
   at Minio.Functional.Tests.Program.Main(String[] args) in /mint/run/core/minio-dotnet/temp/Minio.Functional.Tests/Program.cs:line 148
(8/15) Running minio-go tests ... done in 31 seconds
(9/15) Running minio-java tests ... done in 28 seconds
(10/15) Running minio-js tests ... done in 39 seconds
(11/15) Running minio-py tests ... done in 51 seconds
(12/15) Running s3cmd tests ... done in 1 minutes and 3 seconds
(13/15) Running s3select tests ... done in 3 seconds
(14/15) Running versioning tests ... done in 0 seconds

Executed 14 out of 15 tests successfully.
```
<a name="f8ecfb89-d58a-48e5-9624-a85350cb2485"></a>
### 15123-31425c3/mint-dist-erasure.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-k8s7:32459
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0
RUN_ON_FAIL:          0

To get logs, run 'docker cp :/mint/log /tmp/mint-logs'

(1/15) Running aws-sdk-go tests ... done in 0 seconds
(2/15) Running aws-sdk-java tests ... done in 2 seconds
(3/15) Running aws-sdk-php tests ... done in 42 seconds
(4/15) Running aws-sdk-ruby tests ... done in 7 seconds
(5/15) Running awscli tests ... done in 58 seconds
(6/15) Running healthcheck tests ... done in 0 seconds
(7/15) Running mc tests ... done in 27 seconds
FAILED in 2 minutes and 39 seconds
{
  "name": "minio-dotnet : GetObject_Test3",
  "function": "Task GetObjectAsync(GetObjectArgs args, CancellationToken cancellationToken = default(CancellationToken))",
  "args": {
    "bucketName": "minio-dotnet-example-lb7vmaqhu2tcp8h",
    "objectName": "{b&a}#ab#a",
    "contentType": null,
    "offset": "14",
    "length": "20"
  },
  "duration": 100009,
  "status": "FAIL",
  "alert": "The request was canceled due to the configured HttpClient.Timeout of 100 seconds elapsing.",
  "message": "System.Threading.Tasks.TaskCanceledException: The request was canceled due to the configured HttpClient.Timeout of 100 seconds elapsing.\n ---> System.TimeoutException: The operation was canceled.\n ---> System.Threading.Tasks.TaskCanceledException: The operation was canceled.\n ---> System.IO.IOException: Unable to read data from the transport connection: Operation canceled.\n ---> System.Net.Sockets.SocketException (125): Operation canceled\n   --- End of inner exception stack trace ---\n   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)\n   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource<System.Int32>.GetResult(Int16 token)\n   at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)\n   --- End of inner exception stack trace ---\n   at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)\n   at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)\n   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)\n   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)\n   --- End of inner exception stack trace ---\n   --- End of inner exception stack trace ---\n   at System.Net.Http.HttpClient.HandleFailure(Exception e, Boolean telemetryStarted, HttpResponseMessage response, CancellationTokenSource cts, CancellationToken cancellationToken, CancellationTokenSource pendingRequestsCts)\n   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)\n   at Minio.MinioClient.ExecuteTaskCoreAsync(IEnumerable`1 errorHandlers, HttpRequestMessageBuilder requestMessageBuilder, CancellationToken cancellationToken, Boolean isSts) in /mint/run/core/minio-dotnet/temp/Minio/MinioClient.cs:line 526\n   at Minio.MinioClient.MakeBucketAsync(MakeBucketArgs args, CancellationToken cancellationToken) in /mint/run/core/minio-dotnet/temp/Minio/ApiEndpoints/BucketOperations.cs:line 129\n   at Minio.Functional.Tests.FunctionalTest.Setup_Test(MinioClient minio, String bucketName) in /mint/run/core/minio-dotnet/temp/Minio.Functional.Tests/FunctionalTest.cs:line 468\n   at Minio.Functional.Tests.FunctionalTest.GetObject_3_OffsetLength_Tests(MinioClient minio) in /mint/run/core/minio-dotnet/temp/Minio.Functional.Tests/FunctionalTest.cs:line 4312"
}
(8/15) Running minio-go tests ... done in 1 minutes and 18 seconds
(9/15) Running minio-java tests ... done in 26 seconds
(10/15) Running minio-js tests ... done in 1 minutes and 5 seconds
(11/15) Running minio-py tests ... done in 1 minutes and 9 seconds
(12/15) Running s3cmd tests ... done in 24 seconds
(13/15) Running s3select tests ... done in 3 seconds
(14/15) Running versioning tests ... done in 3 minutes and 3 seconds

Executed 14 out of 15 tests successfully.
```
<a name="3cbf9795-7f92-486b-a22e-a8c073efe936"></a>
### 15123-31425c3/mint-pools.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-k8s7:31230
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0
RUN_ON_FAIL:          0

To get logs, run 'docker cp :/mint/log /tmp/mint-logs'

(1/15) Running aws-sdk-go tests ... done in 8 seconds
(2/15) Running aws-sdk-java tests ... done in 2 seconds
(3/15) Running aws-sdk-php tests ... done in 43 seconds
(4/15) Running aws-sdk-ruby tests ... done in 7 seconds
(5/15) Running awscli tests ... done in 54 seconds
(6/15) Running healthcheck tests ... done in 0 seconds
(7/15) Running mc tests ... done in 30 seconds
FAILED in 3 minutes and 5 seconds
Unhandled exception. System.AggregateException: One or more errors occurred. (A task was canceled.)
 ---> System.Threading.Tasks.TaskCanceledException: A task was canceled.
   at System.Threading.Tasks.Task.GetExceptions(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.Wait()
   at Minio.Functional.Tests.Program.Main(String[] args) in /mint/run/core/minio-dotnet/temp/Minio.Functional.Tests/Program.cs:line 151
--- End of stack trace from previous location ---

   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.Wait()
   at Minio.Functional.Tests.Program.Main(String[] args) in /mint/run/core/minio-dotnet/temp/Minio.Functional.Tests/Program.cs:line 151
(8/15) Running minio-go tests ... done in 1 minutes and 25 seconds
(9/15) Running minio-java tests ... done in 32 seconds
(10/15) Running minio-js tests ... done in 1 minutes and 4 seconds
(11/15) Running minio-py tests ... done in 1 minutes and 21 seconds
(12/15) Running s3cmd tests ... done in 24 seconds
(13/15) Running s3select tests ... done in 4 seconds
(14/15) Running versioning tests ... done in 3 minutes and 4 seconds

Executed 14 out of 15 tests successfully.
```
Deleting image on docker hub
Deleting image locally

**Comment by harshavardhana** [comment]
PTAL @vadmeste
