### PR TITLE
fix: Hold locks before closing all drives

### LINKED ISSUE #8813: setsStorageAPI.Close() data race
```
==================
WARNING: DATA RACE
Write at 0x00c0002afd00 by goroutine 92:
  github.com/minio/minio/cmd.setsStorageAPI.Close()
      d:/minio/minio/cmd/xl-sets.go:53 +0x12d
  github.com/minio/minio/cmd.(*xlSets).ReloadFormat()
      d:/minio/minio/cmd/xl-sets.go:1304 +0x3db
  github.com/minio/minio/cmd.(*xlZones).ReloadFormat()
      d:/minio/minio/cmd/xl-zones.go:1245 +0x22a
  github.com/minio/minio/cmd.(*peerRESTServer).ReloadFormatHandler()
      d:/minio/minio/cmd/peer-rest-server.go:600 +0x200
  github.com/minio/minio/cmd.(*peerRESTServer).ReloadFormatHandler-fm()
      d:/minio/minio/cmd/peer-rest-server.go:570 +0x66
  github.com/minio/minio/cmd.httpTraceHdrs.func1()
      c:/go/src/net/http/server.go:2007 +0x204
  net/http.HandlerFunc.ServeHTTP()
      c:/go/src/net/http/server.go:2007 +0x58
  github.com/gorilla/mux.(*Router).ServeHTTP()
      e:/gopath/pkg/mod/github.com/gorilla/mux@v1.7.0/mux.go:212 +0x145
  github.com/minio/minio/cmd.customHeaderHandler.ServeHTTP()
      d:/minio/minio/cmd/generic-handlers.go:748 +0x19f
  github.com/minio/minio/cmd.(*customHeaderHandler).ServeHTTP()
      <autogenerated>:1 +0x8e
  github.com/minio/minio/cmd.securityHeaderHandler.ServeHTTP()
      d:/minio/minio/cmd/generic-handlers.go:763 +0x250
  github.com/minio/minio/cmd.(*securityHeaderHandler).ServeHTTP()
      <autogenerated>:1 +0x8e
  github.com/minio/minio/cmd.bucketForwardingHandler.ServeHTTP()
      d:/minio/minio/cmd/generic-handlers.go:624 +0x1abd
  github.com/minio/minio/cmd.(*bucketForwardingHandler).ServeHTTP()
      <autogenerated>:1 +0xa4
  github.com/minio/minio/cmd.requestValidityHandler.ServeHTTP()
      d:/minio/minio/cmd/generic-handlers.go:608 +0xb0e
  github.com/minio/minio/cmd.(*requestValidityHandler).ServeHTTP()
      <autogenerated>:1 +0x8e
  github.com/minio/minio/cmd.httpStatsHandler.ServeHTTP()
      d:/minio/minio/cmd/generic-handlers.go:544 +0x1ee
  github.com/minio/minio/cmd.(*httpStatsHandler).ServeHTTP()
      <autogenerated>:1 +0x8e
  github.com/minio/minio/cmd.requestSizeLimitHandler.ServeHTTP()
      d:/minio/minio/cmd/generic-handlers.go:68 +0x18e
  github.com/minio/minio/cmd.(*requestSizeLimitHandler).ServeHTTP()
      <autogenerated>:1 +0xa4
  github.com/minio/minio/cmd.requestHeaderSizeLimitHandler.ServeHTTP()
      d:/minio/minio/cmd/generic-handlers.go:93 +0x394
  github.com/minio/minio/cmd.(*requestHeaderSizeLimitHandler).ServeHTTP()
      <autogenerated>:1 +0x8e
  github.com/minio/minio/cmd.crossDomainPolicy.ServeHTTP()
      d:/minio/minio/cmd/crossdomain-xml-handler.go:51 +0xc7
  github.com/minio/minio/cmd.(*crossDomainPolicy).ServeHTTP()
      <autogenerated>:1 +0x8e
  github.com/minio/minio/cmd.redirectHandler.ServeHTTP()
      d:/minio/minio/cmd/generic-handlers.go:247 +0x7c
  github.com/minio/minio/cmd.(*redirectHandler).ServeHTTP()
      <autogenerated>:1 +0x8e
  github.com/minio/minio/cmd.minioReservedBucketHandler.ServeHTTP()
      d:/minio/minio/cmd/generic-handlers.go:315 +0x99
  github.com/minio/minio/cmd.(*minioReservedBucketHandler).ServeHTTP()
      <autogenerated>:1 +0x8e
  github.com/minio/minio/cmd.cacheControlHandler.ServeHTTP()
      d:/minio/minio/cmd/generic-handlers.go:274 +0xae
  github.com/minio/minio/cmd.(*cacheControlHandler).ServeHTTP()
      <autogenerated>:1 +0x8e
  github.com/minio/minio/cmd.timeValidityHandler.ServeHTTP()
      d:/minio/minio/cmd/generic-handlers.go:385 +0x44c
  github.com/minio/minio/cmd.(*timeValidityHandler).ServeHTTP()
      <autogenerated>:1 +0x8e
  github.com/rs/cors.(*Cors).Handler.func1()
      e:/gopath/pkg/mod/github.com/rs/cors@v1.6.0/cors.go:207 +0x23d
  net/http.HandlerFunc.ServeHTTP()
      c:/go/src/net/http/server.go:2007 +0x58
  github.com/minio/minio/cmd.resourceHandler.ServeHTTP()
      d:/minio/minio/cmd/generic-handlers.go:524 +0xbf
  github.com/minio/minio/cmd.(*resourceHandler).ServeHTTP()
      <autogenerated>:1 +0x8e
  github.com/minio/minio/cmd.authHandler.ServeHTTP()
      d:/minio/minio/cmd/auth-handler.go:480 +0x481
  github.com/minio/minio/cmd.(*authHandler).ServeHTTP()
      <autogenerated>:1 +0x8e
  github.com/minio/minio/cmd.sseTLSHandler.ServeHTTP()
      d:/minio/minio/cmd/generic-handlers.go:798 +0x6ef
  github.com/minio/minio/cmd.(*sseTLSHandler).ServeHTTP()
      <autogenerated>:1 +0x8e
  github.com/minio/minio/cmd.reservedMetadataHandler.ServeHTTP()
      d:/minio/minio/cmd/generic-handlers.go:136 +0x394
  github.com/minio/minio/cmd.(*reservedMetadataHandler).ServeHTTP()
      <autogenerated>:1 +0x8e
  github.com/minio/minio/cmd.criticalErrorHandler.ServeHTTP()
      d:/minio/minio/cmd/generic-handlers.go:780 +0xc0
  github.com/minio/minio/cmd.(*criticalErrorHandler).ServeHTTP()
      <autogenerated>:1 +0x8e
  github.com/minio/minio/cmd/http.(*Server).Start.func1()
      d:/minio/minio/cmd/http/server.go:100 +0x166
  net/http.HandlerFunc.ServeHTTP()
      c:/go/src/net/http/server.go:2007 +0x58
  net/http.serverHandler.ServeHTTP()
      c:/go/src/net/http/server.go:2802 +0xd5
  net/http.(*conn).serve()
      c:/go/src/net/http/server.go:1890 +0x83e

Previous read at 0x00c0002afd00 by goroutine 206:
  runtime.slicecopy()
      c:/go/src/runtime/slice.go:197 +0x0
  github.com/minio/minio/cmd.(*xlSets).GetDisks.func1()
      d:/minio/minio/cmd/xl-sets.go:251 +0x241
  github.com/minio/minio/cmd.xlObjects.HealBucket()
      d:/minio/minio/cmd/xl-v1-healing.go:46 +0x78
  github.com/minio/minio/cmd.(*xlSets).HealBucket()
      d:/minio/minio/cmd/xl-sets.go:1513 +0x351
  github.com/minio/minio/cmd.(*xlZones).HealBucket()
      d:/minio/minio/cmd/xl-zones.go:1285 +0x1a2
  github.com/minio/minio/cmd.bgHealBucket()
      d:/minio/minio/cmd/background-heal-ops.go:174 +0xdb
  github.com/minio/minio/cmd.(*healRoutine).run()
      d:/minio/minio/cmd/background-heal-ops.go:83 +0x4e6

Goroutine 92 (running) created at:
  net/http.(*Server).Serve()
      c:/go/src/net/http/server.go:2928 +0x5bc
  github.com/minio/minio/cmd/http.(*Server).Start()
      d:/minio/minio/cmd/http/server.go:112 +0x417
  github.com/minio/minio/cmd.serverMain.func1()
      d:/minio/minio/cmd/server-main.go:331 +0x3f

Goroutine 206 (running) created at:
  github.com/minio/minio/cmd.startBackgroundHealing()
      d:/minio/minio/cmd/background-heal-ops.go:121 +0x1c3
==================
[...]
```
## Expected Behavior

No data race.

## Current Behavior

Data race.

Points here: https://github.com/minio/minio/blob/5aa5dcdc6dd94f186addcb5afd9c443ff09e3be5/cmd/xl-sets.go#L53

And here: https://github.com/minio/minio/blob/5aa5dcdc6dd94f186addcb5afd9c443ff09e3be5/cmd/xl-sets.go#L251

It seems the former operation needs access to the mutex protecting the slice.

## Steps to Reproduce (for bugs)

1. Build minio with `-race`
2. Start in distributed mode.
3. Secondary servers usually shows this message.

### PR DESCRIPTION
**Pull request by harshavardhana**
## Description
fix: Hold locks before closing all drives

## Motivation and Context
Fixes #8813

## How to test this PR?
As mentioned in #8813 , easily seen with `go build -race`

## Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [ ] Fixes a regression (If yes, please add `commit-id` or `PR #` here)
- [ ] Documentation needed
- [ ] Unit tests needed
- [ ] Functional tests needed (If yes, add [mint](https://github.com/minio/mint) PR # here: )

### CODE REVIEW

**Comment by minio-ops** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-xl.sh | :heavy_check_mark: |
| mint-worm.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :x: [more...](#eee80a86-a5c9-4f8a-8892-7e599030fb97) |
| mint-dist-xl.sh | :x: [more...](#6e91e7cf-44eb-45bd-bd4c-bd5186d3bdeb) |
<a name="6e91e7cf-44eb-45bd-bd4c-bd5186d3bdeb"></a>
### 8818-e306b4e/mint-dist-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.55:30913
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 4b6106357073:/mint/log /tmp/mint-logs'

(1/13) Running awscli tests ... FAILED in 5 minutes and 14 seconds
{"name": "awscli", "duration": 311081, "function": "make_bucket\n", "status": "FAIL", "error": "Connect timeout on endpoint URL: "http://72.28.97.55:30913/awscli-mint-test-bucket-24306""}

Executed 0 out of 13 tests successfully.
```
<a name="eee80a86-a5c9-4f8a-8892-7e599030fb97"></a>
### 8818-e306b4e/mint-large-bucket.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.53:30395
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 71a796e2bbdb:/mint/log /tmp/mint-logs'

(1/13) Running awscli tests ... done in 2 minutes and 15 seconds
(2/13) Running aws-sdk-java tests ... done in 1 seconds
(3/13) Running aws-sdk-ruby tests ... done in 6 seconds
(4/13) Running mc tests ... done in 49 seconds
(5/13) Running minio-go tests ... FAILED in 3 minutes and 21 seconds
{
  "args": {},
  "duration": 101812,
  "error": "Please reduce your request",
  "function": "testStorageClassMetadataCopyObject()",
  "message": "CopyObject failed on RRS",
  "name": "minio-go: testStorageClassMetadataCopyObject",
  "status": "FAIL"
}

Executed 4 out of 13 tests successfully.
```
Deleting image on docker hub
Deleting image locally

File: cmd/xl-sets.go [hunk 1]
```diff
@@ -1488,7 +1488,9 @@ func (s *xlSets) HealFormat(ctx context.Context, dryRun bool) (res madmin.HealRe
 		s.format = refFormat
 
 		// Disconnect/relinquish all existing disks, lockers and reconnect the disks, lockers.
+		s.xlDisksMu.Lock()
 		s.xlDisks.Close()
+		s.xlDisksMu.Unlock()
```
Comment (krishnasrinivas) [inline cmd/xl-sets.go:1493]: we used to have lock statements before right?

**Review by krishnasrinivas — APPROVED** [review]

File: cmd/xl-sets.go (hunk 1 above)
Comment (harshavardhana) [reply cmd/xl-sets.go:1493]: Yes it was changed for some reason @krishnasrinivas

**Review by krisis — APPROVED** [review]
