### PR TITLE
Treat 0.0.0.0 as local address in --address flag

### LINKED ISSUE #4382: Can't explicitly tell minio to serve on 0.0.0.0
Passing `--address 0.0.0.0:9000` to the `serve` command causes Minio to exit with an error:

## Expected Behaviour
Minio should bind on all local addresses, as it does when no `--address` is specified or `--address :port` is specified.

## Current Behaviour
Minio refuses to start with an `--address` flag using `0.0.0.0` for the IP portion. It will error with:

> FATA[0000] Invalid address ‘0.0.0.0:9000’ in command line argument.  cause=host in server address should be this server source=[server-main.go:138:serverHandleCmdArgs()]

## Steps to Reproduce (for bugs)

Run `minio server --address "0.0.0.0:9000" /path/to/storage`

## Context
Configuring minio as a dependency in a project means identifying the address to listen on in each environment (e.g. dev might be 0.0.0.0 for debugging purposes, prod might be 127.0.0.1). The current situation requires special-casing the 0.0.0.0 address when populating a configuration file for the minio system service

## Your Environment
* Version used (`minio version`): 2017-05-05T01:14:51Z
* Operating System and version (`name -a`): Linux gunstrader 3.16.0-4-amd64 #1 SMP Debian 3.16.43-2 (2017-04-30) x86_64 GNU/Linux

### PR DESCRIPTION
**Pull request by krisis**
## Description

This change treats 0.0.0.0 as a local network address for `--address` flag's argument.
Fixes #4382
## Motivation and Context

See #4382 
`minio server --address "0.0.0.0:9000" /tmp/fs` is valid and should work. Without this change, it fails saying "0.0.0.0" is a non-local address, which is incorrect.

## How Has This Been Tested?

Manually and via unit test.

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

File: cmd/net_test.go [hunk 1]
```diff
@@ -226,6 +226,7 @@ func TestCheckLocalServerAddr(t *testing.T) {
 		{"example.org:54321", fmt.Errorf("host in server address should be this server")},
 		{":0", fmt.Errorf("port number must be between 1 to 65535")},
 		{":-10", fmt.Errorf("port number must be between 1 to 65535")},
+		{"0.0.0.0:9000", nil},
```
Comment (balamurugana) [inline cmd/net_test.go]: can you move this into success case listing?

**Review by balamurugana — CHANGES_REQUESTED** [review]
Minor comment.

File: cmd/net_test.go (hunk 1 above)
Comment (krisis) [reply cmd/net_test.go]: @balamurugana done.

**Review by hackintoshrao — APPROVED** [review]

**Review by balamurugana — APPROVED** [review]
