### PR TITLE
Validate user provided SSE-C key on Head Object API

### LINKED ISSUE #6598: .part.minio files left on a target if the sse-c encryption key is incorrect
## Expected Behavior

``.part.minio`` should not remain when the encryption key is incorrect.

```
$ mc mirror --encrypt-key "mysite/test-enc1=$(echo wrong-password | openssl dgst -sha256 -binary | xxd -p -c 32 -l 16)" mysite/test-enc1/ targetdir/
 0 B / ? ┃░░░░░░┃mc: <ERROR> Failed to copy `https://mysite.com/test-enc1/12.rand`. Access Denied.

$ ls -la targetdir/
total 8
drwxr-xr-x  2 arno arno 4096 Oct  9 21:42 .
drwxr-xr-x 40 arno arno 4096 Oct  9 21:41 ..
```

## Current Behavior

``.part.minio``  remain when the encryption key is incorrect.

```
$ mc mirror --encrypt-key "mysite/test-enc1=$(echo wrong-password | openssl dgst -sha256 -binary | xxd -p -c 32 -l 16)" mysite/test-enc1/ targetdir/
 0 B / ? ┃░░░░░░┃mc: <ERROR> Failed to copy `https://mysite.com/test-enc1/12.rand`. Access Denied.

$ ls -la targetdir/
total 8
drwxr-xr-x  2 arno arno 4096 Oct  9 21:42 .
drwxr-xr-x 40 arno arno 4096 Oct  9 21:41 ..
-rw-r--r--  1 arno arno    0 Oct  9 21:42 10.rand.part.minio
-rw-r--r--  1 arno arno    0 Oct  9 21:42 11.rand.part.minio
-rw-r--r--  1 arno arno    0 Oct  9 21:42 12.rand.part.minio
-rw-r--r--  1 arno arno    0 Oct  9 21:42 1.rand.part.minio
```

## Possible Solution

When the encryption key is incorrect, the minio client should hesitate creating the ``.part.minio`` file.

## Steps to Reproduce (for bugs)
1.  ``mkdir sourcedir; cd sourcedir; for i in $(seq 1 50); do openssl rand 1024 > $i.rand; done``
2. ``mc mirror --encrypt-key "mysite/test-enc1=$(echo original-password | openssl dgst -sha256 -binary | xxd -p -c 32 -l 16)" sourcedir/ mysite/test-enc1/``
3. ``mc mirror --encrypt-key "mysite/test-enc1=$(echo wrong-password | openssl dgst -sha256 -binary | xxd -p -c 32 -l 16)" mysite/test-enc1/ targetdir/``
4. See there are 4 empty files with the ``.part.minio`` extension in the ``targetdir/``

## Your Environment

minio client ``2018-09-26T00:42:43Z``
minio server ``2018-10-06T00:15:16Z``

### PR DESCRIPTION
**Pull request by kannappanr**
## Description
User provided SSE-C key is not currently validated on a Head Object API. 
Because of which, the HEAD Object API returns 200 for an incorrect SSE-C key.

Fixes #6598

## Motivation and Context
Issue #6598 

## Regression
No.

## How Has This Been Tested?
```
mc cp --encrypt-key "x1minio/test-enc1=$(echo original-password | openssl dgst -sha256 -binary | xxd -p -c 32 -l 16)" /tmp/sourcedir/1.rand x1minio/test-enc1/
mc stat --debug --encrypt-key "x1minio/test-enc1=$(echo wrong-password | openssl dgst -sha256 -binary | xxd -p -c 32 -l 16)" x1minio/test-enc1/1.rand
```
Without the changes, `HEAD` call would return `200` and with the change, it will return `403` just like `AWS S3`

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added unit tests to cover my changes.
- [ ] I have added/updated functional tests in [mint](https://github.com/minio/mint). (If yes, add `mint` PR # here: )
- [x] All new and existing tests passed.

### CODE REVIEW

**Review by harshavardhana — CHANGES_REQUESTED** [review]
This is not a correct way to fix it @kannappanr we should take the objInfo returned by GetObjectInfo() and validate the provide SSE-C keys. We shouldn't attempt read the body of the object.

File: cmd/object-handlers.go [hunk 1]
```diff
@@ -534,6 +534,24 @@ func (api objectAPIHandlers) HeadObjectHandler(w http.ResponseWriter, r *http.Re
 			case crypto.S3.IsEncrypted(objInfo.UserDefined):
 				w.Header().Set(crypto.SSEHeader, crypto.SSEAlgorithmAES256)
 			case crypto.SSEC.IsEncrypted(objInfo.UserDefined):
+				sealedKey, err := crypto.SSEC.ParseMetadata(objInfo.UserDefined)
```
Comment (harshavardhana) [inline cmd/object-handlers.go]: We need a helper function here for objInfo @kannappanr we don't need to pile all this here move this to cmd/encryption-v1.go

**Review by harshavardhana — CHANGES_REQUESTED** [review]

File: cmd/object-handlers.go (hunk 1 above)
Comment (kannappanr) [reply cmd/object-handlers.go]: done

Comment (aead) [reply cmd/object-handlers.go]: @kannappanr We can use: #6609

**Review by poornas — APPROVED** [review]
LGTM

**Review by harshavardhana — APPROVED** [review]
