### PR TITLE
custom user-agent transport wrapper

### LINKED ISSUE #20783: User-Agent header is not set during OpenID initialization
## NOTE
If this case is urgent, please subscribe to [Subnet](https://min.io/pricing) so that our 24/7 support team may help you faster.

## Expected Behavior
A non-default User-Agent header should be set for all requests.

## Current Behavior
The default `Go-http-client/1.1` User-Agent header is set during the request to the OpenID configuration endpoint `.well-known/openid-configuration`

## Possible Solution
One possible solution is to implement a custom RoundTripper in `internal/http/transports.go` which adds a default User-Agent identifying minio if one is not already set.

## Steps to Reproduce (for bugs)

1. Setup a OIDC compliant Authentication server (EG Keycloak) with access logs
2. Setup minio to use Authentication server
3. Check access logs and see that minio uses the default Go User-Agent

## Context
Blocking default User-Agents is a trivial way to stop low-effort scanning and attacks.

## Regression
No

## Your Environment

* Version used (`minio --version`): `minio version RELEASE.2024-11-07T00-52-20Z (commit-id=cefc43e4daa4cbb490ef6726ea374e26a93eb85e)`
* Server setup and configuration:
```bash
MINIO_IDENTITY_OPENID_CONFIG_URL_PRIMARY_IAM="https://keycloak.domain.tld/realms/Users/.well-known/openid-configuration"
MINIO_IDENTITY_OPENID_CLIENT_ID_PRIMARY_IAM="minio"
MINIO_IDENTITY_OPENID_CLIENT_SECRET_PRIMARY_IAM="<OpenID Secret>"
MINIO_IDENTITY_OPENID_DISPLAY_NAME_PRIMARY_IAM="Keycloak"
MINIO_IDENTITY_OPENID_SCOPES_PRIMARY_IAM="openid,email,profile"
MINIO_IDENTITY_OPENID_REDIRECT_URI_DYNAMIC_PRIMARY_IAM="off"
MINIO_IDENTITY_OPENID_CLAIM_USERINFO=off

MINIO_IDENTITY_OPENID_VENDOR="keycloak"
MINIO_IDENTITY_OPENID_KEYCLOAK_ADMIN_URL="https://keycloak.domain.tld/admin"
MINIO_IDENTITY_OPENID_KEYCLOAK_REALM="Users"
```
* Operating System and version (`uname -a`): `Linux minio 4.18.0-553.27.1.el8_10.x86_64 #1 SMP Fri Oct 18 06:18:15 EDT 2024 x86_64 x86_64 x86_64 GNU/Linux`

### PR DESCRIPTION
**Pull request by 0xMALVEE**
## Community Contribution License
All community contributions in this pull request are licensed to the project maintainers
under the terms of the [Apache 2 license](https://www.apache.org/licenses/LICENSE-2.0). 
By creating this pull request I represent that I have the right to license the 
contributions to the project maintainers under the Apache 2 license.

## Description
closes: https://github.com/minio/minio/issues/20783

## Motivation and Context
User-Agent header is not set during OpenID initialization

## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Optimization (provides speedup with no functional changes)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [ ] Fixes a regression (If yes, please add `commit-id` or `PR #` here)
- [ ] Unit tests added/updated
- [ ] Internal documentation updated
- [ ] Create a documentation update request [here](https://github.com/minio/docs/issues/new?label=doc-change,title=Doc+Updated+Needed+For+PR+github.com%2fminio%2fminio%2fpull%2fNNNNN)

### CODE REVIEW

File: internal/useragent/useragent.go [hunk 1]
```diff
@@ -0,0 +1,15 @@
+package useragent
```
Comment (dormanze) [inline internal/useragent/useragent.go]: You need to add the Copyright and file description at the beginning of the document.

File: internal/useragent/useragent.go [hunk 2]
```diff
@@ -0,0 +1,32 @@
...
+// GNU Affero General Public License for more details.
+//
+// You should have received a copy of the GNU Affero General Public License
+// along with this program.  If not, see <http://www.gnu.org/licenses/>.
+
+package useragent
+
+var provider = func() string {
+	return "Go-http-client/1.1"
+}
```
Comment (klauspost) [inline internal/useragent/useragent.go]: (read other comments first)

Make this an atomic, so it can be updated without races.

```suggestion
var provider atomic.Pointer[func() string]
```

File: internal/useragent/useragent.go [hunk 3]
```diff
@@ -0,0 +1,32 @@
...
+
+// Register sets a custom function to provide the User-Agent string.
+func Register(f func() string) {
+	provider = f
+}
+
+// Get returns the current User-Agent string.
+func Get() string {
+	return provider()
```
Comment (klauspost) [inline internal/useragent/useragent.go]:
```suggestion
	if fn := provider.Load(); fn != nil {
		return fn()
	}
	return "minio/go-http"
```

File: internal/http/transports.go [hunk 4]
```diff
@@ -183,3 +184,23 @@ func (s ConnSettings) NewRemoteTargetHTTPTransport(insecure bool) func() *http.T
...
+}
+
+func (u *uaTransport) RoundTrip(req *http.Request) (*http.Response, error) {
+	req2 := req.Clone(req.Context())
+	req2.Header.Set("User-Agent", u.ua)
+	return u.rt.RoundTrip(req2)
+}
+
+// WithUserAgent wraps an existing transport with custom User-Agent
+func WithUserAgent(rt http.RoundTripper) http.RoundTripper {
```
Comment (klauspost) [inline internal/http/transports.go]: Honestly it feels slightly overengineered that this isn't just...
```suggestion
func WithUserAgent(rt http.RoundTripper, getUA func() string) http.RoundTripper {
```

That also makes it very obvious where the useragent is actually from, and not that it is pulled from a global var somewhere.

Simpler to understand and simpler to use, no need to register anything.

Comment (0xMALVEE) [reply internal/http/transports.go]: yes I agree, the problem I was getting import cycle error due to the getUserAgent() living in package cmd

Comment (klauspost) [reply internal/http/transports.go]: What do you mean? You aren't importing more. You are just sending a `func() string`.

Comment (0xMALVEE) [reply internal/http/transports.go]: ohh, not here. I meant the place where I would be using the WithUserAgent in for example in a different package openid in jwt.go

Comment (klauspost) [reply internal/http/transports.go]: Oh, with jwt... Well, you could just wrap it on the 2 places `openid.LookupConfig` is called.

Comment (0xMALVEE) [reply internal/http/transports.go]: okay, this sounds good. I will update the code

**Review by dormanze — COMMENTED** [review]
LGTM, Approved

File: internal/config/identity/openid/openid.go [hunk 5]
```diff
@@ -199,7 +199,7 @@ func (r *Config) Clone() Config {
 }
 
 // LookupConfig lookup jwks from config, override with any ENVs.
-func LookupConfig(s config.Config, transport http.RoundTripper, closeRespFn func(io.ReadCloser), serverRegion string) (c Config, err error) {
+func LookupConfig(s config.Config, transport http.RoundTripper, closeRespFn func(io.ReadCloser), serverRegion string, getUA func() string) (c Config, err error) {
```
Comment (klauspost) [inline internal/config/identity/openid/openid.go]: The transport is already wrapped here in both call sites, you can revert this (and below)

**Review by klauspost — APPROVED** [review]
Nice and clean :)

**Review by harshavardhana — APPROVED** [review]

**Comment by harshavardhana** [comment]
Please send this to miniohq/eos @0xMALVEE

**Comment by 0xMALVEE** [comment]
> Please send this to miniohq/eos @0xMALVEE

ok
