### PR TITLE
postForm: Follow success_action_status requirement

### LINKED ISSUE #3464: Support success_action_status header
## Expected Behavior
Minio should return a status code equal to the `success_action_status` header during a POST or PUT request.

## Current Behavior
It always returns a 204.

## Steps to Reproduce (for bugs)
Make a POST request to create any object with the `success_action_status` header set to 200 and see the response status code is set to 204. Haven't tested with a PUT but assume it will work the same as a POST request.

## Context
Trying to use FineUploader and it seems to only accept a 200 response code as a success.

## Your Environment
* Version used: RELEASE.2016-12-13T17-19-42Z
* Environment name and version (e.g. nginx 1.9.1): docker

### PR DESCRIPTION
**Pull request by vadmeste**
## Description
S3 spec requires that Post Object response depends on the passed success_action_status. This commit implements that requirement.

## Motivation and Context
Fixes #3464 

## How Has This Been Tested?
go test and manually

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

File: cmd/bucket-handlers.go [hunk 1]
```diff
@@ -448,11 +448,22 @@ func (api objectAPIHandlers) PostPolicyBucketHandler(w http.ResponseWriter, r *h
 	w.Header().Set("ETag", "\""+objInfo.MD5Sum+"\"")
 	w.Header().Set("Location", getObjectLocation(bucket, object))
 
-	// Set common headers.
-	setCommonHeaders(w)
+	// Decide what http response to send depending on success_action_status parameter
+	switch formValues["Success_action_status"] {
```
Comment (harshavardhana) [inline cmd/bucket-handlers.go]: Shouldn't "S" be small case here?

**Review by harshavardhana — COMMENTED** [review]
Only one comment.

File: cmd/bucket-handlers.go [hunk 2]
```diff
@@ -448,11 +448,22 @@ func (api objectAPIHandlers) PostPolicyBucketHandler(w http.ResponseWriter, r *h
...
+	case "201":
+		resp := encodeResponse(PostResponse{
```
Comment (harshavardhana) [inline cmd/bucket-handlers.go:454]: Don't use unkeyed values place the fields properly .Since bucket and object are of string type it would be hard if they get changed and we wouldn't know. Subtle bugs like this can arise.

**Review by harshavardhana — CHANGES_REQUESTED** [review]
One more.

File: cmd/bucket-handlers.go (hunk 2 above)
Comment (vadmeste) [reply cmd/bucket-handlers.go:454]: > Don't use unkeyed values place the fields properly .Since bucket and object are of string type it would be hard if they get changed and we wouldn't know. Subtle bugs like this can arise.

yes, you are right. I fixed it.

File: cmd/bucket-handlers.go (hunk 1 above)
Comment (vadmeste) [reply cmd/bucket-handlers.go]: Currently, all fields in formValues have canonical names that's why it starts by a capital S.

**Review by harshavardhana — APPROVED** [review]

File: cmd/bucket-handlers.go (hunk 1 above)
Comment (harshavardhana) [reply cmd/bucket-handlers.go]: Perhaps you can do http.Canonical so that it gets easier to understand the purpose.
