### PR TITLE
xl: All nodes create meta volumes in its local disks

### LINKED ISSUE #8781: background-ops not found after Update
After Update to the latest version of minio i become the follow error at startup

```
Jan  9 15:06:18 vstorage01 minio[4726]: Error: Bucket not found: .minio.sys/background-ops
Jan  9 15:06:18 vstorage01 minio[4726]:        2: cmd/data-usage.go:100:cmd.runDataUsageInfoForXLZones()
Jan  9 15:06:18 vstorage01 minio[4726]:        1: cmd/data-usage.go:54:cmd.runDataUsageInfoUpdateRoutine()
```

## Expected Behavior
There should no error displayed on system startup

## Current Behavior
error message in syslog on all minio servers

```
Jan  9 15:06:18 vstorage01 minio[4726]: Error: Bucket not found: .minio.sys/background-ops
Jan  9 15:06:18 vstorage01 minio[4726]:        2: cmd/data-usage.go:100:cmd.runDataUsageInfoForXLZones()
Jan  9 15:06:18 vstorage01 minio[4726]:        1: cmd/data-usage.go:54:cmd.runDataUsageInfoUpdateRoutine()
```

## Possible Solution
if the structure is missing, it should be created.

## Steps to Reproduce (for bugs)
1. Error comes after update to the build of 9. jan. The previous release was 11. sept 2019

## Your Environment
* Version used 2020-01-09
* Environment name and version (e.g. nginx 1.9.1): -
* Server type and version: ubuntu 18.04 lts
* Operating System and version (`uname -a`): Linux vstorage01 4.15.0-62-generic #69-Ubuntu SMP Wed Sep 4 20:55:53 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
* Link to your project: -

### PR DESCRIPTION
**Pull request by vadmeste**
## Description
    xl: All nodes create meta volumes in its local disks
    
    Meta volumes directories, tmp/, background-ops/, etc..
    under .minio.sys are created when disks are formatted
    but also when the cluster is started.
    
    The PR will make each node creates meta volumes
    in its local disks and stop relying on the first disk
    since the first node could be offline.

## Motivation and Context
Fixes #8781 

## How to test this PR?
1. Initialize a four nodes with four disks with this old version: minio.RELEASE.2019-10-12T01-39-57Z
2. Upgrade to the latest release 

## Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [x] Fixes a regression (If yes, please add `commit-id` or `PR #` here)
- [ ] Documentation needed
- [ ] Unit tests needed
- [ ] Functional tests needed (If yes, add [mint](https://github.com/minio/mint) PR # here: )

### CODE REVIEW

File: cmd/format-xl.go [hunk 1]
```diff
@@ -776,10 +776,12 @@ func initFormatXL(ctx context.Context, storageDisks []StorageAPI, setCount, driv
 // Make XL backend meta volumes.
 func makeFormatXLMetaVolumes(disk StorageAPI) error {
 	// Attempt to create MinIO internal buckets.
-	err := disk.MakeVolBulk(minioMetaBucket, minioMetaTmpBucket, minioMetaMultipartBucket, minioMetaBackgroundOpsBucket)
-	if err != nil {
-		if !IsErrIgnored(err, initMetaVolIgnoredErrs...) {
-			return err
+	for _, vol := range []string{minioMetaBucket, minioMetaTmpBucket, minioMetaMultipartBucket, minioMetaBackgroundOpsBucket} {
+		err := disk.MakeVol(vol)
```
Comment (harshavardhana) [inline cmd/format-xl.go]: This is incorrect PR @vadmeste you need make MakeVolBulk ignore `errVolumeExists` that's all

**Review by harshavardhana — CHANGES_REQUESTED** [review]

**Comment by minio-ops** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-compression-xl.sh | :heavy_check_mark: |
| mint-xl.sh | :heavy_check_mark: |
| mint-compression-dist-xl.sh | :heavy_check_mark: |
| mint-compression-fs.sh | :heavy_check_mark: |
| mint-worm.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-dist-xl.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :x: [more...](#d8bf7a85-3328-4a20-b83e-29b209be44fb) |
<a name="d8bf7a85-3328-4a20-b83e-29b209be44fb"></a>
### 8786-ab6f121/mint-large-bucket.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.59:31924
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 1d68e8b3d044:/mint/log /tmp/mint-logs'

(1/13) Running awscli tests ... done in 2 minutes and 26 seconds
(2/13) Running aws-sdk-java tests ... done in 1 seconds
(3/13) Running aws-sdk-ruby tests ... done in 8 seconds
(4/13) Running mc tests ... done in 1 minutes and 24 seconds
(5/13) Running minio-go tests ... FAILED in 3 minutes and 58 seconds
{
  "args": {},
  "duration": 106167,
  "error": "Please reduce your request",
  "function": "testStorageClassMetadataCopyObject()",
  "message": "CopyObject failed on RRS",
  "name": "minio-go: testStorageClassMetadataCopyObject",
  "status": "FAIL"
}

Executed 4 out of 13 tests successfully.
```
Deleting image on docker hub
Deleting image locally

**Comment by minio-ops** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-compression-xl.sh | :heavy_check_mark: |
| mint-xl.sh | :heavy_check_mark: |
| mint-compression-dist-xl.sh | :heavy_check_mark: |
| mint-compression-fs.sh | :heavy_check_mark: |
| mint-worm.sh | :heavy_check_mark: |
| mint-dist-xl.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :x: [more...](#05d0548b-4b8c-4a74-b91f-8a7247769135) |
| mint-fs.sh | :x: [more...](#91c223b9-718a-40af-a11c-bc0da67f72ff) |
<a name="05d0548b-4b8c-4a74-b91f-8a7247769135"></a>
### 8786-9714217/mint-large-bucket.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.52:30153
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 4998e4fbdd68:/mint/log /tmp/mint-logs'

(1/13) Running awscli tests ... done in 2 minutes and 22 seconds
(2/13) Running aws-sdk-java tests ... done in 1 seconds
(3/13) Running aws-sdk-ruby tests ... done in 12 seconds
(4/13) Running mc tests ... done in 1 minutes and 17 seconds
(5/13) Running minio-go tests ... FAILED in 3 minutes and 10 seconds
{
  "args": {},
  "duration": 66338,
  "error": "Please reduce your request",
  "function": "testStorageClassMetadataCopyObject()",
  "message": "CopyObject failed on RRS",
  "name": "minio-go: testStorageClassMetadataCopyObject",
  "status": "FAIL"
}

Executed 4 out of 13 tests successfully.
```
<a name="91c223b9-718a-40af-a11c-bc0da67f72ff"></a>
### 8786-9714217/mint-fs.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.55:32256
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp fc762ce7cd04:/mint/log /tmp/mint-logs'

(1/13) Running awscli tests ... FAILED in 5 minutes and 11 seconds
{"name": "awscli", "duration": 308645, "function": "make_bucket\n", "status": "FAIL", "error": "Connect timeout on endpoint URL: "http://72.28.97.55:32256/awscli-mint-test-bucket-26863""}

Executed 0 out of 13 tests successfully.
```
Deleting image on docker hub
Deleting image locally

**Review by harshavardhana — APPROVED** [review]

**Review by harshavardhana — APPROVED** [review]

**Comment by minio-ops** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-xl.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-dist-xl.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :x: [more...](#d1f3f821-d1ac-4a8d-8486-84814bf0bc53) |
| mint-worm.sh | :x: [more...](#a248bb24-073d-4cbd-b5b7-fa72496bdc94) |
<a name="d1f3f821-d1ac-4a8d-8486-84814bf0bc53"></a>
### 8786-8d3a545/mint-large-bucket.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.56:30243
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 236f37506c83:/mint/log /tmp/mint-logs'

(1/13) Running awscli tests ... done in 2 minutes and 18 seconds
(2/13) Running aws-sdk-java tests ... done in 1 seconds
(3/13) Running aws-sdk-ruby tests ... done in 6 seconds
(4/13) Running mc tests ... done in 56 seconds
(5/13) Running minio-go tests ... FAILED in 4 minutes and 3 seconds
{
  "args": {},
  "duration": 121754,
  "error": "Please reduce your request",
  "function": "testStorageClassMetadataCopyObject()",
  "message": "CopyObject failed on RRS",
  "name": "minio-go: testStorageClassMetadataCopyObject",
  "status": "FAIL"
}

Executed 4 out of 13 tests successfully.
```
<a name="a248bb24-073d-4cbd-b5b7-fa72496bdc94"></a>
### 8786-8d3a545/mint-worm.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.55:30770
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            worm
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 2d51bd492b1b:/mint/log /tmp/mint-logs'

(1/1) Running worm tests ... FAILED in 2 minutes and 0 seconds
{
  "alert": "",
  "args": {
    "bucketName": "bucket-04nio9xqbn0k6jkbjz0jyi1dayvfrmqezn7mr1uagdfitk9wif15k22",
    "expiry": 60000000000,
    "objectName": "testObject"
  },
  "duration": 120251,
  "error": "RequestError: send request failed\ncaused by: Put http://72.28.97.55:30770/bucket-04nio9xqbn0k6jkbjz0jyi1dayvfrmqezn7mr1uagdfitk9wif15k22: dial tcp 72.28.97.55:30770: i/o timeout",
  "function": "PutAndDelete",
  "message": "WORM_MODE ON  - CreateBucket Failed",
  "name": "test worm mode",
  "status": "FAIL"
}

Executed 0 out of 1 tests successfully.
```
Deleting image on docker hub
Deleting image locally

**Comment by minio-ops** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-xl.sh | :heavy_check_mark: |
| mint-worm.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-dist-xl.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :x: [more...](#9dc6080e-1ad7-4463-ae79-6a00dc8a1e23) |
<a name="9dc6080e-1ad7-4463-ae79-6a00dc8a1e23"></a>
### 8786-f56de0f/mint-large-bucket.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.55:30784
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp d775a74176f0:/mint/log /tmp/mint-logs'

(1/13) Running awscli tests ... FAILED in 5 minutes and 16 seconds
{"name": "awscli", "duration": 313691, "function": "make_bucket\n", "status": "FAIL", "error": "Connect timeout on endpoint URL: "http://72.28.97.55:30784/awscli-mint-test-bucket-18642""}

Executed 0 out of 13 tests successfully.
```
Deleting image on docker hub
Deleting image locally

File: cmd/format-xl.go [hunk 2]
```diff
@@ -632,8 +632,8 @@ func initFormatXLMetaVolume(storageDisks []StorageAPI, formats []*formatXLV3) er
 	for index := range storageDisks {
 		index := index
 		g.Go(func() error {
-			if formats[index] == nil || storageDisks[index] == nil {
-				// Ignore create meta volume on disks which are not found.
+			if formats[index] == nil || storageDisks[index] == nil || !storageDisks[index].IsLocal() {
+				// Ignore create meta volume on disks which are not found or not local.
```
Comment (donatello) [inline cmd/format-xl.go]: Since most disks are not going to be local, it seems a majority of these go routines are going to return while doing no work. It's more efficient to only start go routines for local disks.

**Review by donatello — CHANGES_REQUESTED** [review]

File: cmd/format-xl.go (hunk 2 above)
Comment (harshavardhana) [reply cmd/format-xl.go]: @vadmeste ^^

**Comment by minio-ops** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-xl.sh | :heavy_check_mark: |
| mint-worm.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-dist-xl.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :x: [more...](#e820ad70-163f-4688-b416-052039ca351c) |
<a name="e820ad70-163f-4688-b416-052039ca351c"></a>
### 8786-bf4bfa1/mint-large-bucket.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.58:30399
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 37a4c823e72c:/mint/log /tmp/mint-logs'

(1/13) Running awscli tests ... done in 2 minutes and 20 seconds
(2/13) Running aws-sdk-java tests ... done in 1 seconds
(3/13) Running aws-sdk-ruby tests ... done in 6 seconds
(4/13) Running mc tests ... done in 1 minutes and 39 seconds
(5/13) Running minio-go tests ... FAILED in 1 minutes and 53 seconds
{
  "args": {
    "bucketName": "minio-go-test-dgsaag1umg305iy1",
    "objectName": "44izq0jbwclq3xgz2f5vaxhrdsexzo"
  },
  "duration": 5757,
  "error": "The bucket you tried to delete is not empty",
  "function": "GetObject(bucketName, objectName)",
  "message": "Cleanup failed",
  "name": "minio-go: testGetObjectReadSeekFunctional",
  "status": "FAIL"
}

Executed 4 out of 13 tests successfully.
```
Deleting image on docker hub
Deleting image locally

File: cmd/storage-interface.go [hunk 3]
```diff
@@ -27,6 +27,7 @@ type StorageAPI interface {
 
 	// Storage operations.
 	IsOnline() bool // Returns true if disk is online.
+	IsLocal() bool
```
Comment (harshavardhana) [inline cmd/storage-interface.go]: Now that we Hostname() it is better to use that instead of IsLocal() @vadmeste

**Review by harshavardhana — CHANGES_REQUESTED** [review]

File: cmd/storage-interface.go (hunk 3 above)
Comment (vadmeste) [reply cmd/storage-interface.go]: > Now that we Hostname() it is better to use that instead of IsLocal() @vadmeste

Yes, fixed

File: cmd/format-xl.go (hunk 2 above)
Comment (vadmeste) [reply cmd/format-xl.go]: > Since most disks are not going to be local, it seems a majority of these go routines are going to return while doing no work. It's more efficient to only start go routines for local disks.

Fixed !

**Comment by vadmeste** [comment]
@harshavardhana @donatello all issues addressed, please take a look.

**Comment by vadmeste** [comment]
I also updated the commit message, since the original issue was fixed in one of the merged Harsha PRs

**Review by harshavardhana — APPROVED** [review]

**Comment by minio-ops** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-xl.sh | :heavy_check_mark: |
| mint-worm.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-dist-xl.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :x: [more...](#980a00bf-7caa-4183-9ecc-f42af8cf1a07) |
<a name="980a00bf-7caa-4183-9ecc-f42af8cf1a07"></a>
### 8786-c38ba98/mint-large-bucket.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.52:30539
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp beccd1247b00:/mint/log /tmp/mint-logs'

(1/13) Running awscli tests ... done in 2 minutes and 24 seconds
(2/13) Running aws-sdk-java tests ... done in 2 seconds
(3/13) Running aws-sdk-ruby tests ... done in 7 seconds
(4/13) Running mc tests ... done in 59 seconds
(5/13) Running minio-go tests ... FAILED in 3 minutes and 11 seconds
{
  "args": {},
  "duration": 73725,
  "error": "Please reduce your request",
  "function": "testStorageClassMetadataCopyObject()",
  "message": "CopyObject failed on RRS",
  "name": "minio-go: testStorageClassMetadataCopyObject",
  "status": "FAIL"
}

Executed 4 out of 13 tests successfully.
```
Deleting image on docker hub
Deleting image locally

**Review by donatello — APPROVED** [review]
