### PR TITLE
xl: Move format detection inside xl objects.

### LINKED ISSUE #1449: xl: return I/O error than giving junk data for get file
In bad situation like wrong set of disks, xl is returning corrupted data for get file and similar calls.  It would be better to return I/O error than returning corrupted data.

### PR DESCRIPTION
**Pull request by harshavardhana**
Fixes #1449

### CODE REVIEW

File: xl-objects.go [hunk 1]
```diff
@@ -43,6 +45,41 @@ func isLeafDirectory(disk StorageAPI, volume, leafPath string) bool {
 	return err == nil
 }
 
+// isValidFormat - validates input arguments with backend 'format.json'
```
Comment (abperiasamy) [inline xl-objects.go:48]: isValidFormat returns bool. In case of error, just panic.

File: xl-objects.go [hunk 2]
```diff
@@ -55,6 +92,12 @@ func newXLObjects(exportPaths ...string) (ObjectLayer, error) {
 	// cleaning up tmp files etc.
 	initObjectLayer(storage)
 
+	// Validate if format exists and input arguments are validated
+	// against backend format.
+	if err = isValidFormat(storage, exportPaths...); err != nil {
+		return nil, err
+	}
```
Comment (abperiasamy) [inline xl-objects.go:108]: isValidFormat should not initialize format.json if it did not exist. It should at the newXLObjects layer.

File: xl-objects.go [hunk 3]
```diff
@@ -43,6 +45,41 @@ func isLeafDirectory(disk StorageAPI, volume, leafPath string) bool {
...
+	xl, err = loadFormatXL(storage)
+	if err != nil {
+		return err
+	}
+	if xl.Version != "1" {
+		return fmt.Errorf("Invalid XL format version %s not recognized, version mismatch.", xl.Version)
+	}
+	if len(exportPaths) != len(xl.Disks) {
+		err = fmt.Errorf("Mismatching number of disks detected %d, wanted %d. Please provide right number of disks.", len(exportPaths), len(xl.Disks))
+		return err
```
Comment (abperiasamy) [inline xl-objects.go]: Number of disks passed at the command-line did not match the backend format.

File: xl-objects.go [hunk 4]
```diff
@@ -43,6 +45,41 @@ func isLeafDirectory(disk StorageAPI, volume, leafPath string) bool {
...
+		})
+	}
+	var xl *xlFormat
+	// Load saved XL format.json and validate.
+	xl, err = loadFormatXL(storage)
+	if err != nil {
+		return err
+	}
+	if xl.Version != "1" {
+		return fmt.Errorf("Invalid XL format version %s not recognized, version mismatch.", xl.Version)
```
Comment (abperiasamy) [inline xl-objects.go]: Unsupported XL backend format [%d] found.

File: xl-objects.go [hunk 5]
```diff
@@ -43,6 +45,41 @@ func isLeafDirectory(disk StorageAPI, volume, leafPath string) bool {
...
+	}
+	if len(exportPaths) != len(xl.Disks) {
+		err = fmt.Errorf("Mismatching number of disks detected %d, wanted %d. Please provide right number of disks.", len(exportPaths), len(xl.Disks))
+		return err
+	}
+	for index, disk := range xl.Disks {
+		if exportPaths[index] != disk {
+			err = fmt.Errorf("Invalid order of disks detected %s, wanted %s. Please provide right order of disks.", exportPaths, xl.Disks)
+			return err
```
Comment (abperiasamy) [inline xl-objects.go]: Invalid order of disks detected %s. Required order is %s.

File: xl-objects.go [hunk 6]
```diff
@@ -43,6 +45,41 @@ func isLeafDirectory(disk StorageAPI, volume, leafPath string) bool {
...
+// isValidFormat - validates input arguments with backend 'format.json'
+func isValidFormat(storage StorageAPI, exportPaths ...string) error {
+	ok, err := isFormatExist(storage)
+	if err != nil {
+		return err
+	}
+	if !ok {
+		// Save new XL format.
+		return saveFormatXL(storage, &xlFormat{
+			Version: "1",
```
Comment (abperiasamy) [inline xl-objects.go]: saveFormatXL goes out.

File: xl-objects.go [hunk 7]
```diff
@@ -43,18 +45,67 @@ func isLeafDirectory(disk StorageAPI, volume, leafPath string) bool {
...
 	}
 
 	// Initialize object layer - like creating minioMetaBucket,
 	// cleaning up tmp files etc.
 	initObjectLayer(storage)
 
+	err = checkFormat(storage)
+	if err != nil && err != errFileNotFound {
+		log.Errorf("checkFormat failed with %s", err)
+		return nil, err
```
Comment (abperiasamy) [inline xl-objects.go]: Unable to check backend format. %s

File: xl-objects.go [hunk 8]
```diff
@@ -43,18 +45,67 @@ func isLeafDirectory(disk StorageAPI, volume, leafPath string) bool {
...
+	}
+	if err == errFileNotFound {
+		// Save new XL format.
```
Comment (abperiasamy) [inline xl-objects.go]: Use nested err checks. It will make it readable.
