### PR TITLE
HealObject should succeed when only N/2 disks have data

### LINKED ISSUE #3950: [heal] Healing after a manual removing of an object in two disks from 4 shows NoSuchKey
## Expected Behavior
Healing should be always successful when I manually remove an object content from two XL disks.

## Current Behavior
Sometimes it is successful and sometimes not.

```
mc: <DEBUG> POST /?bucket=testbucket&heal=&object=128mb.bin HTTP/1.1
Host: localhost:9000
User-Agent: Minio (linux; amd64) madmin-go/0.0.1 mc/DEVELOPMENT.GOGET
Content-Length: 0
Authorization: AWS4-HMAC-SHA256 Credential=minio/20170321/us-east-1/s3/aws4_request, SignedHeaders=host;x-amz-content-sha256;x-amz-date;x-minio-operation, Signature=**RE
DACTED**
X-Amz-Content-Sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
X-Amz-Date: 20170321T210642Z
X-Minio-Operation: object
Accept-Encoding: gzip

mc: <DEBUG> HTTP/1.1 404 Not Found
Transfer-Encoding: chunked
Accept-Ranges: bytes
Content-Type: application/xml
Date: Tue, 21 Mar 2017 21:06:42 GMT
Server: Minio/DEVELOPMENT.GOGET (linux; amd64)
Vary: Origin
X-Amz-Request-Id: 14AE01B4B8AD45D5

ec
<?xml version="1.0" encoding="UTF-8"?>
<Error><Code>NoSuchKey</Code><Message>The specified key does not exist.</Message><Key></Key><BucketName></BucketName><Resource>/</Resource><RequestId>3L137</RequestId><H
ostId>3L137</HostId></Error>
```

## Possible Solution
No idea

## Steps to Reproduce (for bugs)
1. `minio server /path/disk{1..4} # start from fresh disks`
2. `mc mb myminio/testbucket # create testbucket`
3. `mc cp 128mb.file myminio/testbucket/`
4. `rm -r /path/disk{1..2}/testbucket/128mb.file`
5. `mc admin heal -r myminio/testbucket/`
`mc: <ERROR> Cannot repair object: `128mb.bin` The specified key does not exist.`

## Context
Manual testing.

## Your Environment
All

### PR DESCRIPTION
**Pull request by krisis**
Fixes #3950 
## Description

* reduceErrs should prefer nil over other errors
  Consider the following slice of error,
      `[]error {errFileNotFound, errFileNotFound, nil, nil}`

  `reduceErrs` should return `nil` to allow higher-level functionality
  like `erasureReadfile` to reconstruct data when it can.

* heal: Validate part checksums correctly
  Previously, the validation of part checksums assumed checksumInfo in
  xl.json appears in increasing order of part number. This change removes
  that assumption.

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

File: cmd/xl-v1-healing-common.go [hunk 1]
```diff
@@ -239,7 +239,7 @@ func disksWithAllParts(onlineDisks []StorageAPI, partsMetadata []xlMetaV1, errs
 				return nil, nil, traceError(hErr)
 			}
 
-			partChecksum := partsMetadata[index].Erasure.Checksum[pIndex].Hash
+			partChecksum := partsMetadata[index].Erasure.GetCheckSumInfo(part.Name).Hash
```
Comment (vadmeste) [inline cmd/xl-v1-healing-common.go:242]: Good catch!

**Review by vadmeste — APPROVED** [review]

**Review by donatello — APPROVED** [review]

**Comment by krisis** [comment]
@donatello @vadmeste I have added a unit test case to capture healing of an object whose `checksums` array in `xl.json` has the parts in decreasing partId order. This is to check the change included in this PR, where previously blake2b checksum assumed checksums are in increasing partId order.
