### PR TITLE
Fix browser download returning zero bytes for s3

### LINKED ISSUE #4479: [gateway-s3] Browser download gives 0-byte file
When accessing the browser interface for Minio server in gateway mode for S3 backend, clicking an object within any bucket downloads a 0-byte object.

## Expected Behavior

Download should return appropriate data.

## Current Behavior

Downloads a 0-byte file.

## Steps to Reproduce (for bugs)

1. Start Minio server in gateway mode for s3
2. Open Minio browser interface in your web-browser and login.
3. Click any object in any bucket in main content panel - this is to download the file.
4. A 0-byte file is returned.

## Context

Found during release candidate testing.

### PR DESCRIPTION
**Pull request by poornas**
## Description

Clicking on download object from browser returns 0 bytes for s3
## Motivation and Context

The browser's web handler sends -1 as length for full downloads. The s3 api expects the actual length of the object in the GetObject call. This fixes #4479 
## How Has This Been Tested?

Manually on s3, azure and server mode.
## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Review by harshavardhana — APPROVED** [review]

File: cmd/web-handlers.go [hunk 1]
```diff
@@ -546,10 +546,15 @@ func (web *webAPIHandlers) Download(w http.ResponseWriter, r *http.Request) {
 	objectLock.RLock()
 	defer objectLock.RUnlock()
 
-	if err := objectAPI.GetObject(bucket, object, 0, -1, w); err != nil {
+	info, err := objectAPI.GetObjectInfo(bucket, object)
```
Comment (harshavardhana) [inline cmd/web-handlers.go]: One problem here is that this would increase an API call to the backend server. We should avoid that handle this appropriately at the client SDK used by the s3 backend.

**Review by harshavardhana — CHANGES_REQUESTED** [review]

File: cmd/web-handlers.go (hunk 1 above)
Comment (donatello) [reply cmd/web-handlers.go]: A simple GET Object via the S3 API is served by making object layer calls to [GetObjectInfo followed by GetObject](https://github.com/minio/minio/blob/master/cmd/object-handlers.go#L101) - it is not a single call. I think it is acceptable to do the same here. These calls are happening within the backend server and not being sent from browser to backend server.

**Review by donatello — APPROVED** [review]

File: cmd/web-handlers.go (hunk 1 above)
Comment (donatello) [reply cmd/web-handlers.go]: After discussion with @harshavardhana - it will be better to modify in https://github.com/minio/minio/blob/master/cmd/gateway-s3.go#L262 - it avoids a network call to the backend gateway. We can make the change specifically for s3 gateway

**Review by donatello — CHANGES_REQUESTED** [review]

File: cmd/gateway-s3.go [hunk 2]
```diff
@@ -261,9 +261,16 @@ func fromMinioClientListBucketResult(bucket string, result minio.ListBucketResul
 // length indicates the total length of the object.
 func (l *s3Objects) GetObject(bucket string, key string, startOffset int64, length int64, writer io.Writer) error {
 	r := minio.NewGetReqHeaders()
-	if err := r.SetRange(startOffset, startOffset+length-1); err != nil {
-		return s3ToObjectError(traceError(err), bucket, key)
+	length = -2
```
Comment (harshavardhana) [inline cmd/gateway-s3.go]: what is this for? a typo?

File: cmd/gateway-s3.go [hunk 3]
```diff
@@ -261,9 +261,16 @@ func fromMinioClientListBucketResult(bucket string, result minio.ListBucketResul
...
+	if length < 0 && length != -1 {
+		return s3ToObjectError(traceError(errInvalidArgument), bucket, key)
+	}
+	if length != -1 {
```
Comment (harshavardhana) [inline cmd/gateway-s3.go]: this should be `if length >= 0` - more readable.

File: cmd/web-handlers.go (hunk 1 above)
Comment (harshavardhana) [inline cmd/web-handlers.go]: You forgot to remove GetObjectInfo() usage @poornas , revert the changes for web-handlers.go

**Review by harshavardhana — CHANGES_REQUESTED** [review]

File: cmd/gateway-s3.go [hunk 4]
```diff
@@ -261,20 +261,32 @@ func fromMinioClientListBucketResult(bucket string, result minio.ListBucketResul
 // length indicates the total length of the object.
 func (l *s3Objects) GetObject(bucket string, key string, startOffset int64, length int64, writer io.Writer) error {
 	r := minio.NewGetReqHeaders()
-	if err := r.SetRange(startOffset, startOffset+length-1); err != nil {
-		return s3ToObjectError(traceError(err), bucket, key)
+
+	if length < 0 && length != -1 {
+		return s3ToObjectError(traceError(errInvalidArgument), bucket, key)
 	}
+	if length != -1 {
```
Comment (harshavardhana) [inline cmd/gateway-s3.go]: This should be more readable if you add `if startOffset >= 0 && length >= 0`

File: cmd/gateway-s3.go [hunk 5]
```diff
@@ -261,20 +261,32 @@ func fromMinioClientListBucketResult(bucket string, result minio.ListBucketResul
...
 	}
 
 	defer object.Close()
 
-	if _, err := io.CopyN(writer, object, length); err != nil {
-		return s3ToObjectError(traceError(err), bucket, key)
+	if length == -1 {
+		_, err = io.Copy(writer, object)
+	} else {
+		_, err = io.CopyN(writer, object, length)
```
Comment (harshavardhana) [inline cmd/gateway-s3.go]: Actually we don't need `io.CopyN()` we already requested the right amount of file size from the backend we can just do `io.Copy()` instead - this will simplify the code further.

**Review by harshavardhana — CHANGES_REQUESTED** [review]

**Comment by donatello** [comment]
I will test this after all changes are finalized - otherwise, github will keep invalidating my review as changes are made to the PR.

**Comment by poornas** [comment]
incorporated review comments

File: cmd/gateway-s3.go [hunk 6]
```diff
@@ -261,8 +261,15 @@ func fromMinioClientListBucketResult(bucket string, result minio.ListBucketResul
 // length indicates the total length of the object.
 func (l *s3Objects) GetObject(bucket string, key string, startOffset int64, length int64, writer io.Writer) error {
 	r := minio.NewGetReqHeaders()
-	if err := r.SetRange(startOffset, startOffset+length-1); err != nil {
-		return s3ToObjectError(traceError(err), bucket, key)
+
+	if length < 0 && length != -1 {
```
Comment (krishnasrinivas) [inline cmd/gateway-s3.go:265]: `if length < -1` will do the same thing

Comment (donatello) [reply cmd/gateway-s3.go:265]: No if `length < -1` we return error. The only negative length to interpret is -1 as a special case meaning the whole object.

**Review by donatello — APPROVED** [review]
Looks good; tested and verified the fix.

**Review by harshavardhana — APPROVED** [review]
