### PR TITLE
cache: fix call in GetObjectNInfo

### LINKED ISSUE #10751: Minio (K8S) S3 gateway (Backblaze B2)
Suspect my local storage is rather slow (rancher-longhorn), but either way shouldn't cause a crash.

Was using Minio as a Caching S3 gateway between seafile and Backblaze b2's S3 endpoint
Also happens with nextcloud accessing minio.

Image is minio/minio so should be latest docker release.

I had MINIO_CACHE_AFTER set to 1 which may be part of the problem

```
runtime: goroutine stack exceeds 1000000000-byte limit
runtime: sp=0xc021b02390 stack=[0xc021b02000, 0xc041b02000]
fatal error: stack overflow

runtime stack:
runtime.throw(0x1dbb050, 0xe)
        runtime/panic.go:1116 +0x72
runtime.newstack()
        runtime/stack.go:1067 +0x78d
runtime.morestack()
        runtime/asm_amd64.s:449 +0x8f

goroutine 196 [running]:
reflect.resolveNameOff(0x1a594a0, 0x6cb9, 0x0)
        runtime/runtime1.go:476 +0x4c fp=0xc021b023a0 sp=0xc021b02398 pc=0x46c1ec
reflect.(*rtype).nameOff(...)
        reflect/type.go:684
reflect.(*rtype).String(0x1a594a0, 0x0, 0x0)
        reflect/type.go:754 +0x36 fp=0xc021b023d8 sp=0xc021b023a0 pc=0x4e0636
reflect.(*rtype).Name(0x1a594a0, 0xc000ecdbd0, 0x186)
        reflect/type.go:871 +0x38 fp=0xc021b02400 sp=0xc021b023d8 pc=0x4e1578
encoding/json.indirect(0x1a594a0, 0xc000ecdbd0, 0x186, 0x0, 0xc021b02500, 0x46190a, 0x1aee060, 0x0, 0x28c6a0, 0x3247240, ...)
        encoding/json/decode.go:440 +0x6c2 fp=0xc021b02480 sp=0xc021b02400 pc=0x7c6422
encoding/json.(*decodeState).literalStore(0xc0017c62e8, 0xc0017c8422, 0x3, 0x1de, 0x1a594a0, 0xc000ecdbd0, 0x186, 0x0, 0x17b, 0xc0017c6310)
        encoding/json/decode.go:858 +0x208 fp=0xc021b02618 sp=0xc021b02480 pc=0x7c9808
encoding/json.(*decodeState).value(0xc0017c62e8, 0x1a594a0, 0xc000ecdbd0, 0x186, 0x2, 0xc000b52f80)
        encoding/json/decode.go:384 +0x1f1 fp=0xc021b02680 sp=0xc021b02618 pc=0x7c5bf1
encoding/json.(*decodeState).object(0xc0017c62e8, 0x1c375c0, 0xc000ecdbd0, 0x199, 0xc0017c6310, 0x7b)
        encoding/json/decode.go:765 +0x12fe fp=0xc021b02910 sp=0xc021b02680 pc=0x7c845e
encoding/json.(*decodeState).value(0xc0017c62e8, 0x1c375c0, 0xc000ecdbd0, 0x199, 0x1c375c0, 0xc000ecdbd0)
        encoding/json/decode.go:370 +0x6d fp=0xc021b02978 sp=0xc021b02910 pc=0x7c5a6d
encoding/json.(*decodeState).object(0xc0017c62e8, 0x1acdba0, 0xc000ecdbc0, 0x16, 0xc0017c6310, 0x7b)
        encoding/json/decode.go:765 +0x12fe fp=0xc021b02c08 sp=0xc021b02978 pc=0x7c845e
encoding/json.(*decodeState).value(0xc0017c62e8, 0x1acdba0, 0xc000ecdbc0, 0x16, 0xc021b02ce8, 0x7dacb9)
        encoding/json/decode.go:370 +0x6d fp=0xc021b02c70 sp=0xc021b02c08 pc=0x7c5a6d
encoding/json.(*decodeState).unmarshal(0xc0017c62e8, 0x1acdba0, 0xc000ecdbc0, 0x0, 0x0)
        encoding/json/decode.go:180 +0x1ea fp=0xc021b02cf8 sp=0xc021b02c70 pc=0x7c51ea
encoding/json.(*Decoder).Decode(0xc0017c62c0, 0x1acdba0, 0xc000ecdbc0, 0x20b09c0, 0xc0005301e0)
        encoding/json/stream.go:73 +0x16b fp=0xc021b02d38 sp=0xc021b02cf8 pc=0x7da94b
github.com/minio/minio/cmd.jsonLoad(0x20ca760, 0xc0005301e0, 0x1acdba0, 0xc000ecdbc0, 0xc0005301e0, 0x0)
        github.com/minio/minio/cmd/utils.go:567 +0xd4 fp=0xc021b02d88 sp=0xc021b02d38 pc=0x17171f4
github.com/minio/minio/cmd.(*diskCache).statCache(0xc000fa3860, 0x20e4ca0, 0xc00071a4e0, 0xc0016714f0, 0x46, 0xc000ecdbc0, 0x0, 0x0, 0x0, 0x0)
        github.com/minio/minio/cmd/disk-cache-backend.go:487 +0x17e fp=0xc021b02e10 sp=0xc021b02d88 pc=0x158d17e
github.com/minio/minio/cmd.(*diskCache).statCachedMeta(0xc000fa3860, 0x20e4ca0, 0xc00071a4e0, 0xc0016714f0, 0x46, 0x0, 0xc001671400, 0x0, 0x0, 0x0)
        github.com/minio/minio/cmd/disk-cache-backend.go:428 +0x158 fp=0xc021b02e98 sp=0xc021b02e10 pc=0x158c8d8
github.com/minio/minio/cmd.(*diskCache).statRange(0xc000fa3860, 0x20e4ca0, 0xc00071a4e0, 0xc000218105, 0x19, 0xc00021811f, 0x4d, 0x0, 0x0, 0x0, ...)
        github.com/minio/minio/cmd/disk-cache-backend.go:438 +0x134 fp=0xc021b030f0 sp=0xc021b02e98 pc=0x158ca94
github.com/minio/minio/cmd.(*diskCache).Get(0xc000fa3860, 0x20e4ca0, 0xc00071a4e0, 0xc000218105, 0x19, 0xc00021811f, 0x4d, 0x0, 0xc00071a240, 0x0, ...)
        github.com/minio/minio/cmd/disk-cache-backend.go:877 +0x285 fp=0xc021b036f8 sp=0xc021b030f0 pc=0x1591625
github.com/minio/minio/cmd.(*cacheObjects).GetObjectNInfo(0xc000f20d00, 0x20e4ca0, 0xc00071a4e0, 0xc000218105, 0x19, 0xc00021811f, 0x4d, 0x0, 0xc00071a240, 0x1, ...)
        github.com/minio/minio/cmd/disk-cache.go:201 +0x2f8 fp=0xc021b04448 sp=0xc021b036f8 pc=0x1596ef8
github.com/minio/minio/cmd.(*cacheObjects).GetObjectNInfo(0xc000f20d00, 0x20e4ca0, 0xc00071a4e0, 0xc000218105, 0x19, 0xc00021811f, 0x4d, 0x0, 0xc00071a240, 0x1, ...)
        github.com/minio/minio/cmd/disk-cache.go:227 +0x1a1f fp=0xc021b05198 sp=0xc021b04448 pc=0x159861f
github.com/minio/minio/cmd.(*cacheObjects).GetObjectNInfo(0xc000f20d00, 0x20e4ca0, 0xc00071a4e0, 0xc000218105, 0x19, 0xc00021811f, 0x4d, 0x0, 0xc00071a240, 0x1, ...)
        github.com/minio/minio/cmd/disk-cache.go:227 +0x1a1f fp=0xc021b05ee8 sp=0xc021b05198 pc=0x159861f
github.com/minio/minio/cmd.(*cacheObjects).GetObjectNInfo(0xc000f20d00, 0x20e4ca0, 0xc00071a4e0, 0xc000218105, 0x19, 0xc00021811f, 0x4d, 0x0, 0xc00071a240, 0x1, ...)
        github.com/minio/minio/cmd/disk-cache.go:227 +0x1a1f fp=0xc021b06c38 sp=0xc021b05ee8 pc=0x159861f
github.com/minio/minio/cmd.(*cacheObjects).GetObjectNInfo(0xc000f20d00, 0x20e4ca0, 0xc00071a4e0, 0xc000218105, 0x19, 0xc00021811f, 0x4d, 0x0, 0xc00071a240, 0x1, ...)
        github.com/minio/minio/cmd/disk-cache.go:227 +0x1a1f fp=0xc021b07988 sp=0xc021b06c38 pc=0x159861f
github.com/minio/minio/cmd.(*cacheObjects).GetObjectNInfo(0xc000f20d00, 0x20e4ca0, 0xc00071a4e0, 0xc000218105, 0x19, 0xc00021811f, 0x4d, 0x0, 0xc00071a240, 0x1, ...)
        github.com/minio/minio/cmd/disk-cache.go:227 +0x1a1f fp=0xc021b086d8 sp=0xc021b07988 pc=0x159861f
github.com/minio/minio/cmd.(*cacheObjects).GetObjectNInfo(0xc000f20d00, 0x20e4ca0, 0xc00071a4e0, 0xc000218105, 0x19, 0xc00021811f, 0x4d, 0x0, 0xc00071a240, 0x1, ...)
        github.com/minio/minio/cmd/disk-cache.go:227 +0x1a1f fp=0xc021b09428 sp=0xc021b086d8 pc=0x159861f
github.com/minio/minio/cmd.(*cacheObjects).GetObjectNInfo(0xc000f20d00, 0x20e4ca0, 0xc00071a4e0, 0xc000218105, 0x19, 0xc00021811f, 0x4d, 0x0, 0xc00071a240, 0x1, ...)
        github.com/minio/minio/cmd/disk-cache.go:227 +0x1a1f fp=0xc021b0a178 sp=0xc021b09428 pc=0x159861f
github.com/minio/minio/cmd.(*cacheObjects).GetObjectNInfo(0xc000f20d00, 0x20e4ca0, 0xc00071a4e0, 0xc000218105, 0x19, 0xc00021811f, 0x4d, 0x0, 0xc00071a240, 0x1, ...)
        github.com/minio/minio/cmd/disk-cache.go:227 +0x1a1f fp=0xc021b0aec8 sp=0xc021b0a178 pc=0x159861f
github.com/minio/minio/cmd.(*cacheObjects).GetObjectNInfo(0xc000f20d00, 0x20e4ca0, 0xc00071a4e0, 0xc000218105, 0x19, 0xc00021811f, 0x4d, 0x0, 0xc00071a240, 0x1, ...)
        github.com/minio/minio/cmd/disk-cache.go:227 +0x1a1f fp=0xc021b0bc18 sp=0xc021b0aec8 pc=0x159861f
github.com/minio/minio/cmd.(*cacheObjects).GetObjectNInfo(0xc000f20d00, 0x20e4ca0, 0xc00071a4e0, 0xc000218105, 0x19, 0xc00021811f, 0x4d, 0x0, 0xc00071a240, 0x1, ...)
        github.com/minio/minio/cmd/disk-cache.go:227 +0x1a1f fp=0xc021b0c968 sp=0xc021b0bc18 pc=0x159861f
github.com/minio/minio/cmd.(*cacheObjects).GetObjectNInfo(0xc000f20d00, 0x20e4ca0, 0xc00071a4e0, 0xc000218105, 0x19, 0xc00021811f, 0x4d, 0x0, 0xc00071a240, 0x1, ...)
        github.com/minio/minio/cmd/disk-cache.go:227 +0x1a1f fp=0xc021b0d6b8 sp=0xc021b0c968 pc=0x159861f
github.com/minio/minio/cmd.(*cacheObjects).GetObjectNInfo(0xc000f20d00, 0x20e4ca0, 0xc00071a4e0, 0xc000218105, 0x19, 0xc00021811f, 0x4d, 0x0, 0xc00071a240, 0x1, ...)
        github.com/minio/minio/cmd/disk-cache.go:227 +0x1a1f fp=0xc021b0e408 sp=0xc021b0d6b8 pc=0x159861f
github.com/minio/minio/cmd.(*cacheObjects).GetObjectNInfo(0xc000f20d00, 0x20e4ca0, 0xc00071a4e0, 0xc000218105, 0x19, 0xc00021811f, 0x4d, 0x0, 0xc00071a240, 0x1, ...)
        github.com/minio/minio/cmd/disk-cache.go:227 +0x1a1f fp=0xc021b0f158 sp=0xc021b0e408 pc=0x159861f
github.com/minio/minio/cmd.(*cacheObjects).GetObjectNInfo(0xc000f20d00, 0x20e4ca0, 0xc00071a4e0, 0xc000218105, 0x19, 0xc00021811f, 0x4d, 0x0, 0xc00071a240, 0x1, ...)
        github.com/minio/minio/cmd/disk-cache.go:227 +0x1a1f fp=0xc021b0fea8 sp=0xc021b0f158 pc=0x159861f
github.com/minio/minio/cmd.(*cacheObjects).GetObjectNInfo(0xc000f20d00, 0x20e4ca0, 0xc00071a4e0, 0xc000218105, 0x19, 0xc00021811f, 0x4d, 0x0, 0xc00071a240, 0x1, ...)
        github.com/minio/minio/cmd/disk-cache.go:227 +0x1a1f fp=0xc021b10bf8 sp=0xc021b0fea8 pc=0x159861f
github.com/minio/minio/cmd.(*cacheObjects).GetObjectNInfo(0xc000f20d00, 0x20e4ca0, 0xc00071a4e0, 0xc000218105, 0x19, 0xc00021811f, 0x4d, 0x0, 0xc00071a240, 0x1, ...)
        github.com/minio/minio/cmd/disk-cache.go:227 +0x1a1f fp=0xc021b11948 sp=0xc021b10bf8 pc=0x159861f
github.com/minio/minio/cmd.(*cacheObjects).GetObjectNInfo(0xc000f20d00, 0x20e4ca0, 0xc00071a4e0, 0xc000218105, 0x19, 0xc00021811f, 0x4d, 0x0, 0xc00071a240, 0x1, ...)
        github.com/minio/minio/cmd/disk-cache.go:227 +0x1a1f fp=0xc021b12698 sp=0xc021b11948 pc=0x159861f
github.com/minio/minio/cmd.(*cacheObjects).GetObjectNInfo(0xc000f20d00, 0x20e4ca0, 0xc00071a4e0, 0xc000218105, 0x19, 0xc00021811f, 0x4d, 0x0, 0xc00071a240, 0x1, ...)
        github.com/minio/minio/cmd/disk-cache.go:227 +0x1a1f fp=0xc021b133e8 sp=0xc021b12698 pc=0x159861f
github.com/minio/minio/cmd.(*cacheObjects).GetObjectNInfo(0xc000f20d00, 0x20e4ca0, 0xc00071a4e0, 0xc000218105, 0x19, 0xc00021811f, 0x4d, 0x0, 0xc00071a240, 0x1, ...)
        github.com/minio/minio/cmd/disk-cache.go:227 +0x1a1f fp=0xc021b14138 sp=0xc021b133e8 pc=0x159861f
github.com/minio/minio/cmd.(*cacheObjects).GetObjectNInfo(0xc000f20d00, 0x20e4ca0, 0xc00071a4e0, 0xc000218105, 0x19, 0xc00021811f, 0x4d, 0x0, 0xc00071a240, 0x1, ...)
        github.com/minio/minio/cmd/disk-cache.go:227 +0x1a1f fp=0xc021b14e88 sp=0xc021b14138 pc=0x159861f
github.com/minio/minio/cmd.(*cacheObjects).GetObjectNInfo(0xc000f20d00, 0x20e4ca0, 0xc00071a4e0, 0xc000218105, 0x19, 0xc00021811f, 0x4d, 0x0, 0xc00071a240, 0x1, ...)
        github.com/minio/minio/cmd/disk-cache.go:227 +0x1a1f fp=0xc021b15bd8 sp=0xc021b14e88 pc=0x159861f
github.com/minio/minio/cmd.(*cacheObjects).GetObjectNInfo(0xc000f20d00, 0x20e4ca0, 0xc00071a4e0, 0xc000218105, 0x19, 0xc00021811f, 0x4d, 0x0, 0xc00071a240, 0x1, ...)
        github.com/minio/minio/cmd/disk-cache.go:227 +0x1a1f fp=0xc021b16928 sp=0xc021b15bd8 pc=0x159861f
github.com/minio/minio/cmd.(*cacheObjects).GetObjectNInfo(0xc000f20d00, 0x20e4ca0, 0xc00071a4e0, 0xc000218105, 0x19, 0xc00021811f, 0x4d, 0x0, 0xc00071a240, 0x1, ...)
        github.com/minio/minio/cmd/disk-cache.go:227 +0x1a1f fp=0xc021b17678 sp=0xc021b16928 pc=0x159861f
github.com/minio/minio/cmd.(*cacheObjects).GetObjectNInfo(0xc000f20d00, 0x20e4ca0, 0xc00071a4e0, 0xc000218105, 0x19, 0xc00021811f, 0x4d, 0x0, 0xc00071a240, 0x1, ...)
        github.com/minio/minio/cmd/disk-cache.go:227 +0x1a1f fp=0xc021b183c8 sp=0xc021b17678 pc=0x159861f
github.com/minio/minio/cmd.(*cacheObjects).GetObjectNInfo(0xc000f20d00, 0x20e4ca0, 0xc00071a4e0, 0xc000218105, 0x19, 0xc00021811f, 0x4d, 0x0, 0xc00071a240, 0x1, ...)
        github.com/minio/minio/cmd/disk-cache.go:227 +0x1a1f fp=0xc021b19118 sp=0xc021b183c8 pc=0x159861f
github.com/minio/minio/cmd.(*cacheObjects).GetObjectNInfo(0xc000f20d00, 0x20e4ca0, 0xc00071a4e0, 0xc000218105, 0x19, 0xc00021811f, 0x4d, 0x0, 0xc00071a240, 0x1, ...)
        github.com/minio/minio/cmd/disk-cache.go:227 +0x1a1f fp=0xc021b19e68 sp=0xc021b19118 pc=0x159861f
github.com/minio/minio/cmd.(*cacheObjects).GetObjectNInfo(0xc000f20d00, 0x20e4ca0, 0xc00071a4e0, 0xc000218105, 0x19, 0xc00021811f, 0x4d, 0x0, 0xc00071a240, 0x1, ...)
        github.com/minio/minio/cmd/disk-cache.go:227 +0x1a1f fp=0xc021b1abb8 sp=0xc021b19e68 pc=0x159861f
github.com/minio/minio/cmd.(*cacheObjects).GetObjectNInfo(0xc000f20d00, 0x20e4ca0, 0xc00071a4e0, 0xc000218105, 0x19, 0xc00021811f, 0x4d, 0x0, 0xc00071a240, 0x1, ...)
        github.com/minio/minio/cmd/disk-cache.go:227 +0x1a1f fp=0xc021b1b908 sp=0xc021b1abb8 pc=0x159861f
github.com/minio/minio/cmd.(*cacheObjects).GetObjectNInfo(0xc000f20d00, 0x20e4ca0, 0xc00071a4e0, 0xc000218105, 0x19, 0xc00021811f, 0x4d, 0x0, 0xc00071a240, 0x1, ...)
        github.com/minio/minio/cmd/disk-cache.go:227 +0x1a1f fp=0xc021b1c658 sp=0xc021b1b908 pc=0x159861f
github.com/minio/minio/cmd.(*cacheObjects).GetObjectNInfo(0xc000f20d00, 0x20e4ca0, 0xc00071a4e0, 0xc000218105, 0x19, 0xc00021811f, 0x4d, 0x0, 0xc00071a240, 0x1, ...)
        github.com/minio/minio/cmd/disk-cache.go:227 +0x1a1f fp=0xc021b1d3a8 sp=0xc021b1c658 pc=0x159861f
github.com/minio/minio/cmd.(*cacheObjects).GetObjectNInfo(0xc000f20d00, 0x20e4ca0, 0xc00071a4e0, 0xc000218105, 0x19, 0xc00021811f, 0x4d, 0x0, 0xc00071a240, 0x1, ...)
        github.com/minio/minio/cmd/disk-cache.go:227 +0x1a1f fp=0xc021b1e0f8 sp=0xc021b1d3a8 pc=0x159861f
github.com/minio/minio/cmd.(*cacheObjects).GetObjectNInfo(0xc000f20d00, 0x20e4ca0, 0xc00071a4e0, 0xc000218105, 0x19, 0xc00021811f, 0x4d, 0x0, 0xc00071a240, 0x1, ...)
        github.com/minio/minio/cmd/disk-cache.go:227 +0x1a1f fp=0xc021b1ee48 sp=0xc021b1e0f8 pc=0x159861f
github.com/minio/minio/cmd.(*cacheObjects).GetObjectNInfo(0xc000f20d00, 0x20e4ca0, 0xc00071a4e0, 0xc000218105, 0x19, 0xc00021811f, 0x4d, 0x0, 0xc00071a240, 0x1, ...)
        github.com/minio/minio/cmd/disk-cache.go:227 +0x1a1f fp=0xc021b1fb98 sp=0xc021b1ee48 pc=0x159861f
github.com/minio/minio/cmd.(*cacheObjects).GetObjectNInfo(0xc000f20d00, 0x20e4ca0, 0xc00071a4e0, 0xc000218105, 0x19, 0xc00021811f, 0x4d, 0x0, 0xc00071a240, 0x1, ...)
        github.com/minio/minio/cmd/disk-cache.go:227 +0x1a1f fp=0xc021b208e8 sp=0xc021b1fb98 pc=0x159861f
github.com/minio/minio/cmd.(*cacheObjects).GetObjectNInfo(0xc000f20d00, 0x20e4ca0, 0xc00071a4e0, 0xc000218105, 0x19, 0xc00021811f, 0x4d, 0x0, 0xc00071a240, 0x1, ...)
        github.com/minio/minio/cmd/disk-cache.go:227 +0x1a1f fp=0xc021b21638 sp=0xc021b208e8 pc=0x159861f
github.com/minio/minio/cmd.(*cacheObjects).GetObjectNInfo(0xc000f20d00, 0x20e4ca0, 0xc00071a4e0, 0xc000218105, 0x19, 0xc00021811f, 0x4d, 0x0, 0xc00071a240, 0x1, ...)
        github.com/minio/minio/cmd/disk-cache.go:227 +0x1a1f fp=0xc021b22388 sp=0xc021b21638 pc=0x159861f
github.com/minio/minio/cmd.(*cacheObjects).GetObjectNInfo(0xc000f20d00, 0x20e4ca0, 0xc00071a4e0, 0xc000218105, 0x19, 0xc00021811f, 0x4d, 0x0, 0xc00071a240, 0x1, ...)
        github.com/minio/minio/cmd/disk-cache.go:227 +0x1a1f fp=0xc021b230d8 sp=0xc021b22388 pc=0x159861f
github.com/minio/minio/cmd.(*cacheObjects).GetObjectNInfo(0xc000f20d00, 0x20e4ca0, 0xc00071a4e0, 0xc000218105, 0x19, 0xc00021811f, 0x4d, 0x0, 0xc00071a240, 0x1, ...)
        github.com/minio/minio/cmd/disk-cache.go:227 +0x1a1f fp=0xc021b23e28 sp=0xc021b230d8 pc=0x159861f
github.com/minio/minio/cmd.(*cacheObjects).GetObjectNInfo(0xc000f20d00, 0x20e4ca0, 0xc00071a4e0, 0xc000218105, 0x19, 0xc00021811f, 0x4d, 0x0, 0xc00071a240, 0x1, ...)
        github.com/minio/minio/cmd/disk-cache.go:227 +0x1a1f fp=0xc021b24b78 sp=0xc021b23e28 pc=0x159861f
github.com/minio/minio/cmd.(*cacheObjects).GetObjectNInfo(0xc000f20d00, 0x20e4ca0, 0xc00071a4e0, 0xc000218105, 0x19, 0xc00021811f, 0x4d, 0x0, 0xc00071a240, 0x1, ...)
        github.com/minio/minio/cmd/disk-cache.go:227 +0x1a1f fp=0xc021b258c8 sp=0xc021b24b78 pc=0x159861f
github.com/minio/minio/cmd.(*cacheObjects).GetObjectNInfo(0xc000f20d00, 0x20e4ca0, 0xc00071a4e0, 0xc000218105, 0x19, 0xc00021811f, 0x4d, 0x0, 0xc00071a240, 0x1, ...)
        github.com/minio/minio/cmd/disk-cache.go:227 +0x1a1f fp=0xc021b26618 sp=0xc021b258c8 pc=0x159861f
github.com/minio/minio/cmd.(*cacheObjects).GetObjectNInfo(0xc000f20d00, 0x20e4ca0, 0xc00071a4e0, 0xc000218105, 0x19, 0xc00021811f, 0x4d, 0x0, 0xc00071a240, 0x1, ...)
        github.com/minio/minio/cmd/disk-cache.go:227 +0x1a1f fp=0xc021b27368 sp=0xc021b26618 pc=0x159861f
github.com/minio/minio/cmd.(*cacheObjects).GetObjectNInfo(0xc000f20d00, 0x20e4ca0, 0xc00071a4e0, 0xc000218105, 0x19, 0xc00021811f, 0x4d, 0x0, 0xc00071a240, 0x1, ...)
        github.com/minio/minio/cmd/disk-cache.go:227 +0x1a1f fp=0xc021b280b8 sp=0xc021b27368 pc=0x159861f
github.com/minio/minio/cmd.(*cacheObjects).GetObjectNInfo(0xc000f20d00, 0x20e4ca0, 0xc00071a4e0, 0xc000218105, 0x19, 0xc00021811f, 0x4d, 0x0, 0xc00071a240, 0x1, ...)
        github.com/minio/minio/cmd/disk-cache.go:227 +0x1a1f fp=0xc021b28e08 sp=0xc021b280b8 pc=0x159861f
github.com/minio/minio/cmd.(*cacheObjects).GetObjectNInfo(0xc000f20d00, 0x20e4ca0, 0xc00071a4e0, 0xc000218105, 0x19, 0xc00021811f, 0x4d, 0x0, 0xc00071a240, 0x1, ...)
        github.com/minio/minio/cmd/disk-cache.go:227 +0x1a1f fp=0xc021b29b58 sp=0xc021b28e08 pc=0x159861f
github.com/minio/minio/cmd.(*cacheObjects).GetObjectNInfo(0xc000f20d00, 0x20e4ca0, 0xc00071a4e0, 0xc000218105, 0x19, 0xc00021811f, 0x4d, 0x0, 0xc00071a240, 0x1, ...)
        github.com/minio/minio/cmd/disk-cache.go:227 +0x1a1f fp=0xc021b2a8a8 sp=0xc021b29b58 pc=0x159861f
github.com/minio/minio/cmd.(*cacheObjects).GetObjectNInfo(0xc000f20d00, 0x20e4ca0, 0xc00071a4e0, 0xc000218105, 0x19, 0xc00021811f, 0x4d, 0x0, 0xc00071a240, 0x1, ...)
        github.com/minio/minio/cmd/disk-cache.go:227 +0x1a1f fp=0xc021b2b5f8 sp=0xc021b2a8a8 pc=0x159861f
github.com/minio/minio/cmd.(*cacheObjects).GetObjectNInfo(0xc000f20d00, 0x20e4ca0, 0xc00071a4e0, 0xc000218105, 0x19, 0xc00021811f, 0x4d, 0x0, 0xc00071a240, 0x1, ...)
        github.com/minio/minio/cmd/disk-cache.go:227 +0x1a1f fp=0xc021b2c348 sp=0xc021b2b5f8 pc=0x159861f
github.com/minio/minio/cmd.(*cacheObjects).GetObjectNInfo(0xc000f20d00, 0x20e4ca0, 0xc00071a4e0, 0xc000218105, 0x19, 0xc00021811f, 0x4d, 0x0, 0xc00071a240, 0x1, ...)
        github.com/minio/minio/cmd/disk-cache.go:227 +0x1a1f fp=0xc021b2d098 sp=0xc021b2c348 pc=0x159861f
github.com/minio/minio/cmd.(*cacheObjects).GetObjectNInfo(0xc000f20d00, 0x20e4ca0, 0xc00071a4e0, 0xc000218105, 0x19, 0xc00021811f, 0x4d, 0x0, 0xc00071a240, 0x1, ...)
        github.com/minio/minio/cmd/disk-cache.go:227 +0x1a1f fp=0xc021b2dde8 sp=0xc021b2d098 pc=0x159861f
github.com/minio/minio/cmd.(*cacheObjects).GetObjectNInfo(0xc000f20d00, 0x20e4ca0, 0xc00071a4e0, 0xc000218105, 0x19, 0xc00021811f, 0x4d, 0x0, 0xc00071a240, 0x1, ...)
        github.com/minio/minio/cmd/disk-cache.go:227 +0x1a1f fp=0xc021b2eb38 sp=0xc021b2dde8 pc=0x159861f
github.com/minio/minio/cmd.(*cacheObjects).GetObjectNInfo(0xc000f20d00, 0x20e4ca0, 0xc00071a4e0, 0xc000218105, 0x19, 0xc00021811f, 0x4d, 0x0, 0xc00071a240, 0x1, ...)
        github.com/minio/minio/cmd/disk-cache.go:227 +0x1a1f fp=0xc021b2f888 sp=0xc021b2eb38 pc=0x159861f
github.com/minio/minio/cmd.(*cacheObjects).GetObjectNInfo(0xc000f20d00, 0x20e4ca0, 0xc00071a4e0, 0xc000218105, 0x19, 0xc00021811f, 0x4d, 0x0, 0xc00071a240, 0x1, ...)
        github.com/minio/minio/cmd/disk-cache.go:227 +0x1a1f fp=0xc021b305d8 sp=0xc021b2f888 pc=0x159861f
github.com/minio/minio/cmd.(*cacheObjects).GetObjectNInfo(0xc000f20d00, 0x20e4ca0, 0xc00071a4e0, 0xc000218105, 0x19, 0xc00021811f, 0x4d, 0x0, 0xc00071a240, 0x1, ...)
        github.com/minio/minio/cmd/disk-cache.go:227 +0x1a1f fp=0xc021b31328 sp=0xc021b305d8 pc=0x159861f
github.com/minio/minio/cmd.(*cacheObjects).GetObjectNInfo(0xc000f20d00, 0x20e4ca0, 0xc00071a4e0, 0xc000218105, 0x19, 0xc00021811f, 0x4d, 0x0, 0xc00071a240, 0x1, ...)
        github.com/minio/minio/cmd/disk-cache.go:227 +0x1a1f fp=0xc021b32078 sp=0xc021b31328 pc=0x159861f
github.com/minio/minio/cmd.(*cacheObjects).GetObjectNInfo(0xc000f20d00, 0x20e4ca0, 0xc00071a4e0, 0xc000218105, 0x19, 0xc00021811f, 0x4d, 0x0, 0xc00071a240, 0x1, ...)
        github.com/minio/minio/cmd/disk-cache.go:227 +0x1a1f fp=0xc021b32dc8 sp=0xc021b32078 pc=0x159861f
github.com/minio/minio/cmd.(*cacheObjects).GetObjectNInfo(0xc000f20d00, 0x20e4ca0, 0xc00071a4e0, 0xc000218105, 0x19, 0xc00021811f, 0x4d, 0x0, 0xc00071a240, 0x1, ...)
        github.com/minio/minio/cmd/disk-cache.go:227 +0x1a1f fp=0xc021b33b18 sp=0xc021b32dc8 pc=0x159861f
github.com/minio/minio/cmd.(*cacheObjects).GetObjectNInfo(0xc000f20d00, 0x20e4ca0, 0xc00071a4e0, 0xc000218105, 0x19, 0xc00021811f, 0x4d, 0x0, 0xc00071a240, 0x1, ...)
        github.com/minio/minio/cmd/disk-cache.go:227 +0x1a1f fp=0xc021b34868 sp=0xc021b33b18 pc=0x159861f
github.com/minio/minio/cmd.(*cacheObjects).GetObjectNInfo(0xc000f20d00, 0x20e4ca0, 0xc00071a4e0, 0xc000218105, 0x19, 0xc00021811f, 0x4d, 0x0, 0xc00071a240, 0x1, ...)
        github.com/minio/minio/cmd/disk-cache.go:227 +0x1a1f fp=0xc021b355b8 sp=0xc021b34868 pc=0x159861f
github.com/minio/minio/cmd.(*cacheObjects).GetObjectNInfo(0xc000f20d00, 0x20e4ca0, 0xc00071a4e0, 0xc000218105, 0x19, 0xc00021811f, 0x4d, 0x0, 0xc00071a240, 0x1, ...)
        github.com/minio/minio/cmd/disk-cache.go:227 +0x1a1f fp=0xc021b36308 sp=0xc021b355b8 pc=0x159861f
github.com/minio/minio/cmd.(*cacheObjects).GetObjectNInfo(0xc000f20d00, 0x20e4ca0, 0xc00071a4e0, 0xc000218105, 0x19, 0xc00021811f, 0x4d, 0x0, 0xc00071a240, 0x1, ...)
        github.com/minio/minio/cmd/disk-cache.go:227 +0x1a1f fp=0xc021b37058 sp=0xc021b36308 pc=0x159861f
github.com/minio/minio/cmd.(*cacheObjects).GetObjectNInfo(0xc000f20d00, 0x20e4ca0, 0xc00071a4e0, 0xc000218105, 0x19, 0xc00021811f, 0x4d, 0x0, 0xc00071a240, 0x1, ...)
        github.com/minio/minio/cmd/disk-cache.go:227 +0x1a1f fp=0xc021b37da8 sp=0xc021b37058 pc=0x159861f
github.com/minio/minio/cmd.(*cacheObjects).GetObjectNInfo(0xc000f20d00, 0x20e4ca0, 0xc00071a4e0, 0xc000218105, 0x19, 0xc00021811f, 0x4d, 0x0, 0xc00071a240, 0x1, ...)
        github.com/minio/minio/cmd/disk-cache.go:227 +0x1a1f fp=0xc021b38af8 sp=0xc021b37da8 pc=0x159861f
github.com/minio/minio/cmd.(*cacheObjects).GetObjectNInfo(0xc000f20d00, 0x20e4ca0, 0xc00071a4e0, 0xc000218105, 0x19, 0xc00021811f, 0x4d, 0x0, 0xc00071a240, 0x1, ...)
        github.com/minio/minio/cmd/disk-cache.go:227 +0x1a1f fp=0xc021b39848 sp=0xc021b38af8 pc=0x159861f
github.com/minio/minio/cmd.(*cacheObjects).GetObjectNInfo(0xc000f20d00, 0x20e4ca0, 0xc00071a4e0, 0xc000218105, 0x19, 0xc00021811f, 0x4d, 0x0, 0xc00071a240, 0x1, ...)
        github.com/minio/minio/cmd/disk-cache.go:227 +0x1a1f fp=0xc021b3a598 sp=0xc021b39848 pc=0x159861f
github.com/minio/minio/cmd.(*cacheObjects).GetObjectNInfo(0xc000f20d00, 0x20e4ca0, 0xc00071a4e0, 0xc000218105, 0x19, 0xc00021811f, 0x4d, 0x0, 0xc00071a240, 0x1, ...)
        github.com/minio/minio/cmd/disk-cache.go:227 +0x1a1f fp=0xc021b3b2e8 sp=0xc021b3a598 pc=0x159861f
github.com/minio/minio/cmd.(*cacheObjects).GetObjectNInfo(0xc000f20d00, 0x20e4ca0, 0xc00071a4e0, 0xc000218105, 0x19, 0xc00021811f, 0x4d, 0x0, 0xc00071a240, 0x1, ...)
        github.com/minio/minio/cmd/disk-cache.go:227 +0x1a1f fp=0xc021b3c038 sp=0xc021b3b2e8 pc=0x159861f
github.com/minio/minio/cmd.(*cacheObjects).GetObjectNInfo(0xc000f20d00, 0x20e4ca0, 0xc00071a4e0, 0xc000218105, 0x19, 0xc00021811f, 0x4d, 0x0, 0xc00071a240, 0x1, ...)
        github.com/minio/minio/cmd/disk-cache.go:227 +0x1a1f fp=0xc021b3cd88 sp=0xc021b3c038 pc=0x159861f
github.com/minio/minio/cmd.(*cacheObjects).GetObjectNInfo(0xc000f20d00, 0x20e4ca0, 0xc00071a4e0, 0xc000218105, 0x19, 0xc00021811f, 0x4d, 0x0, 0xc00071a240, 0x1, ...)
        github.com/minio/minio/cmd/disk-cache.go:227 +0x1a1f fp=0xc021b3dad8 sp=0xc021b3cd88 pc=0x159861f
github.com/minio/minio/cmd.(*cacheObjects).GetObjectNInfo(0xc000f20d00, 0x20e4ca0, 0xc00071a4e0, 0xc000218105, 0x19, 0xc00021811f, 0x4d, 0x0, 0xc00071a240, 0x1, ...)
        github.com/minio/minio/cmd/disk-cache.go:227 +0x1a1f fp=0xc021b3e828 sp=0xc021b3dad8 pc=0x159861f
github.com/minio/minio/cmd.(*cacheObjects).GetObjectNInfo(0xc000f20d00, 0x20e4ca0, 0xc00071a4e0, 0xc000218105, 0x19, 0xc00021811f, 0x4d, 0x0, 0xc00071a240, 0x1, ...)
        github.com/minio/minio/cmd/disk-cache.go:227 +0x1a1f fp=0xc021b3f578 sp=0xc021b3e828 pc=0x159861f
github.com/minio/minio/cmd.(*cacheObjects).GetObjectNInfo(0xc000f20d00, 0x20e4ca0, 0xc00071a4e0, 0xc000218105, 0x19, 0xc00021811f, 0x4d, 0x0, 0xc00071a240, 0x1, ...)
        github.com/minio/minio/cmd/disk-cache.go:227 +0x1a1f fp=0xc021b402c8 sp=0xc021b3f578 pc=0x159861f
github.com/minio/minio/cmd.(*cacheObjects).GetObjectNInfo(0xc000f20d00, 0x20e4ca0, 0xc00071a4e0, 0xc000218105, 0x19, 0xc00021811f, 0x4d, 0x0, 0xc00071a240, 0x1, ...)
        github.com/minio/minio/cmd/disk-cache.go:227 +0x1a1f fp=0xc021b41018 sp=0xc021b402c8 pc=0x159861f
github.com/minio/minio/cmd.(*cacheObjects).GetObjectNInfo(0xc000f20d00, 0x20e4ca0, 0xc00071a4e0, 0xc000218105, 0x19, 0xc00021811f, 0x4d, 0x0, 0xc00071a240, 0x1, ...)
        github.com/minio/minio/cmd/disk-cache.go:227 +0x1a1f fp=0xc021b41d68 sp=0xc021b41018 pc=0x159861f
github.com/minio/minio/cmd.(*cacheObjects).GetObjectNInfo(0xc000f20d00, 0x20e4ca0, 0xc00071a4e0, 0xc000218105, 0x19, 0xc00021811f, 0x4d, 0x0, 0xc00071a240, 0x1, ...)
        github.com/minio/minio/cmd/disk-cache.go:227 +0x1a1f fp=0xc021b42ab8 sp=0xc021b41d68 pc=0x159861f
github.com/minio/minio/cmd.(*cacheObjects).GetObjectNInfo(0xc000f20d00, 0x20e4ca0, 0xc00071a4e0, 0xc000218105, 0x19, 0xc00021811f, 0x4d, 0x0, 0xc00071a240, 0x1, ...)
        github.com/minio/minio/cmd/disk-cache.go:227 +0x1a1f fp=0xc021b43808 sp=0xc021b42ab8 pc=0x159861f
github.com/minio/minio/cmd.(*cacheObjects).GetObjectNInfo(0xc000f20d00, 0x20e4ca0, 0xc00071a4e0, 0xc000218105, 0x19, 0xc00021811f, 0x4d, 0x0, 0xc00071a240, 0x1, ...)
        github.com/minio/minio/cmd/disk-cache.go:227 +0x1a1f fp=0xc021b44558 sp=0xc021b43808 pc=0x159861f
github.com/minio/minio/cmd.(*cacheObjects).GetObjectNInfo(0xc000f20d00, 0x20e4ca0, 0xc00071a4e0, 0xc000218105, 0x19, 0xc00021811f, 0x4d, 0x0, 0xc00071a240, 0x1, ...)
        github.com/minio/minio/cmd/disk-cache.go:227 +0x1a1f fp=0xc021b452a8 sp=0xc021b44558 pc=0x159861f
github.com/minio/minio/cmd.(*cacheObjects).GetObjectNInfo(0xc000f20d00, 0x20e4ca0, 0xc00071a4e0, 0xc000218105, 0x19, 0xc00021811f, 0x4d, 0x0, 0xc00071a240, 0x1, ...)
        github.com/minio/minio/cmd/disk-cache.go:227 +0x1a1f fp=0xc021b45ff8 sp=0xc021b452a8 pc=0x159861f
github.com/minio/minio/cmd.(*cacheObjects).GetObjectNInfo(0xc000f20d00, 0x20e4ca0, 0xc00071a4e0, 0xc000218105, 0x19, 0xc00021811f, 0x4d, 0x0, 0xc00071a240, 0x1, ...)
        github.com/minio/minio/cmd/disk-cache.go:227 +0x1a1f fp=0xc021b46d48 sp=0xc021b45ff8 pc=0x159861f
github.com/minio/minio/cmd.(*cacheObjects).GetObjectNInfo(0xc000f20d00, 0x20e4ca0, 0xc00071a4e0, 0xc000218105, 0x19, 0xc00021811f, 0x4d, 0x0, 0xc00071a240, 0x1, ...)
        github.com/minio/minio/cmd/disk-cache.go:227 +0x1a1f fp=0xc021b47a98 sp=0xc021b46d48 pc=0x159861f
github.com/minio/minio/cmd.(*cacheObjects).GetObjectNInfo(0xc000f20d00, 0x20e4ca0, 0xc00071a4e0, 0xc000218105, 0x19, 0xc00021811f, 0x4d, 0x0, 0xc00071a240, 0x1, ...)
        github.com/minio/minio/cmd/disk-cache.go:227 +0x1a1f fp=0xc021b487e8 sp=0xc021b47a98 pc=0x159861f
created by net/http.(*Server).Serve
        net/http/server.go:2969 +0x36c

goroutine 1 [select, 2 minutes]:
github.com/minio/minio/cmd.handleSignals()
        github.com/minio/minio/cmd/signals.go:72 +0x10e
github.com/minio/minio/cmd.StartGateway(0xc0004b6b60, 0x20d8ae0, 0xc0006680a0)
        github.com/minio/minio/cmd/gateway-main.go:377 +0xaf3
github.com/minio/minio/cmd/gateway/s3.s3GatewayMain(0xc0004b6b60)
        github.com/minio/minio/cmd/gateway/s3/gateway-s3.go:98 +0x169
github.com/minio/cli.HandleAction(0x1a539a0, 0x1e47010, 0xc0004b6b60, 0xc0002c3300, 0x0)
        github.com/minio/cli@v1.22.0/app.go:500 +0xc2
github.com/minio/cli.Command.Run(0x1da8e43, 0x2, 0x0, 0x0, 0x0, 0x0, 0x0, 0x1de8f8f, 0x22, 0x0, ...)
        github.com/minio/cli@v1.22.0/command.go:225 +0x9fb
github.com/minio/cli.(*App).RunAsSubcommand(0xc0004b64e0, 0xc0004b6000, 0x0, 0x0)
        github.com/minio/cli@v1.22.0/app.go:387 +0x8d4
github.com/minio/cli.Command.startApp(0x1daf3e4, 0x7, 0x0, 0x0, 0x0, 0x0, 0x0, 0x1ddacd7, 0x1c, 0x0, ...)
        github.com/minio/cli@v1.22.0/command.go:313 +0x83f
github.com/minio/cli.Command.Run(0x1daf3e4, 0x7, 0x0, 0x0, 0x0, 0x0, 0x0, 0x1ddacd7, 0x1c, 0x0, ...)
        github.com/minio/cli@v1.22.0/command.go:111 +0x12a8
github.com/minio/cli.(*App).Run(0xc0001c1860, 0xc0000ba040, 0x4, 0x4, 0x0, 0x0)
        github.com/minio/cli@v1.22.0/app.go:261 +0x768
github.com/minio/minio/cmd.Main(0xc0000ba040, 0x4, 0x4)
        github.com/minio/minio/cmd/main.go:167 +0x89
main.main()
        github.com/minio/minio/main.go:37 +0x45

goroutine 5 [chan receive, 2 minutes]:
github.com/rjeczalik/notify.(*nonrecursiveTree).dispatch(0xc00007a2a0, 0xc00007a1e0)
        github.com/rjeczalik/notify@v0.9.2/tree_nonrecursive.go:36 +0xb6
created by github.com/rjeczalik/notify.newNonrecursiveTree
        github.com/rjeczalik/notify@v0.9.2/tree_nonrecursive.go:29 +0xe5

goroutine 6 [chan receive, 2 minutes]:
github.com/rjeczalik/notify.(*nonrecursiveTree).internal(0xc00007a2a0, 0xc00007a240)
        github.com/rjeczalik/notify@v0.9.2/tree_nonrecursive.go:81 +0x58
created by github.com/rjeczalik/notify.newNonrecursiveTree
        github.com/rjeczalik/notify@v0.9.2/tree_nonrecursive.go:30 +0x111

goroutine 7 [sleep, 2 minutes]:
time.Sleep(0x1a3185c5000)
        runtime/time.go:188 +0xbf
github.com/minio/minio/cmd/logger.(*logOnceType).cleanupRoutine(0xc000076370)
        github.com/minio/minio/cmd/logger/logonce.go:63 +0x36
created by github.com/minio/minio/cmd/logger.newLogOnceType
        github.com/minio/minio/cmd/logger/logonce.go:70 +0x77

goroutine 11 [select]:
go.opencensus.io/stats/view.(*worker).start(0xc0004fc5a0)
        go.opencensus.io@v0.22.3/stats/view/worker.go:154 +0x105
created by go.opencensus.io/stats/view.init.0
        go.opencensus.io@v0.22.3/stats/view/worker.go:32 +0x57

goroutine 52 [select]:
github.com/minio/minio/cmd/http.NewDNSCache.func2(0xc0000e05f0, 0xc0005227c0, 0xc0006b60c0)
        github.com/minio/minio/cmd/http/dial_dnscache.go:132 +0xbd
created by github.com/minio/minio/cmd/http.NewDNSCache
        github.com/minio/minio/cmd/http/dial_dnscache.go:130 +0x19e

goroutine 34 [IO wait, 1 minutes]:
internal/poll.runtime_pollWait(0x7f69d20ce038, 0x72, 0x0)
        runtime/netpoll.go:220 +0x55
internal/poll.(*pollDesc).wait(0xc000562018, 0x72, 0x0, 0x0, 0x1daeea4)
        internal/poll/fd_poll_runtime.go:87 +0x45
internal/poll.(*pollDesc).waitRead(...)
        internal/poll/fd_poll_runtime.go:92
internal/poll.(*FD).Accept(0xc000562000, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
        internal/poll/fd_unix.go:394 +0x1fc
net.(*netFD).accept(0xc000562000, 0x37e11d600, 0x0, 0x0)
        net/fd_unix.go:172 +0x45
net.(*TCPListener).accept(0xc000560020, 0xc00030ef88, 0xc00030ef90, 0x10)
        net/tcpsock_posix.go:139 +0x32
net.(*TCPListener).AcceptTCP(0xc000560020, 0xc00055e040, 0xc001d1c068, 0xc000566060)
        net/tcpsock.go:248 +0x65
github.com/minio/minio/cmd/http.(*httpListener).start.func3(0xc000560020, 0xc000566060)
        github.com/minio/minio/cmd/http/listener.go:91 +0x45
created by github.com/minio/minio/cmd/http.(*httpListener).start
        github.com/minio/minio/cmd/http/listener.go:105 +0x195

goroutine 72 [chan receive, 1 minutes]:
github.com/minio/minio/cmd/http.(*httpListener).Accept(0xc00055a090, 0xc000face30, 0x18, 0xc000e28f00, 0x72a9ac)
        github.com/minio/minio/cmd/http/listener.go:111 +0x57
net/http.(*Server).Serve(0xc0001f4900, 0x20d8b20, 0xc00055a090, 0x0, 0x0)
        net/http/server.go:2937 +0x266
github.com/minio/minio/cmd/http.(*Server).Start(0xc0001f4900, 0xc000e44660, 0xc000e44660)
        github.com/minio/minio/cmd/http/server.go:112 +0x245
github.com/minio/minio/cmd.StartGateway.func3(0xc0001f4900)
        github.com/minio/minio/cmd/gateway-main.go:292 +0x2b
created by github.com/minio/minio/cmd.StartGateway
        github.com/minio/minio/cmd/gateway-main.go:291 +0x7e5

goroutine 74 [syscall, 2 minutes]:
os/signal.signal_recv(0xc000046680)
        runtime/sigqueue.go:147 +0x9d
os/signal.loop()
        os/signal/signal_unix.go:23 +0x25
created by os/signal.Notify.func1.1
        os/signal/signal.go:150 +0x45

goroutine 58 [select, 2 minutes]:
github.com/minio/minio/cmd.(*cacheObjects).gc(0xc000f20d00, 0x20e4be0, 0xc0002cc000)
        github.com/minio/minio/cmd/disk-cache.go:712 +0x106
created by github.com/minio/minio/cmd.newServerCacheObjects
        github.com/minio/minio/cmd/disk-cache.go:703 +0x24d

goroutine 78 [select, 2 minutes]:
github.com/minio/minio/cmd.(*diskCache).purgeWait(0xc000fa3860, 0x20e4ca0, 0xc0005d2420)
        github.com/minio/minio/cmd/disk-cache-backend.go:262 +0xbb
created by github.com/minio/minio/cmd.newDiskCache
        github.com/minio/minio/cmd/disk-cache-backend.go:176 +0x30f

goroutine 226 [IO wait]:
internal/poll.runtime_pollWait(0x7f69d20cde78, 0x72, 0x20b3460)
        runtime/netpoll.go:220 +0x55
internal/poll.(*pollDesc).wait(0xc0005f5c98, 0x72, 0x20b3400, 0x2c2e7d8, 0x0)
        internal/poll/fd_poll_runtime.go:87 +0x45
internal/poll.(*pollDesc).waitRead(...)
        internal/poll/fd_poll_runtime.go:92
internal/poll.(*FD).Read(0xc0005f5c80, 0xc000bfa000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
        internal/poll/fd_unix.go:159 +0x1a5
net.(*netFD).Read(0xc0005f5c80, 0xc000bfa000, 0x1000, 0x1000, 0x203000, 0x203000, 0x203000)
        net/fd_posix.go:55 +0x4f
net.(*conn).Read(0xc0000b67e8, 0xc000bfa000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
        net/net.go:182 +0x8e
net/http.(*connReader).Read(0xc00019e210, 0xc000bfa000, 0x1000, 0x1000, 0x10000014e, 0x0, 0x7f69d1d8d8e0)
        net/http/server.go:798 +0x1ad
bufio.(*Reader).fill(0xc0000b9260)
        bufio/bufio.go:101 +0x105
bufio.(*Reader).ReadSlice(0xc0000b9260, 0xa, 0x7f69d1d8d8e0, 0xc001131988, 0x40d9f0, 0xc001050100, 0x100)
        bufio/bufio.go:360 +0x3d
bufio.(*Reader).ReadLine(0xc0000b9260, 0xc001050100, 0x47bdb4, 0xc0011a1400, 0x0, 0x40e358, 0x30)
        bufio/bufio.go:389 +0x34
net/textproto.(*Reader).readLineSlice(0xc000dc5920, 0xc001050100, 0x4a4e4d, 0xc0005f5c80, 0x0, 0x0)
        net/textproto/reader.go:58 +0x6c
net/textproto.(*Reader).ReadLine(...)
        net/textproto/reader.go:39
net/http.readRequest(0xc0000b9260, 0x0, 0xc001050100, 0x0, 0x0)
        net/http/request.go:1012 +0xaa
net/http.(*conn).readRequest(0xc0003601e0, 0x20e4be0, 0xc0010213c0, 0x0, 0x0, 0x0)
        net/http/server.go:984 +0x19a
net/http.(*conn).serve(0xc0003601e0, 0x20e4be0, 0xc0010213c0)
        net/http/server.go:1851 +0x705
created by net/http.(*Server).Serve
        net/http/server.go:2969 +0x36c

goroutine 402 [IO wait, 1 minutes]:
internal/poll.runtime_pollWait(0x7f69d20cdf58, 0x72, 0x20b3460)
        runtime/netpoll.go:220 +0x55
internal/poll.(*pollDesc).wait(0xc00067ed18, 0x72, 0x20b3400, 0x2c2e7d8, 0x0)
        internal/poll/fd_poll_runtime.go:87 +0x45
internal/poll.(*pollDesc).waitRead(...)
        internal/poll/fd_poll_runtime.go:92
internal/poll.(*FD).Read(0xc00067ed00, 0xc000136a91, 0x1, 0x1, 0x0, 0x0, 0x0)
        internal/poll/fd_unix.go:159 +0x1a5
net.(*netFD).Read(0xc00067ed00, 0xc000136a91, 0x1, 0x1, 0x0, 0x0, 0xc000a07200)
        net/fd_posix.go:55 +0x4f
net.(*conn).Read(0xc0005bf760, 0xc000136a91, 0x1, 0x1, 0x0, 0x0, 0x0)
        net/net.go:182 +0x8e
net/http.(*connReader).backgroundRead(0xc000136a80)
        net/http/server.go:690 +0x58
created by net/http.(*connReader).startBackgroundRead
        net/http/server.go:686 +0xd5

goroutine 9333 [IO wait]:
internal/poll.runtime_pollWait(0x7f69d20cdd98, 0x72, 0x20b3460)
        runtime/netpoll.go:220 +0x55
internal/poll.(*pollDesc).wait(0xc001904018, 0x72, 0x20b3400, 0x2c2e7d8, 0x0)
        internal/poll/fd_poll_runtime.go:87 +0x45
internal/poll.(*pollDesc).waitRead(...)
        internal/poll/fd_poll_runtime.go:92
internal/poll.(*FD).Read(0xc001904000, 0xc00031a000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
        internal/poll/fd_unix.go:159 +0x1a5
net.(*netFD).Read(0xc001904000, 0xc00031a000, 0x1000, 0x1000, 0x203000, 0x203000, 0x203000)
        net/fd_posix.go:55 +0x4f
net.(*conn).Read(0xc001d1c068, 0xc00031a000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
        net/net.go:182 +0x8e
net/http.(*connReader).Read(0xc0005d28d0, 0xc00031a000, 0x1000, 0x1000, 0x8, 0x0, 0x203000)
        net/http/server.go:798 +0x1ad
bufio.(*Reader).fill(0xc0005dc780)
        bufio/bufio.go:101 +0x105
bufio.(*Reader).ReadSlice(0xc0005dc780, 0xc000e6ee0a, 0x30, 0xc00190d988, 0x40dbe8, 0x7f69d20390e8, 0xc000213000)
        bufio/bufio.go:360 +0x3d
bufio.(*Reader).ReadLine(0xc0005dc780, 0xc000213000, 0x47bdb4, 0xc001030400, 0xc000faaa80, 0x40e358, 0x30)
        bufio/bufio.go:389 +0x34
net/textproto.(*Reader).readLineSlice(0xc000e6ee10, 0xc000213000, 0x4a4e4d, 0xc001904000, 0x0, 0x0)
        net/textproto/reader.go:58 +0x6c
net/textproto.(*Reader).ReadLine(...)
        net/textproto/reader.go:39
net/http.readRequest(0xc0005dc780, 0x0, 0xc000213000, 0x0, 0x0)
        net/http/request.go:1012 +0xaa
net/http.(*conn).readRequest(0xc000e2c6e0, 0x20e4be0, 0xc001020000, 0x0, 0x0, 0x0)
        net/http/server.go:984 +0x19a
net/http.(*conn).serve(0xc000e2c6e0, 0x20e4be0, 0xc001020000)
        net/http/server.go:1851 +0x705
created by net/http.(*Server).Serve
        net/http/server.go:2969 +0x36c
```

### PR DESCRIPTION
**Pull request by poornas**
Fixes: #10751

## Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [ ] Fixes a regression (If yes, please add `commit-id` or `PR #` here)
- [ ] Documentation needed
- [ ] Unit tests needed

### CODE REVIEW

**Review by harshavardhana — APPROVED** [review]

**Review by kerneltime — APPROVED** [review]
NIT: We should rename the `GetObjectNInfoFn` to `InternalObjectNInfoFn` as it is only used within `type cacheObjects`

**Comment by harshavardhana** [comment]
> NIT: We should rename the `GetObjectNInfoFn` to `InternalObjectNInfoFn` as it is only used within `type cacheObjects`

yeah InnerGetObjectNInfoFn will also work.

**Comment by minio-trusted** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-s3.sh | :heavy_check_mark: |
| mint-erasure.sh | :heavy_check_mark: |
| mint-dist-erasure.sh | :heavy_check_mark: |
| mint-zoned.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-gateway-azure.sh | :x: [more...](#4b1888c6-4f5a-436c-9a9f-32ca892f7d7b) |
<a name="4b1888c6-4f5a-436c-9a9f-32ca892f7d7b"></a>
### 10762-380afd1/mint-gateway-azure.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-dev8.minio.io:32595
ACCESS_KEY:           minioazure
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 55bcab87bb2c:/mint/log /tmp/mint-logs'

(1/15) Running aws-sdk-go tests ... done in 9 seconds
(2/15) Running aws-sdk-java tests ... done in 1 seconds
(3/15) Running aws-sdk-php tests ... done in 2 minutes and 33 seconds
(4/15) Running aws-sdk-ruby tests ... done in 21 seconds
(5/15) Running awscli tests ... done in 2 minutes and 55 seconds
(6/15) Running healthcheck tests ... done in 0 seconds
(7/15) Running mc tests ... done in 3 minutes and 24 seconds
(8/15) Running minio-dotnet tests ... done in 1 minutes and 39 seconds
(9/15) Running minio-go tests ... FAILED in 1 minutes and 47 seconds
{
  "args": {
    "bucketName": "minio-go-test-ateujndnukrw1hs1",
    "objectName": "test-object",
    "opts": "",
    "size": -1
  },
  "duration": 1032,
  "function": "PutObject(bucketName, objectName, reader,size,opts)",
  "message": "Unexpected size",
  "name": "minio-go: testPutObjectStreaming",
  "status": "FAIL"
}
(9/15) Running minio-java tests ... done in 10 minutes and 25 seconds
(10/15) Running minio-js tests ... FAILED in 46 seconds
{
  "name": "minio-js",
  "function": "\"after all\" hook in \"functional tests\"",
  "duration": 81,
  "status": "FAIL",
  "error": "S3Error: The bucket you tried to delete is not empty at Object.parseError (node_modules/minio/dist/main/xml-parsers.js:86:11) at /mint/run/core/minio-js/node_modules/minio/dist/main/transformers.js:156:22 at DestroyableTransform._flush (node_modules/minio/dist/main/transformers.js:80:10) at DestroyableTransform.prefinish (node_modules/readable-stream/lib/_stream_transform.js:129:10) at prefinish (node_modules/readable-stream/lib/_stream_writable.js:611:14) at finishMaybe (node_modules/readable-stream/lib/_stream_writable.js:620:5) at endWritable (node_modules/readable-stream/lib/_stream_writable.js:643:3) at DestroyableTransform.Writable.end (node_modules/readable-stream/lib/_stream_writable.js:571:22) at IncomingMessage.onend (_stream_readable.js:682:10) at endReadableNT (_stream_readable.js:1252:12) at processTicksAndRejections (internal/process/task_queues.js:80:21)"
}
(10/15) Running minio-py tests ... done in 19 minutes and 31 seconds
(11/15) Running s3cmd tests ... done in 2 minutes and 20 seconds
(12/15) Running s3select tests ... done in 39 seconds
(13/15) Running security tests ... done in 0 seconds

Executed 13 out of 15 tests successfully.
```
Deleting image on docker hub
Deleting image locally

**Comment by poornas** [comment]
> > NIT: We should rename the `GetObjectNInfoFn` to `InternalObjectNInfoFn` as it is only used within `type cacheObjects`
> 
> yeah InnerGetObjectNInfoFn will also work.

renamed

**Comment by minio-trusted** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-s3.sh | :heavy_check_mark: |
| mint-erasure.sh | :heavy_check_mark: |
| mint-dist-erasure.sh | :heavy_check_mark: |
| mint-zoned.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-gateway-azure.sh | :x: [more...](#545639e1-959a-4c42-a10d-a175289829b7) |
<a name="545639e1-959a-4c42-a10d-a175289829b7"></a>
### 10762-10f7c24/mint-gateway-azure.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-dev7.minio.io:30715
ACCESS_KEY:           minioazure
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 2c2cac0a3170:/mint/log /tmp/mint-logs'

(1/15) Running aws-sdk-go tests ... done in 8 seconds
(2/15) Running aws-sdk-java tests ... done in 1 seconds
(3/15) Running aws-sdk-php tests ... done in 2 minutes and 33 seconds
(4/15) Running aws-sdk-ruby tests ... done in 22 seconds
(5/15) Running awscli tests ... done in 2 minutes and 11 seconds
(6/15) Running healthcheck tests ... done in 0 seconds
(7/15) Running mc tests ... done in 3 minutes and 33 seconds
(8/15) Running minio-dotnet tests ... done in 2 minutes and 40 seconds
(9/15) Running minio-go tests ... FAILED in 1 minutes and 57 seconds
{
  "args": {
    "bucketName": "minio-go-test-evzxhc999xy0ofau",
    "objectName": "test-object",
    "opts": "",
    "size": -1
  },
  "duration": 1178,
  "function": "PutObject(bucketName, objectName, reader,size,opts)",
  "message": "Unexpected size",
  "name": "minio-go: testPutObjectStreaming",
  "status": "FAIL"
}
(9/15) Running minio-java tests ... FAILED in 28 seconds
{
  "name": "minio-java",
  "function": "getObject()",
  "args": "[multi-part upload]",
  "duration": 723,
  "status": "FAIL",
  "error": "java.net.SocketException: Connection reset >>> [java.base/java.net.SocketInputStream.read(SocketInputStream.java:186), java.base/java.net.SocketInputStream.read(SocketInputStream.java:140), okio.Okio$2.read(Okio.java:140), okio.AsyncTimeout$2.read(AsyncTimeout.java:237), okio.RealBufferedSource.indexOf(RealBufferedSource.java:358), okio.RealBufferedSource.readUtf8LineStrict(RealBufferedSource.java:230), okhttp3.internal.http1.Http1ExchangeCodec.readHeaderLine(Http1ExchangeCodec.java:242), okhttp3.internal.http1.Http1ExchangeCodec.readResponseHeaders(Http1ExchangeCodec.java:213), okhttp3.internal.connection.Exchange.readResponseHeaders(Exchange.java:115), okhttp3.internal.http.CallServerInterceptor.intercept(CallServerInterceptor.java:94), okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142), okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:43), okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142), okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117), okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:94), okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142), okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117), okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93), okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142), okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:88), okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142), okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117), okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:229), okhttp3.RealCall.execute(RealCall.java:81), io.minio.MinioClient.execute(MinioClient.java:1014), io.minio.MinioClient.uploadPart(MinioClient.java:7781), io.minio.MinioClient.putObject(MinioClient.java:4706), io.minio.MinioClient.putObject(MinioClient.java:4881), FunctionalTest.testGetObject(FunctionalTest.java:1161), FunctionalTest.getObject_test(FunctionalTest.java:1244), FunctionalTest.runTests(FunctionalTest.java:3792), FunctionalTest.main(FunctionalTest.java:4058)]"
}
(9/15) Running minio-js tests ... FAILED in 47 seconds
{
  "name": "minio-js",
  "function": "\"after all\" hook in \"functional tests\"",
  "duration": 80,
  "status": "FAIL",
  "error": "S3Error: The bucket you tried to delete is not empty at Object.parseError (node_modules/minio/dist/main/xml-parsers.js:86:11) at /mint/run/core/minio-js/node_modules/minio/dist/main/transformers.js:156:22 at DestroyableTransform._flush (node_modules/minio/dist/main/transformers.js:80:10) at DestroyableTransform.prefinish (node_modules/readable-stream/lib/_stream_transform.js:129:10) at prefinish (node_modules/readable-stream/lib/_stream_writable.js:611:14) at finishMaybe (node_modules/readable-stream/lib/_stream_writable.js:620:5) at endWritable (node_modules/readable-stream/lib/_stream_writable.js:643:3) at DestroyableTransform.Writable.end (node_modules/readable-stream/lib/_stream_writable.js:571:22) at IncomingMessage.onend (_stream_readable.js:682:10) at endReadableNT (_stream_readable.js:1252:12) at processTicksAndRejections (internal/process/task_queues.js:80:21)"
}
(9/15) Running minio-py tests ... done in 18 minutes and 26 seconds
(10/15) Running s3cmd tests ... done in 2 minutes and 39 seconds
(11/15) Running s3select tests ... done in 38 seconds
(12/15) Running security tests ... done in 0 seconds

Executed 12 out of 15 tests successfully.
```
Deleting image on docker hub
Deleting image locally

File: cmd/disk-cache.go [hunk 1]
```diff
@@ -77,11 +77,11 @@ type cacheObjects struct {
 	// Cache stats
 	cacheStats *CacheStats
 
-	GetObjectNInfoFn func(ctx context.Context, bucket, object string, rs *HTTPRangeSpec, h http.Header, lockType LockType, opts ObjectOptions) (gr *GetObjectReader, err error)
-	GetObjectInfoFn  func(ctx context.Context, bucket, object string, opts ObjectOptions) (objInfo ObjectInfo, err error)
-	DeleteObjectFn   func(ctx context.Context, bucket, object string, opts ObjectOptions) (objInfo ObjectInfo, err error)
-	PutObjectFn      func(ctx context.Context, bucket, object string, data *PutObjReader, opts ObjectOptions) (objInfo ObjectInfo, err error)
-	CopyObjectFn     func(ctx context.Context, srcBucket, srcObject, destBucket, destObject string, srcInfo ObjectInfo, srcOpts, dstOpts ObjectOptions) (objInfo ObjectInfo, err error)
+	InnerGetObjectNInfoFn func(ctx context.Context, bucket, object string, rs *HTTPRangeSpec, h http.Header, lockType LockType, opts ObjectOptions) (gr *GetObjectReader, err error)
+	GetObjectInfoFn       func(ctx context.Context, bucket, object string, opts ObjectOptions) (objInfo ObjectInfo, err error)
```
Comment (kerneltime) [inline cmd/disk-cache.go:81]: all these should be renamed ?

Comment (harshavardhana) [reply cmd/disk-cache.go:81]: let's take this in @kerneltime and do it later. Its blocking the release
