### PR TITLE
heal: Print heal command appropriately without export path.

### LINKED ISSUE #3204: [distributed] replace disk, minio server gives incorrect heal command
## Expected Behavior
should give:
```
MINIO_ACCESS_KEY=SXO8VW2OFKKP2OG7AC85 MINIO_SECRET_KEY=CKWSSgrUgvfUMTaNBkB63exet4WW+uNhQvi91Bc3 minio control heal http://localhost:9001
```
## Current Behavior
```
Data volume requires HEALING. Please run the following command:
MINIO_ACCESS_KEY=SXO8VW2OFKKP2OG7AC85 MINIO_SECRET_KEY=CKWSSgrUgvfUMTaNBkB63exet4WW+uNhQvi91Bc3 minio control heal http://localhost:9001/export/disk1
```

## Steps to Reproduce (for bugs)
* start 2:2 d-XL
* bring down 4th server
* replace disk (rm -rf the dir and mkdir again)
* start 4th server, it prints:

```
krishna@escape:~$ minio server --address localhost:9004 http://localhost:9001/export/disk1 http://localhost:9002/export/disk2 http://localhost:9003/export/disk3 http://localhost:9004/export/disk4

Data volume requires HEALING. Please run the following command:
MINIO_ACCESS_KEY=SXO8VW2OFKKP2OG7AC85 MINIO_SECRET_KEY=CKWSSgrUgvfUMTaNBkB63exet4WW+uNhQvi91Bc3 minio control heal http://localhost:9001/export/disk1
[01/04] localhost:9001:/export/disk1 - 38 GiB online
[02/04] localhost:9002:/export/disk2 - 38 GiB online
[03/04] localhost:9003:/export/disk3 - 38 GiB online
[04/04] /export/disk4 - 38 GiB online

Endpoint:  http://localhost:9004
AccessKey: SXO8VW2OFKKP2OG7AC85 
SecretKey: CKWSSgrUgvfUMTaNBkB63exet4WW+uNhQvi91Bc3 
Region:    us-east-1
SQS ARNs:  <none>

Browser Access:
   http://localhost:9004

Command-line Access: https://docs.minio.io/docs/minio-client-quickstart-guide

```

### PR DESCRIPTION
**Pull request by harshavardhana**
## Description
Heal command message should print an appropriate endpoint

## Motivation and Context
Fixes #3204 

## How Has This Been Tested?
Manually.

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by fwessels** [comment]
LGTM

File: cmd/prepare-storage.go [hunk 1]
```diff
@@ -239,7 +235,16 @@ func retryFormattingDisks(firstDisk bool, endpoints []*url.URL, storageDisks []S
...
+						// Healing should always be trigerred from first endpoint.
+						firstEndpoint := endpoints[0]
+						if firstEndpoint == nil {
+							return errInvalidArgument
+						}
+						// We do not need the path component, just extract Host and Scheme.
+						printHealMsg(&url.URL{
+							Host:   firstEndpoint.Host,
+							Scheme: firstEndpoint.Scheme,
+						}, storageDisks, printOnceFn())
```
Comment (krishnasrinivas) [inline cmd/prepare-storage.go]: for singlenode-XL endpoint.Path will be relevant but here path is not getting passed

Comment (harshavardhana) [reply cmd/prepare-storage.go]: why would the path be relevant? @krishnasrinivas healing happens on buckets not individual disks.

Comment (harshavardhana) [reply cmd/prepare-storage.go]: I think there is a bug for single disks since the endpoint is actually a disk so it won't work. Let me fix it.

**Comment by harshavardhana** [comment]
ping @krishnasrinivas check now.

File: cmd/prepare-storage-msg.go [hunk 2]
```diff
@@ -49,21 +50,50 @@ func printOnceFn() printOnceFunc {
...
+				cEndpoint.Host = net.JoinHostPort(hosts[0], globalMinioPort)
+			}
+			return cEndpoint
+		}
+		cEndpoint.Host = firstEndpoint.Host
+		return cEndpoint
+	}
+	cEndpoint.Host = net.JoinHostPort(globalMinioHost, globalMinioPort)
+	return cEndpoint
+}
```
Comment (krishnasrinivas) [inline cmd/prepare-storage-msg.go:90]: this function is more readable if written the following way:
(i.e no multiple levels of `if {...}` indentation and add comments

```
func getHealEndpoint(tls bool, firstEndpoint *url.URL) (cEndpoint *url.URL) {                                                                                                   
        scheme := "http"                                                                                                                                                        
        if tls {                                                                                                                                                                
                scheme = "https"                                                                                                                                                

        }                                                                                                                                                                       
        cEndpoint = &url.URL{                                                                                                                                                   
                Scheme: scheme,                                                                                                                                                 
        }                                                                                                                                                                       
        if globalMinioHost != "" {                                                                                                                                              
                // Host was specified in --address host:port                                                                                                                    
                cEndpoint.Host = net.JoinHostPort(globalMinioHost, globalMinioPort)                                                                                             
                return cEndpoint                                                                                                                                                
        }                                                                                                                                                                       
        if firstEndpoint.Host != "" {                                                                                                                                           
                // singlenode-XL without --address config                                                                                                                                               
                cEndpoint.Host = firstEndpoint.Host                                                                                                                             
                return cEndpoint                                                                                                                                                
        }                                                                                                                                                                       
        // distributed-XL setup without --address config                                                                                                                        
        cEndpoint.Host = globalMinioAddr                                                                                                                                        
        hosts, _, err := getListenIPs(cEndpoint.Host)                                                                                                                           
        if err == nil {                                                                                                                                                         
                cEndpoint.Host = net.JoinHostPort(hosts[0], globalMinioPort)                                                                                                    

        }                                                                                                                                                                       
        return cEndpoint                                                                                                                                                        
}
```

File: cmd/prepare-storage-msg_test.go [hunk 3]
```diff
@@ -18,9 +18,38 @@ package cmd
 
 import (
 	"net/url"
+	"reflect"
 	"testing"
 )
 
+func TestHealEndpoint(t *testing.T) {
```
Comment (krishnasrinivas) [inline cmd/prepare-storage-msg_test.go]: since this function tests `getHealEndpoint` only it should be named TestGetHealEndpoint since that is the convention

File: cmd/prepare-storage-msg_test.go [hunk 4]
```diff
@@ -18,9 +18,38 @@ package cmd
...
+		Scheme: "https",
+		Host:   "localhost:9000",
+	})
+	sHURL = &url.URL{
+		Scheme: "http",
+		Host:   "localhost:9000",
+	}
+	if !reflect.DeepEqual(hURL, sHURL) {
+		t.Fatalf("Expected %#v, but got %#v", sHURL, hURL)
+	}
```
Comment (krishnasrinivas) [inline cmd/prepare-storage-msg_test.go:53]: there can be one test case added when url.Host == ""

File: cmd/prepare-storage-msg.go (hunk 2 above)
Comment (harshavardhana) [reply cmd/prepare-storage-msg.go:90]: This looks good more explicit about each cases, incorporating.

File: cmd/prepare-storage-msg_test.go (hunk 4 above)
Comment (harshavardhana) [reply cmd/prepare-storage-msg_test.go:53]: I avoided the globalHost case on purpose, so that we don't add more racy tests until @hackintoshrao finishes his work on saving global states.

**Review by krishnasrinivas — APPROVED** [review]
