### PR TITLE
fix: validate incoming uploadID to be base64 encoded

### LINKED ISSUE #17863: Data loss from multiple calls to CompleteMultipartUpload object in a short period of time
### Discussed in https://github.com/minio/minio/discussions/17859

<div type='discussions-op-text'>

<sup>Originally posted by **xieys0** August 16, 2023</sup>
## Environment
OS:  Ubuntu22.04.1
Version:  https://dl.min.io/server/minio/release/linux-amd64/archive/minio_20230809233022.0.0_amd64.deb

# df -HT
root@ubuntu:~# df -hT
Filesystem     Type   Size  Used Avail Use% Mounted on
tmpfs          tmpfs  6.3G  2.2M  6.3G   1% /run
/dev/sda2      ext4   479G   12G  443G   3% /
tmpfs          tmpfs   32G     0   32G   0% /dev/shm
tmpfs          tmpfs  5.0M     0  5.0M   0% /run/lock
/dev/sda1      vfat   1.1G  6.1M  1.1G   1% /boot/efi
tmpfs          tmpfs  6.3G  4.0K  6.3G   1% /run/user/0
/dev/sdb       xfs    7.3T   52G  7.3T   1% /mnt/disk1
/dev/sdc       xfs    7.3T   52G  7.3T   1% /mnt/disk2
/dev/sdd       xfs    7.3T   52G  7.3T   1% /mnt/disk3
/dev/sde       xfs    7.3T   52G  7.3T   1% /mnt/disk4

# cat /etc/default/minio
MINIO_ROOT_USER=xxxx
MINIO_ROOT_PASSWORD=xxxx
MINIO_OPTS="--address :9000 --console-address :9001"
MINIO_VOLUMES="/mnt/disk{1...4}"

## Describe
Calling the CompleteMultipartUpload interface multiple times for the same uploadId in a short period of time. The first call returned success, while the other returned uploadId does not exist. The object information can be found, but the object data is missing and cannot be downloaded or restored. There are only xl. meta files in the object folder.

root@ubuntu:/mnt/disk1/test/0CA985D3589645E49ADFAF4391FA754D# ls -la
total 4
drwxr-xr-x 2 minio-user minio-user  29 Aug 15 11:14 .
drwxr-xr-x 3 minio-user minio-user  54 Aug 15 11:14 ..
-rw-r--r-- 1 minio-user minio-user 844 Aug 15 11:14 xl.meta

## Expected Behavior
Object data is not lost

## Current Behavior
Object data is not lost

## Notes
Historical versions and Ubuntu multi node and multi driver environments can still be replicated</div>

### PR DESCRIPTION
**Pull request by harshavardhana**
fixes #17863

## Contribution License
All contributions in this pull request are licensed to the project maintainers 
under the terms of the [Apache 2 license] (https://www.apache.org/licenses/LICENSE-2.0). 
By creating this pull request I represent that I have the right to license the 
contributions to the project maintainers under the Apache 2 license.

## Description
fix: validate incoming uploadID to be base64 encoded

## Motivation and Context
Bonus fixes include

- do not have to write final xl.meta (renameData) does this already, saves some IOPs.

- make sure to purge the multipart directory properly using a recursive delete, otherwise this can easily pile up and rely on the stale uploads cleanup.

## How to test this PR?
As per #17863 

## Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Optimization (provides speedup with no functional changes)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [ ] Fixes a regression (If yes, please add `commit-id` or `PR #` here)
- [ ] Unit tests added/updated
- [ ] Internal documentation updated
- [ ] Create a documentation update request [here](https://github.com/minio/docs/issues/new?label=doc-change,title=Doc+Updated+Needed+For+PR+github.com%2fminio%2fminio%2fpull%2fNNNNN)

### CODE REVIEW

File: cmd/erasure-multipart.go [hunk 1]
```diff
@@ -1227,12 +1226,6 @@ func (er erasureObjects) CompleteMultipartUpload(ctx context.Context, bucket str
 	ctx = lkctx.Context()
 	defer lk.Unlock(lkctx)
 
-	// Write final `xl.meta` at uploadID location
```
Comment (klauspost) [inline cmd/erasure-multipart.go:1230]: So this is already done by renamedata? Nice to get rid of this!

**Review by klauspost — APPROVED** [review]
LGTM

File: cmd/erasure-multipart.go (hunk 1 above)
Comment (harshavardhana) [reply cmd/erasure-multipart.go:1230]: yes @klauspost

**Review by krisis — APPROVED** [review]
