### PR TITLE
windows: Support all REPARSE_POINT attrib files properly.

### LINKED ISSUE #4122: Minio server cant read Windows 2016 deduplicated files
After uploading a file to minio server running on Windows 2016, Everything seems fine and  file is accessible fine using mc client. But as soon as scheduled deduplication runs on the server and  the file's "size on disk" changes to Zero in file properties, minio client cant retrive/list the file. And with every attempt to retrive/list file using mc client, i get below error on  minio server console 

time="2017-04-14T08:38:44-07:00" level=error msg="Unable to stat path d:\\data2/xxxxxx/c4/bb/c4bbf66cbdd866476f0247059f220667/c4bbf66cbdd866476f0247059f220667.ntfsclone.1492098076" cause="readlink \\\\?\\d:\\data2\\xxxxxx\\c4\\bb\\c4bbf66cbdd866476f0247059f220667\\c4bbf66cbdd866476f0247059f220667.ntfsclone.1492098076: The system cannot find the file specified." source="[posix-list-dir-others.go:60:readDir()]"

## Expected Behavior

Since deduplicated file(s) are present in data folders so they must be accessible as any other file(s) 

## Current Behavior

mc client dont list the deduplicated file(s) and server console print above mentioned error

## Steps to Reproduce (for bugs)

1. Setup a windows 2016 server with deduplicated volume d:\\
2.  Start minio on windows 2016 server as "minio.exe server d:\\data2
3.  From a linux server using linux mc client create a bucket
4. Upload a large file to minio server
(NOTE: several copies of same file must be present on the server with different names so that windows deduplication can really deduplicate it)
5. Varify... the file is accessable using mc client
6. Wait untill windows run and finish its scheduled deduplication process or start the deduplication manually and wait for it to finish
7. Try to access same file using mc client and file wont list. And on server you will see above mentioned error on minio console

## Context

Trying to setup minio server on a windows 2016 deduplicated volume

## Your Environment

* Version used:
2017-03-16T21:50:32Z

* Environment name and version (e.g. nginx 1.9.1):
minio.exe for windows 64 bit
* Server type and version:
Windows 64 bit
* Operating System and version:
Windows Server 2016  (Build 14393)
* Link to your project:

### PR DESCRIPTION
**Pull request by harshavardhana**
## Description
This change adopts the upstream fix in this regard at
https://go-review.googlesource.com/#/c/41834/ for Minio's
purposes.

Go's current os.Stat() lacks support for lot of strange
windows files such as

 - share symlinks on SMB2
 - symlinks on docker nanoserver
 - de-duplicated files on NTFS de-duplicated volume.

This PR attempts to incorporate the change mentioned here

   https://blogs.msdn.microsoft.com/oldnewthing/20100212-00/?p=14963/

The article suggests to use Windows I/O manager to
dereferences the symbolic link.

## Motivation and Context
Fixes #4122

## How Has This Been Tested?
Manually on Windows with NTFS volume. 

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by vadmeste** [comment]
I tested this PR with basic operations but not with deduplication yet. LGTM otherwise.

**Comment by harshavardhana** [comment]
This PR is ready for review and testing @vadmeste @krisis - please test with a Windows Server 2012 and above with NTFS Deduplication enabled.

File: cmd/posix-stat_windows.go [hunk 1]
```diff
@@ -0,0 +1,210 @@
...
+	}
+	if name == os.DevNull {
+		return &devNullStat, nil
+	}
+	namep, err := syscall.UTF16PtrFromString(name)
+	if err != nil {
+		return nil, &os.PathError{Op: "Stat", Path: name, Err: err}
+	}
+
+	// Use Windows I/O manager to dereferences the symbolic link, as per
```
Comment (krisis) [inline cmd/posix-stat_windows.go]: typo: s/dereferences/dereference

File: cmd/posix-stat_windows.go [hunk 2]
```diff
@@ -0,0 +1,210 @@
...
+func (fs *fileStat) IsDir() bool  { return fs.Mode().IsDir() }
+
+func (fs *fileStat) Size() int64 {
+	return int64(fs.sys.FileSizeHigh)<<32 + int64(fs.sys.FileSizeLow)
+}
+
+// devNullStat is fileStat structure describing DevNull file ("NUL").
+var devNullStat = fileStat{
+	name: os.DevNull,
+	// hopefully this will work for SameFile
```
Comment (krisis) [inline cmd/posix-stat_windows.go]: what is not known about this? Is this unit-testable?

File: cmd/posix-stat_windows_test.go [hunk 3]
```diff
@@ -0,0 +1,209 @@
...
+	if err != nil {
+		t.Fatal(err)
+	}
+	err = os.Chdir(dir)
+	if err != nil {
+		t.Fatal(err)
+	}
+	defer os.Chdir(oldwd)
+
+	shareName := "GoSymbolicLinkTestShare" // hope no conflictions
```
Comment (krisis) [inline cmd/posix-stat_windows_test.go]: s/conflictions/conflicts

File: cmd/posix-stat_windows.go (hunk 2 above)
Comment (harshavardhana) [reply cmd/posix-stat_windows.go]: Actually that comment is not needed..

File: cmd/posix-stat_windows.go (hunk 1 above)
Comment (harshavardhana) [reply cmd/posix-stat_windows.go]: done

File: cmd/posix-stat_windows_test.go (hunk 3 above)
Comment (harshavardhana) [reply cmd/posix-stat_windows_test.go]: done

**Review by vadmeste — APPROVED** [review]
Tested with basic and dedup files

**Review by vadmeste — APPROVED** [review]
Tested with docker windows container as well.

**Comment by harshavardhana** [comment]
@krisis any feedback ?

**Comment by krisis** [comment]
Testing remains.

**Review by krisis — APPROVED** [review]
LGTM. Tested on a Windows instance.
