### PR TITLE
gateway-s3: Avoid x2 double quotes in ListParts

### LINKED ISSUE #4294: [gateway-s3] List Parts returns parts with ETag having doubled double quotes
## Expected Behavior
ListParts returns 
```
...<Part><PartNumber>1</PartNumber
><LastModified>2017-05-08T18:53:09.031Z</LastModified><ETag>&#34;&#34;d9340f5267685ca716e86c33e570c12e&#34;&#34;</ETag><Size>67108864</Size></Part><Part>...
```

## Current Behavior
ListParts returns 
```
...<Part><PartNumber>1</PartNumber
><LastModified>2017-05-08T18:53:09.031Z</LastModified><ETag>&#34;d9340f5267685ca716e86c33e570c12e&#34;</ETag><Size>67108864</Size></Part><Part>...
```
## Steps to Reproduce (for bugs)
1. Setup a Minio gateway instance pointing to an S3 server
2. Setup a multipart upload and upload a part
3. List parts

(I did this with mc after tweaking some codes to the the gateway xml response)

## Context
Testing

## Your Environment
All, master

### PR DESCRIPTION
**Pull request by vadmeste**
## Description
ListParts response returns doubled double quotes in ETag field.
This commit cleans ETag when receiving it from minio client to
fix the issue.

## Motivation and Context
Fixes #4294 

## How Has This Been Tested?
Manually

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

File: cmd/gateway-s3.go [hunk 1]
```diff
@@ -447,9 +448,12 @@ func (l *s3Gateway) CopyObjectPart(srcBucket string, srcObject string, destBucke
 
 // fromMinioClientObjectPart converts minio ObjectPart to PartInfo
 func fromMinioClientObjectPart(op minio.ObjectPart) PartInfo {
+	// ETag in minio client response contains
+	// double quotes, we need to clean them.
+	cleanETag := strings.Trim(op.ETag, "\"")
```
Comment (harshavardhana) [inline cmd/gateway-s3.go]: Use canonicalizeETag() function here @vadmeste

**Review by harshavardhana — CHANGES_REQUESTED** [review]

File: cmd/gateway-s3.go (hunk 1 above)
Comment (vadmeste) [reply cmd/gateway-s3.go]: Done

**Review by harshavardhana — APPROVED** [review]
Testing LGTM.

**Review by nl5887 — APPROVED** [review]
LGTM
