### PR TITLE
fix: remove the sleep from listing operations

### LINKED ISSUE #9261: Intermittent slow list object
## Expected Behavior

ListObjects should be fast on small number of objects

## Current Behavior

ListObjects is slow (>1 second, I've even seen 20s) sometimes, but not always, even when my distributed minio cluster is under low load.

## Steps to Reproduce (for bugs)
This happens both when using s3 client, minio client or via curl requests. For instance:
```plaintext
nepoxx@nepoxx-arch ~> time mcli ls  --debug sbk/com.company.arcadia/project/builds.temp/
mcli: <DEBUG> GET /com.company.arcadia/?location= HTTP/1.1
Host: minio.company.com
User-Agent: MinIO (linux; amd64) minio-go/v6.0.45 mcli/2019-12-17T23:26:28Z
Authorization: AWS4-HMAC-SHA256 Credential=**REDACTED**/20200403/us-east-1/s3/aws4_request, SignedHeaders=host;x-amz-content-sha256;x-amz-date, Signature=**REDACTED**
X-Amz-Content-Sha256: UNSIGNED-PAYLOAD
X-Amz-Date: 20200403T170025Z
Accept-Encoding: gzip

mcli: <DEBUG> HTTP/1.1 200 OK
Content-Length: 128
Accept-Ranges: bytes
Content-Security-Policy: block-all-mixed-content
Content-Type: application/xml
Date: Fri, 03 Apr 2020 17:00:26 GMT
Server: MinIO/RELEASE.2020-04-02T21-34-49Z
Vary: Origin
X-Amz-Request-Id: 16025DDDCE69F051
X-Xss-Protection: 1; mode=block

mcli: <DEBUG> Response Time:  45.381652ms

mcli: <DEBUG> GET /com.company.arcadia/?delimiter=%2F&encoding-type=url&fetch-owner=true&list-type=2&prefix=project%2Fbuilds.temp HTTP/1.1
Host: minio.company.com
User-Agent: MinIO (linux; amd64) minio-go/v6.0.45 mcli/2019-12-17T23:26:28Z
Authorization: AWS4-HMAC-SHA256 Credential=**REDACTED**/20200403/us-east-1/s3/aws4_request, SignedHeaders=host;x-amz-content-sha256;x-amz-date, Signature=**REDACTED**
X-Amz-Content-Sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
X-Amz-Date: 20200403T170026Z
Accept-Encoding: gzip

mcli: <DEBUG> HTTP/1.1 200 OK
Content-Length: 431
Accept-Ranges: bytes
Content-Security-Policy: block-all-mixed-content
Content-Type: application/xml
Date: Fri, 03 Apr 2020 17:00:26 GMT
Server: MinIO/RELEASE.2020-04-02T21-34-49Z
Vary: Origin
X-Amz-Request-Id: 16025DDDCEB58161
X-Xss-Protection: 1; mode=block

mcli: <DEBUG> Response Time:  13.773497ms

mcli: <DEBUG> GET /com.company.arcadia/?delimiter=%2F&encoding-type=url&fetch-owner=true&list-type=2&prefix=project%2Fbuilds.temp%2F HTTP/1.1
Host: minio.company.com
User-Agent: MinIO (linux; amd64) minio-go/v6.0.45 mcli/2019-12-17T23:26:28Z
Authorization: AWS4-HMAC-SHA256 Credential=**REDACTED**/20200403/us-east-1/s3/aws4_request, SignedHeaders=host;x-amz-content-sha256;x-amz-date, Signature=**REDACTED**
X-Amz-Content-Sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
X-Amz-Date: 20200403T170026Z
Accept-Encoding: gzip

mcli: <DEBUG> HTTP/1.1 200 OK
Content-Length: 42270
Accept-Ranges: bytes
Content-Security-Policy: block-all-mixed-content
Content-Type: application/xml
Date: Fri, 03 Apr 2020 17:00:27 GMT
Server: MinIO/RELEASE.2020-04-02T21-34-49Z
Vary: Origin
X-Amz-Request-Id: 16025DDDCF89F6BB
X-Xss-Protection: 1; mode=block

mcli: <DEBUG> Response Time: 10.811303031s

[2020-04-02 07:29:55 EDT]  1.6GiB 139131
[truncated (about 120 objects)]
[2020-04-03 12:36:09 EDT]  1.6GiB 139373

________________________________________________________
Executed in   10.93 secs   fish           external
   usr time   90.42 millis  597.00 micros   89.82 millis
   sys time   36.13 millis  242.00 micros   35.88 millis
```
(>10s for ~120 objects)

## Your Environment

* Version used (`minio version`):
```plaintext
●  minio1:9000
   Uptime: 57 minutes
   Version: 2020-04-02T21:34:49Z
   Network: 6/6 OK
   Drives: 2/2 OK

●  minio2:9000
   Uptime: 57 minutes
   Version: 2020-04-02T21:34:49Z
   Network: 6/6 OK
   Drives: 2/2 OK

●  minio3:9000
   Uptime: 57 minutes
   Version: 2020-04-02T21:34:49Z
   Network: 6/6 OK
   Drives: 2/2 OK

●  minio4:9000
   Uptime: 57 minutes
   Version: 2020-04-02T21:34:49Z
   Network: 6/6 OK
   Drives: 2/2 OK

●  minio5:9000
   Uptime: 57 minutes
   Version: 2020-04-02T21:34:49Z
   Network: 6/6 OK
   Drives: 2/2 OK

●  minio0:9000
   Uptime: 57 minutes
   Version: 2020-04-02T21:34:49Z
   Network: 6/6 OK
   Drives: 2/2 OK

1.2 TiB Used, 12 Buckets, 116,123 Objects
12 drives online, 0 drives offline
```
* Environment name and version (e.g. nginx 1.9.1):
Using docker swarm with Traefik. Swarm details:
```yaml
version: '3.7'

x-default-deploy: &default-deploy
  endpoint_mode: dnsrr
  replicas: 1
  restart_policy:
    condition: any
    delay: 10s
    window: 60s
  labels:
    - "traefik.enable=true"
    - "traefik.http.routers.minio.entrypoints=http"
    - "traefik.http.routers.minio.rule=Host(`minio.company.com`)"
    - "traefik.http.routers.minio.service=minio"
    - "traefik.http.routers.minio.tls=false"
    - "traefik.http.routers.minio_tls.entrypoints=https"
    - "traefik.http.routers.minio_tls.rule=Host(`minio.company.com`)"
    - "traefik.http.routers.minio_tls.service=minio"
    - "traefik.http.routers.minio_tls.tls=true"
    - "traefik.http.services.minio.loadbalancer.server.port=9000"
    - "traefik.http.services.minio.loadbalancer.healthcheck.port=9000"
    - "traefik.http.services.minio.loadbalancer.healthcheck.path=/minio/health/ready"
    - "traefik.http.services.minio.loadbalancer.healthcheck.interval=20s"
    - "traefik.http.services.minio.loadbalancer.passhostheader=true"

x-venus-deploy: &venus-deploy
  <<: *default-deploy
  placement:
    constraints:
      - node.hostname == venus

x-mars-deploy: &mars-deploy
  <<: *default-deploy
  placement:
    constraints:
      - node.hostname == mars

x-saturn-deploy: &saturn-deploy
  <<: *default-deploy
  placement:
    constraints:
      - node.hostname == saturn

x-minio-service: &minio-common
  image: minio/minio:RELEASE.2020-04-02T21-34-49Z
  networks:
    - traefik-net
  dns:
    - 1.1.1.1
    - 8.8.8.8
  logging:
    driver: json-file
    options:
      max-size: 50k
      max-file: 5
  environment:
    MINIO_ACCESS_KEY: [omitted]
    MINIO_SECRET_KEY: [omitted]
    MINIO_STORAGE_CLASS_STANDARD: EC:6 # Default is N/2
    MINIO_STORAGE_CLASS_RRS: EC:5
  command: >
    server --compat
    http://minio0/export0 http://minio0/export1
    http://minio1/export0 http://minio1/export1
    http://minio2/export0 http://minio2/export1
    http://minio3/export0 http://minio3/export1
    http://minio4/export0 http://minio4/export1
    http://minio5/export0 http://minio5/export1

services:
  minio0:
    <<: *minio-common
    deploy: *venus-deploy
    hostname: minio0
    ports:
      - target: 9000
        published: 9001
        mode: host
    volumes:
      - "/minio/disk0/export:/export0"
      - "/minio/disk1/export:/export1"

  minio1:
    <<: *minio-common
    deploy: *venus-deploy
    hostname: minio1
    ports:
      - target: 9000
        published: 9002
        mode: host
    volumes:
      - "/minio/disk2/export:/export0"
      - "/minio/disk3/export:/export1"

  minio2:
    <<: *minio-common
    deploy: *saturn-deploy
    hostname: minio2
    ports:
      - target: 9000
        published: 9003
        mode: host
    volumes:
      - "/minio/disk0/export:/export0"
      - "/minio/disk1/export:/export1"

  # Mars deployments
  minio3:
    <<: *minio-common
    deploy: *mars-deploy
    hostname: minio3
    ports:
      - target: 9000
        published: 9004
        mode: host
    volumes:
      - "/minio/disk0/export:/export0"
      - "/minio/disk1/export:/export1"

  minio4:
    <<: *minio-common
    deploy: *mars-deploy
    hostname: minio4
    ports:
      - target: 9000
        published: 9005
        mode: host
    volumes:
      - "/minio/disk2/export:/export0"
      - "/minio/disk3/export:/export1"

  minio5:
    <<: *minio-common
    deploy: *saturn-deploy
    hostname: minio5
    ports:
      - target: 9000
        published: 9006
        mode: host
    volumes:
      - "/minio/disk2/export:/export0"
      - "/minio/disk3/export:/export1"

networks:
  traefik-net:
    external: true
```
* Server type and version:
Using docker swarm: `Docker version 18.09.8, build 0dd43dd87f`
* Operating System and version (`uname -a`):
`Linux mars 4.15.0-76-generic #86-Ubuntu SMP Fri Jan 17 17:24:28 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux`

### PR DESCRIPTION
**Pull request by harshavardhana**
## Description
fix: remove the sleep from listing operations

## Motivation and Context
make rest of the Walk() function more predictable,
it was observed that in nominal deployments even
without much workload, the drives are generally
slow for respond for readdir operations, for the
sleepDuration factor of 10 this can cause
unexpected slowness in the Listing calls, while
it is good for all other I/O, it may simply slow
down Listing immensely which is not useful.

fixes #9261

## How to test this PR?
Test when an active I/O is in progress and try to List() this can be slow.

## Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [x] Fixes a regression yes most probably introduced in cfc9cfd84a0064ad9a7bb7eefe4d0415a783e209 and borrowed into 45b1c66195e806c62a4497672614061b8cc11d4b
- [ ] Documentation needed
- [ ] Unit tests needed
- [ ] Functional tests needed (If yes, add [mint](https://github.com/minio/mint) PR # here: )

### CODE REVIEW

**Comment by minio-trusted** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-xl.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-worm.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-dist-xl.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-gateway-azure.sh | :x: [more...](#c4a86b9f-e8a3-4d73-94d7-504ad3ba0579) |
<a name="c4a86b9f-e8a3-4d73-94d7-504ad3ba0579"></a>
### 9287-caa01cd/mint-gateway-azure.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-dev4.minio.io:31205
ACCESS_KEY:           minioazure
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 00c5bc36cd63:/mint/log /tmp/mint-logs'

(1/15) Running aws-sdk-go tests ... done in 7 seconds
(2/15) Running aws-sdk-java tests ... done in 2 seconds
(3/15) Running aws-sdk-php tests ... done in 8 minutes and 47 seconds
(4/15) Running aws-sdk-ruby tests ... done in 16 seconds
(5/15) Running awscli tests ... FAILED in 1 minutes and 59 seconds
{
  "name": "awscli",
  "duration": 1385,
  "function": "make_bucket\n",
  "status": "FAIL",
  "error": "An error occurred (BucketAlreadyOwnedByYou) when calling the CreateBucket operation: Your previous request to create the named bucket succeeded and you already own it."
}

Executed 4 out of 15 tests successfully.
```
Deleting image on docker hub
Deleting image locally

**Comment by minio-trusted** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-worm.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-xl.sh | :x: [more...](#a8729f8e-ac4e-4e07-aa53-47b413c8cb6a) |
| mint-large-bucket.sh | :x: [more...](#4706c16d-9b19-491c-8f00-7020da613a85) |
| mint-dist-xl.sh | :x: [more...](#275732fa-085d-45b7-9941-e30476b7b5df) |
| mint-gateway-azure.sh | :x: [more...](#55e6da5a-a721-4bb3-87d2-1e3f9efe0e2f) |
<a name="275732fa-085d-45b7-9941-e30476b7b5df"></a>
### 9287-c44146a/mint-dist-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-dev3.minio.io:31267
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 2e25c5d754ad:/mint/log /tmp/mint-logs'

(1/15) Running aws-sdk-go tests ... FAILED in 1 seconds
{
  "alert": "",
  "args": {
    "bucketName": "aws-sdk-go-test-qyqgu3lpfoip0c",
    "expiry": 60000000000,
    "objectName1": "testObject1",
    "objectName2": "testObject2"
  },
  "duration": 55,
  "error": "AWS S3 key count mismatch",
  "function": "testListObjects",
  "message": "AWS SDK Go listobjects with prefix '' expected 2 key but got 0, []",
  "name": "aws-sdk-go",
  "status": "FAIL"
}

Executed 0 out of 15 tests successfully.
```
<a name="a8729f8e-ac4e-4e07-aa53-47b413c8cb6a"></a>
### 9287-c44146a/mint-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-dev4.minio.io:31631
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp ec513697c032:/mint/log /tmp/mint-logs'

(1/15) Running aws-sdk-go tests ... FAILED in 0 seconds
{
  "alert": "",
  "args": {
    "bucketName": "aws-sdk-go-test-4flhnxxdlj6bt4",
    "expiry": 60000000000,
    "objectName1": "testObject1",
    "objectName2": "testObject2"
  },
  "duration": 35,
  "error": "AWS S3 key count mismatch",
  "function": "testListObjects",
  "message": "AWS SDK Go listobjects with prefix '' expected 2 key but got 0, []",
  "name": "aws-sdk-go",
  "status": "FAIL"
}

Executed 0 out of 15 tests successfully.
```
<a name="55e6da5a-a721-4bb3-87d2-1e3f9efe0e2f"></a>
### 9287-c44146a/mint-gateway-azure.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-dev6.minio.io:32718
ACCESS_KEY:           minioazure
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 69d188fe8c0e:/mint/log /tmp/mint-logs'

(1/15) Running aws-sdk-go tests ... done in 7 seconds
(2/15) Running aws-sdk-java tests ... done in 2 seconds
(3/15) Running aws-sdk-php tests ... done in 8 minutes and 59 seconds
(4/15) Running aws-sdk-ruby tests ... done in 16 seconds
(5/15) Running awscli tests ... FAILED in 6 seconds
{
  "name": "awscli",
  "duration": 1380,
  "function": "make_bucket\n",
  "status": "FAIL",
  "error": "An error occurred (BucketAlreadyOwnedByYou) when calling the CreateBucket operation: Your previous request to create the named bucket succeeded and you already own it."
}

Executed 4 out of 15 tests successfully.
```
<a name="4706c16d-9b19-491c-8f00-7020da613a85"></a>
### 9287-c44146a/mint-large-bucket.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-c3.minio.io:30630
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 48b9d37ac91b:/mint/log /tmp/mint-logs'

(1/15) Running aws-sdk-go tests ... FAILED in 0 seconds
{
  "alert": "",
  "args": {
    "bucketName": "aws-sdk-go-test-xnqbpfkkjgurbt",
    "expiry": 60000000000,
    "objectName1": "testObject1",
    "objectName2": "testObject2"
  },
  "duration": 172,
  "error": "AWS S3 key count mismatch",
  "function": "testListObjects",
  "message": "AWS SDK Go listobjects with prefix '' expected 2 key but got 0, []",
  "name": "aws-sdk-go",
  "status": "FAIL"
}

Executed 0 out of 15 tests successfully.
```
Deleting image on docker hub
Deleting image locally

File: cmd/posix.go [hunk 1]
```diff
@@ -838,14 +811,15 @@ func (s *posix) Walk(volume, dirPath, marker string, recursive bool, leafFile st
 					Mode:   os.ModeDir,
 				}
 			} else {
-				// Dynamic time delay.
-				t := UTCNow()
+				t := time.Now()
 				buf, err := s.ReadAll(volume, pathJoin(walkResult.entry, leafFile))
-				sleepDuration(time.Since(t), 10.0)
+				fmt.Println("ReadAll", time.Since(t))
```
Comment (klauspost) [inline cmd/posix.go]: Debug

File: cmd/posix.go [hunk 2]
```diff
@@ -838,14 +811,15 @@ func (s *posix) Walk(volume, dirPath, marker string, recursive bool, leafFile st
...
 				if err != nil {
 					continue
 				}
+				t = time.Now()
 				fi = readMetadataFn(buf, volume, walkResult.entry)
+				fmt.Println("readMetadataFn", time.Since(t))
```
Comment (klauspost) [inline cmd/posix.go]: Debug

File: cmd/posix.go [hunk 3]
```diff
@@ -809,17 +776,23 @@ func (s *posix) Walk(volume, dirPath, marker string, recursive bool, leafFile st
...
 			if len(entries) == 0 {
 				return true, nil
 			}
+			t = time.Now()
+			for i, entry := range entries {
+				if _, serr := os.Stat(pathJoin(dirPath, entry, leafFile)); serr == nil {
+					entries[i] = strings.TrimSuffix(entry, SlashSeparator)
+				}
+			}
+			fmt.Println("filterStat", time.Since(t))
```
Comment (klauspost) [inline cmd/posix.go]: Debug

File: cmd/posix.go [hunk 4]
```diff
@@ -809,17 +776,23 @@ func (s *posix) Walk(volume, dirPath, marker string, recursive bool, leafFile st
...
 		defer close(ch)
-		listDir := func(volume, dirPath, dirEntry string) (emptyDir bool, entries []string) {
-			// Dynamic time delay.
-			t := UTCNow()
-			entries, err := s.ListDir(volume, dirPath, -1, leafFile)
-			sleepDuration(time.Since(t), 10.0)
+		listDir := func(volume, dirPath, dirEntry string) (bool, []string) {
+			t := time.Now()
+			entries, err := readDir(pathJoin(volumeDir, dirPath))
+			fmt.Println("readDir", time.Since(t))
```
Comment (klauspost) [inline cmd/posix.go]: Debug

**Review by klauspost — COMMENTED** [review]
No big problems. Lots of debug statements and CI is failing hard as well, though.

**Comment by harshavardhana** [comment]
@klauspost yeah I haven't pushed the latest changes yet.

**Comment by minio-trusted** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-worm.sh | :heavy_check_mark: |
| mint-xl.sh | :x: [more...](#839c80ec-3e85-4a67-8351-86c030151142) |
| mint-large-bucket.sh | :x: [more...](#c55e3d83-6097-476c-88e7-74f14ff0ea37) |
| mint-fs.sh | :x: [more...](#e69f4da4-476f-49cb-88cb-de465d447e36) |
| mint-dist-xl.sh | :x: [more...](#e2c8af9e-b16a-49d8-a8d4-4399646b44f4) |
| mint-gateway-azure.sh | :x: [more...](#3dff7f47-e81c-4c4e-a73c-d62639741f86) |
| mint-gateway-nas.sh | :x: [more...](#67fbd38d-f57c-4aa8-8c52-7005434e5324) |
<a name="e2c8af9e-b16a-49d8-a8d4-4399646b44f4"></a>
### 9287-28681fe/mint-dist-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-dev4.minio.io:32343
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 53065c6b1e0c:/mint/log /tmp/mint-logs'

(1/15) Running aws-sdk-go tests ... done in 1 seconds
(2/15) Running aws-sdk-java tests ... done in 1 seconds
(3/15) Running aws-sdk-php tests ... done in 42 seconds
(4/15) Running aws-sdk-ruby tests ... done in 3 seconds
(5/15) Running awscli tests ... done in 2 minutes and 8 seconds
(6/15) Running healthcheck tests ... done in 0 seconds
(7/15) Running mc tests ... done in 43 seconds
(8/15) Running minio-dotnet tests ... done in 34 seconds
(9/15) Running minio-go tests ... done in 11 minutes and 17 seconds
(10/15) Running minio-java tests ... done in 1 minutes and 56 seconds
(11/15) Running minio-js tests ... done in 49 seconds
(12/15) Running minio-py tests ... done in 1 minutes and 39 seconds
(13/15) Running s3cmd tests ... done in 21 seconds
(14/15) Running s3select tests ... done in 2 seconds
(15/15) Running security tests ... done in 0 seconds

All tests ran successfully
```
<a name="67fbd38d-f57c-4aa8-8c52-7005434e5324"></a>
### 9287-28681fe/mint-gateway-nas.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-dev3.minio.io:32758
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp acd782d5315a:/mint/log /tmp/mint-logs'

(1/15) Running aws-sdk-go tests ... done in 0 seconds
(2/15) Running aws-sdk-java tests ... done in 1 seconds
(3/15) Running aws-sdk-php tests ... done in 41 seconds
(4/15) Running aws-sdk-ruby tests ... done in 2 seconds
(5/15) Running awscli tests ... done in 2 minutes and 3 seconds
(6/15) Running healthcheck tests ... done in 0 seconds
(7/15) Running mc tests ... done in 33 seconds
(8/15) Running minio-dotnet tests ... done in 27 seconds
(9/15) Running minio-go tests ... done in 9 minutes and 3 seconds
(10/15) Running minio-java tests ... done in 21 seconds
(11/15) Running minio-js tests ... done in 30 seconds
(12/15) Running minio-py tests ... done in 56 seconds
(13/15) Running s3cmd tests ... done in 15 seconds
(14/15) Running s3select tests ... done in 1 seconds
(15/15) Running security tests ... done in 0 seconds

All tests ran successfully
```
<a name="839c80ec-3e85-4a67-8351-86c030151142"></a>
### 9287-28681fe/mint-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-dev6.minio.io:32673
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 4489c36883e6:/mint/log /tmp/mint-logs'

(1/15) Running aws-sdk-go tests ... done in 0 seconds
(2/15) Running aws-sdk-java tests ... done in 1 seconds
(3/15) Running aws-sdk-php tests ... done in 42 seconds
(4/15) Running aws-sdk-ruby tests ... done in 2 seconds
(5/15) Running awscli tests ... done in 1 minutes and 9 seconds
(6/15) Running healthcheck tests ... done in 0 seconds
(7/15) Running mc tests ... done in 22 seconds
(8/15) Running minio-dotnet tests ... done in 28 seconds
(9/15) Running minio-go tests ... done in 12 minutes and 12 seconds
(10/15) Running minio-java tests ... done in 37 seconds
(11/15) Running minio-js tests ... done in 44 seconds
(12/15) Running minio-py tests ... done in 58 seconds
(13/15) Running s3cmd tests ... done in 20 seconds
(14/15) Running s3select tests ... done in 1 seconds
(15/15) Running security tests ... done in 0 seconds

All tests ran successfully
```
<a name="3dff7f47-e81c-4c4e-a73c-d62639741f86"></a>
### 9287-28681fe/mint-gateway-azure.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-c3.minio.io:32451
ACCESS_KEY:           minioazure
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp c26d7235aaea:/mint/log /tmp/mint-logs'

(1/15) Running aws-sdk-go tests ... done in 8 seconds
(2/15) Running aws-sdk-java tests ... done in 1 seconds
(3/15) Running aws-sdk-php tests ... done in 9 minutes and 31 seconds
(4/15) Running aws-sdk-ruby tests ... done in 17 seconds
(5/15) Running awscli tests ... FAILED in 2 minutes and 23 seconds
{
  "name": "awscli",
  "duration": 1479,
  "function": "make_bucket\n",
  "status": "FAIL",
  "error": "An error occurred (BucketAlreadyOwnedByYou) when calling the CreateBucket operation: Your previous request to create the named bucket succeeded and you already own it."
}

Executed 4 out of 15 tests successfully.
```
<a name="e69f4da4-476f-49cb-88cb-de465d447e36"></a>
### 9287-28681fe/mint-fs.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-c4.minio.io:31691
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp e34296b9de49:/mint/log /tmp/mint-logs'

(1/15) Running aws-sdk-go tests ... done in 0 seconds
(2/15) Running aws-sdk-java tests ... done in 2 seconds
(3/15) Running aws-sdk-php tests ... done in 41 seconds
(4/15) Running aws-sdk-ruby tests ... done in 1 seconds
(5/15) Running awscli tests ... done in 2 minutes and 3 seconds
(6/15) Running healthcheck tests ... done in 0 seconds
(7/15) Running mc tests ... done in 26 seconds
(8/15) Running minio-dotnet tests ... done in 29 seconds
(9/15) Running minio-go tests ... done in 8 minutes and 35 seconds
(10/15) Running minio-java tests ... done in 21 seconds
(11/15) Running minio-js tests ... done in 41 seconds
(12/15) Running minio-py tests ... done in 53 seconds
(13/15) Running s3cmd tests ... done in 14 seconds
(14/15) Running s3select tests ... done in 1 seconds
(15/15) Running security tests ... done in 0 seconds

All tests ran successfully
```
<a name="c55e3d83-6097-476c-88e7-74f14ff0ea37"></a>
### 9287-28681fe/mint-large-bucket.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-c4.minio.io:31729
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 631dfe595d77:/mint/log /tmp/mint-logs'

(1/15) Running aws-sdk-go tests ... done in 35 seconds
(2/15) Running aws-sdk-java tests ... done in 1 seconds
(3/15) Running aws-sdk-php tests ... done in 46 seconds
(4/15) Running aws-sdk-ruby tests ... done in 7 seconds
(5/15) Running awscli tests ... done in 2 minutes and 21 seconds
(6/15) Running healthcheck tests ... done in 0 seconds
(7/15) Running mc tests ... done in 1 minutes and 31 seconds
(8/15) Running minio-dotnet tests ... done in 57 seconds
(9/15) Running minio-go tests ... done in 12 minutes and 30 seconds
(10/15) Running minio-java tests ... done in 6 minutes and 23 seconds
(11/15) Running minio-js tests ... done in 52 seconds
(12/15) Running minio-py tests ... done in 5 minutes and 31 seconds
(13/15) Running s3cmd tests ... done in 28 seconds
(14/15) Running s3select tests ... done in 6 seconds
(15/15) Running security tests ... done in 0 seconds

All tests ran successfully
```
Deleting image on docker hub
Deleting image locally

**Review by kannappanr — APPROVED** [review]
LGTM

**Comment by minio-trusted** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-xl.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-worm.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-dist-xl.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-gateway-azure.sh | :x: [more...](#798c80dc-bba5-4cab-b220-91b8f9c235fe) |
<a name="798c80dc-bba5-4cab-b220-91b8f9c235fe"></a>
### 9287-008e437/mint-gateway-azure.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-dev4.minio.io:31901
ACCESS_KEY:           minioazure
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp c28bcdbecb60:/mint/log /tmp/mint-logs'

(1/15) Running aws-sdk-go tests ... done in 8 seconds
(2/15) Running aws-sdk-java tests ... done in 1 seconds
(3/15) Running aws-sdk-php tests ... done in 9 minutes and 42 seconds
(4/15) Running aws-sdk-ruby tests ... done in 17 seconds
(5/15) Running awscli tests ... FAILED in 6 seconds
{
  "name": "awscli",
  "duration": 1397,
  "function": "make_bucket\n",
  "status": "FAIL",
  "error": "An error occurred (BucketAlreadyOwnedByYou) when calling the CreateBucket operation: Your previous request to create the named bucket succeeded and you already own it."
}

Executed 4 out of 15 tests successfully.
```
Deleting image on docker hub
Deleting image locally

**Review by krishnasrinivas — APPROVED** [review]
