### PR TITLE
posix: ReadAll should handle the case when parent is not a dir.

### LINKED ISSUE #2047: XL: regression ListObjects should return NoSuchKey instead returns InternalError.
```
$ mc ls --debug myminio/testbucket/98/
mc: <DEBUG> GET /testbucket/?delimiter=%2F&max-keys=1000&prefix=98%2F HTTP/1.1
Host: 127.0.0.1:50000
User-Agent: Minio (linux; amd64) minio-go/1.0.1 mc/DEVELOPMENT.GOGET
Authorization: AWS4-HMAC-SHA256 Credential=**REDACTED**/20160701/us-east-1/s3/aws4_request, SignedHeaders=expect;host;x-amz-content-sha256;x-amz-date, Signature=**REDACTED**
Expect: 100-continue
X-Amz-Content-Sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
X-Amz-Date: 20160701T010237Z
Accept-Encoding: gzip

mc: <DEBUG> HTTP/1.1 500 Internal Server Error
Transfer-Encoding: chunked
Accept-Ranges: bytes
Content-Type: text/xml; charset=utf-8
Date: Fri, 01 Jul 2016 01:02:37 GMT
Server: Minio/DEVELOPMENT.GOGET (linux; amd64)
Vary: Origin
X-Amz-Request-Id: 6UNCYHWPTXPRWLNN

10d
<?xml version="1.0" encoding="UTF-8"?>
<Error><Code>InternalError</Code><Message>We encountered an internal error, please try again.</Message><Key></Key><BucketName></BucketName><Resource>/testbucket/</Resource><RequestId>3L137</RequestId><HostId>3L137</HostId></Error>
0

mc: <DEBUG> Response Time:  2.20383ms
```

### PR DESCRIPTION
**Pull request by harshavardhana**
It can happen so that a read request can come for a file which
already has a parent i.e a file.

This fix handles this scenario - fixes #2047

### CODE REVIEW

File: posix.go [hunk 1]
```diff
@@ -424,11 +424,16 @@ func (s *posix) ReadAll(volume, path string) (buf []byte, err error) {
...
 			return nil, errFileAccessDenied
 		} else if pathErr, ok := err.(*os.PathError); ok {
-			if pathErr.Err == syscall.EISDIR {
-				return nil, errFileNotFound
-			} else if strings.Contains(pathErr.Err.Error(), "The handle is invalid") {
-				// This case is special and needs to be handled for windows.
+			switch pathErr.Err {
+			case syscall.ENOTDIR:
+				fallthrough
+			case syscall.EISDIR:
```
Comment (balamurugana) [inline posix.go]: We could also use like `case syscall.ENOTDIR, syscall.EISDIR:`

**Comment by balamurugana** [comment]
:+1:  LGTM

**Comment by harshavardhana** [comment]
> We could also use like case syscall.ENOTDIR, syscall.EISDIR:

Ooops yeah, my mistake.
