### PR TITLE
Gateway should honour --address flag while checking port availability

### LINKED ISSUE #6426: Gateway fails to start on any port when 9000 (globalMinioPort) is already in use
## Expected Behavior
- start a minio server on port 9000
  - `minio server /tmp`
- afterwards start a minio gateway on a different port, e.g. 9001
  - `minio gateway b2 --address :9001`
- both minio instances should start and not have an "address in use" conflict

## Current Behavior
- the gateway does not start, because it complains of port 9000 being used, even if started with `--address :9001` or any different port
- starting the gateway first on the alternative port and then starting the server on 9000 works

## Possible Solution
Looking at the code, [gateway-main.go#L143](https://github.com/minio/minio/blob/fd1b8491dbe541d780197064e945c451ad733b73/cmd/gateway-main.go#L143) looks wrong to me because it always checks the default `globalMinioPort` instead of the address specified as an argument?

## Steps to Reproduce (for bugs)
See above. Assume that `MINIO_ACCESS_KEY` and `MINIO_SECRET_KEY` are defined in the environment.

## Context
I'm trying to write a generic systemd service `minio@.service` which uses `.conf` files as EnvironmentFiles, so I can start multiple minio services on different ports quickly.

## Regression
I don't know?

## Your Environment
Tried on Debian 9 with the latest release `2018-09-01T00:38:25Z` and various compilations from source.

### PR DESCRIPTION
**Pull request by krisis**
Fixes #6426 
## Description

Extracts port from `--address` flag value for checking port availability.

## Motivation and Context

See #6426 

## Regression

Yes. PR #6303 

## How Has This Been Tested?

Manually

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added unit tests to cover my changes.
- [ ] I have added/updated functional tests in [mint](https://github.com/minio/mint). (If yes, add `mint` PR # here: )
- [ ] All new and existing tests passed.

### CODE REVIEW

File: cmd/gateway-main.go [hunk 1]
```diff
@@ -136,11 +137,17 @@ func StartGateway(ctx *cli.Context, gw Gateway) {
 	// Handle common env vars.
 	handleCommonEnvVars()
 
+	// Get port to listen on from gateway address
+	_, gatewayPort, pErr := net.SplitHostPort(gatewayAddr)
```
Comment (krisis) [inline cmd/gateway-main.go:141]: I chose to use `net.SplitHostPort` over `mustSplitHostPort` because the former allows me to add context (i.e 'Unable to start gateway') to the error message displayed to the user.

## Using `net.SplitHostPort`
```
ERROR Unable to start gateway: address 9001: missing port in address.
```
## Using `mustSplitHostPort`
```
ERROR Unable to split host port 9001: address 9001: missing port in address.
```

**Review by nitisht — APPROVED** [review]
LGTM

**Review by poornas — APPROVED** [review]
Tested, LGTM.
