### PR TITLE
fs: Remove fs meta lock when PutObject() fails

### LINKED ISSUE #4090: When put file to minio server, some reason put have been cancelled, minio not delete extra fs.json in .minio.sys/buckets directory
When I put file by s3cmd， then I cancelled， this log info has appeared。

[root@node2 s3cmd]# ./s3cmd put 1G.txt s3://test/1G_2.txt --disable-multipart
WARNING: Module python-magic is not available. Guessing MIME types based on file extensions.
upload: '1G.txt' -> 's3://test/**1G_2.txt**'  [1 of 1]
  726007808 of 1073741824    67% in   77s     8.88 MB/s^CSee ya!
[root@node2 s3cmd]# 

ERRO[0289] Failed to create object test/**1G_2.txt**         cause=unexpected EOF source=[fs-v1.go:566:fsObjects.PutObject()] stack=fs-v1-helpers.go:267:fsCreateFile fs-v1.go:563:fsObjects.PutObject <autogenerated>:298:(*fsObjects).PutObject object-handlers.go:480:objectAPIHandlers.PutObjectHandler api-router.go:60:(objectAPIHandlers).PutObjectHandler-fm
ERRO[0289] Unable to create an object. /test/**1G_2.txt**    cause=#has incomplete body source=[object-handlers.go:483:objectAPIHandlers.PutObjectHandler()] stack=fs-v1-helpers.go:267:fsCreateFile fs-v1.go:563:fsObjects.PutObject <autogenerated>:298:(*fsObjects).PutObject object-handlers.go:480:objectAPIHandlers.PutObjectHandler api-router.go:60:(objectAPIHandlers).PutObjectHandler-fm

In this test, minio will delete tmp file for 1G_2.txt, but the buckets not delete **1G_2.txt**.
[root@node1 test]# pwd
/home/minio/test/.minio.sys/buckets/test
[root@node1 test]# ls -l
total 0
drwxr-xr-x 2 root root 20 Apr 11 14:10 **1G_2.txt**
drwxr-xr-x 2 root root 20 Apr 11 14:17 1G_3.txt
drwxr-xr-x 2 root root 20 Apr 11 09:46 1G.txt
[root@node1 test]# ls 1G_2.txt/fs.json -l
-rw-r--r-- 1 root root 329 Apr 11 15:18 **1G_2.txt/fs.json**
[root@node1 test]#

### PR DESCRIPTION
**Pull request by vadmeste**
## Description
Removing the fs meta lock file when PutObject() encounters any error
during its execution, such as upload getting permatuerly cancelled
by the client.

## Motivation and Context
Fixes #4090 

## How Has This Been Tested?
go test + Manually

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

File: cmd/fs-v1.go [hunk 1]
```diff
@@ -517,13 +518,29 @@ func (fs fsObjects) PutObject(bucket string, object string, size int64, data io.
...
+		fsMetaPath := pathJoin(bucketMetaDir, bucket, object, fsMetaJSONFile)
 		wlk, err = fs.rwPool.Create(fsMetaPath)
 		if err != nil {
 			return ObjectInfo{}, toObjectErr(traceError(err), bucket, object)
 		}
 		// This close will allow for locks to be synchronized on `fs.json`.
 		defer wlk.Close()
+		defer func() {
+			// Remove meta file when PutObject encounters any error
+			if err != nil {
```
Comment (harshavardhana) [inline cmd/fs-v1.go]: Create a new function as `fsRemoveMeta()`  can be tested independently.

**Review by harshavardhana — CHANGES_REQUESTED** [review]

File: cmd/fs-v1-helpers_test.go [hunk 2]
```diff
@@ -396,3 +400,47 @@ func TestFSRemoves(t *testing.T) {
...
+	if _, err = fsCreateFile(filePath, reader, buf, reader.Size()); err != nil {
+		t.Fatalf("Unable to create file, %s", err)
+	}
+
+	rwPool := &fsIOPool{
+		readersMap: make(map[string]*lock.RLockedFile),
+	}
+
+	if _, err := rwPool.Open(filePath); err != nil {
+		t.Fatalf("Unable to lock file %s\n", filePath)
```
Comment (harshavardhana) [inline cmd/fs-v1-helpers_test.go]: No need for `\n`

File: cmd/fs-v1-helpers_test.go [hunk 3]
```diff
@@ -396,3 +400,47 @@ func TestFSRemoves(t *testing.T) {
...
+	}
+
+	defer rwPool.Close(filePath)
+
+	if err := fsRemoveMeta(fsPath, filePath, "/tmp/"); err != nil {
+		t.Fatalf("Unable to remove file, %s", err)
+	}
+
+	if _, err := os.Stat(filePath); !os.IsNotExist(err) {
+		t.Fatal("`%s` file found though it should have been deleted.", filePath)
```
Comment (harshavardhana) [inline cmd/fs-v1-helpers_test.go]: t.Fatalf

**Review by harshavardhana — CHANGES_REQUESTED** [review]

**Review by harshavardhana — APPROVED** [review]

**Comment by deekoder** [comment]
ping @krisis

File: cmd/fs-v1.go (hunk 1 above)
Comment (krisis) [reply cmd/fs-v1.go]: Pass `err` as argument to the anonymous function being deferred to make the value of `err` used inside the function predictable.

**Comment by krisis** [comment]
@vadmeste, besides the one comment rest of the change look good to me

File: cmd/fs-v1.go (hunk 1 above)
Comment (harshavardhana) [reply cmd/fs-v1.go]: Alternatively keep the err in defer to be of different to avoid this .  Would be easier.?

Comment (vadmeste) [reply cmd/fs-v1.go]: > Pass err as argument to the anonymous function being deferred to make the value of err used inside the function predictable.

`err` here is not initialized inside the function, it is the returned error value, it looks easier to read this way.

Comment (krisis) [reply cmd/fs-v1.go]: @vadmeste, I agree that `err` is not initialized inside the function. The value of `err` used inside the anonymous function is deferred to time of calling. This allows for programming errors like shadowing to cause unexpected value of `err ` to be bound inside the anonymous function. The code in its current form is fine. I am only cautioning of the kind of bugs that could creep in. These situations can be avoided by having conventions similar to avoiding shadowing of variables. This comment is meant in that spirit.

Comment (vadmeste) [reply cmd/fs-v1.go]: I updated the PR, yeah it is much better.

**Review by krisis — APPROVED** [review]
