### PR TITLE
Should take care of the situation if an object already exists at the location.

### LINKED ISSUE #1598: mc cp should fail if prefix already exists as a file (13th)
```
azureuser@minio-test:~$ mc cp /etc/passwd myminio/test1/0bytefile
/etc/passwd:                        1.62 KB / 1.62 KB ┃▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓┃ 100.00 % 195.11 KB0
```

Now this should fail:

```
azureuser@minio-test:~$ mc cp /etc/passwd myminio/test1/0bytefile/passwd
/etc/passwd:                        1.62 KB / 1.62 KB ┃▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓┃ 100.00 % 156.07 KB0azureuser@minio-test:~$ 
```

### PR DESCRIPTION
**Pull request by krishnasrinivas**
Fixes #1598 #1594 #1595

### CODE REVIEW

File: xl-objects.go [hunk 1]
```diff
@@ -212,6 +215,25 @@ func getMultipartObjectInfo(storage StorageAPI, bucket, object string) (info Mul
 	return info, nil
 }
 
+// Returns FileInfo - accounts for both single-put and multipart files.
+func (xl xlObjects) statFile(bucket, object string) (FileInfo, error) {
```
Comment (harshavardhana) [inline xl-objects.go]: We shouldn't have functions like this at Object level, we should wrap them as -`getObjectInfo()` and return a proper wrapped result.

File: fs-objects.go [hunk 2]
```diff
@@ -143,7 +145,73 @@ func (fs fsObjects) GetObjectInfo(bucket, object string) (ObjectInfo, error) {
...
+		return "", BucketNotFound{Bucket: bucket}
+	}
+	if !IsValidObjectName(object) {
+		return "", ObjectNameInvalid{
+			Bucket: bucket,
+			Object: object,
+		}
+	}
+
+	fileWriter, err := fs.storage.CreateFile(bucket, object)
```
Comment (harshavardhana) [inline fs-objects.go:163]: This is incorrect, even FS fs-objects is supposed to use temporary location and rename.  Otherwise there is no cleaner mechanism to clean temporary files on FS which would lie dormant into the future. 

That was the whole reason why we use `tmp` even for FS, so you have to  converge this back and for XL do what is necessary additionally in its own implementation.

File: xl-objects.go [hunk 3]
```diff
@@ -314,16 +405,35 @@ func (xl xlObjects) DeleteObject(bucket, object string) error {
...
+	for _, err := range errs {
 		if err != nil {
-			partFileName := partNumToPartFileName(info.Parts[index].PartNumber)
-			return toObjectErr(err, bucket, pathJoin(object, partFileName))
+			return errUnexpected
 		}
 	}
 	err = xl.storage.DeleteFile(bucket, pathJoin(object, multipartMetaFile))
 	if err != nil {
+		return err
```
Comment (harshavardhana) [inline xl-objects.go:432]: toObjectErr() is missing.

File: xl-erasure-v1.go [hunk 4]
```diff
@@ -628,37 +628,17 @@ func (xl XL) RenameFile(srcVolume, srcPath, dstVolume, dstPath string) error {
...
-
-			return err
-		}
-		srcXLMetaPath := slashpath.Join(srcPath, xlMetaV1File)
-		dstXLMetaPath := slashpath.Join(dstPath, xlMetaV1File)
-		err = disk.RenameFile(srcVolume, srcXLMetaPath, dstVolume, dstXLMetaPath)
+	for _, disk := range xl.storageDisks {
+		// Append "/" as srcPath and dstPath are either leaf-dirs or non-leaf-dris.
+		// If srcPath is an object instead of prefix we just rename the leaf-dir and
+		// not rename the part and metadata files separately.
```
Comment (harshavardhana) [inline xl-erasure-v1.go:634]: You should put a go-routine here with waitgroup.

File: fs-objects.go (hunk 2 above)
Comment (krishnasrinivas) [inline fs-objects.go:163]: PutObject diverged because of the following requirement in XL:

```
+   // check if an object is present as one of the parent dir.
 +  if err = xl.parentDirIsObject(bucket, path.Dir(object)); err != nil {
 +      return "", toObjectErr(err, bucket, object)
 +  }
 +
 +  // Delete if an object already exists.
 +  // FIXME: rename it to tmp file and delete only after
 +  // the newly uploaded file is renamed from tmp location to
 +  // the original location.
 +  err = xl.deleteObject(bucket, object)
 +  if err != nil && err != errFileNotFound {
 +      return "", toObjectErr(err, bucket, object)
 +  }
```

Comment (krishnasrinivas) [inline fs-objects.go:163]: > This is incorrect, even FS fs-objects is supposed to use temporary location and rename. Otherwise there is no cleaner mechanism to clean temporary files on FS which would lie dormant into the future.

but why would id lie dormant? we are cleaning it with Close() or safeCloseAndRemove() no? You mean if the machine goes down?

**Comment by harshavardhana** [comment]
> This is incorrect, even FS fs-objects is supposed to use temporary location and rename. Otherwise there is no cleaner mechanism to clean temporary files on FS which would lie dormant into the future.
> but why would id lie dormant? we are cleaning it with Close() or safeCloseAndRemove() no? You mean if the machine goes down?

There are always cases where it can happen and we don't know what to do in that scenario, it is better to rename and then purge.

File: xl-objects.go (hunk 3 above)
Comment (krishnasrinivas) [inline xl-objects.go:432]: this returns `err` the caller DeleteObject() does toObjectErr()

File: fs-objects.go (hunk 2 above)
Comment (krishnasrinivas) [inline fs-objects.go]: As discussed on phone having it in `tmp` and then renaming will have race condition, we have to bring in a fix where object in tmp is created as this path `.minio/tmp/UUID/path/to/object` but i will make the change to write it to `tmp` for now

but the separation was not driven by this but more because we have to do this for XL:

```
+	// check if an object is present as one of the parent dir.
 +	if err = xl.parentDirIsObject(bucket, path.Dir(object)); err != nil {
 +		return "", toObjectErr(err, bucket, object)
 +	}
```

Comment (harshavardhana) [inline fs-objects.go:163]: > but the separation was not driven by this but more because we have to do this for XL:

But still much of the codebase is still same, even till io.Copy and Md5sum validation.  Don't see any good reason to keep duplicates.  If its not clean then this approach is fine.

File: xl-objects.go (hunk 3 above)
Comment (krishnasrinivas) [inline xl-objects.go:432]: this is the deleteObject function, not DeleteObject. DeleteObject() returns toObjectErr()
