### PR TITLE
fs: Migrate object metadata to objects directory.

### LINKED ISSUE #3352: backend: Namespace conflict with policy.json and actual object called policy.json
`mc policy both myminio/test` fails, refer to steps-to-repro for details.

## Expected Behavior
`mc policy both myminio/test` should work

## Steps to Reproduce (for bugs)
```
krishna@escape:~$ mc mb myminio/test
Bucket created successfully ‘myminio/test’.
krishna@escape:~$ mc cp /etc/passwd myminio/test/policy.json
/etc/passwd:    2.20 KB / 2.20 KB ┃▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓┃ 100.00% 340.99 KB/s 0skrishna@escape:~$ mc policy both myminio/test
mc: <ERROR> Unable to set policy ‘both’ for ‘myminio/test’. 500 Internal Server Error
krishna@escape:~$ 
```

minio server logs:
```
ERRO[0018] Unable to set policy for the bucket test      cause=rename /home/krishna/export/.minio.sys/tmp/474f105d-7067-4e18-9de5-dd35caf250ac /home/krishna/export/.minio.sys/buckets/test/policy.json: is a directory source=[bucket-policy.go:211:writeBucketPolicy()] stack=fs-v1.go:460:fsObjects.PutObject <autogenerated>:195:(*fsObjects).PutObject bucket-policy.go:210:writeBucketPolicy bucket-policy-handlers.go:218:persistAndNotifyBucketPolicyChange bucket-policy-handlers.go:185:objectAPIHandlers.PutBucketPolicyHandler api-router.go:79:(objectAPIHandlers).PutBucketPolicyHandler-fm

```

### PR DESCRIPTION
**Pull request by harshavardhana**
## Description
Migrate object metadata to objects directory.

## Motivation and Context
Fixes #3352

## How Has This Been Tested?
Manually.

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by harshavardhana** [comment]
Will be adding tests. But ready for review.

**Comment by harshavardhana** [comment]
There is a windows issue i am still debugging.. rest of the code can be reviewed @vadmeste @krishnasrinivas

File: cmd/fs-v1.go [hunk 1]
```diff
@@ -72,15 +72,83 @@ func initMetaVolumeFS(fsPath, fsUUID string) error {
...
+// Attempts to migrate old object metadata files to newer format
+//
+// i.e
+//    -------------------------------------------------------
+//    .minio.sys/buckets/<bucket_name>/<object_path>/fs.json
+//    -------------------------------------------------------
+//    .minio.sys/buckets/<bucket_name>/objects/<object_path>/fs.json
+//    -------------------------------------------------------
+//
+func migrateFSObjectMetadataDir(fsPath, fsUUID string) error {
```
Comment (vadmeste) [inline cmd/fs-v1.go]: I can imagine that if a user has too many objects, he will press control-c in the middle of upgrade and it will be a problem. A better approach (unfortunately it also has its drawbacks) is to copy fs.json and not rename them. Once everything is finished, we upgrade fs format to v2.

File: cmd/fs-v1.go [hunk 2]
```diff
@@ -110,17 +178,25 @@ func newFSObjectLayer(fsPath string) (ObjectLayer, error) {
...
 	}
 
 	// If the `format.json` doesn't exist create one.
-	if err == errUnformattedDisk {
+	if err == errUnformattedDisk || err == errFSFormatOld {
 		fsFormatPath := pathJoin(fsPath, minioMetaBucket, fsFormatJSONFile)
+
 		// Initialize format.json, if already exists overwrite it.
-		if serr := saveFormatFS(fsFormatPath, newFSFormatV1()); serr != nil {
+		if serr := saveFormatFS(fsFormatPath, newFSFormatV2()); serr != nil {
```
Comment (vadmeste) [inline cmd/fs-v1.go]: saveFormatFS() should be called after migrateFSObjectMetadataDir() and when this latter is successful.

Comment (harshavardhana) [reply cmd/fs-v1.go]: The reason to do that is if migrate fails we don't need to attempt again.

Comment (harshavardhana) [reply cmd/fs-v1.go]: We can then help the user manually .. migrate

File: cmd/fs-v1.go (hunk 1 above)
Comment (harshavardhana) [reply cmd/fs-v1.go]: Yes we can even block control-c but .. I think it would make sense to print a message . That would make it easier.

Comment (harshavardhana) [reply cmd/fs-v1.go]: Copying each fs.json can take ages. We don't need to do that. Renames are atomic in nature so either it's do or die.. if we print a message about migration then all of this works out nicely.

File: cmd/fs-v1.go (hunk 2 above)
Comment (harshavardhana) [reply cmd/fs-v1.go]: I know it is cleaner to do later. But that was the only reason as I stated above.

File: cmd/fs-v1.go (hunk 1 above)
Comment (vadmeste) [reply cmd/fs-v1.go]: > Copying each fs.json can take ages.

Yeah, that's the drawback.

**Comment by harshavardhana** [comment]
Also brought in locking to avoid multiple migrations running simultaneously in shared backend mode.

**Comment by harshavardhana** [comment]
Windows build has been fixed as well.  Can I get more reviews ?

File: cmd/fs-v1.go [hunk 3]
```diff
@@ -72,15 +72,131 @@ func initMetaVolumeFS(fsPath, fsUUID string) error {
 
 }
 
+// List all buckets at meta bucket prefix in `.minio.sys/buckets/` path.
+func readDirBuckets(metaBucket string) ([]string, error) {
```
Comment (vadmeste) [inline cmd/fs-v1.go]: I think you can move this function to fs-v1-helpers.go, this function is already generic.

File: cmd/fs-v1.go [hunk 4]
```diff
@@ -110,17 +226,25 @@ func newFSObjectLayer(fsPath string) (ObjectLayer, error) {
...
+	if err != nil && err != errUnformattedDisk && err != errFSFormatOld {
 		return nil, fmt.Errorf("Unable to load 'format.json', %s", err)
 	}
 
 	// If the `format.json` doesn't exist create one.
-	if err == errUnformattedDisk {
+	if err == errUnformattedDisk || err == errFSFormatOld {
+		// Disk is in old format migrate object metadata.
+		if err == errFSFormatOld {
+			if merr := migrateFSObjectMetadataDir(fsPath, fsUUID); merr != nil {
```
Comment (vadmeste) [inline cmd/fs-v1.go]: Can we do migrate with the following style?
```
migrateFSObject()
|___ migrateFSObjectV1toV2()
```

That way we will always remember users that have real old installation.

File: cmd/fs-v1-metadata.go [hunk 5]
```diff
@@ -269,6 +284,12 @@ func loadFormatFS(fsPath string) (*formatConfigV1, error) {
 		return nil, err
 	}
 
+	// Check if format is V2.
+	if !isFSFormatV2(format) {
```
Comment (vadmeste) [inline cmd/fs-v1-metadata.go]: I think it is important if we return two errors when we check for FS format version:
- Old version so we can migrate
- Newer unsupported version (like, 3, 4, ..), so we stop here since things start to be unpredictable.

File: cmd/fs-v1.go [hunk 6]
```diff
@@ -72,15 +72,131 @@ func initMetaVolumeFS(fsPath, fsUUID string) error {
...
+//    .minio.sys/buckets/<bucket_name>/objects/<object_path>/fs.json
+//    -------------------------------------------------------
+//
+func migrateFSObjectMetadataDir(fsPath, fsUUID string) (err error) {
+	metaBucket := pathJoin(fsPath, minioMetaBucket, bucketConfigPrefix)
+	migratePlaceHolder := "." + fsUUID
+
+	// Locked for writing ".migrate" file under the buckets folder.
+	var lk *lock.LockedFile
+	lk, err = lock.LockedOpenFile(preparePath(pathJoin(metaBucket, migratePlaceHolder)), os.O_CREATE|os.O_WRONLY, 0600)
```
Comment (vadmeste) [inline cmd/fs-v1.go]: This line can fail if `.minio.sys/buckets` doesn't exist yet. In that case, user can't migrate to format V2

Comment (harshavardhana) [reply cmd/fs-v1.go]: This line already fails.. @vadmeste

File: cmd/fs-v1-metadata.go (hunk 5 above)
Comment (harshavardhana) [reply cmd/fs-v1-metadata.go]: Good idea.

File: cmd/fs-v1.go (hunk 3 above)
Comment (harshavardhana) [reply cmd/fs-v1.go]: Sure

File: cmd/fs-v1.go (hunk 4 above)
Comment (harshavardhana) [reply cmd/fs-v1.go]: Good idea.

**Comment by harshavardhana** [comment]
Changes have been done @vadmeste @krishnasrinivas .. Can you review and test again?

File: cmd/fs-v1-metadata.go [hunk 7]
```diff
@@ -237,17 +238,45 @@ func newFSMetaV1() (fsMeta fsMetaV1) {
...
+func isFSValidFormat(formatCfg *formatConfigV1) bool {
+	if formatCfg == nil {
+		return false
+	}
+	if formatCfg.FS == nil {
+		return false
+	}
+
+	// Check for supported format versions.
+	for _, version := range supportedFormatVersions {
```
Comment (vadmeste) [inline cmd/fs-v1-metadata.go]: I think it is easier to check if the found version is <= 2 than doing this style

and 2 could be a global variable.

File: cmd/fs-v1.go [hunk 8]
```diff
@@ -72,15 +73,124 @@ func initMetaVolumeFS(fsPath, fsUUID string) error {
...
+	defer func() {
+		if err == nil {
+			log.Println("SUCCESS.")
+		} else {
+			log.Printf("FAILED with %s.\n", err)
+		}
+	}()
+
+	var buckets []string
+	buckets, err = fsReaddirBuckets(fsPath)
```
Comment (vadmeste) [inline cmd/fs-v1.go]: Shouldn't we check for buckets inside '.minio.sys/buckets', rather than fsPath ? otherwise we will fail later in `fsRenameFile(pathJoin(metaBucket, bucket), pathJoin(metaBucket, tmpBucket))`

File: cmd/fs-v1-metadata.go (hunk 7 above)
Comment (harshavardhana) [reply cmd/fs-v1-metadata.go]: The reason to do this is quite different.. it is to indicate if we are looking at the right versions supported by Minio.

File: cmd/fs-v1.go (hunk 8 above)
Comment (harshavardhana) [reply cmd/fs-v1.go]: We are constructing it internally @vadmeste

File: cmd/fs-v1-metadata.go (hunk 7 above)
Comment (harshavardhana) [reply cmd/fs-v1-metadata.go]: The lexical ordering is lost if we do `<=` it is safer to not do that and do direct comparison.

File: cmd/fs-v1.go (hunk 8 above)
Comment (vadmeste) [reply cmd/fs-v1.go]: > We are constructing it internally @vadmeste

You mean we are going to create all buckets inside .minio.sys/buckets?

Anyway, it will fail later as I said in fsRenameFile(), I just tested it. pathJoin(metaBucket, bucket) doesn't always exist and it returns an error at that stage.

File: cmd/fs-v1.go [hunk 9]
```diff
@@ -110,17 +219,25 @@ func newFSObjectLayer(fsPath string) (ObjectLayer, error) {
...
+	if err != nil && err != errUnformattedDisk && err != errFSFormatOld {
 		return nil, fmt.Errorf("Unable to load 'format.json', %s", err)
 	}
 
 	// If the `format.json` doesn't exist create one.
-	if err == errUnformattedDisk {
+	if err == errUnformattedDisk || err == errFSFormatOld {
+		// Disk is in old format migrate object metadata.
+		if err == errFSFormatOld {
+			if merr := migrateFSObject(fsPath, fsUUID); merr != nil {
```
Comment (krishnasrinivas) [inline cmd/fs-v1.go]: fsUUID is not shared with other minio processes, hence you could flock on format.json itself during the entire process

Comment (harshavardhana) [reply cmd/fs-v1.go]: Ah yes good catch, should have used that way.. instead.

Comment (harshavardhana) [reply cmd/fs-v1.go]: Fixed.

File: cmd/fs-v1-helpers.go [hunk 10]
```diff
@@ -424,3 +457,18 @@ func fsRemoveMeta(basePath, deletePath, tmpDir string) error {
 	}
 	return fsDeleteFile(basePath, deletePath)
 }
+
+// List all buckets at meta bucket prefix in `.minio.sys/buckets/` path.
+// This is implemented to avoid a bug on windows with using readDir().
+func fsReaddirBuckets(fsPath string) ([]string, error) {
```
Comment (krishnasrinivas) [inline cmd/fs-v1-helpers.go]: Note that this function gets used only for migration. Not during regular FS operations. fsReaddirBuckets reads `fsPath/.minio.sys/buckets` not `fsPath` hence fsReaddirMetaBuckets sounds more appropriate.

Also better move this closer to `migrateFSObject()`

File: cmd/fs-v1-metadata.go [hunk 11]
```diff
@@ -269,6 +309,17 @@ func loadFormatFS(fsPath string) (*formatConfigV1, error) {
...
 
+	// Check if format is currently supported.
+	if !isFSValidFormat(format) {
+		return nil, errCorruptedFormat
+	}
+
+	// Check for format version is current.
+	if format.FS.Version != fsFormatVersion {
+		return nil, errFSFormatOld
+	}
```
Comment (krishnasrinivas) [inline cmd/fs-v1-metadata.go]: Better do these checks version in the caller `loadFormatFS()` because as a code reader I expected loadFormatFS to just load it and not do validation of versions.

File: cmd/fs-v1.go [hunk 12]
```diff
@@ -72,15 +72,100 @@ func initMetaVolumeFS(fsPath, fsUUID string) error {
...
+	log.Println("PLEASE DO NOT STOP THE SERVER")
+	log.Printf("Migrating old bucket metadata format at \"%s\" \"1\" to newer format \"2\"... ", fsPath)
+
+	defer func() {
+		if err == nil {
+			log.Println("SUCCESS.")
+		} else {
+			log.Printf("FAILED with %s.\n", err)
+		}
+	}()
```
Comment (krishnasrinivas) [inline cmd/fs-v1.go]: Instead of doing this style, the more conventional style is better:
```
err = migrateFSObject()
if err {...}
else {...}
```

File: cmd/fs-v1.go [hunk 13]
```diff
@@ -110,17 +195,25 @@ func newFSObjectLayer(fsPath string) (ObjectLayer, error) {
...
+				return nil, merr
+			}
+		}
+
 		fsFormatPath := pathJoin(fsPath, minioMetaBucket, fsFormatJSONFile)
 		// Initialize format.json, if already exists overwrite it.
-		if serr := saveFormatFS(fsFormatPath, newFSFormatV1()); serr != nil {
+		if serr := saveFormatFS(fsFormatPath, newFSFormatV2()); serr != nil {
 			return nil, fmt.Errorf("Unable to initialize 'format.json', %s", serr)
 		}
```
Comment (krishnasrinivas) [inline cmd/fs-v1.go]: Lock should be held for the entire duration of load, migrate, save

File: cmd/fs-v1.go [hunk 14]
```diff
@@ -110,17 +195,25 @@ func newFSObjectLayer(fsPath string) (ObjectLayer, error) {
...
+		if err == errFSFormatOld {
+			if merr := migrateFSObject(fsPath, fsUUID); merr != nil {
+				return nil, merr
+			}
+		}
+
 		fsFormatPath := pathJoin(fsPath, minioMetaBucket, fsFormatJSONFile)
 		// Initialize format.json, if already exists overwrite it.
-		if serr := saveFormatFS(fsFormatPath, newFSFormatV1()); serr != nil {
+		if serr := saveFormatFS(fsFormatPath, newFSFormatV2()); serr != nil {
```
Comment (krishnasrinivas) [inline cmd/fs-v1.go]: saveFormatFS() is not truncating previous contents. We will end up with corrupt format.json if the current json's size is less than previous contents.

File: cmd/fs-v1-helpers.go (hunk 10 above)
Comment (harshavardhana) [reply cmd/fs-v1-helpers.go]: Sure it was there and moved to helpers..

File: cmd/fs-v1-metadata.go (hunk 11 above)
Comment (harshavardhana) [reply cmd/fs-v1-metadata.go]: Sure

File: cmd/fs-v1.go (hunk 14 above)
Comment (harshavardhana) [reply cmd/fs-v1.go]: Yes good thing..

File: cmd/fs-v1.go (hunk 13 above)
Comment (harshavardhana) [reply cmd/fs-v1.go]: Perfect..

**Comment by harshavardhana** [comment]
All changes requested done @krishnasrinivas

File: cmd/format-config-v1.go [hunk 15]
```diff
@@ -47,6 +51,43 @@ type formatConfigV1 struct {
...
+	_, err = lk.Write(fbytes)
+	if err != nil {
+		return 0, traceError(err)
+	}
+	return int64(len(fbytes)), nil
+}
+
+func (f *formatConfigV1) ReadFrom(lk *lock.LockedFile) (n int64, err error) {
+	var fbytes []byte
+	fi, err := lk.Stat()
```
Comment (vadmeste) [inline cmd/format-config-v1.go:73]: Why Stat() ? since we have ioutil.ReadAll later, is that to synchronize access to the file ?

Comment (harshavardhana) [reply cmd/format-config-v1.go:73]: We need to know the exact size to read.. there is a reason for it but i do not remember why.

**Comment by vadmeste** [comment]
I wasn't able to break this code. Probably one last thing is to disable signals as you suggested

```
          ch := make(chan os.Signal)
  
          signal.Notify(ch, syscall.SIGINT, syscall.SIGTERM)
  
          go func() {
                  for {
                          _, ok := <-ch
                          if !ok {
                                  break
                          }
                          log.Println("Please wait until the server finish upgrading..")
                  }
          }()
  
          // Working.. busy update
          time.Sleep(10 * time.Second)
          // Update finished.
  
          signal.Stop(ch)
          close(ch)
```

**Comment by harshavardhana** [comment]
> ch := make(chan os.Signal)
>   
>           signal.Notify(ch, syscall.SIGINT, syscall.SIGTERM)
>   
>           go func() {
>                   for {
>                           _, ok := <-ch
>                           if !ok {
>                                   break
>                           }
>                           log.Println("Please wait until the server finish upgrading..")
>                   }
>           }()
>   
>           // Working.. busy update
>           time.Sleep(10 * time.Second)
>           // Update finished.
>   
>           signal.Stop(ch)
>           close(ch)

We don't need to do that because the server exit with block on `globalServiceDoneCh` and wouldn't exit.

**Comment by vadmeste** [comment]
> We don't need to do that because the server exit with block on globalServiceDoneCh and wouldn't exit.

We are probably missing something, I've just tested with 10,000 buckets and ctrl-c stopped Minio before upgrading to format v2.

File: cmd/fs-v1-metadata.go [hunk 16]
```diff
@@ -237,58 +250,114 @@ func newFSMetaV1() (fsMeta fsMetaV1) {
...
+
+	// Disk is in old format migrate object metadata.
+	if err == errFSFormatOld {
+		if err = migrateFSObject(fsPath, fsUUID); err != nil {
+			return err
+		}
+		format = newFSFormatV2()
+	}
+
+	// Initialize format.json, if already exists overwrite it.
```
Comment (krishnasrinivas) [inline cmd/fs-v1-metadata.go]: we should overwrite only if we migrated from V1 to V2, else leave it as it is

**Comment by harshavardhana** [comment]
> We are probably missing something, I've just tested with 10,000 buckets and ctrl-c stopped Minio before upgrading to format v2.

Let me check.. it shouldn't happen from current code point of view.

File: cmd/fs-v1-metadata.go [hunk 17]
```diff
@@ -237,58 +250,117 @@ func newFSMetaV1() (fsMeta fsMetaV1) {
...
+		}
+
+		// Initialize format v2.
+		format = newFSFormatV2()
+
+		// Initialize format.json.
+		if _, err = format.WriteTo(lk); err != nil {
+			return fmt.Errorf("Unable to initialize 'format.json', %s", err)
+		}
+	}
```
Comment (krishnasrinivas) [inline cmd/fs-v1-metadata.go]: still a problem, because on a fresh export directory we are not writing format to disk, i.e we endup with empty file created at line 322

Comment (harshavardhana) [reply cmd/fs-v1-metadata.go]: Oops.. yes.

**Comment by harshavardhana** [comment]
Fixed and added CTRL-C catcher.. as well. @vadmeste @krishnasrinivas - let me know what else is needed.

**Comment by krishnasrinivas** [comment]
Another problem :-(

If older binary is started on version-2 format.json it runs without exiting.

**Comment by harshavardhana** [comment]
Nothing can be done for older binaries @krishnasrinivas.

**Review by krishnasrinivas — APPROVED** [review]

**Comment by harshavardhana** [comment]
@vadmeste we need to review this as well after the release..

**Comment by harshavardhana** [comment]
@vadmeste waiting on your :+1: .. let me know if you have more comments.

**Review by vadmeste — APPROVED** [review]

**Comment by vadmeste** [comment]
I tested again. LGTM.
