### PR TITLE
api: Sent ErrPreconditionFailed on If-Match failure

### LINKED ISSUE #1981: FS: GetObject wrong responses for If-Match and If-None-Match
## Expected behaviour

If-Match when given a bad ETag should give back 412 Precondition Failed XML error. Instead it is sending the object back.

If-None-Match when given a good ETag should give back 304 Not Modified and no object. Instead it is giving 200 OK and sending the object back. 
## Actual behaviour

If-Match is sending the object back.
If-None-Match is sending the object back.
## Steps to reproduce the behaviour

run the tests for GetObject on s3verify
## Minio version
- (paste output of `minio version`)

### PR DESCRIPTION
**Pull request by krisis**
ref: http://docs.aws.amazon.com/AmazonS3/latest/API/ErrorResponses.html#ErrorCodeList

Fixes #1981 (previous fix didn't add error response to response.Body on If-Match condition failure)

### CODE REVIEW

**Comment by harshavardhana** [comment]
Would you mind adding a test case? 

```
func (s *MyAPISuite) TestHeadOnObject(c *C) {
```

Already tests for If-Modified-Since.

File: server_xl_test.go [hunk 1]
```diff
@@ -841,6 +841,78 @@ func (s *MyAPIXLSuite) TestNotBeAbleToCreateObjectInNonexistentBucket(c *C) {
...
+	c.Assert(err, IsNil)
+	c.Assert(string(body), Equals, "hello world")
+
+	// GetObject with If-Match sending mismatching etag in request headers
+	// is expected to return an error response with ErrPreconditionFailed.
+	request, err = newTestRequest("GET", s.endPoint+"/"+bucketName+"/object1",
+		0, nil, s.accessKey, s.secretKey)
+	request.Header.Set("If-Match", etag[1:])
+	response, err = client.Do(request)
+	c.Assert(response.StatusCode, Equals, http.StatusPreconditionFailed)
```
Comment (harshavardhana) [inline server_xl_test.go]: you can use 'verifyError' wrapper here.
