### PR TITLE
Fix resync replication of delete markers 

### LINKED ISSUE #12919: DELETE markers not replicated during resync
With Two-Way Server-Side Bucket Replication setup replication works fine. Objects and DELETE markers are getting replicated correctly. We have network and hardware issues in the past as a result some objects reside only on one of the sites with COMPLETED status. To get them re-replicated we issued `mc replicate resync` on both sites at 22:00. Markers for objects deleted between 2200 and 0100 are missing on the other site. Markers for objects deleted before 2200 or after 0100 were replicated correctly.

## Expected Behavior

DELETE markers to be replicated normally

## Current Behavior

markers for deleted objects during resync are not replicated.

## Steps to Reproduce (for bugs)

1. configure Two-Way Server-Side Bucket Replication with `--replicate "delete,delete-marker,existing-objects"`
2. upload enough data to the bucket
3. run `mc replicate resync` on both clusters
4. delete some objects before during resync
5. check object status on both clusters after resync

## Your Environment

* Version used (`minio --version`):  Version: 2021-08-05T22:01:19Z
* Server setup and configuration: two baremetal clusters with 5 nodes each
* Operating System and version (`uname -a`): Linux tafl-serv1 5.4.0-74-generic 83-Ubuntu SMP Sat May 8 02:35:39 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

### PR DESCRIPTION
**Pull request by poornas**
## Description

Fixes #12919 

Additionally fixing a regression in GetObjectInfo where delete replication metadata update was not happening in multiple server pools situation, because pool index was not returned correctly. This would cause the version to remain on disk in pending purge status

## Motivation and Context
Needs https://github.com/minio/minio-go/pull/1531

## How to test this PR?
As described in issue

## Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Optimization (provides speedup with no functional changes)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [x] Fixes a regression (If yes, please add `commit-id` or `PR #` here)
- [ ] Documentation updated
- [ ] Unit tests added/updated

### CODE REVIEW

**Comment by minio-trusted** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-s3.sh | :heavy_check_mark: |
| mint-erasure.sh | :heavy_check_mark: |
| mint-dist-erasure.sh | :heavy_check_mark: |
| mint-zoned.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-compress-encrypt-dist-erasure.sh | :heavy_check_mark: |
Deleting image on docker hub
Deleting image locally

**Comment by minio-trusted** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-s3.sh | :heavy_check_mark: |
| mint-erasure.sh | :heavy_check_mark: |
| mint-dist-erasure.sh | :heavy_check_mark: |
| mint-zoned.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-compress-encrypt-dist-erasure.sh | :heavy_check_mark: |
Deleting image on docker hub
Deleting image locally

File: cmd/data-scanner.go [hunk 1]
```diff
@@ -1173,7 +1173,7 @@ func (i *scannerItem) healReplication(ctx context.Context, o ObjectLayer, oi Obj
 			return
 		}
 		// if replication status is Complete on DeleteMarker and existing object resync required
-		if existingObjResync && oi.ReplicationStatus == replication.Completed {
+		if existingObjResync && (oi.ReplicationStatus == replication.Completed || oi.ReplicationStatus == replication.Replica) {
```
Comment (harshavardhana) [inline cmd/data-scanner.go]: why is this required?

File: go.mod [hunk 2]
```diff
@@ -87,3 +87,4 @@ require (
 	google.golang.org/api v0.31.0
 	gopkg.in/yaml.v2 v2.4.0
 )
+replace github.com/minio/minio-go => ../minio-go
```
Comment (harshavardhana) [inline go.mod]: there is a minio-go change needed as well?

**Review by harshavardhana — CHANGES_REQUESTED** [review]

File: cmd/data-scanner.go (hunk 1 above)
Comment (poornas) [reply cmd/data-scanner.go]: In 2 way replication, if one of the sites is out of sync - it seemed like this will help, but on second thoughts it is a bad idea. Will remove this extra condition.

File: go.mod (hunk 2 above)
Comment (poornas) [reply go.mod]: yes - status code returned for stat for a deletemarker version should be MethodNotAllowed rather than BadRequest

**Comment by minio-trusted** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-s3.sh | :heavy_check_mark: |
| mint-erasure.sh | :heavy_check_mark: |
| mint-dist-erasure.sh | :heavy_check_mark: |
| mint-zoned.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-compress-encrypt-dist-erasure.sh | :heavy_check_mark: |
Deleting image on docker hub
Deleting image locally

File: go.mod (hunk 2 above)
Comment (harshavardhana) [reply go.mod]: that is returned by server what is minio-go doing here?

**Review by harshavardhana — CHANGES_REQUESTED** [review]

File: go.mod (hunk 2 above)
Comment (poornas) [reply go.mod]: minio-go has a bug where the ErrorResponse struct is not constructed correctly when error code is MethodNotAllowed - this is an issue in replication because we need to determine if a delete marker version exists or not before trying to replicate it and ErrorCode is not populated because of the minio-go bug.

Comment (harshavardhana) [reply go.mod]: where is the minio-go change? @poornas

Comment (poornas) [reply go.mod]: https://github.com/minio/minio-go/pull/1531/files

**Comment by minio-trusted** [comment]
```
Error running mint automation
+ mkdir -p 12932-3afc9da/gopath/src/github.com/minio
+ git -C 12932-3afc9da/gopath/src/github.com/minio clone --quiet https://github.com/minio/minio.git
+ git -C 12932-3afc9da/gopath/src/github.com/minio/minio remote add minio https://github.com/minio/minio.git
+ git -C 12932-3afc9da/gopath/src/github.com/minio/minio fetch --quiet minio pull/12932/head:pr12932
+ git -C 12932-3afc9da/gopath/src/github.com/minio/minio checkout --quiet pr12932
+ GO111MODULE=on
+ GOPATH=/home/mint-auto/mint-auto/12932-3afc9da/gopath
+ make -C 12932-3afc9da/gopath/src/github.com/minio/minio --quiet
go: github.com/minio/minio-go/v7@v7.0.13-0.20210715203016-9e713532886e (replaced by ../minio-go): reading ../minio-go/go.mod: open /home/mint-auto/mint-auto/12932-3afc9da/gopath/src/github.com/minio/minio-go/go.mod: no such file or directory
go: github.com/minio/minio-go/v7@v7.0.13-0.20210715203016-9e713532886e (replaced by ../minio-go): reading ../minio-go/go.mod: open /home/mint-auto/mint-auto/12932-3afc9da/gopath/src/github.com/minio/minio-go/go.mod: no such file or directory
make: *** [build] Error 1

```

File: cmd/gateway-common.go [hunk 3]
```diff
@@ -331,6 +331,8 @@ func ErrorRespToObjectError(err error, params ...string) error {
 		err = InvalidUploadID{}
 	case "EntityTooSmall":
 		err = PartTooSmall{}
+	case "MethodNotAllowed":
+		err = MethodNotAllowed{}
```
Comment (harshavardhana) [inline cmd/gateway-common.go]: Can you not add this as well to avoid `minio-go` dependency on this change? 

```diff
git diff
diff --git a/cmd/gateway-common.go b/cmd/gateway-common.go
index 1c74c29ff..c39ceb54c 100644
--- a/cmd/gateway-common.go
+++ b/cmd/gateway-common.go
@@ -331,6 +331,8 @@ func ErrorRespToObjectError(err error, params ...string) error {
                err = InvalidUploadID{}
        case "EntityTooSmall":
                err = PartTooSmall{}
+       case http.StatusText(http.StatusMethodNotAllowed):
+               err = toObjectErr(errMethodNotAllowed, bucket, object)
        }
 
        return err
```

**Review by harshavardhana — CHANGES_REQUESTED** [review]

File: cmd/gateway-common.go (hunk 3 above)
Comment (poornas) [reply cmd/gateway-common.go]: fixed

**Comment by minio-trusted** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-s3.sh | :heavy_check_mark: |
| mint-erasure.sh | :heavy_check_mark: |
| mint-dist-erasure.sh | :heavy_check_mark: |
| mint-zoned.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-compress-encrypt-dist-erasure.sh | :heavy_check_mark: |
Deleting image on docker hub
Deleting image locally

**Review by harshavardhana — APPROVED** [review]

**Review by krisis — APPROVED** [review]

**Comment by harshavardhana** [comment]
@poornas PTAL at the conflicts

**Comment by minio-trusted** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-s3.sh | :heavy_check_mark: |
| mint-erasure.sh | :heavy_check_mark: |
| mint-dist-erasure.sh | :heavy_check_mark: |
| mint-zoned.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-compress-encrypt-dist-erasure.sh | :heavy_check_mark: |
Deleting image on docker hub
Deleting image locally
