### PR TITLE
fix: Avoid concurrent map writes in go-routines

### LINKED ISSUE #5897: Rare crash due to a concurrent map writes
## Expected Behavior
No crash

## Current Behavior
Rare crash

```
fatal error: concurrent map writes

goroutine 2505706 [running]:
runtime.throw(0x112243a, 0x15)
        /home/minio/.gimme/versions/go1.10.1.linux.amd64/src/runtime/panic.go:616 +0x81 fp=0xc4200f1eb0 sp=0xc4200f1e90 pc=0x42cc61
runtime.mapassign(0xf77fe0, 0xc4260962a0, 0xc4200f1f78, 0x11fb5a0)
        /home/minio/.gimme/versions/go1.10.1.linux.amd64/src/runtime/hashmap.go:607 +0x553 fp=0xc4200f1f40 sp=0xc4200f1eb0 pc=0x409da3
github.com/minio/minio/cmd.(*NotificationSys).DeleteBucket.func1(0xc4245f4f30, 0xc4204e6b48, 0x32, 0xc4260962a0, 0x7ffde2a453ba, 0x9, 0xc42501238f, 0xc42021e330)
        /home/minio/vadmeste/gospace/src/github.com/minio/minio/cmd/notification.go:71 +0xf0 fp=0xc4200f1fa0 sp=0xc4200f1f40 pc=0xc49270
runtime.goexit()
        /home/minio/.gimme/versions/go1.10.1.linux.amd64/src/runtime/asm_amd64.s:2361 +0x1 fp=0xc4200f1fa8 sp=0xc4200f1fa0 pc=0x45a451
created by github.com/minio/minio/cmd.(*NotificationSys).DeleteBucket
        /home/minio/vadmeste/gospace/src/github.com/minio/minio/cmd/notification.go:68 +0x16e
```

## Possible Solution
Do not know yet

## Steps to Reproduce (for bugs)
Running minio-py in full mode multiple times.

```sh
while true; do 
   docker run --net="host" -e SERVER_ENDPOINT=65.xx.xx.xx:9101 -e ACCESS_KEY=minio -e SECRET_KEY=minio123 -e ENABLE_HTTPS=0 -e MINT_MODE=full minio/mint:edge minio-py; 
done
```

## Context
Testing

## Your Environment
All, master

### PR DESCRIPTION
**Pull request by harshavardhana**
## Description
fix: Avoid concurrent map writes in go-routines

## Motivation and Context
Fixes #5897

## How Has This Been Tested?
After reproducing with `go build -race`

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added unit tests to cover my changes.
- [ ] I have added/updated functional tests in [mint](https://github.com/minio/mint). (If yes, add `mint` PR # here: )
- [x] All new and existing tests passed.

### CODE REVIEW

File: cmd/notification.go [hunk 1]
```diff
@@ -59,94 +59,126 @@ func (sys *NotificationSys) GetPeerRPCClient(addr xnet.Host) *PeerRPCClient {
...
 
-	return errors
+	return errs
 }
 
 // RemoveBucketPolicy - calls RemoveBucketPolicy RPC call on all peers.
-func (sys *NotificationSys) RemoveBucketPolicy(bucketName string) map[xnet.Host]error {
-	errors := make(map[xnet.Host]error)
+func (sys *NotificationSys) RemoveBucketPolicy(bucketName string) []NotificationPeerErr {
+	errs := make([]NotificationPeerErr, len(sys.peerRPCClientMap))
```
Comment (balamurugana) [inline cmd/notification.go]: What is the exact problem with existing code?  There is no way corrupt the map by those goroutines.  If you still paranoid, use `sync.Map`

Comment (balamurugana) [inline cmd/notification.go:116]: What is the exact problem with existing code?  There is no way corrupt the map by those goroutines.  If you still paranoid, use `sync.Map`.

Handling slice is no difference by dealing with map here.

**Review by balamurugana — DISMISSED** [review]

File: cmd/notification.go (hunk 1 above)
Comment (harshavardhana) [reply cmd/notification.go:116]: I don't think so and I don't think you are understanding what maps is doing here - it cannot be used inside go-routine and concurrently updated without protection, look at the referenced bug @balamurugana for the actual detail. Using simply `xnet.Host` as the key index doesn't help in avoiding that either since in Go maps are not position oriented they are simply unordered. To reprodue the problem simply build minio server with `go build -race` and perform any of the NotificationSys operations you will see crashes. 

Slice is different because of the pointer nature and can be independently updated as a memory pointer if you know the right position. That is why i am not using `append` instead I have a slice with proper length equal to the peer clients. 

This is similar to all our code inside erasure code, where we update errs with their respective positions in go-routines.

Comment (balamurugana) [reply cmd/notification.go:116]: I am able to see goroutines and map race.  I don't think returning N element slice is good idea (even though used in existing code).  You could fix using `sync.Map`.

Comment (harshavardhana) [reply cmd/notification.go:116]: sync.Map is actually not necessary we don't need that kind of protection since these are all distinct calls to distinct peers @balamurugana - slices are correct here IMO which allow for no mutex requirement.  We can, in fact, do simply []error I brought the struct to satisfy error logging requirements added by the caller.

Comment (balamurugana) [reply cmd/notification.go:116]: > sync.Map is actually not necessary we don't need that kind of protection since these are all distinct calls to distinct peers @balamurugana

That's why I am talking about a map here.  Map will be nil or empty for all success and non-nil/entries only for errors.  Because data insertion happens only for failures.  Keeping N element slice is not required.

As overall parallel RPC calls to servers, currently we are not handling quorum based waiting for such goroutines all over the code.  This is wider problem to fix (As per my idea higher level type of N endpoints would solve cleanly).  I am seen many problems (without any logs) on failure tests.

As you are fixing map race, you could patch with `sync.Map`.  Let parallel RPC execution fix would take care automatically (Parallel RPC execution would return appropriate data structure for errors)

Comment (harshavardhana) [reply cmd/notification.go:116]: > As overall parallel RPC calls to servers, currently we are not handling quorum based waiting for such goroutines all over the code. This is wider problem to fix (As per my idea higher level type of N endpoints would solve cleanly). I am seen many problems (without any logs) on failure tests.

Can you point to locations where we are not handling this? @balamurugana - From what I see I don't think this is true. 

> That's why I am talking about a map here. Map will be nil or empty for all success and non-nil/entries only for errors. Because data insertion happens only for failures. Keeping N element slice is not required.

If we are optimizing on memory then it is fine but our peer clients never go beyond 32 endpoints and it's premature I think. The problem I have with sync.Map is having to use mutex where it's not needed.

Comment (balamurugana) [reply cmd/notification.go:116]: Code places are wherever we do parallel execution of RPC calls.  As we wait for all RPC calls to finish,  the wait may be infinite.  It is wrong and client never gets response (As these bugs are already reported) or client will timeout itself.  The actual way of waiting should be done for quorum.  This will help to get response quicker for the client.

We don't need to worry about internal mutex or any locking mechanism of any Go builtin data structure (unless it has very serious performance penalty).

Point to this PR is any change it makes will be changed when parallel execution of RPC calls are handled properly.  Less code change is preferred to avoid confusion in parallel RPC executions.

Comment (harshavardhana) [reply cmd/notification.go:116]: > We don't need to worry about internal mutex or any locking mechanism of any Go builtin data structure (unless it has very serious performance penalty).

Why not? how do we conclude sync.Map is correct here? if you look at Go's own source sync.Map is rarely used only in a handful of packages. 

> Point to this PR is any change it makes will be changed when parallel execution of RPC calls are handled properly. Less code change is preferred to avoid confusion in parallel RPC executions.

How is using sync.Map going to be minimal? how is that better understood than slices?

File: cmd/notification.go [hunk 2]
```diff
@@ -59,94 +59,126 @@ func (sys *NotificationSys) GetPeerRPCClient(addr xnet.Host) *PeerRPCClient {
...
+	Err  error     // Error returned by the remote peer for an rpc call
+}
+
 // DeleteBucket - calls DeleteBucket RPC call on all peers.
-func (sys *NotificationSys) DeleteBucket(bucketName string) map[xnet.Host]error {
-	errors := make(map[xnet.Host]error)
+func (sys *NotificationSys) DeleteBucket(bucketName string) []NotificationPeerErr {
+	errs := make([]NotificationPeerErr, len(sys.peerRPCClientMap))
 	var wg sync.WaitGroup
+	idx := 1
```
Comment (vadmeste) [inline cmd/notification.go]: `idx` should start with zero here, otherwise we will have index out of range problem.

File: cmd/notification.go [hunk 3]
```diff
@@ -59,94 +59,126 @@ func (sys *NotificationSys) GetPeerRPCClient(addr xnet.Host) *PeerRPCClient {
...
+	return errs
 }
 
 // SetBucketPolicy - calls SetBucketPolicy RPC call on all peers.
-func (sys *NotificationSys) SetBucketPolicy(bucketName string, bucketPolicy *policy.Policy) map[xnet.Host]error {
-	errors := make(map[xnet.Host]error)
+func (sys *NotificationSys) SetBucketPolicy(bucketName string, bucketPolicy *policy.Policy) []NotificationPeerErr {
+	errs := make([]NotificationPeerErr, len(sys.peerRPCClientMap))
 	var wg sync.WaitGroup
+	idx := 1
```
Comment (vadmeste) [inline cmd/notification.go]: `idx` should start with zero here, otherwise we will have index out of range problem.

File: cmd/notification.go [hunk 4]
```diff
@@ -59,94 +59,126 @@ func (sys *NotificationSys) GetPeerRPCClient(addr xnet.Host) *PeerRPCClient {
...
+	return errs
 }
 
 // RemoveBucketPolicy - calls RemoveBucketPolicy RPC call on all peers.
-func (sys *NotificationSys) RemoveBucketPolicy(bucketName string) map[xnet.Host]error {
-	errors := make(map[xnet.Host]error)
+func (sys *NotificationSys) RemoveBucketPolicy(bucketName string) []NotificationPeerErr {
+	errs := make([]NotificationPeerErr, len(sys.peerRPCClientMap))
 	var wg sync.WaitGroup
+	idx := 1
```
Comment (vadmeste) [inline cmd/notification.go]: `idx` should start with zero here, otherwise we will have index out of range problem.

File: cmd/notification.go [hunk 5]
```diff
@@ -59,94 +59,126 @@ func (sys *NotificationSys) GetPeerRPCClient(addr xnet.Host) *PeerRPCClient {
...
+	return errs
 }
 
 // PutBucketNotification - calls PutBucketNotification RPC call on all peers.
-func (sys *NotificationSys) PutBucketNotification(bucketName string, rulesMap event.RulesMap) map[xnet.Host]error {
-	errors := make(map[xnet.Host]error)
+func (sys *NotificationSys) PutBucketNotification(bucketName string, rulesMap event.RulesMap) []NotificationPeerErr {
+	errs := make([]NotificationPeerErr, len(sys.peerRPCClientMap))
 	var wg sync.WaitGroup
+	idx := 1
```
Comment (vadmeste) [inline cmd/notification.go]: `idx` should start with zero here, otherwise we will have index out of range problem.

File: cmd/notification.go [hunk 6]
```diff
@@ -59,94 +59,126 @@ func (sys *NotificationSys) GetPeerRPCClient(addr xnet.Host) *PeerRPCClient {
...
 }
 
 // ListenBucketNotification - calls ListenBucketNotification RPC call on all peers.
-func (sys *NotificationSys) ListenBucketNotification(bucketName string, eventNames []event.Name, pattern string, targetID event.TargetID, localPeer xnet.Host) map[xnet.Host]error {
-	errors := make(map[xnet.Host]error)
+func (sys *NotificationSys) ListenBucketNotification(bucketName string, eventNames []event.Name, pattern string,
+	targetID event.TargetID, localPeer xnet.Host) []NotificationPeerErr {
+	errs := make([]NotificationPeerErr, len(sys.peerRPCClientMap))
 	var wg sync.WaitGroup
+	idx := 1
```
Comment (vadmeste) [inline cmd/notification.go]: `idx` should start with zero here, otherwise we will have index out of range problem.

Comment (harshavardhana) [reply cmd/notification.go]: Oops yes..

**Comment by balamurugana** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-xl.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-s3.sh | :heavy_check_mark: |
| mint-dist-xl.sh | :x: [more...](#b4d5b02f-fe57-48de-88e8-dd3c197b0878) |
| mint-gateway-azure.sh | :x: [more...](#fe52816f-ea7d-43e4-8ef8-ebca4d2dcbdb) |
<a name="fe52816f-ea7d-43e4-8ef8-ebca4d2dcbdb"></a>
### 5898-7f8bbc6/mint-gateway-azure.sh.log:
```
Running with
SERVER_ENDPOINT: minikube:32023
ACCESS_KEY:      minioazure1
SECRET_KEY:      ***REDACTED***
ENABLE_HTTPS:    0
SERVER_REGION:   us-east-1
MINT_DATA_DIR:   /mint/data
MINT_MODE:       core

To get logs, run 'docker cp 5befd96a58e3:/mint/log /tmp/mint-logs'
(1/13) Running aws-sdk-go tests ... done in 2 seconds
(2/13) Running aws-sdk-java tests ... done in 16 seconds
(3/13) Running aws-sdk-php tests ... done in 56 seconds
(4/13) Running aws-sdk-ruby tests ... done in 27 seconds
(5/13) Running awscli tests ... done in 4 minutes and 55 seconds
(6/13) Running mc tests ... done in 7 minutes and 22 seconds
(7/13) Running minio-dotnet tests ... done in 1 minutes and 9 seconds
(8/13) Running minio-go tests ... done in 1 seconds
(9/13) Running minio-java tests ... done in 32 seconds
(10/13) Running minio-js tests ... FAILED in 2 minutes and 28 seconds
{
  "name": "minio-js",
  "function": "listObjects(bucketName, prefix, recursive)",
  "args": "bucketName:minio-js-test-be22edcf-6641-463e-9bde-b988ed7deec4, recursive:false",
  "duration": 185,
  "status": "FAIL",
  "error": "Error: listObjects lists 11 objects, expected 10 at Readable.client.listObjects.on.on (test/functional-tests.js:947:23) at endReadableNT (_stream_readable.js:978:12) at _combinedTickCallback (internal/process/next_tick.js:80:11) at process._tickCallback (internal/process/next_tick.js:104:9)"
}

Executed 9 out of 13 tests successfully.
```
<a name="b4d5b02f-fe57-48de-88e8-dd3c197b0878"></a>
### 5898-7f8bbc6/mint-dist-xl.sh.log:
```
Running with
SERVER_ENDPOINT: minikube:30391
ACCESS_KEY:      minio
SECRET_KEY:      ***REDACTED***
ENABLE_HTTPS:    0
SERVER_REGION:   us-east-1
MINT_DATA_DIR:   /mint/data
MINT_MODE:       core

To get logs, run 'docker cp 8492dbc25b55:/mint/log /tmp/mint-logs'
(1/13) Running aws-sdk-go tests ... done in 2 seconds
(2/13) Running aws-sdk-java tests ... done in 16 seconds
(3/13) Running aws-sdk-php tests ... done in 49 seconds
(4/13) Running aws-sdk-ruby tests ... done in 17 seconds
(5/13) Running awscli tests ... done in 5 minutes and 59 seconds
(6/13) Running mc tests ... done in 2 minutes and 6 seconds
(7/13) Running minio-dotnet tests ... done in 36 seconds
(8/13) Running minio-go tests ... done in 11 seconds
(9/13) Running minio-java tests ... done in 50 seconds
(10/13) Running minio-js tests ... FAILED in 58 seconds
{
  "name": "minio-js",
  "function": "listenBucketNotification(bucketName, prefix, suffix, events)",
  "args": "bucketName:minio-js-test-8529c7cf-788c-46c4-994a-fe2b27c8f82a, events: s3:ObjectCreated:*",
  "duration": 8536,
  "status": "FAIL",
  "error": "Error: notification not received at client.removeObject.err (test/functional-tests.js:1034:43) at ClientRequest.<anonymous> (node_modules/minio/dist/main/minio.js:420:9) at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:478:21) at HTTPParser.parserOnHeadersComplete (_http_common.js:99:23) at Socket.socketOnData (_http_client.js:367:20) at readableAddChunk (_stream_readable.js:176:18) at Socket.Readable.push (_stream_readable.js:134:10) at TCP.onread (net.js:559:20)"
}

Executed 9 out of 13 tests successfully.
```

**Comment by balamurugana** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-xl.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-dist-xl.sh | :heavy_check_mark: |
| mint-gateway-s3.sh | :heavy_check_mark: |
| mint-gateway-azure.sh | :x: [more...](#ea7e85d6-0814-4a9b-b1e8-e8d2301d6cc8) |
<a name="ea7e85d6-0814-4a9b-b1e8-e8d2301d6cc8"></a>
### 5898-a172e04/mint-gateway-azure.sh.log:
```
Running with
SERVER_ENDPOINT: minikube:30039
ACCESS_KEY:      minioazure1
SECRET_KEY:      ***REDACTED***
ENABLE_HTTPS:    0
SERVER_REGION:   us-east-1
MINT_DATA_DIR:   /mint/data
MINT_MODE:       core

To get logs, run 'docker cp 46751d3e22aa:/mint/log /tmp/mint-logs'
(1/13) Running aws-sdk-go tests ... done in 2 seconds
(2/13) Running aws-sdk-java tests ... done in 13 seconds
(3/13) Running aws-sdk-php tests ... done in 1 minutes and 0 seconds
(4/13) Running aws-sdk-ruby tests ... done in 39 seconds
(5/13) Running awscli tests ... done in 4 minutes and 22 seconds
(6/13) Running mc tests ... done in 7 minutes and 37 seconds
(7/13) Running minio-dotnet tests ... done in 1 minutes and 10 seconds
(8/13) Running minio-go tests ... done in 1 seconds
(9/13) Running minio-java tests ... done in 22 seconds
(10/13) Running minio-js tests ... FAILED in 2 minutes and 38 seconds
{
  "name": "minio-js",
  "function": "listObjects(bucketName, prefix, recursive)",
  "args": "bucketName:minio-js-test-6bd0990a-57a2-463b-bb1e-66bfcedb90d4, recursive:false",
  "duration": 184,
  "status": "FAIL",
  "error": "Error: listObjects lists 11 objects, expected 10 at Readable.client.listObjects.on.on (test/functional-tests.js:947:23) at endReadableNT (_stream_readable.js:978:12) at _combinedTickCallback (internal/process/next_tick.js:80:11) at process._tickCallback (internal/process/next_tick.js:104:9)"
}

Executed 9 out of 13 tests successfully.
```

**Comment by balamurugana** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-xl.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-dist-xl.sh | :heavy_check_mark: |
| mint-gateway-s3.sh | :heavy_check_mark: |
| mint-gateway-azure.sh | :heavy_check_mark: |

**Comment by balamurugana** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-xl.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-s3.sh | :heavy_check_mark: |
| mint-gateway-azure.sh | :heavy_check_mark: |
| mint-dist-xl.sh | :x: [more...](#d7398c99-9f6e-4d15-8915-3d5e0d775689) |
<a name="d7398c99-9f6e-4d15-8915-3d5e0d775689"></a>
### 5898-fe4a92d/mint-dist-xl.sh.log:
```
Running with
SERVER_ENDPOINT: minikube:31765
ACCESS_KEY:      minio
SECRET_KEY:      ***REDACTED***
ENABLE_HTTPS:    0
SERVER_REGION:   us-east-1
MINT_DATA_DIR:   /mint/data
MINT_MODE:       core

To get logs, run 'docker cp fedac9f1b5b8:/mint/log /tmp/mint-logs'
(1/13) Running aws-sdk-go tests ... done in 4 seconds
(2/13) Running aws-sdk-java tests ... done in 14 seconds
(3/13) Running aws-sdk-php tests ... done in 48 seconds
(4/13) Running aws-sdk-ruby tests ... done in 26 seconds
(5/13) Running awscli tests ... done in 3 minutes and 48 seconds
(6/13) Running mc tests ... done in 3 minutes and 2 seconds
(7/13) Running minio-dotnet tests ... done in 44 seconds
(8/13) Running minio-go tests ... done in 7 seconds
(9/13) Running minio-java tests ... done in 36 seconds
(10/13) Running minio-js tests ... FAILED in 1 minutes and 1 seconds
{
  "name": "minio-js",
  "function": "listenBucketNotification(bucketName, prefix, suffix, events)",
  "args": "bucketName:minio-js-test-d4885a01-14f6-487b-a954-59880dca27b5, events: s3:ObjectCreated:*",
  "duration": 8094,
  "status": "FAIL",
  "error": "Error: notification not received at client.removeObject.err (test/functional-tests.js:1034:43) at ClientRequest.<anonymous> (node_modules/minio/dist/main/minio.js:420:9) at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:478:21) at HTTPParser.parserOnHeadersComplete (_http_common.js:99:23) at Socket.socketOnData (_http_client.js:367:20) at readableAddChunk (_stream_readable.js:176:18) at Socket.Readable.push (_stream_readable.js:134:10) at TCP.onread (net.js:559:20)"
}

Executed 9 out of 13 tests successfully.
```

**Comment by harshavardhana** [comment]
Another reason why I want to avoid sync.Map usage is that it loses types basically returning an `interface{}`  and causing us to perform type assertions which brings its own set of problems.

https://www.youtube.com/watch?v=C1EtfDnsdDs this video explains on the pitfalls and the right use case for sync.Map.  `sync.Map` is always used as a high-performance alternative to `map + sync.RWMutex`  and it also solves a specific pattern of problems.  As the video explains properly in one sentence. 

```
If cache contention is not the problem, sync.Map is probably not the solution
```

In our case, it is an overkill and I am going to stick to slices for now.

**Review by vadmeste — APPROVED** [review]
LGTM

**Comment by deekoder** [comment]
We do need to take this for the next release!

**Review by donatello — APPROVED** [review]
I understand the approach using slice here instead of map. The sync.Map approach while it would work has no significant advantage - the use case here falls into neither of the cases that that sync.Map is optimized for - quoting from https://golang.org/pkg/sync/#Map:


>  The Map type is optimized for two common use cases: (1) when the entry for a given key is only ever written once but read many times, as in caches that only grow, or (2) when multiple goroutines read, write, and overwrite entries for disjoint sets of keys. In these two cases, use of a Map may significantly reduce lock contention compared to a Go map paired with a separate Mutex or RWMutex.

**Comment by deekoder** [comment]
Ignoring mint again for this merge.
