### PR TITLE
S3 select: Fix output conversion on select *

### LINKED ISSUE #8268: S3 Select *  no longer works with JSONOutputSerialization
## Expected Behavior

```
 mc sql --json-output ""  -e  "select * FROM S3Object"  myminio/sql/parking-citations-100K.csv
```
should work but does not.
## Current Behavior

Above command works if the --json-output flag is removed.
## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Regression
 Yes - dac1cf5a9aa70762c8ee7d45ccce3f5c2059bbe3 

## Your Environment

* Version used (`minio version`):
* Environment name and version (e.g. nginx 1.9.1):
* Server type and version:
* Operating System and version (`uname -a`):
* Link to your project:

### PR DESCRIPTION
**Pull request by klauspost**
## Description

When we copy full record from input to output we must handle conversion gracefully.

Change CopyFrom to Clone with optional destination.

## Motivation and Context

Fixes #8268

## How to test this PR?

A test will be added for this case.

## Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)

## Checklist:
- [x] Fixes a regression #8268
- [x] Unit tests needed

### CODE REVIEW

**Comment by minio-ops** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-compression-xl.sh | :heavy_check_mark: |
| mint-compression-dist-xl.sh | :heavy_check_mark: |
| mint-compression-fs.sh | :heavy_check_mark: |
| mint-worm.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-xl.sh | :x: [more...](#3747205f-0c3c-4448-aa4a-2e40e0da242f) |
| mint-large-bucket.sh | :x: [more...](#f27b7975-a50e-41c1-bf19-fa2f6276ba4f) |
| mint-fs.sh | :x: [more...](#23e5c201-0924-4b8a-94c5-8edd25a7dfe6) |
| mint-dist-xl.sh | :x: [more...](#4386417d-ac4c-417c-9507-1f59aba58333) |
<a name="4386417d-ac4c-417c-9507-1f59aba58333"></a>
### 8303-03e9d73/mint-dist-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.55:30183
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 4d3d15409d46:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 1 seconds
(2/14) Running aws-sdk-java tests ... done in 1 seconds
(3/14) Running aws-sdk-php tests ... done in 44 seconds
(4/14) Running aws-sdk-ruby tests ... done in 3 seconds
(5/14) Running awscli tests ... done in 2 minutes and 9 seconds
(6/14) Running healthcheck tests ... done in 0 seconds
(7/14) Running mc tests ... done in 1 minutes and 23 seconds
(8/14) Running minio-dotnet tests ... done in 33 seconds
(9/14) Running minio-go tests ... done in 1 minutes and 17 seconds
(10/14) Running minio-java tests ... done in 2 minutes and 2 seconds
(11/14) Running minio-js tests ... done in 52 seconds
(12/14) Running minio-py tests ... FAILED in 3 minutes and 25 seconds
{
  "message": "AccessDenied: message: Access Denied",
  "args": {
    "response.status": 403,
    "object_name": "1a8aa96e-ec06-4ce6-a9b1-14aafcf600ec",
    "response.headers": "{\"_container\": {\"accept-ranges\": [\"Accept-Ranges\", \"bytes\"], \"content-length\": [\"Content-Length\", \"440\"], \"content-security-policy\": [\"Content-Security-Policy\", \"block-all-mixed-content\"], \"content-type\": [\"Content-Type\", \"application/xml\"], \"server\": [\"Server\", \"MinIO/DEVELOPMENT.2019-09-24T22-52-42Z\"], \"vary\": [\"Vary\", \"Origin\"], \"x-amz-request-id\": [\"X-Amz-Request-Id\", \"15C7830FDB800ABB\"], \"x-xss-protection\": [\"X-Xss-Protection\", \"1; mode=block\"], \"date\": [\"Date\", \"Tue, 24 Sep 2019 23:18:19 GMT\"]}}",
    "bucket_name": "minio-py-test-ffd1e8af-8423-4d86-a3ab-6490f48663f5",
    "response.reason": "Forbidden",
    "presigned_get_object_url": "http://72.28.97.55:30183/minio-py-test-ffd1e8af-8423-4d86-a3ab-6490f48663f5/1a8aa96e-ec06-4ce6-a9b1-14aafcf600ec?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=minio%2F20190924%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20190924T231812Z&X-Amz-Expires=5&X-Amz-SignedHeaders=host&X-Amz-Signature=3604da2b6fd0f01c46cbf98e6fab6595ce10df89ceb56320ab3df37d3007c268",
    "response._body": "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<Error><Code>AccessDenied</Code><Message>Request has expired</Message><Key>1a8aa96e-ec06-4ce6-a9b1-14aafcf600ec</Key><BucketName>minio-py-test-ffd1e8af-8423-4d86-a3ab-6490f48663f5</BucketName><Resource>/minio-py-test-ffd1e8af-8423-4d86-a3ab-6490f48663f5/1a8aa96e-ec06-4ce6-a9b1-14aafcf600ec</Resource><RequestId>15C7830FDB800ABB</RequestId><HostId>0dbf1f8c-b386-4d6b-9140-a7e39313dd6c</HostId></Error>"
  },
  "name": "minio-py:test_presigned_get_object_expiry_5sec",
  "function": "presigned_get_object(bucket_name, object_name, expires, response_headers, request_date)",
  "duration": 93,
  "status": "FAIL",
  "error": "Traceback (most recent call last):\n  File \"/mint/run/core/minio-py/tests.py\", line 1341, in test_presigned_get_object_expiry_5sec\n    object_name).get_exception()\nminio.error.AccessDenied: AccessDenied: message: Access Denied\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"/mint/run/core/minio-py/tests.py\", line 2036, in main\n    test_presigned_get_object_expiry_5sec(client, log_output)\n  File \"/mint/run/core/minio-py/tests.py\", line 1355, in test_presigned_get_object_expiry_5sec\n    raise Exception(err)\nException: AccessDenied: message: Access Denied\n"
}

Executed 11 out of 14 tests successfully.
```
<a name="3747205f-0c3c-4448-aa4a-2e40e0da242f"></a>
### 8303-03e9d73/mint-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.58:31345
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp bfaea8613fd2:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 0 seconds
(2/14) Running aws-sdk-java tests ... done in 1 seconds
(3/14) Running aws-sdk-php tests ... done in 41 seconds
(4/14) Running aws-sdk-ruby tests ... done in 2 seconds
(5/14) Running awscli tests ... done in 1 minutes and 51 seconds
(6/14) Running healthcheck tests ... done in 0 seconds
(7/14) Running mc tests ... done in 1 minutes and 4 seconds
(8/14) Running minio-dotnet tests ... done in 25 seconds
(9/14) Running minio-go tests ... done in 59 seconds
(10/14) Running minio-java tests ... done in 25 seconds
(11/14) Running minio-js tests ... done in 45 seconds
(12/14) Running minio-py tests ... done in 2 minutes and 16 seconds
(13/14) Running s3cmd tests ... FAILED in 5 minutes and 9 seconds
{
  "name": "s3cmd",
  "duration": "303239",
  "function": "test_get_object_multipart",
  "status": "FAIL",
  "error": "\n!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!\n    An unexpected error has occurred.\n  Please try reproducing the error using\n  the latest s3cmd code from the git master\n  branch found at:\n    https://github.com/s3tools/s3cmd\n  and have a look at the known issues list:\n    https://github.com/s3tools/s3cmd/wiki/Common-known-issues-and-their-solutions\n  If the error persists, please report the\n  following lines (removing any private\n  info as necessary) to:\n   s3tools-bugs@lists.sourceforge.net\n\n\n!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!\n\nInvoked as: /usr/local/bin/s3cmd --config /tmp/.s3cmd-24763/s3cfg get s3://s3cmd-test-bucket-31320/s3cmd-test-object-28251 s3cmd-test-object-28251.downloaded\nProblem: timeout: timed out\nS3cmd:   2.0.2\npython:   3.5.2 (default, Jul 10 2019, 11:58:48) \n[GCC 5.4.0 20160609]\nenvironment LANG=C.UTF-8\n\nTraceback (most recent call last):\n  File \"/usr/local/bin/s3cmd\", line 3092, in <module>\n    rc = main()\n  File \"/usr/local/bin/s3cmd\", line 3001, in main\n    rc = cmd_func(args)\n  File \"/usr/local/bin/s3cmd\", line 590, in cmd_object_get\n    response = s3.object_get(uri, dst_stream, destination, start_position = start_position, extra_label = seq_label)\n  File \"/usr/local/lib/python3.5/dist-packages/S3/S3.py\", line 716, in object_get\n    response = self.recv_file(request, stream, labels, start_position)\n  File \"/usr/local/lib/python3.5/dist-packages/S3/S3.py\", line 1742, in recv_file\n    data = http_response.read(this_chunk)\n  File \"/usr/lib/python3.5/http/client.py\", line 458, in read\n    n = self.readinto(b)\n  File \"/usr/lib/python3.5/http/client.py\", line 498, in readinto\n    n = self.fp.readinto(b)\n  File \"/usr/lib/python3.5/socket.py\", line 575, in readinto\n    return self._sock.recv_into(b)\nsocket.timeout: timed out\n\n!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!\n    An unexpected error has occurred.\n  Please try reproducing the error using\n  the latest s3cmd code from the git master\n  branch found at:\n    https://github.com/s3tools/s3cmd\n  and have a look at the known issues list:\n    https://github.com/s3tools/s3cmd/wiki/Common-known-issues-and-their-solutions\n  If the error persists, please report the\n  above lines (removing any private\n  info as necessary) to:\n   s3tools-bugs@lists.sourceforge.net\n!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!"
}

Executed 12 out of 14 tests successfully.
```
<a name="23e5c201-0924-4b8a-94c5-8edd25a7dfe6"></a>
### 8303-03e9d73/mint-fs.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.61:32014
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 073ac89f7a66:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 0 seconds
(2/14) Running aws-sdk-java tests ... done in 1 seconds
(3/14) Running aws-sdk-php tests ... done in 42 seconds
(4/14) Running aws-sdk-ruby tests ... done in 2 seconds
(5/14) Running awscli tests ... done in 1 minutes and 51 seconds
(6/14) Running healthcheck tests ... done in 0 seconds
(7/14) Running mc tests ... done in 43 seconds
(8/14) Running minio-dotnet tests ... done in 35 seconds
(9/14) Running minio-go tests ... done in 54 seconds
(10/14) Running minio-java tests ... done in 1 minutes and 26 seconds
(11/14) Running minio-js tests ... done in 42 seconds
(12/14) Running minio-py tests ... FAILED in 2 minutes and 33 seconds
{
  "duration": 48,
  "message": "AccessDenied: message: Access Denied",
  "function": "presigned_get_object(bucket_name, object_name, expires, response_headers, request_date)",
  "args": {
    "bucket_name": "minio-py-test-2572568e-5328-4dfc-ab3c-bddb5eaef4ba",
    "response._body": "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<Error><Code>AccessDenied</Code><Message>Request has expired</Message><Key>cec52e32-8a88-436a-9639-625303a69304</Key><BucketName>minio-py-test-2572568e-5328-4dfc-ab3c-bddb5eaef4ba</BucketName><Resource>/minio-py-test-2572568e-5328-4dfc-ab3c-bddb5eaef4ba/cec52e32-8a88-436a-9639-625303a69304</Resource><RequestId>15C782E5B6B7C99D</RequestId><HostId>da1564c3-a07e-4c8a-a7c0-67d378f752d6</HostId></Error>",
    "response.headers": "{\"_container\": {\"accept-ranges\": [\"Accept-Ranges\", \"bytes\"], \"content-length\": [\"Content-Length\", \"440\"], \"content-security-policy\": [\"Content-Security-Policy\", \"block-all-mixed-content\"], \"content-type\": [\"Content-Type\", \"application/xml\"], \"server\": [\"Server\", \"MinIO/DEVELOPMENT.2019-09-24T22-52-42Z\"], \"vary\": [\"Vary\", \"Origin\"], \"x-amz-request-id\": [\"X-Amz-Request-Id\", \"15C782E5B6B7C99D\"], \"x-xss-protection\": [\"X-Xss-Protection\", \"1; mode=block\"], \"date\": [\"Date\", \"Tue, 24 Sep 2019 23:15:18 GMT\"]}}",
    "object_name": "cec52e32-8a88-436a-9639-625303a69304",
    "response.reason": "Forbidden",
    "presigned_get_object_url": "http://72.28.97.61:32014/minio-py-test-2572568e-5328-4dfc-ab3c-bddb5eaef4ba/cec52e32-8a88-436a-9639-625303a69304?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=minio%2F20190924%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20190924T231511Z&X-Amz-Expires=5&X-Amz-SignedHeaders=host&X-Amz-Signature=50c7aebe7df08f62666925590ab7eae2494b9b5e736520755a291a1e0a7aea12",
    "response.status": 403
  },
  "error": "Traceback (most recent call last):\n  File \"/mint/run/core/minio-py/tests.py\", line 1341, in test_presigned_get_object_expiry_5sec\n    object_name).get_exception()\nminio.error.AccessDenied: AccessDenied: message: Access Denied\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"/mint/run/core/minio-py/tests.py\", line 2036, in main\n    test_presigned_get_object_expiry_5sec(client, log_output)\n  File \"/mint/run/core/minio-py/tests.py\", line 1355, in test_presigned_get_object_expiry_5sec\n    raise Exception(err)\nException: AccessDenied: message: Access Denied\n",
  "status": "FAIL",
  "name": "minio-py:test_presigned_get_object_expiry_5sec"
}

Executed 11 out of 14 tests successfully.
```
<a name="f27b7975-a50e-41c1-bf19-fa2f6276ba4f"></a>
### 8303-03e9d73/mint-large-bucket.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.54:30882
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp e5c32f4f2bcc:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 7 seconds
(2/14) Running aws-sdk-java tests ... done in 1 seconds
(3/14) Running aws-sdk-php tests ... done in 51 seconds
(4/14) Running aws-sdk-ruby tests ... done in 14 seconds
(5/14) Running awscli tests ... done in 1 minutes and 20 seconds
(6/14) Running healthcheck tests ... done in 0 seconds
(7/14) Running mc tests ... done in 1 minutes and 40 seconds
(8/14) Running minio-dotnet tests ... done in 1 minutes and 31 seconds
(9/14) Running minio-go tests ... FAILED in 3 minutes and 34 seconds
{
  "args": {},
  "duration": 84042,
  "error": "Please reduce your request",
  "function": "testStorageClassMetadataCopyObject()",
  "message": "CopyObject failed on RRS",
  "name": "minio-go: testStorageClassMetadataCopyObject",
  "status": "FAIL"
}

Executed 8 out of 14 tests successfully.
```

**Comment by minio-ops** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-xl.sh | :heavy_check_mark: |
| mint-worm.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-dist-xl.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-compression-xl.sh | :x: [more...](#8eef9024-aaeb-458d-b5a7-fe28b783e4c5) |
| mint-large-bucket.sh | :x: [more...](#9ec37b9a-2466-4c01-89ee-14f3251af07e) |
| mint-compression-dist-xl.sh | :x: [more...](#111502a2-4d50-46e8-b844-7a1745622d3d) |
| mint-compression-fs.sh | :x: [more...](#64f2205a-3ef7-4423-beb3-1d7e4d163d6d) |
<a name="9ec37b9a-2466-4c01-89ee-14f3251af07e"></a>
### 8303-acf42da/mint-large-bucket.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.53:30535
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp a19e23732f96:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 3 seconds
(2/14) Running aws-sdk-java tests ... done in 2 seconds
(3/14) Running aws-sdk-php tests ... done in 52 seconds
(4/14) Running aws-sdk-ruby tests ... done in 15 seconds
(5/14) Running awscli tests ... done in 2 minutes and 20 seconds
(6/14) Running healthcheck tests ... done in 0 seconds
(7/14) Running mc tests ... done in 1 minutes and 12 seconds
(8/14) Running minio-dotnet tests ... done in 1 minutes and 40 seconds
(9/14) Running minio-go tests ... FAILED in 4 minutes and 18 seconds
{
  "args": {},
  "duration": 108422,
  "error": "Please reduce your request",
  "function": "testStorageClassMetadataCopyObject()",
  "message": "CopyObject failed on RRS",
  "name": "minio-go: testStorageClassMetadataCopyObject",
  "status": "FAIL"
}

Executed 8 out of 14 tests successfully.
```
<a name="111502a2-4d50-46e8-b844-7a1745622d3d"></a>
### 8303-acf42da/mint-compression-dist-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.52:32298
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 14ee09e385ad:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 0 seconds
(2/14) Running aws-sdk-java tests ... done in 1 seconds
(3/14) Running aws-sdk-php tests ... done in 46 seconds
(4/14) Running aws-sdk-ruby tests ... done in 5 seconds
(5/14) Running awscli tests ... done in 2 minutes and 2 seconds
(6/14) Running healthcheck tests ... done in 0 seconds
(7/14) Running mc tests ... done in 55 seconds
(8/14) Running minio-dotnet tests ... done in 40 seconds
(9/14) Running minio-go tests ... done in 1 minutes and 24 seconds
(10/14) Running minio-java tests ... done in 2 minutes and 13 seconds
(11/14) Running minio-js tests ... done in 1 minutes and 4 seconds
(12/14) Running minio-py tests ... FAILED in 3 minutes and 34 seconds
{
  "args": {
    "object_name": "578f738d-20ed-4359-ac4d-e7b97938f855",
    "bucket_name": "minio-py-test-ffb6af22-5dc8-4d61-9066-0dbfc905f189",
    "presigned_get_object_url": "http://72.28.97.52:32298/minio-py-test-ffb6af22-5dc8-4d61-9066-0dbfc905f189/578f738d-20ed-4359-ac4d-e7b97938f855?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=minio%2F20190924%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20190924T234749Z&X-Amz-Expires=5&X-Amz-SignedHeaders=host&response-content-language=en_US&response-content-type=text%2Fplain&X-Amz-Signature=f7387b198b9198957d35a890c984de30f31b5e7ce0afb740224a9b9240635d6c"
  },
  "name": "minio-py:test_presigned_get_object_response_headers",
  "error": "Traceback (most recent call last):\n  File \"/mint/run/core/minio-py/tests.py\", line 1396, in test_presigned_get_object_response_headers\n    returned_content_language = response.headers['Content-Language']\n  File \"/usr/local/lib/python3.5/dist-packages/urllib3/_collections.py\", line 156, in __getitem__\n    val = self._container[key.lower()]\nKeyError: 'content-language'\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"/mint/run/core/minio-py/tests.py\", line 2039, in main\n    test_presigned_get_object_response_headers(client, log_output)\n  File \"/mint/run/core/minio-py/tests.py\", line 1414, in test_presigned_get_object_response_headers\n    raise Exception(err)\nException: 'content-language'\n",
  "duration": 93,
  "message": "'content-language'",
  "function": "presigned_get_object(bucket_name, object_name, expires, response_headers, request_date)",
  "status": "FAIL"
}

Executed 11 out of 14 tests successfully.
```
<a name="64f2205a-3ef7-4423-beb3-1d7e4d163d6d"></a>
### 8303-acf42da/mint-compression-fs.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.59:32734
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 46f8b7c32c2e:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 0 seconds
(2/14) Running aws-sdk-java tests ... done in 1 seconds
(3/14) Running aws-sdk-php tests ... done in 41 seconds
(4/14) Running aws-sdk-ruby tests ... done in 2 seconds
(5/14) Running awscli tests ... done in 1 minutes and 53 seconds
(6/14) Running healthcheck tests ... done in 0 seconds
(7/14) Running mc tests ... done in 34 seconds
(8/14) Running minio-dotnet tests ... done in 27 seconds
(9/14) Running minio-go tests ... done in 40 seconds
(10/14) Running minio-java tests ... done in 1 minutes and 15 seconds
(11/14) Running minio-js tests ... done in 44 seconds
(12/14) Running minio-py tests ... FAILED in 2 minutes and 53 seconds
{
  "function": "presigned_get_object(bucket_name, object_name, expires, response_headers, request_date)",
  "message": "AccessDenied: message: Access Denied",
  "name": "minio-py:test_presigned_get_object_expiry_5sec",
  "duration": 47,
  "status": "FAIL",
  "error": "Traceback (most recent call last):\n  File \"/mint/run/core/minio-py/tests.py\", line 1341, in test_presigned_get_object_expiry_5sec\n    object_name).get_exception()\nminio.error.AccessDenied: AccessDenied: message: Access Denied\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"/mint/run/core/minio-py/tests.py\", line 2036, in main\n    test_presigned_get_object_expiry_5sec(client, log_output)\n  File \"/mint/run/core/minio-py/tests.py\", line 1355, in test_presigned_get_object_expiry_5sec\n    raise Exception(err)\nException: AccessDenied: message: Access Denied\n",
  "args": {
    "response._body": "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<Error><Code>AccessDenied</Code><Message>Request has expired</Message><Key>75b96953-1d6c-4378-b17b-98b97d035a60</Key><BucketName>minio-py-test-f555851c-bfa9-4936-b017-bf0746d421eb</BucketName><Resource>/minio-py-test-f555851c-bfa9-4936-b017-bf0746d421eb/75b96953-1d6c-4378-b17b-98b97d035a60</Resource><RequestId>15C7847BD91D4F4F</RequestId><HostId>3eb647e1-a105-4e1b-9233-94e92834d462</HostId></Error>",
    "response.reason": "Forbidden",
    "bucket_name": "minio-py-test-f555851c-bfa9-4936-b017-bf0746d421eb",
    "presigned_get_object_url": "http://72.28.97.59:32734/minio-py-test-f555851c-bfa9-4936-b017-bf0746d421eb/75b96953-1d6c-4378-b17b-98b97d035a60?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=minio%2F20190924%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20190924T234416Z&X-Amz-Expires=5&X-Amz-SignedHeaders=host&X-Amz-Signature=318a1dc9c6b97deb8d7bb159cee6ae78d9a869fb8fdc665adaa1ff5fc8493c86",
    "response.status": 403,
    "object_name": "75b96953-1d6c-4378-b17b-98b97d035a60",
    "response.headers": "{\"_container\": {\"accept-ranges\": [\"Accept-Ranges\", \"bytes\"], \"content-length\": [\"Content-Length\", \"440\"], \"content-security-policy\": [\"Content-Security-Policy\", \"block-all-mixed-content\"], \"content-type\": [\"Content-Type\", \"application/xml\"], \"server\": [\"Server\", \"MinIO/DEVELOPMENT.2019-09-24T23-20-59Z\"], \"vary\": [\"Vary\", \"Origin\"], \"x-amz-request-id\": [\"X-Amz-Request-Id\", \"15C7847BD91D4F4F\"], \"x-xss-protection\": [\"X-Xss-Protection\", \"1; mode=block\"], \"date\": [\"Date\", \"Tue, 24 Sep 2019 23:44:22 GMT\"]}}"
  }
}

Executed 11 out of 14 tests successfully.
```
<a name="8eef9024-aaeb-458d-b5a7-fe28b783e4c5"></a>
### 8303-acf42da/mint-compression-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.53:31350
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp a0314a635329:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... FAILED in 6 minutes and 6 seconds
{
  "alert": "",
  "args": {
    "bucketName": "aws-sdk-go-test-wjbredkj5is4ak",
    "expiry": 60000000000,
    "objectName": "presignedTest"
  },
  "duration": 365606,
  "error": "XMinioServerNotInitialized: Server not initialized, please try again.\n\tstatus code: 503, request id: 15C7844F4ED96CEF, host id: ",
  "function": "PresignedPut",
  "message": "AWS SDK Go CreateBucket Failed",
  "name": "aws-sdk-go",
  "status": "FAIL"
}

Executed 0 out of 14 tests successfully.
```

File: pkg/s3select/sql/statement.go [hunk 1]
```diff
@@ -220,11 +220,11 @@ func (e *SelectStatement) AggregateRow(input Record) error {
 // Eval - evaluates the Select statement for the given record. It
 // applies only to non-aggregation queries.
 // The function returns whether the statement passed the WHERE clause and should be outputted.
-func (e *SelectStatement) Eval(input, output Record) (bool, error) {
+func (e *SelectStatement) Eval(input, output Record) (Record, error) {
```
Comment (sinhaashish) [inline pkg/s3select/sql/statement.go:223]: Since we are returning `Record` in place of `bool` the commen `The function returns whether the statement passed the WHERE clause and should be outputted.` must be modified.

**Comment by sinhaashish** [comment]
`CopyFrom` method must be removed from `pkg/s3select/json/record.go` if it is not used anymore.

**Comment by klauspost** [comment]
@sinhaashish Well spotted. Removed.

**Comment by minio-ops** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-xl.sh | :heavy_check_mark: |
| mint-compression-fs.sh | :heavy_check_mark: |
| mint-worm.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-dist-xl.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-compression-xl.sh | :x: [more...](#af98b742-311a-4b63-8aaa-deea1d67488e) |
| mint-large-bucket.sh | :x: [more...](#d8928cfa-f22a-4c05-b6ec-7f97e913829c) |
| mint-compression-dist-xl.sh | :x: [more...](#03470594-0e83-45a8-babf-e5e486f63bda) |
<a name="af98b742-311a-4b63-8aaa-deea1d67488e"></a>
### 8303-2d05bbd/mint-compression-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.52:30808
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 1488edd922db:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... FAILED in 6 minutes and 5 seconds
{
  "alert": "",
  "args": {
    "bucketName": "aws-sdk-go-test-9uwlpscxnhxll3",
    "expiry": 60000000000,
    "objectName": "presignedTest"
  },
  "duration": 365401,
  "error": "XMinioServerNotInitialized: Server not initialized, please try again.\n\tstatus code: 503, request id: 15C811DEF92BFA3E, host id: ",
  "function": "PresignedPut",
  "message": "AWS SDK Go CreateBucket Failed",
  "name": "aws-sdk-go",
  "status": "FAIL"
}

Executed 0 out of 14 tests successfully.
```
<a name="d8928cfa-f22a-4c05-b6ec-7f97e913829c"></a>
### 8303-2d05bbd/mint-large-bucket.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.52:31332
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp ee8a4af488fb:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 4 seconds
(2/14) Running aws-sdk-java tests ... done in 1 seconds
(3/14) Running aws-sdk-php tests ... done in 49 seconds
(4/14) Running aws-sdk-ruby tests ... done in 15 seconds
(5/14) Running awscli tests ... FAILED in 2 minutes and 19 seconds
{
  "name": "awscli",
  "duration": 1166,
  "function": "make_bucket\n",
  "status": "FAIL",
  "error": "delete: s3://awscli-mint-test-bucket-590/datafile-1-kBremove_bucket: awscli-mint-test-bucket-590"
}

Executed 4 out of 14 tests successfully.
```
<a name="03470594-0e83-45a8-babf-e5e486f63bda"></a>
### 8303-2d05bbd/mint-compression-dist-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.59:30728
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 661105e16d15:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 1 seconds
(2/14) Running aws-sdk-java tests ... done in 1 seconds
(3/14) Running aws-sdk-php tests ... done in 44 seconds
(4/14) Running aws-sdk-ruby tests ... done in 4 seconds
(5/14) Running awscli tests ... done in 2 minutes and 3 seconds
(6/14) Running healthcheck tests ... done in 0 seconds
(7/14) Running mc tests ... FAILED in 44 seconds
{
  "name": "mc",
  "duration": "9748",
  "function": "test_find",
  "status": "FAIL",
  "error": "/mint/run/core/mc/mc --config-dir /tmp/.mc-25066 --quiet --no-color mirror /mint/data myminio/mc-test-bucket-25121  >>> \n`/mint/data/datafile-1-MB` -> `myminio/mc-test-bucket-25121/datafile-1-MB`\n`/mint/data/datafile-0-b` -> `myminio/mc-test-bucket-25121/datafile-0-b`\n`/mint/data/datafile-1-b` -> `myminio/mc-test-bucket-25121/datafile-1-b`\n`/mint/data/datafile-1-kB` -> `myminio/mc-test-bucket-25121/datafile-1-kB`\n`/mint/data/datafile-1.03-MB` -> `myminio/mc-test-bucket-25121/datafile-1.03-MB`\n`/mint/data/datafile-10-kB` -> `myminio/mc-test-bucket-25121/datafile-10-kB`\n`/mint/data/datafile-10-MB` -> `myminio/mc-test-bucket-25121/datafile-10-MB`\n`/mint/data/datafile-11-MB` -> `myminio/mc-test-bucket-25121/datafile-11-MB`\n`/mint/data/datafile-100-kB` -> `myminio/mc-test-bucket-25121/datafile-100-kB`\n`/mint/data/datafile-129-MB` -> `myminio/mc-test-bucket-25121/datafile-129-MB`\n`/mint/data/datafile-5-MB` -> `myminio/mc-test-bucket-25121/datafile-5-MB`\n`/mint/data/datafile-33-kB` -> `myminio/mc-test-bucket-25121/datafile-33-kB`\n`/mint/data/datafile-5243880-b` -> `myminio/mc-test-bucket-25121/datafile-5243880-b`\n`/mint/data/datafile-6-MB` -> `myminio/mc-test-bucket-25121/datafile-6-MB`\n`/mint/data/datafile-65-MB` -> `myminio/mc-test-bucket-25121/datafile-65-MB`\nmc: <ERROR> Failed to copy `/mint/data/datafile-129-MB`. One or more of the specified parts could not be found.  The part may not have been uploaded, or the specified entity tag may not match the part's entity tag.\nTotal: 233.17 MiB, Transferred: 234.17 MiB, Speed: 24.20 MiB/s"
}

Executed 6 out of 14 tests successfully.
```

**Review by sinhaashish — APPROVED** [review]
Tested and LGTM

**Review by donatello — APPROVED** [review]
LGTM!
