### PR TITLE
XL/GetObject: If the offset does not fall in the first "dataBlock" it gives incorrect data.

### LINKED ISSUE #1582: XL: GetObject with offset gives wrong data
data with offset:

```
azureuser@minio-test:/mnt$ curl -s -C 1048575999 "http://127.0.0.1:9000/test1/1gfile?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=CWRVPAV8MKFGFBOXKQVZ%2F20160510%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20160510T143855Z&X-Amz-Expires=604800&X-Amz-SignedHeaders=host&X-Amz-Signature=564d8d01ee4b9f710d3a5033d74dd0f97df66ea87dc5c5d51f46dd5e09e77ed1" |hexdump
0000000 0000                                   
0000001
```

expected:

```
azureuser@minio-test:/mnt$ tail -c 1 1gfile |hexdump
0000000 000c                                   
0000001
azureuser@minio-test:/mnt$ 
```

### PR DESCRIPTION
**Pull request by krishnasrinivas**
Fixes #1582

### CODE REVIEW

File: xl-erasure-v1-readfile.go [hunk 1]
```diff
@@ -179,6 +179,7 @@ func (xl XL) ReadFile(volume, path string, startOffset int64) (io.ReadCloser, er
 				startOffset = startOffset - int64(len(dataBlocks))
 				// Start offset is greater than or equal to zero, skip the dataBlocks.
 				if startOffset >= 0 {
+					totalLeft = totalLeft - metadata.Erasure.BlockSize
```
Comment (harshavardhana) [inline xl-erasure-v1-readfile.go:182]: Add a comment here.
