### PR TITLE
fix: batch expiry job doesn't report delete marker in batch-status me…

### LINKED ISSUE #20506: batch expiry job doesn't report delete marker metrics in batch-status
## NOTE
If this case is urgent, please subscribe to [Subnet](https://min.io/pricing) so that our 24/7 support team may help you faster.

batch-expiry jobs don't report delete marker status in batch-status. The metrics are calculated but aren't available via exported types in `madmin-go`'s [`ExpirationInfo`](https://github.com/minio/madmin-go/blob/main/metrics.go#L509).

## Expected Behavior

batch-status output for batch-expiry job should include delete marker stats when applicable.
## Current Behavior

batch-expiry jobs don't report delete marker status in batch-status. 
## Steps to Reproduce (for bugs)

1. Use the following yaml to start a batch expiry job
```
expire:
  apiVersion: v1
  bucket: mybucket  # Bucket where this job will expire matching objects from
  rules:
    - type: deleted # objects with delete marker as their latest version
      name: "*" # match object names that satisfy the wildcard expression.
      olderThan: 1h

  retry:
    attempts: 3 # number of retries for the job before giving up
    delay: 500ms # least amount of delay between each retry
```
2. For the above yaml to work, you need the following
- `mc mb ALIAS/mybucket`
- `mc version enable ALIAS/mybucket`
- Upload a few objects and delete some of them; To create delete markers
3. Now run, `mc batch start ALIAS /path/to/expire.yaml`
4. `mc batch status ALIAS $JOBID`
This will not display any delete marker stats.

## Regression

No

## Your Environment

* Version used (`minio --version`):
* Server setup and configuration:
* Operating System and version (`uname -a`):

### PR DESCRIPTION
**Pull request by jiuker**
## Community Contribution License
All community contributions in this pull request are licensed to the project maintainers
under the terms of the [Apache 2 license](https://www.apache.org/licenses/LICENSE-2.0). 
By creating this pull request I represent that I have the right to license the 
contributions to the project maintainers under the Apache 2 license.

## Description

Now batch expiry job doesn't report delete marker in batch-status metrics

## Motivation and Context

depond on this pr https://github.com/minio/madmin-go/pull/366
fix https://github.com/minio/minio/issues/20506

## How to test this PR?

1. deploy minio
2. run shell as
```shell
mc.exe mb minio9000/mybucket
mc.exe version enable minio9000/mybucket

mc.exe cp issue.yaml minio9000/mybucket/issue3.yaml
mc.exe rm minio9000/mybucket/issue3.yaml
mc.exe cp issue.yaml minio9000/mybucket/issue3.yaml
mc.exe rm minio9000/mybucket/issue3.yaml
mc.exe cp issue.yaml minio9000/mybucket/issue3.yaml
mc.exe rm minio9000/mybucket/issue3.yaml

mc.exe cp issue.yaml minio9000/mybucket/issue2.yaml
mc.exe rm minio9000/mybucket/issue2.yaml
mc.exe cp issue.yaml minio9000/mybucket/issue2.yaml
mc.exe rm minio9000/mybucket/issue2.yaml

mc.exe cp issue.yaml minio9000/mybucket/issue1.yaml
mc.exe rm minio9000/mybucket/issue1.yaml


mc.exe cp issue.yaml minio9000/mybucket/issue0.yaml
mc.exe cp issue.yaml minio9000/mybucket/issue0.yaml
mc.exe cp issue.yaml minio9000/mybucket/issue0.yaml
mc.exe cp issue.yaml minio9000/mybucket/issue0.yaml
mc.exe cp issue.yaml minio9000/mybucket/issue0.yaml
mc.exe cp issue.yaml minio9000/mybucket/issue0.yaml
mc.exe cp issue.yaml minio9000/mybucket/issue0.yaml
mc.exe cp issue.yaml minio9000/mybucket/issue0.yaml
mc.exe cp issue.yaml minio9000/mybucket/issue0.yaml
mc.exe cp issue.yaml minio9000/mybucket/issue0.yaml


mc.exe batch start minio9000 issue20506.yaml
mc.exe batch status minio9000 "id"
```
issue20506.yaml:
```yaml
expire:
  apiVersion: v1
  bucket: mybucket  # Bucket where this job will expire matching objects from
  rules:
    - type: deleted # objects with delete marker as their latest version
      name: "*" # match object names that satisfy the wildcard expression.
      olderThan: 1s

  retry:
    attempts: 3 # number of retries for the job before giving up
    delay: 500ms # least amount of delay between each retry
```
before pr outPut:
```
28187@jiuker MINGW64 /d/workspace/go/src/minio/stage (master)
$ sh issue20506.sh
Bucket created successfully `minio9000/mybucket`.
minio9000/mybucket versioning is enabled
...space\go\src\minio\stage\issue.yaml: 218 B / 218 B [==================================================================================================================================================] 18.82 KiB/s 0sCreated delete marker `minio9000/mybucket/issue1.yaml` (versionId=a90a22ee-1057-4b35-b344-9358d08b803e).
...space\go\src\minio\stage\issue.yaml: 218 B / 218 B [==================================================================================================================================================] 28.68 KiB/s 0sCreated delete marker `minio9000/mybucket/issue1.yaml` (versionId=4de68be7-ec34-4c09-a5c4-fac855c78140).
...space\go\src\minio\stage\issue.yaml: 218 B / 218 B [==================================================================================================================================================] 30.21 KiB/s 0sCreated delete marker `minio9000/mybucket/issue1.yaml` (versionId=63d8d081-119e-41b9-b2d2-b0e5b6a2feb1).

28187@jiuker MINGW64 /d/workspace/go/src/minio/stage (master)
$ mc.exe batch start minio9000 issue20506.yaml
Successfully started 'expire' job `expire-TEMMmNG6Tc4KTByzwPfT69_-1` on '2025-04-14 13:25:20.0588251 +0800 CST'

28187@jiuker MINGW64 /d/workspace/go/src/minio/stage (master)
$ mc.exe batch status minio9000 "expire-TEMMmNG6Tc4KTByzwPfT69_-1"
✔ ✔ ✔
JobType:        expire
Objects:        12
FailedObjects:  0
CurrObjName:

28187@jiuker MINGW64 /d/workspace/go/src/minio/stage (master)
$

```

## Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Optimization (provides speedup with no functional changes)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [ ] Fixes a regression (If yes, please add `commit-id` or `PR #` here)
- [ ] Unit tests added/updated
- [ ] Internal documentation updated
- [ ] Create a documentation update request [here](https://github.com/minio/docs/issues/new?label=doc-change,title=Doc+Updated+Needed+For+PR+github.com%2fminio%2fminio%2fpull%2fNNNNN)

### CODE REVIEW

File: cmd/batch-expire.go [hunk 1]
```diff
@@ -569,9 +570,8 @@ func (r *BatchJobExpire) Start(ctx context.Context, api ObjectLayer, job BatchJo
 		for _, prefix := range prefixes {
 			prefixResultCh := make(chan itemOrErr[ObjectInfo], workerSize)
 			err := api.Walk(ctx, r.Bucket, prefix, prefixResultCh, WalkOptions{
-				Marker:       lastObject,
-				LatestOnly:   false, // we need to visit all versions of the object to implement purge: retainVersions
-				VersionsSort: WalkVersionsSortDesc,
+				Marker:     lastObject,
+				LatestOnly: false, // we need to visit all versions of the object to implement purge: retainVersions
```
Comment (jiuker) [inline cmd/batch-expire.go]: Please note that the sorting rules have been changed here. Please advise of the risks. @harshavardhana @krisis @klauspost

File: cmd/batch-handlers.go [hunk 2]
```diff
@@ -994,11 +996,13 @@ func (ri *batchJobInfo) updateAfter(ctx context.Context, api ObjectLayer, durati
 // Note: to be used only with batch jobs that affect multiple versions through
 // a single action. e.g batch-expire has an option to expire all versions of an
 // object which matches the given filters.
-func (ri *batchJobInfo) trackMultipleObjectVersions(info ObjectInfo, success bool) {
+func (ri *batchJobInfo) trackMultipleObjectVersions(info expireObjInfo, success bool) {
 	if success {
-		ri.Objects += int64(info.NumVersions)
+		ri.Objects += int64(info.NumVersions) - int64(info.DeleteMarkerCount)
```
Comment (jiuker) [inline cmd/batch-handlers.go]: if treat `deleteMarker` is a `Object`, should keep `ri.Objects += int64(info.NumVersions)`, right? @harshavardhana  @vadmeste @klauspost @krisis

File: cmd/batch-expire.go [hunk 3]
```diff
@@ -623,81 +624,121 @@ func (r *BatchJobExpire) Start(ctx context.Context, api ObjectLayer, job BatchJo
...
-					done = true
-				case expireCh <- xfer:
-					toDel = toDel[:0] // resetting toDel
-				}
-				if done {
-					break
-				}
+		// send down filtered entries to be deleted using
+		// DeleteObjects method
+		if len(toDel) > 10 { // batch up to 10 objects/versions to be expired simultaneously.
```
Comment (klauspost) [inline cmd/batch-expire.go:645]: Why only 10? If this is sent as a single operation, I would assume all deletes could be done with a single read+mutate+write of the metadata? So limiting to 10, just seems like a strange limitation. Maybe 1000 would be a reasonable limit.

But it could easily be that I am having to big expectations of how this is done downstream.

Aren't all of these on the same object?

Comment (jiuker) [reply cmd/batch-expire.go:645]: If retain 0 should single Operation for a object. No retain 0, there are many. In fact, I don't know why 10 too. Maybe @krisis @harshavardhana know?

Comment (harshavardhana) [reply cmd/batch-expire.go:645]: This is okay since this PR is not changing any existing assumptions.

**Review by harshavardhana — APPROVED** [review]

**Comment by harshavardhana** [comment]
@jiuker can you rebase the PR?

**Review by harshavardhana — APPROVED** [review]

**Comment by harshavardhana** [comment]
PTAL @krisis @donatello

File: cmd/batch-expire.go (hunk 3 above)
Comment (krisis) [reply cmd/batch-expire.go:645]: >Aren't all of these on the same object?

No, they are versions spanning multiple objects. I had 10 as a conservative default possibly overestimating the cost of a 1000 object DeleteObjects call. We could increase it to 1000 in a subsequent PR.

**Comment by harshavardhana** [comment]
@jiuker can you send this to miniohq/eos as well?

**Comment by jiuker** [comment]
Sure. Will do that
