### PR TITLE
fix: crash in single drive mode for lifecycle

### LINKED ISSUE #12073: lifecycle works unexpected in server or gateway nas mode
## Expected Behavior

server mode:success get object info without err.
gateway nas mode:can get/set lifecycle like server mode.

## Current Behavior

server mode:minio server panic with nil pointer
gateway nas mode: 1.set bucket lifecle successful 2.get bucket lifecycle it returns not implement

## Possible Solution

server mode:it seems that initBackgroundExpiry function only called on erasure mode.
gateway mode:should indicate whether it is supported now

## Steps to Reproduce (for bugs)

1.setbucketlifecycle
2.getobject 
3.error occurs (object was deleted by lifecycle)

## Context

config.Rules = []lifecycle.Rule{
		{
			ID:     "expire_bucket",
			Status: "Enabled",
			Expiration: lifecycle.Expiration{
				Days: 1,
			},
			RuleFilter: lifecycle.Filter{
				Prefix: objectName,
			},
		},
	}

2021-04-16 18:10:26.905691 I | http: panic serving 10.226.22.65:64201: runtime error: invalid memory address or nil pointer dereference
goroutine 4847 [running]:
net/http.(*conn).serve.func1(0xc000645ea0)
	net/http/server.go:1824 +0x153
panic(0x1c652c0, 0x343b370)
	runtime/panic.go:971 +0x499
github.com/minio/minio/cmd.criticalErrorHandler.ServeHTTP.func1(0xc0001d1400, 0x27c3370, 0xc000e3c7e0)
	github.com/minio/minio/cmd/generic-handlers.go:689 +0x1cc
panic(0x1c652c0, 0x343b370)
	runtime/panic.go:965 +0x1b9
github.com/minio/minio/cmd.(*expiryState).queueExpiryTask(0x0, 0xc000bff33d, 0x4, 0xc000bff342, 0x1, 0x0, 0xed6de6072, 0x3464580, 0x241, 0x0, ...)
	github.com/minio/minio/cmd/bucket-lifecycle.go:79 +0x3a
github.com/minio/minio/cmd.objectAPIHandlers.GetObjectHandler(0x2502850, 0x2502820, 0x27c08e0, 0xc0011b3180, 0xc000ff3500)
	github.com/minio/minio/cmd/object-handlers.go:462 +0x1dc5
net/http.HandlerFunc.ServeHTTP(...)
	net/http/server.go:2069
github.com/minio/minio/cmd.httpTraceHdrs.func1(0x27c08e0, 0xc0011b3180, 0xc000ff3500)
	github.com/minio/minio/cmd/handler-utils.go:375 +0x70
net/http.HandlerFunc.ServeHTTP(...)
	net/http/server.go:2069
github.com/minio/minio/cmd.maxClients.func1(0x27c08e0, 0xc0011b3180, 0xc000ff3500)
	github.com/minio/minio/cmd/handler-api.go:153 +0x3b7
net/http.HandlerFunc.ServeHTTP(...)
	net/http/server.go:2069
github.com/minio/minio/cmd.collectAPIStats.func1(0x27c08e0, 0xc0011b30e0, 0xc000ff3500)
	github.com/minio/minio/cmd/handler-utils.go:390 +0xf7
net/http.HandlerFunc.ServeHTTP(0xc0011621c0, 0x27c08e0, 0xc0011b30e0, 0xc000ff3500)
	net/http/server.go:2069 +0x44
github.com/minio/minio/cmd.setRedirectHandler.func1(0x27c08e0, 0xc0011b30e0, 0xc000ff3500)
	github.com/minio/minio/cmd/generic-handlers.go:135 +0xd3
net/http.HandlerFunc.ServeHTTP(0xc0006856f8, 0x27c08e0, 0xc0011b30e0, 0xc000ff3500)
	net/http/server.go:2069 +0x44
github.com/minio/minio/cmd.addCustomHeaders.func1(0x27c08b0, 0xc000685920, 0xc000ff3500)
	github.com/minio/minio/cmd/generic-handlers.go:664 +0x174
net/http.HandlerFunc.ServeHTTP(0xc000685710, 0x27c08b0, 0xc000685920, 0xc000ff3500)
	net/http/server.go:2069 +0x44
github.com/minio/minio/cmd.addSecurityHeaders.func1(0x27c08b0, 0xc000685920, 0xc000ff3500)
	github.com/minio/minio/cmd/generic-handlers.go:673 +0x1ea
net/http.HandlerFunc.ServeHTTP(0xc000685728, 0x27c08b0, 0xc000685920, 0xc000ff3500)
	net/http/server.go:2069 +0x44
github.com/minio/minio/cmd.setBucketForwardingHandler.func1(0x27c08b0, 0xc000685920, 0xc000ff3500)
	github.com/minio/minio/cmd/generic-handlers.go:547 +0xad
net/http.HandlerFunc.ServeHTTP(0xc000685740, 0x27c08b0, 0xc000685920, 0xc000ff3500)
	net/http/server.go:2069 +0x44
github.com/minio/minio/cmd.setRequestValidityHandler.func1(0x27c08b0, 0xc000685920, 0xc000ff3500)
	github.com/minio/minio/cmd/generic-handlers.go:535 +0x468
net/http.HandlerFunc.ServeHTTP(0xc000685758, 0x27c08b0, 0xc000685920, 0xc000ff3500)
	net/http/server.go:2069 +0x44
github.com/minio/minio/cmd.setHTTPStatsHandler.func1(0x27c3370, 0xc000e3c7e0, 0xc000ff3500)
	github.com/minio/minio/cmd/generic-handlers.go:469 +0xfe
net/http.HandlerFunc.ServeHTTP(0xc000685770, 0x27c3370, 0xc000e3c7e0, 0xc000ff3500)
	net/http/server.go:2069 +0x44
github.com/minio/minio/cmd.setRequestSizeLimitHandler.func1(0x27c3370, 0xc000e3c7e0, 0xc000ff3500)
	github.com/minio/minio/cmd/generic-handlers.go:49 +0xeb
net/http.HandlerFunc.ServeHTTP(0xc000685788, 0x27c3370, 0xc000e3c7e0, 0xc000ff3500)
	net/http/server.go:2069 +0x44
github.com/minio/minio/cmd.setRequestHeaderSizeLimitHandler.func1(0x27c3370, 0xc000e3c7e0, 0xc000ff3500)
	github.com/minio/minio/cmd/generic-handlers.go:68 +0x1e8
net/http.HandlerFunc.ServeHTTP(0xc0006857a0, 0x27c3370, 0xc000e3c7e0, 0xc000ff3500)
	net/http/server.go:2069 +0x44
github.com/minio/minio/cmd.crossDomainPolicy.ServeHTTP(0x279d820, 0xc0006857a0, 0x27c3370, 0xc000e3c7e0, 0xc000ff3500)
	github.com/minio/minio/cmd/crossdomain-xml-handler.go:51 +0x82
github.com/minio/minio/cmd.setBrowserRedirectHandler.func1(0x27c3370, 0xc000e3c7e0, 0xc000ff3500)
	github.com/minio/minio/cmd/generic-handlers.go:161 +0x74
net/http.HandlerFunc.ServeHTTP(0xc0006857b8, 0x27c3370, 0xc000e3c7e0, 0xc000ff3500)
	net/http/server.go:2069 +0x44
github.com/minio/minio/cmd.setReservedBucketHandler.func1(0x27c3370, 0xc000e3c7e0, 0xc000ff3500)
	github.com/minio/minio/cmd/generic-handlers.go:293 +0x278
net/http.HandlerFunc.ServeHTTP(0xc000685818, 0x27c3370, 0xc000e3c7e0, 0xc000ff3500)
	net/http/server.go:2069 +0x44
github.com/minio/minio/cmd.setBrowserCacheControlHandler.func1(0x27c3370, 0xc000e3c7e0, 0xc000ff3500)
	github.com/minio/minio/cmd/generic-handlers.go:262 +0x1ce
net/http.HandlerFunc.ServeHTTP(0xc000685830, 0x27c3370, 0xc000e3c7e0, 0xc000ff3500)
	net/http/server.go:2069 +0x44
github.com/minio/minio/cmd.setTimeValidityHandler.func1(0x27c3370, 0xc000e3c7e0, 0xc000ff3500)
	github.com/minio/minio/cmd/generic-handlers.go:357 +0x407
net/http.HandlerFunc.ServeHTTP(0xc000685848, 0x27c3370, 0xc000e3c7e0, 0xc000ff3500)
	net/http/server.go:2069 +0x44
github.com/minio/minio/cmd.setIgnoreResourcesHandler.func1(0x27c3370, 0xc000e3c7e0, 0xc000ff3500)
	github.com/minio/minio/cmd/generic-handlers.go:456 +0xb8
net/http.HandlerFunc.ServeHTTP(0xc0006858a8, 0x27c3370, 0xc000e3c7e0, 0xc000ff3500)
	net/http/server.go:2069 +0x44
github.com/minio/minio/cmd.setAuthHandler.func1(0x27c3370, 0xc000e3c7e0, 0xc000ff3500)
	github.com/minio/minio/cmd/auth-handler.go:492 +0x391
net/http.HandlerFunc.ServeHTTP(0xc0006858c0, 0x27c3370, 0xc000e3c7e0, 0xc000ff3500)
	net/http/server.go:2069 +0x44
github.com/minio/minio/cmd.setSSETLSHandler.func1(0x27c3370, 0xc000e3c7e0, 0xc000ff3500)
	github.com/minio/minio/cmd/generic-handlers.go:707 +0x74
net/http.HandlerFunc.ServeHTTP(0xc0006858d8, 0x27c3370, 0xc000e3c7e0, 0xc000ff3500)
	net/http/server.go:2069 +0x44
github.com/minio/minio/cmd.filterReservedMetadata.func1(0x27c3370, 0xc000e3c7e0, 0xc000ff3500)
	github.com/minio/minio/cmd/generic-handlers.go:108 +0x1e8
net/http.HandlerFunc.ServeHTTP(0xc0006858f0, 0x27c3370, 0xc000e3c7e0, 0xc000ff3500)
	net/http/server.go:2069 +0x44
github.com/gorilla/mux.(*Router).ServeHTTP(0xc0001d3440, 0x27c3370, 0xc000e3c7e0, 0xc0001d1400)
	github.com/gorilla/mux@v1.8.0/mux.go:210 +0xd3
github.com/rs/cors.(*Cors).Handler.func1(0x27c3370, 0xc000e3c7e0, 0xc0001d1400)
	github.com/rs/cors@v1.7.0/cors.go:219 +0x1b9
net/http.HandlerFunc.ServeHTTP(0xc00119ce20, 0x27c3370, 0xc000e3c7e0, 0xc0001d1400)
	net/http/server.go:2069 +0x44
github.com/minio/minio/cmd.criticalErrorHandler.ServeHTTP(0x279d820, 0xc00119ce20, 0x27c3370, 0xc000e3c7e0, 0xc0001d1400)
	github.com/minio/minio/cmd/generic-handlers.go:692 +0x85
github.com/minio/minio/cmd/http.(*Server).Start.func1(0x27c3370, 0xc000e3c7e0, 0xc0001d1400)
	github.com/minio/minio/cmd/http/server.go:101 +0x258
net/http.HandlerFunc.ServeHTTP(0xc001026000, 0x27c3370, 0xc000e3c7e0, 0xc0001d1400)
	net/http/server.go:2069 +0x44
net/http.serverHandler.ServeHTTP(0xc000649560, 0x27c3370, 0xc000e3c7e0, 0xc0001d1400)
	net/http/server.go:2887 +0xa3
net/http.(*conn).serve(0xc000645ea0, 0x27cc9f8, 0xc0001327c0)
	net/http/server.go:1952 +0x8cd
created by net/http.(*Server).Serve
	net/http/server.go:3013 +0x39b

## Your Environment

* Version used (`minio --version`):
* Server setup and configuration:
* Operating System and version (`uname -a`):
minio version RELEASE.2021-03-26T00-00-41Z

cmd:./minio server ./data --address ":9001"

### PR DESCRIPTION
**Pull request by harshavardhana**
## Description
fix: crash in single drive mode for lifecycle

## Motivation and Context
also, make sure to close the channel on the producer
side, not in a separate go-routine, this can lead
to races between a writer and a closer.

## How to test this PR?
fixes #12073

## Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Optimization (provides speedup with no functional changes)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [ ] Fixes a regression (If yes, please add `commit-id` or `PR #` here)
- [ ] Documentation updated
- [ ] Unit tests added/updated

### CODE REVIEW

**Comment by minio-trusted** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-s3.sh | :heavy_check_mark: |
| mint-erasure.sh | :heavy_check_mark: |
| mint-dist-erasure.sh | :heavy_check_mark: |
| mint-zoned.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-compress-encrypt-dist-erasure.sh | :x: [more...](#ce2fc9f3-1387-48a9-89f7-7a555aeed051) |
<a name="ce2fc9f3-1387-48a9-89f7-7a555aeed051"></a>
### 12077-9c62126/mint-compress-encrypt-dist-erasure.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-dev6.minio.io:32750
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 23d08fdffa7f:/mint/log /tmp/mint-logs'

(1/15) Running aws-sdk-go tests ... done in 1 seconds
(2/15) Running aws-sdk-java tests ... done in 2 seconds
(3/15) Running aws-sdk-php tests ... done in 42 seconds
(4/15) Running aws-sdk-ruby tests ... done in 4 seconds
(5/15) Running awscli tests ... FAILED in 31 seconds
{
  "name": "awscli",
  "duration": 2666,
  "function": "aws --endpoint-url http://minio-dev6.minio.io:32750 s3api copy-object --bucket awscli-mint-test-bucket-326 --key datafile-1-kB-copy --copy-source awscli-mint-test-bucket-326/datafile-1-kB\n",
  "status": "FAIL",
  "error": "Hash mismatch expected 084e1383b70fb0c51acc680fef370023, got ac57de7156d7fc25ac1a65f81fa3989b"
}
(5/15) Running healthcheck tests ... done in 0 seconds
(6/15) Running mc tests ... done in 48 seconds
(7/15) Running minio-dotnet tests ... done in 42 seconds
(8/15) Running minio-go tests ... FAILED in 2 minutes and 12 seconds
{
  "args": {},
  "duration": 239,
  "error": "At least one of the pre-conditions you specified did not hold",
  "function": "CopyObjectPart(destination, source)",
  "message": "CopyObjectPart call failed",
  "name": "minio-go: testUnencryptedToSSES3CopyObjectPart",
  "status": "FAIL"
}
(8/15) Running minio-java tests ... FAILED in 1 minutes and 32 seconds
{
  "name": "minio-java",
  "function": "copyObject()",
  "args": "[match etag]",
  "duration": 301,
  "status": "FAIL",
  "error": "error occurred\nErrorResponse(code = PreconditionFailed, message = At least one of the pre-conditions you specified did not hold, bucketName = minio-java-test-2o9n8k0, objectName = minio-java-test-kng3rn-copy, resource = /minio-java-test-2o9n8k0/minio-java-test-kng3rn-copy, requestId = 1676659FF66AE410, hostId = 24f20fcf-e78f-4e40-a2ee-68c8eeaf069a)\nrequest={method=PUT, url=http://minio-dev6.minio.io:32750/minio-java-test-2o9n8k0/minio-java-test-kng3rn-copy, headers=x-amz-copy-source-if-match: 71cff0a060f852067e443ad1e24ae26c-1\nx-amz-copy-source: /minio-java-test-3s2aglu/minio-java-test-kng3rn\nHost: minio-dev6.minio.io:32750\nAccept-Encoding: identity\nUser-Agent: MinIO (Linux; amd64) minio-java/8.0.3\nContent-MD5: 1B2M2Y8AsgTpgAmY7PhCfg==\nx-amz-content-sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855\nx-amz-date: 20210416T170733Z\nAuthorization: AWS4-HMAC-SHA256 Credential=*REDACTED*/20210416/us-east-1/s3/aws4_request, SignedHeaders=content-md5;host;x-amz-content-sha256;x-amz-copy-source;x-amz-copy-source-if-match;x-amz-date, Signature=*REDACTED*\n}\nresponse={code=412, headers=Accept-Ranges: bytes\nContent-Length: 416\nContent-Security-Policy: block-all-mixed-content\nContent-Type: application/xml\nETag: \"71cff0a060f852067e443ad1e24ae26c\"\nLast-Modified: Fri, 16 Apr 2021 17:07:33 GMT\nServer: MinIO\nVary: Origin\nX-Amz-Request-Id: 1676659FF66AE410\nX-Xss-Protection: 1; mode=block\nDate: Fri, 16 Apr 2021 17:07:33 GMT\n}\n >>> [io.minio.MinioClient.execute(MinioClient.java:775), io.minio.MinioClient.execute(MinioClient.java:563), io.minio.MinioClient.executePut(MinioClient.java:904), io.minio.MinioClient.copyObject(MinioClient.java:1232), FunctionalTest.testCopyObjectMatchETag(FunctionalTest.java:1850), FunctionalTest.copyObject(FunctionalTest.java:2016), FunctionalTest.runObjectTests(FunctionalTest.java:3757), FunctionalTest.runTests(FunctionalTest.java:3783), FunctionalTest.main(FunctionalTest.java:3927)]"
}
(8/15) Running minio-js tests ... done in 52 seconds
(9/15) Running minio-py tests ... done in 3 minutes and 8 seconds
(10/15) Running s3cmd tests ... FAILED in 6 seconds
{
  "name": "s3cmd",
  "duration": "3691",
  "function": "test_put_object_multipart",
  "status": "FAIL",
  "error": "WARNING: MD5 Sums don't match!\nWARNING: Retrying upload of /mint/data/datafile-65-MB\nWARNING: MD5 Sums don't match!\nWARNING: Retrying upload of /mint/data/datafile-65-MB\nWARNING: MD5 Sums don't match!\nWARNING: Retrying upload of /mint/data/datafile-65-MB\nWARNING: MD5 Sums don't match!\nWARNING: Retrying upload of /mint/data/datafile-65-MB\nWARNING: MD5 Sums don't match!\nWARNING: Retrying upload of /mint/data/datafile-65-MB\nWARNING: MD5 Sums don't match!\nWARNING: Too many failures. Giving up on '/mint/data/datafile-65-MB'\nERROR: \nUpload of '/mint/data/datafile-65-MB' part 1 failed. Use\n  /usr/local/bin/s3cmd abortmp s3://s3cmd-test-bucket-18981/s3cmd-test-object-31560 5b1b50fa-617e-44ea-b1f6-64e6ab297d52\nto abort the upload, or\n  /usr/local/bin/s3cmd --upload-id 5b1b50fa-617e-44ea-b1f6-64e6ab297d52 put ...\nto continue the upload.\nERROR: Upload of '/mint/data/datafile-65-MB' failed too many times (Last reason: )"
}
(10/15) Running s3select tests ... done in 6 seconds
(11/15) Running security tests ... done in 0 seconds

Executed 11 out of 15 tests successfully.
```
Deleting image on docker hub
Deleting image locally

File: cmd/bucket-lifecycle.go [hunk 1]
```diff
@@ -76,6 +76,8 @@ type expiryState struct {
 
 func (es *expiryState) queueExpiryTask(oi ObjectInfo, rmVersion bool) {
 	select {
+	case <-GlobalContext.Done():
+		close(es.expiryCh)
```
Comment (poornas) [inline cmd/bucket-lifecycle.go]: suggest just returning on GlobalContext.Done() and leaving the go routine that closes the expiryCh in newExpiryState as is. Otherwise, this will result in panic of closing an already closed channel

**Review by poornas — CHANGES_REQUESTED** [review]

File: cmd/bucket-lifecycle.go (hunk 1 above)
Comment (harshavardhana) [reply cmd/bucket-lifecycle.go]: Yes return is missing here.

**Review by poornas — APPROVED** [review]
LGTM

**Comment by minio-trusted** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-s3.sh | :heavy_check_mark: |
| mint-erasure.sh | :heavy_check_mark: |
| mint-dist-erasure.sh | :heavy_check_mark: |
| mint-zoned.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :x: [more...](#17b14da2-be9b-4bc3-a708-dcb008f85ee4) |
| mint-compress-encrypt-dist-erasure.sh | :x: [more...](#4aa6621a-0ed9-4ca5-becb-7b74aa513be8) |
<a name="17b14da2-be9b-4bc3-a708-dcb008f85ee4"></a>
### 12077-e3aab53/mint-large-bucket.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-dev8.minio.io:32420
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 649436e54bd5:/mint/log /tmp/mint-logs'

(1/15) Running aws-sdk-go tests ... done in 1 seconds
(2/15) Running aws-sdk-java tests ... done in 2 seconds
(3/15) Running aws-sdk-php tests ... done in 42 seconds
(4/15) Running aws-sdk-ruby tests ... done in 5 seconds
(5/15) Running awscli tests ... done in 2 minutes and 15 seconds
(6/15) Running healthcheck tests ... done in 0 seconds
(7/15) Running mc tests ... FAILED in 20 seconds
{
  "name": "mc",
  "duration": "10486",
  "function": "test_get_object_multipart",
  "status": "FAIL",
  "error": "/mint/run/core/mc/mc --config-dir /tmp/.mc-21592 --quiet --no-color cp /mint/data/datafile-65-MB myminio/mc-test-bucket-19940/mc-test-object-13201  >>> \n`/mint/data/datafile-65-MB` -> `myminio/mc-test-bucket-19940/mc-test-object-13201`\nmc: <ERROR> Failed to copy `/mint/data/datafile-65-MB`. Object does not exist\nTotal: 0 B, Transferred: 65.00 MiB, Speed: 6.31 MiB/s"
}
(7/15) Running minio-dotnet tests ... done in 47 seconds
(8/15) Running minio-go tests ... done in 2 minutes and 4 seconds
(9/15) Running minio-java tests ... done in 1 minutes and 5 seconds
(10/15) Running minio-js tests ... done in 52 seconds
(11/15) Running minio-py tests ... done in 2 minutes and 35 seconds
(12/15) Running s3cmd tests ... done in 21 seconds
(13/15) Running s3select tests ... done in 4 seconds
(14/15) Running security tests ... done in 1 seconds

Executed 14 out of 15 tests successfully.
```
<a name="4aa6621a-0ed9-4ca5-becb-7b74aa513be8"></a>
### 12077-e3aab53/mint-compress-encrypt-dist-erasure.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-c3.minio.io:30031
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 2b2175fabc2a:/mint/log /tmp/mint-logs'

(1/15) Running aws-sdk-go tests ... done in 1 seconds
(2/15) Running aws-sdk-java tests ... done in 2 seconds
(3/15) Running aws-sdk-php tests ... done in 43 seconds
(4/15) Running aws-sdk-ruby tests ... done in 3 seconds
(5/15) Running awscli tests ... FAILED in 32 seconds
{
  "name": "awscli",
  "duration": 2906,
  "function": "aws --endpoint-url http://minio-c3.minio.io:30031 s3api copy-object --bucket awscli-mint-test-bucket-22269 --key datafile-1-kB-copy --copy-source awscli-mint-test-bucket-22269/datafile-1-kB\n",
  "status": "FAIL",
  "error": "Hash mismatch expected 084e1383b70fb0c51acc680fef370023, got ac57de7156d7fc25ac1a65f81fa3989b"
}
(5/15) Running healthcheck tests ... done in 0 seconds
(6/15) Running mc tests ... done in 48 seconds
(7/15) Running minio-dotnet tests ... done in 39 seconds
(8/15) Running minio-go tests ... FAILED in 1 minutes and 51 seconds
{
  "args": {},
  "duration": 388,
  "error": "At least one of the pre-conditions you specified did not hold",
  "function": "CopyObjectPart(destination, source)",
  "message": "CopyObjectPart call failed",
  "name": "minio-go: testUnencryptedToSSES3CopyObjectPart",
  "status": "FAIL"
}
(8/15) Running minio-java tests ... FAILED in 1 minutes and 36 seconds
{
  "name": "minio-java",
  "function": "copyObject()",
  "args": "[match etag]",
  "duration": 159,
  "status": "FAIL",
  "error": "error occurred\nErrorResponse(code = PreconditionFailed, message = At least one of the pre-conditions you specified did not hold, bucketName = minio-java-test-ua2rsn, objectName = minio-java-test-efp0b0-copy, resource = /minio-java-test-ua2rsn/minio-java-test-efp0b0-copy, requestId = 16766ECAEFF2643E, hostId = e9b64d13-5826-4e07-8d2b-698218744038)\nrequest={method=PUT, url=http://minio-c3.minio.io:30031/minio-java-test-ua2rsn/minio-java-test-efp0b0-copy, headers=x-amz-copy-source-if-match: 71cff0a060f852067e443ad1e24ae26c-1\nx-amz-copy-source: /minio-java-test-q2t1pt/minio-java-test-efp0b0\nHost: minio-c3.minio.io:30031\nAccept-Encoding: identity\nUser-Agent: MinIO (Linux; amd64) minio-java/8.0.3\nContent-MD5: 1B2M2Y8AsgTpgAmY7PhCfg==\nx-amz-content-sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855\nx-amz-date: 20210416T195533Z\nAuthorization: AWS4-HMAC-SHA256 Credential=*REDACTED*/20210416/us-east-1/s3/aws4_request, SignedHeaders=content-md5;host;x-amz-content-sha256;x-amz-copy-source;x-amz-copy-source-if-match;x-amz-date, Signature=*REDACTED*\n}\nresponse={code=412, headers=Accept-Ranges: bytes\nContent-Length: 414\nContent-Security-Policy: block-all-mixed-content\nContent-Type: application/xml\nETag: \"71cff0a060f852067e443ad1e24ae26c\"\nLast-Modified: Fri, 16 Apr 2021 19:55:33 GMT\nServer: MinIO\nVary: Origin\nX-Amz-Request-Id: 16766ECAEFF2643E\nX-Xss-Protection: 1; mode=block\nDate: Fri, 16 Apr 2021 19:55:33 GMT\n}\n >>> [io.minio.MinioClient.execute(MinioClient.java:775), io.minio.MinioClient.execute(MinioClient.java:563), io.minio.MinioClient.executePut(MinioClient.java:904), io.minio.MinioClient.copyObject(MinioClient.java:1232), FunctionalTest.testCopyObjectMatchETag(FunctionalTest.java:1850), FunctionalTest.copyObject(FunctionalTest.java:2016), FunctionalTest.runObjectTests(FunctionalTest.java:3757), FunctionalTest.runTests(FunctionalTest.java:3783), FunctionalTest.main(FunctionalTest.java:3927)]"
}
(8/15) Running minio-js tests ... done in 51 seconds
(9/15) Running minio-py tests ... done in 2 minutes and 53 seconds
(10/15) Running s3cmd tests ... FAILED in 5 seconds
{
  "name": "s3cmd",
  "duration": "2730",
  "function": "test_put_object_multipart",
  "status": "FAIL",
  "error": "WARNING: MD5 Sums don't match!\nWARNING: Retrying upload of /mint/data/datafile-65-MB\nWARNING: MD5 Sums don't match!\nWARNING: Retrying upload of /mint/data/datafile-65-MB\nWARNING: MD5 Sums don't match!\nWARNING: Retrying upload of /mint/data/datafile-65-MB\nWARNING: MD5 Sums don't match!\nWARNING: Retrying upload of /mint/data/datafile-65-MB\nWARNING: MD5 Sums don't match!\nWARNING: Retrying upload of /mint/data/datafile-65-MB\nWARNING: MD5 Sums don't match!\nWARNING: Too many failures. Giving up on '/mint/data/datafile-65-MB'\nERROR: \nUpload of '/mint/data/datafile-65-MB' part 1 failed. Use\n  /usr/local/bin/s3cmd abortmp s3://s3cmd-test-bucket-1244/s3cmd-test-object-1609 c1969c1a-79ca-4026-a61d-770fc0a53e7f\nto abort the upload, or\n  /usr/local/bin/s3cmd --upload-id c1969c1a-79ca-4026-a61d-770fc0a53e7f put ...\nto continue the upload.\nERROR: Upload of '/mint/data/datafile-65-MB' failed too many times (Last reason: )"
}
(10/15) Running s3select tests ... done in 5 seconds
(11/15) Running security tests ... done in 0 seconds

Executed 11 out of 15 tests successfully.
```
Deleting image on docker hub
Deleting image locally
