### PR TITLE
fix: LDAP derivative accounts parentUser validation is not needed

### LINKED ISSUE #9435: aws cli not working with ldap backed assume-role
I have setup minio using the LDAP settings on https://github.com/minio/minio/blob/master/docs/sts/ldap.md with a AD backend. The example `ldap.go` program is working and returning a valid credentials struct but i cannot get it to work using the aws cli

## Expected Behavior
I am expecting not to get an error whe running 
```
aws --profile minio --endpoint-url http://localhost:9001 sts assume-role --policy '{"Version":"2012-10-17","Statement":[{"Sid":"Stmt1","Effect":"Allow","Action":"s3:*","Resource":"arn:aws:s3:::*"}]}' --role-arn arn:xxx:xxx:xxx:xxxx --role-session-name anything
```
## Current Behavior
```
 aws --profile minio --endpoint-url http://localhost:9001 sts assume-role --policy '{"Version":"2012-10-17","Statement":[{"Sid":"Stmt1","Effect":"Allow","Action":"s3:*","Resource":"arn:aws:s3:::*"}]}' --role-arn arn:xxx:xxx:xxx:xxxx --role-session-name anything

An error occurred (MalformedPolicyDocument) when calling the AssumeRole operation: The request was rejected because the policy document was malformed.
```

## Steps to Reproduce (for bugs)

1. setup minio with LDAP STS 
```
export MINIO_IDENTITY_LDAP_SERVER_ADDR=ad1.example.com:636
export MINIO_IDENTITY_LDAP_USERNAME_SEARCH_FILTER='(sAMAccountName=%s)'
export MINIO_IDENTITY_LDAP_GROUP_SEARCH_BASE_DN="dc=example,dc=com"
export MINIO_IDENTITY_LDAP_GROUP_SEARCH_FILTER='(&(objectclass=group)(member=%s))'
export MINIO_IDENTITY_LDAP_GROUP_NAME_ATTRIBUTE=cn
export MINIO_IDENTITY_LDAP_STS_EXPIRY=60h
export MINIO_IDENTITY_LDAP_TLS_SKIP_VERIFY=on
```
2. start minio
```
/usr/bin/minio server --address :9001 /data/archive
```

3. test to confirm working using the `ldap.go` code from https://github.com/minio/minio/blob/master/docs/sts/ldap.go
4. setup aws profile
```
aws configure --profile minio
AWS Access Key ID [****************name]: myusername
AWS Secret Access Key [****************word]: mypassword
Default region name [us-east-1]: 
Default output format [None]: 
```
5. Run example aws sts asume-role command
```
aws --profile minio --endpoint-url http://localhost:9001 sts assume-role --policy '{"Version":"2012-10-17","Statement":[{"Sid":"Stmt1","Effect":"Allow","Action":"s3:*","Resource":"arn:aws:s3:::*"}]}' --role-arn arn:xxx:xxx:xxx:xxxx --role-session-name anything
``` 
Also tried using boto3 in a python script and get the same error.
```
#! /usr/bin/env python

import boto3
from getpass import getpass

username=input('LDAP username: ')
password=getpass('LDAP Password: ')
endpoint="http://minio.localhost:9001"

sts_client = boto3.client(
        'sts',
        aws_access_key_id=username,
        aws_secret_access_key=password,
        endpoint_url=endpoint,
        verify=False
        )


policy_document = """
{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Sid": "",
      "Action": "s3:*",
      "Effect": "Allow",
      "Resource": "arn:aws:s3:::*/*"
    }
  ]
}
"""

credentials = sts_client.assume_role(
    RoleArn='arn:xxx:xxx:xxx:xxxx',
    RoleSessionName='anything',
    #Policy=policy_document,
)
print(credentials)

s3_resource=boto3.resource(
    's3',
    aws_access_key_id=credentials['AccessKeyId'],
    aws_secret_access_key=credentials['SecretAccessKey'],
    aws_session_token=credentials['SessionToken'],
)

for bucket in s3_resource.buckets.all():
    print(bucket.name)
```
## Context

I am trying to do this so that staff within our business can access files in minio using their corporate credentials. This is both for convenience to take advantage of all the predefined staff groups and for audit purposes.

## Your Environment

* Version used (`minio version`): minio version RELEASE.2020-04-15T19-42-18Z
* Server type and version: CentOS release 6.10 (Final)
* Operating System and version (`uname -a`): Linux localhost.localdomain 2.6.32-754.14.2.el6.x86_64 #1 SMP Tue May 14 19:35:42 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

### PR DESCRIPTION
**Pull request by harshavardhana**
## Description
fix: LDAP derivative accounts parentUser validation is not needed

## Motivation and Context
fixes #9435

## How to test this PR?
You need an LDAP local setup
```sh
#!/bin/bash

export MINIO_ACCESS_KEY=minio
export MINIO_SECRET_KEY=minio123
export MINIO_IDENTITY_LDAP_SERVER_ADDR='localhost:389'
export MINIO_IDENTITY_LDAP_USERNAME_FORMAT='uid=%s,dc=example,dc=org'
export MINIO_IDENTITY_LDAP_USERNAME_SEARCH_FILTER='(|(objectclass=posixAccount)(uid=%s))'
export MINIO_IDENTITY_LDAP_TLS_SKIP_VERIFY=on
export MINIO_IDENTITY_LDAP_SERVER_INSECURE=on
minio server ~/test
```

## Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [x] Fixes a regression yes introduced in #9451
- [ ] Documentation needed
- [ ] Unit tests needed
- [ ] Functional tests needed (If yes, add [mint](https://github.com/minio/mint) PR # here: )

### CODE REVIEW

**Review by Alevsk — APPROVED** [review]

**Comment by minio-trusted** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-xl.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-dist-xl.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-gateway-s3.sh | :x: [more...](#c07e89b5-c5ae-407f-9d49-bac07d6cd775) |
| mint-gateway-azure.sh | :x: [more...](#e4320c01-da33-4bb9-91b7-665c224ff2ac) |
<a name="e4320c01-da33-4bb9-91b7-665c224ff2ac"></a>
### 9573-966a0d1/mint-gateway-azure.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-dev3.minio.io:32331
ACCESS_KEY:           minioazure
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp ca06b4981cfb:/mint/log /tmp/mint-logs'

(1/15) Running aws-sdk-go tests ... done in 8 seconds
(2/15) Running aws-sdk-java tests ... done in 1 seconds
(3/15) Running aws-sdk-php tests ... done in 5 minutes and 9 seconds
(4/15) Running aws-sdk-ruby tests ... done in 15 seconds
(5/15) Running awscli tests ... done in 2 minutes and 40 seconds
(6/15) Running healthcheck tests ... done in 0 seconds
(7/15) Running mc tests ... done in 3 minutes and 1 seconds
(8/15) Running minio-dotnet tests ... done in 1 minutes and 27 seconds
(9/15) Running minio-go tests ... done in 3 minutes and 57 seconds
(10/15) Running minio-java tests ... done in 27 minutes and 17 seconds
(11/15) Running minio-js tests ... done in 3 minutes and 42 seconds
(12/15) Running minio-py tests ... done in 9 minutes and 32 seconds
(13/15) Running s3cmd tests ... FAILED in 41 seconds
{
  "name": "s3cmd",
  "duration": "1794",
  "function": "test_copy_object",
  "status": "FAIL",
  "error": ""
}
(13/15) Running s3select tests ... done in 21 seconds
(14/15) Running security tests ... done in 0 seconds

Executed 14 out of 15 tests successfully.
```
<a name="c07e89b5-c5ae-407f-9d49-bac07d6cd775"></a>
### 9573-966a0d1/mint-gateway-s3.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-dev4.minio.io:30139
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 964c762a5dc1:/mint/log /tmp/mint-logs'

(1/15) Running aws-sdk-go tests ... done in 0 seconds
(2/15) Running aws-sdk-java tests ... done in 1 seconds
(3/15) Running aws-sdk-php tests ... done in 42 seconds
(4/15) Running aws-sdk-ruby tests ... done in 1 seconds
(5/15) Running awscli tests ... FAILED in 21 seconds
{
  "name": "awscli",
  "duration": 4455,
  "function": "aws --endpoint-url http://minio-dev4.minio.io:30139 s3api get-object --bucket awscli-mint-test-bucket-4790 --key awscli-mint-test-bucket-4790-object /tmp/datafile-0-b\n",
  "status": "FAIL",
  "error": "Etag mismatch for multipart 0 byte object"
}
(5/15) Running healthcheck tests ... done in 0 seconds
(6/15) Running mc tests ... done in 18 seconds
(7/15) Running minio-dotnet tests ... done in 28 seconds
(8/15) Running minio-go tests ... done in 27 seconds
(9/15) Running minio-java tests ... done in 33 seconds
(10/15) Running minio-js tests ... done in 41 seconds
(11/15) Running minio-py tests ... done in 1 minutes and 1 seconds
(12/15) Running s3cmd tests ... done in 1 minutes and 1 seconds
(13/15) Running s3select tests ... done in 1 seconds
(14/15) Running security tests ... done in 0 seconds

Executed 14 out of 15 tests successfully.
```
Deleting image on docker hub
Deleting image locally

File: cmd/iam.go [hunk 1]
```diff
@@ -1023,9 +1023,15 @@ func (sys *IAMSys) GetUser(accessKey string) (cred auth.Credentials, ok bool) {
...
 	cred, ok = sys.iamUsersMap[accessKey]
 	if ok && cred.IsValid() {
-		if cred.ParentUser != "" {
+		if cred.ParentUser != "" && sys.usersSysType == MinIOUsersSysType {
 			_, ok = sys.iamUsersMap[cred.ParentUser]
 		}
+		// for LDAP service accounts with ParentUser set
+		// we have no way to validate, either because user
+		// doesn't need an explicit policy as it can come
+		// automatically from a group. We are save to ignore
```
Comment (Alevsk) [inline cmd/iam.go]:
```suggestion
		// automatically from a group. We are safe to ignore
```

**Comment by minio-trusted** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-xl.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-dist-xl.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-gateway-s3.sh | :x: [more...](#def2bc15-3682-4749-80ce-87498a261287) |
| mint-gateway-azure.sh | :x: [more...](#32b0ca94-4351-4ee0-9d4d-38fad4905fe0) |
<a name="32b0ca94-4351-4ee0-9d4d-38fad4905fe0"></a>
### 9573-486732f/mint-gateway-azure.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-dev4.minio.io:32183
ACCESS_KEY:           minioazure
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp ec57a5e41b65:/mint/log /tmp/mint-logs'

(1/15) Running aws-sdk-go tests ... done in 7 seconds
(2/15) Running aws-sdk-java tests ... done in 2 seconds
(3/15) Running aws-sdk-php tests ... done in 5 minutes and 9 seconds
(4/15) Running aws-sdk-ruby tests ... done in 16 seconds
(5/15) Running awscli tests ... done in 2 minutes and 40 seconds
(6/15) Running healthcheck tests ... done in 1 seconds
(7/15) Running mc tests ... done in 3 minutes and 1 seconds
(8/15) Running minio-dotnet tests ... done in 1 minutes and 20 seconds
(9/15) Running minio-go tests ... done in 3 minutes and 44 seconds
(10/15) Running minio-java tests ... done in 26 minutes and 35 seconds
(11/15) Running minio-js tests ... done in 2 minutes and 45 seconds
(12/15) Running minio-py tests ... done in 9 minutes and 31 seconds
(13/15) Running s3cmd tests ... FAILED in 0 seconds
{
  "name": "s3cmd",
  "duration": "401",
  "function": "test_make_bucket",
  "status": "FAIL",
  "error": "ERROR: S3 error: 409 (BucketAlreadyOwnedByYou): Your previous request to create the named bucket succeeded and you already own it."
}
(13/15) Running s3select tests ... done in 20 seconds
(14/15) Running security tests ... done in 0 seconds

Executed 14 out of 15 tests successfully.
```
<a name="def2bc15-3682-4749-80ce-87498a261287"></a>
### 9573-486732f/mint-gateway-s3.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-c3.minio.io:30915
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 75b0a669854e:/mint/log /tmp/mint-logs'

(1/15) Running aws-sdk-go tests ... done in 1 seconds
(2/15) Running aws-sdk-java tests ... done in 1 seconds
(3/15) Running aws-sdk-php tests ... done in 41 seconds
(4/15) Running aws-sdk-ruby tests ... done in 2 seconds
(5/15) Running awscli tests ... FAILED in 20 seconds
{
  "name": "awscli",
  "duration": 4240,
  "function": "aws --endpoint-url http://minio-c3.minio.io:30915 s3api get-object --bucket awscli-mint-test-bucket-19069 --key awscli-mint-test-bucket-19069-object /tmp/datafile-0-b\n",
  "status": "FAIL",
  "error": "Etag mismatch for multipart 0 byte object"
}
(5/15) Running healthcheck tests ... done in 0 seconds
(6/15) Running mc tests ... done in 16 seconds
(7/15) Running minio-dotnet tests ... done in 29 seconds
(8/15) Running minio-go tests ... done in 23 seconds
(9/15) Running minio-java tests ... done in 35 seconds
(10/15) Running minio-js tests ... done in 33 seconds
(11/15) Running minio-py tests ... done in 1 minutes and 6 seconds
(12/15) Running s3cmd tests ... done in 1 minutes and 1 seconds
(13/15) Running s3select tests ... done in 0 seconds
(14/15) Running security tests ... done in 0 seconds

Executed 14 out of 15 tests successfully.
```
Deleting image on docker hub
Deleting image locally

File: cmd/iam.go [hunk 2]
```diff
@@ -1617,59 +1623,74 @@ func (sys *IAMSys) IsAllowedServiceAccount(args iampolicy.Args, parent string) b
...
+			groupsVal := args.Claims[ldapGroups]
+			if g, ok := groupsVal.([]interface{}); ok {
+				for _, eachG := range g {
+					if eachGStr, ok := eachG.(string); ok {
+						groups = append(groups, eachGStr)
+					}
 				}
 			}
-		} else {
-			return false
```
Comment (vadmeste) [inline cmd/iam.go:1637]: This `return false` is removed, could you explain why ?

File: cmd/iam.go [hunk 3]
```diff
@@ -1617,59 +1623,74 @@ func (sys *IAMSys) IsAllowedServiceAccount(args iampolicy.Args, parent string) b
...
 	// policies allow the request.
-	if userIface, ok := args.Claims[ldapUser]; ok {
-		var user string
-		if u, ok := userIface.(string); ok {
-			user = u
-		} else {
-			return false
-		}
+	if sys.usersSysType == LDAPUsersSysType {
+		if userIface, ok := args.Claims[ldapUser]; ok {
```
Comment (vadmeste) [inline cmd/iam.go:1627]: I think it is better to have a function isAllowedSTSForLdap() where it contains the code of this block

```
if sys.usersSysType == LDAPUsersSysType {
    return sys.isAllowedSTSForLdap()
}
```

**Review by vadmeste — COMMENTED** [review]
Some comments

**Comment by minio-trusted** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-xl.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-dist-xl.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-gateway-s3.sh | :x: [more...](#502f5ab7-2bad-4a89-8736-44e7c09542d9) |
| mint-gateway-azure.sh | :x: [more...](#47919472-0e07-436b-b5db-bb7ef3f5a2e7) |
<a name="502f5ab7-2bad-4a89-8736-44e7c09542d9"></a>
### 9573-04981fe/mint-gateway-s3.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-dev4.minio.io:30777
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp da5fc85ed441:/mint/log /tmp/mint-logs'

(1/15) Running aws-sdk-go tests ... done in 0 seconds
(2/15) Running aws-sdk-java tests ... done in 1 seconds
(3/15) Running aws-sdk-php tests ... done in 41 seconds
(4/15) Running aws-sdk-ruby tests ... done in 2 seconds
(5/15) Running awscli tests ... FAILED in 20 seconds
{
  "name": "awscli",
  "duration": 4158,
  "function": "aws --endpoint-url http://minio-dev4.minio.io:30777 s3api get-object --bucket awscli-mint-test-bucket-12579 --key awscli-mint-test-bucket-12579-object /tmp/datafile-0-b\n",
  "status": "FAIL",
  "error": "Etag mismatch for multipart 0 byte object"
}
(5/15) Running healthcheck tests ... done in 0 seconds
(6/15) Running mc tests ... done in 18 seconds
(7/15) Running minio-dotnet tests ... done in 28 seconds
(8/15) Running minio-go tests ... done in 30 seconds
(9/15) Running minio-java tests ... done in 24 seconds
(10/15) Running minio-js tests ... done in 33 seconds
(11/15) Running minio-py tests ... done in 1 minutes and 2 seconds
(12/15) Running s3cmd tests ... done in 1 minutes and 3 seconds
(13/15) Running s3select tests ... done in 2 seconds
(14/15) Running security tests ... done in 0 seconds

Executed 14 out of 15 tests successfully.
```
<a name="47919472-0e07-436b-b5db-bb7ef3f5a2e7"></a>
### 9573-04981fe/mint-gateway-azure.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-dev7.minio.io:32675
ACCESS_KEY:           minioazure
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 5fa81ca15cd9:/mint/log /tmp/mint-logs'

(1/15) Running aws-sdk-go tests ... done in 8 seconds
(2/15) Running aws-sdk-java tests ... done in 1 seconds
(3/15) Running aws-sdk-php tests ... done in 5 minutes and 8 seconds
(4/15) Running aws-sdk-ruby tests ... done in 17 seconds
(5/15) Running awscli tests ... done in 2 minutes and 53 seconds
(6/15) Running healthcheck tests ... done in 0 seconds
(7/15) Running mc tests ... done in 3 minutes and 47 seconds
(8/15) Running minio-dotnet tests ... done in 1 minutes and 23 seconds
(9/15) Running minio-go tests ... done in 3 minutes and 44 seconds
(10/15) Running minio-java tests ... done in 26 minutes and 47 seconds
(11/15) Running minio-js tests ... done in 2 minutes and 44 seconds
(12/15) Running minio-py tests ... done in 10 minutes and 5 seconds
(13/15) Running s3cmd tests ... FAILED in 55 seconds
{
  "name": "s3cmd",
  "duration": "2286",
  "function": "test_copy_object",
  "status": "FAIL",
  "error": ""
}
(13/15) Running s3select tests ... done in 21 seconds
(14/15) Running security tests ... done in 0 seconds

Executed 14 out of 15 tests successfully.
```
Deleting image on docker hub
Deleting image locally

File: cmd/iam.go (hunk 2 above)
Comment (harshavardhana) [reply cmd/iam.go:1637]: Groups are not mandatory @vadmeste

File: cmd/iam.go (hunk 3 above)
Comment (harshavardhana) [reply cmd/iam.go:1627]: Yes sure but that is not the purpose of this PR @vadmeste

**Review by vadmeste — APPROVED** [review]
LGTM
