### PR TITLE
Prevent weird messages from rpc lib on start (Fixes #3209):

### LINKED ISSUE #3209: [distributed] Weird messages when starting the server
```
minio2_1  | Created minio configuration file at /root/.minio
minio4_1  | 2016/11/08 18:58:36 method SendEvent has wrong number of ins: 2
minio4_1  | 2016/11/08 18:58:36 method UpdateBucketListener has wrong number of ins: 2
minio4_1  | 2016/11/08 18:58:36 method UpdateBucketNotification has wrong number of ins: 2
minio4_1  | 2016/11/08 18:58:36 method UpdateBucketPolicy has wrong number of ins: 2
minio1_1  | 2016/11/08 18:58:36 method SendEvent has wrong number of ins: 2
minio1_1  | 2016/11/08 18:58:36 method UpdateBucketListener has wrong number of ins: 2
minio1_1  | 2016/11/08 18:58:36 method UpdateBucketNotification has wrong number of ins: 2
minio1_1  | 2016/11/08 18:58:36 method UpdateBucketPolicy has wrong number of ins: 2
minio3_1  | 2016/11/08 18:58:37 method SendEvent has wrong number of ins: 2
minio3_1  | 2016/11/08 18:58:37 method UpdateBucketListener has wrong number of ins: 2
minio3_1  | 2016/11/08 18:58:37 method UpdateBucketNotification has wrong number of ins: 2
minio3_1  | 2016/11/08 18:58:37 method UpdateBucketPolicy has wrong number of ins: 2
minio1_1  | Initializing data volume. Waiting for minimum 3 servers to come online.
minio2_1  | 2016/11/08 18:58:37 method SendEvent has wrong number of ins: 2
minio2_1  | 2016/11/08 18:58:37 method UpdateBucketListener has wrong number of ins: 2
minio2_1  | 2016/11/08 18:58:37 method UpdateBucketNotification has wrong number of ins: 2
minio2_1  | 2016/11/08 18:58:37 method UpdateBucketPolicy has wrong number of ins: 2
```

```
   298			// Method needs three ins: receiver, *args, *reply.
   299			if mtype.NumIn() != 3 {
   300				if reportErr {
   301					log.Println("method", mname, "has wrong number of ins:", mtype.NumIn())
   302				}
   303				continue
   304			}
```

## Expected Behavior
RPC internal messages shouldn't be printed or fixed. 

## Current Behavior
Prints unknown messages without much context.

## Possible Solution
Fix the possible cause reported by RPC.

## Steps to Reproduce (for bugs)
Just docker `docker-compose up` 

## Context
Logging should be controlled and at any point shouldn't be printing.

### PR DESCRIPTION
**Pull request by donatello**
## Description

This is done by not making the methods of the BucketMetaState interface
as methods (via type nesting) on the type implementing
RPCs (s3PeerAPIHandlers).

## Motivation and Context

Fix for https://github.com/minio/minio/issues/3209

## How Has This Been Tested?

Existing unit tests pass. Offending message are no longer printed at startup.

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

File: cmd/s3-peer-router.go [hunk 1]
```diff
@@ -27,7 +27,7 @@ const (
 )
 
 type s3PeerAPIHandlers struct {
-	*localBMS
+	bms *localBMS
```
Comment (harshavardhana) [inline cmd/s3-peer-router.go]: the right way is to use the interface itself as part of the struct rather than the `*localBMS`

Comment (harshavardhana) [reply cmd/s3-peer-router.go]: Like how we use 'io.Reader' use here 

```
bms BucketMetaState
```

Comment (donatello) [reply cmd/s3-peer-router.go]: Fixed.

**Review by harshavardhana — APPROVED** [review]

**Comment by fwessels** [comment]
LGTM
