### PR TITLE
Fix free drive space calculation in XL mode

### LINKED ISSUE #2913: Show effective drive capacity
For XL and Distributed we should show the effective capacity (as compared to the 'gross' capacity). Thus in the case below it should 10.8 (or 11) TiB

```
Initializing data volume for the first time.
[01/04] 172.31.13.67:/mnt/distr - 5.4 TiB online
[02/04] 172.31.13.66:/mnt/distr - 5.4 TiB online
[03/04] 172.31.13.69:/mnt/distr - 5.4 TiB online
[04/04] 172.31.13.68:/mnt/distr - 5.4 TiB online

Endpoint:  http://172.31.13.67:9000  http://127.0.0.1:9000
AccessKey: 9OE9RNWW2PMU5X5A3WHH 
SecretKey: XVjlSlQ/JeLOA7k4Y2zwgNOhnTflirIm++bqgZHb 
Region:    us-east-1
SQS ARNs:  <none>

Browser Access:
   http://172.31.13.67:9000  http://127.0.0.1:9000

Command-line Access: https://docs.minio.io/docs/minio-client-quickstart-guide
   $ mc config host add myminio http://172.31.13.67:9000 9OE9RNWW2PMU5X5A3WHH XVjlSlQ/JeLOA7k4Y2zwgNOhnTflirIm++bqgZHb

Object API (Amazon S3 compatible):
   Go:         https://docs.minio.io/docs/golang-client-quickstart-guide
   Java:       https://docs.minio.io/docs/java-client-quickstart-guide
   Python:     https://docs.minio.io/docs/python-client-quickstart-guide
   JavaScript: https://docs.minio.io/docs/javascript-client-quickstart-guide

Drive Capacity: 21 TiB Free
Status:         4 Online, 0 Offline. We can withstand [2] more drive failure(s).
```

### PR DESCRIPTION
**Pull request by vadmeste**
Fixes #2913

### CODE REVIEW

File: cmd/server-startup-msg.go [hunk 1]
```diff
@@ -124,7 +124,13 @@ func printObjectAPIMsg() {
 
 // Get formatted disk/storage info message.
 func getStorageInfoMsg(storageInfo StorageInfo) string {
-	msg := fmt.Sprintf("%s %s Free", colorBlue("Drive Capacity:"), humanize.IBytes(uint64(storageInfo.Free)))
+	freeSpace := uint64(storageInfo.Free)
+	totalSpace := uint64(storageInfo.Total)
+	if storageInfo.Backend.Type == XL {
+		freeSpace /= 2
+		totalSpace /= 2
+	}
```
Comment (harshavardhana) [inline cmd/server-startup-msg.go:132]: Add a test case to validate this..
