### PR TITLE
fix: Re-use TCP connections for Kafka dials

### LINKED ISSUE #18857: isActive check on Kafka event target can consume ephemeral port range
## Expected Behavior

The `isActive` check in the Kafka event target should not consume a new ephemeral port on each check. These ports then become unavailable for four minutes while in the `TIME_WAIT` state.

## Current Behavior

The `isActive` check (more specifically `pingBrokers` function) will open a new tcp connection to the Kafka server.
https://github.com/minio/minio/blob/f78d677ab68f8a4a9d508456d4d8d37be0416b75/internal/event/target/kafka.go#L190-L195

The `isActive` check is called for every message that is to be sent to Kafka. During a busy period this can result in 1000s of calls to this check. Each will start a new connection and consume a new ephemeral port. This can cause MinIO to exhaust the ephemeral port range on the host. At which point the `isActive` will fail because it cannot create any new connections, so it will return false even when Kafka is healthy and would have no issues receiving messages.

Using netstat on the MinIO while publishing events to a Kafka target shows the issue clearly.
```
netstat -an
Proto Recv-Q Send-Q Local Address           Foreign Address         State
tcp        0      0 127.0.0.1:4222          0.0.0.0:*               LISTEN
tcp        0      0 0.0.0.0:9090            0.0.0.0:*               LISTEN
tcp        0      0 0.0.0.0:9000            0.0.0.0:*               LISTEN
tcp        0      0 127.0.0.1:9000          0.0.0.0:*               LISTEN
tcp        0      0 10.73.90.200:51040      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:53128      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:9000       10.73.109.29:45272      ESTABLISHED
tcp        0      0 10.73.90.200:48034      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:47678      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:45036      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:9000       10.73.109.29:58348      ESTABLISHED
tcp        0      0 10.73.90.200:40386      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:50912      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:47510      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:43782      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:39624      10.73.93.145:9000       TIME_WAIT
tcp        0      0 10.73.90.200:41740      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:40736      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:44848      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:50400      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:44598      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:49548      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:46566      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:47600      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:41848      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:39640      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:40360      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:40268      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:39518      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:51180      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:50204      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:39504      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:43512      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:45208      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:48750      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:46140      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:48918      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:40740      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:48040      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:46156      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:45014      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:45060      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:49494      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:42364      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:41344      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:46480      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:50446      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:40590      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:41098      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:47904      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:40336      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:47470      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:48674      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:42608      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:43928      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:39956      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:50976      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:42024      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:50826      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:44032      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:39308      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:40358      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:44418      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:49972      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:43718      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:42628      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:39760      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:49268      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:45828      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:50316      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:50202      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:47354      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:50820      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:46646      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:42410      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:9000       10.73.109.29:34816      ESTABLISHED
tcp        0      0 10.73.90.200:39636      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:48178      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:42820      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:48412      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:44480      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:45290      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:49246      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:42678      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:43658      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:39368      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:43680      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:45746      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:42282      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:50338      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:49240      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:43326      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:50710      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:47392      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:48350      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:43564      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:46648      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:47220      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:46868      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:40260      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:42050      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:42802      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:48502      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:43820      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:40674      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:42780      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:45384      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:47920      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:49152      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:45692      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:39854      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:44356      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:50620      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:50782      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:45760      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:42528      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:51018      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:50508      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:44198      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:42198      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:50072      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:47586      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:47838      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:44760      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:42976      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:48400      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:39860      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:44132      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:46204      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:40922      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:47068      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:47608      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:9000       10.73.109.29:39596      ESTABLISHED
tcp        0      0 10.73.90.200:45080      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:48456      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:45712      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:46774      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:41052      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:41754      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:49866      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:44252      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:41084      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:47846      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:44128      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:49802      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:48292      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:41868      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:47448      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:39600      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:47240      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:41816      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:46000      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:44796      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:45386      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:40190      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:9000       10.73.109.29:41578      ESTABLISHED
tcp        0      0 10.73.90.200:44070      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:41478      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:41566      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:49444      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:48810      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:45598      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:44428      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:43284      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:48014      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:41538      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:49020      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:41864      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:39522      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:50722      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:44828      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:40792      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:48168      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:41906      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:51164      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:44430      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:43706      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:43298      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:50394      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:48776      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:50776      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:40468      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:39586      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:42968      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:45952      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:45340      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:50092      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:43712      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:48836      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:45520      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:42456      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:45736      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:43644      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:46930      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:39712      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:43340      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:47712      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:43260      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:51090      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:46298      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:40398      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:39486      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:39648      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:44380      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:44716      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:49122      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:40662      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:49408      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:44152      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:47780      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:49436      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:43884      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:49370      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:43138      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:48536      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:40288      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:48132      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:40414      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:41866      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:44996      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:50484      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:50318      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:44818      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:46562      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:47188      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:45904      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:47736      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:41186      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:42044      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:42746      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:42436      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:47332      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:46168      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:50156      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:45972      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:49132      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:9000       10.73.109.29:34190      ESTABLISHED
tcp        0      0 10.73.90.200:42586      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:45558      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:41178      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:46776      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:46134      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:50598      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:48520      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:40472      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:50618      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:50926      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:46794      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:47560      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:49066      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:39732      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:50824      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:44328      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:39376      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:47084      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:44514      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:47706      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:46688      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:50758      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:42048      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:42444      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:50960      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:42432      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:47444      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:43336      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:50712      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:50816      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:39688      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:48250      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:46266      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:44820      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:49714      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:40166      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:49064      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:44798      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:48054      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:43098      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:45514      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:51228      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:9000       10.73.109.29:58968      ESTABLISHED
tcp        0      0 10.73.90.200:9000       10.73.109.29:57802      ESTABLISHED
tcp        0      0 10.73.90.200:39394      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:50330      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:43390      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:48314      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:42688      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:41182      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:48158      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:42580      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:40444      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:41252      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:41216      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:41080      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:49698      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:49638      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:40174      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:39774      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:49920      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:43468      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:44478      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:45046      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:49452      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:40310      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:50866      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:39920      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:44276      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:50676      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:43046      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:40680      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:42674      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:50900      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:45622      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:9000       10.73.109.29:59290      ESTABLISHED
tcp        0      0 10.73.90.200:44422      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:39966      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:39524      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:48392      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:44482      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:39604      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:45916      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:47540      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:46326      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:47414      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:50906      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:44456      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:9000       10.73.109.29:37656      ESTABLISHED
tcp        0      0 10.73.90.200:49854      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:42848      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:41450      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:50076      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:48792      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:48234      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:45362      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:50980      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:49900      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:41420      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:47012      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:50748      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:45772      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:40628      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:49464      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:48748      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:41184      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:47968      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:39450      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:39644      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:39422      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:46400      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:40404      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:42686      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:44698      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:43474      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:40534      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:46666      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:48908      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:49358      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:47978      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:47520      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:45276      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:43240      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:50640      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:47410      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:43948      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:44284      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:45472      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:41394      10.73.110.207:9000      TIME_WAIT
tcp        0      0 10.73.90.200:46710      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:49880      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:47834      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:51050      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:42068      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:46754      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:50886      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:43206      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:50382      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:50608      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:41124      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:43446      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:48002      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:40276      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:50026      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:46062      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:48652      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:46834      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:39976      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:47622      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:46004      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:41326      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:49292      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:44962      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:43722      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:9000       10.73.109.29:39254      ESTABLISHED
tcp        0      0 10.73.90.200:49148      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:44490      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:42566      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:45564      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:41234      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:48324      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:41666      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:41778      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:49984      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:39570      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:49996      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:49192      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:43972      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:48244      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:50704      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:42308      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:45796      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:45522      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:45462      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:41386      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:42336      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:42756      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:48144      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:49694      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:43858      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:9000       10.73.109.29:40866      ESTABLISHED
tcp        0      0 10.73.90.200:50686      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:50266      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:43010      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:46902      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:40802      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:43224      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:48964      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:48730      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:9000       10.73.109.29:41608      ESTABLISHED
tcp        0      0 10.73.90.200:45322      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:45422      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:9000       10.73.109.29:56048      ESTABLISHED
tcp        0      0 10.73.90.200:46766      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:46532      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:41112      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:43936      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:40530      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:49334      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:49890      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:42022      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:45162      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:39998      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:41394      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:49368      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:40498      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:41596      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:40858      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:45282      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:50986      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:47434      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:41568      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:42764      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:44404      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:42812      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:41882      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:42060      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:48698      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:45830      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:39682      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:49158      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:50694      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:43920      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:42326      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:40094      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:42890      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:39602      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:42278      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:49134      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:47994      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:50368      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:43520      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:48784      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:46508      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:42314      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:39560      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:40156      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:47496      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:41852      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:43952      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:47922      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:48150      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:50194      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:42500      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:50594      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:48372      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:41590      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:43476      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:44104      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:50834      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:39480      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:49508      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:50554      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:50984      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:40240      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:48272      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:50082      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:49500      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:49504      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:41902      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:42160      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:44866      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:45996      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:39322      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:48702      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:49606      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:41268      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:45000      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:41850      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:44742      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:41524      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:47848      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:46220      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:44680      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:45342      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:39546      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:50272      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:39964      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:48840      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:49174      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:39726      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:9000       10.73.109.29:41734      ESTABLISHED
tcp        0      0 10.73.90.200:48726      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:43994      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:46546      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:50134      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:46882      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:40732      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:40402      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:50246      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:49266      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:47836      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:41910      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:44754      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:42266      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:43660      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:50034      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:45596      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:42626      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:44072      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:49278      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:43058      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:44264      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:44944      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:43678      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:49658      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:40610      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:47314      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:41164      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:45860      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:48912      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:39878      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:40036      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:43922      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:49614      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:48508      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:44180      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:41456      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:45394      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:43274      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:50946      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:47500      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:42318      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:39736      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:50414      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:47612      10.73.93.145:9000       TIME_WAIT
tcp        0      0 10.73.90.200:43420      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:46730      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:41730      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:48892      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:50066      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:47426      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:40428      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:48740      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:9000       10.73.109.29:60924      ESTABLISHED
tcp        0      0 10.73.90.200:46796      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:42344      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:45498      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:41034      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:50566      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:49962      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:44012      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:9000       10.73.109.29:55074      ESTABLISHED
tcp        0      0 10.73.90.200:39594      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:43418      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:41436      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:49098      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:47884      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:47704      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:39638      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:39514      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:46072      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:42366      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:46150      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:49386      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:42370      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:49108      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:46350      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:41822      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:40666      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:49276      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:42990      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:48296      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:46482      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:9000       10.73.109.29:56266      ESTABLISHED
tcp        0      0 10.73.90.200:47590      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:46908      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:48128      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:39678      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:40974      10.73.116.21:9000       TIME_WAIT
tcp        0      0 10.73.90.200:44586      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:43876      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:47874      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:39848      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:9000       10.73.109.29:38854      ESTABLISHED
tcp        0      0 10.73.90.200:49006      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:40072      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:47798      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:48534      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:45892      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:43182      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:41314      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:40062      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:41270      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:44850      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:42814      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:45058      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:41458      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:50574      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:46812      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:44454      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:46448      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:46338      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:45662      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:44974      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:46412      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:43424      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:41370      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:40778      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:39592      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:9000       10.73.109.29:36548      ESTABLISHED
tcp        0      0 10.73.90.200:41074      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:45266      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:40766      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:40988      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:48858      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:49062      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:46120      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:50564      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:45574      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:44556      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:46278      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:44892      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:43552      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:44960      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:46392      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:50756      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:40916      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:47596      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:45378      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:48304      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:40384      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:43554      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:47992      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:43880      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:49870      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:49258      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:44214      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:45506      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:50486      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:48616      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:43858      10.73.93.145:9000       TIME_WAIT
tcp        0      0 10.73.90.200:48566      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:43408      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:45010      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:49868      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:42250      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:49948      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:42228      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:50488      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:40968      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:9000       10.73.109.29:41332      ESTABLISHED
tcp        0      0 10.73.90.200:43914      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:49812      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:41036      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:42506      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:45430      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:40956      10.73.116.21:9000       TIME_WAIT
tcp        0      0 10.73.90.200:44548      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:47046      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:50850      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:48766      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:40642      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:51158      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:48436      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:41334      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:49218      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:46806      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:40948      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:43078      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:45932      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:46128      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:48106      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:40676      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:47688      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:46564      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:42790      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:45214      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:48280      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:50146      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:49958      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:40570      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:47394      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:49236      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:44662      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:44950      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:9000       10.73.109.29:40184      ESTABLISHED
tcp        0      0 10.73.90.200:44316      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:46082      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:47366      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:47042      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:45708      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:44558      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:46224      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:44258      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:48206      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:43048      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:49078      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:46504      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:40424      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:45702      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:41892      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:46926      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:46084      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:48352      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:49290      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:39754      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:44256      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:46886      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:41762      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:47482      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:45630      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:45326      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:48834      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:50918      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:48484      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:50336      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:42152      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:42642      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:49322      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:47982      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:44922      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:48262      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:39564      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:45204      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:44062      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:41604      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:43180      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:51078      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:41830      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:9000       10.73.109.29:41978      ESTABLISHED
tcp        0      0 10.73.90.200:43126      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:48248      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:42702      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:50096      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:45562      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:44042      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:41928      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:48124      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:42312      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:45412      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:40748      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:49808      10.73.15.28:9092        TIME_WAIT
tcp        0      0 10.73.90.200:43208      10.73.15.28:9092        TIME_WAIT
```
In the above output `10.73.15.28:9092` is the address of my Kafka broker that is being hit by the is `isActive` check and makes up the vast majority of the addresses being used (the above output has actually been truncated, there could be a lot more).

## Possible Solution

Adapt the check so it does not open a new connection each time or perform the check less frequently.
Another possible solution is to remove the `isActive` check all together. Does this check add any value if it done for every message that is sent? If Kafka is down then you would find out about it and get an error anyway when attempting to send the message. It does not seem like the overhead of this connection test is worth it.

## Steps to Reproduce (for bugs)

1. Start MinIO and create a Kafka event target.
2. Configure this target to publish PUT/GET/DELETE on a bucket.
3. Perform lots of PUT, GET or DELETE operations on the bucket (say 300 per second).
4. Using `netstat -an` observe a large number of connections being opened. 
5. You may also observe errors like "not connected to target server/service" because the `isActive` check starts failing. But this is due to the ephemeral port range on the MinIO host exhausted not because Kafka is not available.

## Context

It limits the number of messages that can be sent to Kafka and causes failures in sending messages when there is no issue with the Kafka server. Running MinIO with the `isActive` check removed solves the issue and improves the reliability of sending messages to Kafka.

## Regression

No

## Your Environment

* Version used (`minio --version`): `RELEASE.2024-01-18T22-51-28Z`
* Operating System and version (`uname -a`): `Linux minio-preprod-ss-3-3 5.10.103-1.base.x86_64 #1 SMP Mon Mar 7 05:00:25 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux`

### PR DESCRIPTION
**Pull request by Praveenrajmani**
## Community Contribution License
All community contributions in this pull request are licensed to the project maintainers
under the terms of the [Apache 2 license](https://www.apache.org/licenses/LICENSE-2.0). 
By creating this pull request I represent that I have the right to license the 
contributions to the project maintainers under the Apache 2 license.

## Description
The connections should be properly closed on kafka target pings

## Motivation and Context
Fixes #18857

## How to test this PR?
- Configure bucket notifications + kafka
- Trigger events
- Check `netstat` if there are too many ESTABLISHED connections without being closed

## Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Optimization (provides speedup with no functional changes)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [ ] Fixes a regression (If yes, please add `commit-id` or `PR #` here)
- [ ] Unit tests added/updated
- [ ] Internal documentation updated
- [ ] Create a documentation update request [here](https://github.com/minio/docs/issues/new?label=doc-change,title=Doc+Updated+Needed+For+PR+github.com%2fminio%2fminio%2fpull%2fNNNNN)

### CODE REVIEW

**Review by harshavardhana — APPROVED** [review]

**Comment by Praveenrajmani** [comment]
We can also assign a single connection per broker and reuse it instead of doing `net.Dial` each time. Will fix.

File: internal/event/target/kafka.go [hunk 1]
```diff
@@ -333,23 +320,35 @@ func (target *KafkaTarget) Close() error {
...
+			conn, ok := target.brokerConns[broker.String()]
+			if !ok || conn == nil {
+				conn, errs[idx] = d.Dial("tcp", broker.String())
+				if errs[idx] != nil {
+					return
+				}
+				target.brokerConns[broker.String()] = conn
+			}
+			if _, errs[idx] = conn.Write([]byte("")); errs[idx] != nil {
+				target.brokerConns[broker.String()] = nil
```
Comment (harshavardhana) [inline internal/event/target/kafka.go:353]:
```suggestion
				target.brokerConns[broker.String()] = nil
```

You need an explicit close here which is missing

**Review by harshavardhana — CHANGES_REQUESTED** [review]

**Review by harshavardhana — APPROVED** [review]

**Comment by mctoohey** [comment]
Thanks @Praveenrajmani for the fix!
I just tried out this change. Looks good! I no longer see hundreds of new connections being opened and the number of failures sending to Kafka due to this issue has gone to zero.
