### PR TITLE
s3: Fix GET with partNumber specified

### LINKED ISSUE #11025: Data corruption seen with GET requests when using partNumber
After performing a multipart upload, downloading ranges of the object by specifying partNumber don't align with ranges of the original data. It seems partNumber=1 looks good, but partNumber=2 introduces a 1 byte offset of the returned data and that offset is increased by 1 byte for each part.   
 
## Expected Behavior

When providing partNumber, only the specific content range of the object should be returned.   

## Current Behavior

The content length appears to be correct, but it seems to be offset by 1 byte per part. E.g. given a 6 part upload the final part will be missing the last 6 bytes of data when downloaded using partNumber=6. The object stored within MinIO and the backend NAS (minIO is running in gateway nas mode) is perfectly intact i.e. no issues are seen with the multipart upload.  

## Steps to Reproduce (for bugs)

1. aws s3 cp mylargefile s3://mybucket/mylargefile 
2. aws s3api get-object --bucket mybucket --key mylargefile --part-number 2 mylargefile.2
3. dd if=mylargefile of=sourcecompare.2 bs=1 count=<size of part 2> skip=<size of part 1> 
4. cmp -l sourcecompare.2 mylargefile.2

The <size of part #> value can be pulled from the information stored in the object's fs.json (minio is running in 'gateway nas' mode).

## Context

Clients that download and reassemble multipart objects using partNumber began reporting data corruption after a recent upgrade of MinIO. 
  
## Regression

I'm not certain, but I think the behavior may have been introduce in PR#10618? The behavior seems to be present since the initial release that supported limited content-range downloads with partNumber i.e. it's not seen in RELEASE.2020-09-26T03-44-56Z (however, with the September release, a request of any partNumber will return the entire object) and is seen in RELEASE.2020-10-03T02-19-42Z.

## Your Environment

* Version used (`minio --version`):
* Server setup and configuration:
* Operating System and version (`uname -a`):
RELEASE.2020-11-19T23-48-16Z with MinIO running in gateway nas mode

### PR DESCRIPTION
**Pull request by vadmeste**
## Description
partNumber was miscalculting the start and end of parts when partNumber
query is specified in the GET request. This commit fixes it and also
fixes the ContentRange header in that case.

## Motivation and Context
Fix https://github.com/minio/minio/issues/11025

## How to test this PR?
1. dd if=/dev/urandom of=file.1 count=$[128] bs=$[1024*1024]
2. dd if=/dev/urandom of=file.2 count=$[128] bs=$[1024*1024]
3. cat file1 file2 >file
4. mc cp file myminio/testbucket/
5. aws --profile minio --endpoint-url http://localhost:9000 s3api get-object --bucket testbucket --key file --part-number 2 /tmp/out
6. md5sum file.2 /tmp/out

## Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [ ] Fixes a regression (If yes, please add `commit-id` or `PR #` here)
- [ ] Documentation needed
- [ ] Unit tests needed

### CODE REVIEW

File: cmd/api-headers.go [hunk 1]
```diff
@@ -157,9 +157,9 @@ func setObjectHeaders(w http.ResponseWriter, objInfo ObjectInfo, rs *HTTPRangeSp
 	}
 
 	if opts.PartNumber > 0 {
-		var start, end int64
+		var end = int64(-1)
 		for i := 0; i < len(objInfo.Parts) && i < opts.PartNumber; i++ {
-			start = end
+			start = end + 1
```
Comment (klauspost) [inline cmd/api-headers.go]: A subtle difference would be where the loop never runs, than you will end up with `start = 0 and end = -1` in the RangeSpec, which I suspect should be `end = 0`.

It is a bit weird the way it is made since the byte at offset `end` is included.

Not sure how 0 size is handled.

**Comment by minio-trusted** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-s3.sh | :heavy_check_mark: |
| mint-dist-erasure.sh | :heavy_check_mark: |
| mint-zoned.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-gateway-azure.sh | :x: [more...](#d51b06b5-9bd6-4fdc-8765-9f26a3fa0cbb) |
| mint-erasure.sh | :x: [more...](#7295b91a-b7be-46d6-bde6-43b028263ac9) |
<a name="7295b91a-b7be-46d6-bde6-43b028263ac9"></a>
### 11032-cb92aaf/mint-erasure.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-dev6.minio.io:32009
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp dbc1ec3e2230:/mint/log /tmp/mint-logs'

(1/15) Running aws-sdk-go tests ... done in 1 seconds
(2/15) Running aws-sdk-java tests ... done in 1 seconds
(3/15) Running aws-sdk-php tests ... done in 42 seconds
(4/15) Running aws-sdk-ruby tests ... done in 3 seconds
(5/15) Running awscli tests ... FAILED in 1 minutes and 57 seconds
{
  "name": "awscli",
  "duration": 64674,
  "function": "aws --endpoint-url http://minio-dev6.minio.io:32009 s3 sync --no-progress /mint/data s3://awscli-mint-test-bucket-6878/\n",
  "status": "FAIL",
  "error": "upload: ../../../data/datafile-1-b to s3://awscli-mint-test-bucket-6878/datafile-1-bupload: ../../../data/datafile-0-b to s3://awscli-mint-test-bucket-6878/datafile-0-bupload: ../../../data/datafile-1-kB to s3://awscli-mint-test-bucket-6878/datafile-1-kBupload: ../../../data/datafile-33-kB to s3://awscli-mint-test-bucket-6878/datafile-33-kBupload: ../../../data/datafile-100-kB to s3://awscli-mint-test-bucket-6878/datafile-100-kBupload: ../../../data/datafile-10-kB to s3://awscli-mint-test-bucket-6878/datafile-10-kBupload: ../../../data/datafile-1-MB to s3://awscli-mint-test-bucket-6878/datafile-1-MBupload: ../../../data/datafile-1.03-MB to s3://awscli-mint-test-bucket-6878/datafile-1.03-MBupload: ../../../data/datafile-5-MB to s3://awscli-mint-test-bucket-6878/datafile-5-MBupload: ../../../data/datafile-6-MB to s3://awscli-mint-test-bucket-6878/datafile-6-MBupload: ../../../data/datafile-11-MB to s3://awscli-mint-test-bucket-6878/datafile-11-MBupload: ../../../data/datafile-10-MB to s3://awscli-mint-test-bucket-6878/datafile-10-MBupload: ../../../data/datafile-65-MB to s3://awscli-mint-test-bucket-6878/datafile-65-MBupload: ../../../data/datafile-129-MB to s3://awscli-mint-test-bucket-6878/datafile-129-MBupload failed: ../../../data/datafile-5243880-b to s3://awscli-mint-test-bucket-6878/datafile-5243880-b An error occurred (NoSuchBucket) when calling the PutObject operation: The specified bucket does not exist"
}
(5/15) Running healthcheck tests ... done in 0 seconds
(6/15) Running mc tests ... done in 50 seconds
(7/15) Running minio-dotnet tests ... done in 43 seconds
(8/15) Running minio-go tests ... done in 1 minutes and 27 seconds
(9/15) Running minio-java tests ... done in 45 seconds
(10/15) Running minio-js tests ... done in 48 seconds
(11/15) Running minio-py tests ... done in 2 minutes and 3 seconds
(12/15) Running s3cmd tests ... done in 22 seconds
(13/15) Running s3select tests ... done in 3 seconds
(14/15) Running security tests ... done in 0 seconds

Executed 14 out of 15 tests successfully.
```
<a name="d51b06b5-9bd6-4fdc-8765-9f26a3fa0cbb"></a>
### 11032-cb92aaf/mint-gateway-azure.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-dev4.minio.io:31333
ACCESS_KEY:           minioazure
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 7120a8a35faa:/mint/log /tmp/mint-logs'

(1/15) Running aws-sdk-go tests ... done in 8 seconds
(2/15) Running aws-sdk-java tests ... done in 2 seconds
(3/15) Running aws-sdk-php tests ... done in 1 minutes and 51 seconds
(4/15) Running aws-sdk-ruby tests ... done in 20 seconds
(5/15) Running awscli tests ... done in 3 minutes and 52 seconds
(6/15) Running healthcheck tests ... done in 0 seconds
(7/15) Running mc tests ... done in 3 minutes and 42 seconds
(8/15) Running minio-dotnet tests ... done in 1 minutes and 52 seconds
(9/15) Running minio-go tests ... done in 6 minutes and 19 seconds
(10/15) Running minio-java tests ... FAILED in 8 minutes and 52 seconds
{
  "name": "minio-java",
  "function": "putObject()",
  "args": "[user metadata]",
  "duration": 180,
  "status": "FAIL",
  "error": "error occurred\nErrorResponse(code = AuthenticationFailed, message = -> github.com/Azure/azure-storage-blob-go/azblob.newStorageError, github.com/Azure/azure-storage-blob-go@v0.10.0/azblob/zc_storage_error.go:42\n===== RESPONSE ERROR (ServiceCode=AuthenticationFailed) =====\nDescription=Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature.\nRequestId:aff52344-701e-015a-7e5a-caad3a000000\nTime:2020-12-04T16:27:46.9166593Z, Details: \n   AuthenticationErrorDetail: The MAC signature found in the HTTP request 'P04GGIQM+a8wpgezVpSYwRguErnPvBVfs5qEz1C6XmQ=' is not the same as any computed signature. Server used following string to sign: 'PUT\n\n\n128\n\napplication/xml\n\n\n\n\n\n\nx-ms-blob-cache-control:\nx-ms-blob-content-disposition:\nx-ms-blob-content-encoding:\nx-ms-blob-content-language:\nx-ms-blob-content-type:application/octet-stream\nx-ms-client-request-id:faf035f7-939b-43b5-6a9e-756418966c82\nx-ms-date:Fri, 04 Dec 2020 16:27:46 GMT\nx-ms-meta-my_header1:a   b   c\nx-ms-meta-my_header2:\"a   b   c\"\nx-ms-meta-my_project:Project One\nx-ms-meta-my_unicode_tag:å•†å“\nx-ms-version:2019-02-02\n/minioazure/minio-java-test-1ht67vs/minio-java-test-2efkcqq\ncomp:blocklist\ntimeout:1501'.\n   Code: AuthenticationFailed\n   PUT https://minioazure.blob.core.windows.net/minio-java-test-1ht67vs/minio-java-test-2efkcqq?comp=blocklist&timeout=1501\n   Authorization: REDACTED\n   Content-Length: [128]\n   Content-Type: [application/xml]\n   User-Agent: [APN/1.0 MinIO/1.0 MinIO/2020-12-04T15:54:54Z]\n   X-Ms-Blob-Cache-Control: []\n   X-Ms-Blob-Content-Disposition: []\n   X-Ms-Blob-Content-Encoding: []\n   X-Ms-Blob-Content-Language: []\n   X-Ms-Blob-Content-Type: [application/octet-stream]\n   X-Ms-Client-Request-Id: [faf035f7-939b-43b5-6a9e-756418966c82]\n   X-Ms-Date: [Fri, 04 Dec 2020 16:27:46 GMT]\n   X-Ms-Meta-My_header1: [a   b   c]\n   X-Ms-Meta-My_header2: [\"a   b   c\"]\n   X-Ms-Meta-My_project: [Project One]\n   X-Ms-Meta-My_unicode_tag: [商品]\n   X-Ms-Version: [2019-02-02]\n   --------------------------------------------------------------------------------\n   RESPONSE Status: 403 Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature.\n   Content-Length: [1092]\n   Content-Type: [application/xml]\n   Date: [Fri, 04 Dec 2020 16:27:46 GMT]\n   Server: [Microsoft-HTTPAPI/2.0]\n   X-Ms-Error-Code: [AuthenticationFailed]\n   X-Ms-Request-Id: [aff52344-701e-015a-7e5a-caad3a000000]\n\n\n, bucketName = minio-java-test-1ht67vs, objectName = minio-java-test-2efkcqq, resource = /minio-java-test-1ht67vs/minio-java-test-2efkcqq, requestId = 164D9044B45686ED, hostId = aa17618e-253d-4303-83b4-181f05dee0ae)\nrequest={method=PUT, url=http://minio-dev4.minio.io:31333/minio-java-test-1ht67vs/minio-java-test-2efkcqq, headers=x-amz-meta-My-Unicode-Tag: 商品\nx-amz-meta-My-Project: Project One\nx-amz-meta-My-header1: a   b   c\nx-amz-meta-My-Header2: \"a   b   c\"\nContent-Type: application/octet-stream\nHost: minio-dev4.minio.io:31333\nAccept-Encoding: identity\nUser-Agent: MinIO (Linux; amd64) minio-java/8.0.3\nContent-MD5: A9oFTxee7YVcJ9fWsgQeKg==\nx-amz-content-sha256: 1ff7959f86334ddc5c188a5083268f600146328b2b6c5185e75bf7d9387d6b74\nx-amz-date: 20201204T162746Z\nAuthorization: AWS4-HMAC-SHA256 Credential=*REDACTED*/20201204/us-east-1/s3/aws4_request, SignedHeaders=content-md5;host;x-amz-content-sha256;x-amz-date;x-amz-meta-my-header1;x-amz-meta-my-header2;x-amz-meta-my-project;x-amz-meta-my-unicode-tag, Signature=*REDACTED*\n}\nresponse={code=403, headers=Accept-Ranges: bytes\nContent-Length: 3086\nContent-Security-Policy: block-all-mixed-content\nContent-Type: application/xml\nServer: MinIO\nVary: Origin\nX-Amz-Request-Id: 164D9044B45686ED\nX-Xss-Protection: 1; mode=block\nDate: Fri, 04 Dec 2020 16:27:46 GMT\n}\n >>> [io.minio.MinioClient.execute(MinioClient.java:775), io.minio.MinioClient.putObject(MinioClient.java:4547), io.minio.MinioClient.putObject(MinioClient.java:2713), io.minio.MinioClient.putObject(MinioClient.java:2830), FunctionalTest.testPutObject(FunctionalTest.java:763), FunctionalTest.putObject(FunctionalTest.java:890), FunctionalTest.runObjectTests(FunctionalTest.java:3751), FunctionalTest.runTests(FunctionalTest.java:3783), FunctionalTest.main(FunctionalTest.java:3927)]"
}
(10/15) Running minio-js tests ... done in 2 minutes and 39 seconds
(11/15) Running minio-py tests ... done in 18 minutes and 41 seconds
(12/15) Running s3cmd tests ... done in 2 minutes and 15 seconds
(13/15) Running s3select tests ... done in 59 seconds
(14/15) Running security tests ... done in 0 seconds

Executed 14 out of 15 tests successfully.
```
Deleting image on docker hub
Deleting image locally

**Review by harshavardhana — CHANGES_REQUESTED** [review]
Need some unit tests for this case, this is a critical portion.

Perhaps unit tests for 

- zero byte
- 1 byte
- encrypted (stream)
- multiple parts with unordered boundaries

**Comment by vadmeste** [comment]
> Need some unit tests for this case, this is a critical portion.
> 
> Perhaps unit tests for
> 
> * zero byte
> * 1 byte
> * encrypted (stream)

Done with this.

> * multiple parts with unordered boundaries

What does this ^^ mean exactly ?

**Comment by minio-trusted** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-s3.sh | :heavy_check_mark: |
| mint-erasure.sh | :heavy_check_mark: |
| mint-dist-erasure.sh | :heavy_check_mark: |
| mint-zoned.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-gateway-azure.sh | :x: [more...](#18752db8-0f9c-4238-97b2-20263a5aafb3) |
<a name="18752db8-0f9c-4238-97b2-20263a5aafb3"></a>
### 11032-5bbae12/mint-gateway-azure.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-dev8.minio.io:30344
ACCESS_KEY:           minioazure
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 1c87c9c3c2a6:/mint/log /tmp/mint-logs'

(1/15) Running aws-sdk-go tests ... done in 9 seconds
(2/15) Running aws-sdk-java tests ... done in 2 seconds
(3/15) Running aws-sdk-php tests ... FAILED in 2 minutes and 5 seconds
{
  "name": "aws-sdk-php",
  "function": "getBucketPolicy ( array $params = [] )",
  "args": {
    "Bucket": "aws-sdk-php-5fcf9b51a50ca"
  },
  "duration": "40851",
  "status": "FAIL",
  "error": "Error executing \"CreateBucket\" on \"http://minio-dev8.minio.io:30344/aws-sdk-php-5fcf9b51a50ca\"; AWS HTTP error: Client error: `PUT http://minio-dev8.minio.io:30344/aws-sdk-php-5fcf9b51a50ca` resulted in a `404 Not Found` response:\n<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<Error><Code>NoSuchBucket</Code><Message>The specified bucket does not exist</Mes (truncated...)\n NoSuchBucket (client): The specified bucket does not exist - <?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<Error><Code>NoSuchBucket</Code><Message>The specified bucket does not exist</Message><BucketName>aws-sdk-php-5fcf9b51a50ca</BucketName><Resource>/aws-sdk-php-5fcf9b51a50ca</Resource><RequestId>164EC766071F5C7E</RequestId><HostId>8493c02c-23d4-442e-802a-342d84a576da</HostId></Error>"
}
(3/15) Running aws-sdk-ruby tests ... done in 20 seconds
(4/15) Running awscli tests ... done in 3 minutes and 4 seconds
(5/15) Running healthcheck tests ... done in 1 seconds
(6/15) Running mc tests ... done in 3 minutes and 31 seconds
(7/15) Running minio-dotnet tests ... done in 1 minutes and 48 seconds
(8/15) Running minio-go tests ... FAILED in 1 minutes and 50 seconds
{
  "args": {
    "bucketName": "minio-go-test-lfp6zohp3kf5zlt6",
    "objectName": "test-object",
    "opts": "",
    "size": -1
  },
  "duration": 1242,
  "function": "PutObject(bucketName, objectName, reader,size,opts)",
  "message": "Unexpected size",
  "name": "minio-go: testPutObjectStreaming",
  "status": "FAIL"
}
(8/15) Running minio-java tests ... FAILED in 8 minutes and 57 seconds
{
  "name": "minio-java",
  "function": "putObject()",
  "args": "[user metadata]",
  "duration": 179,
  "status": "FAIL",
  "error": "error occurred\nErrorResponse(code = AuthenticationFailed, message = -> github.com/Azure/azure-storage-blob-go/azblob.newStorageError, github.com/Azure/azure-storage-blob-go@v0.10.0/azblob/zc_storage_error.go:42\n===== RESPONSE ERROR (ServiceCode=AuthenticationFailed) =====\nDescription=Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature.\nRequestId:dd874047-301e-009e-1779-cd94a9000000\nTime:2020-12-08T15:48:49.0703084Z, Details: \n   AuthenticationErrorDetail: The MAC signature found in the HTTP request '1HOvb37AUlcF2k177ybRbWEqPHyARVzwXV3XjlCmezY=' is not the same as any computed signature. Server used following string to sign: 'PUT\n\n\n128\n\napplication/xml\n\n\n\n\n\n\nx-ms-blob-cache-control:\nx-ms-blob-content-disposition:\nx-ms-blob-content-encoding:\nx-ms-blob-content-language:\nx-ms-blob-content-type:application/octet-stream\nx-ms-client-request-id:c7595c3e-0c0e-453e-7177-7a126d1e30fb\nx-ms-date:Tue, 08 Dec 2020 15:48:49 GMT\nx-ms-meta-my_header1:a   b   c\nx-ms-meta-my_header2:\"a   b   c\"\nx-ms-meta-my_project:Project One\nx-ms-meta-my_unicode_tag:å•†å“\nx-ms-version:2019-02-02\n/minioazure/minio-java-test-3e5kl26/minio-java-test-tr83ud\ncomp:blocklist\ntimeout:1501'.\n   Code: AuthenticationFailed\n   PUT https://minioazure.blob.core.windows.net/minio-java-test-3e5kl26/minio-java-test-tr83ud?comp=blocklist&timeout=1501\n   Authorization: REDACTED\n   Content-Length: [128]\n   Content-Type: [application/xml]\n   User-Agent: [APN/1.0 MinIO/1.0 MinIO/2020-12-08T15:21:08Z]\n   X-Ms-Blob-Cache-Control: []\n   X-Ms-Blob-Content-Disposition: []\n   X-Ms-Blob-Content-Encoding: []\n   X-Ms-Blob-Content-Language: []\n   X-Ms-Blob-Content-Type: [application/octet-stream]\n   X-Ms-Client-Request-Id: [c7595c3e-0c0e-453e-7177-7a126d1e30fb]\n   X-Ms-Date: [Tue, 08 Dec 2020 15:48:49 GMT]\n   X-Ms-Meta-My_header1: [a   b   c]\n   X-Ms-Meta-My_header2: [\"a   b   c\"]\n   X-Ms-Meta-My_project: [Project One]\n   X-Ms-Meta-My_unicode_tag: [商品]\n   X-Ms-Version: [2019-02-02]\n   --------------------------------------------------------------------------------\n   RESPONSE Status: 403 Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature.\n   Content-Length: [1091]\n   Content-Type: [application/xml]\n   Date: [Tue, 08 Dec 2020 15:48:48 GMT]\n   Server: [Microsoft-HTTPAPI/2.0]\n   X-Ms-Error-Code: [AuthenticationFailed]\n   X-Ms-Request-Id: [dd874047-301e-009e-1779-cd94a9000000]\n\n\n, bucketName = minio-java-test-3e5kl26, objectName = minio-java-test-tr83ud, resource = /minio-java-test-3e5kl26/minio-java-test-tr83ud, requestId = 164EC876A6CC261A, hostId = 8493c02c-23d4-442e-802a-342d84a576da)\nrequest={method=PUT, url=http://minio-dev8.minio.io:30344/minio-java-test-3e5kl26/minio-java-test-tr83ud, headers=x-amz-meta-My-Unicode-Tag: 商品\nx-amz-meta-My-Project: Project One\nx-amz-meta-My-header1: a   b   c\nx-amz-meta-My-Header2: \"a   b   c\"\nContent-Type: application/octet-stream\nHost: minio-dev8.minio.io:30344\nAccept-Encoding: identity\nUser-Agent: MinIO (Linux; amd64) minio-java/8.0.3\nContent-MD5: A9oFTxee7YVcJ9fWsgQeKg==\nx-amz-content-sha256: 1ff7959f86334ddc5c188a5083268f600146328b2b6c5185e75bf7d9387d6b74\nx-amz-date: 20201208T154848Z\nAuthorization: AWS4-HMAC-SHA256 Credential=*REDACTED*/20201208/us-east-1/s3/aws4_request, SignedHeaders=content-md5;host;x-amz-content-sha256;x-amz-date;x-amz-meta-my-header1;x-amz-meta-my-header2;x-amz-meta-my-project;x-amz-meta-my-unicode-tag, Signature=*REDACTED*\n}\nresponse={code=403, headers=Accept-Ranges: bytes\nContent-Length: 3082\nContent-Security-Policy: block-all-mixed-content\nContent-Type: application/xml\nServer: MinIO\nVary: Origin\nX-Amz-Request-Id: 164EC876A6CC261A\nX-Xss-Protection: 1; mode=block\nDate: Tue, 08 Dec 2020 15:48:49 GMT\n}\n >>> [io.minio.MinioClient.execute(MinioClient.java:775), io.minio.MinioClient.putObject(MinioClient.java:4547), io.minio.MinioClient.putObject(MinioClient.java:2713), io.minio.MinioClient.putObject(MinioClient.java:2830), FunctionalTest.testPutObject(FunctionalTest.java:763), FunctionalTest.putObject(FunctionalTest.java:890), FunctionalTest.runObjectTests(FunctionalTest.java:3751), FunctionalTest.runTests(FunctionalTest.java:3783), FunctionalTest.main(FunctionalTest.java:3927)]"
}
(8/15) Running minio-js tests ... FAILED in 46 seconds
{
  "name": "minio-js",
  "function": "\"after all\" hook in \"functional tests\"",
  "duration": 78,
  "status": "FAIL",
  "error": "S3Error: The bucket you tried to delete is not empty at Object.parseError (node_modules/minio/dist/main/xml-parsers.js:68:11) at /mint/run/core/minio-js/node_modules/minio/dist/main/transformers.js:156:22 at DestroyableTransform._flush (node_modules/minio/dist/main/transformers.js:80:10) at DestroyableTransform.prefinish (node_modules/readable-stream/lib/_stream_transform.js:129:10) at prefinish (node_modules/readable-stream/lib/_stream_writable.js:611:14) at finishMaybe (node_modules/readable-stream/lib/_stream_writable.js:620:5) at endWritable (node_modules/readable-stream/lib/_stream_writable.js:643:3) at DestroyableTransform.Writable.end (node_modules/readable-stream/lib/_stream_writable.js:571:22) at IncomingMessage.onend (_stream_readable.js:684:10) at endReadableNT (_stream_readable.js:1327:12) at processTicksAndRejections (internal/process/task_queues.js:80:21)"
}
(8/15) Running minio-py tests ... done in 18 minutes and 25 seconds
(9/15) Running s3cmd tests ... done in 2 minutes and 15 seconds
(10/15) Running s3select tests ... done in 39 seconds
(11/15) Running security tests ... done in 0 seconds

Executed 11 out of 15 tests successfully.
```
Deleting image on docker hub
Deleting image locally

**Review by harshavardhana — APPROVED** [review]

**Comment by harshavardhana** [comment]
> What does this ^^ mean exactly ?

You added this in your tests already.

**Comment by minio-trusted** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-s3.sh | :heavy_check_mark: |
| mint-erasure.sh | :heavy_check_mark: |
| mint-dist-erasure.sh | :heavy_check_mark: |
| mint-zoned.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-gateway-azure.sh | :x: [more...](#09c56d7b-ce52-4873-9e13-5da82b891a44) |
<a name="09c56d7b-ce52-4873-9e13-5da82b891a44"></a>
### 11032-129c6cd/mint-gateway-azure.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-dev4.minio.io:30395
ACCESS_KEY:           minioazure
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 075bc42732cd:/mint/log /tmp/mint-logs'

(1/15) Running aws-sdk-go tests ... done in 9 seconds
(2/15) Running aws-sdk-java tests ... done in 1 seconds
(3/15) Running aws-sdk-php tests ... done in 2 minutes and 7 seconds
(4/15) Running aws-sdk-ruby tests ... done in 19 seconds
(5/15) Running awscli tests ... done in 2 minutes and 58 seconds
(6/15) Running healthcheck tests ... done in 1 seconds
(7/15) Running mc tests ... done in 3 minutes and 30 seconds
(8/15) Running minio-dotnet tests ... done in 1 minutes and 47 seconds
(9/15) Running minio-go tests ... done in 6 minutes and 24 seconds
(10/15) Running minio-java tests ... FAILED in 8 minutes and 47 seconds
{
  "name": "minio-java",
  "function": "putObject()",
  "args": "[user metadata]",
  "duration": 170,
  "status": "FAIL",
  "error": "error occurred\nErrorResponse(code = AuthenticationFailed, message = -> github.com/Azure/azure-storage-blob-go/azblob.newStorageError, github.com/Azure/azure-storage-blob-go@v0.10.0/azblob/zc_storage_error.go:42\n===== RESPONSE ERROR (ServiceCode=AuthenticationFailed) =====\nDescription=Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature.\nRequestId:207752cb-401e-0170-1381-cdd87f000000\nTime:2020-12-08T16:43:14.9577967Z, Details: \n   AuthenticationErrorDetail: The MAC signature found in the HTTP request '+Dk4q6XnrptmCq37DBN8X5xxIR/2JYEg2z9zWdCHxMs=' is not the same as any computed signature. Server used following string to sign: 'PUT\n\n\n128\n\napplication/xml\n\n\n\n\n\n\nx-ms-blob-cache-control:\nx-ms-blob-content-disposition:\nx-ms-blob-content-encoding:\nx-ms-blob-content-language:\nx-ms-blob-content-type:application/octet-stream\nx-ms-client-request-id:26016d61-6b7e-41ae-5bd4-4d3284ed0cd8\nx-ms-date:Tue, 08 Dec 2020 16:43:14 GMT\nx-ms-meta-my_header1:a   b   c\nx-ms-meta-my_header2:\"a   b   c\"\nx-ms-meta-my_project:Project One\nx-ms-meta-my_unicode_tag:å•†å“\nx-ms-version:2019-02-02\n/minioazure/minio-java-test-29md1kl/minio-java-test-chub5\ncomp:blocklist\ntimeout:1501'.\n   Code: AuthenticationFailed\n   PUT https://minioazure.blob.core.windows.net/minio-java-test-29md1kl/minio-java-test-chub5?comp=blocklist&timeout=1501\n   Authorization: REDACTED\n   Content-Length: [128]\n   Content-Type: [application/xml]\n   User-Agent: [APN/1.0 MinIO/1.0 MinIO/2020-12-08T16:11:24Z]\n   X-Ms-Blob-Cache-Control: []\n   X-Ms-Blob-Content-Disposition: []\n   X-Ms-Blob-Content-Encoding: []\n   X-Ms-Blob-Content-Language: []\n   X-Ms-Blob-Content-Type: [application/octet-stream]\n   X-Ms-Client-Request-Id: [26016d61-6b7e-41ae-5bd4-4d3284ed0cd8]\n   X-Ms-Date: [Tue, 08 Dec 2020 16:43:14 GMT]\n   X-Ms-Meta-My_header1: [a   b   c]\n   X-Ms-Meta-My_header2: [\"a   b   c\"]\n   X-Ms-Meta-My_project: [Project One]\n   X-Ms-Meta-My_unicode_tag: [商品]\n   X-Ms-Version: [2019-02-02]\n   --------------------------------------------------------------------------------\n   RESPONSE Status: 403 Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature.\n   Content-Length: [1090]\n   Content-Type: [application/xml]\n   Date: [Tue, 08 Dec 2020 16:43:14 GMT]\n   Server: [Microsoft-HTTPAPI/2.0]\n   X-Ms-Error-Code: [AuthenticationFailed]\n   X-Ms-Request-Id: [207752cb-401e-0170-1381-cdd87f000000]\n\n\n, bucketName = minio-java-test-29md1kl, objectName = minio-java-test-chub5, resource = /minio-java-test-29md1kl/minio-java-test-chub5, requestId = 164ECB6F0D63B9AB, hostId = 16a2fcf1-e4e0-4b38-8024-e17c49e13e65)\nrequest={method=PUT, url=http://minio-dev4.minio.io:30395/minio-java-test-29md1kl/minio-java-test-chub5, headers=x-amz-meta-My-Unicode-Tag: 商品\nx-amz-meta-My-Project: Project One\nx-amz-meta-My-header1: a   b   c\nx-amz-meta-My-Header2: \"a   b   c\"\nContent-Type: application/octet-stream\nHost: minio-dev4.minio.io:30395\nAccept-Encoding: identity\nUser-Agent: MinIO (Linux; amd64) minio-java/8.0.3\nContent-MD5: A9oFTxee7YVcJ9fWsgQeKg==\nx-amz-content-sha256: 1ff7959f86334ddc5c188a5083268f600146328b2b6c5185e75bf7d9387d6b74\nx-amz-date: 20201208T164314Z\nAuthorization: AWS4-HMAC-SHA256 Credential=*REDACTED*/20201208/us-east-1/s3/aws4_request, SignedHeaders=content-md5;host;x-amz-content-sha256;x-amz-date;x-amz-meta-my-header1;x-amz-meta-my-header2;x-amz-meta-my-project;x-amz-meta-my-unicode-tag, Signature=*REDACTED*\n}\nresponse={code=403, headers=Accept-Ranges: bytes\nContent-Length: 3078\nContent-Security-Policy: block-all-mixed-content\nContent-Type: application/xml\nServer: MinIO\nVary: Origin\nX-Amz-Request-Id: 164ECB6F0D63B9AB\nX-Xss-Protection: 1; mode=block\nDate: Tue, 08 Dec 2020 16:43:14 GMT\n}\n >>> [io.minio.MinioClient.execute(MinioClient.java:775), io.minio.MinioClient.putObject(MinioClient.java:4547), io.minio.MinioClient.putObject(MinioClient.java:2713), io.minio.MinioClient.putObject(MinioClient.java:2830), FunctionalTest.testPutObject(FunctionalTest.java:763), FunctionalTest.putObject(FunctionalTest.java:890), FunctionalTest.runObjectTests(FunctionalTest.java:3751), FunctionalTest.runTests(FunctionalTest.java:3783), FunctionalTest.main(FunctionalTest.java:3927)]"
}
(10/15) Running minio-js tests ... done in 2 minutes and 38 seconds
(11/15) Running minio-py tests ... done in 19 minutes and 4 seconds
(12/15) Running s3cmd tests ... done in 2 minutes and 19 seconds
(13/15) Running s3select tests ... done in 58 seconds
(14/15) Running security tests ... done in 0 seconds

Executed 14 out of 15 tests successfully.
```
Deleting image on docker hub
Deleting image locally

**Review by harshavardhana — APPROVED** [review]

**Review by poornas — APPROVED** [review]
LGTM
