### PR TITLE
Fix multipart replication with 1 part objects

### LINKED ISSUE #20888: The provided 'x-amz-checksum' header does not match what was computed. (*fmt.wrapError)
## NOTE
If this case is urgent, please subscribe to [Subnet](https://min.io/pricing) so that our 24/7 support team may help you faster.

Using FTP to upload on a replicated setup

mc admin replicate add minio1r minio2r

## Expected Behavior

Replication works

## Current Behavior

Feb 03 17:25:45 glus-dmznx minio[893241]: API: SYSTEM.replication
Feb 03 17:25:45 glus-dmznx minio[893241]: Time: 16:25:45 UTC 02/03/2025
Feb 03 17:25:45 glus-dmznx minio[893241]: DeploymentID: 302cf4de-12fc-492b-89a6-dbb14a368aa5
Feb 03 17:25:45 glus-dmznx minio[893241]: Error: unable to replicate for object bucketheraw/2xxGB.dat(610c8725-2cfc-4979-b669-de0ba6c65dca) to target http://minio2-repli:9010: The provided 'x-amz-checksum' header does not match what was computed. (*fmt.wrapError)
Feb 03 17:25:45 glus-dmznx minio[893241]:        4: internal/logger/logger.go:268:logger.LogIf()
Feb 03 17:25:45 glus-dmznx minio[893241]:        3: cmd/logging.go:16:cmd.replLogIf()
Feb 03 17:25:45 glus-dmznx minio[893241]:        2: cmd/bucket-replication.go:1604:cmd.ReplicateObjectInfo.replicateAll()
Feb 03 17:25:45 glus-dmznx minio[893241]:        1: cmd/bucket-replication.go:1101:cmd.replicateObject.func2()

## Possible Solution

Dont know. Maybe a bug in ftp upload?

## Steps to Reproduce (for bugs)
2-node setup. Connect with mc admin replicate.  Use /bin/ftp  to connect and upload.

## Your Environment

* Version used (`minio --version`):
* Server setup and configuration:
* Operating System and version (`uname -a`):
minio -v
minio version RELEASE.2025-01-20T14-49-07Z (commit-id=827004cd6d3da8f49a5320c94ae74ae128156ed6)
Runtime: go1.23.5 linux/amd64
License: GNU AGPLv3 - https://www.gnu.org/licenses/agpl-3.0.html
Copyright: 2015-2025 MinIO, Inc.

uname -a
Linux xxx  4.18.0-553.8.1.el8_10.x86_64 #1 SMP Fri Jun 14 03:19:37 EDT 2024 x86_64 x86_64 x86_64 GNU/Linux

### PR DESCRIPTION
**Pull request by klauspost**
## Description

Fixes #20888

`X-Minio-Internal-Encrypted-Multipart` is not set, since it is only set on encrypted objects.

Therefore `objInfo.isMultipart()` check returns false.

Therefore the object is replicated as single part, assuming the checksum is a regular (full object) checksum and not a checksum-of-checksums.

If we want this to behave symmetric we must strictly match the upload method used. AFAICT this should replicate on all single-part multipart uploads.

We can read this from the checksum. We can modify getCRCMeta to return whether the checksum is multipart.

Bonus: Use full object crc for (s)FTP uploads - disable to reproduce.

## How to test this PR?

Uploading any object as multipart with checksum where there is one part should trigger this. Before this PR, uploading small file via FTP will trigger.

@poornas Could you test, as I don't have a good replicated setup?

## Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)

### CODE REVIEW

**Comment by poornas** [comment]
@klauspost, this PR doesn't work -CompleteMultipartUpload fails with `The provided &#39;x-amz-checksum&#39; header does not match what was computed.` 

The test script is like this
```
$ mc admin replicate add sitea siteb; mc mb sitea/bucket
$ aws s3api create-multipart-upload --bucket bucket --key mult --endpoint-url http://localhost:9002 --profile minio  --checksum-algorithm sha256 | jq .UploadId
$ export UPID=NzcyMWFhNWUtZWVkNy00MzgyLWI2MjQtODFiZjJmMzY0YjNhLjU5YTZkMjU5LTA3NzUtNDdjZS05NjA0LTJmY2ZmMjlkODQ1ZngxNzM4Njg5ODU3MjkzMDcyMDAw
$ aws s3api upload-part --bucket bucket --key mult --part-number 15  --endpoint-url http://localhost:9002 --profile minio --upload-id $UPID --body ./mc  --checksum-algorithm sha256
$ cat /Users/kp/code/scripts/mpuparts.json
{
  "Parts": [
    {
      "ETag": "d7aa8802ce95a53df77b773dc5a64080",
      "PartNumber": 15,
"ChecksumSHA256": "OFSJRntZEy2z6xtIHtuNnm2aL8jMGHR15TebNf9C1X4="
    }
  ]
}
aws s3api complete-multipart-upload --multipart-upload file:///Users/kp/code/scripts/mpuparts.json --bucket bucket --key mult --upload-id $UPID --endpoint-url http://localhost:9002 --profile minio
```

File: cmd/bucket-replication.go [hunk 1]
```diff
@@ -794,23 +794,22 @@ func putReplicationOpts(ctx context.Context, sc string, objInfo ObjectInfo, part
...
-						for k, v := range pi.Checksums { // for PutObjectPart
-							meta[k] = v
-						}
-					}
-				}
-			} else {
-				for k, v := range getCRCMeta(objInfo, 0, nil) { // for PutObject/NewMultipartUpload
-					meta[k] = v
-				}
+			cs, mp := getCRCMeta(objInfo, 0, nil)
```
Comment (poornas) [inline cmd/bucket-replication.go:803]: this change seems incorrect - replication needs to send part checksums here and final checksum will be recomputed on the receiving site

Comment (klauspost) [reply cmd/bucket-replication.go:803]: The receiver only verifies. All that is stored must also be sent.

Comment (harshavardhana) [reply cmd/bucket-replication.go:803]: @poornas PTAL ^^

**Comment by arte-systvit** [comment]
Dear, 
Same result with version:

[root@glus-dmznas-c1 tmp]# minio --version
minio version RELEASE.2025-02-03T21-03-04Z (commit-id=712fe1a8dfd64bbc3fde1863cbbf55ae17e7c911)
Runtime: go1.23.5 linux/amd64
License: GNU AGPLv3 - https://www.gnu.org/licenses/agpl-3.0.html
Copyright: 2015-2025 MinIO, Inc.

ftp> cd bucketheraw
ftp> put 250205ftp.txt
local: 250205ftp.txt remote: 250205ftp.txt
227 Entering Passive Mode (185,95,9,129,117,60)
150 Data transfer starting
226 OK, received 5 bytes
5 bytes sent in 2.4e-05 secs (208.33 Kbytes/sec)

logs:
Feb 05 08:39:56 glus-dmznas-c1.strg.arte minio[24548]: API: SYSTEM.replication
Feb 05 08:39:56 glus-dmznas-c1.strg.arte minio[24548]: Time: 07:39:56 UTC 02/05/2025
Feb 05 08:39:56 glus-dmznas-c1.strg.arte minio[24548]: DeploymentID: 302cf4de-12fc-492b-89a6-dbb14a368aa5
Feb 05 08:39:56 glus-dmznas-c1.strg.arte minio[24548]: Error: unable to replicate for object bucketheraw/250205ftp.txt(92287017-6bb0-4cfa-8e74-a4b509959558) to target http://minio2-repli:9010: The provided 'x-amz-checksum' header does not match what was computed. (*fmt.wrapError)
Feb 05 08:39:56 glus-dmznas-c1.strg.arte minio[24548]:        4: internal/logger/logger.go:268:logger.LogIf()
Feb 05 08:39:56 glus-dmznas-c1.strg.arte minio[24548]:        3: cmd/logging.go:16:cmd.replLogIf()
Feb 05 08:39:56 glus-dmznas-c1.strg.arte minio[24548]:        2: cmd/bucket-replication.go:1604:cmd.ReplicateObjectInfo.replicateAll()
Feb 05 08:39:56 glus-dmznas-c1.strg.arte minio[24548]:        1: cmd/bucket-replication.go:1101:cmd.replicateObject.func2()

Regards

File: cmd/bucket-replication.go (hunk 1 above)
Comment (klauspost) [reply cmd/bucket-replication.go:803]: @poornas Any indication why it failed?

**Comment by klauspost** [comment]
Weird...  

Uploading from MC:
```
mc: <DEBUG> POST /rep/go.sum?uploadId=ZDM0YzUwM2YtZWM1Zi00NWI2LTgxMzYtZTIwMGE3Yjc0Y2Y1LjUxNzdlYzExLTIxZTktNDQxZi05M2EwLTNkMTYzMDY5YmU1NXgxNzM4NzU4MzcxNzQ4ODQ0ODAw HTTP/1.1
Host: 127.0.0.1:9001
User-Agent: MinIO (windows; amd64) minio-go/v7.0.83 mc/DEVELOPMENT.GOGET
Content-Length: 224
Accept-Encoding: zstd,gzip
Authorization: AWS4-HMAC-SHA256 Credential=minio/20250205/us-east-1/s3/aws4_request, SignedHeaders=content-type;host;x-amz-checksum-crc32c;x-amz-content-sha256;x-amz-date, Signature=**REDACTED**
Content-Type: application/octet-stream
X-Amz-Checksum-Crc32c: 1eNxRA==
X-Amz-Content-Sha256: 614ae2c4d0d4cf3a24a13d7128f1862bf82215e90f9a77955163d1183bcd26c2
X-Amz-Date: 20250205T122611Z

mc: <DEBUG> HTTP/1.1 200 OK
```

And the same replication call...

```
POST /rep/go.sum?uploadId=NWUwYzQyNzktNGFhNS00N2RlLTlmMTUtMmQ5N2IyYjQ4ZDBmLjFjNzNlNzhhLWMxN2YtNGUzOS04ZTUyLWY4N2ExMmJjN2IyMngxNzM4NzU4MzI2OTM1NDc1MjAw HTTP/1.1
Host: 127.0.0.1:9000
User-Agent: MinIO (windows; amd64) minio-go/v7.0.83 minio-replication-target/DEVELOPMENT.GOGET arn:minio:replication::2da5880c-2dc3-4cab-b60e-8d87e224f6a6:rep
Content-Length: 224
Authorization: AWS4-HMAC-SHA256 Credential=minio/20250205/us-east-1/s3/aws4_request, SignedHeaders=content-type;host;x-amz-checksum-crc32c;x-amz-checksum-type;x-amz-content-sha256;x-amz-date;x-minio-replication-actual-object-size;x-minio-source-etag;x-minio-source-mtime;x-minio-source-replication-request, Signature=**REDACTED**
Content-Type: application/octet-stream
X-Amz-Checksum-Crc32c: 1eNxRA==
X-Amz-Checksum-Type: COMPOSITE
X-Amz-Content-Sha256: 614ae2c4d0d4cf3a24a13d7128f1862bf82215e90f9a77955163d1183bcd26c2
X-Amz-Date: 20250205T122526Z
X-Minio-Replication-Actual-Object-Size: 31335
X-Minio-Source-Etag: 0ea91f1de3517981ee8658700ce3c414-1
X-Minio-Source-Mtime: 2025-02-05T12:25:26.9262222Z
X-Minio-Source-Replication-Request: true
Accept-Encoding: gzip

HTTP/1.1 400 Bad Request
```

**Comment by klauspost** [comment]
Found it...
```
λ mc stat local/rep/go.sum
Name      : go.sum
Date      : 2025-02-05 14:52:07 CET
Size      : 31 KiB
ETag      : 0ea91f1de3517981ee8658700ce3c414-1
VersionID : 26e64354-2c6a-4f7c-ba3c-723cf83d2311
Type      : file
Checksum  : CRC32C:1eNxRA==-1
Metadata  :
  Content-Type: application/octet-stream
Replication Status: REPLICA

λ mc stat myminio/rep/go.sum
Name      : go.sum
Date      : 2025-02-05 14:52:07 CET
Size      : 31 KiB
ETag      : 0ea91f1de3517981ee8658700ce3c414-1
VersionID : 26e64354-2c6a-4f7c-ba3c-723cf83d2311
Type      : file
Checksum  : CRC32C:1eNxRA==-1
Metadata  :
  Content-Type: application/octet-stream
Replication Status: COMPLETED
```

`x-amz-checksum-algorithm` wasn't set when creating the multipart upload.

**Comment by klauspost** [comment]
Tested multipart, one and n parts, singlepart.

**Comment by klauspost** [comment]
@poornas Can you see if you can break it?

**Comment by poornas** [comment]
@klauspost , tested this - didn't find any issues.

File: internal/hash/checksum.go [hunk 2]
```diff
@@ -203,6 +203,24 @@ func (c ChecksumType) String() string {
 	return "invalid"
 }
 
+// StringFull returns the type and all flags as a string.
+func (c ChecksumType) StringFull() string {
```
Comment (poornas) [inline internal/hash/checksum.go:207]: is this needed? don't see it used

Comment (harshavardhana) [reply internal/hash/checksum.go:207]: I think its for printing purposes we can simply call it String() for stringer compatibility

**Comment by poornas** [comment]
@klauspost , can you update the description for future reference - the actual fix is checksum-algorithm not being set, and nothing to do with encryption (original issue was on an unencrypted 1 part object), so applicable to all replication with sftp afaics

**Review by poornas — APPROVED** [review]

**Comment by harshavardhana** [comment]
> @klauspost , can you update the description for future reference - the actual fix is checksum-algorithm not being set, and nothing to do with encryption (original issue was on an unencrypted 1 part object), so applicable to all replication with sftp afaics

we will change this while merging.

**Review by harshavardhana — APPROVED** [review]

**Comment by harshavardhana** [comment]
@poornas can you send this PR to miniohq/eos that has the EDGE replication changes.

**Comment by klauspost** [comment]
@poornas It is all multipart checksums that aren't replicated. So replicas will not have the same properties as the the original wrt checksums.

To reproduce I could simply use `cat go.sum|mc pipe myminio/rep/go.sum`, which will create a single part multipart with one part.

But no multipart checksums would transfer correctly, since it will just ignore checksums if `x-amz-checksum-algorithm` isn't set on CreateMultipart.
