### PR TITLE
minio: Add config-folder option.

### LINKED ISSUE #997: Allow setting a config directory directly
It is not possible to specify a config directory, on Linux minio insists on using `.minio` in the current user's home directory. This fails when minio is run as user `nobody` on my system, because that user's home directory is `/` and minio is not allowed to create `/.minio`. Apart from abusing the workaround for docker images and setting `DOCKERIMAGE=1` so that minio uses the current working directory, I did not find a way to set the dir.

I think it would be very nice to be able to configure the configuration directory, e.g. by setting an environment variable (e.g. `MINIO_CONFIG_DIR`), and falling back to the current user's home directory if the environment variable is not set.

I do not understand why you're collecting lots of information on the current user in `userCurrent()`, but only ever access the `HomeDir` string of the returned struct. This could be nicely cleaned up and even replace the `DOCKERIMAGE` workaround.

In addition, the function `userCurrent` even exists twice: https://github.com/minio/minio/blob/master/pkg/fs/config.go#L33 and https://github.com/minio/minio/blob/master/utils.go#L63

Are you interested in a PR that cleans this up a bit?

### PR DESCRIPTION
**Pull request by harshavardhana**
Fixes #997

### CODE REVIEW

File: main.go [hunk 1]
```diff
@@ -55,7 +56,7 @@ func init() {
 	checkGolangRuntimeVersion()
 
 	// Check for the environment early on and gracefuly report.
-	_, err := userCurrent()
+	_, err := user.Current()
```
Comment (abperiasamy) [inline main.go:59]: Instead of checking if we are able to determine current user, we should check for configFolder is set or not. Config folder can be auto-determined via home dir (~/.minio) or custom. Check should only bail out if config folder is not set.  It should complain about requiring config folder. This check itself should be introduced as syntax check for main.

File: pkg/fs/config.go [hunk 2]
```diff
@@ -70,11 +40,11 @@ func getFSMultipartsSessionConfigPath() (string, *probe.Error) {
...
-	if err != nil {
-		return "", err.Trace()
+	homeDir, e := user.HomeDir()
+	if e != nil {
+		return "", probe.NewError(e)
 	}
-	fsMultipartsConfigPath := filepath.Join(u.HomeDir, ".minio", "multiparts-session.json")
+	fsMultipartsConfigPath := filepath.Join(homeDir, ".minio", "multiparts-session.json")
 	return fsMultipartsConfigPath, nil
 }
```
Comment (abperiasamy) [inline pkg/fs/config.go:50]: FS should never access config code. Apart from that,  I don't see a need for getFSBucketsConfigPath itself. Any path FS needs to deal with, should be relative to its root path.

File: pkg/user/user.go [hunk 3]
```diff
@@ -0,0 +1,44 @@
+package user
+
+import (
+	"os"
+	"os/user"
+	"runtime"
+	"strconv"
+)
+
+// Current - workaround for docker images with fully static binary and 32bit linux operating systems.
```
Comment (abperiasamy) [inline pkg/user/user.go]: I would word it as, a portable implementation to determine the current user. Golang's user.Current does not work reliably under docker or 32bit linux...

File: pkg/user/user.go [hunk 4]
```diff
@@ -0,0 +1,44 @@
...
+	}
+	return user, nil
+}
+
+// HomeDir - return current home directory.
+func HomeDir() (string, error) {
+	user, err := Current()
+	if err != nil {
+		return "", err
+	}
```
Comment (abperiasamy) [inline pkg/user/user.go:47]: Also look for $HOME as second option. I am also thinking of adding check for DOCKER and using "/" as home, transparently.

File: server-config.go [hunk 5]
```diff
@@ -118,19 +119,32 @@ func (c *configV2) JSON() string {
...
-	u, err := userCurrent()
-	if err != nil {
-		return "", err.Trace()
+	homeDir, e := user.HomeDir()
+	if e != nil {
+		return "", probe.NewError(e)
 	}
-	configPath := filepath.Join(u.HomeDir, ".minio")
+	configPath := filepath.Join(homeDir, ".minio")
 	return configPath, nil
```
Comment (abperiasamy) [inline server-config.go:140]: If user package does best attempt to find homedir and user, this function can remain as is, I mean simpler like this. We can invoke this function in syntax-check for main and verify if we are OK to proceed.  If user has not set config folder and if we are not able to auto-determine, then we fail.

File: server_fs_test.go [hunk 6]
```diff
@@ -85,7 +85,7 @@ func (s *MyAPIFSCacheSuite) SetUpSuite(c *C) {
 	s.secretAccessKey = string(secretAccessKey)
 
 	// do this only once here
-	customConfigPath = root
+	setConfigPath(root)
```
Comment (abperiasamy) [inline server_fs_test.go]: I may name it as setGlobalConfigPath

File: pkg/user/user.go (hunk 4 above)
Comment (harshavardhana) [inline pkg/user/user.go:47]: > Also look for $HOME as second option. I am also thinking of adding check for DOCKER and using "/" as home, transparently.

It is expected that user.Current for most OS and only in cases where it doesn't is handled by Current() - so i don't know if it makes sense to add them again here in this function.

**Comment by harshavardhana** [comment]
Made all those recommended changes also fs doesn't access ".minio" anymore.
