### PR TITLE
boot: getPath() should take care of simple directory exports.

### LINKED ISSUE #3120: "minio server export" does not work on windows
On windows:

```
PS C:\mygo\src\github.com\minio\minio> .\minio server export
time="2016-10-28T05:12:53-07:00" level=fatal msg="Unable to initialize storage disks." cause="GetFileAttributesEx \\\\?\
\C:\\mygo\\src\\github.com\\minio\\minio\\:: The filename, directory name, or volume label syntax is incorrect." locatio
n="validateDisks [C:/mygoserver-main.go:261]"
PS C:\mygo\src\github.com\minio\minio>
```
## Expected Behavior

Should have started the minio server
## Your Environment

Windows 10

### PR DESCRIPTION
**Pull request by krishnasrinivas**
## Description

in Windows "minio server export" the ep.Scheme and ep.Opaque both will be "" but ep.Path will be "export".
This case should be handled.
## Motivation and Context

Details available here https://github.com/minio/minio/issues/3120
## How Has This Been Tested?

Manual testing, added unit test cases.
## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.
  fixes #3120

### CODE REVIEW

File: cmd/object-common_test.go [hunk 1]
```diff
@@ -100,51 +99,49 @@ func TestHouseKeeping(t *testing.T) {
...
-			{
-				ep:   nil,
-				path: "",
-			},
-			{
-				ep:   &url.URL{Path: "/test1"},
-				path: "/test1",
-			},
+			{"\\export", "\\export"},
+			{"D:\\export", "D:\\export"},
```
Comment (harshavardhana) [inline cmd/object-common_test.go]: URL 'D' to --> smaller 'd' you need to handle that.

File: cmd/object-common_test.go [hunk 2]
```diff
@@ -100,51 +99,49 @@ func TestHouseKeeping(t *testing.T) {
...
-		path := getPath(testCase.ep)
-		if path != testCase.path {
-			t.Fatalf("Test: %d Expected path %s, got %s", i+1, testCase.path, path)
+	testCasesCommon := []struct {
+		epStr string
+		path  string
+	}{
+		{"export", "export"},
+		{"http://localhost/export", "/export"},
+		{"https://localhost/export", "/export"},
```
Comment (harshavardhana) [inline cmd/object-common_test.go]: This won't work on windows due to scheme it would trim off the beginning "/"

File: cmd/object-common_test.go [hunk 3]
```diff
@@ -100,51 +99,49 @@ func TestHouseKeeping(t *testing.T) {
...
+	testCases = append(testCases, testCasesCommon...)
+	for _, test := range testCases {
+		eps, err := parseStorageEndpoints([]string{test.epStr})
+		if err != nil {
+			t.Error(test.epStr, err)
+			continue
+		}
+		path := getPath(eps[0])
+		if path != test.path {
+			t.Errorf("For endpoing %s, getPath() failed, got: %s, expected: %s,", test.epStr, path, test.path)
```
Comment (harshavardhana) [inline cmd/object-common_test.go]: add test number so that the error carries the test number as well. "Test %d: For endpoint"
