### PR TITLE
signature-v4: Use sha256("") for calculating canonical request

### LINKED ISSUE #4039: AWS iOS SDK working with minio
## Error messgae

<Error><Code>SignatureDoesNotMatch</Code><Message>The request signature we calculated does not match the signature you provided. Check your key and signing method.</Message><Key></Key><BucketName></BucketName><Resource>/images/test.jpg</Resource><RequestId>3L137</RequestId><HostId>3L137</HostId></Error>
Upload failed with error: (The operation couldn’t be completed. (com.amazonaws.AWSServiceErrorDomain error 3.))

## Here is how I configure
```
let accessKey = "xxxxxxx"
let secretKey = "xxxxxxx"       
let credentialsProvider = AWSStaticCredentialsProvider(accessKey: accessKey, secretKey: secretKey)
let configuration = AWSServiceConfiguration(region: AWSRegionType.USEast1, endpoint: AWSEndpoint(region: .USEast1, service: .APIGateway, url: URL( string:"http://xxxx.com:9000")),credentialsProvider: credentialsProvider)
AWSServiceManager.default().defaultServiceConfiguration = configuration
```

## Possible Solution

refer to this issue, https://github.com/minio/mc/issues/1707
maybe it caused by region issue?

## Your Environment

* Version used: 

  - official docker latest
  - awss3 lib used: pod 'AWSS3', '~> 2.5'

### PR DESCRIPTION
**Pull request by krishnasrinivas**
## Description

When x-amz-content-sha256 header is missing assume e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
as the SHA256 value for calculating canonical-request.

## Motivation and Context

fixes #4039

## How Has This Been Tested?

make test

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

File: cmd/signature-v4-utils.go [hunk 1]
```diff
@@ -47,6 +47,22 @@ func skipContentSha256Cksum(r *http.Request) bool {
 	return isRequestUnsignedPayload(r) || isRequestPresignedUnsignedPayload(r)
 }
 
+// Returns SHA256 for calculating canonical-request.
+func getContentSha256Cksum(r *http.Request) string {
+	defaultSum := emptySHA256
```
Comment (harshavardhana) [inline cmd/signature-v4-utils.go]: This function is pretty confusing.. needs work. the relation between defaultSum and sum is not apparent.

Comment (krishnasrinivas) [reply cmd/signature-v4-utils.go]: do you have suggestions?

Comment (harshavardhana) [reply cmd/signature-v4-utils.go]:
```go
// Returns SHA256 for calculating canonical-request.
func getContentSha256Cksum(r *http.Request) string {
        // For a presigned request we look at the query param for sha256.
	if isRequestPresignedSignatureV4(r) { 
                 presignedCkSum := r.URL.Query().Get("X-Amz-Content-Sha256")
                 if presignedCkSum == "" {
                        // If not set presigned is defaulted to UNSIGNED-PAYLOAD.
                        return unsignedPayload
                 }
                 return presignedCkSum
         }
	contentCkSum := r.Header.Get("X-Amz-Content-Sha256")
        if contentCkSum == "" {
                // If not set content checksum is defaulted to sha256([]byte("")). 
                contentCkSum = emptySHA256
        }
	return contentCkSum
}
```

**Review by harshavardhana — CHANGES_REQUESTED** [review]

**Review by harshavardhana — APPROVED** [review]

File: cmd/auth-handler.go [hunk 2]
```diff
@@ -142,52 +142,55 @@ func isReqAuthenticatedV2(r *http.Request) (s3Error APIErrorCode) {
...
-	} else if isRequestPresignedSignatureV4(r) {
-		return doesPresignedSignatureMatch(sha256sum, r, region)
+
+	// Verify that X-Amz-Content-Sha256 Header == sha256(payload)
+	sum := r.Header.Get("X-Amz-Content-Sha256")
+	if isRequestPresignedSignatureV4(r) {
+		sum = r.URL.Query().Get("X-Amz-Content-Sha256")
 	}
-	return ErrAccessDenied
+	if sum != "" && sum != getSHA256Hash(payload) {
```
Comment (krisis) [inline cmd/auth-handler.go:191]: when can `sum` be `""`? Could you add a comment for it?

File: cmd/signature-v4_test.go [hunk 3]
```diff
@@ -135,21 +135,7 @@ func TestDoesPresignedSignatureMatch(t *testing.T) {
 			region:   "us-west-1",
 			expected: ErrInvalidAccessKeyID,
 		},
-		// (2) Should error when the payload sha256 doesn't match.
```
Comment (krisis) [inline cmd/signature-v4_test.go:138]: why is this test case being removed?

**Review by krisis — CHANGES_REQUESTED** [review]

File: cmd/signature-v4-utils.go [hunk 4]
```diff
@@ -47,6 +47,27 @@ func skipContentSha256Cksum(r *http.Request) bool {
...
 
+// Returns SHA256 for calculating canonical-request.
+func getContentSha256Cksum(r *http.Request) string {
+	// For a presigned request we look at the query param for sha256.
+	if isRequestPresignedSignatureV4(r) {
+		presignedCkSum := r.URL.Query().Get("X-Amz-Content-Sha256")
+		if presignedCkSum == "" {
+			// If not set presigned is defaulted to UNSIGNED-PAYLOAD.
+			return unsignedPayload
+
```
Comment (donatello) [inline cmd/signature-v4-utils.go]: Stray newline.

File: cmd/signature-v4-utils.go [hunk 5]
```diff
@@ -47,6 +47,27 @@ func skipContentSha256Cksum(r *http.Request) bool {
...
+		}
+		return presignedCkSum
+	}
+	contentCkSum := r.Header.Get("X-Amz-Content-Sha256")
+	if contentCkSum == "" {
+		// If not set content checksum is defaulted to sha256([]byte("")).
+		contentCkSum = emptySHA256
+
```
Comment (donatello) [inline cmd/signature-v4-utils.go]: Stray newline.

File: cmd/auth-handler_test.go [hunk 6]
```diff
@@ -308,6 +308,16 @@ func mustNewSignedRequest(method string, urlStr string, contentLength int64, bod
 	return req
 }
 
+func mustNewSignedBadMD5Request(method string, urlStr string, contentLength int64, body io.ReadSeeker, t *testing.T) *http.Request {
+	req := mustNewRequest(method, urlStr, contentLength, body, t)
+	req.Header.Set("Content-Md5", "YWFhYWFhYWFhYWFhYWFhCg==")
+	cred := serverConfig.GetCredential()
+	if err := signRequestV4(req, cred.AccessKey, cred.SecretKey); err != nil {
+		t.Fatalf("Unable to inititalized new signed http request %s", err)
```
Comment (donatello) [inline cmd/auth-handler_test.go]: Typo: `s/inititalized/initialized/`

File: cmd/auth-handler.go (hunk 2 above)
Comment (donatello) [reply cmd/auth-handler.go:191]: Looks like the above code can just use `getContentSha256Cksum` - it need not be reimplemented here.

Comment (krishnasrinivas) [reply cmd/auth-handler.go:191]: `getContentSha256Cksum()` returns `e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855` when `x-amz-content-sha256` is missing and hence should not be used, else we'll end up returning "sha256 does not match" error.

Comment (krishnasrinivas) [reply cmd/auth-handler.go:191]: > when can sum be ""? Could you add a comment for it?

@krisis is comment needed because, then I will have to add a comment "When X-Amz-Content-Sha256 header is missing" but the code for it seems obvious:

```
+	sum := r.Header.Get("X-Amz-Content-Sha256")
 +	if isRequestPresignedSignatureV4(r) {
 +		sum = r.URL.Query().Get("X-Amz-Content-Sha256")
  	}
```

File: cmd/signature-v4_test.go (hunk 3 above)
Comment (krishnasrinivas) [reply cmd/signature-v4_test.go:138]: sha256 verification is not done in this function, just signature verification happens here.

File: cmd/auth-handler.go (hunk 2 above)
Comment (krisis) [reply cmd/auth-handler.go:191]: >// Verify that X-Amz-Content-Sha256 Header == sha256(payload)

@krishnasrinivas the comment above is obvious too. But it informs the reader that sha256sum of payload needs to be validated. In the same spirit you can add to the above comment, what is to be done when sha256sum of payload is not sent as part of the request.

Comment (krishnasrinivas) [reply cmd/auth-handler.go:191]: @krisis do you mean like this:

```
// Verify that X-Amz-Content-Sha256 Header == sha256(payload)
// If X-Amz-Content-Sha256 header is not sent then we don't calculate/verify sha256(payload)
```

If it is not helping then you can suggest a comment.

Comment (krisis) [reply cmd/auth-handler.go:191]: This works.

**Review by harshavardhana — APPROVED** [review]
