### PR TITLE
Fix error message when wrong set of disks are passed

### LINKED ISSUE #1591: Unclear error message when running minio server with wrong set of disks
With wrong set of disks, minio server throws generic error message like

```
FATA[0000] Initializing object layer failed.             Error={Cause:Command-line arguments [/mnt/sdb1/bala/mydisk /mnt/sdc1/bala/mydisk /mnt/sdd1/bala/mydisk /mnt/sde1/bala/mydisk /mnt/sdf1/bala/mydisk /mnt/sdg1/bala/mydisk] is not valid. Type:*errors.errorString}

```

This message need to be very specific.
1. Wrong set of disks given
2. Previous and current disks don't match
etc

### PR DESCRIPTION
**Pull request by balamurugana**
Previously when wrong set of disks are given with last minio server
run, it throws unclear error message.  This is fixed by returning
appropriate errors.

Fixes #1591

### CODE REVIEW

File: routers.go [hunk 1]
```diff
@@ -37,7 +38,11 @@ func newObjectLayer(exportPaths ...string) (ObjectLayer, error) {
 // configureServer handler returns final handler for the http server.
 func configureServerHandler(srvCmdConfig serverCmdConfig) http.Handler {
 	objAPI, err := newObjectLayer(srvCmdConfig.exportPaths...)
-	fatalIf(err, "Initializing object layer failed.", nil)
+	if err == errWriteQuorum {
+		fatalIf(errors.New("Disks are different with last minio server run."), "Initializing object layer failed.", nil)
```
Comment (harshavardhana) [inline routers.go]: Return this error from inside  - newObjectLayer().

Comment (harshavardhana) [inline routers.go]: No reason to expose this error here.

Comment (balamurugana) [inline routers.go]: > Return this error from inside - newObjectLayer().

Done
