### PR TITLE
server: Sort disk arguments for consistent ordering

### LINKED ISSUE #3425: cli: validate if the order of arguments are consistent across all nodes for the first time.
## Expected Behavior
Order of arguments are validated properly across all nodes for the first time.

## Current Behavior
Currently if the order of arguments are given wrong for the first time it can end up corrupting the data and create a wrong backend format.

## Possible Solution
Validate the args early on before even proceeding to generate `format` configs.

## Steps to Reproduce (for bugs)
Quite easy start fresh servers with incorrect orders across nodes, as soon as the nodes `format` themselves they fail with inconsistent `format.json`. 

## Context
This is required since it is a common mistake and we should error out early on.

### PR DESCRIPTION
**Pull request by krisis**
This is important in a distributed setup, where the server hosting the
first disk formats a fresh setup. Sorting ensures that all servers
arrive at the same 'first' server.

Note: This change doesn't protect against different disk arguments
with some disks being same across servers.

## Description

This change implements the sort interface for url.URL type such that disk arguments are sorted based on concatenated Host (incl. port too) and Path. The sorted disk arguments ensure consistent order across servers in a distributed setup.
## Motivation and Context

Fixes #3425 
## How Has This Been Tested?

Manually tested using steps described in #3425 
## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

File: cmd/url-sort.go [hunk 1]
```diff
@@ -0,0 +1,36 @@
...
+
+func (s orderedURLs) Swap(i, j int) {
+	s[i], s[j] = s[j], s[i]
+}
+
+func (s orderedURLs) Len() int {
+	return len(s)
+}
+
+type byHostPath struct{ orderedURLs }
```
Comment (harshavardhana) [inline cmd/url-sort.go]: You don't need two structs.

Comment (krisis) [reply cmd/url-sort.go]: Done.

**Comment by harshavardhana** [comment]
You might have to rebase this. @krisis

**Comment by harshavardhana** [comment]
Arch reviewed, merging.
