### PR TITLE
api: Fix the conditional to check for reserved buckets.

### LINKED ISSUE #2231: mc cp fail
## Expected behaviour
print minio is invalid bucket name on console

## Actual behaviour
mc.exe cp -r lib\minio local
 0 B / 18 B [                                                         ]   0.00%
mc.exe: <ERROR> Failed to copy `lib\minio\aaabc\aaa.txt`. XML syntax error on line 9: element <link> closed by </head>
mc.exe: <ERROR> Session safely terminated. To resume session `mc session resume MqVJhpHR`

## mc version
Version: 2017-06-15T03:38:43Z
Release-tag: RELEASE.2017-06-15T03-38-43Z
Commit-id: c32b1ea48b651125e33015ea0d1596cb377685a4

## System information
window7

### PR DESCRIPTION
**Pull request by harshavardhana**
## Description
Current code was an logical `and` instead we should do `or`.

## Motivation and Context
Fixes https://github.com/minio/mc/issues/2231

## How Has This Been Tested?
Manually using `mc` and `curl`. 

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Review by balamurugana — APPROVED** [review]

**Comment by harshavardhana** [comment]
@donatello need your reviews?

File: cmd/generic-handlers.go [hunk 1]
```diff
@@ -213,7 +213,7 @@ func setPrivateBucketHandler(h http.Handler) http.Handler {
 func (h minioPrivateBucketHandler) ServeHTTP(w http.ResponseWriter, r *http.Request) {
 	// For all non browser requests, reject access to 'minioReservedBucketPath'.
 	bucketName, _ := urlPath2BucketObjectName(r.URL)
-	if !guessIsBrowserReq(r) && isMinioReservedBucket(bucketName) && isMinioMetaBucket(bucketName) {
+	if !guessIsBrowserReq(r) && isMinioReservedBucket(bucketName) || isMinioMetaBucket(bucketName) {
```
Comment (donatello) [inline cmd/generic-handlers.go]: Due to `&&` being higher precedence than `||` this will reject requests to any minio-meta-bucket regardless of it being a browser request. I am not sure if that is intended to fix the bug that is being addressed here (if it is, the comment needs to be updated too). It looks like the intended conditional is `!guessIsBrowserReq(r) && (isMinioReservedBucket(bucketName) || isMinioMetaBucket(bucketName))`.

**Review by donatello — CHANGES_REQUESTED** [review]

File: cmd/generic-handlers.go (hunk 1 above)
Comment (harshavardhana) [reply cmd/generic-handlers.go]: You are right, let me change that. @donatello

**Review by donatello — APPROVED** [review]
