### PR TITLE
admin/heal: Fix deep healing to heal objects under more conditions

### LINKED ISSUE #8319: deep healing is not working on remote hosts for corrupted objects
**Not using the template on purpose**
```
#!/bin/bash

export MINIO_ACCESS_KEY="minio"
export MINIO_SECRET_KEY="minio123"
for i in {01..04}; do
    minio server --address ":90${i}" http://127.0.0.1:9001/tmp/1 http://127.0.0.1:9002/tmp/2 http://127.0.0.1:9003/tmp/3 http://127.0.0.1:9004/tmp/4 http://127.0.0.1:9001/tmp/5 http://127.0.0.1:9002/tmp/6 http://127.0.0.1:9003/tmp/7 http://127.0.0.1:9004/tmp/8 &
done
~ mc config host list myminio-local1
myminio-local1
  URL       : http://localhost:9001
  AccessKey : minio
  SecretKey : minio123
  API       : s3v4
  Lookup    : auto
```

```
~ mc mb myminio-local1/testbucket/
Bucket created successfully `myminio-local1/testbucket/`.
~ mc cp /etc/hosts myminio-local1/testbucket/
/etc/hosts:            417 B / 417 B ┃▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓┃ 100.00% 14.61 KiB/s
~ > /tmp/8/testbucket/hosts/part.1 
~  ls /tmp/8/testbucket/hosts/ -l
total 4
-rw-r--r-- 1 harsha harsha    0 Sep 26 11:56 part.1
-rw-r--r-- 1 harsha harsha 1067 Sep 26 11:54 xl.json
~ mc admin heal --recursive --scan=deep myminio-local1/testbucket/
 ◓  testbucket/hosts
    0/1 objects; 449 B in 1s
    ┌────────┬───┬─────────────────────┐
    │ Green  │ 5 │ 100.0% ████████████ │
    │ Yellow │ 0 │   0.0%              │
    │ Red    │ 0 │   0.0%              │
    │ Grey   │ 0 │   0.0%              │
    └────────┴───┴─────────────────────┘
~ ls /tmp/8/testbucket/hosts/ -l
total 4
-rw-r--r-- 1 harsha harsha    0 Sep 26 11:56 part.1
-rw-r--r-- 1 harsha harsha 1067 Sep 26 11:54 xl.json
(edited)
~ mc config host add myminio-local4 http://localhost:9004 minio minio123
Added `myminio-local4` successfully.
~ mc admin heal --recursive --scan=deep myminio-local4/testbucket/
 ◓  testbucket/hosts
    1/1 objects; 449 B in 1s
    ┌────────┬───┬─────────────────────┐
    │ Green  │ 5 │ 100.0% ████████████ │
    │ Yellow │ 0 │   0.0%              │
    │ Red    │ 0 │   0.0%              │
    │ Grey   │ 0 │   0.0%              │
    └────────┴───┴─────────────────────┘
```

### PR DESCRIPTION
**Pull request by harshavardhana**
## Description
admin/heal: Fix deep healing to heal objects under more conditions

## Motivation and Context
- Heal if the part.1 is truncated from its original size
- Heal if the part.1 fails while being verified in between
- Heal if the part.1 fails while being at a certain offset

Other cleanups include making sure to flush the HTTP responses
properly from storage-rest-server, avoid using 'defer' to
improve call latency. 'defer' incurs latency avoid them
in our hot-paths such as storage-rest handlers.

Fixes #8319

## How to test this PR?
As described in issue #8319 

## Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [x] Fixes a regression perhaps as old as the implementation of VerifyFile() not sure which commit
- [ ] Documentation needed
- [x] Unit tests needed
- [ ] Functional tests needed (If yes, add [mint](https://github.com/minio/mint) PR # here: )

### CODE REVIEW

**Comment by minio-ops** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-compression-xl.sh | :heavy_check_mark: |
| mint-compression-dist-xl.sh | :heavy_check_mark: |
| mint-compression-fs.sh | :heavy_check_mark: |
| mint-worm.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-dist-xl.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-xl.sh | :x: [more...](#00799bcc-db46-43c1-b299-93ff7dfa03de) |
| mint-large-bucket.sh | :x: [more...](#c78255c2-3f63-4016-be3b-e62601b0968e) |
<a name="00799bcc-db46-43c1-b299-93ff7dfa03de"></a>
### 8321-28402b9/mint-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.53:31774
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp d187cc153760:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... FAILED in 6 minutes and 6 seconds
{
  "alert": "",
  "args": {
    "bucketName": "aws-sdk-go-test-b0fo53js292vmg",
    "expiry": 60000000000,
    "objectName": "presignedTest"
  },
  "duration": 366064,
  "error": "XMinioServerNotInitialized: Server not initialized, please try again.\n\tstatus code: 503, request id: 15C81A366BAFB6FE, host id: ",
  "function": "PresignedPut",
  "message": "AWS SDK Go CreateBucket Failed",
  "name": "aws-sdk-go",
  "status": "FAIL"
}

Executed 0 out of 14 tests successfully.
```
<a name="c78255c2-3f63-4016-be3b-e62601b0968e"></a>
### 8321-28402b9/mint-large-bucket.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.59:30379
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 29b73bb18d6f:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 3 seconds
(2/14) Running aws-sdk-java tests ... done in 2 seconds
(3/14) Running aws-sdk-php tests ... done in 49 seconds
(4/14) Running aws-sdk-ruby tests ... done in 12 seconds
(5/14) Running awscli tests ... done in 2 minutes and 28 seconds
(6/14) Running healthcheck tests ... done in 0 seconds
(7/14) Running mc tests ... done in 1 minutes and 18 seconds
(8/14) Running minio-dotnet tests ... done in 1 minutes and 20 seconds
(9/14) Running minio-go tests ... FAILED in 4 minutes and 2 seconds
{
  "args": {},
  "duration": 98952,
  "error": "Please reduce your request",
  "function": "testStorageClassMetadataCopyObject()",
  "message": "CopyObject failed on RRS",
  "name": "minio-go: testStorageClassMetadataCopyObject",
  "status": "FAIL"
}

Executed 8 out of 14 tests successfully.
```

**Comment by minio-ops** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-compression-xl.sh | :heavy_check_mark: |
| mint-compression-dist-xl.sh | :heavy_check_mark: |
| mint-compression-fs.sh | :heavy_check_mark: |
| mint-worm.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-dist-xl.sh | :heavy_check_mark: |
| mint-xl.sh | :x: [more...](#662f8a29-2a4a-4499-9941-b7b27299064d) |
| mint-large-bucket.sh | :x: [more...](#ed637e44-dff2-4c1a-b82e-a405fa3355aa) |
| mint-gateway-nas.sh | :x: [more...](#edeb9d59-5899-4ec6-839c-da9b68745747) |
<a name="662f8a29-2a4a-4499-9941-b7b27299064d"></a>
### 8321-2583852/mint-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.55:32518
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp e2b4c565f608:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 2 seconds
(2/14) Running aws-sdk-java tests ... done in 1 seconds
(3/14) Running aws-sdk-php tests ... done in 41 seconds
(4/14) Running aws-sdk-ruby tests ... done in 2 seconds
(5/14) Running awscli tests ... done in 2 minutes and 5 seconds
(6/14) Running healthcheck tests ... done in 0 seconds
(7/14) Running mc tests ... done in 1 minutes and 5 seconds
(8/14) Running minio-dotnet tests ... done in 23 seconds
(9/14) Running minio-go tests ... done in 40 seconds
(10/14) Running minio-java tests ... done in 22 seconds
(11/14) Running minio-js tests ... FAILED in 8 seconds
{
  "name": "minio-js",
  "function": "\"after all\" hook in \"functional tests\"",
  "duration": 6,
  "status": "FAIL",
  "error": "S3Error: The bucket you tried to delete is not empty at Object.parseError (node_modules/minio/dist/main/xml-parsers.js:83:11) at /mint/run/core/minio-js/node_modules/minio/dist/main/transformers.js:153:22 at DestroyableTransform._flush (node_modules/minio/dist/main/transformers.js:77:10) at DestroyableTransform.prefinish (node_modules/readable-stream/lib/_stream_transform.js:129:10) at prefinish (node_modules/readable-stream/lib/_stream_writable.js:607:14) at finishMaybe (node_modules/readable-stream/lib/_stream_writable.js:616:5) at endWritable (node_modules/readable-stream/lib/_stream_writable.js:629:3) at DestroyableTransform.Writable.end (node_modules/readable-stream/lib/_stream_writable.js:567:22) at IncomingMessage.onend (_stream_readable.js:514:10) at endReadableNT (_stream_readable.js:978:12) at _combinedTickCallback (internal/process/next_tick.js:80:11) at process._tickCallback (internal/process/next_tick.js:104:9)"
}

Executed 10 out of 14 tests successfully.
```
<a name="edeb9d59-5899-4ec6-839c-da9b68745747"></a>
### 8321-2583852/mint-gateway-nas.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.54:30639
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 55ee6066636d:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 0 seconds
(2/14) Running aws-sdk-java tests ... done in 1 seconds
(3/14) Running aws-sdk-php tests ... done in 41 seconds
(4/14) Running aws-sdk-ruby tests ... done in 2 seconds
(5/14) Running awscli tests ... done in 1 minutes and 51 seconds
(6/14) Running healthcheck tests ... done in 0 seconds
(7/14) Running mc tests ... done in 46 seconds
(8/14) Running minio-dotnet tests ... done in 24 seconds
(9/14) Running minio-go tests ... done in 41 seconds
(10/14) Running minio-java tests ... done in 15 seconds
(11/14) Running minio-js tests ... FAILED in 7 seconds
{
  "name": "minio-js",
  "function": "fGetObject(bucketName, objectName, filePath, callback)",
  "args": "bucketName:minio-js-test-3aa4f329-33d7-4bd9-8b04-4516ac948ad0, objectName:datafile-65-MB, filePath:/tmp/datafile-65-MB.download",
  "duration": 88,
  "status": "FAIL",
  "error": "Error: Size mismatch between downloaded file and the object at /mint/run/core/minio-js/node_modules/minio/dist/main/minio.js:965:12 at nextTask (node_modules/minio/node_modules/async/dist/async.js:4578:13) at next (node_modules/minio/node_modules/async/dist/async.js:4586:13) at /mint/run/core/minio-js/node_modules/minio/node_modules/async/dist/async.js:325:20 at FSReqWrap.oncomplete (fs.js:123:15)"
}

Executed 10 out of 14 tests successfully.
```
<a name="ed637e44-dff2-4c1a-b82e-a405fa3355aa"></a>
### 8321-2583852/mint-large-bucket.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.61:30252
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 72e5db6e4525:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 4 seconds
(2/14) Running aws-sdk-java tests ... done in 1 seconds
(3/14) Running aws-sdk-php tests ... done in 51 seconds
(4/14) Running aws-sdk-ruby tests ... done in 15 seconds
(5/14) Running awscli tests ... done in 1 minutes and 26 seconds
(6/14) Running healthcheck tests ... done in 0 seconds
(7/14) Running mc tests ... done in 1 minutes and 43 seconds
(8/14) Running minio-dotnet tests ... done in 2 minutes and 9 seconds
(9/14) Running minio-go tests ... FAILED in 4 minutes and 56 seconds
{
  "args": {},
  "duration": 123737,
  "error": "Please reduce your request",
  "function": "testStorageClassMetadataCopyObject()",
  "message": "CopyObject failed on RRS",
  "name": "minio-go: testStorageClassMetadataCopyObject",
  "status": "FAIL"
}

Executed 8 out of 14 tests successfully.
```

**Comment by minio-ops** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-compression-xl.sh | :heavy_check_mark: |
| mint-xl.sh | :heavy_check_mark: |
| mint-compression-fs.sh | :heavy_check_mark: |
| mint-worm.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-dist-xl.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :x: [more...](#94f4db9d-a28a-4d83-9d7b-0de0f5a7494f) |
| mint-compression-dist-xl.sh | :x: [more...](#0e667eb5-9ea3-4214-9bbf-d0da9ae7f5db) |
<a name="0e667eb5-9ea3-4214-9bbf-d0da9ae7f5db"></a>
### 8321-1acf069/mint-compression-dist-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.51:32715
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 80c6f51cb940:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 0 seconds
(2/14) Running aws-sdk-java tests ... done in 1 seconds
(3/14) Running aws-sdk-php tests ... done in 44 seconds
(4/14) Running aws-sdk-ruby tests ... done in 4 seconds
(5/14) Running awscli tests ... done in 1 minutes and 59 seconds
(6/14) Running healthcheck tests ... done in 0 seconds
(7/14) Running mc tests ... done in 57 seconds
(8/14) Running minio-dotnet tests ... done in 37 seconds
(9/14) Running minio-go tests ... done in 1 minutes and 5 seconds
(10/14) Running minio-java tests ... done in 1 minutes and 38 seconds
(11/14) Running minio-js tests ... done in 51 seconds
(12/14) Running minio-py tests ... FAILED in 3 minutes and 1 seconds
{
  "name": "minio-py:test_presigned_get_object_expiry_5sec",
  "message": "AccessDenied: message: Access Denied",
  "duration": 112,
  "function": "presigned_get_object(bucket_name, object_name, expires, response_headers, request_date)",
  "args": {
    "response._body": "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<Error><Code>AccessDenied</Code><Message>Request has expired</Message><Key>a3a70718-38d1-475f-b6f6-8cab75541368</Key><BucketName>minio-py-test-06704994-4cef-44e5-a920-18d82f120179</BucketName><Resource>/minio-py-test-06704994-4cef-44e5-a920-18d82f120179/a3a70718-38d1-475f-b6f6-8cab75541368</Resource><RequestId>15C81D495082ABA9</RequestId><HostId>0f97f434-79fb-43f0-9f11-5e5a76645b4e</HostId></Error>",
    "bucket_name": "minio-py-test-06704994-4cef-44e5-a920-18d82f120179",
    "response.headers": "{\"_container\": {\"accept-ranges\": [\"Accept-Ranges\", \"bytes\"], \"content-length\": [\"Content-Length\", \"440\"], \"content-security-policy\": [\"Content-Security-Policy\", \"block-all-mixed-content\"], \"content-type\": [\"Content-Type\", \"application/xml\"], \"server\": [\"Server\", \"MinIO/DEVELOPMENT.2019-09-26T22-00-36Z\"], \"vary\": [\"Vary\", \"Origin\"], \"x-amz-request-id\": [\"X-Amz-Request-Id\", \"15C81D495082ABA9\"], \"x-xss-protection\": [\"X-Xss-Protection\", \"1; mode=block\"], \"date\": [\"Date\", \"Thu, 26 Sep 2019 22:24:30 GMT\"]}}",
    "response.reason": "Forbidden",
    "response.status": 403,
    "object_name": "a3a70718-38d1-475f-b6f6-8cab75541368",
    "presigned_get_object_url": "http://72.28.97.51:32715/minio-py-test-06704994-4cef-44e5-a920-18d82f120179/a3a70718-38d1-475f-b6f6-8cab75541368?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=minio%2F20190926%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20190926T222424Z&X-Amz-Expires=5&X-Amz-SignedHeaders=host&X-Amz-Signature=b7533e521604bae33105ff39e05cc4a2f6ee1af7ef56d6db4d83be54e3f1f152"
  },
  "error": "Traceback (most recent call last):\n  File \"/mint/run/core/minio-py/tests.py\", line 1341, in test_presigned_get_object_expiry_5sec\n    object_name).get_exception()\nminio.error.AccessDenied: AccessDenied: message: Access Denied\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"/mint/run/core/minio-py/tests.py\", line 2036, in main\n    test_presigned_get_object_expiry_5sec(client, log_output)\n  File \"/mint/run/core/minio-py/tests.py\", line 1355, in test_presigned_get_object_expiry_5sec\n    raise Exception(err)\nException: AccessDenied: message: Access Denied\n",
  "status": "FAIL"
}

Executed 11 out of 14 tests successfully.
```
<a name="94f4db9d-a28a-4d83-9d7b-0de0f5a7494f"></a>
### 8321-1acf069/mint-large-bucket.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.55:30677
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp b09a4859f53f:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 2 seconds
(2/14) Running aws-sdk-java tests ... done in 2 seconds
(3/14) Running aws-sdk-php tests ... done in 48 seconds
(4/14) Running aws-sdk-ruby tests ... done in 13 seconds
(5/14) Running awscli tests ... done in 2 minutes and 25 seconds
(6/14) Running healthcheck tests ... done in 0 seconds
(7/14) Running mc tests ... done in 1 minutes and 18 seconds
(8/14) Running minio-dotnet tests ... done in 1 minutes and 26 seconds
(9/14) Running minio-go tests ... FAILED in 3 minutes and 51 seconds
{
  "args": {},
  "duration": 99494,
  "error": "Please reduce your request",
  "function": "testStorageClassMetadataCopyObject()",
  "message": "CopyObject failed on RRS",
  "name": "minio-go: testStorageClassMetadataCopyObject",
  "status": "FAIL"
}

Executed 8 out of 14 tests successfully.
```

File: cmd/storage-rest-common.go [hunk 1]
```diff
@@ -16,8 +16,10 @@
 
 package cmd
 
-const storageRESTVersion = "v9"
-const storageRESTPath = minioReservedBucketPath + "/storage/" + storageRESTVersion + SlashSeparator
+const (
+	storageRESTVersion = "v10"
```
Comment (vadmeste) [inline cmd/storage-rest-common.go]: It is probably better to keep the API and just register error type ?

File: cmd/xl-v1-healing.go [hunk 2]
```diff
@@ -192,16 +193,18 @@ func shouldHealObjectOnDisk(xlErr, dataErr error, meta xlMetaV1, quorumModTime t
...
+		if IsErr(dataErr, []error{
+			errFileNotFound,
+			errFileCorrupt,
+		}...) {
 			return true
 		}
-		if dataErr == errFileUnexpectedSize {
+		// Usually this error is not typed and we can't rely on it to be typed
+		// - so we have to do strings based comparison.
+		if dataErr != nil && strings.Contains(dataErr.Error(), "Bitrot verification mismatch") {
```
Comment (vadmeste) [inline cmd/xl-v1-healing.go]: @harshavardhana can you add new function IsBitrotVerificationMismatch() in cmd/storage-errors.go to check if the error string is a bitrot error? if we change the bitrot error message, all the healing will be non functional without knowning it (we don't have any functional tests for distributed healing yet)

**Review by vadmeste — COMMENTED** [review]
Some comments

File: cmd/xl-v1-healing.go (hunk 2 above)
Comment (harshavardhana) [reply cmd/xl-v1-healing.go]: I will try to fix it by bringing in proper types..

File: cmd/storage-rest-common.go (hunk 1 above)
Comment (harshavardhana) [reply cmd/storage-rest-common.go]: Error type cannot be registered for errrors.errorString there is no real error.

Comment (harshavardhana) [reply cmd/storage-rest-common.go]: This change is expected..

Comment (harshavardhana) [reply cmd/storage-rest-common.go]: Reverted pushing a new change..

**Comment by minio-ops** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-compression-xl.sh | :heavy_check_mark: |
| mint-xl.sh | :heavy_check_mark: |
| mint-compression-dist-xl.sh | :heavy_check_mark: |
| mint-worm.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :x: [more...](#c5003278-5a5b-4d8d-9e99-3bb8a344970e) |
| mint-compression-fs.sh | :x: [more...](#1ef95a3d-f2b0-4b52-ab44-2f221c656576) |
| mint-dist-xl.sh | :x: [more...](#2af73641-463f-4a5a-9f61-c9ac4e8cfbf9) |
<a name="1ef95a3d-f2b0-4b52-ab44-2f221c656576"></a>
### 8321-afe1a9b/mint-compression-fs.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.51:32252
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp af32419c0b25:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 0 seconds
(2/14) Running aws-sdk-java tests ... done in 1 seconds
(3/14) Running aws-sdk-php tests ... done in 41 seconds
(4/14) Running aws-sdk-ruby tests ... done in 1 seconds
(5/14) Running awscli tests ... done in 1 minutes and 52 seconds
(6/14) Running healthcheck tests ... done in 0 seconds
(7/14) Running mc tests ... done in 1 minutes and 7 seconds
(8/14) Running minio-dotnet tests ... done in 26 seconds
(9/14) Running minio-go tests ... done in 31 seconds
(10/14) Running minio-java tests ... done in 16 seconds
(11/14) Running minio-js tests ... FAILED in 8 seconds
{
  "name": "minio-js",
  "function": "fPutObject(bucketName, objectName, filePath, callback)",
  "args": "bucketName:minio-js-test-eadc7e28-987a-4c70-bdcb-07ac8f579a2a, objectName:datafile-65-MB, filePath:/tmp/datafile-65-MB",
  "duration": 4589,
  "status": "FAIL",
  "error": "Error: read ECONNRESET at exports._errnoException (util.js:1020:11) at TCP.onread (net.js:580:26)"
}

Executed 10 out of 14 tests successfully.
```
<a name="2af73641-463f-4a5a-9f61-c9ac4e8cfbf9"></a>
### 8321-afe1a9b/mint-dist-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.53:32326
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 38f79dbe4cbe:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 1 seconds
(2/14) Running aws-sdk-java tests ... done in 1 seconds
(3/14) Running aws-sdk-php tests ... done in 49 seconds
(4/14) Running aws-sdk-ruby tests ... done in 3 seconds
(5/14) Running awscli tests ... done in 2 minutes and 6 seconds
(6/14) Running healthcheck tests ... done in 0 seconds
(7/14) Running mc tests ... done in 1 minutes and 17 seconds
(8/14) Running minio-dotnet tests ... done in 59 seconds
(9/14) Running minio-go tests ... done in 1 minutes and 20 seconds
(10/14) Running minio-java tests ... done in 2 minutes and 3 seconds
(11/14) Running minio-js tests ... done in 53 seconds
(12/14) Running minio-py tests ... FAILED in 3 minutes and 18 seconds
{
  "duration": 101,
  "status": "FAIL",
  "error": "Traceback (most recent call last):\n  File \"/mint/run/core/minio-py/tests.py\", line 1396, in test_presigned_get_object_response_headers\n    returned_content_language = response.headers['Content-Language']\n  File \"/usr/local/lib/python3.5/dist-packages/urllib3/_collections.py\", line 156, in __getitem__\n    val = self._container[key.lower()]\nKeyError: 'content-language'\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"/mint/run/core/minio-py/tests.py\", line 2039, in main\n    test_presigned_get_object_response_headers(client, log_output)\n  File \"/mint/run/core/minio-py/tests.py\", line 1414, in test_presigned_get_object_response_headers\n    raise Exception(err)\nException: 'content-language'\n",
  "function": "presigned_get_object(bucket_name, object_name, expires, response_headers, request_date)",
  "message": "'content-language'",
  "args": {
    "object_name": "cbdc13e7-4e10-4bd6-977d-961be5ac0b7a",
    "presigned_get_object_url": "http://72.28.97.53:32326/minio-py-test-835fd77a-2ab9-47c4-adfe-194ef442e8ea/cbdc13e7-4e10-4bd6-977d-961be5ac0b7a?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=minio%2F20190927%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20190927T211216Z&X-Amz-Expires=5&X-Amz-SignedHeaders=host&response-content-language=en_US&response-content-type=text%2Fplain&X-Amz-Signature=e75d44a613cc4b5e8fd6f6af1c6de47a6eafe29c89383ffcc32d28c72759014c",
    "bucket_name": "minio-py-test-835fd77a-2ab9-47c4-adfe-194ef442e8ea"
  },
  "name": "minio-py:test_presigned_get_object_response_headers"
}

Executed 11 out of 14 tests successfully.
```
<a name="c5003278-5a5b-4d8d-9e99-3bb8a344970e"></a>
### 8321-afe1a9b/mint-large-bucket.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.55:32128
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp bfc7ca97248c:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 6 seconds
(2/14) Running aws-sdk-java tests ... done in 2 seconds
(3/14) Running aws-sdk-php tests ... done in 1 minutes and 1 seconds
(4/14) Running aws-sdk-ruby tests ... done in 21 seconds
(5/14) Running awscli tests ... done in 2 minutes and 40 seconds
(6/14) Running healthcheck tests ... done in 3 seconds
(7/14) Running mc tests ... done in 1 minutes and 9 seconds
(8/14) Running minio-dotnet tests ... done in 1 minutes and 47 seconds
(9/14) Running minio-go tests ... FAILED in 4 minutes and 18 seconds
{
  "args": {},
  "duration": 98180,
  "error": "Please reduce your request",
  "function": "testStorageClassMetadataCopyObject()",
  "message": "CopyObject failed on RRS",
  "name": "minio-go: testStorageClassMetadataCopyObject",
  "status": "FAIL"
}

Executed 8 out of 14 tests successfully.
```

**Comment by minio-ops** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-xl.sh | :heavy_check_mark: |
| mint-compression-dist-xl.sh | :heavy_check_mark: |
| mint-compression-fs.sh | :heavy_check_mark: |
| mint-worm.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-dist-xl.sh | :heavy_check_mark: |
| mint-compression-xl.sh | :x: [more...](#5070a008-3459-4361-8494-ca0bd2994e08) |
| mint-large-bucket.sh | :x: [more...](#5191752b-7e8b-4a8f-9f58-0a4e9985c2e2) |
| mint-gateway-nas.sh | :x: [more...](#c15bc669-8904-4d2a-a14f-0f4d668e4fe5) |
<a name="5191752b-7e8b-4a8f-9f58-0a4e9985c2e2"></a>
### 8321-c4a8e34/mint-large-bucket.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.54:31066
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 83c6425dde10:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 2 seconds
(2/14) Running aws-sdk-java tests ... done in 2 seconds
(3/14) Running aws-sdk-php tests ... done in 49 seconds
(4/14) Running aws-sdk-ruby tests ... done in 15 seconds
(5/14) Running awscli tests ... done in 1 minutes and 33 seconds
(6/14) Running healthcheck tests ... done in 0 seconds
(7/14) Running mc tests ... done in 2 minutes and 3 seconds
(8/14) Running minio-dotnet tests ... done in 2 minutes and 17 seconds
(9/14) Running minio-go tests ... FAILED in 4 minutes and 51 seconds
{
  "args": {},
  "duration": 125424,
  "error": "Please reduce your request",
  "function": "testStorageClassMetadataCopyObject()",
  "message": "CopyObject failed on RRS",
  "name": "minio-go: testStorageClassMetadataCopyObject",
  "status": "FAIL"
}

Executed 8 out of 14 tests successfully.
```
<a name="c15bc669-8904-4d2a-a14f-0f4d668e4fe5"></a>
### 8321-c4a8e34/mint-gateway-nas.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.55:31615
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 71eed77a5436:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 0 seconds
(2/14) Running aws-sdk-java tests ... done in 1 seconds
(3/14) Running aws-sdk-php tests ... done in 42 seconds
(4/14) Running aws-sdk-ruby tests ... done in 2 seconds
(5/14) Running awscli tests ... done in 1 minutes and 59 seconds
(6/14) Running healthcheck tests ... done in 0 seconds
(7/14) Running mc tests ... done in 57 seconds
(8/14) Running minio-dotnet tests ... done in 27 seconds
(9/14) Running minio-go tests ... done in 51 seconds
(10/14) Running minio-java tests ... done in 53 seconds
(11/14) Running minio-js tests ... done in 32 seconds
(12/14) Running minio-py tests ... FAILED in 2 minutes and 12 seconds
{
  "duration": 95,
  "status": "FAIL",
  "error": "Traceback (most recent call last):\n  File \"/mint/run/core/minio-py/tests.py\", line 1341, in test_presigned_get_object_expiry_5sec\n    object_name).get_exception()\nminio.error.AccessDenied: AccessDenied: message: Access Denied\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"/mint/run/core/minio-py/tests.py\", line 2036, in main\n    test_presigned_get_object_expiry_5sec(client, log_output)\n  File \"/mint/run/core/minio-py/tests.py\", line 1355, in test_presigned_get_object_expiry_5sec\n    raise Exception(err)\nException: AccessDenied: message: Access Denied\n",
  "args": {
    "response.status": 403,
    "response.reason": "Forbidden",
    "bucket_name": "minio-py-test-65aa4302-1648-4d26-a513-28ed7ca1331b",
    "response._body": "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<Error><Code>AccessDenied</Code><Message>Request has expired</Message><Key>33c504cf-fd64-412e-a699-bf700ae62d15</Key><BucketName>minio-py-test-65aa4302-1648-4d26-a513-28ed7ca1331b</BucketName><Resource>/minio-py-test-65aa4302-1648-4d26-a513-28ed7ca1331b/33c504cf-fd64-412e-a699-bf700ae62d15</Resource><RequestId>15C8691FC2303230</RequestId><HostId></HostId></Error>",
    "presigned_get_object_url": "http://72.28.97.55:31615/minio-py-test-65aa4302-1648-4d26-a513-28ed7ca1331b/33c504cf-fd64-412e-a699-bf700ae62d15?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=minio%2F20190927%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20190927T213408Z&X-Amz-Expires=5&X-Amz-SignedHeaders=host&X-Amz-Signature=fc885d5b45fd85a70303e0a93436173ffed516396d75362cdae1e50bf348bacb",
    "response.headers": "{\"_container\": {\"accept-ranges\": [\"Accept-Ranges\", \"bytes\"], \"content-length\": [\"Content-Length\", \"404\"], \"content-security-policy\": [\"Content-Security-Policy\", \"block-all-mixed-content\"], \"content-type\": [\"Content-Type\", \"application/xml\"], \"server\": [\"Server\", \"MinIO/DEVELOPMENT.2019-09-27T21-12-43Z\"], \"vary\": [\"Vary\", \"Origin\"], \"x-amz-request-id\": [\"X-Amz-Request-Id\", \"15C8691FC2303230\"], \"x-xss-protection\": [\"X-Xss-Protection\", \"1; mode=block\"], \"date\": [\"Date\", \"Fri, 27 Sep 2019 21:34:15 GMT\"]}}",
    "object_name": "33c504cf-fd64-412e-a699-bf700ae62d15"
  },
  "name": "minio-py:test_presigned_get_object_expiry_5sec",
  "message": "AccessDenied: message: Access Denied",
  "function": "presigned_get_object(bucket_name, object_name, expires, response_headers, request_date)"
}

Executed 11 out of 14 tests successfully.
```
<a name="5070a008-3459-4361-8494-ca0bd2994e08"></a>
### 8321-c4a8e34/mint-compression-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.54:32064
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 5aaf04562102:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 1 seconds
(2/14) Running aws-sdk-java tests ... done in 1 seconds
(3/14) Running aws-sdk-php tests ... done in 41 seconds
(4/14) Running aws-sdk-ruby tests ... done in 2 seconds
(5/14) Running awscli tests ... done in 1 minutes and 51 seconds
(6/14) Running healthcheck tests ... done in 0 seconds
(7/14) Running mc tests ... done in 57 seconds
(8/14) Running minio-dotnet tests ... done in 25 seconds
(9/14) Running minio-go tests ... done in 59 seconds
(10/14) Running minio-java tests ... done in 23 seconds
(11/14) Running minio-js tests ... FAILED in 4 seconds
{
  "name": "minio-js",
  "function": "\"after all\" hook in \"functional tests\"",
  "duration": 8,
  "status": "FAIL",
  "error": "S3Error: The bucket you tried to delete is not empty at Object.parseError (node_modules/minio/dist/main/xml-parsers.js:83:11) at /mint/run/core/minio-js/node_modules/minio/dist/main/transformers.js:153:22 at DestroyableTransform._flush (node_modules/minio/dist/main/transformers.js:77:10) at DestroyableTransform.prefinish (node_modules/readable-stream/lib/_stream_transform.js:129:10) at prefinish (node_modules/readable-stream/lib/_stream_writable.js:607:14) at finishMaybe (node_modules/readable-stream/lib/_stream_writable.js:616:5) at endWritable (node_modules/readable-stream/lib/_stream_writable.js:629:3) at DestroyableTransform.Writable.end (node_modules/readable-stream/lib/_stream_writable.js:567:22) at IncomingMessage.onend (_stream_readable.js:514:10) at endReadableNT (_stream_readable.js:978:12) at _combinedTickCallback (internal/process/next_tick.js:80:11) at process._tickCallback (internal/process/next_tick.js:104:9)"
}

Executed 10 out of 14 tests successfully.
```

**Comment by harshavardhana** [comment]
PTAL @vadmeste @krishnasrinivas

File: cmd/storage-rest-server.go [hunk 3]
```diff
@@ -546,12 +547,12 @@ func (s *storageRESTServer) VerifyFile(w http.ResponseWriter, r *http.Request) {
 		s.writeErrorResponse(w, errInvalidArgument)
 		return
 	}
-	algo := BitrotAlgorithmFromString(algoStr)
-	w.Header().Set(xhttp.ContentType, "text/event-stream")
```
Comment (vadmeste) [inline cmd/storage-rest-server.go:555]: Why this header is removed ? don't we use it for long calls ?

File: cmd/posix.go [hunk 4]
```diff
@@ -1605,10 +1607,12 @@ func (s *posix) VerifyFile(volume, path string, fileSize int64, algo BitrotAlgor
 
 		h := algo.New()
 		if _, err = io.CopyBuffer(h, file, *bufp); err != nil {
-			return err
+			// Premature failure in reading the object,file is corrupt.
+			return errFileCorrupt
 		}
 		if !bytes.Equal(h.Sum(nil), sum) {
-			return HashMismatchError{hex.EncodeToString(sum), hex.EncodeToString(h.Sum(nil))}
+			return fmt.Errorf("hashes do not match expected %s, got %s",
```
Comment (vadmeste) [inline cmd/posix.go]: I think we should wrap this error with VerifyFileError() so shouldHealObjectOnDisk() can detect if an object needs to be healed or not.

File: cmd/posix.go [hunk 5]
```diff
@@ -1643,12 +1652,14 @@ func (s *posix) VerifyFile(volume, path string, fileSize int64, algo BitrotAlgor
...
 		n, err = file.Read(buf)
 		if err != nil {
+			// Read's failed for object with right size, at different offsets.
 			return err
 		}
 		size -= int64(n)
 		h.Write(buf)
 		if !bytes.Equal(h.Sum(nil), hashBuf) {
-			return HashMismatchError{hex.EncodeToString(hashBuf), hex.EncodeToString(h.Sum(nil))}
+			return fmt.Errorf("hashes do not match expected %s, got %s",
```
Comment (vadmeste) [inline cmd/posix.go]: I think we should wrap this error with VerifyFileError() so shouldHealObjectOnDisk() can detect if an object needs to be healed or not.

**Review by vadmeste — COMMENTED** [review]
Some comments

File: cmd/storage-rest-server.go (hunk 3 above)
Comment (harshavardhana) [reply cmd/storage-rest-server.go:555]: It's rearranged.. it is still there.

File: cmd/posix.go (hunk 4 above)
Comment (harshavardhana) [reply cmd/posix.go]: Wrapping is already done in defer.

File: cmd/posix.go (hunk 5 above)
Comment (harshavardhana) [reply cmd/posix.go]: Wrapping is already done in defer.

File: cmd/storage-rest-server.go (hunk 3 above)
Comment (harshavardhana) [reply cmd/storage-rest-server.go:555]: Ah damn by mistake I removed it. Will add it back.

**Comment by minio-ops** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-compression-xl.sh | :heavy_check_mark: |
| mint-xl.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-compression-dist-xl.sh | :heavy_check_mark: |
| mint-worm.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-compression-fs.sh | :x: [more...](#0fd8c738-5df8-4aa9-8fc6-bce2d683614d) |
| mint-dist-xl.sh | :x: [more...](#e0fda453-4d15-4585-a457-3450d2c6cf45) |
<a name="e0fda453-4d15-4585-a457-3450d2c6cf45"></a>
### 8321-33c17a9/mint-dist-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.54:31741
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 3c0feb8e13cc:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 0 seconds
(2/14) Running aws-sdk-java tests ... done in 1 seconds
(3/14) Running aws-sdk-php tests ... done in 44 seconds
(4/14) Running aws-sdk-ruby tests ... done in 3 seconds
(5/14) Running awscli tests ... done in 1 minutes and 8 seconds
(6/14) Running healthcheck tests ... done in 0 seconds
(7/14) Running mc tests ... done in 54 seconds
(8/14) Running minio-dotnet tests ... done in 51 seconds
(9/14) Running minio-go tests ... done in 1 minutes and 38 seconds
(10/14) Running minio-java tests ... done in 1 minutes and 32 seconds
(11/14) Running minio-js tests ... FAILED in 19 seconds
{
  "name": "minio-js",
  "function": "fGetObject(bucketName, objectName, filePath)",
  "args": "bucketName:minio-js-test-49250fbe-a73b-4b07-bf41-c0cc7dc22f3c, objectName:datafile-65-MB, filePath:/tmp/datafile-65-MB.download",
  "duration": 892,
  "status": "FAIL",
  "error": "Error: Size mismatch between downloaded file and the object at /mint/run/core/minio-js/node_modules/minio/dist/main/minio.js:965:12 at nextTask (node_modules/minio/node_modules/async/dist/async.js:4578:13) at next (node_modules/minio/node_modules/async/dist/async.js:4586:13) at /mint/run/core/minio-js/node_modules/minio/node_modules/async/dist/async.js:325:20 at FSReqWrap.oncomplete (fs.js:123:15)"
}

Executed 10 out of 14 tests successfully.
```
<a name="0fd8c738-5df8-4aa9-8fc6-bce2d683614d"></a>
### 8321-33c17a9/mint-compression-fs.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.51:30983
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 716526373b33:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 0 seconds
(2/14) Running aws-sdk-java tests ... done in 1 seconds
(3/14) Running aws-sdk-php tests ... done in 42 seconds
(4/14) Running aws-sdk-ruby tests ... done in 1 seconds
(5/14) Running awscli tests ... done in 1 minutes and 2 seconds
(6/14) Running healthcheck tests ... done in 0 seconds
(7/14) Running mc tests ... FAILED in 4 seconds
{
  "name": "mc",
  "duration": "145",
  "function": "test_presigned_get_object",
  "status": "FAIL",
  "error": "unable to download http://72.28.97.51:30983/mc-test-bucket-4852/mc-test-object-28585?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=minio0.000000201909300.000000us-east-10.000000s30.000000aws4_request&X-Amz-Date=20190930T173904Z&X-Amz-Expires=604800&X-Amz-SignedHeaders=host&X-Amz-Signature=8a4e657a7284181b39fc7bdca31a97c641d19412d2209430c5f25da3245370d5"
}

Executed 6 out of 14 tests successfully.
```

File: cmd/posix.go [hunk 6]
```diff
@@ -1547,8 +1552,11 @@ func (s *posix) RenameFile(srcVolume, srcPath, dstVolume, dstPath string) (err e
 
 func (s *posix) VerifyFile(volume, path string, fileSize int64, algo BitrotAlgorithm, sum []byte, shardSize int64) (err error) {
 	defer func() {
-		if err == errFaultyDisk {
-			atomic.AddInt32(&s.ioErrCount, 1)
+		if err != nil {
+			if err == errFaultyDisk {
+				atomic.AddInt32(&s.ioErrCount, 1)
+			}
+			err = VerifyFileError(err.Error())
```
Comment (krishnasrinivas) [inline cmd/posix.go]: Healing will be more predictable (and safer) if it heals only on specific known errors - bitrot, filenotfound, corrupt

Hence it is better to encapsulate only these 3 errors in VerifyFileError.

Ex. for errVolumeNotFound healing code should not try healing.

Comment (harshavardhana) [reply cmd/posix.go]: Fixed

**Comment by minio-ops** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-xl.sh | :heavy_check_mark: |
| mint-compression-dist-xl.sh | :heavy_check_mark: |
| mint-compression-fs.sh | :heavy_check_mark: |
| mint-worm.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-dist-xl.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-compression-xl.sh | :x: [more...](#bd32f619-da58-4bd7-861e-4633a600ba59) |
| mint-large-bucket.sh | :x: [more...](#c65293f0-6f9b-486c-acbb-8c8fd603274f) |
<a name="bd32f619-da58-4bd7-861e-4633a600ba59"></a>
### 8321-ef17897/mint-compression-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.54:30256
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 766254c98c3e:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... FAILED in 6 minutes and 4 seconds
{
  "alert": "",
  "args": {
    "bucketName": "aws-sdk-go-test-0de515wc9qfqw1",
    "expiry": 60000000000,
    "objectName": "presignedTest"
  },
  "duration": 364479,
  "error": "XMinioServerNotInitialized: Server not initialized, please try again.\n\tstatus code: 503, request id: 15C95FCC59788B1E, host id: ",
  "function": "PresignedPut",
  "message": "AWS SDK Go CreateBucket Failed",
  "name": "aws-sdk-go",
  "status": "FAIL"
}

Executed 0 out of 14 tests successfully.
```
<a name="c65293f0-6f9b-486c-acbb-8c8fd603274f"></a>
### 8321-ef17897/mint-large-bucket.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.51:32393
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp e316532b3772:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 2 seconds
(2/14) Running aws-sdk-java tests ... done in 1 seconds
(3/14) Running aws-sdk-php tests ... done in 49 seconds
(4/14) Running aws-sdk-ruby tests ... done in 14 seconds
(5/14) Running awscli tests ... done in 1 minutes and 29 seconds
(6/14) Running healthcheck tests ... done in 0 seconds
(7/14) Running mc tests ... done in 1 minutes and 36 seconds
(8/14) Running minio-dotnet tests ... done in 1 minutes and 41 seconds
(9/14) Running minio-go tests ... FAILED in 4 minutes and 15 seconds
{
  "args": {},
  "duration": 90062,
  "error": "Please reduce your request",
  "function": "testStorageClassMetadataCopyObject()",
  "message": "CopyObject failed on RRS",
  "name": "minio-go: testStorageClassMetadataCopyObject",
  "status": "FAIL"
}

Executed 8 out of 14 tests successfully.
```

**Review by vadmeste — COMMENTED** [review]
LGTM & tested

**Comment by vadmeste** [comment]
@harshavardhana by the way, these tests need to be fixed
```
--- FAIL: TestPosixReadFileWithVerify (0.01s)
    posix_test.go:1314: Test 4: Expected error: hashes do not match expected cd0baa15958b2bda09ee3d648304918a9c02204fb1be9cb7d94edd2c1e5698ac, got be583b36a10f586bb42554452f72b22897b1fd3789174aca0498630609416288, but got: file is corrupted
    posix_test.go:1314: Test 6: Expected error: hashes do not match expected cd0baa15958b2bda09ee3d648304918a9c02204fb1be9cb7d94edd2c1e5698ac, got be583b36a10f586bb42554452f72b22897b1fd3789174aca0498630609416288, but got: file is corrupted
    posix_test.go:1314: Test 8: Expected error: hashes do not match expected 45c92195a44304c4daef07dfc4b606237b11311695ca213c62766f7e10175ee229691b4b3b67336f60d46d98d97b485c5fc0ef22f177c862733bce4735ad267f, got 996a4766540f3bfc3ac9280f2e293c1521c55cb516517464f0b8530bd8ff6ebf342df6948f2325bfee8e3bbd97fb6a4759bf26601b40125ff1058f1a03eb9fb2, but got: file is corrupted
    posix_test.go:1314: Test 10: Expected error: hashes do not match expected 45c92195a44304c4daef07dfc4b606237b11311695ca213c62766f7e10175ee229691b4b3b67336f60d46d98d97b485c5fc0ef22f177c862733bce4735ad267f, got 996a4766540f3bfc3ac9280f2e293c1521c55cb516517464f0b8530bd8ff6ebf342df6948f2325bfee8e3bbd97fb6a4759bf26601b40125ff1058f1a03eb9fb2, but got: file is corrupted
```

**Comment by harshavardhana** [comment]
> --- FAIL: TestPosixReadFileWithVerify (0.01s)
>     posix_test.go:1314: Test 4: Expected error: hashes do not match expected cd0baa15958b2bda09ee3d648304918a9c02204fb1be9cb7d94edd2c1e5698ac, got be583b36a10f586bb42554452f72b22897b1fd3789174aca0498630609416288, but got: file is corrupted
>     posix_test.go:1314: Test 6: Expected error: hashes do not match expected cd0baa15958b2bda09ee3d648304918a9c02204fb1be9cb7d94edd2c1e5698ac, got be583b36a10f586bb42554452f72b22897b1fd3789174aca0498630609416288, but got: file is corrupted
>     posix_test.go:1314: Test 8: Expected error: hashes do not match expected 45c92195a44304c4daef07dfc4b606237b11311695ca213c62766f7e10175ee229691b4b3b67336f60d46d98d97b485c5fc0ef22f177c862733bce4735ad267f, got 996a4766540f3bfc3ac9280f2e293c1521c55cb516517464f0b8530bd8ff6ebf342df6948f2325bfee8e3bbd97fb6a4759bf26601b40125ff1058f1a03eb9fb2, but got: file is corrupted
>     posix_test.go:1314: Test 10: Expected

Fixed @vadmeste

**Review by vadmeste — DISMISSED** [review]
LGTM

**Comment by minio-ops** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-xl.sh | :heavy_check_mark: |
| mint-compression-fs.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-compression-xl.sh | :x: [more...](#a16862bc-02ec-4e67-a6ef-d271bd65634c) |
| mint-large-bucket.sh | :x: [more...](#7ca2184d-5c70-4e21-9e52-b1d0ed9af341) |
| mint-compression-dist-xl.sh | :x: [more...](#008441d9-7b0c-45c0-b3c0-b0baa8e4428f) |
| mint-worm.sh | :x: [more...](#0c6ed787-33e8-408a-8360-674d35cd9f2d) |
| mint-dist-xl.sh | :x: [more...](#d24a4711-2c13-4ede-91c2-f7fbcec55f45) |
<a name="7ca2184d-5c70-4e21-9e52-b1d0ed9af341"></a>
### 8321-462ff72/mint-large-bucket.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.58:30994
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 480f76f7b0a3:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... FAILED in 6 minutes and 5 seconds
{
  "alert": "",
  "args": {
    "bucketName": "aws-sdk-go-test-fb6tx9jrcfrx5l",
    "expiry": 60000000000,
    "objectName": "presignedTest"
  },
  "duration": 365378,
  "error": "XMinioServerNotInitialized: Server not initialized, please try again.\n\tstatus code: 503, request id: 15C992F0F2B78181, host id: ",
  "function": "PresignedPut",
  "message": "AWS SDK Go CreateBucket Failed",
  "name": "aws-sdk-go",
  "status": "FAIL"
}

Executed 0 out of 14 tests successfully.
```
<a name="a16862bc-02ec-4e67-a6ef-d271bd65634c"></a>
### 8321-462ff72/mint-compression-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.61:30690
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 34c0efef4f39:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... FAILED in 0 seconds
{
  "alert": "",
  "args": {
    "bucketName": "aws-sdk-go-test-pxg5kvr2gr1w50",
    "expiry": 60000000000,
    "objectName": "presignedTest"
  },
  "duration": 331,
  "error": "RequestError: send request failed\ncaused by: Put http://72.28.97.61:30690/aws-sdk-go-test-pxg5kvr2gr1w50: dial tcp 72.28.97.61:30690: connect: connection refused",
  "function": "PresignedPut",
  "message": "AWS SDK Go CreateBucket Failed",
  "name": "aws-sdk-go",
  "status": "FAIL"
}

Executed 0 out of 14 tests successfully.
```
<a name="d24a4711-2c13-4ede-91c2-f7fbcec55f45"></a>
### 8321-462ff72/mint-dist-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.61:30902
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp f6ba6ab811f3:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... FAILED in 6 minutes and 6 seconds
{
  "alert": "",
  "args": {
    "bucketName": "aws-sdk-go-test-pwxxz2jeizp2i1",
    "expiry": 60000000000,
    "objectName": "presignedTest"
  },
  "duration": 365773,
  "error": "XMinioServerNotInitialized: Server not initialized, please try again.\n\tstatus code: 503, request id: 15C992F10AC685C4, host id: ",
  "function": "PresignedPut",
  "message": "AWS SDK Go CreateBucket Failed",
  "name": "aws-sdk-go",
  "status": "FAIL"
}

Executed 0 out of 14 tests successfully.
```
<a name="0c6ed787-33e8-408a-8360-674d35cd9f2d"></a>
### 8321-462ff72/mint-worm.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.52:30432
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            worm
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 7f9167f951d8:/mint/log /tmp/mint-logs'

(1/1) Running worm tests ... FAILED in 1 seconds
{
  "alert": "",
  "args": {
    "bucketName": "bucket-maf3tava8cx0u2p6gscyglzbeunzbdipatn75tpvx3jnqzx4qudmra6",
    "expiry": 60000000000,
    "objectName": "testObject"
  },
  "duration": 323,
  "error": "RequestError: send request failed\ncaused by: Put http://72.28.97.52:30432/bucket-maf3tava8cx0u2p6gscyglzbeunzbdipatn75tpvx3jnqzx4qudmra6: dial tcp 72.28.97.52:30432: connect: connection refused",
  "function": "PutAndDelete",
  "message": "WORM_MODE ON  - CreateBucket Failed",
  "name": "test worm mode",
  "status": "FAIL"
}

Executed 0 out of 1 tests successfully.
```
<a name="008441d9-7b0c-45c0-b3c0-b0baa8e4428f"></a>
### 8321-462ff72/mint-compression-dist-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.58:32587
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp d58e1aa3b7db:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... FAILED in 6 minutes and 4 seconds
{
  "alert": "",
  "args": {
    "bucketName": "aws-sdk-go-test-jc29053lnfbi3c",
    "expiry": 60000000000,
    "objectName": "presignedTest"
  },
  "duration": 364019,
  "error": "XMinioServerNotInitialized: Server not initialized, please try again.\n\tstatus code: 503, request id: 15C992F0A189CC62, host id: ",
  "function": "PresignedPut",
  "message": "AWS SDK Go CreateBucket Failed",
  "name": "aws-sdk-go",
  "status": "FAIL"
}

Executed 0 out of 14 tests successfully.
```

**Comment by minio-ops** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-xl.sh | :heavy_check_mark: |
| mint-compression-fs.sh | :heavy_check_mark: |
| mint-worm.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-compression-xl.sh | :x: [more...](#b41a00cb-2917-4627-b691-6e1320d8bb5e) |
| mint-large-bucket.sh | :x: [more...](#811363fa-ea31-42aa-9932-6df4bcc38d07) |
| mint-compression-dist-xl.sh | :x: [more...](#627472af-aafc-481d-808e-663669be4c3e) |
| mint-dist-xl.sh | :x: [more...](#d73c0963-8ac1-408a-b0fa-6853a2d8ffd4) |
<a name="b41a00cb-2917-4627-b691-6e1320d8bb5e"></a>
### 8321-3a86020/mint-compression-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.52:30269
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp d042fa455fb7:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... FAILED in 6 minutes and 6 seconds
{
  "alert": "",
  "args": {
    "bucketName": "aws-sdk-go-test-6ccpzdxfxokfja",
    "expiry": 60000000000,
    "objectName": "presignedTest"
  },
  "duration": 365684,
  "error": "XMinioServerNotInitialized: Server not initialized, please try again.\n\tstatus code: 503, request id: 15C99418C71396F6, host id: ",
  "function": "PresignedPut",
  "message": "AWS SDK Go CreateBucket Failed",
  "name": "aws-sdk-go",
  "status": "FAIL"
}

Executed 0 out of 14 tests successfully.
```
<a name="627472af-aafc-481d-808e-663669be4c3e"></a>
### 8321-3a86020/mint-compression-dist-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.51:31374
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 15d40fa8ebba:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... FAILED in 6 minutes and 4 seconds
{
  "alert": "",
  "args": {
    "bucketName": "aws-sdk-go-test-sp1pj5mr9er4zn",
    "expiry": 60000000000,
    "objectName": "presignedTest"
  },
  "duration": 364332,
  "error": "XMinioServerNotInitialized: Server not initialized, please try again.\n\tstatus code: 503, request id: 15C99418B13378B2, host id: ",
  "function": "PresignedPut",
  "message": "AWS SDK Go CreateBucket Failed",
  "name": "aws-sdk-go",
  "status": "FAIL"
}

Executed 0 out of 14 tests successfully.
```
<a name="811363fa-ea31-42aa-9932-6df4bcc38d07"></a>
### 8321-3a86020/mint-large-bucket.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.58:32762
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 6b7172339877:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... FAILED in 6 minutes and 6 seconds
{
  "alert": "",
  "args": {
    "bucketName": "aws-sdk-go-test-c2ebfufpzepqub",
    "expiry": 60000000000,
    "objectName": "presignedTest"
  },
  "duration": 365746,
  "error": "XMinioServerNotInitialized: Server not initialized, please try again.\n\tstatus code: 503, request id: 15C9941906F13C1D, host id: ",
  "function": "PresignedPut",
  "message": "AWS SDK Go CreateBucket Failed",
  "name": "aws-sdk-go",
  "status": "FAIL"
}

Executed 0 out of 14 tests successfully.
```
<a name="d73c0963-8ac1-408a-b0fa-6853a2d8ffd4"></a>
### 8321-3a86020/mint-dist-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.53:30259
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp e0d8ee0aa646:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... FAILED in 0 seconds
{
  "alert": "",
  "args": {
    "bucketName": "aws-sdk-go-test-555yd3suxz0ebi",
    "expiry": 60000000000,
    "objectName": "presignedTest"
  },
  "duration": 334,
  "error": "RequestError: send request failed\ncaused by: Put http://72.28.97.53:30259/aws-sdk-go-test-555yd3suxz0ebi: dial tcp 72.28.97.53:30259: connect: connection refused",
  "function": "PresignedPut",
  "message": "AWS SDK Go CreateBucket Failed",
  "name": "aws-sdk-go",
  "status": "FAIL"
}

Executed 0 out of 14 tests successfully.
```

**Comment by minio-ops** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-xl.sh | :heavy_check_mark: |
| mint-compression-dist-xl.sh | :heavy_check_mark: |
| mint-worm.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-compression-xl.sh | :x: [more...](#b7d5fc2f-a12f-43cf-a270-3dae75239978) |
| mint-large-bucket.sh | :x: [more...](#eb89df86-e18a-4119-bc58-5fc7ce43456b) |
| mint-compression-fs.sh | :x: [more...](#2f6c0188-3287-494e-9c8a-af7b08558cf2) |
| mint-dist-xl.sh | :x: [more...](#251294d5-06a0-43ce-a2b0-591d8d5487f5) |
<a name="b7d5fc2f-a12f-43cf-a270-3dae75239978"></a>
### 8321-a084a54/mint-compression-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.54:31746
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp ba4c36ce3c6c:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... FAILED in 6 minutes and 6 seconds
{
  "alert": "",
  "args": {
    "bucketName": "aws-sdk-go-test-r665t4qjm0h906",
    "expiry": 60000000000,
    "objectName": "presignedTest"
  },
  "duration": 366080,
  "error": "XMinioServerNotInitialized: Server not initialized, please try again.\n\tstatus code: 503, request id: 15C99DAC0E072C0A, host id: ",
  "function": "PresignedPut",
  "message": "AWS SDK Go CreateBucket Failed",
  "name": "aws-sdk-go",
  "status": "FAIL"
}

Executed 0 out of 14 tests successfully.
```
<a name="2f6c0188-3287-494e-9c8a-af7b08558cf2"></a>
### 8321-a084a54/mint-compression-fs.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.54:32259
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 5803c3c11a84:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 0 seconds
(2/14) Running aws-sdk-java tests ... done in 1 seconds
(3/14) Running aws-sdk-php tests ... done in 42 seconds
(4/14) Running aws-sdk-ruby tests ... done in 2 seconds
(5/14) Running awscli tests ... done in 1 minutes and 55 seconds
(6/14) Running healthcheck tests ... done in 0 seconds
(7/14) Running mc tests ... done in 47 seconds
(8/14) Running minio-dotnet tests ... done in 26 seconds
(9/14) Running minio-go tests ... done in 58 seconds
(10/14) Running minio-java tests ... done in 1 minutes and 31 seconds
(11/14) Running minio-js tests ... done in 43 seconds
(12/14) Running minio-py tests ... FAILED in 2 minutes and 32 seconds
{
  "duration": 55,
  "args": {
    "response.status": 403,
    "bucket_name": "minio-py-test-c837a2d7-b2cd-42c2-86b0-cfbf1c0dc43e",
    "object_name": "f30e7d33-c063-419f-acd2-f755ed0b68bd",
    "presigned_get_object_url": "http://72.28.97.54:32259/minio-py-test-c837a2d7-b2cd-42c2-86b0-cfbf1c0dc43e/f30e7d33-c063-419f-acd2-f755ed0b68bd?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=minio%2F20191001%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20191001T195157Z&X-Amz-Expires=5&X-Amz-SignedHeaders=host&X-Amz-Signature=b267f50fbc6320238371708cbe822ed29e4d3a4c0bd830a99d0d5468a65460e5",
    "response.reason": "Forbidden",
    "response._body": "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<Error><Code>AccessDenied</Code><Message>Request has expired</Message><Key>f30e7d33-c063-419f-acd2-f755ed0b68bd</Key><BucketName>minio-py-test-c837a2d7-b2cd-42c2-86b0-cfbf1c0dc43e</BucketName><Resource>/minio-py-test-c837a2d7-b2cd-42c2-86b0-cfbf1c0dc43e/f30e7d33-c063-419f-acd2-f755ed0b68bd</Resource><RequestId>15C99DDECFAF809B</RequestId><HostId>cccae5df-e73c-4b12-bb38-8aa338541f80</HostId></Error>",
    "response.headers": "{\"_container\": {\"accept-ranges\": [\"Accept-Ranges\", \"bytes\"], \"content-length\": [\"Content-Length\", \"440\"], \"content-security-policy\": [\"Content-Security-Policy\", \"block-all-mixed-content\"], \"content-type\": [\"Content-Type\", \"application/xml\"], \"server\": [\"Server\", \"MinIO/DEVELOPMENT.2019-10-01T19-29-29Z\"], \"vary\": [\"Vary\", \"Origin\"], \"x-amz-request-id\": [\"X-Amz-Request-Id\", \"15C99DDECFAF809B\"], \"x-xss-protection\": [\"X-Xss-Protection\", \"1; mode=block\"], \"date\": [\"Date\", \"Tue, 01 Oct 2019 19:52:05 GMT\"]}}"
  },
  "message": "AccessDenied: message: Access Denied",
  "status": "FAIL",
  "function": "presigned_get_object(bucket_name, object_name, expires, response_headers, request_date)",
  "error": "Traceback (most recent call last):\n  File \"/mint/run/core/minio-py/tests.py\", line 1341, in test_presigned_get_object_expiry_5sec\n    object_name).get_exception()\nminio.error.AccessDenied: AccessDenied: message: Access Denied\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"/mint/run/core/minio-py/tests.py\", line 2036, in main\n    test_presigned_get_object_expiry_5sec(client, log_output)\n  File \"/mint/run/core/minio-py/tests.py\", line 1355, in test_presigned_get_object_expiry_5sec\n    raise Exception(err)\nException: AccessDenied: message: Access Denied\n",
  "name": "minio-py:test_presigned_get_object_expiry_5sec"
}

Executed 11 out of 14 tests successfully.
```
<a name="eb89df86-e18a-4119-bc58-5fc7ce43456b"></a>
### 8321-a084a54/mint-large-bucket.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.56:31839
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp fd59e40c603e:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 6 seconds
(2/14) Running aws-sdk-java tests ... done in 1 seconds
(3/14) Running aws-sdk-php tests ... done in 50 seconds
(4/14) Running aws-sdk-ruby tests ... done in 16 seconds
(5/14) Running awscli tests ... done in 2 minutes and 29 seconds
(6/14) Running healthcheck tests ... done in 0 seconds
(7/14) Running mc tests ... done in 1 minutes and 22 seconds
(8/14) Running minio-dotnet tests ... done in 1 minutes and 20 seconds
(9/14) Running minio-go tests ... FAILED in 3 minutes and 53 seconds
{
  "args": {},
  "duration": 86793,
  "error": "Please reduce your request",
  "function": "testStorageClassMetadataCopyObject()",
  "message": "CopyObject failed on RRS",
  "name": "minio-go: testStorageClassMetadataCopyObject",
  "status": "FAIL"
}

Executed 8 out of 14 tests successfully.
```
<a name="251294d5-06a0-43ce-a2b0-591d8d5487f5"></a>
### 8321-a084a54/mint-dist-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.54:31653
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 6720d3f81c69:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 2 seconds
(2/14) Running aws-sdk-java tests ... done in 1 seconds
(3/14) Running aws-sdk-php tests ... done in 49 seconds
(4/14) Running aws-sdk-ruby tests ... done in 3 seconds
(5/14) Running awscli tests ... done in 1 minutes and 11 seconds
(6/14) Running healthcheck tests ... done in 0 seconds
(7/14) Running mc tests ... done in 1 minutes and 19 seconds
(8/14) Running minio-dotnet tests ... done in 51 seconds
(9/14) Running minio-go tests ... done in 2 minutes and 1 seconds
(10/14) Running minio-java tests ... done in 2 minutes and 14 seconds
(11/14) Running minio-js tests ... done in 57 seconds
(12/14) Running minio-py tests ... FAILED in 3 minutes and 29 seconds
{
  "function": "presigned_get_object(bucket_name, object_name, expires, response_headers, request_date)",
  "message": "'content-language'",
  "status": "FAIL",
  "name": "minio-py:test_presigned_get_object_response_headers",
  "duration": 116,
  "error": "Traceback (most recent call last):\n  File \"/mint/run/core/minio-py/tests.py\", line 1396, in test_presigned_get_object_response_headers\n    returned_content_language = response.headers['Content-Language']\n  File \"/usr/local/lib/python3.5/dist-packages/urllib3/_collections.py\", line 156, in __getitem__\n    val = self._container[key.lower()]\nKeyError: 'content-language'\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"/mint/run/core/minio-py/tests.py\", line 2039, in main\n    test_presigned_get_object_response_headers(client, log_output)\n  File \"/mint/run/core/minio-py/tests.py\", line 1414, in test_presigned_get_object_response_headers\n    raise Exception(err)\nException: 'content-language'\n",
  "args": {
    "object_name": "48dbc5a6-ed4d-49f2-9a76-a5b150fdd6fb",
    "bucket_name": "minio-py-test-4adaadd4-1ea0-4cd3-ba01-e15440aab290",
    "presigned_get_object_url": "http://72.28.97.54:31653/minio-py-test-4adaadd4-1ea0-4cd3-ba01-e15440aab290/48dbc5a6-ed4d-49f2-9a76-a5b150fdd6fb?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=minio%2F20191001%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20191001T195518Z&X-Amz-Expires=5&X-Amz-SignedHeaders=host&response-content-language=en_US&response-content-type=text%2Fplain&X-Amz-Signature=6e86e6931100f65e2794c14165ba731b0decb8456e4f140bbef4441d592036f2"
  }
}

Executed 11 out of 14 tests successfully.
```

**Review by krishnasrinivas — APPROVED** [review]

**Review by vadmeste — APPROVED** [review]
LGTM
