### PR TITLE
Fix multipart upload etag on azure gateway

### LINKED ISSUE #5052: Azure gateway - Etag not changed for multipart upload
On Azure Gateway, we add "-1" to the etag header when we put a new file, but, when we use a multipart upload, it doesn't overwrite the etag header

## Expected Behavior
Append "-1" to multipart etag header

## Current Behavior
Don't append "-1" to multipart etag header

## Context
```
DEBUG: format_uri(): /files/multipart.pdf?partNumber=1&uploadId=f92d518b71f26947

{'data': '',
 'headers': {'accept-ranges': 'bytes',
             'content-length': '0',
             'content-type': 'text/plain; charset=utf-8',
             'date': 'Tue, 10 Oct 2017 17:58:45 GMT',
             'etag': '"fc7d1cde16acc6a9ea43534fe9c47667"',
             'server': 'Minio/DEVELOPMENT.GOGET (linux; amd64)',
             'vary': 'Origin',
             'x-amz-request-id': '14EC474256C4529B'},
 'reason': 'OK',
 'size': 15728640,
 'status': 200}
 15728640 of 15728640   100% in    0s    29.20 MB/s  done
DEBUG: MD5 sums: computed=aefacbcda00c1a546a161ad01d64c7f1, received=fc7d1cde16acc6a9ea43534fe9c47667
WARNING: MD5 Sums don't match!
WARNING: Retrying upload of files/multipart.pdf
```

## Your Environment

* Version used (`minio version`): master + metadata fixes

### PR DESCRIPTION
**Pull request by jmaitrehenry**
## Description
Fix multipart etag like it was already done with put 

## Motivation and Context
Fix #5052 

## How Has This Been Tested?
I deployed a build from master with this fix and start a sync 65450k files of all sizes with a patch for removing custom metadata.

## Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

File: cmd/gateway-azure.go [hunk 1]
```diff
@@ -409,7 +409,7 @@ func (a *azureObjects) ListObjects(bucket, prefix, marker, delimiter string, max
 				Name:            object.Name,
 				ModTime:         time.Time(object.Properties.LastModified),
 				Size:            object.Properties.ContentLength,
-				ETag:            azureToS3ETag(object.Properties.Etag),
+				ETag:            "",
```
Comment (balamurugana) [inline cmd/gateway-azure.go]: Why do we need to reset `ETag`?

File: cmd/gateway-azure.go [hunk 2]
```diff
@@ -655,7 +655,7 @@ func (a *azureObjects) PutObjectPart(bucket, object, uploadID string, partID int
 	}
 
 	info.PartNumber = partID
-	info.ETag = etag
+	info.ETag = azureToS3ETag(etag)
```
Comment (balamurugana) [inline cmd/gateway-azure.go]: {Edit] You could fix the line 627 like `etag = azureToS3ETag(getMD5Hash([]byte(mustGetUUID())))` and rest are taken care automatically.

**Review by balamurugana — CHANGES_REQUESTED** [review]

File: cmd/gateway-azure.go (hunk 1 above)
Comment (jmaitrehenry) [reply cmd/gateway-azure.go]: It's what I'm checking because I don't remember why I reset it...

File: cmd/gateway-azure.go (hunk 2 above)
Comment (krishnasrinivas) [reply cmd/gateway-azure.go]: @balamurugana you mean `etag = azureToS3ETag(getMD5Hash([]byte(mustGetUUID())))`

Comment (balamurugana) [reply cmd/gateway-azure.go]: @krishnasrinivas oops. yes. :smile:

Comment (krishnasrinivas) [reply cmd/gateway-azure.go]: > etag = azureToS3ETag(getMD5Hash([]byte(mustGetUUID())))
Also this would be the only change needed, other changes are not needed

File: cmd/gateway-azure.go (hunk 1 above)
Comment (jmaitrehenry) [reply cmd/gateway-azure.go]: Works without resetting, maybe an error in my side

File: cmd/gateway-azure.go (hunk 2 above)
Comment (jmaitrehenry) [reply cmd/gateway-azure.go]: Done

File: cmd/gateway-azure.go [hunk 3]
```diff
@@ -621,11 +621,7 @@ func (a *azureObjects) PutObjectPart(bucket, object, uploadID string, partID int
 		return info, err
 	}
 
-	etag := data.md5Sum
-	if etag == "" {
-		// Generate random ETag.
-		etag = getMD5Hash([]byte(mustGetUUID()))
-	}
+	etag := azureToS3ETag(getMD5Hash([]byte(mustGetUUID())))
```
Comment (balamurugana) [inline cmd/gateway-azure.go]: You would need to keep `etag := data.md5Sum`

File: cmd/gateway-azure.go [hunk 4]
```diff
@@ -768,7 +764,7 @@ func (a *azureObjects) CompleteMultipartUpload(bucket, object, uploadID string,
 			return objInfo, traceError(PartTooSmall{
 				PartNumber: uploadedParts[i].PartNumber,
 				PartSize:   size,
-				PartETag:   uploadedParts[i].ETag,
+				PartETag:   azureToS3ETag(uploadedParts[i].ETag),
```
Comment (balamurugana) [inline cmd/gateway-azure.go]: The above two changes are not required.

File: cmd/gateway-azure.go (hunk 3 above)
Comment (jmaitrehenry) [reply cmd/gateway-azure.go]: In this case, I should keep the `azureToS3ETag(etag)` on line 654 `info.ETag = azureToS3ETag(etag)` to be sure to have a suffixed etag, no?

File: cmd/gateway-azure.go (hunk 4 above)
Comment (jmaitrehenry) [reply cmd/gateway-azure.go]: Why? Without it, it doesn't work

Comment (jmaitrehenry) [reply cmd/gateway-azure.go]: Hum, maybe not finally, let me check again

File: cmd/gateway-azure.go (hunk 3 above)
Comment (jmaitrehenry) [reply cmd/gateway-azure.go]: Or just, after the `if` add `etag = azureToS3ETag(etag)` ?

Comment (balamurugana) [reply cmd/gateway-azure.go]: below is the change required
```go
	etag := data.md5Sum
	if etag == "" {
		// Generate random ETag.
		etag = azureToS3Tag(getMD5Hash([]byte(mustGetUUID())))
	}
```

Comment (jmaitrehenry) [reply cmd/gateway-azure.go]: It will no work because because some time you will have an etag containing a real md5Sum without suffix.

Comment (balamurugana) [reply cmd/gateway-azure.go]: @jmaitrehenry Yep. Unable to understand why it doesn't work.

Comment (jmaitrehenry) [reply cmd/gateway-azure.go]: @balamurugana Finally, I made a mistake when I double check it.
I made the change asked and it works. Sorry for that :/

**Review by balamurugana — APPROVED** [review]

**Review by krishnasrinivas — APPROVED** [review]
