### PR TITLE
api: Fix registering of s3 endpoint peers properly

### LINKED ISSUE #4158: bucket listening: Regression with standalone FS
## Expected Behavior
`mc watch` against a Minio server in standalone FS mode should succeed

## Current Behavior
`mc watch` against a Minio server in standalone FS mode fails

`ERRO[0129] Error sending update bucket listener to localhost:9000 - Peer :9000 was not initialized, unexpected error  cause=Peer :9000 was not initialized, unexpected error source=[s3-peer-client.go:171:S3PeersUpdateBucketListener()]`

## Possible Solution
No idea.

## Steps to Reproduce (for bugs)
Terminal 1:
1. `minio server /tmp/fs`

Terminal 2:
1. `mc mb myminio/testbucket`
2. `mc watch myminio/testbucket`

## Context
Normal testing

## Your Environment
All
Version: f1d77801678b1e2f8d9b237d313b069d1c5e04bc

### PR DESCRIPTION
**Pull request by harshavardhana**
## Description
We need to have local peer initialized properly
for listen bucket to work, current code did initialize
properly but the resulting code was initializing
peer on a wrong target v/s what listen bucket expected
it to be.

This regression came in de204a0a52e6b13fec2d25b73102239891e6de35

## Motivation and Context
Fixes #4158

## How Has This Been Tested?
Manually using `mc watch` 

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

File: cmd/s3-peer-client.go [hunk 1]
```diff
@@ -42,12 +41,8 @@ type s3Peers []s3Peer
 // slice. The urls slice is assumed to be non-empty and free of nil
 // values.
 func makeS3Peers(endpoints EndpointList) (s3PeerList s3Peers) {
-	thisPeer := globalMinioAddr
-	if globalMinioHost == "" {
-		thisPeer = net.JoinHostPort("localhost", globalMinioPort)
-	}
 	s3PeerList = append(s3PeerList, s3Peer{
-		thisPeer,
+		globalMinioAddr,
```
Comment (vadmeste) [inline cmd/s3-peer-client.go:45]: This is weird, the old doesn't look buggy at all.

Comment (harshavardhana) [reply cmd/s3-peer-client.go:45]: it is because `globalMinioAddr` is used by listenBucket so getPeerClient fails.

Comment (harshavardhana) [reply cmd/s3-peer-client.go:45]: In-fact the current master also doesn't work on windows.. since windows doesn't have `localhost`

**Review by donatello — APPROVED** [review]

**Review by vadmeste — APPROVED** [review]
