### PR TITLE
event/target/webhook: treat all 2xx as success.

### LINKED ISSUE #5769: Webhook throws an error if the endpoint returns a 2xx status code != 200
## Expected Behavior
If the webhook endpoint returns a 2xx status code unequal to 200, the sending event should be treated as success.

## Current Behavior
The request fails for a 201 response:
```
[2018-04-04T15:35:05.933883248Z] [ERROR] unable to send event s3:ObjectAccessed:Get of bucket: [redacted], object: [redacted] to target 1:webhook (sending event failed with 201 Created)
```

## Possible Solution
Treat all 2xx status codes as success.

## Steps to Reproduce (for bugs)

1. Configure minio to send notifications to a webhook endpoint that returns a 20x status code different from 200.
2. Set up notification for a resource
3. See the error in the minio log

## Context
This happens while sending webhook notifications to a publish/subscribe service based on nginx and nchan, which returns several 20x status codes for success. Other webhook sources accept these status codes as success, e.g., GDrive and Dropbox.

## Your Environment

* Version used (`minio version`):
```
# minio version
Version: 2018-03-30T00:38:44Z
Release-Tag: RELEASE.2018-03-30T00-38-44Z
Commit-ID: 804a4f9c159ecef7093585a5b577e03a382af50e
```

### PR DESCRIPTION
**Pull request by balamurugana**
Fixes #5769

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added unit tests to cover my changes.
- [ ] I have added/updated functional tests in [mint](https://github.com/minio/mint). (If yes, add `mint` PR # here: )
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by balamurugana** [comment]
```
Error running mint automation
+ mkdir -p 5792-7187cc0/gopath/src/github.com/minio
+ git -C 5792-7187cc0/gopath/src/github.com/minio clone --quiet https://github.com/minio/minio.git
+ git -C 5792-7187cc0/gopath/src/github.com/minio/minio remote add minio https://github.com/minio/minio.git
+ git -C 5792-7187cc0/gopath/src/github.com/minio/minio fetch --quiet minio pull/5792/head:pr5792
+ git -C 5792-7187cc0/gopath/src/github.com/minio/minio checkout --quiet pr5792
+ GOPATH=/home/bala/mintauto/5792-7187cc0/gopath
+ make -C 5792-7187cc0/gopath/src/github.com/minio/minio --quiet
# runtime
/home/bala/golang/goroot/src/runtime/mstats.go:667:2: non-bool sys.BigEndian (type untyped number) used as if condition
/home/bala/golang/goroot/src/runtime/mstats.go:681:2: non-bool sys.BigEndian (type untyped number) used as if condition
make: *** [checks] Error 1

```

**Review by kannappanr — DISMISSED** [review]

**Review by donatello — COMMENTED** [review]
Seems like it would be better to just check if the status code is between 200 and 300?

**Comment by balamurugana** [comment]
> Seems like it would be better to just check if the status code is between 200 and 300?

I don't think it is good idea.  The specified status codes are as per RFC and not sure whether we need to support non-standard status code.

**Comment by donatello** [comment]
> I don't think it is good idea. The specified status codes are as per RFC and not sure whether we need to support non-standard status code.

2xx is success status according to https://www.iana.org/assignments/http-status-codes/http-status-codes.xhtml. IMO the problem of listing the status code like in the current PR is that it is more difficult to maintain - the golang standard library may add support for more status codes later and the standard itself may assign more in the unassigned range.

**Comment by balamurugana** [comment]
This is what I see
```

200 | OK | [RFC7231, Section 6.3.1]
-- | -- | --
201 | Created | [RFC7231, Section 6.3.2]
202 | Accepted | [RFC7231, Section 6.3.3]
203 | Non-Authoritative Information | [RFC7231, Section 6.3.4]
204 | No Content | [RFC7231, Section 6.3.5]
205 | Reset Content | [RFC7231, Section 6.3.6]
206 | Partial Content | [RFC7233, Section 4.1]
207 | Multi-Status | [RFC4918]
208 | Already Reported | [RFC5842]
209-225 | Unassigned |  
226 | IM Used | [RFC3229]
227-299 | Unassigned
```

I don't know whether we need to handle `unassigned` status codes.  You could check with @abperiasamy whether we need to handle `unassigned` status codes.

**Comment by donatello** [comment]
It says quite clearly right near the beginning:

`2xx: Success - The action was successfully received, understood, and accepted`. 

I think I already made my point about maintainability. But to reiterate - in the future if any new 2XX codes are assigned, the code will fail and will lead to significant debugging for users. Why would we not handle them when the standards body has already assigned the whole range?

**Comment by balamurugana** [comment]
Done

**Comment by kannappanr** [comment]
@balamurugana Have you had a chance to push the changes requested by @donatello ? I see your reply as `Done` but do not yet see the changes reflected.

**Comment by balamurugana** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-xl.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-dist-xl.sh | :heavy_check_mark: |
| mint-gateway-s3.sh | :heavy_check_mark: |
| mint-gateway-azure.sh | :x: [more...](#7588c763-0b87-48e1-8084-fea141b68528) |
<a name="7588c763-0b87-48e1-8084-fea141b68528"></a>
### 5792-138435d/mint-gateway-azure.sh.log:
```
Running with
SERVER_ENDPOINT: minikube:30604
ACCESS_KEY:      minioazure1
SECRET_KEY:      ***REDACTED***
ENABLE_HTTPS:    0
SERVER_REGION:   us-east-1
MINT_DATA_DIR:   /mint/data
MINT_MODE:       core

To get logs, run 'docker cp 1da50212dc16:/mint/log /tmp/mint-logs'
(1/12) Running aws-sdk-go tests ... done in 1 seconds
(2/12) Running aws-sdk-php tests ... done in 8 minutes and 19 seconds
(3/12) Running aws-sdk-ruby tests ... done in 49 seconds
(4/12) Running awscli tests ... done in 3 minutes and 53 seconds
(5/12) Running mc tests ... done in 7 minutes and 34 seconds
(6/12) Running minio-dotnet tests ... done in 1 minutes and 16 seconds
(7/12) Running minio-go tests ... done in 2 seconds
(8/12) Running minio-java tests ... done in 32 seconds
(9/12) Running minio-js tests ... FAILED in 2 minutes and 45 seconds
{
  "name": "minio-js",
  "function": "getBucketPolicy(bucketName, cb)",
  "args": "bucketName:minio-js-test-205bb91c-fb98-4a23-8c4b-08d5fd4650c6",
  "duration": 803,
  "status": "FAIL",
  "error": "S3Error: The bucket policy does not exist at Object.parseError (node_modules/minio/dist/main/xml-parsers.js:56:11) at /mint/run/core/minio-js/node_modules/minio/dist/main/transformers.js:117:22 at DestroyableTransform._flush (node_modules/minio/dist/main/transformers.js:48:26) at DestroyableTransform.<anonymous> (node_modules/minio/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:135:12) at finishMaybe (node_modules/minio/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:371:12) at endWritable (node_modules/minio/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:378:3) at DestroyableTransform.Writable.end (node_modules/minio/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:356:5) at IncomingMessage.onend (_stream_readable.js:511:10) at endReadableNT (_stream_readable.js:974:12) at _combinedTickCallback (internal/process/next_tick.js:80:11) at process._tickCallback (internal/process/next_tick.js:104:9)"
}

Executed 8 out of 12 tests successfully.
```

**Review by donatello — APPROVED** [review]

File: pkg/event/target/webhook.go [hunk 1]
```diff
@@ -79,12 +79,11 @@ func (target *WebhookTarget) Send(eventData event.Event) error {
 	// FIXME: log returned error. ignore time being.
 	_ = resp.Body.Close()
 
-	switch resp.StatusCode {
-	case http.StatusOK, http.StatusAccepted, http.StatusContinue:
-		return nil
-	default:
+	if resp.StatusCode < 200 || resp.StatusCode > 299 {
```
Comment (kannappanr) [inline pkg/event/target/webhook.go:82]: Instead of numbers, is it better to use constants like this ?
`if resp.StatusCode < http.StatusOK || resp.StatusCode >= http.StatusMultipleChoices {`

Comment (balamurugana) [reply pkg/event/target/webhook.go:82]: No. It's wrong. You need to check rfc in previous comments.

Comment (kannappanr) [reply pkg/event/target/webhook.go:82]: I am assuming that you mean that the rfc says `2xx` means success and it might be easier to read, if we have numbers than constants here.

**Review by kannappanr — APPROVED** [review]
LGTM
