### PR TITLE
posix: do not upstream errors in deleteFile

### LINKED ISSUE #4727: completeMultipartUpload completes the upload but reports NoSuchKey error
## Expected Behavior
Theoretically, the test.js file in the gist provided should run forever.

## Current Behavior
However, eventually it outputs the following error:

```
NoSuchKey: The specified key does not exist.
    at Request.extractError (/Users/kyle/Documents/scripts/minio-test/node_modules/aws-sdk/lib/services/s3.js:568:35)
    at Request.callListeners (/Users/kyle/Documents/scripts/minio-test/node_modules/aws-sdk/lib/sequential_executor.js:105:20)
    at Request.emit (/Users/kyle/Documents/scripts/minio-test/node_modules/aws-sdk/lib/sequential_executor.js:77:10)
    at Request.emit (/Users/kyle/Documents/scripts/minio-test/node_modules/aws-sdk/lib/request.js:682:14)
    at Request.transition (/Users/kyle/Documents/scripts/minio-test/node_modules/aws-sdk/lib/request.js:22:10)
    at AcceptorStateMachine.runTo (/Users/kyle/Documents/scripts/minio-test/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /Users/kyle/Documents/scripts/minio-test/node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> (/Users/kyle/Documents/scripts/minio-test/node_modules/aws-sdk/lib/request.js:38:9)
    at Request.<anonymous> (/Users/kyle/Documents/scripts/minio-test/node_modules/aws-sdk/lib/request.js:684:12)
    at Request.callListeners (/Users/kyle/Documents/scripts/minio-test/node_modules/aws-sdk/lib/sequential_executor.js:115:18)
    at Request.emit (/Users/kyle/Documents/scripts/minio-test/node_modules/aws-sdk/lib/sequential_executor.js:77:10)
    at Request.emit (/Users/kyle/Documents/scripts/minio-test/node_modules/aws-sdk/lib/request.js:682:14)
    at Request.transition (/Users/kyle/Documents/scripts/minio-test/node_modules/aws-sdk/lib/request.js:22:10)
    at AcceptorStateMachine.runTo (/Users/kyle/Documents/scripts/minio-test/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /Users/kyle/Documents/scripts/minio-test/node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> (/Users/kyle/Documents/scripts/minio-test/node_modules/aws-sdk/lib/request.js:38:9)
{ [NoSuchKey: The specified key does not exist.]
  cause:
   { [NoSuchKey: The specified key does not exist.]
     message: 'The specified key does not exist.',
     code: 'NoSuchKey',
     region: null,
     time: Wed Jul 26 2017 14:43:11 GMT-0400 (EDT),
     requestId: '14D4F593D38DBDEA',
     extendedRequestId: undefined,
     cfId: undefined,
     statusCode: 404,
     retryable: false,
     retryDelay: 32.2675014147535 },
  isOperational: true,
  code: 'NoSuchKey',
  region: null,
  time: Wed Jul 26 2017 14:43:11 GMT-0400 (EDT),
  requestId: '14D4F593D38DBDEA',
  extendedRequestId: undefined,
  cfId: undefined,
  statusCode: 404,
  retryable: false,
  retryDelay: 32.2675014147535 }
Object exists!
```

The completeMultipartUpload call appears to fail, but when I try to "head" the object, it says it exists, which leads me to believe that completeMultipartUpload was successful after all.

## Steps to Reproduce (for bugs)
Here is a gist: https://gist.github.com/kyleburnett/bb85c386162e2a32c6d092f7898ea6a4
1. Run `npm install` to install dependencies.
2. Run `node setup.js` to generate random data.
3. Replace "your accessKeyId here", "your secretAccessKey here", and "your endpoint here" in `test.js`
4. Run `test.js`.

## Context
I'm trying to upload many files concurrently. I originally discovered this issue because unit tests were failing every 20 or so runs.

## Your Environment
* On a Vagrant VM:
  * Minio: 2017-06-13T19:01:01Z
  * Docker: v1.11.1
  * OS: Ubuntu 14.04.4
* Host
  * Node.js: v4.4.7
  * OS: macOS Sierra v10.12.5

### PR DESCRIPTION
**Pull request by brendanashworth**
## Description
This commit changes posix's `deleteFile()` to not upstream errors from
removing parent directories. This fixes a race condition.

The race condition occurs when multiple `deleteFile()`s are called on the
same parent directory, but different child files. Because `deleteFile()`
recursively removes parent directories if they are empty, but
`deleteFile()` errors if the selected `deletePath` does not exist, there was
an opportunity for a race condition. The two processes would remove the
child directories successfully, then depend on the parent directory
still existing. In some cases this is an invalid assumption, because
other processes can remove the parent directory beforehand. This commit
changes `deleteFile()` to not upstream an error if one occurs, because the
only required error should be from the immediate `deletePath`, not from a
parent path.

In the specific bug report, multiple `CompleteMultipartUpload` requests
would launch multiple `deleteFile()` requests. Because they chain up on
parent directories, ultimately at the end, there would be multiple
remove files for the ultimate parent directory,
`.minio.sys/multipart/{bucket}`. Because only one will succeed and one
will fail, an error would be upstreamed saying that the file does not
exist, and the `CompleteMultipartUpload` code interpreted this as
`NoSuchKey`, or that the object/part id doesn't exist. This was faulty
behavior and is now fixed.

The added test fails before this change and passes after this change.

## Motivation and Context

Fixes: https://github.com/minio/minio/issues/4727

## How Has This Been Tested?
Locally (upstream.patch has fix to `cmd/posix.go`):
```
brendanashworth in ~/Go/src/github.com/minio/minio/cmd $ go test -test.run PosixDeleteFile -v
=== RUN   TestPosixDeleteFile
--- FAIL: TestPosixDeleteFile (0.34s)
	posix_test.go:795: TestPosix case 7: Expected: "%!s(<nil>)", got: "file access denied"
FAIL
exit status 1
FAIL	github.com/minio/minio/cmd	0.493s
brendanashworth in ~/Go/src/github.com/minio/minio/cmd $ git apply ../upstream.patch
brendanashworth in ~/Go/src/github.com/minio/minio/cmd $ go test -test.run PosixDeleteFile -v
=== RUN   TestPosixDeleteFile
--- PASS: TestPosixDeleteFile (0.18s)
PASS
ok  	github.com/minio/minio/cmd	0.261s
```

The test uses permissions (parent directory lacks write permission) to fail, but it fails similarly to how a non-existent directory fails.

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Review by harshavardhana — APPROVED** [review]

File: cmd/posix.go [hunk 1]
```diff
@@ -916,7 +916,10 @@ func deleteFile(basePath, deletePath string) error {
 	}
 
 	// Recursively go down the next path and delete again.
-	return deleteFile(basePath, slashpath.Dir(deletePath))
+	// Errors for parent directories shouldn't trickle down.
+	deleteFile(basePath, slashpath.Dir(deletePath))
```
Comment (krishnasrinivas) [inline cmd/posix.go:920]: The problem with this is if we fail to delete the file for some reason we never return error.

A better fix is to call this function `deleteDir()` which never returns error like how we do here. But delete the file instead in `DeleteFile()`

Comment (harshavardhana) [reply cmd/posix.go:920]: We don't @krishnasrinivas os.Remove() should have removed the expected file or directory by the time it reaches here. This is only the other empty/non-empty directories. If they failed for some reason it is okay to leave them as is.. since it wouldn't hurt IMO. 

If we didn't even return error for os.Remove() then it would mean something else entirely and that is not the case here.  The problem here is that there is no locking involved when the directories are being recursively deleted upwards, which is the reason why inherently deleteFile() is racy and has unexpected results when a concurrent deleteFile() is running along with any i/o with in the same prefix.

I would suggest that we can safely do this change in most cases since our expected nature was to delete an empty directory or file.   If we did so we hope that it is possible for us to delete the top level dirs if they are empty as well, if its not say someone created a file while it is being recursively traversed we are okay to not return an error since as a context we have never held a lock on that part of the namespace anyways.

Comment (harshavardhana) [reply cmd/posix.go:920]: In-fact this is quite nicely explained by @brendanashworth in the commit message that if deleteFile() is to work appropriately we are not supposed to return error for the top-level folders. Since by nature we have never locked that region of namespace anyways - we are only doing it based on a guess-work at that point in time.

Comment (krishnasrinivas) [reply cmd/posix.go:920]: I see

**Review by krishnasrinivas — APPROVED** [review]
