### PR TITLE
Check for absence of checksum and invalid checksum fields.

### LINKED ISSUE #6295: Crash: Unsupported bitrot algorithm
unable to heal minio

## Expected Behavior
I should be able to heal minio bucket

## Current Behavior
executing "mc admin heal --recursive --json --debug live-minio-4" ends with minio crashing.

## Logs

<details>
<summary>Logs</summary>
<pre><code>
Aug 16 22:45:51 live-minio-4 minio[11564]: API: SYSTEM()
Aug 16 22:45:51 live-minio-4 minio[11564]: Time: 22:45:51 EEST 08/16/2018
Aug 16 22:45:51 live-minio-4 minio[11564]: Error: Unsupported bitrot algorithm
Aug 16 22:45:51 live-minio-4 minio[11564]:        1: cmd/logger/logger.go:326:logger.CriticalIf()
Aug 16 22:45:51 live-minio-4 minio[11564]:        2: cmd/xl-v1-metadata.go:77:cmd.BitrotAlgorithm.New()
Aug 16 22:45:51 live-minio-4 minio[11564]:        3: cmd/erasure.go:102:cmd.NewBitrotVerifier()
Aug 16 22:45:51 live-minio-4 minio[11564]:        4: cmd/xl-v1-healing-common.go:182:cmd.disksWithAllParts()
Aug 16 22:45:51 live-minio-4 minio[11564]:        5: cmd/xl-v1-healing.go:308:cmd.healObject()
Aug 16 22:45:51 live-minio-4 minio[11564]:        6: cmd/xl-v1-healing.go:627:cmd.xlObjects.HealObject()
Aug 16 22:45:51 live-minio-4 minio[11564]:        7: cmd/xl-sets.go:1230:cmd.(*xlSets).HealObject()
Aug 16 22:45:51 live-minio-4 minio[11564]:        8: cmd/admin-heal-ops.go:658:cmd.(*healSequence).healObject()
Aug 16 22:45:51 live-minio-4 minio[11564]:        9: cmd/admin-heal-ops.go:635:cmd.(*healSequence).healBucket()
Aug 16 22:45:51 live-minio-4 minio[11564]:       10: cmd/admin-heal-ops.go:577:cmd.(*healSequence).healBuckets()
Aug 16 22:45:51 live-minio-4 minio[11564]:       11: cmd/admin-heal-ops.go:523:cmd.healBuckets)-fm()
Aug 16 22:45:51 live-minio-4 minio[11564]:       12: cmd/admin-heal-ops.go:516:cmd.(*healSequence).traverseAndHeal.func1()
Aug 16 22:45:51 live-minio-4 minio[11564]:       13: cmd/admin-heal-ops.go:523:cmd.(*healSequence).traverseAndHeal()
Aug 16 22:45:51 live-minio-4 minio[11564]: panic: (struct {}) (0x1158e60,0x1eac830)
Aug 16 22:45:51 live-minio-4 minio[11564]: goroutine 2130102 [running]:
Aug 16 22:45:51 live-minio-4 minio[11564]: github.com/minio/minio/cmd/logger.CriticalIf(0x146cee0, 0xc42003c960, 0x145c4c0, 0xc4233c3860)
Aug 16 22:45:51 live-minio-4 minio[11564]: #011/q/.q/sources/gopath/src/github.com/minio/minio/cmd/logger/logger.go:327 +0x74
Aug 16 22:45:51 live-minio-4 minio[11564]: github.com/minio/minio/cmd.BitrotAlgorithm.New(0x0, 0x2, 0x2)
Aug 16 22:45:51 live-minio-4 minio[11564]: #011/q/.q/sources/gopath/src/github.com/minio/minio/cmd/xl-v1-metadata.go:77 +0xac
Aug 16 22:45:51 live-minio-4 minio[11564]: github.com/minio/minio/cmd.NewBitrotVerifier(0x0, 0x0, 0x0, 0x0, 0xa00000)
Aug 16 22:45:51 live-minio-4 minio[11564]: #011/q/.q/sources/gopath/src/github.com/minio/minio/cmd/erasure.go:102 +0x2f
Aug 16 22:45:51 live-minio-4 minio[11564]: github.com/minio/minio/cmd.disksWithAllParts(0x146cf60, 0xc424872360, 0xc422774900, 0x10, 0x10, 0xc420e18000, 0x10, 0x10, 0xc422774300, 0x10, ...)
Aug 16 22:45:51 live-minio-4 minio[11564]: #011/q/.q/sources/gopath/src/github.com/minio/minio/cmd/xl-v1-healing-common.go:182 +0x306
Aug 16 22:45:51 live-minio-4 minio[11564]: github.com/minio/minio/cmd.healObject(0x146cf60, 0xc424872360, 0xc422774200, 0x10, 0x10, 0xc42010a3eb, 0x7, 0xc42984b800, 0x34, 0xb, ...)
Aug 16 22:45:51 live-minio-4 minio[11564]: #011/q/.q/sources/gopath/src/github.com/minio/minio/cmd/xl-v1-healing.go:308 +0x28e
Aug 16 22:45:51 live-minio-4 minio[11564]: github.com/minio/minio/cmd.xlObjects.HealObject(0xc42045f340, 0xc42045f380, 0xc42045f360, 0x0, 0x0, 0x0, 0x0, 0x146cf60, 0xc424872360, 0xc42010a3eb, ...)
Aug 16 22:45:51 live-minio-4 minio[11564]: #011/q/.q/sources/gopath/src/github.com/minio/minio/cmd/xl-v1-healing.go:627 +0x38d
Aug 16 22:45:51 live-minio-4 minio[11564]: github.com/minio/minio/cmd.(*xlSets).HealObject(0xc420432b40, 0x146cf60, 0xc424872360, 0xc42010a3eb, 0x7, 0xc42984b800, 0x34, 0x0, 0x0, 0x0, ...)
Aug 16 22:45:51 live-minio-4 minio[11564]: #011/q/.q/sources/gopath/src/github.com/minio/minio/cmd/xl-sets.go:1230 +0x128
Aug 16 22:45:51 live-minio-4 minio[11564]: github.com/minio/minio/cmd.(*healSequence).healObject(0xc420738300, 0xc42010a3eb, 0x7, 0xc42984b800, 0x34, 0x0, 0x0)
Aug 16 22:45:51 live-minio-4 minio[11564]: #011/q/.q/sources/gopath/src/github.com/minio/minio/cmd/admin-heal-ops.go:658 +0xf4
Aug 16 22:45:51 live-minio-4 minio[11564]: github.com/minio/minio/cmd.(*healSequence).healBucket(0xc420738300, 0xc42010a3eb, 0x7, 0xc422bb05a0, 0x2)
Aug 16 22:45:51 live-minio-4 minio[11564]: #011/q/.q/sources/gopath/src/github.com/minio/minio/cmd/admin-heal-ops.go:635 +0x2ec
Aug 16 22:45:51 live-minio-4 minio[11564]: github.com/minio/minio/cmd.(*healSequence).healBuckets(0xc420738300, 0xc4200a41e0, 0xc42523df00)
Aug 16 22:45:51 live-minio-4 minio[11564]: #011/q/.q/sources/gopath/src/github.com/minio/minio/cmd/admin-heal-ops.go:577 +0x157
Aug 16 22:45:51 live-minio-4 minio[11564]: github.com/minio/minio/cmd.(*healSequence).(github.com/minio/minio/cmd.healBuckets)-fm(0xc420738300, 0x0)
Aug 16 22:45:51 live-minio-4 minio[11564]: #011/q/.q/sources/gopath/src/github.com/minio/minio/cmd/admin-heal-ops.go:523 +0x2a
Aug 16 22:45:51 live-minio-4 minio[11564]: github.com/minio/minio/cmd.(*healSequence).traverseAndHeal.func1(0xc420566bd0)
Aug 16 22:45:51 live-minio-4 minio[11564]: #011/q/.q/sources/gopath/src/github.com/minio/minio/cmd/admin-heal-ops.go:516 +0x8f
Aug 16 22:45:51 live-minio-4 minio[11564]: github.com/minio/minio/cmd.(*healSequence).traverseAndHeal(0xc420738300)
Aug 16 22:45:51 live-minio-4 minio[11564]: #011/q/.q/sources/gopath/src/github.com/minio/minio/cmd/admin-heal-ops.go:523 +0xd9
Aug 16 22:45:51 live-minio-4 minio[11564]: created by github.com/minio/minio/cmd.(*healSequence).healSequenceStart
Aug 16 22:45:51 live-minio-4 minio[11564]: #011/q/.q/sources/gopath/src/github.com/minio/minio/cmd/admin-heal-ops.go:466 +0xf0
Aug 16 22:45:51 live-minio-4 systemd[1]: minio.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
Aug 16 22:45:51 live-minio-4 systemd[1]: minio.service: Unit entered failed state.
Aug 16 22:45:51 live-minio-4 systemd[1]: minio.service: Failed with result 'exit-code'.
</code></pre>
</details>

## Your Environment
* Version used (`minio version`): 2018-08-02T23:11:36Z
* Operating System and version (`uname -a`): 4.9.0-6-amd64 #1 SMP Debian 4.9.88-1+deb9u1 (2018-05-07) x86_64 GNU/Linux

### PR DESCRIPTION
**Pull request by kannappanr**
## Description
This fix currently handles only invalid checksum values or the absence of checksum values.

## Motivation and Context
Fixes #6295

## How Has This Been Tested?
Manually

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added unit tests to cover my changes.
- [ ] I have added/updated functional tests in [mint](https://github.com/minio/mint). (If yes, add `mint` PR # here: )
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by minio-ops** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-gateway-s3.sh | :heavy_check_mark: |
| mint-gateway-azure.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-worm.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-xl.sh | :x: [more...](#733fc4ff-1199-4031-825a-111409aece5e) |
| mint-large-bucket.sh | :x: [more...](#da3fd2ff-cf26-40b7-826a-281b175622fb) |
| mint-dist-xl.sh | :x: [more...](#2ca2d730-e6e5-4826-b25d-b5913c0986b0) |
<a name="733fc4ff-1199-4031-825a-111409aece5e"></a>
### 6298-06dad47/mint-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      minikube:31792
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp e47b4da63f09:/mint/log /tmp/mint-logs'
(1/13) Running awscli tests ... FAILED in 53 seconds
{"name": "awscli", "duration": 32236, "function": "aws --endpoint-url http://minikube:31792 s3 cp /mint/data/datafile-65-MB s3://awscli-mint-test-bucket-15703/datafile-65-MB\n", "status": "FAIL", "error": "Completed 256.0 KiB/65.0 MiB (202.8 KiB/s) with 1 file(s) remaining
Completed 512.0 KiB/65.0 MiB (403.7 KiB/s) with 1 file(s) remaining
Completed 768.0 KiB/65.0 MiB (604.3 KiB/s) with 1 file(s) remaining
Completed 1.0 MiB/65.0 MiB (805.2 KiB/s) with 1 file(s) remaining  
Completed 1.2 MiB/65.0 MiB (706.9 KiB/s) with 1 file(s) remaining  
Completed 1.5 MiB/65.0 MiB (847.7 KiB/s) with 1 file(s) remaining  
Completed 1.8 MiB/65.0 MiB (981.5 KiB/s) with 1 file(s) remaining  
Completed 2.0 MiB/65.0 MiB (1.1 MiB/s) with 1 file(s) remaining    
Completed 2.2 MiB/65.0 MiB (1.2 MiB/s) with 1 file(s) remaining    
Completed 2.5 MiB/65.0 MiB (1.4 MiB/s) with 1 file(s) remaining    
Completed 2.8 MiB/65.0 MiB (1.5 MiB/s) with 1 file(s) remaining    
Completed 3.0 MiB/65.0 MiB (1.6 MiB/s) with 1 file(s) remaining    
Completed 3.2 MiB/65.0 MiB (1.8 MiB/s) with 1 file(s) remaining    
Completed 3.5 MiB/65.0 MiB (1.9 MiB/s) with 1 file(s) remaining    
Completed 3.8 MiB/65.0 MiB (2.0 MiB/s) with 1 file(s) remaining    
Completed 4.0 MiB/65.0 MiB (2.2 MiB/s) with 1 file(s) remaining    
Completed 4.2 MiB/65.0 MiB (2.3 MiB/s) with 1 file(s) remaining    
Completed 4.5 MiB/65.0 MiB (2.4 MiB/s) with 1 file(s) remaining    
Completed 4.8 MiB/65.0 MiB (2.5 MiB/s) with 1 file(s) remaining    
Completed 5.0 MiB/65.0 MiB (2.7 MiB/s) with 1 file(s) remaining    
Completed 5.2 MiB/65.0 MiB (2.8 MiB/s) with 1 file(s) remaining    
Completed 5.5 MiB/65.0 MiB (2.9 MiB/s) with 1 file(s) remaining    
Completed 5.8 MiB/65.0 MiB (3.1 MiB/s) with 1 file(s) remaining    
Completed 6.0 MiB/65.0 MiB (3.2 MiB/s) with 1 file(s) remaining    
Completed 6.2 MiB/65.0 MiB (3.3 MiB/s) with 1 file(s) remaining    
Completed 6.5 MiB/65.0 MiB (3.4 MiB/s) with 1 file(s) remaining    
Completed 6.8 MiB/65.0 MiB (3.6 MiB/s) with 1 file(s) remaining    
Completed 7.0 MiB/65.0 MiB (3.7 MiB/s) with 1 file(s) remaining    
Completed 7.2 MiB/65.0 MiB (3.8 MiB/s) with 1 file(s) remaining    
Completed 7.5 MiB/65.0 MiB (3.9 MiB/s) with 1 file(s) remaining    
Completed 7.8 MiB/65.0 MiB (4.1 MiB/s) with 1 file(s) remaining    
Completed 8.0 MiB/65.0 MiB (4.2 MiB/s) with 1 file(s) remaining    
Completed 8.2 MiB/65.0 MiB (4.3 MiB/s) with 1 file(s) remaining    
Completed 8.5 MiB/65.0 MiB (4.4 MiB/s) with 1 file(s) remaining    
Completed 8.8 MiB/65.0 MiB (4.5 MiB/s) with 1 file(s) remaining    
Completed 9.0 MiB/65.0 MiB (4.7 MiB/s) with 1 file(s) remaining    
Completed 9.2 MiB/65.0 MiB (4.8 MiB/s) with 1 file(s) remaining    
Completed 9.5 MiB/65.0 MiB (4.9 MiB/s) with 1 file(s) remaining    
Completed 9.8 MiB/65.0 MiB (5.0 MiB/s) with 1 file(s) remaining    
Completed 10.0 MiB/65.0 MiB (5.1 MiB/s) with 1 file(s) remaining   
Completed 10.2 MiB/65.0 MiB (5.2 MiB/s) with 1 file(s) remaining   
Completed 10.5 MiB/65.0 MiB (5.3 MiB/s) with 1 file(s) remaining   
Completed 10.8 MiB/65.0 MiB (5.5 MiB/s) with 1 file(s) remaining   
Completed 11.0 MiB/65.0 MiB (5.6 MiB/s) with 1 file(s) remaining   
Completed 11.2 MiB/65.0 MiB (5.7 MiB/s) with 1 file(s) remaining   
Completed 11.5 MiB/65.0 MiB (5.8 MiB/s) with 1 file(s) remaining   
Completed 11.8 MiB/65.0 MiB (5.8 MiB/s) with 1 file(s) remaining   
Completed 12.0 MiB/65.0 MiB (5.9 MiB/s) with 1 file(s) remaining   
Completed 12.2 MiB/65.0 MiB (6.0 MiB/s) with 1 file(s) remaining   
Completed 12.5 MiB/65.0 MiB (6.1 MiB/s) with 1 file(s) remaining   
Completed 12.8 MiB/65.0 MiB (6.2 MiB/s) with 1 file(s) remaining   
Completed 13.0 MiB/65.0 MiB (6.3 MiB/s) with 1 file(s) remaining   
Completed 13.2 MiB/65.0 MiB (6.3 MiB/s) with 1 file(s) remaining   
Completed 13.5 MiB/65.0 MiB (6.3 MiB/s) with 1 file(s) remaining   
Completed 13.8 MiB/65.0 MiB (6.4 MiB/s) with 1 file(s) remaining   
Completed 14.0 MiB/65.0 MiB (6.5 MiB/s) with 1 file(s) remaining   
Completed 14.2 MiB/65.0 MiB (6.6 MiB/s) with 1 file(s) remaining   
Completed 14.5 MiB/65.0 MiB (6.7 MiB/s) with 1 file(s) remaining   
Completed 14.8 MiB/65.0 MiB (6.7 MiB/s) with 1 file(s) remaining   
Completed 15.0 MiB/65.0 MiB (6.8 MiB/s) with 1 file(s) remaining   
Completed 15.2 MiB/65.0 MiB (6.9 MiB/s) with 1 file(s) remaining   
Completed 15.5 MiB/65.0 MiB (7.0 MiB/s) with 1 file(s) remaining   
Completed 15.8 MiB/65.0 MiB (7.1 MiB/s) with 1 file(s) remaining   
Completed 16.0 MiB/65.0 MiB (7.1 MiB/s) with 1 file(s) remaining   
Completed 16.2 MiB/65.0 MiB (7.2 MiB/s) with 1 file(s) remaining   
Completed 16.5 MiB/65.0 MiB (7.2 MiB/s) with 1 file(s) remaining   
Completed 16.8 MiB/65.0 MiB (7.2 MiB/s) with 1 file(s) remaining   
Completed 17.0 MiB/65.0 MiB (7.3 MiB/s) with 1 file(s) remaining   
Completed 17.2 MiB/65.0 MiB (4.7 MiB/s) with 1 file(s) remaining   
Completed 17.5 MiB/65.0 MiB (4.6 MiB/s) with 1 file(s) remaining   
Completed 17.8 MiB/65.0 MiB (4.6 MiB/s) with 1 file(s) remaining   
Completed 18.0 MiB/65.0 MiB (4.5 MiB/s) with 1 file(s) remaining   
Completed 18.2 MiB/65.0 MiB (4.1 MiB/s) with 1 file(s) remaining   
Completed 18.5 MiB/65.0 MiB (4.1 MiB/s) with 1 file(s) remaining   
Completed 18.8 MiB/65.0 MiB (4.0 MiB/s) with 1 file(s) remaining   
Completed 19.0 MiB/65.0 MiB (4.0 MiB/s) with 1 file(s) remaining   
Completed 19.2 MiB/65.0 MiB (3.3 MiB/s) with 1 file(s) remaining   
Completed 19.5 MiB/65.0 MiB (3.2 MiB/s) with 1 file(s) remaining   
Completed 19.8 MiB/65.0 MiB (3.2 MiB/s) with 1 file(s) remaining   
Completed 20.0 MiB/65.0 MiB (2.7 MiB/s) with 1 file(s) remaining   
Completed 20.2 MiB/65.0 MiB (2.7 MiB/s) with 1 file(s) remaining   
Completed 20.5 MiB/65.0 MiB (2.8 MiB/s) with 1 file(s) remaining   
Completed 20.8 MiB/65.0 MiB (2.7 MiB/s) with 1 file(s) remaining   
Completed 21.0 MiB/65.0 MiB (2.7 MiB/s) with 1 file(s) remaining   
Completed 21.2 MiB/65.0 MiB (2.7 MiB/s) with 1 file(s) remaining   
Completed 21.5 MiB/65.0 MiB (2.1 MiB/s) with 1 file(s) remaining   
Completed 21.6 MiB/65.0 MiB (1.6 MiB/s) with 1 file(s) remaining   
upload failed: ../../../data/datafile-65-MB to s3://awscli-mint-test-bucket-15703/datafile-65-MB ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))"}

Executed 0 out of 13 tests successfully.
```
<a name="da3fd2ff-cf26-40b7-826a-281b175622fb"></a>
### 6298-06dad47/mint-large-bucket.sh.log:
```
Running with
SERVER_ENDPOINT:      minikube:31222
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp bff9b0946fc9:/mint/log /tmp/mint-logs'
(1/13) Running awscli tests ... FAILED in 30 seconds
{"name": "awscli", "duration": 21335, "function": "aws --endpoint-url http://minikube:31222 s3 cp /mint/data/datafile-65-MB s3://awscli-mint-test-bucket-31323/datafile-65-MB\n", "status": "FAIL", "error": "Completed 256.0 KiB/65.0 MiB (233.3 KiB/s) with 1 file(s) remaining
Completed 512.0 KiB/65.0 MiB (466.3 KiB/s) with 1 file(s) remaining
Completed 768.0 KiB/65.0 MiB (699.1 KiB/s) with 1 file(s) remaining
Completed 1.0 MiB/65.0 MiB (931.6 KiB/s) with 1 file(s) remaining  
Completed 1.2 MiB/65.0 MiB (1.0 MiB/s) with 1 file(s) remaining    
Completed 1.5 MiB/65.0 MiB (1.2 MiB/s) with 1 file(s) remaining    
Completed 1.8 MiB/65.0 MiB (1.4 MiB/s) with 1 file(s) remaining    
Completed 2.0 MiB/65.0 MiB (1.6 MiB/s) with 1 file(s) remaining    
Completed 2.2 MiB/65.0 MiB (1.8 MiB/s) with 1 file(s) remaining    
Completed 2.5 MiB/65.0 MiB (2.0 MiB/s) with 1 file(s) remaining    
Completed 2.8 MiB/65.0 MiB (2.2 MiB/s) with 1 file(s) remaining    
Completed 3.0 MiB/65.0 MiB (2.4 MiB/s) with 1 file(s) remaining    
Completed 3.2 MiB/65.0 MiB (2.6 MiB/s) with 1 file(s) remaining    
Completed 3.5 MiB/65.0 MiB (2.8 MiB/s) with 1 file(s) remaining    
Completed 3.8 MiB/65.0 MiB (3.0 MiB/s) with 1 file(s) remaining    
Completed 4.0 MiB/65.0 MiB (3.1 MiB/s) with 1 file(s) remaining    
Completed 4.2 MiB/65.0 MiB (3.3 MiB/s) with 1 file(s) remaining    
Completed 4.5 MiB/65.0 MiB (3.4 MiB/s) with 1 file(s) remaining    
Completed 4.8 MiB/65.0 MiB (3.6 MiB/s) with 1 file(s) remaining    
Completed 5.0 MiB/65.0 MiB (3.8 MiB/s) with 1 file(s) remaining    
Completed 5.2 MiB/65.0 MiB (4.0 MiB/s) with 1 file(s) remaining    
Completed 5.5 MiB/65.0 MiB (4.2 MiB/s) with 1 file(s) remaining    
Completed 5.8 MiB/65.0 MiB (4.4 MiB/s) with 1 file(s) remaining    
Completed 6.0 MiB/65.0 MiB (4.5 MiB/s) with 1 file(s) remaining    
Completed 6.2 MiB/65.0 MiB (4.6 MiB/s) with 1 file(s) remaining    
Completed 6.5 MiB/65.0 MiB (4.8 MiB/s) with 1 file(s) remaining    
Completed 6.8 MiB/65.0 MiB (5.0 MiB/s) with 1 file(s) remaining    
Completed 7.0 MiB/65.0 MiB (5.0 MiB/s) with 1 file(s) remaining    
Completed 7.2 MiB/65.0 MiB (5.2 MiB/s) with 1 file(s) remaining    
Completed 7.5 MiB/65.0 MiB (5.3 MiB/s) with 1 file(s) remaining    
Completed 7.8 MiB/65.0 MiB (5.4 MiB/s) with 1 file(s) remaining    
Completed 8.0 MiB/65.0 MiB (5.4 MiB/s) with 1 file(s) remaining    
Completed 8.2 MiB/65.0 MiB (5.6 MiB/s) with 1 file(s) remaining    
Completed 8.5 MiB/65.0 MiB (5.7 MiB/s) with 1 file(s) remaining    
Completed 8.8 MiB/65.0 MiB (5.9 MiB/s) with 1 file(s) remaining    
Completed 9.0 MiB/65.0 MiB (5.6 MiB/s) with 1 file(s) remaining    
Completed 9.2 MiB/65.0 MiB (5.7 MiB/s) with 1 file(s) remaining    
Completed 9.5 MiB/65.0 MiB (5.8 MiB/s) with 1 file(s) remaining    
Completed 9.8 MiB/65.0 MiB (5.9 MiB/s) with 1 file(s) remaining    
Completed 10.0 MiB/65.0 MiB (6.0 MiB/s) with 1 file(s) remaining   
Completed 10.2 MiB/65.0 MiB (6.1 MiB/s) with 1 file(s) remaining   
Completed 10.5 MiB/65.0 MiB (6.3 MiB/s) with 1 file(s) remaining   
Completed 10.8 MiB/65.0 MiB (6.2 MiB/s) with 1 file(s) remaining   
Completed 11.0 MiB/65.0 MiB (3.4 MiB/s) with 1 file(s) remaining   
Completed 11.2 MiB/65.0 MiB (3.4 MiB/s) with 1 file(s) remaining   
Completed 11.5 MiB/65.0 MiB (3.4 MiB/s) with 1 file(s) remaining   
Completed 11.8 MiB/65.0 MiB (3.4 MiB/s) with 1 file(s) remaining   
Completed 12.0 MiB/65.0 MiB (3.4 MiB/s) with 1 file(s) remaining   
Completed 12.2 MiB/65.0 MiB (3.4 MiB/s) with 1 file(s) remaining   
Completed 12.5 MiB/65.0 MiB (3.5 MiB/s) with 1 file(s) remaining   
Completed 12.8 MiB/65.0 MiB (3.4 MiB/s) with 1 file(s) remaining   
Completed 13.0 MiB/65.0 MiB (3.1 MiB/s) with 1 file(s) remaining   
Completed 13.2 MiB/65.0 MiB (3.1 MiB/s) with 1 file(s) remaining   
Completed 13.5 MiB/65.0 MiB (3.2 MiB/s) with 1 file(s) remaining   
Completed 13.8 MiB/65.0 MiB (2.2 MiB/s) with 1 file(s) remaining   
Completed 14.0 MiB/65.0 MiB (2.1 MiB/s) with 1 file(s) remaining   
Completed 14.2 MiB/65.0 MiB (2.1 MiB/s) with 1 file(s) remaining   
upload failed: ../../../data/datafile-65-MB to s3://awscli-mint-test-bucket-31323/datafile-65-MB An error occurred (InternalError) when calling the UploadPart operation (reached max retries: 4): We encountered an internal error, please try again."}

Executed 0 out of 13 tests successfully.
```
<a name="2ca2d730-e6e5-4826-b25d-b5913c0986b0"></a>
### 6298-06dad47/mint-dist-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      minikube:31713
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 874d0b4c715f:/mint/log /tmp/mint-logs'
(1/13) Running awscli tests ... FAILED in 40 seconds
{"name": "awscli", "duration": 19901, "function": "aws --endpoint-url http://minikube:31713 s3 cp /mint/data/datafile-65-MB s3://awscli-mint-test-bucket-23838/datafile-65-MB\n", "status": "FAIL", "error": "Completed 256.0 KiB/65.0 MiB (197.4 KiB/s) with 1 file(s) remaining
Completed 512.0 KiB/65.0 MiB (394.7 KiB/s) with 1 file(s) remaining
Completed 768.0 KiB/65.0 MiB (591.8 KiB/s) with 1 file(s) remaining
Completed 1.0 MiB/65.0 MiB (788.7 KiB/s) with 1 file(s) remaining  
Completed 1.2 MiB/65.0 MiB (766.4 KiB/s) with 1 file(s) remaining  
Completed 1.5 MiB/65.0 MiB (910.9 KiB/s) with 1 file(s) remaining  
Completed 1.8 MiB/65.0 MiB (1.0 MiB/s) with 1 file(s) remaining    
Completed 2.0 MiB/65.0 MiB (1.2 MiB/s) with 1 file(s) remaining    
Completed 2.2 MiB/65.0 MiB (1.3 MiB/s) with 1 file(s) remaining    
Completed 2.5 MiB/65.0 MiB (1.5 MiB/s) with 1 file(s) remaining    
Completed 2.8 MiB/65.0 MiB (1.6 MiB/s) with 1 file(s) remaining    
Completed 3.0 MiB/65.0 MiB (1.7 MiB/s) with 1 file(s) remaining    
Completed 3.2 MiB/65.0 MiB (1.8 MiB/s) with 1 file(s) remaining    
Completed 3.5 MiB/65.0 MiB (1.9 MiB/s) with 1 file(s) remaining    
Completed 3.8 MiB/65.0 MiB (2.0 MiB/s) with 1 file(s) remaining    
Completed 4.0 MiB/65.0 MiB (2.2 MiB/s) with 1 file(s) remaining    
Completed 4.2 MiB/65.0 MiB (2.3 MiB/s) with 1 file(s) remaining    
Completed 4.5 MiB/65.0 MiB (2.4 MiB/s) with 1 file(s) remaining    
Completed 4.8 MiB/65.0 MiB (2.5 MiB/s) with 1 file(s) remaining    
Completed 5.0 MiB/65.0 MiB (2.7 MiB/s) with 1 file(s) remaining    
Completed 5.2 MiB/65.0 MiB (2.8 MiB/s) with 1 file(s) remaining    
Completed 5.5 MiB/65.0 MiB (2.9 MiB/s) with 1 file(s) remaining    
Completed 5.8 MiB/65.0 MiB (3.1 MiB/s) with 1 file(s) remaining    
Completed 6.0 MiB/65.0 MiB (3.2 MiB/s) with 1 file(s) remaining    
Completed 6.2 MiB/65.0 MiB (3.3 MiB/s) with 1 file(s) remaining    
Completed 6.5 MiB/65.0 MiB (3.5 MiB/s) with 1 file(s) remaining    
Completed 6.8 MiB/65.0 MiB (3.6 MiB/s) with 1 file(s) remaining    
Completed 7.0 MiB/65.0 MiB (3.7 MiB/s) with 1 file(s) remaining    
Completed 7.2 MiB/65.0 MiB (3.8 MiB/s) with 1 file(s) remaining    
Completed 7.5 MiB/65.0 MiB (3.9 MiB/s) with 1 file(s) remaining    
Completed 7.8 MiB/65.0 MiB (4.1 MiB/s) with 1 file(s) remaining    
Completed 8.0 MiB/65.0 MiB (4.2 MiB/s) with 1 file(s) remaining    
Completed 8.2 MiB/65.0 MiB (4.3 MiB/s) with 1 file(s) remaining    
Completed 8.5 MiB/65.0 MiB (4.4 MiB/s) with 1 file(s) remaining    
Completed 8.8 MiB/65.0 MiB (4.5 MiB/s) with 1 file(s) remaining    
Completed 9.0 MiB/65.0 MiB (4.6 MiB/s) with 1 file(s) remaining    
Completed 9.2 MiB/65.0 MiB (4.7 MiB/s) with 1 file(s) remaining    
Completed 9.5 MiB/65.0 MiB (4.8 MiB/s) with 1 file(s) remaining    
Completed 9.8 MiB/65.0 MiB (4.9 MiB/s) with 1 file(s) remaining    
Completed 10.0 MiB/65.0 MiB (5.0 MiB/s) with 1 file(s) remaining   
Completed 10.2 MiB/65.0 MiB (5.1 MiB/s) with 1 file(s) remaining   
Completed 10.5 MiB/65.0 MiB (5.2 MiB/s) with 1 file(s) remaining   
Completed 10.8 MiB/65.0 MiB (5.3 MiB/s) with 1 file(s) remaining   
Completed 11.0 MiB/65.0 MiB (5.4 MiB/s) with 1 file(s) remaining   
Completed 11.2 MiB/65.0 MiB (5.5 MiB/s) with 1 file(s) remaining   
Completed 11.5 MiB/65.0 MiB (5.6 MiB/s) with 1 file(s) remaining   
Completed 11.8 MiB/65.0 MiB (5.7 MiB/s) with 1 file(s) remaining   
Completed 12.0 MiB/65.0 MiB (5.8 MiB/s) with 1 file(s) remaining   
Completed 12.2 MiB/65.0 MiB (5.9 MiB/s) with 1 file(s) remaining   
Completed 12.5 MiB/65.0 MiB (6.0 MiB/s) with 1 file(s) remaining   
Completed 12.8 MiB/65.0 MiB (6.0 MiB/s) with 1 file(s) remaining   
Completed 13.0 MiB/65.0 MiB (6.1 MiB/s) with 1 file(s) remaining   
Completed 13.2 MiB/65.0 MiB (6.2 MiB/s) with 1 file(s) remaining   
Completed 13.5 MiB/65.0 MiB (6.3 MiB/s) with 1 file(s) remaining   
Completed 13.8 MiB/65.0 MiB (6.4 MiB/s) with 1 file(s) remaining   
Completed 14.0 MiB/65.0 MiB (6.4 MiB/s) with 1 file(s) remaining   
Completed 14.2 MiB/65.0 MiB (6.5 MiB/s) with 1 file(s) remaining   
Completed 14.5 MiB/65.0 MiB (6.6 MiB/s) with 1 file(s) remaining   
Completed 14.8 MiB/65.0 MiB (6.7 MiB/s) with 1 file(s) remaining   
Completed 15.0 MiB/65.0 MiB (6.7 MiB/s) with 1 file(s) remaining   
Completed 15.2 MiB/65.0 MiB (6.8 MiB/s) with 1 file(s) remaining   
Completed 15.5 MiB/65.0 MiB (6.9 MiB/s) with 1 file(s) remaining   
Completed 15.8 MiB/65.0 MiB (6.9 MiB/s) with 1 file(s) remaining   
Completed 16.0 MiB/65.0 MiB (7.0 MiB/s) with 1 file(s) remaining   
Completed 16.2 MiB/65.0 MiB (7.1 MiB/s) with 1 file(s) remaining   
Completed 16.5 MiB/65.0 MiB (7.2 MiB/s) with 1 file(s) remaining   
Completed 16.8 MiB/65.0 MiB (7.2 MiB/s) with 1 file(s) remaining   
Completed 17.0 MiB/65.0 MiB (7.3 MiB/s) with 1 file(s) remaining   
Completed 17.2 MiB/65.0 MiB (7.4 MiB/s) with 1 file(s) remaining   
Completed 17.5 MiB/65.0 MiB (7.4 MiB/s) with 1 file(s) remaining   
Completed 17.8 MiB/65.0 MiB (7.5 MiB/s) with 1 file(s) remaining   
Completed 18.0 MiB/65.0 MiB (7.6 MiB/s) with 1 file(s) remaining   
Completed 18.2 MiB/65.0 MiB (7.7 MiB/s) with 1 file(s) remaining   
Completed 18.5 MiB/65.0 MiB (4.4 MiB/s) with 1 file(s) remaining   
Completed 18.8 MiB/65.0 MiB (4.2 MiB/s) with 1 file(s) remaining   
Completed 19.0 MiB/65.0 MiB (4.2 MiB/s) with 1 file(s) remaining   
Completed 19.2 MiB/65.0 MiB (4.2 MiB/s) with 1 file(s) remaining   
Completed 19.5 MiB/65.0 MiB (4.1 MiB/s) with 1 file(s) remaining   
Completed 19.8 MiB/65.0 MiB (4.2 MiB/s) with 1 file(s) remaining   
Completed 20.0 MiB/65.0 MiB (4.2 MiB/s) with 1 file(s) remaining   
Completed 20.2 MiB/65.0 MiB (4.2 MiB/s) with 1 file(s) remaining   
Completed 20.5 MiB/65.0 MiB (4.3 MiB/s) with 1 file(s) remaining   
Completed 20.8 MiB/65.0 MiB (3.2 MiB/s) with 1 file(s) remaining   
Completed 21.0 MiB/65.0 MiB (3.2 MiB/s) with 1 file(s) remaining   
Completed 21.2 MiB/65.0 MiB (3.2 MiB/s) with 1 file(s) remaining   
Completed 21.5 MiB/65.0 MiB (3.2 MiB/s) with 1 file(s) remaining   
Completed 21.8 MiB/65.0 MiB (3.2 MiB/s) with 1 file(s) remaining   
Completed 22.0 MiB/65.0 MiB (3.2 MiB/s) with 1 file(s) remaining   
Completed 22.2 MiB/65.0 MiB (3.2 MiB/s) with 1 file(s) remaining   
Completed 22.5 MiB/65.0 MiB (3.3 MiB/s) with 1 file(s) remaining   
Completed 22.8 MiB/65.0 MiB (3.3 MiB/s) with 1 file(s) remaining   
Completed 23.0 MiB/65.0 MiB (3.3 MiB/s) with 1 file(s) remaining   
Completed 23.2 MiB/65.0 MiB (3.3 MiB/s) with 1 file(s) remaining   
Completed 23.5 MiB/65.0 MiB (3.3 MiB/s) with 1 file(s) remaining   
Completed 23.8 MiB/65.0 MiB (3.3 MiB/s) with 1 file(s) remaining   
Completed 24.0 MiB/65.0 MiB (3.4 MiB/s) with 1 file(s) remaining   
Completed 24.2 MiB/65.0 MiB (3.4 MiB/s) with 1 file(s) remaining   
Completed 24.5 MiB/65.0 MiB (3.3 MiB/s) with 1 file(s) remaining   
Completed 24.8 MiB/65.0 MiB (3.3 MiB/s) with 1 file(s) remaining   
Completed 25.0 MiB/65.0 MiB (3.3 MiB/s) with 1 file(s) remaining   
upload failed: ../../../data/datafile-65-MB to s3://awscli-mint-test-bucket-23838/datafile-65-MB An error occurred (InternalError) when calling the UploadPart operation (reached max retries: 4): We encountered an internal error, please try again."}

Executed 0 out of 13 tests successfully.
```

File: cmd/xl-v1-utils.go [hunk 1]
```diff
@@ -162,6 +162,11 @@ func parseXLErasureInfo(ctx context.Context, xlMetaBuf []byte) (ErasureInfo, err
 	erasure.Index = int(erasureResult.Get("index").Int())
 
 	checkSumsResult := erasureResult.Get("checksum").Array()
+
+	if len(checkSumsResult) == 0 {
```
Comment (krishnasrinivas) [inline cmd/xl-v1-utils.go]: logger.LogIf here

File: cmd/xl-v1-utils.go [hunk 2]
```diff
@@ -175,7 +180,11 @@ func parseXLErasureInfo(ctx context.Context, xlMetaBuf []byte) (ErasureInfo, err
 			logger.LogIf(ctx, err)
 			return erasure, err
 		}
-		checkSums[i] = ChecksumInfo{Name: v.Get("name").String(), Algorithm: algorithm, Hash: hash}
+		name := v.Get("name").String()
+		if name == "" {
```
Comment (krishnasrinivas) [inline cmd/xl-v1-utils.go:186]: logger.LogIf here

File: cmd/xl-v1-utils.go (hunk 1 above)
Comment (kannappanr) [reply cmd/xl-v1-utils.go]: We will not have enough information here, that is why I am logging at a higher level.

File: cmd/xl-v1-utils.go [hunk 3]
```diff
@@ -301,6 +310,8 @@ func readXLMeta(ctx context.Context, disk StorageAPI, bucket string, object stri
 	// obtain xlMetaV1{} using `github.com/tidwall/gjson`.
 	xlMeta, err = xlMetaV1UnmarshalJSON(ctx, xlMetaBuf)
 	if err != nil {
+		logger.GetReqInfo(ctx).AppendTags("disk", disk.String())
```
Comment (kannappanr) [inline cmd/xl-v1-utils.go:315]: I can also add the bucket and object information here

Comment (krishnasrinivas) [reply cmd/xl-v1-utils.go:315]: Yes. but bucket/object info should be added at the topmost caller.

Comment (kannappanr) [reply cmd/xl-v1-utils.go:315]: The topmost caller will definitely not have object, may have bucket information. So, in this scenario, passing down the topmost context will not be helpful. I am trying to see if I can add relevant information in between, the topmost caller and at this level.

**Comment by kannappanr** [comment]
@krishnasrinivas and @harshavardhana PTAL

**Review by krishnasrinivas — APPROVED** [review]

**Review by harshavardhana — APPROVED** [review]
