### PR TITLE
config/path: Figure out absolute paths properly on windows.

### LINKED ISSUE #3991: windows: "minio -C ./some_dir server ./dir" leads to error in initializing minio server
## Expected Behavior
`minio -C ./some_dir server ./dir` should work even if there is not directory `./some_dir`

## Current Behavior
`minio -C ./some_dir server ./dir`

leads to the following error:

`minio: <ERROR> Unable to initialize minio config for the first time. Error: mkdir \\?\some_dir\certs: The system cannot find the path specified..`

## Possible Solution
NA

## Steps to Reproduce (for bugs)
1. `minio -C ./some_dir server ./dir`
2.
3.
4.

## Your Environment
* Version used:
```
Version: 2017-03-16T21:50:32Z
Release-Tag: RELEASE.2017-03-16T21-50-32Z
Commit-ID: 5311eb22fd681a8cd4a46e2a872d46c2352c64e8
```
* Environment name and version (e.g. nginx 1.9.1):
* Server type and version:
* Operating System and version:
`Windows 10`
* Link to your project:

### PR DESCRIPTION
**Pull request by harshavardhana**
## Description
The following form of arguments such as

```
minio.exe -C some_dir server dir
```

has stopped working because of lack of handling of
absolute paths for config directory. Always calculate
absolute path for any relative paths on any operating
system.

The following fix converts all config directory relative
paths into absolute paths.

## Motivation and Context
Fixes #3991 

## How Has This Been Tested?
Manually in Windows 2012 R2

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

File: cmd/server-main.go [hunk 1]
```diff
@@ -482,8 +483,12 @@ func serverMain(c *cli.Context) {
 		fatalIf(errors.New("empty directory"), "Configuration directory cannot be empty.")
 	}
 
+	// Disallow relative paths, figure out absolute paths.
+	configDirAbs, err := filepath.Abs(configDir)
```
Comment (balamurugana) [inline cmd/server-main.go]: you can assign it back to `configDir` or make this into a block so that `configDirAbs` is available further below.

Comment (harshavardhana) [reply cmd/server-main.go]: Upon error `configDir` gets replaced when printing.. to empty string. and what do you mean "block" it?

Comment (harshavardhana) [reply cmd/server-main.go]: done

**Review by balamurugana — APPROVED** [review]

File: cmd/server-main.go [hunk 2]
```diff
@@ -482,6 +483,14 @@ func serverMain(c *cli.Context) {
 		fatalIf(errors.New("empty directory"), "Configuration directory cannot be empty.")
 	}
 
+	// Disallow relative paths, figure out absolute paths.
```
Comment (krisis) [inline cmd/server-main.go:486]: Suggestion: if we need to place this inside a block, we could use,
```go
if configDirAbs, err := file path.Abs(configDir); err != nil {
 // Failure code goes here
} else {
  // Set configDir here
}

**Review by krisis — APPROVED** [review]
The changes look good to me. Suggestion is optional.

File: cmd/server-main.go (hunk 2 above)
Comment (balamurugana) [reply cmd/server-main.go:486]: Generic: If failure `//Failure: code goes here` does `return`, `golint` will throw warning.

Comment (krisis) [reply cmd/server-main.go:486]: @bala, `configDirAbs`'s scope ends in the if-else block. To avoid that `configDirAbs` should be defined earlier, defeating the point of restricting its scope.

Comment (harshavardhana) [reply cmd/server-main.go:486]: Since we use fatalIf currently style is more preferred. It collapses the `if err != nil { `
