### PR TITLE
fix: threadwalk lockup under high load

### LINKED ISSUE #9991: Sync/mutex maxClients [Crash]
Error: timed out. some connections are still active. doing abnormal shutdown. goroutines written to
Error description here: https://pastebin.com/fFMKBqCv

## Expected Behavior
The server continues to work at high load, but does not crash (just not save a file)

## Current Behavior
Server freezes, further requests do not work

## Steps to Reproduce (for bugs)

1. Start minio server in docker 
2. Use +10 processes on different hosts
3. Just copy pictures via s3hs (2-6 pic every 2-6 sec)
4. Get Crash

## Context

I have about 5 hosts, on each 3-4 containers that use s3fs. 
After a while I get an error, everything stops working.

What should I do next, start new minio server (two server minio)?
Using the restrictions from the minio documentation, the server continues to fall..

## Your Environment

* Version used (`minio version`): https://hub.docker.com/layers/minio/minio/latest/images/sha256-843af0cdb0fc90ad3f0cf40023f187cfc8dde5022dc355cbd3cd85c92f074516?context=explore
* Operating System and version (`uname -a`): Linux TestHostDelta007 4.4.0-185-generic #215-Ubuntu SMP Mon Jun 8 21:53:19 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

### PR DESCRIPTION
**Pull request by klauspost**
## Description

Fixes #9991

Threadwalk could lock up under high load.

Main issue is that `t.pool[params]` should be `t.pool[oldest]`.

We add a bit more safety features for the code.

* Make writes to the endTimerCh non-blocking in all cases so multiple releases cannot lock up.
* Double check expectations.
* Shift down deletes with copy instead of truncating slice.
* Actually delete the oldest if we are above total limit.
* Actually delete the oldest found and not the current.
* Unexport the mutex so nobody from the outside can meddle with it.

Backport candidate.

## How to test this PR?

High load ListObjects calls.

## Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)
- [x] Fixes a regression #9848

### CODE REVIEW

**Comment by minio-trusted** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-s3.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-xl.sh | :x: [more...](#737f68db-2b5e-4249-b09b-3676496b6ed1) |
| mint-large-bucket.sh | :x: [more...](#05d2b9d2-72d9-4d13-9fea-2fa36b0c9995) |
| mint-dist-xl.sh | :x: [more...](#bc24abee-17a6-429a-af4d-104d75799e98) |
| mint-gateway-azure.sh | :x: [more...](#accd6b0a-0854-4b44-b882-5a2dbf0fe93d) |
| mint-zoned.sh | :x: [more...](#9f1f7435-3112-4af7-bad5-8cb634ed199b) |
<a name="bc24abee-17a6-429a-af4d-104d75799e98"></a>
### 9992-a67d425/mint-dist-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-dev3.minio.io:31060
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp bb1cff476810:/mint/log /tmp/mint-logs'

(1/15) Running aws-sdk-go tests ... done in 13 seconds
(2/15) Running aws-sdk-java tests ... done in 3 seconds
(3/15) Running aws-sdk-php tests ... done in 48 seconds
(4/15) Running aws-sdk-ruby tests ... done in 6 seconds
(5/15) Running awscli tests ... done in 2 minutes and 22 seconds
(6/15) Running healthcheck tests ... done in 0 seconds
(7/15) Running mc tests ... done in 1 minutes and 15 seconds
(8/15) Running minio-dotnet tests ... done in 3 minutes and 16 seconds
(9/15) Running minio-go tests ... FAILED in 2 minutes and 53 seconds
{
  "args": {
    "bucketName": "minio-go-test-mmvt3za43qe96zlj",
    "objectName": "mamqlrxwjij0qpsleml9twbq6jlp65",
    "objectPrefix": "",
    "recursive": "true"
  },
  "duration": 3158,
  "error": "The bucket you tried to delete is not empty. You must delete all versions in the bucket.",
  "function": "RemoveObjectsWithOptions(bucketName, objectsCh, opts)",
  "message": "Cleanup failed",
  "name": "minio-go: testRemoveObjectsWithOptions",
  "status": "FAIL"
}
(9/15) Running minio-java tests ... done in 4 minutes and 48 seconds
(10/15) Running minio-js tests ... done in 1 minutes and 0 seconds
(11/15) Running minio-py tests ... done in 3 minutes and 48 seconds
(12/15) Running s3cmd tests ... done in 22 seconds
(13/15) Running s3select tests ... done in 11 seconds
(14/15) Running security tests ... done in 0 seconds

Executed 14 out of 15 tests successfully.
```
<a name="accd6b0a-0854-4b44-b882-5a2dbf0fe93d"></a>
### 9992-a67d425/mint-gateway-azure.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-c2.minio.io:32673
ACCESS_KEY:           minioazure
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp e8e101451c69:/mint/log /tmp/mint-logs'

(1/15) Running aws-sdk-go tests ... done in 8 seconds
(2/15) Running aws-sdk-java tests ... done in 2 seconds
(3/15) Running aws-sdk-php tests ... done in 3 minutes and 11 seconds
(4/15) Running aws-sdk-ruby tests ... done in 17 seconds
(5/15) Running awscli tests ... done in 2 minutes and 50 seconds
(6/15) Running healthcheck tests ... done in 0 seconds
(7/15) Running mc tests ... done in 2 minutes and 58 seconds
(8/15) Running minio-dotnet tests ... done in 1 minutes and 33 seconds
(9/15) Running minio-go tests ... done in 4 minutes and 34 seconds
(10/15) Running minio-java tests ... FAILED in 5 minutes and 18 seconds
{
  "name": "minio-java",
  "function": "removeObjects(RemoveObjectsArgs args)",
  "duration": 1275,
  "status": "FAIL",
  "error": "org.simpleframework.xml.core.ValueRequiredException: Unable to satisfy @org.simpleframework.xml.Element(name=\"Key\", type=void.class, data=false, required=true) on field 'name' private java.lang.String io.minio.messages.DeletedObject.name for class io.minio.messages.DeletedObject at line 2 >>> [io.minio.Xml.unmarshal(Xml.java:68), io.minio.MinioClient.deleteObjects(MinioClient.java:7354), io.minio.MinioClient$1$1.populate(MinioClient.java:2945), io.minio.MinioClient$1$1.hasNext(MinioClient.java:2977), FunctionalTest.removeObjects(FunctionalTest.java:1395), FunctionalTest.removeObjects_test1(FunctionalTest.java:1534), FunctionalTest.runTests(FunctionalTest.java:3812), FunctionalTest.main(FunctionalTest.java:4056)]"
}
(10/15) Running minio-js tests ... done in 2 minutes and 35 seconds
(11/15) Running minio-py tests ... done in 9 minutes and 54 seconds
(12/15) Running s3cmd tests ... done in 1 minutes and 19 seconds
(13/15) Running s3select tests ... done in 1 minutes and 7 seconds
(14/15) Running security tests ... done in 0 seconds

Executed 14 out of 15 tests successfully.
```
<a name="9f1f7435-3112-4af7-bad5-8cb634ed199b"></a>
### 9992-a67d425/mint-zoned.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-c2.minio.io:30762
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 8116a83e1d09:/mint/log /tmp/mint-logs'

(1/15) Running aws-sdk-go tests ... done in 18 seconds
(2/15) Running aws-sdk-java tests ... done in 3 seconds
(3/15) Running aws-sdk-php tests ... done in 48 seconds
(4/15) Running aws-sdk-ruby tests ... done in 9 seconds
(5/15) Running awscli tests ... done in 2 minutes and 27 seconds
(6/15) Running healthcheck tests ... done in 0 seconds
(7/15) Running mc tests ... done in 2 minutes and 12 seconds
(8/15) Running minio-dotnet tests ... done in 3 minutes and 15 seconds
(9/15) Running minio-go tests ... FAILED in 2 minutes and 55 seconds
{
  "args": {
    "bucketName": "minio-go-test-ncqsuisww3r6f9xf",
    "objectName": "4v6tmfr665n3epe5p25pmoxdxow0ll",
    "objectPrefix": "",
    "recursive": "true"
  },
  "duration": 5024,
  "error": "The bucket you tried to delete is not empty. You must delete all versions in the bucket.",
  "function": "RemoveObjectsWithOptions(bucketName, objectsCh, opts)",
  "message": "Cleanup failed",
  "name": "minio-go: testRemoveObjectsWithOptions",
  "status": "FAIL"
}
(9/15) Running minio-java tests ... done in 6 minutes and 38 seconds
(10/15) Running minio-js tests ... done in 1 minutes and 3 seconds
(11/15) Running minio-py tests ... done in 4 minutes and 19 seconds
(12/15) Running s3cmd tests ... done in 22 seconds
(13/15) Running s3select tests ... done in 10 seconds
(14/15) Running security tests ... done in 0 seconds

Executed 14 out of 15 tests successfully.
```
<a name="05d2b9d2-72d9-4d13-9fea-2fa36b0c9995"></a>
### 9992-a67d425/mint-large-bucket.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-dev6.minio.io:31296
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 1a2285623159:/mint/log /tmp/mint-logs'

(1/15) Running aws-sdk-go tests ... done in 16 seconds
(2/15) Running aws-sdk-java tests ... done in 3 seconds
(3/15) Running aws-sdk-php tests ... FAILED in 5 seconds
{
  "name": "aws-sdk-php",
  "function": "anonDeleteObjects ( array $params = [] )",
  "args": {
    "Bucket": "aws-sdk-php-5f05a26961ff4",
    "Object": "obj1"
  },
  "duration": "458",
  "status": "FAIL",
  "error": "Error executing \"DeleteObjects\" on \"http://minio-dev6.minio.io:31296/aws-sdk-php-5f05a26961ff4?delete\"; AWS HTTP error: Server error: `POST http://minio-dev6.minio.io:31296/aws-sdk-php-5f05a26961ff4?delete` resulted in a `503 Service Unavailable` response:\n<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<Error><Code>XMinioServerNotInitialized</Code><Message>Server not initialized, pl (truncated...)\n XMinioServerNotInitialized (server): Server not initialized, please try again. - <?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<Error><Code>XMinioServerNotInitialized</Code><Message>Server not initialized, please try again.</Message><BucketName>aws-sdk-php-5f05a26961ff4</BucketName><Resource>/aws-sdk-php-5f05a26961ff4</Resource><RequestId>161FC0CDB9ECCB78</RequestId><HostId>7bdee702-2a30-49bf-bbf9-767a54ef63de</HostId></Error>"
}
(3/15) Running aws-sdk-ruby tests ... FAILED in 4 seconds
{
  "name": "aws-sdk-ruby",
  "function": "listBuckets",
  "args": {},
  "duration": 2128.94,
  "error": "Server not initialized, please try again.",
  "status": "FAIL"
}
(3/15) Running awscli tests ... FAILED in 25 seconds
{
  "name": "awscli",
  "duration": 23684,
  "function": "delete_bucket\n",
  "status": "FAIL",
  "error": "fatal error: An error occurred (XMinioServerNotInitialized) when calling the ListObjectsV2 operation (reached max retries: 4): Server not initialized, please try again.remove_bucket failed: Unable to delete all objects in the bucket, bucket will not be deleted."
}
(3/15) Running healthcheck tests ... done in 0 seconds
(4/15) Running mc tests ... FAILED in 1 minutes and 3 seconds
{
  "name": "mc",
  "duration": "62120",
  "function": "test_make_bucket",
  "status": "FAIL",
  "error": "/mint/run/core/mc/mc --config-dir /tmp/.mc-9406 --quiet --no-color mb myminio/mc-test-bucket-13214  >>> \nmc: <ERROR> Unable to make bucket `myminio/mc-test-bucket-13214`. Server not initialized, please try again."
}
(4/15) Running minio-dotnet tests ... done in 22 seconds
(5/15) Running minio-go tests ... FAILED in 6 seconds
{
  "args": {
    "bucketName": "minio-go-test-xmybnyt0ib1ulidu",
    "expires": 3600000000000,
    "objectName": "minio-go-test-xmybnyt0ib1uliduunique"
  },
  "duration": 789,
  "function": "PresignedHeadObject(bucketName, objectName, expires, reqParams)",
  "message": "PresignedHeadObject URL returns status Ƿ",
  "name": "minio-go: testFunctionalV2",
  "status": "FAIL"
}
(5/15) Running minio-java tests ... FAILED in 18 seconds
{
  "name": "minio-java",
  "function": "getPresignedObjectUrl(GetPresignedObjectUrlArgs args)",
  "duration": 73,
  "status": "FAIL",
  "error": "java.lang.Exception: failed to create object. Response: Response{protocol=http/1.1, code=503, message=Service Unavailable, url=http://minio-dev6.minio.io:31296/minio-java-test-iocqbf/minio-java-test-2113vfg?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=minio%2F20200708%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20200708T104200Z&X-Amz-Expires=604800&X-Amz-SignedHeaders=host&X-Amz-Signature=df978e917246fd285643f6a13c5af53c445ec242ca0515663daf67a5562f9c23}, Response body: <?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<Error><Code>XMinioServerNotInitialized</Code><Message>Server not initialized, please try again.</Message><Key>minio-java-test-2113vfg</Key><BucketName>minio-java-test-iocqbf</BucketName><Resource>/minio-java-test-iocqbf/minio-java-test-2113vfg</Resource><RequestId>161FC0EDC01CB413</RequestId><HostId>7bdee702-2a30-49bf-bbf9-767a54ef63de</HostId></Error> >>> [FunctionalTest.readObject(FunctionalTest.java:314), FunctionalTest.getPresignedObjectUrl_test1(FunctionalTest.java:1743), FunctionalTest.runTests(FunctionalTest.java:3802), FunctionalTest.main(FunctionalTest.java:4056)]"
}
(5/15) Running minio-js tests ... FAILED in 6 seconds
{
  "name": "minio-js",
  "function": "removeBucket(bucketName, cb)",
  "args": "bucketName:minio-js-test-41b7d7b5-6ae6-49ba-8081-89ff12809138-region",
  "duration": 18,
  "status": "FAIL",
  "error": "S3Error: Server not initialized, please try again. at Object.parseError (node_modules/minio/dist/main/xml-parsers.js:86:11) at /mint/run/core/minio-js/node_modules/minio/dist/main/transformers.js:156:22 at DestroyableTransform._flush (node_modules/minio/dist/main/transformers.js:80:10) at DestroyableTransform.prefinish (node_modules/readable-stream/lib/_stream_transform.js:129:10) at prefinish (node_modules/readable-stream/lib/_stream_writable.js:611:14) at finishMaybe (node_modules/readable-stream/lib/_stream_writable.js:620:5) at endWritable (node_modules/readable-stream/lib/_stream_writable.js:643:3) at DestroyableTransform.Writable.end (node_modules/readable-stream/lib/_stream_writable.js:571:22) at IncomingMessage.onend (_stream_readable.js:673:10) at endReadableNT (_stream_readable.js:1201:12) at processTicksAndRejections (internal/process/task_queues.js:84:21)"
}
(5/15) Running minio-py tests ... FAILED in 11 minutes and 37 seconds
{
  "name": "minio-py:test_list_objects",
  "function": "list_objects(bucket_name, prefix, recursive)",
  "args": {
    "bucket_name": "minio-py-test-620a3e8a-e79e-4df5-9453-c4d730347943",
    "object_name": "1243d303-26d9-4522-b292-4cf988db0617",
    "recursive": true
  },
  "duration": 612194,
  "message": "HTTPConnectionPool(host='minio-dev6.minio.io', port=31296): Max retries exceeded with url: /minio-py-test-620a3e8a-e79e-4df5-9453-c4d730347943/?prefix= (Caused by ResponseError('too many 503 error responses',))",
  "error": "Traceback (most recent call last):\n  File \"/mint/run/core/minio-py/tests.py\", line 1035, in test_list_objects\n    for obj in objects:\n  File \"/usr/local/lib/python3.6/dist-packages/minio/api.py\", line 1036, in list_objects\n    headers=headers)\n  File \"/usr/local/lib/python3.6/dist-packages/minio/api.py\", line 2000, in _url_open\n    preload_content=preload_content)\n  File \"/usr/local/lib/python3.6/dist-packages/urllib3/poolmanager.py\", line 336, in urlopen\n    response = conn.urlopen(method, u.request_uri, **kw)\n  File \"/usr/local/lib/python3.6/dist-packages/urllib3/connectionpool.py\", line 828, in urlopen\n    **response_kw\n  File \"/usr/local/lib/python3.6/dist-packages/urllib3/connectionpool.py\", line 828, in urlopen\n    **response_kw\n  File \"/usr/local/lib/python3.6/dist-packages/urllib3/connectionpool.py\", line 828, in urlopen\n    **response_kw\n  [Previous line repeated 2 more times]\n  File \"/usr/local/lib/python3.6/dist-packages/urllib3/connectionpool.py\", line 805, in urlopen\n    retries = retries.increment(method, url, response=response, _pool=self)\n  File \"/usr/local/lib/python3.6/dist-packages/urllib3/util/retry.py\", line 439, in increment\n    raise MaxRetryError(_pool, url, error or ResponseError(cause))\nurllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='minio-dev6.minio.io', port=31296): Max retries exceeded with url: /minio-py-test-620a3e8a-e79e-4df5-9453-c4d730347943/?prefix= (Caused by ResponseError('too many 503 error responses',))\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"/mint/run/core/minio-py/tests.py\", line 2085, in main\n    test_list_objects(client, log_output)\n  File \"/mint/run/core/minio-py/tests.py\", line 1042, in test_list_objects\n    raise Exception(err)\nException: HTTPConnectionPool(host='minio-dev6.minio.io', port=31296): Max retries exceeded with url: /minio-py-test-620a3e8a-e79e-4df5-9453-c4d730347943/?prefix= (Caused by ResponseError('too many 503 error responses',))\n",
  "status": "FAIL"
}
(5/15) Running s3cmd tests ... FAILED in 15 seconds
{
  "name": "s3cmd",
  "duration": "780",
  "function": "test_get_object",
  "status": "FAIL",
  "error": "ERROR: S3 error: 503 (XMinioServerNotInitialized): Server not initialized, please try again."
}
(5/15) Running s3select tests ... FAILED in 10 minutes and 17 seconds
{
  "name": "s3select:test_sql_functions_agg_cond_conv",
  "function": "select_object_content(bucket_name, object_name, opts)",
  "args": {
    "total_tests": 8,
    "total_success": 6
  },
  "duration": 602674,
  "message": "HTTPConnectionPool(host='minio-dev6.minio.io', port=31296): Max retries exceeded with url: /s3select-test-3bb8c367-b21c-42d1-a93c-4e417a91a72c/70e2dcee-37e8-43fe-8d17-8dfeec5e048d (Caused by ResponseError('too many 503 error responses',))",
  "error": "Traceback (most recent call last):\n  File \"./tests.py\", line 57, in main\n    test_sql_functions_agg_cond_conv(client, log_output)\n  File \"/mint/run/core/s3select/sql_ops.py\", line 198, in test_sql_functions_agg_cond_conv\n    raise select_err\n  File \"/mint/run/core/s3select/sql_ops.py\", line 196, in test_sql_functions_agg_cond_conv\n    test_sql_expressions(client, json_testfile, tests, log_output)\n  File \"/mint/run/core/s3select/sql_ops.py\", line 89, in test_sql_expressions\n    input_serialization, output_serialization, tests, log_output)\n  File \"/mint/run/core/s3select/sql_ops.py\", line 74, in test_sql_expressions_custom_input_output\n    client.remove_object(bucket_name, object_name)\n  File \"/usr/local/lib/python3.6/dist-packages/minio/api.py\", line 1171, in remove_object\n    object_name=object_name)\n  File \"/usr/local/lib/python3.6/dist-packages/minio/api.py\", line 2000, in _url_open\n    preload_content=preload_content)\n  File \"/usr/local/lib/python3.6/dist-packages/urllib3/poolmanager.py\", line 336, in urlopen\n    response = conn.urlopen(method, u.request_uri, **kw)\n  File \"/usr/local/lib/python3.6/dist-packages/urllib3/connectionpool.py\", line 828, in urlopen\n    **response_kw\n  File \"/usr/local/lib/python3.6/dist-packages/urllib3/connectionpool.py\", line 828, in urlopen\n    **response_kw\n  File \"/usr/local/lib/python3.6/dist-packages/urllib3/connectionpool.py\", line 828, in urlopen\n    **response_kw\n  [Previous line repeated 2 more times]\n  File \"/usr/local/lib/python3.6/dist-packages/urllib3/connectionpool.py\", line 805, in urlopen\n    retries = retries.increment(method, url, response=response, _pool=self)\n  File \"/usr/local/lib/python3.6/dist-packages/urllib3/util/retry.py\", line 439, in increment\n    raise MaxRetryError(_pool, url, error or ResponseError(cause))\nurllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='minio-dev6.minio.io', port=31296): Max retries exceeded with url: /s3select-test-3bb8c367-b21c-42d1-a93c-4e417a91a72c/70e2dcee-37e8-43fe-8d17-8dfeec5e048d (Caused by ResponseError('too many 503 error responses',))\n",
  "status": "FAIL"
}
(5/15) Running security tests ... done in 0 seconds

Executed 5 out of 15 tests successfully.
```
<a name="737f68db-2b5e-4249-b09b-3676496b6ed1"></a>
### 9992-a67d425/mint-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-dev6.minio.io:30025
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 1565987eb29d:/mint/log /tmp/mint-logs'

(1/15) Running aws-sdk-go tests ... done in 5 seconds
(2/15) Running aws-sdk-java tests ... done in 2 seconds
(3/15) Running aws-sdk-php tests ... done in 45 seconds
(4/15) Running aws-sdk-ruby tests ... done in 4 seconds
(5/15) Running awscli tests ... done in 2 minutes and 11 seconds
(6/15) Running healthcheck tests ... done in 1 seconds
(7/15) Running mc tests ... done in 36 seconds
(8/15) Running minio-dotnet tests ... done in 1 minutes and 28 seconds
(9/15) Running minio-go tests ... FAILED in 1 minutes and 50 seconds
{
  "args": {
    "bucketName": "minio-go-test-v9ld6fxc590txojt",
    "objectName": "t3rqqfnjbr3m1006kanarjqtlugprx",
    "objectPrefix": "",
    "recursive": "true"
  },
  "duration": 5087,
  "error": "The bucket you tried to delete is not empty. You must delete all versions in the bucket.",
  "function": "RemoveObjectsWithOptions(bucketName, objectsCh, opts)",
  "message": "Cleanup failed",
  "name": "minio-go: testRemoveObjectsWithOptions",
  "status": "FAIL"
}
(9/15) Running minio-java tests ... done in 3 minutes and 34 seconds
(10/15) Running minio-js tests ... done in 51 seconds
(11/15) Running minio-py tests ... done in 6 minutes and 1 seconds
(12/15) Running s3cmd tests ... done in 22 seconds
(13/15) Running s3select tests ... done in 10 seconds
(14/15) Running security tests ... done in 0 seconds

Executed 14 out of 15 tests successfully.
```
Deleting image on docker hub
Deleting image locally

**Comment by minio-trusted** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-xl.sh | :x: [more...](#37cec2ff-f6fe-4001-8a78-39b7b09149bd) |
| mint-large-bucket.sh | :x: [more...](#3021c315-e26b-4ab9-8ec6-44a904d5b25a) |
| mint-dist-xl.sh | :x: [more...](#43b0edcd-48c3-4406-bd15-9d7b53985951) |
| mint-gateway-s3.sh | :x: [more...](#ca327989-ab62-495b-b580-7b006986042f) |
| mint-gateway-azure.sh | :x: [more...](#6fc2062e-4a18-47db-84d6-c400bc1d70db) |
| mint-zoned.sh | :x: [more...](#b8029b75-715c-4652-829f-4755bbbfca53) |
<a name="6fc2062e-4a18-47db-84d6-c400bc1d70db"></a>
### 9992-aa142a9/mint-gateway-azure.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-dev4.minio.io:30214
ACCESS_KEY:           minioazure
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 83eefa7d0f5f:/mint/log /tmp/mint-logs'

(1/15) Running aws-sdk-go tests ... done in 7 seconds
(2/15) Running aws-sdk-java tests ... done in 3 seconds
(3/15) Running aws-sdk-php tests ... done in 3 minutes and 10 seconds
(4/15) Running aws-sdk-ruby tests ... done in 16 seconds
(5/15) Running awscli tests ... done in 2 minutes and 48 seconds
(6/15) Running healthcheck tests ... done in 0 seconds
(7/15) Running mc tests ... done in 3 minutes and 12 seconds
(8/15) Running minio-dotnet tests ... done in 1 minutes and 31 seconds
(9/15) Running minio-go tests ... done in 4 minutes and 44 seconds
(10/15) Running minio-java tests ... FAILED in 5 minutes and 18 seconds
{
  "name": "minio-java",
  "function": "removeObjects(RemoveObjectsArgs args)",
  "duration": 1254,
  "status": "FAIL",
  "error": "org.simpleframework.xml.core.ValueRequiredException: Unable to satisfy @org.simpleframework.xml.Element(name=\"Key\", type=void.class, data=false, required=true) on field 'name' private java.lang.String io.minio.messages.DeletedObject.name for class io.minio.messages.DeletedObject at line 2 >>> [io.minio.Xml.unmarshal(Xml.java:68), io.minio.MinioClient.deleteObjects(MinioClient.java:7354), io.minio.MinioClient$1$1.populate(MinioClient.java:2945), io.minio.MinioClient$1$1.hasNext(MinioClient.java:2977), FunctionalTest.removeObjects(FunctionalTest.java:1395), FunctionalTest.removeObjects_test1(FunctionalTest.java:1534), FunctionalTest.runTests(FunctionalTest.java:3812), FunctionalTest.main(FunctionalTest.java:4056)]"
}
(10/15) Running minio-js tests ... done in 2 minutes and 32 seconds
(11/15) Running minio-py tests ... done in 9 minutes and 49 seconds
(12/15) Running s3cmd tests ... done in 1 minutes and 26 seconds
(13/15) Running s3select tests ... done in 1 minutes and 7 seconds
(14/15) Running security tests ... done in 0 seconds

Executed 14 out of 15 tests successfully.
```
<a name="ca327989-ab62-495b-b580-7b006986042f"></a>
### 9992-aa142a9/mint-gateway-s3.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-c2.minio.io:32517
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp be2ef152088e:/mint/log /tmp/mint-logs'

(1/15) Running aws-sdk-go tests ... done in 0 seconds
(2/15) Running aws-sdk-java tests ... done in 2 seconds
(3/15) Running aws-sdk-php tests ... done in 42 seconds
(4/15) Running aws-sdk-ruby tests ... done in 2 seconds
(5/15) Running awscli tests ... done in 1 minutes and 4 seconds
(6/15) Running healthcheck tests ... done in 0 seconds
(7/15) Running mc tests ... done in 21 seconds
(8/15) Running minio-dotnet tests ... done in 28 seconds
(9/15) Running minio-go tests ... done in 33 seconds
(10/15) Running minio-java tests ... done in 21 seconds
(11/15) Running minio-js tests ... FAILED in 30 minutes and 2 seconds
{
  "name": "minio-js",
  "function": "\"after all\" hook in \"functional tests\"",
  "duration": 17,
  "status": "FAIL",
  "error": "S3Error: The bucket you tried to delete is not empty at Object.parseError (node_modules/minio/dist/main/xml-parsers.js:86:11) at /mint/run/core/minio-js/node_modules/minio/dist/main/transformers.js:156:22 at DestroyableTransform._flush (node_modules/minio/dist/main/transformers.js:80:10) at DestroyableTransform.prefinish (node_modules/readable-stream/lib/_stream_transform.js:129:10) at prefinish (node_modules/readable-stream/lib/_stream_writable.js:611:14) at finishMaybe (node_modules/readable-stream/lib/_stream_writable.js:620:5) at endWritable (node_modules/readable-stream/lib/_stream_writable.js:643:3) at DestroyableTransform.Writable.end (node_modules/readable-stream/lib/_stream_writable.js:571:22) at IncomingMessage.onend (_stream_readable.js:673:10) at endReadableNT (_stream_readable.js:1201:12) at processTicksAndRejections (internal/process/task_queues.js:84:21)"
}
(11/15) Running minio-py tests ... done in 56 seconds
(12/15) Running s3cmd tests ... done in 58 seconds
(13/15) Running s3select tests ... done in 3 seconds
(14/15) Running security tests ... done in 0 seconds

Executed 14 out of 15 tests successfully.
```
<a name="43b0edcd-48c3-4406-bd15-9d7b53985951"></a>
### 9992-aa142a9/mint-dist-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-dev4.minio.io:31976
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp db5b2a3ad426:/mint/log /tmp/mint-logs'

(1/15) Running aws-sdk-go tests ... done in 9 seconds
(2/15) Running aws-sdk-java tests ... FAILED in 2 seconds
Jul 08, 2020 11:49:13 AM com.amazonaws.util.Base64 warn
WARNING: JAXB is unavailable. Will fallback to SDK implementation which may be less performant.If you are using Java 9+, you will need to include javax.xml.bind:jaxb-api as a dependency.
com.amazonaws.services.s3.model.AmazonS3Exception: Server not initialized, please try again. (Service: Amazon S3; Status Code: 503; Error Code: XMinioServerNotInitialized; Request ID: 161FC498DB948314; S3 Extended Request ID: e5172e4a-ea68-4e75-873b-fd1abd4c69c0), S3 Extended Request ID: e5172e4a-ea68-4e75-873b-fd1abd4c69c0
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.handleErrorResponse(AmazonHttpClient.java:1742)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.handleServiceErrorResponse(AmazonHttpClient.java:1371)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeOneRequest(AmazonHttpClient.java:1347)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeHelper(AmazonHttpClient.java:1127)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.doExecute(AmazonHttpClient.java:784)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeWithTimer(AmazonHttpClient.java:752)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.execute(AmazonHttpClient.java:726)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.access$500(AmazonHttpClient.java:686)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutionBuilderImpl.execute(AmazonHttpClient.java:668)
	at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:532)
	at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:512)
	at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:5052)
	at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:4998)
	at com.amazonaws.services.s3.AmazonS3Client.createBucket(AmazonS3Client.java:1094)
	at io.minio.awssdk.tests.FunctionalTests.initTests(Unknown Source)
	at io.minio.awssdk.tests.FunctionalTests.main(Unknown Source)
(2/15) Running aws-sdk-php tests ... FAILED in 1 seconds
PHP Fatal error:  Uncaught exception 'Aws\S3\Exception\S3Exception' with message 'Error executing "DeleteObject" on "http://minio-dev4.minio.io:31976/aws-sdk-php-5f05b2ba183f5/obj1"; AWS HTTP error: Server error: `DELETE http://minio-dev4.minio.io:31976/aws-sdk-php-5f05b2ba183f5/obj1` resulted in a `503 Service Unavailable` response:
<?xml version="1.0" encoding="UTF-8"?>
<Error><Code>XMinioServerNotInitialized</Code><Message>Server not initialized, pl (truncated...)
 XMinioServerNotInitialized (server): Server not initialized, please try again. - <?xml version="1.0" encoding="UTF-8"?>
<Error><Code>XMinioServerNotInitialized</Code><Message>Server not initialized, please try again.</Message><Key>obj1</Key><BucketName>aws-sdk-php-5f05b2ba183f5</BucketName><Resource>/aws-sdk-php-5f05b2ba183f5/obj1</Resource><RequestId>161FC499047ACE2B</RequestId><HostId>e5172e4a-ea68-4e75-873b-fd1abd4c69c0</HostId></Error>'

GuzzleHttp\Exception\ServerException: Server error: `PUT http://minio-dev4.minio.io:31976/aws-sdk-php-5f05b2ba183f5` result in /mint/run/core/aws-sdk-php/vendor/aws/aws-sdk-php/src/WrappedHttpHandler.php on line 195
(2/15) Running aws-sdk-ruby tests ... FAILED in 3 seconds
{
  "name": "aws-sdk-ruby",
  "function": "listBuckets",
  "args": {},
  "duration": 2135.34,
  "error": "Server not initialized, please try again.",
  "status": "FAIL"
}
(2/15) Running awscli tests ... FAILED in 19 seconds
{
  "name": "awscli",
  "duration": 14079,
  "function": "make_bucket\n",
  "status": "FAIL",
  "error": "An error occurred (XMinioServerNotInitialized) when calling the CreateBucket operation (reached max retries: 4): Server not initialized, please try again."
}
(2/15) Running healthcheck tests ... done in 0 seconds
(3/15) Running mc tests ... FAILED in 0 seconds
(3/15) Running minio-dotnet tests ... done in 6 seconds
(4/15) Running minio-go tests ... FAILED in 1 minutes and 48 seconds
{
  "args": {
    "bucketName": "minio-go-test-ia4zygih3oae2bhm"
  },
  "duration": 105819,
  "error": "Server not initialized, please try again.",
  "function": "GetObject(bucketName, objectName)",
  "message": "MakeBucket failed",
  "name": "minio-go: testGetObjectReadSeekFunctionalV2",
  "status": "FAIL"
}
(4/15) Running minio-java tests ... FAILED in 1 seconds
{
  "name": "minio-java",
  "function": "makeBucket(MakeBucketArgs args)",
  "duration": 354,
  "status": "FAIL",
  "error": "java.lang.IllegalArgumentException: unknown error code string 'XMinioServerNotInitialized' >>> [io.minio.Xml.unmarshal(Xml.java:68), io.minio.MinioClient.execute(MinioClient.java:1050), io.minio.MinioClient.makeBucket(MinioClient.java:3773), FunctionalTest.makeBucket_test1(FunctionalTest.java:435), FunctionalTest.runTests(FunctionalTest.java:3772), FunctionalTest.main(FunctionalTest.java:4056)]"
}
(4/15) Running minio-js tests ... FAILED in 4 seconds
{
  "name": "minio-js",
  "function": "makeBucket(bucketName, region, cb)",
  "args": "bucketName:minio-js-test-9e4256b7-f94d-4817-9518-7a4f7f65a93a-region, region:us-east-1",
  "duration": 22,
  "status": "FAIL",
  "error": "S3Error: Server not initialized, please try again. at Object.parseError (node_modules/minio/dist/main/xml-parsers.js:86:11) at /mint/run/core/minio-js/node_modules/minio/dist/main/transformers.js:156:22 at DestroyableTransform._flush (node_modules/minio/dist/main/transformers.js:80:10) at DestroyableTransform.prefinish (node_modules/readable-stream/lib/_stream_transform.js:129:10) at prefinish (node_modules/readable-stream/lib/_stream_writable.js:611:14) at finishMaybe (node_modules/readable-stream/lib/_stream_writable.js:620:5) at endWritable (node_modules/readable-stream/lib/_stream_writable.js:643:3) at DestroyableTransform.Writable.end (node_modules/readable-stream/lib/_stream_writable.js:571:22) at IncomingMessage.onend (_stream_readable.js:673:10) at endReadableNT (_stream_readable.js:1201:12) at processTicksAndRejections (internal/process/task_queues.js:84:21)"
}
(4/15) Running minio-py tests ... FAILED in 10 minutes and 0 seconds
{
  "name": "minio-py:test_make_bucket_default_region",
  "function": "make_bucket(bucket_name, location)",
  "args": {
    "bucket_name": "minio-py-test-39c41668-c6d6-40a4-a1bb-a3c1b381c206",
    "location": "default value ('us-east-1')"
  },
  "duration": 600482,
  "message": "HTTPConnectionPool(host='minio-dev4.minio.io', port=31976): Max retries exceeded with url: /minio-py-test-39c41668-c6d6-40a4-a1bb-a3c1b381c206/ (Caused by ResponseError('too many 503 error responses',))",
  "error": "Traceback (most recent call last):\n  File \"/mint/run/core/minio-py/tests.py\", line 188, in test_make_bucket_default_region\n    client.make_bucket(bucket_name)\n  File \"/usr/local/lib/python3.6/dist-packages/minio/api.py\", line 371, in make_bucket\n    headers=headers)\n  File \"/usr/local/lib/python3.6/dist-packages/urllib3/poolmanager.py\", line 336, in urlopen\n    response = conn.urlopen(method, u.request_uri, **kw)\n  File \"/usr/local/lib/python3.6/dist-packages/urllib3/connectionpool.py\", line 828, in urlopen\n    **response_kw\n  File \"/usr/local/lib/python3.6/dist-packages/urllib3/connectionpool.py\", line 828, in urlopen\n    **response_kw\n  File \"/usr/local/lib/python3.6/dist-packages/urllib3/connectionpool.py\", line 828, in urlopen\n    **response_kw\n  [Previous line repeated 2 more times]\n  File \"/usr/local/lib/python3.6/dist-packages/urllib3/connectionpool.py\", line 805, in urlopen\n    retries = retries.increment(method, url, response=response, _pool=self)\n  File \"/usr/local/lib/python3.6/dist-packages/urllib3/util/retry.py\", line 439, in increment\n    raise MaxRetryError(_pool, url, error or ResponseError(cause))\nurllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='minio-dev4.minio.io', port=31976): Max retries exceeded with url: /minio-py-test-39c41668-c6d6-40a4-a1bb-a3c1b381c206/ (Caused by ResponseError('too many 503 error responses',))\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"/mint/run/core/minio-py/tests.py\", line 1968, in main\n    test_make_bucket_default_region(client, log_output)\n  File \"/mint/run/core/minio-py/tests.py\", line 196, in test_make_bucket_default_region\n    raise Exception(err)\nException: HTTPConnectionPool(host='minio-dev4.minio.io', port=31976): Max retries exceeded with url: /minio-py-test-39c41668-c6d6-40a4-a1bb-a3c1b381c206/ (Caused by ResponseError('too many 503 error responses',))\n",
  "status": "FAIL"
}
(4/15) Running s3cmd tests ... FAILED in 51 seconds
{
  "name": "s3cmd",
  "duration": "45557",
  "function": "test_put_object_multipart",
  "status": "FAIL",
  "error": "WARNING: Retrying failed request: /s3cmd-test-object-20940?uploads (503 (XMinioServerNotInitialized): Server not initialized, please try again.)\nWARNING: Waiting 3 sec...\nWARNING: Retrying failed request: /s3cmd-test-object-20940?uploads (503 (XMinioServerNotInitialized): Server not initialized, please try again.)\nWARNING: Waiting 6 sec...\nWARNING: Retrying failed request: /s3cmd-test-object-20940?uploads (503 (XMinioServerNotInitialized): Server not initialized, please try again.)\nWARNING: Waiting 9 sec...\nWARNING: Retrying failed request: /s3cmd-test-object-20940?uploads (503 (XMinioServerNotInitialized): Server not initialized, please try again.)\nWARNING: Waiting 12 sec...\nWARNING: Retrying failed request: /s3cmd-test-object-20940?uploads (503 (XMinioServerNotInitialized): Server not initialized, please try again.)\nWARNING: Waiting 15 sec...\nERROR: S3 error: 503 (XMinioServerNotInitialized): Server not initialized, please try again."
}
(4/15) Running s3select tests ... FAILED in 10 minutes and 0 seconds
{
  "name": "s3select:test_csv_input_quote_char",
  "function": "select_object_content(bucket_name, object_name, opts)",
  "args": {
    "bucket_name": "s3select-test-e96c22db-ec3e-4c48-8b36-c627193f14f5"
  },
  "duration": 600435,
  "message": "HTTPConnectionPool(host='minio-dev4.minio.io', port=31976): Max retries exceeded with url: /s3select-test-e96c22db-ec3e-4c48-8b36-c627193f14f5/ (Caused by ResponseError('too many 503 error responses',))",
  "error": "Traceback (most recent call last):\n  File \"./tests.py\", line 45, in main\n    test_csv_input_custom_quote_char(client, log_output)\n  File \"/mint/run/core/s3select/csv.py\", line 82, in test_csv_input_custom_quote_char\n    client.make_bucket(bucket_name)\n  File \"/usr/local/lib/python3.6/dist-packages/minio/api.py\", line 371, in make_bucket\n    headers=headers)\n  File \"/usr/local/lib/python3.6/dist-packages/urllib3/poolmanager.py\", line 336, in urlopen\n    response = conn.urlopen(method, u.request_uri, **kw)\n  File \"/usr/local/lib/python3.6/dist-packages/urllib3/connectionpool.py\", line 828, in urlopen\n    **response_kw\n  File \"/usr/local/lib/python3.6/dist-packages/urllib3/connectionpool.py\", line 828, in urlopen\n    **response_kw\n  File \"/usr/local/lib/python3.6/dist-packages/urllib3/connectionpool.py\", line 828, in urlopen\n    **response_kw\n  [Previous line repeated 2 more times]\n  File \"/usr/local/lib/python3.6/dist-packages/urllib3/connectionpool.py\", line 805, in urlopen\n    retries = retries.increment(method, url, response=response, _pool=self)\n  File \"/usr/local/lib/python3.6/dist-packages/urllib3/util/retry.py\", line 439, in increment\n    raise MaxRetryError(_pool, url, error or ResponseError(cause))\nurllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='minio-dev4.minio.io', port=31976): Max retries exceeded with url: /s3select-test-e96c22db-ec3e-4c48-8b36-c627193f14f5/ (Caused by ResponseError('too many 503 error responses',))\n",
  "status": "FAIL"
}
(4/15) Running security tests ... done in 0 seconds

Executed 4 out of 15 tests successfully.
```
<a name="37cec2ff-f6fe-4001-8a78-39b7b09149bd"></a>
### 9992-aa142a9/mint-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-dev6.minio.io:32766
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp b448e00d0e82:/mint/log /tmp/mint-logs'

(1/15) Running aws-sdk-go tests ... done in 1 seconds
(2/15) Running aws-sdk-java tests ... done in 3 seconds
(3/15) Running aws-sdk-php tests ... done in 43 seconds
(4/15) Running aws-sdk-ruby tests ... done in 3 seconds
(5/15) Running awscli tests ... done in 2 minutes and 4 seconds
(6/15) Running healthcheck tests ... done in 0 seconds
(7/15) Running mc tests ... done in 29 seconds
(8/15) Running minio-dotnet tests ... done in 33 seconds
(9/15) Running minio-go tests ... FAILED in 57 seconds
{
  "args": {
    "bucketName": "minio-go-test-b55llbroeu0oxgla",
    "objectName": "ckpq1qynj2mcjzgiy52bceezb4t0ud",
    "objectPrefix": "",
    "recursive": "true"
  },
  "duration": 4708,
  "error": "The bucket you tried to delete is not empty. You must delete all versions in the bucket.",
  "function": "RemoveObjectsWithOptions(bucketName, objectsCh, opts)",
  "message": "Cleanup failed",
  "name": "minio-go: testRemoveObjectsWithOptions",
  "status": "FAIL"
}
(9/15) Running minio-java tests ... done in 1 minutes and 39 seconds
(10/15) Running minio-js tests ... done in 48 seconds
(11/15) Running minio-py tests ... done in 3 minutes and 23 seconds
(12/15) Running s3cmd tests ... done in 19 seconds
(13/15) Running s3select tests ... done in 6 seconds
(14/15) Running security tests ... done in 0 seconds

Executed 14 out of 15 tests successfully.
```
<a name="3021c315-e26b-4ab9-8ec6-44a904d5b25a"></a>
### 9992-aa142a9/mint-large-bucket.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-dev3.minio.io:32313
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 62428af4f4e6:/mint/log /tmp/mint-logs'

(1/15) Running aws-sdk-go tests ... done in 12 seconds
(2/15) Running aws-sdk-java tests ... done in 2 seconds
(3/15) Running aws-sdk-php tests ... done in 47 seconds
(4/15) Running aws-sdk-ruby tests ... done in 9 seconds
(5/15) Running awscli tests ... done in 2 minutes and 59 seconds
(6/15) Running healthcheck tests ... done in 0 seconds
(7/15) Running mc tests ... done in 1 minutes and 10 seconds
(8/15) Running minio-dotnet tests ... done in 1 minutes and 42 seconds
(9/15) Running minio-go tests ... FAILED in 2 minutes and 19 seconds
{
  "args": {
    "bucketName": "minio-go-test-5dltrgeq0exanou2",
    "objectName": "lsif0blcgz9aj1ajjryg4wts3rcgi6",
    "objectPrefix": "",
    "recursive": "true"
  },
  "duration": 5510,
  "error": "The bucket you tried to delete is not empty. You must delete all versions in the bucket.",
  "function": "RemoveObjectsWithOptions(bucketName, objectsCh, opts)",
  "message": "Cleanup failed",
  "name": "minio-go: testRemoveObjectsWithOptions",
  "status": "FAIL"
}
(9/15) Running minio-java tests ... done in 3 minutes and 36 seconds
(10/15) Running minio-js tests ... done in 52 seconds
(11/15) Running minio-py tests ... done in 4 minutes and 30 seconds
(12/15) Running s3cmd tests ... done in 24 seconds
(13/15) Running s3select tests ... done in 12 seconds
(14/15) Running security tests ... done in 0 seconds

Executed 14 out of 15 tests successfully.
```
<a name="b8029b75-715c-4652-829f-4755bbbfca53"></a>
### 9992-aa142a9/mint-zoned.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-dev7.minio.io:32220
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp c88840b38184:/mint/log /tmp/mint-logs'

(1/15) Running aws-sdk-go tests ... done in 15 seconds
(2/15) Running aws-sdk-java tests ... done in 2 seconds
(3/15) Running aws-sdk-php tests ... done in 48 seconds
(4/15) Running aws-sdk-ruby tests ... done in 9 seconds
(5/15) Running awscli tests ... done in 2 minutes and 26 seconds
(6/15) Running healthcheck tests ... done in 0 seconds
(7/15) Running mc tests ... done in 58 seconds
(8/15) Running minio-dotnet tests ... done in 1 minutes and 50 seconds
(9/15) Running minio-go tests ... FAILED in 2 minutes and 9 seconds
{
  "args": {
    "bucketName": "minio-go-test-ss43hpl1mz1kn5nm",
    "objectName": "4l24ranvqjdz43dyv00c16td2po0fc",
    "objectPrefix": "",
    "recursive": "true"
  },
  "duration": 5446,
  "error": "The bucket you tried to delete is not empty. You must delete all versions in the bucket.",
  "function": "RemoveObjectsWithOptions(bucketName, objectsCh, opts)",
  "message": "Cleanup failed",
  "name": "minio-go: testRemoveObjectsWithOptions",
  "status": "FAIL"
}
(9/15) Running minio-java tests ... done in 4 minutes and 33 seconds
(10/15) Running minio-js tests ... done in 52 seconds
(11/15) Running minio-py tests ... done in 5 minutes and 48 seconds
(12/15) Running s3cmd tests ... done in 22 seconds
(13/15) Running s3select tests ... done in 10 seconds
(14/15) Running security tests ... done in 0 seconds

Executed 14 out of 15 tests successfully.
```
Deleting image on docker hub
Deleting image locally

**Review by harshavardhana — APPROVED** [review]

**Comment by minio-trusted** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-s3.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-xl.sh | :x: [more...](#f5c7baeb-41c7-4fc5-b39f-d0001d3293cb) |
| mint-large-bucket.sh | :x: [more...](#3cfd7050-3864-4891-8d02-d8bb621d65a8) |
| mint-dist-xl.sh | :x: [more...](#3c7bd193-192a-404c-9c84-99b95549628f) |
| mint-gateway-azure.sh | :x: [more...](#cc6b65a5-49ba-4312-9b1e-9e9f14fbd625) |
| mint-zoned.sh | :x: [more...](#6c8068af-09a2-40dd-b9e4-794db8f39df3) |
<a name="f5c7baeb-41c7-4fc5-b39f-d0001d3293cb"></a>
### 9992-5c263c0/mint-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-dev6.minio.io:31493
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 0584bd811418:/mint/log /tmp/mint-logs'

(1/15) Running aws-sdk-go tests ... done in 1 seconds
(2/15) Running aws-sdk-java tests ... done in 2 seconds
(3/15) Running aws-sdk-php tests ... done in 43 seconds
(4/15) Running aws-sdk-ruby tests ... done in 3 seconds
(5/15) Running awscli tests ... done in 2 minutes and 11 seconds
(6/15) Running healthcheck tests ... done in 0 seconds
(7/15) Running mc tests ... done in 41 seconds
(8/15) Running minio-dotnet tests ... done in 43 seconds
(9/15) Running minio-go tests ... FAILED in 1 minutes and 48 seconds
{
  "args": {
    "bucketName": "minio-go-test-c2kfwbxh5zfs4fim",
    "objectName": "ha93natcgpo9oxuhdlgup0otfip6yk",
    "objectPrefix": "",
    "recursive": "true"
  },
  "duration": 5718,
  "error": "The bucket you tried to delete is not empty. You must delete all versions in the bucket.",
  "function": "RemoveObjectsWithOptions(bucketName, objectsCh, opts)",
  "message": "Cleanup failed",
  "name": "minio-go: testRemoveObjectsWithOptions",
  "status": "FAIL"
}
(9/15) Running minio-java tests ... done in 2 minutes and 11 seconds
(10/15) Running minio-js tests ... done in 54 seconds
(11/15) Running minio-py tests ... done in 4 minutes and 17 seconds
(12/15) Running s3cmd tests ... done in 22 seconds
(13/15) Running s3select tests ... done in 7 seconds
(14/15) Running security tests ... done in 0 seconds

Executed 14 out of 15 tests successfully.
```
<a name="6c8068af-09a2-40dd-b9e4-794db8f39df3"></a>
### 9992-5c263c0/mint-zoned.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-dev6.minio.io:31306
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 1e8d7932655e:/mint/log /tmp/mint-logs'

(1/15) Running aws-sdk-go tests ... done in 19 seconds
(2/15) Running aws-sdk-java tests ... done in 3 seconds
(3/15) Running aws-sdk-php tests ... done in 48 seconds
(4/15) Running aws-sdk-ruby tests ... done in 12 seconds
(5/15) Running awscli tests ... done in 2 minutes and 22 seconds
(6/15) Running healthcheck tests ... done in 0 seconds
(7/15) Running mc tests ... done in 1 minutes and 53 seconds
(8/15) Running minio-dotnet tests ... done in 2 minutes and 43 seconds
(9/15) Running minio-go tests ... FAILED in 3 minutes and 17 seconds
{
  "args": {
    "bucketName": "minio-go-test-pu5q21p6rjz3m9av",
    "objectName": "oa4b0jd4nd3rop5a2jo2mzkyqyypiv",
    "objectPrefix": "",
    "recursive": "true"
  },
  "duration": 5906,
  "error": "The bucket you tried to delete is not empty. You must delete all versions in the bucket.",
  "function": "RemoveObjectsWithOptions(bucketName, objectsCh, opts)",
  "message": "Cleanup failed",
  "name": "minio-go: testRemoveObjectsWithOptions",
  "status": "FAIL"
}
(9/15) Running minio-java tests ... done in 6 minutes and 0 seconds
(10/15) Running minio-js tests ... done in 1 minutes and 5 seconds
(11/15) Running minio-py tests ... done in 6 minutes and 2 seconds
(12/15) Running s3cmd tests ... done in 23 seconds
(13/15) Running s3select tests ... done in 11 seconds
(14/15) Running security tests ... done in 0 seconds

Executed 14 out of 15 tests successfully.
```
<a name="cc6b65a5-49ba-4312-9b1e-9e9f14fbd625"></a>
### 9992-5c263c0/mint-gateway-azure.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-c3.minio.io:32417
ACCESS_KEY:           minioazure
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 7588f418973c:/mint/log /tmp/mint-logs'

(1/15) Running aws-sdk-go tests ... done in 8 seconds
(2/15) Running aws-sdk-java tests ... done in 2 seconds
(3/15) Running aws-sdk-php tests ... done in 3 minutes and 16 seconds
(4/15) Running aws-sdk-ruby tests ... done in 17 seconds
(5/15) Running awscli tests ... FAILED in 10 seconds
{
  "name": "awscli",
  "duration": 1302,
  "function": "make_bucket\n",
  "status": "FAIL",
  "error": "An error occurred (BucketAlreadyOwnedByYou) when calling the CreateBucket operation: Your previous request to create the named bucket succeeded and you already own it."
}
(5/15) Running healthcheck tests ... done in 1 seconds
(6/15) Running mc tests ... done in 3 minutes and 45 seconds
(7/15) Running minio-dotnet tests ... done in 1 minutes and 34 seconds
(8/15) Running minio-go tests ... done in 4 minutes and 43 seconds
(9/15) Running minio-java tests ... FAILED in 5 minutes and 36 seconds
{
  "name": "minio-java",
  "function": "removeObjects(RemoveObjectsArgs args)",
  "duration": 1311,
  "status": "FAIL",
  "error": "org.simpleframework.xml.core.ValueRequiredException: Unable to satisfy @org.simpleframework.xml.Element(name=\"Key\", type=void.class, data=false, required=true) on field 'name' private java.lang.String io.minio.messages.DeletedObject.name for class io.minio.messages.DeletedObject at line 2 >>> [io.minio.Xml.unmarshal(Xml.java:68), io.minio.MinioClient.deleteObjects(MinioClient.java:7354), io.minio.MinioClient$1$1.populate(MinioClient.java:2945), io.minio.MinioClient$1$1.hasNext(MinioClient.java:2977), FunctionalTest.removeObjects(FunctionalTest.java:1395), FunctionalTest.removeObjects_test1(FunctionalTest.java:1534), FunctionalTest.runTests(FunctionalTest.java:3812), FunctionalTest.main(FunctionalTest.java:4056)]"
}
(9/15) Running minio-js tests ... done in 2 minutes and 41 seconds
(10/15) Running minio-py tests ... done in 10 minutes and 2 seconds
(11/15) Running s3cmd tests ... done in 1 minutes and 22 seconds
(12/15) Running s3select tests ... done in 1 minutes and 8 seconds
(13/15) Running security tests ... done in 0 seconds

Executed 13 out of 15 tests successfully.
```
<a name="3c7bd193-192a-404c-9c84-99b95549628f"></a>
### 9992-5c263c0/mint-dist-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-dev7.minio.io:31173
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 9c21f358633d:/mint/log /tmp/mint-logs'

(1/15) Running aws-sdk-go tests ... done in 13 seconds
(2/15) Running aws-sdk-java tests ... done in 2 seconds
(3/15) Running aws-sdk-php tests ... done in 48 seconds
(4/15) Running aws-sdk-ruby tests ... done in 10 seconds
(5/15) Running awscli tests ... done in 1 minutes and 42 seconds
(6/15) Running healthcheck tests ... done in 0 seconds
(7/15) Running mc tests ... done in 1 minutes and 39 seconds
(8/15) Running minio-dotnet tests ... done in 2 minutes and 31 seconds
(9/15) Running minio-go tests ... FAILED in 2 minutes and 20 seconds
{
  "args": {
    "bucketName": "minio-go-test-auawd0xz6s9kvp3w",
    "objectName": "xel4sr1f0ooo0na34nnj6mne10lmmk",
    "objectPrefix": "",
    "recursive": "true"
  },
  "duration": 4844,
  "error": "The bucket you tried to delete is not empty. You must delete all versions in the bucket.",
  "function": "RemoveObjectsWithOptions(bucketName, objectsCh, opts)",
  "message": "Cleanup failed",
  "name": "minio-go: testRemoveObjectsWithOptions",
  "status": "FAIL"
}
(9/15) Running minio-java tests ... done in 4 minutes and 51 seconds
(10/15) Running minio-js tests ... done in 1 minutes and 2 seconds
(11/15) Running minio-py tests ... done in 5 minutes and 9 seconds
(12/15) Running s3cmd tests ... done in 32 seconds
(13/15) Running s3select tests ... done in 27 seconds
(14/15) Running security tests ... done in 0 seconds

Executed 14 out of 15 tests successfully.
```
<a name="3cfd7050-3864-4891-8d02-d8bb621d65a8"></a>
### 9992-5c263c0/mint-large-bucket.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-dev4.minio.io:31402
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 46f7ebc32b1c:/mint/log /tmp/mint-logs'

(1/15) Running aws-sdk-go tests ... done in 11 seconds
(2/15) Running aws-sdk-java tests ... done in 3 seconds
(3/15) Running aws-sdk-php tests ... done in 50 seconds
(4/15) Running aws-sdk-ruby tests ... done in 10 seconds
(5/15) Running awscli tests ... done in 2 minutes and 42 seconds
(6/15) Running healthcheck tests ... done in 0 seconds
(7/15) Running mc tests ... done in 1 minutes and 26 seconds
(8/15) Running minio-dotnet tests ... done in 2 minutes and 22 seconds
(9/15) Running minio-go tests ... FAILED in 2 minutes and 37 seconds
{
  "args": {
    "bucketName": "minio-go-test-9bskdzbbf5reqw5m",
    "objectName": "sulh3r4tey6gntp4vk2cl6mctmckjx",
    "objectPrefix": "",
    "recursive": "true"
  },
  "duration": 6709,
  "error": "The bucket you tried to delete is not empty. You must delete all versions in the bucket.",
  "function": "RemoveObjectsWithOptions(bucketName, objectsCh, opts)",
  "message": "Cleanup failed",
  "name": "minio-go: testRemoveObjectsWithOptions",
  "status": "FAIL"
}
(9/15) Running minio-java tests ... done in 4 minutes and 48 seconds
(10/15) Running minio-js tests ... done in 55 seconds
(11/15) Running minio-py tests ... done in 6 minutes and 8 seconds
(12/15) Running s3cmd tests ... done in 25 seconds
(13/15) Running s3select tests ... done in 12 seconds
(14/15) Running security tests ... done in 0 seconds

Executed 14 out of 15 tests successfully.
```
Deleting image on docker hub
Deleting image locally

File: cmd/tree-walk-pool.go [hunk 1]
```diff
@@ -153,7 +164,10 @@ func (t *TreeWalkPool) Set(params listParams, resultCh chan TreeWalkResult, endW
 		t.pool[params] = append(walks, walkInfo)
 	} else {
 		// We are at limit, invalidate oldest, move list down and add new as last.
-		walks[0].endTimerCh <- struct{}{}
+		select {
+		case walks[0].endTimerCh <- struct{}{}:
```
Comment (vadmeste) [inline cmd/tree-walk-pool.go:166]: If I understood correctly, we can have some leaking go routines here, because
select {
case
default:
}

can ignore sending the message if the goroutine is not ready yet to listen from the channel

**Review by vadmeste — COMMENTED** [review]
One comment

File: cmd/tree-walk-pool.go (hunk 1 above)
Comment (harshavardhana) [reply cmd/tree-walk-pool.go:166]: @klauspost ^^

**Comment by minio-trusted** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-gateway-s3.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-xl.sh | :x: [more...](#188bdfd8-bf4b-4713-9730-2ec5686fc101) |
| mint-large-bucket.sh | :x: [more...](#f822e0b1-b67d-45d8-aeec-960ce7782989) |
| mint-fs.sh | :x: [more...](#8987984b-4095-4921-8bde-4947520d4b13) |
| mint-dist-xl.sh | :x: [more...](#5bef48a6-7465-4a39-8867-41a6865903a0) |
| mint-gateway-azure.sh | :x: [more...](#3c849e5c-fc18-41c4-859d-30ddc6b14967) |
| mint-zoned.sh | :x: [more...](#9af6fb19-868d-4b91-9124-1612775bdb30) |
<a name="9af6fb19-868d-4b91-9124-1612775bdb30"></a>
### 9992-ef6b14f/mint-zoned.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-dev4.minio.io:30092
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 64db81a3b687:/mint/log /tmp/mint-logs'

(1/15) Running aws-sdk-go tests ... done in 18 seconds
(2/15) Running aws-sdk-java tests ... done in 3 seconds
(3/15) Running aws-sdk-php tests ... done in 48 seconds
(4/15) Running aws-sdk-ruby tests ... done in 12 seconds
(5/15) Running awscli tests ... done in 3 minutes and 48 seconds
(6/15) Running healthcheck tests ... done in 0 seconds
(7/15) Running mc tests ... done in 1 minutes and 11 seconds
(8/15) Running minio-dotnet tests ... done in 2 minutes and 10 seconds
(9/15) Running minio-go tests ... FAILED in 4 minutes and 21 seconds
{
  "args": {
    "bucketName": "minio-go-test-v2hq4ef9qe5cnvaf",
    "objectName": "66z9wf36jqyqk65cuzmfllcg9drp1u",
    "objectPrefix": "",
    "recursive": "true"
  },
  "duration": 8207,
  "error": "The bucket you tried to delete is not empty. You must delete all versions in the bucket.",
  "function": "RemoveObjectsWithOptions(bucketName, objectsCh, opts)",
  "message": "Cleanup failed",
  "name": "minio-go: testRemoveObjectsWithOptions",
  "status": "FAIL"
}
(9/15) Running minio-java tests ... done in 6 minutes and 17 seconds
(10/15) Running minio-js tests ... done in 1 minutes and 3 seconds
(11/15) Running minio-py tests ... done in 6 minutes and 43 seconds
(12/15) Running s3cmd tests ... done in 27 seconds
(13/15) Running s3select tests ... done in 9 seconds
(14/15) Running security tests ... done in 0 seconds

Executed 14 out of 15 tests successfully.
```
<a name="188bdfd8-bf4b-4713-9730-2ec5686fc101"></a>
### 9992-ef6b14f/mint-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-c2.minio.io:30706
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 2a7462b180bc:/mint/log /tmp/mint-logs'

(1/15) Running aws-sdk-go tests ... done in 4 seconds
(2/15) Running aws-sdk-java tests ... done in 2 seconds
(3/15) Running aws-sdk-php tests ... done in 46 seconds
(4/15) Running aws-sdk-ruby tests ... done in 3 seconds
(5/15) Running awscli tests ... done in 1 minutes and 13 seconds
(6/15) Running healthcheck tests ... done in 0 seconds
(7/15) Running mc tests ... done in 30 seconds
(8/15) Running minio-dotnet tests ... done in 40 seconds
(9/15) Running minio-go tests ... FAILED in 1 minutes and 18 seconds
{
  "args": {
    "bucketName": "minio-go-test-6hcn4sxuqpk4ptvw",
    "objectName": "csp9hbxuqbxzrtyqb00903yd1huwev",
    "objectPrefix": "",
    "recursive": "true"
  },
  "duration": 3554,
  "error": "The bucket you tried to delete is not empty. You must delete all versions in the bucket.",
  "function": "RemoveObjectsWithOptions(bucketName, objectsCh, opts)",
  "message": "Cleanup failed",
  "name": "minio-go: testRemoveObjectsWithOptions",
  "status": "FAIL"
}
(9/15) Running minio-java tests ... done in 2 minutes and 51 seconds
(10/15) Running minio-js tests ... done in 50 seconds
(11/15) Running minio-py tests ... done in 6 minutes and 34 seconds
(12/15) Running s3cmd tests ... done in 24 seconds
(13/15) Running s3select tests ... done in 16 seconds
(14/15) Running security tests ... done in 0 seconds

Executed 14 out of 15 tests successfully.
```
<a name="f822e0b1-b67d-45d8-aeec-960ce7782989"></a>
### 9992-ef6b14f/mint-large-bucket.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-dev3.minio.io:30331
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 2f9b6ba00807:/mint/log /tmp/mint-logs'

(1/15) Running aws-sdk-go tests ... done in 16 seconds
(2/15) Running aws-sdk-java tests ... done in 4 seconds
(3/15) Running aws-sdk-php tests ... done in 47 seconds
(4/15) Running aws-sdk-ruby tests ... done in 11 seconds
(5/15) Running awscli tests ... done in 2 minutes and 28 seconds
(6/15) Running healthcheck tests ... done in 1 seconds
(7/15) Running mc tests ... done in 1 minutes and 26 seconds
(8/15) Running minio-dotnet tests ... done in 2 minutes and 41 seconds
(9/15) Running minio-go tests ... FAILED in 3 minutes and 12 seconds
{
  "args": {
    "bucketName": "minio-go-test-2swc9onoewg5kecs",
    "objectName": "ckf9u0s23pg25oogj5cufyn4ephv5z",
    "objectPrefix": "",
    "recursive": "true"
  },
  "duration": 5382,
  "error": "The bucket you tried to delete is not empty. You must delete all versions in the bucket.",
  "function": "RemoveObjectsWithOptions(bucketName, objectsCh, opts)",
  "message": "Cleanup failed",
  "name": "minio-go: testRemoveObjectsWithOptions",
  "status": "FAIL"
}
(9/15) Running minio-java tests ... done in 6 minutes and 8 seconds
(10/15) Running minio-js tests ... done in 54 seconds
(11/15) Running minio-py tests ... done in 6 minutes and 26 seconds
(12/15) Running s3cmd tests ... done in 24 seconds
(13/15) Running s3select tests ... done in 14 seconds
(14/15) Running security tests ... done in 0 seconds

Executed 14 out of 15 tests successfully.
```
<a name="5bef48a6-7465-4a39-8867-41a6865903a0"></a>
### 9992-ef6b14f/mint-dist-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-dev7.minio.io:32298
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp e6b0db486878:/mint/log /tmp/mint-logs'

(1/15) Running aws-sdk-go tests ... done in 14 seconds
(2/15) Running aws-sdk-java tests ... done in 2 seconds
(3/15) Running aws-sdk-php tests ... done in 49 seconds
(4/15) Running aws-sdk-ruby tests ... done in 7 seconds
(5/15) Running awscli tests ... done in 2 minutes and 53 seconds
(6/15) Running healthcheck tests ... done in 0 seconds
(7/15) Running mc tests ... done in 1 minutes and 39 seconds
(8/15) Running minio-dotnet tests ... done in 2 minutes and 17 seconds
(9/15) Running minio-go tests ... FAILED in 2 minutes and 51 seconds
{
  "args": {
    "bucketName": "minio-go-test-ficp9j9sxm0cfo3t",
    "objectName": "fi6nkse43xoh0zjsdhahbm56yit6fc",
    "objectPrefix": "",
    "recursive": "true"
  },
  "duration": 4511,
  "error": "The bucket you tried to delete is not empty. You must delete all versions in the bucket.",
  "function": "RemoveObjectsWithOptions(bucketName, objectsCh, opts)",
  "message": "Cleanup failed",
  "name": "minio-go: testRemoveObjectsWithOptions",
  "status": "FAIL"
}
(9/15) Running minio-java tests ... done in 5 minutes and 55 seconds
(10/15) Running minio-js tests ... done in 56 seconds
(11/15) Running minio-py tests ... done in 5 minutes and 7 seconds
(12/15) Running s3cmd tests ... done in 31 seconds
(13/15) Running s3select tests ... done in 27 seconds
(14/15) Running security tests ... done in 0 seconds

Executed 14 out of 15 tests successfully.
```
<a name="3c849e5c-fc18-41c4-859d-30ddc6b14967"></a>
### 9992-ef6b14f/mint-gateway-azure.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-c2.minio.io:31787
ACCESS_KEY:           minioazure
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 9d97c2813ea7:/mint/log /tmp/mint-logs'

(1/15) Running aws-sdk-go tests ... done in 7 seconds
(2/15) Running aws-sdk-java tests ... done in 3 seconds
(3/15) Running aws-sdk-php tests ... done in 3 minutes and 15 seconds
(4/15) Running aws-sdk-ruby tests ... done in 16 seconds
(5/15) Running awscli tests ... done in 2 minutes and 37 seconds
(6/15) Running healthcheck tests ... done in 0 seconds
(7/15) Running mc tests ... done in 3 minutes and 10 seconds
(8/15) Running minio-dotnet tests ... done in 1 minutes and 34 seconds
(9/15) Running minio-go tests ... done in 5 minutes and 18 seconds
(10/15) Running minio-java tests ... FAILED in 5 minutes and 18 seconds
{
  "name": "minio-java",
  "function": "removeObjects(RemoveObjectsArgs args)",
  "duration": 1767,
  "status": "FAIL",
  "error": "org.simpleframework.xml.core.ValueRequiredException: Unable to satisfy @org.simpleframework.xml.Element(name=\"Key\", type=void.class, data=false, required=true) on field 'name' private java.lang.String io.minio.messages.DeletedObject.name for class io.minio.messages.DeletedObject at line 2 >>> [io.minio.Xml.unmarshal(Xml.java:68), io.minio.MinioClient.deleteObjects(MinioClient.java:7354), io.minio.MinioClient$1$1.populate(MinioClient.java:2945), io.minio.MinioClient$1$1.hasNext(MinioClient.java:2977), FunctionalTest.removeObjects(FunctionalTest.java:1395), FunctionalTest.removeObjects_test1(FunctionalTest.java:1534), FunctionalTest.runTests(FunctionalTest.java:3812), FunctionalTest.main(FunctionalTest.java:4056)]"
}
(10/15) Running minio-js tests ... done in 2 minutes and 38 seconds
(11/15) Running minio-py tests ... done in 9 minutes and 43 seconds
(12/15) Running s3cmd tests ... done in 1 minutes and 23 seconds
(13/15) Running s3select tests ... done in 1 minutes and 5 seconds
(14/15) Running security tests ... done in 0 seconds

Executed 14 out of 15 tests successfully.
```
<a name="8987984b-4095-4921-8bde-4947520d4b13"></a>
### 9992-ef6b14f/mint-fs.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-dev3.minio.io:30793
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 1c99e0f9cc66:/mint/log /tmp/mint-logs'

(1/15) Running aws-sdk-go tests ... done in 1 seconds
(2/15) Running aws-sdk-java tests ... done in 2 seconds
(3/15) Running aws-sdk-php tests ... done in 42 seconds
(4/15) Running aws-sdk-ruby tests ... done in 1 seconds
(5/15) Running awscli tests ... done in 1 minutes and 6 seconds
(6/15) Running healthcheck tests ... done in 0 seconds
(7/15) Running mc tests ... done in 29 seconds
(8/15) Running minio-dotnet tests ... done in 29 seconds
(9/15) Running minio-go tests ... done in 44 seconds
(10/15) Running minio-java tests ... done in 28 seconds
(11/15) Running minio-js tests ... FAILED in 3 seconds
{
  "name": "minio-js",
  "function": "\"after all\" hook in \"functional tests\"",
  "duration": 7,
  "status": "FAIL",
  "error": "S3Error: The bucket you tried to delete is not empty at Object.parseError (node_modules/minio/dist/main/xml-parsers.js:86:11) at /mint/run/core/minio-js/node_modules/minio/dist/main/transformers.js:156:22 at DestroyableTransform._flush (node_modules/minio/dist/main/transformers.js:80:10) at DestroyableTransform.prefinish (node_modules/readable-stream/lib/_stream_transform.js:129:10) at prefinish (node_modules/readable-stream/lib/_stream_writable.js:611:14) at finishMaybe (node_modules/readable-stream/lib/_stream_writable.js:620:5) at endWritable (node_modules/readable-stream/lib/_stream_writable.js:643:3) at DestroyableTransform.Writable.end (node_modules/readable-stream/lib/_stream_writable.js:571:22) at IncomingMessage.onend (_stream_readable.js:673:10) at endReadableNT (_stream_readable.js:1201:12) at processTicksAndRejections (internal/process/task_queues.js:84:21)"
}
(11/15) Running minio-py tests ... done in 1 minutes and 20 seconds
(12/15) Running s3cmd tests ... done in 22 seconds
(13/15) Running s3select tests ... done in 3 seconds
(14/15) Running security tests ... done in 0 seconds

Executed 14 out of 15 tests successfully.
```
Deleting image on docker hub
Deleting image locally

File: cmd/tree-walk-pool.go (hunk 1 above)
Comment (klauspost) [reply cmd/tree-walk-pool.go:166]: It will only skip it if there is a message or it is closed. In both cases the goroutine will exit.

Comment (klauspost) [reply cmd/tree-walk-pool.go:166]: @vadmeste @harshavardhana

**Comment by harshavardhana** [comment]
PTAL @vadmeste we need this before the release

**Comment by minio-trusted** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-xl.sh | :x: [more...](#1fc06679-74e2-476b-821a-e35791bfa4ed) |
| mint-large-bucket.sh | :x: [more...](#3161ba90-118d-43c1-afa5-83e8b6182637) |
| mint-dist-xl.sh | :x: [more...](#fcb297cb-af55-434a-972b-a549027e753c) |
| mint-gateway-s3.sh | :x: [more...](#32263da3-2703-44cd-8423-e91fb67d321b) |
| mint-gateway-azure.sh | :x: [more...](#77c0a038-8de0-4701-9be8-1dde8edb9ed2) |
| mint-zoned.sh | :x: [more...](#90e68047-774e-4971-9220-937c3d53ff3d) |
<a name="3161ba90-118d-43c1-afa5-83e8b6182637"></a>
### 9992-652561a/mint-large-bucket.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-c3.minio.io:32238
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 72212786f254:/mint/log /tmp/mint-logs'

(1/15) Running aws-sdk-go tests ... done in 14 seconds
(2/15) Running aws-sdk-java tests ... done in 2 seconds
(3/15) Running aws-sdk-php tests ... done in 46 seconds
(4/15) Running aws-sdk-ruby tests ... done in 14 seconds
(5/15) Running awscli tests ... done in 2 minutes and 32 seconds
(6/15) Running healthcheck tests ... done in 0 seconds
(7/15) Running mc tests ... done in 1 minutes and 46 seconds
(8/15) Running minio-dotnet tests ... done in 2 minutes and 9 seconds
(9/15) Running minio-go tests ... FAILED in 2 minutes and 28 seconds
{
  "args": {
    "bucketName": "minio-go-test-12qiot3hpq3hphgn",
    "objectName": "jigdzoz96pahjhd9ravswpwdtws0w5",
    "objectPrefix": "",
    "recursive": "true"
  },
  "duration": 5689,
  "error": "The bucket you tried to delete is not empty. You must delete all versions in the bucket.",
  "function": "RemoveObjectsWithOptions(bucketName, objectsCh, opts)",
  "message": "Cleanup failed",
  "name": "minio-go: testRemoveObjectsWithOptions",
  "status": "FAIL"
}
(9/15) Running minio-java tests ... done in 4 minutes and 38 seconds
(10/15) Running minio-js tests ... done in 55 seconds
(11/15) Running minio-py tests ... done in 5 minutes and 34 seconds
(12/15) Running s3cmd tests ... done in 23 seconds
(13/15) Running s3select tests ... done in 13 seconds
(14/15) Running security tests ... done in 0 seconds

Executed 14 out of 15 tests successfully.
```
<a name="32263da3-2703-44cd-8423-e91fb67d321b"></a>
### 9992-652561a/mint-gateway-s3.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-dev6.minio.io:32501
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 09ce02ea9cfb:/mint/log /tmp/mint-logs'

(1/15) Running aws-sdk-go tests ... done in 0 seconds
(2/15) Running aws-sdk-java tests ... done in 2 seconds
(3/15) Running aws-sdk-php tests ... done in 41 seconds
(4/15) Running aws-sdk-ruby tests ... done in 1 seconds
(5/15) Running awscli tests ... done in 2 minutes and 0 seconds
(6/15) Running healthcheck tests ... done in 0 seconds
(7/15) Running mc tests ... done in 23 seconds
(8/15) Running minio-dotnet tests ... done in 29 seconds
(9/15) Running minio-go tests ... done in 33 seconds
(10/15) Running minio-java tests ... done in 44 seconds
(11/15) Running minio-js tests ... FAILED in 30 minutes and 17 seconds
{
  "name": "minio-js",
  "function": "\"after all\" hook in \"functional tests\"",
  "duration": 14,
  "status": "FAIL",
  "error": "S3Error: The bucket you tried to delete is not empty at Object.parseError (node_modules/minio/dist/main/xml-parsers.js:86:11) at /mint/run/core/minio-js/node_modules/minio/dist/main/transformers.js:156:22 at DestroyableTransform._flush (node_modules/minio/dist/main/transformers.js:80:10) at DestroyableTransform.prefinish (node_modules/readable-stream/lib/_stream_transform.js:129:10) at prefinish (node_modules/readable-stream/lib/_stream_writable.js:611:14) at finishMaybe (node_modules/readable-stream/lib/_stream_writable.js:620:5) at endWritable (node_modules/readable-stream/lib/_stream_writable.js:643:3) at DestroyableTransform.Writable.end (node_modules/readable-stream/lib/_stream_writable.js:571:22) at IncomingMessage.onend (_stream_readable.js:673:10) at endReadableNT (_stream_readable.js:1201:12) at processTicksAndRejections (internal/process/task_queues.js:84:21)"
}
(11/15) Running minio-py tests ... done in 51 seconds
(12/15) Running s3cmd tests ... done in 1 minutes and 4 seconds
(13/15) Running s3select tests ... done in 2 seconds
(14/15) Running security tests ... done in 0 seconds

Executed 14 out of 15 tests successfully.
```
<a name="77c0a038-8de0-4701-9be8-1dde8edb9ed2"></a>
### 9992-652561a/mint-gateway-azure.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-dev3.minio.io:31136
ACCESS_KEY:           minioazure
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp cfa0339b6a10:/mint/log /tmp/mint-logs'

(1/15) Running aws-sdk-go tests ... done in 8 seconds
(2/15) Running aws-sdk-java tests ... done in 2 seconds
(3/15) Running aws-sdk-php tests ... done in 3 minutes and 11 seconds
(4/15) Running aws-sdk-ruby tests ... done in 16 seconds
(5/15) Running awscli tests ... done in 2 minutes and 41 seconds
(6/15) Running healthcheck tests ... done in 0 seconds
(7/15) Running mc tests ... done in 2 minutes and 56 seconds
(8/15) Running minio-dotnet tests ... done in 1 minutes and 34 seconds
(9/15) Running minio-go tests ... done in 5 minutes and 18 seconds
(10/15) Running minio-java tests ... FAILED in 5 minutes and 19 seconds
{
  "name": "minio-java",
  "function": "removeObjects(RemoveObjectsArgs args)",
  "duration": 1286,
  "status": "FAIL",
  "error": "org.simpleframework.xml.core.ValueRequiredException: Unable to satisfy @org.simpleframework.xml.Element(name=\"Key\", type=void.class, data=false, required=true) on field 'name' private java.lang.String io.minio.messages.DeletedObject.name for class io.minio.messages.DeletedObject at line 2 >>> [io.minio.Xml.unmarshal(Xml.java:68), io.minio.MinioClient.deleteObjects(MinioClient.java:7354), io.minio.MinioClient$1$1.populate(MinioClient.java:2945), io.minio.MinioClient$1$1.hasNext(MinioClient.java:2977), FunctionalTest.removeObjects(FunctionalTest.java:1395), FunctionalTest.removeObjects_test1(FunctionalTest.java:1534), FunctionalTest.runTests(FunctionalTest.java:3812), FunctionalTest.main(FunctionalTest.java:4056)]"
}
(10/15) Running minio-js tests ... done in 2 minutes and 37 seconds
(11/15) Running minio-py tests ... done in 9 minutes and 36 seconds
(12/15) Running s3cmd tests ... done in 1 minutes and 48 seconds
(13/15) Running s3select tests ... done in 1 minutes and 4 seconds
(14/15) Running security tests ... done in 0 seconds

Executed 14 out of 15 tests successfully.
```
<a name="fcb297cb-af55-434a-972b-a549027e753c"></a>
### 9992-652561a/mint-dist-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-dev6.minio.io:31205
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 1f7097466c5a:/mint/log /tmp/mint-logs'

(1/15) Running aws-sdk-go tests ... done in 8 seconds
(2/15) Running aws-sdk-java tests ... done in 2 seconds
(3/15) Running aws-sdk-php tests ... done in 45 seconds
(4/15) Running aws-sdk-ruby tests ... done in 6 seconds
(5/15) Running awscli tests ... done in 2 minutes and 22 seconds
(6/15) Running healthcheck tests ... done in 0 seconds
(7/15) Running mc tests ... done in 1 minutes and 0 seconds
(8/15) Running minio-dotnet tests ... done in 2 minutes and 32 seconds
(9/15) Running minio-go tests ... FAILED in 2 minutes and 49 seconds
{
  "args": {
    "bucketName": "minio-go-test-ir23m4thzzlgjc6i",
    "objectName": "6b2zr5k5jsslf3acfowexeqygxbwhi",
    "objectPrefix": "",
    "recursive": "true"
  },
  "duration": 5557,
  "error": "The bucket you tried to delete is not empty. You must delete all versions in the bucket.",
  "function": "RemoveObjectsWithOptions(bucketName, objectsCh, opts)",
  "message": "Cleanup failed",
  "name": "minio-go: testRemoveObjectsWithOptions",
  "status": "FAIL"
}
(9/15) Running minio-java tests ... done in 4 minutes and 32 seconds
(10/15) Running minio-js tests ... FAILED in 32 seconds
{
  "name": "minio-js",
  "function": "\"after all\" hook in \"functional tests\"",
  "duration": 7,
  "status": "FAIL",
  "error": "S3Error: The bucket you tried to delete is not empty at Object.parseError (node_modules/minio/dist/main/xml-parsers.js:86:11) at /mint/run/core/minio-js/node_modules/minio/dist/main/transformers.js:156:22 at DestroyableTransform._flush (node_modules/minio/dist/main/transformers.js:80:10) at DestroyableTransform.prefinish (node_modules/readable-stream/lib/_stream_transform.js:129:10) at prefinish (node_modules/readable-stream/lib/_stream_writable.js:611:14) at finishMaybe (node_modules/readable-stream/lib/_stream_writable.js:620:5) at endWritable (node_modules/readable-stream/lib/_stream_writable.js:643:3) at DestroyableTransform.Writable.end (node_modules/readable-stream/lib/_stream_writable.js:571:22) at IncomingMessage.onend (_stream_readable.js:673:10) at endReadableNT (_stream_readable.js:1201:12) at processTicksAndRejections (internal/process/task_queues.js:84:21)"
}
(10/15) Running minio-py tests ... done in 4 minutes and 56 seconds
(11/15) Running s3cmd tests ... done in 24 seconds
(12/15) Running s3select tests ... done in 17 seconds
(13/15) Running security tests ... done in 0 seconds

Executed 13 out of 15 tests successfully.
```
<a name="90e68047-774e-4971-9220-937c3d53ff3d"></a>
### 9992-652561a/mint-zoned.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-dev3.minio.io:30493
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 8fade9bf4f29:/mint/log /tmp/mint-logs'

(1/15) Running aws-sdk-go tests ... done in 11 seconds
(2/15) Running aws-sdk-java tests ... done in 2 seconds
(3/15) Running aws-sdk-php tests ... done in 50 seconds
(4/15) Running aws-sdk-ruby tests ... done in 17 seconds
(5/15) Running awscli tests ... done in 2 minutes and 37 seconds
(6/15) Running healthcheck tests ... done in 1 seconds
(7/15) Running mc tests ... done in 1 minutes and 29 seconds
(8/15) Running minio-dotnet tests ... done in 2 minutes and 21 seconds
(9/15) Running minio-go tests ... FAILED in 3 minutes and 11 seconds
{
  "args": {
    "bucketName": "minio-go-test-dfrdirlkdefiv925",
    "objectName": "iwpxxjo6kxbet0p22zbobyedxka6kv",
    "objectPrefix": "",
    "recursive": "true"
  },
  "duration": 3833,
  "error": "The bucket you tried to delete is not empty. You must delete all versions in the bucket.",
  "function": "RemoveObjectsWithOptions(bucketName, objectsCh, opts)",
  "message": "Cleanup failed",
  "name": "minio-go: testRemoveObjectsWithOptions",
  "status": "FAIL"
}
(9/15) Running minio-java tests ... done in 5 minutes and 49 seconds
(10/15) Running minio-js tests ... done in 1 minutes and 3 seconds
(11/15) Running minio-py tests ... done in 6 minutes and 4 seconds
(12/15) Running s3cmd tests ... done in 22 seconds
(13/15) Running s3select tests ... done in 13 seconds
(14/15) Running security tests ... done in 0 seconds

Executed 14 out of 15 tests successfully.
```
<a name="1fc06679-74e2-476b-821a-e35791bfa4ed"></a>
### 9992-652561a/mint-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-dev6.minio.io:30917
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 144f7d665b9c:/mint/log /tmp/mint-logs'

(1/15) Running aws-sdk-go tests ... done in 2 seconds
(2/15) Running aws-sdk-java tests ... done in 2 seconds
(3/15) Running aws-sdk-php tests ... done in 44 seconds
(4/15) Running aws-sdk-ruby tests ... done in 3 seconds
(5/15) Running awscli tests ... done in 2 minutes and 8 seconds
(6/15) Running healthcheck tests ... done in 0 seconds
(7/15) Running mc tests ... done in 31 seconds
(8/15) Running minio-dotnet tests ... done in 52 seconds
(9/15) Running minio-go tests ... FAILED in 1 minutes and 28 seconds
{
  "args": {
    "bucketName": "minio-go-test-z6og2mcnrbe2cx4c",
    "objectName": "a4ucqv9zpbr95rwxplpcymdj61algl",
    "objectPrefix": "",
    "recursive": "true"
  },
  "duration": 2763,
  "error": "The bucket you tried to delete is not empty. You must delete all versions in the bucket.",
  "function": "RemoveObjectsWithOptions(bucketName, objectsCh, opts)",
  "message": "Cleanup failed",
  "name": "minio-go: testRemoveObjectsWithOptions",
  "status": "FAIL"
}
(9/15) Running minio-java tests ... done in 1 minutes and 50 seconds
(10/15) Running minio-js tests ... done in 54 seconds
(11/15) Running minio-py tests ... done in 4 minutes and 51 seconds
(12/15) Running s3cmd tests ... done in 21 seconds
(13/15) Running s3select tests ... done in 10 seconds
(14/15) Running security tests ... done in 0 seconds

Executed 14 out of 15 tests successfully.
```
Deleting image on docker hub
Deleting image locally

File: cmd/tree-walk-pool.go (hunk 1 above)
Comment (vadmeste) [reply cmd/tree-walk-pool.go:166]: > It will only skip it if there is a message or it is closed. In both cases the goroutine will exit.

oh yes, because the channel is buffered

File: cmd/tree-walk-pool.go [hunk 2]
```diff
@@ -121,21 +120,33 @@ func (t *TreeWalkPool) Set(params listParams, resultCh chan TreeWalkResult, endW
...
-			walks = walks[1:]
-			if len(walks) > 0 {
-				t.pool[params] = walks
+		if walks, ok := t.pool[oldest]; ok && len(walks) > 0 {
+			endCh := walks[0].endTimerCh
+			if len(walks) > 1 {
+				// Move walks forward
+				copy(walks, walks[1:])
+				walks = walks[:len(walks)-1]
+				if len(walks) > 0 {
```
Comment (vadmeste) [inline cmd/tree-walk-pool.go]: This if looks uneeded, it is also true here. (because it is in another condition where it makes sure that walks has at least two elements and we are removing only one element from it)

LGTM otherwise

Comment (klauspost) [reply cmd/tree-walk-pool.go]: Yeah, just defensive programming.

Comment (klauspost) [reply cmd/tree-walk-pool.go]: I can take it out, since it is pretty obviously not going to happen

**Review by vadmeste — APPROVED** [review]
LGTM

**Comment by minio-trusted** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-s3.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-xl.sh | :x: [more...](#1c1f115f-fe47-4548-98b5-38b8b6670a3f) |
| mint-large-bucket.sh | :x: [more...](#3c527d1a-a553-4f9b-90a7-df48e639f9c6) |
| mint-dist-xl.sh | :x: [more...](#1b23c7fb-8d01-486d-861b-ff20ef4f67dd) |
| mint-gateway-azure.sh | :x: [more...](#ea38a642-89ba-4d20-bf33-68e5573e62a3) |
| mint-zoned.sh | :x: [more...](#2ef2fbdd-bca0-48e8-8867-e1db87d8dd3f) |
<a name="2ef2fbdd-bca0-48e8-8867-e1db87d8dd3f"></a>
### 9992-9b4cdb3/mint-zoned.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-dev7.minio.io:32225
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp d671c0c689bd:/mint/log /tmp/mint-logs'

(1/15) Running aws-sdk-go tests ... done in 10 seconds
(2/15) Running aws-sdk-java tests ... done in 2 seconds
(3/15) Running aws-sdk-php tests ... done in 50 seconds
(4/15) Running aws-sdk-ruby tests ... done in 12 seconds
(5/15) Running awscli tests ... done in 1 minutes and 26 seconds
(6/15) Running healthcheck tests ... done in 0 seconds
(7/15) Running mc tests ... done in 1 minutes and 14 seconds
(8/15) Running minio-dotnet tests ... done in 3 minutes and 45 seconds
(9/15) Running minio-go tests ... FAILED in 3 minutes and 40 seconds
{
  "args": {
    "bucketName": "minio-go-test-00vepvqxhqviyjga",
    "objectName": "5cgz4cipwvp19dpw15ccdwav4jdkts",
    "objectPrefix": "",
    "recursive": "true"
  },
  "duration": 7079,
  "error": "The bucket you tried to delete is not empty. You must delete all versions in the bucket.",
  "function": "RemoveObjectsWithOptions(bucketName, objectsCh, opts)",
  "message": "Cleanup failed",
  "name": "minio-go: testRemoveObjectsWithOptions",
  "status": "FAIL"
}
(9/15) Running minio-java tests ... done in 5 minutes and 13 seconds
(10/15) Running minio-js tests ... done in 1 minutes and 1 seconds
(11/15) Running minio-py tests ... done in 7 minutes and 10 seconds
(12/15) Running s3cmd tests ... done in 25 seconds
(13/15) Running s3select tests ... done in 12 seconds
(14/15) Running security tests ... done in 0 seconds

Executed 14 out of 15 tests successfully.
```
<a name="1b23c7fb-8d01-486d-861b-ff20ef4f67dd"></a>
### 9992-9b4cdb3/mint-dist-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-dev4.minio.io:30963
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 7f3a9066fb2b:/mint/log /tmp/mint-logs'

(1/15) Running aws-sdk-go tests ... done in 13 seconds
(2/15) Running aws-sdk-java tests ... done in 2 seconds
(3/15) Running aws-sdk-php tests ... done in 46 seconds
(4/15) Running aws-sdk-ruby tests ... done in 9 seconds
(5/15) Running awscli tests ... done in 2 minutes and 21 seconds
(6/15) Running healthcheck tests ... done in 0 seconds
(7/15) Running mc tests ... done in 1 minutes and 30 seconds
(8/15) Running minio-dotnet tests ... done in 3 minutes and 2 seconds
(9/15) Running minio-go tests ... FAILED in 2 minutes and 32 seconds
{
  "args": {
    "bucketName": "minio-go-test-vntwq0rolul9jf40",
    "objectName": "cjqwadfpssdpvzbv6c5zw9au5crd4d",
    "objectPrefix": "",
    "recursive": "true"
  },
  "duration": 4369,
  "error": "The bucket you tried to delete is not empty. You must delete all versions in the bucket.",
  "function": "RemoveObjectsWithOptions(bucketName, objectsCh, opts)",
  "message": "Cleanup failed",
  "name": "minio-go: testRemoveObjectsWithOptions",
  "status": "FAIL"
}
(9/15) Running minio-java tests ... done in 4 minutes and 30 seconds
(10/15) Running minio-js tests ... done in 58 seconds
(11/15) Running minio-py tests ... done in 5 minutes and 0 seconds
(12/15) Running s3cmd tests ... done in 26 seconds
(13/15) Running s3select tests ... done in 19 seconds
(14/15) Running security tests ... done in 0 seconds

Executed 14 out of 15 tests successfully.
```
<a name="ea38a642-89ba-4d20-bf33-68e5573e62a3"></a>
### 9992-9b4cdb3/mint-gateway-azure.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-dev4.minio.io:32215
ACCESS_KEY:           minioazure
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 8ee3b76feda1:/mint/log /tmp/mint-logs'

(1/15) Running aws-sdk-go tests ... done in 7 seconds
(2/15) Running aws-sdk-java tests ... done in 3 seconds
(3/15) Running aws-sdk-php tests ... done in 3 minutes and 15 seconds
(4/15) Running aws-sdk-ruby tests ... done in 16 seconds
(5/15) Running awscli tests ... done in 2 minutes and 40 seconds
(6/15) Running healthcheck tests ... done in 0 seconds
(7/15) Running mc tests ... done in 3 minutes and 3 seconds
(8/15) Running minio-dotnet tests ... done in 1 minutes and 34 seconds
(9/15) Running minio-go tests ... done in 5 minutes and 21 seconds
(10/15) Running minio-java tests ... FAILED in 5 minutes and 15 seconds
{
  "name": "minio-java",
  "function": "removeObjects(RemoveObjectsArgs args)",
  "duration": 1229,
  "status": "FAIL",
  "error": "org.simpleframework.xml.core.ValueRequiredException: Unable to satisfy @org.simpleframework.xml.Element(name=\"Key\", type=void.class, data=false, required=true) on field 'name' private java.lang.String io.minio.messages.DeletedObject.name for class io.minio.messages.DeletedObject at line 2 >>> [io.minio.Xml.unmarshal(Xml.java:68), io.minio.MinioClient.deleteObjects(MinioClient.java:7354), io.minio.MinioClient$1$1.populate(MinioClient.java:2945), io.minio.MinioClient$1$1.hasNext(MinioClient.java:2977), FunctionalTest.removeObjects(FunctionalTest.java:1395), FunctionalTest.removeObjects_test1(FunctionalTest.java:1534), FunctionalTest.runTests(FunctionalTest.java:3812), FunctionalTest.main(FunctionalTest.java:4056)]"
}
(10/15) Running minio-js tests ... done in 2 minutes and 35 seconds
(11/15) Running minio-py tests ... done in 9 minutes and 57 seconds
(12/15) Running s3cmd tests ... done in 1 minutes and 20 seconds
(13/15) Running s3select tests ... done in 1 minutes and 5 seconds
(14/15) Running security tests ... done in 0 seconds

Executed 14 out of 15 tests successfully.
```
<a name="1c1f115f-fe47-4548-98b5-38b8b6670a3f"></a>
### 9992-9b4cdb3/mint-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-dev7.minio.io:32441
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 80a9c9162344:/mint/log /tmp/mint-logs'

(1/15) Running aws-sdk-go tests ... done in 2 seconds
(2/15) Running aws-sdk-java tests ... done in 2 seconds
(3/15) Running aws-sdk-php tests ... done in 43 seconds
(4/15) Running aws-sdk-ruby tests ... done in 3 seconds
(5/15) Running awscli tests ... done in 2 minutes and 11 seconds
(6/15) Running healthcheck tests ... done in 0 seconds
(7/15) Running mc tests ... done in 50 seconds
(8/15) Running minio-dotnet tests ... done in 59 seconds
(9/15) Running minio-go tests ... FAILED in 1 minutes and 23 seconds
{
  "args": {
    "bucketName": "minio-go-test-4qxlhoqjeuxm5new",
    "objectName": "5r6czuoralctu0psa1lra5hp2ycw3s",
    "objectPrefix": "",
    "recursive": "true"
  },
  "duration": 5816,
  "error": "The bucket you tried to delete is not empty. You must delete all versions in the bucket.",
  "function": "RemoveObjectsWithOptions(bucketName, objectsCh, opts)",
  "message": "Cleanup failed",
  "name": "minio-go: testRemoveObjectsWithOptions",
  "status": "FAIL"
}
(9/15) Running minio-java tests ... done in 2 minutes and 41 seconds
(10/15) Running minio-js tests ... done in 51 seconds
(11/15) Running minio-py tests ... done in 4 minutes and 32 seconds
(12/15) Running s3cmd tests ... done in 19 seconds
(13/15) Running s3select tests ... done in 6 seconds
(14/15) Running security tests ... done in 0 seconds

Executed 14 out of 15 tests successfully.
```
<a name="3c527d1a-a553-4f9b-90a7-df48e639f9c6"></a>
### 9992-9b4cdb3/mint-large-bucket.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-dev4.minio.io:32180
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 04e2ffe20ed0:/mint/log /tmp/mint-logs'

(1/15) Running aws-sdk-go tests ... done in 9 seconds
(2/15) Running aws-sdk-java tests ... done in 3 seconds
(3/15) Running aws-sdk-php tests ... done in 47 seconds
(4/15) Running aws-sdk-ruby tests ... done in 11 seconds
(5/15) Running awscli tests ... done in 2 minutes and 22 seconds
(6/15) Running healthcheck tests ... done in 0 seconds
(7/15) Running mc tests ... done in 1 minutes and 15 seconds
(8/15) Running minio-dotnet tests ... done in 3 minutes and 0 seconds
(9/15) Running minio-go tests ... FAILED in 2 minutes and 27 seconds
{
  "args": {
    "bucketName": "minio-go-test-63tkewqmxhswpnye",
    "objectName": "g9k5ur3gd1nsiogpmc1wxztvhxd402",
    "objectPrefix": "",
    "recursive": "true"
  },
  "duration": 5429,
  "error": "The bucket you tried to delete is not empty. You must delete all versions in the bucket.",
  "function": "RemoveObjectsWithOptions(bucketName, objectsCh, opts)",
  "message": "Cleanup failed",
  "name": "minio-go: testRemoveObjectsWithOptions",
  "status": "FAIL"
}
(9/15) Running minio-java tests ... done in 4 minutes and 55 seconds
(10/15) Running minio-js tests ... done in 58 seconds
(11/15) Running minio-py tests ... done in 6 minutes and 4 seconds
(12/15) Running s3cmd tests ... done in 25 seconds
(13/15) Running s3select tests ... done in 14 seconds
(14/15) Running security tests ... done in 0 seconds

Executed 14 out of 15 tests successfully.
```
Deleting image on docker hub
Deleting image locally
