### PR TITLE
admin: Add service set creds API

### LINKED ISSUE #3569: [admin] Add an API to change credentials using `mc admin service`
## Expected Behavior
Provide a way to change the server credentials, it shouldn't be allow if environment variable is set. (Just like web-browser)

## Current Behavior
There is no way to change the credentials using `mc admin` 

## Possible Solution
Implement a new API to change credentials and but disallow this if https is not configured on the client or the request is over plain HTTP (to avoid possible security issues)

## Steps to Reproduce (for bugs)
This is a feature.

## Context
Being able to change passwords. 

## Your Environment
Current minio master.

### PR DESCRIPTION
**Pull request by vadmeste**
## Description
Add Set Creds admin API

## Motivation and Context
Fixes #3569 

## How Has This Been Tested?
Manually

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

File: cmd/admin-handlers.go [hunk 1]
```diff
@@ -86,6 +86,61 @@ func (adminAPI adminAPIHandlers) ServiceRestartHandler(w http.ResponseWriter, r
 	sendServiceCmd(globalAdminPeers, serviceRestart)
 }
 
+// Type-safe service query params.
+type serviceQueryKey string
+
+const (
+	serviceAccessKey serviceQueryKey = "accessKey"
```
Comment (harshavardhana) [inline cmd/admin-handlers.go]: We should send access and secretKey as part of the body insteadof query params for security reasons. On a HTTPS connection this becomes more secure just like how browser actually sets the credentials.

File: cmd/api-errors.go [hunk 2]
```diff
@@ -574,6 +575,12 @@ var errorCodeResponse = map[APIErrorCode]APIError{
 		Description:    "Server not initialized, please try again.",
 		HTTPStatusCode: http.StatusServiceUnavailable,
 	},
+	ErrOpNotAcceptable: {
+		Code:           "XMinioOpNotAcceptable",
+		Description:    "Requested operation is not accepted due to unsatisfied conditions.",
```
Comment (harshavardhana) [inline cmd/api-errors.go]:
```
MethodNotAllowed	The specified method is not allowed against this resource.	405 Method Not Allowed	Client
``` 

http://docs.aws.amazon.com/AmazonS3/latest/API/ErrorResponses.html  - is perhaps better here.

File: pkg/madmin/service.go [hunk 3]
```diff
@@ -141,3 +141,28 @@ func (adm *AdminClient) ServiceRestart() error {
...
+	// Execute GET on bucket to list objects.
+	resp, err := adm.executeMethod("POST", reqData)
+
+	defer closeResponse(resp)
+	if err != nil {
+		return err
+	}
+
+	if resp.StatusCode != http.StatusOK {
+		return errors.New("Got HTTP Status: " + resp.Status)
```
Comment (harshavardhana) [inline pkg/madmin/service.go]: Extract the response XML body. For `mc` 'Got HTTP Status' is useless.

File: cmd/admin-handlers.go (hunk 1 above)
Comment (vadmeste) [reply cmd/admin-handlers.go]: > We should send access and secretKey as part of the body insteadof query params for security reasons. On a HTTPS connection this becomes more secure just like how browser actually sets the credentials.

With HTTPS, even query params are encrypted, However, it seems that it is still uncommon and could be leaked in server logs etc.., so will do it.

Comment (harshavardhana) [reply cmd/admin-handlers.go]: But query params are visible to naked eye.

**Comment by vadmeste** [comment]
Comments are addressed, but I did other changes too,

@harshavardhana, @krisis, can you review this PR ?

File: cmd/admin-router.go [hunk 4]
```diff
@@ -36,6 +36,8 @@ func registerAdminRouter(mux *router.Router) {
 
 	// Service restart
 	adminRouter.Methods("POST").Queries("service", "").Headers(minioAdminOpHeader, "restart").HandlerFunc(adminAPI.ServiceRestartHandler)
+	// Service update credentials
+	adminRouter.Methods("POST").Queries("service", "").Headers(minioAdminOpHeader, "setCredentials").HandlerFunc(adminAPI.ServiceCredentialsHandler)
```
Comment (harshavardhana) [inline cmd/admin-router.go]: For http methods and header - to be consistent we can use 'set-credentials'  similar to how 'region' is set as 'us-east-1'

File: cmd/api-errors.go [hunk 5]
```diff
@@ -574,6 +576,12 @@ var errorCodeResponse = map[APIErrorCode]APIError{
 		Description:    "Server not initialized, please try again.",
 		HTTPStatusCode: http.StatusServiceUnavailable,
 	},
+	ErrAdminBadCreds: {
+		Code:           "XMinioBadCreds",
+		Description:    "Credentials are not suitable for use.",
```
Comment (harshavardhana) [inline cmd/api-errors.go]: Propose a more useful new message.

File: docs/admin-api/management-api.md [hunk 6]
```diff
@@ -32,6 +27,12 @@
   - x-minio-operation: status
   - Response: On success 200, return json formatted StorageInfo object.
 
+* SetCredentials
+  - GET /?service
+  - x-minio-operation: setCredentials
```
Comment (harshavardhana) [inline docs/admin-api/management-api.md]: `x-minio-operation: set-credentials`

Comment (harshavardhana) [reply docs/admin-api/management-api.md]: You missed this @vadmeste

Comment (vadmeste) [reply docs/admin-api/management-api.md]: > You missed this @vadmeste

yes thanks. I am also going to add errors description that could be returned by this API.

File: cmd/admin-handlers_test.go [hunk 7]
```diff
@@ -172,20 +187,37 @@ func testServicesCmdHandler(cmd cmdType, t *testing.T) {
 		}
 	}
 
+	if cmd == setCreds {
+		// Check current
```
Comment (krisis) [inline cmd/admin-handlers_test.go]: Could you expand the comment to explain the intent clearly?

File: cmd/api-errors.go [hunk 8]
```diff
@@ -574,6 +576,12 @@ var errorCodeResponse = map[APIErrorCode]APIError{
 		Description:    "Server not initialized, please try again.",
 		HTTPStatusCode: http.StatusServiceUnavailable,
 	},
+	ErrAdminBadCred: {
+		Code:           "XMinioBadCred",
+		Description:    "Credential is mal-formed.",
```
Comment (krisis) [inline cmd/api-errors.go]: s/mal-formed/malformed/
malformed is a non-hyphenated word.

File: cmd/admin-handlers.go [hunk 9]
```diff
@@ -68,6 +70,72 @@ func (adminAPI adminAPIHandlers) ServiceRestartHandler(w http.ResponseWriter, r
...
+	if err != nil {
+		errorIf(err, "Cannot unmarshal credentials request")
+		writeErrorResponse(w, ErrMalformedXML, r.URL)
+		return
+	}
+
+	// Check passed credentials
+	cred, err := getCredential(req.Username, req.Password)
+	if err != nil {
+		writeErrorResponse(w, ErrAdminBadCred, r.URL)
```
Comment (krisis) [inline cmd/admin-handlers.go]: Do we need a new error value ``ErrAdminBadCred``? ``getCredential`` would return one of ``errInvalidAcessKeyLength`` or ``errInvalidSecretKeyLength``. They would be more specific than ``ErrAdminBadCred``, i.e, whether the accesskey is incorrect or the secretkey is incorrect (or both).

Comment (vadmeste) [reply cmd/admin-handlers.go]: > Do we need a new error value ErrAdminBadCred? getCredential would return one of errInvalidAcessKeyLength or errInvalidSecretKeyLength. They would be more specific than ErrAdminBadCred, i.e, whether the accesskey is incorrect or the secretkey is incorrect (or both).

errInvalidAcessKeyLength and errInvalidSecretKeyLength are standard errors, we need an ErrorResponse type which represents the regular S3 xml error like:
```
 27 <?xml version="1.0" encoding="UTF-8"?>
 28 <Error>
 29    <Code>AccessDenied</Code>
 30    <Message>Access Denied</Message>
 31    <BucketName>bucketName</BucketName>
 32    <Key>objectName</Key>
 33    <RequestId>F19772218238A85A</RequestId>
 34    <HostId>GuWkjyviSiGHizehqpmsD1ndz5NClSP19DOT+s2mv7gXGQ8/X1lhbDGiIJEXpGFD</HostId>
 35 </Error>
```

**Comment by vadmeste** [comment]
I addressed your issues @krisis, also I added set credentials example under pkg/madmin/examples/

File: pkg/madmin/examples/service-set-credentials.go [hunk 10]
```diff
@@ -0,0 +1,44 @@
...
+	madmClnt, err := madmin.New("your-minio.example.com:9000", "YOUR-ACCESSKEYID", "YOUR-SECRETACCESSKEY", true)
+	if err != nil {
+		log.Fatalln(err)
+	}
+
+	err = madmClnt.ServiceSetCredentials("YOUR-NEW-ACCESSKEY", "YOUR-NEW-SECRETKEY")
+	if err != nil {
+		log.Fatalln(err)
+	}
+	log.Println("New credentials successfully sent.")
```
Comment (krisis) [inline pkg/madmin/examples/service-set-credentials.go]: nit: "New credentials successfully set" (not sent).

Comment (vadmeste) [reply pkg/madmin/examples/service-set-credentials.go]: Done

**Review by krisis — APPROVED** [review]

File: cmd/admin-handlers.go (hunk 9 above)
Comment (harshavardhana) [reply cmd/admin-handlers.go]: We can construct them to a more palpable behavior and provide two distinct errors one for secret and another for access key rather than one single error "Malformed creds". This provides more context.

**Comment by harshavardhana** [comment]
Can you resolve the conflicts @vadmeste ?

**Comment by vadmeste** [comment]
I increased the timeout of go test here because it seems it is little slow under Windows. Otherwise, all issues are addressed.

**Comment by harshavardhana** [comment]
> I increased the timeout of go test here because it seems it is little slow under Windows. Otherwise, all issues are addressed.

We need to investigate - can you open a bug?

**Review by harshavardhana — APPROVED** [review]

**Comment by vadmeste** [comment]
> We need to investigate - can you open a bug?

I noticed that there is one test which put 1000 small objects and that is taking 2 minutes under Windows. By the way, -race flag is activated. Anyway, as we are writing new tests, execution will take more time and probably this is not a bug. Will open a new issue.

**Comment by harshavardhana** [comment]
> I noticed that there is one test which put 1000 small objects and that is taking 2 minutes under Windows. By the way, -race flag is activated. Anyway, as we are writing new tests, execution will take more time and probably this is not a bug. Will open a new issue

Agreed but we need to investigate further.
