### PR TITLE
Fix: Allow deleting multiple objects anonymously if policy supports it

### LINKED ISSUE #5683: Guest viewing bucket with Read and Write policy can't delete an object
## Expected Behavior

Guests should be able to delete objects from buckets that have the Read and Write policy.

## Current Behavior

When a guest (non-logged-in user) is viewing a bucket that has Read and Write policy, they can't delete an object from the bucket. When they try to delete an object, they receive a message saying "Authentication failed, please check your access credentials"

screen shot 2018-03-21 at 4 27 27 pm

## Possible Solution

The correct permissions for guests might not have been handled properly in the Web.RemoveObject method.

## Steps to Reproduce (for bugs)

1. Log in to the Minio browser
2. Select a bucket
3. In the selected bucket, add a Read and Write policy for prefix '*'
4. Copy the URL of the bucket and log out of the browser
5. Navigate to the previously bucket that was selected on Step 2 by pasting its URL to the address bar
6. Select objects from that bucket
7. Delete the objects

## Context

Not being able to delete objects from a bucket is contradictory to the behavior that is expected from the Read and Write permission

## Your Environment

* Version used (`minio version`): play.minio.io
* Environment name and version (e.g. nginx 1.9.1):
* Server type and version:
* Operating System and version (`uname -a`):
* Link to your project:

### PR DESCRIPTION
**Pull request by kannappanr**
Anonymous multiple objects deletion was not allowed before, even if the policy supported it.

This PR allows both Delete Multiple Objects S3 API and browser API to delete multiple obejcts if the API allows it.

Fixes #5683

## Description

Each object will be enumerated individually and if the policy doesn't allow in the case of S3 API, then access denied error is sent. 

In the case of browser, the browser will not delete any object if any of the object's policy does not allow anonymous deletion

## Motivation and Context
Issue #5683

## Regression
No

## How Has This Been Tested?
As described in issue #5683
and also using the following steps with mc

```
mc mb myminio/test
mc policy public myminio/test
mc cp /etc/issue myminio/test
mc config host add myminio-anon http://127.0.0.1:9000 "" "" --api "s3v4"
mc rm myminio/test/issue
```
Without the change, `mc rm` will fail

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added unit tests to cover my changes.
- [ ] I have added/updated functional tests in [mint](https://github.com/minio/mint). (If yes, add `mint` PR # here: )
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by minio-ops** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-compression-xl.sh | :heavy_check_mark: |
| mint-xl.sh | :heavy_check_mark: |
| mint-compression-dist-xl.sh | :heavy_check_mark: |
| mint-compression-fs.sh | :heavy_check_mark: |
| mint-worm.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-dist-xl.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :x: [more...](#56f66bda-d36d-43f8-993e-e85384814e69) |
<a name="56f66bda-d36d-43f8-993e-e85384814e69"></a>
### 7439-4d25744/mint-large-bucket.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.54:31667
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 08498757289a:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... FAILED in 0 seconds
{
  "alert": "",
  "args": {
    "bucketName": "aws-sdk-go-test-ftbg64tig2ajwg",
    "expiry": 60000000000,
    "objectName": "presignedTest"
  },
  "duration": 358,
  "error": "RequestError: send request failed\ncaused by: Put http://72.28.97.54:31667/aws-sdk-go-test-ftbg64tig2ajwg: dial tcp 72.28.97.54:31667: connect: connection refused",
  "function": "PresignedPut",
  "message": "AWS SDK Go CreateBucket Failed",
  "name": "aws-sdk-go",
  "status": "FAIL"
}

Executed 0 out of 14 tests successfully.
```

**Comment by harshavardhana** [comment]
In S3 deletes are not allowed AFAIK for anonymous users.. @kannappanr any reason we need it?

**Comment by kannappanr** [comment]
@harshavardhana It seems to allow it now.

**Comment by harshavardhana** [comment]
> @harshavardhana It seems to allow it now.

Good to know that's changed now @kannappanr

File: cmd/bucket-handlers.go [hunk 1]
```diff
@@ -326,6 +316,15 @@ func (api objectAPIHandlers) DeleteMultipleObjectsHandler(w http.ResponseWriter,
...
 	for index, object := range deleteObjects.Objects {
+		var s3Error APIErrorCode
+		if s3Error = checkRequestAuthType(ctx, r, policy.DeleteObjectAction, bucket, object.ObjectName); s3Error != ErrNone {
+			// In the event access is denied, a 200 response should still be returned
+			// http://docs.aws.amazon.com/AmazonS3/latest/API/multiobjectdeleteapi.html
+			if s3Error != ErrAccessDenied {
+				writeErrorResponse(ctx, w, errorCodes.ToAPIErr(s3Error), r.URL, guessIsBrowserReq(r))
+				return
+			}
+		}
```
Comment (krishnasrinivas) [inline cmd/bucket-handlers.go]: note that for multi-objects delete, if there were partial success we need to communicate it back to the client appropriately.

Comment (kannappanr) [reply cmd/bucket-handlers.go]: Yes. In that case should we collect all the errors and if we see any error other than `AccessDenied`, return this error, before starting the delete operation?

Comment (krishnasrinivas) [reply cmd/bucket-handlers.go]: i think we don't need to differentiate between access-denied and other errors (apart from object-not-found)
you can check how aws-s3 behaves and we can behave accordingly

Comment (kannappanr) [reply cmd/bucket-handlers.go]: done

**Comment by minio-ops** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-compression-xl.sh | :heavy_check_mark: |
| mint-xl.sh | :heavy_check_mark: |
| mint-compression-dist-xl.sh | :heavy_check_mark: |
| mint-compression-fs.sh | :heavy_check_mark: |
| mint-worm.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :x: [more...](#37b9ece7-eeb7-4c9a-b4df-edd9b8aaeab2) |
| mint-dist-xl.sh | :x: [more...](#fb710ce6-795a-4dad-abea-98ceff38bfb3) |
<a name="37b9ece7-eeb7-4c9a-b4df-edd9b8aaeab2"></a>
### 7439-f500552/mint-large-bucket.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.54:30353
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 8ee7387f1077:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... FAILED in 0 seconds
{
  "alert": "",
  "args": {
    "bucketName": "aws-sdk-go-test-thbyjqmb0en2dv",
    "expiry": 60000000000,
    "objectName": "presignedTest"
  },
  "duration": 269,
  "error": "RequestError: send request failed\ncaused by: Put http://72.28.97.54:30353/aws-sdk-go-test-thbyjqmb0en2dv: dial tcp 72.28.97.54:30353: connect: connection refused",
  "function": "PresignedPut",
  "message": "AWS SDK Go CreateBucket Failed",
  "name": "aws-sdk-go",
  "status": "FAIL"
}

Executed 0 out of 14 tests successfully.
```
<a name="fb710ce6-795a-4dad-abea-98ceff38bfb3"></a>
### 7439-f500552/mint-dist-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.60:30902
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp a7661e4f17a0:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 0 seconds
(2/14) Running aws-sdk-java tests ... done in 21 seconds
(3/14) Running aws-sdk-php tests ... done in 44 seconds
(4/14) Running aws-sdk-ruby tests ... done in 3 seconds
(5/14) Running awscli tests ... done in 35 minutes and 19 seconds
(6/14) Running healthcheck tests ... FAILED in 30 seconds
{
  "alert": "",
  "args": null,
  "duration": 30000,
  "error": "Get http://72.28.97.60:30902/minio/health/live: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)",
  "function": "testLivenessEndpoint",
  "message": "GET request failed",
  "name": "healthcheck",
  "status": "FAIL"
}

Executed 5 out of 14 tests successfully.
```

**Comment by minio-ops** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-compression-xl.sh | :heavy_check_mark: |
| mint-xl.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-compression-dist-xl.sh | :heavy_check_mark: |
| mint-compression-fs.sh | :heavy_check_mark: |
| mint-worm.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-dist-xl.sh | :x: [more...](#307bbfd4-ecde-44d1-8456-4cf8b2560753) |
<a name="307bbfd4-ecde-44d1-8456-4cf8b2560753"></a>
### 7439-9dc93f3/mint-dist-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.56:30130
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 58dea4ac31be:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... FAILED in 0 seconds
{
  "alert": "",
  "args": {
    "bucketName": "aws-sdk-go-test-65xsyalbhq6mj3",
    "expiry": 60000000000,
    "objectName": "presignedTest"
  },
  "duration": 311,
  "error": "RequestError: send request failed\ncaused by: Put http://72.28.97.56:30130/aws-sdk-go-test-65xsyalbhq6mj3: dial tcp 72.28.97.56:30130: connect: connection refused",
  "function": "PresignedPut",
  "message": "AWS SDK Go CreateBucket Failed",
  "name": "aws-sdk-go",
  "status": "FAIL"
}

Executed 0 out of 14 tests successfully.
```

**Comment by minio-ops** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-xl.sh | :heavy_check_mark: |
| mint-compression-dist-xl.sh | :heavy_check_mark: |
| mint-compression-fs.sh | :heavy_check_mark: |
| mint-worm.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-compression-xl.sh | :x: [more...](#4b7f7553-bdb7-4bfa-9242-98a508038f14) |
| mint-large-bucket.sh | :x: [more...](#a77f0e55-238c-45ea-914c-b0c5fd6b1f5d) |
| mint-dist-xl.sh | :x: [more...](#7a78d45e-3cf5-407c-ab92-a57f10fe5cad) |
<a name="a77f0e55-238c-45ea-914c-b0c5fd6b1f5d"></a>
### 7439-b3ef725/mint-large-bucket.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.60:31712
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 12951e67c1f4:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 5 seconds
(2/14) Running aws-sdk-java tests ... done in 1 seconds
(3/14) Running aws-sdk-php tests ... done in 48 seconds
(4/14) Running aws-sdk-ruby tests ... done in 12 seconds
(5/14) Running awscli tests ... done in 18 minutes and 13 seconds
(6/14) Running healthcheck tests ... done in 0 seconds
(7/14) Running mc tests ... FAILED in 1 minutes and 5 seconds
{
  "name": "mc",
  "duration": "30271",
  "function": "test_get_object",
  "status": "FAIL",
  "error": "/mint/run/core/mc/mc --config-dir /tmp/.mc-8775 --quiet --no-color cp myminio/mc-test-bucket-3009/mc-test-object-15272 mc-test-object-15272.downloaded  >>> \nmc: <ERROR> Unable to validate source myminio/mc-test-bucket-3009/mc-test-object-15272"
}

Executed 6 out of 14 tests successfully.
```
<a name="7a78d45e-3cf5-407c-ab92-a57f10fe5cad"></a>
### 7439-b3ef725/mint-dist-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.54:30886
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 86c145d5edff:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 0 seconds
(2/14) Running aws-sdk-java tests ... done in 1 seconds
(3/14) Running aws-sdk-php tests ... done in 44 seconds
(4/14) Running aws-sdk-ruby tests ... done in 4 seconds
(5/14) Running awscli tests ... done in 1 minutes and 51 seconds
(6/14) Running healthcheck tests ... done in 0 seconds
(7/14) Running mc tests ... done in 29 seconds
(8/14) Running minio-dotnet tests ... done in 38 seconds
(9/14) Running minio-go tests ... done in 1 minutes and 9 seconds
(10/14) Running minio-java tests ... done in 2 minutes and 34 seconds
(11/14) Running minio-js tests ... done in 40 seconds
(12/14) Running minio-py tests ... FAILED in 5 minutes and 4 seconds
{
  "name": "minio-py:test_presigned_get_object_expiry_5sec",
  "function": "presigned_get_object(bucket_name, object_name, expires, response_headers, request_date)",
  "args": {
    "bucket_name": "minio-py-test-dbeff9aa-e792-4e14-aa99-e801d844219a",
    "object_name": "59ae46d2-67b6-4105-bebd-be08d747bba8"
  },
  "message": "AccessDenied: message: Access Denied",
  "error": "Traceback (most recent call last):\n  File \"/mint/run/core/minio-py/tests.py\", line 1220, in test_presigned_get_object_expiry_5sec\n    object_name).get_exception()\nminio.error.AccessDenied: AccessDenied: message: Access Denied\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"/mint/run/core/minio-py/tests.py\", line 1885, in main\n    test_presigned_get_object_expiry_5sec(client, log_output)\n  File \"/mint/run/core/minio-py/tests.py\", line 1228, in test_presigned_get_object_expiry_5sec\n    raise Exception(err)\nException: AccessDenied: message: Access Denied\n",
  "duration": 125,
  "status": "FAIL"
}

Executed 11 out of 14 tests successfully.
```
<a name="4b7f7553-bdb7-4bfa-9242-98a508038f14"></a>
### 7439-b3ef725/mint-compression-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.56:30535
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 6a49671b098b:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 0 seconds
(2/14) Running aws-sdk-java tests ... done in 1 seconds
(3/14) Running aws-sdk-php tests ... done in 43 seconds
(4/14) Running aws-sdk-ruby tests ... done in 3 seconds
(5/14) Running awscli tests ... done in 1 minutes and 49 seconds
(6/14) Running healthcheck tests ... done in 0 seconds
(7/14) Running mc tests ... done in 27 seconds
(8/14) Running minio-dotnet tests ... done in 29 seconds
(9/14) Running minio-go tests ... done in 43 seconds
(10/14) Running minio-java tests ... done in 2 minutes and 27 seconds
(11/14) Running minio-js tests ... done in 38 seconds
(12/14) Running minio-py tests ... FAILED in 4 minutes and 23 seconds
{
  "function": "presigned_get_object(bucket_name, object_name, expires, response_headers, request_date)",
  "name": "minio-py:test_presigned_get_object_expiry_5sec",
  "status": "FAIL",
  "error": "Traceback (most recent call last):\n  File \"/mint/run/core/minio-py/tests.py\", line 1220, in test_presigned_get_object_expiry_5sec\n    object_name).get_exception()\nminio.error.AccessDenied: AccessDenied: message: Access Denied\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"/mint/run/core/minio-py/tests.py\", line 1885, in main\n    test_presigned_get_object_expiry_5sec(client, log_output)\n  File \"/mint/run/core/minio-py/tests.py\", line 1228, in test_presigned_get_object_expiry_5sec\n    raise Exception(err)\nException: AccessDenied: message: Access Denied\n",
  "message": "AccessDenied: message: Access Denied",
  "duration": 88,
  "args": {
    "object_name": "32a1e572-3342-4140-a266-48e2f1f4a1af",
    "bucket_name": "minio-py-test-213d74bb-2ac5-45fc-995d-f5195899f324"
  }
}

Executed 11 out of 14 tests successfully.
```

**Review by harshavardhana — APPROVED** [review]
LGTM & tested

**Comment by harshavardhana** [comment]
ping @krishnasrinivas

**Review by krishnasrinivas — APPROVED** [review]
