### PR TITLE
xl: Abort multipart upload should honor quorum properly.

### LINKED ISSUE #3665: [distributed]: Abort Multipart fails when one of the node is permanently is down.
Abort Multipart fails when one of the node is permanently is down.
## Expected Behavior

- Abort Multipart to work when one of the node is down.
## Current Behavior

- Failing when one of the node is permanently down.

```
--- FAIL: TestObjectMultipartAbort (0.48s)
        server_test.go:3807: Expected response status 204, got 500.

```
## Possible Solution

Not sure.
## Steps to Reproduce (for bugs)

1. Run Minio distributed on 4 nodes.
2. Stop one of the node.
3. Run [distributed functional test](https://github.com/minio/perftest/tree/master/distributed-functional-test)

## Context

Testing with one node down.
## Your Environment

* Version used: Latest master at cb48517a78f34fbc3a6cfcf625e813abd9f9ee70 .
* Operating System and version: Ubuntu 16.04

### PR DESCRIPTION
**Pull request by harshavardhana**
## Description
Current implementation didn't honor quorum properly and didn't
handle the errors generated properly. This patch addresses that
and also moves common code `cleanupMultipartUploads` into xl
specific private function.

## Motivation and Context
Fixes #3665

## How Has This Been Tested?
Manually taking down the 4th server.

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

File: cmd/xl-v1-multipart.go [hunk 1]
```diff
@@ -1077,13 +1077,51 @@ func (xl xlObjects) CompleteMultipartUpload(bucket string, object string, upload
...
+}
+
 // abortMultipartUpload - wrapper for purging an ongoing multipart
 // transaction, deletes uploadID entry from `uploads.json` and purges
 // the directory at '.minio.sys/multipart/bucket/object/uploadID' holding
 // all the upload parts.
 func (xl xlObjects) abortMultipartUpload(bucket, object, uploadID string) (err error) {
 	// Cleanup all uploaded parts.
-	if err = cleanupUploadedParts(bucket, object, uploadID, xl.storageDisks...); err != nil {
+	if err = xl.cleanupUploadedParts(bucket, object, uploadID, xl.storageDisks); err != nil {
```
Comment (krisis) [inline cmd/xl-v1-multipart.go]: ``cleanUploadedParts`` is a method of ``xlObjects`` and has access to ``storageDisks``. We shouldn't  be passing it as a parameter.

File: cmd/xl-v1-multipart.go [hunk 2]
```diff
@@ -1077,13 +1077,51 @@ func (xl xlObjects) CompleteMultipartUpload(bucket string, object string, upload
...
+		if disk == nil {
+			errs[index] = traceError(errDiskNotFound)
+			continue
+		}
+		wg.Add(1)
+		// Cleanup each uploadID in a routine.
+		go func(index int, disk StorageAPI) {
+			defer wg.Done()
+			err := cleanupDir(disk, minioMetaMultipartBucket, uploadIDPath)
+			if err != nil && errorCause(err) != errVolumeNotFound {
```
Comment (krisis) [inline cmd/xl-v1-multipart.go]: Why is ``errVolumeNotFound`` treated differently?

File: cmd/xl-v1-multipart.go [hunk 3]
```diff
@@ -1077,13 +1077,51 @@ func (xl xlObjects) CompleteMultipartUpload(bucket string, object string, upload
...
+				errs[index] = err
+			}
+		}(index, disk)
+	}
+
+	// Wait for all the cleanups to finish.
+	wg.Wait()
+
+	// Do we have write quorum?
+	if !isDiskQuorum(errs, xl.writeQuorum) {
```
Comment (krisis) [inline cmd/xl-v1-multipart.go]: ``isDiskQuorum`` looks suspect. It counts "non-ignored" errors and checks if the total is greater than the supplied quorum value. This is the opposite of what we want. We wish to know if there were quorum or more success (i.e, ``err == nil``) to deem the operation a success. This is not related to this patch, but this change relies on it.

**Review by krisis — CHANGES_REQUESTED** [review]

File: cmd/xl-v1-multipart.go (hunk 1 above)
Comment (harshavardhana) [reply cmd/xl-v1-multipart.go]: oh yes.. now we don't need.

File: cmd/xl-v1-multipart.go (hunk 3 above)
Comment (harshavardhana) [reply cmd/xl-v1-multipart.go]: removed..

File: cmd/xl-v1-multipart.go (hunk 2 above)
Comment (harshavardhana) [reply cmd/xl-v1-multipart.go]: It is because `minioMetaMultipartBucket` might not existing but we don't need to throw an error for that and safely ignore it..  But it was an early requirement since sometime we don't delete `minioMetaMultipartBucket` ever. So this case won't happen. 

This can be safely removed.

File: cmd/xl-v1-multipart.go [hunk 4]
```diff
@@ -902,9 +895,9 @@ func (xl xlObjects) CompleteMultipartUpload(bucket string, object string, upload
 
 	// Read metadata associated with the object from all disks.
 	partsMetadata, errs := readAllXLMetadata(xl.storageDisks, minioMetaMultipartBucket, uploadIDPath)
-	// Do we have writeQuorum?.
-	if !isDiskQuorum(errs, xl.writeQuorum) {
-		return ObjectInfo{}, toObjectErr(traceError(errXLWriteQuorum), bucket, object)
+	reducedErr := reduceWriteQuorumErrs(errs, objectOpIgnoredErrs, xl.writeQuorum)
+	if errorCause(reducedErr) == errXLWriteQuorum {
+		return ObjectInfo{}, toObjectErr(traceError(reducedErr), bucket, object)
```
Comment (krisis) [inline cmd/xl-v1-multipart.go]: ``traceError`` is redundant for ``reducedErr``.

**Review by krisis — COMMENTED** [review]
Could you add a test case for toObjectError(...) to ensure that the following property is maintained,
```go
toObjectErr(nil) == nil
```

File: cmd/xl-v1-multipart.go (hunk 4 above)
Comment (harshavardhana) [reply cmd/xl-v1-multipart.go]: done

**Comment by harshavardhana** [comment]
> toObjectErr(nil) == nil

Done add for toAPIErrCode and toStorageErr as well.
