### PR TITLE
Workaround for Windows Docker Engine 19.03.8

### LINKED ISSUE #9726: Server startup failed with 'Unable to initialize sub-systems: Unable to migrate all config at .minio.sys/config/
Can't start minio container with volumes 

## Expected Behavior
Run minio container with mounted directory

docker-compose.yml consist with:

```
version: "3"
services:

  minio:
    image: minio/minio
    container_name: minio
    hostname: minio
    volumes:
      - ./minio/s3:/data
    ports:
      - 9000:9000
    command: 'server /data'
    environment:
      MINIO_ACCESS_KEY: minio
      MINIO_SECRET_KEY: minio123
```
 

## Current Behavior
```
Creating minio ... done
Attaching to minio
minio    | Attempting encryption of all config, IAM users and policies on MinIO backend
minio    | 
minio    | API: SYSTEM()
minio    | Time: 16:41:52 UTC 05/28/2020
minio    | DeploymentID: fe4965f4-6869-4143-93a3-8a6212da10b1
minio    | Error: Unexpected error, please report this issue at https://github.com/minio/minio/issues
minio    |        8: github.com/minio/minio@/cmd/fs-v1-helpers.go:337:cmd.fsCreateFile()
minio    |        7: github.com/minio/minio@/cmd/fs-v1.go:996:cmd.(*FSObjects).putObject()
minio    |        6: github.com/minio/minio@/cmd/fs-v1.go:910:cmd.(*FSObjects).PutObject()
minio    |        5: github.com/minio/minio@/cmd/config-common.go:66:cmd.saveConfig()
minio    |        4: github.com/minio/minio@/cmd/config-encrypted.go:237:cmd.migrateConfigPrefixToEncrypted()
minio    |        3: github.com/minio/minio@/cmd/config-encrypted.go:63:cmd.handleEncryptedConfigBackend()
minio    |        2: github.com/minio/minio@/cmd/server-main.go:230:cmd.initSafeMode()
minio    |        1: github.com/minio/minio@/cmd/server-main.go:524:cmd.serverMain()
minio    | Server startup failed with 'Unable to initialize sub-systems: Unable to migrate all config at .minio.sys/config/: Unexpected error, please report this issue at https://githu
b.com/minio/minio/issues'
minio    | Server switching to safe mode
minio    | Please use 'mc admin config' commands fix this issue
minio    | Endpoint:  http://172.21.0.2:9000  http://127.0.0.1:9000

```

## Steps to Reproduce (for bugs)
1. docker-compose up --build

### PR DESCRIPTION
**Pull request by klauspost**
## Description

Add workaround for issue preventing servers from starting on Windows Docker Engine 19.03.8

Fixes #9726

## How to test this PR?

On Windows:

```
SET GOOS=linux
SET GOARCH=amd64
go build .

docker build -t minio -f Dockerfile.dev .
docker run -p 9000:9000 --name minio1 -e "MINIO_ACCESS_KEY=minio" -e "MINIO_SECRET_KEY=minio123" -v d:\data\docker:/data --rm -it minio server /data
```

## Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)

### CODE REVIEW

File: cmd/fs-v1-helpers.go [hunk 1]
```diff
@@ -363,11 +363,15 @@ func fsCreateFile(ctx context.Context, filePath string, reader io.Reader, buf []
 // wrapper to handle various operating system specific errors.
 func fsFAllocate(fd int, offset int64, len int64) (err error) {
 	e := Fallocate(fd, offset, len)
-	// Ignore errors when Fallocate is not supported in the current system
-	if e != nil && !isSysErrNoSys(e) && !isSysErrOpNotSupported(e) {
+	if e != nil {
 		switch {
 		case isSysErrNoSpace(e):
 			err = errDiskFull
+		case isSysErrNoSys(e) && !isSysErrOpNotSupported(e):
```
Comment (vadmeste) [inline cmd/fs-v1-helpers.go]: I think you mean `isSysErrNoSys(e) || isSysErrOpNotSupported(e)` here

LGTM otherwise

**Review by vadmeste — CHANGES_REQUESTED** [review]

File: cmd/fs-v1-helpers.go (hunk 1 above)
Comment (klauspost) [reply cmd/fs-v1-helpers.go]: @vadmeste Too much copy&paste. Fixed!

**Review by vadmeste — APPROVED** [review]
LGTM

**Review by harshavardhana — APPROVED** [review]

**Comment by minio-trusted** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-xl.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-dist-xl.sh | :heavy_check_mark: |
| mint-gateway-s3.sh | :heavy_check_mark: |
| mint-gateway-azure.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :x: [more...](#eccc8c57-2441-4829-ad30-246d5a2d6803) |
<a name="eccc8c57-2441-4829-ad30-246d5a2d6803"></a>
### 9735-ae8f5d9/mint-gateway-nas.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-dev3.minio.io:30450
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 08488f118041:/mint/log /tmp/mint-logs'

(1/15) Running aws-sdk-go tests ... done in 0 seconds
(2/15) Running aws-sdk-java tests ... done in 2 seconds
(3/15) Running aws-sdk-php tests ... done in 1 seconds
(4/15) Running aws-sdk-ruby tests ... done in 2 seconds
(5/15) Running awscli tests ... done in 2 minutes and 5 seconds
(6/15) Running healthcheck tests ... done in 0 seconds
(7/15) Running mc tests ... done in 27 seconds
(8/15) Running minio-dotnet tests ... done in 28 seconds
(9/15) Running minio-go tests ... done in 37 seconds
(10/15) Running minio-java tests ... done in 32 seconds
(11/15) Running minio-js tests ... FAILED in 13 seconds
{
  "name": "minio-js",
  "function": "getBucketPolicy(bucketName, cb)",
  "args": "bucketName:minio-js-test-376027a4-0193-4be2-a428-815f213bc32d",
  "duration": 7,
  "status": "FAIL",
  "error": "S3Error: The bucket policy does not exist at Object.parseError (node_modules/minio/dist/main/xml-parsers.js:86:11) at /mint/run/core/minio-js/node_modules/minio/dist/main/transformers.js:156:22 at DestroyableTransform._flush (node_modules/minio/dist/main/transformers.js:80:10) at DestroyableTransform.prefinish (node_modules/readable-stream/lib/_stream_transform.js:129:10) at prefinish (node_modules/readable-stream/lib/_stream_writable.js:611:14) at finishMaybe (node_modules/readable-stream/lib/_stream_writable.js:620:5) at endWritable (node_modules/readable-stream/lib/_stream_writable.js:643:3) at DestroyableTransform.Writable.end (node_modules/readable-stream/lib/_stream_writable.js:571:22) at IncomingMessage.onend (_stream_readable.js:673:10) at endReadableNT (_stream_readable.js:1201:12) at processTicksAndRejections (internal/process/task_queues.js:84:21)"
}
(11/15) Running minio-py tests ... done in 56 seconds
(12/15) Running s3cmd tests ... done in 16 seconds
(13/15) Running s3select tests ... done in 2 seconds
(14/15) Running security tests ... done in 0 seconds

Executed 14 out of 15 tests successfully.
```
Deleting image on docker hub
Deleting image locally

**Comment by minio-trusted** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-xl.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-dist-xl.sh | :heavy_check_mark: |
| mint-gateway-azure.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-gateway-s3.sh | :x: [more...](#304ebd8f-b245-4946-b7a8-6e9bb14387f5) |
<a name="304ebd8f-b245-4946-b7a8-6e9bb14387f5"></a>
### 9735-219c983/mint-gateway-s3.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-dev6.minio.io:30159
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp c877bcb6cd59:/mint/log /tmp/mint-logs'

(1/15) Running aws-sdk-go tests ... done in 0 seconds
(2/15) Running aws-sdk-java tests ... done in 2 seconds
(3/15) Running aws-sdk-php tests ... done in 1 seconds
(4/15) Running aws-sdk-ruby tests ... done in 2 seconds
(5/15) Running awscli tests ... done in 2 minutes and 5 seconds
(6/15) Running healthcheck tests ... done in 1 seconds
(7/15) Running mc tests ... done in 22 seconds
(8/15) Running minio-dotnet tests ... done in 28 seconds
(9/15) Running minio-go tests ... done in 39 seconds
(10/15) Running minio-java tests ... done in 27 seconds
(11/15) Running minio-js tests ... FAILED in 15 seconds
{
  "name": "minio-js",
  "function": "\"after all\" hook in \"functional tests\"",
  "duration": 7,
  "status": "FAIL",
  "error": "S3Error: The bucket you tried to delete is not empty at Object.parseError (node_modules/minio/dist/main/xml-parsers.js:86:11) at /mint/run/core/minio-js/node_modules/minio/dist/main/transformers.js:156:22 at DestroyableTransform._flush (node_modules/minio/dist/main/transformers.js:80:10) at DestroyableTransform.prefinish (node_modules/readable-stream/lib/_stream_transform.js:129:10) at prefinish (node_modules/readable-stream/lib/_stream_writable.js:611:14) at finishMaybe (node_modules/readable-stream/lib/_stream_writable.js:620:5) at endWritable (node_modules/readable-stream/lib/_stream_writable.js:643:3) at DestroyableTransform.Writable.end (node_modules/readable-stream/lib/_stream_writable.js:571:22) at IncomingMessage.onend (_stream_readable.js:673:10) at endReadableNT (_stream_readable.js:1201:12) at processTicksAndRejections (internal/process/task_queues.js:84:21)"
}
(11/15) Running minio-py tests ... done in 1 minutes and 6 seconds
(12/15) Running s3cmd tests ... done in 1 minutes and 1 seconds
(13/15) Running s3select tests ... done in 2 seconds
(14/15) Running security tests ... done in 0 seconds

Executed 14 out of 15 tests successfully.
```
Deleting image on docker hub
Deleting image locally

**Comment by minio-trusted** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-xl.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-dist-xl.sh | :heavy_check_mark: |
| mint-gateway-s3.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :x: [more...](#82c22714-a3ad-46a8-acc5-795420d9da3f) |
| mint-gateway-azure.sh | :x: [more...](#cb58afb4-40e8-483f-8a60-fb96bcef61d3) |
<a name="cb58afb4-40e8-483f-8a60-fb96bcef61d3"></a>
### 9735-608ce70/mint-gateway-azure.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-dev6.minio.io:31683
ACCESS_KEY:           minioazure
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 48454acdefea:/mint/log /tmp/mint-logs'

(1/15) Running aws-sdk-go tests ... done in 7 seconds
(2/15) Running aws-sdk-java tests ... done in 1 seconds
(3/15) Running aws-sdk-php tests ... done in 21 seconds
(4/15) Running aws-sdk-ruby tests ... done in 16 seconds
(5/15) Running awscli tests ... done in 4 minutes and 41 seconds
(6/15) Running healthcheck tests ... done in 1 seconds
(7/15) Running mc tests ... done in 2 minutes and 55 seconds
(8/15) Running minio-dotnet tests ... done in 1 minutes and 21 seconds
(9/15) Running minio-go tests ... done in 3 minutes and 56 seconds
(10/15) Running minio-java tests ... done in 25 minutes and 36 seconds
(11/15) Running minio-js tests ... FAILED in 42 seconds
{
  "name": "minio-js",
  "function": "makeBucket(bucketName, region)",
  "args": "bucketName:minio-js-test-71d6145b-37d8-4b5a-a55c-85282ffdb948-region, region:us-east-1",
  "duration": 40219,
  "status": "FAIL",
  "error": "S3Error: -> github.com/Azure/azure-storage-blob-go/azblob.newStorageError, github.com/Azure/azure-storage-blob-go@v0.8.0/azblob/zc_storage_error.go:42 ===== RESPONSE ERROR (ServiceCode=ContainerBeingDeleted) ===== Description=The specified container is being deleted. Try operation later. RequestId:9cdd46ec-801e-00c8-7bcc-357cd9000000 Time:2020-05-29T15:21:33.4254894Z, Details: Code: ContainerBeingDeleted PUT https://minioazure.blob.core.windows.net/minio-js-test-71d6145b-37d8-4b5a-a55c-85282ffdb948-region?restype=container&timeout=1501 Authorization: REDACTED User-Agent: [APN/1.0 MinIO/1.0 MinIO/DEVELOPMENT.GOGET] X-Ms-Client-Request-Id: [14cfb956-ee1e-46d6-4bd6-e57f812b001a] X-Ms-Date: [Fri, 29 May 2020 15:21:33 GMT] X-Ms-Version: [2018-11-09] -------------------------------------------------------------------------------- RESPONSE Status: 409 The specified container is being deleted. Try operation later. Content-Length: [252] Content-Type: [application/xml] Date: [Fri, 29 May 2020 15:21:32 GMT] Server: [Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0] X-Ms-Error-Code: [ContainerBeingDeleted] X-Ms-Request-Id: [9cdd46ec-801e-00c8-7bcc-357cd9000000] X-Ms-Version: [2018-11-09] at Object.parseError (node_modules/minio/dist/main/xml-parsers.js:86:11) at /mint/run/core/minio-js/node_modules/minio/dist/main/transformers.js:156:22 at DestroyableTransform._flush (node_modules/minio/dist/main/transformers.js:80:10) at DestroyableTransform.prefinish (node_modules/readable-stream/lib/_stream_transform.js:129:10) at prefinish (node_modules/readable-stream/lib/_stream_writable.js:611:14) at finishMaybe (node_modules/readable-stream/lib/_stream_writable.js:620:5) at endWritable (node_modules/readable-stream/lib/_stream_writable.js:643:3) at DestroyableTransform.Writable.end (node_modules/readable-stream/lib/_stream_writable.js:571:22) at IncomingMessage.onend (_stream_readable.js:673:10) at endReadableNT (_stream_readable.js:1201:12) at processTicksAndRejections (internal/process/task_queues.js:84:21)"
}
(11/15) Running minio-py tests ... done in 9 minutes and 38 seconds
(12/15) Running s3cmd tests ... done in 1 minutes and 31 seconds
(13/15) Running s3select tests ... done in 1 minutes and 0 seconds
(14/15) Running security tests ... done in 0 seconds

Executed 14 out of 15 tests successfully.
```
<a name="82c22714-a3ad-46a8-acc5-795420d9da3f"></a>
### 9735-608ce70/mint-large-bucket.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-dev4.minio.io:31094
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 158a89124c5f:/mint/log /tmp/mint-logs'

(1/15) Running aws-sdk-go tests ... FAILED in 3 seconds
{
  "alert": "",
  "args": {
    "bucketName": "aws-sdk-go-test-eebidxdeidwefx",
    "objectName": "qajvvry5510j1mas3ktmkhh5a5scmk"
  },
  "duration": 750,
  "error": "RequestError: send request failed\ncaused by: Put http://minio-dev4.minio.io:31094/aws-sdk-go-test-eebidxdeidwefx/qajvvry5510j1mas3ktmkhh5a5scmk?tagging=: EOF",
  "function": "testObjectTagging",
  "message": "AWS SDK Go PUTObjectTagging expected to success but got RequestError",
  "name": "aws-sdk-go",
  "status": "FAIL"
}
(1/15) Running aws-sdk-java tests ... done in 2 seconds
(2/15) Running aws-sdk-php tests ... done in 45 seconds
(3/15) Running aws-sdk-ruby tests ... done in 7 seconds
(4/15) Running awscli tests ... FAILED in 46 seconds
{
  "name": "awscli",
  "duration": 9736,
  "function": "aws --endpoint-url http://minio-dev4.minio.io:31094 s3api copy-object --bucket awscli-mint-test-bucket-26494 --storage-class REDUCED_REDUNDANCY --key datafile-1-kB-copy --copy-source awscli-mint-test-bucket-26494/datafile-1-kB\n",
  "status": "FAIL",
  "error": "An error occurred (SlowDown) when calling the CopyObject operation (reached max retries: 4): Please reduce your request"
}
(4/15) Running healthcheck tests ... done in 0 seconds
(5/15) Running mc tests ... FAILED in 1 minutes and 24 seconds
{
  "name": "mc",
  "duration": "81122",
  "function": "test_put_object_with_storage_class",
  "status": "FAIL",
  "error": "/mint/run/core/mc/mc --config-dir /tmp/.mc-19401 --quiet --no-color cp --storage-class REDUCED_REDUNDANCY /mint/data/datafile-1-MB myminio/mc-test-bucket-11114/mc-test-object-27164  >>> \n`/mint/data/datafile-1-MB` -> `myminio/mc-test-bucket-11114/mc-test-object-27164`\nmc: <ERROR> Failed to copy `/mint/data/datafile-1-MB`. Please reduce your request\nTotal: 0 B, Transferred: 10.00 MiB, Speed: 126.55 KiB/s"
}
(5/15) Running minio-dotnet tests ... done in 1 minutes and 24 seconds
(6/15) Running minio-go tests ... FAILED in 3 minutes and 22 seconds
{
  "args": {},
  "duration": 106042,
  "error": "Please reduce your request",
  "function": "testStorageClassMetadataPutObject()",
  "message": "PutObject failed",
  "name": "minio-go: testStorageClassMetadataPutObject",
  "status": "FAIL"
}
(6/15) Running minio-java tests ... FAILED in 9 seconds
{
  "name": "minio-java",
  "function": "putObject(String bucketName, String objectName, InputStream stream, PutObjectOptions options)",
  "args": "X-Amz-Storage-Class: REDUCED_REDUNDANCY",
  "duration": 59,
  "status": "FAIL",
  "error": "error occurred\nErrorResponse(code = SlowDown, message = Please reduce your request, bucketName = minio-java-test-2kif8su, objectName = minio-java-test-3hle4lo, resource = /minio-java-test-2kif8su/minio-java-test-3hle4lo, requestId = 1613873AC24F81FB, hostId = ac540cbd-bc4f-4e25-8b4c-a13f352ab847)\nrequest={method=POST, url=http://minio-dev4.minio.io:31094/minio-java-test-2kif8su/minio-java-test-3hle4lo?uploads=, headers=X-Amz-Storage-Class: REDUCED_REDUNDANCY\nContent-Type: application/octet-stream\nHost: minio-dev4.minio.io:31094\nAccept-Encoding: identity\nUser-Agent: MinIO (amd64; amd64) minio-java/dev\nContent-MD5: 1B2M2Y8AsgTpgAmY7PhCfg==\nx-amz-content-sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855\nx-amz-date: 20200529T144939Z\nAuthorization: AWS4-HMAC-SHA256 Credential=*REDACTED*/20200529/us-east-1/s3/aws4_request, SignedHeaders=accept-encoding;content-md5;host;x-amz-content-sha256;x-amz-date;x-amz-storage-class, Signature=*REDACTED*\n}\nresponse={code=503, headers=Accept-Ranges: bytes\nContent-Length: 363\nContent-Security-Policy: block-all-mixed-content\nContent-Type: application/xml\nRetry-After: 120\nServer: MinIO/DEVELOPMENT.GOGET\nVary: Origin\nX-Amz-Request-Id: 1613873AC24F81FB\nX-Xss-Protection: 1; mode=block\nDate: Fri, 29 May 2020 14:49:39 GMT\n}\n >>> [io.minio.MinioClient.execute(MinioClient.java:1211), io.minio.MinioClient.execute(MinioClient.java:1236), io.minio.MinioClient.executePost(MinioClient.java:1388), io.minio.MinioClient.createMultipartUpload(MinioClient.java:5092), io.minio.MinioClient.putObject(MinioClient.java:3708), io.minio.MinioClient.putObject(MinioClient.java:3870), FunctionalTest.putObject_test9(FunctionalTest.java:697), FunctionalTest.runTests(FunctionalTest.java:4027), FunctionalTest.main(FunctionalTest.java:4192)]"
}
(6/15) Running minio-js tests ... FAILED in 20 seconds
{
  "name": "minio-js",
  "function": "fPutObject(bucketName, objectName, filePath, metaData)",
  "args": "bucketName:minio-js-test-9bfbe3f4-1b74-4099-934d-6977d6876264, objectName:datafile-65-MB, filePath:/tmp/datafile-65-MB",
  "duration": 8,
  "status": "FAIL",
  "error": "S3Error: Please reduce your request at Object.parseError (node_modules/minio/dist/main/xml-parsers.js:86:11) at /mint/run/core/minio-js/node_modules/minio/dist/main/transformers.js:156:22 at DestroyableTransform._flush (node_modules/minio/dist/main/transformers.js:80:10) at DestroyableTransform.prefinish (node_modules/readable-stream/lib/_stream_transform.js:129:10) at prefinish (node_modules/readable-stream/lib/_stream_writable.js:611:14) at finishMaybe (node_modules/readable-stream/lib/_stream_writable.js:620:5) at endWritable (node_modules/readable-stream/lib/_stream_writable.js:643:3) at DestroyableTransform.Writable.end (node_modules/readable-stream/lib/_stream_writable.js:571:22) at IncomingMessage.onend (_stream_readable.js:673:10) at endReadableNT (_stream_readable.js:1201:12) at processTicksAndRejections (internal/process/task_queues.js:84:21)"
}
(6/15) Running minio-py tests ... done in 4 minutes and 46 seconds
(7/15) Running s3cmd tests ... done in 23 seconds
(8/15) Running s3select tests ... done in 13 seconds
(9/15) Running security tests ... done in 0 seconds

Executed 9 out of 15 tests successfully.
```
Deleting image on docker hub
Deleting image locally
