### PR TITLE
s3: Fix early listing stopping when ILM is enabled (#472)

### LINKED ISSUE #20969: Bucket listings unreliable during ILM process
## Expected Behavior
Listing buckets while automatic bucket cleaning occurs should return all results (with the obvious exception of any items which are removed by cleaning.)

## Current Behavior

I started a process which lists a few of our buckets every few minutes, and let it run. The excerpted result follows:

{"level":"info","bucket":"bucket1","seconds":6.036593013,"count":199279,"caller":"/app/bucket1/cmd/bucketlister/main.go:146","message":"listed"}
{"level":"info","bucket":"bucket2","seconds":0.065199107,"count":1436,"caller":"/app/bucket1/cmd/bucketlister/main.go:146","message":"listed"}
{"level":"info","bucket":"bucket3","seconds":0.111483661,"count":3558,"caller":"/app/bucket1/cmd/bucketlister/main.go:146","message":"listed"}
{"level":"info","bucket":"bucket1","seconds":6.781826241,"count":199332,"caller":"/app/bucket1/cmd/bucketlister/main.go:146","message":"listed"}
{"level":"info","bucket":"bucket2","seconds":0.074197515,"count":1436,"caller":"/app/bucket1/cmd/bucketlister/main.go:146","message":"listed"}
{"level":"info","bucket":"bucket3","seconds":0.129905379,"count":3558,"caller":"/app/bucket1/cmd/bucketlister/main.go:146","message":"listed"}

[0Z occurs, bucket cleaning begins]

{"level":"info","bucket":"bucket1","seconds":0.09604941,"count":811,"caller":"/app/bucket1/cmd/bucketlister/main.go:146","message":"listed"}
{"level":"info","bucket":"bucket2","seconds":0.054896898,"count":742,"caller":"/app/bucket1/cmd/bucketlister/main.go:146","message":"listed"}
{"level":"info","bucket":"bucket3","seconds":0.051438298,"count":449,"caller":"/app/bucket1/cmd/bucketlister/main.go:146","message":"listed"}

...

[bucket cleaning finishes]

{"level":"info","bucket":"bucket1","seconds":7.445846371,"count":196802,"caller":"/app/bucket1/cmd/bucketlister/main.go:146","message":"listed"}
{"level":"info","bucket":"bucket2","seconds":0.046519716,"count":1112,"caller":"/app/bucket1/cmd/bucketlister/main.go:146","message":"listed"}
{"level":"info","bucket":"bucket3","seconds":0.094733125,"count":2947,"caller":"/app/bucket1/cmd/bucketlister/main.go:146","message":"listed"}

## Possible Solution

Not sure. However, the behavior is similar to a previous bug we encountered:

https://github.com/minio/minio/issues/19257

## Steps to Reproduce (for bugs)

1. Create a Minio bucket with an automatic expiration policy.
2. Fill the bucket sufficiently to ensure that cleaning takes a non-negligible amount of time.
3. Repeatedly list the contents of the bucket.
4. Once the cleaning process begins, the listings will be incomplete until the cleaning is complete.

## Context

This unreliability during the bucket cleaning period is problematic.

## Regression

This may be a regression. See issue noted in _Possible Solution_, reproduced here:
https://github.com/minio/minio/issues/19257

## Your Environment

minio version RELEASE.2025-01-20T14-49-07Z (commit-id=827004cd6d3da8f49a5320c94ae74ae128156ed6)

Linux xxx.xxx.com 6.1.0-30-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.1.124-1 (2025-01-12) x86_64 GNU/Linux

### PR DESCRIPTION
**Pull request by vadmeste**
## Community Contribution License
All community contributions in this pull request are licensed to the project maintainers
under the terms of the [Apache 2 license](https://www.apache.org/licenses/LICENSE-2.0). 
By creating this pull request I represent that I have the right to license the 
contributions to the project maintainers under the Apache 2 license.

## Description
S3 listing call is usually sent with a 'max-keys' parameter. This 'max-keys' will also be passed to WalkDir() call. However, when ILM is enabled in a bucket and some objects are skipped, the listing can return IsTruncated set to false even if there are more entries in the drives.

The reason is that drives stop feeding the listing code because it has max-keys parameter and the listing code thinks listing is finished because it is being fed anymore.

Ask the drives to not stop listing and relies on the context cancellation to stop listing in the drives as fast as possible.

## Motivation and Context
Fix https://github.com/minio/minio/issues/20969

## Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Optimization (provides speedup with no functional changes)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [ ] Fixes a regression (If yes, please add `commit-id` or `PR #` here)
- [x] Unit tests added/updated
- [ ] Internal documentation updated
- [ ] Create a documentation update request [here](https://github.com/minio/docs/issues/new?label=doc-change,title=Doc+Updated+Needed+For+PR+github.com%2fminio%2fminio%2fpull%2fNNNNN)

### CODE REVIEW

File: cmd/metacache-walk.go [hunk 1]
```diff
@@ -197,6 +200,9 @@ func (s *xlStorage) WalkDir(ctx context.Context, opts WalkDirOptions, wr io.Writ
 		// Avoid a bunch of cleanup when joining.
 		current = strings.Trim(current, SlashSeparator)
 		for i, entry := range entries {
+			if contextCanceled(ctx) {
```
Comment (klauspost) [inline cmd/metacache-walk.go:203]: This is checked on line 230. Remove that one if you want to keep this.

File: cmd/metacache-server-pool.go [hunk 2]
```diff
@@ -422,6 +426,9 @@ func (z *erasureServerPools) listAndSave(ctx context.Context, o *listPathOptions
 	go func() {
 		var returned bool
 		for entry := range inCh {
+			if o.shouldSkip(ctx, entry) {
+				continue
+			}
```
Comment (klauspost) [inline cmd/metacache-server-pool.go:431]: Is this needed here? It is a very expensive check, and I would rather postpone that to the actual ListObject call than having to do it on the merged stream.

Comment (harshavardhana) [reply cmd/metacache-server-pool.go:431]: How expensive?

**Review by harshavardhana — CHANGES_REQUESTED** [review]

File: cmd/metacache-server-pool.go (hunk 2 above)
Comment (klauspost) [reply cmd/metacache-server-pool.go:431]: It de-serializes and converts to ObjectInfo, or if versioned unpacks all versions... https://github.com/miniohq/eos/blob/a7f51987009ebc9cba04a00467457f19e0a07520/cmd/metacache-server-pool.go#L407

Both are very malloc-intensive.

Comment (vadmeste) [reply cmd/metacache-server-pool.go:431]: @klauspost if we move it, it will still be executed anyway,  would that make a difference if it is done here or in merge() later ?

Comment (klauspost) [reply cmd/metacache-server-pool.go:431]: @vadmeste On the merge stage it will affect the overall throughput, since it would be added as part of the merge process, which is more limited than the code returning results.

Plus it is already unpacking the metadata when returning results - and I am pretty sure it will be applied there again anyway, so this is just duplicating work AFAICT.

Comment (harshavardhana) [reply cmd/metacache-server-pool.go:431]: why do we need to ObjectInfo() conversion here to verification? @klauspost @vadmeste ? FileInfo is enough to operate for shouldSkip()

Comment (vadmeste) [reply cmd/metacache-server-pool.go:431]:
```
                                o.debugln("Resuming", o)
                                entries, err = z.serverPools[o.pool].sets[o.set].streamMetadataParts(ctx, o)
                                entries.reuse = true // We read from stream and are not sharing results.
                                if err == nil {
                                        return entries, nil
                                }
```

it looks like we do not filter when we stream the listing from the drives. I do not think shouldSkip() will be called twice.. however, ToObjectInfo() will be called two times: the first time is in shouldSkip() when we store the listing results in the drives, the second time is when we stream the list results from the drives to do listing continuation (this is because the stored format in the drive is metacacheEntry)

isn't this acceptable for now ?

File: cmd/metacache-walk.go (hunk 1 above)
Comment (harshavardhana) [reply cmd/metacache-walk.go:203]: yes but why do we need to go through all the dirObjects[] population when we know caller is gone already.

**Review by harshavardhana — CHANGES_REQUESTED** [review]

**Review by harshavardhana — APPROVED** [review]

**Review by shtripat — APPROVED** [review]
lgtm
