### PR TITLE
Handle read/quorum errors when initializing all subsystems

### LINKED ISSUE #6584: Rolling upgrade fails when updating config file
## Expected Behavior
Rolling update of Minio server is successful when the config file needs to be migrated

## Current Behavior
Minio server fails to start:
```
ERROR Unable to initialize config system: Failed to migrate config from  29  to  30 . Storage resources are insufficient for the write operation..
```

## Possible Solution
The current code is already designed to take care of this scenario, but migration code returned error with custom message and read/write quroum are not detected anymore.

## Steps to Reproduce (for bugs)
- Run a distributed setup of Minio using this version RELEASE.2018-09-25T21-34-43Z (fresh disks)
- Kill all servers, update minio to latest release, run only N/2 servers

## Context
Fixing a bug

## Regression
No

## Your Environment
All

### LINKED ISSUE #6586: Unable to run a cluster of N/2 disks
## Expected Behavior
Users should be able to read objects with only read quorum disks then I should be able to run a cluster with N/2 nodes (where each node has one disk)

## Current Behavior
Unable to run N/2 nodes where each node has one disk

## Possible Solution
Reduce number of required available endpoints 

## Steps to Reproduce (for bugs)
Run a cluster of 12 nodes.
Kill all nodes
Run only 6 nodes of that cluster

## Context
Fixing a bug

## Regression
No

## Your Environment
All

### PR DESCRIPTION
**Pull request by vadmeste**
## Description
Policy, notification and config subsystems can encounter some read/write quorums errors and we should not quit when that happens in a distributed mode since we need also to support rolling update (when not all nodes are started or ready at the same time)

## Motivation and Context

Fixes #6586 
Fixes #6584

## Regression
No

## How Has This Been Tested?
1. Run a cluster of 12 nodes.
2. Kill all nodes
3. Run only 6 nodes of that cluster

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added unit tests to cover my changes.
- [ ] I have added/updated functional tests in [mint](https://github.com/minio/mint). (If yes, add `mint` PR # here: )
- [x] All new and existing tests passed.

### CODE REVIEW

**Review by harshavardhana — DISMISSED** [review]

**Review by kannappanr — DISMISSED** [review]

**Comment by kannappanr** [comment]
@vadmeste why is this blocked?

**Comment by vadmeste** [comment]
> @vadmeste why is this blocked?

There is still one change I need to add when there is one bucket created (cluster still won't start in that case)

**Comment by vadmeste** [comment]
@harshavardhana @kannappanr I added more one change to fix the issue, please review again

**Review by harshavardhana — APPROVED** [review]

**Review by harshavardhana — CHANGES_REQUESTED** [review]
Other additional changes needed as well, sent a patch to @vadmeste

**Review by harshavardhana — APPROVED** [review]
LGTM tested the scenarios

File: cmd/policy.go [hunk 1]
```diff
@@ -131,25 +132,46 @@ func (sys *PolicySys) Init(objAPI ObjectLayer) error {
...
-		for {
-			select {
-			case <-globalServiceDoneCh:
-				return
-			case <-ticker.C:
-				sys.refresh(objAPI)
+	doneCh := make(chan struct{})
+	defer close(doneCh)
+
+	// Initializing notification needs a retry mechanism for
```
Comment (harshavardhana) [inline cmd/policy.go]: Fix the comment here to point to policy instead of notification

**Review by harshavardhana — CHANGES_REQUESTED** [review]

File: cmd/notification.go [hunk 2]
```diff
@@ -301,48 +300,64 @@ func (sys *NotificationSys) initListeners(ctx context.Context, objAPI ObjectLaye
...
 	if err != nil {
 		return err
 	}
-
 	for _, bucket := range buckets {
 		ctx := logger.SetReqInfo(context.Background(), &logger.ReqInfo{BucketName: bucket.Name})
 		config, err := readNotificationConfig(ctx, objAPI, bucket.Name)
-		if err != nil {
-			if !IsErrIgnored(err, errDiskNotFound, errNoSuchNotifications) {
-				return err
```
Comment (kannappanr) [inline cmd/notification.go]: Should we do something for `errDiskNotFound` error?

File: cmd/policy.go (hunk 1 above)
Comment (vadmeste) [reply cmd/policy.go]: > Fix the comment here to point to policy instead of notification

Fixed

**Review by harshavardhana — APPROVED** [review]

**Review by kannappanr — APPROVED** [review]
LGTM
