### PR TITLE
XL: appendFile should return error if quorum is not met.

### LINKED ISSUE #1890: XL: appendFile always returns nil
erasureCreateFile():

```
56                 err = appendFile(disks, volume, path, blocks, eInfo.Distribution, hashWriters)                                                                                 
57                 if err != nil {                                                                                                                                                
58                         return nil, 0, err                                                                                                                                     
59                 }
```

Here appendFile() always returns nil, is this intentional?

```
111 // appendFile - append data buffer at path.                                                                                                                                   
112 func appendFile(disks []StorageAPI, volume, path string, enBlocks [][]byte, distribution []int, hashWriters []hash.Hash) (err error) {                                        
113         var wg = &sync.WaitGroup{}                                                                                                                                            
114         var wErrs = make([]error, len(disks))                                                                                                                                 
115         // Write encoded data to quorum disks in parallel.                                                                                                                    
116         for index, disk := range disks {                                                                                                                                      
117                 if disk == nil {                                                                                                                                              
118                         continue                                                                                                                                              
119                 }                                                                                                                                                             
120                 wg.Add(1)                                                                                                                                                     
121                 // Write encoded data in routine.                                                                                                                             
122                 go func(index int, disk StorageAPI) {                                                                                                                         
123                         defer wg.Done()                                                                                                                                       
124                         // Pick the block from the distribution.                                                                                                              
125                         blockIndex := distribution[index] - 1                                                                                                                 
126                         n, wErr := disk.AppendFile(volume, path, enBlocks[blockIndex])                                                                                        
127                         if wErr != nil {                                                                                                                                      
128                                 wErrs[index] = wErr                                                                                                                           
129                                 return                                                                                                                                        
130                         }                                                                                                                                                     
131                         if n != int64(len(enBlocks[blockIndex])) {                                                                                                            
132                                 wErrs[index] = errUnexpected                                                                                                                  
133                                 return                                                                                                                                        
134                         }                                                                                                                                                     
135                                                                                                                                                                               
136                         // Calculate hash for each blocks.                                                                                                                    
137                         hashWriters[blockIndex].Write(enBlocks[blockIndex])                                                                                                   
138                                                                                                                                                                               
139                         // Successfully wrote.                                                                                                                                
140                         wErrs[index] = nil                                                                                                                                    
141                 }(index, disk)                                                                                                                                                
142         }                                                                                                                                                                     
143                                                                                                                                                                               
144         // Wait for all the appends to finish.                                                                                                                                
145         wg.Wait()                                                                                                                                                             
146                                                                                                                                                                               
147         // Return success.                                                                                                                                                    
148         return nil                                                                                                                                                            
149 }                       
```

### PR DESCRIPTION
**Pull request by krishnasrinivas**
Fixes #1890

### CODE REVIEW

File: xl-v1-healing.go [hunk 1]
```diff
@@ -70,7 +70,7 @@ func (xl xlObjects) readAllXLMetadata(bucket, object string) ([]xlMetaV1, []erro
 }
 
 // error based on total errors and read quorum.
```
Comment (harshavardhana) [inline xl-v1-healing.go]: This comment needs to change, to reflect new function behavior.
