### PR TITLE
iam reload policy mapping of STS users properly

### LINKED ISSUE #18761: Inconsistent results when querying ldap entities
## Expected Behavior
When querying LDAP policy attachments from minio i expect it to return all attached policies to a user every time.

## Current Behavior
when you get a mapping either via "mc idp ldap policy entities -u" USER TARGET cli command or via the Administer > Identitiy > LDAP > entities section in the webui console. Both with randomly return a subset or all policies attached to a user. Sometimes multiple sets of results will be returned for the same user. This number of returned results depends on number of nodes in the cluster. With 3 nodes at least one set of results is always correct. With 4 nodes this is not the case.

Multiple sets of results are returned until the minio service is restarted by the k8s operator. I presume this is doing some reload of applied policies on all nodes.

❯ mc idp ldap policy entities -u "cn=LDAP_USER" TARGET
Query time: 2024-01-08T16:17:04Z
User -> Policy Mappings:
  User: LDAP_USER
    consoleAdmin
    tmp1
    tmp2
    tmp3
    tmp4
  User: LDAP_USER
    consoleAdmin
    tmp2
    tmp3
    tmp4

## Steps to Reproduce (for bugs)
add ldap idp config to minio k8s deployment.
add 2 policies to a user. query policies attached to a user and see only some be returned.

## Context
we are on a previous binary deployment of minio in production and are testing upgrading to k8s minio or a newer version and noticed this bug which would cause consistency issues.

## Your Environment
* running cluster minio deployment using minio operator in k8s. 4 node deployment. different by similar issues on 3 node cluster.
* MinIO version: minio/minio:RELEASE.2024-01-05T22-17-24Z
* when deploying this version with a single docker container connecting to ldap we do not see this issue. So i presume it has to do with multi node deployments.

### PR DESCRIPTION
**Pull request by poornas**
Incorrect map was being used - leading to inconsistent policy mapping and enforcement of permissions

## Community Contribution License
All community contributions in this pull request are licensed to the project maintainers
under the terms of the [Apache 2 license](https://www.apache.org/licenses/LICENSE-2.0). 
By creating this pull request I represent that I have the right to license the 
contributions to the project maintainers under the Apache 2 license.

## Description
Fixes #18761

## How to test this PR?
in distributed minio with LDAP , attach/detach LDAP policies on one node for a parent user and list entities or perform s3 operations on another node with LDAP sts creds for that user.

Operations should sporadically give inconsistent results, entities listed will also be duplicated/inconsistent

## Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Optimization (provides speedup with no functional changes)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [ ] Fixes a regression (If yes, please add `commit-id` or `PR #` here)  
- [ ] Unit tests added/updated
- [ ] Internal documentation updated
- [ ] Create a documentation update request [here](https://github.com/minio/docs/issues/new?label=doc-change,title=Doc+Updated+Needed+For+PR+github.com%2fminio%2fminio%2fpull%2fNNNNN)

### CODE REVIEW

File: cmd/iam-store.go [hunk 1]
```diff
@@ -1634,6 +1634,8 @@ func (store *IAMStoreSys) PolicyMappingNotificationHandler(ctx context.Context,
 	switch {
 	case isGroup:
 		m = cache.iamGroupPolicyMap
+	case userType == stsUser:
+		m = cache.iamSTSPolicyMap
```
Comment (harshavardhana) [inline cmd/iam-store.go:1638]: this fix is not sufficient @poornas

**Review by donatello — APPROVED** [review]

**Review by harshavardhana — APPROVED** [review]
