### PR TITLE
Return ErrContentSHA256Mismatch if sha256 sum is invalid

### LINKED ISSUE #216: aws-sdk-php tests fail for server/gateway
Mint test on latest rc failed. Reproducible with both Server and Gateway modes

Mint logs:

```
To get logs, run 'sudo docker cp 7bf35828e9e5:/mint/log /tmp/mint-logs'
(1/9) Running aws-sdk-php tests ... FAILED in 1 seconds
{
  "name": "aws-sdk-php",
  "function": "presignedPut ( array $params = [] )",
  "args": {
    "Bucket": "aws-sdk-php-5a0a92dc59ad6",
    "Object": "obj1"
  },
  "duration": "13",
  "status": "FAIL",
  "error": "Server error: `PUT http://127.0.0.1:9000/aws-sdk-php-5a0a92dc59ad6/obj1?X-Amz-Content-Sha256=invalid-sha256&X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=minio%2F20171114%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20171114T065317Z&X-Amz-SignedHeaders=host&X-Amz-Expires=1200&X-Amz-Signature=6f0bc30857ea246de1d84b92d91238d9aa83b21168727017e844b820e6a523c8` resulted in a `500 Internal Server Error` response:\n<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<Error><Code>InternalError</Code><Message>We encountered an internal error, pleas (truncated...)\n"
}

```

Server logs:

```
root@nitish-mint-test:~# ./minio server /tmp/test
Endpoint:  http://147.75.94.237:9000  http://10.64.0.129:9000  http://172.17.0.1:9000  http://127.0.0.1:9000
AccessKey: minio 
SecretKey: minio123 
Region:    us-east-1

Browser Access:
   http://147.75.94.237:9000  http://10.64.0.129:9000  http://172.17.0.1:9000  http://127.0.0.1:9000

Command-line Access: https://docs.minio.io/docs/minio-client-quickstart-guide
   $ mc config host add myminio http://147.75.94.237:9000 minio minio123

Object API (Amazon S3 compatible):
   Go:         https://docs.minio.io/docs/golang-client-quickstart-guide
   Java:       https://docs.minio.io/docs/java-client-quickstart-guide
   Python:     https://docs.minio.io/docs/python-client-quickstart-guide
   JavaScript: https://docs.minio.io/docs/javascript-client-quickstart-guide
   .NET:       https://docs.minio.io/docs/dotnet-client-quickstart-guide

Drive Capacity: 99 GiB Free, 102 GiB Total
ERRO[0007] Unable to fetch bucket info.                  cause=Bucket name invalid: aws-sdk-php-5a0a92dc59ad6-- source=[bucket-handlers.go:130:objectAPIHandlers.GetBucketLocationHandler()] stack=fs-v1.go:193:fsObjects.getBucketDir fs-v1.go:201:fsObjects.statBucketDir fs-v1.go:229:fsObjects.GetBucketInfo <autogenerated>:1:(*fsObjects).GetBucketInfo bucket-handlers.go:129:objectAPIHandlers.GetBucketLocationHandler api-router.go:69:(objectAPIHandlers).GetBucketLocationHandler-fm
ERRO[0007] Unable to fetch bucket info.                  cause=Bucket name invalid: aws-sdk-php-5a0a92dc59b12-- source=[bucket-handlers.go:659:objectAPIHandlers.HeadBucketHandler()] stack=fs-v1.go:193:fsObjects.getBucketDir fs-v1.go:201:fsObjects.statBucketDir fs-v1.go:229:fsObjects.GetBucketInfo <autogenerated>:1:(*fsObjects).GetBucketInfo bucket-handlers.go:658:objectAPIHandlers.HeadBucketHandler api-router.go:89:(objectAPIHandlers).HeadBucketHandler-fm
ERRO[0007] Unable to delete object. obj1-copy0           cause=Prefix access is denied: aws-sdk-php-5a0a92dc59ad6/obj1-copy0 source=[bucket-handlers.go:337:objectAPIHandlers.DeleteMultipleObjectsHandler()]
ERRO[0007] Unable to delete object. obj1-copy1           cause=Prefix access is denied: aws-sdk-php-5a0a92dc59ad6/obj1-copy1 source=[bucket-handlers.go:337:objectAPIHandlers.DeleteMultipleObjectsHandler()]
ERRO[0007] Unable to delete object. obj1-copy2           cause=Prefix access is denied: aws-sdk-php-5a0a92dc59ad6/obj1-copy2 source=[bucket-handlers.go:337:objectAPIHandlers.DeleteMultipleObjectsHandler()]
ERRO[0008] Unable to complete multipart upload.          cause=Part size for 1 should be at least 5MB source=[object-handlers.go:1061:objectAPIHandlers.CompleteMultipartUploadHandler()] stack=fs-v1-multipart.go:806:fsObjects.CompleteMultipartUpload <autogenerated>:1:(*fsObjects).CompleteMultipartUpload object-handlers.go:1059:objectAPIHandlers.CompleteMultipartUploadHandler api-router.go:52:(objectAPIHandlers).CompleteMultipartUploadHandler-fm

```

### PR DESCRIPTION
**Pull request by krisis**
## Description

Minio server and gateway returned `500 Internal Error` if `X-Amz-Content-SHA256` had an invalid hex. 
With this change, we would return ErrContentSHA256Mismatch if the underlying hash reader fails to decode the sha256 sum hex. This is because no payload can have an invalid sha256sum and trivially an invalid sha256 sum hex would be a mismatch.

## Motivation and Context

Fixes minio/mint#216
## How Has This Been Tested?

Using mint
## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added unit tests to cover my changes.
- [ ] I have added/updated functional tests in [mint](https://github.com/minio/mint). (If yes, add `mint` PR # here: )
- [x] All new and existing tests passed.

### CODE REVIEW

File: cmd/object-handlers.go [hunk 1]
```diff
@@ -583,6 +583,10 @@ func (api objectAPIHandlers) PutObjectHandler(w http.ResponseWriter, r *http.Req
 
 	hashReader, err := hash.NewReader(reader, size, md5hex, sha256hex)
 	if err != nil {
+		if _, ok := err.(hex.InvalidByteError); ok {
+			writeErrorResponse(w, ErrContentSHA256Mismatch, r.URL)
```
Comment (harshavardhana) [inline cmd/object-handlers.go]: we have a `pkg/hash/errors.go`  to return this error SHA256Mismatch{} @krisis we so we can return from the hash.NewReader() internally we don't need to do this here. 

We can perhaps do this for md5sum as well while we are at it.

Comment (harshavardhana) [reply cmd/object-handlers.go]: You can also bring a test case inside the package pkg/hash for this.

**Review by harshavardhana — CHANGES_REQUESTED** [review]

**Review by harshavardhana — DISMISSED** [review]

**Review by harshavardhana — APPROVED** [review]
LGTM - tested

**Review by donatello — APPROVED** [review]
