### PR TITLE
fix: set modTime to current in snowball if archive shows empty 

### LINKED ISSUE #16481: snowball zero ModTime (internal error: invalid version entry generated)
I tried to upload snowball (golang).

## Expected Behavior
n/a

## Current Behavior
```
UserAgent: MinIO (linux; amd64) minio-go/v7.0.47
Error: internal error: invalid version entry generated (*errors.errorString)
       5: /home/danil_e71/minio/internal/logger/logger.go:258:logger.LogIf()
       4: /home/danil_e71/minio/cmd/api-errors.go:2235:cmd.toAPIErrorCode()
       3: /home/danil_e71/minio/cmd/api-errors.go:2260:cmd.toAPIError()
       2: /home/danil_e71/minio/cmd/object-handlers.go:2224:cmd.objectAPIHandlers.PutObjectExtractHandler()
       1: net/http/server.go:2109:http.HandlerFunc.ServeHTTP()
```

## Possible Solution
You must set ModTime

```
	input <- minio.SnowballObject{
		ModTime: time.Now(),
```

## Steps to Reproduce (for bugs)

```
	input <- minio.SnowballObject{
		ModTime: 0, 
```

## Context
In previous versions zero modtime is no bug.

[cmd/xl-storage-format-v2.go
](https://github.com/minio/minio/blob/master/cmd/xl-storage-format-v2.go#L324)

## Regression
n/a

## Your Environment
* Version used minio/minio:RELEASE.2023-01-25T00-19-54Z

### PR DESCRIPTION
**Pull request by klauspost**
## Description

If ModTime in snowball object is prior to or equal to unix epoc, set it to current time.

Fixes #16481

## How to test this PR?

See #16481

## Types of changes
- [x] Bug fix/New feature

### CODE REVIEW

**Comment by minio-trusted** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-erasure.sh | :heavy_check_mark: |
| mint-dist-erasure.sh | :heavy_check_mark: |
| mint-compress-encrypt-dist-erasure.sh | :heavy_check_mark: |
| mint-pools.sh | :heavy_check_mark: |
Deleting image on docker hub
Deleting image locally

**Review by harshavardhana — APPROVED** [review]

File: cmd/untar.go [hunk 1]
```diff
@@ -259,6 +260,11 @@ func untar(ctx context.Context, r io.Reader, putObject func(reader io.Reader, in
 			continue
 		}
 
+		// If zero or earlier modtime, set to current.
```
Comment (vadmeste) [inline cmd/untar.go:263]: Can you update the comment to say this is for snowball in particular ? I will never know what this is about in one year

**Review by vadmeste — COMMENTED** [review]
One comment

File: cmd/untar.go (hunk 1 above)
Comment (klauspost) [reply cmd/untar.go:263]: Added the reason for the modification.

**Review by vadmeste — APPROVED** [review]
LGTM

**Comment by minio-trusted** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-erasure.sh | :heavy_check_mark: |
| mint-dist-erasure.sh | :heavy_check_mark: |
| mint-compress-encrypt-dist-erasure.sh | :heavy_check_mark: |
| mint-pools.sh | :heavy_check_mark: |
Deleting image on docker hub
Deleting image locally
