### PR TITLE
fix: calculate correct content-range with partNumber query

### LINKED ISSUE #11824: Multipart download fails on some content
## Expected Behavior

I have a ZIP file in a folder:

```
|- repository/8e/9f123eb2-7bb2-470d-bfbf-48b5104f905b
`- test.zip
```

Downloading the entire folder using the AWS SDK for Java has worked flawlessly till now, i.e.

```
transferManager.downloadDirectory("bucket", "repository/8e/9f123eb2-7bb2-470d-bfbf-48b5104f905b", tempDir)
                .waitForCompletion();
```

The folder is downloaded with the contained file and no exception is thrown.

## Current Behavior

However, since RELEASE.2021-01-30T00-20-58Z, MinIO appears to stop sending the entire file:

```
Exception in thread "main" com.amazonaws.SdkClientException: Unable to complete multipart download. Individual part download failed.
	at com.amazonaws.services.s3.transfer.internal.CompleteMultipartDownload.call(CompleteMultipartDownload.java:54)
	at com.amazonaws.services.s3.transfer.internal.CompleteMultipartDownload.call(CompleteMultipartDownload.java:29)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.util.concurrent.ExecutionException: org.apache.http.ConnectionClosedException: Premature end of Content-Length delimited message body (expected: 35,932,379; received: 5,242,880)
	at java.base/java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:191)
	at com.amazonaws.services.s3.transfer.internal.CompleteMultipartDownload.call(CompleteMultipartDownload.java:47)
	... 5 more
Caused by: org.apache.http.ConnectionClosedException: Premature end of Content-Length delimited message body (expected: 35,932,379; received: 5,242,880)
	at org.apache.http.impl.io.ContentLengthInputStream.read(ContentLengthInputStream.java:178)
	at org.apache.http.conn.EofSensorInputStream.read(EofSensorInputStream.java:135)
	at com.amazonaws.internal.SdkFilterInputStream.read(SdkFilterInputStream.java:90)
	at com.amazonaws.event.ProgressInputStream.read(ProgressInputStream.java:180)
	at com.amazonaws.internal.SdkFilterInputStream.read(SdkFilterInputStream.java:90)
	at com.amazonaws.internal.SdkFilterInputStream.read(SdkFilterInputStream.java:90)
	at com.amazonaws.internal.SdkFilterInputStream.read(SdkFilterInputStream.java:90)
	at com.amazonaws.event.ProgressInputStream.read(ProgressInputStream.java:180)
	at com.amazonaws.internal.SdkFilterInputStream.read(SdkFilterInputStream.java:90)
	at com.amazonaws.util.LengthCheckInputStream.read(LengthCheckInputStream.java:107)
	at com.amazonaws.internal.SdkFilterInputStream.read(SdkFilterInputStream.java:90)
	at com.amazonaws.services.s3.internal.S3AbortableInputStream.read(S3AbortableInputStream.java:125)
	at com.amazonaws.internal.SdkFilterInputStream.read(SdkFilterInputStream.java:90)
	at java.base/java.io.FilterInputStream.read(FilterInputStream.java:107)
	at com.amazonaws.services.s3.transfer.internal.DownloadS3ObjectCallable.call(DownloadS3ObjectCallable.java:71)
	at com.amazonaws.services.s3.transfer.internal.DownloadS3ObjectCallable.call(DownloadS3ObjectCallable.java:36)
	... 4 more
```

The MinIO trace logs (using `mc admin trace`):

```
11:14:38.008 [200 OK] s3.ListObjectsV1 192.168.59.101:9000/bucket/?prefix=reposito
ry%2F8e%2F9f123eb2-7bb2-470d-bfbf-48b5104f905b&delimiter=%2F&encoding-type=url
192.168.59.99     403µs       ↑ 153 B ↓ 658 B
11:14:38.083 [200 OK] s3.ListObjectsV1 192.168.59.101:9000/bucket/?prefix=reposito
ry%2F8e%2F9f123eb2-7bb2-470d-bfbf-48b5104f905b%2F&delimiter=%2F&encoding-type=ur
l  192.168.59.99     912µs       ↑ 153 B ↓ 937 B
11:14:38.100 [200 OK] s3.HeadObject 192.168.59.101:9000/bucket/repository/8e/9f123
eb2-7bb2-470d-bfbf-48b5104f905b/test.zip 192.168.59.99     611µs       ↑ 15
3 B ↓ 323 B
11:14:38.106 [206 Partial Content] s3.HeadObject 192.168.59.101:9000/bucket/reposi
tory/8e/9f123eb2-7bb2-470d-bfbf-48b5104f905b/test.zip?partNumber=1  192.168
.59.99     523µs       ↑ 153 B ↓ 401 B
11:14:38.122 [206 Partial Content] s3.HeadObject 192.168.59.101:9000/bucket/reposi
tory/8e/9f123eb2-7bb2-470d-bfbf-48b5104f905b/test.zip?partNumber=1  192.168
.59.99     728µs       ↑ 153 B ↓ 401 B
11:14:38.131 [206 Partial Content] s3.HeadObject 192.168.59.101:9000/bucket/reposi
tory/8e/9f123eb2-7bb2-470d-bfbf-48b5104f905b/test.zip?partNumber=1  192.168
.59.99     970µs       ↑ 153 B ↓ 401 B
11:14:38.141 [206 Partial Content] s3.HeadObject 192.168.59.101:9000/bucket/reposi
tory/8e/9f123eb2-7bb2-470d-bfbf-48b5104f905b/test.zip?partNumber=2  192.168
.59.99     548µs       ↑ 153 B ↓ 401 B
11:14:38.147 [206 Partial Content] s3.HeadObject 192.168.59.101:9000/bucket/reposi
tory/8e/9f123eb2-7bb2-470d-bfbf-48b5104f905b/test.zip?partNumber=3  192.168
.59.99     1.003ms      ↑ 153 B ↓ 401 B
11:14:38.161 [206 Partial Content] s3.HeadObject 192.168.59.101:9000/bucket/reposi
tory/8e/9f123eb2-7bb2-470d-bfbf-48b5104f905b/test.zip?partNumber=4  192.168
.59.99     728µs       ↑ 153 B ↓ 401 B
11:14:38.171 [206 Partial Content] s3.HeadObject 192.168.59.101:9000/bucket/reposi
tory/8e/9f123eb2-7bb2-470d-bfbf-48b5104f905b/test.zip?partNumber=5  192.168
.59.99     581µs       ↑ 153 B ↓ 401 B
11:14:38.177 [206 Partial Content] s3.HeadObject 192.168.59.101:9000/bucket/reposi
tory/8e/9f123eb2-7bb2-470d-bfbf-48b5104f905b/test.zip?partNumber=6  192.168
.59.99     798µs       ↑ 153 B ↓ 401 B
11:14:38.183 [206 Partial Content] s3.HeadObject 192.168.59.101:9000/bucket/reposi
tory/8e/9f123eb2-7bb2-470d-bfbf-48b5104f905b/test.zip?partNumber=7  192.168
.59.99     411µs       ↑ 153 B ↓ 401 B
11:14:38.135 [206 Partial Content] s3.GetObject 192.168.59.101:9000/bucket/reposit
ory/8e/9f123eb2-7bb2-470d-bfbf-48b5104f905b/test.zip?partNumber=1  192.168.
59.99     113.301ms    ↑ 153 B ↓ 5.0 MiB
11:14:38.143 [206 Partial Content] s3.GetObject 192.168.59.101:9000/bucket/reposit
ory/8e/9f123eb2-7bb2-470d-bfbf-48b5104f905b/test.zip?partNumber=2  192.168.
59.99     204.809ms    ↑ 153 B ↓ 5.0 MiB
11:14:38.149 [206 Partial Content] s3.GetObject 192.168.59.101:9000/bucket/reposit
ory/8e/9f123eb2-7bb2-470d-bfbf-48b5104f905b/test.zip?partNumber=3  192.168.
59.99     214.809ms    ↑ 153 B ↓ 5.0 MiB
11:14:38.297 [206 Partial Content] s3.GetObject 192.168.59.101:9000/bucket/reposit
ory/8e/9f123eb2-7bb2-470d-bfbf-48b5104f905b/test.zip?partNumber=5  192.168.
59.99     829.543ms    ↑ 153 B ↓ 5.0 MiB
11:14:38.289 [206 Partial Content] s3.GetObject 192.168.59.101:9000/bucket/reposit
ory/8e/9f123eb2-7bb2-470d-bfbf-48b5104f905b/test.zip?partNumber=4  192.168.
59.99     839.761ms    ↑ 153 B ↓ 5.0 MiB
11:14:38.293 [206 Partial Content] s3.GetObject 192.168.59.101:9000/bucket/reposit
ory/8e/9f123eb2-7bb2-470d-bfbf-48b5104f905b/test.zip?partNumber=6  192.168.
59.99     1.306906s    ↑ 153 B ↓ 5.0 MiB
11:14:38.299 [206 Partial Content] s3.GetObject 192.168.59.101:9000/bucket/reposit
ory/8e/9f123eb2-7bb2-470d-bfbf-48b5104f905b/test.zip?partNumber=7  192.168.
59.99     1.308151s    ↑ 153 B ↓ 4.3 MiB
```

There were no errors printed in the console.

## Steps to Reproduce (for bugs)

Here is a minimum example using the AWS SDK for Java:

```
package com.tts.premature_end_content;

import com.amazonaws.auth.AWSStaticCredentialsProvider;
import com.amazonaws.auth.BasicAWSCredentials;
import com.amazonaws.client.builder.AwsClientBuilder;
import com.amazonaws.regions.Regions;
import com.amazonaws.services.s3.AmazonS3Client;
import com.amazonaws.services.s3.transfer.TransferManagerBuilder;

import java.io.IOException;
import java.nio.file.Files;

public class Test {
    public static void main(String[] args) throws InterruptedException, IOException {
        var transferManager = TransferManagerBuilder.standard()
                .withS3Client(AmazonS3Client.builder()
                        .withEndpointConfiguration(new AwsClientBuilder.EndpointConfiguration("http://192.168.59.101:9000", Regions.DEFAULT_REGION.getName()))
                        .withCredentials(new AWSStaticCredentialsProvider(new BasicAWSCredentials("minio", "minio123")))
                        .build()
                )
                .build();
        var tempFile = Files.createTempDirectory("test").toFile();
        var download = transferManager.downloadDirectory("ttps", "repository/8e/9f123eb2-7bb2-470d-bfbf-48b5104f905b",
                tempFile);
        System.out.println("Waiting for completion...");
        download.waitForCompletion();
        System.out.println("Finished!");
    }
}
```

*However*, it is only reproducible with particular files. I have tried to create a minimal ZIP file that reproduces the problem but it appears to be dependent on the combination of files contained. Here are some of the features of the ZIP file that fails. It:

* is 35,091 KB compressed
* is 43,945 KB uncompressed
* contains 1,847 files
* contains files of sizes between 80 B and 7 MB

It still doesn't work after removing many of the files, but it's arbitrary as to which and sometimes removing a file is ok if other files are removed with it. For example, I made a smaller version that also fails which:

* is 16,390 KB compressed
* is 16,827 KB uncompressed
* contains 899 files
* contains files of sizes between 1 KB and 5.2 MB

Other things I've tried:

* Downloading the individual ZIP (Works)
* Downloading the unzipped contents in a directory (Works)
* Renaming the file/extension (Fails, i.e. filename is irrelevant)
* Using different prefixes (Fails, i.e. prefix is irrelevant)
* Rezipping the contents, uploading them through MinIO & downloading the directory again (Fails, i.e. not a corrupt ZIP)
* Renaming the contents, e.g. to 001, 002, .. 899 (Fails, i.e. filenames unimportant)

Unfortunately I can't send the file as it contains copyrighted material, e.g. music files. The files inside are pretty arbitrary though, as they're only used for test purposes.

## Regression

Yes, it first occurs in RELEASE.2021-01-30T00-20-58Z. There was no problem in RELEASE.2021-01-16T02-19-44Z and earlier. 

## Your Environment

* MinIO version as above
* MinIO running in Windows standalone and in a Linux VM (Ubuntu) in a Docker container  
For some reason it does appear to work when MinIO was running as a Windows Service, but there may be another reason for that.
* Client/code running in Windows 10 19041.867
* AWS SDK versions 1.11.710 and 1.11.975 (no difference)

### LINKED ISSUE #11989: HEAD requests for a partNumber no longer return a ranged reply
A regression between RELEASE.2020-11-13T20-10-18Z and RELEASE.2021-03-26T00-00-41Z has changed the Content information returned by part-specific HEAD requests.

This might be the same issue as #11824

## Expected Behavior

An HTTP request for part number 1: 

>HEAD /repo1/img?partNumber=1 HTTP/1.1
> if-match: "ccb718aa1f39f6416f789cf733a387c7-7"
> x-amz-content-sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
> x-amz-date: 20210407T003436Z
> ...

should return a ranged response covering the range of bytes for the requested part:

> HTTP/1.1 206 Partial Content
> Accept-Ranges: bytes
> Content-Length: 59768832
> Content-Range: bytes 0-59768831/417988608
> Content-Security-Policy: block-all-mixed-content
> Content-Type: application/octet-stream
> ETag: "ccb718aa1f39f6416f789cf733a387c7-7"
> Last-Modified: Tue, 06 Apr 2021 20:48:30 GMT
> Server: MinIO/RELEASE.2020-11-13T20-10-18Z
> Vary: Origin
> X-Amz-Request-Id: 16736C36CF553906
> X-Xss-Protection: 1; mode=block
> x-amz-mp-parts-count: 7
> Date: Wed, 07 Apr 2021 00:34:33 GMT

## Current Behavior

Reply now covers the whole file, rather than just the bytes in the requested part:

> HTTP/1.1 206 Partial Content <
> Accept-Ranges: bytes <
> Content-Length: 417988608 <
> Content-Range: bytes 0-417988607/417988608 <
> Content-Security-Policy: block-all-mixed-content <
> Content-Type: application/octet-stream <
> ETag: "ccb718aa1f39f6416f789cf733a387c7-7" <
> Last-Modified: Mon, 05 Apr 2021 19:13:29 GMT <
> Server: MinIO <
> Vary: Origin <
> X-Amz-Request-Id: 1673686323A60D1F <
> X-Xss-Protection: 1; mode=block <
> x-amz-mp-parts-count: 7 <
> Date: Tue, 06 Apr 2021 23:24:26 GMT

## Steps to Reproduce (for bugs)

1. upload a multi-part file
2. issue a HEAD request for partNumber=1 - reply should cover the range of part number 1, not the whole file

## Context

While this particular issue is one that I can work around, I'm posting it here because current behavior contradicts AWS S3 documentation and so will affect any applications that depend on the proper Content-range information being returned. 

## Regression
Is this issue a regression? (Yes / No) Yes

### PR DESCRIPTION
**Pull request by harshavardhana**
## Description
fix: calculate correct content-range with partNumber query

## Motivation and Context
fixes #11989
fixes #11824

## How to test this PR?
Upload a multipart file and send `curl` requests with partNumber.

## Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Optimization (provides speedup with no functional changes)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [x] Fixes a regression it used to work, not sure when it was changed.
- [ ] Documentation updated
- [ ] Unit tests added/updated

### CODE REVIEW

**Comment by minio-trusted** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-s3.sh | :heavy_check_mark: |
| mint-erasure.sh | :heavy_check_mark: |
| mint-dist-erasure.sh | :heavy_check_mark: |
| mint-zoned.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-compress-encrypt-dist-erasure.sh | :x: [more...](#42f18bda-84cb-4b07-909a-d41f29fc0be2) |
<a name="42f18bda-84cb-4b07-909a-d41f29fc0be2"></a>
### 11992-b441e8b/mint-compress-encrypt-dist-erasure.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-dev8.minio.io:31908
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 1c3c99b7cb56:/mint/log /tmp/mint-logs'

(1/15) Running aws-sdk-go tests ... done in 1 seconds
(2/15) Running aws-sdk-java tests ... done in 1 seconds
(3/15) Running aws-sdk-php tests ... done in 43 seconds
(4/15) Running aws-sdk-ruby tests ... done in 4 seconds
(5/15) Running awscli tests ... FAILED in 31 seconds
{
  "name": "awscli",
  "duration": 2473,
  "function": "aws --endpoint-url http://minio-dev8.minio.io:31908 s3api copy-object --bucket awscli-mint-test-bucket-15034 --key datafile-1-kB-copy --copy-source awscli-mint-test-bucket-15034/datafile-1-kB\n",
  "status": "FAIL",
  "error": "Hash mismatch expected 084e1383b70fb0c51acc680fef370023, got ac57de7156d7fc25ac1a65f81fa3989b"
}
(5/15) Running healthcheck tests ... done in 0 seconds
(6/15) Running mc tests ... done in 46 seconds
(7/15) Running minio-dotnet tests ... done in 42 seconds
(8/15) Running minio-go tests ... FAILED in 2 minutes and 3 seconds
{
  "args": {},
  "duration": 574,
  "error": "At least one of the pre-conditions you specified did not hold",
  "function": "CopyObjectPart(destination, source)",
  "message": "CopyObjectPart call failed",
  "name": "minio-go: testUnencryptedToSSES3CopyObjectPart",
  "status": "FAIL"
}
(8/15) Running minio-java tests ... FAILED in 1 minutes and 33 seconds
{
  "name": "minio-java",
  "function": "copyObject()",
  "args": "[match etag]",
  "duration": 347,
  "status": "FAIL",
  "error": "error occurred\nErrorResponse(code = PreconditionFailed, message = At least one of the pre-conditions you specified did not hold, bucketName = minio-java-test-1vipco0, objectName = minio-java-test-1f5smbq-copy, resource = /minio-java-test-1vipco0/minio-java-test-1f5smbq-copy, requestId = 16737F2AC4EBC0F8, hostId = 86d0854c-56e6-4579-a810-e3654001036c)\nrequest={method=PUT, url=http://minio-dev8.minio.io:31908/minio-java-test-1vipco0/minio-java-test-1f5smbq-copy, headers=x-amz-copy-source-if-match: 71cff0a060f852067e443ad1e24ae26c-1\nx-amz-copy-source: /minio-java-test-32ije1c/minio-java-test-1f5smbq\nHost: minio-dev8.minio.io:31908\nAccept-Encoding: identity\nUser-Agent: MinIO (Linux; amd64) minio-java/8.0.3\nContent-MD5: 1B2M2Y8AsgTpgAmY7PhCfg==\nx-amz-content-sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855\nx-amz-date: 20210407T062152Z\nAuthorization: AWS4-HMAC-SHA256 Credential=*REDACTED*/20210407/us-east-1/s3/aws4_request, SignedHeaders=content-md5;host;x-amz-content-sha256;x-amz-copy-source;x-amz-copy-source-if-match;x-amz-date, Signature=*REDACTED*\n}\nresponse={code=412, headers=Accept-Ranges: bytes\nContent-Length: 418\nContent-Security-Policy: block-all-mixed-content\nContent-Type: application/xml\nETag: \"71cff0a060f852067e443ad1e24ae26c\"\nLast-Modified: Wed, 07 Apr 2021 06:21:52 GMT\nServer: MinIO\nVary: Origin\nX-Amz-Request-Id: 16737F2AC4EBC0F8\nX-Xss-Protection: 1; mode=block\nDate: Wed, 07 Apr 2021 06:21:52 GMT\n}\n >>> [io.minio.MinioClient.execute(MinioClient.java:775), io.minio.MinioClient.execute(MinioClient.java:563), io.minio.MinioClient.executePut(MinioClient.java:904), io.minio.MinioClient.copyObject(MinioClient.java:1232), FunctionalTest.testCopyObjectMatchETag(FunctionalTest.java:1850), FunctionalTest.copyObject(FunctionalTest.java:2016), FunctionalTest.runObjectTests(FunctionalTest.java:3757), FunctionalTest.runTests(FunctionalTest.java:3783), FunctionalTest.main(FunctionalTest.java:3927)]"
}
(8/15) Running minio-js tests ... done in 52 seconds
(9/15) Running minio-py tests ... done in 3 minutes and 13 seconds
(10/15) Running s3cmd tests ... FAILED in 5 seconds
{
  "name": "s3cmd",
  "duration": "3116",
  "function": "test_put_object_multipart",
  "status": "FAIL",
  "error": "WARNING: MD5 Sums don't match!\nWARNING: Retrying upload of /mint/data/datafile-65-MB\nWARNING: MD5 Sums don't match!\nWARNING: Retrying upload of /mint/data/datafile-65-MB\nWARNING: MD5 Sums don't match!\nWARNING: Retrying upload of /mint/data/datafile-65-MB\nWARNING: MD5 Sums don't match!\nWARNING: Retrying upload of /mint/data/datafile-65-MB\nWARNING: MD5 Sums don't match!\nWARNING: Retrying upload of /mint/data/datafile-65-MB\nWARNING: MD5 Sums don't match!\nWARNING: Too many failures. Giving up on '/mint/data/datafile-65-MB'\nERROR: \nUpload of '/mint/data/datafile-65-MB' part 1 failed. Use\n  /usr/local/bin/s3cmd abortmp s3://s3cmd-test-bucket-6398/s3cmd-test-object-7141 1fc33bc7-0a03-4d66-81ed-13890be90314\nto abort the upload, or\n  /usr/local/bin/s3cmd --upload-id 1fc33bc7-0a03-4d66-81ed-13890be90314 put ...\nto continue the upload.\nERROR: Upload of '/mint/data/datafile-65-MB' failed too many times (Last reason: )"
}
(10/15) Running s3select tests ... done in 7 seconds
(11/15) Running security tests ... done in 0 seconds

Executed 11 out of 15 tests successfully.
```
Deleting image on docker hub
Deleting image locally

**Review by klauspost — APPROVED** [review]
LGTM

File: cmd/api-headers.go [hunk 1]
```diff
@@ -166,6 +166,10 @@ func setObjectHeaders(w http.ResponseWriter, objInfo ObjectInfo, rs *HTTPRangeSp
 
 	if rs == nil && opts.PartNumber > 0 {
 		rs = partNumberToRangeSpec(objInfo, opts.PartNumber)
+		start, rangeLen, err = rs.GetOffsetLength(totalObjectSize)
```
Comment (vadmeste) [inline cmd/api-headers.go]: I believe it is just easier if you move line 167 before line 162

**Review by vadmeste — CHANGES_REQUESTED** [review]
One comment

File: cmd/api-headers.go (hunk 1 above)
Comment (harshavardhana) [reply cmd/api-headers.go]: How is it easier? - remember we are only going to respond to partNumber if range is not set. 

If range is set as well as partNumber range is honored as per AWS S3 spec.

**Comment by minio-trusted** [comment]
```
Error running mint automation
+ mkdir -p 11992-6b2fa0b/gopath/src/github.com/minio
+ git -C 11992-6b2fa0b/gopath/src/github.com/minio clone --quiet https://github.com/minio/minio.git
+ git -C 11992-6b2fa0b/gopath/src/github.com/minio/minio remote add minio https://github.com/minio/minio.git
+ git -C 11992-6b2fa0b/gopath/src/github.com/minio/minio fetch --quiet minio pull/11992/head:pr11992
+ git -C 11992-6b2fa0b/gopath/src/github.com/minio/minio checkout --quiet pr11992
+ GO111MODULE=on
+ GOPATH=/home/mint-auto/mint-auto/11992-6b2fa0b/gopath
+ make -C 11992-6b2fa0b/gopath/src/github.com/minio/minio --quiet
go: downloading github.com/minio/cli v1.22.0
go: downloading github.com/dustin/go-humanize v1.0.0
go: downloading github.com/minio/minio-go/v7 v7.0.11-0.20210302210017-6ae69c73ce78
go: downloading github.com/Azure/azure-pipeline-go v0.2.2
go: downloading github.com/json-iterator/go v1.1.10
go: downloading github.com/colinmarc/hdfs/v2 v2.2.0
go: downloading github.com/Azure/azure-storage-blob-go v0.10.0
go: downloading github.com/montanaflynn/stats v0.5.0
go: downloading github.com/jcmturner/gokrb5/v8 v8.4.2
go: downloading cloud.google.com/go v0.39.0
go: downloading google.golang.org/api v0.5.0
go: downloading github.com/minio/highwayhash v1.0.2
go: downloading github.com/minio/sha256-simd v1.0.0
go: downloading github.com/mattn/go-colorable v0.1.8
go: downloading github.com/fatih/color v1.10.0
go: downloading github.com/dgrijalva/jwt-go v3.2.0+incompatible
go: downloading golang.org/x/sys v0.0.0-20210225134936-a50acf3fe073
go: downloading github.com/shirou/gopsutil/v3 v3.21.1
go: downloading github.com/secure-io/sio-go v0.3.1
go: downloading github.com/valyala/tcplisten v0.0.0-20161114210144-ceec8f93295a
go: downloading github.com/mattn/go-isatty v0.0.12
go: downloading golang.org/x/net v0.0.0-20201216054612-986b41b23924
go: downloading github.com/rjeczalik/notify v0.9.2
go: downloading golang.org/x/crypto v0.0.0-20210220033148-5ea612d1eb83
go: downloading gopkg.in/yaml.v2 v2.3.0
go: downloading github.com/dswarbrick/smart v0.0.0-20190505152634-909a45200d6d
go: downloading github.com/ncw/directio v1.0.5
go: downloading github.com/bcicen/jstream v1.0.1
go: downloading github.com/gorilla/handlers v1.5.1
go: downloading github.com/VividCortex/ewma v1.1.1
go: downloading github.com/klauspost/readahead v1.3.1
go: downloading github.com/dchest/siphash v1.2.1
go: downloading github.com/cespare/xxhash/v2 v2.1.1
go: downloading github.com/djherbis/atime v1.0.0
go: downloading github.com/klauspost/reedsolomon v1.9.11
go: downloading github.com/klauspost/compress v1.11.12
go: downloading github.com/google/uuid v1.1.2
go: downloading github.com/cheggaaa/pb v1.0.29
go: downloading github.com/klauspost/pgzip v1.2.5
go: downloading github.com/miekg/dns v1.1.35
go: downloading github.com/minio/sio v0.2.1
go: downloading github.com/mitchellh/go-homedir v1.1.0
go: downloading github.com/philhofer/fwd v1.1.1
go: downloading github.com/prometheus/client_golang v1.8.0
go: downloading github.com/pierrec/lz4 v2.5.2+incompatible
go: downloading github.com/minio/selfupdate v0.3.1
go: downloading github.com/gorilla/mux v1.8.0
go: downloading github.com/prometheus/client_model v0.2.0
go: downloading github.com/prometheus/procfs v0.6.0
go: downloading github.com/rs/cors v1.7.0
go: downloading github.com/tinylib/msgp v1.1.3
go: downloading go.etcd.io/etcd v0.0.0-20201125193152-8a03d2e9614b
go: downloading github.com/go-ldap/ldap v3.0.2+incompatible
go: downloading github.com/fatih/structs v1.1.0
go: downloading go.uber.org/zap v1.13.0
go: downloading github.com/willf/bloom v2.0.3+incompatible
go: downloading github.com/coredns/coredns v1.4.0
go: downloading github.com/beevik/ntp v0.3.0
go: downloading github.com/minio/simdjson-go v0.2.1
go: downloading github.com/hashicorp/vault/api v1.0.4
go: downloading github.com/Shopify/sarama v1.27.2
go: downloading github.com/eclipse/paho.mqtt.golang v1.3.0
go: downloading github.com/go-sql-driver/mysql v1.5.0
go: downloading github.com/gomodule/redigo v1.8.3
go: downloading github.com/lib/pq v1.9.0
go: downloading github.com/nats-io/nats.go v1.10.0
go: downloading github.com/nats-io/stan.go v0.8.3
go: downloading github.com/nsqio/go-nsq v1.0.8
go: downloading github.com/olivere/elastic/v7 v7.0.22
go: downloading github.com/pkg/errors v0.9.1
go: downloading github.com/streadway/amqp v1.0.0
go: downloading github.com/xdg/scram v0.0.0-20180814205039-7eeb5667e42c
go: downloading github.com/alecthomas/participle v0.2.1
go: downloading github.com/mattn/go-ieproxy v0.0.1
go: downloading github.com/golang/protobuf v1.4.3
go: downloading github.com/spaolacci/murmur3 v1.1.0
go: downloading github.com/willf/bitset v1.1.11
go: downloading git.apache.org/thrift.git v0.13.0
go: downloading github.com/mattn/go-runewidth v0.0.4
go: downloading github.com/tidwall/gjson v1.6.8
go: downloading github.com/tidwall/sjson v1.0.4
go: downloading github.com/go-ldap/ldap/v3 v3.2.4
go: downloading github.com/klauspost/cpuid v1.3.1
go: downloading github.com/golang/snappy v0.0.1
go: downloading github.com/felixge/httpsnoop v1.0.1
go: downloading github.com/mitchellh/mapstructure v1.1.2
go: downloading github.com/hashicorp/go-retryablehttp v0.5.4
go: downloading github.com/hashicorp/go-multierror v1.0.0
go: downloading github.com/hashicorp/errwrap v1.0.0
go: downloading github.com/hashicorp/go-rootcerts v1.0.1
go: downloading github.com/hashicorp/vault/sdk v0.1.13
go: downloading github.com/hashicorp/hcl v1.0.0
go: downloading github.com/hashicorp/go-cleanhttp v0.5.1
go: downloading golang.org/x/time v0.0.0-20191024005414-555d28b269f0
go: downloading gopkg.in/square/go-jose.v2 v2.3.1
go: downloading github.com/xdg/stringprep v1.0.0
go: downloading github.com/nats-io/nuid v1.0.1
go: downloading github.com/tidwall/match v1.0.3
go: downloading github.com/tidwall/pretty v1.0.2
go: downloading github.com/gogo/protobuf v1.3.2
go: downloading github.com/modern-go/concurrent v0.0.0-20180306012644-bacd9c7ef1dd
go: downloading github.com/modern-go/reflect2 v1.0.1
go: downloading github.com/gorilla/websocket v1.4.2
go: downloading github.com/go-asn1-ber/asn1-ber v1.5.1
go: downloading github.com/Azure/go-ntlmssp v0.0.0-20200615164410-66371956d46c
go: downloading golang.org/x/text v0.3.3
go: downloading google.golang.org/grpc v1.26.0
go: downloading golang.org/x/oauth2 v0.0.0-20190226205417-e64efc72b421
go: downloading go.uber.org/multierr v1.3.0
go: downloading go.uber.org/atomic v1.5.0
go: downloading github.com/nats-io/nkeys v0.2.0
go: downloading github.com/nats-io/jwt v1.1.0
go: downloading github.com/prometheus/common v0.14.0
go: downloading github.com/beorn7/perks v1.0.1
go: downloading github.com/jcmturner/gofork v1.0.0
go: downloading github.com/jcmturner/dnsutils/v2 v2.0.0
go: downloading github.com/hashicorp/go-uuid v1.0.2
go: downloading github.com/jcmturner/aescts/v2 v2.0.0
go: downloading github.com/jcmturner/rpc/v2 v2.0.3
go: downloading google.golang.org/protobuf v1.23.0
go: downloading github.com/matttproud/golang_protobuf_extensions v1.0.1
go: downloading gopkg.in/ini.v1 v1.57.0
go: downloading github.com/minio/md5-simd v1.1.1
go: downloading github.com/rs/xid v1.2.1
go: downloading github.com/eapache/go-resiliency v1.2.0
go: downloading gopkg.in/jcmturner/gokrb5.v7 v7.5.0
go: downloading github.com/eapache/go-xerial-snappy v0.0.0-20180814174437-776d5712da21
go: downloading github.com/davecgh/go-spew v1.1.1
go: downloading github.com/rcrowley/go-metrics v0.0.0-20200313005456-10cdbea86bc0
go: downloading github.com/eapache/queue v1.1.0
go: downloading github.com/hashicorp/go-sockaddr v1.0.2
go: downloading github.com/ryanuber/go-glob v1.0.0
go: downloading google.golang.org/genproto v0.0.0-20190819201941-24fa4b261c55
go: downloading github.com/googleapis/gax-go/v2 v2.0.4
go: downloading go.opencensus.io v0.22.5
go: downloading github.com/klauspost/cpuid/v2 v2.0.4
go: downloading github.com/jcmturner/goidentity/v6 v6.0.1
go: downloading github.com/golang/groupcache v0.0.0-20190702054246-869f871628b6
go: downloading github.com/mailru/easyjson v0.7.6
go: downloading github.com/josharian/intern v1.0.0
go: downloading github.com/coreos/go-semver v0.2.0
go: downloading github.com/coreos/go-systemd v0.0.0-20180511133405-39ca1b05acc7
go: downloading github.com/coreos/pkg v0.0.0-20160727233714-3ac0863d7acf
go: downloading gopkg.in/jcmturner/dnsutils.v1 v1.0.1
go: downloading gopkg.in/jcmturner/aescts.v1 v1.0.1
go: downloading gopkg.in/jcmturner/rpc.v1 v1.1.0
# github.com/minio/minio/cmd
cmd/apierrorcode_string.go:23:7: invalid array index ErrInvalidCopyPartRange - 12 (out of bounds for 1-element array)
cmd/apierrorcode_string.go:24:7: invalid array index ErrInvalidCopyPartRangeSource - 13 (out of bounds for 1-element array)
cmd/apierrorcode_string.go:25:7: invalid array index ErrInvalidMaxKeys - 14 (out of bounds for 1-element array)
cmd/apierrorcode_string.go:26:7: invalid array index ErrInvalidEncodingMethod - 15 (out of bounds for 1-element array)
cmd/apierrorcode_string.go:27:7: invalid array index ErrInvalidMaxUploads - 16 (out of bounds for 1-element array)
cmd/apierrorcode_string.go:28:7: invalid array index ErrInvalidMaxParts - 17 (out of bounds for 1-element array)
cmd/apierrorcode_string.go:29:7: invalid array index ErrInvalidPartNumberMarker - 18 (out of bounds for 1-element array)
cmd/apierrorcode_string.go:30:7: invalid array index ErrInvalidPartNumber - 19 (out of bounds for 1-element array)
cmd/apierrorcode_string.go:31:7: invalid array index ErrInvalidRequestBody - 20 (out of bounds for 1-element array)
cmd/apierrorcode_string.go:32:7: invalid array index ErrInvalidCopySource - 21 (out of bounds for 1-element array)
cmd/apierrorcode_string.go:32:7: too many errors
make: *** [build] Error 2

```

**Review by vadmeste — APPROVED** [review]
LGTM

**Comment by minio-trusted** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-s3.sh | :heavy_check_mark: |
| mint-erasure.sh | :heavy_check_mark: |
| mint-dist-erasure.sh | :heavy_check_mark: |
| mint-zoned.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-compress-encrypt-dist-erasure.sh | :x: [more...](#8fbec5de-e8bc-4b2b-a288-10718502c1be) |
<a name="8fbec5de-e8bc-4b2b-a288-10718502c1be"></a>
### 11992-4dbcf3e/mint-compress-encrypt-dist-erasure.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-dev4.minio.io:31798
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp f33a8e80a346:/mint/log /tmp/mint-logs'

(1/15) Running aws-sdk-go tests ... done in 1 seconds
(2/15) Running aws-sdk-java tests ... done in 2 seconds
(3/15) Running aws-sdk-php tests ... done in 43 seconds
(4/15) Running aws-sdk-ruby tests ... done in 3 seconds
(5/15) Running awscli tests ... FAILED in 32 seconds
{
  "name": "awscli",
  "duration": 2560,
  "function": "aws --endpoint-url http://minio-dev4.minio.io:31798 s3api copy-object --bucket awscli-mint-test-bucket-22650 --key datafile-1-kB-copy --copy-source awscli-mint-test-bucket-22650/datafile-1-kB\n",
  "status": "FAIL",
  "error": "Hash mismatch expected 084e1383b70fb0c51acc680fef370023, got ac57de7156d7fc25ac1a65f81fa3989b"
}
(5/15) Running healthcheck tests ... done in 0 seconds
(6/15) Running mc tests ... done in 46 seconds
(7/15) Running minio-dotnet tests ... done in 34 seconds
(8/15) Running minio-go tests ... FAILED in 2 minutes and 6 seconds
{
  "args": {},
  "duration": 285,
  "error": "At least one of the pre-conditions you specified did not hold",
  "function": "CopyObjectPart(destination, source)",
  "message": "CopyObjectPart call failed",
  "name": "minio-go: testUnencryptedToSSES3CopyObjectPart",
  "status": "FAIL"
}
(8/15) Running minio-java tests ... FAILED in 1 minutes and 47 seconds
{
  "name": "minio-java",
  "function": "copyObject()",
  "args": "[match etag]",
  "duration": 302,
  "status": "FAIL",
  "error": "error occurred\nErrorResponse(code = PreconditionFailed, message = At least one of the pre-conditions you specified did not hold, bucketName = minio-java-test-hrepnc, objectName = minio-java-test-2aluis5-copy, resource = /minio-java-test-hrepnc/minio-java-test-2aluis5-copy, requestId = 1673AD1C4A71AA27, hostId = ee3de957-6610-46e5-9955-636318018d37)\nrequest={method=PUT, url=http://minio-dev4.minio.io:31798/minio-java-test-hrepnc/minio-java-test-2aluis5-copy, headers=x-amz-copy-source-if-match: 71cff0a060f852067e443ad1e24ae26c-1\nx-amz-copy-source: /minio-java-test-3pt1unb/minio-java-test-2aluis5\nHost: minio-dev4.minio.io:31798\nAccept-Encoding: identity\nUser-Agent: MinIO (Linux; amd64) minio-java/8.0.3\nContent-MD5: 1B2M2Y8AsgTpgAmY7PhCfg==\nx-amz-content-sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855\nx-amz-date: 20210407T202348Z\nAuthorization: AWS4-HMAC-SHA256 Credential=*REDACTED*/20210407/us-east-1/s3/aws4_request, SignedHeaders=content-md5;host;x-amz-content-sha256;x-amz-copy-source;x-amz-copy-source-if-match;x-amz-date, Signature=*REDACTED*\n}\nresponse={code=412, headers=Accept-Ranges: bytes\nContent-Length: 416\nContent-Security-Policy: block-all-mixed-content\nContent-Type: application/xml\nETag: \"71cff0a060f852067e443ad1e24ae26c\"\nLast-Modified: Wed, 07 Apr 2021 20:23:48 GMT\nServer: MinIO\nVary: Origin\nX-Amz-Request-Id: 1673AD1C4A71AA27\nX-Xss-Protection: 1; mode=block\nDate: Wed, 07 Apr 2021 20:23:48 GMT\n}\n >>> [io.minio.MinioClient.execute(MinioClient.java:775), io.minio.MinioClient.execute(MinioClient.java:563), io.minio.MinioClient.executePut(MinioClient.java:904), io.minio.MinioClient.copyObject(MinioClient.java:1232), FunctionalTest.testCopyObjectMatchETag(FunctionalTest.java:1850), FunctionalTest.copyObject(FunctionalTest.java:2016), FunctionalTest.runObjectTests(FunctionalTest.java:3757), FunctionalTest.runTests(FunctionalTest.java:3783), FunctionalTest.main(FunctionalTest.java:3927)]"
}
(8/15) Running minio-js tests ... done in 56 seconds
(9/15) Running minio-py tests ... done in 2 minutes and 59 seconds
(10/15) Running s3cmd tests ... FAILED in 5 seconds
{
  "name": "s3cmd",
  "duration": "2622",
  "function": "test_put_object_multipart",
  "status": "FAIL",
  "error": "WARNING: MD5 Sums don't match!\nWARNING: Retrying upload of /mint/data/datafile-65-MB\nWARNING: MD5 Sums don't match!\nWARNING: Retrying upload of /mint/data/datafile-65-MB\nWARNING: MD5 Sums don't match!\nWARNING: Retrying upload of /mint/data/datafile-65-MB\nWARNING: MD5 Sums don't match!\nWARNING: Retrying upload of /mint/data/datafile-65-MB\nWARNING: MD5 Sums don't match!\nWARNING: Retrying upload of /mint/data/datafile-65-MB\nWARNING: MD5 Sums don't match!\nWARNING: Too many failures. Giving up on '/mint/data/datafile-65-MB'\nERROR: \nUpload of '/mint/data/datafile-65-MB' part 1 failed. Use\n  /usr/local/bin/s3cmd abortmp s3://s3cmd-test-bucket-27144/s3cmd-test-object-5670 4fe11923-52e3-4bae-976d-ea7f5893aa14\nto abort the upload, or\n  /usr/local/bin/s3cmd --upload-id 4fe11923-52e3-4bae-976d-ea7f5893aa14 put ...\nto continue the upload.\nERROR: Upload of '/mint/data/datafile-65-MB' failed too many times (Last reason: )"
}
(10/15) Running s3select tests ... done in 5 seconds
(11/15) Running security tests ... done in 0 seconds

Executed 11 out of 15 tests successfully.
```
Deleting image on docker hub
Deleting image locally
