### PR TITLE
Change replication to use read lock instead of writelock

### LINKED ISSUE #12573: object not available after upload with asynchronous replication enabled
## Expected Behavior

Object to be accessible from main site immediately after upload. Secondary site to return 404 until the object gets replicated there. 

## Current Behavior

Object is not accessible in main site after upload until it gets replicated. Secondary site returns 404 for the object until it gets replicated there.

## Steps to Reproduce (for bugs)

1. create buckets with asynchronous replication:
2. mc mb site1/test
3. mc mb site2/test
4. mc version enable site1/test
5. mc version enable site2/test
6. mc admin bucket remote add site1/test https://user:pass@site2.somewere.net:9000/test --service "replication"
7. mc replicate add site1/test --remote-bucket test --arn 'arn:minio:replication::xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx:test' --replicate "delete,delete-marker"
8. upload large file. Size is irrelevant just big enough to have a time to test replication
9. mc cp 2Gfile.bin site1/test/
10. immediately copy back file after upload
11. mc cp site1/test/2Gfile.bin bigfile1.bin #this hangs until object gets replicated
12. mc cp site2/test/2Gfile.bin bigfile2.bin #this one returns "mc: <ERROR> Unable to validate source `site2/test/2Gfile.bin`." which is good

## Your Environment

* Version used (`minio --version`): Version: 2021-06-17T00:10:46Z
* Server setup and configuration: two baremetal clusters with 5 nodes each
* Operating System and version (`uname -a`): Linux tafl-serv1 5.4.0-74-generic 83-Ubuntu SMP Sat May 8 02:35:39 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

### PR DESCRIPTION
**Pull request by poornas**
Fixes #12573

This PR also adding audit logging for replication activity

## Motivation and Context
Currently replication holds a write lock for the duration of the transaction - this is unnecessary and can cause reads/stats to block until the write lock is released. Integrity of the transaction is guaranteed by the immutability of the object version.

Also adding audit logging for internal replication activity.
## How to test this PR?
See repro in referenced issue

## Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Optimization (provides speedup with no functional changes)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [ ] Fixes a regression (If yes, please add `commit-id` or `PR #` here)
- [ ] Documentation updated
- [ ] Unit tests added/updated

### CODE REVIEW

File: cmd/bucket-replication.go [hunk 1]
```diff
@@ -605,6 +605,12 @@ func getReplicationAction(oi1 ObjectInfo, oi2 minio.ObjectInfo) replicationActio
 // replicateObject replicates the specified version of the object to destination bucket
 // The source object is then updated to reflect the replication status.
 func replicateObject(ctx context.Context, ri ReplicateObjectInfo, objectAPI ObjectLayer) {
+	auditLogInternal(context.Background(), ri.Bucket, ri.Name, AuditLogOptions{
+		Trigger:   "replication-process",
```
Comment (harshavardhana) [inline cmd/bucket-replication.go]:
```suggestion
		Trigger:   "replication:incoming",
```

File: cmd/bucket-replication.go [hunk 2]
```diff
@@ -605,6 +605,12 @@ func getReplicationAction(oi1 ObjectInfo, oi2 minio.ObjectInfo) replicationActio
...
+		APIName:   "replicateObject",
```
Comment (harshavardhana) [inline cmd/bucket-replication.go]:
```suggestion
		APIName:   "s3:ReplicateObject",
```

File: cmd/bucket-replication.go [hunk 3]
```diff
@@ -690,23 +701,34 @@ func replicateObject(ctx context.Context, ri ReplicateObjectInfo, objectAPI Obje
 				if !ok {
 					return
 				}
+				gr.Close()
+				closeOnDefer = false
 				// This lower level implementation is necessary to avoid write locks from CopyObject.
 				poolIdx, err := z.getPoolIdx(ctx, bucket, object, objInfo.Size)
```
Comment (harshavardhana) [inline cmd/bucket-replication.go]: No reason to use `getPoolIdx()` @poornas you can simply remove the entire reflection code and directly called `PutObjectMetadata()`

File: cmd/bucket-replication.go [hunk 4]
```diff
@@ -690,23 +701,34 @@ func replicateObject(ctx context.Context, ri ReplicateObjectInfo, objectAPI Obje
...
-						fi.Metadata[xhttp.AmzObjectTagging] = objInfo.UserTags
+						popts.UserDefined[xhttp.AmzObjectTagging] = objInfo.UserTags
 					}
-					if err = z.serverPools[poolIdx].getHashedSet(object).updateObjectMeta(ctx, bucket, object, fi); err != nil {
+					if _, err = z.serverPools[poolIdx].getHashedSet(object).PutObjectMetadata(ctx, bucket, object, popts); err != nil {
 						logger.LogIf(ctx, fmt.Errorf("Unable to update replication metadata for %s/%s(%s): %w", bucket, objInfo.Name, objInfo.VersionID, err))
+					} else {
+						auditLogInternal(context.Background(), ri.Bucket, ri.Name, AuditLogOptions{
+							Trigger:   "replication-process",
+							APIName:   "replicateObject",
```
Comment (harshavardhana) [inline cmd/bucket-replication.go]: needs the same changes as above..

File: cmd/data-scanner.go [hunk 5]
```diff
@@ -1343,11 +1342,8 @@ func (d *dynamicSleeper) Update(factor float64, maxWait time.Duration) error {
...
-	entry := audit.NewEntry(globalDeploymentID)
-	entry.Trigger = "internal-scanner"
-	entry.API.Name = "DeleteObject"
-	entry.API.Bucket = bucket
-	entry.API.Object = object
-	ctx = logger.SetAuditEntry(ctx, &entry)
-	logger.AuditLog(ctx, nil, nil, nil)
+	auditLogInternal(ctx, bucket, object, AuditLogOptions{
+		Trigger: "internal-scanner",
+		APIName: "DeleteObject",
```
Comment (harshavardhana) [inline cmd/data-scanner.go]:
```suggestion
		APIName: "s3:ExpireObject",
```

File: cmd/bucket-replication.go [hunk 6]
```diff
@@ -1025,6 +1073,12 @@ func (p *ReplicationPool) queueReplicaTask(ri ReplicateObjectInfo) {
 			close(p.existingReplicaCh)
 		})
 	case ch <- ri:
+		auditLogInternal(context.Background(), ri.Bucket, ri.Name, AuditLogOptions{
+			Trigger:   qname,
+			APIName:   "replicateObject",
```
Comment (harshavardhana) [inline cmd/bucket-replication.go]:
```suggestion
			APIName:   "s3:ReplicateObject",
```

File: cmd/data-scanner.go [hunk 7]
```diff
@@ -1343,11 +1342,8 @@ func (d *dynamicSleeper) Update(factor float64, maxWait time.Duration) error {
...
 func auditLogLifecycle(ctx context.Context, bucket, object string) {
-	entry := audit.NewEntry(globalDeploymentID)
-	entry.Trigger = "internal-scanner"
-	entry.API.Name = "DeleteObject"
-	entry.API.Bucket = bucket
-	entry.API.Object = object
-	ctx = logger.SetAuditEntry(ctx, &entry)
-	logger.AuditLog(ctx, nil, nil, nil)
+	auditLogInternal(ctx, bucket, object, AuditLogOptions{
+		Trigger: "internal-scanner",
```
Comment (harshavardhana) [inline cmd/data-scanner.go]:
```suggestion
		Trigger: "ilm",
```

File: cmd/bucket-replication.go [hunk 8]
```diff
@@ -1033,10 +1087,15 @@ func (p *ReplicationPool) queueReplicaDeleteTask(doi DeletedObjectReplicationInf
...
 	}
+	qname := "replication-delete-queue"
 	var ch chan DeletedObjectReplicationInfo
 	switch doi.OpType {
 	case replication.ExistingObjectReplicationType:
 		ch = p.existingReplicaDeleteCh
+		qname = "replication-existing-delete-queue"
+	case replication.HealReplicationType:
+		ch = p.replicaDeleteCh
+		qname = "replication-healing"
```
Comment (harshavardhana) [inline cmd/bucket-replication.go]: all these strings should be constants @poornas

File: cmd/bucket-replication.go [hunk 9]
```diff
@@ -1011,9 +1054,14 @@ func (p *ReplicationPool) queueReplicaTask(ri ReplicateObjectInfo) {
...
 	}
 	var ch chan ReplicateObjectInfo
+	qname := "replication-queue"
 	switch ri.OpType {
 	case replication.ExistingObjectReplicationType:
 		ch = p.existingReplicaCh
+		qname = "replication-existing-queue"
+	case replication.HealReplicationType:
+		ch = p.replicaCh
+		qname = "replication-healing"
```
Comment (harshavardhana) [inline cmd/bucket-replication.go]:
```suggestion
		qname = "replication:heal"
```

File: cmd/bucket-replication.go [hunk 10]
```diff
@@ -1011,9 +1054,14 @@ func (p *ReplicationPool) queueReplicaTask(ri ReplicateObjectInfo) {
 		return
 	}
 	var ch chan ReplicateObjectInfo
+	qname := "replication-queue"
 	switch ri.OpType {
 	case replication.ExistingObjectReplicationType:
 		ch = p.existingReplicaCh
+		qname = "replication-existing-queue"
```
Comment (harshavardhana) [inline cmd/bucket-replication.go]:
```suggestion
		qname = "replication:existing"
```

File: cmd/bucket-replication.go [hunk 11]
```diff
@@ -1011,9 +1054,14 @@ func (p *ReplicationPool) queueReplicaTask(ri ReplicateObjectInfo) {
 		return
 	}
 	var ch chan ReplicateObjectInfo
+	qname := "replication-queue"
```
Comment (harshavardhana) [inline cmd/bucket-replication.go]:
```suggestion
	qname := "replication:incoming"
```

File: cmd/bucket-replication.go [hunk 12]
```diff
@@ -1002,6 +1039,12 @@ func (p *ReplicationPool) queueReplicaFailedTask(ri ReplicateObjectInfo) {
 			close(p.existingReplicaCh)
 		})
 	case p.mrfReplicaCh <- ri:
+		auditLogInternal(context.Background(), ri.Bucket, ri.Name, AuditLogOptions{
+			Trigger:   "replication-mrf-queue",
```
Comment (harshavardhana) [inline cmd/bucket-replication.go]:
```suggestion
			Trigger:   "replication:mrf",
```

File: cmd/bucket-replication.go [hunk 13]
```diff
@@ -790,14 +814,27 @@ func replicateObject(ctx context.Context, ri ReplicateObjectInfo, objectAPI Obje
...
+			popts.UserDefined[xhttp.AmzBucketReplicationStatus] = replication.Completed.String()
+			if objInfo.UserTags != "" {
+				popts.UserDefined[xhttp.AmzObjectTagging] = objInfo.UserTags
 			}
-			if err = z.serverPools[poolIdx].getHashedSet(object).updateObjectMeta(ctx, bucket, object, fi); err != nil {
+			if _, err = z.serverPools[poolIdx].getHashedSet(object).PutObjectMetadata(ctx, bucket, object, popts); err != nil {
 				logger.LogIf(ctx, fmt.Errorf("Unable to update replication metadata for %s/%s(%s): %w", bucket, objInfo.Name, objInfo.VersionID, err))
+			} else {
+				auditLogInternal(context.Background(), objInfo.Bucket, objInfo.Name, AuditLogOptions{
+					Trigger:   "replication-process",
```
Comment (harshavardhana) [inline cmd/bucket-replication.go]:
```suggestion
					Trigger:   "replication:incoming",
```

File: cmd/bucket-replication.go [hunk 14]
```diff
@@ -1048,6 +1107,16 @@ func (p *ReplicationPool) queueReplicaDeleteTask(doi DeletedObjectReplicationInf
 			close(p.existingReplicaDeleteCh)
 		})
 	case ch <- doi:
+		replStatus := doi.DeleteMarkerReplicationStatus
+		if doi.VersionPurgeStatus != "" {
+			replStatus = string(doi.VersionPurgeStatus)
+		}
+		auditLogInternal(context.Background(), doi.Bucket, doi.ObjectName, AuditLogOptions{
+			Trigger:   qname,
+			APIName:   "replicateDelete",
```
Comment (harshavardhana) [inline cmd/bucket-replication.go]:
```suggestion
			APIName:   "s3:ReplicateDelete",
```

**Review by harshavardhana — CHANGES_REQUESTED** [review]

**Comment by harshavardhana** [comment]
The reason I chose this `<sub-system>:[optional_location]` is to ensure that we follow S3 style strings in our audit formats, this would keep it easier to inter-operate between event targets as well as audit targets.  Nomenclature is already standardized lets not add our own newer meanings and try to keep it simpler.

**Comment by minio-trusted** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-erasure.sh | :heavy_check_mark: |
| mint-compress-encrypt-dist-erasure.sh | :heavy_check_mark: |
| mint-dist-erasure.sh | :heavy_check_mark: |
| mint-gateway-s3.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-zoned.sh | :heavy_check_mark: |
Deleting image on docker hub
Deleting image locally

File: cmd/data-scanner.go (hunk 7 above)
Comment (harshavardhana) [reply cmd/data-scanner.go]: This can be `ilm:expiry` and transition can have `ilm:transition` instead of `internal-scanner`

**Review by harshavardhana — CHANGES_REQUESTED** [review]

**Comment by minio-trusted** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-erasure.sh | :heavy_check_mark: |
| mint-compress-encrypt-dist-erasure.sh | :heavy_check_mark: |
| mint-dist-erasure.sh | :heavy_check_mark: |
| mint-gateway-s3.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-zoned.sh | :heavy_check_mark: |
Deleting image on docker hub
Deleting image locally

**Review by klauspost — APPROVED** [review]
Nice. Even reduces complexity 👍🏼

**Comment by klauspost** [comment]
```
cmd/bucket-replication.go:874:2: exported: exported const ReplicationQueuedActivity should have comment (or a comment on this block) or be unexported (revive)
	ReplicationQueuedActivity         = "replication:queue"
	^
```

**Comment by minio-trusted** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-s3.sh | :heavy_check_mark: |
| mint-erasure.sh | :heavy_check_mark: |
| mint-dist-erasure.sh | :heavy_check_mark: |
| mint-zoned.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-compress-encrypt-dist-erasure.sh | :heavy_check_mark: |
Deleting image on docker hub
Deleting image locally

**Comment by minio-trusted** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-s3.sh | :heavy_check_mark: |
| mint-erasure.sh | :heavy_check_mark: |
| mint-dist-erasure.sh | :heavy_check_mark: |
| mint-zoned.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-compress-encrypt-dist-erasure.sh | :heavy_check_mark: |
Deleting image on docker hub
Deleting image locally

**Review by harshavardhana — APPROVED** [review]

**Comment by hkirov** [comment]
Thanks.
