### PR TITLE
Fix JSON parser handling for certain objects

### LINKED ISSUE #7141: JSON parsing error
It seems that there is a parser error in the select part of the code. I try to run select over it, but it doesn't work. It also seems to be tied to number of entries, as it will go from returning all successfully to returning none successfully.

The file in question when you see bug.json is [https://gist.github.com/rHermes/007dddb88d5ad23f7c4365eb66adff22](url)

## Expected Behavior
```
$ for i in $(seq 10 10 100); do head -$i bug.json | mc pipe m1/test/bug-$i.json ; done
$ for i in $(seq 10 10 100); do  mc sql --query 'SELECT * FROM S3Object' m1/test/bug-$i.json | wc -l ; done
10
20
30
40
50
60
70
80
90
100
```

## Current Behavior

```
$ for i in $(seq 10 10 100); do head -$i bug.json | mc pipe m1/test/bug-$i.json ; done
$ for i in $(seq 10 10 100); do  mc sql --query 'SELECT * FROM S3Object' m1/test/bug-$i.json | wc -l ; done
10
20
30
40
50
60
70
mc: <ERROR> Unable to run sql Error Type of  Encountered an error parsing the JSON file. Check the file and try again.
28
mc: <ERROR> Unable to run sql Error Type of  Encountered an error parsing the JSON file. Check the file and try again.
32
mc: <ERROR> Unable to run sql Error Type of  Encountered an error parsing the JSON file. Check the file and try again.
35
```
## Possible Solution

I do not know where in the code this occurs, I've only just started using minio.

## Steps to Reproduce (for bugs)

1. `wget -O bug.json https://gist.githubusercontent.com/rHermes/007dddb88d5ad23f7c4365eb66adff22/raw/121b9362e2bde0beeee9cf9d063e705aef45c283/bug.json`
2. `mc mb m1/test`

## Context

I'm trying to use the Select API that minio provides.

## Regression

I don't know if it is.

## Your Environment

* Version used (`minio version`): Version : 2019-01-16T21:44:08Z
* Environment name and version (e.g. nginx 1.9.1): traefik setup with docker compose and 6 minio nodes
* Server type and version: Version : 2019-01-16T21:44:08Z
* Operating System and version (`uname -a`): `Linux mellow 4.19.11-arch1-1-ARCH #1 SMP PREEMPT Thu Dec 20 03:40:28 UTC 2018 x86_64 GNU/Linux`

### PR DESCRIPTION
**Pull request by harshavardhana**
## Description
Fix JSON parser handling for certain objects

## Motivation and Context
This PR also adds some comments and simplifies
the code. Primary handling is done to ensure
that we make sure to honor cached buffer.

Added unit tests as well

Fixes #7141

## Regression
No

## How Has This Been Tested?
Using the unit tests and certain specialized JSON files.

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have added unit tests to cover my changes.
- [ ] I have added/updated functional tests in [mint](https://github.com/minio/mint). (If yes, add `mint` PR # here: )
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by minio-ops** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-tls.sh | :heavy_check_mark: |
| mint-compression-xl.sh | :heavy_check_mark: |
| mint-xl.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-compression-fs.sh | :heavy_check_mark: |
| mint-worm.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-dist-xl.sh | :heavy_check_mark: |

**Comment by harshavardhana** [comment]
Can we add @balamurugana and @donatello to review this PR, previous iteration of this PR #7147 was being reviewed by them.

File: pkg/s3select/json/reader.go [hunk 1]
```diff
@@ -135,21 +161,7 @@ func (or *objectReader) Read(p []byte) (n int, err error) {
...
-	if or.p == nil {
-		or.p = p
-		or.start = index
-		or.end = n
-	} else {
-		or.start -= index
-	}
-
-	return index, nil
+	return or.updateState(p[:n]), nil
```
Comment (balamurugana) [inline pkg/s3select/json/reader.go]: 1. Playing with trimming may result in new slice creation (not for the end index, surely for start index, better it can be avoided).  That's the reason I didn't use this style previously.
2. `updateState()` is small and doesn't convey what it does by name i.e. its required to read the description.  IMO the logic needs to be in `Read()` itself
3. If `updateState()` is way to go, why can't it accept `n` as another argument?

Comment (harshavardhana) [reply pkg/s3select/json/reader.go]: Slicing a slice doesn't copy the slice https://blog.golang.org/go-slices-usage-and-internals it's quite common in Go so that's why I added this style, there is no reason to take `n` as an argument.

Comment (harshavardhana) [reply pkg/s3select/json/reader.go]: I would love to keep a proper name for it, my idea was to document the portion which has some intricate logic of maintaining offsets.

So suggest a good name though.

**Comment by minio-ops** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-tls.sh | :heavy_check_mark: |
| mint-compression-xl.sh | :heavy_check_mark: |
| mint-xl.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-compression-fs.sh | :heavy_check_mark: |
| mint-worm.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-dist-xl.sh | :heavy_check_mark: |

File: pkg/s3select/json/reader.go [hunk 2]
```diff
@@ -105,20 +106,45 @@ func (or *objectReader) objectEndIndex(p []byte, length int) int {
 	return -1
 }
 
+// Updates internal states depending on cached values etc.
+// This function updates start and end offsets of JSON objects
+// which is kept such that we can always properly return
+// right JSON objects.
+func (or *objectReader) updateState(p []byte, n int) int {
+	index := or.findEndIndex(p[:n])
```
Comment (balamurugana) [inline pkg/s3select/json/reader.go]: You could pass `p` and `n` to avoid trimming.

File: pkg/s3select/json/reader.go [hunk 3]
```diff
@@ -73,8 +73,9 @@ type objectReader struct {
 	endOfObject bool
 }
 
-func (or *objectReader) objectEndIndex(p []byte, length int) int {
-	for i := 0; i < length; i++ {
+// Returns the location of the end curly braces in a given buffer.
+func (or *objectReader) findEndIndex(p []byte) int {
```
Comment (balamurugana) [inline pkg/s3select/json/reader.go]: The idea of the function name is from `strings.Index()`.  If `objectEndIndex()` is confusing, you could have `jsonEndIndex()` or simply `endIndex()` i.e. no need to have `find` and `index` together.

File: pkg/s3select/json/reader_test.go [hunk 4]
```diff
@@ -0,0 +1,49 @@
...
+	if err != nil {
+		t.Fatal(err)
+	}
+	for _, file := range files {
+		f, err := os.Open(filepath.Join("data", file.Name()))
+		if err != nil {
+			t.Fatal(err)
+		}
+		r := NewReader(f, &ReaderArgs{})
+		for {
```
Comment (balamurugana) [inline pkg/s3select/json/reader_test.go:38]: You would need to do
```go
for err == nil {
    if err = r.Reset(); err == nil {
        _, err = r.Read()
    }
}
```

File: pkg/s3select/json/reader.go (hunk 2 above)
Comment (harshavardhana) [reply pkg/s3select/json/reader.go]: In this scenario trimming is fine, as we are not interested in the entire p. You only read upto `n` as per implementation.

File: pkg/s3select/json/reader.go (hunk 3 above)
Comment (harshavardhana) [reply pkg/s3select/json/reader.go]: I prefer endIndex(), but notice strings.Index takes an argument.

File: pkg/s3select/json/reader_test.go (hunk 4 above)
Comment (harshavardhana) [reply pkg/s3select/json/reader_test.go:38]: Why is that a requirement ?

Comment (harshavardhana) [reply pkg/s3select/json/reader_test.go:38]: AFAICS Reset() is called for every Read()

**Comment by minio-ops** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-tls.sh | :heavy_check_mark: |
| mint-compression-xl.sh | :heavy_check_mark: |
| mint-xl.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-compression-fs.sh | :heavy_check_mark: |
| mint-worm.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-dist-xl.sh | :heavy_check_mark: |

**Comment by harshavardhana** [comment]
Added support for JSON objects with `[` `]` just like how AWS S3 would support.

**Comment by minio-ops** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-tls.sh | :heavy_check_mark: |
| mint-compression-xl.sh | :heavy_check_mark: |
| mint-xl.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-compression-fs.sh | :heavy_check_mark: |
| mint-worm.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-dist-xl.sh | :heavy_check_mark: |

**Comment by minio-ops** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-tls.sh | :heavy_check_mark: |
| mint-compression-xl.sh | :heavy_check_mark: |
| mint-xl.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-compression-fs.sh | :heavy_check_mark: |
| mint-worm.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-dist-xl.sh | :heavy_check_mark: |

**Comment by minio-ops** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-tls.sh | :heavy_check_mark: |
| mint-compression-xl.sh | :heavy_check_mark: |
| mint-xl.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-compression-fs.sh | :heavy_check_mark: |
| mint-worm.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-dist-xl.sh | :heavy_check_mark: |

**Comment by harshavardhana** [comment]
Added three commits @balamurugana  

- Add vendored jstream
- Add Value struct which includes type
- Fix JSON parser handling for certain objects

Top second one gives you the diff of upstream change and last one tells about how this package is used.

**Comment by minio-ops** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-tls.sh | :heavy_check_mark: |
| mint-compression-xl.sh | :heavy_check_mark: |
| mint-xl.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-compression-fs.sh | :heavy_check_mark: |
| mint-worm.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-dist-xl.sh | :heavy_check_mark: |

**Comment by harshavardhana** [comment]
A PR has been sent upstream https://github.com/bcicen/jstream/pull/1

**Comment by minio-ops** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-tls.sh | :heavy_check_mark: |
| mint-compression-xl.sh | :heavy_check_mark: |
| mint-xl.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-compression-fs.sh | :heavy_check_mark: |
| mint-worm.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-dist-xl.sh | :heavy_check_mark: |

File: pkg/s3select/json/reader.go [hunk 5]
```diff
@@ -17,184 +17,39 @@
...
 
-	if !gjson.ValidBytes(data) {
-		return nil, errJSONParsingError(err)
+	var data []byte
+	var err error
+	if v.ValueType != jstream.Object {
+		var json []byte
+		data, err = sjson.SetBytes(json, "_1", v.Value)
+	} else {
+		data, err = json.Marshal(v.Value)
```
Comment (balamurugana) [inline pkg/s3select/json/reader.go:51]: Can't we just do `json.Marshal(v.Value)` in all cases?

Comment (harshavardhana) [reply pkg/s3select/json/reader.go:51]: No we cannot its specifically added for AWS S3 compatible output @balamurugana

**Comment by minio-ops** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-tls.sh | :heavy_check_mark: |
| mint-compression-xl.sh | :heavy_check_mark: |
| mint-xl.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-compression-fs.sh | :heavy_check_mark: |
| mint-worm.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-dist-xl.sh | :heavy_check_mark: |

**Comment by minio-ops** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-tls.sh | :heavy_check_mark: |
| mint-compression-xl.sh | :heavy_check_mark: |
| mint-xl.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-compression-fs.sh | :heavy_check_mark: |
| mint-worm.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-dist-xl.sh | :heavy_check_mark: |

**Comment by minio-ops** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-tls.sh | :heavy_check_mark: |
| mint-xl.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-compression-fs.sh | :heavy_check_mark: |
| mint-worm.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-dist-xl.sh | :heavy_check_mark: |
| mint-compression-xl.sh | :x: [more...](#1a931a98-c2dd-44de-8f7a-1a3a9bd563c9) |
<a name="1a931a98-c2dd-44de-8f7a-1a3a9bd563c9"></a>
### 7162-83c1a2b/mint-compression-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      minikube:32753
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 03389143fa9e:/mint/log /tmp/mint-logs'

(1/13) Running awscli tests ... done in 4 minutes and 0 seconds
(2/13) Running aws-sdk-go tests ... done in 0 seconds
(3/13) Running aws-sdk-java tests ... done in 7 seconds
(4/13) Running aws-sdk-php tests ... done in 44 seconds
(5/13) Running aws-sdk-ruby tests ... done in 6 seconds
(6/13) Running mc tests ... done in 47 seconds
(7/13) Running minio-dotnet tests ... FAILED in 2 minutes and 43 seconds

Unhandled Exception: System.AggregateException: One or more errors occurred. (One or more errors occurred. (Minio API responded with message=Please reduce your request)) ---> System.AggregateException: One or more errors occurred. (Minio API responded with message=Please reduce your request) ---> Minio.Exceptions.MinioException: Minio API responded with message=Please reduce your request
   at Minio.MinioClient.ParseError(IRestResponse response) in /q/.q/sources/minio-dotnet/Minio/MinioClient.cs:line 371
   at Minio.MinioClient.HandleIfErrorResponse(IRestResponse response, IEnumerable`1 handlers, DateTime startTime) in /q/.q/sources/minio-dotnet/Minio/MinioClient.cs:line 513
   at Minio.MinioClient.ExecuteTaskAsync(IEnumerable`1 errorHandlers, IRestRequest request, CancellationToken cancellationToken) in /q/.q/sources/minio-dotnet/Minio/MinioClient.cs:line 359
   at Minio.MinioClient.PutObjectAsync(String bucketName, String objectName, String uploadId, Int32 partNumber, Byte[] data, Dictionary`2 metaData, Dictionary`2 sseHeaders, CancellationToken cancellationToken) in /q/.q/sources/minio-dotnet/Minio/ApiEndpoints/ObjectOperations.cs:line 492
   at Minio.MinioClient.PutObjectAsync(String bucketName, String objectName, Stream data, Int64 size, String contentType, Dictionary`2 metaData, ServerSideEncryption sse, CancellationToken cancellationToken) in /q/.q/sources/minio-dotnet/Minio/ApiEndpoints/ObjectOperations.cs:line 254
   at Minio.Functional.Tests.FunctionalTest.PutObject_Task(MinioClient minio, String bucketName, String objectName, String fileName, String contentType, Int64 size, Dictionary`2 metaData, MemoryStream mstream) in /mint/run/core/minio-dotnet/FunctionalTest.cs:line 923
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.Wait()
   at Minio.Functional.Tests.FunctionalTest.RemoveObjects_Test2(MinioClient minio) in /mint/run/core/minio-dotnet/FunctionalTest.cs:line 2134
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.Wait()
   at Minio.Functional.Tests.FunctionalTest.Main(String[] args) in /mint/run/core/minio-dotnet/FunctionalTest.cs:line 221

Executed 6 out of 13 tests successfully.
```

**Comment by minio-ops** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-tls.sh | :heavy_check_mark: |
| mint-compression-xl.sh | :heavy_check_mark: |
| mint-xl.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-compression-fs.sh | :heavy_check_mark: |
| mint-worm.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-dist-xl.sh | :heavy_check_mark: |

**Comment by minio-ops** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-tls.sh | :heavy_check_mark: |
| mint-compression-xl.sh | :heavy_check_mark: |
| mint-xl.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-compression-fs.sh | :heavy_check_mark: |
| mint-worm.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-dist-xl.sh | :heavy_check_mark: |

File: pkg/s3select/json/data/1.json [hunk 6]
```diff
@@ -0,0 +1,250 @@
...
+{"id":"8819737519"}
+{"id":"8819737520"}
+{"id":"8819737522"}
+{"id":"8819737525"}
+{"id":"8819737528"}
+{"id":"8819737531"}
+{"id":"8819737533"}
+{"id":"8819737535"}
+{"id":"8819737537"}
+{"id":"8819737539"}
```
Comment (donatello) [inline pkg/s3select/json/data/1.json]: Any benefit to having a 250 line dummy data file? Can we not work with shorter?

File: pkg/s3select/json/reader_test.go [hunk 7]
```diff
@@ -0,0 +1,49 @@
...
+	"path/filepath"
+	"testing"
+)
+
+func TestNewReader(t *testing.T) {
+	files, err := ioutil.ReadDir("data")
+	if err != nil {
+		t.Fatal(err)
+	}
+	for _, file := range files {
```
Comment (donatello) [inline pkg/s3select/json/reader_test.go:32]: Are you using a directory of files for tests so that you get `io.ReadCloser`? I would prefer to embed the json content in this source file itself, and write a simple ReadCloser instance for string (or an alias of string) - this way it will be more apparent what cases are being tested (and easier to find).

**Review by donatello — CHANGES_REQUESTED** [review]

File: pkg/s3select/json/data/1.json (hunk 6 above)
Comment (harshavardhana) [reply pkg/s3select/json/data/1.json]: No 250 is to address a bug, we would only list the first 20 lines in master for this json.

File: pkg/s3select/json/reader_test.go (hunk 7 above)
Comment (harshavardhana) [reply pkg/s3select/json/reader_test.go:32]: they are easier to find even now, its a collection of files to test this @donatello - I don't like the idea of embedding files inside source.

File: pkg/s3select/json/reader.go [hunk 8]
```diff
@@ -17,186 +17,49 @@
...
-		return nil, errJSONParsingError(err)
-	}
+	var data []byte
+	var err error
 
-	data = bytes.TrimSpace(data)
-	if len(data) == 0 {
-		return nil, io.EOF
+	if v.ValueType == jstream.Object {
+		data, err = json.Marshal(v.Value)
```
Comment (donatello) [inline pkg/s3select/json/reader.go:51]: This "re-marshalling" is a problem - it ends up re-ordering the keys from the input.

```shell
$ mc cat mys3/sqlselectapi/1.json
{ "Id" : 1, "name" : "q", "color" : "blue" }
{ "name" : "q", "color" : "blue" ,"Id" : 2}
{ "color" : "blue" ,"name" : "q",  "Id" : 3}
{ "Id" : 4 , "name" : "q", "color" : "blue", "Tele": "iphone" }
$ mc sql --query 'select * from s3object s' mys3/sqlselectapi/1.json
{"Id":1,"name":"q","color":"blue"}
{"name":"q","color":"blue","Id":2}
{"color":"blue","name":"q","Id":3}
{"Id":4,"name":"q","color":"blue","Tele":"iphone"}
$ mc sql --query 'select * from s3object s' myminio/sqlselectapi/1.json
{"Id":1,"color":"blue","name":"q"}
{"Id":2,"color":"blue","name":"q"}
{"Id":3,"color":"blue","name":"q"}
{"Id":4,"Tele":"iphone","color":"blue","name":"q"}
```

**Review by donatello — CHANGES_REQUESTED** [review]

File: pkg/s3select/json/reader.go (hunk 8 above)
Comment (harshavardhana) [reply pkg/s3select/json/reader.go:51]: So I discussed this @donatello since S3 also modifies the data, we don't need to comply with the order of keys. The output here is JSON and doesn't have a predefined order, to begin with. Since we cannot guarantee that order in the first place.

Comment (harshavardhana) [reply pkg/s3select/json/reader.go:51]: So the output is expected and we will be fine.

File: pkg/s3select/json/data/1.json (hunk 6 above)
Comment (donatello) [reply pkg/s3select/json/data/1.json]: Hmm, ok, but having a long file does not really help as it does not prove that the bug is fixed on even longer files. I do not understand the problem with the original code, but it may be possible to create a minimal test case. Even if not, it is better to simply write tests for the requirement and implementation rather than an older bug. Over time, this file is just dead-weight, as we won't really care about old bugs after a correct implementation emerges.

Comment (donatello) [reply pkg/s3select/json/data/1.json]: Another point is that if it really is needed to test with such a long file, a few lines of code can generate this content quite easily.

File: pkg/s3select/json/reader_test.go (hunk 7 above)
Comment (donatello) [reply pkg/s3select/json/reader_test.go:32]: With backtick raw strings, there is no real friction in embedding them in source code (no escaping needed).

File: pkg/s3select/json/data/1.json (hunk 6 above)
Comment (harshavardhana) [reply pkg/s3select/json/data/1.json]: > Hmm, ok, but having a long file does not really help as it does not prove that the bug is fixed on even longer files. I do not understand the problem with the original code, but it may be possible to create a minimal test case. Even if not, it is better to simply write tests for the requirement and implementation rather than an older bug. Over time, this file is just dead-weight, as we won't really care about old bugs after a correct implementation emerges.

We are not even using the original code. I can simply remove this file as its not really needed, we have other files with obscure looking JSON. 

> Another point is that if it really is needed to test with such a long file, a few lines of code can generate this content quite easily.

I don't like to generate files for this, it's just good to see actual JSON files and use them when reproducing issues - it is perfectly alright to keep these files since these are variations which are rare to find. 

I will remove the 250 line file as it's not needed with the library anymore.

File: pkg/s3select/json/reader_test.go (hunk 7 above)
Comment (harshavardhana) [reply pkg/s3select/json/reader_test.go:32]: It's not about that it's about being able to use `mc cp` to copy them to test it. It's annoying if its embedded inside the test.

File: pkg/s3select/json/reader.go [hunk 9]
```diff
@@ -17,186 +17,49 @@
...
+	} else {
+		// To be AWS S3 compatible
+		// Select for JSON needs to output non-object JSON as single column value
+		// i.e. a map with `_1` as key and value as the non-object.
+		var json []byte
+		data, err = sjson.SetBytes(json, "_1", v.Value)
```
Comment (balamurugana) [inline pkg/s3select/json/reader.go]: you could just do `sjson.SetBytes(data, ...)`

File: pkg/s3select/json/reader.go [hunk 10]
```diff
@@ -17,186 +17,49 @@
...
-
-	return or.err
-}
-
 // Reader - JSON record reader for S3Select.
 type Reader struct {
 	args         *ReaderArgs
-	objectReader *objectReader
+	decoder      *jstream.Decoder
+	objectReader chan *jstream.MetaValue
```
Comment (balamurugana) [inline pkg/s3select/json/reader.go]: `objectReader` is no sense actually as we support any JSON value not limiting to JSON object.

Comment (harshavardhana) [reply pkg/s3select/json/reader.go]: done

File: pkg/s3select/json/reader.go (hunk 9 above)
Comment (harshavardhana) [reply pkg/s3select/json/reader.go]: done

File: pkg/s3select/json/reader.go (hunk 8 above)
Comment (donatello) [reply pkg/s3select/json/reader.go:51]: No, S3's implementation only removes whitespace, but keeps the input ordering. This distinction is important - S3 mentions this quite clearly in the documentation, quoting from [here](https://docs.aws.amazon.com/AmazonS3/latest/dev/s3-glacier-select-sql-reference-select.html):

> The first form with * (asterisk) returns every row that passed the WHERE clause, as-is.

If the user requests CSV output serialization, this behavior will cause the server to return garbage:

```
$ mc cat mys3/sqlselectapi/7.json
{"name":"q","Id":1,"color":"blue"}
{"name":"s","Id":2,"color":"blue"}
{"name":"t","Id":3,"color":"blue"}
$ mc sql --query 'select * from s3object s' mys3/sqlselectapi/7.json
{"name":"q","Id":1,"color":"blue"}
{"name":"s","Id":2,"color":"blue"}
{"name":"t","Id":3,"color":"blue"}
$ mc sql --query 'select * from s3object s' myminio/sqlselectapi/7.json
{"Id":1,"color":"blue","name":"q"}
{"Id":2,"color":"blue","name":"s"}
{"Id":3,"color":"blue","name":"t"}
```

Imagine the last two commands above requiring CSV output. It will be junk if the application assumes S3 behaviour.

Comment (harshavardhana) [reply pkg/s3select/json/reader.go:51]: @donatello - why would it be junk? can you show me how it will be junk?

Comment (donatello) [reply pkg/s3select/json/reader.go:51]: I mean in CSV output, for the above file, S3 would give:

```
q,1,blue
s,2,blue
t,3,blue
```

We would give:

```
1,blue,q
2,blue,s
3,blue,t
```

Now the application that is expecting S3 behaviour is expecting to see Id (numeric) column as the second one, but minio returns it as the first one, and it does not work. 

The only "predictable" ordering is to keep it the same as the input (other than sorting of course, but that is significantly more expensive and not the route that S3 chose).

**Comment by minio-ops** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-tls.sh | :heavy_check_mark: |
| mint-compression-xl.sh | :heavy_check_mark: |
| mint-xl.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-compression-fs.sh | :heavy_check_mark: |
| mint-worm.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-dist-xl.sh | :heavy_check_mark: |

File: pkg/s3select/json/reader.go (hunk 8 above)
Comment (harshavardhana) [reply pkg/s3select/json/reader.go:51]: To put this to rest fixed the output order @donatello - PTAL

**Comment by minio-ops** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-tls.sh | :heavy_check_mark: |
| mint-compression-xl.sh | :heavy_check_mark: |
| mint-xl.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-compression-fs.sh | :heavy_check_mark: |
| mint-worm.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-dist-xl.sh | :heavy_check_mark: |

**Review by donatello — CHANGES_REQUESTED** [review]
There still appears to be a bug:

```shell
$ mc cat mys3/sqlselectapi/8.json
{"name":"q","Id":1,"color": {"name":"q","Id":1}}
{"name":"s","Id":2,"color": {"id": "ok", "name":"q","Id":2}}
{"name":"t","Id":3,"color": {"Id":3, "name":"q"}}
$ mc sql --query 'select * from s3object s' mys3/sqlselectapi/8.json
{"name":"q","Id":1,"color":{"name":"q","Id":1}}
{"name":"s","Id":2,"color":{"id":"ok","name":"q","Id":2}}
{"name":"t","Id":3,"color":{"Id":3,"name":"q"}}
$ mc sql --query 'select * from s3object s' myminio/sqlselectapi/8.json
{"name":"q","Id":1,"color":[{"key":"name","value":"q"},{"key":"Id","value":1}]}
{"name":"s","Id":2,"color":[{"key":"id","value":"ok"},{"key":"name","value":"q"},{"key":"Id","value":2}]}
{"name":"t","Id":3,"color":[{"key":"Id","value":3},{"key":"name","value":"q"}]}
```

**Comment by minio-ops** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-tls.sh | :heavy_check_mark: |
| mint-compression-xl.sh | :heavy_check_mark: |
| mint-xl.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-compression-fs.sh | :heavy_check_mark: |
| mint-worm.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-dist-xl.sh | :heavy_check_mark: |

**Comment by minio-ops** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-tls.sh | :heavy_check_mark: |
| mint-compression-xl.sh | :heavy_check_mark: |
| mint-xl.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-compression-fs.sh | :heavy_check_mark: |
| mint-worm.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-dist-xl.sh | :x: [more...](#12386698-7233-49dc-bef4-37feb7f46881) |
<a name="12386698-7233-49dc-bef4-37feb7f46881"></a>
### 7162-55aa968/mint-dist-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      minikube:32181
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 8c7cb5634345:/mint/log /tmp/mint-logs'

(1/13) Running awscli tests ... done in 2 minutes and 33 seconds
(2/13) Running aws-sdk-go tests ... done in 0 seconds
(3/13) Running aws-sdk-java tests ... done in 2 seconds
(4/13) Running aws-sdk-php tests ... done in 49 seconds
(5/13) Running aws-sdk-ruby tests ... done in 10 seconds
(6/13) Running mc tests ... done in 56 seconds
(7/13) Running minio-dotnet tests ... FAILED in 5 minutes and 16 seconds

Unhandled Exception: System.AggregateException: One or more errors occurred. (Assert.Fail failed. ) ---> Microsoft.VisualStudio.TestTools.UnitTesting.AssertFailedException: Assert.Fail failed. 
   at Microsoft.VisualStudio.TestTools.UnitTesting.Assert.HandleFail(String assertionName, String message, Object[] parameters)
   at Minio.Functional.Tests.FunctionalTest.<>c.<ListIncompleteUpload_Test2>b__92_1(Exception ex) in /mint/run/core/minio-dotnet/FunctionalTest.cs:line 2534
   at System.Reactive.AutoDetachObserver`1.OnErrorCore(Exception exception) in D:\a\1\s\Rx.NET\Source\src\System.Reactive\Internal\AutoDetachObserver.cs:line 76
   at System.Reactive.AnonymousSafeObserver`1.OnError(Exception error) in D:\a\1\s\Rx.NET\Source\src\System.Reactive\AnonymousSafeObserver.cs:line 62
   at System.Reactive.Linq.ObservableImpl.Throw`1._.Invoke() in D:\a\1\s\Rx.NET\Source\src\System.Reactive\Linq\Observable\Throw.cs:line 42
   at System.Reactive.Concurrency.Scheduler.Invoke(IScheduler scheduler, Action action) in D:\a\1\s\Rx.NET\Source\src\System.Reactive\Concurrency\Scheduler.Simple.cs:line 83
   at System.Reactive.Producer`2.SubscribeRaw(IObserver`1 observer, Boolean enableSafeguard) in D:\a\1\s\Rx.NET\Source\src\System.Reactive\Internal\Producer.cs:line 127
   at System.Reactive.Linq.QueryLanguage.<>c__DisplayClass330_0`1.<Create>b__0(IObserver`1 observer) in D:\a\1\s\Rx.NET\Source\src\System.Reactive\Linq\QueryLanguage.Creation.cs:line 46
   at System.Reactive.AnonymousObservable`1.SubscribeCore(IObserver`1 observer) in D:\a\1\s\Rx.NET\Source\src\System.Reactive\AnonymousObservable.cs:line 37
   at System.Reactive.ObservableBase`1.ScheduledSubscribe(IScheduler _, AutoDetachObserver`1 autoDetachObserver) in D:\a\1\s\Rx.NET\Source\src\System.Reactive\ObservableBase.cs:line 82
   at System.Reactive.Concurrency.CurrentThreadScheduler.Trampoline.Run(SchedulerQueue`1 queue) in D:\a\1\s\Rx.NET\Source\src\System.Reactive\Concurrency\CurrentThreadScheduler.cs:line 126
   at System.Reactive.Concurrency.CurrentThreadScheduler.Schedule[TState](TState state, TimeSpan dueTime, Func`3 action) in D:\a\1\s\Rx.NET\Source\src\System.Reactive\Concurrency\CurrentThreadScheduler.cs:line 94
   at System.Reactive.ObservableBase`1.Subscribe(IObserver`1 observer) in D:\a\1\s\Rx.NET\Source\src\System.Reactive\ObservableBase.cs:line 51
   at Minio.Functional.Tests.FunctionalTest.ListIncompleteUpload_Test2(MinioClient minio) in /mint/run/core/minio-dotnet/FunctionalTest.cs:line 2532
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.Wait()
   at Minio.Functional.Tests.FunctionalTest.Main(String[] args) in /mint/run/core/minio-dotnet/FunctionalTest.cs:line 244

Executed 6 out of 13 tests successfully.
```

**Comment by minio-ops** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-tls.sh | :heavy_check_mark: |
| mint-compression-xl.sh | :heavy_check_mark: |
| mint-xl.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-compression-fs.sh | :heavy_check_mark: |
| mint-worm.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-dist-xl.sh | :heavy_check_mark: |

**Comment by minio-ops** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-compression-xl.sh | :heavy_check_mark: |
| mint-xl.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-compression-dist-xl.sh | :heavy_check_mark: |
| mint-compression-fs.sh | :heavy_check_mark: |
| mint-worm.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-dist-xl.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :x: [more...](#37bb417a-1290-4015-acf4-b3aed81e36fe) |
<a name="37bb417a-1290-4015-acf4-b3aed81e36fe"></a>
### 7162-600bd69/mint-gateway-nas.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.52:31001
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 3a11d2b68ae9:/mint/log /tmp/mint-logs'

(1/13) Running aws-sdk-go tests ... FAILED in 0 seconds
{
  "alert": "",
  "args": {
    "bucketName": "aws-sdk-go-test-2n216a4avpodsf",
    "expiry": 60000000000,
    "objectName": "presignedTest"
  },
  "duration": 23,
  "error": "NoSuchBucket: The specified bucket does not exist\n\tstatus code: 404, request id: 15806A99777C43D1, host id: ",
  "function": "PresignedPut",
  "message": "AWS SDK Go DeleteBucket Failed",
  "name": "aws-sdk-go",
  "status": "FAIL"
}

Executed 0 out of 13 tests successfully.
```

File: pkg/s3select/json/reader.go [hunk 11]
```diff
@@ -17,184 +17,82 @@
...
-	}
+	var data []byte
+	var err error
 
-	if bytes.Count(data, []byte("\n")) > 0 {
-		var s string
-		if s, err = toSingleLineJSON("", "", gjson.ParseBytes(data)); err != nil {
-			return nil, errJSONParsingError(err)
+	if v.ValueType == jstream.Object {
+		kvs := v.Value.([]jstream.KV)
```
Comment (donatello) [inline pkg/s3select/json/reader.go]: Can directly call marshalJSONOrderly here

**Comment by minio-ops** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-compression-xl.sh | :heavy_check_mark: |
| mint-xl.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-compression-dist-xl.sh | :heavy_check_mark: |
| mint-compression-fs.sh | :heavy_check_mark: |
| mint-worm.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-dist-xl.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :x: [more...](#c9148110-a2bf-4102-80a3-5d0387cf3157) |
<a name="c9148110-a2bf-4102-80a3-5d0387cf3157"></a>
### 7162-976b216/mint-gateway-nas.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.52:30630
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 316bdfd1af93:/mint/log /tmp/mint-logs'

(1/13) Running aws-sdk-go tests ... done in 0 seconds
(2/13) Running aws-sdk-java tests ... done in 0 seconds
(3/13) Running aws-sdk-php tests ... done in 41 seconds
(4/13) Running aws-sdk-ruby tests ... FAILED in 2 seconds
{
  "name": "aws-sdk-ruby",
  "function": "presignedPut(bucket_name,file_name)",
  "args": {
    "bucket_name": "aws-sdk-ruby-bucket-bd0251999121",
    "file_name": "datafile-1-MB"
  },
  "duration": 23.8,
  "error": "Connection reset by peer",
  "status": "FAIL"
}

Executed 3 out of 13 tests successfully.
```

File: pkg/s3select/json/reader.go [hunk 12]
```diff
@@ -17,184 +17,52 @@
...
+	var data []byte
+	var err error
 
-	if bytes.Count(data, []byte("\n")) > 0 {
-		var s string
-		if s, err = toSingleLineJSON("", "", gjson.ParseBytes(data)); err != nil {
-			return nil, errJSONParsingError(err)
+	if v.ValueType == jstream.Object {
+		kvs := v.Value.(jstream.KVS)
+		if len(kvs) == 0 {
```
Comment (donatello) [inline pkg/s3select/json/reader.go]: Empty object is also handled in jstream!

**Comment by minio-ops** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-compression-xl.sh | :heavy_check_mark: |
| mint-xl.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-compression-dist-xl.sh | :heavy_check_mark: |
| mint-compression-fs.sh | :heavy_check_mark: |
| mint-worm.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-dist-xl.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :x: [more...](#8a162cb2-7ce4-4f8d-bf5f-9a83d2bdbc79) |
<a name="8a162cb2-7ce4-4f8d-bf5f-9a83d2bdbc79"></a>
### 7162-58501ea/mint-gateway-nas.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.58:30456
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 6f0d93d2a5d8:/mint/log /tmp/mint-logs'

(1/13) Running aws-sdk-go tests ... done in 0 seconds
(2/13) Running aws-sdk-java tests ... done in 1 seconds
(3/13) Running aws-sdk-php tests ... done in 40 seconds
(4/13) Running aws-sdk-ruby tests ... FAILED in 2 seconds
{
  "name": "aws-sdk-ruby",
  "function": "presignedPut(bucket_name,file_name)",
  "args": {
    "bucket_name": "aws-sdk-ruby-bucket-159785e61e28",
    "file_name": "datafile-1-MB"
  },
  "duration": 21.08,
  "error": "Connection reset by peer",
  "status": "FAIL"
}

Executed 3 out of 13 tests successfully.
```

File: pkg/s3select/json/reader.go (hunk 12 above)
Comment (harshavardhana) [reply pkg/s3select/json/reader.go]: I know neat! - changed

**Comment by minio-ops** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-compression-xl.sh | :heavy_check_mark: |
| mint-xl.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-compression-dist-xl.sh | :heavy_check_mark: |
| mint-compression-fs.sh | :heavy_check_mark: |
| mint-worm.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-dist-xl.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :x: [more...](#8782e2d1-6ab6-495f-b020-051499020b16) |
<a name="8782e2d1-6ab6-495f-b020-051499020b16"></a>
### 7162-4227e5a/mint-gateway-nas.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.58:30989
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 659653a2b712:/mint/log /tmp/mint-logs'

(1/13) Running aws-sdk-go tests ... done in 0 seconds
(2/13) Running aws-sdk-java tests ... done in 1 seconds
(3/13) Running aws-sdk-php tests ... done in 41 seconds
(4/13) Running aws-sdk-ruby tests ... FAILED in 2 seconds
{
  "name": "aws-sdk-ruby",
  "function": "presignedPut(bucket_name,file_name)",
  "args": {
    "bucket_name": "aws-sdk-ruby-bucket-1bd89ba9e210",
    "file_name": "datafile-1-MB"
  },
  "duration": 25.85,
  "error": "Connection reset by peer",
  "status": "FAIL"
}

Executed 3 out of 13 tests successfully.
```

**Review by donatello — APPROVED** [review]

**Comment by minio-ops** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-compression-xl.sh | :heavy_check_mark: |
| mint-xl.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-compression-dist-xl.sh | :heavy_check_mark: |
| mint-compression-fs.sh | :heavy_check_mark: |
| mint-worm.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-dist-xl.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :x: [more...](#08cd034a-4b5b-4916-9bf1-2aa3c90b6c87) |
<a name="08cd034a-4b5b-4916-9bf1-2aa3c90b6c87"></a>
### 7162-a20a58c/mint-gateway-nas.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.56:30954
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp eb1b1bd1efe4:/mint/log /tmp/mint-logs'

(1/13) Running aws-sdk-go tests ... done in 0 seconds
(2/13) Running aws-sdk-java tests ... done in 1 seconds
(3/13) Running aws-sdk-php tests ... done in 41 seconds
(4/13) Running aws-sdk-ruby tests ... FAILED in 2 seconds
{
  "name": "aws-sdk-ruby",
  "function": "presignedPost(bucket_name,file_name,expires_in_sec,max_byte_size)",
  "args": {
    "bucket_name": "aws-sdk-ruby-bucket-db72bb5d2f17",
    "file_name": "datafile-1-MB",
    "expires_in_sec": 60,
    "max_byte_size": 3145728
  },
  "duration": 68.49,
  "error": "Expected to be created object does NOT exist",
  "status": "FAIL"
}

Executed 3 out of 13 tests successfully.
```

**Comment by minio-ops** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-compression-xl.sh | :heavy_check_mark: |
| mint-xl.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-compression-dist-xl.sh | :heavy_check_mark: |
| mint-compression-fs.sh | :heavy_check_mark: |
| mint-worm.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-dist-xl.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :x: [more...](#0b20dadc-dbae-4393-b50c-361bac431f56) |
<a name="0b20dadc-dbae-4393-b50c-361bac431f56"></a>
### 7162-80f792f/mint-gateway-nas.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.55:31433
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp c04d92178049:/mint/log /tmp/mint-logs'

(1/13) Running aws-sdk-go tests ... FAILED in 0 seconds
{
  "alert": "",
  "args": {
    "bucketName": "aws-sdk-go-test-1u6qy23iuzl3ij",
    "expiry": 60000000000,
    "objectName": "presignedTest"
  },
  "duration": 9,
  "error": "NoSuchBucket: The specified bucket does not exist\n\tstatus code: 404, request id: 1580EA0BCE3D6CD7, host id: ",
  "function": "PresignedPut",
  "message": "AWS SDK Go DeleteBucket Failed",
  "name": "aws-sdk-go",
  "status": "FAIL"
}

Executed 0 out of 13 tests successfully.
```

**Review by balamurugana — APPROVED** [review]
