### PR TITLE
starts-with policy condition support issue

### LINKED ISSUE #7806: Minio not enforcing key or starts-with condition with boto3 presigned post
The following snippet generates a working pre-signed URL, but I've noticed that the key and **starts-with** condition are not enforced. When I am making the post request with the pre-signed URL, I can change the key to a completely different value and Minio will use it. Interestingly, it appears that Minio does use the **content-length-range** condition.

```
import boto3
from botocore.client import Config

def generate_s3_presigned_post(bucket, key, expiration=3600, acl='private', key_start='temp'):
    """Generate an AWS signature for presigned POST requests.

    This signed data allows file uploads directly from the browser to S3.
    """

    s3 = boto3.client(
        "s3",
        endpoint_url='http://localhost:9000',
        aws_access_key_id='key',
        aws_secret_access_key='secret',
        config=Config(signature_version="s3v4"),
    )

    # http://boto3.readthedocs.io/en/latest/reference/services/s3.html#S3.Client.generate_presigned_post
    data = s3.generate_presigned_post(
        bucket,
        key,

        Conditions=[
            {'acl': acl},
            {'success_action_status': '201'},
            {'x-requested-with': 'xhr'},
            ['starts-with', '$content-type', ''], # Allow any content-type
            ['starts-with', '$key', 'temp'], # Key should start with 'temp'
            ['content-length-range', 0, 20000000], # An upper bound on how large of files we'll accept (20MB)
        ],

        ExpiresIn=expiration,
    )

    # Add other values that the browser JS will need to include in a POST
    data['acl'] = acl
    data['key_start'] = key_start

    return data
```

## Expected Behavior
I would expect the post request to fail if the key is changed or the **starts-with** condition is violated.

## Current Behavior
Minio will use whatever key is provided in the post request, even if it is different from what was used to create the presigned URL.

## Your Environment
* Python 3.7
* minio 4.0.18

### PR DESCRIPTION
**Pull request by ebozduman**
## Description
Fixes #7806.
We did not enforce the post presigned policy condition `"starts-with"`, since we overwrite its index, `"key"`, (by `"key eq <object-name>"` condition created by default) when policy conditions are parsed and saved in the policy conditions map. That's why `"starts-with"` condition is never checked and the object is created without regarding this limitation.
To eliminate this problem, I've introduced dedicated map indexes for each and every `"eq"` and `"starts-with"` condition separately.

## Motivation and Context
We need to support `"starts-with"` for compatibility and security reasons.

## How to test this PR?
Here are the 2 scripts I used to test the fix; `generate_URL.py` and `create_object.py`

**`generate_URL.py`**
Generates policy, signature and all the parameters that need to be fed to the 2nd script, `create_object.py`. Update policy in this script for more testing. You can also run this script against amazon s3 or against your local minio server. Check the endpoint, access/secret key settings and comments for how to switch between s3 and minio.
```
import boto3
import os

from botocore.client import Config
def generate_s3_presigned_post(bucket, key, expiration=3600,key_start=''):
    """Generate an AWS signature for presigned POST requests.
    This signed data allows file uploads directly from the browser to S3.
    """
    s3 = boto3.client(
        "s3",
        # The following lines are to test against either amazon s3 or against your local minio server
        # ===============================
        # Amazon s3
        # Comment/Uncomment the following 3 lines to activate/deactivate
        # endpoint_url='https://s3.amazonaws.com',
        # aws_access_key_id='<your-amazon-access-key>',
        # aws_secret_access_key='<your-amazon-secret-key>',
        # ===============================
        # Minio server
        # Comment/Uncomment the following 3 lines to activate/deactivate
        endpoint_url='http://localhost:9000',
        aws_access_key_id='minio',
        aws_secret_access_key='minio123',
        # ===============================

        config=Config(signature_version="s3v4"),
    )

    data = s3.generate_presigned_post(bucket, key,
        Fields={
            'success_action_status': '201',
        },
        Conditions=[
            {'success_action_status': '201'},  # required
            ['starts-with', 'key', key_start], # Key should start with key_start ('temp')
            ['content-length-range', 0, 200000], # An upper bound on how large of files we'll accept (20MB)
        ],
        ExpiresIn=expiration)
    return data

# Create the presigned URL for a file
urlAndFields = generate_s3_presigned_post('ersan', 'temp_file', 600, 'tmp')
url = {'url': urlAndFields['url']}
fields = urlAndFields['fields']
all = dict(url, **fields)
arguments = ""
for key, val in all.items():
    arguments = arguments + " " + key + " " + val
print(arguments)```
```

**`create_object.py`** takes the output of `generate_URL.py` script as its parameter and puts together a curl command and runs it to create an object, if the policy condition checks are satisfied. 
```
import sys
import re
import os

args = sys.argv
print(args)
print("")

if len(args) < 2:
    fmt.Println("Unexpected number of arguments")
    exit

url = args[2]
print(url)
print("")
fields = args[3:]
print("fields", fields)
fieldsLength = len(fields)
print("fields length:", fieldsLength)
print("")

params = ""
indx = 0
while indx < fieldsLength:
    print("indx at the start", indx)
    print(fields[indx] + "=" + fields[indx+1])
    params = params + " -F " + fields[indx] + "=" + fields[indx+1]
    if indx < fieldsLength - 2:
        indx = indx + 2
    else:
        break

params = params + " -F file=@/etc/issue"
print("")
print("params", params)

myCmd = "curl -v %s %s"%(url, params)
print("")
print("myCmd => ", myCmd)
print("")

os.system(myCmd)
```
Example:
One liner to run both scripts
`$ python3.7 generate_URL.py | xargs python3.7 create_object.py`
or
In 2  steps:
```
$  python3.7 generate_URL.py
$   url http://localhost:9000/ersan success_action_status 201 ...
$  ...
$  ...
$ python3.7 create_object.py <copy and paste-above-output>
```

## Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [ ] Fixes a regression (If yes, please add `commit-id` or `PR #` here)
- [ ] Documentation needed
- [ ] Unit tests needed
- [ ] Functional tests needed (If yes, add [mint](https://github.com/minio/mint) PR # here: )

### CODE REVIEW

**Comment by minio-ops** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-compression-xl.sh | :heavy_check_mark: |
| mint-xl.sh | :heavy_check_mark: |
| mint-compression-dist-xl.sh | :heavy_check_mark: |
| mint-compression-fs.sh | :heavy_check_mark: |
| mint-worm.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :x: [more...](#6af88c76-d4b9-407b-8b81-1f52ad7688b6) |
| mint-dist-xl.sh | :x: [more...](#f2041b89-0c03-4b92-aeb1-17d742453d6f) |
<a name="6af88c76-d4b9-407b-8b81-1f52ad7688b6"></a>
### 7937-e94511b/mint-large-bucket.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.59:31734
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp e324cb63e574:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 1 seconds
(2/14) Running aws-sdk-java tests ... done in 2 seconds
(3/14) Running aws-sdk-php tests ... done in 48 seconds
(4/14) Running aws-sdk-ruby tests ... done in 18 seconds
(5/14) Running awscli tests ... done in 2 minutes and 20 seconds
(6/14) Running healthcheck tests ... done in 1 seconds
(7/14) Running mc tests ... FAILED in 2 minutes and 43 seconds
{
  "name": "mc",
  "duration": "119969",
  "function": "test_mirror_list_objects_storage_class",
  "status": "FAIL",
  "error": "/mint/run/core/mc/mc --config-dir /tmp/.mc-13601 --quiet --no-color mirror --storage-class REDUCED_REDUNDANCY /mint/data myminio/mc-test-bucket-29143  >>> \n`/mint/data/datafile-1-MB` -> `myminio/mc-test-bucket-29143/datafile-1-MB`\n`/mint/data/datafile-0-b` -> `myminio/mc-test-bucket-29143/datafile-0-b`\n`/mint/data/datafile-1-kB` -> `myminio/mc-test-bucket-29143/datafile-1-kB`\n`/mint/data/datafile-1-b` -> `myminio/mc-test-bucket-29143/datafile-1-b`\n`/mint/data/datafile-10-MB` -> `myminio/mc-test-bucket-29143/datafile-10-MB`\n`/mint/data/datafile-1.03-MB` -> `myminio/mc-test-bucket-29143/datafile-1.03-MB`\n`/mint/data/datafile-100-kB` -> `myminio/mc-test-bucket-29143/datafile-100-kB`\n`/mint/data/datafile-10-kB` -> `myminio/mc-test-bucket-29143/datafile-10-kB`\n`/mint/data/datafile-11-MB` -> `myminio/mc-test-bucket-29143/datafile-11-MB`\n`/mint/data/datafile-129-MB` -> `myminio/mc-test-bucket-29143/datafile-129-MB`\n`/mint/data/datafile-5-MB` -> `myminio/mc-test-bucket-29143/datafile-5-MB`\n`/mint/data/datafile-33-kB` -> `myminio/mc-test-bucket-29143/datafile-33-kB`\n`/mint/data/datafile-6-MB` -> `myminio/mc-test-bucket-29143/datafile-6-MB`\n`/mint/data/datafile-5243880-b` -> `myminio/mc-test-bucket-29143/datafile-5243880-b`\n`/mint/data/datafile-65-MB` -> `myminio/mc-test-bucket-29143/datafile-65-MB`\nmc: <ERROR> Failed to copy `/mint/data/datafile-10-MB`. Please reduce your request\nmc: <ERROR> Failed to copy `/mint/data/datafile-65-MB`. Please reduce your request\nmc: <ERROR> Failed to copy `/mint/data/datafile-129-MB`. Please reduce your request\nTotal: 233.17 MiB, Transferred: 383.08 MiB, Speed: 3.20 MiB/s"
}

Executed 6 out of 14 tests successfully.
```
<a name="f2041b89-0c03-4b92-aeb1-17d742453d6f"></a>
### 7937-e94511b/mint-dist-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.51:30398
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp b60559d6a979:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 0 seconds
(2/14) Running aws-sdk-java tests ... done in 1 seconds
(3/14) Running aws-sdk-php tests ... done in 44 seconds
(4/14) Running aws-sdk-ruby tests ... done in 3 seconds
(5/14) Running awscli tests ... done in 2 minutes and 6 seconds
(6/14) Running healthcheck tests ... done in 0 seconds
(7/14) Running mc tests ... done in 1 minutes and 3 seconds
(8/14) Running minio-dotnet tests ... done in 38 seconds
(9/14) Running minio-go tests ... done in 1 minutes and 4 seconds
(10/14) Running minio-java tests ... FAILED in 1 minutes and 8 seconds
{
  "name": "minio-java",
  "function": "removeIncompleteUpload(String bucketName, String objectName)",
  "duration": 511,
  "status": "FAIL",
  "error": "error occurred\nErrorResponse(code=SlowDown, message=Please reduce your request, bucketName=minio-java-test-256h43g, objectName=minio-java-test-s2i0l6, resource=/minio-java-test-256h43g/minio-java-test-s2i0l6, requestId=15B1F9B73132F538, hostId=8d0b1c44-7fb6-4eb6-923f-8f91d6e47757)\nrequest={method=DELETE, url=http://72.28.97.51:30398/minio-java-test-256h43g/minio-java-test-s2i0l6?uploadId=99e84b6a-129b-418b-8e9e-755592b583ce, headers=Host: 72.28.97.51:30398\nUser-Agent: MinIO (amd64; amd64) minio-java/dev\nx-amz-content-sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855\nx-amz-date: 20190716T192510Z\nAuthorization: AWS4-HMAC-SHA256 Credential=*REDACTED*/20190716/us-east-1/s3/aws4_request, SignedHeaders=host;x-amz-content-sha256;x-amz-date, Signature=*REDACTED*\n}\nresponse={code=503, headers=Accept-Ranges: bytes\nContent-Length: 361\nContent-Security-Policy: block-all-mixed-content\nContent-Type: application/xml\nRetry-After: 120\nServer: MinIO/DEVELOPMENT.2019-07-16T19-05-23Z\nVary: Origin\nX-Amz-Request-Id: 15B1F9B73132F538\nX-Xss-Protection: 1; mode=block\nDate: Tue, 16 Jul 2019 19:25:11 GMT\n}\n >>> [io.minio.MinioClient.executeReq(MinioClient.java:1204), io.minio.MinioClient.execute(MinioClient.java:1070), io.minio.MinioClient.executeDelete(MinioClient.java:1347), io.minio.MinioClient.abortMultipartUpload(MinioClient.java:5149), io.minio.MinioClient.putObject(MinioClient.java:4337), io.minio.MinioClient.putObject(MinioClient.java:4183), FunctionalTest.removeIncompleteUploads_test(FunctionalTest.java:1719), FunctionalTest.runTests(FunctionalTest.java:2992), FunctionalTest.main(FunctionalTest.java:3118)]"
}

Executed 9 out of 14 tests successfully.
```

**Comment by minio-ops** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-worm.sh | :heavy_check_mark: |
| mint-compression-xl.sh | :x: [more...](#679e7c24-72a6-4816-b954-40827d3417c2) |
| mint-xl.sh | :x: [more...](#822ab5a3-8f4e-4b71-a8e5-0f4d7938b78f) |
| mint-large-bucket.sh | :x: [more...](#34caac56-ed7e-4563-ab1d-ae4037a8fc1b) |
| mint-compression-dist-xl.sh | :x: [more...](#432858fd-2d1c-4ee3-b5fd-6bf9702336f4) |
| mint-compression-fs.sh | :x: [more...](#ff0e0a4a-1791-43bd-bded-d99d8c03ac7c) |
| mint-fs.sh | :x: [more...](#9c76290b-15a5-40cc-a6b2-0a18bd12564b) |
| mint-dist-xl.sh | :x: [more...](#d4e5d445-bbf0-46f8-a717-ccfddfb38e47) |
| mint-gateway-nas.sh | :x: [more...](#dd97a096-ce55-4105-ac0e-8b8adeaacffa) |
<a name="432858fd-2d1c-4ee3-b5fd-6bf9702336f4"></a>
### 7937-203351d/mint-compression-dist-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.58:30041
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 289f08baddd7:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... FAILED in 0 seconds
{
  "alert": "",
  "args": {
    "bucketName": "aws-sdk-go-test-5s3aswwzvmn2dh",
    "objectName1": "object1.csv",
    "objectName2": "object2.csv"
  },
  "duration": 75,
  "error": "MalformedXML: The XML provided was not well-formed or did not validate against our published schema. Check the service documentation and try again.\n\tstatus code: 400, request id: 15B4FC9E902D64EC, host id: ",
  "function": "testSelectObject",
  "message": "AWS SDK Go Select object failed for unicode separator MalformedXML: The XML provided was not well-formed or did not validate against our published schema. Check the service documentation and try again.\n\tstatus code: 400, request id: 15B4FC9E902D64EC, host id: ",
  "name": "aws-sdk-go",
  "status": "FAIL"
}

Executed 0 out of 14 tests successfully.
```
<a name="ff0e0a4a-1791-43bd-bded-d99d8c03ac7c"></a>
### 7937-203351d/mint-compression-fs.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.58:30574
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp e7af0928e304:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... FAILED in 0 seconds
{
  "alert": "",
  "args": {
    "bucketName": "aws-sdk-go-test-gkov2msbnhl0qb",
    "objectName1": "object1.csv",
    "objectName2": "object2.csv"
  },
  "duration": 8,
  "error": "MalformedXML: The XML provided was not well-formed or did not validate against our published schema. Check the service documentation and try again.\n\tstatus code: 400, request id: 15B4FC9E656DA867, host id: ",
  "function": "testSelectObject",
  "message": "AWS SDK Go Select object failed for unicode separator MalformedXML: The XML provided was not well-formed or did not validate against our published schema. Check the service documentation and try again.\n\tstatus code: 400, request id: 15B4FC9E656DA867, host id: ",
  "name": "aws-sdk-go",
  "status": "FAIL"
}

Executed 0 out of 14 tests successfully.
```
<a name="679e7c24-72a6-4816-b954-40827d3417c2"></a>
### 7937-203351d/mint-compression-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.51:31595
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 9eed8c4c1c97:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... FAILED in 0 seconds
{
  "alert": "",
  "args": {
    "bucketName": "aws-sdk-go-test-0ziwk3zb2shg1o",
    "objectName1": "object1.csv",
    "objectName2": "object2.csv"
  },
  "duration": 16,
  "error": "MalformedXML: The XML provided was not well-formed or did not validate against our published schema. Check the service documentation and try again.\n\tstatus code: 400, request id: 15B4FC9E6BA040ED, host id: ",
  "function": "testSelectObject",
  "message": "AWS SDK Go Select object failed for unicode separator MalformedXML: The XML provided was not well-formed or did not validate against our published schema. Check the service documentation and try again.\n\tstatus code: 400, request id: 15B4FC9E6BA040ED, host id: ",
  "name": "aws-sdk-go",
  "status": "FAIL"
}

Executed 0 out of 14 tests successfully.
```
<a name="d4e5d445-bbf0-46f8-a717-ccfddfb38e47"></a>
### 7937-203351d/mint-dist-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.60:31178
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 9ca8ef4f281d:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... FAILED in 0 seconds
{
  "alert": "",
  "args": {
    "bucketName": "aws-sdk-go-test-36j2wtegm1f4xp",
    "objectName1": "object1.csv",
    "objectName2": "object2.csv"
  },
  "duration": 94,
  "error": "MalformedXML: The XML provided was not well-formed or did not validate against our published schema. Check the service documentation and try again.\n\tstatus code: 400, request id: 15B4FC9E915EAA0F, host id: ",
  "function": "testSelectObject",
  "message": "AWS SDK Go Select object failed for unicode separator MalformedXML: The XML provided was not well-formed or did not validate against our published schema. Check the service documentation and try again.\n\tstatus code: 400, request id: 15B4FC9E915EAA0F, host id: ",
  "name": "aws-sdk-go",
  "status": "FAIL"
}

Executed 0 out of 14 tests successfully.
```
<a name="dd97a096-ce55-4105-ac0e-8b8adeaacffa"></a>
### 7937-203351d/mint-gateway-nas.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.58:31486
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp dce57f567440:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... FAILED in 0 seconds
{
  "alert": "",
  "args": {
    "bucketName": "aws-sdk-go-test-pvb92nzu1fqzpk",
    "objectName1": "object1.csv",
    "objectName2": "object2.csv"
  },
  "duration": 12,
  "error": "MalformedXML: The XML provided was not well-formed or did not validate against our published schema. Check the service documentation and try again.\n\tstatus code: 400, request id: 15B4FC9E5BCE19EF, host id: ",
  "function": "testSelectObject",
  "message": "AWS SDK Go Select object failed for unicode separator MalformedXML: The XML provided was not well-formed or did not validate against our published schema. Check the service documentation and try again.\n\tstatus code: 400, request id: 15B4FC9E5BCE19EF, host id: ",
  "name": "aws-sdk-go",
  "status": "FAIL"
}

Executed 0 out of 14 tests successfully.
```
<a name="9c76290b-15a5-40cc-a6b2-0a18bd12564b"></a>
### 7937-203351d/mint-fs.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.59:30800
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 8f8d886a3578:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... FAILED in 0 seconds
{
  "alert": "",
  "args": {
    "bucketName": "aws-sdk-go-test-ec52mzvjji659b",
    "objectName1": "object1.csv",
    "objectName2": "object2.csv"
  },
  "duration": 14,
  "error": "MalformedXML: The XML provided was not well-formed or did not validate against our published schema. Check the service documentation and try again.\n\tstatus code: 400, request id: 15B4FC9E473A49E8, host id: ",
  "function": "testSelectObject",
  "message": "AWS SDK Go Select object failed for unicode separator MalformedXML: The XML provided was not well-formed or did not validate against our published schema. Check the service documentation and try again.\n\tstatus code: 400, request id: 15B4FC9E473A49E8, host id: ",
  "name": "aws-sdk-go",
  "status": "FAIL"
}

Executed 0 out of 14 tests successfully.
```
<a name="822ab5a3-8f4e-4b71-a8e5-0f4d7938b78f"></a>
### 7937-203351d/mint-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.51:31388
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 0b5ac84c9f2d:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... FAILED in 0 seconds
{
  "alert": "",
  "args": {
    "bucketName": "aws-sdk-go-test-r9uv44uuwd95ux",
    "objectName1": "object1.csv",
    "objectName2": "object2.csv"
  },
  "duration": 26,
  "error": "MalformedXML: The XML provided was not well-formed or did not validate against our published schema. Check the service documentation and try again.\n\tstatus code: 400, request id: 15B4FC9E3D2A8B1B, host id: ",
  "function": "testSelectObject",
  "message": "AWS SDK Go Select object failed for unicode separator MalformedXML: The XML provided was not well-formed or did not validate against our published schema. Check the service documentation and try again.\n\tstatus code: 400, request id: 15B4FC9E3D2A8B1B, host id: ",
  "name": "aws-sdk-go",
  "status": "FAIL"
}

Executed 0 out of 14 tests successfully.
```
<a name="34caac56-ed7e-4563-ab1d-ae4037a8fc1b"></a>
### 7937-203351d/mint-large-bucket.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.55:30963
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 47aad41e0d3b:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... FAILED in 1 seconds
{
  "alert": "",
  "args": {
    "bucketName": "aws-sdk-go-test-ebpl63esppbcgp",
    "objectName1": "object1.csv",
    "objectName2": "object2.csv"
  },
  "duration": 146,
  "error": "MalformedXML: The XML provided was not well-formed or did not validate against our published schema. Check the service documentation and try again.\n\tstatus code: 400, request id: 15B4FC9EE61ACF0B, host id: ",
  "function": "testSelectObject",
  "message": "AWS SDK Go Select object failed for unicode separator MalformedXML: The XML provided was not well-formed or did not validate against our published schema. Check the service documentation and try again.\n\tstatus code: 400, request id: 15B4FC9EE61ACF0B, host id: ",
  "name": "aws-sdk-go",
  "status": "FAIL"
}

Executed 0 out of 14 tests successfully.
```

**Comment by minio-ops** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-worm.sh | :heavy_check_mark: |
| mint-compression-xl.sh | :x: [more...](#692b24ae-df0b-483d-b3ce-f88d1a3be290) |
| mint-xl.sh | :x: [more...](#2cd10697-987e-4342-a363-05011cd43d57) |
| mint-large-bucket.sh | :x: [more...](#30dbe76f-fb41-4542-abe4-e701a970af45) |
| mint-compression-dist-xl.sh | :x: [more...](#24f86f73-13ef-4913-a624-7c40f4782820) |
| mint-compression-fs.sh | :x: [more...](#0a87bb5d-24e9-4f22-be17-7e4fef36f867) |
| mint-fs.sh | :x: [more...](#734d05e8-129b-4a00-aaf8-d3c1d21c1e59) |
| mint-dist-xl.sh | :x: [more...](#425eb71e-044c-4dd7-81cb-e39c4e727a7d) |
| mint-gateway-nas.sh | :x: [more...](#33c5bc81-b004-4377-8650-3b6c6537f6fe) |
<a name="33c5bc81-b004-4377-8650-3b6c6537f6fe"></a>
### 7937-c674659/mint-gateway-nas.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.57:31674
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 6ab1448cc8d9:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... FAILED in 12 seconds
{
  "alert": "",
  "args": {
    "bucketName": "aws-sdk-go-test-4uuhp9lzssqd6p",
    "expiry": 60000000000,
    "objectName": "presignedTest"
  },
  "duration": 12279,
  "error": "RequestError: send request failed\ncaused by: Put http://72.28.97.57:31674/aws-sdk-go-test-4uuhp9lzssqd6p: dial tcp 72.28.97.57:31674: connect: no route to host",
  "function": "PresignedPut",
  "message": "AWS SDK Go CreateBucket Failed",
  "name": "aws-sdk-go",
  "status": "FAIL"
}

Executed 0 out of 14 tests successfully.
```
<a name="24f86f73-13ef-4913-a624-7c40f4782820"></a>
### 7937-c674659/mint-compression-dist-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.57:32351
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp cdd24191073e:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... FAILED in 11 seconds
{
  "alert": "",
  "args": {
    "bucketName": "aws-sdk-go-test-65k1et0qc4ekhz",
    "expiry": 60000000000,
    "objectName": "presignedTest"
  },
  "duration": 11344,
  "error": "RequestError: send request failed\ncaused by: Put http://72.28.97.57:32351/aws-sdk-go-test-65k1et0qc4ekhz: dial tcp 72.28.97.57:32351: connect: no route to host",
  "function": "PresignedPut",
  "message": "AWS SDK Go CreateBucket Failed",
  "name": "aws-sdk-go",
  "status": "FAIL"
}

Executed 0 out of 14 tests successfully.
```
<a name="692b24ae-df0b-483d-b3ce-f88d1a3be290"></a>
### 7937-c674659/mint-compression-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.56:31286
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 145ce18fd383:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... FAILED in 0 seconds
{
  "alert": "",
  "args": {
    "bucketName": "aws-sdk-go-test-9vyd1pjmyj6cqg",
    "objectName1": "object1.csv",
    "objectName2": "object2.csv"
  },
  "duration": 14,
  "error": "MalformedXML: The XML provided was not well-formed or did not validate against our published schema. Check the service documentation and try again.\n\tstatus code: 400, request id: 15B7FA715513FF65, host id: ",
  "function": "testSelectObject",
  "message": "AWS SDK Go Select object failed for unicode separator MalformedXML: The XML provided was not well-formed or did not validate against our published schema. Check the service documentation and try again.\n\tstatus code: 400, request id: 15B7FA715513FF65, host id: ",
  "name": "aws-sdk-go",
  "status": "FAIL"
}

Executed 0 out of 14 tests successfully.
```
<a name="0a87bb5d-24e9-4f22-be17-7e4fef36f867"></a>
### 7937-c674659/mint-compression-fs.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.51:31883
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 7baefb636535:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... FAILED in 1 seconds
{
  "alert": "",
  "args": {
    "bucketName": "aws-sdk-go-test-w93zzvuvf51sct",
    "objectName1": "object1.csv",
    "objectName2": "object2.csv"
  },
  "duration": 14,
  "error": "MalformedXML: The XML provided was not well-formed or did not validate against our published schema. Check the service documentation and try again.\n\tstatus code: 400, request id: 15B7FA7149762F74, host id: ",
  "function": "testSelectObject",
  "message": "AWS SDK Go Select object failed for unicode separator MalformedXML: The XML provided was not well-formed or did not validate against our published schema. Check the service documentation and try again.\n\tstatus code: 400, request id: 15B7FA7149762F74, host id: ",
  "name": "aws-sdk-go",
  "status": "FAIL"
}

Executed 0 out of 14 tests successfully.
```
<a name="734d05e8-129b-4a00-aaf8-d3c1d21c1e59"></a>
### 7937-c674659/mint-fs.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.52:31200
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 7224e3fe19e1:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... FAILED in 0 seconds
{
  "alert": "",
  "args": {
    "bucketName": "aws-sdk-go-test-dktrxm3yxcweyj",
    "objectName1": "object1.csv",
    "objectName2": "object2.csv"
  },
  "duration": 13,
  "error": "MalformedXML: The XML provided was not well-formed or did not validate against our published schema. Check the service documentation and try again.\n\tstatus code: 400, request id: 15B7FA715ECDBACE, host id: ",
  "function": "testSelectObject",
  "message": "AWS SDK Go Select object failed for unicode separator MalformedXML: The XML provided was not well-formed or did not validate against our published schema. Check the service documentation and try again.\n\tstatus code: 400, request id: 15B7FA715ECDBACE, host id: ",
  "name": "aws-sdk-go",
  "status": "FAIL"
}

Executed 0 out of 14 tests successfully.
```
<a name="2cd10697-987e-4342-a363-05011cd43d57"></a>
### 7937-c674659/mint-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.52:31221
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp eb5803a350cf:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... FAILED in 0 seconds
{
  "alert": "",
  "args": {
    "bucketName": "aws-sdk-go-test-i6ffuxqn6tanst",
    "objectName1": "object1.csv",
    "objectName2": "object2.csv"
  },
  "duration": 17,
  "error": "MalformedXML: The XML provided was not well-formed or did not validate against our published schema. Check the service documentation and try again.\n\tstatus code: 400, request id: 15B7FA712FECA2AF, host id: ",
  "function": "testSelectObject",
  "message": "AWS SDK Go Select object failed for unicode separator MalformedXML: The XML provided was not well-formed or did not validate against our published schema. Check the service documentation and try again.\n\tstatus code: 400, request id: 15B7FA712FECA2AF, host id: ",
  "name": "aws-sdk-go",
  "status": "FAIL"
}

Executed 0 out of 14 tests successfully.
```
<a name="425eb71e-044c-4dd7-81cb-e39c4e727a7d"></a>
### 7937-c674659/mint-dist-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.51:32076
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 7b7f6889cdb3:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... FAILED in 0 seconds
{
  "alert": "",
  "args": {
    "bucketName": "aws-sdk-go-test-fg13hh9beguvof",
    "objectName1": "object1.csv",
    "objectName2": "object2.csv"
  },
  "duration": 111,
  "error": "MalformedXML: The XML provided was not well-formed or did not validate against our published schema. Check the service documentation and try again.\n\tstatus code: 400, request id: 15B7FA717E4A60D4, host id: ",
  "function": "testSelectObject",
  "message": "AWS SDK Go Select object failed for unicode separator MalformedXML: The XML provided was not well-formed or did not validate against our published schema. Check the service documentation and try again.\n\tstatus code: 400, request id: 15B7FA717E4A60D4, host id: ",
  "name": "aws-sdk-go",
  "status": "FAIL"
}

Executed 0 out of 14 tests successfully.
```
<a name="30dbe76f-fb41-4542-abe4-e701a970af45"></a>
### 7937-c674659/mint-large-bucket.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.55:31288
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 764e2d6f9559:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... FAILED in 6 seconds
{
  "alert": "",
  "args": {
    "bucketName": "aws-sdk-go-test-isp2fzkco2zp2l",
    "objectName1": "object1.csv",
    "objectName2": "object2.csv"
  },
  "duration": 129,
  "error": "MalformedXML: The XML provided was not well-formed or did not validate against our published schema. Check the service documentation and try again.\n\tstatus code: 400, request id: 15B7FA72CBF51467, host id: ",
  "function": "testSelectObject",
  "message": "AWS SDK Go Select object failed for unicode separator MalformedXML: The XML provided was not well-formed or did not validate against our published schema. Check the service documentation and try again.\n\tstatus code: 400, request id: 15B7FA72CBF51467, host id: ",
  "name": "aws-sdk-go",
  "status": "FAIL"
}

Executed 0 out of 14 tests successfully.
```

**Comment by ebozduman** [comment]
ping @Praveenrajmani , @poornas 

I am looking into the Travis unit test failures. All 3 tests fail due to incorrectly set policies.
Please review the changes while I work on a fix for the broken unit tests;
- TestPostPolicyBucketHandler,
- TestPostPolicyBucketHandlerRedirect,
- TestPostPolicyForm

File: cmd/postpolicyform.go [hunk 1]
```diff
@@ -243,34 +259,66 @@ func checkPostPolicy(formValues http.Header, postPolicyForm PostPolicyForm) erro
...
-			}
-		} else {
-			// This covers all conditions X-Amz-Meta-* and X-Amz-*
-			if strings.HasPrefix(cond, "$x-amz-meta-") || strings.HasPrefix(cond, "$x-amz-") {
-				// Check if policy condition is satisfied
+	for _, policy := range postPolicyForm.Conditions.Policies {
+		for cond, v := range policy {
+			// Form fields names are in canonical format, convert conditions names
+			// to canonical for simplification purpose, so `$key` will become `Key`
+			formCanonicalName := http.CanonicalHeaderKey(strings.TrimPrefix(cond, "$"))
```
Comment (Praveenrajmani) [inline cmd/postpolicyform.go]: We should not remove this prefix `$` for `startsWith` condition. This will fail for the correct case - If we actually try to upload a `key` prefixed object. Because, we fail here 

```
if _, condFound := startsWithConds[cond]; !condFound
```
(`in checkPostPolicy()`) as the keys in `startsWithConds` are prefixed with `$`

**Comment by minio-ops** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-compression-xl.sh | :heavy_check_mark: |
| mint-xl.sh | :heavy_check_mark: |
| mint-compression-fs.sh | :heavy_check_mark: |
| mint-worm.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-dist-xl.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :x: [more...](#b60808a5-ac28-4943-aaff-596624ba69c3) |
| mint-compression-dist-xl.sh | :x: [more...](#4bcb7ec6-4b91-4dbe-be18-5f921d6e544e) |
<a name="4bcb7ec6-4b91-4dbe-be18-5f921d6e544e"></a>
### 7937-436d848/mint-compression-dist-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.59:30356
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 02bf8a01dbd6:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 0 seconds
(2/14) Running aws-sdk-java tests ... done in 2 seconds
(3/14) Running aws-sdk-php tests ... done in 46 seconds
(4/14) Running aws-sdk-ruby tests ... done in 3 seconds
(5/14) Running awscli tests ... done in 1 minutes and 15 seconds
(6/14) Running healthcheck tests ... done in 0 seconds
(7/14) Running mc tests ... done in 44 seconds
(8/14) Running minio-dotnet tests ... done in 44 seconds
(9/14) Running minio-go tests ... done in 1 minutes and 33 seconds
(10/14) Running minio-java tests ... done in 59 seconds
(11/14) Running minio-js tests ... done in 38 seconds
(12/14) Running minio-py tests ... FAILED in 1 seconds
{
  "args": {
    "metadata": {
      "x-amz-storage-class": "STANDARD_IA"
    },
    "bucket_name": "minio-py-test-e87aa4eb-a4fc-47c6-9fd5-400071069dbf",
    "file_path": "/mint/data/datafile-11-MB",
    "object_name": "498a0124-8cc9-4e43-b192-fb54a412545b"
  },
  "name": "minio-py:test_fput_object_large_file",
  "status": "FAIL",
  "function": "fput_object(bucket_name, object_name, file_path, content_type, metadata, sse, progress, part_size)",
  "error": "Traceback (most recent call last):\n  File \"/mint/run/core/minio-py/tests.py\", line 304, in test_fput_object_large_file\n    client.fput_object(bucket_name, object_name+'-large', largefile, sse=sse)\n  File \"/usr/local/lib/python3.5/dist-packages/minio/api.py\", line 571, in fput_object\n    progress, part_size)\n  File \"/usr/local/lib/python3.5/dist-packages/minio/api.py\", line 827, in put_object\n    part_size=part_size)\n  File \"/usr/local/lib/python3.5/dist-packages/minio/api.py\", line 1659, in _stream_put_object\n    uploaded_parts)\n  File \"/usr/local/lib/python3.5/dist-packages/minio/api.py\", line 1745, in _complete_multipart_upload\n    content_sha256=sha256_hex)\n  File \"/usr/local/lib/python3.5/dist-packages/minio/api.py\", line 1901, in _url_open\n    object_name).get_exception()\nminio.error.InvalidPart: InvalidPart: message: One or more of the specified parts could not be found. The part might not have been uploaded, or the specified entity tag might not have matched the part's entity tag\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"/mint/run/core/minio-py/tests.py\", line 1822, in main\n    test_fput_object_large_file(client, largefile, log_output)\n  File \"/mint/run/core/minio-py/tests.py\", line 308, in test_fput_object_large_file\n    raise Exception(err)\nException: InvalidPart: message: One or more of the specified parts could not be found. The part might not have been uploaded, or the specified entity tag might not have matched the part's entity tag\n",
  "message": "InvalidPart: message: One or more of the specified parts could not be found. The part might not have been uploaded, or the specified entity tag might not have matched the part's entity tag",
  "duration": 1230
}

Executed 11 out of 14 tests successfully.
```
<a name="b60808a5-ac28-4943-aaff-596624ba69c3"></a>
### 7937-436d848/mint-large-bucket.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.55:31363
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 1fd311aa2872:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 3 seconds
(2/14) Running aws-sdk-java tests ... done in 4 seconds
(3/14) Running aws-sdk-php tests ... done in 50 seconds
(4/14) Running aws-sdk-ruby tests ... done in 14 seconds
(5/14) Running awscli tests ... done in 2 minutes and 24 seconds
(6/14) Running healthcheck tests ... done in 1 seconds
(7/14) Running mc tests ... FAILED in 2 minutes and 22 seconds
{
  "name": "mc",
  "duration": "103659",
  "function": "test_mirror_list_objects_storage_class",
  "status": "FAIL",
  "error": "/mint/run/core/mc/mc --config-dir /tmp/.mc-32528 --quiet --no-color mirror --storage-class REDUCED_REDUNDANCY /mint/data myminio/mc-test-bucket-30475  >>> \n`/mint/data/datafile-1-MB` -> `myminio/mc-test-bucket-30475/datafile-1-MB`\n`/mint/data/datafile-0-b` -> `myminio/mc-test-bucket-30475/datafile-0-b`\n`/mint/data/datafile-1-kB` -> `myminio/mc-test-bucket-30475/datafile-1-kB`\n`/mint/data/datafile-1-b` -> `myminio/mc-test-bucket-30475/datafile-1-b`\n`/mint/data/datafile-10-MB` -> `myminio/mc-test-bucket-30475/datafile-10-MB`\n`/mint/data/datafile-1.03-MB` -> `myminio/mc-test-bucket-30475/datafile-1.03-MB`\n`/mint/data/datafile-100-kB` -> `myminio/mc-test-bucket-30475/datafile-100-kB`\n`/mint/data/datafile-10-kB` -> `myminio/mc-test-bucket-30475/datafile-10-kB`\n`/mint/data/datafile-11-MB` -> `myminio/mc-test-bucket-30475/datafile-11-MB`\n`/mint/data/datafile-33-kB` -> `myminio/mc-test-bucket-30475/datafile-33-kB`\n`/mint/data/datafile-129-MB` -> `myminio/mc-test-bucket-30475/datafile-129-MB`\n`/mint/data/datafile-5-MB` -> `myminio/mc-test-bucket-30475/datafile-5-MB`\n`/mint/data/datafile-5243880-b` -> `myminio/mc-test-bucket-30475/datafile-5243880-b`\n`/mint/data/datafile-6-MB` -> `myminio/mc-test-bucket-30475/datafile-6-MB`\n`/mint/data/datafile-65-MB` -> `myminio/mc-test-bucket-30475/datafile-65-MB`\nmc: <ERROR> Failed to copy `/mint/data/datafile-11-MB`. Please reduce your request\nmc: <ERROR> Failed to copy `/mint/data/datafile-65-MB`. Please reduce your request\nmc: <ERROR> Failed to copy `/mint/data/datafile-129-MB`. Please reduce your request\nmc: <ERROR> Failed to copy `/mint/data/datafile-10-MB`. Please reduce your request\nTotal: 233.17 MiB, Transferred: 503.80 MiB, Speed: 4.86 MiB/s"
}

Executed 6 out of 14 tests successfully.
```

**Comment by ebozduman** [comment]
@Praveenrajmani @poornas 
This new fix is proposed by @krishnasrinivas and it is much more simpler and less change. There are some other issues that need to be addresses in separate issues. But starts-with issue #7806 was addressing is fixed with this change.
PTAL again.

**Comment by minio-ops** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-xl.sh | :heavy_check_mark: |
| mint-compression-dist-xl.sh | :heavy_check_mark: |
| mint-compression-fs.sh | :heavy_check_mark: |
| mint-worm.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-dist-xl.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-compression-xl.sh | :x: [more...](#09a20f13-a485-45e3-8b00-fa71cf19d34b) |
| mint-large-bucket.sh | :x: [more...](#d0cd9ae4-9d84-4f3f-bad9-7bf63bbe77e9) |
<a name="d0cd9ae4-9d84-4f3f-bad9-7bf63bbe77e9"></a>
### 7937-e3bdac4/mint-large-bucket.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.61:31171
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 506e5db48507:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 3 seconds
(2/14) Running aws-sdk-java tests ... done in 2 seconds
(3/14) Running aws-sdk-php tests ... done in 51 seconds
(4/14) Running aws-sdk-ruby tests ... done in 15 seconds
(5/14) Running awscli tests ... done in 2 minutes and 28 seconds
(6/14) Running healthcheck tests ... done in 0 seconds
(7/14) Running mc tests ... done in 47 seconds
(8/14) Running minio-dotnet tests ... done in 1 minutes and 24 seconds
(9/14) Running minio-go tests ... FAILED in 3 minutes and 34 seconds
{
  "args": {},
  "duration": 78759,
  "error": "The specified key does not exist.",
  "function": "testStorageClassMetadataCopyObject()",
  "message": "Stat failed",
  "name": "minio-go: testStorageClassMetadataCopyObject",
  "status": "FAIL"
}

Executed 8 out of 14 tests successfully.
```
<a name="09a20f13-a485-45e3-8b00-fa71cf19d34b"></a>
### 7937-e3bdac4/mint-compression-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.61:30927
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 270e158ed79d:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... FAILED in 6 minutes and 0 seconds
{
  "alert": "",
  "args": {
    "bucketName": "aws-sdk-go-test-ih2ab91kxz9unm",
    "expiry": 60000000000,
    "objectName": "presignedTest"
  },
  "duration": 360017,
  "error": "XMinioServerNotInitialized: Server not initialized, please try again.\n\tstatus code: 503, request id: 15C119A6ED9DF1AB, host id: ",
  "function": "PresignedPut",
  "message": "AWS SDK Go CreateBucket Failed",
  "name": "aws-sdk-go",
  "status": "FAIL"
}

Executed 0 out of 14 tests successfully.
```
Error: No such image: minio/minio:7937-e3bdac4

**Comment by minio-ops** [comment]
```
Error running mint automation
+ mkdir -p 7937-4bf9d1c/gopath/src/github.com/minio
+ git -C 7937-4bf9d1c/gopath/src/github.com/minio clone --quiet https://github.com/minio/minio.git
+ git -C 7937-4bf9d1c/gopath/src/github.com/minio/minio remote add minio https://github.com/minio/minio.git
+ git -C 7937-4bf9d1c/gopath/src/github.com/minio/minio fetch --quiet minio pull/7937/head:pr7937
+ git -C 7937-4bf9d1c/gopath/src/github.com/minio/minio checkout --quiet pr7937
+ GO111MODULE=on
+ GOPATH=/mnt/nvme/mint-auto/7937-4bf9d1c/gopath
+ make -C 7937-4bf9d1c/gopath/src/github.com/minio/minio --quiet
go: creating work dir: mkdir /tmp/go-build650323209: no space left on device
go: creating work dir: mkdir /tmp/go-build738542994: no space left on device
go: creating work dir: mkdir /tmp/go-build990274035: no space left on device
go: creating work dir: mkdir /tmp/go-build976265380: no space left on device
/mnt/nvme/mint-auto/7937-4bf9d1c/gopath/src/github.com/minio/minio/buildscripts/checkdeps.sh: line 76: cannot create temp file for here-document: No space left on device
/mnt/nvme/mint-auto/7937-4bf9d1c/gopath/src/github.com/minio/minio/buildscripts/checkdeps.sh: line 77: cannot create temp file for here-document: No space left on device
/mnt/nvme/mint-auto/7937-4bf9d1c/gopath/src/github.com/minio/minio/buildscripts/checkdeps.sh: line 76: cannot create temp file for here-document: No space left on device
/mnt/nvme/mint-auto/7937-4bf9d1c/gopath/src/github.com/minio/minio/buildscripts/checkdeps.sh: line 77: cannot create temp file for here-document: No space left on device
go: creating work dir: mkdir /tmp/go-build655945364: no space left on device
make: *** [build] Error 1

```

**Comment by Praveenrajmani** [comment]
@ebozduman I tested this example in the PR. My `starts-with` value was `tmp` and the key name was `tmp_file`. I got this as response 
```
<Error><Code>PostPolicyInvalidKeyName</Code><Message>Invalid according to Policy: Policy Condition failed</Message><BucketName>test</BucketName><Resource>/test</Resource><RequestId>15C1D3CE0876D46B</RequestId><HostId>26b0048d-affe-4ec2-9115-b7c494969635</HostId></Error>
```

**Comment by ebozduman** [comment]
I'll check it and get back to you.

**Comment by ebozduman** [comment]
@Praveenrajmani,

That is the similar behavior with S3. 
```
<Error><Code>AccessDenied</Code><Message>Invalid according to Policy: Policy Condition failed: ["starts-with", "key", "tmp"]</Message><RequestId>687CF6FF1FE73CAD</RequestId><HostId>7+VU3lc+UvPw61/5DQ77cjWviAjJEBaIUoplaVND+O/EnqG911uOktmhJt5SCtEK/DU9UEhmadw=</HostId></Error>
```

Our message:
```
<Error><Code>PostPolicyInvalidKeyName</Code><Message>Invalid according to Policy: Policy Condition failed</Message><BucketName>ersan</BucketName><Resource>/ersan</Resource><Region>us-east-1</Region><RequestId>15C6027A601D14ED</RequestId><HostId>63c53e89-540c-408f-8540-aba6f9c30ce2</HostId></Error>
```

_Note: Please ignore the S3 detail missing in our error message for the time-being. We are aware of it. These type of issues will be filed and addressed as separate issues (per @krishnasrinivas)._

So, you must have your policy defined with the slightly wrong format as :
`['starts-with', 'key', 'tmp']` without the required `$` sign in front of the key name `'key'`. 

That is, the policy is supposed to look like: `['starts-with', '$key', 'tmp']`

Unfortunately, I could not find any S3 documentation that explains about the $ sign. I can simply say that anytime an operand (`starts-with` or `eq`) is explicitly written as a policy, S3 expects the key to be provided **with** a $ sign. 
On the opposite side, for implied exact matching (`{'<key>': '<value>'}`), S3 expects the key to be provided **without** a $ sign.

Please give it a try with the $ sign and let me know how it went.

**Comment by kannappanr** [comment]
PTAL @Praveenrajmani @poornas

**Comment by poornas** [comment]
> Please give it a try with the $ sign and let me know how it went.

the key needs to be prefixed with $ sign

**Review by poornas — APPROVED** [review]
Tested, LGTM

**Comment by harshavardhana** [comment]
Ping @Praveenrajmani

**Comment by minio-ops** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-compression-dist-xl.sh | :heavy_check_mark: |
| mint-compression-fs.sh | :heavy_check_mark: |
| mint-worm.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-dist-xl.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-compression-xl.sh | :x: [more...](#7a21fa7f-4987-49ac-af74-6c85fbe42d34) |
| mint-xl.sh | :x: [more...](#1d1c5b24-e717-47a9-b287-d0eab88b38c5) |
<a name="1d1c5b24-e717-47a9-b287-d0eab88b38c5"></a>
### 7937-fd4d72b/mint-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.61:32496
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp ac19ede3517e:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... FAILED in 6 minutes and 5 seconds
{
  "alert": "",
  "args": {
    "bucketName": "aws-sdk-go-test-nbndqz9copofme",
    "expiry": 60000000000,
    "objectName": "presignedTest"
  },
  "duration": 365039,
  "error": "XMinioServerNotInitialized: Server not initialized, please try again.\n\tstatus code: 503, request id: 15C6B258E81CBA89, host id: ",
  "function": "PresignedPut",
  "message": "AWS SDK Go CreateBucket Failed",
  "name": "aws-sdk-go",
  "status": "FAIL"
}

Executed 0 out of 14 tests successfully.
```
<a name="7a21fa7f-4987-49ac-af74-6c85fbe42d34"></a>
### 7937-fd4d72b/mint-compression-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.55:31510
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 440110822f1d:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... FAILED in 6 minutes and 6 seconds
{
  "alert": "",
  "args": {
    "bucketName": "aws-sdk-go-test-0bod3j65wn3e4c",
    "expiry": 60000000000,
    "objectName": "presignedTest"
  },
  "duration": 365866,
  "error": "XMinioServerNotInitialized: Server not initialized, please try again.\n\tstatus code: 503, request id: 15C6B257C145F3FC, host id: ",
  "function": "PresignedPut",
  "message": "AWS SDK Go CreateBucket Failed",
  "name": "aws-sdk-go",
  "status": "FAIL"
}

Executed 0 out of 14 tests successfully.
```

**Review by Praveenrajmani — APPROVED** [review]
Tested and LGTM

**Comment by minio-ops** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-compression-xl.sh | :heavy_check_mark: |
| mint-xl.sh | :heavy_check_mark: |
| mint-compression-fs.sh | :heavy_check_mark: |
| mint-worm.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-dist-xl.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :x: [more...](#43031057-21d6-45a4-9f29-16c42d00e005) |
| mint-compression-dist-xl.sh | :x: [more...](#36993597-78f2-4af6-9323-f0b5d0e23af7) |
<a name="43031057-21d6-45a4-9f29-16c42d00e005"></a>
### 7937-71eed9c/mint-large-bucket.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.51:30142
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 4b392e354037:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 3 seconds
(2/14) Running aws-sdk-java tests ... done in 1 seconds
(3/14) Running aws-sdk-php tests ... done in 55 seconds
(4/14) Running aws-sdk-ruby tests ... done in 13 seconds
(5/14) Running awscli tests ... done in 2 minutes and 20 seconds
(6/14) Running healthcheck tests ... done in 0 seconds
(7/14) Running mc tests ... done in 1 minutes and 22 seconds
(8/14) Running minio-dotnet tests ... done in 1 minutes and 38 seconds
(9/14) Running minio-go tests ... FAILED in 3 minutes and 46 seconds
{
  "args": {},
  "duration": 87079,
  "error": "Please reduce your request",
  "function": "testStorageClassMetadataCopyObject()",
  "message": "CopyObject failed on RRS",
  "name": "minio-go: testStorageClassMetadataCopyObject",
  "status": "FAIL"
}

Executed 8 out of 14 tests successfully.
```
<a name="36993597-78f2-4af6-9323-f0b5d0e23af7"></a>
### 7937-71eed9c/mint-compression-dist-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.61:30026
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 69c3cde492b8:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 1 seconds
(2/14) Running aws-sdk-java tests ... done in 1 seconds
(3/14) Running aws-sdk-php tests ... done in 44 seconds
(4/14) Running aws-sdk-ruby tests ... done in 4 seconds
(5/14) Running awscli tests ... done in 2 minutes and 4 seconds
(6/14) Running healthcheck tests ... done in 0 seconds
(7/14) Running mc tests ... done in 55 seconds
(8/14) Running minio-dotnet tests ... done in 35 seconds
(9/14) Running minio-go tests ... done in 1 minutes and 15 seconds
(10/14) Running minio-java tests ... done in 2 minutes and 2 seconds
(11/14) Running minio-js tests ... FAILED in 21 seconds
{
  "name": "minio-js",
  "function": "fPutObject(bucketName, objectName, filePath, metaData)",
  "args": "bucketName:minio-js-test-38bf678c-a9e6-42b7-8893-a5b7744795cb, objectName:datafile-65-MB, filePath:/tmp/datafile-65-MB",
  "duration": 636,
  "status": "FAIL",
  "error": "Error: read ECONNRESET at exports._errnoException (util.js:1020:11) at TCP.onread (net.js:580:26)"
}

Executed 10 out of 14 tests successfully.
```
