### PR TITLE
xl: Add '.CORRUPTED' prefix to corrupted objects

### LINKED ISSUE #6575: Unable to replace a file not having read quorum with non standard SC
## Expected Behavior
When I set parity to 4 disks, and I lose data in 5 disks, the object is not visible anymore. However I should be able to replace it when I upload a new object with the same name.

## Current Behavior
Not able to upload an object when there is another object with the same name which lost its read quorum

## Possible Solution
```diff
diff --git a/cmd/xl-v1-object.go b/cmd/xl-v1-object.go
index ecf54402..3434ed43 100644
--- a/cmd/xl-v1-object.go
+++ b/cmd/xl-v1-object.go
@@ -452,13 +452,10 @@ func (xl xlObjects) getObjectInfo(ctx context.Context, bucket, object string) (o
        // Read metadata associated with the object from all disks.
        metaArr, errs := readAllXLMetadata(ctx, xl.getDisks(), bucket, object)

-       // get Quorum for this object
-       readQuorum, _, err := objectQuorumFromMeta(ctx, xl, metaArr, errs)
-       if err != nil {
-               return objInfo, err
-       }
+       // Needed quorum to get object information
+       objectInfoQuorum := len(xl.getDisks()) / 2

-       if reducedErr := reduceReadQuorumErrs(ctx, errs, objectOpIgnoredErrs, readQuorum); reducedErr != nil {
+       if reducedErr := reduceReadQuorumErrs(ctx, errs, objectOpIgnoredErrs, objectInfoQuorum); reducedErr != nil {
                return objInfo, reducedErr
        }

@@ -469,7 +466,7 @@ func (xl xlObjects) getObjectInfo(ctx context.Context, bucket, object string) (o
        modTime, _ := commonTime(modTimes)

        // Pick latest valid metadata.
-       xlMeta, err := pickValidXLMeta(ctx, metaArr, modTime, readQuorum)
+       xlMeta, err := pickValidXLMeta(ctx, metaArr, modTime, objectInfoQuorum)
        if err != nil {
                return objInfo, err
        }
```

## Steps to Reproduce (for bugs)

 
```
$ MINIO_STORAGE_CLASS_STANDARD=EC:4 minio server /tmp/xl/{1..12}

$ mc mb myminio/testbucket && mc cp file myminio/testbucket/

$ rm -rf /tmp/xl/{1..5}/testbucket/file/  # file object does not have read quorum any more
$ mc cp file myminio/testbucket/file # freeze
```

## Context
Fixing a bug

## Regression
No

## Your Environment
All

### PR DESCRIPTION
**Pull request by vadmeste**
## Description
getObjectInfo() checks if a given object has enough xl.json in disks, returns 404 if not and added .CORRUPTED suffix to object.

## Motivation and Context
Fixes #6575 and #6591 

## Regression
No

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added unit tests to cover my changes.
- [ ] I have added/updated functional tests in [mint](https://github.com/minio/mint). (If yes, add `mint` PR # here: )
- [x] All new and existing tests passed.

### CODE REVIEW

**Review by harshavardhana — APPROVED** [review]
LGTM as agreed and tested.

**Review by kannappanr — DISMISSED** [review]
LGTM

**Comment by kannappanr** [comment]
Here is what was discussed on what needs to be done
1. Object without read quorum will be displayed with a `.CORRUPTED` extension
2. User should be able to delete this object using the `RemoveObject` API
3. There should be a best effort to be able to download a partial object.

**Comment by vadmeste** [comment]
> 1. Object without read quorum will be displayed with a `.CORRUPTED` extension

What's the real reason for this? 

When we will add .CORRUPTED extension ? I suggest that healing should do this, I mean renaming objects that healing was unable to heal to add .CORRUTPED extension.

**Comment by harshavardhana** [comment]
Well there are problems adding extensions causes Listing to be all clobbered up. So I think the solution needs more discussion.

**Comment by vadmeste** [comment]
> Well there are problems adding extensions causes Listing to be all clobbered up.

yeah I agree, that's why I suggested that healing does the rename of these objects to add .CORRUPTED extension, but also I am not sure why we add that extension in the first place.

**Comment by harshavardhana** [comment]
Will explain @vadmeste here in a bit about final approach, just discussed.

**Review by harshavardhana — CHANGES_REQUESTED** [review]
I discussed with @abperiasamy the changes here are fine but we also have to make few more changes, i.e we should rename the object which are stale with "objectName.CORRUPTED" atomically. 

Also allow them to be available in the listing output such that they can be deleted by `mc rm`. 

What we need to do should be carefully understood here 

- First we read the `xl.json` from all disks and then ascertain how many disks its missing
- Then pick one of the common `xl.json` and decide the quorum. 
- Once the quorum is obtained see how many places the object still exists, rename all of them as objectName.corrupted
- Recreate empty objects on non-existent disks such as objectName.CORRUPTED with `xl.json` 
- This would allow for quorum and for the objects to be deleted.

All of this happens inside a ReadLock which is okay since other write locks will be blocked, we don't need to acquire a new write lock. Similar to healing but we are actively doing this during GetObjectInfo()

**Comment by harshavardhana** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-gateway-s3.sh | :heavy_exclamation_mark: [more...](#da34e099-4a22-422f-bfdf-ff951161d759) |
| mint-gateway-azure.sh | :heavy_exclamation_mark: [more...](#4c086a31-3aa6-4ed9-9f31-d04c0f69b604) |
| mint-xl.sh | :heavy_exclamation_mark: [more...](#03b07a4e-223e-4bd8-af0b-f7b3fb493d6b) |
| mint-gateway-nas.sh | :heavy_exclamation_mark: [more...](#4621c653-aa2a-4d77-b22e-30ac702da57d) |
| mint-large-bucket.sh | :heavy_exclamation_mark: [more...](#79f1f79d-cc3b-44ca-8730-047ce06a4b15) |
| mint-worm.sh | :heavy_exclamation_mark: [more...](#6a20d74e-3fb4-4c60-9551-1c17b88ef5c1) |
| mint-fs.sh | :heavy_exclamation_mark: [more...](#0a900c61-d25c-468c-8b87-41883ff868af) |
| mint-dist-xl.sh | :heavy_exclamation_mark: [more...](#a1978ea2-e0db-470c-b7a6-bbae7f106287) |
<a name="a1978ea2-e0db-470c-b7a6-bbae7f106287"></a>
### 6592-d5a64e5/mint-dist-xl.sh.xtrace:
```
DISABLED TIME BEING
```
<a name="6a20d74e-3fb4-4c60-9551-1c17b88ef5c1"></a>
### 6592-d5a64e5/mint-worm.sh.xtrace:
```
DISABLED TIME BEING
```
<a name="4c086a31-3aa6-4ed9-9f31-d04c0f69b604"></a>
### 6592-d5a64e5/mint-gateway-azure.sh.xtrace:
```
DISABLED TIME BEING
```
<a name="79f1f79d-cc3b-44ca-8730-047ce06a4b15"></a>
### 6592-d5a64e5/mint-large-bucket.sh.xtrace:
```
DISABLED TIME BEING
```
<a name="0a900c61-d25c-468c-8b87-41883ff868af"></a>
### 6592-d5a64e5/mint-fs.sh.xtrace:
```
DISABLED TIME BEING
```
<a name="da34e099-4a22-422f-bfdf-ff951161d759"></a>
### 6592-d5a64e5/mint-gateway-s3.sh.xtrace:
```
DISABLED TIME BEING
```
<a name="03b07a4e-223e-4bd8-af0b-f7b3fb493d6b"></a>
### 6592-d5a64e5/mint-xl.sh.xtrace:
```
DISABLED TIME BEING
```
<a name="4621c653-aa2a-4d77-b22e-30ac702da57d"></a>
### 6592-d5a64e5/mint-gateway-nas.sh.xtrace:
```
DISABLED TIME BEING
```

**Comment by vadmeste** [comment]
> * Recreate empty objects on non-existent disks such as objectName.CORRUPTED with `xl.json`
> * This would allow for quorum and for the objects to be deleted.

@harshavardhana I think recreating empty object is not needed.

I know that the general rule is that we should not allow deleting an object if there is no write quorum
but I think we can consider errFileNotFound errors reported by some disks as success in case of DELETE. Hence, I think it is okay to allow deleting if the number errs of 'nil' & 'errFileNotFound' >= writeQuorum.

**Comment by vadmeste** [comment]
> I know that the general rule is that we should not allow deleting an object if there is no write quorum
> but I think we can consider errFileNotFound errors reported by some disks as success in case of DELETE. Hence, I think it is okay to allow deleting if the number errs of 'nil' & 'errFileNotFound' >= writeQuorum.

By the way, that's how it is working right now. I investigated this before.

**Comment by harshavardhana** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-gateway-s3.sh | :heavy_exclamation_mark: [more...](#bd63ce10-9f14-49f5-89cf-a3001bcf5880) |
| mint-gateway-azure.sh | :heavy_exclamation_mark: [more...](#bbbbe2ef-c104-4a27-bed8-71447c981c3a) |
| mint-xl.sh | :heavy_exclamation_mark: [more...](#8e93eb48-066b-425c-99c5-3cf7a4e9a659) |
| mint-gateway-nas.sh | :heavy_exclamation_mark: [more...](#e0d78f09-ee20-4ee6-8b77-20c1a2e873b3) |
| mint-large-bucket.sh | :heavy_exclamation_mark: [more...](#a7d8c25c-ae1d-45c7-bfc6-f0578ee80528) |
| mint-worm.sh | :heavy_exclamation_mark: [more...](#954c9320-d03b-4483-9e0b-10e10ba261f9) |
| mint-fs.sh | :heavy_exclamation_mark: [more...](#d6748dee-d2e6-462f-8bdc-ff7eecc252d4) |
| mint-dist-xl.sh | :heavy_exclamation_mark: [more...](#30a1d5d5-ea91-49dd-bc89-9487aa84cd8d) |
<a name="a7d8c25c-ae1d-45c7-bfc6-f0578ee80528"></a>
### 6592-284f30d/mint-large-bucket.sh.xtrace:
```
DISABLED TIME BEING
```
<a name="954c9320-d03b-4483-9e0b-10e10ba261f9"></a>
### 6592-284f30d/mint-worm.sh.xtrace:
```
DISABLED TIME BEING
```
<a name="e0d78f09-ee20-4ee6-8b77-20c1a2e873b3"></a>
### 6592-284f30d/mint-gateway-nas.sh.xtrace:
```
DISABLED TIME BEING
```
<a name="bd63ce10-9f14-49f5-89cf-a3001bcf5880"></a>
### 6592-284f30d/mint-gateway-s3.sh.xtrace:
```
DISABLED TIME BEING
```
<a name="30a1d5d5-ea91-49dd-bc89-9487aa84cd8d"></a>
### 6592-284f30d/mint-dist-xl.sh.xtrace:
```
DISABLED TIME BEING
```
<a name="d6748dee-d2e6-462f-8bdc-ff7eecc252d4"></a>
### 6592-284f30d/mint-fs.sh.xtrace:
```
DISABLED TIME BEING
```
<a name="8e93eb48-066b-425c-99c5-3cf7a4e9a659"></a>
### 6592-284f30d/mint-xl.sh.xtrace:
```
DISABLED TIME BEING
```
<a name="bbbbe2ef-c104-4a27-bed8-71447c981c3a"></a>
### 6592-284f30d/mint-gateway-azure.sh.xtrace:
```
DISABLED TIME BEING
```

**Comment by harshavardhana** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-gateway-s3.sh | :heavy_exclamation_mark: [more...](#bb8b1600-ec21-49e0-ba3a-ec56f7c9068e) |
| mint-gateway-azure.sh | :heavy_exclamation_mark: [more...](#b6330db6-8e5a-4b34-961d-f4520503de90) |
| mint-xl.sh | :heavy_exclamation_mark: [more...](#d5bc4599-2a55-47de-be3e-765955ed9f14) |
| mint-gateway-nas.sh | :heavy_exclamation_mark: [more...](#0187bcb6-409a-445a-9c53-d4d4c2542845) |
| mint-large-bucket.sh | :heavy_exclamation_mark: [more...](#c3776a9f-0ffb-4029-8486-fc8f641d0a82) |
| mint-worm.sh | :heavy_exclamation_mark: [more...](#f7bf3298-e9cc-448c-ade7-d51710c2fc0b) |
| mint-fs.sh | :heavy_exclamation_mark: [more...](#aa9a580a-9330-4b16-9426-c9b934d6c891) |
| mint-dist-xl.sh | :heavy_exclamation_mark: [more...](#2cae8b33-f487-46fc-9484-ce078309c296) |
<a name="0187bcb6-409a-445a-9c53-d4d4c2542845"></a>
### 6592-8783b63/mint-gateway-nas.sh.xtrace:
```
DISABLED TIME BEING
```
<a name="2cae8b33-f487-46fc-9484-ce078309c296"></a>
### 6592-8783b63/mint-dist-xl.sh.xtrace:
```
DISABLED TIME BEING
```
<a name="d5bc4599-2a55-47de-be3e-765955ed9f14"></a>
### 6592-8783b63/mint-xl.sh.xtrace:
```
DISABLED TIME BEING
```
<a name="aa9a580a-9330-4b16-9426-c9b934d6c891"></a>
### 6592-8783b63/mint-fs.sh.xtrace:
```
DISABLED TIME BEING
```
<a name="c3776a9f-0ffb-4029-8486-fc8f641d0a82"></a>
### 6592-8783b63/mint-large-bucket.sh.xtrace:
```
DISABLED TIME BEING
```
<a name="b6330db6-8e5a-4b34-961d-f4520503de90"></a>
### 6592-8783b63/mint-gateway-azure.sh.xtrace:
```
DISABLED TIME BEING
```
<a name="f7bf3298-e9cc-448c-ade7-d51710c2fc0b"></a>
### 6592-8783b63/mint-worm.sh.xtrace:
```
DISABLED TIME BEING
```
<a name="bb8b1600-ec21-49e0-ba3a-ec56f7c9068e"></a>
### 6592-8783b63/mint-gateway-s3.sh.xtrace:
```
DISABLED TIME BEING
```

**Review by harshavardhana — CHANGES_REQUESTED** [review]
is this PR ready?

**Comment by minio-ops** [comment]
```
Error running mint automation
+ mkdir -p 6592-71a59c6/gopath/src/github.com/minio
+ git clone --quiet https://github.com/minio/minio.git 6592-71a59c6/gopath/src/github.com/minio/minio
++ cd 6592-71a59c6/gopath/src/github.com/minio/minio
++ git remote add minio https://github.com/minio/minio.git
++ cd 6592-71a59c6/gopath/src/github.com/minio/minio
++ git fetch --quiet minio pull/6592/head:pr6592
++ cd 6592-71a59c6/gopath/src/github.com/minio/minio
++ git checkout --quiet pr6592
++ minikube ip
+ minikube_ip=192.168.39.156
++ mkdir -p certs
++ cd certs
++ ./cert -host 192.168.39.156
2018/10/13 14:14:12 wrote public.crt
2018/10/13 14:14:12 wrote private.key
+ GOPATH=/mnt/nvme0n1p1/mint-auto/mint-auto/6592-71a59c6/gopath
+ make -C 6592-71a59c6/gopath/src/github.com/minio/minio --quiet
++ minikube docker-env
+ eval 'export DOCKER_TLS_VERIFY="1"
export DOCKER_HOST="tcp://192.168.39.156:2376"
export DOCKER_CERT_PATH="/mnt/nvme0n1p1/mint-auto/.minikube/certs"
export DOCKER_API_VERSION="1.35"
# Run this command to configure your shell:
# eval $(minikube docker-env)'
++ export DOCKER_TLS_VERIFY=1
++ DOCKER_TLS_VERIFY=1
++ export DOCKER_HOST=tcp://192.168.39.156:2376
++ DOCKER_HOST=tcp://192.168.39.156:2376
++ export DOCKER_CERT_PATH=/mnt/nvme0n1p1/mint-auto/.minikube/certs
++ DOCKER_CERT_PATH=/mnt/nvme0n1p1/mint-auto/.minikube/certs
++ export DOCKER_API_VERSION=1.35
++ DOCKER_API_VERSION=1.35
+ cp -af Dockerfile.mint-auto 6592-71a59c6/gopath/src/github.com/minio/minio/
+ docker build --quiet --tag minio/minio-6592-71a59c6 --file 6592-71a59c6/gopath/src/github.com/minio/minio/Dockerfile.mint-auto 6592-71a59c6/gopath/src/github.com/minio/minio
Sending build context to Docker daemon  113.6MB

Step 1/10 : FROM alpine:3.7
 ---> 34ea7509dcad
Step 2/10 : MAINTAINER Minio Inc <dev@minio.io>
 ---> Using cache
 ---> 00ec607a8456
Step 3/10 : COPY minio dockerscripts/docker-entrypoint.sh dockerscripts/healthcheck.sh /usr/bin/
 ---> e077ada902df
Step 4/10 : ENV MINIO_UPDATE off
 ---> Running in f5a744b5e61f
Removing intermediate container f5a744b5e61f
 ---> e0b1621543a7
Step 5/10 : RUN      apk add --no-cache ca-certificates curl su-exec>=0.2 &&      echo 'hosts: files mdns4_minimal [NOTFOUND=return] dns mdns4' >> /etc/nsswitch.conf &&      chmod +x /usr/bin/minio &&      chmod +x /usr/bin/docker-entrypoint.sh &&      chmod +x /usr/bin/healthcheck.sh
 ---> Running in 1ef286d335f9
[91mWARNING: Ignoring http://dl-cdn.alpinelinux.org/alpine/v3.7/main/x86_64/APKINDEX.tar.gz: temporary error (try again later)
[0m[91mERROR: unsatisfiable constraints:
[0mThe command '/bin/sh -c apk add --no-cache ca-certificates curl su-exec>=0.2 &&      echo 'hosts: files mdns4_minimal [NOTFOUND=return] dns mdns4' >> /etc/nsswitch.conf &&      chmod +x /usr/bin/minio &&      chmod +x /usr/bin/docker-entrypoint.sh &&      chmod +x /usr/bin/healthcheck.sh' returned a non-zero code: 3

```

**Comment by vadmeste** [comment]
This is not WIP anymore, but the code doesn't create empty files. As I said, Delete API already doesn't count nonexistent object in some disks as an error since this is already a confirmation of the Delete action. So Delete actually can remove objects that don't have quorum.

This PR modifies getObjectInfo(), but we should notice that this is a dangerous change because if there is any mistake anywhere, `mc ls -r` can rename all objects to .CORRUPTED and this also can happen for any regression in posix, storage rest server/client code. I am really not sure if it is worthy to do the rename in get object info in the first place.

File: cmd/xl-v1-object.go [hunk 1]
```diff
@@ -452,14 +453,35 @@ func (xl xlObjects) getObjectInfo(ctx context.Context, bucket, object string) (o
...
+		// We can consider an object data not reliable
+		// when xl.json is not found in read quorum disks.
+		var notFoundXLJSON int
+		for _, readErr := range errs {
+			if readErr == errFileNotFound {
+				notFoundXLJSON++
+			}
+		}
+		// If xl.json is not present in read quorum disks,
+		// add .CORRUPTION prefix to the current object.
```
Comment (harshavardhana) [inline cmd/xl-v1-object.go]: .CORRUPTED typo here.

File: cmd/xl-v1-object.go [hunk 2]
```diff
@@ -452,14 +453,35 @@ func (xl xlObjects) getObjectInfo(ctx context.Context, bucket, object string) (o
...
+		if len(xl.getDisks())-notFoundXLJSON < readQuorum {
+			rename(ctx, xl.getDisks(), bucket, object, bucket, object+xlCorruptedSuffix, true, len(xl.getDisks())/2+1, []error{errFileNotFound})
+			// Return err file not found since we renamed now the corrupted object
+			return objInfo, errFileNotFound
+		}
+	} else {
+		// If this is a corrupted object, change read quorum to N/2 disks
+		// so it will be visible to users, so they can delete it.
+		readQuorum = len(xl.getDisks()) / 2
```
Comment (harshavardhana) [inline cmd/xl-v1-object.go:485]: We can keep the read quorum similar to standard? And not n/2 ?

File: cmd/xl-v1-object.go [hunk 3]
```diff
@@ -452,14 +453,35 @@ func (xl xlObjects) getObjectInfo(ctx context.Context, bucket, object string) (o
...
+		var notFoundXLJSON int
+		for _, readErr := range errs {
+			if readErr == errFileNotFound {
+				notFoundXLJSON++
+			}
+		}
+		// If xl.json is not present in read quorum disks,
+		// add .CORRUPTION prefix to the current object.
+		if len(xl.getDisks())-notFoundXLJSON < readQuorum {
+			rename(ctx, xl.getDisks(), bucket, object, bucket, object+xlCorruptedSuffix, true, len(xl.getDisks())/2+1, []error{errFileNotFound})
```
Comment (harshavardhana) [inline cmd/xl-v1-object.go]: We can keep the quorum similar to global standard class ?

**Review by harshavardhana — CHANGES_REQUESTED** [review]
We have to be extra careful yes, but it is okay to make the object a user interactive responsibility.

We are not actively deleting anything so it is okay.

File: cmd/xl-v1-object.go (hunk 3 above)
Comment (vadmeste) [reply cmd/xl-v1-object.go]: > We can keep the quorum similar to global standard class ?

Fixed

File: cmd/xl-v1-object.go (hunk 1 above)
Comment (vadmeste) [reply cmd/xl-v1-object.go]: > .CORRUPTED typo here.

Fixed

File: cmd/xl-v1-object.go (hunk 2 above)
Comment (vadmeste) [reply cmd/xl-v1-object.go:485]: > We can keep the read quorum similar to standard? And not n/2 ?

We can't actually because otherwise the object won't be visible, the object is already corrupted anyway

**Comment by vadmeste** [comment]
ping @harshavardhana @kannappanr

**Review by harshavardhana — DISMISSED** [review]

**Comment by minio-ops** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-tls.sh | :heavy_check_mark: |
| mint-xl.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-worm.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-dist-xl.sh | :heavy_check_mark: |

**Comment by minio-ops** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-tls.sh | :heavy_check_mark: |
| mint-xl.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-worm.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-dist-xl.sh | :heavy_check_mark: |

**Review by kannappanr — APPROVED** [review]
LGTM

**Review by harshavardhana — APPROVED** [review]

**Comment by kannappanr** [comment]
Travis passed https://travis-ci.org/minio/minio/builds/442391767?utm_source=github_status&utm_medium=notification
