### PR TITLE
fix: Use mime encode for Non-US-ASCII metadata

### LINKED ISSUE #21256: Non-US-ASCII metadata can be set using a presigned `multipart/form-data` request
Non-US-ASCII metadata can be set using a presigned `multipart/form-data` request. Using the request, it is possible to set the metadata to a value containing umlauts (such as `ä`, `ö`), for example.

Clients that later on fetch this data are forced to disregard the data, although some clients may still parse non-US-ASCII chars. Also see https://github.com/apache/opendal/issues/6131#issuecomment-2844181340
> The HTTP specifications require the use of [only visible US-ASCII octets (VCHAR), SP, and HTAB](https://www.rfc-editor.org/rfc/rfc9110.html#name-field-values).

## Expected Behavior
Not sure, perhaps it should either be rejected or encoded?

https://docs.aws.amazon.com/AmazonS3/latest/userguide/UsingMetadata.html

>When using non-US-ASCII characters in your metadata values, the provided Unicode string is examined for non-US-ASCII characters. Values of such headers are character decoded as per [RFC 2047](https://datatracker.ietf.org/doc/html/rfc2047) before storing and encoded as per [RFC 2047](https://datatracker.ietf.org/doc/html/rfc2047) to make them mail-safe before returning. If the string contains only US-ASCII characters, it is presented as is.

## Steps to Reproduce (for bugs)
- set a metdata value using a presigned `multipart/form-data` request containing non-US-ASCII like `ö`
- request the metadata
- the http headers will contain non-US-ASCII (which will cause varying behaviour depending on the client)

## Your Environment
* Version used (`minio --version`): https://hub.docker.com/layers/minio/minio/latest/images/sha256-3f97c5651cb6662b880c787a232b6b34fec8d8922e08d6617b25d241a21164bb

### PR DESCRIPTION
**Pull request by jiuker**
fix: Use mime encode for Non-US-ASCII metadata

## Community Contribution License
All community contributions in this pull request are licensed to the project maintainers
under the terms of the [Apache 2 license](https://www.apache.org/licenses/LICENSE-2.0). 
By creating this pull request I represent that I have the right to license the 
contributions to the project maintainers under the Apache 2 license.

## Description

fix #21256

## How to test this PR?

```shell
mc cp main.go minio9000/mytest/ --attr="minio=Miniö"

# mc stat main.go s3/mytest/main.go

Name      : main.go
Date      : 2025-05-12 15:50:33 CST
Size      : 113 B
ETag      : 5228a21c835cfe6107c7a19f079aeb01
VersionID : b0ad1ece-d742-4cf0-a881-ca15cd748b6c
Type      : file
Metadata  :
  X-Amz-Meta-Minio: =?UTF-8?b?TWluacO2?=
  Content-Type    : application/octet-stream

```
Show `  X-Amz-Meta-Minio: Miniö` before

## Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Optimization (provides speedup with no functional changes)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [ ] Fixes a regression (If yes, please add `commit-id` or `PR #` here)
- [ ] Unit tests added/updated
- [ ] Internal documentation updated
- [ ] Create a documentation update request [here](https://github.com/minio/docs/issues/new?label=doc-change,title=Doc+Updated+Needed+For+PR+github.com%2fminio%2fminio%2fpull%2fNNNNN)

### CODE REVIEW

File: cmd/api-headers.go [hunk 1]
```diff
@@ -168,6 +170,31 @@ func setObjectHeaders(ctx context.Context, w http.ResponseWriter, objInfo Object
 			if !stringsHasPrefixFold(k, userMetadataPrefix) {
 				continue
 			}
+			// For metadata values like "ö" and "ÄMÄZÕÑ S3" tested against a real AWS S3 bucket, S3 may encode incorrectly.
+			// For example, "ö" was encoded as =?UTF-8?B?w4PCtg==?=, producing invalid UTF-8 instead
+			// of =?UTF-8?B?w7Y=?=. This mirrors errors like the ä½ in another string.
```
Comment (klauspost) [inline cmd/api-headers.go:176]: >> This mirrors errors like the ä½ in another string.

What does that mean?

File: cmd/api-headers.go [hunk 2]
```diff
@@ -168,6 +170,31 @@ func setObjectHeaders(ctx context.Context, w http.ResponseWriter, objInfo Object
...
+			//
+			// S3 uses B-encoding (Base64) for non-ASCII-heavy metadata and Q-encoding
+			// (quoted-printable) for mostly ASCII strings. Long strings are split at word
+			// boundaries to fit RFC 2047’s 75-character limit, ensuring HTTP parser
+			// compatibility.
```
Comment (klauspost) [inline cmd/api-headers.go:181]: Where is this info from?

File: cmd/api-headers.go [hunk 3]
```diff
@@ -168,6 +170,31 @@ func setObjectHeaders(ctx context.Context, w http.ResponseWriter, objInfo Object
...
+			//
+			// However, this splitting increases header size and can introduce errors, unlike Go’s
+			// mime package in MinIO, which correctly encodes strings with fixed B/Q encodings,
+			// avoiding S3’s heuristic-driven issues.
+			//
+			// For MinIO developers, decode S3 metadata with mime.WordDecoder, validate outputs,
+			// report encoding bugs to AWS, and use ASCII-only metadata to ensure reliable S3 API
+			// compatibility.
```
Comment (klauspost) [inline cmd/api-headers.go:189]: > report encoding bugs to AWS

What?

I don't understand this entire sentence?

**Comment by klauspost** [comment]
It seems like "How to test this PR?" just causes a regression the way you present it. Does AWS S3 do the same? Is there a bug in mc?

**Comment by jiuker** [comment]
> It seems like "How to test this PR?" just causes a regression the way you present it. Does AWS S3 do the same? Is there a bug in mc?

Yesh. AWS do the same sthing.
```
mc cp main.go s3/jiuker000/ --attr="minio=Miniö"
mc stat s3/jiuker000/main.go
Name      : main.go
Date      : 2025-05-12 16:17:17 CST
Size      : 113 B
ETag      : 5228a21c835cfe6107c7a19f079aeb01
VersionID : QWnzof3dYEkdvtQ8ftdZsfevgsxyDTAN
Type      : file
Encryption: SSE-S3
Metadata  :
  X-Amz-Meta-Minio: =?UTF-8?Q?Mini=C3=83=C2=B6?=
  Content-Type    : application/octet-stream
```
No mc bug. We add it to get/head object. 
All the info are @harshavardhana provided. And AWS s3 encode `ö` to `=?UTF-8?B?w4PCtg==?=`, but that use golang sdk decode is `Ã¶`, we found that aws s3 will add extra bytes[194/195] per each byte.
orgial: `[195 182 228 189 160 229 165 189 230 136 145 231 154 132 230 156 139 229 143 139]`
we send it to aws s3. and head the object and use golang decode we will got this:
decoded: `[195 131 194 182 195 164 194 189 194 160 195 165 194 165 194 189 195 166 194 136 194 145 195 167 194 154 194 132 195 166 194 156 194 139 195 165 194 143 194 139]`

No idea the rules. No any decode way in `aws-sdk-go`. So @harshavardhana said that is a bug..

**Comment by harshavardhana** [comment]
> It seems like "How to test this PR?" just causes a regression the way you present it. Does AWS S3 do the same? Is there a bug in mc?

bug in AWS S3 @klauspost

**Comment by harshavardhana** [comment]
It looks like @jiuker didn't add the comment that there is a bug in AWS S3, we should write that here in this code path.

**Comment by klauspost** [comment]
Add tests with samples referenced against AWS, so sending [xyz...] in the header should produce the same response [qwe...] as AWS. If you do that on the Server we are fine.

Also fix up minio-go, so it is round-trip safe. That means you get back what you send. If you did the server correctly, that should work against both AWS and MinIO servers.

**Comment by harshavardhana** [comment]
> Add tests with samples referenced against AWS, so sending [xyz...] in the header should produce the same response [qwe...] as AWS. If you do that on the Server we are fine.

@klauspost AWS returns wrong characters - here is missing comment from the PR that I had asked @jiuker to add. 

```
// For metadata values like "ö", "ÄMÄZÕÑ S3", and "öha, das 你好 sollte eigentlich
// funktionieren", tested against a real AWS S3 bucket, S3 may encode incorrectly. For
// example, "ö" was encoded as =?UTF-8?B?w4PCtg==?=, producing invalid UTF-8 instead
// of =?UTF-8?B?w7Y=?=. This mirrors errors like the ä½ in another string.
//
// S3 uses B-encoding (Base64) for non-ASCII-heavy metadata and Q-encoding
// (quoted-printable) for mostly ASCII strings. Long strings are split at word
// boundaries to fit RFC 2047’s 75-character limit, ensuring HTTP parser
// compatibility.
//
// However, this splitting increases header size and can introduce errors, unlike Go’s
// mime package in MinIO, which correctly encodes strings with fixed B/Q encodings,
// avoiding S3’s heuristic-driven issues.
//
// For MinIO developers, decode S3 metadata with mime.WordDecoder, validate outputs,
// report encoding bugs to AWS, and use ASCII-only metadata to ensure reliable S3 API
// compatibility.
```

**Comment by jiuker** [comment]
> > Add tests with samples referenced against AWS, so sending [xyz...] in the header should produce the same response [qwe...] as AWS. If you do that on the Server we are fine.添加测试，其中包含参考 AWS 的示例，因此发送[xyz.]在 header 中应该产生相同的响应[qwe...]作为 AWS。如果你在服务器上这样做，我们就很好。
> 
> @klauspost AWS returns wrong characters - here is missing comment from the PR that I had asked @jiuker to add.AWS 返回错误的字符-这里是我要求添加的 PR 中缺少的评论。
> 
> ```
> // For metadata values like "ö", "ÄMÄZÕÑ S3", and "öha, das 你好 sollte eigentlich
> // funktionieren", tested against a real AWS S3 bucket, S3 may encode incorrectly. For
> // example, "ö" was encoded as =?UTF-8?B?w4PCtg==?=, producing invalid UTF-8 instead
> // of =?UTF-8?B?w7Y=?=. This mirrors errors like the ä½ in another string.
> //
> // S3 uses B-encoding (Base64) for non-ASCII-heavy metadata and Q-encoding
> // (quoted-printable) for mostly ASCII strings. Long strings are split at word
> // boundaries to fit RFC 2047’s 75-character limit, ensuring HTTP parser
> // compatibility.
> //
> // However, this splitting increases header size and can introduce errors, unlike Go’s
> // mime package in MinIO, which correctly encodes strings with fixed B/Q encodings,
> // avoiding S3’s heuristic-driven issues.
> //
> // For MinIO developers, decode S3 metadata with mime.WordDecoder, validate outputs,
> // report encoding bugs to AWS, and use ASCII-only metadata to ensure reliable S3 API
> // compatibility.
> ```

Added

**Comment by klauspost** [comment]
@harshavardhana Yes. I saw your comment and asked for clarification since only half of it makes sense.

This should still have tests, either here or in mint.

**Comment by jiuker** [comment]
> @harshavardhana Yes. I saw your comment and asked for clarification since only half of it makes sense.
> 
> This should still have tests, either here or in mint.

Will have test for mint. @klauspost

**Review by harshavardhana — APPROVED** [review]

**Review by klauspost — APPROVED** [review]

**Review by shtripat — APPROVED** [review]
lgtm
