### PR TITLE
fix: remove DriveOPTimeout for REST callers as they don't work properly

### LINKED ISSUE #19853: s3.PutObject on single transaction failed for large file
## NOTE
Version 2024-05-28 18:49 fail if upload large file with one transaction (not multipart)
## Expected Behavior
If via WEB GUI upload large object, process will finish OK

## Current Behavior
when I upload a larger object using the website, "Resource request is unwritable, please reduce your request rate" appears after a while. If I use trace --debugg from mc I get the information "503 Service Unavailable" for s3.PutObject.

MultiPart upload of the same object is OK.

If I use the older version 2023-11-01T18:37:25Z everything is OK.

## Possible Solution
downgrade - but it is forbidden

## Steps to Reproduce (for bugs)
use Web UI and make upload large file (more then 700MB)
 
## Your Environment
4 servers (every 12 disk (11TB)
erasure-coding
OL8

### PR DESCRIPTION
**Pull request by harshavardhana**
## Community Contribution License
All community contributions in this pull request are licensed to the project maintainers
under the terms of the [Apache 2 license](https://www.apache.org/licenses/LICENSE-2.0). 
By creating this pull request I represent that I have the right to license the 
contributions to the project maintainers under the Apache 2 license.

## Description
fix: remove DriveOPTimeout for REST callers, as they don't work properly

## Motivation and Context
Go's net/http is notoriously difficult to have a streaming deadline per 
READ/WRITE on the net.Conn, if we add them, they will interfere with Go's 
internal requirements for an HTTP connection.

Remove this support for now.

fixes #19853

## How to test this PR?
Well, this is a removal of functionality.

## Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Optimization (provides speedup with no functional changes)
- [x] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [ ] Fixes a regression (If yes, please add `commit-id` or `PR #` here)
- [ ] Unit tests added/updated
- [ ] Internal documentation updated
- [ ] Create a documentation update request [here](https://github.com/minio/docs/issues/new?label=doc-change,title=Doc+Updated+Needed+For+PR+github.com%2fminio%2fminio%2fpull%2fNNNNN)

### CODE REVIEW

**Review by shtripat — APPROVED** [review]
lgtm

File: cmd/server-main.go [hunk 1]
```diff
@@ -414,11 +414,12 @@ func serverHandleCmdArgs(ctxt serverCtxt) {
 	setGlobalInternodeInterface(ctxt.Interface)
 
 	globalTCPOptions = xhttp.TCPOptions{
-		UserTimeout:    int(ctxt.UserTimeout.Milliseconds()),
-		DriveOPTimeout: globalDriveConfig.GetOPTimeout,
-		Interface:      ctxt.Interface,
-		SendBufSize:    ctxt.SendBufSize,
-		RecvBufSize:    ctxt.RecvBufSize,
+		UserTimeout: int(ctxt.UserTimeout.Milliseconds()),
+		// FIXME: Bring this back when we have valid way to handle deadlines
```
Comment (klauspost) [inline cmd/server-main.go:418]:
```suggestion
		// FIXME: Bring DriveOPTimeout back when we have valid way to handle deadlines
```

**Review by klauspost — APPROVED** [review]
