### PR TITLE
"0" offset is ignored in  GetObject method in Azure Gateway code

### LINKED ISSUE #191: minio-js fails with azure gateway
While running mint against azure gateway fails with below error

```
Running minio-js tests ... FAILED in 1 seconds
{ 
  "name": "minio-js",
  "function": "makeBucket(bucketName, region, cb)",
  "duration": 22,
  "status": "FAIL",
  "error": "S3Error: The specified bucket is not valid. at Object.parseError (node_modules/minio/dist/main/xml-parsers.js:56:11) at node_modules/minio/dist/main/transformers.js:117:22 at DestroyableTransform._flush (node_modules/minio/dist/main/transformers.js:48:26) at DestroyableTransform.<anonymous> (node_modules/minio/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:135:12) at finishMaybe (node_modules/minio/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:371:12) at endWritable (node_modules/minio/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:378:3) at DestroyableTransform.Writable.end (node_modules/minio/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:356:5) at IncomingMessage.onend (_stream_readable.js:511:10) at endReadableNT (_stream_readable.js:974:12) at _combinedTickCallback (internal/process/next_tick.js:80:11) at process._tickCallback (internal/process/next_tick.js:104:9)"
}
```

### PR DESCRIPTION
**Pull request by kannappanr**
## Description
In GetObject method, Check if startoffset is a non-negative value.
Ignore check for startOffset > and check for only length > 0.

Fixes minio/mint#191

## How Has This Been Tested?
Ran functional tests for minio-js against Minio server and Azure S3, and GCS gateways.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Review by balamurugana — DISMISSED** [review]

**Review by harshavardhana — COMMENTED** [review]
A title of the PR should have a basic description of the bug here.. @kannappanr 

"Fix bug in GetObject" is not explanatory

**Review by balamurugana — DISMISSED** [review]

File: cmd/gateway-azure.go [hunk 1]
```diff
@@ -475,7 +475,7 @@ func (a *azureObjects) ListObjectsV2(bucket, prefix, continuationToken, delimite
 // length indicates the total length of the object.
 func (a *azureObjects) GetObject(bucket, object string, startOffset int64, length int64, writer io.Writer) error {
 	blobRange := &storage.BlobRange{Start: uint64(startOffset)}
-	if length > 0 && startOffset > 0 {
```
Comment (krishnasrinivas) [inline cmd/gateway-azure.go]: as startOffset is never -ve you can just do:
`if length > 0 {...}`

**Review by krishnasrinivas — APPROVED** [review]

**Review by balamurugana — APPROVED** [review]
