### PR TITLE
S3 Select: Convert CSV data to JSON

### LINKED ISSUE #8458: S3 SELECT (javascript aws-sdk) does not work for strings/dates
_Moving this upon request from klauspost into a new issue._

I'm attempting to use the `aws-sdk` in JavaScript to leverage the `S3 SELECT` call on my MinIO back-end server. I originally looked for a MinIO-specific `S3 SELECT` command, but it seems for now that this is not supported - which I guess is fine if the aws-sdk gets full support. 

My challenge is that I'm trying to run a standard `S3 SELECT` call, fetching data from a CSV file (attached below) to get filtered column data. It works fine when I'm fetching numbers (floats, integers) - but if I try to fetch data from a column of strings/dates, it seems to break as in below.

Note that this issue seems to not only be limited to the parameters extracted, but also for string/date parameters being used as part of `WHERE` filters. For example, I'm unable to fetch data from before dateX and after dateY - as well as data, for which a string column is `in (stringX, stringY)`.

**Works OK:**
`sqlExpression: "SELECT EngineSpeed, BackUpLightandAlarmHornCommand FROM S3Object"`

**Does not seem to work:**
`sqlExpression: "SELECT segments FROM S3Object"`
`sqlExpression: "SELECT timestamps FROM S3Object"`

**Dataset:**
[test.zip](https://github.com/minio/minio/files/3779541/test.zip)

**Eror message (trying to fetch timestamps, which have "-" inside):**
```
"err InternalError: json: error calling MarshalJSON for type jstream.KVS: json: error calling MarshalJSON for type json.RawJSON: invalid character '-' after top-level value"
```

Any help would be greatly appreciated. We'd love to leverage this feature in our frontend so I hope full support will be possible. If any details are needed to replicate this, let me know.

Martin

### PR DESCRIPTION
**Pull request by klauspost**
## Description

Support conversion from CSV to JSON

Expected output match S3 Select.

## Motivation and Context

Fixes #8458

## How to test this PR?

CSV input tests added.

## Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)

### CODE REVIEW

**Comment by minio-ops** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-compression-xl.sh | :heavy_check_mark: |
| mint-compression-dist-xl.sh | :heavy_check_mark: |
| mint-compression-fs.sh | :heavy_check_mark: |
| mint-worm.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-xl.sh | :x: [more...](#2477c93f-fd56-4ff1-8423-3f67668e6671) |
| mint-large-bucket.sh | :x: [more...](#c8cae546-6e05-4f15-9a83-1f99dca812e7) |
| mint-fs.sh | :x: [more...](#5cf2066d-60b8-4410-b0e6-2e455a0b7f1b) |
| mint-dist-xl.sh | :x: [more...](#9900367c-3a5a-4446-b2d0-fd1c6a99dedb) |
<a name="c8cae546-6e05-4f15-9a83-1f99dca812e7"></a>
### 8464-f4894ac/mint-large-bucket.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.53:32511
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 5f2c2d9be068:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 3 seconds
(2/14) Running aws-sdk-java tests ... done in 1 seconds
(3/14) Running aws-sdk-php tests ... done in 1 minutes and 0 seconds
(4/14) Running aws-sdk-ruby tests ... done in 14 seconds
(5/14) Running awscli tests ... done in 2 minutes and 24 seconds
(6/14) Running healthcheck tests ... done in 0 seconds
(7/14) Running mc tests ... done in 1 minutes and 12 seconds
(8/14) Running minio-dotnet tests ... done in 1 minutes and 21 seconds
(9/14) Running minio-go tests ... FAILED in 4 minutes and 7 seconds
{
  "args": {},
  "duration": 104351,
  "error": "Please reduce your request",
  "function": "testStorageClassMetadataCopyObject()",
  "message": "CopyObject failed on RRS",
  "name": "minio-go: testStorageClassMetadataCopyObject",
  "status": "FAIL"
}

Executed 8 out of 14 tests successfully.
```
<a name="5cf2066d-60b8-4410-b0e6-2e455a0b7f1b"></a>
### 8464-f4894ac/mint-fs.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.53:31997
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 3f861727f948:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 1 seconds
(2/14) Running aws-sdk-java tests ... done in 1 seconds
(3/14) Running aws-sdk-php tests ... done in 41 seconds
(4/14) Running aws-sdk-ruby tests ... done in 2 seconds
(5/14) Running awscli tests ... done in 1 minutes and 55 seconds
(6/14) Running healthcheck tests ... done in 0 seconds
(7/14) Running mc tests ... done in 54 seconds
(8/14) Running minio-dotnet tests ... done in 26 seconds
(9/14) Running minio-go tests ... done in 1 minutes and 8 seconds
(10/14) Running minio-java tests ... done in 1 minutes and 36 seconds
(11/14) Running minio-js tests ... done in 43 seconds
(12/14) Running minio-py tests ... FAILED in 2 minutes and 12 seconds
{
  "error": "Traceback (most recent call last):\n  File \"/mint/run/core/minio-py/tests.py\", line 1341, in test_presigned_get_object_expiry_5sec\n    object_name).get_exception()\nminio.error.AccessDenied: AccessDenied: message: Access Denied\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"/mint/run/core/minio-py/tests.py\", line 2036, in main\n    test_presigned_get_object_expiry_5sec(client, log_output)\n  File \"/mint/run/core/minio-py/tests.py\", line 1355, in test_presigned_get_object_expiry_5sec\n    raise Exception(err)\nException: AccessDenied: message: Access Denied\n",
  "function": "presigned_get_object(bucket_name, object_name, expires, response_headers, request_date)",
  "message": "AccessDenied: message: Access Denied",
  "args": {
    "presigned_get_object_url": "http://72.28.97.53:31997/minio-py-test-b7b3ffcd-75f0-423c-8cd1-72af5f80c081/b662ebf2-d5ec-4ca3-8560-5d18045de647?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=minio%2F20191029%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20191029T164908Z&X-Amz-Expires=5&X-Amz-SignedHeaders=host&X-Amz-Signature=11cfaec76046227cfe01ab317bf2841defed011db65c0220c8541f60f1fbcd10",
    "response.headers": "{\"_container\": {\"accept-ranges\": [\"Accept-Ranges\", \"bytes\"], \"content-length\": [\"Content-Length\", \"440\"], \"content-security-policy\": [\"Content-Security-Policy\", \"block-all-mixed-content\"], \"content-type\": [\"Content-Type\", \"application/xml\"], \"server\": [\"Server\", \"MinIO/DEVELOPMENT.2019-10-29T16-20-05Z\"], \"vary\": [\"Vary\", \"Origin\"], \"x-amz-request-id\": [\"X-Amz-Request-Id\", \"15D22C25C8A5C210\"], \"x-xss-protection\": [\"X-Xss-Protection\", \"1; mode=block\"], \"date\": [\"Date\", \"Tue, 29 Oct 2019 16:49:20 GMT\"]}}",
    "response._body": "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<Error><Code>AccessDenied</Code><Message>Request has expired</Message><Key>b662ebf2-d5ec-4ca3-8560-5d18045de647</Key><BucketName>minio-py-test-b7b3ffcd-75f0-423c-8cd1-72af5f80c081</BucketName><Resource>/minio-py-test-b7b3ffcd-75f0-423c-8cd1-72af5f80c081/b662ebf2-d5ec-4ca3-8560-5d18045de647</Resource><RequestId>15D22C25C8A5C210</RequestId><HostId>43182913-e6df-487f-8e64-4b1e724709b6</HostId></Error>",
    "response.reason": "Forbidden",
    "response.status": 403,
    "object_name": "b662ebf2-d5ec-4ca3-8560-5d18045de647",
    "bucket_name": "minio-py-test-b7b3ffcd-75f0-423c-8cd1-72af5f80c081"
  },
  "duration": 58,
  "name": "minio-py:test_presigned_get_object_expiry_5sec",
  "status": "FAIL"
}

Executed 11 out of 14 tests successfully.
```
<a name="9900367c-3a5a-4446-b2d0-fd1c6a99dedb"></a>
### 8464-f4894ac/mint-dist-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.51:30000
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 906da54f8746:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 0 seconds
(2/14) Running aws-sdk-java tests ... done in 1 seconds
(3/14) Running aws-sdk-php tests ... done in 44 seconds
(4/14) Running aws-sdk-ruby tests ... done in 6 seconds
(5/14) Running awscli tests ... done in 1 minutes and 14 seconds
(6/14) Running healthcheck tests ... done in 0 seconds
(7/14) Running mc tests ... done in 50 seconds
(8/14) Running minio-dotnet tests ... done in 43 seconds
(9/14) Running minio-go tests ... done in 1 minutes and 51 seconds
(10/14) Running minio-java tests ... done in 2 minutes and 13 seconds
(11/14) Running minio-js tests ... done in 1 minutes and 0 seconds
(12/14) Running minio-py tests ... FAILED in 3 minutes and 55 seconds
{
  "message": "AccessDenied: message: Access Denied",
  "function": "presigned_get_object(bucket_name, object_name, expires, response_headers, request_date)",
  "status": "FAIL",
  "args": {
    "response.status": 403,
    "response._body": "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<Error><Code>AccessDenied</Code><Message>Request has expired</Message><Key>ec0cc2ec-b719-4b96-94af-5c0ea4314afe</Key><BucketName>minio-py-test-0e42a3cc-2c7a-42a1-b09d-10a65ddb7b6c</BucketName><Resource>/minio-py-test-0e42a3cc-2c7a-42a1-b09d-10a65ddb7b6c/ec0cc2ec-b719-4b96-94af-5c0ea4314afe</Resource><RequestId>15D22C4F71EE8A2A</RequestId><HostId>7278f83a-b199-4756-ab1f-f035fba052b1</HostId></Error>",
    "response.headers": "{\"_container\": {\"accept-ranges\": [\"Accept-Ranges\", \"bytes\"], \"content-length\": [\"Content-Length\", \"440\"], \"content-security-policy\": [\"Content-Security-Policy\", \"block-all-mixed-content\"], \"content-type\": [\"Content-Type\", \"application/xml\"], \"server\": [\"Server\", \"MinIO/DEVELOPMENT.2019-10-29T16-20-05Z\"], \"vary\": [\"Vary\", \"Origin\"], \"x-amz-request-id\": [\"X-Amz-Request-Id\", \"15D22C4F71EE8A2A\"], \"x-xss-protection\": [\"X-Xss-Protection\", \"1; mode=block\"], \"date\": [\"Date\", \"Tue, 29 Oct 2019 16:52:19 GMT\"]}}",
    "object_name": "ec0cc2ec-b719-4b96-94af-5c0ea4314afe",
    "response.reason": "Forbidden",
    "presigned_get_object_url": "http://72.28.97.51:30000/minio-py-test-0e42a3cc-2c7a-42a1-b09d-10a65ddb7b6c/ec0cc2ec-b719-4b96-94af-5c0ea4314afe?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=minio%2F20191029%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20191029T165206Z&X-Amz-Expires=5&X-Amz-SignedHeaders=host&X-Amz-Signature=a4b5b35a86bedb92b3d93d4d5ddf43b080d0334d98684cd5828edd863656fba2",
    "bucket_name": "minio-py-test-0e42a3cc-2c7a-42a1-b09d-10a65ddb7b6c"
  },
  "duration": 113,
  "name": "minio-py:test_presigned_get_object_expiry_5sec",
  "error": "Traceback (most recent call last):\n  File \"/mint/run/core/minio-py/tests.py\", line 1341, in test_presigned_get_object_expiry_5sec\n    object_name).get_exception()\nminio.error.AccessDenied: AccessDenied: message: Access Denied\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"/mint/run/core/minio-py/tests.py\", line 2036, in main\n    test_presigned_get_object_expiry_5sec(client, log_output)\n  File \"/mint/run/core/minio-py/tests.py\", line 1355, in test_presigned_get_object_expiry_5sec\n    raise Exception(err)\nException: AccessDenied: message: Access Denied\n"
}

Executed 11 out of 14 tests successfully.
```
<a name="2477c93f-fd56-4ff1-8423-3f67668e6671"></a>
### 8464-f4894ac/mint-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.52:32742
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 83e191f9c3bf:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 0 seconds
(2/14) Running aws-sdk-java tests ... done in 1 seconds
(3/14) Running aws-sdk-php tests ... done in 41 seconds
(4/14) Running aws-sdk-ruby tests ... done in 2 seconds
(5/14) Running awscli tests ... done in 1 minutes and 52 seconds
(6/14) Running healthcheck tests ... done in 0 seconds
(7/14) Running mc tests ... done in 58 seconds
(8/14) Running minio-dotnet tests ... done in 23 seconds
(9/14) Running minio-go tests ... done in 51 seconds
(10/14) Running minio-java tests ... FAILED in 22 seconds
error occurred
ErrorResponse(code=BucketNotEmpty, message=The bucket you tried to delete is not empty, bucketName=minio-java-test-2nb4g19, objectName=null, resource=/minio-java-test-2nb4g19, requestId=15D22BE47D773798, hostId=2a28e0aa-c0be-4533-8a1e-703f57d0178c)
request={method=DELETE, url=http://72.28.97.52:32742/minio-java-test-2nb4g19, headers=Host: 72.28.97.52:32742
User-Agent: MinIO (amd64; amd64) minio-java/dev
x-amz-content-sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
x-amz-date: 20191029T164440Z
Authorization: AWS4-HMAC-SHA256 Credential=*REDACTED*/20191029/us-east-1/s3/aws4_request, SignedHeaders=host;x-amz-content-sha256;x-amz-date, Signature=*REDACTED*
}
response={code=409, headers=Accept-Ranges: bytes
Content-Length: 328
Content-Security-Policy: block-all-mixed-content
Content-Type: application/xml
Server: MinIO/DEVELOPMENT.2019-10-29T16-20-05Z
Vary: Origin
X-Amz-Request-Id: 15D22BE47D773798
X-Xss-Protection: 1; mode=block
Date: Tue, 29 Oct 2019 16:44:40 GMT
}

	at io.minio.MinioClient.executeReq(MinioClient.java:1204)
	at io.minio.MinioClient.execute(MinioClient.java:1066)
	at io.minio.MinioClient.executeDelete(MinioClient.java:1372)
	at io.minio.MinioClient.removeBucket(MinioClient.java:3693)
	at FunctionalTest.teardown(FunctionalTest.java:403)
	at FunctionalTest.runTests(FunctionalTest.java:3075)
	at FunctionalTest.main(FunctionalTest.java:3148)

Executed 9 out of 14 tests successfully.
```
Error: No such image: minio/minio:8464-f4894ac

**Comment by sinhaashish** [comment]
@klauspost  I tried running the below query  on the data set provided in [issue](https://github.com/minio/minio/issues/8458) using MinIo master branch and it fetched me the correct result. Can you suggest how to replicate this issue so that i can test this PR.
```
sqlExpression: "SELECT segments FROM S3Object"
sqlExpression: "SELECT timestamps FROM S3Object"
```

**Comment by klauspost** [comment]
@sinhaashish 

You must output to JSON for the bug to show. Add `--json-output "rd=\n"` to mc.

**Review by sinhaashish — DISMISSED** [review]
Tested & LGTM

File: pkg/s3select/sql/value.go [hunk 1]
```diff
@@ -339,6 +340,52 @@ const (
 	opIneq = "!="
 )
 
+// InferBytesType will attempt to infer the data type of bytes.
+// Will fail if value type is not bytes or it would result in invalid utf8.
+// ORDER: int, float, bool, JSON, timestamp, string
+// If the content is valid JSON, the type will still be bytes.
+func (v *Value) InferBytesType() (err error) {
```
Comment (donatello) [inline pkg/s3select/sql/value.go:347]: @klauspost Where is this function used?

Comment (donatello) [reply pkg/s3select/sql/value.go:347]: It is actually unused.

**Comment by MatinF** [comment]
Happy to test this once added to the master

File: pkg/s3select/sql/value.go (hunk 1 above)
Comment (klauspost) [reply pkg/s3select/sql/value.go:347]: @donatello Correct. It seems like S3 always treats CSV values as "string". I guess I can just remove it.

Comment (harshavardhana) [reply pkg/s3select/sql/value.go:347]: What we also wished to do was type inference and make our users life simple - this is something we diverged in our implementation..

Comment (klauspost) [reply pkg/s3select/sql/value.go:347]: @harshavardhana  Yeah, that was my original thought, but it changes the output type, 

The tests would then give these results:
```
			query:      `SELECT num from s3object s WHERE id = 2`,
			wantResult: `{"num":"-5"}`,
->			wantResult: `{"num":-5}`,


			name:       "select-float-by-val",
			query:      `SELECT num2 from s3object s WHERE num2 = 0.765111`,
			wantResult: `{"num2":" 0.765111"}`,
->			wantResult: `{"num2":0.765111}`,

```
The string values are what S3 returns. So to be compatible I removed it - and thus why it is inactive. Of course values are still inferred for select comparisons, etc.

**Comment by minio-ops** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-compression-xl.sh | :heavy_check_mark: |
| mint-xl.sh | :heavy_check_mark: |
| mint-compression-dist-xl.sh | :heavy_check_mark: |
| mint-compression-fs.sh | :heavy_check_mark: |
| mint-worm.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :x: [more...](#d20e7dc2-6875-4946-ae36-32a71d8ceb2c) |
| mint-dist-xl.sh | :x: [more...](#3f4fe614-a510-422f-a544-d0eacf7cb813) |
<a name="3f4fe614-a510-422f-a544-d0eacf7cb813"></a>
### 8464-02c8eaa/mint-dist-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.52:30616
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 98341b9f6350:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 1 seconds
(2/14) Running aws-sdk-java tests ... done in 1 seconds
(3/14) Running aws-sdk-php tests ... done in 44 seconds
(4/14) Running aws-sdk-ruby tests ... done in 3 seconds
(5/14) Running awscli tests ... done in 2 minutes and 10 seconds
(6/14) Running healthcheck tests ... done in 0 seconds
(7/14) Running mc tests ... done in 57 seconds
(8/14) Running minio-dotnet tests ... done in 48 seconds
(9/14) Running minio-go tests ... done in 1 minutes and 8 seconds
(10/14) Running minio-java tests ... done in 1 minutes and 37 seconds
(11/14) Running minio-js tests ... done in 51 seconds
(12/14) Running minio-py tests ... FAILED in 3 minutes and 1 seconds
{
  "name": "minio-py:test_presigned_get_object_response_headers",
  "error": "Traceback (most recent call last):\n  File \"/mint/run/core/minio-py/tests.py\", line 1400, in test_presigned_get_object_response_headers\n    returned_content_language = response.headers['Content-Language']\n  File \"/usr/local/lib/python3.5/dist-packages/urllib3/_collections.py\", line 156, in __getitem__\n    val = self._container[key.lower()]\nKeyError: 'content-language'\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"/mint/run/core/minio-py/tests.py\", line 2043, in main\n    test_presigned_get_object_response_headers(client, log_output)\n  File \"/mint/run/core/minio-py/tests.py\", line 1418, in test_presigned_get_object_response_headers\n    raise Exception(err)\nException: 'content-language'\n",
  "function": "presigned_get_object(bucket_name, object_name, expires, response_headers, request_date)",
  "duration": 104,
  "args": {
    "object_name": "603cf8d5-cc03-4da1-b269-6dda415dc0d7",
    "bucket_name": "minio-py-test-ea3a082d-e85c-4f5f-bdd4-21bfa533da9c",
    "presigned_get_object_url": "http://72.28.97.52:30616/minio-py-test-ea3a082d-e85c-4f5f-bdd4-21bfa533da9c/603cf8d5-cc03-4da1-b269-6dda415dc0d7?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=minio%2F20191104%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20191104T091942Z&X-Amz-Expires=5&X-Amz-SignedHeaders=host&response-content-language=en_US&response-content-type=text%2Fplain&X-Amz-Signature=bed00911cad041e6f84c099bc278e7a24454bc1b556cbbcbe79b92f13362ae32"
  },
  "status": "FAIL",
  "message": "'content-language'"
}

Executed 11 out of 14 tests successfully.
```
<a name="d20e7dc2-6875-4946-ae36-32a71d8ceb2c"></a>
### 8464-02c8eaa/mint-large-bucket.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.55:30582
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp fbbb96bb40b7:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 2 seconds
(2/14) Running aws-sdk-java tests ... done in 1 seconds
(3/14) Running aws-sdk-php tests ... done in 53 seconds
(4/14) Running aws-sdk-ruby tests ... done in 12 seconds
(5/14) Running awscli tests ... done in 2 minutes and 29 seconds
(6/14) Running healthcheck tests ... done in 0 seconds
(7/14) Running mc tests ... done in 1 minutes and 12 seconds
(8/14) Running minio-dotnet tests ... done in 1 minutes and 26 seconds
(9/14) Running minio-go tests ... FAILED in 3 minutes and 23 seconds
{
  "args": {},
  "duration": 69527,
  "error": "Please reduce your request",
  "function": "testStorageClassMetadataCopyObject()",
  "message": "CopyObject failed on RRS",
  "name": "minio-go: testStorageClassMetadataCopyObject",
  "status": "FAIL"
}

Executed 8 out of 14 tests successfully.
```
Error: No such image: minio/minio:8464-02c8eaa

File: pkg/s3select/sql/value.go (hunk 1 above)
Comment (klauspost) [reply pkg/s3select/sql/value.go:347]: @donatello @harshavardhana We have these options:

1) Keep values as strings, remove this code.
2) Keep values as strings, keep the code (it could easily be useful)
3) Convert values so values represent their duck type.

I have no particular preference, though I think we should be as compatible as possible.

Comment (harshavardhana) [reply pkg/s3select/sql/value.go:347]: I think output being compatible with AWS is fine and also keeping the type inferred for comparisons is fine too.

**Comment by harshavardhana** [comment]
PTAL @donatello @sinhaashish

**Comment by donatello** [comment]
IIUC the current functionality infers types for comparison purposes, but keeps the string type for output compatibility, I think we can remove this unused function. I am not sure how it would be useful in the future - we usually don't keep unused code around. Either way I am approving this.

**Review by donatello — APPROVED** [review]

**Review by harshavardhana — APPROVED** [review]
