### PR TITLE
Use same timestamp for all chunks in chunked signature

### LINKED ISSUE #2804: signature: Streaming signature sporadic issue not reproducible always.
--- FAIL: TestAPIPutObjectStreamSigV4Handler (0.03s)
    object-handlers_test.go:281: Test 2: Expected the response status to be `200`, but instead found `500`
    object-handlers_test.go:291: Test 2: FS: Object content differs from expected value.: <?xml version="1.0" encoding="UTF-8"?>
        <Error><Code>InternalError</Code><Message>We encountered an internal error, please try again.</Message><Key></Key><BucketName></BucketName><Resource>/w1ts1q3judciakgiarh00nc69cgpmpvqedpozzugncu6hrhjsypwvxtdrhb3/test-object</Resource><RequestId>3L137</RequestId><HostId>3L137</HostId></Error>
FAIL

### PR DESCRIPTION
**Pull request by krisis**
Fixes #2804

### CODE REVIEW

**Comment by donatello** [comment]
That's it eh? :+1:

**Comment by krishnasrinivas** [comment]
:open_mouth:

File: cmd/test-utils_test.go [hunk 1]
```diff
@@ -539,21 +539,10 @@ func newTestStreamingRequest(method, urlStr string, dataLength, chunkSize int64,
...
-	if err != nil {
-		return nil, err
-	}
-
-	currTime := time.Now().UTC()
-	signature, err := signStreamingRequest(req, accessKey, secretKey, currTime)
-	if err != nil {
-		return nil, err
-	}
+func assembleStreamingChunks(req *http.Request, body io.ReadSeeker, chunkSize int64,
```
Comment (harshavardhana) [inline cmd/test-utils_test.go:542]: :+1:
