### PR TITLE
fix: allow bind on ipv6 loopback failures

### LINKED ISSUE #16305: IPv6 is attempted to use even if not supported
## Expected Behavior

No IPv6 shouldn't be used if system doesn't support it. It should be especially true if I hardcode addresses from command line. Why it should even attempt to bind ::1 ?

## Current Behavior

```
> ./minio server --address "127.0.0.1:9000" --console-address "127.0.0.1:9090" /miniodata

API: SYSTEM()
Time: 09:30:19 UTC 12/23/2022
Error: listen tcp [::1]:9000: bind: address family not supported by protocol (*net.OpError)
       2: internal/logger/logger.go:258:logger.LogIf()
       1: cmd/signals.go:79:cmd.handleSignals()
>
```

## Your Environment

```
> ./minio --version
minio version RELEASE.2022-12-12T19-27-27Z (commit-id=a469e6768df4d5d2cb340749fa58e4721a7dee96)
Runtime: go1.19.4 linux/amd64
License: GNU AGPLv3 <https://www.gnu.org/licenses/agpl-3.0.html>
Copyright: 2015-2022 MinIO, Inc.
> uname -sr
Linux 5.15.72
>
```

### PR DESCRIPTION
**Pull request by allanrogerr**
## Description
Allow binding to available addresses. If no binding is possible then report failure otherwise proceed silently
Fixes: https://github.com/minio/minio/issues/16305

## Motivation and Context
Even though user may not have ipv6 interfaces defined, on lo0 for example ```ifconfig lo0```, dns may be listening ipv6 ```sudo lsof -i :53 -S```. In this case, minio attempts to bind to that unbindable ipv6 address ```[::1]``` and is unable to start. It fails with error:
```
Error: listen tcp [::1]:9000: bind: can't assign requested address (*net.OpError)
```

## Steps: Reproduce using Ubuntu(A), MacOS(B)
Linux version A
```
ubuntu@minio:~$ uname -a
Linux minio 5.4.0-136-generic #153-Ubuntu SMP Thu Nov 24 15:59:04 UTC 2022 aarch64 aarch64 aarch64 GNU/Linux
```
go version
```
ubuntu@minio:~/minio$ go version
go version go1.19.4 linux/arm64
```

MacOS B
```
➜  ~ uname -a
Darwin Allans-MBP 22.2.0 Darwin Kernel Version 22.2.0: Fri Nov 11 02:03:51 PST 2022; root:xnu-8792.61.2~4/RELEASE_ARM64_T6000 arm64
```
go version
```
➜  ~ go version
go version go1.19.4 darwin/arm64
```

## Description
Allow binding to available addresses. If no binding is possible then report failure otherwise proceed silently
Fixes: https://github.com/minio/minio/issues/16305

## Motivation and Context
Even though user may not have ipv6 interfaces defined, on lo0 for example ```ifconfig lo0```, dns may be listening ipv6 ```sudo lsof -i :53 -S```. In this case, minio attempts to bind to that unbindable ipv6 address ```[::1]``` and is unable to start. It fails with error:
```
Error: listen tcp [::1]:9000: bind: can't assign requested address (*net.OpError)
```

## How to test this PR?
1. Clone, checkout and build minio:master
```
git clone https://github.com/minio/minio.git
cd minio
git checkout master
make build
go install -v 
```
2. Temporarily disable ipv6: 
A
```
ip addr show
sudo sysctl -w net.ipv6.conf.all.disable_ipv6=1
sudo sysctl -w net.ipv6.conf.default.disable_ipv6=1
sudo sysctl -w net.ipv6.conf.lo.disable_ipv6=1
ip addr show
```

B
```
sudo ifconfig lo0 inet6 ::1 delete
```

3. Run minio server with:
```
minio server --address "localhost:9000" --console-address "localhost:9090" <some empty folder>
```
4. Observe failure
```
Error: listen tcp [::1]:9000: bind: can't assign requested address (*net.OpError)
```
A

image

B

image

5. Pull, checkout and build fix
```
git clone https://github.com/allanrogerr/minio.git
cd minio
git pull --all
git checkout handle-unsupported-ipv6
make build
go install -v 
```
6. Run minio server with:
```
minio server --address "localhost:9000" --console-address "localhost:9090" <some empty folder>
```
7. Observe no failure
8. Revert ipv6 interface from Lo0: 
A
```
sudo sysctl -w net.ipv6.conf.all.disable_ipv6=0
sudo sysctl -w net.ipv6.conf.default.disable_ipv6=0
sudo sysctl -w net.ipv6.conf.lo.disable_ipv6=0
```

B
```
sudo ifconfig lo0 inet6 ::1 add
```

9. Run minio server with:
```
minio server --address "localhost:9000" --console-address "localhost:9090" <some empty folder>
```
image

10. Observe no failure

## Types of changes
- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Optimization (provides speedup with no functional changes)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [ ] Fixes a regression (If yes, please add `commit-id` or `PR #` here)
- [ ] Unit tests added/updated
- [ ] Internal documentation updated
- [ ] Create a documentation update request [here](https://github.com/minio/docs/issues/new?label=doc-change,title=Doc+Updated+Needed+For+PR+github.com%2fminio%2fminio%2fpull%2fNNNNN)

### CODE REVIEW

**Comment by minio-trusted** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-erasure.sh | :heavy_check_mark: |
| mint-compress-encrypt-dist-erasure.sh | :heavy_check_mark: |
| mint-pools.sh | :heavy_check_mark: |
| mint-dist-erasure.sh | :x: [more...](#3a31f125-9f09-412e-86fa-4aeafdac5359) |
<a name="3a31f125-9f09-412e-86fa-4aeafdac5359"></a>
### 16388-4baf4ce/mint-dist-erasure.sh.log:
```
Running with
SERVER_ENDPOINT:      15.15.15.3:31413
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0
RUN_ON_FAIL:          0

To get logs, run 'docker cp 059f2f097ba6:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 1 seconds
(2/14) Running aws-sdk-java tests ... done in 2 seconds
(3/14) Running aws-sdk-php tests ... done in 42 seconds
(4/14) Running aws-sdk-ruby tests ... done in 7 seconds
(5/14) Running awscli tests ... done in 1 minutes and 1 seconds
(6/14) Running healthcheck tests ... done in 0 seconds
(7/14) Running mc tests ... done in 15 seconds
(8/14) Running minio-go tests ... done in 46 seconds
(9/14) Running minio-java tests ... FAILED in 28 seconds
{
  "name": "minio-java",
  "function": "addUser()",
  "duration": 369,
  "status": "FAIL",
  "error": "java.lang.RuntimeException: Request failed with response: {\"Code\":\"InternalError\",\"Message\":\"We encountered an internal error, please try again. (Server not initialized, please try again)\",\"Resource\":\"/minio/admin/v3/add-user\",\"RequestId\":\"1738BDDCC0FED52D\",\"HostId\":\"fe137f90-fd33-408e-82ca-d855d14e571e\"}\n >>> [io.minio.admin.MinioAdminClient.execute(MinioAdminClient.java:206), io.minio.admin.MinioAdminClient.addUser(MinioAdminClient.java:237), TestMinioAdminClient.addUser(TestMinioAdminClient.java:47), TestMinioAdminClient.runAdminTests(TestMinioAdminClient.java:160), FunctionalTest.runTests(FunctionalTest.java:3782), FunctionalTest.runEndpointTests(FunctionalTest.java:3881), FunctionalTest.main(FunctionalTest.java:4002)]"
}
(9/14) Running minio-js tests ... done in 49 seconds
(10/14) Running minio-py tests ... done in 1 minutes and 41 seconds
(11/14) Running s3cmd tests ... done in 15 seconds
(12/14) Running s3select tests ... done in 4 seconds
(13/14) Running versioning tests ... done in 3 minutes and 5 seconds

Executed 13 out of 14 tests successfully.
```
Deleting image on docker hub
Deleting image locally

**Comment by minio-trusted** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-fs.sh | :heavy_check_mark: |
| mint-erasure.sh | :heavy_check_mark: |
| mint-dist-erasure.sh | :heavy_check_mark: |
| mint-compress-encrypt-dist-erasure.sh | :heavy_check_mark: |
| mint-pools.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :x: [more...](#da711254-2f06-4527-9d48-ccfa46913e60) |
<a name="da711254-2f06-4527-9d48-ccfa46913e60"></a>
### 16388-ffb385a/mint-large-bucket.sh.log:
```
Running with
SERVER_ENDPOINT:      15.15.15.1:31641
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0
RUN_ON_FAIL:          0

To get logs, run 'docker cp 0c94c564a3ce:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 1 seconds
(2/14) Running aws-sdk-java tests ... done in 2 seconds
(3/14) Running aws-sdk-php tests ... done in 42 seconds
(4/14) Running aws-sdk-ruby tests ... done in 7 seconds
(5/14) Running awscli tests ... done in 1 minutes and 0 seconds
(6/14) Running healthcheck tests ... done in 1 seconds
(7/14) Running mc tests ... done in 16 seconds
(8/14) Running minio-go tests ... done in 58 seconds
(9/14) Running minio-java tests ... FAILED in 40 seconds
{
  "name": "minio-java",
  "function": "getObjectRetention()",
  "duration": 78,
  "status": "FAIL",
  "error": "java.time.format.DateTimeParseException: Text '2023-01-10T20:43:11.6Z' could not be parsed at index 19 >>> [io.minio.Xml.unmarshal(Xml.java:55), io.minio.MinioAsyncClient.lambda$getObjectRetention$35(MinioAsyncClient.java:1738), java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:642), java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506), java.base/java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:2073), io.minio.S3Base$1.onResponse(S3Base.java:559), okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:519), java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128), java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628), java.base/java.lang.Thread.run(Thread.java:829)]"
}
(9/14) Running minio-js tests ... done in 51 seconds
(10/14) Running minio-py tests ... done in 1 minutes and 46 seconds
(11/14) Running s3cmd tests ... done in 15 seconds
(12/14) Running s3select tests ... done in 4 seconds
(13/14) Running versioning tests ... done in 3 minutes and 5 seconds

Executed 13 out of 14 tests successfully.
```
Deleting image on docker hub
Deleting image locally

**Comment by minio-trusted** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-erasure.sh | :heavy_check_mark: |
| mint-dist-erasure.sh | :heavy_check_mark: |
| mint-compress-encrypt-dist-erasure.sh | :heavy_check_mark: |
| mint-pools.sh | :heavy_check_mark: |
Deleting image on docker hub
Deleting image locally

**Comment by minio-trusted** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-fs.sh | :heavy_check_mark: |
| mint-erasure.sh | :heavy_check_mark: |
| mint-dist-erasure.sh | :heavy_check_mark: |
| mint-compress-encrypt-dist-erasure.sh | :heavy_check_mark: |
| mint-pools.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :x: [more...](#6dc75c8e-6c84-4a9a-8f41-e6eb08dc97f6) |
<a name="6dc75c8e-6c84-4a9a-8f41-e6eb08dc97f6"></a>
### 16388-4b96c2f/mint-large-bucket.sh.log:
```
Running with
SERVER_ENDPOINT:      15.15.15.7:30887
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0
RUN_ON_FAIL:          0

To get logs, run 'docker cp 100c3e809e1f:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 2 seconds
(2/14) Running aws-sdk-java tests ... done in 1 seconds
(3/14) Running aws-sdk-php tests ... done in 42 seconds
(4/14) Running aws-sdk-ruby tests ... done in 8 seconds
(5/14) Running awscli tests ... done in 1 minutes and 0 seconds
(6/14) Running healthcheck tests ... done in 0 seconds
(7/14) Running mc tests ... done in 15 seconds
(8/14) Running minio-go tests ... done in 50 seconds
(9/14) Running minio-java tests ... FAILED in 30 seconds
{
  "name": "minio-java",
  "function": "addUser()",
  "duration": 408,
  "status": "FAIL",
  "error": "java.lang.RuntimeException: Request failed with response: {\"Code\":\"InternalError\",\"Message\":\"We encountered an internal error, please try again. (Server not initialized, please try again)\",\"Resource\":\"/minio/admin/v3/add-user\",\"RequestId\":\"1738C935ED1B75C9\",\"HostId\":\"f1757b68-8ec5-46e2-88fc-f406d1e67d34\"}\n >>> [io.minio.admin.MinioAdminClient.execute(MinioAdminClient.java:206), io.minio.admin.MinioAdminClient.addUser(MinioAdminClient.java:237), TestMinioAdminClient.addUser(TestMinioAdminClient.java:47), TestMinioAdminClient.runAdminTests(TestMinioAdminClient.java:160), FunctionalTest.runTests(FunctionalTest.java:3782), FunctionalTest.runEndpointTests(FunctionalTest.java:3881), FunctionalTest.main(FunctionalTest.java:4002)]"
}
(9/14) Running minio-js tests ... done in 50 seconds
(10/14) Running minio-py tests ... done in 1 minutes and 48 seconds
(11/14) Running s3cmd tests ... done in 15 seconds
(12/14) Running s3select tests ... done in 5 seconds
(13/14) Running versioning tests ... done in 3 minutes and 5 seconds

Executed 13 out of 14 tests successfully.
```
Deleting image on docker hub
Deleting image locally

**Comment by minio-trusted** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-erasure.sh | :heavy_check_mark: |
| mint-dist-erasure.sh | :heavy_check_mark: |
| mint-compress-encrypt-dist-erasure.sh | :heavy_check_mark: |
| mint-pools.sh | :x: [more...](#852a8fb0-3b9e-404b-8d5b-f6e22c0dcbfb) |
<a name="852a8fb0-3b9e-404b-8d5b-f6e22c0dcbfb"></a>
### 16388-1161e50/mint-pools.sh.log:
```
Running with
SERVER_ENDPOINT:      15.15.15.1:32728
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0
RUN_ON_FAIL:          0

To get logs, run 'docker cp e9398bf0726f:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 1 seconds
(2/14) Running aws-sdk-java tests ... FAILED in 2 seconds
Jan 10, 2023 12:39:01 AM com.amazonaws.util.Base64 warn
WARNING: JAXB is unavailable. Will fallback to SDK implementation which may be less performant.If you are using Java 9+, you will need to include javax.xml.bind:jaxb-api as a dependency.
Exception in thread "main" com.amazonaws.services.s3.model.AmazonS3Exception: We encountered an internal error, please try again.: cause(listPathRaw: 0 drives provided) (Service: Amazon S3; Status Code: 500; Error Code: InternalError; Request ID: 1738CB9E4151FD45; S3 Extended Request ID: f26ad4de-ace1-42a3-967f-2edcd95d12a1), S3 Extended Request ID: f26ad4de-ace1-42a3-967f-2edcd95d12a1
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.handleErrorResponse(AmazonHttpClient.java:1742)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.handleServiceErrorResponse(AmazonHttpClient.java:1371)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeOneRequest(AmazonHttpClient.java:1347)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeHelper(AmazonHttpClient.java:1127)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.doExecute(AmazonHttpClient.java:784)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeWithTimer(AmazonHttpClient.java:752)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.execute(AmazonHttpClient.java:726)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.access$500(AmazonHttpClient.java:686)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutionBuilderImpl.execute(AmazonHttpClient.java:668)
	at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:532)
	at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:512)
	at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:5052)
	at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:4998)
	at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:4992)
	at com.amazonaws.services.s3.AmazonS3Client.listObjects(AmazonS3Client.java:895)
	at com.amazonaws.services.s3.AmazonS3Client.listObjects(AmazonS3Client.java:863)
	at io.minio.awssdk.tests.FunctionalTests.teardown(Unknown Source)
	at io.minio.awssdk.tests.FunctionalTests.main(Unknown Source)
(2/14) Running aws-sdk-php tests ... done in 43 seconds
(3/14) Running aws-sdk-ruby tests ... done in 7 seconds
(4/14) Running awscli tests ... FAILED in 32 seconds
{
  "name": "awscli",
  "duration": 13203,
  "function": "delete_bucket\n",
  "status": "FAIL",
  "error": "fatal error: An error occurred (InternalError) when calling the ListObjectsV2 operation (reached max retries: 4): We encountered an internal error, please try again.: cause(listPathRaw: 0 drives provided)remove_bucket failed: Unable to delete all objects in the bucket, bucket will not be deleted."
}
(4/14) Running healthcheck tests ... done in 0 seconds
(5/14) Running mc tests ... FAILED in 31 seconds
{
  "name": "mc",
  "duration": "6648",
  "function": "test_mv_object",
  "status": "FAIL",
  "error": "/mint/run/core/mc/mc --config-dir /tmp/.mc-19653 --quiet --no-color stat myminio/mc-test-bucket-17539/dir-13439-9758/object-1  >>> \nmc: <ERROR> Unable to list folder. We encountered an internal error, please try again.: cause(listPathRaw: 0 drives provided)\nmc: <ERROR> Unable to stat `myminio/mc-test-bucket-17539/dir-13439-9758/object-1`. "
}
(5/14) Running minio-go tests ... FAILED in 1 minutes and 10 seconds
{
  "args": {
    "bucketName": "minio-go-test-kjokxaso0r3gjrit",
    "objectPrefix": "",
    "recursive": "true"
  },
  "duration": 4244,
  "function": "ListObjects(bucketName, objectPrefix, recursive, doneCh)",
  "message": "ListObjects failed unexpectedly",
  "name": "minio-go: testListObjects",
  "status": "FAIL"
}
(5/14) Running minio-java tests ... FAILED in 8 seconds
{
  "name": "minio-java",
  "function": "listObjects()",
  "args": "[bucket]",
  "duration": 184,
  "status": "FAIL",
  "error": "error occurred\nErrorResponse(code = InternalError, message = We encountered an internal error, please try again.: cause(listPathRaw: 0 drives provided), bucketName = minio-java-test-cg7i7f, objectName = null, resource = /minio-java-test-cg7i7f, requestId = 1738CBCADAEED891, hostId = f26ad4de-ace1-42a3-967f-2edcd95d12a1)\nrequest={method=GET, url=http://15.15.15.1:32728/minio-java-test-cg7i7f?list-type=2&prefix=&max-keys=1000&encoding-type=url&delimiter=%2F, headers=Host: 15.15.15.1:32728\nAccept-Encoding: identity\nUser-Agent: MinIO (Linux; amd64) minio-java/8.4.6\nContent-MD5: 1B2M2Y8AsgTpgAmY7PhCfg==\nx-amz-content-sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855\nx-amz-date: 20230110T004213Z\nAuthorization: ██\n}\nresponse={code=500, headers=Accept-Ranges: bytes\nContent-Length: 372\nContent-Security-Policy: block-all-mixed-content\nContent-Type: application/xml\nServer: MinIO\nStrict-Transport-Security: max-age=31536000; includeSubDomains\nVary: Origin\nVary: Accept-Encoding\nX-Amz-Request-Id: 1738CBCADAEED891\nX-Content-Type-Options: nosniff\nX-Xss-Protection: 1; mode=block\nDate: Tue, 10 Jan 2023 00:42:13 GMT\n}\n >>> [io.minio.S3Base$1.onResponse(S3Base.java:690), okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:519), java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128), java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628), java.base/java.lang.Thread.run(Thread.java:829)]"
}
(5/14) Running minio-js tests ... done in 52 seconds
(6/14) Running minio-py tests ... done in 1 minutes and 53 seconds
(7/14) Running s3cmd tests ... done in 16 seconds
(8/14) Running s3select tests ... done in 4 seconds
(9/14) Running versioning tests ... done in 3 minutes and 37 seconds

Executed 9 out of 14 tests successfully.
```
Deleting image on docker hub
Deleting image locally

File: internal/http/listener.go [hunk 1]
```diff
@@ -136,20 +137,39 @@ func newHTTPListener(ctx context.Context, serverAddrs []string) (listener *httpL
...
 	}
 
+	// Fail if no listeners found
+	if len(tcpListeners) == 0 {
+		// Report specific issue
+		if err != nil {
+			return nil, err
+		}
+		// Report general issue
+		err = fmt.Errorf("%v listeners found, expected at least 1", len(tcpListeners))
```
Comment (dilverse) [inline internal/http/listener.go]: since the if block already ensures the `tcpListeners` is `0` should we just update the error string to not use `len(tcpListeners))`?

File: internal/http/listener.go [hunk 2]
```diff
@@ -136,20 +137,39 @@ func newHTTPListener(ctx context.Context, serverAddrs []string) (listener *httpL
 		}
 	}()
 
+	// Silently ignore failure to bind on DNS cached ipv6 loopback
 	for _, serverAddr := range serverAddrs {
 		var l net.Listener
 		if l, err = listenCfg.Listen(ctx, "tcp", serverAddr); err != nil {
+			if strings.HasPrefix(serverAddr, "[::1]") {
```
Comment (vadmeste) [inline internal/http/listener.go]: Maybe let's log instead of doing this strings check in L144 and L153, then return when `len(tcpListeners) == 0`. as you already did below. This looks easier.

Also won't IPv4 be dead anytime soon ?

**Review by vadmeste — COMMENTED** [review]
Some comments

File: internal/http/listener.go (hunk 1 above)
Comment (allanrogerr) [reply internal/http/listener.go]: Thanks, I've removed the redundant calculation

File: internal/http/listener.go (hunk 2 above)
Comment (allanrogerr) [reply internal/http/listener.go]: Please take another look. I've removed the explicit ipv6 loopback string check. Is this what you meant?

**Comment by minio-trusted** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-fs.sh | :heavy_check_mark: |
| mint-erasure.sh | :heavy_check_mark: |
| mint-dist-erasure.sh | :heavy_check_mark: |
| mint-compress-encrypt-dist-erasure.sh | :heavy_check_mark: |
| mint-pools.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :x: [more...](#36c09026-6152-4de0-998c-c0062506687e) |
<a name="36c09026-6152-4de0-998c-c0062506687e"></a>
### 16388-1491d94/mint-large-bucket.sh.log:
```
Running with
SERVER_ENDPOINT:      15.15.15.8:32594
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0
RUN_ON_FAIL:          0

To get logs, run 'docker cp a8e3d8fb7f53:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 1 seconds
(2/14) Running aws-sdk-java tests ... done in 2 seconds
(3/14) Running aws-sdk-php tests ... done in 42 seconds
(4/14) Running aws-sdk-ruby tests ... done in 7 seconds
(5/14) Running awscli tests ... done in 1 minutes and 2 seconds
(6/14) Running healthcheck tests ... done in 0 seconds
(7/14) Running mc tests ... done in 16 seconds
(8/14) Running minio-go tests ... done in 52 seconds
(9/14) Running minio-java tests ... FAILED in 29 seconds
{
  "name": "minio-java",
  "function": "addUser()",
  "duration": 365,
  "status": "FAIL",
  "error": "java.lang.RuntimeException: Request failed with response: {\"Code\":\"InternalError\",\"Message\":\"We encountered an internal error, please try again. (Server not initialized, please try again)\",\"Resource\":\"/minio/admin/v3/add-user\",\"RequestId\":\"1738FAD886E64C49\",\"HostId\":\"fb138638-46c1-4568-acbc-6c7b08888c67\"}\n >>> [io.minio.admin.MinioAdminClient.execute(MinioAdminClient.java:206), io.minio.admin.MinioAdminClient.addUser(MinioAdminClient.java:237), TestMinioAdminClient.addUser(TestMinioAdminClient.java:47), TestMinioAdminClient.runAdminTests(TestMinioAdminClient.java:160), FunctionalTest.runTests(FunctionalTest.java:3782), FunctionalTest.runEndpointTests(FunctionalTest.java:3881), FunctionalTest.main(FunctionalTest.java:4002)]"
}
(9/14) Running minio-js tests ... done in 50 seconds
(10/14) Running minio-py tests ... done in 1 minutes and 48 seconds
(11/14) Running s3cmd tests ... done in 16 seconds
(12/14) Running s3select tests ... done in 4 seconds
(13/14) Running versioning tests ... done in 3 minutes and 5 seconds

Executed 13 out of 14 tests successfully.
```
Deleting image on docker hub
Deleting image locally

**Review by dvaldivia — APPROVED** [review]
Tested. LGTM.

File: internal/http/listener.go (hunk 2 above)
Comment (allanrogerr) [reply internal/http/listener.go]: Hi @vadmeste I need to revert this change since we want to see the failure if any of the explicit ipv4 addresses provided is invalid. We don't want to silently ignore this. Let me know your thoughts please.

Also, I spoke to @dvaldivia today and added more changes. We're want to gracefully let minio startup if the user **explicitly** tries to bind using ```localhost``` and the failure is on the ipv6 loopback.

**Comment by minio-trusted** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-erasure.sh | :heavy_check_mark: |
| mint-dist-erasure.sh | :heavy_check_mark: |
| mint-compress-encrypt-dist-erasure.sh | :heavy_check_mark: |
| mint-pools.sh | :heavy_check_mark: |
Deleting image on docker hub
Deleting image locally

**Review by harshavardhana — APPROVED** [review]
