### PR TITLE
Matches s3 invalid compression format error for 'mc sql'

### LINKED ISSUE #2997: mc sql: Error results causes retry
## Expected behavior

When an error occurs `mc` will print the error and exit.

## Actual behavior

When an error occurs with initial `mc sql` startup, mc keep retrying, eventually giving up after 2 minutes.

`mc: <ERROR> Unable to run sql We encountered an internal error, please try again.`

## Steps to reproduce the behavior

* Upload a file that is NOT a bz2 file as ` local/test/not-really.bz2`
* Execute a query `mc sql -e="SELECT * from s3object LIMIT 1" --csv-input "rd=\n,fh=USE,fd=;" local/test/not-really.bz2`

`mc` prints nothing, but just hangs.

MinIO prints out:
```
API: SelectObject(bucket=test, object=not-really.bz2)
Time: 04:59:14 PST 12/09/2019
DeploymentID: 4af8ce07-cd56-410f-af83-a858a26d6fb5
RequestID: 15DEB5629468CF2C
RemoteHost: ::1
Host: localhost:9000
UserAgent: MinIO (windows; amd64) minio-go/v6.0.45 mc/DEVELOPMENT.GOGET
Error: bzip2 data invalid: bad magic value
       4: cmd\api-errors.go:1743:cmd.toAPIErrorCode()
       3: cmd\api-errors.go:1768:cmd.toAPIError()
       2: cmd\object-handlers.go:222:cmd.objectAPIHandlers.SelectObjectContentHandler()
       1: net\http\server.go:2007:http.HandlerFunc.ServeHTTP()
```

Using `-debug` shows this going on:

```
mc: <DEBUG> POST /test/not-really.bz2?select=&select-type=2 HTTP/1.1                                                                                                               
Host: localhost:9000                                                                                                                                                               
User-Agent: MinIO (windows; amd64) minio-go/v6.0.45 mc/DEVELOPMENT.GOGET                                                                                                           
Content-Length: 537                                                                                                                                                                
Authorization: AWS4-HMAC-SHA256 Credential=minio/20191209/us-east-1/s3/aws4_request, SignedHeaders=content-md5;host;x-amz-content-sha256;x-amz-date, Signature=**REDACTED**        
Content-Md5: 2lqDk7nZC3VKMjWSDw1kXw==                                                                                                                                              
X-Amz-Content-Sha256: 84aa431585ea0e832777ce5bd7c07df41034af5db1bdfeb8f41eedd51c00b14f                                                                                             
X-Amz-Date: 20191209T130459Z                                                                                                                                                       
Accept-Encoding: gzip                                                                                                                                                              
                                                                                                                                                                                   
mc: <DEBUG> HTTP/1.1 500 Internal Server Error                                                                                                                                     
Content-Length: 337                                                                                                                                                                
Accept-Ranges: bytes                                                                                                                                                               
Content-Security-Policy: block-all-mixed-content                                                                                                                                   
Content-Type: application/xml                                                                                                                                                      
Date: Mon, 09 Dec 2019 13:04:59 GMT                                                                                                                                                
Server: MinIO/DEVELOPMENT.GOGET                                                                                                                                                    
Vary: Origin                                                                                                                                                                       
X-Amz-Request-Id: 15DEB5B2C29C51D4                                                                                                                                                 
X-Xss-Protection: 1; mode=block                                                                                                                                                    
                                                                                                                                                                                   
<?xml version="1.0" encoding="UTF-8"?>                                                                                                                                             
<Error><Code>InternalError</Code><Message>We encountered an internal error, please try again.</Message><Key>not-really.bz2</Key><BucketName>test</BucketName><Resource>/test/not-re
ally.bz2</Resource><RequestId>15DEB5B2C29C51D4</RequestId><HostId>4af8ce07-cd56-410f-af83-a858a26d6fb5</HostId></Error>mc: <DEBUG> Response Time:  99.7648ms                       
```
## mc version

- Latest master: 45df811a8911bb7c42531596448138bf90ae9423

## System information

Windows, 64 bit, shouldn't make any difference.

### PR DESCRIPTION
**Pull request by ebozduman**
## Description

`mc sql` command was issuing error messages about invalid compression formatted files in a different way than Amazon S3.
This fix rewords and adjusts these error messages.
Fixes minio/mc#2997 filed against `mc`

## Motivation and Context
S3 compatibility

## How to test this PR?
Copy a sample file, which is not in `"BZIP"` format, over into your MinIO bucket, and append `".bz2"` extension to the copied file name.
Then run the following command against your MinIO server:
```
mc sql -e="SELECT * from s3object LIMIT 1" --csv-input "rd=\n,fh=USE,fd=;" <MinIO-alias>/<bucket-name>/<file-name>.bz2
```
Run the same command with a file, not in `"GZIP"` format, but with `".gz"` extension.
Compare the above MinIO error messages with their S3 counterparts for the same commands. They should match.

## Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [ ] Fixes a regression (If yes, please add `commit-id` or `PR #` here)
- [ ] Documentation needed
- [ ] Unit tests needed
- [ ] Functional tests needed (If yes, add [mint](https://github.com/minio/mint) PR # here: )

### CODE REVIEW

**Comment by minio-ops** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-worm.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-dist-xl.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-xl.sh | :x: [more...](#266cfc1c-c3df-4064-93e9-5d5a8b23d1e7) |
| mint-large-bucket.sh | :x: [more...](#29f3c974-ec6e-436a-966a-91d382009c59) |
| mint-gateway-azure.sh | :x: [more...](#ceb37a9c-09b1-48fc-97c0-f5f8f94867fd) |
<a name="29f3c974-ec6e-436a-966a-91d382009c59"></a>
### 9067-189eb21/mint-large-bucket.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.55:30799
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 9464d19e8231:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... FAILED in 2 minutes and 0 seconds
{
  "alert": "",
  "args": {
    "bucketName": "aws-sdk-go-test-o5kbbhvuvzrrhh",
    "expiry": 60000000000,
    "objectName": "presignedTest"
  },
  "duration": 120268,
  "error": "RequestError: send request failed\ncaused by: Put http://72.28.97.55:30799/aws-sdk-go-test-o5kbbhvuvzrrhh: dial tcp 72.28.97.55:30799: i/o timeout",
  "function": "PresignedPut",
  "message": "AWS SDK Go CreateBucket Failed",
  "name": "aws-sdk-go",
  "status": "FAIL"
}

Executed 0 out of 14 tests successfully.
```
<a name="ceb37a9c-09b1-48fc-97c0-f5f8f94867fd"></a>
### 9067-189eb21/mint-gateway-azure.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.61:31005
ACCESS_KEY:           minioazure
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 4c84ecc78c0b:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 8 seconds
(2/14) Running aws-sdk-java tests ... done in 1 seconds
(3/14) Running aws-sdk-php tests ... done in 5 minutes and 22 seconds
(4/14) Running aws-sdk-ruby tests ... done in 17 seconds
(5/14) Running awscli tests ... done in 3 minutes and 8 seconds
(6/14) Running healthcheck tests ... done in 0 seconds
(7/14) Running mc tests ... done in 6 minutes and 36 seconds
(8/14) Running minio-dotnet tests ... done in 1 minutes and 43 seconds
(9/14) Running minio-go tests ... FAILED in 16 minutes and 9 seconds
{
  "args": {
    "bucketName": "minio-go-test-ghjifxgn6wf6me24",
    "objectName": "3j0qb6oinyhvov3nt3g9egrkzxlouc"
  },
  "duration": 90130,
  "error": "Get http://72.28.97.61:31005/minio-go-test-ghjifxgn6wf6me24/3j0qb6oinyhvov3nt3g9egrkzxlouc: Connection closed by foreign host http://72.28.97.61:31005/minio-go-test-ghjifxgn6wf6me24/3j0qb6oinyhvov3nt3g9egrkzxlouc. Retry again.",
  "function": "GetObject(bucketName, objectName)",
  "message": "ReadAt failed",
  "name": "minio-go: testGetObjectReadAtWhenEOFWasReached",
  "status": "FAIL"
}

Executed 8 out of 14 tests successfully.
```
<a name="266cfc1c-c3df-4064-93e9-5d5a8b23d1e7"></a>
### 9067-189eb21/mint-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.55:31432
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp a548b1a99bf3:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... FAILED in 2 minutes and 0 seconds
{
  "alert": "",
  "args": {
    "bucketName": "aws-sdk-go-test-jb3lg4p0teczmh",
    "expiry": 60000000000,
    "objectName": "presignedTest"
  },
  "duration": 120303,
  "error": "RequestError: send request failed\ncaused by: Put http://72.28.97.55:31432/aws-sdk-go-test-jb3lg4p0teczmh: dial tcp 72.28.97.55:31432: i/o timeout",
  "function": "PresignedPut",
  "message": "AWS SDK Go CreateBucket Failed",
  "name": "aws-sdk-go",
  "status": "FAIL"
}

Executed 0 out of 14 tests successfully.
```
Deleting image on docker hub
Deleting image locally

**Review by fwessels — APPROVED** [review]
LGTM

File: pkg/s3select/select.go [hunk 1]
```diff
@@ -302,9 +302,11 @@ func (s3Select *S3Select) Open(getReader func(offset, length int64) (io.ReadClos
 		s3Select.recordReader, err = csv.NewReader(s3Select.progressReader, &s3Select.Input.CSVArgs)
 		if err != nil {
 			rc.Close()
+			if strings.Contains(err.Error(), "bzip2 data invalid: bad magic value") {
```
Comment (harshavardhana) [inline pkg/s3select/select.go]: you should use, this covers all bzip2 structural errors.

```go
var stErr bzip2.StructuralError
if errors.As(err, &stErr) {
    return errInvalidBZIP2CompressionFormat(err)
}
```

File: pkg/s3select/progress.go [hunk 2]
```diff
@@ -101,6 +101,9 @@ func newProgressReader(rc io.ReadCloser, compType CompressionType) (*progressRea
 		r = scannedReader
 	case gzipType:
 		if r, err = gzip.NewReader(scannedReader); err != nil {
+			if err == gzip.ErrHeader {
```
Comment (harshavardhana) [inline pkg/s3select/progress.go]: The preferred way is this style

```go
if errors.Is(err, gzip.ErrHeader) || errors.Is(err, gzip.ErrChecksum) {
   return errInvalidGZIPCompressionFormat(err)
}
```

**Review by harshavardhana — CHANGES_REQUESTED** [review]

**Review by klauspost — APPROVED** [review]
Fix the issues mention and we should be fine.

File: pkg/s3select/select.go (hunk 1 above)
Comment (ebozduman) [reply pkg/s3select/select.go]: OK

File: pkg/s3select/progress.go (hunk 2 above)
Comment (ebozduman) [reply pkg/s3select/progress.go]: OK

**Review by harshavardhana — APPROVED** [review]

**Comment by minio-ops** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-xl.sh | :heavy_check_mark: |
| mint-worm.sh | :heavy_check_mark: |
| mint-dist-xl.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :x: [more...](#92473814-1472-4b47-8144-3f91494d7f03) |
| mint-fs.sh | :x: [more...](#eafe521e-05e5-4e89-a88d-da4a629813c3) |
| mint-gateway-azure.sh | :x: [more...](#0d9ff896-3350-4f31-8602-774bb306bf6d) |
<a name="92473814-1472-4b47-8144-3f91494d7f03"></a>
### 9067-58aa282/mint-large-bucket.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.55:32233
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 4d03ede09805:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... FAILED in 2 minutes and 0 seconds
{
  "alert": "",
  "args": {
    "bucketName": "aws-sdk-go-test-ylq13kezdjcpjr",
    "expiry": 60000000000,
    "objectName": "presignedTest"
  },
  "duration": 120268,
  "error": "RequestError: send request failed\ncaused by: Put http://72.28.97.55:32233/aws-sdk-go-test-ylq13kezdjcpjr: dial tcp 72.28.97.55:32233: i/o timeout",
  "function": "PresignedPut",
  "message": "AWS SDK Go CreateBucket Failed",
  "name": "aws-sdk-go",
  "status": "FAIL"
}

Executed 0 out of 14 tests successfully.
```
<a name="eafe521e-05e5-4e89-a88d-da4a629813c3"></a>
### 9067-58aa282/mint-fs.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.55:30099
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp ce9a5c35dabc:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... FAILED in 2 minutes and 1 seconds
{
  "alert": "",
  "args": {
    "bucketName": "aws-sdk-go-test-yql6nzfelskiex",
    "expiry": 60000000000,
    "objectName": "presignedTest"
  },
  "duration": 120337,
  "error": "RequestError: send request failed\ncaused by: Put http://72.28.97.55:30099/aws-sdk-go-test-yql6nzfelskiex: dial tcp 72.28.97.55:30099: i/o timeout",
  "function": "PresignedPut",
  "message": "AWS SDK Go CreateBucket Failed",
  "name": "aws-sdk-go",
  "status": "FAIL"
}

Executed 0 out of 14 tests successfully.
```
<a name="0d9ff896-3350-4f31-8602-774bb306bf6d"></a>
### 9067-58aa282/mint-gateway-azure.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.55:32540
ACCESS_KEY:           minioazure
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 034ff553a524:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... FAILED in 2 minutes and 1 seconds
{
  "alert": "",
  "args": {
    "bucketName": "aws-sdk-go-test-swm6yiazyy249i",
    "expiry": 60000000000,
    "objectName": "presignedTest"
  },
  "duration": 120304,
  "error": "RequestError: send request failed\ncaused by: Put http://72.28.97.55:32540/aws-sdk-go-test-swm6yiazyy249i: dial tcp 72.28.97.55:32540: i/o timeout",
  "function": "PresignedPut",
  "message": "AWS SDK Go CreateBucket Failed",
  "name": "aws-sdk-go",
  "status": "FAIL"
}

Executed 0 out of 14 tests successfully.
```
Deleting image on docker hub
Deleting image locally
