### PR TITLE
re-implement StorageInfo to be a peer call

### LINKED ISSUE #15959: Prometheus metric "minio_cluster_disk_offline_total" seems stuck even though all disks are online
## NOTE
If this case is urgent, please subscribe to [Subnet](https://min.io/pricing) so that our 24/7 support team may help you faster.

We notice that some of our Minio pods in Kubernetes keep reporting wrong # of disks offline for a long time. All disks are online. It seems the metric is somehow "stuck". A restart seems to lead to reporting accurate numbers again.

## Expected Behavior
The prometheus metric should report the accurate number as seen in the UI of with the `mc admin info` command.

## Current Behavior
Some pods are stuck on a very high number. This kind of very high number of offline disks can only occur during restart of some servers (which sometimes we have to do due to repairs or upgrades) en is temporarily. When the server or Minio pod comes back online, then the # of disks offline should be updated.

## Possible Solution
Workaround seems to be to restart the pod after which the numbers are accurate again.

## Steps to Reproduce (for bugs)
We noticed that on a production server. At the moment we don't have the facility to try to explicitly reproduce it.

## Context
If the number is not reported correctly it leads to false alarms which will make us turn off the alarm. If there is a real disk failure, we will not notice.

## Regression
Unknown.

## Your Environment
OpenShift 4.10
Minio Version: 2022-09-17T00:09:45Z
Minio Operator 4.5.1
CleanShot 2022-10-28 at 09 51 47

### PR DESCRIPTION
**Pull request by harshavardhana**
## Description
re-implement StorageInfo to be a peer call

## Motivation and Context
This PR also simplifies things, removing the
slice of []error returned that was pretty
much ignored by everyone, so it is removed.

- The state() of the drive error is captured properly, 
  so we simply rely on that for valid errors.

- add additional only "node" level metrics about offline 
  drives if any, just in case cluster metrics are not reliable.

- fix a typo in free inodes metric name to be node level, 
  not cluster.

fixes #15959

## How to test this PR?
As per #15959 

## Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Optimization (provides speedup with no functional changes)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [x] Fixes a regression (If yes, please add `commit-id` or `PR #` here)
- [ ] Unit tests added/updated
- [ ] Internal documentation updated
- [ ] Create a documentation update request [here](https://github.com/minio/docs/issues/new?label=doc-change,title=Doc+Updated+Needed+For+PR+github.com%2fminio%2fminio%2fpull%2fNNNNN)

### CODE REVIEW

File: cmd/peer-rest-server.go [hunk 1]
```diff
@@ -330,6 +330,23 @@ func (s *peerRESTServer) DownloadProfilingDataHandler(w http.ResponseWriter, r *
...
+
+	ctx := newContext(r, w, "LocalStorageInfo")
+
+	objLayer := newObjectLayerFn()
+	if objLayer == nil {
+		s.writeErrorResponse(w, errServerNotInitialized)
+		return
+	}
+
+	logger.LogIf(ctx, gob.NewEncoder(w).Encode(objLayer.LocalStorageInfo(GlobalContext)))
```
Comment (vadmeste) [inline cmd/peer-rest-server.go]: s/GlobalContext/r.Context() ?

File: cmd/metrics-realtime.go [hunk 2]
```diff
@@ -91,18 +91,16 @@ func collectLocalDisksMetrics(disks map[string]struct{}) map[string]madmin.DiskM
...
+	for _, d := range storageInfo.Disks {
 		if len(disks) != 0 {
 			_, ok := disks[d.Endpoint]
 			if !ok {
 				continue
 			}
 		}
 
-		if errs[i] != nil {
+		if d.State != madmin.DriveStateOk {
```
Comment (vadmeste) [inline cmd/metrics-realtime.go]: Let's ignore Unformatted disk as well

**Review by vadmeste — COMMENTED** [review]
Few comments

File: cmd/metrics-realtime.go (hunk 2 above)
Comment (harshavardhana) [reply cmd/metrics-realtime.go]: are you sure? @vadmeste

**Comment by minio-trusted** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-erasure.sh | :heavy_check_mark: |
| mint-dist-erasure.sh | :heavy_check_mark: |
| mint-compress-encrypt-dist-erasure.sh | :heavy_check_mark: |
| mint-pools.sh | :heavy_check_mark: |
Deleting image on docker hub
Deleting image locally

**Review by krisis — APPROVED** [review]

**Review by vadmeste — APPROVED** [review]
LGTM

**Comment by minio-trusted** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-erasure.sh | :heavy_check_mark: |
| mint-dist-erasure.sh | :heavy_check_mark: |
| mint-compress-encrypt-dist-erasure.sh | :heavy_check_mark: |
| mint-pools.sh | :x: [more...](#3a22df43-7e33-46fa-9d6c-08abce107166) |
<a name="3a22df43-7e33-46fa-9d6c-08abce107166"></a>
### 16155-36d6aac/mint-pools.sh.log:
```
Running with
SERVER_ENDPOINT:      15.15.15.6:32175
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0
RUN_ON_FAIL:          0

To get logs, run 'docker cp 951640e159bb:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 1 seconds
(2/14) Running aws-sdk-java tests ... done in 2 seconds
(3/14) Running aws-sdk-php tests ... done in 43 seconds
(4/14) Running aws-sdk-ruby tests ... done in 7 seconds
(5/14) Running awscli tests ... FAILED in 20 seconds
{
  "name": "awscli",
  "duration": 10818,
  "function": "aws --endpoint-url http://15.15.15.6:32175 s3api list-objects --bucket awscli-mint-test-bucket-30404 --prefix datafile-1-kB\n",
  "status": "FAIL",
  "error": ""
}
(5/14) Running healthcheck tests ... done in 0 seconds
(6/14) Running mc tests ... FAILED in 1 minutes and 7 seconds
{
  "name": "mc",
  "duration": "5330",
  "function": "test_mirror_list_objects",
  "status": "FAIL",
  "error": "mirror and list differs"
}
(6/14) Running minio-go tests ... FAILED in 47 seconds
{
  "args": {
    "bucketName": "minio-go-test-101rgbcamt9tavnq",
    "objectName": "uejpkjn5m4uzwl6t2khrmym2vsigt1"
  },
  "duration": 3872,
  "error": "We encountered an internal error, please try again.: cause(listPathRaw: 0 drives provided)",
  "function": "GetObject(bucketName, objectName)",
  "message": "CleanupBucket failed",
  "name": "minio-go: testGetObjectReadSeekFunctional",
  "status": "FAIL"
}
(6/14) Running minio-java tests ... FAILED in 8 seconds
{
  "name": "minio-java",
  "function": "listObjects()",
  "args": "[bucket]",
  "duration": 174,
  "status": "FAIL",
  "error": "error occurred\nErrorResponse(code = InternalError, message = We encountered an internal error, please try again.: cause(listPathRaw: 0 drives provided), bucketName = minio-java-test-2rccks4, objectName = null, resource = /minio-java-test-2rccks4, requestId = 172CC4C790A9E8F1, hostId = 10018f83-b548-4e06-875c-1b7fc5413c22)\nrequest={method=GET, url=http://15.15.15.6:32175/minio-java-test-2rccks4?list-type=2&prefix=&max-keys=1000&encoding-type=url&delimiter=%2F, headers=Host: 15.15.15.6:32175\nAccept-Encoding: identity\nUser-Agent: MinIO (Linux; amd64) minio-java/8.4.5\nContent-MD5: 1B2M2Y8AsgTpgAmY7PhCfg==\nx-amz-content-sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855\nx-amz-date: 20221201T201843Z\nAuthorization: ██\n}\nresponse={code=500, headers=Accept-Ranges: bytes\nContent-Length: 374\nContent-Security-Policy: block-all-mixed-content\nContent-Type: application/xml\nServer: MinIO\nStrict-Transport-Security: max-age=31536000; includeSubDomains\nVary: Origin\nVary: Accept-Encoding\nX-Amz-Request-Id: 172CC4C790A9E8F1\nX-Content-Type-Options: nosniff\nX-Xss-Protection: 1; mode=block\nDate: Thu, 01 Dec 2022 20:18:43 GMT\n}\n >>> [io.minio.S3Base$1.onResponse(S3Base.java:690), okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:519), java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128), java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628), java.base/java.lang.Thread.run(Thread.java:829)]"
}
(6/14) Running minio-js tests ... FAILED in 11 seconds
{
  "name": "minio-js",
  "function": "\"after all\" hook in \"functional tests\"",
  "duration": 11,
  "status": "FAIL",
  "error": "S3Error: The bucket you tried to delete is not empty at Object.parseError (node_modules/minio/dist/main/xml-parsers.js:71:11) at /mint/run/core/minio-js/node_modules/minio/dist/main/transformers.js:166:22 at DestroyableTransform._flush (node_modules/minio/dist/main/transformers.js:90:10) at DestroyableTransform.prefinish (node_modules/readable-stream/lib/_stream_transform.js:129:10) at prefinish (node_modules/readable-stream/lib/_stream_writable.js:611:14) at finishMaybe (node_modules/readable-stream/lib/_stream_writable.js:620:5) at endWritable (node_modules/readable-stream/lib/_stream_writable.js:643:3) at DestroyableTransform.Writable.end (node_modules/readable-stream/lib/_stream_writable.js:571:22) at IncomingMessage.onend (internal/streams/readable.js:670:10) at endReadableNT (internal/streams/readable.js:1333:12) at processTicksAndRejections (internal/process/task_queues.js:82:21)"
}
(6/14) Running minio-py tests ... done in 1 minutes and 49 seconds
(7/14) Running s3cmd tests ... done in 16 seconds
(8/14) Running s3select tests ... done in 5 seconds
(9/14) Running versioning tests ... FAILED in 1 seconds
{
  "alert": "",
  "args": {
    "bucketName": "versioning-test-e0646m2k2g63ej",
    "expiry": 60000000000,
    "objectName": "testObject"
  },
  "duration": 534,
  "error": "InternalError: We encountered an internal error, please try again.: cause(listPathRaw: 0 drives provided)\n\tstatus code: 500, request id: 172CC4E8AA18EC77, host id: ",
  "function": "/mint/build/versioning/put.go:103: main.testPutObject",
  "message": "PUT expected to succeed but got InternalError: We encountered an internal error, please try again.: cause(listPathRaw: 0 drives provided)\n\tstatus code: 500, request id: 172CC4E8AA18EC77, host id: ",
  "name": "versioning",
  "status": "FAIL"
}

Executed 8 out of 14 tests successfully.
```
Deleting image on docker hub
Deleting image locally

**Comment by minio-trusted** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-erasure.sh | :heavy_check_mark: |
| mint-dist-erasure.sh | :heavy_check_mark: |
| mint-compress-encrypt-dist-erasure.sh | :heavy_check_mark: |
| mint-pools.sh | :heavy_check_mark: |
Deleting image on docker hub
Deleting image locally

**Comment by minio-trusted** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-erasure.sh | :heavy_check_mark: |
| mint-dist-erasure.sh | :heavy_check_mark: |
| mint-compress-encrypt-dist-erasure.sh | :heavy_check_mark: |
| mint-pools.sh | :heavy_check_mark: |
Deleting image on docker hub
Deleting image locally

**Comment by Look1216** [comment]
Now I have a doubt：
In my environment there are three machines：192.168.6.110-112，Here is my configuration：

```shell
MINIO_STORAGE_CLASS_STANDARD=EC:1
MINIO_STORAGE_CLASS_RRS=EC:1
MINIO_VOLUMES=http://ossNodepoolb{0...1}:19000/mnt/osspoolb{0...2}/share:HDD http://ossNodepoola{0...2}:19000/mnt/osspoola{0...1}/share:HDD
MINIO_ERASURE_SET_DRIVE_COUNT=3
```


I have two pools ，I started with a mount point umount，and I use `http://192.168.6.110:19000/minio/admin/v3/storageinfo` to get storageinfo as :

```json
{
"Disks": [
   {
       "endpoint": "http://ossNodepoolb1:19000/mnt/osspoolb0/share",
       "path": "/mnt/osspoolb0/share",
       "state": "ok",
       "uuid": "ecae9b92-e827-4ff2-8498-b7ee4d23f22d",
       "major": 253,
       "minor": 2,
       "totalspace": 1066045440,
       "usedspace": 49672192,
       "availspace": 1016373248,
       "metrics": {
           "lastMinute": {
               "DeleteAbandonedParts": {
                   "count": 3,
                   "acc_time_ns": 3839950
               },
               "DiskInfo": {
                   "count": 16,
                   "acc_time_ns": 982870
               },
               "ListVols": {
                   "count": 6,
                   "acc_time_ns": 237762
               },
               "ReadAll": {
                   "count": 3,
                   "acc_time_ns": 1876
               },
               "ReadVersion": {
                   "count": 2,
                   "acc_time_ns": 4046112
               },
               "ReadXL": {
                   "count": 2,
                   "acc_time_ns": 732157
               },
               "StatVol": {
                   "count": 13,
                   "acc_time_ns": 54368
               },
               "WalkDir": {
                   "count": 3,
                   "acc_time_ns": 13751516
               }
           },
           "apiCalls": {
               "AppendFile": 0,
               "CheckParts": 0,
               "CreateFile": 0,
               "Delete": 0,
               "DeleteAbandonedParts": 3,
               "DeleteVersion": 0,
               "DeleteVersions": 0,
               "DeleteVol": 0,
               "DiskInfo": 16,
               "ListDir": 0,
               "ListVols": 6,
               "MakeVol": 0,
               "MakeVolBulk": 0,
               "ReadAll": 3,
               "ReadFile": 0,
               "ReadFileStream": 0,
               "ReadMultiple": 0,
               "ReadVersion": 2,
               "ReadXL": 2,
               "RenameData": 0,
               "RenameFile": 0,
               "StatInfoFile": 0,
               "StatVol": 13,
               "UpdateMetadata": 0,
               "VerifyFile": 0,
               "WalkDir": 3,
               "WriteAll": 0,
               "WriteMetadata": 0
           }
       },
       "free_inodes": 522203,
       "pool_index": 0,
       "set_index": 0,
       "disk_index": 1
   },
   {
       "endpoint": "http://ossNodepoolb1:19000/mnt/osspoolb1/share",
       "path": "/mnt/osspoolb1/share",
       "state": "ok",
       "uuid": "9b79b1e5-9fa6-4d63-94d3-e9ae5c40d92c",
       "major": 253,
       "minor": 3,
       "totalspace": 1066045440,
       "usedspace": 33931264,
       "availspace": 1032114176,
       "metrics": {
           "lastMinute": {
               "DeleteAbandonedParts": {
                   "count": 4,
                   "acc_time_ns": 4421341
               },
               "DiskInfo": {
                   "count": 16,
                   "acc_time_ns": 134977
               },
               "ListVols": {
                   "count": 6,
                   "acc_time_ns": 29057
               },
               "ReadAll": {
                   "count": 3,
                   "acc_time_ns": 1329
               },
               "ReadVersion": {
                   "count": 4,
                   "acc_time_ns": 15050492
               },
               "ReadXL": {
                   "count": 3,
                   "acc_time_ns": 136805932
               },
               "StatVol": {
                   "count": 13,
                   "acc_time_ns": 29208
               },
               "WalkDir": {
                   "count": 3,
                   "acc_time_ns": 5654480
               }
           },
           "apiCalls": {
               "AppendFile": 0,
               "CheckParts": 0,
               "CreateFile": 0,
               "Delete": 0,
               "DeleteAbandonedParts": 4,
               "DeleteVersion": 0,
               "DeleteVersions": 0,
               "DeleteVol": 0,
               "DiskInfo": 16,
               "ListDir": 0,
               "ListVols": 6,
               "MakeVol": 0,
               "MakeVolBulk": 0,
               "ReadAll": 3,
               "ReadFile": 0,
               "ReadFileStream": 0,
               "ReadMultiple": 0,
               "ReadVersion": 4,
               "ReadXL": 3,
               "RenameData": 0,
               "RenameFile": 0,
               "StatInfoFile": 0,
               "StatVol": 13,
               "UpdateMetadata": 0,
               "VerifyFile": 0,
               "WalkDir": 3,
               "WriteAll": 0,
               "WriteMetadata": 0
           }
       },
       "free_inodes": 522207,
       "pool_index": 0,
       "set_index": 1,
       "disk_index": 0
   },
   {
       "endpoint": "http://ossNodepoolb1:19000/mnt/osspoolb2/share",
       "path": "/mnt/osspoolb2/share",
       "state": "ok",
       "uuid": "4774d0d2-4562-44d9-bcaf-1fba9ff95d7b",
       "major": 253,
       "minor": 4,
       "totalspace": 1066045440,
       "usedspace": 33931264,
       "availspace": 1032114176,
       "metrics": {
           "lastMinute": {
               "DeleteAbandonedParts": {
                   "count": 4,
                   "acc_time_ns": 1240446
               },
               "DiskInfo": {
                   "count": 16,
                   "acc_time_ns": 168715
               },
               "ListVols": {
                   "count": 6,
                   "acc_time_ns": 203905
               },
               "ReadAll": {
                   "count": 3,
                   "acc_time_ns": 6457
               },
               "ReadVersion": {
                   "count": 4,
                   "acc_time_ns": 10991368
               },
               "ReadXL": {
                   "count": 3,
                   "acc_time_ns": 57386783
               },
               "StatVol": {
                   "count": 13,
                   "acc_time_ns": 107232
               },
               "WalkDir": {
                   "count": 3,
                   "acc_time_ns": 5908184
               }
           },
           "apiCalls": {
               "AppendFile": 0,
               "CheckParts": 0,
               "CreateFile": 0,
               "Delete": 0,
               "DeleteAbandonedParts": 4,
               "DeleteVersion": 0,
               "DeleteVersions": 0,
               "DeleteVol": 0,
               "DiskInfo": 16,
               "ListDir": 0,
               "ListVols": 6,
               "MakeVol": 0,
               "MakeVolBulk": 0,
               "ReadAll": 3,
               "ReadFile": 0,
               "ReadFileStream": 0,
               "ReadMultiple": 0,
               "ReadVersion": 4,
               "ReadXL": 3,
               "RenameData": 0,
               "RenameFile": 0,
               "StatInfoFile": 0,
               "StatVol": 13,
               "UpdateMetadata": 0,
               "VerifyFile": 0,
               "WalkDir": 3,
               "WriteAll": 0,
               "WriteMetadata": 0
           }
       },
       "free_inodes": 522207,
       "pool_index": 0,
       "set_index": 1,
       "disk_index": 2
   },
   {
       "endpoint": "http://ossNodepoola1:19000/mnt/osspoola0/share",
       "path": "/mnt/osspoola0/share",
       "state": "ok",
       "uuid": "d123c94f-3a55-4f18-a985-e5d5a3894212",
       "major": 253,
       "minor": 5,
       "totalspace": 1066045440,
       "usedspace": 33923072,
       "availspace": 1032122368,
       "metrics": {
           "lastMinute": {
               "DeleteAbandonedParts": {
                   "count": 3,
                   "acc_time_ns": 1695166
               },
               "DiskInfo": {
                   "count": 16,
                   "acc_time_ns": 367094
               },
               "ListVols": {
                   "count": 6,
                   "acc_time_ns": 28765
               },
               "ReadAll": {
                   "count": 3,
                   "acc_time_ns": 3732
               },
               "ReadVersion": {
                   "count": 6,
                   "acc_time_ns": 43317052
               },
               "ReadXL": {
                   "count": 10,
                   "acc_time_ns": 12419520
               },
               "StatVol": {
                   "count": 13,
                   "acc_time_ns": 48787
               },
               "WalkDir": {
                   "count": 3,
                   "acc_time_ns": 21192624
               }
           },
           "apiCalls": {
               "AppendFile": 0,
               "CheckParts": 0,
               "CreateFile": 0,
               "Delete": 0,
               "DeleteAbandonedParts": 3,
               "DeleteVersion": 0,
               "DeleteVersions": 0,
               "DeleteVol": 0,
               "DiskInfo": 16,
               "ListDir": 0,
               "ListVols": 6,
               "MakeVol": 0,
               "MakeVolBulk": 0,
               "ReadAll": 3,
               "ReadFile": 0,
               "ReadFileStream": 0,
               "ReadMultiple": 0,
               "ReadVersion": 6,
               "ReadXL": 10,
               "RenameData": 0,
               "RenameFile": 0,
               "StatInfoFile": 0,
               "StatVol": 13,
               "UpdateMetadata": 0,
               "VerifyFile": 0,
               "WalkDir": 3,
               "WriteAll": 0,
               "WriteMetadata": 0
           }
       },
       "free_inodes": 522208,
       "pool_index": 1,
       "set_index": 0,
       "disk_index": 1
   },
   {
       "endpoint": "http://ossNodepoola1:19000/mnt/osspoola1/share",
       "path": "/mnt/osspoola1/share",
       "state": "ok",
       "uuid": "6566cecf-265c-4e68-9e01-488a0661888b",
       "major": 253,
       "minor": 6,
       "totalspace": 1066045440,
       "usedspace": 33931264,
       "availspace": 1032114176,
       "metrics": {
           "lastMinute": {
               "DeleteAbandonedParts": {
                   "count": 4,
                   "acc_time_ns": 7364793
               },
               "DiskInfo": {
                   "count": 16,
                   "acc_time_ns": 566567
               },
               "ListVols": {
                   "count": 6,
                   "acc_time_ns": 58479
               },
               "ReadAll": {
                   "count": 3,
                   "acc_time_ns": 184397
               },
               "ReadVersion": {
                   "count": 8,
                   "acc_time_ns": 10471657
               },
               "ReadXL": {
                   "count": 6,
                   "acc_time_ns": 25883753
               },
               "StatVol": {
                   "count": 13,
                   "acc_time_ns": 279048
               },
               "WalkDir": {
                   "count": 3,
                   "acc_time_ns": 20996647
               }
           },
           "apiCalls": {
               "AppendFile": 0,
               "CheckParts": 0,
               "CreateFile": 0,
               "Delete": 0,
               "DeleteAbandonedParts": 4,
               "DeleteVersion": 0,
               "DeleteVersions": 0,
               "DeleteVol": 0,
               "DiskInfo": 16,
               "ListDir": 0,
               "ListVols": 6,
               "MakeVol": 0,
               "MakeVolBulk": 0,
               "ReadAll": 3,
               "ReadFile": 0,
               "ReadFileStream": 0,
               "ReadMultiple": 0,
               "ReadVersion": 8,
               "ReadXL": 6,
               "RenameData": 0,
               "RenameFile": 0,
               "StatInfoFile": 0,
               "StatVol": 13,
               "UpdateMetadata": 0,
               "VerifyFile": 0,
               "WalkDir": 3,
               "WriteAll": 0,
               "WriteMetadata": 0
           }
       },
       "free_inodes": 522206,
       "pool_index": 1,
       "set_index": 1,
       "disk_index": 1
   },
   {
       "endpoint": "http://ossNodepoola2:19000/mnt/osspoola0/share",
       "path": "/mnt/osspoola0/share",
       "state": "ok",
       "uuid": "7e740e40-9f60-49a8-b53a-e62850f2f91c",
       "major": 253,
       "minor": 2,
       "totalspace": 1066045440,
       "usedspace": 33923072,
       "availspace": 1032122368,
       "metrics": {
           "lastMinute": {
               "DeleteAbandonedParts": {
                   "count": 3,
                   "acc_time_ns": 1673734
               },
               "DiskInfo": {
                   "count": 10,
                   "acc_time_ns": 407248
               },
               "ListVols": {
                   "count": 1,
                   "acc_time_ns": 11606
               },
               "ReadAll": {
                   "count": 3,
                   "acc_time_ns": 4197
               },
               "ReadVersion": {
                   "count": 6,
                   "acc_time_ns": 19803303
               },
               "ReadXL": {
                   "count": 10,
                   "acc_time_ns": 33189623
               },
               "StatVol": {
                   "count": 4,
                   "acc_time_ns": 317902
               },
               "WalkDir": {
                   "count": 3,
                   "acc_time_ns": 92281467
               }
           },
           "apiCalls": {
               "AppendFile": 0,
               "CheckParts": 0,
               "CreateFile": 0,
               "Delete": 0,
               "DeleteAbandonedParts": 3,
               "DeleteVersion": 0,
               "DeleteVersions": 0,
               "DeleteVol": 0,
               "DiskInfo": 10,
               "ListDir": 0,
               "ListVols": 1,
               "MakeVol": 0,
               "MakeVolBulk": 0,
               "ReadAll": 3,
               "ReadFile": 0,
               "ReadFileStream": 0,
               "ReadMultiple": 0,
               "ReadVersion": 6,
               "ReadXL": 10,
               "RenameData": 0,
               "RenameFile": 0,
               "StatInfoFile": 0,
               "StatVol": 4,
               "UpdateMetadata": 0,
               "VerifyFile": 0,
               "WalkDir": 3,
               "WriteAll": 0,
               "WriteMetadata": 0
           }
       },
       "free_inodes": 522208,
       "pool_index": 1,
       "set_index": 0,
       "disk_index": 2
   },
   {
       "endpoint": "http://ossNodepoola2:19000/mnt/osspoola1/share",
       "path": "/mnt/osspoola1/share",
       "state": "ok",
       "uuid": "cff7f95d-5e17-4f49-84ce-f2a62fe1781a",
       "major": 253,
       "minor": 3,
       "totalspace": 1066045440,
       "usedspace": 33931264,
       "availspace": 1032114176,
       "metrics": {
           "lastMinute": {
               "DeleteAbandonedParts": {
                   "count": 4,
                   "acc_time_ns": 4970245
               },
               "DiskInfo": {
                   "count": 10,
                   "acc_time_ns": 249843
               },
               "ListVols": {
                   "count": 1,
                   "acc_time_ns": 16458
               },
               "ReadAll": {
                   "count": 3,
                   "acc_time_ns": 111707
               },
               "ReadVersion": {
                   "count": 8,
                   "acc_time_ns": 10699363
               },
               "ReadXL": {
                   "count": 6,
                   "acc_time_ns": 6496122
               },
               "StatVol": {
                   "count": 4,
                   "acc_time_ns": 27791
               },
               "WalkDir": {
                   "count": 3,
                   "acc_time_ns": 94842454
               }
           },
           "apiCalls": {
               "AppendFile": 0,
               "CheckParts": 0,
               "CreateFile": 0,
               "Delete": 0,
               "DeleteAbandonedParts": 4,
               "DeleteVersion": 0,
               "DeleteVersions": 0,
               "DeleteVol": 0,
               "DiskInfo": 10,
               "ListDir": 0,
               "ListVols": 1,
               "MakeVol": 0,
               "MakeVolBulk": 0,
               "ReadAll": 3,
               "ReadFile": 0,
               "ReadFileStream": 0,
               "ReadMultiple": 0,
               "ReadVersion": 8,
               "ReadXL": 6,
               "RenameData": 0,
               "RenameFile": 0,
               "StatInfoFile": 0,
               "StatVol": 4,
               "UpdateMetadata": 0,
               "VerifyFile": 0,
               "WalkDir": 3,
               "WriteAll": 0,
               "WriteMetadata": 0
           }
       },
       "free_inodes": 522206,
       "pool_index": 1,
       "set_index": 1,
       "disk_index": 2
   },
   {
       "endpoint": "http://ossNodepoolb0:19000/mnt/osspoolb0/share",
       "path": "/mnt/osspoolb0/share",
       "state": "ok",
       "uuid": "23940d72-e174-41bf-92eb-cc7e5f3835e5",
       "major": 253,
       "minor": 2,
       "totalspace": 1066045440,
       "usedspace": 49672192,
       "availspace": 1016373248,
       "metrics": {
           "lastMinute": {
               "DeleteAbandonedParts": {
                   "count": 3,
                   "acc_time_ns": 884313
               },
               "DiskInfo": {
                   "count": 15,
                   "acc_time_ns": 162145
               },
               "ListVols": {
                   "count": 6,
                   "acc_time_ns": 241820
               },
               "ReadAll": {
                   "count": 3,
                   "acc_time_ns": 3461
               },
               "ReadVersion": {
                   "count": 2,
                   "acc_time_ns": 3186553
               },
               "ReadXL": {
                   "count": 2,
                   "acc_time_ns": 2352720
               },
               "StatVol": {
                   "count": 13,
                   "acc_time_ns": 56636
               },
               "WalkDir": {
                   "count": 3,
                   "acc_time_ns": 29320832
               }
           },
           "apiCalls": {
               "AppendFile": 0,
               "CheckParts": 0,
               "CreateFile": 0,
               "Delete": 0,
               "DeleteAbandonedParts": 3,
               "DeleteVersion": 0,
               "DeleteVersions": 0,
               "DeleteVol": 0,
               "DiskInfo": 15,
               "ListDir": 0,
               "ListVols": 6,
               "MakeVol": 0,
               "MakeVolBulk": 0,
               "ReadAll": 3,
               "ReadFile": 0,
               "ReadFileStream": 0,
               "ReadMultiple": 0,
               "ReadVersion": 2,
               "ReadXL": 2,
               "RenameData": 0,
               "RenameFile": 0,
               "StatInfoFile": 0,
               "StatVol": 13,
               "UpdateMetadata": 0,
               "VerifyFile": 0,
               "WalkDir": 3,
               "WriteAll": 0,
               "WriteMetadata": 0
           }
       },
       "free_inodes": 522203,
       "pool_index": 0,
       "set_index": 0,
       "disk_index": 0
   },
   {
       "endpoint": "http://ossNodepoolb0:19000/mnt/osspoolb1/share",
       "path": "/mnt/osspoolb1/share",
       "state": "ok",
       "uuid": "61a54c8f-25e1-44cc-beb5-55e1e41009a7",
       "major": 253,
       "minor": 3,
       "totalspace": 1066045440,
       "usedspace": 49672192,
       "availspace": 1016373248,
       "metrics": {
           "lastMinute": {
               "DeleteAbandonedParts": {
                   "count": 3,
                   "acc_time_ns": 7714407
               },
               "DiskInfo": {
                   "count": 15,
                   "acc_time_ns": 489993
               },
               "ListVols": {
                   "count": 6,
                   "acc_time_ns": 39297
               },
               "ReadAll": {
                   "count": 3,
                   "acc_time_ns": 1522
               },
               "ReadVersion": {
                   "count": 2,
                   "acc_time_ns": 3285856
               },
               "ReadXL": {
                   "count": 2,
                   "acc_time_ns": 1152971
               },
               "StatVol": {
                   "count": 13,
                   "acc_time_ns": 49057
               },
               "WalkDir": {
                   "count": 3,
                   "acc_time_ns": 39468992
               }
           },
           "apiCalls": {
               "AppendFile": 0,
               "CheckParts": 0,
               "CreateFile": 0,
               "Delete": 0,
               "DeleteAbandonedParts": 3,
               "DeleteVersion": 0,
               "DeleteVersions": 0,
               "DeleteVol": 0,
               "DiskInfo": 15,
               "ListDir": 0,
               "ListVols": 6,
               "MakeVol": 0,
               "MakeVolBulk": 0,
               "ReadAll": 3,
               "ReadFile": 0,
               "ReadFileStream": 0,
               "ReadMultiple": 0,
               "ReadVersion": 2,
               "ReadXL": 2,
               "RenameData": 0,
               "RenameFile": 0,
               "StatInfoFile": 0,
               "StatVol": 13,
               "UpdateMetadata": 0,
               "VerifyFile": 0,
               "WalkDir": 3,
               "WriteAll": 0,
               "WriteMetadata": 0
           }
       },
       "free_inodes": 522203,
       "pool_index": 0,
       "set_index": 0,
       "disk_index": 2
   },
   {
       "endpoint": "http://ossNodepoolb0:19000/mnt/osspoolb2/share",
       "state": "offline",
       "major": 0,
       "minor": 0,
       "pool_index": 0,
       "set_index": 0,
       "disk_index": 0
   },
   {
       "endpoint": "http://ossNodepoola0:19000/mnt/osspoola0/share",
       "path": "/mnt/osspoola0/share",
       "state": "ok",
       "uuid": "573ec861-55d5-4bc5-a467-c81a73d3412c",
       "major": 253,
       "minor": 5,
       "totalspace": 1066045440,
       "usedspace": 33923072,
       "availspace": 1032122368,
       "metrics": {
           "lastMinute": {
               "DeleteAbandonedParts": {
                   "count": 3,
                   "acc_time_ns": 9238482
               },
               "DiskInfo": {
                   "count": 15,
                   "acc_time_ns": 537559
               },
               "ListVols": {
                   "count": 6,
                   "acc_time_ns": 229358
               },
               "ReadAll": {
                   "count": 3,
                   "acc_time_ns": 2958
               },
               "ReadVersion": {
                   "count": 6,
                   "acc_time_ns": 7007973
               },
               "ReadXL": {
                   "count": 10,
                   "acc_time_ns": 48114590
               },
               "StatVol": {
                   "count": 13,
                   "acc_time_ns": 41079
               },
               "WalkDir": {
                   "count": 3,
                   "acc_time_ns": 21652849
               }
           },
           "apiCalls": {
               "AppendFile": 0,
               "CheckParts": 0,
               "CreateFile": 0,
               "Delete": 0,
               "DeleteAbandonedParts": 3,
               "DeleteVersion": 0,
               "DeleteVersions": 0,
               "DeleteVol": 0,
               "DiskInfo": 15,
               "ListDir": 0,
               "ListVols": 6,
               "MakeVol": 0,
               "MakeVolBulk": 0,
               "ReadAll": 3,
               "ReadFile": 0,
               "ReadFileStream": 0,
               "ReadMultiple": 0,
               "ReadVersion": 6,
               "ReadXL": 10,
               "RenameData": 0,
               "RenameFile": 0,
               "StatInfoFile": 0,
               "StatVol": 13,
               "UpdateMetadata": 0,
               "VerifyFile": 0,
               "WalkDir": 3,
               "WriteAll": 0,
               "WriteMetadata": 0
           }
       },
       "free_inodes": 522208,
       "pool_index": 1,
       "set_index": 0,
       "disk_index": 0
   },
   {
       "endpoint": "http://ossNodepoola0:19000/mnt/osspoola1/share",
       "path": "/mnt/osspoola1/share",
       "state": "ok",
       "uuid": "3561bbd2-61a1-4de3-91cd-6d8153469b74",
       "major": 253,
       "minor": 6,
       "totalspace": 1066045440,
       "usedspace": 33931264,
       "availspace": 1032114176,
       "metrics": {
           "lastMinute": {
               "DeleteAbandonedParts": {
                   "count": 4,
                   "acc_time_ns": 3821107
               },
               "DiskInfo": {
                   "count": 15,
                   "acc_time_ns": 221819
               },
               "ListVols": {
                   "count": 6,
                   "acc_time_ns": 58576
               },
               "ReadAll": {
                   "count": 3,
                   "acc_time_ns": 4209
               },
               "ReadVersion": {
                   "count": 8,
                   "acc_time_ns": 23443183
               },
               "ReadXL": {
                   "count": 6,
                   "acc_time_ns": 47559454
               },
               "StatVol": {
                   "count": 13,
                   "acc_time_ns": 614419
               },
               "WalkDir": {
                   "count": 3,
                   "acc_time_ns": 26005286
               }
           },
           "apiCalls": {
               "AppendFile": 0,
               "CheckParts": 0,
               "CreateFile": 0,
               "Delete": 0,
               "DeleteAbandonedParts": 4,
               "DeleteVersion": 0,
               "DeleteVersions": 0,
               "DeleteVol": 0,
               "DiskInfo": 15,
               "ListDir": 0,
               "ListVols": 6,
               "MakeVol": 0,
               "MakeVolBulk": 0,
               "ReadAll": 3,
               "ReadFile": 0,
               "ReadFileStream": 0,
               "ReadMultiple": 0,
               "ReadVersion": 8,
               "ReadXL": 6,
               "RenameData": 0,
               "RenameFile": 0,
               "StatInfoFile": 0,
               "StatVol": 13,
               "UpdateMetadata": 0,
               "VerifyFile": 0,
               "WalkDir": 3,
               "WriteAll": 0,
               "WriteMetadata": 0
           }
       },
       "free_inodes": 522206,
       "pool_index": 1,
       "set_index": 1,
       "disk_index": 0
   },
   {
       "endpoint": "http://ossNodepoolb1:19000/mnt/osspoolb0/share",
       "path": "/mnt/osspoolb0/share",
       "state": "ok",
       "uuid": "ecae9b92-e827-4ff2-8498-b7ee4d23f22d",
       "major": 253,
       "minor": 2,
       "totalspace": 1066045440,
       "usedspace": 49672192,
       "availspace": 1016373248,
       "metrics": {
           "lastMinute": {
               "DeleteAbandonedParts": {
                   "count": 3,
                   "acc_time_ns": 3839950
               },
               "DiskInfo": {
                   "count": 16,
                   "acc_time_ns": 982870
               },
               "ListVols": {
                   "count": 6,
                   "acc_time_ns": 237762
               },
               "ReadAll": {
                   "count": 3,
                   "acc_time_ns": 1876
               },
               "ReadVersion": {
                   "count": 2,
                   "acc_time_ns": 4046112
               },
               "ReadXL": {
                   "count": 2,
                   "acc_time_ns": 732157
               },
               "StatVol": {
                   "count": 13,
                   "acc_time_ns": 54368
               },
               "WalkDir": {
                   "count": 3,
                   "acc_time_ns": 13751516
               }
           },
           "apiCalls": {
               "AppendFile": 0,
               "CheckParts": 0,
               "CreateFile": 0,
               "Delete": 0,
               "DeleteAbandonedParts": 3,
               "DeleteVersion": 0,
               "DeleteVersions": 0,
               "DeleteVol": 0,
               "DiskInfo": 16,
               "ListDir": 0,
               "ListVols": 6,
               "MakeVol": 0,
               "MakeVolBulk": 0,
               "ReadAll": 3,
               "ReadFile": 0,
               "ReadFileStream": 0,
               "ReadMultiple": 0,
               "ReadVersion": 2,
               "ReadXL": 2,
               "RenameData": 0,
               "RenameFile": 0,
               "StatInfoFile": 0,
               "StatVol": 13,
               "UpdateMetadata": 0,
               "VerifyFile": 0,
               "WalkDir": 3,
               "WriteAll": 0,
               "WriteMetadata": 0
           }
       },
       "free_inodes": 522203,
       "pool_index": 0,
       "set_index": 0,
       "disk_index": 1
   },
   {
       "endpoint": "http://ossNodepoolb1:19000/mnt/osspoolb1/share",
       "path": "/mnt/osspoolb1/share",
       "state": "ok",
       "uuid": "9b79b1e5-9fa6-4d63-94d3-e9ae5c40d92c",
       "major": 253,
       "minor": 3,
       "totalspace": 1066045440,
       "usedspace": 33931264,
       "availspace": 1032114176,
       "metrics": {
           "lastMinute": {
               "DeleteAbandonedParts": {
                   "count": 4,
                   "acc_time_ns": 4421341
               },
               "DiskInfo": {
                   "count": 16,
                   "acc_time_ns": 134977
               },
               "ListVols": {
                   "count": 6,
                   "acc_time_ns": 29057
               },
               "ReadAll": {
                   "count": 3,
                   "acc_time_ns": 1329
               },
               "ReadVersion": {
                   "count": 4,
                   "acc_time_ns": 15050492
               },
               "ReadXL": {
                   "count": 3,
                   "acc_time_ns": 136805932
               },
               "StatVol": {
                   "count": 13,
                   "acc_time_ns": 29208
               },
               "WalkDir": {
                   "count": 3,
                   "acc_time_ns": 5654480
               }
           },
           "apiCalls": {
               "AppendFile": 0,
               "CheckParts": 0,
               "CreateFile": 0,
               "Delete": 0,
               "DeleteAbandonedParts": 4,
               "DeleteVersion": 0,
               "DeleteVersions": 0,
               "DeleteVol": 0,
               "DiskInfo": 16,
               "ListDir": 0,
               "ListVols": 6,
               "MakeVol": 0,
               "MakeVolBulk": 0,
               "ReadAll": 3,
               "ReadFile": 0,
               "ReadFileStream": 0,
               "ReadMultiple": 0,
               "ReadVersion": 4,
               "ReadXL": 3,
               "RenameData": 0,
               "RenameFile": 0,
               "StatInfoFile": 0,
               "StatVol": 13,
               "UpdateMetadata": 0,
               "VerifyFile": 0,
               "WalkDir": 3,
               "WriteAll": 0,
               "WriteMetadata": 0
           }
       },
       "free_inodes": 522207,
       "pool_index": 0,
       "set_index": 1,
       "disk_index": 0
   },
   {
       "endpoint": "http://ossNodepoolb1:19000/mnt/osspoolb2/share",
       "path": "/mnt/osspoolb2/share",
       "state": "ok",
       "uuid": "4774d0d2-4562-44d9-bcaf-1fba9ff95d7b",
       "major": 253,
       "minor": 4,
       "totalspace": 1066045440,
       "usedspace": 33931264,
       "availspace": 1032114176,
       "metrics": {
           "lastMinute": {
               "DeleteAbandonedParts": {
                   "count": 4,
                   "acc_time_ns": 1240446
               },
               "DiskInfo": {
                   "count": 16,
                   "acc_time_ns": 168715
               },
               "ListVols": {
                   "count": 6,
                   "acc_time_ns": 203905
               },
               "ReadAll": {
                   "count": 3,
                   "acc_time_ns": 6457
               },
               "ReadVersion": {
                   "count": 4,
                   "acc_time_ns": 10991368
               },
               "ReadXL": {
                   "count": 3,
                   "acc_time_ns": 57386783
               },
               "StatVol": {
                   "count": 13,
                   "acc_time_ns": 107232
               },
               "WalkDir": {
                   "count": 3,
                   "acc_time_ns": 5908184
               }
           },
           "apiCalls": {
               "AppendFile": 0,
               "CheckParts": 0,
               "CreateFile": 0,
               "Delete": 0,
               "DeleteAbandonedParts": 4,
               "DeleteVersion": 0,
               "DeleteVersions": 0,
               "DeleteVol": 0,
               "DiskInfo": 16,
               "ListDir": 0,
               "ListVols": 6,
               "MakeVol": 0,
               "MakeVolBulk": 0,
               "ReadAll": 3,
               "ReadFile": 0,
               "ReadFileStream": 0,
               "ReadMultiple": 0,
               "ReadVersion": 4,
               "ReadXL": 3,
               "RenameData": 0,
               "RenameFile": 0,
               "StatInfoFile": 0,
               "StatVol": 13,
               "UpdateMetadata": 0,
               "VerifyFile": 0,
               "WalkDir": 3,
               "WriteAll": 0,
               "WriteMetadata": 0
           }
       },
       "free_inodes": 522207,
       "pool_index": 0,
       "set_index": 1,
       "disk_index": 2
   },
   {
       "endpoint": "http://ossNodepoola1:19000/mnt/osspoola0/share",
       "path": "/mnt/osspoola0/share",
       "state": "ok",
       "uuid": "d123c94f-3a55-4f18-a985-e5d5a3894212",
       "major": 253,
       "minor": 5,
       "totalspace": 1066045440,
       "usedspace": 33923072,
       "availspace": 1032122368,
       "metrics": {
           "lastMinute": {
               "DeleteAbandonedParts": {
                   "count": 3,
                   "acc_time_ns": 1695166
               },
               "DiskInfo": {
                   "count": 16,
                   "acc_time_ns": 367094
               },
               "ListVols": {
                   "count": 6,
                   "acc_time_ns": 28765
               },
               "ReadAll": {
                   "count": 3,
                   "acc_time_ns": 3732
               },
               "ReadVersion": {
                   "count": 6,
                   "acc_time_ns": 43317052
               },
               "ReadXL": {
                   "count": 10,
                   "acc_time_ns": 12419520
               },
               "StatVol": {
                   "count": 13,
                   "acc_time_ns": 48787
               },
               "WalkDir": {
                   "count": 3,
                   "acc_time_ns": 21192624
               }
           },
           "apiCalls": {
               "AppendFile": 0,
               "CheckParts": 0,
               "CreateFile": 0,
               "Delete": 0,
               "DeleteAbandonedParts": 3,
               "DeleteVersion": 0,
               "DeleteVersions": 0,
               "DeleteVol": 0,
               "DiskInfo": 16,
               "ListDir": 0,
               "ListVols": 6,
               "MakeVol": 0,
               "MakeVolBulk": 0,
               "ReadAll": 3,
               "ReadFile": 0,
               "ReadFileStream": 0,
               "ReadMultiple": 0,
               "ReadVersion": 6,
               "ReadXL": 10,
               "RenameData": 0,
               "RenameFile": 0,
               "StatInfoFile": 0,
               "StatVol": 13,
               "UpdateMetadata": 0,
               "VerifyFile": 0,
               "WalkDir": 3,
               "WriteAll": 0,
               "WriteMetadata": 0
           }
       },
       "free_inodes": 522208,
       "pool_index": 1,
       "set_index": 0,
       "disk_index": 1
   },
   {
       "endpoint": "http://ossNodepoola1:19000/mnt/osspoola1/share",
       "path": "/mnt/osspoola1/share",
       "state": "ok",
       "uuid": "6566cecf-265c-4e68-9e01-488a0661888b",
       "major": 253,
       "minor": 6,
       "totalspace": 1066045440,
       "usedspace": 33931264,
       "availspace": 1032114176,
       "metrics": {
           "lastMinute": {
               "DeleteAbandonedParts": {
                   "count": 4,
                   "acc_time_ns": 7364793
               },
               "DiskInfo": {
                   "count": 16,
                   "acc_time_ns": 566567
               },
               "ListVols": {
                   "count": 6,
                   "acc_time_ns": 58479
               },
               "ReadAll": {
                   "count": 3,
                   "acc_time_ns": 184397
               },
               "ReadVersion": {
                   "count": 8,
                   "acc_time_ns": 10471657
               },
               "ReadXL": {
                   "count": 6,
                   "acc_time_ns": 25883753
               },
               "StatVol": {
                   "count": 13,
                   "acc_time_ns": 279048
               },
               "WalkDir": {
                   "count": 3,
                   "acc_time_ns": 20996647
               }
           },
           "apiCalls": {
               "AppendFile": 0,
               "CheckParts": 0,
               "CreateFile": 0,
               "Delete": 0,
               "DeleteAbandonedParts": 4,
               "DeleteVersion": 0,
               "DeleteVersions": 0,
               "DeleteVol": 0,
               "DiskInfo": 16,
               "ListDir": 0,
               "ListVols": 6,
               "MakeVol": 0,
               "MakeVolBulk": 0,
               "ReadAll": 3,
               "ReadFile": 0,
               "ReadFileStream": 0,
               "ReadMultiple": 0,
               "ReadVersion": 8,
               "ReadXL": 6,
               "RenameData": 0,
               "RenameFile": 0,
               "StatInfoFile": 0,
               "StatVol": 13,
               "UpdateMetadata": 0,
               "VerifyFile": 0,
               "WalkDir": 3,
               "WriteAll": 0,
               "WriteMetadata": 0
           }
       },
       "free_inodes": 522206,
       "pool_index": 1,
       "set_index": 1,
       "disk_index": 1
   },
   {
       "endpoint": "http://ossNodepoolb0:19000/mnt/osspoolb0/share",
       "path": "/mnt/osspoolb0/share",
       "state": "ok",
       "uuid": "23940d72-e174-41bf-92eb-cc7e5f3835e5",
       "major": 253,
       "minor": 2,
       "totalspace": 1066045440,
       "usedspace": 49672192,
       "availspace": 1016373248,
       "metrics": {
           "lastMinute": {
               "DeleteAbandonedParts": {
                   "count": 3,
                   "acc_time_ns": 884313
               },
               "DiskInfo": {
                   "count": 15,
                   "acc_time_ns": 162145
               },
               "ListVols": {
                   "count": 6,
                   "acc_time_ns": 241820
               },
               "ReadAll": {
                   "count": 3,
                   "acc_time_ns": 3461
               },
               "ReadVersion": {
                   "count": 2,
                   "acc_time_ns": 3186553
               },
               "ReadXL": {
                   "count": 2,
                   "acc_time_ns": 2352720
               },
               "StatVol": {
                   "count": 13,
                   "acc_time_ns": 56636
               },
               "WalkDir": {
                   "count": 3,
                   "acc_time_ns": 29320832
               }
           },
           "apiCalls": {
               "AppendFile": 0,
               "CheckParts": 0,
               "CreateFile": 0,
               "Delete": 0,
               "DeleteAbandonedParts": 3,
               "DeleteVersion": 0,
               "DeleteVersions": 0,
               "DeleteVol": 0,
               "DiskInfo": 15,
               "ListDir": 0,
               "ListVols": 6,
               "MakeVol": 0,
               "MakeVolBulk": 0,
               "ReadAll": 3,
               "ReadFile": 0,
               "ReadFileStream": 0,
               "ReadMultiple": 0,
               "ReadVersion": 2,
               "ReadXL": 2,
               "RenameData": 0,
               "RenameFile": 0,
               "StatInfoFile": 0,
               "StatVol": 13,
               "UpdateMetadata": 0,
               "VerifyFile": 0,
               "WalkDir": 3,
               "WriteAll": 0,
               "WriteMetadata": 0
           }
       },
       "free_inodes": 522203,
       "pool_index": 0,
       "set_index": 0,
       "disk_index": 0
   },
   {
       "endpoint": "http://ossNodepoolb0:19000/mnt/osspoolb1/share",
       "path": "/mnt/osspoolb1/share",
       "state": "ok",
       "uuid": "61a54c8f-25e1-44cc-beb5-55e1e41009a7",
       "major": 253,
       "minor": 3,
       "totalspace": 1066045440,
       "usedspace": 49672192,
       "availspace": 1016373248,
       "metrics": {
           "lastMinute": {
               "DeleteAbandonedParts": {
                   "count": 3,
                   "acc_time_ns": 7714407
               },
               "DiskInfo": {
                   "count": 15,
                   "acc_time_ns": 489993
               },
               "ListVols": {
                   "count": 6,
                   "acc_time_ns": 39297
               },
               "ReadAll": {
                   "count": 3,
                   "acc_time_ns": 1522
               },
               "ReadVersion": {
                   "count": 2,
                   "acc_time_ns": 3285856
               },
               "ReadXL": {
                   "count": 2,
                   "acc_time_ns": 1152971
               },
               "StatVol": {
                   "count": 13,
                   "acc_time_ns": 49057
               },
               "WalkDir": {
                   "count": 3,
                   "acc_time_ns": 39468992
               }
           },
           "apiCalls": {
               "AppendFile": 0,
               "CheckParts": 0,
               "CreateFile": 0,
               "Delete": 0,
               "DeleteAbandonedParts": 3,
               "DeleteVersion": 0,
               "DeleteVersions": 0,
               "DeleteVol": 0,
               "DiskInfo": 15,
               "ListDir": 0,
               "ListVols": 6,
               "MakeVol": 0,
               "MakeVolBulk": 0,
               "ReadAll": 3,
               "ReadFile": 0,
               "ReadFileStream": 0,
               "ReadMultiple": 0,
               "ReadVersion": 2,
               "ReadXL": 2,
               "RenameData": 0,
               "RenameFile": 0,
               "StatInfoFile": 0,
               "StatVol": 13,
               "UpdateMetadata": 0,
               "VerifyFile": 0,
               "WalkDir": 3,
               "WriteAll": 0,
               "WriteMetadata": 0
           }
       },
       "free_inodes": 522203,
       "pool_index": 0,
       "set_index": 0,
       "disk_index": 2
   },
   {
       "endpoint": "http://ossNodepoolb0:19000/mnt/osspoolb2/share",
       "state": "offline",
       "major": 0,
       "minor": 0,
       "pool_index": 0,
       "set_index": 0,
       "disk_index": 0
   },
   {
       "endpoint": "http://ossNodepoola0:19000/mnt/osspoola0/share",
       "path": "/mnt/osspoola0/share",
       "state": "ok",
       "uuid": "573ec861-55d5-4bc5-a467-c81a73d3412c",
       "major": 253,
       "minor": 5,
       "totalspace": 1066045440,
       "usedspace": 33923072,
       "availspace": 1032122368,
       "metrics": {
           "lastMinute": {
               "DeleteAbandonedParts": {
                   "count": 3,
                   "acc_time_ns": 9238482
               },
               "DiskInfo": {
                   "count": 15,
                   "acc_time_ns": 537559
               },
               "ListVols": {
                   "count": 6,
                   "acc_time_ns": 229358
               },
               "ReadAll": {
                   "count": 3,
                   "acc_time_ns": 2958
               },
               "ReadVersion": {
                   "count": 6,
                   "acc_time_ns": 7007973
               },
               "ReadXL": {
                   "count": 10,
                   "acc_time_ns": 48114590
               },
               "StatVol": {
                   "count": 13,
                   "acc_time_ns": 41079
               },
               "WalkDir": {
                   "count": 3,
                   "acc_time_ns": 21652849
               }
           },
           "apiCalls": {
               "AppendFile": 0,
               "CheckParts": 0,
               "CreateFile": 0,
               "Delete": 0,
               "DeleteAbandonedParts": 3,
               "DeleteVersion": 0,
               "DeleteVersions": 0,
               "DeleteVol": 0,
               "DiskInfo": 15,
               "ListDir": 0,
               "ListVols": 6,
               "MakeVol": 0,
               "MakeVolBulk": 0,
               "ReadAll": 3,
               "ReadFile": 0,
               "ReadFileStream": 0,
               "ReadMultiple": 0,
               "ReadVersion": 6,
               "ReadXL": 10,
               "RenameData": 0,
               "RenameFile": 0,
               "StatInfoFile": 0,
               "StatVol": 13,
               "UpdateMetadata": 0,
               "VerifyFile": 0,
               "WalkDir": 3,
               "WriteAll": 0,
               "WriteMetadata": 0
           }
       },
       "free_inodes": 522208,
       "pool_index": 1,
       "set_index": 0,
       "disk_index": 0
   },
   {
       "endpoint": "http://ossNodepoola0:19000/mnt/osspoola1/share",
       "path": "/mnt/osspoola1/share",
       "state": "ok",
       "uuid": "3561bbd2-61a1-4de3-91cd-6d8153469b74",
       "major": 253,
       "minor": 6,
       "totalspace": 1066045440,
       "usedspace": 33931264,
       "availspace": 1032114176,
       "metrics": {
           "lastMinute": {
               "DeleteAbandonedParts": {
                   "count": 4,
                   "acc_time_ns": 3821107
               },
               "DiskInfo": {
                   "count": 15,
                   "acc_time_ns": 221819
               },
               "ListVols": {
                   "count": 6,
                   "acc_time_ns": 58576
               },
               "ReadAll": {
                   "count": 3,
                   "acc_time_ns": 4209
               },
               "ReadVersion": {
                   "count": 8,
                   "acc_time_ns": 23443183
               },
               "ReadXL": {
                   "count": 6,
                   "acc_time_ns": 47559454
               },
               "StatVol": {
                   "count": 13,
                   "acc_time_ns": 614419
               },
               "WalkDir": {
                   "count": 3,
                   "acc_time_ns": 26005286
               }
           },
           "apiCalls": {
               "AppendFile": 0,
               "CheckParts": 0,
               "CreateFile": 0,
               "Delete": 0,
               "DeleteAbandonedParts": 4,
               "DeleteVersion": 0,
               "DeleteVersions": 0,
               "DeleteVol": 0,
               "DiskInfo": 15,
               "ListDir": 0,
               "ListVols": 6,
               "MakeVol": 0,
               "MakeVolBulk": 0,
               "ReadAll": 3,
               "ReadFile": 0,
               "ReadFileStream": 0,
               "ReadMultiple": 0,
               "ReadVersion": 8,
               "ReadXL": 6,
               "RenameData": 0,
               "RenameFile": 0,
               "StatInfoFile": 0,
               "StatVol": 13,
               "UpdateMetadata": 0,
               "VerifyFile": 0,
               "WalkDir": 3,
               "WriteAll": 0,
               "WriteMetadata": 0
           }
       },
       "free_inodes": 522206,
       "pool_index": 1,
       "set_index": 1,
       "disk_index": 0
   }
],
"Backend": {
   "Type": 2,
   "GatewayOnline": false,
   "OnlineDisks": null,
   "OfflineDisks": null,
   "StandardSCData": [
       2,
       2
   ],
   "StandardSCParity": 1,
   "RRSCData": [
       2,
       2
   ],
   "RRSCParity": 1,
   "TotalSets": [
       2,
       2
   ],
   "DrivesPerSet": [
       3,
       3
   ]
}
}
```

I have two questions,:

- one is why the information is duplicated, there only 12 disk but have 22 items in response

- and the second is the poolIndex/SetIndex/DiskIndex(0/0/0/) is the same bwtween 
  "endpoint": "http://ossnodepoolb0:19000/mnt/osspoolb0/share" and 
  "endpoint" "http://ossnodepoolb0:19000/mnt/osspoolb2/share"

@harshavardhana
