### PR TITLE
sys/stats: return cgroup mem limit, fall back to sysinfo()

### LINKED ISSUE #4001: caching: Out of memory crashes on cgroup limit
I have seem some crashes on my host with the following message.

[34549785.782753] Memory cgroup out of memory: Kill process 35945 (minio) score 995 or sacrifice child

[34549785.800895] Killed process 35945 (minio) total-vm:8804576kB, anon-rss:3962816kB, file-rss:0kB

The minio server is running in LXC container which is limited to 4GB ram.

It is possible that minio sees the HOST RAM which is much higher: 250+GB

wsadmin@wscwbs-storage06-prod:~$ free -g
             total       used       free     shared    buffers     cached
Mem:           251        250          1          0          8         46

Work-around: I will now start the servers with _MINIO_CACHE_=off.

### PR DESCRIPTION
**Pull request by harshavardhana**
## Description
This is necessary where in certain environments where
cgroup is used to limit memory usage of a container or
a particular process.

GetStats() is used by caching module to figure out the
optimal cacheable size in memory with cgroup limits
what sysinfo reports might not be the right value set
for a given process.

## Motivation and Context
Fixes #4001

## How Has This Been Tested?
Manually using cgroup limits.

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by harshavardhana** [comment]
Tested this with local docker container 

```yml
version: '2'

# starts 4 docker containers running minio server instances. Each
# minio server's web interface will be accessible on the host at port
# 9001 through 9004.
services:
  minio1:
    image: y4m4/minio
    mem_limit: 100m
    ports:
      - "9001:9000"
    volumes:
      - /mnt/export/minio1:/export
    environment:
      MINIO_ACCESS_KEY: minio
      MINIO_SECRET_KEY: minio123
    command: server http://minio1/export http://minio2/export http://minio3/export http://minio4/export        
  minio2:
    image: y4m4/minio
    mem_limit: 100m    
    ports:
      - "9002:9000"
    volumes:
      - /mnt/export/minio2:/export
    environment:
      MINIO_ACCESS_KEY: minio
      MINIO_SECRET_KEY: minio123
    command: server http://minio1/export http://minio2/export http://minio3/export http://minio4/export    
  minio3:
    image: y4m4/minio
    mem_limit: 100m    
    ports:
      - "9003:9000"
    volumes:
      - /mnt/export/minio3:/export
    environment:
      MINIO_ACCESS_KEY: minio
      MINIO_SECRET_KEY: minio123
    command: server http://minio1/export http://minio2/export http://minio3/export http://minio4/export
  minio4:
    image: y4m4/minio
    mem_limit: 100m  
    ports:
      - "9004:9000"
    volumes:
      - /mnt/export/minio4:/export
    environment:
      MINIO_ACCESS_KEY: minio
      MINIO_SECRET_KEY: minio123
    command: server http://minio1/export http://minio2/export http://minio3/export http://minio4/export
```

**Comment by harshavardhana** [comment]
Create a local docker container with this patch.

``` 
FROM ubuntu
COPY minio /usr/bin/minio

ENTRYPOINT ["/usr/bin/minio"]
```

File: pkg/sys/cgroup_linux.go [hunk 1]
```diff
@@ -0,0 +1,189 @@
...
+	"os"
+	"os/exec"
+	"path/filepath"
+	"strconv"
+	"strings"
+)
+
+// Splits special only splits based on the first occurrence
+// of the separator.
+func splitSpecial(text string, sep string) (head string, tail string) {
```
Comment (krisis) [inline pkg/sys/cgroup_linux.go]: `s/splitSpecial/splitBy`
`splitSpecial` doesn't convey what is special. OTOH `splitBy` suggests that it is parametrized by something, a separator in this case.

File: pkg/sys/cgroup_linux.go [hunk 2]
```diff
@@ -0,0 +1,189 @@
...
+// you need to know the pid of the application you are
+// looking for so that the the following parsing logic
+// only parses the file located at /proc/<pid>/cgroup.
+//
+// CGROUP entries id, component and path are always in
+// the following format. ``ID:COMPONENT:PATH``
+//
+// Following code block parses this information and
+// returns a procCGroup which is a parsed list of all
+// the line by line entires from /proc/<pid>cgroup.
```
Comment (krisis) [inline pkg/sys/cgroup_linux.go]: typo: `s/<pid>group/<pid>\/cgroup`

File: pkg/sys/cgroup_linux.go [hunk 3]
```diff
@@ -0,0 +1,189 @@
...
+				return proc, err
+			}
+
+			proc = append(proc, cGroup{ID: iid, Name: name, Path: path})
+			name = next
+		}
+	}
+
+	if err := bio.Err(); err != nil {
+		return proc, err
```
Comment (krisis) [inline pkg/sys/cgroup_linux.go]: It should be `return nil, err`.

File: pkg/sys/cgroup_linux.go [hunk 4]
```diff
@@ -0,0 +1,189 @@
...
+		if memory := cgroups.getByName("memory"); len(memory) != 0 {
+			// Pick the first one.
+			limit, err = getMemoryCGroupMemoryLimit(memory[0])
+		}
+	}
+	return limit, err
+}
+
+// Default value for any error or if cgroup is not set.
+const unlimitedMemoryLimit = 9223372036854771712
```
Comment (krisis) [inline pkg/sys/cgroup_linux.go]: Shouldn't the default limit be only as large as the RAM?

File: pkg/sys/cgroup_linux.go (hunk 1 above)
Comment (balamurugana) [reply pkg/sys/cgroup_linux.go]: isn't `strings.SplitN("hello:gnu:world", ":", 2)` different?

File: cmd/server-rlimit.go [hunk 5]
```diff
@@ -65,7 +69,7 @@ func GetMaxCacheSize() (cacheSize uint64, err error) {
 
 	// Get total RAM.
 	var stats sys.Stats
-	if stats, err = sys.GetStats(); err != nil {
+	if stats, err = sys.GetStats(os.Getpid()); err != nil {
```
Comment (balamurugana) [inline cmd/server-rlimit.go]: As `sys.GetStats()` returns current PID's stat, there is no need to pass PID as argument.

File: pkg/sys/cgroup_linux.go [hunk 6]
```diff
@@ -0,0 +1,189 @@
...
+		head, tail = text[:i], text[i+1:]
+	} else {
+		head = text
+	}
+	head = strings.TrimSpace(head)
+	tail = strings.TrimSpace(tail)
+	return
+}
+
+type procCGroup []cGroup
```
Comment (balamurugana) [inline pkg/sys/cgroup_linux.go]: this type could be after `cGroup` type for better readability.

File: pkg/sys/cgroup_linux.go [hunk 7]
```diff
@@ -0,0 +1,189 @@
...
+
+type cGroup struct {
```
Comment (balamurugana) [inline pkg/sys/cgroup_linux.go]: I think `cgroup` would be better name.

File: pkg/sys/cgroup_linux.go [hunk 8]
```diff
@@ -0,0 +1,189 @@
...
+// CGROUP entries id, component and path are always in
+// the following format. ``ID:COMPONENT:PATH``
+//
+// Following code block parses this information and
+// returns a procCGroup which is a parsed list of all
+// the line by line entires from /proc/<pid>cgroup.
+func parseProcCGroup(r io.Reader) (procCGroup, error) {
+	var proc procCGroup
+
+	bio := bufio.NewScanner(r)
```
Comment (balamurugana) [inline pkg/sys/cgroup_linux.go]: `scanner` is better name than `bio`

**Review by balamurugana — CHANGES_REQUESTED** [review]
I see below is the essence of finding memory size of lxc.
In bash;
```bash
mempathseg=${awk -F: '$2 ~ /^memory$/ {print $3}'  /proc/1/cgroup}

mempath=/sys/fs/cgroup/memory/
if [[ "$mempathseg" != /docker/* ]]; then
    mempath="$mempath$mempathseg"
fi
mempath="$mempath/memory.limit_in_bytes"

memsize=$(cat $mempath)
```

I couldn't able to get why too many layers of code.

File: pkg/sys/cgroup_linux.go (hunk 4 above)
Comment (harshavardhana) [reply pkg/sys/cgroup_linux.go]: Not in cgroup   it weirdly keeps this value.

File: cmd/server-rlimit.go (hunk 5 above)
Comment (harshavardhana) [reply cmd/server-rlimit.go]: Pid is needed to know the right cgroup rules for the given process. As each process can have a different cgroup.

**Comment by krishnasrinivas** [comment]
```
cmd := exec.Command("cgm", "getvalue", cgroup.Name, cgroup.Path, "memory.limit_i\
    n_bytes")
```

On host:
```
root@escape:~# cgm getvalue memory /docker/f6234f456d76086b7da2e758a5b860653be3c5b3503d456525972abc104cb379 memory.limit_in_bytes
call to cgmanager_get_value_sync failed: invalid request
root@escape:~# 
```

**Comment by krishnasrinivas** [comment]
"return early" style results in better indentation and more readable code:
for ex:
```
func getProcCGroup(pid int) (proc procCGroup, err error) {                                   
        var r *os.File                                                                       
        if r, err = os.Open(fmt.Sprintf("/proc/%d/cgroup", pid)); err == nil {               
                defer r.Close()                                                              
                return parseProcCGroup(r)                                                    
        }                                                                                    
        return proc, err                                                                     
}
```
Vs
```
func getProcCGroup(pid int) (proc procCGroup, err error) {                                   
        r, err := os.Open(fmt.Sprintf("/proc/%d/cgroup", pid))                               
        if err != nil {                                                                      
                return proc, err                                                             
        }                                                                                    
        defer r.Close()                                                                      
        return parseProcCGroup(r)                                                            
}
```

Another ex:
```
func getCGroupMemoryLimit(pid int) (limit uint64, err error) {                               
        if cgroups, err := getProcCGroup(pid); err == nil {                                  
                if memory := cgroups.getByName("memory"); len(memory) != 0 {                 
                        // Pick the first one.                                               
                        limit, err = getMemoryCGroupMemoryLimit(memory[0])                   
                }                                                                            
        }                                                                                    
        return limit, err                                                                    
} 
```
Vs
```
func getCGroupMemoryLimit(pid int) (limit uint64, err error) {                               
        cgroups, err := getProcCGroup(pid)                                                   
        if err != nil {                                                                      
                return 0, err                                                                
        }                                                                                    
        memory := cgroups.getByName("memory")                                                
        if len(memory) == 0 {                                                                
                return 0, nil                                                                
        }                                                                                    
        // Pick the first one.                                                               
        return getMemoryCGroupMemoryLimit(memory[0])                                         
}
```

**Comment by harshavardhana** [comment]
> mempathseg=${awk -F: '$2 ~ /^memory$/ {print $3}'  /proc/1/cgroup}
> 
> mempath=/sys/fs/cgroup/memory/
> if [[ "$mempathseg" != /docker/* ]]; then
>     mempath="$mempath$mempathseg"
> fi
> mempath="$mempath/memory.limit_in_bytes"
> 
> memsize=$(cat $mempath)

You cannot always just assume the proc to be '1' always each PID can have its own limits based on which groupname the process is associated with.  The current code handles all scenarios not just defaulting to the init process memory limit alone.  

Process id is needed to know the exact groupname as well while on docker it is not necessary since the process you are running i.e minio is always pid "1"  - But this code caters for process outside containers i.e on a regular operating system as well.

File: pkg/sys/cgroup_linux.go (hunk 7 above)
Comment (harshavardhana) [reply pkg/sys/cgroup_linux.go]: done

File: pkg/sys/cgroup_linux.go (hunk 8 above)
Comment (harshavardhana) [reply pkg/sys/cgroup_linux.go]: done

**Review by krishnasrinivas — APPROVED** [review]

**Comment by balamurugana** [comment]
> You cannot always just assume the proc to be '1' always each PID can have its own limits based on which groupname the process is associated with. The current code handles all scenarios not just defaulting to the init process memory limit alone.
> 
> Process id is needed to know the exact groupname as well while on docker it is not necessary since the process you are running i.e minio is always pid "1" - But this code caters for process outside containers i.e on a regular operating system as well.

I was merely showing a logic not to use PID 1.

This patch has unnecessary types and parsing code to find PID's memory path segment.

**Comment by harshavardhana** [comment]
> This patch has unnecessary types and parsing code to find PID's memory path segment.

Let me see if i can further simplify this.

**Comment by balamurugana** [comment]
Below is the equivalent go code.  These functions are better unit testable.

```go
func getProcMemPathSegment() (memPathSegment string, err error) {
	pidCGroupFile := fmt.Sprintf("/proc/%d/cgroup", os.Getpid())
	file, err := os.Open(pidCGroupFile)
	if err != nil {
		return memPathSegment, err
	}
	defer file.Close()

	scanner := bufio.NewScanner(file)
	for scanner.Scan() {
		line := scanner.Text()

		tokens := strings.SplitN(line, ":", 2)
		if len(tokens) != 2 {
			continue
		}

		tokens = strings.SplitN(line, ":", 2)
		if len(tokens) != 2 {
			continue
		}

		if tokens[0] == "memory" {
			memPathSegment = tokens[1]
			break
		}
	}
	err = scanner.Err()

	return memPathSegment, err
}

const cgroupMemoryPathPrefix = "/sys/fs/cgroup/memory"

func getProcMemFilename() (string, error) {
	memPathSegment, err := getProcMemPathSegment()
	if err != nil {
		return "", err
	}

	memFile := cgroupMemoryPathPrefix
	if !strings.HasPrefix(memPathSegment, "/docker/") {
		memFile = filepath.Join(memFile, memPathSegment)
	}
	memFile = filepath.Join(memFile, "memory.limit_in_bytes")

	return memFile, nil
}

func getProcMemLimit(memFile string) (limit int, err error) {
	data, err := ioutil.ReadFile(memFile)
	if err != nil {
		return limit, err
	}

	dataString := strings.TrimSpace(string(data))
	limit, err = strconv.Atoi(dataString)

	return limit, err
}
```

**Comment by harshavardhana** [comment]
It would be neat to send a PR to my branch @balamurugana

**Comment by harshavardhana** [comment]
> tokens := strings.SplitN(line, ":", 2)
> 		if len(tokens) != 2 {
> 			continue
> 		}
> 
> 		tokens = strings.SplitN(line, ":", 2)
> 		if len(tokens) != 2 {
> 			continue
> 		}
> 
> 		if tokens[0] == "memory" {
> 			memPathSegment = tokens[1]
> 			break
> 		}

There are bugs in this there is a changes that tokens have "name=" in some of the cgroup versions, which leads to an issue where "memory" string is never found. 

Let me bring changes in cgroup only to look for `memory`

**Comment by harshavardhana** [comment]
can you review this again @balamurugana .

File: cmd/server-rlimit.go (hunk 5 above)
Comment (balamurugana) [reply cmd/server-rlimit.go]: But why can't it do `os.Getpid()` inside `sys.GetStats()` ?

Comment (harshavardhana) [reply cmd/server-rlimit.go]: It can @balamurugana but it didn't look idiomatic to me. It looks little clumsy.

Comment (balamurugana) [reply cmd/server-rlimit.go]: As `sys` package is minio specific, I don't think generic PID specific is necessary.  Better `sys` should return cgroup memory limit of current process than some other process.

File: pkg/cgroup/cgroup_linux.go [hunk 9]
```diff
@@ -0,0 +1,260 @@
...
+	// Default docker prefix.
+	dockerPrefixName = "/docker/"
+
+	// Proc controller group path.
+	procCGroupPath = "/proc/%d/cgroup"
+
+	// CGroup entry separator
+	cgroupEntrySep   = ":"
+	cgroupNameSep    = ","
+	cgroupNamePrefix = "name="
```
Comment (balamurugana) [inline pkg/cgroup/cgroup_linux.go]: As they are specific to file format, these constants are overkill.  They make `parseProcCGroup()` function harder to read and understand.

File: pkg/cgroup/cgroup_linux.go [hunk 10]
```diff
@@ -0,0 +1,260 @@
...
+// DO NOT EDIT following constants are chosen defaults for any kernel
+// after 3.x, please open a github issue https://github.com/minio/minio/issues
+// and discuss first if you wish to change this.
+const (
+	// Default value for any error or if cgroup is not set.
+	// this is the defautl if cgroups are not used/configured.
+	unlimitedMemoryLimit = 9223372036854771712
+
+	// Default string for looking for kernel memory param.
+	memoryLimitInBytes = "memory.limit_in_bytes"
```
Comment (balamurugana) [inline pkg/cgroup/cgroup_linux.go]: I see this is a kernel parameter name.  Better name could be `memoryLimitKernelParam`?

File: pkg/cgroup/cgroup_linux.go [hunk 11]
```diff
@@ -0,0 +1,260 @@
...
+
+	// Points to sys path memory path.
+	cgroupMemSysPath = "/sys/fs/cgroup/memory"
+
+	// Default mem controller name.
+	cgroupMemName = "memory"
```
Comment (balamurugana) [inline pkg/cgroup/cgroup_linux.go]: As this constant is used at only one place, there is no need to be a constant.

File: pkg/cgroup/cgroup_linux.go [hunk 12]
```diff
@@ -0,0 +1,260 @@
...
+// at /proc/<pid>/cgroup.
+type CGroup struct {
+	ID   int    // Unique cgroup ID (Assigned usually by kernel).
+	Name string // Name of cgroup type.
+	Path string // Path in /sys/fs/cgroup.
+}
+
+// GetCGByName - returns all the cgroups matching the controller name
+// of the cgroup entry.
+func (pcg ProcCGroup) GetCGByName(name string) (res []CGroup) {
```
Comment (balamurugana) [inline pkg/cgroup/cgroup_linux.go]: Group this function to the type.

File: pkg/cgroup/cgroup_linux.go [hunk 13]
```diff
@@ -0,0 +1,260 @@
...
+//
+// Following code block parses this information and
+// returns a procCGroup which is a parsed list of all
+// the line by line entires from /proc/<pid>/cgroup.
+func parseProcCGroup(r io.Reader) (ProcCGroup, error) {
+	var proc ProcCGroup
+
+	// Start reading cgroup categories line by line
+	// and process them into procCGroup structure.
+	fileScanner := bufio.NewScanner(r)
```
Comment (balamurugana) [inline pkg/cgroup/cgroup_linux.go]: As this function gets a `io.Reader`, `scanner` is appropriate.

File: pkg/cgroup/cgroup_linux.go [hunk 14]
```diff
@@ -0,0 +1,260 @@
...
+)
+
+// ProcCGroup - represents all the entries in a process cgroup file
+// at /proc/<pid>/cgroup.
+type ProcCGroup []CGroup
+
+// CGroup - represents the each cgroup entry in process cgroup file
+// at /proc/<pid>/cgroup.
+type CGroup struct {
+	ID   int    // Unique cgroup ID (Assigned usually by kernel).
```
Comment (balamurugana) [inline pkg/cgroup/cgroup_linux.go]: * How useful `ID` is? I don't think it's useful practically
* If `ID` is removed, it would better to have `CGroup`  as `map[string][]string`
* I feel `CGroup` name is too generic.  As the file `/proc/$PID/cgroup` contains process's cgroup membership, how about better naming?

File: pkg/cgroup/cgroup_linux.go [hunk 15]
```diff
@@ -0,0 +1,260 @@
...
+	for fileScanner.Scan() {
+		line := fileScanner.Text()
+
+		tokens := strings.SplitN(line, cgroupEntrySep, 3)
+		if len(tokens) < 3 {
+			continue
+		}
+
+		id, name, path := tokens[0], tokens[1], tokens[2]
+		for len(name) != 0 {
```
Comment (balamurugana) [inline pkg/cgroup/cgroup_linux.go]: Below is better than `strings.SplitN()` for loop.

```go
for token := range strings.Split(name, cgroupNameSep) {
    name := strings.TrimPrefix(token, cgroupNamePrefix)
    n, err := strconv.Atoi(id)
    if err != nil {
        return nil, err
    }
    proc = append(proc, CGroup{id, name, path})
}
```

File: pkg/cgroup/cgroup_linux.go [hunk 16]
```diff
@@ -0,0 +1,260 @@
...
+	cgmProgGetValue = "getvalue"
+)
+
+// Fetch value of the cgroup kernel param from the cgroup manager,
+// if cgroup manager is configured we should just rely on `cgm` cli
+// to fetch all the values for us.
+func getCGroupManagerKernValue(cg CGroup, kernParam string) (limit uint64, err error) {
+	limit = unlimitedMemoryLimit
+
+	cmd := exec.Command(cgmProgName, cgmProgGetValue, cg.Name, cg.Path, kernParam)
```
Comment (balamurugana) [inline pkg/cgroup/cgroup_linux.go]: You could use string literal than the constant to better readability.

File: pkg/cgroup/cgroup_linux.go [hunk 17]
```diff
@@ -0,0 +1,260 @@
...
+	var out bytes.Buffer
+	cmd.Stdout = &out
+	if err = cmd.Run(); err != nil {
+		return limit, err
+	}
+
+	var v uint64
+	v, err = strconv.ParseUint(strings.TrimSpace(out.String()), 10, 64)
```
Comment (balamurugana) [inline pkg/cgroup/cgroup_linux.go]: As this function is generic enough, for any kernelParam, is the output always uint64?

File: pkg/cgroup/cgroup_linux.go [hunk 18]
```diff
@@ -0,0 +1,260 @@
...
+	// Action param name used to fetch value for a particular
+	// controller.
+	cgmProgGetValue = "getvalue"
+)
+
+// Fetch value of the cgroup kernel param from the cgroup manager,
+// if cgroup manager is configured we should just rely on `cgm` cli
+// to fetch all the values for us.
+func getCGroupManagerKernValue(cg CGroup, kernParam string) (limit uint64, err error) {
+	limit = unlimitedMemoryLimit
```
Comment (balamurugana) [inline pkg/cgroup/cgroup_linux.go]: As `unlimitedMemoryLimit` is treated as return value when `err != nil`, you could better return `0` than `uint64(-1)`.  There is no meaning to `limit` when `err != nil`

File: pkg/cgroup/cgroup_linux.go [hunk 19]
```diff
@@ -0,0 +1,260 @@
...
+		return limit, err
+	}
+
+	memory := pcg.GetCGByName(cgroupMemName)
+	if len(memory) == 0 {
+		return limit, errors.New("Unable to locate any memory limits")
+	}
+
+	// Pick the first entry in memory controller.
+	cg := memory[0]
```
Comment (balamurugana) [inline pkg/cgroup/cgroup_linux.go]: Why ignore others except first entry?  If you are expecting only one entry for memory, you could error out ie multiple memory entires is a unknown situation this may send wrong information.

File: pkg/cgroup/cgroup_linux.go [hunk 20]
```diff
@@ -0,0 +1,260 @@
...
+ * Unless required by applicable law or agreed to in writing, software
+ * distributed under the License is distributed on an "AS IS" BASIS,
+ * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
+ * See the License for the specific language governing permissions and
+ * limitations under the License.
+ */
+
+// Package cgroup implements parsing for all the cgroup
+// categories and functionality in a simple way.
+package cgroup
```
Comment (balamurugana) [inline pkg/cgroup/cgroup_linux.go]: As functions in this package are scoped to its limit, there is no need to have them `CGroup` prefixed

**Review by balamurugana — CHANGES_REQUESTED** [review]

File: pkg/cgroup/cgroup_linux.go (hunk 17 above)
Comment (harshavardhana) [reply pkg/cgroup/cgroup_linux.go]: Yes that is correct this value is always non-negative uint64 value.

File: pkg/cgroup/cgroup_linux.go (hunk 19 above)
Comment (harshavardhana) [reply pkg/cgroup/cgroup_linux.go]: Expectation is only one entry,  error is better.

File: pkg/cgroup/cgroup_linux.go (hunk 20 above)
Comment (harshavardhana) [reply pkg/cgroup/cgroup_linux.go]: Sure

File: pkg/cgroup/cgroup_linux.go (hunk 11 above)
Comment (harshavardhana) [reply pkg/cgroup/cgroup_linux.go]: Sure

File: pkg/cgroup/cgroup_linux.go (hunk 10 above)
Comment (harshavardhana) [reply pkg/cgroup/cgroup_linux.go]: Sure

File: pkg/cgroup/cgroup_linux.go (hunk 9 above)
Comment (harshavardhana) [reply pkg/cgroup/cgroup_linux.go]: Yeah better.

File: pkg/cgroup/cgroup_linux.go (hunk 14 above)
Comment (harshavardhana) [reply pkg/cgroup/cgroup_linux.go]: Will fix it.

File: pkg/cgroup/cgroup_linux.go (hunk 18 above)
Comment (harshavardhana) [reply pkg/cgroup/cgroup_linux.go]: unlimitedMemoryLimit - is the default value if cgroup is not configured 

```
$ cat /sys/fs/cgroup/memory/memory.limit_in_bytes 
9223372036854771712
```

Just helps in handling the top level code.

File: pkg/cgroup/cgroup_linux.go (hunk 16 above)
Comment (harshavardhana) [reply pkg/cgroup/cgroup_linux.go]: Yep will do.

File: pkg/cgroup/cgroup_linux.go (hunk 15 above)
Comment (harshavardhana) [reply pkg/cgroup/cgroup_linux.go]: Sure.. the whole thing is completely changed now.

File: pkg/cgroup/cgroup_linux.go (hunk 12 above)
Comment (harshavardhana) [reply pkg/cgroup/cgroup_linux.go]: Sure

File: pkg/cgroup/cgroup_linux.go (hunk 13 above)
Comment (harshavardhana) [reply pkg/cgroup/cgroup_linux.go]: Makes sense.

**Comment by harshavardhana** [comment]
Fixed all the comments @balamurugana - ready for one more round.

**Comment by harshavardhana** [comment]
Ping @balamurugana anything else needed here ?

File: pkg/cgroup/linux.go [hunk 21]
```diff
@@ -0,0 +1,213 @@
...
+	"strings"
+)
+
+// DO NOT EDIT following constants are chosen defaults for any kernel
+// after 3.x, please open a github issue https://github.com/minio/minio/issues
+// and discuss first if you wish to change this.
+const (
+	// Default value for any error or if cgroup is not set.
+	// this is the defautl if cgroups are not used/configured.
+	unlimitedMemoryLimit = 9223372036854771712
```
Comment (balamurugana) [inline pkg/cgroup/linux.go]: As you see consumer functions of this const, its used to be returned when `err != nil` ie on success file read or command execution, it returns the read value.

In an error situation, returning any value as limit is (has to be) discarded.  So there is no need of this const.

File: pkg/cgroup/linux.go [hunk 22]
```diff
@@ -0,0 +1,213 @@
...
+	// Proc controller group path.
+	procCGroupPath = "/proc/%d/cgroup"
+)
+
+// CGEntries - represents all the entries in a process cgroup file
+// at /proc/<pid>/cgroup.
+type CGEntries map[string][]string
+
+// GetCGPathByName - returns the path matching the controller name.
+func (cg CGEntries) GetCGPathByName(cname string) (path string) {
```
Comment (balamurugana) [inline pkg/cgroup/linux.go]: I think this function is not necessary. As map is its base type.  The consumer can directly do `cg[key]`, its up to the consumer what to do with value as string slice.

In case of `GetCGroupMemoryLimit()`, it could error out if more than one value in slice as we agreed previously.

File: pkg/cgroup/linux.go [hunk 23]
```diff
@@ -0,0 +1,213 @@
...
+	memoryLimitKernelParam = "memory.limit_in_bytes"
+
+	// Points to sys path memory path.
+	cgroupMemSysPath = "/sys/fs/cgroup/memory"
+
+	// Default docker prefix.
+	dockerPrefixName = "/docker/"
+
+	// Proc controller group path.
+	procCGroupPath = "/proc/%d/cgroup"
```
Comment (balamurugana) [inline pkg/cgroup/linux.go]: `cgroupFileTemplate` would be better.

File: pkg/cgroup/linux.go [hunk 24]
```diff
@@ -0,0 +1,213 @@
...
+
+		tokens := strings.SplitN(line, ":", 3)
+		if len(tokens) < 3 {
+			continue
+		}
+
+		_, name, path := tokens[0], tokens[1], tokens[2]
+		for _, token := range strings.Split(name, ",") {
+			name = strings.TrimPrefix(token, "name=")
+			proc[name] = []string{path}
```
Comment (balamurugana) [inline pkg/cgroup/linux.go]: if `name` already exists in `proc`, previous value is lost.

File: pkg/cgroup/linux.go [hunk 25]
```diff
@@ -0,0 +1,213 @@
...
+
+// Control group manager CLI defaults.
+const (
+	// Change this if at all in future control group manager
+	// changes their cli name.
+	cgmProgName = "cgm"
+
+	// Action param name used to fetch value for a particular
+	// controller.
+	cgmProgGetValue = "getvalue"
```
Comment (balamurugana) [inline pkg/cgroup/linux.go]: I think you said of removing these consts.

File: pkg/cgroup/linux.go [hunk 26]
```diff
@@ -0,0 +1,213 @@
...
+	}
+
+	var v uint64
+	v, err = strconv.ParseUint(strings.TrimSpace(out.String()), 10, 64)
+	if err != nil {
+		return limit, err
+	}
+
+	limit = v
+	return limit, nil
```
Comment (balamurugana) [inline pkg/cgroup/linux.go]: Below code is enough, as no one supposes to use `limit` in case of error is set.

```go
limit, err = strconv.ParseUint(strings.TrimSpace(out.String()), 10, 64)
return limit, err
```

little line saver is
```go
    var out bytes.Buffer
    cmd := exec.Command(cgmProgName, cgmProgGetValue, cname, path, kernParam)
    cmd.Stdout = &out
    if err = cmd.Run(); err == nil {
        limit, err = strconv.ParseUint(strings.TrimSpace(out.String()), 10, 64)
    }

    return limit, err
```

File: pkg/cgroup/linux.go [hunk 27]
```diff
@@ -0,0 +1,213 @@
...
+		var b []byte
+		b, err = ioutil.ReadFile(getCGroupMemoryLimitFilePath(path))
+		if err != nil {
+			return limit, err
+		}
+
+		v, err = strconv.ParseUint(strings.TrimSpace(string(b)), 10, 64)
+		if err != nil {
+			return limit, err
+		}
```
Comment (balamurugana) [inline pkg/cgroup/linux.go]: Below code is enough, as no one supposes to use `limit` in case of error is set.

```go
if limit, err = getCGroupManagerKernValue("memory", path, memoryLimitKernelParam); err == nil {
    return limit, err
}

var b []byte
if b, err = ioutil.ReadFile(getCGroupMemoryLimitFilePath(path)); err == nil {
    limit, err = strconv.ParseUint(strings.TrimSpace(string(b)), 10, 64)
}
return limit, err
```

File: pkg/cgroup/linux_test.go [hunk 28]
```diff
@@ -0,0 +1,94 @@
...
+9:hugetlb:/
+8:net_cls,net_prio:/
+7:perf_event:/
+6:pids:/user.slice/user-1000.slice
+5:devices:/user.slice
+4:cpuset:/
+3:cpu,cpuacct:/user.slice
+2:freezer:/
+1:name=systemd:/user.slice/user-1000.slice/session-1.scope
+`
```
Comment (balamurugana) [inline pkg/cgroup/linux_test.go:47]: You could add more case for multiple values for same keys.

File: pkg/cgroup/linux.go [hunk 29]
```diff
@@ -0,0 +1,213 @@
...
+	}
+
+	// Final path.
+	return filepath.Join(path, memoryLimitKernelParam)
+}
+
+// GetCGroupMemoryLimit - Fetches cgroup memory limit either
+// from a file path at '/sys/fs/cgroup/memory', if path fails then
+// fallback to querying cgroup manager.
+func GetCGroupMemoryLimit(pid int) (limit uint64, err error) {
```
Comment (balamurugana) [inline pkg/cgroup/linux.go]: This exposed function `GetCGroupMemoryLimit` can be `GetMemoryLimit` to be used as `cgroup.GetMemoryLimit()`

File: pkg/cgroup/linux.go [hunk 30]
```diff
@@ -0,0 +1,213 @@
...
+
+	// Action param name used to fetch value for a particular
+	// controller.
+	cgmProgGetValue = "getvalue"
+)
+
+// Fetch value of the cgroup kernel param from the cgroup manager,
+// if cgroup manager is configured we should just rely on `cgm` cli
+// to fetch all the values for us.
+func getCGroupManagerKernValue(cname, path, kernParam string) (limit uint64, err error) {
```
Comment (balamurugana) [inline pkg/cgroup/linux.go]: Does `cgm` gives other than `/sys/fs/cgroup/$MEMPATH/memory.limit_in_bytes`?
Is there a chance of missing `/sys/fs/cgroup/$MEMPATH/memory.limit_in_bytes` file?

File: pkg/sys/stats_bsd.go [hunk 31]
```diff
@@ -39,7 +39,7 @@ func getHwPhysmem() (uint64, error) {
 }
 
 // GetStats - return system statistics for bsd.
-func GetStats() (stats Stats, err error) {
+func GetStats(pid int) (stats Stats, err error) {
```
Comment (balamurugana) [inline pkg/sys/stats_bsd.go]: `pid` parameter should be removed.

**Review by balamurugana — CHANGES_REQUESTED** [review]

File: pkg/cgroup/linux.go (hunk 30 above)
Comment (harshavardhana) [reply pkg/cgroup/linux.go]: No there isn't.

File: pkg/sys/stats_bsd.go (hunk 31 above)
Comment (harshavardhana) [reply pkg/sys/stats_bsd.go]: Oh yes.

File: pkg/cgroup/linux.go (hunk 22 above)
Comment (harshavardhana) [reply pkg/cgroup/linux.go]: Agreed.

File: pkg/cgroup/linux.go (hunk 30 above)
Comment (harshavardhana) [reply pkg/cgroup/linux.go]: Cgm doesn't read this file it makes UNIX socket connection to cgm manager which returns it over a DBus call.

File: pkg/cgroup/linux.go (hunk 26 above)
Comment (harshavardhana) [reply pkg/cgroup/linux.go]: This style was avoided on purpose as Krishna suggested on readability loss.

File: pkg/cgroup/linux_test.go (hunk 28 above)
Comment (harshavardhana) [reply pkg/cgroup/linux_test.go:47]: Will do

File: pkg/cgroup/linux.go (hunk 27 above)
Comment (harshavardhana) [reply pkg/cgroup/linux.go]: This style of coding is avoided because of readability argument Krishna posted earlier. Let me see how I can refactor it properly.

File: pkg/cgroup/linux.go (hunk 26 above)
Comment (balamurugana) [reply pkg/cgroup/linux.go]: I couldn't able to get what readability lost.

Comment (harshavardhana) [reply pkg/cgroup/linux.go]: basically the idea is to handle the error case first not success.

File: pkg/cgroup/linux.go (hunk 29 above)
Comment (harshavardhana) [reply pkg/cgroup/linux.go]: Sure

File: pkg/cgroup/linux.go (hunk 25 above)
Comment (harshavardhana) [reply pkg/cgroup/linux.go]: Yes, forgot.

File: pkg/cgroup/linux.go (hunk 24 above)
Comment (harshavardhana) [reply pkg/cgroup/linux.go]: Fixed.

File: pkg/cgroup/linux_test.go (hunk 28 above)
Comment (harshavardhana) [reply pkg/cgroup/linux_test.go:47]: Multiple values for same keys are not possible, but multiple keys are possible for the same value.  Like `cpu,cpuacct`

Comment (harshavardhana) [reply pkg/cgroup/linux_test.go:47]: Same process can have different controllers in different groups as well. But ending path is always unique

File: pkg/cgroup/linux.go (hunk 24 above)
Comment (harshavardhana) [reply pkg/cgroup/linux.go]: Fixed

File: pkg/cgroup/linux.go (hunk 25 above)
Comment (harshavardhana) [reply pkg/cgroup/linux.go]: Fixed

File: pkg/cgroup/linux.go (hunk 21 above)
Comment (harshavardhana) [reply pkg/cgroup/linux.go]: Agreed

File: pkg/cgroup/linux.go (hunk 23 above)
Comment (harshavardhana) [reply pkg/cgroup/linux.go]: Sure

**Comment by harshavardhana** [comment]
ping @balamurugana - PR updated once again with the changes requested. Can you check again?

File: pkg/cgroup/linux.go [hunk 32]
```diff
@@ -0,0 +1,177 @@
...
+	// Default docker prefix.
+	dockerPrefixName = "/docker/"
+
+	// Proc controller group path.
+	cgroupFileTemplate = "/proc/%d/cgroup"
+)
+
+// CGEntries - represents all the entries in a process cgroup file
+// at /proc/<pid>/cgroup as key value pairs.
+type CGEntries map[string]string
```
Comment (balamurugana) [inline pkg/cgroup/linux.go:55]: :+1:

**Review by balamurugana — APPROVED** [review]
