### PR TITLE
Fix net.Listener wrapper to fully close the underlying socket.

### LINKED ISSUE #3164: [distributed] Ignore the error returned by http.Serve after listener has been closed.
```
$ minio server --address ":9002" ~/test

Endpoint:  http://10.1.10.162:9002  http://127.0.0.1:9002  http://172.18.0.1:9002  http://172.17.0.1:9002  http://172.19.0.1:9002
AccessKey: USWUXHGYZQYFYFFIT3RE 
SecretKey: MOJRH0mkL1IPauahWITSVvyDrQbEEIwljvmxdq03 
Region:    us-east-1
SQS ARNs:  arn:minio:sqs:us-east-1:2:amqp arn:minio:sqs:us-east-1:1:redis

Browser Access:
   http://10.1.10.162:9002  http://127.0.0.1:9002  http://172.18.0.1:9002  http://172.17.0.1:9002  http://172.19.0.1:9002

Command-line Access: https://docs.minio.io/docs/minio-client-quickstart-guide
   $ mc config host add myminio http://10.1.10.162:9002 USWUXHGYZQYFYFFIT3RE MOJRH0mkL1IPauahWITSVvyDrQbEEIwljvmxdq03

Object API (Amazon S3 compatible):
   Go:         https://docs.minio.io/docs/golang-client-quickstart-guide
   Java:       https://docs.minio.io/docs/java-client-quickstart-guide
   Python:     https://docs.minio.io/docs/python-client-quickstart-guide
   JavaScript: https://docs.minio.io/docs/javascript-client-quickstart-guide

Drive Capacity: 125 GiB Free, 165 GiB Total
^CERRO[0133] Unable to serve incoming requests.            cause=accept tcp [::]:9002: use of closed network connection location=[server-mux.go:324:(*ServerMux).ListenAndServe.func1()]
```

## Expected Behavior
Listener error like this should not be printed since we are killing the server using CTRL-C. 

## Current Behavior
Prints a non-useful error.

## Possible Solution
Ignore the error and let other errors to be printed. 

## Steps to Reproduce (for bugs)
Just start server and do some i/o and then CTRL-C the server.

## Context
Unnecessary logging should be avoided

## Your Environment
Current master

### LINKED ISSUE #3170: [distributed] ServerMux races waiting on connections to close and adding new incoming connection states
```
==================
WARNING: DATA RACE
Read at 0x00c4203667dc by goroutine 197:
  internal/race.Read()
      /home/travis/.gimme/versions/go1.7.3.linux.amd64/src/internal/race/race.go:37 +0x38
  sync.(*WaitGroup).Add()
      /home/travis/.gimme/versions/go1.7.3.linux.amd64/src/sync/waitgroup.go:71 +0x292
  github.com/minio/minio/cmd.(*ServerMux).connState.func1()
      /home/travis/gopath/src/github.com/minio/minio/cmd/server-mux.go:387 +0x1f3
  net/http.(*conn).setState()
      /home/travis/.gimme/versions/go1.7.3.linux.amd64/src/net/http/server.go:1473 +0x96
  net/http.(*Server).Serve()
      /home/travis/.gimme/versions/go1.7.3.linux.amd64/src/net/http/server.go:2292 +0x50a
  github.com/minio/minio/cmd.(*ServerMux).ListenAndServe.func1()
      /home/travis/gopath/src/github.com/minio/minio/cmd/server-mux.go:323 +0x7e
Previous write at 0x00c4203667dc by goroutine 416:
  internal/race.Write()
      /home/travis/.gimme/versions/go1.7.3.linux.amd64/src/internal/race/race.go:41 +0x38
  sync.(*WaitGroup).Wait()
      /home/travis/.gimme/versions/go1.7.3.linux.amd64/src/sync/waitgroup.go:129 +0x151
  github.com/minio/minio/cmd.(*ServerMux).Close()
      /home/travis/gopath/src/github.com/minio/minio/cmd/server-mux.go:372 +0x350
  github.com/minio/minio/cmd.TestListenAndServePlain()
      /home/travis/gopath/src/github.com/minio/minio/cmd/server-mux_test.go:261 +0x4f6
  testing.tRunner()
      /home/travis/.gimme/versions/go1.7.3.linux.amd64/src/testing/testing.go:610 +0xc9
Goroutine 197 (running) created at:
  github.com/minio/minio/cmd.(*ServerMux).ListenAndServe()
      /home/travis/gopath/src/github.com/minio/minio/cmd/server-mux.go:325 +0x291
  github.com/minio/minio/cmd.TestListenAndServePlain.func2()
      /home/travis/gopath/src/github.com/minio/minio/cmd/server-mux_test.go:234 +0x38
Goroutine 416 (finished) created at:
  testing.(*T).Run()
      /home/travis/.gimme/versions/go1.7.3.linux.amd64/src/testing/testing.go:646 +0x52f
  testing.RunTests.func1()
      /home/travis/.gimme/versions/go1.7.3.linux.amd64/src/testing/testing.go:793 +0xb9
  testing.tRunner()
      /home/travis/.gimme/versions/go1.7.3.linux.amd64/src/testing/testing.go:610 +0xc9
  testing.RunTests()
      /home/travis/.gimme/versions/go1.7.3.linux.amd64/src/testing/testing.go:799 +0x4ba
  testing.(*M).Run()
      /home/travis/.gimme/versions/go1.7.3.linux.amd64/src/testing/testing.go:743 +0x12f
  main.main()
      github.com/minio/minio/cmd/_test/_testmain.go:824 +0x1b8
==================
```

## Expected Behavior
No races seen

## Current Behavior
Races seen

## Possible Solution
Block the accept and change the state of the connections. 

## Steps to Reproduce (for bugs)
Occasionally using our go tests.

## Your Environment

Current master.

### PR DESCRIPTION
**Pull request by harshavardhana**
net.Listener doesn't fully close the underlying socket.

Leads to races and accepting connections. This patch implements 
a way to reject accepting new connections.

## Description
```
// The default Listener returns from Close before the underlying
// socket has been closed if another goroutine has an active
// reference (e.g. is in Accept).
//
// The following sequence of events can happen:
//
// Goroutine 1 is running Accept, and is blocked, waiting for epoll
//
// Goroutine 2 calls Close. It sees an extra reference, and so cannot
//  destroy the socket, but instead decrements a reference, marks the
//  connection as closed and unblocks epoll.
//
// Goroutine 2 returns to the caller, makes a new connection.
// The new connection is sent to the socket (since it hasn't been destroyed)
//
// Goroutine 1 returns from epoll, and accepts the new connection.
//
// To avoid accepting connections after Close, we block Goroutine 2
```

## Motivation and Context
Fixes #3170 
Fixes #3164 

Addresses the problem in Golang - https://github.com/golang/go/issues/10527

## How Has This Been Tested?
Manually and through 'go tests'

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

File: cmd/server-mux.go [hunk 1]
```diff
@@ -294,7 +360,11 @@ func (m *ServerMux) ListenAndServeTLS(certFile, keyFile string) (err error) {
 					}
 				}),
 			)
-			errorIf(serr, "Unable to serve incoming requests.")
+			// Do not print if the message if listener is closed.
+			// if not we are supposed to print the error.
```
Comment (fwessels) [inline cmd/server-mux.go]: typo in comment: ... if the message if ...
and second comment is unnecessary? repeated?

File: cmd/server-mux.go [hunk 2]
```diff
@@ -134,16 +134,88 @@ func (c *ConnMux) Read(b []byte) (int, error) {
...
+// Goroutine 1 returns from epoll, and accepts the new connection.
+//
+// To avoid accepting connections after Close, we block Goroutine 2
+// from returning from Close till Accept returns an error to the user.
 type ListenerMux struct {
 	net.Listener
 	config *tls.Config
+	// Cond is used to signal Close when there are no references to the listener.
+	cond *sync.Cond
+	refs int
```
Comment (fwessels) [inline cmd/server-mux.go:168]: Consider using atomic increment (https://golang.org/pkg/sync/atomic/) ?
This can prevent unnecessary locking and unlocking

**Comment by fwessels** [comment]
Code in itself LGTM.
Using atomic increment we may simplify code/improve performance.

File: cmd/server-mux.go [hunk 3]
```diff
@@ -134,16 +134,88 @@ func (c *ConnMux) Read(b []byte) (int, error) {
...
+	if l == nil {
+		return nil
+	}
+
+	if err := l.Listener.Close(); err != nil {
+		return err
+	}
+
+	l.cond.L.Lock()
+	for l.refs > 0 {
```
Comment (krishnasrinivas) [inline cmd/server-mux.go:206]: here since l.cond.L.Lock() is already held, decRef() will get blocked and never be able to decrement l.refs

Comment (fwessels) [reply cmd/server-mux.go:206]: Maybe one more reason to use atomic increment/decrement?

Comment (krishnasrinivas) [reply cmd/server-mux.go:206]: but using synx.Mutex will be more high level and readable right?

Comment (harshavardhana) [reply cmd/server-mux.go:206]: That is the purpose. Cond is used as a way to suspend the aforementioned go-routine.

Comment (harshavardhana) [reply cmd/server-mux.go:206]: Look at the test case to the condition that is mentioned to handle refs.

Comment (harshavardhana) [reply cmd/server-mux.go:206]: This is what i am talking about  - https://golang.org/pkg/sync/#Cond.Wait

### sync#Cond.Wait

Wait atomically unlocks c.L and suspends execution of the calling goroutine. After later 
resuming execution, Wait locks c.L before returning. Unlike in other systems, Wait cannot 
return unless awoken by Broadcast or Signal.

Because c.L is not locked when Wait first resumes, the caller typically cannot assume 
that the condition is true when Wait returns. Instead, the caller should Wait in a loop:

```
c.L.Lock()
for !condition() {
    c.Wait()
}
... make use of condition ...
c.L.Unlock()
```

File: cmd/server-mux.go (hunk 2 above)
Comment (harshavardhana) [reply cmd/server-mux.go:168]: Locking is still needed in the way functionality can be provided using sync.Cond. This is what i am talking about  - https://golang.org/pkg/sync/#Cond.Wait

### sync#Cond.Wait

Wait atomically unlocks c.L and suspends execution of the calling goroutine. After later 
resuming execution, Wait locks c.L before returning. Unlike in other systems, Wait cannot 
return unless awoken by Broadcast or Signal.

Because c.L is not locked when Wait first resumes, the caller typically cannot assume 
that the condition is true when Wait returns. Instead, the caller should Wait in a loop:

```
c.L.Lock()
for !condition() {
    c.Wait()
}
... make use of condition ...
c.L.Unlock()
```

**Review by krishnasrinivas — APPROVED** [review]
