### PR TITLE
return AWS compliant error if SSE-C key is wrong

### LINKED ISSUE #5202: SSE-C get returns wrong error code if key does not match
The minio server returns different API error if a  wrong key is specified during a valid SSE-C GET request.

## Expected Behavior
```
aws s3api put-object --no-verify-ssl --endpoint-url https://localhost:9000 --bucket my-bucket --key my-secret-diary --sse-customer-algorithm AES256 --sse-customer-key ztlKok1pBAPRmgqJiQrEHzA4vd7nCRwgHs+7twwTVC4= --sse-customer-key-md5 9YM3wnhKW8AuV3T0ID/rNQ== --body ~/my-diary.txt
/usr/lib/python3/dist-packages/urllib3/connectionpool.py:794: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.org/en/latest/security.html
  InsecureRequestWarning)
{
    "SSECustomerKeyMD5": "9YM3wnhKW8AuV3T0ID/rNQ==",
    "SSECustomerAlgorithm": "AES256",
    "ETag": "\"865ee9626c39608a4582e55be6cca926\""
}
➜ ~ aws s3api get-object --no-verify-ssl --endpoint-url https://localhost:9000 --bucket my-bucket --key my-secret-diary --sse-customer-algorithm AES256 --sse-customer-key MzJieXRlc2xvbmdzZWNyZXRrZXltdXN0cHJvdmlkZWQ= --sse-customer-key-md5 7PpPLAK26ONlVUGOWlusfg== ~/my-diary2.txt
/usr/lib/python3/dist-packages/urllib3/connectionpool.py:794: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.org/en/latest/security.html
  InsecureRequestWarning)

An error occurred (AccessDenied) when calling the GetObject operation: Access Denied.
```

## Current Behavior
```
aws s3api put-object --no-verify-ssl --endpoint-url https://localhost:9000 --bucket my-bucket --key my-secret-diary --sse-customer-algorithm AES256 --sse-customer-key ztlKok1pBAPRmgqJiQrEHzA4vd7nCRwgHs+7twwTVC4= --sse-customer-key-md5 9YM3wnhKW8AuV3T0ID/rNQ== --body ~/my-diary.txt
/usr/lib/python3/dist-packages/urllib3/connectionpool.py:794: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.org/en/latest/security.html
  InsecureRequestWarning)
{
    "ETag": "\"ce1489ceeec8883547ac46865fdd0318\"",
    "SSECustomerKeyMD5": "9YM3wnhKW8AuV3T0ID/rNQ==",
    "SSECustomerAlgorithm": "AES256"
}
➜ ~ aws s3api get-object --no-verify-ssl --endpoint-url https://localhost:9000 --bucket my-bucket --key my-secret-diary --sse-customer-algorithm AES256 --sse-customer-key MzJieXRlc2xvbmdzZWNyZXRrZXltdXN0cHJvdmlkZWQ= --sse-customer-key-md5 7PpPLAK26ONlVUGOWlusfg== ~/my-diary2.txt
/usr/lib/python3/dist-packages/urllib3/connectionpool.py:794: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.org/en/latest/security.html
  InsecureRequestWarning)
{
    "ContentType": "application/xml",
    "AcceptRanges": "bytes",
    "Metadata": {}
}
➜
```

## Possible Solution
[DecryptRequest](https://github.com/minio/minio/blob/master/cmd/encryption-v1.go#L256) should return `errSSEKeyMismatch` instead of `errObjectTampered` to be strictly AWS compliant.
 
## Steps to Reproduce (for bugs)
1. Start minio server with TLS
2. Create a SSE-C encrypted object `o` with key `k1` 
3. Try to get SSE-C encrypted object `o` with key `k2`

## Context
Problem encountered during encryption refactoring/ reimplementation of minio-go.
The root cause is that [DecryptRequest](https://github.com/minio/minio/blob/master/cmd/encryption-v1.go#L256) returns `ObjectTampered` which is only one possible error cause:
1. Object was modified -> tampered
2. Client provided key is wrong -> access denied

## Your Environment
current master

### PR DESCRIPTION
**Pull request by aead**
## Description
This PR changes the behavior of DecryptRequest.
Instead of returning `object-tampered` if the client provided
key is wrong DecryptRequest will return `access-denied`.

This is AWS S3 behavior.

## Motivation and Context
Fixes #5202

## How Has This Been Tested?
manually - bug was detected during minio-go encryption refactoring

## Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added unit tests to cover my changes.
- [ ] I have added/updated functional tests in [mint](https://github.com/minio/mint). (If yes, add `mint` PR # here: )
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by aead** [comment]
code-cov: again fs-background append.
Smells like concurrency related problem...

**Review by vadmeste — APPROVED** [review]
LGTM

File: cmd/encryption-v1.go [hunk 1]
```diff
@@ -253,7 +253,9 @@ func DecryptRequest(client io.Writer, r *http.Request, metadata map[string]strin
 		Key: keyEncryptionKey,
 	})
 	if n != 32 || err != nil {
-		return nil, errObjectTampered
+		// Either the provided key does not match or the object was tampered.
+		// To provide strict AWS S3 compatibility we return: access denied.
+		return nil, errSSEKeyMismatch
```
Comment (harshavardhana) [inline cmd/encryption-v1.go:258]: should we return `errSSEKeyMismatch`  for `n != 32` and `err != nil` as errObjectTampered?  is it only possible to decrypt the object to know if the key mismatched?

**Review by harshavardhana — CHANGES_REQUESTED** [review]

File: cmd/encryption-v1.go (hunk 1 above)
Comment (aead) [reply cmd/encryption-v1.go:258]: We don't decrypt the object here. We decrypt the sealed `object-encryption-key`. The sealed `object-encryption-key` is part of the object metadata and is 64 bytes long. (16b header, 32b key, 16b tag). The decryption of the sealed `object-encryption-key` fails if:
 - The client provided key is not correct: `keyEncryptionKey' = SHA256(key' || iv)`
 - The object metadata was modified (IV): `keyEncryptionKey' = SHA256(key || iv')`
 - The object metadata was modified (sealedKey): `authentication tag mismatch`

`n != 32` is always true if `err != nil` - except the `object-encryption-key` was > 32 during encryption but that would be a bug in the `EncryptRequest` function and should never happen!

At this point we don't touch the object at all - only the object metadata. The "problem" is that either the client provided the wrong key OR the metadata (containing an encrypted object key) was modified. There is no way to detect whether the client key is wrong OR the metadata was modified.
Both error handling (key-mismatch or object tampered) would be  correct...

Comment (harshavardhana) [reply cmd/encryption-v1.go:258]: okay

**Review by harshavardhana — APPROVED** [review]
