### PR TITLE
Fix preInit logic when mixed disk situations exist.

### LINKED ISSUE #4903: Running distributed on a fresh setup - storage preparation fails consistently
## Expected Behavior
Distributed setup regardless of being a fresh setup starts consistently. 

## Current Behavior

Following script fails quite consistently. 
```
#!/bin/bash

uuid1=$(uuid)
uuid2=$(uuid)
uuid3=$(uuid)
uuid4=$(uuid)

export MINIO_ACCESS_KEY="minio"
export MINIO_SECRET_KEY="minio123"

mkdir -p "/tmp/$uuid1" "/tmp/$uuid2" "/tmp/$uuid3" "/tmp/$uuid4"
echo "/tmp/$uuid1 /tmp/$uuid2 /tmp/$uuid3 /tmp/$uuid4"
minio server --address localhost:9001 "http://localhost:9001/tmp/${uuid1}" "http://localhost:9002/tmp/${uuid2}" "http://localhost:9003/tmp/${uuid3}" "http://localhost:9004/tmp/${uuid4}"&
minio server --address localhost:9002 "http://localhost:9001/tmp/${uuid1}" "http://localhost:9002/tmp/${uuid2}" "http://localhost:9003/tmp/${uuid3}" "http://localhost:9004/tmp/${uuid4}"&
minio server --address localhost:9003 "http://localhost:9001/tmp/${uuid1}" "http://localhost:9002/tmp/${uuid2}" "http://localhost:9003/tmp/${uuid3}" "http://localhost:9004/tmp/${uuid4}"&
minio server --address localhost:9004 "http://localhost:9001/tmp/${uuid1}" "http://localhost:9002/tmp/${uuid2}" "http://localhost:9003/tmp/${uuid3}" "http://localhost:9004/tmp/${uuid4}"
```

## Possible Solution
Not sure

## Steps to Reproduce (for bugs)
Quite simply run the above referenced script.

## Context
Distributed setup

## Your Environment
master branch.

### PR DESCRIPTION
**Pull request by harshavardhana**
## Description
When servers are started simultaneously across multiple
nodes or simulating a local setup, it can happen such
that one of the servers in setup reaches a following
situation where it observes

 - Some servers are formatted
 - Some servers are unformatted
 - Some servers are offline

Current state machine doesn't handle this correctly, to fix
this situation where we have unformatted, formatted and
disks offline we do not decisively know the course of
action. So we wait for the offline disks to change their state.

Once the offline disks change their state to either one of these
states we can decisively move forward.

  - nil (formatted disk)
  - errUnformattedDisk
  - Or any other error such as errCorruptedDisk.

## Motivation and Context
Fixes #4903

## How Has This Been Tested?
Manually and using 

```sh
#!/bin/bash

uuid1=$(uuid)
uuid2=$(uuid)
uuid3=$(uuid)
uuid4=$(uuid)

export MINIO_ACCESS_KEY="minio"
export MINIO_SECRET_KEY="minio123"

mkdir -p "/tmp/$uuid1" "/tmp/$uuid2" "/tmp/$uuid3" "/tmp/$uuid4"
echo "/tmp/$uuid1 /tmp/$uuid2 /tmp/$uuid3 /tmp/$uuid4"
minio server --address localhost:9001 "http://localhost:9001/tmp/${uuid1}" "http://localhost:9002/tmp/${uuid2}" "http://localhost:9003/tmp/${uuid3}" "http://localhost:9004/tmp/${uuid4}"&
minio server --address localhost:9002 "http://localhost:9001/tmp/${uuid1}" "http://localhost:9002/tmp/${uuid2}" "http://localhost:9003/tmp/${uuid3}" "http://localhost:9004/tmp/${uuid4}"&
minio server --address localhost:9003 "http://localhost:9001/tmp/${uuid1}" "http://localhost:9002/tmp/${uuid2}" "http://localhost:9003/tmp/${uuid3}" "http://localhost:9004/tmp/${uuid4}"&
minio server --address localhost:9004 "http://localhost:9001/tmp/${uuid1}" "http://localhost:9002/tmp/${uuid2}" "http://localhost:9003/tmp/${uuid3}" "http://localhost:9004/tmp/${uuid4}"
```

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

File: cmd/prepare-storage.go [hunk 1]
```diff
@@ -134,22 +134,21 @@ func quickErrToActions(errMap map[error]int) InitActions {
 // - Unformatted setup
 //   - Format/Wait for format when `disksUnformatted == diskCount`
 //
-// - Wait for all when `disksUnformatted + disksOffline == disksCount`
+// - Wait for all when `disksUnformatted + disksOffline + disksUnformatted == disksCount`
```
Comment (krisis) [inline cmd/prepare-storage.go]: the comment seems odd. `disksUnformatted` appears twice in the expression above.

File: cmd/prepare-storage.go [hunk 2]
```diff
@@ -169,17 +168,6 @@ func prepForInitXL(firstDisk bool, sErrs []error, diskCount int) InitActions {
...
-			return WaitForAll
-		}
-
-		// Some disks possibly corrupted and too many unformatted disks.
-		return Abort
-	}
-
 	// Already formatted and in quorum, proceed to initialization of object layer.
 	if disksFormatted >= readQuorum {
 		if disksFormatted+disksOffline == diskCount {
```
Comment (krisis) [inline cmd/prepare-storage.go:172]: In this block of code, we proceed to initialize object layer only if disks are either formatted or offline. But we should initialize object layer and serve GET/HEAD requests on buckets and objects.

Observe what happens in a 8 disk setup where,
```go
  disksFormatted = 4
  disksUnformatted = 2
  disksOffline = 2
  readQuorum = 4
```
With this change, we will wait until one or more disks to be healed or come on-line.

To avoid this we should,
```go
if disksFormatted >= readQuroum {
  if disksFormatted + disksUnformatted + disksOffline == diskCount {
    return InitObjectLayer  
  }
}
```

File: cmd/prepare-storage.go [hunk 3]
```diff
@@ -190,7 +178,14 @@ func prepForInitXL(firstDisk bool, sErrs []error, diskCount int) InitActions {
 		return WaitForHeal
 	}
 
-	// Exhausted all our checks, un-handled errors perhaps we Abort.
+	// Some disks unformatted, Some disks formatted and some disks are offline.
+	// This is an undecisive state - wait for all of offline disks to be online
+	// to figure out the course of action.
+	if disksUnformatted+disksFormatted+disksOffline == diskCount {
+		return WaitForAll
```
Comment (krisis) [inline cmd/prepare-storage.go]: Here we should return `WaitForHeal`. I.e we can initialize object layer when we have `readQuorum` number of formatted disks.

File: cmd/prepare-storage_test.go [hunk 4]
```diff
@@ -101,6 +102,11 @@ func TestPrepForInitXL(t *testing.T) {
 		nil, nil, nil, nil,
 		errServerTimeMismatch, nil, nil, nil,
 	}
+	// Wait for all undecisive state.
+	undecisiveErrs := []error{
+		errDiskNotFound, nil, nil, nil,
+		errUnformattedDisk, errUnformattedDisk, errDiskNotFound, errDiskNotFound,
```
Comment (krisis) [inline cmd/prepare-storage_test.go]: This unit test case captures previous comment.
```go
alsoDecisiveErrs := []error {
  nil, nil, nil, nil,
  errUnformatted, errUnformatted, errDiskNotFound, errDiskNotFound
}
```

**Review by krisis — CHANGES_REQUESTED** [review]

File: cmd/prepare-storage.go (hunk 2 above)
Comment (harshavardhana) [reply cmd/prepare-storage.go:172]: This case is already handled.

File: cmd/prepare-storage.go (hunk 1 above)
Comment (harshavardhana) [reply cmd/prepare-storage.go]: Done

File: cmd/prepare-storage.go (hunk 3 above)
Comment (harshavardhana) [reply cmd/prepare-storage.go]: Explained on why its already handled..

Comment (vadmeste) [reply cmd/prepare-storage.go]: I am not sure, isn't this an infinite waiting ? shouldn't we be able to run the cluster even if we have some nodes < quorum offline ?

File: cmd/prepare-storage.go [hunk 5]
```diff
@@ -280,7 +275,7 @@ func retryFormattingXLDisks(firstDisk bool, endpoints EndpointList, storageDisks
 					printRegularMsg(endpoints, storageDisks, printOnceFn())
 				}
 				return err
-			case WaitForHeal:
+			case SuggestToHeal:
```
Comment (krisis) [inline cmd/prepare-storage.go:278]: The message printed in `case WaitForFormatting` should be "Initializing data volume for first time. Waiting for first server to complete formatting disks (elapsed %s)\n". This is not related to PR but found while reviewing.

File: cmd/prepare-storage.go (hunk 3 above)
Comment (harshavardhana) [reply cmd/prepare-storage.go]: We should wait regardless since we don't have enough quorum to decide anything. @vadmeste . If there are enough corrupted we exit anyways. It is when there are disks offline and we don't have quorum number of formatted disks and some look unformatted. We have to wait infinitely you have to look at the entire flow to understand the state machine here @vadmeste .

File: cmd/prepare-storage.go [hunk 6]
```diff
@@ -169,28 +168,24 @@ func prepForInitXL(firstDisk bool, sErrs []error, diskCount int) InitActions {
...
+
+	// Some disks unformatted, Some disks formatted and some disks are offline.
+	// This is an undecisive state - wait for all of offline disks to be online
+	// to figure out the course of action.
+	if disksUnformatted+disksFormatted+disksOffline == diskCount {
+		return WaitForAll
 	}
 
-	// Exhausted all our checks, un-handled errors perhaps we Abort.
+	// Exhausted all our checks, un-handled situations such as some disks corrupted we Abort.
```
Comment (krisis) [inline cmd/prepare-storage.go:188]: we should stay in `WaitForAll` state even when there are corrupted disks. `disksUnformatted+disksFormatted+disksOffline == diskCount` is not a necessary condition.

E.g, in a 8 disk setup where
```go
disksFormatted = 3
disksOffline = 3
disksCorrupted = 1
disksUnformatted = 1
```
Here we don't have `readQuorum` in formatted disks, so we need to wait. It is still possible that the 1 of the 3 offline disks may be formatted, so we can't abort at this point.

**Review by krisis — CHANGES_REQUESTED** [review]

File: cmd/prepare-storage.go [hunk 7]
```diff
@@ -169,28 +168,24 @@ func prepForInitXL(firstDisk bool, sErrs []error, diskCount int) InitActions {
...
 		if disksFormatted+disksOffline == diskCount {
 			return InitObjectLayer
 		}
 
 		// Some of the formatted disks are possibly corrupted or unformatted, heal them.
-		return WaitForHeal
+		return SuggestToHeal
+	}
+
+	// Some disks unformatted, Some disks formatted and some disks are offline.
```
Comment (vadmeste) [inline cmd/prepare-storage.go]: Can make the comment also say that we don't have quorum here that's why this is undecisive state ?

Comment (harshavardhana) [reply cmd/prepare-storage.go]: Done

**Review by vadmeste — APPROVED** [review]
LGTM & tested

File: cmd/prepare-storage.go [hunk 8]
```diff
@@ -74,8 +74,8 @@ const (
 	// is applicable.
 	FormatDisks InitActions = iota
 
-	// WaitForHeal - Wait for disks to heal.
-	WaitForHeal
+	// SuggestToHeal - Wait for disks to heal.
```
Comment (krisis) [inline cmd/prepare-storage.go]: The comment needs update. s/Wait for disks to heal/ Print heal message and initialize object layer.

Comment (harshavardhana) [reply cmd/prepare-storage.go]: Fixed @krisis

**Review by krisis — APPROVED** [review]
LGTM.
