### PR TITLE
cache only on GET operations

### LINKED ISSUE #7573: CompleteMultipartUpload Error: encoding/hex: invalid byte: U+002D '-'
When uploading using the official Python client to a MinIO server in B2 gateway mode with disk cache enabled, I'm seeing this error consistently:

```
API: CompleteMultipartUpload(bucket=bucketname-with-dashes, object=48191817212958.orig-audio)
Time: 15:07:47 UTC 04/23/2019
RequestID: 159822EB9A67A27A
RemoteHost: 10.233.69.170
UserAgent: Minio (Linux; x86_64) minio-py/4.0.13
Error: encoding/hex: invalid byte: U+002D '-'
       1: cmd/object-api-utils.go:198:cmd.getCompleteMultipartMD5()
       2: cmd/fs-v1-multipart.go:507:cmd.(*FSObjects).CompleteMultipartUpload()
       3: cmd/disk-cache.go:853:cmd.cacheObjects.CompleteMultipartUpload()
       4: cmd/object-handlers.go:2284:cmd.objectAPIHandlers.CompleteMultipartUploadHandler()
       5: net/http/server.go:1995:http.HandlerFunc.ServeHTTP()
```

It does not seem to affect B2, since the file is uploaded and available from B2. It does however affect the disk cache, as the file does not appear in the cache until it's been accessed once.

## Expected Behavior
CompleteMultiPartUpload succeeds and the file is cached in the disk cache.

## Current Behavior
CompleteMultiPartUpload fails, the file is not cached, but is present in B2.

## Steps to Reproduce (for bugs)

1. Setup a MinIO server in gateway and disk cache mode with B2 as the backend.
2. Upload a file via multipart.
3. Check error logs and if file is in cache (it won't be).

## Regression
Unknown.

## Your Environment

* Version used (`minio version`): `RELEASE.2019-04-18T21-44-59Z`
* Environment name and version (e.g. nginx 1.9.1):
* Server type and version:
* Operating System and version (`uname -a`):
* Link to your project:

### PR DESCRIPTION
**Pull request by poornas**
Fixes: #7573, #6265 and #6630

## Description

Some gateway backends may not necessarily return MD5Sum as ETag in UploadPart. For simplicity and consistent performance it was decided to cache only on GET operations.

## Motivation and Context

For compatibility

## Regression
 No

## How Has This Been Tested?

1.  MINIO_CACHE_DRIVES=/tmp/cache minio gateway b2
2. object upload should not cache the object. However a GET operation should save entry in the cache.

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added unit tests to cover my changes.
- [ ] I have added/updated functional tests in [mint](https://github.com/minio/mint). (If yes, add `mint` PR # here: )
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by minio-ops** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-compression-xl.sh | :heavy_check_mark: |
| mint-xl.sh | :heavy_check_mark: |
| mint-compression-dist-xl.sh | :heavy_check_mark: |
| mint-worm.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :x: [more...](#e37b8767-ea59-4d95-ae9b-61c2b782c067) |
| mint-compression-fs.sh | :x: [more...](#1b8dda44-c9e4-475d-ab19-faaec63b1ddd) |
| mint-dist-xl.sh | :x: [more...](#9206f27c-ffec-4345-82d3-c441106a440a) |
<a name="e37b8767-ea59-4d95-ae9b-61c2b782c067"></a>
### 7575-2ff49c5/mint-large-bucket.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.53:30701
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 445d5f021c51:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... FAILED in 6 minutes and 0 seconds
{
  "alert": "",
  "args": {
    "bucketName": "aws-sdk-go-test-kcemn5driw5y4n",
    "expiry": 60000000000,
    "objectName": "presignedTest"
  },
  "duration": 360009,
  "error": "XMinioServerNotInitialized: Server not initialized, please try again.\n\tstatus code: 503, request id: 159836463D36F229, host id: ",
  "function": "PresignedPut",
  "message": "AWS SDK Go CreateBucket Failed",
  "name": "aws-sdk-go",
  "status": "FAIL"
}

Executed 0 out of 14 tests successfully.
```
<a name="1b8dda44-c9e4-475d-ab19-faaec63b1ddd"></a>
### 7575-2ff49c5/mint-compression-fs.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.61:31078
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 3bcd67e990cb:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... FAILED in 0 seconds
{
  "alert": "",
  "args": {
    "bucketName": "aws-sdk-go-test-ct0re3jwy93w5z",
    "expiry": 60000000000,
    "objectName": "presignedTest"
  },
  "duration": 255,
  "error": "RequestError: send request failed\ncaused by: Put http://72.28.97.61:31078/aws-sdk-go-test-ct0re3jwy93w5z: dial tcp 72.28.97.61:31078: connect: connection refused",
  "function": "PresignedPut",
  "message": "AWS SDK Go CreateBucket Failed",
  "name": "aws-sdk-go",
  "status": "FAIL"
}

Executed 0 out of 14 tests successfully.
```
<a name="9206f27c-ffec-4345-82d3-c441106a440a"></a>
### 7575-2ff49c5/mint-dist-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.61:30785
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp c60bb2a87ce8:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... FAILED in 6 minutes and 0 seconds
{
  "alert": "",
  "args": {
    "bucketName": "aws-sdk-go-test-dbvlogb2edlkca",
    "expiry": 60000000000,
    "objectName": "presignedTest"
  },
  "duration": 360011,
  "error": "XMinioServerNotInitialized: Server not initialized, please try again.\n\tstatus code: 503, request id: 1598364643DAAFA1, host id: ",
  "function": "PresignedPut",
  "message": "AWS SDK Go CreateBucket Failed",
  "name": "aws-sdk-go",
  "status": "FAIL"
}

Executed 0 out of 14 tests successfully.
```

**Comment by poornas** [comment]
@donatello , @nitisht this is waiting on your review

**Comment by minio-ops** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-compression-xl.sh | :heavy_exclamation_mark: [more...](#73b70b16-2fec-4ab8-a535-441bce4c3134) |
| mint-xl.sh | :heavy_exclamation_mark: [more...](#e158c98e-f5bd-4b2e-b6c9-4be14b3652d5) |
| mint-large-bucket.sh | :heavy_exclamation_mark: [more...](#d4a6b310-1765-4c5f-9fec-7494da878f57) |
| mint-compression-dist-xl.sh | :heavy_exclamation_mark: [more...](#891c1c69-6e1e-44ec-8c76-1b35368bcc96) |
| mint-compression-fs.sh | :heavy_exclamation_mark: [more...](#04fab6c9-10f0-44d9-99b9-8c74b35814c2) |
| mint-worm.sh | :heavy_exclamation_mark: [more...](#6707b84f-70d8-482c-9251-a15147993bcb) |
| mint-fs.sh | :heavy_exclamation_mark: [more...](#63953173-cfa0-44f4-a4b0-a1a29d95be10) |
| mint-dist-xl.sh | :heavy_exclamation_mark: [more...](#c002f6e3-730b-41e7-8480-a2296bcf2a44) |
| mint-gateway-nas.sh | :heavy_exclamation_mark: [more...](#4567a07f-2bb8-49dd-8240-23ffd8636a2a) |
<a name="4567a07f-2bb8-49dd-8240-23ffd8636a2a"></a>
### 7575-09a4c35/mint-gateway-nas.sh.xtrace:
```
DISABLED TIME BEING
```
<a name="891c1c69-6e1e-44ec-8c76-1b35368bcc96"></a>
### 7575-09a4c35/mint-compression-dist-xl.sh.xtrace:
```
DISABLED TIME BEING
```
<a name="6707b84f-70d8-482c-9251-a15147993bcb"></a>
### 7575-09a4c35/mint-worm.sh.xtrace:
```
DISABLED TIME BEING
```
<a name="04fab6c9-10f0-44d9-99b9-8c74b35814c2"></a>
### 7575-09a4c35/mint-compression-fs.sh.xtrace:
```
DISABLED TIME BEING
```
<a name="e158c98e-f5bd-4b2e-b6c9-4be14b3652d5"></a>
### 7575-09a4c35/mint-xl.sh.xtrace:
```
DISABLED TIME BEING
```
<a name="63953173-cfa0-44f4-a4b0-a1a29d95be10"></a>
### 7575-09a4c35/mint-fs.sh.xtrace:
```
DISABLED TIME BEING
```
<a name="73b70b16-2fec-4ab8-a535-441bce4c3134"></a>
### 7575-09a4c35/mint-compression-xl.sh.xtrace:
```
DISABLED TIME BEING
```
<a name="c002f6e3-730b-41e7-8480-a2296bcf2a44"></a>
### 7575-09a4c35/mint-dist-xl.sh.xtrace:
```
DISABLED TIME BEING
```
<a name="d4a6b310-1765-4c5f-9fec-7494da878f57"></a>
### 7575-09a4c35/mint-large-bucket.sh.xtrace:
```
DISABLED TIME BEING
```

File: cmd/disk-cache.go [hunk 1]
```diff
@@ -846,7 +846,7 @@ func (c cacheObjects) CompleteMultipartUpload(ctx context.Context, bucket, objec
 		return
 	}
 	// create new multipart upload in cache with same uploadID
-	dcache.CompleteMultipartUpload(ctx, bucket, object, uploadID, uploadedParts, opts)
+	dcache.completeMultipartUpload(ctx, bucket, object, uploadID, objInfo.ETag, uploadedParts, opts)
 	return
```
Comment (donatello) [inline cmd/disk-cache.go]: Not sure if I am understanding the PR correctly, but isnt the better approach to simply call dcache.completeMultipartUpload like previously and only write a little code to over-write the ETag coming from the backend into the cache backend?

Comment (poornas) [reply cmd/disk-cache.go]: issue is Part ETag for gateway backends need not be md5sum - fsObjects CompleteMultipartUpload implementation generates the ETag for finalized upload by creating md5hash of concatenated part ETags (see getCompleteMultipartMD5 in object-api-utils.go). If we rely on fsObjects implementation as in master, the part ETag cannot be hex decoded causing overall operation to fail. For cache purposes, we just need to persist the backend ETag in the cache - hence the need for this change.

Comment (donatello) [reply cmd/disk-cache.go]: Yeah i meant that we could add some code to only overwrite the ETag in the cache fs backend alone. This way we can inherit any changes to the CompleteMultipartUpload code - otherwise doing a reimplementation like this will cause some overhead to make sure the two implementations stay in sync.

**Comment by minio-ops** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-compression-xl.sh | :heavy_check_mark: |
| mint-xl.sh | :heavy_check_mark: |
| mint-compression-dist-xl.sh | :heavy_check_mark: |
| mint-compression-fs.sh | :heavy_check_mark: |
| mint-worm.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-dist-xl.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :x: [more...](#4d61a6a2-9bb2-4712-aaf8-12379e59f702) |
<a name="4d61a6a2-9bb2-4712-aaf8-12379e59f702"></a>
### 7575-64fb8a7/mint-large-bucket.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.56:30730
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp c8bf4cdd0bda:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 4 seconds
(2/14) Running aws-sdk-java tests ... done in 2 seconds
(3/14) Running aws-sdk-php tests ... done in 52 seconds
(4/14) Running aws-sdk-ruby tests ... done in 12 seconds
(5/14) Running awscli tests ... done in 2 minutes and 8 seconds
(6/14) Running healthcheck tests ... done in 0 seconds
(7/14) Running mc tests ... done in 44 seconds
(8/14) Running minio-dotnet tests ... FAILED in 2 minutes and 43 seconds

Unhandled Exception: System.AggregateException: One or more errors occurred. (The operation has timed out.) ---> System.Net.WebException: The operation has timed out.
   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
--- End of stack trace from previous location where exception was thrown ---
   at Minio.Functional.Tests.FunctionalTest.PresignedGetObject_Test3(MinioClient minio) in /mint/run/core/minio-dotnet/FunctionalTest.cs:line 2269
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.Wait()
   at Minio.Functional.Tests.FunctionalTest.Main(String[] args) in /mint/run/core/minio-dotnet/FunctionalTest.cs:line 244

Executed 7 out of 14 tests successfully.
```

**Comment by minio-ops** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-xl.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-compression-dist-xl.sh | :heavy_check_mark: |
| mint-compression-fs.sh | :heavy_check_mark: |
| mint-worm.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-dist-xl.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-compression-xl.sh | :x: [more...](#0d9888e8-9e30-478c-a6b3-962e34e283de) |
<a name="0d9888e8-9e30-478c-a6b3-962e34e283de"></a>
### 7575-a838d61/mint-compression-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.53:31768
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 6c0bfbc43cc6:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... FAILED in 6 minutes and 0 seconds
{
  "alert": "",
  "args": {
    "bucketName": "aws-sdk-go-test-gvuovfcamcdnb3",
    "expiry": 60000000000,
    "objectName": "presignedTest"
  },
  "duration": 360018,
  "error": "XMinioServerNotInitialized: Server not initialized, please try again.\n\tstatus code: 503, request id: 159B4CE17924EC2F, host id: ",
  "function": "PresignedPut",
  "message": "AWS SDK Go CreateBucket Failed",
  "name": "aws-sdk-go",
  "status": "FAIL"
}

Executed 0 out of 14 tests successfully.
```

**Review by harshavardhana — CHANGES_REQUESTED** [review]
We shouldn't allow warming based on GET alone, we should do Head as well 

Another thing we need to do is cache after a successful PUT and CompleteMultipart upload This requires PUT and CompleteMultipart to take a callback which updates the cache.

Also we need to state that this is a breaking change and changes existing functionality fundamentally.

**Comment by poornas** [comment]
> We shouldn't allow warming based on GET alone, we should do Head as well
> 
> Another thing we need to do is cache after a successful PUT and CompleteMultipart upload This requires PUT and CompleteMultipart to take a callback which updates the cache.
> 
> Also we need to state that this is a breaking change and changes existing functionality fundamentally.

we could do that - however it seems like caching after Put/CompleteMultipart is done  has potential to leave stale entries in cache for the case where object is deleted before background PUT to cache completes.

**Comment by harshavardhana** [comment]
But a delete would never work if the object is being read, as in being filled in the cache. It is a corner case scenario but the benefits outweigh that situation.

**Comment by nitisht** [comment]
> Another thing we need to do is cache after a successful PUT and CompleteMultipart upload This requires PUT and CompleteMultipart to take a callback which updates the cache.

Are we going to do this in current PR?

**Comment by harshavardhana** [comment]
We need to @nitisht

**Comment by lseelenbinder** [comment]
Hi all, I was the one who originally submitted the bug report leading to the PR. I thought maybe giving some context would be helpful.

Our situation is we upload multi-GB files via the B2 gateway (b2 is a backup in this instance), then process those same multi-GB files a few times locally and then never touch them again. If we're able to upload to B2, have it cached in the process, and then pull from the B2 gateway without hitting B2 and incurring download costs (both actual download fees and higher latency), it solves the problem perfectly for us. If we always have to request the file once from B2 after uploading via the gateway, it would have a pretty big impact on our overall costs of this part of the system (paying at least 1x bandwidth for uploaded objects).

It looks like @harshavardhana is suggesting caching after a successful PUT + complete upload, so I believe the path forward covers our use case, but I wanted to add my voice of support for that happening.

**Comment by poornas** [comment]
this PR can be reviewed,@donatello and @nitisht

**Comment by minio-ops** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-compression-xl.sh | :heavy_check_mark: |
| mint-xl.sh | :heavy_check_mark: |
| mint-compression-dist-xl.sh | :heavy_check_mark: |
| mint-compression-fs.sh | :heavy_check_mark: |
| mint-worm.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-dist-xl.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :x: [more...](#d87fcba9-d827-431e-981e-0f10cc9b735d) |
<a name="d87fcba9-d827-431e-981e-0f10cc9b735d"></a>
### 7575-3a92d7a/mint-large-bucket.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.59:30530
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp e6a83bf16509:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 2 seconds
(2/14) Running aws-sdk-java tests ... done in 2 seconds
(3/14) Running aws-sdk-php tests ... done in 15 minutes and 51 seconds
(4/14) Running aws-sdk-ruby tests ... done in 26 seconds
(5/14) Running awscli tests ... done in 2 minutes and 3 seconds
(6/14) Running healthcheck tests ... done in 0 seconds
(7/14) Running mc tests ... done in 32 seconds
(8/14) Running minio-dotnet tests ... done in 1 minutes and 14 seconds
(9/14) Running minio-go tests ... done in 1 minutes and 50 seconds
(10/14) Running minio-java tests ... FAILED in 8 minutes and 23 seconds
{
  "name": "minio-java",
  "function": "copyObject(String bucketName, String objectName, String destBucketName, CopyConditions copyConditions)",
  "duration": 302204,
  "status": "FAIL",
  "error": "error occurred\nErrorResponse(code=XMinioReadQuorum, message=Multiple disk failures, unable to reconstruct data., bucketName=minio-java-test-ea3hrg, objectName=minio-java-test-3ts74a5, resource=/minio-java-test-ea3hrg/minio-java-test-3ts74a5, requestId=159F88FA81000D1D, hostId=25dc65bb-5feb-4797-a68b-752a6748f0e0)\nrequest={method=GET, url=http://72.28.97.59:30530/minio-java-test-ea3hrg/minio-java-test-3ts74a5, headers=Host: 72.28.97.59:30530\nUser-Agent: Minio (amd64; amd64) minio-java/dev\nx-amz-content-sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855\nx-amz-date: 20190517T173645Z\nAuthorization: AWS4-HMAC-SHA256 Credential=*REDACTED*/20190517/us-east-1/s3/aws4_request, SignedHeaders=host;x-amz-content-sha256;x-amz-date, Signature=*REDACTED*\n}\nresponse={code=503, headers=Accept-Ranges: bytes\nContent-Length: 1024\nContent-Security-Policy: block-all-mixed-content\nContent-Type: application/xml\nETag: \"80691ec7300fd1d401d9822d53178dac-1\"\nLast-Modified: Fri, 17 May 2019 17:36:45 GMT\nRetry-After: 120\nServer: MinIO/DEVELOPMENT.2019-05-17T16-53-26Z\nVary: Origin\nX-Amz-Request-Id: 159F88FA81000D1D\nX-Minio-Deployment-Id: 25dc65bb-5feb-4797-a68b-752a6748f0e0\nX-Xss-Protection: 1; mode=block\nDate: Fri, 17 May 2019 17:36:45 GMT\n}\n >>> [io.minio.MinioClient.executeReq(MinioClient.java:1190), io.minio.MinioClient.execute(MinioClient.java:1056), io.minio.MinioClient.executeGet(MinioClient.java:1284), io.minio.MinioClient.getObject(MinioClient.java:1860), io.minio.MinioClient.getObject(MinioClient.java:1594), FunctionalTest.copyObject_test3(FunctionalTest.java:2101), FunctionalTest.runTests(FunctionalTest.java:3008), FunctionalTest.main(FunctionalTest.java:3121)]"
}

Executed 9 out of 14 tests successfully.
```

**Comment by minio-ops** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-compression-xl.sh | :heavy_check_mark: |
| mint-xl.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-compression-dist-xl.sh | :heavy_check_mark: |
| mint-compression-fs.sh | :heavy_check_mark: |
| mint-worm.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-dist-xl.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |

**Comment by minio-ops** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-compression-xl.sh | :heavy_check_mark: |
| mint-xl.sh | :heavy_check_mark: |
| mint-compression-dist-xl.sh | :heavy_check_mark: |
| mint-compression-fs.sh | :heavy_check_mark: |
| mint-worm.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-dist-xl.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :x: [more...](#113048bf-25a8-4cda-b7f6-b283eda05024) |
<a name="113048bf-25a8-4cda-b7f6-b283eda05024"></a>
### 7575-fd48e91/mint-large-bucket.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.59:31023
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 673d43a19149:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 2 seconds
(2/14) Running aws-sdk-java tests ... done in 2 seconds
(3/14) Running aws-sdk-php tests ... done in 10 minutes and 50 seconds
(4/14) Running aws-sdk-ruby tests ... FAILED in 4 minutes and 15 seconds
{
  "name": "aws-sdk-ruby",
  "function": "copyObject(source_bucket_name, target_bucket_name, source_file_name, target_file_name = )",
  "args": {
    "source_bucket_name": "aws-sdk-ruby-bucket-bbc012b9e1e0",
    "target_bucket_name": "aws-sdk-ruby-bucket-46ba655171b7",
    "source_file_name": "datafile-1-kB",
    "target_file_name": "datafile-1-kB-copy"
  },
  "duration": 242772.23,
  "error": "Net::ReadTimeout",
  "status": "FAIL"
}

Executed 3 out of 14 tests successfully.
```

**Comment by minio-ops** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-compression-xl.sh | :heavy_check_mark: |
| mint-xl.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-compression-dist-xl.sh | :heavy_check_mark: |
| mint-worm.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-dist-xl.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-compression-fs.sh | :x: [more...](#d3ff740f-1bd0-428e-8106-02c8798d3fe9) |
<a name="d3ff740f-1bd0-428e-8106-02c8798d3fe9"></a>
### 7575-f97bfde/mint-compression-fs.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.56:31141
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 484ccd46f308:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 0 seconds
(2/14) Running aws-sdk-java tests ... done in 1 seconds
(3/14) Running aws-sdk-php tests ... done in 41 seconds
(4/14) Running aws-sdk-ruby tests ... done in 1 seconds
(5/14) Running awscli tests ... done in 1 minutes and 45 seconds
(6/14) Running healthcheck tests ... done in 0 seconds
(7/14) Running mc tests ... done in 18 seconds
(8/14) Running minio-dotnet tests ... done in 23 seconds
(9/14) Running minio-go tests ... done in 18 seconds
(10/14) Running minio-java tests ... done in 14 seconds
(11/14) Running minio-js tests ... done in 34 seconds
(12/14) Running minio-py tests ... FAILED in 53 seconds
{
  "error": "Traceback (most recent call last):\n  File \"/mint/run/core/minio-py/tests.py\", line 1226, in test_presigned_get_object_expiry_5sec\n    raise ValueError('Presigned get url failed to expire!')\nValueError: Presigned get url failed to expire!\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"/mint/run/core/minio-py/tests.py\", line 1885, in main\n    test_presigned_get_object_expiry_5sec(client, log_output)\n  File \"/mint/run/core/minio-py/tests.py\", line 1228, in test_presigned_get_object_expiry_5sec\n    raise Exception(err)\nException: Presigned get url failed to expire!\n",
  "function": "presigned_get_object(bucket_name, object_name, expires, response_headers, request_date)",
  "args": {
    "object_name": "05d1ca72-804f-49a5-818d-cc5eee0bc4f9",
    "bucket_name": "minio-py-test-a5f8e5a7-c967-4682-844c-018eb9e8dd2b"
  },
  "duration": 5026,
  "status": "FAIL",
  "name": "minio-py:test_presigned_get_object_expiry_5sec",
  "message": "Presigned get url failed to expire!"
}

Executed 11 out of 14 tests successfully.
```

**Review by nitisht — DISMISSED** [review]
LGTM & Tested

File: cmd/disk-cache-utils.go [hunk 2]
```diff
@@ -0,0 +1,146 @@
...
+	for _, directive := range cacheExcludeDirectives {
+		if s == directive {
+			return true
+		}
+	}
+	return false
+}
+
+// returns struct with cache-control settings from user metadata.
+func getCacheControlOpts(m map[string]string) (c cacheControl, err error) {
```
Comment (nitisht) [inline cmd/disk-cache-utils.go:54]: May be obvious to some users, but can we add a section in document about the supported cache control headers?

Comment (poornas) [reply cmd/disk-cache-utils.go:54]: updated docs for this - @nitisht, PR needs to be reapproved.

**Review by donatello — APPROVED** [review]

**Comment by minio-ops** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-compression-xl.sh | :heavy_check_mark: |
| mint-xl.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-compression-dist-xl.sh | :heavy_check_mark: |
| mint-compression-fs.sh | :heavy_check_mark: |
| mint-worm.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-dist-xl.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |

**Review by nitisht — APPROVED** [review]
