### PR TITLE
gateway: Reject endpoint pointing to local gateway

### LINKED ISSUE #4307: [gateway-s3] Reject endpoint pointing to the gateway itself
## Expected Behavior
The server shows an error when the passed endpoint points to the gateway server itself.

## Current Behavior
The server shows the following error when trying to list buckets (for example):

```
2017/05/09 10:53:09 http: Accept error: accept tcp [::]:9000: accept4: too many open files; retrying in 5ms
2017/05/09 10:53:09 http: Accept error: accept tcp [::]:9000: accept4: too many open files; retrying in 10ms
2017/05/09 10:53:09 http: Accept error: accept tcp [::]:9000: accept4: too many open files; retrying in 20ms
2017/05/09 10:53:09 http: Accept error: accept tcp [::]:9000: accept4: too many open files; retrying in 40ms
2017/05/09 10:53:09 http: Accept error: accept tcp [::]:9000: accept4: too many open files; retrying in 80ms
2017/05/09 10:53:09 http: Accept error: accept tcp [::]:9000: accept4: too many open files; retrying in 160ms
2017/05/09 10:53:09 http: Accept error: accept tcp [::]:9000: accept4: too many open files; retrying in 320ms
2017/05/09 10:53:10 http: Accept error: accept tcp [::]:9000: accept4: too many open files; retrying in 640ms
2017/05/09 10:53:10 http: Accept error: accept tcp [::]:9000: accept4: too many open files; retrying in 1s
2017/05/09 10:53:11 http: Accept error: accept tcp [::]:9000: accept4: too many open files; retrying in 1s
2017/05/09 10:53:12 http: Accept error: accept tcp [::]:9000: accept4: too many open files; retrying in 1s
```

## Possible Solution
Reject endpoint pointing to the gateway itself

## Steps to Reproduce (for bugs)
1. Run gateway
`MINIO_ACCESS_KEY=minio MINIO_SECRET_KEY=minio123 minio gateway s3 http://localhost:9000`
2. List buckets
`mc ls myminio/`

## Context
Testing gateway.

## Your Environment
All.

### PR DESCRIPTION
**Pull request by vadmeste**
## Description
Show an error when the user enters an endpoint url pointing
to the gateway server itself.

## Motivation and Context
Fix #4307 

## How Has This Been Tested?
go test + Manually

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

File: cmd/net.go [hunk 1]
```diff
@@ -186,6 +189,114 @@ func checkPortAvailability(port string) (err error) {
...
+		}
+	}
+
+	return host, port, nil
+}
+
+// isLocalAddr - checks if the given parameter
+// correspond to one of the local IP of the
+// current machine
+func isLocalAddr(host string) (bool, error) {
```
Comment (balamurugana) [inline cmd/net.go]: As `host` refers to name or IP, I prefer `isLocalHost()` over `isLocalAddr()`

File: cmd/net.go [hunk 2]
```diff
@@ -186,6 +189,114 @@ func checkPortAvailability(port string) (err error) {
...
+
+	// If intersection of two IP sets is not empty, then the host is local host.
+	isLocal := !localIP4.Intersection(hostIPs).IsEmpty()
+	return isLocal, nil
+}
+
+// isSameAddr - returns true if two addresses, even with different
+// formats point to the same machine, e.g:
+//   ':9000' and 'http://localhost:9000/' will return true
+func sameLocalAddrs(addr1, addr2 string) (bool, error) {
```
Comment (balamurugana) [inline cmd/net.go]: If `addr1 = 192.168.122.6:9000` and `addr2 = 10.1.10.23:9000` points to same host `myremotehost` where both addresses are not local host, this function returns `false`.  Is this wanted?

File: cmd/net_test.go [hunk 3]
```diff
@@ -240,3 +240,67 @@ func TestCheckLocalServerAddr(t *testing.T) {
 		}
 	}
 }
+
+func TestExtractHostPort(t *testing.T) {
+	testCases := []struct {
+		addr       string
+		host       string
+		port       string
+		shouldFail bool
```
Comment (balamurugana) [inline cmd/net_test.go]: You could compare error messages whether we receive correct error or not.

File: cmd/net_test.go [hunk 4]
```diff
@@ -240,3 +240,67 @@ func TestCheckLocalServerAddr(t *testing.T) {
...
+		}
+	}
+}
+
+func TestSameLocalAddrs(t *testing.T) {
+	testCases := []struct {
+		addr1      string
+		addr2      string
+		sameAddr   bool
+		shouldFail bool
```
Comment (balamurugana) [inline cmd/net_test.go]: same as above.

**Review by balamurugana — CHANGES_REQUESTED** [review]

File: cmd/net.go (hunk 2 above)
Comment (vadmeste) [reply cmd/net.go]: > If addr1 = 192.168.122.6:9000 and addr2 = 10.1.10.23:9000 points to same host myremotehost where both addresses are not local host, this function returns false. Is this wanted?

yes, that's why I called this function sameLocalAddrs()

File: cmd/net.go (hunk 1 above)
Comment (vadmeste) [reply cmd/net.go]: > As host refers to name or IP, I prefer isLocalHost() over isLocalAddr()

Done

File: cmd/net_test.go (hunk 3 above)
Comment (vadmeste) [reply cmd/net_test.go]: > You could compare error messages whether we receive correct error or not.

Done

File: cmd/net_test.go (hunk 4 above)
Comment (vadmeste) [reply cmd/net_test.go]: > same as above.

Done

**Comment by harshavardhana** [comment]
is this PR ready to merged @balamurugana @krishnasrinivas ?

File: cmd/net.go [hunk 5]
```diff
@@ -186,6 +189,114 @@ func checkPortAvailability(port string) (err error) {
...
+		}
+	} else {
+		addr = u.Host
+		scheme = u.Scheme
+	}
+
+	// Use the given parameter again if url.Parse()
+	// didn't return any useful result.
+	if addr == "" {
+		addr = hostAddr
```
Comment (krishnasrinivas) [inline cmd/net.go:216]:
```
root@escape:~# minio gateway --address :80 s3 localhost
FATA[0000] Unable to compare server and endpoint addresses.  cause=unable to guess port from scheme source=[gateway-main.go:197:gatewayMain()]
root@escape:~#
```

is fixed by:
```
--- a/cmd/net.go
+++ b/cmd/net.go
@@ -210,6 +210,7 @@ func extractHostPort(hostAddr string) (string, string, error) {
        // didn't return any useful result.
        if addr == "" {
                addr = hostAddr
+               scheme = "http"
        }
 
        // At this point, addr can be one of the following form:

```

I have half a mind to ask if this PR is really worth the code added. But the code is well written and readable and hence won't ask ;-)

File: cmd/gateway-main.go [hunk 6]
```diff
@@ -185,11 +185,24 @@ func gatewayMain(ctx *cli.Context) {
 	}
 
 	// First argument is selected backend type.
-	backendType := ctx.Args().First()
+	backendType := ctx.Args().Get(0)
+	// Second argument is the endpoint address (optional)
+	endpointAddr := ctx.Args().Get(1)
+	// Third argument is the address flag
+	serverAddr := ctx.String("address")
```
Comment (balamurugana) [inline cmd/gateway-main.go:192]: As this PR is doing input args validation, I see below things here.
* non-empty `serverAddr` should be checked with `CheckLocalServerAddr(serverAddr string)`
* Here valid value format of `endpointAddr` is "", "remote-server", "remote-server:port", "http://remote-server", "https://remote-server:port".  Other than these values are error case.
* there is a special case where `serverAddr` can be a local host only for testing.  In this case, port in `serverAddr` should not be same as `endpointAddr` (as this PR addresses).

If the PR scope is only to last point only, I am not sure how critical to fix that case.  Additionally not sure why gateway is not failing to return error on port already in use.

**Review by balamurugana — CHANGES_REQUESTED** [review]

File: cmd/net.go (hunk 5 above)
Comment (vadmeste) [reply cmd/net.go:216]: thanks @krishnasrinivas, I addressed your comment.

File: cmd/gateway-main.go (hunk 6 above)
Comment (vadmeste) [reply cmd/gateway-main.go:192]: > Additionally not sure why gateway is not failing to return error on port already in use.

We don't have two codes that are trying to allocate a port, but actually, the gateway keeps callting itself infinitely.



> Here valid value format of endpointAddr is "",

empty endpoint addr is not valid anymore. We don't need this case. I updated the PR.



> If the PR scope is only to last point only, I am not sure how critical to fix that case.

It is little annoying to not address this use case because:
- the old shown error is non-understandable to our users
`2017/05/09 10:53:09 http: Accept error: accept tcp [::]:9000: accept4: too many open files; retrying in 5ms`
- this use case allocates all available resources which could have bad effect on the system.

**Review by krishnasrinivas — APPROVED** [review]

**Comment by harshavardhana** [comment]
@balamurugana your final take on this?

**Comment by harshavardhana** [comment]
@balamurugana what is the final take on this?

**Review by balamurugana — APPROVED** [review]
As I have opened an issue https://github.com/minio/minio/issues/4355 to address proper validation of command line arguments, lets take this PR as interim solution.
