### PR TITLE
fix: claim based oidc for official aws libraries

### LINKED ISSUE #21421: Impossible to obtain claim-based OIDC STS credentials with official AWS libraries
I have a Minio cluster set up with claim-based OIDC login (where the policy names come from a JWT claim rather than being configured against a `RoleArn`).  In order to obtain temporary credentials for these logins I must call the Minio STS `AssumeRoleWithWebIdentity` API _without_ a `RoleArn` parameter.  This is fine using hand-rolled HTTP calls or Minio's own client libraries, but does not work with official AWS libraries such as `boto3` (Python) or the `aws` command line client.

In the official AWS version of the STS API, `RoleArn` is a _required_ parameter and the AWS libraries raise an error if you attempt to `AssumeRoleWithWebIdentity` with a missing or blank `RoleArn` and `RoleSessionName`.  This incompatibility makes it impossible to use claim-based web identity tokens with minio:

- the Minio STS API request _must not_ include a `RoleArn` parameter
- the AWS client libraries insist that any STS request _must_ include a `RoleArn`

## Expected Behavior
Given a Minio server configured for claim-based OIDC authorization, I would like to be able to configure the following in `~/.aws/config`:

```
[default]
region = us-east-1
services = minio
web_identity_token_file = /path/to/web-identity-token

[services minio]
s3 = 
  endpoint_url = https://minio.example.com:9000
sts =
  endpoint_url = https://minio.example.com:9000
```

and have the `aws` command line tool or `boto3` python library automatically obtain and use temporary credentials using the specified web identity token and renew them behind the scenes when they expire.

## Current Behavior
The `aws` cli and `boto3`/`botocore` libraries complain about the above configuration, because with AWS STS the role ARN is compulsory:

```
The provided profile or the current environment is configured to assume role with web identity but has no role ARN configured. Ensure that the profile has the role_arnconfiguration set or the AWS_ROLE_ARN env var is set.
```

I can set up a _role policy based_ OIDC configuration in minio and add its `role_arn = ...` to the configuration in order to use the role policy, but the only way to do claim-based OIDC in Minio is to omit the role ARN entirely, which is not allowed.

## Possible Solution
The simplest fix would be for Minio to support a "dummy" role ARN parameter value and have that treated as equivalent to the current behaviour when the parameter is omitted, e.g.

https://github.com/minio/minio/blob/de234b888c26cc191f3062a625af82640c966795/cmd/sts-handlers.go#L417-L419

after line 418 insert

```go
	if roleArnStr == "arn:minio:iam:::role/dummy-internal" {
		roleArnStr = ""
	}
```

to treat a `RoleArn` value of `arn:minio:iam:::role/dummy-internal` as equivalent to no `RoleArn` at all.  The `~/.aws/config` file would then list this dummy ARN:

```
[default]
region = us-east-1
services = minio
web_identity_token_file = /path/to/web-identity-token
role_arn = arn:minio:iam:::role/dummy-internal
role_session_name = oidc

[services minio]
s3 = 
  endpoint_url = https://minio.example.com:9000
sts =
  endpoint_url = https://minio.example.com:9000
```

With this patch in place, `aws s3 ls some-bucket` works correctly, obtaining a temporary credential from Minio STS using the web identity token from the configured file and using that credential to list the bucket.

## Context
I chose this particular ARN as an example because it is the string representation of the actual `openid.DummyRoleARN` internal placeholder, but an extension of this idea could be to allow multiple claim-based OIDC providers, distinguished using dummy ARNs like `arn:minio:iam:::role/claim/{oidc-config-id}`.

## Your Environment

* Version used (`minio --version`): affects all versions up to and including the latest main - fix tested by building from source as at commit de234b888c26cc191f3062a625af82640c966795
* Server setup and configuration: any
* Operating System and version (`uname -a`): tested on Mac OS Sequoia ARM64, but again, this is not platform specific

### PR DESCRIPTION
**Pull request by 0xMALVEE**
## Community Contribution License
All community contributions in this pull request are licensed to the project maintainers
under the terms of the [Apache 2 license](https://www.apache.org/licenses/LICENSE-2.0). 
By creating this pull request I represent that I have the right to license the 
contributions to the project maintainers under the Apache 2 license.

## Description
closes: https://github.com/minio/minio/issues/21421

## Motivation and Context
Impossible to obtain claim-based OIDC STS credentials with official AWS libraries

## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Optimization (provides speedup with no functional changes)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [ ] Fixes a regression (If yes, please add `commit-id` or `PR #` here)
- [ ] Unit tests added/updated
- [ ] Internal documentation updated
- [ ] Create a documentation update request [here](https://github.com/minio/docs/issues/new?label=doc-change,title=Doc+Updated+Needed+For+PR+github.com%2fminio%2fminio%2fpull%2fNNNNN)

### CODE REVIEW

**Review by zveinn — APPROVED** [review]

**Review by harshavardhana — APPROVED** [review]

**Comment by harshavardhana** [comment]
@0xMALVEE can you send this PR to miniohq/eos as well?

**Comment by 0xMALVEE** [comment]
> @0xMALVEE can you send this PR to miniohq/eos as well?

sure

File: cmd/sts-handlers.go [hunk 1]
```diff
@@ -414,9 +414,13 @@ func (sts *stsAPIHandlers) AssumeRoleWithSSO(w http.ResponseWriter, r *http.Requ
...
 	// Currently, we do not support multiple claim based IDPs, as there is no
 	// defined parameter to disambiguate the intended IDP in this STS request.
+	//
+	// Skip RoleArn existence check when policy mapping is based on a JWT claim.
+	// This is required to support clients (like the AWS CLI or SDKs) that enforce providing a RoleArn,
+	// even though it's not used in claim-based identity mode.
 	roleArn := openid.DummyRoleARN
 	roleArnStr := r.Form.Get(stsRoleArn)
-	if roleArnStr != "" {
+	if roleArnStr != "" && strings.TrimSpace(iamPolicyClaimNameOpenID()) == "" {
```
Comment (ianroberts) [inline cmd/sts-handlers.go:423]: I don't think this logic will work when you have a mixture of claim-based and policy-based OIDC providers registered in the same minio. If there is _any_ claim-based provider configured then it’ll ignore the roleArn completely and treat _all_ AssumeRoleWithWebIdentity signins as claim based.

The logic probably needs to be more like

- if the supplied role ARN is one that is registered to a role policy, then use that
- if the role ARN is not one that is registered, but there is a claim based provider available, then try that
- if there’s no claim based provider, then error out

I guess there's a theoretical risk here of a typo in the role ARN leading to silently authorizing with the wrong policies rather than returning an error message, but only if the claim-based provider is the same issuer and client ID as the desired policy-based one (otherwise the JWT signature wouldn't validate).

(sorry I didn’t spot this before the merge, I only became aware of the PR when I got the email saying it had closed my issue)

Comment (klauspost) [reply cmd/sts-handlers.go:423]: @0xMALVEE PTAL

Comment (0xMALVEE) [reply cmd/sts-handlers.go:423]: checking on this

Comment (ianroberts) [reply cmd/sts-handlers.go:423]: @0xMALVEE I've suggested a possible fix in #21512

Comment (ianroberts) [reply cmd/sts-handlers.go:423]: The alternative would be my original suggestion in #21421 of a specific, documented `RoleARN` value that is treated as an alias for the claim-based provider, and then typo-ed `RoleARN` values would return the real "invalid parameter value" error message rather than claiming it's a problem validating the signature.
