### PR TITLE
Safely use unsafe.Pointer to avoid crashes on ARM

### LINKED ISSUE #8005: ARM64 : Minio server crashes randomly
Minio server is terminating randomly on ARM64 platform. Built the latest code on ARM64 platform and used for testing.The deployment type is "distributed mode". 
In a week testing on 6 nodes, 3 servers crashed. 
The load was moderate when these crashes happened.

Log messages ::
-------------------------------------------------------------------------------------------
goroutine 338370336 [IO wait]:
runtime.gopark(0x1821768, 0xfffe25850a98, 0x4001841b02, 0x5)
       /usr/local/go/src/runtime/proc.go:301 +0xf0 fp=0x40042fc9c0 sp=0x40042fc9a0 pc=0x43cf50
runtime.netpollblock(0xfffe25850a70, 0x72, 0x409266a000)
       /usr/local/go/src/runtime/netpoll.go:389 +0xa4 fp=0x40042fca00 sp=0x40042fc9c0 pc=0x4385f4
internal/poll.runtime_pollWait(0xfffe25850a70, 0x72, 0xffffffffffffffff)
       /usr/local/go/src/runtime/netpoll.go:182 +0x48 fp=0x40042fca30 sp=0x40042fca00 pc=0x437b48
internal/poll.(*pollDesc).wait(0x408b030818, 0x72, 0x1000, 0x1000, 0xffffffffffffffff)
       /usr/local/go/src/internal/poll/fd_poll_runtime.go:87 +0xa0 fp=0x40042fca60 sp=0x40042fca30 pc=0x493fc0
internal/poll.(*pollDesc).waitRead(...)
       /usr/local/go/src/internal/poll/fd_poll_runtime.go:92
internal/poll.(*FD).Read(0x408b030800, 0x409266a000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
       /usr/local/go/src/internal/poll/fd_unix.go:169 +0x170 fp=0x40042fcac0 sp=0x40042fca60 pc=0x494e40
net.(*netFD).Read(0x408b030800, 0x409266a000, 0x1000, 0x1000, 0x40042fcb78, 0x413008, 0x40042fcb60)
       /usr/local/go/src/net/fd_unix.go:202 +0x44 fp=0x40042fcb20 sp=0x40042fcac0 pc=0x598c14
net.(*conn).Read(0x4031f50158, 0x409266a000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
       /usr/local/go/src/net/net.go:177 +0x5c fp=0x40042fcb80 sp=0x40042fcb20 pc=0x5ab42c
net/http.(*persistConn).Read(0x408dc807e0, 0x409266a000, 0x1000, 0x1000, 0x40042fcc68, 0x6c2f30, 0x405fa8c840)
       /usr/local/go/src/net/http/transport.go:1524 +0x60 fp=0x40042fcc00 sp=0x40042fcb80 pc=0x6c1da0
bufio.(*Reader).fill(0x4004105a40)
       /usr/local/go/src/bufio/bufio.go:100 +0x100 fp=0x40042fcc50 sp=0x40042fcc00 pc=0x4b0000
bufio.(*Reader).Peek(0x4004105a40, 0x1, 0x0, 0x0, 0x1, 0x400d6c5600, 0x0)
       /usr/local/go/src/bufio/bufio.go:138 +0x40 fp=0x40042fcc70 sp=0x40042fcc50 pc=0x4b0180
net/http.(*persistConn).readLoop(0x408dc807e0)
       /usr/local/go/src/net/http/transport.go:1677 +0x16c fp=0x40042fcfd0 sp=0x40042fcc70 pc=0x6c282c
runtime.goexit()
       /usr/local/go/src/runtime/asm_arm64.s:1128 +0x4 fp=0x40042fcfd0 sp=0x40042fcfd0 pc=0x46aa74
created by net/http.(*Transport).dialConn
       /usr/local/go/src/net/http/transport

## Expected Behavior
Minio server shouldn't terminate.

## Current Behavior
Minio server terminates.

## Your Environment

* Version used (`minio version`):
Minio (built from source on ARM64 platform)
Version: DEVELOPMENT.GOGET
Release-Tag: DEVELOPMENT.GOGET
Commit-ID: DEVELOPMENT.GOGET

* Operating System and version (`uname -a`):
aarch64 aarch64 aarch64 GNU/Linux

### PR DESCRIPTION
**Pull request by harshavardhana**
## Description
Safely use unsafe.Pointer to avoid crashes on ARM

## Motivation and Context
Refactor the Dirent parsing code such that when we
calculate offsets are correct based on the platform
This PR fixes a silent potential crash on ARM
architecture.

Fixes #8005 

## How to test this PR?
You need access to ARM64 hardware as mentioned in issue #8005 

## Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [ ] Fixes a regression (If yes, please add `commit-id` or `PR #` here)
- [ ] Documentation needed
- [x] Unit tests needed
- [ ] Functional tests needed (If yes, add [mint](https://github.com/minio/mint) PR # here: )

### CODE REVIEW

**Comment by minio-ops** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-xl.sh | :heavy_check_mark: |
| mint-compression-fs.sh | :heavy_check_mark: |
| mint-worm.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-compression-xl.sh | :x: [more...](#fb3fe038-f31d-4ac0-a6d9-b39995af0bef) |
| mint-large-bucket.sh | :x: [more...](#82713b0f-97fd-4265-84aa-bdedddbd8f36) |
| mint-compression-dist-xl.sh | :x: [more...](#e0fb35bb-ac55-475e-9b2f-e4ed339b9925) |
| mint-fs.sh | :x: [more...](#16e65233-22e3-456d-a4ad-efc918fb5013) |
| mint-dist-xl.sh | :x: [more...](#576103c2-4b3d-47ec-af79-e1dfdcd9c10a) |
<a name="16e65233-22e3-456d-a4ad-efc918fb5013"></a>
### 8027-db7f486/mint-fs.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.57:31369
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp afec2b6ac8b9:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... FAILED in 12 seconds
{
  "alert": "",
  "args": {
    "bucketName": "aws-sdk-go-test-zje4humqluve3u",
    "expiry": 60000000000,
    "objectName": "presignedTest"
  },
  "duration": 12515,
  "error": "RequestError: send request failed\ncaused by: Put http://72.28.97.57:31369/aws-sdk-go-test-zje4humqluve3u: dial tcp 72.28.97.57:31369: connect: no route to host",
  "function": "PresignedPut",
  "message": "AWS SDK Go CreateBucket Failed",
  "name": "aws-sdk-go",
  "status": "FAIL"
}

Executed 0 out of 14 tests successfully.
```
<a name="e0fb35bb-ac55-475e-9b2f-e4ed339b9925"></a>
### 8027-db7f486/mint-compression-dist-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.60:30201
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp ebb3455bf991:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 1 seconds
(2/14) Running aws-sdk-java tests ... done in 1 seconds
(3/14) Running aws-sdk-php tests ... done in 42 seconds
(4/14) Running aws-sdk-ruby tests ... done in 3 seconds
(5/14) Running awscli tests ... done in 1 minutes and 6 seconds
(6/14) Running healthcheck tests ... done in 0 seconds
(7/14) Running mc tests ... done in 55 seconds
(8/14) Running minio-dotnet tests ... done in 1 minutes and 11 seconds
(9/14) Running minio-go tests ... FAILED in 6 minutes and 58 seconds
{
  "args": {
    "destination": {},
    "sourceList": "source array of 10,001 elements"
  },
  "duration": 408681,
  "error": "Delete http://72.28.97.60:30201/minio-go-test-cz5griykt61kog1r/: dial tcp 72.28.97.60:30201: connect: no route to host",
  "function": "ComposeObject(destination, sourceList)",
  "message": "Cleanup failed",
  "name": "minio-go: testComposeObjectErrorCasesWrapper",
  "status": "FAIL"
}

Executed 8 out of 14 tests successfully.
```
<a name="fb3fe038-f31d-4ac0-a6d9-b39995af0bef"></a>
### 8027-db7f486/mint-compression-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.60:30451
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 402199769af1:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 0 seconds
(2/14) Running aws-sdk-java tests ... done in 1 seconds
(3/14) Running aws-sdk-php tests ... done in 41 seconds
(4/14) Running aws-sdk-ruby tests ... done in 2 seconds
(5/14) Running awscli tests ... done in 1 minutes and 1 seconds
(6/14) Running healthcheck tests ... done in 0 seconds
(7/14) Running mc tests ... done in 30 seconds
(8/14) Running minio-dotnet tests ... done in 36 seconds
(9/14) Running minio-go tests ... done in 33 seconds
(10/14) Running minio-java tests ... done in 23 seconds
(11/14) Running minio-js tests ... FAILED in 2 minutes and 35 seconds
{
  "name": "minio-js",
  "function": "\"after all\" hook in \"functional tests\"",
  "duration": 1626,
  "status": "FAIL",
  "error": "Error: connect EHOSTUNREACH 72.28.97.60:30451 at Object.exports._errnoException (util.js:1020:11) at exports._exceptionWithHostPort (util.js:1043:20) at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1099:14)"
}

Executed 10 out of 14 tests successfully.
```
<a name="576103c2-4b3d-47ec-af79-e1dfdcd9c10a"></a>
### 8027-db7f486/mint-dist-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.54:32361
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 242147e76ecd:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 0 seconds
(2/14) Running aws-sdk-java tests ... done in 1 seconds
(3/14) Running aws-sdk-php tests ... done in 44 seconds
(4/14) Running aws-sdk-ruby tests ... done in 4 seconds
(5/14) Running awscli tests ... FAILED in 1 minutes and 57 seconds
{"name": "awscli", "duration": 66524, "function": "aws --endpoint-url http://72.28.97.54:32361 s3 sync /mint/data s3://awscli-mint-test-bucket-9082/\n", "status": "FAIL", "error": "Completed 256.0 KiB/233.2 MiB (4.6 MiB/s) with 15 file(s) remaining
Completed 512.0 KiB/233.2 MiB (8.7 MiB/s) with 15 file(s) remaining
upload: ../../../data/datafile-0-b to s3://awscli-mint-test-bucket-9082/datafile-0-bCompleted 512.0 KiB/233.2 MiB (8.7 MiB/s) with 14 file(s) remaining
Completed 768.0 KiB/233.2 MiB (9.8 MiB/s) with 14 file(s) remaining
Completed 1.0 MiB/233.2 MiB (11.0 MiB/s) with 14 file(s) remaining 
Completed 1.0 MiB/233.2 MiB (7.9 MiB/s) with 14 file(s) remaining  
upload: ../../../data/datafile-10-kB to s3://awscli-mint-test-bucket-9082/datafile-10-kBCompleted 1.0 MiB/233.2 MiB (7.9 MiB/s) with 13 file(s) remaining
Completed 1.0 MiB/233.2 MiB (7.8 MiB/s) with 13 file(s) remaining
Completed 1.3 MiB/233.2 MiB (9.7 MiB/s) with 13 file(s) remaining
Completed 1.3 MiB/233.2 MiB (9.6 MiB/s) with 13 file(s) remaining
upload: ../../../data/datafile-1-b to s3://awscli-mint-test-bucket-9082/datafile-1-bCompleted 1.3 MiB/233.2 MiB (9.6 MiB/s) with 12 file(s) remaining
upload: ../../../data/datafile-1-kB to s3://awscli-mint-test-bucket-9082/datafile-1-kBCompleted 1.3 MiB/233.2 MiB (9.6 MiB/s) with 11 file(s) remaining
Completed 1.5 MiB/233.2 MiB (11.4 MiB/s) with 11 file(s) remaining
Completed 1.6 MiB/233.2 MiB (10.4 MiB/s) with 11 file(s) remaining
upload: ../../../data/datafile-100-kB to s3://awscli-mint-test-bucket-9082/datafile-100-kBCompleted 1.6 MiB/233.2 MiB (10.4 MiB/s) with 10 file(s) remaining
Completed 1.9 MiB/233.2 MiB (11.1 MiB/s) with 10 file(s) remaining
Completed 2.1 MiB/233.2 MiB (12.4 MiB/s) with 10 file(s) remaining
Completed 2.1 MiB/233.2 MiB (11.9 MiB/s) with 10 file(s) remaining
upload: ../../../data/datafile-33-kB to s3://awscli-mint-test-bucket-9082/datafile-33-kBCompleted 2.1 MiB/233.2 MiB (11.9 MiB/s) with 9 file(s) remaining
Completed 2.4 MiB/233.2 MiB (13.1 MiB/s) with 9 file(s) remaining
Completed 2.6 MiB/233.2 MiB (13.5 MiB/s) with 9 file(s) remaining
Completed 2.9 MiB/233.2 MiB (14.5 MiB/s) with 9 file(s) remaining
Completed 3.1 MiB/233.2 MiB (15.6 MiB/s) with 9 file(s) remaining
Completed 3.4 MiB/233.2 MiB (16.7 MiB/s) with 9 file(s) remaining
Completed 3.6 MiB/233.2 MiB (17.5 MiB/s) with 9 file(s) remaining
Completed 3.9 MiB/233.2 MiB (17.8 MiB/s) with 9 file(s) remaining
Completed 4.1 MiB/233.2 MiB (18.8 MiB/s) with 9 file(s) remaining
Completed 4.4 MiB/233.2 MiB (19.1 MiB/s) with 9 file(s) remaining
Completed 4.6 MiB/233.2 MiB (20.0 MiB/s) with 9 file(s) remaining
Completed 4.9 MiB/233.2 MiB (20.4 MiB/s) with 9 file(s) remaining
Completed 5.1 MiB/233.2 MiB (21.4 MiB/s) with 9 file(s) remaining
Completed 5.4 MiB/233.2 MiB (21.1 MiB/s) with 9 file(s) remaining
Completed 5.6 MiB/233.2 MiB (21.9 MiB/s) with 9 file(s) remaining
Completed 5.9 MiB/233.2 MiB (22.7 MiB/s) with 9 file(s) remaining
Completed 6.1 MiB/233.2 MiB (23.3 MiB/s) with 9 file(s) remaining
Completed 6.4 MiB/233.2 MiB (24.2 MiB/s) with 9 file(s) remaining
Completed 6.6 MiB/233.2 MiB (24.2 MiB/s) with 9 file(s) remaining
Completed 6.9 MiB/233.2 MiB (25.0 MiB/s) with 9 file(s) remaining
Completed 7.1 MiB/233.2 MiB (25.6 MiB/s) with 9 file(s) remaining
Completed 7.4 MiB/233.2 MiB (26.5 MiB/s) with 9 file(s) remaining
Completed 7.6 MiB/233.2 MiB (27.1 MiB/s) with 9 file(s) remaining
upload: ../../../data/datafile-1-MB to s3://awscli-mint-test-bucket-9082/datafile-1-MBCompleted 7.6 MiB/233.2 MiB (27.1 MiB/s) with 8 file(s) remaining
Completed 7.9 MiB/233.2 MiB (27.4 MiB/s) with 8 file(s) remaining
Completed 8.1 MiB/233.2 MiB (27.6 MiB/s) with 8 file(s) remaining
Completed 8.4 MiB/233.2 MiB (28.1 MiB/s) with 8 file(s) remaining
Completed 8.6 MiB/233.2 MiB (28.9 MiB/s) with 8 file(s) remaining
Completed 8.9 MiB/233.2 MiB (29.4 MiB/s) with 8 file(s) remaining
Completed 9.1 MiB/233.2 MiB (30.0 MiB/s) with 8 file(s) remaining
Completed 9.4 MiB/233.2 MiB (30.4 MiB/s) with 8 file(s) remaining
Completed 9.6 MiB/233.2 MiB (30.5 MiB/s) with 8 file(s) remaining
Completed 9.7 MiB/233.2 MiB (30.3 MiB/s) with 8 file(s) remaining
upload: ../../../data/datafile-1.03-MB to s3://awscli-mint-test-bucket-9082/datafile-1.03-MBCompleted 9.7 MiB/233.2 MiB (30.3 MiB/s) with 7 file(s) remaining
Completed 9.9 MiB/233.2 MiB (31.0 MiB/s) with 7 file(s) remaining
Completed 10.2 MiB/233.2 MiB (31.7 MiB/s) with 7 file(s) remaining
Completed 10.4 MiB/233.2 MiB (32.3 MiB/s) with 7 file(s) remaining
Completed 10.7 MiB/233.2 MiB (32.2 MiB/s) with 7 file(s) remaining
Completed 10.9 MiB/233.2 MiB (32.4 MiB/s) with 7 file(s) remaining
Completed 11.2 MiB/233.2 MiB (32.7 MiB/s) with 7 file(s) remaining
Completed 11.4 MiB/233.2 MiB (33.2 MiB/s) with 7 file(s) remaining
Completed 11.7 MiB/233.2 MiB (33.2 MiB/s) with 7 file(s) remaining
Completed 11.9 MiB/233.2 MiB (33.8 MiB/s) with 7 file(s) remaining
Completed 12.2 MiB/233.2 MiB (34.0 MiB/s) with 7 file(s) remaining
Completed 12.4 MiB/233.2 MiB (34.2 MiB/s) with 7 file(s) remaining
Completed 12.7 MiB/233.2 MiB (34.3 MiB/s) with 7 file(s) remaining
Completed 12.9 MiB/233.2 MiB (34.3 MiB/s) with 7 file(s) remaining
Completed 13.2 MiB/233.2 MiB (34.8 MiB/s) with 7 file(s) remaining
Completed 13.4 MiB/233.2 MiB (35.4 MiB/s) with 7 file(s) remaining
Completed 13.7 MiB/233.2 MiB (36.0 MiB/s) with 7 file(s) remaining
Completed 13.9 MiB/233.2 MiB (36.5 MiB/s) with 7 file(s) remaining
Completed 14.2 MiB/233.2 MiB (36.9 MiB/s) with 7 file(s) remaining
Completed 14.4 MiB/233.2 MiB (37.4 MiB/s) with 7 file(s) remaining
Completed 14.7 MiB/233.2 MiB (37.1 MiB/s) with 7 file(s) remaining
Completed 14.9 MiB/233.2 MiB (37.6 MiB/s) with 7 file(s) remaining
Completed 15.2 MiB/233.2 MiB (38.2 MiB/s) with 7 file(s) remaining
Completed 15.4 MiB/233.2 MiB (38.5 MiB/s) with 7 file(s) remaining
Completed 15.7 MiB/233.2 MiB (38.9 MiB/s) with 7 file(s) remaining
Completed 15.9 MiB/233.2 MiB (39.3 MiB/s) with 7 file(s) remaining
Completed 16.2 MiB/233.2 MiB (39.3 MiB/s) with 7 file(s) remaining
Completed 16.4 MiB/233.2 MiB (39.7 MiB/s) with 7 file(s) remaining
Completed 16.7 MiB/233.2 MiB (40.1 MiB/s) with 7 file(s) remaining
Completed 16.9 MiB/233.2 MiB (40.6 MiB/s) with 7 file(s) remaining
Completed 17.2 MiB/233.2 MiB (41.1 MiB/s) with 7 file(s) remaining
Completed 17.4 MiB/233.2 MiB (41.4 MiB/s) with 7 file(s) remaining
Completed 17.7 MiB/233.2 MiB (41.7 MiB/s) with 7 file(s) remaining
Completed 17.9 MiB/233.2 MiB (42.0 MiB/s) with 7 file(s) remaining
Completed 18.2 MiB/233.2 MiB (42.4 MiB/s) with 7 file(s) remaining
Completed 18.4 MiB/233.2 MiB (42.7 MiB/s) with 7 file(s) remaining
Completed 18.7 MiB/233.2 MiB (43.3 MiB/s) with 7 file(s) remaining
Completed 18.9 MiB/233.2 MiB (43.3 MiB/s) with 7 file(s) remaining
Completed 19.2 MiB/233.2 MiB (43.5 MiB/s) with 7 file(s) remaining
Completed 19.4 MiB/233.2 MiB (44.0 MiB/s) with 7 file(s) remaining
Completed 19.7 MiB/233.2 MiB (43.8 MiB/s) with 7 file(s) remaining
Completed 19.9 MiB/233.2 MiB (44.3 MiB/s) with 7 file(s) remaining
Completed 20.2 MiB/233.2 MiB (44.7 MiB/s) with 7 file(s) remaining
Completed 20.4 MiB/233.2 MiB (44.8 MiB/s) with 7 file(s) remaining
Completed 20.7 MiB/233.2 MiB (44.9 MiB/s) with 7 file(s) remaining
Completed 20.9 MiB/233.2 MiB (45.4 MiB/s) with 7 file(s) remaining
Completed 21.2 MiB/233.2 MiB (45.4 MiB/s) with 7 file(s) remaining
Completed 21.4 MiB/233.2 MiB (45.8 MiB/s) with 7 file(s) remaining
Completed 21.7 MiB/233.2 MiB (46.1 MiB/s) with 7 file(s) remaining
Completed 21.9 MiB/233.2 MiB (46.1 MiB/s) with 7 file(s) remaining
Completed 22.2 MiB/233.2 MiB (46.4 MiB/s) with 7 file(s) remaining
Completed 22.4 MiB/233.2 MiB (46.7 MiB/s) with 7 file(s) remaining
Completed 22.7 MiB/233.2 MiB (46.9 MiB/s) with 7 file(s) remaining
Completed 22.9 MiB/233.2 MiB (47.3 MiB/s) with 7 file(s) remaining
Completed 23.2 MiB/233.2 MiB (47.5 MiB/s) with 7 file(s) remaining
Completed 23.4 MiB/233.2 MiB (47.4 MiB/s) with 7 file(s) remaining
Completed 23.7 MiB/233.2 MiB (47.8 MiB/s) with 7 file(s) remaining
Completed 23.9 MiB/233.2 MiB (47.5 MiB/s) with 7 file(s) remaining
Completed 24.2 MiB/233.2 MiB (47.5 MiB/s) with 7 file(s) remaining
Completed 24.4 MiB/233.2 MiB (47.6 MiB/s) with 7 file(s) remaining
Completed 24.7 MiB/233.2 MiB (47.4 MiB/s) with 7 file(s) remaining
Completed 24.9 MiB/233.2 MiB (47.5 MiB/s) with 7 file(s) remaining
Completed 25.2 MiB/233.2 MiB (47.9 MiB/s) with 7 file(s) remaining
Completed 25.4 MiB/233.2 MiB (48.2 MiB/s) with 7 file(s) remaining
Completed 25.7 MiB/233.2 MiB (48.6 MiB/s) with 7 file(s) remaining
Completed 25.9 MiB/233.2 MiB (48.3 MiB/s) with 7 file(s) remaining
Completed 26.2 MiB/233.2 MiB (48.3 MiB/s) with 7 file(s) remaining
Completed 26.4 MiB/233.2 MiB (48.7 MiB/s) with 7 file(s) remaining
Completed 26.7 MiB/233.2 MiB (49.1 MiB/s) with 7 file(s) remaining
Completed 26.9 MiB/233.2 MiB (48.8 MiB/s) with 7 file(s) remaining
Completed 27.2 MiB/233.2 MiB (48.9 MiB/s) with 7 file(s) remaining
Completed 27.4 MiB/233.2 MiB (49.3 MiB/s) with 7 file(s) remaining
Completed 27.7 MiB/233.2 MiB (49.6 MiB/s) with 7 file(s) remaining
Completed 27.9 MiB/233.2 MiB (49.2 MiB/s) with 7 file(s) remaining
Completed 28.2 MiB/233.2 MiB (49.2 MiB/s) with 7 file(s) remaining
Completed 28.4 MiB/233.2 MiB (49.4 MiB/s) with 7 file(s) remaining
Completed 28.7 MiB/233.2 MiB (48.6 MiB/s) with 7 file(s) remaining
Completed 28.9 MiB/233.2 MiB (48.9 MiB/s) with 7 file(s) remaining
Completed 29.2 MiB/233.2 MiB (49.4 MiB/s) with 7 file(s) remaining
Completed 29.4 MiB/233.2 MiB (49.4 MiB/s) with 7 file(s) remaining
Completed 29.7 MiB/233.2 MiB (49.7 MiB/s) with 7 file(s) remaining
Completed 29.9 MiB/233.2 MiB (48.8 MiB/s) with 7 file(s) remaining
Completed 30.2 MiB/233.2 MiB (48.2 MiB/s) with 7 file(s) remaining
Completed 30.4 MiB/233.2 MiB (48.5 MiB/s) with 7 file(s) remaining
Completed 30.7 MiB/233.2 MiB (48.5 MiB/s) with 7 file(s) remaining
Completed 30.9 MiB/233.2 MiB (48.7 MiB/s) with 7 file(s) remaining
Completed 31.2 MiB/233.2 MiB (48.0 MiB/s) with 7 file(s) remaining
Completed 31.4 MiB/233.2 MiB (48.4 MiB/s) with 7 file(s) remaining
Completed 31.7 MiB/233.2 MiB (48.7 MiB/s) with 7 file(s) remaining
Completed 31.9 MiB/233.2 MiB (48.8 MiB/s) with 7 file(s) remaining
Completed 32.2 MiB/233.2 MiB (47.5 MiB/s) with 7 file(s) remaining
Completed 32.4 MiB/233.2 MiB (47.8 MiB/s) with 7 file(s) remaining
Completed 32.7 MiB/233.2 MiB (48.0 MiB/s) with 7 file(s) remaining
Completed 32.9 MiB/233.2 MiB (48.1 MiB/s) with 7 file(s) remaining
Completed 33.2 MiB/233.2 MiB (47.6 MiB/s) with 7 file(s) remaining
Completed 33.4 MiB/233.2 MiB (47.9 MiB/s) with 7 file(s) remaining
Completed 33.7 MiB/233.2 MiB (47.8 MiB/s) with 7 file(s) remaining
Completed 33.9 MiB/233.2 MiB (48.0 MiB/s) with 7 file(s) remaining
Completed 34.2 MiB/233.2 MiB (47.6 MiB/s) with 7 file(s) remaining
Completed 34.4 MiB/233.2 MiB (47.8 MiB/s) with 7 file(s) remaining
Completed 34.7 MiB/233.2 MiB (47.8 MiB/s) with 7 file(s) remaining
Completed 34.9 MiB/233.2 MiB (48.0 MiB/s) with 7 file(s) remaining
upload: ../../../data/datafile-5-MB to s3://awscli-mint-test-bucket-9082/datafile-5-MBCompleted 34.9 MiB/233.2 MiB (48.0 MiB/s) with 6 file(s) remaining
Completed 35.2 MiB/233.2 MiB (47.6 MiB/s) with 6 file(s) remaining
Completed 35.4 MiB/233.2 MiB (47.8 MiB/s) with 6 file(s) remaining
Completed 35.7 MiB/233.2 MiB (47.4 MiB/s) with 6 file(s) remaining
Completed 35.9 MiB/233.2 MiB (47.5 MiB/s) with 6 file(s) remaining
Completed 36.2 MiB/233.2 MiB (47.8 MiB/s) with 6 file(s) remaining
Completed 36.4 MiB/233.2 MiB (47.8 MiB/s) with 6 file(s) remaining
Completed 36.7 MiB/233.2 MiB (47.6 MiB/s) with 6 file(s) remaining
Completed 36.9 MiB/233.2 MiB (47.9 MiB/s) with 6 file(s) remaining
Completed 37.2 MiB/233.2 MiB (48.2 MiB/s) with 6 file(s) remaining
Completed 37.4 MiB/233.2 MiB (48.0 MiB/s) with 6 file(s) remaining
Completed 37.7 MiB/233.2 MiB (47.9 MiB/s) with 6 file(s) remaining
Completed 37.9 MiB/233.2 MiB (48.0 MiB/s) with 6 file(s) remaining
Completed 37.9 MiB/233.2 MiB (47.7 MiB/s) with 6 file(s) remaining
upload: ../../../data/datafile-5243880-b to s3://awscli-mint-test-bucket-9082/datafile-5243880-bCompleted 37.9 MiB/233.2 MiB (47.7 MiB/s) with 5 file(s) remaining
Completed 38.2 MiB/233.2 MiB (48.0 MiB/s) with 5 file(s) remaining
Completed 38.4 MiB/233.2 MiB (48.2 MiB/s) with 5 file(s) remaining
Completed 38.7 MiB/233.2 MiB (48.2 MiB/s) with 5 file(s) remaining
Completed 38.9 MiB/233.2 MiB (48.3 MiB/s) with 5 file(s) remaining
Completed 39.2 MiB/233.2 MiB (47.9 MiB/s) with 5 file(s) remaining
Completed 39.4 MiB/233.2 MiB (47.8 MiB/s) with 5 file(s) remaining
Completed 39.7 MiB/233.2 MiB (47.8 MiB/s) with 5 file(s) remaining
Completed 39.9 MiB/233.2 MiB (47.9 MiB/s) with 5 file(s) remaining
Completed 40.2 MiB/233.2 MiB (48.1 MiB/s) with 5 file(s) remaining
Completed 40.4 MiB/233.2 MiB (48.0 MiB/s) with 5 file(s) remaining
Completed 40.7 MiB/233.2 MiB (48.2 MiB/s) with 5 file(s) remaining
Completed 40.9 MiB/233.2 MiB (48.2 MiB/s) with 5 file(s) remaining
Completed 41.2 MiB/233.2 MiB (48.4 MiB/s) with 5 file(s) remaining
Completed 41.4 MiB/233.2 MiB (48.2 MiB/s) with 5 file(s) remaining
Completed 41.7 MiB/233.2 MiB (48.3 MiB/s) with 5 file(s) remaining
Completed 41.9 MiB/233.2 MiB (48.1 MiB/s) with 5 file(s) remaining
Completed 42.2 MiB/233.2 MiB (48.2 MiB/s) with 5 file(s) remaining
Completed 42.4 MiB/233.2 MiB (48.4 MiB/s) with 5 file(s) remaining
Completed 42.7 MiB/233.2 MiB (48.2 MiB/s) with 5 file(s) remaining
Completed 42.9 MiB/233.2 MiB (48.5 MiB/s) with 5 file(s) remaining
Completed 43.2 MiB/233.2 MiB (48.7 MiB/s) with 5 file(s) remaining
Completed 43.4 MiB/233.2 MiB (48.3 MiB/s) with 5 file(s) remaining
Completed 43.7 MiB/233.2 MiB (48.5 MiB/s) with 5 file(s) remaining
Completed 43.9 MiB/233.2 MiB (48.0 MiB/s) with 5 file(s) remaining
Completed 44.2 MiB/233.2 MiB (48.2 MiB/s) with 5 file(s) remaining
Completed 44.4 MiB/233.2 MiB (48.1 MiB/s) with 5 file(s) remaining
Completed 44.7 MiB/233.2 MiB (48.0 MiB/s) with 5 file(s) remaining
Completed 44.9 MiB/233.2 MiB (48.2 MiB/s) with 5 file(s) remaining
Completed 45.2 MiB/233.2 MiB (48.0 MiB/s) with 5 file(s) remaining
Completed 45.4 MiB/233.2 MiB (48.1 MiB/s) with 5 file(s) remaining
Completed 45.7 MiB/233.2 MiB (48.0 MiB/s) with 5 file(s) remaining
Completed 45.9 MiB/233.2 MiB (47.8 MiB/s) with 5 file(s) remaining
Completed 46.2 MiB/233.2 MiB (48.0 MiB/s) with 5 file(s) remaining
Completed 46.4 MiB/233.2 MiB (47.8 MiB/s) with 5 file(s) remaining
Completed 46.7 MiB/233.2 MiB (47.9 MiB/s) with 5 file(s) remaining
Completed 46.9 MiB/233.2 MiB (48.1 MiB/s) with 5 file(s) remaining
Completed 47.2 MiB/233.2 MiB (48.3 MiB/s) with 5 file(s) remaining
Completed 47.4 MiB/233.2 MiB (48.4 MiB/s) with 5 file(s) remaining
Completed 47.7 MiB/233.2 MiB (48.6 MiB/s) with 5 file(s) remaining
Completed 47.9 MiB/233.2 MiB (48.2 MiB/s) with 5 file(s) remaining
Completed 48.2 MiB/233.2 MiB (48.3 MiB/s) with 5 file(s) remaining
Completed 48.4 MiB/233.2 MiB (48.5 MiB/s) with 5 file(s) remaining
Completed 48.7 MiB/233.2 MiB (48.5 MiB/s) with 5 file(s) remaining
Completed 48.9 MiB/233.2 MiB (48.4 MiB/s) with 5 file(s) remaining
Completed 49.2 MiB/233.2 MiB (48.6 MiB/s) with 5 file(s) remaining
Completed 49.4 MiB/233.2 MiB (48.6 MiB/s) with 5 file(s) remaining
Completed 49.7 MiB/233.2 MiB (48.4 MiB/s) with 5 file(s) remaining
Completed 49.9 MiB/233.2 MiB (48.6 MiB/s) with 5 file(s) remaining
Completed 50.2 MiB/233.2 MiB (48.8 MiB/s) with 5 file(s) remaining
Completed 50.4 MiB/233.2 MiB (48.5 MiB/s) with 5 file(s) remaining
Completed 50.7 MiB/233.2 MiB (48.7 MiB/s) with 5 file(s) remaining
Completed 50.9 MiB/233.2 MiB (48.5 MiB/s) with 5 file(s) remaining
Completed 51.2 MiB/233.2 MiB (48.4 MiB/s) with 5 file(s) remaining
Completed 51.4 MiB/233.2 MiB (48.7 MiB/s) with 5 file(s) remaining
Completed 51.7 MiB/233.2 MiB (48.4 MiB/s) with 5 file(s) remaining
Completed 51.9 MiB/233.2 MiB (48.6 MiB/s) with 5 file(s) remaining
Completed 52.2 MiB/233.2 MiB (48.6 MiB/s) with 5 file(s) remaining
Completed 52.4 MiB/233.2 MiB (48.3 MiB/s) with 5 file(s) remaining
Completed 52.7 MiB/233.2 MiB (48.4 MiB/s) with 5 file(s) remaining
Completed 52.9 MiB/233.2 MiB (48.6 MiB/s) with 5 file(s) remaining
Completed 53.2 MiB/233.2 MiB (48.8 MiB/s) with 5 file(s) remaining
upload: ../../../data/datafile-6-MB to s3://awscli-mint-test-bucket-9082/datafile-6-MBCompleted 53.2 MiB/233.2 MiB (48.8 MiB/s) with 4 file(s) remaining
Completed 53.4 MiB/233.2 MiB (48.1 MiB/s) with 4 file(s) remaining
Completed 53.7 MiB/233.2 MiB (48.3 MiB/s) with 4 file(s) remaining
Completed 53.9 MiB/233.2 MiB (48.4 MiB/s) with 4 file(s) remaining
Completed 54.2 MiB/233.2 MiB (48.1 MiB/s) with 4 file(s) remaining
Completed 54.4 MiB/233.2 MiB (48.3 MiB/s) with 4 file(s) remaining
Completed 54.7 MiB/233.2 MiB (48.0 MiB/s) with 4 file(s) remaining
Completed 54.9 MiB/233.2 MiB (48.2 MiB/s) with 4 file(s) remaining
Completed 55.2 MiB/233.2 MiB (48.3 MiB/s) with 4 file(s) remaining
Completed 55.4 MiB/233.2 MiB (48.2 MiB/s) with 4 file(s) remaining
Completed 55.7 MiB/233.2 MiB (48.0 MiB/s) with 4 file(s) remaining
Completed 55.9 MiB/233.2 MiB (48.1 MiB/s) with 4 file(s) remaining
Completed 56.2 MiB/233.2 MiB (48.3 MiB/s) with 4 file(s) remaining
Completed 56.4 MiB/233.2 MiB (48.4 MiB/s) with 4 file(s) remaining
Completed 56.7 MiB/233.2 MiB (48.3 MiB/s) with 4 file(s) remaining
Completed 56.9 MiB/233.2 MiB (48.4 MiB/s) with 4 file(s) remaining
Completed 57.2 MiB/233.2 MiB (48.3 MiB/s) with 4 file(s) remaining
Completed 57.4 MiB/233.2 MiB (48.5 MiB/s) with 4 file(s) remaining
Completed 57.7 MiB/233.2 MiB (48.6 MiB/s) with 4 file(s) remaining
Completed 57.9 MiB/233.2 MiB (48.4 MiB/s) with 4 file(s) remaining
Completed 58.2 MiB/233.2 MiB (48.6 MiB/s) with 4 file(s) remaining
Completed 58.4 MiB/233.2 MiB (48.1 MiB/s) with 4 file(s) remaining
Completed 58.7 MiB/233.2 MiB (48.3 MiB/s) with 4 file(s) remaining
Completed 58.9 MiB/233.2 MiB (48.4 MiB/s) with 4 file(s) remaining
Completed 59.2 MiB/233.2 MiB (48.3 MiB/s) with 4 file(s) remaining
Completed 59.4 MiB/233.2 MiB (48.4 MiB/s) with 4 file(s) remaining
Completed 59.7 MiB/233.2 MiB (48.6 MiB/s) with 4 file(s) remaining
Completed 59.9 MiB/233.2 MiB (48.6 MiB/s) with 4 file(s) remaining
Completed 60.2 MiB/233.2 MiB (48.7 MiB/s) with 4 file(s) remaining
Completed 60.4 MiB/233.2 MiB (48.6 MiB/s) with 4 file(s) remaining
Completed 60.7 MiB/233.2 MiB (48.8 MiB/s) with 4 file(s) remaining
Completed 60.9 MiB/233.2 MiB (48.9 MiB/s) with 4 file(s) remaining
Completed 61.2 MiB/233.2 MiB (49.0 MiB/s) with 4 file(s) remaining
Completed 61.4 MiB/233.2 MiB (49.0 MiB/s) with 4 file(s) remaining
Completed 61.7 MiB/233.2 MiB (49.1 MiB/s) with 4 file(s) remaining
Completed 61.9 MiB/233.2 MiB (49.0 MiB/s) with 4 file(s) remaining
Completed 62.2 MiB/233.2 MiB (49.2 MiB/s) with 4 file(s) remaining
Completed 62.4 MiB/233.2 MiB (49.3 MiB/s) with 4 file(s) remaining
Completed 62.7 MiB/233.2 MiB (49.1 MiB/s) with 4 file(s) remaining
Completed 62.9 MiB/233.2 MiB (49.3 MiB/s) with 4 file(s) remaining
Completed 63.2 MiB/233.2 MiB (49.3 MiB/s) with 4 file(s) remaining
Completed 63.4 MiB/233.2 MiB (49.4 MiB/s) with 4 file(s) remaining
Completed 63.7 MiB/233.2 MiB (49.4 MiB/s) with 4 file(s) remaining
Completed 63.9 MiB/233.2 MiB (49.5 MiB/s) with 4 file(s) remaining
Completed 64.2 MiB/233.2 MiB (49.3 MiB/s) with 4 file(s) remaining
Completed 64.4 MiB/233.2 MiB (49.5 MiB/s) with 4 file(s) remaining
Completed 64.7 MiB/233.2 MiB (49.5 MiB/s) with 4 file(s) remaining
Completed 64.9 MiB/233.2 MiB (49.6 MiB/s) with 4 file(s) remaining
Completed 65.2 MiB/233.2 MiB (49.7 MiB/s) with 4 file(s) remaining
Completed 65.4 MiB/233.2 MiB (49.4 MiB/s) with 4 file(s) remaining
Completed 65.7 MiB/233.2 MiB (49.4 MiB/s) with 4 file(s) remaining
Completed 65.9 MiB/233.2 MiB (49.6 MiB/s) with 4 file(s) remaining
Completed 66.2 MiB/233.2 MiB (49.8 MiB/s) with 4 file(s) remaining
Completed 66.4 MiB/233.2 MiB (50.0 MiB/s) with 4 file(s) remaining
Completed 66.7 MiB/233.2 MiB (49.5 MiB/s) with 4 file(s) remaining
Completed 66.9 MiB/233.2 MiB (49.6 MiB/s) with 4 file(s) remaining
Completed 67.2 MiB/233.2 MiB (49.7 MiB/s) with 4 file(s) remaining
Completed 67.4 MiB/233.2 MiB (49.4 MiB/s) with 4 file(s) remaining
Completed 67.7 MiB/233.2 MiB (49.5 MiB/s) with 4 file(s) remaining
Completed 67.9 MiB/233.2 MiB (49.5 MiB/s) with 4 file(s) remaining
Completed 68.2 MiB/233.2 MiB (49.6 MiB/s) with 4 file(s) remaining
Completed 68.4 MiB/233.2 MiB (49.5 MiB/s) with 4 file(s) remaining
Completed 68.7 MiB/233.2 MiB (49.5 MiB/s) with 4 file(s) remaining
Completed 68.9 MiB/233.2 MiB (49.6 MiB/s) with 4 file(s) remaining
Completed 69.2 MiB/233.2 MiB (49.7 MiB/s) with 4 file(s) remaining
Completed 69.4 MiB/233.2 MiB (49.5 MiB/s) with 4 file(s) remaining
Completed 69.7 MiB/233.2 MiB (49.7 MiB/s) with 4 file(s) remaining
Completed 69.9 MiB/233.2 MiB (49.7 MiB/s) with 4 file(s) remaining
Completed 70.2 MiB/233.2 MiB (49.7 MiB/s) with 4 file(s) remaining
Completed 70.4 MiB/233.2 MiB (49.6 MiB/s) with 4 file(s) remaining
Completed 70.7 MiB/233.2 MiB (49.6 MiB/s) with 4 file(s) remaining
Completed 70.9 MiB/233.2 MiB (49.5 MiB/s) with 4 file(s) remaining
Completed 71.2 MiB/233.2 MiB (49.5 MiB/s) with 4 file(s) remaining
Completed 71.4 MiB/233.2 MiB (49.3 MiB/s) with 4 file(s) remaining
Completed 71.7 MiB/233.2 MiB (49.4 MiB/s) with 4 file(s) remaining
Completed 71.9 MiB/233.2 MiB (49.3 MiB/s) with 4 file(s) remaining
Completed 72.2 MiB/233.2 MiB (49.0 MiB/s) with 4 file(s) remaining
Completed 72.4 MiB/233.2 MiB (49.1 MiB/s) with 4 file(s) remaining
Completed 72.7 MiB/233.2 MiB (49.1 MiB/s) with 4 file(s) remaining
Completed 72.9 MiB/233.2 MiB (49.0 MiB/s) with 4 file(s) remaining
Completed 73.2 MiB/233.2 MiB (49.0 MiB/s) with 4 file(s) remaining
Completed 73.4 MiB/233.2 MiB (49.0 MiB/s) with 4 file(s) remaining
Completed 73.7 MiB/233.2 MiB (48.9 MiB/s) with 4 file(s) remaining
Completed 73.9 MiB/233.2 MiB (48.9 MiB/s) with 4 file(s) remaining
Completed 74.2 MiB/233.2 MiB (49.0 MiB/s) with 4 file(s) remaining
Completed 74.4 MiB/233.2 MiB (48.9 MiB/s) with 4 file(s) remaining
Completed 74.7 MiB/233.2 MiB (48.8 MiB/s) with 4 file(s) remaining
Completed 74.9 MiB/233.2 MiB (49.0 MiB/s) with 4 file(s) remaining
Completed 75.2 MiB/233.2 MiB (49.0 MiB/s) with 4 file(s) remaining
Completed 75.4 MiB/233.2 MiB (48.9 MiB/s) with 4 file(s) remaining
Completed 75.7 MiB/233.2 MiB (49.0 MiB/s) with 4 file(s) remaining
Completed 75.9 MiB/233.2 MiB (49.1 MiB/s) with 4 file(s) remaining
Completed 76.2 MiB/233.2 MiB (48.9 MiB/s) with 4 file(s) remaining
Completed 76.4 MiB/233.2 MiB (49.0 MiB/s) with 4 file(s) remaining
Completed 76.7 MiB/233.2 MiB (49.1 MiB/s) with 4 file(s) remaining
Completed 76.9 MiB/233.2 MiB (49.0 MiB/s) with 4 file(s) remaining
Completed 77.2 MiB/233.2 MiB (49.2 MiB/s) with 4 file(s) remaining
Completed 77.4 MiB/233.2 MiB (49.3 MiB/s) with 4 file(s) remaining
Completed 77.7 MiB/233.2 MiB (49.1 MiB/s) with 4 file(s) remaining
Completed 77.9 MiB/233.2 MiB (49.2 MiB/s) with 4 file(s) remaining
Completed 78.2 MiB/233.2 MiB (49.3 MiB/s) with 4 file(s) remaining
Completed 78.4 MiB/233.2 MiB (49.1 MiB/s) with 4 file(s) remaining
Completed 78.7 MiB/233.2 MiB (49.3 MiB/s) with 4 file(s) remaining
Completed 78.9 MiB/233.2 MiB (49.4 MiB/s) with 4 file(s) remaining
Completed 79.2 MiB/233.2 MiB (49.3 MiB/s) with 4 file(s) remaining
Completed 79.4 MiB/233.2 MiB (49.3 MiB/s) with 4 file(s) remaining
Completed 79.7 MiB/233.2 MiB (49.5 MiB/s) with 4 file(s) remaining
Completed 79.9 MiB/233.2 MiB (49.4 MiB/s) with 4 file(s) remaining
Completed 80.2 MiB/233.2 MiB (49.4 MiB/s) with 4 file(s) remaining
Completed 80.4 MiB/233.2 MiB (49.6 MiB/s) with 4 file(s) remaining
Completed 80.7 MiB/233.2 MiB (49.5 MiB/s) with 4 file(s) remaining
Completed 80.9 MiB/233.2 MiB (49.4 MiB/s) with 4 file(s) remaining
Completed 81.2 MiB/233.2 MiB (49.5 MiB/s) with 4 file(s) remaining
Completed 81.4 MiB/233.2 MiB (49.6 MiB/s) with 4 file(s) remaining
Completed 81.7 MiB/233.2 MiB (49.7 MiB/s) with 4 file(s) remaining
Completed 81.9 MiB/233.2 MiB (49.7 MiB/s) with 4 file(s) remaining
Completed 82.2 MiB/233.2 MiB (49.8 MiB/s) with 4 file(s) remaining
Completed 82.4 MiB/233.2 MiB (50.0 MiB/s) with 4 file(s) remaining
Completed 82.7 MiB/233.2 MiB (50.0 MiB/s) with 4 file(s) remaining
Completed 82.9 MiB/233.2 MiB (50.0 MiB/s) with 4 file(s) remaining
Completed 83.2 MiB/233.2 MiB (50.0 MiB/s) with 4 file(s) remaining
Completed 83.4 MiB/233.2 MiB (50.1 MiB/s) with 4 file(s) remaining
Completed 83.7 MiB/233.2 MiB (50.2 MiB/s) with 4 file(s) remaining
Completed 83.9 MiB/233.2 MiB (50.2 MiB/s) with 4 file(s) remaining
Completed 84.2 MiB/233.2 MiB (50.2 MiB/s) with 4 file(s) remaining
Completed 84.4 MiB/233.2 MiB (50.3 MiB/s) with 4 file(s) remaining
Completed 84.7 MiB/233.2 MiB (50.4 MiB/s) with 4 file(s) remaining
Completed 84.9 MiB/233.2 MiB (50.5 MiB/s) with 4 file(s) remaining
Completed 85.2 MiB/233.2 MiB (50.5 MiB/s) with 4 file(s) remaining
Completed 85.4 MiB/233.2 MiB (50.4 MiB/s) with 4 file(s) remaining
upload: ../../../data/datafile-10-MB to s3://awscli-mint-test-bucket-9082/datafile-10-MBCompleted 85.4 MiB/233.2 MiB (50.4 MiB/s) with 3 file(s) remaining
Completed 85.7 MiB/233.2 MiB (50.4 MiB/s) with 3 file(s) remaining
Completed 85.9 MiB/233.2 MiB (50.5 MiB/s) with 3 file(s) remaining
Completed 86.2 MiB/233.2 MiB (50.6 MiB/s) with 3 file(s) remaining
Completed 86.4 MiB/233.2 MiB (50.7 MiB/s) with 3 file(s) remaining
Completed 86.7 MiB/233.2 MiB (50.7 MiB/s) with 3 file(s) remaining
Completed 86.9 MiB/233.2 MiB (50.6 MiB/s) with 3 file(s) remaining
Completed 87.2 MiB/233.2 MiB (50.6 MiB/s) with 3 file(s) remaining
Completed 87.4 MiB/233.2 MiB (50.6 MiB/s) with 3 file(s) remaining
Completed 87.7 MiB/233.2 MiB (50.7 MiB/s) with 3 file(s) remaining
Completed 87.9 MiB/233.2 MiB (50.6 MiB/s) with 3 file(s) remaining
Completed 88.2 MiB/233.2 MiB (50.7 MiB/s) with 3 file(s) remaining
Completed 88.4 MiB/233.2 MiB (50.7 MiB/s) with 3 file(s) remaining
Completed 88.7 MiB/233.2 MiB (50.8 MiB/s) with 3 file(s) remaining
Completed 88.9 MiB/233.2 MiB (50.8 MiB/s) with 3 file(s) remaining
Completed 89.2 MiB/233.2 MiB (50.8 MiB/s) with 3 file(s) remaining
Completed 89.4 MiB/233.2 MiB (50.9 MiB/s) with 3 file(s) remaining
Completed 89.7 MiB/233.2 MiB (50.9 MiB/s) with 3 file(s) remaining
Completed 89.9 MiB/233.2 MiB (50.8 MiB/s) with 3 file(s) remaining
Completed 90.2 MiB/233.2 MiB (51.0 MiB/s) with 3 file(s) remaining
Completed 90.4 MiB/233.2 MiB (50.9 MiB/s) with 3 file(s) remaining
Completed 90.7 MiB/233.2 MiB (50.9 MiB/s) with 3 file(s) remaining
Completed 90.9 MiB/233.2 MiB (51.0 MiB/s) with 3 file(s) remaining
Completed 91.2 MiB/233.2 MiB (51.0 MiB/s) with 3 file(s) remaining
Completed 91.4 MiB/233.2 MiB (50.9 MiB/s) with 3 file(s) remaining
Completed 91.7 MiB/233.2 MiB (51.0 MiB/s) with 3 file(s) remaining
Completed 91.9 MiB/233.2 MiB (51.1 MiB/s) with 3 file(s) remaining
Completed 92.2 MiB/233.2 MiB (51.0 MiB/s) with 3 file(s) remaining
Completed 92.4 MiB/233.2 MiB (51.1 MiB/s) with 3 file(s) remaining
Completed 92.7 MiB/233.2 MiB (51.1 MiB/s) with 3 file(s) remaining
Completed 92.9 MiB/233.2 MiB (51.2 MiB/s) with 3 file(s) remaining
Completed 93.2 MiB/233.2 MiB (51.2 MiB/s) with 3 file(s) remaining
Completed 93.4 MiB/233.2 MiB (51.1 MiB/s) with 3 file(s) remaining
Completed 93.7 MiB/233.2 MiB (51.2 MiB/s) with 3 file(s) remaining
Completed 93.9 MiB/233.2 MiB (51.3 MiB/s) with 3 file(s) remaining
Completed 94.2 MiB/233.2 MiB (51.4 MiB/s) with 3 file(s) remaining
Completed 94.4 MiB/233.2 MiB (51.3 MiB/s) with 3 file(s) remaining
Completed 94.7 MiB/233.2 MiB (51.3 MiB/s) with 3 file(s) remaining
Completed 94.9 MiB/233.2 MiB (51.4 MiB/s) with 3 file(s) remaining
Completed 95.2 MiB/233.2 MiB (51.3 MiB/s) with 3 file(s) remaining
Completed 95.4 MiB/233.2 MiB (51.4 MiB/s) with 3 file(s) remaining
Completed 95.7 MiB/233.2 MiB (51.5 MiB/s) with 3 file(s) remaining
Completed 95.9 MiB/233.2 MiB (51.5 MiB/s) with 3 file(s) remaining
Completed 96.2 MiB/233.2 MiB (51.5 MiB/s) with 3 file(s) remaining
Completed 96.4 MiB/233.2 MiB (51.6 MiB/s) with 3 file(s) remaining
Completed 96.7 MiB/233.2 MiB (51.5 MiB/s) with 3 file(s) remaining
Completed 96.9 MiB/233.2 MiB (51.5 MiB/s) with 3 file(s) remaining
Completed 97.2 MiB/233.2 MiB (51.6 MiB/s) with 3 file(s) remaining
Completed 97.4 MiB/233.2 MiB (51.7 MiB/s) with 3 file(s) remaining
Completed 97.7 MiB/233.2 MiB (51.5 MiB/s) with 3 file(s) remaining
Completed 97.9 MiB/233.2 MiB (51.6 MiB/s) with 3 file(s) remaining
Completed 98.2 MiB/233.2 MiB (51.7 MiB/s) with 3 file(s) remaining
Completed 98.4 MiB/233.2 MiB (51.8 MiB/s) with 3 file(s) remaining
Completed 98.7 MiB/233.2 MiB (51.6 MiB/s) with 3 file(s) remaining
Completed 98.9 MiB/233.2 MiB (51.6 MiB/s) with 3 file(s) remaining
Completed 99.2 MiB/233.2 MiB (51.7 MiB/s) with 3 file(s) remaining
Completed 99.4 MiB/233.2 MiB (51.8 MiB/s) with 3 file(s) remaining
Completed 99.7 MiB/233.2 MiB (51.6 MiB/s) with 3 file(s) remaining
Completed 99.9 MiB/233.2 MiB (51.6 MiB/s) with 3 file(s) remaining
Completed 100.2 MiB/233.2 MiB (51.6 MiB/s) with 3 file(s) remaining
Completed 100.4 MiB/233.2 MiB (51.6 MiB/s) with 3 file(s) remaining
Completed 100.7 MiB/233.2 MiB (51.6 MiB/s) with 3 file(s) remaining
Completed 100.9 MiB/233.2 MiB (51.5 MiB/s) with 3 file(s) remaining
Completed 101.2 MiB/233.2 MiB (51.6 MiB/s) with 3 file(s) remaining
Completed 101.4 MiB/233.2 MiB (51.7 MiB/s) with 3 file(s) remaining
Completed 101.7 MiB/233.2 MiB (51.5 MiB/s) with 3 file(s) remaining
Completed 101.9 MiB/233.2 MiB (51.6 MiB/s) with 3 file(s) remaining
Completed 102.2 MiB/233.2 MiB (51.6 MiB/s) with 3 file(s) remaining
Completed 102.4 MiB/233.2 MiB (51.6 MiB/s) with 3 file(s) remaining
Completed 102.7 MiB/233.2 MiB (51.7 MiB/s) with 3 file(s) remaining
Completed 102.9 MiB/233.2 MiB (51.6 MiB/s) with 3 file(s) remaining
Completed 103.2 MiB/233.2 MiB (51.5 MiB/s) with 3 file(s) remaining
Completed 103.4 MiB/233.2 MiB (51.5 MiB/s) with 3 file(s) remaining
Completed 103.7 MiB/233.2 MiB (51.6 MiB/s) with 3 file(s) remaining
Completed 103.9 MiB/233.2 MiB (51.7 MiB/s) with 3 file(s) remaining
Completed 104.2 MiB/233.2 MiB (51.6 MiB/s) with 3 file(s) remaining
Completed 104.4 MiB/233.2 MiB (51.7 MiB/s) with 3 file(s) remaining
Completed 104.7 MiB/233.2 MiB (51.5 MiB/s) with 3 file(s) remaining
Completed 104.9 MiB/233.2 MiB (51.6 MiB/s) with 3 file(s) remaining
Completed 105.2 MiB/233.2 MiB (51.7 MiB/s) with 3 file(s) remaining
Completed 105.4 MiB/233.2 MiB (51.7 MiB/s) with 3 file(s) remaining
Completed 105.7 MiB/233.2 MiB (51.7 MiB/s) with 3 file(s) remaining
Completed 105.9 MiB/233.2 MiB (51.6 MiB/s) with 3 file(s) remaining
Completed 106.2 MiB/233.2 MiB (51.7 MiB/s) with 3 file(s) remaining
Completed 106.4 MiB/233.2 MiB (51.8 MiB/s) with 3 file(s) remaining
Completed 106.7 MiB/233.2 MiB (51.8 MiB/s) with 3 file(s) remaining
Completed 106.9 MiB/233.2 MiB (51.7 MiB/s) with 3 file(s) remaining
Completed 107.2 MiB/233.2 MiB (51.7 MiB/s) with 3 file(s) remaining
Completed 107.4 MiB/233.2 MiB (51.8 MiB/s) with 3 file(s) remaining
Completed 107.7 MiB/233.2 MiB (51.7 MiB/s) with 3 file(s) remaining
Completed 107.9 MiB/233.2 MiB (51.7 MiB/s) with 3 file(s) remaining
Completed 108.2 MiB/233.2 MiB (51.6 MiB/s) with 3 file(s) remaining
Completed 108.4 MiB/233.2 MiB (51.5 MiB/s) with 3 file(s) remaining
Completed 108.7 MiB/233.2 MiB (51.6 MiB/s) with 3 file(s) remaining
Completed 108.9 MiB/233.2 MiB (51.3 MiB/s) with 3 file(s) remaining
Completed 109.2 MiB/233.2 MiB (51.4 MiB/s) with 3 file(s) remaining
Completed 109.4 MiB/233.2 MiB (51.5 MiB/s) with 3 file(s) remaining
Completed 109.7 MiB/233.2 MiB (51.1 MiB/s) with 3 file(s) remaining
Completed 109.9 MiB/233.2 MiB (51.2 MiB/s) with 3 file(s) remaining
Completed 110.2 MiB/233.2 MiB (51.2 MiB/s) with 3 file(s) remaining
Completed 110.4 MiB/233.2 MiB (51.1 MiB/s) with 3 file(s) remaining
Completed 110.7 MiB/233.2 MiB (51.1 MiB/s) with 3 file(s) remaining
Completed 110.9 MiB/233.2 MiB (51.1 MiB/s) with 3 file(s) remaining
Completed 111.2 MiB/233.2 MiB (51.1 MiB/s) with 3 file(s) remaining
Completed 111.4 MiB/233.2 MiB (51.2 MiB/s) with 3 file(s) remaining
Completed 111.7 MiB/233.2 MiB (51.1 MiB/s) with 3 file(s) remaining
Completed 111.9 MiB/233.2 MiB (51.2 MiB/s) with 3 file(s) remaining
Completed 112.2 MiB/233.2 MiB (51.3 MiB/s) with 3 file(s) remaining
Completed 112.4 MiB/233.2 MiB (51.2 MiB/s) with 3 file(s) remaining
Completed 112.7 MiB/233.2 MiB (51.3 MiB/s) with 3 file(s) remaining
Completed 112.9 MiB/233.2 MiB (51.3 MiB/s) with 3 file(s) remaining
Completed 113.2 MiB/233.2 MiB (51.3 MiB/s) with 3 file(s) remaining
Completed 113.4 MiB/233.2 MiB (51.3 MiB/s) with 3 file(s) remaining
Completed 113.7 MiB/233.2 MiB (51.3 MiB/s) with 3 file(s) remaining
Completed 113.9 MiB/233.2 MiB (51.3 MiB/s) with 3 file(s) remaining
Completed 114.2 MiB/233.2 MiB (51.4 MiB/s) with 3 file(s) remaining
Completed 114.4 MiB/233.2 MiB (51.3 MiB/s) with 3 file(s) remaining
Completed 114.7 MiB/233.2 MiB (51.4 MiB/s) with 3 file(s) remaining
Completed 114.9 MiB/233.2 MiB (51.3 MiB/s) with 3 file(s) remaining
Completed 115.2 MiB/233.2 MiB (51.3 MiB/s) with 3 file(s) remaining
Completed 115.4 MiB/233.2 MiB (51.3 MiB/s) with 3 file(s) remaining
Completed 115.7 MiB/233.2 MiB (51.3 MiB/s) with 3 file(s) remaining
Completed 115.9 MiB/233.2 MiB (51.2 MiB/s) with 3 file(s) remaining
Completed 116.2 MiB/233.2 MiB (51.1 MiB/s) with 3 file(s) remaining
Completed 116.4 MiB/233.2 MiB (51.0 MiB/s) with 3 file(s) remaining
Completed 116.7 MiB/233.2 MiB (50.9 MiB/s) with 3 file(s) remaining
Completed 116.9 MiB/233.2 MiB (50.9 MiB/s) with 3 file(s) remaining
Completed 117.2 MiB/233.2 MiB (50.9 MiB/s) with 3 file(s) remaining
Completed 117.4 MiB/233.2 MiB (50.9 MiB/s) with 3 file(s) remaining
Completed 117.7 MiB/233.2 MiB (51.0 MiB/s) with 3 file(s) remaining
Completed 117.9 MiB/233.2 MiB (51.0 MiB/s) with 3 file(s) remaining
Completed 118.2 MiB/233.2 MiB (51.0 MiB/s) with 3 file(s) remaining
Completed 118.4 MiB/233.2 MiB (51.0 MiB/s) with 3 file(s) remaining
Completed 118.7 MiB/233.2 MiB (51.0 MiB/s) with 3 file(s) remaining
Completed 118.9 MiB/233.2 MiB (51.0 MiB/s) with 3 file(s) remaining
Completed 119.2 MiB/233.2 MiB (51.0 MiB/s) with 3 file(s) remaining
Completed 119.4 MiB/233.2 MiB (48.3 MiB/s) with 3 file(s) remaining
Completed 119.7 MiB/233.2 MiB (48.3 MiB/s) with 3 file(s) remaining
Completed 119.9 MiB/233.2 MiB (48.4 MiB/s) with 3 file(s) remaining
Completed 120.2 MiB/233.2 MiB (48.5 MiB/s) with 3 file(s) remaining
Completed 120.4 MiB/233.2 MiB (48.5 MiB/s) with 3 file(s) remaining
Completed 120.7 MiB/233.2 MiB (48.6 MiB/s) with 3 file(s) remaining
Completed 120.9 MiB/233.2 MiB (48.7 MiB/s) with 3 file(s) remaining
Completed 121.2 MiB/233.2 MiB (48.7 MiB/s) with 3 file(s) remaining
Completed 121.4 MiB/233.2 MiB (48.8 MiB/s) with 3 file(s) remaining
Completed 121.7 MiB/233.2 MiB (48.8 MiB/s) with 3 file(s) remaining
Completed 121.9 MiB/233.2 MiB (48.9 MiB/s) with 3 file(s) remaining
Completed 122.2 MiB/233.2 MiB (48.9 MiB/s) with 3 file(s) remaining
Completed 122.4 MiB/233.2 MiB (49.0 MiB/s) with 3 file(s) remaining
Completed 122.7 MiB/233.2 MiB (49.0 MiB/s) with 3 file(s) remaining
Completed 122.9 MiB/233.2 MiB (49.1 MiB/s) with 3 file(s) remaining
Completed 123.2 MiB/233.2 MiB (49.1 MiB/s) with 3 file(s) remaining
Completed 123.4 MiB/233.2 MiB (49.2 MiB/s) with 3 file(s) remaining
Completed 123.7 MiB/233.2 MiB (49.3 MiB/s) with 3 file(s) remaining
Completed 123.9 MiB/233.2 MiB (49.3 MiB/s) with 3 file(s) remaining
Completed 124.2 MiB/233.2 MiB (49.4 MiB/s) with 3 file(s) remaining
Completed 124.4 MiB/233.2 MiB (49.4 MiB/s) with 3 file(s) remaining
Completed 124.7 MiB/233.2 MiB (49.5 MiB/s) with 3 file(s) remaining
Completed 124.9 MiB/233.2 MiB (49.5 MiB/s) with 3 file(s) remaining
Completed 125.2 MiB/233.2 MiB (49.6 MiB/s) with 3 file(s) remaining
Completed 125.4 MiB/233.2 MiB (49.6 MiB/s) with 3 file(s) remaining
Completed 125.7 MiB/233.2 MiB (49.7 MiB/s) with 3 file(s) remaining
Completed 125.9 MiB/233.2 MiB (49.8 MiB/s) with 3 file(s) remaining
Completed 126.2 MiB/233.2 MiB (49.8 MiB/s) with 3 file(s) remaining
Completed 126.4 MiB/233.2 MiB (49.9 MiB/s) with 3 file(s) remaining
Completed 126.7 MiB/233.2 MiB (49.9 MiB/s) with 3 file(s) remaining
Completed 126.9 MiB/233.2 MiB (50.0 MiB/s) with 3 file(s) remaining
Completed 127.2 MiB/233.2 MiB (50.0 MiB/s) with 3 file(s) remaining
Completed 127.4 MiB/233.2 MiB (48.2 MiB/s) with 3 file(s) remaining
Completed 127.7 MiB/233.2 MiB (48.3 MiB/s) with 3 file(s) remaining
Completed 127.9 MiB/233.2 MiB (48.3 MiB/s) with 3 file(s) remaining
Completed 128.2 MiB/233.2 MiB (48.4 MiB/s) with 3 file(s) remaining
Completed 128.4 MiB/233.2 MiB (48.4 MiB/s) with 3 file(s) remaining
Completed 128.7 MiB/233.2 MiB (48.4 MiB/s) with 3 file(s) remaining
Completed 128.9 MiB/233.2 MiB (48.5 MiB/s) with 3 file(s) remaining
Completed 129.2 MiB/233.2 MiB (48.5 MiB/s) with 3 file(s) remaining
Completed 129.4 MiB/233.2 MiB (48.5 MiB/s) with 3 file(s) remaining
Completed 129.7 MiB/233.2 MiB (48.6 MiB/s) with 3 file(s) remaining
Completed 129.9 MiB/233.2 MiB (48.6 MiB/s) with 3 file(s) remaining
Completed 130.2 MiB/233.2 MiB (48.6 MiB/s) with 3 file(s) remaining
Completed 130.4 MiB/233.2 MiB (48.7 MiB/s) with 3 file(s) remaining
Completed 130.7 MiB/233.2 MiB (48.7 MiB/s) with 3 file(s) remaining
Completed 130.9 MiB/233.2 MiB (48.8 MiB/s) with 3 file(s) remaining
Completed 131.2 MiB/233.2 MiB (48.9 MiB/s) with 3 file(s) remaining
Completed 131.4 MiB/233.2 MiB (48.9 MiB/s) with 3 file(s) remaining
Completed 131.7 MiB/233.2 MiB (49.0 MiB/s) with 3 file(s) remaining
Completed 131.9 MiB/233.2 MiB (49.0 MiB/s) with 3 file(s) remaining
Completed 132.2 MiB/233.2 MiB (49.1 MiB/s) with 3 file(s) remaining
Completed 132.4 MiB/233.2 MiB (49.1 MiB/s) with 3 file(s) remaining
Completed 132.7 MiB/233.2 MiB (49.2 MiB/s) with 3 file(s) remaining
Completed 132.9 MiB/233.2 MiB (49.2 MiB/s) with 3 file(s) remaining
Completed 133.2 MiB/233.2 MiB (49.3 MiB/s) with 3 file(s) remaining
Completed 133.4 MiB/233.2 MiB (49.3 MiB/s) with 3 file(s) remaining
Completed 133.7 MiB/233.2 MiB (49.4 MiB/s) with 3 file(s) remaining
Completed 133.9 MiB/233.2 MiB (49.4 MiB/s) with 3 file(s) remaining
Completed 134.2 MiB/233.2 MiB (49.5 MiB/s) with 3 file(s) remaining
Completed 134.4 MiB/233.2 MiB (49.5 MiB/s) with 3 file(s) remaining
Completed 134.7 MiB/233.2 MiB (49.6 MiB/s) with 3 file(s) remaining
Completed 134.9 MiB/233.2 MiB (49.6 MiB/s) with 3 file(s) remaining
Completed 135.2 MiB/233.2 MiB (49.7 MiB/s) with 3 file(s) remaining
Completed 135.4 MiB/233.2 MiB (41.7 MiB/s) with 3 file(s) remaining
Completed 135.7 MiB/233.2 MiB (41.8 MiB/s) with 3 file(s) remaining
Completed 135.9 MiB/233.2 MiB (41.7 MiB/s) with 3 file(s) remaining
Completed 136.2 MiB/233.2 MiB (41.7 MiB/s) with 3 file(s) remaining
Completed 136.4 MiB/233.2 MiB (41.8 MiB/s) with 3 file(s) remaining
Completed 136.7 MiB/233.2 MiB (41.9 MiB/s) with 3 file(s) remaining
Completed 136.9 MiB/233.2 MiB (41.9 MiB/s) with 3 file(s) remaining
Completed 137.2 MiB/233.2 MiB (42.0 MiB/s) with 3 file(s) remaining
Completed 137.4 MiB/233.2 MiB (42.0 MiB/s) with 3 file(s) remaining
Completed 137.7 MiB/233.2 MiB (42.1 MiB/s) with 3 file(s) remaining
Completed 137.9 MiB/233.2 MiB (42.1 MiB/s) with 3 file(s) remaining
Completed 138.2 MiB/233.2 MiB (42.2 MiB/s) with 3 file(s) remaining
Completed 138.4 MiB/233.2 MiB (42.2 MiB/s) with 3 file(s) remaining
Completed 138.7 MiB/233.2 MiB (42.3 MiB/s) with 3 file(s) remaining
Completed 138.9 MiB/233.2 MiB (42.3 MiB/s) with 3 file(s) remaining
Completed 139.2 MiB/233.2 MiB (42.3 MiB/s) with 3 file(s) remaining
Completed 139.4 MiB/233.2 MiB (42.4 MiB/s) with 3 file(s) remaining
Completed 139.7 MiB/233.2 MiB (42.4 MiB/s) with 3 file(s) remaining
Completed 139.9 MiB/233.2 MiB (42.5 MiB/s) with 3 file(s) remaining
Completed 140.2 MiB/233.2 MiB (42.5 MiB/s) with 3 file(s) remaining
Completed 140.4 MiB/233.2 MiB (42.6 MiB/s) with 3 file(s) remaining
Completed 140.7 MiB/233.2 MiB (42.6 MiB/s) with 3 file(s) remaining
Completed 140.9 MiB/233.2 MiB (42.7 MiB/s) with 3 file(s) remaining
Completed 141.2 MiB/233.2 MiB (42.7 MiB/s) with 3 file(s) remaining
Completed 141.4 MiB/233.2 MiB (42.7 MiB/s) with 3 file(s) remaining
Completed 141.7 MiB/233.2 MiB (42.8 MiB/s) with 3 file(s) remaining
Completed 141.9 MiB/233.2 MiB (42.8 MiB/s) with 3 file(s) remaining
Completed 142.2 MiB/233.2 MiB (42.9 MiB/s) with 3 file(s) remaining
Completed 142.4 MiB/233.2 MiB (42.9 MiB/s) with 3 file(s) remaining
Completed 142.7 MiB/233.2 MiB (43.0 MiB/s) with 3 file(s) remaining
Completed 142.9 MiB/233.2 MiB (43.0 MiB/s) with 3 file(s) remaining
Completed 143.2 MiB/233.2 MiB (43.1 MiB/s) with 3 file(s) remaining
Completed 143.4 MiB/233.2 MiB (43.1 MiB/s) with 3 file(s) remaining
Completed 143.7 MiB/233.2 MiB (43.2 MiB/s) with 3 file(s) remaining
Completed 143.9 MiB/233.2 MiB (43.2 MiB/s) with 3 file(s) remaining
Completed 144.2 MiB/233.2 MiB (42.9 MiB/s) with 3 file(s) remaining
Completed 144.4 MiB/233.2 MiB (42.8 MiB/s) with 3 file(s) remaining
Completed 144.7 MiB/233.2 MiB (41.8 MiB/s) with 3 file(s) remaining
Completed 144.9 MiB/233.2 MiB (39.6 MiB/s) with 3 file(s) remaining
Completed 145.2 MiB/233.2 MiB (39.7 MiB/s) with 3 file(s) remaining
Completed 145.4 MiB/233.2 MiB (39.7 MiB/s) with 3 file(s) remaining
Completed 145.7 MiB/233.2 MiB (39.8 MiB/s) with 3 file(s) remaining
Completed 145.9 MiB/233.2 MiB (39.9 MiB/s) with 3 file(s) remaining
Completed 146.2 MiB/233.2 MiB (39.9 MiB/s) with 3 file(s) remaining
Completed 146.4 MiB/233.2 MiB (39.9 MiB/s) with 3 file(s) remaining
Completed 146.7 MiB/233.2 MiB (40.0 MiB/s) with 3 file(s) remaining
Completed 146.9 MiB/233.2 MiB (40.0 MiB/s) with 3 file(s) remaining
Completed 147.2 MiB/233.2 MiB (40.1 MiB/s) with 3 file(s) remaining
Completed 147.4 MiB/233.2 MiB (40.1 MiB/s) with 3 file(s) remaining
Completed 147.7 MiB/233.2 MiB (40.2 MiB/s) with 3 file(s) remaining
Completed 147.9 MiB/233.2 MiB (40.2 MiB/s) with 3 file(s) remaining
Completed 148.2 MiB/233.2 MiB (40.2 MiB/s) with 3 file(s) remaining
Completed 148.4 MiB/233.2 MiB (40.3 MiB/s) with 3 file(s) remaining
Completed 148.7 MiB/233.2 MiB (40.3 MiB/s) with 3 file(s) remaining
Completed 148.9 MiB/233.2 MiB (40.4 MiB/s) with 3 file(s) remaining
Completed 149.2 MiB/233.2 MiB (40.4 MiB/s) with 3 file(s) remaining
Completed 149.4 MiB/233.2 MiB (40.5 MiB/s) with 3 file(s) remaining
Completed 149.7 MiB/233.2 MiB (40.5 MiB/s) with 3 file(s) remaining
Completed 149.9 MiB/233.2 MiB (40.5 MiB/s) with 3 file(s) remaining
Completed 150.2 MiB/233.2 MiB (40.6 MiB/s) with 3 file(s) remaining
Completed 150.4 MiB/233.2 MiB (40.6 MiB/s) with 3 file(s) remaining
Completed 150.7 MiB/233.2 MiB (40.7 MiB/s) with 3 file(s) remaining
Completed 150.9 MiB/233.2 MiB (40.7 MiB/s) with 3 file(s) remaining
Completed 151.2 MiB/233.2 MiB (40.7 MiB/s) with 3 file(s) remaining
Completed 151.4 MiB/233.2 MiB (40.8 MiB/s) with 3 file(s) remaining
Completed 151.7 MiB/233.2 MiB (40.8 MiB/s) with 3 file(s) remaining
Completed 151.9 MiB/233.2 MiB (40.9 MiB/s) with 3 file(s) remaining
Completed 152.2 MiB/233.2 MiB (40.9 MiB/s) with 3 file(s) remaining
Completed 152.4 MiB/233.2 MiB (41.0 MiB/s) with 3 file(s) remaining
Completed 152.7 MiB/233.2 MiB (41.0 MiB/s) with 3 file(s) remaining
Completed 152.9 MiB/233.2 MiB (38.7 MiB/s) with 3 file(s) remaining
Completed 153.2 MiB/233.2 MiB (38.8 MiB/s) with 3 file(s) remaining
Completed 153.4 MiB/233.2 MiB (38.8 MiB/s) with 3 file(s) remaining
Completed 153.7 MiB/233.2 MiB (38.9 MiB/s) with 3 file(s) remaining
Completed 153.9 MiB/233.2 MiB (38.9 MiB/s) with 3 file(s) remaining
Completed 154.2 MiB/233.2 MiB (39.0 MiB/s) with 3 file(s) remaining
Completed 154.4 MiB/233.2 MiB (39.0 MiB/s) with 3 file(s) remaining
Completed 154.7 MiB/233.2 MiB (39.1 MiB/s) with 3 file(s) remaining
Completed 154.9 MiB/233.2 MiB (39.1 MiB/s) with 3 file(s) remaining
Completed 155.2 MiB/233.2 MiB (39.1 MiB/s) with 3 file(s) remaining
Completed 155.4 MiB/233.2 MiB (39.2 MiB/s) with 3 file(s) remaining
Completed 155.7 MiB/233.2 MiB (39.2 MiB/s) with 3 file(s) remaining
Completed 155.9 MiB/233.2 MiB (39.3 MiB/s) with 3 file(s) remaining
Completed 156.2 MiB/233.2 MiB (39.3 MiB/s) with 3 file(s) remaining
Completed 156.4 MiB/233.2 MiB (39.3 MiB/s) with 3 file(s) remaining
Completed 156.7 MiB/233.2 MiB (39.4 MiB/s) with 3 file(s) remaining
Completed 156.9 MiB/233.2 MiB (39.4 MiB/s) with 3 file(s) remaining
Completed 157.2 MiB/233.2 MiB (39.5 MiB/s) with 3 file(s) remaining
Completed 157.4 MiB/233.2 MiB (39.5 MiB/s) with 3 file(s) remaining
Completed 157.7 MiB/233.2 MiB (39.5 MiB/s) with 3 file(s) remaining
Completed 157.9 MiB/233.2 MiB (39.6 MiB/s) with 3 file(s) remaining
Completed 158.2 MiB/233.2 MiB (39.6 MiB/s) with 3 file(s) remaining
Completed 158.4 MiB/233.2 MiB (39.7 MiB/s) with 3 file(s) remaining
Completed 158.7 MiB/233.2 MiB (39.7 MiB/s) with 3 file(s) remaining
Completed 158.9 MiB/233.2 MiB (39.7 MiB/s) with 3 file(s) remaining
Completed 159.2 MiB/233.2 MiB (39.8 MiB/s) with 3 file(s) remaining
Completed 159.4 MiB/233.2 MiB (39.8 MiB/s) with 3 file(s) remaining
Completed 159.7 MiB/233.2 MiB (39.9 MiB/s) with 3 file(s) remaining
Completed 159.9 MiB/233.2 MiB (39.9 MiB/s) with 3 file(s) remaining
Completed 160.2 MiB/233.2 MiB (39.9 MiB/s) with 3 file(s) remaining
Completed 160.4 MiB/233.2 MiB (40.0 MiB/s) with 3 file(s) remaining
Completed 160.7 MiB/233.2 MiB (40.0 MiB/s) with 3 file(s) remaining
Completed 160.9 MiB/233.2 MiB (39.9 MiB/s) with 3 file(s) remaining
Completed 161.2 MiB/233.2 MiB (40.0 MiB/s) with 3 file(s) remaining
Completed 161.4 MiB/233.2 MiB (39.5 MiB/s) with 3 file(s) remaining
Completed 161.7 MiB/233.2 MiB (38.8 MiB/s) with 3 file(s) remaining
Completed 161.9 MiB/233.2 MiB (38.5 MiB/s) with 3 file(s) remaining
Completed 162.2 MiB/233.2 MiB (35.3 MiB/s) with 3 file(s) remaining
Completed 162.4 MiB/233.2 MiB (35.4 MiB/s) with 3 file(s) remaining
Completed 162.7 MiB/233.2 MiB (35.4 MiB/s) with 3 file(s) remaining
Completed 162.9 MiB/233.2 MiB (35.4 MiB/s) with 3 file(s) remaining
Completed 163.2 MiB/233.2 MiB (34.8 MiB/s) with 3 file(s) remaining
Completed 163.4 MiB/233.2 MiB (34.6 MiB/s) with 3 file(s) remaining
Completed 163.7 MiB/233.2 MiB (34.0 MiB/s) with 3 file(s) remaining
Completed 163.9 MiB/233.2 MiB (33.0 MiB/s) with 3 file(s) remaining
Completed 164.2 MiB/233.2 MiB (33.0 MiB/s) with 3 file(s) remaining
Completed 164.4 MiB/233.2 MiB (33.0 MiB/s) with 3 file(s) remaining
Completed 164.7 MiB/233.2 MiB (33.1 MiB/s) with 3 file(s) remaining
Completed 164.9 MiB/233.2 MiB (33.1 MiB/s) with 3 file(s) remaining
Completed 165.2 MiB/233.2 MiB (33.1 MiB/s) with 3 file(s) remaining
Completed 165.4 MiB/233.2 MiB (33.2 MiB/s) with 3 file(s) remaining
Completed 165.7 MiB/233.2 MiB (33.2 MiB/s) with 3 file(s) remaining
Completed 165.9 MiB/233.2 MiB (33.3 MiB/s) with 3 file(s) remaining
Completed 166.2 MiB/233.2 MiB (33.3 MiB/s) with 3 file(s) remaining
Completed 166.4 MiB/233.2 MiB (33.3 MiB/s) with 3 file(s) remaining
Completed 166.7 MiB/233.2 MiB (33.4 MiB/s) with 3 file(s) remaining
Completed 166.9 MiB/233.2 MiB (33.4 MiB/s) with 3 file(s) remaining
Completed 167.2 MiB/233.2 MiB (33.4 MiB/s) with 3 file(s) remaining
Completed 167.4 MiB/233.2 MiB (33.5 MiB/s) with 3 file(s) remaining
Completed 167.7 MiB/233.2 MiB (33.5 MiB/s) with 3 file(s) remaining
Completed 167.9 MiB/233.2 MiB (33.5 MiB/s) with 3 file(s) remaining
Completed 168.2 MiB/233.2 MiB (33.6 MiB/s) with 3 file(s) remaining
Completed 168.4 MiB/233.2 MiB (33.6 MiB/s) with 3 file(s) remaining
Completed 168.7 MiB/233.2 MiB (33.6 MiB/s) with 3 file(s) remaining
Completed 168.9 MiB/233.2 MiB (33.7 MiB/s) with 3 file(s) remaining
Completed 169.2 MiB/233.2 MiB (33.7 MiB/s) with 3 file(s) remaining
Completed 169.4 MiB/233.2 MiB (33.7 MiB/s) with 3 file(s) remaining
Completed 169.7 MiB/233.2 MiB (33.8 MiB/s) with 3 file(s) remaining
Completed 169.9 MiB/233.2 MiB (33.8 MiB/s) with 3 file(s) remaining
Completed 170.2 MiB/233.2 MiB (33.8 MiB/s) with 3 file(s) remaining
Completed 170.4 MiB/233.2 MiB (33.9 MiB/s) with 3 file(s) remaining
Completed 170.7 MiB/233.2 MiB (33.9 MiB/s) with 3 file(s) remaining
Completed 170.9 MiB/233.2 MiB (33.9 MiB/s) with 3 file(s) remaining
Completed 171.2 MiB/233.2 MiB (34.0 MiB/s) with 3 file(s) remaining
Completed 171.4 MiB/233.2 MiB (34.0 MiB/s) with 3 file(s) remaining
Completed 171.7 MiB/233.2 MiB (34.0 MiB/s) with 3 file(s) remaining
Completed 171.9 MiB/233.2 MiB (34.0 MiB/s) with 3 file(s) remaining
Completed 172.2 MiB/233.2 MiB (34.1 MiB/s) with 3 file(s) remaining
Completed 172.4 MiB/233.2 MiB (34.1 MiB/s) with 3 file(s) remaining
Completed 172.7 MiB/233.2 MiB (34.1 MiB/s) with 3 file(s) remaining
Completed 172.9 MiB/233.2 MiB (34.1 MiB/s) with 3 file(s) remaining
Completed 173.2 MiB/233.2 MiB (34.2 MiB/s) with 3 file(s) remaining
Completed 173.4 MiB/233.2 MiB (34.2 MiB/s) with 3 file(s) remaining
Completed 173.7 MiB/233.2 MiB (34.2 MiB/s) with 3 file(s) remaining
Completed 173.9 MiB/233.2 MiB (34.2 MiB/s) with 3 file(s) remaining
Completed 174.2 MiB/233.2 MiB (34.3 MiB/s) with 3 file(s) remaining
Completed 174.4 MiB/233.2 MiB (34.3 MiB/s) with 3 file(s) remaining
Completed 174.7 MiB/233.2 MiB (34.3 MiB/s) with 3 file(s) remaining
Completed 174.9 MiB/233.2 MiB (34.4 MiB/s) with 3 file(s) remaining
Completed 175.2 MiB/233.2 MiB (34.4 MiB/s) with 3 file(s) remaining
Completed 175.4 MiB/233.2 MiB (34.4 MiB/s) with 3 file(s) remaining
Completed 175.7 MiB/233.2 MiB (34.4 MiB/s) with 3 file(s) remaining
Completed 175.9 MiB/233.2 MiB (34.5 MiB/s) with 3 file(s) remaining
Completed 176.2 MiB/233.2 MiB (34.5 MiB/s) with 3 file(s) remaining
Completed 176.4 MiB/233.2 MiB (34.5 MiB/s) with 3 file(s) remaining
Completed 176.7 MiB/233.2 MiB (34.5 MiB/s) with 3 file(s) remaining
Completed 176.9 MiB/233.2 MiB (34.5 MiB/s) with 3 file(s) remaining
Completed 177.2 MiB/233.2 MiB (34.6 MiB/s) with 3 file(s) remaining
Completed 177.4 MiB/233.2 MiB (34.6 MiB/s) with 3 file(s) remaining
Completed 177.7 MiB/233.2 MiB (34.6 MiB/s) with 3 file(s) remaining
Completed 177.9 MiB/233.2 MiB (34.1 MiB/s) with 3 file(s) remaining
Completed 178.2 MiB/233.2 MiB (34.2 MiB/s) with 3 file(s) remaining
Completed 178.4 MiB/233.2 MiB (34.2 MiB/s) with 3 file(s) remaining
Completed 178.7 MiB/233.2 MiB (34.3 MiB/s) with 3 file(s) remaining
Completed 178.9 MiB/233.2 MiB (34.3 MiB/s) with 3 file(s) remaining
Completed 179.2 MiB/233.2 MiB (34.3 MiB/s) with 3 file(s) remaining
Completed 179.4 MiB/233.2 MiB (34.3 MiB/s) with 3 file(s) remaining
Completed 179.7 MiB/233.2 MiB (34.4 MiB/s) with 3 file(s) remaining
Completed 179.9 MiB/233.2 MiB (34.4 MiB/s) with 3 file(s) remaining
Completed 180.2 MiB/233.2 MiB (34.4 MiB/s) with 3 file(s) remaining
Completed 180.4 MiB/233.2 MiB (34.4 MiB/s) with 3 file(s) remaining
Completed 180.7 MiB/233.2 MiB (34.5 MiB/s) with 3 file(s) remaining
Completed 180.9 MiB/233.2 MiB (34.5 MiB/s) with 3 file(s) remaining
Completed 181.2 MiB/233.2 MiB (34.5 MiB/s) with 3 file(s) remaining
Completed 181.4 MiB/233.2 MiB (34.5 MiB/s) with 3 file(s) remaining
Completed 181.7 MiB/233.2 MiB (34.6 MiB/s) with 3 file(s) remaining
Completed 181.9 MiB/233.2 MiB (34.6 MiB/s) with 3 file(s) remaining
Completed 182.2 MiB/233.2 MiB (34.6 MiB/s) with 3 file(s) remaining
Completed 182.4 MiB/233.2 MiB (34.6 MiB/s) with 3 file(s) remaining
Completed 182.7 MiB/233.2 MiB (34.7 MiB/s) with 3 file(s) remaining
Completed 182.9 MiB/233.2 MiB (34.7 MiB/s) with 3 file(s) remaining
Completed 183.2 MiB/233.2 MiB (34.7 MiB/s) with 3 file(s) remaining
Completed 183.4 MiB/233.2 MiB (34.7 MiB/s) with 3 file(s) remaining
Completed 183.7 MiB/233.2 MiB (34.8 MiB/s) with 3 file(s) remaining
Completed 183.9 MiB/233.2 MiB (34.8 MiB/s) with 3 file(s) remaining
Completed 184.2 MiB/233.2 MiB (34.8 MiB/s) with 3 file(s) remaining
Completed 184.4 MiB/233.2 MiB (34.9 MiB/s) with 3 file(s) remaining
Completed 184.7 MiB/233.2 MiB (34.9 MiB/s) with 3 file(s) remaining
Completed 184.9 MiB/233.2 MiB (34.9 MiB/s) with 3 file(s) remaining
Completed 185.2 MiB/233.2 MiB (34.9 MiB/s) with 3 file(s) remaining
Completed 185.4 MiB/233.2 MiB (35.0 MiB/s) with 3 file(s) remaining
Completed 185.7 MiB/233.2 MiB (35.0 MiB/s) with 3 file(s) remaining
Completed 185.9 MiB/233.2 MiB (34.7 MiB/s) with 3 file(s) remaining
Completed 186.2 MiB/233.2 MiB (34.8 MiB/s) with 3 file(s) remaining
Completed 186.4 MiB/233.2 MiB (34.8 MiB/s) with 3 file(s) remaining
Completed 186.7 MiB/233.2 MiB (34.8 MiB/s) with 3 file(s) remaining
Completed 186.9 MiB/233.2 MiB (34.8 MiB/s) with 3 file(s) remaining
Completed 187.2 MiB/233.2 MiB (34.8 MiB/s) with 3 file(s) remaining
Completed 187.4 MiB/233.2 MiB (34.8 MiB/s) with 3 file(s) remaining
Completed 187.7 MiB/233.2 MiB (34.9 MiB/s) with 3 file(s) remaining
Completed 187.9 MiB/233.2 MiB (34.9 MiB/s) with 3 file(s) remaining
Completed 188.2 MiB/233.2 MiB (34.9 MiB/s) with 3 file(s) remaining
Completed 188.4 MiB/233.2 MiB (34.9 MiB/s) with 3 file(s) remaining
Completed 188.7 MiB/233.2 MiB (35.0 MiB/s) with 3 file(s) remaining
Completed 188.9 MiB/233.2 MiB (35.0 MiB/s) with 3 file(s) remaining
Completed 189.2 MiB/233.2 MiB (35.0 MiB/s) with 3 file(s) remaining
Completed 189.4 MiB/233.2 MiB (35.1 MiB/s) with 3 file(s) remaining
Completed 189.7 MiB/233.2 MiB (35.1 MiB/s) with 3 file(s) remaining
Completed 189.9 MiB/233.2 MiB (35.1 MiB/s) with 3 file(s) remaining
Completed 190.2 MiB/233.2 MiB (35.2 MiB/s) with 3 file(s) remaining
Completed 190.4 MiB/233.2 MiB (35.2 MiB/s) with 3 file(s) remaining
Completed 190.7 MiB/233.2 MiB (35.2 MiB/s) with 3 file(s) remaining
Completed 190.9 MiB/233.2 MiB (35.3 MiB/s) with 3 file(s) remaining
Completed 191.2 MiB/233.2 MiB (35.3 MiB/s) with 3 file(s) remaining
Completed 191.4 MiB/233.2 MiB (35.3 MiB/s) with 3 file(s) remaining
Completed 191.7 MiB/233.2 MiB (35.3 MiB/s) with 3 file(s) remaining
Completed 191.9 MiB/233.2 MiB (35.4 MiB/s) with 3 file(s) remaining
Completed 192.2 MiB/233.2 MiB (35.4 MiB/s) with 3 file(s) remaining
Completed 192.4 MiB/233.2 MiB (35.4 MiB/s) with 3 file(s) remaining
Completed 192.7 MiB/233.2 MiB (35.5 MiB/s) with 3 file(s) remaining
Completed 192.9 MiB/233.2 MiB (35.5 MiB/s) with 3 file(s) remaining
Completed 193.2 MiB/233.2 MiB (35.5 MiB/s) with 3 file(s) remaining
Completed 193.4 MiB/233.2 MiB (35.6 MiB/s) with 3 file(s) remaining
Completed 193.7 MiB/233.2 MiB (35.6 MiB/s) with 3 file(s) remaining
Completed 193.9 MiB/233.2 MiB (35.2 MiB/s) with 3 file(s) remaining
Completed 194.2 MiB/233.2 MiB (35.3 MiB/s) with 3 file(s) remaining
Completed 194.4 MiB/233.2 MiB (35.3 MiB/s) with 3 file(s) remaining
Completed 194.7 MiB/233.2 MiB (34.8 MiB/s) with 3 file(s) remaining
Completed 194.9 MiB/233.2 MiB (30.6 MiB/s) with 3 file(s) remaining
Completed 195.2 MiB/233.2 MiB (30.6 MiB/s) with 3 file(s) remaining
Completed 195.4 MiB/233.2 MiB (30.3 MiB/s) with 3 file(s) remaining
Completed 195.7 MiB/233.2 MiB (30.1 MiB/s) with 3 file(s) remaining
Completed 195.9 MiB/233.2 MiB (30.1 MiB/s) with 3 file(s) remaining
Completed 196.2 MiB/233.2 MiB (30.1 MiB/s) with 3 file(s) remaining
Completed 196.4 MiB/233.2 MiB (30.1 MiB/s) with 3 file(s) remaining
Completed 196.7 MiB/233.2 MiB (30.2 MiB/s) with 3 file(s) remaining
Completed 196.9 MiB/233.2 MiB (29.9 MiB/s) with 3 file(s) remaining
Completed 197.2 MiB/233.2 MiB (29.7 MiB/s) with 3 file(s) remaining
Completed 197.4 MiB/233.2 MiB (29.8 MiB/s) with 3 file(s) remaining
Completed 197.7 MiB/233.2 MiB (29.8 MiB/s) with 3 file(s) remaining
Completed 197.9 MiB/233.2 MiB (29.8 MiB/s) with 3 file(s) remaining
Completed 198.2 MiB/233.2 MiB (29.7 MiB/s) with 3 file(s) remaining
Completed 198.4 MiB/233.2 MiB (29.6 MiB/s) with 3 file(s) remaining
Completed 198.7 MiB/233.2 MiB (29.4 MiB/s) with 3 file(s) remaining
Completed 198.9 MiB/233.2 MiB (29.4 MiB/s) with 3 file(s) remaining
Completed 199.2 MiB/233.2 MiB (29.3 MiB/s) with 3 file(s) remaining
Completed 199.4 MiB/233.2 MiB (29.3 MiB/s) with 3 file(s) remaining
Completed 199.7 MiB/233.2 MiB (29.2 MiB/s) with 3 file(s) remaining
Completed 199.9 MiB/233.2 MiB (29.1 MiB/s) with 3 file(s) remaining
Completed 200.2 MiB/233.2 MiB (29.1 MiB/s) with 3 file(s) remaining
Completed 200.4 MiB/233.2 MiB (29.1 MiB/s) with 3 file(s) remaining
Completed 200.7 MiB/233.2 MiB (29.0 MiB/s) with 3 file(s) remaining
Completed 200.9 MiB/233.2 MiB (29.1 MiB/s) with 3 file(s) remaining
Completed 201.2 MiB/233.2 MiB (28.8 MiB/s) with 3 file(s) remaining
Completed 201.4 MiB/233.2 MiB (28.8 MiB/s) with 3 file(s) remaining
Completed 201.7 MiB/233.2 MiB (28.7 MiB/s) with 3 file(s) remaining
Completed 201.9 MiB/233.2 MiB (28.5 MiB/s) with 3 file(s) remaining
Completed 202.2 MiB/233.2 MiB (28.4 MiB/s) with 3 file(s) remaining
Completed 202.4 MiB/233.2 MiB (25.3 MiB/s) with 3 file(s) remaining
Completed 202.7 MiB/233.2 MiB (25.3 MiB/s) with 3 file(s) remaining
Completed 202.9 MiB/233.2 MiB (25.3 MiB/s) with 3 file(s) remaining
Completed 203.2 MiB/233.2 MiB (25.3 MiB/s) with 3 file(s) remaining
Completed 203.4 MiB/233.2 MiB (25.3 MiB/s) with 3 file(s) remaining
Completed 203.7 MiB/233.2 MiB (25.3 MiB/s) with 3 file(s) remaining
Completed 203.9 MiB/233.2 MiB (25.3 MiB/s) with 3 file(s) remaining
Completed 204.2 MiB/233.2 MiB (25.3 MiB/s) with 3 file(s) remaining
Completed 204.4 MiB/233.2 MiB (25.3 MiB/s) with 3 file(s) remaining
Completed 204.7 MiB/233.2 MiB (25.3 MiB/s) with 3 file(s) remaining
Completed 204.9 MiB/233.2 MiB (25.3 MiB/s) with 3 file(s) remaining
Completed 205.2 MiB/233.2 MiB (25.4 MiB/s) with 3 file(s) remaining
Completed 205.4 MiB/233.2 MiB (25.4 MiB/s) with 3 file(s) remaining
Completed 205.7 MiB/233.2 MiB (25.4 MiB/s) with 3 file(s) remaining
Completed 205.9 MiB/233.2 MiB (25.4 MiB/s) with 3 file(s) remaining
Completed 206.2 MiB/233.2 MiB (25.4 MiB/s) with 3 file(s) remaining
Completed 206.4 MiB/233.2 MiB (25.4 MiB/s) with 3 file(s) remaining
Completed 206.7 MiB/233.2 MiB (25.5 MiB/s) with 3 file(s) remaining
Completed 206.9 MiB/233.2 MiB (25.5 MiB/s) with 3 file(s) remaining
Completed 207.2 MiB/233.2 MiB (25.5 MiB/s) with 3 file(s) remaining
Completed 207.4 MiB/233.2 MiB (25.5 MiB/s) with 3 file(s) remaining
Completed 207.7 MiB/233.2 MiB (25.5 MiB/s) with 3 file(s) remaining
Completed 207.9 MiB/233.2 MiB (25.5 MiB/s) with 3 file(s) remaining
Completed 208.2 MiB/233.2 MiB (25.6 MiB/s) with 3 file(s) remaining
Completed 208.4 MiB/233.2 MiB (25.6 MiB/s) with 3 file(s) remaining
Completed 208.7 MiB/233.2 MiB (25.6 MiB/s) with 3 file(s) remaining
Completed 208.9 MiB/233.2 MiB (25.6 MiB/s) with 3 file(s) remaining
Completed 209.2 MiB/233.2 MiB (25.6 MiB/s) with 3 file(s) remaining
Completed 209.4 MiB/233.2 MiB (25.6 MiB/s) with 3 file(s) remaining
Completed 209.7 MiB/233.2 MiB (25.7 MiB/s) with 3 file(s) remaining
Completed 209.9 MiB/233.2 MiB (25.7 MiB/s) with 3 file(s) remaining
Completed 210.2 MiB/233.2 MiB (25.7 MiB/s) with 3 file(s) remaining
Completed 210.4 MiB/233.2 MiB (25.7 MiB/s) with 3 file(s) remaining
Completed 210.7 MiB/233.2 MiB (25.7 MiB/s) with 3 file(s) remaining
Completed 210.9 MiB/233.2 MiB (25.7 MiB/s) with 3 file(s) remaining
Completed 211.2 MiB/233.2 MiB (25.7 MiB/s) with 3 file(s) remaining
Completed 211.4 MiB/233.2 MiB (25.7 MiB/s) with 3 file(s) remaining
Completed 211.7 MiB/233.2 MiB (25.7 MiB/s) with 3 file(s) remaining
Completed 211.9 MiB/233.2 MiB (25.8 MiB/s) with 3 file(s) remaining
Completed 212.2 MiB/233.2 MiB (25.8 MiB/s) with 3 file(s) remaining
Completed 212.4 MiB/233.2 MiB (25.8 MiB/s) with 3 file(s) remaining
Completed 212.7 MiB/233.2 MiB (25.8 MiB/s) with 3 file(s) remaining
Completed 212.9 MiB/233.2 MiB (25.8 MiB/s) with 3 file(s) remaining
Completed 213.2 MiB/233.2 MiB (25.8 MiB/s) with 3 file(s) remaining
Completed 213.4 MiB/233.2 MiB (25.8 MiB/s) with 3 file(s) remaining
Completed 213.7 MiB/233.2 MiB (25.9 MiB/s) with 3 file(s) remaining
Completed 213.9 MiB/233.2 MiB (25.9 MiB/s) with 3 file(s) remaining
Completed 214.2 MiB/233.2 MiB (25.9 MiB/s) with 3 file(s) remaining
Completed 214.4 MiB/233.2 MiB (25.9 MiB/s) with 3 file(s) re...Truncated

**Comment by minio-ops** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-xl.sh | :heavy_check_mark: |
| mint-compression-dist-xl.sh | :heavy_check_mark: |
| mint-compression-fs.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-dist-xl.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-compression-xl.sh | :x: [more...](#081d1060-1a03-479d-a312-bfd0875b9af6) |
| mint-large-bucket.sh | :x: [more...](#d898b95e-772f-47b3-a11a-e09a7e7c149d) |
| mint-worm.sh | :x: [more...](#270ccb2e-a4ef-42da-860b-972cb1ec74b8) |
<a name="d898b95e-772f-47b3-a11a-e09a7e7c149d"></a>
### 8027-aae92bc/mint-large-bucket.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.52:31819
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 97459c10abd2:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 3 seconds
(2/14) Running aws-sdk-java tests ... done in 2 seconds
(3/14) Running aws-sdk-php tests ... done in 50 seconds
(4/14) Running aws-sdk-ruby tests ... done in 14 seconds
(5/14) Running awscli tests ... FAILED in 2 minutes and 10 seconds
{"name": "awscli", "duration": 66674, "function": "aws --endpoint-url http://72.28.97.52:31819 s3 sync /mint/data s3://awscli-mint-test-bucket-5091/\n", "status": "FAIL", "error": "Completed 256.0 KiB/233.2 MiB (4.3 MiB/s) with 15 file(s) remaining
Completed 512.0 KiB/233.2 MiB (8.5 MiB/s) with 15 file(s) remaining
Completed 768.0 KiB/233.2 MiB (12.2 MiB/s) with 15 file(s) remaining
Completed 1.0 MiB/233.2 MiB (16.1 MiB/s) with 15 file(s) remaining  
Completed 1.2 MiB/233.2 MiB (19.1 MiB/s) with 15 file(s) remaining  
Completed 1.5 MiB/233.2 MiB (22.7 MiB/s) with 15 file(s) remaining  
Completed 1.8 MiB/233.2 MiB (26.1 MiB/s) with 15 file(s) remaining  
Completed 2.0 MiB/233.2 MiB (29.6 MiB/s) with 15 file(s) remaining  
Completed 2.0 MiB/233.2 MiB (8.1 MiB/s) with 15 file(s) remaining   
upload: ../../../data/datafile-10-kB to s3://awscli-mint-test-bucket-5091/datafile-10-kBCompleted 2.0 MiB/233.2 MiB (8.1 MiB/s) with 14 file(s) remaining
upload: ../../../data/datafile-0-b to s3://awscli-mint-test-bucket-5091/datafile-0-bCompleted 2.0 MiB/233.2 MiB (8.1 MiB/s) with 13 file(s) remaining
Completed 2.1 MiB/233.2 MiB (8.3 MiB/s) with 13 file(s) remaining
upload: ../../../data/datafile-100-kB to s3://awscli-mint-test-bucket-5091/datafile-100-kBCompleted 2.1 MiB/233.2 MiB (8.3 MiB/s) with 12 file(s) remaining
Completed 2.1 MiB/233.2 MiB (7.6 MiB/s) with 12 file(s) remaining
upload: ../../../data/datafile-1.03-MB to s3://awscli-mint-test-bucket-5091/datafile-1.03-MBCompleted 2.1 MiB/233.2 MiB (7.6 MiB/s) with 11 file(s) remaining
Completed 2.4 MiB/233.2 MiB (7.9 MiB/s) with 11 file(s) remaining
Completed 2.6 MiB/233.2 MiB (8.7 MiB/s) with 11 file(s) remaining
Completed 2.9 MiB/233.2 MiB (9.5 MiB/s) with 11 file(s) remaining
Completed 3.1 MiB/233.2 MiB (10.3 MiB/s) with 11 file(s) remaining
Completed 3.4 MiB/233.2 MiB (11.1 MiB/s) with 11 file(s) remaining
Completed 3.6 MiB/233.2 MiB (11.7 MiB/s) with 11 file(s) remaining
Completed 3.9 MiB/233.2 MiB (12.0 MiB/s) with 11 file(s) remaining
Completed 4.1 MiB/233.2 MiB (12.2 MiB/s) with 11 file(s) remaining
Completed 4.4 MiB/233.2 MiB (12.5 MiB/s) with 11 file(s) remaining
Completed 4.4 MiB/233.2 MiB (12.4 MiB/s) with 11 file(s) remaining
upload: ../../../data/datafile-33-kB to s3://awscli-mint-test-bucket-5091/datafile-33-kBCompleted 4.4 MiB/233.2 MiB (12.4 MiB/s) with 10 file(s) remaining
Completed 4.4 MiB/233.2 MiB (12.3 MiB/s) with 10 file(s) remaining
upload: ../../../data/datafile-1-b to s3://awscli-mint-test-bucket-5091/datafile-1-bCompleted 4.4 MiB/233.2 MiB (12.3 MiB/s) with 9 file(s) remaining
Completed 4.7 MiB/233.2 MiB (12.8 MiB/s) with 9 file(s) remaining
Completed 4.9 MiB/233.2 MiB (13.4 MiB/s) with 9 file(s) remaining
Completed 5.2 MiB/233.2 MiB (14.0 MiB/s) with 9 file(s) remaining
Completed 5.4 MiB/233.2 MiB (14.6 MiB/s) with 9 file(s) remaining
Completed 5.7 MiB/233.2 MiB (15.3 MiB/s) with 9 file(s) remaining
Completed 5.9 MiB/233.2 MiB (15.8 MiB/s) with 9 file(s) remaining
Completed 6.2 MiB/233.2 MiB (16.1 MiB/s) with 9 file(s) remaining
Completed 6.4 MiB/233.2 MiB (16.7 MiB/s) with 9 file(s) remaining
Completed 6.7 MiB/233.2 MiB (16.6 MiB/s) with 9 file(s) remaining
Completed 6.9 MiB/233.2 MiB (17.2 MiB/s) with 9 file(s) remaining
Completed 7.2 MiB/233.2 MiB (17.7 MiB/s) with 9 file(s) remaining
Completed 7.4 MiB/233.2 MiB (18.3 MiB/s) with 9 file(s) remaining
Completed 7.7 MiB/233.2 MiB (18.9 MiB/s) with 9 file(s) remaining
Completed 7.9 MiB/233.2 MiB (19.4 MiB/s) with 9 file(s) remaining
Completed 8.2 MiB/233.2 MiB (20.0 MiB/s) with 9 file(s) remaining
Completed 8.4 MiB/233.2 MiB (20.5 MiB/s) with 9 file(s) remaining
Completed 8.7 MiB/233.2 MiB (21.0 MiB/s) with 9 file(s) remaining
Completed 8.9 MiB/233.2 MiB (21.6 MiB/s) with 9 file(s) remaining
Completed 9.2 MiB/233.2 MiB (22.1 MiB/s) with 9 file(s) remaining
Completed 9.4 MiB/233.2 MiB (22.7 MiB/s) with 9 file(s) remaining
Completed 9.7 MiB/233.2 MiB (23.0 MiB/s) with 9 file(s) remaining
Completed 9.9 MiB/233.2 MiB (23.6 MiB/s) with 9 file(s) remaining
Completed 10.2 MiB/233.2 MiB (24.2 MiB/s) with 9 file(s) remaining
Completed 10.4 MiB/233.2 MiB (24.7 MiB/s) with 9 file(s) remaining
Completed 10.7 MiB/233.2 MiB (25.3 MiB/s) with 9 file(s) remaining
Completed 10.9 MiB/233.2 MiB (25.8 MiB/s) with 9 file(s) remaining
Completed 11.2 MiB/233.2 MiB (26.3 MiB/s) with 9 file(s) remaining
Completed 11.4 MiB/233.2 MiB (26.8 MiB/s) with 9 file(s) remaining
Completed 11.7 MiB/233.2 MiB (27.3 MiB/s) with 9 file(s) remaining
Completed 11.9 MiB/233.2 MiB (27.4 MiB/s) with 9 file(s) remaining
Completed 12.2 MiB/233.2 MiB (27.6 MiB/s) with 9 file(s) remaining
Completed 12.4 MiB/233.2 MiB (27.8 MiB/s) with 9 file(s) remaining
Completed 12.7 MiB/233.2 MiB (27.9 MiB/s) with 9 file(s) remaining
Completed 12.9 MiB/233.2 MiB (28.5 MiB/s) with 9 file(s) remaining
Completed 13.2 MiB/233.2 MiB (28.3 MiB/s) with 9 file(s) remaining
Completed 13.4 MiB/233.2 MiB (28.7 MiB/s) with 9 file(s) remaining
Completed 13.7 MiB/233.2 MiB (28.8 MiB/s) with 9 file(s) remaining
Completed 13.9 MiB/233.2 MiB (29.0 MiB/s) with 9 file(s) remaining
Completed 14.2 MiB/233.2 MiB (29.5 MiB/s) with 9 file(s) remaining
Completed 14.4 MiB/233.2 MiB (29.5 MiB/s) with 9 file(s) remaining
Completed 14.7 MiB/233.2 MiB (29.9 MiB/s) with 9 file(s) remaining
Completed 14.7 MiB/233.2 MiB (29.4 MiB/s) with 9 file(s) remaining
upload: ../../../data/datafile-1-kB to s3://awscli-mint-test-bucket-5091/datafile-1-kBCompleted 14.7 MiB/233.2 MiB (29.4 MiB/s) with 8 file(s) remaining
Completed 14.9 MiB/233.2 MiB (29.8 MiB/s) with 8 file(s) remaining
Completed 15.2 MiB/233.2 MiB (30.2 MiB/s) with 8 file(s) remaining
Completed 15.4 MiB/233.2 MiB (30.6 MiB/s) with 8 file(s) remaining
Completed 15.7 MiB/233.2 MiB (31.1 MiB/s) with 8 file(s) remaining
Completed 15.9 MiB/233.2 MiB (31.5 MiB/s) with 8 file(s) remaining
Completed 16.2 MiB/233.2 MiB (31.9 MiB/s) with 8 file(s) remaining
Completed 16.4 MiB/233.2 MiB (32.3 MiB/s) with 8 file(s) remaining
Completed 16.7 MiB/233.2 MiB (32.4 MiB/s) with 8 file(s) remaining
Completed 16.9 MiB/233.2 MiB (32.7 MiB/s) with 8 file(s) remaining
Completed 17.2 MiB/233.2 MiB (33.0 MiB/s) with 8 file(s) remaining
Completed 17.4 MiB/233.2 MiB (32.6 MiB/s) with 8 file(s) remaining
Completed 17.7 MiB/233.2 MiB (32.9 MiB/s) with 8 file(s) remaining
Completed 17.9 MiB/233.2 MiB (33.4 MiB/s) with 8 file(s) remaining
Completed 18.2 MiB/233.2 MiB (33.2 MiB/s) with 8 file(s) remaining
Completed 18.4 MiB/233.2 MiB (33.6 MiB/s) with 8 file(s) remaining
Completed 18.7 MiB/233.2 MiB (33.5 MiB/s) with 8 file(s) remaining
Completed 18.9 MiB/233.2 MiB (33.5 MiB/s) with 8 file(s) remaining
Completed 19.2 MiB/233.2 MiB (33.9 MiB/s) with 8 file(s) remaining
Completed 19.4 MiB/233.2 MiB (33.6 MiB/s) with 8 file(s) remaining
Completed 19.7 MiB/233.2 MiB (34.0 MiB/s) with 8 file(s) remaining
Completed 19.9 MiB/233.2 MiB (34.1 MiB/s) with 8 file(s) remaining
Completed 20.2 MiB/233.2 MiB (33.8 MiB/s) with 8 file(s) remaining
Completed 20.4 MiB/233.2 MiB (34.2 MiB/s) with 8 file(s) remaining
Completed 20.7 MiB/233.2 MiB (34.2 MiB/s) with 8 file(s) remaining
Completed 20.9 MiB/233.2 MiB (34.5 MiB/s) with 8 file(s) remaining
Completed 21.2 MiB/233.2 MiB (34.9 MiB/s) with 8 file(s) remaining
Completed 21.4 MiB/233.2 MiB (35.3 MiB/s) with 8 file(s) remaining
Completed 21.7 MiB/233.2 MiB (35.6 MiB/s) with 8 file(s) remaining
Completed 21.9 MiB/233.2 MiB (36.0 MiB/s) with 8 file(s) remaining
Completed 22.2 MiB/233.2 MiB (36.3 MiB/s) with 8 file(s) remaining
upload: ../../../data/datafile-1-MB to s3://awscli-mint-test-bucket-5091/datafile-1-MBCompleted 22.2 MiB/233.2 MiB (36.3 MiB/s) with 7 file(s) remaining
Completed 22.4 MiB/233.2 MiB (35.9 MiB/s) with 7 file(s) remaining
Completed 22.7 MiB/233.2 MiB (36.1 MiB/s) with 7 file(s) remaining
Completed 22.9 MiB/233.2 MiB (35.8 MiB/s) with 7 file(s) remaining
Completed 23.2 MiB/233.2 MiB (36.2 MiB/s) with 7 file(s) remaining
Completed 23.4 MiB/233.2 MiB (36.6 MiB/s) with 7 file(s) remaining
Completed 23.7 MiB/233.2 MiB (36.4 MiB/s) with 7 file(s) remaining
Completed 23.9 MiB/233.2 MiB (36.8 MiB/s) with 7 file(s) remaining
Completed 24.2 MiB/233.2 MiB (36.7 MiB/s) with 7 file(s) remaining
Completed 24.4 MiB/233.2 MiB (36.5 MiB/s) with 7 file(s) remaining
Completed 24.7 MiB/233.2 MiB (36.9 MiB/s) with 7 file(s) remaining
Completed 24.9 MiB/233.2 MiB (37.2 MiB/s) with 7 file(s) remaining
Completed 25.2 MiB/233.2 MiB (37.3 MiB/s) with 7 file(s) remaining
Completed 25.4 MiB/233.2 MiB (37.5 MiB/s) with 7 file(s) remaining
Completed 25.7 MiB/233.2 MiB (37.0 MiB/s) with 7 file(s) remaining
Completed 25.9 MiB/233.2 MiB (36.9 MiB/s) with 7 file(s) remaining
Completed 26.2 MiB/233.2 MiB (37.1 MiB/s) with 7 file(s) remaining
Completed 26.4 MiB/233.2 MiB (37.3 MiB/s) with 7 file(s) remaining
Completed 26.7 MiB/233.2 MiB (37.6 MiB/s) with 7 file(s) remaining
Completed 26.9 MiB/233.2 MiB (37.9 MiB/s) with 7 file(s) remaining
Completed 27.2 MiB/233.2 MiB (38.2 MiB/s) with 7 file(s) remaining
Completed 27.4 MiB/233.2 MiB (38.5 MiB/s) with 7 file(s) remaining
Completed 27.7 MiB/233.2 MiB (38.8 MiB/s) with 7 file(s) remaining
Completed 27.9 MiB/233.2 MiB (38.5 MiB/s) with 7 file(s) remaining
Completed 28.2 MiB/233.2 MiB (38.5 MiB/s) with 7 file(s) remaining
Completed 28.4 MiB/233.2 MiB (38.8 MiB/s) with 7 file(s) remaining
Completed 28.7 MiB/233.2 MiB (39.0 MiB/s) with 7 file(s) remaining
Completed 28.9 MiB/233.2 MiB (39.3 MiB/s) with 7 file(s) remaining
Completed 29.2 MiB/233.2 MiB (39.3 MiB/s) with 7 file(s) remaining
Completed 29.4 MiB/233.2 MiB (39.5 MiB/s) with 7 file(s) remaining
Completed 29.7 MiB/233.2 MiB (39.2 MiB/s) with 7 file(s) remaining
Completed 29.9 MiB/233.2 MiB (39.3 MiB/s) with 7 file(s) remaining
Completed 30.2 MiB/233.2 MiB (39.4 MiB/s) with 7 file(s) remaining
Completed 30.4 MiB/233.2 MiB (39.7 MiB/s) with 7 file(s) remaining
Completed 30.7 MiB/233.2 MiB (39.7 MiB/s) with 7 file(s) remaining
Completed 30.9 MiB/233.2 MiB (39.3 MiB/s) with 7 file(s) remaining
Completed 31.2 MiB/233.2 MiB (39.5 MiB/s) with 7 file(s) remaining
Completed 31.4 MiB/233.2 MiB (39.7 MiB/s) with 7 file(s) remaining
Completed 31.7 MiB/233.2 MiB (39.6 MiB/s) with 7 file(s) remaining
Completed 31.9 MiB/233.2 MiB (39.8 MiB/s) with 7 file(s) remaining
Completed 32.2 MiB/233.2 MiB (39.9 MiB/s) with 7 file(s) remaining
Completed 32.4 MiB/233.2 MiB (40.0 MiB/s) with 7 file(s) remaining
Completed 32.7 MiB/233.2 MiB (39.5 MiB/s) with 7 file(s) remaining
Completed 32.9 MiB/233.2 MiB (39.5 MiB/s) with 7 file(s) remaining
Completed 33.2 MiB/233.2 MiB (39.6 MiB/s) with 7 file(s) remaining
Completed 33.4 MiB/233.2 MiB (39.9 MiB/s) with 7 file(s) remaining
upload: ../../../data/datafile-5-MB to s3://awscli-mint-test-bucket-5091/datafile-5-MBCompleted 33.4 MiB/233.2 MiB (39.9 MiB/s) with 6 file(s) remaining
Completed 33.7 MiB/233.2 MiB (39.6 MiB/s) with 6 file(s) remaining
Completed 33.9 MiB/233.2 MiB (39.9 MiB/s) with 6 file(s) remaining
Completed 34.2 MiB/233.2 MiB (39.6 MiB/s) with 6 file(s) remaining
Completed 34.4 MiB/233.2 MiB (39.8 MiB/s) with 6 file(s) remaining
Completed 34.7 MiB/233.2 MiB (39.7 MiB/s) with 6 file(s) remaining
Completed 34.9 MiB/233.2 MiB (39.8 MiB/s) with 6 file(s) remaining
Completed 35.2 MiB/233.2 MiB (39.4 MiB/s) with 6 file(s) remaining
Completed 35.4 MiB/233.2 MiB (39.7 MiB/s) with 6 file(s) remaining
Completed 35.7 MiB/233.2 MiB (39.6 MiB/s) with 6 file(s) remaining
Completed 35.9 MiB/233.2 MiB (39.8 MiB/s) with 6 file(s) remaining
Completed 36.2 MiB/233.2 MiB (39.4 MiB/s) with 6 file(s) remaining
Completed 36.4 MiB/233.2 MiB (39.5 MiB/s) with 6 file(s) remaining
Completed 36.7 MiB/233.2 MiB (39.7 MiB/s) with 6 file(s) remaining
Completed 36.9 MiB/233.2 MiB (39.7 MiB/s) with 6 file(s) remaining
Completed 37.2 MiB/233.2 MiB (39.5 MiB/s) with 6 file(s) remaining
Completed 37.4 MiB/233.2 MiB (39.5 MiB/s) with 6 file(s) remaining
Completed 37.7 MiB/233.2 MiB (39.7 MiB/s) with 6 file(s) remaining
Completed 37.9 MiB/233.2 MiB (39.7 MiB/s) with 6 file(s) remaining
Completed 38.2 MiB/233.2 MiB (39.8 MiB/s) with 6 file(s) remaining
Completed 38.4 MiB/233.2 MiB (39.8 MiB/s) with 6 file(s) remaining
Completed 38.7 MiB/233.2 MiB (39.8 MiB/s) with 6 file(s) remaining
Completed 38.9 MiB/233.2 MiB (40.0 MiB/s) with 6 file(s) remaining
Completed 39.2 MiB/233.2 MiB (40.0 MiB/s) with 6 file(s) remaining
Completed 39.4 MiB/233.2 MiB (39.7 MiB/s) with 6 file(s) remaining
Completed 39.7 MiB/233.2 MiB (39.7 MiB/s) with 6 file(s) remaining
Completed 39.9 MiB/233.2 MiB (39.9 MiB/s) with 6 file(s) remaining
Completed 40.2 MiB/233.2 MiB (40.0 MiB/s) with 6 file(s) remaining
Completed 40.4 MiB/233.2 MiB (40.2 MiB/s) with 6 file(s) remaining
Completed 40.7 MiB/233.2 MiB (39.7 MiB/s) with 6 file(s) remaining
Completed 40.9 MiB/233.2 MiB (39.9 MiB/s) with 6 file(s) remaining
Completed 41.2 MiB/233.2 MiB (40.0 MiB/s) with 6 file(s) remaining
Completed 41.4 MiB/233.2 MiB (40.1 MiB/s) with 6 file(s) remaining
Completed 41.7 MiB/233.2 MiB (39.8 MiB/s) with 6 file(s) remaining
Completed 41.9 MiB/233.2 MiB (40.0 MiB/s) with 6 file(s) remaining
Completed 42.2 MiB/233.2 MiB (40.1 MiB/s) with 6 file(s) remaining
Completed 42.4 MiB/233.2 MiB (40.2 MiB/s) with 6 file(s) remaining
Completed 42.7 MiB/233.2 MiB (40.2 MiB/s) with 6 file(s) remaining
Completed 42.9 MiB/233.2 MiB (40.0 MiB/s) with 6 file(s) remaining
Completed 43.2 MiB/233.2 MiB (40.2 MiB/s) with 6 file(s) remaining
Completed 43.2 MiB/233.2 MiB (40.0 MiB/s) with 6 file(s) remaining
upload: ../../../data/datafile-5243880-b to s3://awscli-mint-test-bucket-5091/datafile-5243880-bCompleted 43.2 MiB/233.2 MiB (40.0 MiB/s) with 5 file(s) remaining
Completed 43.4 MiB/233.2 MiB (40.1 MiB/s) with 5 file(s) remaining
Completed 43.7 MiB/233.2 MiB (40.1 MiB/s) with 5 file(s) remaining
Completed 43.9 MiB/233.2 MiB (40.1 MiB/s) with 5 file(s) remaining
Completed 44.2 MiB/233.2 MiB (40.3 MiB/s) with 5 file(s) remaining
Completed 44.4 MiB/233.2 MiB (40.4 MiB/s) with 5 file(s) remaining
Completed 44.7 MiB/233.2 MiB (40.2 MiB/s) with 5 file(s) remaining
Completed 44.9 MiB/233.2 MiB (40.1 MiB/s) with 5 file(s) remaining
Completed 45.2 MiB/233.2 MiB (40.3 MiB/s) with 5 file(s) remaining
Completed 45.4 MiB/233.2 MiB (40.4 MiB/s) with 5 file(s) remaining
Completed 45.7 MiB/233.2 MiB (40.6 MiB/s) with 5 file(s) remaining
Completed 45.9 MiB/233.2 MiB (40.4 MiB/s) with 5 file(s) remaining
Completed 46.2 MiB/233.2 MiB (40.3 MiB/s) with 5 file(s) remaining
Completed 46.4 MiB/233.2 MiB (40.4 MiB/s) with 5 file(s) remaining
Completed 46.7 MiB/233.2 MiB (40.6 MiB/s) with 5 file(s) remaining
Completed 46.9 MiB/233.2 MiB (40.8 MiB/s) with 5 file(s) remaining
Completed 47.2 MiB/233.2 MiB (40.7 MiB/s) with 5 file(s) remaining
Completed 47.4 MiB/233.2 MiB (40.6 MiB/s) with 5 file(s) remaining
Completed 47.7 MiB/233.2 MiB (40.4 MiB/s) with 5 file(s) remaining
Completed 47.9 MiB/233.2 MiB (40.4 MiB/s) with 5 file(s) remaining
Completed 48.2 MiB/233.2 MiB (40.4 MiB/s) with 5 file(s) remaining
Completed 48.4 MiB/233.2 MiB (40.5 MiB/s) with 5 file(s) remaining
Completed 48.7 MiB/233.2 MiB (40.6 MiB/s) with 5 file(s) remaining
Completed 48.9 MiB/233.2 MiB (40.4 MiB/s) with 5 file(s) remaining
Completed 49.2 MiB/233.2 MiB (40.3 MiB/s) with 5 file(s) remaining
Completed 49.4 MiB/233.2 MiB (40.4 MiB/s) with 5 file(s) remaining
Completed 49.7 MiB/233.2 MiB (40.2 MiB/s) with 5 file(s) remaining
Completed 49.9 MiB/233.2 MiB (40.2 MiB/s) with 5 file(s) remaining
Completed 50.2 MiB/233.2 MiB (40.0 MiB/s) with 5 file(s) remaining
Completed 50.4 MiB/233.2 MiB (40.2 MiB/s) with 5 file(s) remaining
Completed 50.7 MiB/233.2 MiB (40.3 MiB/s) with 5 file(s) remaining
Completed 50.9 MiB/233.2 MiB (39.8 MiB/s) with 5 file(s) remaining
Completed 51.2 MiB/233.2 MiB (39.7 MiB/s) with 5 file(s) remaining
Completed 51.4 MiB/233.2 MiB (39.7 MiB/s) with 5 file(s) remaining
Completed 51.7 MiB/233.2 MiB (39.7 MiB/s) with 5 file(s) remaining
Completed 51.9 MiB/233.2 MiB (39.4 MiB/s) with 5 file(s) remaining
Completed 52.2 MiB/233.2 MiB (39.5 MiB/s) with 5 file(s) remaining
Completed 52.4 MiB/233.2 MiB (39.3 MiB/s) with 5 file(s) remaining
Completed 52.7 MiB/233.2 MiB (39.0 MiB/s) with 5 file(s) remaining
Completed 52.9 MiB/233.2 MiB (39.1 MiB/s) with 5 file(s) remaining
Completed 53.2 MiB/233.2 MiB (39.0 MiB/s) with 5 file(s) remaining
Completed 53.4 MiB/233.2 MiB (39.2 MiB/s) with 5 file(s) remaining
Completed 53.7 MiB/233.2 MiB (39.3 MiB/s) with 5 file(s) remaining
Completed 53.9 MiB/233.2 MiB (39.5 MiB/s) with 5 file(s) remaining
Completed 54.2 MiB/233.2 MiB (39.6 MiB/s) with 5 file(s) remaining
Completed 54.4 MiB/233.2 MiB (39.5 MiB/s) with 5 file(s) remaining
Completed 54.7 MiB/233.2 MiB (39.7 MiB/s) with 5 file(s) remaining
Completed 54.9 MiB/233.2 MiB (39.9 MiB/s) with 5 file(s) remaining
upload: ../../../data/datafile-6-MB to s3://awscli-mint-test-bucket-5091/datafile-6-MBCompleted 54.9 MiB/233.2 MiB (39.9 MiB/s) with 4 file(s) remaining
Completed 55.2 MiB/233.2 MiB (39.4 MiB/s) with 4 file(s) remaining
Completed 55.4 MiB/233.2 MiB (39.5 MiB/s) with 4 file(s) remaining
Completed 55.7 MiB/233.2 MiB (39.2 MiB/s) with 4 file(s) remaining
Completed 55.9 MiB/233.2 MiB (39.0 MiB/s) with 4 file(s) remaining
Completed 56.2 MiB/233.2 MiB (39.0 MiB/s) with 4 file(s) remaining
Completed 56.4 MiB/233.2 MiB (38.8 MiB/s) with 4 file(s) remaining
Completed 56.7 MiB/233.2 MiB (38.7 MiB/s) with 4 file(s) remaining
Completed 56.9 MiB/233.2 MiB (38.7 MiB/s) with 4 file(s) remaining
Completed 57.2 MiB/233.2 MiB (38.4 MiB/s) with 4 file(s) remaining
Completed 57.4 MiB/233.2 MiB (38.6 MiB/s) with 4 file(s) remaining
Completed 57.7 MiB/233.2 MiB (38.3 MiB/s) with 4 file(s) remaining
Completed 57.9 MiB/233.2 MiB (38.2 MiB/s) with 4 file(s) remaining
Completed 58.2 MiB/233.2 MiB (38.2 MiB/s) with 4 file(s) remaining
Completed 58.4 MiB/233.2 MiB (38.1 MiB/s) with 4 file(s) remaining
Completed 58.7 MiB/233.2 MiB (37.7 MiB/s) with 4 file(s) remaining
Completed 58.9 MiB/233.2 MiB (37.4 MiB/s) with 4 file(s) remaining
Completed 59.2 MiB/233.2 MiB (37.0 MiB/s) with 4 file(s) remaining
Completed 59.4 MiB/233.2 MiB (36.7 MiB/s) with 4 file(s) remaining
Completed 59.7 MiB/233.2 MiB (36.3 MiB/s) with 4 file(s) remaining
Completed 59.9 MiB/233.2 MiB (36.3 MiB/s) with 4 file(s) remaining
Completed 60.2 MiB/233.2 MiB (36.5 MiB/s) with 4 file(s) remaining
Completed 60.4 MiB/233.2 MiB (36.6 MiB/s) with 4 file(s) remaining
Completed 60.7 MiB/233.2 MiB (36.7 MiB/s) with 4 file(s) remaining
Completed 60.9 MiB/233.2 MiB (36.9 MiB/s) with 4 file(s) remaining
Completed 61.2 MiB/233.2 MiB (36.9 MiB/s) with 4 file(s) remaining
Completed 61.4 MiB/233.2 MiB (37.0 MiB/s) with 4 file(s) remaining
Completed 61.7 MiB/233.2 MiB (36.9 MiB/s) with 4 file(s) remaining
Completed 61.9 MiB/233.2 MiB (36.8 MiB/s) with 4 file(s) remaining
Completed 62.2 MiB/233.2 MiB (36.9 MiB/s) with 4 file(s) remaining
Completed 62.4 MiB/233.2 MiB (36.8 MiB/s) with 4 file(s) remaining
Completed 62.7 MiB/233.2 MiB (36.9 MiB/s) with 4 file(s) remaining
Completed 62.9 MiB/233.2 MiB (36.9 MiB/s) with 4 file(s) remaining
Completed 63.2 MiB/233.2 MiB (36.8 MiB/s) with 4 file(s) remaining
Completed 63.4 MiB/233.2 MiB (36.8 MiB/s) with 4 file(s) remaining
Completed 63.7 MiB/233.2 MiB (36.7 MiB/s) with 4 file(s) remaining
Completed 63.9 MiB/233.2 MiB (36.8 MiB/s) with 4 file(s) remaining
Completed 64.2 MiB/233.2 MiB (36.7 MiB/s) with 4 file(s) remaining
Completed 64.4 MiB/233.2 MiB (36.8 MiB/s) with 4 file(s) remaining
upload: ../../../data/datafile-11-MB to s3://awscli-mint-test-bucket-5091/datafile-11-MBCompleted 64.4 MiB/233.2 MiB (36.8 MiB/s) with 3 file(s) remaining
Completed 64.7 MiB/233.2 MiB (36.6 MiB/s) with 3 file(s) remaining
Completed 64.9 MiB/233.2 MiB (36.7 MiB/s) with 3 file(s) remaining
Completed 65.2 MiB/233.2 MiB (36.5 MiB/s) with 3 file(s) remaining
Completed 65.4 MiB/233.2 MiB (36.6 MiB/s) with 3 file(s) remaining
Completed 65.7 MiB/233.2 MiB (36.6 MiB/s) with 3 file(s) remaining
Completed 65.9 MiB/233.2 MiB (36.7 MiB/s) with 3 file(s) remaining
Completed 66.2 MiB/233.2 MiB (36.8 MiB/s) with 3 file(s) remaining
Completed 66.4 MiB/233.2 MiB (36.8 MiB/s) with 3 file(s) remaining
Completed 66.7 MiB/233.2 MiB (36.9 MiB/s) with 3 file(s) remaining
Completed 66.9 MiB/233.2 MiB (36.8 MiB/s) with 3 file(s) remaining
Completed 67.2 MiB/233.2 MiB (36.8 MiB/s) with 3 file(s) remaining
Completed 67.4 MiB/233.2 MiB (36.8 MiB/s) with 3 file(s) remaining
Completed 67.7 MiB/233.2 MiB (36.7 MiB/s) with 3 file(s) remaining
Completed 67.9 MiB/233.2 MiB (36.8 MiB/s) with 3 file(s) remaining
Completed 68.2 MiB/233.2 MiB (36.7 MiB/s) with 3 file(s) remaining
Completed 68.4 MiB/233.2 MiB (36.7 MiB/s) with 3 file(s) remaining
Completed 68.7 MiB/233.2 MiB (36.8 MiB/s) with 3 file(s) remaining
Completed 68.9 MiB/233.2 MiB (36.6 MiB/s) with 3 file(s) remaining
Completed 69.2 MiB/233.2 MiB (36.8 MiB/s) with 3 file(s) remaining
Completed 69.4 MiB/233.2 MiB (36.5 MiB/s) with 3 file(s) remaining
Completed 69.7 MiB/233.2 MiB (36.6 MiB/s) with 3 file(s) remaining
Completed 69.9 MiB/233.2 MiB (36.7 MiB/s) with 3 file(s) remaining
Completed 70.2 MiB/233.2 MiB (36.8 MiB/s) with 3 file(s) remaining
Completed 70.4 MiB/233.2 MiB (36.9 MiB/s) with 3 file(s) remaining
Completed 70.7 MiB/233.2 MiB (37.0 MiB/s) with 3 file(s) remaining
Completed 70.9 MiB/233.2 MiB (37.1 MiB/s) with 3 file(s) remaining
Completed 71.2 MiB/233.2 MiB (37.1 MiB/s) with 3 file(s) remaining
Completed 71.4 MiB/233.2 MiB (37.2 MiB/s) with 3 file(s) remaining
Completed 71.7 MiB/233.2 MiB (37.3 MiB/s) with 3 file(s) remaining
Completed 71.9 MiB/233.2 MiB (37.1 MiB/s) with 3 file(s) remaining
Completed 72.2 MiB/233.2 MiB (37.2 MiB/s) with 3 file(s) remaining
Completed 72.4 MiB/233.2 MiB (37.3 MiB/s) with 3 file(s) remaining
Completed 72.7 MiB/233.2 MiB (37.2 MiB/s) with 3 file(s) remaining
Completed 72.9 MiB/233.2 MiB (37.2 MiB/s) with 3 file(s) remaining
Completed 73.2 MiB/233.2 MiB (37.3 MiB/s) with 3 file(s) remaining
Completed 73.4 MiB/233.2 MiB (37.3 MiB/s) with 3 file(s) remaining
Completed 73.7 MiB/233.2 MiB (37.2 MiB/s) with 3 file(s) remaining
Completed 73.9 MiB/233.2 MiB (37.3 MiB/s) with 3 file(s) remaining
Completed 74.2 MiB/233.2 MiB (37.4 MiB/s) with 3 file(s) remaining
Completed 74.4 MiB/233.2 MiB (37.5 MiB/s) with 3 file(s) remaining
Completed 74.7 MiB/233.2 MiB (37.6 MiB/s) with 3 file(s) remaining
Completed 74.9 MiB/233.2 MiB (37.7 MiB/s) with 3 file(s) remaining
Completed 75.2 MiB/233.2 MiB (37.8 MiB/s) with 3 file(s) remaining
Completed 75.4 MiB/233.2 MiB (37.9 MiB/s) with 3 file(s) remaining
Completed 75.7 MiB/233.2 MiB (37.9 MiB/s) with 3 file(s) remaining
Completed 75.9 MiB/233.2 MiB (38.0 MiB/s) with 3 file(s) remaining
Completed 76.2 MiB/233.2 MiB (38.0 MiB/s) with 3 file(s) remaining
Completed 76.4 MiB/233.2 MiB (38.0 MiB/s) with 3 file(s) remaining
Completed 76.7 MiB/233.2 MiB (38.1 MiB/s) with 3 file(s) remaining
Completed 76.9 MiB/233.2 MiB (38.1 MiB/s) with 3 file(s) remaining
Completed 77.2 MiB/233.2 MiB (38.2 MiB/s) with 3 file(s) remaining
Completed 77.4 MiB/233.2 MiB (38.1 MiB/s) with 3 file(s) remaining
Completed 77.7 MiB/233.2 MiB (38.2 MiB/s) with 3 file(s) remaining
Completed 77.9 MiB/233.2 MiB (38.3 MiB/s) with 3 file(s) remaining
Completed 78.2 MiB/233.2 MiB (38.3 MiB/s) with 3 file(s) remaining
Completed 78.4 MiB/233.2 MiB (38.3 MiB/s) with 3 file(s) remaining
Completed 78.7 MiB/233.2 MiB (38.2 MiB/s) with 3 file(s) remaining
Completed 78.9 MiB/233.2 MiB (38.3 MiB/s) with 3 file(s) remaining
Completed 79.2 MiB/233.2 MiB (38.3 MiB/s) with 3 file(s) remaining
Completed 79.4 MiB/233.2 MiB (38.4 MiB/s) with 3 file(s) remaining
Completed 79.7 MiB/233.2 MiB (38.4 MiB/s) with 3 file(s) remaining
Completed 79.9 MiB/233.2 MiB (38.3 MiB/s) with 3 file(s) remaining
Completed 80.2 MiB/233.2 MiB (38.4 MiB/s) with 3 file(s) remaining
Completed 80.4 MiB/233.2 MiB (38.5 MiB/s) with 3 file(s) remaining
Completed 80.7 MiB/233.2 MiB (38.7 MiB/s) with 3 file(s) remaining
Completed 80.9 MiB/233.2 MiB (38.8 MiB/s) with 3 file(s) remaining
Completed 81.2 MiB/233.2 MiB (38.9 MiB/s) with 3 file(s) remaining
Completed 81.4 MiB/233.2 MiB (39.0 MiB/s) with 3 file(s) remaining
Completed 81.7 MiB/233.2 MiB (39.1 MiB/s) with 3 file(s) remaining
Completed 81.9 MiB/233.2 MiB (39.2 MiB/s) with 3 file(s) remaining
Completed 82.2 MiB/233.2 MiB (39.1 MiB/s) with 3 file(s) remaining
Completed 82.4 MiB/233.2 MiB (39.2 MiB/s) with 3 file(s) remaining
Completed 82.7 MiB/233.2 MiB (39.3 MiB/s) with 3 file(s) remaining
Completed 82.9 MiB/233.2 MiB (39.3 MiB/s) with 3 file(s) remaining
Completed 83.2 MiB/233.2 MiB (39.3 MiB/s) with 3 file(s) remaining
Completed 83.4 MiB/233.2 MiB (39.4 MiB/s) with 3 file(s) remaining
Completed 83.7 MiB/233.2 MiB (39.5 MiB/s) with 3 file(s) remaining
Completed 83.9 MiB/233.2 MiB (39.5 MiB/s) with 3 file(s) remaining
Completed 84.2 MiB/233.2 MiB (39.5 MiB/s) with 3 file(s) remaining
Completed 84.4 MiB/233.2 MiB (39.5 MiB/s) with 3 file(s) remaining
Completed 84.7 MiB/233.2 MiB (39.6 MiB/s) with 3 file(s) remaining
Completed 84.9 MiB/233.2 MiB (39.7 MiB/s) with 3 file(s) remaining
Completed 85.2 MiB/233.2 MiB (39.7 MiB/s) with 3 file(s) remaining
Completed 85.4 MiB/233.2 MiB (39.7 MiB/s) with 3 file(s) remaining
Completed 85.7 MiB/233.2 MiB (39.7 MiB/s) with 3 file(s) remaining
Completed 85.9 MiB/233.2 MiB (39.9 MiB/s) with 3 file(s) remaining
Completed 86.2 MiB/233.2 MiB (40.0 MiB/s) with 3 file(s) remaining
Completed 86.4 MiB/233.2 MiB (40.1 MiB/s) with 3 file(s) remaining
Completed 86.7 MiB/233.2 MiB (40.2 MiB/s) with 3 file(s) remaining
Completed 86.9 MiB/233.2 MiB (40.3 MiB/s) with 3 file(s) remaining
Completed 87.2 MiB/233.2 MiB (40.4 MiB/s) with 3 file(s) remaining
Completed 87.4 MiB/233.2 MiB (40.3 MiB/s) with 3 file(s) remaining
Completed 87.7 MiB/233.2 MiB (40.4 MiB/s) with 3 file(s) remaining
Completed 87.9 MiB/233.2 MiB (40.4 MiB/s) with 3 file(s) remaining
Completed 88.2 MiB/233.2 MiB (40.4 MiB/s) with 3 file(s) remaining
Completed 88.4 MiB/233.2 MiB (40.5 MiB/s) with 3 file(s) remaining
Completed 88.7 MiB/233.2 MiB (40.3 MiB/s) with 3 file(s) remaining
Completed 88.9 MiB/233.2 MiB (40.4 MiB/s) with 3 file(s) remaining
Completed 89.2 MiB/233.2 MiB (40.5 MiB/s) with 3 file(s) remaining
Completed 89.4 MiB/233.2 MiB (40.3 MiB/s) with 3 file(s) remaining
Completed 89.7 MiB/233.2 MiB (40.4 MiB/s) with 3 file(s) remaining
Completed 89.9 MiB/233.2 MiB (40.5 MiB/s) with 3 file(s) remaining
Completed 90.2 MiB/233.2 MiB (40.6 MiB/s) with 3 file(s) remaining
Completed 90.4 MiB/233.2 MiB (40.5 MiB/s) with 3 file(s) remaining
Completed 90.7 MiB/233.2 MiB (40.5 MiB/s) with 3 file(s) remaining
Completed 90.9 MiB/233.2 MiB (40.6 MiB/s) with 3 file(s) remaining
Completed 91.2 MiB/233.2 MiB (40.7 MiB/s) with 3 file(s) remaining
Completed 91.4 MiB/233.2 MiB (40.6 MiB/s) with 3 file(s) remaining
Completed 91.7 MiB/233.2 MiB (40.6 MiB/s) with 3 file(s) remaining
Completed 91.9 MiB/233.2 MiB (40.5 MiB/s) with 3 file(s) remaining
Completed 92.2 MiB/233.2 MiB (40.6 MiB/s) with 3 file(s) remaining
Completed 92.4 MiB/233.2 MiB (40.7 MiB/s) with 3 file(s) remaining
Completed 92.7 MiB/233.2 MiB (40.6 MiB/s) with 3 file(s) remaining
Completed 92.9 MiB/233.2 MiB (40.6 MiB/s) with 3 file(s) remaining
Completed 93.2 MiB/233.2 MiB (40.7 MiB/s) with 3 file(s) remaining
Completed 93.4 MiB/233.2 MiB (40.8 MiB/s) with 3 file(s) remaining
Completed 93.7 MiB/233.2 MiB (40.9 MiB/s) with 3 file(s) remaining
Completed 93.9 MiB/233.2 MiB (41.0 MiB/s) with 3 file(s) remaining
Completed 94.2 MiB/233.2 MiB (41.0 MiB/s) with 3 file(s) remaining
Completed 94.4 MiB/233.2 MiB (41.0 MiB/s) with 3 file(s) remaining
Completed 94.7 MiB/233.2 MiB (41.0 MiB/s) with 3 file(s) remaining
Completed 94.9 MiB/233.2 MiB (41.0 MiB/s) with 3 file(s) remaining
Completed 95.2 MiB/233.2 MiB (41.1 MiB/s) with 3 file(s) remaining
Completed 95.4 MiB/233.2 MiB (41.2 MiB/s) with 3 file(s) remaining
Completed 95.7 MiB/233.2 MiB (41.2 MiB/s) with 3 file(s) remaining
Completed 95.9 MiB/233.2 MiB (41.2 MiB/s) with 3 file(s) remaining
Completed 96.2 MiB/233.2 MiB (41.3 MiB/s) with 3 file(s) remaining
Completed 96.4 MiB/233.2 MiB (41.2 MiB/s) with 3 file(s) remaining
Completed 96.7 MiB/233.2 MiB (41.2 MiB/s) with 3 file(s) remaining
Completed 96.9 MiB/233.2 MiB (41.3 MiB/s) with 3 file(s) remaining
Completed 97.2 MiB/233.2 MiB (41.4 MiB/s) with 3 file(s) remaining
Completed 97.4 MiB/233.2 MiB (41.4 MiB/s) with 3 file(s) remaining
Completed 97.7 MiB/233.2 MiB (41.3 MiB/s) with 3 file(s) remaining
Completed 97.9 MiB/233.2 MiB (41.4 MiB/s) with 3 file(s) remaining
Completed 98.2 MiB/233.2 MiB (41.4 MiB/s) with 3 file(s) remaining
Completed 98.4 MiB/233.2 MiB (41.3 MiB/s) with 3 file(s) remaining
Completed 98.7 MiB/233.2 MiB (41.3 MiB/s) with 3 file(s) remaining
Completed 98.9 MiB/233.2 MiB (41.4 MiB/s) with 3 file(s) remaining
Completed 99.2 MiB/233.2 MiB (41.3 MiB/s) with 3 file(s) remaining
Completed 99.4 MiB/233.2 MiB (41.4 MiB/s) with 3 file(s) remaining
Completed 99.7 MiB/233.2 MiB (41.5 MiB/s) with 3 file(s) remaining
Completed 99.9 MiB/233.2 MiB (41.2 MiB/s) with 3 file(s) remaining
Completed 100.2 MiB/233.2 MiB (41.3 MiB/s) with 3 file(s) remaining
Completed 100.4 MiB/233.2 MiB (41.4 MiB/s) with 3 file(s) remaining
Completed 100.7 MiB/233.2 MiB (41.4 MiB/s) with 3 file(s) remaining
Completed 100.9 MiB/233.2 MiB (41.4 MiB/s) with 3 file(s) remaining
Completed 101.2 MiB/233.2 MiB (41.5 MiB/s) with 3 file(s) remaining
Completed 101.4 MiB/233.2 MiB (41.4 MiB/s) with 3 file(s) remaining
Completed 101.7 MiB/233.2 MiB (41.3 MiB/s) with 3 file(s) remaining
Completed 101.9 MiB/233.2 MiB (41.4 MiB/s) with 3 file(s) remaining
Completed 102.2 MiB/233.2 MiB (41.5 MiB/s) with 3 file(s) remaining
Completed 102.4 MiB/233.2 MiB (41.5 MiB/s) with 3 file(s) remaining
Completed 102.7 MiB/233.2 MiB (41.6 MiB/s) with 3 file(s) remaining
Completed 102.9 MiB/233.2 MiB (41.4 MiB/s) with 3 file(s) remaining
Completed 103.2 MiB/233.2 MiB (41.5 MiB/s) with 3 file(s) remaining
Completed 103.4 MiB/233.2 MiB (41.4 MiB/s) with 3 file(s) remaining
Completed 103.7 MiB/233.2 MiB (41.3 MiB/s) with 3 file(s) remaining
Completed 103.9 MiB/233.2 MiB (41.2 MiB/s) with 3 file(s) remaining
Completed 104.2 MiB/233.2 MiB (41.3 MiB/s) with 3 file(s) remaining
Completed 104.4 MiB/233.2 MiB (41.4 MiB/s) with 3 file(s) remaining
Completed 104.7 MiB/233.2 MiB (41.5 MiB/s) with 3 file(s) remaining
Completed 104.9 MiB/233.2 MiB (41.6 MiB/s) with 3 file(s) remaining
Completed 105.2 MiB/233.2 MiB (41.7 MiB/s) with 3 file(s) remaining
Completed 105.4 MiB/233.2 MiB (41.6 MiB/s) with 3 file(s) remaining
Completed 105.7 MiB/233.2 MiB (41.6 MiB/s) with 3 file(s) remaining
Completed 105.9 MiB/233.2 MiB (41.6 MiB/s) with 3 file(s) remaining
Completed 106.2 MiB/233.2 MiB (41.4 MiB/s) with 3 file(s) remaining
Completed 106.4 MiB/233.2 MiB (41.5 MiB/s) with 3 file(s) remaining
Completed 106.7 MiB/233.2 MiB (41.5 MiB/s) with 3 file(s) remaining
Completed 106.9 MiB/233.2 MiB (41.5 MiB/s) with 3 file(s) remaining
Completed 107.2 MiB/233.2 MiB (41.6 MiB/s) with 3 file(s) remaining
Completed 107.4 MiB/233.2 MiB (41.6 MiB/s) with 3 file(s) remaining
Completed 107.7 MiB/233.2 MiB (41.5 MiB/s) with 3 file(s) remaining
Completed 107.9 MiB/233.2 MiB (41.5 MiB/s) with 3 file(s) remaining
Completed 108.2 MiB/233.2 MiB (41.5 MiB/s) with 3 file(s) remaining
Completed 108.4 MiB/233.2 MiB (41.6 MiB/s) with 3 file(s) remaining
Completed 108.7 MiB/233.2 MiB (41.5 MiB/s) with 3 file(s) remaining
Completed 108.9 MiB/233.2 MiB (41.5 MiB/s) with 3 file(s) remaining
Completed 109.2 MiB/233.2 MiB (41.5 MiB/s) with 3 file(s) remaining
Completed 109.4 MiB/233.2 MiB (41.6 MiB/s) with 3 file(s) remaining
Completed 109.7 MiB/233.2 MiB (41.4 MiB/s) with 3 file(s) remaining
Completed 109.9 MiB/233.2 MiB (41.5 MiB/s) with 3 file(s) remaining
Completed 110.2 MiB/233.2 MiB (41.5 MiB/s) with 3 file(s) remaining
Completed 110.4 MiB/233.2 MiB (41.4 MiB/s) with 3 file(s) remaining
Completed 110.7 MiB/233.2 MiB (41.3 MiB/s) with 3 file(s) remaining
Completed 110.9 MiB/233.2 MiB (41.3 MiB/s) with 3 file(s) remaining
Completed 111.2 MiB/233.2 MiB (41.4 MiB/s) with 3 file(s) remaining
Completed 111.4 MiB/233.2 MiB (41.3 MiB/s) with 3 file(s) remaining
Completed 111.7 MiB/233.2 MiB (41.2 MiB/s) with 3 file(s) remaining
Completed 111.9 MiB/233.2 MiB (41.3 MiB/s) with 3 file(s) remaining
Completed 112.2 MiB/233.2 MiB (41.3 MiB/s) with 3 file(s) remaining
Completed 112.4 MiB/233.2 MiB (41.3 MiB/s) with 3 file(s) remaining
Completed 112.7 MiB/233.2 MiB (41.3 MiB/s) with 3 file(s) remaining
Completed 112.9 MiB/233.2 MiB (41.4 MiB/s) with 3 file(s) remaining
Completed 113.2 MiB/233.2 MiB (41.4 MiB/s) with 3 file(s) remaining
Completed 113.4 MiB/233.2 MiB (41.4 MiB/s) with 3 file(s) remaining
Completed 113.7 MiB/233.2 MiB (41.5 MiB/s) with 3 file(s) remaining
Completed 113.9 MiB/233.2 MiB (41.4 MiB/s) with 3 file(s) remaining
Completed 114.2 MiB/233.2 MiB (41.2 MiB/s) with 3 file(s) remaining
Completed 114.4 MiB/233.2 MiB (41.3 MiB/s) with 3 file(s) remaining
Completed 114.7 MiB/233.2 MiB (41.4 MiB/s) with 3 file(s) remaining
Completed 114.9 MiB/233.2 MiB (41.4 MiB/s) with 3 file(s) remaining
Completed 115.2 MiB/233.2 MiB (41.4 MiB/s) with 3 file(s) remaining
Completed 115.4 MiB/233.2 MiB (41.4 MiB/s) with 3 file(s) remaining
Completed 115.7 MiB/233.2 MiB (41.5 MiB/s) with 3 file(s) remaining
Completed 115.9 MiB/233.2 MiB (41.5 MiB/s) with 3 file(s) remaining
Completed 116.2 MiB/233.2 MiB (41.5 MiB/s) with 3 file(s) remaining
Completed 116.4 MiB/233.2 MiB (41.5 MiB/s) with 3 file(s) remaining
Completed 116.7 MiB/233.2 MiB (41.6 MiB/s) with 3 file(s) remaining
Completed 116.9 MiB/233.2 MiB (41.6 MiB/s) with 3 file(s) remaining
Completed 117.2 MiB/233.2 MiB (41.6 MiB/s) with 3 file(s) remaining
Completed 117.4 MiB/233.2 MiB (41.5 MiB/s) with 3 file(s) remaining
Completed 117.7 MiB/233.2 MiB (41.5 MiB/s) with 3 file(s) remaining
Completed 117.9 MiB/233.2 MiB (41.5 MiB/s) with 3 file(s) remaining
Completed 118.2 MiB/233.2 MiB (41.6 MiB/s) with 3 file(s) remaining
Completed 118.4 MiB/233.2 MiB (41.5 MiB/s) with 3 file(s) remaining
Completed 118.7 MiB/233.2 MiB (41.6 MiB/s) with 3 file(s) remaining
Completed 118.9 MiB/233.2 MiB (41.4 MiB/s) with 3 file(s) remaining
Completed 119.2 MiB/233.2 MiB (41.5 MiB/s) with 3 file(s) remaining
Completed 119.4 MiB/233.2 MiB (41.5 MiB/s) with 3 file(s) remaining
Completed 119.7 MiB/233.2 MiB (41.5 MiB/s) with 3 file(s) remaining
Completed 119.9 MiB/233.2 MiB (41.5 MiB/s) with 3 file(s) remaining
Completed 120.2 MiB/233.2 MiB (41.5 MiB/s) with 3 file(s) remaining
Completed 120.4 MiB/233.2 MiB (41.6 MiB/s) with 3 file(s) remaining
Completed 120.7 MiB/233.2 MiB (41.7 MiB/s) with 3 file(s) remaining
Completed 120.9 MiB/233.2 MiB (41.8 MiB/s) with 3 file(s) remaining
Completed 121.2 MiB/233.2 MiB (41.8 MiB/s) with 3 file(s) remaining
Completed 121.4 MiB/233.2 MiB (41.8 MiB/s) with 3 file(s) remaining
Completed 121.7 MiB/233.2 MiB (41.9 MiB/s) with 3 file(s) remaining
Completed 121.9 MiB/233.2 MiB (41.9 MiB/s) with 3 file(s) remaining
Completed 122.2 MiB/233.2 MiB (41.9 MiB/s) with 3 file(s) remaining
Completed 122.4 MiB/233.2 MiB (41.8 MiB/s) with 3 file(s) remaining
Completed 122.7 MiB/233.2 MiB (41.7 MiB/s) with 3 file(s) remaining
Completed 122.9 MiB/233.2 MiB (41.8 MiB/s) with 3 file(s) remaining
Completed 123.2 MiB/233.2 MiB (41.7 MiB/s) with 3 file(s) remaining
Completed 123.4 MiB/233.2 MiB (41.7 MiB/s) with 3 file(s) remaining
Completed 123.7 MiB/233.2 MiB (41.7 MiB/s) with 3 file(s) remaining
Completed 123.9 MiB/233.2 MiB (41.7 MiB/s) with 3 file(s) remaining
Completed 124.2 MiB/233.2 MiB (41.7 MiB/s) with 3 file(s) remaining
Completed 124.4 MiB/233.2 MiB (41.8 MiB/s) with 3 file(s) remaining
Completed 124.7 MiB/233.2 MiB (41.6 MiB/s) with 3 file(s) remaining
Completed 124.9 MiB/233.2 MiB (41.6 MiB/s) with 3 file(s) remaining
Completed 125.2 MiB/233.2 MiB (41.5 MiB/s) with 3 file(s) remaining
Completed 125.4 MiB/233.2 MiB (41.5 MiB/s) with 3 file(s) remaining
Completed 125.7 MiB/233.2 MiB (41.4 MiB/s) with 3 file(s) remaining
Completed 125.9 MiB/233.2 MiB (41.2 MiB/s) with 3 file(s) remaining
Completed 126.2 MiB/233.2 MiB (41.3 MiB/s) with 3 file(s) remaining
Completed 126.4 MiB/233.2 MiB (41.3 MiB/s) with 3 file(s) remaining
Completed 126.7 MiB/233.2 MiB (41.2 MiB/s) with 3 file(s) remaining
Completed 126.9 MiB/233.2 MiB (41.1 MiB/s) with 3 file(s) remaining
Completed 127.2 MiB/233.2 MiB (41.1 MiB/s) with 3 file(s) remaining
Completed 127.4 MiB/233.2 MiB (41.1 MiB/s) with 3 file(s) remaining
Completed 127.7 MiB/233.2 MiB (41.1 MiB/s) with 3 file(s) remaining
Completed 127.9 MiB/233.2 MiB (41.2 MiB/s) with 3 file(s) remaining
Completed 128.2 MiB/233.2 MiB (41.2 MiB/s) with 3 file(s) remaining
Completed 128.4 MiB/233.2 MiB (41.3 MiB/s) with 3 file(s) remaining
Completed 128.7 MiB/233.2 MiB (41.4 MiB/s) with 3 file(s) remaining
Completed 128.9 MiB/233.2 MiB (41.4 MiB/s) with 3 file(s) remaining
Completed 129.2 MiB/233.2 MiB (41.5 MiB/s) with 3 file(s) remaining
Completed 129.4 MiB/233.2 MiB (41.5 MiB/s) with 3 file(s) remaining
Completed 129.7 MiB/233.2 MiB (41.5 MiB/s) with 3 file(s) remaining
Completed 129.9 MiB/233.2 MiB (41.5 MiB/s) with 3 file(s) remaining
Completed 130.2 MiB/233.2 MiB (41.4 MiB/s) with 3 file(s) remaining
Completed 130.4 MiB/233.2 MiB (41.5 MiB/s) with 3 file(s) remaining
Completed 130.7 MiB/233.2 MiB (41.6 MiB/s) with 3 file(s) remaining
Completed 130.9 MiB/233.2 MiB (41.6 MiB/s) with 3 file(s) remaining
Completed 131.2 MiB/233.2 MiB (41.5 MiB/s) with 3 file(s) remaining
Completed 131.4 MiB/233.2 MiB (41.6 MiB/s) with 3 file(s) remaining
Completed 131.7 MiB/233.2 MiB (41.6 MiB/s) with 3 file(s) remaining
Completed 131.9 MiB/233.2 MiB (41.7 MiB/s) with 3 file(s) remaining
Completed 132.2 MiB/233.2 MiB (41.5 MiB/s) with 3 file(s) remaining
Completed 132.4 MiB/233.2 MiB (41.5 MiB/s) with 3 file(s) remaining
Completed 132.7 MiB/233.2 MiB (41.6 MiB/s) with 3 file(s) remaining
Completed 132.9 MiB/233.2 MiB (41.7 MiB/s) with 3 file(s) remaining
Completed 133.2 MiB/233.2 MiB (41.7 MiB/s) with 3 file(s) remaining
Completed 133.4 MiB/233.2 MiB (41.6 MiB/s) with 3 file(s) remaining
Completed 133.7 MiB/233.2 MiB (41.7 MiB/s) with 3 file(s) remaining
Completed 133.9 MiB/233.2 MiB (41.7 MiB/s) with 3 file(s) remaining
Completed 134.2 MiB/233.2 MiB (41.7 MiB/s) with 3 file(s) remaining
Completed 134.4 MiB/233.2 MiB (41.7 MiB/s) with 3 file(s) remaining
Completed 134.7 MiB/233.2 MiB (41.7 MiB/s) with 3 file(s) remaining
Completed 134.9 MiB/233.2 MiB (41.8 MiB/s) with 3 file(s) remaining
Completed 135.2 MiB/233.2 MiB (41.8 MiB/s) with 3 file(s) remaining
Completed 135.4 MiB/233.2 MiB (41.8 MiB/s) with 3 file(s) remaining
Completed 135.7 MiB/233.2 MiB (41.8 MiB/s) with 3 file(s) remaining
Completed 135.9 MiB/233.2 MiB (41.9 MiB/s) with 3 file(s) remaining
Completed 136.2 MiB/233.2 MiB (41.9 MiB/s) with 3 file(s) remaining
Completed 136.4 MiB/233.2 MiB (42.0 MiB/s) with 3 file(s) remaining
Completed 136.7 MiB/233.2 MiB (41.9 MiB/s) with 3 file(s) remaining
Completed 136.9 MiB/233.2 MiB (41.9 MiB/s) with 3 file(s) remaining
Completed 137.2 MiB/233.2 MiB (42.0 MiB/s) with 3 file(s) remaining
Completed 137.4 MiB/233.2 MiB (42.0 MiB/s) with 3 file(s) remaining
Completed 137.7 MiB/233.2 MiB (42.0 MiB/s) with 3 file(s) remaining
Completed 137.9 MiB/233.2 MiB (41.9 MiB/s) with 3 file(s) remaining
Completed 138.2 MiB/233.2 MiB (41.9 MiB/s) with 3 file(s) remaining
Completed 138.4 MiB/233.2 MiB (42.0 MiB/s) with 3 file(s) remaining
Completed 138.7 MiB/233.2 MiB (41.9 MiB/s) with 3 file(s) remaining
Completed 138.9 MiB/233.2 MiB (41.9 MiB/s) with 3 file(s) remaining
Completed 139.2 MiB/233.2 MiB (42.0 MiB/s) with 3 file(s) remaining
Completed 139.4 MiB/233.2 MiB (42.1 MiB/s) with 3 file(s) remaining
Completed 139.7 MiB/233.2 MiB (42.1 MiB/s) with 3 file(s) remaining
Completed 139.9 MiB/233.2 MiB (42.0 MiB/s) with 3 file(s) remaining
Completed 140.2 MiB/233.2 MiB (42.0 MiB/s) with 3 file(s) remaining
Completed 140.4 MiB/233.2 MiB (42.0 MiB/s) with 3 file(s) remaining
Completed 140.7 MiB/233.2 MiB (42.1 MiB/s) with 3 file(s) remaining
Completed 140.9 MiB/233.2 MiB (42.0 MiB/s) with 3 file(s) remaining
Completed 141.2 MiB/233.2 MiB (42.1 MiB/s) with 3 file(s) remaining
Completed 141.4 MiB/233.2 MiB (42.1 MiB/s) with 3 file(s) remaining
Completed 141.7 MiB/233.2 MiB (41.9 MiB/s) with 3 file(s) remaining
Completed 141.9 MiB/233.2 MiB (42.0 MiB/s) with 3 file(s) remaining
Completed 142.2 MiB/233.2 MiB (42.0 MiB/s) with 3 file(s) remaining
Completed 142.4 MiB/233.2 MiB (42.0 MiB/s) with 3 file(s) remaining
Completed 142.7 MiB/233.2 MiB (42.0 MiB/s) with 3 file(s) remaining
Completed 142.9 MiB/233.2 MiB (42.0 MiB/s) with 3 file(s) remaining
Completed 143.2 MiB/233.2 MiB (42.0 MiB/s) with 3 file(s) remaining
Completed 143.4 MiB/233.2 MiB (42.0 MiB/s) with 3 file(s) remaining
Completed 143.7 MiB/233.2 MiB (42.0 MiB/s) with 3 file(s) remaining
Completed 143.9 MiB/233.2 MiB (42.0 MiB/s) with 3 file(s) remaining
Completed 144.2 MiB/233.2 MiB (42.0 MiB/s) with 3 file(s) remaining
Completed 144.4 MiB/233.2 MiB (42.0 MiB/s) with 3 file(s) remaining
Completed 144.7 MiB/233.2 MiB (41.9 MiB/s) with 3 file(s) remaining
Completed 144.9 MiB/233.2 MiB (41.9 MiB/s) with 3 file(s) remaining
Completed 145.2 MiB/233.2 MiB (41.9 MiB/s) with 3 file(s) remaining
Completed 145.4 MiB/233.2 MiB (41.8 MiB/s) with 3 file(s) remaining
Completed 145.7 MiB/233.2 MiB (41.8 MiB/s) with 3 file(s) remaining
Completed 145.9 MiB/233.2 MiB (41.8 MiB/s) with 3 file(s) remaining
Completed 146.2 MiB/233.2 MiB (41.8 MiB/s) with 3 file(s) remaining
Completed 146.4 MiB/233.2 MiB (41.7 MiB/s) with 3 file(s) remaining
Completed 146.7 MiB/233.2 MiB (41.8 MiB/s) with 3 file(s) remaining
Completed 146.9 MiB/233.2 MiB (41.8 MiB/s) with 3 file(s) remaining
Completed 147.2 MiB/233.2 MiB (41.7 MiB/s) with 3 file(s) remaining
Completed 147.4 MiB/233.2 MiB (41.7 MiB/s) with 3 file(s) remaining
Completed 147.7 MiB/233.2 MiB (41.7 MiB/s) with 3 file(s) remaining
Completed 147.9 MiB/233.2 MiB (41.7 MiB/s) with 3 file(s) remaining
Completed 148.2 MiB/233.2 MiB (41.6 MiB/s) with 3 file(s) remaining
Completed 148.4 MiB/233.2 MiB (41.6 MiB/s) with 3 file(s) remaining
Completed 148.7 MiB/233.2 MiB (41.5 MiB/s) with 3 file(s) remaining
Completed 148.9 MiB/233.2 MiB (41.4 MiB/s) with 3 file(s) remaining
Completed 149.2 MiB/233.2 MiB (41.4 MiB/s) with 3 file(s) remaining
Completed 149.4 MiB/233.2 MiB (41.3 MiB/s) with 3 file(s) remaining
Completed 149.7 MiB/233.2 MiB (41.4 MiB/s) with 3 file(s) remaining
Completed 149.9 MiB/233.2 MiB (41.2 MiB/s) with 3 file(s) remaining
Completed 150.2 MiB/233.2 MiB (41.2 MiB/s) with 3 file(s) remaining
Completed 150.4 MiB/233.2 MiB (40.9 MiB/s) with 3 file(s) remaining
Completed 150.7 MiB/233.2 MiB (40.8 MiB/s) with 3 file(s) remaining
Completed 150.9 MiB/233.2 MiB (40.4 MiB/s) with 3 file(s) remaining
Completed 151.2 MiB/233.2 MiB (40.3 MiB/s) with 3 file(s) remaining
Completed 151.4 MiB/233.2 MiB (38.4 MiB/s) with 3 file(s) remaining
Completed 151.7 MiB/233.2 MiB (38.5 MiB/s) with 3 file(s) remaining
Completed 151.9 MiB/233.2 MiB (38.6 MiB/s) with 3 file(s) remaining
Completed 152.2 MiB/233.2 MiB (38.6 MiB/s) with 3 file(s) remaining
Completed 152.4 MiB/233.2 MiB (38.7 MiB/s) with 3 file(s) remaining
Completed 152.7 MiB/233.2 MiB (38.6 MiB/s) with 3 file(s) remaining
Completed 152.9 MiB/233.2 MiB (38.5 MiB/s) with 3 file(s) remaining
Completed 153.2 MiB/233.2 MiB (38.3 MiB/s) with 3 file(s) remaining
Completed 153.4 MiB/233.2 MiB (38.2 MiB/s) with 3 file(s) remaining
Completed 153.7 MiB/233.2 MiB (38.3 MiB/s) with 3 file(s) remaining
Completed 153.9 MiB/233.2 MiB (38.3 MiB/s) with 3 file(s) remaining
Completed 154.2 MiB/233.2 MiB (38.4 MiB/s) with 3 file(s) remaining
Completed 154.4 MiB/233.2 MiB (38.4 MiB/s) with 3 file(s) remaining
Completed 154.7 MiB/233.2 MiB (38.4 MiB/s) with 3 file(s) remaining
Completed 154.9 MiB/233.2 MiB (38.5 MiB/s) with 3 file(s) remaining
Completed 155.2 MiB/233.2 MiB (38.4 MiB/s) with 3 file(s) remaining
Completed 155.4 MiB/233.2 MiB (38.4 MiB/s) with 3 file(s) remaining
Completed 155.7 MiB/233.2 MiB (38.4 MiB/s) with 3 file(s) remaining
Completed 155.9 MiB/233.2 MiB (38.5 MiB/s) with 3 file(s) remaining
Completed 156.2 MiB/233.2 MiB (38.5 MiB/s) with 3 file(s) remaining
Completed 156.4 MiB/233.2 MiB (38.5 MiB/s) with 3 file(s) remaining
Completed 156.7 MiB/233.2 MiB (38.5 MiB/s) with 3 file(s) remaining
Completed 156.9 MiB/233.2 MiB (38.5 MiB/s) with 3 file(s) remaining
Completed 157.2 MiB/233.2 MiB (38.5 MiB/s) with 3 file(s) remaining
Completed 157.4 MiB/233.2 MiB (38.5 MiB/s) with 3 file(s) remaining
Completed 157.7 MiB/233.2 MiB (38.5 MiB/s) with 3 file(s) remaining
Completed 157.9 MiB/233.2 MiB (38.5 MiB/s) with 3 file(s) remaining
Completed 158.2 MiB/233.2 MiB (38.4 MiB/s) with 3 file(s) remaining
Completed 158.4 MiB/233.2 MiB (38.4 MiB/s) with 3 file(s) remaining
Completed 158.7 MiB/233.2 MiB (38.4 MiB/s) with 3 file(s) remaining
Completed 158.9 MiB/233.2 MiB (38.4 MiB/s) with 3 file(s) remaining
Completed 159.2 MiB/233.2 MiB (38.4 MiB/s) with 3 file(s) remaining
Completed 159.4 MiB/233.2 MiB (38.4 MiB/s) with 3 file(s) remaining
Completed 159.7 MiB/233.2 MiB (38.5 MiB/s) with 3 file(s) remaining
Completed 159.9 MiB/233.2 MiB (38.5 MiB/s) with 3 file(s) remaining
Completed 160.2 MiB/233.2 MiB (38.6 MiB/s) with 3 file(s) remaining
Completed 160.4 MiB/233.2 MiB (38.6 MiB/s) with 3 file(s) remaining
Completed 160.7 MiB/233.2 MiB (38.6 MiB/s) with 3 file(s) remaining
Completed 160.9 MiB/233.2 MiB (38.6 MiB/s) with 3 file(s) remaining
Completed 161.2 MiB/233.2 MiB (38.7 MiB/s) with 3 file(s) remaining
Completed 161.4 MiB/233.2 MiB (38.6 MiB/s) with 3 file(s) remaining
Completed 161.7 MiB/233.2 MiB (38.6 MiB/s) with 3 file(s) remaining
Completed 161.9 MiB/233.2 MiB (38.7 MiB/s) with 3 file(s) remaining
Completed 162.2 MiB/233.2 MiB (38.7 MiB/s) with 3 file(s) remaining
Completed 162.4 MiB/233.2 MiB (38.8 MiB/s) with 3 file(s) remaining
Completed 162.7 MiB/233.2 MiB (38.8 MiB/s) with 3 file(s) remaining
Completed 162.9 MiB/233.2 MiB (38.9 MiB/s) with 3 file(s) remaining
Completed 163.2 MiB/233.2 MiB (38.9 MiB/s) with 3 file(s) remaining
Completed 163.4 MiB/233.2 MiB (38.9 MiB/s) with 3 file(s) remaining
Completed 163.7 MiB/233.2 MiB (38.9 MiB/s) with 3 file(s) remaining
Completed 163.9 MiB/233.2 MiB (39.0 MiB/s) with 3 file(s) remaining
Completed 164.2 MiB/233.2 MiB (38.9 MiB/s) with 3 file(s) remaining
Completed 164.4 MiB/233.2 MiB (39.0 MiB/s) with 3 file(s) remaining
Completed 164.7 MiB/233.2 MiB (38.9 MiB/s) with 3 file(s) remaining
Completed 164.9 MiB/233.2 MiB (39.0 MiB/s) with 3 file(s) remaining
Completed 165.2 MiB/233.2 MiB (39.0 MiB/s) with 3 file(s) remaining
Completed 165.4 MiB/233.2 MiB (38.9 MiB/s) with 3 file(s) remaining
Completed 165.7 MiB/233.2 MiB (38.9 MiB/s) with 3 file(s) remaining
Completed 165.9 MiB/233.2 MiB (39.0 MiB/s) with 3 file(s) remaining
Completed 166.2 MiB/233.2 MiB (39.0 MiB/s) with 3 file(s) remaining
Completed 166.4 MiB/233.2 MiB (39.0 MiB/s) with 3 file(s) remaining
Completed 166.7 MiB/233.2 MiB (38.9 MiB/s) with 3 file(s) remaining
Completed 166.9 MiB/233.2 MiB (39.0 MiB/s) with 3 file(s) remaining
Completed 167.2 MiB/233.2 MiB (39.0 MiB/s) with 3 file(s) remaining
Completed 167.4 MiB/233.2 MiB (38.9 MiB/s) with 3 file(s) remaining
Completed 167.7 MiB/233.2 MiB (39.0 MiB/s) with 3 file(s) remaining
Completed 167.9 MiB/233.2 MiB (39.0 MiB/s) with 3 file(s) remaining
Completed 168.2 MiB/233.2 MiB (39.0 MiB/s) with 3 file(s) remaining
Completed 168.4 MiB/233.2 MiB (39.0 MiB/s) with 3 file(s) remaining
Completed 168.7 MiB/233.2 MiB (39.0 MiB/s) with 3 file(s) remaining
Completed 168.9 MiB/233.2 MiB (39.0 MiB/s) with 3 file(s) remaining
Completed 169.2 MiB/233.2 MiB (39.0 MiB/s) with 3 file(s) remaining
Completed 169.4 MiB/233.2 MiB (39.0 MiB/s) with 3 file(s) remaining
Completed 169.7 MiB/233.2 MiB (39.0 MiB/s) with 3 file(s) remaining
Completed 169.9 MiB/233.2 MiB (39.0 MiB/s) with 3 file(s) remaining
Completed 170.2 MiB/233.2 MiB (39.0 MiB/s) with 3 file(s) remaining
Completed 170.4 MiB/233.2 MiB (39.0 MiB/s) with 3 file(s) remaining
Completed 170.7 MiB/233.2 MiB (39.0 MiB/s) with 3 file(s) remaining
Completed 170.9 MiB/233.2 MiB (39.1 MiB/s) with 3 file(s) remaining
Completed 171.2 MiB/233.2 MiB (39.1 MiB/s) with 3 file(s) remaining
Completed 171.4 MiB/233.2 MiB (39.2 MiB/s) with 3 file(s) remaining
Completed 171.7 MiB/233.2 MiB (39.2 MiB/s) with 3 file(s) remaining
Completed 171.9 MiB/233.2 MiB (39.3 MiB/s) with 3 file(s) remaining
Completed 172.2 MiB/233.2 MiB (39.3 MiB/s) with 3 file(s) remaining
Completed 172.4 MiB/233.2 MiB (39.3 MiB/s) with 3 file(s) remaining
Completed 172.7 MiB/233.2 MiB (39.3 MiB/s) with 3 file(s) remaining
Completed 172.9 MiB/233.2 MiB (39.4 MiB/s) with 3 file(s) remaining
Completed 173.2 MiB/233.2 MiB (39.3 MiB/s) with 3 file(s) remaining
Completed 173.4 MiB/233.2 MiB (39.3 MiB/s) with 3 file(s) remaining
Completed 173.7 MiB/233.2 MiB (39.4 MiB/s) with 3 file(s) remaining
Completed 173.9 MiB/233.2 MiB (39.3 MiB/s) with 3 file(s) remaining
Completed 174.2 MiB/233.2 MiB (39.4 MiB/s) with 3 file(s) remaining
Completed 174.4 MiB/233.2 MiB (39.4 MiB/s) with 3 file(s) remaining
Completed 174.7 MiB/233.2 MiB (39.4 MiB/s) with 3 file(s) remaining
Completed 174.9 MiB/233.2 MiB (39.4 MiB/s) with 3 file(s) remaining
Completed 175.2 MiB/233.2 MiB (39.4 MiB/s) with 3 file(s) remaining
Completed 175.4 MiB/233.2 MiB (39.4 MiB/s) with 3 file(s) remaining
Completed 175.7 MiB/233.2 MiB (39.4 MiB/s) with 3 file(s) remaining
Completed 175.9 MiB/233.2 MiB (39.4 MiB/s) with 3 file(s) remaining
Completed 176.2 MiB/233.2 MiB (39.3 MiB/s) with 3 file(s) remaining
Completed 176.4 MiB/233.2 MiB (39.3 MiB/s) with 3 file(s) remaining
Completed 176.7 MiB/233.2 MiB (39.2 MiB/s) with 3 file(s) remaining
Completed 176.9 MiB/233.2 MiB (39.3 MiB/s) with 3 file(s) remaining
Completed 177.2 MiB/233.2 MiB (39.3 MiB/s) with 3 file(s) remaining
Completed 177.4 MiB/233.2 MiB (39.3 MiB/s) with 3 file(s) remaining
Completed 177.7 MiB/233.2 MiB (39.4 MiB/s) with 3 file(s) remaining
Completed 177.9 MiB/233.2 MiB (39.4 MiB/s) with 3 file(s) remaining
Completed 178.2 MiB/233.2 MiB (39.5 MiB/s) with 3 file(s) remaining
Completed 178.4 MiB/233.2 MiB (39.5 MiB/s) with 3 file(s) remaining
Completed 178.7 MiB/233.2 MiB (39.5 MiB/s) with 3 file(s) remaining
Completed 178.9 MiB/233.2 MiB (39.5 MiB/s) with 3 file(s) remaining
Completed 179.2 MiB/233.2 MiB (39.5 MiB/s) with 3 file(s) remaining
Completed 179.4 MiB/233.2 MiB (39.6 MiB/s) with 3 file(s) remaining
Completed 179.7 MiB/233.2 MiB (39.5 MiB/s) with 3 file(s) remaining
Completed 179.9 MiB/233.2 MiB (39.5 MiB/s) with 3 file(s) remaining
Completed 180.2 MiB/233.2 MiB (39.5 MiB/s) with 3 file(s) remaining
Completed 180.4 MiB/233.2 MiB (39.5 MiB/s) with 3 file(s) remaining
Completed 180.7 MiB/233.2 MiB (39.5 MiB/s) with 3 file(s) remaining
Completed 180.9 MiB/233.2 MiB (39.5 MiB/s) with 3 file(s) remaining
Completed 181.2 MiB/233.2 MiB (39.5 MiB/s) with 3 file(s) remaining
Completed 181.4 MiB/233.2 MiB (39.5 MiB/s) with 3 file(s) remaining
Completed 181.7 MiB/233.2 MiB (39.4 MiB/s) with 3 file(s) remaining
Completed 181.9 MiB/233.2 MiB (39.3 MiB/s) with 3 file(s) remaining
Completed 182.2 MiB/233.2 MiB (39.3 MiB/s) with 3 file(s) remaining
Completed 182.4 MiB/233.2 MiB (39.2 MiB/s) with 3 file(s) remaining
Completed 182.7 MiB/233.2 MiB (39.1 MiB/s) with 3 file(s) remaining
Completed 182.9 MiB/233.2 MiB (39.1 MiB/s) with 3 file(s) remaining
Completed 183.2 MiB/233.2 MiB (39.1 MiB/s) with 3 file(s) remaining
Completed 183.4 MiB/233.2 MiB (39.1 MiB/s) with 3 file(s) remaining
Completed 183.7 MiB/233.2 MiB (39.0 MiB/s) with 3 file(s) remaining
Completed 183.9 MiB/233.2 MiB (39.1 MiB/s) with 3 file(s) remaining
Completed 184.2 MiB/233.2 MiB (39.0 MiB/s) with 3 file(s) remaining
Completed 184.4 MiB/233.2 MiB (39.0 MiB/s) with 3 file(s) remaining
Completed 184.7 MiB/233.2 MiB (39.0 MiB/s) with 3 file(s) remaining
Completed 184.9 MiB/233.2 MiB (39.0 MiB/s) with 3 file(s) remaining
Completed 185.2 MiB/233.2 MiB (38.9 MiB/s) with 3 file(s) remaining
Completed 185.4 MiB/233.2 MiB (38.9 MiB/s) with 3 file(s) remaining
Completed 185.7 MiB/233.2 MiB (39.0 MiB/s) with 3 file(s) remaining
Completed 185.9 MiB/233.2 MiB (38.9 MiB/s) with 3 file(s) remaining
Completed 186.2 MiB/233.2 MiB (38.9 MiB/s) with 3 file(s) remaining
Completed 186.4 MiB/233.2 MiB (38.9 MiB/s) with 3 file(s) remaining
Completed 186.7 MiB/233.2 MiB (38.9 MiB/s) with 3 file(s) remaining
Completed 186.9 MiB/233.2 MiB (38.9 MiB/s) with 3 file(s) remaining
Completed 187.2 MiB/233.2 MiB (38.9 MiB/s) with 3 file(s) remaining
Completed 187.4 MiB/233.2 MiB (38.9 MiB/s) with 3 file(s) remaining
Completed 187.7 MiB/233.2 MiB (38.9 MiB/s) with 3 file(s) remaining
Completed 187.9 MiB/233.2 MiB (38.9 MiB/s) with 3 file(s) remaining
Completed 188.2 MiB/233.2 MiB (38.9 MiB/s) with 3 file(s) remaining
Completed 188.4 MiB/233.2 MiB (38.9 MiB/s) with 3 file(s) remaining
Completed 188.7 MiB/233.2 MiB (38.9 MiB/s) with 3 file(s) remaining
Completed 188.9 MiB/233.2 MiB (38.9 MiB/s) with 3 file(s) remaining
Completed 189.2 MiB/233.2 MiB (38.8 MiB/s) with 3 file(s) remaining
Completed 189.4 MiB/233.2 MiB (38.8 MiB/s) with 3 file(s) remaining
Completed 189.7 MiB/233.2 MiB (38.8 MiB/s) with 3 file(s) remaining
Completed 189.9 MiB/233.2 MiB (38.9 MiB/s) with 3 file(s) remaining
Completed 190.2 MiB/233.2 MiB (38.9 MiB/s) with 3 file(s) remaining
Completed 190.4 MiB/233.2 MiB (38.9 MiB/s) with 3 file(s) remaining
Completed 190.7 MiB/233.2 MiB (39.0 MiB/s) with 3 file(s) remaining
Completed 190.9 MiB/233.2 MiB (39.0 MiB/s) with 3 file(s) remaining
Completed 191.2 MiB/233.2 MiB (39.1 MiB/s) with 3 file(s) remaining
Completed 191.4 MiB/233.2 MiB (39.1 MiB/s) with 3 file(s) remaining
Completed 191.7 MiB/233.2 MiB (39.1 MiB/s) with 3 file(s) remaining
Completed 191.9 MiB/233.2 MiB (39.1 MiB/s) with 3 file(s) remaining
Completed 192.2 MiB/233.2 MiB (39.1 MiB/s) with 3 file(s) remaining
Completed 192.4 MiB/233.2 MiB (39.1 MiB/s) with 3 file(s) remaining
Completed 192.7 MiB/233.2 MiB (39.1 MiB/s) with 3 file(s) remaining
Completed 192.9 MiB/233.2 MiB (39.1 MiB/s) with 3 file(s) remaining
Completed 193.2 MiB/233.2 MiB (39.1 MiB/s) with 3 file(s) remaining
Completed 193.4 MiB/233.2 MiB (39.1 MiB/s) with 3 file(s) remaining
Completed 193.7 MiB/233.2 MiB (39.1 MiB/s) with 3 file(s) remaining
Completed 193.9 MiB/233.2 MiB (39.1 MiB/s) with 3 file(s) remaining
Completed 194.2 MiB/233.2 MiB (39.1 MiB/s) with 3 file(s) remaining
Completed 194.4 MiB/233.2 MiB (39.1 MiB/s) with 3 file(s) remaining
Completed 194.7 MiB/233.2 MiB (39.1 MiB/s) with 3 file(s) remaining
Completed 194.9 MiB/233.2 MiB (39.1 MiB/s) with 3 file(s) remaining
Completed 195.2 MiB/233.2 MiB (39.1 MiB/s) with 3 file(s) remaining
Completed 195.4 MiB/233.2 MiB (39.1 MiB/s) with 3 file(s) remaining
Completed 195.7 MiB/233.2 MiB (39.0 MiB/s) with 3 file(s) remaining
Completed 195.9 MiB/233.2 MiB (39.1 MiB/s) with 3 file(s) remaining
Completed 196.2 MiB/233.2 MiB (39.0 MiB/s) with 3 file(s) remaining
Completed 196.4 MiB/233.2 MiB (39.0 MiB/s) with 3 file(s) remaining
Completed 196.7 MiB/233.2 MiB (39.1 MiB/s) with 3 file(s) remaining
Completed 196.9 MiB/233.2 MiB (39.1 MiB/s) with 3 file(s) remaining
Completed 197.2 MiB/233.2 MiB (39.2 MiB/s) with 3 file(s) remaining
Completed 197.4 MiB/233.2 MiB (39.1 MiB/s) with 3 file(s) remaining
Completed 197.7 MiB/233.2 MiB (39.1 MiB/s) with 3 file(s) remaining
Completed 197.9 MiB/233.2 MiB (39.2 MiB/s) with 3 file(s) remaining
Completed 198.2 MiB/233.2 MiB (39.2 MiB/s) with 3 file(s) remaining
Completed 198.4 MiB/233.2 MiB (39.2 MiB/s) with 3 file(s) remaining
Completed 198.7 MiB/233.2 MiB (39.2 MiB/s) with 3 file(s) remaining
Completed 198.9 MiB/233.2 MiB (39.2 MiB/s) with 3 file(s) remaining
Completed 199.2 MiB/233.2 MiB (39.2 MiB/s) with 3 file(s) remaining
Completed 199.4 MiB/233.2 MiB (39.2 MiB/s) with 3 file(s) remaining
Completed 199.7 MiB/233.2 MiB (39.2 MiB/s) with 3 file(s) remaining
Completed 199.9 MiB/233.2 MiB (39.2 MiB/s) with 3 file(s) remaining
Completed 200.2 MiB/233.2 MiB (39.2 MiB/s) with 3 file(s) remaining
Completed 200.4 MiB/233.2 MiB (39.2 MiB/s) with 3 file(s) remaining
Completed 200.7 MiB/233.2 MiB (39.2 MiB/s) with 3 file(s) remaining
Completed 200.9 MiB/233.2 MiB (39.2 MiB/s) with 3 file(s) remaining
Completed 201.2 MiB/233.2 MiB (39.3 MiB/s) with 3 file(s) remaining
Completed 201.4 MiB/233.2 MiB (39.2 MiB/s) with 3 file(s) remaining
Completed 201.7 MiB/233.2 MiB (39.3 MiB/s) with 3 file(s) remaining
Completed 201.9 MiB/233.2 MiB (39.2 MiB/s) with 3 file(s) remaining
Completed 202.2 MiB/233.2 MiB (39.2 MiB/s) with 3 file(s) remaining
Completed 202.4 MiB/233.2 MiB (39.2 MiB/s) with 3 file(s) remaining
Completed 202.7 MiB/233.2 MiB (39.2 MiB/s) with 3 file(s) remaining
Completed 202.9 MiB/233.2 MiB (39.1 MiB/s) with 3 file(s) remaining
Completed 203.2 MiB/233.2 MiB (39.1 MiB/s) with 3 file(s) remaining
Completed 203.4 MiB/233.2 MiB (39.1 MiB/s) with 3 file(s) remaining
Completed 203.7 MiB/233.2 MiB (39.1 MiB/s) with 3 file(s) remaining
Completed 203.9 MiB/233.2 MiB (39.1 MiB/s) with 3 file(s) remaining
Completed 204.2 MiB/233.2 MiB (39.1 MiB/s) with 3 file(s) remaining
Completed 204.4 MiB/233.2 MiB (39.1 MiB/s) with 3 file(s) remaining
Completed 204.7 MiB/233.2 MiB (39.1 MiB/s) with 3 file(s) remaining
Completed 204.9 MiB/233.2 MiB (39.1 MiB/s) with 3 file(s) remaining
Completed 205.2 MiB/233.2 MiB (39.1 MiB/s) with 3 file(s) remaining
Completed 205.4 MiB/233.2 MiB (39.1 MiB/s) with 3 file(s) remaining
Completed 205.7 MiB/233.2 MiB (39.1 MiB/s) with 3 file(s) remaining
Completed 205.9 MiB/233.2 MiB (39.1 MiB/s) with 3 file(s) remaining
Completed 206.2 MiB/233.2 MiB (39.1 MiB/s) with 3 file(s) remaining
Completed 206.4 MiB/233.2 MiB (39.1 MiB/s) with 3 file(s) remaining
Completed 206.7 MiB/233.2 MiB (39.1 MiB/s) with 3 file(s) remaining
Completed 206.9 MiB/233.2 MiB (39.1 MiB/s) with 3 file(s) remaining
Completed 207.2 MiB/233.2 MiB (39.0 MiB/s) with 3 file(s) remaining
Completed 207.4 MiB/233.2 MiB (38.9 MiB/s) with 3 file(s) remaining
Completed 207.7 MiB/233.2 MiB (38.9 MiB/s) with 3 file(s) remaining
Completed 207.9 MiB/233.2 MiB (38.9 MiB/s) with 3 file(s) remaining
Completed 208.2 MiB/233.2 MiB (38.8 MiB/s) with 3 file(s) remaining
Completed 208.4 MiB/233.2 MiB (38.7 MiB/s) with 3 file(s) remaining
Completed 208.7 MiB/233.2 MiB (38.8 MiB/s) with 3 file(s) remaining
Completed 208.9 MiB/233.2 MiB (38.8 MiB/s) with 3 file(s) remaining
Completed 209.2 MiB/233.2 MiB (38.8 MiB/s) with 3 file(s) remaining
Completed 209.4 MiB/233.2 MiB (38.8 MiB/s) with 3 file(s) remaining
Completed 209.7 MiB/233.2 MiB (38.7 MiB/s) with 3 file(s) remaining
Completed 209.9 MiB/233.2 MiB (38.7 MiB/s) with 3 file(s) remaining
Completed 210.2 MiB/233.2 MiB (38.7 MiB/s) with 3 file(s) remaining
Completed 210.4 MiB/233.2 MiB (38.7 MiB/s) with 3 file(s) remaining
Completed 210.7 MiB/233.2 MiB (38.7 MiB/s) with 3 file(s) remaining
Completed 210.9 MiB/233.2 MiB (38.7 MiB/s) with 3 file(s) remaining
Completed 211.2 MiB/233.2 MiB (38.7 MiB/s) with 3 file(s) remaining
Completed 211.4 MiB/233.2 MiB (38.7 MiB/s) with 3 file(s) remaining
Completed 211.7 MiB/233.2 MiB (38.7 MiB/s) with 3 file(s) remaining
Completed 211.9 MiB/233.2 MiB (38.6 MiB/s) with 3 file(s) remaining
Completed 212.2 MiB/233.2 MiB (38.5 MiB/s) with 3 file(s) remaining
Completed 212.4 MiB/233.2 MiB (38.5 MiB/s) with 3 file(s) remaining
Completed 212.7 MiB/233.2 MiB (38.4 MiB/s) with 3 file(s) remaining
Completed 212.9 MiB/233.2 MiB (38.4 MiB/s) with 3 file(s) remaining
Completed 213.2 MiB/233.2 MiB (38.3 MiB/s) with 3 file(s) remaining
Completed 213.4 MiB/233.2 MiB (38.3 MiB/s) with 3 file(s) remaining
Completed 213.7 MiB/233.2 MiB (38.2 MiB/s) with 3 file(s) remaining
Completed 213.9 MiB/233.2 MiB (38.2 MiB/s) with 3 file(s) remaining
Completed 214.2 MiB/233.2 MiB (38.1 MiB/s) with 3 file(s) remaining
Completed 214.4 MiB/233.2 MiB (38.1 MiB/s) with 3 file(s) remaining
Completed 214.7 MiB/233.2 MiB (38.0 MiB/s) with 3 file(s) remaining
Completed 214.9 MiB/233.2 MiB (38.0 MiB/s) with 3 file(s) remaining
Completed 215.2 MiB/233.2 MiB (38.0 MiB/s) with 3 file(s) remaining
Completed 215.4 MiB/233.2 MiB (37.9 MiB/s) with 3 file(s) remaining
Completed 215.7 MiB/233.2 MiB (37.9 MiB/s) with 3 file(s) remaining
Completed 215.9 MiB/233.2 MiB (37.9 MiB/s) with 3 file(s) remaining
Completed 216.2 MiB/233.2 MiB (37.8 MiB/s) with 3 file(s) remaining
Completed 216.4 MiB/233.2 MiB (29.6 MiB/s) with 3 file(s) remaining
Completed 216.7 MiB/233.2 MiB (29.6 MiB/s) with 3 file(s) remaining
Completed 216.9 MiB/233.2 MiB (29.7 MiB/s) with 3 file(s) remaining
Completed 217.2 MiB/233.2 MiB (29.7 MiB/s) with 3 file(s) remaining
Completed 217.4 MiB/233.2 MiB (29.7 MiB/s) with 3 file(s) remaining
Completed 217.7 MiB/233.2 MiB (29.4 MiB/s) with 3 file(s) remaining
Completed 217.9 MiB/233.2 MiB (28.6 MiB/s) with 3 file(s) remaining
Completed 218.2 MiB/233.2 MiB (27.3 MiB/s) with 3 file(s) remaining
Completed 218.4 MiB/233.2 MiB (27.4 MiB/s) with 3 file(s) remaining
Completed 218.7 MiB/233.2 MiB (27.4 MiB/s) with 3 file(s) remaining
Completed 218.9 MiB/233.2 MiB (27.4 MiB/s) with 3 file(s) remaining
Completed 219.2 MiB/233.2 MiB (27.5 MiB/s) with 3 file(s) remaining
Completed 219.4 MiB/233.2 MiB (27.3 MiB/s) with 3 file(s) remaining
Completed 219.7 MiB/233.2 MiB (26.5 MiB/s) with 3 file(s) remaining
Completed 219.9 MiB/233.2 MiB (26.6 MiB/s) with 3 file(s) remaining
Completed 220.2 MiB/233.2 MiB (26.6 MiB/s) with 3 file(s) remaining
Completed 220.4 MiB/233.2 MiB (26.6 MiB/s) with 3 file(s) remaining
upload: ../../../data/datafile-65-MB to s3://awscli-mint-test-bucket-5091/datafile-65-MBCompleted 220.4 MiB/233.2 MiB (26.6 MiB/s) with 2 file(s) remaining
Completed 220.7 MiB/233.2 MiB (17.8 MiB/s) with 2 file(s) remaining
Completed 220.9 MiB/233.2 MiB (17.3 MiB/s) with 2 file(s) remaining
Completed 221.2 MiB/233.2 MiB (12.4 MiB/s) with 2 file(s) remaining
upload failed: ../../../data/datafile-129-MB to s3://awscli-mint-test-bucket-5091/datafile-129-MB ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))Completed 233.2 MiB/233.2 MiB (12.4 MiB/s) with 1 file(s) remaining
upload: ../../../data/datafile-10-MB to s3://awscli-mint-test-bucket-5091/datafile-10-MB"}

Executed 4 out of 14 tests successfully.
```
<a name="270ccb2e-a4ef-42da-860b-972cb1ec74b8"></a>
### 8027-aae92bc/mint-worm.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.57:30735
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            worm
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp cc00f40d870a:/mint/log /tmp/mint-logs'

(1/1) Running worm tests ... FAILED in 13 seconds
{
  "alert": "",
  "args": {
    "bucketName": "bucket-5eky4blxemep3xny5wh8y7pa3283sfme1lbzmd91sutuklrxblifsj7",
    "expiry": 60000000000,
    "objectName": "testObject"
  },
  "duration": 12607,
  "error": "RequestError: send request failed\ncaused by: Put http://72.28.97.57:30735/bucket-5eky4blxemep3xny5wh8y7pa3283sfme1lbzmd91sutuklrxblifsj7: dial tcp 72.28.97.57:30735: connect: no route to host",
  "function": "PutAndDelete",
  "message": "WORM_MODE ON  - CreateBucket Failed",
  "name": "test worm mode",
  "status": "FAIL"
}

Executed 0 out of 1 tests successfully.
```
<a name="081d1060-1a03-479d-a312-bfd0875b9af6"></a>
### 8027-aae92bc/mint-compression-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.52:32224
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 7dc2de231237:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in ...Truncated

**Comment by minio-ops** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-compression-xl.sh | :heavy_check_mark: |
| mint-xl.sh | :heavy_check_mark: |
| mint-compression-dist-xl.sh | :heavy_check_mark: |
| mint-compression-fs.sh | :heavy_check_mark: |
| mint-worm.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-dist-xl.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :x: [more...](#a67f7b31-00d2-4b99-9a0a-efb34902ccaf) |
<a name="a67f7b31-00d2-4b99-9a0a-efb34902ccaf"></a>
### 8027-5df8177/mint-large-bucket.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.60:32762
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp e793ad5405c2:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 3 seconds
(2/14) Running aws-sdk-java tests ... done in 2 seconds
(3/14) Running aws-sdk-php tests ... done in 48 seconds
(4/14) Running aws-sdk-ruby tests ... done in 11 seconds
(5/14) Running awscli tests ... done in 2 minutes and 38 seconds
(6/14) Running healthcheck tests ... done in 0 seconds
(7/14) Running mc tests ... FAILED in 2 minutes and 26 seconds
{
  "name": "mc",
  "duration": "96586",
  "function": "test_mirror_list_objects_storage_class",
  "status": "FAIL",
  "error": "/mint/run/core/mc/mc --config-dir /tmp/.mc-12939 --quiet --no-color mirror --storage-class REDUCED_REDUNDANCY /mint/data myminio/mc-test-bucket-10166  >>> \n`/mint/data/datafile-1-MB` -> `myminio/mc-test-bucket-10166/datafile-1-MB`\n`/mint/data/datafile-0-b` -> `myminio/mc-test-bucket-10166/datafile-0-b`\n`/mint/data/datafile-1-kB` -> `myminio/mc-test-bucket-10166/datafile-1-kB`\n`/mint/data/datafile-10-MB` -> `myminio/mc-test-bucket-10166/datafile-10-MB`\n`/mint/data/datafile-1-b` -> `myminio/mc-test-bucket-10166/datafile-1-b`\n`/mint/data/datafile-1.03-MB` -> `myminio/mc-test-bucket-10166/datafile-1.03-MB`\n`/mint/data/datafile-100-kB` -> `myminio/mc-test-bucket-10166/datafile-100-kB`\n`/mint/data/datafile-10-kB` -> `myminio/mc-test-bucket-10166/datafile-10-kB`\n`/mint/data/datafile-129-MB` -> `myminio/mc-test-bucket-10166/datafile-129-MB`\n`/mint/data/datafile-11-MB` -> `myminio/mc-test-bucket-10166/datafile-11-MB`\n`/mint/data/datafile-33-kB` -> `myminio/mc-test-bucket-10166/datafile-33-kB`\n`/mint/data/datafile-5-MB` -> `myminio/mc-test-bucket-10166/datafile-5-MB`\n`/mint/data/datafile-5243880-b` -> `myminio/mc-test-bucket-10166/datafile-5243880-b`\n`/mint/data/datafile-6-MB` -> `myminio/mc-test-bucket-10166/datafile-6-MB`\n`/mint/data/datafile-65-MB` -> `myminio/mc-test-bucket-10166/datafile-65-MB`\nmc: <ERROR> Failed to copy `/mint/data/datafile-10-MB`. Please reduce your request\nmc: <ERROR> Failed to copy `/mint/data/datafile-129-MB`. Please reduce your request\nmc: <ERROR> Failed to copy `/mint/data/datafile-65-MB`. Please reduce your request\nmc: <ERROR> Failed to copy `/mint/data/datafile-11-MB`. Please reduce your request\nTotal: 233.17 MiB, Transferred: 484.42 MiB, Speed: 5.02 MiB/s"
}

Executed 6 out of 14 tests successfully.
```

**Comment by vadmeste** [comment]
By the way @harshavardhana, did you see in the original issue report any indication that there is an issue in dirent code ?

File: cmd/posix-list-dir_unix.go [hunk 1]
```diff
@@ -19,93 +19,63 @@
...
 	}
-	return entries, nil
-}
 
-var readDirBufPool = sync.Pool{
-	New: func() interface{} {
-		b := make([]byte, readDirentBufSize)
-		return &b
-	},
+	// Special cases for common things:
```
Comment (vadmeste) [inline cmd/posix-list-dir_unix.go]: I am not sure why there are special cases here, I mean it looks like `name = string(nameBuf[:nameLen])` is enough instead of if {} else if {} else {}

**Comment by harshavardhana** [comment]
Yes @vadmeste it happened every 12hrs which is our disk usage thread.

**Comment by minio-ops** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-xl.sh | :heavy_check_mark: |
| mint-compression-dist-xl.sh | :heavy_check_mark: |
| mint-compression-fs.sh | :heavy_check_mark: |
| mint-worm.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-dist-xl.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-compression-xl.sh | :x: [more...](#eb06edbb-20ac-4199-beb1-208ff84bdb46) |
| mint-large-bucket.sh | :x: [more...](#67124c19-91c2-4bad-9f4d-928278a36274) |
<a name="eb06edbb-20ac-4199-beb1-208ff84bdb46"></a>
### 8027-5806d06/mint-compression-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.53:31933
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp a800abf40c63:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 0 seconds
(2/14) Running aws-sdk-java tests ... done in 1 seconds
(3/14) Running aws-sdk-php tests ... done in 41 seconds
(4/14) Running aws-sdk-ruby tests ... done in 2 seconds
(5/14) Running awscli tests ... done in 1 minutes and 56 seconds
(6/14) Running healthcheck tests ... done in 0 seconds
(7/14) Running mc tests ... done in 52 seconds
(8/14) Running minio-dotnet tests ... done in 34 seconds
(9/14) Running minio-go tests ... done in 36 seconds
(10/14) Running minio-java tests ... done in 18 seconds
(11/14) Running minio-js tests ... done in 35 seconds
(12/14) Running minio-py tests ... done in 1 minutes and 15 seconds
(13/14) Running s3cmd tests ... FAILED in 7 seconds
{
  "name": "s3cmd",
  "duration": "2149",
  "function": "test_get_object_multipart",
  "status": "FAIL",
  "error": "\n!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!\n    An unexpected error has occurred.\n  Please try reproducing the error using\n  the latest s3cmd code from the git master\n  branch found at:\n    https://github.com/s3tools/s3cmd\n  and have a look at the known issues list:\n    https://github.com/s3tools/s3cmd/wiki/Common-known-issues-and-their-solutions\n  If the error persists, please report the\n  following lines (removing any private\n  info as necessary) to:\n   s3tools-bugs@lists.sourceforge.net\n\n\n!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!\n\nInvoked as: /usr/local/bin/s3cmd --config /tmp/.s3cmd-31927/s3cfg get s3://s3cmd-test-bucket-20851/s3cmd-test-object-8959 s3cmd-test-object-8959.downloaded\nProblem: <class 'ConnectionResetError: [Errno 104] Connection reset by peer\nS3cmd:   2.0.2\npython:   3.5.2 (default, Nov 12 2018, 13:43:14) \n[GCC 5.4.0 20160609]\nenvironment LANG=C.UTF-8\n\nTraceback (most recent call last):\n  File \"/usr/local/bin/s3cmd\", line 3092, in <module>\n    rc = main()\n  File \"/usr/local/bin/s3cmd\", line 3001, in main\n    rc = cmd_func(args)\n  File \"/usr/local/bin/s3cmd\", line 590, in cmd_object_get\n    response = s3.object_get(uri, dst_stream, destination, start_position = start_position, extra_label = seq_label)\n  File \"/usr/local/lib/python3.5/dist-packages/S3/S3.py\", line 716, in object_get\n    response = self.recv_file(request, stream, labels, start_position)\n  File \"/usr/local/lib/python3.5/dist-packages/S3/S3.py\", line 1742, in recv_file\n    data = http_response.read(this_chunk)\n  File \"/usr/lib/python3.5/http/client.py\", line 448, in read\n    n = self.readinto(b)\n  File \"/usr/lib/python3.5/http/client.py\", line 488, in readinto\n    n = self.fp.readinto(b)\n  File \"/usr/lib/python3.5/socket.py\", line 575, in readinto\n    return self._sock.recv_into(b)\nConnectionResetError: [Errno 104] Connection reset by peer\n\n!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!\n    An unexpected error has occurred.\n  Please try reproducing the error using\n  the latest s3cmd code from the git master\n  branch found at:\n    https://github.com/s3tools/s3cmd\n  and have a look at the known issues list:\n    https://github.com/s3tools/s3cmd/wiki/Common-known-issues-and-their-solutions\n  If the error persists, please report the\n  above lines (removing any private\n  info as necessary) to:\n   s3tools-bugs@lists.sourceforge.net\n!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!"
}

Executed 12 out of 14 tests successfully.
```
<a name="67124c19-91c2-4bad-9f4d-928278a36274"></a>
### 8027-5806d06/mint-large-bucket.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.58:32480
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 7c8e79fee4fe:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 2 seconds
(2/14) Running aws-sdk-java tests ... done in 2 seconds
(3/14) Running aws-sdk-php tests ... done in 46 seconds
(4/14) Running aws-sdk-ruby tests ... done in 12 seconds
(5/14) Running awscli tests ... done in 2 minutes and 34 seconds
(6/14) Running healthcheck tests ... done in 0 seconds
(7/14) Running mc tests ... FAILED in 2 minutes and 27 seconds
{
  "name": "mc",
  "duration": "107584",
  "function": "test_mirror_list_objects_storage_class",
  "status": "FAIL",
  "error": "/mint/run/core/mc/mc --config-dir /tmp/.mc-7199 --quiet --no-color mirror --storage-class REDUCED_REDUNDANCY /mint/data myminio/mc-test-bucket-18881  >>> \n`/mint/data/datafile-1-MB` -> `myminio/mc-test-bucket-18881/datafile-1-MB`\n`/mint/data/datafile-0-b` -> `myminio/mc-test-bucket-18881/datafile-0-b`\n`/mint/data/datafile-1-kB` -> `myminio/mc-test-bucket-18881/datafile-1-kB`\n`/mint/data/datafile-1-b` -> `myminio/mc-test-bucket-18881/datafile-1-b`\n`/mint/data/datafile-10-MB` -> `myminio/mc-test-bucket-18881/datafile-10-MB`\n`/mint/data/datafile-1.03-MB` -> `myminio/mc-test-bucket-18881/datafile-1.03-MB`\n`/mint/data/datafile-100-kB` -> `myminio/mc-test-bucket-18881/datafile-100-kB`\n`/mint/data/datafile-10-kB` -> `myminio/mc-test-bucket-18881/datafile-10-kB`\n`/mint/data/datafile-11-MB` -> `myminio/mc-test-bucket-18881/datafile-11-MB`\n`/mint/data/datafile-129-MB` -> `myminio/mc-test-bucket-18881/datafile-129-MB`\n`/mint/data/datafile-5-MB` -> `myminio/mc-test-bucket-18881/datafile-5-MB`\n`/mint/data/datafile-33-kB` -> `myminio/mc-test-bucket-18881/datafile-33-kB`\n`/mint/data/datafile-6-MB` -> `myminio/mc-test-bucket-18881/datafile-6-MB`\n`/mint/data/datafile-5243880-b` -> `myminio/mc-test-bucket-18881/datafile-5243880-b`\n`/mint/data/datafile-65-MB` -> `myminio/mc-test-bucket-18881/datafile-65-MB`\nmc: <ERROR> Failed to copy `/mint/data/datafile-10-MB`. Please reduce your request\nmc: <ERROR> Failed to copy `/mint/data/datafile-11-MB`. Please reduce your request\nmc: <ERROR> Failed to copy `/mint/data/datafile-65-MB`. Please reduce your request\nmc: <ERROR> Failed to copy `/mint/data/datafile-129-MB`. Please reduce your request\nTotal: 233.17 MiB, Transferred: 487.45 MiB, Speed: 4.65 MiB/s"
}

Executed 6 out of 14 tests successfully.
```

**Comment by minio-ops** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-compression-xl.sh | :heavy_check_mark: |
| mint-compression-dist-xl.sh | :heavy_check_mark: |
| mint-compression-fs.sh | :heavy_check_mark: |
| mint-worm.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-dist-xl.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-xl.sh | :x: [more...](#a88d3df5-521b-4d9f-948c-18d6482f64c3) |
| mint-large-bucket.sh | :x: [more...](#7896bbf7-981a-45bd-bf9d-ba6987a78e3d) |
<a name="a88d3df5-521b-4d9f-948c-18d6482f64c3"></a>
### 8027-d49b929/mint-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.57:30345
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 71deeb846c45:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... FAILED in 13 seconds
{
  "alert": "",
  "args": {
    "bucketName": "aws-sdk-go-test-rj0wb95zoa9wnj",
    "expiry": 60000000000,
    "objectName": "presignedTest"
  },
  "duration": 12552,
  "error": "RequestError: send request failed\ncaused by: Put http://72.28.97.57:30345/aws-sdk-go-test-rj0wb95zoa9wnj: dial tcp 72.28.97.57:30345: connect: no route to host",
  "function": "PresignedPut",
  "message": "AWS SDK Go CreateBucket Failed",
  "name": "aws-sdk-go",
  "status": "FAIL"
}

Executed 0 out of 14 tests successfully.
```
<a name="7896bbf7-981a-45bd-bf9d-ba6987a78e3d"></a>
### 8027-d49b929/mint-large-bucket.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.51:31421
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp cb25737412b4:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 5 seconds
(2/14) Running aws-sdk-java tests ... done in 1 seconds
(3/14) Running aws-sdk-php tests ... done in 53 seconds
(4/14) Running aws-sdk-ruby tests ... done in 14 seconds
(5/14) Running awscli tests ... done in 2 minutes and 28 seconds
(6/14) Running healthcheck tests ... done in 0 seconds
(7/14) Running mc tests ... FAILED in 2 minutes and 31 seconds
{
  "name": "mc",
  "duration": "109364",
  "function": "test_mirror_list_objects_storage_class",
  "status": "FAIL",
  "error": "/mint/run/core/mc/mc --config-dir /tmp/.mc-16148 --quiet --no-color mirror --storage-class REDUCED_REDUNDANCY /mint/data myminio/mc-test-bucket-27725  >>> \n`/mint/data/datafile-1-MB` -> `myminio/mc-test-bucket-27725/datafile-1-MB`\n`/mint/data/datafile-0-b` -> `myminio/mc-test-bucket-27725/datafile-0-b`\n`/mint/data/datafile-1-kB` -> `myminio/mc-test-bucket-27725/datafile-1-kB`\n`/mint/data/datafile-10-MB` -> `myminio/mc-test-bucket-27725/datafile-10-MB`\n`/mint/data/datafile-1-b` -> `myminio/mc-test-bucket-27725/datafile-1-b`\n`/mint/data/datafile-1.03-MB` -> `myminio/mc-test-bucket-27725/datafile-1.03-MB`\n`/mint/data/datafile-100-kB` -> `myminio/mc-test-bucket-27725/datafile-100-kB`\n`/mint/data/datafile-10-kB` -> `myminio/mc-test-bucket-27725/datafile-10-kB`\n`/mint/data/datafile-129-MB` -> `myminio/mc-test-bucket-27725/datafile-129-MB`\n`/mint/data/datafile-11-MB` -> `myminio/mc-test-bucket-27725/datafile-11-MB`\n`/mint/data/datafile-5-MB` -> `myminio/mc-test-bucket-27725/datafile-5-MB`\n`/mint/data/datafile-33-kB` -> `myminio/mc-test-bucket-27725/datafile-33-kB`\n`/mint/data/datafile-6-MB` -> `myminio/mc-test-bucket-27725/datafile-6-MB`\n`/mint/data/datafile-5243880-b` -> `myminio/mc-test-bucket-27725/datafile-5243880-b`\n`/mint/data/datafile-65-MB` -> `myminio/mc-test-bucket-27725/datafile-65-MB`\nmc: <ERROR> Failed to copy `/mint/data/datafile-11-MB`. Please reduce your request\nmc: <ERROR> Failed to copy `/mint/data/datafile-65-MB`. Please reduce your request\nmc: <ERROR> Failed to copy `/mint/data/datafile-129-MB`. Please reduce your request\nmc: <ERROR> Failed to copy `/mint/data/datafile-10-MB`. Please reduce your request\nTotal: 233.17 MiB, Transferred: 504.11 MiB, Speed: 4.61 MiB/s"
}

Executed 6 out of 14 tests successfully.
```

**Comment by minio-ops** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-compression-xl.sh | :heavy_check_mark: |
| mint-xl.sh | :heavy_check_mark: |
| mint-compression-dist-xl.sh | :heavy_check_mark: |
| mint-compression-fs.sh | :heavy_check_mark: |
| mint-worm.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-dist-xl.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :x: [more...](#e338838e-6a80-4937-b09f-a8fdb9b0eba7) |
<a name="e338838e-6a80-4937-b09f-a8fdb9b0eba7"></a>
### 8027-96c9743/mint-large-bucket.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.58:31464
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 9379f8bde929:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 4 seconds
(2/14) Running aws-sdk-java tests ... done in 2 seconds
(3/14) Running aws-sdk-php tests ... done in 52 seconds
(4/14) Running aws-sdk-ruby tests ... done in 17 seconds
(5/14) Running awscli tests ... done in 2 minutes and 21 seconds
(6/14) Running healthcheck tests ... done in 0 seconds
(7/14) Running mc tests ... FAILED in 2 minutes and 32 seconds
{
  "name": "mc",
  "duration": "118908",
  "function": "test_mirror_list_objects_storage_class",
  "status": "FAIL",
  "error": "/mint/run/core/mc/mc --config-dir /tmp/.mc-7255 --quiet --no-color mirror --storage-class REDUCED_REDUNDANCY /mint/data myminio/mc-test-bucket-14737  >>> \n`/mint/data/datafile-1-MB` -> `myminio/mc-test-bucket-14737/datafile-1-MB`\n`/mint/data/datafile-0-b` -> `myminio/mc-test-bucket-14737/datafile-0-b`\n`/mint/data/datafile-1-kB` -> `myminio/mc-test-bucket-14737/datafile-1-kB`\n`/mint/data/datafile-1-b` -> `myminio/mc-test-bucket-14737/datafile-1-b`\n`/mint/data/datafile-11-MB` -> `myminio/mc-test-bucket-14737/datafile-11-MB`\n`/mint/data/datafile-1.03-MB` -> `myminio/mc-test-bucket-14737/datafile-1.03-MB`\n`/mint/data/datafile-33-kB` -> `myminio/mc-test-bucket-14737/datafile-33-kB`\n`/mint/data/datafile-100-kB` -> `myminio/mc-test-bucket-14737/datafile-100-kB`\n`/mint/data/datafile-10-kB` -> `myminio/mc-test-bucket-14737/datafile-10-kB`\n`/mint/data/datafile-5-MB` -> `myminio/mc-test-bucket-14737/datafile-5-MB`\n`/mint/data/datafile-5243880-b` -> `myminio/mc-test-bucket-14737/datafile-5243880-b`\n`/mint/data/datafile-10-MB` -> `myminio/mc-test-bucket-14737/datafile-10-MB`\n`/mint/data/datafile-6-MB` -> `myminio/mc-test-bucket-14737/datafile-6-MB`\n`/mint/data/datafile-129-MB` -> `myminio/mc-test-bucket-14737/datafile-129-MB`\n`/mint/data/datafile-65-MB` -> `myminio/mc-test-bucket-14737/datafile-65-MB`\nmc: <ERROR> Failed to copy `/mint/data/datafile-65-MB`. Please reduce your request\nmc: <ERROR> Failed to copy `/mint/data/datafile-10-MB`. Please reduce your request\nmc: <ERROR> Failed to copy `/mint/data/datafile-129-MB`. Please reduce your request\nmc: <ERROR> Failed to copy `/mint/data/datafile-11-MB`. Please reduce your request\nTotal: 233.17 MiB, Transferred: 501.67 MiB, Speed: 4.22 MiB/s"
}

Executed 6 out of 14 tests successfully.
```

**Comment by minio-ops** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-compression-xl.sh | :heavy_check_mark: |
| mint-compression-dist-xl.sh | :heavy_check_mark: |
| mint-compression-fs.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-dist-xl.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-xl.sh | :x: [more...](#8fdf7c37-373a-4cb9-b081-2b6afb482213) |
| mint-large-bucket.sh | :x: [more...](#cbbec7b6-7777-48d0-b6de-93c531e65e04) |
| mint-worm.sh | :x: [more...](#de4570ea-2b3f-430d-808e-6d04c9fcd8ad) |
<a name="8fdf7c37-373a-4cb9-b081-2b6afb482213"></a>
### 8027-4f41b65/mint-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.53:31044
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 20a6e0395a2e:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... FAILED in 6 minutes and 0 seconds
{
  "alert": "",
  "args": {
    "bucketName": "aws-sdk-go-test-r1lmhyjkf6awke",
    "expiry": 60000000000,
    "objectName": "presignedTest"
  },
  "duration": 360015,
  "error": "XMinioServerNotInitialized: Server not initialized, please try again.\n\tstatus code: 503, request id: 15B87633AED0B64A, host id: ",
  "function": "PresignedPut",
  "message": "AWS SDK Go CreateBucket Failed",
  "name": "aws-sdk-go",
  "status": "FAIL"
}

Executed 0 out of 14 tests successfully.
```
<a name="cbbec7b6-7777-48d0-b6de-93c531e65e04"></a>
### 8027-4f41b65/mint-large-bucket.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.52:30614
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 2f89d5a7068b:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 2 seconds
(2/14) Running aws-sdk-java tests ... done in 2 seconds
(3/14) Running aws-sdk-php tests ... done in 46 seconds
(4/14) Running aws-sdk-ruby tests ... done in 13 seconds
(5/14) Running awscli tests ... FAILED in 2 minutes and 19 seconds
{"name": "awscli", "duration": 72518, "function": "aws --endpoint-url http://72.28.97.52:30614 s3 sync /mint/data s3://awscli-mint-test-bucket-917/\n", "status": "FAIL", "error": "Completed 256.0 KiB/233.2 MiB (5.0 MiB/s) with 15 file(s) remaining
Completed 512.0 KiB/233.2 MiB (9.8 MiB/s) with 15 file(s) remaining
Completed 768.0 KiB/233.2 MiB (14.5 MiB/s) with 15 file(s) remaining
Completed 1.0 MiB/233.2 MiB (19.0 MiB/s) with 15 file(s) remaining  
Completed 1.2 MiB/233.2 MiB (20.3 MiB/s) with 15 file(s) remaining  
Completed 1.5 MiB/233.2 MiB (24.1 MiB/s) with 15 file(s) remaining  
Completed 1.8 MiB/233.2 MiB (27.8 MiB/s) with 15 file(s) remaining  
Completed 2.0 MiB/233.2 MiB (30.9 MiB/s) with 15 file(s) remaining  
upload: ../../../data/datafile-0-b to s3://awscli-mint-test-bucket-917/datafile-0-bCompleted 2.0 MiB/233.2 MiB (30.9 MiB/s) with 14 file(s) remaining
Completed 2.0 MiB/233.2 MiB (23.1 MiB/s) with 14 file(s) remaining
upload: ../../../data/datafile-1-kB to s3://awscli-mint-test-bucket-917/datafile-1-kBCompleted 2.0 MiB/233.2 MiB (23.1 MiB/s) with 13 file(s) remaining
Completed 2.0 MiB/233.2 MiB (18.7 MiB/s) with 13 file(s) remaining
upload: ../../../data/datafile-10-kB to s3://awscli-mint-test-bucket-917/datafile-10-kBCompleted 2.0 MiB/233.2 MiB (18.7 MiB/s) with 12 file(s) remaining
Completed 2.1 MiB/233.2 MiB (16.5 MiB/s) with 12 file(s) remaining
upload: ../../../data/datafile-100-kB to s3://awscli-mint-test-bucket-917/datafile-100-kBCompleted 2.1 MiB/233.2 MiB (16.5 MiB/s) with 11 file(s) remaining
Completed 2.1 MiB/233.2 MiB (15.5 MiB/s) with 11 file(s) remaining
upload: ../../../data/datafile-1-b to s3://awscli-mint-test-bucket-917/datafile-1-bCompleted 2.1 MiB/233.2 MiB (15.5 MiB/s) with 10 file(s) remaining
Completed 2.4 MiB/233.2 MiB (16.5 MiB/s) with 10 file(s) remaining
Completed 2.6 MiB/233.2 MiB (18.1 MiB/s) with 10 file(s) remaining
Completed 2.9 MiB/233.2 MiB (19.8 MiB/s) with 10 file(s) remaining
Completed 3.1 MiB/233.2 MiB (21.3 MiB/s) with 10 file(s) remaining
Completed 3.4 MiB/233.2 MiB (22.2 MiB/s) with 10 file(s) remaining
Completed 3.6 MiB/233.2 MiB (22.1 MiB/s) with 10 file(s) remaining
Completed 3.9 MiB/233.2 MiB (22.3 MiB/s) with 10 file(s) remaining
Completed 3.9 MiB/233.2 MiB (21.5 MiB/s) with 10 file(s) remaining
upload: ../../../data/datafile-1.03-MB to s3://awscli-mint-test-bucket-917/datafile-1.03-MBCompleted 3.9 MiB/233.2 MiB (21.5 MiB/s) with 9 file(s) remaining
Completed 4.1 MiB/233.2 MiB (22.8 MiB/s) with 9 file(s) remaining
Completed 4.4 MiB/233.2 MiB (23.2 MiB/s) with 9 file(s) remaining
Completed 4.6 MiB/233.2 MiB (23.6 MiB/s) with 9 file(s) remaining
Completed 4.9 MiB/233.2 MiB (24.1 MiB/s) with 9 file(s) remaining
Completed 5.1 MiB/233.2 MiB (24.9 MiB/s) with 9 file(s) remaining
Completed 5.4 MiB/233.2 MiB (26.0 MiB/s) with 9 file(s) remaining
Completed 5.6 MiB/233.2 MiB (27.1 MiB/s) with 9 file(s) remaining
Completed 5.9 MiB/233.2 MiB (28.2 MiB/s) with 9 file(s) remaining
Completed 6.1 MiB/233.2 MiB (29.2 MiB/s) with 9 file(s) remaining
Completed 6.4 MiB/233.2 MiB (30.3 MiB/s) with 9 file(s) remaining
Completed 6.6 MiB/233.2 MiB (30.2 MiB/s) with 9 file(s) remaining
Completed 6.9 MiB/233.2 MiB (31.3 MiB/s) with 9 file(s) remaining
Completed 7.1 MiB/233.2 MiB (31.2 MiB/s) with 9 file(s) remaining
Completed 7.4 MiB/233.2 MiB (32.2 MiB/s) with 9 file(s) remaining
Completed 7.6 MiB/233.2 MiB (32.2 MiB/s) with 9 file(s) remaining
Completed 7.9 MiB/233.2 MiB (33.0 MiB/s) with 9 file(s) remaining
Completed 8.1 MiB/233.2 MiB (33.0 MiB/s) with 9 file(s) remaining
Completed 8.4 MiB/233.2 MiB (33.8 MiB/s) with 9 file(s) remaining
Completed 8.6 MiB/233.2 MiB (33.9 MiB/s) with 9 file(s) remaining
Completed 8.9 MiB/233.2 MiB (34.5 MiB/s) with 9 file(s) remaining
Completed 9.1 MiB/233.2 MiB (34.8 MiB/s) with 9 file(s) remaining
Completed 9.4 MiB/233.2 MiB (35.2 MiB/s) with 9 file(s) remaining
Completed 9.6 MiB/233.2 MiB (35.4 MiB/s) with 9 file(s) remaining
Completed 9.9 MiB/233.2 MiB (35.8 MiB/s) with 9 file(s) remaining
Completed 10.1 MiB/233.2 MiB (36.2 MiB/s) with 9 file(s) remaining
Completed 10.4 MiB/233.2 MiB (36.4 MiB/s) with 9 file(s) remaining
Completed 10.6 MiB/233.2 MiB (36.8 MiB/s) with 9 file(s) remaining
Completed 10.9 MiB/233.2 MiB (37.1 MiB/s) with 9 file(s) remaining
Completed 11.1 MiB/233.2 MiB (37.9 MiB/s) with 9 file(s) remaining
Completed 11.4 MiB/233.2 MiB (38.6 MiB/s) with 9 file(s) remaining
Completed 11.6 MiB/233.2 MiB (39.4 MiB/s) with 9 file(s) remaining
Completed 11.9 MiB/233.2 MiB (39.9 MiB/s) with 9 file(s) remaining
Completed 12.1 MiB/233.2 MiB (39.5 MiB/s) with 9 file(s) remaining
Completed 12.4 MiB/233.2 MiB (39.2 MiB/s) with 9 file(s) remaining
Completed 12.6 MiB/233.2 MiB (39.4 MiB/s) with 9 file(s) remaining
Completed 12.9 MiB/233.2 MiB (39.6 MiB/s) with 9 file(s) remaining
Completed 13.1 MiB/233.2 MiB (39.4 MiB/s) with 9 file(s) remaining
Completed 13.4 MiB/233.2 MiB (39.9 MiB/s) with 9 file(s) remaining
Completed 13.6 MiB/233.2 MiB (38.5 MiB/s) with 9 file(s) remaining
Completed 13.9 MiB/233.2 MiB (38.0 MiB/s) with 9 file(s) remaining
Completed 14.1 MiB/233.2 MiB (35.6 MiB/s) with 9 file(s) remaining
Completed 14.4 MiB/233.2 MiB (36.2 MiB/s) with 9 file(s) remaining
Completed 14.6 MiB/233.2 MiB (30.9 MiB/s) with 9 file(s) remaining
Completed 14.9 MiB/233.2 MiB (29.6 MiB/s) with 9 file(s) remaining
Completed 15.1 MiB/233.2 MiB (28.0 MiB/s) with 9 file(s) remaining
Completed 15.4 MiB/233.2 MiB (18.9 MiB/s) with 9 file(s) remaining
Completed 15.6 MiB/233.2 MiB (19.2 MiB/s) with 9 file(s) remaining
Completed 15.9 MiB/233.2 MiB (19.5 MiB/s) with 9 file(s) remaining
Completed 16.1 MiB/233.2 MiB (19.8 MiB/s) with 9 file(s) remaining
Completed 16.4 MiB/233.2 MiB (19.3 MiB/s) with 9 file(s) remaining
Completed 16.6 MiB/233.2 MiB (19.3 MiB/s) with 9 file(s) remaining
Completed 16.9 MiB/233.2 MiB (19.2 MiB/s) with 9 file(s) remaining
Completed 17.1 MiB/233.2 MiB (19.2 MiB/s) with 9 file(s) remaining
Completed 17.4 MiB/233.2 MiB (19.3 MiB/s) with 9 file(s) remaining
Completed 17.6 MiB/233.2 MiB (19.3 MiB/s) with 9 file(s) remaining
Completed 17.9 MiB/233.2 MiB (19.4 MiB/s) with 9 file(s) remaining
Completed 18.1 MiB/233.2 MiB (19.4 MiB/s) with 9 file(s) remaining
Completed 18.4 MiB/233.2 MiB (19.3 MiB/s) with 9 file(s) remaining
Completed 18.6 MiB/233.2 MiB (19.3 MiB/s) with 9 file(s) remaining
Completed 18.9 MiB/233.2 MiB (19.2 MiB/s) with 9 file(s) remaining
Completed 19.1 MiB/233.2 MiB (19.2 MiB/s) with 9 file(s) remaining
Completed 19.4 MiB/233.2 MiB (19.3 MiB/s) with 9 file(s) remaining
Completed 19.6 MiB/233.2 MiB (19.3 MiB/s) with 9 file(s) remaining
Completed 19.9 MiB/233.2 MiB (19.3 MiB/s) with 9 file(s) remaining
Completed 20.1 MiB/233.2 MiB (19.3 MiB/s) with 9 file(s) remaining
upload: ../../../data/datafile-5-MB to s3://awscli-mint-test-bucket-917/datafile-5-MBCompleted 20.1 MiB/233.2 MiB (19.3 MiB/s) with 8 file(s) remaining
Completed 20.4 MiB/233.2 MiB (19.3 MiB/s) with 8 file(s) remaining
Completed 20.6 MiB/233.2 MiB (19.4 MiB/s) with 8 file(s) remaining
Completed 20.9 MiB/233.2 MiB (19.4 MiB/s) with 8 file(s) remaining
Completed 21.1 MiB/233.2 MiB (19.4 MiB/s) with 8 file(s) remaining
Completed 21.4 MiB/233.2 MiB (19.4 MiB/s) with 8 file(s) remaining
Completed 21.6 MiB/233.2 MiB (19.6 MiB/s) with 8 file(s) remaining
Completed 21.9 MiB/233.2 MiB (19.8 MiB/s) with 8 file(s) remaining
Completed 22.1 MiB/233.2 MiB (20.0 MiB/s) with 8 file(s) remaining
Completed 22.4 MiB/233.2 MiB (20.2 MiB/s) with 8 file(s) remaining
Completed 22.6 MiB/233.2 MiB (20.4 MiB/s) with 8 file(s) remaining
Completed 22.9 MiB/233.2 MiB (20.6 MiB/s) with 8 file(s) remaining
Completed 23.1 MiB/233.2 MiB (20.8 MiB/s) with 8 file(s) remaining
Completed 23.4 MiB/233.2 MiB (21.0 MiB/s) with 8 file(s) remaining
Completed 23.6 MiB/233.2 MiB (21.2 MiB/s) with 8 file(s) remaining
Completed 23.9 MiB/233.2 MiB (21.4 MiB/s) with 8 file(s) remaining
Completed 24.1 MiB/233.2 MiB (21.6 MiB/s) with 8 file(s) remaining
Completed 24.4 MiB/233.2 MiB (21.5 MiB/s) with 8 file(s) remaining
Completed 24.6 MiB/233.2 MiB (21.7 MiB/s) with 8 file(s) remaining
Completed 24.9 MiB/233.2 MiB (21.9 MiB/s) with 8 file(s) remaining
Completed 25.1 MiB/233.2 MiB (21.9 MiB/s) with 8 file(s) remaining
Completed 25.4 MiB/233.2 MiB (22.1 MiB/s) with 8 file(s) remaining
Completed 25.6 MiB/233.2 MiB (22.3 MiB/s) with 8 file(s) remaining
Completed 25.9 MiB/233.2 MiB (22.3 MiB/s) with 8 file(s) remaining
Completed 26.1 MiB/233.2 MiB (22.5 MiB/s) with 8 file(s) remaining
Completed 26.4 MiB/233.2 MiB (22.7 MiB/s) with 8 file(s) remaining
Completed 26.6 MiB/233.2 MiB (22.7 MiB/s) with 8 file(s) remaining
Completed 26.9 MiB/233.2 MiB (22.9 MiB/s) with 8 file(s) remaining
Completed 27.1 MiB/233.2 MiB (23.1 MiB/s) with 8 file(s) remaining
Completed 27.4 MiB/233.2 MiB (23.3 MiB/s) with 8 file(s) remaining
Completed 27.6 MiB/233.2 MiB (23.5 MiB/s) with 8 file(s) remaining
Completed 27.9 MiB/233.2 MiB (23.7 MiB/s) with 8 file(s) remaining
Completed 28.1 MiB/233.2 MiB (23.9 MiB/s) with 8 file(s) remaining
Completed 28.4 MiB/233.2 MiB (23.9 MiB/s) with 8 file(s) remaining
Completed 28.6 MiB/233.2 MiB (24.1 MiB/s) with 8 file(s) remaining
Completed 28.9 MiB/233.2 MiB (24.2 MiB/s) with 8 file(s) remaining
upload: ../../../data/datafile-6-MB to s3://awscli-mint-test-bucket-917/datafile-6-MBCompleted 28.9 MiB/233.2 MiB (24.2 MiB/s) with 7 file(s) remaining
Completed 29.1 MiB/233.2 MiB (24.3 MiB/s) with 7 file(s) remaining
Completed 29.4 MiB/233.2 MiB (24.5 MiB/s) with 7 file(s) remaining
Completed 29.6 MiB/233.2 MiB (24.5 MiB/s) with 7 file(s) remaining
Completed 29.9 MiB/233.2 MiB (24.7 MiB/s) with 7 file(s) remaining
Completed 30.1 MiB/233.2 MiB (24.9 MiB/s) with 7 file(s) remaining
Completed 30.4 MiB/233.2 MiB (25.1 MiB/s) with 7 file(s) remaining
Completed 30.6 MiB/233.2 MiB (25.3 MiB/s) with 7 file(s) remaining
Completed 30.9 MiB/233.2 MiB (25.5 MiB/s) with 7 file(s) remaining
Completed 31.1 MiB/233.2 MiB (25.7 MiB/s) with 7 file(s) remaining
Completed 31.4 MiB/233.2 MiB (25.7 MiB/s) with 7 file(s) remaining
Completed 31.6 MiB/233.2 MiB (25.8 MiB/s) with 7 file(s) remaining
Completed 31.9 MiB/233.2 MiB (25.9 MiB/s) with 7 file(s) remaining
Completed 32.1 MiB/233.2 MiB (26.0 MiB/s) with 7 file(s) remaining
Completed 32.4 MiB/233.2 MiB (26.2 MiB/s) with 7 file(s) remaining
Completed 32.6 MiB/233.2 MiB (26.4 MiB/s) with 7 file(s) remaining
Completed 32.9 MiB/233.2 MiB (26.6 MiB/s) with 7 file(s) remaining
Completed 33.1 MiB/233.2 MiB (26.8 MiB/s) with 7 file(s) remaining
Completed 33.4 MiB/233.2 MiB (26.8 MiB/s) with 7 file(s) remaining
Completed 33.6 MiB/233.2 MiB (26.9 MiB/s) with 7 file(s) remaining
Completed 33.9 MiB/233.2 MiB (26.9 MiB/s) with 7 file(s) remaining
Completed 34.1 MiB/233.2 MiB (27.0 MiB/s) with 7 file(s) remaining
Completed 34.4 MiB/233.2 MiB (27.1 MiB/s) with 7 file(s) remaining
Completed 34.6 MiB/233.2 MiB (27.2 MiB/s) with 7 file(s) remaining
Completed 34.9 MiB/233.2 MiB (27.3 MiB/s) with 7 file(s) remaining
Completed 35.1 MiB/233.2 MiB (27.3 MiB/s) with 7 file(s) remaining
Completed 35.4 MiB/233.2 MiB (27.5 MiB/s) with 7 file(s) remaining
Completed 35.6 MiB/233.2 MiB (27.3 MiB/s) with 7 file(s) remaining
Completed 35.9 MiB/233.2 MiB (27.5 MiB/s) with 7 file(s) remaining
Completed 36.1 MiB/233.2 MiB (27.6 MiB/s) with 7 file(s) remaining
Completed 36.4 MiB/233.2 MiB (27.4 MiB/s) with 7 file(s) remaining
Completed 36.6 MiB/233.2 MiB (27.4 MiB/s) with 7 file(s) remaining
Completed 36.9 MiB/233.2 MiB (27.5 MiB/s) with 7 file(s) remaining
Completed 37.1 MiB/233.2 MiB (27.5 MiB/s) with 7 file(s) remaining
Completed 37.4 MiB/233.2 MiB (27.4 MiB/s) with 7 file(s) remaining
Completed 37.6 MiB/233.2 MiB (27.4 MiB/s) with 7 file(s) remaining
Completed 37.9 MiB/233.2 MiB (27.3 MiB/s) with 7 file(s) remaining
Completed 38.1 MiB/233.2 MiB (27.4 MiB/s) with 7 file(s) remaining
Completed 38.4 MiB/233.2 MiB (27.5 MiB/s) with 7 file(s) remaining
Completed 38.6 MiB/233.2 MiB (27.3 MiB/s) with 7 file(s) remaining
Completed 38.9 MiB/233.2 MiB (27.5 MiB/s) with 7 file(s) remaining
Completed 39.1 MiB/233.2 MiB (27.7 MiB/s) with 7 file(s) remaining
Completed 39.4 MiB/233.2 MiB (27.8 MiB/s) with 7 file(s) remaining
Completed 39.6 MiB/233.2 MiB (27.6 MiB/s) with 7 file(s) remaining
Completed 39.9 MiB/233.2 MiB (27.7 MiB/s) with 7 file(s) remaining
Completed 40.1 MiB/233.2 MiB (27.8 MiB/s) with 7 file(s) remaining
Completed 40.4 MiB/233.2 MiB (27.7 MiB/s) with 7 file(s) remaining
Completed 40.6 MiB/233.2 MiB (27.8 MiB/s) with 7 file(s) remaining
Completed 40.9 MiB/233.2 MiB (27.8 MiB/s) with 7 file(s) remaining
Completed 41.1 MiB/233.2 MiB (27.9 MiB/s) with 7 file(s) remaining
Completed 41.4 MiB/233.2 MiB (27.7 MiB/s) with 7 file(s) remaining
Completed 41.6 MiB/233.2 MiB (27.9 MiB/s) with 7 file(s) remaining
Completed 41.9 MiB/233.2 MiB (28.0 MiB/s) with 7 file(s) remaining
Completed 42.1 MiB/233.2 MiB (28.0 MiB/s) with 7 file(s) remaining
Completed 42.4 MiB/233.2 MiB (27.8 MiB/s) with 7 file(s) remaining
Completed 42.6 MiB/233.2 MiB (27.9 MiB/s) with 7 file(s) remaining
Completed 42.9 MiB/233.2 MiB (28.0 MiB/s) with 7 file(s) remaining
Completed 43.1 MiB/233.2 MiB (28.1 MiB/s) with 7 file(s) remaining
Completed 43.4 MiB/233.2 MiB (28.1 MiB/s) with 7 file(s) remaining
Completed 43.6 MiB/233.2 MiB (28.2 MiB/s) with 7 file(s) remaining
Completed 43.9 MiB/233.2 MiB (28.2 MiB/s) with 7 file(s) remaining
Completed 44.1 MiB/233.2 MiB (28.1 MiB/s) with 7 file(s) remaining
Completed 44.4 MiB/233.2 MiB (28.0 MiB/s) with 7 file(s) remaining
Completed 44.6 MiB/233.2 MiB (27.9 MiB/s) with 7 file(s) remaining
Completed 44.9 MiB/233.2 MiB (27.9 MiB/s) with 7 file(s) remaining
Completed 45.1 MiB/233.2 MiB (27.9 MiB/s) with 7 file(s) remaining
Completed 45.4 MiB/233.2 MiB (28.0 MiB/s) with 7 file(s) remaining
Completed 45.6 MiB/233.2 MiB (28.0 MiB/s) with 7 file(s) remaining
Completed 45.9 MiB/233.2 MiB (28.1 MiB/s) with 7 file(s) remaining
Completed 46.1 MiB/233.2 MiB (28.1 MiB/s) with 7 file(s) remaining
Completed 46.4 MiB/233.2 MiB (28.0 MiB/s) with 7 file(s) remaining
Completed 46.6 MiB/233.2 MiB (28.2 MiB/s) with 7 file(s) remaining
Completed 46.9 MiB/233.2 MiB (28.1 MiB/s) with 7 file(s) remaining
Completed 47.1 MiB/233.2 MiB (28.2 MiB/s) with 7 file(s) remaining
Completed 47.4 MiB/233.2 MiB (28.1 MiB/s) with 7 file(s) remaining
Completed 47.6 MiB/233.2 MiB (28.2 MiB/s) with 7 file(s) remaining
Completed 47.9 MiB/233.2 MiB (28.1 MiB/s) with 7 file(s) remaining
Completed 48.1 MiB/233.2 MiB (28.2 MiB/s) with 7 file(s) remaining
Completed 48.4 MiB/233.2 MiB (28.2 MiB/s) with 7 file(s) remaining
Completed 48.6 MiB/233.2 MiB (28.2 MiB/s) with 7 file(s) remaining
Completed 48.9 MiB/233.2 MiB (28.1 MiB/s) with 7 file(s) remaining
Completed 49.1 MiB/233.2 MiB (28.0 MiB/s) with 7 file(s) remaining
Completed 49.4 MiB/233.2 MiB (27.9 MiB/s) with 7 file(s) remaining
Completed 49.6 MiB/233.2 MiB (27.7 MiB/s) with 7 file(s) remaining
Completed 49.9 MiB/233.2 MiB (27.7 MiB/s) with 7 file(s) remaining
Completed 50.1 MiB/233.2 MiB (27.7 MiB/s) with 7 file(s) remaining
Completed 50.4 MiB/233.2 MiB (27.8 MiB/s) with 7 file(s) remaining
Completed 50.6 MiB/233.2 MiB (27.8 MiB/s) with 7 file(s) remaining
Completed 50.9 MiB/233.2 MiB (27.8 MiB/s) with 7 file(s) remaining
Completed 51.1 MiB/233.2 MiB (27.8 MiB/s) with 7 file(s) remaining
Completed 51.4 MiB/233.2 MiB (27.8 MiB/s) with 7 file(s) remaining
Completed 51.6 MiB/233.2 MiB (25.7 MiB/s) with 7 file(s) remaining
upload: ../../../data/datafile-1-MB to s3://awscli-mint-test-bucket-917/datafile-1-MBCompleted 51.6 MiB/233.2 MiB (25.7 MiB/s) with 6 file(s) remaining
Completed 51.9 MiB/233.2 MiB (25.6 MiB/s) with 6 file(s) remaining
Completed 52.1 MiB/233.2 MiB (25.5 MiB/s) with 6 file(s) remaining
Completed 52.4 MiB/233.2 MiB (25.5 MiB/s) with 6 file(s) remaining
Completed 52.6 MiB/233.2 MiB (25.5 MiB/s) with 6 file(s) remaining
Completed 52.9 MiB/233.2 MiB (25.4 MiB/s) with 6 file(s) remaining
Completed 53.1 MiB/233.2 MiB (25.4 MiB/s) with 6 file(s) remaining
Completed 53.4 MiB/233.2 MiB (25.4 MiB/s) with 6 file(s) remaining
Completed 53.6 MiB/233.2 MiB (25.4 MiB/s) with 6 file(s) remaining
Completed 53.9 MiB/233.2 MiB (25.4 MiB/s) with 6 file(s) remaining
Completed 54.1 MiB/233.2 MiB (25.4 MiB/s) with 6 file(s) remaining
Completed 54.4 MiB/233.2 MiB (25.4 MiB/s) with 6 file(s) remaining
Completed 54.6 MiB/233.2 MiB (25.4 MiB/s) with 6 file(s) remaining
Completed 54.9 MiB/233.2 MiB (25.4 MiB/s) with 6 file(s) remaining
Completed 55.1 MiB/233.2 MiB (25.5 MiB/s) with 6 file(s) remaining
Completed 55.4 MiB/233.2 MiB (25.6 MiB/s) with 6 file(s) remaining
Completed 55.6 MiB/233.2 MiB (25.7 MiB/s) with 6 file(s) remaining
Completed 55.9 MiB/233.2 MiB (25.8 MiB/s) with 6 file(s) remaining
Completed 56.1 MiB/233.2 MiB (25.9 MiB/s) with 6 file(s) remaining
Completed 56.4 MiB/233.2 MiB (25.9 MiB/s) with 6 file(s) remaining
Completed 56.6 MiB/233.2 MiB (25.9 MiB/s) with 6 file(s) remaining
Completed 56.9 MiB/233.2 MiB (25.9 MiB/s) with 6 file(s) remaining
Completed 57.1 MiB/233.2 MiB (25.9 MiB/s) with 6 file(s) remaining
Completed 57.4 MiB/233.2 MiB (25.9 MiB/s) with 6 file(s) remaining
Completed 57.6 MiB/233.2 MiB (25.9 MiB/s) with 6 file(s) remaining
Completed 57.9 MiB/233.2 MiB (25.9 MiB/s) with 6 file(s) remaining
Completed 58.1 MiB/233.2 MiB (25.9 MiB/s) with 6 file(s) remaining
Completed 58.4 MiB/233.2 MiB (25.9 MiB/s) with 6 file(s) remaining
Completed 58.6 MiB/233.2 MiB (25.8 MiB/s) with 6 file(s) remaining
Completed 58.9 MiB/233.2 MiB (25.8 MiB/s) with 6 file(s) remaining
Completed 59.1 MiB/233.2 MiB (25.8 MiB/s) with 6 file(s) remaining
Completed 59.4 MiB/233.2 MiB (25.8 MiB/s) with 6 file(s) remaining
Completed 59.6 MiB/233.2 MiB (25.8 MiB/s) with 6 file(s) remaining
Completed 59.9 MiB/233.2 MiB (25.9 MiB/s) with 6 file(s) remaining
Completed 60.1 MiB/233.2 MiB (25.9 MiB/s) with 6 file(s) remaining
Completed 60.4 MiB/233.2 MiB (25.9 MiB/s) with 6 file(s) remaining
Completed 60.6 MiB/233.2 MiB (26.0 MiB/s) with 6 file(s) remaining
Completed 60.9 MiB/233.2 MiB (26.0 MiB/s) with 6 file(s) remaining
Completed 61.1 MiB/233.2 MiB (26.0 MiB/s) with 6 file(s) remaining
Completed 61.4 MiB/233.2 MiB (26.0 MiB/s) with 6 file(s) remaining
Completed 61.6 MiB/233.2 MiB (26.0 MiB/s) with 6 file(s) remaining
Completed 61.9 MiB/233.2 MiB (26.0 MiB/s) with 6 file(s) remaining
Completed 62.1 MiB/233.2 MiB (26.0 MiB/s) with 6 file(s) remaining
Completed 62.4 MiB/233.2 MiB (26.1 MiB/s) with 6 file(s) remaining
Completed 62.6 MiB/233.2 MiB (26.1 MiB/s) with 6 file(s) remaining
Completed 62.9 MiB/233.2 MiB (26.1 MiB/s) with 6 file(s) remaining
Completed 63.1 MiB/233.2 MiB (26.1 MiB/s) with 6 file(s) remaining
Completed 63.4 MiB/233.2 MiB (25.1 MiB/s) with 6 file(s) remaining
Completed 63.6 MiB/233.2 MiB (25.2 MiB/s) with 6 file(s) remaining
Completed 63.9 MiB/233.2 MiB (25.3 MiB/s) with 6 file(s) remaining
Completed 64.1 MiB/233.2 MiB (25.4 MiB/s) with 6 file(s) remaining
Completed 64.4 MiB/233.2 MiB (25.4 MiB/s) with 6 file(s) remaining
upload failed: ../../../data/datafile-10-MB to s3://awscli-mint-test-bucket-917/datafile-10-MB An error occurred (InvalidPart) when calling the CompleteMultipartUpload operation: One or more of the specified parts could not be found.  The part may not have been uploaded, or the specified entity tag may not match the part's entity tag.Completed 64.4 MiB/233.2 MiB (25.4 MiB/s) with 5 file(s) remaining
Completed 64.6 MiB/233.2 MiB (25.4 MiB/s) with 5 file(s) remaining
Completed 64.9 MiB/233.2 MiB (25.3 MiB/s) with 5 file(s) remaining
Completed 65.1 MiB/233.2 MiB (25.2 MiB/s) with 5 file(s) remaining
Completed 65.4 MiB/233.2 MiB (25.2 MiB/s) with 5 file(s) remaining
Completed 65.6 MiB/233.2 MiB (25.2 MiB/s) with 5 file(s) remaining
upload: ../../../data/datafile-11-MB to s3://awscli-mint-test-bucket-917/datafile-11-MBCompleted 65.6 MiB/233.2 MiB (25.2 MiB/s) with 4 file(s) remaining
Completed 65.9 MiB/233.2 MiB (25.2 MiB/s) with 4 file(s) remaining
Completed 65.9 MiB/233.2 MiB (25.1 MiB/s) with 4 file(s) remaining
upload: ../../../data/datafile-5243880-b to s3://awscli-mint-test-bucket-917/datafile-5243880-bCompleted 65.9 MiB/233.2 MiB (25.1 MiB/s) with 3 file(s) remaining
Completed 66.1 MiB/233.2 MiB (25.2 MiB/s) with 3 file(s) remaining
Completed 66.4 MiB/233.2 MiB (25.1 MiB/s) with 3 file(s) remaining
Completed 66.6 MiB/233.2 MiB (25.1 MiB/s) with 3 file(s) remaining
Completed 66.9 MiB/233.2 MiB (25.1 MiB/s) with 3 file(s) remaining
Completed 67.1 MiB/233.2 MiB (25.1 MiB/s) with 3 file(s) remaining
Completed 67.4 MiB/233.2 MiB (25.1 MiB/s) with 3 file(s) remaining
Completed 67.6 MiB/233.2 MiB (25.1 MiB/s) with 3 file(s) remaining
Completed 67.9 MiB/233.2 MiB (25.1 MiB/s) with 3 file(s) remaining
Completed 68.1 MiB/233.2 MiB (25.1 MiB/s) with 3 file(s) remaining
Completed 68.4 MiB/233.2 MiB (25.1 MiB/s) with 3 file(s) remaining
Completed 68.6 MiB/233.2 MiB (25.2 MiB/s) with 3 file(s) remaining
Completed 68.9 MiB/233.2 MiB (25.2 MiB/s) with 3 file(s) remaining
Completed 69.1 MiB/233.2 MiB (25.3 MiB/s) with 3 file(s) remaining
Completed 69.4 MiB/233.2 MiB (25.4 MiB/s) with 3 file(s) remaining
Completed 69.6 MiB/233.2 MiB (25.5 MiB/s) with 3 file(s) remaining
Completed 69.9 MiB/233.2 MiB (25.5 MiB/s) with 3 file(s) remaining
Completed 70.1 MiB/233.2 MiB (25.6 MiB/s) with 3 file(s) remaining
Completed 70.4 MiB/233.2 MiB (25.6 MiB/s) with 3 file(s) remaining
Completed 70.6 MiB/233.2 MiB (25.7 MiB/s) with 3 file(s) remaining
Completed 70.9 MiB/233.2 MiB (25.7 MiB/s) with 3 file(s) remaining
Completed 71.1 MiB/233.2 MiB (25.8 MiB/s) with 3 file(s) remaining
Completed 71.4 MiB/233.2 MiB (25.8 MiB/s) with 3 file(s) remaining
Completed 71.6 MiB/233.2 MiB (25.9 MiB/s) with 3 file(s) remaining
Completed 71.9 MiB/233.2 MiB (25.9 MiB/s) with 3 file(s) remaining
Completed 72.1 MiB/233.2 MiB (26.0 MiB/s) with 3 file(s) remaining
Completed 72.4 MiB/233.2 MiB (25.9 MiB/s) with 3 file(s) remaining
Completed 72.6 MiB/233.2 MiB (26.0 MiB/s) with 3 file(s) remaining
Completed 72.9 MiB/233.2 MiB (26.0 MiB/s) with 3 file(s) remaining
Completed 73.1 MiB/233.2 MiB (26.1 MiB/s) with 3 file(s) remaining
Completed 73.4 MiB/233.2 MiB (26.1 MiB/s) with 3 file(s) remaining
Completed 73.6 MiB/233.2 MiB (26.2 MiB/s) with 3 file(s) remaining
Completed 73.9 MiB/233.2 MiB (26.2 MiB/s) with 3 file(s) remaining
Completed 74.1 MiB/233.2 MiB (26.3 MiB/s) with 3 file(s) remaining
Completed 74.4 MiB/233.2 MiB (26.3 MiB/s) with 3 file(s) remaining
Completed 74.6 MiB/233.2 MiB (26.3 MiB/s) with 3 file(s) remaining
Completed 74.9 MiB/233.2 MiB (26.3 MiB/s) with 3 file(s) remaining
Completed 75.1 MiB/233.2 MiB (26.3 MiB/s) with 3 file(s) remaining
Completed 75.4 MiB/233.2 MiB (26.3 MiB/s) with 3 file(s) remaining
Completed 75.6 MiB/233.2 MiB (26.4 MiB/s) with 3 file(s) remaining
Completed 75.9 MiB/233.2 MiB (26.5 MiB/s) with 3 file(s) remaining
Completed 76.1 MiB/233.2 MiB (26.6 MiB/s) with 3 file(s) remaining
Completed 76.4 MiB/233.2 MiB (26.6 MiB/s) with 3 file(s) remaining
Completed 76.6 MiB/233.2 MiB (26.6 MiB/s) with 3 file(s) remaining
Completed 76.9 MiB/233.2 MiB (26.7 MiB/s) with 3 file(s) remaining
Completed 77.1 MiB/233.2 MiB (26.8 MiB/s) with 3 file(s) remaining
Completed 77.4 MiB/233.2 MiB (26.9 MiB/s) with 3 file(s) remaining
Completed 77.6 MiB/233.2 MiB (27.0 MiB/s) with 3 file(s) remaining
Completed 77.9 MiB/233.2 MiB (27.0 MiB/s) with 3 file(s) remaining
Completed 78.1 MiB/233.2 MiB (27.0 MiB/s) with 3 file(s) remaining
Completed 78.4 MiB/233.2 MiB (27.1 MiB/s) with 3 file(s) remaining
Completed 78.6 MiB/233.2 MiB (27.2 MiB/s) with 3 file(s) remaining
Completed 78.9 MiB/233.2 MiB (27.3 MiB/s) with 3 file(s) remaining
Completed 79.1 MiB/233.2 MiB (27.4 MiB/s) with 3 file(s) remaining
Completed 79.4 MiB/233.2 MiB (27.4 MiB/s) with 3 file(s) remaining
Completed 79.6 MiB/233.2 MiB (27.4 MiB/s) with 3 file(s) remaining
Completed 79.9 MiB/233.2 MiB (27.5 MiB/s) with 3 file(s) remaining
Completed 80.1 MiB/233.2 MiB (27.5 MiB/s) with 3 file(s) remaining
Completed 80.4 MiB/233.2 MiB (27.6 MiB/s) with 3 file(s) remaining
Completed 80.6 MiB/233.2 MiB (27.6 MiB/s) with 3 file(s) remaining
Completed 80.9 MiB/233.2 MiB (27.6 MiB/s) with 3 file(s) remaining
Completed 81.1 MiB/233.2 MiB (27.7 MiB/s) with 3 file(s) remaining
Completed 81.4 MiB/233.2 MiB (27.8 MiB/s) with 3 file(s) remaining
Completed 81.6 MiB/233.2 MiB (27.8 MiB/s) with 3 file(s) remaining
Completed 81.9 MiB/233.2 MiB (27.8 MiB/s) with 3 file(s) remaining
Completed 82.1 MiB/233.2 MiB (27.9 MiB/s) with 3 file(s) remaining
Completed 82.4 MiB/233.2 MiB (28.0 MiB/s) with 3 file(s) remaining
Completed 82.6 MiB/233.2 MiB (28.0 MiB/s) with 3 file(s) remaining
Completed 82.9 MiB/233.2 MiB (28.1 MiB/s) with 3 file(s) remaining
Completed 83.1 MiB/233.2 MiB (28.1 MiB/s) with 3 file(s) remaining
Completed 83.4 MiB/233.2 MiB (28.1 MiB/s) with 3 file(s) remaining
Completed 83.6 MiB/233.2 MiB (28.2 MiB/s) with 3 file(s) remaining
Completed 83.9 MiB/233.2 MiB (28.3 MiB/s) with 3 file(s) remaining
Completed 84.1 MiB/233.2 MiB (28.3 MiB/s) with 3 file(s) remaining
Completed 84.4 MiB/233.2 MiB (28.4 MiB/s) with 3 file(s) remaining
Completed 84.6 MiB/233.2 MiB (28.4 MiB/s) with 3 file(s) remaining
Completed 84.9 MiB/233.2 MiB (28.4 MiB/s) with 3 file(s) remaining
Completed 85.1 MiB/233.2 MiB (28.5 MiB/s) with 3 file(s) remaining
Completed 85.4 MiB/233.2 MiB (28.6 MiB/s) with 3 file(s) remaining
Completed 85.6 MiB/233.2 MiB (28.6 MiB/s) with 3 file(s) remaining
Completed 85.9 MiB/233.2 MiB (28.6 MiB/s) with 3 file(s) remaining
Completed 86.1 MiB/233.2 MiB (28.7 MiB/s) with 3 file(s) remaining
Completed 86.4 MiB/233.2 MiB (28.7 MiB/s) with 3 file(s) remaining
Completed 86.6 MiB/233.2 MiB (28.8 MiB/s) with 3 file(s) remaining
Completed 86.9 MiB/233.2 MiB (28.8 MiB/s) with 3 file(s) remaining
Completed 87.1 MiB/233.2 MiB (28.8 MiB/s) with 3 file(s) remaining
Completed 87.4 MiB/233.2 MiB (28.9 MiB/s) with 3 file(s) remaining
Completed 87.6 MiB/233.2 MiB (29.0 MiB/s) with 3 file(s) remaining
Completed 87.9 MiB/233.2 MiB (29.0 MiB/s) with 3 file(s) remaining
Completed 88.1 MiB/233.2 MiB (29.0 MiB/s) with 3 file(s) remaining
Completed 88.4 MiB/233.2 MiB (29.1 MiB/s) with 3 file(s) remaining
Completed 88.6 MiB/233.2 MiB (29.1 MiB/s) with 3 file(s) remaining
Completed 88.9 MiB/233.2 MiB (29.2 MiB/s) with 3 file(s) remaining
Completed 89.1 MiB/233.2 MiB (29.3 MiB/s) with 3 file(s) remaining
Completed 89.4 MiB/233.2 MiB (29.3 MiB/s) with 3 file(s) remaining
Completed 89.6 MiB/233.2 MiB (29.4 MiB/s) with 3 file(s) remaining
Completed 89.9 MiB/233.2 MiB (29.5 MiB/s) with 3 file(s) remaining
Completed 90.1 MiB/233.2 MiB (29.5 MiB/s) with 3 file(s) remaining
Completed 90.4 MiB/233.2 MiB (29.6 MiB/s) with 3 file(s) remaining
Completed 90.6 MiB/233.2 MiB (29.6 MiB/s) with 3 file(s) remaining
Completed 90.9 MiB/233.2 MiB (29.7 MiB/s) with 3 file(s) remaining
Completed 91.1 MiB/233.2 MiB (29.7 MiB/s) with 3 file(s) remaining
Completed 91.4 MiB/233.2 MiB (29.7 MiB/s) with 3 file(s) remaining
Completed 91.6 MiB/233.2 MiB (29.8 MiB/s) with 3 file(s) remaining
Completed 91.9 MiB/233.2 MiB (29.8 MiB/s) with 3 file(s) remaining
Completed 92.1 MiB/233.2 MiB (29.9 MiB/s) with 3 file(s) remaining
Completed 92.4 MiB/233.2 MiB (29.9 MiB/s) with 3 file(s) remaining
Completed 92.6 MiB/233.2 MiB (29.9 MiB/s) with 3 file(s) remaining
Completed 92.9 MiB/233.2 MiB (30.0 MiB/s) with 3 file(s) remaining
Completed 93.1 MiB/233.2 MiB (30.1 MiB/s) with 3 file(s) remaining
Completed 93.4 MiB/233.2 MiB (30.0 MiB/s) with 3 file(s) remaining
Completed 93.6 MiB/233.2 MiB (30.1 MiB/s) with 3 file(s) remaining
Completed 93.9 MiB/233.2 MiB (30.1 MiB/s) with 3 file(s) remaining
Completed 94.1 MiB/233.2 MiB (30.2 MiB/s) with 3 file(s) remaining
Completed 94.4 MiB/233.2 MiB (30.2 MiB/s) with 3 file(s) remaining
Completed 94.6 MiB/233.2 MiB (30.3 MiB/s) with 3 file(s) remaining
Completed 94.9 MiB/233.2 MiB (30.3 MiB/s) with 3 file(s) remaining
Completed 95.1 MiB/233.2 MiB (30.3 MiB/s) with 3 file(s) remaining
Completed 95.4 MiB/233.2 MiB (30.4 MiB/s) with 3 file(s) remaining
Completed 95.6 MiB/233.2 MiB (30.4 MiB/s) with 3 file(s) remaining
Completed 95.9 MiB/233.2 MiB (30.5 MiB/s) with 3 file(s) remaining
Completed 96.1 MiB/233.2 MiB (30.5 MiB/s) with 3 file(s) remaining
Completed 96.4 MiB/233.2 MiB (30.5 MiB/s) with 3 file(s) remaining
Completed 96.6 MiB/233.2 MiB (30.6 MiB/s) with 3 file(s) remaining
Completed 96.9 MiB/233.2 MiB (30.6 MiB/s) with 3 file(s) remaining
Completed 97.1 MiB/233.2 MiB (30.7 MiB/s) with 3 file(s) remaining
Completed 97.4 MiB/233.2 MiB (30.7 MiB/s) with 3 file(s) remaining
Completed 97.6 MiB/233.2 MiB (30.8 MiB/s) with 3 file(s) remaining
Completed 97.9 MiB/233.2 MiB (30.8 MiB/s) with 3 file(s) remaining
Completed 98.1 MiB/233.2 MiB (30.8 MiB/s) with 3 file(s) remaining
Completed 98.4 MiB/233.2 MiB (30.9 MiB/s) with 3 file(s) remaining
Completed 98.6 MiB/233.2 MiB (30.9 MiB/s) with 3 file(s) remaining
Completed 98.9 MiB/233.2 MiB (31.0 MiB/s) with 3 file(s) remaining
Completed 99.1 MiB/233.2 MiB (31.1 MiB/s) with 3 file(s) remaining
Completed 99.4 MiB/233.2 MiB (31.2 MiB/s) with 3 file(s) remaining
Completed 99.6 MiB/233.2 MiB (31.2 MiB/s) with 3 file(s) remaining
Completed 99.9 MiB/233.2 MiB (31.3 MiB/s) with 3 file(s) remaining
Completed 100.1 MiB/233.2 MiB (31.3 MiB/s) with 3 file(s) remaining
Completed 100.4 MiB/233.2 MiB (31.4 MiB/s) with 3 file(s) remaining
Completed 100.6 MiB/233.2 MiB (31.4 MiB/s) with 3 file(s) remaining
Completed 100.9 MiB/233.2 MiB (31.4 MiB/s) with 3 file(s) remaining
Completed 101.1 MiB/233.2 MiB (31.5 MiB/s) with 3 file(s) remaining
Completed 101.4 MiB/233.2 MiB (31.6 MiB/s) with 3 file(s) remaining
Completed 101.6 MiB/233.2 MiB (31.6 MiB/s) with 3 file(s) remaining
Completed 101.9 MiB/233.2 MiB (31.6 MiB/s) with 3 file(s) remaining
Completed 102.1 MiB/233.2 MiB (31.7 MiB/s) with 3 file(s) remaining
Completed 102.4 MiB/233.2 MiB (31.7 MiB/s) with 3 file(s) remaining
Completed 102.6 MiB/233.2 MiB (31.8 MiB/s) with 3 file(s) remaining
Completed 102.9 MiB/233.2 MiB (31.8 MiB/s) with 3 file(s) remaining
Completed 103.1 MiB/233.2 MiB (31.9 MiB/s) with 3 file(s) remaining
Completed 103.4 MiB/233.2 MiB (31.9 MiB/s) with 3 file(s) remaining
Completed 103.6 MiB/233.2 MiB (32.0 MiB/s) with 3 file(s) remaining
Completed 103.9 MiB/233.2 MiB (32.0 MiB/s) with 3 file(s) remaining
Completed 104.1 MiB/233.2 MiB (32.0 MiB/s) with 3 file(s) remaining
Completed 104.4 MiB/233.2 MiB (32.0 MiB/s) with 3 file(s) remaining
Completed 104.6 MiB/233.2 MiB (32.1 MiB/s) with 3 file(s) remaining
Completed 104.9 MiB/233.2 MiB (32.0 MiB/s) with 3 file(s) remaining
Completed 105.1 MiB/233.2 MiB (32.1 MiB/s) with 3 file(s) remaining
Completed 105.4 MiB/233.2 MiB (32.1 MiB/s) with 3 file(s) remaining
Completed 105.6 MiB/233.2 MiB (32.1 MiB/s) with 3 file(s) remaining
Completed 105.9 MiB/233.2 MiB (32.1 MiB/s) with 3 file(s) remaining
Completed 106.1 MiB/233.2 MiB (32.0 MiB/s) with 3 file(s) remaining
Completed 106.4 MiB/233.2 MiB (32.1 MiB/s) with 3 file(s) remaining
Completed 106.6 MiB/233.2 MiB (32.0 MiB/s) with 3 file(s) remaining
Completed 106.9 MiB/233.2 MiB (31.9 MiB/s) with 3 file(s) remaining
Completed 107.1 MiB/233.2 MiB (31.9 MiB/s) with 3 file(s) remaining
Completed 107.4 MiB/233.2 MiB (31.9 MiB/s) with 3 file(s) remaining
Completed 107.6 MiB/233.2 MiB (32.0 MiB/s) with 3 file(s) remaining
Completed 107.9 MiB/233.2 MiB (32.1 MiB/s) with 3 file(s) remaining
Completed 108.1 MiB/233.2 MiB (32.1 MiB/s) with 3 file(s) remaining
Completed 108.4 MiB/233.2 MiB (32.2 MiB/s) with 3 file(s) remaining
Completed 108.6 MiB/233.2 MiB (32.2 MiB/s) with 3 file(s) remaining
Completed 108.9 MiB/233.2 MiB (32.2 MiB/s) with 3 file(s) remaining
Completed 109.1 MiB/233.2 MiB (32.1 MiB/s) with 3 file(s) remaining
Completed 109.4 MiB/233.2 MiB (32.2 MiB/s) with 3 file(s) remaining
Completed 109.6 MiB/233.2 MiB (32.1 MiB/s) with 3 file(s) remaining
Completed 109.9 MiB/233.2 MiB (32.1 MiB/s) with 3 file(s) remaining
Completed 110.1 MiB/233.2 MiB (32.2 MiB/s) with 3 file(s) remaining
Completed 110.4 MiB/233.2 MiB (32.1 MiB/s) with 3 file(s) remaining
Completed 110.6 MiB/233.2 MiB (32.2 MiB/s) with 3 file(s) remaining
Completed 110.9 MiB/233.2 MiB (32.2 MiB/s) with 3 file(s) remaining
Completed 111.1 MiB/233.2 MiB (32.1 MiB/s) with 3 file(s) remaining
Completed 111.4 MiB/233.2 MiB (32.0 MiB/s) with 3 file(s) remaining
Completed 111.6 MiB/233.2 MiB (32.1 MiB/s) with 3 file(s) remaining
Completed 111.9 MiB/233.2 MiB (32.0 MiB/s) with 3 file(s) remaining
Completed 112.1 MiB/233.2 MiB (32.1 MiB/s) with 3 file(s) remaining
Completed 112.4 MiB/233.2 MiB (32.0 MiB/s) with 3 file(s) remaining
Completed 112.6 MiB/233.2 MiB (32.1 MiB/s) with 3 file(s) remaining
Completed 112.9 MiB/233.2 MiB (32.0 MiB/s) with 3 file(s) remaining
Completed 113.1 MiB/233.2 MiB (32.1 MiB/s) with 3 file(s) remaining
Completed 113.4 MiB/233.2 MiB (32.1 MiB/s) with 3 file(s) remaining
Completed 113.6 MiB/233.2 MiB (32.1 MiB/s) with 3 file(s) remaining
Completed 113.9 MiB/233.2 MiB (32.2 MiB/s) with 3 file(s) remaining
Completed 114.1 MiB/233.2 MiB (32.3 MiB/s) with 3 file(s) remaining
Completed 114.4 MiB/233.2 MiB (32.3 MiB/s) with 3 file(s) remaining
Completed 114.6 MiB/233.2 MiB (32.3 MiB/s) with 3 file(s) remaining
Completed 114.9 MiB/233.2 MiB (32.4 MiB/s) with 3 file(s) remaining
Completed 115.1 MiB/233.2 MiB (32.4 MiB/s) with 3 file(s) remaining
Completed 115.4 MiB/233.2 MiB (32.4 MiB/s) with 3 file(s) remaining
Completed 115.6 MiB/233.2 MiB (32.5 MiB/s) with 3 file(s) remaining
Completed 115.9 MiB/233.2 MiB (32.5 MiB/s) with 3 file(s) remaining
Completed 116.1 MiB/233.2 MiB (32.5 MiB/s) with 3 file(s) remaining
Completed 116.4 MiB/233.2 MiB (32.6 MiB/s) with 3 file(s) remaining
Completed 116.6 MiB/233.2 MiB (32.6 MiB/s) with 3 file(s) remaining
Completed 116.9 MiB/233.2 MiB (32.6 MiB/s) with 3 file(s) remaining
Completed 117.1 MiB/233.2 MiB (32.6 MiB/s) with 3 file(s) remaining
Completed 117.4 MiB/233.2 MiB (32.7 MiB/s) with 3 file(s) remaining
Completed 117.6 MiB/233.2 MiB (32.7 MiB/s) with 3 file(s) remaining
Completed 117.9 MiB/233.2 MiB (32.7 MiB/s) with 3 file(s) remaining
Completed 118.1 MiB/233.2 MiB (32.7 MiB/s) with 3 file(s) remaining
Completed 118.4 MiB/233.2 MiB (32.8 MiB/s) with 3 file(s) remaining
Completed 118.6 MiB/233.2 MiB (32.8 MiB/s) with 3 file(s) remaining
Completed 118.9 MiB/233.2 MiB (32.8 MiB/s) with 3 file(s) remaining
Completed 119.1 MiB/233.2 MiB (32.9 MiB/s) with 3 file(s) remaining
Completed 119.4 MiB/233.2 MiB (32.9 MiB/s) with 3 file(s) remaining
Completed 119.6 MiB/233.2 MiB (32.9 MiB/s) with 3 file(s) remaining
Completed 119.9 MiB/233.2 MiB (32.9 MiB/s) with 3 file(s) remaining
Completed 120.1 MiB/233.2 MiB (32.9 MiB/s) with 3 file(s) remaining
Completed 120.4 MiB/233.2 MiB (33.0 MiB/s) with 3 file(s) remaining
Completed 120.6 MiB/233.2 MiB (33.0 MiB/s) with 3 file(s) remaining
Completed 120.9 MiB/233.2 MiB (33.0 MiB/s) with 3 file(s) remaining
Completed 121.1 MiB/233.2 MiB (33.1 MiB/s) with 3 file(s) remaining
Completed 121.4 MiB/233.2 MiB (33.1 MiB/s) with 3 file(s) remaining
Completed 121.6 MiB/233.2 MiB (33.1 MiB/s) with 3 file(s) remaining
Completed 121.9 MiB/233.2 MiB (33.2 MiB/s) with 3 file(s) remaining
Completed 122.1 MiB/233.2 MiB (33.1 MiB/s) with 3 file(s) remaining
Completed 122.4 MiB/233.2 MiB (33.2 MiB/s) with 3 file(s) remaining
Completed 122.6 MiB/233.2 MiB (33.3 MiB/s) with 3 file(s) remaining
Completed 122.9 MiB/233.2 MiB (33.3 MiB/s) with 3 file(s) remaining
Completed 123.1 MiB/233.2 MiB (33.4 MiB/s) with 3 file(s) remaining
Completed 123.4 MiB/233.2 MiB (33.4 MiB/s) with 3 file(s) remaining
Completed 123.6 MiB/233.2 MiB (33.5 MiB/s) with 3 file(s) remaining
Completed 123.9 MiB/233.2 MiB (33.5 MiB/s) with 3 file(s) remaining
Completed 124.1 MiB/233.2 MiB (33.6 MiB/s) with 3 file(s) remaining
Completed 124.4 MiB/233.2 MiB (33.5 MiB/s) with 3 file(s) remaining
Completed 124.6 MiB/233.2 MiB (33.6 MiB/s) with 3 file(s) remaining
Completed 124.9 MiB/233.2 MiB (33.6 MiB/s) with 3 file(s) remaining
Completed 125.1 MiB/233.2 MiB (33.6 MiB/s) with 3 file(s) remaining
Completed 125.4 MiB/233.2 MiB (33.6 MiB/s) with 3 file(s) remaining
Completed 125.6 MiB/233.2 MiB (33.7 MiB/s) with 3 file(s) remaining
Completed 125.9 MiB/233.2 MiB (33.7 MiB/s) with 3 file(s) remaining
Completed 126.1 MiB/233.2 MiB (33.7 MiB/s) with 3 file(s) remaining
Completed 126.4 MiB/233.2 MiB (33.7 MiB/s) with 3 file(s) remaining
Completed 126.6 MiB/233.2 MiB (33.7 MiB/s) with 3 file(s) remaining
Completed 126.9 MiB/233.2 MiB (33.8 MiB/s) with 3 file(s) remaining
Completed 127.1 MiB/233.2 MiB (33.8 MiB/s) with 3 file(s) remaining
Completed 127.4 MiB/233.2 MiB (33.8 MiB/s) with 3 file(s) remaining
Completed 127.6 MiB/233.2 MiB (33.8 MiB/s) with 3 file(s) remaining
Completed 127.9 MiB/233.2 MiB (33.8 MiB/s) with 3 file(s) remaining
Completed 128.1 MiB/233.2 MiB (33.8 MiB/s) with 3 file(s) remaining
Completed 128.4 MiB/233.2 MiB (33.8 MiB/s) with 3 file(s) remaining
Completed 128.6 MiB/233.2 MiB (33.8 MiB/s) with 3 file(s) remaining
Completed 128.9 MiB/233.2 MiB (33.8 MiB/s) with 3 file(s) remaining
Completed 129.1 MiB/233.2 MiB (33.8 MiB/s) with 3 file(s) remaining
Completed 129.4 MiB/233.2 MiB (33.8 MiB/s) with 3 file(s) remaining
Completed 129.6 MiB/233.2 MiB (33.9 MiB/s) with 3 file(s) remaining
Completed 129.9 MiB/233.2 MiB (33.9 MiB/s) with 3 file(s) remaining
Completed 130.1 MiB/233.2 MiB (33.9 MiB/s) with 3 file(s) remaining
Completed 130.4 MiB/233.2 MiB (33.9 MiB/s) with 3 file(s) remaining
Completed 130.6 MiB/233.2 MiB (33.9 MiB/s) with 3 file(s) remaining
Completed 130.9 MiB/233.2 MiB (33.9 MiB/s) with 3 file(s) remaining
Completed 131.1 MiB/233.2 MiB (33.9 MiB/s) with 3 file(s) remaining
Completed 131.4 MiB/233.2 MiB (33.9 MiB/s) with 3 file(s) remaining
Completed 131.6 MiB/233.2 MiB (33.9 MiB/s) with 3 file(s) remaining
Completed 131.9 MiB/233.2 MiB (34.0 MiB/s) with 3 file(s) remaining
Completed 132.1 MiB/233.2 MiB (34.0 MiB/s) with 3 file(s) remaining
Completed 132.4 MiB/233.2 MiB (34.0 MiB/s) with 3 file(s) remaining
Completed 132.6 MiB/233.2 MiB (34.0 MiB/s) with 3 file(s) remaining
Completed 132.9 MiB/233.2 MiB (34.0 MiB/s) with 3 file(s) remaining
Completed 133.1 MiB/233.2 MiB (34.1 MiB/s) with 3 file(s) remaining
Completed 133.4 MiB/233.2 MiB (34.1 MiB/s) with 3 file(s) remaining
Completed 133.6 MiB/233.2 MiB (34.2 MiB/s) with 3 file(s) remaining
Completed 133.9 MiB/233.2 MiB (34.2 MiB/s) with 3 file(s) remaining
Completed 134.1 MiB/233.2 MiB (34.3 MiB/s) with 3 file(s) remaining
Completed 134.4 MiB/233.2 MiB (34.3 MiB/s) with 3 file(s) remaining
Completed 134.6 MiB/233.2 MiB (34.4 MiB/s) with 3 file(s) remaining
Completed 134.9 MiB/233.2 MiB (34.4 MiB/s) with 3 file(s) remaining
Completed 135.1 MiB/233.2 MiB (34.4 MiB/s) with 3 file(s) remaining
Completed 135.4 MiB/233.2 MiB (34.4 MiB/s) with 3 file(s) remaining
Completed 135.6 MiB/233.2 MiB (34.5 MiB/s) with 3 file(s) remaining
Completed 135.9 MiB/233.2 MiB (34.5 MiB/s) with 3 file(s) remaining
Completed 136.1 MiB/233.2 MiB (34.6 MiB/s) with 3 file(s) remaining
Completed 136.4 MiB/233.2 MiB (34.5 MiB/s) with 3 file(s) remaining
Completed 136.6 MiB/233.2 MiB (34.6 MiB/s) with 3 file(s) remaining
Completed 136.9 MiB/233.2 MiB (34.6 MiB/s) with 3 file(s) remaining
Completed 137.1 MiB/233.2 MiB (34.6 MiB/s) with 3 file(s) remaining
Completed 137.4 MiB/233.2 MiB (34.6 MiB/s) with 3 file(s) remaining
Completed 137.6 MiB/233.2 MiB (34.6 MiB/s) with 3 file(s) remaining
Completed 137.9 MiB/233.2 MiB (34.6 MiB/s) with 3 file(s) remaining
Completed 138.1 MiB/233.2 MiB (34.7 MiB/s) with 3 file(s) remaining
Completed 138.4 MiB/233.2 MiB (34.7 MiB/s) with 3 file(s) remaining
Completed 138.6 MiB/233.2 MiB (34.7 MiB/s) with 3 file(s) remaining
Completed 138.9 MiB/233.2 MiB (34.7 MiB/s) with 3 file(s) remaining
Completed 139.1 MiB/233.2 MiB (34.7 MiB/s) with 3 file(s) remaining
Completed 139.4 MiB/233.2 MiB (34.8 MiB/s) with 3 file(s) remaining
Completed 139.6 MiB/233.2 MiB (34.8 MiB/s) with 3 file(s) remaining
Completed 139.9 MiB/233.2 MiB (34.8 MiB/s) with 3 file(s) remaining
Completed 140.1 MiB/233.2 MiB (34.9 MiB/s) with 3 file(s) remaining
Completed 140.4 MiB/233.2 MiB (34.8 MiB/s) with 3 file(s) remaining
Completed 140.6 MiB/233.2 MiB (34.9 MiB/s) with 3 file(s) remaining
Completed 140.9 MiB/233.2 MiB (34.9 MiB/s) with 3 file(s) remaining
Completed 141.1 MiB/233.2 MiB (34.9 MiB/s) with 3 file(s) remaining
Completed 141.4 MiB/233.2 MiB (35.0 MiB/s) with 3 file(s) remaining
Completed 141.6 MiB/233.2 MiB (35.0 MiB/s) with 3 file(s) remaining
Completed 141.9 MiB/233.2 MiB (35.0 MiB/s) with 3 file(s) remaining
Completed 142.1 MiB/233.2 MiB (35.0 MiB/s) with 3 file(s) remaining
Completed 142.4 MiB/233.2 MiB (35.1 MiB/s) with 3 file(s) remaining
Completed 142.6 MiB/233.2 MiB (35.1 MiB/s) with 3 file(s) remaining
Completed 142.9 MiB/233.2 MiB (35.1 MiB/s) with 3 file(s) remaining
Completed 143.1 MiB/233.2 MiB (35.2 MiB/s) with 3 file(s) remaining
Completed 143.4 MiB/233.2 MiB (35.2 MiB/s) with 3 file(s) remaining
Completed 143.6 MiB/233.2 MiB (35.2 MiB/s) with 3 file(s) remaining
Completed 143.9 MiB/233.2 MiB (35.2 MiB/s) with 3 file(s) remaining
Completed 144.1 MiB/233.2 MiB (35.3 MiB/s) with 3 file(s) remaining
Completed 144.4 MiB/233.2 MiB (35.3 MiB/s) with 3 file(s) remaining
Completed 144.6 MiB/233.2 MiB (35.3 MiB/s) with 3 file(s) remaining
Completed 144.9 MiB/233.2 MiB (35.4 MiB/s) with 3 file(s) remaining
Completed 145.1 MiB/233.2 MiB (35.3 MiB/s) with 3 file(s) remaining
Completed 145.4 MiB/233.2 MiB (35.4 MiB/s) with 3 file(s) remaining
Completed 145.6 MiB/233.2 MiB (35.4 MiB/s) with 3 file(s) remaining
Completed 145.9 MiB/233.2 MiB (35.4 MiB/s) with 3 file(s) remaining
Completed 146.1 MiB/233.2 MiB (35.4 MiB/s) with 3 file(s) remaining
Completed 146.4 MiB/233.2 MiB (35.4 MiB/s) with 3 file(s) remaining
Completed 146.6 MiB/233.2 MiB (35.4 MiB/s) with 3 file(s) remaining
Completed 146.9 MiB/233.2 MiB (35.4 MiB/s) with 3 file(s) remaining
Completed 147.1 MiB/233.2 MiB (35.4 MiB/s) with 3 file(s) remaining
Completed 147.4 MiB/233.2 MiB (35.5 MiB/s) with 3 file(s) remaining
Completed 147.6 MiB/233.2 MiB (35.5 MiB/s) with 3 file(s) remaining
Completed 147.9 MiB/233.2 MiB (35.6 MiB/s) with 3 file(s) remaining
Completed 148.1 MiB/233.2 MiB (35.6 MiB/s) with 3 file(s) remaining
Completed 148.4 MiB/233.2 MiB (35.7 MiB/s) with 3 file(s) remaining
Completed 148.6 MiB/233.2 MiB (35.7 MiB/s) with 3 file(s) remaining
Completed 148.9 MiB/233.2 MiB (35.6 MiB/s) with 3 file(s) remaining
Completed 149.1 MiB/233.2 MiB (35.7 MiB/s) with 3 file(s) remaining
Completed 149.4 MiB/233.2 MiB (35.6 MiB/s) with 3 file(s) remaining
Completed 149.6 MiB/233.2 MiB (35.6 MiB/s) with 3 file(s) remaining
Completed 149.9 MiB/233.2 MiB (35.6 MiB/s) with 3 file(s) remaining
Completed 150.1 MiB/233.2 MiB (35.6 MiB/s) with 3 file(s) remaining
Completed 150.4 MiB/233.2 MiB (35.5 MiB/s) with 3 file(s) remaining
Completed 150.6 MiB/233.2 MiB (35.6 MiB/s) with 3 file(s) remaining
Completed 150.9 MiB/233.2 MiB (35.6 MiB/s) with 3 file(s) remaining
Completed 151.1 MiB/233.2 MiB (35.5 MiB/s) with 3 file(s) remaining
Completed 151.4 MiB/233.2 MiB (35.5 MiB/s) with 3 file(s) remaining
Completed 151.6 MiB/233.2 MiB (35.5 MiB/s) with 3 file(s) remaining
Completed 151.9 MiB/233.2 MiB (35.5 MiB/s) with 3 file(s) remaining
Completed 152.1 MiB/233.2 MiB (35.5 MiB/s) with 3 file(s) remaining
Completed 152.4 MiB/233.2 MiB (35.5 MiB/s) with 3 file(s) remaining
Completed 152.6 MiB/233.2 MiB (35.5 MiB/s) with 3 file(s) remaining
Completed 152.9 MiB/233.2 MiB (35.5 MiB/s) with 3 file(s) remaining
Completed 153.1 MiB/233.2 MiB (35.6 MiB/s) with 3 file(s) remaining
Completed 153.4 MiB/233.2 MiB (35.5 MiB/s) with 3 file(s) remaining
Completed 153.6 MiB/233.2 MiB (35.5 MiB/s) with 3 file(s) remaining
Completed 153.9 MiB/233.2 MiB (35.6 MiB/s) with 3 file(s) remaining
Completed 154.1 MiB/233.2 MiB (35.5 MiB/s) with 3 file(s) remaining
Completed 154.4 MiB/233.2 MiB (35.4 MiB/s) with 3 file(s) remaining
Completed 154.6 MiB/233.2 MiB (35.3 MiB/s) with 3 file(s) remaining
Completed 154.9 MiB/233.2 MiB (35.3 MiB/s) with 3 file(s) remaining
Completed 155.1 MiB/233.2 MiB (35.3 MiB/s) with 3 file(s) remaining
Completed 155.4 MiB/233.2 MiB (35.4 MiB/s) with 3 file(s) remaining
Completed 155.6 MiB/233.2 MiB (35.4 MiB/s) with 3 file(s) remaining
Completed 155.9 MiB/233.2 MiB (35.5 MiB/s) with 3 file(s) remaining
Completed 156.1 MiB/233.2 MiB (35.5 MiB/s) with 3 file(s) remaining
Completed 156.4 MiB/233.2 MiB (35.5 MiB/s) with 3 file(s) remaining
Completed 156.6 MiB/233.2 MiB (35.5 MiB/s) with 3 file(s) remaining
Completed 156.9 MiB/233.2 MiB (35.5 MiB/s) with 3 file(s) remaining
Completed 157.1 MiB/233.2 MiB (35.6 MiB/s) with 3 file(s) remaining
Completed 157.4 MiB/233.2 MiB (35.6 MiB/s) with 3 file(s) remaining
Completed 157.6 MiB/233.2 MiB (35.6 MiB/s) with 3 file(s) remaining
Completed 157.9 MiB/233.2 MiB (35.7 MiB/s) with 3 file(s) remaining
Completed 158.1 MiB/233.2 MiB (35.7 MiB/s) with 3 file(s) remaining
Completed 158.4 MiB/233.2 MiB (35.8 MiB/s) with 3 file(s) remaining
Completed 158.6 MiB/233.2 MiB (35.8 MiB/s) with 3 file(s) remaining
Completed 158.9 MiB/233.2 MiB (35.9 MiB/s) with 3 file(s) remaining
Completed 159.1 MiB/233.2 MiB (35.9 MiB/s) with 3 file(s) remaining
Completed 159.4 MiB/233.2 MiB (35.9 MiB/s) with 3 file(s) remaining
Completed 159.6 MiB/233.2 MiB (35.9 MiB/s) with 3 file(s) remaining
Completed 159.9 MiB/233.2 MiB (35.9 MiB/s) with 3 file(s) remaining
Completed 160.1 MiB/233.2 MiB (35.9 MiB/s) with 3 file(s) remaining
Completed 160.4 MiB/233.2 MiB (36.0 MiB/s) with 3 file(s) remaining
Completed 160.6 MiB/233.2 MiB (36.0 MiB/s) with 3 file(s) remaining
Completed 160.9 MiB/233.2 MiB (36.0 MiB/s) with 3 file(s) remaining
Completed 161.1 MiB/233.2 MiB (36.0 MiB/s) with 3 file(s) remaining
Completed 161.4 MiB/233.2 MiB (36.0 MiB/s) with 3 file(s) remaining
Completed 161.6 MiB/233.2 MiB (36.0 MiB/s) with 3 file(s) remaining
Completed 161.9 MiB/233.2 MiB (36.1 MiB/s) with 3 file(s) remaining
Completed 162.1 MiB/233.2 MiB (36.1 MiB/s) with 3 file(s) remaining
Completed 162.4 MiB/233.2 MiB (36.1 MiB/s) with 3 file(s) remaining
Completed 162.6 MiB/233.2 MiB (36.2 MiB/s) with 3 file(s) remaining
Completed 162.9 MiB/233.2 MiB (36.1 MiB/s) with 3 file(s) remaining
Completed 163.1 MiB/233.2 MiB (36.2 MiB/s) with 3 file(s) remaining
Completed 163.4 MiB/233.2 MiB (36.2 MiB/s) with 3 file(s) remaining
Completed 163.6 MiB/233.2 MiB (36.3 MiB/s) with 3 file(s) remaining
Completed 163.9 MiB/233.2 MiB (36.3 MiB/s) with 3 file(s) remaining
Completed 164.1 MiB/233.2 MiB (36.4 MiB/s) with 3 file(s) remaining
Completed 164.4 MiB/233.2 MiB (36.4 MiB/s) with 3 file(s) remaining
Completed 164.6 MiB/233.2 MiB (36.5 MiB/s) with 3 file(s) remaining
Completed 164.9 MiB/233.2 MiB (36.5 MiB/s) with 3 file(s) remaining
Completed 165.1 MiB/233.2 MiB (36.5 MiB/s) with 3 file(s) remaining
Completed 165.4 MiB/233.2 MiB (36.5 MiB/s) with 3 file(s) remaining
Completed 165.6 MiB/233.2 MiB (36.6 MiB/s) with 3 file(s) remaining
Completed 165.9 MiB/233.2 MiB (36.5 MiB/s) with 3 file(s) remaining
Completed 166.1 MiB/233.2 MiB (36.6 MiB/s) with 3 file(s) remaining
Completed 166.4 MiB/233.2 MiB (36.6 MiB/s) with 3 file(s) remaining
Completed 166.6 MiB/233.2 MiB (36.6 MiB/s) with 3 file(s) remaining
Completed 166.9 MiB/233.2 MiB (36.7 MiB/s) with 3 file(s) remaining
Completed 167.1 MiB/233.2 MiB (36.7 MiB/s) with 3 file(s) remaining
Completed 167.4 MiB/233.2 MiB (36.7 MiB/s) with 3 file(s) remaining
Completed 167.6 MiB/233.2 MiB (36.7 MiB/s) with 3 file(s) remaining
Completed 167.9 MiB/233.2 MiB (36.7 MiB/s) with 3 file(s) remaining
Completed 168.1 MiB/233.2 MiB (36.7 MiB/s) with 3 file(s) remaining
Completed 168.4 MiB/233.2 MiB (36.7 MiB/s) with 3 file(s) remaining
Completed 168.6 MiB/233.2 MiB (36.8 MiB/s) with 3 file(s) remaining
Completed 168.9 MiB/233.2 MiB (36.8 MiB/s) with 3 file(s) remaining
Completed 169.1 MiB/233.2 MiB (36.8 MiB/s) with 3 file(s) remaining
Completed 169.4 MiB/233.2 MiB (36.8 MiB/s) with 3 file(s) remaining
Completed 169.6 MiB/233.2 MiB (36.8 MiB/s) with 3 file(s) remaining
Completed 169.9 MiB/233.2 MiB (36.8 MiB/s) with 3 file(s) remaining
Completed 170.1 MiB/233.2 MiB (36.8 MiB/s) with 3 file(s) remaining
Completed 170.4 MiB/233.2 MiB (36.9 MiB/s) with 3 file(s) remaining
Completed 170.6 MiB/233.2 MiB (36.9 MiB/s) with 3 file(s) remaining
Completed 170.9 MiB/233.2 MiB (36.9 MiB/s) with 3 file(s) remaining
Completed 171.1 MiB/233.2 MiB (36.9 MiB/s) with 3 file(s) remaining
Completed 171.4 MiB/233.2 MiB (36.9 MiB/s) with 3 file(s) remaining
Completed 171.6 MiB/233.2 MiB (37.0 MiB/s) with 3 file(s) remaining
Completed 171.9 MiB/233.2 MiB (37.0 MiB/s) with 3 file(s) remaining
Completed 172.1 MiB/233.2 MiB (37.0 MiB/s) with 3 file(s) remaining
Completed 172.4 MiB/233.2 MiB (37.0 MiB/s) with 3 file(s) remaining
Completed 172.6 MiB/233.2 MiB (37.0 MiB/s) with 3 file(s) remaining
Completed 172.9 MiB/233.2 MiB (37.0 MiB/s) with 3 file(s) remaining
Completed 173.1 MiB/233.2 MiB (37.0 MiB/s) with 3 file(s) remaining
Completed 173.4 MiB/233.2 MiB (37.1 MiB/s) with 3 file(s) remaining
Completed 173.6 MiB/233.2 MiB (37.1 MiB/s) with 3 file(s) remaining
Completed 173.9 MiB/233.2 MiB (37.2 MiB/s) with 3 file(s) remaining
Completed 174.1 MiB/233.2 MiB (37.1 MiB/s) with 3 file(s) remaining
Completed 174.4 MiB/233.2 MiB (37.2 MiB/s) with 3 file(s) remaining
Completed 174.6 MiB/233.2 MiB (37.2 MiB/s) with 3 file(s) remaining
Completed 174.9 MiB/233.2 MiB (37.2 MiB/s) with 3 file(s) remaining
Completed 175.1 MiB/233.2 MiB (37.2 MiB/s) with 3 file(s) remaining
Completed 175.4 MiB/233.2 MiB (37.3 MiB/s) with 3 file(s) remaining
Completed 175.6 MiB/233.2 MiB (37.2 MiB/s) with 3 file(s) remaining
Completed 175.9 MiB/233.2 MiB (37.2 MiB/s) with 3 file(s) remaining
Completed 176.1 MiB/233.2 MiB (37.1 MiB/s) with 3 file(s) remaining
Completed 176.4 MiB/233.2 MiB (37.1 MiB/s) with 3 file(s) remaining
Completed 176.6 MiB/233.2 MiB (37.1 MiB/s) with 3 file(s) remaining
Completed 176.9 MiB/233.2 MiB (37.1 MiB/s) with 3 file(s) remaining
Completed 177.1 MiB/233.2 MiB (37.0 MiB/s) with 3 file(s) remaining
Completed 177.4 MiB/233.2 MiB (36.9 MiB/s) with 3 file(s) remaining
Completed 177.6 MiB/233.2 MiB (36.8 MiB/s) with 3 file(s) remaining
Completed 177.9 MiB/233.2 MiB (36.6 MiB/s) with 3 file(s) remaining
Completed 178.1 MiB/233.2 MiB (36.7 MiB/s) with 3 file(s) remaining
Completed 178.4 MiB/233.2 MiB (36.6 MiB/s) with 3 file(s) remaining
Completed 178.6 MiB/233.2 MiB (34.9 MiB/s) with 3 file(s) remaining
Completed 178.9 MiB/233.2 MiB (34.9 MiB/s) with 3 file(s) remaining
Completed 179.1 MiB/233.2 MiB (35.0 MiB/s) with 3 file(s) remaining
Completed 179.4 MiB/233.2 MiB (35.0 MiB/s) with 3 file(s) remaining
Completed 179.6 MiB/233.2 MiB (34.9 MiB/s) with 3 file(s) remaining
Completed 179.9 MiB/233.2 MiB (34.5 MiB/s) with 3 file(s) remaining
Completed 180.1 MiB/233.2 MiB (34.5 MiB/s) with 3 file(s) remaining
Completed 180.4 MiB/233.2 MiB (34.5 MiB/s) with 3 file(s) remaining
Completed 180.6 MiB/233.2 MiB (34.5 MiB/s) with 3 file(s) remaining
Completed 180.9 MiB/233.2 MiB (34.5 MiB/s) with 3 file(s) remaining
Completed 181.1 MiB/233.2 MiB (34.5 MiB/s) with 3 file(s) remaining
Completed 181.4 MiB/233.2 MiB (34.5 MiB/s) with 3 file(s) remaining
Completed 181.6 MiB/233.2 MiB (34.5 MiB/s) with 3 file(s) remaining
Completed 181.9 MiB/233.2 MiB (34.4 MiB/s) with 3 file(s) remaining
Completed 182.1 MiB/233.2 MiB (34.4 MiB/s) with 3 file(s) remaining
Completed 182.4 MiB/233.2 MiB (34.4 MiB/s) with 3 file(s) remaining
Completed 182.6 MiB/233.2 MiB (34.4 MiB/s) with 3 file(s) remaining
Completed 182.9 MiB/233.2 MiB (34.4 MiB/s) with 3 file(s) remaining
Completed 183.1 MiB/233.2 MiB (34.4 MiB/s) with 3 file(s) remaining
Completed 183.4 MiB/233.2 MiB (34.5 MiB/s) with 3 file(s) remaining
Completed 183.6 MiB/233.2 MiB (34.4 MiB/s) with 3 file(s) remaining
Completed 183.9 MiB/233.2 MiB (34.4 MiB/s) with 3 file(s) remaining
Completed 184.1 MiB/233.2 MiB (34.4 MiB/s) with 3 file(s) remaining
Completed 184.4 MiB/233.2 MiB (34.4 MiB/s) with 3 file(s) remaining
Completed 184.6 MiB/233.2 MiB (34.4 MiB/s) with 3 file(s) remaining
Completed 184.9 MiB/233.2 MiB (34.4 MiB/s) with 3 file(s) remaining
Completed 185.1 MiB/233.2 MiB (34.4 MiB/s) with 3 file(s) remaining
Completed 185.4 MiB/233.2 MiB (34.4 MiB/s) with 3 file(s) remaining
Completed 185.6 MiB/233.2 MiB (34.4 MiB/s) with 3 file(s) remaining
Completed 185.9 MiB/233.2 MiB (33.8 MiB/s) with 3 file(s) remaining
Completed 186.1 MiB/233.2 MiB (32.8 MiB/s) with 3 file(s) remaining
Completed 186.4 MiB/233.2 MiB (32.9 MiB/s) with 3 file(s) remaining
Completed 186.6 MiB/233.2 MiB (32.9 MiB/s) with 3 file(s) remaining
Completed 186.9 MiB/233.2 MiB (33.0 MiB/s) with 3 file(s) remaining
Completed 187.1 MiB/233.2 MiB (33.0 MiB/s) with 3 file(s) remaining
Completed 187.4 MiB/233.2 MiB (32.9 MiB/s) with 3 file(s) remaining
Completed 187.6 MiB/233.2 MiB (32.8 MiB/s) with 3 file(s) remaining
Completed 187.9 MiB/233.2 MiB (32.7 MiB/s) with 3 file(s) remaining
Completed 188.1 MiB/233.2 MiB (32.7 MiB/s) with 3 file(s) remaining
Completed 188.4 MiB/233.2 MiB (32.4 MiB/s) with 3 file(s) remaining
Completed 188.6 MiB/233.2 MiB (32.2 MiB/s) with 3 file(s) remaining
Completed 188.9 MiB/233.2 MiB (32.0 MiB/s) with 3 file(s) remaining
Completed 189.1 MiB/233.2 MiB (32.0 MiB/s) with 3 file(s) remaining
Completed 189.4 MiB/233.2 MiB (32.1 MiB/s) with 3 file(s) remaining
Completed 189.6 MiB/233.2 MiB (32.1 MiB/s) with 3 file(s) remaining
Completed 189.9 MiB/233.2 MiB (32.0 MiB/s) with 3 file(s) remaining
Completed 190.1 MiB/233.2 MiB (32.0 MiB/s) with 3 file(s) remaining
Completed 190.4 MiB/233.2 MiB (32.0 MiB/s) with 3 file(s) remaining
Completed 190.6 MiB/233.2 MiB (32.1 MiB/s) with 3 file(s) remaining
Completed 190.9 MiB/233.2 MiB (32.1 MiB/s) with 3 file(s) remaining
Completed 191.1 MiB/233.2 MiB (32.1 MiB/s) with 3 file(s) remaining
Completed 191.4 MiB/233.2 MiB (31.9 MiB/s) with 3 file(s) remaining
Completed 191.6 MiB/233.2 MiB (31.8 MiB/s) with 3 file(s) remaining
Completed 191.9 MiB/233.2 MiB (31.8 MiB/s) with 3 file(s) remaining
Completed 192.1 MiB/233.2 MiB (31.4 MiB/s) with 3 file(s) remaining
Completed 192.4 MiB/233.2 MiB (31.4 MiB/s) with 3 file(s) remaining
Completed 192.6 MiB/233.2 MiB (31.3 MiB/s) with 3 file(s) remaining
Completed 192.9 MiB/233.2 MiB (31.3 MiB/s) with 3 file(s) remaining
Completed 193.1 MiB/233.2 MiB (31.1 MiB/s) with 3 file(s) remaining
Completed 193.4 MiB/233.2 MiB (31.1 MiB/s) with 3 file(s) remaining
Completed 193.6 MiB/233.2 MiB (31.1 MiB/s) with 3 file(s) remaining
Completed 193.9 MiB/233.2 MiB (31.2 MiB/s) with 3 file(s) remaining
Completed 194.1 MiB/233.2 MiB (31.2 MiB/s) with 3 file(s) remaining
Completed 194.4 MiB/233.2 MiB (31.2 MiB/s) with 3 file(s) remaining
Completed 194.6 MiB/233.2 MiB (31.2 MiB/s) with 3 file(s) remaining
Completed 194.9 MiB/233.2 MiB (31.2 MiB/s) with 3 file(s) remaining
Completed 195.1 MiB/233.2 MiB (31.2 MiB/s) with 3 file(s) remaining
Completed 195.4 MiB/233.2 MiB (31.2 MiB/s) with 3 file(s) remaining
Completed 195.6 MiB/233.2 MiB (31.2 MiB/s) with 3 file(s) remaining
Completed 195.9 MiB/233.2 MiB (31.3 MiB/s) with 3 file(s) remaining
Completed 196.1 MiB/233.2 MiB (31.3 MiB/s) with 3 file(s) remaining
Completed 196.4 MiB/233.2 MiB (31.3 MiB/s) with 3 file(s) remaining
Completed 196.6 MiB/233.2 MiB (31.3 MiB/s) with 3 file(s) remaining
Completed 196.9 MiB/233.2 MiB (31.4 MiB/s) with 3 file(s) remaining
Completed 197.1 MiB/233.2 MiB (31.4 MiB/s) with 3 file(s) remaining
Completed 197.4 MiB/233.2 MiB (31.4 MiB/s) with 3 file(s) remaining
Completed 197.6 MiB/233.2 MiB (31.4 MiB/s) with 3 file(s) remaining
Completed 197.9 MiB/233.2 MiB (31.5 MiB/s) with 3 file(s) remaining
Completed 198.1 MiB/233.2 MiB (31.5 MiB/s) with 3 file(s) remaining
Completed 198.4 MiB/233.2 MiB (31.5 MiB/s) with 3 file(s) remaining
Completed 198.6 MiB/233.2 MiB (31.6 MiB/s) with 3 file(s) remaining
Completed 198.9 MiB/233.2 MiB (31.6 MiB/s) with 3 file(s) remaining
Completed 199.1 MiB/233.2 MiB (31.6 MiB/s) with 3 file(s) remaining
Completed 199.4 MiB/233.2 MiB (31.6 MiB/s) with 3 file(s) remaining
upload: ../../../data/datafile-65-MB to s3://awscli-mint-test-bucket-917/datafile-65-MBCompleted 199.4 MiB/233.2 MiB (31.6 MiB/s) with 2 file(s) remaining
Completed 199.6 MiB/233.2 MiB (31.2 MiB/s) with 2 file(s) remaining
Completed 199.9 MiB/233.2 MiB (31.2 MiB/s) with 2 file(s) remaining
Completed 200.1 MiB/233.2 MiB (31.3 MiB/s) with 2 file(s) remaining
Completed 200.4 MiB/233.2 MiB (31.3 MiB/s) with 2 file(s) remaining
Completed 200.6 MiB/233.2 MiB (30.4 MiB/s) with 2 file(s) remaining
Completed 200.9 MiB/233.2 MiB (30.4 MiB/s) with 2 file(s) remaining
Completed 201.1 MiB/233.2 MiB (30.5 MiB/s) with 2 file(s) remaining
Completed 201.4 MiB/233.2 MiB (30.5 MiB/s) with 2 file(s) remaining
Completed 201.6 MiB/233.2 MiB (30.5 MiB/s) with 2 file(s) remaining
Completed 201.9 MiB/233.2 MiB (30.5 MiB/s) with 2 file(s) remaining
Completed 202.1 MiB/233.2 MiB (30.5 MiB/s) with 2 file(s) remaining
Completed 202.4 MiB/233.2 MiB (30.5 MiB/s) with 2 file(s) remaining
Completed 202.6 MiB/233.2 MiB (30.6 MiB/s) with 2 file(s) remaining
Completed 202.9 MiB/233.2 MiB (30.6 MiB/s) with 2 file(s) remaining
Completed 203.1 MiB/233.2 MiB (30.6 MiB/s) with 2 file(s) remaining
Completed 203.4 MiB/233.2 MiB (30.6 MiB/s) with 2 file(s) remaining
Completed 203.6 MiB/233.2 MiB (30.6 MiB/s) with 2 file(s) remaining
Completed 203.9 MiB/233.2 MiB (30.6 MiB/s) with 2 file(s) remaining
Completed 204.1 MiB/233.2 MiB (30.7 MiB/s) with 2 file(s) remaining
Completed 204.4 MiB/233.2 MiB (30.7 MiB/s) with 2 file(s) remaining
Completed 204.6 MiB/233.2 MiB (30.4 MiB/s) with 2 file(s) remaining
Completed 204.9 MiB/233.2 MiB (30.5 MiB/s) with 2 file(s) remaining
Completed 205.1 MiB/233.2 MiB (30.5 MiB/s) with 2 file(s) remaining
Completed 205.4 MiB/233.2 MiB (30.5 MiB/s) with 2 file(s) remaining
Completed 205.6 MiB/233.2 MiB (30.5 MiB/s) with 2 file(s) remaining
Completed 205.9 MiB/233.2 MiB (30.1 MiB/s) with 2 file(s) remaining
Completed 206.1 MiB/233.2 MiB (30.1 MiB/s) with 2 file(s) remaining
Completed 206.4 MiB/233.2 MiB (30.2 MiB/s) with 2 file(s) remaining
Completed 206.6 MiB/233.2 MiB (30.2 MiB/s) with 2 file(s) remaining
Completed 206.9 MiB/233.2 MiB (30.2 MiB/s) with 2 file(s) remaining
Completed 207.1 MiB/233.2 MiB (30.1 MiB/s) with 2 file(s) remaining
Completed 207.4 MiB/233.2 MiB (29.9 MiB/s) with 2 file(s) remaining
Completed 207.6 MiB/233.2 MiB (29.8 MiB/s) with 2 file(s) remaining
Completed 207.9 MiB/233.2 MiB (29.6 MiB/s) with 2 file(s) remaining
Completed 208.1 MiB/233.2 MiB (29.6 MiB/s) with 2 file(s) remaining
Completed 208.4 MiB/233.2 MiB (29.6 MiB/s) with 2 file(s) remaining
Completed 208.6 MiB/233.2 MiB (29.7 MiB/s) with 2 file(s) remaining
Completed 208.9 MiB/233.2 MiB (29.7 MiB/s) with 2 file(s) remaining
Completed 209.1 MiB/233.2 MiB (29.7 MiB/s) with 2 file(s) remaining
Completed 209.4 MiB/233.2 MiB (29.7 MiB/s) with 2 file(s) remaining
Completed 209.6 MiB/233.2 MiB (29.7 MiB/s) with 2 file(s) remaining
Completed 209.9 MiB/233.2 MiB (29.7 MiB/s) with 2 file(s) remaining
Completed 210.1 MiB/233.2 MiB (29.8 MiB/s) with 2 file(s) remaining
Completed 210.4 MiB/233.2 MiB (29.8 MiB/s) with 2 file(s) remaining
Completed 210.6 MiB/233.2 MiB (29.8 MiB/s) with 2 file(s) remaining
Completed 210.9 MiB/233.2 MiB (29.8 MiB/s) with 2 file(s) remaining
Completed 211.1 MiB/233.2 MiB (29.8 MiB/s) with 2 file(s) remaining
Completed 211.4 MiB/233.2 MiB (29.8 MiB/s) with 2 file(s) remaining
Completed 211.6 MiB/233.2 MiB (29.9 MiB/s) with 2 file(s) remaining
Completed 211.9 MiB/233.2 MiB (29.9 MiB/s) with 2 file(s) remaining
Completed 212.1 MiB/233.2 MiB (29.9 MiB/s) with 2 file(s) remaining
Completed 212.4 MiB/233.2 MiB (29.9 MiB/s) with 2 file(s) remaining
Completed 212.6 MiB/233.2 MiB (29.9 MiB/s) with 2 file(s) remaining
Completed 212.9 MiB/233.2 MiB (29.9 MiB/s) with 2 file(s) remaining
Completed 213.1 MiB/233.2 MiB (30.0 MiB/s) with 2 file(s) remaining
Completed 213.4 MiB/233.2 MiB (30.0 MiB/s) with 2 file(s) remaining
Completed 213.6 MiB/233.2 MiB (30.0 MiB/s) with 2 file(s) remaining
Completed 213.9 MiB/233.2 MiB (30.0 MiB/s) with 2 file(s) remaining
Completed 214.1 MiB/233.2 MiB (30.1 MiB/s) with 2 file(s) remaining
Completed 214.4 MiB/233.2 MiB (29.9 MiB/s) with 2 file(s) remaining
Completed 214.6 MiB/233.2 MiB (29.6 MiB/s) with 2 file(s) remaining
Completed 214.9 MiB/233.2 MiB (29.5 MiB/s) with 2 file(s) remaining
Completed 215.1 MiB/233.2 MiB (29.5 MiB/s) with 2 file(s) remaining
Completed 215.4 MiB/233.2 MiB (29.5 MiB/s) with 2 file(s) remaining
Completed 215.6 MiB/233.2 MiB (29.5 MiB/s) with 2 file(s) remaining
Completed 215.9 MiB/233.2 MiB (29.5 MiB/s) with 2 file(s) remaining
Completed 216.1 MiB/233.2 MiB (29.5 MiB/s) with 2 file(s) remaining
Completed 216.4 MiB/233.2 MiB (29.5 MiB/s) with 2 file(s) remaining
Completed 216.6 MiB/233.2 MiB (29.5 MiB/s) with 2 file(s) remaining
Completed 216.9 MiB/233.2 MiB (29.5 MiB/s) with 2 file(s) remaining
Completed 217.1 MiB/233.2 MiB (29.6 MiB/s) with 2 file(s) remaining
Completed 217.4 MiB/233.2 MiB (29.6 MiB/s) with 2 file(s) remaining
Completed 217.6 MiB/233.2 MiB (29.6 MiB/s) with 2 file(s) remaining
Completed 217.9 MiB/233.2 MiB (29.6 MiB/s) with 2 file(s) remaining
Completed 218.1 MiB/233.2 MiB (29.6 MiB/s) with 2 file(s) remaining
Completed 218.4 MiB/233.2 MiB (29.6 MiB/s) with 2 file(s) remaining
Completed 218.6 MiB/233.2 MiB (29.6 MiB/s) with 2 file(s) remaining
Completed 218.9 MiB/233.2 MiB (29.6 MiB/s) with 2 file(s) remaining
Completed 219.1 MiB/233.2 MiB (29.6 MiB/s) with 2 file(s) remaining
Completed 219.4 MiB/233.2 MiB (29.6 MiB/s) with 2 file(s) remaining
Completed 219.6 MiB/233.2 MiB (29.6 MiB/s) with 2 file(s) remaining
Completed 219.9 MiB/233.2 MiB (29.6 MiB/s) with 2 file(s) remaining
Completed 220.1 MiB/233.2 MiB (29.7 MiB/s) with 2 file(s) remaining
Completed 220.4 MiB/233.2 MiB (29.7 MiB/s) with 2 file(s) remaining
Completed 220.6 MiB/233.2 MiB (29.7 MiB/s) with 2 file(s) remaining
Completed 220.9 MiB/233.2 MiB (29.7 MiB/s) with 2 file(s) remaining
Completed 221.1 MiB/233.2 MiB (29.7 MiB/s) with 2 file(s) remaining
Completed 221.4 MiB/233.2 MiB (29.8 MiB/s) with 2 file(s) remaining
Completed 221.6 MiB/233.2 MiB (29.8 MiB/s) with 2 file(s) remaining
Completed 221.9 MiB/233.2 MiB (29.5 MiB/s) with 2 file(s) remaining
Completed 222.1 MiB/233.2 MiB (29.0 MiB/s) with 2 file(s) remaining
Completed 222.4 MiB/233.2 MiB (28.7 MiB/s) with 2 file(s) remaining
Completed 222.6 MiB/233.2 MiB (28.4 MiB/s) with 2 file(s) remaining
Completed 222.9 MiB/233.2 MiB (28.2 MiB/s) with 2 file(s) remaining
Completed 223.1 MiB/233.2 MiB (27.9 MiB/s) with 2 file(s) remaining
Completed 223.4 MiB/233.2 MiB (27.6 MiB/s) with 2 file(s) remaining
Completed 223.6 MiB/233.2 MiB (27.3 MiB/s) with 2 file(s) remaining
Completed 223.9 MiB/233.2 MiB (25.9 MiB/s) with 2 file(s) remaining
Completed 22...Truncated

**Comment by minio-ops** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-compression-xl.sh | :heavy_check_mark: |
| mint-xl.sh | :heavy_check_mark: |
| mint-compression-fs.sh | :heavy_check_mark: |
| mint-worm.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :x: [more...](#0e76ae35-9174-401d-8e09-3532a4567bd1) |
| mint-compression-dist-xl.sh | :x: [more...](#9d34fe20-c7e8-4bc5-b22b-dfa062a7186c) |
| mint-dist-xl.sh | :x: [more...](#2911e71a-0b3d-4aea-975a-9e11b9aa25c1) |
<a name="2911e71a-0b3d-4aea-975a-9e11b9aa25c1"></a>
### 8027-b4335f1/mint-dist-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.51:30655
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp e67c61622762:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 0 seconds
(2/14) Running aws-sdk-java tests ... done in 1 seconds
(3/14) Running aws-sdk-php tests ... done in 46 seconds
(4/14) Running aws-sdk-ruby tests ... done in 3 seconds
(5/14) Running awscli tests ... done in 1 minutes and 11 seconds
(6/14) Running healthcheck tests ... done in 0 seconds
(7/14) Running mc tests ... done in 59 seconds
(8/14) Running minio-dotnet tests ... done in 45 seconds
(9/14) Running minio-go tests ... done in 1 minutes and 14 seconds
(10/14) Running minio-java tests ... done in 1 minutes and 27 seconds
(11/14) Running minio-js tests ... done in 39 seconds
(12/14) Running minio-py tests ... FAILED in 21 seconds
{
  "function": "stat_object(bucket_name, object_name, sse)",
  "duration": 10205,
  "message": "InvalidPart: message: One or more of the specified parts could not be found. The part might not have been uploaded, or the specified entity tag might not have matched the part's entity tag",
  "error": "Traceback (most recent call last):\n  File \"/mint/run/core/minio-py/tests.py\", line 726, in test_stat_object\n    sse=sse)\n  File \"/usr/local/lib/python3.5/dist-packages/minio/api.py\", line 827, in put_object\n    part_size=part_size)\n  File \"/usr/local/lib/python3.5/dist-packages/minio/api.py\", line 1659, in _stream_put_object\n    uploaded_parts)\n  File \"/usr/local/lib/python3.5/dist-packages/minio/api.py\", line 1745, in _complete_multipart_upload\n    content_sha256=sha256_hex)\n  File \"/usr/local/lib/python3.5/dist-packages/minio/api.py\", line 1901, in _url_open\n    object_name).get_exception()\nminio.error.InvalidPart: InvalidPart: message: One or more of the specified parts could not be found. The part might not have been uploaded, or the specified entity tag might not have matched the part's entity tag\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"/mint/run/core/minio-py/tests.py\", line 1864, in main\n    test_stat_object(client, log_output)\n  File \"/mint/run/core/minio-py/tests.py\", line 732, in test_stat_object\n    raise Exception(err)\nException: InvalidPart: message: One or more of the specified parts could not be found. The part might not have been uploaded, or the specified entity tag might not have matched the part's entity tag\n",
  "args": {
    "bucket_name": "minio-py-test-66667aa1-d951-48d7-a671-6c4406868610",
    "metadata": {
      "X-Amz-Meta-Testing": "value"
    },
    "object_name": "d8eee411-1c77-4a52-bd3e-b7d9f9a3e099",
    "data": "LimitedRandomReader(MB_11)",
    "length": 11534336,
    "content_type": "application/octet-stream"
  },
  "name": "minio-py:test_stat_object",
  "status": "FAIL"
}

Executed 11 out of 14 tests successfully.
```
<a name="9d34fe20-c7e8-4bc5-b22b-dfa062a7186c"></a>
### 8027-b4335f1/mint-compression-dist-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.56:32073
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 5b20950386c4:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 0 seconds
(2/14) Running aws-sdk-java tests ... done in 1 seconds
(3/14) Running aws-sdk-php tests ... done in 52 seconds
(4/14) Running aws-sdk-ruby tests ... done in 3 seconds
(5/14) Running awscli tests ... FAILED in 52 seconds
{"name": "awscli", "duration": 6525, "function": "aws --endpoint-url http://72.28.97.56:32073 s3 cp /mint/data/datafile-65-MB s3://awscli-mint-test-bucket-15646/datafile-65-MB\n", "status": "FAIL", "error": "Completed 256.0 KiB/65.0 MiB (1.1 MiB/s) with 1 file(s) remaining
Completed 512.0 KiB/65.0 MiB (2.1 MiB/s) with 1 file(s) remaining
Completed 768.0 KiB/65.0 MiB (3.2 MiB/s) with 1 file(s) remaining
Completed 1.0 MiB/65.0 MiB (4.2 MiB/s) with 1 file(s) remaining  
Completed 1.2 MiB/65.0 MiB (4.3 MiB/s) with 1 file(s) remaining  
Completed 1.5 MiB/65.0 MiB (5.2 MiB/s) with 1 file(s) remaining  
Completed 1.8 MiB/65.0 MiB (6.0 MiB/s) with 1 file(s) remaining  
Completed 2.0 MiB/65.0 MiB (6.9 MiB/s) with 1 file(s) remaining  
Completed 2.2 MiB/65.0 MiB (7.7 MiB/s) with 1 file(s) remaining  
Completed 2.5 MiB/65.0 MiB (8.5 MiB/s) with 1 file(s) remaining  
Completed 2.8 MiB/65.0 MiB (9.3 MiB/s) with 1 file(s) remaining  
Completed 3.0 MiB/65.0 MiB (10.1 MiB/s) with 1 file(s) remaining 
Completed 3.2 MiB/65.0 MiB (10.9 MiB/s) with 1 file(s) remaining 
Completed 3.5 MiB/65.0 MiB (11.7 MiB/s) with 1 file(s) remaining 
Completed 3.8 MiB/65.0 MiB (12.4 MiB/s) with 1 file(s) remaining 
Completed 4.0 MiB/65.0 MiB (13.2 MiB/s) with 1 file(s) remaining 
Completed 4.2 MiB/65.0 MiB (13.7 MiB/s) with 1 file(s) remaining 
Completed 4.5 MiB/65.0 MiB (14.4 MiB/s) with 1 file(s) remaining 
Completed 4.8 MiB/65.0 MiB (14.9 MiB/s) with 1 file(s) remaining 
Completed 5.0 MiB/65.0 MiB (15.5 MiB/s) with 1 file(s) remaining 
Completed 5.2 MiB/65.0 MiB (16.0 MiB/s) with 1 file(s) remaining 
Completed 5.5 MiB/65.0 MiB (16.5 MiB/s) with 1 file(s) remaining 
Completed 5.8 MiB/65.0 MiB (17.0 MiB/s) with 1 file(s) remaining 
Completed 6.0 MiB/65.0 MiB (17.6 MiB/s) with 1 file(s) remaining 
Completed 6.2 MiB/65.0 MiB (18.0 MiB/s) with 1 file(s) remaining 
Completed 6.5 MiB/65.0 MiB (18.5 MiB/s) with 1 file(s) remaining 
Completed 6.8 MiB/65.0 MiB (19.0 MiB/s) with 1 file(s) remaining 
Completed 7.0 MiB/65.0 MiB (19.4 MiB/s) with 1 file(s) remaining 
Completed 7.2 MiB/65.0 MiB (19.8 MiB/s) with 1 file(s) remaining 
Completed 7.5 MiB/65.0 MiB (20.3 MiB/s) with 1 file(s) remaining 
Completed 7.8 MiB/65.0 MiB (20.6 MiB/s) with 1 file(s) remaining 
Completed 8.0 MiB/65.0 MiB (20.8 MiB/s) with 1 file(s) remaining 
Completed 8.2 MiB/65.0 MiB (21.2 MiB/s) with 1 file(s) remaining 
Completed 8.5 MiB/65.0 MiB (21.6 MiB/s) with 1 file(s) remaining 
Completed 8.8 MiB/65.0 MiB (21.9 MiB/s) with 1 file(s) remaining 
Completed 9.0 MiB/65.0 MiB (22.3 MiB/s) with 1 file(s) remaining 
Completed 9.2 MiB/65.0 MiB (22.6 MiB/s) with 1 file(s) remaining 
Completed 9.5 MiB/65.0 MiB (23.0 MiB/s) with 1 file(s) remaining 
Completed 9.8 MiB/65.0 MiB (23.3 MiB/s) with 1 file(s) remaining 
Completed 10.0 MiB/65.0 MiB (23.6 MiB/s) with 1 file(s) remaining
Completed 10.2 MiB/65.0 MiB (24.0 MiB/s) with 1 file(s) remaining
Completed 10.5 MiB/65.0 MiB (24.2 MiB/s) with 1 file(s) remaining
Completed 10.8 MiB/65.0 MiB (24.6 MiB/s) with 1 file(s) remaining
Completed 11.0 MiB/65.0 MiB (24.9 MiB/s) with 1 file(s) remaining
Completed 11.2 MiB/65.0 MiB (25.2 MiB/s) with 1 file(s) remaining
Completed 11.5 MiB/65.0 MiB (25.4 MiB/s) with 1 file(s) remaining
Completed 11.8 MiB/65.0 MiB (25.8 MiB/s) with 1 file(s) remaining
Completed 12.0 MiB/65.0 MiB (26.0 MiB/s) with 1 file(s) remaining
Completed 12.2 MiB/65.0 MiB (26.3 MiB/s) with 1 file(s) remaining
Completed 12.5 MiB/65.0 MiB (26.5 MiB/s) with 1 file(s) remaining
Completed 12.8 MiB/65.0 MiB (26.8 MiB/s) with 1 file(s) remaining
Completed 13.0 MiB/65.0 MiB (27.0 MiB/s) with 1 file(s) remaining
Completed 13.2 MiB/65.0 MiB (27.3 MiB/s) with 1 file(s) remaining
Completed 13.5 MiB/65.0 MiB (27.5 MiB/s) with 1 file(s) remaining
Completed 13.8 MiB/65.0 MiB (27.8 MiB/s) with 1 file(s) remaining
Completed 14.0 MiB/65.0 MiB (27.9 MiB/s) with 1 file(s) remaining
Completed 14.2 MiB/65.0 MiB (28.1 MiB/s) with 1 file(s) remaining
Completed 14.5 MiB/65.0 MiB (28.3 MiB/s) with 1 file(s) remaining
Completed 14.8 MiB/65.0 MiB (28.6 MiB/s) with 1 file(s) remaining
Completed 15.0 MiB/65.0 MiB (28.8 MiB/s) with 1 file(s) remaining
Completed 15.2 MiB/65.0 MiB (29.0 MiB/s) with 1 file(s) remaining
Completed 15.5 MiB/65.0 MiB (29.1 MiB/s) with 1 file(s) remaining
Completed 15.8 MiB/65.0 MiB (29.4 MiB/s) with 1 file(s) remaining
Completed 16.0 MiB/65.0 MiB (29.5 MiB/s) with 1 file(s) remaining
Completed 16.2 MiB/65.0 MiB (29.9 MiB/s) with 1 file(s) remaining
Completed 16.5 MiB/65.0 MiB (30.3 MiB/s) with 1 file(s) remaining
Completed 16.8 MiB/65.0 MiB (30.7 MiB/s) with 1 file(s) remaining
Completed 17.0 MiB/65.0 MiB (31.1 MiB/s) with 1 file(s) remaining
Completed 17.2 MiB/65.0 MiB (31.5 MiB/s) with 1 file(s) remaining
Completed 17.5 MiB/65.0 MiB (31.9 MiB/s) with 1 file(s) remaining
Completed 17.8 MiB/65.0 MiB (32.3 MiB/s) with 1 file(s) remaining
Completed 18.0 MiB/65.0 MiB (32.6 MiB/s) with 1 file(s) remaining
Completed 18.2 MiB/65.0 MiB (32.8 MiB/s) with 1 file(s) remaining
Completed 18.5 MiB/65.0 MiB (33.0 MiB/s) with 1 file(s) remaining
Completed 18.8 MiB/65.0 MiB (32.9 MiB/s) with 1 file(s) remaining
Completed 19.0 MiB/65.0 MiB (32.4 MiB/s) with 1 file(s) remaining
Completed 19.2 MiB/65.0 MiB (32.1 MiB/s) with 1 file(s) remaining
Completed 19.5 MiB/65.0 MiB (31.9 MiB/s) with 1 file(s) remaining
Completed 19.8 MiB/65.0 MiB (31.6 MiB/s) with 1 file(s) remaining
Completed 20.0 MiB/65.0 MiB (31.4 MiB/s) with 1 file(s) remaining
Completed 20.2 MiB/65.0 MiB (31.3 MiB/s) with 1 file(s) remaining
Completed 20.5 MiB/65.0 MiB (31.2 MiB/s) with 1 file(s) remaining
Completed 20.8 MiB/65.0 MiB (31.2 MiB/s) with 1 file(s) remaining
Completed 21.0 MiB/65.0 MiB (31.1 MiB/s) with 1 file(s) remaining
Completed 21.2 MiB/65.0 MiB (31.1 MiB/s) with 1 file(s) remaining
Completed 21.5 MiB/65.0 MiB (31.0 MiB/s) with 1 file(s) remaining
Completed 21.8 MiB/65.0 MiB (31.0 MiB/s) with 1 file(s) remaining
Completed 22.0 MiB/65.0 MiB (31.0 MiB/s) with 1 file(s) remaining
Completed 22.2 MiB/65.0 MiB (30.9 MiB/s) with 1 file(s) remaining
Completed 22.5 MiB/65.0 MiB (30.9 MiB/s) with 1 file(s) remaining
Completed 22.8 MiB/65.0 MiB (30.9 MiB/s) with 1 file(s) remaining
Completed 23.0 MiB/65.0 MiB (30.9 MiB/s) with 1 file(s) remaining
Completed 23.2 MiB/65.0 MiB (31.0 MiB/s) with 1 file(s) remaining
Completed 23.5 MiB/65.0 MiB (31.0 MiB/s) with 1 file(s) remaining
Completed 23.8 MiB/65.0 MiB (31.0 MiB/s) with 1 file(s) remaining
Completed 24.0 MiB/65.0 MiB (31.1 MiB/s) with 1 file(s) remaining
Completed 24.2 MiB/65.0 MiB (31.3 MiB/s) with 1 file(s) remaining
Completed 24.5 MiB/65.0 MiB (31.6 MiB/s) with 1 file(s) remaining
Completed 24.8 MiB/65.0 MiB (31.9 MiB/s) with 1 file(s) remaining
Completed 25.0 MiB/65.0 MiB (32.2 MiB/s) with 1 file(s) remaining
Completed 25.2 MiB/65.0 MiB (32.5 MiB/s) with 1 file(s) remaining
Completed 25.5 MiB/65.0 MiB (32.6 MiB/s) with 1 file(s) remaining
Completed 25.8 MiB/65.0 MiB (32.9 MiB/s) with 1 file(s) remaining
Completed 26.0 MiB/65.0 MiB (33.1 MiB/s) with 1 file(s) remaining
Completed 26.2 MiB/65.0 MiB (33.4 MiB/s) with 1 file(s) remaining
Completed 26.5 MiB/65.0 MiB (33.7 MiB/s) with 1 file(s) remaining
Completed 26.8 MiB/65.0 MiB (33.9 MiB/s) with 1 file(s) remaining
Completed 27.0 MiB/65.0 MiB (34.2 MiB/s) with 1 file(s) remaining
Completed 27.2 MiB/65.0 MiB (34.5 MiB/s) with 1 file(s) remaining
Completed 27.5 MiB/65.0 MiB (34.7 MiB/s) with 1 file(s) remaining
Completed 27.8 MiB/65.0 MiB (34.7 MiB/s) with 1 file(s) remaining
Completed 28.0 MiB/65.0 MiB (35.0 MiB/s) with 1 file(s) remaining
Completed 28.2 MiB/65.0 MiB (34.9 MiB/s) with 1 file(s) remaining
Completed 28.5 MiB/65.0 MiB (35.2 MiB/s) with 1 file(s) remaining
Completed 28.8 MiB/65.0 MiB (35.4 MiB/s) with 1 file(s) remaining
Completed 29.0 MiB/65.0 MiB (35.3 MiB/s) with 1 file(s) remaining
Completed 29.2 MiB/65.0 MiB (35.5 MiB/s) with 1 file(s) remaining
Completed 29.5 MiB/65.0 MiB (35.4 MiB/s) with 1 file(s) remaining
Completed 29.8 MiB/65.0 MiB (35.6 MiB/s) with 1 file(s) remaining
Completed 30.0 MiB/65.0 MiB (35.4 MiB/s) with 1 file(s) remaining
Completed 30.2 MiB/65.0 MiB (35.6 MiB/s) with 1 file(s) remaining
Completed 30.5 MiB/65.0 MiB (35.5 MiB/s) with 1 file(s) remaining
Completed 30.8 MiB/65.0 MiB (35.6 MiB/s) with 1 file(s) remaining
Completed 31.0 MiB/65.0 MiB (35.4 MiB/s) with 1 file(s) remaining
Completed 31.2 MiB/65.0 MiB (35.6 MiB/s) with 1 file(s) remaining
Completed 31.5 MiB/65.0 MiB (35.3 MiB/s) with 1 file(s) remaining
Completed 31.8 MiB/65.0 MiB (35.5 MiB/s) with 1 file(s) remaining
Completed 32.0 MiB/65.0 MiB (35.3 MiB/s) with 1 file(s) remaining
Completed 32.2 MiB/65.0 MiB (35.4 MiB/s) with 1 file(s) remaining
Completed 32.5 MiB/65.0 MiB (35.3 MiB/s) with 1 file(s) remaining
Completed 32.8 MiB/65.0 MiB (35.5 MiB/s) with 1 file(s) remaining
Completed 33.0 MiB/65.0 MiB (35.3 MiB/s) with 1 file(s) remaining
Completed 33.2 MiB/65.0 MiB (35.5 MiB/s) with 1 file(s) remaining
Completed 33.5 MiB/65.0 MiB (35.3 MiB/s) with 1 file(s) remaining
Completed 33.8 MiB/65.0 MiB (35.5 MiB/s) with 1 file(s) remaining
Completed 34.0 MiB/65.0 MiB (35.3 MiB/s) with 1 file(s) remaining
Completed 34.2 MiB/65.0 MiB (35.6 MiB/s) with 1 file(s) remaining
Completed 34.5 MiB/65.0 MiB (35.4 MiB/s) with 1 file(s) remaining
Completed 34.8 MiB/65.0 MiB (35.6 MiB/s) with 1 file(s) remaining
Completed 35.0 MiB/65.0 MiB (35.4 MiB/s) with 1 file(s) remaining
Completed 35.2 MiB/65.0 MiB (35.6 MiB/s) with 1 file(s) remaining
Completed 35.5 MiB/65.0 MiB (35.4 MiB/s) with 1 file(s) remaining
Completed 35.8 MiB/65.0 MiB (35.6 MiB/s) with 1 file(s) remaining
Completed 36.0 MiB/65.0 MiB (35.6 MiB/s) with 1 file(s) remaining
Completed 36.2 MiB/65.0 MiB (35.8 MiB/s) with 1 file(s) remaining
Completed 36.5 MiB/65.0 MiB (35.8 MiB/s) with 1 file(s) remaining
Completed 36.8 MiB/65.0 MiB (36.0 MiB/s) with 1 file(s) remaining
Completed 37.0 MiB/65.0 MiB (36.0 MiB/s) with 1 file(s) remaining
Completed 37.2 MiB/65.0 MiB (36.2 MiB/s) with 1 file(s) remaining
Completed 37.5 MiB/65.0 MiB (36.2 MiB/s) with 1 file(s) remaining
Completed 37.8 MiB/65.0 MiB (36.4 MiB/s) with 1 file(s) remaining
Completed 38.0 MiB/65.0 MiB (36.6 MiB/s) with 1 file(s) remaining
Completed 38.2 MiB/65.0 MiB (36.8 MiB/s) with 1 file(s) remaining
Completed 38.5 MiB/65.0 MiB (37.0 MiB/s) with 1 file(s) remaining
Completed 38.8 MiB/65.0 MiB (37.2 MiB/s) with 1 file(s) remaining
Completed 39.0 MiB/65.0 MiB (37.4 MiB/s) with 1 file(s) remaining
Completed 39.2 MiB/65.0 MiB (37.6 MiB/s) with 1 file(s) remaining
Completed 39.5 MiB/65.0 MiB (37.6 MiB/s) with 1 file(s) remaining
Completed 39.8 MiB/65.0 MiB (37.7 MiB/s) with 1 file(s) remaining
Completed 40.0 MiB/65.0 MiB (37.6 MiB/s) with 1 file(s) remaining
Completed 40.2 MiB/65.0 MiB (37.8 MiB/s) with 1 file(s) remaining
Completed 40.5 MiB/65.0 MiB (37.7 MiB/s) with 1 file(s) remaining
Completed 40.8 MiB/65.0 MiB (37.7 MiB/s) with 1 file(s) remaining
Completed 41.0 MiB/65.0 MiB (37.9 MiB/s) with 1 file(s) remaining
Completed 41.2 MiB/65.0 MiB (38.0 MiB/s) with 1 file(s) remaining
Completed 41.5 MiB/65.0 MiB (38.0 MiB/s) with 1 file(s) remaining
Completed 41.8 MiB/65.0 MiB (38.0 MiB/s) with 1 file(s) remaining
Completed 42.0 MiB/65.0 MiB (38.1 MiB/s) with 1 file(s) remaining
Completed 42.2 MiB/65.0 MiB (38.0 MiB/s) with 1 file(s) remaining
Completed 42.5 MiB/65.0 MiB (38.0 MiB/s) with 1 file(s) remaining
Completed 42.8 MiB/65.0 MiB (38.0 MiB/s) with 1 file(s) remaining
Completed 43.0 MiB/65.0 MiB (38.1 MiB/s) with 1 file(s) remaining
Completed 43.2 MiB/65.0 MiB (38.2 MiB/s) with 1 file(s) remaining
Completed 43.5 MiB/65.0 MiB (37.9 MiB/s) with 1 file(s) remaining
Completed 43.8 MiB/65.0 MiB (38.1 MiB/s) with 1 file(s) remaining
Completed 44.0 MiB/65.0 MiB (37.4 MiB/s) with 1 file(s) remaining
Completed 44.2 MiB/65.0 MiB (36.8 MiB/s) with 1 file(s) remaining
Completed 44.5 MiB/65.0 MiB (36.2 MiB/s) with 1 file(s) remaining
Completed 44.8 MiB/65.0 MiB (35.8 MiB/s) with 1 file(s) remaining
Completed 45.0 MiB/65.0 MiB (36.0 MiB/s) with 1 file(s) remaining
Completed 45.2 MiB/65.0 MiB (36.2 MiB/s) with 1 file(s) remaining
Completed 45.5 MiB/65.0 MiB (36.4 MiB/s) with 1 file(s) remaining
Completed 45.8 MiB/65.0 MiB (36.5 MiB/s) with 1 file(s) remaining
Completed 46.0 MiB/65.0 MiB (36.7 MiB/s) with 1 file(s) remaining
Completed 46.2 MiB/65.0 MiB (36.8 MiB/s) with 1 file(s) remaining
Completed 46.5 MiB/65.0 MiB (37.0 MiB/s) with 1 file(s) remaining
Completed 46.8 MiB/65.0 MiB (37.2 MiB/s) with 1 file(s) remaining
Completed 47.0 MiB/65.0 MiB (37.3 MiB/s) with 1 file(s) remaining
Completed 47.2 MiB/65.0 MiB (37.5 MiB/s) with 1 file(s) remaining
Completed 47.5 MiB/65.0 MiB (37.5 MiB/s) with 1 file(s) remaining
Completed 47.8 MiB/65.0 MiB (37.6 MiB/s) with 1 file(s) remaining
Completed 48.0 MiB/65.0 MiB (37.2 MiB/s) with 1 file(s) remaining
Completed 48.2 MiB/65.0 MiB (36.8 MiB/s) with 1 file(s) remaining
Completed 48.5 MiB/65.0 MiB (36.4 MiB/s) with 1 file(s) remaining
Completed 48.8 MiB/65.0 MiB (36.4 MiB/s) with 1 file(s) remaining
Completed 49.0 MiB/65.0 MiB (36.3 MiB/s) with 1 file(s) remaining
Completed 49.2 MiB/65.0 MiB (36.1 MiB/s) with 1 file(s) remaining
Completed 49.5 MiB/65.0 MiB (36.0 MiB/s) with 1 file(s) remaining
Completed 49.8 MiB/65.0 MiB (35.7 MiB/s) with 1 file(s) remaining
Completed 50.0 MiB/65.0 MiB (35.6 MiB/s) with 1 file(s) remaining
Completed 50.2 MiB/65.0 MiB (35.3 MiB/s) with 1 file(s) remaining
Completed 50.5 MiB/65.0 MiB (35.3 MiB/s) with 1 file(s) remaining
Completed 50.8 MiB/65.0 MiB (35.0 MiB/s) with 1 file(s) remaining
Completed 51.0 MiB/65.0 MiB (34.9 MiB/s) with 1 file(s) remaining
Completed 51.2 MiB/65.0 MiB (34.6 MiB/s) with 1 file(s) remaining
Completed 51.5 MiB/65.0 MiB (34.6 MiB/s) with 1 file(s) remaining
Completed 51.8 MiB/65.0 MiB (34.4 MiB/s) with 1 file(s) remaining
Completed 52.0 MiB/65.0 MiB (34.4 MiB/s) with 1 file(s) remaining
Completed 52.2 MiB/65.0 MiB (34.1 MiB/s) with 1 file(s) remaining
Completed 52.5 MiB/65.0 MiB (34.2 MiB/s) with 1 file(s) remaining
Completed 52.8 MiB/65.0 MiB (33.9 MiB/s) with 1 file(s) remaining
Completed 53.0 MiB/65.0 MiB (34.0 MiB/s) with 1 file(s) remaining
Completed 53.2 MiB/65.0 MiB (33.8 MiB/s) with 1 file(s) remaining
Completed 53.5 MiB/65.0 MiB (33.8 MiB/s) with 1 file(s) remaining
Completed 53.8 MiB/65.0 MiB (33.7 MiB/s) with 1 file(s) remaining
Completed 54.0 MiB/65.0 MiB (33.7 MiB/s) with 1 file(s) remaining
Completed 54.2 MiB/65.0 MiB (33.6 MiB/s) with 1 file(s) remaining
Completed 54.5 MiB/65.0 MiB (33.6 MiB/s) with 1 file(s) remaining
Completed 54.8 MiB/65.0 MiB (33.4 MiB/s) with 1 file(s) remaining
Completed 55.0 MiB/65.0 MiB (33.5 MiB/s) with 1 file(s) remaining
Completed 55.2 MiB/65.0 MiB (33.4 MiB/s) with 1 file(s) remaining
Completed 55.5 MiB/65.0 MiB (33.4 MiB/s) with 1 file(s) remaining
Completed 55.8 MiB/65.0 MiB (33.3 MiB/s) with 1 file(s) remaining
Completed 56.0 MiB/65.0 MiB (33.3 MiB/s) with 1 file(s) remaining
Completed 56.2 MiB/65.0 MiB (33.2 MiB/s) with 1 file(s) remaining
Completed 56.5 MiB/65.0 MiB (33.0 MiB/s) with 1 file(s) remaining
Completed 56.8 MiB/65.0 MiB (32.7 MiB/s) with 1 file(s) remaining
Completed 57.0 MiB/65.0 MiB (32.7 MiB/s) with 1 file(s) remaining
Completed 57.2 MiB/65.0 MiB (32.5 MiB/s) with 1 file(s) remaining
Completed 57.5 MiB/65.0 MiB (32.3 MiB/s) with 1 file(s) remaining
Completed 57.8 MiB/65.0 MiB (32.2 MiB/s) with 1 file(s) remaining
Completed 58.0 MiB/65.0 MiB (32.0 MiB/s) with 1 file(s) remaining
Completed 58.2 MiB/65.0 MiB (31.9 MiB/s) with 1 file(s) remaining
Completed 58.5 MiB/65.0 MiB (31.7 MiB/s) with 1 file(s) remaining
Completed 58.8 MiB/65.0 MiB (18.9 MiB/s) with 1 file(s) remaining
Completed 59.0 MiB/65.0 MiB (18.8 MiB/s) with 1 file(s) remaining
Completed 59.2 MiB/65.0 MiB (18.7 MiB/s) with 1 file(s) remaining
Completed 59.5 MiB/65.0 MiB (18.7 MiB/s) with 1 file(s) remaining
Completed 59.8 MiB/65.0 MiB (18.6 MiB/s) with 1 file(s) remaining
Completed 60.0 MiB/65.0 MiB (18.6 MiB/s) with 1 file(s) remaining
Completed 60.2 MiB/65.0 MiB (18.5 MiB/s) with 1 file(s) remaining
Completed 60.5 MiB/65.0 MiB (18.5 MiB/s) with 1 file(s) remaining
Completed 60.8 MiB/65.0 MiB (18.4 MiB/s) with 1 file(s) remaining
Completed 61.0 MiB/65.0 MiB (18.4 MiB/s) with 1 file(s) remaining
Completed 61.2 MiB/65.0 MiB (18.3 MiB/s) with 1 file(s) remaining
Completed 61.5 MiB/65.0 MiB (18.3 MiB/s) with 1 file(s) remaining
Completed 61.8 MiB/65.0 MiB (18.3 MiB/s) with 1 file(s) remaining
Completed 62.0 MiB/65.0 MiB (18.2 MiB/s) with 1 file(s) remaining
Completed 62.2 MiB/65.0 MiB (18.2 MiB/s) with 1 file(s) remaining
Completed 62.5 MiB/65.0 MiB (18.2 MiB/s) with 1 file(s) remaining
Completed 62.8 MiB/65.0 MiB (18.1 MiB/s) with 1 file(s) remaining
Completed 63.0 MiB/65.0 MiB (18.1 MiB/s) with 1 file(s) remaining
Completed 63.2 MiB/65.0 MiB (18.1 MiB/s) with 1 file(s) remaining
Completed 63.5 MiB/65.0 MiB (18.0 MiB/s) with 1 file(s) remaining
Completed 63.8 MiB/65.0 MiB (18.0 MiB/s) with 1 file(s) remaining
Completed 64.0 MiB/65.0 MiB (18.0 MiB/s) with 1 file(s) remaining
Completed 64.2 MiB/65.0 MiB (18.0 MiB/s) with 1 file(s) remaining
Completed 64.5 MiB/65.0 MiB (18.0 MiB/s) with 1 file(s) remaining
Completed 64.8 MiB/65.0 MiB (18.0 MiB/s) with 1 file(s) remaining
Completed 65.0 MiB/65.0 MiB (18.0 MiB/s) with 1 file(s) remaining
upload failed: ../../../data/datafile-65-MB to s3://awscli-mint-test-bucket-15646/datafile-65-MB An error occurred (InvalidPart) when calling the CompleteMultipartUpload operation: One or more of the specified parts could not be found.  The part may not have been uploaded, or the specified entity tag may not match the part's entity tag."}

Executed 4 out of 14 tests successfully.
```
<a name="0e76ae35-9174-401d-8e09-3532a4567bd1"></a>
### 8027-b4335f1/mint-large-bucket.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.57:32280
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp a41bfa85fcb6:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... FAILED in 12 seconds
{
  "alert": "",
  "args": {
    "bucketName": "aws-sdk-go-test-nzhycrhkcsuvcb",
    "expiry": 60000000000,
    "objectName": "presignedTest"
  },
  "duration": 12594,
  "error": "RequestError: send request failed\ncaused by: Put http://72.28.97.57:32280/aws-sdk-go-test-nzhycrhkcsuvcb: dial tcp 72.28.97.57:32280: connect: no route to host",
  "function": "PresignedPut",
  "message": "AWS SDK Go CreateBucket Failed",
  "name": "aws-sdk-go",
  "status": "FAIL"
}

Executed 0 out of 14 tests successfully.
```

**Comment by minio-ops** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-compression-xl.sh | :heavy_check_mark: |
| mint-xl.sh | :heavy_check_mark: |
| mint-compression-dist-xl.sh | :heavy_check_mark: |
| mint-compression-fs.sh | :heavy_check_mark: |
| mint-worm.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :x: [more...](#a2093147-2e1a-4d5b-8148-ea8ed7e2b958) |
| mint-fs.sh | :x: [more...](#c6f24b5e-90cc-45d3-9d94-c898bff445cb) |
| mint-dist-xl.sh | :x: [more...](#c8ea88d9-0ab4-41bd-9267-6532aaaabf1b) |
<a name="c6f24b5e-90cc-45d3-9d94-c898bff445cb"></a>
### 8027-a15cc36/mint-fs.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.57:31890
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 8b41e8651d3b:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... FAILED in 12 seconds
{
  "alert": "",
  "args": {
    "bucketName": "aws-sdk-go-test-0g0tpogsr2vq2r",
    "expiry": 60000000000,
    "objectName": "presignedTest"
  },
  "duration": 12536,
  "error": "RequestError: send request failed\ncaused by: Put http://72.28.97.57:31890/aws-sdk-go-test-0g0tpogsr2vq2r: dial tcp 72.28.97.57:31890: connect: no route to host",
  "function": "PresignedPut",
  "message": "AWS SDK Go CreateBucket Failed",
  "name": "aws-sdk-go",
  "status": "FAIL"
}

Executed 0 out of 14 tests successfully.
```
<a name="a2093147-2e1a-4d5b-8148-ea8ed7e2b958"></a>
### 8027-a15cc36/mint-large-bucket.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.53:32242
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 9851467bf44a:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 3 seconds
(2/14) Running aws-sdk-java tests ... done in 1 seconds
(3/14) Running aws-sdk-php tests ... done in 52 seconds
(4/14) Running aws-sdk-ruby tests ... done in 12 seconds
(5/14) Running awscli tests ... FAILED in 2 minutes and 18 seconds
{"name": "awscli", "duration": 69247, "function": "aws --endpoint-url http://72.28.97.53:32242 s3 sync /mint/data s3://awscli-mint-test-bucket-16832/\n", "status": "FAIL", "error": "Completed 256.0 KiB/233.2 MiB (5.4 MiB/s) with 15 file(s) remaining
Completed 512.0 KiB/233.2 MiB (10.7 MiB/s) with 15 file(s) remaining
Completed 768.0 KiB/233.2 MiB (15.8 MiB/s) with 15 file(s) remaining
Completed 1.0 MiB/233.2 MiB (20.2 MiB/s) with 15 file(s) remaining  
Completed 1.2 MiB/233.2 MiB (23.8 MiB/s) with 15 file(s) remaining  
Completed 1.5 MiB/233.2 MiB (28.1 MiB/s) with 15 file(s) remaining  
Completed 1.8 MiB/233.2 MiB (31.9 MiB/s) with 15 file(s) remaining  
Completed 2.0 MiB/233.2 MiB (31.5 MiB/s) with 15 file(s) remaining  
upload: ../../../data/datafile-0-b to s3://awscli-mint-test-bucket-16832/datafile-0-bCompleted 2.0 MiB/233.2 MiB (31.5 MiB/s) with 14 file(s) remaining
Completed 2.0 MiB/233.2 MiB (14.0 MiB/s) with 14 file(s) remaining
upload: ../../../data/datafile-1-b to s3://awscli-mint-test-bucket-16832/datafile-1-bCompleted 2.0 MiB/233.2 MiB (14.0 MiB/s) with 13 file(s) remaining
upload: ../../../data/datafile-1-MB to s3://awscli-mint-test-bucket-16832/datafile-1-MBCompleted 2.0 MiB/233.2 MiB (14.0 MiB/s) with 12 file(s) remaining
Completed 2.3 MiB/233.2 MiB (11.1 MiB/s) with 12 file(s) remaining
Completed 2.3 MiB/233.2 MiB (11.2 MiB/s) with 12 file(s) remaining
upload: ../../../data/datafile-1.03-MB to s3://awscli-mint-test-bucket-16832/datafile-1.03-MBCompleted 2.3 MiB/233.2 MiB (11.2 MiB/s) with 11 file(s) remaining
Completed 2.4 MiB/233.2 MiB (11.6 MiB/s) with 11 file(s) remaining
upload: ../../../data/datafile-100-kB to s3://awscli-mint-test-bucket-16832/datafile-100-kBCompleted 2.4 MiB/233.2 MiB (11.6 MiB/s) with 10 file(s) remaining
Completed 2.6 MiB/233.2 MiB (12.8 MiB/s) with 10 file(s) remaining
Completed 2.9 MiB/233.2 MiB (13.9 MiB/s) with 10 file(s) remaining
Completed 2.9 MiB/233.2 MiB (13.9 MiB/s) with 10 file(s) remaining
upload: ../../../data/datafile-10-kB to s3://awscli-mint-test-bucket-16832/datafile-10-kBCompleted 2.9 MiB/233.2 MiB (13.9 MiB/s) with 9 file(s) remaining
Completed 2.9 MiB/233.2 MiB (13.8 MiB/s) with 9 file(s) remaining
upload: ../../../data/datafile-1-kB to s3://awscli-mint-test-bucket-16832/datafile-1-kBCompleted 2.9 MiB/233.2 MiB (13.8 MiB/s) with 8 file(s) remaining
Completed 3.1 MiB/233.2 MiB (14.9 MiB/s) with 8 file(s) remaining
Completed 3.4 MiB/233.2 MiB (15.9 MiB/s) with 8 file(s) remaining
Completed 3.6 MiB/233.2 MiB (16.7 MiB/s) with 8 file(s) remaining
Completed 3.9 MiB/233.2 MiB (17.6 MiB/s) with 8 file(s) remaining
Completed 4.1 MiB/233.2 MiB (18.4 MiB/s) with 8 file(s) remaining
Completed 4.4 MiB/233.2 MiB (19.2 MiB/s) with 8 file(s) remaining
Completed 4.6 MiB/233.2 MiB (20.1 MiB/s) with 8 file(s) remaining
Completed 4.9 MiB/233.2 MiB (20.9 MiB/s) with 8 file(s) remaining
Completed 5.1 MiB/233.2 MiB (21.7 MiB/s) with 8 file(s) remaining
Completed 5.4 MiB/233.2 MiB (22.5 MiB/s) with 8 file(s) remaining
Completed 5.6 MiB/233.2 MiB (23.3 MiB/s) with 8 file(s) remaining
Completed 5.9 MiB/233.2 MiB (24.1 MiB/s) with 8 file(s) remaining
Completed 6.1 MiB/233.2 MiB (24.9 MiB/s) with 8 file(s) remaining
Completed 6.4 MiB/233.2 MiB (25.7 MiB/s) with 8 file(s) remaining
Completed 6.6 MiB/233.2 MiB (26.5 MiB/s) with 8 file(s) remaining
Completed 6.9 MiB/233.2 MiB (27.3 MiB/s) with 8 file(s) remaining
Completed 7.1 MiB/233.2 MiB (28.1 MiB/s) with 8 file(s) remaining
Completed 7.4 MiB/233.2 MiB (29.0 MiB/s) with 8 file(s) remaining
Completed 7.4 MiB/233.2 MiB (28.9 MiB/s) with 8 file(s) remaining
upload: ../../../data/datafile-33-kB to s3://awscli-mint-test-bucket-16832/datafile-33-kBCompleted 7.4 MiB/233.2 MiB (28.9 MiB/s) with 7 file(s) remaining
Completed 7.7 MiB/233.2 MiB (29.7 MiB/s) with 7 file(s) remaining
Completed 7.9 MiB/233.2 MiB (30.6 MiB/s) with 7 file(s) remaining
Completed 8.2 MiB/233.2 MiB (30.7 MiB/s) with 7 file(s) remaining
Completed 8.4 MiB/233.2 MiB (30.4 MiB/s) with 7 file(s) remaining
Completed 8.7 MiB/233.2 MiB (31.3 MiB/s) with 7 file(s) remaining
Completed 8.9 MiB/233.2 MiB (31.9 MiB/s) with 7 file(s) remaining
Completed 9.2 MiB/233.2 MiB (32.6 MiB/s) with 7 file(s) remaining
Completed 9.4 MiB/233.2 MiB (31.8 MiB/s) with 7 file(s) remaining
Completed 9.7 MiB/233.2 MiB (32.6 MiB/s) with 7 file(s) remaining
Completed 9.9 MiB/233.2 MiB (33.1 MiB/s) with 7 file(s) remaining
Completed 10.2 MiB/233.2 MiB (33.9 MiB/s) with 7 file(s) remaining
Completed 10.4 MiB/233.2 MiB (34.3 MiB/s) with 7 file(s) remaining
Completed 10.7 MiB/233.2 MiB (33.2 MiB/s) with 7 file(s) remaining
Completed 10.9 MiB/233.2 MiB (33.8 MiB/s) with 7 file(s) remaining
Completed 11.2 MiB/233.2 MiB (34.3 MiB/s) with 7 file(s) remaining
Completed 11.4 MiB/233.2 MiB (33.6 MiB/s) with 7 file(s) remaining
Completed 11.7 MiB/233.2 MiB (34.2 MiB/s) with 7 file(s) remaining
Completed 11.9 MiB/233.2 MiB (34.7 MiB/s) with 7 file(s) remaining
Completed 12.2 MiB/233.2 MiB (34.0 MiB/s) with 7 file(s) remaining
Completed 12.4 MiB/233.2 MiB (34.5 MiB/s) with 7 file(s) remaining
Completed 12.7 MiB/233.2 MiB (35.0 MiB/s) with 7 file(s) remaining
Completed 12.9 MiB/233.2 MiB (34.7 MiB/s) with 7 file(s) remaining
Completed 13.2 MiB/233.2 MiB (35.3 MiB/s) with 7 file(s) remaining
Completed 13.4 MiB/233.2 MiB (35.9 MiB/s) with 7 file(s) remaining
Completed 13.7 MiB/233.2 MiB (35.9 MiB/s) with 7 file(s) remaining
Completed 13.9 MiB/233.2 MiB (36.6 MiB/s) with 7 file(s) remaining
Completed 14.2 MiB/233.2 MiB (37.0 MiB/s) with 7 file(s) remaining
Completed 14.4 MiB/233.2 MiB (37.5 MiB/s) with 7 file(s) remaining
Completed 14.7 MiB/233.2 MiB (37.8 MiB/s) with 7 file(s) remaining
Completed 14.9 MiB/233.2 MiB (38.4 MiB/s) with 7 file(s) remaining
Completed 15.2 MiB/233.2 MiB (39.0 MiB/s) with 7 file(s) remaining
Completed 15.4 MiB/233.2 MiB (39.6 MiB/s) with 7 file(s) remaining
Completed 15.7 MiB/233.2 MiB (39.8 MiB/s) with 7 file(s) remaining
Completed 15.9 MiB/233.2 MiB (40.0 MiB/s) with 7 file(s) remaining
Completed 16.2 MiB/233.2 MiB (40.5 MiB/s) with 7 file(s) remaining
Completed 16.4 MiB/233.2 MiB (40.8 MiB/s) with 7 file(s) remaining
Completed 16.7 MiB/233.2 MiB (41.2 MiB/s) with 7 file(s) remaining
Completed 16.9 MiB/233.2 MiB (41.7 MiB/s) with 7 file(s) remaining
Completed 17.2 MiB/233.2 MiB (42.2 MiB/s) with 7 file(s) remaining
Completed 17.4 MiB/233.2 MiB (42.3 MiB/s) with 7 file(s) remaining
Completed 17.7 MiB/233.2 MiB (42.6 MiB/s) with 7 file(s) remaining
Completed 17.9 MiB/233.2 MiB (43.2 MiB/s) with 7 file(s) remaining
Completed 18.2 MiB/233.2 MiB (43.4 MiB/s) with 7 file(s) remaining
Completed 18.4 MiB/233.2 MiB (43.7 MiB/s) with 7 file(s) remaining
Completed 18.7 MiB/233.2 MiB (44.1 MiB/s) with 7 file(s) remaining
Completed 18.9 MiB/233.2 MiB (44.5 MiB/s) with 7 file(s) remaining
Completed 19.2 MiB/233.2 MiB (44.9 MiB/s) with 7 file(s) remaining
Completed 19.4 MiB/233.2 MiB (45.4 MiB/s) with 7 file(s) remaining
Completed 19.7 MiB/233.2 MiB (45.9 MiB/s) with 7 file(s) remaining
Completed 19.9 MiB/233.2 MiB (46.3 MiB/s) with 7 file(s) remaining
Completed 20.2 MiB/233.2 MiB (46.7 MiB/s) with 7 file(s) remaining
Completed 20.4 MiB/233.2 MiB (46.6 MiB/s) with 7 file(s) remaining
Completed 20.7 MiB/233.2 MiB (47.1 MiB/s) with 7 file(s) remaining
Completed 20.9 MiB/233.2 MiB (47.7 MiB/s) with 7 file(s) remaining
Completed 21.2 MiB/233.2 MiB (48.2 MiB/s) with 7 file(s) remaining
Completed 21.4 MiB/233.2 MiB (48.6 MiB/s) with 7 file(s) remaining
Completed 21.7 MiB/233.2 MiB (48.9 MiB/s) with 7 file(s) remaining
Completed 21.9 MiB/233.2 MiB (49.4 MiB/s) with 7 file(s) remaining
Completed 22.2 MiB/233.2 MiB (50.0 MiB/s) with 7 file(s) remaining
Completed 22.4 MiB/233.2 MiB (50.3 MiB/s) with 7 file(s) remaining
Completed 22.7 MiB/233.2 MiB (50.2 MiB/s) with 7 file(s) remaining
Completed 22.9 MiB/233.2 MiB (50.7 MiB/s) with 7 file(s) remaining
Completed 23.2 MiB/233.2 MiB (51.0 MiB/s) with 7 file(s) remaining
Completed 23.4 MiB/233.2 MiB (51.5 MiB/s) with 7 file(s) remaining
Completed 23.7 MiB/233.2 MiB (51.6 MiB/s) with 7 file(s) remaining
Completed 23.9 MiB/233.2 MiB (51.7 MiB/s) with 7 file(s) remaining
upload: ../../../data/datafile-5-MB to s3://awscli-mint-test-bucket-16832/datafile-5-MBCompleted 23.9 MiB/233.2 MiB (51.7 MiB/s) with 6 file(s) remaining
Completed 24.2 MiB/233.2 MiB (51.7 MiB/s) with 6 file(s) remaining
Completed 24.4 MiB/233.2 MiB (52.1 MiB/s) with 6 file(s) remaining
Completed 24.7 MiB/233.2 MiB (52.6 MiB/s) with 6 file(s) remaining
Completed 24.9 MiB/233.2 MiB (53.1 MiB/s) with 6 file(s) remaining
Completed 25.2 MiB/233.2 MiB (53.1 MiB/s) with 6 file(s) remaining
Completed 25.4 MiB/233.2 MiB (52.9 MiB/s) with 6 file(s) remaining
Completed 25.7 MiB/233.2 MiB (53.3 MiB/s) with 6 file(s) remaining
Completed 25.9 MiB/233.2 MiB (53.8 MiB/s) with 6 file(s) remaining
Completed 26.2 MiB/233.2 MiB (54.3 MiB/s) with 6 file(s) remaining
Completed 26.4 MiB/233.2 MiB (53.9 MiB/s) with 6 file(s) remaining
Completed 26.7 MiB/233.2 MiB (53.8 MiB/s) with 6 file(s) remaining
Completed 26.9 MiB/233.2 MiB (54.2 MiB/s) with 6 file(s) remaining
Completed 27.2 MiB/233.2 MiB (54.7 MiB/s) with 6 file(s) remaining
Completed 27.4 MiB/233.2 MiB (55.1 MiB/s) with 6 file(s) remaining
Completed 27.7 MiB/233.2 MiB (54.8 MiB/s) with 6 file(s) remaining
Completed 27.9 MiB/233.2 MiB (54.7 MiB/s) with 6 file(s) remaining
Completed 28.2 MiB/233.2 MiB (55.1 MiB/s) with 6 file(s) remaining
Completed 28.4 MiB/233.2 MiB (55.6 MiB/s) with 6 file(s) remaining
Completed 28.7 MiB/233.2 MiB (56.0 MiB/s) with 6 file(s) remaining
Completed 28.9 MiB/233.2 MiB (55.5 MiB/s) with 6 file(s) remaining
Completed 29.2 MiB/233.2 MiB (55.6 MiB/s) with 6 file(s) remaining
Completed 29.4 MiB/233.2 MiB (55.8 MiB/s) with 6 file(s) remaining
Completed 29.7 MiB/233.2 MiB (56.3 MiB/s) with 6 file(s) remaining
Completed 29.9 MiB/233.2 MiB (56.7 MiB/s) with 6 file(s) remaining
Completed 30.2 MiB/233.2 MiB (56.3 MiB/s) with 6 file(s) remaining
Completed 30.4 MiB/233.2 MiB (56.5 MiB/s) with 6 file(s) remaining
Completed 30.7 MiB/233.2 MiB (56.9 MiB/s) with 6 file(s) remaining
Completed 30.9 MiB/233.2 MiB (57.3 MiB/s) with 6 file(s) remaining
Completed 31.2 MiB/233.2 MiB (57.2 MiB/s) with 6 file(s) remaining
Completed 31.4 MiB/233.2 MiB (57.6 MiB/s) with 6 file(s) remaining
Completed 31.7 MiB/233.2 MiB (57.9 MiB/s) with 6 file(s) remaining
Completed 31.9 MiB/233.2 MiB (58.0 MiB/s) with 6 file(s) remaining
Completed 32.2 MiB/233.2 MiB (57.9 MiB/s) with 6 file(s) remaining
Completed 32.4 MiB/233.2 MiB (58.3 MiB/s) with 6 file(s) remaining
Completed 32.7 MiB/233.2 MiB (58.2 MiB/s) with 6 file(s) remaining
Completed 32.9 MiB/233.2 MiB (58.5 MiB/s) with 6 file(s) remaining
Completed 33.2 MiB/233.2 MiB (58.7 MiB/s) with 6 file(s) remaining
Completed 33.4 MiB/233.2 MiB (58.1 MiB/s) with 6 file(s) remaining
Completed 33.7 MiB/233.2 MiB (58.5 MiB/s) with 6 file(s) remaining
Completed 33.9 MiB/233.2 MiB (58.6 MiB/s) with 6 file(s) remaining
Completed 34.2 MiB/233.2 MiB (58.4 MiB/s) with 6 file(s) remaining
Completed 34.4 MiB/233.2 MiB (58.9 MiB/s) with 6 file(s) remaining
Completed 34.7 MiB/233.2 MiB (58.6 MiB/s) with 6 file(s) remaining
Completed 34.9 MiB/233.2 MiB (59.0 MiB/s) with 6 file(s) remaining
Completed 35.2 MiB/233.2 MiB (59.3 MiB/s) with 6 file(s) remaining
Completed 35.4 MiB/233.2 MiB (59.4 MiB/s) with 6 file(s) remaining
Completed 35.7 MiB/233.2 MiB (59.4 MiB/s) with 6 file(s) remaining
Completed 35.9 MiB/233.2 MiB (59.7 MiB/s) with 6 file(s) remaining
Completed 36.2 MiB/233.2 MiB (59.8 MiB/s) with 6 file(s) remaining
Completed 36.4 MiB/233.2 MiB (60.0 MiB/s) with 6 file(s) remaining
Completed 36.7 MiB/233.2 MiB (60.3 MiB/s) with 6 file(s) remaining
Completed 36.9 MiB/233.2 MiB (60.2 MiB/s) with 6 file(s) remaining
Completed 37.2 MiB/233.2 MiB (60.5 MiB/s) with 6 file(s) remaining
Completed 37.4 MiB/233.2 MiB (60.8 MiB/s) with 6 file(s) remaining
Completed 37.7 MiB/233.2 MiB (60.9 MiB/s) with 6 file(s) remaining
Completed 37.9 MiB/233.2 MiB (61.0 MiB/s) with 6 file(s) remaining
Completed 38.2 MiB/233.2 MiB (61.2 MiB/s) with 6 file(s) remaining
Completed 38.4 MiB/233.2 MiB (61.5 MiB/s) with 6 file(s) remaining
Completed 38.7 MiB/233.2 MiB (61.5 MiB/s) with 6 file(s) remaining
Completed 38.9 MiB/233.2 MiB (61.8 MiB/s) with 6 file(s) remaining
Completed 39.2 MiB/233.2 MiB (61.7 MiB/s) with 6 file(s) remaining
Completed 39.4 MiB/233.2 MiB (61.9 MiB/s) with 6 file(s) remaining
Completed 39.7 MiB/233.2 MiB (62.0 MiB/s) with 6 file(s) remaining
Completed 39.9 MiB/233.2 MiB (61.8 MiB/s) with 6 file(s) remaining
Completed 40.2 MiB/233.2 MiB (62.2 MiB/s) with 6 file(s) remaining
Completed 40.4 MiB/233.2 MiB (62.0 MiB/s) with 6 file(s) remaining
Completed 40.7 MiB/233.2 MiB (62.0 MiB/s) with 6 file(s) remaining
Completed 40.9 MiB/233.2 MiB (62.3 MiB/s) with 6 file(s) remaining
Completed 41.2 MiB/233.2 MiB (62.3 MiB/s) with 6 file(s) remaining
Completed 41.4 MiB/233.2 MiB (62.5 MiB/s) with 6 file(s) remaining
Completed 41.7 MiB/233.2 MiB (62.7 MiB/s) with 6 file(s) remaining
Completed 41.9 MiB/233.2 MiB (62.8 MiB/s) with 6 file(s) remaining
Completed 42.2 MiB/233.2 MiB (63.0 MiB/s) with 6 file(s) remaining
Completed 42.4 MiB/233.2 MiB (63.0 MiB/s) with 6 file(s) remaining
Completed 42.7 MiB/233.2 MiB (63.0 MiB/s) with 6 file(s) remaining
Completed 42.9 MiB/233.2 MiB (62.8 MiB/s) with 6 file(s) remaining
Completed 43.2 MiB/233.2 MiB (62.8 MiB/s) with 6 file(s) remaining
Completed 43.4 MiB/233.2 MiB (62.8 MiB/s) with 6 file(s) remaining
Completed 43.7 MiB/233.2 MiB (62.9 MiB/s) with 6 file(s) remaining
Completed 43.9 MiB/233.2 MiB (63.0 MiB/s) with 6 file(s) remaining
Completed 44.2 MiB/233.2 MiB (63.0 MiB/s) with 6 file(s) remaining
Completed 44.4 MiB/233.2 MiB (63.1 MiB/s) with 6 file(s) remaining
Completed 44.7 MiB/233.2 MiB (63.1 MiB/s) with 6 file(s) remaining
Completed 44.9 MiB/233.2 MiB (63.1 MiB/s) with 6 file(s) remaining
Completed 45.2 MiB/233.2 MiB (63.2 MiB/s) with 6 file(s) remaining
Completed 45.2 MiB/233.2 MiB (53.7 MiB/s) with 6 file(s) remaining
upload: ../../../data/datafile-5243880-b to s3://awscli-mint-test-bucket-16832/datafile-5243880-bCompleted 45.2 MiB/233.2 MiB (53.7 MiB/s) with 5 file(s) remaining
Completed 45.4 MiB/233.2 MiB (52.2 MiB/s) with 5 file(s) remaining
Completed 45.7 MiB/233.2 MiB (52.5 MiB/s) with 5 file(s) remaining
Completed 45.9 MiB/233.2 MiB (52.7 MiB/s) with 5 file(s) remaining
Completed 46.2 MiB/233.2 MiB (52.7 MiB/s) with 5 file(s) remaining
Completed 46.4 MiB/233.2 MiB (52.7 MiB/s) with 5 file(s) remaining
Completed 46.7 MiB/233.2 MiB (52.8 MiB/s) with 5 file(s) remaining
Completed 46.9 MiB/233.2 MiB (52.9 MiB/s) with 5 file(s) remaining
Completed 47.2 MiB/233.2 MiB (53.0 MiB/s) with 5 file(s) remaining
Completed 47.4 MiB/233.2 MiB (48.1 MiB/s) with 5 file(s) remaining
Completed 47.7 MiB/233.2 MiB (48.3 MiB/s) with 5 file(s) remaining
Completed 47.9 MiB/233.2 MiB (48.5 MiB/s) with 5 file(s) remaining
Completed 48.2 MiB/233.2 MiB (48.7 MiB/s) with 5 file(s) remaining
Completed 48.4 MiB/233.2 MiB (48.9 MiB/s) with 5 file(s) remaining
Completed 48.7 MiB/233.2 MiB (48.9 MiB/s) with 5 file(s) remaining
Completed 48.9 MiB/233.2 MiB (49.1 MiB/s) with 5 file(s) remaining
Completed 49.2 MiB/233.2 MiB (49.2 MiB/s) with 5 file(s) remaining
Completed 49.4 MiB/233.2 MiB (49.3 MiB/s) with 5 file(s) remaining
Completed 49.7 MiB/233.2 MiB (49.5 MiB/s) with 5 file(s) remaining
Completed 49.9 MiB/233.2 MiB (49.6 MiB/s) with 5 file(s) remaining
Completed 50.2 MiB/233.2 MiB (49.8 MiB/s) with 5 file(s) remaining
Completed 50.4 MiB/233.2 MiB (50.0 MiB/s) with 5 file(s) remaining
Completed 50.7 MiB/233.2 MiB (50.1 MiB/s) with 5 file(s) remaining
Completed 50.9 MiB/233.2 MiB (50.3 MiB/s) with 5 file(s) remaining
Completed 51.2 MiB/233.2 MiB (50.4 MiB/s) with 5 file(s) remaining
Completed 51.4 MiB/233.2 MiB (50.5 MiB/s) with 5 file(s) remaining
Completed 51.7 MiB/233.2 MiB (50.7 MiB/s) with 5 file(s) remaining
Completed 51.9 MiB/233.2 MiB (50.7 MiB/s) with 5 file(s) remaining
Completed 52.2 MiB/233.2 MiB (50.8 MiB/s) with 5 file(s) remaining
Completed 52.4 MiB/233.2 MiB (51.0 MiB/s) with 5 file(s) remaining
Completed 52.7 MiB/233.2 MiB (51.2 MiB/s) with 5 file(s) remaining
Completed 52.9 MiB/233.2 MiB (51.3 MiB/s) with 5 file(s) remaining
Completed 53.2 MiB/233.2 MiB (51.5 MiB/s) with 5 file(s) remaining
Completed 53.4 MiB/233.2 MiB (51.6 MiB/s) with 5 file(s) remaining
Completed 53.7 MiB/233.2 MiB (51.8 MiB/s) with 5 file(s) remaining
Completed 53.9 MiB/233.2 MiB (51.9 MiB/s) with 5 file(s) remaining
Completed 54.2 MiB/233.2 MiB (52.1 MiB/s) with 5 file(s) remaining
Completed 54.4 MiB/233.2 MiB (52.2 MiB/s) with 5 file(s) remaining
Completed 54.7 MiB/233.2 MiB (52.4 MiB/s) with 5 file(s) remaining
Completed 54.9 MiB/233.2 MiB (52.5 MiB/s) with 5 file(s) remaining
Completed 55.2 MiB/233.2 MiB (52.7 MiB/s) with 5 file(s) remaining
Completed 55.4 MiB/233.2 MiB (46.5 MiB/s) with 5 file(s) remaining
upload: ../../../data/datafile-6-MB to s3://awscli-mint-test-bucket-16832/datafile-6-MBCompleted 55.4 MiB/233.2 MiB (46.5 MiB/s) with 4 file(s) remaining
Completed 55.7 MiB/233.2 MiB (46.6 MiB/s) with 4 file(s) remaining
Completed 55.9 MiB/233.2 MiB (46.8 MiB/s) with 4 file(s) remaining
Completed 56.2 MiB/233.2 MiB (47.0 MiB/s) with 4 file(s) remaining
Completed 56.4 MiB/233.2 MiB (47.0 MiB/s) with 4 file(s) remaining
Completed 56.7 MiB/233.2 MiB (47.1 MiB/s) with 4 file(s) remaining
Completed 56.9 MiB/233.2 MiB (47.2 MiB/s) with 4 file(s) remaining
Completed 57.2 MiB/233.2 MiB (47.2 MiB/s) with 4 file(s) remaining
Completed 57.4 MiB/233.2 MiB (47.3 MiB/s) with 4 file(s) remaining
Completed 57.7 MiB/233.2 MiB (47.4 MiB/s) with 4 file(s) remaining
Completed 57.9 MiB/233.2 MiB (47.5 MiB/s) with 4 file(s) remaining
Completed 58.2 MiB/233.2 MiB (47.6 MiB/s) with 4 file(s) remaining
Completed 58.4 MiB/233.2 MiB (47.7 MiB/s) with 4 file(s) remaining
Completed 58.7 MiB/233.2 MiB (47.8 MiB/s) with 4 file(s) remaining
Completed 58.9 MiB/233.2 MiB (48.0 MiB/s) with 4 file(s) remaining
Completed 59.2 MiB/233.2 MiB (48.1 MiB/s) with 4 file(s) remaining
Completed 59.4 MiB/233.2 MiB (48.2 MiB/s) with 4 file(s) remaining
Completed 59.7 MiB/233.2 MiB (48.4 MiB/s) with 4 file(s) remaining
Completed 59.9 MiB/233.2 MiB (48.5 MiB/s) with 4 file(s) remaining
Completed 60.2 MiB/233.2 MiB (48.6 MiB/s) with 4 file(s) remaining
Completed 60.4 MiB/233.2 MiB (48.7 MiB/s) with 4 file(s) remaining
Completed 60.7 MiB/233.2 MiB (48.8 MiB/s) with 4 file(s) remaining
Completed 60.9 MiB/233.2 MiB (49.0 MiB/s) with 4 file(s) remaining
Completed 61.2 MiB/233.2 MiB (49.1 MiB/s) with 4 file(s) remaining
Completed 61.4 MiB/233.2 MiB (49.2 MiB/s) with 4 file(s) remaining
Completed 61.7 MiB/233.2 MiB (49.3 MiB/s) with 4 file(s) remaining
Completed 61.9 MiB/233.2 MiB (49.5 MiB/s) with 4 file(s) remaining
Completed 62.2 MiB/233.2 MiB (49.6 MiB/s) with 4 file(s) remaining
Completed 62.4 MiB/233.2 MiB (49.7 MiB/s) with 4 file(s) remaining
Completed 62.7 MiB/233.2 MiB (49.8 MiB/s) with 4 file(s) remaining
Completed 62.9 MiB/233.2 MiB (50.0 MiB/s) with 4 file(s) remaining
Completed 63.2 MiB/233.2 MiB (50.1 MiB/s) with 4 file(s) remaining
Completed 63.4 MiB/233.2 MiB (45.9 MiB/s) with 4 file(s) remaining
Completed 63.7 MiB/233.2 MiB (46.0 MiB/s) with 4 file(s) remaining
Completed 63.9 MiB/233.2 MiB (46.2 MiB/s) with 4 file(s) remaining
Completed 64.2 MiB/233.2 MiB (46.0 MiB/s) with 4 file(s) remaining
Completed 64.4 MiB/233.2 MiB (46.1 MiB/s) with 4 file(s) remaining
Completed 64.7 MiB/233.2 MiB (46.2 MiB/s) with 4 file(s) remaining
Completed 64.9 MiB/233.2 MiB (46.3 MiB/s) with 4 file(s) remaining
Completed 65.2 MiB/233.2 MiB (46.3 MiB/s) with 4 file(s) remaining
Completed 65.4 MiB/233.2 MiB (46.4 MiB/s) with 4 file(s) remaining
Completed 65.7 MiB/233.2 MiB (46.4 MiB/s) with 4 file(s) remaining
Completed 65.9 MiB/233.2 MiB (46.5 MiB/s) with 4 file(s) remaining
Completed 66.2 MiB/233.2 MiB (46.6 MiB/s) with 4 file(s) remaining
Completed 66.4 MiB/233.2 MiB (46.7 MiB/s) with 4 file(s) remaining
Completed 66.7 MiB/233.2 MiB (46.8 MiB/s) with 4 file(s) remaining
Completed 66.9 MiB/233.2 MiB (46.9 MiB/s) with 4 file(s) remaining
Completed 67.2 MiB/233.2 MiB (47.1 MiB/s) with 4 file(s) remaining
Completed 67.4 MiB/233.2 MiB (47.2 MiB/s) with 4 file(s) remaining
Completed 67.7 MiB/233.2 MiB (47.4 MiB/s) with 4 file(s) remaining
Completed 67.9 MiB/233.2 MiB (47.4 MiB/s) with 4 file(s) remaining
Completed 68.2 MiB/233.2 MiB (47.6 MiB/s) with 4 file(s) remaining
Completed 68.4 MiB/233.2 MiB (47.6 MiB/s) with 4 file(s) remaining
Completed 68.7 MiB/233.2 MiB (47.8 MiB/s) with 4 file(s) remaining
Completed 68.9 MiB/233.2 MiB (47.8 MiB/s) with 4 file(s) remaining
Completed 69.2 MiB/233.2 MiB (48.0 MiB/s) with 4 file(s) remaining
Completed 69.4 MiB/233.2 MiB (48.0 MiB/s) with 4 file(s) remaining
Completed 69.7 MiB/233.2 MiB (48.1 MiB/s) with 4 file(s) remaining
Completed 69.9 MiB/233.2 MiB (48.2 MiB/s) with 4 file(s) remaining
Completed 70.2 MiB/233.2 MiB (48.3 MiB/s) with 4 file(s) remaining
Completed 70.4 MiB/233.2 MiB (48.4 MiB/s) with 4 file(s) remaining
Completed 70.7 MiB/233.2 MiB (48.5 MiB/s) with 4 file(s) remaining
Completed 70.9 MiB/233.2 MiB (48.6 MiB/s) with 4 file(s) remaining
Completed 71.2 MiB/233.2 MiB (48.7 MiB/s) with 4 file(s) remaining
Completed 71.4 MiB/233.2 MiB (48.8 MiB/s) with 4 file(s) remaining
Completed 71.7 MiB/233.2 MiB (48.9 MiB/s) with 4 file(s) remaining
Completed 71.9 MiB/233.2 MiB (49.0 MiB/s) with 4 file(s) remaining
Completed 72.2 MiB/233.2 MiB (48.9 MiB/s) with 4 file(s) remaining
Completed 72.4 MiB/233.2 MiB (49.1 MiB/s) with 4 file(s) remaining
Completed 72.7 MiB/233.2 MiB (49.2 MiB/s) with 4 file(s) remaining
Completed 72.9 MiB/233.2 MiB (49.3 MiB/s) with 4 file(s) remaining
Completed 73.2 MiB/233.2 MiB (49.4 MiB/s) with 4 file(s) remaining
Completed 73.4 MiB/233.2 MiB (49.5 MiB/s) with 4 file(s) remaining
Completed 73.7 MiB/233.2 MiB (49.6 MiB/s) with 4 file(s) remaining
Completed 73.9 MiB/233.2 MiB (49.7 MiB/s) with 4 file(s) remaining
Completed 74.2 MiB/233.2 MiB (49.7 MiB/s) with 4 file(s) remaining
Completed 74.4 MiB/233.2 MiB (49.9 MiB/s) with 4 file(s) remaining
Completed 74.7 MiB/233.2 MiB (49.9 MiB/s) with 4 file(s) remaining
Completed 74.9 MiB/233.2 MiB (50.1 MiB/s) with 4 file(s) remaining
Completed 75.2 MiB/233.2 MiB (50.1 MiB/s) with 4 file(s) remaining
Completed 75.4 MiB/233.2 MiB (50.2 MiB/s) with 4 file(s) remaining
Completed 75.7 MiB/233.2 MiB (50.3 MiB/s) with 4 file(s) remaining
Completed 75.9 MiB/233.2 MiB (50.4 MiB/s) with 4 file(s) remaining
Completed 76.2 MiB/233.2 MiB (50.5 MiB/s) with 4 file(s) remaining
Completed 76.4 MiB/233.2 MiB (50.6 MiB/s) with 4 file(s) remaining
Completed 76.7 MiB/233.2 MiB (50.6 MiB/s) with 4 file(s) remaining
Completed 76.9 MiB/233.2 MiB (50.7 MiB/s) with 4 file(s) remaining
Completed 77.2 MiB/233.2 MiB (50.8 MiB/s) with 4 file(s) remaining
Completed 77.4 MiB/233.2 MiB (50.8 MiB/s) with 4 file(s) remaining
Completed 77.7 MiB/233.2 MiB (50.8 MiB/s) with 4 file(s) remaining
Completed 77.9 MiB/233.2 MiB (50.8 MiB/s) with 4 file(s) remaining
Completed 78.2 MiB/233.2 MiB (50.8 MiB/s) with 4 file(s) remaining
Completed 78.4 MiB/233.2 MiB (50.9 MiB/s) with 4 file(s) remaining
Completed 78.7 MiB/233.2 MiB (51.0 MiB/s) with 4 file(s) remaining
Completed 78.9 MiB/233.2 MiB (51.0 MiB/s) with 4 file(s) remaining
Completed 79.2 MiB/233.2 MiB (51.1 MiB/s) with 4 file(s) remaining
upload: ../../../data/datafile-11-MB to s3://awscli-mint-test-bucket-16832/datafile-11-MBCompleted 79.2 MiB/233.2 MiB (51.1 MiB/s) with 3 file(s) remaining
Completed 79.4 MiB/233.2 MiB (47.7 MiB/s) with 3 file(s) remaining
Completed 79.7 MiB/233.2 MiB (47.8 MiB/s) with 3 file(s) remaining
Completed 79.9 MiB/233.2 MiB (48.0 MiB/s) with 3 file(s) remaining
Completed 80.2 MiB/233.2 MiB (48.1 MiB/s) with 3 file(s) remaining
Completed 80.4 MiB/233.2 MiB (48.2 MiB/s) with 3 file(s) remaining
Completed 80.7 MiB/233.2 MiB (48.3 MiB/s) with 3 file(s) remaining
Completed 80.9 MiB/233.2 MiB (48.4 MiB/s) with 3 file(s) remaining
Completed 81.2 MiB/233.2 MiB (48.4 MiB/s) with 3 file(s) remaining
Completed 81.4 MiB/233.2 MiB (48.5 MiB/s) with 3 file(s) remaining
Completed 81.7 MiB/233.2 MiB (48.6 MiB/s) with 3 file(s) remaining
Completed 81.9 MiB/233.2 MiB (48.8 MiB/s) with 3 file(s) remaining
Completed 82.2 MiB/233.2 MiB (48.9 MiB/s) with 3 file(s) remaining
Completed 82.4 MiB/233.2 MiB (49.0 MiB/s) with 3 file(s) remaining
Completed 82.7 MiB/233.2 MiB (49.1 MiB/s) with 3 file(s) remaining
Completed 82.9 MiB/233.2 MiB (49.2 MiB/s) with 3 file(s) remaining
Completed 83.2 MiB/233.2 MiB (49.3 MiB/s) with 3 file(s) remaining
Completed 83.4 MiB/233.2 MiB (49.4 MiB/s) with 3 file(s) remaining
Completed 83.7 MiB/233.2 MiB (49.4 MiB/s) with 3 file(s) remaining
Completed 83.9 MiB/233.2 MiB (49.6 MiB/s) with 3 file(s) remaining
Completed 84.2 MiB/233.2 MiB (49.6 MiB/s) with 3 file(s) remaining
Completed 84.4 MiB/233.2 MiB (49.7 MiB/s) with 3 file(s) remaining
Completed 84.7 MiB/233.2 MiB (49.8 MiB/s) with 3 file(s) remaining
Completed 84.9 MiB/233.2 MiB (49.9 MiB/s) with 3 file(s) remaining
Completed 85.2 MiB/233.2 MiB (50.0 MiB/s) with 3 file(s) remaining
Completed 85.4 MiB/233.2 MiB (50.1 MiB/s) with 3 file(s) remaining
Completed 85.7 MiB/233.2 MiB (50.1 MiB/s) with 3 file(s) remaining
Completed 85.9 MiB/233.2 MiB (50.3 MiB/s) with 3 file(s) remaining
Completed 86.2 MiB/233.2 MiB (50.3 MiB/s) with 3 file(s) remaining
Completed 86.4 MiB/233.2 MiB (50.3 MiB/s) with 3 file(s) remaining
Completed 86.7 MiB/233.2 MiB (50.5 MiB/s) with 3 file(s) remaining
Completed 86.9 MiB/233.2 MiB (50.6 MiB/s) with 3 file(s) remaining
Completed 87.2 MiB/233.2 MiB (50.7 MiB/s) with 3 file(s) remaining
Completed 87.4 MiB/233.2 MiB (50.8 MiB/s) with 3 file(s) remaining
Completed 87.7 MiB/233.2 MiB (50.8 MiB/s) with 3 file(s) remaining
Completed 87.9 MiB/233.2 MiB (50.9 MiB/s) with 3 file(s) remaining
Completed 88.2 MiB/233.2 MiB (51.0 MiB/s) with 3 file(s) remaining
Completed 88.4 MiB/233.2 MiB (51.1 MiB/s) with 3 file(s) remaining
Completed 88.7 MiB/233.2 MiB (51.2 MiB/s) with 3 file(s) remaining
Completed 88.9 MiB/233.2 MiB (51.2 MiB/s) with 3 file(s) remaining
Completed 89.2 MiB/233.2 MiB (51.3 MiB/s) with 3 file(s) remaining
Completed 89.4 MiB/233.2 MiB (51.4 MiB/s) with 3 file(s) remaining
Completed 89.7 MiB/233.2 MiB (51.5 MiB/s) with 3 file(s) remaining
Completed 89.9 MiB/233.2 MiB (51.5 MiB/s) with 3 file(s) remaining
Completed 90.2 MiB/233.2 MiB (51.7 MiB/s) with 3 file(s) remaining
Completed 90.4 MiB/233.2 MiB (51.7 MiB/s) with 3 file(s) remaining
Completed 90.7 MiB/233.2 MiB (51.8 MiB/s) with 3 file(s) remaining
Completed 90.9 MiB/233.2 MiB (51.9 MiB/s) with 3 file(s) remaining
Completed 91.2 MiB/233.2 MiB (51.9 MiB/s) with 3 file(s) remaining
Completed 91.4 MiB/233.2 MiB (51.8 MiB/s) with 3 file(s) remaining
Completed 91.7 MiB/233.2 MiB (51.8 MiB/s) with 3 file(s) remaining
Completed 91.9 MiB/233.2 MiB (51.7 MiB/s) with 3 file(s) remaining
Completed 92.2 MiB/233.2 MiB (51.7 MiB/s) with 3 file(s) remaining
Completed 92.4 MiB/233.2 MiB (51.7 MiB/s) with 3 file(s) remaining
Completed 92.7 MiB/233.2 MiB (51.4 MiB/s) with 3 file(s) remaining
Completed 92.9 MiB/233.2 MiB (51.1 MiB/s) with 3 file(s) remaining
Completed 93.2 MiB/233.2 MiB (50.8 MiB/s) with 3 file(s) remaining
Completed 93.4 MiB/233.2 MiB (50.9 MiB/s) with 3 file(s) remaining
Completed 93.7 MiB/233.2 MiB (51.0 MiB/s) with 3 file(s) remaining
Completed 93.9 MiB/233.2 MiB (50.9 MiB/s) with 3 file(s) remaining
Completed 94.2 MiB/233.2 MiB (50.6 MiB/s) with 3 file(s) remaining
Completed 94.4 MiB/233.2 MiB (50.4 MiB/s) with 3 file(s) remaining
Completed 94.7 MiB/233.2 MiB (50.2 MiB/s) with 3 file(s) remaining
Completed 94.9 MiB/233.2 MiB (50.3 MiB/s) with 3 file(s) remaining
Completed 95.2 MiB/233.2 MiB (50.2 MiB/s) with 3 file(s) remaining
Completed 95.4 MiB/233.2 MiB (50.1 MiB/s) with 3 file(s) remaining
Completed 95.7 MiB/233.2 MiB (49.9 MiB/s) with 3 file(s) remaining
Completed 95.9 MiB/233.2 MiB (50.0 MiB/s) with 3 file(s) remaining
Completed 96.2 MiB/233.2 MiB (50.1 MiB/s) with 3 file(s) remaining
Completed 96.4 MiB/233.2 MiB (50.2 MiB/s) with 3 file(s) remaining
Completed 96.7 MiB/233.2 MiB (50.2 MiB/s) with 3 file(s) remaining
Completed 96.9 MiB/233.2 MiB (50.3 MiB/s) with 3 file(s) remaining
Completed 97.2 MiB/233.2 MiB (50.3 MiB/s) with 3 file(s) remaining
Completed 97.4 MiB/233.2 MiB (50.3 MiB/s) with 3 file(s) remaining
Completed 97.7 MiB/233.2 MiB (50.3 MiB/s) with 3 file(s) remaining
Completed 97.9 MiB/233.2 MiB (50.4 MiB/s) with 3 file(s) remaining
Completed 98.2 MiB/233.2 MiB (50.4 MiB/s) with 3 file(s) remaining
Completed 98.4 MiB/233.2 MiB (50.5 MiB/s) with 3 file(s) remaining
Completed 98.7 MiB/233.2 MiB (50.6 MiB/s) with 3 file(s) remaining
Completed 98.9 MiB/233.2 MiB (50.6 MiB/s) with 3 file(s) remaining
Completed 99.2 MiB/233.2 MiB (50.7 MiB/s) with 3 file(s) remaining
Completed 99.4 MiB/233.2 MiB (50.8 MiB/s) with 3 file(s) remaining
Completed 99.7 MiB/233.2 MiB (50.8 MiB/s) with 3 file(s) remaining
Completed 99.9 MiB/233.2 MiB (50.9 MiB/s) with 3 file(s) remaining
Completed 100.2 MiB/233.2 MiB (50.9 MiB/s) with 3 file(s) remaining
Completed 100.4 MiB/233.2 MiB (51.0 MiB/s) with 3 file(s) remaining
Completed 100.7 MiB/233.2 MiB (51.2 MiB/s) with 3 file(s) remaining
Completed 100.9 MiB/233.2 MiB (51.3 MiB/s) with 3 file(s) remaining
Completed 101.2 MiB/233.2 MiB (51.4 MiB/s) with 3 file(s) remaining
Completed 101.4 MiB/233.2 MiB (51.5 MiB/s) with 3 file(s) remaining
Completed 101.7 MiB/233.2 MiB (51.6 MiB/s) with 3 file(s) remaining
Completed 101.9 MiB/233.2 MiB (51.7 MiB/s) with 3 file(s) remaining
Completed 102.2 MiB/233.2 MiB (51.8 MiB/s) with 3 file(s) remaining
Completed 102.4 MiB/233.2 MiB (51.9 MiB/s) with 3 file(s) remaining
Completed 102.7 MiB/233.2 MiB (51.9 MiB/s) with 3 file(s) remaining
Completed 102.9 MiB/233.2 MiB (52.0 MiB/s) with 3 file(s) remaining
Completed 103.2 MiB/233.2 MiB (52.1 MiB/s) with 3 file(s) remaining
Completed 103.4 MiB/233.2 MiB (52.1 MiB/s) with 3 file(s) remaining
Completed 103.7 MiB/233.2 MiB (52.2 MiB/s) with 3 file(s) remaining
Completed 103.9 MiB/233.2 MiB (52.3 MiB/s) with 3 file(s) remaining
Completed 104.2 MiB/233.2 MiB (52.3 MiB/s) with 3 file(s) remaining
Completed 104.4 MiB/233.2 MiB (52.4 MiB/s) with 3 file(s) remaining
Completed 104.7 MiB/233.2 MiB (52.4 MiB/s) with 3 file(s) remaining
Completed 104.9 MiB/233.2 MiB (52.6 MiB/s) with 3 file(s) remaining
Completed 105.2 MiB/233.2 MiB (52.6 MiB/s) with 3 file(s) remaining
Completed 105.4 MiB/233.2 MiB (52.7 MiB/s) with 3 file(s) remaining
Completed 105.7 MiB/233.2 MiB (52.7 MiB/s) with 3 file(s) remaining
Completed 105.9 MiB/233.2 MiB (52.8 MiB/s) with 3 file(s) remaining
Completed 106.2 MiB/233.2 MiB (52.9 MiB/s) with 3 file(s) remaining
Completed 106.4 MiB/233.2 MiB (52.9 MiB/s) with 3 file(s) remaining
Completed 106.7 MiB/233.2 MiB (53.0 MiB/s) with 3 file(s) remaining
Completed 106.9 MiB/233.2 MiB (53.1 MiB/s) with 3 file(s) remaining
Completed 107.2 MiB/233.2 MiB (53.2 MiB/s) with 3 file(s) remaining
Completed 107.4 MiB/233.2 MiB (53.2 MiB/s) with 3 file(s) remaining
Completed 107.7 MiB/233.2 MiB (53.3 MiB/s) with 3 file(s) remaining
Completed 107.9 MiB/233.2 MiB (53.3 MiB/s) with 3 file(s) remaining
Completed 108.2 MiB/233.2 MiB (53.4 MiB/s) with 3 file(s) remaining
Completed 108.4 MiB/233.2 MiB (53.5 MiB/s) with 3 file(s) remaining
Completed 108.7 MiB/233.2 MiB (53.6 MiB/s) with 3 file(s) remaining
Completed 108.9 MiB/233.2 MiB (53.6 MiB/s) with 3 file(s) remaining
Completed 109.2 MiB/233.2 MiB (53.7 MiB/s) with 3 file(s) remaining
Completed 109.4 MiB/233.2 MiB (53.8 MiB/s) with 3 file(s) remaining
Completed 109.7 MiB/233.2 MiB (53.8 MiB/s) with 3 file(s) remaining
Completed 109.9 MiB/233.2 MiB (53.9 MiB/s) with 3 file(s) remaining
Completed 110.2 MiB/233.2 MiB (53.9 MiB/s) with 3 file(s) remaining
Completed 110.4 MiB/233.2 MiB (54.0 MiB/s) with 3 file(s) remaining
Completed 110.7 MiB/233.2 MiB (54.0 MiB/s) with 3 file(s) remaining
Completed 110.9 MiB/233.2 MiB (54.0 MiB/s) with 3 file(s) remaining
Completed 111.2 MiB/233.2 MiB (54.1 MiB/s) with 3 file(s) remaining
Completed 111.4 MiB/233.2 MiB (54.1 MiB/s) with 3 file(s) remaining
Completed 111.7 MiB/233.2 MiB (54.2 MiB/s) with 3 file(s) remaining
Completed 111.9 MiB/233.2 MiB (54.2 MiB/s) with 3 file(s) remaining
Completed 112.2 MiB/233.2 MiB (54.2 MiB/s) with 3 file(s) remaining
Completed 112.4 MiB/233.2 MiB (50.0 MiB/s) with 3 file(s) remaining
Completed 112.7 MiB/233.2 MiB (50.1 MiB/s) with 3 file(s) remaining
Completed 112.9 MiB/233.2 MiB (50.1 MiB/s) with 3 file(s) remaining
Completed 113.2 MiB/233.2 MiB (50.2 MiB/s) with 3 file(s) remaining
Completed 113.4 MiB/233.2 MiB (50.3 MiB/s) with 3 file(s) remaining
Completed 113.7 MiB/233.2 MiB (50.4 MiB/s) with 3 file(s) remaining
Completed 113.9 MiB/233.2 MiB (50.5 MiB/s) with 3 file(s) remaining
Completed 114.2 MiB/233.2 MiB (50.6 MiB/s) with 3 file(s) remaining
Completed 114.4 MiB/233.2 MiB (50.7 MiB/s) with 3 file(s) remaining
Completed 114.7 MiB/233.2 MiB (50.8 MiB/s) with 3 file(s) remaining
Completed 114.9 MiB/233.2 MiB (50.8 MiB/s) with 3 file(s) remaining
Completed 115.2 MiB/233.2 MiB (50.9 MiB/s) with 3 file(s) remaining
Completed 115.4 MiB/233.2 MiB (51.0 MiB/s) with 3 file(s) remaining
Completed 115.7 MiB/233.2 MiB (51.1 MiB/s) with 3 file(s) remaining
Completed 115.9 MiB/233.2 MiB (51.2 MiB/s) with 3 file(s) remaining
Completed 116.2 MiB/233.2 MiB (51.3 MiB/s) with 3 file(s) remaining
Completed 116.4 MiB/233.2 MiB (51.3 MiB/s) with 3 file(s) remaining
Completed 116.7 MiB/233.2 MiB (51.4 MiB/s) with 3 file(s) remaining
Completed 116.9 MiB/233.2 MiB (51.5 MiB/s) with 3 file(s) remaining
Completed 117.2 MiB/233.2 MiB (51.6 MiB/s) with 3 file(s) remaining
Completed 117.4 MiB/233.2 MiB (51.7 MiB/s) with 3 file(s) remaining
Completed 117.7 MiB/233.2 MiB (51.7 MiB/s) with 3 file(s) remaining
Completed 117.9 MiB/233.2 MiB (51.7 MiB/s) with 3 file(s) remaining
Completed 118.2 MiB/233.2 MiB (51.8 MiB/s) with 3 file(s) remaining
Completed 118.4 MiB/233.2 MiB (51.8 MiB/s) with 3 file(s) remaining
Completed 118.7 MiB/233.2 MiB (51.9 MiB/s) with 3 file(s) remaining
Completed 118.9 MiB/233.2 MiB (51.9 MiB/s) with 3 file(s) remaining
Completed 119.2 MiB/233.2 MiB (52.0 MiB/s) with 3 file(s) remaining
Completed 119.4 MiB/233.2 MiB (52.0 MiB/s) with 3 file(s) remaining
Completed 119.7 MiB/233.2 MiB (52.1 MiB/s) with 3 file(s) remaining
Completed 119.9 MiB/233.2 MiB (52.2 MiB/s) with 3 file(s) remaining
Completed 120.2 MiB/233.2 MiB (52.2 MiB/s) with 3 file(s) remaining
Completed 120.4 MiB/233.2 MiB (52.3 MiB/s) with 3 file(s) remaining
Completed 120.7 MiB/233.2 MiB (52.3 MiB/s) with 3 file(s) remaining
Completed 120.9 MiB/233.2 MiB (52.4 MiB/s) with 3 file(s) remaining
Completed 121.2 MiB/233.2 MiB (52.1 MiB/s) with 3 file(s) remaining
Completed 121.4 MiB/233.2 MiB (44.6 MiB/s) with 3 file(s) remaining
Completed 121.7 MiB/233.2 MiB (44.7 MiB/s) with 3 file(s) remaining
Completed 121.9 MiB/233.2 MiB (44.8 MiB/s) with 3 file(s) remaining
Completed 122.2 MiB/233.2 MiB (44.9 MiB/s) with 3 file(s) remaining
Completed 122.4 MiB/233.2 MiB (44.9 MiB/s) with 3 file(s) remaining
Completed 122.7 MiB/233.2 MiB (45.0 MiB/s) with 3 file(s) remaining
Completed 122.9 MiB/233.2 MiB (45.1 MiB/s) with 3 file(s) remaining
Completed 123.2 MiB/233.2 MiB (45.2 MiB/s) with 3 file(s) remaining
Completed 123.4 MiB/233.2 MiB (45.3 MiB/s) with 3 file(s) remaining
Completed 123.7 MiB/233.2 MiB (45.3 MiB/s) with 3 file(s) remaining
Completed 123.9 MiB/233.2 MiB (45.4 MiB/s) with 3 file(s) remaining
Completed 124.2 MiB/233.2 MiB (45.4 MiB/s) with 3 file(s) remaining
Completed 124.4 MiB/233.2 MiB (45.5 MiB/s) with 3 file(s) remaining
Completed 124.7 MiB/233.2 MiB (45.6 MiB/s) with 3 file(s) remaining
Completed 124.9 MiB/233.2 MiB (45.6 MiB/s) with 3 file(s) remaining
Completed 125.2 MiB/233.2 MiB (45.7 MiB/s) with 3 file(s) remaining
Completed 125.4 MiB/233.2 MiB (45.7 MiB/s) with 3 file(s) remaining
Completed 125.7 MiB/233.2 MiB (45.8 MiB/s) with 3 file(s) remaining
Completed 125.9 MiB/233.2 MiB (45.8 MiB/s) with 3 file(s) remaining
Completed 126.2 MiB/233.2 MiB (45.9 MiB/s) with 3 file(s) remaining
Completed 126.4 MiB/233.2 MiB (45.9 MiB/s) with 3 file(s) remaining
Completed 126.7 MiB/233.2 MiB (46.0 MiB/s) with 3 file(s) remaining
Completed 126.9 MiB/233.2 MiB (46.1 MiB/s) with 3 file(s) remaining
Completed 127.2 MiB/233.2 MiB (46.1 MiB/s) with 3 file(s) remaining
Completed 127.4 MiB/233.2 MiB (46.2 MiB/s) with 3 file(s) remaining
Completed 127.7 MiB/233.2 MiB (46.2 MiB/s) with 3 file(s) remaining
Completed 127.9 MiB/233.2 MiB (46.3 MiB/s) with 3 file(s) remaining
Completed 128.2 MiB/233.2 MiB (46.4 MiB/s) with 3 file(s) remaining
Completed 128.4 MiB/233.2 MiB (46.4 MiB/s) with 3 file(s) remaining
Completed 128.7 MiB/233.2 MiB (46.5 MiB/s) with 3 file(s) remaining
Completed 128.9 MiB/233.2 MiB (46.5 MiB/s) with 3 file(s) remaining
Completed 129.2 MiB/233.2 MiB (46.6 MiB/s) with 3 file(s) remaining
Completed 129.4 MiB/233.2 MiB (46.2 MiB/s) with 3 file(s) remaining
Completed 129.7 MiB/233.2 MiB (46.3 MiB/s) with 3 file(s) remaining
Completed 129.9 MiB/233.2 MiB (46.4 MiB/s) with 3 file(s) remaining
Completed 130.2 MiB/233.2 MiB (45.4 MiB/s) with 3 file(s) remaining
Completed 130.4 MiB/233.2 MiB (39.6 MiB/s) with 3 file(s) remaining
Completed 130.7 MiB/233.2 MiB (39.7 MiB/s) with 3 file(s) remaining
Completed 130.9 MiB/233.2 MiB (39.8 MiB/s) with 3 file(s) remaining
Completed 131.2 MiB/233.2 MiB (38.8 MiB/s) with 3 file(s) remaining
Completed 131.4 MiB/233.2 MiB (38.5 MiB/s) with 3 file(s) remaining
Completed 131.7 MiB/233.2 MiB (38.1 MiB/s) with 3 file(s) remaining
Completed 131.9 MiB/233.2 MiB (33.7 MiB/s) with 3 file(s) remaining
Completed 132.2 MiB/233.2 MiB (33.7 MiB/s) with 3 file(s) remaining
Completed 132.4 MiB/233.2 MiB (33.8 MiB/s) with 3 file(s) remaining
Completed 132.7 MiB/233.2 MiB (33.8 MiB/s) with 3 file(s) remaining
Completed 132.9 MiB/233.2 MiB (33.9 MiB/s) with 3 file(s) remaining
Completed 133.2 MiB/233.2 MiB (33.9 MiB/s) with 3 file(s) remaining
Completed 133.4 MiB/233.2 MiB (34.0 MiB/s) with 3 file(s) remaining
Completed 133.7 MiB/233.2 MiB (34.1 MiB/s) with 3 file(s) remaining
Completed 133.9 MiB/233.2 MiB (34.1 MiB/s) with 3 file(s) remaining
Completed 134.2 MiB/233.2 MiB (34.2 MiB/s) with 3 file(s) remaining
Completed 134.4 MiB/233.2 MiB (34.2 MiB/s) with 3 file(s) remaining
Completed 134.7 MiB/233.2 MiB (34.3 MiB/s) with 3 file(s) remaining
Completed 134.9 MiB/233.2 MiB (34.3 MiB/s) with 3 file(s) remaining
Completed 135.2 MiB/233.2 MiB (34.4 MiB/s) with 3 file(s) remaining
Completed 135.4 MiB/233.2 MiB (34.4 MiB/s) with 3 file(s) remaining
Completed 135.7 MiB/233.2 MiB (34.4 MiB/s) with 3 file(s) remaining
Completed 135.9 MiB/233.2 MiB (34.5 MiB/s) with 3 file(s) remaining
Completed 136.2 MiB/233.2 MiB (34.5 MiB/s) with 3 file(s) remaining
Completed 136.4 MiB/233.2 MiB (34.6 MiB/s) with 3 file(s) remaining
Completed 136.7 MiB/233.2 MiB (34.6 MiB/s) with 3 file(s) remaining
Completed 136.9 MiB/233.2 MiB (34.7 MiB/s) with 3 file(s) remaining
Completed 137.2 MiB/233.2 MiB (34.7 MiB/s) with 3 file(s) remaining
Completed 137.4 MiB/233.2 MiB (34.8 MiB/s) with 3 file(s) remaining
Completed 137.7 MiB/233.2 MiB (34.8 MiB/s) with 3 file(s) remaining
Completed 137.9 MiB/233.2 MiB (34.9 MiB/s) with 3 file(s) remaining
Completed 138.2 MiB/233.2 MiB (34.9 MiB/s) with 3 file(s) remaining
Completed 138.4 MiB/233.2 MiB (35.0 MiB/s) with 3 file(s) remaining
Completed 138.7 MiB/233.2 MiB (35.1 MiB/s) with 3 file(s) remaining
Completed 138.9 MiB/233.2 MiB (35.1 MiB/s) with 3 file(s) remaining
Completed 139.2 MiB/233.2 MiB (35.2 MiB/s) with 3 file(s) remaining
Completed 139.4 MiB/233.2 MiB (35.2 MiB/s) with 3 file(s) remaining
Completed 139.7 MiB/233.2 MiB (35.3 MiB/s) with 3 file(s) remaining
Completed 139.9 MiB/233.2 MiB (35.3 MiB/s) with 3 file(s) remaining
Completed 140.2 MiB/233.2 MiB (35.4 MiB/s) with 3 file(s) remaining
Completed 140.4 MiB/233.2 MiB (35.4 MiB/s) with 3 file(s) remaining
Completed 140.7 MiB/233.2 MiB (35.5 MiB/s) with 3 file(s) remaining
Completed 140.9 MiB/233.2 MiB (35.5 MiB/s) with 3 file(s) remaining
Completed 141.2 MiB/233.2 MiB (35.6 MiB/s) with 3 file(s) remaining
Completed 141.4 MiB/233.2 MiB (35.6 MiB/s) with 3 file(s) remaining
Completed 141.7 MiB/233.2 MiB (35.7 MiB/s) with 3 file(s) remaining
Completed 141.9 MiB/233.2 MiB (35.7 MiB/s) with 3 file(s) remaining
Completed 142.2 MiB/233.2 MiB (35.7 MiB/s) with 3 file(s) remaining
Completed 142.4 MiB/233.2 MiB (35.8 MiB/s) with 3 file(s) remaining
Completed 142.7 MiB/233.2 MiB (35.8 MiB/s) with 3 file(s) remaining
Completed 142.9 MiB/233.2 MiB (35.9 MiB/s) with 3 file(s) remaining
Completed 143.2 MiB/233.2 MiB (35.9 MiB/s) with 3 file(s) remaining
Completed 143.4 MiB/233.2 MiB (35.9 MiB/s) with 3 file(s) remaining
Completed 143.7 MiB/233.2 MiB (36.0 MiB/s) with 3 file(s) remaining
Completed 143.9 MiB/233.2 MiB (36.0 MiB/s) with 3 file(s) remaining
Completed 144.2 MiB/233.2 MiB (36.0 MiB/s) with 3 file(s) remaining
Completed 144.4 MiB/233.2 MiB (36.0 MiB/s) with 3 file(s) remaining
Completed 144.7 MiB/233.2 MiB (36.1 MiB/s) with 3 file(s) remaining
Completed 144.9 MiB/233.2 MiB (36.1 MiB/s) with 3 file(s) remaining
Completed 145.2 MiB/233.2 MiB (36.1 MiB/s) with 3 file(s) remaining
Completed 145.4 MiB/233.2 MiB (36.1 MiB/s) with 3 file(s) remaining
Completed 145.7 MiB/233.2 MiB (36.2 MiB/s) with 3 file(s) remaining
Completed 145.9 MiB/233.2 MiB (36.2 MiB/s) with 3 file(s) remaining
Completed 146.2 MiB/233.2 MiB (36.2 MiB/s) with 3 file(s) remaining
Completed 146.4 MiB/233.2 MiB (36.3 MiB/s) with 3 file(s) remaining
Completed 146.7 MiB/233.2 MiB (36.3 MiB/s) with 3 file(s) remaining
Completed 146.9 MiB/233.2 MiB (36.3 MiB/s) with 3 file(s) remaining
Completed 147.2 MiB/233.2 MiB (36.2 MiB/s) with 3 file(s) remaining
Completed 147.4 MiB/233.2 MiB (36.1 MiB/s) with 3 file(s) remaining
Completed 147.7 MiB/233.2 MiB (36.0 MiB/s) with 3 file(s) remaining
Completed 147.9 MiB/233.2 MiB (28.6 MiB/s) with 3 file(s) remaining
Completed 148.2 MiB/233.2 MiB (28.7 MiB/s) with 3 file(s) remaining
Completed 148.4 MiB/233.2 MiB (28.7 MiB/s) with 3 file(s) remaining
Completed 148.7 MiB/233.2 MiB (28.3 MiB/s) with 3 file(s) remaining
Completed 148.9 MiB/233.2 MiB (27.9 MiB/s) with 3 file(s) remaining
Completed 149.2 MiB/233.2 MiB (27.9 MiB/s) with 3 file(s) remaining
Completed 149.4 MiB/233.2 MiB (28.0 MiB/s) with 3 file(s) remaining
Completed 149.7 MiB/233.2 MiB (28.0 MiB/s) with 3 file(s) remaining
Completed 149.9 MiB/233.2 MiB (28.0 MiB/s) with 3 file(s) remaining
Completed 150.2 MiB/233.2 MiB (28.1 MiB/s) with 3 file(s) remaining
Completed 150.4 MiB/233.2 MiB (28.1 MiB/s) with 3 file(s) remaining
Completed 150.7 MiB/233.2 MiB (28.2 MiB/s) with 3 file(s) remaining
Completed 150.9 MiB/233.2 MiB (28.2 MiB/s) with 3 file(s) remaining
Completed 151.2 MiB/233.2 MiB (28.1 MiB/s) with 3 file(s) remaining
Completed 151.4 MiB/233.2 MiB (27.9 MiB/s) with 3 file(s) remaining
Completed 151.7 MiB/233.2 MiB (27.7 MiB/s) with 3 file(s) remaining
Completed 151.9 MiB/233.2 MiB (27.6 MiB/s) with 3 file(s) remaining
Completed 152.2 MiB/233.2 MiB (27.6 MiB/s) with 3 file(s) remaining
Completed 152.4 MiB/233.2 MiB (27.7 MiB/s) with 3 file(s) remaining
Completed 152.7 MiB/233.2 MiB (27.5 MiB/s) with 3 file(s) remaining
Completed 152.9 MiB/233.2 MiB (27.5 MiB/s) with 3 file(s) remaining
Completed 153.2 MiB/233.2 MiB (27.4 MiB/s) with 3 file(s) remaining
Completed 153.4 MiB/233.2 MiB (27.4 MiB/s) with 3 file(s) remaining
Completed 153.7 MiB/233.2 MiB (27.2 MiB/s) with 3 file(s) remaining
Completed 153.9 MiB/233.2 MiB (27.3 MiB/s) with 3 file(s) remaining
Completed 154.2 MiB/233.2 MiB (27.3 MiB/s) with 3 file(s) remaining
Completed 154.4 MiB/233.2 MiB (27.1 MiB/s) with 3 file(s) remaining
Completed 154.7 MiB/233.2 MiB (26.6 MiB/s) with 3 file(s) remaining
Completed 154.9 MiB/233.2 MiB (26.7 MiB/s) with 3 file(s) remaining
Completed 155.2 MiB/233.2 MiB (26.7 MiB/s) with 3 file(s) remaining
Completed 155.4 MiB/233.2 MiB (26.7 MiB/s) with 3 file(s) remaining
Completed 155.7 MiB/233.2 MiB (26.8 MiB/s) with 3 file(s) remaining
Completed 155.9 MiB/233.2 MiB (26.8 MiB/s) with 3 file(s) remaining
Completed 156.2 MiB/233.2 MiB (26.8 MiB/s) with 3 file(s) remaining
Completed 156.4 MiB/233.2 MiB (26.9 MiB/s) with 3 file(s) remaining
Completed 156.7 MiB/233.2 MiB (26.9 MiB/s) with 3 file(s) remaining
Completed 156.9 MiB/233.2 MiB (26.3 MiB/s) with 3 file(s) remaining
Completed 157.2 MiB/233.2 MiB (26.3 MiB/s) with 3 file(s) remaining
Completed 157.4 MiB/233.2 MiB (26.4 MiB/s) with 3 file(s) remaining
Completed 157.7 MiB/233.2 MiB (26.4 MiB/s) with 3 file(s) remaining
Completed 157.9 MiB/233.2 MiB (26.4 MiB/s) with 3 file(s) remaining
Completed 158.2 MiB/233.2 MiB (26.4 MiB/s) with 3 file(s) remaining
Completed 158.4 MiB/233.2 MiB (26.5 MiB/s) with 3 file(s) remaining
Completed 158.7 MiB/233.2 MiB (26.5 MiB/s) with 3 file(s) remaining
Completed 158.9 MiB/233.2 MiB (26.5 MiB/s) with 3 file(s) remaining
Completed 159.2 MiB/233.2 MiB (26.6 MiB/s) with 3 file(s) remaining
Completed 159.4 MiB/233.2 MiB (26.6 MiB/s) with 3 file(s) remaining
Completed 159.7 MiB/233.2 MiB (26.6 MiB/s) with 3 file(s) remaining
Completed 159.9 MiB/233.2 MiB (26.6 MiB/s) with 3 file(s) remaining
Completed 160.2 MiB/233.2 MiB (26.7 MiB/s) with 3 file(s) remaining
Completed 160.4 MiB/233.2 MiB (26.7 MiB/s) with 3 file(s) remaining
Completed 160.7 MiB/233.2 MiB (26.7 MiB/s) with 3 file(s) remaining
Completed 160.9 MiB/233.2 MiB (26.8 MiB/s) with 3 file(s) remaining
Completed 161.2 MiB/233.2 MiB (26.8 MiB/s) with 3 file(s) remaining
Completed 161.4 MiB/233.2 MiB (26.8 MiB/s) with 3 file(s) remaining
Completed 161.7 MiB/233.2 MiB (26.9 MiB/s) with 3 file(s) remaining
Completed 161.9 MiB/233.2 MiB (26.9 MiB/s) with 3 file(s) remaining
Completed 162.2 MiB/233.2 MiB (26.9 MiB/s) with 3 file(s) remaining
Completed 162.4 MiB/233.2 MiB (26.9 MiB/s) with 3 file(s) remaining
Completed 162.7 MiB/233.2 MiB (27.0 MiB/s) with 3 file(s) remaining
Completed 162.9 MiB/233.2 MiB (27.0 MiB/s) with 3 file(s) remaining
Completed 163.2 MiB/233.2 MiB (27.0 MiB/s) with 3 file(s) remaining
Completed 163.4 MiB/233.2 MiB (27.1 MiB/s) with 3 file(s) remaining
Completed 163.7 MiB/233.2 MiB (27.1 MiB/s) with 3 file(s) remaining
Completed 163.9 MiB/233.2 MiB (24.7 MiB/s) with 3 file(s) remaining
Completed 164.2 MiB/233.2 MiB (24.7 MiB/s) with 3 file(s) remaining
Completed 164.4 MiB/233.2 MiB (24.8 MiB/s) with 3 file(s) remaining
Completed 164.7 MiB/233.2 MiB (24.8 MiB/s) with 3 file(s) remaining
Completed 164.9 MiB/233.2 MiB (22.6 MiB/s) with 3 file(s) remaining
Completed 165.2 MiB/233.2 MiB (22.6 MiB/s) with 3 file(s) remaining
Completed 165.4 MiB/233.2 MiB (22.6 MiB/s) with 3 file(s) remaining
Completed 165.7 MiB/233.2 MiB (22.7 MiB/s) with 3 file(s) remaining
Completed 165.9 MiB/233.2 MiB (22.7 MiB/s) with 3 file(s) remaining
Completed 166.2 MiB/233.2 MiB (22.7 MiB/s) with 3 file(s) remaining
Completed 166.4 MiB/233.2 MiB (22.8 MiB/s) with 3 file(s) remaining
Completed 166.7 MiB/233.2 MiB (22.8 MiB/s) with 3 file(s) remaining
Completed 166.9 MiB/233.2 MiB (22.8 MiB/s) with 3 file(s) remaining
Completed 167.2 MiB/233.2 MiB (22.9 MiB/s) with 3 file(s) remaining
Completed 167.4 MiB/233.2 MiB (22.9 MiB/s) with 3 file(s) remaining
Completed 167.7 MiB/233.2 MiB (22.9 MiB/s) with 3 file(s) remaining
Completed 167.9 MiB/233.2 MiB (23.0 MiB/s) with 3 file(s) remaining
Completed 168.2 MiB/233.2 MiB (23.0 MiB/s) with 3 file(s) remaining
Completed 168.4 MiB/233.2 MiB (23.0 MiB/s) with 3 file(s) remaining
Completed 168.7 MiB/233.2 MiB (23.0 MiB/s) with 3 file(s) remaining
Completed 168.9 MiB/233.2 MiB (23.0 MiB/s) with 3 file(s) remaining
Completed 169.2 MiB/233.2 MiB (23.0 MiB/s) with 3 file(s) remaining
Completed 169.4 MiB/233.2 MiB (23.1 MiB/s) with 3 file(s) remaining
Completed 169.7 MiB/233.2 MiB (23.1 MiB/s) with 3 file(s) remaining
Completed 169.9 MiB/233.2 MiB (23.1 MiB/s) with 3 file(s) remaining
Completed 170.2 MiB/233.2 MiB (23.2 MiB/s) with 3 file(s) remaining
Completed 170.4 MiB/233.2 MiB (23.2 MiB/s) with 3 file(s) remaining
Completed 170.7 MiB/233.2 MiB (23.2 MiB/s) with 3 file(s) remaining
Completed 170.9 MiB/233.2 MiB (23.2 MiB/s) with 3 file(s) remaining
Completed 171.2 MiB/233.2 MiB (23.3 MiB/s) with 3 file(s) remaining
Completed 171.4 MiB/233.2 MiB (23.3 MiB/s) with 3 file(s) remaining
Completed 171.7 MiB/233.2 MiB (23.3 MiB/s) with 3 file(s) remaining
Completed 171.9 MiB/233.2 MiB (23.3 MiB/s) with 3 file(s) remaining
Completed 172.2 MiB/233.2 MiB (23.4 MiB/s) with 3 file(s) remaining
Completed 172.4 MiB/233.2 MiB (23.4 MiB/s) with 3 file(s) remaining
Completed 172.7 MiB/233.2 MiB (23.4 MiB/s) with 3 file(s) remaining
Completed 172.9 MiB/233.2 MiB (22.9 MiB/s) with 3 file(s) remaining
Completed 173.2 MiB/233.2 MiB (22.9 MiB/s) with 3 file(s) remaining
Completed 173.4 MiB/233.2 MiB (22.9 MiB/s) with 3 file(s) remaining
Completed 173.7 MiB/233.2 MiB (22.9 MiB/s) with 3 file(s) remaining
Completed 173.9 MiB/233.2 MiB (22.9 MiB/s) with 3 file(s) remaining
Completed 174.2 MiB/233.2 MiB (23.0 MiB/s) with 3 file(s) remaining
Completed 174.4 MiB/233.2 MiB (23.0 MiB/s) with 3 file(s) remaining
Completed 174.7 MiB/233.2 MiB (23.0 MiB/s) with 3 file(s) remaining
Completed 174.9 MiB/233.2 MiB (23.0 MiB/s) with 3 file(s) remaining
Completed 175.2 MiB/233.2 MiB (23.1 MiB/s) with 3 file(s) remaining
Completed 175.4 MiB/233.2 MiB (23.1 MiB/s) with 3 file(s) remaining
Completed 175.7 MiB/233.2 MiB (23.1 MiB/s) with 3 file(s) remaining
Completed 175.9 MiB/233.2 MiB (23.2 MiB/s) with 3 file(s) remaining
Completed 176.2 MiB/233.2 MiB (23.2 MiB/s) with 3 file(s) remaining
Completed 176.4 MiB/233.2 MiB (23.2 MiB/s) with 3 file(s) remaining
Completed 176.7 MiB/233.2 MiB (23.2 MiB/s) with 3 file(s) remaining
Completed 176.9 MiB/233.2 MiB (23.3 MiB/s) with 3 file(s) remaining
Completed 177.2 MiB/233.2 MiB (23.3 MiB/s) with 3 file(s) remaining
Completed 177.4 MiB/233.2 MiB (23.3 MiB/s) with 3 file(s) remaining
Completed 177.7 MiB/233.2 MiB (23.3 MiB/s) with 3 file(s) remaining
Completed 177.9 MiB/233.2 MiB (23.4 MiB/s) with 3 file(s) remaining
Completed 178.2 MiB/233.2 MiB (23.4 MiB/s) with 3 file(s) remaining
Completed 178.4 MiB/233.2 MiB (23.4 MiB/s) with 3 file(s) remaining
Completed 178.7 MiB/233.2 MiB (23.4 MiB/s) with 3 file(s) remaining
Completed 178.9 MiB/233.2 MiB (23.5 MiB/s) with 3 file(s) remaining
Completed 179.2 MiB/233.2 MiB (23.5 MiB/s) with 3 file(s) remaining
Completed 179.4 MiB/233.2 MiB (23.5 MiB/s) with 3 file(s) remaining
Completed 179.7 MiB/233.2 MiB (23.5 MiB/s) with 3 file(s) remaining
Completed 179.9 MiB/233.2 MiB (23.6 MiB/s) with 3 file(s) remaining
Completed 180.2 MiB/233.2 MiB (23.6 MiB/s) with 3 file(s) remaining
Completed 180.4 MiB/233.2 MiB (23.6 MiB/s) with 3 file(s) remaining
Completed 180.7 MiB/233.2 MiB (23.6 MiB/s) with 3 file(s) remaining
Completed 180.9 MiB/233.2 MiB (23.7 MiB/s) with 3 file(s) remaining
Completed 181.2 MiB/233.2 MiB (23.7 MiB/s) with 3 file(s) remaining
Completed 181.4 MiB/233.2 MiB (23.7 MiB/s) with 3 file(s) remaining
Completed 181.7 MiB/233.2 MiB (23.7 MiB/s) with 3 file(s) remaining
Completed 181.9 MiB/233.2 MiB (23.8 MiB/s) with 3 file(s) remaining
Completed 182.2 MiB/233.2 MiB (23.8 MiB/s) with 3 file(s) remaining
Completed 182.4 MiB/233.2 MiB (23.8 MiB/s) with 3 file(s) remaining
Completed 182.7 MiB/233.2 MiB (23.8 MiB/s) with 3 file(s) remaining
Completed 182.9 MiB/233.2 MiB (23.9 MiB/s) with 3 file(s) remaining
Completed 183.2 MiB/233.2 MiB (23.9 MiB/s) with 3 file(s) remaining
Completed 183.4 MiB/233.2 MiB (23.9 MiB/s) with 3 file(s) remaining
Completed 183.7 MiB/233.2 MiB (23.9 MiB/s) with 3 file(s) remaining
Completed 183.9 MiB/233.2 MiB (24.0 MiB/s) with 3 file(s) remaining
Completed 184.2 MiB/233.2 MiB (24.0 MiB/s) with 3 file(s) remaining
Completed 184.4 MiB/233.2 MiB (24.0 MiB/s) with 3 file(s) remaining
Completed 184.7 MiB/233.2 MiB (24.0 MiB/s) with 3 file(s) remaining
Completed 184.9 MiB/233.2 MiB (24.1 MiB/s) with 3 file(s) remaining
Completed 185.2 MiB/233.2 MiB (24.1 MiB/s) with 3 file(s) remaining
Completed 185.4 MiB/233.2 MiB (24.1 MiB/s) with 3 file(s) remaining
Completed 185.7 MiB/233.2 MiB (24.1 MiB/s) with 3 file(s) remaining
Completed 185.9 MiB/233.2 MiB (24.1 MiB/s) with 3 file(s) remaining
Completed 186.2 MiB/233.2 MiB (24.2 MiB/s) with 3 file(s) remaining
Completed 186.4 MiB/233.2 MiB (24.2 MiB/s) with 3 file(s) remaining
Completed 186.7 MiB/233.2 MiB (24.2 MiB/s) with 3 file(s) remaining
Completed 186.9 MiB/233.2 MiB (24.1 MiB/s) with 3 file(s) remaining
Completed 187.2 MiB/233.2 MiB (24.1 MiB/s) with 3 file(s) remaining
Completed 187.4 MiB/233.2 MiB (24.2 MiB/s) with 3 file(s) remaining
Completed 187.7 MiB/233.2 MiB (24.2 MiB/s) with 3 file(s) remaining
Completed 187.9 MiB/233.2 MiB (24.2 MiB/s) with 3 file(s) remaining
Completed 188.2 MiB/233.2 MiB (24.3 MiB/s) with 3 file(s) remaining
Completed 188.4 MiB/233.2 MiB (24.3 MiB/s) with 3 file(s) remaining
Completed 188.7 MiB/233.2 MiB (24.3 MiB/s) with 3 file(s) remaining
Completed 188.9 MiB/233.2 MiB (24.4 MiB/s) with 3 file(s) remaining
Completed 189.2 MiB/233.2 MiB (24.4 MiB/s) with 3 file(s) remaining
Completed 189.4 MiB/233.2 MiB (24.4 MiB/s) with 3 file(s) remaining
Completed 189.7 MiB/233.2 MiB (24.4 MiB/s) with 3 file(s) remaining
Completed 189.9 MiB/233.2 MiB (24.5 MiB/s) with 3 file(s) remaining
Completed 190.2 MiB/233.2 MiB (24.5 MiB/s) with 3 file(s) remaining
Completed 190.4 MiB/233.2 MiB (24.5 MiB/s) with 3 file(s) remaining
Completed 190.7 MiB/233.2 MiB (24.5 MiB/s) with 3 file(s) remaining
Completed 190.9 MiB/233.2 MiB (24.6 MiB/s) with 3 file(s) remaining
Completed 191.2 MiB/233.2 MiB (24.6 MiB/s) with 3 file(s) remaining
Completed 191.4 MiB/233.2 MiB (24.6 MiB/s) with 3 file(s) remaining
Completed 191.7 MiB/233.2 MiB (24.6 MiB/s) with 3 file(s) remaining
Completed 191.9 MiB/233.2 MiB (24.6 MiB/s) with 3 file(s) remaining
Completed 192.2 MiB/233.2 MiB (24.7 MiB/s) with 3 file(s) remaining
Completed 192.4 MiB/233.2 MiB (24.7 MiB/s) with 3 file(s) remaining
Completed 192.7 MiB/233.2 MiB (24.7 MiB/s) with 3 file(s) remaining
Completed 192.9 MiB/233.2 MiB (24.7 MiB/s) with 3 file(s) remaining
Completed 193.2 MiB/233.2 MiB (24.8 MiB/s) with 3 file(s) remaining
Completed 193.4 MiB/233.2 MiB (24.8 MiB/s) with 3 file(s) remaining
Completed 193.7 MiB/233.2 MiB (24.8 MiB/s) with 3 file(s) remaining
Completed 193.9 MiB/233.2 MiB (24.8 MiB/s) with 3 file(s) remaining
Completed 194.2 MiB/233.2 MiB (24.8 MiB/s) with 3 file(s) remaining
Completed 194.4 MiB/233.2 MiB (24.9 MiB/s) with 3 file(s) remaining
Completed 194.7 MiB/233.2 MiB (24.9 MiB/s) with 3 file(s) remaining
Completed 194.9 MiB/233.2 MiB (24.7 MiB/s) with 3 file(s) remaining
Completed 195.2 MiB/233.2 MiB (24.6 MiB/s) with 3 file(s) remaining
Completed 195.4 MiB/233.2 MiB (24.6 MiB/s) with 3 file(s) remaining
Completed 195.7 MiB/233.2 MiB (24.6 MiB/s) with 3 file(s) remaining
Completed 195.9 MiB/233.2 MiB (24.6 MiB/s) with 3 file(s) remaining
Completed 196.2 MiB/233.2 MiB (24.6 MiB/s) with 3 file(s) remaining
Completed 196.4 MiB/233.2 MiB (24.6 MiB/s) with 3 file(s) remaining
Completed 196.7 MiB/233.2 MiB (24.6 MiB/s) with 3 file(s) remaining
Completed 196.9 MiB/233.2 MiB (24.6 MiB/s) with 3 file(s) remaining
Completed 197.2 MiB/233.2 MiB (24.7 MiB/s) with 3 file(s) remaining
Completed 197.4 MiB/233.2 MiB (24.7 MiB/s) with 3 file(s) remaining
Completed 197.7 MiB/233.2 MiB (24.7 MiB/s) with 3 file(s) remaining
Completed 197.9 MiB/233.2 MiB (24.7 MiB/s) with 3 file(s) remaining
Completed 198.2 MiB/233.2 MiB (24.8 MiB/s) with 3 file(s) remaining
Completed 198.4 MiB/233.2 MiB (24.8 MiB/s) with 3 file(s) remaining
Completed 198.7 MiB/233.2 MiB (24.8 MiB/s) with 3 file(s) remaining
Completed 198.9 MiB/233.2 MiB (24.8 MiB/s) with 3 file(s) remaining
Completed 199.2 MiB/233.2 MiB (24.9 MiB/s) with 3 file(s) remaining
Completed 199.4 MiB/233.2 MiB (24.9 MiB/s) with 3 file(s) remaining
Completed 199.7 MiB/233.2 MiB (24.9 MiB/s) with 3 file(s) remaining
Completed 199.9 MiB/233.2 MiB (24.9 MiB/s) with 3 file(s) remaining
Completed 200.2 MiB/233.2 MiB (25.0 MiB/s) with 3 file(s) remaining
Completed 200.4 MiB/233.2 MiB (25.0 MiB/s) with 3 file(s) remaining
Completed 200.7 MiB/233.2 MiB (25.0 MiB/s) with 3 file(s) remaining
Completed 200.9 MiB/233.2 MiB (25.0 MiB/s) with 3 file(s) remaining
Completed 201.2 MiB/233.2 MiB (25.0 MiB/s) with 3 file(s) remaining
Completed 201.4 MiB/233.2 MiB (24.8 MiB/s) with 3 file(s) remaining
Completed 201.7 MiB/233.2 MiB (24.8 MiB/s) with 3 file(s) remaining
Completed 201.9 MiB/233.2 MiB (24.8 MiB/s) with 3 file(s) remaining
Completed 202.2 MiB/233.2 MiB (24.8 MiB/s) with 3 file(s) remaining
Completed 202.4 MiB/233.2 MiB (24.8 MiB/s) with 3 file(s) remaining
Completed 202.7 MiB/233.2 MiB (24.9 MiB/s) with 3 file(s) remaining
Completed 202.9 MiB/233.2 MiB (24.9 MiB/s) with 3 file(s) remaining
Completed 203.2 MiB/233.2 MiB (24.9 MiB/s) with 3 file(s) remaining
Completed 203.4 MiB/233.2 MiB (24.9 MiB/s) with 3 file(s) remaining
Completed 203.7 MiB/233.2 MiB (24.9 MiB/s) with 3 file(s) remaining
Completed 203.9 MiB/233.2 MiB (25.0 MiB/s) with 3 file(s) remaining
Completed 204.2 MiB/233.2 MiB (25.0 MiB/s) with 3 file(s) remaining
Completed 204.4 MiB/233.2 MiB (25.0 MiB/s) with 3 file(s) remaining
Completed 204.7 MiB/233.2 MiB (25.0 MiB/s) with 3 file(s) remaining
Completed 204.9 MiB/233.2 MiB (25.1 MiB/s) with 3 file(s) remaining
Completed 205.2 MiB/233.2 MiB (25.1 MiB/s) with 3 file(s) remaining
Completed 205.4 MiB/233.2 MiB (25.1 MiB/s) with 3 file(s) remaining
Completed 205.7 MiB/233.2 MiB (25.1 MiB/s) with 3 file(s) remaining
Completed 205.9 MiB/233.2 MiB (25.1 MiB/s) with 3 file(s) remaining
Completed 206.2 MiB/233.2 MiB (25.2 MiB/s) with 3 file(s) remaining
Completed 206.4 MiB/233.2 MiB (25.2 MiB/s) with 3 file(s) remaining
Completed 206.7 MiB/233.2 MiB (25.2 MiB/s) with 3 file(s) remaining
Completed 206.9 MiB/233.2 MiB (25.2 MiB/s) with 3 file(s) remaining
Completed 207.2 MiB/233.2 MiB (25.2 MiB/s) with 3 file(s) remaining
Completed 207.4 MiB/233.2 MiB (25.3 MiB/s) with 3 file(s) remaining
Completed 207.7 MiB/233.2 MiB (25.3 MiB/s) with 3 file(s) remaining
Completed 207.9 MiB/233.2 MiB (25.3 MiB/s) with 3 file(s) remaining
Completed 208.2 MiB/233.2 MiB (25.3 MiB/s) with 3 file(s) remaining
Completed 208.4 MiB/233.2 MiB (24.7 MiB/s) with 3 file(s) remaining
Completed 208.7 MiB/233.2 MiB (24.7 MiB/s) with 3 file(s) remaining
Completed 208.9 MiB/233.2 MiB (24.7 MiB/s) with 3 file(s) remaining
Completed 209.2 MiB/233.2 MiB (24.8 MiB/s) with 3 file(s) remaining
Completed 209.4 MiB/233.2 MiB (24.8 MiB/s) with 3 file(s) remaining
Completed 209.7 MiB/233.2 MiB (24.8 MiB/s) with 3 file(s) remaining
Completed 209.9 MiB/233.2 MiB (24.8 MiB/s) with 3 file(s) remaining
Completed 210.2 MiB/233.2 MiB (24.9 MiB/s) with 3 file(s) remaining
Completed 210.4 MiB/233.2 MiB (24.9 MiB/s) with 3 file(s) remaining
Completed 210.7 MiB/233.2 MiB (24.9 MiB/s) with 3 file(s) remaining
Completed 210.9 MiB/233.2 MiB (25.0 MiB/s) with 3 file(s) remaining
Completed 211.2 MiB/233.2 MiB (25.0 MiB/s) with 3 file(s) remaining
Completed 211.4 MiB/233.2 MiB (25.0 MiB/s) with 3 file(s) remaining
Completed 211.7 MiB/233.2 MiB (25.0 MiB/s) with 3 file(s) remaining
Completed 211.9 MiB/233.2 MiB (25.0 MiB/s) with 3 file(s) remaining
upload: ../../../data/datafile-65-MB to s3://awscli-mint-test-bucket-16832/datafile-65-MBCompleted 211.9 MiB/233.2 MiB (25.0 MiB/s) with 2 file(s) remaining
Completed 212.2 MiB/233.2 MiB (25.0 MiB/s) with 2 file(s) remaining
Completed 212.4 MiB/233.2 MiB (25.1 MiB/s) with 2 file(s) remaining
Completed 212.7 MiB/233.2 MiB (25.1 MiB/s) with 2 file(s) remaining
Completed 212.9 MiB/233.2 MiB (25.1 MiB/s) with 2 file(s) remaining
Completed 213.2 MiB/233.2 MiB (25.1 MiB/s) with 2 file(s) remaining
Completed 213.4 MiB/233.2 MiB (25.2 MiB/s) with 2 file(s) remaining
Completed 213.7 MiB/233.2 MiB (25.2 MiB/s) with 2 file(s) remaining
Completed 213.9 MiB/233.2 MiB (25.1 MiB/s) with 2 file(s) remaining
Completed 214.2 MiB/233.2 MiB (25.1 MiB/s) with 2 file(s) remaining
Completed 214.4 MiB/233.2 MiB (25.1 MiB/s) with 2 file(s) remaining
Completed 214.7 MiB/233.2 MiB (25.2 MiB/s) with 2 file(s) remaining
Completed 214.9 MiB/233.2 MiB (25.2 MiB/s) with 2 file(s) remaining
Completed 215.2 MiB/233.2 MiB (25.2 MiB/s) with 2 file(s) remaining
Completed 215.4 MiB/233.2 MiB (25.3 MiB/s) with 2 file(s) remaining
Completed 215.7 MiB/233.2 MiB (25.3 MiB/s) with 2 file(s) remaining
Completed 215.9 MiB/233.2 MiB (25.3 MiB/s) with 2 file(s) remaining
Completed 216.2 MiB/233.2 MiB (25.3 MiB/s) with 2 file(s) remaining
Completed 216.4 MiB/233.2 MiB (25.3 MiB/s) with 2 file(s) remaining
Completed 216.7 MiB/233.2 MiB (25.4 MiB/s) with 2 file(s) remaining
Completed 216.9 MiB/233.2 MiB (25.4 MiB/s) with 2 file(s) remaining
Completed 217.2 MiB/233.2 MiB (25.4 MiB/s) with 2 file(s) remaining
Completed 217.4 MiB/233.2 MiB (25.4 MiB/s) with 2 file(s) remaining
Completed 217.7 MiB/233.2 MiB (25.4 MiB/s) with 2 file(s) remaining
Completed 217.9 MiB/233.2 MiB (25.5 MiB/s) with 2 file(s) remaining
Completed 218.2 MiB/233.2 MiB (25.5 MiB/s) with 2 file(s) remaining
Completed 218.4 MiB/233.2 MiB (25.5 MiB/s) with 2 file(s) remaining
Completed 218.7 MiB/233.2 MiB (25.5 MiB/s) with 2 file(s) remaining
Completed 218.9 MiB/233.2 MiB (25.6 MiB/s) with 2 file(s) remaining
Completed 219.2 MiB/233.2 MiB (25.6 MiB/s) with 2 file(s) remaining
Completed 219.4 MiB/233.2 MiB (25.6 MiB/s) with 2 file(s) remaining
Completed 219.7 MiB/233.2 MiB (25.6 MiB/s) with 2 file(s) remaining
Completed 219.9 MiB/233.2 MiB (25.6 MiB/s) with 2 file(s) remaining
Completed 220.2 MiB/233.2 MiB (25.7 MiB/s) with 2 file(s) remaining
Completed 220.4 MiB/233.2 MiB (25.7 MiB/s) with 2 file(s) remaining
Completed 220.7 MiB/233.2 MiB (25.7 MiB/s) with 2 file(s) remaining
Completed 220.9 MiB/233.2 MiB (25.7 MiB/s) with 2 file(s) remaining
Completed 221.2 MiB/233.2 MiB (25.8 MiB/s) with 2 file(s) remaining
Completed 221.4 MiB/233.2 MiB (25.8 MiB/s) with 2 file(s) remaining
Completed 221.7 MiB/233.2 MiB (25.8 MiB/s) with 2 file(s) remaining
Completed 221.9 MiB/233.2 MiB (25.8 MiB/s) with 2 file(s) remaining
Completed 222.2 MiB/233.2 MiB (25.8 MiB/s) with 2 file(s) remaining
Completed 222.4 MiB/233.2 MiB (25.8 MiB/s) with 2 file(s) remaining
Completed 222.7 MiB/233.2 MiB (25.9 MiB/s) with 2 file(s) remaining
Completed 222.9 MiB/233.2 MiB (25.6 MiB/s) with 2 file(s) remaining
Completed 223.2 MiB/233.2 MiB (25.7 MiB/s) with 2 file(s) remaining
Completed 223.4 MiB/233.2 MiB (25.7 MiB/s) with 2 file(s) remaining
Completed 223.7 MiB/233.2 MiB (25.7 MiB/s) with 2 file(s) remaining
Completed 223.9 MiB/233.2 MiB (25.7 MiB/s) with 2 file(s) remaining
Completed 224.2 MiB/233.2 MiB (25.7 MiB/s) with 2 file(s) remaining
Completed 224.4 MiB/233.2 MiB (25.5 MiB/s) with 2 file(s) remaining
Completed 224.7 MiB/2...Truncated

**Comment by minio-ops** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-compression-xl.sh | :heavy_check_mark: |
| mint-xl.sh | :heavy_check_mark: |
| mint-compression-fs.sh | :heavy_check_mark: |
| mint-worm.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-dist-xl.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :x: [more...](#7362264f-459d-4af3-80fe-4d1daea50ece) |
| mint-compression-dist-xl.sh | :x: [more...](#28e5385a-65ea-4858-a050-b368d62bf6d3) |
<a name="28e5385a-65ea-4858-a050-b368d62bf6d3"></a>
### 8027-adc5b66/mint-compression-dist-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.57:30587
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 2b7536bbb35e:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... FAILED in 12 seconds
{
  "alert": "",
  "args": {
    "bucketName": "aws-sdk-go-test-h3h5szwkrakvx6",
    "expiry": 60000000000,
    "objectName": "presignedTest"
  },
  "duration": 12091,
  "error": "RequestError: send request failed\ncaused by: Put http://72.28.97.57:30587/aws-sdk-go-test-h3h5szwkrakvx6: dial tcp 72.28.97.57:30587: connect: no route to host",
  "function": "PresignedPut",
  "message": "AWS SDK Go CreateBucket Failed",
  "name": "aws-sdk-go",
  "status": "FAIL"
}

Executed 0 out of 14 tests successfully.
```
<a name="7362264f-459d-4af3-80fe-4d1daea50ece"></a>
### 8027-adc5b66/mint-large-bucket.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.57:30440
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 7d3bea688046:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... FAILED in 16 seconds
{
  "alert": "",
  "args": {
    "bucketName": "aws-sdk-go-test-ugomnipfrgp6qh",
    "expiry": 60000000000,
    "objectName": "presignedTest"
  },
  "duration": 15346,
  "error": "RequestError: send request failed\ncaused by: Put http://72.28.97.57:30440/aws-sdk-go-test-ugomnipfrgp6qh: dial tcp 72.28.97.57:30440: connect: no route to host",
  "function": "PresignedPut",
  "message": "AWS SDK Go CreateBucket Failed",
  "name": "aws-sdk-go",
  "status": "FAIL"
}

Executed 0 out of 14 tests successfully.
```

**Comment by minio-ops** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-compression-xl.sh | :heavy_check_mark: |
| mint-xl.sh | :heavy_check_mark: |
| mint-compression-fs.sh | :heavy_check_mark: |
| mint-worm.sh | :heavy_check_mark: |
| mint-dist-xl.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :x: [more...](#d801dbb2-d866-4faa-873e-857d6770fb29) |
| mint-compression-dist-xl.sh | :x: [more...](#ff10100b-2065-455e-b591-867c734f8704) |
| mint-fs.sh | :x: [more...](#914284ce-decc-4f2f-a79c-dbf8abe54e33) |
<a name="ff10100b-2065-455e-b591-867c734f8704"></a>
### 8027-c2d3ddc/mint-compression-dist-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.60:30804
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp cef824b41bce:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 0 seconds
(2/14) Running aws-sdk-java tests ... done in 1 seconds
(3/14) Running aws-sdk-php tests ... done in 44 seconds
(4/14) Running aws-sdk-ruby tests ... done in 3 seconds
(5/14) Running awscli tests ... FAILED in 1 minutes and 49 seconds
{"name": "awscli", "duration": 62947, "function": "aws --endpoint-url http://72.28.97.60:30804 s3 sync /mint/data s3://awscli-mint-test-bucket-20632/\n", "status": "FAIL", "error": "upload: ../../../data/datafile-0-b to s3://awscli-mint-test-bucket-20632/datafile-0-bCompleted 0 Bytes/~157.2 MiB (0 Bytes/s) with ~11 file(s) remaining (calculating...)
Completed 256.0 KiB/233.2 MiB (3.1 MiB/s) with 14 file(s) remaining                 
Completed 512.0 KiB/233.2 MiB (6.0 MiB/s) with 14 file(s) remaining                 
Completed 768.0 KiB/233.2 MiB (8.9 MiB/s) with 14 file(s) remaining                 
Completed 1.0 MiB/233.2 MiB (11.8 MiB/s) with 14 file(s) remaining                  
Completed 1.2 MiB/233.2 MiB (14.5 MiB/s) with 14 file(s) remaining                  
Completed 1.5 MiB/233.2 MiB (17.2 MiB/s) with 14 file(s) remaining                  
Completed 1.8 MiB/233.2 MiB (19.9 MiB/s) with 14 file(s) remaining                  
Completed 2.0 MiB/233.2 MiB (22.6 MiB/s) with 14 file(s) remaining                  
Completed 2.0 MiB/233.2 MiB (20.6 MiB/s) with 14 file(s) remaining                  
upload: ../../../data/datafile-10-kB to s3://awscli-mint-test-bucket-20632/datafile-10-kBCompleted 2.0 MiB/233.2 MiB (20.6 MiB/s) with 13 file(s) remaining
Completed 2.0 MiB/233.2 MiB (17.6 MiB/s) with 13 file(s) remaining
upload: ../../../data/datafile-1-kB to s3://awscli-mint-test-bucket-20632/datafile-1-kBCompleted 2.0 MiB/233.2 MiB (17.6 MiB/s) with 12 file(s) remaining
Completed 2.1 MiB/233.2 MiB (18.0 MiB/s) with 12 file(s) remaining
upload: ../../../data/datafile-100-kB to s3://awscli-mint-test-bucket-20632/datafile-100-kBCompleted 2.1 MiB/233.2 MiB (18.0 MiB/s) with 11 file(s) remaining
Completed 2.1 MiB/233.2 MiB (17.8 MiB/s) with 11 file(s) remaining
upload: ../../../data/datafile-1-b to s3://awscli-mint-test-bucket-20632/datafile-1-bCompleted 2.1 MiB/233.2 MiB (17.8 MiB/s) with 10 file(s) remaining
Completed 2.1 MiB/233.2 MiB (14.6 MiB/s) with 10 file(s) remaining
upload: ../../../data/datafile-1.03-MB to s3://awscli-mint-test-bucket-20632/datafile-1.03-MBCompleted 2.1 MiB/233.2 MiB (14.6 MiB/s) with 9 file(s) remaining
Completed 2.4 MiB/233.2 MiB (16.1 MiB/s) with 9 file(s) remaining
Completed 2.6 MiB/233.2 MiB (17.7 MiB/s) with 9 file(s) remaining
Completed 2.9 MiB/233.2 MiB (19.2 MiB/s) with 9 file(s) remaining
Completed 3.1 MiB/233.2 MiB (20.8 MiB/s) with 9 file(s) remaining
Completed 3.4 MiB/233.2 MiB (22.4 MiB/s) with 9 file(s) remaining
Completed 3.6 MiB/233.2 MiB (23.9 MiB/s) with 9 file(s) remaining
Completed 3.9 MiB/233.2 MiB (24.7 MiB/s) with 9 file(s) remaining
Completed 4.1 MiB/233.2 MiB (25.2 MiB/s) with 9 file(s) remaining
upload: ../../../data/datafile-1-MB to s3://awscli-mint-test-bucket-20632/datafile-1-MBCompleted 4.1 MiB/233.2 MiB (25.2 MiB/s) with 8 file(s) remaining
Completed 4.4 MiB/233.2 MiB (26.1 MiB/s) with 8 file(s) remaining
Completed 4.6 MiB/233.2 MiB (27.2 MiB/s) with 8 file(s) remaining
Completed 4.9 MiB/233.2 MiB (28.7 MiB/s) with 8 file(s) remaining
Completed 5.1 MiB/233.2 MiB (29.7 MiB/s) with 8 file(s) remaining
Completed 5.4 MiB/233.2 MiB (30.8 MiB/s) with 8 file(s) remaining
Completed 5.6 MiB/233.2 MiB (32.1 MiB/s) with 8 file(s) remaining
Completed 5.9 MiB/233.2 MiB (33.4 MiB/s) with 8 file(s) remaining
Completed 6.1 MiB/233.2 MiB (34.6 MiB/s) with 8 file(s) remaining
Completed 6.4 MiB/233.2 MiB (35.5 MiB/s) with 8 file(s) remaining
Completed 6.6 MiB/233.2 MiB (36.7 MiB/s) with 8 file(s) remaining
Completed 6.9 MiB/233.2 MiB (38.0 MiB/s) with 8 file(s) remaining
Completed 7.1 MiB/233.2 MiB (39.0 MiB/s) with 8 file(s) remaining
Completed 7.4 MiB/233.2 MiB (40.2 MiB/s) with 8 file(s) remaining
Completed 7.6 MiB/233.2 MiB (41.1 MiB/s) with 8 file(s) remaining
Completed 7.9 MiB/233.2 MiB (42.3 MiB/s) with 8 file(s) remaining
Completed 8.1 MiB/233.2 MiB (43.5 MiB/s) with 8 file(s) remaining
Completed 8.4 MiB/233.2 MiB (44.4 MiB/s) with 8 file(s) remaining
Completed 8.6 MiB/233.2 MiB (45.5 MiB/s) with 8 file(s) remaining
Completed 8.9 MiB/233.2 MiB (46.3 MiB/s) with 8 file(s) remaining
Completed 9.1 MiB/233.2 MiB (47.5 MiB/s) with 8 file(s) remaining
Completed 9.4 MiB/233.2 MiB (48.3 MiB/s) with 8 file(s) remaining
Completed 9.6 MiB/233.2 MiB (48.9 MiB/s) with 8 file(s) remaining
Completed 9.9 MiB/233.2 MiB (49.7 MiB/s) with 8 file(s) remaining
Completed 10.1 MiB/233.2 MiB (50.9 MiB/s) with 8 file(s) remaining
Completed 10.4 MiB/233.2 MiB (51.9 MiB/s) with 8 file(s) remaining
Completed 10.6 MiB/233.2 MiB (52.5 MiB/s) with 8 file(s) remaining
Completed 10.9 MiB/233.2 MiB (53.5 MiB/s) with 8 file(s) remaining
Completed 11.1 MiB/233.2 MiB (54.3 MiB/s) with 8 file(s) remaining
Completed 11.4 MiB/233.2 MiB (55.1 MiB/s) with 8 file(s) remaining
Completed 11.6 MiB/233.2 MiB (55.8 MiB/s) with 8 file(s) remaining
Completed 11.9 MiB/233.2 MiB (56.9 MiB/s) with 8 file(s) remaining
Completed 12.1 MiB/233.2 MiB (57.8 MiB/s) with 8 file(s) remaining
Completed 12.4 MiB/233.2 MiB (58.5 MiB/s) with 8 file(s) remaining
Completed 12.6 MiB/233.2 MiB (59.0 MiB/s) with 8 file(s) remaining
Completed 12.9 MiB/233.2 MiB (60.1 MiB/s) with 8 file(s) remaining
Completed 13.1 MiB/233.2 MiB (61.0 MiB/s) with 8 file(s) remaining
Completed 13.4 MiB/233.2 MiB (61.6 MiB/s) with 8 file(s) remaining
Completed 13.6 MiB/233.2 MiB (62.5 MiB/s) with 8 file(s) remaining
Completed 13.9 MiB/233.2 MiB (63.2 MiB/s) with 8 file(s) remaining
Completed 14.1 MiB/233.2 MiB (63.7 MiB/s) with 8 file(s) remaining
Completed 14.4 MiB/233.2 MiB (64.5 MiB/s) with 8 file(s) remaining
Completed 14.6 MiB/233.2 MiB (65.3 MiB/s) with 8 file(s) remaining
Completed 14.9 MiB/233.2 MiB (66.1 MiB/s) with 8 file(s) remaining
Completed 15.1 MiB/233.2 MiB (67.1 MiB/s) with 8 file(s) remaining
Completed 15.4 MiB/233.2 MiB (67.8 MiB/s) with 8 file(s) remaining
Completed 15.6 MiB/233.2 MiB (68.0 MiB/s) with 8 file(s) remaining
Completed 15.9 MiB/233.2 MiB (68.8 MiB/s) with 8 file(s) remaining
Completed 16.1 MiB/233.2 MiB (69.7 MiB/s) with 8 file(s) remaining
Completed 16.4 MiB/233.2 MiB (69.2 MiB/s) with 8 file(s) remaining
Completed 16.6 MiB/233.2 MiB (69.3 MiB/s) with 8 file(s) remaining
Completed 16.9 MiB/233.2 MiB (69.2 MiB/s) with 8 file(s) remaining
Completed 17.1 MiB/233.2 MiB (70.0 MiB/s) with 8 file(s) remaining
Completed 17.4 MiB/233.2 MiB (70.8 MiB/s) with 8 file(s) remaining
Completed 17.6 MiB/233.2 MiB (71.7 MiB/s) with 8 file(s) remaining
Completed 17.9 MiB/233.2 MiB (70.6 MiB/s) with 8 file(s) remaining
Completed 18.1 MiB/233.2 MiB (70.1 MiB/s) with 8 file(s) remaining
Completed 18.4 MiB/233.2 MiB (70.9 MiB/s) with 8 file(s) remaining
Completed 18.6 MiB/233.2 MiB (71.8 MiB/s) with 8 file(s) remaining
Completed 18.9 MiB/233.2 MiB (70.0 MiB/s) with 8 file(s) remaining
Completed 19.1 MiB/233.2 MiB (70.7 MiB/s) with 8 file(s) remaining
Completed 19.4 MiB/233.2 MiB (71.3 MiB/s) with 8 file(s) remaining
Completed 19.6 MiB/233.2 MiB (71.7 MiB/s) with 8 file(s) remaining
Completed 19.9 MiB/233.2 MiB (72.5 MiB/s) with 8 file(s) remaining
Completed 20.1 MiB/233.2 MiB (73.3 MiB/s) with 8 file(s) remaining
Completed 20.4 MiB/233.2 MiB (73.8 MiB/s) with 8 file(s) remaining
Completed 20.6 MiB/233.2 MiB (74.4 MiB/s) with 8 file(s) remaining
Completed 20.9 MiB/233.2 MiB (75.0 MiB/s) with 8 file(s) remaining
Completed 21.1 MiB/233.2 MiB (75.9 MiB/s) with 8 file(s) remaining
Completed 21.4 MiB/233.2 MiB (75.4 MiB/s) with 8 file(s) remaining
Completed 21.6 MiB/233.2 MiB (75.1 MiB/s) with 8 file(s) remaining
Completed 21.9 MiB/233.2 MiB (75.0 MiB/s) with 8 file(s) remaining
Completed 22.1 MiB/233.2 MiB (74.5 MiB/s) with 8 file(s) remaining
Completed 22.4 MiB/233.2 MiB (74.2 MiB/s) with 8 file(s) remaining
Completed 22.6 MiB/233.2 MiB (73.9 MiB/s) with 8 file(s) remaining
Completed 22.9 MiB/233.2 MiB (74.1 MiB/s) with 8 file(s) remaining
Completed 23.1 MiB/233.2 MiB (74.8 MiB/s) with 8 file(s) remaining
Completed 23.4 MiB/233.2 MiB (74.0 MiB/s) with 8 file(s) remaining
Completed 23.6 MiB/233.2 MiB (73.4 MiB/s) with 8 file(s) remaining
Completed 23.9 MiB/233.2 MiB (71.9 MiB/s) with 8 file(s) remaining
Completed 24.1 MiB/233.2 MiB (72.3 MiB/s) with 8 file(s) remaining
Completed 24.4 MiB/233.2 MiB (71.6 MiB/s) with 8 file(s) remaining
Completed 24.6 MiB/233.2 MiB (71.3 MiB/s) with 8 file(s) remaining
Completed 24.9 MiB/233.2 MiB (70.2 MiB/s) with 8 file(s) remaining
Completed 25.1 MiB/233.2 MiB (70.2 MiB/s) with 8 file(s) remaining
Completed 25.4 MiB/233.2 MiB (69.8 MiB/s) with 8 file(s) remaining
Completed 25.6 MiB/233.2 MiB (69.5 MiB/s) with 8 file(s) remaining
Completed 25.9 MiB/233.2 MiB (70.0 MiB/s) with 8 file(s) remaining
Completed 26.1 MiB/233.2 MiB (70.5 MiB/s) with 8 file(s) remaining
Completed 26.4 MiB/233.2 MiB (71.1 MiB/s) with 8 file(s) remaining
Completed 26.6 MiB/233.2 MiB (71.7 MiB/s) with 8 file(s) remaining
Completed 26.9 MiB/233.2 MiB (72.2 MiB/s) with 8 file(s) remaining
Completed 27.1 MiB/233.2 MiB (70.7 MiB/s) with 8 file(s) remaining
Completed 27.4 MiB/233.2 MiB (71.3 MiB/s) with 8 file(s) remaining
Completed 27.6 MiB/233.2 MiB (71.7 MiB/s) with 8 file(s) remaining
Completed 27.9 MiB/233.2 MiB (70.2 MiB/s) with 8 file(s) remaining
Completed 28.1 MiB/233.2 MiB (70.1 MiB/s) with 8 file(s) remaining
Completed 28.4 MiB/233.2 MiB (69.5 MiB/s) with 8 file(s) remaining
Completed 28.6 MiB/233.2 MiB (69.8 MiB/s) with 8 file(s) remaining
Completed 28.9 MiB/233.2 MiB (70.3 MiB/s) with 8 file(s) remaining
Completed 29.1 MiB/233.2 MiB (69.6 MiB/s) with 8 file(s) remaining
Completed 29.4 MiB/233.2 MiB (70.0 MiB/s) with 8 file(s) remaining
Completed 29.6 MiB/233.2 MiB (69.1 MiB/s) with 8 file(s) remaining
Completed 29.9 MiB/233.2 MiB (69.2 MiB/s) with 8 file(s) remaining
Completed 30.1 MiB/233.2 MiB (69.6 MiB/s) with 8 file(s) remaining
Completed 30.4 MiB/233.2 MiB (69.3 MiB/s) with 8 file(s) remaining
Completed 30.6 MiB/233.2 MiB (68.9 MiB/s) with 8 file(s) remaining
Completed 30.9 MiB/233.2 MiB (69.0 MiB/s) with 8 file(s) remaining
Completed 31.1 MiB/233.2 MiB (69.4 MiB/s) with 8 file(s) remaining
Completed 31.4 MiB/233.2 MiB (69.4 MiB/s) with 8 file(s) remaining
Completed 31.6 MiB/233.2 MiB (69.9 MiB/s) with 8 file(s) remaining
upload: ../../../data/datafile-5-MB to s3://awscli-mint-test-bucket-20632/datafile-5-MBCompleted 31.6 MiB/233.2 MiB (69.9 MiB/s) with 7 file(s) remaining
Completed 31.9 MiB/233.2 MiB (68.7 MiB/s) with 7 file(s) remaining
Completed 32.1 MiB/233.2 MiB (69.0 MiB/s) with 7 file(s) remaining
Completed 32.4 MiB/233.2 MiB (68.2 MiB/s) with 7 file(s) remaining
Completed 32.6 MiB/233.2 MiB (68.3 MiB/s) with 7 file(s) remaining
Completed 32.9 MiB/233.2 MiB (68.5 MiB/s) with 7 file(s) remaining
Completed 32.9 MiB/233.2 MiB (67.9 MiB/s) with 7 file(s) remaining
upload: ../../../data/datafile-5243880-b to s3://awscli-mint-test-bucket-20632/datafile-5243880-bCompleted 32.9 MiB/233.2 MiB (67.9 MiB/s) with 6 file(s) remaining
Completed 33.1 MiB/233.2 MiB (67.7 MiB/s) with 6 file(s) remaining
Completed 33.4 MiB/233.2 MiB (68.1 MiB/s) with 6 file(s) remaining
Completed 33.6 MiB/233.2 MiB (68.2 MiB/s) with 6 file(s) remaining
Completed 33.9 MiB/233.2 MiB (68.2 MiB/s) with 6 file(s) remaining
Completed 34.1 MiB/233.2 MiB (68.4 MiB/s) with 6 file(s) remaining
Completed 34.4 MiB/233.2 MiB (68.3 MiB/s) with 6 file(s) remaining
Completed 34.6 MiB/233.2 MiB (68.5 MiB/s) with 6 file(s) remaining
Completed 34.9 MiB/233.2 MiB (69.0 MiB/s) with 6 file(s) remaining
Completed 35.1 MiB/233.2 MiB (68.7 MiB/s) with 6 file(s) remaining
Completed 35.4 MiB/233.2 MiB (69.0 MiB/s) with 6 file(s) remaining
Completed 35.6 MiB/233.2 MiB (69.4 MiB/s) with 6 file(s) remaining
Completed 35.9 MiB/233.2 MiB (69.3 MiB/s) with 6 file(s) remaining
Completed 36.1 MiB/233.2 MiB (69.4 MiB/s) with 6 file(s) remaining
Completed 36.4 MiB/233.2 MiB (69.4 MiB/s) with 6 file(s) remaining
Completed 36.6 MiB/233.2 MiB (69.2 MiB/s) with 6 file(s) remaining
Completed 36.9 MiB/233.2 MiB (69.6 MiB/s) with 6 file(s) remaining
Completed 37.1 MiB/233.2 MiB (69.6 MiB/s) with 6 file(s) remaining
Completed 37.4 MiB/233.2 MiB (69.9 MiB/s) with 6 file(s) remaining
Completed 37.6 MiB/233.2 MiB (69.6 MiB/s) with 6 file(s) remaining
Completed 37.9 MiB/233.2 MiB (69.9 MiB/s) with 6 file(s) remaining
Completed 38.1 MiB/233.2 MiB (70.3 MiB/s) with 6 file(s) remaining
Completed 38.4 MiB/233.2 MiB (69.7 MiB/s) with 6 file(s) remaining
Completed 38.6 MiB/233.2 MiB (70.0 MiB/s) with 6 file(s) remaining
Completed 38.9 MiB/233.2 MiB (70.4 MiB/s) with 6 file(s) remaining
Completed 39.1 MiB/233.2 MiB (70.0 MiB/s) with 6 file(s) remaining
Completed 39.4 MiB/233.2 MiB (70.5 MiB/s) with 6 file(s) remaining
Completed 39.6 MiB/233.2 MiB (70.3 MiB/s) with 6 file(s) remaining
Completed 39.9 MiB/233.2 MiB (70.1 MiB/s) with 6 file(s) remaining
Completed 40.1 MiB/233.2 MiB (70.5 MiB/s) with 6 file(s) remaining
Completed 40.4 MiB/233.2 MiB (70.0 MiB/s) with 6 file(s) remaining
Completed 40.6 MiB/233.2 MiB (70.4 MiB/s) with 6 file(s) remaining
Completed 40.9 MiB/233.2 MiB (70.7 MiB/s) with 6 file(s) remaining
Completed 41.1 MiB/233.2 MiB (70.2 MiB/s) with 6 file(s) remaining
Completed 41.4 MiB/233.2 MiB (70.1 MiB/s) with 6 file(s) remaining
Completed 41.6 MiB/233.2 MiB (70.5 MiB/s) with 6 file(s) remaining
Completed 41.9 MiB/233.2 MiB (70.4 MiB/s) with 6 file(s) remaining
Completed 42.1 MiB/233.2 MiB (70.8 MiB/s) with 6 file(s) remaining
Completed 42.4 MiB/233.2 MiB (71.1 MiB/s) with 6 file(s) remaining
Completed 42.6 MiB/233.2 MiB (70.9 MiB/s) with 6 file(s) remaining
Completed 42.9 MiB/233.2 MiB (71.3 MiB/s) with 6 file(s) remaining
Completed 43.1 MiB/233.2 MiB (71.0 MiB/s) with 6 file(s) remaining
Completed 43.4 MiB/233.2 MiB (70.6 MiB/s) with 6 file(s) remaining
Completed 43.6 MiB/233.2 MiB (70.8 MiB/s) with 6 file(s) remaining
Completed 43.9 MiB/233.2 MiB (70.6 MiB/s) with 6 file(s) remaining
Completed 44.1 MiB/233.2 MiB (70.9 MiB/s) with 6 file(s) remaining
upload: ../../../data/datafile-6-MB to s3://awscli-mint-test-bucket-20632/datafile-6-MBCompleted 44.1 MiB/233.2 MiB (70.9 MiB/s) with 5 file(s) remaining
Completed 44.4 MiB/233.2 MiB (70.6 MiB/s) with 5 file(s) remaining
Completed 44.6 MiB/233.2 MiB (70.3 MiB/s) with 5 file(s) remaining
Completed 44.9 MiB/233.2 MiB (70.6 MiB/s) with 5 file(s) remaining
Completed 45.1 MiB/233.2 MiB (70.9 MiB/s) with 5 file(s) remaining
Completed 45.4 MiB/233.2 MiB (71.3 MiB/s) with 5 file(s) remaining
Completed 45.6 MiB/233.2 MiB (71.6 MiB/s) with 5 file(s) remaining
Completed 45.9 MiB/233.2 MiB (71.8 MiB/s) with 5 file(s) remaining
Completed 46.1 MiB/233.2 MiB (72.1 MiB/s) with 5 file(s) remaining
Completed 46.4 MiB/233.2 MiB (71.8 MiB/s) with 5 file(s) remaining
Completed 46.6 MiB/233.2 MiB (72.2 MiB/s) with 5 file(s) remaining
Completed 46.9 MiB/233.2 MiB (72.4 MiB/s) with 5 file(s) remaining
Completed 47.1 MiB/233.2 MiB (72.2 MiB/s) with 5 file(s) remaining
Completed 47.4 MiB/233.2 MiB (72.0 MiB/s) with 5 file(s) remaining
Completed 47.6 MiB/233.2 MiB (71.8 MiB/s) with 5 file(s) remaining
Completed 47.9 MiB/233.2 MiB (71.7 MiB/s) with 5 file(s) remaining
Completed 48.1 MiB/233.2 MiB (71.9 MiB/s) with 5 file(s) remaining
Completed 48.4 MiB/233.2 MiB (72.1 MiB/s) with 5 file(s) remaining
Completed 48.6 MiB/233.2 MiB (71.4 MiB/s) with 5 file(s) remaining
Completed 48.9 MiB/233.2 MiB (71.6 MiB/s) with 5 file(s) remaining
Completed 49.1 MiB/233.2 MiB (71.1 MiB/s) with 5 file(s) remaining
Completed 49.4 MiB/233.2 MiB (71.4 MiB/s) with 5 file(s) remaining
Completed 49.6 MiB/233.2 MiB (71.6 MiB/s) with 5 file(s) remaining
Completed 49.9 MiB/233.2 MiB (70.7 MiB/s) with 5 file(s) remaining
Completed 50.1 MiB/233.2 MiB (70.4 MiB/s) with 5 file(s) remaining
Completed 50.4 MiB/233.2 MiB (69.8 MiB/s) with 5 file(s) remaining
Completed 50.6 MiB/233.2 MiB (69.5 MiB/s) with 5 file(s) remaining
Completed 50.9 MiB/233.2 MiB (68.9 MiB/s) with 5 file(s) remaining
Completed 51.1 MiB/233.2 MiB (68.6 MiB/s) with 5 file(s) remaining
Completed 51.4 MiB/233.2 MiB (68.0 MiB/s) with 5 file(s) remaining
Completed 51.6 MiB/233.2 MiB (67.7 MiB/s) with 5 file(s) remaining
Completed 51.9 MiB/233.2 MiB (67.8 MiB/s) with 5 file(s) remaining
Completed 52.1 MiB/233.2 MiB (68.1 MiB/s) with 5 file(s) remaining
Completed 52.4 MiB/233.2 MiB (68.3 MiB/s) with 5 file(s) remaining
Completed 52.6 MiB/233.2 MiB (68.5 MiB/s) with 5 file(s) remaining
Completed 52.9 MiB/233.2 MiB (68.8 MiB/s) with 5 file(s) remaining
Completed 53.1 MiB/233.2 MiB (68.6 MiB/s) with 5 file(s) remaining
Completed 53.4 MiB/233.2 MiB (68.4 MiB/s) with 5 file(s) remaining
Completed 53.6 MiB/233.2 MiB (68.5 MiB/s) with 5 file(s) remaining
Completed 53.9 MiB/233.2 MiB (68.2 MiB/s) with 5 file(s) remaining
Completed 54.1 MiB/233.2 MiB (68.2 MiB/s) with 5 file(s) remaining
Completed 54.4 MiB/233.2 MiB (68.1 MiB/s) with 5 file(s) remaining
Completed 54.6 MiB/233.2 MiB (67.8 MiB/s) with 5 file(s) remaining
Completed 54.9 MiB/233.2 MiB (68.1 MiB/s) with 5 file(s) remaining
Completed 55.1 MiB/233.2 MiB (67.6 MiB/s) with 5 file(s) remaining
Completed 55.4 MiB/233.2 MiB (67.7 MiB/s) with 5 file(s) remaining
Completed 55.6 MiB/233.2 MiB (67.8 MiB/s) with 5 file(s) remaining
Completed 55.9 MiB/233.2 MiB (67.2 MiB/s) with 5 file(s) remaining
Completed 56.1 MiB/233.2 MiB (67.5 MiB/s) with 5 file(s) remaining
Completed 56.4 MiB/233.2 MiB (67.4 MiB/s) with 5 file(s) remaining
Completed 56.6 MiB/233.2 MiB (67.0 MiB/s) with 5 file(s) remaining
Completed 56.9 MiB/233.2 MiB (67.0 MiB/s) with 5 file(s) remaining
Completed 57.1 MiB/233.2 MiB (66.8 MiB/s) with 5 file(s) remaining
Completed 57.4 MiB/233.2 MiB (66.6 MiB/s) with 5 file(s) remaining
Completed 57.6 MiB/233.2 MiB (66.8 MiB/s) with 5 file(s) remaining
Completed 57.9 MiB/233.2 MiB (67.0 MiB/s) with 5 file(s) remaining
Completed 58.1 MiB/233.2 MiB (67.2 MiB/s) with 5 file(s) remaining
Completed 58.4 MiB/233.2 MiB (66.7 MiB/s) with 5 file(s) remaining
Completed 58.6 MiB/233.2 MiB (66.9 MiB/s) with 5 file(s) remaining
Completed 58.9 MiB/233.2 MiB (66.8 MiB/s) with 5 file(s) remaining
Completed 59.1 MiB/233.2 MiB (66.4 MiB/s) with 5 file(s) remaining
Completed 59.4 MiB/233.2 MiB (66.2 MiB/s) with 5 file(s) remaining
Completed 59.6 MiB/233.2 MiB (65.9 MiB/s) with 5 file(s) remaining
Completed 59.9 MiB/233.2 MiB (66.0 MiB/s) with 5 file(s) remaining
Completed 60.1 MiB/233.2 MiB (65.8 MiB/s) with 5 file(s) remaining
Completed 60.4 MiB/233.2 MiB (66.0 MiB/s) with 5 file(s) remaining
Completed 60.6 MiB/233.2 MiB (65.9 MiB/s) with 5 file(s) remaining
Completed 60.9 MiB/233.2 MiB (66.1 MiB/s) with 5 file(s) remaining
Completed 61.1 MiB/233.2 MiB (65.9 MiB/s) with 5 file(s) remaining
Completed 61.4 MiB/233.2 MiB (66.1 MiB/s) with 5 file(s) remaining
Completed 61.6 MiB/233.2 MiB (66.3 MiB/s) with 5 file(s) remaining
Completed 61.9 MiB/233.2 MiB (66.3 MiB/s) with 5 file(s) remaining
Completed 62.1 MiB/233.2 MiB (66.5 MiB/s) with 5 file(s) remaining
Completed 62.4 MiB/233.2 MiB (66.1 MiB/s) with 5 file(s) remaining
Completed 62.6 MiB/233.2 MiB (66.3 MiB/s) with 5 file(s) remaining
Completed 62.9 MiB/233.2 MiB (66.6 MiB/s) with 5 file(s) remaining
Completed 63.1 MiB/233.2 MiB (66.5 MiB/s) with 5 file(s) remaining
Completed 63.4 MiB/233.2 MiB (66.7 MiB/s) with 5 file(s) remaining
Completed 63.6 MiB/233.2 MiB (66.8 MiB/s) with 5 file(s) remaining
Completed 63.9 MiB/233.2 MiB (67.0 MiB/s) with 5 file(s) remaining
Completed 64.1 MiB/233.2 MiB (67.2 MiB/s) with 5 file(s) remaining
Completed 64.4 MiB/233.2 MiB (67.4 MiB/s) with 5 file(s) remaining
Completed 64.6 MiB/233.2 MiB (67.6 MiB/s) with 5 file(s) remaining
Completed 64.9 MiB/233.2 MiB (67.7 MiB/s) with 5 file(s) remaining
Completed 65.1 MiB/233.2 MiB (67.9 MiB/s) with 5 file(s) remaining
Completed 65.4 MiB/233.2 MiB (68.0 MiB/s) with 5 file(s) remaining
Completed 65.6 MiB/233.2 MiB (68.2 MiB/s) with 5 file(s) remaining
Completed 65.9 MiB/233.2 MiB (68.3 MiB/s) with 5 file(s) remaining
Completed 66.1 MiB/233.2 MiB (68.4 MiB/s) with 5 file(s) remaining
Completed 66.4 MiB/233.2 MiB (68.4 MiB/s) with 5 file(s) remaining
Completed 66.6 MiB/233.2 MiB (68.6 MiB/s) with 5 file(s) remaining
Completed 66.9 MiB/233.2 MiB (68.7 MiB/s) with 5 file(s) remaining
Completed 67.1 MiB/233.2 MiB (68.6 MiB/s) with 5 file(s) remaining
Completed 67.4 MiB/233.2 MiB (68.8 MiB/s) with 5 file(s) remaining
Completed 67.6 MiB/233.2 MiB (68.8 MiB/s) with 5 file(s) remaining
Completed 67.9 MiB/233.2 MiB (68.7 MiB/s) with 5 file(s) remaining
Completed 68.1 MiB/233.2 MiB (68.8 MiB/s) with 5 file(s) remaining
Completed 68.4 MiB/233.2 MiB (68.8 MiB/s) with 5 file(s) remaining
Completed 68.6 MiB/233.2 MiB (68.8 MiB/s) with 5 file(s) remaining
Completed 68.9 MiB/233.2 MiB (69.0 MiB/s) with 5 file(s) remaining
Completed 69.1 MiB/233.2 MiB (69.0 MiB/s) with 5 file(s) remaining
Completed 69.4 MiB/233.2 MiB (69.0 MiB/s) with 5 file(s) remaining
Completed 69.6 MiB/233.2 MiB (68.9 MiB/s) with 5 file(s) remaining
Completed 69.9 MiB/233.2 MiB (68.9 MiB/s) with 5 file(s) remaining
Completed 70.1 MiB/233.2 MiB (69.0 MiB/s) with 5 file(s) remaining
Completed 70.4 MiB/233.2 MiB (69.1 MiB/s) with 5 file(s) remaining
Completed 70.6 MiB/233.2 MiB (68.9 MiB/s) with 5 file(s) remaining
Completed 70.9 MiB/233.2 MiB (69.0 MiB/s) with 5 file(s) remaining
Completed 71.1 MiB/233.2 MiB (69.0 MiB/s) with 5 file(s) remaining
Completed 71.4 MiB/233.2 MiB (69.2 MiB/s) with 5 file(s) remaining
Completed 71.6 MiB/233.2 MiB (69.3 MiB/s) with 5 file(s) remaining
Completed 71.9 MiB/233.2 MiB (69.5 MiB/s) with 5 file(s) remaining
Completed 72.1 MiB/233.2 MiB (69.7 MiB/s) with 5 file(s) remaining
Completed 72.4 MiB/233.2 MiB (69.6 MiB/s) with 5 file(s) remaining
Completed 72.6 MiB/233.2 MiB (69.8 MiB/s) with 5 file(s) remaining
Completed 72.9 MiB/233.2 MiB (69.0 MiB/s) with 5 file(s) remaining
upload: ../../../data/datafile-11-MB to s3://awscli-mint-test-bucket-20632/datafile-11-MBCompleted 72.9 MiB/233.2 MiB (69.0 MiB/s) with 4 file(s) remaining
Completed 73.1 MiB/233.2 MiB (68.5 MiB/s) with 4 file(s) remaining
Completed 73.4 MiB/233.2 MiB (68.6 MiB/s) with 4 file(s) remaining
Completed 73.6 MiB/233.2 MiB (68.8 MiB/s) with 4 file(s) remaining
Completed 73.9 MiB/233.2 MiB (69.0 MiB/s) with 4 file(s) remaining
Completed 74.1 MiB/233.2 MiB (69.2 MiB/s) with 4 file(s) remaining
Completed 74.4 MiB/233.2 MiB (69.3 MiB/s) with 4 file(s) remaining
Completed 74.6 MiB/233.2 MiB (68.9 MiB/s) with 4 file(s) remaining
Completed 74.9 MiB/233.2 MiB (68.9 MiB/s) with 4 file(s) remaining
Completed 75.1 MiB/233.2 MiB (68.6 MiB/s) with 4 file(s) remaining
Completed 75.4 MiB/233.2 MiB (68.1 MiB/s) with 4 file(s) remaining
Completed 75.6 MiB/233.2 MiB (68.3 MiB/s) with 4 file(s) remaining
Completed 75.9 MiB/233.2 MiB (68.5 MiB/s) with 4 file(s) remaining
Completed 76.1 MiB/233.2 MiB (68.7 MiB/s) with 4 file(s) remaining
Completed 76.4 MiB/233.2 MiB (68.8 MiB/s) with 4 file(s) remaining
Completed 76.6 MiB/233.2 MiB (69.0 MiB/s) with 4 file(s) remaining
Completed 76.9 MiB/233.2 MiB (68.7 MiB/s) with 4 file(s) remaining
Completed 77.1 MiB/233.2 MiB (68.9 MiB/s) with 4 file(s) remaining
Completed 77.4 MiB/233.2 MiB (68.8 MiB/s) with 4 file(s) remaining
Completed 77.6 MiB/233.2 MiB (68.8 MiB/s) with 4 file(s) remaining
Completed 77.9 MiB/233.2 MiB (68.6 MiB/s) with 4 file(s) remaining
Completed 78.1 MiB/233.2 MiB (68.6 MiB/s) with 4 file(s) remaining
Completed 78.4 MiB/233.2 MiB (68.6 MiB/s) with 4 file(s) remaining
Completed 78.6 MiB/233.2 MiB (68.6 MiB/s) with 4 file(s) remaining
Completed 78.9 MiB/233.2 MiB (68.5 MiB/s) with 4 file(s) remaining
Completed 79.1 MiB/233.2 MiB (68.1 MiB/s) with 4 file(s) remaining
Completed 79.4 MiB/233.2 MiB (68.3 MiB/s) with 4 file(s) remaining
Completed 79.6 MiB/233.2 MiB (68.4 MiB/s) with 4 file(s) remaining
Completed 79.9 MiB/233.2 MiB (68.2 MiB/s) with 4 file(s) remaining
Completed 80.1 MiB/233.2 MiB (68.3 MiB/s) with 4 file(s) remaining
Completed 80.4 MiB/233.2 MiB (68.4 MiB/s) with 4 file(s) remaining
Completed 80.6 MiB/233.2 MiB (68.2 MiB/s) with 4 file(s) remaining
Completed 80.9 MiB/233.2 MiB (68.3 MiB/s) with 4 file(s) remaining
Completed 81.1 MiB/233.2 MiB (68.2 MiB/s) with 4 file(s) remaining
Completed 81.4 MiB/233.2 MiB (68.4 MiB/s) with 4 file(s) remaining
Completed 81.6 MiB/233.2 MiB (68.5 MiB/s) with 4 file(s) remaining
Completed 81.9 MiB/233.2 MiB (68.7 MiB/s) with 4 file(s) remaining
Completed 82.1 MiB/233.2 MiB (68.9 MiB/s) with 4 file(s) remaining
Completed 82.4 MiB/233.2 MiB (69.0 MiB/s) with 4 file(s) remaining
Completed 82.6 MiB/233.2 MiB (69.1 MiB/s) with 4 file(s) remaining
Completed 82.9 MiB/233.2 MiB (69.3 MiB/s) with 4 file(s) remaining
Completed 83.1 MiB/233.2 MiB (69.4 MiB/s) with 4 file(s) remaining
Completed 83.4 MiB/233.2 MiB (69.1 MiB/s) with 4 file(s) remaining
Completed 83.6 MiB/233.2 MiB (68.8 MiB/s) with 4 file(s) remaining
Completed 83.9 MiB/233.2 MiB (69.0 MiB/s) with 4 file(s) remaining
Completed 84.1 MiB/233.2 MiB (69.2 MiB/s) with 4 file(s) remaining
Completed 84.4 MiB/233.2 MiB (69.1 MiB/s) with 4 file(s) remaining
Completed 84.6 MiB/233.2 MiB (69.3 MiB/s) with 4 file(s) remaining
Completed 84.9 MiB/233.2 MiB (69.1 MiB/s) with 4 file(s) remaining
Completed 85.1 MiB/233.2 MiB (69.1 MiB/s) with 4 file(s) remaining
Completed 85.4 MiB/233.2 MiB (69.1 MiB/s) with 4 file(s) remaining
Completed 85.6 MiB/233.2 MiB (69.3 MiB/s) with 4 file(s) remaining
Completed 85.9 MiB/233.2 MiB (69.1 MiB/s) with 4 file(s) remaining
Completed 86.1 MiB/233.2 MiB (69.1 MiB/s) with 4 file(s) remaining
Completed 86.4 MiB/233.2 MiB (68.9 MiB/s) with 4 file(s) remaining
Completed 86.6 MiB/233.2 MiB (68.7 MiB/s) with 4 file(s) remaining
Completed 86.9 MiB/233.2 MiB (68.9 MiB/s) with 4 file(s) remaining
Completed 87.1 MiB/233.2 MiB (69.0 MiB/s) with 4 file(s) remaining
Completed 87.4 MiB/233.2 MiB (68.6 MiB/s) with 4 file(s) remaining
Completed 87.6 MiB/233.2 MiB (68.3 MiB/s) with 4 file(s) remaining
Completed 87.9 MiB/233.2 MiB (68.4 MiB/s) with 4 file(s) remaining
Completed 88.1 MiB/233.2 MiB (68.4 MiB/s) with 4 file(s) remaining
Completed 88.4 MiB/233.2 MiB (68.4 MiB/s) with 4 file(s) remaining
Completed 88.6 MiB/233.2 MiB (68.2 MiB/s) with 4 file(s) remaining
Completed 88.9 MiB/233.2 MiB (68.3 MiB/s) with 4 file(s) remaining
Completed 89.1 MiB/233.2 MiB (68.4 MiB/s) with 4 file(s) remaining
Completed 89.4 MiB/233.2 MiB (68.2 MiB/s) with 4 file(s) remaining
Completed 89.6 MiB/233.2 MiB (68.2 MiB/s) with 4 file(s) remaining
upload failed: ../../../data/datafile-10-MB to s3://awscli-mint-test-bucket-20632/datafile-10-MB An error occurred (InvalidPart) when calling the CompleteMultipartUpload operation: One or more of the specified parts could not be found.  The part may not have been uploaded, or the specified entity tag may not match the part's entity tag.Completed 89.6 MiB/233.2 MiB (68.2 MiB/s) with 3 file(s) remaining
Completed 89.9 MiB/233.2 MiB (68.1 MiB/s) with 3 file(s) remaining
Completed 90.1 MiB/233.2 MiB (67.7 MiB/s) with 3 file(s) remaining
Completed 90.4 MiB/233.2 MiB (67.9 MiB/s) with 3 file(s) remaining
Completed 90.6 MiB/233.2 MiB (68.0 MiB/s) with 3 file(s) remaining
Completed 90.9 MiB/233.2 MiB (67.9 MiB/s) with 3 file(s) remaining
Completed 91.1 MiB/233.2 MiB (67.6 MiB/s) with 3 file(s) remaining
Completed 91.4 MiB/233.2 MiB (67.7 MiB/s) with 3 file(s) remaining
Completed 91.6 MiB/233.2 MiB (67.8 MiB/s) with 3 file(s) remaining
Completed 91.9 MiB/233.2 MiB (67.9 MiB/s) with 3 file(s) remaining
Completed 92.1 MiB/233.2 MiB (68.0 MiB/s) with 3 file(s) remaining
Completed 92.4 MiB/233.2 MiB (68.2 MiB/s) with 3 file(s) remaining
Completed 92.6 MiB/233.2 MiB (68.3 MiB/s) with 3 file(s) remaining
Completed 92.9 MiB/233.2 MiB (68.3 MiB/s) with 3 file(s) remaining
Completed 93.1 MiB/233.2 MiB (68.4 MiB/s) with 3 file(s) remaining
Completed 93.4 MiB/233.2 MiB (68.5 MiB/s) with 3 file(s) remaining
Completed 93.6 MiB/233.2 MiB (68.7 MiB/s) with 3 file(s) remaining
Completed 93.9 MiB/233.2 MiB (68.8 MiB/s) with 3 file(s) remaining
Completed 94.1 MiB/233.2 MiB (68.9 MiB/s) with 3 file(s) remaining
Completed 94.4 MiB/233.2 MiB (69.1 MiB/s) with 3 file(s) remaining
Completed 94.6 MiB/233.2 MiB (69.1 MiB/s) with 3 file(s) remaining
Completed 94.9 MiB/233.2 MiB (69.2 MiB/s) with 3 file(s) remaining
Completed 95.1 MiB/233.2 MiB (68.8 MiB/s) with 3 file(s) remaining
Completed 95.4 MiB/233.2 MiB (68.9 MiB/s) with 3 file(s) remaining
Completed 95.6 MiB/233.2 MiB (69.1 MiB/s) with 3 file(s) remaining
Completed 95.9 MiB/233.2 MiB (69.1 MiB/s) with 3 file(s) remaining
Completed 96.1 MiB/233.2 MiB (69.1 MiB/s) with 3 file(s) remaining
Completed 96.4 MiB/233.2 MiB (69.1 MiB/s) with 3 file(s) remaining
Completed 96.6 MiB/233.2 MiB (69.1 MiB/s) with 3 file(s) remaining
Completed 96.9 MiB/233.2 MiB (69.1 MiB/s) with 3 file(s) remaining
Completed 97.1 MiB/233.2 MiB (69.0 MiB/s) with 3 file(s) remaining
Completed 97.4 MiB/233.2 MiB (68.9 MiB/s) with 3 file(s) remaining
Completed 97.6 MiB/233.2 MiB (68.6 MiB/s) with 3 file(s) remaining
Completed 97.9 MiB/233.2 MiB (68.8 MiB/s) with 3 file(s) remaining
Completed 98.1 MiB/233.2 MiB (68.9 MiB/s) with 3 file(s) remaining
Completed 98.4 MiB/233.2 MiB (69.1 MiB/s) with 3 file(s) remaining
Completed 98.6 MiB/233.2 MiB (69.0 MiB/s) with 3 file(s) remaining
Completed 98.9 MiB/233.2 MiB (68.9 MiB/s) with 3 file(s) remaining
Completed 99.1 MiB/233.2 MiB (68.8 MiB/s) with 3 file(s) remaining
Completed 99.4 MiB/233.2 MiB (68.9 MiB/s) with 3 file(s) remaining
Completed 99.6 MiB/233.2 MiB (69.0 MiB/s) with 3 file(s) remaining
Completed 99.9 MiB/233.2 MiB (68.6 MiB/s) with 3 file(s) remaining
Completed 100.1 MiB/233.2 MiB (68.6 MiB/s) with 3 file(s) remaining
Completed 100.4 MiB/233.2 MiB (68.7 MiB/s) with 3 file(s) remaining
Completed 100.6 MiB/233.2 MiB (68.7 MiB/s) with 3 file(s) remaining
Completed 100.9 MiB/233.2 MiB (68.4 MiB/s) with 3 file(s) remaining
Completed 101.1 MiB/233.2 MiB (68.5 MiB/s) with 3 file(s) remaining
Completed 101.4 MiB/233.2 MiB (68.2 MiB/s) with 3 file(s) remaining
Completed 101.6 MiB/233.2 MiB (68.4 MiB/s) with 3 file(s) remaining
Completed 101.9 MiB/233.2 MiB (68.4 MiB/s) with 3 file(s) remaining
Completed 102.1 MiB/233.2 MiB (68.5 MiB/s) with 3 file(s) remaining
Completed 102.4 MiB/233.2 MiB (68.1 MiB/s) with 3 file(s) remaining
Completed 102.6 MiB/233.2 MiB (68.1 MiB/s) with 3 file(s) remaining
Completed 102.9 MiB/233.2 MiB (68.2 MiB/s) with 3 file(s) remaining
Completed 103.1 MiB/233.2 MiB (68.3 MiB/s) with 3 file(s) remaining
Completed 103.4 MiB/233.2 MiB (68.4 MiB/s) with 3 file(s) remaining
Completed 103.6 MiB/233.2 MiB (68.1 MiB/s) with 3 file(s) remaining
Completed 103.9 MiB/233.2 MiB (68.3 MiB/s) with 3 file(s) remaining
Completed 104.1 MiB/233.2 MiB (68.3 MiB/s) with 3 file(s) remaining
Completed 104.4 MiB/233.2 MiB (68.0 MiB/s) with 3 file(s) remaining
Completed 104.6 MiB/233.2 MiB (68.0 MiB/s) with 3 file(s) remaining
Completed 104.9 MiB/233.2 MiB (68.2 MiB/s) with 3 file(s) remaining
Completed 105.1 MiB/233.2 MiB (68.2 MiB/s) with 3 file(s) remaining
Completed 105.4 MiB/233.2 MiB (68.2 MiB/s) with 3 file(s) remaining
Completed 105.6 MiB/233.2 MiB (67.9 MiB/s) with 3 file(s) remaining
Completed 105.9 MiB/233.2 MiB (68.1 MiB/s) with 3 file(s) remaining
Completed 106.1 MiB/233.2 MiB (68.2 MiB/s) with 3 file(s) remaining
Completed 106.4 MiB/233.2 MiB (68.2 MiB/s) with 3 file(s) remaining
Completed 106.6 MiB/233.2 MiB (67.9 MiB/s) with 3 file(s) remaining
Completed 106.9 MiB/233.2 MiB (67.9 MiB/s) with 3 file(s) remaining
Completed 107.1 MiB/233.2 MiB (68.0 MiB/s) with 3 file(s) remaining
Completed 107.4 MiB/233.2 MiB (67.9 MiB/s) with 3 file(s) remaining
Completed 107.6 MiB/233.2 MiB (68.0 MiB/s) with 3 file(s) remaining
Completed 107.9 MiB/233.2 MiB (67.8 MiB/s) with 3 file(s) remaining
Completed 108.1 MiB/233.2 MiB (67.9 MiB/s) with 3 file(s) remaining
Completed 108.4 MiB/233.2 MiB (67.6 MiB/s) with 3 file(s) remaining
Completed 108.6 MiB/233.2 MiB (67.3 MiB/s) with 3 file(s) remaining
Completed 108.9 MiB/233.2 MiB (67.4 MiB/s) with 3 file(s) remaining
Completed 109.1 MiB/233.2 MiB (67.2 MiB/s) with 3 file(s) remaining
Completed 109.4 MiB/233.2 MiB (66.9 MiB/s) with 3 file(s) remaining
Completed 109.6 MiB/233.2 MiB (67.0 MiB/s) with 3 file(s) remaining
Completed 109.9 MiB/233.2 MiB (66.5 MiB/s) with 3 file(s) remaining
Completed 110.1 MiB/233.2 MiB (66.6 MiB/s) with 3 file(s) remaining
Completed 110.4 MiB/233.2 MiB (66.4 MiB/s) with 3 file(s) remaining
Completed 110.6 MiB/233.2 MiB (66.3 MiB/s) with 3 file(s) remaining
Completed 110.9 MiB/233.2 MiB (66.4 MiB/s) with 3 file(s) remaining
Completed 111.1 MiB/233.2 MiB (66.1 MiB/s) with 3 file(s) remaining
Completed 111.4 MiB/233.2 MiB (66.1 MiB/s) with 3 file(s) remaining
Completed 111.6 MiB/233.2 MiB (66.0 MiB/s) with 3 file(s) remaining
Completed 111.9 MiB/233.2 MiB (66.0 MiB/s) with 3 file(s) remaining
Completed 112.1 MiB/233.2 MiB (65.9 MiB/s) with 3 file(s) remaining
Completed 112.4 MiB/233.2 MiB (65.7 MiB/s) with 3 file(s) remaining
Completed 112.6 MiB/233.2 MiB (65.8 MiB/s) with 3 file(s) remaining
Completed 112.9 MiB/233.2 MiB (65.5 MiB/s) with 3 file(s) remaining
Completed 113.1 MiB/233.2 MiB (65.6 MiB/s) with 3 file(s) remaining
Completed 113.4 MiB/233.2 MiB (65.5 MiB/s) with 3 file(s) remaining
Completed 113.6 MiB/233.2 MiB (65.4 MiB/s) with 3 file(s) remaining
Completed 113.9 MiB/233.2 MiB (65.3 MiB/s) with 3 file(s) remaining
Completed 114.1 MiB/233.2 MiB (65.2 MiB/s) with 3 file(s) remaining
Completed 114.4 MiB/233.2 MiB (65.1 MiB/s) with 3 file(s) remaining
Completed 114.6 MiB/233.2 MiB (65.2 MiB/s) with 3 file(s) remaining
Completed 114.9 MiB/233.2 MiB (65.0 MiB/s) with 3 file(s) remaining
Completed 115.1 MiB/233.2 MiB (64.7 MiB/s) with 3 file(s) remaining
Completed 115.4 MiB/233.2 MiB (64.8 MiB/s) with 3 file(s) remaining
Completed 115.6 MiB/233.2 MiB (64.4 MiB/s) with 3 file(s) remaining
Completed 115.9 MiB/233.2 MiB (64.5 MiB/s) with 3 file(s) remaining
Completed 116.1 MiB/233.2 MiB (64.2 MiB/s) with 3 file(s) remaining
Completed 116.4 MiB/233.2 MiB (63.9 MiB/s) with 3 file(s) remaining
Completed 116.6 MiB/233.2 MiB (64.0 MiB/s) with 3 file(s) remaining
Completed 116.9 MiB/233.2 MiB (64.1 MiB/s) with 3 file(s) remaining
Completed 117.1 MiB/233.2 MiB (63.4 MiB/s) with 3 file(s) remaining
Completed 117.4 MiB/233.2 MiB (63.2 MiB/s) with 3 file(s) remaining
Completed 117.6 MiB/233.2 MiB (62.9 MiB/s) with 3 file(s) remaining
Completed 117.9 MiB/233.2 MiB (62.2 MiB/s) with 3 file(s) remaining
Completed 118.1 MiB/233.2 MiB (61.5 MiB/s) with 3 file(s) remaining
Completed 118.4 MiB/233.2 MiB (60.9 MiB/s) with 3 file(s) remaining
Completed 118.6 MiB/233.2 MiB (60.2 MiB/s) with 3 file(s) remaining
Completed 118.9 MiB/233.2 MiB (59.6 MiB/s) with 3 file(s) remaining
Completed 119.1 MiB/233.2 MiB (59.5 MiB/s) with 3 file(s) remaining
Completed 119.4 MiB/233.2 MiB (59.6 MiB/s) with 3 file(s) remaining
Completed 119.6 MiB/233.2 MiB (59.5 MiB/s) with 3 file(s) remaining
Completed 119.9 MiB/233.2 MiB (59.1 MiB/s) with 3 file(s) remaining
Completed 120.1 MiB/233.2 MiB (58.8 MiB/s) with 3 file(s) remaining
Completed 120.4 MiB/233.2 MiB (58.0 MiB/s) with 3 file(s) remaining
Completed 120.6 MiB/233.2 MiB (57.8 MiB/s) with 3 file(s) remaining
Completed 120.9 MiB/233.2 MiB (57.7 MiB/s) with 3 file(s) remaining
Completed 121.1 MiB/233.2 MiB (57.5 MiB/s) with 3 file(s) remaining
Completed 121.4 MiB/233.2 MiB (57.4 MiB/s) with 3 file(s) remaining
Completed 121.6 MiB/233.2 MiB (57.2 MiB/s) with 3 file(s) remaining
Completed 121.9 MiB/233.2 MiB (57.1 MiB/s) with 3 file(s) remaining
Completed 122.1 MiB/233.2 MiB (57.0 MiB/s) with 3 file(s) remaining
Completed 122.4 MiB/233.2 MiB (56.9 MiB/s) with 3 file(s) remaining
Completed 122.6 MiB/233.2 MiB (56.9 MiB/s) with 3 file(s) remaining
Completed 122.9 MiB/233.2 MiB (56.8 MiB/s) with 3 file(s) remaining
Completed 123.1 MiB/233.2 MiB (56.9 MiB/s) with 3 file(s) remaining
Completed 123.4 MiB/233.2 MiB (56.9 MiB/s) with 3 file(s) remaining
Completed 123.6 MiB/233.2 MiB (56.9 MiB/s) with 3 file(s) remaining
Completed 123.9 MiB/233.2 MiB (56.8 MiB/s) with 3 file(s) remaining
Completed 124.1 MiB/233.2 MiB (56.8 MiB/s) with 3 file(s) remaining
Completed 124.4 MiB/233.2 MiB (56.8 MiB/s) with 3 file(s) remaining
Completed 124.6 MiB/233.2 MiB (56.7 MiB/s) with 3 file(s) remaining
Completed 124.9 MiB/233.2 MiB (56.7 MiB/s) with 3 file(s) remaining
Completed 125.1 MiB/233.2 MiB (56.7 MiB/s) with 3 file(s) remaining
Completed 125.4 MiB/233.2 MiB (56.7 MiB/s) with 3 file(s) remaining
Completed 125.6 MiB/233.2 MiB (56.7 MiB/s) with 3 file(s) remaining
Completed 125.9 MiB/233.2 MiB (56.6 MiB/s) with 3 file(s) remaining
Completed 126.1 MiB/233.2 MiB (56.6 MiB/s) with 3 file(s) remaining
Completed 126.4 MiB/233.2 MiB (56.6 MiB/s) with 3 file(s) remaining
Completed 126.6 MiB/233.2 MiB (56.6 MiB/s) with 3 file(s) remaining
Completed 126.9 MiB/233.2 MiB (56.5 MiB/s) with 3 file(s) remaining
Completed 127.1 MiB/233.2 MiB (56.5 MiB/s) with 3 file(s) remaining
Completed 127.4 MiB/233.2 MiB (54.0 MiB/s) with 3 file(s) remaining
Completed 127.6 MiB/233.2 MiB (54.1 MiB/s) with 3 file(s) remaining
Completed 127.9 MiB/233.2 MiB (54.2 MiB/s) with 3 file(s) remaining
Completed 128.1 MiB/233.2 MiB (54.3 MiB/s) with 3 file(s) remaining
Completed 128.4 MiB/233.2 MiB (54.4 MiB/s) with 3 file(s) remaining
Completed 128.6 MiB/233.2 MiB (54.4 MiB/s) with 3 file(s) remaining
Completed 128.9 MiB/233.2 MiB (54.5 MiB/s) with 3 file(s) remaining
Completed 129.1 MiB/233.2 MiB (54.6 MiB/s) with 3 file(s) remaining
Completed 129.4 MiB/233.2 MiB (54.6 MiB/s) with 3 file(s) remaining
Completed 129.6 MiB/233.2 MiB (54.6 MiB/s) with 3 file(s) remaining
Completed 129.9 MiB/233.2 MiB (54.6 MiB/s) with 3 file(s) remaining
Completed 130.1 MiB/233.2 MiB (54.7 MiB/s) with 3 file(s) remaining
Completed 130.4 MiB/233.2 MiB (54.7 MiB/s) with 3 file(s) remaining
Completed 130.6 MiB/233.2 MiB (54.7 MiB/s) with 3 file(s) remaining
Completed 130.9 MiB/233.2 MiB (54.8 MiB/s) with 3 file(s) remaining
Completed 131.1 MiB/233.2 MiB (54.8 MiB/s) with 3 file(s) remaining
Completed 131.4 MiB/233.2 MiB (54.8 MiB/s) with 3 file(s) remaining
Completed 131.6 MiB/233.2 MiB (54.9 MiB/s) with 3 file(s) remaining
Completed 131.9 MiB/233.2 MiB (54.9 MiB/s) with 3 file(s) remaining
Completed 132.1 MiB/233.2 MiB (54.9 MiB/s) with 3 file(s) remaining
Completed 132.4 MiB/233.2 MiB (55.0 MiB/s) with 3 file(s) remaining
Completed 132.6 MiB/233.2 MiB (55.0 MiB/s) with 3 file(s) remaining
Completed 132.9 MiB/233.2 MiB (55.0 MiB/s) with 3 file(s) remaining
Completed 133.1 MiB/233.2 MiB (55.1 MiB/s) with 3 file(s) remaining
Completed 133.4 MiB/233.2 MiB (55.1 MiB/s) with 3 file(s) remaining
Completed 133.6 MiB/233.2 MiB (55.1 MiB/s) with 3 file(s) remaining
Completed 133.9 MiB/233.2 MiB (55.2 MiB/s) with 3 file(s) remaining
Completed 134.1 MiB/233.2 MiB (55.2 MiB/s) with 3 file(s) remaining
Completed 134.4 MiB/233.2 MiB (55.2 MiB/s) with 3 file(s) remaining
Completed 134.6 MiB/233.2 MiB (55.3 MiB/s) with 3 file(s) remaining
Completed 134.9 MiB/233.2 MiB (55.3 MiB/s) with 3 file(s) remaining
Completed 135.1 MiB/233.2 MiB (55.4 MiB/s) with 3 file(s) remaining
Completed 135.4 MiB/233.2 MiB (54.7 MiB/s) with 3 file(s) remaining
Completed 135.6 MiB/233.2 MiB (54.7 MiB/s) with 3 file(s) remaining
Completed 135.9 MiB/233.2 MiB (54.8 MiB/s) with 3 file(s) remaining
Completed 136.1 MiB/233.2 MiB (54.9 MiB/s) with 3 file(s) remaining
Completed 136.4 MiB/233.2 MiB (55.0 MiB/s) with 3 file(s) remaining
Completed 136.6 MiB/233.2 MiB (55.1 MiB/s) with 3 file(s) remaining
Completed 136.9 MiB/233.2 MiB (55.0 MiB/s) with 3 file(s) remaining
Completed 137.1 MiB/233.2 MiB (55.1 MiB/s) with 3 file(s) remaining
Completed 137.4 MiB/233.2 MiB (55.2 MiB/s) with 3 file(s) remaining
Completed 137.6 MiB/233.2 MiB (55.3 MiB/s) with 3 file(s) remaining
Completed 137.9 MiB/233.2 MiB (55.4 MiB/s) with 3 file(s) remaining
Completed 138.1 MiB/233.2 MiB (54.8 MiB/s) with 3 file(s) remaining
Completed 138.4 MiB/233.2 MiB (54.6 MiB/s) with 3 file(s) remaining
Completed 138.6 MiB/233.2 MiB (54.7 MiB/s) with 3 file(s) remaining
Completed 138.9 MiB/233.2 MiB (54.7 MiB/s) with 3 file(s) remaining
Completed 139.1 MiB/233.2 MiB (54.5 MiB/s) with 3 file(s) remaining
Completed 139.4 MiB/233.2 MiB (54.4 MiB/s) with 3 file(s) remaining
Completed 139.6 MiB/233.2 MiB (54.5 MiB/s) with 3 file(s) remaining
Completed 139.9 MiB/233.2 MiB (54.4 MiB/s) with 3 file(s) remaining
Completed 140.1 MiB/233.2 MiB (54.5 MiB/s) with 3 file(s) remaining
Completed 140.4 MiB/233.2 MiB (54.5 MiB/s) with 3 file(s) remaining
Completed 140.6 MiB/233.2 MiB (54.6 MiB/s) with 3 file(s) remaining
Completed 140.9 MiB/233.2 MiB (54.6 MiB/s) with 3 file(s) remaining
Completed 141.1 MiB/233.2 MiB (54.5 MiB/s) with 3 file(s) remaining
Completed 141.4 MiB/233.2 MiB (54.6 MiB/s) with 3 file(s) remaining
Completed 141.6 MiB/233.2 MiB (54.6 MiB/s) with 3 file(s) remaining
Completed 141.9 MiB/233.2 MiB (54.5 MiB/s) with 3 file(s) remaining
Completed 142.1 MiB/233.2 MiB (54.6 MiB/s) with 3 file(s) remaining
Completed 142.4 MiB/233.2 MiB (54.7 MiB/s) with 3 file(s) remaining
Completed 142.6 MiB/233.2 MiB (54.6 MiB/s) with 3 file(s) remaining
Completed 142.9 MiB/233.2 MiB (54.7 MiB/s) with 3 file(s) remaining
Completed 143.1 MiB/233.2 MiB (54.8 MiB/s) with 3 file(s) remaining
Completed 143.4 MiB/233.2 MiB (54.8 MiB/s) with 3 file(s) remaining
Completed 143.6 MiB/233.2 MiB (54.8 MiB/s) with 3 file(s) remaining
Completed 143.9 MiB/233.2 MiB (54.8 MiB/s) with 3 file(s) remaining
Completed 144.1 MiB/233.2 MiB (54.9 MiB/s) with 3 file(s) remaining
Completed 144.4 MiB/233.2 MiB (54.9 MiB/s) with 3 file(s) remaining
Completed 144.6 MiB/233.2 MiB (54.9 MiB/s) with 3 file(s) remaining
Completed 144.9 MiB/233.2 MiB (55.0 MiB/s) with 3 file(s) remaining
Completed 145.1 MiB/233.2 MiB (55.0 MiB/s) with 3 file(s) remaining
Completed 145.4 MiB/233.2 MiB (55.0 MiB/s) with 3 file(s) remaining
Completed 145.6 MiB/233.2 MiB (55.0 MiB/s) with 3 file(s) remaining
Completed 145.9 MiB/233.2 MiB (55.1 MiB/s) with 3 file(s) remaining
Completed 146.1 MiB/233.2 MiB (55.1 MiB/s) with 3 file(s) remaining
Completed 146.4 MiB/233.2 MiB (55.2 MiB/s) with 3 file(s) remaining
Completed 146.6 MiB/233.2 MiB (55.2 MiB/s) with 3 file(s) remaining
Completed 146.9 MiB/233.2 MiB (55.3 MiB/s) with 3 file(s) remaining
Completed 147.1 MiB/233.2 MiB (55.3 MiB/s) with 3 file(s) remaining
Completed 147.4 MiB/233.2 MiB (55.3 MiB/s) with 3 file(s) remaining
Completed 147.6 MiB/233.2 MiB (55.4 MiB/s) with 3 file(s) remaining
Completed 147.9 MiB/233.2 MiB (55.4 MiB/s) with 3 file(s) remaining
Completed 148.1 MiB/233.2 MiB (55.4 MiB/s) with 3 file(s) remaining
Completed 148.4 MiB/233.2 MiB (55.5 MiB/s) with 3 file(s) remaining
Completed 148.6 MiB/233.2 MiB (55.5 MiB/s) with 3 file(s) remaining
Completed 148.9 MiB/233.2 MiB (55.5 MiB/s) with 3 file(s) remaining
Completed 149.1 MiB/233.2 MiB (55.6 MiB/s) with 3 file(s) remaining
Completed 149.4 MiB/233.2 MiB (55.6 MiB/s) with 3 file(s) remaining
Completed 149.6 MiB/233.2 MiB (55.6 MiB/s) with 3 file(s) remaining
Completed 149.9 MiB/233.2 MiB (55.7 MiB/s) with 3 file(s) remaining
Completed 150.1 MiB/233.2 MiB (55.7 MiB/s) with 3 file(s) remaining
Completed 150.4 MiB/233.2 MiB (55.7 MiB/s) with 3 file(s) remaining
Completed 150.6 MiB/233.2 MiB (55.8 MiB/s) with 3 file(s) remaining
Completed 150.9 MiB/233.2 MiB (55.8 MiB/s) with 3 file(s) remaining
Completed 151.1 MiB/233.2 MiB (55.8 MiB/s) with 3 file(s) remaining
Completed 151.4 MiB/233.2 MiB (55.9 MiB/s) with 3 file(s) remaining
Completed 151.6 MiB/233.2 MiB (55.9 MiB/s) with 3 file(s) remaining
Completed 151.9 MiB/233.2 MiB (55.9 MiB/s) with 3 file(s) remaining
Completed 152.1 MiB/233.2 MiB (56.0 MiB/s) with 3 file(s) remaining
Completed 152.4 MiB/233.2 MiB (56.0 MiB/s) with 3 file(s) remaining
Completed 152.6 MiB/233.2 MiB (56.0 MiB/s) with 3 file(s) remaining
Completed 152.9 MiB/233.2 MiB (56.1 MiB/s) with 3 file(s) remaining
Completed 153.1 MiB/233.2 MiB (56.1 MiB/s) with 3 file(s) remaining
Completed 153.4 MiB/233.2 MiB (56.1 MiB/s) with 3 file(s) remaining
Completed 153.6 MiB/233.2 MiB (56.1 MiB/s) with 3 file(s) remaining
Completed 153.9 MiB/233.2 MiB (56.1 MiB/s) with 3 file(s) remaining
Completed 154.1 MiB/233.2 MiB (56.2 MiB/s) with 3 file(s) remaining
Completed 154.4 MiB/233.2 MiB (56.2 MiB/s) with 3 file(s) remaining
Completed 154.6 MiB/233.2 MiB (56.2 MiB/s) with 3 file(s) remaining
Completed 154.9 MiB/233.2 MiB (56.3 MiB/s) with 3 file(s) remaining
Completed 155.1 MiB/233.2 MiB (56.3 MiB/s) with 3 file(s) remaining
Completed 155.4 MiB/233.2 MiB (56.3 MiB/s) with 3 file(s) remaining
Completed 155.6 MiB/233.2 MiB (56.4 MiB/s) with 3 file(s) remaining
Completed 155.9 MiB/233.2 MiB (56.4 MiB/s) with 3 file(s) remaining
Completed 156.1 MiB/233.2 MiB (56.4 MiB/s) with 3 file(s) remaining
Completed 156.4 MiB/233.2 MiB (56.5 MiB/s) with 3 file(s) remaining
Completed 156.6 MiB/233.2 MiB (56.5 MiB/s) with 3 file(s) remaining
Completed 156.9 MiB/233.2 MiB (56.6 MiB/s) with 3 file(s) remaining
Completed 157.1 MiB/233.2 MiB (56.6 MiB/s) with 3 file(s) remaining
Completed 157.4 MiB/233.2 MiB (56.7 MiB/s) with 3 file(s) remaining
Completed 157.6 MiB/233.2 MiB (56.8 MiB/s) with 3 file(s) remaining
Completed 157.9 MiB/233.2 MiB (56.9 MiB/s) with 3 file(s) remaining
Completed 158.1 MiB/233.2 MiB (56.9 MiB/s) with 3 file(s) remaining
Completed 158.4 MiB/233.2 MiB (56.9 MiB/s) with 3 file(s) remaining
Completed 158.6 MiB/233.2 MiB (57.0 MiB/s) with 3 file(s) remaining
Completed 158.9 MiB/233.2 MiB (57.0 MiB/s) with 3 file(s) remaining
Completed 159.1 MiB/233.2 MiB (57.0 MiB/s) with 3 file(s) remaining
Completed 159.4 MiB/233.2 MiB (57.1 MiB/s) with 3 file(s) remaining
Completed 159.6 MiB/233.2 MiB (57.0 MiB/s) with 3 file(s) remaining
Completed 159.9 MiB/233.2 MiB (57.0 MiB/s) with 3 file(s) remaining
Completed 160.1 MiB/233.2 MiB (57.1 MiB/s) with 3 file(s) remaining
Completed 160.4 MiB/233.2 MiB (57.1 MiB/s) with 3 file(s) remaining
Completed 160.6 MiB/233.2 MiB (57.1 MiB/s) with 3 file(s) remaining
Completed 160.9 MiB/233.2 MiB (57.2 MiB/s) with 3 file(s) remaining
Completed 161.1 MiB/233.2 MiB (57.2 MiB/s) with 3 file(s) remaining
Completed 161.4 MiB/233.2 MiB (57.3 MiB/s) with 3 file(s) remaining
Completed 161.6 MiB/233.2 MiB (57.4 MiB/s) with 3 file(s) remaining
Completed 161.9 MiB/233.2 MiB (57.4 MiB/s) with 3 file(s) remaining
Completed 162.1 MiB/233.2 MiB (57.5 MiB/s) with 3 file(s) remaining
Completed 162.4 MiB/233.2 MiB (57.5 MiB/s) with 3 file(s) remaining
Completed 162.6 MiB/233.2 MiB (57.6 MiB/s) with 3 file(s) remaining
Completed 162.9 MiB/233.2 MiB (57.7 MiB/s) with 3 file(s) remaining
Completed 163.1 MiB/233.2 MiB (57.7 MiB/s) with 3 file(s) remaining
Completed 163.4 MiB/233.2 MiB (57.8 MiB/s) with 3 file(s) remaining
Completed 163.6 MiB/233.2 MiB (57.9 MiB/s) with 3 file(s) remaining
Completed 163.9 MiB/233.2 MiB (58.0 MiB/s) with 3 file(s) remaining
Completed 164.1 MiB/233.2 MiB (58.0 MiB/s) with 3 file(s) remaining
Completed 164.4 MiB/233.2 MiB (58.0 MiB/s) with 3 file(s) remaining
Completed 164.6 MiB/233.2 MiB (58.0 MiB/s) with 3 file(s) remaining
Completed 164.9 MiB/233.2 MiB (58.0 MiB/s) with 3 file(s) remaining
Completed 165.1 MiB/233.2 MiB (58.0 MiB/s) with 3 file(s) remaining
Completed 165.4 MiB/233.2 MiB (58.1 MiB/s) with 3 file(s) remaining
Completed 165.6 MiB/233.2 MiB (58.1 MiB/s) with 3 file(s) remaining
Completed 165.9 MiB/233.2 MiB (58.0 MiB/s) with 3 file(s) remaining
Completed 166.1 MiB/233.2 MiB (58.1 MiB/s) with 3 file(s) remaining
Completed 166.4 MiB/233.2 MiB (58.0 MiB/s) with 3 file(s) remaining
Completed 166.6 MiB/233.2 MiB (57.9 MiB/s) with 3 file(s) remaining
Completed 166.9 MiB/233.2 MiB (57.9 MiB/s) with 3 file(s) remaining
Completed 167.1 MiB/233.2 MiB (57.9 MiB/s) with 3 file(s) remaining
Completed 167.4 MiB/233.2 MiB (57.8 MiB/s) with 3 file(s) remaining
Completed 167.6 MiB/233.2 MiB (57.7 MiB/s) with 3 file(s) remaining
Completed 167.9 MiB/233.2 MiB (57.6 MiB/s) with 3 file(s) remaining
Completed 168.1 MiB/233.2 MiB (57.7 MiB/s) with 3 file(s) remaining
Completed 168.4 MiB/233.2 MiB (57.7 MiB/s) with 3 file(s) remaining
Completed 168.6 MiB/233.2 MiB (57.6 MiB/s) with 3 file(s) remaining
Completed 168.9 MiB/233.2 MiB (57.5 MiB/s) with 3 file(s) remaining
Completed 169.1 MiB/233.2 MiB (57.5 MiB/s) with 3 file(s) remaining
Completed 169.4 MiB/233.2 MiB (57.5 MiB/s) with 3 file(s) remaining
Completed 169.6 MiB/233.2 MiB (57.4 MiB/s) with 3 file(s) remaining
Completed 169.9 MiB/233.2 MiB (57.4 MiB/s) with 3 file(s) remaining
Completed 170.1 MiB/233.2 MiB (57.4 MiB/s) with 3 file(s) remaining
Completed 170.4 MiB/233.2 MiB (57.3 MiB/s) with 3 file(s) remaining
Completed 170.6 MiB/233.2 MiB (57.4 MiB/s) with 3 file(s) remaining
Completed 170.9 MiB/233.2 MiB (57.3 MiB/s) with 3 file(s) remaining
Completed 171.1 MiB/233.2 MiB (57.4 MiB/s) with 3 file(s) remaining
Completed 171.4 MiB/233.2 MiB (57.4 MiB/s) with 3 file(s) remaining
Completed 171.6 MiB/233.2 MiB (57.3 MiB/s) with 3 file(s) remaining
Completed 171.9 MiB/233.2 MiB (57.4 MiB/s) with 3 file(s) remaining
Completed 172.1 MiB/233.2 MiB (57.5 MiB/s) with 3 file(s) remaining
Completed 172.4 MiB/233.2 MiB (57.4 MiB/s) with 3 file(s) remaining
Completed 172.6 MiB/233.2 MiB (57.4 MiB/s) with 3 file(s) remaining
Completed 172.9 MiB/233.2 MiB (57.5 MiB/s) with 3 file(s) remaining
Completed 173.1 MiB/233.2 MiB (57.4 MiB/s) with 3 file(s) remaining
Completed 173.4 MiB/233.2 MiB (57.5 MiB/s) with 3 file(s) remaining
Completed 173.6 MiB/233.2 MiB (57.5 MiB/s) with 3 file(s) remaining
Completed 173.9 MiB/233.2 MiB (57.5 MiB/s) with 3 file(s) remaining
Completed 174.1 MiB/233.2 MiB (57.6 MiB/s) with 3 file(s) remaining
Completed 174.4 MiB/233.2 MiB (57.6 MiB/s) with 3 file(s) remaining
Completed 174.6 MiB/233.2 MiB (57.7 MiB/s) with 3 file(s) remaining
Completed 174.9 MiB/233.2 MiB (57.8 MiB/s) with 3 file(s) remaining
Completed 175.1 MiB/233.2 MiB (57.8 MiB/s) with 3 file(s) remaining
Completed 175.4 MiB/233.2 MiB (57.9 MiB/s) with 3 file(s) remaining
Completed 175.6 MiB/233.2 MiB (57.9 MiB/s) with 3 file(s) remaining
Completed 175.9 MiB/233.2 MiB (57.8 MiB/s) with 3 file(s) remaining
Completed 176.1 MiB/233.2 MiB (57.9 MiB/s) with 3 file(s) remaining
Completed 176.4 MiB/233.2 MiB (57.9 MiB/s) with 3 file(s) remaining
Completed 176.6 MiB/233.2 MiB (57.8 MiB/s) with 3 file(s) remaining
Completed 176.9 MiB/233.2 MiB (57.9 MiB/s) with 3 file(s) remaining
Completed 177.1 MiB/233.2 MiB (57.9 MiB/s) with 3 file(s) remaining
Completed 177.4 MiB/233.2 MiB (57.9 MiB/s) with 3 file(s) remaining
Completed 177.6 MiB/233.2 MiB (57.9 MiB/s) with 3 file(s) remaining
Completed 177.9 MiB/233.2 MiB (57.9 MiB/s) with 3 file(s) remaining
Completed 178.1 MiB/233.2 MiB (57.9 MiB/s) with 3 file(s) remaining
Completed 178.4 MiB/233.2 MiB (57.9 MiB/s) with 3 file(s) remaining
Completed 178.6 MiB/233.2 MiB (58.0 MiB/s) with 3 file(s) remaining
Completed 178.9 MiB/233.2 MiB (58.0 MiB/s) with 3 file(s) remaining
Completed 179.1 MiB/233.2 MiB (58.1 MiB/s) with 3 file(s) remaining
Completed 179.4 MiB/233.2 MiB (58.1 MiB/s) with 3 file(s) remaining
Completed 179.6 MiB/233.2 MiB (58.2 MiB/s) with 3 file(s) remaining
Completed 179.9 MiB/233.2 MiB (58.3 MiB/s) with 3 file(s) remaining
Completed 180.1 MiB/233.2 MiB (58.3 MiB/s) with 3 file(s) remaining
Completed 180.4 MiB/233.2 MiB (58.3 MiB/s) with 3 file(s) remaining
Completed 180.6 MiB/233.2 MiB (58.4 MiB/s) with 3 file(s) remaining
Completed 180.9 MiB/233.2 MiB (58.4 MiB/s) with 3 file(s) remaining
Completed 181.1 MiB/233.2 MiB (58.3 MiB/s) with 3 file(s) remaining
Completed 181.4 MiB/233.2 MiB (58.3 MiB/s) with 3 file(s) remaining
Completed 181.6 MiB/233.2 MiB (58.4 MiB/s) with 3 file(s) remaining
Completed 181.9 MiB/233.2 MiB (58.4 MiB/s) with 3 file(s) remaining
Completed 182.1 MiB/233.2 MiB (58.4 MiB/s) with 3 file(s) remaining
Completed 182.4 MiB/233.2 MiB (58.4 MiB/s) with 3 file(s) remaining
Completed 182.6 MiB/233.2 MiB (58.5 MiB/s) with 3 file(s) remaining
Completed 182.9 MiB/233.2 MiB (58.5 MiB/s) with 3 file(s) remaining
Completed 183.1 MiB/233.2 MiB (58.4 MiB/s) with 3 file(s) remaining
Completed 183.4 MiB/233.2 MiB (58.5 MiB/s) with 3 file(s) remaining
Completed 183.6 MiB/233.2 MiB (58.6 MiB/s) with 3 file(s) remaining
Completed 183.9 MiB/233.2 MiB (58.6 MiB/s) with 3 file(s) remaining
Completed 184.1 MiB/233.2 MiB (58.5 MiB/s) with 3 file(s) remaining
Completed 184.4 MiB/233.2 MiB (58.5 MiB/s) with 3 file(s) remaining
Completed 184.6 MiB/233.2 MiB (58.5 MiB/s) with 3 file(s) remaining
Completed 184.9 MiB/233.2 MiB (58.4 MiB/s) with 3 file(s) remaining
Completed 185.1 MiB/233.2 MiB (58.5 MiB/s) with 3 file(s) remaining
Completed 185.4 MiB/233.2 MiB (58.5 MiB/s) with 3 file(s) remaining
Completed 185.6 MiB/233.2 MiB (58.4 MiB/s) with 3 file(s) remaining
Completed 185.9 MiB/233.2 MiB (58.5 MiB/s) with 3 file(s) remaining
Completed 186.1 MiB/233.2 MiB (58.5 MiB/s) with 3 file(s) remaining
Completed 186.4 MiB/233.2 MiB (58.5 MiB/s) with 3 file(s) remaining
Completed 186.6 MiB/233.2 MiB (58.6 MiB/s) with 3 file(s) remaining
Completed 186.9 MiB/233.2 MiB (58.6 MiB/s) with 3 file(s) remaining
Completed 187.1 MiB/233.2 MiB (58.7 MiB/s) with 3 file(s) remaining
Completed 187.4 MiB/233.2 MiB (58.7 MiB/s) with 3 file(s) remaining
Completed 187.6 MiB/233.2 MiB (58.6 MiB/s) with 3 file(s) remaining
Completed 187.9 MiB/233.2 MiB (58.7 MiB/s) with 3 file(s) remaining
Completed 188.1 MiB/233.2 MiB (58.7 MiB/s) with 3 file(s) remaining
Completed 188.4 MiB/233.2 MiB (58.6 MiB/s) with 3 file(s) remaining
Completed 188.6 MiB/233.2 MiB (58.6 MiB/s) with 3 file(s) remaining
Completed 188.9 MiB/233.2 MiB (58.7 MiB/s) with 3 file(s) remaining
Completed 189.1 MiB/233.2 MiB (58.5 MiB/s) with 3 file(s) remaining
Completed 189.4 MiB/233.2 MiB (58.6 MiB/s) with 3 file(s) remaining
Completed 189.6 MiB/233.2 MiB (58.6 MiB/s) with 3 file(s) remaining
Completed 189.9 MiB/233.2 MiB (58.5 MiB/s) with 3 file(s) remaining
Completed 190.1 MiB/233.2 MiB (58.5 MiB/s) with 3 file(s) remaining
Completed 190.4 MiB/233.2 MiB (58.4 MiB/s) with 3 file(s) remaining
Completed 190.6 MiB/233.2 MiB (58.5 MiB/s) with 3 file(s) remaining
Completed 190.9 MiB/233.2 MiB (58.4 MiB/s) with 3 file(s) remaining
Completed 191.1 MiB/233.2 MiB (58.4 MiB/s) with 3 file(s) remaining
Completed 191.4 MiB/233.2 MiB (58.3 MiB/s) with 3 file(s) remaining
Completed 191.6 MiB/233.2 MiB (58.4 MiB/s) with 3 file(s) remaining
Completed 191.9 MiB/233.2 MiB (58.3 MiB/s) with 3 file(s) remaining
Completed 192.1 MiB/233.2 MiB (58.3 MiB/s) with 3 file(s) remaining
Completed 192.4 MiB/233.2 MiB (58.3 MiB/s) with 3 file(s) remaining
Completed 192.6 MiB/233.2 MiB (58.3 MiB/s) with 3 file(s) remaining
Completed 192.9 MiB/233.2 MiB (58.3 MiB/s) with 3 file(s) remaining
Completed 193.1 MiB/233.2 MiB (58.3 MiB/s) with 3 file(s) remaining
Completed 193.4 MiB/233.2 MiB (58.3 MiB/s) with 3 file(s) remaining
Completed 193.6 MiB/233.2 MiB (58.3 MiB/s) with 3 file(s) remaining
Completed 193.9 MiB/233.2 MiB (58.3 MiB/s) with 3 file(s) remaining
Completed 194.1 MiB/233.2 MiB (58.3 MiB/s) with 3 file(s) remaining
Completed 194.4 MiB/233.2 MiB (58.2 MiB/s) with 3 file(s) remaining
Completed 194.6 MiB/233.2 MiB (58.3 MiB/s) with 3 file(s) remaining
Completed 194.9 MiB/233.2 MiB (58.2 MiB/s) with 3 file(s) remaining
Completed 195.1 MiB/233.2 MiB (58.3 MiB/s) with 3 file(s) remaining
Completed 195.4 MiB/233.2 MiB (58.2 MiB/s) with 3 file(s) remaining
Completed 195.6 MiB/233.2 MiB (58.2 MiB/s) with 3 file(s) remaining
Completed 195.9 MiB/233.2 MiB (58.2 MiB/s) with 3 file(s) remaining
Completed 196.1 MiB/233.2 MiB (58.2 MiB/s) with 3 file(s) remaining
Completed 196.4 MiB/233.2 MiB (58.2 MiB/s) with 3 file(s) remaining
Completed 196.6 MiB/233.2 MiB (58.3 MiB/s) with 3 file(s) remaining
Completed 196.9 MiB/233.2 MiB (58.2 MiB/s) with 3 file(s) remaining
Completed 197.1 MiB/233.2 MiB (58.3 MiB/s) with 3 file(s) remaining
Completed 197.4 MiB/233.2 MiB (58.2 MiB/s) with 3 file(s) remaining
Completed 197.6 MiB/233.2 MiB (58.2 MiB/s) with 3 file(s) remaining
Completed 197.9 MiB/233.2 MiB (58.3 MiB/s) with 3 file(s) remaining
Completed 198.1 MiB/233.2 MiB (58.3 MiB/s) with 3 file(s) remaining
Completed 198.4 MiB/233.2 MiB (58.4 MiB/s) with 3 file(s) remaining
Completed 198.6 MiB/233.2 MiB (58.4 MiB/s) with 3 file(s) remaining
Completed 198.9 MiB/233.2 MiB (58.5 MiB/s) with 3 file(s) remaining
Completed 199.1 MiB/233.2 MiB (58.4 MiB/s) with 3 file(s) remaining
Completed 199.4 MiB/233.2 MiB (58.5 MiB/s) with 3 file(s) remaining
Completed 199.6 MiB/233.2 MiB (58.3 MiB/s) with 3 file(s) remaining
Completed 199.9 MiB/233.2 MiB (58.4 MiB/s) with 3 file(s) remaining
Completed 200.1 MiB/233.2 MiB (58.3 MiB/s) with 3 file(s) remaining
Completed 200.4 MiB/233.2 MiB (58.4 MiB/s) with 3 file(s) remaining
Completed 200.6 MiB/233.2 MiB (58.3 MiB/s) with 3 file(s) remaining
Completed 200.9 MiB/233.2 MiB (58.4 MiB/s) with 3 file(s) remaining
Completed 201.1 MiB/233.2 MiB (58.3 MiB/s) with 3 file(s) remaining
Completed 201.4 MiB/233.2 MiB (58.3 MiB/s) with 3 file(s) remaining
Completed 201.6 MiB/233.2 MiB (58.1 MiB/s) with 3 file(s) remaining
Completed 201.9 MiB/233.2 MiB (58.2 MiB/s) with 3 file(s) remaining
Completed 202.1 MiB/233.2 MiB (58.0 MiB/s) with 3 file(s) remaining
Completed 202.4 MiB/233.2 MiB (57.9 MiB/s) with 3 file(s) remaining
Completed 202.6 MiB/233.2 MiB (57.9 MiB/s) with 3 file(s) remaining
Completed 202.9 MiB/233.2 MiB (57.7 MiB/s) with 3 file(s) remaining
Completed 203.1 MiB/233.2 MiB (57.8 MiB/s) with 3 file(s) remaining
Completed 203.4 MiB/233.2 MiB (57.6 MiB/s) with 3 file(s) remaining
Completed 203.6 MiB/233.2 MiB (57.6 MiB/s) with 3 file(s) remaining
Completed 203.9 MiB/233.2 MiB (57.6 MiB/s) with 3 file(s) remaining
Completed 204.1 MiB/233.2 MiB (57.5 MiB/s) with 3 file(s) remaining
Completed 204.4 MiB/233.2 MiB (57.5 MiB/s) with 3 file(s) remaining
Completed 204.6 MiB/233.2 MiB (57.3 MiB/s) with 3 file(s) remaining
Completed 204.9 MiB/233.2 MiB (57.1 MiB/s) with 3 file(s) remaining
Completed 205.1 MiB/233.2 MiB (57.0 MiB/s) with 3 file(s) remaining
Completed 205.4 MiB/233.2 MiB (56.9 MiB/s) with 3 file(s) remaining
Completed 205.6 MiB/233.2 MiB (56.8 MiB/s) with 3 file(s) remaining
Completed 205.9 MiB/233.2 MiB (56.7 MiB/s) with 3 file(s) remaining
Completed 206.1 MiB/233.2 MiB (56.7 MiB/s) with 3 file(s) remaining
Completed 206.4 MiB/233.2 MiB (56.5 MiB/s) with 3 file(s) remaining
Completed 206.6 MiB/233.2 MiB (56.5 MiB/s) with 3 file(s) remaining
Completed 206.9 MiB/233.2 MiB (56.4 MiB/s) with 3 file(s) remaining
Completed 207.1 MiB/233.2 MiB (56.3 MiB/s) with 3 file(s) remaining
Completed 207.4 MiB/233.2 MiB (56.3 MiB/s) with 3 file(s) remaining
Completed 207.6 MiB/233.2 MiB (56.3 MiB/s) with 3 file(s) remaining
Completed 207.9 MiB/233.2 MiB (56.4 MiB/s) with 3 file(s) remaining
Completed 208.1 MiB/233.2 MiB (56.4 MiB/s) with 3 file(s) remaining
Completed 208.4 MiB/233.2 MiB (56.5 MiB/s) with 3 file(s) remaining
Completed 208.6 MiB/233.2 MiB (56.5 MiB/s) with 3 file(s) remaining
Completed 208.9 MiB/233.2 MiB (56.6 MiB/s) with 3 file(s) remaining
Completed 209.1 MiB/233.2 MiB (56.5 MiB/s) with 3 file(s) remaining
Completed 209.4 MiB/233.2 MiB (56.6 MiB/s) with 3 file(s) remaining
Completed 209.6 MiB/233.2 MiB (56.5 MiB/s) with 3 file(s) remaining
Completed 209.9 MiB/233.2 MiB (56.5 MiB/s) with 3 file(s) remaining
Completed 210.1 MiB/233.2 MiB (56.5 MiB/s) with 3 file(s) remaining
Completed 210.4 MiB/233.2 MiB (56.5 MiB/s) with 3 file(s) remaining
Completed 210.6 MiB/233.2 MiB (56.5 MiB/s) with 3 file(s) remaining
Completed 210.9 MiB/233.2 MiB (56.4 MiB/s) with 3 file(s) remaining
Completed 211.1 MiB/233.2 MiB (56.4 MiB/s) with 3 file(s) remaining
Completed 211.4 MiB/233.2 MiB (56.3 MiB/s) with 3 file(s) remaining
Completed 211.6 MiB/233.2 MiB (56.2 MiB/s) with 3 file(s) remaining
Completed 211.9 MiB/233.2 MiB (56.1 MiB/s) with 3 file(s) remaining
Completed 212.1 MiB/233.2 MiB (56.0 MiB/s) with 3 file(s) remaining
Completed 212.4 MiB/233.2 MiB (56.1 MiB/s) with 3 file(s) remaining
Completed 212.6 MiB/233.2 MiB (56.1 MiB/s) with 3 file(s) remaining
Completed 212.9 MiB/233.2 MiB (56.2 MiB/s) with 3 file(s) remaining
Completed 213.1 MiB/233.2 MiB (56.2 MiB/s) with 3 file(s) remaining
Completed 213.4 MiB/233.2 MiB (56.3 MiB/s) with 3 file(s) remaining
Completed 213.6 MiB/233.2 MiB (56.3 MiB/s) with 3 file(s) remaining
Completed 213.9 MiB/233.2 MiB (56.2 MiB/s) with 3 file(s) remaining
Completed 214.1 MiB/233.2 MiB (56.3 MiB/s) with 3 file(s) remaining
Completed 214.4 MiB/233.2 MiB (56.2 MiB/s) with 3 file(s) remaining
Completed 214.6 MiB/233.2 MiB (56.3 MiB/s) with 3 file(s) remaining
Completed 214.9 MiB/233.2 MiB (56.2 MiB/s) with 3 file(s) remaining
Completed 215.1 MiB/233.2 MiB (56.3 MiB/s) with 3 file(s) remaining
Completed 215.4 MiB/233.2 MiB (56.2 MiB/s) with 3 file(s) remaining
Completed 215.6 MiB/233.2 MiB (56.2 MiB/s) with 3 file(s) remaining
Completed 215.9 MiB/233.2 MiB (56.2 MiB/s) with 3 file(s) remaining
Completed 216.1 MiB/233.2 MiB (56.2 MiB/s) with 3 file(s) remaining
Completed 216.4 MiB/233.2 MiB (56.2 MiB/s) with 3 file(s) remaining
Completed 216.6 MiB/233.2 MiB (56.3 MiB/s) with 3 file(s) remaining
Completed 216.9 MiB/233.2 MiB (56.3 MiB/s) with 3 file(s) remaining
Completed 217.1 MiB/233.2 MiB (56.4 MiB/s) with 3 file(s) remaining
Completed 217.4 MiB/233.2 MiB (56.4 MiB/s) with 3 file(s) remaining
Completed 217.6 MiB/233.2 MiB (56.5 MiB/s) with 3 file(s) remaining
Completed 217.9 MiB/233.2 MiB (56.5 MiB/s) with 3 file(s) remaining
Completed 218.1 MiB/233.2 MiB (56.5 MiB/s) with 3 file(s) remaining
Completed 218.4 MiB/233.2 MiB (56.4 MiB/s) with 3 file(s) remaining
Completed 218.6 MiB/233.2 MiB (56.5 MiB/s) with 3 file(s) remaining
Completed 218.9 MiB/233.2 MiB (56.5 MiB/s) with 3 file(s) remaining
Completed 219.1 MiB/233.2 MiB (56.5 MiB/s) with 3 file(s) remaining
Completed 219.4 MiB/233.2 MiB (56.5 MiB/s) with 3 file(s) remaining
Completed 219.6 MiB/233.2 MiB (56.4 MiB/s) with 3 file(s) remaining
Completed 219.9 MiB/233.2 MiB (56.5 MiB/s) with 3 file(s) remaining
Completed 220.1 MiB/233.2 MiB (56.5 MiB/s) with 3 file(s) remaining
Completed 220.4 MiB/233.2 MiB (56.4 MiB/s) with 3 file(s) remaining
Completed 220.6 MiB/233.2 MiB (56.5 MiB/s) with 3 file(s) remaining
Completed 220.9 MiB/233.2 MiB (56.5 MiB/s) with 3 file(s) remaining
Completed 221.1 MiB/233.2 MiB (56.5 MiB/s) with 3 file(s) remaining
Completed 221.4 MiB/233.2 MiB (56.5 MiB/s) with 3 file(s) remaining
Completed 221.6 MiB/233.2 MiB (56.5 MiB/s) with 3 file(s) remaining
Completed 221.9 MiB/233.2 MiB (56.5 MiB/s) with 3 file(s) remaining
Completed 222.1 MiB/233.2 MiB (56.5 MiB/s) with 3 file(s) remaining
Completed 222.4 MiB/233.2 MiB (56.5 MiB/s) with 3 file(s) remaining
Completed 222.6 MiB/233.2 MiB (56.5 MiB/s) with 3 file(s) remaining
Completed 222.9 MiB/233.2 MiB (56.6 MiB/s) with 3 file(s) remaining
Completed 223.1 MiB/233.2 MiB (56.5 MiB/s) with 3 file(s) remaining
Completed 223.4 MiB/233.2 MiB (56.5 MiB/s) with 3 file(s) remaining
Completed 223.6 MiB/233.2 MiB (56.6 MiB/s) with 3 file(s) remaining
Completed 223.9 MiB/233.2 MiB (56.4 MiB/s) with 3 file(s) remaining
Completed 224.1 MiB/233.2 MiB (56.4 MiB/s) with 3 file(s) remaining
Completed 224.4 MiB/233.2 MiB (56.4 MiB/s) with 3 file(s) remaining
Completed 224.6 MiB/233.2 MiB (56.4 MiB/s) with 3 file(s) remaining
Completed 224.9 MiB/233.2 MiB (56.3 MiB/s) with 3 file(s) remaining
Completed 225.1 MiB/233.2 MiB (56.3 MiB/s) with 3 file(s) remaining
Completed 225.4 MiB/233.2 MiB (56.3 MiB/s) with 3 file(s) remaining
Completed 225.6 MiB/233.2 MiB (56.2 MiB/s) with 3 file(s) remaining
upload: ../../../data/datafile-65-MB to s3://awscli-mint-test-bucket-20632/datafile-65-MBCompleted 225.6 MiB/233.2 MiB (56.2 MiB/s) with 2 file(s) remaining
Completed 225.9 MiB/233.2 MiB (56.1 MiB/s) with 2 file(s) remaining
Completed 226.1 MiB/233.2 MiB (56.0 MiB/s) with 2 file(s) remaining
Completed 226.4 MiB/233.2 MiB (56.1 MiB/s) with 2 file(s) remaining
Completed 226.6 MiB/233.2 MiB (55.9 MiB/s) with 2 file(s) remaining
Completed 226.9 MiB/233.2 MiB (55.9 MiB/...Truncated

**Comment by minio-ops** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-xl.sh | :heavy_check_mark: |
| mint-compression-fs.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-compression-xl.sh | :x: [more...](#df68edf0-86d3-47da-905e-9485d252916b) |
| mint-large-bucket.sh | :x: [more...](#1d607995-9eb3-4144-bffa-2c0707af6b62) |
| mint-compression-dist-xl.sh | :x: [more...](#dabaf4cd-079d-44da-8467-c565fdb0c914) |
| mint-worm.sh | :x: [more...](#95bbb983-3b70-4b49-ae1b-cebbf19ec798) |
| mint-dist-xl.sh | :x: [more...](#8efa3c17-6f1a-4e65-9795-c83c043395ea) |
<a name="95bbb983-3b70-4b49-ae1b-cebbf19ec798"></a>
### 8027-ff6fa17/mint-worm.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.57:31275
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            worm
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp d6f591e1bd61:/mint/log /tmp/mint-logs'

(1/1) Running worm tests ... FAILED in 13 seconds
{
  "alert": "",
  "args": {
    "bucketName": "bucket-thmxqjtackee7tz9npgqx2f8en60j99wggq1tb411e63uid3u08z8do",
    "expiry": 60000000000,
    "objectName": "testObject"
  },
  "duration": 12268,
  "error": "RequestError: send request failed\ncaused by: Put http://72.28.97.57:31275/bucket-thmxqjtackee7tz9npgqx2f8en60j99wggq1tb411e63uid3u08z8do: dial tcp 72.28.97.57:31275: connect: no route to host",
  "function": "PutAndDelete",
  "message": "WORM_MODE ON  - CreateBucket Failed",
  "name": "test worm mode",
  "status": "FAIL"
}

Executed 0 out of 1 tests successfully.
```
<a name="8efa3c17-6f1a-4e65-9795-c83c043395ea"></a>
### 8027-ff6fa17/mint-dist-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.55:32745
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 172b7f1dfcbc:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 0 seconds
(2/14) Running aws-sdk-java tests ... done in 2 seconds
(3/14) Running aws-sdk-php tests ... done in 45 seconds
(4/14) Running aws-sdk-ruby tests ... done in 4 seconds
(5/14) Running awscli tests ... FAILED in 1 minutes and 5 seconds
{"name": "awscli", "duration": 10323, "function": "aws --endpoint-url http://72.28.97.55:32745 s3 sync /mint/data s3://awscli-mint-test-bucket-26258/\n", "status": "FAIL", "error": "Completed 256.0 KiB/233.2 MiB (5.0 MiB/s) with 15 file(s) remaining
upload: ../../../data/datafile-0-b to s3://awscli-mint-test-bucket-26258/datafile-0-bCompleted 256.0 KiB/233.2 MiB (5.0 MiB/s) with 14 file(s) remaining
Completed 512.0 KiB/233.2 MiB (9.0 MiB/s) with 14 file(s) remaining
Completed 768.0 KiB/233.2 MiB (13.2 MiB/s) with 14 file(s) remaining
Completed 1.0 MiB/233.2 MiB (17.2 MiB/s) with 14 file(s) remaining  
Completed 1.2 MiB/233.2 MiB (20.8 MiB/s) with 14 file(s) remaining  
Completed 1.5 MiB/233.2 MiB (23.6 MiB/s) with 14 file(s) remaining  
Completed 1.8 MiB/233.2 MiB (26.2 MiB/s) with 14 file(s) remaining  
Completed 2.0 MiB/233.2 MiB (28.7 MiB/s) with 14 file(s) remaining  
Completed 2.0 MiB/233.2 MiB (15.7 MiB/s) with 14 file(s) remaining  
upload: ../../../data/datafile-1-b to s3://awscli-mint-test-bucket-26258/datafile-1-bCompleted 2.0 MiB/233.2 MiB (15.7 MiB/s) with 13 file(s) remaining
Completed 2.0 MiB/233.2 MiB (15.6 MiB/s) with 13 file(s) remaining
upload: ../../../data/datafile-10-kB to s3://awscli-mint-test-bucket-26258/datafile-10-kBCompleted 2.0 MiB/233.2 MiB (15.6 MiB/s) with 12 file(s) remaining
Completed 2.0 MiB/233.2 MiB (15.4 MiB/s) with 12 file(s) remaining
upload: ../../../data/datafile-1-kB to s3://awscli-mint-test-bucket-26258/datafile-1-kBCompleted 2.0 MiB/233.2 MiB (15.4 MiB/s) with 11 file(s) remaining
Completed 2.1 MiB/233.2 MiB (15.9 MiB/s) with 11 file(s) remaining
upload: ../../../data/datafile-100-kB to s3://awscli-mint-test-bucket-26258/datafile-100-kBCompleted 2.1 MiB/233.2 MiB (15.9 MiB/s) with 10 file(s) remaining
Completed 2.1 MiB/233.2 MiB (12.6 MiB/s) with 10 file(s) remaining
upload: ../../../data/datafile-1.03-MB to s3://awscli-mint-test-bucket-26258/datafile-1.03-MBCompleted 2.1 MiB/233.2 MiB (12.6 MiB/s) with 9 file(s) remaining
Completed 2.2 MiB/233.2 MiB (12.7 MiB/s) with 9 file(s) remaining
upload: ../../../data/datafile-33-kB to s3://awscli-mint-test-bucket-26258/datafile-33-kBCompleted 2.2 MiB/233.2 MiB (12.7 MiB/s) with 8 file(s) remaining
upload: ../../../data/datafile-1-MB to s3://awscli-mint-test-bucket-26258/datafile-1-MBCompleted 2.2 MiB/233.2 MiB (12.7 MiB/s) with 7 file(s) remaining
Completed 2.4 MiB/233.2 MiB (13.2 MiB/s) with 7 file(s) remaining
Completed 2.7 MiB/233.2 MiB (14.3 MiB/s) with 7 file(s) remaining
Completed 2.9 MiB/233.2 MiB (15.5 MiB/s) with 7 file(s) remaining
Completed 3.2 MiB/233.2 MiB (16.6 MiB/s) with 7 file(s) remaining
Completed 3.4 MiB/233.2 MiB (17.8 MiB/s) with 7 file(s) remaining
Completed 3.7 MiB/233.2 MiB (18.9 MiB/s) with 7 file(s) remaining
Completed 3.9 MiB/233.2 MiB (20.1 MiB/s) with 7 file(s) remaining
Completed 4.2 MiB/233.2 MiB (21.2 MiB/s) with 7 file(s) remaining
Completed 4.4 MiB/233.2 MiB (22.4 MiB/s) with 7 file(s) remaining
Completed 4.7 MiB/233.2 MiB (22.9 MiB/s) with 7 file(s) remaining
Completed 4.9 MiB/233.2 MiB (24.1 MiB/s) with 7 file(s) remaining
Completed 5.2 MiB/233.2 MiB (25.0 MiB/s) with 7 file(s) remaining
Completed 5.4 MiB/233.2 MiB (25.9 MiB/s) with 7 file(s) remaining
Completed 5.7 MiB/233.2 MiB (27.0 MiB/s) with 7 file(s) remaining
Completed 5.9 MiB/233.2 MiB (28.1 MiB/s) with 7 file(s) remaining
Completed 6.2 MiB/233.2 MiB (29.0 MiB/s) with 7 file(s) remaining
Completed 6.4 MiB/233.2 MiB (29.8 MiB/s) with 7 file(s) remaining
Completed 6.7 MiB/233.2 MiB (30.8 MiB/s) with 7 file(s) remaining
Completed 6.9 MiB/233.2 MiB (31.9 MiB/s) with 7 file(s) remaining
Completed 7.2 MiB/233.2 MiB (32.7 MiB/s) with 7 file(s) remaining
Completed 7.4 MiB/233.2 MiB (33.6 MiB/s) with 7 file(s) remaining
Completed 7.7 MiB/233.2 MiB (34.6 MiB/s) with 7 file(s) remaining
Completed 7.9 MiB/233.2 MiB (35.3 MiB/s) with 7 file(s) remaining
Completed 8.2 MiB/233.2 MiB (36.4 MiB/s) with 7 file(s) remaining
Completed 8.4 MiB/233.2 MiB (37.2 MiB/s) with 7 file(s) remaining
Completed 8.7 MiB/233.2 MiB (38.0 MiB/s) with 7 file(s) remaining
Completed 8.9 MiB/233.2 MiB (38.9 MiB/s) with 7 file(s) remaining
Completed 9.2 MiB/233.2 MiB (39.9 MiB/s) with 7 file(s) remaining
Completed 9.4 MiB/233.2 MiB (40.5 MiB/s) with 7 file(s) remaining
Completed 9.7 MiB/233.2 MiB (41.3 MiB/s) with 7 file(s) remaining
Completed 9.9 MiB/233.2 MiB (42.3 MiB/s) with 7 file(s) remaining
Completed 10.2 MiB/233.2 MiB (43.1 MiB/s) with 7 file(s) remaining
Completed 10.4 MiB/233.2 MiB (43.7 MiB/s) with 7 file(s) remaining
Completed 10.7 MiB/233.2 MiB (44.0 MiB/s) with 7 file(s) remaining
Completed 10.9 MiB/233.2 MiB (45.0 MiB/s) with 7 file(s) remaining
Completed 11.2 MiB/233.2 MiB (46.0 MiB/s) with 7 file(s) remaining
Completed 11.4 MiB/233.2 MiB (47.0 MiB/s) with 7 file(s) remaining
Completed 11.7 MiB/233.2 MiB (47.1 MiB/s) with 7 file(s) remaining
Completed 11.9 MiB/233.2 MiB (48.1 MiB/s) with 7 file(s) remaining
Completed 12.2 MiB/233.2 MiB (48.9 MiB/s) with 7 file(s) remaining
Completed 12.4 MiB/233.2 MiB (49.7 MiB/s) with 7 file(s) remaining
Completed 12.7 MiB/233.2 MiB (50.2 MiB/s) with 7 file(s) remaining
Completed 12.9 MiB/233.2 MiB (50.9 MiB/s) with 7 file(s) remaining
Completed 13.2 MiB/233.2 MiB (51.7 MiB/s) with 7 file(s) remaining
Completed 13.4 MiB/233.2 MiB (52.3 MiB/s) with 7 file(s) remaining
Completed 13.7 MiB/233.2 MiB (53.2 MiB/s) with 7 file(s) remaining
Completed 13.9 MiB/233.2 MiB (53.6 MiB/s) with 7 file(s) remaining
Completed 14.2 MiB/233.2 MiB (54.4 MiB/s) with 7 file(s) remaining
Completed 14.4 MiB/233.2 MiB (54.4 MiB/s) with 7 file(s) remaining
Completed 14.7 MiB/233.2 MiB (55.2 MiB/s) with 7 file(s) remaining
Completed 14.9 MiB/233.2 MiB (55.8 MiB/s) with 7 file(s) remaining
Completed 15.2 MiB/233.2 MiB (55.7 MiB/s) with 7 file(s) remaining
Completed 15.4 MiB/233.2 MiB (56.3 MiB/s) with 7 file(s) remaining
Completed 15.7 MiB/233.2 MiB (56.9 MiB/s) with 7 file(s) remaining
Completed 15.9 MiB/233.2 MiB (56.7 MiB/s) with 7 file(s) remaining
Completed 16.2 MiB/233.2 MiB (57.4 MiB/s) with 7 file(s) remaining
Completed 16.4 MiB/233.2 MiB (57.1 MiB/s) with 7 file(s) remaining
Completed 16.7 MiB/233.2 MiB (56.7 MiB/s) with 7 file(s) remaining
Completed 16.9 MiB/233.2 MiB (57.5 MiB/s) with 7 file(s) remaining
Completed 17.2 MiB/233.2 MiB (56.9 MiB/s) with 7 file(s) remaining
Completed 17.4 MiB/233.2 MiB (57.6 MiB/s) with 7 file(s) remaining
Completed 17.7 MiB/233.2 MiB (58.4 MiB/s) with 7 file(s) remaining
Completed 17.9 MiB/233.2 MiB (58.3 MiB/s) with 7 file(s) remaining
Completed 18.2 MiB/233.2 MiB (58.9 MiB/s) with 7 file(s) remaining
Completed 18.4 MiB/233.2 MiB (58.2 MiB/s) with 7 file(s) remaining
Completed 18.7 MiB/233.2 MiB (58.3 MiB/s) with 7 file(s) remaining
Completed 18.9 MiB/233.2 MiB (58.8 MiB/s) with 7 file(s) remaining
Completed 19.2 MiB/233.2 MiB (58.9 MiB/s) with 7 file(s) remaining
Completed 19.4 MiB/233.2 MiB (59.7 MiB/s) with 7 file(s) remaining
Completed 19.7 MiB/233.2 MiB (59.5 MiB/s) with 7 file(s) remaining
Completed 19.9 MiB/233.2 MiB (59.8 MiB/s) with 7 file(s) remaining
Completed 20.2 MiB/233.2 MiB (60.0 MiB/s) with 7 file(s) remaining
Completed 20.4 MiB/233.2 MiB (59.3 MiB/s) with 7 file(s) remaining
Completed 20.7 MiB/233.2 MiB (59.8 MiB/s) with 7 file(s) remaining
Completed 20.9 MiB/233.2 MiB (60.1 MiB/s) with 7 file(s) remaining
Completed 21.2 MiB/233.2 MiB (60.7 MiB/s) with 7 file(s) remaining
Completed 21.4 MiB/233.2 MiB (61.2 MiB/s) with 7 file(s) remaining
Completed 21.7 MiB/233.2 MiB (60.5 MiB/s) with 7 file(s) remaining
Completed 21.9 MiB/233.2 MiB (61.2 MiB/s) with 7 file(s) remaining
Completed 22.2 MiB/233.2 MiB (61.0 MiB/s) with 7 file(s) remaining
Completed 22.4 MiB/233.2 MiB (60.5 MiB/s) with 7 file(s) remaining
Completed 22.7 MiB/233.2 MiB (61.0 MiB/s) with 7 file(s) remaining
Completed 22.9 MiB/233.2 MiB (61.6 MiB/s) with 7 file(s) remaining
Completed 23.2 MiB/233.2 MiB (62.2 MiB/s) with 7 file(s) remaining
Completed 23.4 MiB/233.2 MiB (62.2 MiB/s) with 7 file(s) remaining
Completed 23.7 MiB/233.2 MiB (61.4 MiB/s) with 7 file(s) remaining
Completed 23.9 MiB/233.2 MiB (62.1 MiB/s) with 7 file(s) remaining
Completed 24.2 MiB/233.2 MiB (61.9 MiB/s) with 7 file(s) remaining
Completed 24.4 MiB/233.2 MiB (61.4 MiB/s) with 7 file(s) remaining
Completed 24.7 MiB/233.2 MiB (61.8 MiB/s) with 7 file(s) remaining
Completed 24.9 MiB/233.2 MiB (61.7 MiB/s) with 7 file(s) remaining
Completed 25.2 MiB/233.2 MiB (62.3 MiB/s) with 7 file(s) remaining
Completed 25.4 MiB/233.2 MiB (62.6 MiB/s) with 7 file(s) remaining
Completed 25.7 MiB/233.2 MiB (62.7 MiB/s) with 7 file(s) remaining
Completed 25.9 MiB/233.2 MiB (63.0 MiB/s) with 7 file(s) remaining
Completed 26.2 MiB/233.2 MiB (63.0 MiB/s) with 7 file(s) remaining
Completed 26.4 MiB/233.2 MiB (62.6 MiB/s) with 7 file(s) remaining
Completed 26.7 MiB/233.2 MiB (62.9 MiB/s) with 7 file(s) remaining
Completed 26.9 MiB/233.2 MiB (63.4 MiB/s) with 7 file(s) remaining
Completed 27.2 MiB/233.2 MiB (63.5 MiB/s) with 7 file(s) remaining
Completed 27.4 MiB/233.2 MiB (62.8 MiB/s) with 7 file(s) remaining
Completed 27.7 MiB/233.2 MiB (62.6 MiB/s) with 7 file(s) remaining
Completed 27.9 MiB/233.2 MiB (63.0 MiB/s) with 7 file(s) remaining
Completed 28.2 MiB/233.2 MiB (63.2 MiB/s) with 7 file(s) remaining
Completed 28.4 MiB/233.2 MiB (63.6 MiB/s) with 7 file(s) remaining
Completed 28.7 MiB/233.2 MiB (63.0 MiB/s) with 7 file(s) remaining
Completed 28.9 MiB/233.2 MiB (63.5 MiB/s) with 7 file(s) remaining
Completed 29.2 MiB/233.2 MiB (63.1 MiB/s) with 7 file(s) remaining
Completed 29.4 MiB/233.2 MiB (63.3 MiB/s) with 7 file(s) remaining
Completed 29.7 MiB/233.2 MiB (63.8 MiB/s) with 7 file(s) remaining
Completed 29.9 MiB/233.2 MiB (64.0 MiB/s) with 7 file(s) remaining
Completed 30.2 MiB/233.2 MiB (63.7 MiB/s) with 7 file(s) remaining
Completed 30.4 MiB/233.2 MiB (63.7 MiB/s) with 7 file(s) remaining
Completed 30.7 MiB/233.2 MiB (63.4 MiB/s) with 7 file(s) remaining
Completed 30.9 MiB/233.2 MiB (63.9 MiB/s) with 7 file(s) remaining
Completed 31.2 MiB/233.2 MiB (64.1 MiB/s) with 7 file(s) remaining
Completed 31.4 MiB/233.2 MiB (64.5 MiB/s) with 7 file(s) remaining
Completed 31.7 MiB/233.2 MiB (64.2 MiB/s) with 7 file(s) remaining
Completed 31.9 MiB/233.2 MiB (64.6 MiB/s) with 7 file(s) remaining
Completed 32.2 MiB/233.2 MiB (65.0 MiB/s) with 7 file(s) remaining
Completed 32.4 MiB/233.2 MiB (65.3 MiB/s) with 7 file(s) remaining
Completed 32.7 MiB/233.2 MiB (65.7 MiB/s) with 7 file(s) remaining
Completed 32.9 MiB/233.2 MiB (66.1 MiB/s) with 7 file(s) remaining
Completed 33.2 MiB/233.2 MiB (66.4 MiB/s) with 7 file(s) remaining
Completed 33.4 MiB/233.2 MiB (66.7 MiB/s) with 7 file(s) remaining
Completed 33.7 MiB/233.2 MiB (66.9 MiB/s) with 7 file(s) remaining
Completed 33.9 MiB/233.2 MiB (67.4 MiB/s) with 7 file(s) remaining
Completed 34.2 MiB/233.2 MiB (67.7 MiB/s) with 7 file(s) remaining
Completed 34.4 MiB/233.2 MiB (68.1 MiB/s) with 7 file(s) remaining
Completed 34.7 MiB/233.2 MiB (68.4 MiB/s) with 7 file(s) remaining
Completed 34.9 MiB/233.2 MiB (68.8 MiB/s) with 7 file(s) remaining
Completed 35.2 MiB/233.2 MiB (69.1 MiB/s) with 7 file(s) remaining
Completed 35.4 MiB/233.2 MiB (69.4 MiB/s) with 7 file(s) remaining
Completed 35.7 MiB/233.2 MiB (69.7 MiB/s) with 7 file(s) remaining
Completed 35.9 MiB/233.2 MiB (69.9 MiB/s) with 7 file(s) remaining
Completed 36.2 MiB/233.2 MiB (70.2 MiB/s) with 7 file(s) remaining
Completed 36.4 MiB/233.2 MiB (70.5 MiB/s) with 7 file(s) remaining
Completed 36.7 MiB/233.2 MiB (70.9 MiB/s) with 7 file(s) remaining
Completed 36.9 MiB/233.2 MiB (71.1 MiB/s) with 7 file(s) remaining
Completed 37.2 MiB/233.2 MiB (71.6 MiB/s) with 7 file(s) remaining
Completed 37.4 MiB/233.2 MiB (71.9 MiB/s) with 7 file(s) remaining
Completed 37.7 MiB/233.2 MiB (72.2 MiB/s) with 7 file(s) remaining
Completed 37.9 MiB/233.2 MiB (72.4 MiB/s) with 7 file(s) remaining
Completed 38.2 MiB/233.2 MiB (72.8 MiB/s) with 7 file(s) remaining
Completed 38.4 MiB/233.2 MiB (73.0 MiB/s) with 7 file(s) remaining
Completed 38.7 MiB/233.2 MiB (73.3 MiB/s) with 7 file(s) remaining
Completed 38.9 MiB/233.2 MiB (73.6 MiB/s) with 7 file(s) remaining
Completed 39.2 MiB/233.2 MiB (74.0 MiB/s) with 7 file(s) remaining
Completed 39.4 MiB/233.2 MiB (74.3 MiB/s) with 7 file(s) remaining
Completed 39.7 MiB/233.2 MiB (74.7 MiB/s) with 7 file(s) remaining
Completed 39.9 MiB/233.2 MiB (75.0 MiB/s) with 7 file(s) remaining
Completed 40.2 MiB/233.2 MiB (75.3 MiB/s) with 7 file(s) remaining
Completed 40.4 MiB/233.2 MiB (75.7 MiB/s) with 7 file(s) remaining
Completed 40.7 MiB/233.2 MiB (76.1 MiB/s) with 7 file(s) remaining
Completed 40.9 MiB/233.2 MiB (76.3 MiB/s) with 7 file(s) remaining
Completed 41.2 MiB/233.2 MiB (76.6 MiB/s) with 7 file(s) remaining
Completed 41.4 MiB/233.2 MiB (76.9 MiB/s) with 7 file(s) remaining
Completed 41.7 MiB/233.2 MiB (77.2 MiB/s) with 7 file(s) remaining
Completed 41.9 MiB/233.2 MiB (77.5 MiB/s) with 7 file(s) remaining
Completed 42.2 MiB/233.2 MiB (77.8 MiB/s) with 7 file(s) remaining
Completed 42.4 MiB/233.2 MiB (78.0 MiB/s) with 7 file(s) remaining
Completed 42.7 MiB/233.2 MiB (78.3 MiB/s) with 7 file(s) remaining
Completed 42.9 MiB/233.2 MiB (77.1 MiB/s) with 7 file(s) remaining
Completed 43.2 MiB/233.2 MiB (75.6 MiB/s) with 7 file(s) remaining
Completed 43.4 MiB/233.2 MiB (74.3 MiB/s) with 7 file(s) remaining
upload: ../../../data/datafile-5-MB to s3://awscli-mint-test-bucket-26258/datafile-5-MBCompleted 43.4 MiB/233.2 MiB (74.3 MiB/s) with 6 file(s) remaining
Completed 43.7 MiB/233.2 MiB (73.2 MiB/s) with 6 file(s) remaining
Completed 43.9 MiB/233.2 MiB (72.1 MiB/s) with 6 file(s) remaining
Completed 44.2 MiB/233.2 MiB (71.1 MiB/s) with 6 file(s) remaining
Completed 44.4 MiB/233.2 MiB (70.4 MiB/s) with 6 file(s) remaining
Completed 44.7 MiB/233.2 MiB (70.5 MiB/s) with 6 file(s) remaining
Completed 44.9 MiB/233.2 MiB (69.7 MiB/s) with 6 file(s) remaining
Completed 45.2 MiB/233.2 MiB (68.9 MiB/s) with 6 file(s) remaining
Completed 45.4 MiB/233.2 MiB (68.4 MiB/s) with 6 file(s) remaining
Completed 45.7 MiB/233.2 MiB (66.4 MiB/s) with 6 file(s) remaining
Completed 45.7 MiB/233.2 MiB (64.9 MiB/s) with 6 file(s) remaining
upload: ../../../data/datafile-5243880-b to s3://awscli-mint-test-bucket-26258/datafile-5243880-bCompleted 45.7 MiB/233.2 MiB (64.9 MiB/s) with 5 file(s) remaining
Completed 45.9 MiB/233.2 MiB (65.1 MiB/s) with 5 file(s) remaining
Completed 46.2 MiB/233.2 MiB (64.7 MiB/s) with 5 file(s) remaining
Completed 46.4 MiB/233.2 MiB (64.3 MiB/s) with 5 file(s) remaining
Completed 46.7 MiB/233.2 MiB (64.1 MiB/s) with 5 file(s) remaining
Completed 46.9 MiB/233.2 MiB (64.1 MiB/s) with 5 file(s) remaining
Completed 47.2 MiB/233.2 MiB (64.1 MiB/s) with 5 file(s) remaining
upload: ../../../data/datafile-6-MB to s3://awscli-mint-test-bucket-26258/datafile-6-MBCompleted 47.2 MiB/233.2 MiB (64.1 MiB/s) with 4 file(s) remaining
Completed 47.4 MiB/233.2 MiB (61.4 MiB/s) with 4 file(s) remaining
Completed 47.7 MiB/233.2 MiB (61.2 MiB/s) with 4 file(s) remaining
Completed 47.9 MiB/233.2 MiB (61.1 MiB/s) with 4 file(s) remaining
Completed 48.2 MiB/233.2 MiB (61.0 MiB/s) with 4 file(s) remaining
Completed 48.4 MiB/233.2 MiB (60.9 MiB/s) with 4 file(s) remaining
Completed 48.7 MiB/233.2 MiB (60.9 MiB/s) with 4 file(s) remaining
Completed 48.9 MiB/233.2 MiB (60.7 MiB/s) with 4 file(s) remaining
Completed 49.2 MiB/233.2 MiB (60.7 MiB/s) with 4 file(s) remaining
Completed 49.4 MiB/233.2 MiB (60.7 MiB/s) with 4 file(s) remaining
Completed 49.7 MiB/233.2 MiB (60.8 MiB/s) with 4 file(s) remaining
Completed 49.9 MiB/233.2 MiB (61.0 MiB/s) with 4 file(s) remaining
Completed 50.2 MiB/233.2 MiB (60.8 MiB/s) with 4 file(s) remaining
Completed 50.4 MiB/233.2 MiB (61.0 MiB/s) with 4 file(s) remaining
Completed 50.7 MiB/233.2 MiB (61.3 MiB/s) with 4 file(s) remaining
Completed 50.9 MiB/233.2 MiB (61.5 MiB/s) with 4 file(s) remaining
Completed 51.2 MiB/233.2 MiB (61.7 MiB/s) with 4 file(s) remaining
Completed 51.4 MiB/233.2 MiB (61.8 MiB/s) with 4 file(s) remaining
Completed 51.7 MiB/233.2 MiB (61.9 MiB/s) with 4 file(s) remaining
Completed 51.9 MiB/233.2 MiB (62.1 MiB/s) with 4 file(s) remaining
Completed 52.2 MiB/233.2 MiB (62.3 MiB/s) with 4 file(s) remaining
Completed 52.4 MiB/233.2 MiB (62.4 MiB/s) with 4 file(s) remaining
Completed 52.7 MiB/233.2 MiB (62.7 MiB/s) with 4 file(s) remaining
Completed 52.9 MiB/233.2 MiB (62.7 MiB/s) with 4 file(s) remaining
Completed 53.2 MiB/233.2 MiB (63.0 MiB/s) with 4 file(s) remaining
Completed 53.4 MiB/233.2 MiB (63.2 MiB/s) with 4 file(s) remaining
Completed 53.7 MiB/233.2 MiB (63.4 MiB/s) with 4 file(s) remaining
Completed 53.9 MiB/233.2 MiB (63.6 MiB/s) with 4 file(s) remaining
Completed 54.2 MiB/233.2 MiB (63.7 MiB/s) with 4 file(s) remaining
Completed 54.4 MiB/233.2 MiB (63.9 MiB/s) with 4 file(s) remaining
Completed 54.7 MiB/233.2 MiB (64.1 MiB/s) with 4 file(s) remaining
Completed 54.9 MiB/233.2 MiB (64.1 MiB/s) with 4 file(s) remaining
Completed 55.2 MiB/233.2 MiB (64.3 MiB/s) with 4 file(s) remaining
Completed 55.4 MiB/233.2 MiB (64.4 MiB/s) with 4 file(s) remaining
Completed 55.7 MiB/233.2 MiB (64.5 MiB/s) with 4 file(s) remaining
Completed 55.9 MiB/233.2 MiB (64.6 MiB/s) with 4 file(s) remaining
Completed 56.2 MiB/233.2 MiB (64.8 MiB/s) with 4 file(s) remaining
Completed 56.4 MiB/233.2 MiB (64.7 MiB/s) with 4 file(s) remaining
Completed 56.7 MiB/233.2 MiB (64.9 MiB/s) with 4 file(s) remaining
Completed 56.9 MiB/233.2 MiB (65.1 MiB/s) with 4 file(s) remaining
Completed 57.2 MiB/233.2 MiB (65.2 MiB/s) with 4 file(s) remaining
Completed 57.4 MiB/233.2 MiB (65.0 MiB/s) with 4 file(s) remaining
Completed 57.7 MiB/233.2 MiB (65.2 MiB/s) with 4 file(s) remaining
Completed 57.9 MiB/233.2 MiB (65.5 MiB/s) with 4 file(s) remaining
Completed 58.2 MiB/233.2 MiB (65.6 MiB/s) with 4 file(s) remaining
Completed 58.4 MiB/233.2 MiB (65.5 MiB/s) with 4 file(s) remaining
Completed 58.7 MiB/233.2 MiB (65.7 MiB/s) with 4 file(s) remaining
Completed 58.9 MiB/233.2 MiB (65.9 MiB/s) with 4 file(s) remaining
Completed 59.2 MiB/233.2 MiB (65.9 MiB/s) with 4 file(s) remaining
Completed 59.4 MiB/233.2 MiB (65.9 MiB/s) with 4 file(s) remaining
Completed 59.7 MiB/233.2 MiB (66.1 MiB/s) with 4 file(s) remaining
Completed 59.9 MiB/233.2 MiB (66.3 MiB/s) with 4 file(s) remaining
Completed 60.2 MiB/233.2 MiB (66.2 MiB/s) with 4 file(s) remaining
Completed 60.4 MiB/233.2 MiB (66.2 MiB/s) with 4 file(s) remaining
Completed 60.7 MiB/233.2 MiB (66.4 MiB/s) with 4 file(s) remaining
Completed 60.9 MiB/233.2 MiB (66.6 MiB/s) with 4 file(s) remaining
Completed 61.2 MiB/233.2 MiB (66.5 MiB/s) with 4 file(s) remaining
Completed 61.4 MiB/233.2 MiB (66.5 MiB/s) with 4 file(s) remaining
Completed 61.7 MiB/233.2 MiB (66.7 MiB/s) with 4 file(s) remaining
Completed 61.9 MiB/233.2 MiB (66.8 MiB/s) with 4 file(s) remaining
Completed 62.2 MiB/233.2 MiB (66.8 MiB/s) with 4 file(s) remaining
Completed 62.4 MiB/233.2 MiB (66.8 MiB/s) with 4 file(s) remaining
Completed 62.7 MiB/233.2 MiB (67.0 MiB/s) with 4 file(s) remaining
Completed 62.9 MiB/233.2 MiB (67.2 MiB/s) with 4 file(s) remaining
Completed 63.2 MiB/233.2 MiB (67.2 MiB/s) with 4 file(s) remaining
Completed 63.4 MiB/233.2 MiB (67.2 MiB/s) with 4 file(s) remaining
Completed 63.7 MiB/233.2 MiB (67.3 MiB/s) with 4 file(s) remaining
Completed 63.9 MiB/233.2 MiB (67.5 MiB/s) with 4 file(s) remaining
Completed 64.2 MiB/233.2 MiB (67.6 MiB/s) with 4 file(s) remaining
Completed 64.4 MiB/233.2 MiB (67.7 MiB/s) with 4 file(s) remaining
Completed 64.7 MiB/233.2 MiB (67.8 MiB/s) with 4 file(s) remaining
Completed 64.9 MiB/233.2 MiB (68.0 MiB/s) with 4 file(s) remaining
Completed 65.2 MiB/233.2 MiB (68.0 MiB/s) with 4 file(s) remaining
Completed 65.4 MiB/233.2 MiB (68.1 MiB/s) with 4 file(s) remaining
Completed 65.7 MiB/233.2 MiB (68.2 MiB/s) with 4 file(s) remaining
Completed 65.9 MiB/233.2 MiB (68.4 MiB/s) with 4 file(s) remaining
Completed 66.2 MiB/233.2 MiB (68.4 MiB/s) with 4 file(s) remaining
Completed 66.4 MiB/233.2 MiB (68.5 MiB/s) with 4 file(s) remaining
Completed 66.7 MiB/233.2 MiB (68.5 MiB/s) with 4 file(s) remaining
Completed 66.9 MiB/233.2 MiB (68.8 MiB/s) with 4 file(s) remaining
Completed 67.2 MiB/233.2 MiB (68.7 MiB/s) with 4 file(s) remaining
Completed 67.4 MiB/233.2 MiB (68.7 MiB/s) with 4 file(s) remaining
Completed 67.7 MiB/233.2 MiB (68.9 MiB/s) with 4 file(s) remaining
Completed 67.9 MiB/233.2 MiB (69.1 MiB/s) with 4 file(s) remaining
Completed 68.2 MiB/233.2 MiB (69.1 MiB/s) with 4 file(s) remaining
Completed 68.4 MiB/233.2 MiB (69.2 MiB/s) with 4 file(s) remaining
Completed 68.7 MiB/233.2 MiB (69.3 MiB/s) with 4 file(s) remaining
Completed 68.9 MiB/233.2 MiB (69.6 MiB/s) with 4 file(s) remaining
Completed 69.2 MiB/233.2 MiB (69.2 MiB/s) with 4 file(s) remaining
Completed 69.4 MiB/233.2 MiB (69.0 MiB/s) with 4 file(s) remaining
Completed 69.7 MiB/233.2 MiB (68.7 MiB/s) with 4 file(s) remaining
Completed 69.9 MiB/233.2 MiB (68.5 MiB/s) with 4 file(s) remaining
Completed 70.2 MiB/233.2 MiB (68.4 MiB/s) with 4 file(s) remaining
Completed 70.4 MiB/233.2 MiB (68.4 MiB/s) with 4 file(s) remaining
Completed 70.7 MiB/233.2 MiB (68.3 MiB/s) with 4 file(s) remaining
Completed 70.9 MiB/233.2 MiB (68.0 MiB/s) with 4 file(s) remaining
Completed 71.2 MiB/233.2 MiB (67.7 MiB/s) with 4 file(s) remaining
Completed 71.4 MiB/233.2 MiB (67.1 MiB/s) with 4 file(s) remaining
Completed 71.7 MiB/233.2 MiB (67.3 MiB/s) with 4 file(s) remaining
Completed 71.9 MiB/233.2 MiB (67.4 MiB/s) with 4 file(s) remaining
Completed 72.2 MiB/233.2 MiB (67.6 MiB/s) with 4 file(s) remaining
Completed 72.4 MiB/233.2 MiB (67.8 MiB/s) with 4 file(s) remaining
Completed 72.7 MiB/233.2 MiB (68.0 MiB/s) with 4 file(s) remaining
Completed 72.9 MiB/233.2 MiB (68.2 MiB/s) with 4 file(s) remaining
Completed 73.2 MiB/233.2 MiB (68.3 MiB/s) with 4 file(s) remaining
Completed 73.4 MiB/233.2 MiB (68.5 MiB/s) with 4 file(s) remaining
Completed 73.7 MiB/233.2 MiB (68.6 MiB/s) with 4 file(s) remaining
Completed 73.9 MiB/233.2 MiB (68.8 MiB/s) with 4 file(s) remaining
Completed 74.2 MiB/233.2 MiB (69.0 MiB/s) with 4 file(s) remaining
Completed 74.4 MiB/233.2 MiB (69.1 MiB/s) with 4 file(s) remaining
Completed 74.7 MiB/233.2 MiB (69.3 MiB/s) with 4 file(s) remaining
Completed 74.9 MiB/233.2 MiB (69.3 MiB/s) with 4 file(s) remaining
Completed 75.2 MiB/233.2 MiB (69.5 MiB/s) with 4 file(s) remaining
Completed 75.4 MiB/233.2 MiB (69.5 MiB/s) with 4 file(s) remaining
Completed 75.7 MiB/233.2 MiB (69.7 MiB/s) with 4 file(s) remaining
Completed 75.9 MiB/233.2 MiB (69.7 MiB/s) with 4 file(s) remaining
Completed 76.2 MiB/233.2 MiB (69.8 MiB/s) with 4 file(s) remaining
Completed 76.4 MiB/233.2 MiB (70.0 MiB/s) with 4 file(s) remaining
Completed 76.7 MiB/233.2 MiB (70.1 MiB/s) with 4 file(s) remaining
Completed 76.9 MiB/233.2 MiB (70.3 MiB/s) with 4 file(s) remaining
Completed 77.2 MiB/233.2 MiB (70.4 MiB/s) with 4 file(s) remaining
Completed 77.4 MiB/233.2 MiB (70.6 MiB/s) with 4 file(s) remaining
Completed 77.7 MiB/233.2 MiB (70.8 MiB/s) with 4 file(s) remaining
Completed 77.9 MiB/233.2 MiB (70.9 MiB/s) with 4 file(s) remaining
Completed 78.2 MiB/233.2 MiB (71.1 MiB/s) with 4 file(s) remaining
Completed 78.4 MiB/233.2 MiB (71.3 MiB/s) with 4 file(s) remaining
Completed 78.7 MiB/233.2 MiB (71.5 MiB/s) with 4 file(s) remaining
Completed 78.9 MiB/233.2 MiB (71.6 MiB/s) with 4 file(s) remaining
Completed 79.2 MiB/233.2 MiB (71.8 MiB/s) with 4 file(s) remaining
Completed 79.4 MiB/233.2 MiB (72.0 MiB/s) with 4 file(s) remaining
Completed 79.7 MiB/233.2 MiB (72.2 MiB/s) with 4 file(s) remaining
Completed 79.9 MiB/233.2 MiB (72.4 MiB/s) with 4 file(s) remaining
Completed 80.2 MiB/233.2 MiB (72.2 MiB/s) with 4 file(s) remaining
Completed 80.4 MiB/233.2 MiB (72.1 MiB/s) with 4 file(s) remaining
Completed 80.7 MiB/233.2 MiB (72.0 MiB/s) with 4 file(s) remaining
Completed 80.9 MiB/233.2 MiB (71.3 MiB/s) with 4 file(s) remaining
Completed 81.2 MiB/233.2 MiB (70.2 MiB/s) with 4 file(s) remaining
Completed 81.4 MiB/233.2 MiB (69.4 MiB/s) with 4 file(s) remaining
Completed 81.7 MiB/233.2 MiB (68.3 MiB/s) with 4 file(s) remaining
Completed 81.9 MiB/233.2 MiB (67.3 MiB/s) with 4 file(s) remaining
Completed 82.2 MiB/233.2 MiB (66.5 MiB/s) with 4 file(s) remaining
Completed 82.4 MiB/233.2 MiB (65.6 MiB/s) with 4 file(s) remaining
Completed 82.7 MiB/233.2 MiB (64.9 MiB/s) with 4 file(s) remaining
Completed 82.9 MiB/233.2 MiB (64.1 MiB/s) with 4 file(s) remaining
Completed 83.2 MiB/233.2 MiB (63.4 MiB/s) with 4 file(s) remaining
Completed 83.4 MiB/233.2 MiB (62.7 MiB/s) with 4 file(s) remaining
Completed 83.7 MiB/233.2 MiB (62.0 MiB/s) with 4 file(s) remaining
Completed 83.9 MiB/233.2 MiB (61.3 MiB/s) with 4 file(s) remaining
Completed 84.2 MiB/233.2 MiB (60.5 MiB/s) with 4 file(s) remaining
Completed 84.4 MiB/233.2 MiB (59.8 MiB/s) with 4 file(s) remaining
Completed 84.7 MiB/233.2 MiB (59.3 MiB/s) with 4 file(s) remaining
Completed 84.9 MiB/233.2 MiB (58.8 MiB/s) with 4 file(s) remaining
Completed 85.2 MiB/233.2 MiB (58.5 MiB/s) with 4 file(s) remaining
Completed 85.4 MiB/233.2 MiB (58.1 MiB/s) with 4 file(s) remaining
Completed 85.7 MiB/233.2 MiB (57.8 MiB/s) with 4 file(s) remaining
Completed 85.9 MiB/233.2 MiB (57.5 MiB/s) with 4 file(s) remaining
Completed 86.2 MiB/233.2 MiB (57.1 MiB/s) with 4 file(s) remaining
Completed 86.4 MiB/233.2 MiB (56.7 MiB/s) with 4 file(s) remaining
Completed 86.7 MiB/233.2 MiB (56.3 MiB/s) with 4 file(s) remaining
Completed 86.9 MiB/233.2 MiB (56.0 MiB/s) with 4 file(s) remaining
upload: ../../../data/datafile-10-MB to s3://awscli-mint-test-bucket-26258/datafile-10-MBCompleted 86.9 MiB/233.2 MiB (56.0 MiB/s) with 3 file(s) remaining
Completed 87.2 MiB/233.2 MiB (55.9 MiB/s) with 3 file(s) remaining
Completed 87.4 MiB/233.2 MiB (53.1 MiB/s) with 3 file(s) remaining
Completed 87.7 MiB/233.2 MiB (53.1 MiB/s) with 3 file(s) remaining
Completed 87.9 MiB/233.2 MiB (53.0 MiB/s) with 3 file(s) remaining
Completed 88.2 MiB/233.2 MiB (53.1 MiB/s) with 3 file(s) remaining
Completed 88.4 MiB/233.2 MiB (53.1 MiB/s) with 3 file(s) remaining
Completed 88.7 MiB/233.2 MiB (53.1 MiB/s) with 3 file(s) remaining
upload: ../../../data/datafile-11-MB to s3://awscli-mint-test-bucket-26258/datafile-11-MBCompleted 88.7 MiB/233.2 MiB (53.1 MiB/s) with 2 file(s) remaining
Completed 88.9 MiB/233.2 MiB (53.0 MiB/s) with 2 file(s) remaining
Completed 89.2 MiB/233.2 MiB (53.1 MiB/s) with 2 file(s) remaining
Completed 89.4 MiB/233.2 MiB (53.0 MiB/s) with 2 file(s) remaining
Completed 89.7 MiB/233.2 MiB (53.1 MiB/s) with 2 file(s) remaining
Completed 89.9 MiB/233.2 MiB (53.1 MiB/s) with 2 file(s) remaining
Completed 90.2 MiB/233.2 MiB (53.1 MiB/s) with 2 file(s) remaining
Completed 90.4 MiB/233.2 MiB (53.1 MiB/s) with 2 file(s) remaining
Completed 90.7 MiB/233.2 MiB (53.2 MiB/s) with 2 file(s) remaining
Completed 90.9 MiB/233.2 MiB (53.3 MiB/s) with 2 file(s) remaining
Completed 91.2 MiB/233.2 MiB (53.4 MiB/s) with 2 file(s) remaining
Completed 91.4 MiB/233.2 MiB (53.5 MiB/s) with 2 file(s) remaining
Completed 91.7 MiB/233.2 MiB (53.6 MiB/s) with 2 file(s) remaining
Completed 91.9 MiB/233.2 MiB (53.7 MiB/s) with 2 file(s) remaining
Completed 92.2 MiB/233.2 MiB (53.8 MiB/s) with 2 file(s) remaining
Completed 92.4 MiB/233.2 MiB (53.9 MiB/s) with 2 file(s) remaining
Completed 92.7 MiB/233.2 MiB (54.0 MiB/s) with 2 file(s) remaining
Completed 92.9 MiB/233.2 MiB (54.2 MiB/s) with 2 file(s) remaining
Completed 93.2 MiB/233.2 MiB (54.3 MiB/s) with 2 file(s) remaining
Completed 93.4 MiB/233.2 MiB (54.4 MiB/s) with 2 file(s) remaining
Completed 93.7 MiB/233.2 MiB (54.5 MiB/s) with 2 file(s) remaining
Completed 93.9 MiB/233.2 MiB (54.6 MiB/s) with 2 file(s) remaining
Completed 94.2 MiB/233.2 MiB (54.7 MiB/s) with 2 file(s) remaining
Completed 94.4 MiB/233.2 MiB (54.8 MiB/s) with 2 file(s) remaining
Completed 94.7 MiB/233.2 MiB (54.9 MiB/s) with 2 file(s) remaining
Completed 94.9 MiB/233.2 MiB (55.1 MiB/s) with 2 file(s) remaining
Completed 95.2 MiB/233.2 MiB (55.1 MiB/s) with 2 file(s) remaining
Completed 95.4 MiB/233.2 MiB (55.2 MiB/s) with 2 file(s) remaining
Completed 95.7 MiB/233.2 MiB (55.4 MiB/s) with 2 file(s) remaining
Completed 95.9 MiB/233.2 MiB (55.5 MiB/s) with 2 file(s) remaining
Completed 96.2 MiB/233.2 MiB (55.5 MiB/s) with 2 file(s) remaining
Completed 96.4 MiB/233.2 MiB (55.6 MiB/s) with 2 file(s) remaining
Completed 96.7 MiB/233.2 MiB (55.7 MiB/s) with 2 file(s) remaining
Completed 96.9 MiB/233.2 MiB (55.9 MiB/s) with 2 file(s) remaining
Completed 97.2 MiB/233.2 MiB (56.0 MiB/s) with 2 file(s) remaining
Completed 97.4 MiB/233.2 MiB (56.1 MiB/s) with 2 file(s) remaining
Completed 97.7 MiB/233.2 MiB (56.1 MiB/s) with 2 file(s) remaining
Completed 97.9 MiB/233.2 MiB (56.3 MiB/s) with 2 file(s) remaining
Completed 98.2 MiB/233.2 MiB (56.4 MiB/s) with 2 file(s) remaining
Completed 98.4 MiB/233.2 MiB (56.5 MiB/s) with 2 file(s) remaining
Completed 98.7 MiB/233.2 MiB (56.6 MiB/s) with 2 file(s) remaining
Completed 98.9 MiB/233.2 MiB (56.7 MiB/s) with 2 file(s) remaining
Completed 99.2 MiB/233.2 MiB (56.8 MiB/s) with 2 file(s) remaining
Completed 99.4 MiB/233.2 MiB (56.9 MiB/s) with 2 file(s) remaining
Completed 99.7 MiB/233.2 MiB (57.0 MiB/s) with 2 file(s) remaining
Completed 99.9 MiB/233.2 MiB (57.1 MiB/s) with 2 file(s) remaining
Completed 100.2 MiB/233.2 MiB (57.2 MiB/s) with 2 file(s) remaining
Completed 100.4 MiB/233.2 MiB (57.3 MiB/s) with 2 file(s) remaining
Completed 100.7 MiB/233.2 MiB (57.2 MiB/s) with 2 file(s) remaining
Completed 100.9 MiB/233.2 MiB (57.1 MiB/s) with 2 file(s) remaining
Completed 101.2 MiB/233.2 MiB (56.7 MiB/s) with 2 file(s) remaining
Completed 101.4 MiB/233.2 MiB (56.6 MiB/s) with 2 file(s) remaining
Completed 101.7 MiB/233.2 MiB (56.3 MiB/s) with 2 file(s) remaining
Completed 101.9 MiB/233.2 MiB (55.9 MiB/s) with 2 file(s) remaining
Completed 102.2 MiB/233.2 MiB (55.9 MiB/s) with 2 file(s) remaining
Completed 102.4 MiB/233.2 MiB (55.8 MiB/s) with 2 file(s) remaining
Completed 102.7 MiB/233.2 MiB (55.8 MiB/s) with 2 file(s) remaining
Completed 102.9 MiB/233.2 MiB (55.8 MiB/s) with 2 file(s) remaining
Completed 103.2 MiB/233.2 MiB (55.6 MiB/s) with 2 file(s) remaining
Completed 103.4 MiB/233.2 MiB (55.5 MiB/s) with 2 file(s) remaining
Completed 103.7 MiB/233.2 MiB (55.3 MiB/s) with 2 file(s) remaining
Completed 103.9 MiB/233.2 MiB (55.3 MiB/s) with 2 file(s) remaining
Completed 104.2 MiB/233.2 MiB (55.1 MiB/s) with 2 file(s) remaining
Completed 104.4 MiB/233.2 MiB (55.0 MiB/s) with 2 file(s) remaining
Completed 104.7 MiB/233.2 MiB (54.8 MiB/s) with 2 file(s) remaining
Completed 104.9 MiB/233.2 MiB (54.7 MiB/s) with 2 file(s) remaining
Completed 105.2 MiB/233.2 MiB (54.7 MiB/s) with 2 file(s) remaining
Completed 105.4 MiB/233.2 MiB (54.6 MiB/s) with 2 file(s) remaining
Completed 105.7 MiB/233.2 MiB (54.5 MiB/s) with 2 file(s) remaining
Completed 105.9 MiB/233.2 MiB (54.5 MiB/s) with 2 file(s) remaining
Completed 106.2 MiB/233.2 MiB (54.3 MiB/s) with 2 file(s) remaining
Completed 106.4 MiB/233.2 MiB (54.2 MiB/s) with 2 file(s) remaining
Completed 106.7 MiB/233.2 MiB (54.1 MiB/s) with 2 file(s) remaining
Completed 106.9 MiB/233.2 MiB (54.0 MiB/s) with 2 file(s) remaining
Completed 107.2 MiB/233.2 MiB (53.8 MiB/s) with 2 file(s) remaining
Completed 107.4 MiB/233.2 MiB (53.8 MiB/s) with 2 file(s) remaining
Completed 107.7 MiB/233.2 MiB (53.8 MiB/s) with 2 file(s) remaining
Completed 107.9 MiB/233.2 MiB (53.8 MiB/s) with 2 file(s) remaining
Completed 108.2 MiB/233.2 MiB (53.7 MiB/s) with 2 file(s) remaining
Completed 108.4 MiB/233.2 MiB (53.8 MiB/s) with 2 file(s) remaining
Completed 108.7 MiB/233.2 MiB (53.6 MiB/s) with 2 file(s) remaining
Completed 108.9 MiB/233.2 MiB (53.5 MiB/s) with 2 file(s) remaining
Completed 109.2 MiB/233.2 MiB (53.6 MiB/s) with 2 file(s) remaining
Completed 109.4 MiB/233.2 MiB (53.5 MiB/s) with 2 file(s) remaining
Completed 109.7 MiB/233.2 MiB (53.5 MiB/s) with 2 file(s) remaining
Completed 109.9 MiB/233.2 MiB (53.6 MiB/s) with 2 file(s) remaining
Completed 110.2 MiB/233.2 MiB (53.6 MiB/s) with 2 file(s) remaining
Completed 110.4 MiB/233.2 MiB (53.6 MiB/s) with 2 file(s) remaining
Completed 110.7 MiB/233.2 MiB (53.6 MiB/s) with 2 file(s) remaining
Completed 110.9 MiB/233.2 MiB (53.7 MiB/s) with 2 file(s) remaining
Completed 111.2 MiB/233.2 MiB (53.6 MiB/s) with 2 file(s) remaining
Completed 111.4 MiB/233.2 MiB (53.7 MiB/s) with 2 file(s) remaining
Completed 111.7 MiB/233.2 MiB (53.7 MiB/s) with 2 file(s) remaining
Completed 111.9 MiB/233.2 MiB (53.6 MiB/s) with 2 file(s) remaining
Completed 112.2 MiB/233.2 MiB (53.7 MiB/s) with 2 file(s) remaining
Completed 112.4 MiB/233.2 MiB (53.5 MiB/s) with 2 file(s) remaining
Completed 112.7 MiB/233.2 MiB (53.6 MiB/s) with 2 file(s) remaining
Completed 112.9 MiB/233.2 MiB (53.5 MiB/s) with 2 file(s) remaining
Completed 113.2 MiB/233.2 MiB (53.5 MiB/s) with 2 file(s) remaining
Completed 113.4 MiB/233.2 MiB (53.4 MiB/s) with 2 file(s) remaining
Completed 113.7 MiB/233.2 MiB (53.5 MiB/s) with 2 file(s) remaining
Completed 113.9 MiB/233.2 MiB (53.3 MiB/s) with 2 file(s) remaining
Completed 114.2 MiB/233.2 MiB (53.2 MiB/s) with 2 file(s) remaining
Completed 114.4 MiB/233.2 MiB (53.0 MiB/s) with 2 file(s) remaining
Completed 114.7 MiB/233.2 MiB (52.9 MiB/s) with 2 file(s) remaining
Completed 114.9 MiB/233.2 MiB (52.9 MiB/s) with 2 file(s) remaining
Completed 115.2 MiB/233.2 MiB (52.8 MiB/s) with 2 file(s) remaining
Completed 115.4 MiB/233.2 MiB (52.7 MiB/s) with 2 file(s) remaining
Completed 115.7 MiB/233.2 MiB (52.6 MiB/s) with 2 file(s) remaining
Completed 115.9 MiB/233.2 MiB (52.5 MiB/s) with 2 file(s) remaining
Completed 116.2 MiB/233.2 MiB (52.4 MiB/s) with 2 file(s) remaining
Completed 116.4 MiB/233.2 MiB (52.4 MiB/s) with 2 file(s) remaining
Completed 116.7 MiB/233.2 MiB (52.2 MiB/s) with 2 file(s) remaining
Completed 116.9 MiB/233.2 MiB (52.2 MiB/s) with 2 file(s) remaining
Completed 117.2 MiB/233.2 MiB (52.2 MiB/s) with 2 file(s) remaining
Completed 117.4 MiB/233.2 MiB (52.1 MiB/s) with 2 file(s) remaining
Completed 117.7 MiB/233.2 MiB (52.1 MiB/s) with 2 file(s) remaining
Completed 117.9 MiB/233.2 MiB (52.0 MiB/s) with 2 file(s) remaining
Completed 118.2 MiB/233.2 MiB (52.0 MiB/s) with 2 file(s) remaining
Completed 118.4 MiB/233.2 MiB (52.0 MiB/s) with 2 file(s) remaining
Completed 118.7 MiB/233.2 MiB (52.1 MiB/s) with 2 file(s) remaining
Completed 118.9 MiB/233.2 MiB (52.0 MiB/s) with 2 file(s) remaining
Completed 119.2 MiB/233.2 MiB (51.9 MiB/s) with 2 file(s) remaining
Completed 119.4 MiB/233.2 MiB (52.0 MiB/s) with 2 file(s) remaining
Completed 119.7 MiB/233.2 MiB (52.0 MiB/s) with 2 file(s) remaining
Completed 119.9 MiB/233.2 MiB (51.9 MiB/s) with 2 file(s) remaining
Completed 120.2 MiB/233.2 MiB (51.8 MiB/s) with 2 file(s) remaining
Completed 120.4 MiB/233.2 MiB (51.7 MiB/s) with 2 file(s) remaining
Completed 120.7 MiB/233.2 MiB (51.7 MiB/s) with 2 file(s) remaining
Completed 120.9 MiB/233.2 MiB (51.7 MiB/s) with 2 file(s) remaining
Completed 121.2 MiB/233.2 MiB (51.7 MiB/s) with 2 file(s) remaining
Completed 121.4 MiB/233.2 MiB (51.7 MiB/s) with 2 file(s) remaining
Completed 121.7 MiB/233.2 MiB (51.7 MiB/s) with 2 file(s) remaining
Completed 121.9 MiB/233.2 MiB (51.7 MiB/s) with 2 file(s) remaining
Completed 122.2 MiB/233.2 MiB (51.7 MiB/s) with 2 file(s) remaining
Completed 122.4 MiB/233.2 MiB (51.8 MiB/s) with 2 file(s) remaining
Completed 122.7 MiB/233.2 MiB (51.9 MiB/s) with 2 file(s) remaining
Completed 122.9 MiB/233.2 MiB (51.8 MiB/s) with 2 file(s) remaining
Completed 123.2 MiB/233.2 MiB (51.8 MiB/s) with 2 file(s) remaining
Completed 123.4 MiB/233.2 MiB (51.8 MiB/s) with 2 file(s) remaining
Completed 123.7 MiB/233.2 MiB (51.8 MiB/s) with 2 file(s) remaining
Completed 123.9 MiB/233.2 MiB (51.8 MiB/s) with 2 file(s) remaining
Completed 124.2 MiB/233.2 MiB (51.8 MiB/s) with 2 file(s) remaining
Completed 124.4 MiB/233.2 MiB (51.8 MiB/s) with 2 file(s) remaining
Completed 124.7 MiB/233.2 MiB (51.9 MiB/s) with 2 file(s) remaining
Completed 124.9 MiB/233.2 MiB (52.0 MiB/s) with 2 file(s) remaining
Completed 125.2 MiB/233.2 MiB (52.0 MiB/s) with 2 file(s) remaining
Completed 125.4 MiB/233.2 MiB (52.1 MiB/s) with 2 file(s) remaining
Completed 125.7 MiB/233.2 MiB (52.2 MiB/s) with 2 file(s) remaining
Completed 125.9 MiB/233.2 MiB (52.3 MiB/s) with 2 file(s) remaining
Completed 126.2 MiB/233.2 MiB (52.3 MiB/s) with 2 file(s) remaining
Completed 126.4 MiB/233.2 MiB (52.4 MiB/s) with 2 file(s) remaining
Completed 126.7 MiB/233.2 MiB (52.5 MiB/s) with 2 file(s) remaining
Completed 126.9 MiB/233.2 MiB (52.6 MiB/s) with 2 file(s) remaining
Completed 127.2 MiB/233.2 MiB (52.7 MiB/s) with 2 file(s) remaining
Completed 127.4 MiB/233.2 MiB (52.7 MiB/s) with 2 file(s) remaining
Completed 127.7 MiB/233.2 MiB (52.8 MiB/s) with 2 file(s) remaining
Completed 127.9 MiB/233.2 MiB (52.9 MiB/s) with 2 file(s) remaining
Completed 128.2 MiB/233.2 MiB (53.0 MiB/s) with 2 file(s) remaining
Completed 128.4 MiB/233.2 MiB (53.0 MiB/s) with 2 file(s) remaining
Completed 128.7 MiB/233.2 MiB (53.1 MiB/s) with 2 file(s) remaining
Completed 128.9 MiB/233.2 MiB (53.2 MiB/s) with 2 file(s) remaining
Completed 129.2 MiB/233.2 MiB (53.3 MiB/s) with 2 file(s) remaining
Completed 129.4 MiB/233.2 MiB (53.4 MiB/s) with 2 file(s) remaining
Completed 129.7 MiB/233.2 MiB (53.4 MiB/s) with 2 file(s) remaining
Completed 129.9 MiB/233.2 MiB (53.5 MiB/s) with 2 file(s) remaining
Completed 130.2 MiB/233.2 MiB (53.6 MiB/s) with 2 file(s) remaining
Completed 130.4 MiB/233.2 MiB (53.7 MiB/s) with 2 file(s) remaining
Completed 130.7 MiB/233.2 MiB (53.8 MiB/s) with 2 file(s) remaining
Completed 130.9 MiB/233.2 MiB (53.8 MiB/s) with 2 file(s) remaining
Completed 131.2 MiB/233.2 MiB (53.9 MiB/s) with 2 file(s) remaining
Completed 131.4 MiB/233.2 MiB (54.0 MiB/s) with 2 file(s) remaining
Completed 131.7 MiB/233.2 MiB (54.1 MiB/s) with 2 file(s) remaining
Completed 131.9 MiB/233.2 MiB (54.2 MiB/s) with 2 file(s) remaining
Completed 132.2 MiB/233.2 MiB (54.3 MiB/s) with 2 file(s) remaining
Completed 132.4 MiB/233.2 MiB (54.3 MiB/s) with 2 file(s) remaining
Completed 132.7 MiB/233.2 MiB (54.4 MiB/s) with 2 file(s) remaining
Completed 132.9 MiB/233.2 MiB (54.5 MiB/s) with 2 file(s) remaining
Completed 133.2 MiB/233.2 MiB (54.6 MiB/s) with 2 file(s) remaining
Completed 133.4 MiB/233.2 MiB (54.7 MiB/s) with 2 file(s) remaining
Completed 133.7 MiB/233.2 MiB (54.7 MiB/s) with 2 file(s) remaining
Completed 133.9 MiB/233.2 MiB (54.8 MiB/s) with 2 file(s) remaining
Completed 134.2 MiB/233.2 MiB (54.9 MiB/s) with 2 file(s) remaining
Completed 134.4 MiB/233.2 MiB (55.0 MiB/s) with 2 file(s) remaining
Completed 134.7 MiB/233.2 MiB (55.0 MiB/s) with 2 file(s) remaining
Completed 134.9 MiB/233.2 MiB (54.9 MiB/s) with 2 file(s) remaining
Completed 135.2 MiB/233.2 MiB (54.6 MiB/s) with 2 file(s) remaining
Completed 135.4 MiB/233.2 MiB (54.6 MiB/s) with 2 file(s) remaining
Completed 135.7 MiB/233.2 MiB (54.3 MiB/s) with 2 file(s) remaining
Completed 135.9 MiB/233.2 MiB (54.4 MiB/s) with 2 file(s) remaining
Completed 136.2 MiB/233.2 MiB (54.4 MiB/s) with 2 file(s) remaining
Completed 136.4 MiB/233.2 MiB (54.5 MiB/s) with 2 file(s) remaining
Completed 136.7 MiB/233.2 MiB (54.1 MiB/s) with 2 file(s) remaining
Completed 136.9 MiB/233.2 MiB (54.2 MiB/s) with 2 file(s) remaining
Completed 137.2 MiB/233.2 MiB (53.3 MiB/s) with 2 file(s) remaining
Completed 137.4 MiB/233.2 MiB (53.0 MiB/s) with 2 file(s) remaining
Completed 137.7 MiB/233.2 MiB (52.6 MiB/s) with 2 file(s) remaining
Completed 137.9 MiB/233.2 MiB (52.7 MiB/s) with 2 file(s) remaining
Completed 138.2 MiB/233.2 MiB (52.8 MiB/s) with 2 file(s) remaining
Completed 138.4 MiB/233.2 MiB (52.9 MiB/s) with 2 file(s) remaining
Completed 138.7 MiB/233.2 MiB (52.9 MiB/s) with 2 file(s) remaining
Completed 138.9 MiB/233.2 MiB (53.0 MiB/s) with 2 file(s) remaining
Completed 139.2 MiB/233.2 MiB (53.1 MiB/s) with 2 file(s) remaining
Completed 139.4 MiB/233.2 MiB (53.2 MiB/s) with 2 file(s) remaining
Completed 139.7 MiB/233.2 MiB (53.3 MiB/s) with 2 file(s) remaining
Completed 139.9 MiB/233.2 MiB (53.1 MiB/s) with 2 file(s) remaining
Completed 140.2 MiB/233.2 MiB (52.7 MiB/s) with 2 file(s) remaining
Completed 140.4 MiB/233.2 MiB (52.7 MiB/s) with 2 file(s) remaining
Completed 140.7 MiB/233.2 MiB (52.8 MiB/s) with 2 file(s) remaining
Completed 140.9 MiB/233.2 MiB (52.1 MiB/s) with 2 file(s) remaining
Completed 141.2 MiB/233.2 MiB (52.2 MiB/s) with 2 file(s) remaining
Completed 141.4 MiB/233.2 MiB (51.7 MiB/s) with 2 file(s) remaining
Completed 141.7 MiB/233.2 MiB (51.8 MiB/s) with 2 file(s) remaining
Completed 141.9 MiB/233.2 MiB (51.9 MiB/s) with 2 file(s) remaining
Completed 142.2 MiB/233.2 MiB (52.0 MiB/s) with 2 file(s) remaining
Completed 142.4 MiB/233.2 MiB (52.0 MiB/s) with 2 file(s) remaining
Completed 142.7 MiB/233.2 MiB (51.3 MiB/s) with 2 file(s) remaining
Completed 142.9 MiB/233.2 MiB (50.8 MiB/s) with 2 file(s) remaining
Completed 143.2 MiB/233.2 MiB (50.7 MiB/s) with 2 file(s) remaining
Completed 143.4 MiB/233.2 MiB (50.8 MiB/s) with 2 file(s) remaining
Completed 143.7 MiB/233.2 MiB (50.9 MiB/s) with 2 file(s) remaining
Completed 143.9 MiB/233.2 MiB (50.3 MiB/s) with 2 file(s) remaining
Completed 144.2 MiB/233.2 MiB (50.3 MiB/s) with 2 file(s) remaining
Completed 144.4 MiB/233.2 MiB (50.3 MiB/s) with 2 file(s) remaining
Completed 144.7 MiB/233.2 MiB (50.1 MiB/s) with 2 file(s) remaining
Completed 144.9 MiB/233.2 MiB (49.8 MiB/s) with 2 file(s) remaining
Completed 145.2 MiB/233.2 MiB (49.8 MiB/s) with 2 file(s) remaining
Completed 145.4 MiB/233.2 MiB (49.9 MiB/s) with 2 file(s) remaining
Completed 145.7 MiB/233.2 MiB (49.8 MiB/s) with 2 file(s) remaining
Completed 145.9 MiB/233.2 MiB (49.8 MiB/s) with 2 file(s) remaining
Completed 146.2 MiB/233.2 MiB (49.8 MiB/s) with 2 file(s) remaining
Completed 146.4 MiB/233.2 MiB (49.9 MiB/s) with 2 file(s) remaining
Completed 146.7 MiB/233.2 MiB (50.0 MiB/s) with 2 file(s) remaining
Completed 146.9 MiB/233.2 MiB (49.7 MiB/s) with 2 file(s) remaining
Completed 147.2 MiB/233.2 MiB (49.8 MiB/s) with 2 file(s) remaining
Completed 147.4 MiB/233.2 MiB (49.9 MiB/s) with 2 file(s) remaining
Completed 147.7 MiB/233.2 MiB (49.9 MiB/s) with 2 file(s) remaining
Completed 147.9 MiB/233.2 MiB (50.0 MiB/s) with 2 file(s) remaining
Completed 148.2 MiB/233.2 MiB (50.1 MiB/s) with 2 file(s) remaining
Completed 148.4 MiB/233.2 MiB (50.1 MiB/s) with 2 file(s) remaining
Completed 148.7 MiB/233.2 MiB (50.1 MiB/s) with 2 file(s) remaining
Completed 148.9 MiB/233.2 MiB (50.2 MiB/s) with 2 file(s) remaining
Completed 149.2 MiB/233.2 MiB (50.3 MiB/s) with 2 file(s) remaining
Completed 149.4 MiB/233.2 MiB (50.3 MiB/s) with 2 file(s) remaining
Completed 149.7 MiB/233.2 MiB (50.4 MiB/s) with 2 file(s) remaining
Completed 149.9 MiB/233.2 MiB (49.2 MiB/s) with 2 file(s) remaining
Completed 150.2 MiB/233.2 MiB (48.5 MiB/s) with 2 file(s) remaining
Completed 150.4 MiB/233.2 MiB (47.9 MiB/s) with 2 file(s) remaining
Completed 150.7 MiB/233.2 MiB (44.7 MiB/s) with 2 file(s) remaining
Completed 150.9 MiB/233.2 MiB (44.7 MiB/s) with 2 file(s) remaining
Completed 151.2 MiB/233.2 MiB (44.8 MiB/s) with 2 file(s) remaining
Completed 151.4 MiB/233.2 MiB (44.8 MiB/s) with 2 file(s) remaining
Completed 151.7 MiB/233.2 MiB (44.9 MiB/s) with 2 file(s) remaining
Completed 151.9 MiB/233.2 MiB (45.0 MiB/s) with 2 file(s) remaining
Completed 152.2 MiB/233.2 MiB (45.0 MiB/s) with 2 file(s) remaining
Completed 152.4 MiB/233.2 MiB (45.1 MiB/s) with 2 file(s) remaining
Completed 152.7 MiB/233.2 MiB (45.2 MiB/s) with 2 file(s) remaining
Completed 152.9 MiB/233.2 MiB (45.2 MiB/s) with 2 file(s) remaining
Completed 153.2 MiB/233.2 MiB (45.3 MiB/s) with 2 file(s) remaining
Completed 153.4 MiB/233.2 MiB (45.3 MiB/s) with 2 file(s) remaining
Completed 153.7 MiB/233.2 MiB (45.4 MiB/s) with 2 file(s) remaining
Completed 153.9 MiB/233.2 MiB (45.5 MiB/s) with 2 file(s) remaining
Completed 154.2 MiB/233.2 MiB (45.5 MiB/s) with 2 file(s) remaining
Completed 154.4 MiB/233.2 MiB (45.6 MiB/s) with 2 file(s) remaining
Completed 154.7 MiB/233.2 MiB (45.7 MiB/s) with 2 file(s) remaining
Completed 154.9 MiB/233.2 MiB (45.7 MiB/s) with 2 file(s) remaining
Completed 155.2 MiB/233.2 MiB (45.8 MiB/s) with 2 file(s) remaining
Completed 155.4 MiB/233.2 MiB (45.8 MiB/s) with 2 file(s) remaining
Completed 155.7 MiB/233.2 MiB (45.9 MiB/s) with 2 file(s) remaining
Completed 155.9 MiB/233.2 MiB (45.9 MiB/s) with 2 file(s) remaining
Completed 156.2 MiB/233.2 MiB (46.0 MiB/s) with 2 file(s) remaining
Completed 156.4 MiB/233.2 MiB (46.0 MiB/s) with 2 file(s) remaining
Completed 156.7 MiB/233.2 MiB (46.1 MiB/s) with 2 file(s) remaining
Completed 156.9 MiB/233.2 MiB (46.1 MiB/s) with 2 file(s) remaining
Completed 157.2 MiB/233.2 MiB (46.2 MiB/s) with 2 file(s) remaining
Completed 157.4 MiB/233.2 MiB (46.3 MiB/s) with 2 file(s) remaining
Completed 157.7 MiB/233.2 MiB (46.3 MiB/s) with 2 file(s) remaining
Completed 157.9 MiB/233.2 MiB (46.3 MiB/s) with 2 file(s) remaining
Completed 158.2 MiB/233.2 MiB (46.4 MiB/s) with 2 file(s) remaining
Completed 158.4 MiB/233.2 MiB (46.4 MiB/s) with 2 file(s) remaining
Completed 158.7 MiB/233.2 MiB (40.7 MiB/s) with 2 file(s) remaining
Completed 158.9 MiB/233.2 MiB (40.8 MiB/s) with 2 file(s) remaining
Completed 159.2 MiB/233.2 MiB (40.8 MiB/s) with 2 file(s) remaining
Completed 159.4 MiB/233.2 MiB (40.9 MiB/s) with 2 file(s) remaining
Completed 159.7 MiB/233.2 MiB (40.9 MiB/s) with 2 file(s) remaining
Completed 159.9 MiB/233.2 MiB (41.0 MiB/s) with 2 file(s) remaining
Completed 160.2 MiB/233.2 MiB (41.0 MiB/s) with 2 file(s) remaining
Completed 160.4 MiB/233.2 MiB (39.5 MiB/s) with 2 file(s) remaining
Completed 160.7 MiB/233.2 MiB (39.1 MiB/s) with 2 file(s) remaining
Completed 160.9 MiB/233.2 MiB (38.8 MiB/s) with 2 file(s) remaining
Completed 161.2 MiB/233.2 MiB (38.8 MiB/s) with 2 file(s) remaining
Completed 161.4 MiB/233.2 MiB (38.5 MiB/s) with 2 file(s) remaining
Completed 161.7 MiB/233.2 MiB (38.6 MiB/s) with 2 file(s) remaining
Completed 161.9 MiB/233.2 MiB (38.2 MiB/s) with 2 file(s) remaining
Completed 162.2 MiB/233.2 MiB (38.3 MiB/s) with 2 file(s) remaining
Completed 162.4 MiB/233.2 MiB (37.9 MiB/s) with 2 file(s) remaining
Completed 162.7 MiB/233.2 MiB (38.0 MiB/s) with 2 file(s) remaining
Completed 162.9 MiB/233.2 MiB (37.7 MiB/s) with 2 file(s) remaining
Completed 163.2 MiB/233.2 MiB (37.7 MiB/s) with 2 file(s) remaining
Completed 163.4 MiB/233.2 MiB (37.8 MiB/s) with 2 file(s) remaining
Completed 163.7 MiB/233.2 MiB (37.5 MiB/s) with 2 file(s) remaining
Completed 163.9 MiB/233.2 MiB (37.5 MiB/s) with 2 file(s) remaining
Completed 164.2 MiB/233.2 MiB (37.2 MiB/s) with 2 file(s) remaining
Completed 164.4 MiB/233.2 MiB (37.3 MiB/s) with 2 file(s) remaining
Completed 164.7 MiB/233.2 MiB (37.3 MiB/s) with 2 file(s) remaining
Completed 164.9 MiB/233.2 MiB (37.4 MiB/s) with 2 file(s) remaining
Completed 165.2 MiB/233.2 MiB (37.4 MiB/s) with 2 file(s) remaining
Completed 165.4 MiB/233.2 MiB (37.5 MiB/s) with 2 file(s) remaining
Completed 165.7 MiB/233.2 MiB (37.5 MiB/s) with 2 file(s) remaining
Completed 165.9 MiB/233.2 MiB (37.2 MiB/s) with 2 file(s) remaining
Completed 166.2 MiB/233.2 MiB (37.3 MiB/s) with 2 file(s) remaining
Completed 166.4 MiB/233.2 MiB (37.0 MiB/s) with 2 file(s) remaining
Completed 166.7 MiB/233.2 MiB (30.7 MiB/s) with 2 file(s) remaining
Completed 166.9 MiB/233.2 MiB (30.7 MiB/s) with 2 file(s) remaining
Completed 167.2 MiB/233.2 MiB (30.7 MiB/s) with 2 file(s) remaining
Completed 167.4 MiB/233.2 MiB (30.7 MiB/s) with 2 file(s) remaining
Completed 167.7 MiB/233.2 MiB (30.7 MiB/s) with 2 file(s) remaining
Completed 167.9 MiB/233.2 MiB (30.7 MiB/s) with 2 file(s) remaining
Completed 168.2 MiB/233.2 MiB (30.7 MiB/s) with 2 file(s) remaining
Completed 168.4 MiB/233.2 MiB (30.7 MiB/s) with 2 file(s) remaining
Completed 168.7 MiB/233.2 MiB (30.7 MiB/s) with 2 file(s) remaining
Completed 168.9 MiB/233.2 MiB (30.7 MiB/s) with 2 file(s) remaining
Completed 169.2 MiB/233.2 MiB (30.7 MiB/s) with 2 file(s) remaining
Completed 169.4 MiB/233.2 MiB (30.7 MiB/s) with 2 file(s) remaining
Completed 169.7 MiB/233.2 MiB (30.7 MiB/s) with 2 file(s) remaining
Completed 169.9 MiB/233.2 MiB (30.7 MiB/s) with 2 file(s) remaining
Completed 170.2 MiB/233.2 MiB (30.7 MiB/s) with 2 file(s) remaining
Completed 170.4 MiB/233.2 MiB (30.7 MiB/s) with 2 file(s) remaining
Completed 170.7 MiB/233.2 MiB (30.7 MiB/s) with 2 file(s) remaining
Completed 170.9 MiB/233.2 MiB (30.8 MiB/s) with 2 file(s) remaining
Completed 171.2 MiB/233.2 MiB (30.8 MiB/s) with 2 file(s) remaining
Completed 171.4 MiB/233.2 MiB (30.8 MiB/s) with 2 file(s) remaining
Completed 171.7 MiB/233.2 MiB (30.8 MiB/s) with 2 file(s) remaining
Completed 171.9 MiB/233.2 MiB (30.8 MiB/s) with 2 file(s) remaining
Completed 172.2 MiB/233.2 MiB (30.8 MiB/s) with 2 file(s) remaining
Completed 172.4 MiB/233.2 MiB (30.9 MiB/s) with 2 file(s) remaining
Completed 172.7 MiB/233.2 MiB (30.9 MiB/s) with 2 file(s) remaining
Completed 172.9 MiB/233.2 MiB (30.9 MiB/s) with 2 file(s) remaining
Completed 173.2 MiB/233.2 MiB (30.8 MiB/s) with 2 file(s) remaining
Completed 173.4 MiB/233.2 MiB (30.9 MiB/s) with 2 file(s) remaining
Completed 173.7 MiB/233.2 MiB (30.8 MiB/s) with 2 file(s) remaining
Completed 173.9 MiB/233.2 MiB (30.8 MiB/s) with 2 file(s) remaining
Completed 174.2 MiB/233.2 MiB (30.9 MiB/s) with 2 file(s) remaining
Completed 174.4 MiB/233.2 MiB (30.8 MiB/s) with 2 file(s) remaining
Completed 174.7 MiB/233.2 MiB (30.8 MiB/s) with 2 file(s) remaining
Completed 174.9 MiB/233.2 MiB (30.8 MiB/s) with 2 file(s) remaining
Completed 175.2 MiB/233.2 MiB (30.8 MiB/s) with 2 file(s) remaining
Completed 175.4 MiB/233.2 MiB (30.8 MiB/s) with 2 file(s) remaining
Completed 175.7 MiB/233.2 MiB (30.8 MiB/s) with 2 file(s) remaining
Completed 175.9 MiB/233.2 MiB (30.8 MiB/s) with 2 file(s) remaining
Completed 176.2 MiB/233.2 MiB (30.8 MiB/s) with 2 file(s) remaining
Completed 176.4 MiB/233.2 MiB (30.8 MiB/s) with 2 file(s) remaining
Completed 176.7 MiB/233.2 MiB (30.8 MiB/s) with 2 file(s) remaining
Completed 176.9 MiB/233.2 MiB (30.8 MiB/s) with 2 file(s) remaining
Completed 177.2 MiB/233.2 MiB (30.8 MiB/s) with 2 file(s) remaining
Completed 177.4 MiB/233.2 MiB (30.8 MiB/s) with 2 file(s) remaining
Completed 177.7 MiB/233.2 MiB (30.8 MiB/s) with 2 file(s) remaining
Completed 177.9 MiB/233.2 MiB (30.8 MiB/s) with 2 file(s) remaining
Completed 178.2 MiB/233.2 MiB (30.8 MiB/s) with 2 file(s) remaining
Completed 178.4 MiB/233.2 MiB (30.8 MiB/s) with 2 file(s) remaining
Completed 178.7 MiB/233.2 MiB (30.8 MiB/s) with 2 file(s) remaining
Completed 178.9 MiB/233.2 MiB (30.8 MiB/s) with 2 file(s) remaining
Completed 179.2 MiB/233.2 MiB (30.8 MiB/s) with 2 file(s) remaining
Completed 179.4 MiB/233.2 MiB (30.8 MiB/s) with 2 file(s) remaining
Completed 179.7 MiB/233.2 MiB (30.8 MiB/s) with 2 file(s) remaining
Completed 179.9 MiB/233.2 MiB (30.8 MiB/s) with 2 file(s) remaining
Completed 180.2 MiB/233.2 MiB (30.8 MiB/s) with 2 file(s) remaining
Completed 180.4 MiB/233.2 MiB (30.8 MiB/s) with 2 file(s) remaining
Completed 180.7 MiB/233.2 MiB (30.8 MiB/s) with 2 file(s) remaining
Completed 180.9 MiB/233.2 MiB (30.8 MiB/s) with 2 file(s) remaining
Completed 181.2 MiB/233.2 MiB (30.8 MiB/s) with 2 file(s) remaining
Completed 181.4 MiB/233.2 MiB (30.8 MiB/s) with 2 file(s) remaining
Completed 181.7 MiB/233.2 MiB (30.8 MiB/s) with 2 file(s) remaining
Completed 181.9 MiB/233.2 MiB (30.8 MiB/s) with 2 file(s) remaining
Completed 182.2 MiB/233.2 MiB (30.8 MiB/s) with 2 file(s) remaining
Completed 182.4 MiB/233.2 MiB (30.8 MiB/s) with 2 file(s) remaining
Completed 182.7 MiB/233.2 MiB (30.8 MiB/s) with 2 file(s) remaining
Completed 182.9 MiB/233.2 MiB (30.9 MiB/s) with 2 file(s) remaining
Completed 183.2 MiB/233.2 MiB (30.9 MiB/s) with 2 file(s) remaining
Completed 183.4 MiB/233.2 MiB (30.9 MiB/s) with 2 file(s) remaining
Completed 183.7 MiB/233.2 MiB (30.9 MiB/s) with 2 file(s) remaining
Completed 183.9 MiB/233.2 MiB (30.9 MiB/s) with 2 file(s) remaining
Completed 184.2 MiB/233.2 MiB (30.9 MiB/s) with 2 file(s) remaining
Completed 184.4 MiB/233.2 MiB (30.9 MiB/s) with 2 file(s) remaining
Completed 184.7 MiB/233.2 MiB (30.9 MiB/s) with 2 file(s) remaining
Completed 184.9 MiB/233.2 MiB (31.0 MiB/s) with 2 file(s) remaining
Completed 185.2 MiB/233.2 MiB (31.0 MiB/s) with 2 file(s) remaining
Completed 185.4 MiB/233.2 MiB (31.0 MiB/s) with 2 file(s) remaining
Completed 185.7 MiB/233.2 MiB (31.0 MiB/s) with 2 file(s) remaining
Completed 185.9 MiB/233.2 MiB (31.1 MiB/s) with 2 file(s) remaining
Completed 186.2 MiB/233.2 MiB (31.1 MiB/s) with 2 file(s) remaining
Completed 186.4 MiB/233.2 MiB (31.1 MiB/s) with 2 file(s) remaining
Completed 186.7 MiB/233.2 MiB (31.1 MiB/s) with 2 file(s) remaining
Completed 186.9 MiB/233.2 MiB (31.1 MiB/s) with 2 file(s) remaining
Completed 187.2 MiB/233.2 MiB (31.1 MiB/s) with 2 file(s) remaining
Completed 187.4 MiB/233.2 MiB (31.2 MiB/s) with 2 file(s) remaining
Completed 187.7 MiB/233.2 MiB (31.2 MiB/s) with 2 file(s) remaining
Completed 187.9 MiB/233.2 MiB (31.2 MiB/s) with 2 file(s) remaining
Completed 188.2 MiB/233.2 MiB (31.2 MiB/s) with 2 file(s) remaining
Completed 188.4 MiB/233.2 MiB (31.2 MiB/s) with 2 file(s) remaining
Completed 188.7 MiB/233.2 MiB (31.2 MiB/s) with 2 file(s) remaining
Completed 188.9 MiB/233.2 MiB (31.3 MiB/s) with 2 file(s) remaining
Completed 189.2 MiB/233.2 MiB (31.3 MiB/s) with 2 file(s) remaining
Completed 189.4 MiB/233.2 MiB (31.3 MiB/s) with 2 file(s) remaining
Completed 189.7 MiB/233.2 MiB (31.3 MiB/s) with 2 file(s) remaining
Completed 189.9 MiB/233.2 MiB (31.3 MiB/s) with 2 file(s) remaining
Completed 190.2 MiB/233.2 MiB (31.3 MiB/s) with 2 file(s) remaining
Completed 190.4 MiB/233.2 MiB (31.3 MiB/s) with 2 file(s) remaining
Completed 190.7 MiB/233.2 MiB (31.4 MiB/s) with 2 file(s) remaining
Completed 190.9 MiB/233.2 MiB (31.4 MiB/s) with 2 file(s) remaining
Completed 191.2 MiB/233.2 MiB (31.4 MiB/s) with 2 file(s) remaining
Completed 191.4 MiB/233.2 MiB (31.4 MiB/s) with 2 file(s) remaining
Completed 191.7 MiB/233.2 MiB (31.4 MiB/s) with 2 file(s) remaining
Completed 191.9 MiB/233.2 MiB (31.5 MiB/s) with 2 file(s) remaining
Completed 192.2 MiB/233.2 MiB (31.5 MiB/s) with 2 file(s) remaining
Completed 192.4 MiB/233.2 MiB (31.5 MiB/s) with 2 file(s) remaining
Completed 192.7 MiB/233.2 MiB (31.5 MiB/s) with 2 file(s) remaining
Completed 192.9 MiB/233.2 MiB (31.5 MiB/s) with 2 file(s) remaining
Completed 193.2 MiB/233.2 MiB (31.6 MiB/s) with 2 file(s) remaining
Completed 193.4 MiB/233.2 MiB (31.6 MiB/s) with 2 file(s) remaining
Completed 193.7 MiB/233.2 MiB (31.6 MiB/s) with 2 file(s) remaining
Completed 193.9 MiB/233.2 MiB (31.6 MiB/s) with 2 file(s) remaining
Completed 194.2 MiB/233.2 MiB (31.6 MiB/s) with 2 file(s) remaining
Completed 194.4 MiB/233.2 MiB (31.6 MiB/s) with 2 file(s) remaining
Completed 194.7 MiB/233.2 MiB (31.7 MiB/s) with 2 file(s) remaining
Completed 194.9 MiB/233.2 MiB (31.7 MiB/s) with 2 file(s) remaining
Completed 195.2 MiB/233.2 MiB (31.6 MiB/s) with 2 file(s) remaining
Completed 195.4 MiB/233.2 MiB (31.6 MiB/s) with 2 file(s) remaining
Completed 195.7 MiB/233.2 MiB (31.6 MiB/s) with 2 file(s) remaining
Completed 195.9 MiB/233.2 MiB (31.6 MiB/s) with 2 file(s) remaining
Completed 196.2 MiB/233.2 MiB (31.6 MiB/s) with 2 file(s) remaining
Completed 196.4 MiB/233.2 MiB (31.6 MiB/s) with 2 file(s) remaining
Completed 196.7 MiB/233.2 MiB (31.6 MiB/s) with 2 file(s) remaining
Completed 196.9 MiB/233.2 MiB (31.6 MiB/s) with 2 file(s) remaining
Completed 197.2 MiB/233.2 MiB (31.6 MiB/s) with 2 file(s) remaining
Completed 197.4 MiB/233.2 MiB (31.6 MiB/s) with 2 file(s) remaining
Completed 197.7 MiB/233.2 MiB (31.6 MiB/s) with 2 file(s) remaining
Completed 197.9 MiB/233.2 MiB (31.7 MiB/s) with 2 file(s) remaining
Completed 198.2 MiB/233.2 MiB (31.7 MiB/s) with 2 file(s) remaining
Completed 198.4 MiB/233.2 MiB (31.7 MiB/s) with 2 file(s) remaining
Completed 198.7 MiB/233.2 MiB (31.7 MiB/s) with 2 file(s) remaining
Completed 198.9 MiB/233.2 MiB (31.7 MiB/s) with 2 file(s) remaining
Completed 199.2 MiB/233.2 MiB (31.7 MiB/s) with 2 file(s) remaining
Completed 199.4 MiB/233.2 MiB (31.7 MiB/s) with 2 file(s) remaining
Completed 199.7 MiB/233.2 MiB (31.7 MiB/s) with 2 file(s) remaining
Completed 199.9 MiB/233.2 MiB (31.7 MiB/s) with 2 file(s) remaining
Completed 200.2 MiB/233.2 MiB (31.7 MiB/s) with 2 file(s) remaining
Completed 200.4 MiB/233.2 MiB (31.7 MiB/s) with 2 file(s) remaining
Completed 200.7 MiB/233.2 MiB (31.8 MiB/s) with 2 file(s) remaining
Completed 200.9 MiB/233.2 MiB (31.8 MiB/s) with 2 file(s) remaining
Completed 201.2 MiB/233.2 MiB (31.8 MiB/s) with 2 file(s) remaining
Completed 201.4 MiB/233.2 MiB (31.6 MiB/s) with 2 file(s) remaining
Completed 201.7 MiB/233.2 MiB (31.6 MiB/s) with 2 file(s) remaining
Completed 201.9 MiB/233.2 MiB (31.6 MiB/s) with 2 file(s) remaining
Completed 202.2 MiB/233.2 MiB (31.6 MiB/s) with 2 file(s) remaining
Completed 202.4 MiB/233.2 MiB (31.6 MiB/s) with 2 file(s) remaining
Completed 202.7 MiB/233.2 MiB (31.6 MiB/s) with 2 file(s) remaining
Completed 202.9 MiB/233.2 MiB (31.6 MiB/s) with 2 file(s) remaining
Completed 203.2 MiB/233.2 MiB (31.7 MiB/s) with 2 file(s) remaining
Completed 203.4 MiB/233.2 MiB (31.7 MiB/s) with 2 file(s) remaining
Completed 203.7 MiB/233.2 MiB (31.7 MiB/s) with 2 file(s) remaining
Completed 203.9 MiB/233.2 MiB (31.7 MiB/s) with 2 file(s) remaining
Completed 204.2 MiB/233.2 MiB (31.7 MiB/s) with 2 file(s) remaining
Completed 204.4 MiB/233.2 MiB (31.7 MiB/s) with 2 file(s) remaining
Completed 204.7 MiB/233.2 MiB (31.7 MiB/s) with 2 file(s) remaining
Completed 204.9 MiB/233.2 MiB (31.7 MiB/s) with 2 file(s) remaining
Completed 205.2 MiB/233.2 MiB (31.7 MiB/s) with 2 file(s) remaining
Completed 205.4 MiB/233.2 MiB (31.8 MiB/s) with 2 file(s) remaining
Completed 205.7 MiB/233.2 MiB (31.8 MiB/s) with 2 file(s) remaining
Completed 205.9 MiB/233.2 MiB (31.8 MiB/s) with 2 file(s) remaining
Completed 206.2 MiB/233.2 MiB (31.8 MiB/s) with 2 file(s) remaining
Completed 206.4 MiB/233.2 MiB (31.8 MiB/s) with 2 file(s) remaining
Completed 206.7 MiB/233.2 MiB (31.8 MiB/s) with 2 file(s) remaining
Completed 206.9 MiB/233.2 MiB (31.8 MiB/s) with 2 file(s) remaining
Completed 207.2 MiB/233.2 MiB (31.8 MiB/s) with 2 file(s) remaining
Completed 207.4 MiB/233.2 MiB (31.9 MiB/s) with 2 file(s) remaining
Completed 207.7 MiB/233.2 MiB (31.9 MiB/s) with 2 file(s) remaining
Completed 207.9 MiB/233.2 MiB (31.9 MiB/s) with 2 file(s) remaining
Completed 208.2 MiB/233.2 MiB (32.0 MiB/s) with 2 file(s) remaining
Completed 208.4 MiB/233.2 MiB (32.0 MiB/s) with 2 file(s) remaining
Completed 208.7 MiB/233.2 MiB (32.0 MiB/s) with 2 file(s) remaining
Completed 208.9 MiB/233.2 MiB (32.1 MiB/s) with 2 file(s) remaining
Completed 209.2 MiB/233.2 MiB (32.1 MiB/s) with 2 file(s) remaining
Completed 209.4 MiB/233.2 MiB (32.1 MiB/s) with 2 file(s) remaining
Completed 209.7 MiB/233.2 MiB (32.2 MiB/s) with 2 file(s) remaining
Completed 209.9 MiB/233.2 MiB (32.2 MiB/s) with 2 file(s) remaining
Completed 210.2 MiB/233.2 MiB (32.2 MiB/s) with 2 file(s) remaining
Completed 210.4 MiB/233.2 MiB (32.3 MiB/s) with 2 file(s) remaining
Completed 210.7 MiB/233.2 MiB (32.3 MiB/s) with 2 file(s) remaining
Completed 210.9 MiB/233.2 MiB (32.3 MiB/s) with 2 file(s) remaining
Completed 211.2 MiB/233.2 MiB (32.4 MiB/s) with 2 file(s) remaining
Completed 211.4 MiB/233.2 MiB (32.4 MiB/s) with 2 file(s) remaining
Completed 211.7 MiB/233.2 MiB (32.4 MiB/s) with 2 file(s) remaining
Completed 211.9 MiB/233.2 MiB (32.5 MiB/s) with 2 file(s) remaining
Completed 212.2 MiB/233.2 MiB (32.5 MiB/s) with 2 file(s) remaining
Completed 212.4 MiB/233.2 MiB (32.6 MiB/s) with 2 file(s) remaining
Completed 212.7 MiB/233.2 MiB (32.6 MiB/s) with 2 file(s) remaining
Completed 212.9 MiB/233.2 MiB (32.6 MiB/s) with 2 file(s) remaining
Completed 213.2 MiB/233.2 MiB (32.7 MiB/s) with 2 file(s) remaining
Completed 213.4 MiB/233.2 MiB (32.7 MiB/s) with 2 file(s) remaining
Completed 213.7 MiB/233.2 MiB (32.7 MiB/s) with 2 file(s) remaining
Completed 213.9 MiB/233.2 MiB (32.8 MiB/s) with 2 file(s) remaining
Completed 214.2 MiB/233.2 MiB (32.8 MiB/s) with 2 file(s) remaining
Completed 214.4 MiB/233.2 MiB (32.8 MiB/s) with 2 file(s) remaining
Completed 214.7 MiB/233.2 MiB (32.9 MiB/s) with 2 file(s) remaining
Completed 214.9 MiB/233.2 MiB (32.9 MiB/s) with 2 file(s) remaining
Completed 215.2 MiB/233.2 MiB (32.9 MiB/s) with 2 file(s) remaining
Completed 215.4 MiB/233.2 MiB (32.9 MiB/s) with 2 file(s) remaining
Completed 215.7 MiB/233.2 MiB (33.0 MiB/s) with 2 file(s) remaining
Completed 215.9 MiB/233.2 MiB (33.0 MiB/s) with 2 file(s) remaining
Completed 216.2 MiB/233.2 MiB (33.0 MiB/s) with 2 file(s) remaining
Completed 216.4 MiB/233.2 MiB (33.0 MiB/s) with 2 file(s) remaining
Completed 216.7 MiB/233.2 MiB (33.0 MiB/s) with 2 file(s) remaining
Completed 216.9 MiB/233.2 MiB (33.0 MiB/s) with 2 file(s) remaining
Completed 217.2 MiB/233.2 MiB (33.0 MiB/s) with 2 file(s) remaining
Completed 217.4 MiB/233.2 MiB (33.0 MiB/s) with 2 file(s) remaining
Completed 217.7 MiB/233.2 MiB (33.0 MiB/s) with 2 file(s) remaining
Completed 217.9 MiB/233.2 MiB (33.0 MiB/s) with 2 file(s) remaining
Completed 218.2 MiB/233.2 MiB (33.0 MiB/s) with 2 file(s) remaining
Completed 218.4 MiB/233.2 MiB (33.0 MiB/s) with 2 file(s) remaining
Completed 218.7 MiB/233.2 MiB (33.0 MiB/s) with 2 file(s) remaining
Completed 218.9 MiB/233.2 MiB (33.0 MiB/s) with 2 file(s) remaining
Completed 219.2 MiB/233.2 MiB (32.9 MiB/s) with 2 file(s) remaining
Completed 219.4 MiB/233.2 MiB (32.8 MiB/s) with 2 file(s) remaining
Completed 219.7 MiB/233.2 MiB (32.7 MiB/s) with 2 file(s) remaining
Completed 219.9 MiB/233.2 MiB (32.7 MiB/s) with 2 file(s) remaining
Completed 220.2 MiB/233.2 MiB (32.7 MiB/s) with 2 file(s) remaining
Completed 220.4 MiB/233.2 MiB (32.6 MiB/s) with 2 file(s) remaining
Completed 220.7 MiB/233.2 MiB (32.7 MiB/s) with 2 file(s) remaining
Completed 220.9 MiB/233.2 MiB (32.7 MiB/s) with 2 file(s) remaining
Completed 221.2 MiB/233.2 MiB (32.7 MiB/s) with 2 file(s) remaining
Completed 221.4 MiB/233.2 MiB (32.7 MiB/s) with 2 file(s) remaining
Completed 221.7 MiB/233.2 MiB (32.8 MiB/s) with 2 file(s) remaining
Completed 221.9 MiB/233.2 MiB (32.8 MiB/s) with 2 file(s) remaining
Completed 222.2 MiB/233.2 MiB (32.8 MiB/s) with 2 file(s) remaining
Completed 222.4 MiB/233.2 MiB (32.8 MiB/s) with 2 file(s) remaining
Completed 222.7 MiB/233.2 MiB (32.8 MiB/s) with 2 file(s) remaining
Completed 222.9 MiB/233.2 MiB (32.8 MiB/s) with 2 file(s) remaining
Completed 223.2 MiB/233.2 MiB (32.8 MiB/s) with 2 file(s) remaining
Completed 223.4 MiB/233.2 MiB (32.8 MiB/s) with 2 file(s) remaining
Completed 223.7 MiB/233.2 MiB (32.8 MiB/s) with 2 file(s) remaining
Completed 223.9 MiB/233.2 MiB (32.8 MiB/s) with 2 file(s) remaining
Completed 224.2 MiB/233.2 MiB (32...Truncated

**Comment by minio-ops** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-compression-xl.sh | :heavy_check_mark: |
| mint-xl.sh | :heavy_check_mark: |
| mint-compression-dist-xl.sh | :heavy_check_mark: |
| mint-compression-fs.sh | :heavy_check_mark: |
| mint-worm.sh | :heavy_check_mark: |
| mint-dist-xl.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :x: [more...](#f5575f6c-2348-4863-ab4f-58b4107dc106) |
| mint-fs.sh | :x: [more...](#46a2f7e1-5954-4804-b861-bdaff6823cd3) |
<a name="46a2f7e1-5954-4804-b861-bdaff6823cd3"></a>
### 8027-e567389/mint-fs.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.57:32108
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 78f9e25e55d1:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... FAILED in 13 seconds
{
  "alert": "",
  "args": {
    "bucketName": "aws-sdk-go-test-heiilmxoncgiyk",
    "expiry": 60000000000,
    "objectName": "presignedTest"
  },
  "duration": 12623,
  "error": "RequestError: send request failed\ncaused by: Put http://72.28.97.57:32108/aws-sdk-go-test-heiilmxoncgiyk: dial tcp 72.28.97.57:32108: connect: no route to host",
  "function": "PresignedPut",
  "message": "AWS SDK Go CreateBucket Failed",
  "name": "aws-sdk-go",
  "status": "FAIL"
}

Executed 0 out of 14 tests successfully.
```
<a name="f5575f6c-2348-4863-ab4f-58b4107dc106"></a>
### 8027-e567389/mint-large-bucket.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.60:30751
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 25f893254475:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 3 seconds
(2/14) Running aws-sdk-java tests ... done in 2 seconds
(3/14) Running aws-sdk-php tests ... done in 48 seconds
(4/14) Running aws-sdk-ruby tests ... done in 12 seconds
(5/14) Running awscli tests ... done in 2 minutes and 23 seconds
(6/14) Running healthcheck tests ... done in 1 seconds
(7/14) Running mc tests ... FAILED in 2 minutes and 26 seconds
{
  "name": "mc",
  "duration": "107471",
  "function": "test_mirror_list_objects_storage_class",
  "status": "FAIL",
  "error": "/mint/run/core/mc/mc --config-dir /tmp/.mc-23736 --quiet --no-color mirror --storage-class REDUCED_REDUNDANCY /mint/data myminio/mc-test-bucket-1460  >>> \n`/mint/data/datafile-1-MB` -> `myminio/mc-test-bucket-1460/datafile-1-MB`\n`/mint/data/datafile-0-b` -> `myminio/mc-test-bucket-1460/datafile-0-b`\n`/mint/data/datafile-1-kB` -> `myminio/mc-test-bucket-1460/datafile-1-kB`\n`/mint/data/datafile-1-b` -> `myminio/mc-test-bucket-1460/datafile-1-b`\n`/mint/data/datafile-10-MB` -> `myminio/mc-test-bucket-1460/datafile-10-MB`\n`/mint/data/datafile-1.03-MB` -> `myminio/mc-test-bucket-1460/datafile-1.03-MB`\n`/mint/data/datafile-100-kB` -> `myminio/mc-test-bucket-1460/datafile-100-kB`\n`/mint/data/datafile-10-kB` -> `myminio/mc-test-bucket-1460/datafile-10-kB`\n`/mint/data/datafile-129-MB` -> `myminio/mc-test-bucket-1460/datafile-129-MB`\n`/mint/data/datafile-11-MB` -> `myminio/mc-test-bucket-1460/datafile-11-MB`\n`/mint/data/datafile-5-MB` -> `myminio/mc-test-bucket-1460/datafile-5-MB`\n`/mint/data/datafile-6-MB` -> `myminio/mc-test-bucket-1460/datafile-6-MB`\n`/mint/data/datafile-33-kB` -> `myminio/mc-test-bucket-1460/datafile-33-kB`\n`/mint/data/datafile-5243880-b` -> `myminio/mc-test-bucket-1460/datafile-5243880-b`\n`/mint/data/datafile-65-MB` -> `myminio/mc-test-bucket-1460/datafile-65-MB`\nmc: <ERROR> Failed to copy `/mint/data/datafile-65-MB`. Please reduce your request\nmc: <ERROR> Failed to copy `/mint/data/datafile-11-MB`. Please reduce your request\nmc: <ERROR> Failed to copy `/mint/data/datafile-129-MB`. Please reduce your request\nTotal: 233.17 MiB, Transferred: 520.42 MiB, Speed: 4.85 MiB/s"
}

Executed 6 out of 14 tests successfully.
```

File: cmd/posix-list-dir_windows.go [hunk 2]
```diff
@@ -74,7 +75,8 @@ func readDirN(dirPath string, count int) (entries []string, err error) {
 			}
 		}
 		name := syscall.UTF16ToString(data.FileName[0:])
-		if name == "." || name == ".." { // Useless names
+		fmt.Println("Windows test", name)
```
Comment (donatello) [inline cmd/posix-list-dir_windows.go]: Need the print?

File: cmd/posix-dirent_namelen_linux.go [hunk 3]
```diff
@@ -0,0 +1,41 @@
...
+	const nameBufLen = uint16(len(nameBuf))
+	limit := dirent.Reclen - fixedHdr
+	if limit > nameBufLen {
+		limit = nameBufLen
+	}
+	nameLen := bytes.IndexByte(nameBuf[:limit], 0)
+	if nameLen < 0 {
+		return 0, fmt.Errorf("failed to find terminating 0 byte in dirent")
+	}
+	return uint64(nameLen), nil
```
Comment (donatello) [inline cmd/posix-dirent_namelen_linux.go:42]: This can be done safely by `nameLen := bytes.IndexByte(dirent.Name[:], 0)` right? Why is this unsafe approach needed? A comment would be illuminating.

File: cmd/posix-list-dir_unix.go [hunk 4]
```diff
@@ -19,93 +19,56 @@
...
 
-		switch dirent.Type {
-		case syscall.DT_DIR:
-			entries = append(entries, name+SlashSeparator)
-		case syscall.DT_REG:
-			entries = append(entries, name)
-		case syscall.DT_LNK, syscall.DT_UNKNOWN:
-			// If its symbolic link, follow the link using os.Stat()
+func parseDirEnt(buf []byte) (consumed int, name string, typ os.FileMode, err error) {
+	// golang.org/issue/15653
```
Comment (donatello) [inline cmd/posix-list-dir_unix.go:37]: This issue appears to be fixed upstream - perhaps we can avoid doing the arcane unsafe stuff.

**Review by donatello — CHANGES_REQUESTED** [review]

File: cmd/posix-list-dir_windows.go (hunk 2 above)
Comment (harshavardhana) [reply cmd/posix-list-dir_windows.go]: That was for CI test will be removed @donatello

File: cmd/posix-list-dir_unix.go (hunk 4 above)
Comment (harshavardhana) [reply cmd/posix-list-dir_unix.go:37]: It is not fixed @donatello the reason we need to do is figure out the Directory, and XFS limitation on older filesystems. 

The code is directly borrowed and adding syscall.ParseDirent() is not suitable for our needs where we need to manage the right names for the directories etc.

File: cmd/posix-dirent_namelen_linux.go (hunk 3 above)
Comment (harshavardhana) [reply cmd/posix-dirent_namelen_linux.go:42]: https://github.com/golang/tools/commit/5f9a5413737ba4b4f692214aebee582b47c8be74

**Comment by minio-ops** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-compression-xl.sh | :heavy_check_mark: |
| mint-xl.sh | :heavy_check_mark: |
| mint-compression-fs.sh | :heavy_check_mark: |
| mint-worm.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :x: [more...](#c38a14f4-7738-4ed2-b43a-f9081ddc7a17) |
| mint-compression-dist-xl.sh | :x: [more...](#1588371b-24f1-4889-bcb5-4d4f322f1f9e) |
| mint-dist-xl.sh | :x: [more...](#7a7a6e71-c89d-4317-bed8-0c544e9cd2ef) |
<a name="c38a14f4-7738-4ed2-b43a-f9081ddc7a17"></a>
### 8027-605678e/mint-large-bucket.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.59:32610
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 65ccfaf642da:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 3 seconds
(2/14) Running aws-sdk-java tests ... done in 1 seconds
(3/14) Running aws-sdk-php tests ... done in 48 seconds
(4/14) Running aws-sdk-ruby tests ... done in 11 seconds
(5/14) Running awscli tests ... done in 2 minutes and 20 seconds
(6/14) Running healthcheck tests ... done in 1 seconds
(7/14) Running mc tests ... FAILED in 2 minutes and 3 seconds
{
  "name": "mc",
  "duration": "84794",
  "function": "test_mirror_list_objects_storage_class",
  "status": "FAIL",
  "error": "/mint/run/core/mc/mc --config-dir /tmp/.mc-31250 --quiet --no-color mirror --storage-class REDUCED_REDUNDANCY /mint/data myminio/mc-test-bucket-8643  >>> \n`/mint/data/datafile-1-MB` -> `myminio/mc-test-bucket-8643/datafile-1-MB`\n`/mint/data/datafile-0-b` -> `myminio/mc-test-bucket-8643/datafile-0-b`\n`/mint/data/datafile-1-b` -> `myminio/mc-test-bucket-8643/datafile-1-b`\n`/mint/data/datafile-1.03-MB` -> `myminio/mc-test-bucket-8643/datafile-1.03-MB`\n`/mint/data/datafile-1-kB` -> `myminio/mc-test-bucket-8643/datafile-1-kB`\n`/mint/data/datafile-10-kB` -> `myminio/mc-test-bucket-8643/datafile-10-kB`\n`/mint/data/datafile-10-MB` -> `myminio/mc-test-bucket-8643/datafile-10-MB`\n`/mint/data/datafile-100-kB` -> `myminio/mc-test-bucket-8643/datafile-100-kB`\n`/mint/data/datafile-11-MB` -> `myminio/mc-test-bucket-8643/datafile-11-MB`\n`/mint/data/datafile-33-kB` -> `myminio/mc-test-bucket-8643/datafile-33-kB`\n`/mint/data/datafile-129-MB` -> `myminio/mc-test-bucket-8643/datafile-129-MB`\n`/mint/data/datafile-5243880-b` -> `myminio/mc-test-bucket-8643/datafile-5243880-b`\n`/mint/data/datafile-6-MB` -> `myminio/mc-test-bucket-8643/datafile-6-MB`\n`/mint/data/datafile-5-MB` -> `myminio/mc-test-bucket-8643/datafile-5-MB`\n`/mint/data/datafile-65-MB` -> `myminio/mc-test-bucket-8643/datafile-65-MB`\nmc: <ERROR> Failed to copy `/mint/data/datafile-129-MB`. Please reduce your request\nmc: <ERROR> Failed to copy `/mint/data/datafile-10-MB`. Please reduce your request\nmc: <ERROR> Failed to copy `/mint/data/datafile-65-MB`. Please reduce your request\nmc: <ERROR> Failed to copy `/mint/data/datafile-11-MB`. Please reduce your request\nTotal: 233.17 MiB, Transferred: 543.11 MiB, Speed: 6.41 MiB/s"
}

Executed 6 out of 14 tests successfully.
```
<a name="1588371b-24f1-4889-bcb5-4d4f322f1f9e"></a>
### 8027-605678e/mint-compression-dist-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.58:31151
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 83e1e6519700:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 0 seconds
(2/14) Running aws-sdk-java tests ... done in 1 seconds
(3/14) Running aws-sdk-php tests ... done in 44 seconds
(4/14) Running aws-sdk-ruby tests ... done in 3 seconds
(5/14) Running awscli tests ... FAILED in 54 seconds
{"name": "awscli", "duration": 5811, "function": "aws --endpoint-url http://72.28.97.58:31151 s3 cp /mint/data/datafile-65-MB s3://awscli-mint-test-bucket-547/datafile-65-MB\n", "status": "FAIL", "error": "Completed 256.0 KiB/65.0 MiB (2.2 MiB/s) with 1 file(s) remaining
Completed 512.0 KiB/65.0 MiB (4.3 MiB/s) with 1 file(s) remaining
Completed 768.0 KiB/65.0 MiB (6.2 MiB/s) with 1 file(s) remaining
Completed 1.0 MiB/65.0 MiB (8.0 MiB/s) with 1 file(s) remaining  
Completed 1.2 MiB/65.0 MiB (7.5 MiB/s) with 1 file(s) remaining  
Completed 1.5 MiB/65.0 MiB (8.8 MiB/s) with 1 file(s) remaining  
Completed 1.8 MiB/65.0 MiB (10.0 MiB/s) with 1 file(s) remaining 
Completed 2.0 MiB/65.0 MiB (11.3 MiB/s) with 1 file(s) remaining 
Completed 2.2 MiB/65.0 MiB (12.5 MiB/s) with 1 file(s) remaining 
Completed 2.5 MiB/65.0 MiB (13.7 MiB/s) with 1 file(s) remaining 
Completed 2.8 MiB/65.0 MiB (14.9 MiB/s) with 1 file(s) remaining 
Completed 3.0 MiB/65.0 MiB (16.0 MiB/s) with 1 file(s) remaining 
Completed 3.2 MiB/65.0 MiB (17.1 MiB/s) with 1 file(s) remaining 
Completed 3.5 MiB/65.0 MiB (18.2 MiB/s) with 1 file(s) remaining 
Completed 3.8 MiB/65.0 MiB (19.3 MiB/s) with 1 file(s) remaining 
Completed 4.0 MiB/65.0 MiB (20.4 MiB/s) with 1 file(s) remaining 
Completed 4.2 MiB/65.0 MiB (21.5 MiB/s) with 1 file(s) remaining 
Completed 4.5 MiB/65.0 MiB (22.6 MiB/s) with 1 file(s) remaining 
Completed 4.8 MiB/65.0 MiB (23.6 MiB/s) with 1 file(s) remaining 
Completed 5.0 MiB/65.0 MiB (24.6 MiB/s) with 1 file(s) remaining 
Completed 5.2 MiB/65.0 MiB (25.6 MiB/s) with 1 file(s) remaining 
Completed 5.5 MiB/65.0 MiB (26.5 MiB/s) with 1 file(s) remaining 
Completed 5.8 MiB/65.0 MiB (27.5 MiB/s) with 1 file(s) remaining 
Completed 6.0 MiB/65.0 MiB (28.4 MiB/s) with 1 file(s) remaining 
Completed 6.2 MiB/65.0 MiB (29.3 MiB/s) with 1 file(s) remaining 
Completed 6.5 MiB/65.0 MiB (30.2 MiB/s) with 1 file(s) remaining 
Completed 6.8 MiB/65.0 MiB (31.1 MiB/s) with 1 file(s) remaining 
Completed 7.0 MiB/65.0 MiB (32.0 MiB/s) with 1 file(s) remaining 
Completed 7.2 MiB/65.0 MiB (32.8 MiB/s) with 1 file(s) remaining 
Completed 7.5 MiB/65.0 MiB (33.6 MiB/s) with 1 file(s) remaining 
Completed 7.8 MiB/65.0 MiB (34.5 MiB/s) with 1 file(s) remaining 
Completed 8.0 MiB/65.0 MiB (35.3 MiB/s) with 1 file(s) remaining 
Completed 8.2 MiB/65.0 MiB (36.1 MiB/s) with 1 file(s) remaining 
Completed 8.5 MiB/65.0 MiB (36.9 MiB/s) with 1 file(s) remaining 
Completed 8.8 MiB/65.0 MiB (37.6 MiB/s) with 1 file(s) remaining 
Completed 9.0 MiB/65.0 MiB (38.4 MiB/s) with 1 file(s) remaining 
Completed 9.2 MiB/65.0 MiB (26.8 MiB/s) with 1 file(s) remaining 
Completed 9.5 MiB/65.0 MiB (27.4 MiB/s) with 1 file(s) remaining 
Completed 9.8 MiB/65.0 MiB (27.8 MiB/s) with 1 file(s) remaining 
Completed 10.0 MiB/65.0 MiB (28.2 MiB/s) with 1 file(s) remaining
Completed 10.2 MiB/65.0 MiB (28.9 MiB/s) with 1 file(s) remaining
Completed 10.5 MiB/65.0 MiB (29.4 MiB/s) with 1 file(s) remaining
Completed 10.8 MiB/65.0 MiB (29.8 MiB/s) with 1 file(s) remaining
Completed 11.0 MiB/65.0 MiB (30.4 MiB/s) with 1 file(s) remaining
Completed 11.2 MiB/65.0 MiB (31.0 MiB/s) with 1 file(s) remaining
Completed 11.5 MiB/65.0 MiB (31.4 MiB/s) with 1 file(s) remaining
Completed 11.8 MiB/65.0 MiB (31.6 MiB/s) with 1 file(s) remaining
Completed 12.0 MiB/65.0 MiB (32.1 MiB/s) with 1 file(s) remaining
Completed 12.2 MiB/65.0 MiB (32.6 MiB/s) with 1 file(s) remaining
Completed 12.5 MiB/65.0 MiB (33.1 MiB/s) with 1 file(s) remaining
Completed 12.8 MiB/65.0 MiB (33.6 MiB/s) with 1 file(s) remaining
Completed 13.0 MiB/65.0 MiB (34.2 MiB/s) with 1 file(s) remaining
Completed 13.2 MiB/65.0 MiB (34.6 MiB/s) with 1 file(s) remaining
Completed 13.5 MiB/65.0 MiB (34.9 MiB/s) with 1 file(s) remaining
Completed 13.8 MiB/65.0 MiB (35.5 MiB/s) with 1 file(s) remaining
Completed 14.0 MiB/65.0 MiB (36.0 MiB/s) with 1 file(s) remaining
Completed 14.2 MiB/65.0 MiB (36.4 MiB/s) with 1 file(s) remaining
Completed 14.5 MiB/65.0 MiB (36.8 MiB/s) with 1 file(s) remaining
Completed 14.8 MiB/65.0 MiB (37.4 MiB/s) with 1 file(s) remaining
Completed 15.0 MiB/65.0 MiB (37.7 MiB/s) with 1 file(s) remaining
Completed 15.2 MiB/65.0 MiB (38.1 MiB/s) with 1 file(s) remaining
Completed 15.5 MiB/65.0 MiB (38.7 MiB/s) with 1 file(s) remaining
Completed 15.8 MiB/65.0 MiB (39.1 MiB/s) with 1 file(s) remaining
Completed 16.0 MiB/65.0 MiB (39.4 MiB/s) with 1 file(s) remaining
Completed 16.2 MiB/65.0 MiB (40.0 MiB/s) with 1 file(s) remaining
Completed 16.5 MiB/65.0 MiB (40.3 MiB/s) with 1 file(s) remaining
Completed 16.8 MiB/65.0 MiB (40.7 MiB/s) with 1 file(s) remaining
Completed 17.0 MiB/65.0 MiB (41.2 MiB/s) with 1 file(s) remaining
Completed 17.2 MiB/65.0 MiB (41.5 MiB/s) with 1 file(s) remaining
Completed 17.5 MiB/65.0 MiB (42.0 MiB/s) with 1 file(s) remaining
Completed 17.8 MiB/65.0 MiB (42.4 MiB/s) with 1 file(s) remaining
Completed 18.0 MiB/65.0 MiB (42.7 MiB/s) with 1 file(s) remaining
Completed 18.2 MiB/65.0 MiB (43.2 MiB/s) with 1 file(s) remaining
Completed 18.5 MiB/65.0 MiB (43.4 MiB/s) with 1 file(s) remaining
Completed 18.8 MiB/65.0 MiB (44.0 MiB/s) with 1 file(s) remaining
Completed 19.0 MiB/65.0 MiB (44.2 MiB/s) with 1 file(s) remaining
Completed 19.2 MiB/65.0 MiB (44.7 MiB/s) with 1 file(s) remaining
Completed 19.5 MiB/65.0 MiB (45.0 MiB/s) with 1 file(s) remaining
Completed 19.8 MiB/65.0 MiB (45.4 MiB/s) with 1 file(s) remaining
Completed 20.0 MiB/65.0 MiB (45.6 MiB/s) with 1 file(s) remaining
Completed 20.2 MiB/65.0 MiB (46.1 MiB/s) with 1 file(s) remaining
Completed 20.5 MiB/65.0 MiB (46.4 MiB/s) with 1 file(s) remaining
Completed 20.8 MiB/65.0 MiB (46.8 MiB/s) with 1 file(s) remaining
Completed 21.0 MiB/65.0 MiB (47.1 MiB/s) with 1 file(s) remaining
Completed 21.2 MiB/65.0 MiB (47.4 MiB/s) with 1 file(s) remaining
Completed 21.5 MiB/65.0 MiB (47.5 MiB/s) with 1 file(s) remaining
Completed 21.8 MiB/65.0 MiB (47.6 MiB/s) with 1 file(s) remaining
Completed 22.0 MiB/65.0 MiB (47.7 MiB/s) with 1 file(s) remaining
Completed 22.2 MiB/65.0 MiB (47.7 MiB/s) with 1 file(s) remaining
Completed 22.5 MiB/65.0 MiB (47.7 MiB/s) with 1 file(s) remaining
Completed 22.8 MiB/65.0 MiB (47.8 MiB/s) with 1 file(s) remaining
Completed 23.0 MiB/65.0 MiB (47.9 MiB/s) with 1 file(s) remaining
Completed 23.2 MiB/65.0 MiB (47.8 MiB/s) with 1 file(s) remaining
Completed 23.5 MiB/65.0 MiB (47.6 MiB/s) with 1 file(s) remaining
Completed 23.8 MiB/65.0 MiB (47.6 MiB/s) with 1 file(s) remaining
Completed 24.0 MiB/65.0 MiB (47.6 MiB/s) with 1 file(s) remaining
Completed 24.2 MiB/65.0 MiB (47.5 MiB/s) with 1 file(s) remaining
Completed 24.5 MiB/65.0 MiB (47.3 MiB/s) with 1 file(s) remaining
Completed 24.8 MiB/65.0 MiB (47.1 MiB/s) with 1 file(s) remaining
Completed 25.0 MiB/65.0 MiB (47.0 MiB/s) with 1 file(s) remaining
Completed 25.2 MiB/65.0 MiB (46.7 MiB/s) with 1 file(s) remaining
Completed 25.5 MiB/65.0 MiB (44.9 MiB/s) with 1 file(s) remaining
Completed 25.8 MiB/65.0 MiB (44.8 MiB/s) with 1 file(s) remaining
Completed 26.0 MiB/65.0 MiB (44.2 MiB/s) with 1 file(s) remaining
Completed 26.2 MiB/65.0 MiB (44.4 MiB/s) with 1 file(s) remaining
Completed 26.5 MiB/65.0 MiB (43.7 MiB/s) with 1 file(s) remaining
Completed 26.8 MiB/65.0 MiB (43.9 MiB/s) with 1 file(s) remaining
Completed 27.0 MiB/65.0 MiB (43.4 MiB/s) with 1 file(s) remaining
Completed 27.2 MiB/65.0 MiB (43.8 MiB/s) with 1 file(s) remaining
Completed 27.5 MiB/65.0 MiB (43.4 MiB/s) with 1 file(s) remaining
Completed 27.8 MiB/65.0 MiB (43.7 MiB/s) with 1 file(s) remaining
Completed 28.0 MiB/65.0 MiB (43.4 MiB/s) with 1 file(s) remaining
Completed 28.2 MiB/65.0 MiB (43.8 MiB/s) with 1 file(s) remaining
Completed 28.5 MiB/65.0 MiB (43.6 MiB/s) with 1 file(s) remaining
Completed 28.8 MiB/65.0 MiB (43.9 MiB/s) with 1 file(s) remaining
Completed 29.0 MiB/65.0 MiB (43.8 MiB/s) with 1 file(s) remaining
Completed 29.2 MiB/65.0 MiB (44.1 MiB/s) with 1 file(s) remaining
Completed 29.5 MiB/65.0 MiB (44.1 MiB/s) with 1 file(s) remaining
Completed 29.8 MiB/65.0 MiB (44.5 MiB/s) with 1 file(s) remaining
Completed 30.0 MiB/65.0 MiB (44.5 MiB/s) with 1 file(s) remaining
Completed 30.2 MiB/65.0 MiB (44.8 MiB/s) with 1 file(s) remaining
Completed 30.5 MiB/65.0 MiB (44.8 MiB/s) with 1 file(s) remaining
Completed 30.8 MiB/65.0 MiB (45.1 MiB/s) with 1 file(s) remaining
Completed 31.0 MiB/65.0 MiB (45.3 MiB/s) with 1 file(s) remaining
Completed 31.2 MiB/65.0 MiB (45.6 MiB/s) with 1 file(s) remaining
Completed 31.5 MiB/65.0 MiB (45.7 MiB/s) with 1 file(s) remaining
Completed 31.8 MiB/65.0 MiB (46.1 MiB/s) with 1 file(s) remaining
Completed 32.0 MiB/65.0 MiB (46.2 MiB/s) with 1 file(s) remaining
Completed 32.2 MiB/65.0 MiB (46.5 MiB/s) with 1 file(s) remaining
Completed 32.5 MiB/65.0 MiB (46.7 MiB/s) with 1 file(s) remaining
Completed 32.8 MiB/65.0 MiB (47.0 MiB/s) with 1 file(s) remaining
Completed 33.0 MiB/65.0 MiB (47.1 MiB/s) with 1 file(s) remaining
Completed 33.2 MiB/65.0 MiB (47.4 MiB/s) with 1 file(s) remaining
Completed 33.5 MiB/65.0 MiB (47.6 MiB/s) with 1 file(s) remaining
Completed 33.8 MiB/65.0 MiB (47.8 MiB/s) with 1 file(s) remaining
Completed 34.0 MiB/65.0 MiB (48.0 MiB/s) with 1 file(s) remaining
Completed 34.2 MiB/65.0 MiB (48.2 MiB/s) with 1 file(s) remaining
Completed 34.5 MiB/65.0 MiB (48.3 MiB/s) with 1 file(s) remaining
Completed 34.8 MiB/65.0 MiB (48.7 MiB/s) with 1 file(s) remaining
Completed 35.0 MiB/65.0 MiB (48.8 MiB/s) with 1 file(s) remaining
Completed 35.2 MiB/65.0 MiB (49.0 MiB/s) with 1 file(s) remaining
Completed 35.5 MiB/65.0 MiB (49.1 MiB/s) with 1 file(s) remaining
Completed 35.8 MiB/65.0 MiB (49.4 MiB/s) with 1 file(s) remaining
Completed 36.0 MiB/65.0 MiB (49.6 MiB/s) with 1 file(s) remaining
Completed 36.2 MiB/65.0 MiB (49.8 MiB/s) with 1 file(s) remaining
Completed 36.5 MiB/65.0 MiB (50.0 MiB/s) with 1 file(s) remaining
Completed 36.8 MiB/65.0 MiB (50.1 MiB/s) with 1 file(s) remaining
Completed 37.0 MiB/65.0 MiB (50.4 MiB/s) with 1 file(s) remaining
Completed 37.2 MiB/65.0 MiB (50.5 MiB/s) with 1 file(s) remaining
Completed 37.5 MiB/65.0 MiB (50.8 MiB/s) with 1 file(s) remaining
Completed 37.8 MiB/65.0 MiB (50.8 MiB/s) with 1 file(s) remaining
Completed 38.0 MiB/65.0 MiB (51.1 MiB/s) with 1 file(s) remaining
Completed 38.2 MiB/65.0 MiB (51.2 MiB/s) with 1 file(s) remaining
Completed 38.5 MiB/65.0 MiB (51.5 MiB/s) with 1 file(s) remaining
Completed 38.8 MiB/65.0 MiB (51.6 MiB/s) with 1 file(s) remaining
Completed 39.0 MiB/65.0 MiB (51.8 MiB/s) with 1 file(s) remaining
Completed 39.2 MiB/65.0 MiB (52.0 MiB/s) with 1 file(s) remaining
Completed 39.5 MiB/65.0 MiB (52.2 MiB/s) with 1 file(s) remaining
Completed 39.8 MiB/65.0 MiB (52.3 MiB/s) with 1 file(s) remaining
Completed 40.0 MiB/65.0 MiB (52.5 MiB/s) with 1 file(s) remaining
Completed 40.2 MiB/65.0 MiB (52.7 MiB/s) with 1 file(s) remaining
Completed 40.5 MiB/65.0 MiB (52.8 MiB/s) with 1 file(s) remaining
Completed 40.8 MiB/65.0 MiB (52.8 MiB/s) with 1 file(s) remaining
Completed 41.0 MiB/65.0 MiB (52.8 MiB/s) with 1 file(s) remaining
Completed 41.2 MiB/65.0 MiB (36.1 MiB/s) with 1 file(s) remaining
Completed 41.5 MiB/65.0 MiB (36.3 MiB/s) with 1 file(s) remaining
Completed 41.8 MiB/65.0 MiB (33.3 MiB/s) with 1 file(s) remaining
Completed 42.0 MiB/65.0 MiB (15.5 MiB/s) with 1 file(s) remaining
Completed 42.2 MiB/65.0 MiB (15.6 MiB/s) with 1 file(s) remaining
Completed 42.5 MiB/65.0 MiB (15.6 MiB/s) with 1 file(s) remaining
Completed 42.8 MiB/65.0 MiB (15.7 MiB/s) with 1 file(s) remaining
Completed 43.0 MiB/65.0 MiB (15.8 MiB/s) with 1 file(s) remaining
Completed 43.2 MiB/65.0 MiB (15.9 MiB/s) with 1 file(s) remaining
Completed 43.5 MiB/65.0 MiB (15.9 MiB/s) with 1 file(s) remaining
Completed 43.8 MiB/65.0 MiB (16.0 MiB/s) with 1 file(s) remaining
Completed 44.0 MiB/65.0 MiB (16.1 MiB/s) with 1 file(s) remaining
Completed 44.2 MiB/65.0 MiB (16.2 MiB/s) with 1 file(s) remaining
Completed 44.5 MiB/65.0 MiB (16.3 MiB/s) with 1 file(s) remaining
Completed 44.8 MiB/65.0 MiB (16.3 MiB/s) with 1 file(s) remaining
Completed 45.0 MiB/65.0 MiB (16.4 MiB/s) with 1 file(s) remaining
Completed 45.2 MiB/65.0 MiB (16.5 MiB/s) with 1 file(s) remaining
Completed 45.5 MiB/65.0 MiB (16.6 MiB/s) with 1 file(s) remaining
Completed 45.8 MiB/65.0 MiB (16.7 MiB/s) with 1 file(s) remaining
Completed 46.0 MiB/65.0 MiB (16.7 MiB/s) with 1 file(s) remaining
Completed 46.2 MiB/65.0 MiB (16.8 MiB/s) with 1 file(s) remaining
Completed 46.5 MiB/65.0 MiB (16.9 MiB/s) with 1 file(s) remaining
Completed 46.8 MiB/65.0 MiB (17.0 MiB/s) with 1 file(s) remaining
Completed 47.0 MiB/65.0 MiB (17.1 MiB/s) with 1 file(s) remaining
Completed 47.2 MiB/65.0 MiB (17.1 MiB/s) with 1 file(s) remaining
Completed 47.5 MiB/65.0 MiB (17.2 MiB/s) with 1 file(s) remaining
Completed 47.8 MiB/65.0 MiB (17.3 MiB/s) with 1 file(s) remaining
Completed 48.0 MiB/65.0 MiB (17.4 MiB/s) with 1 file(s) remaining
Completed 48.2 MiB/65.0 MiB (17.4 MiB/s) with 1 file(s) remaining
Completed 48.5 MiB/65.0 MiB (17.5 MiB/s) with 1 file(s) remaining
Completed 48.8 MiB/65.0 MiB (17.6 MiB/s) with 1 file(s) remaining
Completed 49.0 MiB/65.0 MiB (17.7 MiB/s) with 1 file(s) remaining
Completed 49.2 MiB/65.0 MiB (17.8 MiB/s) with 1 file(s) remaining
Completed 49.5 MiB/65.0 MiB (17.8 MiB/s) with 1 file(s) remaining
Completed 49.8 MiB/65.0 MiB (17.4 MiB/s) with 1 file(s) remaining
Completed 50.0 MiB/65.0 MiB (17.5 MiB/s) with 1 file(s) remaining
Completed 50.2 MiB/65.0 MiB (17.6 MiB/s) with 1 file(s) remaining
Completed 50.5 MiB/65.0 MiB (17.6 MiB/s) with 1 file(s) remaining
Completed 50.8 MiB/65.0 MiB (17.7 MiB/s) with 1 file(s) remaining
Completed 51.0 MiB/65.0 MiB (17.7 MiB/s) with 1 file(s) remaining
Completed 51.2 MiB/65.0 MiB (17.8 MiB/s) with 1 file(s) remaining
Completed 51.5 MiB/65.0 MiB (17.9 MiB/s) with 1 file(s) remaining
Completed 51.8 MiB/65.0 MiB (17.9 MiB/s) with 1 file(s) remaining
Completed 52.0 MiB/65.0 MiB (18.0 MiB/s) with 1 file(s) remaining
Completed 52.2 MiB/65.0 MiB (18.0 MiB/s) with 1 file(s) remaining
Completed 52.5 MiB/65.0 MiB (18.1 MiB/s) with 1 file(s) remaining
Completed 52.8 MiB/65.0 MiB (18.2 MiB/s) with 1 file(s) remaining
Completed 53.0 MiB/65.0 MiB (18.2 MiB/s) with 1 file(s) remaining
Completed 53.2 MiB/65.0 MiB (18.3 MiB/s) with 1 file(s) remaining
Completed 53.5 MiB/65.0 MiB (18.3 MiB/s) with 1 file(s) remaining
Completed 53.8 MiB/65.0 MiB (18.4 MiB/s) with 1 file(s) remaining
Completed 54.0 MiB/65.0 MiB (18.5 MiB/s) with 1 file(s) remaining
Completed 54.2 MiB/65.0 MiB (18.5 MiB/s) with 1 file(s) remaining
Completed 54.5 MiB/65.0 MiB (18.6 MiB/s) with 1 file(s) remaining
Completed 54.8 MiB/65.0 MiB (18.6 MiB/s) with 1 file(s) remaining
Completed 55.0 MiB/65.0 MiB (18.7 MiB/s) with 1 file(s) remaining
Completed 55.2 MiB/65.0 MiB (18.8 MiB/s) with 1 file(s) remaining
Completed 55.5 MiB/65.0 MiB (18.9 MiB/s) with 1 file(s) remaining
Completed 55.8 MiB/65.0 MiB (18.9 MiB/s) with 1 file(s) remaining
Completed 56.0 MiB/65.0 MiB (19.0 MiB/s) with 1 file(s) remaining
Completed 56.2 MiB/65.0 MiB (19.1 MiB/s) with 1 file(s) remaining
Completed 56.5 MiB/65.0 MiB (19.1 MiB/s) with 1 file(s) remaining
Completed 56.8 MiB/65.0 MiB (19.2 MiB/s) with 1 file(s) remaining
Completed 57.0 MiB/65.0 MiB (19.3 MiB/s) with 1 file(s) remaining
Completed 57.2 MiB/65.0 MiB (19.3 MiB/s) with 1 file(s) remaining
Completed 57.5 MiB/65.0 MiB (19.3 MiB/s) with 1 file(s) remaining
Completed 57.8 MiB/65.0 MiB (19.3 MiB/s) with 1 file(s) remaining
Completed 58.0 MiB/65.0 MiB (19.4 MiB/s) with 1 file(s) remaining
Completed 58.2 MiB/65.0 MiB (19.5 MiB/s) with 1 file(s) remaining
Completed 58.5 MiB/65.0 MiB (19.5 MiB/s) with 1 file(s) remaining
Completed 58.8 MiB/65.0 MiB (19.6 MiB/s) with 1 file(s) remaining
Completed 59.0 MiB/65.0 MiB (19.6 MiB/s) with 1 file(s) remaining
Completed 59.2 MiB/65.0 MiB (19.7 MiB/s) with 1 file(s) remaining
Completed 59.5 MiB/65.0 MiB (19.8 MiB/s) with 1 file(s) remaining
Completed 59.8 MiB/65.0 MiB (19.8 MiB/s) with 1 file(s) remaining
Completed 60.0 MiB/65.0 MiB (19.9 MiB/s) with 1 file(s) remaining
Completed 60.2 MiB/65.0 MiB (20.0 MiB/s) with 1 file(s) remaining
Completed 60.5 MiB/65.0 MiB (20.0 MiB/s) with 1 file(s) remaining
Completed 60.8 MiB/65.0 MiB (20.1 MiB/s) with 1 file(s) remaining
Completed 61.0 MiB/65.0 MiB (20.1 MiB/s) with 1 file(s) remaining
Completed 61.2 MiB/65.0 MiB (20.2 MiB/s) with 1 file(s) remaining
Completed 61.5 MiB/65.0 MiB (20.3 MiB/s) with 1 file(s) remaining
Completed 61.8 MiB/65.0 MiB (20.3 MiB/s) with 1 file(s) remaining
Completed 62.0 MiB/65.0 MiB (20.4 MiB/s) with 1 file(s) remaining
Completed 62.2 MiB/65.0 MiB (20.4 MiB/s) with 1 file(s) remaining
Completed 62.5 MiB/65.0 MiB (20.5 MiB/s) with 1 file(s) remaining
Completed 62.8 MiB/65.0 MiB (20.5 MiB/s) with 1 file(s) remaining
Completed 63.0 MiB/65.0 MiB (20.6 MiB/s) with 1 file(s) remaining
Completed 63.2 MiB/65.0 MiB (20.7 MiB/s) with 1 file(s) remaining
Completed 63.5 MiB/65.0 MiB (20.7 MiB/s) with 1 file(s) remaining
Completed 63.8 MiB/65.0 MiB (20.8 MiB/s) with 1 file(s) remaining
Completed 64.0 MiB/65.0 MiB (20.8 MiB/s) with 1 file(s) remaining
Completed 64.2 MiB/65.0 MiB (20.9 MiB/s) with 1 file(s) remaining
Completed 64.5 MiB/65.0 MiB (20.9 MiB/s) with 1 file(s) remaining
Completed 64.8 MiB/65.0 MiB (21.0 MiB/s) with 1 file(s) remaining
Completed 65.0 MiB/65.0 MiB (21.0 MiB/s) with 1 file(s) remaining
upload failed: ../../../data/datafile-65-MB to s3://awscli-mint-test-bucket-547/datafile-65-MB An error occurred (InvalidPart) when calling the CompleteMultipartUpload operation: One or more of the specified parts could not be found.  The part may not have been uploaded, or the specified entity tag may not match the part's entity tag."}

Executed 4 out of 14 tests successfully.
```
<a name="7a7a6e71-c89d-4317-bed8-0c544e9cd2ef"></a>
### 8027-605678e/mint-dist-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.57:31291
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 850af05915a4:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... FAILED in 13 seconds
{
  "alert": "",
  "args": {
    "bucketName": "aws-sdk-go-test-cb5zgvagthqb0b",
    "expiry": 60000000000,
    "objectName": "presignedTest"
  },
  "duration": 12509,
  "error": "RequestError: send request failed\ncaused by: Put http://72.28.97.57:31291/aws-sdk-go-test-cb5zgvagthqb0b: dial tcp 72.28.97.57:31291: connect: no route to host",
  "function": "PresignedPut",
  "message": "AWS SDK Go CreateBucket Failed",
  "name": "aws-sdk-go",
  "status": "FAIL"
}

Executed 0 out of 14 tests successfully.
```

**Review by donatello — APPROVED** [review]

**Comment by minio-ops** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-xl.sh | :heavy_check_mark: |
| mint-compression-dist-xl.sh | :heavy_check_mark: |
| mint-compression-fs.sh | :heavy_check_mark: |
| mint-worm.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-dist-xl.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-compression-xl.sh | :x: [more...](#a7ebf2d9-2776-46a3-b745-539557ae8d7b) |
| mint-large-bucket.sh | :x: [more...](#7ac80d20-9aa1-4d54-8b8e-0e225990cad5) |
<a name="7ac80d20-9aa1-4d54-8b8e-0e225990cad5"></a>
### 8027-1f3cde6/mint-large-bucket.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.61:32173
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp e0ef875b203c:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 7 seconds
(2/14) Running aws-sdk-java tests ... done in 2 seconds
(3/14) Running aws-sdk-php tests ... done in 51 seconds
(4/14) Running aws-sdk-ruby tests ... done in 14 seconds
(5/14) Running awscli tests ... done in 2 minutes and 33 seconds
(6/14) Running healthcheck tests ... done in 0 seconds
(7/14) Running mc tests ... FAILED in 2 minutes and 31 seconds
{
  "name": "mc",
  "duration": "113841",
  "function": "test_mirror_list_objects_storage_class",
  "status": "FAIL",
  "error": "/mint/run/core/mc/mc --config-dir /tmp/.mc-16140 --quiet --no-color mirror --storage-class REDUCED_REDUNDANCY /mint/data myminio/mc-test-bucket-29091  >>> \n`/mint/data/datafile-1-MB` -> `myminio/mc-test-bucket-29091/datafile-1-MB`\n`/mint/data/datafile-0-b` -> `myminio/mc-test-bucket-29091/datafile-0-b`\n`/mint/data/datafile-1-b` -> `myminio/mc-test-bucket-29091/datafile-1-b`\n`/mint/data/datafile-1.03-MB` -> `myminio/mc-test-bucket-29091/datafile-1.03-MB`\n`/mint/data/datafile-1-kB` -> `myminio/mc-test-bucket-29091/datafile-1-kB`\n`/mint/data/datafile-10-kB` -> `myminio/mc-test-bucket-29091/datafile-10-kB`\n`/mint/data/datafile-10-MB` -> `myminio/mc-test-bucket-29091/datafile-10-MB`\n`/mint/data/datafile-33-kB` -> `myminio/mc-test-bucket-29091/datafile-33-kB`\n`/mint/data/datafile-100-kB` -> `myminio/mc-test-bucket-29091/datafile-100-kB`\n`/mint/data/datafile-11-MB` -> `myminio/mc-test-bucket-29091/datafile-11-MB`\n`/mint/data/datafile-129-MB` -> `myminio/mc-test-bucket-29091/datafile-129-MB`\n`/mint/data/datafile-5243880-b` -> `myminio/mc-test-bucket-29091/datafile-5243880-b`\n`/mint/data/datafile-6-MB` -> `myminio/mc-test-bucket-29091/datafile-6-MB`\n`/mint/data/datafile-5-MB` -> `myminio/mc-test-bucket-29091/datafile-5-MB`\n`/mint/data/datafile-65-MB` -> `myminio/mc-test-bucket-29091/datafile-65-MB`\nmc: <ERROR> Failed to copy `/mint/data/datafile-65-MB`. Please reduce your request\nmc: <ERROR> Failed to copy `/mint/data/datafile-129-MB`. Please reduce your request\nmc: <ERROR> Failed to copy `/mint/data/datafile-11-MB`. Please reduce your request\nmc: <ERROR> Failed to copy `/mint/data/datafile-10-MB`. Please reduce your request\nTotal: 233.17 MiB, Transferred: 508.52 MiB, Speed: 4.47 MiB/s"
}

Executed 6 out of 14 tests successfully.
```
<a name="a7ebf2d9-2776-46a3-b745-539557ae8d7b"></a>
### 8027-1f3cde6/mint-compression-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.51:31952
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp c383511907af:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... FAILED in 6 minutes and 0 seconds
{
  "alert": "",
  "args": {
    "bucketName": "aws-sdk-go-test-e30eweqesnaaab",
    "expiry": 60000000000,
    "objectName": "presignedTest"
  },
  "duration": 360022,
  "error": "XMinioServerNotInitialized: Server not initialized, please try again.\n\tstatus code: 503, request id: 15B8BF3075710A47, host id: ",
  "function": "PresignedPut",
  "message": "AWS SDK Go CreateBucket Failed",
  "name": "aws-sdk-go",
  "status": "FAIL"
}

Executed 0 out of 14 tests successfully.
```

**Comment by minio-ops** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-compression-xl.sh | :heavy_check_mark: |
| mint-xl.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-compression-dist-xl.sh | :heavy_check_mark: |
| mint-worm.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-compression-fs.sh | :x: [more...](#ce8bb1bd-4d13-4ee4-a715-3768ee513791) |
| mint-dist-xl.sh | :x: [more...](#c044cc33-c96c-4fcc-8f6e-215aff3802fd) |
<a name="c044cc33-c96c-4fcc-8f6e-215aff3802fd"></a>
### 8027-cf64ea3/mint-dist-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.59:32540
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 21a1eb8385c0:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 1 seconds
(2/14) Running aws-sdk-java tests ... done in 1 seconds
(3/14) Running aws-sdk-php tests ... done in 48 seconds
(4/14) Running aws-sdk-ruby tests ... done in 5 seconds
(5/14) Running awscli tests ... FAILED in 1 minutes and 58 seconds
{"name": "awscli", "duration": 67403, "function": "aws --endpoint-url http://72.28.97.59:32540 s3 sync /mint/data s3://awscli-mint-test-bucket-28058/\n", "status": "FAIL", "error": "Completed 256.0 KiB/233.2 MiB (4.8 MiB/s) with 15 file(s) remaining
Completed 512.0 KiB/233.2 MiB (9.5 MiB/s) with 15 file(s) remaining
Completed 768.0 KiB/233.2 MiB (14.1 MiB/s) with 15 file(s) remaining
Completed 1.0 MiB/233.2 MiB (17.6 MiB/s) with 15 file(s) remaining  
Completed 1.2 MiB/233.2 MiB (21.7 MiB/s) with 15 file(s) remaining  
Completed 1.5 MiB/233.2 MiB (25.7 MiB/s) with 15 file(s) remaining  
Completed 1.8 MiB/233.2 MiB (29.6 MiB/s) with 15 file(s) remaining  
Completed 2.0 MiB/233.2 MiB (33.5 MiB/s) with 15 file(s) remaining  
upload: ../../../data/datafile-0-b to s3://awscli-mint-test-bucket-28058/datafile-0-bCompleted 2.0 MiB/233.2 MiB (33.5 MiB/s) with 14 file(s) remaining
Completed 2.0 MiB/233.2 MiB (19.5 MiB/s) with 14 file(s) remaining
upload: ../../../data/datafile-1-b to s3://awscli-mint-test-bucket-28058/datafile-1-bCompleted 2.0 MiB/233.2 MiB (19.5 MiB/s) with 13 file(s) remaining
Completed 2.0 MiB/233.2 MiB (13.3 MiB/s) with 13 file(s) remaining
upload: ../../../data/datafile-1-kB to s3://awscli-mint-test-bucket-28058/datafile-1-kBCompleted 2.0 MiB/233.2 MiB (13.3 MiB/s) with 12 file(s) remaining
upload: ../../../data/datafile-1-MB to s3://awscli-mint-test-bucket-28058/datafile-1-MBCompleted 2.0 MiB/233.2 MiB (13.3 MiB/s) with 11 file(s) remaining
Completed 2.0 MiB/233.2 MiB (12.9 MiB/s) with 11 file(s) remaining
upload: ../../../data/datafile-1.03-MB to s3://awscli-mint-test-bucket-28058/datafile-1.03-MBCompleted 2.0 MiB/233.2 MiB (12.9 MiB/s) with 10 file(s) remaining
Completed 2.1 MiB/233.2 MiB (13.2 MiB/s) with 10 file(s) remaining
upload: ../../../data/datafile-100-kB to s3://awscli-mint-test-bucket-28058/datafile-100-kBCompleted 2.1 MiB/233.2 MiB (13.2 MiB/s) with 9 file(s) remaining
Completed 2.1 MiB/233.2 MiB (12.5 MiB/s) with 9 file(s) remaining
upload: ../../../data/datafile-10-kB to s3://awscli-mint-test-bucket-28058/datafile-10-kBCompleted 2.1 MiB/233.2 MiB (12.5 MiB/s) with 8 file(s) remaining
Completed 2.2 MiB/233.2 MiB (11.6 MiB/s) with 8 file(s) remaining
upload: ../../../data/datafile-33-kB to s3://awscli-mint-test-bucket-28058/datafile-33-kBCompleted 2.2 MiB/233.2 MiB (11.6 MiB/s) with 7 file(s) remaining
Completed 2.4 MiB/233.2 MiB (11.3 MiB/s) with 7 file(s) remaining
Completed 2.7 MiB/233.2 MiB (12.4 MiB/s) with 7 file(s) remaining
Completed 2.9 MiB/233.2 MiB (13.5 MiB/s) with 7 file(s) remaining
Completed 3.2 MiB/233.2 MiB (14.6 MiB/s) with 7 file(s) remaining
Completed 3.4 MiB/233.2 MiB (15.7 MiB/s) with 7 file(s) remaining
Completed 3.7 MiB/233.2 MiB (16.7 MiB/s) with 7 file(s) remaining
Completed 3.9 MiB/233.2 MiB (17.7 MiB/s) with 7 file(s) remaining
Completed 4.2 MiB/233.2 MiB (18.3 MiB/s) with 7 file(s) remaining
Completed 4.4 MiB/233.2 MiB (19.4 MiB/s) with 7 file(s) remaining
Completed 4.7 MiB/233.2 MiB (20.3 MiB/s) with 7 file(s) remaining
Completed 4.9 MiB/233.2 MiB (21.2 MiB/s) with 7 file(s) remaining
Completed 5.2 MiB/233.2 MiB (22.1 MiB/s) with 7 file(s) remaining
Completed 5.4 MiB/233.2 MiB (23.1 MiB/s) with 7 file(s) remaining
Completed 5.7 MiB/233.2 MiB (24.1 MiB/s) with 7 file(s) remaining
Completed 5.9 MiB/233.2 MiB (24.8 MiB/s) with 7 file(s) remaining
Completed 6.2 MiB/233.2 MiB (25.9 MiB/s) with 7 file(s) remaining
Completed 6.4 MiB/233.2 MiB (26.7 MiB/s) with 7 file(s) remaining
Completed 6.7 MiB/233.2 MiB (27.7 MiB/s) with 7 file(s) remaining
Completed 6.9 MiB/233.2 MiB (28.5 MiB/s) with 7 file(s) remaining
Completed 7.2 MiB/233.2 MiB (29.4 MiB/s) with 7 file(s) remaining
Completed 7.4 MiB/233.2 MiB (30.0 MiB/s) with 7 file(s) remaining
Completed 7.7 MiB/233.2 MiB (30.9 MiB/s) with 7 file(s) remaining
Completed 7.9 MiB/233.2 MiB (31.4 MiB/s) with 7 file(s) remaining
Completed 8.2 MiB/233.2 MiB (32.4 MiB/s) with 7 file(s) remaining
Completed 8.4 MiB/233.2 MiB (32.8 MiB/s) with 7 file(s) remaining
Completed 8.7 MiB/233.2 MiB (33.7 MiB/s) with 7 file(s) remaining
Completed 8.9 MiB/233.2 MiB (34.2 MiB/s) with 7 file(s) remaining
Completed 9.2 MiB/233.2 MiB (35.0 MiB/s) with 7 file(s) remaining
Completed 9.4 MiB/233.2 MiB (35.9 MiB/s) with 7 file(s) remaining
Completed 9.7 MiB/233.2 MiB (36.7 MiB/s) with 7 file(s) remaining
Completed 9.9 MiB/233.2 MiB (37.2 MiB/s) with 7 file(s) remaining
Completed 10.2 MiB/233.2 MiB (38.1 MiB/s) with 7 file(s) remaining
Completed 10.4 MiB/233.2 MiB (38.9 MiB/s) with 7 file(s) remaining
Completed 10.7 MiB/233.2 MiB (39.7 MiB/s) with 7 file(s) remaining
Completed 10.9 MiB/233.2 MiB (40.1 MiB/s) with 7 file(s) remaining
Completed 11.2 MiB/233.2 MiB (40.9 MiB/s) with 7 file(s) remaining
Completed 11.4 MiB/233.2 MiB (41.1 MiB/s) with 7 file(s) remaining
Completed 11.7 MiB/233.2 MiB (41.9 MiB/s) with 7 file(s) remaining
Completed 11.9 MiB/233.2 MiB (42.7 MiB/s) with 7 file(s) remaining
Completed 12.2 MiB/233.2 MiB (43.4 MiB/s) with 7 file(s) remaining
Completed 12.4 MiB/233.2 MiB (44.0 MiB/s) with 7 file(s) remaining
Completed 12.7 MiB/233.2 MiB (44.7 MiB/s) with 7 file(s) remaining
Completed 12.9 MiB/233.2 MiB (45.5 MiB/s) with 7 file(s) remaining
Completed 13.2 MiB/233.2 MiB (46.3 MiB/s) with 7 file(s) remaining
Completed 13.4 MiB/233.2 MiB (46.6 MiB/s) with 7 file(s) remaining
Completed 13.7 MiB/233.2 MiB (47.3 MiB/s) with 7 file(s) remaining
Completed 13.9 MiB/233.2 MiB (47.6 MiB/s) with 7 file(s) remaining
Completed 14.2 MiB/233.2 MiB (48.4 MiB/s) with 7 file(s) remaining
Completed 14.4 MiB/233.2 MiB (49.1 MiB/s) with 7 file(s) remaining
Completed 14.7 MiB/233.2 MiB (49.7 MiB/s) with 7 file(s) remaining
Completed 14.9 MiB/233.2 MiB (50.3 MiB/s) with 7 file(s) remaining
Completed 15.2 MiB/233.2 MiB (51.1 MiB/s) with 7 file(s) remaining
Completed 15.4 MiB/233.2 MiB (51.6 MiB/s) with 7 file(s) remaining
Completed 15.7 MiB/233.2 MiB (52.2 MiB/s) with 7 file(s) remaining
Completed 15.9 MiB/233.2 MiB (52.3 MiB/s) with 7 file(s) remaining
Completed 16.2 MiB/233.2 MiB (52.8 MiB/s) with 7 file(s) remaining
Completed 16.4 MiB/233.2 MiB (53.4 MiB/s) with 7 file(s) remaining
Completed 16.7 MiB/233.2 MiB (53.6 MiB/s) with 7 file(s) remaining
Completed 16.9 MiB/233.2 MiB (54.2 MiB/s) with 7 file(s) remaining
Completed 17.2 MiB/233.2 MiB (54.9 MiB/s) with 7 file(s) remaining
Completed 17.4 MiB/233.2 MiB (54.8 MiB/s) with 7 file(s) remaining
Completed 17.7 MiB/233.2 MiB (54.9 MiB/s) with 7 file(s) remaining
Completed 17.9 MiB/233.2 MiB (54.1 MiB/s) with 7 file(s) remaining
Completed 18.2 MiB/233.2 MiB (54.4 MiB/s) with 7 file(s) remaining
Completed 18.4 MiB/233.2 MiB (54.9 MiB/s) with 7 file(s) remaining
Completed 18.7 MiB/233.2 MiB (55.4 MiB/s) with 7 file(s) remaining
Completed 18.9 MiB/233.2 MiB (55.5 MiB/s) with 7 file(s) remaining
Completed 19.2 MiB/233.2 MiB (56.0 MiB/s) with 7 file(s) remaining
Completed 19.4 MiB/233.2 MiB (56.6 MiB/s) with 7 file(s) remaining
Completed 19.7 MiB/233.2 MiB (57.2 MiB/s) with 7 file(s) remaining
Completed 19.9 MiB/233.2 MiB (56.8 MiB/s) with 7 file(s) remaining
Completed 20.2 MiB/233.2 MiB (57.3 MiB/s) with 7 file(s) remaining
Completed 20.4 MiB/233.2 MiB (57.2 MiB/s) with 7 file(s) remaining
Completed 20.7 MiB/233.2 MiB (57.0 MiB/s) with 7 file(s) remaining
Completed 20.9 MiB/233.2 MiB (57.3 MiB/s) with 7 file(s) remaining
Completed 21.2 MiB/233.2 MiB (57.5 MiB/s) with 7 file(s) remaining
Completed 21.4 MiB/233.2 MiB (57.4 MiB/s) with 7 file(s) remaining
Completed 21.7 MiB/233.2 MiB (58.0 MiB/s) with 7 file(s) remaining
Completed 21.9 MiB/233.2 MiB (58.6 MiB/s) with 7 file(s) remaining
Completed 22.2 MiB/233.2 MiB (59.3 MiB/s) with 7 file(s) remaining
Completed 22.4 MiB/233.2 MiB (59.3 MiB/s) with 7 file(s) remaining
Completed 22.7 MiB/233.2 MiB (59.9 MiB/s) with 7 file(s) remaining
Completed 22.9 MiB/233.2 MiB (60.0 MiB/s) with 7 file(s) remaining
Completed 23.2 MiB/233.2 MiB (60.0 MiB/s) with 7 file(s) remaining
Completed 23.4 MiB/233.2 MiB (60.0 MiB/s) with 7 file(s) remaining
Completed 23.7 MiB/233.2 MiB (60.5 MiB/s) with 7 file(s) remaining
Completed 23.9 MiB/233.2 MiB (60.7 MiB/s) with 7 file(s) remaining
Completed 24.2 MiB/233.2 MiB (60.8 MiB/s) with 7 file(s) remaining
Completed 24.4 MiB/233.2 MiB (60.7 MiB/s) with 7 file(s) remaining
Completed 24.7 MiB/233.2 MiB (61.0 MiB/s) with 7 file(s) remaining
Completed 24.9 MiB/233.2 MiB (61.4 MiB/s) with 7 file(s) remaining
Completed 25.2 MiB/233.2 MiB (61.7 MiB/s) with 7 file(s) remaining
Completed 25.4 MiB/233.2 MiB (62.1 MiB/s) with 7 file(s) remaining
Completed 25.7 MiB/233.2 MiB (62.2 MiB/s) with 7 file(s) remaining
Completed 25.9 MiB/233.2 MiB (62.7 MiB/s) with 7 file(s) remaining
Completed 26.2 MiB/233.2 MiB (62.9 MiB/s) with 7 file(s) remaining
Completed 26.4 MiB/233.2 MiB (62.9 MiB/s) with 7 file(s) remaining
Completed 26.7 MiB/233.2 MiB (62.9 MiB/s) with 7 file(s) remaining
Completed 26.9 MiB/233.2 MiB (63.0 MiB/s) with 7 file(s) remaining
Completed 27.2 MiB/233.2 MiB (63.0 MiB/s) with 7 file(s) remaining
Completed 27.4 MiB/233.2 MiB (62.9 MiB/s) with 7 file(s) remaining
Completed 27.7 MiB/233.2 MiB (62.9 MiB/s) with 7 file(s) remaining
Completed 27.9 MiB/233.2 MiB (63.1 MiB/s) with 7 file(s) remaining
Completed 28.2 MiB/233.2 MiB (63.4 MiB/s) with 7 file(s) remaining
Completed 28.4 MiB/233.2 MiB (63.6 MiB/s) with 7 file(s) remaining
Completed 28.7 MiB/233.2 MiB (64.0 MiB/s) with 7 file(s) remaining
Completed 28.9 MiB/233.2 MiB (64.1 MiB/s) with 7 file(s) remaining
Completed 29.2 MiB/233.2 MiB (62.0 MiB/s) with 7 file(s) remaining
Completed 29.4 MiB/233.2 MiB (60.2 MiB/s) with 7 file(s) remaining
Completed 29.7 MiB/233.2 MiB (60.3 MiB/s) with 7 file(s) remaining
Completed 29.9 MiB/233.2 MiB (59.3 MiB/s) with 7 file(s) remaining
Completed 30.2 MiB/233.2 MiB (58.2 MiB/s) with 7 file(s) remaining
Completed 30.4 MiB/233.2 MiB (58.3 MiB/s) with 7 file(s) remaining
Completed 30.7 MiB/233.2 MiB (57.5 MiB/s) with 7 file(s) remaining
Completed 30.9 MiB/233.2 MiB (56.9 MiB/s) with 7 file(s) remaining
Completed 31.2 MiB/233.2 MiB (56.7 MiB/s) with 7 file(s) remaining
Completed 31.4 MiB/233.2 MiB (55.3 MiB/s) with 7 file(s) remaining
Completed 31.7 MiB/233.2 MiB (55.7 MiB/s) with 7 file(s) remaining
Completed 31.9 MiB/233.2 MiB (54.8 MiB/s) with 7 file(s) remaining
Completed 32.2 MiB/233.2 MiB (54.9 MiB/s) with 7 file(s) remaining
Completed 32.4 MiB/233.2 MiB (54.4 MiB/s) with 7 file(s) remaining
Completed 32.7 MiB/233.2 MiB (54.0 MiB/s) with 7 file(s) remaining
Completed 32.9 MiB/233.2 MiB (53.4 MiB/s) with 7 file(s) remaining
Completed 33.2 MiB/233.2 MiB (53.3 MiB/s) with 7 file(s) remaining
Completed 33.4 MiB/233.2 MiB (52.8 MiB/s) with 7 file(s) remaining
Completed 33.4 MiB/233.2 MiB (52.7 MiB/s) with 7 file(s) remaining
upload: ../../../data/datafile-5243880-b to s3://awscli-mint-test-bucket-28058/datafile-5243880-bCompleted 33.4 MiB/233.2 MiB (52.7 MiB/s) with 6 file(s) remaining
Completed 33.7 MiB/233.2 MiB (52.7 MiB/s) with 6 file(s) remaining
Completed 33.9 MiB/233.2 MiB (52.1 MiB/s) with 6 file(s) remaining
Completed 34.2 MiB/233.2 MiB (52.2 MiB/s) with 6 file(s) remaining
Completed 34.4 MiB/233.2 MiB (51.6 MiB/s) with 6 file(s) remaining
Completed 34.7 MiB/233.2 MiB (51.9 MiB/s) with 6 file(s) remaining
upload: ../../../data/datafile-5-MB to s3://awscli-mint-test-bucket-28058/datafile-5-MBCompleted 34.7 MiB/233.2 MiB (51.9 MiB/s) with 5 file(s) remaining
Completed 34.9 MiB/233.2 MiB (51.8 MiB/s) with 5 file(s) remaining
Completed 35.2 MiB/233.2 MiB (52.2 MiB/s) with 5 file(s) remaining
Completed 35.4 MiB/233.2 MiB (52.3 MiB/s) with 5 file(s) remaining
Completed 35.7 MiB/233.2 MiB (52.3 MiB/s) with 5 file(s) remaining
Completed 35.9 MiB/233.2 MiB (52.4 MiB/s) with 5 file(s) remaining
Completed 36.2 MiB/233.2 MiB (52.4 MiB/s) with 5 file(s) remaining
Completed 36.4 MiB/233.2 MiB (52.2 MiB/s) with 5 file(s) remaining
Completed 36.7 MiB/233.2 MiB (52.4 MiB/s) with 5 file(s) remaining
Completed 36.9 MiB/233.2 MiB (52.5 MiB/s) with 5 file(s) remaining
Completed 37.2 MiB/233.2 MiB (52.5 MiB/s) with 5 file(s) remaining
Completed 37.4 MiB/233.2 MiB (52.5 MiB/s) with 5 file(s) remaining
Completed 37.7 MiB/233.2 MiB (52.4 MiB/s) with 5 file(s) remaining
Completed 37.9 MiB/233.2 MiB (52.4 MiB/s) with 5 file(s) remaining
Completed 38.2 MiB/233.2 MiB (52.4 MiB/s) with 5 file(s) remaining
Completed 38.4 MiB/233.2 MiB (52.4 MiB/s) with 5 file(s) remaining
Completed 38.7 MiB/233.2 MiB (52.4 MiB/s) with 5 file(s) remaining
Completed 38.9 MiB/233.2 MiB (52.4 MiB/s) with 5 file(s) remaining
Completed 39.2 MiB/233.2 MiB (51.8 MiB/s) with 5 file(s) remaining
Completed 39.4 MiB/233.2 MiB (48.1 MiB/s) with 5 file(s) remaining
Completed 39.7 MiB/233.2 MiB (48.3 MiB/s) with 5 file(s) remaining
Completed 39.9 MiB/233.2 MiB (48.6 MiB/s) with 5 file(s) remaining
Completed 40.2 MiB/233.2 MiB (48.8 MiB/s) with 5 file(s) remaining
Completed 40.4 MiB/233.2 MiB (49.1 MiB/s) with 5 file(s) remaining
Completed 40.7 MiB/233.2 MiB (49.2 MiB/s) with 5 file(s) remaining
Completed 40.9 MiB/233.2 MiB (49.3 MiB/s) with 5 file(s) remaining
Completed 41.2 MiB/233.2 MiB (49.4 MiB/s) with 5 file(s) remaining
Completed 41.4 MiB/233.2 MiB (49.5 MiB/s) with 5 file(s) remaining
Completed 41.7 MiB/233.2 MiB (49.6 MiB/s) with 5 file(s) remaining
Completed 41.9 MiB/233.2 MiB (49.7 MiB/s) with 5 file(s) remaining
Completed 42.2 MiB/233.2 MiB (49.8 MiB/s) with 5 file(s) remaining
Completed 42.4 MiB/233.2 MiB (49.9 MiB/s) with 5 file(s) remaining
Completed 42.7 MiB/233.2 MiB (50.0 MiB/s) with 5 file(s) remaining
Completed 42.9 MiB/233.2 MiB (50.1 MiB/s) with 5 file(s) remaining
Completed 43.2 MiB/233.2 MiB (50.2 MiB/s) with 5 file(s) remaining
Completed 43.4 MiB/233.2 MiB (50.5 MiB/s) with 5 file(s) remaining
Completed 43.7 MiB/233.2 MiB (50.7 MiB/s) with 5 file(s) remaining
Completed 43.9 MiB/233.2 MiB (50.9 MiB/s) with 5 file(s) remaining
Completed 44.2 MiB/233.2 MiB (51.1 MiB/s) with 5 file(s) remaining
Completed 44.4 MiB/233.2 MiB (51.3 MiB/s) with 5 file(s) remaining
Completed 44.7 MiB/233.2 MiB (51.5 MiB/s) with 5 file(s) remaining
Completed 44.9 MiB/233.2 MiB (51.7 MiB/s) with 5 file(s) remaining
Completed 45.2 MiB/233.2 MiB (51.9 MiB/s) with 5 file(s) remaining
Completed 45.4 MiB/233.2 MiB (52.2 MiB/s) with 5 file(s) remaining
Completed 45.7 MiB/233.2 MiB (52.4 MiB/s) with 5 file(s) remaining
Completed 45.9 MiB/233.2 MiB (52.5 MiB/s) with 5 file(s) remaining
Completed 46.2 MiB/233.2 MiB (52.6 MiB/s) with 5 file(s) remaining
Completed 46.4 MiB/233.2 MiB (52.7 MiB/s) with 5 file(s) remaining
Completed 46.7 MiB/233.2 MiB (52.6 MiB/s) with 5 file(s) remaining
Completed 46.9 MiB/233.2 MiB (52.7 MiB/s) with 5 file(s) remaining
Completed 47.2 MiB/233.2 MiB (52.8 MiB/s) with 5 file(s) remaining
Completed 47.4 MiB/233.2 MiB (53.0 MiB/s) with 5 file(s) remaining
Completed 47.7 MiB/233.2 MiB (52.8 MiB/s) with 5 file(s) remaining
Completed 47.9 MiB/233.2 MiB (52.9 MiB/s) with 5 file(s) remaining
Completed 48.2 MiB/233.2 MiB (52.8 MiB/s) with 5 file(s) remaining
Completed 48.4 MiB/233.2 MiB (53.0 MiB/s) with 5 file(s) remaining
Completed 48.7 MiB/233.2 MiB (53.1 MiB/s) with 5 file(s) remaining
Completed 48.9 MiB/233.2 MiB (53.2 MiB/s) with 5 file(s) remaining
Completed 49.2 MiB/233.2 MiB (53.3 MiB/s) with 5 file(s) remaining
Completed 49.4 MiB/233.2 MiB (53.5 MiB/s) with 5 file(s) remaining
Completed 49.7 MiB/233.2 MiB (53.7 MiB/s) with 5 file(s) remaining
Completed 49.9 MiB/233.2 MiB (53.7 MiB/s) with 5 file(s) remaining
Completed 50.2 MiB/233.2 MiB (54.0 MiB/s) with 5 file(s) remaining
Completed 50.4 MiB/233.2 MiB (54.0 MiB/s) with 5 file(s) remaining
Completed 50.7 MiB/233.2 MiB (54.2 MiB/s) with 5 file(s) remaining
Completed 50.9 MiB/233.2 MiB (54.3 MiB/s) with 5 file(s) remaining
Completed 51.2 MiB/233.2 MiB (54.5 MiB/s) with 5 file(s) remaining
Completed 51.4 MiB/233.2 MiB (54.7 MiB/s) with 5 file(s) remaining
Completed 51.7 MiB/233.2 MiB (54.7 MiB/s) with 5 file(s) remaining
Completed 51.9 MiB/233.2 MiB (54.9 MiB/s) with 5 file(s) remaining
Completed 52.2 MiB/233.2 MiB (55.0 MiB/s) with 5 file(s) remaining
Completed 52.4 MiB/233.2 MiB (55.0 MiB/s) with 5 file(s) remaining
Completed 52.7 MiB/233.2 MiB (55.2 MiB/s) with 5 file(s) remaining
Completed 52.9 MiB/233.2 MiB (55.4 MiB/s) with 5 file(s) remaining
Completed 53.2 MiB/233.2 MiB (55.4 MiB/s) with 5 file(s) remaining
Completed 53.4 MiB/233.2 MiB (55.6 MiB/s) with 5 file(s) remaining
Completed 53.7 MiB/233.2 MiB (55.8 MiB/s) with 5 file(s) remaining
Completed 53.9 MiB/233.2 MiB (55.7 MiB/s) with 5 file(s) remaining
Completed 54.2 MiB/233.2 MiB (55.9 MiB/s) with 5 file(s) remaining
Completed 54.4 MiB/233.2 MiB (55.8 MiB/s) with 5 file(s) remaining
Completed 54.7 MiB/233.2 MiB (56.0 MiB/s) with 5 file(s) remaining
Completed 54.9 MiB/233.2 MiB (55.9 MiB/s) with 5 file(s) remaining
Completed 55.2 MiB/233.2 MiB (56.1 MiB/s) with 5 file(s) remaining
Completed 55.4 MiB/233.2 MiB (56.0 MiB/s) with 5 file(s) remaining
Completed 55.7 MiB/233.2 MiB (56.1 MiB/s) with 5 file(s) remaining
Completed 55.9 MiB/233.2 MiB (56.3 MiB/s) with 5 file(s) remaining
Completed 56.2 MiB/233.2 MiB (56.3 MiB/s) with 5 file(s) remaining
Completed 56.4 MiB/233.2 MiB (56.3 MiB/s) with 5 file(s) remaining
Completed 56.7 MiB/233.2 MiB (56.3 MiB/s) with 5 file(s) remaining
Completed 56.9 MiB/233.2 MiB (56.4 MiB/s) with 5 file(s) remaining
Completed 57.2 MiB/233.2 MiB (56.5 MiB/s) with 5 file(s) remaining
Completed 57.4 MiB/233.2 MiB (56.6 MiB/s) with 5 file(s) remaining
Completed 57.7 MiB/233.2 MiB (56.6 MiB/s) with 5 file(s) remaining
Completed 57.9 MiB/233.2 MiB (56.8 MiB/s) with 5 file(s) remaining
Completed 58.2 MiB/233.2 MiB (56.8 MiB/s) with 5 file(s) remaining
Completed 58.4 MiB/233.2 MiB (56.9 MiB/s) with 5 file(s) remaining
Completed 58.7 MiB/233.2 MiB (57.1 MiB/s) with 5 file(s) remaining
Completed 58.9 MiB/233.2 MiB (57.1 MiB/s) with 5 file(s) remaining
Completed 59.2 MiB/233.2 MiB (57.1 MiB/s) with 5 file(s) remaining
Completed 59.4 MiB/233.2 MiB (57.3 MiB/s) with 5 file(s) remaining
Completed 59.7 MiB/233.2 MiB (57.3 MiB/s) with 5 file(s) remaining
Completed 59.9 MiB/233.2 MiB (57.4 MiB/s) with 5 file(s) remaining
Completed 60.2 MiB/233.2 MiB (57.4 MiB/s) with 5 file(s) remaining
Completed 60.4 MiB/233.2 MiB (57.6 MiB/s) with 5 file(s) remaining
Completed 60.7 MiB/233.2 MiB (57.7 MiB/s) with 5 file(s) remaining
Completed 60.9 MiB/233.2 MiB (57.7 MiB/s) with 5 file(s) remaining
Completed 61.2 MiB/233.2 MiB (57.8 MiB/s) with 5 file(s) remaining
Completed 61.4 MiB/233.2 MiB (57.5 MiB/s) with 5 file(s) remaining
Completed 61.7 MiB/233.2 MiB (57.1 MiB/s) with 5 file(s) remaining
Completed 61.9 MiB/233.2 MiB (56.6 MiB/s) with 5 file(s) remaining
Completed 62.2 MiB/233.2 MiB (56.3 MiB/s) with 5 file(s) remaining
Completed 62.4 MiB/233.2 MiB (55.9 MiB/s) with 5 file(s) remaining
Completed 62.7 MiB/233.2 MiB (55.7 MiB/s) with 5 file(s) remaining
Completed 62.9 MiB/233.2 MiB (55.9 MiB/s) with 5 file(s) remaining
Completed 63.2 MiB/233.2 MiB (56.1 MiB/s) with 5 file(s) remaining
Completed 63.4 MiB/233.2 MiB (56.2 MiB/s) with 5 file(s) remaining
Completed 63.7 MiB/233.2 MiB (56.3 MiB/s) with 5 file(s) remaining
Completed 63.9 MiB/233.2 MiB (55.9 MiB/s) with 5 file(s) remaining
Completed 64.2 MiB/233.2 MiB (55.9 MiB/s) with 5 file(s) remaining
Completed 64.4 MiB/233.2 MiB (55.7 MiB/s) with 5 file(s) remaining
Completed 64.7 MiB/233.2 MiB (55.7 MiB/s) with 5 file(s) remaining
Completed 64.9 MiB/233.2 MiB (55.3 MiB/s) with 5 file(s) remaining
Completed 65.2 MiB/233.2 MiB (55.0 MiB/s) with 5 file(s) remaining
Completed 65.4 MiB/233.2 MiB (54.7 MiB/s) with 5 file(s) remaining
Completed 65.7 MiB/233.2 MiB (54.4 MiB/s) with 5 file(s) remaining
Completed 65.9 MiB/233.2 MiB (54.2 MiB/s) with 5 file(s) remaining
Completed 66.2 MiB/233.2 MiB (53.9 MiB/s) with 5 file(s) remaining
Completed 66.4 MiB/233.2 MiB (53.7 MiB/s) with 5 file(s) remaining
Completed 66.7 MiB/233.2 MiB (53.6 MiB/s) with 5 file(s) remaining
Completed 66.9 MiB/233.2 MiB (53.4 MiB/s) with 5 file(s) remaining
Completed 67.2 MiB/233.2 MiB (53.3 MiB/s) with 5 file(s) remaining
Completed 67.4 MiB/233.2 MiB (53.3 MiB/s) with 5 file(s) remaining
Completed 67.7 MiB/233.2 MiB (53.3 MiB/s) with 5 file(s) remaining
Completed 67.9 MiB/233.2 MiB (53.3 MiB/s) with 5 file(s) remaining
Completed 68.2 MiB/233.2 MiB (53.3 MiB/s) with 5 file(s) remaining
Completed 68.4 MiB/233.2 MiB (53.4 MiB/s) with 5 file(s) remaining
Completed 68.7 MiB/233.2 MiB (53.5 MiB/s) with 5 file(s) remaining
Completed 68.9 MiB/233.2 MiB (53.5 MiB/s) with 5 file(s) remaining
upload: ../../../data/datafile-6-MB to s3://awscli-mint-test-bucket-28058/datafile-6-MBCompleted 68.9 MiB/233.2 MiB (53.5 MiB/s) with 4 file(s) remaining
Completed 69.2 MiB/233.2 MiB (53.5 MiB/s) with 4 file(s) remaining
Completed 69.4 MiB/233.2 MiB (53.5 MiB/s) with 4 file(s) remaining
Completed 69.7 MiB/233.2 MiB (53.5 MiB/s) with 4 file(s) remaining
Completed 69.9 MiB/233.2 MiB (53.5 MiB/s) with 4 file(s) remaining
Completed 70.2 MiB/233.2 MiB (53.5 MiB/s) with 4 file(s) remaining
Completed 70.4 MiB/233.2 MiB (53.5 MiB/s) with 4 file(s) remaining
Completed 70.7 MiB/233.2 MiB (53.6 MiB/s) with 4 file(s) remaining
Completed 70.9 MiB/233.2 MiB (53.6 MiB/s) with 4 file(s) remaining
Completed 71.2 MiB/233.2 MiB (53.6 MiB/s) with 4 file(s) remaining
Completed 71.4 MiB/233.2 MiB (44.7 MiB/s) with 4 file(s) remaining
Completed 71.7 MiB/233.2 MiB (44.9 MiB/s) with 4 file(s) remaining
Completed 71.9 MiB/233.2 MiB (45.0 MiB/s) with 4 file(s) remaining
Completed 72.2 MiB/233.2 MiB (45.1 MiB/s) with 4 file(s) remaining
Completed 72.4 MiB/233.2 MiB (45.3 MiB/s) with 4 file(s) remaining
Completed 72.7 MiB/233.2 MiB (45.4 MiB/s) with 4 file(s) remaining
Completed 72.9 MiB/233.2 MiB (45.5 MiB/s) with 4 file(s) remaining
Completed 73.2 MiB/233.2 MiB (45.6 MiB/s) with 4 file(s) remaining
Completed 73.4 MiB/233.2 MiB (45.7 MiB/s) with 4 file(s) remaining
Completed 73.7 MiB/233.2 MiB (45.7 MiB/s) with 4 file(s) remaining
Completed 73.9 MiB/233.2 MiB (45.8 MiB/s) with 4 file(s) remaining
Completed 74.2 MiB/233.2 MiB (45.9 MiB/s) with 4 file(s) remaining
Completed 74.4 MiB/233.2 MiB (46.0 MiB/s) with 4 file(s) remaining
Completed 74.7 MiB/233.2 MiB (46.1 MiB/s) with 4 file(s) remaining
Completed 74.9 MiB/233.2 MiB (46.2 MiB/s) with 4 file(s) remaining
Completed 75.2 MiB/233.2 MiB (46.3 MiB/s) with 4 file(s) remaining
Completed 75.4 MiB/233.2 MiB (46.4 MiB/s) with 4 file(s) remaining
Completed 75.7 MiB/233.2 MiB (46.4 MiB/s) with 4 file(s) remaining
Completed 75.9 MiB/233.2 MiB (46.5 MiB/s) with 4 file(s) remaining
Completed 76.2 MiB/233.2 MiB (46.6 MiB/s) with 4 file(s) remaining
Completed 76.4 MiB/233.2 MiB (46.6 MiB/s) with 4 file(s) remaining
Completed 76.7 MiB/233.2 MiB (46.7 MiB/s) with 4 file(s) remaining
Completed 76.9 MiB/233.2 MiB (46.8 MiB/s) with 4 file(s) remaining
Completed 77.2 MiB/233.2 MiB (46.8 MiB/s) with 4 file(s) remaining
Completed 77.4 MiB/233.2 MiB (46.9 MiB/s) with 4 file(s) remaining
Completed 77.7 MiB/233.2 MiB (46.9 MiB/s) with 4 file(s) remaining
Completed 77.9 MiB/233.2 MiB (47.0 MiB/s) with 4 file(s) remaining
Completed 78.2 MiB/233.2 MiB (47.0 MiB/s) with 4 file(s) remaining
Completed 78.4 MiB/233.2 MiB (47.1 MiB/s) with 4 file(s) remaining
Completed 78.7 MiB/233.2 MiB (47.2 MiB/s) with 4 file(s) remaining
Completed 78.9 MiB/233.2 MiB (47.2 MiB/s) with 4 file(s) remaining
Completed 79.2 MiB/233.2 MiB (47.3 MiB/s) with 4 file(s) remaining
Completed 79.4 MiB/233.2 MiB (40.5 MiB/s) with 4 file(s) remaining
Completed 79.7 MiB/233.2 MiB (40.6 MiB/s) with 4 file(s) remaining
Completed 79.9 MiB/233.2 MiB (40.7 MiB/s) with 4 file(s) remaining
Completed 80.2 MiB/233.2 MiB (40.8 MiB/s) with 4 file(s) remaining
Completed 80.4 MiB/233.2 MiB (40.9 MiB/s) with 4 file(s) remaining
Completed 80.7 MiB/233.2 MiB (41.0 MiB/s) with 4 file(s) remaining
Completed 80.9 MiB/233.2 MiB (41.0 MiB/s) with 4 file(s) remaining
Completed 81.2 MiB/233.2 MiB (41.1 MiB/s) with 4 file(s) remaining
Completed 81.4 MiB/233.2 MiB (41.2 MiB/s) with 4 file(s) remaining
Completed 81.7 MiB/233.2 MiB (41.3 MiB/s) with 4 file(s) remaining
Completed 81.9 MiB/233.2 MiB (41.3 MiB/s) with 4 file(s) remaining
Completed 82.2 MiB/233.2 MiB (41.4 MiB/s) with 4 file(s) remaining
Completed 82.4 MiB/233.2 MiB (41.5 MiB/s) with 4 file(s) remaining
Completed 82.7 MiB/233.2 MiB (41.5 MiB/s) with 4 file(s) remaining
Completed 82.9 MiB/233.2 MiB (41.6 MiB/s) with 4 file(s) remaining
Completed 83.2 MiB/233.2 MiB (41.7 MiB/s) with 4 file(s) remaining
Completed 83.4 MiB/233.2 MiB (41.8 MiB/s) with 4 file(s) remaining
Completed 83.7 MiB/233.2 MiB (41.8 MiB/s) with 4 file(s) remaining
Completed 83.9 MiB/233.2 MiB (41.9 MiB/s) with 4 file(s) remaining
Completed 84.2 MiB/233.2 MiB (42.0 MiB/s) with 4 file(s) remaining
Completed 84.4 MiB/233.2 MiB (42.0 MiB/s) with 4 file(s) remaining
Completed 84.7 MiB/233.2 MiB (42.1 MiB/s) with 4 file(s) remaining
Completed 84.9 MiB/233.2 MiB (42.1 MiB/s) with 4 file(s) remaining
Completed 85.2 MiB/233.2 MiB (42.2 MiB/s) with 4 file(s) remaining
Completed 85.4 MiB/233.2 MiB (42.2 MiB/s) with 4 file(s) remaining
Completed 85.7 MiB/233.2 MiB (42.2 MiB/s) with 4 file(s) remaining
Completed 85.9 MiB/233.2 MiB (42.3 MiB/s) with 4 file(s) remaining
Completed 86.2 MiB/233.2 MiB (42.3 MiB/s) with 4 file(s) remaining
Completed 86.4 MiB/233.2 MiB (42.4 MiB/s) with 4 file(s) remaining
Completed 86.7 MiB/233.2 MiB (42.5 MiB/s) with 4 file(s) remaining
Completed 86.9 MiB/233.2 MiB (42.5 MiB/s) with 4 file(s) remaining
Completed 87.2 MiB/233.2 MiB (42.5 MiB/s) with 4 file(s) remaining
upload: ../../../data/datafile-11-MB to s3://awscli-mint-test-bucket-28058/datafile-11-MBCompleted 87.2 MiB/233.2 MiB (42.5 MiB/s) with 3 file(s) remaining
upload: ../../../data/datafile-10-MB to s3://awscli-mint-test-bucket-28058/datafile-10-MBCompleted 87.2 MiB/233.2 MiB (42.5 MiB/s) with 2 file(s) remaining
Completed 87.4 MiB/233.2 MiB (39.5 MiB/s) with 2 file(s) remaining
Completed 87.7 MiB/233.2 MiB (39.6 MiB/s) with 2 file(s) remaining
Completed 87.9 MiB/233.2 MiB (39.7 MiB/s) with 2 file(s) remaining
Completed 88.2 MiB/233.2 MiB (39.8 MiB/s) with 2 file(s) remaining
Completed 88.4 MiB/233.2 MiB (39.9 MiB/s) with 2 file(s) remaining
Completed 88.7 MiB/233.2 MiB (40.0 MiB/s) with 2 file(s) remaining
Completed 88.9 MiB/233.2 MiB (40.1 MiB/s) with 2 file(s) remaining
Completed 89.2 MiB/233.2 MiB (40.2 MiB/s) with 2 file(s) remaining
Completed 89.4 MiB/233.2 MiB (40.3 MiB/s) with 2 file(s) remaining
Completed 89.7 MiB/233.2 MiB (40.4 MiB/s) with 2 file(s) remaining
Completed 89.9 MiB/233.2 MiB (40.4 MiB/s) with 2 file(s) remaining
Completed 90.2 MiB/233.2 MiB (40.5 MiB/s) with 2 file(s) remaining
Completed 90.4 MiB/233.2 MiB (40.6 MiB/s) with 2 file(s) remaining
Completed 90.7 MiB/233.2 MiB (40.6 MiB/s) with 2 file(s) remaining
Completed 90.9 MiB/233.2 MiB (40.7 MiB/s) with 2 file(s) remaining
Completed 91.2 MiB/233.2 MiB (40.8 MiB/s) with 2 file(s) remaining
Completed 91.4 MiB/233.2 MiB (40.9 MiB/s) with 2 file(s) remaining
Completed 91.7 MiB/233.2 MiB (40.9 MiB/s) with 2 file(s) remaining
Completed 91.9 MiB/233.2 MiB (41.0 MiB/s) with 2 file(s) remaining
Completed 92.2 MiB/233.2 MiB (41.1 MiB/s) with 2 file(s) remaining
Completed 92.4 MiB/233.2 MiB (41.1 MiB/s) with 2 file(s) remaining
Completed 92.7 MiB/233.2 MiB (41.2 MiB/s) with 2 file(s) remaining
Completed 92.9 MiB/233.2 MiB (41.3 MiB/s) with 2 file(s) remaining
Completed 93.2 MiB/233.2 MiB (41.4 MiB/s) with 2 file(s) remaining
Completed 93.4 MiB/233.2 MiB (41.5 MiB/s) with 2 file(s) remaining
Completed 93.7 MiB/233.2 MiB (41.5 MiB/s) with 2 file(s) remaining
Completed 93.9 MiB/233.2 MiB (41.6 MiB/s) with 2 file(s) remaining
Completed 94.2 MiB/233.2 MiB (41.7 MiB/s) with 2 file(s) remaining
Completed 94.4 MiB/233.2 MiB (41.8 MiB/s) with 2 file(s) remaining
Completed 94.7 MiB/233.2 MiB (41.9 MiB/s) with 2 file(s) remaining
Completed 94.9 MiB/233.2 MiB (42.0 MiB/s) with 2 file(s) remaining
Completed 95.2 MiB/233.2 MiB (42.0 MiB/s) with 2 file(s) remaining
Completed 95.4 MiB/233.2 MiB (42.1 MiB/s) with 2 file(s) remaining
Completed 95.7 MiB/233.2 MiB (42.2 MiB/s) with 2 file(s) remaining
Completed 95.9 MiB/233.2 MiB (42.2 MiB/s) with 2 file(s) remaining
Completed 96.2 MiB/233.2 MiB (42.3 MiB/s) with 2 file(s) remaining
Completed 96.4 MiB/233.2 MiB (42.4 MiB/s) with 2 file(s) remaining
Completed 96.7 MiB/233.2 MiB (42.4 MiB/s) with 2 file(s) remaining
Completed 96.9 MiB/233.2 MiB (42.5 MiB/s) with 2 file(s) remaining
Completed 97.2 MiB/233.2 MiB (42.6 MiB/s) with 2 file(s) remaining
Completed 97.4 MiB/233.2 MiB (42.6 MiB/s) with 2 file(s) remaining
Completed 97.7 MiB/233.2 MiB (42.7 MiB/s) with 2 file(s) remaining
Completed 97.9 MiB/233.2 MiB (42.8 MiB/s) with 2 file(s) remaining
Completed 98.2 MiB/233.2 MiB (42.9 MiB/s) with 2 file(s) remaining
Completed 98.4 MiB/233.2 MiB (43.0 MiB/s) with 2 file(s) remaining
Completed 98.7 MiB/233.2 MiB (43.1 MiB/s) with 2 file(s) remaining
Completed 98.9 MiB/233.2 MiB (43.1 MiB/s) with 2 file(s) remaining
Completed 99.2 MiB/233.2 MiB (43.2 MiB/s) with 2 file(s) remaining
Completed 99.4 MiB/233.2 MiB (43.3 MiB/s) with 2 file(s) remaining
Completed 99.7 MiB/233.2 MiB (43.4 MiB/s) with 2 file(s) remaining
Completed 99.9 MiB/233.2 MiB (43.5 MiB/s) with 2 file(s) remaining
Completed 100.2 MiB/233.2 MiB (43.5 MiB/s) with 2 file(s) remaining
Completed 100.4 MiB/233.2 MiB (43.6 MiB/s) with 2 file(s) remaining
Completed 100.7 MiB/233.2 MiB (43.7 MiB/s) with 2 file(s) remaining
Completed 100.9 MiB/233.2 MiB (43.8 MiB/s) with 2 file(s) remaining
Completed 101.2 MiB/233.2 MiB (43.9 MiB/s) with 2 file(s) remaining
Completed 101.4 MiB/233.2 MiB (44.0 MiB/s) with 2 file(s) remaining
Completed 101.7 MiB/233.2 MiB (44.1 MiB/s) with 2 file(s) remaining
Completed 101.9 MiB/233.2 MiB (44.2 MiB/s) with 2 file(s) remaining
Completed 102.2 MiB/233.2 MiB (44.2 MiB/s) with 2 file(s) remaining
Completed 102.4 MiB/233.2 MiB (44.3 MiB/s) with 2 file(s) remaining
Completed 102.7 MiB/233.2 MiB (44.3 MiB/s) with 2 file(s) remaining
Completed 102.9 MiB/233.2 MiB (44.4 MiB/s) with 2 file(s) remaining
Completed 103.2 MiB/233.2 MiB (44.4 MiB/s) with 2 file(s) remaining
Completed 103.4 MiB/233.2 MiB (44.5 MiB/s) with 2 file(s) remaining
Completed 103.7 MiB/233.2 MiB (44.6 MiB/s) with 2 file(s) remaining
Completed 103.9 MiB/233.2 MiB (44.7 MiB/s) with 2 file(s) remaining
Completed 104.2 MiB/233.2 MiB (44.7 MiB/s) with 2 file(s) remaining
Completed 104.4 MiB/233.2 MiB (44.8 MiB/s) with 2 file(s) remaining
Completed 104.7 MiB/233.2 MiB (44.9 MiB/s) with 2 file(s) remaining
Completed 104.9 MiB/233.2 MiB (45.0 MiB/s) with 2 file(s) remaining
Completed 105.2 MiB/233.2 MiB (45.0 MiB/s) with 2 file(s) remaining
Completed 105.4 MiB/233.2 MiB (45.1 MiB/s) with 2 file(s) remaining
Completed 105.7 MiB/233.2 MiB (45.1 MiB/s) with 2 file(s) remaining
Completed 105.9 MiB/233.2 MiB (45.2 MiB/s) with 2 file(s) remaining
Completed 106.2 MiB/233.2 MiB (45.2 MiB/s) with 2 file(s) remaining
Completed 106.4 MiB/233.2 MiB (45.3 MiB/s) with 2 file(s) remaining
Completed 106.7 MiB/233.2 MiB (45.4 MiB/s) with 2 file(s) remaining
Completed 106.9 MiB/233.2 MiB (45.4 MiB/s) with 2 file(s) remaining
Completed 107.2 MiB/233.2 MiB (45.5 MiB/s) with 2 file(s) remaining
Completed 107.4 MiB/233.2 MiB (45.6 MiB/s) with 2 file(s) remaining
Completed 107.7 MiB/233.2 MiB (45.7 MiB/s) with 2 file(s) remaining
Completed 107.9 MiB/233.2 MiB (45.8 MiB/s) with 2 file(s) remaining
Completed 108.2 MiB/233.2 MiB (45.9 MiB/s) with 2 file(s) remaining
Completed 108.4 MiB/233.2 MiB (45.9 MiB/s) with 2 file(s) remaining
Completed 108.7 MiB/233.2 MiB (46.0 MiB/s) with 2 file(s) remaining
Completed 108.9 MiB/233.2 MiB (46.1 MiB/s) with 2 file(s) remaining
Completed 109.2 MiB/233.2 MiB (46.2 MiB/s) with 2 file(s) remaining
Completed 109.4 MiB/233.2 MiB (46.2 MiB/s) with 2 file(s) remaining
Completed 109.7 MiB/233.2 MiB (46.3 MiB/s) with 2 file(s) remaining
Completed 109.9 MiB/233.2 MiB (46.4 MiB/s) with 2 file(s) remaining
Completed 110.2 MiB/233.2 MiB (46.4 MiB/s) with 2 file(s) remaining
Completed 110.4 MiB/233.2 MiB (46.5 MiB/s) with 2 file(s) remaining
Completed 110.7 MiB/233.2 MiB (46.5 MiB/s) with 2 file(s) remaining
Completed 110.9 MiB/233.2 MiB (46.5 MiB/s) with 2 file(s) remaining
Completed 111.2 MiB/233.2 MiB (46.6 MiB/s) with 2 file(s) remaining
Completed 111.4 MiB/233.2 MiB (46.7 MiB/s) with 2 file(s) remaining
Completed 111.7 MiB/233.2 MiB (46.7 MiB/s) with 2 file(s) remaining
Completed 111.9 MiB/233.2 MiB (46.8 MiB/s) with 2 file(s) remaining
Completed 112.2 MiB/233.2 MiB (46.9 MiB/s) with 2 file(s) remaining
Completed 112.4 MiB/233.2 MiB (47.0 MiB/s) with 2 file(s) remaining
Completed 112.7 MiB/233.2 MiB (47.0 MiB/s) with 2 file(s) remaining
Completed 112.9 MiB/233.2 MiB (47.0 MiB/s) with 2 file(s) remaining
Completed 113.2 MiB/233.2 MiB (47.1 MiB/s) with 2 file(s) remaining
Completed 113.4 MiB/233.2 MiB (47.2 MiB/s) with 2 file(s) remaining
Completed 113.7 MiB/233.2 MiB (47.2 MiB/s) with 2 file(s) remaining
Completed 113.9 MiB/233.2 MiB (47.2 MiB/s) with 2 file(s) remaining
Completed 114.2 MiB/233.2 MiB (47.3 MiB/s) with 2 file(s) remaining
Completed 114.4 MiB/233.2 MiB (47.3 MiB/s) with 2 file(s) remaining
Completed 114.7 MiB/233.2 MiB (47.4 MiB/s) with 2 file(s) remaining
Completed 114.9 MiB/233.2 MiB (47.5 MiB/s) with 2 file(s) remaining
Completed 115.2 MiB/233.2 MiB (47.6 MiB/s) with 2 file(s) remaining
Completed 115.4 MiB/233.2 MiB (47.6 MiB/s) with 2 file(s) remaining
Completed 115.7 MiB/233.2 MiB (47.6 MiB/s) with 2 file(s) remaining
Completed 115.9 MiB/233.2 MiB (47.7 MiB/s) with 2 file(s) remaining
Completed 116.2 MiB/233.2 MiB (47.7 MiB/s) with 2 file(s) remaining
Completed 116.4 MiB/233.2 MiB (47.8 MiB/s) with 2 file(s) remaining
Completed 116.7 MiB/233.2 MiB (47.9 MiB/s) with 2 file(s) remaining
Completed 116.9 MiB/233.2 MiB (47.9 MiB/s) with 2 file(s) remaining
Completed 117.2 MiB/233.2 MiB (47.9 MiB/s) with 2 file(s) remaining
Completed 117.4 MiB/233.2 MiB (48.0 MiB/s) with 2 file(s) remaining
Completed 117.7 MiB/233.2 MiB (48.1 MiB/s) with 2 file(s) remaining
Completed 117.9 MiB/233.2 MiB (48.0 MiB/s) with 2 file(s) remaining
Completed 118.2 MiB/233.2 MiB (47.9 MiB/s) with 2 file(s) remaining
Completed 118.4 MiB/233.2 MiB (48.0 MiB/s) with 2 file(s) remaining
Completed 118.7 MiB/233.2 MiB (48.0 MiB/s) with 2 file(s) remaining
Completed 118.9 MiB/233.2 MiB (48.0 MiB/s) with 2 file(s) remaining
Completed 119.2 MiB/233.2 MiB (47.9 MiB/s) with 2 file(s) remaining
Completed 119.4 MiB/233.2 MiB (48.0 MiB/s) with 2 file(s) remaining
Completed 119.7 MiB/233.2 MiB (48.1 MiB/s) with 2 file(s) remaining
Completed 119.9 MiB/233.2 MiB (48.0 MiB/s) with 2 file(s) remaining
Completed 120.2 MiB/233.2 MiB (47.6 MiB/s) with 2 file(s) remaining
Completed 120.4 MiB/233.2 MiB (47.5 MiB/s) with 2 file(s) remaining
Completed 120.7 MiB/233.2 MiB (47.5 MiB/s) with 2 file(s) remaining
Completed 120.9 MiB/233.2 MiB (47.6 MiB/s) with 2 file(s) remaining
Completed 121.2 MiB/233.2 MiB (47.7 MiB/s) with 2 file(s) remaining
Completed 121.4 MiB/233.2 MiB (47.8 MiB/s) with 2 file(s) remaining
Completed 121.7 MiB/233.2 MiB (47.8 MiB/s) with 2 file(s) remaining
Completed 121.9 MiB/233.2 MiB (47.8 MiB/s) with 2 file(s) remaining
Completed 122.2 MiB/233.2 MiB (47.8 MiB/s) with 2 file(s) remaining
Completed 122.4 MiB/233.2 MiB (47.8 MiB/s) with 2 file(s) remaining
Completed 122.7 MiB/233.2 MiB (47.8 MiB/s) with 2 file(s) remaining
Completed 122.9 MiB/233.2 MiB (47.7 MiB/s) with 2 file(s) remaining
Completed 123.2 MiB/233.2 MiB (47.8 MiB/s) with 2 file(s) remaining
Completed 123.4 MiB/233.2 MiB (47.7 MiB/s) with 2 file(s) remaining
Completed 123.7 MiB/233.2 MiB (47.4 MiB/s) with 2 file(s) remaining
Completed 123.9 MiB/233.2 MiB (47.5 MiB/s) with 2 file(s) remaining
Completed 124.2 MiB/233.2 MiB (47.4 MiB/s) with 2 file(s) remaining
Completed 124.4 MiB/233.2 MiB (47.5 MiB/s) with 2 file(s) remaining
Completed 124.7 MiB/233.2 MiB (47.3 MiB/s) with 2 file(s) remaining
Completed 124.9 MiB/233.2 MiB (47.3 MiB/s) with 2 file(s) remaining
Completed 125.2 MiB/233.2 MiB (47.3 MiB/s) with 2 file(s) remaining
Completed 125.4 MiB/233.2 MiB (47.1 MiB/s) with 2 file(s) remaining
Completed 125.7 MiB/233.2 MiB (47.1 MiB/s) with 2 file(s) remaining
Completed 125.9 MiB/233.2 MiB (47.1 MiB/s) with 2 file(s) remaining
Completed 126.2 MiB/233.2 MiB (47.0 MiB/s) with 2 file(s) remaining
Completed 126.4 MiB/233.2 MiB (47.0 MiB/s) with 2 file(s) remaining
Completed 126.7 MiB/233.2 MiB (47.0 MiB/s) with 2 file(s) remaining
Completed 126.9 MiB/233.2 MiB (46.9 MiB/s) with 2 file(s) remaining
Completed 127.2 MiB/233.2 MiB (47.0 MiB/s) with 2 file(s) remaining
Completed 127.4 MiB/233.2 MiB (47.0 MiB/s) with 2 file(s) remaining
Completed 127.7 MiB/233.2 MiB (46.8 MiB/s) with 2 file(s) remaining
Completed 127.9 MiB/233.2 MiB (46.9 MiB/s) with 2 file(s) remaining
Completed 128.2 MiB/233.2 MiB (47.0 MiB/s) with 2 file(s) remaining
Completed 128.4 MiB/233.2 MiB (46.9 MiB/s) with 2 file(s) remaining
Completed 128.7 MiB/233.2 MiB (46.8 MiB/s) with 2 file(s) remaining
Completed 128.9 MiB/233.2 MiB (46.8 MiB/s) with 2 file(s) remaining
Completed 129.2 MiB/233.2 MiB (46.9 MiB/s) with 2 file(s) remaining
Completed 129.4 MiB/233.2 MiB (46.8 MiB/s) with 2 file(s) remaining
Completed 129.7 MiB/233.2 MiB (46.9 MiB/s) with 2 file(s) remaining
Completed 129.9 MiB/233.2 MiB (46.8 MiB/s) with 2 file(s) remaining
Completed 130.2 MiB/233.2 MiB (46.8 MiB/s) with 2 file(s) remaining
Completed 130.4 MiB/233.2 MiB (46.9 MiB/s) with 2 file(s) remaining
Completed 130.7 MiB/233.2 MiB (46.7 MiB/s) with 2 file(s) remaining
Completed 130.9 MiB/233.2 MiB (46.8 MiB/s) with 2 file(s) remaining
Completed 131.2 MiB/233.2 MiB (46.8 MiB/s) with 2 file(s) remaining
Completed 131.4 MiB/233.2 MiB (46.8 MiB/s) with 2 file(s) remaining
Completed 131.7 MiB/233.2 MiB (46.8 MiB/s) with 2 file(s) remaining
Completed 131.9 MiB/233.2 MiB (46.8 MiB/s) with 2 file(s) remaining
Completed 132.2 MiB/233.2 MiB (46.8 MiB/s) with 2 file(s) remaining
Completed 132.4 MiB/233.2 MiB (46.8 MiB/s) with 2 file(s) remaining
Completed 132.7 MiB/233.2 MiB (46.9 MiB/s) with 2 file(s) remaining
Completed 132.9 MiB/233.2 MiB (46.8 MiB/s) with 2 file(s) remaining
Completed 133.2 MiB/233.2 MiB (46.9 MiB/s) with 2 file(s) remaining
Completed 133.4 MiB/233.2 MiB (47.0 MiB/s) with 2 file(s) remaining
Completed 133.7 MiB/233.2 MiB (47.0 MiB/s) with 2 file(s) remaining
Completed 133.9 MiB/233.2 MiB (47.0 MiB/s) with 2 file(s) remaining
Completed 134.2 MiB/233.2 MiB (47.0 MiB/s) with 2 file(s) remaining
Completed 134.4 MiB/233.2 MiB (47.1 MiB/s) with 2 file(s) remaining
Completed 134.7 MiB/233.2 MiB (47.1 MiB/s) with 2 file(s) remaining
Completed 134.9 MiB/233.2 MiB (47.2 MiB/s) with 2 file(s) remaining
Completed 135.2 MiB/233.2 MiB (47.2 MiB/s) with 2 file(s) remaining
Completed 135.4 MiB/233.2 MiB (47.2 MiB/s) with 2 file(s) remaining
Completed 135.7 MiB/233.2 MiB (47.2 MiB/s) with 2 file(s) remaining
Completed 135.9 MiB/233.2 MiB (47.3 MiB/s) with 2 file(s) remaining
Completed 136.2 MiB/233.2 MiB (47.3 MiB/s) with 2 file(s) remaining
Completed 136.4 MiB/233.2 MiB (47.3 MiB/s) with 2 file(s) remaining
Completed 136.7 MiB/233.2 MiB (47.3 MiB/s) with 2 file(s) remaining
Completed 136.9 MiB/233.2 MiB (47.4 MiB/s) with 2 file(s) remaining
Completed 137.2 MiB/233.2 MiB (47.5 MiB/s) with 2 file(s) remaining
Completed 137.4 MiB/233.2 MiB (47.5 MiB/s) with 2 file(s) remaining
Completed 137.7 MiB/233.2 MiB (47.6 MiB/s) with 2 file(s) remaining
Completed 137.9 MiB/233.2 MiB (47.5 MiB/s) with 2 file(s) remaining
Completed 138.2 MiB/233.2 MiB (47.6 MiB/s) with 2 file(s) remaining
Completed 138.4 MiB/233.2 MiB (47.6 MiB/s) with 2 file(s) remaining
Completed 138.7 MiB/233.2 MiB (47.7 MiB/s) with 2 file(s) remaining
Completed 138.9 MiB/233.2 MiB (47.7 MiB/s) with 2 file(s) remaining
Completed 139.2 MiB/233.2 MiB (47.7 MiB/s) with 2 file(s) remaining
Completed 139.4 MiB/233.2 MiB (47.8 MiB/s) with 2 file(s) remaining
Completed 139.7 MiB/233.2 MiB (47.8 MiB/s) with 2 file(s) remaining
Completed 139.9 MiB/233.2 MiB (47.7 MiB/s) with 2 file(s) remaining
Completed 140.2 MiB/233.2 MiB (47.8 MiB/s) with 2 file(s) remaining
Completed 140.4 MiB/233.2 MiB (47.8 MiB/s) with 2 file(s) remaining
Completed 140.7 MiB/233.2 MiB (47.7 MiB/s) with 2 file(s) remaining
Completed 140.9 MiB/233.2 MiB (47.7 MiB/s) with 2 file(s) remaining
Completed 141.2 MiB/233.2 MiB (47.6 MiB/s) with 2 file(s) remaining
Completed 141.4 MiB/233.2 MiB (47.6 MiB/s) with 2 file(s) remaining
Completed 141.7 MiB/233.2 MiB (47.6 MiB/s) with 2 file(s) remaining
Completed 141.9 MiB/233.2 MiB (47.7 MiB/s) with 2 file(s) remaining
Completed 142.2 MiB/233.2 MiB (47.7 MiB/s) with 2 file(s) remaining
Completed 142.4 MiB/233.2 MiB (47.7 MiB/s) with 2 file(s) remaining
Completed 142.7 MiB/233.2 MiB (47.8 MiB/s) with 2 file(s) remaining
Completed 142.9 MiB/233.2 MiB (47.8 MiB/s) with 2 file(s) remaining
Completed 143.2 MiB/233.2 MiB (47.8 MiB/s) with 2 file(s) remaining
Completed 143.4 MiB/233.2 MiB (47.8 MiB/s) with 2 file(s) remaining
Completed 143.7 MiB/233.2 MiB (47.8 MiB/s) with 2 file(s) remaining
Completed 143.9 MiB/233.2 MiB (47.9 MiB/s) with 2 file(s) remaining
Completed 144.2 MiB/233.2 MiB (47.9 MiB/s) with 2 file(s) remaining
Completed 144.4 MiB/233.2 MiB (47.9 MiB/s) with 2 file(s) remaining
Completed 144.7 MiB/233.2 MiB (48.0 MiB/s) with 2 file(s) remaining
Completed 144.9 MiB/233.2 MiB (48.0 MiB/s) with 2 file(s) remaining
Completed 145.2 MiB/233.2 MiB (48.0 MiB/s) with 2 file(s) remaining
Completed 145.4 MiB/233.2 MiB (48.1 MiB/s) with 2 file(s) remaining
Completed 145.7 MiB/233.2 MiB (48.1 MiB/s) with 2 file(s) remaining
Completed 145.9 MiB/233.2 MiB (48.2 MiB/s) with 2 file(s) remaining
Completed 146.2 MiB/233.2 MiB (48.2 MiB/s) with 2 file(s) remaining
Completed 146.4 MiB/233.2 MiB (48.2 MiB/s) with 2 file(s) remaining
Completed 146.7 MiB/233.2 MiB (48.3 MiB/s) with 2 file(s) remaining
Completed 146.9 MiB/233.2 MiB (48.3 MiB/s) with 2 file(s) remaining
Completed 147.2 MiB/233.2 MiB (48.3 MiB/s) with 2 file(s) remaining
Completed 147.4 MiB/233.2 MiB (48.4 MiB/s) with 2 file(s) remaining
Completed 147.7 MiB/233.2 MiB (48.4 MiB/s) with 2 file(s) remaining
Completed 147.9 MiB/233.2 MiB (48.4 MiB/s) with 2 file(s) remaining
Completed 148.2 MiB/233.2 MiB (48.5 MiB/s) with 2 file(s) remaining
Completed 148.4 MiB/233.2 MiB (48.5 MiB/s) with 2 file(s) remaining
Completed 148.7 MiB/233.2 MiB (48.5 MiB/s) with 2 file(s) remaining
Completed 148.9 MiB/233.2 MiB (48.6 MiB/s) with 2 file(s) remaining
Completed 149.2 MiB/233.2 MiB (48.6 MiB/s) with 2 file(s) remaining
Completed 149.4 MiB/233.2 MiB (48.6 MiB/s) with 2 file(s) remaining
Completed 149.7 MiB/233.2 MiB (48.7 MiB/s) with 2 file(s) remaining
Completed 149.9 MiB/233.2 MiB (48.7 MiB/s) with 2 file(s) remaining
Completed 150.2 MiB/233.2 MiB (48.8 MiB/s) with 2 file(s) remaining
Completed 150.4 MiB/233.2 MiB (48.8 MiB/s) with 2 file(s) remaining
Completed 150.7 MiB/233.2 MiB (48.8 MiB/s) with 2 file(s) remaining
Completed 150.9 MiB/233.2 MiB (48.7 MiB/s) with 2 file(s) remaining
Completed 151.2 MiB/233.2 MiB (48.3 MiB/s) with 2 file(s) remaining
Completed 151.4 MiB/233.2 MiB (47.0 MiB/s) with 2 file(s) remaining
Completed 151.7 MiB/233.2 MiB (47.1 MiB/s) with 2 file(s) remaining
Completed 151.9 MiB/233.2 MiB (47.2 MiB/s) with 2 file(s) remaining
Completed 152.2 MiB/233.2 MiB (47.2 MiB/s) with 2 file(s) remaining
Completed 152.4 MiB/233.2 MiB (47.3 MiB/s) with 2 file(s) remaining
Completed 152.7 MiB/233.2 MiB (47.4 MiB/s) with 2 file(s) remaining
Completed 152.9 MiB/233.2 MiB (47.4 MiB/s) with 2 file(s) remaining
Completed 153.2 MiB/233.2 MiB (47.5 MiB/s) with 2 file(s) remaining
Completed 153.4 MiB/233.2 MiB (47.6 MiB/s) with 2 file(s) remaining
Completed 153.7 MiB/233.2 MiB (47.6 MiB/s) with 2 file(s) remaining
Completed 153.9 MiB/233.2 MiB (47.7 MiB/s) with 2 file(s) remaining
Completed 154.2 MiB/233.2 MiB (47.7 MiB/s) with 2 file(s) remaining
Completed 154.4 MiB/233.2 MiB (47.7 MiB/s) with 2 file(s) remaining
Completed 154.7 MiB/233.2 MiB (47.8 MiB/s) with 2 file(s) remaining
Completed 154.9 MiB/233.2 MiB (47.8 MiB/s) with 2 file(s) remaining
Completed 155.2 MiB/233.2 MiB (47.8 MiB/s) with 2 file(s) remaining
Completed 155.4 MiB/233.2 MiB (47.8 MiB/s) with 2 file(s) remaining
Completed 155.7 MiB/233.2 MiB (47.9 MiB/s) with 2 file(s) remaining
Completed 155.9 MiB/233.2 MiB (47.9 MiB/s) with 2 file(s) remaining
Completed 156.2 MiB/233.2 MiB (47.9 MiB/s) with 2 file(s) remaining
Completed 156.4 MiB/233.2 MiB (48.0 MiB/s) with 2 file(s) remaining
Completed 156.7 MiB/233.2 MiB (48.0 MiB/s) with 2 file(s) remaining
Completed 156.9 MiB/233.2 MiB (48.0 MiB/s) with 2 file(s) remaining
Completed 157.2 MiB/233.2 MiB (48.1 MiB/s) with 2 file(s) remaining
Completed 157.4 MiB/233.2 MiB (48.1 MiB/s) with 2 file(s) remaining
Completed 157.7 MiB/233.2 MiB (48.1 MiB/s) with 2 file(s) remaining
Completed 157.9 MiB/233.2 MiB (48.1 MiB/s) with 2 file(s) remaining
Completed 158.2 MiB/233.2 MiB (48.1 MiB/s) with 2 file(s) remaining
Completed 158.4 MiB/233.2 MiB (48.1 MiB/s) with 2 file(s) remaining
Completed 158.7 MiB/233.2 MiB (48.2 MiB/s) with 2 file(s) remaining
Completed 158.9 MiB/233.2 MiB (48.2 MiB/s) with 2 file(s) remaining
Completed 159.2 MiB/233.2 MiB (48.2 MiB/s) with 2 file(s) remaining
Completed 159.4 MiB/233.2 MiB (46.3 MiB/s) with 2 file(s) remaining
Completed 159.7 MiB/233.2 MiB (46.3 MiB/s) with 2 file(s) remaining
Completed 159.9 MiB/233.2 MiB (46.4 MiB/s) with 2 file(s) remaining
Completed 160.2 MiB/233.2 MiB (46.5 MiB/s) with 2 file(s) remaining
Completed 160.4 MiB/233.2 MiB (46.5 MiB/s) with 2 file(s) remaining
Completed 160.7 MiB/233.2 MiB (46.5 MiB/s) with 2 file(s) remaining
Completed 160.9 MiB/233.2 MiB (46.6 MiB/s) with 2 file(s) remaining
Completed 161.2 MiB/233.2 MiB (46.7 MiB/s) with 2 file(s) remaining
Completed 161.4 MiB/233.2 MiB (46.7 MiB/s) with 2 file(s) remaining
Completed 161.7 MiB/233.2 MiB (46.8 MiB/s) with 2 file(s) remaining
Completed 161.9 MiB/233.2 MiB (46.8 MiB/s) with 2 file(s) remaining
Completed 162.2 MiB/233.2 MiB (46.8 MiB/s) with 2 file(s) remaining
Completed 162.4 MiB/233.2 MiB (46.8 MiB/s) with 2 file(s) remaining
Completed 162.7 MiB/233.2 MiB (46.9 MiB/s) with 2 file(s) remaining
Completed 162.9 MiB/233.2 MiB (46.9 MiB/s) with 2 file(s) remaining
Completed 163.2 MiB/233.2 MiB (46.9 MiB/s) with 2 file(s) remaining
Completed 163.4 MiB/233.2 MiB (46.9 MiB/s) with 2 file(s) remaining
Completed 163.7 MiB/233.2 MiB (46.9 MiB/s) with 2 file(s) remaining
Completed 163.9 MiB/233.2 MiB (46.9 MiB/s) with 2 file(s) remaining
Completed 164.2 MiB/233.2 MiB (46.9 MiB/s) with 2 file(s) remaining
Completed 164.4 MiB/233.2 MiB (47.0 MiB/s) with 2 file(s) remaining
Completed 164.7 MiB/233.2 MiB (47.0 MiB/s) with 2 file(s) remaining
Completed 164.9 MiB/233.2 MiB (47.1 MiB/s) with 2 file(s) remaining
Completed 165.2 MiB/233.2 MiB (47.1 MiB/s) with 2 file(s) remaining
Completed 165.4 MiB/233.2 MiB (47.1 MiB/s) with 2 file(s) remaining
Completed 165.7 MiB/233.2 MiB (47.2 MiB/s) with 2 file(s) remaining
Completed 165.9 MiB/233.2 MiB (47.2 MiB/s) with 2 file(s) remaining
Completed 166.2 MiB/233.2 MiB (47.3 MiB/s) with 2 file(s) remaining
Completed 166.4 MiB/233.2 MiB (47.3 MiB/s) with 2 file(s) remaining
Completed 166.7 MiB/233.2 MiB (47.3 MiB/s) with 2 file(s) remaining
Completed 166.9 MiB/233.2 MiB (47.4 MiB/s) with 2 file(s) remaining
Completed 167.2 MiB/233.2 MiB (47.4 MiB/s) with 2 file(s) remaining
Completed 167.4 MiB/233.2 MiB (47.4 MiB/s) with 2 file(s) remaining
Completed 167.7 MiB/233.2 MiB (47.5 MiB/s) with 2 file(s) remaining
Completed 167.9 MiB/233.2 MiB (47.5 MiB/s) with 2 file(s) remaining
Completed 168.2 MiB/233.2 MiB (47.6 MiB/s) with 2 file(s) remaining
Completed 168.4 MiB/233.2 MiB (46.5 MiB/s) with 2 file(s) remaining
Completed 168.7 MiB/233.2 MiB (46.6 MiB/s) with 2 file(s) remaining
Completed 168.9 MiB/233.2 MiB (46.6 MiB/s) with 2 file(s) remaining
Completed 169.2 MiB/233.2 MiB (46.7 MiB/s) with 2 file(s) remaining
Completed 169.4 MiB/233.2 MiB (46.7 MiB/s) with 2 file(s) remaining
Completed 169.7 MiB/233.2 MiB (46.8 MiB/s) with 2 file(s) remaining
Completed 169.9 MiB/233.2 MiB (46.9 MiB/s) with 2 file(s) remaining
Completed 170.2 MiB/233.2 MiB (46.9 MiB/s) with 2 file(s) remaining
Completed 170.4 MiB/233.2 MiB (47.0 MiB/s) with 2 file(s) remaining
Completed 170.7 MiB/233.2 MiB (47.0 MiB/s) with 2 file(s) remaining
Completed 170.9 MiB/233.2 MiB (47.0 MiB/s) with 2 file(s) remaining
Completed 171.2 MiB/233.2 MiB (47.0 MiB/s) with 2 file(s) remaining
Completed 171.4 MiB/233.2 MiB (47.1 MiB/s) with 2 file(s) remaining
Completed 171.7 MiB/233.2 MiB (47.1 MiB/s) with 2 file(s) remaining
Completed 171.9 MiB/233.2 MiB (47.1 MiB/s) with 2 file(s) remaining
Completed 172.2 MiB/233.2 MiB (47.2 MiB/s) with 2 file(s) remaining
Completed 172.4 MiB/233.2 MiB (47.2 MiB/s) with 2 file(s) remaining
Completed 172.7 MiB/233.2 MiB (47.2 MiB/s) with 2 file(s) remaining
Completed 172.9 MiB/233.2 MiB (47.2 MiB/s) with 2 file(s) remaining
Completed 173.2 MiB/233.2 MiB (47.3 MiB/s) with 2 file(s) remaining
Completed 173.4 MiB/233.2 MiB (47.3 MiB/s) with 2 file(s) remaining
Completed 173.7 MiB/233.2 MiB (47.3 MiB/s) with 2 file(s) remaining
Completed 173.9 MiB/233.2 MiB (47.3 MiB/s) with 2 file(s) remaining
Completed 174.2 MiB/233.2 MiB (47.4 MiB/s) with 2 file(s) remaining
Completed 174.4 MiB/233.2 MiB (47.4 MiB/s) with 2 file(s) remaining
Completed 174.7 MiB/233.2 MiB (47.4 MiB/s) with 2 file(s) remaining
Completed 174.9 MiB/233.2 MiB (47.5 MiB/s) with 2 file(s) remaining
Completed 175.2 MiB/233.2 MiB (47.5 MiB/s) with 2 file(s) remaining
Completed 175.4 MiB/233.2 MiB (47.6 MiB/s) with 2 file(s) remaining
Completed 175.7 MiB/233.2 MiB (47.6 MiB/s) with 2 file(s) remaining
Completed 175.9 MiB/233.2 MiB (47.7 MiB/s) with 2 file(s) remaining
Completed 176.2 MiB/233.2 MiB (47.7 MiB/s) with 2 file(s) remaining
Completed 176.4 MiB/233.2 MiB (44.8 MiB/s) with 2 file(s) remaining
Completed 176.7 MiB/233.2 MiB (44.8 MiB/s) with 2 file(s) remaining
Completed 176.9 MiB/233.2 MiB (44.9 MiB/s) with 2 file(s) remaining
Completed 177.2 MiB/233.2 MiB (44.9 MiB/s) with 2 file(s) remaining
Completed 177.4 MiB/233.2 MiB (44.7 MiB/s) with 2 file(s) remaining
Completed 177.7 MiB/233.2 MiB (44.2 MiB/s) with 2 file(s) remaining
Completed 177.9 MiB/233.2 MiB (43.7 MiB/s) with 2 file(s) remaining
Completed 178.2 MiB/233.2 MiB (43.8 MiB/s) with 2 file(s) remaining
Completed 178.4 MiB/233.2 MiB (43.8 MiB/s) with 2 file(s) remaining
Completed 178.7 MiB/233.2 MiB (43.9 MiB/s) with 2 file(s) remaining
Completed 178.9 MiB/233.2 MiB (43.7 MiB/s) with 2 file(s) remaining
Completed 179.2 MiB/233.2 MiB (43.5 MiB/s) with 2 file(s) remaining
Completed 179.4 MiB/233.2 MiB (41.2 MiB/s) with 2 file(s) remaining
Completed 179.7 MiB/233.2 MiB (41.3 MiB/s) with 2 file(s) remaining
Completed 179.9 MiB/233.2 MiB (41.3 MiB/s) with 2 file(s) remaining
Completed 180.2 MiB/233.2 MiB (41.3 MiB/s) with 2 file(s) remaining
Completed 180.4 MiB/233.2 MiB (41.4 MiB/s) with 2 file(s) remaining
Completed 180.7 MiB/233.2 MiB (41.4 MiB/s) with 2 file(s) remaining
Completed 180.9 MiB/233.2 MiB (41.5 MiB/s) with 2 file(s) remaining
Completed 181.2 MiB/233.2 MiB (41.5 MiB/s) with 2 file(s) remaining
Completed 181.4 MiB/233.2 MiB (41.5 MiB/s) with 2 file(s) remaining
Completed 181.7 MiB/233.2 MiB (41.6 MiB/s) with 2 file(s) remaining
Completed 181.9 MiB/233.2 MiB (41.6 MiB/s) with 2 file(s) remaining
Completed 182.2 MiB/233.2 MiB (41.6 MiB/s) with 2 file(s) remaining
Completed 182.4 MiB/233.2 MiB (41.7 MiB/s) with 2 file(s) remaining
Completed 182.7 MiB/233.2 MiB (41.7 MiB/s) with 2 file(s) remaining
Completed 182.9 MiB/233.2 MiB (41.7 MiB/s) with 2 file(s) remaining
Completed 183.2 MiB/233.2 MiB (41.8 MiB/s) with 2 file(s) remaining
Completed 183.4 MiB/233.2 MiB (41.8 MiB/s) with 2 file(s) remaining
Completed 183.7 MiB/233.2 MiB (41.8 MiB/s) with 2 file(s) remaining
Completed 183.9 MiB/233.2 MiB (41.9 MiB/s) with 2 file(s) remaining
Completed 184.2 MiB/233.2 MiB (41.9 MiB/s) with 2 file(s) remaining
Completed 184.4 MiB/233.2 MiB (42.0 MiB/s) with 2 file(s) remaining
Completed 184.7 MiB/233.2 MiB (42.0 MiB/s) with 2 file(s) remaining
Completed 184.9 MiB/233.2 MiB (42.0 MiB/s) with 2 file(s) remaining
Completed 185.2 MiB/233.2 MiB (42.1 MiB/s) with 2 file(s) remaining
Completed 185.4 MiB/233.2 MiB (42.1 MiB/s) with 2 file(s) remaining
Completed 185.7 MiB/233.2 MiB (42.2 MiB/s) with 2 file(s) remaining
Completed 185.9 MiB/233.2 MiB (42.2 MiB/s) with 2 file(s) remaining
Completed 186.2 MiB/233.2 MiB (42.3 MiB/s) with 2 file(s) remaining
Completed 186.4 MiB/233.2 MiB (42.3 MiB/s) with 2 file(s) remaining
Completed 186.7 MiB/233.2 MiB (42.3 MiB/s) with 2 file(s) remaining
Completed 186.9 MiB/233.2 MiB (42.4 MiB/s) with 2 file(s) remaining
Completed 187.2 MiB/233.2 MiB (42.4 MiB/s) with 2 file(s) remaining
Completed 187.4 MiB/233.2 MiB (42.4 MiB/s) with 2 file(s) remaining
Completed 187.7 MiB/233.2 MiB (42.5 MiB/s) with 2 file(s) remaining
Completed 187.9 MiB/233.2 MiB (42.5 MiB/s) with 2 file(s) remaining
Completed 188.2 MiB/233.2 MiB (42.5 MiB/s) with 2 file(s) remaining
Completed 188.4 MiB/233.2 MiB (42.5 MiB/s) with 2 file(s) remaining
Completed 188.7 MiB/233.2 MiB (42.5 MiB/s) with 2 file(s) remaining
Completed 188.9 MiB/233.2 MiB (42.5 MiB/s) with 2 file(s) remaining
Completed 189.2 MiB/233.2 MiB (42.4 MiB/s) with 2 file(s) remaining
Completed 189.4 MiB/233.2 MiB (42.4 MiB/s) with 2 file(s) remaining
Completed 189.7 MiB/233.2 MiB (42.3 MiB/s) with 2 file(s) remaining
Completed 189.9 MiB/233.2 MiB (42.3 MiB/s) with 2 file(s) remaining
Completed 190.2 MiB/233.2 MiB (42.2 MiB/s) with 2 file(s) remaining
Completed 190.4 MiB/233.2 MiB (42.2 MiB/s) with 2 file(s) remaining
Completed 190.7 MiB/233.2 MiB (42.1 MiB/s) with 2 file(s) remaining
Completed 190.9 MiB/233.2 MiB (42.1 MiB/s) with 2 file(s) remaining
Completed 191.2 MiB/233.2 MiB (42.0 MiB/s) with 2 file(s) remaining
Completed 191.4 MiB/233.2 MiB (42.0 MiB/s) with 2 file(s) remaining
Completed 191.7 MiB/233.2 MiB (42.0 MiB/s) with 2 file(s) remaining
Completed 191.9 MiB/233.2 MiB (42.0 MiB/s) with 2 file(s) remaining
Completed 192.2 MiB/233.2 MiB (41.9 MiB/s) with 2 file(s) remaining
Completed 192.4 MiB/233.2 MiB (42.0 MiB/s) with 2 file(s) remaining
Completed 192.7 MiB/233.2 MiB (42.0 MiB/s) with 2 file(s) remaining
Completed 192.9 MiB/233.2 MiB (42.1 MiB/s) with 2 file(s) remaining
Completed 193.2 MiB/233.2 MiB (42.1 MiB/s) with 2 file(s) remaining
Completed 193.4 MiB/233.2 MiB (42.2 MiB/s) with 2 file(s) remaining
Completed 193.7 MiB/233.2 MiB (42.2 MiB/s) with 2 file(s) remaining
Completed 193.9 MiB/233.2 MiB (42.3 MiB/s) with 2 file(s) remaining
Completed 194.2 MiB/233.2 MiB (42.3 MiB/s) with 2 file(s) remaining
Completed 194.4 MiB/233.2 MiB (42.3 MiB/s) with 2 file(s) remaining
Completed 194.7 MiB/233.2 MiB (42.4 MiB/s) with 2 file(s) remaining
Completed 194.9 MiB/233.2 MiB (42.4 MiB/s) with 2 file(s) remaining
Completed 195.2 MiB/233.2 MiB (42.5 MiB/s) with 2 file(s) remaining
Completed 195.4 MiB/233.2 MiB (42.5 MiB/s) with 2 file(s) remaining
Completed 195.7 MiB/233.2 MiB (42.6 MiB/s) with 2 file(s) remaining
Completed 195.9 MiB/233.2 MiB (42.6 MiB/s) with 2 file(s) remaining
Completed 196.2 MiB/233.2 MiB (42.6 MiB/s) with 2 file(s) remaining
Completed 196.4 MiB/233.2 MiB (42.0 MiB/s) with 2 file(s) remaining
Completed 196.7 MiB/233.2 MiB (41.8 MiB/s) with 2 file(s) remaining
Completed 196.9 MiB/233.2 MiB (41.5 MiB/s) with 2 file(s) remaining
Completed 197.2 MiB/233.2 MiB (41.1 MiB/s) with 2 file(s) remaining
Completed 197.4 MiB/233.2 MiB (40.9 MiB/s) with 2 file(s) remaining
Completed 197.7 MiB/233.2 MiB (40.9 MiB/s) with 2 file(s) remaining
Completed 197.9 MiB/233.2 MiB (41.0 MiB/s) with 2 file(s) remaining
Completed 198.2 MiB/233.2 MiB (41.0 MiB/s) with 2 file(s) remaining
Completed 198.4 MiB/233.2 MiB (41.1 MiB/s) with 2 file(s) remaining
Completed 198.7 MiB/233.2 MiB (41.1 MiB/s) with 2 file(s) remaining
Completed 198.9 MiB/233.2 MiB (41.2 MiB/s) with 2 file(s) remaining
Completed 199.2 MiB/233.2 MiB (41.2 MiB/s) with 2 file(s) remaining
Completed 199.4 MiB/233.2 MiB (41.2 MiB/s) with 2 file(s) remaining
Completed 199.7 MiB/233.2 MiB (41.3 MiB/s) with 2 file(s) remaining
Completed 199.9 MiB/233.2 MiB (41.3 MiB/s) with 2 file(s) remaining
Completed 200.2 MiB/233.2 MiB (41.3 MiB/s) with 2 file(s) remaining
Completed 200.4 MiB/233.2 MiB (41.3 MiB/s) with 2 file(s) remaining
Completed 200.7 MiB/233.2 MiB (41.4 MiB/s) with 2 file(s) remaining
Completed 200.9 MiB/233.2 MiB (41.4 MiB/s) with 2 file(s) remaining
Completed 201.2 MiB/233.2 MiB (41.4 MiB/s) with 2 file(s) remaining
Completed 201.4 MiB/233.2 MiB (41.5 MiB/s) with 2 file(s) remaining
Completed 201.7 MiB/233.2 MiB (41.5 MiB/s) with 2 file(s) remaining
Completed 201.9 MiB/233.2 MiB (41.5 MiB/s) with 2 file(s) remaining
Completed 202.2 MiB/233.2 MiB (41.6 MiB/s) with 2 file(s) remaining
Completed 202.4 MiB/233.2 MiB (41.6 MiB/s) with 2 file(s) remaining
Completed 202.7 MiB/233.2 MiB (41.6 MiB/s) with 2 file(s) remaining
Completed 202.9 MiB/233.2 MiB (41.7 MiB/s) with 2 file(s) remaining
Completed 203.2 MiB/233.2 MiB (41.7 MiB/s) with 2 file(s) remaining
Completed 203.4 MiB/233.2 MiB (41.7 MiB/s) with 2 file(s) remaining
Completed 203.7 MiB/233.2 MiB (41.8 MiB/s) with 2 file(s) remaining
Completed 203.9 MiB/233.2 MiB (41.8 MiB/s) with 2 file(s) remaining
Completed 204.2 MiB/233.2 MiB (41.8 MiB/s) with 2 file(s) remaining
Completed 204.4 MiB/233.2 MiB (41.9 MiB/s) with 2 file(s) remaining
Completed 204.7 MiB/233.2 MiB (41.9 MiB/s) with 2 file(s) remaining
Completed 204.9 MiB/233.2 MiB (41.9 MiB/s) with 2 file(s) remaining
Completed 205.2 MiB/233.2 MiB (42.0 MiB/s) with 2 file(s) remaining
Completed 205.4 MiB/233.2 MiB (42.0 MiB/s) with 2 file(s) remaining
Completed 205.7 MiB/233.2 MiB (42.0 MiB/s) with 2 file(s) remaining
Completed 205.9 MiB/233.2 MiB (42.1 MiB/s) with 2 file(s) remaining
Completed 206.2 MiB/233.2 MiB (41.9 MiB/s) with 2 file(s) remaining
Completed 206.4 MiB/233.2 MiB (41.5 MiB/s) with 2 file(s) remaining
Completed 206.7 MiB/233.2 MiB (41.2 MiB/s) with 2 file(s) remaining
Completed 206.9 MiB/233.2 MiB (40.9 MiB/s) with 2 file(s) remaining
Completed 207.2 MiB/233.2 MiB (40.6 MiB/s) with 2 file(s) remaining
Completed 207.4 MiB/233.2 MiB (40.4 MiB/s) with 2 file(s) remaining
Completed 207.7 MiB/233.2 MiB (40.5 MiB/s) with 2 file(s) remaining
Completed 207.9 MiB/233.2 MiB (40.5 MiB/s) with 2 file(s) remaining
Completed 208.2 MiB/233.2 MiB (40.6 MiB/s) with 2 file(s) remaining
Completed 208.4 MiB/233.2 MiB (40.5 MiB/s) with 2 file(s) remaining
Completed 208.7 MiB/233.2 MiB (40.5 MiB/s) with 2 file(s) remaining
Completed 208.9 MiB/233.2 MiB (40.2 MiB/s) with 2 file(s) remaining
Completed 209.2 MiB/233.2 MiB (39.9 MiB/s) with 2 file(s) remaining
Completed 209.4 MiB/233.2 MiB (39.9 MiB/s) with 2 file(s) remaining
Completed 209.7 MiB/233.2 MiB (40.0 MiB/s) with 2 file(s) remaining
Completed 209.9 MiB/233.2 MiB (40.0 MiB/s) with 2 file(s) remaining
Completed 210.2 MiB/233.2 MiB (40.0 MiB/s) with 2 file(s) remaining
Completed 210.4 MiB/233.2 MiB (40.1 MiB/s) with 2 file(s) remaining
Completed 210.7 MiB/233.2 MiB (40.1 MiB/s) with 2 file(s) remaining
Completed 210.9 MiB/233.2 MiB (40.1 MiB/s) with 2 file(s) remaining
Completed 211.2 MiB/233.2 MiB (40.2 MiB/s) with 2 file(s) remaining
Completed 211.4 MiB/233.2 MiB (40.2 MiB/s) with 2 file(s) remaining
Completed 211.7 MiB/233.2 MiB (40.2 MiB/s) with 2 file(s) remaining
Completed 211.9 MiB/233.2 MiB (40.2 MiB/s) with 2 file(s) remaining
Completed 212.2 MiB/233.2 MiB (40.3 MiB/s) with 2 file(s) remaining
Completed 212.4 MiB/233.2 MiB (40.3 MiB/s) with 2 file(s) remaining
Completed 212.7 MiB/233.2 MiB (40.3 MiB/s) with 2 file(s) remaining
Completed 212.9 MiB/233.2 MiB (40.4 MiB/s) with 2 file(s) remaining
Completed 213.2 MiB/233.2 MiB (40.4 MiB/s) with 2 file(s) remaining
Completed 213.4 MiB/233.2 MiB (40.4 MiB/s) with 2 file(s) remaining
Completed 213.7 MiB/233.2 MiB (40.5 MiB/s) with 2 file(s) remaining
Completed 213.9 MiB/233.2 MiB (40.5 MiB/s) with 2 file(s) remaining
Completed 214.2 MiB/233.2 MiB (40.5 MiB/s) with 2 file(s) remaining
Completed 214.4 MiB/233.2 MiB (40.5 MiB/s) with 2 file(s) remaining
Completed 214.7 MiB/233.2 MiB (40.6 MiB/s) with 2 file(s) remaining
Completed 214.9 MiB/233.2 MiB (40.6 MiB/s) with 2 file(s) remaining
Completed 215.2 MiB/233.2 MiB (40.6 MiB/s) with 2 file(s) remaining
Completed 215.4 MiB/233.2 MiB (38.5 MiB/s) with 2 file(s) remaining
Completed 215.7 MiB/233.2 MiB (38.5 MiB/s) with 2 file(s) remaining
Completed 215.9 MiB/233.2 MiB (38.5 MiB/s) with 2 file(s) remaining
Completed 216.2 MiB/233.2 MiB (38.6 MiB/s) with 2 file(s) remaining
Completed 216.4 MiB/233.2 MiB (38.6 MiB/s) with 2 file(s) remaining
Completed 216.7 MiB/233.2 MiB (38.6 MiB/s) with 2 file(s) remaining
Completed 216.9 MiB/233.2 MiB (38.6 MiB/s) with 2 file(s) remaining
Completed 217.2 MiB/233.2 MiB (38.7 MiB/s) with 2 file(s) remaining
Completed 217.4 MiB/233.2 MiB (38.7 MiB/s) with 2 file(s) remaining
Completed 217.7 MiB/233.2 MiB (38.7 MiB/s) with 2 file(s) remaining
Completed 217.9 MiB/233.2 MiB (38.7 MiB/s) with 2 file(s) remaining
Completed 218.2 MiB/233.2 MiB (38.8 MiB/s) with 2 file(s) remaining
Completed 218.4 MiB/233.2 MiB (38.7 MiB/s) with 2 file(s) remaining
Completed 218.7 MiB/233.2 MiB (38.3 MiB/s) with 2 file(s) remaining
Completed 218.9 MiB/233.2 MiB (37.8 MiB/s) with 2 file(s) remaining
Completed 219.2 MiB/233.2 MiB (37.6 MiB/s) with 2 file(s) remaining
Completed 219.4 MiB/233.2 MiB (37.1 MiB/s) with 2 file(s) remaining
Completed 219.7 MiB/233.2 MiB (36.6 MiB/s) with 2 file(s) remaining
Completed 219.9 MiB/233.2 MiB (36.4 MiB/s) with 2 file(s) remaining
Completed 220.2 MiB/233.2 MiB (36.4 MiB/s) with 2 file(s) remaining
Completed 220.4 MiB/233.2 MiB (36.5 MiB/s) with 2 file(s) remaining
Completed 220.7 MiB/233.2 MiB (36.5 MiB/s) with 2 file(s) remaining
Completed 220.9 MiB/233.2 MiB (36.5 MiB/s) with 2 file(s) remaining
Completed 221.2 MiB/233.2 MiB (36.6 MiB/s) with 2 file(s) remaining
Completed 221.4 MiB/233.2 MiB (36.6 MiB/s) with 2 file(s) remaining
Completed 221.7 MiB/233.2 MiB (36.6 MiB/s) with 2 file(s) remaining
Completed 221.9 MiB/233.2 MiB (36.7 MiB/s) with 2 file(s) remaining
Completed 222.2 MiB/233.2 MiB (36.7 MiB/s) with 2 file(s) remaining
Completed 222.4 MiB/233.2 MiB (36.7 MiB/s) with 2 file(s) remaining
Completed 222.7 MiB/233.2 MiB (36.7 MiB/s) with 2 file(s) remaining
Completed 222.9 MiB/233.2 MiB (36.8 MiB/s) with 2 file(s) remaining
Completed 223.2 MiB/233.2 MiB (36.8 MiB/s) with 2 file(s) remaining
Completed 223.4 MiB/233.2 MiB (36.8 MiB/s) with 2 file(s) remaining
Completed 223.7 MiB/233.2 MiB (36.9 MiB/s) with 2 file(s) remaining
Completed 223.9 MiB/233.2 MiB (36.9 MiB/s) with 2 file(s) remaining
Completed 224.2 MiB/233.2 MiB (36.9 MiB/s) with 2 file(s) remaining
Completed 224.4 MiB/233.2 MiB (36.9 MiB/s) with 2 file(s) remaining
Completed 224.7 MiB/233.2 MiB (37.0 MiB/s) with 2 file(s) remaining
Completed 224.9 MiB/233.2 MiB (37.0 MiB/s) with 2 file(s) remaining
Completed 225.2 MiB/233.2 MiB (37.0 MiB/s) with 2 file(s) remaining
Completed 225.4 MiB/233.2 MiB (37.0 MiB/s) with 2 file(s) remaining
Completed 225.7 MiB/233.2 MiB (37.1 MiB/s) with 2 file(s) remaining
Completed 225.9 MiB/233.2 MiB (37.1 MiB/s) with 2 file(s) remaining
Completed 226.2 MiB/233.2 MiB (37.1 MiB/s) with 2 file(s) remaining
Completed 226.4 MiB/233.2 MiB (37.1 MiB/s) with 2 file(s) remaining
Completed 226.7 MiB/233.2 MiB (37.2 MiB/s) with 2 file(s) remaining
Completed 226.9 MiB/233.2 MiB (37.2 MiB/s) with 2 file(s) remaining
Completed 227.2 MiB/233.2 MiB (37.2 MiB/s) with 2 file(s) remaining
Completed 227.4 MiB/233.2 MiB (37.3 MiB/s) with 2 file(s) remaining
Completed 227.7 MiB/233.2 MiB (37.3 MiB/s) with 2 file(s) remaining
Completed 227.9 MiB/233.2 MiB (37.3 MiB/s) with 2 file(s) remaining
Completed 228.2 MiB/233.2 MiB (37.3 MiB/s) with 2 file(s) remaining
Completed 228.4 MiB/233.2 MiB ...Truncated

**Comment by harshavardhana** [comment]
ping @vadmeste

**Review by vadmeste — APPROVED** [review]
LGTM & tested
