### PR TITLE
azure: allow parts > 100MiB size to work properly

### LINKED ISSUE #4868: azure: allow parts > 100MiB size to work properly
Currently if any multipart part sizing > 100MiB throws an error.  Such parts can be handled by chunking them into 100MiB and upload them into azure block blob.  Below is the discussion snippet.
```
As per discussion with @abperiasamy, this is gateway issue not supporting 525MB or any allowable S3 part size. If data in stream is >100MB, Azure gateway code needs to split into new parts internally i.e. every 100MB of data is created with separate parts till end of stream.
```
Refer #4640

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Version used (`minio version`):
* Environment name and version (e.g. nginx 1.9.1):
* Server type and version:
* Operating System and version (`uname -a`):
* Link to your project:

### PR DESCRIPTION
**Pull request by balamurugana**
Previously if any multipart part size > 100MiB is uploaded, azure
gateway returns error.

This patch fixes the issue by creating sub parts sizing each 100MiB of
given multipart part.  On complete multipart, it fetches all uploaded
azure block ids for each parts and performs completion.

Fixes #4868

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

File: cmd/gateway-azure.go [hunk 1]
```diff
@@ -550,10 +552,25 @@ func (a *azureObjects) PutObjectPart(bucket, object, uploadID string, partID int
...
-	if err != nil {
-		return info, azureToObjectError(traceError(err), bucket, object)
+	subPartCount := size / azureBlockSize
+	lastSubPartSize := size - subPartCount*azureBlockSize
+	if lastSubPartSize != 0 {
+		subPartCount++
+	} else {
+		lastSubPartSize = azureBlockSize
+	}
+
```
Comment (krishnasrinivas) [inline cmd/gateway-azure.go]: instead of pre-calculating subPartCount and lastSubPartSize above, doing it the following way looks easier to read (subjective opinion):
```
        remaining := size                                                                               
        subPartNumber := 1                                                                              
        for {                                                                                           
                subPartSize := remaining                                                                
                if subPartSize > azureBlockSize {                                                       
                        subPartSize = azureBlockSize                                                    
                }                                                                                       
                remaining = remaining - subPartSize                                                     
                id := azureGetBlockID(partID, subPartNumber, etag)                                      
                err = a.client.PutBlockWithLength(bucket, object, id, uint64(subPartSize), teeReader, n\
il)                                                                                                     
                if err != nil {                                                                         
                        return info, azureToObjectError(traceError(err), bucket, object)                
                }                                                                                       
                if remaining == 0 {                                                                     
                        break                                                                           
                }                                                                                       
                subPartNumber++                                                                         
        }
```

File: cmd/gateway-azure.go [hunk 2]
```diff
@@ -639,14 +656,47 @@ func (a *azureObjects) CompleteMultipartUpload(bucket, object, uploadID string,
...
+				})
+			}
+		}
+
+		if len(blocks) == 0 {
+			return nil, InvalidPart{}
+		}
+
+		return blocks, nil
+	}
```
Comment (krishnasrinivas) [inline cmd/gateway-azure.go]: introducing azureEncodeBlockID and azureDecodeBlockID will make the above code more readable:
```
func azureEncodeBlockID(partID, subPartNumber int, md5Hex string) string {                              
        return base64.StdEncoding.EncodeToString([]byte(fmt.Sprintf("%05d.%02d.%s", partID, subPartNumb\
er, md5Hex)))                                                                                           
}                                                                                                       
                                                                                                        
func azureDecodeBlockID(blockID string) (partID, subPartNumber int, md5Hex string, err error) {         
        b, err := base64.StdEncoding.DecodeString(blockID)                                              
        if err != nil {                                                                                 
                return                                                                                  
        }                                                                                               
        fmt.Sscanf(string(b), "%05d.%02d.%s", &partID, &subPartNumber, &md5Hex)                         
        return                                                                                          
}                                                                                                       

....
...

        getBlocks := func(partNumber int, etag string) (blocks []storage.Block, err error) {            
                var idBytes []byte                                                                      
                for _, part := range resp.UncommittedBlocks {                                           
                        respPartNumber, _, respEtag, err := azureDecodeBlockID(part.Name)               
                        if err != nil {                                                                 
                                return nil, InvalidPart{}                                               
                        }                                                                               
                        if partNumber == respPartNumber && etag == respEtag {                           
                                blocks = append(blocks, storage.Block{                                  
                                        ID:     part.Name,                                              
                                        Status: storage.BlockStatusUncommitted,                         
                                })                                                                      
                        }                                                                               
                }                                                                                       
                                                                                                        
                if len(blocks) == 0 {                                                                   
                        return nil, InvalidPart{}                                                       
                }                                                                                       
                                                                                                        
                return blocks, nil                                                                      
        }                                                                                               


```

File: cmd/gateway-azure.go [hunk 3]
```diff
@@ -639,14 +656,47 @@ func (a *azureObjects) CompleteMultipartUpload(bucket, object, uploadID string,
...
+
+	var allBlocks []storage.Block
 	var blocks []storage.Block
```
Comment (krishnasrinivas) [inline cmd/gateway-azure.go]: blocks can be inside the scope of the `for loop` below

Comment (balamurugana) [reply cmd/gateway-azure.go]: Done

File: cmd/gateway-azure.go (hunk 2 above)
Comment (balamurugana) [reply cmd/gateway-azure.go]: Done

File: cmd/gateway-azure.go (hunk 1 above)
Comment (balamurugana) [reply cmd/gateway-azure.go]: Done

**Comment by balamurugana** [comment]
@krishnasrinivas addressed all the comments.

File: cmd/gateway-azure.go [hunk 4]
```diff
@@ -550,10 +547,20 @@ func (a *azureObjects) PutObjectPart(bucket, object, uploadID string, partID int
 		teeReader = io.TeeReader(data, io.MultiWriter(writers...))
 	}
 
-	id := azureGetBlockID(partID, etag)
-	err = a.client.PutBlockWithLength(bucket, object, id, uint64(size), teeReader, nil)
-	if err != nil {
-		return info, azureToObjectError(traceError(err), bucket, object)
+	subPartSize := int64(azureBlockSize)
+	subPartNumber := 1
+	for remainingSize := size; remainingSize > 0; remainingSize -= subPartSize {
```
Comment (krishnasrinivas) [inline cmd/gateway-azure.go]: this does not work for the case where we upload just one part with 0 size and do completemultipart of that 0 sized part

Comment (balamurugana) [reply cmd/gateway-azure.go]: Is zero sized part allowed in s3?

Comment (krishnasrinivas) [reply cmd/gateway-azure.go]: yes

Comment (balamurugana) [reply cmd/gateway-azure.go]: This means gateway supposes to fail  for parts other than last part sizing < 5MB?

Comment (balamurugana) [reply cmd/gateway-azure.go]: Fixed now

**Comment by krishnasrinivas** [comment]
@balamurugana can you update the PR once it is tested?

**Comment by balamurugana** [comment]
@krishnasrinivas I tested this PR by running minio-java which does 525MiB as part size which succeeded.

**Review by krishnasrinivas — APPROVED** [review]

**Review by harshavardhana — APPROVED** [review]
