### PR TITLE
fix: Don't allow to set unconfigured notification ARNs

### LINKED ISSUE #8642: notifications: Server allows for setting unconfigured ARNs
Actually, there is a bug in server in-fact 

```
mc event add play/testbucket arn:minio:sqs::us-west-2:1
Successfully added arn:minio:sqs::us-west-2:1

mc event add play/testbucket arn:minio:sqs::us-west-2:2
Successfully added arn:minio:sqs::us-west-2:2

mc event add play/testbucket arn:minio:sqs::us-west-2:3
Successfully added arn:minio:sqs::us-west-2:3
```

```
mc event list play/testbucket/
arn:minio:sqs:us-east-1:us-west-2:1   s3:ObjectCreated:*,s3:ObjectRemoved:*,s3:ObjectAccessed:*   Filter: 
arn:minio:sqs:us-east-1:us-west-2:2   s3:ObjectCreated:*,s3:ObjectRemoved:*,s3:ObjectAccessed:*   Filter: 
arn:minio:sqs:us-east-1:us-west-2:3   s3:ObjectCreated:*,s3:ObjectRemoved:*,s3:ObjectAccessed:*   Filter: 
```

_Originally posted by @harshavardhana in https://github.com/minio/mc/issues/3006#issuecomment-565149148_

### PR DESCRIPTION
**Pull request by harshavardhana**
## Description
fix: Don't allow to set unconfigured notification ARNs

## Motivation and Context
Fixes #8642

## How to test this PR?
As mentioned in the issue #8642

## Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [x] Fixes a regression introduced in 63e0a81760fbd3763e36049cd820cd26b7945790
- [ ] Documentation needed
- [ ] Unit tests needed
- [ ] Functional tests needed (If yes, add [mint](https://github.com/minio/mint) PR # here: )

### CODE REVIEW

**Review by kannappanr — APPROVED** [review]
LGTM

**Review by poornas — APPROVED** [review]

**Comment by harshavardhana** [comment]
This breaks away from a fix which was done some time ago #7673

**Comment by harshavardhana** [comment]
Let me fix this properly to ensure that we don't allow setting new configs which have non-existent while allowing existing ones to continue @kannappanr

**Comment by minio-ops** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-compression-xl.sh | :heavy_check_mark: |
| mint-compression-fs.sh | :heavy_check_mark: |
| mint-worm.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-xl.sh | :x: [more...](#ae160b70-0280-421a-890b-21890251e186) |
| mint-large-bucket.sh | :x: [more...](#d1e86ec6-d113-45aa-88be-ee72bc6f935b) |
| mint-compression-dist-xl.sh | :x: [more...](#80ba7d29-a177-4210-91c3-66e63d960951) |
| mint-dist-xl.sh | :x: [more...](#f1f1e2e5-8aef-4ea9-b8ca-2a7db9122e72) |
<a name="d1e86ec6-d113-45aa-88be-ee72bc6f935b"></a>
### 8643-fde0397/mint-large-bucket.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.58:31311
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp bccc943464de:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 1 seconds
(2/14) Running aws-sdk-java tests ... done in 1 seconds
(3/14) Running aws-sdk-php tests ... done in 48 seconds
(4/14) Running aws-sdk-ruby tests ... done in 5 seconds
(5/14) Running awscli tests ... done in 2 minutes and 32 seconds
(6/14) Running healthcheck tests ... done in 0 seconds
(7/14) Running mc tests ... done in 1 minutes and 30 seconds
(8/14) Running minio-dotnet tests ... done in 1 minutes and 1 seconds
(9/14) Running minio-go tests ... FAILED in 3 minutes and 37 seconds
{
  "args": {},
  "duration": 102421,
  "error": "Please reduce your request",
  "function": "testStorageClassMetadataCopyObject()",
  "message": "CopyObject failed on RRS",
  "name": "minio-go: testStorageClassMetadataCopyObject",
  "status": "FAIL"
}

Executed 8 out of 14 tests successfully.
```
<a name="f1f1e2e5-8aef-4ea9-b8ca-2a7db9122e72"></a>
### 8643-fde0397/mint-dist-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.58:30102
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 543097e08d32:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 0 seconds
(2/14) Running aws-sdk-java tests ... done in 1 seconds
(3/14) Running aws-sdk-php tests ... done in 46 seconds
(4/14) Running aws-sdk-ruby tests ... done in 3 seconds
(5/14) Running awscli tests ... done in 2 minutes and 12 seconds
(6/14) Running healthcheck tests ... done in 0 seconds
(7/14) Running mc tests ... done in 55 seconds
(8/14) Running minio-dotnet tests ... done in 51 seconds
(9/14) Running minio-go tests ... FAILED in 1 minutes and 1 seconds
{
  "args": {
    "bucketName": "minio-go-test-4o5nfzpjb1k933nl"
  },
  "duration": 22655,
  "error": "Please reduce your request",
  "function": "RemoveObjects(bucketName, objectsCh)",
  "message": "Unexpected error",
  "name": "minio-go: testRemoveMultipleObjects",
  "status": "FAIL"
}

Executed 8 out of 14 tests successfully.
```
<a name="80ba7d29-a177-4210-91c3-66e63d960951"></a>
### 8643-fde0397/mint-compression-dist-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.54:31979
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp f5a990d068b7:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 0 seconds
(2/14) Running aws-sdk-java tests ... done in 1 seconds
(3/14) Running aws-sdk-php tests ... done in 45 seconds
(4/14) Running aws-sdk-ruby tests ... done in 4 seconds
(5/14) Running awscli tests ... done in 1 minutes and 17 seconds
(6/14) Running healthcheck tests ... done in 1 seconds
(7/14) Running mc tests ... done in 26 seconds
(8/14) Running minio-dotnet tests ... done in 33 seconds
(9/14) Running minio-go tests ... done in 1 minutes and 34 seconds
(10/14) Running minio-java tests ... FAILED in 56 seconds
{
  "name": "minio-java",
  "function": "listObjects(final String bucketName, final String prefix, final boolean recursive)",
  "args": "prefix :minio, recursive: true",
  "duration": 50542,
  "status": "FAIL",
  "error": "error occurred\nErrorResponse(code=SlowDown, message=Please reduce your request, bucketName=minio-java-test-10g7kj3, objectName=minio-java-test-1a4cgfv, resource=/minio-java-test-10g7kj3/minio-java-test-1a4cgfv, requestId=15DFB92C20A2CD2B, hostId=3f261c51-7040-4c0d-b248-f03ca9917e36)\nrequest={method=PUT, url=http://72.28.97.54:31979/minio-java-test-10g7kj3/minio-java-test-1a4cgfv, headers=Content-Type: application/octet-stream\nContent-Encoding: aws-chunked\nx-amz-decoded-content-length: 1\nHost: 72.28.97.54:31979\nUser-Agent: MinIO (amd64; amd64) minio-java/dev\nx-amz-content-sha256: STREAMING-AWS4-HMAC-SHA256-PAYLOAD\nx-amz-date: 20191212T201953Z\nAuthorization: AWS4-HMAC-SHA256 Credential=*REDACTED*/20191212/us-east-1/s3/aws4_request, SignedHeaders=content-encoding;host;x-amz-content-sha256;x-amz-date;x-amz-decoded-content-length, Signature=*REDACTED*\n}\nresponse={code=503, headers=Accept-Ranges: bytes\nContent-Length: 363\nContent-Security-Policy: block-all-mixed-content\nContent-Type: application/xml\nRetry-After: 120\nServer: MinIO/DEVELOPMENT.2019-12-12T19-54-37Z\nVary: Origin\nX-Amz-Request-Id: 15DFB92C20A2CD2B\nX-Xss-Protection: 1; mode=block\nDate: Thu, 12 Dec 2019 20:19:53 GMT\n}\n >>> [io.minio.MinioClient.executeReq(MinioClient.java:1204), io.minio.MinioClient.execute(MinioClient.java:1066), io.minio.MinioClient.executePut(MinioClient.java:1430), io.minio.MinioClient.executePut(MinioClient.java:1452), io.minio.MinioClient.putObject(MinioClient.java:4511), io.minio.MinioClient.putObject(MinioClient.java:4564), io.minio.MinioClient.putObject(MinioClient.java:4478), FunctionalTest.listObject_test5(FunctionalTest.java:1485), FunctionalTest.runTests(FunctionalTest.java:3010), FunctionalTest.main(FunctionalTest.java:3148)]"
}

Executed 9 out of 14 tests successfully.
```
<a name="ae160b70-0280-421a-890b-21890251e186"></a>
### 8643-fde0397/mint-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.52:30753
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 9282b2c643a3:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 0 seconds
(2/14) Running aws-sdk-java tests ... done in 1 seconds
(3/14) Running aws-sdk-php tests ... done in 42 seconds
(4/14) Running aws-sdk-ruby tests ... done in 2 seconds
(5/14) Running awscli tests ... done in 1 minutes and 53 seconds
(6/14) Running healthcheck tests ... done in 0 seconds
(7/14) Running mc tests ... done in 56 seconds
(8/14) Running minio-dotnet tests ... done in 25 seconds
(9/14) Running minio-go tests ... done in 56 seconds
(10/14) Running minio-java tests ... done in 24 seconds
(11/14) Running minio-js tests ... FAILED in 4 seconds
{
  "name": "minio-js",
  "function": "\"after all\" hook in \"functional tests\"",
  "duration": 8,
  "status": "FAIL",
  "error": "S3Error: The bucket you tried to delete is not empty at Object.parseError (node_modules/minio/dist/main/xml-parsers.js:83:11) at /mint/run/core/minio-js/node_modules/minio/dist/main/transformers.js:153:22 at DestroyableTransform._flush (node_modules/minio/dist/main/transformers.js:77:10) at DestroyableTransform.prefinish (node_modules/readable-stream/lib/_stream_transform.js:129:10) at prefinish (node_modules/readable-stream/lib/_stream_writable.js:607:14) at finishMaybe (node_modules/readable-stream/lib/_stream_writable.js:616:5) at endWritable (node_modules/readable-stream/lib/_stream_writable.js:629:3) at DestroyableTransform.Writable.end (node_modules/readable-stream/lib/_stream_writable.js:567:22) at IncomingMessage.onend (_stream_readable.js:514:10) at endReadableNT (_stream_readable.js:978:12) at _combinedTickCallback (internal/process/next_tick.js:80:11) at process._tickCallback (internal/process/next_tick.js:104:9)"
}

Executed 10 out of 14 tests successfully.
```
Deleting image on docker hub
Deleting image locally

**Comment by minio-ops** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-xl.sh | :heavy_check_mark: |
| mint-compression-fs.sh | :heavy_check_mark: |
| mint-worm.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-compression-xl.sh | :x: [more...](#7efd05a6-6d17-46d6-80ca-9ddd9cf0109b) |
| mint-large-bucket.sh | :x: [more...](#6bf7a2ee-d233-4927-a40d-cfff12ce3320) |
| mint-compression-dist-xl.sh | :x: [more...](#c3f7596e-ca83-4268-9e91-d8daf6c2f2cd) |
| mint-dist-xl.sh | :x: [more...](#6a76029c-a630-45e2-9be1-726376cc94c9) |
<a name="6bf7a2ee-d233-4927-a40d-cfff12ce3320"></a>
### 8643-3b04359/mint-large-bucket.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.51:30135
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 51e0db91b823:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 6 seconds
(2/14) Running aws-sdk-java tests ... done in 1 seconds
(3/14) Running aws-sdk-php tests ... done in 50 seconds
(4/14) Running aws-sdk-ruby tests ... done in 5 seconds
(5/14) Running awscli tests ... done in 2 minutes and 11 seconds
(6/14) Running healthcheck tests ... done in 0 seconds
(7/14) Running mc tests ... done in 1 minutes and 13 seconds
(8/14) Running minio-dotnet tests ... done in 1 minutes and 24 seconds
(9/14) Running minio-go tests ... FAILED in 4 minutes and 3 seconds
{
  "args": {},
  "duration": 100565,
  "error": "Please reduce your request",
  "function": "testStorageClassMetadataCopyObject()",
  "message": "CopyObject failed on RRS",
  "name": "minio-go: testStorageClassMetadataCopyObject",
  "status": "FAIL"
}

Executed 8 out of 14 tests successfully.
```
<a name="7efd05a6-6d17-46d6-80ca-9ddd9cf0109b"></a>
### 8643-3b04359/mint-compression-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.56:32636
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp cf04c1b6741e:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... FAILED in 6 minutes and 4 seconds
{
  "alert": "",
  "args": {
    "bucketName": "aws-sdk-go-test-2jduixl26m4zqk",
    "expiry": 60000000000,
    "objectName": "presignedTest"
  },
  "duration": 364018,
  "error": "XMinioServerNotInitialized: Server not initialized, please try again.\n\tstatus code: 503, request id: 15DFBEDE9777AD10, host id: ",
  "function": "PresignedPut",
  "message": "AWS SDK Go CreateBucket Failed",
  "name": "aws-sdk-go",
  "status": "FAIL"
}

Executed 0 out of 14 tests successfully.
```
<a name="c3f7596e-ca83-4268-9e91-d8daf6c2f2cd"></a>
### 8643-3b04359/mint-compression-dist-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.58:32073
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 52d17b745d64:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 0 seconds
(2/14) Running aws-sdk-java tests ... done in 1 seconds
(3/14) Running aws-sdk-php tests ... done in 44 seconds
(4/14) Running aws-sdk-ruby tests ... done in 6 seconds
(5/14) Running awscli tests ... done in 1 minutes and 57 seconds
(6/14) Running healthcheck tests ... done in 0 seconds
(7/14) Running mc tests ... done in 49 seconds
(8/14) Running minio-dotnet tests ... done in 40 seconds
(9/14) Running minio-go tests ... done in 1 minutes and 8 seconds
(10/14) Running minio-java tests ... FAILED in 9 seconds
{
  "name": "minio-java",
  "function": "putObject(String bucketName, String objectName, InputStream body, long size, String contentType)",
  "args": "size: 1 KB, contentType: application/javascript",
  "duration": 20,
  "status": "FAIL",
  "error": "error occurred\nErrorResponse(code=SlowDown, message=Please reduce your request, bucketName=minio-java-test-2gckgu1, objectName=path/to/minio-java-test-jb3ne0, resource=/minio-java-test-2gckgu1/path/to/minio-java-test-jb3ne0, requestId=15DFBED770428DCE, hostId=f22eeb15-1c11-4fc1-8ad0-4a502b728d4d)\nrequest={method=PUT, url=http://72.28.97.58:32073/minio-java-test-2gckgu1/path/to/minio-java-test-jb3ne0, headers=Content-Type: application/javascript\nContent-Encoding: aws-chunked\nx-amz-decoded-content-length: 1024\nHost: 72.28.97.58:32073\nUser-Agent: MinIO (amd64; amd64) minio-java/dev\nx-amz-content-sha256: STREAMING-AWS4-HMAC-SHA256-PAYLOAD\nx-amz-date: 20191212T220347Z\nAuthorization: AWS4-HMAC-SHA256 Credential=*REDACTED*/20191212/us-east-1/s3/aws4_request, SignedHeaders=content-encoding;host;x-amz-content-sha256;x-amz-date;x-amz-decoded-content-length, Signature=*REDACTED*\n}\nresponse={code=503, headers=Accept-Ranges: bytes\nContent-Length: 377\nContent-Security-Policy: block-all-mixed-content\nContent-Type: application/xml\nRetry-After: 120\nServer: MinIO/DEVELOPMENT.2019-12-12T21-39-14Z\nVary: Origin\nX-Amz-Request-Id: 15DFBED770428DCE\nX-Xss-Protection: 1; mode=block\nDate: Thu, 12 Dec 2019 22:03:47 GMT\n}\n >>> [io.minio.MinioClient.executeReq(MinioClient.java:1204), io.minio.MinioClient.execute(MinioClient.java:1066), io.minio.MinioClient.executePut(MinioClient.java:1430), io.minio.MinioClient.executePut(MinioClient.java:1452), io.minio.MinioClient.putObject(MinioClient.java:4511), io.minio.MinioClient.putObject(MinioClient.java:4564), io.minio.MinioClient.putObject(MinioClient.java:4478), FunctionalTest.putObject_test6(FunctionalTest.java:520), FunctionalTest.runTests(FunctionalTest.java:2988), FunctionalTest.main(FunctionalTest.java:3148)]"
}

Executed 9 out of 14 tests successfully.
```
<a name="6a76029c-a630-45e2-9be1-726376cc94c9"></a>
### 8643-3b04359/mint-dist-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.56:31774
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp afccdb0c707a:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 1 seconds
(2/14) Running aws-sdk-java tests ... done in 1 seconds
(3/14) Running aws-sdk-php tests ... done in 49 seconds
(4/14) Running aws-sdk-ruby tests ... done in 2 seconds
(5/14) Running awscli tests ... done in 2 minutes and 0 seconds
(6/14) Running healthcheck tests ... done in 0 seconds
(7/14) Running mc tests ... done in 52 seconds
(8/14) Running minio-dotnet tests ... done in 44 seconds
(9/14) Running minio-go tests ... done in 1 minutes and 17 seconds
(10/14) Running minio-java tests ... FAILED in 6 seconds
{
  "name": "minio-java",
  "function": "getObject(String bucketName, String objectName)",
  "duration": 211,
  "status": "FAIL",
  "error": "error occurred\nErrorResponse(code=SlowDown, message=Please reduce your request, bucketName=minio-java-test-200pv7b, objectName=minio-java-test-13ieu04, resource=/minio-java-test-200pv7b/minio-java-test-13ieu04, requestId=15DFBEDBC45536D3, hostId=14ecd0e4-940b-46e4-b7d4-e3b466c1ba9d)\nrequest={method=PUT, url=http://72.28.97.56:31774/minio-java-test-200pv7b/minio-java-test-13ieu04, headers=Content-Type: application/octet-stream\nHost: 72.28.97.56:31774\nUser-Agent: MinIO (amd64; amd64) minio-java/dev\nx-amz-content-sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855\nx-amz-date: 20191212T220405Z\nAuthorization: AWS4-HMAC-SHA256 Credential=*REDACTED*/20191212/us-east-1/s3/aws4_request, SignedHeaders=host;x-amz-content-sha256;x-amz-date, Signature=*REDACTED*\n}\nresponse={code=503, headers=Accept-Ranges: bytes\nContent-Length: 363\nContent-Security-Policy: block-all-mixed-content\nContent-Type: application/xml\nRetry-After: 120\nServer: MinIO/DEVELOPMENT.2019-12-12T21-39-14Z\nVary: Origin\nX-Amz-Request-Id: 15DFBEDBC45536D3\nX-Xss-Protection: 1; mode=block\nDate: Thu, 12 Dec 2019 22:04:05 GMT\n}\n >>> [io.minio.MinioClient.executeReq(MinioClient.java:1204), io.minio.MinioClient.execute(MinioClient.java:1066), io.minio.MinioClient.executePut(MinioClient.java:1430), io.minio.MinioClient.executePut(MinioClient.java:1452), io.minio.MinioClient.putObject(MinioClient.java:4511), io.minio.MinioClient.putObject(MinioClient.java:4564), io.minio.MinioClient.putObject(MinioClient.java:4478), FunctionalTest.getObject_test6(FunctionalTest.java:1184), FunctionalTest.runTests(FunctionalTest.java:3003), FunctionalTest.main(FunctionalTest.java:3148)]"
}

Executed 9 out of 14 tests successfully.
```
Deleting image on docker hub
Deleting image locally

**Comment by harshavardhana** [comment]
I made some more changes in GetBucketNotificarion to preserve the #7673 behavior

PTAL @poornas @kannappanr

**Comment by minio-ops** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-compression-xl.sh | :heavy_check_mark: |
| mint-compression-fs.sh | :heavy_check_mark: |
| mint-worm.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-xl.sh | :x: [more...](#ff328da0-d339-4267-93a2-04456e75f9e4) |
| mint-large-bucket.sh | :x: [more...](#b8b29d82-ab6a-4545-9e76-844e5b7c8ec3) |
| mint-compression-dist-xl.sh | :x: [more...](#c2d2483f-b350-4e80-b318-aeef021ef80d) |
| mint-dist-xl.sh | :x: [more...](#c8927115-3b20-4608-be08-64141b3cb446) |
<a name="c8927115-3b20-4608-be08-64141b3cb446"></a>
### 8643-4b4cffb/mint-dist-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.55:31342
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 394561792c5e:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 1 seconds
(2/14) Running aws-sdk-java tests ... done in 1 seconds
(3/14) Running aws-sdk-php tests ... done in 43 seconds
(4/14) Running aws-sdk-ruby tests ... done in 3 seconds
(5/14) Running awscli tests ... done in 1 minutes and 15 seconds
(6/14) Running healthcheck tests ... done in 0 seconds
(7/14) Running mc tests ... done in 43 seconds
(8/14) Running minio-dotnet tests ... done in 36 seconds
(9/14) Running minio-go tests ... done in 1 minutes and 34 seconds
(10/14) Running minio-java tests ... FAILED in 47 seconds
{
  "name": "minio-java",
  "function": "listObjects(final String bucketName, final String prefix, final boolean recursive)",
  "args": "prefix :minio, recursive: true",
  "duration": 40714,
  "status": "FAIL",
  "error": "error occurred\nErrorResponse(code=SlowDown, message=Please reduce your request, bucketName=minio-java-test-v9i7j4, objectName=minio-java-test-2rq9pq5, resource=/minio-java-test-v9i7j4/minio-java-test-2rq9pq5, requestId=15DFC3CEC6BC9846, hostId=9ba79edb-0f26-49fe-9502-c80e84759a25)\nrequest={method=PUT, url=http://72.28.97.55:31342/minio-java-test-v9i7j4/minio-java-test-2rq9pq5, headers=Content-Type: application/octet-stream\nContent-Encoding: aws-chunked\nx-amz-decoded-content-length: 1\nHost: 72.28.97.55:31342\nUser-Agent: MinIO (amd64; amd64) minio-java/dev\nx-amz-content-sha256: STREAMING-AWS4-HMAC-SHA256-PAYLOAD\nx-amz-date: 20191212T233447Z\nAuthorization: AWS4-HMAC-SHA256 Credential=*REDACTED*/20191212/us-east-1/s3/aws4_request, SignedHeaders=content-encoding;host;x-amz-content-sha256;x-amz-date;x-amz-decoded-content-length, Signature=*REDACTED*\n}\nresponse={code=503, headers=Accept-Ranges: bytes\nContent-Length: 361\nContent-Security-Policy: block-all-mixed-content\nContent-Type: application/xml\nRetry-After: 120\nServer: MinIO/DEVELOPMENT.2019-12-12T23-09-53Z\nVary: Origin\nX-Amz-Request-Id: 15DFC3CEC6BC9846\nX-Xss-Protection: 1; mode=block\nDate: Thu, 12 Dec 2019 23:34:47 GMT\n}\n >>> [io.minio.MinioClient.executeReq(MinioClient.java:1204), io.minio.MinioClient.execute(MinioClient.java:1066), io.minio.MinioClient.executePut(MinioClient.java:1430), io.minio.MinioClient.executePut(MinioClient.java:1452), io.minio.MinioClient.putObject(MinioClient.java:4511), io.minio.MinioClient.putObject(MinioClient.java:4564), io.minio.MinioClient.putObject(MinioClient.java:4478), FunctionalTest.listObject_test5(FunctionalTest.java:1485), FunctionalTest.runTests(FunctionalTest.java:3010), FunctionalTest.main(FunctionalTest.java:3148)]"
}

Executed 9 out of 14 tests successfully.
```
<a name="ff328da0-d339-4267-93a2-04456e75f9e4"></a>
### 8643-4b4cffb/mint-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.52:32512
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 4d3e5ceba0f7:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 0 seconds
(2/14) Running aws-sdk-java tests ... done in 1 seconds
(3/14) Running aws-sdk-php tests ... done in 42 seconds
(4/14) Running aws-sdk-ruby tests ... done in 1 seconds
(5/14) Running awscli tests ... done in 1 minutes and 54 seconds
(6/14) Running healthcheck tests ... done in 0 seconds
(7/14) Running mc tests ... FAILED in 13 seconds
{
  "name": "mc",
  "duration": "7602",
  "function": "test_get_object_multipart",
  "status": "FAIL",
  "error": "/mint/run/core/mc/mc --config-dir /tmp/.mc-15611 --quiet --no-color cp myminio/mc-test-bucket-1754/mc-test-object-16200 mc-test-object-16200.downloaded  >>> \n`myminio/mc-test-bucket-1754/mc-test-object-16200` -> `mc-test-object-16200.downloaded`\nmc: <ERROR> Failed to copy `http://72.28.97.52:32512/mc-test-bucket-1754/mc-test-object-16200`. read tcp 172.17.0.11:57336->72.28.97.52:32512: read: connection reset by peer\nmc: <ERROR> Session safely terminated. To resume session `mc session resume nuWkACKt`"
}

Executed 6 out of 14 tests successfully.
```
<a name="c2d2483f-b350-4e80-b318-aeef021ef80d"></a>
### 8643-4b4cffb/mint-compression-dist-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.55:30903
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 193849f90b5d:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 0 seconds
(2/14) Running aws-sdk-java tests ... done in 1 seconds
(3/14) Running aws-sdk-php tests ... done in 44 seconds
(4/14) Running aws-sdk-ruby tests ... done in 3 seconds
(5/14) Running awscli tests ... done in 1 minutes and 9 seconds
(6/14) Running healthcheck tests ... done in 0 seconds
(7/14) Running mc tests ... done in 31 seconds
(8/14) Running minio-dotnet tests ... done in 35 seconds
(9/14) Running minio-go tests ... done in 1 minutes and 30 seconds
(10/14) Running minio-java tests ... FAILED in 1 minutes and 6 seconds
{
  "name": "minio-java",
  "function": "listObjects(final String bucketName, final String prefix, final boolean recursive)",
  "args": "prefix :minio, recursive: true",
  "duration": 60602,
  "status": "FAIL",
  "error": "error occurred\nErrorResponse(code=SlowDown, message=Please reduce your request, bucketName=minio-java-test-2brlli6, objectName=minio-java-test-3qfiaf7, resource=/minio-java-test-2brlli6/minio-java-test-3qfiaf7, requestId=15DFC3CDBACDB24D, hostId=df83a9e7-72c1-4d50-85fb-12cf77e2bf90)\nrequest={method=PUT, url=http://72.28.97.55:30903/minio-java-test-2brlli6/minio-java-test-3qfiaf7, headers=Content-Type: application/octet-stream\nContent-Encoding: aws-chunked\nx-amz-decoded-content-length: 1\nHost: 72.28.97.55:30903\nUser-Agent: MinIO (amd64; amd64) minio-java/dev\nx-amz-content-sha256: STREAMING-AWS4-HMAC-SHA256-PAYLOAD\nx-amz-date: 20191212T233442Z\nAuthorization: AWS4-HMAC-SHA256 Credential=*REDACTED*/20191212/us-east-1/s3/aws4_request, SignedHeaders=content-encoding;host;x-amz-content-sha256;x-amz-date;x-amz-decoded-content-length, Signature=*REDACTED*\n}\nresponse={code=503, headers=Accept-Ranges: bytes\nContent-Length: 363\nContent-Security-Policy: block-all-mixed-content\nContent-Type: application/xml\nRetry-After: 120\nServer: MinIO/DEVELOPMENT.2019-12-12T23-09-53Z\nVary: Origin\nX-Amz-Request-Id: 15DFC3CDBACDB24D\nX-Xss-Protection: 1; mode=block\nDate: Thu, 12 Dec 2019 23:34:43 GMT\n}\n >>> [io.minio.MinioClient.executeReq(MinioClient.java:1204), io.minio.MinioClient.execute(MinioClient.java:1066), io.minio.MinioClient.executePut(MinioClient.java:1430), io.minio.MinioClient.executePut(MinioClient.java:1452), io.minio.MinioClient.putObject(MinioClient.java:4511), io.minio.MinioClient.putObject(MinioClient.java:4564), io.minio.MinioClient.putObject(MinioClient.java:4478), FunctionalTest.listObject_test5(FunctionalTest.java:1485), FunctionalTest.runTests(FunctionalTest.java:3010), FunctionalTest.main(FunctionalTest.java:3148)]"
}

Executed 9 out of 14 tests successfully.
```
<a name="b8b29d82-ab6a-4545-9e76-844e5b7c8ec3"></a>
### 8643-4b4cffb/mint-large-bucket.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.58:32276
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 9f0fa0f11d66:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 1 seconds
(2/14) Running aws-sdk-java tests ... done in 1 seconds
(3/14) Running aws-sdk-php tests ... done in 46 seconds
(4/14) Running aws-sdk-ruby tests ... done in 6 seconds
(5/14) Running awscli tests ... done in 2 minutes and 13 seconds
(6/14) Running healthcheck tests ... done in 0 seconds
(7/14) Running mc tests ... done in 1 minutes and 16 seconds
(8/14) Running minio-dotnet tests ... done in 1 minutes and 4 seconds
(9/14) Running minio-go tests ... FAILED in 3 minutes and 55 seconds
{
  "args": {},
  "duration": 114804,
  "error": "Please reduce your request",
  "function": "testStorageClassMetadataCopyObject()",
  "message": "CopyObject failed on RRS",
  "name": "minio-go: testStorageClassMetadataCopyObject",
  "status": "FAIL"
}

Executed 8 out of 14 tests successfully.
```
Deleting image on docker hub
Deleting image locally

**Comment by harshavardhana** [comment]
@Praveenrajmani PTAL if this fix makes sense to you.

**Comment by harshavardhana** [comment]
What we are essentially doing is filtering out the unconfigured pre-existing Arn's in Get, but never allow Put with unconfigured to succeed. Which is the correct fix for #7673

File: cmd/bucket-notification-handlers.go [hunk 1]
```diff
@@ -87,15 +86,38 @@ func (api objectAPIHandlers) GetBucketNotificationHandler(w http.ResponseWriter,
 			writeErrorResponse(ctx, w, toAPIError(ctx, err), r.URL, guessIsBrowserReq(r))
 			return
 		}
-		config = &event.Config{}
-	} else {
-		if err = xml.NewDecoder(bytes.NewReader(configData)).Decode(&config); err != nil {
+		notificationBytes, err := xml.Marshal(&event.Config{
+			XMLNS: "http://s3.amazonaws.com/doc/2006-03-01/",
```
Comment (Praveenrajmani) [inline cmd/bucket-notification-handlers.go]: Shouldn't we set the region also @harshavardhana

File: cmd/bucket-notification-handlers.go [hunk 2]
```diff
@@ -87,15 +86,38 @@ func (api objectAPIHandlers) GetBucketNotificationHandler(w http.ResponseWriter,
...
+
+	if err = config.Validate(globalServerRegion, globalNotificationSys.targetList); err != nil {
+		arnErr, ok := err.(*event.ErrARNNotFound)
+		if !ok {
+			writeErrorResponse(ctx, w, toAPIError(ctx, err), r.URL, guessIsBrowserReq(r))
+			return
+		}
+		for i, queue := range config.QueueList {
+			// Remove ARN not found queues
+			if reflect.DeepEqual(queue.ARN, arnErr.ARN) {
```
Comment (Praveenrajmani) [inline cmd/bucket-notification-handlers.go:122]: This will remove the ARN from the config if it is not present in the globalNotificationSys.targetList? Is it ok if we remove?

Comment (Praveenrajmani) [reply cmd/bucket-notification-handlers.go:122]: Attaching a comment regarding this conversation - https://github.com/minio/minio/pull/7673#issuecomment-494275324 Does this make sense?

File: cmd/bucket-notification-handlers.go [hunk 3]
```diff
@@ -87,15 +86,38 @@ func (api objectAPIHandlers) GetBucketNotificationHandler(w http.ResponseWriter,
...
+				config.QueueList = append(config.QueueList[:i],
+					config.QueueList[i+1:]...)
+			}
+		}
+	}
 
 	// If xml namespace is empty, set a default value before returning.
 	if config.XMLNS == "" {
```
Comment (Praveenrajmani) [inline cmd/bucket-notification-handlers.go:134]: We are missing `config.SetRegion(globalServerRegion)` here as well

File: cmd/bucket-notification-handlers.go [hunk 4]
```diff
@@ -149,17 +171,15 @@ func (api objectAPIHandlers) PutBucketNotificationHandler(w http.ResponseWriter,
...
 	if err != nil {
 		apiErr := errorCodes.ToAPIErr(ErrMalformedXML)
 		if event.IsEventError(err) {
 			apiErr = toAPIError(ctx, err)
 		}
-		if _, ok := err.(*event.ErrARNNotFound); !ok {
-			writeErrorResponse(ctx, w, apiErr, r.URL, guessIsBrowserReq(r))
-			return
-		}
+		writeErrorResponse(ctx, w, apiErr, r.URL, guessIsBrowserReq(r))
```
Comment (Praveenrajmani) [inline cmd/bucket-notification-handlers.go:192]: Previously we skipped the ARN Not Found error because `event.ParseConfig` would throw `ARN Not Found` even if one of the ARN is removed in the config.

Comment (Praveenrajmani) [reply cmd/bucket-notification-handlers.go:192]: This is reverting the fix for https://github.com/minio/minio/issues/7650

File: cmd/bucket-notification-handlers.go (hunk 2 above)
Comment (harshavardhana) [reply cmd/bucket-notification-handlers.go:122]: Yes the intention is to allow existing ones to be not sent to client which are stale. Since they are not useful to client.

File: cmd/bucket-notification-handlers.go (hunk 3 above)
Comment (harshavardhana) [reply cmd/bucket-notification-handlers.go:134]: That is not needed here we are not trying to save anything here.

File: cmd/bucket-notification-handlers.go (hunk 4 above)
Comment (harshavardhana) [reply cmd/bucket-notification-handlers.go:192]: It is not reverting the fix instead it is fixing it correctly the current master after the fix silently allows setting unconfigured arns which is a serious bug.

File: cmd/bucket-notification-handlers.go (hunk 1 above)
Comment (harshavardhana) [reply cmd/bucket-notification-handlers.go]: No it is not needed.

**Review by Praveenrajmani — APPROVED** [review]

File: cmd/config-current.go [hunk 5]
```diff
@@ -282,7 +282,8 @@ func validateConfig(s config.Config) error {
 		return err
 	}
 
-	return notify.TestNotificationTargets(s, GlobalServiceDoneCh, NewCustomHTTPTransport())
+	return notify.TestNotificationTargets(s, GlobalServiceDoneCh, NewCustomHTTPTransport(),
+		globalNotificationSys.ConfiguredTargetIDs())
```
Comment (Praveenrajmani) [inline cmd/config-current.go:286]: globalNotificationSys would not have been initialized at this moment

File: cmd/config/notify/parse.go [hunk 6]
```diff
@@ -275,12 +269,24 @@ func RegisterNotificationTargets(cfg config.Config, doneCh <-chan struct{}, tran
...
 			newTarget.Close()
 			continue
 		}
-		if err := targetList.Add(newTarget); err != nil {
-			return nil, err
+	}
+
+	if test {
+		// Verify if user is trying to disable already configured
+		// notification targets, based on their target IDs
```
Comment (Praveenrajmani) [inline cmd/config/notify/parse.go:283]: len of targetIDs will be 0 always, if the globalNotificationSys hasn't initialized yet

Comment (Praveenrajmani) [reply cmd/config/notify/parse.go:283]: verified this with print statements. len(targetIDs) gave me 0 always

File: cmd/config-current.go (hunk 5 above)
Comment (harshavardhana) [reply cmd/config-current.go:286]: Of course it would be, the call is only happening when server is running.

File: cmd/config/notify/parse.go (hunk 6 above)
Comment (harshavardhana) [reply cmd/config/notify/parse.go:283]: If it's not initialized then bad luck we can't do much.

**Comment by Praveenrajmani** [comment]
Tested the latest changes
