### PR TITLE
signature-v2: encode path and query strings when calculating signature

### LINKED ISSUE #3251: Files with spaces fail signature checks
I cannot upload or download files with space(s) in the name. I'm experiencing the issue with both Cyberduck and Node `aws-sdk`.

Log excerpt:
```
time="2016-11-13T21:49:35Z" level=error msg="{\"method\":\"GET\",\"path\":\"/hostr/uploads/f/150/fceddePi_Picture 2.png\",\"query\":\"\",\"header\":{\"Authorization\":[\"AWS M3E9PUR0BTZ7EQPDTCIQ:ddHj0tlm5My8F1GBmY0F0LWcEgA=\"],\"Connection\":[\"close\"],\"Content-Length\":[\"0\"],\"Host\":[\"minio:9000\"],\"User-Agent\":[\"aws-sdk-nodejs/2.7.0 darwin/v7.1.0\"],\"X-Amz-Date\":[\"Sun, 13 Nov 2016 21:49:35 GMT\"]}}" cause="Signature does not match" location="[object-handlers.go:108:objectAPIHandlers.GetObjectHandler()]"
```

Environment
* Docker `1.12.3`
* Minio `minio/minio:edge`
* Nginx `1.11.1-1~jessie`

### PR DESCRIPTION
**Pull request by vadmeste**
## Description
signature-v2 wasn't encoding path and query when calculating signature v2, fixing that..

## Motivation and Context
Fixes #3251 

## How Has This Been Tested?
Manually

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [Not Yet] All new and existing tests passed.

### CODE REVIEW

File: cmd/signature-v2.go [hunk 1]
```diff
@@ -191,14 +192,33 @@ func doesSignV2Match(r *http.Request) APIErrorCode {
...
 	if encodedResource == "" {
 		splits := strings.Split(r.URL.Path, "?")
 		if len(splits) > 0 {
-			encodedResource = splits[0]
+			encodedResource = getURLEncodedName(splits[0])
+		}
+	}
+
+	// Encode query strings
+	encodedQuery := ""
```
Comment (harshavardhana) [inline cmd/signature-v2.go]: why can't we get like `r.URL.Query().Encode()` instead of looping and creating our own encodedQuery?

Comment (vadmeste) [reply cmd/signature-v2.go]: > why can't we get like r.URL.Query().Encode() instead of looping and creating our own encodedQuery?

actually, this does more than encoding like sorting and removing "=" in case of empty values for some parameters.. but also I found this is done in lower layer. so I simplified as you suggested

**Review by fwessels — COMMENTED** [review]
LGTM

**Review by harshavardhana — APPROVED** [review]
