### PR TITLE
go1.8: Changes to support golang 1.8

### LINKED ISSUE #4662: [go1.8] Ensure Minio tests passing in go 1.8
Minio tests do not pass with go 1.8.

As a first step, We should ensure that Minio tests pass, then we'll decide other actions to ensure the quality of Minio server with go 1.8.

### LINKED ISSUE #4663: [go1.8] Manual tests of cases not covered by tests (hard to test automatically)
Like:
* Target notifications (NATs, Redis, ..)
* Minio command line arguments
* Bucket notifications for FS and XL
* Gateways

### LINKED ISSUE #4664: [go1.8] Make sure that distributed Minio work
Manual testing of distributed Minio to avoid any surprises.

Test with docker-compose, Mesos and other orchestration tools

### LINKED ISSUE #4665: [go1.8] Compare performance between go1.7 and go1.8
Try to detect any performance regression, which doesn't necessarily mean that there is a bug in go1.8.

### LINKED ISSUE #4691: [go1.8] Distributed minio shows `Server times are too far apart` error message
## Expected Behavior
Normal cluster behavior 

## Current Behavior

Running four Minio docker instances locally:

```
00:03 $ docker-compose up                                                           
Starting minio_minio4_1 ...                                                             
Starting minio_minio4_1                                                             
Starting minio_minio3_1 ...                                    
Starting minio_minio2_1 ...                                    
Starting minio_minio3_1                                                                
Starting minio_minio1_1 ...                                         
Starting minio_minio2_1                                        
Starting minio_minio1_1 ... done                               
Attaching to minio_minio4_1, minio_minio3_1, minio_minio2_1, minio_minio1_1              
minio4_1  | Waiting for all hosts to resolve.......All hosts are resolving proceeding to initialize Minio.
minio3_1  | Waiting for all hosts to resolve.......All hosts are resolving proceeding to initialize Minio.
minio2_1  | Waiting for all hosts to resolve.......All hosts are resolving proceeding to initialize Minio.
minio1_1  | Waiting for all hosts to resolve.......All hosts are resolving proceeding to initialize Minio.
minio1_1  |                                                                       
minio1_1  | Detected configuration inconsistencies in the cluster. Please fix following servers.
minio1_1  | [02/04] http://minio2:9000/myexport : Server times are too far apart        
minio1_1  | [03/04] http://minio3:9000/myexport : Server times are too far apart    
minio3_1  |                                                                       
minio3_1  | Detected configuration inconsistencies in the cluster. Please fix following servers.
minio3_1  | [01/04] http://minio1:9000/myexport : Server times are too far apart        
minio3_1  | [02/04] http://minio2:9000/myexport : Server times are too far apart    
minio4_1  |                                                 
minio4_1  | Detected configuration inconsistencies in the cluster. Please fix following servers.
minio4_1  | [01/04] http://minio1:9000/myexport : Server times are too far apart         
minio4_1  | [02/04] http://minio2:9000/myexport : Server times are too far apart 
minio4_1  | [03/04] http://minio3:9000/myexport : Server times are too far apart
```

`Server times are too far apart` can also seen when `mc watch` is called.

```
minio3_1  | time="2017-07-18T23:11:03Z" level=error msg="Error sending update bucket listener to minio1:9000 - Server times are too far apart" cause="Server times are too far apart" source="[s3-peer-client.go:166:S3PeersUpdateBucketListener()]"
```

## Possible Solution
There is something weird with go1.8 and RPC, not sure how to fix this yet.

## Steps to Reproduce (for bugs)
1. Download this PR and build the image locally (`docker build . -t minio/minio`)
2. 
```
$ cat > docker-compose.yaml`
version: '2'

# starts 4 docker containers running minio server instances. Each
# minio server's web interface will be accessible on the host at port
# 9001 through 9004.
services:
  minio1:
    image: minio/minio
    ports:
      - "9001:9000"
    environment:
      MINIO_ACCESS_KEY: minio
      MINIO_SECRET_KEY: minio123
    command: server http://minio1/myexport http://minio2/myexport http://minio3/myexport http://minio4/myexport 
  minio2:
    image: minio/minio
    ports:
      - "9002:9000"
    environment:
      MINIO_ACCESS_KEY: minio
      MINIO_SECRET_KEY: minio123
    command: server http://minio1/myexport http://minio2/myexport http://minio3/myexport http://minio4/myexport 
  minio3:
    image: minio/minio
    ports:
      - "9003:9000"
    environment:
      MINIO_ACCESS_KEY: minio
      MINIO_SECRET_KEY: minio123
    command: server http://minio1/myexport http://minio2/myexport http://minio3/myexport http://minio4/myexport 
  minio4:
    image: minio/minio
    ports:
      - "9004:9000"
    environment:
      MINIO_ACCESS_KEY: minio
      MINIO_SECRET_KEY: minio123
    command: server http://minio1/myexport http://minio2/myexport http://minio3/myexport http://minio4/myexport 
```
3. 
```
$ docker-compose up
```

## Context
Testing the migration of Minio to go 1.8

## Your Environment
All

### PR DESCRIPTION
**Pull request by vadmeste**
## Description
QuirkConn is added to replace net.Conn as a workaround to a golang bug:
https://github.com/golang/go/issues/21133

## Motivation and Context
Move to go1.8

Fixes #4662 
Fixes #4664 
Fixes #4665 
Fixes #4691 
Fixes #4663 

## How Has This Been Tested?
Manual + go tests

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by vadmeste** [comment]
This can be reviewed.. 

Basic operations are also tested under Windows.

File: cmd/net_test.go [hunk 1]
```diff
@@ -291,10 +291,9 @@ func TestSameLocalAddrs(t *testing.T) {
 		expectedErr error
 	}{
 		{"", "", false, errors.New("unable to process empty address")},
-		{":9000", ":9000", true, nil},
-		{"localhost:9000", ":9000", true, nil},
-		{"localhost:9000", "http://localhost:9000", true, nil},
-		{"8.8.8.8:9000", "http://localhost:9000", false, nil},
+		{"http://localhost:9000", ":9000", true, nil},
+		{"http://localhost:9000", "http://localhost:9000", true, nil},
+		{"http://8.8.8.8:9000", "http://localhost:9000", false, nil},
```
Comment (balamurugana) [inline cmd/net_test.go]: Why are these cases changed?

File: main_test.go [hunk 2]
```diff
@@ -28,9 +28,9 @@ func TestCheckGoVersion(t *testing.T) {
 		expectedErr error
 	}{
 		{minGoVersion, nil},
-		{minGoVersion + ".10", nil},
-		{"1.6.8", fmt.Errorf("Minio is not compiled by Go >= 1.7.  Please recompile accordingly.")},
-		{"0.1", fmt.Errorf("Minio is not compiled by Go >= 1.7.  Please recompile accordingly.")},
+		{"1.6.8", fmt.Errorf("Minio is not compiled by Go >= 1.8.3.  Please recompile accordingly")},
+		{"1.5", fmt.Errorf("Minio is not compiled by Go >= 1.8.3.  Please recompile accordingly")},
```
Comment (balamurugana) [inline main_test.go:32]: Not sure why above two cases are modified

File: cmd/net_test.go (hunk 1 above)
Comment (vadmeste) [reply cmd/net_test.go]: > Why are these cases changed?

I had to adapt because go 1.8 doesn't consider 8.8.8.8:9000 as a network address anymore.

But still, it doesn't affect us, since

`minio server local_address:9000/export 8.8.8.1:9000/export 8.8.8.2:9000/export 8.8.8.3:9000/export`

is a standalone erasure and not distributed.

File: main_test.go (hunk 2 above)
Comment (vadmeste) [reply main_test.go:32]: > Not sure why above two cases are modified

I had to update the error message since it contains the last supported golang version

**Review by harshavardhana — APPROVED** [review]
LGTM.

**Review by harshavardhana — APPROVED** [review]

File: cmd/net_test.go (hunk 1 above)
Comment (balamurugana) [reply cmd/net_test.go]: As `extractHostPort()` is used in `sameLocalAddrs()` and `extractHostPort()` supports three types ":9000", "localhost:9000", "http://localhost:9000/".

I see `sameLocalAddrs()` is used in gateway-main.go and values from command line arguments are passed.  There is a possibility of three types of value passed to the function.

I think you need to keep previous cases in addition.

File: main_test.go (hunk 2 above)
Comment (balamurugana) [reply main_test.go:32]: I couldn't able to understand why you removed `minGoVersion + ".10"` positive case.

**Review by balamurugana — CHANGES_REQUESTED** [review]

File: main_test.go (hunk 2 above)
Comment (vadmeste) [reply main_test.go:32]: > I couldn't able to understand why you removed minGoVersion + ".10" positive case.

Actually because this was failing, 1.8.3.10 is considered malformed version and we are requiring 1.8.3 as minimal version.

File: cmd/net_test.go (hunk 1 above)
Comment (vadmeste) [reply cmd/net_test.go]: > I think you need to keep previous cases in addition.

Done now.. for that I made some few changes, can you review again? @balamurugana

File: main_test.go (hunk 2 above)
Comment (balamurugana) [reply main_test.go:32]: OK. Got it.

**Review by balamurugana — APPROVED** [review]

File: cmd/net.go [hunk 3]
```diff
@@ -198,13 +198,15 @@ func extractHostPort(hostAddr string) (string, string, error) {
...
+	// Simplify the work of url.Parse() and always send a url with
+	if !strings.HasPrefix(hostAddr, "http://") && !strings.HasPrefix(hostAddr, "https://") {
+		hostAddr = "//" + hostAddr
+	}
+
 	// Parse address to extract host and scheme field
 	u, err := url.Parse(hostAddr)
 	if err != nil {
-		// Ignore scheme not present error
-		if !strings.Contains(err.Error(), "missing protocol scheme") {
```
Comment (balamurugana) [inline cmd/net.go:205]: This error message check is still valid.

**Review by balamurugana — CHANGES_REQUESTED** [review]

File: cmd/net.go (hunk 3 above)
Comment (vadmeste) [reply cmd/net.go:205]: > This error message check is still valid.

Actually, we were *ignoring* `missing protocol scheme` but now we won't ignore it just because it will never happen in practice.

File: cmd/net.go [hunk 4]
```diff
@@ -198,13 +198,15 @@ func extractHostPort(hostAddr string) (string, string, error) {
...
-			return "", "", err
-		}
+		return "", "", err
 	} else {
```
Comment (harshavardhana) [inline cmd/net.go]: Remove this `else {` block..

**Review by harshavardhana — CHANGES_REQUESTED** [review]

**Review by balamurugana — COMMENTED** [review]
LGTM.

lint error needs to be fixed.

**Comment by vadmeste** [comment]
All comments fixed and minikube change reverted.

**Review by harshavardhana — APPROVED** [review]

**Review by balamurugana — APPROVED** [review]

**Review by harshavardhana — COMMENTED** [review]
One missing thing is `checkdeps.sh` should be updated to check for go1.8.3  and merge https://github.com/minio/cookbook/pull/175

**Review by harshavardhana — CHANGES_REQUESTED** [review]
Keeping is :-1: until we fix `checkdeps.sh`

**Comment by vadmeste** [comment]
> Keeping is  until we fix checkdeps.sh

Done

**Review by harshavardhana — APPROVED** [review]
