### PR TITLE
Fix azure gateway handling of ETag for CopyObject

### LINKED ISSUE #9428: Azure-gateway mode: copy with replace metadata changes format of the etag
We have an minio service that is launched in azure gateway mode.
Part of docker-compose file:
```
  minio-azure:
    image: minio/minio
    container_name: minio-azure
    ports:
      - 9001:9000
    environment:
      MINIO_ACCESS_KEY: ${MINIO_AZURE_CLIENT_ID}
      MINIO_SECRET_KEY: ${MINIO_AZURE_CLIENT_SECRET}
    command: gateway azure
```

We have a bunch of tests that run on both normal and asure-gateway minio services.
There is a test that checks format of the etag  and it fail on  minio-azure.

The code (official c# minio client):
```cs
		[Test]
		public async Task UpdateETag_Ok()
		{
			const string data = "Hello, world!";
			var stream = new MemoryStream(Encoding.UTF8.GetBytes(data));
			var bucketName = Guid.NewGuid().ToString("N");
			var blobName = Guid.NewGuid().ToString("N");

			try
			{
				if (!await MinioClient.BucketExistsAsync(bucketName))
					await MinioClient.MakeBucketAsync(bucketName);

				// create
				stream.Position = 0;
				await MinioClient.PutObjectAsync(bucketName, blobName, stream, stream.Length);
				var info1 = await MinioClient.StatObjectAsync(bucketName, blobName);

				// copy
				var copyConditions = new CopyConditions();
				copyConditions.SetReplaceMetadataDirective();
				var metadata = new Dictionary<string, string> { ["content-type"] = "application/text" };
				stream.Position = 0;
				await MinioClient.CopyObjectAsync(
					bucketName, blobName,
					bucketName, blobName,
					copyConditions, metadata);
				var info2 = await MinioClient.StatObjectAsync(bucketName, blobName);

				// clear
				await MinioClient.RemoveObjectAsync(bucketName, blobName);

				// check info
				Console.WriteLine(info1.ETag);
				Console.WriteLine(info2.ETag);
				Assert.AreEqual(info1.ETag.Length, info2.ETag.Length); // (1)
				// ...
			}
			finally
			{
				await MinioClient.RemoveBucketAsync(bucketName);
			}
		}
```

output:
```
6cd3556deb0da54bca060b4c39479839 // before copy
0x8D7E76C4A397E14-1              // after copy
```

## Expected Behavior
I'd expect that etag format will not be changed after the copy operation

## Current Behavior
Etag format changes

## Context
This is minor issue for us as we do not rely on etag format.
However we do store the etag externally and we'd prefer the fix sooner than later as it will reduce amount of our data affected.

## Your Environment
 You are running an older version of MinIO released 3 weeks ago 
 Update: docker pull minio/minio:RELEASE.2020-04-22T00-11-12Z 
Latest minio container; run under  docker-desktop and Azure AKS.

### PR DESCRIPTION
**Pull request by poornas**
Fixes #9428

## Motivation and Context
See above issue

## How to test this PR?
run azure gateway and do a `mc cp` on server side.

## Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [ ] Fixes a regression (If yes, please add `commit-id` or `PR #` here)
- [ ] Documentation needed
- [ ] Unit tests needed
- [ ] Functional tests needed (If yes, add [mint](https://github.com/minio/mint) PR # here: )

### CODE REVIEW

**Review by harshavardhana — APPROVED** [review]
LGTM and test

File: cmd/gateway/azure/gateway-azure.go [hunk 1]
```diff
@@ -885,17 +885,24 @@ func (a *azureObjects) CopyObject(ctx context.Context, srcBucket, srcObject, des
...
+	if err != nil {
+		return objInfo, azureToObjectError(err, srcBucket, srcObject)
+	}
 	destBlob := a.client.NewContainerURL(destBucket).NewBlobURL(destObject)
+
 	azureMeta, props, err := s3MetaToAzureProperties(ctx, srcInfo.UserDefined)
 	if err != nil {
 		return objInfo, azureToObjectError(err, srcBucket, srcObject)
 	}
+	props.ContentMD5 = srcProps.ContentMD5()
```
Comment (harshavardhana) [inline cmd/gateway/azure/gateway-azure.go:901]: why did you change the md5sum?

**Review by harshavardhana — CHANGES_REQUESTED** [review]

File: cmd/gateway/azure/gateway-azure.go (hunk 1 above)
Comment (poornas) [reply cmd/gateway/azure/gateway-azure.go:901]: otherwise ListObjects has issues for the dest object as the Azure ETag is used - @kannappanr  noticed this with aws-cli

**Comment by minio-trusted** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-xl.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-dist-xl.sh | :heavy_check_mark: |
| mint-gateway-s3.sh | :x: [more...](#76019781-c248-440c-b1e1-4dd86405029a) |
| mint-gateway-azure.sh | :x: [more...](#663ae3e5-7215-429e-b191-205d653f5d41) |
| mint-gateway-nas.sh | :x: [more...](#5a2558d4-b55d-464a-84cf-ff3692db21db) |
<a name="76019781-c248-440c-b1e1-4dd86405029a"></a>
### 9544-1a7e126/mint-gateway-s3.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-dev6.minio.io:31442
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 8effcd46e3db:/mint/log /tmp/mint-logs'

(1/15) Running aws-sdk-go tests ... done in 1 seconds
(2/15) Running aws-sdk-java tests ... done in 1 seconds
(3/15) Running aws-sdk-php tests ... done in 41 seconds
(4/15) Running aws-sdk-ruby tests ... done in 2 seconds
(5/15) Running awscli tests ... FAILED in 21 seconds
{
  "name": "awscli",
  "duration": 4524,
  "function": "aws --endpoint-url http://minio-dev6.minio.io:31442 s3api get-object --bucket awscli-mint-test-bucket-5868 --key awscli-mint-test-bucket-5868-object /tmp/datafile-0-b\n",
  "status": "FAIL",
  "error": "Etag mismatch for multipart 0 byte object"
}
(5/15) Running healthcheck tests ... done in 0 seconds
(6/15) Running mc tests ... done in 18 seconds
(7/15) Running minio-dotnet tests ... done in 29 seconds
(8/15) Running minio-go tests ... FAILED in 25 seconds
{}
(8/15) Running minio-java tests ... FAILED in 44 seconds
{
  "name": "minio-java",
  "function": "enableObjectLegalHold(String bucketName, String objectName, String versionId)",
  "duration": 81,
  "status": "FAIL",
  "error": "error occurred\nErrorResponse(code = InvalidRequest, message = Bucket is missing ObjectLockConfiguration, bucketName = minio-java-test-2gqtncu, objectName = minio-java-test-1ljslc2, resource = /minio-java-test-2gqtncu/minio-java-test-1ljslc2, requestId = 160CD90291893C20, hostId = 353076bc-49fd-47b3-a777-1813f224471a)\nrequest={method=PUT, url=http://minio-dev6.minio.io:31442/minio-java-test-2gqtncu/minio-java-test-1ljslc2?legal-hold=, headers=Host: minio-dev6.minio.io:31442\nAccept-Encoding: identity\nUser-Agent: MinIO (amd64; amd64) minio-java/dev\nContent-MD5: erOisiAmIIzsh/Ze2QqGXw==\nx-amz-content-sha256: 96b73c95a8d33e664ab2170e095025b47ebd55978bb71cebd6a51e394bf96722\nx-amz-date: 20200507T202933Z\nAuthorization: AWS4-HMAC-SHA256 Credential=*REDACTED*/20200507/us-east-1/s3/aws4_request, SignedHeaders=accept-encoding;content-md5;host;x-amz-content-sha256;x-amz-date, Signature=*REDACTED*\n}\nresponse={code=400, headers=Accept-Ranges: bytes\nContent-Length: 384\nContent-Security-Policy: block-all-mixed-content\nContent-Type: application/xml\nServer: MinIO/DEVELOPMENT.GOGET\nVary: Origin\nX-Amz-Request-Id: 160CD90291893C20\nX-Xss-Protection: 1; mode=block\nDate: Thu, 07 May 2020 20:29:33 GMT\n}\n >>> [io.minio.MinioClient.execute(MinioClient.java:1211), io.minio.MinioClient.execute(MinioClient.java:1236), io.minio.MinioClient.executePut(MinioClient.java:1410), io.minio.MinioClient.executePut(MinioClient.java:1424), io.minio.MinioClient.enableObjectLegalHold(MinioClient.java:3568), FunctionalTest.enableObjectLegalHold_test(FunctionalTest.java:3303), FunctionalTest.runTests(FunctionalTest.java:4079), FunctionalTest.main(FunctionalTest.java:4192)]"
}
(8/15) Running minio-js tests ... done in 55 seconds
(9/15) Running minio-py tests ... done in 1 minutes and 6 seconds
(10/15) Running s3cmd tests ... done in 1 minutes and 2 seconds
(11/15) Running s3select tests ... done in 1 seconds
(12/15) Running security tests ... done in 0 seconds

Executed 12 out of 15 tests successfully.
```
<a name="663ae3e5-7215-429e-b191-205d653f5d41"></a>
### 9544-1a7e126/mint-gateway-azure.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-dev6.minio.io:30420
ACCESS_KEY:           minioazure
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 8f1f1a42f305:/mint/log /tmp/mint-logs'

(1/15) Running aws-sdk-go tests ... done in 8 seconds
(2/15) Running aws-sdk-java tests ... done in 2 seconds
(3/15) Running aws-sdk-php tests ... done in 10 minutes and 45 seconds
(4/15) Running aws-sdk-ruby tests ... FAILED in 4 minutes and 3 seconds
{
  "name": "aws-sdk-ruby",
  "function": "listBuckets",
  "args": {},
  "duration": 242555.54,
  "error": "Net::ReadTimeout",
  "status": "FAIL"
}
(4/15) Running awscli tests ... FAILED in 54 seconds
{
  "name": "awscli",
  "duration": 3952,
  "function": "aws --endpoint-url http://minio-dev6.minio.io:30420 s3api copy-object --bucket awscli-mint-test-bucket-12174 --storage-class REDUCED_REDUNDANCY --key datafile-1-kB-copy --copy-source awscli-mint-test-bucket-12174/datafile-1-kB\n",
  "status": "FAIL",
  "error": "An error occurred (NotImplemented) when calling the CopyObject operation: A header you provided implies functionality that is not implemented"
}
(4/15) Running healthcheck tests ... done in 0 seconds
(5/15) Running mc tests ... done in 3 minutes and 7 seconds
(6/15) Running minio-dotnet tests ... done in 3 minutes and 8 seconds
(7/15) Running minio-go tests ... FAILED in 17 seconds
{
  "args": {
    "destination": {},
    "source": {
      "Headers": {
        "X-Amz-Copy-Source": [
          "minio-go-test-yv9r11yh4f4dyscz/srcObject"
        ]
      }
    }
  },
  "duration": 2475,
  "function": "CopyObject(destination, source)",
  "message": "Metadata match failed",
  "name": "minio-go: testUserMetadataCopyingWrapper",
  "status": "FAIL"
}
(7/15) Running minio-java tests ... FAILED in 28 minutes and 39 seconds
{
  "name": "minio-java",
  "function": "enableObjectLegalHold(String bucketName, String objectName, String versionId)",
  "duration": 1825,
  "status": "FAIL",
  "error": "error occurred\nErrorResponse(code = InvalidRequest, message = Bucket is missing ObjectLockConfiguration, bucketName = minio-java-test-31g1v9, objectName = minio-java-test-2e06i2q, resource = /minio-java-test-31g1v9/minio-java-test-2e06i2q, requestId = 160CDBA182B7960F, hostId = eb54067d-5357-42f4-943b-e1fad3477c09)\nrequest={method=PUT, url=http://minio-dev6.minio.io:30420/minio-java-test-31g1v9/minio-java-test-2e06i2q?legal-hold=, headers=Host: minio-dev6.minio.io:30420\nAccept-Encoding: identity\nUser-Agent: MinIO (amd64; amd64) minio-java/dev\nContent-MD5: erOisiAmIIzsh/Ze2QqGXw==\nx-amz-content-sha256: 96b73c95a8d33e664ab2170e095025b47ebd55978bb71cebd6a51e394bf96722\nx-amz-date: 20200507T211735Z\nAuthorization: AWS4-HMAC-SHA256 Credential=*REDACTED*/20200507/us-east-1/s3/aws4_request, SignedHeaders=accept-encoding;content-md5;host;x-amz-content-sha256;x-amz-date, Signature=*REDACTED*\n}\nresponse={code=400, headers=Accept-Ranges: bytes\nContent-Length: 382\nContent-Security-Policy: block-all-mixed-content\nContent-Type: application/xml\nServer: MinIO/DEVELOPMENT.GOGET\nVary: Origin\nX-Amz-Request-Id: 160CDBA182B7960F\nX-Xss-Protection: 1; mode=block\nDate: Thu, 07 May 2020 21:17:35 GMT\n}\n >>> [io.minio.MinioClient.execute(MinioClient.java:1211), io.minio.MinioClient.execute(MinioClient.java:1236), io.minio.MinioClient.executePut(MinioClient.java:1410), io.minio.MinioClient.executePut(MinioClient.java:1424), io.minio.MinioClient.enableObjectLegalHold(MinioClient.java:3568), FunctionalTest.enableObjectLegalHold_test(FunctionalTest.java:3303), FunctionalTest.runTests(FunctionalTest.java:4079), FunctionalTest.main(FunctionalTest.java:4192)]"
}
(7/15) Running minio-js tests ... FAILED in 9 minutes and 30 seconds
{
  "name": "minio-js",
  "function": "listObjectsV2WithMetadata(bucketName, prefix, recursive, startAfter)",
  "args": "bucketName:minio-js-test-4011f28a-7816-4223-b637-ffcb217761fd, recursive:true",
  "duration": 209,
  "status": "FAIL",
  "error": "TypeError: Cannot read property '0' of undefined at /mint/run/core/minio-js/node_modules/minio/dist/main/xml-parsers.js:414:42 at Array.forEach (<anonymous>) at parseListObjectsV2WithMetadata (node_modules/minio/dist/main/xml-parsers.js:409:21) at DestroyableTransform._flush (node_modules/minio/dist/main/transformers.js:88:19) at DestroyableTransform.prefinish (node_modules/readable-stream/lib/_stream_transform.js:129:10) at prefinish (node_modules/readable-stream/lib/_stream_writable.js:611:14) at finishMaybe (node_modules/readable-stream/lib/_stream_writable.js:620:5) at endWritable (node_modules/readable-stream/lib/_stream_writable.js:643:3) at DestroyableTransform.Writable.end (node_modules/readable-stream/lib/_stream_writable.js:571:22) at IncomingMessage.onend (_stream_readable.js:673:10) at endReadableNT (_stream_readable.js:1201:12) at processTicksAndRejections (internal/process/task_queues.js:84:21)"
}
(7/15) Running minio-py tests ... done in 12 minutes and 41 seconds
(8/15) Running s3cmd tests ... FAILED in 42 seconds
{
  "name": "s3cmd",
  "duration": "1720",
  "function": "test_copy_object",
  "status": "FAIL",
  "error": ""
}
(8/15) Running s3select tests ... done in 22 seconds
(9/15) Running security tests ... done in 0 seconds

Executed 9 out of 15 tests successfully.
```
<a name="5a2558d4-b55d-464a-84cf-ff3692db21db"></a>
### 9544-1a7e126/mint-gateway-nas.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-dev7.minio.io:31944
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 576129f7471a:/mint/log /tmp/mint-logs'

(1/15) Running aws-sdk-go tests ... done in 0 seconds
(2/15) Running aws-sdk-java tests ... done in 1 seconds
(3/15) Running aws-sdk-php tests ... done in 41 seconds
(4/15) Running aws-sdk-ruby tests ... done in 2 seconds
(5/15) Running awscli tests ... done in 2 minutes and 4 seconds
(6/15) Running healthcheck tests ... done in 0 seconds
(7/15) Running mc tests ... done in 38 seconds
(8/15) Running minio-dotnet tests ... done in 29 seconds
(9/15) Running minio-go tests ... FAILED in 30 seconds
{}
(9/15) Running minio-java tests ... FAILED in 23 seconds
{
  "name": "minio-java",
  "function": "enableObjectLegalHold(String bucketName, String objectName, String versionId)",
  "duration": 35,
  "status": "FAIL",
  "error": "error occurred\nErrorResponse(code = InvalidRequest, message = Bucket is missing ObjectLockConfiguration, bucketName = minio-java-test-1fbea48, objectName = minio-java-test-23nvbgc, resource = /minio-java-test-1fbea48/minio-java-test-23nvbgc, requestId = 160CD91B5D4DD830, hostId = 49e0de48-a2b0-4353-810d-e368b74c5e98)\nrequest={method=PUT, url=http://minio-dev7.minio.io:31944/minio-java-test-1fbea48/minio-java-test-23nvbgc?legal-hold=, headers=Host: minio-dev7.minio.io:31944\nAccept-Encoding: identity\nUser-Agent: MinIO (amd64; amd64) minio-java/dev\nContent-MD5: erOisiAmIIzsh/Ze2QqGXw==\nx-amz-content-sha256: 96b73c95a8d33e664ab2170e095025b47ebd55978bb71cebd6a51e394bf96722\nx-amz-date: 20200507T203120Z\nAuthorization: AWS4-HMAC-SHA256 Credential=*REDACTED*/20200507/us-east-1/s3/aws4_request, SignedHeaders=accept-encoding;content-md5;host;x-amz-content-sha256;x-amz-date, Signature=*REDACTED*\n}\nresponse={code=400, headers=Accept-Ranges: bytes\nContent-Length: 384\nContent-Security-Policy: block-all-mixed-content\nContent-Type: application/xml\nServer: MinIO/DEVELOPMENT.GOGET\nVary: Origin\nX-Amz-Request-Id: 160CD91B5D4DD830\nX-Xss-Protection: 1; mode=block\nDate: Thu, 07 May 2020 20:31:20 GMT\n}\n >>> [io.minio.MinioClient.execute(MinioClient.java:1211), io.minio.MinioClient.execute(MinioClient.java:1236), io.minio.MinioClient.executePut(MinioClient.java:1410), io.minio.MinioClient.executePut(MinioClient.java:1424), io.minio.MinioClient.enableObjectLegalHold(MinioClient.java:3568), FunctionalTest.enableObjectLegalHold_test(FunctionalTest.java:3303), FunctionalTest.runTests(FunctionalTest.java:4079), FunctionalTest.main(FunctionalTest.java:4192)]"
}
(9/15) Running minio-js tests ... done in 33 seconds
(10/15) Running minio-py tests ... done in 53 seconds
(11/15) Running s3cmd tests ... done in 15 seconds
(12/15) Running s3select tests ... done in 0 seconds
(13/15) Running security tests ... done in 0 seconds

Executed 13 out of 15 tests successfully.
```
Deleting image on docker hub
Deleting image locally

**Review by Praveenrajmani — APPROVED** [review]
LGTM

**Comment by Praveenrajmani** [comment]
@poornas Can you check the mint failure reported on `awscli copy object` and in minio-go `testUserMetadataCopyingWrapper`

**Comment by poornas** [comment]
> @poornas Can you check the mint failure reported on `awscli copy object` and in minio-go `testUserMetadataCopyingWrapper`

awscli copy failure is because storage class rr is not supported in Azure, other error happens with master also - reason is ComposeObject does a CopyObjectPart that is unimplemented in Azure.

**Review by kannappanr — APPROVED** [review]
LGTM

File: cmd/gateway/azure/gateway-azure.go (hunk 1 above)
Comment (vadmeste) [reply cmd/gateway/azure/gateway-azure.go:901]: Actually I tried to copy a multipart file in AWS S3 and it seems the ETag of the dest object is different to the source object.

```
11:36 $ mc stat s3/v-testbucket/6mb
Name      : 6mb
Date      : 2020-05-08 11:28:36 CET
Size      : 6.0 MiB
ETag      : 1300691e19c44c68501fcf2ca875f46e-2
Type      : file
Metadata  :
  Content-Type: application/octet-stream

Name      : 6mb.copy
Date      : 2020-05-08 11:36:18 CET
Size      : 6.0 MiB
ETag      : beb0ad7c527fdd8d8d56386b8a29b56e
Type      : file
Metadata  :
  Content-Type: application/octet-stream
```

However it is weird because the ETag of the dest object is the md5 sum of the source object.

Comment (kannappanr) [reply cmd/gateway/azure/gateway-azure.go:901]: Yes, in the case of Azure

```
 {
            "Key": "128m",
            "LastModified": "2020-05-08T15:41:19.000Z",
            "ETag": "\"0x8D7F36640F24553-1\"",
            "Size": 134217728,
            "StorageClass": "STANDARD",
            "Owner": {
                "DisplayName": "",
                "ID": "02d6176db174dc93cb1b899f7c6078f08654445fe8cf1b6ce98d8855f66bdbf4"
            }
        },
        {
            "Key": "128m.copy",
            "LastModified": "2020-05-08T15:42:19.000Z",
            "ETag": "\"0x8D7F366647230FC-1\"",
            "Size": 134217728,
            "StorageClass": "STANDARD",
            "Owner": {
                "DisplayName": "",
                "ID": "02d6176db174dc93cb1b899f7c6078f08654445fe8cf1b6ce98d8855f66bdbf4"
            }
        },

```
```
$ mc stat myazure/testbucket/128m
Name      : 128m
Date      : 2020-05-08 08:41:19 PDT 
Size      : 128 MiB 
ETag      : 190d5e1aa1b3b051102415baccfc57ea-1 
Type      : file 
Metadata  :
  Content-Type: application/octet-stream 

Name      : 128m.copy
Date      : 2020-05-08 08:42:19 PDT 
Size      : 128 MiB 
ETag      : 0x8D7F366647230FC-1 
Type      : file 
Metadata  :
  Content-Type: application/octet-stream 
```
In the case of the original putobject, irrespective of this PR, there is mismatch between `etag` listed by azure and what gateway displays as part of `head-object`

**Review by harshavardhana — APPROVED** [review]
