### PR TITLE
Only heal on disks where we are sure that healing is needed

### LINKED ISSUE #7146: heal fails if an underlying disk is unmounted
Have 4 loop mounts (to simulate disks)

```
/dev/loop0       1038336     34140   1004196   4% /tmp/xl/export1
/dev/loop1       1038336     34172   1004164   4% /tmp/xl/export2
/dev/loop2       1038336     34172   1004164   4% /tmp/xl/export3
/dev/loop3       1038336     34140   1004196   4% /tmp/xl/export4
```

start minio server:
```
minio server /tmp/export{1..4}
```

```
unmount /tmp/xl/export4
```

```
krishna@escape:~$ mc admin heal -q myminio
[Red    ->    Red] ** system:disk-format **
mc: <ERROR> Unable to display heal status. Heal had an error - Bucket not found: .minio.sys
krishna@escape:~$ 
```

Healing process is trying to heal config.json on the unmounted disk and errors out.

## Expected Behavior

healing process should not exit

## Possible Solution

Healing process should not try to heal on unavailable disks.
(I will send a PR)

## Steps to Reproduce (for bugs)

Explained in description

## Regression

No

### PR DESCRIPTION
**Pull request by krishnasrinivas**
fixes #7146 

## Description

Heal only on known errors (as it is safer) i.e we should not heal an object on errors like errVolumeNotFound errUnformatedDisk etc.

## Regression

No, but the bug is exposed after da98ea8a59df1a68a623a8fa840c7ff2d3fc51b3

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added unit tests to cover my changes.
- [ ] I have added/updated functional tests in [mint](https://github.com/minio/mint). (If yes, add `mint` PR # here: )
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by krishnasrinivas** [comment]
requesting review from @donatello

**Comment by kannappanr** [comment]
@krishnasrinivas PTAL Travis failures https://travis-ci.org/minio/minio/jobs/484116213#L1466

**Comment by minio-ops** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-tls.sh | :heavy_check_mark: |
| mint-compression-xl.sh | :heavy_check_mark: |
| mint-xl.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-compression-fs.sh | :heavy_check_mark: |
| mint-worm.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-dist-xl.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :x: [more...](#491356f2-61a2-419d-a0cd-af813396f0bd) |
<a name="491356f2-61a2-419d-a0cd-af813396f0bd"></a>
### 7148-311aa66/mint-large-bucket.sh.log:
```
Running with
SERVER_ENDPOINT:      minikube:30342
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 0f46455a6b0e:/mint/log /tmp/mint-logs'

(1/13) Running awscli tests ... FAILED in 3 minutes and 16 seconds
{
  "name": "awscli",
  "duration": 73374,
  "function": "delete_bucket\n",
  "status": "FAIL",
  "error": "remove_bucket failed: s3://awscli-mint-test-bucket-4870 An error occurred (BucketNotEmpty) when calling the DeleteBucket operation: The bucket you tried to delete is not empty"
}

Executed 0 out of 13 tests successfully.
```

File: cmd/xl-v1-healing.go [hunk 1]
```diff
@@ -248,6 +249,30 @@ func listAllBuckets(storageDisks []StorageAPI) (buckets map[string]VolInfo,
...
+		return true
+	case errCorruptedFormat:
+		return true
+	}
+	if xlErr == nil {
+		// If xl.json was read fine but there is some problem with the part.N files.
+		if dataErr == errFileNotFound {
+			return true
+		}
+		if _, ok := dataErr.(hashMismatchError); ok {
```
Comment (donatello) [inline cmd/xl-v1-healing.go:266]: I think hashMismatchError would not be caught in this manner when the error comes from a remote disk as error type is not preserved on the network - so a err.String() comparison may be needed. Could you test a distributed case with corrupt file on a remote disk to check this?

**Review by donatello — CHANGES_REQUESTED** [review]

File: cmd/xl-v1-healing.go (hunk 1 above)
Comment (krishnasrinivas) [reply cmd/xl-v1-healing.go:266]: good catch

**Comment by minio-ops** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-tls.sh | :heavy_check_mark: |
| mint-compression-xl.sh | :heavy_check_mark: |
| mint-xl.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-compression-fs.sh | :heavy_check_mark: |
| mint-worm.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-dist-xl.sh | :heavy_check_mark: |

File: cmd/xl-v1-healing.go [hunk 2]
```diff
@@ -248,6 +249,30 @@ func listAllBuckets(storageDisks []StorageAPI) (buckets map[string]VolInfo,
...
+			return true
+		}
+		if quorumModTime != meta.Stat.ModTime {
```
Comment (harshavardhana) [inline cmd/xl-v1-healing.go:269]: Perhaps if xlMeta.Parts are different we should also heal. We should also heal if xlMeta.Version is different?

**Review by harshavardhana — CHANGES_REQUESTED** [review]

**Review by donatello — APPROVED** [review]

File: cmd/xl-v1-healing.go (hunk 2 above)
Comment (donatello) [reply cmd/xl-v1-healing.go:269]: I assumed that those differences are caught by their modTime being not equal to quorumModTime.

Comment (harshavardhana) [reply cmd/xl-v1-healing.go:269]: That is acceptable @donatello

**Review by harshavardhana — APPROVED** [review]
