### PR TITLE
heal: Add healing support for bucket metadata files.

### LINKED ISSUE #2980: [distributed]: Enable quick heal for  'policy.json', 'notification.xml' , 'listeners.json'
Basically all bucket metadata files as well.

### LINKED ISSUE #3237: [distributed] HealObject() tries to heal when one of the servers is down
## Expected Behavior
HealObject() should return immediately as there is nothing to heal.

## Current Behavior
ListHealObject() tries to heal the object thinking that the object in the down server is outdated.

## Steps to Reproduce (for bugs)
1. start 3:3 dxl
3. Upload a `bucket/object`
2. Bring down 6th server
3. Exec heal command on the bucket: (this takes up CPU healing the object)

```
krishna@escape:~$ MINIO_ACCESS_KEY=SXO8VW2OFKKP2OG7AC85 MINIO_SECRET_KEY=CKWSSgrUgvfUMTaNBkB63exet4WW+uNhQvi91Bc3 minio control heal http://localhost:9005/testbucket
[0] ◐ SUCCESS  5g                                                                                                    
krishna@escape:~$ 
```

It actually tried to heal the object and said success.

Fix:
ListObjectsHeal() should not have returned the object
HealObject() should not try to heal the object (xlShouldHeal should return false)

### PR DESCRIPTION
**Pull request by harshavardhana**
## Description
This change implements healing of bucket metadata under `policy.json, notification.xml and listener.json`

## Motivation and Context
Fixes #2980 

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by harshavardhana** [comment]
Tests are pending working on it.. but this is ready for review.

File: cmd/xl-v1-healing.go [hunk 1]
```diff
@@ -82,29 +86,56 @@ func (xl xlObjects) HealBucket(bucket string) error {
...
-	if !IsValidBucketName(bucket) {
-		return traceError(BucketNameInvalid{Bucket: bucket})
+// Heals all the metadata associated for a given bucket.
+func healBucketMetadata(storageDisks []StorageAPI, bucket string) error {
+	policyPath := pathJoin(bucketConfigPrefix, bucket, policyJSON)
+	// Lock the `policy.json` before healing.
+	policyLock := nsMutex.NewNSLock(minioMetaBucket, policyPath)
+	policyLock.RLock()
+	defer policyLock.RUnlock()
+
```
Comment (donatello) [inline cmd/xl-v1-healing.go:148]: Since this mutates the file on on some disks, shouldn't this take a write lock instead of read?

Comment (donatello) [reply cmd/xl-v1-healing.go:148]: Also, it appears that this keeps the lock longer than necessary. It may be better to write this section with this scheme:

``` go
f := func(){
    policyLock := ...
    policyLock.RLock() // or write lock - not sure
    defer policyLock.RUnlock()
    return healObject(...)
}
if err := f(); err != nil {
    if !isErrObjectNotFound(err) {
        return err
    }
}
```

File: cmd/xl-v1-healing.go [hunk 2]
```diff
@@ -82,29 +86,56 @@ func (xl xlObjects) HealBucket(bucket string) error {
...
 
-	// Verify if object is valid.
-	if !IsValidObjectName(object) {
-		return traceError(ObjectNameInvalid{Bucket: bucket, Object: object})
+	nConfigPath := path.Join(bucketConfigPrefix, bucket, bucketNotificationConfig)
+	// Lock the `notificiation.xml` before healing.
+	ncLock := nsMutex.NewNSLock(minioMetaBucket, nConfigPath)
+	ncLock.RLock()
+	defer ncLock.RUnlock()
+
```
Comment (donatello) [inline cmd/xl-v1-healing.go]: Same points as for policy above.

File: cmd/xl-v1-healing.go [hunk 3]
```diff
@@ -82,29 +86,56 @@ func (xl xlObjects) HealBucket(bucket string) error {
...
-	// Lock the object before healing.
-	objectLock := nsMutex.NewNSLock(bucket, object)
-	objectLock.RLock()
-	defer objectLock.RUnlock()
+	// Lock the `listeners.json` before healing.
+	lConfigPath := path.Join(bucketConfigPrefix, bucket, bucketListenerConfig)
+	listenLock := nsMutex.NewNSLock(minioMetaBucket, lConfigPath)
+	listenLock.RLock()
+	defer listenLock.RUnlock()
+
```
Comment (donatello) [inline cmd/xl-v1-healing.go:165]: Same points as for policy above.

File: cmd/xl-v1-healing.go (hunk 1 above)
Comment (harshavardhana) [reply cmd/xl-v1-healing.go:148]: > Since this mutates the file on on some disks, shouldn't this take a write lock instead of read?

The reason to not hold Write lock is that it would block the Read operations, also since we are only writing to missing disks. Additional advantage here is that Write() outside of this call at this path will still block because of our Read lock. So all in all it works without much trouble. 

This is how object healing is implemented and it is a correct behavior.

File: cmd/xl-v1-healing.go (hunk 2 above)
Comment (harshavardhana) [reply cmd/xl-v1-healing.go]: Same as above.

File: cmd/xl-v1-healing.go (hunk 3 above)
Comment (harshavardhana) [reply cmd/xl-v1-healing.go:165]: Same as above.

File: cmd/xl-v1-healing.go (hunk 1 above)
Comment (fwessels) [reply cmd/xl-v1-healing.go:148]: What happens if a heal on the same object would happen simultaneously on more than one nodes? Any chance of corrupted data?

Comment (harshavardhana) [reply cmd/xl-v1-healing.go:148]: Whoever completes last gets to create their missing blocks which are always the same given the state of the object.

File: cmd/xl-v1-healing.go [hunk 4]
```diff
@@ -82,29 +86,47 @@ func (xl xlObjects) HealBucket(bucket string) error {
...
+// Heals all the metadata associated for a given bucket, this function
+// heals `policy.json`, `notification.xml` and `listeners.json`.
+func healBucketMetadata(storageDisks []StorageAPI, bucket string) error {
+	healBucketMetaFn := func(metaPath string) error {
+		metaLock := nsMutex.NewNSLock(minioMetaBucket, metaPath)
+		metaLock.RLock()
+		defer metaLock.RUnlock()
+		// Heals the metaPath.
+		if err := healObject(storageDisks, minioMetaBucket, metaPath); err != nil {
+			if !isErrObjectNotFound(err) {
```
Comment (fwessels) [inline cmd/xl-v1-healing.go]: Can collapse two if statements into a single one

**Review by fwessels — COMMENTED** [review]
LGTM

File: cmd/xl-v1-healing.go (hunk 4 above)
Comment (harshavardhana) [reply cmd/xl-v1-healing.go]: Yes will do

File: cmd/xl-v1-healing.go (hunk 1 above)
Comment (donatello) [reply cmd/xl-v1-healing.go:148]: > The reason to not hold Write lock is that it would block the Read operations, also since we are only writing to missing disks. Additional advantage here is that Write() outside of this call at this path will still block because of our Read lock. So all in all it works without much trouble. 

Ok. The code is however holding onto the lock a bit longer than necessary - e.g. policy path lock is held during notification config heal, and notification path lock is held during listener config heal.

Comment (harshavardhana) [reply cmd/xl-v1-healing.go:148]: I already addressed that @donatello - check the latest patch.

**Comment by harshavardhana** [comment]
This is ready for review, this patch only adds quickHeal part.

**Comment by harshavardhana** [comment]
Any reviews here @minio/core ?

**Comment by donatello** [comment]
I will do shortly.

**Review by donatello — APPROVED** [review]
