### PR TITLE
fix: avoid metadata cache without data for all callers

### LINKED ISSUE #19925: with mincache enabled `HEAD` request returns different `Content-Length` then matching `GET` on a KMS setup
I have enabled server-side encryption on my bucket and uploaded `Audi cabriolet 01.jpg` of 2,971,514 bytes to the `test` bucket. When I try to copy the file using `mc`, then I got the following error: `Input reader closed pre-maturely. Expected '2972986' bytes, but only received '2971514' bytes.`

I ran the `mc` command using the `--debug` flag and noticed that the `HEAD` request returns a different length then the `GET` request. This is the `HEAD` request:
```
HEAD /test/audi/Audi%20cabriolet%2001.jpg HTTP/1.1
Host: tenant-rdk-hl.tenant-rdk:9000
User-Agent: MinIO (linux; amd64) minio-go/v7.0.70 __debug_bin2996553503/DEVELOPMENT.GOGET
Authorization: AWS4-HMAC-SHA256 Credential=l5m7mQiwUi2GCSH3/20240612/us-east-1/s3/aws4_request, SignedHeaders=host;x-amz-content-sha256;x-amz-date, Signature=**REDACTED**
X-Amz-Content-Sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
X-Amz-Date: 20240612T160723Z
```
`HEAD` response:
```
HTTP/1.1 200 OK
Content-Length: 2972986
Accept-Ranges: bytes
Content-Type: image/jpeg
Date: Wed, 12 Jun 2024 16:07:23 GMT
Etag: "efd738945e94f4dbb8588b788b2ea7c1"
Last-Modified: Wed, 12 Jun 2024 15:21:24 GMT
Server: MinIO
Strict-Transport-Security: max-age=31536000; includeSubDomains
Vary: Origin
Vary: Accept-Encoding
X-Amz-Id-2: d5a265f7265c149d31b79b2568737f9e0d97aab546838b9090d7403265887733
X-Amz-Request-Id: 17D84D79C009F04A
X-Content-Type-Options: nosniff
X-Xss-Protection: 1; mode=block
```
Then it performs the actual `GET` and that request looks like:
```
GET /test/audi/Audi%20cabriolet%2001.jpg HTTP/1.1
Host: tenant-rdk-hl.tenant-rdk:9000
User-Agent: MinIO (linux; amd64) minio-go/v7.0.70 __debug_bin2996553503/DEVELOPMENT.GOGET
Accept-Encoding: identity
Authorization: AWS4-HMAC-SHA256 Credential=l5m7mQiwUi2GCSH3/20240612/us-east-1/s3/aws4_request, SignedHeaders=host;x-amz-content-sha256;x-amz-date, Signature=**REDACTED**
X-Amz-Content-Sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
X-Amz-Date: 20240612T160904Z
```
And the response is:
```
HTTP/1.1 200 OK
Content-Length: 2971514
Accept-Ranges: bytes
Content-Type: image/jpeg
Date: Wed, 12 Jun 2024 16:09:04 GMT
Etag: "efd738945e94f4dbb8588b788b2ea7c1"
Last-Modified: Wed, 12 Jun 2024 15:21:24 GMT
Server: MinIO
Strict-Transport-Security: max-age=31536000; includeSubDomains
Vary: Origin
Vary: Accept-Encoding
X-Amz-Id-2: d5a265f7265c149d31b79b2568737f9e0d97aab546838b9090d7403265887733
X-Amz-Request-Id: 17D84D916E7CC820
X-Amz-Server-Side-Encryption: aws:kms
X-Amz-Server-Side-Encryption-Aws-Kms-Key-Id: arn:aws:kms:tenant-rdk-key
X-Content-Type-Options: nosniff
X-Xss-Protection: 1; mode=block
```
This seems to be a bug in Minio, because both the `HEAD` and `GET` requests should return the same content length. I never have seen this issue without encryption.

### PR DESCRIPTION
**Pull request by harshavardhana**
## Community Contribution License
All community contributions in this pull request are licensed to the project maintainers
under the terms of the [Apache 2 license](https://www.apache.org/licenses/LICENSE-2.0). 
By creating this pull request I represent that I have the right to license the 
contributions to the project maintainers under the Apache 2 license.

## Description
fix: avoid metadata cache without data for all callers

## Motivation and Context
there are a lot of unnecessary places where we set
incorrect metadata regarding the objects in SSE,
causing premature errors thrown via the client.

fixes #19925 
## How to test this PR?
As per #19925 

## Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Optimization (provides speedup with no functional changes)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [ ] Fixes a regression (If yes, please add `commit-id` or `PR #` here)
- [ ] Unit tests added/updated
- [ ] Internal documentation updated
- [ ] Create a documentation update request [here](https://github.com/minio/docs/issues/new?label=doc-change,title=Doc+Updated+Needed+For+PR+github.com%2fminio%2fminio%2fpull%2fNNNNN)

### CODE REVIEW

File: cmd/object-handlers.go [hunk 1]
```diff
@@ -665,6 +632,12 @@ func (api objectAPIHandlers) getObjectHandler(ctx context.Context, objectAPI Obj
 
 	setHeadGetRespHeaders(w, r.Form)
 
+	var buf *bytebufferpool.ByteBuffer
+	if update && globalCacheConfig.MatchesSize(objInfo.Size) {
```
Comment (jiuker) [inline cmd/object-handlers.go:634]: please remove   Line 613-Line 614 and then LGTM
```diff
-		// Never store encrypted objects in cache.
-		update = false
```
Tested with this removed.

**Review by jiuker — CHANGES_REQUESTED** [review]

**Review by jiuker — APPROVED** [review]

**Review by ramondeklein — CHANGES_REQUESTED** [review]
Incorrect comment. The `update` variable was used later on...

**Comment by ramondeklein** [comment]
I see that @jiuker pushed to this branch too, so I pushed my code clean-up too. Hope that's okay...

**Review by ramondeklein — APPROVED** [review]

**Comment by ramondeklein** [comment]
This PR fixes the `Input reader closed pre-maturely` error.

File: cmd/object-handlers.go (hunk 1 above)
Comment (harshavardhana) [reply cmd/object-handlers.go:634]: why? @jiuker

Comment (jiuker) [reply cmd/object-handlers.go:634]: We save the encrypted objects in cache. @harshavardhana. Configured  KMS is SEE
