### PR TITLE
Avoid blocking send on channels inside mutex

### LINKED ISSUE #5023: minio client hangs on certain buckets after certain operations
When you do a combination of "mc find watch" on one terminal and "mc cp" on another, mc hangs on certain commands on the bucket where this operation was performed.

## Expected Behavior
At any given point, mc cp and ls command should not hang on any bucket

## Current Behavior
Once the server gets into this state, mc cp and mc ls commands hang on those buckets, on which these operations were performed.

From then on, whenever you do a mc cp onto any other bucket on the server, that also starts exhibiting the same behavior.

## Steps to Reproduce (for bugs)
Environment: Connecting to my local Minio server

Bucket Name: ``` test ```
Bucket  has the following files
```
datafile-100-kB
datafile-11-MB
datafile-33-kB
datafile-6-MB
datafile-1.03-MB
datafile-1-b
datafile-5-MB
listfiles.go
datafile-10-kB
datafile-1-MB
datafile-65-MB
list.go
listfiles.go
```
____________________________________________
On terminal 1
enter the following command
```
mc find myminio/test --watch
```
You should only see
```
/test/datafile-1-MB
```
Now keep pressing Ctrl +C, until it displays the last file
```
/test/datafile-1-MB
^C
/test/datafile-1-b
^C
/test/datafile-1.03-MB
^C
/test/datafile-10-kB
^C
/test/datafile-100-kB
^C
/test/datafile-11-MB
^C
/test/datafile-33-kB
^C
/test/datafile-5-MB
^C
/test/datafile-6-MB
^C
/test/datafile-65-MB
^C
/test/list.go
^C
/test/listfiles.go
```

At this point on Terminal 2, enter the following command
```
mc cp list.go myminio/test
```
on Terminal 1, you should see this
```
panic: close of closed channel

goroutine 40 [running]:
github.com/minio/mc/cmd.(*watchObject).Close(0xc4202a49e0)
	/home/test/gopath/src/github.com/minio/mc/cmd/watch.go:84 +0x2f
github.com/minio/mc/cmd.(*s3Client).Watch.func2(0xc4202a49e0, 0xc4202b0f00, 0xc4202b0de0, 0xc42030f060, 0xc4202b0d80)
	/home/test/gopath/src/github.com/minio/mc/cmd/client-s3.go:495 +0xc9a
created by github.com/minio/mc/cmd.(*s3Client).Watch
	/home/test/gopath/src/github.com/minio/mc/cmd/client-s3.go:495 +0x90e
```

-------------------------------------
On terminal 1, enter the following command
```
mc find myminio/test --watch
```
you should see
```
/test/datafile-1-MB
```
now, on terminal 2, enter the following command multiple times

```
mc cp list.go myminio/test
```
on the first terminal you will see
```
/test/datafile-1-MB
myminiomyminio/test/list.go
myminiomyminio/test/list.go
myminiomyminio/test/list.go
myminiomyminio/test/list.go
myminiomyminio/test/list.go
myminiomyminio/test/list.go
myminiomyminio/test/list.go
myminiomyminio/test/list.go
myminiomyminio/test/list.go
myminiomyminio/test/list.go
^C
/test/datafile-1-b
panic: send on closed channel
	panic: close of closed channel

goroutine 5 [running]:
github.com/minio/mc/cmd.(*watchObject).Close(0xc42000c4c0)
	/home/test/gopath/src/github.com/minio/mc/cmd/watch.go:84 +0x2f
panic(0x8aa440, 0xc42032cac0)
	/home/test/go/src/runtime/panic.go:489 +0x2cf
github.com/minio/mc/cmd.(*s3Client).Watch.func2(0xc42000c4c0, 0xc42001a2a0, 0xc42001a180, 0xc4202f19a0, 0xc42001a120)
	/home/test/gopath/src/github.com/minio/mc/cmd/client-s3.go:461 +0x964
created by github.com/minio/mc/cmd.(*s3Client).Watch
	/home/test/gopath/src/github.com/minio/mc/cmd/client-s3.go:495 +0x90e

```
------------------------
on terminal 1, enter the following command 
```
mc find myminio/test --watch
```
you should see
```
/test/datafile-1-MB
```
now, on terminal 2, enter the following command multiple times

on the first terminal you will see
```
/test/datafile-1-MB
myminiomyminio/test/list.go
myminiomyminio/test/list.go
myminiomyminio/test/list.go
myminiomyminio/test/list.go
myminiomyminio/test/list.go
myminiomyminio/test/list.go
myminiomyminio/test/list.go
myminiomyminio/test/list.go
myminiomyminio/test/list.go
myminiomyminio/test/list.go
myminiomyminio/test/list.go
myminiomyminio/test/list.go
myminiomyminio/test/list.go
myminiomyminio/test/list.go
myminiomyminio/test/list.go
myminiomyminio/test/list.go
myminiomyminio/test/list.go
```
Basically, for every single mc cp on terminal 2, now you will start seeing multiple lines being displayed on terminal 1. This is an indication that something is wrong in the server.

now press Ctrl +C on terminal 1

you should see
```
/test/datafile-1-b
```
on terminal 2, enter the following command
```
mc cp list.go myminio/test
```
you will see the following panic on terminal 1
```
panic: send on closed channel
	panic: close of closed channel

goroutine 37 [running]:
github.com/minio/mc/cmd.(*watchObject).Close(0xc4202ed920)
	/home/test/gopath/src/github.com/minio/mc/cmd/watch.go:84 +0x2f
panic(0x8aa440, 0xc42035e500)
	/home/test/go/src/runtime/panic.go:489 +0x2cf
github.com/minio/mc/cmd.(*s3Client).Watch.func2(0xc4202ed920, 0xc4202c9560, 0xc4202c9440, 0xc4202ed560, 0xc4202c93e0)
	/home/test/gopath/src/github.com/minio/mc/cmd/client-s3.go:461 +0x964
created by github.com/minio/mc/cmd.(*s3Client).Watch
	/home/test/gopath/src/github.com/minio/mc/cmd/client-s3.go:495 +0x90e
```

-------------------

Now on terminal 1, enter the following command

```
mc find myminio/test --watch
```
```
/test/datafile-1-MB
```
press Ctrl + C again

On terminal 2, enter the mc cp command again

Now the cp command should hang

press Ctrl + C on terminal 2 

On terminal 3, enter 
```
mc ls myminio/test 
```
you should see the command hang

## Your Environment

* Version used (`minio version`): 2017-09-29T19:16:56Z
* Environment name and version (e.g. nginx 1.9.1):
* Server type and version:
* Operating System and version (`uname -a`):
Linux ubuntu-ltp 4.10.0-35-generic #39-Ubuntu SMP Wed Sep 13 07:46:59 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
* Link to your project:

### PR DESCRIPTION
**Pull request by krisis**
## Description

The server side implementation of ListenBucketNotification uses channels to send notification events from the origin of the event like PutObject to the ListenBucketHandler (used by mc find --watch internally). The channels are stored in a map which is protected by a mutex. ListenBucketHandler does the following when a client closes connection.

- sendBucketNotification returns immediately after a failed write (over HTTP). This means we have a channel that has a sender with no receiver
- removes reference to the channel from the map
- closes the channel.

On the other hand, a concurrent PutObjectHandler does the following,

- send notification event on channels read from the map (note: this is inside the critical section)
- release the namespace mutex lock

In this scenario, PutObjectHandler is blocked, holding the mutex protecting the map of channels and the namespace mutex since the channels used to send notification is blocked (remember, it has no receiver).

This change removes the cyclic dependency between the event channel and map of ARN to channels by using a separate done channel to signal that the client has quit.

Fixes #5023 
## Motivation and Context

https://github.com/minio/minio/issues/5023
## How Has This Been Tested?

Not yet.
## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Review by harshavardhana — APPROVED** [review]

File: cmd/event-notifier.go [hunk 1]
```diff
@@ -230,7 +230,14 @@ func (en *eventNotifier) SendListenerEvent(arn string, event []NotificationEvent
...
 	ch, ok := en.internal.connectedListeners[arn]
 	if ok {
-		ch <- event
+		// To avoid blocking of send event over the channel
+		// while inside critical section.
+		//FIXME: The intermediary channel can be replaced by
+		//the actual http.ResponseWriter.
+		select {
+		case ch <- event:
+		default:
```
Comment (harshavardhana) [inline cmd/event-notifier.go]: Can we log an error here?

File: cmd/event-notifier.go [hunk 2]
```diff
@@ -230,7 +230,14 @@ func (en *eventNotifier) SendListenerEvent(arn string, event []NotificationEvent
 
 	ch, ok := en.internal.connectedListeners[arn]
 	if ok {
-		ch <- event
+		// To avoid blocking of send event over the channel
+		// while inside critical section.
+		//FIXME: The intermediary channel can be replaced by
```
Comment (harshavardhana) [inline cmd/event-notifier.go]: Also comment can have a space after `//`

**Review by harshavardhana — CHANGES_REQUESTED** [review]

**Comment by kannappanr** [comment]
This fix doesn't do much for the behavior. Please see the attached file
[krisis_fix_failure_1.txt](https://github.com/minio/minio/files/1366644/krisis_fix_failure_1.txt)

**Comment by harshavardhana** [comment]
> This fix doesn't do much for the behavior. Please see the attached file
> krisis_fix_failure_1.txt

I don't think its fully finished yet @kannappanr

**Comment by harshavardhana** [comment]
> I don't think its fully finished yet @kannappanr

My bad it should work @kannappanr can you double check if you are running the right build? Because of this line
```
        /home/kannappan/gopath/src/github.com/minio/minio/cmd/event-notifier.go:233 +0x124
```
This still shows old code. Instead we have moved to line 238.

**Comment by kannappanr** [comment]
Yes, with this build, I am unable to reproduce the issue.

**Comment by harshavardhana** [comment]
Thanks @kannappanr

File: cmd/event-notifier.go (hunk 1 above)
Comment (krisis) [reply cmd/event-notifier.go]: @harshavardhana What would the error message be? What do we intend to inform our users here?

Comment (harshavardhana) [reply cmd/event-notifier.go]:
```
errorIf(errors.New("blocked channel"), "Unable to send the event to %s, possibly no receiver", arn) 
```
This log will be removed by moving to http.ResponseWriter.

**Review by harshavardhana — APPROVED** [review]

File: cmd/event-notifier.go [hunk 3]
```diff
@@ -230,7 +230,19 @@ func (en *eventNotifier) SendListenerEvent(arn string, event []NotificationEvent
...
-		ch <- event
+		// To avoid blocking of send event over the channel
+		// while inside critical section.
+		// FIXME: The intermediary channel can be replaced by
+		// the actual http.ResponseWriter.
+		select {
+		case ch <- event:
+		default:
+			// When there is no receiver at the other end
+			// of the event channel, the channel blocks
```
Comment (donatello) [inline cmd/event-notifier.go]: I don't think fix is correct - it would introduce a new problem. The ListenBucketNotificationHandler is the only go routine that listens on the channel and writes any received events to the http response writer. This means that between iterations of this loop, sending on the channel is blocked (because there is no listener). This in turn means that this select block will drop events, thus losing them.

See https://play.golang.org/p/oPmqFoaNA7 for a demonstration.

**Review by donatello — CHANGES_REQUESTED** [review]
This bug needs some rethinking - possibly directly writing to the response-writer will work, but it needs to be synchronized with other writers.

File: cmd/event-notifier.go (hunk 3 above)
Comment (harshavardhana) [reply cmd/event-notifier.go]: Loosing is acceptable in this scenario @donatello , we are aware that it will happen. So there is a comment on why it is okay ignore. The reasoning is simple this only happens on a unbuffered channel when indeed there is no receiver. This part of the code is also scheduled to be quickly fixed by moving to response writers instead of channel.

Comment (harshavardhana) [reply cmd/event-notifier.go]: Also this situation only happens when there are other active listeners.. which are non-blocking so it is highly unlikely that all of them are blocking and not receiving. Single listener `default:` should never get executed.

**Comment by harshavardhana** [comment]
> This bug needs some rethinking - possibly directly writing to the response-writer will work, but it needs to be synchronized with other writers.

This is out of scope in this PR - IMO.

**Comment by harshavardhana** [comment]
If the stop gap solution is not acceptable, i guess our current server is fine and it is pretty rare to reproduce this issue. We can fully implement the responseWriter style which does io.MultiWriter will work in this scenario and we can close this PR. @donatello @krisis

File: cmd/bucket-notification-handlers.go [hunk 4]
```diff
@@ -226,23 +226,14 @@ func writeNotification(w http.ResponseWriter, notification map[string][]Notifica
...
 		select {
-		case events := <-arnListenerCh:
-			if err := writeNotification(w, map[string][]NotificationEvent{"Records": events}); err != nil {
-				errorIf(err, "Unable to write notification to client.")
-				return
-			}
-		case <-time.After(globalSNSConnAlive): // Wait for global conn active seconds.
-			if err := writeNotification(w, dummyEvents); err != nil {
+		case <-time.After(globalSNSConnAlive):
+			if err := writeNotification(w, emptyEvent); err != nil {
```
Comment (donatello) [inline cmd/bucket-notification-handlers.go]: It is not clear to me if `ResponseWriter` is concurrent-safe. We are writing in one thread here, and in another when events are sent.

File: cmd/bucket-notification-handlers.go [hunk 5]
```diff
@@ -226,25 +218,51 @@ func writeNotification(w http.ResponseWriter, notification map[string][]Notifica
...
+// unbuffered channels.
+func newListenChan() *listenChan {
+	return &listenChan{
+		doneCh: make(chan struct{}),
+		dataCh: make(chan []NotificationEvent),
+	}
+}
+
+// sendNotificationEvent sends notification events on the data channel
+// until doneCh is not closed
```
Comment (donatello) [inline cmd/bucket-notification-handlers.go]: s/until doneCh is not closed/unless doneCh is closed/

File: cmd/bucket-notification-handlers.go [hunk 6]
```diff
@@ -226,25 +218,51 @@ func writeNotification(w http.ResponseWriter, notification map[string][]Notifica
...
+	case <-l.doneCh:
+	// Blocks until receiver is available.
+	case l.dataCh <- events:
+	}
+}
+
+// waitForListener writes event notification OR whitespaces on
+// ResponseWriter until client closes connection
+func (l *listenChan) waitForListener(w http.ResponseWriter) {
+	emptyEvent := map[string][]NotificationEvent{"Records": nil}
```
Comment (donatello) [inline cmd/bucket-notification-handlers.go]: Can be simplified to just: 
`emptyEvent := map[string][]NotificationEvent{}`
since nil is a zero value anyway.

File: cmd/bucket-notification-handlers.go [hunk 7]
```diff
@@ -226,25 +218,51 @@ func writeNotification(w http.ResponseWriter, notification map[string][]Notifica
...
 				return
 			}
-		case <-time.After(globalSNSConnAlive): // Wait for global conn active seconds.
-			if err := writeNotification(w, dummyEvents); err != nil {
-				// FIXME - do not log for all errors.
-				errorIf(err, "Unable to write notification to client.")
+		case <-time.After(globalSNSConnAlive):
+			if err := writeNotification(w, emptyEvent); err != nil {
+				errorIf(err, "Unable to write empty notification")
+				close(l.doneCh)
```
Comment (donatello) [inline cmd/bucket-notification-handlers.go]: The close statement can be factored out from both cases and made into a defer statement at the beginning of the function.

**Review by donatello — DISMISSED** [review]
LGTM - suggesting minor changes.

**Comment by deekoder** [comment]
can reviewers also examine code coverage failures?

File: cmd/bucket-notification-handlers.go (hunk 6 above)
Comment (harshavardhana) [reply cmd/bucket-notification-handlers.go]: You need "Records" otherwise the client unmarshal will fail. @donatello

File: cmd/bucket-notification-handlers.go [hunk 8]
```diff
@@ -226,25 +218,51 @@ func writeNotification(w http.ResponseWriter, notification map[string][]Notifica
...
+		dataCh: make(chan []NotificationEvent),
+	}
+}
+
+// sendNotificationEvent sends notification events on the data channel
+// until doneCh is not closed
+func (l *listenChan) sendNotificationEvent(events []NotificationEvent) {
+	select {
+	// Returns immediately if receiver has quit.
+	case <-l.doneCh:
```
Comment (harshavardhana) [inline cmd/bucket-notification-handlers.go]: We can add a test case for `doneCh` here.

File: cmd/bucket-notification-handlers.go [hunk 9]
```diff
@@ -226,25 +218,51 @@ func writeNotification(w http.ResponseWriter, notification map[string][]Notifica
...
+				close(l.doneCh)
 				return
 			}
-		case <-time.After(globalSNSConnAlive): // Wait for global conn active seconds.
-			if err := writeNotification(w, dummyEvents); err != nil {
-				// FIXME - do not log for all errors.
-				errorIf(err, "Unable to write notification to client.")
+		case <-time.After(globalSNSConnAlive):
+			if err := writeNotification(w, emptyEvent); err != nil {
+				errorIf(err, "Unable to write empty notification")
```
Comment (harshavardhana) [inline cmd/bucket-notification-handlers.go]: Perhaps this log is not needed, most probably client actually died/disconnected here.. Its a good case of us.

**Review by harshavardhana — CHANGES_REQUESTED** [review]

File: cmd/bucket-notification-handlers.go (hunk 5 above)
Comment (krisis) [reply cmd/bucket-notification-handlers.go]: done

File: cmd/bucket-notification-handlers.go (hunk 7 above)
Comment (krisis) [reply cmd/bucket-notification-handlers.go]: done

File: cmd/bucket-notification-handlers.go (hunk 8 above)
Comment (krisis) [reply cmd/bucket-notification-handlers.go]: I have added a test case.

File: cmd/bucket-notification-handlers.go (hunk 9 above)
Comment (krisis) [reply cmd/bucket-notification-handlers.go]: This log captures failure of server to write to the client when it was writing empty notification events as opposed actual events like in the previous case statement. Both these error message indicate that the client has quit, but the different error messages allow us to uniquely identify the exact case.

Comment (harshavardhana) [reply cmd/bucket-notification-handlers.go]: Correct but client dead is a good case so we don't need to log that message, any other we can log.

Comment (krisis) [reply cmd/bucket-notification-handlers.go]: Both the error logs assume that any error during Write on http.ResponseWriter is due to client quitting ListenBucketNotification. Are you suggesting we should only log error values other than the `ECONNRESET` equivalent `net.OpError`?

Comment (harshavardhana) [reply cmd/bucket-notification-handlers.go]: Yes..any broken pipe. We can ignore where the connection is dead sort of.

**Comment by donatello** [comment]
This change LGTM but the build seems to be failing in Windows. Looks like some kind of file-lock related issue (unrelated to this change itself?).

**Comment by krisis** [comment]
@harshavardhana @donatello could you guys review again?

**Review by harshavardhana — APPROVED** [review]
LGTM tested and working.

File: cmd/server_test.go [hunk 10]
```diff
@@ -522,32 +522,6 @@ func (s *TestSuiteCommon) TestListenBucketNotificationHandler(c *check) {
 	if s.signer == signerV4 {
 		verifyError(c, response, "XAmzContentSHA256Mismatch", "The provided 'x-amz-content-sha256' header does not match what was computed.", http.StatusBadRequest)
 	}
-
-	// Change global value from 5 second to 100millisecond.
-	globalSNSConnAlive = 100 * time.Millisecond
-	req, err = newTestSignedRequest("GET",
```
Comment (harshavardhana) [inline cmd/server_test.go:528]: Why not leave this here for now? @krisis - this can be fixed when the Bala's refactor change is merged.

**Review by harshavardhana — CHANGES_REQUESTED** [review]

File: cmd/server_test.go (hunk 10 above)
Comment (krisis) [reply cmd/server_test.go:528]: It serves no purpose. It sends a http request to the listenBucketNotication handler and nothing else. So, there is never a bad time to remove it.

**Review by donatello — APPROVED** [review]

**Review by harshavardhana — APPROVED** [review]
