### PR TITLE
Check pool-index for invalid setups

### LINKED ISSUE #16500: MinIO crashed after metrics access
## NOTE

Minio crashed when detect some drives are swapped. Panic occurred after 1-2 minutes after start instance

```
Detected unexpected drive ordering refusing to use the drive - poolID: 1st, found drive mounted at ...
...
Detected unexpected drive ordering refusing to use the drive: ...
...
panic: runtime error: index out of range [-1]

goroutine 11668 [running]:
github.com/minio/minio/cmd.GetTotalUsableCapacity(...)
        /root/work/bigtop/build/minio/rpm/BUILD/minio-20221111034420/cmd/notification-summary.go:36
github.com/minio/minio/cmd.getClusterStorageMetrics.func1({0x5173fe0, 0xc0001deec0})
        /root/work/bigtop/build/minio/rpm/BUILD/minio-20221111034420/cmd/metrics-v2.go:2015 +0xeb0
github.com/minio/minio/cmd.(*MetricsGroup).RegisterRead.func1.1()
        /root/work/bigtop/build/minio/rpm/BUILD/minio-20221111034420/cmd/metrics-v2.go:253 +0x2b
github.com/minio/minio/cmd.(*timedValue).Get(0xc0012bf7a0)
        /root/work/bigtop/build/minio/rpm/BUILD/minio-20221111034420/cmd/utils.go:1056 +0x48
github.com/minio/minio/cmd.(*MetricsGroup).Get(0x28fb9c3?)
        /root/work/bigtop/build/minio/rpm/BUILD/minio-20221111034420/cmd/metrics-v2.go:283 +0x30
github.com/minio/minio/cmd.populateAndPublish({0xc001289720, 0x13, 0x166c080?}, 0xc01c69ffa8)
        /root/work/bigtop/build/minio/rpm/BUILD/minio-20221111034420/cmd/metrics-v2.go:2255 +0x66
github.com/minio/minio/cmd.ReportMetrics.func1()
        /root/work/bigtop/build/minio/rpm/BUILD/minio-20221111034420/cmd/metrics-v2.go:2220 +0x98
created by github.com/minio/minio/cmd.ReportMetrics
        /root/work/bigtop/build/minio/rpm/BUILD/minio-20221111034420/cmd/metrics-v2.go:2218 +0xeb
```

Possibly GetTotalUsableCapacity should ignore unrecognized drives

## Expected Behavior

should work

## Current Behavior

instance crashed

## Possible Solution

Ignore not assigned drives

## Steps to Reproduce (for bugs)

Swap two drives and restart minio

## Your Environment

* Version used (`minio --version`): from master
Latest Version: minio/minio:RELEASE.2023-01-25T00-19-54Z

minio version DEVELOPMENT.GOGET (commit-id=DEVELOPMENT.GOGET)
Runtime: go1.18.8 linux/amd64
License: GNU AGPLv3 <https://www.gnu.org/licenses/agpl-3.0.html>
Copyright: 2015-0000 MinIO, Inc.

* Server setup and configuration:
* Operating System and version (`uname -a`): centos7

### PR DESCRIPTION
**Pull request by klauspost**
## Description

Fixes #16500

## How to test this PR?

See #16500

## Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)

### CODE REVIEW

**Review by harshavardhana — APPROVED** [review]

**Review by harshavardhana — APPROVED** [review]

**Comment by minio-trusted** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-erasure.sh | :heavy_check_mark: |
| mint-dist-erasure.sh | :heavy_check_mark: |
| mint-compress-encrypt-dist-erasure.sh | :heavy_check_mark: |
| mint-pools.sh | :heavy_check_mark: |
Deleting image on docker hub
Deleting image locally

File: cmd/erasure-server-pool-rebalance.go [hunk 1]
```diff
@@ -133,6 +133,11 @@ func (z *erasureServerPools) initRebalanceMeta(ctx context.Context, buckets []st
 	}, len(z.serverPools))
 	var totalCap, totalFree uint64
 	for _, disk := range si.Disks {
+		// Ignore invalid.
+		if len(diskStats) <= disk.PoolIndex {
```
Comment (vadmeste) [inline cmd/erasure-server-pool-rebalance.go]: I don't think this will work:

we have 'unrecognizedDisk' which is used in place of regular xlStorage when there is an order issue. disk.PoolIndex will be -1 and len(diskStats) will never be less or equal to disk.PoolIndex.

I think what you need to do is check if disk.PoolIndex == -1  

But also add a new code here `cmd/erasure.go, line 190` to return `pool, set, disk = -1, -1, -1` (you will understand why)

**Review by vadmeste — CHANGES_REQUESTED** [review]
One comment

File: cmd/erasure-server-pool-rebalance.go (hunk 1 above)
Comment (klauspost) [reply cmd/erasure-server-pool-rebalance.go]: Adding as secondary measure 👍🏼

**Comment by minio-trusted** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-erasure.sh | :heavy_check_mark: |
| mint-dist-erasure.sh | :heavy_check_mark: |
| mint-compress-encrypt-dist-erasure.sh | :heavy_check_mark: |
| mint-pools.sh | :heavy_check_mark: |
Deleting image on docker hub
Deleting image locally

**Review by harshavardhana — APPROVED** [review]

**Review by vadmeste — APPROVED** [review]
LGTM
