### PR TITLE
use acceptedResponseStatusCode everywhere in HTTP logger

### LINKED ISSUE #13754: Incorrect error message thrown during audit publishing
Setup an audit webhook with elasticsearch endpoint and notice there is a incorrect error message every time there is an audit published. 

API: SYSTEM()
Time: 19:39:49 UTC 11/24/2021
DeploymentID: 599cc902-b1ae-480a-9ee6-63b3ca639d83
Error: http://<elastic:9200>/ returned '201 Created', please check your endpoint configuration (*errors.errorString)
       3: internal/logger/logonce.go:54:logger.(*logOnceType).logOnceIf()
       2: internal/logger/logonce.go:94:logger.LogOnceIf()
       1: internal/logger/target/http/http.go:165:http.(*Target).startHTTPLogger.func1()

https://github.com/minio/minio/blob/master/internal/logger/target/http/http.go#L160 is only accepting 200 as valid status code. It should be accepting all 2xx status codes as success.

## Expected Behavior

No error message thrown every time an audit message is published

## Current Behavior

Incorrect error message is thrown, like below,

API: SYSTEM()
Time: 19:39:49 UTC 11/24/2021
DeploymentID: 599cc902-b1ae-480a-9ee6-63b3ca639d83
Error: http://<elastic:9200>/ returned '201 Created', please check your endpoint configuration (*errors.errorString)
       3: internal/logger/logonce.go:54:logger.(*logOnceType).logOnceIf()
       2: internal/logger/logonce.go:94:logger.LogOnceIf()
       1: internal/logger/target/http/http.go:165:http.(*Target).startHTTPLogger.func1()

## Possible Solution

Accept all 2xx codes
## Steps to Reproduce (for bugs)

1. Setup an elasticsearch cluster
2. Configure an audit webhook to it
3. Do MinIO operations using mc binary, like mc mb etc.,
4. Notice the incorrect error message thrown in the logs

## Your Environment

* Version used (`minio --version`):
* Server setup and configuration:
* Operating System and version (`uname -a`):
minio/minio:RELEASE.2021-11-03T03-36-36Z

### PR DESCRIPTION
**Pull request by harshavardhana**
## Description
use acceptedResponseStatusCode everywhere in HTTP logger

## Motivation and Context
fixes #13754 

## How to test this PR?
As per #13754 

## Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Optimization (provides speedup with no functional changes)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [ ] Fixes a regression (If yes, please add `commit-id` or `PR #` here)
- [ ] Documentation updated
- [ ] Unit tests added/updated

### CODE REVIEW

File: buildscripts/minio-upgrade.sh [hunk 1]
```diff
@@ -37,8 +37,11 @@ verify_checksum_mc() {
...
 
 add_alias() {
-    until (mc alias set minio http://127.0.0.1:9000 minioadmin minioadmin); do
-        echo "...waiting... for 5secs" && sleep 5
+    for i in $(seq 1 4); do
+        echo "... attempting to add alias $i"
+        until (mc alias set minio http://127.0.0.1:9000 minioadmin minioadmin); do
+            echo "...waiting... for 5secs" && sleep 5
+        done
     done
```
Comment (harshavardhana) [inline buildscripts/minio-upgrade.sh:45]: This is on purpose attempting to 'add' alias "successfully" 4 times for 4 servers.

**Review by donatello — APPROVED** [review]

**Review by krisis — APPROVED** [review]
