### PR TITLE
fs mode: List already existing buckets with capital letters

### LINKED ISSUE #6938: Objects in buckets with capitalized names can be listed with AWS cli, but not with mc
## Expected Behavior

Minio should consistently provide, or consistently not provide, access to buckets with invalid names (e.g. containing capital letters).

Note this may be somehow related to running on case-insensitive (but case-preserving) APFS, or to running on macOS.

## Current Behavior

`mc` doesn't list buckets with capitalized names, or their contents, but Minio does expose them to `aws cli`, at least when listing the bucket contents.

## Possible Solution

- preferred: go ahead and expose invalid bucket names in all cases, just don't let people create them
- less optimal: figure out what's different between `list-buckets` and `list-objects`, and make sure Minio doesn't expose invalid bucket names to AWS in the `list-buckets` operation

## Steps to Reproduce (for bugs)

1. Create the following directory tree, where the leaf nodes are files.

   ```
   foo
   ├── Bar
   │   └── baz
   └── qux
       └── quux
   ```

   E.g.,

   ```
   $ mkdir foo
   $ mkdir foo/Bar        # capital letter, not a valid bucket name
   $ touch foo/Bar/baz
   $ mkdir foo/qux
   $ touch foo/qux/quux
   ```

2. Start a Minio server against the specified directory.

   ```
   $ MINIO_ACCESS_KEY=123 MINIO_SECRET_KEY=abcdefgh minio server foo
   ```

3. Add the new server to the `mc` client configuration.

   ```
   mc config host add foo http://127.0.0.1:9000 123 abcdefgh
   ```

4. List the available buckets with both `mc` and `aws s3`:

   ```
   $ mc ls foo
   [2018-12-07 11:28:48 PST]     0B qux/
   $ AWS_ACCESS_KEY_ID=123 AWS_SECRET_ACCESS_KEY=abcdefgh aws --endpoint-url http://localhost:9000 s3 ls
   2018-12-07 11:28:48 qux
   ```

   Note that the bucket with the capital letter is not listed by either client.

5. Attempt to list the bucket with the invalid name, using both `mc` and `aws s3`:

   ```
   $ mc ls foo/Bar        # appears to be empty
   $ AWS_ACCESS_KEY_ID=123 AWS_SECRET_ACCESS_KEY=abcdefgh aws --endpoint-url http://localhost:9000 s3 ls Bar
   2018-12-07 11:28:29          0 baz
   ```

   Note that `mc` appears unable to list the bucket contents, but `aws s3` can.

## Context

Trying to use Minio to provide access to an existing directory, which has capitalized subdirectories. As a workaround, I've created a separate "minio" directory, with an all-lower-case symlink to the original directory, which lets me treat the directory as a single bucket. (Subdirectories with capital letters, spaces, etc. appear to be fine.) Not ideal for all cases, but works for this one.

## Your Environment

* Version used (`minio version`):

   Version: 2018-12-06T01:27:43Z
   Release-Tag: RELEASE.2018-12-06T01-27-43Z
   Commit-ID: 40852801ea63d0e10f220c0d7d2a8d6a8efa5688

* Operating System and version (`uname -a`):

  ```
  Darwin Anachronic.local 18.2.0 Darwin Kernel Version 18.2.0: Fri Oct  5 19:41:49 PDT 2018; root:xnu-4903.221.2~2/RELEASE_X86_64 x86_64
  ```

  (Mac OS X 10.14.1)

* Filesystem: APFS (case-insensitive)

### PR DESCRIPTION
**Pull request by kannappanr**
## Description
if a bucket with `Captialized letters` is created, `InvalidBucketName` error
will be returned. In the case of pre-existing buckets,
it will be listed.

Fixes #6938

## Motivation and Context
Issue #6938

## Regression
No

## How Has This Been Tested?
Start minio in fs mode, with a data directory that has two directories
The first one called `AAAAA`, the second one called `sample`

Without this PR, if you use `mc ls myminio`, the bucket with name containing capital letters will not be listed.
With this fix, it will be listed.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added unit tests to cover my changes.
- [ ] I have added/updated functional tests in [mint](https://github.com/minio/mint). (If yes, add `mint` PR # here: )
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by minio-ops** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-compression-xl.sh | :heavy_check_mark: |
| mint-xl.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-compression-dist-xl.sh | :heavy_check_mark: |
| mint-compression-fs.sh | :heavy_check_mark: |
| mint-worm.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-dist-xl.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |

**Comment by harshavardhana** [comment]
@kannappanr PR itself is fine but we should allow only capitalized bucket names

> --- FAIL: TestFSListBuckets (0.01s)
    fs-v1_test.go:375: ListBuckets not working properly [{bucket 2019-02-14 00:25:16.700966475 +0000 UTC} {vo^ 2019-02-14 00:25:16.700966475 +0000 UTC}]

Lets actually use the `github.com/minio/minio/pkg/s3utils` for this validation? 

```
// CheckValidBucketName - checks if we have a valid input bucket name.
func CheckValidBucketName(bucketName string) (err error) {
        return checkBucketNameCommon(bucketName, false)
}

// CheckValidBucketNameStrict - checks if we have a valid input bucket name.
// This is a stricter version.
// - http://docs.aws.amazon.com/AmazonS3/latest/dev/UsingBucket.html
func CheckValidBucketNameStrict(bucketName string) (err error) {
        return checkBucketNameCommon(bucketName, true)
}
```

**Comment by minio-ops** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-compression-xl.sh | :heavy_check_mark: |
| mint-xl.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-compression-dist-xl.sh | :heavy_check_mark: |
| mint-compression-fs.sh | :heavy_check_mark: |
| mint-worm.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-dist-xl.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |

**Review by harshavardhana — APPROVED** [review]
LGTM & tested

**Comment by minio-ops** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-compression-xl.sh | :heavy_check_mark: |
| mint-xl.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-compression-fs.sh | :heavy_check_mark: |
| mint-worm.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-compression-dist-xl.sh | :x: [more...](#742c9745-0ca6-4a4c-a072-4d6f672f5fc2) |
| mint-fs.sh | :x: [more...](#0cf377c6-250b-469c-bc19-9be16bfb61d0) |
| mint-dist-xl.sh | :x: [more...](#b084662e-44eb-4078-bcff-62108692ddb8) |
<a name="b084662e-44eb-4078-bcff-62108692ddb8"></a>
### 7244-1aa2ed4/mint-dist-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.54:30971
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp b8e22a007567:/mint/log /tmp/mint-logs'

(1/13) Running aws-sdk-go tests ... FAILED in 0 seconds
{
  "alert": "",
  "args": {
    "bucketName": "aws-sdk-go-test-ev4fkxrso604l5",
    "expiry": 60000000000,
    "objectName": "presignedTest"
  },
  "duration": 369,
  "error": "RequestError: send request failed\ncaused by: Put http://72.28.97.54:30971/aws-sdk-go-test-ev4fkxrso604l5: dial tcp 72.28.97.54:30971: connect: connection refused",
  "function": "PresignedPut",
  "message": "AWS SDK Go CreateBucket Failed",
  "name": "aws-sdk-go",
  "status": "FAIL"
}

Executed 0 out of 13 tests successfully.
```
<a name="0cf377c6-250b-469c-bc19-9be16bfb61d0"></a>
### 7244-1aa2ed4/mint-fs.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.61:30065
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp ad469a355322:/mint/log /tmp/mint-logs'

(1/13) Running aws-sdk-go tests ... FAILED in 0 seconds
{
  "alert": "",
  "args": {
    "bucketName": "aws-sdk-go-test-6nftzsnk1wlnr5",
    "expiry": 60000000000,
    "objectName": "presignedTest"
  },
  "duration": 284,
  "error": "RequestError: send request failed\ncaused by: Put http://72.28.97.61:30065/aws-sdk-go-test-6nftzsnk1wlnr5: dial tcp 72.28.97.61:30065: connect: connection refused",
  "function": "PresignedPut",
  "message": "AWS SDK Go CreateBucket Failed",
  "name": "aws-sdk-go",
  "status": "FAIL"
}

Executed 0 out of 13 tests successfully.
```
<a name="742c9745-0ca6-4a4c-a072-4d6f672f5fc2"></a>
### 7244-1aa2ed4/mint-compression-dist-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.55:32011
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 04b23e6330a1:/mint/log /tmp/mint-logs'

(1/13) Running aws-sdk-go tests ... FAILED in 1 seconds
{
  "alert": "",
  "args": {
    "bucketName": "aws-sdk-go-test-vazms09lf2td9i",
    "expiry": 60000000000,
    "objectName": "presignedTest"
  },
  "duration": 296,
  "error": "RequestError: send request failed\ncaused by: Put http://72.28.97.55:32011/aws-sdk-go-test-vazms09lf2td9i: dial tcp 72.28.97.55:32011: connect: connection refused",
  "function": "PresignedPut",
  "message": "AWS SDK Go CreateBucket Failed",
  "name": "aws-sdk-go",
  "status": "FAIL"
}

Executed 0 out of 13 tests successfully.
```

File: cmd/fs-v1.go [hunk 1]
```diff
@@ -289,9 +290,8 @@ func (fs *FSObjects) MakeBucketWithLocation(ctx context.Context, bucket, locatio
 	}
 	defer bucketLock.Unlock()
 	// Verify if bucket is valid.
-	if !IsValidBucketName(bucket) {
-		err := BucketNameInvalid{Bucket: bucket}
-		logger.LogIf(ctx, err)
+	if err := s3utils.CheckValidBucketNameStrict(bucket); err != nil {
+		err = BucketNameInvalid{Bucket: bucket}
```
Comment (ebozduman) [inline cmd/fs-v1.go]: Why not => `return BucketNameInvalid{Bucket: bucket}` and get rid of `err`?

File: cmd/xl-v1-bucket.go [hunk 2]
```diff
@@ -178,7 +178,7 @@ func (xl xlObjects) listBuckets(ctx context.Context) (bucketsInfo []BucketInfo,
 			// should take care of this.
 			var bucketsInfo []BucketInfo
 			for _, volInfo := range volsInfo {
-				if isReservedOrInvalidBucket(volInfo.Name) {
+				if isReservedOrInvalidBucket(volInfo.Name, true) {
```
Comment (ebozduman) [inline cmd/xl-v1-bucket.go:181]: There is no need to do strict name check here. 
Checking reserved word for listing buckets is good enough..

**Review by ebozduman — CHANGES_REQUESTED** [review]

**Review by ebozduman — CHANGES_REQUESTED** [review]
When I search with `func \(.*\).*MakeBucket`, I see bunch of places we do `!IsValidBucketName` checks.
Do we want  to replace them with s3utils...?

File: cmd/xl-v1-bucket.go (hunk 2 above)
Comment (kannappanr) [reply cmd/xl-v1-bucket.go:181]: If someone changes the bucket names in the backend to have invalid names, even though they are not supposed to touch the backend, then this will not list those buckets. So, this code does not change the existing behavior.

File: cmd/fs-v1.go (hunk 1 above)
Comment (kannappanr) [reply cmd/fs-v1.go]: done

**Review by harshavardhana — DISMISSED** [review]

**Comment by minio-ops** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-compression-xl.sh | :heavy_check_mark: |
| mint-xl.sh | :heavy_check_mark: |
| mint-compression-fs.sh | :heavy_check_mark: |
| mint-worm.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :x: [more...](#8a612008-1cfe-44ac-8041-1c5131291b58) |
| mint-compression-dist-xl.sh | :x: [more...](#464a483c-c20e-4cef-af19-545e5c2b37a1) |
| mint-dist-xl.sh | :x: [more...](#63f03135-fdda-4a1f-92d5-2dbdec4a62cb) |
<a name="464a483c-c20e-4cef-af19-545e5c2b37a1"></a>
### 7244-2c727e0/mint-compression-dist-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.61:31848
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 72429b0b991b:/mint/log /tmp/mint-logs'

(1/13) Running aws-sdk-go tests ... FAILED in 0 seconds
{
  "alert": "",
  "args": {
    "bucketName": "aws-sdk-go-test-qnnotu30qyuny5",
    "expiry": 60000000000,
    "objectName": "presignedTest"
  },
  "duration": 271,
  "error": "RequestError: send request failed\ncaused by: Put http://72.28.97.61:31848/aws-sdk-go-test-qnnotu30qyuny5: dial tcp 72.28.97.61:31848: connect: connection refused",
  "function": "PresignedPut",
  "message": "AWS SDK Go CreateBucket Failed",
  "name": "aws-sdk-go",
  "status": "FAIL"
}

Executed 0 out of 13 tests successfully.
```
<a name="63f03135-fdda-4a1f-92d5-2dbdec4a62cb"></a>
### 7244-2c727e0/mint-dist-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.56:30625
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 96e1f05687eb:/mint/log /tmp/mint-logs'

(1/13) Running aws-sdk-go tests ... FAILED in 0 seconds
{
  "alert": "",
  "args": {
    "bucketName": "aws-sdk-go-test-uaxjvge9ddccab",
    "expiry": 60000000000,
    "objectName": "presignedTest"
  },
  "duration": 312,
  "error": "RequestError: send request failed\ncaused by: Put http://72.28.97.56:30625/aws-sdk-go-test-uaxjvge9ddccab: dial tcp 72.28.97.56:30625: connect: connection refused",
  "function": "PresignedPut",
  "message": "AWS SDK Go CreateBucket Failed",
  "name": "aws-sdk-go",
  "status": "FAIL"
}

Executed 0 out of 13 tests successfully.
```
<a name="8a612008-1cfe-44ac-8041-1c5131291b58"></a>
### 7244-2c727e0/mint-large-bucket.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.52:31471
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp b17d58ae5404:/mint/log /tmp/mint-logs'

(1/13) Running aws-sdk-go tests ... FAILED in 6 minutes and 0 seconds
{
  "alert": "",
  "args": {
    "bucketName": "aws-sdk-go-test-bj23pklyrogrsh",
    "expiry": 60000000000,
    "objectName": "presignedTest"
  },
  "duration": 360015,
  "error": "XMinioServerNotInitialized: Server not initialized, please try again.\n\tstatus code: 503, request id: 1587E77ED8F17633, host id: ",
  "function": "PresignedPut",
  "message": "AWS SDK Go CreateBucket Failed",
  "name": "aws-sdk-go",
  "status": "FAIL"
}

Executed 0 out of 13 tests successfully.
```

**Comment by kannappanr** [comment]
> When I search with `func \(.*\).*MakeBucket`, I see bunch of places we do `!IsValidBucketName` checks.
> Do we want to replace them with s3utils...?

There were only a couple of places that used `isValidBucketName`, I have modified it in `oss gateway` and in the case of `Azure`, there was a comment about why `IsValidBucketName` should be used, so I have left it as is.

**Comment by minio-ops** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-compression-xl.sh | :heavy_check_mark: |
| mint-xl.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-compression-dist-xl.sh | :heavy_check_mark: |
| mint-compression-fs.sh | :heavy_check_mark: |
| mint-worm.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-dist-xl.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |

**Review by harshavardhana — APPROVED** [review]
LGTM & tested

**Review by ebozduman — APPROVED** [review]
LGTM
