### PR TITLE
browser: Send correct arguments for RemoveObjects web handler.

### LINKED ISSUE #3839: Deleting file from bucket does not work from webUI, works fine in minioc
I have upgraded minioc to current version from master on OpenBSD6.0/amd64, golang 1.7.5

Version: 2017-03-03T08:17:24Z
Release-Tag: DEVELOPMENT.2017-03-03T08-17-24Z
Commit-ID: 98d17d2a97e6db184a6b86104624610dfe124d17

## Expected Behavior
Delete should work in webui too.

## Current Behavior
Clicking on delete button on object shows red "We encountered an internal error, please try again." Trying again does not help. delete works using current minioc.

Console log says:
ERRO[1199] Unexpected error, please report this issue at https://github.com/minio/minio/issues  cause=Unexpected error, please report this issue at https://github.com/minio/minio/issues source=[web-handlers.go:994:toWebAPIError()]

## Steps to Reproduce (for bugs)

1. just try to delete an item, even at bucket level. Haven't tried with folders ...
2.
3.
4.

## Your Environment
Version: 2017-03-03T08:17:24Z
Release-Tag: DEVELOPMENT.2017-03-03T08-17-24Z
Commit-ID: 98d17d2a97e6db184a6b86104624610dfe124d17

* Version used:DEVELOPMENT.2017-03-03T08-17-24Z
* Environment name and version (e.g. nginx 1.9.1): 
* Operating System and version: OpenBSD6.0/amd64

### PR DESCRIPTION
**Pull request by krishnasrinivas**
## Description

Deleting file from bucket does not work from webUI

## Motivation and Context

Fixes #3839

## How Has This Been Tested?

manual and go test

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

File: cmd/web-handlers.go [hunk 1]
```diff
@@ -293,8 +293,8 @@ objectLoop:
 			return err
 		}
 		if !hasSuffix(object, slashSeparator) {
-			// If not a directory, compress the file and write it to response.
-			err = remove(pathJoin(args.Prefix, object))
```
Comment (harshavardhana) [inline cmd/web-handlers.go:297]: Can you add a test case for this change/bug?

**Review by harshavardhana — CHANGES_REQUESTED** [review]

File: cmd/web-handlers.go (hunk 1 above)
Comment (krishnasrinivas) [reply cmd/web-handlers.go:297]: test case was already there, but the browser code also needed. i had assumed rushenn would do multi-delete before a release is made which did not happen. i have made the browser changes now.

Comment (harshavardhana) [reply cmd/web-handlers.go:297]: Okay

**Review by harshavardhana — APPROVED** [review]
