### PR TITLE
do not remove Sid from svcaccount policies

### LINKED ISSUE #13905: IAM Policies do not keep Sid
According to the documentation "MinIO policy documents use the same schema as AWS IAM Policy documents."

But **IAM Policies** and **Service Account Policies** remove Sid field from the given json and don't store it. **(Note that Bucket policies keep Sid field)**

Sid is really useful when it comes to controlling policies programmatically. otherwise, you have to loop through all statements and have some special checks to find your desired statement to update.

## Expected Behavior
Keep Sid field in **IAM Policies** and **Service Account policies**

## Current Behavior
Sid field gets removed.

## Steps to Reproduce (for bugs)
- Suppose you have this policy.json
```
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Sid": "AddSomeRestrictions",
            "Effect": "Deny",
            "Action": [
                "s3:GetObject"
            ],
            "Resource": [
                "arn:aws:s3:::public-bucket/private.txt*",
                "arn:aws:s3:::public-bucket/private2.txt*"
            ]
        }
    ]
}
```
- Run `mc admin policy add local newpolicy policy.json`
- Run `mc admin policy info local newpolicy`
- You should see that Sid is removed
- The same thing happens for Service Account policies

## Your Environment
* Version used (`minio --version`): RELEASE.2021-12-10T23-03-39Z

### PR DESCRIPTION
**Pull request by harshavardhana**
## Description
do not remove Sid from svcaccount policies

## Motivation and Context
fixes #13905

## How to test this PR?
As per #13905

## Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Optimization (provides speedup with no functional changes)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [ ] Fixes a regression (If yes, please add `commit-id` or `PR #` here)
- [ ] Documentation updated
- [ ] Unit tests added/updated

### CODE REVIEW

**Comment by minio-trusted** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-s3.sh | :heavy_check_mark: |
| mint-erasure.sh | :heavy_check_mark: |
| mint-dist-erasure.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-compress-encrypt-dist-erasure.sh | :heavy_check_mark: |
| mint-pools.sh | :heavy_check_mark: |
Deleting image on docker hub
Deleting image locally

**Comment by minio-trusted** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-s3.sh | :heavy_check_mark: |
| mint-erasure.sh | :heavy_check_mark: |
| mint-dist-erasure.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-compress-encrypt-dist-erasure.sh | :heavy_check_mark: |
| mint-pools.sh | :heavy_check_mark: |
Deleting image on docker hub
Deleting image locally

**Comment by minio-trusted** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-s3.sh | :heavy_check_mark: |
| mint-erasure.sh | :heavy_check_mark: |
| mint-dist-erasure.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-compress-encrypt-dist-erasure.sh | :heavy_check_mark: |
| mint-pools.sh | :heavy_check_mark: |
Deleting image on docker hub
Deleting image locally

**Comment by minio-trusted** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-s3.sh | :heavy_check_mark: |
| mint-erasure.sh | :heavy_check_mark: |
| mint-dist-erasure.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-compress-encrypt-dist-erasure.sh | :heavy_check_mark: |
| mint-pools.sh | :heavy_check_mark: |
Deleting image on docker hub
Deleting image locally

File: cmd/iam-store.go [hunk 1]
```diff
@@ -1511,13 +1512,16 @@ func (store *IAMStoreSys) AddServiceAccount(ctx context.Context, cred auth.Crede
 	// Found newly requested service account, to be an existing account -
 	// reject such operation (updates to the service account are handled in
 	// a different API).
-	if _, found := cache.iamUsersMap[accessKey]; found {
-		return errIAMActionNotAllowed
+	if scred, found := cache.iamUsersMap[accessKey]; found {
+		if scred.ParentUser != parentUser {
```
Comment (vadmeste) [inline cmd/iam-store.go:1516]: If I understood correctly we should not have this. cred.AccessKey will be the access key  of the service account and we cannot have it duplicated

**Review by vadmeste — COMMENTED** [review]
One comment

File: cmd/iam-store.go (hunk 1 above)
Comment (harshavardhana) [reply cmd/iam-store.go:1516]: Well this is because someone can ask to create same service account with different parent user. This is to reject and send valid errors.

**Comment by harshavardhana** [comment]
PTAL @vadmeste @donatello

**Review by vadmeste — APPROVED** [review]
LGTM

**Review by donatello — APPROVED** [review]
