### PR TITLE
Sid value can be any unicode character support it

### LINKED ISSUE #6476: Can not set bucket policy via JS API
Minio JavaScript API SDK constantly throws errors when trying to set bucket policy.
```javascript
const Minio = require('minio');

var minioClient = new Minio.Client({
    endPoint: 'localhost',
    port: 9000,
    useSSL: false,
    accessKey: 'AIOUR3892NG79230GN832AKHP',
    secretKey: 'HL8sllkjdsf83mvKda30fnldl3rho',
});

const policy = {
    Version: '2018-09-15',
    Id: 'test-policy-1',
    Statement: [
        {
            Action: ['s3:GetObject'],
            Effect: 'Allow',
            Principal: {
                AWS: ['*'],
            },
            Resource: ['arn:aws:s3:::nextbucket/*'],
        },
    ],
};

minioClient.makeBucket('nextbucket', 'region-1', function(err) {
    if (err) return console.log('Error creating bucket.', err);

    console.log('Bucket created successfully in "region-1".');

    minioClient.setBucketPolicy('nextbucket', JSON.stringify(policy), function(err) {
        if (err) throw err;
        console.log('Bucket policy set');
    });
});

```

## Expected Behavior
The code above should make a new bucket and set anonymous access policy to it.

## Current Behavior
The code above successfully creates a new bucket but fails to set policy with the following error:
```javascript
S3Error: Policy has invalid resource.
    at Object.parseError (.../minio-js/node_modules/minio/dist/main/xml-parsers.js:86:11)
    at .../minio-js/node_modules/minio/dist/main/transformers.js:159:22
    at DestroyableTransform._flush (.../minio-js/node_modules/minio/dist/main/transformers.js:89:10)
    at DestroyableTransform.<anonymous> (.../minio-js/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:135:12)
    at Object.onceWrapper (events.js:313:30)
    at emitNone (events.js:111:20)
    at DestroyableTransform.emit (events.js:208:7)
    at finishMaybe (.../minio-js/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:371:12)
    at endWritable (.../minio-js/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:378:3)
    at DestroyableTransform.Writable.end (.../minio-js/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:356:5)
```

## Steps to Reproduce (for bugs)

1. Install and run latest mini via docker
2. Setup js app environment
3. Run the code above

## Your Environment

* Version used (`minio version`):
* Environment name and version (e.g. nginx 1.9.1):
* Server type and version:
* Operating System and version (`uname -a`):
* Link to your project:

### PR DESCRIPTION
**Pull request by harshavardhana**
## Description
Sid value can be any Unicode character support it

## Motivation and Context
Fixes #6476

## Regression
No

## How Has This Been Tested?
Using the following policy against Minio and AWS S3, in master Minio would fail with invalid policy document error.

```json
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Sid": "¶s",
            "Effect": "Allow",
            "Principal": {
                "AWS": "*"
            },
            "Action": [
                "s3:GetBucketLocation",
                "s3:ListBucket",
                "s3:ListBucketMultipartUploads"
            ],
            "Resource": "arn:aws:s3:::vadmeste"
        },
        {
            "Sid": "",
            "Effect": "Allow",
            "Principal": {
                "AWS": "*"
            },
            "Action": "s3:ListBucket",
            "Resource": "arn:aws:s3:::vadmeste",
            "Condition": {
                "StringEquals": {
                    "s3:prefix": "prefix/"
                }
            }
        },
        {
            "Sid": "",
            "Effect": "Allow",
            "Principal": {
                "AWS": "*"
            },
            "Action": [
                "s3:AbortMultipartUpload",
                "s3:DeleteObject",
                "s3:GetObject",
                "s3:ListMultipartUploadParts",
                "s3:PutObject"
            ],
            "Resource": "arn:aws:s3:::vadmeste/prefix/*"
        },
        {
            "Sid": "",
            "Effect": "Allow",
            "Principal": {
                "AWS": "*"
            },
            "Action": "s3:GetObject",
            "Resource": "arn:aws:s3:::vadmeste/*"
        }
    ]
}
```

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have added unit tests to cover my changes.
- [ ] I have added/updated functional tests in [mint](https://github.com/minio/mint). (If yes, add `mint` PR # here: )
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by minio-ops** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-tls.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-worm.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-dist-xl.sh | :heavy_check_mark: |
| mint-xl.sh | :x: [more...](#8b392b9a-2bdc-491b-a24d-1e1fceedd5f1) |
<a name="8b392b9a-2bdc-491b-a24d-1e1fceedd5f1"></a>
### 6676-6b598ff/mint-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      minikube:30464
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp fee6fafeb188:/mint/log /tmp/mint-logs'
(1/13) Running awscli tests ... done in 1 minutes and 11 seconds
(2/13) Running aws-sdk-go tests ... done in 0 seconds
(3/13) Running aws-sdk-java tests ... done in 6 seconds
(4/13) Running aws-sdk-php tests ... done in 41 seconds
(5/13) Running aws-sdk-ruby tests ... done in 5 seconds
(6/13) Running mc tests ... done in 31 seconds
(7/13) Running minio-dotnet tests ... done in 2 minutes and 43 seconds
(8/13) Running minio-go tests ... done in 54 seconds
(9/13) Running minio-java tests ... done in 1 minutes and 58 seconds
(10/13) Running minio-js tests ... FAILED in 1 seconds
{
  "name": "minio-js",
  "function": "putObject(bucketName, objectName, stream, cb)",
  "args": "bucketName:minio-js-test-e8c49114-fe4c-4026-b2f7-8a24f2346569, objectName:datafile-6-MB",
  "duration": 58,
  "status": "FAIL",
  "error": "Error: read ECONNRESET at exports._errnoException (util.js:1020:11) at TCP.onread (net.js:580:26)"
}

Executed 9 out of 13 tests successfully.
```

**Review by nitisht — DISMISSED** [review]
LGTM & Tested

**Comment by harshavardhana** [comment]
ping @balamurugana can you review?

File: pkg/policy/id.go [hunk 1]
```diff
@@ -34,7 +32,7 @@ func (id ID) IsValid() bool {
 		return true
 	}
 
-	return idRegexp.MatchString(string(id))
+	return utf8.ValidString(string(id))
```
Comment (balamurugana) [inline pkg/policy/id.go:30]: According to https://docs.aws.amazon.com/AmazonS3/latest/dev/example-bucket-policies.html, `ID`  can be any arbitrary string.  This function needs to be just one liner `return utf8.ValidString(string(id))`

File: pkg/policy/id_test.go [hunk 2]
```diff
@@ -29,13 +29,15 @@ func TestIDIsValid(t *testing.T) {
 	}{
 		{ID("DenyEncryptionSt1"), true},
 		{ID(""), true},
+		{ID("abc-test"), true},
+		{ID("abc test"), true},
```
Comment (balamurugana) [inline pkg/policy/id_test.go]: These tests are not useful according to https://docs.aws.amazon.com/AmazonS3/latest/dev/example-bucket-policies.html.  Only three cases like empty string, non-empty string and non-utf8 string are good enough.

File: pkg/policy/id_test.go [hunk 3]
```diff
@@ -29,13 +29,15 @@ func TestIDIsValid(t *testing.T) {
...
 	}
 
 	for i, testCase := range testCases {
 		result := testCase.id.IsValid()
 
 		if result != testCase.expectedResult {
-			t.Fatalf("case %v: result: expected: %v, got: %v\n", i+1, testCase.expectedResult, result)
+			t.Errorf("case %v: result: expected: %v, got: %v\n", i+1, testCase.expectedResult, result)
```
Comment (balamurugana) [inline pkg/policy/id_test.go:39]: Failing early is better than unnoticed `t.Errorf()`

File: pkg/policy/id_test.go [hunk 4]
```diff
@@ -77,8 +81,8 @@ func TestIDUnmarshalJSON(t *testing.T) {
 		{[]byte(`"foo"`), ID("foo"), false},
 		{[]byte(`"1234"`), ID("1234"), false},
 		{[]byte(`"DenyEncryptionSt1"`), ID("DenyEncryptionSt1"), false},
+		{[]byte(`"foo bar"`), ID("foo bar"), false},
```
Comment (balamurugana) [inline pkg/policy/id_test.go]: Same as above

File: pkg/policy/id_test.go (hunk 3 above)
Comment (harshavardhana) [reply pkg/policy/id_test.go:39]: It's not unnoticed @balamurugana t.Errorf() simply continues to next test case. t.Fatalf is not correct.

File: pkg/policy/id_test.go (hunk 4 above)
Comment (harshavardhana) [reply pkg/policy/id_test.go]: It's not unnoticed @balamurugana t.Errorf() simply continues to next test case. t.Fatalf is not correct.

Comment (harshavardhana) [reply pkg/policy/id_test.go]: t.Errorf is also the most common used in tabled test cases for you to see all tests cases failing, there is no reason for us to fail only one test. We have no state or relation between test cases.

File: pkg/policy/id.go (hunk 1 above)
Comment (harshavardhana) [reply pkg/policy/id.go:30]: okay

File: pkg/policy/id_test.go (hunk 4 above)
Comment (balamurugana) [reply pkg/policy/id_test.go]: Unable to understand.  Do you say `t.Errorf()` triggers aborting test function if any `t.Errorf()` occurred after completing all test cases? 
If not `t.Fatal()` is better which stops immediately on first failure.  So that its easy to look and fix when `make test` is run manually or in travis-ci; else a good amount of search is required.

Comment (harshavardhana) [reply pkg/policy/id_test.go]: > Do you say t.Errorf() triggers aborting test function if any t.Errorf() occurred after completing all test cases?

Yes definitely.   t.Errorf is the most commonly used in a scenario where you are simply validating a bunch of tests, t.Fatalf is only used when you don't want the test to continue further like when you want some code to stop immediately. There is of course use of t.Fatalif in certain cases - but not in this case. 

One such example to look at https://golang.org/src/unicode/utf8/utf8_test.go

Comment (balamurugana) [reply pkg/policy/id_test.go]: Personally I prefer fast failure to know the issue immediately than later.  With this tiny test cases it might look OK but I wouldn't do.

File: pkg/policy/id_test.go [hunk 5]
```diff
@@ -29,13 +29,14 @@ func TestIDIsValid(t *testing.T) {
 	}{
 		{ID("DenyEncryptionSt1"), true},
 		{ID(""), true},
+		{ID("aa\xe2"), false},
```
Comment (balamurugana) [inline pkg/policy/id_test.go:32]: These cases also apply to `Marshal()` and `Unmarshal()` i.e. need to have only three cases.

**Comment by minio-ops** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-tls.sh | :heavy_check_mark: |
| mint-xl.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-worm.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-dist-xl.sh | :heavy_check_mark: |

**Comment by minio-ops** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-tls.sh | :heavy_check_mark: |
| mint-xl.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-worm.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-dist-xl.sh | :heavy_check_mark: |

File: pkg/policy/id_test.go (hunk 5 above)
Comment (harshavardhana) [reply pkg/policy/id_test.go:32]: Will do

Comment (harshavardhana) [reply pkg/policy/id_test.go:32]: done

**Comment by harshavardhana** [comment]
@balamurugana @nitisht PTAL

**Review by nitisht — APPROVED** [review]

**Comment by minio-ops** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-tls.sh | :heavy_check_mark: |
| mint-xl.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-worm.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-dist-xl.sh | :heavy_check_mark: |

**Review by balamurugana — APPROVED** [review]
