### PR TITLE
posix: Mkdir() and OpenFile() should honor umask.

### LINKED ISSUE #1965: minio sets 700/600 mode on directories/files
## Expected behaviour

I expected minio to create directories/files with a default umask, which in my case is 022.
## Actual behaviour

Minio, however, creates directories/files with a mode 700/600, which makes it impossible to integrate with an existing web-server, for them both to serve one directory.
## Steps to reproduce the behaviour

Install minio, create a bucket. Observer 700 mode.
## Minio version
- (paste output of `minio version`)
  Version: 2016-06-03T19:32:05Z
  Release-Tag: RELEASE.2016-06-03T19-32-05Z
  Commit-ID: 73ddb5be758566dde18b519393c7554ae280b074
  ## System information
  Linux enceladus 3.10.0-229.el7.x86_64 #1 SMP Fri Mar 6 11:36:42 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

### PR DESCRIPTION
**Pull request by harshavardhana**
Adds two unit tests for validation as well.

Fixes #1965

### CODE REVIEW

File: posix-utils_test.go [hunk 1]
```diff
@@ -0,0 +1,74 @@
...
+		{"1234567", true},
+		{"123", true},
+		{"s3-eu-west-1.amazonaws.com", true},
+		{"ideas-are-more-powerful-than-guns", true},
+		{"testbucket", true},
+		{"1bucket", true},
+		{"bucket1", true},
+		// cases for which test should fail.
+		// passing invalid bucket names.
+		{"------", true},
```
Comment (hackintoshrao) [inline posix-utils_test.go]: the `shouldPass` parameter should `false` if test is expected to fail right?
