### PR TITLE
XL/GetObject: If quorum not available during GetObject appropriate error should be returned.

### LINKED ISSUE #2129: XL: when readQuorum fails, GetObject returns 200OK with no content
in 8:8 setup, when 8 disks are down:

```
krishna@escape:~$ mc --debug cat myminio/testbucket/passwd
mc: <DEBUG> GET /testbucket/?location= HTTP/1.1
Host: localhost:9000
User-Agent: Minio (linux; amd64) minio-go/1.0.1 mc/2016-07-06T11:47:13Z
Authorization: AWS4-HMAC-SHA256 Credential=**REDACTED**/20160707/us-east-1/s3/aws4_request, SignedHeaders=host;x-amz-content-sha256;x-amz-date, Signature=**REDACTED**
X-Amz-Content-Sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
X-Amz-Date: 20160707T142610Z
Accept-Encoding: gzip

mc: <DEBUG> HTTP/1.1 200 OK
Transfer-Encoding: chunked
Accept-Ranges: bytes
Content-Type: text/xml; charset=utf-8
Date: Thu, 07 Jul 2016 14:26:10 GMT
Server: Minio/DEVELOPMENT.GOGET (linux; amd64)
Vary: Origin
X-Amz-Request-Id: 9O64XXWK7YYGQHKA

mc: <DEBUG> Response Time:  1.763014ms

mc: <DEBUG> GET /testbucket/passwd HTTP/1.1
Host: localhost:9000
User-Agent: Minio (linux; amd64) minio-go/1.0.1 mc/2016-07-06T11:47:13Z
Authorization: AWS4-HMAC-SHA256 Credential=**REDACTED**/20160707/us-east-1/s3/aws4_request, SignedHeaders=expect;host;x-amz-content-sha256;x-amz-date, Signature=**REDACTED**
Expect: 100-continue
X-Amz-Content-Sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
X-Amz-Date: 20160707T142610Z
Accept-Encoding: gzip

mc: <DEBUG> HTTP/1.1 200 OK
Content-Length: 2204
Accept-Ranges: bytes
Content-Type: application/octet-stream
Date: Thu, 07 Jul 2016 14:26:10 GMT
Etag: "b9a59b85f2dd2b7fa57a82be7b15c806"
Last-Modified: Thu, 07 Jul 2016 14:24:08 GMT
Server: Minio/DEVELOPMENT.GOGET (linux; amd64)
Vary: Origin
X-Amz-Request-Id: WOE87UCMUTPI49PI

mc: <DEBUG> Response Time:  1.946786ms

krishna@escape:~$ 
```

Should have returned quorum/internal error.

### PR DESCRIPTION
**Pull request by krishnasrinivas**
fixes #2129

@harshavardhana I don't know how it behaves if headers have already been sent down the wire because parial data was already written on the response writer. But it works as expected if no data was sent down the socket when the quorum error is returned.

### CODE REVIEW

File: object-handlers.go [hunk 1]
```diff
@@ -144,7 +144,10 @@ func (api objectAPIHandlers) GetObjectHandler(w http.ResponseWriter, r *http.Req
 	// Reads the object at startOffset and writes to mw.
 	if err := api.ObjectAPI.GetObject(bucket, object, startOffset, length, w); err != nil {
 		errorIf(err, "Unable to write to client.")
-		// Do not send error response here, client would have already died.
+		// In case headers haven't been written to client, unset the headers and send an error response.
+		unsetObjectHeaders(w)
+		apiErr := toAPIErrorCode(err)
+		writeErrorResponse(w, r, apiErr, r.URL.Path)
```
Comment (harshavardhana) [inline object-handlers.go]: You cannot do this, response writer cannot be written again once you have started writing.

**Comment by harshavardhana** [comment]
> @harshavardhana I don't know how it behaves if headers have already been sent down the wire because parial data was already written on the response writer. But it works as expected if no data was sent down the socket when the quorum error is returned.

Golang implementation doesn't allow this to happen, once you have started writing to response writer you cannot again write to it even if there is a partial data.

**Comment by harshavardhana** [comment]
Also you need to be absolutely sure that the data was not written yet, which is not possible in this scenario. As this might lead to races for http.ResponseWriter which starts printing messages on the screen. 

The idea is simple you need to write a non http.StatusOK on the first write to the response writer could be an error etc this could be a custom closer wrapped in so that if the Close() occurs before the Write() happened we write non http.StatusOK by doing w.responseWriter.WriteHeader(errstatus)

File: object-handlers.go [hunk 2]
```diff
@@ -106,24 +113,22 @@ func (api objectAPIHandlers) GetObjectHandler(w http.ResponseWriter, r *http.Req
...
-		// log the error.
-		errorIf(err, "Invalid request range")
 	}
 
-	// Set standard object headers.
-	setObjectHeaders(w, objInfo, hrange)
-
-	// Set any additional requested response headers.
-	setGetRespHeaders(w, r.URL.Query())
-
```
Comment (harshavardhana) [inline object-handlers.go:126]: Now that you moved this would introduce a bug in checkSourceETag() subsequently, change the function to take in 'ETag' rather than look for responseWriter to have ETag set.

File: object-handlers.go [hunk 3]
```diff
@@ -141,13 +146,44 @@ func (api objectAPIHandlers) GetObjectHandler(w http.ResponseWriter, r *http.Req
...
+			// partial data has already been written before an error
+			// occoured then no point in setting StatusCode and
+			// sending error XML.
+			apiErr := toAPIErrorCode(err)
+			writeErrorResponse(w, r, apiErr, r.URL.Path)
+		}
 		return
 	}
-	// Success.
+	if !dataWritten {
```
Comment (harshavardhana) [inline object-handlers.go:173]: This is harder to follow, why even read if its a '0byte' object? - we have that value with us anyways in objInfo.Size - we could set the headers and return? not even have funcToWriter() for it.

File: object-handlers.go [hunk 4]
```diff
@@ -141,13 +146,44 @@ func (api objectAPIHandlers) GetObjectHandler(w http.ResponseWriter, r *http.Req
...
+	})
 	// Reads the object at startOffset and writes to mw.
-	if err := api.ObjectAPI.GetObject(bucket, object, startOffset, length, w); err != nil {
+	if err := api.ObjectAPI.GetObject(bucket, object, startOffset, length, writer); err != nil {
 		errorIf(err, "Unable to write to client.")
-		// Do not send error response here, client would have already died.
+		if !dataWritten {
+			// Error response only if no data has been written. i.e if
+			// partial data has already been written before an error
+			// occoured then no point in setting StatusCode and
```
Comment (harshavardhana) [inline object-handlers.go]: 'occurred'

File: object-handlers.go [hunk 5]
```diff
@@ -141,13 +146,44 @@ func (api objectAPIHandlers) GetObjectHandler(w http.ResponseWriter, r *http.Req
...
+		}
+		return w.Write(p)
+	})
 	// Reads the object at startOffset and writes to mw.
-	if err := api.ObjectAPI.GetObject(bucket, object, startOffset, length, w); err != nil {
+	if err := api.ObjectAPI.GetObject(bucket, object, startOffset, length, writer); err != nil {
 		errorIf(err, "Unable to write to client.")
-		// Do not send error response here, client would have already died.
+		if !dataWritten {
+			// Error response only if no data has been written. i.e if
```
Comment (harshavardhana) [inline object-handlers.go]: 'Write error response only if not data has been written yet to the client'

**Comment by harshavardhana** [comment]
@krishnasrinivas can you address or reply to comments? - lets get this merged soon.

File: object-handlers.go [hunk 6]
```diff
@@ -178,57 +173,85 @@ func (api objectAPIHandlers) GetObjectHandler(w http.ResponseWriter, r *http.Req
...
+	return false
+}
+
+// returns true if object was modified after givenTime.
+func ifModifiedSince(objTime time.Time, givenTimeStr string) bool {
+	givenTime, err := time.Parse(http.TimeFormat, givenTimeStr)
+	if err != nil {
+		return true
+	}
+	if objTime.After(givenTime) {
```
Comment (harshavardhana) [inline object-handlers.go:252]: `return objTime.After(givenTime)`

**Comment by krishnasrinivas** [comment]
@harshavardhana I haven't taken care of this:

```
-       // The Date-Modified header truncates sub-second precision, so
-       // use mtied me < t+1s instead of mtime <= t to check for unmodified.
```

See if it is needed in the refactored code.

Also I tried doing:

> > This is harder to follow, why even read if its a '0byte' object? - we have that value with us anyways in objInfo.Size - we could set the headers and return? not even have funcToWriter() for it.

But realized i get offset and length and quorum validation for free if i call GetObject() hence simplified the code to this:

```
        if !dataWritten {                                                                                                                                                                                                         
                // If ObjectAPI.GetObject did not return error and no data has                                                                                                                                                    
                // been written it would mean that it is a 0-byte object.                                                                                                                                                         
                // call wrter.Write(nil) to set appropriate headers.                                                                                                                                                              
                writer.Write(nil)                                                                                                                                                                                                 
        }           
```

**Comment by harshavardhana** [comment]
> @harshavardhana I haven't taken care of this:
> -       // The Date-Modified header truncates sub-second precision, so
> -       // use mtied me < t+1s instead of mtime <= t to check for unmodified.
>   See if it is needed in the refactored code.

Yeah this is needed, there is a bug which can happen with applications.
