### PR TITLE
Preserve trailing backslash in URL paths

### LINKED ISSUE #7649: webhook notification strips '/' from the endpoint url
## Expected Behavior
Minio sends notification events to the endpoint url exactly without stripping trailing slash

## Current Behavior
Minio sends notification events to the endpoint url after removing the trailing slash

## Possible Solution
Do not know

## Steps to Reproduce (for bugs)
1. Enable webhook on Minio server
```
                "webhook": {
                    "1": {
                        "enable": true,
                        "endpoint": "http://localhost:4201/api/v1/webhooks/"
                    }
                }
```
2. `mc mb myminio/testbucket/`
3. `mc event add myminio/testbucket/ arn:minio:sqs::1:webhook`
4. In another terminal, run: `nc -l -p 4201`
5. `mc cp file myminio/testbucket/`

In nc output: `POST /webhook HTTP/1.1`
Though it should be: `POST /webhook/ HTTP/1.1`

## Context
Fixing issue encountered by one user community

## Regression
No

## Your Environment
master

### PR DESCRIPTION
**Pull request by Praveenrajmani**
## Description
Unmarshalling the endpoint would clean the url.Path which will remove the trailing backslash.  

## Motivation and Context
Fixes #7649 

## Regression
No

## How Has This Been Tested?
As per steps provided in #7649

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added unit tests to cover my changes.
- [ ] I have added/updated functional tests in [mint](https://github.com/minio/mint). (If yes, add `mint` PR # here: )
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by minio-ops** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-compression-xl.sh | :heavy_check_mark: |
| mint-xl.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-compression-dist-xl.sh | :heavy_check_mark: |
| mint-compression-fs.sh | :heavy_check_mark: |
| mint-worm.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-dist-xl.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |

File: pkg/net/url.go [hunk 1]
```diff
@@ -74,7 +75,15 @@ func (u *URL) UnmarshalJSON(data []byte) (err error) {
 		return err
 	}
 
+	// ParseURL removes the tailing '/' in path.Clean
```
Comment (sinhaashish) [inline pkg/net/url.go]: Typo tailing -> trailing

**Review by sinhaashish — DISMISSED** [review]
Tested & LGTM

File: pkg/net/url.go (hunk 1 above)
Comment (Praveenrajmani) [reply pkg/net/url.go]: Done :+1: @sinhaashish

**Comment by minio-ops** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-compression-xl.sh | :heavy_check_mark: |
| mint-xl.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-compression-dist-xl.sh | :heavy_check_mark: |
| mint-compression-fs.sh | :heavy_check_mark: |
| mint-worm.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-dist-xl.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |

File: pkg/net/url.go [hunk 2]
```diff
@@ -74,7 +75,15 @@ func (u *URL) UnmarshalJSON(data []byte) (err error) {
 		return err
 	}
 
+	// ParseURL removes the trailing '/' in path.Clean
+	if strings.HasSuffix(s, "/") {
+		// Preserving the actual path.
+		uu, _ := url.Parse(s)
+		*ru = URL(*uu)
```
Comment (balamurugana) [inline pkg/net/url.go]: This is wrong. you would need to fix `ParseURL()` to preserve trailing single `/`. You will also need to examine places where this package is used across minio code for breakage.

**Comment by minio-ops** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-compression-xl.sh | :heavy_check_mark: |
| mint-xl.sh | :heavy_check_mark: |
| mint-compression-dist-xl.sh | :heavy_check_mark: |
| mint-compression-fs.sh | :heavy_check_mark: |
| mint-worm.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-dist-xl.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :x: [more...](#04128aa2-632e-493e-9e53-0dd2cb2e9af1) |
<a name="04128aa2-632e-493e-9e53-0dd2cb2e9af1"></a>
### 7678-4846587/mint-large-bucket.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.55:30615
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 515fab73bfc4:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 2 seconds
(2/14) Running aws-sdk-java tests ... done in 2 seconds
(3/14) Running aws-sdk-php tests ... done in 5 minutes and 51 seconds
(4/14) Running aws-sdk-ruby tests ... FAILED in 4 minutes and 11 seconds
{
  "name": "aws-sdk-ruby",
  "function": "copyObject(source_bucket_name, target_bucket_name, source_file_name, target_file_name = )",
  "args": {
    "source_bucket_name": "aws-sdk-ruby-bucket-a22276d4e61b",
    "target_bucket_name": "aws-sdk-ruby-bucket-b06959730cb0",
    "source_file_name": "datafile-1-kB",
    "target_file_name": "datafile-1-kB-copy"
  },
  "duration": 242552.93,
  "error": "Net::ReadTimeout",
  "status": "FAIL"
}

Executed 3 out of 14 tests successfully.
```

File: pkg/net/url.go (hunk 2 above)
Comment (Praveenrajmani) [reply pkg/net/url.go]: Done :+1:

**Comment by minio-ops** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-compression-xl.sh | :heavy_check_mark: |
| mint-xl.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-compression-dist-xl.sh | :heavy_check_mark: |
| mint-compression-fs.sh | :heavy_check_mark: |
| mint-worm.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-dist-xl.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |

**Comment by harshavardhana** [comment]
What is the Go url.URL behavior @Praveenrajmani since our. net.ParseURL is a drop in replacement.? Have you verified their behavior?. it can cause confusion many places..

**Comment by Praveenrajmani** [comment]
> What is the Go url.URL behavior @Praveenrajmani since our. net.ParseURL is a drop in replacement.? Have you verified their behavior?. it can cause confusion many places..

Yes @harshavardhana . Go's url.Parse(s) will not remove the trailing `/`.. It is the `path.Clean` in our `net.ParseURL` that strips away the trailing slash.

**Comment by harshavardhana** [comment]
> Yes @harshavardhana . Go's url.Parse(s) will not remove the trailing `/`.. It is the `path.Clean` in our `net.ParseURL` that strips away the trailing slash.

Understood - thanks @Praveenrajmani

**Comment by Praveenrajmani** [comment]
@balamurugana @sinhaashish Can i get some reviews?

File: pkg/net/url_test.go [hunk 3]
```diff
@@ -107,12 +107,13 @@ func TestURLUnmarshalJSON(t *testing.T) {
 		{[]byte(`"https://play.min.io:0"`), &URL{Scheme: "https", Host: "play.min.io:0"}, false},
 		{[]byte(`"https://147.75.201.93:9000/"`), &URL{Scheme: "https", Host: "147.75.201.93:9000", Path: "/"}, false},
 		{[]byte(`"https://s3.amazonaws.com/?location"`), &URL{Scheme: "https", Host: "s3.amazonaws.com", Path: "/", RawQuery: "location"}, false},
-		{[]byte(`"http://myminio:10000/mybucket//myobject/"`), &URL{Scheme: "http", Host: "myminio:10000", Path: "/mybucket/myobject"}, false},
+		{[]byte(`"http://myminio:10000/mybucket//myobject"`), &URL{Scheme: "http", Host: "myminio:10000", Path: "/mybucket/myobject"}, false},
```
Comment (balamurugana) [inline pkg/net/url_test.go]: This case is already covered in below test case. you could need to add new test case for ends with `//`

File: pkg/net/url_test.go [hunk 4]
```diff
@@ -107,12 +107,13 @@ func TestURLUnmarshalJSON(t *testing.T) {
...
 		{[]byte(`"ftp://myftp.server:10000/myuser"`), &URL{Scheme: "ftp", Host: "myftp.server:10000", Path: "/myuser"}, false},
 		{[]byte(`"myserver:1000"`), nil, true},
 		{[]byte(`"http://:1000/mybucket"`), nil, true},
 		{[]byte(`"https://147.75.201.93:90000/"`), nil, true},
 		{[]byte(`"http:/play"`), nil, true},
+		{[]byte(`"http://webhook.server:10000/mywebhook/"`), &URL{Scheme: "http", Host: "webhook.server:10000", Path: "/mywebhook/"}, false},
```
Comment (balamurugana) [inline pkg/net/url_test.go]: Group positive cases together

Comment (Praveenrajmani) [reply pkg/net/url_test.go]: Done :+1:

File: pkg/net/url_test.go (hunk 3 above)
Comment (Praveenrajmani) [reply pkg/net/url_test.go]: Done :+1:

**Comment by Praveenrajmani** [comment]
Review comments are addressed. PTAL @balamurugana @sinhaashish

**Comment by minio-ops** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-compression-xl.sh | :heavy_check_mark: |
| mint-xl.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-compression-dist-xl.sh | :heavy_check_mark: |
| mint-compression-fs.sh | :heavy_check_mark: |
| mint-worm.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-dist-xl.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |

File: pkg/net/url_test.go [hunk 5]
```diff
@@ -107,12 +107,13 @@ func TestURLUnmarshalJSON(t *testing.T) {
...
 		{[]byte(`"https://s3.amazonaws.com/?location"`), &URL{Scheme: "https", Host: "s3.amazonaws.com", Path: "/", RawQuery: "location"}, false},
-		{[]byte(`"http://myminio:10000/mybucket//myobject/"`), &URL{Scheme: "http", Host: "myminio:10000", Path: "/mybucket/myobject"}, false},
+		{[]byte(`"http://myminio:10000/mybucket/myobject//"`), &URL{Scheme: "http", Host: "myminio:10000", Path: "/mybucket/myobject/"}, false},
 		{[]byte(`"ftp://myftp.server:10000/myuser"`), &URL{Scheme: "ftp", Host: "myftp.server:10000", Path: "/myuser"}, false},
+		{[]byte(`"http://webhook.server:10000/mywebhook/"`), &URL{Scheme: "http", Host: "webhook.server:10000", Path: "/mywebhook/"}, false},
 		{[]byte(`"myserver:1000"`), nil, true},
 		{[]byte(`"http://:1000/mybucket"`), nil, true},
 		{[]byte(`"https://147.75.201.93:90000/"`), nil, true},
-		{[]byte(`"http:/play"`), nil, true},
+		{[]byte(`"http:/play"`), nil, true},
```
Comment (balamurugana) [inline pkg/net/url_test.go]: extra trailing whitespace

Comment (Praveenrajmani) [reply pkg/net/url_test.go]: Done :+1: PTAL @balamurugana @sinhaashish

**Comment by minio-ops** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-xl.sh | :heavy_check_mark: |
| mint-compression-dist-xl.sh | :heavy_check_mark: |
| mint-compression-fs.sh | :heavy_check_mark: |
| mint-worm.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-dist-xl.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-compression-xl.sh | :x: [more...](#4813b6bc-af19-4f1a-bcbd-94e0fdf198a3) |
| mint-large-bucket.sh | :x: [more...](#9c8b3b27-bf13-4347-9b0b-9cf3215c439c) |
<a name="4813b6bc-af19-4f1a-bcbd-94e0fdf198a3"></a>
### 7678-0277294/mint-compression-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.59:30306
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp cfee3ec85418:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 0 seconds
(2/14) Running aws-sdk-java tests ... done in 1 seconds
(3/14) Running aws-sdk-php tests ... done in 42 seconds
(4/14) Running aws-sdk-ruby tests ... done in 2 seconds
(5/14) Running awscli tests ... done in 56 seconds
(6/14) Running healthcheck tests ... done in 1 seconds
(7/14) Running mc tests ... done in 32 seconds
(8/14) Running minio-dotnet tests ... done in 25 seconds
(9/14) Running minio-go tests ... done in 1 minutes and 12 seconds
(10/14) Running minio-java tests ... done in 58 seconds
(11/14) Running minio-js tests ... done in 36 seconds
(12/14) Running minio-py tests ... FAILED in 2 minutes and 57 seconds
{
  "duration": 5072,
  "message": "Presigned get url failed to expire!",
  "name": "minio-py:test_presigned_get_object_expiry_5sec",
  "args": {
    "response.reason": "OK",
    "response.reason-2": "OK",
    "response._body": "frfusnbypalkmrhzdxftbubpnvupzyavqaqccedindvnvuxbvzcdcxxqdzozmpegpykdxaidgiczlllbvpxbuszqlogiseovenfltlccciykalxtldoryofiksfyqozvqrnozciknekikpelepovjpgtxjbgrmybhkpopcqphgrqvdwefcdkebljxiirjhoxjapqfqbxmnyezjvshkokmgzkxexlmytkdcjffaceptlpbucznuniqzlyvpdnzitgbffxrpugcrxdrajnbcuwjxijeuegsfytfajlsudfczgfrbehxnraofykqjyekhdiwabfdzprmopjahvkfopagmxjirrpnsguccdaefkfvwhjstgpeurxwuyckmwfxaotsigftwtahhgmenewnoykbvpjrwwbvhkbiaihlotwjpzevcbzhkrslylhocbiuvmjueihppfbqlgjcqmqajmznqrwhnabjntxceotmegnoyouyeablisjykgernyfilxjulceadzbeqlqgpzvcmreleqynkzgqknqlwxytmkewvcdcpyjsscossjdlwvoxvgkywvsyrmllyvubmqalxnetaesbtjimgezzyudajikqylgjgqtqtqlftrwavfankmudwxxeuhblsixtwngqeuxdjydbnyddkjlqlvezmgdvxutzjfnuiqjzsnyzipjtuirccfvsznmnaueqzuixaxzloisnwimbdchnpfnsmzvtohhoreexhlfjyvcvsghsqjxgkgntumubesyorwfjzlchfcldyuojeyvduehxaglwjigxsomjqkwzostlljqtzwoyxcbvivtunqyqqxtjmdkfyucbqhcihxcpwfvvuxpnlboojhobrvayrdrnfgmwttpsvkgzhcofyzagoxkixqhlwmkuviwagtpnjkdqxuddktqaimtkuuagqdynhmfbnouhfdbdfanbpbxklqfdrfyddjnpfnbmmpoxmzcesfekufmiwsnlktquqqzuvtcnzge",
    "response.status": 200,
    "object_name": "cefa5ba6-dc0d-42e4-ab37-6f2c8c1803c6",
    "response.headers": "{\"_container\": {\"accept-ranges\": [\"Accept-Ranges\", \"bytes\"], \"content-length\": [\"Content-Length\", \"1024\"], \"content-security-policy\": [\"Content-Security-Policy\", \"block-all-mixed-content\"], \"content-type\": [\"Content-Type\", \"application/octet-stream\"], \"etag\": [\"ETag\", \"\\\"5bd8f6ee955c98aa69322111ea606fce-1\\\"\"], \"last-modified\": [\"Last-Modified\", \"Mon, 03 Jun 2019 06:17:17 GMT\"], \"server\": [\"Server\", \"MinIO/DEVELOPMENT.2019-06-03T05-56-08Z\"], \"vary\": [\"Vary\", \"Origin\"], \"x-amz-request-id\": [\"X-Amz-Request-Id\", \"15A49BC4357C85FD\"], \"x-minio-deployment-id\": [\"X-Minio-Deployment-Id\", \"bb503ad5-6d7d-4281-8efb-aa6e38c3a909\"], \"x-xss-protection\": [\"X-Xss-Protection\", \"1; mode=block\"], \"date\": [\"Date\", \"Mon, 03 Jun 2019 06:17:17 GMT\"]}}",
    "bucket_name": "minio-py-test-03c2e9e9-95e3-48cd-aabe-ad74288ce778",
    "response._body-2": "frfusnbypalkmrhzdxftbubpnvupzyavqaqccedindvnvuxbvzcdcxxqdzozmpegpykdxaidgiczlllbvpxbuszqlogiseovenfltlccciykalxtldoryofiksfyqozvqrnozciknekikpelepovjpgtxjbgrmybhkpopcqphgrqvdwefcdkebljxiirjhoxjapqfqbxmnyezjvshkokmgzkxexlmytkdcjffaceptlpbucznuniqzlyvpdnzitgbffxrpugcrxdrajnbcuwjxijeuegsfytfajlsudfczgfrbehxnraofykqjyekhdiwabfdzprmopjahvkfopagmxjirrpnsguccdaefkfvwhjstgpeurxwuyckmwfxaotsigftwtahhgmenewnoykbvpjrwwbvhkbiaihlotwjpzevcbzhkrslylhocbiuvmjueihppfbqlgjcqmqajmznqrwhnabjntxceotmegnoyouyeablisjykgernyfilxjulceadzbeqlqgpzvcmreleqynkzgqknqlwxytmkewvcdcpyjsscossjdlwvoxvgkywvsyrmllyvubmqalxnetaesbtjimgezzyudajikqylgjgqtqtqlftrwavfankmudwxxeuhblsixtwngqeuxdjydbnyddkjlqlvezmgdvxutzjfnuiqjzsnyzipjtuirccfvsznmnaueqzuixaxzloisnwimbdchnpfnsmzvtohhoreexhlfjyvcvsghsqjxgkgntumubesyorwfjzlchfcldyuojeyvduehxaglwjigxsomjqkwzostlljqtzwoyxcbvivtunqyqqxtjmdkfyucbqhcihxcpwfvvuxpnlboojhobrvayrdrnfgmwttpsvkgzhcofyzagoxkixqhlwmkuviwagtpnjkdqxuddktqaimtkuuagqdynhmfbnouhfdbdfanbpbxklqfdrfyddjnpfnbmmpoxmzcesfekufmiwsnlktquqqzuvtcnzge",
    "response.status-2": 200,
    "response.headers-2": "{\"_container\": {\"accept-ranges\": [\"Accept-Ranges\", \"bytes\"], \"content-length\": [\"Content-Length\", \"1024\"], \"content-security-policy\": [\"Content-Security-Policy\", \"block-all-mixed-content\"], \"content-type\": [\"Content-Type\", \"application/octet-stream\"], \"etag\": [\"ETag\", \"\\\"5bd8f6ee955c98aa69322111ea606fce-1\\\"\"], \"last-modified\": [\"Last-Modified\", \"Mon, 03 Jun 2019 06:17:17 GMT\"], \"server\": [\"Server\", \"MinIO/DEVELOPMENT.2019-06-03T05-56-08Z\"], \"vary\": [\"Vary\", \"Origin\"], \"x-amz-request-id\": [\"X-Amz-Request-Id\", \"15A49BC5600EA8D3\"], \"x-minio-deployment-id\": [\"X-Minio-Deployment-Id\", \"bb503ad5-6d7d-4281-8efb-aa6e38c3a909\"], \"x-xss-protection\": [\"X-Xss-Protection\", \"1; mode=block\"], \"date\": [\"Date\", \"Mon, 03 Jun 2019 06:17:23 GMT\"]}}",
    "presigned_get_object_url": "http://72.28.97.59:30306/minio-py-test-03c2e9e9-95e3-48cd-aabe-ad74288ce778/cefa5ba6-dc0d-42e4-ab37-6f2c8c1803c6?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=minio%2F20190603%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20190603T061718Z&X-Amz-Expires=5&X-Amz-SignedHeaders=host&X-Amz-Signature=1e1a3de07d2cdeedfd339f8a435b311cbd2ee4797c2764078f2c9db6f6401611"
  },
  "error": "Traceback (most recent call last):\n  File \"/mint/run/core/minio-py/tests.py\", line 1242, in test_presigned_get_object_expiry_5sec\n    raise ValueError('Presigned get url failed to expire!')\nValueError: Presigned get url failed to expire!\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"/mint/run/core/minio-py/tests.py\", line 1913, in main\n    test_presigned_get_object_expiry_5sec(client, log_output)\n  File \"/mint/run/core/minio-py/tests.py\", line 1244, in test_presigned_get_object_expiry_5sec\n    raise Exception(err)\nException: Presigned get url failed to expire!\n",
  "status": "FAIL",
  "function": "presigned_get_object(bucket_name, object_name, expires, response_headers, request_date)"
}

Executed 11 out of 14 tests successfully.
```
<a name="9c8b3b27-bf13-4347-9b0b-9cf3215c439c"></a>
### 7678-0277294/mint-large-bucket.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.57:30103
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 2844efe10061:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... FAILED in 3 seconds
{
  "alert": "",
  "args": {
    "bucketName": "aws-sdk-go-test-gbb6ytfnuh1ls4",
    "expiry": 60000000000,
    "objectName": "presignedTest"
  },
  "duration": 3052,
  "error": "RequestError: send request failed\ncaused by: Put http://72.28.97.57:30103/aws-sdk-go-test-gbb6ytfnuh1ls4: dial tcp 72.28.97.57:30103: connect: no route to host",
  "function": "PresignedPut",
  "message": "AWS SDK Go CreateBucket Failed",
  "name": "aws-sdk-go",
  "status": "FAIL"
}

Executed 0 out of 14 tests successfully.
```

**Review by balamurugana — COMMENTED** [review]
LGTM

**Comment by Praveenrajmani** [comment]
PTAL @balamurugana @sinhaashish

**Comment by minio-ops** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-compression-xl.sh | :heavy_check_mark: |
| mint-xl.sh | :heavy_check_mark: |
| mint-compression-dist-xl.sh | :heavy_check_mark: |
| mint-compression-fs.sh | :heavy_check_mark: |
| mint-worm.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :x: [more...](#9eccdf1e-a455-4a45-b88b-07d294b34f1e) |
| mint-dist-xl.sh | :x: [more...](#656985e1-257d-4d68-bb9b-c9a30100573e) |
<a name="656985e1-257d-4d68-bb9b-c9a30100573e"></a>
### 7678-2df769e/mint-dist-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.53:31108
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 3bb7f2a73ee9:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 0 seconds
(2/14) Running aws-sdk-java tests ... done in 1 seconds
(3/14) Running aws-sdk-php tests ... done in 43 seconds
(4/14) Running aws-sdk-ruby tests ... done in 3 seconds
(5/14) Running awscli tests ... done in 2 minutes and 0 seconds
(6/14) Running healthcheck tests ... done in 0 seconds
(7/14) Running mc tests ... done in 1 minutes and 1 seconds
(8/14) Running minio-dotnet tests ... done in 30 seconds
(9/14) Running minio-go tests ... done in 59 seconds
(10/14) Running minio-java tests ... FAILED in 40 seconds
{
  "name": "minio-java",
  "function": "listIncompleteUploads(String bucketName, String prefix)",
  "duration": 547,
  "status": "FAIL",
  "error": "error occurred\nErrorResponse(code=SlowDown, message=Please reduce your request, bucketName=minio-java-test-3ua2ug7, objectName=minio-java-test-3s073an, resource=/minio-java-test-3ua2ug7/minio-java-test-3s073an, requestId=15A53E7DCE1A8AB2, hostId=e14b7fec-2e8d-40b3-bc72-b5d5eda085d0)\nrequest={method=DELETE, url=http://72.28.97.53:31108/minio-java-test-3ua2ug7/minio-java-test-3s073an?uploadId=22483a3e-011c-4a8c-af35-cac5e2333530, headers=Host: 72.28.97.53:31108\nUser-Agent: MinIO (amd64; amd64) minio-java/dev\nx-amz-content-sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855\nx-amz-date: 20190605T075916Z\nAuthorization: AWS4-HMAC-SHA256 Credential=*REDACTED*/20190605/us-east-1/s3/aws4_request, SignedHeaders=host;x-amz-content-sha256;x-amz-date, Signature=*REDACTED*\n}\nresponse={code=503, headers=Accept-Ranges: bytes\nContent-Security-Policy: block-all-mixed-content\nContent-Type: application/xml\nRetry-After: 120\nServer: MinIO/DEVELOPMENT.2019-06-05T07-40-19Z\nVary: Origin\nX-Amz-Request-Id: 15A53E7DCE1A8AB2\nX-Minio-Deployment-Id: e14b7fec-2e8d-40b3-bc72-b5d5eda085d0\nX-Xss-Protection: 1; mode=block\nDate: Wed, 05 Jun 2019 07:59:16 GMT\nTransfer-Encoding: chunked\n}\n >>> [io.minio.MinioClient.executeReq(MinioClient.java:1204), io.minio.MinioClient.execute(MinioClient.java:1070), io.minio.MinioClient.executeDelete(MinioClient.java:1347), io.minio.MinioClient.abortMultipartUpload(MinioClient.java:5149), io.minio.MinioClient.putObject(MinioClient.java:4337), io.minio.MinioClient.putObject(MinioClient.java:4183), FunctionalTest.listIncompleteUploads_test2(FunctionalTest.java:1639), FunctionalTest.runTests(FunctionalTest.java:2989), FunctionalTest.main(FunctionalTest.java:3118)]"
}

Executed 9 out of 14 tests successfully.
```
<a name="9eccdf1e-a455-4a45-b88b-07d294b34f1e"></a>
### 7678-2df769e/mint-large-bucket.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.59:31155
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp e0edc5e0ab4b:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 2 seconds
(2/14) Running aws-sdk-java tests ... done in 1 seconds
(3/14) Running aws-sdk-php tests ... done in 48 seconds
(4/14) Running aws-sdk-ruby tests ... done in 14 seconds
(5/14) Running awscli tests ... done in 2 minutes and 21 seconds
(6/14) Running healthcheck tests ... done in 0 seconds
(7/14) Running mc tests ... FAILED in 7 minutes and 36 seconds
{
  "name": "mc",
  "duration": "120566",
  "function": "test_mirror_list_objects_storage_class",
  "status": "FAIL",
  "error": "/mint/run/core/mc/mc --config-dir /tmp/.mc-17854 --quiet --no-color mirror --storage-class REDUCED_REDUNDANCY /mint/data myminio/mc-test-bucket-12501  >>> \n`/mint/data/datafile-1-MB` -> `myminio/mc-test-bucket-12501/datafile-1-MB`\n`/mint/data/datafile-0-b` -> `myminio/mc-test-bucket-12501/datafile-0-b`\n`/mint/data/datafile-1-kB` -> `myminio/mc-test-bucket-12501/datafile-1-kB`\n`/mint/data/datafile-1-b` -> `myminio/mc-test-bucket-12501/datafile-1-b`\n`/mint/data/datafile-10-MB` -> `myminio/mc-test-bucket-12501/datafile-10-MB`\n`/mint/data/datafile-1.03-MB` -> `myminio/mc-test-bucket-12501/datafile-1.03-MB`\n`/mint/data/datafile-100-kB` -> `myminio/mc-test-bucket-12501/datafile-100-kB`\n`/mint/data/datafile-129-MB` -> `myminio/mc-test-bucket-12501/datafile-129-MB`\n`/mint/data/datafile-10-kB` -> `myminio/mc-test-bucket-12501/datafile-10-kB`\n`/mint/data/datafile-11-MB` -> `myminio/mc-test-bucket-12501/datafile-11-MB`\n`/mint/data/datafile-5-MB` -> `myminio/mc-test-bucket-12501/datafile-5-MB`\n`/mint/data/datafile-33-kB` -> `myminio/mc-test-bucket-12501/datafile-33-kB`\n`/mint/data/datafile-6-MB` -> `myminio/mc-test-bucket-12501/datafile-6-MB`\n`/mint/data/datafile-5243880-b` -> `myminio/mc-test-bucket-12501/datafile-5243880-b`\n`/mint/data/datafile-65-MB` -> `myminio/mc-test-bucket-12501/datafile-65-MB`\nmc: <ERROR> Failed to copy `/mint/data/datafile-129-MB`. Please reduce your request\nmc: <ERROR> Failed to copy `/mint/data/datafile-65-MB`. Please reduce your request\nmc: <ERROR> Failed to copy `/mint/data/datafile-10-MB`. Please reduce your request\nmc: <ERROR> Failed to copy `/mint/data/datafile-11-MB`. Please reduce your request\nTotal: 233.17 MiB, Transferred: 487.96 MiB, Speed: 4.05 MiB/s"
}

Executed 6 out of 14 tests successfully.
```

**Comment by minio-ops** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-compression-xl.sh | :heavy_check_mark: |
| mint-compression-dist-xl.sh | :heavy_check_mark: |
| mint-compression-fs.sh | :heavy_check_mark: |
| mint-worm.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-xl.sh | :x: [more...](#da676ba7-0f6f-4dbd-ba0a-6df66c88ccba) |
| mint-large-bucket.sh | :x: [more...](#c53ee429-1861-4493-b181-1f598a4a9165) |
| mint-dist-xl.sh | :x: [more...](#f13172f5-de1c-41ab-9bca-e2cd39c99873) |
<a name="da676ba7-0f6f-4dbd-ba0a-6df66c88ccba"></a>
### 7678-e799da4/mint-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.55:31662
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 22aa89b21052:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... FAILED in 6 minutes and 0 seconds
{
  "alert": "",
  "args": {
    "bucketName": "aws-sdk-go-test-pffae1i4ggn0gz",
    "expiry": 60000000000,
    "objectName": "presignedTest"
  },
  "duration": 360008,
  "error": "XMinioServerNotInitialized: Server not initialized, please try again.\n\tstatus code: 503, request id: 15A58A0DFC90C0CA, host id: ",
  "function": "PresignedPut",
  "message": "AWS SDK Go CreateBucket Failed",
  "name": "aws-sdk-go",
  "status": "FAIL"
}

Executed 0 out of 14 tests successfully.
```
<a name="c53ee429-1861-4493-b181-1f598a4a9165"></a>
### 7678-e799da4/mint-large-bucket.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.57:30506
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp b9a7a6a12f63:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... FAILED in 3 seconds
{
  "alert": "",
  "args": {
    "bucketName": "aws-sdk-go-test-6mhf1u4ektqen6",
    "expiry": 60000000000,
    "objectName": "presignedTest"
  },
  "duration": 3074,
  "error": "RequestError: send request failed\ncaused by: Put http://72.28.97.57:30506/aws-sdk-go-test-6mhf1u4ektqen6: dial tcp 72.28.97.57:30506: connect: no route to host",
  "function": "PresignedPut",
  "message": "AWS SDK Go CreateBucket Failed",
  "name": "aws-sdk-go",
  "status": "FAIL"
}

Executed 0 out of 14 tests successfully.
```
<a name="f13172f5-de1c-41ab-9bca-e2cd39c99873"></a>
### 7678-e799da4/mint-dist-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.54:31365
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 4fb1b1157a1f:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 0 seconds
(2/14) Running aws-sdk-java tests ... done in 1 seconds
(3/14) Running aws-sdk-php tests ... done in 43 seconds
(4/14) Running aws-sdk-ruby tests ... done in 3 seconds
(5/14) Running awscli tests ... done in 1 minutes and 57 seconds
(6/14) Running healthcheck tests ... done in 0 seconds
(7/14) Running mc tests ... done in 51 seconds
(8/14) Running minio-dotnet tests ... done in 35 seconds
(9/14) Running minio-go tests ... done in 59 seconds
(10/14) Running minio-java tests ... FAILED in 39 seconds
{
  "name": "minio-java",
  "function": "presignedGetObject(String bucketName, String objectName, Integer expires, Map<String, String> reqParams)",
  "duration": 43,
  "status": "FAIL",
  "error": "java.lang.Exception: failed to read object. Response: Response{protocol=http/1.1, code=503, message=Service Unavailable, url=http://72.28.97.54:31365/minio-java-test-an991u/minio-java-test-1oh3504?response-content-type=application%2Fjson&X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=minio%2F20190606%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20190606T070346Z&X-Amz-Expires=3600&X-Amz-SignedHeaders=host&X-Amz-Signature=719868c11162f7964690598447a55ff8cf606f821282ef50a149730c854d546d}, Response body: <?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<Error><Code>SlowDown</Code><Message>Please reduce your request</Message><Key>minio-java-test-1oh3504</Key><BucketName>minio-java-test-an991u</BucketName><Resource>/minio-java-test-an991u/minio-java-test-1oh3504</Resource><RequestId>15A58A0B195CD44D</RequestId><HostId>11270965-eaee-4842-87aa-76c44b25fe20</HostId></Error> >>> [FunctionalTest.readObject(FunctionalTest.java:201), FunctionalTest.presignedGetObject_test3(FunctionalTest.java:1842), FunctionalTest.runTests(FunctionalTest.java:2996), FunctionalTest.main(FunctionalTest.java:3118)]"
}

Executed 9 out of 14 tests successfully.
```

**Comment by harshavardhana** [comment]
PTAL @balamurugana @sinhaashish @vadmeste

File: pkg/net/url.go [hunk 6]
```diff
@@ -100,6 +101,11 @@ func ParseURL(s string) (u *URL, err error) {
 		uu.Path = path.Clean(uu.Path)
 	}
 
+	// path.Clean removes the trailing '/' and converts '//' to '/'.
+	if strings.HasSuffix(s, "/") && !strings.HasSuffix(uu.Path, "/") {
```
Comment (vadmeste) [inline pkg/net/url.go:105]: @Praveenrajmani I doubt cleaning uu.Path has any useful purpose, I think it is enough to just remove it

**Review by vadmeste — COMMENTED** [review]
One comment

File: pkg/net/url.go (hunk 6 above)
Comment (Praveenrajmani) [reply pkg/net/url.go:105]: @vadmeste In windows, filepath,Clean() converts all the `/` into `\`. And it resolves all the `.` and `..` to the current and parent directories as well.

Comment (Praveenrajmani) [reply pkg/net/url.go:105]: And i fear it would break in many places. It might be a breaking change

Comment (balamurugana) [reply pkg/net/url.go:105]: This `URL` package is little different than standard `url.URL` i.e. it removes some corner limitation of `url.URL`. This `URL` package ensures below
1. Not allowed to have scheme without host.
2. port in host should be a number.
3. Keeps path cleaned e.g. `/mybucket//myobject/` is converted to `/mybucket/myobject/` (extra slash are moved)
4. Removes default ports 80/443 for schemes `http/https` when converting to string.

When these are not benefited, its better to use `url.URL` directly in those cases.

**Comment by Praveenrajmani** [comment]
PTAL @balamurugana @sinhaashish

**Comment by minio-ops** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-compression-xl.sh | :heavy_check_mark: |
| mint-worm.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-xl.sh | :x: [more...](#c4cef452-3515-477d-8803-5455033331ad) |
| mint-large-bucket.sh | :x: [more...](#7bd34e70-c17c-4262-9c9c-a611a046064f) |
| mint-compression-dist-xl.sh | :x: [more...](#4257db67-fdb8-401c-8683-978183bb7994) |
| mint-compression-fs.sh | :x: [more...](#4fb032c4-b875-4357-96ce-70f014f8b76f) |
| mint-dist-xl.sh | :x: [more...](#65bbaa96-9b70-4e08-b5a6-ea844ba812c9) |
| mint-gateway-nas.sh | :x: [more...](#9ebf29e8-0d2d-4e91-ac40-bb19550ade5f) |
<a name="7bd34e70-c17c-4262-9c9c-a611a046064f"></a>
### 7678-c1bbc5c/mint-large-bucket.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.56:30123
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 45646430ab92:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 3 seconds
(2/14) Running aws-sdk-java tests ... done in 1 seconds
(3/14) Running aws-sdk-php tests ... done in 1 minutes and 48 seconds
(4/14) Running aws-sdk-ruby tests ... done in 16 seconds
(5/14) Running awscli tests ... done in 2 minutes and 26 seconds
(6/14) Running healthcheck tests ... done in 0 seconds
(7/14) Running mc tests ... FAILED in 1 minutes and 43 seconds
{
  "name": "mc",
  "duration": "99873",
  "function": "test_put_object_with_storage_class",
  "status": "FAIL",
  "error": "/mint/run/core/mc/mc --config-dir /tmp/.mc-28705 --quiet --no-color cp --storage-class REDUCED_REDUNDANCY /mint/data/datafile-1-MB myminio/mc-test-bucket-3035/mc-test-object-17681  >>> \n`/mint/data/datafile-1-MB` -> `myminio/mc-test-bucket-3035/mc-test-object-17681`\nmc: <ERROR> Failed to copy `/mint/data/datafile-1-MB`. Please reduce your request\nmc: <ERROR> Session safely terminated. To resume session `mc session resume nQDzZeQU`"
}

Executed 6 out of 14 tests successfully.
```
<a name="9ebf29e8-0d2d-4e91-ac40-bb19550ade5f"></a>
### 7678-c1bbc5c/mint-gateway-nas.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.60:30381
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 722e951e5a21:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... FAILED in 3 seconds
{
  "alert": "",
  "args": {
    "bucketName": "aws-sdk-go-test-yyrgffzxbv0uvm",
    "expiry": 60000000000,
    "objectName": "presignedTest"
  },
  "duration": 3068,
  "error": "RequestError: send request failed\ncaused by: Put http://72.28.97.60:30381/aws-sdk-go-test-yyrgffzxbv0uvm: dial tcp 72.28.97.60:30381: connect: no route to host",
  "function": "PresignedPut",
  "message": "AWS SDK Go CreateBucket Failed",
  "name": "aws-sdk-go",
  "status": "FAIL"
}

Executed 0 out of 14 tests successfully.
```
<a name="4257db67-fdb8-401c-8683-978183bb7994"></a>
### 7678-c1bbc5c/mint-compression-dist-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.57:32179
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 4d3804edfc40:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... FAILED in 2 seconds
{
  "alert": "",
  "args": {
    "bucketName": "aws-sdk-go-test-parqigsk0553ry",
    "expiry": 60000000000,
    "objectName": "presignedTest"
  },
  "duration": 2186,
  "error": "RequestError: send request failed\ncaused by: Put http://72.28.97.57:32179/aws-sdk-go-test-parqigsk0553ry: dial tcp 72.28.97.57:32179: connect: no route to host",
  "function": "PresignedPut",
  "message": "AWS SDK Go CreateBucket Failed",
  "name": "aws-sdk-go",
  "status": "FAIL"
}

Executed 0 out of 14 tests successfully.
```
<a name="65bbaa96-9b70-4e08-b5a6-ea844ba812c9"></a>
### 7678-c1bbc5c/mint-dist-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.56:32720
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp b76240b3205b:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 0 seconds
(2/14) Running aws-sdk-java tests ... done in 1 seconds
(3/14) Running aws-sdk-php tests ... done in 1 minutes and 43 seconds
(4/14) Running aws-sdk-ruby tests ... done in 3 seconds
(5/14) Running awscli tests ... done in 1 minutes and 3 seconds
(6/14) Running healthcheck tests ... done in 0 seconds
(7/14) Running mc tests ... done in 49 seconds
(8/14) Running minio-dotnet tests ... done in 31 seconds
(9/14) Running minio-go tests ... done in 47 seconds
(10/14) Running minio-java tests ... FAILED in 41 seconds
{
  "name": "minio-java",
  "function": "listIncompleteUploads(final String bucketName, final String prefix, final boolean recursive)",
  "args": "prefix: minio, recursive: true",
  "duration": 228,
  "status": "FAIL",
  "error": "error occurred\nErrorResponse(code=SlowDown, message=Please reduce your request, bucketName=minio-java-test-a00aq1, objectName=minio-java-test-20c7i6o, resource=/minio-java-test-a00aq1/minio-java-test-20c7i6o, requestId=15AF910B7CC834B0, hostId=103fb3dc-ce35-423e-947e-78c66908da17)\nrequest={method=DELETE, url=http://72.28.97.56:32720/minio-java-test-a00aq1/minio-java-test-20c7i6o?uploadId=c7835383-a23e-4605-8d8b-ea28069ec7bc, headers=Host: 72.28.97.56:32720\nUser-Agent: MinIO (amd64; amd64) minio-java/dev\nx-amz-content-sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855\nx-amz-date: 20190708T230434Z\nAuthorization: AWS4-HMAC-SHA256 Credential=*REDACTED*/20190708/us-east-1/s3/aws4_request, SignedHeaders=host;x-amz-content-sha256;x-amz-date, Signature=*REDACTED*\n}\nresponse={code=503, headers=Accept-Ranges: bytes\nContent-Length: 361\nContent-Security-Policy: block-all-mixed-content\nContent-Type: application/xml\nRetry-After: 120\nServer: MinIO/DEVELOPMENT.2019-07-08T22-45-59Z\nVary: Origin\nX-Amz-Request-Id: 15AF910B7CC834B0\nX-Xss-Protection: 1; mode=block\nDate: Mon, 08 Jul 2019 23:04:34 GMT\n}\n >>> [io.minio.MinioClient.executeReq(MinioClient.java:1204), io.minio.MinioClient.execute(MinioClient.java:1070), io.minio.MinioClient.executeDelete(MinioClient.java:1347), io.minio.MinioClient.abortMultipartUpload(MinioClient.java:5149), io.minio.MinioClient.putObject(MinioClient.java:4337), io.minio.MinioClient.putObject(MinioClient.java:4183), FunctionalTest.listIncompleteUploads_test3(FunctionalTest.java:1679), FunctionalTest.runTests(FunctionalTest.java:2990), FunctionalTest.main(FunctionalTest.java:3118)]"
}

Executed 9 out of 14 tests successfully.
```
<a name="c4cef452-3515-477d-8803-5455033331ad"></a>
### 7678-c1bbc5c/mint-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.57:31438
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp ed86e73f92a5:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... FAILED in 3 seconds
{
  "alert": "",
  "args": {
    "bucketName": "aws-sdk-go-test-xyfpmacg3w3ge5",
    "expiry": 60000000000,
    "objectName": "presignedTest"
  },
  "duration": 3079,
  "error": "RequestError: send request failed\ncaused by: Put http://72.28.97.57:31438/aws-sdk-go-test-xyfpmacg3w3ge5: dial tcp 72.28.97.57:31438: connect: no route to host",
  "function": "PresignedPut",
  "message": "AWS SDK Go CreateBucket Failed",
  "name": "aws-sdk-go",
  "status": "FAIL"
}

Executed 0 out of 14 tests successfully.
```
<a name="4fb032c4-b875-4357-96ce-70f014f8b76f"></a>
### 7678-c1bbc5c/mint-compression-fs.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.55:32391
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp f644cf28c4d8:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 0 seconds
(2/14) Running aws-sdk-java tests ... done in 1 seconds
(3/14) Running aws-sdk-php tests ... done in 41 seconds
(4/14) Running aws-sdk-ruby tests ... FAILED in 1 seconds
{
  "name": "aws-sdk-ruby",
  "function": "presignedPut(bucket_name,file_name)",
  "args": {
    "bucket_name": "aws-sdk-ruby-bucket-5c83c96c9c14",
    "file_name": "datafile-1-kB"
  },
  "duration": 13.93,
  "error": "Failed to open TCP connection to 72.28.97.55:32391 (Connection refused - connect(2) for \"72.28.97.55\" port 32391)",
  "status": "FAIL"
}

Executed 3 out of 14 tests successfully.
```

**Review by balamurugana — COMMENTED** [review]
LGTM

**Comment by Praveenrajmani** [comment]
PTAL @sinhaashish @vadmeste

**Review by vadmeste — APPROVED** [review]
LGTM

**Comment by minio-ops** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-xl.sh | :heavy_check_mark: |
| mint-compression-dist-xl.sh | :heavy_check_mark: |
| mint-worm.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-compression-xl.sh | :x: [more...](#8f3ce262-7cfc-4826-83a0-cc1bcde7d245) |
| mint-large-bucket.sh | :x: [more...](#fd4ccc04-83b0-4f9f-b7b6-6b01d440494b) |
| mint-compression-fs.sh | :x: [more...](#30f5d379-0e63-434a-aa6b-f89cce8fd356) |
| mint-dist-xl.sh | :x: [more...](#7c37f344-916c-4fb3-8e8c-c0cee6c5a452) |
<a name="fd4ccc04-83b0-4f9f-b7b6-6b01d440494b"></a>
### 7678-866cfad/mint-large-bucket.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.53:31027
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 2e9eee16ae56:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 2 seconds
(2/14) Running aws-sdk-java tests ... done in 2 seconds
(3/14) Running aws-sdk-php tests ... done in 54 seconds
(4/14) Running aws-sdk-ruby tests ... done in 12 seconds
(5/14) Running awscli tests ... done in 1 minutes and 27 seconds
(6/14) Running healthcheck tests ... done in 1 seconds
(7/14) Running mc tests ... FAILED in 1 minutes and 14 seconds
{
  "name": "mc",
  "duration": "71780",
  "function": "test_put_object_with_storage_class",
  "status": "FAIL",
  "error": "/mint/run/core/mc/mc --config-dir /tmp/.mc-224 --quiet --no-color cp --storage-class REDUCED_REDUNDANCY /mint/data/datafile-1-MB myminio/mc-test-bucket-32246/mc-test-object-10029  >>> \n`/mint/data/datafile-1-MB` -> `myminio/mc-test-bucket-32246/mc-test-object-10029`\nmc: <ERROR> Failed to copy `/mint/data/datafile-1-MB`. Please reduce your request\nmc: <ERROR> Session safely terminated. To resume session `mc session resume hNeKsogS`"
}

Executed 6 out of 14 tests successfully.
```
<a name="7c37f344-916c-4fb3-8e8c-c0cee6c5a452"></a>
### 7678-866cfad/mint-dist-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.54:30353
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 25d69b16e590:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 0 seconds
(2/14) Running aws-sdk-java tests ... done in 1 seconds
(3/14) Running aws-sdk-php tests ... done in 43 seconds
(4/14) Running aws-sdk-ruby tests ... done in 3 seconds
(5/14) Running awscli tests ... done in 2 minutes and 0 seconds
(6/14) Running healthcheck tests ... done in 0 seconds
(7/14) Running mc tests ... done in 42 seconds
(8/14) Running minio-dotnet tests ... done in 35 seconds
(9/14) Running minio-go tests ... done in 51 seconds
(10/14) Running minio-java tests ... FAILED in 40 seconds
{
  "name": "minio-java",
  "function": "listIncompleteUploads(String bucketName, String prefix)",
  "duration": 580,
  "status": "FAIL",
  "error": "error occurred\nErrorResponse(code=SlowDown, message=Please reduce your request, bucketName=minio-java-test-2ersgoi, objectName=minio-java-test-1aarv11, resource=/minio-java-test-2ersgoi/minio-java-test-1aarv11, requestId=15AFCE72C1A13869, hostId=c795839c-51a6-4bc1-8e23-cb8d01ded112)\nrequest={method=DELETE, url=http://72.28.97.54:30353/minio-java-test-2ersgoi/minio-java-test-1aarv11?uploadId=853b9f93-2d7a-4b70-9b52-4b1c253d67d7, headers=Host: 72.28.97.54:30353\nUser-Agent: MinIO (amd64; amd64) minio-java/dev\nx-amz-content-sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855\nx-amz-date: 20190709T174947Z\nAuthorization: AWS4-HMAC-SHA256 Credential=*REDACTED*/20190709/us-east-1/s3/aws4_request, SignedHeaders=host;x-amz-content-sha256;x-amz-date, Signature=*REDACTED*\n}\nresponse={code=503, headers=Accept-Ranges: bytes\nContent-Length: 363\nContent-Security-Policy: block-all-mixed-content\nContent-Type: application/xml\nRetry-After: 120\nServer: MinIO/DEVELOPMENT.2019-07-09T17-31-11Z\nVary: Origin\nX-Amz-Request-Id: 15AFCE72C1A13869\nX-Xss-Protection: 1; mode=block\nDate: Tue, 09 Jul 2019 17:49:48 GMT\n}\n >>> [io.minio.MinioClient.executeReq(MinioClient.java:1204), io.minio.MinioClient.execute(MinioClient.java:1070), io.minio.MinioClient.executeDelete(MinioClient.java:1347), io.minio.MinioClient.abortMultipartUpload(MinioClient.java:5149), io.minio.MinioClient.putObject(MinioClient.java:4337), io.minio.MinioClient.putObject(MinioClient.java:4183), FunctionalTest.listIncompleteUploads_test2(FunctionalTest.java:1639), FunctionalTest.runTests(FunctionalTest.java:2989), FunctionalTest.main(FunctionalTest.java:3118)]"
}

Executed 9 out of 14 tests successfully.
```
<a name="30f5d379-0e63-434a-aa6b-f89cce8fd356"></a>
### 7678-866cfad/mint-compression-fs.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.57:30994
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 15a06763e985:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... FAILED in 3 seconds
{
  "alert": "",
  "args": {
    "bucketName": "aws-sdk-go-test-zxcym9ugodptr3",
    "expiry": 60000000000,
    "objectName": "presignedTest"
  },
  "duration": 2451,
  "error": "RequestError: send request failed\ncaused by: Put http://72.28.97.57:30994/aws-sdk-go-test-zxcym9ugodptr3: dial tcp 72.28.97.57:30994: connect: no route to host",
  "function": "PresignedPut",
  "message": "AWS SDK Go CreateBucket Failed",
  "name": "aws-sdk-go",
  "status": "FAIL"
}

Executed 0 out of 14 tests successfully.
```
<a name="8f3ce262-7cfc-4826-83a0-cc1bcde7d245"></a>
### 7678-866cfad/mint-compression-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.57:32330
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 12eb39e6ee32:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... FAILED in 3 seconds
{
  "alert": "",
  "args": {
    "bucketName": "aws-sdk-go-test-v9kubekgn93x39",
    "expiry": 60000000000,
    "objectName": "presignedTest"
  },
  "duration": 3073,
  "error": "RequestError: send request failed\ncaused by: Put http://72.28.97.57:32330/aws-sdk-go-test-v9kubekgn93x39: dial tcp 72.28.97.57:32330: connect: no route to host",
  "function": "PresignedPut",
  "message": "AWS SDK Go CreateBucket Failed",
  "name": "aws-sdk-go",
  "status": "FAIL"
}

Executed 0 out of 14 tests successfully.
```

**Comment by minio-ops** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-compression-xl.sh | :heavy_check_mark: |
| mint-xl.sh | :heavy_check_mark: |
| mint-compression-dist-xl.sh | :heavy_check_mark: |
| mint-compression-fs.sh | :heavy_check_mark: |
| mint-worm.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :x: [more...](#1b310a2b-1c12-4535-97c6-44eff260f0b2) |
| mint-dist-xl.sh | :x: [more...](#ef6f9bdd-8054-49b8-9f7f-a44233b60539) |
<a name="1b310a2b-1c12-4535-97c6-44eff260f0b2"></a>
### 7678-991c66b/mint-large-bucket.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.51:31525
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp e7e26aa7f3c2:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 1 seconds
(2/14) Running aws-sdk-java tests ... done in 2 seconds
(3/14) Running aws-sdk-php tests ... done in 48 seconds
(4/14) Running aws-sdk-ruby tests ... done in 12 seconds
(5/14) Running awscli tests ... done in 2 minutes and 16 seconds
(6/14) Running healthcheck tests ... done in 0 seconds
(7/14) Running mc tests ... FAILED in 1 minutes and 20 seconds
{
  "name": "mc",
  "duration": "76228",
  "function": "test_put_object_with_storage_class",
  "status": "FAIL",
  "error": "/mint/run/core/mc/mc --config-dir /tmp/.mc-2150 --quiet --no-color cp --storage-class REDUCED_REDUNDANCY /mint/data/datafile-1-MB myminio/mc-test-bucket-24995/mc-test-object-1078  >>> \n`/mint/data/datafile-1-MB` -> `myminio/mc-test-bucket-24995/mc-test-object-1078`\nmc: <ERROR> Failed to copy `/mint/data/datafile-1-MB`. Please reduce your request\nmc: <ERROR> Session safely terminated. To resume session `mc session resume UiqEZrAR`"
}

Executed 6 out of 14 tests successfully.
```
<a name="ef6f9bdd-8054-49b8-9f7f-a44233b60539"></a>
### 7678-991c66b/mint-dist-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.55:32502
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 06606042df6d:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 0 seconds
(2/14) Running aws-sdk-java tests ... done in 1 seconds
(3/14) Running aws-sdk-php tests ... done in 43 seconds
(4/14) Running aws-sdk-ruby tests ... done in 3 seconds
(5/14) Running awscli tests ... done in 2 minutes and 5 seconds
(6/14) Running healthcheck tests ... done in 0 seconds
(7/14) Running mc tests ... done in 1 minutes and 8 seconds
(8/14) Running minio-dotnet tests ... done in 37 seconds
(9/14) Running minio-go tests ... done in 50 seconds
(10/14) Running minio-java tests ... FAILED in 44 seconds
{
  "name": "minio-java",
  "function": "listIncompleteUploads(final String bucketName, final String prefix, final boolean recursive)",
  "args": "prefix: minio, recursive: true",
  "duration": 820,
  "status": "FAIL",
  "error": "error occurred\nErrorResponse(code=SlowDown, message=Please reduce your request, bucketName=minio-java-test-2cr1f1a, objectName=minio-java-test-3s12chi, resource=/minio-java-test-2cr1f1a/minio-java-test-3s12chi, requestId=15B07281404414BA, hostId=372a482b-7352-4e12-bbfe-8b417bd3d1d7)\nrequest={method=DELETE, url=http://72.28.97.55:32502/minio-java-test-2cr1f1a/minio-java-test-3s12chi?uploadId=bde5036e-5eab-4b01-a8c3-d9a236158860, headers=Host: 72.28.97.55:32502\nUser-Agent: MinIO (amd64; amd64) minio-java/dev\nx-amz-content-sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855\nx-amz-date: 20190711T195610Z\nAuthorization: AWS4-HMAC-SHA256 Credential=*REDACTED*/20190711/us-east-1/s3/aws4_request, SignedHeaders=host;x-amz-content-sha256;x-amz-date, Signature=*REDACTED*\n}\nresponse={code=503, headers=Accept-Ranges: bytes\nContent-Length: 363\nContent-Security-Policy: block-all-mixed-content\nContent-Type: application/xml\nRetry-After: 120\nServer: MinIO/DEVELOPMENT.2019-07-11T19-36-58Z\nVary: Origin\nX-Amz-Request-Id: 15B07281404414BA\nX-Xss-Protection: 1; mode=block\nDate: Thu, 11 Jul 2019 19:56:10 GMT\n}\n >>> [io.minio.MinioClient.executeReq(MinioClient.java:1204), io.minio.MinioClient.execute(MinioClient.java:1070), io.minio.MinioClient.executeDelete(MinioClient.java:1347), io.minio.MinioClient.abortMultipartUpload(MinioClient.java:5149), io.minio.MinioClient.putObject(MinioClient.java:4337), io.minio.MinioClient.putObject(MinioClient.java:4183), FunctionalTest.listIncompleteUploads_test3(FunctionalTest.java:1679), FunctionalTest.runTests(FunctionalTest.java:2990), FunctionalTest.main(FunctionalTest.java:3118)]"
}

Executed 9 out of 14 tests successfully.
```

**Comment by harshavardhana** [comment]
PTAL @balamurugana @sinhaashish

**Comment by kannappanr** [comment]
ping @balamurugana @sinhaashish

**Comment by kannappanr** [comment]
ping @sinhaashish PTAL

**Comment by kannappanr** [comment]
Can this PR be reviewed @sinhaashish

**Review by sinhaashish — APPROVED** [review]
LGTM
