### PR TITLE
Send actual size of object in event notifications

### LINKED ISSUE #8407: The object size reported to events is wrong when server side encryption is enabled
If I enable the server side encryption the size reported to events are wrong:

The encryption size on filesystem are 78 byte:

```
ls -ln data/coda2/test2.ebcdic
-rw-r--r-- 1 23232115 30002 78 Oct 16 10:28 data/coda2/test2.ebcdic
```
the rclone client correctly reports the size of the unencrypted file, 48 byte:

```
$ rclone lsjson srv:coda2/test2.ebcdic
[
{"Path":"minio","Name":"minio","Size":48,"MimeType":"application/octet-stream","ModTime":"2019-10-14T18:55:05.000000000Z","IsDir":false}
]
```

the size  on the event are 78:

``` 
{"Records": [{"s3": {"bucket": {"arn": "arn:aws:s3:::coda2", "name": "coda2
", "ownerIdentity": {"principalId": "admin"}}, "object": {"key": "test2.ebcdic", "eTag": "2001
0f00b03170f5311b15fe3290ca6c-1", "size": 78

```
minio is latest release.

### PR DESCRIPTION
**Pull request by poornas**
Fixes: #8407

## Description
The S3 layer receives encrypted size in ObjectInfo. The response headers decrypts the size correctly before sending the response in case of encrypted objects. This is not being done consistently for notification events. 

This change is needed for compressed objects also.

This PR fixes this by letting the notification.go  Send() and setObjectHeaders() in api-headers.go get the actual size before sending to client.

## How to test this PR?
Set auto encryption on and start minio server with webhook setup to receive all notifications. 
Do `mc cp`, stat and cat operations.
The size of the object received by the webhook server should be actual size of object, not the encrypted size.

## Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [ ] Fixes a regression (If yes, please add `commit-id` or `PR #` here)
- [ ] Documentation needed
- [ ] Unit tests needed
- [ ] Functional tests needed (If yes, add [mint](https://github.com/minio/mint) PR # here: )

### CODE REVIEW

**Comment by minio-ops** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-compression-xl.sh | :heavy_check_mark: |
| mint-compression-dist-xl.sh | :heavy_check_mark: |
| mint-compression-fs.sh | :heavy_check_mark: |
| mint-worm.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-dist-xl.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-xl.sh | :x: [more...](#c194ff05-9b89-414a-b44f-97f2b7499d3f) |
| mint-large-bucket.sh | :x: [more...](#10415b4f-7d52-4f23-820f-ab849b96ce50) |
<a name="c194ff05-9b89-414a-b44f-97f2b7499d3f"></a>
### 8418-17e373f/mint-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.55:31408
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 3df4cab37a44:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... FAILED in 6 minutes and 6 seconds
{
  "alert": "",
  "args": {
    "bucketName": "aws-sdk-go-test-rk9glnq2r2y9dt",
    "expiry": 60000000000,
    "objectName": "presignedTest"
  },
  "duration": 365557,
  "error": "XMinioServerNotInitialized: Server not initialized, please try again.\n\tstatus code: 503, request id: 15CEDB39A162C087, host id: ",
  "function": "PresignedPut",
  "message": "AWS SDK Go CreateBucket Failed",
  "name": "aws-sdk-go",
  "status": "FAIL"
}

Executed 0 out of 14 tests successfully.
```
<a name="10415b4f-7d52-4f23-820f-ab849b96ce50"></a>
### 8418-17e373f/mint-large-bucket.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.56:31686
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 0b4de3d856d7:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 7 seconds
(2/14) Running aws-sdk-java tests ... done in 1 seconds
(3/14) Running aws-sdk-php tests ... done in 55 seconds
(4/14) Running aws-sdk-ruby tests ... done in 17 seconds
(5/14) Running awscli tests ... done in 2 minutes and 38 seconds
(6/14) Running healthcheck tests ... done in 0 seconds
(7/14) Running mc tests ... done in 1 minutes and 18 seconds
(8/14) Running minio-dotnet tests ... done in 1 minutes and 31 seconds
(9/14) Running minio-go tests ... FAILED in 4 minutes and 27 seconds
{
  "args": {},
  "duration": 99387,
  "error": "Please reduce your request",
  "function": "testStorageClassMetadataCopyObject()",
  "message": "CopyObject failed on RRS",
  "name": "minio-go: testStorageClassMetadataCopyObject",
  "status": "FAIL"
}

Executed 8 out of 14 tests successfully.
```
{"name": "8418-17e373f", "full_size": 34544195, "images": [{"size": 34544195, "architecture": "amd64", "variant": null, "features": null, "os": "linux", "os_version": null, "os_features": null}], "id": 73108793, "repository": 757613, "creator": 21164, "last_updater": 21164, "last_updated": "2019-10-18T21:08:24.115390Z", "image_id": null, "v2": true}Error: No such image: minio/minio:8418-17e373f

**Comment by minio-ops** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-compression-xl.sh | :heavy_check_mark: |
| mint-xl.sh | :heavy_check_mark: |
| mint-compression-fs.sh | :heavy_check_mark: |
| mint-worm.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-dist-xl.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :x: [more...](#2127f879-32e8-44e5-a544-f48310d3203b) |
| mint-compression-dist-xl.sh | :x: [more...](#07c81a99-d74a-4318-8f03-fd01e21b7918) |
<a name="2127f879-32e8-44e5-a544-f48310d3203b"></a>
### 8418-2957486/mint-large-bucket.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.61:31939
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp d606c07a9329:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 3 seconds
(2/14) Running aws-sdk-java tests ... done in 2 seconds
(3/14) Running aws-sdk-php tests ... done in 50 seconds
(4/14) Running aws-sdk-ruby tests ... done in 15 seconds
(5/14) Running awscli tests ... done in 1 minutes and 26 seconds
(6/14) Running healthcheck tests ... done in 0 seconds
(7/14) Running mc tests ... done in 1 minutes and 47 seconds
(8/14) Running minio-dotnet tests ... done in 2 minutes and 3 seconds
(9/14) Running minio-go tests ... FAILED in 5 minutes and 26 seconds
{
  "args": {},
  "duration": 118523,
  "error": "Please reduce your request",
  "function": "testStorageClassMetadataCopyObject()",
  "message": "CopyObject failed on RRS",
  "name": "minio-go: testStorageClassMetadataCopyObject",
  "status": "FAIL"
}

Executed 8 out of 14 tests successfully.
```
<a name="07c81a99-d74a-4318-8f03-fd01e21b7918"></a>
### 8418-2957486/mint-compression-dist-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.59:31291
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 24642901e207:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 1 seconds
(2/14) Running aws-sdk-java tests ... done in 1 seconds
(3/14) Running aws-sdk-php tests ... done in 44 seconds
(4/14) Running aws-sdk-ruby tests ... done in 7 seconds
(5/14) Running awscli tests ... done in 2 minutes and 1 seconds
(6/14) Running healthcheck tests ... done in 0 seconds
(7/14) Running mc tests ... done in 1 minutes and 6 seconds
(8/14) Running minio-dotnet tests ... done in 49 seconds
(9/14) Running minio-go tests ... done in 1 minutes and 17 seconds
(10/14) Running minio-java tests ... done in 1 minutes and 40 seconds
(11/14) Running minio-js tests ... done in 55 seconds
(12/14) Running minio-py tests ... FAILED in 3 minutes and 23 seconds
{
  "status": "FAIL",
  "duration": 112,
  "message": "'content-language'",
  "name": "minio-py:test_presigned_get_object_response_headers",
  "function": "presigned_get_object(bucket_name, object_name, expires, response_headers, request_date)",
  "error": "Traceback (most recent call last):\n  File \"/mint/run/core/minio-py/tests.py\", line 1396, in test_presigned_get_object_response_headers\n    returned_content_language = response.headers['Content-Language']\n  File \"/usr/local/lib/python3.5/dist-packages/urllib3/_collections.py\", line 156, in __getitem__\n    val = self._container[key.lower()]\nKeyError: 'content-language'\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"/mint/run/core/minio-py/tests.py\", line 2039, in main\n    test_presigned_get_object_response_headers(client, log_output)\n  File \"/mint/run/core/minio-py/tests.py\", line 1414, in test_presigned_get_object_response_headers\n    raise Exception(err)\nException: 'content-language'\n",
  "args": {
    "bucket_name": "minio-py-test-e85ad02a-a0cb-49f4-8b15-9ac731d41608",
    "object_name": "75ed59c0-2799-4636-ac99-4ddbcf2049ea",
    "presigned_get_object_url": "http://72.28.97.59:31291/minio-py-test-e85ad02a-a0cb-49f4-8b15-9ac731d41608/75ed59c0-2799-4636-ac99-4ddbcf2049ea?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=minio%2F20191018%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20191018T221120Z&X-Amz-Expires=5&X-Amz-SignedHeaders=host&response-content-language=en_US&response-content-type=text%2Fplain&X-Amz-Signature=8e3a2c4732fa9a8847a8d4987993fada7f56afa17f593ffc79ba22846d5c94f4"
  }
}

Executed 11 out of 14 tests successfully.
```
{"name": "8418-2957486", "full_size": 34544176, "images": [{"size": 34544176, "architecture": "amd64", "variant": null, "features": null, "os": "linux", "os_version": null, "os_features": null}], "id": 73112275, "repository": 757613, "creator": 21164, "last_updater": 21164, "last_updated": "2019-10-18T21:40:51.837338Z", "image_id": null, "v2": true}Error: No such image: minio/minio:8418-2957486

**Review by harshavardhana — APPROVED** [review]

File: cmd/notification.go [hunk 1]
```diff
@@ -1168,6 +1168,17 @@ func (args eventArgs) ToEvent() event.Event {
 func sendEvent(args eventArgs) {
 
 	// remove sensitive encryption entries in metadata.
+	switch {
+	case crypto.IsEncrypted(args.Object.UserDefined):
+		if totalObjectSize, err := args.Object.DecryptedSize(); err == nil {
+			args.Object.Size = totalObjectSize
+		}
+	case args.Object.IsCompressed():
+		if totalObjectSize := args.Object.GetActualSize(); totalObjectSize >= 0 {
```
Comment (harshavardhana) [inline cmd/notification.go]: This type of code is not useful @poornas 

```
args.Object.Size = args.Object.GetActualSize()
```

is enough

**Review by harshavardhana — CHANGES_REQUESTED** [review]

**Comment by minio-ops** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-xl.sh | :heavy_check_mark: |
| mint-compression-dist-xl.sh | :heavy_check_mark: |
| mint-compression-fs.sh | :heavy_check_mark: |
| mint-worm.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-compression-xl.sh | :x: [more...](#06acacaf-20e1-4ac8-97d2-d07442c342e3) |
| mint-large-bucket.sh | :x: [more...](#78ebd5ee-5115-4572-bea7-aac16c044818) |
| mint-dist-xl.sh | :x: [more...](#ac44f7b3-4e14-4cc3-9cd2-06abd40997b0) |
<a name="ac44f7b3-4e14-4cc3-9cd2-06abd40997b0"></a>
### 8418-db4c581/mint-dist-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.55:30493
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 58091383992b:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 0 seconds
(2/14) Running aws-sdk-java tests ... done in 1 seconds
(3/14) Running aws-sdk-php tests ... done in 44 seconds
(4/14) Running aws-sdk-ruby tests ... done in 3 seconds
(5/14) Running awscli tests ... done in 2 minutes and 7 seconds
(6/14) Running healthcheck tests ... done in 0 seconds
(7/14) Running mc tests ... done in 58 seconds
(8/14) Running minio-dotnet tests ... done in 43 seconds
(9/14) Running minio-go tests ... done in 1 minutes and 10 seconds
(10/14) Running minio-java tests ... done in 1 minutes and 55 seconds
(11/14) Running minio-js tests ... done in 58 seconds
(12/14) Running minio-py tests ... FAILED in 3 minutes and 32 seconds
{
  "function": "presigned_get_object(bucket_name, object_name, expires, response_headers, request_date)",
  "duration": 96,
  "error": "Traceback (most recent call last):\n  File \"/mint/run/core/minio-py/tests.py\", line 1341, in test_presigned_get_object_expiry_5sec\n    object_name).get_exception()\nminio.error.AccessDenied: AccessDenied: message: Access Denied\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"/mint/run/core/minio-py/tests.py\", line 2036, in main\n    test_presigned_get_object_expiry_5sec(client, log_output)\n  File \"/mint/run/core/minio-py/tests.py\", line 1355, in test_presigned_get_object_expiry_5sec\n    raise Exception(err)\nException: AccessDenied: message: Access Denied\n",
  "name": "minio-py:test_presigned_get_object_expiry_5sec",
  "args": {
    "object_name": "f528e80b-1672-45d5-8dd5-6ad963ffb6e5",
    "response.reason": "Forbidden",
    "presigned_get_object_url": "http://72.28.97.55:30493/minio-py-test-1a109ff0-a571-4b0c-97be-451c54c55df0/f528e80b-1672-45d5-8dd5-6ad963ffb6e5?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=minio%2F20191018%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20191018T224329Z&X-Amz-Expires=5&X-Amz-SignedHeaders=host&X-Amz-Signature=c032015c3e16e6d7b6a0a68d739b07166028e95e2e70203dc5640c5247a0ccfa",
    "response._body": "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<Error><Code>AccessDenied</Code><Message>Request has expired</Message><Key>f528e80b-1672-45d5-8dd5-6ad963ffb6e5</Key><BucketName>minio-py-test-1a109ff0-a571-4b0c-97be-451c54c55df0</BucketName><Resource>/minio-py-test-1a109ff0-a571-4b0c-97be-451c54c55df0/f528e80b-1672-45d5-8dd5-6ad963ffb6e5</Resource><RequestId>15CEDF197B1DB8A0</RequestId><HostId>1f3edb45-7053-4099-b254-72b16229f616</HostId></Error>",
    "bucket_name": "minio-py-test-1a109ff0-a571-4b0c-97be-451c54c55df0",
    "response.headers": "{\"_container\": {\"accept-ranges\": [\"Accept-Ranges\", \"bytes\"], \"content-length\": [\"Content-Length\", \"440\"], \"content-security-policy\": [\"Content-Security-Policy\", \"block-all-mixed-content\"], \"content-type\": [\"Content-Type\", \"application/xml\"], \"server\": [\"Server\", \"MinIO/DEVELOPMENT.2019-10-18T22-12-33Z\"], \"vary\": [\"Vary\", \"Origin\"], \"x-amz-request-id\": [\"X-Amz-Request-Id\", \"15CEDF197B1DB8A0\"], \"x-xss-protection\": [\"X-Xss-Protection\", \"1; mode=block\"], \"date\": [\"Date\", \"Fri, 18 Oct 2019 22:43:40 GMT\"]}}",
    "response.status": 403
  },
  "message": "AccessDenied: message: Access Denied",
  "status": "FAIL"
}

Executed 11 out of 14 tests successfully.
```
<a name="78ebd5ee-5115-4572-bea7-aac16c044818"></a>
### 8418-db4c581/mint-large-bucket.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.56:31992
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp e40056547a42:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 3 seconds
(2/14) Running aws-sdk-java tests ... done in 1 seconds
(3/14) Running aws-sdk-php tests ... done in 55 seconds
(4/14) Running aws-sdk-ruby tests ... done in 16 seconds
(5/14) Running awscli tests ... done in 1 minutes and 41 seconds
(6/14) Running healthcheck tests ... done in 0 seconds
(7/14) Running mc tests ... done in 1 minutes and 24 seconds
(8/14) Running minio-dotnet tests ... done in 1 minutes and 33 seconds
(9/14) Running minio-go tests ... FAILED in 4 minutes and 19 seconds
{
  "args": {},
  "duration": 77764,
  "error": "Please reduce your request",
  "function": "testStorageClassMetadataCopyObject()",
  "message": "CopyObject failed on RRS",
  "name": "minio-go: testStorageClassMetadataCopyObject",
  "status": "FAIL"
}

Executed 8 out of 14 tests successfully.
```
<a name="06acacaf-20e1-4ac8-97d2-d07442c342e3"></a>
### 8418-db4c581/mint-compression-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.51:30179
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 28eda9c607aa:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 1 seconds
(2/14) Running aws-sdk-java tests ... done in 1 seconds
(3/14) Running aws-sdk-php tests ... done in 42 seconds
(4/14) Running aws-sdk-ruby tests ... done in 2 seconds
(5/14) Running awscli tests ... done in 59 seconds
(6/14) Running healthcheck tests ... done in 0 seconds
(7/14) Running mc tests ... done in 58 seconds
(8/14) Running minio-dotnet tests ... done in 24 seconds
(9/14) Running minio-go tests ... done in 1 minutes and 10 seconds
(10/14) Running minio-java tests ... done in 21 seconds
(11/14) Running minio-js tests ... FAILED in 16 seconds
{
  "name": "minio-js",
  "function": "fGetObject(bucketName, objectName, filePath, callback)",
  "args": "bucketName:minio-js-test-a9891b6c-3622-4031-a3ec-db31a62e416d, objectName:datafile-65-MB, filePath:/tmp/datafile-65-MB.download",
  "duration": 975,
  "status": "FAIL",
  "error": "Error: Size mismatch between downloaded file and the object at /mint/run/core/minio-js/node_modules/minio/dist/main/minio.js:965:12 at nextTask (node_modules/minio/node_modules/async/dist/async.js:4578:13) at next (node_modules/minio/node_modules/async/dist/async.js:4586:13) at /mint/run/core/minio-js/node_modules/minio/node_modules/async/dist/async.js:325:20 at FSReqWrap.oncomplete (fs.js:123:15)"
}

Executed 10 out of 14 tests successfully.
```
{"name": "8418-db4c581", "full_size": 34544190, "images": [{"size": 34544190, "architecture": "amd64", "variant": null, "features": null, "os": "linux", "os_version": null, "os_features": null}], "id": 73114935, "repository": 757613, "creator": 21164, "last_updater": 21164, "last_updated": "2019-10-18T22:13:21.321639Z", "image_id": null, "v2": true}Error: No such image: minio/minio:8418-db4c581

**Review by kannappanr — APPROVED** [review]

**Comment by minio-ops** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-compression-xl.sh | :heavy_check_mark: |
| mint-xl.sh | :heavy_check_mark: |
| mint-compression-dist-xl.sh | :heavy_check_mark: |
| mint-compression-fs.sh | :heavy_check_mark: |
| mint-worm.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-dist-xl.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :x: [more...](#6b207a47-4752-419b-bf48-7bf952beb3f4) |
<a name="6b207a47-4752-419b-bf48-7bf952beb3f4"></a>
### 8418-91521a7/mint-large-bucket.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.59:32723
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp eb8760b02e75:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 2 seconds
(2/14) Running aws-sdk-java tests ... done in 1 seconds
(3/14) Running aws-sdk-php tests ... done in 55 seconds
(4/14) Running aws-sdk-ruby tests ... done in 14 seconds
(5/14) Running awscli tests ... done in 2 minutes and 30 seconds
(6/14) Running healthcheck tests ... done in 0 seconds
(7/14) Running mc tests ... done in 1 minutes and 23 seconds
(8/14) Running minio-dotnet tests ... done in 1 minutes and 31 seconds
(9/14) Running minio-go tests ... FAILED in 4 minutes and 53 seconds
{
  "args": {},
  "duration": 98441,
  "error": "Please reduce your request",
  "function": "testStorageClassMetadataCopyObject()",
  "message": "CopyObject failed on RRS",
  "name": "minio-go: testStorageClassMetadataCopyObject",
  "status": "FAIL"
}

Executed 8 out of 14 tests successfully.
```
Error: No such image: minio/minio:8418-91521a7

File: cmd/notification.go (hunk 1 above)
Comment (poornas) [reply cmd/notification.go]: done

**Review by harshavardhana — APPROVED** [review]
