### PR TITLE
Copy metadata before spawning goroutine + prealloc maps

### LINKED ISSUE #10426: fatal error: concurrent map iteration and map write
With cache enabled, on Windows, with the newest version, `minio.RELEASE.2020-09-05T07-14-49Z`, minio crashes with `fatal error: concurrent map iteration and map write`.

## Expected Behavior
Run without crashing.

## Current Behavior
Under some load of uploading multiple files, using multipart uploads, it will crash after some time (less than 30 minutes).

```
fatal error: concurrent map iteration and map write

goroutine 23463 [running]:
runtime.throw(0x1d8fbcd, 0x26)
	runtime/panic.go:1116 +0x79 fp=0xc000523af0 sp=0xc000523ac0 pc=0x4386f9
runtime.mapiternext(0xc000523bd0)
	runtime/map.go:853 +0x559 fp=0xc000523b70 sp=0xc000523af0 pc=0x410659
github.com/minio/minio/cmd.getMetadata(0xc000f3eac0, 0x7, 0xc000f3eac8, 0x31, 0x186fc0a8, 0xed6e6dd42, 0x3575980, 0x24482, 0x0, 0xc0027acc30, ...)
	github.com/minio/minio/cmd/disk-cache.go:178 +0x1e0 fp=0xc000523c40 sp=0xc000523b70 pc=0x1531fb0
github.com/minio/minio/cmd.(*cacheObjects).GetObjectNInfo.func2(0xc000331d60, 0x21619a0, 0xc000e946c0, 0xc000f3eac0, 0x7, 0xc000f3eac8, 0x31, 0xc0005e8030, 0xc000e0e000, 0xc0005e8038)
	github.com/minio/minio/cmd/disk-cache.go:341 +0xfc fp=0xc000523f90 sp=0xc000523c40 pc=0x16fe91c
runtime.goexit()
	runtime/asm_amd64.s:1373 +0x1 fp=0xc000523f98 sp=0xc000523f90 pc=0x469c81
created by github.com/minio/minio/cmd.(*cacheObjects).GetObjectNInfo
	github.com/minio/minio/cmd/disk-cache.go:337 +0xa69
```

## Possible Solution
N/A

## Steps to Reproduce (for bugs)

1. Enable caching on Windows.
2. Upload many files via multi-part upload.
3. Mix-in some downloads.

The `mc admin obd` command fails to download a report, but doesn't crash minio.
Running the warp benchmark locally and on the server didn't cause the fault.

## Context
N/A

## Regression
Yes.

It was working for months with a local build of 2af3004409f46e083855451c9b97f592d8fb1263. I also tested on the next released version, `RELEASE.2020-06-01T17-28-03Z`, which did work. `RELEASE.2020-07-02T00-15-09Z` also worked.

A more recent build, `RELEASE.2020-08-08T04-50-06Z` had the same fatal error with a similar call-stack.

## Your Environment

* Version used (`minio --version`): RELEASE.2020-09-05T07-14-49Z
* Server setup and configuration: The object storage is on a network drive and the remote file-system does occasionally error/timeout with access denied or file not found when completing the multi-part uploads. Retrying always worked and this was not crashing minio.
* Operating System and version (`uname -a`): Windows Server 2016

Hopefully the error log is enough to track the issue down: [minio-service.err.log](https://github.com/minio/minio/files/5179820/minio-service.err.log)

Nothing unexpected occurred in the normal output log: [minio-service.out.log](https://github.com/minio/minio/files/5179835/minio-service.out.log)

### PR DESCRIPTION
**Pull request by klauspost**
## Description

In `(*cacheObjects).GetObjectNInfo` copy the metadata before spawning a goroutine.

Clean up a `map[string]string` allocations and copies as well, reducing allocs and simplifying the code.

Fixes #10426  (even more)

## Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)

### CODE REVIEW

**Comment by minio-trusted** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-zoned.sh | :heavy_check_mark: |
| mint-fs.sh | :x: [more...](#e659a1f1-4ded-4f29-93b3-cf800faba16f) |
| mint-gateway-s3.sh | :x: [more...](#1333e361-19ff-4f06-b224-a9b82b33db78) |
| mint-gateway-azure.sh | :x: [more...](#c266b7a7-47ed-4898-b998-43e8b0210623) |
| mint-erasure.sh | :x: [more...](#823dc356-ffb5-4075-b16f-4354943ad555) |
| mint-dist-erasure.sh | :x: [more...](#b92ecae6-8248-4638-bf8d-9e86461d35bc) |
| mint-gateway-nas.sh | :x: [more...](#037b181d-11d4-4773-ba97-f89b0c20223d) |
<a name="b92ecae6-8248-4638-bf8d-9e86461d35bc"></a>
### 10458-34bffe8/mint-dist-erasure.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-dev4.minio.io:30113
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 9ef48df18f6e:/mint/log /tmp/mint-logs'

(1/15) Running aws-sdk-go tests ... done in 2 seconds
(2/15) Running aws-sdk-java tests ... done in 1 seconds
(3/15) Running aws-sdk-php tests ... FAILED in 16 minutes and 31 seconds
{
  "name": "aws-sdk-php",
  "function": "getBucketPolicy ( array $params = [] )",
  "args": {
    "Bucket": "aws-sdk-php-5f5a1ed8d6d1c"
  },
  "duration": "987105",
  "status": "FAIL",
  "error": "Error executing \"CreateBucket\" on \"http://minio-dev4.minio.io:30113/aws-sdk-php-5f5a1ed8d6d1c\"; AWS HTTP error: Client error: `PUT http://minio-dev4.minio.io:30113/aws-sdk-php-5f5a1ed8d6d1c` resulted in a `403 Forbidden` response:\n<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<Error><Code>RequestTimeTooSkewed</Code><Message>The difference between the reque (truncated...)\n RequestTimeTooSkewed (client): The difference between the request time and the server's time is too large. - <?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<Error><Code>RequestTimeTooSkewed</Code><Message>The difference between the request time and the server&#39;s time is too large.</Message><Resource>/aws-sdk-php-5f5a1ed8d6d1c</Resource><RequestId></RequestId><HostId>dd385d93-e6d2-4a81-ad33-3a0cd4e5b8b2</HostId></Error>"
}
(3/15) Running aws-sdk-ruby tests ... done in 3 seconds
(4/15) Running awscli tests ... done in 2 minutes and 8 seconds
(5/15) Running healthcheck tests ... done in 0 seconds
(6/15) Running mc tests ... done in 27 seconds
(7/15) Running minio-dotnet tests ... done in 36 seconds
(8/15) Running minio-go tests ... done in 1 minutes and 16 seconds
(9/15) Running minio-java tests ... done in 57 seconds
(10/15) Running minio-js tests ... done in 47 seconds
(11/15) Running minio-py tests ... done in 2 minutes and 33 seconds
(12/15) Running s3cmd tests ... done in 19 seconds
(13/15) Running s3select tests ... done in 6 seconds
(14/15) Running security tests ... done in 0 seconds

Executed 14 out of 15 tests successfully.
```
<a name="e659a1f1-4ded-4f29-93b3-cf800faba16f"></a>
### 10458-34bffe8/mint-fs.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-c3.minio.io:32516
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 92808bd53529:/mint/log /tmp/mint-logs'

(1/15) Running aws-sdk-go tests ... done in 0 seconds
(2/15) Running aws-sdk-java tests ... done in 2 seconds
(3/15) Running aws-sdk-php tests ... done in 41 seconds
(4/15) Running aws-sdk-ruby tests ... done in 1 seconds
(5/15) Running awscli tests ... FAILED in 10 seconds
{"name": "awscli", "duration": 6778, "function": "aws --endpoint-url http://minio-c3.minio.io:32516 s3api put-object --body /mint/data/datafile-1-kB --bucket awscli-mint-test-bucket-27737 --key datafile-1-kB\n", "status": "FAIL", "error": "Could not connect to the endpoint URL: "http://minio-c3.minio.io:32516/awscli-mint-test-bucket-27737/datafile-1-kB""}
(5/15) Running healthcheck tests ... done in 0 seconds
(6/15) Running mc tests ... done in 19 seconds
(7/15) Running minio-dotnet tests ... done in 28 seconds
(8/15) Running minio-go tests ... done in 53 seconds
(9/15) Running minio-java tests ... done in 18 seconds
(10/15) Running minio-js tests ... done in 47 seconds
(11/15) Running minio-py tests ... done in 1 minutes and 23 seconds
(12/15) Running s3cmd tests ... done in 21 seconds
(13/15) Running s3select tests ... done in 3 seconds
(14/15) Running security tests ... done in 0 seconds

Executed 14 out of 15 tests successfully.
```
<a name="823dc356-ffb5-4075-b16f-4354943ad555"></a>
### 10458-34bffe8/mint-erasure.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-dev8.minio.io:30189
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 296e9e67c698:/mint/log /tmp/mint-logs'

(1/15) Running aws-sdk-go tests ... FAILED in 0 seconds
{
  "alert": "",
  "args": {
    "bucketName": "aws-sdk-go-test-x2bxkipr3jbtqn",
    "expiry": 60000000000,
    "objectName": "presignedTest"
  },
  "duration": 396,
  "error": "RequestError: send request failed\ncaused by: Put \"http://minio-dev8.minio.io:30189/aws-sdk-go-test-x2bxkipr3jbtqn\": dial tcp 72.28.97.61:30189: connect: connection refused",
  "function": "PresignedPut",
  "message": "AWS SDK Go CreateBucket Failed",
  "name": "aws-sdk-go",
  "status": "FAIL"
}
(1/15) Running aws-sdk-java tests ... done in 2 seconds
(2/15) Running aws-sdk-php tests ... done in 41 seconds
(3/15) Running aws-sdk-ruby tests ... done in 3 seconds
(4/15) Running awscli tests ... done in 1 minutes and 11 seconds
(5/15) Running healthcheck tests ... done in 0 seconds
(6/15) Running mc tests ... done in 37 seconds
(7/15) Running minio-dotnet tests ... done in 43 seconds
(8/15) Running minio-go tests ... done in 1 minutes and 25 seconds
(9/15) Running minio-java tests ... done in 53 seconds
(10/15) Running minio-js tests ... done in 51 seconds
(11/15) Running minio-py tests ... done in 2 minutes and 30 seconds
(12/15) Running s3cmd tests ... done in 24 seconds
(13/15) Running s3select tests ... done in 3 seconds
(14/15) Running security tests ... done in 0 seconds

Executed 14 out of 15 tests successfully.
```
<a name="1333e361-19ff-4f06-b224-a9b82b33db78"></a>
### 10458-34bffe8/mint-gateway-s3.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-c3.minio.io:31593
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp c817613822c7:/mint/log /tmp/mint-logs'

(1/15) Running aws-sdk-go tests ... done in 1 seconds
(2/15) Running aws-sdk-java tests ... done in 2 seconds
(3/15) Running aws-sdk-php tests ... done in 42 seconds
(4/15) Running aws-sdk-ruby tests ... done in 2 seconds
(5/15) Running awscli tests ... FAILED in 16 seconds
{
  "name": "awscli",
  "duration": 8936,
  "function": "aws --endpoint-url http://minio-c3.minio.io:31593 s3api put-object --bucket awscli-mint-test-bucket-11268 --key prefix/directory/\n",
  "status": "FAIL",
  "error": "An error occurred (NoSuchBucket) when calling the PutObject operation: The specified bucket does not exist"
}
(5/15) Running healthcheck tests ... done in 0 seconds
(6/15) Running mc tests ... done in 25 seconds
(7/15) Running minio-dotnet tests ... done in 32 seconds
(8/15) Running minio-go tests ... done in 1 minutes and 29 seconds
(9/15) Running minio-java tests ... done in 1 minutes and 29 seconds
(10/15) Running minio-js tests ... done in 52 seconds
(11/15) Running minio-py tests ... done in 2 minutes and 18 seconds
(12/15) Running s3cmd tests ... done in 1 minutes and 14 seconds
(13/15) Running s3select tests ... done in 8 seconds
(14/15) Running security tests ... done in 0 seconds

Executed 14 out of 15 tests successfully.
```
<a name="c266b7a7-47ed-4898-b998-43e8b0210623"></a>
### 10458-34bffe8/mint-gateway-azure.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-dev7.minio.io:31231
ACCESS_KEY:           minioazure
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 32020cd52626:/mint/log /tmp/mint-logs'

(1/15) Running aws-sdk-go tests ... done in 8 seconds
(2/15) Running aws-sdk-java tests ... done in 1 seconds
(3/15) Running aws-sdk-php tests ... done in 1 minutes and 10 seconds
(4/15) Running aws-sdk-ruby tests ... done in 18 seconds
(5/15) Running awscli tests ... FAILED in 44 seconds
{
  "name": "awscli",
  "duration": 4055,
  "function": "aws --endpoint-url http://minio-dev7.minio.io:31231 s3api copy-object --bucket awscli-mint-test-bucket-15643 --key datafile-1-kB-copy --copy-source awscli-mint-test-bucket-15643/datafile-1-kB\n",
  "status": "FAIL",
  "error": "Hash mismatch expected a861ac626e0bee4421a50737c581233c, got 0x8D8558715AE2B11-1"
}
(5/15) Running healthcheck tests ... done in 1 seconds
(6/15) Running mc tests ... done in 3 minutes and 32 seconds
(7/15) Running minio-dotnet tests ... done in 1 minutes and 34 seconds
(8/15) Running minio-go tests ... done in 5 minutes and 51 seconds
(9/15) Running minio-java tests ... done in 7 minutes and 33 seconds
(10/15) Running minio-js tests ... done in 2 minutes and 35 seconds
(11/15) Running minio-py tests ... done in 13 minutes and 27 seconds
(12/15) Running s3cmd tests ... done in 2 minutes and 13 seconds
(13/15) Running s3select tests ... FAILED in 1 minutes and 13 seconds
{
  "name": "s3select:test_csv_input_quote_char",
  "function": "select_object_content(bucket_name, object_name, opts)",
  "args": {
    "bucket_name": "s3select-test-eed43af1-4635-4122-85da-7d887ab2e08b"
  },
  "duration": 72920,
  "message": "Test test_9 unexpectedly failed with: 'event-type'",
  "error": "Traceback (most recent call last):\n  File \"/mint/run/core/s3select/csv.py\", line 39, in test_sql_api\n    for d in data.stream(10*1024):\n  File \"/usr/local/lib/python3.6/dist-packages/minio/select/reader.py\", line 211, in stream\n    message = self.__extract_message()\n  File \"/usr/local/lib/python3.6/dist-packages/minio/select/reader.py\", line 161, in __extract_message\n    event_type = header_map[\"event-type\"]\nKeyError: 'event-type'\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"./tests.py\", line 52, in main\n    test_csv_input_custom_quote_char(client, log_output)\n  File \"/mint/run/core/s3select/csv.py\", line 119, in test_csv_input_custom_quote_char\n    data, sql_opts, expected_output)\n  File \"/mint/run/core/s3select/csv.py\", line 45, in test_sql_api\n    'Test {} unexpectedly failed with: {}'.format(test_name, select_err))\nValueError: Test test_9 unexpectedly failed with: 'event-type'\n",
  "status": "FAIL"
}
(13/15) Running security tests ... done in 0 seconds

Executed 13 out of 15 tests successfully.
```
<a name="037b181d-11d4-4773-ba97-f89b0c20223d"></a>
### 10458-34bffe8/mint-gateway-nas.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-dev7.minio.io:30972
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 22f1ceaf5e02:/mint/log /tmp/mint-logs'

(1/15) Running aws-sdk-go tests ... done in 1 seconds
(2/15) Running aws-sdk-java tests ... done in 1 seconds
(3/15) Running aws-sdk-php tests ... FAILED in 41 seconds
PHP Warning:  strtolower() expects parameter 1 to be string, array given in /mint/run/core/aws-sdk-php/quick-tests.php on line 189
PHP Warning:  strtolower() expects parameter 1 to be string, array given in /mint/run/core/aws-sdk-php/quick-tests.php on line 189
PHP Warning:  strtolower() expects parameter 1 to be string, array given in /mint/run/core/aws-sdk-php/quick-tests.php on line 189
PHP Warning:  strtolower() expects parameter 1 to be string, array given in /mint/run/core/aws-sdk-php/quick-tests.php on line 189
PHP Fatal error:  Uncaught exception 'Aws\S3\Exception\S3Exception' with message 'Error executing "DeleteObject" on "http://minio-dev7.minio.io:30972/aws-sdk-php-5f5a1ed7a9459/obj1"; AWS HTTP error: Client error: `DELETE http://minio-dev7.minio.io:30972/aws-sdk-php-5f5a1ed7a9459/obj1` resulted in a `404 Not Found` response:
<?xml version="1.0" encoding="UTF-8"?>
<Error><Code>NoSuchBucket</Code><Message>The specified bucket does not exist</Mes (truncated...)
 NoSuchBucket (client): The specified bucket does not exist - <?xml version="1.0" encoding="UTF-8"?>
<Error><Code>NoSuchBucket</Code><Message>The specified bucket does not exist</Message><Key>obj1</Key><BucketName>aws-sdk-php-5f5a1ed7a9459</BucketName><Resource>/aws-sdk-php-5f5a1ed7a9459/obj1</Resource><RequestId>16336C98DEB1BEC8</RequestId><HostId>71dc3172-1cd6-4e84-a6ce-dfcf30419d20</HostId></Error>'

GuzzleHttp\Exception\ClientException: Client error: `DELETE http://minio-dev7.minio.io:30972/aws-sdk-php-5f5a1ed7a9459/obj1` resulted in a `404 Not Found` response:
<?xml ve in /mint/run/core/aws-sdk-php/vendor/aws/aws-sdk-php/src/WrappedHttpHandler.php on line 195
(3/15) Running aws-sdk-ruby tests ... done in 2 seconds
(4/15) Running awscli tests ... done in 1 minutes and 3 seconds
(5/15) Running healthcheck tests ... done in 0 seconds
(6/15) Running mc tests ... done in 42 seconds
(7/15) Running minio-dotnet tests ... done in 31 seconds
(8/15) Running minio-go tests ... done in 1 minutes and 1 seconds
(9/15) Running minio-java tests ... done in 28 seconds
(10/15) Running minio-js tests ... done in 33 seconds
(11/15) Running minio-py tests ... done in 1 minutes and 17 seconds
(12/15) Running s3cmd tests ... done in 15 seconds
(13/15) Running s3select tests ... done in 2 seconds
(14/15) Running security tests ... done in 0 seconds

Executed 14 out of 15 tests successfully.
```
Deleting image on docker hub
Deleting image locally
Error: No such image: minio/minio:10458-34bffe8

**Comment by minio-trusted** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-erasure.sh | :heavy_check_mark: |
| mint-dist-erasure.sh | :heavy_check_mark: |
| mint-zoned.sh | :heavy_check_mark: |
| mint-fs.sh | :x: [more...](#708bfc06-5076-49ce-b009-8076603fd482) |
| mint-gateway-s3.sh | :x: [more...](#49bb33a7-75ae-49d4-881c-dd17acd917d9) |
| mint-gateway-azure.sh | :x: [more...](#5bbb2992-58f9-4de9-9ab5-916914a85467) |
| mint-gateway-nas.sh | :x: [more...](#76f8ff3b-8039-46da-9806-c7f3cae261f5) |
<a name="49bb33a7-75ae-49d4-881c-dd17acd917d9"></a>
### 10458-815c61c/mint-gateway-s3.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-dev7.minio.io:32657
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 7570e18126be:/mint/log /tmp/mint-logs'

(1/15) Running aws-sdk-go tests ... done in 1 seconds
(2/15) Running aws-sdk-java tests ... done in 1 seconds
(3/15) Running aws-sdk-php tests ... done in 42 seconds
(4/15) Running aws-sdk-ruby tests ... done in 3 seconds
(5/15) Running awscli tests ... FAILED in 1 minutes and 10 seconds
{
  "name": "awscli",
  "duration": 63309,
  "function": "aws --endpoint-url http://minio-dev7.minio.io:32657 s3api put-object --bucket awscli-mint-test-bucket-25678 --key prefix/directory/\n",
  "status": "FAIL",
  "error": "An error occurred (NoSuchBucket) when calling the PutObject operation: The specified bucket does not exist"
}
(5/15) Running healthcheck tests ... done in 0 seconds
(6/15) Running mc tests ... done in 30 seconds
(7/15) Running minio-dotnet tests ... done in 31 seconds
(8/15) Running minio-go tests ... done in 1 minutes and 25 seconds
(9/15) Running minio-java tests ... done in 56 seconds
(10/15) Running minio-js tests ... done in 42 seconds
(11/15) Running minio-py tests ... done in 2 minutes and 26 seconds
(12/15) Running s3cmd tests ... done in 1 minutes and 4 seconds
(13/15) Running s3select tests ... done in 4 seconds
(14/15) Running security tests ... done in 0 seconds

Executed 14 out of 15 tests successfully.
```
<a name="5bbb2992-58f9-4de9-9ab5-916914a85467"></a>
### 10458-815c61c/mint-gateway-azure.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-dev6.minio.io:30153
ACCESS_KEY:           minioazure
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 050bfb80cc0b:/mint/log /tmp/mint-logs'

(1/15) Running aws-sdk-go tests ... done in 9 seconds
(2/15) Running aws-sdk-java tests ... done in 1 seconds
(3/15) Running aws-sdk-php tests ... FAILED in 16 minutes and 49 seconds
{
  "name": "aws-sdk-php",
  "function": "getBucketPolicy ( array $params = [] )",
  "args": {
    "Bucket": "aws-sdk-php-5f5a2ad70a05f"
  },
  "duration": "980206",
  "status": "FAIL",
  "error": "Error executing \"CreateBucket\" on \"http://minio-dev6.minio.io:30153/aws-sdk-php-5f5a2ad70a05f\"; AWS HTTP error: Client error: `PUT http://minio-dev6.minio.io:30153/aws-sdk-php-5f5a2ad70a05f` resulted in a `403 Forbidden` response:\n<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<Error><Code>RequestTimeTooSkewed</Code><Message>The difference between the reque (truncated...)\n RequestTimeTooSkewed (client): The difference between the request time and the server's time is too large. - <?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<Error><Code>RequestTimeTooSkewed</Code><Message>The difference between the request time and the server&#39;s time is too large.</Message><Resource>/aws-sdk-php-5f5a2ad70a05f</Resource><RequestId></RequestId><HostId>c53ec095-7476-475d-8ca4-50652acf4575</HostId></Error>"
}
(3/15) Running aws-sdk-ruby tests ... done in 19 seconds
(4/15) Running awscli tests ... FAILED in 44 seconds
{
  "name": "awscli",
  "duration": 3952,
  "function": "aws --endpoint-url http://minio-dev6.minio.io:30153 s3api copy-object --bucket awscli-mint-test-bucket-19876 --key datafile-1-kB-copy --copy-source awscli-mint-test-bucket-19876/datafile-1-kB\n",
  "status": "FAIL",
  "error": "Hash mismatch expected a861ac626e0bee4421a50737c581233c, got 0x8D855906798EE52-1"
}
(4/15) Running healthcheck tests ... done in 1 seconds
(5/15) Running mc tests ... done in 3 minutes and 28 seconds
(6/15) Running minio-dotnet tests ... done in 1 minutes and 35 seconds
(7/15) Running minio-go tests ... done in 6 minutes and 1 seconds
(8/15) Running minio-java tests ... done in 7 minutes and 59 seconds
(9/15) Running minio-js tests ... done in 2 minutes and 35 seconds
(10/15) Running minio-py tests ... done in 13 minutes and 14 seconds
(11/15) Running s3cmd tests ... done in 2 minutes and 15 seconds
(12/15) Running s3select tests ... done in 1 minutes and 2 seconds
(13/15) Running security tests ... done in 0 seconds

Executed 13 out of 15 tests successfully.
```
<a name="708bfc06-5076-49ce-b009-8076603fd482"></a>
### 10458-815c61c/mint-fs.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-dev4.minio.io:30164
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 45e1b87df647:/mint/log /tmp/mint-logs'

(1/15) Running aws-sdk-go tests ... done in 1 seconds
(2/15) Running aws-sdk-java tests ... done in 1 seconds
(3/15) Running aws-sdk-php tests ... done in 41 seconds
(4/15) Running aws-sdk-ruby tests ... done in 2 seconds
(5/15) Running awscli tests ... FAILED in 10 seconds
{
  "name": "awscli",
  "duration": 6196,
  "function": "delete_bucket\n",
  "status": "FAIL",
  "error": "fatal error: An error occurred (NoSuchBucket) when calling the ListObjectsV2 operation: The specified bucket does not existremove_bucket failed: Unable to delete all objects in the bucket, bucket will not be deleted."
}
(5/15) Running healthcheck tests ... done in 0 seconds
(6/15) Running mc tests ... done in 17 seconds
(7/15) Running minio-dotnet tests ... done in 27 seconds
(8/15) Running minio-go tests ... done in 41 seconds
(9/15) Running minio-java tests ... done in 17 seconds
(10/15) Running minio-js tests ... done in 40 seconds
(11/15) Running minio-py tests ... done in 1 minutes and 8 seconds
(12/15) Running s3cmd tests ... done in 13 seconds
(13/15) Running s3select tests ... done in 2 seconds
(14/15) Running security tests ... done in 0 seconds

Executed 14 out of 15 tests successfully.
```
<a name="76f8ff3b-8039-46da-9806-c7f3cae261f5"></a>
### 10458-815c61c/mint-gateway-nas.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-dev4.minio.io:32390
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp f43d1d912316:/mint/log /tmp/mint-logs'

(1/15) Running aws-sdk-go tests ... done in 1 seconds
(2/15) Running aws-sdk-java tests ... done in 1 seconds
(3/15) Running aws-sdk-php tests ... FAILED in 16 minutes and 20 seconds
{
  "name": "aws-sdk-php",
  "function": "getBucketPolicy ( array $params = [] )",
  "args": {
    "Bucket": "aws-sdk-php-5f5a2ace9c536"
  },
  "duration": "979190",
  "status": "FAIL",
  "error": "Error executing \"CreateBucket\" on \"http://minio-dev4.minio.io:32390/aws-sdk-php-5f5a2ace9c536\"; AWS HTTP error: Client error: `PUT http://minio-dev4.minio.io:32390/aws-sdk-php-5f5a2ace9c536` resulted in a `403 Forbidden` response:\n<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<Error><Code>RequestTimeTooSkewed</Code><Message>The difference between the reque (truncated...)\n RequestTimeTooSkewed (client): The difference between the request time and the server's time is too large. - <?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<Error><Code>RequestTimeTooSkewed</Code><Message>The difference between the request time and the server&#39;s time is too large.</Message><Resource>/aws-sdk-php-5f5a2ace9c536</Resource><RequestId></RequestId><HostId>c1838788-c39b-448b-8a16-01b47e8f21df</HostId></Error>"
}
(3/15) Running aws-sdk-ruby tests ... done in 2 seconds
(4/15) Running awscli tests ... done in 2 minutes and 3 seconds
(5/15) Running healthcheck tests ... done in 0 seconds
(6/15) Running mc tests ... done in 18 seconds
(7/15) Running minio-dotnet tests ... done in 33 seconds
(8/15) Running minio-go tests ... done in 31 seconds
(9/15) Running minio-java tests ... done in 17 seconds
(10/15) Running minio-js tests ... done in 31 seconds
(11/15) Running minio-py tests ... done in 1 minutes and 4 seconds
(12/15) Running s3cmd tests ... done in 13 seconds
(13/15) Running s3select tests ... done in 2 seconds
(14/15) Running security tests ... done in 0 seconds

Executed 14 out of 15 tests successfully.
```
Deleting image on docker hub
Deleting image locally
Error: No such image: minio/minio:10458-815c61c

File: cmd/disk-cache.go [hunk 1]
```diff
@@ -334,11 +333,12 @@ func (c *cacheObjects) GetObjectNInfo(ctx context.Context, bucket, object string
...
+	userDefined := getMetadata(bkReader.ObjInfo)
 	go func() {
 		putErr := dcache.Put(ctx, bucket, object,
 			io.LimitReader(pipeReader, bkReader.ObjInfo.Size),
 			bkReader.ObjInfo.Size, nil, ObjectOptions{
-				UserDefined: getMetadata(bkReader.ObjInfo),
+				UserDefined: userDefined,
 			}, false)
 		// close the write end of the pipe, so the error gets
 		// propagated to getObjReader
```
Comment (ngbrown) [inline cmd/disk-cache.go:344]: Extract metadata copy before capture

File: cmd/fs-v1-multipart.go [hunk 2]
```diff
@@ -731,7 +731,7 @@ func (fs *FSObjects) CompleteMultipartUpload(ctx context.Context, bucket string,
 		return oi, toObjectErr(err, bucket, object)
 	}
 	// Save additional metadata.
-	if len(fsMeta.Meta) == 0 {
+	if fsMeta.Meta == nil {
 		fsMeta.Meta = make(map[string]string)
 	}
 	fsMeta.Meta["etag"] = s3MD5
```
Comment (ngbrown) [inline cmd/fs-v1-multipart.go:737]: check for `nil` instead of `0` length

**Review by harshavardhana — APPROVED** [review]

**Review by ngbrown — COMMENTED** [review]
Are these the only two significant changes? The rest seem to be side-effect natural improvements.

The good news is, I deployed a build from this commit (815c61c19667b9ff6eeaaeabe8f414080b616aad) and it's been working without issue for 30 minutes.

File: cmd/fs-v1-multipart.go (hunk 2 above)
Comment (harshavardhana) [reply cmd/fs-v1-multipart.go:737]: This is just cosmetic @ngbrown

File: cmd/disk-cache.go (hunk 1 above)
Comment (harshavardhana) [reply cmd/disk-cache.go:344]: This is the main change @ngbrown

**Review by poornas — APPROVED** [review]
LGTM

**Comment by minio-trusted** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-s3.sh | :heavy_check_mark: |
| mint-erasure.sh | :heavy_check_mark: |
| mint-dist-erasure.sh | :heavy_check_mark: |
| mint-zoned.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-gateway-azure.sh | :x: [more...](#8c03d402-afdc-437b-aea3-ce7d1daa83a3) |
<a name="8c03d402-afdc-437b-aea3-ce7d1daa83a3"></a>
### 10458-5e01201/mint-gateway-azure.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-dev6.minio.io:32362
ACCESS_KEY:           minioazure
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 765df1aab6a3:/mint/log /tmp/mint-logs'

(1/15) Running aws-sdk-go tests ... done in 7 seconds
(2/15) Running aws-sdk-java tests ... done in 2 seconds
(3/15) Running aws-sdk-php tests ... done in 1 minutes and 11 seconds
(4/15) Running aws-sdk-ruby tests ... done in 18 seconds
(5/15) Running awscli tests ... FAILED in 44 seconds
{
  "name": "awscli",
  "duration": 3910,
  "function": "aws --endpoint-url http://minio-dev6.minio.io:32362 s3api copy-object --bucket awscli-mint-test-bucket-4453 --key datafile-1-kB-copy --copy-source awscli-mint-test-bucket-4453/datafile-1-kB\n",
  "status": "FAIL",
  "error": "Hash mismatch expected a861ac626e0bee4421a50737c581233c, got 0x8D855B147757CD4-1"
}
(5/15) Running healthcheck tests ... done in 0 seconds
(6/15) Running mc tests ... done in 3 minutes and 49 seconds
(7/15) Running minio-dotnet tests ... done in 1 minutes and 36 seconds
(8/15) Running minio-go tests ... done in 6 minutes and 51 seconds
(9/15) Running minio-java tests ... done in 7 minutes and 58 seconds
(10/15) Running minio-js tests ... FAILED in 42 seconds
{
  "name": "minio-js",
  "function": "makeBucket(bucketName, region)",
  "args": "bucketName:minio-js-test-29936e60-2c78-468b-b698-3fa6cc38ae18-region, region:us-east-1",
  "duration": 40310,
  "status": "FAIL",
  "error": "S3Error: The specified bucket does not exist at Object.parseError (node_modules/minio/dist/main/xml-parsers.js:86:11) at /mint/run/core/minio-js/node_modules/minio/dist/main/transformers.js:156:22 at DestroyableTransform._flush (node_modules/minio/dist/main/transformers.js:80:10) at DestroyableTransform.prefinish (node_modules/readable-stream/lib/_stream_transform.js:129:10) at prefinish (node_modules/readable-stream/lib/_stream_writable.js:611:14) at finishMaybe (node_modules/readable-stream/lib/_stream_writable.js:620:5) at endWritable (node_modules/readable-stream/lib/_stream_writable.js:643:3) at DestroyableTransform.Writable.end (node_modules/readable-stream/lib/_stream_writable.js:571:22) at IncomingMessage.onend (_stream_readable.js:678:10) at endReadableNT (_stream_readable.js:1244:12) at processTicksAndRejections (internal/process/task_queues.js:80:21)"
}
(10/15) Running minio-py tests ... done in 13 minutes and 33 seconds
(11/15) Running s3cmd tests ... done in 2 minutes and 13 seconds
(12/15) Running s3select tests ... done in 1 minutes and 3 seconds
(13/15) Running security tests ... done in 0 seconds

Executed 13 out of 15 tests successfully.
```
Deleting image on docker hub
Deleting image locally
Error: No such image: minio/minio:10458-5e01201
