### PR TITLE
CopyObject: fix read/write err on closed pipe

### LINKED ISSUE #15128: CopyObject: read/write on closed pipe
Hello,

The CopyObject S3 API is failing with Minio in erasure coded mode.

## Expected Behavior
A new version of the object is created with updated metadata.

## Current Behavior
I get this error stack in the Minio log:

```
API: CopyObject
Time: Tue Jun 21 2022 08:56:55 GMT+0200 (Central European Summer Time)
DeploymentID: 3234941a-ebbb-4f7d-9133-3b56838f80cd
RequestID: 16FA96FA5C4657DF
RemoteHost: 192.168.152.12
UserAgent: Boto3/1.21.41 Python/3.10.5 Linux/4.19.0-17-cloud-amd64 Botocore/1.24.41
Error: io: read/write on closed pipe (*errors.errorString)

Backtrace: 
0: internal/logger/logger.go:278:logger.LogIf()
1: cmd/erasure-encode.go:87:cmd.(*Erasure).Encode()
2: cmd/erasure-object.go:1062:cmd.erasureObjects.putObject()
3: cmd/erasure-object.go:871:cmd.erasureObjects.PutObject()
4: cmd/erasure-sets.go:945:cmd.(*erasureSets).PutObject()
5: cmd/erasure-server-pool.go:1151:cmd.(*erasureServerPools).CopyObject()
6: cmd/object-handlers.go:1505:cmd.objectAPIHandlers.CopyObjectHandler()
7: net/http/server.go:2084:http.HandlerFunc.ServeHTTP()
```

Using the trace function I also see "Internal.ReadXL 403 Forbidden" messages that seem to be concomitant with the CopyObject call. The request return 500 to the client.

## Steps to Reproduce (for bugs)
1. Create a Minio cluster in erasure coding mode
2. Create a bucket with object lock and versioning enabled
3. Upload an object to the bucket
4. Try to use CopyObject to update the object metadata

Using Python boto3:

```
self.s3.copy_object(Key=key, Bucket=bucket_name,
                CopySource={"Key": key, "Bucket": bucket_name},
                Metadata={"ContentDisposition": 'attachment; filename*=UTF-8\'\'{}'.format(content_disposition)},
                MetadataDirective="REPLACE")
```

## Context
I use this API to copy an object on the same path while updating the metadata (Content-Dispostion). Versioning and object lock are enabled.

## Regression
This must be a regression since I has made a script that was used to update the objects metadata and it was working before. When I tried to run it again it didn't work anymore. Worked with ```2022-04-16T04-26-02Z```.

## Your Environment
* Version used (`minio --version`): ```2022-06-17T02:00:35Z```
* Server setup and configuration: 4 servers with 6 drives and EC:3
* Operating System and version (`uname -a`): ```5.10.0-14-amd64 #1 SMP Debian 5.10.113-1 (2022-04-29) x86_64 GNU/Linux```

### PR DESCRIPTION
**Pull request by poornas**
Fixes: #15128
Regression from PR#14971

## How to test this PR?
see issue description

## Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Optimization (provides speedup with no functional changes)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [x] Fixes a regression (If yes, please add `commit-id` or `PR #` here)
- [ ] Documentation updated
- [ ] Unit tests added/updated

### CODE REVIEW

File: cmd/object-handlers.go [hunk 1]
```diff
@@ -1433,10 +1433,6 @@ func (api objectAPIHandlers) CopyObjectHandler(w http.ResponseWriter, r *http.Re
 		srcInfo.metadataOnly = false
 	}
 
-	if srcInfo.metadataOnly {
-		gr.Close() // We are not interested in the reader stream at this point close it.
-	}
-
```
Comment (harshavardhana) [inline cmd/object-handlers.go:1439]: @poornas not sure why this would be true - this is expected to be closed if we are only doing metadataOnly operation - we should figure out why there is a PutObject() for metadata update.

**Review by harshavardhana — CHANGES_REQUESTED** [review]

File: cmd/object-handlers.go (hunk 1 above)
Comment (poornas) [reply cmd/object-handlers.go:1439]: For versioned objects, even metadata updates creates a new version

**Comment by minio-trusted** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-s3.sh | :heavy_check_mark: |
| mint-erasure.sh | :heavy_check_mark: |
| mint-dist-erasure.sh | :heavy_check_mark: |
| mint-compress-encrypt-dist-erasure.sh | :heavy_check_mark: |
| mint-pools.sh | :heavy_check_mark: |
Deleting image on docker hub
Deleting image locally

File: cmd/object-handlers.go (hunk 1 above)
Comment (harshavardhana) [reply cmd/object-handlers.go:1439]: Then we need to make sure to gr.Close() inside `erasure-server-pool.go` when we decide to not do PutObject() @poornas

**Review by harshavardhana — CHANGES_REQUESTED** [review]

File: cmd/erasure-server-pool.go [hunk 2]
```diff
@@ -1125,6 +1125,7 @@ func (z *erasureServerPools) CopyObject(ctx context.Context, srcBucket, srcObjec
 		// Destination is not versioned and source version ID is empty
 		// perform an in-place update.
 		if !dstOpts.Versioned && srcOpts.VersionID == "" {
+			srcInfo.Reader.Close() // We are not interested in the reader stream at this point close it.
```
Comment (harshavardhana) [inline cmd/erasure-server-pool.go]: isn't it is true for all the code that calls CopyObject() underneath?

Comment (poornas) [reply cmd/erasure-server-pool.go]: yes, but we need to do this in erasure set layer

**Comment by minio-trusted** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-s3.sh | :heavy_check_mark: |
| mint-erasure.sh | :x: [more...](#872188fc-51f6-41d6-a22d-d98f02ac5cd5) |
| mint-dist-erasure.sh | :x: [more...](#1c14b538-bf42-4b1e-821b-db2368e58e7e) |
| mint-compress-encrypt-dist-erasure.sh | :x: [more...](#1560be3d-07a1-4822-a5a2-8cc71e9523c4) |
| mint-pools.sh | :x: [more...](#48256f6c-9158-4758-9e7b-9b6f5cee5223) |
<a name="1c14b538-bf42-4b1e-821b-db2368e58e7e"></a>
### 15135-d6a0723/mint-dist-erasure.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-k8s4:31115
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0
RUN_ON_FAIL:          0

To get logs, run 'docker cp :/mint/log /tmp/mint-logs'

(1/15) Running aws-sdk-go tests ... done in 8 seconds
(2/15) Running aws-sdk-java tests ... done in 1 seconds
(3/15) Running aws-sdk-php tests ... done in 43 seconds
(4/15) Running aws-sdk-ruby tests ... done in 6 seconds
(5/15) Running awscli tests ... done in 56 seconds
(6/15) Running healthcheck tests ... done in 0 seconds
(7/15) Running mc tests ... done in 28 seconds
FAILED in 1 minutes and 51 seconds
Unhandled exception. System.AggregateException: One or more errors occurred. (A task was canceled.)
 ---> System.Threading.Tasks.TaskCanceledException: A task was canceled.
   at System.Threading.Tasks.Task.GetExceptions(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.Wait()
   at Minio.Functional.Tests.Program.Main(String[] args) in /mint/run/core/minio-dotnet/temp/Minio.Functional.Tests/Program.cs:line 123
--- End of stack trace from previous location ---

   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.Wait()
   at Minio.Functional.Tests.Program.Main(String[] args) in /mint/run/core/minio-dotnet/temp/Minio.Functional.Tests/Program.cs:line 123
(8/15) Running minio-go tests ... done in 1 minutes and 26 seconds
(9/15) Running minio-java tests ... done in 31 seconds
(10/15) Running minio-js tests ... done in 1 minutes and 6 seconds
(11/15) Running minio-py tests ... done in 1 minutes and 19 seconds
(12/15) Running s3cmd tests ... done in 24 seconds
(13/15) Running s3select tests ... done in 4 seconds
(14/15) Running versioning tests ... done in 3 minutes and 3 seconds

Executed 14 out of 15 tests successfully.
```
<a name="1560be3d-07a1-4822-a5a2-8cc71e9523c4"></a>
### 15135-d6a0723/mint-compress-encrypt-dist-erasure.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-k8s7:32548
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0
RUN_ON_FAIL:          0

To get logs, run 'docker cp :/mint/log /tmp/mint-logs'

(1/15) Running aws-sdk-go tests ... done in 8 seconds
(2/15) Running aws-sdk-java tests ... done in 2 seconds
(3/15) Running aws-sdk-php tests ... done in 43 seconds
(4/15) Running aws-sdk-ruby tests ... done in 6 seconds
(5/15) Running awscli tests ... done in 54 seconds
(6/15) Running healthcheck tests ... done in 0 seconds
(7/15) Running mc tests ... done in 26 seconds
FAILED in 2 minutes and 24 seconds
Unhandled exception. System.AggregateException: One or more errors occurred. (A task was canceled.)
 ---> System.Threading.Tasks.TaskCanceledException: A task was canceled.
   at System.Threading.Tasks.Task.GetExceptions(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.Wait()
   at Minio.Functional.Tests.Program.Main(String[] args) in /mint/run/core/minio-dotnet/temp/Minio.Functional.Tests/Program.cs:line 132
--- End of stack trace from previous location ---

   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.Wait()
   at Minio.Functional.Tests.Program.Main(String[] args) in /mint/run/core/minio-dotnet/temp/Minio.Functional.Tests/Program.cs:line 132
(8/15) Running minio-go tests ... done in 1 minutes and 16 seconds
(9/15) Running minio-java tests ... done in 34 seconds
(10/15) Running minio-js tests ... done in 1 minutes and 7 seconds
(11/15) Running minio-py tests ... done in 1 minutes and 19 seconds
(12/15) Running s3cmd tests ... done in 24 seconds
(13/15) Running s3select tests ... done in 4 seconds
(14/15) Running versioning tests ... done in 3 minutes and 4 seconds

Executed 14 out of 15 tests successfully.
```
<a name="48256f6c-9158-4758-9e7b-9b6f5cee5223"></a>
### 15135-d6a0723/mint-pools.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-k8s5:32501
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0
RUN_ON_FAIL:          0

To get logs, run 'docker cp :/mint/log /tmp/mint-logs'

(1/15) Running aws-sdk-go tests ... done in 8 seconds
(2/15) Running aws-sdk-java tests ... done in 1 seconds
(3/15) Running aws-sdk-php tests ... done in 44 seconds
(4/15) Running aws-sdk-ruby tests ... done in 7 seconds
(5/15) Running awscli tests ... done in 57 seconds
(6/15) Running healthcheck tests ... done in 0 seconds
(7/15) Running mc tests ... FAILED in 54 seconds
{
  "name": "mc",
  "duration": "22970",
  "function": "test_find",
  "status": "FAIL",
  "error": "mirror and list differs"
}
(7/15) Running minio-dotnet tests ... done in 6 minutes and 42 seconds
(8/15) Running minio-go tests ... done in 1 minutes and 40 seconds
(9/15) Running minio-java tests ... done in 36 seconds
(10/15) Running minio-js tests ... done in 1 minutes and 5 seconds
(11/15) Running minio-py tests ... done in 1 minutes and 37 seconds
(12/15) Running s3cmd tests ... done in 27 seconds
(13/15) Running s3select tests ... done in 4 seconds
(14/15) Running versioning tests ... done in 3 minutes and 5 seconds

Executed 14 out of 15 tests successfully.
```
<a name="872188fc-51f6-41d6-a22d-d98f02ac5cd5"></a>
### 15135-d6a0723/mint-erasure.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-k8s6:31146
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0
RUN_ON_FAIL:          0

To get logs, run 'docker cp :/mint/log /tmp/mint-logs'

(1/15) Running aws-sdk-go tests ... done in 7 seconds
(2/15) Running aws-sdk-java tests ... done in 1 seconds
(3/15) Running aws-sdk-php tests ... done in 43 seconds
(4/15) Running aws-sdk-ruby tests ... done in 6 seconds
(5/15) Running awscli tests ... done in 54 seconds
(6/15) Running healthcheck tests ... done in 0 seconds
(7/15) Running mc tests ... done in 24 seconds
FAILED in 2 minutes and 1 seconds
{
  "name": "minio-dotnet : PutObject_Test3",
  "function": "Task PutObjectAsync(PutObjectArgs args, CancellationToken cancellationToken = default(CancellationToken))",
  "args": {
    "bucketName": "minio-dotnet-example-ire8qczpyidjrra",
    "objectName": "&{{cada+@(",
    "contentType": "custom-contenttype",
    "size": "1MB"
  },
  "duration": 100032,
  "status": "FAIL",
  "alert": "",
  "message": "The request was canceled due to the configured HttpClient.Timeout of 100 seconds elapsing.",
  "error": "System.Threading.Tasks.TaskCanceledException: The request was canceled due to the configured HttpClient.Timeout of 100 seconds elapsing.\n ---> System.TimeoutException: The operation was canceled.\n ---> System.Threading.Tasks.TaskCanceledException: The operation was canceled.\n ---> System.IO.IOException: Unable to read data from the transport connection: Operation canceled.\n ---> System.Net.Sockets.SocketException (125): Operation canceled\n   --- End of inner exception stack trace ---\n   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)\n   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource<System.Int32>.GetResult(Int16 token)\n   at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)\n   --- End of inner exception stack trace ---\n   at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)\n   at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)\n   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)\n   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)\n   --- End of inner exception stack trace ---\n   --- End of inner exception stack trace ---\n   at System.Net.Http.HttpClient.HandleFailure(Exception e, Boolean telemetryStarted, HttpResponseMessage response, CancellationTokenSource cts, CancellationToken cancellationToken, CancellationTokenSource pendingRequestsCts)\n   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)\n   at Minio.MinioClient.ExecuteTaskCoreAsync(IEnumerable`1 errorHandlers, HttpRequestMessageBuilder requestMessageBuilder, CancellationToken cancellationToken, Boolean isSts) in /mint/run/core/minio-dotnet/temp/Minio/MinioClient.cs:line 526\n   at Minio.MinioClient.PutObjectSinglePartAsync(PutObjectArgs args, CancellationToken cancellationToken) in /mint/run/core/minio-dotnet/temp/Minio/ApiEndpoints/ObjectOperations.cs:line 1162\n   at Minio.MinioClient.PutObjectAsync(PutObjectArgs args, CancellationToken cancellationToken) in /mint/run/core/minio-dotnet/temp/Minio/ApiEndpoints/ObjectOperations.cs:line 655\n   at Minio.Functional.Tests.FunctionalTest.PutObject_Tester(MinioClient minio, String bucketName, String objectName, String fileName, String contentType, Int64 size, Dictionary`2 metaData, MemoryStream mstream) in /mint/run/core/minio-dotnet/temp/Minio.Functional.Tests/FunctionalTest.cs:line 897\n   at Minio.Functional.Tests.FunctionalTest.PutObject_Test3(MinioClient minio) in /mint/run/core/minio-dotnet/temp/Minio.Functional.Tests/FunctionalTest.cs:line 2866"
}
(8/15) Running minio-go tests ... done in 1 minutes and 13 seconds
(9/15) Running minio-java tests ... done in 20 seconds
(10/15) Running minio-js tests ... done in 1 minutes and 2 seconds
(11/15) Running minio-py tests ... done in 1 minutes and 0 seconds
(12/15) Running s3cmd tests ... done in 24 seconds
(13/15) Running s3select tests ... done in 1 seconds
(14/15) Running versioning tests ... done in 3 minutes and 2 seconds

Executed 14 out of 15 tests successfully.
```
Deleting image on docker hub
Deleting image locally

**Comment by minio-trusted** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-s3.sh | :heavy_check_mark: |
| mint-erasure.sh | :heavy_check_mark: |
| mint-dist-erasure.sh | :heavy_check_mark: |
| mint-compress-encrypt-dist-erasure.sh | :heavy_check_mark: |
| mint-pools.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :x: [more...](#eab26fc4-dcd9-47e6-bb17-89cfd3337f76) |
<a name="eab26fc4-dcd9-47e6-bb17-89cfd3337f76"></a>
### 15135-baefaa0/mint-large-bucket.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-k8s1:30558
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0
RUN_ON_FAIL:          0

To get logs, run 'docker cp :/mint/log /tmp/mint-logs'

(1/15) Running aws-sdk-go tests ... done in 8 seconds
(2/15) Running aws-sdk-java tests ... done in 1 seconds
(3/15) Running aws-sdk-php tests ... done in 44 seconds
(4/15) Running aws-sdk-ruby tests ... done in 7 seconds
(5/15) Running awscli tests ... done in 56 seconds
(6/15) Running healthcheck tests ... done in 0 seconds
(7/15) Running mc tests ... done in 30 seconds
(8/15) Running minio-dotnet tests ... done in 6 minutes and 18 seconds
(9/15) Running minio-go tests ... done in 1 minutes and 27 seconds
(10/15) Running minio-java tests ... done in 33 seconds
(11/15) Running minio-js tests ... FAILED in 54 seconds
{
  "name": "minio-js",
  "function": "\"after all\" hook for \"removeObjects(bucketName, objectsList)",
  "args": "bucketName:minio-js-test-ver-presign-0cac4df5-0b8c-4ff1-8910-be8b4c2a174b\"",
  "duration": 6,
  "status": "FAIL",
  "error": "S3Error: The bucket you tried to delete is not empty. You must delete all versions in the bucket. at Object.parseError (node_modules/minio/dist/main/xml-parsers.js:71:11) at /mint/run/core/minio-js/node_modules/minio/dist/main/transformers.js:166:22 at DestroyableTransform._flush (node_modules/minio/dist/main/transformers.js:90:10) at DestroyableTransform.prefinish (node_modules/readable-stream/lib/_stream_transform.js:129:10) at prefinish (node_modules/readable-stream/lib/_stream_writable.js:611:14) at finishMaybe (node_modules/readable-stream/lib/_stream_writable.js:620:5) at endWritable (node_modules/readable-stream/lib/_stream_writable.js:643:3) at DestroyableTransform.Writable.end (node_modules/readable-stream/lib/_stream_writable.js:571:22) at IncomingMessage.onend (internal/streams/readable.js:670:10) at endReadableNT (internal/streams/readable.js:1333:12) at processTicksAndRejections (internal/process/task_queues.js:82:21)"
}
(11/15) Running minio-py tests ... done in 1 minutes and 22 seconds
(12/15) Running s3cmd tests ... done in 25 seconds
(13/15) Running s3select tests ... done in 4 seconds
(14/15) Running versioning tests ... done in 3 minutes and 5 seconds

Executed 14 out of 15 tests successfully.
```
Deleting image on docker hub
Deleting image locally

**Review by harshavardhana — APPROVED** [review]
