### PR TITLE
Storage info in xl-sets can ignore the faulty disks

### LINKED ISSUE #2813: mc admin info crashes
## Expected behavior
`mc admin info alias` should return information on the `alias` instance
## Actual behavior
`mc admin info alias` crashes with the following stack trace (full output):

```
~> mc admin info myminioalias
●  minio0:9000
   Status : online
   Uptime : 6 hours
  Version : 2019-06-27T21:13:50Z
  Storage : Used 1.5 TiB
   Drives : 2/2 OK

●  minio1:9000
   Status : online
   Uptime : 3 hours
  Version : 2019-06-27T21:13:50Z
  Storage : Used 1.5 TiB
   Drives : 2/2 OK

panic: runtime error: index out of range

goroutine 1 [running]:
github.com/minio/mc/cmd.infoMessage.String(0x0, 0x0, 0x5558abb0c261, 0x2, 0xc00028fbe0, 0xb, 0x0, 0x0, 0xc00030cc60, 0x0, ...)
        /build/minio-client/src/go/src/github.com/minio/mc/cmd/admin-info.go:172 +0x15cc
github.com/minio/mc/cmd.printMsg(0x5558abf2e420, 0xc00055a1e0)
        /build/minio-client/src/go/src/github.com/minio/mc/cmd/print.go:30 +0xed
github.com/minio/mc/cmd.mainAdminInfo(0xc0002d6600, 0x0, 0x2d6600)
        /build/minio-client/src/go/src/github.com/minio/mc/cmd/admin-info.go:292 +0x766
github.com/minio/cli.HandleAction(0x5558abe06840, 0x5558abf13768, 0xc0002d6600, 0xc0002c8400, 0x0)
        /build/minio-client/src/go/pkg/mod/github.com/minio/cli@v1.20.0/app.go:526 +0xca
github.com/minio/cli.Command.Run(0x5558abb0d876, 0x4, 0x0, 0x0, 0x0, 0x0, 0x0, 0x5558abb29295, 0x20, 0x0, ...)
        /build/minio-client/src/go/pkg/mod/github.com/minio/cli@v1.20.0/command.go:220 +0x998
github.com/minio/cli.(*App).RunAsSubcommand(0xc0001985a0, 0xc000087680, 0x0, 0x0)
        /build/minio-client/src/go/pkg/mod/github.com/minio/cli@v1.20.0/app.go:415 +0x817
github.com/minio/cli.Command.startApp(0x5558abb0e31f, 0x5, 0x0, 0x0, 0x0, 0x0, 0x0, 0x5558abb1c189, 0x14, 0x0, ...)
        /build/minio-client/src/go/pkg/mod/github.com/minio/cli@v1.20.0/command.go:308 +0x815
github.com/minio/cli.Command.Run(0x5558abb0e31f, 0x5, 0x0, 0x0, 0x0, 0x0, 0x0, 0x5558abb1c189, 0x14, 0x0, ...)
        /build/minio-client/src/go/pkg/mod/github.com/minio/cli@v1.20.0/command.go:106 +0x12a4
github.com/minio/cli.(*App).Run(0xc0001983c0, 0xc0000ac040, 0x4, 0x4, 0x0, 0x0)
        /build/minio-client/src/go/pkg/mod/github.com/minio/cli@v1.20.0/app.go:289 +0x6b1
github.com/minio/mc/cmd.Main(0xc0000ac040, 0x4, 0x4)
        /build/minio-client/src/go/src/github.com/minio/mc/cmd/main.go:102 +0x267
main.main()
        /build/minio-client/src/go/src/github.com/minio/mc/main.go:32 +0x47
```
## Steps to reproduce the behavior
This is a hard one. I currently have a faulty disk in my cluster. My faulty disk is mounted and some files/folders are accessible but most of the folders/files return a `ls: cannot access '...': Input/ouput error`

Here is my docker swarm compose file (take a look at `minio2`):

```yaml
version: '3.4'

x-default-deploy: &default-deploy
  replicas: 1
  restart_policy:
    condition: any
    delay: 10s
    window: 60s

x-venus-deploy: &venus-deploy
  <<: *default-deploy
  placement:
    constraints:
      - node.hostname == venus

x-mars-deploy: &mars-deploy
  <<: *default-deploy
  placement:
    constraints:
      - node.hostname == mars

x-minio-service: &minio-common
  image: minio/minio:RELEASE.2019-06-27T21-13-50Z
  networks:
    - minio_net
  logging:
    driver: json-file
    options:
      max-size: 50k
      max-file: 5
  environment:
    MINIO_ACCESS_KEY: {omitted}
    MINIO_SECRET_KEY: {omitted}
    # MINIO_STORAGE_CLASS_STANDARD: EC:4 # Default is N/2
    MINIO_STORAGE_CLASS_RRS: EC:2
  command: >
    server --compat
    http://minio0/export0 http://minio0/export1
    http://minio1/export0 http://minio1/export1
    http://minio2/export0 http://minio2/export1
    http://minio3/export0 http://minio3/export1
    http://minio4/export0 http://minio4/export1
    http://minio5/export0 http://minio5/export1

services:
  minio0:
    <<: *minio-common
    deploy: *venus-deploy
    hostname: minio0
    ports:
      - target: 9000
        published: 9001
        mode: host
    volumes:
      - "/minio/disk0/export:/export0"
      - "/minio/disk1/export:/export1"

  minio1:
    <<: *minio-common
    deploy: *venus-deploy
    hostname: minio1
    ports:
      - target: 9000
        published: 9002
        mode: host
    volumes:
      - "/minio/disk2/export:/export0"
      - "/minio/disk3/export:/export1"

  minio2:
    <<: *minio-common
    deploy: *venus-deploy
    hostname: minio2
    ports:
      - target: 9000
        published: 9003
        mode: host
    volumes:
      - "/minio/disk4/export:/export0" # <- This is the faulty disk #######################
      - "/minio/disk5/export:/export1"

  # Mars deployments
  minio3:
    <<: *minio-common
    deploy: *mars-deploy
    hostname: minio3
    ports:
      - target: 9000
        published: 9004
        mode: host
    volumes:
      - "/minio/disk0/export:/export0"
      - "/minio/disk1/export:/export1"

  minio4:
    <<: *minio-common
    deploy: *mars-deploy
    hostname: minio4
    ports:
      - target: 9000
        published: 9005
        mode: host
    volumes:
      - "/minio/disk2/export:/export0"
      - "/minio/disk3/export:/export1"

  minio5:
    <<: *minio-common
    deploy: *mars-deploy
    hostname: minio5
    ports:
      - target: 9000
        published: 9006
        mode: host
    volumes:
      - "/minio/disk4/export:/export0"
      - "/minio/disk5/export:/export1"

networks:
  minio_net:

```

Of course, if the disk is replaced by a non faulty disk, the problem goes away.

## mc version
- Version: 2019-06-12T20:35:20Z
Release-tag: RELEASE.2019-06-12T20-35-20Z
Commit-id: ca26dac8e2e7d2e9b2d888e82f9edbf0873b7d2e

## System information
Server:
- OS: Ubuntu 18.04.2 LTS
Kernel: Linux venus 4.15.0-54-generic #58-Ubuntu SMP Mon Jun 24 10:55:24 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
Docker version 18.09.5, build e8ff056

Client:
OS: Arch (also tested on Ubuntu)
Linux {omitted} 5.1.15-arch1-1-ARCH #1 SMP PREEMPT Tue Jun 25 04:49:39 UTC 2019 x86_64 GNU/Linux

### PR DESCRIPTION
**Pull request by Praveenrajmani**
## Description
Currently, `mc admin info` command will panic even if a single faulty disk exist. This is because the serverInfo API will respond with an empty `Set` for such node which has a faulty disk.

## Motivation and Context
Fixes https://github.com/minio/mc/issues/2813

## How to test this PR?
Steps provided in the issue

## Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [ ] Fixes a regression (If yes, please add `commit-id` or `PR #` here)
- [ ] Documentation needed
- [ ] Unit tests needed
- [ ] Functional tests needed (If yes, add [mint](https://github.com/minio/mint) PR # here: )

### CODE REVIEW

**Comment by minio-ops** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-compression-xl.sh | :heavy_check_mark: |
| mint-compression-dist-xl.sh | :heavy_check_mark: |
| mint-compression-fs.sh | :heavy_check_mark: |
| mint-worm.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-xl.sh | :x: [more...](#596ca654-383c-4779-8586-ef5e0d21ed5a) |
| mint-large-bucket.sh | :x: [more...](#56154941-d71f-43d7-aa31-0841af0fdef3) |
| mint-fs.sh | :x: [more...](#a4e3c6e8-2781-4cf2-9b11-087cc92df04b) |
| mint-dist-xl.sh | :x: [more...](#db412894-5278-4f38-861f-4a4ccfbea0f6) |
<a name="596ca654-383c-4779-8586-ef5e0d21ed5a"></a>
### 7878-bae2d8e/mint-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.60:30225
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 638518b2949c:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... FAILED in 3 seconds
{
  "alert": "",
  "args": {
    "bucketName": "aws-sdk-go-test-p14umanawtxf0f",
    "expiry": 60000000000,
    "objectName": "presignedTest"
  },
  "duration": 3056,
  "error": "RequestError: send request failed\ncaused by: Put http://72.28.97.60:30225/aws-sdk-go-test-p14umanawtxf0f: dial tcp 72.28.97.60:30225: connect: no route to host",
  "function": "PresignedPut",
  "message": "AWS SDK Go CreateBucket Failed",
  "name": "aws-sdk-go",
  "status": "FAIL"
}

Executed 0 out of 14 tests successfully.
```
<a name="56154941-d71f-43d7-aa31-0841af0fdef3"></a>
### 7878-bae2d8e/mint-large-bucket.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.52:31787
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 7a14ca4c1013:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 1 seconds
(2/14) Running aws-sdk-java tests ... done in 2 seconds
(3/14) Running aws-sdk-php tests ... done in 48 seconds
(4/14) Running aws-sdk-ruby tests ... done in 14 seconds
(5/14) Running awscli tests ... done in 1 minutes and 30 seconds
(6/14) Running healthcheck tests ... done in 0 seconds
(7/14) Running mc tests ... FAILED in 2 minutes and 33 seconds
{
  "name": "mc",
  "duration": "111604",
  "function": "test_mirror_list_objects_storage_class",
  "status": "FAIL",
  "error": "/mint/run/core/mc/mc --config-dir /tmp/.mc-12387 --quiet --no-color mirror --storage-class REDUCED_REDUNDANCY /mint/data myminio/mc-test-bucket-21185  >>> \n`/mint/data/datafile-1-MB` -> `myminio/mc-test-bucket-21185/datafile-1-MB`\n`/mint/data/datafile-0-b` -> `myminio/mc-test-bucket-21185/datafile-0-b`\n`/mint/data/datafile-1.03-MB` -> `myminio/mc-test-bucket-21185/datafile-1.03-MB`\n`/mint/data/datafile-1-b` -> `myminio/mc-test-bucket-21185/datafile-1-b`\n`/mint/data/datafile-1-kB` -> `myminio/mc-test-bucket-21185/datafile-1-kB`\n`/mint/data/datafile-10-kB` -> `myminio/mc-test-bucket-21185/datafile-10-kB`\n`/mint/data/datafile-10-MB` -> `myminio/mc-test-bucket-21185/datafile-10-MB`\n`/mint/data/datafile-100-kB` -> `myminio/mc-test-bucket-21185/datafile-100-kB`\n`/mint/data/datafile-129-MB` -> `myminio/mc-test-bucket-21185/datafile-129-MB`\n`/mint/data/datafile-11-MB` -> `myminio/mc-test-bucket-21185/datafile-11-MB`\n`/mint/data/datafile-5-MB` -> `myminio/mc-test-bucket-21185/datafile-5-MB`\n`/mint/data/datafile-33-kB` -> `myminio/mc-test-bucket-21185/datafile-33-kB`\n`/mint/data/datafile-65-MB` -> `myminio/mc-test-bucket-21185/datafile-65-MB`\n`/mint/data/datafile-6-MB` -> `myminio/mc-test-bucket-21185/datafile-6-MB`\n`/mint/data/datafile-5243880-b` -> `myminio/mc-test-bucket-21185/datafile-5243880-b`\nmc: <ERROR> Failed to copy `/mint/data/datafile-11-MB`. Please reduce your request\nmc: <ERROR> Failed to copy `/mint/data/datafile-65-MB`. Please reduce your request\nmc: <ERROR> Failed to copy `/mint/data/datafile-129-MB`. Please reduce your request\nTotal: 233.17 MiB, Transferred: 517.55 MiB, Speed: 4.64 MiB/s"
}

Executed 6 out of 14 tests successfully.
```
<a name="a4e3c6e8-2781-4cf2-9b11-087cc92df04b"></a>
### 7878-bae2d8e/mint-fs.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.57:31437
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 2b2a61b87e9e:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... FAILED in 3 seconds
{
  "alert": "",
  "args": {
    "bucketName": "aws-sdk-go-test-x2rhecj0xj53po",
    "expiry": 60000000000,
    "objectName": "presignedTest"
  },
  "duration": 3063,
  "error": "RequestError: send request failed\ncaused by: Put http://72.28.97.57:31437/aws-sdk-go-test-x2rhecj0xj53po: dial tcp 72.28.97.57:31437: connect: no route to host",
  "function": "PresignedPut",
  "message": "AWS SDK Go CreateBucket Failed",
  "name": "aws-sdk-go",
  "status": "FAIL"
}

Executed 0 out of 14 tests successfully.
```
<a name="db412894-5278-4f38-861f-4a4ccfbea0f6"></a>
### 7878-bae2d8e/mint-dist-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.61:31213
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 12bf28594524:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 0 seconds
(2/14) Running aws-sdk-java tests ... done in 1 seconds
(3/14) Running aws-sdk-php tests ... done in 42 seconds
(4/14) Running aws-sdk-ruby tests ... done in 3 seconds
(5/14) Running awscli tests ... done in 1 minutes and 7 seconds
(6/14) Running healthcheck tests ... done in 0 seconds
(7/14) Running mc tests ... done in 33 seconds
(8/14) Running minio-dotnet tests ... done in 50 seconds
(9/14) Running minio-go tests ... done in 1 minutes and 14 seconds
(10/14) Running minio-java tests ... FAILED in 45 seconds
{
  "name": "minio-java",
  "function": "listIncompleteUploads(final String bucketName, final String prefix, final boolean recursive)",
  "args": "prefix: minio, recursive: true",
  "duration": 260,
  "status": "FAIL",
  "error": "error occurred\nErrorResponse(code=SlowDown, message=Please reduce your request, bucketName=minio-java-test-pbb65r, objectName=minio-java-test-35hpa3g, resource=/minio-java-test-pbb65r/minio-java-test-35hpa3g, requestId=15AE3764D66245A9, hostId=d3d7afe8-d3e8-4d49-b809-3f3e6f9b53fa)\nrequest={method=DELETE, url=http://72.28.97.61:31213/minio-java-test-pbb65r/minio-java-test-35hpa3g?uploadId=d3973697-91ba-4d14-a908-69d520320086, headers=Host: 72.28.97.61:31213\nUser-Agent: MinIO (amd64; amd64) minio-java/dev\nx-amz-content-sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855\nx-amz-date: 20190704T133026Z\nAuthorization: AWS4-HMAC-SHA256 Credential=*REDACTED*/20190704/us-east-1/s3/aws4_request, SignedHeaders=host;x-amz-content-sha256;x-amz-date, Signature=*REDACTED*\n}\nresponse={code=503, headers=Accept-Ranges: bytes\nContent-Length: 361\nContent-Security-Policy: block-all-mixed-content\nContent-Type: application/xml\nRetry-After: 120\nServer: MinIO/DEVELOPMENT.2019-07-04T13-12-06Z\nVary: Origin\nX-Amz-Request-Id: 15AE3764D66245A9\nX-Xss-Protection: 1; mode=block\nDate: Thu, 04 Jul 2019 13:30:27 GMT\n}\n >>> [io.minio.MinioClient.executeReq(MinioClient.java:1204), io.minio.MinioClient.execute(MinioClient.java:1070), io.minio.MinioClient.executeDelete(MinioClient.java:1347), io.minio.MinioClient.abortMultipartUpload(MinioClient.java:5149), io.minio.MinioClient.putObject(MinioClient.java:4337), io.minio.MinioClient.putObject(MinioClient.java:4183), FunctionalTest.listIncompleteUploads_test3(FunctionalTest.java:1679), FunctionalTest.runTests(FunctionalTest.java:2990), FunctionalTest.main(FunctionalTest.java:3118)]"
}

Executed 9 out of 14 tests successfully.
```

**Comment by harshavardhana** [comment]
Even faulty disks information should be sent, we shouldn't ignore those disks. `mc admin info` should be an conclusive evidence of what is happening on server.

**Comment by Praveenrajmani** [comment]
> Even faulty disks information should be sent, we shouldn't ignore those disks. `mc admin info` should be an conclusive evidence of what is happening on server.

Agreed :+1: Will check for faulty disk errors

**Comment by kannappanr** [comment]
ping @Praveenrajmani

**Comment by Praveenrajmani** [comment]
PTAL @harshavardhana @vadmeste

**Comment by minio-ops** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-worm.sh | :heavy_check_mark: |
| mint-compression-xl.sh | :x: [more...](#2359cca4-8e9d-4f31-a198-39c429c7edf4) |
| mint-xl.sh | :x: [more...](#917875be-93a3-4f6d-83ac-c90c616f3465) |
| mint-large-bucket.sh | :x: [more...](#7ec50bfe-518c-4e82-97d6-911c9b36a699) |
| mint-compression-dist-xl.sh | :x: [more...](#3eadfa70-b46c-4bb4-872c-1e5a4f83affa) |
| mint-compression-fs.sh | :x: [more...](#cdc81f25-ee5c-47fe-8c23-f269ffa23756) |
| mint-fs.sh | :x: [more...](#768ba98c-775b-444c-92bd-4a4fd3d1be0f) |
| mint-dist-xl.sh | :x: [more...](#79b42ca8-5499-48eb-ac3d-0f0b677584a0) |
| mint-gateway-nas.sh | :x: [more...](#cff38e15-ca04-4329-a093-34ce8da5e59e) |
<a name="3eadfa70-b46c-4bb4-872c-1e5a4f83affa"></a>
### 7878-406d433/mint-compression-dist-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.57:31440
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp d734a12d2399:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... FAILED in 18 seconds
{
  "alert": "",
  "args": {
    "bucketName": "aws-sdk-go-test-k94q91xq25h4vp",
    "expiry": 60000000000,
    "objectName": "presignedTest"
  },
  "duration": 17696,
  "error": "RequestError: send request failed\ncaused by: Put http://72.28.97.57:31440/aws-sdk-go-test-k94q91xq25h4vp: dial tcp 72.28.97.57:31440: connect: no route to host",
  "function": "PresignedPut",
  "message": "AWS SDK Go CreateBucket Failed",
  "name": "aws-sdk-go",
  "status": "FAIL"
}

Executed 0 out of 14 tests successfully.
```
<a name="768ba98c-775b-444c-92bd-4a4fd3d1be0f"></a>
### 7878-406d433/mint-fs.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.54:32463
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 00c184b2d7a9:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... FAILED in 0 seconds
{
  "alert": "",
  "args": {
    "bucketName": "aws-sdk-go-test-i6lba0ga1q6qhv",
    "objectName1": "object1.csv",
    "objectName2": "object2.csv"
  },
  "duration": 14,
  "error": "MalformedXML: The XML provided was not well-formed or did not validate against our published schema. Check the service documentation and try again.\n\tstatus code: 400, request id: 15B6B7EA939C6FCE, host id: ",
  "function": "testSelectObject",
  "message": "AWS SDK Go Select object failed for unicode separator MalformedXML: The XML provided was not well-formed or did not validate against our published schema. Check the service documentation and try again.\n\tstatus code: 400, request id: 15B6B7EA939C6FCE, host id: ",
  "name": "aws-sdk-go",
  "status": "FAIL"
}

Executed 0 out of 14 tests successfully.
```
<a name="cdc81f25-ee5c-47fe-8c23-f269ffa23756"></a>
### 7878-406d433/mint-compression-fs.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.56:31888
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 70f63fa921ad:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... FAILED in 0 seconds
{
  "alert": "",
  "args": {
    "bucketName": "aws-sdk-go-test-h4euzaw4ovh445",
    "objectName1": "object1.csv",
    "objectName2": "object2.csv"
  },
  "duration": 16,
  "error": "MalformedXML: The XML provided was not well-formed or did not validate against our published schema. Check the service documentation and try again.\n\tstatus code: 400, request id: 15B6B7EAB8175600, host id: ",
  "function": "testSelectObject",
  "message": "AWS SDK Go Select object failed for unicode separator MalformedXML: The XML provided was not well-formed or did not validate against our published schema. Check the service documentation and try again.\n\tstatus code: 400, request id: 15B6B7EAB8175600, host id: ",
  "name": "aws-sdk-go",
  "status": "FAIL"
}

Executed 0 out of 14 tests successfully.
```
<a name="7ec50bfe-518c-4e82-97d6-911c9b36a699"></a>
### 7878-406d433/mint-large-bucket.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.52:30037
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 7bc4c26dda71:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... FAILED in 2 seconds
{
  "alert": "",
  "args": {
    "bucketName": "aws-sdk-go-test-cljd5opbb9wjw0",
    "objectName1": "object1.csv",
    "objectName2": "object2.csv"
  },
  "duration": 267,
  "error": "MalformedXML: The XML provided was not well-formed or did not validate against our published schema. Check the service documentation and try again.\n\tstatus code: 400, request id: 15B6B7EB3D1A7175, host id: ",
  "function": "testSelectObject",
  "message": "AWS SDK Go Select object failed for unicode separator MalformedXML: The XML provided was not well-formed or did not validate against our published schema. Check the service documentation and try again.\n\tstatus code: 400, request id: 15B6B7EB3D1A7175, host id: ",
  "name": "aws-sdk-go",
  "status": "FAIL"
}

Executed 0 out of 14 tests successfully.
```
<a name="79b42ca8-5499-48eb-ac3d-0f0b677584a0"></a>
### 7878-406d433/mint-dist-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.57:32754
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp b310ec4a6a7c:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... FAILED in 18 seconds
{
  "alert": "",
  "args": {
    "bucketName": "aws-sdk-go-test-wb5i5dcbl1ufm3",
    "expiry": 60000000000,
    "objectName": "presignedTest"
  },
  "duration": 17768,
  "error": "RequestError: send request failed\ncaused by: Put http://72.28.97.57:32754/aws-sdk-go-test-wb5i5dcbl1ufm3: dial tcp 72.28.97.57:32754: connect: no route to host",
  "function": "PresignedPut",
  "message": "AWS SDK Go CreateBucket Failed",
  "name": "aws-sdk-go",
  "status": "FAIL"
}

Executed 0 out of 14 tests successfully.
```
<a name="cff38e15-ca04-4329-a093-34ce8da5e59e"></a>
### 7878-406d433/mint-gateway-nas.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.57:32608
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 3608374f3735:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... FAILED in 15 seconds
{
  "alert": "",
  "args": {
    "bucketName": "aws-sdk-go-test-cbnheljfcholfn",
    "expiry": 60000000000,
    "objectName": "presignedTest"
  },
  "duration": 15342,
  "error": "RequestError: send request failed\ncaused by: Put http://72.28.97.57:32608/aws-sdk-go-test-cbnheljfcholfn: dial tcp 72.28.97.57:32608: connect: no route to host",
  "function": "PresignedPut",
  "message": "AWS SDK Go CreateBucket Failed",
  "name": "aws-sdk-go",
  "status": "FAIL"
}

Executed 0 out of 14 tests successfully.
```
<a name="917875be-93a3-4f6d-83ac-c90c616f3465"></a>
### 7878-406d433/mint-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.60:31048
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 63bc046f3ed4:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... FAILED in 0 seconds
{
  "alert": "",
  "args": {
    "bucketName": "aws-sdk-go-test-i25gdp6cne33v6",
    "objectName1": "object1.csv",
    "objectName2": "object2.csv"
  },
  "duration": 14,
  "error": "MalformedXML: The XML provided was not well-formed or did not validate against our published schema. Check the service documentation and try again.\n\tstatus code: 400, request id: 15B6B7EAA5880D89, host id: ",
  "function": "testSelectObject",
  "message": "AWS SDK Go Select object failed for unicode separator MalformedXML: The XML provided was not well-formed or did not validate against our published schema. Check the service documentation and try again.\n\tstatus code: 400, request id: 15B6B7EAA5880D89, host id: ",
  "name": "aws-sdk-go",
  "status": "FAIL"
}

Executed 0 out of 14 tests successfully.
```
<a name="2359cca4-8e9d-4f31-a198-39c429c7edf4"></a>
### 7878-406d433/mint-compression-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.54:31029
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 0efddbe0d5e1:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... FAILED in 6 minutes and 0 seconds
{
  "alert": "",
  "args": {
    "bucketName": "aws-sdk-go-test-4ohyr4co5zfntw",
    "expiry": 60000000000,
    "objectName": "presignedTest"
  },
  "duration": 360010,
  "error": "XMinioServerNotInitialized: Server not initialized, please try again.\n\tstatus code: 503, request id: 15B6B83E7EF44587, host id: ",
  "function": "PresignedPut",
  "message": "AWS SDK Go CreateBucket Failed",
  "name": "aws-sdk-go",
  "status": "FAIL"
}

Executed 0 out of 14 tests successfully.
```

File: cmd/format-xl.go [hunk 1]
```diff
@@ -698,6 +698,22 @@ func initStorageDisks(endpoints EndpointList) ([]StorageAPI, error) {
 	return storageDisks, nil
 }
 
+// Runs through the faulty disks and record their errors.
+func initDisksWithErrors(endpoints EndpointList) ([]StorageAPI, []error) {
+	storageDisks := make([]StorageAPI, len(endpoints))
+	var dErrs = make([]error, len(storageDisks))
+	for index, endpoint := range endpoints {
+		storage, err := newStorageAPI(endpoint)
+		if err != nil && err != errDiskNotFound {
```
Comment (vadmeste) [inline cmd/format-xl.go]: Can you tell why you are ignoring setting errDiskNotFound in dErrs ?

File: cmd/format-xl.go [hunk 2]
```diff
@@ -698,6 +698,22 @@ func initStorageDisks(endpoints EndpointList) ([]StorageAPI, error) {
...
+			logger.LogIf(context.Background(), err)
+			dErrs[index] = errFaultyDisk
```
Comment (vadmeste) [inline cmd/format-xl.go]: I don't think replacing all errors with errFaultyDisk is a good idea. I think that a better idea is to map errDiskNotFound to offline node and map other "unknown" errors with corrupted

**Review by vadmeste — COMMENTED** [review]
Some comments

File: cmd/format-xl.go (hunk 1 above)
Comment (Praveenrajmani) [reply cmd/format-xl.go]: We are recording the `errDiskNotFound` already in loadFormatXLAll() function. But still, it is ok to record this here as well :+1:

File: cmd/format-xl.go (hunk 2 above)
Comment (Praveenrajmani) [reply cmd/format-xl.go]: @vadmeste is errFaultyDisk not making sense here? I mean, is it OK to consider all the other unknown errors as `errCorruptedFormat`?

Comment (vadmeste) [reply cmd/format-xl.go]: > is it OK to consider all the other unknown errors as `errCorruptedFormat`?

I think so.. because we already have only three state, online - offline - something wrong (corrupted)

**Comment by Praveenrajmani** [comment]
PTAL @vadmeste

**Comment by minio-ops** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-worm.sh | :heavy_check_mark: |
| mint-compression-xl.sh | :x: [more...](#9107efab-2f6d-4edf-80d6-755d4b0177cc) |
| mint-xl.sh | :x: [more...](#4a932ca2-6928-4826-a099-04bc614ad28f) |
| mint-large-bucket.sh | :x: [more...](#f0293f66-51b6-415f-be8c-c69dbf763d0b) |
| mint-compression-dist-xl.sh | :x: [more...](#5a8642b7-e509-4313-85de-cab5b79cf507) |
| mint-compression-fs.sh | :x: [more...](#e9556ff9-16ee-4a5f-8e06-38566f61400e) |
| mint-fs.sh | :x: [more...](#479f4eae-da31-416c-b4d7-22005a66b5df) |
| mint-dist-xl.sh | :x: [more...](#b3e51b6a-121d-4c17-b3bb-18dd859effe1) |
| mint-gateway-nas.sh | :x: [more...](#13434f81-8e70-4230-81a9-6227224a4ebc) |
<a name="4a932ca2-6928-4826-a099-04bc614ad28f"></a>
### 7878-e3dc93f/mint-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.57:31148
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp dcf95eb1f381:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... FAILED in 12 seconds
{
  "alert": "",
  "args": {
    "bucketName": "aws-sdk-go-test-22kn5pgo6d1ars",
    "expiry": 60000000000,
    "objectName": "presignedTest"
  },
  "duration": 12291,
  "error": "RequestError: send request failed\ncaused by: Put http://72.28.97.57:31148/aws-sdk-go-test-22kn5pgo6d1ars: dial tcp 72.28.97.57:31148: connect: no route to host",
  "function": "PresignedPut",
  "message": "AWS SDK Go CreateBucket Failed",
  "name": "aws-sdk-go",
  "status": "FAIL"
}

Executed 0 out of 14 tests successfully.
```
<a name="13434f81-8e70-4230-81a9-6227224a4ebc"></a>
### 7878-e3dc93f/mint-gateway-nas.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.58:30168
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 593930f0866a:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... FAILED in 0 seconds
{
  "alert": "",
  "args": {
    "bucketName": "aws-sdk-go-test-lw9huh16sje93d",
    "objectName1": "object1.csv",
    "objectName2": "object2.csv"
  },
  "duration": 12,
  "error": "MalformedXML: The XML provided was not well-formed or did not validate against our published schema. Check the service documentation and try again.\n\tstatus code: 400, request id: 15B721D8D7F1705B, host id: ",
  "function": "testSelectObject",
  "message": "AWS SDK Go Select object failed for unicode separator MalformedXML: The XML provided was not well-formed or did not validate against our published schema. Check the service documentation and try again.\n\tstatus code: 400, request id: 15B721D8D7F1705B, host id: ",
  "name": "aws-sdk-go",
  "status": "FAIL"
}

Executed 0 out of 14 tests successfully.
```
<a name="5a8642b7-e509-4313-85de-cab5b79cf507"></a>
### 7878-e3dc93f/mint-compression-dist-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.57:32086
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 9b39fcc52000:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... FAILED in 12 seconds
{
  "alert": "",
  "args": {
    "bucketName": "aws-sdk-go-test-y1umwgft90elfh",
    "expiry": 60000000000,
    "objectName": "presignedTest"
  },
  "duration": 11724,
  "error": "RequestError: send request failed\ncaused by: Put http://72.28.97.57:32086/aws-sdk-go-test-y1umwgft90elfh: dial tcp 72.28.97.57:32086: connect: no route to host",
  "function": "PresignedPut",
  "message": "AWS SDK Go CreateBucket Failed",
  "name": "aws-sdk-go",
  "status": "FAIL"
}

Executed 0 out of 14 tests successfully.
```
<a name="9107efab-2f6d-4edf-80d6-755d4b0177cc"></a>
### 7878-e3dc93f/mint-compression-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.54:30109
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp e76cb823ba50:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... FAILED in 0 seconds
{
  "alert": "",
  "args": {
    "bucketName": "aws-sdk-go-test-dmdqkegxdvi2pp",
    "objectName1": "object1.csv",
    "objectName2": "object2.csv"
  },
  "duration": 32,
  "error": "MalformedXML: The XML provided was not well-formed or did not validate against our published schema. Check the service documentation and try again.\n\tstatus code: 400, request id: 15B721D8CE5E58CB, host id: ",
  "function": "testSelectObject",
  "message": "AWS SDK Go Select object failed for unicode separator MalformedXML: The XML provided was not well-formed or did not validate against our published schema. Check the service documentation and try again.\n\tstatus code: 400, request id: 15B721D8CE5E58CB, host id: ",
  "name": "aws-sdk-go",
  "status": "FAIL"
}

Executed 0 out of 14 tests successfully.
```
<a name="b3e51b6a-121d-4c17-b3bb-18dd859effe1"></a>
### 7878-e3dc93f/mint-dist-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.61:32706
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp cb04763c47db:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... FAILED in 0 seconds
{
  "alert": "",
  "args": {
    "bucketName": "aws-sdk-go-test-2cr1b2joy0l215",
    "objectName1": "object1.csv",
    "objectName2": "object2.csv"
  },
  "duration": 131,
  "error": "MalformedXML: The XML provided was not well-formed or did not validate against our published schema. Check the service documentation and try again.\n\tstatus code: 400, request id: 15B721D9036E4582, host id: ",
  "function": "testSelectObject",
  "message": "AWS SDK Go Select object failed for unicode separator MalformedXML: The XML provided was not well-formed or did not validate against our published schema. Check the service documentation and try again.\n\tstatus code: 400, request id: 15B721D9036E4582, host id: ",
  "name": "aws-sdk-go",
  "status": "FAIL"
}

Executed 0 out of 14 tests successfully.
```
<a name="f0293f66-51b6-415f-be8c-c69dbf763d0b"></a>
### 7878-e3dc93f/mint-large-bucket.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.56:30630
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 976fc06d0070:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... FAILED in 2 seconds
{
  "alert": "",
  "args": {
    "bucketName": "aws-sdk-go-test-z1gpr6rwsz1qc2",
    "objectName1": "object1.csv",
    "objectName2": "object2.csv"
  },
  "duration": 236,
  "error": "MalformedXML: The XML provided was not well-formed or did not validate against our published schema. Check the service documentation and try again.\n\tstatus code: 400, request id: 15B721D9470B0776, host id: ",
  "function": "testSelectObject",
  "message": "AWS SDK Go Select object failed for unicode separator MalformedXML: The XML provided was not well-formed or did not validate against our published schema. Check the service documentation and try again.\n\tstatus code: 400, request id: 15B721D9470B0776, host id: ",
  "name": "aws-sdk-go",
  "status": "FAIL"
}

Executed 0 out of 14 tests successfully.
```
<a name="479f4eae-da31-416c-b4d7-22005a66b5df"></a>
### 7878-e3dc93f/mint-fs.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.60:30669
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 84acc13095d4:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... FAILED in 0 seconds
{
  "alert": "",
  "args": {
    "bucketName": "aws-sdk-go-test-ayun5hfdgjjsas",
    "objectName1": "object1.csv",
    "objectName2": "object2.csv"
  },
  "duration": 8,
  "error": "MalformedXML: The XML provided was not well-formed or did not validate against our published schema. Check the service documentation and try again.\n\tstatus code: 400, request id: 15B721D8B750180D, host id: ",
  "function": "testSelectObject",
  "message": "AWS SDK Go Select object failed for unicode separator MalformedXML: The XML provided was not well-formed or did not validate against our published schema. Check the service documentation and try again.\n\tstatus code: 400, request id: 15B721D8B750180D, host id: ",
  "name": "aws-sdk-go",
  "status": "FAIL"
}

Executed 0 out of 14 tests successfully.
```
<a name="e9556ff9-16ee-4a5f-8e06-38566f61400e"></a>
### 7878-e3dc93f/mint-compression-fs.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.55:31452
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp b070bac4f349:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... FAILED in 0 seconds
{
  "alert": "",
  "args": {
    "bucketName": "aws-sdk-go-test-o09wahgukq4xj9",
    "objectName1": "object1.csv",
    "objectName2": "object2.csv"
  },
  "duration": 71,
  "error": "MalformedXML: The XML provided was not well-formed or did not validate against our published schema. Check the service documentation and try again.\n\tstatus code: 400, request id: 15B721D8E2A6E038, host id: ",
  "function": "testSelectObject",
  "message": "AWS SDK Go Select object failed for unicode separator MalformedXML: The XML provided was not well-formed or did not validate against our published schema. Check the service documentation and try again.\n\tstatus code: 400, request id: 15B721D8E2A6E038, host id: ",
  "name": "aws-sdk-go",
  "status": "FAIL"
}

Executed 0 out of 14 tests successfully.
```

**Review by vadmeste — APPROVED** [review]
LGTM & tested

**Review by harshavardhana — APPROVED** [review]

**Comment by minio-ops** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-compression-xl.sh | :heavy_check_mark: |
| mint-xl.sh | :heavy_check_mark: |
| mint-compression-dist-xl.sh | :heavy_check_mark: |
| mint-compression-fs.sh | :heavy_check_mark: |
| mint-worm.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-dist-xl.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :x: [more...](#3faea7b0-64b9-43e4-82d8-2d26d9f955d3) |
| mint-gateway-nas.sh | :x: [more...](#ed0efe8e-903a-456d-898f-f7db598cdb2e) |
<a name="3faea7b0-64b9-43e4-82d8-2d26d9f955d3"></a>
### 7878-d7d5072/mint-large-bucket.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.54:31002
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 12562a6134c4:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 3 seconds
(2/14) Running aws-sdk-java tests ... done in 1 seconds
(3/14) Running aws-sdk-php tests ... done in 49 seconds
(4/14) Running aws-sdk-ruby tests ... done in 13 seconds
(5/14) Running awscli tests ... done in 1 minutes and 28 seconds
(6/14) Running healthcheck tests ... done in 0 seconds
(7/14) Running mc tests ... FAILED in 2 minutes and 27 seconds
{
  "name": "mc",
  "duration": "93498",
  "function": "test_mirror_list_objects_storage_class",
  "status": "FAIL",
  "error": "/mint/run/core/mc/mc --config-dir /tmp/.mc-25333 --quiet --no-color mirror --storage-class REDUCED_REDUNDANCY /mint/data myminio/mc-test-bucket-29418  >>> \n`/mint/data/datafile-1-MB` -> `myminio/mc-test-bucket-29418/datafile-1-MB`\n`/mint/data/datafile-0-b` -> `myminio/mc-test-bucket-29418/datafile-0-b`\n`/mint/data/datafile-1-kB` -> `myminio/mc-test-bucket-29418/datafile-1-kB`\n`/mint/data/datafile-1.03-MB` -> `myminio/mc-test-bucket-29418/datafile-1.03-MB`\n`/mint/data/datafile-1-b` -> `myminio/mc-test-bucket-29418/datafile-1-b`\n`/mint/data/datafile-10-MB` -> `myminio/mc-test-bucket-29418/datafile-10-MB`\n`/mint/data/datafile-100-kB` -> `myminio/mc-test-bucket-29418/datafile-100-kB`\n`/mint/data/datafile-10-kB` -> `myminio/mc-test-bucket-29418/datafile-10-kB`\n`/mint/data/datafile-129-MB` -> `myminio/mc-test-bucket-29418/datafile-129-MB`\n`/mint/data/datafile-5-MB` -> `myminio/mc-test-bucket-29418/datafile-5-MB`\n`/mint/data/datafile-5243880-b` -> `myminio/mc-test-bucket-29418/datafile-5243880-b`\n`/mint/data/datafile-33-kB` -> `myminio/mc-test-bucket-29418/datafile-33-kB`\n`/mint/data/datafile-11-MB` -> `myminio/mc-test-bucket-29418/datafile-11-MB`\n`/mint/data/datafile-6-MB` -> `myminio/mc-test-bucket-29418/datafile-6-MB`\n`/mint/data/datafile-65-MB` -> `myminio/mc-test-bucket-29418/datafile-65-MB`\nmc: <ERROR> Failed to copy `/mint/data/datafile-10-MB`. Please reduce your request\nmc: <ERROR> Failed to copy `/mint/data/datafile-65-MB`. Please reduce your request\nmc: <ERROR> Failed to copy `/mint/data/datafile-11-MB`. Please reduce your request\nmc: <ERROR> Failed to copy `/mint/data/datafile-129-MB`. Please reduce your request\nTotal: 233.17 MiB, Transferred: 488.49 MiB, Speed: 5.23 MiB/s"
}

Executed 6 out of 14 tests successfully.
```
<a name="ed0efe8e-903a-456d-898f-f7db598cdb2e"></a>
### 7878-d7d5072/mint-gateway-nas.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.57:31947
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp f50f96adedb8:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... FAILED in 13 seconds
{
  "alert": "",
  "args": {
    "bucketName": "aws-sdk-go-test-qrzg1jvs3o5ist",
    "expiry": 60000000000,
    "objectName": "presignedTest"
  },
  "duration": 12492,
  "error": "RequestError: send request failed\ncaused by: Put http://72.28.97.57:31947/aws-sdk-go-test-qrzg1jvs3o5ist: dial tcp 72.28.97.57:31947: connect: no route to host",
  "function": "PresignedPut",
  "message": "AWS SDK Go CreateBucket Failed",
  "name": "aws-sdk-go",
  "status": "FAIL"
}

Executed 0 out of 14 tests successfully.
```
