### PR TITLE
utils: reduceErrs returns and validates quorum errors.

### LINKED ISSUE #3298: reduceErrs should return maximally occurring error and its count
[reduceErrs](https://github.com/minio/minio/blob/master/cmd/xl-v1-utils.go#L35) returns the error which occurs the most, filtering out ``ignoredErrs``. This is insufficient to know if the corresponding operation had the same result in quorum or more number of nodes.

## Expected Behavior

``reduceErrs`` should return maximally occurring error and its count
## Current Behavior

``reduceErrs`` returns the maximally occurring error. e.g, ``reduceErrs([]error{errFileNotFound, errFileNotFound, nil, nil}, nil}`` will return ``nil`` or ``errFileNotFound`` depending on the order in which the keys where inserted into the underlying map, which is used to count the number of occurrences of an error.

## Possible Solution

``reduceErrs`` should return the number of occurrences of the maximally occurring error.

## Steps to Reproduce (for bugs)

N/A

## Context

With ``reduceErrs`` returning an error (incl. ``nil``) which may not have quorum may cause data to diverge among disks in a erasure code backend.

## Your Environment

* Version used:
* Environment name and version (e.g. nginx 1.9.1):
* Server type and version:
* Operating System and version:
* Link to your project:

### PR DESCRIPTION
**Pull request by harshavardhana**
## Description
This is needed as explained by @krisis 

Lets say we have following errors.

```
[]error{nil, errFileNotFound, errDiskAccessDenied, errDiskAccesDenied}
```

Since the last two errors are filtered, the maximum is nil,
depending on map order.

Let's say we get nil from reduceErr. Clearly at this point
we don't have quorum nodes agreeing about the data and since
GetObject only requires N/2 (Read quorum) and isDiskQuorum
would have returned true. This is problematic and can lead to
undersiable consequences.

## Motivation and Context
Fixes #3298 

## How Has This Been Tested?
Theoretical 

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

File: cmd/xl-v1-metadata.go [hunk 1]
```diff
@@ -336,7 +336,12 @@ func writeUniqueXLMetadata(disks []StorageAPI, bucket, prefix string, xlMetas []
 		return traceError(errXLWriteQuorum)
 	}
 
-	return reduceErrs(mErrs, objectOpIgnoredErrs)
+	if maxCount, reducedErr := reduceErrs(mErrs, objectOpIgnoredErrs); reducedErr != nil {
+		if maxCount >= quorum {
+			return reducedErr
```
Comment (krisis) [inline cmd/xl-v1-metadata.go]: if the maxCount is less than quorum we should return the corresponding quorum error (read or write).
```go
else {
  return traceError(errXLWriteQuorum)
}
```

File: cmd/xl-v1-utils.go [hunk 2]
```diff
@@ -42,14 +41,20 @@ func reduceErrs(errs []error, ignoredErrs []error) error {
...
 	max := 0
-	var errMax error
 	for err, count := range errorCounts {
 		if max < count {
 			max = count
-			errMax = err
+			maxErr = err
+		}
+	}
+	if maxErr != nil {
```
Comment (krisis) [inline cmd/xl-v1-utils.go]: Even if ``maxErr`` is ``nil`` the count must be greater than or equal to the quorum value.

File: cmd/xl-v1-utils.go [hunk 3]
```diff
@@ -42,14 +41,20 @@ func reduceErrs(errs []error, ignoredErrs []error) error {
...
+		if max >= quorum {
+			maxErr = traceError(maxErr, errs...)
+		} else {
+			maxErr = traceError(errXLReadQuorum, errs...)
```
Comment (krisis) [inline cmd/xl-v1-utils.go]: It could be read or write quorum depending on the operation. It can't be errXLReadQuorum unconditionally.

File: cmd/xl-v1-object.go [hunk 4]
```diff
@@ -339,8 +339,11 @@ func rename(disks []StorageAPI, srcBucket, srcEntry, dstBucket, dstEntry string,
 		undoRename(disks, srcBucket, srcEntry, dstBucket, dstEntry, isPart, errs)
 		return traceError(errXLWriteQuorum)
 	}
-	// Return on first error, also undo any partially successful rename operations.
-	return reduceErrs(errs, objectOpIgnoredErrs)
+	// Return on quorum error.
+	if reducedErr := reduceWriteQuorumErrs(errs, objectOpIgnoredErrs, quorum); reducedErr != nil {
```
Comment (krisis) [inline cmd/xl-v1-object.go]: you could do ``return reduceWriteQuorumErrs(...)``. reduceWriteQuorumErrs handles all error  values alike, including nil.

File: cmd/xl-v1-utils.go [hunk 5]
```diff
@@ -42,14 +41,45 @@ func reduceErrs(errs []error, ignoredErrs []error) error {
...
+	}
+	return max, maxErr
+}
+
+// reduceReadQuorumErrs behaves like reduceErrs but only for returning
+// values of maximally occuring errors validated against readQuorum.
+func reduceReadQuorumErrs(errs []error, ignoredErrs []error, readQuorum int) (maxErr error) {
+	maxCount, maxErr := reduceErrs(errs, ignoredErrs)
+	if maxCount >= readQuorum {
+		if maxErr != nil {
```
Comment (krisis) [inline cmd/xl-v1-utils.go]: While this is correct, we can simplify as follows. There is no need to handle ``nil`` differently.
```go
if maxCount >= readQuorum {
  return traceError(maxErr, errs)
} else {
  return traceError(errXLReadQuorum, errs)
}
```

File: cmd/xl-v1-utils.go [hunk 6]
```diff
@@ -42,14 +41,45 @@ func reduceErrs(errs []error, ignoredErrs []error) error {
...
+		}
+		return maxErr
+	}
+	maxErr = traceError(errXLReadQuorum, errs...)
+	return
+}
+
+// reduceWriteQuorumErrs behaves like reduceErrs but only for returning
+// values of maximally occuring errors validated against writeQuorum.
+func reduceWriteQuorumErrs(errs []error, ignoredErrs []error, writeQuorum int) (maxErr error) {
```
Comment (krisis) [inline cmd/xl-v1-utils.go:81]: reduceReadQuorumErrs and reduceWriteQuorumErrs can be unified as below,
```go
func reduceQuorumErrs(errs, ignoredErrs []error, quorum int, quorumErr error) error {
  maxCount, maxErr := reduceErrs(errs, ignoredErrs)
  if maxCount >= quorum {
    return traceError(maxErr, errs)
  } 
  return traceError(quorumErr, errs)
}

func reduceReadQuorumErrs(errs, ignoredErrs []error, readQuorum int) {
  return reduceQuorumErrs(errs, ignoredErrs, readQuorum, errXLReadQuorum)
}

func reduceWriteQuorumErrs(errs, ignoredErrs []error, writeQuorum int) {
  return reduceQuorumErrs(errs, ignoredErrs, writeQuorum, errXLWriteQuorum)
}
```

**Review by krisis — APPROVED** [review]
LGTM
