### PR TITLE
canonicalize ETag correctly

### LINKED ISSUE #7441: minio is not handling double-double quotes in CompleteMultiPartUpload ETag
I am testing the Vertica S3 Export feature against minio. Unfortunately the export fails with Vertica giving me an error.

## Expected Behavior
* Running an S3 Export from Vertica should succeed against minio

## Current Behavior
* Running an S3 Export from Vertica fails, with minio returning a 500 internal error in response to Vertica's last call to minio

## Possible Solution
It looks like S3 will simply remove as many double-quotes as it finds in ETags, but minio may only be removing a single set.  Vertica is sending the ETag with two sets of double-quotes.

## Steps to Reproduce (for bugs)
1. Start a multipart upload
2. Upload a single part
3. Complete the multipart upload and send the ETag wrapped in two sets of double-quotes, like so:  `<ETag>""ETag value""</ETag>`

## Context
* Here is an example POST request which caused the minio error (some parts censored):

POST /bucket/path/7f018980-5ff7-47c4-a687-7b33cad6da22/a44e9279-2625-4fd8-b69e-24903bab2932/export.ab1a6cea.csv?uploadId=324b64dc-49f5-4329-ba9c-00e8d9a0c6c7 HTTP/1.1
Host: s3.amazonaws.com
Accept: */*
Authorization: AWS4-HMAC-SHA256 Credential=CREDS/20190328/us-east-1/s3/aws4_request,SignedHeaders=content-type;date;host;x-amz-content-sha256,Signature=SIGNATURE
Content-Type: text/xml
Date: 20190328T221206Z
x-amz-content-sha256: SHA256
Content-Length: 177

`<?xml version="1.0" encoding="UTF-8"?><CompleteMultipartUpload><Part><PartNumber>1</PartNumber><ETag>""e357af0ed6e5dddcdb5a7ad36954f090""</ETag></Part></CompleteMultipartUpload>`

* This is the response body from minio:
`<?xml version="1.0" encoding="UTF-8"?>
<Error><Code>InternalError</Code><Message>We encountered an internal error, please try again.</Message><Key>path/7f018980-5ff7-47c4-a687-7b33cad6da22/a44e9279-2625-4fd8-b69e-24903bab2932/export.ab1a6cea.csv</Key><BucketName>bucket</BucketName><Resource>/bucket/path/7f018980-5ff7-47c4-a687-7b33cad6da22/a44e9279-2625-4fd8-b69e-24903bab2932/export.ab1a6cea.csv</Resource><RequestId>15903EFCA1F951C8</RequestId><HostId>a4a4209d-91aa-4f3e-87b4-b41fbcb4ae13</HostId></Error>`

* This is the error log (from minio log) which appeared at the time of the error response (relevant part bolded):
2019-03-28T16:48:09.463279972Z time="2019-03-28T16:48:09Z"
level=error msg="Unable to complete multipart upload."
**cause="encoding/hex: invalid byte: U+0022 '"'"**
source="[object-handlers.go:952:objectAPIHandlers.CompleteMultipartUploadHandler()]"
stack="object-api-utils.go:185:getCompleteMultipartMD5 fs-v1-multipart.go:714:fsObjects.CompleteMultipartUpload <autogenerated>:387:(*fsObjects).CompleteMultipartUpload object-handlers.go:950:objectAPIHandlers.CompleteMultipartUploadHandler api-router.go:50:(objectAPIHandlers).CompleteMultipartUploadHandler-fm" 

## Regression
Not a regression

## Your Environment
* Version used: Minio RELEASE.2019-03-27T22-35-21Z

### PR DESCRIPTION
**Pull request by poornas**
Fixes #7441 - Trim extra quotes prefixing/suffixing ETag in
CompleteMultipartUpload request and response

## How Has This Been Tested?

Use  aws cli to do a multipart upload. In complete multipart upload, the upload should succeed even if redundant quotes prefix/suffix the part ETag. See example in PR thread.
## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have added unit tests to cover my changes.
- [ ] I have added/updated functional tests in [mint](https://github.com/minio/mint). (If yes, add `mint` PR # here: )
- [x] All new and existing tests passed.

### CODE REVIEW

File: cmd/object-handlers-common.go [hunk 1]
```diff
@@ -19,14 +19,18 @@ package cmd
...
+	"regexp"
 	"time"
 
 	"github.com/minio/minio/cmd/crypto"
 	"github.com/minio/minio/pkg/event"
 	"github.com/minio/minio/pkg/handlers"
 )
 
+var (
+	etagRegex = regexp.MustCompile("\"*?([^\"]*?)\"*?$")
```
Comment (harshavardhana) [inline cmd/object-handlers-common.go:31]: Does S3 support any number of double quotes ?

**Review by harshavardhana — CHANGES_REQUESTED** [review]

**Comment by minio-ops** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-compression-xl.sh | :heavy_check_mark: |
| mint-xl.sh | :heavy_check_mark: |
| mint-compression-fs.sh | :heavy_check_mark: |
| mint-worm.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :x: [more...](#2100fabb-e461-4797-b570-e664cf4defca) |
| mint-compression-dist-xl.sh | :x: [more...](#06821321-90b2-4045-9059-9c2b5840dffa) |
| mint-dist-xl.sh | :x: [more...](#38f15299-4123-4d46-ad6a-79d039be13e1) |
<a name="06821321-90b2-4045-9059-9c2b5840dffa"></a>
### 7442-baec183/mint-compression-dist-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.51:32746
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 5cbd9f93ce51:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 2 minutes and 9 seconds
(2/14) Running aws-sdk-java tests ... done in 4 seconds
(3/14) Running aws-sdk-php tests ... done in 1 minutes and 17 seconds
(4/14) Running aws-sdk-ruby tests ... done in 52 seconds
(5/14) Running awscli tests ... done in 1 minutes and 51 seconds
(6/14) Running healthcheck tests ... done in 0 seconds
(7/14) Running mc tests ... done in 37 seconds
(8/14) Running minio-dotnet tests ... done in 47 seconds
(9/14) Running minio-go tests ... done in 1 minutes and 58 seconds
(10/14) Running minio-java tests ... FAILED in 3 minutes and 26 seconds
{
  "name": "minio-java",
  "function": "listObjects(final String bucketName, final String prefix, final boolean recursive)",
  "args": "prefix :minio, recursive: true",
  "duration": 185300,
  "status": "FAIL",
  "error": "java.net.ConnectException: Failed to connect to /72.28.97.51:32746 >>> [okhttp3.internal.connection.RealConnection.connectSocket(RealConnection.java:249), okhttp3.internal.connection.RealConnection.connect(RealConnection.java:167), okhttp3.internal.connection.StreamAllocation.findConnection(StreamAllocation.java:257), okhttp3.internal.connection.StreamAllocation.findHealthyConnection(StreamAllocation.java:135), okhttp3.internal.connection.StreamAllocation.newStream(StreamAllocation.java:114), okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:42), okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147), okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121), okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:94), okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147), okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121), okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93), okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147), okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:125), okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147), okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121), okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:264), okhttp3.RealCall.execute(RealCall.java:93), io.minio.MinioClient.executeReq(MinioClient.java:1097), io.minio.MinioClient.execute(MinioClient.java:1056), io.minio.MinioClient.executePost(MinioClient.java:1354), io.minio.MinioClient.removeObject(MinioClient.java:2625), io.minio.MinioClient.access$000(MinioClient.java:152), io.minio.MinioClient$3$1.populate(MinioClient.java:2697), io.minio.MinioClient$3$1.hasNext(MinioClient.java:2719), FunctionalTest.listObject_test5(FunctionalTest.java:1476), FunctionalTest.runTests(FunctionalTest.java:2985), FunctionalTest.main(FunctionalTest.java:3121)]"
}

Executed 9 out of 14 tests successfully.
```
<a name="2100fabb-e461-4797-b570-e664cf4defca"></a>
### 7442-baec183/mint-large-bucket.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.59:30197
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 7f01fab4740b:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... FAILED in 1 seconds
{
  "alert": "",
  "args": {
    "bucketName": "aws-sdk-go-test-0na6k65a9rlfd9",
    "expiry": 60000000000,
    "objectName": "presignedTest"
  },
  "duration": 296,
  "error": "RequestError: send request failed\ncaused by: Put http://72.28.97.59:30197/aws-sdk-go-test-0na6k65a9rlfd9: dial tcp 72.28.97.59:30197: connect: connection refused",
  "function": "PresignedPut",
  "message": "AWS SDK Go CreateBucket Failed",
  "name": "aws-sdk-go",
  "status": "FAIL"
}

Executed 0 out of 14 tests successfully.
```
<a name="38f15299-4123-4d46-ad6a-79d039be13e1"></a>
### 7442-baec183/mint-dist-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.53:32114
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 9cbe60ec2cfb:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... FAILED in 6 minutes and 0 seconds
{
  "alert": "",
  "args": {
    "bucketName": "aws-sdk-go-test-er32qo4ei2jnrg",
    "expiry": 60000000000,
    "objectName": "presignedTest"
  },
  "duration": 360017,
  "error": "XMinioServerNotInitialized: Server not initialized, please try again.\n\tstatus code: 503, request id: 15907F02450EC7E4, host id: ",
  "function": "PresignedPut",
  "message": "AWS SDK Go CreateBucket Failed",
  "name": "aws-sdk-go",
  "status": "FAIL"
}

Executed 0 out of 14 tests successfully.
```

File: cmd/object-handlers-common.go (hunk 1 above)
Comment (poornas) [reply cmd/object-handlers-common.go:31]: AWS strips off any number of prefix or suffix quotes around part ETag and completes multipart upload, whereas minio fails with internal error.fs and xl CompleteMultipartUpload operation needs to canonicalize ETag for part before using it.
```
➜  ~ aws s3api create-multipart-upload   --bucket tbucket11 --key etag2 --endpoint-url http://localhost:9000
{
    "Bucket": "tbucket11", 
    "UploadId": "10786eee-45a3-41b4-9148-01098858801a", 
    "Key": "etag2"
}
➜  ~ aws s3api upload-part --upload-id 10786eee-45a3-41b4-9148-01098858801a --bucket tbucket11   --key etag2 --part-number 1  --body /home/kris/Downloads/dump/large5243880.txt --endpoint-url http://localhost:9000
{
    "ETag": "\"60a6c45ad32da4cee4fffe1ddc982a8b\""
}
➜  ~ aws s3api upload-part --upload-id 10786eee-45a3-41b4-9148-01098858801a --bucket tbucket11   --key etag2 --part-number 2  --body /home/kris/Downloads/dump/smallfile --endpoint-url http://localhost:9000
{
    "ETag": "\"57c743902b2fc8eea6ba3bb4fc58c8e8\""
}
➜  ~ aws s3api complete-multipart-upload --multipart-upload file:///home/kris/code/src/github.com/minio/mpuparts --bucket tbucket11 --key etag2   --upload-id 10786eee-45a3-41b4-9148-01098858801a --endpoint-url http://localhost:9000        

An error occurred (InternalError) when calling the CompleteMultipartUpload operation (reached max retries: 4): We encountered an internal error, please try again.

```

Comment (harshavardhana) [reply cmd/object-handlers-common.go:31]: Good to know.

**Comment by minio-ops** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-compression-xl.sh | :heavy_check_mark: |
| mint-compression-dist-xl.sh | :heavy_check_mark: |
| mint-compression-fs.sh | :heavy_check_mark: |
| mint-worm.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-dist-xl.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-xl.sh | :x: [more...](#73aafa4d-e366-493c-9a8e-e18b06e9f7c1) |
| mint-large-bucket.sh | :x: [more...](#b6b5715c-81ce-4a7d-b942-d66eca95c89b) |
<a name="b6b5715c-81ce-4a7d-b942-d66eca95c89b"></a>
### 7442-24ac04f/mint-large-bucket.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.52:31145
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 9b1f5f9643ea:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... FAILED in 1 seconds
{
  "alert": "",
  "args": {
    "bucketName": "aws-sdk-go-test-ywfkkdr9x169jv",
    "expiry": 60000000000,
    "objectName": "presignedTest"
  },
  "duration": 307,
  "error": "RequestError: send request failed\ncaused by: Put http://72.28.97.52:31145/aws-sdk-go-test-ywfkkdr9x169jv: dial tcp 72.28.97.52:31145: connect: connection refused",
  "function": "PresignedPut",
  "message": "AWS SDK Go CreateBucket Failed",
  "name": "aws-sdk-go",
  "status": "FAIL"
}

Executed 0 out of 14 tests successfully.
```
<a name="73aafa4d-e366-493c-9a8e-e18b06e9f7c1"></a>
### 7442-24ac04f/mint-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.57:30746
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 00683103c3fa:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 0 seconds
(2/14) Running aws-sdk-java tests ... done in 1 seconds
(3/14) Running aws-sdk-php tests ... done in 43 seconds
(4/14) Running aws-sdk-ruby tests ... done in 3 seconds
(5/14) Running awscli tests ... done in 1 minutes and 50 seconds
(6/14) Running healthcheck tests ... done in 0 seconds
(7/14) Running mc tests ... done in 24 seconds
(8/14) Running minio-dotnet tests ... done in 30 seconds
(9/14) Running minio-go tests ... done in 45 seconds
(10/14) Running minio-java tests ... done in 2 minutes and 8 seconds
(11/14) Running minio-js tests ... done in 40 seconds
(12/14) Running minio-py tests ... FAILED in 4 minutes and 5 seconds
{
  "error": "Traceback (most recent call last):\n  File \"/mint/run/core/minio-py/tests.py\", line 1220, in test_presigned_get_object_expiry_5sec\n    object_name).get_exception()\nminio.error.AccessDenied: AccessDenied: message: Access Denied\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"/mint/run/core/minio-py/tests.py\", line 1885, in main\n    test_presigned_get_object_expiry_5sec(client, log_output)\n  File \"/mint/run/core/minio-py/tests.py\", line 1228, in test_presigned_get_object_expiry_5sec\n    raise Exception(err)\nException: AccessDenied: message: Access Denied\n",
  "args": {
    "object_name": "352e0074-6cd1-454f-ad37-6a6f22516415",
    "bucket_name": "minio-py-test-f2be60f2-d86d-492a-8a44-124c5963946c"
  },
  "name": "minio-py:test_presigned_get_object_expiry_5sec",
  "status": "FAIL",
  "duration": 102,
  "message": "AccessDenied: message: Access Denied",
  "function": "presigned_get_object(bucket_name, object_name, expires, response_headers, request_date)"
}

Executed 11 out of 14 tests successfully.
```

**Review by harshavardhana — APPROVED** [review]

**Review by kannappanr — APPROVED** [review]
LGTM
