### PR TITLE
Remove background policy reload, instead read policy from backend

### LINKED ISSUE #7723: MinIO instances are out of sync after uploading a file to a bucket when running in GCS Gateway mode.
MinIO instances are out of sync after uploading a file to a bucket when running in GCS Gateway mode.

## Expected Behavior

All MinIO instances should be in sync with GCS after uploading a file to a bucket when running in GCS Gateway mode.

## Current Behavior

Only one instance is in sync with GCS after uploading a file to a bucket when running in GCS Gateway mode.

## Steps to Reproduce (for bugs)

1. Start two instances of MinIO in GCS Gateway mode 

```
docker run --rm -p 9000:9000 --name gcs-s3-1 -v <credentials.json path>:/credentials.json \
    -e "GOOGLE_APPLICATION_CREDENTIALS=/credentials.json" \
    -e "MINIO_ACCESS_KEY=acceskeygoeshere" \
    -e "MINIO_SECRET_KEY=secretkeygoeshere" \
    minio/minio:RELEASE.2019-04-09T01-22-30Z gateway gcs mygcpproject
```

```
docker run --rm -p 9001:9000 --name gcs-s3-2 -v <credentials.json path>:/credentials.json \
    -e "GOOGLE_APPLICATION_CREDENTIALS=/credentials.json" \
    -e "MINIO_ACCESS_KEY=acceskeygoeshere" \
    -e "MINIO_SECRET_KEY=secretkeygoeshere" \
    minio/minio:RELEASE.2019-04-09T01-22-30Z gateway gcs mygcpproject
```

On instance that is exposed on port 9000, via web interface

2. Create a new bucket.

3. Change bucket policy to ReadOnly for all users

4. Upload the file

5. Use REST API on instance that is exposed on port 9001 to download the file

The result will be simmilar to:

```
* Preparing request to http://localhost:9001/mw456/foo.yaml
* Using libcurl/7.54.0 LibreSSL/2.6.5 zlib/1.2.11 nghttp2/1.24.1
* Current time is 2019-05-30T18:34:44.509Z
* Disable timeout
* Enable automatic URL encoding
* Disable SSL validation
* Enable cookie sending with jar of 0 cookies
* Found bundle for host localhost: 0x7fd9bd46d230 [can pipeline]
* Re-using existing connection! (#17) with host localhost
* Connected to localhost (::1) port 9001 (#17)

> GET /mw456/foo.yaml HTTP/1.1
> Host: localhost:9001
> User-Agent: insomnia/6.5.3
> Accept: */*

< HTTP/1.1 403 Forbidden
< Accept-Ranges: bytes
< Content-Security-Policy: block-all-mixed-content
< Content-Type: application/xml
< Server: Minio/RELEASE.2019-04-09T01-22-30Z
< Vary: Origin
< X-Amz-Request-Id: 15A389AFE3EF39B0
< X-Xss-Protection: 1; mode=block
< Date: Thu, 30 May 2019 18:34:44 GMT
< Transfer-Encoding: chunked


* Received 259 B chunk
* Received 5 B chunk
* Connection #17 to host localhost left intact
```

## Context

When running MinIO on kubernetes the response to download request cycles with `n-1` * `403 Forbidden` and 1 * `200 OK` for `n` pods running MinIO.

## Your Environment

* Version used (`minio version`): RELEASE.2019-04-09T01-22-30Z
* Link to your project: https://github.com/kyma-project

### PR DESCRIPTION
**Pull request by harshavardhana**
## Description
Remove background policy reload, instead read policy from backend

## Motivation and Context
Inconsistencies can arise after applying bucket policies in
gateway mode, since all gateway instances do not share a
common shared state. This is by design to keep gateway as
share nothing architecture.

This PR fixes such inconsistencies by reloading policy
if any from the backend.

Fixes #7723

## Regression
No, this was a design issue

## How Has This Been Tested?
Setting up gateway instances as mentioned in #7723 

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added unit tests to cover my changes.
- [ ] I have added/updated functional tests in [mint](https://github.com/minio/mint). (If yes, add `mint` PR # here: )
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by minio-ops** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-compression-xl.sh | :heavy_check_mark: |
| mint-xl.sh | :heavy_check_mark: |
| mint-compression-dist-xl.sh | :heavy_check_mark: |
| mint-compression-fs.sh | :heavy_check_mark: |
| mint-worm.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :x: [more...](#a44c7591-007e-4f93-bf80-a3fa6d598308) |
| mint-dist-xl.sh | :x: [more...](#3b8e299c-aa9a-4877-9ea0-dc86b462ceca) |
<a name="3b8e299c-aa9a-4877-9ea0-dc86b462ceca"></a>
### 7727-d31d109/mint-dist-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.58:30628
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp c00da50fba3a:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 0 seconds
(2/14) Running aws-sdk-java tests ... done in 1 seconds
(3/14) Running aws-sdk-php tests ... done in 42 seconds
(4/14) Running aws-sdk-ruby tests ... done in 3 seconds
(5/14) Running awscli tests ... done in 1 minutes and 54 seconds
(6/14) Running healthcheck tests ... done in 0 seconds
(7/14) Running mc tests ... done in 56 seconds
(8/14) Running minio-dotnet tests ... done in 35 seconds
(9/14) Running minio-go tests ... done in 48 seconds
(10/14) Running minio-java tests ... FAILED in 35 seconds
{
  "name": "minio-java",
  "function": "listIncompleteUploads(final String bucketName, final String prefix, final boolean recursive)",
  "args": "prefix: minio, recursive: true",
  "duration": 305,
  "status": "FAIL",
  "error": "error occurred\nErrorResponse(code=SlowDown, message=Please reduce your request, bucketName=minio-java-test-2oqdhd6, objectName=minio-java-test-3a27d8m, resource=/minio-java-test-2oqdhd6/minio-java-test-3a27d8m, requestId=15A3B137DC0B8F19, hostId=29454d72-78f8-4076-ace8-3b26b95077fd)\nrequest={method=DELETE, url=http://72.28.97.58:30628/minio-java-test-2oqdhd6/minio-java-test-3a27d8m?uploadId=d162e071-6edb-4c70-ac33-65540456b7db, headers=Host: 72.28.97.58:30628\nUser-Agent: MinIO (amd64; amd64) minio-java/dev\nx-amz-content-sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855\nx-amz-date: 20190531T063909Z\nAuthorization: AWS4-HMAC-SHA256 Credential=*REDACTED*/20190531/us-east-1/s3/aws4_request, SignedHeaders=host;x-amz-content-sha256;x-amz-date, Signature=*REDACTED*\n}\nresponse={code=503, headers=Accept-Ranges: bytes\nContent-Security-Policy: block-all-mixed-content\nContent-Type: application/xml\nRetry-After: 120\nServer: MinIO/DEVELOPMENT.2019-05-31T06-20-38Z\nVary: Origin\nX-Amz-Request-Id: 15A3B137DC0B8F19\nX-Minio-Deployment-Id: 29454d72-78f8-4076-ace8-3b26b95077fd\nX-Xss-Protection: 1; mode=block\nDate: Fri, 31 May 2019 06:39:09 GMT\nTransfer-Encoding: chunked\n}\n >>> [io.minio.MinioClient.executeReq(MinioClient.java:1204), io.minio.MinioClient.execute(MinioClient.java:1070), io.minio.MinioClient.executeDelete(MinioClient.java:1347), io.minio.MinioClient.abortMultipartUpload(MinioClient.java:5149), io.minio.MinioClient.putObject(MinioClient.java:4337), io.minio.MinioClient.putObject(MinioClient.java:4183), FunctionalTest.listIncompleteUploads_test3(FunctionalTest.java:1679), FunctionalTest.runTests(FunctionalTest.java:2990), FunctionalTest.main(FunctionalTest.java:3118)]"
}

Executed 9 out of 14 tests successfully.
```
<a name="a44c7591-007e-4f93-bf80-a3fa6d598308"></a>
### 7727-d31d109/mint-large-bucket.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.59:32057
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp b6cb818c453f:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 2 seconds
(2/14) Running aws-sdk-java tests ... done in 1 seconds
(3/14) Running aws-sdk-php tests ... done in 48 seconds
(4/14) Running aws-sdk-ruby tests ... done in 13 seconds
(5/14) Running awscli tests ... done in 2 minutes and 12 seconds
(6/14) Running healthcheck tests ... done in 0 seconds
(7/14) Running mc tests ... FAILED in 2 minutes and 30 seconds
{
  "name": "mc",
  "duration": "111047",
  "function": "test_mirror_list_objects_storage_class",
  "status": "FAIL",
  "error": "/mint/run/core/mc/mc --config-dir /tmp/.mc-11177 --quiet --no-color mirror --storage-class REDUCED_REDUNDANCY /mint/data myminio/mc-test-bucket-14999  >>> \n`/mint/data/datafile-1-MB` -> `myminio/mc-test-bucket-14999/datafile-1-MB`\n`/mint/data/datafile-1-b` -> `myminio/mc-test-bucket-14999/datafile-1-b`\n`/mint/data/datafile-0-b` -> `myminio/mc-test-bucket-14999/datafile-0-b`\n`/mint/data/datafile-1-kB` -> `myminio/mc-test-bucket-14999/datafile-1-kB`\n`/mint/data/datafile-1.03-MB` -> `myminio/mc-test-bucket-14999/datafile-1.03-MB`\n`/mint/data/datafile-10-kB` -> `myminio/mc-test-bucket-14999/datafile-10-kB`\n`/mint/data/datafile-10-MB` -> `myminio/mc-test-bucket-14999/datafile-10-MB`\n`/mint/data/datafile-100-kB` -> `myminio/mc-test-bucket-14999/datafile-100-kB`\n`/mint/data/datafile-11-MB` -> `myminio/mc-test-bucket-14999/datafile-11-MB`\n`/mint/data/datafile-129-MB` -> `myminio/mc-test-bucket-14999/datafile-129-MB`\n`/mint/data/datafile-33-kB` -> `myminio/mc-test-bucket-14999/datafile-33-kB`\n`/mint/data/datafile-6-MB` -> `myminio/mc-test-bucket-14999/datafile-6-MB`\n`/mint/data/datafile-5243880-b` -> `myminio/mc-test-bucket-14999/datafile-5243880-b`\n`/mint/data/datafile-65-MB` -> `myminio/mc-test-bucket-14999/datafile-65-MB`\n`/mint/data/datafile-5-MB` -> `myminio/mc-test-bucket-14999/datafile-5-MB`\nmc: <ERROR> Failed to copy `/mint/data/datafile-11-MB`. Please reduce your request\nmc: <ERROR> Failed to copy `/mint/data/datafile-129-MB`. Please reduce your request\nmc: <ERROR> Failed to copy `/mint/data/datafile-65-MB`. Please reduce your request\nTotal: 233.17 MiB, Transferred: 550.55 MiB, Speed: 4.96 MiB/s"
}

Executed 6 out of 14 tests successfully.
```

**Comment by minio-ops** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-xl.sh | :heavy_check_mark: |
| mint-compression-dist-xl.sh | :heavy_check_mark: |
| mint-compression-fs.sh | :heavy_check_mark: |
| mint-worm.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-compression-xl.sh | :x: [more...](#b95940f1-bc22-4308-a2b0-faf9626062e7) |
| mint-large-bucket.sh | :x: [more...](#d72290d2-29dd-4d72-80af-cb85ecde2ce6) |
| mint-dist-xl.sh | :x: [more...](#fa96f369-c73f-488e-b1cc-2578124cfa93) |
<a name="fa96f369-c73f-488e-b1cc-2578124cfa93"></a>
### 7727-93cb149/mint-dist-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.57:31615
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 5731dc3f5456:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 0 seconds
(2/14) Running aws-sdk-java tests ... done in 1 seconds
(3/14) Running aws-sdk-php tests ... done in 43 seconds
(4/14) Running aws-sdk-ruby tests ... done in 3 seconds
(5/14) Running awscli tests ... done in 1 minutes and 56 seconds
(6/14) Running healthcheck tests ... done in 0 seconds
(7/14) Running mc tests ... done in 53 seconds
(8/14) Running minio-dotnet tests ... done in 33 seconds
(9/14) Running minio-go tests ... done in 49 seconds
(10/14) Running minio-java tests ... FAILED in 43 seconds
{
  "name": "minio-java",
  "function": "listIncompleteUploads(final String bucketName, final String prefix, final boolean recursive)",
  "args": "prefix: minio, recursive: true",
  "duration": 410,
  "status": "FAIL",
  "error": "error occurred\nErrorResponse(code=SlowDown, message=Please reduce your request, bucketName=minio-java-test-2ul3ods, objectName=minio-java-test-2qqoumr, resource=/minio-java-test-2ul3ods/minio-java-test-2qqoumr, requestId=15A3B2B054E833C2, hostId=3ea2bdbe-1155-4f9f-8bec-4fe226730af0)\nrequest={method=DELETE, url=http://72.28.97.57:31615/minio-java-test-2ul3ods/minio-java-test-2qqoumr?uploadId=ab3951bc-adc6-42f3-ad55-bae04d046c63, headers=Host: 72.28.97.57:31615\nUser-Agent: MinIO (amd64; amd64) minio-java/dev\nx-amz-content-sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855\nx-amz-date: 20190531T070606Z\nAuthorization: AWS4-HMAC-SHA256 Credential=*REDACTED*/20190531/us-east-1/s3/aws4_request, SignedHeaders=host;x-amz-content-sha256;x-amz-date, Signature=*REDACTED*\n}\nresponse={code=503, headers=Accept-Ranges: bytes\nContent-Security-Policy: block-all-mixed-content\nContent-Type: application/xml\nRetry-After: 120\nServer: MinIO/DEVELOPMENT.2019-05-31T06-47-35Z\nVary: Origin\nX-Amz-Request-Id: 15A3B2B054E833C2\nX-Minio-Deployment-Id: 3ea2bdbe-1155-4f9f-8bec-4fe226730af0\nX-Xss-Protection: 1; mode=block\nDate: Fri, 31 May 2019 07:06:06 GMT\nTransfer-Encoding: chunked\n}\n >>> [io.minio.MinioClient.executeReq(MinioClient.java:1204), io.minio.MinioClient.execute(MinioClient.java:1070), io.minio.MinioClient.executeDelete(MinioClient.java:1347), io.minio.MinioClient.abortMultipartUpload(MinioClient.java:5149), io.minio.MinioClient.putObject(MinioClient.java:4337), io.minio.MinioClient.putObject(MinioClient.java:4183), FunctionalTest.listIncompleteUploads_test3(FunctionalTest.java:1679), FunctionalTest.runTests(FunctionalTest.java:2990), FunctionalTest.main(FunctionalTest.java:3118)]"
}

Executed 9 out of 14 tests successfully.
```
<a name="d72290d2-29dd-4d72-80af-cb85ecde2ce6"></a>
### 7727-93cb149/mint-large-bucket.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.53:31972
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 8824fc7d9eb9:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 2 seconds
(2/14) Running aws-sdk-java tests ... done in 1 seconds
(3/14) Running aws-sdk-php tests ... done in 49 seconds
(4/14) Running aws-sdk-ruby tests ... done in 14 seconds
(5/14) Running awscli tests ... done in 1 minutes and 13 seconds
(6/14) Running healthcheck tests ... done in 0 seconds
(7/14) Running mc tests ... FAILED in 2 minutes and 53 seconds
{
  "name": "mc",
  "duration": "138010",
  "function": "test_mirror_list_objects_storage_class",
  "status": "FAIL",
  "error": "/mint/run/core/mc/mc --config-dir /tmp/.mc-27157 --quiet --no-color mirror --storage-class REDUCED_REDUNDANCY /mint/data myminio/mc-test-bucket-14596  >>> \n`/mint/data/datafile-1-MB` -> `myminio/mc-test-bucket-14596/datafile-1-MB`\n`/mint/data/datafile-0-b` -> `myminio/mc-test-bucket-14596/datafile-0-b`\n`/mint/data/datafile-1.03-MB` -> `myminio/mc-test-bucket-14596/datafile-1.03-MB`\n`/mint/data/datafile-1-kB` -> `myminio/mc-test-bucket-14596/datafile-1-kB`\n`/mint/data/datafile-1-b` -> `myminio/mc-test-bucket-14596/datafile-1-b`\n`/mint/data/datafile-10-MB` -> `myminio/mc-test-bucket-14596/datafile-10-MB`\n`/mint/data/datafile-100-kB` -> `myminio/mc-test-bucket-14596/datafile-100-kB`\n`/mint/data/datafile-10-kB` -> `myminio/mc-test-bucket-14596/datafile-10-kB`\n`/mint/data/datafile-129-MB` -> `myminio/mc-test-bucket-14596/datafile-129-MB`\n`/mint/data/datafile-11-MB` -> `myminio/mc-test-bucket-14596/datafile-11-MB`\n`/mint/data/datafile-5-MB` -> `myminio/mc-test-bucket-14596/datafile-5-MB`\n`/mint/data/datafile-65-MB` -> `myminio/mc-test-bucket-14596/datafile-65-MB`\n`/mint/data/datafile-33-kB` -> `myminio/mc-test-bucket-14596/datafile-33-kB`\n`/mint/data/datafile-5243880-b` -> `myminio/mc-test-bucket-14596/datafile-5243880-b`\n`/mint/data/datafile-6-MB` -> `myminio/mc-test-bucket-14596/datafile-6-MB`\nmc: <ERROR> Failed to copy `/mint/data/datafile-129-MB`. Please reduce your request\nmc: <ERROR> Failed to copy `/mint/data/datafile-10-MB`. Please reduce your request\nmc: <ERROR> Failed to copy `/mint/data/datafile-11-MB`. Please reduce your request\nmc: <ERROR> Failed to copy `/mint/data/datafile-65-MB`. Please reduce your request\nTotal: 233.17 MiB, Transferred: 494.92 MiB, Speed: 3.59 MiB/s"
}

Executed 6 out of 14 tests successfully.
```
<a name="b95940f1-bc22-4308-a2b0-faf9626062e7"></a>
### 7727-93cb149/mint-compression-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.51:31089
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp cb4e114dbcc9:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... FAILED in 6 minutes and 0 seconds
{
  "alert": "",
  "args": {
    "bucketName": "aws-sdk-go-test-9rg19nizhgnzln",
    "expiry": 60000000000,
    "objectName": "presignedTest"
  },
  "duration": 360016,
  "error": "XMinioServerNotInitialized: Server not initialized, please try again.\n\tstatus code: 503, request id: 15A3B2B4DC1DFC02, host id: ",
  "function": "PresignedPut",
  "message": "AWS SDK Go CreateBucket Failed",
  "name": "aws-sdk-go",
  "status": "FAIL"
}

Executed 0 out of 14 tests successfully.
```

File: cmd/policy.go [hunk 1]
```diff
@@ -88,7 +87,15 @@ func (sys *PolicySys) IsAllowed(args policy.Args) bool {
 	if p, found := sys.bucketPolicyMap[args.BucketName]; found {
 		return p.IsAllowed(args)
 	}
-
+	objAPI := newObjectLayerFn()
+	if objAPI != nil {
+		config, err := objAPI.GetBucketPolicy(context.Background(), args.BucketName)
+		if err == nil {
+			// Update the cache with new policy.
+			sys.bucketPolicyMap[args.BucketName] = *config
```
Comment (kannappanr) [inline cmd/policy.go]: Why is the policy being cached, I thought the idea is to go to the backend to check the policy when we need to check. We might not have to check the policy for all the calls anyway

Comment (harshavardhana) [reply cmd/policy.go]: Oh yes it is better to hit the backend..

**Comment by minio-ops** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-compression-xl.sh | :heavy_check_mark: |
| mint-xl.sh | :heavy_check_mark: |
| mint-compression-dist-xl.sh | :heavy_check_mark: |
| mint-compression-fs.sh | :heavy_check_mark: |
| mint-worm.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :x: [more...](#890264a1-20ca-4807-8863-209117c42513) |
| mint-dist-xl.sh | :x: [more...](#de11c354-17ad-432f-ae70-0f0e9cb501ce) |
<a name="de11c354-17ad-432f-ae70-0f0e9cb501ce"></a>
### 7727-0e0b49b/mint-dist-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.61:31847
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp de531d1f753c:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 0 seconds
(2/14) Running aws-sdk-java tests ... done in 1 seconds
(3/14) Running aws-sdk-php tests ... done in 43 seconds
(4/14) Running aws-sdk-ruby tests ... done in 3 seconds
(5/14) Running awscli tests ... done in 1 minutes and 58 seconds
(6/14) Running healthcheck tests ... done in 0 seconds
(7/14) Running mc tests ... done in 58 seconds
(8/14) Running minio-dotnet tests ... done in 32 seconds
(9/14) Running minio-go tests ... done in 53 seconds
(10/14) Running minio-java tests ... FAILED in 42 seconds
{
  "name": "minio-java",
  "function": "presignedPutObject(String bucketName, String objectName, Integer expires)",
  "duration": 16,
  "status": "FAIL",
  "error": "java.lang.Exception: failed to create object. Response: Response{protocol=http/1.1, code=503, message=Service Unavailable, url=http://72.28.97.61:31847/minio-java-test-ad0hhk/minio-java-test-27gfltf?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=minio%2F20190531%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20190531T191336Z&X-Amz-Expires=3600&X-Amz-SignedHeaders=host&X-Amz-Signature=15049d6021ed052d68815d390b364cc4975f1fd0d3b43bfa46dce906f3ab7b84}, Response body: <?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<Error><Code>SlowDown</Code><Message>Please reduce your request</Message><Key>minio-java-test-27gfltf</Key><BucketName>minio-java-test-ad0hhk</BucketName><Resource>/minio-java-test-ad0hhk/minio-java-test-27gfltf</Resource><RequestId>15A3DA634E2B4386</RequestId><HostId>b63ca5fa-e858-4e49-acea-553960b90251</HostId></Error> >>> [FunctionalTest.writeObject(FunctionalTest.java:236), FunctionalTest.presignedPutObject_test2(FunctionalTest.java:1895), FunctionalTest.runTests(FunctionalTest.java:2999), FunctionalTest.main(FunctionalTest.java:3118)]"
}

Executed 9 out of 14 tests successfully.
```
<a name="890264a1-20ca-4807-8863-209117c42513"></a>
### 7727-0e0b49b/mint-large-bucket.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.59:32562
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp d6ee54301c55:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 2 seconds
(2/14) Running aws-sdk-java tests ... done in 3 seconds
(3/14) Running aws-sdk-php tests ... done in 47 seconds
(4/14) Running aws-sdk-ruby tests ... done in 13 seconds
(5/14) Running awscli tests ... done in 2 minutes and 13 seconds
(6/14) Running healthcheck tests ... done in 0 seconds
(7/14) Running mc tests ... FAILED in 2 minutes and 44 seconds
{
  "name": "mc",
  "duration": "123115",
  "function": "test_mirror_list_objects_storage_class",
  "status": "FAIL",
  "error": "/mint/run/core/mc/mc --config-dir /tmp/.mc-31510 --quiet --no-color mirror --storage-class REDUCED_REDUNDANCY /mint/data myminio/mc-test-bucket-25879  >>> \n`/mint/data/datafile-1-MB` -> `myminio/mc-test-bucket-25879/datafile-1-MB`\n`/mint/data/datafile-0-b` -> `myminio/mc-test-bucket-25879/datafile-0-b`\n`/mint/data/datafile-1-kB` -> `myminio/mc-test-bucket-25879/datafile-1-kB`\n`/mint/data/datafile-1-b` -> `myminio/mc-test-bucket-25879/datafile-1-b`\n`/mint/data/datafile-10-MB` -> `myminio/mc-test-bucket-25879/datafile-10-MB`\n`/mint/data/datafile-1.03-MB` -> `myminio/mc-test-bucket-25879/datafile-1.03-MB`\n`/mint/data/datafile-11-MB` -> `myminio/mc-test-bucket-25879/datafile-11-MB`\n`/mint/data/datafile-33-kB` -> `myminio/mc-test-bucket-25879/datafile-33-kB`\n`/mint/data/datafile-10-kB` -> `myminio/mc-test-bucket-25879/datafile-10-kB`\n`/mint/data/datafile-129-MB` -> `myminio/mc-test-bucket-25879/datafile-129-MB`\n`/mint/data/datafile-5-MB` -> `myminio/mc-test-bucket-25879/datafile-5-MB`\n`/mint/data/datafile-5243880-b` -> `myminio/mc-test-bucket-25879/datafile-5243880-b`\n`/mint/data/datafile-100-kB` -> `myminio/mc-test-bucket-25879/datafile-100-kB`\n`/mint/data/datafile-65-MB` -> `myminio/mc-test-bucket-25879/datafile-65-MB`\n`/mint/data/datafile-6-MB` -> `myminio/mc-test-bucket-25879/datafile-6-MB`\nmc: <ERROR> Failed to copy `/mint/data/datafile-129-MB`. Please reduce your request\nmc: <ERROR> Failed to copy `/mint/data/datafile-65-MB`. Please reduce your request\nmc: <ERROR> Failed to copy `/mint/data/datafile-11-MB`. Please reduce your request\nmc: <ERROR> Failed to copy `/mint/data/datafile-10-MB`. Please reduce your request\nTotal: 233.17 MiB, Transferred: 516.17 MiB, Speed: 4.19 MiB/s"
}

Executed 6 out of 14 tests successfully.
```

File: cmd/policy.go [hunk 2]
```diff
@@ -84,9 +83,23 @@ func (sys *PolicySys) IsAllowed(args policy.Args) bool {
...
-		return p.IsAllowed(args)
+	if globalIsGateway {
+		// When gateway is enabled, no cached value
+		// is used to validate bucket policies.
+		objAPI := newObjectLayerFn()
+		if objAPI != nil {
+			config, err := objAPI.GetBucketPolicy(context.Background(), args.BucketName)
+			if err == nil {
+				// Update the cache with new policy.
+				sys.bucketPolicyMap[args.BucketName] = *config
```
Comment (poornas) [inline cmd/policy.go]: policy doesn't need to be cached here in the map since we are always fetching policy from backend.

**Review by poornas — CHANGES_REQUESTED** [review]

File: cmd/policy.go (hunk 2 above)
Comment (harshavardhana) [reply cmd/policy.go]: This is for non gateways @poornas

Comment (poornas) [reply cmd/policy.go]: Line 94 can be removed since it is not needed to keep policy in map if globalIsGateway is true

**Comment by minio-ops** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-compression-xl.sh | :heavy_check_mark: |
| mint-xl.sh | :heavy_check_mark: |
| mint-compression-dist-xl.sh | :heavy_check_mark: |
| mint-compression-fs.sh | :heavy_check_mark: |
| mint-worm.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :x: [more...](#2f1392f8-1417-46d8-a973-d0ef1f650f11) |
| mint-dist-xl.sh | :x: [more...](#1a8ebf7f-b184-48cf-8010-41baf473402f) |
<a name="2f1392f8-1417-46d8-a973-d0ef1f650f11"></a>
### 7727-80b6f6e/mint-large-bucket.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.53:30564
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 8c3aa76b8143:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 1 seconds
(2/14) Running aws-sdk-java tests ... done in 2 seconds
(3/14) Running aws-sdk-php tests ... done in 47 seconds
(4/14) Running aws-sdk-ruby tests ... done in 14 seconds
(5/14) Running awscli tests ... done in 2 minutes and 7 seconds
(6/14) Running healthcheck tests ... done in 1 seconds
(7/14) Running mc tests ... FAILED in 1 minutes and 9 seconds
{
  "name": "mc",
  "duration": "66105",
  "function": "test_put_object_with_storage_class",
  "status": "FAIL",
  "error": "/mint/run/core/mc/mc --config-dir /tmp/.mc-29933 --quiet --no-color cp --storage-class REDUCED_REDUNDANCY /mint/data/datafile-1-MB myminio/mc-test-bucket-24014/mc-test-object-8743  >>> \n`/mint/data/datafile-1-MB` -> `myminio/mc-test-bucket-24014/mc-test-object-8743`\nmc: <ERROR> Failed to copy `/mint/data/datafile-1-MB`. Please reduce your request\nmc: <ERROR> Session safely terminated. To resume session `mc session resume HgPsgRTA`"
}

Executed 6 out of 14 tests successfully.
```
<a name="1a8ebf7f-b184-48cf-8010-41baf473402f"></a>
### 7727-80b6f6e/mint-dist-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.53:32447
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 7b097bfd84af:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 0 seconds
(2/14) Running aws-sdk-java tests ... done in 1 seconds
(3/14) Running aws-sdk-php tests ... done in 43 seconds
(4/14) Running aws-sdk-ruby tests ... done in 2 seconds
(5/14) Running awscli tests ... done in 1 minutes and 58 seconds
(6/14) Running healthcheck tests ... done in 1 seconds
(7/14) Running mc tests ... done in 56 seconds
(8/14) Running minio-dotnet tests ... done in 34 seconds
(9/14) Running minio-go tests ... done in 52 seconds
(10/14) Running minio-java tests ... FAILED in 40 seconds
{
  "name": "minio-java",
  "function": "listIncompleteUploads(String bucketName, String prefix)",
  "duration": 914,
  "status": "FAIL",
  "error": "error occurred\nErrorResponse(code=SlowDown, message=Please reduce your request, bucketName=minio-java-test-8lfepo, objectName=minio-java-test-25c5c1b, resource=/minio-java-test-8lfepo/minio-java-test-25c5c1b, requestId=15A453F7CFCC8B34, hostId=adec2d58-c49a-4eb9-9b6e-2c437fc8fff9)\nrequest={method=DELETE, url=http://72.28.97.53:32447/minio-java-test-8lfepo/minio-java-test-25c5c1b?uploadId=bc43e879-e46f-4dc0-8bd4-7b9d74bb45ba, headers=Host: 72.28.97.53:32447\nUser-Agent: MinIO (amd64; amd64) minio-java/dev\nx-amz-content-sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855\nx-amz-date: 20190602T082134Z\nAuthorization: AWS4-HMAC-SHA256 Credential=*REDACTED*/20190602/us-east-1/s3/aws4_request, SignedHeaders=host;x-amz-content-sha256;x-amz-date, Signature=*REDACTED*\n}\nresponse={code=503, headers=Accept-Ranges: bytes\nContent-Security-Policy: block-all-mixed-content\nContent-Type: application/xml\nRetry-After: 120\nServer: MinIO/DEVELOPMENT.2019-06-02T08-02-49Z\nVary: Origin\nX-Amz-Request-Id: 15A453F7CFCC8B34\nX-Minio-Deployment-Id: adec2d58-c49a-4eb9-9b6e-2c437fc8fff9\nX-Xss-Protection: 1; mode=block\nDate: Sun, 02 Jun 2019 08:21:35 GMT\nTransfer-Encoding: chunked\n}\n >>> [io.minio.MinioClient.executeReq(MinioClient.java:1204), io.minio.MinioClient.execute(MinioClient.java:1070), io.minio.MinioClient.executeDelete(MinioClient.java:1347), io.minio.MinioClient.abortMultipartUpload(MinioClient.java:5149), io.minio.MinioClient.putObject(MinioClient.java:4337), io.minio.MinioClient.putObject(MinioClient.java:4183), FunctionalTest.listIncompleteUploads_test2(FunctionalTest.java:1639), FunctionalTest.runTests(FunctionalTest.java:2989), FunctionalTest.main(FunctionalTest.java:3118)]"
}

Executed 9 out of 14 tests successfully.
```

File: cmd/policy.go (hunk 2 above)
Comment (harshavardhana) [reply cmd/policy.go]: Done

**Review by kannappanr — APPROVED** [review]
LGTM

**Comment by minio-ops** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-xl.sh | :heavy_check_mark: |
| mint-compression-dist-xl.sh | :heavy_check_mark: |
| mint-compression-fs.sh | :heavy_check_mark: |
| mint-worm.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-dist-xl.sh | :heavy_check_mark: |
| mint-compression-xl.sh | :x: [more...](#a4f0e714-2383-455a-82bb-8dc921b64eed) |
| mint-large-bucket.sh | :x: [more...](#e92990a7-133c-44a7-a0ee-d0f0c7f1a186) |
| mint-gateway-nas.sh | :x: [more...](#ba89ac20-ff5f-40d4-8589-a0a349b76bd7) |
<a name="e92990a7-133c-44a7-a0ee-d0f0c7f1a186"></a>
### 7727-6b6a575/mint-large-bucket.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.55:32683
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 842d63b39342:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 1 seconds
(2/14) Running aws-sdk-java tests ... done in 2 seconds
(3/14) Running aws-sdk-php tests ... done in 48 seconds
(4/14) Running aws-sdk-ruby tests ... done in 14 seconds
(5/14) Running awscli tests ... done in 2 minutes and 5 seconds
(6/14) Running healthcheck tests ... done in 0 seconds
(7/14) Running mc tests ... FAILED in 1 minutes and 59 seconds
{
  "name": "mc",
  "duration": "86798",
  "function": "test_mirror_list_objects_storage_class",
  "status": "FAIL",
  "error": "/mint/run/core/mc/mc --config-dir /tmp/.mc-27882 --quiet --no-color mirror --storage-class REDUCED_REDUNDANCY /mint/data myminio/mc-test-bucket-11080  >>> \n`/mint/data/datafile-1-MB` -> `myminio/mc-test-bucket-11080/datafile-1-MB`\n`/mint/data/datafile-0-b` -> `myminio/mc-test-bucket-11080/datafile-0-b`\n`/mint/data/datafile-1-b` -> `myminio/mc-test-bucket-11080/datafile-1-b`\n`/mint/data/datafile-1.03-MB` -> `myminio/mc-test-bucket-11080/datafile-1.03-MB`\n`/mint/data/datafile-1-kB` -> `myminio/mc-test-bucket-11080/datafile-1-kB`\n`/mint/data/datafile-10-kB` -> `myminio/mc-test-bucket-11080/datafile-10-kB`\n`/mint/data/datafile-10-MB` -> `myminio/mc-test-bucket-11080/datafile-10-MB`\n`/mint/data/datafile-11-MB` -> `myminio/mc-test-bucket-11080/datafile-11-MB`\n`/mint/data/datafile-100-kB` -> `myminio/mc-test-bucket-11080/datafile-100-kB`\n`/mint/data/datafile-5-MB` -> `myminio/mc-test-bucket-11080/datafile-5-MB`\n`/mint/data/datafile-33-kB` -> `myminio/mc-test-bucket-11080/datafile-33-kB`\n`/mint/data/datafile-129-MB` -> `myminio/mc-test-bucket-11080/datafile-129-MB`\n`/mint/data/datafile-5243880-b` -> `myminio/mc-test-bucket-11080/datafile-5243880-b`\n`/mint/data/datafile-6-MB` -> `myminio/mc-test-bucket-11080/datafile-6-MB`\n`/mint/data/datafile-65-MB` -> `myminio/mc-test-bucket-11080/datafile-65-MB`\nmc: <ERROR> Failed to copy `/mint/data/datafile-65-MB`. Please reduce your request\nmc: <ERROR> Failed to copy `/mint/data/datafile-129-MB`. Please reduce your request\nmc: <ERROR> Failed to copy `/mint/data/datafile-10-MB`. Please reduce your request\nTotal: 233.17 MiB, Transferred: 489.19 MiB, Speed: 5.64 MiB/s"
}

Executed 6 out of 14 tests successfully.
```
<a name="a4f0e714-2383-455a-82bb-8dc921b64eed"></a>
### 7727-6b6a575/mint-compression-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.57:31052
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 534f92d70256:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... FAILED in 3 seconds
{
  "alert": "",
  "args": {
    "bucketName": "aws-sdk-go-test-oc9vy2uclipppa",
    "expiry": 60000000000,
    "objectName": "presignedTest"
  },
  "duration": 3058,
  "error": "RequestError: send request failed\ncaused by: Put http://72.28.97.57:31052/aws-sdk-go-test-oc9vy2uclipppa: dial tcp 72.28.97.57:31052: connect: no route to host",
  "function": "PresignedPut",
  "message": "AWS SDK Go CreateBucket Failed",
  "name": "aws-sdk-go",
  "status": "FAIL"
}

Executed 0 out of 14 tests successfully.
```
<a name="ba89ac20-ff5f-40d4-8589-a0a349b76bd7"></a>
### 7727-6b6a575/mint-gateway-nas.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.56:32560
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 470d6f194457:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 0 seconds
(2/14) Running aws-sdk-java tests ... done in 1 seconds
(3/14) Running aws-sdk-php tests ... done in 41 seconds
(4/14) Running aws-sdk-ruby tests ... done in 2 seconds
(5/14) Running awscli tests ... done in 1 minutes and 45 seconds
(6/14) Running healthcheck tests ... done in 0 seconds
(7/14) Running mc tests ... done in 36 seconds
(8/14) Running minio-dotnet tests ... done in 25 seconds
(9/14) Running minio-go tests ... done in 36 seconds
(10/14) Running minio-java tests ... done in 14 seconds
(11/14) Running minio-js tests ... FAILED in 4 seconds
{
  "name": "minio-js",
  "function": "\"after all\" hook in \"functional tests\"",
  "duration": 6,
  "status": "FAIL",
  "error": "S3Error: The bucket you tried to delete is not empty at Object.parseError (node_modules/minio/dist/main/xml-parsers.js:56:11) at /mint/run/core/minio-js/node_modules/minio/dist/main/transformers.js:117:22 at DestroyableTransform._flush (node_modules/minio/dist/main/transformers.js:48:26) at DestroyableTransform.<anonymous> (node_modules/minio/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:135:12) at finishMaybe (node_modules/minio/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:371:12) at endWritable (node_modules/minio/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:378:3) at DestroyableTransform.Writable.end (node_modules/minio/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:356:5) at IncomingMessage.onend (_stream_readable.js:514:10) at endReadableNT (_stream_readable.js:978:12) at _combinedTickCallback (internal/process/next_tick.js:80:11) at process._tickCallback (internal/process/next_tick.js:104:9)"
}

Executed 10 out of 14 tests successfully.
```

**Review by poornas — APPROVED** [review]
LGTM
