### PR TITLE
Stop duplicate entry in Notification.xml

### LINKED ISSUE #7671: Do not allow duplicate entry in Notification
Duplicate entry allowed in Notification.xml

## Expected Behavior

adding the same event must error out stating 
``` 
mc: <ERROR> Cannot enable notification on the specified bucket. An object key name filtering rule defined with overlapping prefixes, overlapping suffixes, or overlapping combinations of prefixes and suffixes for the same event types.
 ```

## Current Behavior

Allows the addtion of duplicate entry in Notification.xml

## Steps to Reproduce (for bugs)

Try 
1. mc event add  myminio/test arn:minio:sqs::1:elasticsearch  --suffix .jpg

The notification XML entry is :
``` 
<?xml version="1.0" encoding="UTF-8"?>
<NotificationConfiguration>
   <QueueConfiguration>
      <Id />
      <Filter>
         <S3Key>
            <FilterRule>
               <Name>suffix</Name>
               <Value>.jpg</Value>
            </FilterRule>
         </S3Key>
      </Filter>
      <Event>s3:ObjectCreated:*</Event>
      <Event>s3:ObjectRemoved:*</Event>
      <Event>s3:ObjectAccessed:*</Event>
      <Queue>arn:minio:sqs::1:elasticsearch</Queue>
   </QueueConfiguration>
</NotificationConfiguration>
 ```

Now add the region in arn and re-run 
2. mc event add  myminio/test1 arn:minio:sqs:us-east-1:1:elasticsearch  --suffix .jpg
Console shows `Successfully added arn:minio:sqs:us-east-1:1:elasticsearch` 
While notification.xml has entry 
```
<?xml version="1.0" encoding="UTF-8"?>
<NotificationConfiguration>
   <QueueConfiguration>
      <Id />
      <Filter>
         <S3Key>
            <FilterRule>
               <Name>suffix</Name>
               <Value>.jpg</Value>
            </FilterRule>
         </S3Key>
      </Filter>
      <Event>s3:ObjectCreated:*</Event>
      <Event>s3:ObjectRemoved:*</Event>
      <Event>s3:ObjectAccessed:*</Event>
      <Queue>arn:minio:sqs::1:elasticsearch</Queue>
   </QueueConfiguration>
   <QueueConfiguration>
      <Id />
      <Filter>
         <S3Key>
            <FilterRule>
               <Name>suffix</Name>
               <Value>.jpg</Value>
            </FilterRule>
         </S3Key>
      </Filter>
      <Event>s3:ObjectCreated:*</Event>
      <Event>s3:ObjectRemoved:*</Event>
      <Event>s3:ObjectAccessed:*</Event>
      <Queue>arn:minio:sqs::1:elasticsearch</Queue>
   </QueueConfiguration>
</NotificationConfiguration>
```

Second scenerio
1. Run 
`mc mb myminio/mybucket
2. Event add using region in arn 
`mc event add  myminio/mybucket arn:minio:sqs:us-east-1:1:elasticsearch  --suffix .jpg`
3. Again run 
`mc event add  myminio/mybucket arn:minio:sqs:us-east-1:1:elasticsearch  --suffix .jpg`
Console shows `Successfully added arn:minio:sqs:us-east-1:1:elasticsearch` 

In this scenario it should error out stating duplicate entries.

## Regression

No

## Your Environment

* Version used (`minio version`):
* Environment name and version (e.g. nginx 1.9.1):
* Server type and version:
* Operating System and version (`uname -a`): 
* Link to your project:

### PR DESCRIPTION
**Pull request by sinhaashish**
Duplicate entry are allowed in Notification.xml

## Description

When we pass the region in ARN, duplicate entries get added in `Notification.xml`. 

## Motivation and Context

fixes #7671 

## Regression

Yes

## Types of changes

- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [X] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added unit tests to cover my changes.
- [ ] I have added/updated functional tests in [mint](https://github.com/minio/mint). (If yes, add `mint` PR # here: )
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by minio-ops** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-compression-xl.sh | :heavy_check_mark: |
| mint-xl.sh | :heavy_check_mark: |
| mint-compression-dist-xl.sh | :heavy_check_mark: |
| mint-compression-fs.sh | :heavy_check_mark: |
| mint-worm.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-dist-xl.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :x: [more...](#b6016b6a-25fe-4c70-91d9-6aec6cade914) |
<a name="b6016b6a-25fe-4c70-91d9-6aec6cade914"></a>
### 7690-a4b0a29/mint-large-bucket.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.56:31865
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 6dc2053808d3:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 2 seconds
(2/14) Running aws-sdk-java tests ... done in 1 seconds
(3/14) Running aws-sdk-php tests ... done in 49 seconds
(4/14) Running aws-sdk-ruby tests ... done in 14 seconds
(5/14) Running awscli tests ... done in 2 minutes and 4 seconds
(6/14) Running healthcheck tests ... done in 1 seconds
(7/14) Running mc tests ... FAILED in 2 minutes and 6 seconds
{
  "name": "mc",
  "duration": "101652",
  "function": "test_mirror_list_objects_storage_class",
  "status": "FAIL",
  "error": "/mint/run/core/mc/mc --config-dir /tmp/.mc-3173 --quiet --no-color mirror --storage-class REDUCED_REDUNDANCY /mint/data myminio/mc-test-bucket-25785  >>> \n`/mint/data/datafile-1-MB` -> `myminio/mc-test-bucket-25785/datafile-1-MB`\n`/mint/data/datafile-0-b` -> `myminio/mc-test-bucket-25785/datafile-0-b`\n`/mint/data/datafile-1-b` -> `myminio/mc-test-bucket-25785/datafile-1-b`\n`/mint/data/datafile-1.03-MB` -> `myminio/mc-test-bucket-25785/datafile-1.03-MB`\n`/mint/data/datafile-1-kB` -> `myminio/mc-test-bucket-25785/datafile-1-kB`\n`/mint/data/datafile-10-MB` -> `myminio/mc-test-bucket-25785/datafile-10-MB`\n`/mint/data/datafile-100-kB` -> `myminio/mc-test-bucket-25785/datafile-100-kB`\n`/mint/data/datafile-10-kB` -> `myminio/mc-test-bucket-25785/datafile-10-kB`\n`/mint/data/datafile-33-kB` -> `myminio/mc-test-bucket-25785/datafile-33-kB`\n`/mint/data/datafile-11-MB` -> `myminio/mc-test-bucket-25785/datafile-11-MB`\n`/mint/data/datafile-5243880-b` -> `myminio/mc-test-bucket-25785/datafile-5243880-b`\n`/mint/data/datafile-5-MB` -> `myminio/mc-test-bucket-25785/datafile-5-MB`\n`/mint/data/datafile-65-MB` -> `myminio/mc-test-bucket-25785/datafile-65-MB`\n`/mint/data/datafile-6-MB` -> `myminio/mc-test-bucket-25785/datafile-6-MB`\nmc: <ERROR> Failed to copy `/mint/data/datafile-65-MB`. Multiple disks failures, unable to write data.\nmc: <ERROR> Failed to copy `/mint/data/datafile-10-MB`. Multiple disks failures, unable to write data.\nTotal: 104.17 MiB, Transferred: 334.17 MiB, Speed: 3.29 MiB/s"
}

Executed 6 out of 14 tests successfully.
```

**Comment by minio-ops** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-compression-xl.sh | :heavy_check_mark: |
| mint-xl.sh | :heavy_check_mark: |
| mint-compression-dist-xl.sh | :heavy_check_mark: |
| mint-compression-fs.sh | :heavy_check_mark: |
| mint-worm.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-dist-xl.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :x: [more...](#141526ba-6947-47e9-8b75-1631df268436) |
<a name="141526ba-6947-47e9-8b75-1631df268436"></a>
### 7690-1765179/mint-large-bucket.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.51:31188
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 6af767f72034:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 2 seconds
(2/14) Running aws-sdk-java tests ... done in 1 seconds
(3/14) Running aws-sdk-php tests ... done in 48 seconds
(4/14) Running aws-sdk-ruby tests ... done in 13 seconds
(5/14) Running awscli tests ... done in 2 minutes and 4 seconds
(6/14) Running healthcheck tests ... done in 0 seconds
(7/14) Running mc tests ... FAILED in 2 minutes and 25 seconds
{
  "name": "mc",
  "duration": "122282",
  "function": "test_mirror_list_objects_storage_class",
  "status": "FAIL",
  "error": "/mint/run/core/mc/mc --config-dir /tmp/.mc-20510 --quiet --no-color mirror --storage-class REDUCED_REDUNDANCY /mint/data myminio/mc-test-bucket-18940  >>> \n`/mint/data/datafile-1-MB` -> `myminio/mc-test-bucket-18940/datafile-1-MB`\n`/mint/data/datafile-0-b` -> `myminio/mc-test-bucket-18940/datafile-0-b`\n`/mint/data/datafile-1.03-MB` -> `myminio/mc-test-bucket-18940/datafile-1.03-MB`\n`/mint/data/datafile-1-b` -> `myminio/mc-test-bucket-18940/datafile-1-b`\n`/mint/data/datafile-1-kB` -> `myminio/mc-test-bucket-18940/datafile-1-kB`\n`/mint/data/datafile-10-kB` -> `myminio/mc-test-bucket-18940/datafile-10-kB`\n`/mint/data/datafile-10-MB` -> `myminio/mc-test-bucket-18940/datafile-10-MB`\n`/mint/data/datafile-11-MB` -> `myminio/mc-test-bucket-18940/datafile-11-MB`\n`/mint/data/datafile-100-kB` -> `myminio/mc-test-bucket-18940/datafile-100-kB`\n`/mint/data/datafile-5-MB` -> `myminio/mc-test-bucket-18940/datafile-5-MB`\n`/mint/data/datafile-6-MB` -> `myminio/mc-test-bucket-18940/datafile-6-MB`\n`/mint/data/datafile-33-kB` -> `myminio/mc-test-bucket-18940/datafile-33-kB`\n`/mint/data/datafile-5243880-b` -> `myminio/mc-test-bucket-18940/datafile-5243880-b`\n`/mint/data/datafile-65-MB` -> `myminio/mc-test-bucket-18940/datafile-65-MB`\nmc: <ERROR> Failed to copy `/mint/data/datafile-10-MB`. Multiple disks failures, unable to write data.\nmc: <ERROR> Failed to copy `/mint/data/datafile-11-MB`. Multiple disks failures, unable to write data.\nmc: <ERROR> Failed to copy `/mint/data/datafile-65-MB`. Multiple disks failures, unable to write data.\nTotal: 104.17 MiB, Transferred: 411.05 MiB, Speed: 3.36 MiB/s"
}

Executed 6 out of 14 tests successfully.
```

File: pkg/event/config.go [hunk 1]
```diff
@@ -220,8 +221,15 @@ func (conf *Config) UnmarshalXML(d *xml.Decoder, start xml.StartElement) error {
 
 	// Empty queue list means user wants to delete the notification configuration.
 	if len(parsedConfig.QueueList) > 0 {
+		fmt.Println(parsedConfig.QueueList)
```
Comment (kannappanr) [inline pkg/event/config.go]: Please remove debug logs

Comment (sinhaashish) [reply pkg/event/config.go]: sorry, just missed it. removed now.

**Comment by minio-ops** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-xl.sh | :heavy_check_mark: |
| mint-compression-dist-xl.sh | :heavy_check_mark: |
| mint-compression-fs.sh | :heavy_check_mark: |
| mint-worm.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-dist-xl.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-compression-xl.sh | :x: [more...](#cdeb1cce-91f7-46f9-aca0-309bc0b3c340) |
| mint-large-bucket.sh | :x: [more...](#5bdde6db-981b-46ea-b6a0-2a093038aeec) |
<a name="cdeb1cce-91f7-46f9-aca0-309bc0b3c340"></a>
### 7690-0c793fd/mint-compression-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.56:31308
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 44fa4b42c434:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... FAILED in 6 minutes and 0 seconds
{
  "alert": "",
  "args": {
    "bucketName": "aws-sdk-go-test-t060x09vsc3crs",
    "expiry": 60000000000,
    "objectName": "presignedTest"
  },
  "duration": 360014,
  "error": "XMinioServerNotInitialized: Server not initialized, please try again.\n\tstatus code: 503, request id: 15A225B331DFBD06, host id: ",
  "function": "PresignedPut",
  "message": "AWS SDK Go CreateBucket Failed",
  "name": "aws-sdk-go",
  "status": "FAIL"
}

Executed 0 out of 14 tests successfully.
```
<a name="5bdde6db-981b-46ea-b6a0-2a093038aeec"></a>
### 7690-0c793fd/mint-large-bucket.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.57:30621
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp dad6701edaed:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 2 seconds
(2/14) Running aws-sdk-java tests ... done in 1 seconds
(3/14) Running aws-sdk-php tests ... done in 48 seconds
(4/14) Running aws-sdk-ruby tests ... done in 12 seconds
(5/14) Running awscli tests ... done in 2 minutes and 5 seconds
(6/14) Running healthcheck tests ... done in 0 seconds
(7/14) Running mc tests ... FAILED in 1 minutes and 55 seconds
{
  "name": "mc",
  "duration": "91915",
  "function": "test_mirror_list_objects_storage_class",
  "status": "FAIL",
  "error": "/mint/run/core/mc/mc --config-dir /tmp/.mc-11207 --quiet --no-color mirror --storage-class REDUCED_REDUNDANCY /mint/data myminio/mc-test-bucket-2552  >>> \n`/mint/data/datafile-0-b` -> `myminio/mc-test-bucket-2552/datafile-0-b`\n`/mint/data/datafile-1-MB` -> `myminio/mc-test-bucket-2552/datafile-1-MB`\n`/mint/data/datafile-1-kB` -> `myminio/mc-test-bucket-2552/datafile-1-kB`\n`/mint/data/datafile-1-b` -> `myminio/mc-test-bucket-2552/datafile-1-b`\n`/mint/data/datafile-100-kB` -> `myminio/mc-test-bucket-2552/datafile-100-kB`\n`/mint/data/datafile-1.03-MB` -> `myminio/mc-test-bucket-2552/datafile-1.03-MB`\n`/mint/data/datafile-10-kB` -> `myminio/mc-test-bucket-2552/datafile-10-kB`\n`/mint/data/datafile-11-MB` -> `myminio/mc-test-bucket-2552/datafile-11-MB`\n`/mint/data/datafile-33-kB` -> `myminio/mc-test-bucket-2552/datafile-33-kB`\n`/mint/data/datafile-10-MB` -> `myminio/mc-test-bucket-2552/datafile-10-MB`\n`/mint/data/datafile-5-MB` -> `myminio/mc-test-bucket-2552/datafile-5-MB`\n`/mint/data/datafile-5243880-b` -> `myminio/mc-test-bucket-2552/datafile-5243880-b`\n`/mint/data/datafile-65-MB` -> `myminio/mc-test-bucket-2552/datafile-65-MB`\n`/mint/data/datafile-6-MB` -> `myminio/mc-test-bucket-2552/datafile-6-MB`\nmc: <ERROR> Failed to copy `/mint/data/datafile-11-MB`. Multiple disks failures, unable to write data.\nmc: <ERROR> Failed to copy `/mint/data/datafile-65-MB`. Multiple disks failures, unable to write data.\nTotal: 104.17 MiB, Transferred: 350.24 MiB, Speed: 3.81 MiB/s"
}

Executed 6 out of 14 tests successfully.
```

**Comment by kannappanr** [comment]
@sinhaashish Can you check why `mc` mint test is failing in `large-bucket` setup? It seems to be consistently failing.

**Comment by sinhaashish** [comment]
> @sinhaashish Can you check why `mc` mint test is failing in `large-bucket` setup? It seems to be consistently failing.


I did an force push and the error didn't occur this time.

**Comment by minio-ops** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-compression-xl.sh | :heavy_check_mark: |
| mint-compression-dist-xl.sh | :heavy_check_mark: |
| mint-compression-fs.sh | :heavy_check_mark: |
| mint-worm.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-xl.sh | :x: [more...](#27a01689-14c9-4c9d-a818-67f4916f3a89) |
| mint-large-bucket.sh | :x: [more...](#7b367026-5f5d-4017-9da0-fbf9f127634c) |
| mint-dist-xl.sh | :x: [more...](#05b3d23c-9679-44ab-b219-b7934059d40f) |
<a name="27a01689-14c9-4c9d-a818-67f4916f3a89"></a>
### 7690-0706ee4/mint-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.61:32702
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 1a969a365513:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... FAILED in 6 minutes and 0 seconds
{
  "alert": "",
  "args": {
    "bucketName": "aws-sdk-go-test-nbwre26qq0udy4",
    "expiry": 60000000000,
    "objectName": "presignedTest"
  },
  "duration": 360017,
  "error": "XMinioServerNotInitialized: Server not initialized, please try again.\n\tstatus code: 503, request id: 15A36D1897481F7F, host id: ",
  "function": "PresignedPut",
  "message": "AWS SDK Go CreateBucket Failed",
  "name": "aws-sdk-go",
  "status": "FAIL"
}

Executed 0 out of 14 tests successfully.
```
<a name="05b3d23c-9679-44ab-b219-b7934059d40f"></a>
### 7690-0706ee4/mint-dist-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.52:31436
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 7adf621ee297:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 1 seconds
(2/14) Running aws-sdk-java tests ... done in 1 seconds
(3/14) Running aws-sdk-php tests ... done in 43 seconds
(4/14) Running aws-sdk-ruby tests ... done in 3 seconds
(5/14) Running awscli tests ... done in 1 minutes and 57 seconds
(6/14) Running healthcheck tests ... done in 0 seconds
(7/14) Running mc tests ... done in 1 minutes and 0 seconds
(8/14) Running minio-dotnet tests ... done in 44 seconds
(9/14) Running minio-go tests ... done in 1 minutes and 18 seconds
(10/14) Running minio-java tests ... FAILED in 1 minutes and 28 seconds
{
  "name": "minio-java",
  "function": "listIncompleteUploads(final String bucketName, final String prefix, final boolean recursive)",
  "args": "prefix: minio, recursive: true",
  "duration": 317,
  "status": "FAIL",
  "error": "error occurred\nErrorResponse(code=SlowDown, message=Please reduce your request, bucketName=minio-java-test-1rmupup, objectName=minio-java-test-3uqabk4, resource=/minio-java-test-1rmupup/minio-java-test-3uqabk4, requestId=15A36D2A3E973E3E, hostId=12624492-87a4-46e0-95c3-bd34546466ae)\nrequest={method=DELETE, url=http://72.28.97.52:31436/minio-java-test-1rmupup/minio-java-test-3uqabk4?uploadId=d3005d51-1315-4d28-b0ef-035f5fec023e, headers=Host: 72.28.97.52:31436\nUser-Agent: MinIO (amd64; amd64) minio-java/dev\nx-amz-content-sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855\nx-amz-date: 20190530T095204Z\nAuthorization: AWS4-HMAC-SHA256 Credential=*REDACTED*/20190530/us-east-1/s3/aws4_request, SignedHeaders=host;x-amz-content-sha256;x-amz-date, Signature=*REDACTED*\n}\nresponse={code=503, headers=Accept-Ranges: bytes\nContent-Security-Policy: block-all-mixed-content\nContent-Type: application/xml\nRetry-After: 120\nServer: MinIO/DEVELOPMENT.2019-05-30T09-31-45Z\nVary: Origin\nX-Amz-Request-Id: 15A36D2A3E973E3E\nX-Minio-Deployment-Id: 12624492-87a4-46e0-95c3-bd34546466ae\nX-Xss-Protection: 1; mode=block\nDate: Thu, 30 May 2019 09:52:04 GMT\nTransfer-Encoding: chunked\n}\n >>> [io.minio.MinioClient.executeReq(MinioClient.java:1204), io.minio.MinioClient.execute(MinioClient.java:1070), io.minio.MinioClient.executeDelete(MinioClient.java:1347), io.minio.MinioClient.abortMultipartUpload(MinioClient.java:5149), io.minio.MinioClient.putObject(MinioClient.java:4337), io.minio.MinioClient.putObject(MinioClient.java:4183), FunctionalTest.listIncompleteUploads_test3(FunctionalTest.java:1679), FunctionalTest.runTests(FunctionalTest.java:2990), FunctionalTest.main(FunctionalTest.java:3118)]"
}

Executed 9 out of 14 tests successfully.
```
<a name="7b367026-5f5d-4017-9da0-fbf9f127634c"></a>
### 7690-0706ee4/mint-large-bucket.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.53:30770
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 26e84a1b0ef9:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 3 seconds
(2/14) Running aws-sdk-java tests ... done in 1 seconds
(3/14) Running aws-sdk-php tests ... done in 48 seconds
(4/14) Running aws-sdk-ruby tests ... done in 11 seconds
(5/14) Running awscli tests ... done in 2 minutes and 14 seconds
(6/14) Running healthcheck tests ... done in 0 seconds
(7/14) Running mc tests ... done in 1 minutes and 7 seconds
(8/14) Running minio-dotnet tests ... done in 1 minutes and 8 seconds
(9/14) Running minio-go tests ... done in 1 minutes and 35 seconds
(10/14) Running minio-java tests ... FAILED in 1 minutes and 22 seconds
{
  "name": "minio-java",
  "function": "removeIncompleteUpload(String bucketName, String objectName)",
  "duration": 348,
  "status": "FAIL",
  "error": "error occurred\nErrorResponse(code=SlowDown, message=Please reduce your request, bucketName=minio-java-test-1tjjhio, objectName=minio-java-test-2n0dr90, resource=/minio-java-test-1tjjhio/minio-java-test-2n0dr90, requestId=15A36D3B9BAF624B, hostId=d9049f19-e49b-449e-8b9e-30c786c9b55c)\nrequest={method=DELETE, url=http://72.28.97.53:30770/minio-java-test-1tjjhio/minio-java-test-2n0dr90?uploadId=39915454-c9b7-4f78-83ad-f60ebef0321d, headers=Host: 72.28.97.53:30770\nUser-Agent: MinIO (amd64; amd64) minio-java/dev\nx-amz-content-sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855\nx-amz-date: 20190530T095318Z\nAuthorization: AWS4-HMAC-SHA256 Credential=*REDACTED*/20190530/us-east-1/s3/aws4_request, SignedHeaders=host;x-amz-content-sha256;x-amz-date, Signature=*REDACTED*\n}\nresponse={code=503, headers=Accept-Ranges: bytes\nContent-Security-Policy: block-all-mixed-content\nContent-Type: application/xml\nRetry-After: 120\nServer: MinIO/DEVELOPMENT.2019-05-30T09-31-45Z\nVary: Origin\nX-Amz-Request-Id: 15A36D3B9BAF624B\nX-Minio-Deployment-Id: d9049f19-e49b-449e-8b9e-30c786c9b55c\nX-Xss-Protection: 1; mode=block\nDate: Thu, 30 May 2019 09:53:18 GMT\nTransfer-Encoding: chunked\n}\n >>> [io.minio.MinioClient.executeReq(MinioClient.java:1204), io.minio.MinioClient.execute(MinioClient.java:1070), io.minio.MinioClient.executeDelete(MinioClient.java:1347), io.minio.MinioClient.abortMultipartUpload(MinioClient.java:5149), io.minio.MinioClient.putObject(MinioClient.java:4337), io.minio.MinioClient.putObject(MinioClient.java:4183), FunctionalTest.removeIncompleteUploads_test(FunctionalTest.java:1719), FunctionalTest.runTests(FunctionalTest.java:2992), FunctionalTest.main(FunctionalTest.java:3118)]"
}

Executed 9 out of 14 tests successfully.
```

**Comment by nitisht** [comment]
> I did an force push and the error didn't occur this time.

AWS SDK Go tests are failing with server not initialised error (MinIO XL Mode), this needs to be checked

```
(1/14) Running aws-sdk-go tests ... FAILED in 6 minutes and 0 seconds
{
  "alert": "",
  "args": {
    "bucketName": "aws-sdk-go-test-nbwre26qq0udy4",
    "expiry": 60000000000,
    "objectName": "presignedTest"
  },
  "duration": 360017,
  "error": "XMinioServerNotInitialized: Server not initialized, please try again.\n\tstatus code: 503, request id: 15A36D1897481F7F, host id: ",
  "function": "PresignedPut",
  "message": "AWS SDK Go CreateBucket Failed",
  "name": "aws-sdk-go",
  "status": "FAIL"
}
```

**Comment by minio-ops** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-compression-xl.sh | :heavy_check_mark: |
| mint-compression-dist-xl.sh | :heavy_check_mark: |
| mint-compression-fs.sh | :heavy_check_mark: |
| mint-worm.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-xl.sh | :x: [more...](#59e207c7-0f9b-4550-b184-722f7fb1fc0e) |
| mint-large-bucket.sh | :x: [more...](#00f73eee-e4ed-49de-bdd7-5f4400a827c1) |
| mint-dist-xl.sh | :x: [more...](#9b4e237c-42ea-4506-81c9-d130c44e5555) |
<a name="00f73eee-e4ed-49de-bdd7-5f4400a827c1"></a>
### 7690-b2ba49b/mint-large-bucket.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.53:32143
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp db37eaabcedd:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 1 seconds
(2/14) Running aws-sdk-java tests ... done in 2 seconds
(3/14) Running aws-sdk-php tests ... done in 52 seconds
(4/14) Running aws-sdk-ruby tests ... done in 15 seconds
(5/14) Running awscli tests ... done in 2 minutes and 7 seconds
(6/14) Running healthcheck tests ... done in 0 seconds
(7/14) Running mc tests ... FAILED in 8 minutes and 28 seconds
{
  "name": "mc",
  "duration": "177909",
  "function": "test_mirror_list_objects_storage_class",
  "status": "FAIL",
  "error": "/mint/run/core/mc/mc --config-dir /tmp/.mc-22695 --quiet --no-color mirror --storage-class REDUCED_REDUNDANCY /mint/data myminio/mc-test-bucket-23770  >>> \n`/mint/data/datafile-1-MB` -> `myminio/mc-test-bucket-23770/datafile-1-MB`\n`/mint/data/datafile-0-b` -> `myminio/mc-test-bucket-23770/datafile-0-b`\n`/mint/data/datafile-1-kB` -> `myminio/mc-test-bucket-23770/datafile-1-kB`\n`/mint/data/datafile-1-b` -> `myminio/mc-test-bucket-23770/datafile-1-b`\n`/mint/data/datafile-10-MB` -> `myminio/mc-test-bucket-23770/datafile-10-MB`\n`/mint/data/datafile-10-kB` -> `myminio/mc-test-bucket-23770/datafile-10-kB`\n`/mint/data/datafile-1.03-MB` -> `myminio/mc-test-bucket-23770/datafile-1.03-MB`\n`/mint/data/datafile-100-kB` -> `myminio/mc-test-bucket-23770/datafile-100-kB`\n`/mint/data/datafile-11-MB` -> `myminio/mc-test-bucket-23770/datafile-11-MB`\n`/mint/data/datafile-129-MB` -> `myminio/mc-test-bucket-23770/datafile-129-MB`\n`/mint/data/datafile-33-kB` -> `myminio/mc-test-bucket-23770/datafile-33-kB`\n`/mint/data/datafile-5243880-b` -> `myminio/mc-test-bucket-23770/datafile-5243880-b`\n`/mint/data/datafile-65-MB` -> `myminio/mc-test-bucket-23770/datafile-65-MB`\n`/mint/data/datafile-6-MB` -> `myminio/mc-test-bucket-23770/datafile-6-MB`\n`/mint/data/datafile-5-MB` -> `myminio/mc-test-bucket-23770/datafile-5-MB`\nmc: <ERROR> Failed to copy `/mint/data/datafile-129-MB`. Please reduce your request\nmc: <ERROR> Failed to copy `/mint/data/datafile-65-MB`. Please reduce your request\nTotal: 233.17 MiB, Transferred: 404.46 MiB, Speed: 2.27 MiB/s"
}

Executed 6 out of 14 tests successfully.
```
<a name="9b4e237c-42ea-4506-81c9-d130c44e5555"></a>
### 7690-b2ba49b/mint-dist-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.58:31183
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 526054c90589:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 0 seconds
(2/14) Running aws-sdk-java tests ... done in 1 seconds
(3/14) Running aws-sdk-php tests ... done in 43 seconds
(4/14) Running aws-sdk-ruby tests ... done in 2 seconds
(5/14) Running awscli tests ... done in 1 minutes and 54 seconds
(6/14) Running healthcheck tests ... done in 1 seconds
(7/14) Running mc tests ... done in 45 seconds
(8/14) Running minio-dotnet tests ... done in 34 seconds
(9/14) Running minio-go tests ... done in 48 seconds
(10/14) Running minio-java tests ... FAILED in 42 seconds
{
  "name": "minio-java",
  "function": "listIncompleteUploads(final String bucketName, final String prefix, final boolean recursive)",
  "args": "prefix: minio, recursive: true",
  "duration": 551,
  "status": "FAIL",
  "error": "error occurred\nErrorResponse(code=SlowDown, message=Please reduce your request, bucketName=minio-java-test-eqns0h, objectName=minio-java-test-hricml, resource=/minio-java-test-eqns0h/minio-java-test-hricml, requestId=15A3B51FE947C4F5, hostId=edb18138-a161-4889-85af-076b546c2a46)\nrequest={method=DELETE, url=http://72.28.97.58:31183/minio-java-test-eqns0h/minio-java-test-hricml?uploadId=ee877a57-e0cf-4ab9-b2bc-fef641ce4281, headers=Host: 72.28.97.58:31183\nUser-Agent: MinIO (amd64; amd64) minio-java/dev\nx-amz-content-sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855\nx-amz-date: 20190531T075044Z\nAuthorization: AWS4-HMAC-SHA256 Credential=*REDACTED*/20190531/us-east-1/s3/aws4_request, SignedHeaders=host;x-amz-content-sha256;x-amz-date, Signature=*REDACTED*\n}\nresponse={code=503, headers=Accept-Ranges: bytes\nContent-Security-Policy: block-all-mixed-content\nContent-Type: application/xml\nRetry-After: 120\nServer: MinIO/DEVELOPMENT.2019-05-31T07-32-17Z\nVary: Origin\nX-Amz-Request-Id: 15A3B51FE947C4F5\nX-Minio-Deployment-Id: edb18138-a161-4889-85af-076b546c2a46\nX-Xss-Protection: 1; mode=block\nDate: Fri, 31 May 2019 07:50:44 GMT\nTransfer-Encoding: chunked\n}\n >>> [io.minio.MinioClient.executeReq(MinioClient.java:1204), io.minio.MinioClient.execute(MinioClient.java:1070), io.minio.MinioClient.executeDelete(MinioClient.java:1347), io.minio.MinioClient.abortMultipartUpload(MinioClient.java:5149), io.minio.MinioClient.putObject(MinioClient.java:4337), io.minio.MinioClient.putObject(MinioClient.java:4183), FunctionalTest.listIncompleteUploads_test3(FunctionalTest.java:1679), FunctionalTest.runTests(FunctionalTest.java:2990), FunctionalTest.main(FunctionalTest.java:3118)]"
}

Executed 9 out of 14 tests successfully.
```
<a name="59e207c7-0f9b-4550-b184-722f7fb1fc0e"></a>
### 7690-b2ba49b/mint-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.59:30278
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp ed8aa058d9b6:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... FAILED in 6 minutes and 0 seconds
{
  "alert": "",
  "args": {
    "bucketName": "aws-sdk-go-test-uvauwysgcaza9x",
    "expiry": 60000000000,
    "objectName": "presignedTest"
  },
  "duration": 360009,
  "error": "XMinioServerNotInitialized: Server not initialized, please try again.\n\tstatus code: 503, request id: 15A3B526EB8A91DE, host id: ",
  "function": "PresignedPut",
  "message": "AWS SDK Go CreateBucket Failed",
  "name": "aws-sdk-go",
  "status": "FAIL"
}

Executed 0 out of 14 tests successfully.
```

**Comment by sinhaashish** [comment]
> > I did an force push and the error didn't occur this time.
> 
> AWS SDK Go tests are failing with server not initialised error (MinIO XL Mode), this needs to be checked
> 
> ```
> (1/14) Running aws-sdk-go tests ... FAILED in 6 minutes and 0 seconds
> {
>   "alert": "",
>   "args": {
>     "bucketName": "aws-sdk-go-test-nbwre26qq0udy4",
>     "expiry": 60000000000,
>     "objectName": "presignedTest"
>   },
>   "duration": 360017,
>   "error": "XMinioServerNotInitialized: Server not initialized, please try again.\n\tstatus code: 503, request id: 15A36D1897481F7F, host id: ",
>   "function": "PresignedPut",
>   "message": "AWS SDK Go CreateBucket Failed",
>   "name": "aws-sdk-go",
>   "status": "FAIL"
> }
> ```


Ran this test locally and it passed . The mint test are failing with `Error Response= SlowDown`. This PR can be reviewed.

**Comment by minio-ops** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-compression-xl.sh | :heavy_check_mark: |
| mint-xl.sh | :heavy_check_mark: |
| mint-compression-fs.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :x: [more...](#2e2b7fe6-af6e-4939-9f89-fa6d8db0e1a8) |
| mint-compression-dist-xl.sh | :x: [more...](#1f37a82b-41ff-44e9-8c91-57f2e884d5c4) |
| mint-worm.sh | :x: [more...](#f7a7bbbc-6024-4498-8193-c48d73f8d52b) |
| mint-dist-xl.sh | :x: [more...](#9f8f9e0e-ede5-44fa-a1c5-915f13f825c9) |
<a name="1f37a82b-41ff-44e9-8c91-57f2e884d5c4"></a>
### 7690-2e71527/mint-compression-dist-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.57:30350
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp a0dd274943b0:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... FAILED in 3 seconds
{
  "alert": "",
  "args": {
    "bucketName": "aws-sdk-go-test-6wdd9ibxlxqqdm",
    "expiry": 60000000000,
    "objectName": "presignedTest"
  },
  "duration": 2716,
  "error": "RequestError: send request failed\ncaused by: Put http://72.28.97.57:30350/aws-sdk-go-test-6wdd9ibxlxqqdm: dial tcp 72.28.97.57:30350: connect: no route to host",
  "function": "PresignedPut",
  "message": "AWS SDK Go CreateBucket Failed",
  "name": "aws-sdk-go",
  "status": "FAIL"
}

Executed 0 out of 14 tests successfully.
```
<a name="9f8f9e0e-ede5-44fa-a1c5-915f13f825c9"></a>
### 7690-2e71527/mint-dist-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.52:31793
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp b72a3c053791:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 1 seconds
(2/14) Running aws-sdk-java tests ... done in 1 seconds
(3/14) Running aws-sdk-php tests ... done in 42 seconds
(4/14) Running aws-sdk-ruby tests ... done in 3 seconds
(5/14) Running awscli tests ... done in 1 minutes and 56 seconds
(6/14) Running healthcheck tests ... done in 0 seconds
(7/14) Running mc tests ... done in 1 minutes and 6 seconds
(8/14) Running minio-dotnet tests ... done in 39 seconds
(9/14) Running minio-go tests ... done in 50 seconds
(10/14) Running minio-java tests ... FAILED in 41 seconds
{
  "name": "minio-java",
  "function": "listIncompleteUploads(final String bucketName, final String prefix, final boolean recursive)",
  "args": "prefix: minio, recursive: true",
  "duration": 688,
  "status": "FAIL",
  "error": "error occurred\nErrorResponse(code=SlowDown, message=Please reduce your request, bucketName=minio-java-test-52g8bf, objectName=minio-java-test-20rueco, resource=/minio-java-test-52g8bf/minio-java-test-20rueco, requestId=15A4E62101C40FA1, hostId=44cf883a-0e24-457c-88a0-79f76e40538e)\nrequest={method=DELETE, url=http://72.28.97.52:31793/minio-java-test-52g8bf/minio-java-test-20rueco?uploadId=840f1f8c-019e-4edc-b9a5-91991a96d020, headers=Host: 72.28.97.52:31793\nUser-Agent: MinIO (amd64; amd64) minio-java/dev\nx-amz-content-sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855\nx-amz-date: 20190604T050000Z\nAuthorization: AWS4-HMAC-SHA256 Credential=*REDACTED*/20190604/us-east-1/s3/aws4_request, SignedHeaders=host;x-amz-content-sha256;x-amz-date, Signature=*REDACTED*\n}\nresponse={code=503, headers=Accept-Ranges: bytes\nContent-Security-Policy: block-all-mixed-content\nContent-Type: application/xml\nRetry-After: 120\nServer: MinIO/DEVELOPMENT.2019-06-04T04-41-09Z\nVary: Origin\nX-Amz-Request-Id: 15A4E62101C40FA1\nX-Minio-Deployment-Id: 44cf883a-0e24-457c-88a0-79f76e40538e\nX-Xss-Protection: 1; mode=block\nDate: Tue, 04 Jun 2019 05:00:00 GMT\nTransfer-Encoding: chunked\n}\n >>> [io.minio.MinioClient.executeReq(MinioClient.java:1204), io.minio.MinioClient.execute(MinioClient.java:1070), io.minio.MinioClient.executeDelete(MinioClient.java:1347), io.minio.MinioClient.abortMultipartUpload(MinioClient.java:5149), io.minio.MinioClient.putObject(MinioClient.java:4337), io.minio.MinioClient.putObject(MinioClient.java:4183), FunctionalTest.listIncompleteUploads_test3(FunctionalTest.java:1679), FunctionalTest.runTests(FunctionalTest.java:2990), FunctionalTest.main(FunctionalTest.java:3118)]"
}

Executed 9 out of 14 tests successfully.
```
<a name="f7a7bbbc-6024-4498-8193-c48d73f8d52b"></a>
### 7690-2e71527/mint-worm.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.57:30407
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            worm
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 543d30a0791a:/mint/log /tmp/mint-logs'

(1/1) Running worm tests ... FAILED in 3 seconds
{
  "alert": "",
  "args": {
    "bucketName": "bucket-ezfvvf565wg9i7099kij1y95fvevodu1rzpkixajj6fu0yv1s46d1xt",
    "expiry": 60000000000,
    "objectName": "testObject"
  },
  "duration": 3052,
  "error": "RequestError: send request failed\ncaused by: Put http://72.28.97.57:30407/bucket-ezfvvf565wg9i7099kij1y95fvevodu1rzpkixajj6fu0yv1s46d1xt: dial tcp 72.28.97.57:30407: connect: no route to host",
  "function": "PutAndDelete",
  "message": "WORM_MODE ON  - CreateBucket Failed",
  "name": "test worm mode",
  "status": "FAIL"
}

Executed 0 out of 1 tests successfully.
```
<a name="2e2b7fe6-af6e-4939-9f89-fa6d8db0e1a8"></a>
### 7690-2e71527/mint-large-bucket.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.51:31025
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp c79bcc55e8ee:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 1 seconds
(2/14) Running aws-sdk-java tests ... done in 2 seconds
(3/14) Running aws-sdk-php tests ... done in 49 seconds
(4/14) Running aws-sdk-ruby tests ... done in 13 seconds
(5/14) Running awscli tests ... done in 2 minutes and 18 seconds
(6/14) Running healthcheck tests ... done in 0 seconds
(7/14) Running mc tests ... FAILED in 3 minutes and 0 seconds
{
  "name": "mc",
  "duration": "143744",
  "function": "test_mirror_list_objects_storage_class",
  "status": "FAIL",
  "error": "/mint/run/core/mc/mc --config-dir /tmp/.mc-20278 --quiet --no-color mirror --storage-class REDUCED_REDUNDANCY /mint/data myminio/mc-test-bucket-7842  >>> \n`/mint/data/datafile-1-MB` -> `myminio/mc-test-bucket-7842/datafile-1-MB`\n`/mint/data/datafile-0-b` -> `myminio/mc-test-bucket-7842/datafile-0-b`\n`/mint/data/datafile-1-b` -> `myminio/mc-test-bucket-7842/datafile-1-b`\n`/mint/data/datafile-1.03-MB` -> `myminio/mc-test-bucket-7842/datafile-1.03-MB`\n`/mint/data/datafile-1-kB` -> `myminio/mc-test-bucket-7842/datafile-1-kB`\n`/mint/data/datafile-10-MB` -> `myminio/mc-test-bucket-7842/datafile-10-MB`\n`/mint/data/datafile-100-kB` -> `myminio/mc-test-bucket-7842/datafile-100-kB`\n`/mint/data/datafile-10-kB` -> `myminio/mc-test-bucket-7842/datafile-10-kB`\n`/mint/data/datafile-129-MB` -> `myminio/mc-test-bucket-7842/datafile-129-MB`\n`/mint/data/datafile-11-MB` -> `myminio/mc-test-bucket-7842/datafile-11-MB`\n`/mint/data/datafile-65-MB` -> `myminio/mc-test-bucket-7842/datafile-65-MB`\n`/mint/data/datafile-33-kB` -> `myminio/mc-test-bucket-7842/datafile-33-kB`\n`/mint/data/datafile-5-MB` -> `myminio/mc-test-bucket-7842/datafile-5-MB`\n`/mint/data/datafile-6-MB` -> `myminio/mc-test-bucket-7842/datafile-6-MB`\n`/mint/data/datafile-5243880-b` -> `myminio/mc-test-bucket-7842/datafile-5243880-b`\nmc: <ERROR> Failed to copy `/mint/data/datafile-129-MB`. Please reduce your request\nmc: <ERROR> Failed to copy `/mint/data/datafile-11-MB`. Please reduce your request\nmc: <ERROR> Failed to copy `/mint/data/datafile-10-MB`. Please reduce your request\nmc: <ERROR> Failed to copy `/mint/data/datafile-6-MB`. Please reduce your request\nmc: <ERROR> Failed to copy `/mint/data/datafile-65-MB`. Please reduce your request\nTotal: 233.17 MiB, Transferred: 592.11 MiB, Speed: 4.12 MiB/s"
}

Executed 6 out of 14 tests successfully.
```

**Review by Praveenrajmani — APPROVED** [review]
LGTM and tested. I see that the mint errors are irrelevant to these changes.

**Comment by minio-ops** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-compression-xl.sh | :heavy_check_mark: |
| mint-xl.sh | :heavy_check_mark: |
| mint-compression-dist-xl.sh | :heavy_check_mark: |
| mint-compression-fs.sh | :heavy_check_mark: |
| mint-worm.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :x: [more...](#48c5cde9-699f-4b81-80d9-69759514b5d4) |
| mint-dist-xl.sh | :x: [more...](#9d89dadc-f03a-45ef-96fc-b312f3d9b734) |
<a name="48c5cde9-699f-4b81-80d9-69759514b5d4"></a>
### 7690-4b7268c/mint-large-bucket.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.52:30262
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp cc6e543bdbb6:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 1 seconds
(2/14) Running aws-sdk-java tests ... done in 2 seconds
(3/14) Running aws-sdk-php tests ... done in 49 seconds
(4/14) Running aws-sdk-ruby tests ... done in 13 seconds
(5/14) Running awscli tests ... done in 2 minutes and 19 seconds
(6/14) Running healthcheck tests ... done in 0 seconds
(7/14) Running mc tests ... FAILED in 57 seconds
{
  "name": "mc",
  "duration": "50395",
  "function": "test_put_object_with_storage_class",
  "status": "FAIL",
  "error": "/mint/run/core/mc/mc --config-dir /tmp/.mc-30395 --quiet --no-color cp --storage-class REDUCED_REDUNDANCY /mint/data/datafile-1-MB myminio/mc-test-bucket-8465/mc-test-object-1772  >>> \n`/mint/data/datafile-1-MB` -> `myminio/mc-test-bucket-8465/mc-test-object-1772`\nmc: <ERROR> Failed to copy `/mint/data/datafile-1-MB`. Please reduce your request\nmc: <ERROR> Session safely terminated. To resume session `mc session resume YwUItGiV`"
}

Executed 6 out of 14 tests successfully.
```
<a name="9d89dadc-f03a-45ef-96fc-b312f3d9b734"></a>
### 7690-4b7268c/mint-dist-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.53:32576
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 25df60ad3774:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 0 seconds
(2/14) Running aws-sdk-java tests ... done in 1 seconds
(3/14) Running aws-sdk-php tests ... done in 45 seconds
(4/14) Running aws-sdk-ruby tests ... done in 4 seconds
(5/14) Running awscli tests ... done in 2 minutes and 6 seconds
(6/14) Running healthcheck tests ... done in 0 seconds
(7/14) Running mc tests ... done in 55 seconds
(8/14) Running minio-dotnet tests ... done in 40 seconds
(9/14) Running minio-go tests ... done in 1 minutes and 11 seconds
(10/14) Running minio-java tests ... FAILED in 2 minutes and 26 seconds
{
  "name": "minio-java",
  "function": "listIncompleteUploads(String bucketName, String prefix)",
  "duration": 584,
  "status": "FAIL",
  "error": "error occurred\nErrorResponse(code=SlowDown, message=Please reduce your request, bucketName=minio-java-test-34feiip, objectName=minio-java-test-39vl8f6, resource=/minio-java-test-34feiip/minio-java-test-39vl8f6, requestId=15A4EC95FC91DDF1, hostId=d274770f-5c24-4b7c-ac43-c49126b8e556)\nrequest={method=DELETE, url=http://72.28.97.53:32576/minio-java-test-34feiip/minio-java-test-39vl8f6?uploadId=24563727-dc76-4720-b0e7-97846774df0b, headers=Host: 72.28.97.53:32576\nUser-Agent: MinIO (amd64; amd64) minio-java/dev\nx-amz-content-sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855\nx-amz-date: 20190604T065819Z\nAuthorization: AWS4-HMAC-SHA256 Credential=*REDACTED*/20190604/us-east-1/s3/aws4_request, SignedHeaders=host;x-amz-content-sha256;x-amz-date, Signature=*REDACTED*\n}\nresponse={code=503, headers=Accept-Ranges: bytes\nContent-Security-Policy: block-all-mixed-content\nContent-Type: application/xml\nRetry-After: 120\nServer: MinIO/DEVELOPMENT.2019-06-04T06-37-21Z\nVary: Origin\nX-Amz-Request-Id: 15A4EC95FC91DDF1\nX-Minio-Deployment-Id: d274770f-5c24-4b7c-ac43-c49126b8e556\nX-Xss-Protection: 1; mode=block\nDate: Tue, 04 Jun 2019 06:58:20 GMT\nTransfer-Encoding: chunked\n}\n >>> [io.minio.MinioClient.executeReq(MinioClient.java:1204), io.minio.MinioClient.execute(MinioClient.java:1070), io.minio.MinioClient.executeDelete(MinioClient.java:1347), io.minio.MinioClient.abortMultipartUpload(MinioClient.java:5149), io.minio.MinioClient.putObject(MinioClient.java:4337), io.minio.MinioClient.putObject(MinioClient.java:4183), FunctionalTest.listIncompleteUploads_test2(FunctionalTest.java:1639), FunctionalTest.runTests(FunctionalTest.java:2989), FunctionalTest.main(FunctionalTest.java:3118)]"
}

Executed 9 out of 14 tests successfully.
```

**Comment by minio-ops** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-compression-xl.sh | :heavy_check_mark: |
| mint-compression-dist-xl.sh | :heavy_check_mark: |
| mint-compression-fs.sh | :heavy_check_mark: |
| mint-worm.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-xl.sh | :x: [more...](#0b224def-f071-401a-929f-db0f7d2a8ff6) |
| mint-large-bucket.sh | :x: [more...](#8e773aa0-546b-4edc-a79f-bd454eedfffc) |
| mint-dist-xl.sh | :x: [more...](#a6c3a9b0-3324-4a08-af18-203c5042a5aa) |
<a name="0b224def-f071-401a-929f-db0f7d2a8ff6"></a>
### 7690-75bd0ca/mint-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.57:30034
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 255bd973dd0d:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... FAILED in 3 seconds
{
  "alert": "",
  "args": {
    "bucketName": "aws-sdk-go-test-rek5dvpall2ds4",
    "expiry": 60000000000,
    "objectName": "presignedTest"
  },
  "duration": 3071,
  "error": "RequestError: send request failed\ncaused by: Put http://72.28.97.57:30034/aws-sdk-go-test-rek5dvpall2ds4: dial tcp 72.28.97.57:30034: connect: no route to host",
  "function": "PresignedPut",
  "message": "AWS SDK Go CreateBucket Failed",
  "name": "aws-sdk-go",
  "status": "FAIL"
}

Executed 0 out of 14 tests successfully.
```
<a name="a6c3a9b0-3324-4a08-af18-203c5042a5aa"></a>
### 7690-75bd0ca/mint-dist-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.54:32671
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp f75a05ba19e2:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 1 seconds
(2/14) Running aws-sdk-java tests ... done in 1 seconds
(3/14) Running aws-sdk-php tests ... done in 44 seconds
(4/14) Running aws-sdk-ruby tests ... done in 3 seconds
(5/14) Running awscli tests ... done in 3 minutes and 15 seconds
(6/14) Running healthcheck tests ... done in 0 seconds
(7/14) Running mc tests ... done in 39 seconds
(8/14) Running minio-dotnet tests ... done in 34 seconds
(9/14) Running minio-go tests ... done in 1 minutes and 6 seconds
(10/14) Running minio-java tests ... FAILED in 1 minutes and 44 seconds
{
  "name": "minio-java",
  "function": "listIncompleteUploads(String bucketName, String prefix)",
  "duration": 637,
  "status": "FAIL",
  "error": "error occurred\nErrorResponse(code=SlowDown, message=Please reduce your request, bucketName=minio-java-test-51pmde, objectName=minio-java-test-cu8l96, resource=/minio-java-test-51pmde/minio-java-test-cu8l96, requestId=15A53D4AB741F334, hostId=4511ce2d-e5d1-452f-a2a7-8a7e5050bc03)\nrequest={method=DELETE, url=http://72.28.97.54:32671/minio-java-test-51pmde/minio-java-test-cu8l96?uploadId=8836e9b2-2e65-45bb-a319-fb59426ebee6, headers=Host: 72.28.97.54:32671\nUser-Agent: MinIO (amd64; amd64) minio-java/dev\nx-amz-content-sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855\nx-amz-date: 20190605T073717Z\nAuthorization: AWS4-HMAC-SHA256 Credential=*REDACTED*/20190605/us-east-1/s3/aws4_request, SignedHeaders=host;x-amz-content-sha256;x-amz-date, Signature=*REDACTED*\n}\nresponse={code=503, headers=Accept-Ranges: bytes\nContent-Security-Policy: block-all-mixed-content\nContent-Type: application/xml\nRetry-After: 120\nServer: MinIO/DEVELOPMENT.2019-06-05T07-16-18Z\nVary: Origin\nX-Amz-Request-Id: 15A53D4AB741F334\nX-Minio-Deployment-Id: 4511ce2d-e5d1-452f-a2a7-8a7e5050bc03\nX-Xss-Protection: 1; mode=block\nDate: Wed, 05 Jun 2019 07:37:17 GMT\nTransfer-Encoding: chunked\n}\n >>> [io.minio.MinioClient.executeReq(MinioClient.java:1204), io.minio.MinioClient.execute(MinioClient.java:1070), io.minio.MinioClient.executeDelete(MinioClient.java:1347), io.minio.MinioClient.abortMultipartUpload(MinioClient.java:5149), io.minio.MinioClient.putObject(MinioClient.java:4337), io.minio.MinioClient.putObject(MinioClient.java:4183), FunctionalTest.listIncompleteUploads_test2(FunctionalTest.java:1639), FunctionalTest.runTests(FunctionalTest.java:2989), FunctionalTest.main(FunctionalTest.java:3118)]"
}

Executed 9 out of 14 tests successfully.
```
<a name="8e773aa0-546b-4edc-a79f-bd454eedfffc"></a>
### 7690-75bd0ca/mint-large-bucket.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.51:30943
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp eb370a6a6c5a:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 1 seconds
(2/14) Running aws-sdk-java tests ... done in 2 seconds
(3/14) Running aws-sdk-php tests ... done in 49 seconds
(4/14) Running aws-sdk-ruby tests ... done in 30 seconds
(5/14) Running awscli tests ... done in 2 minutes and 9 seconds
(6/14) Running healthcheck tests ... done in 1 seconds
(7/14) Running mc tests ... FAILED in 2 minutes and 19 seconds
{
  "name": "mc",
  "duration": "110710",
  "function": "test_mirror_list_objects_storage_class",
  "status": "FAIL",
  "error": "/mint/run/core/mc/mc --config-dir /tmp/.mc-13676 --quiet --no-color mirror --storage-class REDUCED_REDUNDANCY /mint/data myminio/mc-test-bucket-23201  >>> \n`/mint/data/datafile-1-MB` -> `myminio/mc-test-bucket-23201/datafile-1-MB`\n`/mint/data/datafile-1-kB` -> `myminio/mc-test-bucket-23201/datafile-1-kB`\n`/mint/data/datafile-0-b` -> `myminio/mc-test-bucket-23201/datafile-0-b`\n`/mint/data/datafile-1-b` -> `myminio/mc-test-bucket-23201/datafile-1-b`\n`/mint/data/datafile-1.03-MB` -> `myminio/mc-test-bucket-23201/datafile-1.03-MB`\n`/mint/data/datafile-10-kB` -> `myminio/mc-test-bucket-23201/datafile-10-kB`\n`/mint/data/datafile-10-MB` -> `myminio/mc-test-bucket-23201/datafile-10-MB`\n`/mint/data/datafile-11-MB` -> `myminio/mc-test-bucket-23201/datafile-11-MB`\n`/mint/data/datafile-100-kB` -> `myminio/mc-test-bucket-23201/datafile-100-kB`\n`/mint/data/datafile-129-MB` -> `myminio/mc-test-bucket-23201/datafile-129-MB`\n`/mint/data/datafile-33-kB` -> `myminio/mc-test-bucket-23201/datafile-33-kB`\n`/mint/data/datafile-5243880-b` -> `myminio/mc-test-bucket-23201/datafile-5243880-b`\n`/mint/data/datafile-5-MB` -> `myminio/mc-test-bucket-23201/datafile-5-MB`\n`/mint/data/datafile-65-MB` -> `myminio/mc-test-bucket-23201/datafile-65-MB`\n`/mint/data/datafile-6-MB` -> `myminio/mc-test-bucket-23201/datafile-6-MB`\nmc: <ERROR> Failed to copy `/mint/data/datafile-129-MB`. Please reduce your request\nmc: <ERROR> Failed to copy `/mint/data/datafile-65-MB`. Please reduce your request\nmc: <ERROR> Failed to copy `/mint/data/datafile-10-MB`. Please reduce your request\nmc: <ERROR> Failed to copy `/mint/data/datafile-11-MB`. Please reduce your request\nTotal: 233.17 MiB, Transferred: 572.05 MiB, Speed: 5.17 MiB/s"
}

Executed 6 out of 14 tests successfully.
```

**Comment by minio-ops** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-compression-xl.sh | :heavy_check_mark: |
| mint-xl.sh | :heavy_check_mark: |
| mint-compression-dist-xl.sh | :heavy_check_mark: |
| mint-compression-fs.sh | :heavy_check_mark: |
| mint-worm.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :x: [more...](#ba3e4be4-a16a-4ef8-ab7a-fc7bdbb123bb) |
| mint-dist-xl.sh | :x: [more...](#d4c6cdd2-53a7-4f21-9d98-51d3366e9fe8) |
| mint-gateway-nas.sh | :x: [more...](#d09da7e4-416d-4116-8e08-199af6ae20c1) |
<a name="d09da7e4-416d-4116-8e08-199af6ae20c1"></a>
### 7690-d44ef0b/mint-gateway-nas.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.57:32426
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 939a84342fe9:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... FAILED in 3 seconds
{
  "alert": "",
  "args": {
    "bucketName": "aws-sdk-go-test-y3mlqacky9smhi",
    "expiry": 60000000000,
    "objectName": "presignedTest"
  },
  "duration": 3070,
  "error": "RequestError: send request failed\ncaused by: Put http://72.28.97.57:32426/aws-sdk-go-test-y3mlqacky9smhi: dial tcp 72.28.97.57:32426: connect: no route to host",
  "function": "PresignedPut",
  "message": "AWS SDK Go CreateBucket Failed",
  "name": "aws-sdk-go",
  "status": "FAIL"
}

Executed 0 out of 14 tests successfully.
```
<a name="d4c6cdd2-53a7-4f21-9d98-51d3366e9fe8"></a>
### 7690-d44ef0b/mint-dist-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.59:30711
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp be43c747d7da:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 0 seconds
(2/14) Running aws-sdk-java tests ... done in 1 seconds
(3/14) Running aws-sdk-php tests ... done in 44 seconds
(4/14) Running aws-sdk-ruby tests ... done in 3 seconds
(5/14) Running awscli tests ... done in 1 minutes and 56 seconds
(6/14) Running healthcheck tests ... done in 2 seconds
(7/14) Running mc tests ... done in 54 seconds
(8/14) Running minio-dotnet tests ... done in 49 seconds
(9/14) Running minio-go tests ... done in 1 minutes and 11 seconds
(10/14) Running minio-java tests ... FAILED in 1 minutes and 23 seconds
{
  "name": "minio-java",
  "function": "listIncompleteUploads(final String bucketName, final String prefix, final boolean recursive)",
  "args": "prefix: minio, recursive: true",
  "duration": 285,
  "status": "FAIL",
  "error": "error occurred\nErrorResponse(code=SlowDown, message=Please reduce your request, bucketName=minio-java-test-3ocbigk, objectName=minio-java-test-1nu47g6, resource=/minio-java-test-3ocbigk/minio-java-test-1nu47g6, requestId=15A5873D747CC450, hostId=73902fb7-60d3-4eb9-bb3f-8b79b359b6e1)\nrequest={method=DELETE, url=http://72.28.97.59:30711/minio-java-test-3ocbigk/minio-java-test-1nu47g6?uploadId=c4d1e50c-64d5-496f-9a2d-b3b07ed927d1, headers=Host: 72.28.97.59:30711\nUser-Agent: MinIO (amd64; amd64) minio-java/dev\nx-amz-content-sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855\nx-amz-date: 20190606T061223Z\nAuthorization: AWS4-HMAC-SHA256 Credential=*REDACTED*/20190606/us-east-1/s3/aws4_request, SignedHeaders=host;x-amz-content-sha256;x-amz-date, Signature=*REDACTED*\n}\nresponse={code=503, headers=Accept-Ranges: bytes\nContent-Security-Policy: block-all-mixed-content\nContent-Type: application/xml\nRetry-After: 120\nServer: MinIO/DEVELOPMENT.2019-06-06T05-52-26Z\nVary: Origin\nX-Amz-Request-Id: 15A5873D747CC450\nX-Minio-Deployment-Id: 73902fb7-60d3-4eb9-bb3f-8b79b359b6e1\nX-Xss-Protection: 1; mode=block\nDate: Thu, 06 Jun 2019 06:12:23 GMT\nTransfer-Encoding: chunked\n}\n >>> [io.minio.MinioClient.executeReq(MinioClient.java:1204), io.minio.MinioClient.execute(MinioClient.java:1070), io.minio.MinioClient.executeDelete(MinioClient.java:1347), io.minio.MinioClient.abortMultipartUpload(MinioClient.java:5149), io.minio.MinioClient.putObject(MinioClient.java:4337), io.minio.MinioClient.putObject(MinioClient.java:4183), FunctionalTest.listIncompleteUploads_test3(FunctionalTest.java:1679), FunctionalTest.runTests(FunctionalTest.java:2990), FunctionalTest.main(FunctionalTest.java:3118)]"
}

Executed 9 out of 14 tests successfully.
```
<a name="ba3e4be4-a16a-4ef8-ab7a-fc7bdbb123bb"></a>
### 7690-d44ef0b/mint-large-bucket.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.53:30885
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 7c03be5e8e29:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 2 seconds
(2/14) Running aws-sdk-java tests ... done in 2 seconds
(3/14) Running aws-sdk-php tests ... done in 48 seconds
(4/14) Running aws-sdk-ruby tests ... done in 12 seconds
(5/14) Running awscli tests ... done in 2 minutes and 20 seconds
(6/14) Running healthcheck tests ... done in 0 seconds
(7/14) Running mc tests ... FAILED in 3 minutes and 44 seconds
{
  "name": "mc",
  "duration": "181953",
  "function": "test_mirror_list_objects_storage_class",
  "status": "FAIL",
  "error": "/mint/run/core/mc/mc --config-dir /tmp/.mc-25639 --quiet --no-color mirror --storage-class REDUCED_REDUNDANCY /mint/data myminio/mc-test-bucket-11566  >>> \n`/mint/data/datafile-1-MB` -> `myminio/mc-test-bucket-11566/datafile-1-MB`\n`/mint/data/datafile-0-b` -> `myminio/mc-test-bucket-11566/datafile-0-b`\n`/mint/data/datafile-1-kB` -> `myminio/mc-test-bucket-11566/datafile-1-kB`\n`/mint/data/datafile-10-MB` -> `myminio/mc-test-bucket-11566/datafile-10-MB`\n`/mint/data/datafile-1-b` -> `myminio/mc-test-bucket-11566/datafile-1-b`\n`/mint/data/datafile-10-kB` -> `myminio/mc-test-bucket-11566/datafile-10-kB`\n`/mint/data/datafile-1.03-MB` -> `myminio/mc-test-bucket-11566/datafile-1.03-MB`\n`/mint/data/datafile-100-kB` -> `myminio/mc-test-bucket-11566/datafile-100-kB`\n`/mint/data/datafile-11-MB` -> `myminio/mc-test-bucket-11566/datafile-11-MB`\n`/mint/data/datafile-129-MB` -> `myminio/mc-test-bucket-11566/datafile-129-MB`\n`/mint/data/datafile-33-kB` -> `myminio/mc-test-bucket-11566/datafile-33-kB`\n`/mint/data/datafile-5243880-b` -> `myminio/mc-test-bucket-11566/datafile-5243880-b`\n`/mint/data/datafile-5-MB` -> `myminio/mc-test-bucket-11566/datafile-5-MB`\n`/mint/data/datafile-65-MB` -> `myminio/mc-test-bucket-11566/datafile-65-MB`\n`/mint/data/datafile-6-MB` -> `myminio/mc-test-bucket-11566/datafile-6-MB`\nmc: <ERROR> Failed to copy `/mint/data/datafile-65-MB`. Please reduce your request\nmc: <ERROR> Failed to copy `/mint/data/datafile-129-MB`. Please reduce your request\nTotal: 233.17 MiB, Transferred: 431.82 MiB, Speed: 2.37 MiB/s"
}

Executed 6 out of 14 tests successfully.
```

**Comment by minio-ops** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-compression-xl.sh | :heavy_check_mark: |
| mint-xl.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-compression-dist-xl.sh | :heavy_check_mark: |
| mint-compression-fs.sh | :heavy_check_mark: |
| mint-worm.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-dist-xl.sh | :x: [more...](#0a0d4b1a-eef6-482e-bdbb-dedb4fa46a12) |
<a name="0a0d4b1a-eef6-482e-bdbb-dedb4fa46a12"></a>
### 7690-ec8b22b/mint-dist-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.60:31951
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 3eef8d987960:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 1 seconds
(2/14) Running aws-sdk-java tests ... done in 1 seconds
(3/14) Running aws-sdk-php tests ... done in 44 seconds
(4/14) Running aws-sdk-ruby tests ... done in 7 seconds
(5/14) Running awscli tests ... done in 1 minutes and 1 seconds
(6/14) Running healthcheck tests ... done in 0 seconds
(7/14) Running mc tests ... done in 50 seconds
(8/14) Running minio-dotnet tests ... done in 37 seconds
(9/14) Running minio-go tests ... done in 1 minutes and 33 seconds
(10/14) Running minio-java tests ... FAILED in 2 minutes and 15 seconds
{
  "name": "minio-java",
  "function": "listIncompleteUploads(String bucketName, String prefix)",
  "duration": 1423,
  "status": "FAIL",
  "error": "error occurred\nErrorResponse(code=SlowDown, message=Please reduce your request, bucketName=minio-java-test-me9aq5, objectName=minio-java-test-lg49ar, resource=/minio-java-test-me9aq5/minio-java-test-lg49ar, requestId=15A90774706849E0, hostId=40cfc540-03b0-447b-84dc-d9b00af47c3a)\nrequest={method=DELETE, url=http://72.28.97.60:31951/minio-java-test-me9aq5/minio-java-test-lg49ar?uploadId=431d8b45-c4fd-4832-b7b2-252effcf8238, headers=Host: 72.28.97.60:31951\nUser-Agent: MinIO (amd64; amd64) minio-java/dev\nx-amz-content-sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855\nx-amz-date: 20190617T155542Z\nAuthorization: AWS4-HMAC-SHA256 Credential=*REDACTED*/20190617/us-east-1/s3/aws4_request, SignedHeaders=host;x-amz-content-sha256;x-amz-date, Signature=*REDACTED*\n}\nresponse={code=503, headers=Accept-Ranges: bytes\nContent-Length: 359\nContent-Security-Policy: block-all-mixed-content\nContent-Type: application/xml\nRetry-After: 120\nServer: MinIO/DEVELOPMENT.2019-06-17T15-35-28Z\nVary: Origin\nX-Amz-Request-Id: 15A90774706849E0\nX-Minio-Deployment-Id: 40cfc540-03b0-447b-84dc-d9b00af47c3a\nX-Xss-Protection: 1; mode=block\nDate: Mon, 17 Jun 2019 15:55:43 GMT\n}\n >>> [io.minio.MinioClient.executeReq(MinioClient.java:1204), io.minio.MinioClient.execute(MinioClient.java:1070), io.minio.MinioClient.executeDelete(MinioClient.java:1347), io.minio.MinioClient.abortMultipartUpload(MinioClient.java:5149), io.minio.MinioClient.putObject(MinioClient.java:4337), io.minio.MinioClient.putObject(MinioClient.java:4183), FunctionalTest.listIncompleteUploads_test2(FunctionalTest.java:1639), FunctionalTest.runTests(FunctionalTest.java:2989), FunctionalTest.main(FunctionalTest.java:3118)]"
}

Executed 9 out of 14 tests successfully.
```

**Review by nitisht — APPROVED** [review]
LGTM & Tested

**Comment by minio-ops** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-compression-xl.sh | :heavy_check_mark: |
| mint-xl.sh | :heavy_check_mark: |
| mint-compression-fs.sh | :heavy_check_mark: |
| mint-worm.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :x: [more...](#800ae303-3d41-4df1-81fd-c020f871a468) |
| mint-compression-dist-xl.sh | :x: [more...](#da271be9-e835-4b16-be91-b3ccb61ce1c1) |
| mint-dist-xl.sh | :x: [more...](#ea5fe474-3f5c-431e-87b5-94e6f0e3be7d) |
<a name="800ae303-3d41-4df1-81fd-c020f871a468"></a>
### 7690-2711d19/mint-large-bucket.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.61:30174
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 119b2ddcf104:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 2 seconds
(2/14) Running aws-sdk-java tests ... done in 2 seconds
(3/14) Running aws-sdk-php tests ... done in 55 seconds
(4/14) Running aws-sdk-ruby tests ... done in 13 seconds
(5/14) Running awscli tests ... done in 2 minutes and 12 seconds
(6/14) Running healthcheck tests ... done in 1 seconds
(7/14) Running mc tests ... FAILED in 2 minutes and 32 seconds
{
  "name": "mc",
  "duration": "117078",
  "function": "test_mirror_list_objects_storage_class",
  "status": "FAIL",
  "error": "/mint/run/core/mc/mc --config-dir /tmp/.mc-17128 --quiet --no-color mirror --storage-class REDUCED_REDUNDANCY /mint/data myminio/mc-test-bucket-27156  >>> \n`/mint/data/datafile-1-MB` -> `myminio/mc-test-bucket-27156/datafile-1-MB`\n`/mint/data/datafile-0-b` -> `myminio/mc-test-bucket-27156/datafile-0-b`\n`/mint/data/datafile-1-b` -> `myminio/mc-test-bucket-27156/datafile-1-b`\n`/mint/data/datafile-1-kB` -> `myminio/mc-test-bucket-27156/datafile-1-kB`\n`/mint/data/datafile-10-MB` -> `myminio/mc-test-bucket-27156/datafile-10-MB`\n`/mint/data/datafile-1.03-MB` -> `myminio/mc-test-bucket-27156/datafile-1.03-MB`\n`/mint/data/datafile-33-kB` -> `myminio/mc-test-bucket-27156/datafile-33-kB`\n`/mint/data/datafile-10-kB` -> `myminio/mc-test-bucket-27156/datafile-10-kB`\n`/mint/data/datafile-129-MB` -> `myminio/mc-test-bucket-27156/datafile-129-MB`\n`/mint/data/datafile-11-MB` -> `myminio/mc-test-bucket-27156/datafile-11-MB`\n`/mint/data/datafile-6-MB` -> `myminio/mc-test-bucket-27156/datafile-6-MB`\n`/mint/data/datafile-5-MB` -> `myminio/mc-test-bucket-27156/datafile-5-MB`\n`/mint/data/datafile-100-kB` -> `myminio/mc-test-bucket-27156/datafile-100-kB`\n`/mint/data/datafile-5243880-b` -> `myminio/mc-test-bucket-27156/datafile-5243880-b`\n`/mint/data/datafile-65-MB` -> `myminio/mc-test-bucket-27156/datafile-65-MB`\nmc: <ERROR> Failed to copy `/mint/data/datafile-129-MB`. Please reduce your request\nmc: <ERROR> Failed to copy `/mint/data/datafile-11-MB`. Please reduce your request\nmc: <ERROR> Failed to copy `/mint/data/datafile-65-MB`. Please reduce your request\nmc: <ERROR> Failed to copy `/mint/data/datafile-10-MB`. Please reduce your request\nTotal: 233.17 MiB, Transferred: 567.78 MiB, Speed: 4.85 MiB/s"
}

Executed 6 out of 14 tests successfully.
```
<a name="da271be9-e835-4b16-be91-b3ccb61ce1c1"></a>
### 7690-2711d19/mint-compression-dist-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.57:30432
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 6a2af4666165:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... FAILED in 4 seconds
{
  "alert": "",
  "args": {
    "bucketName": "aws-sdk-go-test-je3vg23pfkmtj0",
    "expiry": 60000000000,
    "objectName": "presignedTest"
  },
  "duration": 3071,
  "error": "RequestError: send request failed\ncaused by: Put http://72.28.97.57:30432/aws-sdk-go-test-je3vg23pfkmtj0: dial tcp 72.28.97.57:30432: connect: no route to host",
  "function": "PresignedPut",
  "message": "AWS SDK Go CreateBucket Failed",
  "name": "aws-sdk-go",
  "status": "FAIL"
}

Executed 0 out of 14 tests successfully.
```
<a name="ea5fe474-3f5c-431e-87b5-94e6f0e3be7d"></a>
### 7690-2711d19/mint-dist-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.59:31085
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 0ae1fa7417e6:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 0 seconds
(2/14) Running aws-sdk-java tests ... done in 1 seconds
(3/14) Running aws-sdk-php tests ... done in 51 seconds
(4/14) Running aws-sdk-ruby tests ... done in 3 seconds
(5/14) Running awscli tests ... done in 2 minutes and 0 seconds
(6/14) Running healthcheck tests ... done in 0 seconds
(7/14) Running mc tests ... done in 49 seconds
(8/14) Running minio-dotnet tests ... done in 37 seconds
(9/14) Running minio-go tests ... done in 1 minutes and 8 seconds
(10/14) Running minio-java tests ... FAILED in 1 minutes and 40 seconds
{
  "name": "minio-java",
  "function": "presignedGetObject(String bucketName, String objectName, Integer expires, Map<String, String> reqParams)",
  "duration": 96,
  "status": "FAIL",
  "error": "java.lang.Exception: failed to read object. Response: Response{protocol=http/1.1, code=503, message=Service Unavailable, url=http://72.28.97.59:31085/minio-java-test-248r292/minio-java-test-18gs9qv?response-content-type=application%2Fjson&X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=minio%2F20190621%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20190621T033517Z&X-Amz-Expires=3600&X-Amz-SignedHeaders=host&X-Amz-Signature=f8a624c1d0adf8c5c3d36d0e02941f59b91a1cb7276a0b2076bf663d9361cf11}, Response body: <?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<Error><Code>SlowDown</Code><Message>Please reduce your request</Message><Key>minio-java-test-18gs9qv</Key><BucketName>minio-java-test-248r292</BucketName><Resource>/minio-java-test-248r292/minio-java-test-18gs9qv</Resource><RequestId>15AA195F155AFDEA</RequestId><HostId>262b1af0-620c-4f98-abaa-30c13a956808</HostId></Error> >>> [FunctionalTest.readObject(FunctionalTest.java:201), FunctionalTest.presignedGetObject_test3(FunctionalTest.java:1842), FunctionalTest.runTests(FunctionalTest.java:2996), FunctionalTest.main(FunctionalTest.java:3118)]"
}

Executed 9 out of 14 tests successfully.
```
{"name": "7690-2711d19", "full_size": 63688685, "images": [{"size": 63688685, "architecture": "amd64", "variant": null, "features": null, "os": "linux", "os_version": null, "os_features": null}], "id": 59617324, "repository": 757613, "creator": 21164, "last_updater": 21164, "last_updated": "2019-06-21T03:16:05.078250Z", "image_id": null, "v2": true}
