### PR TITLE
Log replication errors once

### LINKED ISSUE #20057: garbage logs in site replicated setup when one of the site is down
## NOTE
If this case is urgent, please subscribe to [Subnet](https://min.io/pricing) so that our 24/7 support team may help you faster.

## Expected Behavior
Minimal logs that indicate the error and does not repeat them

## Current Behavior
```
API: SYSTEM.replication
Time: 06:36:59 UTC 07/09/2024
DeploymentID: dc963e0c-40d0-4ec6-980e-54488f46ac6f
Error: myminio1: ConfigureReplication: Site replication error(s): 
'ConfigureReplication' on site myminio2 (d21fb870-3481-4410-8b84-3ad801fde911): failed(bucket replication config validation error: cmd.APIError{Code:"RemoteDestinationNotFoundError", Description:"The remote destination bucket does not exist (Head \"http://localhost:9002/testbucket/\": dial tcp 127.0.0.1:9002: connect: connection refused)", HTTPStatusCode:404, ObjectSize:"", RangeRequested:""}) (*fmt.wrapError)
       5: internal/logger/logger.go:268:logger.LogIf()
       4: cmd/logging.go:16:cmd.replLogIf()
       3: cmd/site-replication.go:5228:cmd.(*SiteReplicationSys).healBucketReplicationConfig()
       2: cmd/site-replication.go:4467:cmd.(*SiteReplicationSys).healBuckets()
       1: cmd/site-replication.go:4281:cmd.(*SiteReplicationSys).startHealRoutine()

API: SYSTEM.replication
Time: 06:37:29 UTC 07/09/2024
DeploymentID: dc963e0c-40d0-4ec6-980e-54488f46ac6f
Error: myminio1: ConfigureReplication: Site replication error(s): 
'ConfigureReplication' on site myminio2 (d21fb870-3481-4410-8b84-3ad801fde911): failed(bucket replication config validation error: cmd.APIError{Code:"RemoteDestinationNotFoundError", Description:"The remote destination bucket does not exist (Head \"http://localhost:9002/testbucket/\": dial tcp 127.0.0.1:9002: connect: connection refused)", HTTPStatusCode:404, ObjectSize:"", RangeRequested:""}) (*fmt.wrapError)
       5: internal/logger/logger.go:268:logger.LogIf()
       4: cmd/logging.go:16:cmd.replLogIf()
       3: cmd/site-replication.go:5228:cmd.(*SiteReplicationSys).healBucketReplicationConfig()
       2: cmd/site-replication.go:4467:cmd.(*SiteReplicationSys).healBuckets()
       1: cmd/site-replication.go:4281:cmd.(*SiteReplicationSys).startHealRoutine()

API: SYSTEM.replication
Time: 06:37:59 UTC 07/09/2024
DeploymentID: dc963e0c-40d0-4ec6-980e-54488f46ac6f
Error: Unable to heal IAM policy consoleAdmin from peer site myminio1 -> site  : Site replication error(s): 
'SRPeerReplicateIAMItem' on site myminio2 (d21fb870-3481-4410-8b84-3ad801fde911): failed(Remote service endpoint http://localhost:9002 not available
	remote target is offline for endpoint http://localhost:9002)
'SRPeerReplicateIAMItem' on site myminio1 (dc963e0c-40d0-4ec6-980e-54488f46ac6f): succeeded (*fmt.wrapError)
       5: internal/logger/logger.go:268:logger.LogIf()
       4: cmd/logging.go:16:cmd.replLogIf()
       3: cmd/site-replication.go:5321:cmd.(*SiteReplicationSys).healPolicies()
       2: cmd/site-replication.go:5254:cmd.(*SiteReplicationSys).healIAMSystem()
       1: cmd/site-replication.go:4280:cmd.(*SiteReplicationSys).startHealRoutine()

API: SYSTEM.replication
Time: 06:37:59 UTC 07/09/2024
DeploymentID: dc963e0c-40d0-4ec6-980e-54488f46ac6f
Error: myminio1: ConfigureReplication: Site replication error(s): 
'ConfigureReplication' on site myminio2 (d21fb870-3481-4410-8b84-3ad801fde911): failed(bucket replication config validation error: cmd.APIError{Code:"RemoteDestinationNotFoundError", Description:"The remote destination bucket does not exist (Head \"http://localhost:9002/testbucket/\": dial tcp 127.0.0.1:9002: connect: connection refused)", HTTPStatusCode:404, ObjectSize:"", RangeRequested:""}) (*fmt.wrapError)
       5: internal/logger/logger.go:268:logger.LogIf()
       4: cmd/logging.go:16:cmd.replLogIf()
       3: cmd/site-replication.go:5228:cmd.(*SiteReplicationSys).healBucketReplicationConfig()
       2: cmd/site-replication.go:4467:cmd.(*SiteReplicationSys).healBuckets()
       1: cmd/site-replication.go:4281:cmd.(*SiteReplicationSys).startHealRoutine()

API: SYSTEM.replication
Time: 06:38:29 UTC 07/09/2024
DeploymentID: dc963e0c-40d0-4ec6-980e-54488f46ac6f
Error: Unable to heal IAM policy consoleAdmin from peer site myminio1 -> site  : Site replication error(s): 
'SRPeerReplicateIAMItem' on site myminio1 (dc963e0c-40d0-4ec6-980e-54488f46ac6f): succeeded
'SRPeerReplicateIAMItem' on site myminio2 (d21fb870-3481-4410-8b84-3ad801fde911): failed(Remote service endpoint http://localhost:9002 not available
	remote target is offline for endpoint http://localhost:9002) (*fmt.wrapError)
       5: internal/logger/logger.go:268:logger.LogIf()
       4: cmd/logging.go:16:cmd.replLogIf()
       3: cmd/site-replication.go:5321:cmd.(*SiteReplicationSys).healPolicies()
       2: cmd/site-replication.go:5254:cmd.(*SiteReplicationSys).healIAMSystem()
       1: cmd/site-replication.go:4280:cmd.(*SiteReplicationSys).startHealRoutine()

API: SYSTEM.replication
Time: 06:38:29 UTC 07/09/2024
DeploymentID: dc963e0c-40d0-4ec6-980e-54488f46ac6f
Error: myminio1: ConfigureReplication: Site replication error(s): 
'ConfigureReplication' on site myminio2 (d21fb870-3481-4410-8b84-3ad801fde911): failed(bucket replication config validation error: cmd.APIError{Code:"RemoteDestinationNotFoundError", Description:"The remote destination bucket does not exist (Head \"http://localhost:9002/testbucket/\": dial tcp 127.0.0.1:9002: connect: connection refused)", HTTPStatusCode:404, ObjectSize:"", RangeRequested:""}) (*fmt.wrapError)
       5: internal/logger/logger.go:268:logger.LogIf()
       4: cmd/logging.go:16:cmd.replLogIf()
       3: cmd/site-replication.go:5228:cmd.(*SiteReplicationSys).healBucketReplicationConfig()
       2: cmd/site-replication.go:4467:cmd.(*SiteReplicationSys).healBuckets()
       1: cmd/site-replication.go:4281:cmd.(*SiteReplicationSys).startHealRoutine()

API: SYSTEM.replication
Time: 06:38:59 UTC 07/09/2024
DeploymentID: dc963e0c-40d0-4ec6-980e-54488f46ac6f
Error: myminio1: ConfigureReplication: Site replication error(s): 
'ConfigureReplication' on site myminio2 (d21fb870-3481-4410-8b84-3ad801fde911): failed(bucket replication config validation error: cmd.APIError{Code:"RemoteDestinationNotFoundError", Description:"The remote destination bucket does not exist (Head \"http://localhost:9002/testbucket/\": dial tcp 127.0.0.1:9002: connect: connection refused)", HTTPStatusCode:404, ObjectSize:"", RangeRequested:""}) (*fmt.wrapError)
       5: internal/logger/logger.go:268:logger.LogIf()
       4: cmd/logging.go:16:cmd.replLogIf()
       3: cmd/site-replication.go:5228:cmd.(*SiteReplicationSys).healBucketReplicationConfig()
       2: cmd/site-replication.go:4467:cmd.(*SiteReplicationSys).healBuckets()
       1: cmd/site-replication.go:4281:cmd.(*SiteReplicationSys).startHealRoutine()

harsha@sysrq:~/minio$ 
API: SYSTEM.replication
Time: 06:39:29 UTC 07/09/2024
DeploymentID: dc963e0c-40d0-4ec6-980e-54488f46ac6f
Error: myminio1: ConfigureReplication: Site replication error(s): 
'ConfigureReplication' on site myminio2 (d21fb870-3481-4410-8b84-3ad801fde911): failed(bucket replication config validation error: cmd.APIError{Code:"RemoteDestinationNotFoundError", Description:"The remote destination bucket does not exist (Head \"http://localhost:9002/testbucket/\": dial tcp 127.0.0.1:9002: connect: connection refused)", HTTPStatusCode:404, ObjectSize:"", RangeRequested:""}) (*fmt.wrapError)
       5: internal/logger/logger.go:268:logger.LogIf()
       4: cmd/logging.go:16:cmd.replLogIf()
       3: cmd/site-replication.go:5228:cmd.(*SiteReplicationSys).healBucketReplicationConfig()
       2: cmd/site-replication.go:4467:cmd.(*SiteReplicationSys).healBuckets()
       1: cmd/site-replication.go:4281:cmd.(*SiteReplicationSys).startHealRoutine()

API: SYSTEM.replication
Time: 06:39:59 UTC 07/09/2024
DeploymentID: dc963e0c-40d0-4ec6-980e-54488f46ac6f
Error: Unable to heal IAM policy consoleAdmin from peer site myminio1 -> site  : Site replication error(s): 
'SRPeerReplicateIAMItem' on site myminio1 (dc963e0c-40d0-4ec6-980e-54488f46ac6f): succeeded
'SRPeerReplicateIAMItem' on site myminio2 (d21fb870-3481-4410-8b84-3ad801fde911): failed(Remote service endpoint http://localhost:9002 not available
	remote target is offline for endpoint http://localhost:9002) (*fmt.wrapError)
       5: internal/logger/logger.go:268:logger.LogIf()
       4: cmd/logging.go:16:cmd.replLogIf()
       3: cmd/site-replication.go:5321:cmd.(*SiteReplicationSys).healPolicies()
       2: cmd/site-replication.go:5254:cmd.(*SiteReplicationSys).healIAMSystem()
       1: cmd/site-replication.go:4280:cmd.(*SiteReplicationSys).startHealRoutine()

API: SYSTEM.replication
Time: 06:39:59 UTC 07/09/2024
DeploymentID: dc963e0c-40d0-4ec6-980e-54488f46ac6f
Error: myminio1: ConfigureReplication: Site replication error(s): 
'ConfigureReplication' on site myminio2 (d21fb870-3481-4410-8b84-3ad801fde911): failed(bucket replication config validation error: cmd.APIError{Code:"RemoteDestinationNotFoundError", Description:"The remote destination bucket does not exist (Head \"http://localhost:9002/testbucket/\": dial tcp 127.0.0.1:9002: connect: connection refused)", HTTPStatusCode:404, ObjectSize:"", RangeRequested:""}) (*fmt.wrapError)
       5: internal/logger/logger.go:268:logger.LogIf()
       4: cmd/logging.go:16:cmd.replLogIf()
       3: cmd/site-replication.go:5228:cmd.(*SiteReplicationSys).healBucketReplicationConfig()
       2: cmd/site-replication.go:4467:cmd.(*SiteReplicationSys).healBuckets()
       1: cmd/site-replication.go:4281:cmd.(*SiteReplicationSys).startHealRoutine()
```

## Possible Solution
Use logger.OnceIf() to effectively mute the similar looking logs for 1hr

## Steps to Reproduce (for bugs)
Setup site replication and then turn-off one of the sites and observe the logs on online site.

## Context

Copious amount of logs are useless and they yield no real value, they are a hindrance towards an RCA. 

## Your Environment
master branch

### PR DESCRIPTION
**Pull request by shtripat**
## Community Contribution License
All community contributions in this pull request are licensed to the project maintainers
under the terms of the [Apache 2 license](https://www.apache.org/licenses/LICENSE-2.0). 
By creating this pull request I represent that I have the right to license the 
contributions to the project maintainers under the Apache 2 license.

## Description
Also sort the errors map for multiple sites in ascending order of deployment ids, so that the error message generated is always definitive order and same.
Otherwise error messages were happening in random order for different sites and so they used to not match and treated as different error messages and logged again (comparison with old messages used to fail).

## Motivation and Context
Fixes: https://github.com/minio/minio/issues/20057

## How to test this PR?
Follow the issue https://github.com/minio/minio/issues/20057 and logs should not repeat again and again

## Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Optimization (provides speedup with no functional changes)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [ ] Fixes a regression (If yes, please add `commit-id` or `PR #` here)
- [ ] Unit tests added/updated
- [ ] Internal documentation updated
- [ ] Create a documentation update request [here](https://github.com/minio/docs/issues/new?label=doc-change,title=Doc+Updated+Needed+For+PR+github.com%2fminio%2fminio%2fpull%2fNNNNN)

### CODE REVIEW

File: cmd/site-replication.go [hunk 1]
```diff
@@ -2268,9 +2268,20 @@ func (c *SiteReplicationSys) toErrorFromErrMap(errMap map[string]error, actionNa
...
 func (c *SiteReplicationSys) newConcErr(errMap map[string]error, actionName string) error {
+	// Sort keys of errMap to arrange errors in definitive order always
+	keys := []string{}
+	orderedErrMap := make(map[string]error, len(keys))
+	for d := range errMap {
+		keys = append(keys, d)
+	}
+	sort.Strings(keys)
+	for _, key := range keys {
+		orderedErrMap[key] = errMap[key]
```
Comment (klauspost) [inline cmd/site-replication.go]: That is not how maps work ;)

Order is always random.

Comment (shtripat) [reply cmd/site-replication.go]: yes, that was a mistake. Changed the logic now.

**Review by harshavardhana — APPROVED** [review]

**Review by klauspost — APPROVED** [review]

**Review by vadmeste — APPROVED** [review]
