### PR TITLE
api: MakeBucket() should honor regions properly.

### LINKED ISSUE #4967: MakeBucket call should fail if region is set in config.json and the region sent by client does not match
Server should validate the region parameter in MakeBucket call, if it is set in the server side

## Expected Behavior
If wrong region is sent by the client, MakeBucket call should fail.

## Current Behavior
Currently MakeBucket call succeeds, even if the region is set to say us-west-2 in config.json and the client sets the region to us-east-1

## Possible Solution
Server should fail to create the bucket if the region sent by the client does not match the region information is set in config.json. This check can be ignored if there is no region information set in config.json.

## Steps to Reproduce (for bugs)
1. Set region value to "region": "us-west-2" in .minio/config.json
2. Start your Minio server
3. Use the follwoing code to reproduce the issue
```
package main

import (
	"fmt"
	"log"
	"math/rand"
	"time"
	minio "github.com/minio/minio-go"
)

func main() {
	// initialize logging params
	startTime := time.Now()
	function := "GetObject(bucketName, objectName)"
	args := map[string]interface{}{
		"bucketName": "",
		"objectName": "",
	}

	// Seed random based on current time.
	rand.Seed(time.Now().Unix())

	// Instantiate new minio client object.
	c, err := minio.New("localhost:9000", "minio", "minio123", false)
	if err != nil {
		log.Fatalln(function, args, startTime, "", "Minio client object creation failed", err)
	}

	// Generate a new random bucket name.
	bucketName := fmt.Sprintf("minio-go-test.%d", rand.Int())
	args["bucketName"] = bucketName

	// Make a new bucket.
	err = c.MakeBucket(bucketName, "us-east-1")
	if err != nil {
		fmt.Println("MakeBucket failed as expected")
	} else {
		log.Fatalln("MakeBucket success")
	}
	
}
```
## Your Environment
* Operating System and version (`uname -a`):
Linux ubuntu-ltp 4.10.0-35-generic #39-Ubuntu SMP Wed Sep 13 07:46:59 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

### PR DESCRIPTION
**Pull request by harshavardhana**
## Description
api: MakeBucket() should honor regions properly.

## Motivation and Context
Fixes #4967

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

File: cmd/bucket-handlers.go [hunk 1]
```diff
@@ -380,7 +380,7 @@ func (api objectAPIHandlers) PutBucketHandler(w http.ResponseWriter, r *http.Req
 	}
 
 	// PutBucket does not have any bucket action.
-	s3Error := checkRequestAuthType(r, "", "", globalMinioDefaultRegion)
```
Comment (vadmeste) [inline cmd/bucket-handlers.go]: As per my understanding, if we do this, it means the following `if` will not be needed

File: cmd/bucket-handlers.go [hunk 2]
```diff
@@ -380,7 +380,7 @@ func (api objectAPIHandlers) PutBucketHandler(w http.ResponseWriter, r *http.Req
...
+	s3Error := checkRequestAuthType(r, "", "", globalServerRegion)
```
Comment (vadmeste) [inline cmd/bucket-handlers.go]: As per my understanding, if we do this, it means the following `if` will not be needed

Comment (harshavardhana) [reply cmd/bucket-handlers.go]: Yes that is correct, it was never called anymore @vadmeste

**Review by donatello — APPROVED** [review]

**Review by krishnasrinivas — APPROVED** [review]
