### PR TITLE
Vendorize minio-go

### LINKED ISSUE #6873: [gateway] Is it possible to use minio gateway / caching with Chinese AWS regions such as for cn-north-1?
I would like to use _minio gateway s3_ with the Chinese AWS regions such as _cn-north-1__ or __cn-northwest-1_ but receive errors when starting up.

## Expected Behavior
I expected to require to define, apart from AWS_ACCESS_KEY and AWS_SECRET_KEY, a custom endpoint as this is different for the Chinese regions:

_cn-north-1- s3.cn-north-1.amazonaws.com.cn_
_cn-northwest-1 - s3.cn-northwest-1.amazonaws.com.cn_

mc does know the distinction as well, https://github.com/minio/mc/blob/master/vendor/github.com/minio/minio-go/s3-endpoints.go

## Current Behavior
Whatever I tried, adding or leaving out AWS_REGION or MINIO_REGION or the custom endpoint I received either:

> ERROR Unable to initialize gateway backend: The specified bucket does not exist.

>  "ERROR Unable to initialize gateway backend: The AWS Access Key Id you provided does not exist in our records.."

or even 

> ERROR Unable to initialize gateway backend: The authorization header is malformed; the region 'us-east-1' is wrong; expecting 'cn-north-1'.

when adding port 443, as in _https://s3.cn-north-1.amazonaws.com.cn:443_ to the endpoint.

## Steps to Reproduce (for bugs)

```
docker run --rm -p 9000:9000 --name minio-s3 \
-e "AWS_ACCESS_KEY_ID=redacted" \
-e "AWS_SECRET_KEY=redacted" \
-e "MINIO_ACCESS_KEY=youraccess" \
-e "MINIO_SECRET_KEY=wasgranted" \
 -e "AWS_REGION=cn-north-1" \
 -e "MINIO_REGION=cn-north-1" \
minio/minio gateway s3 https://s3.cn-north-1.amazonaws.com.cn    

```

## Context
Since the connectivity between Europe and China is quite affected by latency and also packet loss, a remote S3 bucket in cn-north-1 that needs to be accessed from across the globe would greatly benefit from the gateway and caching abilities of minio.

## Your Environment
* Version used (`minio version`): docker image with tag RELEASE.2018-11-22T02-51-56Z

### PR DESCRIPTION
**Pull request by kannappanr**
## Description
Vendorize minio-go to take the latest changes from minio-go to fix #6873

## Motivation and Context
Fixes #6873

## Regression
No

## How Has This Been Tested?
`MINIO_ACCESS_KEY=Your_Access_Key MINIO_SECRET_KEY=Your_Secret_key  minio gateway s3 https://s3.ca-central-1.amazonaws.com`

You will see `ERROR Unable to initialize gateway backend: The specified bucket does not exist..` error without this fix.

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added unit tests to cover my changes.
- [ ] I have added/updated functional tests in [mint](https://github.com/minio/mint). (If yes, add `mint` PR # here: )
- [x] All new and existing tests passed.

### CODE REVIEW

File: cmd/gateway/s3/gateway-s3.go [hunk 1]
```diff
@@ -510,7 +510,7 @@ func (l *s3Objects) AbortMultipartUpload(ctx context.Context, bucket string, obj
 
 // CompleteMultipartUpload completes ongoing multipart upload and finalizes object
 func (l *s3Objects) CompleteMultipartUpload(ctx context.Context, bucket string, object string, uploadID string, uploadedParts []minio.CompletePart, opts minio.ObjectOptions) (oi minio.ObjectInfo, e error) {
-	err := l.Client.CompleteMultipartUpload(bucket, object, uploadID, minio.ToMinioClientCompleteParts(uploadedParts))
+	_, err := l.Client.CompleteMultipartUpload(bucket, object, uploadID, minio.ToMinioClientCompleteParts(uploadedParts))
```
Comment (harshavardhana) [inline cmd/gateway/s3/gateway-s3.go]: We can use this ETag returned and fill it in minio.ObjectInfo, rather than doing GetObjectInfo? It optimizes the call here.

**Review by harshavardhana — CHANGES_REQUESTED** [review]

**Comment by minio-ops** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-tls.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-compression-fs.sh | :heavy_check_mark: |
| mint-worm.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-compression-xl.sh | :x: [more...](#aec0e190-a67b-4010-98d7-c79a29d6c642) |
| mint-xl.sh | :x: [more...](#b603a9a7-004b-4453-aecc-c70584b6ba39) |
| mint-large-bucket.sh | :x: [more...](#44413e95-05f4-4fc1-a655-ab609bc17d75) |
| mint-dist-xl.sh | :x: [more...](#1107ccab-e731-40f7-b31a-c3212fb8e071) |
<a name="44413e95-05f4-4fc1-a655-ab609bc17d75"></a>
### 6883-919de92/mint-large-bucket.sh.log:
```
Running with
SERVER_ENDPOINT:      minikube:31868
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 35a3a4535413:/mint/log /tmp/mint-logs'

(1/13) Running awscli tests ... FAILED in 43 seconds
{
  "name": "awscli",
  "duration": 21939,
  "function": "aws --endpoint-url http://minikube:31868 s3api get-object --bucket awscli-mint-test-bucket-31778 --key awscli-mint-test-bucket-31778-object /tmp/datafile-0-b\n",
  "status": "FAIL",
  "error": "An error occurred (InternalError) when calling the GetObject operation (reached max retries: 4): We encountered an internal error, please try again."
}

Executed 0 out of 13 tests successfully.
```
<a name="1107ccab-e731-40f7-b31a-c3212fb8e071"></a>
### 6883-919de92/mint-dist-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      minikube:32165
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 40e4e873049e:/mint/log /tmp/mint-logs'

(1/13) Running awscli tests ... FAILED in 36 seconds
{
  "name": "awscli",
  "duration": 19905,
  "function": "aws --endpoint-url http://minikube:32165 s3api get-object --bucket awscli-mint-test-bucket-9968 --key awscli-mint-test-bucket-9968-object /tmp/datafile-0-b\n",
  "status": "FAIL",
  "error": "An error occurred (InternalError) when calling the GetObject operation (reached max retries: 4): We encountered an internal error, please try again."
}

Executed 0 out of 13 tests successfully.
```
<a name="b603a9a7-004b-4453-aecc-c70584b6ba39"></a>
### 6883-919de92/mint-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      minikube:30634
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 1d69f5eeb733:/mint/log /tmp/mint-logs'

(1/13) Running awscli tests ... FAILED in 1 minutes and 17 seconds
{
  "name": "awscli",
  "duration": 29961,
  "function": "aws --endpoint-url http://minikube:30634 s3api get-object --bucket awscli-mint-test-bucket-31183 --key awscli-mint-test-bucket-31183-object /tmp/datafile-0-b\n",
  "status": "FAIL",
  "error": "An error occurred (InternalError) when calling the GetObject operation (reached max retries: 4): We encountered an internal error, please try again."
}

Executed 0 out of 13 tests successfully.
```
<a name="aec0e190-a67b-4010-98d7-c79a29d6c642"></a>
### 6883-919de92/mint-compression-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      minikube:30637
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 802701fe7a8f:/mint/log /tmp/mint-logs'

(1/13) Running awscli tests ... FAILED in 1 minutes and 23 seconds
{
  "name": "awscli",
  "duration": 33181,
  "function": "aws --endpoint-url http://minikube:30637 s3api get-object --bucket awscli-mint-test-bucket-24501 --key awscli-mint-test-bucket-24501-object /tmp/datafile-0-b\n",
  "status": "FAIL",
  "error": "An error occurred (InternalError) when calling the GetObject operation (reached max retries: 4): We encountered an internal error, please try again."
}

Executed 0 out of 13 tests successfully.
```

File: cmd/gateway/s3/gateway-s3.go (hunk 1 above)
Comment (kannappanr) [reply cmd/gateway/s3/gateway-s3.go]: This is already being done in another PR. That was why I did not do it here. Will go ahead and add that code here.

**Comment by minio-ops** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-tls.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-compression-fs.sh | :heavy_check_mark: |
| mint-worm.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-compression-xl.sh | :x: [more...](#01f0927a-0fc9-4727-8249-a94dd546d8b3) |
| mint-xl.sh | :x: [more...](#0da34e91-263e-4269-9c53-d08515db9f75) |
| mint-large-bucket.sh | :x: [more...](#9db2d5af-cc6d-4e1b-b442-a8424e391121) |
| mint-dist-xl.sh | :x: [more...](#dfade79f-8c22-4fd0-8a15-25444450d605) |
<a name="9db2d5af-cc6d-4e1b-b442-a8424e391121"></a>
### 6883-cd89eca/mint-large-bucket.sh.log:
```
Running with
SERVER_ENDPOINT:      minikube:30101
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 6a26e0b4c655:/mint/log /tmp/mint-logs'

(1/13) Running awscli tests ... FAILED in 43 seconds
{
  "name": "awscli",
  "duration": 21751,
  "function": "aws --endpoint-url http://minikube:30101 s3api get-object --bucket awscli-mint-test-bucket-14074 --key awscli-mint-test-bucket-14074-object /tmp/datafile-0-b\n",
  "status": "FAIL",
  "error": "An error occurred (InternalError) when calling the GetObject operation (reached max retries: 4): We encountered an internal error, please try again."
}

Executed 0 out of 13 tests successfully.
```
<a name="dfade79f-8c22-4fd0-8a15-25444450d605"></a>
### 6883-cd89eca/mint-dist-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      minikube:30663
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp a0ad556718f1:/mint/log /tmp/mint-logs'

(1/13) Running awscli tests ... FAILED in 35 seconds
{
  "name": "awscli",
  "duration": 18327,
  "function": "aws --endpoint-url http://minikube:30663 s3api get-object --bucket awscli-mint-test-bucket-22526 --key awscli-mint-test-bucket-22526-object /tmp/datafile-0-b\n",
  "status": "FAIL",
  "error": "An error occurred (InternalError) when calling the GetObject operation (reached max retries: 4): We encountered an internal error, please try again."
}

Executed 0 out of 13 tests successfully.
```
<a name="0da34e91-263e-4269-9c53-d08515db9f75"></a>
### 6883-cd89eca/mint-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      minikube:32145
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 4bc871ca55d1:/mint/log /tmp/mint-logs'

(1/13) Running awscli tests ... FAILED in 1 minutes and 12 seconds
{
  "name": "awscli",
  "duration": 24629,
  "function": "aws --endpoint-url http://minikube:32145 s3api get-object --bucket awscli-mint-test-bucket-21327 --key awscli-mint-test-bucket-21327-object /tmp/datafile-0-b\n",
  "status": "FAIL",
  "error": "An error occurred (InternalError) when calling the GetObject operation (reached max retries: 4): We encountered an internal error, please try again."
}

Executed 0 out of 13 tests successfully.
```
<a name="01f0927a-0fc9-4727-8249-a94dd546d8b3"></a>
### 6883-cd89eca/mint-compression-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      minikube:32183
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 042d4a6b56c2:/mint/log /tmp/mint-logs'

(1/13) Running awscli tests ... FAILED in 1 minutes and 17 seconds
{
  "name": "awscli",
  "duration": 26505,
  "function": "aws --endpoint-url http://minikube:32183 s3api get-object --bucket awscli-mint-test-bucket-11791 --key awscli-mint-test-bucket-11791-object /tmp/datafile-0-b\n",
  "status": "FAIL",
  "error": "An error occurred (InternalError) when calling the GetObject operation (reached max retries: 4): We encountered an internal error, please try again."
}

Executed 0 out of 13 tests successfully.
```

**Comment by minio-ops** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-tls.sh | :heavy_check_mark: |
| mint-compression-xl.sh | :heavy_check_mark: |
| mint-xl.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-compression-fs.sh | :heavy_check_mark: |
| mint-worm.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-dist-xl.sh | :heavy_check_mark: |

**Review by poornas — APPROVED** [review]

**Review by harshavardhana — APPROVED** [review]
