### PR TITLE
xl: Heal empty parts

### LINKED ISSUE #7366: heal: Fail to heal part.1 when corrupted and empty
## Expected Behavior
Whatever the content of part.1, healing should be able to fix the object if it can be recovered.

## Current Behavior
Unable to heal the object, yellow object in mc admin heal output

## Possible Solution
Do not know yet

## Steps to Reproduce (for bugs)
```
1. dd if=/dev/urandom of=file bs=1024 count=1024
2. mc mb myminio/testbucket/
3. mc cp file myminio/testbucket/
4. rm -rf /path/to/backend/disk-1/testbucket/file/part.1 && touch /path/to/backend/disk-1/testbucket/file/part.1
5. mc admin heal -r myminio/testbucket/ 
```

## Context
Fixing a found bug

## Regression
Do not know

## Your Environment
All

### PR DESCRIPTION
**Pull request by vadmeste**
## Description
posix.VerifyFile() doesn't know how to check if a file
is corrupted if that file is empty. We do have the part
size in xl.json so we pass it to VerifyFile to return
an error so healing empty parts can work properly.

## Motivation and Context
Fixes #7366 

## How to test this PR?
Described here

## Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [ ] Fixes a regression (If yes, please add `commit-id` or `PR #` here)
- [ ] Documentation needed
- [x] Unit tests needed
- [ ] Functional tests needed (If yes, add [mint](https://github.com/minio/mint) PR # here: )

### CODE REVIEW

**Comment by minio-ops** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-compression-xl.sh | :heavy_check_mark: |
| mint-xl.sh | :heavy_check_mark: |
| mint-compression-fs.sh | :heavy_check_mark: |
| mint-worm.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :x: [more...](#be0ca0f9-f2e8-4c53-96c9-2d01aa6e0a42) |
| mint-compression-dist-xl.sh | :x: [more...](#34f1d0ae-fad4-4590-8274-59107621b202) |
| mint-dist-xl.sh | :x: [more...](#48ec632a-8b3a-4aab-83c9-f4540b41dbef) |
<a name="be0ca0f9-f2e8-4c53-96c9-2d01aa6e0a42"></a>
### 7860-3702018/mint-large-bucket.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.59:31843
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 5e6a2befb84c:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 2 seconds
(2/14) Running aws-sdk-java tests ... done in 2 seconds
(3/14) Running aws-sdk-php tests ... done in 49 seconds
(4/14) Running aws-sdk-ruby tests ... done in 18 seconds
(5/14) Running awscli tests ... done in 2 minutes and 13 seconds
(6/14) Running healthcheck tests ... done in 0 seconds
(7/14) Running mc tests ... FAILED in 1 minutes and 15 seconds
{
  "name": "mc",
  "duration": "70675",
  "function": "test_put_object_with_storage_class",
  "status": "FAIL",
  "error": "/mint/run/core/mc/mc --config-dir /tmp/.mc-9974 --quiet --no-color cp --storage-class REDUCED_REDUNDANCY /mint/data/datafile-1-MB myminio/mc-test-bucket-13164/mc-test-object-3263  >>> \n`/mint/data/datafile-1-MB` -> `myminio/mc-test-bucket-13164/mc-test-object-3263`\nmc: <ERROR> Failed to copy `/mint/data/datafile-1-MB`. Please reduce your request\nmc: <ERROR> Session safely terminated. To resume session `mc session resume iznCdAcR`"
}

Executed 6 out of 14 tests successfully.
```
<a name="48ec632a-8b3a-4aab-83c9-f4540b41dbef"></a>
### 7860-3702018/mint-dist-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.51:30045
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp ad19ec913db1:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 1 seconds
(2/14) Running aws-sdk-java tests ... done in 1 seconds
(3/14) Running aws-sdk-php tests ... done in 43 seconds
(4/14) Running aws-sdk-ruby tests ... done in 3 seconds
(5/14) Running awscli tests ... done in 2 minutes and 4 seconds
(6/14) Running healthcheck tests ... done in 0 seconds
(7/14) Running mc tests ... done in 46 seconds
(8/14) Running minio-dotnet tests ... done in 36 seconds
(9/14) Running minio-go tests ... done in 56 seconds
(10/14) Running minio-java tests ... FAILED in 1 minutes and 9 seconds
{
  "name": "minio-java",
  "function": "listIncompleteUploads(final String bucketName, final String prefix, final boolean recursive)",
  "args": "prefix: minio, recursive: true",
  "duration": 631,
  "status": "FAIL",
  "error": "error occurred\nErrorResponse(code=SlowDown, message=Please reduce your request, bucketName=minio-java-test-29m3jpl, objectName=minio-java-test-1qahkrs, resource=/minio-java-test-29m3jpl/minio-java-test-1qahkrs, requestId=15AD6471FB13112B, hostId=8e31febf-439c-4c7e-b1a3-dd8cd6d5ad59)\nrequest={method=DELETE, url=http://72.28.97.51:30045/minio-java-test-29m3jpl/minio-java-test-1qahkrs?uploadId=6c269e68-08ed-49e9-a784-56d46805eb94, headers=Host: 72.28.97.51:30045\nUser-Agent: MinIO (amd64; amd64) minio-java/dev\nx-amz-content-sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855\nx-amz-date: 20190701T210446Z\nAuthorization: AWS4-HMAC-SHA256 Credential=*REDACTED*/20190701/us-east-1/s3/aws4_request, SignedHeaders=host;x-amz-content-sha256;x-amz-date, Signature=*REDACTED*\n}\nresponse={code=503, headers=Accept-Ranges: bytes\nContent-Length: 363\nContent-Security-Policy: block-all-mixed-content\nContent-Type: application/xml\nRetry-After: 120\nServer: MinIO/DEVELOPMENT.2019-07-01T20-45-22Z\nVary: Origin\nX-Amz-Request-Id: 15AD6471FB13112B\nX-Minio-Deployment-Id: 8e31febf-439c-4c7e-b1a3-dd8cd6d5ad59\nX-Xss-Protection: 1; mode=block\nDate: Mon, 01 Jul 2019 21:04:46 GMT\n}\n >>> [io.minio.MinioClient.executeReq(MinioClient.java:1204), io.minio.MinioClient.execute(MinioClient.java:1070), io.minio.MinioClient.executeDelete(MinioClient.java:1347), io.minio.MinioClient.abortMultipartUpload(MinioClient.java:5149), io.minio.MinioClient.putObject(MinioClient.java:4337), io.minio.MinioClient.putObject(MinioClient.java:4183), FunctionalTest.listIncompleteUploads_test3(FunctionalTest.java:1679), FunctionalTest.runTests(FunctionalTest.java:2990), FunctionalTest.main(FunctionalTest.java:3118)]"
}

Executed 9 out of 14 tests successfully.
```
<a name="34f1d0ae-fad4-4590-8274-59107621b202"></a>
### 7860-3702018/mint-compression-dist-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.57:30611
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 8537fb6b2a14:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... FAILED in 3 seconds
{
  "alert": "",
  "args": {
    "bucketName": "aws-sdk-go-test-dmz3kqhaq0gxjt",
    "expiry": 60000000000,
    "objectName": "presignedTest"
  },
  "duration": 3070,
  "error": "RequestError: send request failed\ncaused by: Put http://72.28.97.57:30611/aws-sdk-go-test-dmz3kqhaq0gxjt: dial tcp 72.28.97.57:30611: connect: no route to host",
  "function": "PresignedPut",
  "message": "AWS SDK Go CreateBucket Failed",
  "name": "aws-sdk-go",
  "status": "FAIL"
}

Executed 0 out of 14 tests successfully.
```

**Review by donatello — APPROVED** [review]

**Review by krishnasrinivas — APPROVED** [review]

**Comment by deekoder** [comment]
Blocked for merge till conflcts are resolved. I will merge as soon as the pr is updated.

**Comment by vadmeste** [comment]
This PR is updated after moving bitrot checking in posix layer

**Comment by minio-ops** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-compression-xl.sh | :heavy_check_mark: |
| mint-xl.sh | :heavy_check_mark: |
| mint-compression-dist-xl.sh | :heavy_check_mark: |
| mint-compression-fs.sh | :heavy_check_mark: |
| mint-worm.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :x: [more...](#2cd0af0f-79b3-4a7a-b4e7-ad6389f5ee74) |
| mint-dist-xl.sh | :x: [more...](#c26fa18a-680b-4d19-820b-75aa77ad2ab1) |
<a name="c26fa18a-680b-4d19-820b-75aa77ad2ab1"></a>
### 7860-189c323/mint-dist-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.56:32614
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 89128a27b68e:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 1 seconds
(2/14) Running aws-sdk-java tests ... done in 1 seconds
(3/14) Running aws-sdk-php tests ... done in 44 seconds
(4/14) Running aws-sdk-ruby tests ... done in 3 seconds
(5/14) Running awscli tests ... done in 2 minutes and 4 seconds
(6/14) Running healthcheck tests ... done in 0 seconds
(7/14) Running mc tests ... done in 1 minutes and 5 seconds
(8/14) Running minio-dotnet tests ... done in 37 seconds
(9/14) Running minio-go tests ... done in 1 minutes and 6 seconds
(10/14) Running minio-java tests ... FAILED in 1 minutes and 26 seconds
{
  "name": "minio-java",
  "function": "presignedGetObject(String bucketName, String objectName, Integer expires)",
  "duration": 89,
  "status": "FAIL",
  "error": "java.lang.Exception: failed to read object. Response: Response{protocol=http/1.1, code=503, message=Service Unavailable, url=http://72.28.97.56:32614/minio-java-test-1ccjrcs/minio-java-test-3sga2bm?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=minio%2F20190712%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20190712T175833Z&X-Amz-Expires=3600&X-Amz-SignedHeaders=host&X-Amz-Signature=c6cc9c146d71226b9f598695fff276feb58b9fced7c3736d9e705e1c85c7fbe4}, Response body: <?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<Error><Code>SlowDown</Code><Message>Please reduce your request</Message><Key>minio-java-test-3sga2bm</Key><BucketName>minio-java-test-1ccjrcs</BucketName><Resource>/minio-java-test-1ccjrcs/minio-java-test-3sga2bm</Resource><RequestId>15B0BAAAB6DA30FC</RequestId><HostId>1f9c6410-858a-4522-b244-aa3602eb993c</HostId></Error> >>> [FunctionalTest.readObject(FunctionalTest.java:201), FunctionalTest.presignedGetObject_test2(FunctionalTest.java:1803), FunctionalTest.runTests(FunctionalTest.java:2995), FunctionalTest.main(FunctionalTest.java:3118)]"
}

Executed 9 out of 14 tests successfully.
```
<a name="2cd0af0f-79b3-4a7a-b4e7-ad6389f5ee74"></a>
### 7860-189c323/mint-large-bucket.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.60:30882
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 4057ff193416:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 2 seconds
(2/14) Running aws-sdk-java tests ... done in 2 seconds
(3/14) Running aws-sdk-php tests ... done in 50 seconds
(4/14) Running aws-sdk-ruby tests ... done in 20 seconds
(5/14) Running awscli tests ... done in 1 minutes and 30 seconds
(6/14) Running healthcheck tests ... done in 0 seconds
(7/14) Running mc tests ... FAILED in 2 minutes and 56 seconds
{
  "name": "mc",
  "duration": "130385",
  "function": "test_mirror_list_objects_storage_class",
  "status": "FAIL",
  "error": "/mint/run/core/mc/mc --config-dir /tmp/.mc-4033 --quiet --no-color mirror --storage-class REDUCED_REDUNDANCY /mint/data myminio/mc-test-bucket-25316  >>> \n`/mint/data/datafile-1-MB` -> `myminio/mc-test-bucket-25316/datafile-1-MB`\n`/mint/data/datafile-0-b` -> `myminio/mc-test-bucket-25316/datafile-0-b`\n`/mint/data/datafile-1-kB` -> `myminio/mc-test-bucket-25316/datafile-1-kB`\n`/mint/data/datafile-10-MB` -> `myminio/mc-test-bucket-25316/datafile-10-MB`\n`/mint/data/datafile-1.03-MB` -> `myminio/mc-test-bucket-25316/datafile-1.03-MB`\n`/mint/data/datafile-1-b` -> `myminio/mc-test-bucket-25316/datafile-1-b`\n`/mint/data/datafile-100-kB` -> `myminio/mc-test-bucket-25316/datafile-100-kB`\n`/mint/data/datafile-10-kB` -> `myminio/mc-test-bucket-25316/datafile-10-kB`\n`/mint/data/datafile-33-kB` -> `myminio/mc-test-bucket-25316/datafile-33-kB`\n`/mint/data/datafile-5243880-b` -> `myminio/mc-test-bucket-25316/datafile-5243880-b`\n`/mint/data/datafile-5-MB` -> `myminio/mc-test-bucket-25316/datafile-5-MB`\n`/mint/data/datafile-11-MB` -> `myminio/mc-test-bucket-25316/datafile-11-MB`\n`/mint/data/datafile-129-MB` -> `myminio/mc-test-bucket-25316/datafile-129-MB`\n`/mint/data/datafile-6-MB` -> `myminio/mc-test-bucket-25316/datafile-6-MB`\n`/mint/data/datafile-65-MB` -> `myminio/mc-test-bucket-25316/datafile-65-MB`\nmc: <ERROR> Failed to copy `/mint/data/datafile-65-MB`. Please reduce your request\nmc: <ERROR> Failed to copy `/mint/data/datafile-11-MB`. Please reduce your request\nmc: <ERROR> Failed to copy `/mint/data/datafile-129-MB`. Please reduce your request\nmc: <ERROR> Failed to copy `/mint/data/datafile-10-MB`. Please reduce your request\nTotal: 233.17 MiB, Transferred: 497.11 MiB, Speed: 3.81 MiB/s"
}

Executed 6 out of 14 tests successfully.
```

File: cmd/xl-v1-healing-common.go [hunk 1]
```diff
@@ -183,10 +183,10 @@ func disksWithAllParts(ctx context.Context, onlineDisks []StorageAPI, partsMetad
 			// it needs healing too.
 			for _, part := range partsMetadata[i].Parts {
 				checksumInfo := erasureInfo.GetChecksumInfo(part.Name)
-				err = onlineDisk.VerifyFile(bucket, pathJoin(object, part.Name), checksumInfo.Algorithm, checksumInfo.Hash, erasure.ShardSize())
+				err = onlineDisk.VerifyFile(bucket, pathJoin(object, part.Name), part.Size == 0, checksumInfo.Algorithm, checksumInfo.Hash, erasure.ShardSize())
```
Comment (krishnasrinivas) [inline cmd/xl-v1-healing-common.go:186]: @vadmeste 

`erasure.ShardFileSize(part.Size)` will give you exact shard file size, hence you can use that instead of `empty` boolean

Comment (vadmeste) [reply cmd/xl-v1-healing-common.go:186]: > @vadmeste
> 
> `erasure.ShardFileSize(part.Size)` will give you exact shard file size, hence you can use that instead of `empty` boolean

Well, bitrot works well for any size, but it just doesn't know what to do for empty files.. I am not sure we need to use size instead of empty flag, (this is the PR which does that anyway https://github.com/minio/minio/pull/7932)

Comment (krishnasrinivas) [reply cmd/xl-v1-healing-common.go:186]: `empty` files are not possible practically since we use O_DIRECT. Similarly incorrect sizes are also not possible. (unless the backend FS does not support O_DIRECT)

Instead of using empty bool you can use the size itself as it is available. For the code reader it is more obvious to see that we are verifying exact size instead of checking for `empty`
