### PR TITLE
select: Fix leak on compressed files

### LINKED ISSUE #11300: MinIO select API for compressed object causing OOM for MinIO Server
## Expected Behavior
MinIO select API for compressed object must not cause OOM for MinIO server.

## Current Behavior
MinIO server resource is increasing and reaching the max resource allocated(i.e 10GB) and server restarts .

## Steps to Reproduce (for bugs)
Code snippet :

   public static String getCSVObjectHeader(String bucketName, String objectName, String contentType,
                                            MinioClient minioClient) throws Exception{
        try {
            String sqlExpression = "select * from S3Object limit 1";
            CompressionType compressionType = null;
            if("application/gzip".equalsIgnoreCase(contentType)
                    || "application/x-gzip".equalsIgnoreCase(contentType)){
                compressionType = CompressionType.GZIP;
            }
            InputSerialization is = new InputSerialization(compressionType, false, null, null, FileHeaderInfo.NONE, null, null, null);
            OutputSerialization os = new OutputSerialization(null, null, null, QuoteFields.ASNEEDED, null);
            SelectResponseStream stream =
                    minioClient.selectObjectContent(
                            SelectObjectContentArgs.builder()
                                    .bucket(bucketName)
                                    .object(objectName)
                                    .sqlExpression(sqlExpression)
                                    .inputSerialization(is)
                                    .outputSerialization(os)
                                    .requestProgress(true)
                                    .build());
            byte[] buf = new byte[2048];
            int bytesRead = stream.read(buf, 0, buf.length);
            String header =  (new String(buf, 0, bytesRead, StandardCharsets.UTF_8)).trim();
            stream.reset();
            stream.close();
            return header;
        } catch(Exception e) {
            System.out.println("Error retrieving header from S3 Object. ");
            throw e;
        }
   }

When fetched header for object, resource for MinIO sever increases gradually and terminates .
image

When not using select API with same load, resource for MinIo server remains in some 100-300MB
image

## Your Environment

* Version used (`minio --version`): 2021-01-05T05:22:38Z
* Server setup and configuration: 4 server with each having (4 CPU and 10GB RAM)
* Operating System and version (`uname -a`): Linux itom-di-minio-1 4.18.0-80.el8.x86_64 #1 SMP Tue Jun 4 09:19:46 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

### PR DESCRIPTION
**Pull request by klauspost**
## Description

Properly close gzip reader when done reading.

Fixes #11300

## How to test this PR?

Upload 1000 gzipped files to a prefix. Execute `mc sql -query="select * from S3Object limit 1" local2/bucket/prefix/`, observe memory usage slowly rise.

## Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)

### CODE REVIEW

File: pkg/s3select/progress.go [hunk 1]
```diff
@@ -92,30 +93,35 @@ func (pr *progressReader) Stats() (bytesScanned, bytesProcessed int64) {
...
+		pr.gzr, err = gzip.NewReader(scannedReader)
 		if err != nil {
 			if errors.Is(err, gzip.ErrHeader) || errors.Is(err, gzip.ErrChecksum) {
 				return nil, errInvalidGZIPCompressionFormat(err)
 			}
 			return nil, errTruncatedInput(err)
 		}
+		r = pr.gzr
 	case bzip2Type:
 		r = bzip2.NewReader(scannedReader)
```
Comment (harshavardhana) [inline pkg/s3select/progress.go:120]: would it still be problem if it was bzip2 @klauspost ?

Comment (klauspost) [reply pkg/s3select/progress.go:120]: @harshavardhana No, it doesn't require closing, it can be GCed as-is.

pgzip has readahead which keeps data unless it reaches the end of the stream, which is why the repro needs a `limit 1`.

Comment (harshavardhana) [reply pkg/s3select/progress.go:120]: ah okay @klauspost

**Review by harshavardhana — APPROVED** [review]

**Comment by minio-trusted** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-s3.sh | :heavy_check_mark: |
| mint-erasure.sh | :heavy_check_mark: |
| mint-dist-erasure.sh | :heavy_check_mark: |
| mint-zoned.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-gateway-azure.sh | :x: [more...](#58bdd908-f79c-4cd7-8b40-07a6eacef4b4) |
<a name="58bdd908-f79c-4cd7-8b40-07a6eacef4b4"></a>
### 11302-86b4750/mint-gateway-azure.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-c3.minio.io:32285
ACCESS_KEY:           minioazure
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 82d3b96f418d:/mint/log /tmp/mint-logs'

(1/15) Running aws-sdk-go tests ... done in 9 seconds
(2/15) Running aws-sdk-java tests ... done in 2 seconds
(3/15) Running aws-sdk-php tests ... done in 2 minutes and 45 seconds
(4/15) Running aws-sdk-ruby tests ... done in 21 seconds
(5/15) Running awscli tests ... done in 2 minutes and 54 seconds
(6/15) Running healthcheck tests ... done in 0 seconds
(7/15) Running mc tests ... done in 3 minutes and 58 seconds
(8/15) Running minio-dotnet tests ... done in 1 minutes and 43 seconds
(9/15) Running minio-go tests ... done in 6 minutes and 38 seconds
(10/15) Running minio-java tests ... FAILED in 8 minutes and 49 seconds
{
  "name": "minio-java",
  "function": "putObject()",
  "args": "[user metadata]",
  "duration": 171,
  "status": "FAIL",
  "error": "error occurred\nErrorResponse(code = AuthenticationFailed, message = -> github.com/Azure/azure-storage-blob-go/azblob.newStorageError, github.com/Azure/azure-storage-blob-go@v0.10.0/azblob/zc_storage_error.go:42\n===== RESPONSE ERROR (ServiceCode=AuthenticationFailed) =====\nDescription=Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature.\nRequestId:1e52eebb-701e-0099-6fa5-ee622c000000\nTime:2021-01-19T20:54:11.2403827Z, Details: \n   AuthenticationErrorDetail: The MAC signature found in the HTTP request 'AtXr1aVhdlBYq/Q4kABHWNaO5aX/QTK6DrZgpps0QKs=' is not the same as any computed signature. Server used following string to sign: 'PUT\n\n\n128\n\napplication/xml\n\n\n\n\n\n\nx-ms-blob-cache-control:\nx-ms-blob-content-disposition:\nx-ms-blob-content-encoding:\nx-ms-blob-content-language:\nx-ms-blob-content-type:application/octet-stream\nx-ms-client-request-id:e830c0d8-9721-4b56-5a94-87d6b0f30718\nx-ms-date:Tue, 19 Jan 2021 20:54:11 GMT\nx-ms-meta-my_header1:a   b   c\nx-ms-meta-my_header2:\"a   b   c\"\nx-ms-meta-my_project:Project One\nx-ms-meta-my_unicode_tag:å•†å“\nx-ms-version:2019-02-02\n/minioazure/minio-java-test-1j1srqk/minio-java-test-17lb22p\ncomp:blocklist\ntimeout:1501'.\n   Code: AuthenticationFailed\n   PUT https://minioazure.blob.core.windows.net/minio-java-test-1j1srqk/minio-java-test-17lb22p?comp=blocklist&timeout=1501\n   Authorization: REDACTED\n   Content-Length: [128]\n   Content-Type: [application/xml]\n   User-Agent: [APN/1.0 MinIO/1.0 MinIO/2021-01-19T20:20:30Z]\n   X-Ms-Blob-Cache-Control: []\n   X-Ms-Blob-Content-Disposition: []\n   X-Ms-Blob-Content-Encoding: []\n   X-Ms-Blob-Content-Language: []\n   X-Ms-Blob-Content-Type: [application/octet-stream]\n   X-Ms-Client-Request-Id: [e830c0d8-9721-4b56-5a94-87d6b0f30718]\n   X-Ms-Date: [Tue, 19 Jan 2021 20:54:11 GMT]\n   X-Ms-Meta-My_header1: [a   b   c]\n   X-Ms-Meta-My_header2: [\"a   b   c\"]\n   X-Ms-Meta-My_project: [Project One]\n   X-Ms-Meta-My_unicode_tag: [商品]\n   X-Ms-Version: [2019-02-02]\n   --------------------------------------------------------------------------------\n   RESPONSE Status: 403 Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature.\n   Content-Length: [1092]\n   Content-Type: [application/xml]\n   Date: [Tue, 19 Jan 2021 20:54:11 GMT]\n   Server: [Microsoft-HTTPAPI/2.0]\n   X-Ms-Error-Code: [AuthenticationFailed]\n   X-Ms-Request-Id: [1e52eebb-701e-0099-6fa5-ee622c000000]\n\n\n, bucketName = minio-java-test-1j1srqk, objectName = minio-java-test-17lb22p, resource = /minio-java-test-1j1srqk/minio-java-test-17lb22p, requestId = 165BBD8074F6401F, hostId = 4a64d371-3c79-4044-b819-6cbdfdff87ef)\nrequest={method=PUT, url=http://minio-c3.minio.io:32285/minio-java-test-1j1srqk/minio-java-test-17lb22p, headers=x-amz-meta-My-Unicode-Tag: 商品\nx-amz-meta-My-Project: Project One\nx-amz-meta-My-header1: a   b   c\nx-amz-meta-My-Header2: \"a   b   c\"\nContent-Type: application/octet-stream\nHost: minio-c3.minio.io:32285\nAccept-Encoding: identity\nUser-Agent: MinIO (Linux; amd64) minio-java/8.0.3\nContent-MD5: A9oFTxee7YVcJ9fWsgQeKg==\nx-amz-content-sha256: 1ff7959f86334ddc5c188a5083268f600146328b2b6c5185e75bf7d9387d6b74\nx-amz-date: 20210119T205411Z\nAuthorization: AWS4-HMAC-SHA256 Credential=*REDACTED*/20210119/us-east-1/s3/aws4_request, SignedHeaders=content-md5;host;x-amz-content-sha256;x-amz-date;x-amz-meta-my-header1;x-amz-meta-my-header2;x-amz-meta-my-project;x-amz-meta-my-unicode-tag, Signature=*REDACTED*\n}\nresponse={code=403, headers=Accept-Ranges: bytes\nContent-Length: 3086\nContent-Security-Policy: block-all-mixed-content\nContent-Type: application/xml\nServer: MinIO\nVary: Origin\nX-Amz-Request-Id: 165BBD8074F6401F\nX-Xss-Protection: 1; mode=block\nDate: Tue, 19 Jan 2021 20:54:11 GMT\n}\n >>> [io.minio.MinioClient.execute(MinioClient.java:775), io.minio.MinioClient.putObject(MinioClient.java:4547), io.minio.MinioClient.putObject(MinioClient.java:2713), io.minio.MinioClient.putObject(MinioClient.java:2830), FunctionalTest.testPutObject(FunctionalTest.java:763), FunctionalTest.putObject(FunctionalTest.java:890), FunctionalTest.runObjectTests(FunctionalTest.java:3751), FunctionalTest.runTests(FunctionalTest.java:3783), FunctionalTest.main(FunctionalTest.java:3927)]"
}
(10/15) Running minio-js tests ... done in 2 minutes and 41 seconds
(11/15) Running minio-py tests ... done in 18 minutes and 40 seconds
(12/15) Running s3cmd tests ... done in 2 minutes and 23 seconds
(13/15) Running s3select tests ... done in 1 minutes and 1 seconds
(14/15) Running security tests ... done in 0 seconds

Executed 14 out of 15 tests successfully.
```
Deleting image on docker hub
Deleting image locally

**Review by poornas — APPROVED** [review]
LGTM
