### PR TITLE
Refactor HTTP server to address bugs

### LINKED ISSUE #4494: Unable to peek into incoming protocol
Sudden printing of these messages. Not really helpful for me as the user to figure out why this message shows up. 

## Expected Behavior
Some indication of what caused it would be more insightful to consume for me as the user. Also they seem to always print in pairs.
 
## Possible Solution
Not print it ?
 
## Steps to Reproduce (for bugs)
 Unsure, it is printed often when the server starts and minio browser is loaded. I am not sure of the exact steps
 

## Your Environment

* Version used (`minio version`): 2017-06-02T22 
* Environment name and version (e.g. nginx 1.9.1):
* Server type and version: 
* Operating System and version (`uname -a`): Windows Server 2016 on aws.
* Link to your project:

### PR DESCRIPTION
**Pull request by balamurugana**
## Description

* Remove unnecessary goroutine to start multiple TCP listeners.
* HTTP server waits for shutdown to maximum of Server.ShutdownTimeout
  than per serverShutdownPoll.
* Handles new connection errors properly.
* Handles read and write timeout properly.
* Handles error on start of HTTP server properly by exiting minio
  process.

Fixes #4494 #4476
## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

File: cmd/certs.go [hunk 1]
```diff
@@ -90,19 +90,26 @@ func getRootCAs(certsCAsDir string) (*x509.CertPool, error) {
 	return rootCAs, nil
 }
 
-func getSSLConfig() (publicCerts []*x509.Certificate, rootCAs *x509.CertPool, secureConn bool, err error) {
+func getSSLConfig() (x509Certs []*x509.Certificate, rootCAs *x509.CertPool, tlsCert *tls.Certificate, secureConn bool, err error) {
```
Comment (harshavardhana) [inline cmd/certs.go:93]: Can you add a test for this function?

File: cmd/gateway-main.go [hunk 2]
```diff
@@ -314,8 +318,8 @@ func gatewayMain(ctx *cli.Context, backendType gatewayBackend) {
 
 	// Check and load SSL certificates.
 	var err error
-	globalPublicCerts, globalRootCAs, globalIsSSL, err = getSSLConfig()
-	fatalIf(err, "Invalid SSL key file")
+	globalPublicCerts, globalRootCAs, globalTLSCertificate, globalIsSSL, err = getSSLConfig()
+	fatalIf(err, "Invalid SSL key/certificate file")
```
Comment (harshavardhana) [inline cmd/gateway-main.go]: `Invalid SSL certificates` is fine.

File: cmd/gateway-main.go [hunk 3]
```diff
@@ -359,17 +363,15 @@ func gatewayMain(ctx *cli.Context, backendType gatewayBackend) {
...
-
+	globalHTTPServer = miniohttp.NewServer([]string{ctx.String("address")}, registerHandlers(router, handlerFns...), globalTLSCertificate)
 	// Start server, automatically configures TLS if certs are available.
 	go func() {
-		cert, key := "", ""
-		if globalIsSSL {
-			cert, key = getPublicCertFile(), getPrivateKeyFile()
-		}
-		fatalIf(apiServer.ListenAndServe(cert, key), "Failed to start minio server")
+		serr := globalHTTPServer.Start()
```
Comment (harshavardhana) [inline cmd/gateway-main.go]: New variable is not needed

```
globalHTTPServerErrorCh <- globalHTTPServer.Start()
```

File: cmd/server-main.go [hunk 4]
```diff
@@ -149,8 +153,8 @@ func serverMain(ctx *cli.Context) {
 
 	// Check and load SSL certificates.
 	var err error
-	globalPublicCerts, globalRootCAs, globalIsSSL, err = getSSLConfig()
-	fatalIf(err, "Invalid SSL key file")
+	globalPublicCerts, globalRootCAs, globalTLSCertificate, globalIsSSL, err = getSSLConfig()
+	fatalIf(err, "Invalid SSL key/certificate file")
```
Comment (harshavardhana) [inline cmd/server-main.go]: "Invalid SSL certificates" is fine..

File: cmd/server-main.go [hunk 5]
```diff
@@ -176,43 +180,47 @@ func serverMain(ctx *cli.Context) {
...
 
+	signal.Notify(globalOSSignalCh, os.Interrupt, syscall.SIGTERM)
+
 	newObject, err := newObjectLayer(globalEndpoints)
-	fatalIf(err, "Initializing object layer failed")
+	if err != nil {
+		errorIf(err, "Initializing object layer failed")
+		err = globalHTTPServer.Shutdown()
+		errorIf(err, "Unable to shutdown http server")
+		os.Exit(1)
```
Comment (harshavardhana) [inline cmd/server-main.go:209]: why this why not just `fatalIf()` ?

File: cmd/signals.go [hunk 6]
```diff
@@ -18,32 +18,75 @@ package cmd
...
-		// Wait for the signal.
-		<-sigCh
+	stopProcess := func() error {
+		err := globalHTTPServer.Shutdown()
+		errorIf(err, "Unable to shutdown http server")
+		if objAPI := newObjectLayerFn(); objAPI != nil {
+			oerr := objAPI.Shutdown()
+			errorIf(oerr, "Unable to shutdown object layer")
+			if err == nil {
+				err = oerr
```
Comment (harshavardhana) [inline cmd/signals.go]: This is pretty convoluted code.. why is it done this way? we should just return in this pattern 

```
if err := globalHTTPServer.Shutdown(); err != nil {
     errorIf(err, "Unable to shutdown http server")
     return err
}
```

File: cmd/signals.go [hunk 7]
```diff
@@ -18,32 +18,75 @@ package cmd
...
+	}
 
-		// Notify the caller.
-		trapCh <- true
-	}(trapCh)
+	for {
+		select {
+		case err := <-globalHTTPServerErrorCh:
+			errorIf(err, "http server exited abnormally")
+			if objAPI := newObjectLayerFn(); objAPI != nil {
```
Comment (harshavardhana) [inline cmd/signals.go]: why initialize objectlayer again when http server exited?

File: cmd/signals.go [hunk 8]
```diff
@@ -18,32 +18,75 @@ package cmd
...
+				oerr := objAPI.Shutdown()
+				errorIf(oerr, "Unable to shutdown object layer")
+				if err == nil {
+					err = oerr
```
Comment (harshavardhana) [inline cmd/signals.go]: same as above this pattern is very go like.

File: pkg/http/bufconn.go [hunk 9]
```diff
@@ -0,0 +1,88 @@
...
+
+func (c *bufConn) setReadTimeout() {
+	if c.readTimeout != 0 {
+		c.SetReadDeadline(time.Now().Add(c.readTimeout))
+	}
+}
+
+func (c *bufConn) setWriteTimeout() {
+	if c.writeTimeout != 0 {
+		c.SetWriteDeadline(time.Now().Add(c.writeTimeout))
```
Comment (harshavardhana) [inline pkg/http/bufconn.go]: Needs a test case.. for this.

File: pkg/http/bufconn.go [hunk 10]
```diff
@@ -0,0 +1,88 @@
...
+	return c.bufReader.Peek(n)
+}
+
+// Read - reads data from the connection using wrapped buffered reader.
+func (c *bufConn) Read(b []byte) (n int, err error) {
+	c.setReadTimeout()
+	n, err = c.bufReader.Read(b)
+
+	if c.updateBytesReadFunc != nil {
+		c.updateBytesReadFunc(n)
```
Comment (harshavardhana) [inline pkg/http/bufconn.go]: Needs a testcase for this as well.

File: pkg/http/listener.go [hunk 11]
```diff
@@ -0,0 +1,326 @@
...
+}
+
+// Accept - reads from httpListener.acceptCh for one of previously accepted TCP connection and returns the same.
+func (listener *httpListener) Accept() (conn net.Conn, err error) {
+	result, ok := <-listener.acceptCh
+	if ok {
+		return result.conn, result.err
+	}
+
+	return nil, io.EOF
```
Comment (harshavardhana) [inline pkg/http/listener.go]: is Accept supposed to give io.EOF? this is not an I/O operation... perhaps you should use a better error here.

File: pkg/http/server.go [hunk 12]
```diff
@@ -0,0 +1,184 @@
...
+	// Start servicing with listener.
+	return srv.Server.Serve(listener)
+}
+
+// Shutdown - shuts down HTTP server.
+func (srv *Server) Shutdown() error {
+	srv.inShutdownMutex.Lock()
+	if !srv.inShutdown {
+		// Indicate the server is in shutdown.
+		srv.inShutdown = true
```
Comment (harshavardhana) [inline pkg/http/server.go]: You don't need two variables one lock and another variable it is better to use sync.Atomic - https://golang.org/src/net/http/server.go?s=74304:74358#L2440

File: pkg/http/listener.go [hunk 13]
```diff
@@ -0,0 +1,326 @@
...
+}
+
+// Close - closes underneath all TCP listeners.
+func (listener *httpListener) Close() (err error) {
+	listener.mutex.Lock()
+	defer listener.mutex.Unlock()
+	if listener.doneChs == nil {
```
Comment (harshavardhana) [inline pkg/http/listener.go]: Rather than doing like this you could simply loop over doneChs 

```
for i := range listener.doneChs {
}
```

File: pkg/http/listener.go [hunk 14]
```diff
@@ -0,0 +1,326 @@
...
+
+	for _, serverAddr := range serverAddrs {
+		var l net.Listener
+		if l, err = net.Listen("tcp", serverAddr); err != nil {
+			return nil, err
+		}
+
+		tcpListener, ok := l.(*net.TCPListener)
+		if !ok {
+			return nil, errors.New("unexpected assertion failure to get net.TCPListener")
```
Comment (harshavardhana) [inline pkg/http/listener.go]: Error message can be better..

File: pkg/http/server.go [hunk 15]
```diff
@@ -0,0 +1,184 @@
...
+	}
+
+	// Wrap given handler to do additional
+	// * return 503 (service unavailable) if the server in shutdown.
+	wrappedHandler := http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
+		atomic.AddInt32(&srv.requestCount, 1)
+		defer atomic.AddInt32(&srv.requestCount, -1)
+
+		// If server is in shutdown, return 503 (service unavailable)
+		srv.inShutdownMutex.Lock()
```
Comment (harshavardhana) [inline pkg/http/server.go]: Need for this type of locking.. you can use sync.Atomic

**Review by harshavardhana — CHANGES_REQUESTED** [review]

File: cmd/certs.go (hunk 1 above)
Comment (balamurugana) [reply cmd/certs.go:93]: Functions used in `getSSLConfig()` have unit tests individually.  Let me know if you want separate test function.

File: cmd/gateway-main.go (hunk 2 above)
Comment (balamurugana) [reply cmd/gateway-main.go]: I think we would need to convey the problem with key/certificate files.

File: cmd/gateway-main.go (hunk 3 above)
Comment (balamurugana) [reply cmd/gateway-main.go]: Done

File: cmd/server-main.go (hunk 4 above)
Comment (balamurugana) [reply cmd/server-main.go]: Replied to the same case above.

File: cmd/server-main.go (hunk 5 above)
Comment (balamurugana) [reply cmd/server-main.go:209]: If `globalHTTPServer.Shutdown()` returns `nil` ie clean shutdown, we should `os.Exit(1)` as well.

File: cmd/signals.go (hunk 6 above)
Comment (balamurugana) [reply cmd/signals.go]: Changing the function to return `bool` which will simplify over all logic.

File: cmd/signals.go (hunk 7 above)
Comment (balamurugana) [reply cmd/signals.go]: Using same logic from https://github.com/minio/minio/blob/master/cmd/service.go#L104

File: cmd/signals.go (hunk 8 above)
Comment (balamurugana) [reply cmd/signals.go]: Changing the function to return `bool` which will simplify over all logic.

File: pkg/http/bufconn.go (hunk 9 above)
Comment (balamurugana) [reply pkg/http/bufconn.go]: Its hard to introduce delay in writing to a connection.  Any write to connection happens without an error.  Requires inputs for the test.

File: pkg/http/bufconn.go (hunk 10 above)
Comment (balamurugana) [reply pkg/http/bufconn.go]: The callback function is called with data read from the connection.  Not sure what value it adds with the test case.

File: pkg/http/listener.go (hunk 11 above)
Comment (balamurugana) [reply pkg/http/listener.go]: Requires help for better error to return.

File: pkg/http/listener.go (hunk 13 above)
Comment (balamurugana) [reply pkg/http/listener.go]: Not applicable.  This is a check to do whether there are tcp listeners underneath.

File: pkg/http/listener.go (hunk 14 above)
Comment (balamurugana) [reply pkg/http/listener.go]: Any suggestion?

File: pkg/http/server.go (hunk 12 above)
Comment (balamurugana) [reply pkg/http/server.go]: The approach is different here.  Its not only guard `src.inShutdown`, it also guards shutdown operation ie there is no need to have one more mutex with `sync.Atomic`

File: pkg/http/server.go (hunk 15 above)
Comment (balamurugana) [reply pkg/http/server.go]: See below.

File: cmd/server-main.go (hunk 5 above)
Comment (harshavardhana) [reply cmd/server-main.go:209]: ~~Why os.Exit should only have a status `1`  on a clean shutdown. This can cause confusion if there is a script trapping the status. We are also not differentiating between unclean and clean shutdown both have os.Exit set to 1~~

File: cmd/gateway-main.go (hunk 2 above)
Comment (harshavardhana) [reply cmd/gateway-main.go]: There is no meaning in SSL to separately indicate this .. key and crt in conjunction are called SSL certificates. We don't need to print code level differentiation IMO.

File: pkg/http/bufconn.go (hunk 10 above)
Comment (harshavardhana) [reply pkg/http/bufconn.go]: To see if it really updates the internal valus.

File: pkg/http/bufconn.go (hunk 9 above)
Comment (harshavardhana) [reply pkg/http/bufconn.go]: WriteTimeout is configurable we can add a test case.

File: pkg/http/server.go (hunk 12 above)
Comment (harshavardhana) [reply pkg/http/server.go]: You don't need a mutex is also what I am suggesting.

File: pkg/http/listener.go (hunk 11 above)
Comment (harshavardhana) [reply pkg/http/listener.go]: We should return syscall.EINVAL just like pkg/net implementation

File: pkg/http/listener.go (hunk 13 above)
Comment (harshavardhana) [reply pkg/http/listener.go]: A double Close on listener should return error as syscall.EINVAL

File: cmd/certs.go (hunk 1 above)
Comment (harshavardhana) [reply cmd/certs.go:93]: Then its not needed @balamurugana

File: cmd/gateway-main.go (hunk 2 above)
Comment (balamurugana) [reply cmd/gateway-main.go]: Done

File: pkg/http/listener.go (hunk 11 above)
Comment (balamurugana) [reply pkg/http/listener.go]: Done

File: pkg/http/listener.go (hunk 13 above)
Comment (balamurugana) [reply pkg/http/listener.go]: Done

**Review by harshavardhana — APPROVED** [review]
Changes LGTM now @balamurugana going to build and start testing with varied workload.

**Comment by harshavardhana** [comment]
Looks like i/o timeout is still happening i can reproduce it right after 30secs. 

```
Initializing data volume.
[01/04] http://147.75.90.109:9000/export1 - 218 GiB online
[02/04] http://147.75.90.109:9000/export2 - 218 GiB online
[03/04] http://147.75.90.45:9000/export1 - 218 GiB online
[04/04] http://147.75.90.45:9000/export2 - 218 GiB online
Endpoint:  http://147.75.90.109:9000  http://10.88.126.7:9000  http://172.17.0.1:9000  http://172.18.0.1:9000  http://127.0.0.1:9000
AccessKey: minio 
SecretKey: minio123 

Browser Access:
   http://147.75.90.109:9000  http://10.88.126.7:9000  http://172.17.0.1:9000  http://172.18.0.1:9000  http://127.0.0.1:9000

Command-line Access: https://docs.minio.io/docs/minio-client-quickstart-guide
   $ mc config host add myminio http://147.75.90.109:9000 minio minio123

Object API (Amazon S3 compatible):
   Go:         https://docs.minio.io/docs/golang-client-quickstart-guide
   Java:       https://docs.minio.io/docs/java-client-quickstart-guide
   Python:     https://docs.minio.io/docs/python-client-quickstart-guide
   JavaScript: https://docs.minio.io/docs/javascript-client-quickstart-guide
   .NET:       https://docs.minio.io/docs/dotnet-client-quickstart-guide

Drive Capacity: 411 GiB Free, 436 GiB Total
Status:         4 Online, 0 Offline. We can withstand [2] drive failure(s).



0 read tcp 147.75.90.109:9000->147.75.90.45:51454: i/o timeout
0 read tcp 147.75.90.109:9000->147.75.90.45:51452: i/o timeout
0 read tcp 147.75.90.109:9000->147.75.90.45:51448: i/o timeout
0 read tcp 147.75.90.109:9000->147.75.90.45:51450: i/o timeout
```

**Review by harshavardhana — CHANGES_REQUESTED** [review]
Keeping it :-1: with recent observation.

File: pkg/http/listener.go (hunk 14 above)
Comment (harshavardhana) [reply pkg/http/listener.go]: This error message can be about 

```fmt.Errorf("Unexpected listener type found %v, expected net.TCPListener",  l) ```

**Review by harshavardhana — APPROVED** [review]
LGTM in terms of HTTP behavior.

**Comment by krishnasrinivas** [comment]
review not complete

File: pkg/http/listener.go [hunk 16]
```diff
@@ -0,0 +1,326 @@
...
+	defer listener.mutex.Unlock()
+	if listener.doneChs == nil {
+		return syscall.EINVAL
+	}
+
+	wg := &sync.WaitGroup{}
+	for i := range listener.tcpListeners {
+		wg.Add(1)
+		go func(tcpListener *net.TCPListener, doneCh chan<- struct{}) {
+			tcpListener.Close()
```
Comment (krishnasrinivas) [inline pkg/http/listener.go]: since tcpListener.Close() is not blocking, there is no need to do this in parallel?

File: pkg/http/listener.go [hunk 17]
```diff
@@ -0,0 +1,326 @@
...
+	conn net.Conn
+	err  error
+}
+
+// httpListener - HTTP listener capable of handling multiple server addresses.
+type httpListener struct {
+	mutex                  sync.Mutex         // to guard Close() method.
+	tcpListeners           []*net.TCPListener // underlaying TCP listeners.
+	acceptCh               chan acceptResult  // channel where all TCP listeners write accepted connection.
+	doneChs                []chan struct{}    // done channels for each goroutine for TCP listeners.
```
Comment (krishnasrinivas) [inline pkg/http/listener.go]: can't we use just one doneCh for all the listeners?

File: pkg/http/listener.go [hunk 18]
```diff
@@ -0,0 +1,326 @@
...
+			// As stop signal is received, close accepted connection.
+			if result.conn != nil {
+				result.conn.Close()
+			}
+			return false
+		}
+	}
+
+	// Closure to accept single connection.
+	acceptTCP := func(tcpConn *net.TCPConn, doneCh <-chan struct{}) {
```
Comment (krishnasrinivas) [inline pkg/http/listener.go]: better rename acceptTCP to handleConn

File: pkg/http/listener.go [hunk 19]
```diff
@@ -0,0 +1,326 @@
...
+				"Received non-HTTP message from new connection %s at server %s",
+				bufconn.RemoteAddr(), bufconn.LocalAddr())
+		}
+
+		bufconn.Close()
+		return
+	}
+
+	// Closure to handle new connections till done channel is not closed.
+	handleConnection := func(tcpListener *net.TCPListener, doneCh <-chan struct{}) {
```
Comment (krishnasrinivas) [inline pkg/http/listener.go]: better rename handleConnection to handlerListener

**Review by krishnasrinivas — COMMENTED** [review]
@balamurugana Good abstractions, needs more review

File: cmd/server-main.go [hunk 20]
```diff
@@ -176,43 +180,46 @@ func serverMain(ctx *cli.Context) {
 	initNSLock(globalIsDistXL)
 
 	// Configure server.
-	handler, err := configureServerHandler(globalEndpoints)
+	var handler http.Handler
```
Comment (fwessels) [inline cmd/server-main.go]: Add comment about pulling in 'net/http' ?

File: cmd/signals.go [hunk 21]
```diff
@@ -1,5 +1,5 @@
 /*
- * Minio Client, (C) 2015 Minio, Inc.
+ * Minio Client, (C) 2015, 2016, 2017 Minio, Inc.
```
Comment (fwessels) [inline cmd/signals.go]: Minio Client --> Minio Object Storage ?

File: pkg/http/bufconn.go [hunk 22]
```diff
@@ -0,0 +1,88 @@
...
+	bufReader              *bufio.Reader // buffered reader wraps reader in net.Conn.
+	readTimeout            time.Duration // sets the read timeout in the connection.
+	writeTimeout           time.Duration // sets the write timeout in the connection.
+	updateBytesReadFunc    func(int)     // function to be called to update bytes read.
+	updateBytesWrittenFunc func(int)     // function to be called to update bytes written.
+}
+
+func (c *bufConn) setReadTimeout() {
+	if c.readTimeout != 0 {
+		c.SetReadDeadline(time.Now().Add(c.readTimeout))
```
Comment (fwessels) [inline pkg/http/bufconn.go]: Use UTCNow() in favor of time.Now() ?

File: pkg/http/bufconn.go (hunk 9 above)
Comment (fwessels) [reply pkg/http/bufconn.go]: Same as above (UTCNow()?)

File: pkg/http/bufconn.go [hunk 23]
```diff
@@ -0,0 +1,88 @@
...
+	if err == nil && c.updateBytesWrittenFunc != nil {
+		c.updateBytesWrittenFunc(n)
+	}
+
+	return n, err
+}
+
+// newBufConn - creates a new connection object wrapping net.Conn.
+func newBufConn(c net.Conn, readTimeout, writeTimeout time.Duration,
+	updateBytesReadFunc func(int), updateBytesWrittenFunc func(int)) *bufConn {
```
Comment (fwessels) [inline pkg/http/bufconn.go]: Can drop 'first' func(int)' (prototypes are the saem for updateBytesReadFunc and updateBytesWrittenFunc)

File: pkg/http/listener.go [hunk 24]
```diff
@@ -0,0 +1,326 @@
...
+			listener.errorLogFunc(errors.New("junk message"),
+				"Received non-HTTP message from new connection %s at server %s",
+				bufconn.RemoteAddr(), bufconn.LocalAddr())
+		}
+
+		bufconn.Close()
+		return
+	}
+
+	// Closure to handle new connections till done channel is not closed.
```
Comment (fwessels) [inline pkg/http/listener.go]: till -> while ? (or "until done channel is closed"?)

File: pkg/http/listener.go [hunk 25]
```diff
@@ -0,0 +1,326 @@
...
+
+// Close - closes underneath all TCP listeners.
+func (listener *httpListener) Close() (err error) {
+	listener.mutex.Lock()
+	defer listener.mutex.Unlock()
+	if listener.doneChs == nil {
+		return syscall.EINVAL
+	}
+
+	wg := &sync.WaitGroup{}
```
Comment (fwessels) [inline pkg/http/listener.go]: Why declare as a pointer here?

File: pkg/http/listener.go [hunk 26]
```diff
@@ -0,0 +1,326 @@
...
+// * listen to multiple addresses
+// * controls incoming connections only doing HTTP protocol
+func newHTTPListener(serverAddrs []string,
+	tlsConfig *tls.Config,
+	tcpKeepAliveTimeout time.Duration,
+	readTimeout time.Duration,
+	writeTimeout time.Duration,
+	updateBytesReadFunc func(int),
+	updateBytesWrittenFunc func(int),
+	errorLogFunc func(error, string, ...interface{})) (listener *httpListener, err error) {
```
Comment (fwessels) [inline pkg/http/listener.go:278]: Can reduce to a single time.Duration and  func(int) declaration.

File: pkg/http/listener_test.go [hunk 27]
```diff
@@ -0,0 +1,819 @@
...
+
+	"github.com/minio/minio-go/pkg/set"
+)
+
+var serverPort uint32 = 60000
+
+func getNextPort() string {
+	port := atomic.LoadUint32(&serverPort)
+	atomic.AddUint32(&serverPort, 1)
+	return strconv.Itoa(int(port))
```
Comment (fwessels) [inline pkg/http/listener_test.go]: AddUint32() return the new value, so line 41 can be collapsed into line 42 as follows:
```
port := atomic.AddUint32(&serverPort, 1) - 1
```
(you could prevent the -1 by initializating to 60000 - 1)

File: pkg/http/server.go [hunk 28]
```diff
@@ -0,0 +1,184 @@
...
+	DefaultWriteTimeout = 30 * time.Second
+
+	// DefaultMaxHeaderBytes - default maximum HTTP header size in bytes.
+	DefaultMaxHeaderBytes = 1 * humanize.MiByte
+)
+
+// Server - extended http.Server supports multiple addresses to serve and enhanced connection handling.
+type Server struct {
+	http.Server
+	Addrs                  []string                            // addresses on which the server listen for new connection.
```
Comment (fwessels) [inline pkg/http/server.go]: listen --> listens

File: pkg/http/server.go (hunk 12 above)
Comment (fwessels) [reply pkg/http/server.go]: If you initialize inShutdown (as uint32) to 0, then `if atomic.AddUint32(&srv.inShutdown, 1) == 1 { /* executed only once */ }` will guarantee that the contents of the if statement are executed only once.

Comment (balamurugana) [reply pkg/http/server.go]: It doesn't prevent using the mutex for this method execution lock and there is no need to have two way for  `inShutdown` ie usage of `inShutdown` with `sync.Atomic` and the function locking with mutex.

File: cmd/signals.go (hunk 21 above)
Comment (balamurugana) [reply cmd/signals.go]: Done

File: pkg/http/bufconn.go (hunk 22 above)
Comment (balamurugana) [reply pkg/http/bufconn.go]: Using time.Now().UTC(). UTCNow() can't be used from minio main package.

File: pkg/http/listener.go (hunk 24 above)
Comment (balamurugana) [reply pkg/http/listener.go]: Done

File: pkg/http/listener.go (hunk 25 above)
Comment (balamurugana) [reply pkg/http/listener.go]: Done. Fixing.

File: pkg/http/listener.go (hunk 14 above)
Comment (balamurugana) [reply pkg/http/listener.go]: Done

File: pkg/http/bufconn.go (hunk 22 above)
Comment (fwessels) [reply pkg/http/bufconn.go]: Of course...   😄

File: pkg/http/server.go (hunk 28 above)
Comment (balamurugana) [reply pkg/http/server.go]: Done

File: pkg/http/listener_test.go (hunk 27 above)
Comment (balamurugana) [reply pkg/http/listener_test.go]: Reducing one line of code, I don't see any additional benefits the change gives.  I prefer a plain/simple/straight-forward logic.

File: pkg/http/listener.go (hunk 26 above)
Comment (balamurugana) [reply pkg/http/listener.go:278]: I prefer this style for better readability.

File: pkg/http/bufconn.go (hunk 23 above)
Comment (balamurugana) [reply pkg/http/bufconn.go]: Done

File: cmd/server-main.go (hunk 20 above)
Comment (balamurugana) [reply cmd/server-main.go]: Done

File: pkg/http/listener_test.go (hunk 27 above)
Comment (fwessels) [reply pkg/http/listener_test.go]: When people see it this way, they may derive that you apparently need to load the variable separately...

File: pkg/http/bufconn.go [hunk 29]
```diff
@@ -0,0 +1,88 @@
...
+package http
+
+import (
+	"bufio"
+	"net"
+	"time"
+)
+
+// bufConn - is a generic stream-oriented network connection supporting buffered reader and read/write timeout.
+type bufConn struct {
```
Comment (harshavardhana) [inline pkg/http/bufconn.go]: Can you make this Bufconn as a publicly exported struct as discussed ?

File: pkg/http/listener_test.go (hunk 27 above)
Comment (balamurugana) [reply pkg/http/listener_test.go]: Done. Fixing.

File: pkg/http/bufconn.go (hunk 29 above)
Comment (balamurugana) [reply pkg/http/bufconn.go]: Done

File: pkg/http/server.go (hunk 12 above)
Comment (fwessels) [reply pkg/http/server.go]: Not fully understanding your comment, but pls see the following commit for what I meant: https://github.com/fwessels/minio/commit/01ff3f690c3b4a4c7799025ef16845c6a7e75e36

File: pkg/http/listener.go (hunk 17 above)
Comment (balamurugana) [reply pkg/http/listener.go]: Done

File: pkg/http/listener.go (hunk 19 above)
Comment (balamurugana) [reply pkg/http/listener.go]: Done

File: pkg/http/listener.go (hunk 18 above)
Comment (balamurugana) [reply pkg/http/listener.go]: Done

File: pkg/http/listener.go (hunk 16 above)
Comment (balamurugana) [reply pkg/http/listener.go]: Done

**Comment by harshavardhana** [comment]
Tests are failing @balamurugana

**Review by krishnasrinivas — APPROVED** [review]

**Review by harshavardhana — APPROVED** [review]

**Review by krishnasrinivas — APPROVED** [review]

**Comment by deekoder** [comment]
Krishna approved. Some reason reviewer's name disappeared from the reviewer list. Merging.

**Comment by xmovu** [comment]
Howdy,

Just to make sure, any ETA for this? I see that you've modified the code, but I'm newbie in terms of GitHub, so I'm not even sure if I redownload it from github, it'll be working.

Anyway, 2 transfers seem to work fine, but more than that cause IO errors, though there's plenty of IOPS.

How's the development so far? Can we help you testing somehow?

**Comment by harshavardhana** [comment]
> Howdy,
> 
> Just to make sure, any ETA for this? I see that you've modified the code, but I'm newbie in terms of GitHub, so I'm not even sure if I redownload it from github, it'll be working.
> 
> Anyway, 2 transfers seem to work fine, but more than that cause IO errors, though there's plenty of IOPS.
> 
> How's the development so far? Can we help you testing somehow?

@wdimd you can test the latest changes with docker `docker pull minio/minio:edge` should get your the current master .

**Comment by xmovu** [comment]
Thank you, however, I run this downloading the binaty/executable file, no docker.
Any alternative?

**Comment by harshavardhana** [comment]
You can build from `go get github.com/minio/minio`
