### PR TITLE
HealObjects should remove objects without quorum

### LINKED ISSUE #7402: Potential case of not being able to delete directories with stale files
## Expected Behavior
Able to delete the `empty` directory. 

## Current Behavior
Not able to delete `empty` directory due to stale data.

## Possible Solution
Not possible in the current design, there are potential problems in the approach which we have taken to handle directories inside XL layer which have exposed rather a corner case but an important bug. 

There is a possibility of addressing this in healing code where we can selectively purge stale entries without the quorum, but for that, we need to move to unsorted tree walk and do not rely on leaf node detection.

## Steps to Reproduce (for bugs)
Have a set of 4 disks distributed setup 

```
#!/bin/bash

export MINIO_ACCESS_KEY="minio"
export MINIO_SECRET_KEY="minio123"

rm -rf /tmp/{1..4}
for i in {01..04}; do
    minio server --address ":90${i}" http://127.0.0.1:9001/tmp/1 http://127.0.0.1:9002/tmp/2 http://127.0.0.1:9003/tmp/3 http://127.0.0.1:9004/tmp/4 &
done
```

Now copy some files 
```
~ mc cp /etc/hosts myminio/testbucket/directory/1/hosts
~ mc cp /etc/hosts myminio/testbucket/directory/2/hosts
~ mc cp /etc/hosts myminio/testbucket/directory/3/hosts
~ mc cp /etc/hosts myminio/testbucket/directory/4/hosts
```

At this moment take the first server down such as running on 9001
and delete prefix `1/`

```
~ mc rm -r --force myminio/testbucket/prefix/1/
```

Delete is successful but NOTE we have a stale entry on the server running at 9001 

Now proceed to bring the 9001 back up and now take down 9002, delete prefix `2/`

```
~ mc rm -r --force myminio/testbucket/directory/2/
```

Delete is again successful but NOTE we have a stale entry on the server running at 9002 

Now repeat the steps as mentioned. Once all of this done we have sufficiently removed all objects in quorum on all servers but have left stale entries for each prefix on each of the servers. 

Now when you do 
```
~ mc ls myminio/testbucket/directory/
```

There are no entries but this directory is persistent and visible. Try to delete this directory.

```
~ mc rm -r --force myminio/testbucket/directory/
```

`mc` says it is trying to delete the directory, but it cannot because of the following line of code on server.

```
        var isObjectDir = hasSuffix(object, slashSeparator)

        if isObjectDir && !xl.isObjectDir(bucket, object) {
                return toObjectErr(errFileNotFound, bucket, object)
        }
```

Here 
```
xl.isObjectDir(bucket, object) 
```

Always returns `false` because all the directories return non-empty, that basically invalidates the function to indicate that directory is non-empty so it is not an "actual" directory on MinIO.  Unless xl.isObjectDir() returns true.

## Context
Stale files are not deleted as we thought previously due to a corner case issue, as reproduced here. 

## Regression
Not really but a design flaw from what it looks like. I have tried various different ways to fix this issue but it is not possible to cleanly address it unless we have native directory support.

## Your Environment
All releases of MinIO have this problem on all platforms.

### PR DESCRIPTION
**Pull request by harshavardhana**
## Description
HealObjects should remove objects without quorum

## Motivation and Context
This PR adds a way to list objects without quorum
such that they can purged by `mc admin heal --remove`

Fixes #7402 

## Regression
No

## How Has This Been Tested?
Reproducing the issue as mentioned in issue #7402 and then using `mc admin heal --remove` to remove these stale entries. 

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added unit tests to cover my changes.
- [ ] I have added/updated functional tests in [mint](https://github.com/minio/mint). (If yes, add `mint` PR # here: )
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by minio-ops** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-compression-xl.sh | :heavy_check_mark: |
| mint-xl.sh | :heavy_check_mark: |
| mint-compression-dist-xl.sh | :heavy_check_mark: |
| mint-worm.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-dist-xl.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :x: [more...](#71756749-18ed-4869-827c-fe20632966f6) |
| mint-compression-fs.sh | :x: [more...](#1027b25c-c413-4d6a-9088-a264206bb455) |
<a name="1027b25c-c413-4d6a-9088-a264206bb455"></a>
### 7407-c3709cb/mint-compression-fs.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.54:30976
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 1e79e0b41d90:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 0 seconds
(2/14) Running aws-sdk-java tests ... done in 1 seconds
(3/14) Running aws-sdk-php tests ... done in 42 seconds
(4/14) Running aws-sdk-ruby tests ... done in 2 seconds
(5/14) Running awscli tests ... done in 1 minutes and 48 seconds
(6/14) Running healthcheck tests ... done in 0 seconds
(7/14) Running mc tests ... done in 25 seconds
(8/14) Running minio-dotnet tests ... done in 25 seconds
(9/14) Running minio-go tests ... done in 26 seconds
(10/14) Running minio-java tests ... done in 52 seconds
(11/14) Running minio-js tests ... done in 36 seconds
(12/14) Running minio-py tests ... FAILED in 1 minutes and 52 seconds
{
  "message": "AccessDenied: message: Access Denied",
  "args": {
    "bucket_name": "minio-py-test-f7979290-a38c-458d-8931-b85a02cf6e1c",
    "object_name": "b59f630b-7aa4-428a-b21c-0d5a9095ee79"
  },
  "name": "minio-py:test_presigned_get_object_expiry_5sec",
  "duration": 57,
  "error": "Traceback (most recent call last):\n  File \"/mint/run/core/minio-py/tests.py\", line 1220, in test_presigned_get_object_expiry_5sec\n    object_name).get_exception()\nminio.error.AccessDenied: AccessDenied: message: Access Denied\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"/mint/run/core/minio-py/tests.py\", line 1885, in main\n    test_presigned_get_object_expiry_5sec(client, log_output)\n  File \"/mint/run/core/minio-py/tests.py\", line 1228, in test_presigned_get_object_expiry_5sec\n    raise Exception(err)\nException: AccessDenied: message: Access Denied\n",
  "function": "presigned_get_object(bucket_name, object_name, expires, response_headers, request_date)",
  "status": "FAIL"
}

Executed 11 out of 14 tests successfully.
```
<a name="71756749-18ed-4869-827c-fe20632966f6"></a>
### 7407-c3709cb/mint-large-bucket.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.53:31908
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 492353e1344a:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... FAILED in 1 seconds
{
  "alert": "",
  "args": {
    "bucketName": "aws-sdk-go-test-e1putn93yqcylz",
    "expiry": 60000000000,
    "objectName": "presignedTest"
  },
  "duration": 328,
  "error": "RequestError: send request failed\ncaused by: Put http://72.28.97.53:31908/aws-sdk-go-test-e1putn93yqcylz: dial tcp 72.28.97.53:31908: connect: connection refused",
  "function": "PresignedPut",
  "message": "AWS SDK Go CreateBucket Failed",
  "name": "aws-sdk-go",
  "status": "FAIL"
}

Executed 0 out of 14 tests successfully.
```

**Comment by harshavardhana** [comment]
ping @vadmeste @kannappanr

**Review by kannappanr — DISMISSED** [review]
LGTM. Tested

**Comment by harshavardhana** [comment]
Actually moving this to blocked, for now, there are some bugs which I found which deletes proper data as well. @kannappanr @vadmeste

**Comment by harshavardhana** [comment]
Removing blocked fixed this properly now @kannappanr @vadmeste - HealObjects is now able to handle all situations, related to healing corrupt objects.

**Comment by minio-ops** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-xl.sh | :heavy_check_mark: |
| mint-compression-fs.sh | :heavy_check_mark: |
| mint-worm.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-compression-xl.sh | :x: [more...](#0571bd8c-75df-49c4-a3af-98d000fb24f6) |
| mint-large-bucket.sh | :x: [more...](#1aafb4ea-676c-4f24-a0ee-97917759c84f) |
| mint-compression-dist-xl.sh | :x: [more...](#dac23a94-8e35-426e-a51e-97f87a534247) |
| mint-dist-xl.sh | :x: [more...](#7b760c85-fa81-4e3b-a4e5-b7515e760a8e) |
<a name="dac23a94-8e35-426e-a51e-97f87a534247"></a>
### 7407-7c0613f/mint-compression-dist-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.52:30773
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 01267481a09f:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... FAILED in 0 seconds
{
  "alert": "",
  "args": {
    "bucketName": "aws-sdk-go-test-sgleeytrykkbdo",
    "expiry": 60000000000,
    "objectName": "presignedTest"
  },
  "duration": 340,
  "error": "RequestError: send request failed\ncaused by: Put http://72.28.97.52:30773/aws-sdk-go-test-sgleeytrykkbdo: dial tcp 72.28.97.52:30773: connect: connection refused",
  "function": "PresignedPut",
  "message": "AWS SDK Go CreateBucket Failed",
  "name": "aws-sdk-go",
  "status": "FAIL"
}

Executed 0 out of 14 tests successfully.
```
<a name="0571bd8c-75df-49c4-a3af-98d000fb24f6"></a>
### 7407-7c0613f/mint-compression-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.55:31050
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 5cac07d0e20f:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 0 seconds
(2/14) Running aws-sdk-java tests ... done in 1 seconds
(3/14) Running aws-sdk-php tests ... done in 44 seconds
(4/14) Running aws-sdk-ruby tests ... done in 3 seconds
(5/14) Running awscli tests ... done in 1 minutes and 57 seconds
(6/14) Running healthcheck tests ... done in 0 seconds
(7/14) Running mc tests ... done in 21 seconds
(8/14) Running minio-dotnet tests ... done in 49 seconds
(9/14) Running minio-go tests ... done in 1 minutes and 11 seconds
(10/14) Running minio-java tests ... done in 3 minutes and 10 seconds
(11/14) Running minio-js tests ... done in 50 seconds
(12/14) Running minio-py tests ... FAILED in 6 minutes and 43 seconds
{
  "args": {
    "bucket_name": "minio-py-test-3ee8558d-192c-455e-ae70-b31b4316df3d",
    "object_name": "17be2157-05e5-4083-88e9-c818796200f3"
  },
  "error": "Traceback (most recent call last):\n  File \"/mint/run/core/minio-py/tests.py\", line 1220, in test_presigned_get_object_expiry_5sec\n    object_name).get_exception()\nminio.error.AccessDenied: AccessDenied: message: Access Denied\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"/mint/run/core/minio-py/tests.py\", line 1885, in main\n    test_presigned_get_object_expiry_5sec(client, log_output)\n  File \"/mint/run/core/minio-py/tests.py\", line 1228, in test_presigned_get_object_expiry_5sec\n    raise Exception(err)\nException: AccessDenied: message: Access Denied\n",
  "status": "FAIL",
  "name": "minio-py:test_presigned_get_object_expiry_5sec",
  "message": "AccessDenied: message: Access Denied",
  "function": "presigned_get_object(bucket_name, object_name, expires, response_headers, request_date)",
  "duration": 107
}

Executed 11 out of 14 tests successfully.
```
<a name="7b760c85-fa81-4e3b-a4e5-b7515e760a8e"></a>
### 7407-7c0613f/mint-dist-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.54:31856
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 9986f06af7f8:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... FAILED in 0 seconds
{
  "alert": "",
  "args": {
    "bucketName": "aws-sdk-go-test-z3ksfvpdfydzpv",
    "expiry": 60000000000,
    "objectName": "presignedTest"
  },
  "duration": 346,
  "error": "RequestError: send request failed\ncaused by: Put http://72.28.97.54:31856/aws-sdk-go-test-z3ksfvpdfydzpv: dial tcp 72.28.97.54:31856: connect: connection refused",
  "function": "PresignedPut",
  "message": "AWS SDK Go CreateBucket Failed",
  "name": "aws-sdk-go",
  "status": "FAIL"
}

Executed 0 out of 14 tests successfully.
```
<a name="1aafb4ea-676c-4f24-a0ee-97917759c84f"></a>
### 7407-7c0613f/mint-large-bucket.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.51:31812
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp e281044b50ee:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... FAILED in 0 seconds
{
  "alert": "",
  "args": {
    "bucketName": "aws-sdk-go-test-vuwai33xjjnebk",
    "expiry": 60000000000,
    "objectName": "presignedTest"
  },
  "duration": 298,
  "error": "RequestError: send request failed\ncaused by: Put http://72.28.97.51:31812/aws-sdk-go-test-vuwai33xjjnebk: dial tcp 72.28.97.51:31812: connect: connection refused",
  "function": "PresignedPut",
  "message": "AWS SDK Go CreateBucket Failed",
  "name": "aws-sdk-go",
  "status": "FAIL"
}

Executed 0 out of 14 tests successfully.
```

**Comment by vadmeste** [comment]
@harshavardhana can you add a quick unit test for this ? in cmd/xl-v1-healing_test.go, you can follow TestHealObjectXL..

**Comment by minio-ops** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-compression-xl.sh | :heavy_check_mark: |
| mint-xl.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-compression-fs.sh | :heavy_check_mark: |
| mint-worm.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-dist-xl.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-compression-dist-xl.sh | :x: [more...](#0a1229f4-157a-4062-bbb5-eeef0991efcc) |
<a name="0a1229f4-157a-4062-bbb5-eeef0991efcc"></a>
### 7407-7604a4c/mint-compression-dist-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.54:31230
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp c58020c538f7:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 2 minutes and 0 seconds
(2/14) Running aws-sdk-java tests ... done in 1 seconds
(3/14) Running aws-sdk-php tests ... done in 50 seconds
(4/14) Running aws-sdk-ruby tests ... done in 18 seconds
(5/14) Running awscli tests ... done in 2 minutes and 40 seconds
(6/14) Running healthcheck tests ... done in 0 seconds
(7/14) Running mc tests ... done in 31 seconds
(8/14) Running minio-dotnet tests ... done in 42 seconds
(9/14) Running minio-go tests ... done in 1 minutes and 39 seconds
(10/14) Running minio-java tests ... done in 3 minutes and 47 seconds
(11/14) Running minio-js tests ... done in 42 seconds
(12/14) Running minio-py tests ... FAILED in 9 minutes and 3 seconds
{
  "message": "AccessDenied: message: Access Denied",
  "error": "Traceback (most recent call last):\n  File \"/mint/run/core/minio-py/tests.py\", line 1220, in test_presigned_get_object_expiry_5sec\n    object_name).get_exception()\nminio.error.AccessDenied: AccessDenied: message: Access Denied\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"/mint/run/core/minio-py/tests.py\", line 1885, in main\n    test_presigned_get_object_expiry_5sec(client, log_output)\n  File \"/mint/run/core/minio-py/tests.py\", line 1228, in test_presigned_get_object_expiry_5sec\n    raise Exception(err)\nException: AccessDenied: message: Access Denied\n",
  "function": "presigned_get_object(bucket_name, object_name, expires, response_headers, request_date)",
  "duration": 483,
  "name": "minio-py:test_presigned_get_object_expiry_5sec",
  "args": {
    "bucket_name": "minio-py-test-aa97dde4-3ab8-4f1c-9382-53777d579bc5",
    "object_name": "7ba96e7f-bcb2-48c1-9ef7-d3350dac7e54"
  },
  "status": "FAIL"
}

Executed 11 out of 14 tests successfully.
```

**Comment by minio-ops** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-compression-xl.sh | :heavy_check_mark: |
| mint-xl.sh | :heavy_check_mark: |
| mint-compression-dist-xl.sh | :heavy_check_mark: |
| mint-compression-fs.sh | :heavy_check_mark: |
| mint-worm.sh | :heavy_check_mark: |
| mint-dist-xl.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :x: [more...](#3b107e2f-c901-4fa0-b2bd-107bbdd64c18) |
| mint-fs.sh | :x: [more...](#d32db461-f3ed-4289-8f28-7bf6321c53b0) |
<a name="3b107e2f-c901-4fa0-b2bd-107bbdd64c18"></a>
### 7407-98e46ad/mint-large-bucket.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.55:32042
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 14237620c803:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... FAILED in 1 seconds
{
  "alert": "",
  "args": {
    "bucketName": "aws-sdk-go-test-gtyblvh0lg0fpd",
    "expiry": 60000000000,
    "objectName": "presignedTest"
  },
  "duration": 338,
  "error": "RequestError: send request failed\ncaused by: Put http://72.28.97.55:32042/aws-sdk-go-test-gtyblvh0lg0fpd: dial tcp 72.28.97.55:32042: connect: connection refused",
  "function": "PresignedPut",
  "message": "AWS SDK Go CreateBucket Failed",
  "name": "aws-sdk-go",
  "status": "FAIL"
}

Executed 0 out of 14 tests successfully.
```
<a name="d32db461-f3ed-4289-8f28-7bf6321c53b0"></a>
### 7407-98e46ad/mint-fs.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.52:31556
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 6a185439997e:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 0 seconds
(2/14) Running aws-sdk-java tests ... done in 1 seconds
(3/14) Running aws-sdk-php tests ... done in 51 seconds
(4/14) Running aws-sdk-ruby tests ... done in 4 seconds
(5/14) Running awscli tests ... done in 1 minutes and 51 seconds
(6/14) Running healthcheck tests ... done in 0 seconds
(7/14) Running mc tests ... done in 22 seconds
(8/14) Running minio-dotnet tests ... done in 29 seconds
(9/14) Running minio-go tests ... done in 56 seconds
(10/14) Running minio-java tests ... done in 4 minutes and 54 seconds
(11/14) Running minio-js tests ... done in 1 minutes and 9 seconds
(12/14) Running minio-py tests ... FAILED in 6 minutes and 0 seconds
{
  "message": "AccessDenied: message: Access Denied",
  "duration": 71,
  "args": {
    "bucket_name": "minio-py-test-6099dbc2-06af-4717-907e-e64f34168653",
    "object_name": "725549d5-9d37-4ea8-9922-54fa0d80ef02"
  },
  "error": "Traceback (most recent call last):\n  File \"/mint/run/core/minio-py/tests.py\", line 1220, in test_presigned_get_object_expiry_5sec\n    object_name).get_exception()\nminio.error.AccessDenied: AccessDenied: message: Access Denied\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"/mint/run/core/minio-py/tests.py\", line 1885, in main\n    test_presigned_get_object_expiry_5sec(client, log_output)\n  File \"/mint/run/core/minio-py/tests.py\", line 1228, in test_presigned_get_object_expiry_5sec\n    raise Exception(err)\nException: AccessDenied: message: Access Denied\n",
  "name": "minio-py:test_presigned_get_object_expiry_5sec",
  "status": "FAIL",
  "function": "presigned_get_object(bucket_name, object_name, expires, response_headers, request_date)"
}

Executed 11 out of 14 tests successfully.
```

**Comment by minio-ops** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-compression-xl.sh | :heavy_check_mark: |
| mint-xl.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-compression-fs.sh | :heavy_check_mark: |
| mint-worm.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-dist-xl.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-compression-dist-xl.sh | :x: [more...](#5b7e3247-6f8a-4297-9093-db1b10d2dfca) |
<a name="5b7e3247-6f8a-4297-9093-db1b10d2dfca"></a>
### 7407-abae7b8/mint-compression-dist-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.60:30458
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp b8ed266720e3:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... FAILED in 0 seconds
{
  "alert": "",
  "args": {
    "bucketName": "aws-sdk-go-test-odqw0s49mmbjny",
    "expiry": 60000000000,
    "objectName": "presignedTest"
  },
  "duration": 345,
  "error": "RequestError: send request failed\ncaused by: Put http://72.28.97.60:30458/aws-sdk-go-test-odqw0s49mmbjny: dial tcp 72.28.97.60:30458: connect: connection refused",
  "function": "PresignedPut",
  "message": "AWS SDK Go CreateBucket Failed",
  "name": "aws-sdk-go",
  "status": "FAIL"
}

Executed 0 out of 14 tests successfully.
```

**Comment by harshavardhana** [comment]
> @harshavardhana can you add a quick unit test for this ? in cmd/xl-v1-healing_test.go, you can follow TestHealObjectXL..

Sure let me add..

**Comment by harshavardhana** [comment]
Added a unit test as well @vadmeste @kannappanr - PTAL , the user has already confirmed this to be working.

**Comment by minio-ops** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-compression-xl.sh | :heavy_check_mark: |
| mint-xl.sh | :heavy_check_mark: |
| mint-compression-fs.sh | :heavy_check_mark: |
| mint-worm.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-dist-xl.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :x: [more...](#118fb5df-1705-4efc-b6e4-05cbc4da5e3b) |
| mint-compression-dist-xl.sh | :x: [more...](#959bf521-eca0-4f9e-918e-a0c95d59c99f) |
<a name="118fb5df-1705-4efc-b6e4-05cbc4da5e3b"></a>
### 7407-d9f943e/mint-large-bucket.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.53:30507
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 3a156c696dc5:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... FAILED in 0 seconds
{
  "alert": "",
  "args": {
    "bucketName": "aws-sdk-go-test-3wmmqv1qp6thec",
    "expiry": 60000000000,
    "objectName": "presignedTest"
  },
  "duration": 229,
  "error": "RequestError: send request failed\ncaused by: Put http://72.28.97.53:30507/aws-sdk-go-test-3wmmqv1qp6thec: dial tcp 72.28.97.53:30507: connect: connection refused",
  "function": "PresignedPut",
  "message": "AWS SDK Go CreateBucket Failed",
  "name": "aws-sdk-go",
  "status": "FAIL"
}

Executed 0 out of 14 tests successfully.
```
<a name="959bf521-eca0-4f9e-918e-a0c95d59c99f"></a>
### 7407-d9f943e/mint-compression-dist-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.56:32748
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 3edd7f5f3d15:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 0 seconds
(2/14) Running aws-sdk-java tests ... FAILED in 1 seconds
com.amazonaws.services.s3.model.AmazonS3Exception: Server not initialized, please try again. (Service: Amazon S3; Status Code: 503; Error Code: XMinioServerNotInitialized; Request ID: 158F606A6963B1EB; S3 Extended Request ID: 158F606A6963B1EB), S3 Extended Request ID: 158F606A6963B1EB
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.handleErrorResponse(AmazonHttpClient.java:1630)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeOneRequest(AmazonHttpClient.java:1302)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeHelper(AmazonHttpClient.java:1056)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.doExecute(AmazonHttpClient.java:743)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeWithTimer(AmazonHttpClient.java:717)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.execute(AmazonHttpClient.java:699)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.access$500(AmazonHttpClient.java:667)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutionBuilderImpl.execute(AmazonHttpClient.java:649)
	at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:513)
	at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:4330)
	at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:4277)
	at com.amazonaws.services.s3.AmazonS3Client.createBucket(AmazonS3Client.java:1025)
	at io.minio.awssdk.tests.FunctionalTests.initTests(Unknown Source)
	at io.minio.awssdk.tests.FunctionalTests.main(Unknown Source)

Executed 1 out of 14 tests successfully.
```

File: cmd/posix.go [hunk 1]
```diff
@@ -1358,9 +1358,18 @@ func (s *posix) RenameFile(srcVolume, srcPath, dstVolume, dstPath string) (err e
 		if err == nil && !isDirEmpty(dstFilePath) {
 			return errFileAccessDenied
 		}
-		if !os.IsNotExist(err) {
+		if err != nil && !os.IsNotExist(err) {
 			return err
 		}
+		// Empty destination remove it before rename.
+		if isDirEmpty(dstFilePath) {
```
Comment (vadmeste) [inline cmd/posix.go:1365]: Can you say more about this change ? what particular case does it fix ?

Comment (harshavardhana) [reply cmd/posix.go:1365]: It fixes an important issue #7421, this is perhaps a really old bug. I can't write more because it's already written above when srcIsDir is true destination should be empty.

**Comment by minio-ops** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-compression-xl.sh | :heavy_check_mark: |
| mint-xl.sh | :heavy_check_mark: |
| mint-compression-dist-xl.sh | :heavy_check_mark: |
| mint-compression-fs.sh | :heavy_check_mark: |
| mint-worm.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :x: [more...](#0dbe6759-47e3-4aa1-bd29-10d694c534aa) |
| mint-dist-xl.sh | :x: [more...](#d4fd39d5-c8f0-486c-adf3-699294c58818) |
<a name="0dbe6759-47e3-4aa1-bd29-10d694c534aa"></a>
### 7407-c84091d/mint-large-bucket.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.54:30815
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp a0d3a91ba65b:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... FAILED in 1 seconds
{
  "alert": "",
  "args": {
    "bucketName": "aws-sdk-go-test-0doqyv3mvf6yzz",
    "expiry": 60000000000,
    "objectName": "presignedTest"
  },
  "duration": 279,
  "error": "RequestError: send request failed\ncaused by: Put http://72.28.97.54:30815/aws-sdk-go-test-0doqyv3mvf6yzz: dial tcp 72.28.97.54:30815: connect: connection refused",
  "function": "PresignedPut",
  "message": "AWS SDK Go CreateBucket Failed",
  "name": "aws-sdk-go",
  "status": "FAIL"
}

Executed 0 out of 14 tests successfully.
```
<a name="d4fd39d5-c8f0-486c-adf3-699294c58818"></a>
### 7407-c84091d/mint-dist-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.57:30657
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 8b10a8866c9a:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 3 seconds
(2/14) Running aws-sdk-java tests ... done in 2 seconds
(3/14) Running aws-sdk-php tests ... done in 45 seconds
(4/14) Running aws-sdk-ruby tests ... done in 3 seconds
(5/14) Running awscli tests ... done in 2 minutes and 32 seconds
(6/14) Running healthcheck tests ... done in 0 seconds
(7/14) Running mc tests ... done in 27 seconds
(8/14) Running minio-dotnet tests ... done in 35 seconds
(9/14) Running minio-go tests ... done in 58 seconds
(10/14) Running minio-java tests ... done in 1 minutes and 53 seconds
(11/14) Running minio-js tests ... done in 38 seconds
(12/14) Running minio-py tests ... FAILED in 3 minutes and 12 seconds
{
  "name": "minio-py:test_presigned_get_object_expiry_5sec",
  "message": "AccessDenied: message: Access Denied",
  "function": "presigned_get_object(bucket_name, object_name, expires, response_headers, request_date)",
  "args": {
    "bucket_name": "minio-py-test-7b9b4775-042a-4e14-95b9-6b55c0e55bb9",
    "object_name": "86d216f9-ac55-4ac3-9285-5a4c3d7587e7"
  },
  "duration": 108,
  "status": "FAIL",
  "error": "Traceback (most recent call last):\n  File \"/mint/run/core/minio-py/tests.py\", line 1220, in test_presigned_get_object_expiry_5sec\n    object_name).get_exception()\nminio.error.AccessDenied: AccessDenied: message: Access Denied\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"/mint/run/core/minio-py/tests.py\", line 1885, in main\n    test_presigned_get_object_expiry_5sec(client, log_output)\n  File \"/mint/run/core/minio-py/tests.py\", line 1228, in test_presigned_get_object_expiry_5sec\n    raise Exception(err)\nException: AccessDenied: message: Access Denied\n"
}

Executed 11 out of 14 tests successfully.
```

File: cmd/xl-v1-healing.go [hunk 2]
```diff
@@ -599,6 +603,18 @@ func (xl xlObjects) isObjectDangling(metaArr []xlMetaV1, errs []error) (validMet
 			corruptedXLJSON++
 		}
 	}
+	var notFoundParts int
+	for i, readErr := range dataErrs {
+		// Only count part errors, if the error is not
+		// same as xl.json error. This is to avoid
+		// double counting when both parts and xl.json
+		// are not available.
+		if errs[i] != dataErrs[i] {
```
Comment (kannappanr) [inline cmd/xl-v1-healing.go:612]: Is `if errs[i] != dataErrs[i] {` same as `if errs[i] != readErr {`

Comment (harshavardhana) [reply cmd/xl-v1-healing.go:612]: Its to convey a message @kannappanr to be more readable, I would perhaps deprecate `readErr`

Comment (kannappanr) [reply cmd/xl-v1-healing.go:612]: Now, it looks cleaner to me.

**Comment by minio-ops** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-compression-xl.sh | :heavy_check_mark: |
| mint-xl.sh | :heavy_check_mark: |
| mint-compression-dist-xl.sh | :heavy_check_mark: |
| mint-compression-fs.sh | :heavy_check_mark: |
| mint-worm.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-dist-xl.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :x: [more...](#ff408497-e071-43a2-a04b-1de9d744e25f) |
<a name="ff408497-e071-43a2-a04b-1de9d744e25f"></a>
### 7407-99b746f/mint-large-bucket.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.53:31428
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 1db360cf897b:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... FAILED in 0 seconds
{
  "alert": "",
  "args": {
    "bucketName": "aws-sdk-go-test-kt1sdpimz3wwjo",
    "expiry": 60000000000,
    "objectName": "presignedTest"
  },
  "duration": 377,
  "error": "RequestError: send request failed\ncaused by: Put http://72.28.97.53:31428/aws-sdk-go-test-kt1sdpimz3wwjo: dial tcp 72.28.97.53:31428: connect: connection refused",
  "function": "PresignedPut",
  "message": "AWS SDK Go CreateBucket Failed",
  "name": "aws-sdk-go",
  "status": "FAIL"
}

Executed 0 out of 14 tests successfully.
```

**Comment by minio-ops** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-compression-xl.sh | :heavy_check_mark: |
| mint-xl.sh | :heavy_check_mark: |
| mint-compression-dist-xl.sh | :heavy_check_mark: |
| mint-compression-fs.sh | :heavy_check_mark: |
| mint-worm.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-dist-xl.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :x: [more...](#2083a1e4-4450-4858-b40d-ab4c9eb1f566) |
<a name="2083a1e4-4450-4858-b40d-ab4c9eb1f566"></a>
### 7407-26a2bdd/mint-large-bucket.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.51:31762
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 219d62f0ee27:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... FAILED in 0 seconds
{
  "alert": "",
  "args": {
    "bucketName": "aws-sdk-go-test-vj4lwin4hb9spq",
    "expiry": 60000000000,
    "objectName": "presignedTest"
  },
  "duration": 279,
  "error": "RequestError: send request failed\ncaused by: Put http://72.28.97.51:31762/aws-sdk-go-test-vj4lwin4hb9spq: dial tcp 72.28.97.51:31762: connect: connection refused",
  "function": "PresignedPut",
  "message": "AWS SDK Go CreateBucket Failed",
  "name": "aws-sdk-go",
  "status": "FAIL"
}

Executed 0 out of 14 tests successfully.
```

**Review by vadmeste — APPROVED** [review]
LGTM & tested

**Review by kannappanr — APPROVED** [review]
LGTM
