### PR TITLE
Remove site replication config if it succeeded locally

### LINKED ISSUE #16265: Support removing a site from the replication config even if that site is down
## Expected Behavior

Related to discussion in https://github.com/minio/docs/issues/677

The current site replication behavior has a logical progression that makes recovery complicated. 
Specifically:

1. Removing a site requires removing the entire replication config via `mc admin replicate remove --force --all`. This allows removing a site that is offline/unhealthy, since we otherwise try to update the entire replication config across all sites.
2. Since site replication requires that no more than one site have data, this means you would have to wipe all other remaining sites before rebuilding the configuration
3. This complicates recovery by substantially increasing the amount of data to re-replicate

In discussion with @poornas this is an oversight that resulted from trying to avoid a situation similar to the following:

1. Site C goes down and is not expected to come back online
2. Admin removes Site C from the replication configuration
3. Site C somehow comes back up
4. Site A, B, D have their replication config excluding Site C. SiteC still thinks it's a part of the full set

The above would allow for Site C to replicate data to A/B/D and result in an undesired replication state, until someone reset Site C's setup.

Our docs already warn to completely wipe the unhealthy site before bringing it back up, *but* a user could still do this by accident - thus the current logic. However, in discussion with @poornas , it is more important to avoid having to re-replicate a large amount of data to multiple sites in more complex replication configurations. 

## Current Behavior

Removing a site requires completely resetting the site replication configuration, which also requires wiping all but one site in the config as per the existing site replication configuration rules.

## Possible Solution

we need to support syntax similar to the following:

```shell
$> mc admin replicate remove --force --dangerous HEALTHY_SITE_ALIAS UNHEALTHY_SITE_ALIAS
```

Running without `--dangerous` should output something similar to the following if the target site is offline or unhealthy:

```
WARNING: UNHEALTHY_SITE_ALIAS is offline or unreachable.
Include the --dangerous flag to force remove UNHEALTHY_SITE_ALIAS from the existing configuration.

Using this flag does NOT update UNHEALTHY_SITE_ALIAS, and if that deployment comes back online it can continue replicating as per the original site replication configuration.
You MUST completely wipe the UNHEALTHY_SITE_ALIAS deployment before bringing it back online, if ever, to avoid an unstable replication state.
```

If the site is online, then there's no real issue with removing it, since we can maintain a consistent replication state.

## Steps to Reproduce (for bugs)

See linked DOCS issue 

## Context

This may affect any user with multi-site replication configurations who needs to perform site recovery.

## Regression

No

## Your Environment

See linked DOCS issue

### PR DESCRIPTION
**Pull request by poornas**
In the event of failure to remove on one/more peers, the site replication removal command should be re-issued on peer that still has the site replication configuration.

Also adding validations to ensure requestor of site removal is still a participant in site replication

Fixes: #16265

## Motivation and Context
This PR allows removal of site from site replication even if one/more peers are offline or returned errors during removal. 

## How to test this PR?

1. configure site replication b/w 3 minio clusters A, B, C
2. take down C, then do `mc admin replicate remove A C --force` . Both A & B site config should drop C from list of peers
3. Bring back C, `mc admin replicate remove C X` where X is A,B or C. This should clear the site config in C without affecting the old peers A and B

## Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Optimization (provides speedup with no functional changes)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [ ] Fixes a regression (If yes, please add `commit-id` or `PR #` here)
- [ ] Unit tests added/updated
- [ ] Internal documentation updated
- [ ] Create a documentation update request [here](https://github.com/minio/docs/issues/new?label=doc-change,title=Doc+Updated+Needed+For+PR+github.com%2fminio%2fminio%2fpull%2fNNNNN)

### CODE REVIEW

**Comment by minio-trusted** [comment]
```
Error running mint automation
+ mkdir -p 16279-d562491/gopath/src/github.com/minio
+ git -C 16279-d562491/gopath/src/github.com/minio clone --quiet https://github.com/minio/minio.git
+ git -C 16279-d562491/gopath/src/github.com/minio/minio remote add minio https://github.com/minio/minio.git
+ git -C 16279-d562491/gopath/src/github.com/minio/minio fetch --quiet minio pull/16279/head:pr16279
+ git -C 16279-d562491/gopath/src/github.com/minio/minio checkout --quiet pr16279
+ GO111MODULE=on
+ GOPATH=/home/mint-auto/mint-auto/16279-d562491/gopath
+ make -C 16279-d562491/gopath/src/github.com/minio/minio --quiet
go: downloading cloud.google.com/go/storage v1.26.0
go: downloading github.com/djherbis/atime v1.1.0
go: downloading github.com/bcicen/jstream v1.0.1
go: downloading github.com/dustin/go-humanize v1.0.0
go: downloading github.com/Azure/azure-storage-blob-go v0.15.0
go: downloading github.com/minio/dperf v0.4.2
go: downloading github.com/minio/highwayhash v1.0.2
go: downloading github.com/minio/kes v0.22.0
go: downloading github.com/miekg/dns v1.1.50
go: downloading github.com/minio/minio-go/v7 v7.0.44
go: downloading github.com/bits-and-blooms/bloom/v3 v3.3.1
go: downloading github.com/klauspost/compress v1.15.12
go: downloading github.com/klauspost/pgzip v1.2.5
go: downloading github.com/cespare/xxhash/v2 v2.1.2
go: downloading github.com/coreos/go-oidc v2.2.1+incompatible
go: downloading github.com/minio/pkg v1.5.8
go: downloading github.com/minio/console v0.22.2
go: downloading github.com/cheggaaa/pb v1.0.29
go: downloading github.com/fatih/color v1.13.0
go: downloading github.com/klauspost/filepathx v1.1.1
go: downloading github.com/minio/sio v0.3.0
go: downloading github.com/minio/xxml v0.0.3
go: downloading github.com/klauspost/readahead v1.4.0
go: downloading github.com/minio/zipindex v0.3.0
go: downloading github.com/minio/selfupdate v0.5.0
go: downloading github.com/minio/cli v1.24.0
go: downloading github.com/philhofer/fwd v1.1.2-0.20210722190033-5c56ac6d0bb9
go: downloading github.com/lithammer/shortuuid/v4 v4.0.0
go: downloading github.com/gorilla/mux v1.8.0
go: downloading github.com/pierrec/lz4 v2.6.1+incompatible
go: downloading github.com/go-openapi/loads v0.21.2
go: downloading github.com/json-iterator/go v1.1.12
go: downloading github.com/felixge/fgprof v0.9.3
go: downloading github.com/klauspost/reedsolomon v1.11.3
go: downloading github.com/dchest/siphash v1.2.3
go: downloading github.com/google/uuid v1.3.0
go: downloading github.com/inconshreveable/mousetrap v1.0.1
go: downloading github.com/zeebo/xxh3 v1.0.2
go: downloading google.golang.org/api v0.98.0
go: downloading github.com/golang-jwt/jwt/v4 v4.4.2
go: downloading golang.org/x/oauth2 v0.2.0
go: downloading github.com/hashicorp/golang-lru v0.5.4
go: downloading golang.org/x/sys v0.2.0
go: downloading go.etcd.io/etcd/api/v3 v3.5.5
go: downloading golang.org/x/crypto v0.3.0
go: downloading go.etcd.io/etcd/client/v3 v3.5.5
go: downloading github.com/rs/dnscache v0.0.0-20211102005908-e0241e321417
go: downloading github.com/tinylib/msgp v1.1.7-0.20220719154719-f3635b96e483
go: downloading github.com/prometheus/client_golang v1.13.0
go: downloading github.com/shirou/gopsutil/v3 v3.22.9
go: downloading github.com/valyala/bytebufferpool v1.0.0
go: downloading github.com/secure-io/sio-go v0.3.1
go: downloading github.com/prometheus/client_model v0.3.0
go: downloading github.com/rs/cors v1.8.2
go: downloading github.com/cosnicolaou/pbzip2 v1.0.1
go: downloading go.uber.org/atomic v1.10.0
go: downloading github.com/prometheus/common v0.37.0
go: downloading github.com/prometheus/procfs v0.8.0
go: downloading github.com/mitchellh/go-homedir v1.1.0
go: downloading gopkg.in/yaml.v2 v2.4.0
go: downloading go.uber.org/zap v1.23.0
go: downloading github.com/coredns/coredns v1.9.4
go: downloading github.com/beevik/ntp v0.3.0
go: downloading github.com/go-ldap/ldap/v3 v3.4.4
go: downloading golang.org/x/time v0.0.0-20220722155302-e5dcc9cfc0b9
go: downloading github.com/minio/sha256-simd v1.0.0
go: downloading github.com/buger/jsonparser v1.1.1
go: downloading github.com/Shopify/sarama v1.36.0
go: downloading github.com/eclipse/paho.mqtt.golang v1.4.1
go: downloading github.com/ncw/directio v1.0.5
go: downloading github.com/elastic/go-elasticsearch/v7 v7.17.7
go: downloading github.com/go-sql-driver/mysql v1.6.0
go: downloading github.com/gomodule/redigo v1.8.9
go: downloading github.com/lib/pq v1.10.7
go: downloading github.com/nats-io/nats.go v1.17.0
go: downloading github.com/nats-io/stan.go v0.10.3
go: downloading github.com/nsqio/go-nsq v1.1.0
go: downloading github.com/minio/simdjson-go v0.4.2
go: downloading github.com/pkg/errors v0.9.1
go: downloading github.com/rabbitmq/amqp091-go v1.5.0
go: downloading github.com/xdg/scram v1.0.5
go: downloading golang.org/x/sync v0.1.0
go: downloading github.com/bits-and-blooms/bitset v1.3.3
go: downloading github.com/mattn/go-colorable v0.1.13
go: downloading github.com/mattn/go-isatty v0.0.16
go: downloading github.com/mattn/go-runewidth v0.0.14
go: downloading github.com/golang/protobuf v1.5.2
go: downloading github.com/gogo/protobuf v1.3.2
go: downloading github.com/pquerna/cachecontrol v0.1.0
go: downloading gopkg.in/square/go-jose.v2 v2.6.0
go: downloading github.com/minio/csvparser v1.0.0
go: downloading golang.org/x/net v0.2.0
go: downloading github.com/fraugster/parquet-go v0.12.0
go: downloading github.com/alecthomas/participle v0.7.1
go: downloading github.com/google/pprof v0.0.0-20220829040838-70bd9ae97f40
go: downloading github.com/Azure/go-ntlmssp v0.0.0-20220621081337-cb9428e4ac1e
go: downloading github.com/go-asn1-ber/asn1-ber v1.5.4
go: downloading github.com/klauspost/cpuid/v2 v2.2.1
go: downloading go.etcd.io/etcd/client/pkg/v3 v3.5.5
go: downloading google.golang.org/grpc v1.50.1
go: downloading github.com/nats-io/nuid v1.0.1
go: downloading github.com/xdg/stringprep v1.0.3
go: downloading github.com/rivo/uniseg v0.4.2
go: downloading github.com/coreos/go-semver v0.3.0
go: downloading google.golang.org/genproto v0.0.0-20221018160656-63c7b68cfc55
go: downloading cloud.google.com/go v0.104.0
go: downloading github.com/matttproud/golang_protobuf_extensions v1.0.2
go: downloading github.com/modern-go/concurrent v0.0.0-20180306012644-bacd9c7ef1dd
go: downloading github.com/modern-go/reflect2 v1.0.2
go: downloading github.com/Azure/azure-pipeline-go v0.2.3
go: downloading github.com/gorilla/websocket v1.5.0
go: downloading github.com/golang/snappy v0.0.4
go: downloading github.com/go-openapi/analysis v0.21.4
go: downloading github.com/go-openapi/spec v0.20.7
go: downloading github.com/go-openapi/swag v0.22.3
go: downloading google.golang.org/protobuf v1.28.1
go: downloading github.com/nats-io/nkeys v0.3.0
go: downloading github.com/beorn7/perks v1.0.1
go: downloading go.uber.org/multierr v1.8.0
go: downloading github.com/rs/xid v1.4.0
go: downloading github.com/minio/md5-simd v1.1.2
go: downloading gopkg.in/ini.v1 v1.67.0
go: downloading golang.org/x/text v0.4.0
go: downloading github.com/rjeczalik/notify v0.9.2
go: downloading github.com/fatih/structs v1.1.0
go: downloading github.com/montanaflynn/stats v0.6.6
go: downloading github.com/lestrrat-go/jwx v1.2.25
go: downloading aead.dev/mem v0.2.0
go: downloading github.com/mattn/go-ieproxy v0.0.1
go: downloading github.com/coreos/go-systemd/v22 v22.4.0
go: downloading github.com/jcmturner/gokrb5/v8 v8.4.3
go: downloading github.com/eapache/queue v1.1.0
go: downloading github.com/jcmturner/gofork v1.7.6
go: downloading github.com/hashicorp/go-multierror v1.1.1
go: downloading github.com/eapache/go-resiliency v1.3.0
go: downloading github.com/davecgh/go-spew v1.1.1
go: downloading github.com/eapache/go-xerial-snappy v0.0.0-20180814174437-776d5712da21
go: downloading github.com/pierrec/lz4/v4 v4.1.16
go: downloading github.com/rcrowley/go-metrics v0.0.0-20201227073835-cf1acfcdf475
go: downloading github.com/mailru/easyjson v0.7.7
go: downloading gopkg.in/yaml.v3 v3.0.1
go: downloading github.com/hashicorp/errwrap v1.1.0
go: downloading github.com/josharian/intern v1.0.0
go: downloading github.com/apache/thrift v0.16.0
go: downloading github.com/go-openapi/strfmt v0.21.3
go: downloading github.com/go-openapi/jsonpointer v0.19.5
go: downloading github.com/lestrrat-go/option v1.0.0
go: downloading github.com/lestrrat-go/httpcc v1.0.1
go: downloading github.com/lestrrat-go/backoff/v2 v2.0.8
go: downloading github.com/lestrrat-go/blackmagic v1.0.1
go: downloading github.com/lestrrat-go/iter v1.0.2
go: downloading github.com/hashicorp/go-uuid v1.0.3
go: downloading github.com/jcmturner/dnsutils/v2 v2.0.0
go: downloading github.com/jcmturner/rpc/v2 v2.0.3
go: downloading github.com/jcmturner/aescts/v2 v2.0.0
go: downloading github.com/go-openapi/jsonreference v0.20.0
go: downloading github.com/asaskevich/govalidator v0.0.0-20210307081110-f21760c49a8d
go: downloading github.com/mitchellh/mapstructure v1.5.0
go: downloading github.com/go-openapi/errors v0.20.3
go: downloading go.mongodb.org/mongo-driver v1.10.3
go: downloading github.com/oklog/ulid v1.3.1
go: downloading cloud.google.com/go/iam v0.4.0
go: downloading cloud.google.com/go/compute v1.10.0
go: downloading github.com/googleapis/gax-go/v2 v2.5.1
go: downloading go.opencensus.io v0.23.0
go: downloading golang.org/x/xerrors v0.0.0-20220907171357-04be3eba64a2
go: downloading github.com/golang/groupcache v0.0.0-20210331224755-41bb18bfe9da
go: downloading github.com/go-openapi/runtime v0.24.2
go: downloading github.com/go-openapi/validate v0.22.0
go: downloading github.com/jessevdk/go-flags v1.5.0
go: downloading github.com/unrolled/secure v1.13.0
go: downloading github.com/minio/mc v0.0.0-20221201184114-854b4f123f03
go: downloading github.com/tidwall/gjson v1.14.3
go: downloading github.com/tidwall/match v1.1.1
go: downloading github.com/tidwall/pretty v1.2.1
go: downloading github.com/docker/go-units v0.5.0
go: downloading github.com/jedib0t/go-pretty/v6 v6.3.8
go: downloading github.com/charmbracelet/bubbles v0.14.0
go: downloading github.com/navidys/tvxwidgets v0.1.1
go: downloading github.com/minio/colorjson v1.0.4
go: downloading github.com/google/shlex v0.0.0-20191202100458-e7afc7fbc510
go: downloading gopkg.in/h2non/filetype.v1 v1.0.5
go: downloading github.com/olekukonko/tablewriter v0.0.5
go: downloading github.com/minio/filepath v1.0.0
go: downloading github.com/tklauser/go-sysconf v0.3.11
go: downloading golang.org/x/term v0.2.0
go: downloading github.com/posener/complete v1.2.3
go: downloading github.com/charmbracelet/lipgloss v0.6.0
go: downloading github.com/charmbracelet/bubbletea v0.22.1
go: downloading github.com/gdamore/tcell/v2 v2.5.3
go: downloading github.com/pkg/xattr v0.4.9
go: downloading github.com/muesli/reflow v0.3.0
go: downloading github.com/prometheus/prom2json v1.3.2
go: downloading github.com/rivo/tview v0.0.0-20220916081518-2e69b7385a37
go: downloading github.com/muesli/termenv v0.13.0
go: downloading github.com/muesli/cancelreader v0.2.2
go: downloading github.com/mattn/go-localereader v0.0.1
go: downloading github.com/containerd/console v1.0.3
go: downloading github.com/muesli/ansi v0.0.0-20211031195517-c9f0611b6c70
go: downloading github.com/tklauser/numcpus v0.6.0
go: downloading github.com/lucasb-eyer/go-colorful v1.2.0
go: downloading github.com/gdamore/encoding v1.0.0
go: downloading github.com/aymanbagabas/go-osc52 v1.2.1
go: downloading github.com/googleapis/enterprise-certificate-proxy v0.1.0
go: downloading github.com/google/go-cmp v0.5.9
../../../../pkg/mod/github.com/minio/console@v0.22.2/pkg/logger/config/config.go:20:2: github.com/minio/madmin-go/v2@v2.0.1: replacement directory ../madmin-go does not exist
../../../../pkg/mod/github.com/minio/pkg@v1.5.8/sys/stats_linux.go:27:2: github.com/minio/madmin-go/v2@v2.0.1: replacement directory ../madmin-go does not exist
cmd/admin-handlers.go:51:2: github.com/minio/madmin-go/v2@v2.0.1: replacement directory ../madmin-go does not exist
cmd/server-rlimit.go:24:2: github.com/minio/madmin-go/v2@v2.0.1: replacement directory ../madmin-go does not exist
make: *** [build] Error 1

```

**Comment by minio-trusted** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-erasure.sh | :heavy_check_mark: |
| mint-dist-erasure.sh | :heavy_check_mark: |
| mint-compress-encrypt-dist-erasure.sh | :heavy_check_mark: |
| mint-pools.sh | :heavy_check_mark: |
Deleting image on docker hub
Deleting image locally

File: cmd/site-replication.go [hunk 1]
```diff
@@ -72,6 +72,10 @@ var (
 		Cause: errors.New("peer not found"),
 		Code:  ErrSiteReplicationInvalidRequest,
 	}
+	errSRRequestorNotFound = SRError{
+		Cause: errors.New("requesting site not found in site replication config"),
```
Comment (ravindk89) [inline cmd/site-replication.go:76]: Q: Can we state which site which was not found? Or is this intended to say that the site specified as the initial alias is not in the replication config (e.g. for mc admin replicate add/remove)

**Review by ravindk89 — COMMENTED** [review]
I'll test this tomorrow , but had a thought.

Something I've seen done in other replicated setups is to have something like a version attached to the config which gets bumped each time the config changes.

If a member is out of sync, then it simply does not work as expected until an admin comes along to fix the issue.

So for example, lets say on init `mc admin replicate add SITEA SITEB SITEC` we set the replica version to 1. If we add SITED the replica version is now 2. If Site C goes down and gets removed by `mc admin replicate remove SITEA SITEC --force`, replica version is now 3. If Site C mysteriously comes back up, it sees that it is out of sync with the replica set and blocks replication (or fails to start entirely). A site-down scenario is the only time I can think of where this matters, since for adding a site we still require all sites to be online and healthy anyways (I assume?)

This would act as a safety valve for any sort of seriously flappy or unstable topology where a given site keeps going down and coming back up, where once an admin chooses to drop that site, there is no danger of it somehow coming back online and replicating garbage data. 

Thoughts?

File: cmd/site-replication.go (hunk 1 above)
Comment (poornas) [reply cmd/site-replication.go:76]: the requesting site here is the initial alias in `mc admin replicate remove`.

**Comment by poornas** [comment]
> I'll test this tomorrow , but had a thought.
> 
> Something I've seen done in other replicated setups is to have something like a version attached to the config which gets bumped each time the config changes.
> 
> If a member is out of sync, then it simply does not work as expected until an admin comes along to fix the issue.
> 
> So for example, lets say on init `mc admin replicate add SITEA SITEB SITEC` we set the replica version to 1. If we add SITED the replica version is now 2. If Site C goes down and gets removed by `mc admin replicate remove SITEA SITEC --force`, replica version is now 3. If Site C mysteriously comes back up, it sees that it is out of sync with the replica set and blocks replication (or fails to start entirely). A site-down scenario is the only time I can think of where this matters, since for adding a site we still require all sites to be online and healthy anyways (I assume?)
> 
> This would act as a safety valve for any sort of seriously flappy or unstable topology where a given site keeps going down and coming back up, where once an admin chooses to drop that site, there is no danger of it somehow coming back online and replicating garbage data.
> 
> Thoughts?

Adding a version to the site replication config is not an adequate guard, timestamp would be better. However, all of this is an overkill - If a site has been dropped from site replication while it was offline, and if it ever is brought back online, let's make a note in the documentation that it should explicitly delink itself with `mc admin replicate remove sitec sitec --force` so that it no longer replicates to the other sites. `mc admin replicate remove` should not be used frivolously unless a site is going to be dropped permanently

**Comment by ravindk89** [comment]
https://github.com/minio/minio/issues/16265#issuecomment-1362240348

Made this in the wrong spot. Either way, LGTM unless we want to try handling the API/mc errors in a particular way.

**Review by ravindk89 — APPROVED** [review]
Works in practice. Throws errors and warnings, but functions at the end. Since this is a `--force` operation I think it's OK to say in docs that some level of error/warning is expected, as this is a brute force op.

Thanks!

**Review by harshavardhana — APPROVED** [review]

**Comment by minio-trusted** [comment]
```
Error running mint automation
+ mkdir -p 16279-7530190/gopath/src/github.com/minio
+ git -C 16279-7530190/gopath/src/github.com/minio clone --quiet https://github.com/minio/minio.git
+ git -C 16279-7530190/gopath/src/github.com/minio/minio remote add minio https://github.com/minio/minio.git
+ git -C 16279-7530190/gopath/src/github.com/minio/minio fetch --quiet minio pull/16279/head:pr16279
+ git -C 16279-7530190/gopath/src/github.com/minio/minio checkout --quiet pr16279
+ GO111MODULE=on
+ GOPATH=/home/mint-auto/mint-auto/16279-7530190/gopath
+ make -C 16279-7530190/gopath/src/github.com/minio/minio --quiet
go: downloading github.com/gorilla/mux v1.8.0
go: downloading github.com/klauspost/filepathx v1.1.1
go: downloading github.com/klauspost/compress v1.15.12
go: downloading github.com/minio/highwayhash v1.0.2
go: downloading github.com/hashicorp/golang-lru v0.5.4
go: downloading github.com/klauspost/pgzip v1.2.5
go: downloading github.com/inconshreveable/mousetrap v1.0.1
go: downloading github.com/golang-jwt/jwt/v4 v4.4.2
go: downloading github.com/klauspost/readahead v1.4.0
go: downloading github.com/lithammer/shortuuid/v4 v4.0.0
go: downloading github.com/miekg/dns v1.1.50
go: downloading github.com/minio/kes v0.22.0
go: downloading github.com/json-iterator/go v1.1.12
go: downloading github.com/minio/cli v1.24.0
go: downloading github.com/minio/minio-go/v7 v7.0.44
go: downloading github.com/poornas/madmin-go/v2 v2.0.0-20221219211815-92423f627884
go: downloading github.com/klauspost/reedsolomon v1.11.3
go: downloading github.com/zeebo/xxh3 v1.0.2
go: downloading github.com/minio/dperf v0.4.2
go: downloading go.etcd.io/etcd/client/v3 v3.5.5
go: downloading go.uber.org/atomic v1.10.0
go: downloading github.com/minio/console v0.22.2
go: downloading golang.org/x/crypto v0.3.0
go: downloading cloud.google.com/go/storage v1.26.0
go: downloading github.com/Azure/azure-storage-blob-go v0.15.0
go: downloading github.com/minio/pkg v1.5.8
go: downloading github.com/cheggaaa/pb v1.0.29
go: downloading github.com/bits-and-blooms/bloom/v3 v3.3.1
go: downloading github.com/coreos/go-oidc v2.2.1+incompatible
go: downloading github.com/bcicen/jstream v1.0.1
go: downloading github.com/dchest/siphash v1.2.3
go: downloading github.com/cespare/xxhash/v2 v2.1.2
go: downloading github.com/cosnicolaou/pbzip2 v1.0.1
go: downloading github.com/dustin/go-humanize v1.0.0
go: downloading github.com/go-openapi/loads v0.21.2
go: downloading github.com/felixge/fgprof v0.9.3
go: downloading github.com/fatih/color v1.13.0
go: downloading github.com/google/uuid v1.3.0
go: downloading github.com/secure-io/sio-go v0.3.1
go: downloading github.com/djherbis/atime v1.1.0
go: downloading github.com/minio/zipindex v0.3.0
go: downloading github.com/pierrec/lz4 v2.6.1+incompatible
go: downloading github.com/minio/xxml v0.0.3
go: downloading github.com/shirou/gopsutil/v3 v3.22.9
go: downloading github.com/mitchellh/go-homedir v1.1.0
go: downloading github.com/rs/cors v1.8.2
go: downloading github.com/prometheus/client_model v0.3.0
go: downloading github.com/rs/dnscache v0.0.0-20211102005908-e0241e321417
go: downloading github.com/prometheus/procfs v0.8.0
go: downloading github.com/prometheus/common v0.37.0
go: downloading github.com/minio/sio v0.3.0
go: downloading github.com/minio/selfupdate v0.5.0
go: downloading go.etcd.io/etcd/api/v3 v3.5.5
go: downloading github.com/tinylib/msgp v1.1.7-0.20220719154719-f3635b96e483
go: downloading github.com/prometheus/client_golang v1.13.0
go: downloading github.com/philhofer/fwd v1.1.2-0.20210722190033-5c56ac6d0bb9
go: downloading github.com/valyala/bytebufferpool v1.0.0
go: downloading golang.org/x/oauth2 v0.2.0
go: downloading golang.org/x/sys v0.2.0
go: downloading google.golang.org/api v0.98.0
go: downloading gopkg.in/yaml.v2 v2.4.0
go: downloading go.uber.org/zap v1.23.0
go: downloading golang.org/x/time v0.0.0-20220722155302-e5dcc9cfc0b9
go: downloading github.com/go-ldap/ldap/v3 v3.4.4
go: downloading github.com/minio/sha256-simd v1.0.0
go: downloading github.com/buger/jsonparser v1.1.1
go: downloading github.com/beevik/ntp v0.3.0
go: downloading github.com/coredns/coredns v1.9.4
go: downloading github.com/ncw/directio v1.0.5
go: downloading github.com/minio/simdjson-go v0.4.2
go: downloading github.com/Shopify/sarama v1.36.0
go: downloading github.com/eclipse/paho.mqtt.golang v1.4.1
go: downloading github.com/elastic/go-elasticsearch/v7 v7.17.7
go: downloading github.com/go-sql-driver/mysql v1.6.0
go: downloading github.com/gomodule/redigo v1.8.9
go: downloading github.com/lib/pq v1.10.7
go: downloading github.com/nats-io/nats.go v1.17.0
go: downloading github.com/nats-io/stan.go v0.10.3
go: downloading github.com/nsqio/go-nsq v1.1.0
go: downloading github.com/pkg/errors v0.9.1
go: downloading github.com/rabbitmq/amqp091-go v1.5.0
go: downloading github.com/xdg/scram v1.0.5
go: downloading github.com/mattn/go-colorable v0.1.13
go: downloading github.com/mattn/go-isatty v0.0.16
go: downloading golang.org/x/sync v0.1.0
go: downloading github.com/bits-and-blooms/bitset v1.3.3
go: downloading github.com/mattn/go-runewidth v0.0.14
go: downloading github.com/golang/protobuf v1.5.2
go: downloading github.com/minio/csvparser v1.0.0
go: downloading github.com/fraugster/parquet-go v0.12.0
go: downloading github.com/alecthomas/participle v0.7.1
go: downloading github.com/pquerna/cachecontrol v0.1.0
go: downloading gopkg.in/square/go-jose.v2 v2.6.0
go: downloading golang.org/x/net v0.2.0
go: downloading github.com/gogo/protobuf v1.3.2
go: downloading github.com/Azure/go-ntlmssp v0.0.0-20220621081337-cb9428e4ac1e
go: downloading github.com/go-asn1-ber/asn1-ber v1.5.4
go: downloading github.com/klauspost/cpuid/v2 v2.2.1
go: downloading go.etcd.io/etcd/client/pkg/v3 v3.5.5
go: downloading google.golang.org/grpc v1.50.1
go: downloading github.com/xdg/stringprep v1.0.3
go: downloading github.com/google/pprof v0.0.0-20220829040838-70bd9ae97f40
go: downloading github.com/golang/snappy v0.0.4
go: downloading github.com/nats-io/nuid v1.0.1
go: downloading github.com/rivo/uniseg v0.4.2
go: downloading github.com/modern-go/concurrent v0.0.0-20180306012644-bacd9c7ef1dd
go: downloading github.com/modern-go/reflect2 v1.0.2
go: downloading github.com/coreos/go-semver v0.3.0
go: downloading google.golang.org/genproto v0.0.0-20221018160656-63c7b68cfc55
go: downloading github.com/matttproud/golang_protobuf_extensions v1.0.2
go: downloading github.com/go-openapi/spec v0.20.7
go: downloading github.com/go-openapi/swag v0.22.3
go: downloading github.com/go-openapi/analysis v0.21.4
go: downloading github.com/Azure/azure-pipeline-go v0.2.3
go: downloading github.com/gorilla/websocket v1.5.0
go: downloading github.com/rjeczalik/notify v0.9.2
go: downloading github.com/montanaflynn/stats v0.6.6
go: downloading github.com/lestrrat-go/jwx v1.2.25
go: downloading github.com/fatih/structs v1.1.0
go: downloading github.com/beorn7/perks v1.0.1
go: downloading google.golang.org/protobuf v1.28.1
go: downloading golang.org/x/text v0.4.0
go: downloading github.com/coreos/go-systemd/v22 v22.4.0
go: downloading github.com/rs/xid v1.4.0
go: downloading github.com/minio/md5-simd v1.1.2
go: downloading gopkg.in/ini.v1 v1.67.0
go: downloading github.com/mattn/go-ieproxy v0.0.1
go: downloading github.com/mailru/easyjson v0.7.7
go: downloading gopkg.in/yaml.v3 v3.0.1
go: downloading cloud.google.com/go v0.104.0
go: downloading github.com/nats-io/nkeys v0.3.0
go: downloading go.uber.org/multierr v1.8.0
go: downloading github.com/apache/thrift v0.16.0
go: downloading github.com/tklauser/go-sysconf v0.3.11
go: downloading github.com/josharian/intern v1.0.0
go: downloading aead.dev/mem v0.2.0
go: downloading github.com/eapache/go-resiliency v1.3.0
go: downloading github.com/rcrowley/go-metrics v0.0.0-20201227073835-cf1acfcdf475
go: downloading github.com/jcmturner/gokrb5/v8 v8.4.3
go: downloading github.com/jcmturner/gofork v1.7.6
go: downloading github.com/hashicorp/go-multierror v1.1.1
go: downloading github.com/eapache/go-xerial-snappy v0.0.0-20180814174437-776d5712da21
go: downloading github.com/pierrec/lz4/v4 v4.1.16
go: downloading github.com/davecgh/go-spew v1.1.1
go: downloading github.com/eapache/queue v1.1.0
go: downloading github.com/go-openapi/jsonpointer v0.19.5
go: downloading github.com/go-openapi/strfmt v0.21.3
go: downloading github.com/lestrrat-go/iter v1.0.2
go: downloading github.com/lestrrat-go/blackmagic v1.0.1
go: downloading github.com/lestrrat-go/option v1.0.0
go: downloading github.com/lestrrat-go/backoff/v2 v2.0.8
go: downloading github.com/lestrrat-go/httpcc v1.0.1
go: downloading github.com/go-openapi/jsonreference v0.20.0
go: downloading github.com/hashicorp/errwrap v1.1.0
go: downloading github.com/tklauser/numcpus v0.6.0
go: downloading github.com/asaskevich/govalidator v0.0.0-20210307081110-f21760c49a8d
go: downloading github.com/oklog/ulid v1.3.1
go: downloading go.mongodb.org/mongo-driver v1.10.3
go: downloading github.com/go-openapi/errors v0.20.3
go: downloading github.com/mitchellh/mapstructure v1.5.0
go: downloading cloud.google.com/go/compute v1.10.0
go: downloading github.com/googleapis/gax-go/v2 v2.5.1
go: downloading cloud.google.com/go/iam v0.4.0
go: downloading go.opencensus.io v0.23.0
go: downloading golang.org/x/xerrors v0.0.0-20220907171357-04be3eba64a2
go: downloading github.com/jcmturner/dnsutils/v2 v2.0.0
go: downloading github.com/hashicorp/go-uuid v1.0.3
go: downloading github.com/jcmturner/rpc/v2 v2.0.3
go: downloading github.com/jcmturner/aescts/v2 v2.0.0
go: downloading github.com/golang/groupcache v0.0.0-20210331224755-41bb18bfe9da
go: downloading github.com/go-openapi/runtime v0.24.2
go: downloading github.com/go-openapi/validate v0.22.0
go: downloading github.com/minio/mc v0.0.0-20221201184114-854b4f123f03
go: downloading github.com/tidwall/gjson v1.14.3
go: downloading github.com/jessevdk/go-flags v1.5.0
go: downloading github.com/unrolled/secure v1.13.0
go: downloading github.com/tidwall/pretty v1.2.1
go: downloading github.com/tidwall/match v1.1.1
go: downloading github.com/docker/go-units v0.5.0
go: downloading github.com/jedib0t/go-pretty/v6 v6.3.8
go: downloading github.com/charmbracelet/bubbles v0.14.0
go: downloading github.com/charmbracelet/bubbletea v0.22.1
go: downloading github.com/muesli/reflow v0.3.0
go: downloading github.com/rivo/tview v0.0.0-20220916081518-2e69b7385a37
go: downloading github.com/minio/colorjson v1.0.4
go: downloading github.com/charmbracelet/lipgloss v0.6.0
go: downloading github.com/olekukonko/tablewriter v0.0.5
go: downloading github.com/gdamore/tcell/v2 v2.5.3
go: downloading github.com/posener/complete v1.2.3
go: downloading github.com/prometheus/prom2json v1.3.2
go: downloading github.com/google/shlex v0.0.0-20191202100458-e7afc7fbc510
go: downloading github.com/minio/filepath v1.0.0
go: downloading gopkg.in/h2non/filetype.v1 v1.0.5
go: downloading golang.org/x/term v0.2.0
go: downloading github.com/pkg/xattr v0.4.9
go: downloading github.com/navidys/tvxwidgets v0.1.1
go: downloading github.com/muesli/termenv v0.13.0
go: downloading github.com/containerd/console v1.0.3
go: downloading github.com/muesli/ansi v0.0.0-20211031195517-c9f0611b6c70
go: downloading github.com/muesli/cancelreader v0.2.2
go: downloading github.com/mattn/go-localereader v0.0.1
go: downloading github.com/lucasb-eyer/go-colorful v1.2.0
go: downloading github.com/aymanbagabas/go-osc52 v1.2.1
go: downloading github.com/gdamore/encoding v1.0.0
go: downloading github.com/google/go-cmp v0.5.9
go: downloading github.com/googleapis/enterprise-certificate-proxy v0.1.0
# github.com/minio/minio/cmd
cmd/server-main.go:350:39: undefined: madmin.TraceBootstrap
cmd/server-main.go:355:21: undefined: madmin.TraceBootstrap
make: *** [build] Error 2

```

File: go.mod [hunk 2]
```diff
@@ -228,3 +228,5 @@ require (
 	gopkg.in/square/go-jose.v2 v2.6.0 // indirect
 	gopkg.in/yaml.v3 v3.0.1 // indirect
 )
+
+replace github.com/minio/madmin-go/v2 => github.com/poornas/madmin-go/v2 v2.0.0-20221219211815-92423f627884
```
Comment (harshavardhana) [inline go.mod]:
```suggestion
```

File: go.sum [hunk 3]
```diff
@@ -887,6 +885,8 @@ github.com/pkg/xattr v0.4.9/go.mod h1:di8WF84zAKk8jzR1UBTEWh9AUlIZZ7M/JNt8e9B6kt
 github.com/pmezard/go-difflib v1.0.0/go.mod h1:iKH77koFhYxTK1pcRnkKkqfTogsbg7gZNVY4sRDYZ/4=
 github.com/pmezard/go-difflib v1.0.1-0.20181226105442-5d4384ee4fb2 h1:Jamvg5psRIccs7FGNTlIRMkT8wgtp5eCXdBlqhYGL6U=
 github.com/pmezard/go-difflib v1.0.1-0.20181226105442-5d4384ee4fb2/go.mod h1:iKH77koFhYxTK1pcRnkKkqfTogsbg7gZNVY4sRDYZ/4=
+github.com/poornas/madmin-go/v2 v2.0.0-20221219211815-92423f627884 h1:FmqT31QwxYtvLkLVAcXykELuHHPidVMS6MtmMtgGvS0=
+github.com/poornas/madmin-go/v2 v2.0.0-20221219211815-92423f627884/go.mod h1:5aFi/VLWBHC2DEFfGIlUmAeJhaF4ZAjuYpEWZFU14Zw=
```
Comment (harshavardhana) [inline go.sum]:
```suggestion
github.com/minio/madmin-go/v2 v2.0.2-0.20221221104141-93e7e5aefaf2 h1:MPWI0f+mXCX9/0t8XBHXHzR8L0yT40NI4fdbvKyy0aU=
github.com/minio/madmin-go/v2 v2.0.2-0.20221221104141-93e7e5aefaf2/go.mod h1:5aFi/VLWBHC2DEFfGIlUmAeJhaF4ZAjuYpEWZFU14Zw=
```

**Review by harshavardhana — CHANGES_REQUESTED** [review]

**Comment by minio-trusted** [comment]
```
Error running mint automation
+ mkdir -p 16279-f0a000b/gopath/src/github.com/minio
+ git -C 16279-f0a000b/gopath/src/github.com/minio clone --quiet https://github.com/minio/minio.git
+ git -C 16279-f0a000b/gopath/src/github.com/minio/minio remote add minio https://github.com/minio/minio.git
+ git -C 16279-f0a000b/gopath/src/github.com/minio/minio fetch --quiet minio pull/16279/head:pr16279
+ git -C 16279-f0a000b/gopath/src/github.com/minio/minio checkout --quiet pr16279
+ GO111MODULE=on
+ GOPATH=/home/mint-auto/mint-auto/16279-f0a000b/gopath
+ make -C 16279-f0a000b/gopath/src/github.com/minio/minio --quiet
go: downloading github.com/klauspost/pgzip v1.2.5
go: downloading github.com/minio/selfupdate v0.5.0
go: downloading github.com/dustin/go-humanize v1.0.0
go: downloading github.com/minio/sio v0.3.0
go: downloading github.com/minio/xxml v0.0.3
go: downloading github.com/bcicen/jstream v1.0.1
go: downloading github.com/bits-and-blooms/bloom/v3 v3.3.1
go: downloading github.com/minio/pkg v1.5.8
go: downloading github.com/cespare/xxhash/v2 v2.1.2
go: downloading github.com/Azure/azure-storage-blob-go v0.15.0
go: downloading github.com/cheggaaa/pb v1.0.29
go: downloading github.com/minio/zipindex v0.3.0
go: downloading github.com/mitchellh/go-homedir v1.1.0
go: downloading github.com/cosnicolaou/pbzip2 v1.0.1
go: downloading github.com/philhofer/fwd v1.1.2-0.20210722190033-5c56ac6d0bb9
go: downloading github.com/prometheus/client_model v0.3.0
go: downloading github.com/dchest/siphash v1.2.3
go: downloading github.com/djherbis/atime v1.1.0
go: downloading github.com/minio/console v0.22.2
go: downloading github.com/minio/highwayhash v1.0.2
go: downloading github.com/rs/dnscache v0.0.0-20211102005908-e0241e321417
go: downloading github.com/pierrec/lz4 v2.6.1+incompatible
go: downloading github.com/secure-io/sio-go v0.3.1
go: downloading github.com/google/uuid v1.3.0
go: downloading github.com/golang-jwt/jwt/v4 v4.4.2
go: downloading cloud.google.com/go/storage v1.26.0
go: downloading github.com/felixge/fgprof v0.9.3
go: downloading github.com/minio/minio-go/v7 v7.0.44
go: downloading github.com/gorilla/mux v1.8.0
go: downloading github.com/go-openapi/loads v0.21.2
go: downloading github.com/klauspost/readahead v1.4.0
go: downloading github.com/miekg/dns v1.1.50
go: downloading github.com/prometheus/common v0.37.0
go: downloading github.com/prometheus/procfs v0.8.0
go: downloading github.com/fatih/color v1.13.0
go: downloading github.com/valyala/bytebufferpool v1.0.0
go: downloading github.com/tinylib/msgp v1.1.7-0.20220719154719-f3635b96e483
go: downloading github.com/prometheus/client_golang v1.13.0
go: downloading go.etcd.io/etcd/client/v3 v3.5.5
go: downloading golang.org/x/crypto v0.3.0
go: downloading go.uber.org/atomic v1.10.0
go: downloading github.com/minio/cli v1.24.0
go: downloading github.com/klauspost/reedsolomon v1.11.3
go: downloading github.com/minio/kes v0.22.0
go: downloading github.com/lithammer/shortuuid/v4 v4.0.0
go: downloading github.com/coreos/go-oidc v2.2.1+incompatible
go: downloading github.com/minio/dperf v0.4.2
go: downloading github.com/hashicorp/golang-lru v0.5.4
go: downloading github.com/minio/madmin-go/v2 v2.0.2-0.20221221104141-93e7e5aefaf2
go: downloading github.com/klauspost/compress v1.15.12
go: downloading github.com/json-iterator/go v1.1.12
go: downloading github.com/inconshreveable/mousetrap v1.0.1
go: downloading github.com/klauspost/filepathx v1.1.1
go: downloading github.com/rs/cors v1.8.2
go: downloading github.com/shirou/gopsutil/v3 v3.22.9
go: downloading github.com/zeebo/xxh3 v1.0.2
go: downloading go.etcd.io/etcd/api/v3 v3.5.5
go: downloading golang.org/x/oauth2 v0.2.0
go: downloading golang.org/x/sys v0.2.0
go: downloading google.golang.org/api v0.98.0
go: downloading gopkg.in/yaml.v2 v2.4.0
go: downloading golang.org/x/time v0.0.0-20220722155302-e5dcc9cfc0b9
go: downloading github.com/coredns/coredns v1.9.4
go: downloading github.com/buger/jsonparser v1.1.1
go: downloading github.com/beevik/ntp v0.3.0
go: downloading go.uber.org/zap v1.23.0
go: downloading github.com/minio/sha256-simd v1.0.0
go: downloading github.com/go-ldap/ldap/v3 v3.4.4
go: downloading github.com/ncw/directio v1.0.5
go: downloading github.com/minio/simdjson-go v0.4.2
go: downloading github.com/Shopify/sarama v1.36.0
go: downloading github.com/eclipse/paho.mqtt.golang v1.4.1
go: downloading github.com/elastic/go-elasticsearch/v7 v7.17.7
go: downloading github.com/go-sql-driver/mysql v1.6.0
go: downloading github.com/gomodule/redigo v1.8.9
go: downloading github.com/lib/pq v1.10.7
go: downloading github.com/nats-io/nats.go v1.17.0
go: downloading github.com/nats-io/stan.go v0.10.3
go: downloading github.com/nsqio/go-nsq v1.1.0
go: downloading github.com/pkg/errors v0.9.1
go: downloading github.com/rabbitmq/amqp091-go v1.5.0
go: downloading github.com/xdg/scram v1.0.5
go: downloading github.com/mattn/go-colorable v0.1.13
go: downloading github.com/mattn/go-isatty v0.0.16
go: downloading golang.org/x/sync v0.1.0
go: downloading github.com/golang/protobuf v1.5.2
go: downloading github.com/bits-and-blooms/bitset v1.3.3
go: downloading github.com/gogo/protobuf v1.3.2
go: downloading github.com/fraugster/parquet-go v0.12.0
go: downloading github.com/mattn/go-runewidth v0.0.14
go: downloading github.com/minio/csvparser v1.0.0
go: downloading github.com/pquerna/cachecontrol v0.1.0
go: downloading gopkg.in/square/go-jose.v2 v2.6.0
go: downloading github.com/alecthomas/participle v0.7.1
go: downloading golang.org/x/net v0.2.0
go: downloading github.com/klauspost/cpuid/v2 v2.2.1
go: downloading github.com/google/pprof v0.0.0-20220829040838-70bd9ae97f40
go: downloading github.com/Azure/go-ntlmssp v0.0.0-20220621081337-cb9428e4ac1e
go: downloading github.com/go-asn1-ber/asn1-ber v1.5.4
go: downloading github.com/golang/snappy v0.0.4
go: downloading go.etcd.io/etcd/client/pkg/v3 v3.5.5
go: downloading google.golang.org/grpc v1.50.1
go: downloading github.com/nats-io/nuid v1.0.1
go: downloading github.com/xdg/stringprep v1.0.3
go: downloading github.com/go-openapi/analysis v0.21.4
go: downloading github.com/go-openapi/spec v0.20.7
go: downloading github.com/go-openapi/swag v0.22.3
go: downloading github.com/matttproud/golang_protobuf_extensions v1.0.2
go: downloading github.com/modern-go/concurrent v0.0.0-20180306012644-bacd9c7ef1dd
go: downloading github.com/coreos/go-semver v0.3.0
go: downloading github.com/modern-go/reflect2 v1.0.2
go: downloading google.golang.org/genproto v0.0.0-20221018160656-63c7b68cfc55
go: downloading github.com/rivo/uniseg v0.4.2
go: downloading github.com/Azure/azure-pipeline-go v0.2.3
go: downloading github.com/gorilla/websocket v1.5.0
go: downloading github.com/rjeczalik/notify v0.9.2
go: downloading github.com/lestrrat-go/jwx v1.2.25
go: downloading github.com/montanaflynn/stats v0.6.6
go: downloading github.com/fatih/structs v1.1.0
go: downloading github.com/beorn7/perks v1.0.1
go: downloading google.golang.org/protobuf v1.28.1
go: downloading aead.dev/mem v0.2.0
go: downloading github.com/rs/xid v1.4.0
go: downloading gopkg.in/ini.v1 v1.67.0
go: downloading github.com/minio/md5-simd v1.1.2
go: downloading golang.org/x/text v0.4.0
go: downloading github.com/mailru/easyjson v0.7.7
go: downloading github.com/mattn/go-ieproxy v0.0.1
go: downloading gopkg.in/yaml.v3 v3.0.1
go: downloading github.com/nats-io/nkeys v0.3.0
go: downloading go.uber.org/multierr v1.8.0
go: downloading github.com/coreos/go-systemd/v22 v22.4.0
go: downloading cloud.google.com/go v0.104.0
go: downloading github.com/apache/thrift v0.16.0
go: downloading github.com/tklauser/go-sysconf v0.3.11
go: downloading github.com/josharian/intern v1.0.0
go: downloading github.com/davecgh/go-spew v1.1.1
go: downloading github.com/eapache/queue v1.1.0
go: downloading github.com/eapache/go-resiliency v1.3.0
go: downloading github.com/rcrowley/go-metrics v0.0.0-20201227073835-cf1acfcdf475
go: downloading github.com/jcmturner/gokrb5/v8 v8.4.3
go: downloading github.com/pierrec/lz4/v4 v4.1.16
go: downloading github.com/eapache/go-xerial-snappy v0.0.0-20180814174437-776d5712da21
go: downloading github.com/hashicorp/go-multierror v1.1.1
go: downloading github.com/jcmturner/gofork v1.7.6
go: downloading github.com/go-openapi/strfmt v0.21.3
go: downloading github.com/go-openapi/jsonpointer v0.19.5
go: downloading github.com/lestrrat-go/iter v1.0.2
go: downloading github.com/lestrrat-go/httpcc v1.0.1
go: downloading github.com/lestrrat-go/blackmagic v1.0.1
go: downloading github.com/lestrrat-go/backoff/v2 v2.0.8
go: downloading github.com/lestrrat-go/option v1.0.0
go: downloading github.com/hashicorp/errwrap v1.1.0
go: downloading github.com/go-openapi/jsonreference v0.20.0
go: downloading github.com/tklauser/numcpus v0.6.0
go: downloading github.com/asaskevich/govalidator v0.0.0-20210307081110-f21760c49a8d
go: downloading github.com/go-openapi/errors v0.20.3
go: downloading go.mongodb.org/mongo-driver v1.10.3
go: downloading github.com/mitchellh/mapstructure v1.5.0
go: downloading github.com/oklog/ulid v1.3.1
go: downloading github.com/jcmturner/aescts/v2 v2.0.0
go: downloading github.com/hashicorp/go-uuid v1.0.3
go: downloading github.com/jcmturner/rpc/v2 v2.0.3
go: downloading github.com/jcmturner/dnsutils/v2 v2.0.0
go: downloading cloud.google.com/go/iam v0.4.0
go: downloading cloud.google.com/go/compute v1.10.0
go: downloading go.opencensus.io v0.23.0
go: downloading github.com/googleapis/gax-go/v2 v2.5.1
go: downloading golang.org/x/xerrors v0.0.0-20220907171357-04be3eba64a2
go: downloading github.com/golang/groupcache v0.0.0-20210331224755-41bb18bfe9da
go: downloading github.com/go-openapi/validate v0.22.0
go: downloading github.com/go-openapi/runtime v0.24.2
go: downloading github.com/minio/mc v0.0.0-20221201184114-854b4f123f03
go: downloading github.com/jessevdk/go-flags v1.5.0
go: downloading github.com/unrolled/secure v1.13.0
go: downloading github.com/tidwall/gjson v1.14.3
go: downloading github.com/tidwall/pretty v1.2.1
go: downloading github.com/tidwall/match v1.1.1
go: downloading github.com/docker/go-units v0.5.0
go: downloading github.com/jedib0t/go-pretty/v6 v6.3.8
go: downloading github.com/charmbracelet/bubbles v0.14.0
go: downloading gopkg.in/h2non/filetype.v1 v1.0.5
go: downloading github.com/google/shlex v0.0.0-20191202100458-e7afc7fbc510
go: downloading github.com/charmbracelet/bubbletea v0.22.1
go: downloading github.com/charmbracelet/lipgloss v0.6.0
go: downloading github.com/posener/complete v1.2.3
go: downloading github.com/muesli/reflow v0.3.0
go: downloading github.com/minio/colorjson v1.0.4
go: downloading github.com/minio/filepath v1.0.0
go: downloading github.com/gdamore/tcell/v2 v2.5.3
go: downloading github.com/olekukonko/tablewriter v0.0.5
go: downloading github.com/prometheus/prom2json v1.3.2
go: downloading github.com/pkg/xattr v0.4.9
go: downloading golang.org/x/term v0.2.0
go: downloading github.com/rivo/tview v0.0.0-20220916081518-2e69b7385a37
go: downloading github.com/navidys/tvxwidgets v0.1.1
go: downloading github.com/muesli/termenv v0.13.0
go: downloading github.com/containerd/console v1.0.3
go: downloading github.com/muesli/cancelreader v0.2.2
go: downloading github.com/mattn/go-localereader v0.0.1
go: downloading github.com/muesli/ansi v0.0.0-20211031195517-c9f0611b6c70
go: downloading github.com/lucasb-eyer/go-colorful v1.2.0
go: downloading github.com/aymanbagabas/go-osc52 v1.2.1
go: downloading github.com/gdamore/encoding v1.0.0
go: downloading github.com/googleapis/enterprise-certificate-proxy v0.1.0
go: downloading github.com/google/go-cmp v0.5.9
# github.com/minio/minio/cmd
cmd/site-replication.go:2095:9: rreq.RequestingDepID undefined (type madmin.SRRemoveReq has no field or method RequestingDepID)
cmd/site-replication.go:2178:10: rreq.RequestingDepID undefined (type madmin.SRRemoveReq has no field or method RequestingDepID)
cmd/site-replication.go:2182:30: rreq.RequestingDepID undefined (type madmin.SRRemoveReq has no field or method RequestingDepID)
make: *** [build] Error 2

```

**Comment by minio-trusted** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-fs.sh | :heavy_check_mark: |
| mint-erasure.sh | :heavy_check_mark: |
| mint-dist-erasure.sh | :heavy_check_mark: |
| mint-pools.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :x: [more...](#45eb2478-d455-4304-ac91-501cc18aff36) |
| mint-compress-encrypt-dist-erasure.sh | :x: [more...](#460e0307-a151-4056-ba3c-a3d60626e87a) |
<a name="45eb2478-d455-4304-ac91-501cc18aff36"></a>
### 16279-b77003e/mint-large-bucket.sh.log:
```
Running with
SERVER_ENDPOINT:      15.15.15.3:31088
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0
RUN_ON_FAIL:          0

To get logs, run 'docker cp c8c1215de8e2:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 1 seconds
(2/14) Running aws-sdk-java tests ... done in 2 seconds
(3/14) Running aws-sdk-php tests ... done in 42 seconds
(4/14) Running aws-sdk-ruby tests ... done in 7 seconds
(5/14) Running awscli tests ... done in 1 minutes and 0 seconds
(6/14) Running healthcheck tests ... done in 0 seconds
(7/14) Running mc tests ... done in 16 seconds
(8/14) Running minio-go tests ... done in 46 seconds
(9/14) Running minio-java tests ... FAILED in 29 seconds
{
  "name": "minio-java",
  "function": "addUser()",
  "duration": 408,
  "status": "FAIL",
  "error": "java.lang.RuntimeException: Request failed with response: {\"Code\":\"InternalError\",\"Message\":\"We encountered an internal error, please try again. (Server not initialized, please try again)\",\"Resource\":\"/minio/admin/v3/add-user\",\"RequestId\":\"17330D9F40C0CD1D\",\"HostId\":\"f7ff067f-25db-43e1-8164-a8ce063dc86d\"}\n >>> [io.minio.admin.MinioAdminClient.execute(MinioAdminClient.java:206), io.minio.admin.MinioAdminClient.addUser(MinioAdminClient.java:237), TestMinioAdminClient.addUser(TestMinioAdminClient.java:47), TestMinioAdminClient.runAdminTests(TestMinioAdminClient.java:160), FunctionalTest.runTests(FunctionalTest.java:3782), FunctionalTest.runEndpointTests(FunctionalTest.java:3881), FunctionalTest.main(FunctionalTest.java:4002)]"
}
(9/14) Running minio-js tests ... done in 50 seconds
(10/14) Running minio-py tests ... done in 1 minutes and 46 seconds
(11/14) Running s3cmd tests ... done in 15 seconds
(12/14) Running s3select tests ... done in 4 seconds
(13/14) Running versioning tests ... done in 3 minutes and 5 seconds

Executed 13 out of 14 tests successfully.
```
<a name="460e0307-a151-4056-ba3c-a3d60626e87a"></a>
### 16279-b77003e/mint-compress-encrypt-dist-erasure.sh.log:
```
Running with
SERVER_ENDPOINT:      15.15.15.7:30920
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0
RUN_ON_FAIL:          0

To get logs, run 'docker cp d47af49db238:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 1 seconds
(2/14) Running aws-sdk-java tests ... done in 2 seconds
(3/14) Running aws-sdk-php tests ... done in 42 seconds
(4/14) Running aws-sdk-ruby tests ... done in 7 seconds
(5/14) Running awscli tests ... done in 59 seconds
(6/14) Running healthcheck tests ... done in 0 seconds
(7/14) Running mc tests ... done in 16 seconds
(8/14) Running minio-go tests ... done in 44 seconds
(9/14) Running minio-java tests ... FAILED in 26 seconds
{
  "name": "minio-java",
  "function": "addUser()",
  "duration": 399,
  "status": "FAIL",
  "error": "java.lang.RuntimeException: Request failed with response: {\"Code\":\"InternalError\",\"Message\":\"We encountered an internal error, please try again. (Server not initialized, please try again)\",\"Resource\":\"/minio/admin/v3/add-user\",\"RequestId\":\"17330D9DE8C85CF0\",\"HostId\":\"eb74fd0f-8f56-4795-9972-8c017b156ac5\"}\n >>> [io.minio.admin.MinioAdminClient.execute(MinioAdminClient.java:206), io.minio.admin.MinioAdminClient.addUser(MinioAdminClient.java:237), TestMinioAdminClient.addUser(TestMinioAdminClient.java:47), TestMinioAdminClient.runAdminTests(TestMinioAdminClient.java:160), FunctionalTest.runTests(FunctionalTest.java:3782), FunctionalTest.runEndpointTests(FunctionalTest.java:3881), FunctionalTest.main(FunctionalTest.java:4002)]"
}
(9/14) Running minio-js tests ... done in 49 seconds
(10/14) Running minio-py tests ... done in 1 minutes and 40 seconds
(11/14) Running s3cmd tests ... done in 14 seconds
(12/14) Running s3select tests ... done in 4 seconds
(13/14) Running versioning tests ... done in 5 minutes and 5 seconds

Executed 13 out of 14 tests successfully.
```
Deleting image on docker hub
Deleting image locally

**Comment by harshavardhana** [comment]
https://github.com/minio/mc/pull/4418 this PR is also needed to ensure that we do not crash the client.

**Comment by minio-trusted** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-erasure.sh | :heavy_check_mark: |
| mint-dist-erasure.sh | :heavy_check_mark: |
| mint-compress-encrypt-dist-erasure.sh | :heavy_check_mark: |
| mint-pools.sh | :heavy_check_mark: |
Deleting image on docker hub
Deleting image locally

**Review by harshavardhana — APPROVED** [review]
