### PR TITLE
Fix: Preserve MD5Sum for SSE encrypted objects

### LINKED ISSUE #6580: SSE-S3 PutObject Etag incompatible with AWS S3
## Expected Behavior
AWS S3 behavior, returned ETag is same as the original object 
```
$  s3cmd put /etc/issue --server-side-encryption s3://vadmeste/obj
upload: '/etc/issue' -> 's3://vadmeste/obj'  [1 of 1]
 26 of 26   100% in    0s    45.89 B/s  done

$ mc cat s3/vadmeste/obj

mc: <DEBUG> GET /obj HTTP/1.1
Host: vadmeste.s3.amazonaws.com
User-Agent: Minio (linux; amd64) minio-go/v6.0.8 mc/2018-10-01T22:37:50Z
Authorization: AWS4-HMAC-SHA256 Credential=**REDACTED**/20181007/us-east-1/s3/aws4_request, SignedHeaders=host;x-amz-content-sha256;x-amz-date, Signature=**REDACTED**
X-Amz-Content-Sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
X-Amz-Date: 20181007T080221Z
Accept-Encoding: gzip

mc: <DEBUG> HTTP/1.1 200 OK
Content-Length: 26
Accept-Ranges: bytes
Content-Type: text/plain
Date: Sun, 07 Oct 2018 08:02:22 GMT
Etag: "38103f9a76bb14e2abbc051b65722cff"
Last-Modified: Sun, 07 Oct 2018 08:01:58 GMT
Server: AmazonS3
X-Amz-Id-2: mok3b6vFSBPQkgXejiWF1eaT2ylgiAcU7130bzVDyQLeLW+mpdeuspOarxl9feMHWdZ4lmgdWGE=
X-Amz-Meta-S3cmd-Attrs: atime:1538875848/ctime:1534869850/gid:0/gname:root/md5:38103f9a76bb14e2abbc051b65722cff/mode:33188/mtime:1534772680/uid:0/uname:root
X-Amz-Request-Id: 36BA302681C145BF
X-Amz-Server-Side-Encryption: AES256
X-Amz-Version-Id: SiVT7t5L.T0KOpV4JPmSz5vJhTimqY0B

$ md5sum /etc/issue
38103f9a76bb14e2abbc051b65722cff  /etc/issue
```

## Current Behavior
Minio,  returned ETag is not same as the original object 
```
s3cmd put /etc/issue --server-side-encryption s3://vadmeste/obj
upload: '/etc/issue' -> 's3://vadmeste/obj'  [1 of 1]
 26 of 26   100% in    0s  1743.33 B/s  done
WARNING: MD5 Sums don't match!
WARNING: Retrying upload of /etc/issue
upload: '/etc/issue' -> 's3://vadmeste/obj'  [1 of 1]
 26 of 26   100% in    0s   476.11 B/s  done
WARNING: MD5 Sums don't match!
WARNING: Retrying upload of /etc/issue
upload: '/etc/issue' -> 's3://vadmeste/obj'  [1 of 1]
 26 of 26   100% in    0s   440.97 B/s  done
WARNING: MD5 Sums don't match!
WARNING: Retrying upload of /etc/issue
upload: '/etc/issue' -> 's3://vadmeste/obj'  [1 of 1]
 26 of 26   100% in    0s   510.78 B/s  done
WARNING: MD5 Sums don't match!
WARNING: Retrying upload of /etc/issue
upload: '/etc/issue' -> 's3://vadmeste/obj'  [1 of 1]
 26 of 26   100% in    0s   464.07 B/s  done
WARNING: MD5 Sums don't match!
WARNING: Retrying upload of /etc/issue
upload: '/etc/issue' -> 's3://vadmeste/obj'  [1 of 1]
 26 of 26   100% in    0s   475.29 B/s  done
WARNING: MD5 Sums don't match!
WARNING: Too many failures. Giving up on '/etc/issue'
ERROR: Upload of '/etc/issue' failed too many times (Last reason: )

$ s3cmd put /etc/issue --server-side-encryption s3://vadmeste/obj --debug  2>&1 |grep MD5
INFO: Running stat() and reading/calculating MD5 values on 1 files, this may take some time...
DEBUG: MD5 sums: computed=38103f9a76bb14e2abbc051b65722cff, received=b0669757fc3a19731794200ba9016146
WARNING: MD5 Sums don't match!
DEBUG: MD5 sums: computed=38103f9a76bb14e2abbc051b65722cff, received=ea882d6bcfc05a6605530de9729283a2
WARNING: MD5 Sums don't match!
DEBUG: MD5 sums: computed=38103f9a76bb14e2abbc051b65722cff, received=f84f9ad83fc07f86a3e33919a5ccf2db
WARNING: MD5 Sums don't match!
DEBUG: MD5 sums: computed=38103f9a76bb14e2abbc051b65722cff, received=c7e27b763e6bea7a03ac92b0c7a45934
WARNING: MD5 Sums don't match!
DEBUG: MD5 sums: computed=38103f9a76bb14e2abbc051b65722cff, received=3d473d1d09035128a6fd3a949d1c6d33
WARNING: MD5 Sums don't match!
DEBUG: MD5 sums: computed=38103f9a76bb14e2abbc051b65722cff, received=d000450838ff08cc82835bc473af8682
WARNING: MD5 Sums don't match!

$ mc cat myminio/vadmeste/obj
mc: <DEBUG> GET /vadmeste/obj HTTP/1.1
Host: localhost:9000
User-Agent: Minio (linux; amd64) minio-go/v6.0.8 mc/2018-10-01T22:37:50Z
Authorization: AWS4-HMAC-SHA256 Credential=minio/20181007/us-east-1/s3/aws4_request, SignedHeaders=host;x-amz-content-sha256;x-amz-date, Signature=**REDACTED**
X-Amz-Content-Sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
X-Amz-Date: 20181007T080404Z
Accept-Encoding: gzip

mc: <DEBUG> HTTP/1.1 200 OK
Content-Length: 26
Accept-Ranges: bytes
Content-Security-Policy: block-all-mixed-content
Content-Type: text/plain
Date: Sun, 07 Oct 2018 08:04:04 GMT
Etag: "d000450838ff08cc82835bc473af8682"
Last-Modified: Sun, 07 Oct 2018 08:03:42 GMT
Server: Minio/DEVELOPMENT.2018-10-07T08-00-14Z (linux; amd64)
Vary: Origin
X-Amz-Meta-S3cmd-Attrs: atime:1538875848/ctime:1534869850/gid:0/gname:root/md5:38103f9a76bb14e2abbc051b65722cff/mode:33188/mtime:1534772680/uid:0/uname:root
X-Amz-Request-Id: 155B44E42CF428FC
X-Amz-Server-Side-Encryption: AES256
X-Xss-Protection: 1; mode=block
```

## Possible Solution
No solution yet, this would require some implementation change. Current implementation treats SSE-S3 and SSE-KMS as same this is not true on AWS S3. Their behavior is different and should be implemented properly.

## Steps to Reproduce (for bugs)
Already explained in Expected and Current behavior. 

## Context
Compatibility and implementation issues with SSE

## Regression
No, implementation issue. 

## Your Environment
master branch with #6488, I don't think this PR has any effect this seems to be true with vault based implementation.

### PR DESCRIPTION
**Pull request by poornas**
To conform with AWS S3 Spec on ETag for SSE-S3 encrypted objects,
encrypt client sent MD5Sum and store it n backend as ETag.Extend
this behavior to SSE-C encrypted objects.

## Description

Fixes #6580 for minio server. Unable to reopen https://github.com/minio/minio/pull/6680 which was closed due to github issues yesterday and could not update PR for travis test failures.
## Motivation and Context

S3 spec specifies that content MD5Sum to be returned as Etag for single PUT,Upload Part operations where client requests SSE-S3 encryption. This PR makes minio server conformant to S3 spec.
## Regression
 No ( Incorrectly implemented because we were returning encrypted MD5Sum as ETag)

## How Has This Been Tested?

manually with awscli & minio KMS settings(MINIO_SSE_VAULT_ENDPOINT etc)[See KMS documentation)

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added unit tests to cover my changes.
- [ ] I have added/updated functional tests in [mint](https://github.com/minio/mint). (If yes, add `mint` PR # here: )
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by minio-ops** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-tls.sh | :heavy_check_mark: |
| mint-xl.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-worm.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-dist-xl.sh | :heavy_check_mark: |

**Comment by poornas** [comment]
@aead & @donatello , this is waiting on your review.

File: cmd/encryption-v1.go [hunk 1]
```diff
@@ -896,6 +913,57 @@ func (o *ObjectInfo) DecryptedSize() (int64, error) {
 	return size, nil
 }
 
+// For encrypted objects, the ETag sent by client if available
+// is stored in encrypted form in the backend.Decrypt the ETag
```
Comment (donatello) [inline cmd/encryption-v1.go]:
```suggestion
// is stored in encrypted form in the backend. Decrypt the ETag
```

It just looks like a code snippet without the space.

File: cmd/encryption-v1.go [hunk 2]
```diff
@@ -896,6 +913,57 @@ func (o *ObjectInfo) DecryptedSize() (int64, error) {
...
+		return objInfo.ETag
+	}
+	if crypto.SSECopy.IsRequested(headers) {
+		key, err = crypto.SSECopy.ParseHTTP(headers)
+		if err != nil {
+			return objInfo.ETag
+		}
+	}
+	if crypto.SSEC.IsEncrypted(objInfo.UserDefined) && !copySource {
+		return objInfo.ETag[len(objInfo.ETag)-32:]
```
Comment (donatello) [inline cmd/encryption-v1.go:936]: What is the reason for chopping up the ETag? A comment would be nice.

File: cmd/encryption-v1.go [hunk 3]
```diff
@@ -896,6 +913,57 @@ func (o *ObjectInfo) DecryptedSize() (int64, error) {
...
+	if err != nil {
+		return objInfo.ETag
+	}
+	return tryDecryptETag(objectEncryptionKey, objInfo.ETag, false)
+}
+
+// helper to decrypt Etag given object encryption key and encrypted ETag
+func tryDecryptETag(key []byte, encryptedETag string, ssec bool) string {
+	if ssec {
+		return encryptedETag[len(encryptedETag)-32:]
```
Comment (donatello) [inline cmd/encryption-v1.go:952]: Same q as above. What is meaning of dropping the first 32 bytes? It just should documented in a comment.

**Review by donatello — CHANGES_REQUESTED** [review]

File: cmd/object-api-utils.go [hunk 4]
```diff
@@ -597,3 +598,39 @@ func (g *GetObjectReader) Read(p []byte) (n int, err error) {
 	}
 	return
 }
+
+// PutObjectReader is a type that wraps sio.EncryptReader and
+// underlying hash.Reader in a struct
+type PutObjectReader struct {
+	DataReader *hash.Reader // actual data stream
+	OrigReader *hash.Reader // original data stream
```
Comment (donatello) [inline cmd/object-api-utils.go]: The two readers above are named a bit vaguely? The names need to disambiguate the semantics better.

File: cmd/object-api-utils.go [hunk 5]
```diff
@@ -597,3 +598,39 @@ func (g *GetObjectReader) Read(p []byte) (n int, err error) {
 	}
 	return
 }
+
+// PutObjectReader is a type that wraps sio.EncryptReader and
+// underlying hash.Reader in a struct
+type PutObjectReader struct {
```
Comment (donatello) [inline cmd/object-api-utils.go]: This type should not really end with the Reader suffix as it is not an `io.Reader`. Maybe `PutObjReaders` or something else.

File: cmd/object-api-utils.go [hunk 6]
```diff
@@ -597,3 +598,39 @@ func (g *GetObjectReader) Read(p []byte) (n int, err error) {
...
+func (p *PutObjectReader) Size() int64 {
+	return p.DataReader.Size()
+}
+
+// NewPutObjectReader returns a new PutObjectReader and holds
+// reference to underlying data stream from client and the encrypted
+// data reader
+func NewPutObjectReader(r *hash.Reader) *PutObjectReader {
+	return &PutObjectReader{OrigReader: r, DataReader: r}
+}
```
Comment (donatello) [inline cmd/object-api-utils.go]: To really make the purpose of this new struct `PutObjectReader` clear, all instantiation of the type should happen via constructor functions like above. This particular function looks like it applies only for un-encrypted put data?

**Review by donatello — CHANGES_REQUESTED** [review]

File: cmd/object-api-utils.go (hunk 4 above)
Comment (aead) [reply cmd/object-api-utils.go]: Maybe:
```
Plaintext *hash.Reader
Ciphertext *hash.Reader
```
?
Making it quite obvious for non-encrypted requests, too...

Comment (poornas) [reply cmd/object-api-utils.go]: @aead, DataReader could be an encrypted stream or plaintext, whereas OrigReader was plaintext. It is the DataReader that actually gets streamed, and OrigReader used only for computing MD5 of client sent content.

File: cmd/object-api-utils.go (hunk 6 above)
Comment (poornas) [reply cmd/object-api-utils.go]: It is initialized to same reader for both encrypted and plain text case. For encryption, the object encryption key is set on the OrigReader so that encrypted MD5Sum of client content can be fetched. For encryption, DataReader is changed to use the one returned by sio.EncryptReader

File: cmd/encryption-v1.go (hunk 2 above)
Comment (poornas) [reply cmd/encryption-v1.go:936]: done.

File: cmd/encryption-v1.go (hunk 3 above)
Comment (poornas) [reply cmd/encryption-v1.go:952]: done.

**Comment by minio-ops** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-tls.sh | :heavy_check_mark: |
| mint-xl.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-worm.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-dist-xl.sh | :heavy_check_mark: |

**Review by aead — COMMENTED** [review]
Code looks okay. But have to test...

**Comment by poornas** [comment]
fixed travis failure

**Comment by minio-ops** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-tls.sh | :heavy_check_mark: |
| mint-xl.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-worm.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-dist-xl.sh | :heavy_check_mark: |

**Comment by minio-ops** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-tls.sh | :heavy_check_mark: |
| mint-xl.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-worm.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-dist-xl.sh | :heavy_check_mark: |

**Comment by minio-ops** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-tls.sh | :heavy_check_mark: |
| mint-xl.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-worm.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-dist-xl.sh | :heavy_check_mark: |

**Review by donatello — DISMISSED** [review]

**Comment by harshavardhana** [comment]
Works neat

```
~  ant
Buildfile: /home/harsha/aws-sdk/java/aws-java-sdk-1.11.434/samples/AmazonS3/build.xml

run:
    [javac] /home/harsha/aws-sdk/java/aws-java-sdk-1.11.434/samples/AmazonS3/build.xml:12: warning: 'includeantruntime' was not set, defaulting to build.sysclasspath=last; set to false for repeatable builds
     [java] ===========================================
     [java] Getting Started with Amazon S3
     [java] ===========================================
     [java] 
     [java] Uploading a new object to S3 from a file
     [java] 
     [java] Downloading an object
     [java] Content-Type: text/plain
     [java]     abcdefghijklmnopqrstuvwxyz
     [java]     01234567890112345678901234
     [java]     !@#$%^&*()-=[]{};':',.<>/?
     [java]     01234567890112345678901234
     [java]     abcdefghijklmnopqrstuvwxyz
     [java] 

BUILD SUCCESSFUL
Total time: 1 second
```

```java
/*
 * Copyright 2010-2017 Amazon.com, Inc. or its affiliates. All Rights Reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License").
 * You may not use this file except in compliance with the License.
 * A copy of the License is located at
 *
 *  http://aws.amazon.com/apache2.0
 *
 * or in the "license" file accompanying this file. This file is distributed
 * on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
 * express or implied. See the License for the specific language governing
 * permissions and limitations under the License.
 */
import java.io.BufferedReader;
import java.io.File;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.InputStream;
import java.io.InputStreamReader;
import java.io.OutputStreamWriter;
import java.io.Writer;

import com.amazonaws.AmazonClientException;
import com.amazonaws.AmazonServiceException;
// For BasicAWSCredentials
import com.amazonaws.auth.AWSCredentials;
import com.amazonaws.auth.AWSStaticCredentialsProvider;
import com.amazonaws.auth.BasicAWSCredentials;
import com.amazonaws.auth.profile.ProfileCredentialsProvider;
import com.amazonaws.client.builder.AwsClientBuilder.EndpointConfiguration;
// For all S3 Clients
import com.amazonaws.services.s3.AmazonS3;
import com.amazonaws.services.s3.AmazonS3ClientBuilder;
import com.amazonaws.services.s3.model.Bucket;
import com.amazonaws.services.s3.model.GetObjectRequest;
import com.amazonaws.services.s3.model.ListObjectsRequest;
import com.amazonaws.services.s3.model.ObjectListing;
import com.amazonaws.services.s3.model.ObjectMetadata;
import com.amazonaws.services.s3.model.PutObjectRequest;
import com.amazonaws.services.s3.model.S3Object;
import com.amazonaws.services.s3.model.S3ObjectSummary;

/**
 * This sample demonstrates how to make basic requests to Amazon S3 using the AWS SDK for Java.
 *
 * <p><b>Prerequisites:</b> You must have a valid Amazon Web Services developer account, and be
 * signed up to use Amazon S3. For more information on Amazon S3, see http://aws.amazon.com/s3.
 *
 * <p>Fill in your AWS access credentials in the provided credentials file template, and be sure to
 * move the file to the default location (/Users/rwipfel/.aws/credentials) where the sample code
 * will load the credentials from.
 *
 * <p><b>WARNING:</b> To avoid accidental leakage of your credentials, DO NOT keep the credentials
 * file in your source directory.
 *
 * <p>http://aws.amazon.com/security-credentials
 */
public class S3Sample {

  public static void main(String[] args) throws IOException {

    AWSCredentials credentials = new BasicAWSCredentials("minio", "minio123");

    System.out.println("===========================================");
    System.out.println("Getting Started with Amazon S3");
    System.out.println("===========================================\n");

    AmazonS3 s3 =
        AmazonS3ClientBuilder.standard()
            .withCredentials(new AWSStaticCredentialsProvider(credentials))
            .withPathStyleAccessEnabled(true)
            .withEndpointConfiguration(
                new EndpointConfiguration("http://localhost:9000", "us-east-1"))
            .build();

    String bucketName = "vadmeste"; // "my-first-s3-bucket-" + UUID.randomUUID();
    String key = "my-objectname";

    try {
      /*
       * Create a new S3 bucket - Amazon S3 bucket names are globally unique,
       * so once a bucket name has been taken by any user, you can't create
       * another bucket with that same name.
       *
       * You can optionally specify a location for your bucket if you want to
       * keep your data closer to your applications or users.
       */

      /*
       * Upload an object to your bucket - You can easily upload a file to
       * S3, or upload directly an InputStream if you know the length of
       * the data in the stream. You can also specify your own metadata
       * when uploading to S3, which allows you set a variety of options
       * like content-type and content-encoding, plus additional metadata
       * specific to your applications.
       */
      ObjectMetadata metadata = new ObjectMetadata();
      // FIXME: Uncomment to enable SSE-S3
      // metadata.setSSEAlgorithm(ObjectMetadata.AES_256_SERVER_SIDE_ENCRYPTION);
      System.out.println("Uploading a new object to S3 from a file\n");
      s3.putObject(
          new PutObjectRequest(bucketName, key, createSampleFile()).withMetadata(metadata));

      /*
       * Download an object - When you download an object, you get all of
       * the object's metadata and a stream from which to read the contents.
       * It's important to read the contents of the stream as quickly as
       * possibly since the data is streamed directly from Amazon S3 and your
       * network connection will remain open until you read all the data or
       * close the input stream.
       *
       * GetObjectRequest also supports several other options, including
       * conditional downloading of objects based on modification times,
       * ETags, and selectively downloading a range of an object.
       */
      System.out.println("Downloading an object");
      S3Object object = s3.getObject(new GetObjectRequest(bucketName, key));
      System.out.println("Content-Type: " + object.getObjectMetadata().getContentType());
      displayTextInputStream(object.getObjectContent());

      /*
       * Delete an object - Unless versioning has been turned on for your bucket,
       * there is no way to undelete an object, so use caution when deleting objects.
       */
      // System.out.println("Deleting an object\n");
      // s3.deleteObject(bucketName, key);

      /*
       * Delete a bucket - A bucket must be completely empty before it can be
       * deleted, so remember to delete any objects from your buckets before
       * you try to delete them.
       */
      // System.out.println("Deleting bucket " + bucketName + "\n");
      // s3.deleteBucket(bucketName);
    } catch (AmazonServiceException ase) {
      System.out.println(
          "Caught an AmazonServiceException, which means your request made it "
              + "to Amazon S3, but was rejected with an error response for some reason.");
      System.out.println("Error Message:    " + ase.getMessage());
      System.out.println("HTTP Status Code: " + ase.getStatusCode());
      System.out.println("AWS Error Code:   " + ase.getErrorCode());
      System.out.println("Error Type:       " + ase.getErrorType());
      System.out.println("Request ID:       " + ase.getRequestId());
    } catch (AmazonClientException ace) {
      System.out.println(
          "Caught an AmazonClientException, which means the client encountered "
              + "a serious internal problem while trying to communicate with S3, "
              + "such as not being able to access the network.");
      System.out.println("Error Message: " + ace.getMessage());
    }
  }

  /**
   * Creates a temporary file with text data to demonstrate uploading a file to Amazon S3
   *
   * @return A newly created temporary file with text data.
   * @throws IOException
   */
  private static File createSampleFile() throws IOException {
    File file = File.createTempFile("aws-java-sdk-", ".txt");
    file.deleteOnExit();

    Writer writer = new OutputStreamWriter(new FileOutputStream(file));
    writer.write("abcdefghijklmnopqrstuvwxyz\n");
    writer.write("01234567890112345678901234\n");
    writer.write("!@#$%^&*()-=[]{};':',.<>/?\n");
    writer.write("01234567890112345678901234\n");
    writer.write("abcdefghijklmnopqrstuvwxyz\n");
    writer.close();

    return file;
  }

  /**
   * Displays the contents of the specified input stream as text.
   *
   * @param input The input stream to display as text.
   * @throws IOException
   */
  private static void displayTextInputStream(InputStream input) throws IOException {
    BufferedReader reader = new BufferedReader(new InputStreamReader(input));
    while (true) {
      String line = reader.readLine();
      if (line == null) break;

      System.out.println("    " + line);
    }
    System.out.println();
  }
}
```

**Comment by harshavardhana** [comment]
Added blocked label for some discussion with @poornas

**Comment by poornas** [comment]
@donatello  and @aead, updated PR to remove all references to encryption from object layer.

**Comment by minio-ops** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-tls.sh | :heavy_check_mark: |
| mint-xl.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-worm.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-dist-xl.sh | :heavy_check_mark: |
| mint-compression-xl.sh | :x: [more...](#08455aff-bee5-479e-9f4a-cc1fd880292d) |
| mint-compression-dist-xl.sh | :x: [more...](#bf49ec51-2e1a-479f-b468-1bc58bdc0f42) |
| mint-compression-fs.sh | :x: [more...](#7715ab5a-17c4-437f-bd47-e1bcb28122c9) |
<a name="7715ab5a-17c4-437f-bd47-e1bcb28122c9"></a>
### 6680-d73b531/mint-compression-fs.sh.log:
```
Running with
SERVER_ENDPOINT:      minikube:31551
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp d7857776cb4b:/mint/log /tmp/mint-logs'

(1/13) Running awscli tests ... FAILED in 1 minutes and 49 seconds
{
  "name": "awscli",
  "duration": 21392,
  "function": "aws --endpoint-url http://minikube:31551 s3api copy-object --bucket awscli-mint-test-bucket-22701 --key datafile-1-b-copy --copy-source awscli-mint-test-bucket-22701/datafile-1-b\n",
  "status": "FAIL",
  "error": ""
}

Executed 0 out of 13 tests successfully.
```
<a name="bf49ec51-2e1a-479f-b468-1bc58bdc0f42"></a>
### 6680-d73b531/mint-compression-dist-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      minikube:32063
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp f4437d3ee6a7:/mint/log /tmp/mint-logs'

(1/13) Running awscli tests ... FAILED in 1 minutes and 47 seconds
{
  "name": "awscli",
  "duration": 19729,
  "function": "aws --endpoint-url http://minikube:32063 s3api copy-object --bucket awscli-mint-test-bucket-8719 --key datafile-1-b-copy --copy-source awscli-mint-test-bucket-8719/datafile-1-b\n",
  "status": "FAIL",
  "error": ""
}

Executed 0 out of 13 tests successfully.
```
<a name="08455aff-bee5-479e-9f4a-cc1fd880292d"></a>
### 6680-d73b531/mint-compression-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      minikube:32375
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp d004f644ee84:/mint/log /tmp/mint-logs'

(1/13) Running awscli tests ... FAILED in 1 minutes and 44 seconds
{
  "name": "awscli",
  "duration": 19006,
  "function": "aws --endpoint-url http://minikube:32375 s3api copy-object --bucket awscli-mint-test-bucket-31361 --key datafile-1-b-copy --copy-source awscli-mint-test-bucket-31361/datafile-1-b\n",
  "status": "FAIL",
  "error": ""
}

Executed 0 out of 13 tests successfully.
```

**Comment by harshavardhana** [comment]
When compression is enabled this PR seems to be failing..

**Comment by minio-ops** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-tls.sh | :heavy_check_mark: |
| mint-xl.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-worm.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-dist-xl.sh | :heavy_check_mark: |
| mint-compression-xl.sh | :x: [more...](#dcba0e73-bf07-4b66-a57a-da48a2fbc08f) |
| mint-compression-dist-xl.sh | :x: [more...](#da154256-97a7-4692-b2c2-53fb9ae2900d) |
| mint-compression-fs.sh | :x: [more...](#155e5707-969e-4515-bebd-d98c24c993ae) |
<a name="155e5707-969e-4515-bebd-d98c24c993ae"></a>
### 6680-967eeb6/mint-compression-fs.sh.log:
```
Running with
SERVER_ENDPOINT:      minikube:31667
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp fbf9f326b79b:/mint/log /tmp/mint-logs'

(1/13) Running awscli tests ... FAILED in 1 minutes and 44 seconds
{
  "name": "awscli",
  "duration": 16929,
  "function": "aws --endpoint-url http://minikube:31667 s3api copy-object --bucket awscli-mint-test-bucket-19113 --key datafile-1-b-copy --copy-source awscli-mint-test-bucket-19113/datafile-1-b\n",
  "status": "FAIL",
  "error": ""
}

Executed 0 out of 13 tests successfully.
```
<a name="da154256-97a7-4692-b2c2-53fb9ae2900d"></a>
### 6680-967eeb6/mint-compression-dist-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      minikube:31475
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 164f5e9dcf46:/mint/log /tmp/mint-logs'

(1/13) Running awscli tests ... FAILED in 1 minutes and 43 seconds
{
  "name": "awscli",
  "duration": 12015,
  "function": "aws --endpoint-url http://minikube:31475 s3api copy-object --bucket awscli-mint-test-bucket-29033 --key datafile-1-b-copy --copy-source awscli-mint-test-bucket-29033/datafile-1-b\n",
  "status": "FAIL",
  "error": ""
}

Executed 0 out of 13 tests successfully.
```
<a name="dcba0e73-bf07-4b66-a57a-da48a2fbc08f"></a>
### 6680-967eeb6/mint-compression-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      minikube:32151
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 920b0de82057:/mint/log /tmp/mint-logs'

(1/13) Running awscli tests ... FAILED in 1 minutes and 38 seconds
{
  "name": "awscli",
  "duration": 11335,
  "function": "aws --endpoint-url http://minikube:32151 s3api copy-object --bucket awscli-mint-test-bucket-28281 --key datafile-1-b-copy --copy-source awscli-mint-test-bucket-28281/datafile-1-b\n",
  "status": "FAIL",
  "error": ""
}

Executed 0 out of 13 tests successfully.
```

**Comment by poornas** [comment]
fixed.

**Comment by minio-ops** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-tls.sh | :heavy_check_mark: |
| mint-xl.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-worm.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-dist-xl.sh | :heavy_check_mark: |
| mint-compression-xl.sh | :x: [more...](#5074c393-d936-4cc9-a783-a86f6591dfaf) |
| mint-compression-dist-xl.sh | :x: [more...](#6fcf3ef3-76a7-4a32-905d-040d4d09f42d) |
| mint-compression-fs.sh | :x: [more...](#0b5a3dab-9d21-4d5d-b0c0-1cec39dcb17e) |
<a name="6fcf3ef3-76a7-4a32-905d-040d4d09f42d"></a>
### 6680-b0e84a2/mint-compression-dist-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      minikube:31323
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 45dd45df0d04:/mint/log /tmp/mint-logs'

(1/13) Running awscli tests ... FAILED in 16 seconds
{
  "name": "awscli",
  "duration": 8357,
  "function": "make_bucket\n",
  "status": "FAIL",
  "error": "An error occurred (XMinioServerNotInitialized) when calling the CreateBucket operation (reached max retries: 4): Server not initialized, please try again."
}

Executed 0 out of 13 tests successfully.
```
<a name="5074c393-d936-4cc9-a783-a86f6591dfaf"></a>
### 6680-b0e84a2/mint-compression-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      minikube:31620
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 0f0edcc5508d:/mint/log /tmp/mint-logs'

(1/13) Running awscli tests ... FAILED in 1 minutes and 37 seconds
{
  "name": "awscli",
  "duration": 20751,
  "function": "aws --endpoint-url http://minikube:31620 s3api copy-object --bucket awscli-mint-test-bucket-27351 --key datafile-1-b-copy --copy-source awscli-mint-test-bucket-27351/datafile-1-b\n",
  "status": "FAIL",
  "error": ""
}

Executed 0 out of 13 tests successfully.
```
<a name="0b5a3dab-9d21-4d5d-b0c0-1cec39dcb17e"></a>
### 6680-b0e84a2/mint-compression-fs.sh.log:
```
Running with
SERVER_ENDPOINT:      minikube:32382
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 58ab271c0114:/mint/log /tmp/mint-logs'

(1/13) Running awscli tests ... FAILED in 1 minutes and 30 seconds
{
  "name": "awscli",
  "duration": 15033,
  "function": "aws --endpoint-url http://minikube:32382 s3api copy-object --bucket awscli-mint-test-bucket-12521 --key datafile-1-b-copy --copy-source awscli-mint-test-bucket-12521/datafile-1-b\n",
  "status": "FAIL",
  "error": ""
}

Executed 0 out of 13 tests successfully.
```

**Comment by minio-ops** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-tls.sh | :heavy_check_mark: |
| mint-compression-xl.sh | :heavy_check_mark: |
| mint-xl.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-compression-fs.sh | :heavy_check_mark: |
| mint-worm.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-dist-xl.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :x: [more...](#df77a8bd-50c0-4d6a-95a0-86381bd6c6ee) |
| mint-compression-dist-xl.sh | :x: [more...](#f68e7d35-a172-45ec-8930-5b1621077d92) |
<a name="df77a8bd-50c0-4d6a-95a0-86381bd6c6ee"></a>
### 6680-b185a92/mint-large-bucket.sh.log:
```
Running with
SERVER_ENDPOINT:      minikube:30361
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 95ebc875e8b7:/mint/log /tmp/mint-logs'

(1/13) Running awscli tests ... done in 2 minutes and 18 seconds
(2/13) Running aws-sdk-go tests ... done in 1 seconds
(3/13) Running aws-sdk-java tests ... done in 2 seconds
(4/13) Running aws-sdk-php tests ... done in 55 seconds
(5/13) Running aws-sdk-ruby tests ... done in 42 seconds
(6/13) Running mc tests ... done in 1 minutes and 46 seconds
(7/13) Running minio-dotnet tests ... FAILED in 6 minutes and 41 seconds

Unhandled Exception: System.AggregateException: One or more errors occurred. (One or more errors occurred. (Minio API responded with message=Unsuccessful response from server without XML error: The operation has timed out.) (Minio API responded with message=Unsuccessful response from server without XML error: The operation has timed out.) (Minio API responded with message=Unsuccessful response from server without XML error: The operation has timed out.) (Minio API responded with message=Unsuccessful response from server without XML error: The operation has timed out.) (Minio API responded with message=Unsuccessful response from server without XML error: The operation has timed out.) (Minio API responded with message=Unsuccessful response from server without XML error: The operation has timed out.) (Minio API responded with message=Unsuccessful response from server without XML error: The operation has timed out.) (Minio API responded with message=Unsuccessful response from server without XML error: The operation has timed out.)) ---> System.AggregateException: One or more errors occurred. (Minio API responded with message=Unsuccessful response from server without XML error: The operation has timed out.) (Minio API responded with message=Unsuccessful response from server without XML error: The operation has timed out.) (Minio API responded with message=Unsuccessful response from server without XML error: The operation has timed out.) (Minio API responded with message=Unsuccessful response from server without XML error: The operation has timed out.) (Minio API responded with message=Unsuccessful response from server without XML error: The operation has timed out.) (Minio API responded with message=Unsuccessful response from server without XML error: The operation has timed out.) (Minio API responded with message=Unsuccessful response from server without XML error: The operation has timed out.) (Minio API responded with message=Unsuccessful response from server without XML error: The operation has timed out.) ---> Minio.Exceptions.InternalClientException: Minio API responded with message=Unsuccessful response from server without XML error: The operation has timed out.
   at Minio.MinioClient.ParseError(IRestResponse response) in /q/.q/sources/minio-dotnet/Minio/MinioClient.cs:line 450
   at Minio.MinioClient.HandleIfErrorResponse(IRestResponse response, IEnumerable`1 handlers, DateTime startTime) in /q/.q/sources/minio-dotnet/Minio/MinioClient.cs:line 505
   at Minio.MinioClient.ExecuteTaskAsync(IEnumerable`1 errorHandlers, IRestRequest request, CancellationToken cancellationToken) in /q/.q/sources/minio-dotnet/Minio/MinioClient.cs:line 351
   at Minio.MinioClient.PutObjectAsync(String bucketName, String objectName, String uploadId, Int32 partNumber, Byte[] data, Dictionary`2 metaData, CancellationToken cancellationToken) in /q/.q/sources/minio-dotnet/Minio/ApiEndpoints/ObjectOperations.cs:line 483
   at Minio.MinioClient.PutObjectAsync(String bucketName, String objectName, Stream data, Int64 size, String contentType, Dictionary`2 metaData, CancellationToken cancellationToken) in /q/.q/sources/minio-dotnet/Minio/ApiEndpoints/ObjectOperations.cs:line 229
   at Minio.Functional.Tests.FunctionalTest.PutObject_Task(MinioClient minio, String bucketName, String objectName, String fileName, String contentType, Int64 size, Dictionary`2 metaData, MemoryStream mstream) in /mint/run/core/minio-dotnet/FunctionalTest.cs:line 740
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.Wait()
   at Minio.Functional.Tests.FunctionalTest.RemoveObjects_Test2(MinioClient minio) in /mint/run/core/minio-dotnet/FunctionalTest.cs:line 1738
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.Wait()
   at Minio.Functional.Tests.FunctionalTest.Main(String[] args) in /mint/run/core/minio-dotnet/FunctionalTest.cs:line 218

Executed 6 out of 13 tests successfully.
```
<a name="f68e7d35-a172-45ec-8930-5b1621077d92"></a>
### 6680-b185a92/mint-compression-dist-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      minikube:30749
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp a088af9a4772:/mint/log /tmp/mint-logs'

(1/13) Running awscli tests ... FAILED in 23 seconds
{
  "name": "awscli",
  "duration": 14951,
  "function": "make_bucket\n",
  "status": "FAIL",
  "error": "An error occurred (XMinioServerNotInitialized) when calling the CreateBucket operation (reached max retries: 4): Server not initialized, please try again."
}

Executed 0 out of 13 tests successfully.
```

**Comment by minio-ops** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-tls.sh | :heavy_check_mark: |
| mint-compression-xl.sh | :heavy_check_mark: |
| mint-xl.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-compression-dist-xl.sh | :heavy_check_mark: |
| mint-compression-fs.sh | :heavy_check_mark: |
| mint-worm.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-dist-xl.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :x: [more...](#615a37fe-4954-475c-ba9a-520b2005acdc) |
<a name="615a37fe-4954-475c-ba9a-520b2005acdc"></a>
### 6680-0d80284/mint-large-bucket.sh.log:
```
Running with
SERVER_ENDPOINT:      minikube:31863
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 840bc306d026:/mint/log /tmp/mint-logs'

(1/13) Running awscli tests ... done in 4 minutes and 20 seconds
(2/13) Running aws-sdk-go tests ... done in 6 seconds
(3/13) Running aws-sdk-java tests ... done in 7 seconds
(4/13) Running aws-sdk-php tests ... done in 1 minutes and 16 seconds
(5/13) Running aws-sdk-ruby tests ... done in 34 seconds
(6/13) Running mc tests ... done in 2 minutes and 27 seconds
(7/13) Running minio-dotnet tests ... FAILED in 6 minutes and 57 seconds

Unhandled Exception: System.AggregateException: One or more errors occurred. (One or more errors occurred. (Minio API responded with message=Unsuccessful response from server without XML error: The operation has timed out.) (Minio API responded with message=Unsuccessful response from server without XML error: The operation has timed out.) (Minio API responded with message=Unsuccessful response from server without XML error: The operation has timed out.) (Minio API responded with message=Unsuccessful response from server without XML error: The operation has timed out.) (Minio API responded with message=Unsuccessful response from server without XML error: The operation has timed out.) (Minio API responded with message=Unsuccessful response from server without XML error: The operation has timed out.) (Minio API responded with message=Unsuccessful response from server without XML error: The operation has timed out.) (Minio API responded with message=Unsuccessful response from server without XML error: The operation has timed out.) (Minio API responded with message=Unsuccessful response from server without XML error: The operation has timed out.) (Minio API responded with message=Unsuccessful response from server without XML error: The operation has timed out.) (Minio API responded with message=Unsuccessful response from server without XML error: The operation has timed out.) (Minio API responded with message=Unsuccessful response from server without XML error: The operation has timed out.) (Minio API responded with message=Unsuccessful response from server without XML error: The operation has timed out.) (Minio API responded with message=Unsuccessful response from server without XML error: The operation has timed out.) (Minio API responded with message=Unsuccessful response from server without XML error: The operation has timed out.) (Minio API responded with message=Unsuccessful response from server without XML error: The operation has timed out.) (Minio API responded with message=Unsuccessful response from server without XML error: The operation has timed out.) (Minio API responded with message=Unsuccessful response from server without XML error: The operation has timed out.) (Minio API responded with message=Unsuccessful response from server without XML error: The operation has timed out.) (Minio API responded with message=Unsuccessful response from server without XML error: The operation has timed out.) (Minio API responded with message=Unsuccessful response from server without XML error: The operation has timed out.) (Minio API responded with message=Unsuccessful response from server without XML error: The operation has timed out.) (Minio API responded with message=Unsuccessful response from server without XML error: The operation has timed out.) (Minio API responded with message=Unsuccessful response from server without XML error: The operation has timed out.) (Minio API responded with message=Unsuccessful response from server without XML error: The operation has timed out.) (Minio API responded with message=Unsuccessful response from server without XML error: The operation has timed out.) (Minio API responded with message=Unsuccessful response from server without XML error: The operation has timed out.) (Minio API responded with message=Unsuccessful response from server without XML error: The operation has timed out.) (Minio API responded with message=Unsuccessful response from server without XML error: The operation has timed out.) (Minio API responded with message=Unsuccessful response from server without XML error: The operation has timed out.) (Minio API responded with message=Unsuccessful response from server without XML error: The operation has timed out.) (Minio API responded with message=Unsuccessful response from server without XML error: The operation has timed out.) (Minio API responded with message=Unsuccessful response from server without XML error: The operation has timed out.) (Minio API responded with message=Unsuccessful response from server without XML error: The operation has timed out.) (Minio API responded with message=Unsuccessful response from server without XML error: The operation has timed out.) (Minio API responded with message=Unsuccessful response from server without XML error: The operation has timed out.) (Minio API responded with message=Unsuccessful response from server without XML error: The operation has timed out.) (Minio API responded with message=Unsuccessful response from server without XML error: The operation has timed out.) (Minio API responded with message=Unsuccessful response from server without XML error: The operation has timed out.) (Minio API responded with message=Unsuccessful response from server without XML error: The operation has timed out.) (Minio API responded with message=Unsuccessful response from server without XML error: The operation has timed out.) (Minio API responded with message=Unsuccessful response from server without XML error: The operation has timed out.) (Minio API responded with message=Unsuccessful response from server without XML error: The operation has timed out.) (Minio API responded with message=Unsuccessful response from server without XML error: The operation has timed out.) (Minio API responded with message=Unsuccessful response from server without XML error: The operation has timed out.) (Minio API responded with message=Unsuccessful response from server without XML error: The operation has timed out.) (Minio API responded with message=Unsuccessful response from server without XML error: The operation has timed out.) (Minio API responded with message=Unsuccessful response from server without XML error: The operation has timed out.) (Minio API responded with message=Unsuccessful response from server without XML error: The operation has timed out.) (Minio API responded with message=Unsuccessful response from server without XML error: The operation has timed out.) (Minio API responded with message=Unsuccessful response from server without XML error: The operation has timed out.) (Minio API responded with message=Unsuccessful response from server without XML error: The operation has timed out.) (Minio API responded with message=Unsuccessful response from server without XML error: The operation has timed out.) (Minio API responded with message=Unsuccessful response from server without XML error: The operation has timed out.) (Minio API responded with message=Unsuccessful response from server without XML error: The operation has timed out.) (Minio API responded with message=Unsuccessful response from server without XML error: The operation has timed out.) (Minio API responded with message=Unsuccessful response from server without XML error: The operation has timed out.) (Minio API responded with message=Unsuccessful response from server without XML error: The operation has timed out.) (Minio API responded with message=Unsuccessful response from server without XML error: The operation has timed out.) (Minio API responded with message=Unsuccessful response from server without XML error: The operation has timed out.) (Minio API responded with message=Unsuccessful response from server without XML error: The operation has timed out.) (Minio API responded with message=Unsuccessful response from server without XML error: The operation has timed out.) (Minio API responded with message=Unsuccessful response from server without XML error: The operation has timed out.) (Minio API responded with message=Unsuccessful response from server without XML error: The operation has timed out.) (Minio API responded with message=Unsuccessful response from server without XML error: The operation has timed out.) (Minio API responded with message=Unsuccessful response from server without XML error: The operation has timed out.) (Minio API responded with message=Unsuccessful response from server without XML error: The operation has timed out.) (Minio API responded with message=Unsuccessful response from server without XML error: The operation has timed out.) (Minio API responded with message=Unsuccessful response from server without XML error: The operation has timed out.) (Minio API responded with message=Unsuccessful response from server without XML error: The operation has timed out.) (Minio API responded with message=Unsuccessful response from server without XML error: The operation has timed out.) (Minio API responded with message=Unsuccessful response from server without XML error: The operation has timed out.) (Minio API responded with message=Unsuccessful response from server without XML error: The operation has timed out.) (Minio API responded with message=Unsuccessful response from server without XML error: The operation has timed out.) (Minio API responded with message=Unsuccessful response from server without XML error: The operation has timed out.) (Minio API responded with message=Unsuccessful response from server without XML error: The operation has timed out.) (Minio API responded with message=Unsuccessful response from server without XML error: The operation has timed out.) (Minio API responded with message=Unsuccessful response from server without XML error: The operation has timed out.) (Minio API responded with message=Unsuccessful response from server without XML error: The operation has timed out.) (Minio API responded with message=Unsuccessful response from server without XML error: The operation has timed out.) (Minio API responded with message=Unsuccessful response from server without XML error: The operation has timed out.) (Minio API responded with message=Unsuccessful response from server without XML error: The operation has timed out.) (Minio API responded with message=Unsuccessful response from server without XML error: The operation has timed out.) (Minio API responded with message=Unsuccessful response from server without XML error: The operation has timed out.) (Minio API responded with message=Unsuccessful response from server without XML error: The operation has timed out.) (Minio API responded with message=Unsuccessful response from server without XML error: The operation has timed out.) (Minio API responded with message=Unsuccessful response from server without XML error: The operation has timed out.) (Minio API responded with message=Unsuccessful response from server without XML error: The operation has timed out.) (Minio API responded with message=Unsuccessful response from server without XML error: The operation has timed out.) (Minio API responded with message=Unsuccessful response from server without XML error: The operation has timed out.) (Minio API responded with message=Unsuccessful response from server without XML error: The operation has timed out.) (Minio API responded with message=Unsuccessful response from server without XML error: The operation has timed out.) (Minio API responded with message=Unsuccessful response from server without XML error: The operation has timed out.) (Minio API responded with message=Unsuccessful response from server without XML error: The operation has timed out.) (Minio API responded with message=Unsuccessful response from server without XML error: The operation has timed out.) (Minio API responded with message=Unsuccessful response from server without XML error: The operation has timed out.) (Minio API responded with message=Unsuccessful response from server without XML error: The operation has timed out.) (Minio API responded with message=Unsuccessful response from server without XML error: The operation has timed out.) (Minio API responded with message=Unsuccessful response from server without XML error: The operation has timed out.) (Minio API responded with message=Unsuccessful response from server without XML error: The operation has timed out.) (Minio API responded with message=Unsuccessful response from server without XML error: The operation has timed out.) (Minio API responded with message=Unsuccessful response from server without XML error: The operation has timed out.) (Minio API responded with message=Unsuccessful response from server without XML error: The operation has timed out.) (Minio API responded with message=Unsuccessful response from server without XML error: The operation has timed out.) (Minio API responded with message=Unsuccessful response from server without XML error: The operation has timed out.) (Minio API responded with message=Unsuccessful response from server without XML error: The operation has timed out.) (Minio API responded with message=Unsuccessful response from server without XML error: The operation has timed out.) (Minio API responded with message=Unsuccessful response from server without XML error: The operation has timed out.) (Minio API responded with message=Unsuccessful response from server without XML error: The operation has timed out.) (Minio API responded with message=Unsuccessful response from server without XML error: The operation has timed out.) (Minio API responded with message=Unsuccessful response from server without XML error: The operation has timed out.) (Minio API responded with message=Unsuccessful response from server without XML error: The operation has timed out.) (Minio API responded with message=Unsuccessful response from server without XML error: The operation has timed out.) (Minio API responded with message=Unsuccessful response from server without XML error: The operation has timed out.) (Minio API responded with message=Unsuccessful response from server without XML error: The operation has timed out.) (Minio API responded with message=Unsuccessful response from server without XML error: The operation has timed out.) (Minio API responded with message=Unsuccessful response from server without XML error: The operation has timed out.) (Minio API responded with message=Unsuccessful response from server without XML error: The operation has timed out.) (Minio API responded with message=Unsuccessful response from server without XML error: The operation has timed out.) (Minio API responded with message=Unsuccessful response from server without XML error: The operation has timed out.) (Minio API responded with message=Unsuccessful response from server without XML error: The operation has timed out.) (Minio API responded with message=Unsuccessful response from server without XML error: The operation has timed out.) (Minio API responded with message=Unsuccessful response from server without XML error: The operation has timed out.) (Minio API responded with message=Unsuccessful response from server without XML error: The operation has timed out.) (Minio API responded with message=Unsuccessful response from server without XML error: The operation has timed out.) (Minio API responded with message=Unsuccessful response from server without XML error: The operation has timed out.) (Minio API responded with message=Unsuccessful response from server without XML error: The operation has timed out.) (Minio API responded with message=Unsuccessful response from server without XML error: The operation has timed out.) (Minio API responded with message=Unsuccessful response from server without XML error: The operation has timed out.) (Minio API responded with message=Unsuccessful response from server without XML error: The operation has timed out.) (Minio API responded with message=Unsuccessful response from server without XML error: The operation has timed out.) (Minio API responded with message=Unsuccessful response from server without XML error: The operation has timed out.) (Minio API responded with message=Unsuccessful response from server without XML error: The operation has timed out.) (Minio API responded with message=Unsuccessful response from server without XML error: The operation has timed out.) (Minio API responded with message=Unsuccessful response from server without XML error: The operation has timed out.) (Minio API responded with message=Unsuccessful response from server without XML error: The operation has timed out.) (Minio API responded with message=Unsuccessful response from server without XML error: The operation has timed out.) (Minio API responded with message=Unsuccessful response from server without XML error: The operation has timed out.) (Minio API responded with message=Unsuccessful response from server without XML error: The operation has timed out.) (Minio API responded with message=Unsuccessful response from server without XML error: The operation has timed out.) (Minio API responded with message=Unsuccessful response from server without XML error: The operation has timed out.) (Minio API responded with message=Unsuccessful response from server without XML error: The operation has timed out.)) ---> System.AggregateException: One or more errors occurred. (Minio API responded with message=Unsuccessful response from server without XML error: The operation has timed out.) (Minio API responded with message=Unsuccessful response from server without XML error: The operation has timed out.) (Minio API responded with message=Unsuccessful response from server without XML error: The operation has timed out.) (Minio API responded with message=Unsuccessful response from server without XML error: The operation has timed out.) (Minio API responded with message=Unsuccessful response from server without XML error: The operation has timed out.) (Minio API responded with message=Unsuccessful response from server without XML error: The operation has timed out.) (Minio API responded with message=Unsuccessful response from server without XML error: The operation has timed out.) (Minio API responded with message=Unsuccessful response from server without XML error: The operation has timed out.) (Minio API responded with message=Unsuccessful response from server without XML error: The operation has timed out.) (Minio API responded with message=Unsuccessful response from server without XML error: The operation has timed out.) (Minio API responded with message=Unsuccessful response from server without XML error: The operation has timed out.) (Minio API responded with message=Unsuccessful response from server without XML error: The operation has timed out.) (Minio API responded with message=Unsuccessful response from server without XML error: The operation has timed out.) (Minio API responded with message=Unsuccessful response from server without XML error: The operation has timed out.) (Minio API responded with message=Unsuccessful response from server without XML error: The operation has timed out.) (Minio API responded with message=Unsuccessful response from server without XML error: The operation has timed out.) (Minio API responded with message=Unsuccessful response from server without XML error: The operation has timed out.) (Minio API responded with message=Unsuccessful response from server without XML error: The operation has timed out.) (Minio API responded with message=Unsuccessful response from server without XML error: The operation has timed out.) (Minio API responded with message=Unsuccessful response from server without XML error: The operation has timed out.) (Minio API responded with message=Unsuccessful response from server without XML error: The operation has timed out.) (Minio API responded with message=Unsuccessful response from server without XML error: The operation has timed out.) (Minio API responded with message=Unsuccessful response from server without XML error: The operation has timed out.) (Minio API responded with message=Unsuccessful response from server without XML error: The operation has timed out.) (Minio API responded with message=Unsuccessful response from server without XML error: The operation has timed out.) (Minio API responded with message=Unsuccessful response from server without XML error: The operation has timed out.) (Minio API responded with message=Unsuccessful response from server without XML error: The operation has timed out.) (Minio API responded with message=Unsuccessful response from server without XML error: The operation has timed out.) (Minio API responded with message=Unsuccessful response from server without XML error: The operation has timed out.) (Minio API responded with message=Unsuccessful response from server without XML error: The operation has timed out.) (Minio API responded with message=Unsuccessful response from server without XML error: The operation has timed out.) (Minio API responded with message=Unsuccessful response from server without XML error: The operation has timed out.) (Minio API responded with message=Unsuccessful response from server without XML error: The operation has timed out.) (Minio API responded with message=Unsuccessful response from server without XML error: The operation has timed out.) (Minio API responded with message=Unsuccessful response from server without XML error: The operation has timed out.) (Minio API responded with message=Unsuccessful response from server without XML error: The operation has timed out.) (Minio API responded with message=Unsuccessful response from server without XML error: The operation has timed out.) (Minio API responded with message=Unsuccessful response from server without XML error: The operation has timed out.) (Minio API responded with message=Unsuccessful response from server without XML error: The operation has timed out.) (Minio API responded with message=Unsuccessful response from server without XML error: The operation has timed out.) (Minio API responded with message=Unsuccessful response from server without XML error: The operation has timed out.) (Minio API responded with message=Unsuccessful response from server without XML error: The operation has timed out.) (Minio API responded with message=Unsuccessful response from server without XML error: The operation has timed out.) (Minio API responded with message=Unsuccessful response from server without XML error: The operation has timed out.) (Minio API responded with message=Unsuccessful response from server without XML error: The operation has timed out.) (Minio API responded with message=Unsuccessful response from server without XML error: The operation has timed out.) (Minio API responded with message=Unsuccessful response from server without XML error: The operation has timed out.) (Minio API responded with message=Unsuccessful response from server without XML error: The operation has timed out.) (Minio API responded with message=Unsuccessful response from server without XML error: The operation has timed out.) (Minio API responded with message=Unsuccessful response from server without XML error: The operation has timed out.) (Minio API responded with message=Unsuccessful response from server without XML error: The operation has timed out.) (Minio API responded with message=Unsuccessful response from server without XML error: The operation has timed out.) (Minio API responded with message=Unsuccessful response from server without XML error: The operation has timed out.) (Minio API responded with message=Unsuccessful response from server without XML error: The operation has timed out.) (Minio API responded with message=Unsuccessful response from server without XML error: The operation has timed out.) (Minio API responded with message=Unsuccessful response from server without XML error: The operation has timed out.) (Minio API responded with message=Unsuccessful response from server without XML error: The operation has timed out.) (Minio API responded with message=Unsuccessful response from server without XML error: The operation has timed out.) (Minio API responded with message=Unsuccessful response from server without XML error: The operation has timed out.) (Minio API responded with message=Unsuccessful response from server without XML error: The operation has timed out.) (Minio API responded with message=Unsuccessful response from server without XML error: The operation has timed out.) (Minio API responded with message=Unsuccessful response from server without XML error: The operation has timed out.) (Minio API responded with message=Unsuccessful response from server without XML error: The operation has timed out.) (Minio API responded with message=Unsuccessful response from server without XML error: The operation has timed out.) (Minio API responded with message=Unsuccessful response from server without XML error: The operation has timed out.) (Minio API responded with message=Unsuccessful response from server without XML error: The operation has timed out.) (Minio API responded with message=Unsuccessful response from server without XML error: The operation has timed out.) (Minio API responded with message=Unsuccessful response from server without XML error: The operation has timed out.) (Minio API responded with message=Unsuccessful response from server without XML error: The operation has timed out.) (Minio API responded with message=Unsuccessful response from server without XML error: The operation has timed out.) (Minio API responded with message=Unsuccessful response from server without XML error: The operation has timed out.) (Minio API responded with message=Unsuccessful response from server without XML error: The operation has timed out.) (Minio API responded with message=Unsuccessful response from server without XML error: The operation has timed out.) (Minio API responded with message=Unsuccessful response from server without XML error: The operation has timed out.) (Minio API responded with message=Unsuccessful response from server without XML error: The operation has timed out.) (Minio API responded with message=Unsuccessful response from server without XML error: The operation has timed out.) (Minio API responded with message=Unsuccessful response from server without XML error: The operation has timed out.) (Minio API responded with message=Unsuccessful response from server without XML error: The operation has timed out.) (Minio API responded with message=Unsuccessful response from server without XML error: The operation has timed out.) (Minio API responded with message=Unsuccessful response from server without XML error: The operation has timed out.) (Minio API responded with message=Unsuccessful response from server without XML error: The operation has timed out.) (Minio API responded with message=Unsuccessful response from server without XML error: The operation has timed out.) (Minio API responded with message=Unsuccessful response from server without XML error: The operation has timed out.) (Minio API responded with message=Unsuccessful response from server without XML error: The operation has timed out.) (Minio API responded with message=Unsuccessful response from server without XML error: The operation has timed out.) (Minio API responded with message=Unsuccessful response from server without XML error: The operation has timed out.) (Minio API responded with message=Unsuccessful response from server without XML error: The operation has timed out.) (Minio API responded with message=Unsuccessful response from server without XML error: The operation has timed out.) (Minio API responded with message=Unsuccessful response from server without XML error: The operation has timed out.) (Minio API responded with message=Unsuccessful response from server without XML error: The operation has timed out.) (Minio API responded with message=Unsuccessful response from server without XML error: The operation has timed out.) (Minio API responded with message=Unsuccessful response from server without XML error: The operation has timed out.) (Minio API responded with message=Unsuccessful response from server without XML error: The operation has timed out.) (Minio API responded with message=Unsuccessful response from server without XML error: The operation has timed out.) (Minio API responded with message=Unsuccessful response from server without XML error: The operation has timed out.) (Minio API responded with message=Unsuccessful response from server without XML error: The operation has timed out.) (Minio API responded with message=Unsuccessful response from server without XML error: The operation has timed out.) (Minio API responded with message=Unsuccessful response from server without XML error: The operation has timed out.) (Minio API responded with message=Unsuccessful response from server without XML error: The operation has timed out.) (Minio API responded with message=Unsuccessful response from server without XML error: The operation has timed out.) (Minio API responded with message=Unsuccessful response from server without XML error: The operation has timed out.) (Minio API responded with message=Unsuccessful response from server without XML error: The operation has timed out.) (Minio API responded with message=Unsuccessful response from server without XML error: The operation has timed out.) (Minio API responded with message=Unsuccessful response from server without XML error: The operation has timed out.) (Minio API responded with message=Unsuccessful response from server without XML error: The operation has timed out.) (Minio API responded with message=Unsuccessful response from server without XML error: The operation has timed out.) (Minio API responded with message=Unsuccessful response from server without XML error: The operation has timed out.) (Minio API responded with message=Unsuccessful response from server without XML error: The operation has timed out.) (Minio API responded with message=Unsuccessful response from server without XML error: The operation has timed out.) (Minio API responded with message=Unsuccessful response from server without XML error: The operation has timed out.) (Minio API responded with message=Unsuccessful response from server without XML error: The operation has timed out.) (Minio API responded with message=Unsuccessful response from server without XML error: The operation has timed out.) (Minio API responded with message=Unsuccessful response from server without XML error: The operation has timed out.) (Minio API responded with message=Unsuccessful response from server without XML error: The operation has timed out.) (Minio API responded with message=Unsuccessful response from server without XML error: The operation has timed out.) (Minio API responded with message=Unsuccessful response from server without XML error: The operation has timed out.) (Minio API responded with message=Unsuccessful response from server without XML error: The operation has timed out.) (Minio API responded with message=Unsuccessful response from server without XML error: The operation has timed out.) (Minio API responded with message=Unsuccessful response from server without XML error: The operation has timed out.) (Minio API responded with message=Unsuccessful response from server without XML error: The operation has timed out.) (Minio API responded with message=Unsuccessful response from server without XML error: The operation has timed out.) (Minio API responded with message=Unsuccessful response from server without XML error: The operation has timed out.) (Minio API responded with message=Unsuccessful response from server without XML error: The operation has timed out.) (Minio API responded with message=Unsuccessful response from server without XML error: The operation has timed out.) (Minio API responded with message=Unsuccessful response from server without XML error: The operation has timed out.) (Minio API responded with message=Unsuccessful response from server without XML error: The operation has timed out.) (Minio API responded with message=Unsuccessful response from server without XML error: The operation has timed out.) (Minio API responded with message=Unsuccessful response from server without XML error: The operation has timed out.) (Minio API responded with message=Unsuccessful response from server without XML error: The operation has timed out.) (Minio API responded with message=Unsuccessful response from server without XML error: The operation has timed out.) (Minio API responded with message=Unsuccessful response from server without XML error: The operation has timed out.) (Minio API responded with message=Unsuccessful response from server without XML error: The operation has timed out.) (Minio API responded with message=Unsuccessful response from server without XML error: The operation has timed out.) (Minio API responded with message=Unsuccessful response from server without XML error: The operation has timed out.) (Minio API responded with message=Unsuccessful response from server without XML error: The operation has timed out.) (Minio API responded with message=Unsuccessful response from server without XML error: The operation has timed out.) (Minio API responded with message=Unsuccessful response from server without XML error: The operation has timed out.) (Minio API responded with message=Unsuccessful response from server without XML error: The operation has timed out.) (Minio API responded with message=Unsuccessful response from server without XML error: The operation has timed out.) (Minio API responded with message=Unsuccessful response from server without XML error: The operation has timed out.) (Minio API responded with message=Unsuccessful response from server without XML error: The operation has timed out.) (Minio API responded with message=Unsuccessful response from server without XML error: The operation has timed out.) ---> Minio.Exceptions.InternalClientException: Minio API responded with message=Unsuccessful response from server without XML error: The operation has timed out.
   at Minio.MinioClient.ParseError(IRestResponse response) in /q/.q/sources/minio-dotnet/Minio/MinioClient.cs:line 450
   at Minio.MinioClient.HandleIfErrorResponse(IRestResponse response, IEnumerable`1 handlers, DateTime startTime) in /q/.q/sources/minio-dotnet/Minio/MinioClient.cs:line 505
   at Minio.MinioClient.ExecuteTaskAsync(IEnumerable`1 errorHandlers, IRestRequest request, CancellationToken cancellationToken) in /q/.q/sources/minio-dotnet/Minio/MinioClient.cs:line 351
   at Minio.MinioClient.PutObjectAsync(String bucketName, String objectName, String uploadId, Int32 partNumber, Byte[] data, Dictionary`2 metaData, CancellationToken cancellationToken) in /q/.q/sources/minio-dotnet/Minio/ApiEndpoints/ObjectOperations.cs:line 483
   at Minio.MinioClient.PutObjectAsync(String bucketName, String objectName, Stream data, Int64 size, String contentType, Dictionary`2 metaData, CancellationToken cancellationToken) in /q/.q/sources/minio-dotnet/Minio/ApiEndpoints/ObjectOperations.cs:line 229
   at Minio.Functional.Tests.FunctionalTest.PutObject_Task(MinioClient minio, String bucketName, String objectName, String fileName, String contentType, Int64 size, Dictionary`2 metaData, MemoryStream mstream) in /mint/run/core/minio-dotnet/FunctionalTest.cs:line 740
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.Wait()
   at Minio.Functional.Tests.FunctionalTest.RemoveObjects_Test2(MinioClient minio) in /mint/run/core/minio-dotnet/FunctionalTest.cs:line 1738
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.Wait()
   at Minio.Functional.Tests.FunctionalTest.Main(String[] args) in /mint/run/core/minio-dotnet/FunctionalTest.cs:line 218

Executed 6 out of 13 tests successfully.
```

**Comment by minio-ops** [comment]
```
Error running mint automation
+ mkdir -p 6680-d09ef82/gopath/src/github.com/minio
+ git clone --quiet https://github.com/minio/minio.git 6680-d09ef82/gopath/src/github.com/minio/minio
++ cd 6680-d09ef82/gopath/src/github.com/minio/minio
++ git remote add minio https://github.com/minio/minio.git
++ cd 6680-d09ef82/gopath/src/github.com/minio/minio
++ git fetch --quiet minio pull/6680/head:pr6680
++ cd 6680-d09ef82/gopath/src/github.com/minio/minio
++ git checkout --quiet pr6680
++ minikube ip
+ minikube_ip=192.168.39.64
++ mkdir -p certs
++ cd certs
++ ./cert -host 192.168.39.64
2018/11/12 13:38:41 wrote public.crt
2018/11/12 13:38:41 wrote private.key
+ GOPATH=/mnt/nvme0n1p1/mint-auto/mint-auto/6680-d09ef82/gopath
+ make -C 6680-d09ef82/gopath/src/github.com/minio/minio --quiet
# github.com/minio/minio/cmd
cmd/gateway-unsupported.go:46:1: syntax error: non-declaration statement outside function body
cmd/gateway-unsupported.go:48:1: syntax error: unexpected ==, expecting }
cmd/gateway-unsupported.go:51:1: syntax error: unexpected >>, expecting }
make: *** [build] Error 2

```

**Comment by poornas** [comment]
rebased PR.

File: cmd/encryption-v1.go [hunk 7]
```diff
@@ -909,6 +906,64 @@ func (o *ObjectInfo) DecryptedSize() (int64, error) {
...
+	if crypto.SSECopy.IsRequested(headers) {
+		key, err = crypto.SSECopy.ParseHTTP(headers)
+		if err != nil {
+			return objInfo.ETag
+		}
+	}
+	// As per AWS S3 Spec, ETag for SSE-C encrypted objects need not be MD5Sum of the data.
+	// Since server side copy with same source and dest just replaces the ETag, we save
+	// encrypted content MD5Sum as ETag for both SSE-C and SSE-S3, we standardize the ETag
+	//encryption across SSE-C and SSE-C, and only return last 32 bytes for SSE-C
```
Comment (aead) [inline cmd/encryption-v1.go]: typo: 2x SSE-C

**Comment by minio-ops** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-tls.sh | :heavy_check_mark: |
| mint-compression-xl.sh | :heavy_check_mark: |
| mint-xl.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-compression-fs.sh | :heavy_check_mark: |
| mint-worm.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-dist-xl.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :x: [more...](#75470fc9-2c85-4e89-a3bf-b48e50348cbf) |
<a name="75470fc9-2c85-4e89-a3bf-b48e50348cbf"></a>
### 6680-eec9410/mint-large-bucket.sh.log:
```
Running with
SERVER_ENDPOINT:      minikube:30703
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp a42b2b895fc6:/mint/log /tmp/mint-logs'

(1/13) Running awscli tests ... done in 1 minutes and 54 seconds
(2/13) Running aws-sdk-go tests ... done in 2 seconds
(3/13) Running aws-sdk-java tests ... done in 2 seconds
(4/13) Running aws-sdk-php tests ... done in 54 seconds
(5/13) Running aws-sdk-ruby tests ... done in 41 seconds
(6/13) Running mc tests ... done in 1 minutes and 50 seconds
(7/13) Running minio-dotnet tests ... FAILED in 6 minutes and 19 seconds

Unhandled Exception: System.AggregateException: One or more errors occurred. (One or more errors occurred. (Minio API responded with message=Please reduce your request) (Minio API responded with message=Unsuccessful response from server without XML error: The operation has timed out.)) ---> System.AggregateException: One or more errors occurred. (Minio API responded with message=Please reduce your request) (Minio API responded with message=Unsuccessful response from server without XML error: The operation has timed out.) ---> Minio.Exceptions.MinioException: Minio API responded with message=Please reduce your request
   at Minio.MinioClient.ParseError(IRestResponse response) in /q/.q/sources/minio-dotnet/Minio/MinioClient.cs:line 363
   at Minio.MinioClient.HandleIfErrorResponse(IRestResponse response, IEnumerable`1 handlers, DateTime startTime) in /q/.q/sources/minio-dotnet/Minio/MinioClient.cs:line 505
   at Minio.MinioClient.ExecuteTaskAsync(IEnumerable`1 errorHandlers, IRestRequest request, CancellationToken cancellationToken) in /q/.q/sources/minio-dotnet/Minio/MinioClient.cs:line 351
   at Minio.MinioClient.PutObjectAsync(String bucketName, String objectName, String uploadId, Int32 partNumber, Byte[] data, Dictionary`2 metaData, CancellationToken cancellationToken) in /q/.q/sources/minio-dotnet/Minio/ApiEndpoints/ObjectOperations.cs:line 483
   at Minio.MinioClient.PutObjectAsync(String bucketName, String objectName, Stream data, Int64 size, String contentType, Dictionary`2 metaData, CancellationToken cancellationToken) in /q/.q/sources/minio-dotnet/Minio/ApiEndpoints/ObjectOperations.cs:line 229
   at Minio.Functional.Tests.FunctionalTest.PutObject_Task(MinioClient minio, String bucketName, String objectName, String fileName, String contentType, Int64 size, Dictionary`2 metaData, MemoryStream mstream) in /mint/run/core/minio-dotnet/FunctionalTest.cs:line 740
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.Wait()
   at Minio.Functional.Tests.FunctionalTest.RemoveObjects_Test2(MinioClient minio) in /mint/run/core/minio-dotnet/FunctionalTest.cs:line 1738
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.Wait()
   at Minio.Functional.Tests.FunctionalTest.Main(String[] args) in /mint/run/core/minio-dotnet/FunctionalTest.cs:line 218

Executed 6 out of 13 tests successfully.
```

**Review by aead — DISMISSED** [review]
LGTM - only thing is a small typo

File: cmd/encryption-v1.go (hunk 7 above)
Comment (poornas) [reply cmd/encryption-v1.go]: fixed.

**Review by aead — DISMISSED** [review]

**Comment by minio-ops** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-tls.sh | :heavy_check_mark: |
| mint-compression-xl.sh | :heavy_check_mark: |
| mint-xl.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-compression-fs.sh | :heavy_check_mark: |
| mint-worm.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-dist-xl.sh | :heavy_check_mark: |

File: cmd/object-api-utils.go [hunk 8]
```diff
@@ -597,3 +599,61 @@ func (g *GetObjectReader) Read(p []byte) (n int, err error) {
...
 	return
 }
+
+//SealMD5CurrFn seals md5sum with object encryption key and returns sealed
+// md5sum
+type SealMD5CurrFn func([]byte) []byte
+
+// PutObjReaders is a type that wraps sio.EncryptReader and
+// underlying hash.Reader in a struct
+type PutObjReaders struct {
```
Comment (donatello) [inline cmd/object-api-utils.go]: Now that this type has a io.Reader interface, the name should be `PutObjReader` IMO.

**Review by donatello — CHANGES_REQUESTED** [review]

**Comment by donatello** [comment]
Also build is failing.

File: cmd/object-api-utils.go (hunk 8 above)
Comment (poornas) [reply cmd/object-api-utils.go]: done.

**Comment by minio-ops** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-tls.sh | :heavy_check_mark: |
| mint-compression-xl.sh | :heavy_check_mark: |
| mint-xl.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-compression-fs.sh | :heavy_check_mark: |
| mint-worm.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-dist-xl.sh | :heavy_check_mark: |

**Comment by poornas** [comment]
ping @donatello and @aead - fixed review comments

File: cmd/object-api-utils.go [hunk 9]
```diff
@@ -597,3 +599,61 @@ func (g *GetObjectReader) Read(p []byte) (n int, err error) {
...
+
+// NewPutObjReader returns a new PutObjReader and holds
+// reference to underlying data stream from client and the encrypted
+// data reader
+func NewPutObjReader(rawReader *hash.Reader, encReader *hash.Reader, encKey []byte) *PutObjReader {
+	p := PutObjReader{Reader: rawReader, rawReader: rawReader}
+
+	var objKey crypto.ObjectKey
+	copy(objKey[:], encKey)
+	p.sealMD5Fn = sealETagFn(objKey)
```
Comment (donatello) [inline cmd/object-api-utils.go:640]: sealETagFn can probably be inlined and eliminated - not sure if it's needed for any other purpose.

**Review by donatello — APPROVED** [review]
LGTM - have a minor comment.

**Review by aead — APPROVED** [review]
