### PR TITLE
fix: veeam SOS API 'system.xml' strings

### LINKED ISSUE #17195: SOS API (Veeam) system.xml is not compatible with Veeam
## Expected Behavior

Veeam recognizes MinIO as providing SOS API, but it does not.

## Current Behavior

Manually requesting the system.xml object works, but there are some errors in it, which is why Veeam does not accept it.

## Possible Solution

<div class="table-wrap">

XML Tag | Change | Description
-- | -- | --
ProtocolVersion | add enclosing double quotes | That's how it is described in the documentation and it's not working without it.
ModelName | add enclosing double quotes | That's how it is described in the documentation and recommended by Veeam (even if it is currently working without it).
APIEndpoints | remove this tag including subtags | The tag is optional. Since IAM and STS processing is not supported it should be removed.
SystemRecommendations | remove this tag including subtags | The tag is optional and should not be there, unless there are differences in Veeam defaults that have been previously discussed with Veeam.

</div>

<p></p>

I'll submit a pull request.

## Steps to Reproduce (for bugs)

1. Follow "Appendix C: Manual plug-in load test" of the "Veeam Smart Object Storage API SOSAPI v1.0" available in the Veeam partner portal
2. Notice that in the last step "If everything was implemented correctly you will the capacity information when you create a new backup job" does not work i.e. no capacity is displayed.

After the changes I propose, the capacity is displayed correctly.

## Your Environment

* Version used (`minio --version`): RELEASE.2023-05-04T21-44-30Z
* Server setup and configuration:
* Operating System and version (`uname -a`):

### PR DESCRIPTION
**Pull request by harshavardhana**
## Description
fix: veeam SOS API 'system.xml' strings

## Motivation and Context
fixes #17195

The system.xml should look like this:

```
    <?xml version="1.0" encoding="UTF-8"?>
    <SystemInfo>
      <ProtocolVersion>"1.0"</ProtocolVersion>
      <ModelName>"MinIO RELEASE.2023-04-28T18-11-17Z"</ModelName>
    </SystemInfo>
```

Original-Author: Omar Kohl <omarkohl@posteo.net>

We should keep the KBBlockSize value to 4MiB.

## How to test this PR?
Needs Veeam SOS API support

## Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Optimization (provides speedup with no functional changes)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [ ] Fixes a regression (If yes, please add `commit-id` or `PR #` here)
- [ ] Unit tests added/updated
- [ ] Internal documentation updated
- [ ] Create a documentation update request [here](https://github.com/minio/docs/issues/new?label=doc-change,title=Doc+Updated+Needed+For+PR+github.com%2fminio%2fminio%2fpull%2fNNNNN)

### CODE REVIEW

File: cmd/veeam-sos-api.go [hunk 1]
```diff
@@ -118,8 +120,8 @@ func veeamSOSAPIGetObject(ctx context.Context, bucket, object string, rs *HTTPRa
 	switch object {
 	case systemXMLObject:
 		si := systemInfo{
-			ProtocolVersion: "1.0",
-			ModelName:       "MinIO " + ReleaseTag,
+			ProtocolVersion: `"1.0"`,
+			ModelName:       "\"MinIO \"" + ReleaseTag + "\"",
```
Comment (vadmeste) [inline cmd/veeam-sos-api.go]: There are three double quotes here, it doesn't look right

**Review by vadmeste — CHANGES_REQUESTED** [review]

File: cmd/veeam-sos-api.go (hunk 1 above)
Comment (harshavardhana) [inline cmd/veeam-sos-api.go]:
```suggestion
			ModelName:       "\"MinIO " + ReleaseTag + "\"",
```

Comment (harshavardhana) [reply cmd/veeam-sos-api.go]: Yeah it's fixed.

**Review by vadmeste — APPROVED** [review]
LGTM

**Review by krisis — APPROVED** [review]
