### PR TITLE
Cleanup - Comments and readability fixes

### LINKED ISSUE #1369: tests: Add comments
Listing code readability issues, will be fixed in a while. 
- https://github.com/minio/minio/blob/master/fs.go#L485 , ENOTDIR can be used. 
- https://github.com/minio/minio/blob/master/object-utils_test.go , some comments need spaces in after // and full stop at the end.
- Needs comments for the tests here. https://github.com/minio/minio/blob/master/object_api_suite_test.go
- full stop at the end of comments for object-errors.go
- https://github.com/minio/minio/blob/master/object-errors.go#L76 , added a break after Bad digest. The error message on console without a break is less readable. 

Will be stacking up more before the fixes are sent.

### PR DESCRIPTION
**Pull request by hackintoshrao**
- Fixes #1369 
- Adding `isBucketExist` check to `PutObject` . 
- Few more assertions added object API suite.

### CODE REVIEW

File: object_api_suite_test.go [hunk 1]
```diff
@@ -281,20 +288,29 @@ func testObjectOverwriteWorks(c *check.C, create func() objectAPI) {
 	c.Assert(r.Close(), check.IsNil)
 }
 
+// Tests validate that bucket operation on non-existent bucket fails.
 func testNonExistantBucketOperations(c *check.C, create func() objectAPI) {
 	obj := create()
 	_, err := obj.PutObject("bucket1", "object", int64(len("one")), bytes.NewBufferString("one"), nil)
 	c.Assert(err, check.Not(check.IsNil))
+	/*
+		c.Assert(err.ToGoError().Error(), check.Equals, "Bucket not found: bucket1")
```
Comment (harshavardhana) [inline object_api_suite_test.go]: what is this for?

File: object_api_suite_test.go [hunk 2]
```diff
@@ -281,20 +288,29 @@ func testObjectOverwriteWorks(c *check.C, create func() objectAPI) {
...
 
+// Tests validate that recreation of the bucket fails.
 func testBucketRecreateFails(c *check.C, create func() objectAPI) {
 	obj := create()
 	err := obj.MakeBucket("string")
 	c.Assert(err, check.IsNil)
 	err = obj.MakeBucket("string")
 	c.Assert(err, check.Not(check.IsNil))
+	/*
+		c.Assert(err.ToGoError().Error(), check.Equals, "Bucket exists: string")
```
Comment (harshavardhana) [inline object_api_suite_test.go]: why commented?
