### PR TITLE
lock: improve locker initialization at init

### LINKED ISSUE #8773: Fallback to safe mode when quorum disks hosting config.json are unavailable
## Expected Behavior
.minio.sys/config/config.json is stored in a particular erasure set. If quorum disks of that particular erasure set are not available, the cluster still needs to be online, so at least we can fix it (by healing it).

## Current Behavior
Nodes of that cluster are frozen.

## Possible Solution
Fallback to safe mode

## Steps to Reproduce (for bugs)
1. 
2.
3.
4.

## Your Environment

* Version used (`minio version`):
* Environment name and version (e.g. nginx 1.9.1):
* Server type and version:
* Operating System and version (`uname -a`):
* Link to your project:

### PR DESCRIPTION
**Pull request by harshavardhana**
## Description
lock: improve locker initialization at init

## Motivation and Context
Use reference format to initialize lockers
during startup, also handle `nil` for NetLocker
in dsync and remove *errorLocker* implementation

Add further tuning parameters such as

 - DialTimeout is now 15 seconds from 30 seconds
 - KeepAliveTimeout is not 20 seconds, 5 seconds
   more than default 15 seconds
 - ResponseHeaderTimeout to 10 seconds
 - ExpectContinueTimeout is reduced to 3 seconds
 - DualStack is enabled by default remove setting
   it to `true`
 - Reduce IdleConnTimeout to 30 seconds from
   1 minute to avoid idleConn build-up

Fixes #8773

## How to test this PR?
Thanks to @vadmeste for this reproducer
```sh
#!/bin/bash
​
MINIO_BINARY=minio
NODES_COUNT=3
TMP_BACKEND="tmp-backend"
​
start_minio() {
    ARGS=()
​
    for i in $(seq 1 $NODES_COUNT); do
        ARGS+=("http://minio:$[9000+$i]/tmp/$TMP_BACKEND/$i/1/ http://minio:$[9000+$i]/tmp/$TMP_BACKEND/$i/2/ http://minio:$[9000+$i]/tmp/$TMP_BACKEND/$i/3/ http://minio:$[9000+$i]/tmp/$TMP_BACKEND/$i/4/ http://minio:$[9000+$i]/tmp/$TMP_BACKEND/$i/5/ http://minio:$[9000+$i]/tmp/$TMP_BACKEND/$i/6/ ")
    done
​
    for i in $(seq 1 $NODES_COUNT); do
        $MINIO_BINARY server --address ":$[9000+$i]" ${ARGS[@]} &
    done
}
​
kill_minio() {
    killall -9 minio
}
​
​
kill_minio
rm -rf /tmp/$TMP_BACKEND/*
​
start_minio
​
sleep 10
​
echo ""
echo "Remove the contents of the disks belonging to the first erasuere set"
echo ""
​
killall minio
​
rm -rf /tmp/$TMP_BACKEND/2/*/
​
start_minio
```

## Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [x] Fixes a regression yes this is true from the set based locker change
- [ ] Documentation needed
- [x] Unit tests needed
- [ ] Functional tests needed (If yes, add [mint](https://github.com/minio/mint) PR # here: )

### CODE REVIEW

**Comment by minio-ops** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-compression-xl.sh | :heavy_check_mark: |
| mint-xl.sh | :heavy_check_mark: |
| mint-compression-fs.sh | :heavy_check_mark: |
| mint-worm.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :x: [more...](#2023d72a-ea0a-4842-a205-3dcc43dab0c0) |
| mint-compression-dist-xl.sh | :x: [more...](#51755a43-2ac8-4431-96f3-5d0d0ed66fff) |
| mint-fs.sh | :x: [more...](#d7e58861-3474-4730-a680-a8fff8038287) |
| mint-dist-xl.sh | :x: [more...](#b757c44a-1365-4ad2-bfba-1330da094fb6) |
<a name="b757c44a-1365-4ad2-bfba-1330da094fb6"></a>
### 8776-90163f2/mint-dist-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.58:30857
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp fa6ae04a6dd6:/mint/log /tmp/mint-logs'

(1/13) Running awscli tests ... FAILED in 11 seconds
{
  "name": "awscli",
  "duration": 8754,
  "function": "make_bucket\n",
  "status": "FAIL",
  "error": "An error occurred (XMinioServerNotInitialized) when calling the CreateBucket operation (reached max retries: 4): Server not initialized, please try again."
}

Executed 0 out of 13 tests successfully.
```
<a name="d7e58861-3474-4730-a680-a8fff8038287"></a>
### 8776-90163f2/mint-fs.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.55:30752
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 64d4633bdd0f:/mint/log /tmp/mint-logs'

(1/13) Running awscli tests ... FAILED in 5 minutes and 6 seconds
{"name": "awscli", "duration": 304523, "function": "make_bucket\n", "status": "FAIL", "error": "Connect timeout on endpoint URL: "http://72.28.97.55:30752/awscli-mint-test-bucket-24445""}

Executed 0 out of 13 tests successfully.
```
<a name="2023d72a-ea0a-4842-a205-3dcc43dab0c0"></a>
### 8776-90163f2/mint-large-bucket.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.61:32554
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp a79cad0d5d5c:/mint/log /tmp/mint-logs'

(1/13) Running awscli tests ... FAILED in 10 seconds
{
  "name": "awscli",
  "duration": 8162,
  "function": "make_bucket\n",
  "status": "FAIL",
  "error": "An error occurred (XMinioServerNotInitialized) when calling the CreateBucket operation (reached max retries: 4): Server not initialized, please try again."
}

Executed 0 out of 13 tests successfully.
```
<a name="51755a43-2ac8-4431-96f3-5d0d0ed66fff"></a>
### 8776-90163f2/mint-compression-dist-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.59:32263
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp fd3390106ce1:/mint/log /tmp/mint-logs'

(1/13) Running awscli tests ... FAILED in 12 seconds
{
  "name": "awscli",
  "duration": 9266,
  "function": "make_bucket\n",
  "status": "FAIL",
  "error": "An error occurred (XMinioServerNotInitialized) when calling the CreateBucket operation (reached max retries: 4): Server not initialized, please try again."
}

Executed 0 out of 13 tests successfully.
```
Deleting image on docker hub
Deleting image locally

**Comment by minio-ops** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-compression-xl.sh | :heavy_check_mark: |
| mint-compression-dist-xl.sh | :heavy_check_mark: |
| mint-compression-fs.sh | :heavy_check_mark: |
| mint-worm.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-dist-xl.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-xl.sh | :x: [more...](#7fa153b5-c6f4-4e4c-81df-db0bee76e2e6) |
| mint-large-bucket.sh | :x: [more...](#14773d5b-d00e-48a4-956f-751e15a076c5) |
<a name="7fa153b5-c6f4-4e4c-81df-db0bee76e2e6"></a>
### 8776-6e202be/mint-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.55:31207
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp bc0997784c27:/mint/log /tmp/mint-logs'

(1/13) Running awscli tests ... FAILED in 5 minutes and 10 seconds
{"name": "awscli", "duration": 308036, "function": "make_bucket\n", "status": "FAIL", "error": "Connect timeout on endpoint URL: "http://72.28.97.55:31207/awscli-mint-test-bucket-26336""}

Executed 0 out of 13 tests successfully.
```
<a name="14773d5b-d00e-48a4-956f-751e15a076c5"></a>
### 8776-6e202be/mint-large-bucket.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.56:31858
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 9c16c89b2ee6:/mint/log /tmp/mint-logs'

(1/13) Running awscli tests ... done in 2 minutes and 21 seconds
(2/13) Running aws-sdk-java tests ... done in 1 seconds
(3/13) Running aws-sdk-ruby tests ... done in 6 seconds
(4/13) Running mc tests ... done in 1 minutes and 22 seconds
(5/13) Running minio-go tests ... FAILED in 2 minutes and 3 seconds
{
  "args": {
    "bucketName": "minio-go-test-p49qga9arrn1soay",
    "ctx": {
      "Context": 0
    },
    "objectName": "test-file-2017618716",
    "opts": {
      "UserMetadata": null,
      "Progress": null,
      "ContentType": "binary/octet-stream",
      "ContentEncoding": "",
      "ContentDisposition": "",
      "ContentLanguage": "",
      "CacheControl": "",
      "Mode": null,
      "RetainUntilDate": null,
      "ServerSideEncryption": null,
      "NumThreads": 0,
      "StorageClass": "",
      "WebsiteRedirectLocation": "",
      "PartSize": 0
    }
  },
  "duration": 999,
  "error": "The bucket you tried to delete is not empty",
  "function": "PutObjectWithContext(ctx, bucketName, objectName, fileName, opts)",
  "message": "Cleanup failed",
  "name": "minio-go: testPutObjectWithContext",
  "status": "FAIL"
}

Executed 4 out of 13 tests successfully.
```
Deleting image on docker hub
Deleting image locally

**Comment by minio-ops** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-compression-xl.sh | :heavy_check_mark: |
| mint-compression-dist-xl.sh | :heavy_check_mark: |
| mint-compression-fs.sh | :heavy_check_mark: |
| mint-worm.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-dist-xl.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-xl.sh | :x: [more...](#bb243c0b-953d-46cb-a2b1-d62107bbbc14) |
| mint-large-bucket.sh | :x: [more...](#3370bf8f-fed8-470d-aac6-56d477cc6938) |
<a name="3370bf8f-fed8-470d-aac6-56d477cc6938"></a>
### 8776-61aa424/mint-large-bucket.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.52:32425
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 01b41b0f7bc9:/mint/log /tmp/mint-logs'

(1/13) Running awscli tests ... done in 1 minutes and 29 seconds
(2/13) Running aws-sdk-java tests ... done in 1 seconds
(3/13) Running aws-sdk-ruby tests ... done in 6 seconds
(4/13) Running mc tests ... done in 1 minutes and 5 seconds
(5/13) Running minio-go tests ... FAILED in 3 minutes and 55 seconds
{
  "args": {},
  "duration": 90991,
  "error": "Please reduce your request",
  "function": "testStorageClassMetadataCopyObject()",
  "message": "CopyObject failed on RRS",
  "name": "minio-go: testStorageClassMetadataCopyObject",
  "status": "FAIL"
}

Executed 4 out of 13 tests successfully.
```
<a name="bb243c0b-953d-46cb-a2b1-d62107bbbc14"></a>
### 8776-61aa424/mint-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.61:32609
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 091ec82deb98:/mint/log /tmp/mint-logs'

(1/13) Running awscli tests ... FAILED in 8 seconds
{
  "name": "awscli",
  "duration": 5950,
  "function": "make_bucket\n",
  "status": "FAIL",
  "error": "An error occurred (XMinioServerNotInitialized) when calling the CreateBucket operation (reached max retries: 4): Server not initialized, please try again."
}

Executed 0 out of 13 tests successfully.
```
Deleting image on docker hub
Deleting image locally

**Review by klauspost — APPROVED** [review]
👍 Looks solid!

File: cmd/endpoint.go [hunk 1]
```diff
@@ -548,11 +546,7 @@ func CreateEndpoints(serverAddr string, foundLocal bool, args ...[]string) (Endp
 			return endpoints, setupType, config.ErrInvalidErasureEndpoints(nil).Msg(err.Error())
 		}
 
-		for _, ep := range eps {
-			ep.SetIndex = i
-			newEndpoints = append(newEndpoints, ep)
-		}
-		endpoints = append(endpoints, newEndpoints...)
+		endpoints = append(endpoints, append(Endpoints{}, eps...)...)
```
Comment (vadmeste) [inline cmd/endpoint.go]: Why not `endpoints = append(endpoints, eps...)` ?

**Review by vadmeste — COMMENTED** [review]
One comment, LGTM otherwise

**Comment by minio-ops** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-compression-xl.sh | :heavy_check_mark: |
| mint-xl.sh | :heavy_check_mark: |
| mint-compression-dist-xl.sh | :heavy_check_mark: |
| mint-compression-fs.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :x: [more...](#4928b31f-e403-42e9-bfd1-94c1d82f0925) |
| mint-worm.sh | :x: [more...](#c49a6b75-b014-4300-9f6f-a101c0e4cc1d) |
| mint-dist-xl.sh | :x: [more...](#42560732-cc23-4103-bfeb-1c5b533f1e3e) |
<a name="42560732-cc23-4103-bfeb-1c5b533f1e3e"></a>
### 8776-d61d504/mint-dist-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.55:31210
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 5e703ad5f98d:/mint/log /tmp/mint-logs'

(1/13) Running awscli tests ... FAILED in 5 minutes and 8 seconds
{"name": "awscli", "duration": 305832, "function": "make_bucket\n", "status": "FAIL", "error": "Connect timeout on endpoint URL: "http://72.28.97.55:31210/awscli-mint-test-bucket-8442""}

Executed 0 out of 13 tests successfully.
```
<a name="c49a6b75-b014-4300-9f6f-a101c0e4cc1d"></a>
### 8776-d61d504/mint-worm.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.55:30054
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            worm
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp e46cc997ec9e:/mint/log /tmp/mint-logs'

(1/1) Running worm tests ... FAILED in 2 minutes and 1 seconds
{
  "alert": "",
  "args": {
    "bucketName": "bucket-6ko33m2vklp3jljpo8ni1ijt2e0r53memx2qbro0w2b8a8px9q8yj6i",
    "expiry": 60000000000,
    "objectName": "testObject"
  },
  "duration": 120239,
  "error": "RequestError: send request failed\ncaused by: Put http://72.28.97.55:30054/bucket-6ko33m2vklp3jljpo8ni1ijt2e0r53memx2qbro0w2b8a8px9q8yj6i: dial tcp 72.28.97.55:30054: i/o timeout",
  "function": "PutAndDelete",
  "message": "WORM_MODE ON  - CreateBucket Failed",
  "name": "test worm mode",
  "status": "FAIL"
}

Executed 0 out of 1 tests successfully.
```
<a name="4928b31f-e403-42e9-bfd1-94c1d82f0925"></a>
### 8776-d61d504/mint-large-bucket.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.56:32540
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 51a294e3c010:/mint/log /tmp/mint-logs'

(1/13) Running awscli tests ... done in 2 minutes and 25 seconds
(2/13) Running aws-sdk-java tests ... done in 1 seconds
(3/13) Running aws-sdk-ruby tests ... done in 7 seconds
(4/13) Running mc tests ... done in 1 minutes and 14 seconds
(5/13) Running minio-go tests ... FAILED in 3 minutes and 7 seconds
{
  "args": {},
  "duration": 69493,
  "error": "Please reduce your request",
  "function": "testStorageClassMetadataCopyObject()",
  "message": "CopyObject failed on RRS",
  "name": "minio-go: testStorageClassMetadataCopyObject",
  "status": "FAIL"
}

Executed 4 out of 13 tests successfully.
```
Deleting image on docker hub
Deleting image locally

**Comment by minio-ops** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-compression-xl.sh | :heavy_check_mark: |
| mint-xl.sh | :heavy_check_mark: |
| mint-compression-dist-xl.sh | :heavy_check_mark: |
| mint-compression-fs.sh | :heavy_check_mark: |
| mint-worm.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-dist-xl.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :x: [more...](#6927de35-0701-4d38-b101-724b1faa698d) |
<a name="6927de35-0701-4d38-b101-724b1faa698d"></a>
### 8776-09a976d/mint-large-bucket.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.55:32742
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 1bc4aaecace7:/mint/log /tmp/mint-logs'

(1/13) Running awscli tests ... FAILED in 5 minutes and 14 seconds
{"name": "awscli", "duration": 312585, "function": "make_bucket\n", "status": "FAIL", "error": "Connect timeout on endpoint URL: "http://72.28.97.55:32742/awscli-mint-test-bucket-25008""}

Executed 0 out of 13 tests successfully.
```
Deleting image on docker hub
Deleting image locally

**Comment by minio-ops** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-compression-xl.sh | :heavy_check_mark: |
| mint-xl.sh | :heavy_check_mark: |
| mint-compression-dist-xl.sh | :heavy_check_mark: |
| mint-compression-fs.sh | :heavy_check_mark: |
| mint-worm.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :x: [more...](#72ae59ad-d482-40cb-bcdc-21e85d7cf285) |
| mint-dist-xl.sh | :x: [more...](#501e1ee0-c954-43d2-88dc-b6ad5c601174) |
<a name="501e1ee0-c954-43d2-88dc-b6ad5c601174"></a>
### 8776-ca24b80/mint-dist-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.51:31141
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 8736f939fc65:/mint/log /tmp/mint-logs'

(1/13) Running awscli tests ... done in 2 minutes and 12 seconds
(2/13) Running aws-sdk-java tests ... done in 1 seconds
(3/13) Running aws-sdk-ruby tests ... done in 5 seconds
(4/13) Running mc tests ... done in 1 minutes and 11 seconds
(5/13) Running minio-go tests ... done in 1 minutes and 34 seconds
(6/13) Running minio-js tests ... FAILED in 18 seconds
{
  "name": "minio-js",
  "function": "fPutObject(bucketName, objectName, filePath, metaData)",
  "args": "bucketName:minio-js-test-0d5910ce-25db-48fd-a4f0-930f97530512, objectName:datafile-65-MB, filePath:/tmp/datafile-65-MB",
  "duration": 2048,
  "status": "FAIL",
  "error": "S3Error: Please reduce your request at Object.parseError (node_modules/minio/dist/main/xml-parsers.js:85:11) at /mint/run/core/minio-js/node_modules/minio/dist/main/transformers.js:155:22 at DestroyableTransform._flush (node_modules/minio/dist/main/transformers.js:79:10) at DestroyableTransform.prefinish (node_modules/readable-stream/lib/_stream_transform.js:129:10) at prefinish (node_modules/readable-stream/lib/_stream_writable.js:607:14) at finishMaybe (node_modules/readable-stream/lib/_stream_writable.js:616:5) at endWritable (node_modules/readable-stream/lib/_stream_writable.js:629:3) at DestroyableTransform.Writable.end (node_modules/readable-stream/lib/_stream_writable.js:567:22) at IncomingMessage.onend (_stream_readable.js:727:10) at endReadableNT (_stream_readable.js:1215:12) at processTicksAndRejections (internal/process/task_queues.js:84:21)"
}

Executed 5 out of 13 tests successfully.
```
<a name="72ae59ad-d482-40cb-bcdc-21e85d7cf285"></a>
### 8776-ca24b80/mint-large-bucket.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.61:32681
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 2b1c4122d135:/mint/log /tmp/mint-logs'

(1/13) Running awscli tests ... done in 2 minutes and 32 seconds
(2/13) Running aws-sdk-java tests ... done in 1 seconds
(3/13) Running aws-sdk-ruby tests ... done in 7 seconds
(4/13) Running mc tests ... done in 1 minutes and 19 seconds
(5/13) Running minio-go tests ... FAILED in 3 minutes and 39 seconds
{
  "args": {},
  "duration": 88452,
  "error": "Please reduce your request",
  "function": "testStorageClassMetadataCopyObject()",
  "message": "CopyObject failed on RRS",
  "name": "minio-go: testStorageClassMetadataCopyObject",
  "status": "FAIL"
}

Executed 4 out of 13 tests successfully.
```
Deleting image on docker hub
Deleting image locally

**Comment by minio-ops** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-compression-xl.sh | :heavy_check_mark: |
| mint-xl.sh | :heavy_check_mark: |
| mint-compression-dist-xl.sh | :heavy_check_mark: |
| mint-worm.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-dist-xl.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :x: [more...](#34f98ec6-b6cd-4f9e-a18b-a704e7fb8ff8) |
| mint-compression-fs.sh | :x: [more...](#0d958528-e619-46e0-975f-d967398d3f21) |
<a name="34f98ec6-b6cd-4f9e-a18b-a704e7fb8ff8"></a>
### 8776-9ba72dd/mint-large-bucket.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.58:31840
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 43d1d09b6050:/mint/log /tmp/mint-logs'

(1/13) Running awscli tests ... done in 2 minutes and 23 seconds
(2/13) Running aws-sdk-java tests ... done in 1 seconds
(3/13) Running aws-sdk-ruby tests ... done in 6 seconds
(4/13) Running mc tests ... done in 1 minutes and 21 seconds
(5/13) Running minio-go tests ... FAILED in 3 minutes and 16 seconds
{
  "args": {},
  "duration": 80653,
  "error": "Please reduce your request",
  "function": "testStorageClassMetadataCopyObject()",
  "message": "CopyObject failed on RRS",
  "name": "minio-go: testStorageClassMetadataCopyObject",
  "status": "FAIL"
}

Executed 4 out of 13 tests successfully.
```
<a name="0d958528-e619-46e0-975f-d967398d3f21"></a>
### 8776-9ba72dd/mint-compression-fs.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.55:31746
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp ddce8df68129:/mint/log /tmp/mint-logs'

(1/13) Running awscli tests ... FAILED in 5 minutes and 11 seconds
{"name": "awscli", "duration": 309270, "function": "make_bucket\n", "status": "FAIL", "error": "Connect timeout on endpoint URL: "http://72.28.97.55:31746/awscli-mint-test-bucket-32596""}

Executed 0 out of 13 tests successfully.
```
Deleting image on docker hub
Deleting image locally

**Comment by minio-ops** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-compression-xl.sh | :heavy_check_mark: |
| mint-xl.sh | :heavy_check_mark: |
| mint-compression-fs.sh | :heavy_check_mark: |
| mint-worm.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :x: [more...](#3004cd5c-e92f-47a0-aabb-954065e87c57) |
| mint-compression-dist-xl.sh | :x: [more...](#94874772-2e0c-401e-85d4-5a60f60fe17e) |
| mint-fs.sh | :x: [more...](#7143eb79-1841-4e4d-a7c8-12e9b24adc4b) |
| mint-dist-xl.sh | :x: [more...](#a71692fc-3e79-4bff-8d53-fa0a555ce597) |
<a name="7143eb79-1841-4e4d-a7c8-12e9b24adc4b"></a>
### 8776-2b03f40/mint-fs.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.55:32061
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 2347e039d5d9:/mint/log /tmp/mint-logs'

(1/13) Running awscli tests ... FAILED in 5 minutes and 8 seconds
{"name": "awscli", "duration": 305705, "function": "make_bucket\n", "status": "FAIL", "error": "Connect timeout on endpoint URL: "http://72.28.97.55:32061/awscli-mint-test-bucket-13653""}

Executed 0 out of 13 tests successfully.
```
<a name="a71692fc-3e79-4bff-8d53-fa0a555ce597"></a>
### 8776-2b03f40/mint-dist-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.55:31193
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp a1b0303b00cd:/mint/log /tmp/mint-logs'

(1/13) Running awscli tests ... FAILED in 5 minutes and 7 seconds
{"name": "awscli", "duration": 304666, "function": "make_bucket\n", "status": "FAIL", "error": "Connect timeout on endpoint URL: "http://72.28.97.55:31193/awscli-mint-test-bucket-12359""}

Executed 0 out of 13 tests successfully.
```
<a name="3004cd5c-e92f-47a0-aabb-954065e87c57"></a>
### 8776-2b03f40/mint-large-bucket.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.56:30256
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp e16a44bbaba9:/mint/log /tmp/mint-logs'

(1/13) Running awscli tests ... done in 2 minutes and 16 seconds
(2/13) Running aws-sdk-java tests ... done in 1 seconds
(3/13) Running aws-sdk-ruby tests ... done in 6 seconds
(4/13) Running mc tests ... done in 52 seconds
(5/13) Running minio-go tests ... FAILED in 3 minutes and 57 seconds
{
  "args": {},
  "duration": 134438,
  "error": "Please reduce your request",
  "function": "testStorageClassMetadataCopyObject()",
  "message": "CopyObject failed on RRS",
  "name": "minio-go: testStorageClassMetadataCopyObject",
  "status": "FAIL"
}

Executed 4 out of 13 tests successfully.
```
<a name="94874772-2e0c-401e-85d4-5a60f60fe17e"></a>
### 8776-2b03f40/mint-compression-dist-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.55:31886
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 74a6966245a4:/mint/log /tmp/mint-logs'

(1/13) Running awscli tests ... FAILED in 5 minutes and 12 seconds
{"name": "awscli", "duration": 309128, "function": "make_bucket\n", "status": "FAIL", "error": "Connect timeout on endpoint URL: "http://72.28.97.55:31886/awscli-mint-test-bucket-10784""}

Executed 0 out of 13 tests successfully.
```
Deleting image on docker hub
Deleting image locally

**Comment by minio-ops** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-compression-xl.sh | :heavy_check_mark: |
| mint-compression-dist-xl.sh | :heavy_check_mark: |
| mint-compression-fs.sh | :heavy_check_mark: |
| mint-worm.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-dist-xl.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-xl.sh | :x: [more...](#70a5dda6-8579-4cb9-91aa-75173e4f1f2e) |
| mint-large-bucket.sh | :x: [more...](#3401a7f5-9efb-48e3-baee-3f81c2177ca2) |
<a name="70a5dda6-8579-4cb9-91aa-75173e4f1f2e"></a>
### 8776-e69d98b/mint-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.58:30614
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 0a8b57278f51:/mint/log /tmp/mint-logs'

(1/13) Running awscli tests ... FAILED in 12 seconds
{
  "name": "awscli",
  "duration": 9467,
  "function": "make_bucket\n",
  "status": "FAIL",
  "error": "An error occurred (XMinioServerNotInitialized) when calling the CreateBucket operation (reached max retries: 4): Server not initialized, please try again."
}

Executed 0 out of 13 tests successfully.
```
<a name="3401a7f5-9efb-48e3-baee-3f81c2177ca2"></a>
### 8776-e69d98b/mint-large-bucket.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.51:30483
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 4b718b745bb3:/mint/log /tmp/mint-logs'

(1/13) Running awscli tests ... done in 2 minutes and 24 seconds
(2/13) Running aws-sdk-java tests ... done in 1 seconds
(3/13) Running aws-sdk-ruby tests ... done in 8 seconds
(4/13) Running mc tests ... done in 1 minutes and 3 seconds
(5/13) Running minio-go tests ... FAILED in 3 minutes and 37 seconds
{
  "args": {},
  "duration": 88816,
  "error": "Please reduce your request",
  "function": "testStorageClassMetadataCopyObject()",
  "message": "CopyObject failed on RRS",
  "name": "minio-go: testStorageClassMetadataCopyObject",
  "status": "FAIL"
}

Executed 4 out of 13 tests successfully.
```
Deleting image on docker hub
Deleting image locally

**Comment by minio-ops** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-compression-xl.sh | :heavy_check_mark: |
| mint-xl.sh | :heavy_check_mark: |
| mint-compression-dist-xl.sh | :heavy_check_mark: |
| mint-compression-fs.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :x: [more...](#5de96cf8-56fa-4b0f-9b88-8a9c051a284f) |
| mint-worm.sh | :x: [more...](#e87b51f4-9b5e-4f99-9e7a-74c1fbed94c2) |
| mint-dist-xl.sh | :x: [more...](#e7e398b6-2559-4306-b567-91add82464b1) |
<a name="e7e398b6-2559-4306-b567-91add82464b1"></a>
### 8776-e1f50a3/mint-dist-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.61:32475
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 0090d6743da2:/mint/log /tmp/mint-logs'

(1/13) Running awscli tests ... done in 2 minutes and 13 seconds
(2/13) Running aws-sdk-java tests ... done in 1 seconds
(3/13) Running aws-sdk-ruby tests ... done in 3 seconds
(4/13) Running mc tests ... done in 1 minutes and 18 seconds
(5/13) Running minio-go tests ... done in 1 minutes and 45 seconds
(6/13) Running minio-js tests ... FAILED in 6 seconds
{
  "name": "minio-js",
  "function": "\"after all\" hook in \"functional tests\"",
  "duration": 8,
  "status": "FAIL",
  "error": "S3Error: The bucket you tried to delete is not empty at Object.parseError (node_modules/minio/dist/main/xml-parsers.js:85:11) at /mint/run/core/minio-js/node_modules/minio/dist/main/transformers.js:155:22 at DestroyableTransform._flush (node_modules/minio/dist/main/transformers.js:79:10) at DestroyableTransform.prefinish (node_modules/readable-stream/lib/_stream_transform.js:129:10) at prefinish (node_modules/readable-stream/lib/_stream_writable.js:607:14) at finishMaybe (node_modules/readable-stream/lib/_stream_writable.js:616:5) at endWritable (node_modules/readable-stream/lib/_stream_writable.js:629:3) at DestroyableTransform.Writable.end (node_modules/readable-stream/lib/_stream_writable.js:567:22) at IncomingMessage.onend (_stream_readable.js:727:10) at endReadableNT (_stream_readable.js:1215:12) at processTicksAndRejections (internal/process/task_queues.js:84:21)"
}

Executed 5 out of 13 tests successfully.
```
<a name="5de96cf8-56fa-4b0f-9b88-8a9c051a284f"></a>
### 8776-e1f50a3/mint-large-bucket.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.59:30110
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp c7ef86e0a937:/mint/log /tmp/mint-logs'

(1/13) Running awscli tests ... FAILED in 7 seconds
{
  "name": "awscli",
  "duration": 4612,
  "function": "make_bucket\n",
  "status": "FAIL",
  "error": "An error occurred (XMinioServerNotInitialized) when calling the CreateBucket operation (reached max retries: 4): Server not initialized, please try again."
}

Executed 0 out of 13 tests successfully.
```
<a name="e87b51f4-9b5e-4f99-9e7a-74c1fbed94c2"></a>
### 8776-e1f50a3/mint-worm.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.55:31887
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            worm
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 1bd677d9832d:/mint/log /tmp/mint-logs'

(1/1) Running worm tests ... FAILED in 2 minutes and 0 seconds
{
  "alert": "",
  "args": {
    "bucketName": "bucket-wj66qte424lfpgvabbmx2uryom2ujizofkwhi76liy1jmz5ysw4yhwx",
    "expiry": 60000000000,
    "objectName": "testObject"
  },
  "duration": 120255,
  "error": "RequestError: send request failed\ncaused by: Put http://72.28.97.55:31887/bucket-wj66qte424lfpgvabbmx2uryom2ujizofkwhi76liy1jmz5ysw4yhwx: dial tcp 72.28.97.55:31887: i/o timeout",
  "function": "PutAndDelete",
  "message": "WORM_MODE ON  - CreateBucket Failed",
  "name": "test worm mode",
  "status": "FAIL"
}

Executed 0 out of 1 tests successfully.
```
Deleting image on docker hub
Deleting image locally

**Comment by minio-ops** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-worm.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-xl.sh | :x: [more...](#476f276a-e04c-4012-851a-fbda55646d03) |
| mint-large-bucket.sh | :x: [more...](#eba7d370-0186-4794-8670-5abcda2c1152) |
| mint-dist-xl.sh | :x: [more...](#cba1f529-8636-441a-9444-e64f50f98ebe) |
<a name="cba1f529-8636-441a-9444-e64f50f98ebe"></a>
### 8776-ac36197/mint-dist-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.55:31936
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp c53db70f9e1c:/mint/log /tmp/mint-logs'

(1/13) Running awscli tests ... FAILED in 5 minutes and 8 seconds
{"name": "awscli", "duration": 306238, "function": "make_bucket\n", "status": "FAIL", "error": "Connect timeout on endpoint URL: "http://72.28.97.55:31936/awscli-mint-test-bucket-23312""}

Executed 0 out of 13 tests successfully.
```
<a name="476f276a-e04c-4012-851a-fbda55646d03"></a>
### 8776-ac36197/mint-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.58:30574
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 303d84123490:/mint/log /tmp/mint-logs'

(1/13) Running awscli tests ... FAILED in 11 seconds
{
  "name": "awscli",
  "duration": 8951,
  "function": "make_bucket\n",
  "status": "FAIL",
  "error": "An error occurred (XMinioServerNotInitialized) when calling the CreateBucket operation (reached max retries: 4): Server not initialized, please try again."
}

Executed 0 out of 13 tests successfully.
```
<a name="eba7d370-0186-4794-8670-5abcda2c1152"></a>
### 8776-ac36197/mint-large-bucket.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.56:30821
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp cdaa5702176e:/mint/log /tmp/mint-logs'

(1/13) Running awscli tests ... done in 2 minutes and 15 seconds
(2/13) Running aws-sdk-java tests ... done in 1 seconds
(3/13) Running aws-sdk-ruby tests ... done in 5 seconds
(4/13) Running mc tests ... done in 41 seconds
(5/13) Running minio-go tests ... FAILED in 2 minutes and 52 seconds
{
  "args": {},
  "duration": 78018,
  "error": "Please reduce your request",
  "function": "testStorageClassMetadataCopyObject()",
  "message": "CopyObject failed on RRS",
  "name": "minio-go: testStorageClassMetadataCopyObject",
  "status": "FAIL"
}

Executed 4 out of 13 tests successfully.
```
Deleting image on docker hub
Deleting image locally

**Comment by minio-ops** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-xl.sh | :heavy_check_mark: |
| mint-worm.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-dist-xl.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :x: [more...](#cf73665c-a92c-4963-91b6-25b1e3d17b85) |
<a name="cf73665c-a92c-4963-91b6-25b1e3d17b85"></a>
### 8776-fe0ac6e/mint-large-bucket.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.56:30680
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp ddca7a054db6:/mint/log /tmp/mint-logs'

(1/13) Running awscli tests ... done in 2 minutes and 17 seconds
(2/13) Running aws-sdk-java tests ... done in 1 seconds
(3/13) Running aws-sdk-ruby tests ... done in 5 seconds
(4/13) Running mc tests ... done in 1 minutes and 9 seconds
(5/13) Running minio-go tests ... FAILED in 3 minutes and 8 seconds
{
  "args": {},
  "duration": 80766,
  "error": "Please reduce your request",
  "function": "testStorageClassMetadataCopyObject()",
  "message": "CopyObject failed on RRS",
  "name": "minio-go: testStorageClassMetadataCopyObject",
  "status": "FAIL"
}

Executed 4 out of 13 tests successfully.
```
Deleting image on docker hub
Deleting image locally

**Comment by minio-ops** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-xl.sh | :heavy_check_mark: |
| mint-worm.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-dist-xl.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :x: [more...](#e5963270-4e1a-4e89-a6ed-8c3d671520c7) |
<a name="e5963270-4e1a-4e89-a6ed-8c3d671520c7"></a>
### 8776-c1ee5a2/mint-large-bucket.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.56:32499
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 5aad42366f24:/mint/log /tmp/mint-logs'

(1/13) Running awscli tests ... FAILED in 13 seconds
{
  "name": "awscli",
  "duration": 10767,
  "function": "make_bucket\n",
  "status": "FAIL",
  "error": "An error occurred (XMinioServerNotInitialized) when calling the CreateBucket operation (reached max retries: 4): Server not initialized, please try again."
}

Executed 0 out of 13 tests successfully.
```
Deleting image on docker hub
Deleting image locally

**Comment by minio-ops** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-worm.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-dist-xl.sh | :heavy_check_mark: |
| mint-xl.sh | :x: [more...](#2c9eeb4b-2f99-46e5-8611-5fa622c33e69) |
| mint-large-bucket.sh | :x: [more...](#e7ff997a-e270-4668-809a-cdd9ce3ba71d) |
| mint-gateway-nas.sh | :x: [more...](#5640b38a-6497-4220-881a-8d2234c84a21) |
<a name="5640b38a-6497-4220-881a-8d2234c84a21"></a>
### 8776-ad94b8e/mint-gateway-nas.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.55:30454
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp aa1fe15cae35:/mint/log /tmp/mint-logs'

(1/13) Running awscli tests ... FAILED in 5 minutes and 15 seconds
{"name": "awscli", "duration": 312517, "function": "make_bucket\n", "status": "FAIL", "error": "Connect timeout on endpoint URL: "http://72.28.97.55:30454/awscli-mint-test-bucket-30029""}

Executed 0 out of 13 tests successfully.
```
<a name="2c9eeb4b-2f99-46e5-8611-5fa622c33e69"></a>
### 8776-ad94b8e/mint-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.55:30145
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 229c7c9b2cfa:/mint/log /tmp/mint-logs'

(1/13) Running awscli tests ... FAILED in 5 minutes and 10 seconds
{"name": "awscli", "duration": 307711, "function": "make_bucket\n", "status": "FAIL", "error": "Connect timeout on endpoint URL: "http://72.28.97.55:30145/awscli-mint-test-bucket-22507""}

Executed 0 out of 13 tests successfully.
```
<a name="e7ff997a-e270-4668-809a-cdd9ce3ba71d"></a>
### 8776-ad94b8e/mint-large-bucket.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.58:30461
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp ce1d007f6e7d:/mint/log /tmp/mint-logs'

(1/13) Running awscli tests ... done in 2 minutes and 27 seconds
(2/13) Running aws-sdk-java tests ... done in 1 seconds
(3/13) Running aws-sdk-ruby tests ... done in 7 seconds
(4/13) Running mc tests ... done in 49 seconds
(5/13) Running minio-go tests ... FAILED in 3 minutes and 37 seconds
{
  "args": {},
  "duration": 103436,
  "error": "Please reduce your request",
  "function": "testStorageClassMetadataCopyObject()",
  "message": "CopyObject failed on RRS",
  "name": "minio-go: testStorageClassMetadataCopyObject",
  "status": "FAIL"
}

Executed 4 out of 13 tests successfully.
```
Deleting image on docker hub
Deleting image locally

**Review by vadmeste — APPROVED** [review]
LGTM
