### PR TITLE
fix: Avoid double usage calculation on every restart

### LINKED ISSUE #8844: high CPU/memory usage when crawling disk usage
I'm running minio (in server mode) on an edge server for local object storage.
Every 12h when disk usage is crawled this results in a peak of CPU/memory usage.
Since there are quite a few other things running on this edge node, this breaks my use case.

It was working fine with version RELEASE.2019-09-26T19-42-35Z

Related:
* documentation about this: #8722
* rss increase: #8664

## Expected Behavior

Disk usage calculation does NOT create high peaks in CPU/memory usage.

## Current Behavior

Disk usage calculation creates high peaks in CPU/memory usage.

## Possible Solution

Disk usage calculation should either run non-aggressively in the background (probably preferred) or an option provided to turn this feature off.

## Steps to Reproduce (for bugs)

1. run minio server
2. observe the high CPU/memory usage every 12h

## Context

This prevents me from using minio for local object storage on our edge nodes as these high peaks degrade the performance of the other processes running on the same edge node too much.

## Regression

For my use-case this is a clear regression.

## Your Environment

* Version used (`minio version`): `RELEASE.2020-01-16T22-40-29Z`
* Environment name and version (e.g. nginx 1.9.1):
* Server type and version: various smaller x86 edge nodes
* Operating System and version (`uname -a`): Linux
* Link to your project:

### PR DESCRIPTION
**Pull request by harshavardhana**
## Description
fix: Avoid double usage calculation on every restart

## Motivation and Context
On every restart of the server, usage was being
calculated which is not useful instead wait for
sufficient time to start the crawling routine.

This PR also avoids lots of double allocations
through strings, optimizes usage of string builders
and also avoids crawling through symbolic links.

Fixes #8844

## How to test this PR?
As mentioned in the PR #8844 

## Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [ ] Fixes a regression (If yes, please add `commit-id` or `PR #` here)
- [ ] Documentation needed
- [x] Unit tests needed
- [ ] Functional tests needed (If yes, add [mint](https://github.com/minio/mint) PR # here: )

### CODE REVIEW

**Comment by minio-ops** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-xl.sh | :heavy_check_mark: |
| mint-worm.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-dist-xl.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :x: [more...](#3371287f-fac9-41fc-b959-08fef76507d6) |
<a name="3371287f-fac9-41fc-b959-08fef76507d6"></a>
### 8856-53d2651/mint-large-bucket.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.53:32723
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 5376de8c860a:/mint/log /tmp/mint-logs'

(1/13) Running awscli tests ... done in 2 minutes and 21 seconds
(2/13) Running aws-sdk-java tests ... done in 1 seconds
(3/13) Running aws-sdk-ruby tests ... done in 6 seconds
(4/13) Running mc tests ... done in 59 seconds
(5/13) Running minio-go tests ... FAILED in 2 minutes and 53 seconds
{
  "args": {},
  "duration": 67660,
  "error": "Please reduce your request",
  "function": "testStorageClassMetadataCopyObject()",
  "message": "CopyObject failed on RRS",
  "name": "minio-go: testStorageClassMetadataCopyObject",
  "status": "FAIL"
}

Executed 4 out of 13 tests successfully.
```
Deleting image on docker hub
Deleting image locally

**Comment by minio-ops** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-xl.sh | :heavy_check_mark: |
| mint-worm.sh | :heavy_check_mark: |
| mint-dist-xl.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :x: [more...](#e0657f1c-9844-4c11-9415-7ffcb31667a9) |
| mint-fs.sh | :x: [more...](#a1fb0b04-0b65-4387-89e3-a1aa6ee753bc) |
<a name="e0657f1c-9844-4c11-9415-7ffcb31667a9"></a>
### 8856-d2f2571/mint-large-bucket.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.61:32182
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 98d5ec2a2cc7:/mint/log /tmp/mint-logs'

(1/13) Running awscli tests ... done in 1 minutes and 29 seconds
(2/13) Running aws-sdk-java tests ... done in 1 seconds
(3/13) Running aws-sdk-ruby tests ... done in 5 seconds
(4/13) Running mc tests ... done in 39 seconds
(5/13) Running minio-go tests ... FAILED in 3 minutes and 20 seconds
{
  "args": {},
  "duration": 65993,
  "error": "Please reduce your request",
  "function": "testStorageClassMetadataCopyObject()",
  "message": "CopyObject failed on RRS",
  "name": "minio-go: testStorageClassMetadataCopyObject",
  "status": "FAIL"
}

Executed 4 out of 13 tests successfully.
```
<a name="a1fb0b04-0b65-4387-89e3-a1aa6ee753bc"></a>
### 8856-d2f2571/mint-fs.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.55:30907
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 839bed216524:/mint/log /tmp/mint-logs'

(1/13) Running awscli tests ... FAILED in 5 minutes and 9 seconds
{"name": "awscli", "duration": 306580, "function": "make_bucket\n", "status": "FAIL", "error": "Connect timeout on endpoint URL: "http://72.28.97.55:30907/awscli-mint-test-bucket-6794""}

Executed 0 out of 13 tests successfully.
```
Deleting image on docker hub
Deleting image locally

**Comment by minio-ops** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-worm.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-dist-xl.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-xl.sh | :x: [more...](#6ff11002-f13d-4434-bcb3-32c965bfa1da) |
| mint-large-bucket.sh | :x: [more...](#4a9f7f05-10bd-4077-9b54-a914370353bb) |
<a name="4a9f7f05-10bd-4077-9b54-a914370353bb"></a>
### 8856-ee38755/mint-large-bucket.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.51:30931
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 6d548d7c6ac0:/mint/log /tmp/mint-logs'

(1/13) Running awscli tests ... done in 2 minutes and 22 seconds
(2/13) Running aws-sdk-java tests ... done in 1 seconds
(3/13) Running aws-sdk-ruby tests ... done in 6 seconds
(4/13) Running mc tests ... done in 48 seconds
(5/13) Running minio-go tests ... FAILED in 2 minutes and 53 seconds
{
  "args": {},
  "duration": 66818,
  "error": "Please reduce your request",
  "function": "testStorageClassMetadataCopyObject()",
  "message": "CopyObject failed on RRS",
  "name": "minio-go: testStorageClassMetadataCopyObject",
  "status": "FAIL"
}

Executed 4 out of 13 tests successfully.
```
<a name="6ff11002-f13d-4434-bcb3-32c965bfa1da"></a>
### 8856-ee38755/mint-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.53:30597
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 618e96b9f62c:/mint/log /tmp/mint-logs'

(1/13) Running awscli tests ... FAILED in 13 seconds
{
  "name": "awscli",
  "duration": 10757,
  "function": "make_bucket\n",
  "status": "FAIL",
  "error": "An error occurred (XMinioServerNotInitialized) when calling the CreateBucket operation (reached max retries: 4): Server not initialized, please try again."
}

Executed 0 out of 13 tests successfully.
```
Deleting image on docker hub
Deleting image locally

File: cmd/fs-v1.go [hunk 1]
```diff
@@ -266,19 +264,13 @@ func (fs *FSObjects) crawlAndGetDataUsageInfo(ctx context.Context, endCh <-chan
...
-		bucket := splits[0]
-		prefix := splits[1]
-
+		bucket, prefix := path2BucketObject(fs.fsPath, origPath)
 		if bucket == "" {
 			return nil
 		}
 
 		if isReservedOrInvalidBucket(bucket, false) {
-			return filepath.SkipDir
```
Comment (vadmeste) [inline cmd/fs-v1.go:283]: filepath.SkipDir should help avoid a useless recursive listing of .minio.sys, is there any reason removing this ?

File: cmd/fs-v1.go [hunk 2]
```diff
@@ -293,8 +285,8 @@ func (fs *FSObjects) crawlAndGetDataUsageInfo(ctx context.Context, endCh <-chan
 			return nil
 		}
 
-		// Get file size
-		fi, err := os.Stat(origPath)
+		// Get file size, no need to follow symlinks.
+		fi, err := os.Lstat(origPath)
```
Comment (vadmeste) [inline cmd/fs-v1.go]: I noticed that FS can follow symlinks, that's why I did os.Stat() and not os.Lstat() to avoid breaking current deployements.

**Review by vadmeste — COMMENTED** [review]
Some comments

File: cmd/data-usage.go [hunk 3]
```diff
@@ -48,40 +48,34 @@ func runDataUsageInfoUpdateRoutine() {
...
-		if err != nil {
-			logger.LogIf(ctx, err)
-		}
-		select {
-		case <-endCh:
-			return
-		// Wait until the next crawl interval
-		case <-t.C:
-		}
+func shouldCrawl(ctx context.Context, objAPI ObjectLayer) *time.Timer {
```
Comment (klauspost) [inline cmd/data-usage.go]: Please document what the returned timer means.

If I read it correctly, this is what it does, so maybe:

```suggestion
// timeToNextCrawl returns the duration until next crawl should occur.
func timeToNextCrawl(ctx context.Context, objAPI ObjectLayer) time.Duration {
```

Returning a duration makes it more flexible. Also avoids needing to check for a nil timer.

File: cmd/utils.go [hunk 4]
```diff
@@ -67,28 +67,47 @@ func request2BucketObjectName(r *http.Request) (bucketName, objectName string) {
...
+func path2BucketObject(b, s string) (bucket, prefix string) {
+	sbuf := path2BucketObjectPool.Get().(*[]string)
+	defer func() {
+		// Reset values to default.
+		(*sbuf)[0] = ""
+		(*sbuf)[1] = ""
+		path2BucketObjectPool.Put(sbuf)
+	}()
+
+	n := len((*sbuf))
```
Comment (klauspost) [inline cmd/utils.go]: Isn't this always 2?

File: cmd/utils.go [hunk 5]
```diff
@@ -67,28 +67,47 @@ func request2BucketObjectName(r *http.Request) (bucketName, objectName string) {
...
+		sbuf := make([]string, 2)
+		return &sbuf
+	},
+}
+
+// Similar to https://golang.org/pkg/strings/#SplitN
+// but doesn't trucate the return list, keeps the
+// size of the array 'n'
+func path2BucketObject(b, s string) (bucket, prefix string) {
+	sbuf := path2BucketObjectPool.Get().(*[]string)
```
Comment (klauspost) [inline cmd/utils.go]: A am not sure why this is needed at all. It does nothing that 2 `string` values cannot do. 

Without this, it would be 32 bytes that could be allocated on the stack, but now it is forced to the heap and requires synchronization and a defer call.

Remove `path2BucketObjectPool` completely.

**Review by klauspost — COMMENTED** [review]
Nice. A few minor things.

File: cmd/utils.go (hunk 5 above)
Comment (harshavardhana) [reply cmd/utils.go]: @klauspost this is an allocation that I am avoiding. This call is called inside a recursive function across files and folders in the walk routine invoking allocations. Current master adds 2 allocations per file, so across let's say a millions of files this becomes too much for any system. 

There is a different way which this can be solved, let me add that.

File: cmd/data-usage.go (hunk 3 above)
Comment (harshavardhana) [reply cmd/data-usage.go]: We will never return nil timer in this function,  returning duration is harder to handle with the select loop so I prefer to keep it this way.

File: cmd/fs-v1.go (hunk 2 above)
Comment (harshavardhana) [reply cmd/fs-v1.go]: On purpose @vadmeste we will not do that anymore since creating eloop scenario is easy and we waste resources crawling such files.

File: cmd/fs-v1.go (hunk 1 above)
Comment (harshavardhana) [reply cmd/fs-v1.go:283]: In my tests this causes entire crawler to stop test with master on `minio server ~/`

File: cmd/data-usage.go (hunk 3 above)
Comment (harshavardhana) [reply cmd/data-usage.go]: Fixed

File: cmd/utils.go (hunk 5 above)
Comment (harshavardhana) [reply cmd/utils.go]: Fixed

**Comment by minio-ops** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-xl.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-dist-xl.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :x: [more...](#b115f819-82d2-48dd-a232-22110d662402) |
| mint-worm.sh | :x: [more...](#abcff056-a989-44bd-a51d-1259bdc33c87) |
<a name="b115f819-82d2-48dd-a232-22110d662402"></a>
### 8856-e8a4bfa/mint-large-bucket.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.61:32624
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp ffc9d56bfd58:/mint/log /tmp/mint-logs'

(1/13) Running awscli tests ... done in 2 minutes and 24 seconds
(2/13) Running aws-sdk-java tests ... done in 1 seconds
(3/13) Running aws-sdk-ruby tests ... done in 8 seconds
(4/13) Running mc tests ... done in 57 seconds
(5/13) Running minio-go tests ... FAILED in 3 minutes and 38 seconds
{
  "args": {},
  "duration": 99392,
  "error": "Please reduce your request",
  "function": "testStorageClassMetadataCopyObject()",
  "message": "CopyObject failed on RRS",
  "name": "minio-go: testStorageClassMetadataCopyObject",
  "status": "FAIL"
}

Executed 4 out of 13 tests successfully.
```
<a name="abcff056-a989-44bd-a51d-1259bdc33c87"></a>
### 8856-e8a4bfa/mint-worm.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.55:31975
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            worm
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp d0b5e8ed5508:/mint/log /tmp/mint-logs'

(1/1) Running worm tests ... FAILED in 2 minutes and 1 seconds
{
  "alert": "",
  "args": {
    "bucketName": "bucket-y8xvztuuexgyyoswvqa0q8fwrvpn48yl0ckqr1ci0uzfc2a53vhmvyz",
    "expiry": 60000000000,
    "objectName": "testObject"
  },
  "duration": 120274,
  "error": "RequestError: send request failed\ncaused by: Put http://72.28.97.55:31975/bucket-y8xvztuuexgyyoswvqa0q8fwrvpn48yl0ckqr1ci0uzfc2a53vhmvyz: dial tcp 72.28.97.55:31975: i/o timeout",
  "function": "PutAndDelete",
  "message": "WORM_MODE ON  - CreateBucket Failed",
  "name": "test worm mode",
  "status": "FAIL"
}

Executed 0 out of 1 tests successfully.
```
Deleting image on docker hub
Deleting image locally

**Comment by minio-ops** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-xl.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-dist-xl.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :x: [more...](#b5a0d35e-f467-41ab-91d9-3858008f7471) |
| mint-worm.sh | :x: [more...](#408a0f51-81ab-40b4-89df-5f2fcb954fcb) |
<a name="b5a0d35e-f467-41ab-91d9-3858008f7471"></a>
### 8856-183285e/mint-large-bucket.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.52:30854
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp abfcae55f9f5:/mint/log /tmp/mint-logs'

(1/13) Running awscli tests ... done in 1 minutes and 31 seconds
(2/13) Running aws-sdk-java tests ... done in 1 seconds
(3/13) Running aws-sdk-ruby tests ... done in 7 seconds
(4/13) Running mc tests ... done in 51 seconds
(5/13) Running minio-go tests ... FAILED in 3 minutes and 49 seconds
{
  "args": {},
  "duration": 107827,
  "error": "Please reduce your request",
  "function": "testStorageClassMetadataCopyObject()",
  "message": "CopyObject failed on RRS",
  "name": "minio-go: testStorageClassMetadataCopyObject",
  "status": "FAIL"
}

Executed 4 out of 13 tests successfully.
```
<a name="408a0f51-81ab-40b4-89df-5f2fcb954fcb"></a>
### 8856-183285e/mint-worm.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.55:31007
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            worm
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 57b32dee72a9:/mint/log /tmp/mint-logs'

(1/1) Running worm tests ... FAILED in 2 minutes and 0 seconds
{
  "alert": "",
  "args": {
    "bucketName": "bucket-1jjelwdysw9oahsnnwdf0fpcfnp52ue3idrc9jr9h9e553ctdbkdeql",
    "expiry": 60000000000,
    "objectName": "testObject"
  },
  "duration": 120355,
  "error": "RequestError: send request failed\ncaused by: Put http://72.28.97.55:31007/bucket-1jjelwdysw9oahsnnwdf0fpcfnp52ue3idrc9jr9h9e553ctdbkdeql: dial tcp 72.28.97.55:31007: i/o timeout",
  "function": "PutAndDelete",
  "message": "WORM_MODE ON  - CreateBucket Failed",
  "name": "test worm mode",
  "status": "FAIL"
}

Executed 0 out of 1 tests successfully.
```
Deleting image on docker hub
Deleting image locally

**Comment by minio-ops** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-worm.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-xl.sh | :x: [more...](#e2fe342e-d92d-40c1-937a-43bec0a42979) |
| mint-large-bucket.sh | :x: [more...](#0c2806d2-9c6f-44e0-a8b5-f49260fec1b8) |
| mint-dist-xl.sh | :x: [more...](#8df9e20e-39aa-4fc3-9d11-24881707c9ea) |
<a name="e2fe342e-d92d-40c1-937a-43bec0a42979"></a>
### 8856-c0f4a42/mint-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.55:31780
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp f7d1bec12172:/mint/log /tmp/mint-logs'

(1/13) Running awscli tests ... FAILED in 5 minutes and 10 seconds
{"name": "awscli", "duration": 307170, "function": "make_bucket\n", "status": "FAIL", "error": "Connect timeout on endpoint URL: "http://72.28.97.55:31780/awscli-mint-test-bucket-23040""}

Executed 0 out of 13 tests successfully.
```
<a name="8df9e20e-39aa-4fc3-9d11-24881707c9ea"></a>
### 8856-c0f4a42/mint-dist-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.55:30579
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 7454368cea16:/mint/log /tmp/mint-logs'

(1/13) Running awscli tests ... FAILED in 5 minutes and 14 seconds
{"name": "awscli", "duration": 311599, "function": "make_bucket\n", "status": "FAIL", "error": "Connect timeout on endpoint URL: "http://72.28.97.55:30579/awscli-mint-test-bucket-26351""}

Executed 0 out of 13 tests successfully.
```
<a name="0c2806d2-9c6f-44e0-a8b5-f49260fec1b8"></a>
### 8856-c0f4a42/mint-large-bucket.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.53:30192
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 7b56d62d7853:/mint/log /tmp/mint-logs'

(1/13) Running awscli tests ... done in 2 minutes and 25 seconds
(2/13) Running aws-sdk-java tests ... done in 1 seconds
(3/13) Running aws-sdk-ruby tests ... done in 6 seconds
(4/13) Running mc tests ... done in 44 seconds
(5/13) Running minio-go tests ... FAILED in 3 minutes and 1 seconds
{
  "args": {},
  "duration": 82791,
  "error": "Please reduce your request",
  "function": "testStorageClassMetadataCopyObject()",
  "message": "CopyObject failed on RRS",
  "name": "minio-go: testStorageClassMetadataCopyObject",
  "status": "FAIL"
}

Executed 4 out of 13 tests successfully.
```
Deleting image on docker hub
Deleting image locally

**Comment by minio-ops** [comment]
```
Error running mint automation
+ mkdir -p 8856-8581a55/gopath/src/github.com/minio
+ git -C 8856-8581a55/gopath/src/github.com/minio clone --quiet https://github.com/minio/minio.git
+ git -C 8856-8581a55/gopath/src/github.com/minio/minio remote add minio https://github.com/minio/minio.git
+ git -C 8856-8581a55/gopath/src/github.com/minio/minio fetch --quiet minio pull/8856/head:pr8856
+ git -C 8856-8581a55/gopath/src/github.com/minio/minio checkout --quiet pr8856
+ GO111MODULE=on
+ GOPATH=/mnt/nvme/mint-auto/8856-8581a55/gopath
+ make -C 8856-8581a55/gopath/src/github.com/minio/minio --quiet
go: downloading github.com/minio/hdfs/v3 v3.0.1
go: downloading github.com/minio/gokrb5/v7 v7.2.5
go: downloading github.com/minio/minio-go/v6 v6.0.45-0.20200117140906-66cf57d21ba4
go: downloading github.com/kurin/blazer v0.5.4-0.20190613185654-cf2f27cc0be3
go: downloading google.golang.org/api v0.5.0
go: downloading github.com/json-iterator/go v1.1.7
go: downloading cloud.google.com/go v0.39.0
go: downloading github.com/miekg/dns v1.1.8
go: extracting github.com/json-iterator/go v1.1.7
go: downloading github.com/gorilla/mux v1.7.0
go: extracting github.com/kurin/blazer v0.5.4-0.20190613185654-cf2f27cc0be3
go: extracting github.com/minio/hdfs/v3 v3.0.1
go: downloading github.com/dgrijalva/jwt-go v3.2.0+incompatible
go: extracting github.com/gorilla/mux v1.7.0
go: extracting github.com/dgrijalva/jwt-go v3.2.0+incompatible
go: downloading gopkg.in/ldap.v3 v3.0.3
go: downloading github.com/modern-go/reflect2 v1.0.1
go: extracting github.com/miekg/dns v1.1.8
go: extracting github.com/minio/minio-go/v6 v6.0.45-0.20200117140906-66cf57d21ba4
go: downloading github.com/prometheus/client_golang v0.9.3-0.20190127221311-3c4408c8b829
go: downloading go.uber.org/atomic v1.3.2
go: downloading github.com/klauspost/compress v1.9.7
go: extracting gopkg.in/ldap.v3 v3.0.3
go: extracting github.com/modern-go/reflect2 v1.0.1
go: downloading github.com/minio/cli v1.22.0
go: downloading github.com/gorilla/rpc v1.2.0
go: extracting cloud.google.com/go v0.39.0
go: extracting go.uber.org/atomic v1.3.2
go: downloading github.com/rs/cors v1.6.0
go: extracting github.com/prometheus/client_golang v0.9.3-0.20190127221311-3c4408c8b829
go: extracting github.com/minio/cli v1.22.0
go: downloading github.com/gorilla/handlers v1.4.0
go: downloading github.com/Azure/azure-pipeline-go v0.2.1
go: extracting github.com/rs/cors v1.6.0
go: extracting github.com/gorilla/rpc v1.2.0
go: downloading github.com/prometheus/procfs v0.0.0-20190117184657-bf6a532e95b1
go: downloading github.com/modern-go/concurrent v0.0.0-20180306012644-bacd9c7ef1dd
go: downloading github.com/aliyun/aliyun-oss-go-sdk v0.0.0-20190307165228-86c17b95fcd5
go: extracting github.com/gorilla/handlers v1.4.0
go: extracting github.com/Azure/azure-pipeline-go v0.2.1
go: downloading golang.org/x/net v0.0.0-20190923162816-aa69164e4478
go: extracting github.com/modern-go/concurrent v0.0.0-20180306012644-bacd9c7ef1dd
go: downloading github.com/ncw/directio v1.0.5
go: extracting github.com/prometheus/procfs v0.0.0-20190117184657-bf6a532e95b1
go: downloading github.com/Azure/azure-storage-blob-go v0.8.0
go: extracting github.com/aliyun/aliyun-oss-go-sdk v0.0.0-20190307165228-86c17b95fcd5
go: downloading github.com/prometheus/client_model v0.0.0-20190129233127-fd36f4220a90
go: extracting github.com/ncw/directio v1.0.5
go: downloading github.com/prometheus/common v0.2.0
go: extracting github.com/Azure/azure-storage-blob-go v0.8.0
go: extracting github.com/prometheus/client_model v0.0.0-20190129233127-fd36f4220a90
go: extracting golang.org/x/net v0.0.0-20190923162816-aa69164e4478
go: extracting github.com/prometheus/common v0.2.0
go: downloading github.com/minio/lsync v1.0.1
go: extracting github.com/minio/lsync v1.0.1
go: downloading github.com/minio/sio v0.2.0
go: downloading github.com/beorn7/perks v0.0.0-20180321164747-3a771d992973
go: extracting github.com/beorn7/perks v0.0.0-20180321164747-3a771d992973
go: downloading github.com/minio/highwayhash v1.0.0
go: extracting github.com/minio/sio v0.2.0
go: downloading github.com/coreos/etcd v3.3.12+incompatible
go: extracting github.com/minio/highwayhash v1.0.0
go: downloading github.com/mitchellh/go-homedir v1.1.0
go: extracting github.com/mitchellh/go-homedir v1.1.0
go: downloading github.com/skyrings/skyring-common v0.0.0-20160929130248-d1c0bb1cbd5e
go: extracting github.com/coreos/etcd v3.3.12+incompatible
go: downloading golang.org/x/crypto v0.0.0-20191117063200-497ca9f6d64f
go: extracting github.com/klauspost/compress v1.9.7
go: downloading google.golang.org/grpc v1.22.0
go: downloading github.com/klauspost/reedsolomon v1.9.3
go: extracting github.com/skyrings/skyring-common v0.0.0-20160929130248-d1c0bb1cbd5e
go: extracting github.com/klauspost/reedsolomon v1.9.3
go: extracting golang.org/x/crypto v0.0.0-20191117063200-497ca9f6d64f
go: downloading github.com/beevik/ntp v0.2.0
go: extracting github.com/beevik/ntp v0.2.0
go: extracting google.golang.org/grpc v1.22.0
go: extracting github.com/minio/gokrb5/v7 v7.2.5
go: downloading gopkg.in/ini.v1 v1.48.0
go: downloading github.com/elazarl/go-bindata-assetfs v1.0.0
go: downloading gopkg.in/jcmturner/goidentity.v3 v3.0.0
go: downloading github.com/dustin/go-humanize v1.0.0
go: downloading github.com/klauspost/pgzip v1.2.1
go: extracting github.com/elazarl/go-bindata-assetfs v1.0.0
go: extracting gopkg.in/jcmturner/goidentity.v3 v3.0.0
go: downloading github.com/cheggaaa/pb v1.0.28
go: downloading github.com/shirou/gopsutil v2.18.12+incompatible
go: extracting gopkg.in/ini.v1 v1.48.0
go: downloading github.com/klauspost/cpuid v1.2.2
go: extracting github.com/dustin/go-humanize v1.0.0
go: downloading github.com/fatih/color v1.7.0
go: extracting github.com/klauspost/pgzip v1.2.1
go: extracting github.com/cheggaaa/pb v1.0.28
go: downloading github.com/klauspost/readahead v1.3.1
go: downloading github.com/Shopify/sarama v1.24.1
go: extracting google.golang.org/api v0.5.0
go: extracting github.com/shirou/gopsutil v2.18.12+incompatible
go: downloading github.com/mattn/go-ieproxy v0.0.0-20190805055040-f9202b1cfdeb
go: extracting github.com/fatih/color v1.7.0
go: extracting github.com/klauspost/readahead v1.3.1
go: downloading golang.org/x/sys v0.0.0-20190922100055-0a153f010e69
go: downloading gopkg.in/jcmturner/rpc.v1 v1.1.0
go: extracting github.com/klauspost/cpuid v1.2.2
go: downloading github.com/mattn/go-isatty v0.0.7
go: extracting github.com/mattn/go-ieproxy v0.0.0-20190805055040-f9202b1cfdeb
go: downloading github.com/secure-io/sio-go v0.3.0
go: extracting github.com/Shopify/sarama v1.24.1
go: downloading github.com/djherbis/atime v1.0.0
go: extracting gopkg.in/jcmturner/rpc.v1 v1.1.0
go: downloading github.com/streadway/amqp v0.0.0-20190404075320-75d898a42a94
go: extracting github.com/mattn/go-isatty v0.0.7
go: extracting github.com/djherbis/atime v1.0.0
go: extracting github.com/secure-io/sio-go v0.3.0
go: downloading github.com/gogo/protobuf v1.2.1
go: downloading github.com/minio/parquet-go v0.0.0-20191231003236-20b3c07bcd2c
go: extracting github.com/streadway/amqp v0.0.0-20190404075320-75d898a42a94
go: downloading github.com/pkg/errors v0.8.1
go: extracting golang.org/x/sys v0.0.0-20190922100055-0a153f010e69
go: extracting github.com/minio/parquet-go v0.0.0-20191231003236-20b3c07bcd2c
go: downloading github.com/googleapis/gax-go/v2 v2.0.4
go: downloading github.com/hashicorp/go-uuid v1.0.1
go: downloading github.com/bcicen/jstream v0.0.0-20190220045926-16c1f8af81c2
go: downloading go.opencensus.io v0.21.0
go: downloading git.apache.org/thrift.git v0.12.0
go: downloading github.com/lib/pq v1.1.1
go: downloading github.com/gomodule/redigo v2.0.0+incompatible
go: extracting github.com/pkg/errors v0.8.1
go: downloading github.com/valyala/tcplisten v0.0.0-20161114210144-ceec8f93295a
go: extracting github.com/hashicorp/go-uuid v1.0.1
go: extracting github.com/googleapis/gax-go/v2 v2.0.4
go: downloading google.golang.org/genproto v0.0.0-20190513181449-d00d292a067c
go: downloading github.com/nats-io/nats.go v1.9.1
go: extracting github.com/bcicen/jstream v0.0.0-20190220045926-16c1f8af81c2
go: downloading golang.org/x/time v0.0.0-20190308202827-9d24e82272b4
go: extracting go.opencensus.io v0.21.0
go: downloading github.com/rcrowley/go-metrics v0.0.0-20190704165056-9c2d0518ed81
go: extracting github.com/gomodule/redigo v2.0.0+incompatible
go: downloading github.com/alecthomas/participle v0.2.1
go: extracting github.com/lib/pq v1.1.1
go: downloading gopkg.in/jcmturner/gokrb5.v7 v7.2.3
go: extracting github.com/valyala/tcplisten v0.0.0-20161114210144-ceec8f93295a
go: downloading github.com/davecgh/go-spew v1.1.1
go: extracting github.com/gogo/protobuf v1.2.1
go: extracting golang.org/x/time v0.0.0-20190308202827-9d24e82272b4
go: downloading github.com/eapache/go-resiliency v1.2.0
go: extracting github.com/nats-io/nats.go v1.9.1
go: downloading golang.org/x/oauth2 v0.0.0-20190402181905-9f3314589c9a
go: extracting github.com/rcrowley/go-metrics v0.0.0-20190704165056-9c2d0518ed81
go: downloading github.com/nats-io/nuid v1.0.1
go: downloading github.com/mattn/go-runewidth v0.0.4
go: extracting github.com/alecthomas/participle v0.2.1
go: extracting github.com/davecgh/go-spew v1.1.1
go: downloading github.com/golang/protobuf v1.3.2
go: downloading github.com/nats-io/jwt v0.3.2
go: extracting github.com/eapache/go-resiliency v1.2.0
go: extracting golang.org/x/oauth2 v0.0.0-20190402181905-9f3314589c9a
go: downloading github.com/pierrec/lz4 v2.2.6+incompatible
go: extracting github.com/nats-io/nuid v1.0.1
go: downloading github.com/nsqio/go-nsq v1.0.7
go: extracting github.com/mattn/go-runewidth v0.0.4
go: downloading github.com/hashicorp/vault/api v1.0.4
go: extracting github.com/nats-io/jwt v0.3.2
go: extracting github.com/golang/protobuf v1.3.2
go: extracting github.com/nsqio/go-nsq v1.0.7
go: extracting github.com/hashicorp/vault/api v1.0.4
go: downloading github.com/mattn/go-colorable v0.1.1
go: extracting google.golang.org/genproto v0.0.0-20190513181449-d00d292a067c
go: extracting github.com/mattn/go-colorable v0.1.1
go: downloading github.com/hashicorp/vault/sdk v0.1.13
go: extracting github.com/hashicorp/vault/sdk v0.1.13
go: downloading github.com/hashicorp/errwrap v1.0.0
go: extracting github.com/hashicorp/errwrap v1.0.0
go: downloading github.com/eapache/go-xerial-snappy v0.0.0-20180814174437-776d5712da21
go: extracting github.com/eapache/go-xerial-snappy v0.0.0-20180814174437-776d5712da21
go: downloading gopkg.in/olivere/elastic.v5 v5.0.80
go: downloading github.com/eapache/queue v1.1.0
go: extracting github.com/eapache/queue v1.1.0
go: downloading github.com/hashicorp/go-retryablehttp v0.5.4
go: extracting github.com/hashicorp/go-retryablehttp v0.5.4
go: downloading github.com/nats-io/stan.go v0.4.5
go: extracting git.apache.org/thrift.git v0.12.0
go: extracting github.com/nats-io/stan.go v0.4.5
go: extracting gopkg.in/olivere/elastic.v5 v5.0.80
go: downloading github.com/mitchellh/mapstructure v1.1.2
go: extracting github.com/mitchellh/mapstructure v1.1.2
go: downloading github.com/eclipse/paho.mqtt.golang v1.2.0
go: downloading github.com/hashicorp/golang-lru v0.5.1
go: extracting github.com/eclipse/paho.mqtt.golang v1.2.0
go: extracting github.com/hashicorp/golang-lru v0.5.1
go: downloading golang.org/x/text v0.3.2
go: downloading github.com/hashicorp/go-rootcerts v1.0.1
go: extracting github.com/hashicorp/go-rootcerts v1.0.1
go: downloading github.com/go-sql-driver/mysql v1.4.1
go: extracting github.com/go-sql-driver/mysql v1.4.1
go: downloading github.com/hashicorp/go-multierror v1.0.0
go: extracting github.com/hashicorp/go-multierror v1.0.0
go: downloading github.com/mailru/easyjson v0.0.0-20180730094502-03f2033d19d5
go: extracting github.com/mailru/easyjson v0.0.0-20180730094502-03f2033d19d5
go: extracting golang.org/x/text v0.3.2
go: extracting github.com/pierrec/lz4 v2.2.6+incompatible
go: downloading github.com/hashicorp/go-cleanhttp v0.5.1
go: downloading gopkg.in/jcmturner/dnsutils.v1 v1.0.1
go: extracting github.com/hashicorp/go-cleanhttp v0.5.1
go: downloading github.com/minio/sha256-simd v0.1.1
go: extracting gopkg.in/jcmturner/dnsutils.v1 v1.0.1
go: downloading github.com/jcmturner/gofork v0.0.0-20190328161633-dc7c13fece03
go: extracting github.com/minio/sha256-simd v0.1.1
go: extracting github.com/jcmturner/gofork v0.0.0-20190328161633-dc7c13fece03
go: downloading github.com/inconshreveable/go-update v0.0.0-20160112193335-8152e7eb6ccf
go: extracting github.com/inconshreveable/go-update v0.0.0-20160112193335-8152e7eb6ccf
go: downloading github.com/coredns/coredns v1.4.0
go: extracting github.com/coredns/coredns v1.4.0
go: downloading github.com/nats-io/nkeys v0.1.3
go: extracting github.com/nats-io/nkeys v0.1.3
go: downloading gopkg.in/asn1-ber.v1 v1.0.0-20181015200546-f715ec2f112d
go: extracting gopkg.in/asn1-ber.v1 v1.0.0-20181015200546-f715ec2f112d
go: downloading github.com/hashicorp/go-sockaddr v1.0.2
go: extracting github.com/hashicorp/go-sockaddr v1.0.2
go: downloading gopkg.in/jcmturner/aescts.v1 v1.0.1
go: extracting gopkg.in/jcmturner/aescts.v1 v1.0.1
go: downloading github.com/hashicorp/hcl v1.0.0
go: extracting github.com/hashicorp/hcl v1.0.0
go: downloading github.com/rjeczalik/notify v0.9.2
go: extracting github.com/rjeczalik/notify v0.9.2
go: downloading github.com/golang/snappy v0.0.1
go: extracting github.com/golang/snappy v0.0.1
go: extracting gopkg.in/jcmturner/gokrb5.v7 v7.2.3
go: downloading gopkg.in/square/go-jose.v2 v2.3.1
go: downloading github.com/ryanuber/go-glob v1.0.0
go: downloading github.com/tidwall/sjson v1.0.4
go: downloading github.com/tidwall/gjson v1.3.5
go: downloading gopkg.in/yaml.v2 v2.2.4
go: downloading github.com/fatih/structs v1.1.0
go: downloading github.com/matttproud/golang_protobuf_extensions v1.0.1
go: extracting github.com/ryanuber/go-glob v1.0.0
go: extracting github.com/tidwall/sjson v1.0.4
go: extracting github.com/tidwall/gjson v1.3.5
go: downloading github.com/tidwall/match v1.0.1
go: downloading github.com/tidwall/pretty v1.0.0
go: extracting github.com/matttproud/golang_protobuf_extensions v1.0.1
go: extracting github.com/fatih/structs v1.1.0
go: extracting gopkg.in/yaml.v2 v2.2.4
go: extracting github.com/tidwall/match v1.0.1
go: extracting github.com/tidwall/pretty v1.0.0
go: extracting gopkg.in/square/go-jose.v2 v2.3.1
go: finding github.com/kurin/blazer v0.5.4-0.20190613185654-cf2f27cc0be3
go: finding github.com/minio/minio-go/v6 v6.0.45-0.20200117140906-66cf57d21ba4
go: finding github.com/minio/cli v1.22.0
go: finding github.com/minio/gokrb5/v7 v7.2.5
go: finding github.com/minio/hdfs/v3 v3.0.1
go: finding github.com/dustin/go-humanize v1.0.0
go: finding google.golang.org/api v0.5.0
go: finding cloud.google.com/go v0.39.0
go: finding github.com/dgrijalva/jwt-go v3.2.0+incompatible
go: finding github.com/aliyun/aliyun-oss-go-sdk v0.0.0-20190307165228-86c17b95fcd5
go: finding github.com/json-iterator/go v1.1.7
go: finding github.com/gorilla/mux v1.7.0
go: finding github.com/minio/highwayhash v1.0.0
go: finding github.com/valyala/tcplisten v0.0.0-20161114210144-ceec8f93295a
go: finding github.com/hashicorp/go-uuid v1.0.1
go: finding github.com/Azure/azure-pipeline-go v0.2.1
go: finding github.com/jcmturner/gofork v0.0.0-20190328161633-dc7c13fece03
go: finding golang.org/x/crypto v0.0.0-20191117063200-497ca9f6d64f
go: finding github.com/mitchellh/go-homedir v1.1.0
go: finding gopkg.in/jcmturner/dnsutils.v1 v1.0.1
go: finding github.com/fatih/color v1.7.0
go: finding github.com/minio/sha256-simd v0.1.1
go: finding github.com/mattn/go-colorable v0.1.1
go: finding golang.org/x/oauth2 v0.0.0-20190402181905-9f3314589c9a
go: finding github.com/mattn/go-isatty v0.0.7
go: finding gopkg.in/ini.v1 v1.48.0
go: finding github.com/Azure/azure-storage-blob-go v0.8.0
go: finding github.com/rjeczalik/notify v0.9.2
go: finding google.golang.org/genproto v0.0.0-20190513181449-d00d292a067c
go: finding golang.org/x/net v0.0.0-20190923162816-aa69164e4478
go: finding github.com/googleapis/gax-go/v2 v2.0.4
go: finding google.golang.org/grpc v1.22.0
go: finding golang.org/x/sys v0.0.0-20190922100055-0a153f010e69
go: finding github.com/mattn/go-ieproxy v0.0.0-20190805055040-f9202b1cfdeb
go: finding go.opencensus.io v0.21.0
go: finding github.com/modern-go/concurrent v0.0.0-20180306012644-bacd9c7ef1dd
go: finding github.com/gogo/protobuf v1.2.1
go: finding golang.org/x/time v0.0.0-20190308202827-9d24e82272b4
go: finding github.com/modern-go/reflect2 v1.0.1
go: finding github.com/golang/protobuf v1.3.2
go: finding gopkg.in/jcmturner/aescts.v1 v1.0.1
go: finding github.com/secure-io/sio-go v0.3.0
go: finding github.com/ncw/directio v1.0.5
go: finding github.com/shirou/gopsutil v2.18.12+incompatible
go: finding gopkg.in/jcmturner/goidentity.v3 v3.0.0
go: finding gopkg.in/jcmturner/rpc.v1 v1.1.0
go: finding golang.org/x/text v0.3.2
go: finding github.com/hashicorp/golang-lru v0.5.1
go: finding github.com/cheggaaa/pb v1.0.28
go: finding github.com/mattn/go-runewidth v0.0.4
go: finding github.com/coreos/etcd v3.3.12+incompatible
go: finding github.com/djherbis/atime v1.0.0
go: finding github.com/elazarl/go-bindata-assetfs v1.0.0
go: finding github.com/gorilla/handlers v1.4.0
go: finding github.com/gorilla/rpc v1.2.0
go: finding github.com/inconshreveable/go-update v0.0.0-20160112193335-8152e7eb6ccf
go: finding github.com/klauspost/compress v1.9.7
go: finding github.com/klauspost/readahead v1.3.1
go: finding github.com/klauspost/reedsolomon v1.9.3
go: finding github.com/klauspost/cpuid v1.2.2
go: finding github.com/miekg/dns v1.1.8
go: finding github.com/minio/lsync v1.0.1
go: finding github.com/coredns/coredns v1.4.0
go: finding gopkg.in/ldap.v3 v3.0.3
go: finding gopkg.in/asn1-ber.v1 v1.0.0-20181015200546-f715ec2f112d
go: finding github.com/Shopify/sarama v1.24.1
go: finding github.com/davecgh/go-spew v1.1.1
go: finding github.com/eapache/go-resiliency v1.2.0
go: finding github.com/eapache/go-xerial-snappy v0.0.0-20180814174437-776d5712da21
go: finding github.com/golang/snappy v0.0.1
go: finding github.com/eapache/queue v1.1.0
go: finding github.com/pierrec/lz4 v2.2.6+incompatible
go: finding github.com/rcrowley/go-metrics v0.0.0-20190704165056-9c2d0518ed81
go: finding gopkg.in/jcmturner/gokrb5.v7 v7.2.3
go: finding github.com/eclipse/paho.mqtt.golang v1.2.0
go: finding github.com/go-sql-driver/mysql v1.4.1
go: finding github.com/gomodule/redigo v2.0.0+incompatible
go: finding github.com/lib/pq v1.1.1
go: finding github.com/nats-io/nats.go v1.9.1
go: finding github.com/nats-io/jwt v0.3.2
go: finding github.com/nats-io/nkeys v0.1.3
go: finding github.com/nats-io/nuid v1.0.1
go: finding github.com/nats-io/stan.go v0.4.5
go: finding github.com/nsqio/go-nsq v1.0.7
go: finding github.com/pkg/errors v0.8.1
go: finding github.com/skyrings/skyring-common v0.0.0-20160929130248-d1c0bb1cbd5e
go: finding github.com/streadway/amqp v0.0.0-20190404075320-75d898a42a94
go: finding gopkg.in/olivere/elastic.v5 v5.0.80
go: finding github.com/mailru/easyjson v0.0.0-20180730094502-03f2033d19d5
go: finding github.com/hashicorp/vault/api v1.0.4
go: finding github.com/hashicorp/errwrap v1.0.0
go: finding github.com/hashicorp/go-cleanhttp v0.5.1
go: finding github.com/hashicorp/go-multierror v1.0.0
go: finding github.com/hashicorp/go-retryablehttp v0.5.4
go: finding github.com/hashicorp/go-rootcerts v1.0.1
go: finding github.com/hashicorp/hcl v1.0.0
go: finding github.com/hashicorp/vault/sdk v0.1.13
go: finding github.com/hashicorp/go-sockaddr v1.0.2
go: finding github.com/ryanuber/go-glob v1.0.0
go: finding github.com/mitchellh/mapstructure v1.1.2
go: finding gopkg.in/square/go-jose.v2 v2.3.1
go: finding github.com/minio/sio v0.2.0
go: finding github.com/beevik/ntp v0.2.0
go: finding github.com/fatih/structs v1.1.0
go: finding gopkg.in/yaml.v2 v2.2.4
go: finding github.com/klauspost/pgzip v1.2.1
go: finding github.com/bcicen/jstream v0.0.0-20190220045926-16c1f8af81c2
go: finding github.com/alecthomas/participle v0.2.1
go: finding github.com/minio/parquet-go v0.0.0-20191231003236-20b3c07bcd2c
go: finding git.apache.org/thrift.git v0.12.0
go: finding github.com/tidwall/gjson v1.3.5
go: finding github.com/tidwall/match v1.0.1
go: finding github.com/tidwall/pretty v1.0.0
go: finding github.com/tidwall/sjson v1.0.4
go: finding github.com/prometheus/client_golang v0.9.3-0.20190127221311-3c4408c8b829
go: finding github.com/beorn7/perks v0.0.0-20180321164747-3a771d992973
go: finding github.com/prometheus/client_model v0.0.0-20190129233127-fd36f4220a90
go: finding github.com/prometheus/common v0.2.0
go: finding github.com/matttproud/golang_protobuf_extensions v1.0.1
go: finding github.com/prometheus/procfs v0.0.0-20190117184657-bf6a532e95b1
go: finding github.com/rs/cors v1.6.0
go: finding go.uber.org/atomic v1.3.2
# github.com/minio/minio/cmd
cmd/generic-handlers.go:728:45: too many values in bucketForwardingHandler literal
make: *** [build] Error 2

```

**Comment by minio-ops** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-xl.sh | :heavy_check_mark: |
| mint-worm.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-dist-xl.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :x: [more...](#9be6707f-7031-45c2-ae18-6c8c3bbe708f) |
<a name="9be6707f-7031-45c2-ae18-6c8c3bbe708f"></a>
### 8856-b781c1b/mint-large-bucket.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.59:32090
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 64935c6cfc6c:/mint/log /tmp/mint-logs'

(1/13) Running awscli tests ... done in 1 minutes and 30 seconds
(2/13) Running aws-sdk-java tests ... done in 1 seconds
(3/13) Running aws-sdk-ruby tests ... done in 5 seconds
(4/13) Running mc tests ... done in 40 seconds
(5/13) Running minio-go tests ... FAILED in 3 minutes and 15 seconds
{
  "args": {},
  "duration": 67775,
  "error": "Please reduce your request",
  "function": "testStorageClassMetadataCopyObject()",
  "message": "CopyObject failed on RRS",
  "name": "minio-go: testStorageClassMetadataCopyObject",
  "status": "FAIL"
}

Executed 4 out of 13 tests successfully.
```
Deleting image on docker hub
Deleting image locally

**Comment by minio-ops** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-fs.sh | :heavy_check_mark: |
| mint-dist-xl.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-xl.sh | :x: [more...](#1fd27b0e-49d5-459c-b8f7-c6f699a22949) |
| mint-large-bucket.sh | :x: [more...](#d2db6031-8da5-4f77-be2d-960e0b2a960a) |
| mint-worm.sh | :x: [more...](#3dbad609-f077-413c-b4de-f56d328c03d7) |
<a name="1fd27b0e-49d5-459c-b8f7-c6f699a22949"></a>
### 8856-cbbafaf/mint-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.55:31680
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 4e0a74aee87c:/mint/log /tmp/mint-logs'

(1/13) Running awscli tests ... FAILED in 5 minutes and 11 seconds
{"name": "awscli", "duration": 309346, "function": "make_bucket\n", "status": "FAIL", "error": "Connect timeout on endpoint URL: "http://72.28.97.55:31680/awscli-mint-test-bucket-9670""}

Executed 0 out of 13 tests successfully.
```
<a name="d2db6031-8da5-4f77-be2d-960e0b2a960a"></a>
### 8856-cbbafaf/mint-large-bucket.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.61:31611
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp ba8cbf47eab9:/mint/log /tmp/mint-logs'

(1/13) Running awscli tests ... done in 2 minutes and 21 seconds
(2/13) Running aws-sdk-java tests ... done in 1 seconds
(3/13) Running aws-sdk-ruby tests ... done in 6 seconds
(4/13) Running mc tests ... done in 48 seconds
(5/13) Running minio-go tests ... FAILED in 3 minutes and 36 seconds
{
  "args": {},
  "duration": 107378,
  "error": "Please reduce your request",
  "function": "testStorageClassMetadataCopyObject()",
  "message": "CopyObject failed on RRS",
  "name": "minio-go: testStorageClassMetadataCopyObject",
  "status": "FAIL"
}

Executed 4 out of 13 tests successfully.
```
<a name="3dbad609-f077-413c-b4de-f56d328c03d7"></a>
### 8856-cbbafaf/mint-worm.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.55:32710
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            worm
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 81834e3285d0:/mint/log /tmp/mint-logs'

(1/1) Running worm tests ... FAILED in 2 minutes and 0 seconds
{
  "alert": "",
  "args": {
    "bucketName": "bucket-u9o9xo9r7vnvl4p99lh1lgl3j8barhm41euim1jskqzboklx3zuy09y",
    "expiry": 60000000000,
    "objectName": "testObject"
  },
  "duration": 120320,
  "error": "RequestError: send request failed\ncaused by: Put http://72.28.97.55:32710/bucket-u9o9xo9r7vnvl4p99lh1lgl3j8barhm41euim1jskqzboklx3zuy09y: dial tcp 72.28.97.55:32710: i/o timeout",
  "function": "PutAndDelete",
  "message": "WORM_MODE ON  - CreateBucket Failed",
  "name": "test worm mode",
  "status": "FAIL"
}

Executed 0 out of 1 tests successfully.
```
Deleting image on docker hub
Deleting image locally

**Comment by minio-ops** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-xl.sh | :x: [more...](#1ee7fd51-627a-4123-943f-f99831536b5e) |
| mint-large-bucket.sh | :x: [more...](#710aa296-f76a-4787-b82c-f1f421eec627) |
| mint-worm.sh | :x: [more...](#c90e9fa5-42ac-41a0-bca9-d499b4ff88e6) |
| mint-fs.sh | :x: [more...](#65bbef91-c86d-4f65-88f4-714b8a04044a) |
| mint-dist-xl.sh | :x: [more...](#6be5dad6-c9e4-4c55-9254-be4287130131) |
<a name="65bbef91-c86d-4f65-88f4-714b8a04044a"></a>
### 8856-f872006/mint-fs.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.52:30306
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp a76e41023d6e:/mint/log /tmp/mint-logs'

(1/13) Running awscli tests ... FAILED in 14 seconds
{"name": "awscli", "duration": 11734, "function": "make_bucket\n", "status": "FAIL", "error": "Could not connect to the endpoint URL: "http://72.28.97.52:30306/awscli-mint-test-bucket-5701""}

Executed 0 out of 13 tests successfully.
```
<a name="c90e9fa5-42ac-41a0-bca9-d499b4ff88e6"></a>
### 8856-f872006/mint-worm.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.59:32677
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            worm
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp c8657ddee2eb:/mint/log /tmp/mint-logs'

(1/1) Running worm tests ... FAILED in 0 seconds
{
  "alert": "",
  "args": {
    "bucketName": "bucket-ioxit9l5my0mgpfa87xp4i3hgmhuucjq8ghju145mvtx0fm1csntx59",
    "expiry": 60000000000,
    "objectName": "testObject"
  },
  "duration": 309,
  "error": "RequestError: send request failed\ncaused by: Put http://72.28.97.59:32677/bucket-ioxit9l5my0mgpfa87xp4i3hgmhuucjq8ghju145mvtx0fm1csntx59: dial tcp 72.28.97.59:32677: connect: connection refused",
  "function": "PutAndDelete",
  "message": "WORM_MODE ON  - CreateBucket Failed",
  "name": "test worm mode",
  "status": "FAIL"
}

Executed 0 out of 1 tests successfully.
```
<a name="6be5dad6-c9e4-4c55-9254-be4287130131"></a>
### 8856-f872006/mint-dist-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.51:30471
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp b7751bb55963:/mint/log /tmp/mint-logs'

(1/13) Running awscli tests ... FAILED in 9 seconds
{
  "name": "awscli",
  "duration": 7400,
  "function": "make_bucket\n",
  "status": "FAIL",
  "error": "An error occurred (XMinioServerNotInitialized) when calling the CreateBucket operation (reached max retries: 4): Server not initialized, please try again."
}

Executed 0 out of 13 tests successfully.
```
<a name="1ee7fd51-627a-4123-943f-f99831536b5e"></a>
### 8856-f872006/mint-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.56:32357
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 38255b2abd64:/mint/log /tmp/mint-logs'

(1/13) Running awscli tests ... FAILED in 15 seconds
{"name": "awscli", "duration": 13442, "function": "make_bucket\n", "status": "FAIL", "error": "Could not connect to the endpoint URL: "http://72.28.97.56:32357/awscli-mint-test-bucket-1725""}

Executed 0 out of 13 tests successfully.
```
<a name="710aa296-f76a-4787-b82c-f1f421eec627"></a>
### 8856-f872006/mint-large-bucket.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.56:30092
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 0b54f2273007:/mint/log /tmp/mint-logs'

(1/13) Running awscli tests ... FAILED in 10 seconds
{
  "name": "awscli",
  "duration": 8252,
  "function": "make_bucket\n",
  "status": "FAIL",
  "error": "An error occurred (SlowDown) when calling the CreateBucket operation (reached max retries: 4): Please reduce your request"
}

Executed 0 out of 13 tests successfully.
```
Deleting image on docker hub
Deleting image locally

**Comment by minio-ops** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-fs.sh | :heavy_check_mark: |
| mint-dist-xl.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-xl.sh | :x: [more...](#5be06ea4-ec4c-4692-87a2-b8c9dfd08790) |
| mint-large-bucket.sh | :x: [more...](#06575b4f-16e9-46fb-bce3-a652f23b5d85) |
| mint-worm.sh | :x: [more...](#56bf36eb-dbcc-4dac-955d-f3eb517209f1) |
<a name="5be06ea4-ec4c-4692-87a2-b8c9dfd08790"></a>
### 8856-fc8f22b/mint-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.59:32715
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp efc323e341f4:/mint/log /tmp/mint-logs'

(1/13) Running awscli tests ... FAILED in 11 seconds
{
  "name": "awscli",
  "duration": 9618,
  "function": "make_bucket\n",
  "status": "FAIL",
  "error": "An error occurred (XMinioServerNotInitialized) when calling the CreateBucket operation (reached max retries: 4): Server not initialized, please try again."
}

Executed 0 out of 13 tests successfully.
```
<a name="56bf36eb-dbcc-4dac-955d-f3eb517209f1"></a>
### 8856-fc8f22b/mint-worm.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.55:30337
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            worm
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 227c13305d05:/mint/log /tmp/mint-logs'

(1/1) Running worm tests ... FAILED in 2 minutes and 0 seconds
{
  "alert": "",
  "args": {
    "bucketName": "bucket-2gabami1fv6d2qdp0ix6o2wwjzmfm05wympdjvjyx1y90rqapv9d13s",
    "expiry": 60000000000,
    "objectName": "testObject"
  },
  "duration": 120312,
  "error": "RequestError: send request failed\ncaused by: Put http://72.28.97.55:30337/bucket-2gabami1fv6d2qdp0ix6o2wwjzmfm05wympdjvjyx1y90rqapv9d13s: dial tcp 72.28.97.55:30337: i/o timeout",
  "function": "PutAndDelete",
  "message": "WORM_MODE ON  - CreateBucket Failed",
  "name": "test worm mode",
  "status": "FAIL"
}

Executed 0 out of 1 tests successfully.
```
<a name="06575b4f-16e9-46fb-bce3-a652f23b5d85"></a>
### 8856-fc8f22b/mint-large-bucket.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.59:32489
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 0ad1f0d23836:/mint/log /tmp/mint-logs'

(1/13) Running awscli tests ... done in 2 minutes and 23 seconds
(2/13) Running aws-sdk-java tests ... done in 1 seconds
(3/13) Running aws-sdk-ruby tests ... done in 7 seconds
(4/13) Running mc tests ... done in 54 seconds
(5/13) Running minio-go tests ... FAILED in 2 minutes and 52 seconds
{
  "args": {},
  "duration": 74952,
  "error": "Please reduce your request",
  "function": "testStorageClassMetadataCopyObject()",
  "message": "CopyObject failed on RRS",
  "name": "minio-go: testStorageClassMetadataCopyObject",
  "status": "FAIL"
}

Executed 4 out of 13 tests successfully.
```
Deleting image on docker hub
Deleting image locally

**Comment by minio-ops** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-worm.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-xl.sh | :x: [more...](#36bb5b8d-ea90-4838-944a-cd36dea95f18) |
| mint-large-bucket.sh | :x: [more...](#4d50b3d8-5166-4198-98dd-5919b02e544c) |
| mint-dist-xl.sh | :x: [more...](#a92257f8-ad88-4472-b345-b70e8841bb32) |
<a name="a92257f8-ad88-4472-b345-b70e8841bb32"></a>
### 8856-74d3781/mint-dist-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.55:30777
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 26cb16684e45:/mint/log /tmp/mint-logs'

(1/13) Running awscli tests ... FAILED in 5 minutes and 8 seconds
{"name": "awscli", "duration": 305714, "function": "make_bucket\n", "status": "FAIL", "error": "Connect timeout on endpoint URL: "http://72.28.97.55:30777/awscli-mint-test-bucket-13757""}

Executed 0 out of 13 tests successfully.
```
<a name="4d50b3d8-5166-4198-98dd-5919b02e544c"></a>
### 8856-74d3781/mint-large-bucket.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.61:32276
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 6ce9bb20cec8:/mint/log /tmp/mint-logs'

(1/13) Running awscli tests ... done in 2 minutes and 23 seconds
(2/13) Running aws-sdk-java tests ... done in 1 seconds
(3/13) Running aws-sdk-ruby tests ... done in 5 seconds
(4/13) Running mc tests ... done in 40 seconds
(5/13) Running minio-go tests ... FAILED in 3 minutes and 15 seconds
{
  "args": {},
  "duration": 99549,
  "error": "Please reduce your request",
  "function": "testStorageClassMetadataCopyObject()",
  "message": "CopyObject failed on RRS",
  "name": "minio-go: testStorageClassMetadataCopyObject",
  "status": "FAIL"
}

Executed 4 out of 13 tests successfully.
```
<a name="36bb5b8d-ea90-4838-944a-cd36dea95f18"></a>
### 8856-74d3781/mint-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.55:30625
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 7df0adbcd2e4:/mint/log /tmp/mint-logs'

(1/13) Running awscli tests ... FAILED in 5 minutes and 6 seconds
{"name": "awscli", "duration": 304619, "function": "make_bucket\n", "status": "FAIL", "error": "Connect timeout on endpoint URL: "http://72.28.97.55:30625/awscli-mint-test-bucket-8485""}

Executed 0 out of 13 tests successfully.
```
Deleting image on docker hub
Deleting image locally

**Comment by minio-ops** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-worm.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-dist-xl.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-xl.sh | :x: [more...](#a27748fc-598a-400d-aafa-16b836b86ec8) |
| mint-large-bucket.sh | :x: [more...](#5018a09e-b1fe-4545-baa2-8259050dbcf0) |
<a name="a27748fc-598a-400d-aafa-16b836b86ec8"></a>
### 8856-7a22491/mint-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.58:32485
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 77061b7c25eb:/mint/log /tmp/mint-logs'

(1/13) Running awscli tests ... FAILED in 9 seconds
{
  "name": "awscli",
  "duration": 6975,
  "function": "make_bucket\n",
  "status": "FAIL",
  "error": "An error occurred (XMinioServerNotInitialized) when calling the CreateBucket operation (reached max retries: 4): Server not initialized, please try again."
}

Executed 0 out of 13 tests successfully.
```
<a name="5018a09e-b1fe-4545-baa2-8259050dbcf0"></a>
### 8856-7a22491/mint-large-bucket.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.61:30599
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 91a275c2d66e:/mint/log /tmp/mint-logs'

(1/13) Running awscli tests ... done in 2 minutes and 22 seconds
(2/13) Running aws-sdk-java tests ... done in 1 seconds
(3/13) Running aws-sdk-ruby tests ... done in 6 seconds
(4/13) Running mc tests ... done in 1 minutes and 4 seconds
(5/13) Running minio-go tests ... FAILED in 3 minutes and 47 seconds
{
  "args": {},
  "duration": 118985,
  "error": "Please reduce your request",
  "function": "testStorageClassMetadataCopyObject()",
  "message": "CopyObject failed on RRS",
  "name": "minio-go: testStorageClassMetadataCopyObject",
  "status": "FAIL"
}

Executed 4 out of 13 tests successfully.
```
Deleting image on docker hub
Deleting image locally

File: cmd/data-usage.go [hunk 6]
```diff
@@ -143,3 +142,86 @@ func loadDataUsageFromBackend(ctx context.Context, objAPI ObjectLayer) (DataUsag
...
+				continue
+			}
+
+			size, err := getSize(item)
+			if err != nil {
+				skipCh <- nil
+				continue
+			}
+
+			dataUsageInfo.ObjectsCount++
```
Comment (vadmeste) [inline cmd/data-usage.go:219]: This seems to count all files under object/xl.json & object/part.N

In other words, calculating the number of objects is currently wrong

**Review by vadmeste — CHANGES_REQUESTED** [review]

File: cmd/utils.go [hunk 7]
```diff
@@ -67,28 +67,37 @@ func request2BucketObjectName(r *http.Request) (bucketName, objectName string) {
...
+
+func path2BucketObject(s string) (bucket, prefix string) {
+	tokens := make([]string, 2)
+	return path2BucketObjectWithTokens("", s, tokens)
+}
+
+// Similar to https://golang.org/pkg/strings/#SplitN
+// but doesn't trucate the return list, keeps the
+// size of the array 'n'
+func path2BucketObjectWithTokens(b, s string, tokens []string) (bucket, prefix string) {
```
Comment (klauspost) [inline cmd/utils.go]: Simpler: 

```Go
// path2BucketObjectWithTokens returns the bucket and prefix, if any, of an object path.
// b is something that is trimmed from the front(?), s is the path.
// (not sure where the tokens comes in)
func path2BucketObjectWithTokens(b, s string) (bucket, prefix string) {
	s = strings.TrimPrefix(s, b)
	s = strings.TrimPrefix(s, SlashSeparator)
	m := strings.Index(s, SlashSeparator)
	if m < 0 {
		return s, ""
	}
	return s[:m], s[m+len(SlashSeparator):]
}
```

Still only uses stack. And avoids allocation on caller. This comparison does not include allocating the slice in the benchmark:
```
BenchmarkSlash/ref-12         	66754560	        18.0 ns/op	       0 B/op	       0 allocs/op
BenchmarkSlash/simple-12      	99944197	        12.7 ns/op	       0 B/op	       0 allocs/op
```

Comment (klauspost) [inline cmd/utils.go]: Simpler:

```Go
// path2BucketObjectWithTokens returns bucket and prefix, if any, of a path 's'.
// b is trimmed from the front of the path.
// (not sure where the tokens fit into this)
func path2BucketObjectWithTokens(b, s string) (bucket, prefix string) {
	s = strings.TrimPrefix(s, b)
	s = strings.TrimPrefix(s, SlashSeparator)
	m := strings.Index(s, SlashSeparator)
	if m < 0 {
		return s, ""
	}
	return s[:m], s[m+len(SlashSeparator):]
}
```

Allocations are still only on the stack and the caller does not have to allocate the slice. The slice allocation is not included in the benchmark of the reference.

```
BenchmarkSlash/ref-12         	66847153	        18.1 ns/op	       0 B/op	       0 allocs/op
BenchmarkSlash/simple-12      	100000000	        12.9 ns/op	       0 B/op	       0 allocs/op
```

The test passes.

Comment (harshavardhana) [reply cmd/utils.go]: This is neat @klauspost

File: cmd/data-usage.go (hunk 6 above)
Comment (harshavardhana) [reply cmd/data-usage.go:219]: Changing it, this seems to be the issue with the return value.

**Comment by harshavardhana** [comment]
PR is updated @vadmeste @klauspost PTAL

**Comment by minio-ops** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-xl.sh | :heavy_check_mark: |
| mint-worm.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-dist-xl.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :x: [more...](#7f459bf4-9fa8-4252-9086-30643a53f0e7) |
<a name="7f459bf4-9fa8-4252-9086-30643a53f0e7"></a>
### 8856-3376b98/mint-large-bucket.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.53:30530
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 8ceeb427a1c4:/mint/log /tmp/mint-logs'

(1/13) Running awscli tests ... FAILED in 23 seconds
{
  "name": "awscli",
  "duration": 20796,
  "function": "delete_bucket\n",
  "status": "FAIL",
  "error": "fatal error: An error occurred (XMinioServerNotInitialized) when calling the ListObjectsV2 operation (reached max retries: 4): Server not initialized, please try again.remove_bucket failed: Unable to delete all objects in the bucket, bucket will not be deleted."
}

Executed 0 out of 13 tests successfully.
```
Deleting image on docker hub
Deleting image locally

**Comment by minio-ops** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-xl.sh | :heavy_check_mark: |
| mint-worm.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-dist-xl.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :x: [more...](#89588ecb-f3b4-49a4-a11e-f61a9319e95a) |
<a name="89588ecb-f3b4-49a4-a11e-f61a9319e95a"></a>
### 8856-9062427/mint-large-bucket.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.53:32139
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 22ccbf6877ee:/mint/log /tmp/mint-logs'

(1/13) Running awscli tests ... done in 2 minutes and 40 seconds
(2/13) Running aws-sdk-java tests ... done in 1 seconds
(3/13) Running aws-sdk-ruby tests ... done in 9 seconds
(4/13) Running mc tests ... done in 56 seconds
(5/13) Running minio-go tests ... FAILED in 3 minutes and 19 seconds
{
  "args": {},
  "duration": 60322,
  "error": "Please reduce your request",
  "function": "testStorageClassMetadataCopyObject()",
  "message": "CopyObject failed on RRS",
  "name": "minio-go: testStorageClassMetadataCopyObject",
  "status": "FAIL"
}

Executed 4 out of 13 tests successfully.
```
Deleting image on docker hub
Deleting image locally

**Review by vadmeste — APPROVED** [review]
LGTM & tested

**Review by kannappanr — APPROVED** [review]
LGTM
