### PR TITLE
Quick patch for Snowball AutoExtract: #20883

### LINKED ISSUE #20883: `X-Amz-Meta-Snowball-Auto-Extract` unexpected behavior with restrictive `key`
## Problem
I'm using the access key created with the policy below I should only be able to GET and PUT objects on bucket `tarbucket` and **only** when the prefix starts with `myuser/`. However, when using the automatic extraction feature provided by `X-Amz-Meta-Snowball-Auto-Extract=true`, the server seems to write the data into the bucket's "root", even if my access key doesn't allow me to do the analogous operations.

Side effect: This could have implications like data loss via `overwrite` on common clashing `keys`

## Replication
I generate an `accesskey` with the following policy (written in file `key-policy.json`) and add the respective alias `s3tar`
```json
{
 "Version": "2012-10-17",
 "Statement": [
  {
   "Effect": "Allow",
   "Action": [
    "s3:ListBucket"
   ],
   "Resource": [
    "arn:aws:s3:::tarbucket"
   ],
   "Condition": {
    "StringLike": {
     "s3:prefix": [
      "",
      "myuser/*"
     ]
    }
   }
  },
  {
   "Effect": "Allow",
   "Action": [
    "s3:DeleteObject",
    "s3:GetObject",
    "s3:PutObject"
   ],
   "Resource": [
    "arn:aws:s3:::tarbucket/myuser/*"
   ]
  }
 ]
}
```
```bash
mc admin accesskey create --policy key-policy.json --access-key tar-problem --secret-key tar-problem play/
mc alias set s3tar https://play.min.io tar-problem tar-problem

# recreate the bucket with `play` alias
mc rb --force play/tarbucket/
mc mb play/tarbucket/

# Create the only prefix this alias/accesskey should allow
mc mb s3tar/tarbucket/myuser
mc ls --recursive s3tar/tarbucket/

# This should FAIL!
echo helloworld! | mc pipe  s3tar/tarbucket/helloworld

#  Create a sample tar
mkdir -p mydir/{1..3}/{a..c}/
echo HelloWorld! | tee mydir/{1..3}/{a..c}/file.txt
tar -czvf  mydir.tar.gz mydir/

########################################################################
#  PROBLEM: This writes to a prefix which permissions should NOT allow #
########################################################################
mc cp  --disable-multipart --attr "X-Amz-Meta-Snowball-Auto-Extract=true" mydir.tar.gz s3tar/tarbucket/myuser/
# shows nothing
mc ls s3tar/tarbucket/myuser/
# Shows where the tar was extracted to, which is under `tarbucket/mydir/....`
mc ls --recursive s3tar/tarbucket/
# But listing the prefix directly show Access denied as expected
mc ls s3tar/tarbucket/mydir/
```
## Expected behaviour
I guess `Access Denied` should be the outcome of this. However, there's the possible fallback to:
```bash
# This works fine!
mc cp  --disable-multipart --attr "X-Amz-Meta-Snowball-Auto-Extract=true;X-Amz-Meta-Minio-Snowball-Prefix=myuser/" mydir.tar.gz s3tar/tarbucket/myuser/
```
I'm not sure about the role of the `prefix` in this call on "S3 standards", but it would make sense to me that it would fit well on the 'X-Amz-Meta-Minio-Snowball-Prefix' header?!

## Relevant Debug output
```
mc: <DEBUG> PUT /tarbucket/myuser/mydir.tar.gz HTTP/1.1
Host: play.min.io
User-Agent: MinIO (linux; amd64) minio-go/v7.0.83 mc/RELEASE.2025-01-17T23-25-50Z
Content-Length: 390
Accept-Encoding: zstd,gzip
Authorization: AWS4-HMAC-SHA256 Credential=tar-problem/20250130/us-east-1/s3/aws4_request, SignedHeaders=content-type;host;x-amz-content-sha256;x-amz-date;x-amz-meta-snowball-auto-extract, Signature=**REDACTED**
Content-Type: application/gzip
X-Amz-Content-Sha256: UNSIGNED-PAYLOAD
X-Amz-Date: 20250130T164723Z
X-Amz-Meta-Snowball-Auto-Extract: true

mc: <DEBUG> HTTP/1.1 200 OK
Content-Length: 0
```
## Your Environment
* Server version (via 'mc admin info play'): `2024-12-21T04:24:45Z`
* Client version: `mc version RELEASE.2025-01-17T23-25-50Z (commit-id=cc8758c88da31b95dde7b0b6997980ebfb8b98c4)
Runtime: go1.23.5 linux/amd64
Copyright (c) 2015-2025 MinIO, Inc.
License GNU AGPLv3 <https://www.gnu.org/licenses/agpl-3.0.html>`

### PR DESCRIPTION
**Pull request by mannreis**
## Community Contribution License
All community contributions in this pull request are licensed to the project maintainers
under the terms of the [Apache 2 license](https://www.apache.org/licenses/LICENSE-2.0). 
By creating this pull request I represent that I have the right to license the 
contributions to the project maintainers under the Apache 2 license.

## Description
The object name or prefix on Put requests with `X-Amz-Meta-Snowball-Auto-Extract=true` is erroneously checked for permission. Because in reality the url object name is ignored and the extraction targets `bucket/`.

Fixes #20883

## Motivation and Context

I believe there are two ways of fixing this:
 - if not present , default `X-Amz-Meta-Minio-Snowball-Prefix` to the client's request prefix/object. Would this break S3 compatibility!? I didn't check that...
 - Ignoring the request object/prefix [**implemented here**]
 
 Inferring from: https://blog.min.io/minio-optimizes-small-objects/ it seems that only the bucket part of the request should be taken into account.

## Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)

### CODE REVIEW

**Comment by klauspost** [comment]
It will pick up if user doesn't have write access to the root, but you would really need to check every object AFAICT.

File: cmd/object-handlers.go [hunk 1]
```diff
@@ -2229,8 +2229,15 @@ func (api objectAPIHandlers) PutObjectExtractHandler(w http.ResponseWriter, r *h
...
-	// Check if put is allowed
-	if s3Err = isPutActionAllowed(ctx, rAuthType, bucket, object, r, policy.PutObjectAction); s3Err != ErrNone {
+	var opts untarOptions
+	opts.ignoreDirs = strings.EqualFold(r.Header.Get(xhttp.MinIOSnowballIgnoreDirs), "true")
+	opts.ignoreErrs = strings.EqualFold(r.Header.Get(xhttp.MinIOSnowballIgnoreErrors), "true")
+	opts.prefixAll = r.Header.Get(xhttp.MinIOSnowballPrefix)
+	if opts.prefixAll != "" {
+		opts.prefixAll = trimLeadingSlash(pathJoin(opts.prefixAll, slashSeparator))
+	}
+	// Check if put is allow for empty or Snowball prefix see #https://github.com/minio/minio/issues/20883
```
Comment (klauspost) [inline cmd/object-handlers.go]:
```suggestion
	// Check if put is allow for specified prefix.
```

**Comment by mannreis** [comment]
Right... I think it would work for the example without needing to check each object. But with a more exotic key policy it could trigger the same behavior.

File: cmd/object-handlers.go [hunk 2]
```diff
@@ -2298,7 +2305,11 @@ func (api objectAPIHandlers) PutObjectExtractHandler(w http.ResponseWriter, r *h
 
 	putObjectTar := func(reader io.Reader, info os.FileInfo, object string) error {
 		size := info.Size()
-
+		// Check for every object if put is allowed. See #https://github.com/minio/minio/issues/20883
```
Comment (klauspost) [inline cmd/object-handlers.go]:
```suggestion
```
Code is pretty self-explaining.

**Review by klauspost — COMMENTED** [review]
LGTM. Just a few cosmetics.

**Review by klauspost — APPROVED** [review]

**Review by harshavardhana — APPROVED** [review]
