### PR TITLE
server: terminal width should fallback to 80x25.

### LINKED ISSUE #1891: docker: Image fails to start on Red Hat Enterprise Linux 7.2
## Expected behaviour

Be able to start the Minio docker container.
## Actual behaviour

Fails to start and listing the logs on the failed container shows the following results:
`time="2016-06-10T17:14:56Z" level=fatal msg="Unable to colorize experimental update notification string ‘’." error="inappropriate ioctl for device" probe="{\"cause\":25,\"trace\":[{\"line\":50,\"file\":\"notifier.go\",\"func\":\"main.colorizeUpdateMessage\"},{\"line\":93,\"file\":\"update-main.go\",\"func\":\"main.updateMessage.String\",\"env\":{\"Tags\":[\"\"]}}],\"sysinfo\":{\"host.arch\":\"amd64\",\"host.cpus\":\"2\",\"host.lang\":\"go1.6\",\"host.name\":\"abbddcef35f5\",\"host.os\":\"linux\",\"mem.heap.total\":\"4.8MB\",\"mem.heap.used\":\"2.0MB\",\"mem.total\":\"7.7MB\",\"mem.used\":\"2.0MB\"}}" 
time="2016-06-10T17:18:35Z" level=fatal msg="Unable to colorize experimental update notification string ‘’." error="inappropriate ioctl for device" probe="{\"cause\":25,\"trace\":[{\"line\":50,\"file\":\"notifier.go\",\"func\":\"main.colorizeUpdateMessage\"},{\"line\":93,\"file\":\"update-main.go\",\"func\":\"main.updateMessage.String\",\"env\":{\"Tags\":[\"\"]}}],\"sysinfo\":{\"host.arch\":\"amd64\",\"host.cpus\":\"2\",\"host.lang\":\"go1.6\",\"host.name\":\"abbddcef35f5\",\"host.os\":\"linux\",\"mem.heap.total\":\"5.8MB\",\"mem.heap.used\":\"2.0MB\",\"mem.total\":\"7.3MB\",\"mem.used\":\"2.0MB\"}}"`
## Steps to reproduce the behaviour

docker run -p 9000:9000 --name minio1 -v /mnt/export/minio1:/export -v /mnt/config/minio1:/root/.minio  minio/minio /mnt
## Minio version

minio/minio:latest
## System information

RedHat Enterprise Linux 7.2
Docker 1.11.2
Running headless

### PR DESCRIPTION
**Pull request by harshavardhana**
Some environments might disable access to `/dev/tty`, fall
back to '80' in such scenarios.

Move to 'cheggaaa/pb' package for better cross platform
support on fetching terminal width.

Fixes #1891

### CODE REVIEW

File: notifier.go [hunk 1]
```diff
@@ -44,14 +44,18 @@ func colorizeUpdateMessage(updateString string) (string, error) {
...
 	line1Rest := maxContentWidth - line1Length
 
-	terminal, err := ts.GetSize()
-	if err != nil {
-		return "", err
+	// termWidth is set to a default one to use when we are
+	// not able to calculate terminal width via OS syscalls
+	termWidth := 25
+
+	terminalWidth, err := pb.GetTerminalWidth()
```
Comment (abperiasamy) [inline notifier.go]: if width, err := pb.GetTerminalWidth(); err == nil {
    termWidth = width
}

Use shorter names for temporarily scoped variables. Longer names are often more meaningful and indicates that they are scoped to live longer.

Comment (harshavardhana) [inline notifier.go]: > if width, err := pb.GetTerminalWidth(); err == nil {
> termWidth = width
> }
> 
> Use shorter names for temporarily scoped variables. Longer names are often more meaningful and indicates that they are scoped to live longer.

Done
