### PR TITLE
gateway-s3: vendor-update minio-go

### LINKED ISSUE #4218: [gateway] S3: Cannot put an object using signature v2
## Expected Behavior
I should be able to upload an object using signature v2

## Current Behavior
Not able to upload an object using signature v2.

## Possible Solution
No idea.

## Steps to Reproduce (for bugs)
**Terminal 1:**
1. `minio server --address ":9001" /tmp/fs/`

**Terminal 2:**
1. `MINIO_ACCESS_KEY=minio MINIO_SECRET_KEY=minio123 minio gateway s3 http://localhost:9001/`

**Terminal 3:**

1. *Configure mc to point to localhost:9000 and use signature v2*
2. `mc mb myminio/testbucket`
3. `mc cp file myminio/testbucket`

```
ERRO[0002] Unable to create an object. /testbucket/api-stat.go  cause=The request signature we calculated does not match the signature you provided. Check your key and signing method. source=[object-handlers.go:539:objectAPIHandlers.PutObjectHandler()] stack=home/vadmeste/work/gospace/src/github.com/minio/minio/cmd/gateway-s3.go:333:(*s3Gateway).PutObject home/vadmeste/work/gospace/src/github.com/minio/minio/cmd/object-handlers.go:525:objectAPIHandlers.PutObjectHandler home/vadmeste/work/gospace/src/github.com/minio/minio/cmd/api-router.go:60:(objectAPIHandlers).PutObjectHandler-fm
```

## Context
Testing

## Your Environment
All, last master

### PR DESCRIPTION
**Pull request by krishnasrinivas**
## Description

Server was using old minio-go causing signature mismatch when sha256 was empty

Also disable sha256 verification in gateway as the backend server will do it for us.

## Motivation and Context

fixes #4218

## How Has This Been Tested?

manually

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

File: cmd/gateway-s3-anonymous.go [hunk 1]
```diff
@@ -16,18 +16,23 @@
...
+	"io"
+
+	minio "github.com/minio/minio-go"
+)
 
 // AnonGetObject - Get object anonymously
 func (l *s3Gateway) AnonGetObject(bucket string, key string, startOffset int64, length int64, writer io.Writer) error {
-	object, err := l.anonClient.GetObject(bucket, key)
+	r := minio.NewGetReqHeaders()
+	r.SetRange(startOffset, startOffset+length-1)
```
Comment (harshavardhana) [inline cmd/gateway-s3-anonymous.go]: Check for the error.. in-case the offsets are wrong.

File: cmd/gateway-s3.go [hunk 2]
```diff
@@ -264,17 +262,15 @@ func fromMinioClientListBucketResult(bucket string, result minio.ListBucketResul
 // startOffset indicates the starting read location of the object.
 // length indicates the total length of the object.
 func (l *s3Gateway) GetObject(bucket string, key string, startOffset int64, length int64, writer io.Writer) error {
-	object, err := l.Client.GetObject(bucket, key)
+	r := minio.NewGetReqHeaders()
+	r.SetRange(startOffset, startOffset+length-1)
```
Comment (harshavardhana) [inline cmd/gateway-s3.go]: Check for the error..

File: cmd/gateway-s3.go [hunk 3]
```diff
@@ -301,7 +297,8 @@ func fromMinioClientObjectInfo(bucket string, oi minio.ObjectInfo) ObjectInfo {
 
 // GetObjectInfo reads object info and replies back ObjectInfo
 func (l *s3Gateway) GetObjectInfo(bucket string, object string) (objInfo ObjectInfo, err error) {
-	oi, err := l.Client.StatObject(bucket, object)
+	r := minio.NewGetReqHeaders()
```
Comment (harshavardhana) [inline cmd/gateway-s3.go]: Keep it as  `minio.NewHeadReqHeaders()`

**Review by harshavardhana — CHANGES_REQUESTED** [review]

**Review by harshavardhana — APPROVED** [review]

**Review by nl5887 — APPROVED** [review]

**Review by harshavardhana — APPROVED** [review]
