### PR TITLE
Locking: move locking code from xl-erasure to xl-objects.

### LINKED ISSUE #1644: XL: parallel upload of the same part number fails (18th)
parallel upload of the same part number fails:

```
krishna@escape:~/tmp$ go run test.go
2016/05/14 19:52:17 Test: parallel uploads of the same part
2016/05/14 19:52:17 uploadID =  39ac8705-7d27-4a33-8209-f89489698908
2016/05/14 19:52:18 99 The specified key does not exist.
2016/05/14 19:52:18 84 Object name already exists as a directory.
2016/05/14 19:52:18 60 Object name already exists as a directory.
2016/05/14 19:52:18 15 The specified key does not exist.
2016/05/14 19:52:18 11 The specified key does not exist.
2016/05/14 19:52:18 59 The specified key does not exist.
2016/05/14 19:52:18 80 The specified key does not exist.
2016/05/14 19:52:18 66 The specified key does not exist.
2016/05/14 19:52:18 63 The specified key does not exist.
2016/05/14 19:52:18 4 The specified key does not exist.
2016/05/14 19:52:18 85 The specified key does not exist.
2016/05/14 19:52:18 65 The specified key does not exist.
2016/05/14 19:52:18 34 The specified key does not exist.
2016/05/14 19:52:18 41 The specified key does not exist.
2016/05/14 19:52:18 53 The specified key does not exist.
2016/05/14 19:52:18 47 The specified key does not exist.
2016/05/14 19:52:18 39 The specified key does not exist.
2016/05/14 19:52:18 37 The specified key does not exist.
2016/05/14 19:52:18 88 The specified key does not exist.
2016/05/14 19:52:18 74 The specified key does not exist.
2016/05/14 19:52:18 8 The specified key does not exist.
2016/05/14 19:52:18 35 The specified key does not exist.
2016/05/14 19:52:18 45 The specified key does not exist.
2016/05/14 19:52:18 29 The specified key does not exist.
2016/05/14 19:52:18 52 The specified key does not exist.
2016/05/14 19:52:18 54 The specified key does not exist.
2016/05/14 19:52:18 19 The specified key does not exist.
```

### LINKED ISSUE #1649: XL: parallel uploads of small files gives error
```
krishna@escape:~/tmp$ go run test.go
2016/05/16 00:02:47 Object name already exists as a directory.
exit status 1
krishna@escape:~/tmp$ 
```

test code:

```
        {
                size := int64(10)
                randBytes := make([]byte, size)
                rand.Read(randBytes)

                wg := &sync.WaitGroup{}
                count := 100
                errs := make([]error, count)
                for i := 0; i < count; i++ {
                        i := i
                        wg.Add(1)
                        go func() {
                                defer wg.Done()
                                _, err := client.PutObject(bucketName, objectName, bytes.NewBuffer(randBytes), "")
                                errs[i] = err
                        }()
                }
                wg.Wait()
                for _, err := range errs {
                        if err != nil {
                                log.Fatal(err)
                        }
                }
                log.Println("done")
        }
```

### PR DESCRIPTION
**Pull request by krishnasrinivas**
Fixes #1649 #1650 #1624

### CODE REVIEW

File: object-common-multipart.go [hunk 1]
```diff
@@ -84,7 +84,9 @@ func newMultipartUploadCommon(storage StorageAPI, bucket string, object string)
 	if !IsValidObjectName(object) {
 		return "", ObjectNameInvalid{Bucket: bucket, Object: object}
 	}
-
+	// This lock needs to be held for any changes to the directory contents of ".minio/multipart/object/"
+	nsMutex.Lock(bucket, pathJoin(mpartMetaPrefix, bucket, object))
```
Comment (harshavardhana) [inline object-common-multipart.go]: bucket should be 'minioMetaBucket'

File: xl-objects-multipart.go [hunk 2]
```diff
@@ -245,6 +250,10 @@ func (xl xlObjects) CompleteMultipartUpload(bucket string, object string, upload
 		return "", toObjectErr(err, minioMetaBucket, uploadIDIncompletePath)
 	}
 
+	// Hold write lock on the destination before rename
+	nsMutex.Lock(bucket, pathJoin(bucket, object))
```
Comment (harshavardhana) [inline xl-objects-multipart.go]: Isn't the destination already "bucket, object" shouldn't this be 

nsMutex.Lock(bucket, object) ?

Comment (krishnasrinivas) [inline xl-objects-multipart.go]: you are right

File: xl-objects.go [hunk 3]
```diff
@@ -150,6 +156,8 @@ func (xl xlObjects) GetObject(bucket, object string, startOffset int64) (io.Read
 	if !IsValidObjectName(object) {
 		return nil, ObjectNameInvalid{Bucket: bucket, Object: object}
 	}
+	nsMutex.RLock(bucket, object)
+	defer nsMutex.RUnlock(bucket, object)
```
Comment (harshavardhana) [inline xl-objects.go:160]: It is better to perhaps "RUnlock()" after its known that it is a Multipart object, since there would be multiple `RLock()` on the same bucket, object..

Comment (krishnasrinivas) [inline xl-objects.go:160]: Can't let go of the lock because it might introduce a race condition, or I did not understand what you said

Comment (harshavardhana) [inline xl-objects.go:160]: > Can't let go of the lock because it might introduce a race condition, or I did not understand what you said

I mean if you do 'defer' this code would not have unlocked.  Now before the go-routine there is another RLock() which would cause panic.

Comment (krishnasrinivas) [inline xl-objects.go:160]: It won't panic, RLock() will succeed fine as it is a read lock. If it was a write-lock Lock() it would have blocked.
The reason a second RLock() is held is so that in the go-routine we still have a Rlock because the function `GetObject` would have returned hence releasing the lock held at the beginning of the `GetObject`

Comment (harshavardhana) [inline xl-objects.go:160]: > It won't panic, RLock() will succeed fine as it is a read lock. If it was a write-lock Lock() it would have blocked.
> The reason a second RLock() is held is so that in the go-routine we still have a Rlock because the function GetObject would have returned hence releasing the lock held at the beginning of the GetObject

Understood need to clear that up in the code, it can get confusing.

Comment (krishnasrinivas) [inline xl-objects.go:160]: let me add a detailed comment
