### PR TITLE
Remove treewalk abort log message

### LINKED ISSUE #5943: API: ListObjectsV1, Error: treeWalk abort
minio stdout spews such messages:

```
minio_1  | API: ListObjectsV1(bucket=gitlab-registry)
minio_1  | Time: 23:11:54 UTC 05/16/2018
minio_1  | RemoteHost: 192.168.24.55:34022
minio_1  | UserAgent: aws-sdk-go/1.6.12 (go1.9.2; linux; amd64)
minio_1  | Error: treeWalk abort
minio_1  |        1: cmd/tree-walk.go:232:cmd.doTreeWalk()
minio_1  |        2: cmd/tree-walk.go:223:cmd.doTreeWalk()
minio_1  |        3: cmd/tree-walk.go:223:cmd.doTreeWalk()
minio_1  |        4: cmd/tree-walk.go:223:cmd.doTreeWalk()
minio_1  |        5: cmd/tree-walk.go:223:cmd.doTreeWalk()
minio_1  |        6: cmd/tree-walk.go:223:cmd.doTreeWalk()
minio_1  |        7: cmd/tree-walk.go:223:cmd.doTreeWalk()
minio_1  |        8: cmd/tree-walk.go:223:cmd.doTreeWalk()
minio_1  |        9: cmd/tree-walk.go:265:cmd.startTreeWalk.func1()
```

perhaps debug, as i don't notice anything actually broken.

## Your Environment
* Version used (`minio version`): `minio/minio:RELEASE.2018-05-11T00-29-24Z`

### PR DESCRIPTION
**Pull request by kannappanr**
Log doesn't add any value and can be removed.

Fixes #5943

## Description
Ongoing cleanup of unwanted log messages in minio code.

## Motivation and Context
Removal of unwanted log messages in minio server.

## How Has This Been Tested?
Manually

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added unit tests to cover my changes.
- [ ] I have added/updated functional tests in [mint](https://github.com/minio/mint). (If yes, add `mint` PR # here: )
- [x] All new and existing tests passed.

### CODE REVIEW

File: cmd/tree-walk.go [hunk 1]
```diff
@@ -147,7 +147,6 @@ func doTreeWalk(ctx context.Context, bucket, prefixDir, entryPrefixMatch, marker
 	if err != nil {
 		select {
 		case <-endWalkCh:
-			logger.LogIf(ctx, errWalkAbort)
```
Comment (harshavardhana) [inline cmd/tree-walk.go:150]: There is one more place we need to remove it, all the way below in the same file.

**Review by ebozduman — CHANGES_REQUESTED** [review]
There is one more reference to `errWalkAbort` in the code at line number 210 in the same file

**Comment by kannappanr** [comment]
comments have been addressed. PTAL

**Review by ebozduman — APPROVED** [review]

**Review by harshavardhana — APPROVED** [review]
