### PR TITLE
Deprecate config-dir bring in certs-dir for TLS configuration

### LINKED ISSUE #7016: minio server -h output includes a default Path to a deprecated configuration directory. ("/Users/Administrator/.minio")
minio server -h output includes the -C option which shows the path to a configuration directory. The configuration directory has been moved so this statement is no longer valid.

I minio server with the -C option and a valid path. It created the directory, but did not use that directory to hold the configuration files. Perhaps this portion of the code also needs to be removed?

FLAGS:
  --config-dir value, -C value  Path to configuration directory. (default: "/Users/Administrator/.minio")

## Your Environment
mc version RELEASE.2018-12-12T19-02-22Z

$ minio version
Version: 2018-12-19T23:46:24Z
Release-Tag: RELEASE.2018-12-19T23-46-24Z
Commit-ID: 7881791a913dacef9562e7a33a8186503d7967bf

### LINKED ISSUE #7032: configure minio instance documentation
Some time ago the configuration `config.json` was moved into the data directory. This leads to some confusion on my side. I don't know if it is even supposed to work the way it was documented in the past.

The [configuration guide](https://docs.minio.io/docs/minio-server-configuration-guide.html) states that the access key and secret key can be given in the `config.json`. As this file was moved into the data directory, it isn't read. But after the data directory was created with the environment variables supplied, the access key and secret key in the configuration are ignored. So there is just no way to set these variables. Maybe this should be removed in the configuration guide.
There is also no hint anywhere, that the secret and access key need to be provided using environment variables, as the service starts fine without them. I think the best way to handle that case would be to just exit 1 when configuration options are not provided.

After some testing I found minio also listening on all interfaces on port 9000. This can lead to the same problem mongodb had some time ago with being deployed on a server and being open to all requests.

Is it possible to provide add a configuration file which can be written using a configuration management system and minio using this as a base to start all other operations? For me, the most important options at the moment are the other instances, the listening address and secret/access key.
At the same time all config options should be made configurable through all mechanisms. At the moment command line parameters and environment variables are support for some but not all options and need to be collected in the init/rc/systemd script in different ways, which makes the configuration harder than necessary.

## Expected Behavior
Minio should be configurable through a config file and all options should be possible to be provided through command line options and environment variables.

## Current Behavior
At the moment secret and access key can only be provided using environment variables. When monio starts and these variables are missing, it does not crash or hint that these are missing, the cluster is just inaccessible. Normally, this wouldn't regarded as a proper start.

## Possible Solution
One option would be to provide a configuration file which handles the node specific configuration data, like the access and secret key, listening address and peers to use.

## Steps to Reproduce (for bugs)
1. start an instance of minio with config-dir set and no environment variables defined.
2. netstat -ln shows a listening service on port 9000 on all interfaces
3. mc can't connect because of missing credentials

## Context
I am trying to build a minio cluster to get started trying it out and hit this error. I am using a self compiled minio. The plan is to generate the configuration based on documentation, which is  not possible with how minio works at the moment.

## Regression
No idea if this is a regression. But seeing the documentation on config.json, I would say it is.

## Your Environment
* Version used (`minio version`): `root@store1a:/ # minio version
Version: 2018-12-13T02:04:19Z
Release-Tag: RELEASE.2018-12-13T02-04-19Z
Commit-ID: 6f7c99a33325bb11431dd56a1d261a18e5293de3`
* Environment name and version (e.g. nginx 1.9.1): nothing specific, just starting minio
* Server type and version: bare metal server
* Operating System and version (`uname -a`): FreeBSD 12.0-RELEASE

### PR DESCRIPTION
**Pull request by harshavardhana**
## Description
This PR is to provide an indication that config-dir will be removed
in future and all users should migrate to new --certs-dir option

## Motivation and Context
Fixes #7016
Fixes #7032

## Regression
No

## How Has This Been Tested?
Start by testing the command line option by specifying new certs-dir location
```
minio server --certs-dir /tmp/my-certs ~/test
```

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I have added unit tests to cover my changes.
- [ ] I have added/updated functional tests in [mint](https://github.com/minio/mint). (If yes, add `mint` PR # here: )
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by minio-ops** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-tls.sh | :heavy_check_mark: |
| mint-compression-xl.sh | :heavy_check_mark: |
| mint-xl.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-compression-fs.sh | :heavy_check_mark: |
| mint-worm.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-dist-xl.sh | :x: [more...](#ebd7d724-24de-4b03-834c-a9eae0579e5b) |
<a name="ebd7d724-24de-4b03-834c-a9eae0579e5b"></a>
### 7033-fc3fd3c/mint-dist-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      minikube:30539
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 913af3729705:/mint/log /tmp/mint-logs'

(1/13) Running awscli tests ... FAILED in 2 minutes and 21 seconds
{
  "name": "awscli",
  "duration": 69269,
  "function": "delete_bucket\n",
  "status": "FAIL",
  "error": "remove_bucket failed: s3://awscli-mint-test-bucket-23352 An error occurred (BucketNotEmpty) when calling the DeleteBucket operation: The bucket you tried to delete is not empty"
}

Executed 0 out of 13 tests successfully.
```

File: cmd/main.go [hunk 1]
```diff
@@ -32,13 +32,12 @@ var globalFlags = []cli.Flag{
...
-				usage = usage + "  This option must be set."
-			}
-			return usage
-		}(),
+		Usage: "[DEPRECATED] Path to legacy configuration directory.",
+	},
+	cli.StringFlag{
+		Name:  "certs-dir, S",
+		Value: getCertsDir(),
+		Usage: "Path to certs directory.",
```
Comment (balamurugana) [inline cmd/main.go:40]: I have below thoughts on config directories.
1. config directories are constants i.e. only Gets.
2. default config directories need to be probed at `init()` and created at `init()`
3. user defined config directories are validated and created if they are passed.

If above points make sense, below code is good enough
```go

var globalConfigDir *configDir
var globalCertsDir *condfigDir
var globalCADir *configDir

var defaultMinioConfigDir *configDir
var defaultCertsDir *condfigDir
var defaultCADir *configDir

func init() {
    // find and set all default config dirs.
}

type configDir struct {
    path string
}

(dir *configDir) Dir() string {
    return dir.path
}

func newConfigDir(dir string) (&configDir, error) {
    // validate passed dir
    return &configDir{dir}, nil
}

// In `globalFlags`
 	cli.StringFlag{
 		Name:  "config-dir, C",
 		Value: defaultConfigDir.Dir(),
 		Usage: "[DEPRECATED] Path to legacy configuration directory.",
 	},
 	cli.StringFlag{
 		Name:  "certs-dir, S",
 		Value: defaultCertsDir.Dir(),
 		Usage: "Path to certs directory.",
 	},

// In command line argument validations.
globalConfigDir, err = newConfigDir(value-from-cmd)
globalCertsDir, err = newConfigDir(value-from-cmd)
globalCADir, err = newConfigDir(value-from-cmd)
```

Comment (harshavardhana) [reply cmd/main.go:40]: Actually the intention is we should not create unnecessary directories unless user specified them, so doing it in init() is not an option. In container environments we don't have write access everywhere. 

Current code is pretty much doing what you just wrote, let me see if I can simplify it.

Comment (balamurugana) [reply cmd/main.go:40]: My previous comment is not about creating config directories.  Its about how config directory constants are created and used.  Its about implementing with simplicity.

Comment (harshavardhana) [reply cmd/main.go:40]: okay then let me take this approach and see where it leads me. @balamurugana will update the PR

Comment (harshavardhana) [reply cmd/main.go:40]: Done @balamurugana

**Comment by minio-ops** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-tls.sh | :heavy_check_mark: |
| mint-compression-xl.sh | :heavy_check_mark: |
| mint-xl.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-compression-fs.sh | :heavy_check_mark: |
| mint-worm.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-dist-xl.sh | :heavy_check_mark: |

**Comment by minio-ops** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-tls.sh | :heavy_check_mark: |
| mint-compression-xl.sh | :heavy_check_mark: |
| mint-xl.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-compression-fs.sh | :heavy_check_mark: |
| mint-worm.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-dist-xl.sh | :heavy_check_mark: |

**Comment by minio-ops** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-tls.sh | :heavy_check_mark: |
| mint-compression-xl.sh | :heavy_check_mark: |
| mint-xl.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-compression-fs.sh | :heavy_check_mark: |
| mint-worm.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-dist-xl.sh | :heavy_check_mark: |

File: cmd/dir.go [hunk 2]
```diff
@@ -0,0 +1,113 @@
...
+
+	// Public certificate file for HTTPS.
+	publicCertFile = "public.crt"
+
+	// Private key file for HTTPS.
+	privateKeyFile = "private.key"
+)
+
+// Dir - points to a user set directory.
+type Dir struct {
```
Comment (balamurugana) [inline cmd/dir.go]: Naming `Dir` is too generic.  IMO this needs to be more precise to something like `configDir`.  The meaning of `configDir` is any configuration directory constant (immutable object) not the direct meaning to `minioConfigDir`

File: cmd/dir.go [hunk 3]
```diff
@@ -0,0 +1,113 @@
...
+)
+
+func init() {
+	defaultConfigDir = Dir{path: getDefaultConfigDir()}
+	defaultCertsDir = Dir{path: getDefaultCertsDir()}
+	defaultCertsCADir = Dir{path: getDefaultCertsCADir()}
+}
+
+// Get - returns current directory.
+func (dir Dir) Get() string {
```
Comment (balamurugana) [inline cmd/dir.go]: I would prefer to bind to a pointer and using pointer everywhere is better than structure variable copying on every assignment and it makes sure the data does not change (the variable pointing to address change means the value change).

File: cmd/dir.go [hunk 4]
```diff
@@ -0,0 +1,113 @@
...
+func getConfigFile() string {
+	return filepath.Join(globalConfigDir.Get(), minioConfigFile)
+}
+
+func getPublicCertFile() string {
+	return filepath.Join(globalCertsDir.Get(), publicCertFile)
+}
+
+func getPrivateKeyFile() string {
+	return filepath.Join(globalCertsDir.Get(), privateKeyFile)
```
Comment (balamurugana) [inline cmd/dir.go]: My choice here is these file names are set globally only once than calling a function to create every time.

Comment (harshavardhana) [reply cmd/dir.go]: But this is a dynamic value and cannot be set Globally, I want to only keep 3 global variables and rest are obtained based on those values.

Comment (balamurugana) [reply cmd/dir.go]: As my understanding, I believe minio config file, public/private key files are fixed in minio progress lifetime i.e they are created in command line parsing time.

Comment (harshavardhana) [reply cmd/dir.go]: It is fixed but doesn't need to be another global variable. It is simply deduced from a constant global variable, are you saying I shouldn't do that?

I am just trying to avoid making more changes in rest of the code and also only have few global variables in this process.

File: cmd/dir.go (hunk 3 above)
Comment (harshavardhana) [reply cmd/dir.go]: Yeah I can do that.

File: cmd/dir.go (hunk 2 above)
Comment (harshavardhana) [reply cmd/dir.go]: Sure I agree, I might move this into a package perhaps.

**Comment by harshavardhana** [comment]
PR updated @balamurugana @poornas - PTAL

**Comment by minio-ops** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-tls.sh | :heavy_check_mark: |
| mint-compression-xl.sh | :heavy_check_mark: |
| mint-xl.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-compression-fs.sh | :heavy_check_mark: |
| mint-worm.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-dist-xl.sh | :heavy_check_mark: |

**Review by balamurugana — APPROVED** [review]

**Review by poornas — APPROVED** [review]
LGTM
