### PR TITLE
Avoid chown instead fallback to rootpath for user perms

### LINKED ISSUE #7864: When Minio starts, it takes a lot of time to change the permissions of the file directory
Hi,I use docker to run Minio instances (in k8s) on shared NAS volumes as object gateways and share 13TB of data on NAS volumes, which are held by no-root users. At the same time, I set MINIO_USERNAME and MINIO_GROUPNAME as root (because volumes are held by root users in the production environment), and then we found that Minio instances have been changing directory permissions for shared volumes for a long time. I think the source file will decide whether to update directory permissions based on the existence of the “.minio.sys” folder. If I create this folder manually, can I guarantee Minio in the future? Or can you tell me how I should start in the most appropriate way? Thank you！
## Expected Behavior

Quick start when the amount of data is large

## Current Behavior

It takes a lot of time to change the permissions of the file directory

## Steps to Reproduce (for bugs)

This is my resource profile in k8s.
```
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: storage-minio
spec:
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: storage-minio
        component: minio
    spec:
      volumes:
      - name: local-ghome
        hostPath:
          path: "/ghome"
      containers:
      - name: storage-minio
        image: minio/minio:RELEASE.2019-06-19T18-24-42Z
        args:
        - gateway
        - nas
        - /ghome
        env:
        - name: MINIO_ACCESS_KEY
          value: "MINIO_ACCESS_KEY"
        - name: MINIO_SECRET_KEY
          value: "MINIO_SECRET_KEY"
        - name: MINIO_USERNAME
          value: "root"
        - name: MINIO_GROUPNAME
          value: "root"
        ports:
        - containerPort: 9000
          name: client
        volumeMounts:
        - name: local-ghome
          mountPath: "/ghome"
```

## Your Environment

* minio/minio:RELEASE.2019-06-19T18-24-42Z
* docker community 18.09.5
* kubernetes v1.13.5
* ubuntu 16.04

### PR DESCRIPTION
**Pull request by harshavardhana**
## Description
Avoid chown instead fallback to rootpath for user perms

## Motivation and Context
Fixes #7864

## How to test this PR?
Build a docker container 
```
~ mkdir -p /tmp/1
~ TAG=${USER}/minio:perm make docker
~ docker run -v /tmp/1:/data --rm ${USER}/minio:perm minio server /data
```

## Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [x] Fixes a regression (If yes, in PR #7569) 
- [ ] Documentation needed
- [ ] Unit tests needed
- [ ] Functional tests needed (If yes, add [mint](https://github.com/minio/mint) PR # here: )

### CODE REVIEW

**Comment by minio-ops** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-xl.sh | :heavy_check_mark: |
| mint-compression-dist-xl.sh | :heavy_check_mark: |
| mint-compression-fs.sh | :heavy_check_mark: |
| mint-worm.sh | :heavy_check_mark: |
| mint-compression-xl.sh | :x: [more...](#01cfbce2-f2f6-41ee-a6ba-0ea7ff7dae0e) |
| mint-large-bucket.sh | :x: [more...](#f1be0c8e-835f-4610-94bb-441ab3cc53bc) |
| mint-fs.sh | :x: [more...](#c61138d3-1835-4826-9a8b-cf2653708f11) |
| mint-dist-xl.sh | :x: [more...](#94e5b3e6-ba7c-4ab4-9a95-f13c3fa53cbc) |
| mint-gateway-nas.sh | :x: [more...](#d4883b04-7d37-49e7-b48c-0931db497aae) |
<a name="c61138d3-1835-4826-9a8b-cf2653708f11"></a>
### 7874-8606113/mint-fs.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.57:31143
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp eeb96dee8900:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... FAILED in 4 seconds
{
  "alert": "",
  "args": {
    "bucketName": "aws-sdk-go-test-1r10smi1rn0acv",
    "expiry": 60000000000,
    "objectName": "presignedTest"
  },
  "duration": 3062,
  "error": "RequestError: send request failed\ncaused by: Put http://72.28.97.57:31143/aws-sdk-go-test-1r10smi1rn0acv: dial tcp 72.28.97.57:31143: connect: no route to host",
  "function": "PresignedPut",
  "message": "AWS SDK Go CreateBucket Failed",
  "name": "aws-sdk-go",
  "status": "FAIL"
}

Executed 0 out of 14 tests successfully.
```
<a name="01cfbce2-f2f6-41ee-a6ba-0ea7ff7dae0e"></a>
### 7874-8606113/mint-compression-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.55:32679
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 184ee6f53395:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... FAILED in 6 minutes and 0 seconds
{
  "alert": "",
  "args": {
    "bucketName": "aws-sdk-go-test-ml3tglmn6njqhp",
    "expiry": 60000000000,
    "objectName": "presignedTest"
  },
  "duration": 360009,
  "error": "XMinioServerNotInitialized: Server not initialized, please try again.\n\tstatus code: 503, request id: 15ADF6FDDDEB9D23, host id: ",
  "function": "PresignedPut",
  "message": "AWS SDK Go CreateBucket Failed",
  "name": "aws-sdk-go",
  "status": "FAIL"
}

Executed 0 out of 14 tests successfully.
```
<a name="94e5b3e6-ba7c-4ab4-9a95-f13c3fa53cbc"></a>
### 7874-8606113/mint-dist-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.56:31532
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 9d0a27873309:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 0 seconds
(2/14) Running aws-sdk-java tests ... done in 1 seconds
(3/14) Running aws-sdk-php tests ... done in 43 seconds
(4/14) Running aws-sdk-ruby tests ... done in 3 seconds
(5/14) Running awscli tests ... done in 1 minutes and 57 seconds
(6/14) Running healthcheck tests ... done in 0 seconds
(7/14) Running mc tests ... done in 45 seconds
(8/14) Running minio-dotnet tests ... done in 31 seconds
(9/14) Running minio-go tests ... done in 55 seconds
(10/14) Running minio-java tests ... FAILED in 42 seconds
{
  "name": "minio-java",
  "function": "listIncompleteUploads(String bucketName, String prefix)",
  "duration": 1068,
  "status": "FAIL",
  "error": "error occurred\nErrorResponse(code=SlowDown, message=Please reduce your request, bucketName=minio-java-test-1ffkr3c, objectName=minio-java-test-19sru10, resource=/minio-java-test-1ffkr3c/minio-java-test-19sru10, requestId=15ADF6F87284710E, hostId=6b6ab700-a997-4c40-aabb-8b841086aece)\nrequest={method=DELETE, url=http://72.28.97.56:31532/minio-java-test-1ffkr3c/minio-java-test-19sru10?uploadId=6f13bc09-9616-4e6a-8d94-a9edf1d9e51f, headers=Host: 72.28.97.56:31532\nUser-Agent: MinIO (amd64; amd64) minio-java/dev\nx-amz-content-sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855\nx-amz-date: 20190703T174952Z\nAuthorization: AWS4-HMAC-SHA256 Credential=*REDACTED*/20190703/us-east-1/s3/aws4_request, SignedHeaders=host;x-amz-content-sha256;x-amz-date, Signature=*REDACTED*\n}\nresponse={code=503, headers=Accept-Ranges: bytes\nContent-Length: 363\nContent-Security-Policy: block-all-mixed-content\nContent-Type: application/xml\nRetry-After: 120\nServer: MinIO/DEVELOPMENT.2019-07-03T17-31-13Z\nVary: Origin\nX-Amz-Request-Id: 15ADF6F87284710E\nX-Xss-Protection: 1; mode=block\nDate: Wed, 03 Jul 2019 17:49:53 GMT\n}\n >>> [io.minio.MinioClient.executeReq(MinioClient.java:1204), io.minio.MinioClient.execute(MinioClient.java:1070), io.minio.MinioClient.executeDelete(MinioClient.java:1347), io.minio.MinioClient.abortMultipartUpload(MinioClient.java:5149), io.minio.MinioClient.putObject(MinioClient.java:4337), io.minio.MinioClient.putObject(MinioClient.java:4183), FunctionalTest.listIncompleteUploads_test2(FunctionalTest.java:1639), FunctionalTest.runTests(FunctionalTest.java:2989), FunctionalTest.main(FunctionalTest.java:3118)]"
}

Executed 9 out of 14 tests successfully.
```
<a name="f1be0c8e-835f-4610-94bb-441ab3cc53bc"></a>
### 7874-8606113/mint-large-bucket.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.55:30869
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 174c32083c02:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 2 seconds
(2/14) Running aws-sdk-java tests ... done in 1 seconds
(3/14) Running aws-sdk-php tests ... done in 49 seconds
(4/14) Running aws-sdk-ruby tests ... done in 16 seconds
(5/14) Running awscli tests ... done in 1 minutes and 19 seconds
(6/14) Running healthcheck tests ... done in 0 seconds
(7/14) Running mc tests ... FAILED in 2 minutes and 24 seconds
{
  "name": "mc",
  "duration": "114596",
  "function": "test_mirror_list_objects_storage_class",
  "status": "FAIL",
  "error": "/mint/run/core/mc/mc --config-dir /tmp/.mc-9335 --quiet --no-color mirror --storage-class REDUCED_REDUNDANCY /mint/data myminio/mc-test-bucket-5086  >>> \n`/mint/data/datafile-0-b` -> `myminio/mc-test-bucket-5086/datafile-0-b`\n`/mint/data/datafile-1-MB` -> `myminio/mc-test-bucket-5086/datafile-1-MB`\n`/mint/data/datafile-1-kB` -> `myminio/mc-test-bucket-5086/datafile-1-kB`\n`/mint/data/datafile-1-b` -> `myminio/mc-test-bucket-5086/datafile-1-b`\n`/mint/data/datafile-10-MB` -> `myminio/mc-test-bucket-5086/datafile-10-MB`\n`/mint/data/datafile-1.03-MB` -> `myminio/mc-test-bucket-5086/datafile-1.03-MB`\n`/mint/data/datafile-100-kB` -> `myminio/mc-test-bucket-5086/datafile-100-kB`\n`/mint/data/datafile-10-kB` -> `myminio/mc-test-bucket-5086/datafile-10-kB`\n`/mint/data/datafile-129-MB` -> `myminio/mc-test-bucket-5086/datafile-129-MB`\n`/mint/data/datafile-11-MB` -> `myminio/mc-test-bucket-5086/datafile-11-MB`\n`/mint/data/datafile-5-MB` -> `myminio/mc-test-bucket-5086/datafile-5-MB`\n`/mint/data/datafile-33-kB` -> `myminio/mc-test-bucket-5086/datafile-33-kB`\n`/mint/data/datafile-6-MB` -> `myminio/mc-test-bucket-5086/datafile-6-MB`\n`/mint/data/datafile-5243880-b` -> `myminio/mc-test-bucket-5086/datafile-5243880-b`\n`/mint/data/datafile-65-MB` -> `myminio/mc-test-bucket-5086/datafile-65-MB`\nmc: <ERROR> Failed to copy `/mint/data/datafile-10-MB`. Please reduce your request\nmc: <ERROR> Failed to copy `/mint/data/datafile-129-MB`. Please reduce your request\nmc: <ERROR> Failed to copy `/mint/data/datafile-11-MB`. Please reduce your request\nmc: <ERROR> Failed to copy `/mint/data/datafile-65-MB`. Please reduce your request\nTotal: 233.17 MiB, Transferred: 589.42 MiB, Speed: 5.15 MiB/s"
}

Executed 6 out of 14 tests successfully.
```
<a name="d4883b04-7d37-49e7-b48c-0931db497aae"></a>
### 7874-8606113/mint-gateway-nas.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.57:32734
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp e4031210331d:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... FAILED in 4 seconds
{
  "alert": "",
  "args": {
    "bucketName": "aws-sdk-go-test-mgfekxtlwokznj",
    "expiry": 60000000000,
    "objectName": "presignedTest"
  },
  "duration": 3076,
  "error": "RequestError: send request failed\ncaused by: Put http://72.28.97.57:32734/aws-sdk-go-test-mgfekxtlwokznj: dial tcp 72.28.97.57:32734: connect: no route to host",
  "function": "PresignedPut",
  "message": "AWS SDK Go CreateBucket Failed",
  "name": "aws-sdk-go",
  "status": "FAIL"
}

Executed 0 out of 14 tests successfully.
```

**Comment by minio-ops** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-compression-xl.sh | :heavy_check_mark: |
| mint-compression-fs.sh | :heavy_check_mark: |
| mint-worm.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-xl.sh | :x: [more...](#63ad207f-03f0-44e7-a63a-832e9bf2a3e1) |
| mint-large-bucket.sh | :x: [more...](#4e1ef025-f749-447f-827c-a26f8fbede70) |
| mint-compression-dist-xl.sh | :x: [more...](#2567473e-e0fc-4a32-961c-164001ea04fd) |
| mint-dist-xl.sh | :x: [more...](#352ee3d3-ed03-4abd-9624-47928ccdee93) |
<a name="4e1ef025-f749-447f-827c-a26f8fbede70"></a>
### 7874-3426fbd/mint-large-bucket.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.56:31706
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp babb58a423af:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 2 seconds
(2/14) Running aws-sdk-java tests ... done in 2 seconds
(3/14) Running aws-sdk-php tests ... done in 50 seconds
(4/14) Running aws-sdk-ruby tests ... done in 13 seconds
(5/14) Running awscli tests ... done in 2 minutes and 27 seconds
(6/14) Running healthcheck tests ... done in 1 seconds
(7/14) Running mc tests ... FAILED in 1 minutes and 49 seconds
{
  "name": "mc",
  "duration": "87733",
  "function": "test_mirror_list_objects_storage_class",
  "status": "FAIL",
  "error": "/mint/run/core/mc/mc --config-dir /tmp/.mc-5207 --quiet --no-color mirror --storage-class REDUCED_REDUNDANCY /mint/data myminio/mc-test-bucket-31762  >>> \n`/mint/data/datafile-1-MB` -> `myminio/mc-test-bucket-31762/datafile-1-MB`\n`/mint/data/datafile-0-b` -> `myminio/mc-test-bucket-31762/datafile-0-b`\n`/mint/data/datafile-1-kB` -> `myminio/mc-test-bucket-31762/datafile-1-kB`\n`/mint/data/datafile-1-b` -> `myminio/mc-test-bucket-31762/datafile-1-b`\n`/mint/data/datafile-10-MB` -> `myminio/mc-test-bucket-31762/datafile-10-MB`\n`/mint/data/datafile-1.03-MB` -> `myminio/mc-test-bucket-31762/datafile-1.03-MB`\n`/mint/data/datafile-100-kB` -> `myminio/mc-test-bucket-31762/datafile-100-kB`\n`/mint/data/datafile-10-kB` -> `myminio/mc-test-bucket-31762/datafile-10-kB`\n`/mint/data/datafile-129-MB` -> `myminio/mc-test-bucket-31762/datafile-129-MB`\n`/mint/data/datafile-11-MB` -> `myminio/mc-test-bucket-31762/datafile-11-MB`\n`/mint/data/datafile-5-MB` -> `myminio/mc-test-bucket-31762/datafile-5-MB`\n`/mint/data/datafile-33-kB` -> `myminio/mc-test-bucket-31762/datafile-33-kB`\n`/mint/data/datafile-6-MB` -> `myminio/mc-test-bucket-31762/datafile-6-MB`\n`/mint/data/datafile-5243880-b` -> `myminio/mc-test-bucket-31762/datafile-5243880-b`\n`/mint/data/datafile-65-MB` -> `myminio/mc-test-bucket-31762/datafile-65-MB`\nmc: <ERROR> Failed to copy `/mint/data/datafile-11-MB`. Please reduce your request\nmc: <ERROR> Failed to copy `/mint/data/datafile-129-MB`. Please reduce your request\nmc: <ERROR> Failed to copy `/mint/data/datafile-10-MB`. Please reduce your request\nmc: <ERROR> Failed to copy `/mint/data/datafile-65-MB`. Please reduce your request\nTotal: 233.17 MiB, Transferred: 563.52 MiB, Speed: 6.43 MiB/s"
}

Executed 6 out of 14 tests successfully.
```
<a name="63ad207f-03f0-44e7-a63a-832e9bf2a3e1"></a>
### 7874-3426fbd/mint-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.57:31079
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 0ec0e4d49b12:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... FAILED in 3 seconds
{
  "alert": "",
  "args": {
    "bucketName": "aws-sdk-go-test-hqxwkgfjcbamwn",
    "expiry": 60000000000,
    "objectName": "presignedTest"
  },
  "duration": 3066,
  "error": "RequestError: send request failed\ncaused by: Put http://72.28.97.57:31079/aws-sdk-go-test-hqxwkgfjcbamwn: dial tcp 72.28.97.57:31079: connect: no route to host",
  "function": "PresignedPut",
  "message": "AWS SDK Go CreateBucket Failed",
  "name": "aws-sdk-go",
  "status": "FAIL"
}

Executed 0 out of 14 tests successfully.
```
<a name="2567473e-e0fc-4a32-961c-164001ea04fd"></a>
### 7874-3426fbd/mint-compression-dist-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.60:32328
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp e506997f26a1:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... FAILED in 3 seconds
{
  "alert": "",
  "args": {
    "bucketName": "aws-sdk-go-test-tife92rojtuxz9",
    "expiry": 60000000000,
    "objectName": "presignedTest"
  },
  "duration": 3075,
  "error": "RequestError: send request failed\ncaused by: Put http://72.28.97.60:32328/aws-sdk-go-test-tife92rojtuxz9: dial tcp 72.28.97.60:32328: connect: no route to host",
  "function": "PresignedPut",
  "message": "AWS SDK Go CreateBucket Failed",
  "name": "aws-sdk-go",
  "status": "FAIL"
}

Executed 0 out of 14 tests successfully.
```
<a name="352ee3d3-ed03-4abd-9624-47928ccdee93"></a>
### 7874-3426fbd/mint-dist-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.55:31310
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp faf4470e2070:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 0 seconds
(2/14) Running aws-sdk-java tests ... done in 1 seconds
(3/14) Running aws-sdk-php tests ... done in 44 seconds
(4/14) Running aws-sdk-ruby tests ... done in 4 seconds
(5/14) Running awscli tests ... done in 2 minutes and 0 seconds
(6/14) Running healthcheck tests ... done in 0 seconds
(7/14) Running mc tests ... done in 32 seconds
(8/14) Running minio-dotnet tests ... done in 42 seconds
(9/14) Running minio-go tests ... done in 1 minutes and 5 seconds
(10/14) Running minio-java tests ... FAILED in 1 minutes and 7 seconds
{
  "name": "minio-java",
  "function": "presignedGetObject(String bucketName, String objectName, Integer expires)",
  "duration": 168,
  "status": "FAIL",
  "error": "java.lang.Exception: failed to read object. Response: Response{protocol=http/1.1, code=503, message=Service Unavailable, url=http://72.28.97.55:31310/minio-java-test-2f4iala/minio-java-test-3m4hcn7?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=minio%2F20190703%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20190703T195102Z&X-Amz-Expires=3600&X-Amz-SignedHeaders=host&X-Amz-Signature=793b537d96d74efa9b1ef445dee0793ca108588e3fa1fbc5978039e19da44d67}, Response body: <?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<Error><Code>SlowDown</Code><Message>Please reduce your request</Message><Key>minio-java-test-3m4hcn7</Key><BucketName>minio-java-test-2f4iala</BucketName><Resource>/minio-java-test-2f4iala/minio-java-test-3m4hcn7</Resource><RequestId>15ADFD95182CE3BA</RequestId><HostId>9969864b-cd92-4f91-8543-e74410b4ad1b</HostId></Error> >>> [FunctionalTest.readObject(FunctionalTest.java:201), FunctionalTest.presignedGetObject_test2(FunctionalTest.java:1803), FunctionalTest.runTests(FunctionalTest.java:2995), FunctionalTest.main(FunctionalTest.java:3118)]"
}

Executed 9 out of 14 tests successfully.
```

**Comment by minio-ops** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-xl.sh | :heavy_check_mark: |
| mint-compression-dist-xl.sh | :heavy_check_mark: |
| mint-compression-fs.sh | :heavy_check_mark: |
| mint-worm.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-compression-xl.sh | :x: [more...](#c30d1fda-fef6-4172-a397-6e2b2667d578) |
| mint-large-bucket.sh | :x: [more...](#e61f373f-1641-45d4-834c-47d2e290e101) |
| mint-dist-xl.sh | :x: [more...](#66da2f02-eb17-4586-bf88-771909907df5) |
<a name="66da2f02-eb17-4586-bf88-771909907df5"></a>
### 7874-f3de4d4/mint-dist-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.58:32588
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 6d876ed0a292:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 0 seconds
(2/14) Running aws-sdk-java tests ... done in 1 seconds
(3/14) Running aws-sdk-php tests ... done in 44 seconds
(4/14) Running aws-sdk-ruby tests ... done in 4 seconds
(5/14) Running awscli tests ... done in 2 minutes and 6 seconds
(6/14) Running healthcheck tests ... done in 0 seconds
(7/14) Running mc tests ... done in 1 minutes and 1 seconds
(8/14) Running minio-dotnet tests ... done in 46 seconds
(9/14) Running minio-go tests ... done in 1 minutes and 4 seconds
(10/14) Running minio-java tests ... FAILED in 1 minutes and 23 seconds
{
  "name": "minio-java",
  "function": "removeIncompleteUpload(String bucketName, String objectName)",
  "duration": 1575,
  "status": "FAIL",
  "error": "error occurred\nErrorResponse(code=SlowDown, message=Please reduce your request, bucketName=minio-java-test-3ff3gjj, objectName=minio-java-test-kqu5d1, resource=/minio-java-test-3ff3gjj/minio-java-test-kqu5d1, requestId=15ADFF0F3DC38DC7, hostId=f4b9cb33-745e-4248-843a-a4e5ca486a25)\nrequest={method=DELETE, url=http://72.28.97.58:32588/minio-java-test-3ff3gjj/minio-java-test-kqu5d1?uploadId=07ecdadb-e2a0-4db4-bd95-bd9b4cf3d784, headers=Host: 72.28.97.58:32588\nUser-Agent: MinIO (amd64; amd64) minio-java/dev\nx-amz-content-sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855\nx-amz-date: 20190703T201806Z\nAuthorization: AWS4-HMAC-SHA256 Credential=*REDACTED*/20190703/us-east-1/s3/aws4_request, SignedHeaders=host;x-amz-content-sha256;x-amz-date, Signature=*REDACTED*\n}\nresponse={code=503, headers=Accept-Ranges: bytes\nContent-Length: 361\nContent-Security-Policy: block-all-mixed-content\nContent-Type: application/xml\nRetry-After: 120\nServer: MinIO/DEVELOPMENT.2019-07-03T19-57-54Z\nVary: Origin\nX-Amz-Request-Id: 15ADFF0F3DC38DC7\nX-Xss-Protection: 1; mode=block\nDate: Wed, 03 Jul 2019 20:18:07 GMT\n}\n >>> [io.minio.MinioClient.executeReq(MinioClient.java:1204), io.minio.MinioClient.execute(MinioClient.java:1070), io.minio.MinioClient.executeDelete(MinioClient.java:1347), io.minio.MinioClient.abortMultipartUpload(MinioClient.java:5149), io.minio.MinioClient.putObject(MinioClient.java:4337), io.minio.MinioClient.putObject(MinioClient.java:4183), FunctionalTest.removeIncompleteUploads_test(FunctionalTest.java:1719), FunctionalTest.runTests(FunctionalTest.java:2992), FunctionalTest.main(FunctionalTest.java:3118)]"
}

Executed 9 out of 14 tests successfully.
```
<a name="c30d1fda-fef6-4172-a397-6e2b2667d578"></a>
### 7874-f3de4d4/mint-compression-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.57:31006
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp a898b9e66707:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... FAILED in 3 seconds
{
  "alert": "",
  "args": {
    "bucketName": "aws-sdk-go-test-4bqz5bkze2gi5o",
    "expiry": 60000000000,
    "objectName": "presignedTest"
  },
  "duration": 3072,
  "error": "RequestError: send request failed\ncaused by: Put http://72.28.97.57:31006/aws-sdk-go-test-4bqz5bkze2gi5o: dial tcp 72.28.97.57:31006: connect: no route to host",
  "function": "PresignedPut",
  "message": "AWS SDK Go CreateBucket Failed",
  "name": "aws-sdk-go",
  "status": "FAIL"
}

Executed 0 out of 14 tests successfully.
```
<a name="e61f373f-1641-45d4-834c-47d2e290e101"></a>
### 7874-f3de4d4/mint-large-bucket.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.56:30512
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp fe82b9361f14:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 2 seconds
(2/14) Running aws-sdk-java tests ... done in 2 seconds
(3/14) Running aws-sdk-php tests ... done in 48 seconds
(4/14) Running aws-sdk-ruby tests ... done in 12 seconds
(5/14) Running awscli tests ... done in 2 minutes and 21 seconds
(6/14) Running healthcheck tests ... done in 0 seconds
(7/14) Running mc tests ... FAILED in 2 minutes and 34 seconds
{
  "name": "mc",
  "duration": "100871",
  "function": "test_mirror_list_objects_storage_class",
  "status": "FAIL",
  "error": "/mint/run/core/mc/mc --config-dir /tmp/.mc-27339 --quiet --no-color mirror --storage-class REDUCED_REDUNDANCY /mint/data myminio/mc-test-bucket-13887  >>> \n`/mint/data/datafile-1-MB` -> `myminio/mc-test-bucket-13887/datafile-1-MB`\n`/mint/data/datafile-0-b` -> `myminio/mc-test-bucket-13887/datafile-0-b`\n`/mint/data/datafile-1.03-MB` -> `myminio/mc-test-bucket-13887/datafile-1.03-MB`\n`/mint/data/datafile-1-kB` -> `myminio/mc-test-bucket-13887/datafile-1-kB`\n`/mint/data/datafile-100-kB` -> `myminio/mc-test-bucket-13887/datafile-100-kB`\n`/mint/data/datafile-11-MB` -> `myminio/mc-test-bucket-13887/datafile-11-MB`\n`/mint/data/datafile-10-MB` -> `myminio/mc-test-bucket-13887/datafile-10-MB`\n`/mint/data/datafile-1-b` -> `myminio/mc-test-bucket-13887/datafile-1-b`\n`/mint/data/datafile-10-kB` -> `myminio/mc-test-bucket-13887/datafile-10-kB`\n`/mint/data/datafile-33-kB` -> `myminio/mc-test-bucket-13887/datafile-33-kB`\n`/mint/data/datafile-129-MB` -> `myminio/mc-test-bucket-13887/datafile-129-MB`\n`/mint/data/datafile-5243880-b` -> `myminio/mc-test-bucket-13887/datafile-5243880-b`\n`/mint/data/datafile-65-MB` -> `myminio/mc-test-bucket-13887/datafile-65-MB`\n`/mint/data/datafile-5-MB` -> `myminio/mc-test-bucket-13887/datafile-5-MB`\n`/mint/data/datafile-6-MB` -> `myminio/mc-test-bucket-13887/datafile-6-MB`\nmc: <ERROR> Failed to copy `/mint/data/datafile-65-MB`. Please reduce your request\nmc: <ERROR> Failed to copy `/mint/data/datafile-129-MB`. Please reduce your request\nmc: <ERROR> Failed to copy `/mint/data/datafile-11-MB`. Please reduce your request\nmc: <ERROR> Failed to copy `/mint/data/datafile-10-MB`. Please reduce your request\nTotal: 233.17 MiB, Transferred: 557.39 MiB, Speed: 5.53 MiB/s"
}

Executed 6 out of 14 tests successfully.
```

**Review by wlan0 — APPROVED** [review]

File: dockerscripts/check-user.go [hunk 1]
```diff
@@ -43,13 +42,13 @@ func getUserGroup(path string) (string, error) {
...
 		if os.IsNotExist(err) {
-			cmd := exec.Command("chown", "-R", defaultUserGroup, path)
-			if err = cmd.Run(); err != nil {
+			fi, err = os.Stat(path)
+			if err != nil {
 				return "", err
 			}
-			return defaultUserGroup, nil
+		} else {
+			return "", err
```
Comment (krishnasrinivas) [inline dockerscripts/check-user.go:50]: following reads better (i.e return-early style)
```
if err != nil {
    if !os.IsNotExist(err) {
        return "", err
    }
    fi, err = os.Stat(path)
    if err != nil {
        return "", err
    }
}
```

**Review by krishnasrinivas — APPROVED** [review]

**Comment by minio-ops** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-compression-xl.sh | :heavy_check_mark: |
| mint-xl.sh | :heavy_check_mark: |
| mint-compression-fs.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :x: [more...](#7a19e979-8621-49ac-8004-b8cf10684809) |
| mint-compression-dist-xl.sh | :x: [more...](#a7c8c16a-69e2-4ecf-87c6-f86ac7b3b66c) |
| mint-worm.sh | :x: [more...](#babb1cbb-98ed-4a4b-b257-7a9cc93cc5a7) |
| mint-dist-xl.sh | :x: [more...](#906e264d-ba7c-4eda-80f9-9d9eb35084e5) |
<a name="7a19e979-8621-49ac-8004-b8cf10684809"></a>
### 7874-80ff085/mint-large-bucket.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.54:30582
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 2a84de84cae9:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 3 seconds
(2/14) Running aws-sdk-java tests ... done in 2 seconds
(3/14) Running aws-sdk-php tests ... done in 48 seconds
(4/14) Running aws-sdk-ruby tests ... done in 16 seconds
(5/14) Running awscli tests ... done in 2 minutes and 28 seconds
(6/14) Running healthcheck tests ... done in 1 seconds
(7/14) Running mc tests ... FAILED in 2 minutes and 22 seconds
{
  "name": "mc",
  "duration": "103148",
  "function": "test_mirror_list_objects_storage_class",
  "status": "FAIL",
  "error": "/mint/run/core/mc/mc --config-dir /tmp/.mc-21948 --quiet --no-color mirror --storage-class REDUCED_REDUNDANCY /mint/data myminio/mc-test-bucket-13190  >>> \n`/mint/data/datafile-1-MB` -> `myminio/mc-test-bucket-13190/datafile-1-MB`\n`/mint/data/datafile-0-b` -> `myminio/mc-test-bucket-13190/datafile-0-b`\n`/mint/data/datafile-1-kB` -> `myminio/mc-test-bucket-13190/datafile-1-kB`\n`/mint/data/datafile-1-b` -> `myminio/mc-test-bucket-13190/datafile-1-b`\n`/mint/data/datafile-1.03-MB` -> `myminio/mc-test-bucket-13190/datafile-1.03-MB`\n`/mint/data/datafile-10-MB` -> `myminio/mc-test-bucket-13190/datafile-10-MB`\n`/mint/data/datafile-11-MB` -> `myminio/mc-test-bucket-13190/datafile-11-MB`\n`/mint/data/datafile-100-kB` -> `myminio/mc-test-bucket-13190/datafile-100-kB`\n`/mint/data/datafile-10-kB` -> `myminio/mc-test-bucket-13190/datafile-10-kB`\n`/mint/data/datafile-129-MB` -> `myminio/mc-test-bucket-13190/datafile-129-MB`\n`/mint/data/datafile-33-kB` -> `myminio/mc-test-bucket-13190/datafile-33-kB`\n`/mint/data/datafile-5243880-b` -> `myminio/mc-test-bucket-13190/datafile-5243880-b`\n`/mint/data/datafile-5-MB` -> `myminio/mc-test-bucket-13190/datafile-5-MB`\n`/mint/data/datafile-65-MB` -> `myminio/mc-test-bucket-13190/datafile-65-MB`\n`/mint/data/datafile-6-MB` -> `myminio/mc-test-bucket-13190/datafile-6-MB`\nmc: <ERROR> Failed to copy `/mint/data/datafile-129-MB`. Please reduce your request\nmc: <ERROR> Failed to copy `/mint/data/datafile-65-MB`. Please reduce your request\nmc: <ERROR> Failed to copy `/mint/data/datafile-10-MB`. Please reduce your request\nmc: <ERROR> Failed to copy `/mint/data/datafile-11-MB`. Please reduce your request\nTotal: 233.17 MiB, Transferred: 570.45 MiB, Speed: 5.53 MiB/s"
}

Executed 6 out of 14 tests successfully.
```
<a name="a7c8c16a-69e2-4ecf-87c6-f86ac7b3b66c"></a>
### 7874-80ff085/mint-compression-dist-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.60:31713
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 8aec79b5bd2f:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... FAILED in 3 seconds
{
  "alert": "",
  "args": {
    "bucketName": "aws-sdk-go-test-jphqguilfw3msq",
    "expiry": 60000000000,
    "objectName": "presignedTest"
  },
  "duration": 2635,
  "error": "RequestError: send request failed\ncaused by: Put http://72.28.97.60:31713/aws-sdk-go-test-jphqguilfw3msq: dial tcp 72.28.97.60:31713: connect: no route to host",
  "function": "PresignedPut",
  "message": "AWS SDK Go CreateBucket Failed",
  "name": "aws-sdk-go",
  "status": "FAIL"
}

Executed 0 out of 14 tests successfully.
```
<a name="babb1cbb-98ed-4a4b-b257-7a9cc93cc5a7"></a>
### 7874-80ff085/mint-worm.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.60:30072
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            worm
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp aa6f903c6c1b:/mint/log /tmp/mint-logs'

(1/1) Running worm tests ... FAILED in 3 seconds
{
  "alert": "",
  "args": {
    "bucketName": "bucket-pto4py8bzbjkvhvpp1kzl4gjeqimvly6gf8ey1gd8qdxvd5yk034gpr",
    "expiry": 60000000000,
    "objectName": "testObject"
  },
  "duration": 3076,
  "error": "RequestError: send request failed\ncaused by: Put http://72.28.97.60:30072/bucket-pto4py8bzbjkvhvpp1kzl4gjeqimvly6gf8ey1gd8qdxvd5yk034gpr: dial tcp 72.28.97.60:30072: connect: no route to host",
  "function": "PutAndDelete",
  "message": "WORM_MODE ON  - CreateBucket Failed",
  "name": "test worm mode",
  "status": "FAIL"
}

Executed 0 out of 1 tests successfully.
```
<a name="906e264d-ba7c-4eda-80f9-9d9eb35084e5"></a>
### 7874-80ff085/mint-dist-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.53:30805
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp b80fa295897c:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 0 seconds
(2/14) Running aws-sdk-java tests ... done in 1 seconds
(3/14) Running aws-sdk-php tests ... done in 44 seconds
(4/14) Running aws-sdk-ruby tests ... done in 3 seconds
(5/14) Running awscli tests ... done in 2 minutes and 4 seconds
(6/14) Running healthcheck tests ... done in 0 seconds
(7/14) Running mc tests ... done in 50 seconds
(8/14) Running minio-dotnet tests ... done in 42 seconds
(9/14) Running minio-go tests ... done in 59 seconds
(10/14) Running minio-java tests ... FAILED in 1 minutes and 28 seconds
{
  "name": "minio-java",
  "function": "presignedGetObject(String bucketName, String objectName)",
  "duration": 99,
  "status": "FAIL",
  "error": "java.lang.Exception: failed to read object. Response: Response{protocol=http/1.1, code=503, message=Service Unavailable, url=http://72.28.97.53:30805/minio-java-test-1jc9jos/minio-java-test-15v61ug?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=minio%2F20190704%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20190704T011108Z&X-Amz-Expires=604800&X-Amz-SignedHeaders=host&X-Amz-Signature=6109f45c981f262503710ea5517e9be17f095443b0a5e1d47b45d7228c9a0c2c}, Response body: <?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<Error><Code>SlowDown</Code><Message>Please reduce your request</Message><Key>minio-java-test-15v61ug</Key><BucketName>minio-java-test-1jc9jos</BucketName><Resource>/minio-java-test-1jc9jos/minio-java-test-15v61ug</Resource><RequestId>15AE0F0CBF574E27</RequestId><HostId>c1e94cf1-427e-4d07-9580-12e857618103</HostId></Error> >>> [FunctionalTest.readObject(FunctionalTest.java:201), FunctionalTest.presignedGetObject_test1(FunctionalTest.java:1767), FunctionalTest.runTests(FunctionalTest.java:2994), FunctionalTest.main(FunctionalTest.java:3118)]"
}

Executed 9 out of 14 tests successfully.
```
