### PR TITLE
rpc: Protect racy access of internal auth states.

### LINKED ISSUE #3232: [distributed]: Data race  when nodes are restarted.
-  server didn't respond for while but CPU usage was very high (around 700%) when nodes are stopped and started randomly.
- Later when it started most of the nodes reported data race. (binary was built with -race flag) and the process dies with exceeding go routine limits.
## Expected Behavior

- Data race shouldnt happen.
## Current Behavior

here is the data race log.

```
Initializing data volume.
[01/08] http://minio1:9199/tmp/rao1 - 218 GiB online
[02/08] http://minio2:9199/tmp/rao1 - 218 GiB online
[03/08] http://minio3:9199/tmp/rao1 - 0 B offline
[04/08] http://minio4:9199/tmp/rao1 - 218 GiB online
[05/08] http://minio5:9199/tmp/rao1 - 218 GiB online
[06/08] http://minio6:9199/tmp/rao1 - 218 GiB online
[07/08] http://minio7:9199/tmp/rao1 - 218 GiB online
[08/08] http://minio8:9199/tmp/rao1 - 218 GiB online
==================
WARNING: DATA RACE
Read at 0x00c420430f50 by goroutine 293:
  github.com/minio/minio/cmd.(*AuthRPCClient).Login()
      /root/work/src/github.com/minio/minio/cmd/auth-rpc-client.go:128 +0x5f
  github.com/minio/minio/cmd.(*AuthRPCClient).Call()
      /root/work/src/github.com/minio/minio/cmd/auth-rpc-client.go:161 +0x45
  github.com/minio/minio/vendor/github.com/minio/dsync.lock.func1()
      /root/work/src/github.com/minio/minio/vendor/github.com/minio/dsync/drwmutex.go:172 +0x484

Previous write at 0x00c420430f50 by goroutine 61:
  github.com/minio/minio/cmd.(*AuthRPCClient).Login()
      /root/work/src/github.com/minio/minio/cmd/auth-rpc-client.go:149 +0x5b6
  github.com/minio/minio/cmd.(*AuthRPCClient).Call()
      /root/work/src/github.com/minio/minio/cmd/auth-rpc-client.go:161 +0x45
  github.com/minio/minio/vendor/github.com/minio/dsync.lock.func1()
      /root/work/src/github.com/minio/minio/vendor/github.com/minio/dsync/drwmutex.go:172 +0x484

Goroutine 293 (running) created at:
github.com/minio/minio/vendor/github.com/minio/dsync.lock()
      /root/work/src/github.com/minio/minio/vendor/github.com/minio/dsync/drwmutex.go:191 +0x137
  github.com/minio/minio/vendor/github.com/minio/dsync.(*DRWMutex).lockBlocking()
      /root/work/src/github.com/minio/minio/vendor/github.com/minio/dsync/drwmutex.go:120 +0x1ab
  github.com/minio/minio/vendor/github.com/minio/dsync.(*DRWMutex).RLock()
      /root/work/src/github.com/minio/minio/vendor/github.com/minio/dsync/drwmutex.go:104 +0x3d
  github.com/minio/minio/cmd.(*nsLockMap).lock()
      /root/work/src/github.com/minio/minio/cmd/namespace-lock.go:140 +0x255
  github.com/minio/minio/cmd.(*lockInstance).RLock()
      /root/work/src/github.com/minio/minio/cmd/namespace-lock.go:290 +0xed
  github.com/minio/minio/cmd.xlObjects.GetBucketInfo()
      /root/work/src/github.com/minio/minio/cmd/xl-v1-bucket.go:177 +0x123
  github.com/minio/minio/cmd.(*xlObjects).GetBucketInfo()
      <autogenerated>:840 +0xfe
  github.com/minio/minio/cmd.isBucketExist()
      /root/work/src/github.com/minio/minio/cmd/object-common.go:282 +0x9e
  github.com/minio/minio/cmd.readBucketPolicyJSON()
      /root/work/src/github.com/minio/minio/cmd/bucket-policy.go:146 +0x7a
  github.com/minio/minio/cmd.readBucketPolicy()
      /root/work/src/github.com/minio/minio/cmd/bucket-policy.go:178 +0x63
  github.com/minio/minio/cmd.loadAllBucketPolicies()
      /root/work/src/github.com/minio/minio/cmd/bucket-policy.go:87 +0x290
  github.com/minio/minio/cmd.initBucketPolicies()
      /root/work/src/github.com/minio/minio/cmd/bucket-policy.go:118 +0x52
  github.com/minio/minio/cmd.newObjectLayer()
      /root/work/src/github.com/minio/minio/cmd/routers.go:69 +0x230
  github.com/minio/minio/cmd.serverMain()
      /root/work/src/github.com/minio/minio/cmd/server-main.go:492 +0xdf6
  github.com/minio/minio/vendor/github.com/minio/cli.Command.Run()
      /root/work/src/github.com/minio/minio/vendor/github.com/minio/cli/command.go:117 +0x10d7
  github.com/minio/minio/vendor/github.com/minio/cli.(*App).Run()
      /root/work/src/github.com/minio/minio/vendor/github.com/minio/cli/app.go:186 +0x34c
  github.com/minio/minio/vendor/github.com/minio/cli.(*App).RunAndExitOnError()
      /root/work/src/github.com/minio/minio/vendor/github.com/minio/cli/app.go:197 +0x70
  github.com/minio/minio/cmd.Main()
      /root/work/src/github.com/minio/minio/cmd/main.go:226 +0x95
  main.main()
      /root/work/src/github.com/minio/minio/main.go:22 +0x2f

Goroutine 61 (finished) created at:
  github.com/minio/minio/vendor/github.com/minio/dsync.lock()
      /root/work/src/github.com/minio/minio/vendor/github.com/minio/dsync/drwmutex.go:191 +0x137
  github.com/minio/minio/vendor/github.com/minio/dsync.(*DRWMutex).lockBlocking()
      /root/work/src/github.com/minio/minio/vendor/github.com/minio/dsync/drwmutex.go:120 +0x1ab
  github.com/minio/minio/vendor/github.com/minio/dsync.(*DRWMutex).RLock()
      /root/work/src/github.com/minio/minio/vendor/github.com/minio/dsync/drwmutex.go:104 +0x3d
  github.com/minio/minio/cmd.(*nsLockMap).lock()
  /root/work/src/github.com/minio/minio/cmd/namespace-lock.go:140 +0x255
  github.com/minio/minio/cmd.(*lockInstance).RLock()
      /root/work/src/github.com/minio/minio/cmd/namespace-lock.go:290 +0xed
  github.com/minio/minio/cmd.xlObjects.GetBucketInfo()
      /root/work/src/github.com/minio/minio/cmd/xl-v1-bucket.go:177 +0x123
  github.com/minio/minio/cmd.(*xlObjects).GetBucketInfo()
      <autogenerated>:840 +0xfe
  github.com/minio/minio/cmd.isBucketExist()
      /root/work/src/github.com/minio/minio/cmd/object-common.go:282 +0x9e
  github.com/minio/minio/cmd.readBucketPolicyJSON()
      /root/work/src/github.com/minio/minio/cmd/bucket-policy.go:146 +0x7a
  github.com/minio/minio/cmd.readBucketPolicy()
      /root/work/src/github.com/minio/minio/cmd/bucket-policy.go:178 +0x63
  github.com/minio/minio/cmd.loadAllBucketPolicies()
      /root/work/src/github.com/minio/minio/cmd/bucket-policy.go:87 +0x290
  github.com/minio/minio/cmd.initBucketPolicies()
      /root/work/src/github.com/minio/minio/cmd/bucket-policy.go:118 +0x52
  github.com/minio/minio/cmd.newObjectLayer()
      /root/work/src/github.com/minio/minio/cmd/routers.go:69 +0x230
  github.com/minio/minio/cmd.serverMain()
      /root/work/src/github.com/minio/minio/cmd/server-main.go:492 +0xdf6
  github.com/minio/minio/vendor/github.com/minio/cli.Command.Run()
      /root/work/src/github.com/minio/minio/vendor/github.com/minio/cli/command.go:117 +0x10d7
  github.com/minio/minio/vendor/github.com/minio/cli.(*App).Run()
      /root/work/src/github.com/minio/minio/vendor/github.com/minio/cli/app.go:186 +0x34c
  github.com/minio/minio/vendor/github.com/minio/cli.(*App).RunAndExitOnError()
      /root/work/src/github.com/minio/minio/vendor/github.com/minio/cli/app.go:197 +0x70
  github.com/minio/minio/cmd.Main()
      /root/work/src/github.com/minio/minio/cmd/main.go:226 +0x95
  main.main()
      /root/work/src/github.com/minio/minio/main.go:22 +0x2f
==================
==================
WARNING: DATA RACE
Read at 0x00c420430f58 by goroutine 293:
  github.com/minio/minio/cmd.(*AuthRPCClient).Call()
      /root/work/src/github.com/minio/minio/cmd/auth-rpc-client.go:163 +0x9f
  github.com/minio/minio/vendor/github.com/minio/dsync.lock.func1()
      /root/work/src/github.com/minio/minio/vendor/github.com/minio/dsync/drwmutex.go:172 +0x484

Previous write at 0x00c420430f58 by goroutine 61:
  github.com/minio/minio/cmd.(*AuthRPCClient).Login()
      /root/work/src/github.com/minio/minio/cmd/auth-rpc-client.go:147 +0x511
  github.com/minio/minio/cmd.(*AuthRPCClient).Call()
      /root/work/src/github.com/minio/minio/cmd/auth-rpc-client.go:161 +0x45
  github.com/minio/minio/vendor/github.com/minio/dsync.lock.func1()
      /root/work/src/github.com/minio/minio/vendor/github.com/minio/dsync/drwmutex.go:172 +0x484

Goroutine 293 (running) created at:
  github.com/minio/minio/vendor/github.com/minio/dsync.lock()
      /root/work/src/github.com/minio/minio/vendor/github.com/minio/dsync/drwmutex.go:191 +0x137
 github.com/minio/minio/vendor/github.com/minio/dsync.(*DRWMutex).lockBlocking()                                                                                           [25/1990]
      /root/work/src/github.com/minio/minio/vendor/github.com/minio/dsync/drwmutex.go:120 +0x1ab
  github.com/minio/minio/vendor/github.com/minio/dsync.(*DRWMutex).RLock()
      /root/work/src/github.com/minio/minio/vendor/github.com/minio/dsync/drwmutex.go:104 +0x3d
  github.com/minio/minio/cmd.(*nsLockMap).lock()
      /root/work/src/github.com/minio/minio/cmd/namespace-lock.go:140 +0x255
  github.com/minio/minio/cmd.(*lockInstance).RLock()
      /root/work/src/github.com/minio/minio/cmd/namespace-lock.go:290 +0xed
  github.com/minio/minio/cmd.xlObjects.GetBucketInfo()
      /root/work/src/github.com/minio/minio/cmd/xl-v1-bucket.go:177 +0x123
  github.com/minio/minio/cmd.(*xlObjects).GetBucketInfo()
      <autogenerated>:840 +0xfe
  github.com/minio/minio/cmd.isBucketExist()
      /root/work/src/github.com/minio/minio/cmd/object-common.go:282 +0x9e
  github.com/minio/minio/cmd.readBucketPolicyJSON()
      /root/work/src/github.com/minio/minio/cmd/bucket-policy.go:146 +0x7a
  github.com/minio/minio/cmd.readBucketPolicy()
      /root/work/src/github.com/minio/minio/cmd/bucket-policy.go:178 +0x63
  github.com/minio/minio/cmd.loadAllBucketPolicies()
      /root/work/src/github.com/minio/minio/cmd/bucket-policy.go:87 +0x290
  github.com/minio/minio/cmd.initBucketPolicies()
      /root/work/src/github.com/minio/minio/cmd/bucket-policy.go:118 +0x52
  github.com/minio/minio/cmd.newObjectLayer()
      /root/work/src/github.com/minio/minio/cmd/routers.go:69 +0x230
  github.com/minio/minio/cmd.serverMain()
      /root/work/src/github.com/minio/minio/cmd/server-main.go:492 +0xdf6
  github.com/minio/minio/vendor/github.com/minio/cli.Command.Run()
      /root/work/src/github.com/minio/minio/vendor/github.com/minio/cli/command.go:117 +0x10d7
  github.com/minio/minio/vendor/github.com/minio/cli.(*App).Run()
      /root/work/src/github.com/minio/minio/vendor/github.com/minio/cli/app.go:186 +0x34c
  github.com/minio/minio/vendor/github.com/minio/cli.(*App).RunAndExitOnError()
      /root/work/src/github.com/minio/minio/vendor/github.com/minio/cli/app.go:197 +0x70
  github.com/minio/minio/cmd.Main()
      /root/work/src/github.com/minio/minio/cmd/main.go:226 +0x95
  main.main()
      /root/work/src/github.com/minio/minio/main.go:22 +0x2f

Goroutine 61 (finished) created at:
  github.com/minio/minio/vendor/github.com/minio/dsync.lock()
      /root/work/src/github.com/minio/minio/vendor/github.com/minio/dsync/drwmutex.go:191 +0x137
  github.com/minio/minio/vendor/github.com/minio/dsync.(*DRWMutex).lockBlocking()
      /root/work/src/github.com/minio/minio/vendor/github.com/minio/dsync/drwmutex.go:120 +0x1ab
  github.com/minio/minio/vendor/github.com/minio/dsync.(*DRWMutex).RLock()
      /root/work/src/github.com/minio/minio/vendor/github.com/minio/dsync/drwmutex.go:104 +0x3d
  github.com/minio/minio/cmd.(*nsLockMap).lock()
      /root/work/src/github.com/minio/minio/cmd/namespace-lock.go:140 +0x255
  github.com/minio/minio/cmd.(*lockInstance).RLock()
      /root/work/src/github.com/minio/minio/cmd/namespace-lock.go:290 +0xed
  github.com/minio/minio/cmd.xlObjects.GetBucketInfo()
      /root/work/src/github.com/minio/minio/cmd/xl-v1-bucket.go:177 +0x123
  github.com/minio/minio/cmd.(*xlObjects).GetBucketInfo()
      <autogenerated>:840 +0xfe
  github.com/minio/minio/cmd.isBucketExist()
      /root/work/src/github.com/minio/minio/cmd/object-common.go:282 +0x9e
  github.com/minio/minio/cmd.readBucketPolicyJSON()
      /root/work/src/github.com/minio/minio/cmd/bucket-policy.go:146 +0x7a
  github.com/minio/minio/cmd.readBucketPolicy()
      /root/work/src/github.com/minio/minio/cmd/bucket-policy.go:178 +0x63
  github.com/minio/minio/cmd.loadAllBucketPolicies()
      /root/work/src/github.com/minio/minio/cmd/bucket-policy.go:87 +0x290
  github.com/minio/minio/cmd.initBucketPolicies()
      /root/work/src/github.com/minio/minio/cmd/bucket-policy.go:118 +0x52
  github.com/minio/minio/cmd.newObjectLayer()
      /root/work/src/github.com/minio/minio/cmd/routers.go:69 +0x230
  github.com/minio/minio/cmd.serverMain()
      /root/work/src/github.com/minio/minio/cmd/server-main.go:492 +0xdf6
  github.com/minio/minio/vendor/github.com/minio/cli.Command.Run()
      /root/work/src/github.com/minio/minio/vendor/github.com/minio/cli/command.go:117 +0x10d7
  github.com/minio/minio/vendor/github.com/minio/cli.(*App).Run()
      /root/work/src/github.com/minio/minio/vendor/github.com/minio/cli/app.go:186 +0x34c
  github.com/minio/minio/vendor/github.com/minio/cli.(*App).RunAndExitOnError()
      /root/work/src/github.com/minio/minio/vendor/github.com/minio/cli/app.go:197 +0x70
  github.com/minio/minio/cmd.Main()
      /root/work/src/github.com/minio/minio/cmd/main.go:226 +0x95
  main.main()
      /root/work/src/github.com/minio/minio/main.go:22 +0x2f
==================
race: limit on 8192 simultaneously alive goroutines is exceeded, dying
```

## Possible Solution

Not sure.
## Steps to Reproduce (for bugs)

1. Build binary with `-race`. 
2. Start the server on 8 nodes. Randomly kill them and start again
## Context

Testing with nodes being restarted.
## Your Environment

* Version used: Latest master 2f373684f5ce9310fd78677b2d76d1d5ac9cbce8

### PR DESCRIPTION
**Pull request by harshavardhana**
## Description
Add locks to protect race access of auth clients internal states.

## Motivation and Context
Fixes #3232

## How Has This Been Tested?
Manually.

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by harshavardhana** [comment]
ping @hackintoshrao can you pull this PR and test with #3232

File: cmd/auth-rpc-client.go [hunk 1]
```diff
@@ -117,15 +119,20 @@ func newAuthClient(cfg *authConfig) *AuthRPCClient {
...
+	authClient.mu.Lock()
 	// reset token on closing a connection
 	authClient.isLoggedIn = false
+	authClient.mu.Unlock()
 	return authClient.rpc.Close()
 }
 
 // Login - a jwt based authentication is performed with rpc server.
 func (authClient *AuthRPCClient) Login() error {
+	authClient.mu.Lock()
```
Comment (donatello) [inline cmd/auth-rpc-client.go:131]: I think better to serialize calls to `Login()` by just doing:

``` go
func (authClient *AuthRPCClient) Login() error {
        authClient.mu.Lock()
        defer authClient.mu.Unlock()
        // login code follows.
}
```

No point racing to call the loginMethod from multiple threads, right?

**Review by donatello — APPROVED** [review]

**Comment by fwessels** [comment]
LGTM

**Review by krishnasrinivas — APPROVED** [review]
