### PR TITLE
fs/erasure: Ignore objects with / even for DeleteObject()

### LINKED ISSUE #4302: fs/erasure: Return success for objects ending with "/" for DeleteObject()
## Expected Behavior
DeleteObject() behaves the same way as PutObject() for directory operations.

## Current Behavior
```
9:deleteObject object-handlers.go:1023:objectAPIHandlers.DeleteObjectHandler api-router.go:62:(objectAPIHandlers).DeleteObjectHandler-fm" 
time="2017-05-05T09:03:52-03:00" level=error msg="Unable to delete an object minio-backup/MBS-ecae5738-c326-4954-abbc-374120a89ac5/CBB_CITYHALL008/CBB_DiskImage/Disk_00000000-0000-0000-0000-000000000000/Volume_FAT_00000000-0000-0000-0000-000000000000:/20170505115750/" cause="Object name invalid: minio-backup#MBS-ecae5738-c326-4954-abbc-374120a89ac5/CBB_CITYHALL008/CBB_DiskImage/Disk_00000000-0000-0000-0000-000000000000/Volume_FAT_00000000-0000-0000-0000-000000000000:/20170505115750/" source="[object-handlers.go:1024:objectAPIHandlers.DeleteObjectHandler()]" stack="object-api-input-checks.go:39:checkBucketAndObjectNames object-api-input-checks.go:28:checkDelObjArgs fs-v1.go:641:fsObjects.DeleteObject <autogenerated>:407:(*fsObjects).DeleteObject object-handlers-common.go:239:deleteObject object-handlers.go:1023:objectAPIHandlers.DeleteObjectHandler api-router.go:62:(objectAPIHandlers).DeleteObjectHandler-fm"
```

We throw an error on the console.

## Possible Solution
Ignore objects ending with '/' 

## Steps to Reproduce (for bugs)
Just initiate a DeleteObject() request with an object with "/" in it.

## Context
Server testing.

## Your Environment
minio master.

### PR DESCRIPTION
**Pull request by harshavardhana**
## Description
Ignore objects with / even for DeleteObject(). Additionally GetObject() also returns errFileNotFound similar to HeadObject().

## Motivation and Context
Fixes #4302

## How Has This Been Tested?
Manually and `go tests` 

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

File: cmd/fs-v1.go [hunk 1]
```diff
@@ -592,10 +598,9 @@ func (fs fsObjects) GetObjectInfo(bucket, object string) (ObjectInfo, error) {
 func (fs fsObjects) PutObject(bucket string, object string, size int64, data io.Reader, metadata map[string]string, sha256sum string) (objInfo ObjectInfo, retErr error) {
 	var err error
 
-	// This is a special case with size as '0' and object ends with
-	// a slash separator, we treat it like a valid operation and
-	// return success.
-	if isObjectDir(object, size) {
+	// This is a special case object ends witha slash separator,
+	// we treat it like a valid operation and return success.
+	if isObjectDir(object) {
```
Comment (krishnasrinivas) [inline cmd/fs-v1.go]: `if isObjectDir(object) && size == 0` is better?

Comment (harshavardhana) [reply cmd/fs-v1.go]: yes agreed..

File: cmd/fs-v1.go [hunk 2]
```diff
@@ -473,6 +473,12 @@ func (fs fsObjects) CopyObject(srcBucket, srcObject, dstBucket, dstObject string
 // startOffset indicates the starting read location of the object.
 // length indicates the total length of the object.
 func (fs fsObjects) GetObject(bucket, object string, offset int64, length int64, writer io.Writer) (err error) {
+	// This is a special case with object whose name ends with
+	// a slash separator, we always return object not found here.
+	if hasSuffix(object, slashSeparator) {
```
Comment (vadmeste) [inline cmd/fs-v1.go]: Isn't better if we do this check after checkGetObjArgs ?

Comment (harshavardhana) [reply cmd/fs-v1.go]: CheckGetObjArgs would return error.

Comment (vadmeste) [reply cmd/fs-v1.go]: > CheckGetObjArgs would return error.

yeah, I know. 

By the way, checkGetObjArgs calls IsValidObjectName(), this latter is called only from two places. I think it is safe to modify the behavior of IsValidObjectName() and make it accept trailing slash and then we can move your code after checkGetObjArgs. The reason is that any invalid object name with a trailing slash will return object not found, it would be good to take care of that use case.

**Comment by harshavardhana** [comment]
@vadmeste done with all the changes. @krishnasrinivas can you review?

**Comment by krishnasrinivas** [comment]
Since this behavior should not affect `checkPutObjectArgs()` (though in PutObject isObjectDir() check is done before checkPutObjectArgs and hence returns earlier)

better do it this way:

```
--- a/cmd/object-api-input-checks.go
+++ b/cmd/object-api-input-checks.go
@@ -20,12 +20,20 @@ import "github.com/skyrings/skyring-common/tools/uuid"
 
 // Checks on GetObject arguments, bucket and object.
 func checkGetObjArgs(bucket, object string) error {
-       return checkBucketAndObjectNames(bucket, object)
+       err := checkBucketAndObjectNames(bucket, object)
+       if errorCause(err) != nil && hasSuffix(object, slashSeparator) {
+               return traceError(ObjectNotFound{Bucket: bucket, Object: object})
+       }
+       return err
 }
 
 // Checks on DeleteObject arguments, bucket and object.
 func checkDelObjArgs(bucket, object string) error {
-       return checkBucketAndObjectNames(bucket, object)
+       err := checkBucketAndObjectNames(bucket, object)
+       if errorCause(err) != nil && hasSuffix(object, slashSeparator) {
+               return traceError(ObjectNotFound{Bucket: bucket, Object: object})
+       }
+       return err
 }
```

**Comment by harshavardhana** [comment]
> --- a/cmd/object-api-input-checks.go
> +++ b/cmd/object-api-input-checks.go
> @@ -20,12 +20,20 @@ import "github.com/skyrings/skyring-common/tools/uuid"
>  
>  // Checks on GetObject arguments, bucket and object.
>  func checkGetObjArgs(bucket, object string) error {
> -       return checkBucketAndObjectNames(bucket, object)
> +       err := checkBucketAndObjectNames(bucket, object)
> +       if errorCause(err) != nil && hasSuffix(object, slashSeparator) {
> +               return traceError(ObjectNotFound{Bucket: bucket, Object: object})
> +       }
> +       return err
>  }
>  
>  // Checks on DeleteObject arguments, bucket and object.
>  func checkDelObjArgs(bucket, object string) error {
> -       return checkBucketAndObjectNames(bucket, object)
> +       err := checkBucketAndObjectNames(bucket, object)
> +       if errorCause(err) != nil && hasSuffix(object, slashSeparator) {
> +               return traceError(ObjectNotFound{Bucket: bucket, Object: object})
> +       }
> +       return err
>  }

This doesn't solve any purpose @krishnasrinivas - checkPutObjectArgs() doesn't use checkBucketAndObjectNames()

**Comment by krishnasrinivas** [comment]
> This doesn't solve any purpose @krishnasrinivas - checkPutObjectArgs() doesn't use checkBucketAndObjectNames()

I see, I assumed `checkBucketAndObjectNames()` is a common function to all checks.

**Review by krishnasrinivas — APPROVED** [review]

**Review by vadmeste — APPROVED** [review]
