### PR TITLE
gcs: Save partNumber as part of backend format.

### LINKED ISSUE #4637: [GCS] ListObjectParts should return parts info for remembered upload IDs
When upload IDs are remembered for objects, ListObjectParts needs to return parts information for client to do further actions like complete multipart etc.

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Version used (`minio version`):
* Environment name and version (e.g. nginx 1.9.1):
* Server type and version:
* Operating System and version (`uname -a`):
* Link to your project:

### PR DESCRIPTION
**Pull request by harshavardhana**
## Description
Add partNumber to the GCS backend as future protection and also allowing users to reconstruct and compose object without using minio gateway. 

## Motivation and Context
Fixes #4637

## How Has This Been Tested?
Manually.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by harshavardhana** [comment]
This PR is also not blocked anymore @krishnasrinivas and @abperiasamy discussed this and we agreed to do the way its done in this PR.

**Comment by deekoder** [comment]
@krishnasrinivas  will merge this after review completes.

File: cmd/gateway-gcs.go [hunk 1]
```diff
@@ -951,8 +952,8 @@ func (l *gcsGateway) CompleteMultipartUpload(bucket string, key string, uploadID
 		composeParts := make([]*storage.ObjectHandle, composeCount)
 		for i := 0; i < composeCount; i++ {
 			// Create 'composed-object-N' using next 32 parts.
-			composeName := fmt.Sprintf("composed-object-%d", i)
-			composeParts[i] = l.client.Bucket(bucket).Object(gcsMultipartDataName(uploadID, composeName))
+			composeObjectName := fmt.Sprintf("%s/%s/composed-object-%05d", gcsMinioMultipartPathV1, uploadID, i)
```
Comment (krishnasrinivas) [inline cmd/gateway-gcs.go]: better keep this in `minio.sys.temp/tmp/uploadID/composed-object-%05d`? That way backend will be cleaner.
In case we need to implement ListObjectParts in future it will also be easy as we need not have to filter out composed objects.

**Review by krishnasrinivas — APPROVED** [review]

File: cmd/gateway-gcs.go [hunk 2]
```diff
@@ -80,8 +80,13 @@ func gcsMultipartMetaName(uploadID string) string {
...
 
 // Returns name of the part object.
-func gcsMultipartDataName(uploadID, etag string) string {
-	return fmt.Sprintf("%s/%s/%s", gcsMinioMultipartPathV1, uploadID, etag)
+func gcsMultipartDataName(uploadID string, partNumber int, etag string) string {
+	return fmt.Sprintf("%s/%s/%05d.%s", gcsMinioMultipartPathV1, uploadID, partNumber, etag)
+}
+
+// Returns name of the composed object.
+func gcsMultipartComposeName(uploadID string, composeNumber int) string {
```
Comment (balamurugana) [inline cmd/gateway-gcs.go]: As this function is used only in `CompleteMultipartUpload()`, is it good idea to make it as closure?

File: cmd/gateway-gcs.go [hunk 3]
```diff
@@ -80,8 +80,13 @@ func gcsMultipartMetaName(uploadID string) string {
...
+	return fmt.Sprintf("tmp/%s/%s/composed-object-%05d", gcsMinioMultipartPathV1, uploadID, composeNumber)
```
Comment (balamurugana) [inline cmd/gateway-gcs.go]: IMO we shouldn't occupy one more name `tmp` instead we could use `minio.sys.temp` prefixed to this name.

**Review by balamurugana — CHANGES_REQUESTED** [review]

File: cmd/gateway-gcs.go (hunk 3 above)
Comment (krishnasrinivas) [reply cmd/gateway-gcs.go]: @balamurugana it is like:
for FS   : .minio.sys/tmp/...
for GFS: minio.sys.temp/tmp/...

for GCS we are using minio.sys.temp instead of .minio.sys

Comment (harshavardhana) [reply cmd/gateway-gcs.go]: Oh i thought it was done that .. my intention was to keep in .minio.sys.temp will send a updated PR.

File: cmd/gateway-gcs.go (hunk 2 above)
Comment (harshavardhana) [reply cmd/gateway-gcs.go]: Makes sense..

**Comment by harshavardhana** [comment]
@balamurugana @krishnasrinivas - please verify updated the PR with requested changes.

File: cmd/gateway-gcs.go [hunk 4]
```diff
@@ -942,7 +942,13 @@ func (l *gcsGateway) CompleteMultipartUpload(bucket string, key string, uploadID
...
 	var parts []*storage.ObjectHandle
 	for _, uploadedPart := range uploadedParts {
-		parts = append(parts, l.client.Bucket(bucket).Object(gcsMultipartDataName(uploadID, uploadedPart.ETag)))
+		parts = append(parts, l.client.Bucket(bucket).Object(gcsMultipartDataName(uploadID,
+			uploadedPart.PartNumber, uploadedPart.ETag)))
+	}
+
+	// Returns name of the composed object.
+	gcsMultipartComposeName := func(uploadID string, composeNumber int) string {
+		return fmt.Sprintf("%s/tmp/%s/composed-object-%05d", gcsMinioMultipartPathV1, uploadID, composeNumber)
```
Comment (balamurugana) [inline cmd/gateway-gcs.go]: I just wanted to confirm that `minio.sys.temp/multipart/v1/tmp/UPLOADID/` is directory than `minio.sys.temp/tmp/...`

Comment (harshavardhana) [reply cmd/gateway-gcs.go]: Yes the first one..

Comment (krishnasrinivas) [reply cmd/gateway-gcs.go]: @harshavardhana  just like in FS we have:
.minio.sys/multipart
.minio.sys/tmp

in GCS we can have:
minio.sys.temp/multipart
minio.sys.temp/tmp

Just like FS/XL, all staging files can be in `minio.sys.temp/tmp` This way contents of .minio.sys/multipart/v1/uploadID is clean and predictable. In future if we have to implement ListObjectParts() it will be simple as we don't have to filter out tmp.

Comment (harshavardhana) [reply cmd/gateway-gcs.go]: Ah okay let me do that..

**Review by balamurugana — APPROVED** [review]
