### PR TITLE
remove all dead codes

### LINKED ISSUE #5012: Remove unusued code from various files
## Expected Behavior
No unused code should be present in out source.

## Current Behavior
```
$ deadcode .
admin-handlers.go:49:2: mgmtKeyMarker is unused
admin-handlers.go:52:2: mgmtUploadIDMarker is unused
admin-handlers.go:53:2: mgmtMaxUploads is unused
format-config-v1.go:535:6: isFormatNotFound is unused
format-config-v1.go:547:6: isFormatFound is unused
notify-webhook.go:54:5: successStatus is unused
gateway-gcs.go:63:2: gcsMaxPartCount is unused
```

## Possible Solution
Remove or re-use these functions and variables.

## Steps to Reproduce (for bugs)
Install https://github.com/remyoudompheng/go-misc/tree/master/deadcode and then run `deadcode .` in  `cmd/` directory.

## Context
Cleanup.

## Your Environment
master

### PR DESCRIPTION
**Pull request by balamurugana**
Fixes #5012

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

File: buildscripts/deadcode.sh [hunk 1]
```diff
@@ -0,0 +1,12 @@
+#!/bin/bash
+
+rv=0
+for dir in cmd $(find pkg -type d); do
```
Comment (harshavardhana) [inline buildscripts/deadcode.sh]: You can use 

```
for i in $(go list ./... | grep -v vendor); do deadcode -test $i; done
```

Comment (balamurugana) [reply buildscripts/deadcode.sh]: done

File: Makefile [hunk 2]
```diff
@@ -46,7 +46,7 @@ cyclo:
 	@${GOPATH}/bin/gocyclo -over 100 pkg
 
 deadcode:
-	@${GOPATH}/bin/deadcode
+	@deadcode $(go list ./...)
```
Comment (harshavardhana) [inline Makefile]: We should avoid vendor directory here.. this might give false positives for vendor-ed libraries which we cannot fix.  
```
@deadcode $(go list ./... | grep -v vendor |grep -v browser)
```

**Review by harshavardhana — CHANGES_REQUESTED** [review]

File: Makefile (hunk 2 above)
Comment (balamurugana) [reply Makefile]: `go list ./...` does not return `vendor` directory.  `browser` does not fail.  Unable to understand your comment.

Comment (harshavardhana) [reply Makefile]: are you using go 1.9? @balamurugana 

```
$ go list ./...
github.com/minio/minio
github.com/minio/minio/browser
github.com/minio/minio/cmd
github.com/minio/minio/pkg/cgroup
github.com/minio/minio/pkg/disk
github.com/minio/minio/pkg/http
github.com/minio/minio/pkg/lock
github.com/minio/minio/pkg/madmin
github.com/minio/minio/pkg/madmin/examples
github.com/minio/minio/pkg/mimedb
github.com/minio/minio/pkg/mimedb/util
github.com/minio/minio/pkg/mountinfo
github.com/minio/minio/pkg/objcache
github.com/minio/minio/pkg/quick
github.com/minio/minio/pkg/safe
github.com/minio/minio/pkg/sys
github.com/minio/minio/pkg/trie
github.com/minio/minio/pkg/wildcard
github.com/minio/minio/pkg/words
github.com/minio/minio/pkg/x/os
github.com/minio/minio/vendor/cloud.google.com/go/compute/metadata
github.com/minio/minio/vendor/cloud.google.com/go/iam
github.com/minio/minio/vendor/cloud.google.com/go/internal
github.com/minio/minio/vendor/cloud.google.com/go/internal/optional
github.com/minio/minio/vendor/cloud.google.com/go/internal/version
github.com/minio/minio/vendor/cloud.google.com/go/storage
github.com/minio/minio/vendor/github.com/Azure/azure-sdk-for-go/storage
github.com/minio/minio/vendor/github.com/Azure/go-autorest/autorest
github.com/minio/minio/vendor/github.com/Azure/go-autorest/autorest/adal
github.com/minio/minio/vendor/github.com/Azure/go-autorest/autorest/azure
github.com/minio/minio/vendor/github.com/Azure/go-autorest/autorest/date
```

**Review by harshavardhana — APPROVED** [review]

**Review by krisis — APPROVED** [review]
