### PR TITLE
xl: bit-rot algo was not set in get-object.

### LINKED ISSUE #3650: bitrot: Fail to get an object when default bitrot algorithm is sha256
## Expected Behavior
When I change the default bitrot in the code to sha256 (think about arm64 which uses sha256 by default), I  should be able to get any object.

## Current Behavior
Not able to get an object with sha256 bitrot

## Possible Solution
void

## Steps to Reproduce (for bugs)
1. Change code in xl-v1-metadata.go and make getDefaultBitRotAlgo() returns sha256Algo
2. Start from fresh 4 disks, create a bucket, upload any object using mc.
3. Download that object using mc.

## Context
Manual testing to perform another task

## Your Environment
Last master ccd949d8ca068ddc406f58479132f2101c30493b

### PR DESCRIPTION
**Pull request by krishnasrinivas**
fixes #3650

## Description

bit rot algo was not set.

## Motivation and Context

https://github.com/minio/minio/issues/3650

## How Has This Been Tested?

make test
manual

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Review by vadmeste — APPROVED** [review]

File: cmd/xl-v1-object.go [hunk 1]
```diff
@@ -281,7 +281,7 @@ func (xl xlObjects) GetObject(bucket, object string, startOffset int64, length i
 			// Set checksum algo only once, while it is possible to have
```
Comment (harshavardhana) [inline cmd/xl-v1-object.go:281]: This comment needs to be removed, is it still valid?

**Review by harshavardhana — CHANGES_REQUESTED** [review]

**Review by harshavardhana — APPROVED** [review]

File: cmd/xl-v1-object.go (hunk 1 above)
Comment (krishnasrinivas) [reply cmd/xl-v1-object.go:281]: it's still valid, yes
