### PR TITLE
GCS gateway to return error in getBucketPolicy, when no policy is set

### LINKED ISSUE #199: minio-js fails on gcs gateway
Below is an error
```
Running minio-js tests ... FAILED in 4 seconds
{ 
  "name": "minio-js",
  "function": "makeBucket(bucketName, region, cb)",
  "duration": 507,
  "status": "FAIL",
  "error": "S3Error: The specified bucket is not valid. at Object.parseError (node_modules/minio/dist/main/xml-parsers.js:56:11) at node_modules/minio/dist/main/transformers.js:117:22 at DestroyableTransform._flush (node_modules/minio/dist/main/transformers.js:48:26) at DestroyableTransform.<anonymous> (node_modules/minio/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:135:12) at finishMaybe (node_modules/minio/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:371:12) at endWritable (node_modules/minio/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:378:3) at DestroyableTransform.Writable.end (node_modules/minio/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:356:5) at IncomingMessage.onend (_stream_readable.js:511:10) at endReadableNT (_stream_readable.js:974:12) at _combinedTickCallback (internal/process/next_tick.js:80:11) at process._tickCallback (internal/process/next_tick.js:104:9)"
}
```

### PR DESCRIPTION
**Pull request by kannappanr**
## Description
Return NoSuchBucketPolicy error when there is no policy set.
Fixes minio/mint#199

## How Has This Been Tested?
Ran functional tests for minio-js against Minio server and Azure S3, and GCS gateways.

## Types of changes

- [ x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Review by balamurugana — DISMISSED** [review]

File: cmd/gateway-gcs.go [hunk 1]
```diff
@@ -1060,20 +1060,24 @@ func (l *gcsGateway) GetBucketPolicies(bucket string) (policy.BucketAccessPolicy
...
+		isPolicySet = true
 		switch r.Role {
 		case storage.RoleReader:
 			policyInfo.Statements = policy.SetPolicy(policyInfo.Statements, policy.BucketPolicyReadOnly, bucket, "")
 		case storage.RoleWriter:
 			policyInfo.Statements = policy.SetPolicy(policyInfo.Statements, policy.BucketPolicyWriteOnly, bucket, "")
 		}
 	}
-
+	//Return NoSuchBucketPolicy error, when policy is not set
```
Comment (harshavardhana) [inline cmd/gateway-gcs.go]: We shouldn't do it like this @kannappanr we can simply do `len(policyInfo.Statements) == 0` and return PolicyNotFound{}

Comment (kannappanr) [reply cmd/gateway-gcs.go]: Done.

**Review by balamurugana — DISMISSED** [review]

**Review by krishnasrinivas — DISMISSED** [review]

File: cmd/gateway-gcs.go (hunk 1 above)
Comment (harshavardhana) [reply cmd/gateway-gcs.go]: Comment needs to have "// " space - this is Go styling.

**Review by krishnasrinivas — APPROVED** [review]

**Review by harshavardhana — APPROVED** [review]

**Review by balamurugana — APPROVED** [review]
