### PR TITLE
config: Check for duplicated entries in all scopes

### LINKED ISSUE #3812: Duplicated notify entries doesn't throw errors
By mistake, I created 2 `kafka` objects in the `notifiy` objects in `config.json` and I was confused why it was not working.

## Expected Behavior
An error should be thrown at the server startup if there are duplicated notification definition.

## Current Behavior
Not sure

### PR DESCRIPTION
**Pull request by vadmeste**
## Description
Validate Minio config by checking if there is double json key
in any scope level. The returned error contains the json path
to the duplicated key.

## Motivation and Context
Fixes #3812 

## How Has This Been Tested?
go test + Manually

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Review by krishnasrinivas — APPROVED** [review]

File: cmd/config-v14.go [hunk 1]
```diff
@@ -158,6 +160,60 @@ func loadConfig(envParams envParams) error {
...
+	return nil
+}
+
+// validateConfig checks for
+func validateConfig() error {
+	configFile := getConfigFile()
+	// Load config file
+	jsonBytes, err := ioutil.ReadFile(configFile)
+	if err != nil {
+		return err
```
Comment (harshavardhana) [inline cmd/config-v14.go]: As discussed we need to do in the following manner

 - checkVersion()
 - checkDuplicateKeys()
 - checkValidTypes()
 - checkEachNotificationTargets()

Each step also should have an error which guides the user on fixing the problem.

**Review by harshavardhana — CHANGES_REQUESTED** [review]

File: cmd/config-v14.go (hunk 1 above)
Comment (vadmeste) [reply cmd/config-v14.go]: Yes, I was going to do that in a separate PR, (for extensive validation issue)

Comment (harshavardhana) [reply cmd/config-v14.go]: Actually we need to do it in this one, because this PR is not complete without the other changes.

Comment (vadmeste) [reply cmd/config-v14.go]: Not sure what do you mean exactly by checkValidTypes(), by the way, json already checks for type validation, it cannot accept "version : 14" for example.

Otherwise, I added some empty validation functions, each field and sub fields will take care of their proper validation.

Comment (harshavardhana) [reply cmd/config-v14.go]: What i mean you load and parse it once.. So that allows for type validation.

**Comment by harshavardhana** [comment]
ping @balamurugana this is waiting on your review as well.

**Comment by vadmeste** [comment]
> ping @balamurugana this is waiting on your review as well.

@team Notification target are not extensively validated yet, please if someone implemented a notification target, can he tell me what parameters need to be validated? (for example, with postgreSQL it is obviously that database field shouldn't be empty)

**Comment by harshavardhana** [comment]
```
Running cyclo:
cmd/config-v14.go:169:8: "occurences" is a misspelling of "occurrences"
cmd/config-v14.go:169:8: "occurences" is a misspelling of "occurrences"
make: *** [spelling] Error 2
``` 

@vadmeste please run `mispell -w`

**Comment by vadmeste** [comment]
> @vadmeste please run mispell -w

Done

**Review by harshavardhana — APPROVED** [review]

**Comment by vadmeste** [comment]
@harshavardhana, tests are added
