### PR TITLE
simplify broker healthcheck by following kafka guidelines

### LINKED ISSUE #19081: "fatal error: concurrent map writes" after upgrade from RELEASE.2023-10-24T04-42-36Z to RELEASE.2024-02-06T21-36-22Z
## NOTE
Running the minio cluster in kubernetes cluster with operator version 5.0.11. After upgrading minio image from RELEASE.2023-10-24T04-42-36Z to RELEASE.2024-02-06T21-36-22Z, all minio pods crash with error "fatal error: concurrent map writes".

Cluster is containing 10 nodes with Ec:3 parity scheme for the nvme disk pools, around 700TB usable capacity. 

We tested some other smaller clusters with this binary upgrade, all works. 

## Expected Behavior
Upgrade went smoothly, without crashloop.

## Current Behavior
All Minio pods start running for a few mins while waiting for reconnecting other nodes, then it will crash and error our "fatal error: concurrent map writes"

## Possible Solution

N/A

## Steps to Reproduce (for bugs)

1.Install minio operator/tenant 5.0.11
2. overwrite minio image to RELEASE.2024-02-06T21-36-22Z in values.yaml file
3. helm upgrade the tenant

Not reproducible in the smaller minio cluster

## Context

Unable to upgrade cluster to newer version minio. 

## Regression

No

## Your Environment

* Version used (`minio --version`): MInio version RELEASE.2023-10-24T04-42-36Z prior the upgrade. Try to upgrade to RELEASE.2024-02-06T21-36-22Z. MInio operator version 5.0.10, minio Tenant version 5.0.11
* Server setup and configuration:  10 Dedicated node running kubernetes v1.24.10 containerd. Each host equiped 16x 7.3 TB NvMe drives mounted to file system with xfs. Minio tenant is configure use EC:3 storage class. 
* Operating System and version (`uname -a`): kernel 5.14.0-284.11.1.el9_2.x86_64, Rocky Linux 9.2 (Blue Onyx)

### PR DESCRIPTION
**Pull request by harshavardhana**
## Community Contribution License
All community contributions in this pull request are licensed to the project maintainers
under the terms of the [Apache 2 license](https://www.apache.org/licenses/LICENSE-2.0). 
By creating this pull request I represent that I have the right to license the 
contributions to the project maintainers under the Apache 2 license.

## Description
simplify broker healthcheck by following kafka guidelines

## Motivation and Context
fixes #19081

## How to test this PR?
Configure more than one broker.

## Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Optimization (provides speedup with no functional changes)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [x] Fixes a regression #18860
- [ ] Unit tests added/updated
- [ ] Internal documentation updated
- [ ] Create a documentation update request [here](https://github.com/minio/docs/issues/new?label=doc-change,title=Doc+Updated+Needed+For+PR+github.com%2fminio%2fminio%2fpull%2fNNNNN)

### CODE REVIEW

**Review by jiuker — APPROVED** [review]

**Review by shtripat — APPROVED** [review]

File: internal/logger/target/kafka/kafka.go [hunk 1]
```diff
@@ -411,11 +416,13 @@ func (h *Target) Cancel() {
 		h.producer.Close()
```
Comment (Praveenrajmani) [inline internal/logger/target/kafka/kafka.go:378]: likewise, can we close the producer after closing the broker connections?

**Review by Praveenrajmani — APPROVED** [review]
minor nit; LGTM otherwise.

**Comment by harshavardhana** [comment]
The entire thing is now re-implemented, we should have never implemented connection management on our end. 

The correct way is implemented now // cc @Praveenrajmani
