### PR TITLE
fix: bufconn and listener tests for megacheck

### LINKED ISSUE #4824: pkg/http: bufconn/listener_test.go has wrong go-routine and testing usage
## Expected Behavior
Avoid https://github.com/dominikh/go-tools/blob/master/cmd/staticcheck/docs/checks/SA2002

## Current Behavior
```
$ megacheck github.com/minio/minio/pkg/http
pkg/http/bufconn_test.go:43:2: the goroutine calls T.Fatalf, which must be called in the same goroutine as the test (SA2002)
pkg/http/bufconn_test.go:43:2: the goroutine calls T.Fatalf, which must be called in the same goroutine as the test (SA2002)
pkg/http/bufconn_test.go:43:2: the goroutine calls T.Fatalf, which must be called in the same goroutine as the test (SA2002)
pkg/http/bufconn_test.go:43:2: the goroutine calls T.Fatalf, which must be called in the same goroutine as the test (SA2002)
pkg/http/bufconn_test.go:43:2: the goroutine calls T.Fatalf, which must be called in the same goroutine as the test (SA2002)
pkg/http/bufconn_test.go:43:2: the goroutine calls T.Fatalf, which must be called in the same goroutine as the test (SA2002)
pkg/http/bufconn_test.go:44:3: should call wg.Add(1) before starting the goroutine to avoid a race (SA2000)
pkg/http/listener.go:209:3: redundant return statement (S1023)
pkg/http/listener_test.go:506:3: the goroutine calls T.Fatalf, which must be called in the same goroutine as the test (SA2002)
pkg/http/listener_test.go:506:3: the goroutine calls T.Fatalf, which must be called in the same goroutine as the test (SA2002)
pkg/http/listener_test.go:575:4: the goroutine calls T.Fatalf, which must be called in the same goroutine as the test (SA2002)
pkg/http/listener_test.go:575:4: the goroutine calls T.Fatalf, which must be called in the same goroutine as the test (SA2002)
pkg/http/listener_test.go:654:4: the goroutine calls T.Fatalf, which must be called in the same goroutine as the test (SA2002)
pkg/http/listener_test.go:654:4: the goroutine calls T.Fatalf, which must be called in the same goroutine as the test (SA2002)
```

## Possible Solution
Fixes are simple but should be fixed since they have bugs.

## Steps to Reproduce (for bugs)
```
$ go get honnef.co/go/tools/cmd/megacheck
$ megacheck github.com/minio/minio/pkg/http
```

## Context
Code review.

## Your Environment
Current master.

### PR DESCRIPTION
**Pull request by balamurugana**
Fixes #4824

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

File: pkg/http/listener_test.go [hunk 1]
```diff
@@ -37,6 +37,13 @@ import (
 
 var serverPort uint32 = 60000
 
+// As t.Fatalf() is not goroutine safe, use this closure.
```
Comment (krisis) [inline pkg/http/listener_test.go]: update comment since `fail` is no longer a function closure.

**Review by krisis — CHANGES_REQUESTED** [review]

**Review by harshavardhana — COMMENTED** [review]
LGTM. waiting for CI to give :+1:

**Review by krisis — APPROVED** [review]

**Review by harshavardhana — APPROVED** [review]
