### PR TITLE
reference format obtained doesn't need further validation

### LINKED ISSUE #8884: Sporadic simple CI failure
## Expected Behavior
No error during Simple CI test

## Current Behavior
```
4294 Step 23/43 : RUN make verify-healing
4295 ---> Running in 9096ea108bcc
4296 Error generating git commit-id:  exit status 128
4297 exit status 1
4298 Verify healing build with race
4299 Initializing environment
4300 Testing in Distributed Erasure setup healing test case 1
4301 Remove the contents of the disks belonging to '2' erasure set
4302 Testing in Distributed Erasure setup healing test case 2
4303 Remove the contents of the disks belonging to '1' erasure set
4304 /go/src/github.com/minio/minio/buildscripts/verify-healing.sh: line 126: kill: (546) - No such process
4305 cat: '/go/src/github.com/minio/minio/.verify-16680/*.log': No such file or directory
4306 make: *** [Makefile:81: verify-healing] Error 1
4307 The command '/bin/sh -c make verify-healing' returned a non-zero code: 2
4308 error running ci task for minio/minio:74c5e638e45734a46d47430dd904ce4bbcf5df41: exit status 2
```

## Steps to Reproduce (for bugs)
No steps to reproduce, the issue happens sometimes

## Context
Fix a rare error in Simple Test

## Regression
No

## Your Environment
All

### PR DESCRIPTION
**Pull request by harshavardhana**
## Description
reference format obtained doesn't need further validation

## Motivation and Context
we don't need to validateFormats again once we have obtained
reference format, because it is possible that at this stage
another server is doing a disk heal during startup, once
in a while due to delays we get false positives and our
server doesn't start.

Format in quorum as reference format can be assumed as valid
and we proceed further, until and unless HealFormat re-inits
the disks after a successful heal.

Also use separate port for healing tests to avoid any
conflicts with regular build testing.

Fixes #8884

## How to test this PR?
Hard to reproduce this issue, only possible on certain slower environments.

## Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [ ] Fixes a regression (If yes, please add `commit-id` or `PR #` here)
- [ ] Documentation needed
- [ ] Unit tests needed
- [ ] Functional tests needed (If yes, add [mint](https://github.com/minio/mint) PR # here: )

### CODE REVIEW

**Comment by minio-ops** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-worm.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-dist-xl.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-xl.sh | :x: [more...](#b7836d33-8cdc-46bb-b61e-0390d3d621e8) |
| mint-large-bucket.sh | :x: [more...](#44f0c83e-1b80-4228-82cf-996e582f4f30) |
| mint-gateway-azure.sh | :x: [more...](#c18653ff-9e84-407a-aa62-dd4fc36e149f) |
<a name="b7836d33-8cdc-46bb-b61e-0390d3d621e8"></a>
### 8964-492f7c7/mint-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.59:31565
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 2679cdfcaaf1:/mint/log /tmp/mint-logs'

(1/13) Running awscli tests ... FAILED in 13 seconds
{
  "name": "awscli",
  "duration": 11734,
  "function": "make_bucket\n",
  "status": "FAIL",
  "error": "An error occurred (XMinioServerNotInitialized) when calling the CreateBucket operation (reached max retries: 4): Server not initialized, please try again."
}

Executed 0 out of 13 tests successfully.
```
<a name="c18653ff-9e84-407a-aa62-dd4fc36e149f"></a>
### 8964-492f7c7/mint-gateway-azure.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.58:31771
ACCESS_KEY:           minioazure
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 70704a4a7cf4:/mint/log /tmp/mint-logs'

(1/13) Running awscli tests ... FAILED in 1 minutes and 25 seconds
{
  "name": "awscli",
  "duration": 1553,
  "function": "make_bucket\n",
  "status": "FAIL",
  "error": "An error occurred (BucketAlreadyOwnedByYou) when calling the CreateBucket operation: Your previous request to create the named bucket succeeded and you already own it."
}

Executed 0 out of 13 tests successfully.
```
<a name="44f0c83e-1b80-4228-82cf-996e582f4f30"></a>
### 8964-492f7c7/mint-large-bucket.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.52:31988
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 6fdb5ef332f5:/mint/log /tmp/mint-logs'

(1/13) Running awscli tests ... done in 2 minutes and 22 seconds
(2/13) Running aws-sdk-java tests ... done in 2 seconds
(3/13) Running aws-sdk-ruby tests ... done in 9 seconds
(4/13) Running mc tests ... done in 41 seconds
(5/13) Running minio-go tests ... FAILED in 14 minutes and 7 seconds
{
  "args": {},
  "duration": 78135,
  "error": "Please reduce your request",
  "function": "testStorageClassMetadataCopyObject()",
  "message": "CopyObject failed on RRS",
  "name": "minio-go: testStorageClassMetadataCopyObject",
  "status": "FAIL"
}

Executed 4 out of 13 tests successfully.
```
Deleting image on docker hub
Deleting image locally

**Comment by minio-ops** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-xl.sh | :heavy_check_mark: |
| mint-worm.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-dist-xl.sh | :heavy_check_mark: |
| mint-gateway-azure.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :x: [more...](#c5080d2b-36d8-4b52-8c67-97835bbe5f96) |
<a name="c5080d2b-36d8-4b52-8c67-97835bbe5f96"></a>
### 8964-fb1a30f/mint-large-bucket.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.52:32342
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 5b2ebd917df9:/mint/log /tmp/mint-logs'

(1/13) Running awscli tests ... done in 2 minutes and 24 seconds
(2/13) Running aws-sdk-java tests ... done in 1 seconds
(3/13) Running aws-sdk-ruby tests ... done in 7 seconds
(4/13) Running mc tests ... done in 51 seconds
(5/13) Running minio-go tests ... FAILED in 14 minutes and 7 seconds
{
  "args": {},
  "duration": 105133,
  "error": "Please reduce your request",
  "function": "testStorageClassMetadataCopyObject()",
  "message": "CopyObject failed on RRS",
  "name": "minio-go: testStorageClassMetadataCopyObject",
  "status": "FAIL"
}

Executed 4 out of 13 tests successfully.
```
Deleting image on docker hub
Deleting image locally

**Comment by harshavardhana** [comment]
PTAL @vadmeste @krishnasrinivas this PR needed to avoid spurious failures in SimpleCI.

**Comment by minio-ops** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-worm.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-dist-xl.sh | :heavy_check_mark: |
| mint-gateway-azure.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-xl.sh | :x: [more...](#dcfcea50-19be-4d5a-80dd-78efc7cf7820) |
| mint-large-bucket.sh | :x: [more...](#cc4e95b5-9640-4088-bce4-597feefc1ca3) |
<a name="cc4e95b5-9640-4088-bce4-597feefc1ca3"></a>
### 8964-c8bd180/mint-large-bucket.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.59:30877
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 47ba0729a7e8:/mint/log /tmp/mint-logs'

(1/13) Running awscli tests ... done in 2 minutes and 33 seconds
(2/13) Running aws-sdk-java tests ... done in 1 seconds
(3/13) Running aws-sdk-ruby tests ... done in 9 seconds
(4/13) Running mc tests ... done in 1 minutes and 2 seconds
(5/13) Running minio-go tests ... FAILED in 14 minutes and 56 seconds
{
  "args": {},
  "duration": 74231,
  "error": "Please reduce your request",
  "function": "testStorageClassMetadataCopyObject()",
  "message": "CopyObject failed on RRS",
  "name": "minio-go: testStorageClassMetadataCopyObject",
  "status": "FAIL"
}

Executed 4 out of 13 tests successfully.
```
<a name="dcfcea50-19be-4d5a-80dd-78efc7cf7820"></a>
### 8964-c8bd180/mint-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.53:32287
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 340af9750c0f:/mint/log /tmp/mint-logs'

(1/13) Running awscli tests ... FAILED in 12 seconds
{
  "name": "awscli",
  "duration": 10086,
  "function": "make_bucket\n",
  "status": "FAIL",
  "error": "An error occurred (XMinioServerNotInitialized) when calling the CreateBucket operation (reached max retries: 4): Server not initialized, please try again."
}

Executed 0 out of 13 tests successfully.
```
Deleting image on docker hub
Deleting image locally

File: cmd/prepare-storage.go [hunk 1]
```diff
@@ -302,17 +302,6 @@ func connectLoadInitFormats(retryCount int, firstDisk bool, endpoints Endpoints,
 		return nil, err
 	}
 
-	// Validate all format configs with reference format.
-	if err = validateXLFormats(format, formatConfigs, endpoints, setCount, drivesPerSet); err != nil {
-		return nil, err
-	}
-
-	// Get the deploymentID if set.
-	format.ID, err = formatXLGetDeploymentID(format, formatConfigs)
```
Comment (vadmeste) [inline cmd/prepare-storage.go:311]: Removing this will regenerate a new deployment ID in each cluster restart ?

**Review by vadmeste — COMMENTED** [review]
One comment

File: cmd/prepare-storage.go (hunk 1 above)
Comment (harshavardhana) [reply cmd/prepare-storage.go:311]: It's not needed @vadmeste format in quorum already has deployment ID

**Comment by harshavardhana** [comment]
Can this be looked at @krishnasrinivas @vadmeste ?

**Comment by minio-ops** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-worm.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-dist-xl.sh | :heavy_check_mark: |
| mint-gateway-azure.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-xl.sh | :x: [more...](#dcd55ea6-824c-4d35-ba3b-66d32cff6e4f) |
| mint-large-bucket.sh | :x: [more...](#439ea919-b3f3-4c40-a10b-4b8c0393a807) |
<a name="dcd55ea6-824c-4d35-ba3b-66d32cff6e4f"></a>
### 8964-7f539c8/mint-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.55:30515
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 4d917af9f0da:/mint/log /tmp/mint-logs'

(1/13) Running awscli tests ... FAILED in 5 minutes and 9 seconds
{"name": "awscli", "duration": 306618, "function": "make_bucket\n", "status": "FAIL", "error": "Connect timeout on endpoint URL: "http://72.28.97.55:30515/awscli-mint-test-bucket-23334""}

Executed 0 out of 13 tests successfully.
```
<a name="439ea919-b3f3-4c40-a10b-4b8c0393a807"></a>
### 8964-7f539c8/mint-large-bucket.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.53:30022
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 09c33f17405e:/mint/log /tmp/mint-logs'

(1/13) Running awscli tests ... done in 2 minutes and 26 seconds
(2/13) Running aws-sdk-java tests ... done in 2 seconds
(3/13) Running aws-sdk-ruby tests ... done in 5 seconds
(4/13) Running mc tests ... done in 40 seconds
(5/13) Running minio-go tests ... FAILED in 12 minutes and 55 seconds
{
  "args": {},
  "duration": 89780,
  "error": "Please reduce your request",
  "function": "testStorageClassMetadataCopyObject()",
  "message": "CopyObject failed on RRS",
  "name": "minio-go: testStorageClassMetadataCopyObject",
  "status": "FAIL"
}

Executed 4 out of 13 tests successfully.
```
Deleting image on docker hub
Deleting image locally

**Review by kannappanr — APPROVED** [review]
LGTM

**Comment by minio-ops** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-xl.sh | :heavy_check_mark: |
| mint-worm.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-dist-xl.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :x: [more...](#713531d2-ca61-43e1-a2a9-1d7ce0bbe739) |
| mint-gateway-azure.sh | :x: [more...](#4e90e9f6-9260-4a01-a5b7-363dbd0b4fb4) |
| mint-gateway-nas.sh | :x: [more...](#fe463f34-54e8-44a3-bd81-ef6ecd986265) |
<a name="713531d2-ca61-43e1-a2a9-1d7ce0bbe739"></a>
### 8964-4f95e75/mint-large-bucket.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.53:31684
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp aff0947eff98:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 3 seconds
(2/14) Running aws-sdk-java tests ... done in 1 seconds
(3/14) Running aws-sdk-php tests ... done in 48 seconds
(4/14) Running aws-sdk-ruby tests ... done in 5 seconds
(5/14) Running awscli tests ... done in 2 minutes and 22 seconds
(6/14) Running healthcheck tests ... done in 0 seconds
(7/14) Running mc tests ... done in 48 seconds
(8/14) Running minio-dotnet tests ... done in 41 seconds
(9/14) Running minio-go tests ... FAILED in 11 minutes and 38 seconds
{
  "args": {},
  "duration": 68325,
  "error": "Please reduce your request",
  "function": "testStorageClassMetadataCopyObject()",
  "message": "CopyObject failed on RRS",
  "name": "minio-go: testStorageClassMetadataCopyObject",
  "status": "FAIL"
}

Executed 8 out of 14 tests successfully.
```
<a name="4e90e9f6-9260-4a01-a5b7-363dbd0b4fb4"></a>
### 8964-4f95e75/mint-gateway-azure.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.58:30445
ACCESS_KEY:           minioazure
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 0420b2b1969e:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 9 seconds
(2/14) Running aws-sdk-java tests ... done in 1 seconds
(3/14) Running aws-sdk-php tests ... done in 3 minutes and 54 seconds
(4/14) Running aws-sdk-ruby tests ... done in 17 seconds
(5/14) Running awscli tests ... done in 3 minutes and 29 seconds
(6/14) Running healthcheck tests ... done in 1 seconds
(7/14) Running mc tests ... done in 6 minutes and 11 seconds
(8/14) Running minio-dotnet tests ... done in 1 minutes and 37 seconds
(9/14) Running minio-go tests ... done in 30 minutes and 29 seconds
(10/14) Running minio-java tests ... FAILED in 18 minutes and 22 seconds
{
  "name": "minio-java",
  "function": "composeObject(String bucketName, String objectName,List<ComposeSource> composeSources, Map <String,String > headerMap, ServerSideEncryption sseTarget)",
  "args": "size: 6 MB & 6 MB",
  "duration": 11324,
  "status": "FAIL",
  "error": "error occurred\nErrorResponse(code=NotImplemented, message=A header you provided implies functionality that is not implemented, bucketName=minio-java-test-1t397tg, objectName=minio-java-test-3e8kb91, resource=/minio-java-test-1t397tg/minio-java-test-3e8kb91, requestId=15F2EBDDFEC6BADC, hostId=ae5a4828-f342-4480-bf17-5be1da1d39b1)\nrequest={method=PUT, url=http://72.28.97.58:30445/minio-java-test-1t397tg/minio-java-test-3e8kb91?uploadId=7048d602a7d98c28&partNumber=1, headers=x-amz-copy-source-if-match: 7457fb21662f9890ef8ac1105402c4ee-2\nx-amz-copy-source: minio-java-test-1t397tg/minio-java-test-150vdc4\nAccept-Encoding: identity\nHost: 72.28.97.58:30445\nUser-Agent: MinIO (amd64; amd64) minio-java/dev\nx-amz-content-sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855\nx-amz-date: 20200213T092237Z\nAuthorization: AWS4-HMAC-SHA256 Credential=*REDACTED*/20200213/us-east-1/s3/aws4_request, SignedHeaders=accept-encoding;host;x-amz-content-sha256;x-amz-copy-source;x-amz-copy-source-if-match;x-amz-date, Signature=*REDACTED*\n}\nresponse={code=501, headers=Accept-Ranges: bytes\nContent-Length: 410\nContent-Security-Policy: block-all-mixed-content\nContent-Type: application/xml\nServer: MinIO/DEVELOPMENT.2020-02-13T07-58-56Z\nVary: Origin\nX-Amz-Request-Id: 15F2EBDDFEC6BADC\nX-Xss-Protection: 1; mode=block\nDate: Thu, 13 Feb 2020 09:22:38 GMT\n}\n >>> [io.minio.MinioClient.executeReq(MinioClient.java:1220), io.minio.MinioClient.execute(MinioClient.java:1082), io.minio.MinioClient.executePut(MinioClient.java:1446), io.minio.MinioClient.executePut(MinioClient.java:1468), io.minio.MinioClient.uploadPartCopy(MinioClient.java:2619), io.minio.MinioClient.composeObject(MinioClient.java:2572), FunctionalTest.composeObject_test1(FunctionalTest.java:2587), FunctionalTest.runTests(FunctionalTest.java:3396), FunctionalTest.main(FunctionalTest.java:3514)]"
}

Executed 9 out of 14 tests successfully.
```
<a name="fe463f34-54e8-44a3-bd81-ef6ecd986265"></a>
### 8964-4f95e75/mint-gateway-nas.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.55:32136
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp fe3d3db9bae4:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... FAILED in 2 minutes and 1 seconds
{
  "alert": "",
  "args": {
    "bucketName": "aws-sdk-go-test-i956e1zt9n5wbj",
    "expiry": 60000000000,
    "objectName": "presignedTest"
  },
  "duration": 120378,
  "error": "RequestError: send request failed\ncaused by: Put http://72.28.97.55:32136/aws-sdk-go-test-i956e1zt9n5wbj: dial tcp 72.28.97.55:32136: i/o timeout",
  "function": "PresignedPut",
  "message": "AWS SDK Go CreateBucket Failed",
  "name": "aws-sdk-go",
  "status": "FAIL"
}

Executed 0 out of 14 tests successfully.
```
Deleting image on docker hub
Deleting image locally

**Comment by vadmeste** [comment]
I did some testing here with 4 nodes, one disk for each node configuration.

After the removal of the validation code, the node which has an inconsistent format.json will start now and is able to receive S3 requests, but it won't write anything in its own disk because xlSets.connectDisks() and connectDisksWithQuorum() are also doing their own validation

**Review by vadmeste — APPROVED** [review]
LGTM

**Comment by kannappanr** [comment]
@y4m4, Please resolve the conflicts

**Comment by minio-ops** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-xl.sh | :x: [more...](#a9d05155-6ed7-4ff0-9371-3c537133a5fc) |
| mint-large-bucket.sh | :x: [more...](#71f68fda-a3e5-4f6c-a869-1ebc2e11e6bf) |
| mint-worm.sh | :x: [more...](#d836e132-2233-4a57-9482-b1aa1cc188f7) |
| mint-dist-xl.sh | :x: [more...](#0a0297f1-cb6a-4efc-b01e-5c41003b41c4) |
| mint-gateway-azure.sh | :x: [more...](#3d5cc8a9-53c6-4ff5-b897-5e765301bee0) |
<a name="71f68fda-a3e5-4f6c-a869-1ebc2e11e6bf"></a>
### 8964-0c1a863/mint-large-bucket.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.58:30471
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp fe7e6899e74a:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... FAILED in 6 minutes and 4 seconds
{
  "alert": "",
  "args": {
    "bucketName": "aws-sdk-go-test-x6xvbuwkb20dw6",
    "expiry": 60000000000,
    "objectName": "presignedTest"
  },
  "duration": 364227,
  "error": "XMinioServerNotInitialized: Server not initialized, please try again.\n\tstatus code: 503, request id: 15F30635EBED2538, host id: ",
  "function": "PresignedPut",
  "message": "AWS SDK Go CreateBucket Failed",
  "name": "aws-sdk-go",
  "status": "FAIL"
}

Executed 0 out of 14 tests successfully.
```
<a name="a9d05155-6ed7-4ff0-9371-3c537133a5fc"></a>
### 8964-0c1a863/mint-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.55:30730
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp f62c04746af6:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... FAILED in 2 minutes and 0 seconds
{
  "alert": "",
  "args": {
    "bucketName": "aws-sdk-go-test-yzfg6tceodshpk",
    "expiry": 60000000000,
    "objectName": "presignedTest"
  },
  "duration": 120261,
  "error": "RequestError: send request failed\ncaused by: Put http://72.28.97.55:30730/aws-sdk-go-test-yzfg6tceodshpk: dial tcp 72.28.97.55:30730: i/o timeout",
  "function": "PresignedPut",
  "message": "AWS SDK Go CreateBucket Failed",
  "name": "aws-sdk-go",
  "status": "FAIL"
}

Executed 0 out of 14 tests successfully.
```
<a name="0a0297f1-cb6a-4efc-b01e-5c41003b41c4"></a>
### 8964-0c1a863/mint-dist-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.58:32192
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 4bfc26d7b06f:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... FAILED in 0 seconds
{
  "alert": "",
  "args": {
    "bucketName": "aws-sdk-go-test-1ou21er2tr5dbq",
    "expiry": 60000000000,
    "objectName": "presignedTest"
  },
  "duration": 388,
  "error": "RequestError: send request failed\ncaused by: Put http://72.28.97.58:32192/aws-sdk-go-test-1ou21er2tr5dbq: dial tcp 72.28.97.58:32192: connect: connection refused",
  "function": "PresignedPut",
  "message": "AWS SDK Go CreateBucket Failed",
  "name": "aws-sdk-go",
  "status": "FAIL"
}

Executed 0 out of 14 tests successfully.
```
<a name="d836e132-2233-4a57-9482-b1aa1cc188f7"></a>
### 8964-0c1a863/mint-worm.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.55:31916
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            worm
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 7b32c14a62fc:/mint/log /tmp/mint-logs'

(1/1) Running worm tests ... FAILED in 2 minutes and 0 seconds
{
  "alert": "",
  "args": {
    "bucketName": "bucket-4rui0pt75fm5uqqik6a9w9qog79ik2ha7o91gh2i5l8xe2kjfpig0zt",
    "expiry": 60000000000,
    "objectName": "testObject"
  },
  "duration": 120316,
  "error": "RequestError: send request failed\ncaused by: Put http://72.28.97.55:31916/bucket-4rui0pt75fm5uqqik6a9w9qog79ik2ha7o91gh2i5l8xe2kjfpig0zt: dial tcp 72.28.97.55:31916: i/o timeout",
  "function": "PutAndDelete",
  "message": "WORM_MODE ON  - CreateBucket Failed",
  "name": "test worm mode",
  "status": "FAIL"
}

Executed 0 out of 1 tests successfully.
```
<a name="3d5cc8a9-53c6-4ff5-b897-5e765301bee0"></a>
### 8964-0c1a863/mint-gateway-azure.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.56:30164
ACCESS_KEY:           minioazure
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 8b0c97dbaa72:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 8 seconds
(2/14) Running aws-sdk-java tests ... done in 1 seconds
(3/14) Running aws-sdk-php tests ... done in 4 minutes and 1 seconds
(4/14) Running aws-sdk-ruby tests ... done in 17 seconds
(5/14) Running awscli tests ... done in 3 minutes and 4 seconds
(6/14) Running healthcheck tests ... done in 0 seconds
(7/14) Running mc tests ... done in 6 minutes and 42 seconds
(8/14) Running minio-dotnet tests ... done in 1 minutes and 42 seconds
(9/14) Running minio-go tests ... done in 31 minutes and 31 seconds
(10/14) Running minio-java tests ... FAILED in 18 minutes and 35 seconds
{
  "name": "minio-java",
  "function": "composeObject(String bucketName, String objectName,List<ComposeSource> composeSources, Map <String,String > headerMap, ServerSideEncryption sseTarget)",
  "args": "size: 6 MB & 6 MB",
  "duration": 11191,
  "status": "FAIL",
  "error": "error occurred\nErrorResponse(code=NotImplemented, message=A header you provided implies functionality that is not implemented, bucketName=minio-java-test-7ohkfk, objectName=minio-java-test-1p898mp, resource=/minio-java-test-7ohkfk/minio-java-test-1p898mp, requestId=15F3097B2517ECD5, hostId=609ee515-718b-44b6-9bb3-60c8bdad18bf)\nrequest={method=PUT, url=http://72.28.97.56:30164/minio-java-test-7ohkfk/minio-java-test-1p898mp?uploadId=2303d28a0fda6044&partNumber=1, headers=x-amz-copy-source-if-match: 1da667e4bc751007ccf1945839b9e172-2\nx-amz-copy-source: minio-java-test-7ohkfk/minio-java-test-39794h5\nAccept-Encoding: identity\nHost: 72.28.97.56:30164\nUser-Agent: MinIO (amd64; amd64) minio-java/dev\nx-amz-content-sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855\nx-amz-date: 20200213T182518Z\nAuthorization: AWS4-HMAC-SHA256 Credential=*REDACTED*/20200213/us-east-1/s3/aws4_request, SignedHeaders=accept-encoding;host;x-amz-content-sha256;x-amz-copy-source;x-amz-copy-source-if-match;x-amz-date, Signature=*REDACTED*\n}\nresponse={code=501, headers=Accept-Ranges: bytes\nContent-Length: 408\nContent-Security-Policy: block-all-mixed-content\nContent-Type: application/xml\nServer: MinIO/DEVELOPMENT.2020-02-13T17-00-09Z\nVary: Origin\nX-Amz-Request-Id: 15F3097B2517ECD5\nX-Xss-Protection: 1; mode=block\nDate: Thu, 13 Feb 2020 18:25:19 GMT\n}\n >>> [io.minio.MinioClient.executeReq(MinioClient.java:1220), io.minio.MinioClient.execute(MinioClient.java:1082), io.minio.MinioClient.executePut(MinioClient.java:1446), io.minio.MinioClient.executePut(MinioClient.java:1468), io.minio.MinioClient.uploadPartCopy(MinioClient.java:2619), io.minio.MinioClient.composeObject(MinioClient.java:2572), FunctionalTest.composeObject_test1(FunctionalTest.java:2587), FunctionalTest.runTests(FunctionalTest.java:3396), FunctionalTest.main(FunctionalTest.java:3514)]"
}

Executed 9 out of 14 tests successfully.
```
Deleting image on docker hub
Deleting image locally

**Comment by harshavardhana** [comment]
> I did some testing here with 4 nodes, one disk for each node configuration.
> 
> After the removal of the validation code, the node which has an inconsistent format.json will start now and is able to receive S3 requests, but it won't write anything in its own disk because xlSets.connectDisks() and connectDisksWithQuorum() are also doing their own validation

This is how it should be @vadmeste we should be able to take requests and not fail prematurely.

**Comment by minio-ops** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-xl.sh | :heavy_check_mark: |
| mint-worm.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-dist-xl.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :x: [more...](#6807ee18-952d-4210-90a4-e030615bc33b) |
| mint-gateway-azure.sh | :x: [more...](#0cfecc2b-0616-41bd-909b-3ed605d9252a) |
<a name="0cfecc2b-0616-41bd-909b-3ed605d9252a"></a>
### 8964-40e47dd/mint-gateway-azure.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.52:31860
ACCESS_KEY:           minioazure
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp c7da29f5bd0e:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 8 seconds
(2/14) Running aws-sdk-java tests ... done in 1 seconds
(3/14) Running aws-sdk-php tests ... done in 4 minutes and 5 seconds
(4/14) Running aws-sdk-ruby tests ... done in 18 seconds
(5/14) Running awscli tests ... done in 2 minutes and 57 seconds
(6/14) Running healthcheck tests ... done in 0 seconds
(7/14) Running mc tests ... done in 6 minutes and 21 seconds
(8/14) Running minio-dotnet tests ... done in 1 minutes and 33 seconds
(9/14) Running minio-go tests ... done in 31 minutes and 50 seconds
(10/14) Running minio-java tests ... FAILED in 18 minutes and 23 seconds
{
  "name": "minio-java",
  "function": "composeObject(String bucketName, String objectName,List<ComposeSource> composeSources, Map <String,String > headerMap, ServerSideEncryption sseTarget)",
  "args": "size: 6 MB & 6 MB",
  "duration": 11726,
  "status": "FAIL",
  "error": "error occurred\nErrorResponse(code=NotImplemented, message=A header you provided implies functionality that is not implemented, bucketName=minio-java-test-18u7gka, objectName=minio-java-test-1asjaqv, resource=/minio-java-test-18u7gka/minio-java-test-1asjaqv, requestId=15F315112CB34450, hostId=cb37535d-b2cf-4bdf-8077-52369b3d0fdf)\nrequest={method=PUT, url=http://72.28.97.52:31860/minio-java-test-18u7gka/minio-java-test-1asjaqv?uploadId=c001c2488b7a2531&partNumber=1, headers=x-amz-copy-source-if-match: 4edb5b242576bb5f57a8382d150ded37-2\nx-amz-copy-source: minio-java-test-18u7gka/minio-java-test-3qoo9e0\nAccept-Encoding: identity\nHost: 72.28.97.52:31860\nUser-Agent: MinIO (amd64; amd64) minio-java/dev\nx-amz-content-sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855\nx-amz-date: 20200213T215737Z\nAuthorization: AWS4-HMAC-SHA256 Credential=*REDACTED*/20200213/us-east-1/s3/aws4_request, SignedHeaders=accept-encoding;host;x-amz-content-sha256;x-amz-copy-source;x-amz-copy-source-if-match;x-amz-date, Signature=*REDACTED*\n}\nresponse={code=501, headers=Accept-Ranges: bytes\nContent-Length: 410\nContent-Security-Policy: block-all-mixed-content\nContent-Type: application/xml\nServer: MinIO/DEVELOPMENT.2020-02-13T20-32-47Z\nVary: Origin\nX-Amz-Request-Id: 15F315112CB34450\nX-Xss-Protection: 1; mode=block\nDate: Thu, 13 Feb 2020 21:57:38 GMT\n}\n >>> [io.minio.MinioClient.executeReq(MinioClient.java:1220), io.minio.MinioClient.execute(MinioClient.java:1082), io.minio.MinioClient.executePut(MinioClient.java:1446), io.minio.MinioClient.executePut(MinioClient.java:1468), io.minio.MinioClient.uploadPartCopy(MinioClient.java:2619), io.minio.MinioClient.composeObject(MinioClient.java:2572), FunctionalTest.composeObject_test1(FunctionalTest.java:2587), FunctionalTest.runTests(FunctionalTest.java:3396), FunctionalTest.main(FunctionalTest.java:3514)]"
}

Executed 9 out of 14 tests successfully.
```
<a name="6807ee18-952d-4210-90a4-e030615bc33b"></a>
### 8964-40e47dd/mint-large-bucket.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.51:30118
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 82ef2a016149:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 3 seconds
(2/14) Running aws-sdk-java tests ... done in 1 seconds
(3/14) Running aws-sdk-php tests ... done in 47 seconds
(4/14) Running aws-sdk-ruby tests ... done in 6 seconds
(5/14) Running awscli tests ... done in 2 minutes and 20 seconds
(6/14) Running healthcheck tests ... done in 0 seconds
(7/14) Running mc tests ... done in 50 seconds
(8/14) Running minio-dotnet tests ... done in 40 seconds
(9/14) Running minio-go tests ... FAILED in 14 minutes and 48 seconds
{
  "args": {},
  "duration": 102766,
  "error": "Please reduce your request",
  "function": "testStorageClassMetadataCopyObject()",
  "message": "CopyObject failed on RRS",
  "name": "minio-go: testStorageClassMetadataCopyObject",
  "status": "FAIL"
}

Executed 8 out of 14 tests successfully.
```
Deleting image on docker hub
Deleting image locally
