### PR TITLE
xl: CompleteMultipartUpload should rename files in a routine.

### LINKED ISSUE #1526: completemultipartupload timedout clients while renaming 9012 parts.
```
mc: <ERROR> Failed to copy ‘atul/data/freebase-rdf-latest’. Post http://127.0.0.1:9000/testbucket/freebase-rdf-latest.gz?uploadId=636
bc24b-223e-436d-bde7-bf5402377e43: net/http: request canceled (Client.Timeout exceeded while awaiting headers)
mc: <ERROR> Session safely terminated. To resume session ‘mc session resume nlAOdrTD’
minio@minio2:~$
```

Whereas the transaction did complete in the background. 

```
$ mc ls myminio/testbucket/freebase-rdf-latest.gz
[2016-05-07 16:44:39 PDT] 396GiB freebase-rdf-latest.gz
```

### PR DESCRIPTION
**Pull request by harshavardhana**
This solves the client timeout while renaming 9000+ parts.

Fixes #1526

### CODE REVIEW

File: object-utils.go [hunk 1]
```diff
@@ -109,18 +109,18 @@ func pathJoin(s1 string, s2 string) string {
 }
 
 // Create an s3 compatible MD5sum for complete multipart transaction.
-func makeS3MD5(md5Strs ...string) (string, error) {
+func makeS3MD5(parts ...completePart) (string, error) {
 	var finalMD5Bytes []byte
```
Comment (abperiasamy) [inline object-utils.go:113]: rename makeS3MD5 to CompleteMultipartMD5

File: xl-objects-multipart.go [hunk 2]
```diff
@@ -127,22 +141,44 @@ func (xl xlObjects) CompleteMultipartUpload(bucket string, object string, upload
...
+			if rErr != nil {
+				errs[index] = rErr
+				return
+			}
+			multipartObjSuffix := path.Join(object, partNumToPartFileName(part.PartNumber))
+			rErr = xl.storage.RenameFile(minioMetaBucket, tmpMultipartObjSuffix, bucket, multipartObjSuffix)
+			if rErr != nil {
+				if dErr := xl.storage.DeleteFile(minioMetaBucket, tmpMultipartObjSuffix); dErr != nil {
+					errs[index] = dErr
+					return
```
Comment (abperiasamy) [inline xl-objects-multipart.go:168]: we should log each error here. If we have multiple errors, we will still notice only the first error.
