### PR TITLE
fix: do not overwrite error on fallback.

### LINKED ISSUE #13397: `mc cp` cannot retrieve objects
Hi,

I'm doing backups with restic to a bare-metal machine running MinIO. Yesterday restic was unable to verify an older backup complaining about thousands of missing objects:

```
...
pack 3aa2ed21: does not exist
pack d20d64ec: does not exist
pack ac0aa250: does not exist
...
```

I tried to narrow this down in the past hours. No hardware errors were logged, S.M.A.R.T. data and underlying filesystems check out ok. The objects, which restic complains about, also show unexpected behaviour when I try to retrieve them with mc:

## Expected Behavior
I can retrieve an object with `mc cp`.

## Current Behavior
`mc cp` cannot retrieve the object, although `mc stat` says it exists. 
```
root@phoenix:~# mc stat phoenix/james-full/data/3a/3aa2ed217d8d44b2278eeb5d94912f04cf3a643d03aa3d202fb2e71bbf8d2846
Name      : 3aa2ed217d8d44b2278eeb5d94912f04cf3a643d03aa3d202fb2e71bbf8d2846
Date      : 2020-06-13 14:26:27 CEST 
Size      : 4.3 MiB 
ETag      : 2461bc12fe7d1e48e78a42197ca1e27c 
Type      : file 

root@phoenix:~# mc cp phoenix/james-full/data/3a/3aa2ed217d8d44b2278eeb5d94912f04cf3a643d03aa3d202fb2e71bbf8d2846 /tmp
mc: <ERROR> Failed to copy `http://127.0.0.1:9000/james-full/data/3a/3aa2ed217d8d44b2278eeb5d94912f04cf3a643d03aa3d202fb2e71bbf8d2846`. The specified key does not exist.
```

But I can still copy the same object to a temporary bucket and retrieve it from there:
(md5 sum matches the expected result from `mc stat` above)

```
root@phoenix:~# mc cp phoenix/james-full/data/3a/3aa2ed217d8d44b2278eeb5d94912f04cf3a643d03aa3d202fb2e71bbf8d2846 phoenix/temp/
...43d03aa3d202fb2e71bbf8d2846:  4.31 MiB / 4.31 MiB ┃▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓┃ 6.74 MiB/s 0s
root@phoenix:~# mc cp phoenix/temp/3aa2ed217d8d44b2278eeb5d94912f04cf3a643d03aa3d202fb2e71bbf8d2846 /tmp
...43d03aa3d202fb2e71bbf8d2846:  4.31 MiB / 4.31 MiB ┃▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓┃ 48.24 MiB/s 0s
root@phoenix:~# md5sum /tmp/3aa2ed217d8d44b2278eeb5d94912f04cf3a643d03aa3d202fb2e71bbf8d2846 
2461bc12fe7d1e48e78a42197ca1e27c  /tmp/3aa2ed217d8d44b2278eeb5d94912f04cf3a643d03aa3d202fb2e71bbf8d2846
```

## Possible Solution
I wonder whether this behaviour has something to do with a storage format change/migration which I missed. I noticed that newer objects use a different on-disk format. Looking through the changelogs, I could not find any matching breaking changes or caveats, though.

older objects:
```
root@phoenix:~# ls -l /minio_a/disk7/a/james-full/data/3a/3aa2ed217d8d44b2278eeb5d94912f04cf3a643d03aa3d202fb2e71bbf8d2846/
total 740
-rw-r--r-- 1 minio-user minio-user 752543 Jun 13  2020 part.1
-rw-r--r-- 1 minio-user minio-user    510 Jun 13  2020 xl.json
```

newer objects:
```
root@phoenix:~# ls -lR /minio_a/disk7/a/gitlab/data/9a/9a18710b0aaa8a0627ee6f21ac2bfa48752298218b0cd1cce571e86761c92bf2
/minio_a/disk7/a/gitlab/data/9a/9a18710b0aaa8a0627ee6f21ac2bfa48752298218b0cd1cce571e86761c92bf2:
total 8
drwxr-xr-x 2 minio-user minio-user 4096 Okt 10 09:37 4243e8fc-9f46-46c9-8e3c-48b9023ac86d
-rw-r--r-- 1 minio-user minio-user  332 Okt 10 09:37 xl.meta

/minio_a/disk7/a/gitlab/data/9a/9a18710b0aaa8a0627ee6f21ac2bfa48752298218b0cd1cce571e86761c92bf2/4243e8fc-9f46-46c9-8e3c-48b9023ac86d:
total 804
-rw-r--r-- 1 minio-user minio-user 823248 Okt 10 09:37 part.1
```

## My Environment
* minio upgraded yesterday to `RELEASE.2021-10-08T23-58-24Z`
* old version before yesterday was `RELEASE.2021-08-05T22-01-19Z`
* Debian 11 on bare metal, 9x2TB disks, ext4, default kernel, AMD Opteron 2378, 32GB ECC RAM.
* System is used for cold, last-resort backups, it stays completely disconnected and I only power it on about once a month for a few hours.

### PR DESCRIPTION
**Pull request by harshavardhana**
## Description
fix: do not overwrite errors on fallback.

## Motivation and Context
older content was returning '404' upon headObject()
due to swallowing of the error, make sure the
error in handling independently.

fixes #13397
## How to test this PR?
As per #13397 upgrade from an older release from say 

```
~ ./minio.RELEASE.2019-12-30T05-45-39Z server /tmp/xl{1...4}
```

## Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Optimization (provides speedup with no functional changes)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [ ] Fixes a regression (If yes, please add `commit-id` or `PR #` here)
- [ ] Documentation updated
- [x] Unit tests added/updated

### CODE REVIEW

File: internal/config/identity/tls/config.go [hunk 1]
```diff
@@ -85,18 +85,21 @@ func Lookup(kvs config.KVS) (Config, error) {
...
+	cfg.InsecureSkipVerify, err = config.ParseBool(env.Get(EnvIdentityTLSSkipVerify, kvs.Get(skipVerify)))
 	if err != nil {
 		return Config{}, err
 	}
-	return Config{
-		Enabled:            enabled,
-		InsecureSkipVerify: insecureSkipVerify,
-	}, nil
+	return cfg, nil
 }
```
Comment (harshavardhana) [inline internal/config/identity/tls/config.go]: This is just a change to avoid some random prints related to a config value.

**Review by kannappanr — APPROVED** [review]
LGTM

**Comment by minio-trusted** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-s3.sh | :heavy_check_mark: |
| mint-erasure.sh | :heavy_check_mark: |
| mint-dist-erasure.sh | :heavy_check_mark: |
| mint-zoned.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-compress-encrypt-dist-erasure.sh | :heavy_check_mark: |
Deleting image on docker hub
Deleting image locally

**Comment by minio-trusted** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-s3.sh | :heavy_check_mark: |
| mint-erasure.sh | :heavy_check_mark: |
| mint-dist-erasure.sh | :heavy_check_mark: |
| mint-zoned.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-compress-encrypt-dist-erasure.sh | :heavy_check_mark: |
Deleting image on docker hub
Deleting image locally

**Review by krisis — APPROVED** [review]

**Review by poornas — APPROVED** [review]
