### PR TITLE
browser: Implement infinite scrolling for object listing.

### LINKED ISSUE #2831: browser: Appears to timeout on bucket with large number of files (intermittent)
## Expected behaviour

It would be better if the client did not time out ... :(

For directories / buckets with LARGE numbers of files there is probably a more user friendly behavior (perhaps warning the user that it will take a long time to render, rendering the list a "page" at a time, allowing the user some control over the behavior, etc). 
## Actual behaviour

On a test minio system (small/laptop installation) - Minio client times out (intermittently) on a bucked that contains many image files... 

I _suspect_ the problem is the large number of files, but it could be something else... 
## Steps to reproduce the behaviour

I downloaded the "State Farm Distracted Driver" dataset from Kaggle... 
https://www.kaggle.com/c/state-farm-distracted-driver-detection/data

I started Minio server on my datasets directory... 

Scotts-MacBook-Pro-2:datasets scott$ pwd
/Users/scott/datasets
Scotts-MacBook-Pro-2:datasets scott$ ls -l
total 0
drwxr-xr-x  5 scott  staff  170 Sep 21 14:28 airlines
drwxr-xr-x  5 scott  staff  170 Sep 24 12:21 digit-reconition
drwxr-xr-x  7 scott  staff  238 Sep 21 12:50 redhat-kaggle
drwxr-xr-x  6 scott  staff  204 Oct  3 10:10 sf-distracted-driver
drwx------@ 7 scott  staff  238 Sep 21 14:29 thecounted-data
drwx------@ 6 scott  staff  204 Sep 21 14:28 thecounted-data-old

The "sf-distracted-driver" bucket contains sub-buckets (directories)

Scotts-MacBook-Pro-2:datasets scott$ find sf-distracted-driver -type d
sf-distracted-driver
sf-distracted-driver/imgs
sf-distracted-driver/imgs/test
sf-distracted-driver/imgs/train
sf-distracted-driver/imgs/train/c0
sf-distracted-driver/imgs/train/c1
sf-distracted-driver/imgs/train/c2
sf-distracted-driver/imgs/train/c3
sf-distracted-driver/imgs/train/c4
sf-distracted-driver/imgs/train/c5
sf-distracted-driver/imgs/train/c6
sf-distracted-driver/imgs/train/c7
sf-distracted-driver/imgs/train/c8
sf-distracted-driver/imgs/train/c9

The sf-distracted-driver/images/test directory contains 79727 files:

Scotts-MacBook-Pro-2:datasets scott$ ls -l sf-distracted-driver/imgs/test | wc -l
   79727

When you click on "test" under sf-distracted-driver, imgs in Minio Client you will get a 
"spinning wheel" for quite some time (30seconds +/-) then a message that Minio Client 
is non-responsive. 

NOTE: It does appear to be somewhat intermittent - on a subsequent attempt it did "complete" and listed all the "objects" (images) in the bucket. 
## Minio version
- (paste output of `minio version`)

Scotts-MacBook-Pro-2:Downloads scott$ ./minio version 

  New update: https://dl.minio.io/server/minio/release/darwin-amd64/minio?update=yes 

Version: 2016-08-21T02:44:47Z
Release-Tag: RELEASE.2016-08-21T02-44-47Z
Commit-ID: 975eb319730c8db093b4744bf9e012356d61eef2
## System information

MacBook Pro
OS X El Capitan v 10.11.5
Processor: 2.8 GHZ Intel Core i7
Mem 16GB

### PR DESCRIPTION
**Pull request by krishnasrinivas**
fixes #2831

## Description

Implement infinite scrolling for object listing. Need to figure out how to automatically load more objects on scroll. Right now we have a "more" button. @rushenn can you make this button look better? For this button to appear you need to have more than 100 objects in a bucket. In the backend you can do:
`for i in {1..200}; do touch $i; done` to create 200 files (1 to 200)

## Motivation and Context

https://github.com/minio/minio/issues/2831

## How Has This Been Tested?

manual

## Types of changes

- [] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by harshavardhana** [comment]
> Implement infinite scrolling for object listing. Need to figure out how to automatically load more objects on scroll. Right now we have a "more" button. @rushenn can you make this button look better? For this button to appear you need to have more than 100 objects in a bucket. In the backend you can do:
> for i in {1..200}; do touch $i; done to create 200 files (1 to 200)

We can enable based on "scrolling" event.

**Comment by krishnasrinivas** [comment]
> We can enable based on "scrolling" event.

yes, there are some react components for this, will be exploring it.

File: cmd/web-handlers.go [hunk 1]
```diff
@@ -225,30 +228,26 @@ func (web *webAPIHandlers) ListObjects(r *http.Request, args *ListObjectsArgs, r
...
-		}
-		for _, prefix := range lo.Prefixes {
-			reply.Objects = append(reply.Objects, WebObjectInfo{
-				Key: prefix,
-			})
-		}
-		if !lo.IsTruncated {
-			break
-		}
+	lo, err := objectAPI.ListObjects(args.BucketName, args.Prefix, args.Marker, "/", 100)
```
Comment (harshavardhana) [inline cmd/web-handlers.go]: why only 100, 1000 might be better since for the most part we don't have to do secondary queries.  Perhaps this can be controlled by the browser UI? basically browser can intelligently request on how much it wants?

File: browser/app/js/reducers.js [hunk 2]
```diff
@@ -75,8 +75,16 @@ export default (state = {
     case actions.SET_CURRENT_BUCKET:
       newState.currentBucket = action.currentBucket
       break
-    case actions.SET_OBJECTS:
-      newState.objects = action.objects
+  case actions.SET_OBJECTS:
+      if (!action.objects.length) {
+	newState.objects = []
```
Comment (harshavardhana) [inline browser/app/js/reducers.js]: This tabbing looks odd..

File: browser/app/js/actions.js [hunk 3]
```diff
@@ -299,7 +329,9 @@ export const selectPrefix = prefix => {
         dispatch(setObjects(
           utils.sortObjectsByName(objects.map(object => {
             object.name = object.name.replace(`${prefix}`, ''); return object
-          }))
+          })),
+	  res.nextmarker,
```
Comment (harshavardhana) [inline browser/app/js/actions.js]: Indentation issue here..

**Review by harshavardhana — CHANGES_REQUESTED** [review]

**Comment by krishnasrinivas** [comment]
> why only 100, 1000 might be better since for the most part we don't have to do secondary queries. Perhaps this can be controlled by the browser UI? basically browser can intelligently request on how much it wants?

Made it 1000. If it has to be configurable in the UI then that change can be made too. For now I have kept it simple.

File: cmd/web-handlers.go [hunk 4]
```diff
@@ -225,30 +228,26 @@ func (web *webAPIHandlers) ListObjects(r *http.Request, args *ListObjectsArgs, r
...
-		}
-		for _, prefix := range lo.Prefixes {
-			reply.Objects = append(reply.Objects, WebObjectInfo{
-				Key: prefix,
-			})
-		}
-		if !lo.IsTruncated {
-			break
-		}
+	lo, err := objectAPI.ListObjects(args.BucketName, args.Prefix, args.Marker, "/", 1000)
```
Comment (harshavardhana) [inline cmd/web-handlers.go]: we can use the common constants for this.. 

```
slashSeparator, maxObjectList)
```

**Review by harshavardhana — CHANGES_REQUESTED** [review]

**Comment by harshavardhana** [comment]
> Made it 1000. If it has to be configurable in the UI then that change can be made too. For now I have kept it simple.

:+1:

File: cmd/web-handlers.go (hunk 4 above)
Comment (harshavardhana) [reply cmd/web-handlers.go]: did you look at this @krishnasrinivas ?

Comment (krishnasrinivas) [reply cmd/web-handlers.go]: check now @harshavardhana

**Review by harshavardhana — APPROVED** [review]
