### PR TITLE
set storage class of object-info in FS mode

### LINKED ISSUE #5777: reply with correct storage class when running in FS
## Expected Behavior
Server should reply with the storage-class specified during the PUT when requesting an object.
For example: `STANDARD`

## Current Behavior
Server response with empty storage class when running in FS.

## Possible Solution
Still triaging... 

## Steps to Reproduce (for bugs)
1. Setup server in FS
2. Upload object with storage class `STANDARD`
3. Download object and check storage class
4. Storage class will be empty.

See: 
 - https://github.com/minio/minio-go/pull/963
 - https://github.com/aead/s3/pull/5

## Context
Testing, API
Follow-up bug of #5754

## Your Environment
master

### PR DESCRIPTION
**Pull request by aead**
## Description
This change sets the storage class of the object-info if a storage
class was specified during PUT. The server now replies with the
storage class which was set during uploading the object in FS mode.

## Motivation and Context

Fixes #5777

## How Has This Been Tested?
manually using test cases and mint

## Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added unit tests to cover my changes.
- [ ] I have added/updated functional tests in [mint](https://github.com/minio/mint). (If yes, add `mint` PR # here: )
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by balamurugana** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-xl.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-dist-xl.sh | :heavy_check_mark: |
| mint-gateway-s3.sh | :heavy_check_mark: |
| mint-gateway-azure.sh | :heavy_check_mark: |

**Review by harshavardhana — DISMISSED** [review]

**Review by nitisht — APPROVED** [review]

File: cmd/fs-v1-metadata.go [hunk 1]
```diff
@@ -169,6 +169,7 @@ func (m fsMetaV1) ToObjectInfo(bucket, object string, fi os.FileInfo) ObjectInfo
 	objInfo.ETag = extractETag(m.Meta)
 	objInfo.ContentType = m.Meta["content-type"]
 	objInfo.ContentEncoding = m.Meta["content-encoding"]
+	objInfo.StorageClass = m.Meta[amzStorageClass]
```
Comment (nitisht) [inline cmd/fs-v1-metadata.go]: `m.Meta[amzStorageClass]` will be empty if not set during the putObject etc, you can follow this style 
https://github.com/minio/minio/blob/master/cmd/xl-v1-metadata.go#L321

**Review by nitisht — CHANGES_REQUESTED** [review]
added a comment

File: cmd/fs-v1-metadata.go (hunk 1 above)
Comment (aead) [reply cmd/fs-v1-metadata.go]: Hm, but if a client does not specify a storage class during PUT - should we than add one (as default)? Is this S3 behavior?

Comment (nitisht) [reply cmd/fs-v1-metadata.go]: > Is this S3 behavior?

yes, S3 returns `STANDARD` for objects without anything specified.

Comment (aead) [reply cmd/fs-v1-metadata.go]: Okay - changed. PTAL

**Comment by balamurugana** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-xl.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-dist-xl.sh | :heavy_check_mark: |
| mint-gateway-s3.sh | :heavy_check_mark: |
| mint-gateway-azure.sh | :heavy_check_mark: |

**Review by nitisht — APPROVED** [review]
LGTM

**Review by harshavardhana — APPROVED** [review]
