### PR TITLE
azure gateway: return MD5Sum as ETag for S3 API compatibility

### LINKED ISSUE #6872: Azure gateway not caching multipart uploaded files
## Expected Behavior

When gateway edge cache is enabled, multipart uploaded files should also be cached.
## Current Behavior

FIles uploaded through multipart uploads are getting saved in cache but getting deleted at the time of complete multipart upload.
## Possible Solution

ETag generated in PutObjectPart for Azure gatewat is not md5sum but a generated ETag ( not hex encoded representation of md5sum). CompleteMultipart call fails during part verification because the part ETag cannot be hex decoded. Possible solution is to store per part ETag metadata during UploadPart that can be cleaned up on multipart upload completion. 
 
## Steps to Reproduce (for bugs)

1. export MINIO_CACHE_DRIVES=/tmp/cache 
2. ./minio gateway azure
3. Upload a large file > 65 mb via mc
4. 

## Context

Reported by a user on slack.
## Regression
 No

## Your Environment

* Version used (`minio version`):
* Environment name and version (e.g. nginx 1.9.1):
* Server type and version:
* Operating System and version (`uname -a`):
* Link to your project:

### PR DESCRIPTION
**Pull request by poornas**
Fixes #6872.

ETag generated in PutObjectPart is a UUID string rather than the MD5Sum of data being uploaded for Azure gateway. This poses a problem when edge caching mode is on, because part ETag validation is done at the time of CompleteMultipartUpload and it is expected that ETag be a hex encoded string.
## Description

Since the Azure BlockBlob api does not allow setting metadata, save a temporary part metadata file with the association between the uuid based ETag (used as part of the block id) and the md5sum which is known after data is written to backend. This temporary part metadata is cleaned up on completion of upload or aborting of upload. This allows PutObjectPart to be [S3 compatible](https://docs.aws.amazon.com/AmazonS3/latest/API/RESTCommonResponseHeaders.html) w.r.t etag
## Motivation and Context

allows objects uploaded to Azure via multipart API to be saved in edge cache when edge cache is enabled.
## Regression
 No

## How Has This Been Tested?

1. enable edge cache ```export MINIO_CACHE_DRIVES=/tmp/testcache```
2. start azure gateway ./minio gateway azure
3. mc cp /tmp/large myazure/testbucket/multipart
4.  You should see testbucket/multipart cached in /tmp/testcache folder
## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added unit tests to cover my changes.
- [ ] I have added/updated functional tests in [mint](https://github.com/minio/mint). (If yes, add `mint` PR # here: )
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by minio-ops** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-tls.sh | :heavy_check_mark: |
| mint-compression-xl.sh | :heavy_check_mark: |
| mint-xl.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-compression-fs.sh | :heavy_check_mark: |
| mint-worm.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-dist-xl.sh | :heavy_check_mark: |

**Review by harshavardhana — DISMISSED** [review]

**Comment by poornas** [comment]
@krishnasrinivas, PTAL

File: cmd/gateway/azure/gateway-azure.go [hunk 1]
```diff
@@ -1141,10 +1190,33 @@ func (a *azureObjects) CompleteMultipartUpload(ctx context.Context, bucket, obje
...
+		if err = json.NewDecoder(partMetadataReader).Decode(&partMetadata); err != nil {
+			logger.LogIf(ctx, err)
+			return objInfo, azureToObjectError(err, bucket, partMetadataObject)
+		}
+
+		if partMetadata.Metadata["x-amz-meta-md5sum"] != part.ETag {
+			return objInfo, minio.InvalidPart{}
+		}
+		defer func() {
+			derr := pblob.Delete(nil)
```
Comment (krishnasrinivas) [inline cmd/gateway/azure/gateway-azure.go]: should be deleted only in case of successful CompleteMultipartUpload()

File: cmd/gateway/azure/gateway-azure.go [hunk 2]
```diff
@@ -46,12 +46,14 @@ import (
...
-	azureBlockSize             = 100 * humanize.MiByte
-	azureS3MinPartSize         = 5 * humanize.MiByte
-	metadataObjectNameTemplate = minio.GatewayMinioSysTmp + "multipart/v1/%s.%x/azure.json"
-	azureBackend               = "azure"
-	azureMarkerPrefix          = "{minio}"
+	globalAzureAPIVersion          = "2016-05-31"
+	azureBlockSize                 = 100 * humanize.MiByte
+	azureS3MinPartSize             = 5 * humanize.MiByte
+	metadataObjectNameTemplate     = minio.GatewayMinioSysTmp + "multipart/v1/%s.%x/azure.json"
+	metadataObjectPartNameTemplate = minio.GatewayMinioSysTmp + "multipart/v1/%s.%x.%x/azure.json"
```
Comment (krishnasrinivas) [inline cmd/gateway/azure/gateway-azure.go]: We were encoding all the information into blockIDs itself so that we don't have to store an external metadata file like this. But now if we are having a part-meta file for each part then we don't have to encode anything in blockIDs and instead encode all the info in this meta file itself. This way blockIDs are just UUIDs and the part-meta file will look like this:

metadataObjectPartNameTemplate = minio.GatewayMinioSysTmp + "multipart/v1/%s.%x.%x/part-%d.json"
```
{
    etag: "d9cca721a735dac4efe709e0f3518373",
    blockIDs: ["4ef280b9-5752-49f8-ab6c-bc464c7dde0e", "0beb2b5a-633e-410a-a43e-6725bc366ef4", ....]
}
```

Also the following naming conventions will make it harder for future maintainers:
```
	metadata["x-amz-meta-etag"] = etag
	metadata["x-amz-meta-md5sum"] = md5Hex
```

i.e here x-amz-meta-etag is the unique string we use for azure and x-amz-meta-md5sum is the etag that is returned to s3-client. We can clean it up if we make the above change. Let's discuss with @abperiasamy

Comment (poornas) [reply cmd/gateway/azure/gateway-azure.go]: @krishnasrinivas, refactored to use the per part metadata file as per discussion for multipart operation.

**Comment by minio-ops** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-tls.sh | :heavy_check_mark: |
| mint-compression-xl.sh | :heavy_check_mark: |
| mint-xl.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-compression-fs.sh | :heavy_check_mark: |
| mint-worm.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-dist-xl.sh | :heavy_check_mark: |

**Comment by minio-ops** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-tls.sh | :heavy_check_mark: |
| mint-xl.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-compression-fs.sh | :heavy_check_mark: |
| mint-worm.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-dist-xl.sh | :heavy_check_mark: |
| mint-compression-xl.sh | :x: [more...](#c75ca2f0-0997-4500-8935-833db2ab4f8f) |
<a name="c75ca2f0-0997-4500-8935-833db2ab4f8f"></a>
### 6884-7312549/mint-compression-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      minikube:32229
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp a08f705e33ee:/mint/log /tmp/mint-logs'

(1/13) Running awscli tests ... done in 3 minutes and 18 seconds
(2/13) Running aws-sdk-go tests ... done in 1 seconds
(3/13) Running aws-sdk-java tests ... done in 6 seconds
(4/13) Running aws-sdk-php tests ... done in 43 seconds
(5/13) Running aws-sdk-ruby tests ... done in 2 seconds
(6/13) Running mc tests ... done in 27 seconds
(7/13) Running minio-dotnet tests ... FAILED in 2 minutes and 42 seconds

Unhandled Exception: System.AggregateException: One or more errors occurred. (Assert.Fail failed. ) ---> Microsoft.VisualStudio.TestTools.UnitTesting.AssertFailedException: Assert.Fail failed. 
   at Microsoft.VisualStudio.TestTools.UnitTesting.Assert.HandleFail(String assertionName, String message, Object[] parameters)
   at Minio.Functional.Tests.FunctionalTest.<>c.<ListIncompleteUpload_Test2>b__85_1(Exception ex) in /mint/run/core/minio-dotnet/FunctionalTest.cs:line 2138
   at System.Reactive.AutoDetachObserver`1.OnErrorCore(Exception exception) in D:\a\1\s\Rx.NET\Source\src\System.Reactive\Internal\AutoDetachObserver.cs:line 76
   at System.Reactive.AnonymousSafeObserver`1.OnError(Exception error) in D:\a\1\s\Rx.NET\Source\src\System.Reactive\AnonymousSafeObserver.cs:line 62
   at System.Reactive.Linq.ObservableImpl.Throw`1._.Invoke() in D:\a\1\s\Rx.NET\Source\src\System.Reactive\Linq\Observable\Throw.cs:line 42
   at System.Reactive.Concurrency.Scheduler.Invoke(IScheduler scheduler, Action action) in D:\a\1\s\Rx.NET\Source\src\System.Reactive\Concurrency\Scheduler.Simple.cs:line 83
   at System.Reactive.Producer`2.SubscribeRaw(IObserver`1 observer, Boolean enableSafeguard) in D:\a\1\s\Rx.NET\Source\src\System.Reactive\Internal\Producer.cs:line 127
   at System.Reactive.Linq.QueryLanguage.<>c__DisplayClass330_0`1.<Create>b__0(IObserver`1 observer) in D:\a\1\s\Rx.NET\Source\src\System.Reactive\Linq\QueryLanguage.Creation.cs:line 46
   at System.Reactive.AnonymousObservable`1.SubscribeCore(IObserver`1 observer) in D:\a\1\s\Rx.NET\Source\src\System.Reactive\AnonymousObservable.cs:line 37
   at System.Reactive.ObservableBase`1.ScheduledSubscribe(IScheduler _, AutoDetachObserver`1 autoDetachObserver) in D:\a\1\s\Rx.NET\Source\src\System.Reactive\ObservableBase.cs:line 82
   at System.Reactive.Concurrency.CurrentThreadScheduler.Trampoline.Run(SchedulerQueue`1 queue) in D:\a\1\s\Rx.NET\Source\src\System.Reactive\Concurrency\CurrentThreadScheduler.cs:line 126
   at System.Reactive.Concurrency.CurrentThreadScheduler.Schedule[TState](TState state, TimeSpan dueTime, Func`3 action) in D:\a\1\s\Rx.NET\Source\src\System.Reactive\Concurrency\CurrentThreadScheduler.cs:line 94
   at System.Reactive.ObservableBase`1.Subscribe(IObserver`1 observer) in D:\a\1\s\Rx.NET\Source\src\System.Reactive\ObservableBase.cs:line 51
   at Minio.Functional.Tests.FunctionalTest.ListIncompleteUpload_Test2(MinioClient minio) in /mint/run/core/minio-dotnet/FunctionalTest.cs:line 2136
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.Wait()
   at Minio.Functional.Tests.FunctionalTest.Main(String[] args) in /mint/run/core/minio-dotnet/FunctionalTest.cs:line 241

Executed 6 out of 13 tests successfully.
```

**Comment by minio-ops** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-tls.sh | :heavy_check_mark: |
| mint-compression-xl.sh | :heavy_check_mark: |
| mint-xl.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-compression-fs.sh | :heavy_check_mark: |
| mint-worm.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-dist-xl.sh | :heavy_check_mark: |

**Comment by poornas** [comment]
@krishnasrinivas, your review comments were addressed - PTAL.

**Comment by minio-ops** [comment]
```
Error running mint automation
+ mkdir -p 6884-d63a9b3/gopath/src/github.com/minio
+ git clone --quiet https://github.com/minio/minio.git 6884-d63a9b3/gopath/src/github.com/minio/minio
++ cd 6884-d63a9b3/gopath/src/github.com/minio/minio
++ git remote add minio https://github.com/minio/minio.git
++ cd 6884-d63a9b3/gopath/src/github.com/minio/minio
++ git fetch --quiet minio pull/6884/head:pr6884
++ cd 6884-d63a9b3/gopath/src/github.com/minio/minio
++ git checkout --quiet pr6884
++ minikube ip
+ minikube_ip=192.168.39.88
++ mkdir -p certs
++ cd certs
++ ./cert -host 192.168.39.88
2019/01/07 08:50:36 wrote public.crt
2019/01/07 08:50:36 wrote private.key
+ GOPATH=/mnt/nvme0n1p1/mint-auto/mint-auto/6884-d63a9b3/gopath
+ make -C 6884-d63a9b3/gopath/src/github.com/minio/minio --quiet
# github.com/minio/minio/cmd/gateway/azure
cmd/gateway/azure/gateway-azure.go:1118:32: not enough arguments in call to a.ListObjectParts
	have (context.Context, string, string, string, int, number)
	want (context.Context, string, string, string, int, int, cmd.ObjectOptions)
cmd/gateway/azure/gateway-azure.go:1265:32: not enough arguments in call to a.ListObjectParts
	have (context.Context, string, string, string, int, number)
	want (context.Context, string, string, string, int, int, cmd.ObjectOptions)
make: *** [build] Error 2

```

**Comment by kannappanr** [comment]
@poornas Can you PTAL at the travis failures?

**Comment by poornas** [comment]
fixed @kannappanr

**Comment by krishnasrinivas** [comment]
@poornas checking

File: cmd/gateway/azure/gateway-azure.go [hunk 3]
```diff
@@ -261,6 +264,30 @@ func s3MetaToAzureProperties(ctx context.Context, s3Metadata map[string]string)
...
+
+// partMetadataV1 struct holds the part specific metadata for
+// multipart operations.
+type partMetadataV1 struct {
+	Version  string   `json:"version"`
+	UploadID string   `json:"uploadID"`
+	PartID   string   `json:"partID"`
+	Size     int64    `json:"Size"`
+	BlockIDs []string `json:"blockIDs"`
+	MD5Sum   string   `json:"md5sum"`
```
Comment (krishnasrinivas) [inline cmd/gateway/azure/gateway-azure.go]: can be renamed to ETag, since it is actually ETag and we using MD5sum as ETag

Comment (poornas) [reply cmd/gateway/azure/gateway-azure.go]: ok, renamed this to ETag

**Comment by minio-ops** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-tls.sh | :heavy_check_mark: |
| mint-compression-xl.sh | :heavy_check_mark: |
| mint-xl.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-compression-fs.sh | :heavy_check_mark: |
| mint-worm.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-dist-xl.sh | :heavy_check_mark: |

**Comment by krishnasrinivas** [comment]
Slightly held up, will check the PR in a couple of days.

**Review by harshavardhana — DISMISSED** [review]
LGTM tested

**Comment by harshavardhana** [comment]
ping @krishnasrinivas

**Comment by minio-ops** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-tls.sh | :heavy_check_mark: |
| mint-compression-xl.sh | :heavy_check_mark: |
| mint-xl.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-compression-fs.sh | :heavy_check_mark: |
| mint-worm.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-dist-xl.sh | :heavy_check_mark: |

**Comment by harshavardhana** [comment]
@poornas can you fix the build issues

```
# github.com/minio/minio/cmd/gateway/azure [github.com/minio/minio/cmd/gateway/azure.test]
cmd/gateway/azure/gateway-azure_test.go:204:14: undefined: azureGetBlockID
cmd/gateway/azure/gateway-azure_test.go:233:48: undefined: azureParseBlockID
```

**Comment by minio-ops** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-tls.sh | :heavy_check_mark: |
| mint-compression-xl.sh | :heavy_check_mark: |
| mint-xl.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-compression-fs.sh | :heavy_check_mark: |
| mint-worm.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-dist-xl.sh | :heavy_check_mark: |

**Review by harshavardhana — DISMISSED** [review]

**Comment by minio-ops** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-compression-xl.sh | :heavy_exclamation_mark: [more...](#b8030e46-e4fb-4b47-ad99-275539ba4ada) |
| mint-xl.sh | :heavy_exclamation_mark: [more...](#f5aeff51-766e-45b6-85e6-9e500a32e0c1) |
| mint-large-bucket.sh | :heavy_exclamation_mark: [more...](#9ec195fe-ee10-4aef-ad7c-65549f9245db) |
| mint-compression-dist-xl.sh | :heavy_exclamation_mark: [more...](#f7538d9e-50e9-4d9a-aeee-68ceefc0d6b9) |
| mint-compression-fs.sh | :heavy_exclamation_mark: [more...](#29e51459-ef03-4406-856f-e8f8ff992624) |
| mint-worm.sh | :heavy_exclamation_mark: [more...](#0ef0e36d-9335-43f1-9852-1e9b44696a4a) |
| mint-fs.sh | :heavy_exclamation_mark: [more...](#a85e48da-ef43-42e1-8d2b-821d3d2de02f) |
| mint-dist-xl.sh | :heavy_exclamation_mark: [more...](#33498411-c5d6-4939-a263-afa350fa93bb) |
| mint-gateway-nas.sh | :heavy_exclamation_mark: [more...](#92b501f9-8827-41ef-b26e-d7e79ea134b2) |
<a name="f7538d9e-50e9-4d9a-aeee-68ceefc0d6b9"></a>
### 6884-f67db21/mint-compression-dist-xl.sh.xtrace:
```
DISABLED TIME BEING
```
<a name="0ef0e36d-9335-43f1-9852-1e9b44696a4a"></a>
### 6884-f67db21/mint-worm.sh.xtrace:
```
DISABLED TIME BEING
```
<a name="f5aeff51-766e-45b6-85e6-9e500a32e0c1"></a>
### 6884-f67db21/mint-xl.sh.xtrace:
```
DISABLED TIME BEING
```
<a name="33498411-c5d6-4939-a263-afa350fa93bb"></a>
### 6884-f67db21/mint-dist-xl.sh.xtrace:
```
DISABLED TIME BEING
```
<a name="b8030e46-e4fb-4b47-ad99-275539ba4ada"></a>
### 6884-f67db21/mint-compression-xl.sh.xtrace:
```
DISABLED TIME BEING
```
<a name="92b501f9-8827-41ef-b26e-d7e79ea134b2"></a>
### 6884-f67db21/mint-gateway-nas.sh.xtrace:
```
DISABLED TIME BEING
```
<a name="a85e48da-ef43-42e1-8d2b-821d3d2de02f"></a>
### 6884-f67db21/mint-fs.sh.xtrace:
```
DISABLED TIME BEING
```
<a name="9ec195fe-ee10-4aef-ad7c-65549f9245db"></a>
### 6884-f67db21/mint-large-bucket.sh.xtrace:
```
DISABLED TIME BEING
```
<a name="29e51459-ef03-4406-856f-e8f8ff992624"></a>
### 6884-f67db21/mint-compression-fs.sh.xtrace:
```
DISABLED TIME BEING
```

**Comment by krishnasrinivas** [comment]
@poornas with new way of storing metadata files we no longer need to do GetBlockList and peek into the contents which will simplify the code.

You can grep for GetBlockList in the code and make related changes. For ex completemultipart can now be (tricky function getBlocks is no longer needed):
```
func (a *azureObjects) CompleteMultipartUpload(ctx context.Context, bucket, object, uploadID string, uploadedParts []minio.CompletePart, opts minio.ObjectOptions) (objInfo minio.ObjectInfo, err error) {
        metadataObject := getAzureMetadataObjectName(object, uploadID)
        if err = a.checkUploadIDExists(ctx, bucket, object, uploadID); err != nil {
                return objInfo, err
        }

        if err = checkAzureUploadID(ctx, uploadID); err != nil {
                return objInfo, err
        }

        var metadataReader io.Reader
        blob := a.client.GetContainerReference(bucket).GetBlobReference(metadataObject)
        if metadataReader, err = blob.Get(nil); err != nil {
                return objInfo, azureToObjectError(err, bucket, metadataObject)
        }

        var metadata azureMultipartMetadata
        if err = json.NewDecoder(metadataReader).Decode(&metadata); err != nil {
                logger.LogIf(ctx, err)
                return objInfo, azureToObjectError(err, bucket, metadataObject)
        }

        var allBlocks []storage.Block
        var lastPartSize int
        for i, part := range uploadedParts {
                var partMetadataReader io.Reader
                var partMetadata partMetadataV1
                partMetadataObject := getAzureMetadataPartName(object, uploadID, part.PartNumber)
                pblob := a.client.GetContainerReference(bucket).GetBlobReference(partMetadataObject)
                if partMetadataReader, err = pblob.Get(nil); err != nil {
                        return objInfo, azureToObjectError(err, bucket, partMetadataObject)
                }

                if err = json.NewDecoder(partMetadataReader).Decode(&partMetadata); err != nil {
                        logger.LogIf(ctx, err)
                        return objInfo, azureToObjectError(err, bucket, partMetadataObject)
                }

                if partMetadata.ETag != part.ETag {
                        return objInfo, minio.InvalidPart{}
                }
                for _, blockID := range partMetadata.BlockIDs {
                        allBlocks = append(allBlocks, storage.Block{blockID, storage.BlockStatusUncommitted})
                }
                if i < (en(uploadedParts)-1) && partMetadata.Size < azureS3MinPartSize {
                        return objInfo, minio.PartTooSmall{
                                PartNumber: uploadedParts[i].PartNumber,
                                PartSize:   size,
                                PartETag:   uploadedParts[i].ETag,
                        }
                }
        }

        objBlob := a.client.GetContainerReference(bucket).GetBlobReference(object)
        err = objBlob.PutBlockList(allBlocks, nil)
        if err != nil {
                return objInfo, azureToObjectError(err, bucket, object)
        }

        blob := a.client.GetContainerReference(bucket).GetBlobReference(metadataObject)
        derr := blob.Delete(nil)
        logger.GetReqInfo(ctx).AppendTags("uploadID", uploadID)
        logger.LogIf(ctx, derr)

        if len(metadata.Metadata) > 0 {
                objBlob.Metadata, objBlob.Properties, err = s3MetaToAzureProperties(ctx, metadata.Metadata)
                if err != nil {
                        return objInfo, azureToObjectError(err, bucket, object)
                }
                err = objBlob.SetProperties(nil)
                if err != nil {
                        return objInfo, azureToObjectError(err, bucket, object)
                }
                err = objBlob.SetMetadata(nil)
                if err != nil {
                        return objInfo, azureToObjectError(err, bucket, object)
                }
        }
        var partNumberMarker int
        for {
                lpi, err := a.ListObjectParts(ctx, bucket, object, uploadID, partNumberMarker, maxPartsCount, minio.ObjectOptions{})
                if err != nil {
                        break
                }
                for _, part := range lpi.Parts {
                        pblob := a.client.GetContainerReference(bucket).GetBlobReference(
                                getAzureMetadataPartName(object, uploadID, part.PartNumber))
                        pblob.Delete(nil)
                }
                partNumberMarker = lpi.NextPartNumberMarker
                if !lpi.IsTruncated {
                        break
                }
        }
        return a.GetObjectInfo(ctx, bucket, object, minio.ObjectOptions{})
}
```

**Comment by poornas** [comment]
> @poornas with new way of storing metadata files we no longer need to do GetBlockList and peek into the contents which will simplify the code.
> 
> You can grep for GetBlockList in the code and make related changes. For ex completemultipart can now be (tricky function getBlocks is no longer needed):

@krishnasrinivas, getBlocks() validates whether block id in the part metadata file is valid. Are you suggesting that we drop this validation altogether?

**Comment by krishnasrinivas** [comment]
> @krishnasrinivas, getBlocks() validates whether block id in the part metadata file is valid. Are you suggesting that we drop this validation altogether?

yes, because PutBlockList() will fail, if it is not valid.

This is similar to s3 clients uploading parts and in the end sending the etags for all the parts. So S3 server will send an error back if any of the etags are not found.

**Comment by poornas** [comment]
@krishnasrinivas && @harshavardhana , updated PR

**Comment by minio-ops** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-compression-xl.sh | :heavy_check_mark: |
| mint-xl.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-compression-dist-xl.sh | :heavy_check_mark: |
| mint-compression-fs.sh | :heavy_check_mark: |
| mint-worm.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-dist-xl.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :x: [more...](#29ed8b9e-57c0-4729-930f-3fbf29d4429b) |
<a name="29ed8b9e-57c0-4729-930f-3fbf29d4429b"></a>
### 6884-e6b4604/mint-gateway-nas.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.61:32661
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp bee1ba3bb542:/mint/log /tmp/mint-logs'

(1/13) Running aws-sdk-go tests ... done in 0 seconds
(2/13) Running aws-sdk-java tests ... done in 1 seconds
(3/13) Running aws-sdk-php tests ... done in 41 seconds
(4/13) Running aws-sdk-ruby tests ... FAILED in 1 seconds
{
  "name": "aws-sdk-ruby",
  "function": "presignedPut(bucket_name,file_name)",
  "args": {
    "bucket_name": "aws-sdk-ruby-bucket-e51b2893f217",
    "file_name": "datafile-1-MB"
  },
  "duration": 20.8,
  "error": "Connection reset by peer",
  "status": "FAIL"
}

Executed 3 out of 13 tests successfully.
```

**Comment by minio-ops** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-compression-xl.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-compression-dist-xl.sh | :heavy_check_mark: |
| mint-compression-fs.sh | :heavy_check_mark: |
| mint-worm.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-dist-xl.sh | :heavy_check_mark: |
| mint-xl.sh | :x: [more...](#4b47bf16-af12-4630-9305-2467405c99f3) |
| mint-gateway-nas.sh | :x: [more...](#b78a8f5e-6490-4f24-8eb2-020633420f78) |
<a name="b78a8f5e-6490-4f24-8eb2-020633420f78"></a>
### 6884-39dc546/mint-gateway-nas.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.52:31936
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 1403a26727a7:/mint/log /tmp/mint-logs'

(1/13) Running aws-sdk-go tests ... done in 0 seconds
(2/13) Running aws-sdk-java tests ... done in 1 seconds
(3/13) Running aws-sdk-php tests ... done in 41 seconds
(4/13) Running aws-sdk-ruby tests ... FAILED in 2 seconds
{
  "name": "aws-sdk-ruby",
  "function": "presignedPut(bucket_name,file_name)",
  "args": {
    "bucket_name": "aws-sdk-ruby-bucket-9de5c443bb7a",
    "file_name": "datafile-1-MB"
  },
  "duration": 23.54,
  "error": "Connection reset by peer",
  "status": "FAIL"
}

Executed 3 out of 13 tests successfully.
```
<a name="4b47bf16-af12-4630-9305-2467405c99f3"></a>
### 6884-39dc546/mint-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.54:31383
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 9acb61a3fe5a:/mint/log /tmp/mint-logs'

(1/13) Running aws-sdk-go tests ... done in 0 seconds
(2/13) Running aws-sdk-java tests ... done in 0 seconds
(3/13) Running aws-sdk-php tests ... done in 41 seconds
(4/13) Running aws-sdk-ruby tests ... done in 2 seconds
(5/13) Running awscli tests ... done in 45 seconds
(6/13) Running mc tests ... done in 14 seconds
(7/13) Running minio-dotnet tests ... done in 2 minutes and 38 seconds
(8/13) Running minio-go tests ... done in 17 seconds
(9/13) Running minio-java tests ... FAILED in 37 seconds
{
  "name": "minio-java",
  "function": "presignedGetObject(String bucketName, String objectName, Integer expires)",
  "duration": 79,
  "status": "FAIL",
  "error": "java.io.EOFException >>> [okio.RealBufferedSink.write(RealBufferedSink.java:107), io.minio.HttpRequestBody.writeTo(HttpRequestBody.java:74), okhttp3.internal.http.CallServerInterceptor.intercept(CallServerInterceptor.java:62), okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92), okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:45), okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92), okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67), okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:93), okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92), okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67), okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93), okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92), okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:120), okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92), okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67), okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:185), okhttp3.RealCall.execute(RealCall.java:69), io.minio.MinioClient.executeReq(MinioClient.java:1097), io.minio.MinioClient.execute(MinioClient.java:1056), io.minio.MinioClient.executePut(MinioClient.java:1399), io.minio.MinioClient.executePut(MinioClient.java:1421), io.minio.MinioClient.putObject(MinioClient.java:3986), io.minio.MinioClient.putObject(MinioClient.java:4029), io.minio.MinioClient.putObject(MinioClient.java:3570), FunctionalTest.presignedGetObject_test2(FunctionalTest.java:1806), FunctionalTest.runTests(FunctionalTest.java:3031), FunctionalTest.main(FunctionalTest.java:3154)]"
}

Executed 8 out of 13 tests successfully.
```

**Review by krishnasrinivas — APPROVED** [review]

**Comment by minio-ops** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-compression-xl.sh | :heavy_check_mark: |
| mint-xl.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-compression-dist-xl.sh | :heavy_check_mark: |
| mint-compression-fs.sh | :heavy_check_mark: |
| mint-worm.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-dist-xl.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :x: [more...](#d23617f3-3bbd-4b1c-9df0-d7a8b81419b1) |
<a name="d23617f3-3bbd-4b1c-9df0-d7a8b81419b1"></a>
### 6884-3c543d7/mint-gateway-nas.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.56:30603
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 997bc3c3f8cc:/mint/log /tmp/mint-logs'

(1/13) Running aws-sdk-go tests ... done in 0 seconds
(2/13) Running aws-sdk-java tests ... done in 0 seconds
(3/13) Running aws-sdk-php tests ... done in 42 seconds
(4/13) Running aws-sdk-ruby tests ... FAILED in 1 seconds
{
  "name": "aws-sdk-ruby",
  "function": "presignedPut(bucket_name,file_name)",
  "args": {
    "bucket_name": "aws-sdk-ruby-bucket-dccb9b3f8dc5",
    "file_name": "datafile-1-MB"
  },
  "duration": 23.65,
  "error": "Connection reset by peer",
  "status": "FAIL"
}

Executed 3 out of 13 tests successfully.
```

**Review by harshavardhana — APPROVED** [review]
