### PR TITLE
xl/CreateFile: handle errFileNameTooLong error properly

### LINKED ISSUE #1501: XL/fs: Internal Server Error for PutObject with a name longer than 255 bytes
First of all, thanks for sharing a great software!

I tested putting an object with a name longer than 255 bytes.
Then it took about 20 seconds to get the results and the error
was "500 Internal Server Error".

I believe another error should be defined in [minio/api-errors.go](https://github.com/minio/minio/blob/master/api-errors.go) and the server returns it immediately.

My test environment:

```
$ go version
go version go1.6.2 linux/amd64
$ cd $GOPATH/src/github.com/minio/minio && git rev-parse HEAD
e4d89d8156927b2c60f5e719a78f0750a270f540
```

I tested with the following code.

```
package main

import (
    "bytes"
    "encoding/json"
    "io/ioutil"
    "os"
    "os/exec"
    "path/filepath"
    "strings"
    "testing"
    "time"

    "github.com/minio/minio-go"
)

func startMinio(addr, configDir, storageDir string) (*exec.Cmd, error) {
    err := os.MkdirAll(configDir, 0700)
    if err != nil {
        return nil, err
    }
    err = os.MkdirAll(storageDir, 0700)
    if err != nil {
        return nil, err
    }
    cmd := exec.Command("minio", "--config-dir", configDir, "server", "--address", addr, storageDir)
    err = cmd.Start()

    // NOTE: We need to wait some time for clients to work properly.
    // If clients connect to the server too soon, I got the
    // "The access key ID you provided does not exist in our records." error
    // when I call APIs like ListBuckets or MakeBucket
    time.Sleep(time.Second)

    return cmd, err
}

func stopMinio(cmd *exec.Cmd) error {
    return cmd.Process.Kill()
}

type Config struct {
    Credential Credential `json:"credential"`
    Region     string     `json:"region"`
}

type Credential struct {
    AccessKey string `json:"accessKey"`
    SecretKey string `json:"secretKey"`
}

func readConfig(configDir string) (config Config, err error) {
    configPath := filepath.Join(configDir, "config.json")
    file, err := os.Open(configPath)
    if err != nil {
        return
    }
    defer file.Close()

    decoder := json.NewDecoder(file)
    err = decoder.Decode(&config)
    return
}

func startMinioForTest(t *testing.T, addr string) (cmd *exec.Cmd, baseDir string, config Config, err error) {
    baseDir, err = ioutil.TempDir("", "minio-test")
    if err != nil {
        return
    }
    t.Logf("startMinioForTest created baseDir=%s", baseDir)

    configDir := filepath.Join(baseDir, "config")
    storageDir := filepath.Join(baseDir, "storage")
    cmd, err = startMinio(addr, configDir, storageDir)
    if err != nil {
        return
    }
    t.Logf("startMinioForTest started minio server. pid=%d, listenAddr=%s", cmd.Process.Pid, addr)
    config, err = readConfig(configDir)
    return
}

func stopMinioForTest(t *testing.T, addr string, cmd *exec.Cmd, baseDir string) {
    err := stopMinio(cmd)
    if err != nil {
        t.Errorf("failed to stop minio server with pid=%d, listenAddress=%s", cmd.Process.Pid, addr)
    }
    t.Logf("stopMinioForTest stopped minio server with pid=%d, listenAddress=%s", cmd.Process.Pid, addr)
    err = os.RemoveAll(baseDir)
    if err != nil {
        t.Errorf("failed to remove directory %s: err=%s", baseDir, err)
    }
    t.Logf("stopMinioForTest removed baseDir=%s", baseDir)
}

func newClient(addr string, config Config) (*minio.Client, error) {
    return minio.New(addr, config.Credential.AccessKey, config.Credential.SecretKey, true)
}

const listenAddr = "127.0.0.1:19999"

func TestPutAndTextFileWithTooLongDirName(t *testing.T) {
    cmd, baseDir, config, err := startMinioForTest(t, listenAddr)
    if err != nil {
        t.Fatal(err)
    }
    defer stopMinioForTest(t, listenAddr, cmd, baseDir)

    client, err := newClient(listenAddr, config)
    if err != nil {
        t.Error(err)
    }

    bucketName := "bucket1.example.com"
    err = client.MakeBucket(bucketName, config.Region)
    if err != nil {
        t.Error(err)
    }

    objectName := strings.Repeat("a", 256)
    contentType := "text/plain"
    var buf bytes.Buffer
    content := "hello world\ngoodbye world\n"
    buf.WriteString(content)
    _, err = client.PutObject(bucketName, objectName, &buf, contentType)
    if err == nil {
        t.Error("should have an error")
    }
    // NOTE: This error should not be "500 Internal Server Error"
    wantedError := "500 Internal Server Error"
    if err.Error() != wantedError {
        t.Errorf("unexpected error, got %s; want %s", err.Error(), wantedError)
    }
}
```

### PR DESCRIPTION
**Pull request by balamurugana**
When errFileNameTooLong error is returned from posix, xl.CreateFile()
treats the error specially by returning the same error immediately.

Fixes #1501

### CODE REVIEW

**Comment by harshavardhana** [comment]
can you add a test case for this? @balamurugana

File: posix.go [hunk 1]
```diff
@@ -439,7 +439,15 @@ func (s fsStorage) CreateFile(volume, path string) (writeCloser io.WriteCloser,
 	filePath := pathJoin(volumeDir, path)
 	// Verify if the file already exists and is not of regular type.
 	var st os.FileInfo
-	if st, err = os.Stat(filePath); err == nil {
+	if st, err = os.Stat(filePath); err != nil {
+		// File path segment is too long than supported length
+		if strings.Contains(err.Error(), "file name too long") {
+			return nil, errFileNameTooLong
+		} else if strings.Contains(err.Error(), "system cannot find the path specified") {
```
Comment (harshavardhana) [inline posix.go]: This error is because the file doesn't exist "system cannot find the path specified" is "os.IsNotExist(err)" . did you validate this directly on windows node?

Comment (balamurugana) [inline posix.go]: Yes. I got the error string from Windows XP box and Windows server 2012 R2.

**Comment by balamurugana** [comment]
Looks like AppVeyor failed with many other errors not related to this patch.  Is it possible to run it manually?

**Comment by harshavardhana** [comment]
> Looks like AppVeyor failed with many other errors not related to this patch. Is it possible to run it manually?

yes check your gitter, i gave you access to windows box.  The real problem is "system cannot find the specified file" means "no such file or directory" on windows it has nothing to do with keyName being 255 characters.

**Comment by balamurugana** [comment]
> The real problem is "system cannot find the specified file" means "no such file or directory" on windows it has nothing to do with keyName being 255 characters.

Run below code in Windows.  You will get the error message

``` go
package main

import (
    "fmt"
    "os"
)

func main() {
    s := fmt.Sprintf("%0256d", 1)
    _, err := os.Create(s)
    fmt.Println(err.Error())
}
```

**Comment by harshavardhana** [comment]
> package main
> 
> import (
>     "fmt"
>     "os"
> )
> 
> func main() {
>     s := fmt.Sprintf("%0256d", 1)
>     _, err := os.Create(s)
>     fmt.Println(err.Error())
> }

Better is to avoid syscalls here, since they are reporting messages which are not same for different operating systems. It is easier to just take the 'length' of 'volname+path'
