### PR TITLE
fix: support dropping privileges with arbitrary users

### LINKED ISSUE #18380: MINIO_USERNAME env var not working in latest release (groupadd command not found)
From version: `RELEASE.2023-11-01T18-37-25Z ` and `RELEASE.2023-11-01T01-57-10Z`

## Expected Behavior
User can be added with ENV VARS `MINIO_USERNAME`, `MINIO_GROUPNAME`

## Current Behavior
Attempt to add user with variables ends up with failure:
```
minio_1  | /usr/bin/docker-entrypoint.sh: line 18: groupadd: command not found
minio_1  | /usr/bin/docker-entrypoint.sh: line 21: exec: setpriv: not found
```

## Possible Solution
N/A

## Steps to Reproduce (for bugs)
run following docker-compose.yaml:
```
version: '3'
services:
  minio:
    ### last one working with groupadd / useradd working
    # image: quay.io/minio/minio:RELEASE.2023-10-25T06-33-25Z
    ### latest
    image: quay.io/minio/minio:RELEASE.2023-11-01T18-37-25Z
    volumes:
      - ./data:/data
    ports:
      - 9000:9000
      - 9001:9001
    environment:
      MINIO_ROOT_USER: 'minio_user'
      MINIO_ROOT_PASSWORD: 'minio_password'
      MINIO_ADDRESS: ':9000'
      MINIO_CONSOLE_ADDRESS: ':9001'
      MINIO_USERNAME: 'test-user'
      MINIO_GROUPNAME: 'test-user'
    command: minio server /data
```

## Context
- I'm using image which is adding the user and then running the server with it
## Regression
Yes
(last working version: `RELEASE.2023-10-25T06-33-25Z`)

## Your Environment
- see Steps to reproduce

### PR DESCRIPTION
**Pull request by harshavardhana**
## Community Contribution License
All community contributions in this pull request are licensed to the project maintainers
under the terms of the [Apache 2 license] (https://www.apache.org/licenses/LICENSE-2.0). 
By creating this pull request I represent that I have the right to license the 
contributions to the project maintainers under the Apache 2 license.

## Description
fix: support dropping privileges with arbitrary users

## Motivation and Context
fixes #18380

## How to test this PR?
You need to run this via `docker run -e MINIO_USERNAME=test-user -e MINIO_GROUPNAME=test-user` 

## Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Optimization (provides speedup with no functional changes)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [x] Fixes a regression yes since migrating to ubi-micro image
- [ ] Unit tests added/updated
- [ ] Internal documentation updated
- [ ] Create a documentation update request [here](https://github.com/minio/docs/issues/new?label=doc-change,title=Doc+Updated+Needed+For+PR+github.com%2fminio%2fminio%2fpull%2fNNNNN)

### CODE REVIEW

File: dockerscripts/docker-entrypoint.sh [hunk 1]
```diff
@@ -8,22 +8,19 @@ if [ "${1}" != "minio" ]; then
...
 		fi
-		exec setpriv --reuid="${MINIO_USERNAME}" \
-			--regid="${MINIO_GROUPNAME}" --keep-groups "$@"
 	else
 		exec "$@"
 	fi
 }
 
-## Switch to user if applicable.
+## DEPRECATED and unsupported - switch to user if applicable.
```
Comment (vadmeste) [inline dockerscripts/docker-entrypoint.sh:25]: This means we are going to remove this soon, right ?

Comment (harshavardhana) [reply dockerscripts/docker-entrypoint.sh:25]: well we need it for a while @vadmeste

**Review by vadmeste — APPROVED** [review]
LGTM
