### PR TITLE
fix : IAM Intialization failing with a large number of users/policies

### LINKED ISSUE #11305: Support high number of users in IAM
## Expected Behavior
MinIO installed in gateway mode, is provisioned **with >500 users + policies**.
After a restart of the MinIO server, the users and policies should be available for usage. (thanks to etcd backend)

## Current Behavior
After a restart of the MinIO server, the users and policies are not available.
- user could not login
- `mc admin user info [...]` could not respond

## Steps to Reproduce
https://gist.github.com/christophemorio/eb67efd9819e89f778617ef5c6c8d705

1. start an etcd server
2. start a MinIO server in s3 gateway mode
3. run this script to provision many users
4. restart MinIO
5. query any user or policy => it returns a timeout, or item not found, with error logs on MinIO server

### Console logs
```
2021-01-19T14:51:14.600580431Z 
2021-01-19T14:51:14.600615626Z  You are running an older version of MinIO released 1 week ago 
2021-01-19T14:51:14.600620578Z  Update: Run `mc admin update` 
2021-01-19T14:51:14.600624063Z 
2021-01-19T14:51:14.600627338Z 
2021-01-19T14:51:14.601016356Z Endpoint:  http://172.17.0.5:9000  http://127.0.0.1:9000
2021-01-19T14:51:14.601030536Z 
2021-01-19T14:51:14.601034637Z Browser Access:
2021-01-19T14:51:14.601038867Z    http://172.17.0.5:9000  http://127.0.0.1:9000
2021-01-19T14:51:14.601042281Z 
2021-01-19T14:51:14.601079931Z Object API (Amazon S3 compatible):
2021-01-19T14:51:14.601089242Z    Go:         https://docs.min.io/docs/golang-client-quickstart-guide
2021-01-19T14:51:14.601125754Z    Java:       https://docs.min.io/docs/java-client-quickstart-guide
2021-01-19T14:51:14.601375066Z    Python:     https://docs.min.io/docs/python-client-quickstart-guide
2021-01-19T14:51:14.601386686Z    JavaScript: https://docs.min.io/docs/javascript-client-quickstart-guide
2021-01-19T14:51:14.601391063Z    .NET:       https://docs.min.io/docs/dotnet-client-quickstart-guide
2021-01-19T14:51:43.830119487Z {"level":"warn","ts":"2021-01-19T14:51:43.829Z","caller":"clientv3/retry_interceptor.go:62","msg":"retrying of unary invoker failed","target":"endpoint://client-ebbd6fcb-7268-4953-a1c7-135919bb5ec3/etcd:2379","attempt":0,"error":"rpc error: code = DeadlineExceeded desc = context deadline exceeded"}
2021-01-19T14:51:43.83025429Z 
2021-01-19T14:51:43.830267145Z API: SYSTEM()
2021-01-19T14:51:43.830273081Z Time: 14:51:43 UTC 01/19/2021
2021-01-19T14:51:43.830290925Z DeploymentID: db2a4cf3-14bd-4e01-b26a-065aae081049
2021-01-19T14:51:43.830296712Z Error: Unable to initialize IAM sub-system, some users may not be available etcd is unreachable, please check your endpoints [http://etcd:2379] (*fmt.wrapError)
2021-01-19T14:51:43.830302529Z        1: cmd/iam.go:530:cmd.(*IAMSys).Init()
```

## Context
Server `RELEASE.2019-10-02T21-19-38Z` in gateway mode used to works fine with high number of users and policies (one per user).
The same users and policies fails to apply on `RELEASE.2021-01-05T05-22-38Z` after a restart of the server.

## Regression
This was not an issue for old server prior to ~RELEASE.2021-01-05T05-22-38Z~ RELEASE.2019-10-12T01-39-57Z.

## Your Environment
(test environment)
* Version used (`minio --version`):  `docker.io/minio/minio:RELEASE.2021-01-05T05-22-38Z`
* Server setup and configuration: minikube
* Operating System and version (`uname -a`): `Linux minikube 4.19.114 #1 SMP Mon Aug 3 12:35:22 PDT 2020 x86_64 GNU/Linux`
* one etcd v3.4.14 (cluster of a single member)
* one replicas of MinIO pod

### PR DESCRIPTION
**Pull request by sgandon**
## Description
when launching Minio, the initialization phase of IAM may fail with this error:
`Error: Unable to initialize IAM sub-system, some users may not be available etcd is unreachable`

This is mainly due to the fact that all user/policy/policy-mapping values are loaded atomically, meaning there is one etcd request for each single user/policy/policy-mapping and even for a big etcd server this may fail.  
This PR aims at fixing this issue by loading all the users (policies/mappings) values in one single request instead of too many.

## Motivation and Context
This mainly fixes #11305

## How to test this PR?
create a large number of users with an etcd setup (it regularrly fails with 2000 users but more is better for tests).

## Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Optimization (provides speedup with no functional changes)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [ ] Fixes a regression (If yes, please add `commit-id` or `PR #` here)
- [ ] Documentation updated
- [ ] Unit tests added/updated

### CODE REVIEW

**Comment by minio-trusted** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-s3.sh | :heavy_check_mark: |
| mint-erasure.sh | :heavy_check_mark: |
| mint-dist-erasure.sh | :heavy_check_mark: |
| mint-zoned.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-compress-encrypt-dist-erasure.sh | :x: [more...](#5ff54723-f848-494b-a02b-de75858deeca) |
<a name="5ff54723-f848-494b-a02b-de75858deeca"></a>
### 11701-2e4431a/mint-compress-encrypt-dist-erasure.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-dev8.minio.io:31757
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 582a57eb9234:/mint/log /tmp/mint-logs'

(1/15) Running aws-sdk-go tests ... done in 2 seconds
(2/15) Running aws-sdk-java tests ... done in 1 seconds
(3/15) Running aws-sdk-php tests ... done in 43 seconds
(4/15) Running aws-sdk-ruby tests ... done in 4 seconds
(5/15) Running awscli tests ... FAILED in 31 seconds
{
  "name": "awscli",
  "duration": 2615,
  "function": "aws --endpoint-url http://minio-dev8.minio.io:31757 s3api copy-object --bucket awscli-mint-test-bucket-13270 --key datafile-1-kB-copy --copy-source awscli-mint-test-bucket-13270/datafile-1-kB\n",
  "status": "FAIL",
  "error": "Hash mismatch expected 084e1383b70fb0c51acc680fef370023, got ac57de7156d7fc25ac1a65f81fa3989b"
}
(5/15) Running healthcheck tests ... done in 0 seconds
(6/15) Running mc tests ... done in 50 seconds
(7/15) Running minio-dotnet tests ... done in 54 seconds
(8/15) Running minio-go tests ... FAILED in 2 minutes and 38 seconds
{
  "args": {
    "destination": {
      "Bucket": "minio-go-test-a2qdupzyihxrwrsf",
      "Object": "dstObject",
      "Encryption": {},
      "UserMetadata": null,
      "ReplaceMetadata": false,
      "UserTags": null,
      "ReplaceTags": false,
      "LegalHold": "",
      "Mode": "",
      "RetainUntilDate": "0001-01-01T00:00:00Z",
      "Size": 0,
      "Progress": null
    },
    "source": {
      "Bucket": "minio-go-test-a2qdupzyihxrwrsf",
      "Object": "srcObject",
      "VersionID": "",
      "MatchETag": "",
      "NoMatchETag": "",
      "MatchModifiedSince": "0001-01-01T00:00:00Z",
      "MatchUnmodifiedSince": "0001-01-01T00:00:00Z",
      "MatchRange": false,
      "Start": 0,
      "End": 0,
      "Encryption": null
    }
  },
  "duration": 3339,
  "error": "We encountered an internal error, please try again.: cause(s2: corrupt input)",
  "function": "CopyObject(destination, source)",
  "message": "GetObject failed",
  "name": "minio-go: testUnencryptedToSSES3CopyObject",
  "status": "FAIL"
}
(8/15) Running minio-java tests ... FAILED in 1 minutes and 40 seconds
{
  "name": "minio-java",
  "function": "copyObject()",
  "args": "[match etag]",
  "duration": 188,
  "status": "FAIL",
  "error": "error occurred\nErrorResponse(code = PreconditionFailed, message = At least one of the pre-conditions you specified did not hold, bucketName = minio-java-test-17v1aii, objectName = minio-java-test-14kfgar-copy, resource = /minio-java-test-17v1aii/minio-java-test-14kfgar-copy, requestId = 16691EC4ECC9B9A3, hostId = e57c0601-a846-4d17-b50c-cb938ec6eda5)\nrequest={method=PUT, url=http://minio-dev8.minio.io:31757/minio-java-test-17v1aii/minio-java-test-14kfgar-copy, headers=x-amz-copy-source-if-match: 71cff0a060f852067e443ad1e24ae26c-1\nx-amz-copy-source: /minio-java-test-3rh3vc/minio-java-test-14kfgar\nHost: minio-dev8.minio.io:31757\nAccept-Encoding: identity\nUser-Agent: MinIO (Linux; amd64) minio-java/8.0.3\nContent-MD5: 1B2M2Y8AsgTpgAmY7PhCfg==\nx-amz-content-sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855\nx-amz-date: 20210304T110252Z\nAuthorization: AWS4-HMAC-SHA256 Credential=*REDACTED*/20210304/us-east-1/s3/aws4_request, SignedHeaders=content-md5;host;x-amz-content-sha256;x-amz-copy-source;x-amz-copy-source-if-match;x-amz-date, Signature=*REDACTED*\n}\nresponse={code=412, headers=Accept-Ranges: bytes\nContent-Length: 418\nContent-Security-Policy: block-all-mixed-content\nContent-Type: application/xml\nETag: \"71cff0a060f852067e443ad1e24ae26c\"\nLast-Modified: Thu, 04 Mar 2021 11:02:52 GMT\nServer: MinIO\nVary: Origin\nX-Amz-Request-Id: 16691EC4ECC9B9A3\nX-Xss-Protection: 1; mode=block\nDate: Thu, 04 Mar 2021 11:02:52 GMT\n}\n >>> [io.minio.MinioClient.execute(MinioClient.java:775), io.minio.MinioClient.execute(MinioClient.java:563), io.minio.MinioClient.executePut(MinioClient.java:904), io.minio.MinioClient.copyObject(MinioClient.java:1232), FunctionalTest.testCopyObjectMatchETag(FunctionalTest.java:1850), FunctionalTest.copyObject(FunctionalTest.java:2016), FunctionalTest.runObjectTests(FunctionalTest.java:3757), FunctionalTest.runTests(FunctionalTest.java:3783), FunctionalTest.main(FunctionalTest.java:3927)]"
}
(8/15) Running minio-js tests ... done in 49 seconds
(9/15) Running minio-py tests ... done in 3 minutes and 14 seconds
(10/15) Running s3cmd tests ... FAILED in 5 seconds
{
  "name": "s3cmd",
  "duration": "3010",
  "function": "test_put_object_multipart",
  "status": "FAIL",
  "error": "WARNING: MD5 Sums don't match!\nWARNING: Retrying upload of /mint/data/datafile-65-MB\nWARNING: MD5 Sums don't match!\nWARNING: Retrying upload of /mint/data/datafile-65-MB\nWARNING: MD5 Sums don't match!\nWARNING: Retrying upload of /mint/data/datafile-65-MB\nWARNING: MD5 Sums don't match!\nWARNING: Retrying upload of /mint/data/datafile-65-MB\nWARNING: MD5 Sums don't match!\nWARNING: Retrying upload of /mint/data/datafile-65-MB\nWARNING: MD5 Sums don't match!\nWARNING: Too many failures. Giving up on '/mint/data/datafile-65-MB'\nERROR: \nUpload of '/mint/data/datafile-65-MB' part 1 failed. Use\n  /usr/local/bin/s3cmd abortmp s3://s3cmd-test-bucket-13420/s3cmd-test-object-6328 51d63760-82e7-47cd-bf47-e072f9d20134\nto abort the upload, or\n  /usr/local/bin/s3cmd --upload-id 51d63760-82e7-47cd-bf47-e072f9d20134 put ...\nto continue the upload.\nERROR: Upload of '/mint/data/datafile-65-MB' failed too many times (Last reason: )"
}
(10/15) Running s3select tests ... done in 6 seconds
(11/15) Running security tests ... done in 0 seconds

Executed 11 out of 15 tests successfully.
```
Deleting image on docker hub
Deleting image locally

**Comment by minio-trusted** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-s3.sh | :heavy_check_mark: |
| mint-erasure.sh | :heavy_check_mark: |
| mint-dist-erasure.sh | :heavy_check_mark: |
| mint-zoned.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-compress-encrypt-dist-erasure.sh | :x: [more...](#08a3890a-e613-4dd0-99a8-0ffc2a131142) |
<a name="08a3890a-e613-4dd0-99a8-0ffc2a131142"></a>
### 11701-e407ef5/mint-compress-encrypt-dist-erasure.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-c2.minio.io:32583
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 58a26a8befae:/mint/log /tmp/mint-logs'

(1/15) Running aws-sdk-go tests ... done in 2 seconds
(2/15) Running aws-sdk-java tests ... done in 2 seconds
(3/15) Running aws-sdk-php tests ... done in 43 seconds
(4/15) Running aws-sdk-ruby tests ... done in 4 seconds
(5/15) Running awscli tests ... FAILED in 32 seconds
{
  "name": "awscli",
  "duration": 2784,
  "function": "aws --endpoint-url http://minio-c2.minio.io:32583 s3api copy-object --bucket awscli-mint-test-bucket-15934 --key datafile-1-kB-copy --copy-source awscli-mint-test-bucket-15934/datafile-1-kB\n",
  "status": "FAIL",
  "error": "Hash mismatch expected 084e1383b70fb0c51acc680fef370023, got ac57de7156d7fc25ac1a65f81fa3989b"
}
(5/15) Running healthcheck tests ... done in 0 seconds
(6/15) Running mc tests ... done in 48 seconds
(7/15) Running minio-dotnet tests ... done in 43 seconds
(8/15) Running minio-go tests ... FAILED in 1 minutes and 53 seconds
{
  "args": {
    "bucketName": "minio-go-test-51xdupcy1zh40ze6",
    "objectName": "k3lz5de9pjcow259nmrdvmzshyxbbt"
  },
  "duration": 9140,
  "error": "read tcp 172.17.0.7:40012->72.28.97.58:32583: read: connection reset by peer",
  "function": "GetObject(bucketName, objectName)",
  "message": "ReadAt failed",
  "name": "minio-go: testSSES3EncryptedGetObjectReadAtFunctional",
  "status": "FAIL"
}
(8/15) Running minio-java tests ... FAILED in 1 minutes and 57 seconds
{
  "name": "minio-java",
  "function": "copyObject()",
  "args": "[match etag]",
  "duration": 258,
  "status": "FAIL",
  "error": "error occurred\nErrorResponse(code = PreconditionFailed, message = At least one of the pre-conditions you specified did not hold, bucketName = minio-java-test-2af6bhr, objectName = minio-java-test-u3vcao-copy, resource = /minio-java-test-2af6bhr/minio-java-test-u3vcao-copy, requestId = 16691FDCD237C85A, hostId = d8b3644c-8ff6-4a97-bf70-e2e2dfc17d3a)\nrequest={method=PUT, url=http://minio-c2.minio.io:32583/minio-java-test-2af6bhr/minio-java-test-u3vcao-copy, headers=x-amz-copy-source-if-match: 71cff0a060f852067e443ad1e24ae26c-1\nx-amz-copy-source: /minio-java-test-iuqnid/minio-java-test-u3vcao\nHost: minio-c2.minio.io:32583\nAccept-Encoding: identity\nUser-Agent: MinIO (Linux; amd64) minio-java/8.0.3\nContent-MD5: 1B2M2Y8AsgTpgAmY7PhCfg==\nx-amz-content-sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855\nx-amz-date: 20210304T112254Z\nAuthorization: AWS4-HMAC-SHA256 Credential=*REDACTED*/20210304/us-east-1/s3/aws4_request, SignedHeaders=content-md5;host;x-amz-content-sha256;x-amz-copy-source;x-amz-copy-source-if-match;x-amz-date, Signature=*REDACTED*\n}\nresponse={code=412, headers=Accept-Ranges: bytes\nContent-Length: 416\nContent-Security-Policy: block-all-mixed-content\nContent-Type: application/xml\nETag: \"71cff0a060f852067e443ad1e24ae26c\"\nLast-Modified: Thu, 04 Mar 2021 11:22:54 GMT\nServer: MinIO\nVary: Origin\nX-Amz-Request-Id: 16691FDCD237C85A\nX-Xss-Protection: 1; mode=block\nDate: Thu, 04 Mar 2021 11:22:54 GMT\n}\n >>> [io.minio.MinioClient.execute(MinioClient.java:775), io.minio.MinioClient.execute(MinioClient.java:563), io.minio.MinioClient.executePut(MinioClient.java:904), io.minio.MinioClient.copyObject(MinioClient.java:1232), FunctionalTest.testCopyObjectMatchETag(FunctionalTest.java:1850), FunctionalTest.copyObject(FunctionalTest.java:2016), FunctionalTest.runObjectTests(FunctionalTest.java:3757), FunctionalTest.runTests(FunctionalTest.java:3783), FunctionalTest.main(FunctionalTest.java:3927)]"
}
(8/15) Running minio-js tests ... done in 51 seconds
(9/15) Running minio-py tests ... done in 3 minutes and 14 seconds
(10/15) Running s3cmd tests ... FAILED in 6 seconds
{
  "name": "s3cmd",
  "duration": "3129",
  "function": "test_put_object_multipart",
  "status": "FAIL",
  "error": "WARNING: MD5 Sums don't match!\nWARNING: Retrying upload of /mint/data/datafile-65-MB\nWARNING: MD5 Sums don't match!\nWARNING: Retrying upload of /mint/data/datafile-65-MB\nWARNING: MD5 Sums don't match!\nWARNING: Retrying upload of /mint/data/datafile-65-MB\nWARNING: MD5 Sums don't match!\nWARNING: Retrying upload of /mint/data/datafile-65-MB\nWARNING: MD5 Sums don't match!\nWARNING: Retrying upload of /mint/data/datafile-65-MB\nWARNING: MD5 Sums don't match!\nWARNING: Too many failures. Giving up on '/mint/data/datafile-65-MB'\nERROR: \nUpload of '/mint/data/datafile-65-MB' part 1 failed. Use\n  /usr/local/bin/s3cmd abortmp s3://s3cmd-test-bucket-10437/s3cmd-test-object-30251 8b2bac0a-7d60-4af1-966e-c076305e6be9\nto abort the upload, or\n  /usr/local/bin/s3cmd --upload-id 8b2bac0a-7d60-4af1-966e-c076305e6be9 put ...\nto continue the upload.\nERROR: Upload of '/mint/data/datafile-65-MB' failed too many times (Last reason: )"
}
(10/15) Running s3select tests ... done in 7 seconds
(11/15) Running security tests ... done in 0 seconds

Executed 11 out of 15 tests successfully.
```
Deleting image on docker hub
Deleting image locally

File: cmd/iam-etcd-store.go [hunk 1]
```diff
@@ -273,35 +263,53 @@ func (ies *IAMEtcdStore) loadPolicyDoc(ctx context.Context, policy string, m map
...
+	m[policy] = p
+	return nil
+}
+
 func (ies *IAMEtcdStore) loadPolicyDocs(ctx context.Context, m map[string]iampolicy.Policy) error {
 	ctx, cancel := context.WithTimeout(ctx, defaultContextTimeout)
 	defer cancel()
-	r, err := ies.client.Get(ctx, iamConfigPoliciesPrefix, etcd.WithPrefix(), etcd.WithKeysOnly())
+	//we retrieve all keys and values to avoid too many calls to etcd in case of
+	//a large number of policies
```
Comment (harshavardhana) [inline cmd/iam-etcd-store.go]:
```suggestion
	//  Retrieve all keys and values to avoid too many calls to etcd in case of
	//  a large number of policies
```

File: cmd/iam-etcd-store.go [hunk 2]
```diff
@@ -273,35 +263,53 @@ func (ies *IAMEtcdStore) loadPolicyDoc(ctx context.Context, policy string, m map
...
 		if err == errConfigNotFound {
 			return errNoSuchUser
 		}
 		return err
 	}
+	user := extractPrefixAndSuffix(string(userkv.Key), basePrefix, path.Base(string(userkv.Key)))
+	return ies.setupUser(ctx, user, userType, u, m)
+}
 
+func (ies *IAMEtcdStore) setupUser(ctx context.Context, user string, userType IAMUserType, u UserIdentity, m map[string]auth.Credentials) error {
```
Comment (harshavardhana) [inline cmd/iam-etcd-store.go]:
```suggestion
func (ies *IAMEtcdStore) addUser(ctx context.Context, user string, userType IAMUserType, u UserIdentity, m map[string]auth.Credentials) error {
```

File: cmd/iam-etcd-store.go [hunk 3]
```diff
@@ -351,16 +370,16 @@ func (ies *IAMEtcdStore) loadUsers(ctx context.Context, userType IAMUserType, m
 	cctx, cancel := context.WithTimeout(ctx, defaultContextTimeout)
 	defer cancel()
 
-	r, err := ies.client.Get(cctx, basePrefix, etcd.WithPrefix(), etcd.WithKeysOnly())
+	//we retrieve all keys and values to avoid too many calls to etcd in case of
+	//a large number of users
```
Comment (harshavardhana) [inline cmd/iam-etcd-store.go]: Same as above

File: cmd/iam-etcd-store.go [hunk 4]
```diff
@@ -432,17 +464,16 @@ func (ies *IAMEtcdStore) loadMappedPolicies(ctx context.Context, userType IAMUse
 			basePrefix = iamConfigPolicyDBUsersPrefix
 		}
 	}
-
-	r, err := ies.client.Get(cctx, basePrefix, etcd.WithPrefix(), etcd.WithKeysOnly())
+	//we retrieve all keys and values to avoid too many calls to etcd in case of
+	//a large number of policy mappings
```
Comment (harshavardhana) [inline cmd/iam-etcd-store.go]: Same as above

File: cmd/iam-etcd-store.go [hunk 5]
```diff
@@ -432,17 +464,16 @@ func (ies *IAMEtcdStore) loadMappedPolicies(ctx context.Context, userType IAMUse
...
 	if err != nil {
 		return err
 	}
 
-	users := etcdKvsToSetPolicyDB(basePrefix, r.Kvs)
-
-	// Reload config and policies for all users.
-	for _, user := range users.ToSlice() {
-		if err = ies.loadMappedPolicy(ctx, user, userType, isGroup, m); err != nil && err != errNoSuchPolicy {
+	//parse all policies mapping to create the proper data model
```
Comment (harshavardhana) [inline cmd/iam-etcd-store.go]:
```suggestion
	// parse all policies mapping to create the proper data model
```

File: cmd/iam-etcd-store.go [hunk 6]
```diff
@@ -42,34 +42,20 @@ var defaultContextTimeout = 30 * time.Second
...
-	}
-	return items
+// Extract string by stripping off the `prefix` value and the suffix,
+// value, usually in the following form.
+//  s := "config/iam/users/foo/config.json"
+//  prefix := "config/iam/users/"
+//  suffix := "config.json"
+//  result is foo
+func extractPrefixAndSuffix(s string, prefix string, suffix string) string {
+	return path.Clean(strings.TrimSuffix(strings.TrimPrefix(string(s), prefix), suffix))
```
Comment (harshavardhana) [inline cmd/iam-etcd-store.go]: Can we add some unit tests on this while we are at it?

**Review by harshavardhana — CHANGES_REQUESTED** [review]

**Comment by minio-trusted** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-gateway-s3.sh | :heavy_check_mark: |
| mint-dist-erasure.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :x: [more...](#d455187b-0702-458a-a5ec-ce812023488c) |
| mint-fs.sh | :x: [more...](#c5ac080e-4692-4953-b1ff-fdc5f36a950e) |
| mint-erasure.sh | :x: [more...](#2b1e49d2-8c7a-4f42-b083-7e5bbbbb6de7) |
| mint-zoned.sh | :x: [more...](#8d68f045-0a3f-4f5a-b2b1-d18f00ae5981) |
| mint-compress-encrypt-dist-erasure.sh | :x: [more...](#9ac929cd-2bee-4b27-a9e3-2bad5047a774) |
<a name="9ac929cd-2bee-4b27-a9e3-2bad5047a774"></a>
### 11701-3ead0da/mint-compress-encrypt-dist-erasure.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-c2.minio.io:30780
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 87744a7a0e7d:/mint/log /tmp/mint-logs'

(1/15) Running aws-sdk-go tests ... done in 1 seconds
(2/15) Running aws-sdk-java tests ... done in 2 seconds
(3/15) Running aws-sdk-php tests ... done in 43 seconds
(4/15) Running aws-sdk-ruby tests ... done in 5 seconds
(5/15) Running awscli tests ... FAILED in 32 seconds
{
  "name": "awscli",
  "duration": 2790,
  "function": "aws --endpoint-url http://minio-c2.minio.io:30780 s3api copy-object --bucket awscli-mint-test-bucket-32089 --key datafile-1-kB-copy --copy-source awscli-mint-test-bucket-32089/datafile-1-kB\n",
  "status": "FAIL",
  "error": "Hash mismatch expected 084e1383b70fb0c51acc680fef370023, got ac57de7156d7fc25ac1a65f81fa3989b"
}
(5/15) Running healthcheck tests ... done in 1 seconds
(6/15) Running mc tests ... done in 44 seconds
(7/15) Running minio-dotnet tests ... done in 37 seconds
(8/15) Running minio-go tests ... FAILED in 2 minutes and 8 seconds
{
  "args": {
    "destination": {
      "Bucket": "minio-go-test-xh9hrd4m3qcje1ya",
      "Object": "dstObject",
      "Encryption": {},
      "UserMetadata": null,
      "ReplaceMetadata": false,
      "UserTags": null,
      "ReplaceTags": false,
      "LegalHold": "",
      "Mode": "",
      "RetainUntilDate": "0001-01-01T00:00:00Z",
      "Size": 0,
      "Progress": null
    },
    "source": {
      "Bucket": "minio-go-test-xh9hrd4m3qcje1ya",
      "Object": "srcObject",
      "VersionID": "",
      "MatchETag": "",
      "NoMatchETag": "",
      "MatchModifiedSince": "0001-01-01T00:00:00Z",
      "MatchUnmodifiedSince": "0001-01-01T00:00:00Z",
      "MatchRange": false,
      "Start": 0,
      "End": 0,
      "Encryption": null
    }
  },
  "duration": 5459,
  "error": "We encountered an internal error, please try again.: cause(s2: corrupt input)",
  "function": "CopyObject(destination, source)",
  "message": "GetObject failed",
  "name": "minio-go: testUnencryptedToSSES3CopyObject",
  "status": "FAIL"
}
(8/15) Running minio-java tests ... FAILED in 1 minutes and 55 seconds
{
  "name": "minio-java",
  "function": "copyObject()",
  "args": "[match etag]",
  "duration": 248,
  "status": "FAIL",
  "error": "error occurred\nErrorResponse(code = PreconditionFailed, message = At least one of the pre-conditions you specified did not hold, bucketName = minio-java-test-17jidut, objectName = minio-java-test-165ug50-copy, resource = /minio-java-test-17jidut/minio-java-test-165ug50-copy, requestId = 16696847C46512A1, hostId = 2f5901f8-942f-43c7-80a3-4d3f62b75e4c)\nrequest={method=PUT, url=http://minio-c2.minio.io:30780/minio-java-test-17jidut/minio-java-test-165ug50-copy, headers=x-amz-copy-source-if-match: 71cff0a060f852067e443ad1e24ae26c-1\nx-amz-copy-source: /minio-java-test-2mjtcuk/minio-java-test-165ug50\nHost: minio-c2.minio.io:30780\nAccept-Encoding: identity\nUser-Agent: MinIO (Linux; amd64) minio-java/8.0.3\nContent-MD5: 1B2M2Y8AsgTpgAmY7PhCfg==\nx-amz-content-sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855\nx-amz-date: 20210305T092958Z\nAuthorization: AWS4-HMAC-SHA256 Credential=*REDACTED*/20210305/us-east-1/s3/aws4_request, SignedHeaders=content-md5;host;x-amz-content-sha256;x-amz-copy-source;x-amz-copy-source-if-match;x-amz-date, Signature=*REDACTED*\n}\nresponse={code=412, headers=Accept-Ranges: bytes\nContent-Length: 418\nContent-Security-Policy: block-all-mixed-content\nContent-Type: application/xml\nETag: \"71cff0a060f852067e443ad1e24ae26c\"\nLast-Modified: Fri, 05 Mar 2021 09:29:58 GMT\nServer: MinIO\nVary: Origin\nX-Amz-Request-Id: 16696847C46512A1\nX-Xss-Protection: 1; mode=block\nDate: Fri, 05 Mar 2021 09:29:58 GMT\n}\n >>> [io.minio.MinioClient.execute(MinioClient.java:775), io.minio.MinioClient.execute(MinioClient.java:563), io.minio.MinioClient.executePut(MinioClient.java:904), io.minio.MinioClient.copyObject(MinioClient.java:1232), FunctionalTest.testCopyObjectMatchETag(FunctionalTest.java:1850), FunctionalTest.copyObject(FunctionalTest.java:2016), FunctionalTest.runObjectTests(FunctionalTest.java:3757), FunctionalTest.runTests(FunctionalTest.java:3783), FunctionalTest.main(FunctionalTest.java:3927)]"
}
(8/15) Running minio-js tests ... done in 56 seconds
(9/15) Running minio-py tests ... done in 3 minutes and 3 seconds
(10/15) Running s3cmd tests ... FAILED in 5 seconds
{
  "name": "s3cmd",
  "duration": "3027",
  "function": "test_put_object_multipart",
  "status": "FAIL",
  "error": "WARNING: MD5 Sums don't match!\nWARNING: Retrying upload of /mint/data/datafile-65-MB\nWARNING: MD5 Sums don't match!\nWARNING: Retrying upload of /mint/data/datafile-65-MB\nWARNING: MD5 Sums don't match!\nWARNING: Retrying upload of /mint/data/datafile-65-MB\nWARNING: MD5 Sums don't match!\nWARNING: Retrying upload of /mint/data/datafile-65-MB\nWARNING: MD5 Sums don't match!\nWARNING: Retrying upload of /mint/data/datafile-65-MB\nWARNING: MD5 Sums don't match!\nWARNING: Too many failures. Giving up on '/mint/data/datafile-65-MB'\nERROR: \nUpload of '/mint/data/datafile-65-MB' part 1 failed. Use\n  /usr/local/bin/s3cmd abortmp s3://s3cmd-test-bucket-8676/s3cmd-test-object-27969 886f69b4-b6d8-4c41-b3ed-6cb7b1b3250e\nto abort the upload, or\n  /usr/local/bin/s3cmd --upload-id 886f69b4-b6d8-4c41-b3ed-6cb7b1b3250e put ...\nto continue the upload.\nERROR: Upload of '/mint/data/datafile-65-MB' failed too many times (Last reason: )"
}
(10/15) Running s3select tests ... done in 6 seconds
(11/15) Running security tests ... done in 0 seconds

Executed 11 out of 15 tests successfully.
```
<a name="8d68f045-0a3f-4f5a-b2b1-d18f00ae5981"></a>
### 11701-3ead0da/mint-zoned.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-c2.minio.io:31542
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 8354ee4a190d:/mint/log /tmp/mint-logs'

(1/15) Running aws-sdk-go tests ... done in 1 seconds
(2/15) Running aws-sdk-java tests ... done in 2 seconds
(3/15) Running aws-sdk-php tests ... done in 44 seconds
(4/15) Running aws-sdk-ruby tests ... done in 5 seconds
(5/15) Running awscli tests ... done in 2 minutes and 42 seconds
(6/15) Running healthcheck tests ... done in 0 seconds
(7/15) Running mc tests ... FAILED in 6 seconds
{
  "name": "mc",
  "duration": "837",
  "function": "test_put_object_with_metadata",
  "status": "FAIL",
  "error": "unable to put object with metadata"
}
(7/15) Running minio-dotnet tests ... done in 51 seconds
(8/15) Running minio-go tests ... done in 2 minutes and 13 seconds
(9/15) Running minio-java tests ... done in 1 minutes and 55 seconds
(10/15) Running minio-js tests ... done in 56 seconds
(11/15) Running minio-py tests ... done in 3 minutes and 10 seconds
(12/15) Running s3cmd tests ... done in 31 seconds
(13/15) Running s3select tests ... done in 6 seconds
(14/15) Running security tests ... done in 0 seconds

Executed 14 out of 15 tests successfully.
```
<a name="d455187b-0702-458a-a5ec-ce812023488c"></a>
### 11701-3ead0da/mint-large-bucket.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-dev8.minio.io:31767
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp ab0377842c8a:/mint/log /tmp/mint-logs'

(1/15) Running aws-sdk-go tests ... done in 2 seconds
(2/15) Running aws-sdk-java tests ... done in 2 seconds
(3/15) Running aws-sdk-php tests ... done in 43 seconds
(4/15) Running aws-sdk-ruby tests ... done in 6 seconds
(5/15) Running awscli tests ... FAILED in 2 minutes and 12 seconds
{
  "name": "awscli",
  "duration": 66795,
  "function": "delete_bucket\n",
  "status": "FAIL",
  "error": "remove_bucket failed: s3://awscli-mint-test-bucket-18451 An error occurred (BucketNotEmpty) when calling the DeleteBucket operation: The bucket you tried to delete is not empty"
}
(5/15) Running healthcheck tests ... done in 0 seconds
(6/15) Running mc tests ... done in 57 seconds
(7/15) Running minio-dotnet tests ... done in 58 seconds
(8/15) Running minio-go tests ... done in 2 minutes and 21 seconds
(9/15) Running minio-java tests ... done in 1 minutes and 24 seconds
(10/15) Running minio-js tests ... done in 56 seconds
(11/15) Running minio-py tests ... done in 3 minutes and 12 seconds
(12/15) Running s3cmd tests ... done in 23 seconds
(13/15) Running s3select tests ... done in 6 seconds
(14/15) Running security tests ... done in 0 seconds

Executed 14 out of 15 tests successfully.
```
<a name="c5ac080e-4692-4953-b1ff-fdc5f36a950e"></a>
### 11701-3ead0da/mint-fs.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-dev4.minio.io:30790
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp b15b532c072b:/mint/log /tmp/mint-logs'

(1/15) Running aws-sdk-go tests ... done in 0 seconds
(2/15) Running aws-sdk-java tests ... done in 2 seconds
(3/15) Running aws-sdk-php tests ... done in 41 seconds
(4/15) Running aws-sdk-ruby tests ... done in 1 seconds
(5/15) Running awscli tests ... FAILED in 1 minutes and 54 seconds
{
  "name": "awscli",
  "duration": 62873,
  "function": "aws --endpoint-url http://minio-dev4.minio.io:30790 s3 sync --no-progress /mint/data s3://awscli-mint-test-bucket-16974/\n",
  "status": "FAIL",
  "error": "upload: ../../../data/datafile-0-b to s3://awscli-mint-test-bucket-16974/datafile-0-bupload: ../../../data/datafile-1-kB to s3://awscli-mint-test-bucket-16974/datafile-1-kBupload: ../../../data/datafile-100-kB to s3://awscli-mint-test-bucket-16974/datafile-100-kBupload: ../../../data/datafile-10-kB to s3://awscli-mint-test-bucket-16974/datafile-10-kBupload: ../../../data/datafile-33-kB to s3://awscli-mint-test-bucket-16974/datafile-33-kBupload: ../../../data/datafile-1.03-MB to s3://awscli-mint-test-bucket-16974/datafile-1.03-MBupload: ../../../data/datafile-5-MB to s3://awscli-mint-test-bucket-16974/datafile-5-MBupload: ../../../data/datafile-5243880-b to s3://awscli-mint-test-bucket-16974/datafile-5243880-bupload: ../../../data/datafile-10-MB to s3://awscli-mint-test-bucket-16974/datafile-10-MBupload: ../../../data/datafile-6-MB to s3://awscli-mint-test-bucket-16974/datafile-6-MBupload: ../../../data/datafile-11-MB to s3://awscli-mint-test-bucket-16974/datafile-11-MBupload: ../../../data/datafile-1-MB to s3://awscli-mint-test-bucket-16974/datafile-1-MBupload: ../../../data/datafile-65-MB to s3://awscli-mint-test-bucket-16974/datafile-65-MBupload: ../../../data/datafile-129-MB to s3://awscli-mint-test-bucket-16974/datafile-129-MBupload failed: ../../../data/datafile-1-b to s3://awscli-mint-test-bucket-16974/datafile-1-b An error occurred (NoSuchBucket) when calling the PutObject operation: The specified bucket does not exist"
}
(5/15) Running healthcheck tests ... done in 0 seconds
(6/15) Running mc tests ... done in 28 seconds
(7/15) Running minio-dotnet tests ... done in 36 seconds
(8/15) Running minio-go tests ... done in 1 minutes and 10 seconds
(9/15) Running minio-java tests ... done in 35 seconds
(10/15) Running minio-js tests ... done in 45 seconds
(11/15) Running minio-py tests ... done in 1 minutes and 35 seconds
(12/15) Running s3cmd tests ... done in 13 seconds
(13/15) Running s3select tests ... done in 2 seconds
(14/15) Running security tests ... done in 0 seconds

Executed 14 out of 15 tests successfully.
```
<a name="2b1e49d2-8c7a-4f42-b083-7e5bbbbb6de7"></a>
### 11701-3ead0da/mint-erasure.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-c2.minio.io:32636
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 60c68d526764:/mint/log /tmp/mint-logs'

(1/15) Running aws-sdk-go tests ... done in 1 seconds
(2/15) Running aws-sdk-java tests ... done in 1 seconds
(3/15) Running aws-sdk-php tests ... done in 42 seconds
(4/15) Running aws-sdk-ruby tests ... done in 3 seconds
(5/15) Running awscli tests ... done in 2 minutes and 11 seconds
(6/15) Running healthcheck tests ... done in 1 seconds
(7/15) Running mc tests ... FAILED in 55 seconds
{
  "name": "mc",
  "duration": "31653",
  "function": "test_mirror_list_objects_storage_class",
  "status": "FAIL",
  "error": "mirror and list differs"
}
(7/15) Running minio-dotnet tests ... done in 36 seconds
(8/15) Running minio-go tests ... done in 1 minutes and 49 seconds
(9/15) Running minio-java tests ... done in 58 seconds
(10/15) Running minio-js tests ... done in 56 seconds
(11/15) Running minio-py tests ... done in 2 minutes and 11 seconds
(12/15) Running s3cmd tests ... done in 23 seconds
(13/15) Running s3select tests ... done in 5 seconds
(14/15) Running security tests ... done in 0 seconds

Executed 14 out of 15 tests successfully.
```
Deleting image on docker hub
Deleting image locally

**Comment by minio-trusted** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-s3.sh | :heavy_check_mark: |
| mint-erasure.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :x: [more...](#e68e3cea-cc97-4f31-b8ec-1b7f821d9c3c) |
| mint-dist-erasure.sh | :x: [more...](#9eb5658c-838a-409c-b6f4-4e56ee63c910) |
| mint-zoned.sh | :x: [more...](#c486ef75-0595-40e9-8b80-045779061326) |
| mint-gateway-nas.sh | :x: [more...](#a3a9b7ba-30d2-402a-93f2-167f9d87f9d0) |
| mint-compress-encrypt-dist-erasure.sh | :x: [more...](#19410153-0f0f-419b-80bf-6fa6d4d97bbd) |
<a name="19410153-0f0f-419b-80bf-6fa6d4d97bbd"></a>
### 11701-0f04992/mint-compress-encrypt-dist-erasure.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-dev6.minio.io:30141
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 467515b64965:/mint/log /tmp/mint-logs'

(1/15) Running aws-sdk-go tests ... done in 1 seconds
(2/15) Running aws-sdk-java tests ... done in 2 seconds
(3/15) Running aws-sdk-php tests ... done in 43 seconds
(4/15) Running aws-sdk-ruby tests ... done in 4 seconds
(5/15) Running awscli tests ... FAILED in 33 seconds
{
  "name": "awscli",
  "duration": 2738,
  "function": "aws --endpoint-url http://minio-dev6.minio.io:30141 s3api copy-object --bucket awscli-mint-test-bucket-26808 --key datafile-1-kB-copy --copy-source awscli-mint-test-bucket-26808/datafile-1-kB\n",
  "status": "FAIL",
  "error": "Hash mismatch expected 084e1383b70fb0c51acc680fef370023, got ac57de7156d7fc25ac1a65f81fa3989b"
}
(5/15) Running healthcheck tests ... done in 0 seconds
(6/15) Running mc tests ... done in 43 seconds
(7/15) Running minio-dotnet tests ... done in 37 seconds
(8/15) Running minio-go tests ... FAILED in 2 minutes and 8 seconds
{
  "args": {
    "destination": {
      "Bucket": "minio-go-test-rbwz6aprwwdyapu4",
      "Object": "dstObject",
      "Encryption": {},
      "UserMetadata": null,
      "ReplaceMetadata": false,
      "UserTags": null,
      "ReplaceTags": false,
      "LegalHold": "",
      "Mode": "",
      "RetainUntilDate": "0001-01-01T00:00:00Z",
      "Size": 0,
      "Progress": null
    },
    "source": {
      "Bucket": "minio-go-test-rbwz6aprwwdyapu4",
      "Object": "srcObject",
      "VersionID": "",
      "MatchETag": "",
      "NoMatchETag": "",
      "MatchModifiedSince": "0001-01-01T00:00:00Z",
      "MatchUnmodifiedSince": "0001-01-01T00:00:00Z",
      "MatchRange": false,
      "Start": 0,
      "End": 0,
      "Encryption": null
    }
  },
  "duration": 3451,
  "error": "We encountered an internal error, please try again.: cause(s2: corrupt input)",
  "function": "CopyObject(destination, source)",
  "message": "GetObject failed",
  "name": "minio-go: testUnencryptedToSSES3CopyObject",
  "status": "FAIL"
}
(8/15) Running minio-java tests ... FAILED in 1 minutes and 37 seconds
{
  "name": "minio-java",
  "function": "copyObject()",
  "args": "[match etag]",
  "duration": 422,
  "status": "FAIL",
  "error": "error occurred\nErrorResponse(code = PreconditionFailed, message = At least one of the pre-conditions you specified did not hold, bucketName = minio-java-test-2re2q19, objectName = minio-java-test-unq79l-copy, resource = /minio-java-test-2re2q19/minio-java-test-unq79l-copy, requestId = 16696F04DEC10BCD, hostId = f41d3a1a-5d6f-470f-bd6b-d208678356ad)\nrequest={method=PUT, url=http://minio-dev6.minio.io:30141/minio-java-test-2re2q19/minio-java-test-unq79l-copy, headers=x-amz-copy-source-if-match: 71cff0a060f852067e443ad1e24ae26c-1\nx-amz-copy-source: /minio-java-test-3i6p00r/minio-java-test-unq79l\nHost: minio-dev6.minio.io:30141\nAccept-Encoding: identity\nUser-Agent: MinIO (Linux; amd64) minio-java/8.0.3\nContent-MD5: 1B2M2Y8AsgTpgAmY7PhCfg==\nx-amz-content-sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855\nx-amz-date: 20210305T113327Z\nAuthorization: AWS4-HMAC-SHA256 Credential=*REDACTED*/20210305/us-east-1/s3/aws4_request, SignedHeaders=content-md5;host;x-amz-content-sha256;x-amz-copy-source;x-amz-copy-source-if-match;x-amz-date, Signature=*REDACTED*\n}\nresponse={code=412, headers=Accept-Ranges: bytes\nContent-Length: 416\nContent-Security-Policy: block-all-mixed-content\nContent-Type: application/xml\nETag: \"71cff0a060f852067e443ad1e24ae26c\"\nLast-Modified: Fri, 05 Mar 2021 11:33:27 GMT\nServer: MinIO\nVary: Origin\nX-Amz-Request-Id: 16696F04DEC10BCD\nX-Xss-Protection: 1; mode=block\nDate: Fri, 05 Mar 2021 11:33:28 GMT\n}\n >>> [io.minio.MinioClient.execute(MinioClient.java:775), io.minio.MinioClient.execute(MinioClient.java:563), io.minio.MinioClient.executePut(MinioClient.java:904), io.minio.MinioClient.copyObject(MinioClient.java:1232), FunctionalTest.testCopyObjectMatchETag(FunctionalTest.java:1850), FunctionalTest.copyObject(FunctionalTest.java:2016), FunctionalTest.runObjectTests(FunctionalTest.java:3757), FunctionalTest.runTests(FunctionalTest.java:3783), FunctionalTest.main(FunctionalTest.java:3927)]"
}
(8/15) Running minio-js tests ... done in 59 seconds
(9/15) Running minio-py tests ... done in 2 minutes and 54 seconds
(10/15) Running s3cmd tests ... FAILED in 6 seconds
{
  "name": "s3cmd",
  "duration": "3627",
  "function": "test_put_object_multipart",
  "status": "FAIL",
  "error": "WARNING: MD5 Sums don't match!\nWARNING: Retrying upload of /mint/data/datafile-65-MB\nWARNING: MD5 Sums don't match!\nWARNING: Retrying upload of /mint/data/datafile-65-MB\nWARNING: MD5 Sums don't match!\nWARNING: Retrying upload of /mint/data/datafile-65-MB\nWARNING: MD5 Sums don't match!\nWARNING: Retrying upload of /mint/data/datafile-65-MB\nWARNING: MD5 Sums don't match!\nWARNING: Retrying upload of /mint/data/datafile-65-MB\nWARNING: MD5 Sums don't match!\nWARNING: Too many failures. Giving up on '/mint/data/datafile-65-MB'\nERROR: \nUpload of '/mint/data/datafile-65-MB' part 1 failed. Use\n  /usr/local/bin/s3cmd abortmp s3://s3cmd-test-bucket-19349/s3cmd-test-object-13435 e10ee670-9a61-45c6-a158-cdc7b51906f8\nto abort the upload, or\n  /usr/local/bin/s3cmd --upload-id e10ee670-9a61-45c6-a158-cdc7b51906f8 put ...\nto continue the upload.\nERROR: Upload of '/mint/data/datafile-65-MB' failed too many times (Last reason: )"
}
(10/15) Running s3select tests ... done in 6 seconds
(11/15) Running security tests ... done in 0 seconds

Executed 11 out of 15 tests successfully.
```
<a name="e68e3cea-cc97-4f31-b8ec-1b7f821d9c3c"></a>
### 11701-0f04992/mint-large-bucket.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-c3.minio.io:31722
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 88eaa3076f30:/mint/log /tmp/mint-logs'

(1/15) Running aws-sdk-go tests ... done in 1 seconds
(2/15) Running aws-sdk-java tests ... done in 2 seconds
(3/15) Running aws-sdk-php tests ... done in 43 seconds
(4/15) Running aws-sdk-ruby tests ... done in 5 seconds
(5/15) Running awscli tests ... done in 2 minutes and 19 seconds
(6/15) Running healthcheck tests ... done in 1 seconds
(7/15) Running mc tests ... FAILED in 46 seconds
{
  "name": "mc",
  "duration": "10050",
  "function": "test_mirror_list_objects_storage_class",
  "status": "FAIL",
  "error": "mirror and list differs"
}
(7/15) Running minio-dotnet tests ... done in 52 seconds
(8/15) Running minio-go tests ... done in 2 minutes and 9 seconds
(9/15) Running minio-java tests ... done in 1 minutes and 8 seconds
(10/15) Running minio-js tests ... done in 49 seconds
(11/15) Running minio-py tests ... done in 3 minutes and 0 seconds
(12/15) Running s3cmd tests ... done in 22 seconds
(13/15) Running s3select tests ... done in 6 seconds
(14/15) Running security tests ... done in 0 seconds

Executed 14 out of 15 tests successfully.
```
<a name="9eb5658c-838a-409c-b6f4-4e56ee63c910"></a>
### 11701-0f04992/mint-dist-erasure.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-c2.minio.io:32142
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp a03deaffcfe2:/mint/log /tmp/mint-logs'

(1/15) Running aws-sdk-go tests ... done in 2 seconds
(2/15) Running aws-sdk-java tests ... done in 1 seconds
(3/15) Running aws-sdk-php tests ... done in 43 seconds
(4/15) Running aws-sdk-ruby tests ... done in 4 seconds
(5/15) Running awscli tests ... FAILED in 11 minutes and 31 seconds
{"name": "awscli", "duration": 626764, "function": "aws --endpoint-url http://minio-c2.minio.io:32142 s3 sync --no-progress /mint/data s3://awscli-mint-test-bucket-25589/\n", "status": "FAIL", "error": "upload: ../../../data/datafile-0-b to s3://awscli-mint-test-bucket-25589/datafile-0-bupload: ../../../data/datafile-1-b to s3://awscli-mint-test-bucket-25589/datafile-1-bupload: ../../../data/datafile-1-kB to s3://awscli-mint-test-bucket-25589/datafile-1-kBupload: ../../../data/datafile-10-kB to s3://awscli-mint-test-bucket-25589/datafile-10-kBupload: ../../../data/datafile-100-kB to s3://awscli-mint-test-bucket-25589/datafile-100-kBupload: ../../../data/datafile-33-kB to s3://awscli-mint-test-bucket-25589/datafile-33-kBupload: ../../../data/datafile-1-MB to s3://awscli-mint-test-bucket-25589/datafile-1-MBupload: ../../../data/datafile-1.03-MB to s3://awscli-mint-test-bucket-25589/datafile-1.03-MBupload: ../../../data/datafile-6-MB to s3://awscli-mint-test-bucket-25589/datafile-6-MBupload: ../../../data/datafile-5243880-b to s3://awscli-mint-test-bucket-25589/datafile-5243880-bupload: ../../../data/datafile-5-MB to s3://awscli-mint-test-bucket-25589/datafile-5-MBupload: ../../../data/datafile-11-MB to s3://awscli-mint-test-bucket-25589/datafile-11-MBupload: ../../../data/datafile-10-MB to s3://awscli-mint-test-bucket-25589/datafile-10-MBupload: ../../../data/datafile-65-MB to s3://awscli-mint-test-bucket-25589/datafile-65-MBupload failed: ../../../data/datafile-129-MB to s3://awscli-mint-test-bucket-25589/datafile-129-MB Read timeout on endpoint URL: "http://minio-c2.minio.io:32142/awscli-mint-test-bucket-25589/datafile-129-MB?uploadId=f0d51340-e960-4de4-b411-6937d72ef7dc&partNumber=6""}
(5/15) Running healthcheck tests ... done in 0 seconds
(6/15) Running mc tests ... done in 35 seconds
(7/15) Running minio-dotnet tests ... done in 37 seconds
(8/15) Running minio-go tests ... done in 1 minutes and 11 seconds
(9/15) Running minio-java tests ... done in 49 seconds
(10/15) Running minio-js tests ... done in 48 seconds
(11/15) Running minio-py tests ... done in 2 minutes and 32 seconds
(12/15) Running s3cmd tests ... done in 19 seconds
(13/15) Running s3select tests ... done in 6 seconds
(14/15) Running security tests ... done in 0 seconds

Executed 14 out of 15 tests successfully.
```
<a name="c486ef75-0595-40e9-8b80-045779061326"></a>
### 11701-0f04992/mint-zoned.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-dev8.minio.io:31321
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp e04ccdfaf14d:/mint/log /tmp/mint-logs'

(1/15) Running aws-sdk-go tests ... done in 2 seconds
(2/15) Running aws-sdk-java tests ... done in 1 seconds
(3/15) Running aws-sdk-php tests ... done in 43 seconds
(4/15) Running aws-sdk-ruby tests ... done in 4 seconds
(5/15) Running awscli tests ... FAILED in 2 minutes and 2 seconds
{
  "name": "awscli",
  "duration": 76552,
  "function": "aws --endpoint-url http://minio-dev8.minio.io:31321 s3api upload-part --bucket awscli-mint-test-bucket-7754 --key awscli-mint-test-bucket-7754-object --body /mint/data/datafile-10-MB --upload-id 532ed67a-eff0-41db-8427-395d464413bd --part-number 2\n",
  "status": "FAIL",
  "error": ""
}
(5/15) Running healthcheck tests ... done in 0 seconds
(6/15) Running mc tests ... done in 1 minutes and 12 seconds
(7/15) Running minio-dotnet tests ... done in 49 seconds
(8/15) Running minio-go tests ... done in 2 minutes and 4 seconds
(9/15) Running minio-java tests ... done in 1 minutes and 35 seconds
(10/15) Running minio-js tests ... done in 50 seconds
(11/15) Running minio-py tests ... done in 3 minutes and 1 seconds
(12/15) Running s3cmd tests ... done in 23 seconds
(13/15) Running s3select tests ... done in 9 seconds
(14/15) Running security tests ... done in 0 seconds

Executed 14 out of 15 tests successfully.
```
<a name="a3a9b7ba-30d2-402a-93f2-167f9d87f9d0"></a>
### 11701-0f04992/mint-gateway-nas.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-dev7.minio.io:31629
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp d83d86d4c7b3:/mint/log /tmp/mint-logs'

(1/15) Running aws-sdk-go tests ... done in 0 seconds
(2/15) Running aws-sdk-java tests ... done in 1 seconds
(3/15) Running aws-sdk-php tests ... done in 41 seconds
(4/15) Running aws-sdk-ruby tests ... done in 2 seconds
(5/15) Running awscli tests ... done in 2 minutes and 1 seconds
(6/15) Running healthcheck tests ... done in 0 seconds
(7/15) Running mc tests ... done in 54 seconds
(8/15) Running minio-dotnet tests ... done in 32 seconds
(9/15) Running minio-go tests ... FAILED in 16 minutes and 15 seconds
{
  "args": {
    "bucketName": "minio-go-test-wmkjj6hee0azkxbt",
    "fileName": "/mint/data/datafile-129-MB",
    "location": "us-east-1",
    "objectName": "minio-go-test-wmkjj6hee0azkxbtFPutObject-GTar",
    "opts": {
      "UserMetadata": null,
      "UserTags": null,
      "Progress": null,
      "ContentType": "",
      "ContentEncoding": "",
      "ContentDisposition": "",
      "ContentLanguage": "",
      "CacheControl": "",
      "Mode": "",
      "RetainUntilDate": "0001-01-01T00:00:00Z",
      "ServerSideEncryption": null,
      "NumThreads": 0,
      "StorageClass": "",
      "WebsiteRedirectLocation": "",
      "PartSize": 0,
      "LegalHold": "",
      "SendContentMd5": false,
      "DisableMultipart": false,
      "Internal": {
        "SourceVersionID": "",
        "SourceETag": "",
        "ReplicationStatus": "",
        "SourceMTime": "0001-01-01T00:00:00Z"
      }
    }
  },
  "duration": 954268,
  "error": "The specified bucket does not exist",
  "function": "FPutObject(bucketName, objectName, fileName, opts)",
  "message": "FPutObject failed",
  "name": "minio-go: testFPutObject",
  "status": "FAIL"
}
(9/15) Running minio-java tests ... done in 15 seconds
(10/15) Running minio-js tests ... done in 30 seconds
(11/15) Running minio-py tests ... done in 1 minutes and 4 seconds
(12/15) Running s3cmd tests ... done in 13 seconds
(13/15) Running s3select tests ... done in 3 seconds
(14/15) Running security tests ... done in 0 seconds

Executed 14 out of 15 tests successfully.
```
Deleting image on docker hub
Deleting image locally

**Comment by minio-trusted** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-erasure.sh | :heavy_check_mark: |
| mint-dist-erasure.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :x: [more...](#a8bccdc1-adc6-4dcf-8f5d-54714dd95a2e) |
| mint-fs.sh | :x: [more...](#cc869392-2c33-4941-bb30-88697bef8e0d) |
| mint-gateway-s3.sh | :x: [more...](#dc7151a8-f7b0-4150-a9e2-966a2d134611) |
| mint-zoned.sh | :x: [more...](#b03bd7cb-651e-4a5e-8fb8-2595eaf0406e) |
| mint-compress-encrypt-dist-erasure.sh | :x: [more...](#32f7324a-0d25-419f-a41f-0440d11202fb) |
<a name="dc7151a8-f7b0-4150-a9e2-966a2d134611"></a>
### 11701-b8993a1/mint-gateway-s3.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-c3.minio.io:30900
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp fc567c294bb5:/mint/log /tmp/mint-logs'

(1/15) Running aws-sdk-go tests ... done in 1 seconds
(2/15) Running aws-sdk-java tests ... done in 2 seconds
(3/15) Running aws-sdk-php tests ... done in 42 seconds
(4/15) Running aws-sdk-ruby tests ... done in 3 seconds
(5/15) Running awscli tests ... FAILED in 1 minutes and 9 seconds
{
  "name": "awscli",
  "duration": 15229,
  "function": "aws --endpoint-url http://minio-c3.minio.io:30900 s3 rm s3://awscli-mint-test-bucket-4459/datafile-65-MB\n",
  "status": "FAIL",
  "error": "delete failed: s3://awscli-mint-test-bucket-4459/datafile-65-MB An error occurred (NoSuchBucket) when calling the DeleteObject operation: The specified bucket does not exist"
}
(5/15) Running healthcheck tests ... done in 0 seconds
(6/15) Running mc tests ... done in 50 seconds
(7/15) Running minio-dotnet tests ... done in 40 seconds
(8/15) Running minio-go tests ... done in 59 seconds
(9/15) Running minio-java tests ... done in 1 minutes and 8 seconds
(10/15) Running minio-js tests ... done in 41 seconds
(11/15) Running minio-py tests ... done in 2 minutes and 13 seconds
(12/15) Running s3cmd tests ... done in 1 minutes and 7 seconds
(13/15) Running s3select tests ... done in 5 seconds
(14/15) Running security tests ... done in 0 seconds

Executed 14 out of 15 tests successfully.
```
<a name="32f7324a-0d25-419f-a41f-0440d11202fb"></a>
### 11701-b8993a1/mint-compress-encrypt-dist-erasure.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-dev6.minio.io:31348
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp b76de9c253c5:/mint/log /tmp/mint-logs'

(1/15) Running aws-sdk-go tests ... done in 2 seconds
(2/15) Running aws-sdk-java tests ... done in 1 seconds
(3/15) Running aws-sdk-php tests ... done in 43 seconds
(4/15) Running aws-sdk-ruby tests ... done in 4 seconds
(5/15) Running awscli tests ... FAILED in 33 seconds
{
  "name": "awscli",
  "duration": 2708,
  "function": "aws --endpoint-url http://minio-dev6.minio.io:31348 s3api copy-object --bucket awscli-mint-test-bucket-15179 --key datafile-1-kB-copy --copy-source awscli-mint-test-bucket-15179/datafile-1-kB\n",
  "status": "FAIL",
  "error": "Hash mismatch expected 084e1383b70fb0c51acc680fef370023, got ac57de7156d7fc25ac1a65f81fa3989b"
}
(5/15) Running healthcheck tests ... done in 1 seconds
(6/15) Running mc tests ... done in 52 seconds
(7/15) Running minio-dotnet tests ... done in 1 minutes and 1 seconds
(8/15) Running minio-go tests ... FAILED in 1 minutes and 55 seconds
{
  "args": {
    "destination": {
      "Bucket": "minio-go-test-e5p5gj6uxfzndc1f",
      "Object": "dstObject",
      "Encryption": {},
      "UserMetadata": null,
      "ReplaceMetadata": false,
      "UserTags": null,
      "ReplaceTags": false,
      "LegalHold": "",
      "Mode": "",
      "RetainUntilDate": "0001-01-01T00:00:00Z",
      "Size": 0,
      "Progress": null
    },
    "source": {
      "Bucket": "minio-go-test-e5p5gj6uxfzndc1f",
      "Object": "srcObject",
      "VersionID": "",
      "MatchETag": "",
      "NoMatchETag": "",
      "MatchModifiedSince": "0001-01-01T00:00:00Z",
      "MatchUnmodifiedSince": "0001-01-01T00:00:00Z",
      "MatchRange": false,
      "Start": 0,
      "End": 0,
      "Encryption": null
    }
  },
  "duration": 6424,
  "error": "We encountered an internal error, please try again.: cause(s2: corrupt input)",
  "function": "CopyObject(destination, source)",
  "message": "GetObject failed",
  "name": "minio-go: testUnencryptedToSSES3CopyObject",
  "status": "FAIL"
}
(8/15) Running minio-java tests ... FAILED in 1 minutes and 30 seconds
{
  "name": "minio-java",
  "function": "copyObject()",
  "args": "[match etag]",
  "duration": 244,
  "status": "FAIL",
  "error": "error occurred\nErrorResponse(code = PreconditionFailed, message = At least one of the pre-conditions you specified did not hold, bucketName = minio-java-test-1fc7f52, objectName = minio-java-test-3qkt850-copy, resource = /minio-java-test-1fc7f52/minio-java-test-3qkt850-copy, requestId = 166970A7075F0857, hostId = 02d80137-9ddf-47a9-8178-2ef32ed94bc8)\nrequest={method=PUT, url=http://minio-dev6.minio.io:31348/minio-java-test-1fc7f52/minio-java-test-3qkt850-copy, headers=x-amz-copy-source-if-match: 71cff0a060f852067e443ad1e24ae26c-1\nx-amz-copy-source: /minio-java-test-2562r00/minio-java-test-3qkt850\nHost: minio-dev6.minio.io:31348\nAccept-Encoding: identity\nUser-Agent: MinIO (Linux; amd64) minio-java/8.0.3\nContent-MD5: 1B2M2Y8AsgTpgAmY7PhCfg==\nx-amz-content-sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855\nx-amz-date: 20210305T120323Z\nAuthorization: AWS4-HMAC-SHA256 Credential=*REDACTED*/20210305/us-east-1/s3/aws4_request, SignedHeaders=content-md5;host;x-amz-content-sha256;x-amz-copy-source;x-amz-copy-source-if-match;x-amz-date, Signature=*REDACTED*\n}\nresponse={code=412, headers=Accept-Ranges: bytes\nContent-Length: 418\nContent-Security-Policy: block-all-mixed-content\nContent-Type: application/xml\nETag: \"71cff0a060f852067e443ad1e24ae26c\"\nLast-Modified: Fri, 05 Mar 2021 12:03:24 GMT\nServer: MinIO\nVary: Origin\nX-Amz-Request-Id: 166970A7075F0857\nX-Xss-Protection: 1; mode=block\nDate: Fri, 05 Mar 2021 12:03:24 GMT\n}\n >>> [io.minio.MinioClient.execute(MinioClient.java:775), io.minio.MinioClient.execute(MinioClient.java:563), io.minio.MinioClient.executePut(MinioClient.java:904), io.minio.MinioClient.copyObject(MinioClient.java:1232), FunctionalTest.testCopyObjectMatchETag(FunctionalTest.java:1850), FunctionalTest.copyObject(FunctionalTest.java:2016), FunctionalTest.runObjectTests(FunctionalTest.java:3757), FunctionalTest.runTests(FunctionalTest.java:3783), FunctionalTest.main(FunctionalTest.java:3927)]"
}
(8/15) Running minio-js tests ... done in 50 seconds
(9/15) Running minio-py tests ... done in 3 minutes and 40 seconds
(10/15) Running s3cmd tests ... FAILED in 6 seconds
{
  "name": "s3cmd",
  "duration": "3148",
  "function": "test_put_object_multipart",
  "status": "FAIL",
  "error": "WARNING: MD5 Sums don't match!\nWARNING: Retrying upload of /mint/data/datafile-65-MB\nWARNING: MD5 Sums don't match!\nWARNING: Retrying upload of /mint/data/datafile-65-MB\nWARNING: MD5 Sums don't match!\nWARNING: Retrying upload of /mint/data/datafile-65-MB\nWARNING: MD5 Sums don't match!\nWARNING: Retrying upload of /mint/data/datafile-65-MB\nWARNING: MD5 Sums don't match!\nWARNING: Retrying upload of /mint/data/datafile-65-MB\nWARNING: MD5 Sums don't match!\nWARNING: Too many failures. Giving up on '/mint/data/datafile-65-MB'\nERROR: \nUpload of '/mint/data/datafile-65-MB' part 1 failed. Use\n  /usr/local/bin/s3cmd abortmp s3://s3cmd-test-bucket-13152/s3cmd-test-object-26624 eb44ee06-1a87-40bf-9129-a2596d7db6cb\nto abort the upload, or\n  /usr/local/bin/s3cmd --upload-id eb44ee06-1a87-40bf-9129-a2596d7db6cb put ...\nto continue the upload.\nERROR: Upload of '/mint/data/datafile-65-MB' failed too many times (Last reason: )"
}
(10/15) Running s3select tests ... done in 7 seconds
(11/15) Running security tests ... done in 0 seconds

Executed 11 out of 15 tests successfully.
```
<a name="cc869392-2c33-4941-bb30-88697bef8e0d"></a>
### 11701-b8993a1/mint-fs.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-dev4.minio.io:30549
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp cae35f607349:/mint/log /tmp/mint-logs'

(1/15) Running aws-sdk-go tests ... done in 0 seconds
(2/15) Running aws-sdk-java tests ... done in 2 seconds
(3/15) Running aws-sdk-php tests ... done in 41 seconds
(4/15) Running aws-sdk-ruby tests ... done in 2 seconds
(5/15) Running awscli tests ... FAILED in 1 minutes and 53 seconds
{
  "name": "awscli",
  "duration": 63138,
  "function": "aws --endpoint-url http://minio-dev4.minio.io:30549 s3 sync --no-progress /mint/data s3://awscli-mint-test-bucket-23959/\n",
  "status": "FAIL",
  "error": "upload: ../../../data/datafile-0-b to s3://awscli-mint-test-bucket-23959/datafile-0-bupload: ../../../data/datafile-1-b to s3://awscli-mint-test-bucket-23959/datafile-1-bupload: ../../../data/datafile-10-kB to s3://awscli-mint-test-bucket-23959/datafile-10-kBupload: ../../../data/datafile-33-kB to s3://awscli-mint-test-bucket-23959/datafile-33-kBupload: ../../../data/datafile-100-kB to s3://awscli-mint-test-bucket-23959/datafile-100-kBupload: ../../../data/datafile-1-MB to s3://awscli-mint-test-bucket-23959/datafile-1-MBupload: ../../../data/datafile-1.03-MB to s3://awscli-mint-test-bucket-23959/datafile-1.03-MBupload: ../../../data/datafile-6-MB to s3://awscli-mint-test-bucket-23959/datafile-6-MBupload: ../../../data/datafile-10-MB to s3://awscli-mint-test-bucket-23959/datafile-10-MBupload: ../../../data/datafile-5-MB to s3://awscli-mint-test-bucket-23959/datafile-5-MBupload: ../../../data/datafile-5243880-b to s3://awscli-mint-test-bucket-23959/datafile-5243880-bupload: ../../../data/datafile-11-MB to s3://awscli-mint-test-bucket-23959/datafile-11-MBupload: ../../../data/datafile-65-MB to s3://awscli-mint-test-bucket-23959/datafile-65-MBupload: ../../../data/datafile-129-MB to s3://awscli-mint-test-bucket-23959/datafile-129-MBupload failed: ../../../data/datafile-1-kB to s3://awscli-mint-test-bucket-23959/datafile-1-kB An error occurred (NoSuchBucket) when calling the PutObject operation: The specified bucket does not exist"
}
(5/15) Running healthcheck tests ... done in 1 seconds
(6/15) Running mc tests ... done in 33 seconds
(7/15) Running minio-dotnet tests ... done in 33 seconds
(8/15) Running minio-go tests ... done in 59 seconds
(9/15) Running minio-java tests ... done in 30 seconds
(10/15) Running minio-js tests ... done in 43 seconds
(11/15) Running minio-py tests ... done in 1 minutes and 14 seconds
(12/15) Running s3cmd tests ... done in 14 seconds
(13/15) Running s3select tests ... done in 3 seconds
(14/15) Running security tests ... done in 0 seconds

Executed 14 out of 15 tests successfully.
```
<a name="a8bccdc1-adc6-4dcf-8f5d-54714dd95a2e"></a>
### 11701-b8993a1/mint-large-bucket.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-dev7.minio.io:31684
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp d5e32c7da81f:/mint/log /tmp/mint-logs'

(1/15) Running aws-sdk-go tests ... done in 1 seconds
(2/15) Running aws-sdk-java tests ... done in 2 seconds
(3/15) Running aws-sdk-php tests ... done in 43 seconds
(4/15) Running aws-sdk-ruby tests ... done in 5 seconds
(5/15) Running awscli tests ... done in 2 minutes and 19 seconds
(6/15) Running healthcheck tests ... done in 1 seconds
(7/15) Running mc tests ... FAILED in 4 seconds
{
  "name": "mc",
  "duration": "443",
  "function": "test_put_object_with_metadata",
  "status": "FAIL",
  "error": "unable to put object with metadata"
}
(7/15) Running minio-dotnet tests ... done in 54 seconds
(8/15) Running minio-go tests ... done in 1 minutes and 53 seconds
(9/15) Running minio-java tests ... done in 1 minutes and 25 seconds
(10/15) Running minio-js tests ... done in 50 seconds
(11/15) Running minio-py tests ... done in 3 minutes and 27 seconds
(12/15) Running s3cmd tests ... done in 22 seconds
(13/15) Running s3select tests ... done in 7 seconds
(14/15) Running security tests ... done in 0 seconds

Executed 14 out of 15 tests successfully.
```
<a name="b03bd7cb-651e-4a5e-8fb8-2595eaf0406e"></a>
### 11701-b8993a1/mint-zoned.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-c2.minio.io:30202
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp e6fff73ef1fc:/mint/log /tmp/mint-logs'

(1/15) Running aws-sdk-go tests ... done in 2 seconds
(2/15) Running aws-sdk-java tests ... done in 2 seconds
(3/15) Running aws-sdk-php tests ... done in 43 seconds
(4/15) Running aws-sdk-ruby tests ... done in 5 seconds
(5/15) Running awscli tests ... FAILED in 7 minutes and 31 seconds
{
  "name": "awscli",
  "duration": 389297,
  "function": "aws --endpoint-url http://minio-c2.minio.io:30202 s3 sync --no-progress /mint/data s3://awscli-mint-test-bucket-23773/\n",
  "status": "FAIL",
  "error": "upload: ../../../data/datafile-0-b to s3://awscli-mint-test-bucket-23773/datafile-0-bupload: ../../../data/datafile-1-b to s3://awscli-mint-test-bucket-23773/datafile-1-bupload: ../../../data/datafile-1-kB to s3://awscli-mint-test-bucket-23773/datafile-1-kBupload: ../../../data/datafile-100-kB to s3://awscli-mint-test-bucket-23773/datafile-100-kBupload: ../../../data/datafile-10-kB to s3://awscli-mint-test-bucket-23773/datafile-10-kBupload: ../../../data/datafile-33-kB to s3://awscli-mint-test-bucket-23773/datafile-33-kBupload: ../../../data/datafile-1-MB to s3://awscli-mint-test-bucket-23773/datafile-1-MBupload: ../../../data/datafile-1.03-MB to s3://awscli-mint-test-bucket-23773/datafile-1.03-MBupload: ../../../data/datafile-5243880-b to s3://awscli-mint-test-bucket-23773/datafile-5243880-bupload: ../../../data/datafile-10-MB to s3://awscli-mint-test-bucket-23773/datafile-10-MBupload: ../../../data/datafile-5-MB to s3://awscli-mint-test-bucket-23773/datafile-5-MBupload: ../../../data/datafile-6-MB to s3://awscli-mint-test-bucket-23773/datafile-6-MBupload: ../../../data/datafile-11-MB to s3://awscli-mint-test-bucket-23773/datafile-11-MBupload failed: ../../../data/datafile-129-MB to s3://awscli-mint-test-bucket-23773/datafile-129-MB An error occurred (SlowDown) when calling the UploadPart operation (reached max retries: 4): Please reduce your requestupload failed: ../../../data/datafile-65-MB to s3://awscli-mint-test-bucket-23773/datafile-65-MB An error occurred (SlowDown) when calling the UploadPart operation (reached max retries: 4): Please reduce your request"
}
(5/15) Running healthcheck tests ... done in 0 seconds
(6/15) Running mc tests ... done in 35 seconds
(7/15) Running minio-dotnet tests ... done in 41 seconds
(8/15) Running minio-go tests ... done in 1 minutes and 24 seconds
(9/15) Running minio-java tests ... done in 1 minutes and 28 seconds
(10/15) Running minio-js tests ... done in 49 seconds
(11/15) Running minio-py tests ... done in 2 minutes and 43 seconds
(12/15) Running s3cmd tests ... done in 19 seconds
(13/15) Running s3select tests ... done in 6 seconds
(14/15) Running security tests ... done in 0 seconds

Executed 14 out of 15 tests successfully.
```
Deleting image on docker hub
Deleting image locally

**Comment by sgandon** [comment]
So many mint failures, I'll try to reproduce those issues locally, but this morning there was only 1 error.

**Comment by harshavardhana** [comment]
@sgandon it might not related to your PR it is some infrastructure issue on our end.

**Review by harshavardhana — APPROVED** [review]

**Review by klauspost — APPROVED** [review]
LGTM
