### PR TITLE
Use default ports for the schemes when dialing

### LINKED ISSUE #7946: Can't ‘endpoint’ of webhook set ports 80 and 443?
## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Version used (`minio version`):
* Environment name and version (e.g. nginx 1.9.1):
* Server type and version:
* Operating System and version (`uname -a`):
* Link to your project:

### PR DESCRIPTION
**Pull request by Praveenrajmani**
## Description
The targets may have been configured with default ports say, 443 for `https` or 80 for `http`. In such cases, the tcp dialup should not fail if the port is not provided in the target config 

## Motivation and Context
Fixes #7946

## How to test this PR?
Run the target in http/https on default ports and do not specify the port in the config url

## Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [ ] Fixes a regression (If yes, please add `commit-id` or `PR #` here)
- [ ] Documentation needed
- [ ] Unit tests needed
- [ ] Functional tests needed (If yes, add [mint](https://github.com/minio/mint) PR # here: )

### CODE REVIEW

**Comment by minio-ops** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-worm.sh | :heavy_check_mark: |
| mint-compression-xl.sh | :x: [more...](#fb1ec12d-9851-473b-82d7-95dbbd3d374d) |
| mint-xl.sh | :x: [more...](#6d8b19c1-b12f-4ef9-ac14-b555a0b7362d) |
| mint-large-bucket.sh | :x: [more...](#d3160f58-cfc7-4c34-84ae-7642b0ade7ef) |
| mint-compression-dist-xl.sh | :x: [more...](#cdb78edb-8e41-40ed-8496-7763c2cc1706) |
| mint-compression-fs.sh | :x: [more...](#c7a96eb0-5a48-4c9d-b6fb-e87c062c39b6) |
| mint-fs.sh | :x: [more...](#c1c1e726-8bab-4ff0-93c9-11872545cfc4) |
| mint-dist-xl.sh | :x: [more...](#4754a048-4166-43ca-a540-f7c2f0885207) |
| mint-gateway-nas.sh | :x: [more...](#827fc215-7706-4555-afa8-f03a2142fea5) |
<a name="cdb78edb-8e41-40ed-8496-7763c2cc1706"></a>
### 7960-71cf850/mint-compression-dist-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.51:31523
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 6c3b827be12b:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... FAILED in 0 seconds
{
  "alert": "",
  "args": {
    "bucketName": "aws-sdk-go-test-ofudyxb06ewyye",
    "objectName1": "object1.csv",
    "objectName2": "object2.csv"
  },
  "duration": 62,
  "error": "MalformedXML: The XML provided was not well-formed or did not validate against our published schema. Check the service documentation and try again.\n\tstatus code: 400, request id: 15B3AB24063FC284, host id: ",
  "function": "testSelectObject",
  "message": "AWS SDK Go Select object failed for unicode separator MalformedXML: The XML provided was not well-formed or did not validate against our published schema. Check the service documentation and try again.\n\tstatus code: 400, request id: 15B3AB24063FC284, host id: ",
  "name": "aws-sdk-go",
  "status": "FAIL"
}

Executed 0 out of 14 tests successfully.
```
<a name="6d8b19c1-b12f-4ef9-ac14-b555a0b7362d"></a>
### 7960-71cf850/mint-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.61:30401
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 69b2ed7797ed:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... FAILED in 0 seconds
{
  "alert": "",
  "args": {
    "bucketName": "aws-sdk-go-test-4mekz9mh6tmn5c",
    "objectName1": "object1.csv",
    "objectName2": "object2.csv"
  },
  "duration": 26,
  "error": "MalformedXML: The XML provided was not well-formed or did not validate against our published schema. Check the service documentation and try again.\n\tstatus code: 400, request id: 15B3AB23BBA084C1, host id: ",
  "function": "testSelectObject",
  "message": "AWS SDK Go Select object failed for unicode separator MalformedXML: The XML provided was not well-formed or did not validate against our published schema. Check the service documentation and try again.\n\tstatus code: 400, request id: 15B3AB23BBA084C1, host id: ",
  "name": "aws-sdk-go",
  "status": "FAIL"
}

Executed 0 out of 14 tests successfully.
```
<a name="827fc215-7706-4555-afa8-f03a2142fea5"></a>
### 7960-71cf850/mint-gateway-nas.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.52:32586
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp a1d0a10c9e72:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... FAILED in 0 seconds
{
  "alert": "",
  "args": {
    "bucketName": "aws-sdk-go-test-ofpk1zdxcwaoor",
    "objectName1": "object1.csv",
    "objectName2": "object2.csv"
  },
  "duration": 18,
  "error": "MalformedXML: The XML provided was not well-formed or did not validate against our published schema. Check the service documentation and try again.\n\tstatus code: 400, request id: 15B3AB23E32A6424, host id: ",
  "function": "testSelectObject",
  "message": "AWS SDK Go Select object failed for unicode separator MalformedXML: The XML provided was not well-formed or did not validate against our published schema. Check the service documentation and try again.\n\tstatus code: 400, request id: 15B3AB23E32A6424, host id: ",
  "name": "aws-sdk-go",
  "status": "FAIL"
}

Executed 0 out of 14 tests successfully.
```
<a name="d3160f58-cfc7-4c34-84ae-7642b0ade7ef"></a>
### 7960-71cf850/mint-large-bucket.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.56:31161
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 20fb73691cee:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... FAILED in 2 seconds
{
  "alert": "",
  "args": {
    "bucketName": "aws-sdk-go-test-ubxfqibhcbocbv",
    "objectName1": "object1.csv",
    "objectName2": "object2.csv"
  },
  "duration": 196,
  "error": "MalformedXML: The XML provided was not well-formed or did not validate against our published schema. Check the service documentation and try again.\n\tstatus code: 400, request id: 15B3AB246C59DB76, host id: ",
  "function": "testSelectObject",
  "message": "AWS SDK Go Select object failed for unicode separator MalformedXML: The XML provided was not well-formed or did not validate against our published schema. Check the service documentation and try again.\n\tstatus code: 400, request id: 15B3AB246C59DB76, host id: ",
  "name": "aws-sdk-go",
  "status": "FAIL"
}

Executed 0 out of 14 tests successfully.
```
<a name="fb1ec12d-9851-473b-82d7-95dbbd3d374d"></a>
### 7960-71cf850/mint-compression-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.60:30115
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 07e05d78db38:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... FAILED in 0 seconds
{
  "alert": "",
  "args": {
    "bucketName": "aws-sdk-go-test-1xmevouehal0hs",
    "objectName1": "object1.csv",
    "objectName2": "object2.csv"
  },
  "duration": 24,
  "error": "MalformedXML: The XML provided was not well-formed or did not validate against our published schema. Check the service documentation and try again.\n\tstatus code: 400, request id: 15B3AB23CE0686E7, host id: ",
  "function": "testSelectObject",
  "message": "AWS SDK Go Select object failed for unicode separator MalformedXML: The XML provided was not well-formed or did not validate against our published schema. Check the service documentation and try again.\n\tstatus code: 400, request id: 15B3AB23CE0686E7, host id: ",
  "name": "aws-sdk-go",
  "status": "FAIL"
}

Executed 0 out of 14 tests successfully.
```
<a name="4754a048-4166-43ca-a540-f7c2f0885207"></a>
### 7960-71cf850/mint-dist-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.51:32750
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 0666d0c2bdd5:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... FAILED in 0 seconds
{
  "alert": "",
  "args": {
    "bucketName": "aws-sdk-go-test-6arktdb1eel2iu",
    "objectName1": "object1.csv",
    "objectName2": "object2.csv"
  },
  "duration": 55,
  "error": "MalformedXML: The XML provided was not well-formed or did not validate against our published schema. Check the service documentation and try again.\n\tstatus code: 400, request id: 15B3AB23F6D86C8A, host id: ",
  "function": "testSelectObject",
  "message": "AWS SDK Go Select object failed for unicode separator MalformedXML: The XML provided was not well-formed or did not validate against our published schema. Check the service documentation and try again.\n\tstatus code: 400, request id: 15B3AB23F6D86C8A, host id: ",
  "name": "aws-sdk-go",
  "status": "FAIL"
}

Executed 0 out of 14 tests successfully.
```
<a name="c1c1e726-8bab-4ff0-93c9-11872545cfc4"></a>
### 7960-71cf850/mint-fs.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.52:31320
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp dc5740f3ce59:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... FAILED in 0 seconds
{
  "alert": "",
  "args": {
    "bucketName": "aws-sdk-go-test-rfo6qzrv1q39yk",
    "objectName1": "object1.csv",
    "objectName2": "object2.csv"
  },
  "duration": 13,
  "error": "MalformedXML: The XML provided was not well-formed or did not validate against our published schema. Check the service documentation and try again.\n\tstatus code: 400, request id: 15B3AB23B3C14D3F, host id: ",
  "function": "testSelectObject",
  "message": "AWS SDK Go Select object failed for unicode separator MalformedXML: The XML provided was not well-formed or did not validate against our published schema. Check the service documentation and try again.\n\tstatus code: 400, request id: 15B3AB23B3C14D3F, host id: ",
  "name": "aws-sdk-go",
  "status": "FAIL"
}

Executed 0 out of 14 tests successfully.
```
<a name="c7a96eb0-5a48-4c9d-b6fb-e87c062c39b6"></a>
### 7960-71cf850/mint-compression-fs.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.51:31792
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp fa2b94d4365d:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... FAILED in 0 seconds
{
  "alert": "",
  "args": {
    "bucketName": "aws-sdk-go-test-mzrhaqgcw33p9i",
    "objectName1": "object1.csv",
    "objectName2": "object2.csv"
  },
  "duration": 14,
  "error": "MalformedXML: The XML provided was not well-formed or did not validate against our published schema. Check the service documentation and try again.\n\tstatus code: 400, request id: 15B3AB23AEBCB4AA, host id: ",
  "function": "testSelectObject",
  "message": "AWS SDK Go Select object failed for unicode separator MalformedXML: The XML provided was not well-formed or did not validate against our published schema. Check the service documentation and try again.\n\tstatus code: 400, request id: 15B3AB23AEBCB4AA, host id: ",
  "name": "aws-sdk-go",
  "status": "FAIL"
}

Executed 0 out of 14 tests successfully.
```

**Comment by minio-ops** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-xl.sh | :heavy_check_mark: |
| mint-compression-dist-xl.sh | :heavy_check_mark: |
| mint-compression-fs.sh | :heavy_check_mark: |
| mint-worm.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-compression-xl.sh | :x: [more...](#4257c1c3-4da6-46f1-93d8-819544e97c24) |
| mint-large-bucket.sh | :x: [more...](#e399558b-c477-42a5-ab95-0bdc2770b520) |
| mint-dist-xl.sh | :x: [more...](#ccd76de8-b940-4f01-bb12-f4216e62f9de) |
| mint-gateway-nas.sh | :x: [more...](#5a31ba37-023d-4628-88cd-763b8b17cb85) |
<a name="4257c1c3-4da6-46f1-93d8-819544e97c24"></a>
### 7960-1538bdf/mint-compression-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.54:30150
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp aa42c0ab8737:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 0 seconds
(2/14) Running aws-sdk-java tests ... done in 1 seconds
(3/14) Running aws-sdk-php tests ... done in 41 seconds
(4/14) Running aws-sdk-ruby tests ... done in 1 seconds
(5/14) Running awscli tests ... FAILED in 1 minutes and 44 seconds
{"name": "awscli", "duration": 62860, "function": "aws --endpoint-url http://72.28.97.54:30150 s3 sync /mint/data s3://awscli-mint-test-bucket-12499/\n", "status": "FAIL", "error": "upload: ../../../data/datafile-0-b to s3://awscli-mint-test-bucket-12499/datafile-0-bCompleted 0 Bytes/~157.2 MiB (0 Bytes/s) with ~11 file(s) remaining (calculating...)
Completed 1 Byte/233.2 MiB (17 Bytes/s) with 14 file(s) remaining                   
upload: ../../../data/datafile-1-b to s3://awscli-mint-test-bucket-12499/datafile-1-bCompleted 1 Byte/233.2 MiB (17 Bytes/s) with 13 file(s) remaining
Completed 1.0 KiB/233.2 MiB (16.1 KiB/s) with 13 file(s) remaining
upload: ../../../data/datafile-1-kB to s3://awscli-mint-test-bucket-12499/datafile-1-kBCompleted 1.0 KiB/233.2 MiB (16.1 KiB/s) with 12 file(s) remaining
Completed 257.0 KiB/233.2 MiB (3.7 MiB/s) with 12 file(s) remaining
Completed 513.0 KiB/233.2 MiB (7.3 MiB/s) with 12 file(s) remaining
Completed 769.0 KiB/233.2 MiB (10.2 MiB/s) with 12 file(s) remaining
Completed 1.0 MiB/233.2 MiB (13.5 MiB/s) with 12 file(s) remaining  
Completed 1.3 MiB/233.2 MiB (16.5 MiB/s) with 12 file(s) remaining  
Completed 1.5 MiB/233.2 MiB (19.7 MiB/s) with 12 file(s) remaining  
Completed 1.5 MiB/233.2 MiB (19.2 MiB/s) with 12 file(s) remaining  
upload: ../../../data/datafile-10-kB to s3://awscli-mint-test-bucket-12499/datafile-10-kBCompleted 1.5 MiB/233.2 MiB (19.2 MiB/s) with 11 file(s) remaining
Completed 1.5 MiB/233.2 MiB (17.7 MiB/s) with 11 file(s) remaining
upload: ../../../data/datafile-33-kB to s3://awscli-mint-test-bucket-12499/datafile-33-kBCompleted 1.5 MiB/233.2 MiB (17.7 MiB/s) with 10 file(s) remaining
Completed 1.8 MiB/233.2 MiB (18.9 MiB/s) with 10 file(s) remaining
Completed 1.9 MiB/233.2 MiB (19.2 MiB/s) with 10 file(s) remaining
upload: ../../../data/datafile-100-kB to s3://awscli-mint-test-bucket-12499/datafile-100-kBCompleted 1.9 MiB/233.2 MiB (19.2 MiB/s) with 9 file(s) remaining
Completed 2.1 MiB/233.2 MiB (21.3 MiB/s) with 9 file(s) remaining
Completed 2.4 MiB/233.2 MiB (23.3 MiB/s) with 9 file(s) remaining
Completed 2.6 MiB/233.2 MiB (24.2 MiB/s) with 9 file(s) remaining
Completed 2.9 MiB/233.2 MiB (26.4 MiB/s) with 9 file(s) remaining
Completed 3.1 MiB/233.2 MiB (28.4 MiB/s) with 9 file(s) remaining
Completed 3.4 MiB/233.2 MiB (30.0 MiB/s) with 9 file(s) remaining
Completed 3.6 MiB/233.2 MiB (30.4 MiB/s) with 9 file(s) remaining
Completed 3.9 MiB/233.2 MiB (30.3 MiB/s) with 9 file(s) remaining
Completed 4.1 MiB/233.2 MiB (31.9 MiB/s) with 9 file(s) remaining
Completed 4.4 MiB/233.2 MiB (33.2 MiB/s) with 9 file(s) remaining
Completed 4.6 MiB/233.2 MiB (34.9 MiB/s) with 9 file(s) remaining
Completed 4.9 MiB/233.2 MiB (34.1 MiB/s) with 9 file(s) remaining
Completed 5.1 MiB/233.2 MiB (33.4 MiB/s) with 9 file(s) remaining
Completed 5.4 MiB/233.2 MiB (34.7 MiB/s) with 9 file(s) remaining
Completed 5.6 MiB/233.2 MiB (36.3 MiB/s) with 9 file(s) remaining
Completed 5.9 MiB/233.2 MiB (37.8 MiB/s) with 9 file(s) remaining
Completed 6.1 MiB/233.2 MiB (38.5 MiB/s) with 9 file(s) remaining
Completed 6.4 MiB/233.2 MiB (40.1 MiB/s) with 9 file(s) remaining
Completed 6.6 MiB/233.2 MiB (41.4 MiB/s) with 9 file(s) remaining
Completed 6.9 MiB/233.2 MiB (42.0 MiB/s) with 9 file(s) remaining
Completed 7.1 MiB/233.2 MiB (41.4 MiB/s) with 9 file(s) remaining
Completed 7.4 MiB/233.2 MiB (42.7 MiB/s) with 9 file(s) remaining
Completed 7.6 MiB/233.2 MiB (43.7 MiB/s) with 9 file(s) remaining
Completed 7.9 MiB/233.2 MiB (44.9 MiB/s) with 9 file(s) remaining
Completed 8.1 MiB/233.2 MiB (46.1 MiB/s) with 9 file(s) remaining
Completed 8.4 MiB/233.2 MiB (43.5 MiB/s) with 9 file(s) remaining
Completed 8.6 MiB/233.2 MiB (44.5 MiB/s) with 9 file(s) remaining
Completed 8.9 MiB/233.2 MiB (42.6 MiB/s) with 9 file(s) remaining
Completed 9.1 MiB/233.2 MiB (42.2 MiB/s) with 9 file(s) remaining
Completed 9.4 MiB/233.2 MiB (41.7 MiB/s) with 9 file(s) remaining
Completed 9.6 MiB/233.2 MiB (41.9 MiB/s) with 9 file(s) remaining
Completed 9.9 MiB/233.2 MiB (40.4 MiB/s) with 9 file(s) remaining
Completed 9.9 MiB/233.2 MiB (37.1 MiB/s) with 9 file(s) remaining
upload: ../../../data/datafile-1.03-MB to s3://awscli-mint-test-bucket-12499/datafile-1.03-MBCompleted 9.9 MiB/233.2 MiB (37.1 MiB/s) with 8 file(s) remaining
Completed 10.2 MiB/233.2 MiB (37.9 MiB/s) with 8 file(s) remaining
Completed 10.4 MiB/233.2 MiB (37.6 MiB/s) with 8 file(s) remaining
Completed 10.7 MiB/233.2 MiB (38.1 MiB/s) with 8 file(s) remaining
Completed 10.9 MiB/233.2 MiB (36.8 MiB/s) with 8 file(s) remaining
Completed 11.2 MiB/233.2 MiB (37.7 MiB/s) with 8 file(s) remaining
Completed 11.4 MiB/233.2 MiB (38.4 MiB/s) with 8 file(s) remaining
Completed 11.7 MiB/233.2 MiB (38.8 MiB/s) with 8 file(s) remaining
Completed 11.9 MiB/233.2 MiB (38.9 MiB/s) with 8 file(s) remaining
Completed 12.2 MiB/233.2 MiB (37.9 MiB/s) with 8 file(s) remaining
Completed 12.4 MiB/233.2 MiB (38.6 MiB/s) with 8 file(s) remaining
Completed 12.7 MiB/233.2 MiB (37.5 MiB/s) with 8 file(s) remaining
Completed 12.9 MiB/233.2 MiB (36.5 MiB/s) with 8 file(s) remaining
Completed 13.2 MiB/233.2 MiB (36.8 MiB/s) with 8 file(s) remaining
Completed 13.4 MiB/233.2 MiB (37.3 MiB/s) with 8 file(s) remaining
Completed 13.7 MiB/233.2 MiB (36.5 MiB/s) with 8 file(s) remaining
Completed 13.9 MiB/233.2 MiB (36.6 MiB/s) with 8 file(s) remaining
Completed 14.2 MiB/233.2 MiB (36.7 MiB/s) with 8 file(s) remaining
Completed 14.4 MiB/233.2 MiB (34.8 MiB/s) with 8 file(s) remaining
Completed 14.7 MiB/233.2 MiB (35.4 MiB/s) with 8 file(s) remaining
Completed 14.9 MiB/233.2 MiB (35.6 MiB/s) with 8 file(s) remaining
Completed 15.2 MiB/233.2 MiB (34.9 MiB/s) with 8 file(s) remaining
Completed 15.4 MiB/233.2 MiB (35.2 MiB/s) with 8 file(s) remaining
Completed 15.7 MiB/233.2 MiB (34.5 MiB/s) with 8 file(s) remaining
Completed 15.9 MiB/233.2 MiB (34.7 MiB/s) with 8 file(s) remaining
Completed 16.2 MiB/233.2 MiB (34.5 MiB/s) with 8 file(s) remaining
Completed 16.4 MiB/233.2 MiB (34.8 MiB/s) with 8 file(s) remaining
Completed 16.7 MiB/233.2 MiB (35.3 MiB/s) with 8 file(s) remaining
Completed 16.9 MiB/233.2 MiB (34.1 MiB/s) with 8 file(s) remaining
Completed 17.2 MiB/233.2 MiB (34.0 MiB/s) with 8 file(s) remaining
Completed 17.4 MiB/233.2 MiB (34.4 MiB/s) with 8 file(s) remaining
Completed 17.7 MiB/233.2 MiB (34.0 MiB/s) with 8 file(s) remaining
Completed 17.9 MiB/233.2 MiB (34.1 MiB/s) with 8 file(s) remaining
Completed 18.2 MiB/233.2 MiB (33.6 MiB/s) with 8 file(s) remaining
Completed 18.4 MiB/233.2 MiB (33.0 MiB/s) with 8 file(s) remaining
Completed 18.7 MiB/233.2 MiB (32.9 MiB/s) with 8 file(s) remaining
Completed 18.9 MiB/233.2 MiB (33.3 MiB/s) with 8 file(s) remaining
Completed 19.2 MiB/233.2 MiB (33.0 MiB/s) with 8 file(s) remaining
Completed 19.4 MiB/233.2 MiB (33.4 MiB/s) with 8 file(s) remaining
Completed 19.7 MiB/233.2 MiB (33.7 MiB/s) with 8 file(s) remaining
Completed 19.9 MiB/233.2 MiB (34.1 MiB/s) with 8 file(s) remaining
Completed 20.2 MiB/233.2 MiB (32.5 MiB/s) with 8 file(s) remaining
Completed 20.4 MiB/233.2 MiB (32.3 MiB/s) with 8 file(s) remaining
Completed 20.7 MiB/233.2 MiB (32.5 MiB/s) with 8 file(s) remaining
Completed 20.9 MiB/233.2 MiB (32.5 MiB/s) with 8 file(s) remaining
Completed 21.2 MiB/233.2 MiB (32.6 MiB/s) with 8 file(s) remaining
Completed 21.4 MiB/233.2 MiB (32.3 MiB/s) with 8 file(s) remaining
Completed 21.7 MiB/233.2 MiB (32.2 MiB/s) with 8 file(s) remaining
Completed 21.9 MiB/233.2 MiB (32.2 MiB/s) with 8 file(s) remaining
Completed 22.2 MiB/233.2 MiB (32.2 MiB/s) with 8 file(s) remaining
Completed 22.4 MiB/233.2 MiB (32.5 MiB/s) with 8 file(s) remaining
Completed 22.7 MiB/233.2 MiB (32.8 MiB/s) with 8 file(s) remaining
Completed 22.9 MiB/233.2 MiB (33.1 MiB/s) with 8 file(s) remaining
Completed 23.2 MiB/233.2 MiB (32.1 MiB/s) with 8 file(s) remaining
Completed 23.4 MiB/233.2 MiB (31.9 MiB/s) with 8 file(s) remaining
Completed 23.7 MiB/233.2 MiB (32.2 MiB/s) with 8 file(s) remaining
Completed 23.9 MiB/233.2 MiB (32.2 MiB/s) with 8 file(s) remaining
Completed 24.2 MiB/233.2 MiB (32.5 MiB/s) with 8 file(s) remaining
Completed 24.4 MiB/233.2 MiB (31.9 MiB/s) with 8 file(s) remaining
Completed 24.7 MiB/233.2 MiB (32.0 MiB/s) with 8 file(s) remaining
Completed 24.9 MiB/233.2 MiB (32.1 MiB/s) with 8 file(s) remaining
Completed 25.2 MiB/233.2 MiB (31.8 MiB/s) with 8 file(s) remaining
Completed 25.4 MiB/233.2 MiB (32.1 MiB/s) with 8 file(s) remaining
Completed 25.7 MiB/233.2 MiB (32.3 MiB/s) with 8 file(s) remaining
Completed 25.9 MiB/233.2 MiB (32.0 MiB/s) with 8 file(s) remaining
Completed 26.2 MiB/233.2 MiB (31.9 MiB/s) with 8 file(s) remaining
Completed 26.4 MiB/233.2 MiB (32.1 MiB/s) with 8 file(s) remaining
Completed 26.7 MiB/233.2 MiB (31.7 MiB/s) with 8 file(s) remaining
Completed 26.9 MiB/233.2 MiB (31.4 MiB/s) with 8 file(s) remaining
Completed 27.2 MiB/233.2 MiB (31.1 MiB/s) with 8 file(s) remaining
Completed 27.4 MiB/233.2 MiB (30.9 MiB/s) with 8 file(s) remaining
Completed 27.7 MiB/233.2 MiB (31.2 MiB/s) with 8 file(s) remaining
Completed 27.9 MiB/233.2 MiB (30.8 MiB/s) with 8 file(s) remaining
Completed 28.2 MiB/233.2 MiB (30.7 MiB/s) with 8 file(s) remaining
Completed 28.4 MiB/233.2 MiB (30.4 MiB/s) with 8 file(s) remaining
Completed 28.7 MiB/233.2 MiB (30.7 MiB/s) with 8 file(s) remaining
Completed 28.9 MiB/233.2 MiB (30.8 MiB/s) with 8 file(s) remaining
Completed 29.2 MiB/233.2 MiB (30.6 MiB/s) with 8 file(s) remaining
Completed 29.4 MiB/233.2 MiB (30.8 MiB/s) with 8 file(s) remaining
Completed 29.7 MiB/233.2 MiB (30.9 MiB/s) with 8 file(s) remaining
Completed 29.9 MiB/233.2 MiB (30.2 MiB/s) with 8 file(s) remaining
Completed 30.2 MiB/233.2 MiB (29.9 MiB/s) with 8 file(s) remaining
Completed 30.4 MiB/233.2 MiB (29.5 MiB/s) with 8 file(s) remaining
Completed 30.7 MiB/233.2 MiB (29.6 MiB/s) with 8 file(s) remaining
Completed 30.9 MiB/233.2 MiB (29.6 MiB/s) with 8 file(s) remaining
Completed 31.2 MiB/233.2 MiB (29.2 MiB/s) with 8 file(s) remaining
Completed 31.4 MiB/233.2 MiB (29.4 MiB/s) with 8 file(s) remaining
Completed 31.7 MiB/233.2 MiB (29.5 MiB/s) with 8 file(s) remaining
Completed 31.9 MiB/233.2 MiB (29.1 MiB/s) with 8 file(s) remaining
Completed 32.2 MiB/233.2 MiB (29.1 MiB/s) with 8 file(s) remaining
Completed 32.4 MiB/233.2 MiB (28.9 MiB/s) with 8 file(s) remaining
Completed 32.7 MiB/233.2 MiB (28.5 MiB/s) with 8 file(s) remaining
Completed 32.9 MiB/233.2 MiB (28.7 MiB/s) with 8 file(s) remaining
Completed 33.2 MiB/233.2 MiB (28.8 MiB/s) with 8 file(s) remaining
Completed 33.4 MiB/233.2 MiB (28.6 MiB/s) with 8 file(s) remaining
Completed 33.7 MiB/233.2 MiB (28.8 MiB/s) with 8 file(s) remaining
Completed 33.9 MiB/233.2 MiB (29.0 MiB/s) with 8 file(s) remaining
Completed 34.2 MiB/233.2 MiB (29.1 MiB/s) with 8 file(s) remaining
Completed 34.4 MiB/233.2 MiB (29.1 MiB/s) with 8 file(s) remaining
Completed 34.7 MiB/233.2 MiB (29.0 MiB/s) with 8 file(s) remaining
Completed 34.9 MiB/233.2 MiB (29.0 MiB/s) with 8 file(s) remaining
Completed 35.2 MiB/233.2 MiB (29.2 MiB/s) with 8 file(s) remaining
Completed 35.4 MiB/233.2 MiB (29.1 MiB/s) with 8 file(s) remaining
Completed 35.7 MiB/233.2 MiB (29.1 MiB/s) with 8 file(s) remaining
Completed 35.9 MiB/233.2 MiB (29.1 MiB/s) with 8 file(s) remaining
Completed 36.2 MiB/233.2 MiB (29.0 MiB/s) with 8 file(s) remaining
Completed 36.4 MiB/233.2 MiB (28.9 MiB/s) with 8 file(s) remaining
Completed 36.7 MiB/233.2 MiB (29.1 MiB/s) with 8 file(s) remaining
Completed 36.9 MiB/233.2 MiB (28.9 MiB/s) with 8 file(s) remaining
Completed 37.2 MiB/233.2 MiB (28.6 MiB/s) with 8 file(s) remaining
Completed 37.4 MiB/233.2 MiB (28.8 MiB/s) with 8 file(s) remaining
Completed 37.7 MiB/233.2 MiB (28.4 MiB/s) with 8 file(s) remaining
Completed 37.9 MiB/233.2 MiB (28.3 MiB/s) with 8 file(s) remaining
Completed 38.2 MiB/233.2 MiB (28.1 MiB/s) with 8 file(s) remaining
Completed 38.4 MiB/233.2 MiB (28.0 MiB/s) with 8 file(s) remaining
Completed 38.4 MiB/233.2 MiB (27.8 MiB/s) with 8 file(s) remaining
upload: ../../../data/datafile-5243880-b to s3://awscli-mint-test-bucket-12499/datafile-5243880-bCompleted 38.4 MiB/233.2 MiB (27.8 MiB/s) with 7 file(s) remaining
Completed 38.7 MiB/233.2 MiB (27.8 MiB/s) with 7 file(s) remaining
Completed 38.9 MiB/233.2 MiB (27.2 MiB/s) with 7 file(s) remaining
Completed 39.2 MiB/233.2 MiB (27.3 MiB/s) with 7 file(s) remaining
Completed 39.4 MiB/233.2 MiB (27.4 MiB/s) with 7 file(s) remaining
Completed 39.7 MiB/233.2 MiB (27.5 MiB/s) with 7 file(s) remaining
Completed 39.9 MiB/233.2 MiB (27.0 MiB/s) with 7 file(s) remaining
Completed 40.2 MiB/233.2 MiB (26.9 MiB/s) with 7 file(s) remaining
Completed 40.4 MiB/233.2 MiB (26.8 MiB/s) with 7 file(s) remaining
Completed 40.7 MiB/233.2 MiB (26.9 MiB/s) with 7 file(s) remaining
Completed 40.9 MiB/233.2 MiB (26.7 MiB/s) with 7 file(s) remaining
Completed 41.2 MiB/233.2 MiB (26.8 MiB/s) with 7 file(s) remaining
Completed 41.4 MiB/233.2 MiB (26.7 MiB/s) with 7 file(s) remaining
Completed 41.7 MiB/233.2 MiB (26.6 MiB/s) with 7 file(s) remaining
Completed 41.9 MiB/233.2 MiB (26.6 MiB/s) with 7 file(s) remaining
Completed 42.2 MiB/233.2 MiB (26.5 MiB/s) with 7 file(s) remaining
Completed 42.4 MiB/233.2 MiB (26.5 MiB/s) with 7 file(s) remaining
Completed 42.7 MiB/233.2 MiB (26.4 MiB/s) with 7 file(s) remaining
Completed 42.9 MiB/233.2 MiB (26.4 MiB/s) with 7 file(s) remaining
Completed 43.2 MiB/233.2 MiB (26.4 MiB/s) with 7 file(s) remaining
Completed 43.4 MiB/233.2 MiB (26.4 MiB/s) with 7 file(s) remaining
Completed 43.7 MiB/233.2 MiB (26.3 MiB/s) with 7 file(s) remaining
Completed 43.9 MiB/233.2 MiB (26.0 MiB/s) with 7 file(s) remaining
Completed 44.2 MiB/233.2 MiB (25.9 MiB/s) with 7 file(s) remaining
Completed 44.4 MiB/233.2 MiB (25.5 MiB/s) with 7 file(s) remaining
Completed 44.7 MiB/233.2 MiB (25.2 MiB/s) with 7 file(s) remaining
Completed 44.9 MiB/233.2 MiB (25.1 MiB/s) with 7 file(s) remaining
Completed 45.2 MiB/233.2 MiB (25.2 MiB/s) with 7 file(s) remaining
Completed 45.4 MiB/233.2 MiB (24.8 MiB/s) with 7 file(s) remaining
Completed 45.7 MiB/233.2 MiB (24.8 MiB/s) with 7 file(s) remaining
Completed 45.9 MiB/233.2 MiB (24.6 MiB/s) with 7 file(s) remaining
Completed 46.2 MiB/233.2 MiB (24.5 MiB/s) with 7 file(s) remaining
Completed 46.4 MiB/233.2 MiB (24.6 MiB/s) with 7 file(s) remaining
Completed 46.7 MiB/233.2 MiB (24.6 MiB/s) with 7 file(s) remaining
Completed 46.9 MiB/233.2 MiB (24.3 MiB/s) with 7 file(s) remaining
Completed 47.2 MiB/233.2 MiB (24.2 MiB/s) with 7 file(s) remaining
upload: ../../../data/datafile-6-MB to s3://awscli-mint-test-bucket-12499/datafile-6-MBCompleted 47.2 MiB/233.2 MiB (24.2 MiB/s) with 6 file(s) remaining
Completed 47.4 MiB/233.2 MiB (24.0 MiB/s) with 6 file(s) remaining
Completed 47.7 MiB/233.2 MiB (24.0 MiB/s) with 6 file(s) remaining
Completed 47.9 MiB/233.2 MiB (24.0 MiB/s) with 6 file(s) remaining
Completed 48.2 MiB/233.2 MiB (24.0 MiB/s) with 6 file(s) remaining
Completed 48.4 MiB/233.2 MiB (24.1 MiB/s) with 6 file(s) remaining
Completed 48.7 MiB/233.2 MiB (23.9 MiB/s) with 6 file(s) remaining
Completed 48.9 MiB/233.2 MiB (24.0 MiB/s) with 6 file(s) remaining
Completed 49.2 MiB/233.2 MiB (24.1 MiB/s) with 6 file(s) remaining
Completed 49.4 MiB/233.2 MiB (24.2 MiB/s) with 6 file(s) remaining
Completed 49.7 MiB/233.2 MiB (24.1 MiB/s) with 6 file(s) remaining
Completed 49.9 MiB/233.2 MiB (24.2 MiB/s) with 6 file(s) remaining
Completed 50.2 MiB/233.2 MiB (24.1 MiB/s) with 6 file(s) remaining
Completed 50.4 MiB/233.2 MiB (23.7 MiB/s) with 6 file(s) remaining
Completed 50.7 MiB/233.2 MiB (23.8 MiB/s) with 6 file(s) remaining
Completed 50.9 MiB/233.2 MiB (23.9 MiB/s) with 6 file(s) remaining
Completed 51.2 MiB/233.2 MiB (23.6 MiB/s) with 6 file(s) remaining
Completed 51.4 MiB/233.2 MiB (23.6 MiB/s) with 6 file(s) remaining
Completed 51.7 MiB/233.2 MiB (23.2 MiB/s) with 6 file(s) remaining
Completed 51.9 MiB/233.2 MiB (23.3 MiB/s) with 6 file(s) remaining
Completed 52.2 MiB/233.2 MiB (23.3 MiB/s) with 6 file(s) remaining
Completed 52.4 MiB/233.2 MiB (23.3 MiB/s) with 6 file(s) remaining
Completed 52.7 MiB/233.2 MiB (23.1 MiB/s) with 6 file(s) remaining
Completed 52.9 MiB/233.2 MiB (23.1 MiB/s) with 6 file(s) remaining
Completed 53.2 MiB/233.2 MiB (23.2 MiB/s) with 6 file(s) remaining
Completed 53.4 MiB/233.2 MiB (23.0 MiB/s) with 6 file(s) remaining
upload: ../../../data/datafile-5-MB to s3://awscli-mint-test-bucket-12499/datafile-5-MBCompleted 53.4 MiB/233.2 MiB (23.0 MiB/s) with 5 file(s) remaining
Completed 53.7 MiB/233.2 MiB (23.1 MiB/s) with 5 file(s) remaining
Completed 53.9 MiB/233.2 MiB (23.1 MiB/s) with 5 file(s) remaining
Completed 54.2 MiB/233.2 MiB (22.8 MiB/s) with 5 file(s) remaining
Completed 54.4 MiB/233.2 MiB (22.8 MiB/s) with 5 file(s) remaining
Completed 54.7 MiB/233.2 MiB (22.9 MiB/s) with 5 file(s) remaining
Completed 54.9 MiB/233.2 MiB (22.9 MiB/s) with 5 file(s) remaining
Completed 55.2 MiB/233.2 MiB (22.8 MiB/s) with 5 file(s) remaining
Completed 55.4 MiB/233.2 MiB (22.7 MiB/s) with 5 file(s) remaining
Completed 55.7 MiB/233.2 MiB (22.7 MiB/s) with 5 file(s) remaining
Completed 55.9 MiB/233.2 MiB (22.6 MiB/s) with 5 file(s) remaining
Completed 56.2 MiB/233.2 MiB (22.7 MiB/s) with 5 file(s) remaining
Completed 56.4 MiB/233.2 MiB (22.7 MiB/s) with 5 file(s) remaining
Completed 56.7 MiB/233.2 MiB (22.5 MiB/s) with 5 file(s) remaining
Completed 56.9 MiB/233.2 MiB (22.4 MiB/s) with 5 file(s) remaining
Completed 57.2 MiB/233.2 MiB (22.3 MiB/s) with 5 file(s) remaining
Completed 57.4 MiB/233.2 MiB (22.1 MiB/s) with 5 file(s) remaining
Completed 57.7 MiB/233.2 MiB (22.1 MiB/s) with 5 file(s) remaining
Completed 57.9 MiB/233.2 MiB (21.9 MiB/s) with 5 file(s) remaining
Completed 58.2 MiB/233.2 MiB (21.9 MiB/s) with 5 file(s) remaining
Completed 58.4 MiB/233.2 MiB (21.8 MiB/s) with 5 file(s) remaining
Completed 58.7 MiB/233.2 MiB (21.7 MiB/s) with 5 file(s) remaining
Completed 58.9 MiB/233.2 MiB (21.8 MiB/s) with 5 file(s) remaining
Completed 59.2 MiB/233.2 MiB (21.7 MiB/s) with 5 file(s) remaining
Completed 59.4 MiB/233.2 MiB (21.6 MiB/s) with 5 file(s) remaining
upload: ../../../data/datafile-11-MB to s3://awscli-mint-test-bucket-12499/datafile-11-MBCompleted 59.4 MiB/233.2 MiB (21.6 MiB/s) with 4 file(s) remaining
Completed 59.7 MiB/233.2 MiB (21.6 MiB/s) with 4 file(s) remaining
Completed 59.9 MiB/233.2 MiB (21.4 MiB/s) with 4 file(s) remaining
Completed 60.2 MiB/233.2 MiB (21.3 MiB/s) with 4 file(s) remaining
Completed 60.4 MiB/233.2 MiB (21.4 MiB/s) with 4 file(s) remaining
Completed 60.7 MiB/233.2 MiB (21.4 MiB/s) with 4 file(s) remaining
Completed 60.9 MiB/233.2 MiB (21.5 MiB/s) with 4 file(s) remaining
Completed 61.2 MiB/233.2 MiB (21.6 MiB/s) with 4 file(s) remaining
Completed 61.4 MiB/233.2 MiB (21.6 MiB/s) with 4 file(s) remaining
Completed 61.7 MiB/233.2 MiB (21.6 MiB/s) with 4 file(s) remaining
Completed 61.9 MiB/233.2 MiB (21.7 MiB/s) with 4 file(s) remaining
Completed 62.2 MiB/233.2 MiB (21.7 MiB/s) with 4 file(s) remaining
Completed 62.4 MiB/233.2 MiB (21.7 MiB/s) with 4 file(s) remaining
Completed 62.7 MiB/233.2 MiB (21.7 MiB/s) with 4 file(s) remaining
Completed 62.9 MiB/233.2 MiB (21.7 MiB/s) with 4 file(s) remaining
Completed 63.2 MiB/233.2 MiB (21.7 MiB/s) with 4 file(s) remaining
Completed 63.4 MiB/233.2 MiB (21.5 MiB/s) with 4 file(s) remaining
Completed 63.7 MiB/233.2 MiB (21.5 MiB/s) with 4 file(s) remaining
Completed 63.9 MiB/233.2 MiB (21.5 MiB/s) with 4 file(s) remaining
Completed 64.2 MiB/233.2 MiB (21.4 MiB/s) with 4 file(s) remaining
Completed 64.4 MiB/233.2 MiB (21.4 MiB/s) with 4 file(s) remaining
Completed 64.7 MiB/233.2 MiB (21.4 MiB/s) with 4 file(s) remaining
Completed 64.9 MiB/233.2 MiB (21.3 MiB/s) with 4 file(s) remaining
Completed 65.2 MiB/233.2 MiB (21.3 MiB/s) with 4 file(s) remaining
Completed 65.4 MiB/233.2 MiB (21.4 MiB/s) with 4 file(s) remaining
Completed 65.7 MiB/233.2 MiB (21.4 MiB/s) with 4 file(s) remaining
Completed 65.9 MiB/233.2 MiB (21.5 MiB/s) with 4 file(s) remaining
Completed 66.2 MiB/233.2 MiB (21.5 MiB/s) with 4 file(s) remaining
Completed 66.4 MiB/233.2 MiB (21.5 MiB/s) with 4 file(s) remaining
Completed 66.7 MiB/233.2 MiB (21.6 MiB/s) with 4 file(s) remaining
Completed 66.9 MiB/233.2 MiB (21.6 MiB/s) with 4 file(s) remaining
Completed 67.2 MiB/233.2 MiB (21.5 MiB/s) with 4 file(s) remaining
Completed 67.4 MiB/233.2 MiB (21.6 MiB/s) with 4 file(s) remaining
Completed 67.7 MiB/233.2 MiB (21.5 MiB/s) with 4 file(s) remaining
Completed 67.9 MiB/233.2 MiB (21.6 MiB/s) with 4 file(s) remaining
Completed 68.2 MiB/233.2 MiB (21.5 MiB/s) with 4 file(s) remaining
Completed 68.4 MiB/233.2 MiB (21.4 MiB/s) with 4 file(s) remaining
Completed 68.7 MiB/233.2 MiB (21.5 MiB/s) with 4 file(s) remaining
Completed 68.9 MiB/233.2 MiB (21.5 MiB/s) with 4 file(s) remaining
Completed 69.2 MiB/233.2 MiB (21.6 MiB/s) with 4 file(s) remaining
Completed 69.4 MiB/233.2 MiB (21.6 MiB/s) with 4 file(s) remaining
Completed 69.7 MiB/233.2 MiB (21.5 MiB/s) with 4 file(s) remaining
Completed 69.9 MiB/233.2 MiB (21.5 MiB/s) with 4 file(s) remaining
Completed 70.2 MiB/233.2 MiB (21.6 MiB/s) with 4 file(s) remaining
Completed 70.4 MiB/233.2 MiB (21.6 MiB/s) with 4 file(s) remaining
Completed 70.7 MiB/233.2 MiB (21.4 MiB/s) with 4 file(s) remaining
Completed 70.9 MiB/233.2 MiB (21.5 MiB/s) with 4 file(s) remaining
Completed 71.2 MiB/233.2 MiB (21.5 MiB/s) with 4 file(s) remaining
Completed 71.4 MiB/233.2 MiB (21.6 MiB/s) with 4 file(s) remaining
Completed 71.7 MiB/233.2 MiB (21.5 MiB/s) with 4 file(s) remaining
Completed 71.9 MiB/233.2 MiB (21.5 MiB/s) with 4 file(s) remaining
Completed 72.2 MiB/233.2 MiB (21.6 MiB/s) with 4 file(s) remaining
Completed 72.4 MiB/233.2 MiB (21.6 MiB/s) with 4 file(s) remaining
Completed 72.7 MiB/233.2 MiB (21.5 MiB/s) with 4 file(s) remaining
Completed 72.9 MiB/233.2 MiB (21.5 MiB/s) with 4 file(s) remaining
Completed 73.2 MiB/233.2 MiB (21.5 MiB/s) with 4 file(s) remaining
Completed 73.4 MiB/233.2 MiB (21.6 MiB/s) with 4 file(s) remaining
Completed 73.7 MiB/233.2 MiB (21.7 MiB/s) with 4 file(s) remaining
Completed 73.9 MiB/233.2 MiB (21.7 MiB/s) with 4 file(s) remaining
Completed 74.2 MiB/233.2 MiB (21.6 MiB/s) with 4 file(s) remaining
Completed 74.4 MiB/233.2 MiB (21.6 MiB/s) with 4 file(s) remaining
Completed 74.7 MiB/233.2 MiB (21.6 MiB/s) with 4 file(s) remaining
Completed 74.9 MiB/233.2 MiB (21.5 MiB/s) with 4 file(s) remaining
Completed 75.2 MiB/233.2 MiB (21.6 MiB/s) with 4 file(s) remaining
Completed 75.4 MiB/233.2 MiB (21.5 MiB/s) with 4 file(s) remaining
Completed 75.7 MiB/233.2 MiB (21.6 MiB/s) with 4 file(s) remaining
Completed 75.9 MiB/233.2 MiB (21.6 MiB/s) with 4 file(s) remaining
Completed 76.2 MiB/233.2 MiB (21.6 MiB/s) with 4 file(s) remaining
Completed 76.4 MiB/233.2 MiB (21.5 MiB/s) with 4 file(s) remaining
Completed 76.7 MiB/233.2 MiB (21.6 MiB/s) with 4 file(s) remaining
Completed 76.9 MiB/233.2 MiB (21.6 MiB/s) with 4 file(s) remaining
Completed 77.2 MiB/233.2 MiB (21.4 MiB/s) with 4 file(s) remaining
Completed 77.4 MiB/233.2 MiB (21.4 MiB/s) with 4 file(s) remaining
Completed 77.7 MiB/233.2 MiB (21.5 MiB/s) with 4 file(s) remaining
Completed 77.9 MiB/233.2 MiB (21.4 MiB/s) with 4 file(s) remaining
Completed 78.2 MiB/233.2 MiB (21.4 MiB/s) with 4 file(s) remaining
Completed 78.4 MiB/233.2 MiB (21.5 MiB/s) with 4 file(s) remaining
Completed 78.7 MiB/233.2 MiB (21.4 MiB/s) with 4 file(s) remaining
Completed 78.9 MiB/233.2 MiB (21.5 MiB/s) with 4 file(s) remaining
Completed 79.2 MiB/233.2 MiB (21.4 MiB/s) with 4 file(s) remaining
Completed 79.4 MiB/233.2 MiB (21.4 MiB/s) with 4 file(s) remaining
Completed 79.7 MiB/233.2 MiB (21.4 MiB/s) with 4 file(s) remaining
Completed 79.9 MiB/233.2 MiB (21.4 MiB/s) with 4 file(s) remaining
Completed 80.2 MiB/233.2 MiB (21.4 MiB/s) with 4 file(s) remaining
Completed 80.4 MiB/233.2 MiB (21.5 MiB/s) with 4 file(s) remaining
Completed 80.7 MiB/233.2 MiB (21.5 MiB/s) with 4 file(s) remaining
Completed 80.9 MiB/233.2 MiB (21.4 MiB/s) with 4 file(s) remaining
Completed 81.2 MiB/233.2 MiB (21.4 MiB/s) with 4 file(s) remaining
Completed 81.4 MiB/233.2 MiB (21.4 MiB/s) with 4 file(s) remaining
Completed 81.7 MiB/233.2 MiB (21.5 MiB/s) with 4 file(s) remaining
Completed 81.9 MiB/233.2 MiB (21.4 MiB/s) with 4 file(s) remaining
Completed 82.2 MiB/233.2 MiB (21.3 MiB/s) with 4 file(s) remaining
Completed 82.4 MiB/233.2 MiB (21.3 MiB/s) with 4 file(s) remaining
Completed 82.7 MiB/233.2 MiB (21.3 MiB/s) with 4 file(s) remaining
Completed 82.9 MiB/233.2 MiB (21.3 MiB/s) with 4 file(s) remaining
Completed 83.2 MiB/233.2 MiB (21.2 MiB/s) with 4 file(s) remaining
Completed 83.4 MiB/233.2 MiB (21.3 MiB/s) with 4 file(s) remaining
Completed 83.7 MiB/233.2 MiB (21.2 MiB/s) with 4 file(s) remaining
Completed 83.9 MiB/233.2 MiB (21.2 MiB/s) with 4 file(s) remaining
Completed 84.2 MiB/233.2 MiB (21.2 MiB/s) with 4 file(s) remaining
Completed 84.4 MiB/233.2 MiB (21.2 MiB/s) with 4 file(s) remaining
Completed 84.7 MiB/233.2 MiB (21.2 MiB/s) with 4 file(s) remaining
Completed 84.9 MiB/233.2 MiB (21.2 MiB/s) with 4 file(s) remaining
Completed 85.2 MiB/233.2 MiB (21.0 MiB/s) with 4 file(s) remaining
Completed 85.4 MiB/233.2 MiB (21.1 MiB/s) with 4 file(s) remaining
Completed 85.7 MiB/233.2 MiB (21.1 MiB/s) with 4 file(s) remaining
Completed 85.9 MiB/233.2 MiB (21.1 MiB/s) with 4 file(s) remaining
Completed 86.2 MiB/233.2 MiB (21.1 MiB/s) with 4 file(s) remaining
Completed 86.4 MiB/233.2 MiB (21.1 MiB/s) with 4 file(s) remaining
Completed 86.7 MiB/233.2 MiB (21.1 MiB/s) with 4 file(s) remaining
Completed 86.9 MiB/233.2 MiB (21.1 MiB/s) with 4 file(s) remaining
Completed 87.2 MiB/233.2 MiB (21.1 MiB/s) with 4 file(s) remaining
Completed 87.4 MiB/233.2 MiB (20.9 MiB/s) with 4 file(s) remaining
Completed 87.7 MiB/233.2 MiB (20.9 MiB/s) with 4 file(s) remaining
Completed 87.9 MiB/233.2 MiB (20.9 MiB/s) with 4 file(s) remaining
Completed 88.2 MiB/233.2 MiB (20.9 MiB/s) with 4 file(s) remaining
Completed 88.4 MiB/233.2 MiB (21.0 MiB/s) with 4 file(s) remaining
Completed 88.7 MiB/233.2 MiB (21.0 MiB/s) with 4 file(s) remaining
Completed 88.9 MiB/233.2 MiB (21.0 MiB/s) with 4 file(s) remaining
Completed 89.2 MiB/233.2 MiB (21.0 MiB/s) with 4 file(s) remaining
Completed 89.4 MiB/233.2 MiB (21.0 MiB/s) with 4 file(s) remaining
Completed 89.7 MiB/233.2 MiB (20.9 MiB/s) with 4 file(s) remaining
Completed 89.9 MiB/233.2 MiB (20.9 MiB/s) with 4 file(s) remaining
Completed 90.2 MiB/233.2 MiB (20.8 MiB/s) with 4 file(s) remaining
Completed 90.4 MiB/233.2 MiB (20.9 MiB/s) with 4 file(s) remaining
Completed 90.7 MiB/233.2 MiB (20.8 MiB/s) with 4 file(s) remaining
Completed 90.9 MiB/233.2 MiB (20.9 MiB/s) with 4 file(s) remaining
Completed 91.2 MiB/233.2 MiB (20.8 MiB/s) with 4 file(s) remaining
Completed 91.4 MiB/233.2 MiB (20.9 MiB/s) with 4 file(s) remaining
Completed 91.7 MiB/233.2 MiB (20.8 MiB/s) with 4 file(s) remaining
Completed 91.9 MiB/233.2 MiB (20.8 MiB/s) with 4 file(s) remaining
Completed 92.2 MiB/233.2 MiB (20.8 MiB/s) with 4 file(s) remaining
Completed 92.4 MiB/233.2 MiB (20.7 MiB/s) with 4 file(s) remaining
Completed 92.7 MiB/233.2 MiB (20.7 MiB/s) with 4 file(s) remaining
Completed 92.9 MiB/233.2 MiB (20.5 MiB/s) with 4 file(s) remaining
Completed 93.2 MiB/233.2 MiB (20.5 MiB/s) with 4 file(s) remaining
Completed 93.4 MiB/233.2 MiB (20.5 MiB/s) with 4 file(s) remaining
Completed 93.7 MiB/233.2 MiB (20.6 MiB/s) with 4 file(s) remaining
Completed 93.9 MiB/233.2 MiB (20.6 MiB/s) with 4 file(s) remaining
Completed 94.2 MiB/233.2 MiB (20.5 MiB/s) with 4 file(s) remaining
Completed 94.4 MiB/233.2 MiB (20.6 MiB/s) with 4 file(s) remaining
Completed 94.7 MiB/233.2 MiB (20.5 MiB/s) with 4 file(s) remaining
Completed 94.9 MiB/233.2 MiB (20.6 MiB/s) with 4 file(s) remaining
Completed 95.2 MiB/233.2 MiB (20.6 MiB/s) with 4 file(s) remaining
Completed 95.4 MiB/233.2 MiB (20.7 MiB/s) with 4 file(s) remaining
Completed 95.7 MiB/233.2 MiB (20.7 MiB/s) with 4 file(s) remaining
Completed 95.9 MiB/233.2 MiB (20.7 MiB/s) with 4 file(s) remaining
Completed 96.2 MiB/233.2 MiB (20.7 MiB/s) with 4 file(s) remaining
Completed 96.4 MiB/233.2 MiB (20.8 MiB/s) with 4 file(s) remaining
Completed 96.7 MiB/233.2 MiB (20.8 MiB/s) with 4 file(s) remaining
Completed 96.9 MiB/233.2 MiB (20.8 MiB/s) with 4 file(s) remaining
Completed 97.2 MiB/233.2 MiB (20.7 MiB/s) with 4 file(s) remaining
Completed 97.4 MiB/233.2 MiB (20.8 MiB/s) with 4 file(s) remaining
Completed 97.7 MiB/233.2 MiB (20.8 MiB/s) with 4 file(s) remaining
Completed 97.9 MiB/233.2 MiB (20.9 MiB/s) with 4 file(s) remaining
Completed 98.2 MiB/233.2 MiB (20.9 MiB/s) with 4 file(s) remaining
Completed 98.4 MiB/233.2 MiB (20.9 MiB/s) with 4 file(s) remaining
Completed 98.7 MiB/233.2 MiB (20.9 MiB/s) with 4 file(s) remaining
Completed 98.9 MiB/233.2 MiB (20.9 MiB/s) with 4 file(s) remaining
Completed 99.2 MiB/233.2 MiB (20.9 MiB/s) with 4 file(s) remaining
Completed 99.4 MiB/233.2 MiB (20.9 MiB/s) with 4 file(s) remaining
Completed 99.7 MiB/233.2 MiB (20.9 MiB/s) with 4 file(s) remaining
Completed 99.9 MiB/233.2 MiB (21.0 MiB/s) with 4 file(s) remaining
Completed 100.2 MiB/233.2 MiB (20.9 MiB/s) with 4 file(s) remaining
Completed 100.4 MiB/233.2 MiB (20.9 MiB/s) with 4 file(s) remaining
Completed 100.7 MiB/233.2 MiB (20.9 MiB/s) with 4 file(s) remaining
Completed 100.9 MiB/233.2 MiB (20.9 MiB/s) with 4 file(s) remaining
Completed 101.2 MiB/233.2 MiB (21.0 MiB/s) with 4 file(s) remaining
Completed 101.4 MiB/233.2 MiB (21.0 MiB/s) with 4 file(s) remaining
Completed 101.7 MiB/233.2 MiB (21.1 MiB/s) with 4 file(s) remaining
Completed 101.9 MiB/233.2 MiB (21.0 MiB/s) with 4 file(s) remaining
Completed 102.2 MiB/233.2 MiB (21.0 MiB/s) with 4 file(s) remaining
Completed 102.4 MiB/233.2 MiB (21.0 MiB/s) with 4 file(s) remaining
Completed 102.7 MiB/233.2 MiB (21.1 MiB/s) with 4 file(s) remaining
Completed 102.9 MiB/233.2 MiB (21.0 MiB/s) with 4 file(s) remaining
Completed 103.2 MiB/233.2 MiB (21.1 MiB/s) with 4 file(s) remaining
Completed 103.4 MiB/233.2 MiB (21.1 MiB/s) with 4 file(s) remaining
Completed 103.7 MiB/233.2 MiB (21.1 MiB/s) with 4 file(s) remaining
Completed 103.9 MiB/233.2 MiB (21.1 MiB/s) with 4 file(s) remaining
Completed 104.2 MiB/233.2 MiB (21.1 MiB/s) with 4 file(s) remaining
Completed 104.4 MiB/233.2 MiB (21.1 MiB/s) with 4 file(s) remaining
Completed 104.7 MiB/233.2 MiB (21.1 MiB/s) with 4 file(s) remaining
Completed 104.9 MiB/233.2 MiB (20.9 MiB/s) with 4 file(s) remaining
Completed 105.2 MiB/233.2 MiB (21.0 MiB/s) with 4 file(s) remaining
Completed 105.4 MiB/233.2 MiB (21.0 MiB/s) with 4 file(s) remaining
Completed 105.7 MiB/233.2 MiB (21.0 MiB/s) with 4 file(s) remaining
Completed 105.9 MiB/233.2 MiB (20.9 MiB/s) with 4 file(s) remaining
Completed 106.2 MiB/233.2 MiB (20.9 MiB/s) with 4 file(s) remaining
Completed 106.4 MiB/233.2 MiB (20.9 MiB/s) with 4 file(s) remaining
Completed 106.7 MiB/233.2 MiB (20.9 MiB/s) with 4 file(s) remaining
Completed 106.9 MiB/233.2 MiB (20.9 MiB/s) with 4 file(s) remaining
Completed 107.2 MiB/233.2 MiB (20.8 MiB/s) with 4 file(s) remaining
Completed 107.4 MiB/233.2 MiB (20.9 MiB/s) with 4 file(s) remaining
Completed 107.7 MiB/233.2 MiB (20.9 MiB/s) with 4 file(s) remaining
Completed 107.9 MiB/233.2 MiB (20.9 MiB/s) with 4 file(s) remaining
Completed 108.2 MiB/233.2 MiB (21.0 MiB/s) with 4 file(s) remaining
Completed 108.4 MiB/233.2 MiB (21.0 MiB/s) with 4 file(s) remaining
Completed 108.7 MiB/233.2 MiB (21.0 MiB/s) with 4 file(s) remaining
Completed 108.9 MiB/233.2 MiB (21.0 MiB/s) with 4 file(s) remaining
Completed 109.2 MiB/233.2 MiB (21.0 MiB/s) with 4 file(s) remaining
Completed 109.4 MiB/233.2 MiB (21.0 MiB/s) with 4 file(s) remaining
Completed 109.7 MiB/233.2 MiB (21.0 MiB/s) with 4 file(s) remaining
Completed 109.9 MiB/233.2 MiB (21.1 MiB/s) with 4 file(s) remaining
Completed 110.2 MiB/233.2 MiB (21.1 MiB/s) with 4 file(s) remaining
Completed 110.4 MiB/233.2 MiB (21.1 MiB/s) with 4 file(s) remaining
Completed 110.7 MiB/233.2 MiB (21.1 MiB/s) with 4 file(s) remaining
Completed 110.9 MiB/233.2 MiB (21.1 MiB/s) with 4 file(s) remaining
Completed 111.2 MiB/233.2 MiB (21.1 MiB/s) with 4 file(s) remaining
Completed 111.4 MiB/233.2 MiB (21.1 MiB/s) with 4 file(s) remaining
Completed 111.7 MiB/233.2 MiB (21.1 MiB/s) with 4 file(s) remaining
Completed 111.9 MiB/233.2 MiB (21.2 MiB/s) with 4 file(s) remaining
Completed 112.2 MiB/233.2 MiB (21.1 MiB/s) with 4 file(s) remaining
Completed 112.4 MiB/233.2 MiB (21.1 MiB/s) with 4 file(s) remaining
Completed 112.7 MiB/233.2 MiB (21.2 MiB/s) with 4 file(s) remaining
Completed 112.9 MiB/233.2 MiB (21.1 MiB/s) with 4 file(s) remaining
Completed 113.2 MiB/233.2 MiB (21.1 MiB/s) with 4 file(s) remaining
Completed 113.4 MiB/233.2 MiB (21.1 MiB/s) with 4 file(s) remaining
Completed 113.7 MiB/233.2 MiB (21.1 MiB/s) with 4 file(s) remaining
Completed 113.9 MiB/233.2 MiB (21.2 MiB/s) with 4 file(s) remaining
Completed 114.2 MiB/233.2 MiB (21.1 MiB/s) with 4 file(s) remaining
Completed 114.4 MiB/233.2 MiB (21.1 MiB/s) with 4 file(s) remaining
Completed 114.7 MiB/233.2 MiB (21.1 MiB/s) with 4 file(s) remaining
Completed 114.9 MiB/233.2 MiB (21.2 MiB/s) with 4 file(s) remaining
Completed 115.2 MiB/233.2 MiB (21.2 MiB/s) with 4 file(s) remaining
Completed 115.4 MiB/233.2 MiB (21.3 MiB/s) with 4 file(s) remaining
Completed 115.7 MiB/233.2 MiB (21.2 MiB/s) with 4 file(s) remaining
Completed 115.9 MiB/233.2 MiB (21.2 MiB/s) with 4 file(s) remaining
Completed 116.2 MiB/233.2 MiB (21.2 MiB/s) with 4 file(s) remaining
Completed 116.4 MiB/233.2 MiB (21.3 MiB/s) with 4 file(s) remaining
Completed 116.7 MiB/233.2 MiB (21.3 MiB/s) with 4 file(s) remaining
Completed 116.9 MiB/233.2 MiB (21.3 MiB/s) with 4 file(s) remaining
Completed 117.2 MiB/233.2 MiB (21.3 MiB/s) with 4 file(s) remaining
Completed 117.4 MiB/233.2 MiB (21.4 MiB/s) with 4 file(s) remaining
Completed 117.7 MiB/233.2 MiB (21.3 MiB/s) with 4 file(s) remaining
Completed 117.9 MiB/233.2 MiB (21.4 MiB/s) with 4 file(s) remaining
Completed 118.2 MiB/233.2 MiB (21.4 MiB/s) with 4 file(s) remaining
Completed 118.4 MiB/233.2 MiB (21.4 MiB/s) with 4 file(s) remaining
Completed 118.7 MiB/233.2 MiB (21.4 MiB/s) with 4 file(s) remaining
Completed 118.9 MiB/233.2 MiB (21.3 MiB/s) with 4 file(s) remaining
Completed 119.2 MiB/233.2 MiB (21.4 MiB/s) with 4 file(s) remaining
Completed 119.4 MiB/233.2 MiB (21.3 MiB/s) with 4 file(s) remaining
Completed 119.6 MiB/233.2 MiB (21.3 MiB/s) with 4 file(s) remaining
Completed 119.9 MiB/233.2 MiB (21.2 MiB/s) with 4 file(s) remaining
Completed 120.1 MiB/233.2 MiB (21.2 MiB/s) with 4 file(s) remaining
Completed 120.4 MiB/233.2 MiB (21.2 MiB/s) with 4 file(s) remaining
Completed 120.6 MiB/233.2 MiB (21.2 MiB/s) with 4 file(s) remaining
Completed 120.9 MiB/233.2 MiB (21.3 MiB/s) with 4 file(s) remaining
Completed 121.1 MiB/233.2 MiB (21.3 MiB/s) with 4 file(s) remaining
Completed 121.4 MiB/233.2 MiB (21.3 MiB/s) with 4 file(s) remaining
Completed 121.6 MiB/233.2 MiB (21.3 MiB/s) with 4 file(s) remaining
Completed 121.9 MiB/233.2 MiB (21.2 MiB/s) with 4 file(s) remaining
Completed 122.1 MiB/233.2 MiB (21.3 MiB/s) with 4 file(s) remaining
Completed 122.4 MiB/233.2 MiB (21.3 MiB/s) with 4 file(s) remaining
Completed 122.6 MiB/233.2 MiB (21.3 MiB/s) with 4 file(s) remaining
Completed 122.9 MiB/233.2 MiB (21.4 MiB/s) with 4 file(s) remaining
Completed 123.1 MiB/233.2 MiB (21.4 MiB/s) with 4 file(s) remaining
Completed 123.4 MiB/233.2 MiB (21.3 MiB/s) with 4 file(s) remaining
Completed 123.6 MiB/233.2 MiB (21.3 MiB/s) with 4 file(s) remaining
Completed 123.9 MiB/233.2 MiB (21.4 MiB/s) with 4 file(s) remaining
Completed 124.1 MiB/233.2 MiB (21.4 MiB/s) with 4 file(s) remaining
Completed 124.4 MiB/233.2 MiB (21.5 MiB/s) with 4 file(s) remaining
Completed 124.6 MiB/233.2 MiB (21.4 MiB/s) with 4 file(s) remaining
upload: ../../../data/datafile-10-MB to s3://awscli-mint-test-bucket-12499/datafile-10-MBCompleted 124.6 MiB/233.2 MiB (21.4 MiB/s) with 3 file(s) remaining
Completed 124.9 MiB/233.2 MiB (21.5 MiB/s) with 3 file(s) remaining
Completed 125.1 MiB/233.2 MiB (21.5 MiB/s) with 3 file(s) remaining
Completed 125.4 MiB/233.2 MiB (21.5 MiB/s) with 3 file(s) remaining
Completed 125.6 MiB/233.2 MiB (21.5 MiB/s) with 3 file(s) remaining
Completed 125.9 MiB/233.2 MiB (21.5 MiB/s) with 3 file(s) remaining
Completed 126.1 MiB/233.2 MiB (21.6 MiB/s) with 3 file(s) remaining
Completed 126.4 MiB/233.2 MiB (21.6 MiB/s) with 3 file(s) remaining
Completed 126.6 MiB/233.2 MiB (21.5 MiB/s) with 3 file(s) remaining
Completed 126.9 MiB/233.2 MiB (21.6 MiB/s) with 3 file(s) remaining
Completed 127.1 MiB/233.2 MiB (21.5 MiB/s) with 3 file(s) remaining
Completed 127.4 MiB/233.2 MiB (21.5 MiB/s) with 3 file(s) remaining
Completed 127.6 MiB/233.2 MiB (21.6 MiB/s) with 3 file(s) remaining
Completed 127.9 MiB/233.2 MiB (21.5 MiB/s) with 3 file(s) remaining
Completed 128.1 MiB/233.2 MiB (21.5 MiB/s) with 3 file(s) remaining
Completed 128.4 MiB/233.2 MiB (21.5 MiB/s) with 3 file(s) remaining
Completed 128.6 MiB/233.2 MiB (21.5 MiB/s) with 3 file(s) remaining
Completed 128.9 MiB/233.2 MiB (21.5 MiB/s) with 3 file(s) remaining
Completed 129.1 MiB/233.2 MiB (21.5 MiB/s) with 3 file(s) remaining
Completed 129.4 MiB/233.2 MiB (21.5 MiB/s) with 3 file(s) remaining
Completed 129.6 MiB/233.2 MiB (21.5 MiB/s) with 3 file(s) remaining
Completed 129.9 MiB/233.2 MiB (21.5 MiB/s) with 3 file(s) remaining
Completed 130.1 MiB/233.2 MiB (21.5 MiB/s) with 3 file(s) remaining
Completed 130.4 MiB/233.2 MiB (21.5 MiB/s) with 3 file(s) remaining
Completed 130.6 MiB/233.2 MiB (21.5 MiB/s) with 3 file(s) remaining
Completed 130.9 MiB/233.2 MiB (21.5 MiB/s) with 3 file(s) remaining
Completed 131.1 MiB/233.2 MiB (21.5 MiB/s) with 3 file(s) remaining
Completed 131.4 MiB/233.2 MiB (21.5 MiB/s) with 3 file(s) remaining
Completed 131.6 MiB/233.2 MiB (21.5 MiB/s) with 3 file(s) remaining
Completed 131.9 MiB/233.2 MiB (21.5 MiB/s) with 3 file(s) remaining
Completed 132.1 MiB/233.2 MiB (21.4 MiB/s) with 3 file(s) remaining
Completed 132.4 MiB/233.2 MiB (21.4 MiB/s) with 3 file(s) remaining
Completed 132.6 MiB/233.2 MiB (21.4 MiB/s) with 3 file(s) remaining
Completed 132.9 MiB/233.2 MiB (21.3 MiB/s) with 3 file(s) remaining
Completed 133.1 MiB/233.2 MiB (21.3 MiB/s) with 3 file(s) remaining
Completed 133.4 MiB/233.2 MiB (21.4 MiB/s) with 3 file(s) remaining
Completed 133.6 MiB/233.2 MiB (21.4 MiB/s) with 3 file(s) remaining
Completed 133.9 MiB/233.2 MiB (21.3 MiB/s) with 3 file(s) remaining
Completed 134.1 MiB/233.2 MiB (21.4 MiB/s) with 3 file(s) remaining
Completed 134.4 MiB/233.2 MiB (21.4 MiB/s) with 3 file(s) remaining
Completed 134.6 MiB/233.2 MiB (21.4 MiB/s) with 3 file(s) remaining
Completed 134.9 MiB/233.2 MiB (21.3 MiB/s) with 3 file(s) remaining
Completed 135.1 MiB/233.2 MiB (21.3 MiB/s) with 3 file(s) remaining
Completed 135.4 MiB/233.2 MiB (21.3 MiB/s) with 3 file(s) remaining
Completed 135.6 MiB/233.2 MiB (21.3 MiB/s) with 3 file(s) remaining
upload failed: ../../../data/datafile-129-MB to s3://awscli-mint-test-bucket-12499/datafile-129-MB ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))Completed 213.7 MiB/233.2 MiB (21.3 MiB/s) with 2 file(s) remaining
Completed 213.9 MiB/233.2 MiB (21.3 MiB/s) with 2 file(s) remaining
Completed 214.2 MiB/233.2 MiB (21.3 MiB/s) with 2 file(s) remaining
Completed 214.4 MiB/233.2 MiB (21.3 MiB/s) with 2 file(s) remaining
Completed 214.7 MiB/233.2 MiB (21.3 MiB/s) with 2 file(s) remaining
Completed 214.9 MiB/233.2 MiB (21.3 MiB/s) with 2 file(s) remaining
Completed 215.2 MiB/233.2 MiB (21.3 MiB/s) with 2 file(s) remaining
Completed 215.4 MiB/233.2 MiB (21.3 MiB/s) with 2 file(s) remaining
Completed 215.7 MiB/233.2 MiB (21.3 MiB/s) with 2 file(s) remaining
Completed 215.9 MiB/233.2 MiB (21.3 MiB/s) with 2 file(s) remaining
Completed 216.2 MiB/233.2 MiB (21.2 MiB/s) with 2 file(s) remaining
Completed 216.4 MiB/233.2 MiB (21.3 MiB/s) with 2 file(s) remaining
Completed 216.7 MiB/233.2 MiB (21.3 MiB/s) with 2 file(s) remaining
Completed 216.9 MiB/233.2 MiB (21.2 MiB/s) with 2 file(s) remaining
Completed 217.2 MiB/233.2 MiB (21.2 MiB/s) with 2 file(s) remaining
Completed 217.4 MiB/233.2 MiB (21.2 MiB/s) with 2 file(s) remaining
Completed 217.7 MiB/233.2 MiB (21.2 MiB/s) with 2 file(s) remaining
Completed 217.9 MiB/233.2 MiB (21.2 MiB/s) with 2 file(s) remaining
Completed 218.2 MiB/233.2 MiB (21.2 MiB/s) with 2 file(s) remaining
Completed 218.4 MiB/233.2 MiB (21.2 MiB/s) with 2 file(s) remaining
Completed 218.7 MiB/233.2 MiB (21.2 MiB/s) with 2 file(s) remaining
Completed 218.9 MiB/233.2 MiB (21.1 MiB/s) with 2 file(s) remaining
Completed 219.2 MiB/233.2 MiB (21.2 MiB/s) with 2 file(s) remaining
Completed 219.4 MiB/233.2 MiB (21.2 MiB/s) with 2 file(s) remaining
Completed 219.7 MiB/233.2 MiB (21.1 MiB/s) with 2 file(s) remaining
Completed 219.9 MiB/233.2 MiB (21.1 MiB/s) with 2 file(s) remaining
Completed 220.2 MiB/233.2 MiB (21.1 MiB/s) with 2 file(s) remaining
Completed 220.4 MiB/233.2 MiB (21.1 MiB/s) with 2 file(s) remaining
Completed 220.7 MiB/233.2 MiB (21.1 MiB/s) with 2 file(s) remaining
Completed 220.9 MiB/233.2 MiB (21.1 MiB/s) with 2 file(s) remaining
Completed 221.2 MiB/233.2 MiB (21.1 MiB/s) with 2 file(s) remaining
Completed 221.4 MiB/233.2 MiB (21.1 MiB/s) with 2 file(s) remaining
Completed 221.7 MiB/233.2 MiB (21.1 MiB/s) with 2 file(s) remaining
Completed 221.9 MiB/233.2 MiB (21.1 MiB/s) with 2 file(s) remaining
Completed 222.2 MiB/233.2 MiB (21.1 MiB/s) with 2 file(s) remaining
Completed 222.4 MiB/233.2 MiB (21.1 MiB/s) with 2 file(s) remaining
Completed 222.7 MiB/233.2 MiB (21.0 MiB/s) with 2 file(s) remaining
Completed 222.9 MiB/233.2 MiB (21.1 MiB/s) with 2 file(s) remaining
Completed 223.2 MiB/233.2 MiB (21.1 MiB/s) with 2 file(s) remaining
Completed 223.4 MiB/233.2 MiB (21.0 MiB/s) with 2 file(s) remaining
Completed 223.7 MiB/233.2 MiB (21.0 MiB/s) with 2 file(s) remaining
Completed 223.9 MiB/233.2 MiB (21.1 MiB/s) with 2 file(s) remaining
Completed 224.2 MiB/233.2 MiB (21.0 MiB/s) with 2 file(s) remaining
Completed 224.4 MiB/233.2 MiB (21.0 MiB/s) with 2 file(s) remaining
Completed 224.7 MiB/233.2 MiB (21.0 MiB/s) with 2 file(s) remaining
Completed 224.9 MiB/233.2 MiB (21.0 MiB/s) with 2 file(s) remaining
Completed 225.2 MiB/233.2 MiB (21.0 MiB/s) with 2 file(s) remaining
Completed 225.4 MiB/233.2 MiB (20.9 MiB/s) with 2 file(s) remaining
Completed 225.7 MiB/233.2 MiB (20.9 MiB/s) with 2 file(s) remaining
Completed 225.9 MiB/233.2 MiB (20.9 MiB/s) with 2 file(s) remaining
Completed 226.2 MiB/233.2 MiB (20.9 MiB/s) with 2 file(s) remaining
Completed 226.4 MiB/233.2 MiB (20.9 MiB/s) with 2 file(s) remaining
Completed 226.7 MiB/233.2 MiB (20.9 MiB/s) with 2 file(s) remaining
Completed 226.9 MiB/233.2 MiB (20.9 MiB/s) with 2 file(s) remaining
Completed 227.2 MiB/233.2 MiB (20.9 MiB/s) with 2 file(s) remaining
Completed 227.4 MiB/233.2 MiB (20.9 MiB/s) with 2 file(s) remaining
Completed 227.7 MiB/233.2 MiB (20.8 MiB/s) with 2 file(s) remaining
Completed 227.9 MiB/233.2 MiB (20.8 MiB/s) with 2 file(s) remaining
Completed 228.2 MiB/233.2 MiB (20.9 MiB/s) with 2 file(s) remaining
Completed 228.4 MiB/233.2 MiB (20.8 MiB/s) with 2 file(s) remaining
Completed 228.7 MiB/233.2 MiB (20.7 MiB/s) with 2 file(s) remaining
Completed 228.9 MiB/233.2 MiB (20.7 MiB/s) with 2 file(s) remaining
Completed 229.2 MiB/233.2 MiB (20.7 MiB/s) with 2 file(s) remaining
Completed 229.4 MiB/233.2 MiB (20.7 MiB/s) with 2 file(s) remaining
Completed 229.7 MiB/233.2 MiB (20.6 MiB/s) with 2 file(s) remaining
Completed 229.9 MiB/233.2 MiB (20.6 MiB/s) with 2 file(s) remaining
Completed 230.2 MiB/233.2 MiB (20.6 MiB/s) with 2 file(s) remaining
Completed 230.4 MiB/233.2 MiB (20.5 MiB/s) with 2 file(s) remaining
Completed 230.7 MiB/233.2 MiB (20.5 MiB/s) with 2 file(s) remaining
Completed 230.9 MiB/233.2 MiB (20.5 MiB/s) with 2 file(s) remaining
Completed 231.2 MiB/233.2 MiB (20.4 MiB/s) with 2 file(s) remaining
Completed 231.4 MiB/233.2 MiB (20.4 MiB/s) with 2 file(s) remaining
Completed 231.7 MiB/233.2 MiB (20.3 MiB/s) with 2 file(s) remaining
Completed 231.9 MiB/233.2 MiB (20.2 MiB/s) with 2 file(s) remaining
Completed 232.2 MiB/233.2 MiB (20.1 MiB/s) with 2 file(s) remaining
Completed 232.4 MiB/233.2 MiB (20.0 MiB/s) with 2 file(s) remaining
Completed 232.7 MiB/233.2 MiB (19.8 MiB/s) with 2 file(s) remaining
Completed 232.9 MiB/233.2 MiB (19.7 MiB/s) with 2 file(s) remaining
Completed 233.2 MiB/233.2 MiB (19.6 MiB/s) with 2 file(s) remaining
upload: ../../../data/datafile-65-MB to s3://awscli-mint-test-bucket-12499/datafile-65-MBCompleted 233.2 MiB/233.2 MiB (19.6 MiB/s) with 1 file(s) remaining
upload: ../../../data/datafile-1-MB to s3://awscli-mint-test-bucket-12499/datafile-1-MB"}

Executed 4 out of 14 tests successfully.
```
<a name="5a31ba37-023d-4628-88cd-763b8b17cb85"></a>
### 7960-1538bdf/mint-gateway-nas.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.61:32655
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp eaeae52a8453:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 0 seconds
(2/14) Running aws-sdk-java tests ... done in 1 seconds
(3/14) Running aws-sdk-php tests ... done in 41 seconds
(4/14) Running aws-sdk-ruby tests ... done in 1 seconds
(5/14) Running awscli tests ... done in 59 seconds
(6/14) Running healthcheck tests ... done in 0 seconds
(7/14) Running mc tests ... done in 23 seconds
(8/14) Running minio-dotnet tests ... done in 21 seconds
(9/14) Running minio-go tests ... done in 30 seconds
(10/14) Running minio-java tests ... FAILED in 2 seconds
{
  "name": "minio-java",
  "function": "putObject(String bucketName, String objectName, InputStream body, long size, String contentType)",
  "args": "contentType: application/javascript",
  "duration": 334,
  "status": "FAIL",
  "error": "java.net.ProtocolException: unexpected end of stream >>> [okhttp3.internal.http1.Http1Codec$FixedLengthSink.close(Http1Codec.java:318), okio.ForwardingSink.close(ForwardingSink.java:47), okio.RealBufferedSink.close(RealBufferedSink.java:248), okhttp3.internal.http.CallServerInterceptor.intercept(CallServerInterceptor.java:84), okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147), okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:45), okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147), okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121), okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:94), okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147), okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121), okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93), okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147), okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:125), okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147), okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121), okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:264), okhttp3.RealCall.execute(RealCall.java:93), io.minio.MinioClient.executeReq(MinioClient.java:1111), io.minio.MinioClient.execute(MinioClient.java:1070), io.minio.MinioClient.executePut(MinioClient.java:1405), io.minio.MinioClient.executePut(MinioClient.java:1427), io.minio.MinioClient.putObject(MinioClient.java:4216), io.minio.MinioClient.putObject(MinioClient.java:4328), io.minio.MinioClient.putObject(MinioClient.java:4183), FunctionalTest.testPutObjectUnknownStreamSize(FunctionalTest.java:548), FunctionalTest.putObject_test8(FunctionalTest.java:576), FunctionalTest.runTests(FunctionalTest.java:2962), FunctionalTest.main(FunctionalTest.java:3118)]"
}

Executed 9 out of 14 tests successfully.
```
<a name="e399558b-c477-42a5-ab95-0bdc2770b520"></a>
### 7960-1538bdf/mint-large-bucket.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.58:31798
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp a0d0cfe42439:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 3 seconds
(2/14) Running aws-sdk-java tests ... done in 1 seconds
(3/14) Running aws-sdk-php tests ... done in 49 seconds
(4/14) Running aws-sdk-ruby tests ... done in 16 seconds
(5/14) Running awscli tests ... done in 2 minutes and 20 seconds
(6/14) Running healthcheck tests ... done in 1 seconds
(7/14) Running mc tests ... FAILED in 2 minutes and 40 seconds
{
  "name": "mc",
  "duration": "130733",
  "function": "test_mirror_list_objects_storage_class",
  "status": "FAIL",
  "error": "/mint/run/core/mc/mc --config-dir /tmp/.mc-4609 --quiet --no-color mirror --storage-class REDUCED_REDUNDANCY /mint/data myminio/mc-test-bucket-25880  >>> \n`/mint/data/datafile-1-MB` -> `myminio/mc-test-bucket-25880/datafile-1-MB`\n`/mint/data/datafile-0-b` -> `myminio/mc-test-bucket-25880/datafile-0-b`\n`/mint/data/datafile-1-kB` -> `myminio/mc-test-bucket-25880/datafile-1-kB`\n`/mint/data/datafile-1-b` -> `myminio/mc-test-bucket-25880/datafile-1-b`\n`/mint/data/datafile-10-MB` -> `myminio/mc-test-bucket-25880/datafile-10-MB`\n`/mint/data/datafile-1.03-MB` -> `myminio/mc-test-bucket-25880/datafile-1.03-MB`\n`/mint/data/datafile-100-kB` -> `myminio/mc-test-bucket-25880/datafile-100-kB`\n`/mint/data/datafile-10-kB` -> `myminio/mc-test-bucket-25880/datafile-10-kB`\n`/mint/data/datafile-11-MB` -> `myminio/mc-test-bucket-25880/datafile-11-MB`\n`/mint/data/datafile-33-kB` -> `myminio/mc-test-bucket-25880/datafile-33-kB`\n`/mint/data/datafile-129-MB` -> `myminio/mc-test-bucket-25880/datafile-129-MB`\n`/mint/data/datafile-5-MB` -> `myminio/mc-test-bucket-25880/datafile-5-MB`\n`/mint/data/datafile-5243880-b` -> `myminio/mc-test-bucket-25880/datafile-5243880-b`\n`/mint/data/datafile-65-MB` -> `myminio/mc-test-bucket-25880/datafile-65-MB`\n`/mint/data/datafile-6-MB` -> `myminio/mc-test-bucket-25880/datafile-6-MB`\nmc: <ERROR> Failed to copy `/mint/data/datafile-129-MB`. Please reduce your request\nmc: <ERROR> Failed to copy `/mint/data/datafile-65-MB`. Please reduce your request\nmc: <ERROR> Failed to copy `/mint/data/datafile-11-MB`. Please reduce your request\nmc: <ERROR> Failed to copy `/mint/data/datafile-10-MB`. Please reduce your request\nTotal: 233.17 MiB, Transferred: 492.25 MiB, Speed: 3.77 MiB/s"
}

Executed 6 out of 14 tests successfully.
```
<a name="ccd76de8-b940-4f01-bb12-f4216e62f9de"></a>
### 7960-1538bdf/mint-dist-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.57:31233
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp ed666eabded1:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... FAILED in 13 seconds
{
  "alert": "",
  "args": {
    "bucketName": "aws-sdk-go-test-nut1nvbw52iqjj",
    "expiry": 60000000000,
    "objectName": "presignedTest"
  },
  "duration": 12605,
  "error": "RequestError: send request failed\ncaused by: Put http://72.28.97.57:31233/aws-sdk-go-test-nut1nvbw52iqjj: dial tcp 72.28.97.57:31233: connect: no route to host",
  "function": "PresignedPut",
  "message": "AWS SDK Go CreateBucket Failed",
  "name": "aws-sdk-go",
  "status": "FAIL"
}

Executed 0 out of 14 tests successfully.
```

**Review by harshavardhana — CHANGES_REQUESTED** [review]
The real issue is using net.Dial for verifying the HTTP endpoint in webhook @Praveenrajmani in-fact that part of code should be doing just `http.Post()` instead of performing a Dial.

So this new refactor is not needed, DialURL should be DialHTTP instead because net.LookupPort() doesn't understand custom schemes but URL parsing succeeds which can lead to unexpected inputs.

```go
package main

import (
	"fmt"
	"net"
	"net/url"
)

func main() {
	u, err := url.Parse("tcp://testbucket")
	fmt.Println(u, err, u.Scheme)
	port, err := net.LookupPort("tcp", u.Scheme)
	fmt.Println(u, err, port)
}
```

**Comment by Praveenrajmani** [comment]
> .Post

Are you suggesting this? @harshavardhana 
```
    req, err := http.NewRequest("HEAD", url, nil)
    if err != nil {
       return 0, err
    }
    resp, err := client.Do(req)
    if err != nil {
       return 0, err
    }
```

**Comment by harshavardhana** [comment]
>     req, err := http.NewRequest("HEAD", url, nil)
>     if err != nil {
>        return 0, err
>     }
>     resp, err := client.Do(req)
>     if err != nil {
>        return 0, err
>     }

Yes but it may be that Webhook only has "POST" enabled i.e we may be able to send a POST without body and verify the webhook endpoint is up.

**Comment by Praveenrajmani** [comment]
> > ```
> > req, err := http.NewRequest("HEAD", url, nil)
> > if err != nil {
> >    return 0, err
> > }
> > resp, err := client.Do(req)
> > if err != nil {
> >    return 0, err
> > }
> > ```
> 
> Yes but it may be that Webhook only has "POST" enabled i.e we may be able to send a POST without body and verify the webhook endpoint is up.

Updated :+1:

**Comment by minio-ops** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-compression-xl.sh | :heavy_check_mark: |
| mint-xl.sh | :heavy_check_mark: |
| mint-compression-fs.sh | :heavy_check_mark: |
| mint-worm.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :x: [more...](#10a97584-ed92-4e22-886c-6e72df37480c) |
| mint-compression-dist-xl.sh | :x: [more...](#30b470dd-4d2d-4940-8676-29c94a993e38) |
| mint-dist-xl.sh | :x: [more...](#b3c9e6af-e82e-4ae8-bd9b-39441c042d9b) |
<a name="30b470dd-4d2d-4940-8676-29c94a993e38"></a>
### 7960-93efaec/mint-compression-dist-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.57:31478
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 9b3f7486ba36:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... FAILED in 12 seconds
{
  "alert": "",
  "args": {
    "bucketName": "aws-sdk-go-test-9un6m3oc0bonxv",
    "expiry": 60000000000,
    "objectName": "presignedTest"
  },
  "duration": 12271,
  "error": "RequestError: send request failed\ncaused by: Put http://72.28.97.57:31478/aws-sdk-go-test-9un6m3oc0bonxv: dial tcp 72.28.97.57:31478: connect: no route to host",
  "function": "PresignedPut",
  "message": "AWS SDK Go CreateBucket Failed",
  "name": "aws-sdk-go",
  "status": "FAIL"
}

Executed 0 out of 14 tests successfully.
```
<a name="b3c9e6af-e82e-4ae8-bd9b-39441c042d9b"></a>
### 7960-93efaec/mint-dist-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.61:30210
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 20cc8f3e0fdc:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 0 seconds
(2/14) Running aws-sdk-java tests ... done in 1 seconds
(3/14) Running aws-sdk-php tests ... done in 43 seconds
(4/14) Running aws-sdk-ruby tests ... done in 3 seconds
(5/14) Running awscli tests ... done in 2 minutes and 3 seconds
(6/14) Running healthcheck tests ... done in 0 seconds
(7/14) Running mc tests ... done in 1 minutes and 0 seconds
(8/14) Running minio-dotnet tests ... done in 46 seconds
(9/14) Running minio-go tests ... done in 47 seconds
(10/14) Running minio-java tests ... FAILED in 41 seconds
{
  "name": "minio-java",
  "function": "removeIncompleteUpload(String bucketName, String objectName)",
  "duration": 226,
  "status": "FAIL",
  "error": "error occurred\nErrorResponse(code=SlowDown, message=Please reduce your request, bucketName=minio-java-test-1blqk27, objectName=minio-java-test-srlj58, resource=/minio-java-test-1blqk27/minio-java-test-srlj58, requestId=15B622EEA2DFF766, hostId=dfd19a15-15fc-42f0-9f42-6e5978fe8c08)\nrequest={method=DELETE, url=http://72.28.97.61:30210/minio-java-test-1blqk27/minio-java-test-srlj58?uploadId=a95ebfe6-d3c2-4c2c-8b9b-918529036998, headers=Host: 72.28.97.61:30210\nUser-Agent: MinIO (amd64; amd64) minio-java/dev\nx-amz-content-sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855\nx-amz-date: 20190730T084528Z\nAuthorization: AWS4-HMAC-SHA256 Credential=*REDACTED*/20190730/us-east-1/s3/aws4_request, SignedHeaders=host;x-amz-content-sha256;x-amz-date, Signature=*REDACTED*\n}\nresponse={code=503, headers=Accept-Ranges: bytes\nContent-Length: 361\nContent-Security-Policy: block-all-mixed-content\nContent-Type: application/xml\nRetry-After: 120\nServer: MinIO/DEVELOPMENT.2019-07-30T08-26-29Z\nVary: Origin\nX-Amz-Request-Id: 15B622EEA2DFF766\nX-Xss-Protection: 1; mode=block\nDate: Tue, 30 Jul 2019 08:45:28 GMT\n}\n >>> [io.minio.MinioClient.executeReq(MinioClient.java:1204), io.minio.MinioClient.execute(MinioClient.java:1070), io.minio.MinioClient.executeDelete(MinioClient.java:1347), io.minio.MinioClient.abortMultipartUpload(MinioClient.java:5149), io.minio.MinioClient.putObject(MinioClient.java:4337), io.minio.MinioClient.putObject(MinioClient.java:4183), FunctionalTest.removeIncompleteUploads_test(FunctionalTest.java:1719), FunctionalTest.runTests(FunctionalTest.java:2992), FunctionalTest.main(FunctionalTest.java:3118)]"
}

Executed 9 out of 14 tests successfully.
```
<a name="10a97584-ed92-4e22-886c-6e72df37480c"></a>
### 7960-93efaec/mint-large-bucket.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.57:32517
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 24786cacc0ce:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... FAILED in 18 seconds
{
  "alert": "",
  "args": {
    "bucketName": "aws-sdk-go-test-ai9krn6dfzydfs",
    "expiry": 60000000000,
    "objectName": "presignedTest"
  },
  "duration": 18393,
  "error": "RequestError: send request failed\ncaused by: Put http://72.28.97.57:32517/aws-sdk-go-test-ai9krn6dfzydfs: dial tcp 72.28.97.57:32517: connect: no route to host",
  "function": "PresignedPut",
  "message": "AWS SDK Go CreateBucket Failed",
  "name": "aws-sdk-go",
  "status": "FAIL"
}

Executed 0 out of 14 tests successfully.
```

**Comment by minio-ops** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-compression-xl.sh | :heavy_check_mark: |
| mint-xl.sh | :heavy_check_mark: |
| mint-compression-dist-xl.sh | :heavy_check_mark: |
| mint-compression-fs.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :x: [more...](#78da2a96-54ad-4d2f-8c10-dc6a971bdc5c) |
| mint-worm.sh | :x: [more...](#f2fbbc71-e586-4b78-a19c-57977ea285b9) |
| mint-dist-xl.sh | :x: [more...](#dfdc63a3-ec18-4a06-80fb-a2ddd5835bf7) |
<a name="f2fbbc71-e586-4b78-a19c-57977ea285b9"></a>
### 7960-e050bd2/mint-worm.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.57:31827
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            worm
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp fb9eeb8c4bd8:/mint/log /tmp/mint-logs'

(1/1) Running worm tests ... FAILED in 12 seconds
{
  "alert": "",
  "args": {
    "bucketName": "bucket-apyjsvuxz710e1cqir8jabb49f2eon7pvine8e3sj985xm3rtuagovt",
    "expiry": 60000000000,
    "objectName": "testObject"
  },
  "duration": 12588,
  "error": "RequestError: send request failed\ncaused by: Put http://72.28.97.57:31827/bucket-apyjsvuxz710e1cqir8jabb49f2eon7pvine8e3sj985xm3rtuagovt: dial tcp 72.28.97.57:31827: connect: no route to host",
  "function": "PutAndDelete",
  "message": "WORM_MODE ON  - CreateBucket Failed",
  "name": "test worm mode",
  "status": "FAIL"
}

Executed 0 out of 1 tests successfully.
```
<a name="78da2a96-54ad-4d2f-8c10-dc6a971bdc5c"></a>
### 7960-e050bd2/mint-large-bucket.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.51:30082
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 0a40d80bd3b1:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 3 seconds
(2/14) Running aws-sdk-java tests ... done in 1 seconds
(3/14) Running aws-sdk-php tests ... done in 51 seconds
(4/14) Running aws-sdk-ruby tests ... done in 11 seconds
(5/14) Running awscli tests ... done in 2 minutes and 18 seconds
(6/14) Running healthcheck tests ... done in 0 seconds
(7/14) Running mc tests ... FAILED in 7 minutes and 24 seconds
{
  "name": "mc",
  "duration": "109127",
  "function": "test_mirror_list_objects_storage_class",
  "status": "FAIL",
  "error": "/mint/run/core/mc/mc --config-dir /tmp/.mc-8291 --quiet --no-color mirror --storage-class REDUCED_REDUNDANCY /mint/data myminio/mc-test-bucket-24888  >>> \n`/mint/data/datafile-0-b` -> `myminio/mc-test-bucket-24888/datafile-0-b`\n`/mint/data/datafile-1-kB` -> `myminio/mc-test-bucket-24888/datafile-1-kB`\n`/mint/data/datafile-1-b` -> `myminio/mc-test-bucket-24888/datafile-1-b`\n`/mint/data/datafile-1-MB` -> `myminio/mc-test-bucket-24888/datafile-1-MB`\n`/mint/data/datafile-10-kB` -> `myminio/mc-test-bucket-24888/datafile-10-kB`\n`/mint/data/datafile-1.03-MB` -> `myminio/mc-test-bucket-24888/datafile-1.03-MB`\n`/mint/data/datafile-10-MB` -> `myminio/mc-test-bucket-24888/datafile-10-MB`\n`/mint/data/datafile-11-MB` -> `myminio/mc-test-bucket-24888/datafile-11-MB`\n`/mint/data/datafile-5-MB` -> `myminio/mc-test-bucket-24888/datafile-5-MB`\n`/mint/data/datafile-129-MB` -> `myminio/mc-test-bucket-24888/datafile-129-MB`\n`/mint/data/datafile-100-kB` -> `myminio/mc-test-bucket-24888/datafile-100-kB`\n`/mint/data/datafile-6-MB` -> `myminio/mc-test-bucket-24888/datafile-6-MB`\n`/mint/data/datafile-33-kB` -> `myminio/mc-test-bucket-24888/datafile-33-kB`\n`/mint/data/datafile-5243880-b` -> `myminio/mc-test-bucket-24888/datafile-5243880-b`\n`/mint/data/datafile-65-MB` -> `myminio/mc-test-bucket-24888/datafile-65-MB`\nmc: <ERROR> Failed to copy `/mint/data/datafile-10-MB`. Please reduce your request\nmc: <ERROR> Failed to copy `/mint/data/datafile-129-MB`. Please reduce your request\nmc: <ERROR> Failed to copy `/mint/data/datafile-11-MB`. Please reduce your request\nmc: <ERROR> Failed to copy `/mint/data/datafile-65-MB`. Please reduce your request\nTotal: 233.17 MiB, Transferred: 498.05 MiB, Speed: 4.57 MiB/s"
}

Executed 6 out of 14 tests successfully.
```
<a name="dfdc63a3-ec18-4a06-80fb-a2ddd5835bf7"></a>
### 7960-e050bd2/mint-dist-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.58:30743
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp c6296e38dd33:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 1 seconds
(2/14) Running aws-sdk-java tests ... done in 1 seconds
(3/14) Running aws-sdk-php tests ... done in 46 seconds
(4/14) Running aws-sdk-ruby tests ... done in 3 seconds
(5/14) Running awscli tests ... done in 2 minutes and 1 seconds
(6/14) Running healthcheck tests ... done in 0 seconds
(7/14) Running mc tests ... done in 1 minutes and 5 seconds
(8/14) Running minio-dotnet tests ... done in 34 seconds
(9/14) Running minio-go tests ... done in 1 minutes and 1 seconds
(10/14) Running minio-java tests ... FAILED in 37 seconds
{
  "name": "minio-java",
  "function": "listIncompleteUploads(String bucketName, String prefix)",
  "duration": 371,
  "status": "FAIL",
  "error": "error occurred\nErrorResponse(code=SlowDown, message=Please reduce your request, bucketName=minio-java-test-jr4qrs, objectName=minio-java-test-39du55k, resource=/minio-java-test-jr4qrs/minio-java-test-39du55k, requestId=15B644EECB930EB4, hostId=2db0f296-7c52-4484-b7ca-4803a0702989)\nrequest={method=DELETE, url=http://72.28.97.58:30743/minio-java-test-jr4qrs/minio-java-test-39du55k?uploadId=ac1f2b84-306e-40e9-bec5-52e8c9ff8f97, headers=Host: 72.28.97.58:30743\nUser-Agent: MinIO (amd64; amd64) minio-java/dev\nx-amz-content-sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855\nx-amz-date: 20190730T190832Z\nAuthorization: AWS4-HMAC-SHA256 Credential=*REDACTED*/20190730/us-east-1/s3/aws4_request, SignedHeaders=host;x-amz-content-sha256;x-amz-date, Signature=*REDACTED*\n}\nresponse={code=503, headers=Accept-Ranges: bytes\nContent-Length: 361\nContent-Security-Policy: block-all-mixed-content\nContent-Type: application/xml\nRetry-After: 120\nServer: MinIO/DEVELOPMENT.2019-07-30T18-46-09Z\nVary: Origin\nX-Amz-Request-Id: 15B644EECB930EB4\nX-Xss-Protection: 1; mode=block\nDate: Tue, 30 Jul 2019 19:08:33 GMT\n}\n >>> [io.minio.MinioClient.executeReq(MinioClient.java:1204), io.minio.MinioClient.execute(MinioClient.java:1070), io.minio.MinioClient.executeDelete(MinioClient.java:1347), io.minio.MinioClient.abortMultipartUpload(MinioClient.java:5149), io.minio.MinioClient.putObject(MinioClient.java:4337), io.minio.MinioClient.putObject(MinioClient.java:4183), FunctionalTest.listIncompleteUploads_test2(FunctionalTest.java:1639), FunctionalTest.runTests(FunctionalTest.java:2989), FunctionalTest.main(FunctionalTest.java:3118)]"
}

Executed 9 out of 14 tests successfully.
```

**Comment by minio-ops** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-xl.sh | :heavy_check_mark: |
| mint-compression-dist-xl.sh | :heavy_check_mark: |
| mint-compression-fs.sh | :heavy_check_mark: |
| mint-worm.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-dist-xl.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-compression-xl.sh | :x: [more...](#c40a70bb-3771-4ba1-a263-89e5c2ef18b7) |
| mint-large-bucket.sh | :x: [more...](#a2a17211-fe08-40db-8027-786033bbf656) |
<a name="a2a17211-fe08-40db-8027-786033bbf656"></a>
### 7960-9f9610d/mint-large-bucket.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.60:31584
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp d64bd7a705b8:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 2 seconds
(2/14) Running aws-sdk-java tests ... done in 2 seconds
(3/14) Running aws-sdk-php tests ... done in 48 seconds
(4/14) Running aws-sdk-ruby tests ... done in 12 seconds
(5/14) Running awscli tests ... FAILED in 1 minutes and 1 seconds
{"name": "awscli", "duration": 8901, "function": "aws --endpoint-url http://72.28.97.60:31584 s3 cp /mint/data/datafile-65-MB s3://awscli-mint-test-bucket-5336/datafile-65-MB\n", "status": "FAIL", "error": "Completed 256.0 KiB/65.0 MiB (1.2 MiB/s) with 1 file(s) remaining
Completed 512.0 KiB/65.0 MiB (2.3 MiB/s) with 1 file(s) remaining
Completed 768.0 KiB/65.0 MiB (3.5 MiB/s) with 1 file(s) remaining
Completed 1.0 MiB/65.0 MiB (4.6 MiB/s) with 1 file(s) remaining  
Completed 1.2 MiB/65.0 MiB (5.7 MiB/s) with 1 file(s) remaining  
Completed 1.5 MiB/65.0 MiB (6.8 MiB/s) with 1 file(s) remaining  
Completed 1.8 MiB/65.0 MiB (7.4 MiB/s) with 1 file(s) remaining  
Completed 2.0 MiB/65.0 MiB (7.8 MiB/s) with 1 file(s) remaining  
Completed 2.2 MiB/65.0 MiB (8.4 MiB/s) with 1 file(s) remaining  
Completed 2.5 MiB/65.0 MiB (8.8 MiB/s) with 1 file(s) remaining  
Completed 2.8 MiB/65.0 MiB (9.3 MiB/s) with 1 file(s) remaining  
Completed 3.0 MiB/65.0 MiB (9.7 MiB/s) with 1 file(s) remaining  
Completed 3.2 MiB/65.0 MiB (10.2 MiB/s) with 1 file(s) remaining 
Completed 3.5 MiB/65.0 MiB (10.6 MiB/s) with 1 file(s) remaining 
Completed 3.8 MiB/65.0 MiB (11.0 MiB/s) with 1 file(s) remaining 
Completed 4.0 MiB/65.0 MiB (11.4 MiB/s) with 1 file(s) remaining 
Completed 4.2 MiB/65.0 MiB (11.8 MiB/s) with 1 file(s) remaining 
Completed 4.5 MiB/65.0 MiB (12.2 MiB/s) with 1 file(s) remaining 
Completed 4.8 MiB/65.0 MiB (12.6 MiB/s) with 1 file(s) remaining 
Completed 5.0 MiB/65.0 MiB (12.9 MiB/s) with 1 file(s) remaining 
Completed 5.2 MiB/65.0 MiB (13.2 MiB/s) with 1 file(s) remaining 
Completed 5.5 MiB/65.0 MiB (13.8 MiB/s) with 1 file(s) remaining 
Completed 5.8 MiB/65.0 MiB (14.4 MiB/s) with 1 file(s) remaining 
Completed 6.0 MiB/65.0 MiB (15.0 MiB/s) with 1 file(s) remaining 
Completed 6.2 MiB/65.0 MiB (15.6 MiB/s) with 1 file(s) remaining 
Completed 6.5 MiB/65.0 MiB (16.1 MiB/s) with 1 file(s) remaining 
Completed 6.8 MiB/65.0 MiB (16.7 MiB/s) with 1 file(s) remaining 
Completed 7.0 MiB/65.0 MiB (17.2 MiB/s) with 1 file(s) remaining 
Completed 7.2 MiB/65.0 MiB (17.4 MiB/s) with 1 file(s) remaining 
Completed 7.5 MiB/65.0 MiB (17.9 MiB/s) with 1 file(s) remaining 
Completed 7.8 MiB/65.0 MiB (18.1 MiB/s) with 1 file(s) remaining 
Completed 8.0 MiB/65.0 MiB (18.4 MiB/s) with 1 file(s) remaining 
Completed 8.2 MiB/65.0 MiB (18.9 MiB/s) with 1 file(s) remaining 
Completed 8.5 MiB/65.0 MiB (19.0 MiB/s) with 1 file(s) remaining 
Completed 8.8 MiB/65.0 MiB (19.4 MiB/s) with 1 file(s) remaining 
Completed 9.0 MiB/65.0 MiB (19.6 MiB/s) with 1 file(s) remaining 
Completed 9.2 MiB/65.0 MiB (20.0 MiB/s) with 1 file(s) remaining 
Completed 9.5 MiB/65.0 MiB (20.2 MiB/s) with 1 file(s) remaining 
Completed 9.8 MiB/65.0 MiB (20.5 MiB/s) with 1 file(s) remaining 
Completed 10.0 MiB/65.0 MiB (20.7 MiB/s) with 1 file(s) remaining
Completed 10.2 MiB/65.0 MiB (21.2 MiB/s) with 1 file(s) remaining
Completed 10.5 MiB/65.0 MiB (21.7 MiB/s) with 1 file(s) remaining
Completed 10.8 MiB/65.0 MiB (22.2 MiB/s) with 1 file(s) remaining
Completed 11.0 MiB/65.0 MiB (22.6 MiB/s) with 1 file(s) remaining
Completed 11.2 MiB/65.0 MiB (23.1 MiB/s) with 1 file(s) remaining
Completed 11.5 MiB/65.0 MiB (23.3 MiB/s) with 1 file(s) remaining
Completed 11.8 MiB/65.0 MiB (23.4 MiB/s) with 1 file(s) remaining
Completed 12.0 MiB/65.0 MiB (23.7 MiB/s) with 1 file(s) remaining
Completed 12.2 MiB/65.0 MiB (23.8 MiB/s) with 1 file(s) remaining
Completed 12.5 MiB/65.0 MiB (24.1 MiB/s) with 1 file(s) remaining
Completed 12.8 MiB/65.0 MiB (24.1 MiB/s) with 1 file(s) remaining
Completed 13.0 MiB/65.0 MiB (23.9 MiB/s) with 1 file(s) remaining
Completed 13.2 MiB/65.0 MiB (23.7 MiB/s) with 1 file(s) remaining
Completed 13.5 MiB/65.0 MiB (23.5 MiB/s) with 1 file(s) remaining
Completed 13.8 MiB/65.0 MiB (23.5 MiB/s) with 1 file(s) remaining
Completed 14.0 MiB/65.0 MiB (23.4 MiB/s) with 1 file(s) remaining
Completed 14.2 MiB/65.0 MiB (23.4 MiB/s) with 1 file(s) remaining
Completed 14.5 MiB/65.0 MiB (23.5 MiB/s) with 1 file(s) remaining
Completed 14.8 MiB/65.0 MiB (23.6 MiB/s) with 1 file(s) remaining
Completed 15.0 MiB/65.0 MiB (23.8 MiB/s) with 1 file(s) remaining
Completed 15.2 MiB/65.0 MiB (24.0 MiB/s) with 1 file(s) remaining
Completed 15.5 MiB/65.0 MiB (24.1 MiB/s) with 1 file(s) remaining
Completed 15.8 MiB/65.0 MiB (24.2 MiB/s) with 1 file(s) remaining
Completed 16.0 MiB/65.0 MiB (24.4 MiB/s) with 1 file(s) remaining
Completed 16.2 MiB/65.0 MiB (24.4 MiB/s) with 1 file(s) remaining
Completed 16.5 MiB/65.0 MiB (24.5 MiB/s) with 1 file(s) remaining
Completed 16.8 MiB/65.0 MiB (24.5 MiB/s) with 1 file(s) remaining
Completed 17.0 MiB/65.0 MiB (24.6 MiB/s) with 1 file(s) remaining
Completed 17.2 MiB/65.0 MiB (21.9 MiB/s) with 1 file(s) remaining
Completed 17.5 MiB/65.0 MiB (22.2 MiB/s) with 1 file(s) remaining
Completed 17.8 MiB/65.0 MiB (22.5 MiB/s) with 1 file(s) remaining
Completed 18.0 MiB/65.0 MiB (22.8 MiB/s) with 1 file(s) remaining
Completed 18.2 MiB/65.0 MiB (23.1 MiB/s) with 1 file(s) remaining
Completed 18.5 MiB/65.0 MiB (23.3 MiB/s) with 1 file(s) remaining
Completed 18.8 MiB/65.0 MiB (23.0 MiB/s) with 1 file(s) remaining
Completed 19.0 MiB/65.0 MiB (22.9 MiB/s) with 1 file(s) remaining
Completed 19.2 MiB/65.0 MiB (22.9 MiB/s) with 1 file(s) remaining
Completed 19.5 MiB/65.0 MiB (23.2 MiB/s) with 1 file(s) remaining
Completed 19.8 MiB/65.0 MiB (23.5 MiB/s) with 1 file(s) remaining
Completed 20.0 MiB/65.0 MiB (23.7 MiB/s) with 1 file(s) remaining
Completed 20.2 MiB/65.0 MiB (24.0 MiB/s) with 1 file(s) remaining
Completed 20.5 MiB/65.0 MiB (24.3 MiB/s) with 1 file(s) remaining
Completed 20.8 MiB/65.0 MiB (24.6 MiB/s) with 1 file(s) remaining
Completed 21.0 MiB/65.0 MiB (24.6 MiB/s) with 1 file(s) remaining
Completed 21.2 MiB/65.0 MiB (24.5 MiB/s) with 1 file(s) remaining
Completed 21.5 MiB/65.0 MiB (24.7 MiB/s) with 1 file(s) remaining
Completed 21.8 MiB/65.0 MiB (24.8 MiB/s) with 1 file(s) remaining
Completed 22.0 MiB/65.0 MiB (24.9 MiB/s) with 1 file(s) remaining
Completed 22.2 MiB/65.0 MiB (25.0 MiB/s) with 1 file(s) remaining
Completed 22.5 MiB/65.0 MiB (25.1 MiB/s) with 1 file(s) remaining
Completed 22.8 MiB/65.0 MiB (25.2 MiB/s) with 1 file(s) remaining
Completed 23.0 MiB/65.0 MiB (25.4 MiB/s) with 1 file(s) remaining
Completed 23.2 MiB/65.0 MiB (25.4 MiB/s) with 1 file(s) remaining
Completed 23.5 MiB/65.0 MiB (25.6 MiB/s) with 1 file(s) remaining
Completed 23.8 MiB/65.0 MiB (25.6 MiB/s) with 1 file(s) remaining
Completed 24.0 MiB/65.0 MiB (25.8 MiB/s) with 1 file(s) remaining
Completed 24.2 MiB/65.0 MiB (26.0 MiB/s) with 1 file(s) remaining
Completed 24.5 MiB/65.0 MiB (26.3 MiB/s) with 1 file(s) remaining
Completed 24.8 MiB/65.0 MiB (26.5 MiB/s) with 1 file(s) remaining
Completed 25.0 MiB/65.0 MiB (26.6 MiB/s) with 1 file(s) remaining
Completed 25.2 MiB/65.0 MiB (26.6 MiB/s) with 1 file(s) remaining
Completed 25.5 MiB/65.0 MiB (26.8 MiB/s) with 1 file(s) remaining
Completed 25.8 MiB/65.0 MiB (27.0 MiB/s) with 1 file(s) remaining
Completed 26.0 MiB/65.0 MiB (26.9 MiB/s) with 1 file(s) remaining
Completed 26.2 MiB/65.0 MiB (27.1 MiB/s) with 1 file(s) remaining
Completed 26.5 MiB/65.0 MiB (27.4 MiB/s) with 1 file(s) remaining
Completed 26.8 MiB/65.0 MiB (27.2 MiB/s) with 1 file(s) remaining
Completed 27.0 MiB/65.0 MiB (27.5 MiB/s) with 1 file(s) remaining
Completed 27.2 MiB/65.0 MiB (27.7 MiB/s) with 1 file(s) remaining
Completed 27.5 MiB/65.0 MiB (27.5 MiB/s) with 1 file(s) remaining
Completed 27.8 MiB/65.0 MiB (27.8 MiB/s) with 1 file(s) remaining
Completed 28.0 MiB/65.0 MiB (27.9 MiB/s) with 1 file(s) remaining
Completed 28.2 MiB/65.0 MiB (27.9 MiB/s) with 1 file(s) remaining
Completed 28.5 MiB/65.0 MiB (28.0 MiB/s) with 1 file(s) remaining
Completed 28.8 MiB/65.0 MiB (28.1 MiB/s) with 1 file(s) remaining
Completed 29.0 MiB/65.0 MiB (28.0 MiB/s) with 1 file(s) remaining
Completed 29.2 MiB/65.0 MiB (28.2 MiB/s) with 1 file(s) remaining
Completed 29.5 MiB/65.0 MiB (28.3 MiB/s) with 1 file(s) remaining
Completed 29.8 MiB/65.0 MiB (28.3 MiB/s) with 1 file(s) remaining
Completed 30.0 MiB/65.0 MiB (28.5 MiB/s) with 1 file(s) remaining
Completed 30.2 MiB/65.0 MiB (28.6 MiB/s) with 1 file(s) remaining
Completed 30.5 MiB/65.0 MiB (28.6 MiB/s) with 1 file(s) remaining
Completed 30.8 MiB/65.0 MiB (28.7 MiB/s) with 1 file(s) remaining
Completed 31.0 MiB/65.0 MiB (28.9 MiB/s) with 1 file(s) remaining
Completed 31.2 MiB/65.0 MiB (28.9 MiB/s) with 1 file(s) remaining
Completed 31.5 MiB/65.0 MiB (29.0 MiB/s) with 1 file(s) remaining
Completed 31.8 MiB/65.0 MiB (29.1 MiB/s) with 1 file(s) remaining
Completed 32.0 MiB/65.0 MiB (29.2 MiB/s) with 1 file(s) remaining
Completed 32.2 MiB/65.0 MiB (29.2 MiB/s) with 1 file(s) remaining
Completed 32.5 MiB/65.0 MiB (29.3 MiB/s) with 1 file(s) remaining
Completed 32.8 MiB/65.0 MiB (29.5 MiB/s) with 1 file(s) remaining
Completed 33.0 MiB/65.0 MiB (29.4 MiB/s) with 1 file(s) remaining
Completed 33.2 MiB/65.0 MiB (29.6 MiB/s) with 1 file(s) remaining
Completed 33.5 MiB/65.0 MiB (29.8 MiB/s) with 1 file(s) remaining
Completed 33.8 MiB/65.0 MiB (30.0 MiB/s) with 1 file(s) remaining
Completed 34.0 MiB/65.0 MiB (30.2 MiB/s) with 1 file(s) remaining
Completed 34.2 MiB/65.0 MiB (30.3 MiB/s) with 1 file(s) remaining
Completed 34.5 MiB/65.0 MiB (30.5 MiB/s) with 1 file(s) remaining
Completed 34.8 MiB/65.0 MiB (30.7 MiB/s) with 1 file(s) remaining
Completed 35.0 MiB/65.0 MiB (30.9 MiB/s) with 1 file(s) remaining
Completed 35.2 MiB/65.0 MiB (31.1 MiB/s) with 1 file(s) remaining
Completed 35.5 MiB/65.0 MiB (31.3 MiB/s) with 1 file(s) remaining
Completed 35.8 MiB/65.0 MiB (31.4 MiB/s) with 1 file(s) remaining
Completed 36.0 MiB/65.0 MiB (31.6 MiB/s) with 1 file(s) remaining
Completed 36.2 MiB/65.0 MiB (31.8 MiB/s) with 1 file(s) remaining
Completed 36.5 MiB/65.0 MiB (32.0 MiB/s) with 1 file(s) remaining
Completed 36.8 MiB/65.0 MiB (32.1 MiB/s) with 1 file(s) remaining
Completed 37.0 MiB/65.0 MiB (32.2 MiB/s) with 1 file(s) remaining
Completed 37.2 MiB/65.0 MiB (32.4 MiB/s) with 1 file(s) remaining
Completed 37.5 MiB/65.0 MiB (32.3 MiB/s) with 1 file(s) remaining
Completed 37.8 MiB/65.0 MiB (32.4 MiB/s) with 1 file(s) remaining
Completed 38.0 MiB/65.0 MiB (32.6 MiB/s) with 1 file(s) remaining
Completed 38.2 MiB/65.0 MiB (32.5 MiB/s) with 1 file(s) remaining
Completed 38.5 MiB/65.0 MiB (32.6 MiB/s) with 1 file(s) remaining
Completed 38.8 MiB/65.0 MiB (32.8 MiB/s) with 1 file(s) remaining
Completed 39.0 MiB/65.0 MiB (32.9 MiB/s) with 1 file(s) remaining
Completed 39.2 MiB/65.0 MiB (32.8 MiB/s) with 1 file(s) remaining
Completed 39.5 MiB/65.0 MiB (32.9 MiB/s) with 1 file(s) remaining
Completed 39.8 MiB/65.0 MiB (32.8 MiB/s) with 1 file(s) remaining
Completed 40.0 MiB/65.0 MiB (32.9 MiB/s) with 1 file(s) remaining
Completed 40.2 MiB/65.0 MiB (33.0 MiB/s) with 1 file(s) remaining
Completed 40.5 MiB/65.0 MiB (33.2 MiB/s) with 1 file(s) remaining
Completed 40.8 MiB/65.0 MiB (33.0 MiB/s) with 1 file(s) remaining
Completed 41.0 MiB/65.0 MiB (33.2 MiB/s) with 1 file(s) remaining
Completed 41.2 MiB/65.0 MiB (33.2 MiB/s) with 1 file(s) remaining
Completed 41.5 MiB/65.0 MiB (33.2 MiB/s) with 1 file(s) remaining
Completed 41.8 MiB/65.0 MiB (33.3 MiB/s) with 1 file(s) remaining
Completed 42.0 MiB/65.0 MiB (33.2 MiB/s) with 1 file(s) remaining
Completed 42.2 MiB/65.0 MiB (33.3 MiB/s) with 1 file(s) remaining
Completed 42.5 MiB/65.0 MiB (33.5 MiB/s) with 1 file(s) remaining
Completed 42.8 MiB/65.0 MiB (33.6 MiB/s) with 1 file(s) remaining
Completed 43.0 MiB/65.0 MiB (33.5 MiB/s) with 1 file(s) remaining
Completed 43.2 MiB/65.0 MiB (33.7 MiB/s) with 1 file(s) remaining
Completed 43.5 MiB/65.0 MiB (33.5 MiB/s) with 1 file(s) remaining
Completed 43.8 MiB/65.0 MiB (33.6 MiB/s) with 1 file(s) remaining
Completed 44.0 MiB/65.0 MiB (33.4 MiB/s) with 1 file(s) remaining
Completed 44.2 MiB/65.0 MiB (33.5 MiB/s) with 1 file(s) remaining
Completed 44.5 MiB/65.0 MiB (33.4 MiB/s) with 1 file(s) remaining
Completed 44.8 MiB/65.0 MiB (33.3 MiB/s) with 1 file(s) remaining
Completed 45.0 MiB/65.0 MiB (33.5 MiB/s) with 1 file(s) remaining
Completed 45.2 MiB/65.0 MiB (33.5 MiB/s) with 1 file(s) remaining
Completed 45.5 MiB/65.0 MiB (33.4 MiB/s) with 1 file(s) remaining
Completed 45.8 MiB/65.0 MiB (33.5 MiB/s) with 1 file(s) remaining
Completed 46.0 MiB/65.0 MiB (33.4 MiB/s) with 1 file(s) remaining
Completed 46.2 MiB/65.0 MiB (33.4 MiB/s) with 1 file(s) remaining
Completed 46.5 MiB/65.0 MiB (33.3 MiB/s) with 1 file(s) remaining
Completed 46.8 MiB/65.0 MiB (33.5 MiB/s) with 1 file(s) remaining
Completed 47.0 MiB/65.0 MiB (32.5 MiB/s) with 1 file(s) remaining
Completed 47.2 MiB/65.0 MiB (32.6 MiB/s) with 1 file(s) remaining
Completed 47.5 MiB/65.0 MiB (32.4 MiB/s) with 1 file(s) remaining
Completed 47.8 MiB/65.0 MiB (32.3 MiB/s) with 1 file(s) remaining
Completed 48.0 MiB/65.0 MiB (32.0 MiB/s) with 1 file(s) remaining
Completed 48.2 MiB/65.0 MiB (31.9 MiB/s) with 1 file(s) remaining
Completed 48.5 MiB/65.0 MiB (31.5 MiB/s) with 1 file(s) remaining
Completed 48.8 MiB/65.0 MiB (31.6 MiB/s) with 1 file(s) remaining
Completed 49.0 MiB/65.0 MiB (31.1 MiB/s) with 1 file(s) remaining
Completed 49.2 MiB/65.0 MiB (31.2 MiB/s) with 1 file(s) remaining
Completed 49.5 MiB/65.0 MiB (31.1 MiB/s) with 1 file(s) remaining
Completed 49.8 MiB/65.0 MiB (31.1 MiB/s) with 1 file(s) remaining
Completed 50.0 MiB/65.0 MiB (31.2 MiB/s) with 1 file(s) remaining
Completed 50.2 MiB/65.0 MiB (31.3 MiB/s) with 1 file(s) remaining
Completed 50.5 MiB/65.0 MiB (31.4 MiB/s) with 1 file(s) remaining
Completed 50.8 MiB/65.0 MiB (31.4 MiB/s) with 1 file(s) remaining
Completed 51.0 MiB/65.0 MiB (31.5 MiB/s) with 1 file(s) remaining
Completed 51.2 MiB/65.0 MiB (31.6 MiB/s) with 1 file(s) remaining
Completed 51.5 MiB/65.0 MiB (31.6 MiB/s) with 1 file(s) remaining
Completed 51.8 MiB/65.0 MiB (31.8 MiB/s) with 1 file(s) remaining
Completed 52.0 MiB/65.0 MiB (31.8 MiB/s) with 1 file(s) remaining
Completed 52.2 MiB/65.0 MiB (31.9 MiB/s) with 1 file(s) remaining
Completed 52.5 MiB/65.0 MiB (32.0 MiB/s) with 1 file(s) remaining
Completed 52.8 MiB/65.0 MiB (32.0 MiB/s) with 1 file(s) remaining
Completed 53.0 MiB/65.0 MiB (32.0 MiB/s) with 1 file(s) remaining
Completed 53.2 MiB/65.0 MiB (31.8 MiB/s) with 1 file(s) remaining
Completed 53.5 MiB/65.0 MiB (31.6 MiB/s) with 1 file(s) remaining
Completed 53.8 MiB/65.0 MiB (31.5 MiB/s) with 1 file(s) remaining
Completed 54.0 MiB/65.0 MiB (31.4 MiB/s) with 1 file(s) remaining
Completed 54.2 MiB/65.0 MiB (31.3 MiB/s) with 1 file(s) remaining
Completed 54.5 MiB/65.0 MiB (31.3 MiB/s) with 1 file(s) remaining
Completed 54.8 MiB/65.0 MiB (31.2 MiB/s) with 1 file(s) remaining
Completed 55.0 MiB/65.0 MiB (31.1 MiB/s) with 1 file(s) remaining
Completed 55.2 MiB/65.0 MiB (31.1 MiB/s) with 1 file(s) remaining
Completed 55.5 MiB/65.0 MiB (31.0 MiB/s) with 1 file(s) remaining
Completed 55.8 MiB/65.0 MiB (30.8 MiB/s) with 1 file(s) remaining
Completed 56.0 MiB/65.0 MiB (30.7 MiB/s) with 1 file(s) remaining
Completed 56.2 MiB/65.0 MiB (30.6 MiB/s) with 1 file(s) remaining
Completed 56.5 MiB/65.0 MiB (30.5 MiB/s) with 1 file(s) remaining
Completed 56.8 MiB/65.0 MiB (30.5 MiB/s) with 1 file(s) remaining
Completed 57.0 MiB/65.0 MiB (30.5 MiB/s) with 1 file(s) remaining
Completed 57.2 MiB/65.0 MiB (30.4 MiB/s) with 1 file(s) remaining
Completed 57.5 MiB/65.0 MiB (30.3 MiB/s) with 1 file(s) remaining
Completed 57.8 MiB/65.0 MiB (30.2 MiB/s) with 1 file(s) remaining
Completed 58.0 MiB/65.0 MiB (30.2 MiB/s) with 1 file(s) remaining
Completed 58.2 MiB/65.0 MiB (26.9 MiB/s) with 1 file(s) remaining
Completed 58.5 MiB/65.0 MiB (26.8 MiB/s) with 1 file(s) remaining
Completed 58.8 MiB/65.0 MiB (26.8 MiB/s) with 1 file(s) remaining
Completed 59.0 MiB/65.0 MiB (26.7 MiB/s) with 1 file(s) remaining
Completed 59.2 MiB/65.0 MiB (26.7 MiB/s) with 1 file(s) remaining
Completed 59.5 MiB/65.0 MiB (26.6 MiB/s) with 1 file(s) remaining
Completed 59.8 MiB/65.0 MiB (26.6 MiB/s) with 1 file(s) remaining
Completed 60.0 MiB/65.0 MiB (26.6 MiB/s) with 1 file(s) remaining
Completed 60.2 MiB/65.0 MiB (26.5 MiB/s) with 1 file(s) remaining
Completed 60.5 MiB/65.0 MiB (26.5 MiB/s) with 1 file(s) remaining
Completed 60.8 MiB/65.0 MiB (26.5 MiB/s) with 1 file(s) remaining
Completed 61.0 MiB/65.0 MiB (26.5 MiB/s) with 1 file(s) remaining
Completed 61.2 MiB/65.0 MiB (26.5 MiB/s) with 1 file(s) remaining
Completed 61.5 MiB/65.0 MiB (26.5 MiB/s) with 1 file(s) remaining
Completed 61.8 MiB/65.0 MiB (26.5 MiB/s) with 1 file(s) remaining
Completed 62.0 MiB/65.0 MiB (26.5 MiB/s) with 1 file(s) remaining
Completed 62.2 MiB/65.0 MiB (26.5 MiB/s) with 1 file(s) remaining
Completed 62.5 MiB/65.0 MiB (26.4 MiB/s) with 1 file(s) remaining
Completed 62.8 MiB/65.0 MiB (26.1 MiB/s) with 1 file(s) remaining
Completed 63.0 MiB/65.0 MiB (25.8 MiB/s) with 1 file(s) remaining
Completed 63.2 MiB/65.0 MiB (25.6 MiB/s) with 1 file(s) remaining
Completed 63.5 MiB/65.0 MiB (25.4 MiB/s) with 1 file(s) remaining
Completed 63.8 MiB/65.0 MiB (25.3 MiB/s) with 1 file(s) remaining
Completed 64.0 MiB/65.0 MiB (25.2 MiB/s) with 1 file(s) remaining
Completed 64.2 MiB/65.0 MiB (25.1 MiB/s) with 1 file(s) remaining
Completed 64.5 MiB/65.0 MiB (25.0 MiB/s) with 1 file(s) remaining
Completed 64.8 MiB/65.0 MiB (24.9 MiB/s) with 1 file(s) remaining
Completed 65.0 MiB/65.0 MiB (24.8 MiB/s) with 1 file(s) remaining
upload failed: ../../../data/datafile-65-MB to s3://awscli-mint-test-bucket-5336/datafile-65-MB An error occurred (InvalidPart) when calling the CompleteMultipartUpload operation: One or more of the specified parts could not be found.  The part may not have been uploaded, or the specified entity tag may not match the part's entity tag."}

Executed 4 out of 14 tests successfully.
```
<a name="c40a70bb-3771-4ba1-a263-89e5c2ef18b7"></a>
### 7960-9f9610d/mint-compression-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.57:31076
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp ddfefa3ec27e:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... FAILED in 13 seconds
{
  "alert": "",
  "args": {
    "bucketName": "aws-sdk-go-test-lzuwqhk4a9nmgk",
    "expiry": 60000000000,
    "objectName": "presignedTest"
  },
  "duration": 12528,
  "error": "RequestError: send request failed\ncaused by: Put http://72.28.97.57:31076/aws-sdk-go-test-lzuwqhk4a9nmgk: dial tcp 72.28.97.57:31076: connect: no route to host",
  "function": "PresignedPut",
  "message": "AWS SDK Go CreateBucket Failed",
  "name": "aws-sdk-go",
  "status": "FAIL"
}

Executed 0 out of 14 tests successfully.
```

File: pkg/event/target/webhook.go [hunk 1]
```diff
@@ -136,15 +137,16 @@ func (target *WebhookTarget) send(eventData event.Event) error {
 // Send - reads an event from store and sends it to webhook.
 func (target *WebhookTarget) Send(eventKey string) error {
 
-	urlStr, pErr := xnet.ParseURL(target.args.Endpoint.String())
+	u, pErr := xnet.ParseURL(target.args.Endpoint.String())
```
Comment (sinhaashish) [inline pkg/event/target/webhook.go:140]: Rename `u` to  `urlStr`

Comment (Praveenrajmani) [reply pkg/event/target/webhook.go:140]: I cannot have the variable name as `urlStr` because of 2 reasons.
- Its of type URL not string.
- I cannot use `url` as it clashes with url package alias.

**Comment by minio-ops** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-compression-xl.sh | :heavy_check_mark: |
| mint-xl.sh | :heavy_check_mark: |
| mint-compression-dist-xl.sh | :heavy_check_mark: |
| mint-compression-fs.sh | :heavy_check_mark: |
| mint-worm.sh | :heavy_check_mark: |
| mint-dist-xl.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :x: [more...](#9fd7237b-aa10-404f-9a53-5e15df55be2c) |
| mint-fs.sh | :x: [more...](#61c6a883-21b4-45e4-abe3-e936536706d0) |
<a name="9fd7237b-aa10-404f-9a53-5e15df55be2c"></a>
### 7960-4561f7f/mint-large-bucket.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.59:32596
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 1a87d505c524:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 3 seconds
(2/14) Running aws-sdk-java tests ... done in 2 seconds
(3/14) Running aws-sdk-php tests ... done in 50 seconds
(4/14) Running aws-sdk-ruby tests ... done in 11 seconds
(5/14) Running awscli tests ... done in 2 minutes and 30 seconds
(6/14) Running healthcheck tests ... done in 0 seconds
(7/14) Running mc tests ... FAILED in 2 minutes and 58 seconds
{
  "name": "mc",
  "duration": "136281",
  "function": "test_mirror_list_objects_storage_class",
  "status": "FAIL",
  "error": "/mint/run/core/mc/mc --config-dir /tmp/.mc-28930 --quiet --no-color mirror --storage-class REDUCED_REDUNDANCY /mint/data myminio/mc-test-bucket-18871  >>> \n`/mint/data/datafile-1-MB` -> `myminio/mc-test-bucket-18871/datafile-1-MB`\n`/mint/data/datafile-0-b` -> `myminio/mc-test-bucket-18871/datafile-0-b`\n`/mint/data/datafile-1-b` -> `myminio/mc-test-bucket-18871/datafile-1-b`\n`/mint/data/datafile-1.03-MB` -> `myminio/mc-test-bucket-18871/datafile-1.03-MB`\n`/mint/data/datafile-1-kB` -> `myminio/mc-test-bucket-18871/datafile-1-kB`\n`/mint/data/datafile-10-kB` -> `myminio/mc-test-bucket-18871/datafile-10-kB`\n`/mint/data/datafile-10-MB` -> `myminio/mc-test-bucket-18871/datafile-10-MB`\n`/mint/data/datafile-11-MB` -> `myminio/mc-test-bucket-18871/datafile-11-MB`\n`/mint/data/datafile-100-kB` -> `myminio/mc-test-bucket-18871/datafile-100-kB`\n`/mint/data/datafile-33-kB` -> `myminio/mc-test-bucket-18871/datafile-33-kB`\n`/mint/data/datafile-5243880-b` -> `myminio/mc-test-bucket-18871/datafile-5243880-b`\n`/mint/data/datafile-5-MB` -> `myminio/mc-test-bucket-18871/datafile-5-MB`\n`/mint/data/datafile-129-MB` -> `myminio/mc-test-bucket-18871/datafile-129-MB`\n`/mint/data/datafile-6-MB` -> `myminio/mc-test-bucket-18871/datafile-6-MB`\n`/mint/data/datafile-65-MB` -> `myminio/mc-test-bucket-18871/datafile-65-MB`\nmc: <ERROR> Failed to copy `/mint/data/datafile-11-MB`. Put http://72.28.97.59:32596/mc-test-bucket-18871/datafile-11-MB: read tcp 172.17.0.8:55328->72.28.97.59:32596: read: connection reset by peer\nmc: <ERROR> Failed to copy `/mint/data/datafile-129-MB`. Please reduce your request\nmc: <ERROR> Failed to copy `/mint/data/datafile-10-MB`. Please reduce your request\nmc: <ERROR> Failed to copy `/mint/data/datafile-65-MB`. Please reduce your request\nTotal: 233.17 MiB, Transferred: 539.12 MiB, Speed: 3.96 MiB/s"
}

Executed 6 out of 14 tests successfully.
```
<a name="61c6a883-21b4-45e4-abe3-e936536706d0"></a>
### 7960-4561f7f/mint-fs.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.57:32288
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp e914f17a16a9:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... FAILED in 12 seconds
{
  "alert": "",
  "args": {
    "bucketName": "aws-sdk-go-test-vtfushqzlrae1i",
    "expiry": 60000000000,
    "objectName": "presignedTest"
  },
  "duration": 12624,
  "error": "RequestError: send request failed\ncaused by: Put http://72.28.97.57:32288/aws-sdk-go-test-vtfushqzlrae1i: dial tcp 72.28.97.57:32288: connect: no route to host",
  "function": "PresignedPut",
  "message": "AWS SDK Go CreateBucket Failed",
  "name": "aws-sdk-go",
  "status": "FAIL"
}

Executed 0 out of 14 tests successfully.
```

**Review by sinhaashish — APPROVED** [review]
LGTM

**Review by harshavardhana — APPROVED** [review]

**Comment by minio-ops** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-compression-xl.sh | :heavy_check_mark: |
| mint-compression-fs.sh | :heavy_check_mark: |
| mint-worm.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-xl.sh | :x: [more...](#ee557a42-7da4-47f3-b667-0e82f8f52c40) |
| mint-large-bucket.sh | :x: [more...](#b72bfa44-cb74-4571-9de7-3f302619f234) |
| mint-compression-dist-xl.sh | :x: [more...](#fbcd6b5d-00c6-48d3-b0e9-3dcddbd69a50) |
| mint-dist-xl.sh | :x: [more...](#4fa07379-830b-4ef6-9fec-bb00f01a301e) |
<a name="4fa07379-830b-4ef6-9fec-bb00f01a301e"></a>
### 7960-3b8e767/mint-dist-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.53:30113
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 7e962907c0ec:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 1 seconds
(2/14) Running aws-sdk-java tests ... done in 1 seconds
(3/14) Running aws-sdk-php tests ... done in 48 seconds
(4/14) Running aws-sdk-ruby tests ... done in 3 seconds
(5/14) Running awscli tests ... done in 2 minutes and 2 seconds
(6/14) Running healthcheck tests ... done in 0 seconds
(7/14) Running mc tests ... done in 57 seconds
(8/14) Running minio-dotnet tests ... done in 34 seconds
(9/14) Running minio-go tests ... done in 1 minutes and 3 seconds
(10/14) Running minio-java tests ... done in 50 seconds
(11/14) Running minio-js tests ... done in 38 seconds
(12/14) Running minio-py tests ... FAILED in 11 seconds
{
  "function": "put_object(bucket_name, object_name, data, length, content_type, metadata, sse, progress, part_size)",
  "status": "FAIL",
  "error": "Traceback (most recent call last):\n  File \"/mint/run/core/minio-py/tests.py\", line 609, in test_put_object\n    sse=sse)\n  File \"/usr/local/lib/python3.5/dist-packages/minio/api.py\", line 827, in put_object\n    part_size=part_size)\n  File \"/usr/local/lib/python3.5/dist-packages/minio/api.py\", line 1659, in _stream_put_object\n    uploaded_parts)\n  File \"/usr/local/lib/python3.5/dist-packages/minio/api.py\", line 1745, in _complete_multipart_upload\n    content_sha256=sha256_hex)\n  File \"/usr/local/lib/python3.5/dist-packages/minio/api.py\", line 1901, in _url_open\n    object_name).get_exception()\nminio.error.InvalidPart: InvalidPart: message: One or more of the specified parts could not be found. The part might not have been uploaded, or the specified entity tag might not have matched the part's entity tag\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"/mint/run/core/minio-py/tests.py\", line 1854, in main\n    test_put_object(client, log_output)\n  File \"/mint/run/core/minio-py/tests.py\", line 623, in test_put_object\n    raise Exception(err)\nException: InvalidPart: message: One or more of the specified parts could not be found. The part might not have been uploaded, or the specified entity tag might not have matched the part's entity tag\n",
  "message": "InvalidPart: message: One or more of the specified parts could not be found. The part might not have been uploaded, or the specified entity tag might not have matched the part's entity tag",
  "args": {
    "metadata": {
      "x-amz-meta-testing": "value",
      "test-key": "value2"
    },
    "bucket_name": "minio-py-test-bfc9b3a3-eebd-4e23-827a-b4d42aa3608b",
    "length": 11534336,
    "data": "LimitedRandomReader(MB_11)",
    "object_name": "1fbd62ea-a849-4ab5-9987-ab2f50f937fc",
    "content_type": "application/octet-stream"
  },
  "duration": 7889,
  "name": "minio-py:test_put_object"
}

Executed 11 out of 14 tests successfully.
```
<a name="fbcd6b5d-00c6-48d3-b0e9-3dcddbd69a50"></a>
### 7960-3b8e767/mint-compression-dist-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.52:32079
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 941b03a0d36e:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 1 seconds
(2/14) Running aws-sdk-java tests ... done in 1 seconds
(3/14) Running aws-sdk-php tests ... done in 43 seconds
(4/14) Running aws-sdk-ruby tests ... done in 3 seconds
(5/14) Running awscli tests ... FAILED in 1 minutes and 2 seconds
{"name": "awscli", "duration": 9787, "function": "aws --endpoint-url http://72.28.97.52:32079 s3 sync /mint/data s3://awscli-mint-test-bucket-20374/\n", "status": "FAIL", "error": "upload: ../../../data/datafile-0-b to s3://awscli-mint-test-bucket-20374/datafile-0-bCompleted 0 Bytes/~157.2 MiB (0 Bytes/s) with ~11 file(s) remaining (calculating...)
Completed 256.0 KiB/233.2 MiB (4.2 MiB/s) with 14 file(s) remaining                 
Completed 512.0 KiB/233.2 MiB (7.5 MiB/s) with 14 file(s) remaining                 
Completed 512.0 KiB/233.2 MiB (7.3 MiB/s) with 14 file(s) remaining                 
upload: ../../../data/datafile-1-b to s3://awscli-mint-test-bucket-20374/datafile-1-bCompleted 512.0 KiB/233.2 MiB (7.3 MiB/s) with 13 file(s) remaining
Completed 768.0 KiB/233.2 MiB (10.6 MiB/s) with 13 file(s) remaining
Completed 1.0 MiB/233.2 MiB (14.0 MiB/s) with 13 file(s) remaining  
Completed 1.0 MiB/233.2 MiB (13.4 MiB/s) with 13 file(s) remaining  
upload: ../../../data/datafile-1-kB to s3://awscli-mint-test-bucket-20374/datafile-1-kBCompleted 1.0 MiB/233.2 MiB (13.4 MiB/s) with 12 file(s) remaining
Completed 1.3 MiB/233.2 MiB (16.5 MiB/s) with 12 file(s) remaining
Completed 1.5 MiB/233.2 MiB (19.7 MiB/s) with 12 file(s) remaining
Completed 1.8 MiB/233.2 MiB (21.9 MiB/s) with 12 file(s) remaining
Completed 1.8 MiB/233.2 MiB (20.7 MiB/s) with 12 file(s) remaining
upload: ../../../data/datafile-10-kB to s3://awscli-mint-test-bucket-20374/datafile-10-kBCompleted 1.8 MiB/233.2 MiB (20.7 MiB/s) with 11 file(s) remaining
Completed 2.0 MiB/233.2 MiB (23.1 MiB/s) with 11 file(s) remaining
Completed 2.0 MiB/233.2 MiB (20.7 MiB/s) with 11 file(s) remaining
upload: ../../../data/datafile-33-kB to s3://awscli-mint-test-bucket-20374/datafile-33-kBCompleted 2.0 MiB/233.2 MiB (20.7 MiB/s) with 10 file(s) remaining
Completed 2.1 MiB/233.2 MiB (20.4 MiB/s) with 10 file(s) remaining
upload: ../../../data/datafile-100-kB to s3://awscli-mint-test-bucket-20374/datafile-100-kBCompleted 2.1 MiB/233.2 MiB (20.4 MiB/s) with 9 file(s) remaining
upload: ../../../data/datafile-1-MB to s3://awscli-mint-test-bucket-20374/datafile-1-MBCompleted 2.1 MiB/233.2 MiB (20.4 MiB/s) with 8 file(s) remaining
Completed 2.4 MiB/233.2 MiB (20.1 MiB/s) with 8 file(s) remaining
Completed 2.6 MiB/233.2 MiB (21.6 MiB/s) with 8 file(s) remaining
Completed 2.7 MiB/233.2 MiB (21.2 MiB/s) with 8 file(s) remaining
upload: ../../../data/datafile-1.03-MB to s3://awscli-mint-test-bucket-20374/datafile-1.03-MBCompleted 2.7 MiB/233.2 MiB (21.2 MiB/s) with 7 file(s) remaining
Completed 2.9 MiB/233.2 MiB (22.9 MiB/s) with 7 file(s) remaining
Completed 3.2 MiB/233.2 MiB (24.8 MiB/s) with 7 file(s) remaining
Completed 3.4 MiB/233.2 MiB (25.7 MiB/s) with 7 file(s) remaining
Completed 3.7 MiB/233.2 MiB (27.5 MiB/s) with 7 file(s) remaining
Completed 3.9 MiB/233.2 MiB (28.7 MiB/s) with 7 file(s) remaining
Completed 4.2 MiB/233.2 MiB (30.5 MiB/s) with 7 file(s) remaining
Completed 4.4 MiB/233.2 MiB (31.5 MiB/s) with 7 file(s) remaining
Completed 4.7 MiB/233.2 MiB (33.2 MiB/s) with 7 file(s) remaining
Completed 4.9 MiB/233.2 MiB (34.3 MiB/s) with 7 file(s) remaining
Completed 5.2 MiB/233.2 MiB (35.5 MiB/s) with 7 file(s) remaining
Completed 5.4 MiB/233.2 MiB (37.2 MiB/s) with 7 file(s) remaining
Completed 5.7 MiB/233.2 MiB (38.0 MiB/s) with 7 file(s) remaining
Completed 5.9 MiB/233.2 MiB (38.5 MiB/s) with 7 file(s) remaining
Completed 6.2 MiB/233.2 MiB (40.0 MiB/s) with 7 file(s) remaining
Completed 6.4 MiB/233.2 MiB (40.9 MiB/s) with 7 file(s) remaining
Completed 6.7 MiB/233.2 MiB (42.4 MiB/s) with 7 file(s) remaining
Completed 6.9 MiB/233.2 MiB (43.6 MiB/s) with 7 file(s) remaining
Completed 7.2 MiB/233.2 MiB (44.7 MiB/s) with 7 file(s) remaining
Completed 7.4 MiB/233.2 MiB (45.4 MiB/s) with 7 file(s) remaining
Completed 7.7 MiB/233.2 MiB (46.5 MiB/s) with 7 file(s) remaining
Completed 7.9 MiB/233.2 MiB (47.5 MiB/s) with 7 file(s) remaining
Completed 8.2 MiB/233.2 MiB (48.2 MiB/s) with 7 file(s) remaining
Completed 8.4 MiB/233.2 MiB (49.2 MiB/s) with 7 file(s) remaining
Completed 8.7 MiB/233.2 MiB (50.4 MiB/s) with 7 file(s) remaining
Completed 8.9 MiB/233.2 MiB (51.8 MiB/s) with 7 file(s) remaining
Completed 9.2 MiB/233.2 MiB (52.2 MiB/s) with 7 file(s) remaining
Completed 9.4 MiB/233.2 MiB (52.6 MiB/s) with 7 file(s) remaining
Completed 9.7 MiB/233.2 MiB (53.8 MiB/s) with 7 file(s) remaining
Completed 9.9 MiB/233.2 MiB (54.9 MiB/s) with 7 file(s) remaining
Completed 10.2 MiB/233.2 MiB (56.0 MiB/s) with 7 file(s) remaining
Completed 10.4 MiB/233.2 MiB (55.0 MiB/s) with 7 file(s) remaining
Completed 10.7 MiB/233.2 MiB (56.1 MiB/s) with 7 file(s) remaining
Completed 10.9 MiB/233.2 MiB (57.3 MiB/s) with 7 file(s) remaining
Completed 11.2 MiB/233.2 MiB (57.3 MiB/s) with 7 file(s) remaining
Completed 11.4 MiB/233.2 MiB (58.3 MiB/s) with 7 file(s) remaining
Completed 11.7 MiB/233.2 MiB (58.7 MiB/s) with 7 file(s) remaining
Completed 11.9 MiB/233.2 MiB (59.6 MiB/s) with 7 file(s) remaining
Completed 12.2 MiB/233.2 MiB (60.7 MiB/s) with 7 file(s) remaining
Completed 12.4 MiB/233.2 MiB (59.5 MiB/s) with 7 file(s) remaining
Completed 12.7 MiB/233.2 MiB (60.4 MiB/s) with 7 file(s) remaining
Completed 12.9 MiB/233.2 MiB (61.4 MiB/s) with 7 file(s) remaining
Completed 13.2 MiB/233.2 MiB (62.5 MiB/s) with 7 file(s) remaining
Completed 13.4 MiB/233.2 MiB (63.2 MiB/s) with 7 file(s) remaining
Completed 13.7 MiB/233.2 MiB (63.8 MiB/s) with 7 file(s) remaining
Completed 13.9 MiB/233.2 MiB (64.1 MiB/s) with 7 file(s) remaining
Completed 14.2 MiB/233.2 MiB (64.3 MiB/s) with 7 file(s) remaining
Completed 14.4 MiB/233.2 MiB (64.4 MiB/s) with 7 file(s) remaining
Completed 14.7 MiB/233.2 MiB (64.9 MiB/s) with 7 file(s) remaining
Completed 14.9 MiB/233.2 MiB (65.5 MiB/s) with 7 file(s) remaining
Completed 15.2 MiB/233.2 MiB (66.0 MiB/s) with 7 file(s) remaining
Completed 15.4 MiB/233.2 MiB (66.8 MiB/s) with 7 file(s) remaining
Completed 15.7 MiB/233.2 MiB (67.3 MiB/s) with 7 file(s) remaining
Completed 15.9 MiB/233.2 MiB (67.5 MiB/s) with 7 file(s) remaining
Completed 16.2 MiB/233.2 MiB (67.4 MiB/s) with 7 file(s) remaining
Completed 16.4 MiB/233.2 MiB (68.1 MiB/s) with 7 file(s) remaining
Completed 16.7 MiB/233.2 MiB (67.6 MiB/s) with 7 file(s) remaining
Completed 16.9 MiB/233.2 MiB (68.5 MiB/s) with 7 file(s) remaining
Completed 17.2 MiB/233.2 MiB (69.0 MiB/s) with 7 file(s) remaining
Completed 17.4 MiB/233.2 MiB (69.4 MiB/s) with 7 file(s) remaining
Completed 17.7 MiB/233.2 MiB (69.3 MiB/s) with 7 file(s) remaining
Completed 17.9 MiB/233.2 MiB (70.0 MiB/s) with 7 file(s) remaining
Completed 18.2 MiB/233.2 MiB (69.9 MiB/s) with 7 file(s) remaining
Completed 18.4 MiB/233.2 MiB (70.4 MiB/s) with 7 file(s) remaining
Completed 18.7 MiB/233.2 MiB (71.2 MiB/s) with 7 file(s) remaining
Completed 18.9 MiB/233.2 MiB (70.5 MiB/s) with 7 file(s) remaining
Completed 19.2 MiB/233.2 MiB (70.5 MiB/s) with 7 file(s) remaining
Completed 19.4 MiB/233.2 MiB (71.3 MiB/s) with 7 file(s) remaining
Completed 19.7 MiB/233.2 MiB (71.8 MiB/s) with 7 file(s) remaining
Completed 19.9 MiB/233.2 MiB (72.1 MiB/s) with 7 file(s) remaining
Completed 20.2 MiB/233.2 MiB (72.7 MiB/s) with 7 file(s) remaining
Completed 20.4 MiB/233.2 MiB (72.1 MiB/s) with 7 file(s) remaining
Completed 20.7 MiB/233.2 MiB (72.6 MiB/s) with 7 file(s) remaining
Completed 20.9 MiB/233.2 MiB (72.8 MiB/s) with 7 file(s) remaining
Completed 21.2 MiB/233.2 MiB (73.6 MiB/s) with 7 file(s) remaining
Completed 21.4 MiB/233.2 MiB (74.0 MiB/s) with 7 file(s) remaining
Completed 21.7 MiB/233.2 MiB (74.6 MiB/s) with 7 file(s) remaining
Completed 21.9 MiB/233.2 MiB (73.6 MiB/s) with 7 file(s) remaining
Completed 22.2 MiB/233.2 MiB (73.8 MiB/s) with 7 file(s) remaining
Completed 22.4 MiB/233.2 MiB (74.2 MiB/s) with 7 file(s) remaining
Completed 22.7 MiB/233.2 MiB (74.8 MiB/s) with 7 file(s) remaining
Completed 22.9 MiB/233.2 MiB (73.1 MiB/s) with 7 file(s) remaining
Completed 23.2 MiB/233.2 MiB (73.7 MiB/s) with 7 file(s) remaining
Completed 23.4 MiB/233.2 MiB (74.5 MiB/s) with 7 file(s) remaining
Completed 23.7 MiB/233.2 MiB (74.2 MiB/s) with 7 file(s) remaining
Completed 23.9 MiB/233.2 MiB (73.6 MiB/s) with 7 file(s) remaining
Completed 24.2 MiB/233.2 MiB (74.1 MiB/s) with 7 file(s) remaining
Completed 24.4 MiB/233.2 MiB (74.7 MiB/s) with 7 file(s) remaining
Completed 24.7 MiB/233.2 MiB (74.2 MiB/s) with 7 file(s) remaining
Completed 24.9 MiB/233.2 MiB (74.8 MiB/s) with 7 file(s) remaining
Completed 25.2 MiB/233.2 MiB (74.8 MiB/s) with 7 file(s) remaining
Completed 25.4 MiB/233.2 MiB (75.1 MiB/s) with 7 file(s) remaining
Completed 25.7 MiB/233.2 MiB (75.0 MiB/s) with 7 file(s) remaining
Completed 25.9 MiB/233.2 MiB (74.9 MiB/s) with 7 file(s) remaining
Completed 26.2 MiB/233.2 MiB (75.0 MiB/s) with 7 file(s) remaining
Completed 26.4 MiB/233.2 MiB (75.2 MiB/s) with 7 file(s) remaining
Completed 26.7 MiB/233.2 MiB (75.1 MiB/s) with 7 file(s) remaining
Completed 26.9 MiB/233.2 MiB (74.4 MiB/s) with 7 file(s) remaining
Completed 27.2 MiB/233.2 MiB (74.8 MiB/s) with 7 file(s) remaining
Completed 27.4 MiB/233.2 MiB (75.2 MiB/s) with 7 file(s) remaining
Completed 27.7 MiB/233.2 MiB (75.4 MiB/s) with 7 file(s) remaining
Completed 27.9 MiB/233.2 MiB (74.9 MiB/s) with 7 file(s) remaining
Completed 28.2 MiB/233.2 MiB (74.6 MiB/s) with 7 file(s) remaining
Completed 28.4 MiB/233.2 MiB (75.1 MiB/s) with 7 file(s) remaining
Completed 28.7 MiB/233.2 MiB (75.3 MiB/s) with 7 file(s) remaining
Completed 28.9 MiB/233.2 MiB (75.6 MiB/s) with 7 file(s) remaining
Completed 29.2 MiB/233.2 MiB (75.2 MiB/s) with 7 file(s) remaining
Completed 29.4 MiB/233.2 MiB (75.7 MiB/s) with 7 file(s) remaining
Completed 29.7 MiB/233.2 MiB (75.6 MiB/s) with 7 file(s) remaining
Completed 29.9 MiB/233.2 MiB (75.8 MiB/s) with 7 file(s) remaining
Completed 30.2 MiB/233.2 MiB (75.9 MiB/s) with 7 file(s) remaining
Completed 30.4 MiB/233.2 MiB (76.2 MiB/s) with 7 file(s) remaining
Completed 30.7 MiB/233.2 MiB (76.4 MiB/s) with 7 file(s) remaining
Completed 30.9 MiB/233.2 MiB (76.2 MiB/s) with 7 file(s) remaining
Completed 31.2 MiB/233.2 MiB (76.2 MiB/s) with 7 file(s) remaining
Completed 31.4 MiB/233.2 MiB (76.7 MiB/s) with 7 file(s) remaining
Completed 31.7 MiB/233.2 MiB (76.1 MiB/s) with 7 file(s) remaining
Completed 31.9 MiB/233.2 MiB (76.5 MiB/s) with 7 file(s) remaining
Completed 32.2 MiB/233.2 MiB (76.8 MiB/s) with 7 file(s) remaining
Completed 32.4 MiB/233.2 MiB (77.3 MiB/s) with 7 file(s) remaining
Completed 32.7 MiB/233.2 MiB (77.4 MiB/s) with 7 file(s) remaining
Completed 32.9 MiB/233.2 MiB (76.8 MiB/s) with 7 file(s) remaining
Completed 33.2 MiB/233.2 MiB (76.8 MiB/s) with 7 file(s) remaining
Completed 33.4 MiB/233.2 MiB (77.3 MiB/s) with 7 file(s) remaining
Completed 33.7 MiB/233.2 MiB (76.9 MiB/s) with 7 file(s) remaining
Completed 33.9 MiB/233.2 MiB (77.4 MiB/s) with 7 file(s) remaining
Completed 34.2 MiB/233.2 MiB (77.0 MiB/s) with 7 file(s) remaining
Completed 34.4 MiB/233.2 MiB (77.2 MiB/s) with 7 file(s) remaining
Completed 34.7 MiB/233.2 MiB (77.6 MiB/s) with 7 file(s) remaining
Completed 34.9 MiB/233.2 MiB (77.3 MiB/s) with 7 file(s) remaining
Completed 35.2 MiB/233.2 MiB (77.1 MiB/s) with 7 file(s) remaining
Completed 35.4 MiB/233.2 MiB (77.4 MiB/s) with 7 file(s) remaining
Completed 35.7 MiB/233.2 MiB (77.8 MiB/s) with 7 file(s) remaining
Completed 35.9 MiB/233.2 MiB (78.3 MiB/s) with 7 file(s) remaining
Completed 36.2 MiB/233.2 MiB (77.7 MiB/s) with 7 file(s) remaining
Completed 36.4 MiB/233.2 MiB (78.2 MiB/s) with 7 file(s) remaining
Completed 36.4 MiB/233.2 MiB (77.7 MiB/s) with 7 file(s) remaining
upload: ../../../data/datafile-5243880-b to s3://awscli-mint-test-bucket-20374/datafile-5243880-bCompleted 36.4 MiB/233.2 MiB (77.7 MiB/s) with 6 file(s) remaining
Completed 36.7 MiB/233.2 MiB (78.0 MiB/s) with 6 file(s) remaining
Completed 36.9 MiB/233.2 MiB (78.5 MiB/s) with 6 file(s) remaining
Completed 37.2 MiB/233.2 MiB (79.0 MiB/s) with 6 file(s) remaining
upload: ../../../data/datafile-5-MB to s3://awscli-mint-test-bucket-20374/datafile-5-MBCompleted 37.2 MiB/233.2 MiB (79.0 MiB/s) with 5 file(s) remaining
Completed 37.4 MiB/233.2 MiB (78.8 MiB/s) with 5 file(s) remaining
Completed 37.7 MiB/233.2 MiB (79.0 MiB/s) with 5 file(s) remaining
Completed 37.9 MiB/233.2 MiB (79.3 MiB/s) with 5 file(s) remaining
Completed 38.2 MiB/233.2 MiB (79.4 MiB/s) with 5 file(s) remaining
Completed 38.4 MiB/233.2 MiB (79.8 MiB/s) with 5 file(s) remaining
Completed 38.7 MiB/233.2 MiB (80.0 MiB/s) with 5 file(s) remaining
Completed 38.9 MiB/233.2 MiB (80.0 MiB/s) with 5 file(s) remaining
Completed 39.2 MiB/233.2 MiB (80.5 MiB/s) with 5 file(s) remaining
Completed 39.4 MiB/233.2 MiB (80.3 MiB/s) with 5 file(s) remaining
Completed 39.7 MiB/233.2 MiB (80.2 MiB/s) with 5 file(s) remaining
Completed 39.9 MiB/233.2 MiB (80.6 MiB/s) with 5 file(s) remaining
Completed 40.2 MiB/233.2 MiB (80.6 MiB/s) with 5 file(s) remaining
Completed 40.4 MiB/233.2 MiB (81.1 MiB/s) with 5 file(s) remaining
Completed 40.7 MiB/233.2 MiB (80.4 MiB/s) with 5 file(s) remaining
Completed 40.9 MiB/233.2 MiB (80.5 MiB/s) with 5 file(s) remaining
Completed 41.2 MiB/233.2 MiB (80.9 MiB/s) with 5 file(s) remaining
Completed 41.4 MiB/233.2 MiB (81.1 MiB/s) with 5 file(s) remaining
Completed 41.7 MiB/233.2 MiB (80.9 MiB/s) with 5 file(s) remaining
Completed 41.9 MiB/233.2 MiB (81.1 MiB/s) with 5 file(s) remaining
Completed 42.2 MiB/233.2 MiB (81.4 MiB/s) with 5 file(s) remaining
Completed 42.4 MiB/233.2 MiB (81.0 MiB/s) with 5 file(s) remaining
Completed 42.7 MiB/233.2 MiB (81.3 MiB/s) with 5 file(s) remaining
Completed 42.9 MiB/233.2 MiB (81.1 MiB/s) with 5 file(s) remaining
Completed 43.2 MiB/233.2 MiB (80.9 MiB/s) with 5 file(s) remaining
Completed 43.4 MiB/233.2 MiB (81.1 MiB/s) with 5 file(s) remaining
Completed 43.7 MiB/233.2 MiB (81.2 MiB/s) with 5 file(s) remaining
Completed 43.9 MiB/233.2 MiB (80.9 MiB/s) with 5 file(s) remaining
Completed 44.2 MiB/233.2 MiB (80.8 MiB/s) with 5 file(s) remaining
Completed 44.4 MiB/233.2 MiB (81.0 MiB/s) with 5 file(s) remaining
Completed 44.7 MiB/233.2 MiB (80.9 MiB/s) with 5 file(s) remaining
Completed 44.9 MiB/233.2 MiB (80.6 MiB/s) with 5 file(s) remaining
Completed 45.2 MiB/233.2 MiB (80.7 MiB/s) with 5 file(s) remaining
Completed 45.4 MiB/233.2 MiB (80.8 MiB/s) with 5 file(s) remaining
Completed 45.7 MiB/233.2 MiB (81.1 MiB/s) with 5 file(s) remaining
Completed 45.9 MiB/233.2 MiB (80.6 MiB/s) with 5 file(s) remaining
Completed 46.2 MiB/233.2 MiB (81.0 MiB/s) with 5 file(s) remaining
Completed 46.4 MiB/233.2 MiB (81.1 MiB/s) with 5 file(s) remaining
Completed 46.7 MiB/233.2 MiB (81.3 MiB/s) with 5 file(s) remaining
Completed 46.9 MiB/233.2 MiB (80.7 MiB/s) with 5 file(s) remaining
Completed 47.2 MiB/233.2 MiB (80.9 MiB/s) with 5 file(s) remaining
Completed 47.4 MiB/233.2 MiB (81.0 MiB/s) with 5 file(s) remaining
Completed 47.7 MiB/233.2 MiB (81.3 MiB/s) with 5 file(s) remaining
Completed 47.9 MiB/233.2 MiB (80.9 MiB/s) with 5 file(s) remaining
Completed 48.2 MiB/233.2 MiB (81.0 MiB/s) with 5 file(s) remaining
Completed 48.4 MiB/233.2 MiB (81.2 MiB/s) with 5 file(s) remaining
Completed 48.7 MiB/233.2 MiB (81.5 MiB/s) with 5 file(s) remaining
Completed 48.9 MiB/233.2 MiB (80.7 MiB/s) with 5 file(s) remaining
Completed 49.2 MiB/233.2 MiB (81.1 MiB/s) with 5 file(s) remaining
Completed 49.4 MiB/233.2 MiB (81.3 MiB/s) with 5 file(s) remaining
Completed 49.7 MiB/233.2 MiB (81.7 MiB/s) with 5 file(s) remaining
Completed 49.9 MiB/233.2 MiB (81.1 MiB/s) with 5 file(s) remaining
Completed 50.2 MiB/233.2 MiB (81.3 MiB/s) with 5 file(s) remaining
Completed 50.4 MiB/233.2 MiB (81.6 MiB/s) with 5 file(s) remaining
Completed 50.7 MiB/233.2 MiB (81.7 MiB/s) with 5 file(s) remaining
Completed 50.9 MiB/233.2 MiB (81.6 MiB/s) with 5 file(s) remaining
Completed 51.2 MiB/233.2 MiB (81.6 MiB/s) with 5 file(s) remaining
Completed 51.4 MiB/233.2 MiB (81.9 MiB/s) with 5 file(s) remaining
Completed 51.7 MiB/233.2 MiB (81.8 MiB/s) with 5 file(s) remaining
Completed 51.9 MiB/233.2 MiB (81.9 MiB/s) with 5 file(s) remaining
Completed 52.2 MiB/233.2 MiB (81.6 MiB/s) with 5 file(s) remaining
Completed 52.4 MiB/233.2 MiB (81.7 MiB/s) with 5 file(s) remaining
Completed 52.7 MiB/233.2 MiB (81.8 MiB/s) with 5 file(s) remaining
Completed 52.9 MiB/233.2 MiB (81.6 MiB/s) with 5 file(s) remaining
Completed 53.2 MiB/233.2 MiB (81.8 MiB/s) with 5 file(s) remaining
Completed 53.4 MiB/233.2 MiB (81.5 MiB/s) with 5 file(s) remaining
Completed 53.7 MiB/233.2 MiB (81.6 MiB/s) with 5 file(s) remaining
Completed 53.9 MiB/233.2 MiB (81.0 MiB/s) with 5 file(s) remaining
Completed 54.2 MiB/233.2 MiB (81.4 MiB/s) with 5 file(s) remaining
upload: ../../../data/datafile-6-MB to s3://awscli-mint-test-bucket-20374/datafile-6-MBCompleted 54.2 MiB/233.2 MiB (81.4 MiB/s) with 4 file(s) remaining
Completed 54.4 MiB/233.2 MiB (80.8 MiB/s) with 4 file(s) remaining
Completed 54.7 MiB/233.2 MiB (80.7 MiB/s) with 4 file(s) remaining
Completed 54.9 MiB/233.2 MiB (80.7 MiB/s) with 4 file(s) remaining
Completed 55.2 MiB/233.2 MiB (80.1 MiB/s) with 4 file(s) remaining
Completed 55.4 MiB/233.2 MiB (80.4 MiB/s) with 4 file(s) remaining
Completed 55.7 MiB/233.2 MiB (79.8 MiB/s) with 4 file(s) remaining
Completed 55.9 MiB/233.2 MiB (80.0 MiB/s) with 4 file(s) remaining
Completed 56.2 MiB/233.2 MiB (79.7 MiB/s) with 4 file(s) remaining
Completed 56.4 MiB/233.2 MiB (79.4 MiB/s) with 4 file(s) remaining
Completed 56.7 MiB/233.2 MiB (79.6 MiB/s) with 4 file(s) remaining
Completed 56.9 MiB/233.2 MiB (79.4 MiB/s) with 4 file(s) remaining
Completed 57.2 MiB/233.2 MiB (79.3 MiB/s) with 4 file(s) remaining
Completed 57.4 MiB/233.2 MiB (79.4 MiB/s) with 4 file(s) remaining
Completed 57.7 MiB/233.2 MiB (79.1 MiB/s) with 4 file(s) remaining
Completed 57.9 MiB/233.2 MiB (79.2 MiB/s) with 4 file(s) remaining
Completed 58.2 MiB/233.2 MiB (79.1 MiB/s) with 4 file(s) remaining
Completed 58.4 MiB/233.2 MiB (78.8 MiB/s) with 4 file(s) remaining
Completed 58.7 MiB/233.2 MiB (79.0 MiB/s) with 4 file(s) remaining
Completed 58.9 MiB/233.2 MiB (78.7 MiB/s) with 4 file(s) remaining
Completed 59.2 MiB/233.2 MiB (78.6 MiB/s) with 4 file(s) remaining
Completed 59.4 MiB/233.2 MiB (78.6 MiB/s) with 4 file(s) remaining
Completed 59.7 MiB/233.2 MiB (78.2 MiB/s) with 4 file(s) remaining
Completed 59.9 MiB/233.2 MiB (78.5 MiB/s) with 4 file(s) remaining
Completed 60.2 MiB/233.2 MiB (77.7 MiB/s) with 4 file(s) remaining
Completed 60.4 MiB/233.2 MiB (77.4 MiB/s) with 4 file(s) remaining
Completed 60.7 MiB/233.2 MiB (76.9 MiB/s) with 4 file(s) remaining
Completed 60.9 MiB/233.2 MiB (76.6 MiB/s) with 4 file(s) remaining
Completed 61.2 MiB/233.2 MiB (76.2 MiB/s) with 4 file(s) remaining
Completed 61.4 MiB/233.2 MiB (75.9 MiB/s) with 4 file(s) remaining
Completed 61.7 MiB/233.2 MiB (75.5 MiB/s) with 4 file(s) remaining
Completed 61.9 MiB/233.2 MiB (75.0 MiB/s) with 4 file(s) remaining
Completed 62.2 MiB/233.2 MiB (74.6 MiB/s) with 4 file(s) remaining
Completed 62.4 MiB/233.2 MiB (74.2 MiB/s) with 4 file(s) remaining
Completed 62.7 MiB/233.2 MiB (73.9 MiB/s) with 4 file(s) remaining
Completed 62.9 MiB/233.2 MiB (73.3 MiB/s) with 4 file(s) remaining
Completed 63.2 MiB/233.2 MiB (73.3 MiB/s) with 4 file(s) remaining
Completed 63.4 MiB/233.2 MiB (55.8 MiB/s) with 4 file(s) remaining
Completed 63.7 MiB/233.2 MiB (55.8 MiB/s) with 4 file(s) remaining
Completed 63.9 MiB/233.2 MiB (55.8 MiB/s) with 4 file(s) remaining
Completed 64.2 MiB/233.2 MiB (55.8 MiB/s) with 4 file(s) remaining
Completed 64.4 MiB/233.2 MiB (55.9 MiB/s) with 4 file(s) remaining
Completed 64.7 MiB/233.2 MiB (55.9 MiB/s) with 4 file(s) remaining
Completed 64.9 MiB/233.2 MiB (56.0 MiB/s) with 4 file(s) remaining
Completed 65.2 MiB/233.2 MiB (56.1 MiB/s) with 4 file(s) remaining
Completed 65.4 MiB/233.2 MiB (56.2 MiB/s) with 4 file(s) remaining
Completed 65.7 MiB/233.2 MiB (56.3 MiB/s) with 4 file(s) remaining
Completed 65.9 MiB/233.2 MiB (56.4 MiB/s) with 4 file(s) remaining
Completed 66.2 MiB/233.2 MiB (56.4 MiB/s) with 4 file(s) remaining
Completed 66.4 MiB/233.2 MiB (56.5 MiB/s) with 4 file(s) remaining
Completed 66.7 MiB/233.2 MiB (56.6 MiB/s) with 4 file(s) remaining
Completed 66.9 MiB/233.2 MiB (56.7 MiB/s) with 4 file(s) remaining
Completed 67.2 MiB/233.2 MiB (56.8 MiB/s) with 4 file(s) remaining
Completed 67.4 MiB/233.2 MiB (56.9 MiB/s) with 4 file(s) remaining
Completed 67.7 MiB/233.2 MiB (57.0 MiB/s) with 4 file(s) remaining
Completed 67.9 MiB/233.2 MiB (57.1 MiB/s) with 4 file(s) remaining
Completed 68.2 MiB/233.2 MiB (57.2 MiB/s) with 4 file(s) remaining
Completed 68.4 MiB/233.2 MiB (57.3 MiB/s) with 4 file(s) remaining
Completed 68.7 MiB/233.2 MiB (57.5 MiB/s) with 4 file(s) remaining
Completed 68.9 MiB/233.2 MiB (57.6 MiB/s) with 4 file(s) remaining
Completed 69.2 MiB/233.2 MiB (57.8 MiB/s) with 4 file(s) remaining
Completed 69.4 MiB/233.2 MiB (57.9 MiB/s) with 4 file(s) remaining
Completed 69.7 MiB/233.2 MiB (58.1 MiB/s) with 4 file(s) remaining
Completed 69.9 MiB/233.2 MiB (58.3 MiB/s) with 4 file(s) remaining
Completed 70.2 MiB/233.2 MiB (58.4 MiB/s) with 4 file(s) remaining
Completed 70.4 MiB/233.2 MiB (58.6 MiB/s) with 4 file(s) remaining
Completed 70.7 MiB/233.2 MiB (58.7 MiB/s) with 4 file(s) remaining
Completed 70.9 MiB/233.2 MiB (58.9 MiB/s) with 4 file(s) remaining
Completed 71.2 MiB/233.2 MiB (59.0 MiB/s) with 4 file(s) remaining
Completed 71.4 MiB/233.2 MiB (59.1 MiB/s) with 4 file(s) remaining
Completed 71.7 MiB/233.2 MiB (59.2 MiB/s) with 4 file(s) remaining
Completed 71.9 MiB/233.2 MiB (59.4 MiB/s) with 4 file(s) remaining
Completed 72.2 MiB/233.2 MiB (59.4 MiB/s) with 4 file(s) remaining
Completed 72.4 MiB/233.2 MiB (59.5 MiB/s) with 4 file(s) remaining
Completed 72.7 MiB/233.2 MiB (59.6 MiB/s) with 4 file(s) remaining
Completed 72.9 MiB/233.2 MiB (59.8 MiB/s) with 4 file(s) remaining
Completed 73.2 MiB/233.2 MiB (59.8 MiB/s) with 4 file(s) remaining
Completed 73.4 MiB/233.2 MiB (59.9 MiB/s) with 4 file(s) remaining
Completed 73.7 MiB/233.2 MiB (60.0 MiB/s) with 4 file(s) remaining
Completed 73.9 MiB/233.2 MiB (60.1 MiB/s) with 4 file(s) remaining
Completed 74.2 MiB/233.2 MiB (60.1 MiB/s) with 4 file(s) remaining
Completed 74.4 MiB/233.2 MiB (60.3 MiB/s) with 4 file(s) remaining
Completed 74.7 MiB/233.2 MiB (60.3 MiB/s) with 4 file(s) remaining
Completed 74.9 MiB/233.2 MiB (60.5 MiB/s) with 4 file(s) remaining
Completed 75.2 MiB/233.2 MiB (60.5 MiB/s) with 4 file(s) remaining
Completed 75.4 MiB/233.2 MiB (60.4 MiB/s) with 4 file(s) remaining
Completed 75.7 MiB/233.2 MiB (60.5 MiB/s) with 4 file(s) remaining
Completed 75.9 MiB/233.2 MiB (60.5 MiB/s) with 4 file(s) remaining
Completed 76.2 MiB/233.2 MiB (60.6 MiB/s) with 4 file(s) remaining
Completed 76.4 MiB/233.2 MiB (60.6 MiB/s) with 4 file(s) remaining
Completed 76.7 MiB/233.2 MiB (60.7 MiB/s) with 4 file(s) remaining
Completed 76.9 MiB/233.2 MiB (60.8 MiB/s) with 4 file(s) remaining
Completed 77.2 MiB/233.2 MiB (60.9 MiB/s) with 4 file(s) remaining
Completed 77.4 MiB/233.2 MiB (60.9 MiB/s) with 4 file(s) remaining
Completed 77.7 MiB/233.2 MiB (61.1 MiB/s) with 4 file(s) remaining
Completed 77.9 MiB/233.2 MiB (61.1 MiB/s) with 4 file(s) remaining
Completed 78.2 MiB/233.2 MiB (61.2 MiB/s) with 4 file(s) remaining
Completed 78.4 MiB/233.2 MiB (61.3 MiB/s) with 4 file(s) remaining
Completed 78.7 MiB/233.2 MiB (61.3 MiB/s) with 4 file(s) remaining
Completed 78.9 MiB/233.2 MiB (61.4 MiB/s) with 4 file(s) remaining
Completed 79.2 MiB/233.2 MiB (61.4 MiB/s) with 4 file(s) remaining
upload: ../../../data/datafile-11-MB to s3://awscli-mint-test-bucket-20374/datafile-11-MBCompleted 79.2 MiB/233.2 MiB (61.4 MiB/s) with 3 file(s) remaining
Completed 79.4 MiB/233.2 MiB (51.8 MiB/s) with 3 file(s) remaining
Completed 79.7 MiB/233.2 MiB (51.9 MiB/s) with 3 file(s) remaining
Completed 79.9 MiB/233.2 MiB (52.1 MiB/s) with 3 file(s) remaining
Completed 80.2 MiB/233.2 MiB (52.2 MiB/s) with 3 file(s) remaining
Completed 80.4 MiB/233.2 MiB (52.3 MiB/s) with 3 file(s) remaining
Completed 80.7 MiB/233.2 MiB (52.2 MiB/s) with 3 file(s) remaining
Completed 80.9 MiB/233.2 MiB (52.4 MiB/s) with 3 file(s) remaining
Completed 81.2 MiB/233.2 MiB (52.5 MiB/s) with 3 file(s) remaining
Completed 81.4 MiB/233.2 MiB (52.6 MiB/s) with 3 file(s) remaining
Completed 81.7 MiB/233.2 MiB (52.8 MiB/s) with 3 file(s) remaining
Completed 81.9 MiB/233.2 MiB (52.9 MiB/s) with 3 file(s) remaining
Completed 82.2 MiB/233.2 MiB (53.0 MiB/s) with 3 file(s) remaining
Completed 82.4 MiB/233.2 MiB (53.2 MiB/s) with 3 file(s) remaining
Completed 82.7 MiB/233.2 MiB (53.3 MiB/s) with 3 file(s) remaining
Completed 82.9 MiB/233.2 MiB (53.5 MiB/s) with 3 file(s) remaining
Completed 83.2 MiB/233.2 MiB (53.6 MiB/s) with 3 file(s) remaining
Completed 83.4 MiB/233.2 MiB (53.7 MiB/s) with 3 file(s) remaining
Completed 83.7 MiB/233.2 MiB (53.8 MiB/s) with 3 file(s) remaining
upload: ../../../data/datafile-10-MB to s3://awscli-mint-test-bucket-20374/datafile-10-MBCompleted 83.7 MiB/233.2 MiB (53.8 MiB/s) with 2 file(s) remaining
Completed 83.9 MiB/233.2 MiB (53.7 MiB/s) with 2 file(s) remaining
Completed 84.2 MiB/233.2 MiB (53.8 MiB/s) with 2 file(s) remaining
Completed 84.4 MiB/233.2 MiB (54.0 MiB/s) with 2 file(s) remaining
Completed 84.7 MiB/233.2 MiB (54.1 MiB/s) with 2 file(s) remaining
Completed 84.9 MiB/233.2 MiB (54.1 MiB/s) with 2 file(s) remaining
Completed 85.2 MiB/233.2 MiB (54.2 MiB/s) with 2 file(s) remaining
Completed 85.4 MiB/233.2 MiB (54.3 MiB/s) with 2 file(s) remaining
Completed 85.7 MiB/233.2 MiB (54.5 MiB/s) with 2 file(s) remaining
Completed 85.9 MiB/233.2 MiB (54.5 MiB/s) with 2 file(s) remaining
Completed 86.2 MiB/233.2 MiB (54.6 MiB/s) with 2 file(s) remaining
Completed 86.4 MiB/233.2 MiB (54.6 MiB/s) with 2 file(s) remaining
Completed 86.7 MiB/233.2 MiB (54.7 MiB/s) with 2 file(s) remaining
Completed 86.9 MiB/233.2 MiB (54.9 MiB/s) with 2 file(s) remaining
Completed 87.2 MiB/233.2 MiB (55.0 MiB/s) with 2 file(s) remaining
Completed 87.4 MiB/233.2 MiB (55.1 MiB/s) with 2 file(s) remaining
Completed 87.7 MiB/233.2 MiB (55.1 MiB/s) with 2 file(s) remaining
Completed 87.9 MiB/233.2 MiB (55.2 MiB/s) with 2 file(s) remaining
Completed 88.2 MiB/233.2 MiB (55.4 MiB/s) with 2 file(s) remaining
Completed 88.4 MiB/233.2 MiB (55.4 MiB/s) with 2 file(s) remaining
Completed 88.7 MiB/233.2 MiB (55.5 MiB/s) with 2 file(s) remaining
Completed 88.9 MiB/233.2 MiB (55.6 MiB/s) with 2 file(s) remaining
Completed 89.2 MiB/233.2 MiB (55.7 MiB/s) with 2 file(s) remaining
Completed 89.4 MiB/233.2 MiB (55.7 MiB/s) with 2 file(s) remaining
Completed 89.7 MiB/233.2 MiB (55.8 MiB/s) with 2 file(s) remaining
Completed 89.9 MiB/233.2 MiB (55.8 MiB/s) with 2 file(s) remaining
Completed 90.2 MiB/233.2 MiB (56.0 MiB/s) with 2 file(s) remaining
Completed 90.4 MiB/233.2 MiB (56.1 MiB/s) with 2 file(s) remaining
Completed 90.7 MiB/233.2 MiB (56.1 MiB/s) with 2 file(s) remaining
Completed 90.9 MiB/233.2 MiB (56.1 MiB/s) with 2 file(s) remaining
Completed 91.2 MiB/233.2 MiB (56.3 MiB/s) with 2 file(s) remaining
Completed 91.4 MiB/233.2 MiB (56.4 MiB/s) with 2 file(s) remaining
Completed 91.7 MiB/233.2 MiB (56.5 MiB/s) with 2 file(s) remaining
Completed 91.9 MiB/233.2 MiB (56.5 MiB/s) with 2 file(s) remaining
Completed 92.2 MiB/233.2 MiB (56.6 MiB/s) with 2 file(s) remaining
Completed 92.4 MiB/233.2 MiB (56.7 MiB/s) with 2 file(s) remaining
Completed 92.7 MiB/233.2 MiB (56.8 MiB/s) with 2 file(s) remaining
Completed 92.9 MiB/233.2 MiB (56.9 MiB/s) with 2 file(s) remaining
Completed 93.2 MiB/233.2 MiB (56.9 MiB/s) with 2 file(s) remaining
Completed 93.4 MiB/233.2 MiB (57.0 MiB/s) with 2 file(s) remaining
Completed 93.7 MiB/233.2 MiB (57.1 MiB/s) with 2 file(s) remaining
Completed 93.9 MiB/233.2 MiB (57.0 MiB/s) with 2 file(s) remaining
Completed 94.2 MiB/233.2 MiB (57.1 MiB/s) with 2 file(s) remaining
Completed 94.4 MiB/233.2 MiB (57.1 MiB/s) with 2 file(s) remaining
Completed 94.7 MiB/233.2 MiB (57.2 MiB/s) with 2 file(s) remaining
Completed 94.9 MiB/233.2 MiB (57.2 MiB/s) with 2 file(s) remaining
Completed 95.2 MiB/233.2 MiB (57.3 MiB/s) with 2 file(s) remaining
Completed 95.4 MiB/233.2 MiB (57.5 MiB/s) with 2 file(s) remaining
Completed 95.7 MiB/233.2 MiB (57.5 MiB/s) with 2 file(s) remaining
Completed 95.9 MiB/233.2 MiB (57.5 MiB/s) with 2 file(s) remaining
Completed 96.2 MiB/233.2 MiB (57.7 MiB/s) with 2 file(s) remaining
Completed 96.4 MiB/233.2 MiB (57.8 MiB/s) with 2 file(s) remaining
Completed 96.7 MiB/233.2 MiB (57.8 MiB/s) with 2 file(s) remaining
Completed 96.9 MiB/233.2 MiB (57.9 MiB/s) with 2 file(s) remaining
Completed 97.2 MiB/233.2 MiB (58.0 MiB/s) with 2 file(s) remaining
Completed 97.4 MiB/233.2 MiB (58.1 MiB/s) with 2 file(s) remaining
Completed 97.7 MiB/233.2 MiB (58.1 MiB/s) with 2 file(s) remaining
Completed 97.9 MiB/233.2 MiB (58.2 MiB/s) with 2 file(s) remaining
Completed 98.2 MiB/233.2 MiB (58.2 MiB/s) with 2 file(s) remaining
Completed 98.4 MiB/233.2 MiB (58.3 MiB/s) with 2 file(s) remaining
Completed 98.7 MiB/233.2 MiB (58.5 MiB/s) with 2 file(s) remaining
Completed 98.9 MiB/233.2 MiB (58.4 MiB/s) with 2 file(s) remaining
Completed 99.2 MiB/233.2 MiB (58.4 MiB/s) with 2 file(s) remaining
Completed 99.4 MiB/233.2 MiB (58.5 MiB/s) with 2 file(s) remaining
Completed 99.7 MiB/233.2 MiB (58.6 MiB/s) with 2 file(s) remaining
Completed 99.9 MiB/233.2 MiB (58.7 MiB/s) with 2 file(s) remaining
Completed 100.2 MiB/233.2 MiB (58.8 MiB/s) with 2 file(s) remaining
Completed 100.4 MiB/233.2 MiB (58.8 MiB/s) with 2 file(s) remaining
Completed 100.7 MiB/233.2 MiB (58.8 MiB/s) with 2 file(s) remaining
Completed 100.9 MiB/233.2 MiB (58.9 MiB/s) with 2 file(s) remaining
Completed 101.2 MiB/233.2 MiB (58.9 MiB/s) with 2 file(s) remaining
Completed 101.4 MiB/233.2 MiB (58.9 MiB/s) with 2 file(s) remaining
Completed 101.7 MiB/233.2 MiB (58.9 MiB/s) with 2 file(s) remaining
Completed 101.9 MiB/233.2 MiB (59.0 MiB/s) with 2 file(s) remaining
Completed 102.2 MiB/233.2 MiB (59.2 MiB/s) with 2 file(s) remaining
Completed 102.4 MiB/233.2 MiB (59.1 MiB/s) with 2 file(s) remaining
Completed 102.7 MiB/233.2 MiB (59.1 MiB/s) with 2 file(s) remaining
Completed 102.9 MiB/233.2 MiB (58.9 MiB/s) with 2 file(s) remaining
Completed 103.2 MiB/233.2 MiB (59.0 MiB/s) with 2 file(s) remaining
Completed 103.4 MiB/233.2 MiB (59.1 MiB/s) with 2 file(s) remaining
Completed 103.7 MiB/233.2 MiB (59.2 MiB/s) with 2 file(s) remaining
Completed 103.9 MiB/233.2 MiB (59.2 MiB/s) with 2 file(s) remaining
Completed 104.2 MiB/233.2 MiB (59.3 MiB/s) with 2 file(s) remaining
Completed 104.4 MiB/233.2 MiB (59.3 MiB/s) with 2 file(s) remaining
Completed 104.7 MiB/233.2 MiB (59.4 MiB/s) with 2 file(s) remaining
Completed 104.9 MiB/233.2 MiB (59.5 MiB/s) with 2 file(s) remaining
Completed 105.2 MiB/233.2 MiB (59.5 MiB/s) with 2 file(s) remaining
Completed 105.4 MiB/233.2 MiB (59.5 MiB/s) with 2 file(s) remaining
Completed 105.7 MiB/233.2 MiB (59.5 MiB/s) with 2 file(s) remaining
Completed 105.9 MiB/233.2 MiB (59.6 MiB/s) with 2 file(s) remaining
Completed 106.2 MiB/233.2 MiB (59.7 MiB/s) with 2 file(s) remaining
Completed 106.4 MiB/233.2 MiB (59.6 MiB/s) with 2 file(s) remaining
Completed 106.7 MiB/233.2 MiB (59.7 MiB/s) with 2 file(s) remaining
Completed 106.9 MiB/233.2 MiB (59.7 MiB/s) with 2 file(s) remaining
Completed 107.2 MiB/233.2 MiB (59.8 MiB/s) with 2 file(s) remaining
Completed 107.4 MiB/233.2 MiB (59.8 MiB/s) with 2 file(s) remaining
Completed 107.7 MiB/233.2 MiB (60.0 MiB/s) with 2 file(s) remaining
Completed 107.9 MiB/233.2 MiB (59.8 MiB/s) with 2 file(s) remaining
Completed 108.2 MiB/233.2 MiB (59.9 MiB/s) with 2 file(s) remaining
Completed 108.4 MiB/233.2 MiB (60.0 MiB/s) with 2 file(s) remaining
Completed 108.7 MiB/233.2 MiB (60.1 MiB/s) with 2 file(s) remaining
Completed 108.9 MiB/233.2 MiB (60.3 MiB/s) with 2 file(s) remaining
Completed 109.2 MiB/233.2 MiB (60.2 MiB/s) with 2 file(s) remaining
Completed 109.4 MiB/233.2 MiB (60.1 MiB/s) with 2 file(s) remaining
Completed 109.7 MiB/233.2 MiB (60.2 MiB/s) with 2 file(s) remaining
Completed 109.9 MiB/233.2 MiB (60.3 MiB/s) with 2 file(s) remaining
Completed 110.2 MiB/233.2 MiB (60.4 MiB/s) with 2 file(s) remaining
Completed 110.4 MiB/233.2 MiB (60.4 MiB/s) with 2 file(s) remaining
Completed 110.7 MiB/233.2 MiB (60.5 MiB/s) with 2 file(s) remaining
Completed 110.9 MiB/233.2 MiB (60.6 MiB/s) with 2 file(s) remaining
Completed 111.2 MiB/233.2 MiB (60.6 MiB/s) with 2 file(s) remaining
Completed 111.4 MiB/233.2 MiB (60.6 MiB/s) with 2 file(s) remaining
Completed 111.7 MiB/233.2 MiB (60.7 MiB/s) with 2 file(s) remaining
Completed 111.9 MiB/233.2 MiB (60.7 MiB/s) with 2 file(s) remaining
Completed 112.2 MiB/233.2 MiB (60.8 MiB/s) with 2 file(s) remaining
Completed 112.4 MiB/233.2 MiB (60.7 MiB/s) with 2 file(s) remaining
Completed 112.7 MiB/233.2 MiB (60.8 MiB/s) with 2 file(s) remaining
Completed 112.9 MiB/233.2 MiB (60.8 MiB/s) with 2 file(s) remaining
Completed 113.2 MiB/233.2 MiB (60.9 MiB/s) with 2 file(s) remaining
Completed 113.4 MiB/233.2 MiB (61.0 MiB/s) with 2 file(s) remaining
Completed 113.7 MiB/233.2 MiB (61.0 MiB/s) with 2 file(s) remaining
Completed 113.9 MiB/233.2 MiB (61.0 MiB/s) with 2 file(s) remaining
Completed 114.2 MiB/233.2 MiB (61.1 MiB/s) with 2 file(s) remaining
Completed 114.4 MiB/233.2 MiB (61.1 MiB/s) with 2 file(s) remaining
Completed 114.7 MiB/233.2 MiB (61.2 MiB/s) with 2 file(s) remaining
Completed 114.9 MiB/233.2 MiB (61.2 MiB/s) with 2 file(s) remaining
Completed 115.2 MiB/233.2 MiB (61.2 MiB/s) with 2 file(s) remaining
Completed 115.4 MiB/233.2 MiB (61.3 MiB/s) with 2 file(s) remaining
Completed 115.7 MiB/233.2 MiB (61.3 MiB/s) with 2 file(s) remaining
Completed 115.9 MiB/233.2 MiB (61.3 MiB/s) with 2 file(s) remaining
Completed 116.2 MiB/233.2 MiB (61.4 MiB/s) with 2 file(s) remaining
Completed 116.4 MiB/233.2 MiB (61.5 MiB/s) with 2 file(s) remaining
Completed 116.7 MiB/233.2 MiB (61.6 MiB/s) with 2 file(s) remaining
Completed 116.9 MiB/233.2 MiB (61.6 MiB/s) with 2 file(s) remaining
Completed 117.2 MiB/233.2 MiB (61.6 MiB/s) with 2 file(s) remaining
Completed 117.4 MiB/233.2 MiB (61.6 MiB/s) with 2 file(s) remaining
Completed 117.7 MiB/233.2 MiB (61.6 MiB/s) with 2 file(s) remaining
Completed 117.9 MiB/233.2 MiB (61.8 MiB/s) with 2 file(s) remaining
Completed 118.2 MiB/233.2 MiB (61.9 MiB/s) with 2 file(s) remaining
Completed 118.4 MiB/233.2 MiB (61.9 MiB/s) with 2 file(s) remaining
Completed 118.7 MiB/233.2 MiB (61.9 MiB/s) with 2 file(s) remaining
Completed 118.9 MiB/233.2 MiB (62.0 MiB/s) with 2 file(s) remaining
Completed 119.2 MiB/233.2 MiB (62.0 MiB/s) with 2 file(s) remaining
Completed 119.4 MiB/233.2 MiB (62.1 MiB/s) with 2 file(s) remaining
Completed 119.7 MiB/233.2 MiB (62.2 MiB/s) with 2 file(s) remaining
Completed 119.9 MiB/233.2 MiB (62.3 MiB/s) with 2 file(s) remaining
Completed 120.2 MiB/233.2 MiB (62.4 MiB/s) with 2 file(s) remaining
Completed 120.4 MiB/233.2 MiB (62.5 MiB/s) with 2 file(s) remaining
Completed 120.7 MiB/233.2 MiB (62.6 MiB/s) with 2 file(s) remaining
Completed 120.9 MiB/233.2 MiB (62.7 MiB/s) with 2 file(s) remaining
Completed 121.2 MiB/233.2 MiB (62.8 MiB/s) with 2 file(s) remaining
Completed 121.4 MiB/233.2 MiB (62.8 MiB/s) with 2 file(s) remaining
Completed 121.7 MiB/233.2 MiB (62.8 MiB/s) with 2 file(s) remaining
Completed 121.9 MiB/233.2 MiB (62.9 MiB/s) with 2 file(s) remaining
Completed 122.2 MiB/233.2 MiB (63.0 MiB/s) with 2 file(s) remaining
Completed 122.4 MiB/233.2 MiB (62.9 MiB/s) with 2 file(s) remaining
Completed 122.7 MiB/233.2 MiB (63.0 MiB/s) with 2 file(s) remaining
Completed 122.9 MiB/233.2 MiB (63.0 MiB/s) with 2 file(s) remaining
Completed 123.2 MiB/233.2 MiB (63.1 MiB/s) with 2 file(s) remaining
Completed 123.4 MiB/233.2 MiB (63.2 MiB/s) with 2 file(s) remaining
Completed 123.7 MiB/233.2 MiB (63.3 MiB/s) with 2 file(s) remaining
Completed 123.9 MiB/233.2 MiB (63.3 MiB/s) with 2 file(s) remaining
Completed 124.2 MiB/233.2 MiB (63.4 MiB/s) with 2 file(s) remaining
Completed 124.4 MiB/233.2 MiB (63.3 MiB/s) with 2 file(s) remaining
Completed 124.7 MiB/233.2 MiB (63.4 MiB/s) with 2 file(s) remaining
Completed 124.9 MiB/233.2 MiB (63.4 MiB/s) with 2 file(s) remaining
Completed 125.2 MiB/233.2 MiB (63.6 MiB/s) with 2 file(s) remaining
Completed 125.4 MiB/233.2 MiB (63.7 MiB/s) with 2 file(s) remaining
Completed 125.7 MiB/233.2 MiB (63.8 MiB/s) with 2 file(s) remaining
Completed 125.9 MiB/233.2 MiB (63.9 MiB/s) with 2 file(s) remaining
Completed 126.2 MiB/233.2 MiB (63.7 MiB/s) with 2 file(s) remaining
Completed 126.4 MiB/233.2 MiB (63.7 MiB/s) with 2 file(s) remaining
Completed 126.7 MiB/233.2 MiB (63.7 MiB/s) with 2 file(s) remaining
Completed 126.9 MiB/233.2 MiB (63.8 MiB/s) with 2 file(s) remaining
Completed 127.2 MiB/233.2 MiB (63.9 MiB/s) with 2 file(s) remaining
Completed 127.4 MiB/233.2 MiB (63.9 MiB/s) with 2 file(s) remaining
Completed 127.7 MiB/233.2 MiB (64.0 MiB/s) with 2 file(s) remaining
Completed 127.9 MiB/233.2 MiB (64.0 MiB/s) with 2 file(s) remaining
Completed 128.2 MiB/233.2 MiB (64.1 MiB/s) with 2 file(s) remaining
Completed 128.4 MiB/233.2 MiB (64.2 MiB/s) with 2 file(s) remaining
Completed 128.7 MiB/233.2 MiB (64.3 MiB/s) with 2 file(s) remaining
Completed 128.9 MiB/233.2 MiB (64.3 MiB/s) with 2 file(s) remaining
Completed 129.2 MiB/233.2 MiB (64.3 MiB/s) with 2 file(s) remaining
Completed 129.4 MiB/233.2 MiB (64.3 MiB/s) with 2 file(s) remaining
Completed 129.7 MiB/233.2 MiB (64.3 MiB/s) with 2 file(s) remaining
Completed 129.9 MiB/233.2 MiB (64.5 MiB/s) with 2 file(s) remaining
Completed 130.2 MiB/233.2 MiB (64.5 MiB/s) with 2 file(s) remaining
Completed 130.4 MiB/233.2 MiB (64.6 MiB/s) with 2 file(s) remaining
Completed 130.7 MiB/233.2 MiB (64.6 MiB/s) with 2 file(s) remaining
Completed 130.9 MiB/233.2 MiB (64.6 MiB/s) with 2 file(s) remaining
Completed 131.2 MiB/233.2 MiB (64.5 MiB/s) with 2 file(s) remaining
Completed 131.4 MiB/233.2 MiB (64.6 MiB/s) with 2 file(s) remaining
Completed 131.7 MiB/233.2 MiB (64.6 MiB/s) with 2 file(s) remaining
Completed 131.9 MiB/233.2 MiB (64.7 MiB/s) with 2 file(s) remaining
Completed 132.2 MiB/233.2 MiB (64.7 MiB/s) with 2 file(s) remaining
Completed 132.4 MiB/233.2 MiB (64.6 MiB/s) with 2 file(s) remaining
Completed 132.7 MiB/233.2 MiB (64.8 MiB/s) with 2 file(s) remaining
Completed 132.9 MiB/233.2 MiB (64.8 MiB/s) with 2 file(s) remaining
Completed 133.2 MiB/233.2 MiB (64.9 MiB/s) with 2 file(s) remaining
Completed 133.4 MiB/233.2 MiB (65.0 MiB/s) with 2 file(s) remaining
Completed 133.7 MiB/233.2 MiB (64.8 MiB/s) with 2 file(s) remaining
Completed 133.9 MiB/233.2 MiB (64.9 MiB/s) with 2 file(s) remaining
Completed 134.2 MiB/233.2 MiB (65.0 MiB/s) with 2 file(s) remaining
Completed 134.4 MiB/233.2 MiB (65.0 MiB/s) with 2 file(s) remaining
Completed 134.7 MiB/233.2 MiB (65.0 MiB/s) with 2 file(s) remaining
Completed 134.9 MiB/233.2 MiB (65.1 MiB/s) with 2 file(s) remaining
Completed 135.2 MiB/233.2 MiB (64.9 MiB/s) with 2 file(s) remaining
Completed 135.4 MiB/233.2 MiB (65.0 MiB/s) with 2 file(s) remaining
Completed 135.7 MiB/233.2 MiB (65.1 MiB/s) with 2 file(s) remaining
Completed 135.9 MiB/233.2 MiB (65.1 MiB/s) with 2 file(s) remaining
Completed 136.2 MiB/233.2 MiB (65.2 MiB/s) with 2 file(s) remaining
Completed 136.4 MiB/233.2 MiB (65.2 MiB/s) with 2 file(s) remaining
Completed 136.7 MiB/233.2 MiB (65.3 MiB/s) with 2 file(s) remaining
Completed 136.9 MiB/233.2 MiB (65.3 MiB/s) with 2 file(s) remaining
Completed 137.2 MiB/233.2 MiB (65.3 MiB/s) with 2 file(s) remaining
Completed 137.4 MiB/233.2 MiB (65.3 MiB/s) with 2 file(s) remaining
Completed 137.7 MiB/233.2 MiB (65.3 MiB/s) with 2 file(s) remaining
Completed 137.9 MiB/233.2 MiB (65.4 MiB/s) with 2 file(s) remaining
Completed 138.2 MiB/233.2 MiB (65.4 MiB/s) with 2 file(s) remaining
Completed 138.4 MiB/233.2 MiB (65.3 MiB/s) with 2 file(s) remaining
Completed 138.7 MiB/233.2 MiB (65.3 MiB/s) with 2 file(s) remaining
Completed 138.9 MiB/233.2 MiB (65.4 MiB/s) with 2 file(s) remaining
Completed 139.2 MiB/233.2 MiB (65.4 MiB/s) with 2 file(s) remaining
Completed 139.4 MiB/233.2 MiB (65.4 MiB/s) with 2 file(s) remaining
Completed 139.7 MiB/233.2 MiB (65.4 MiB/s) with 2 file(s) remaining
Completed 139.9 MiB/233.2 MiB (65.3 MiB/s) with 2 file(s) remaining
Completed 140.2 MiB/233.2 MiB (65.3 MiB/s) with 2 file(s) remaining
Completed 140.4 MiB/233.2 MiB (65.4 MiB/s) with 2 file(s) remaining
Completed 140.7 MiB/233.2 MiB (65.5 MiB/s) with 2 file(s) remaining
Completed 140.9 MiB/233.2 MiB (65.6 MiB/s) with 2 file(s) remaining
Completed 141.2 MiB/233.2 MiB (65.7 MiB/s) with 2 file(s) remaining
Completed 141.4 MiB/233.2 MiB (65.7 MiB/s) with 2 file(s) remaining
Completed 141.7 MiB/233.2 MiB (65.8 MiB/s) with 2 file(s) remaining
Completed 141.9 MiB/233.2 MiB (65.9 MiB/s) with 2 file(s) remaining
Completed 142.2 MiB/233.2 MiB (66.0 MiB/s) with 2 file(s) remaining
Completed 142.4 MiB/233.2 MiB (66.1 MiB/s) with 2 file(s) remaining
Completed 142.7 MiB/233.2 MiB (66.2 MiB/s) with 2 file(s) remaining
Completed 142.9 MiB/233.2 MiB (66.2 MiB/s) with 2 file(s) remaining
Completed 143.2 MiB/233.2 MiB (66.3 MiB/s) with 2 file(s) remaining
Completed 143.4 MiB/233.2 MiB (66.4 MiB/s) with 2 file(s) remaining
Completed 143.7 MiB/233.2 MiB (66.5 MiB/s) with 2 file(s) remaining
Completed 143.9 MiB/233.2 MiB (66.4 MiB/s) with 2 file(s) remaining
Completed 144.2 MiB/233.2 MiB (66.4 MiB/s) with 2 file(s) remaining
Completed 144.4 MiB/233.2 MiB (66.5 MiB/s) with 2 file(s) remaining
Completed 144.7 MiB/233.2 MiB (66.6 MiB/s) with 2 file(s) remaining
Completed 144.9 MiB/233.2 MiB (66.5 MiB/s) with 2 file(s) remaining
Completed 145.2 MiB/233.2 MiB (66.5 MiB/s) with 2 file(s) remaining
Completed 145.4 MiB/233.2 MiB (66.6 MiB/s) with 2 file(s) remaining
Completed 145.7 MiB/233.2 MiB (66.7 MiB/s) with 2 file(s) remaining
Completed 145.9 MiB/233.2 MiB (66.7 MiB/s) with 2 file(s) remaining
Completed 146.2 MiB/233.2 MiB (66.8 MiB/s) with 2 file(s) remaining
Completed 146.4 MiB/233.2 MiB (67.0 MiB/s) with 2 file(s) remaining
Completed 146.7 MiB/233.2 MiB (67.0 MiB/s) with 2 file(s) remaining
Completed 146.9 MiB/233.2 MiB (67.1 MiB/s) with 2 file(s) remaining
Completed 147.2 MiB/233.2 MiB (67.0 MiB/s) with 2 file(s) remaining
Completed 147.4 MiB/233.2 MiB (67.0 MiB/s) with 2 file(s) remaining
Completed 147.7 MiB/233.2 MiB (67.1 MiB/s) with 2 file(s) remaining
Completed 147.9 MiB/233.2 MiB (67.1 MiB/s) with 2 file(s) remaining
Completed 148.2 MiB/233.2 MiB (67.1 MiB/s) with 2 file(s) remaining
Completed 148.4 MiB/233.2 MiB (67.1 MiB/s) with 2 file(s) remaining
Completed 148.7 MiB/233.2 MiB (67.2 MiB/s) with 2 file(s) remaining
Completed 148.9 MiB/233.2 MiB (67.0 MiB/s) with 2 file(s) remaining
Completed 149.2 MiB/233.2 MiB (67.1 MiB/s) with 2 file(s) remaining
Completed 149.4 MiB/233.2 MiB (67.1 MiB/s) with 2 file(s) remaining
Completed 149.7 MiB/233.2 MiB (67.1 MiB/s) with 2 file(s) remaining
Completed 149.9 MiB/233.2 MiB (67.2 MiB/s) with 2 file(s) remaining
Completed 150.2 MiB/233.2 MiB (67.3 MiB/s) with 2 file(s) remaining
Completed 150.4 MiB/233.2 MiB (67.2 MiB/s) with 2 file(s) remaining
Completed 150.7 MiB/233.2 MiB (67.2 MiB/s) with 2 file(s) remaining
Completed 150.9 MiB/233.2 MiB (67.2 MiB/s) with 2 file(s) remaining
Completed 151.2 MiB/233.2 MiB (67.2 MiB/s) with 2 file(s) remaining
Completed 151.4 MiB/233.2 MiB (67.2 MiB/s) with 2 file(s) remaining
Completed 151.7 MiB/233.2 MiB (67.2 MiB/s) with 2 file(s) remaining
Completed 151.9 MiB/233.2 MiB (67.3 MiB/s) with 2 file(s) remaining
Completed 152.2 MiB/233.2 MiB (67.3 MiB/s) with 2 file(s) remaining
Completed 152.4 MiB/233.2 MiB (67.4 MiB/s) with 2 file(s) remaining
Completed 152.7 MiB/233.2 MiB (67.4 MiB/s) with 2 file(s) remaining
Completed 152.9 MiB/233.2 MiB (67.5 MiB/s) with 2 file(s) remaining
Completed 153.2 MiB/233.2 MiB (67.4 MiB/s) with 2 file(s) remaining
Completed 153.4 MiB/233.2 MiB (67.5 MiB/s) with 2 file(s) remaining
Completed 153.7 MiB/233.2 MiB (67.6 MiB/s) with 2 file(s) remaining
Completed 153.9 MiB/233.2 MiB (67.6 MiB/s) with 2 file(s) remaining
Completed 154.2 MiB/233.2 MiB (67.7 MiB/s) with 2 file(s) remaining
Completed 154.4 MiB/233.2 MiB (67.7 MiB/s) with 2 file(s) remaining
Completed 154.7 MiB/233.2 MiB (67.6 MiB/s) with 2 file(s) remaining
Completed 154.9 MiB/233.2 MiB (67.7 MiB/s) with 2 file(s) remaining
Completed 155.2 MiB/233.2 MiB (67.8 MiB/s) with 2 file(s) remaining
Completed 155.4 MiB/233.2 MiB (67.8 MiB/s) with 2 file(s) remaining
Completed 155.7 MiB/233.2 MiB (67.8 MiB/s) with 2 file(s) remaining
Completed 155.9 MiB/233.2 MiB (67.9 MiB/s) with 2 file(s) remaining
Completed 156.2 MiB/233.2 MiB (67.8 MiB/s) with 2 file(s) remaining
Completed 156.4 MiB/233.2 MiB (67.9 MiB/s) with 2 file(s) remaining
Completed 156.7 MiB/233.2 MiB (67.9 MiB/s) with 2 file(s) remaining
Completed 156.9 MiB/233.2 MiB (68.0 MiB/s) with 2 file(s) remaining
Completed 157.2 MiB/233.2 MiB (68.0 MiB/s) with 2 file(s) remaining
Completed 157.4 MiB/233.2 MiB (67.9 MiB/s) with 2 file(s) remaining
Completed 157.7 MiB/233.2 MiB (67.9 MiB/s) with 2 file(s) remaining
Completed 157.9 MiB/233.2 MiB (68.0 MiB/s) with 2 file(s) remaining
Completed 158.2 MiB/233.2 MiB (68.0 MiB/s) with 2 file(s) remaining
Completed 158.4 MiB/233.2 MiB (68.1 MiB/s) with 2 file(s) remaining
Completed 158.7 MiB/233.2 MiB (68.1 MiB/s) with 2 file(s) remaining
Completed 158.9 MiB/233.2 MiB (68.1 MiB/s) with 2 file(s) remaining
Completed 159.2 MiB/233.2 MiB (68.1 MiB/s) with 2 file(s) remaining
Completed 159.4 MiB/233.2 MiB (68.1 MiB/s) with 2 file(s) remaining
Completed 159.7 MiB/233.2 MiB (68.2 MiB/s) with 2 file(s) remaining
Completed 159.9 MiB/233.2 MiB (68.3 MiB/s) with 2 file(s) remaining
Completed 160.2 MiB/233.2 MiB (68.3 MiB/s) with 2 file(s) remaining
Completed 160.4 MiB/233.2 MiB (68.2 MiB/s) with 2 file(s) remaining
Completed 160.7 MiB/233.2 MiB (68.2 MiB/s) with 2 file(s) remaining
Completed 160.9 MiB/233.2 MiB (68.3 MiB/s) with 2 file(s) remaining
Completed 161.2 MiB/233.2 MiB (68.1 MiB/s) with 2 file(s) remaining
Completed 161.4 MiB/233.2 MiB (68.2 MiB/s) with 2 file(s) remaining
Completed 161.7 MiB/233.2 MiB (68.1 MiB/s) with 2 file(s) remaining
Completed 161.9 MiB/233.2 MiB (68.2 MiB/s) with 2 file(s) remaining
Completed 162.2 MiB/233.2 MiB (68.1 MiB/s) with 2 file(s) remaining
Completed 162.4 MiB/233.2 MiB (68.2 MiB/s) with 2 file(s) remaining
Completed 162.7 MiB/233.2 MiB (68.1 MiB/s) with 2 file(s) remaining
Completed 162.9 MiB/233.2 MiB (68.1 MiB/s) with 2 file(s) remaining
Completed 163.2 MiB/233.2 MiB (68.2 MiB/s) with 2 file(s) remaining
Completed 163.4 MiB/233.2 MiB (68.0 MiB/s) with 2 file(s) remaining
Completed 163.7 MiB/233.2 MiB (68.1 MiB/s) with 2 file(s) remaining
Completed 163.9 MiB/233.2 MiB (68.2 MiB/s) with 2 file(s) remaining
Completed 164.2 MiB/233.2 MiB (68.2 MiB/s) with 2 file(s) remaining
Completed 164.4 MiB/233.2 MiB (68.3 MiB/s) with 2 file(s) remaining
Completed 164.7 MiB/233.2 MiB (68.4 MiB/s) with 2 file(s) remaining
Completed 164.9 MiB/233.2 MiB (68.4 MiB/s) with 2 file(s) remaining
Completed 165.2 MiB/233.2 MiB (68.4 MiB/s) with 2 file(s) remaining
Completed 165.4 MiB/233.2 MiB (68.4 MiB/s) with 2 file(s) remaining
Completed 165.7 MiB/233.2 MiB (68.5 MiB/s) with 2 file(s) remaining
Completed 165.9 MiB/233.2 MiB (68.4 MiB/s) with 2 file(s) remaining
Completed 166.2 MiB/233.2 MiB (68.4 MiB/s) with 2 file(s) remaining
Completed 166.4 MiB/233.2 MiB (68.2 MiB/s) with 2 file(s) remaining
Completed 166.7 MiB/233.2 MiB (68.3 MiB/s) with 2 file(s) remaining
Completed 166.9 MiB/233.2 MiB (68.4 MiB/s) with 2 file(s) remaining
Completed 167.2 MiB/233.2 MiB (68.3 MiB/s) with 2 file(s) remaining
Completed 167.4 MiB/233.2 MiB (68.1 MiB/s) with 2 file(s) remaining
Completed 167.7 MiB/233.2 MiB (68.2 MiB/s) with 2 file(s) remaining
Completed 167.9 MiB/233.2 MiB (68.2 MiB/s) with 2 file(s) remaining
Completed 168.2 MiB/233.2 MiB (68.2 MiB/s) with 2 file(s) remaining
Completed 168.4 MiB/233.2 MiB (68.1 MiB/s) with 2 file(s) remaining
Completed 168.7 MiB/233.2 MiB (68.1 MiB/s) with 2 file(s) remaining
Completed 168.9 MiB/233.2 MiB (67.9 MiB/s) with 2 file(s) remaining
Completed 169.2 MiB/233.2 MiB (67.9 MiB/s) with 2 file(s) remaining
Completed 169.4 MiB/233.2 MiB (67.8 MiB/s) with 2 file(s) remaining
Completed 169.7 MiB/233.2 MiB (67.6 MiB/s) with 2 file(s) remaining
Completed 169.9 MiB/233.2 MiB (67.3 MiB/s) with 2 file(s) remaining
Completed 170.2 MiB/233.2 MiB (67.2 MiB/s) with 2 file(s) remaining
Completed 170.4 MiB/233.2 MiB (67.1 MiB/s) with 2 file(s) remaining
Completed 170.7 MiB/233.2 MiB (67.0 MiB/s) with 2 file(s) remaining
Completed 170.9 MiB/233.2 MiB (66.9 MiB/s) with 2 file(s) remaining
Completed 171.2 MiB/233.2 MiB (66.9 MiB/s) with 2 file(s) remaining
Completed 171.4 MiB/233.2 MiB (66.8 MiB/s) with 2 file(s) remaining
Completed 171.7 MiB/233.2 MiB (66.8 MiB/s) with 2 file(s) remaining
Completed 171.9 MiB/233.2 MiB (66.7 MiB/s) with 2 file(s) remaining
Completed 172.2 MiB/233.2 MiB (66.7 MiB/s) with 2 file(s) remaining
Completed 172.4 MiB/233.2 MiB (66.6 MiB/s) with 2 file(s) remaining
Completed 172.7 MiB/233.2 MiB (66.6 MiB/s) with 2 file(s) remaining
Completed 172.9 MiB/233.2 MiB (66.5 MiB/s) with 2 file(s) remaining
Completed 173.2 MiB/233.2 MiB (66.5 MiB/s) with 2 file(s) remaining
Completed 173.4 MiB/233.2 MiB (66.5 MiB/s) with 2 file(s) remaining
Completed 173.7 MiB/233.2 MiB (66.4 MiB/s) with 2 file(s) remaining
Completed 173.9 MiB/233.2 MiB (66.4 MiB/s) with 2 file(s) remaining
Completed 174.2 MiB/233.2 MiB (66.5 MiB/s) with 2 file(s) remaining
Completed 174.4 MiB/233.2 MiB (66.3 MiB/s) with 2 file(s) remaining
Completed 174.7 MiB/233.2 MiB (66.3 MiB/s) with 2 file(s) remaining
Completed 174.9 MiB/233.2 MiB (66.4 MiB/s) with 2 file(s) remaining
Completed 175.2 MiB/233.2 MiB (66.3 MiB/s) with 2 file(s) remaining
Completed 175.4 MiB/233.2 MiB (66.3 MiB/s) with 2 file(s) remaining
Completed 175.7 MiB/233.2 MiB (66.4 MiB/s) with 2 file(s) remaining
Completed 175.9 MiB/233.2 MiB (66.4 MiB/s) with 2 file(s) remaining
Completed 176.2 MiB/233.2 MiB (66.4 MiB/s) with 2 file(s) remaining
Completed 176.4 MiB/233.2 MiB (66.4 MiB/s) with 2 file(s) remaining
Completed 176.7 MiB/233.2 MiB (66.3 MiB/s) with 2 file(s) remaining
Completed 176.9 MiB/233.2 MiB (66.2 MiB/s) with 2 file(s) remaining
Completed 177.2 MiB/233.2 MiB (66.1 MiB/s) with 2 file(s) remaining
Completed 177.4 MiB/233.2 MiB (66.1 MiB/s) with 2 file(s) remaining
Completed 177.7 MiB/233.2 MiB (66.0 MiB/s) with 2 file(s) remaining
Completed 177.9 MiB/233.2 MiB (65.9 MiB/s) with 2 file(s) remaining
Completed 178.2 MiB/233.2 MiB (65.9 MiB/s) with 2 file(s) remaining
Completed 178.4 MiB/233.2 MiB (65.9 MiB/s) with 2 file(s) remaining
Completed 178.7 MiB/233.2 MiB (65.9 MiB/s) with 2 file(s) remaining
Completed 178.9 MiB/233.2 MiB (65.9 MiB/s) with 2 file(s) remaining
Completed 179.2 MiB/233.2 MiB (65.8 MiB/s) with 2 file(s) remaining
Completed 179.4 MiB/233.2 MiB (65.8 MiB/s) with 2 file(s) remaining
Completed 179.7 MiB/233.2 MiB (65.8 MiB/s) with 2 file(s) remaining
Completed 179.9 MiB/233.2 MiB (65.9 MiB/s) with 2 file(s) remaining
Completed 180.2 MiB/233.2 MiB (65.9 MiB/s) with 2 file(s) remaining
Completed 180.4 MiB/233.2 MiB (65.9 MiB/s) with 2 file(s) remaining
Completed 180.7 MiB/233.2 MiB (66.0 MiB/s) with 2 file(s) remaining
Completed 180.9 MiB/233.2 MiB (65.9 MiB/s) with 2 file(s) remaining
Completed 181.2 MiB/233.2 MiB (65.9 MiB/s) with 2 file(s) remaining
Completed 181.4 MiB/233.2 MiB (65.9 MiB/s) with 2 file(s) remaining
Completed 181.7 MiB/233.2 MiB (65.9 MiB/s) with 2 file(s) remaining
Completed 181.9 MiB/233.2 MiB (65.8 MiB/s) with 2 file(s) remaining
Completed 182.2 MiB/233.2 MiB (65.9 MiB/s) with 2 file(s) remaining
Completed 182.4 MiB/233.2 MiB (65.8 MiB/s) with 2 file(s) remaining
Completed 182.7 MiB/233.2 MiB (65.8 MiB/s) with 2 file(s) remaining
Completed 182.9 MiB/233.2 MiB (65.9 MiB/s) with 2 file(s) remaining
Completed 183.2 MiB/233.2 MiB (65.8 MiB/s) with 2 file(s) remaining
Completed 183.4 MiB/233.2 MiB (65.7 MiB/s) with 2 file(s) remaining
Completed 183.7 MiB/233.2 MiB (65.8 MiB/s) with 2 file(s) remaining
Completed 183.9 MiB/233.2 MiB (65.8 MiB/s) with 2 file(s) remaining
Completed 184.2 MiB/233.2 MiB (65.7 MiB/s) with 2 file(s) remaining
Completed 184.4 MiB/233.2 MiB (65.7 MiB/s) with 2 file(s) remaining
Completed 184.7 MiB/233.2 MiB (65.8 MiB/s) with 2 file(s) remaining
Completed 184.9 MiB/233.2 MiB (65.7 MiB/s) with 2 file(s) remaining
Completed 185.2 MiB/233.2 MiB (65.8 MiB/s) with 2 file(s) remaining
Completed 185.4 MiB/233.2 MiB (65.8 MiB/s) with 2 file(s) remaining
Completed 185.7 MiB/233.2 MiB (65.9 MiB/s) with 2 file(s) remaining
Completed 185.9 MiB/233.2 MiB (65.8 MiB/s) with 2 file(s) remaining
Completed 186.2 MiB/233.2 MiB (65.8 MiB/s) with 2 file(s) remaining
Completed 186.4 MiB/233.2 MiB (65.8 MiB/s) with 2 file(s) remaining
Completed 186.7 MiB/233.2 MiB (65.7 MiB/s) with 2 file(s) remaining
Completed 186.9 MiB/233.2 MiB (65.7 MiB/s) with 2 file(s) remaining
Completed 187.2 MiB/233.2 MiB (65.7 MiB/s) with 2 file(s) remaining
Completed 187.4 MiB/233.2 MiB (65.7 MiB/s) with 2 file(s) remaining
Completed 187.7 MiB/233.2 MiB (65.6 MiB/s) with 2 file(s) remaining
Completed 187.9 MiB/233.2 MiB (65.6 MiB/s) with 2 file(s) remaining
Completed 188.2 MiB/233.2 MiB (65.6 MiB/s) with 2 file(s) remaining
Completed 188.4 MiB/233.2 MiB (65.5 MiB/s) with 2 file(s) remaining
Completed 188.7 MiB/233.2 MiB (65.5 MiB/s) with 2 file(s) remaining
Completed 188.9 MiB/233.2 MiB (65.6 MiB/s) with 2 file(s) remaining
Completed 189.2 MiB/233.2 MiB (65.6 MiB/s) with 2 file(s) remaining
Completed 189.4 MiB/233.2 MiB (65.6 MiB/s) with 2 file(s) remaining
Completed 189.7 MiB/233.2 MiB (65.6 MiB/s) with 2 file(s) remaining
Completed 189.9 MiB/233.2 MiB (65.6 MiB/s) with 2 file(s) remaining
Completed 190.2 MiB/233.2 MiB (65.6 MiB/s) with 2 file(s) remaining
Completed 190.4 MiB/233.2 MiB (65.6 MiB/s) with 2 file(s) remaining
Completed 190.7 MiB/233.2 MiB (65.6 MiB/s) with 2 file(s) remaining
Completed 190.9 MiB/233.2 MiB (65.6 MiB/s) with 2 file(s) remaining
Completed 191.2 MiB/233.2 MiB (65.6 MiB/s) with 2 file(s) remaining
Completed 191.4 MiB/233.2 MiB (64.8 MiB/s) with 2 file(s) remaining
Completed 191.7 MiB/233.2 MiB (64.9 MiB/s) with 2 file(s) remaining
Completed 191.9 MiB/233.2 MiB (64.9 MiB/s) with 2 file(s) remaining
Completed 192.2 MiB/233.2 MiB (64.9 MiB/s) with 2 file(s) remaining
Completed 192.4 MiB/233.2 MiB (64.9 MiB/s) with 2 file(s) remaining
Completed 192.7 MiB/233.2 MiB (64.9 MiB/s) with 2 file(s) remaining
Completed 192.9 MiB/233.2 MiB (64.9 MiB/s) with 2 file(s) remaining
Completed 193.2 MiB/233.2 MiB (64.9 MiB/s) with 2 file(s) remaining
Completed 193.4 MiB/233.2 MiB (64.9 MiB/s) with 2 file(s) remaining
Completed 193.7 MiB/233.2 MiB (64.9 MiB/s) with 2 file(s) remaining
Completed 193.9 MiB/233.2 MiB (64.9 MiB/s) with 2 file(s) remaining
Completed 194.2 MiB/233.2 MiB (64.9 MiB/s) with 2 file(s) remaining
Completed 194.4 MiB/233.2 MiB (64.9 MiB/s) with 2 file(s) remaining
Completed 194.7 MiB/233.2 MiB (64.9 MiB/s) with 2 file(s) remaining
Completed 194.9 MiB/233.2 MiB (64.9 MiB/s) with 2 file(s) remaining
Completed 195.2 MiB/233.2 MiB (64.9 MiB/s) with 2 file(s) remaining
Completed 195.4 MiB/233.2 MiB (64.9 MiB/s) with 2 file(s) remaining
Completed 195.7 MiB/233.2 MiB (64.9 MiB/s) with 2 file(s) remaining
Completed 195.9 MiB/233.2 MiB (65.0 MiB/s) with 2 file(s) remaining
Completed 196.2 MiB/233.2 MiB (65.0 MiB/s) with 2 file(s) remaining
Completed 196.4 MiB/233.2 MiB (65.0 MiB/s) with 2 file(s) remaining
Completed 196.7 MiB/233.2 MiB (65.0 MiB/s) with 2 file(s) remaining
Completed 196.9 MiB/233.2 MiB (65.1 MiB/s) with 2 file(s) remaining
Completed 197.2 MiB/233.2 MiB (65.1 MiB/s) with 2 file(s) remaining
Completed 197.4 MiB/233.2 MiB (65.2 MiB/s) with 2 file(s) remaining
Completed 197.7 MiB/233.2 MiB (65.3 MiB/s) with 2 file(s) remaining
Completed 197.9 MiB/233.2 MiB (65.3 MiB/s) with 2 file(s) remaining
Completed 198.2 MiB/233.2 MiB (65.3 MiB/s) with 2 file(s) remaining
Completed 198.4 MiB/233.2 MiB (65.3 MiB/s) with 2 file(s) remaining
Completed 198.7 MiB/233.2 MiB (65.3 MiB/s) with 2 file(s) remaining
Completed 198.9 MiB/233.2 MiB (65.3 MiB/s) with 2 file(s) remaining
Completed 199.2 MiB/233.2 MiB (65.4 MiB/s) with 2 file(s) remaining
Completed 199.4 MiB/233.2 MiB (65.4 MiB/s) with 2 file(s) remaining
Completed 199.7 MiB/233.2 MiB (65.5 MiB/s) with 2 file(s) remaining
Completed 199.9 MiB/233.2 MiB (65.5 MiB/s) with 2 file(s) remaining
Completed 200.2 MiB/233.2 MiB (65.5 MiB/s) with 2 file(s) remaining
Completed 200.4 MiB/233.2 MiB (65.5 MiB/s) with 2 file(s) remaining
Completed 200.7 MiB/233.2 MiB (65.5 MiB/s) with 2 file(s) remaining
Completed 200.9 MiB/233.2 MiB (65.6 MiB/s) with 2 file(s) remaining
Completed 201.2 MiB/233.2 MiB (65.6 MiB/s) with 2 file(s) remaining
Completed 201.4 MiB/233.2 MiB (65.6 MiB/s) with 2 file(s) remaining
Completed 201.7 MiB/233.2 MiB (65.7 MiB/s) with 2 file(s) remaining
Completed 201.9 MiB/233.2 MiB (65.7 MiB/s) with 2 file(s) remaining
Completed 202.2 MiB/233.2 MiB (65.8 MiB/s) with 2 file(s) remaining
Completed 202.4 MiB/233.2 MiB (65.8 MiB/s) with 2 file(s) remaining
Completed 202.7 MiB/233.2 MiB (65.8 MiB/s) with 2 file(s) remaining
Completed 202.9 MiB/233.2 MiB (65.8 MiB/s) with 2 file(s) remaining
Completed 203.2 MiB/233.2 MiB (65.9 MiB/s) with 2 file(s) remaining
Completed 203.4 MiB/233.2 MiB (65.9 MiB/s) with 2 file(s) remaining
Completed 203.7 MiB/233.2 MiB (65.9 MiB/s) with 2 file(s) remaining
Completed 203.9 MiB/233.2 MiB (66.0 MiB/s) with 2 file(s) remaining
Completed 204.2 MiB/233.2 MiB (66.0 MiB/s) with 2 file(s) remaining
Completed 204.4 MiB/233.2 MiB (66.0 MiB/s) with 2 file(s) remaining
Completed 204.7 MiB/233.2 MiB (66.0 MiB/s) with 2 file(s) remaining
Completed 204.9 MiB/233.2 MiB (66.0 MiB/s) with 2 file(s) remaining
Completed 205.2 MiB/233.2 MiB (66.0 MiB/s) with 2 file(s) remaining
Completed 205.4 MiB/233.2 MiB (66.0 MiB/s) with 2 file(s) remaining
Completed 205.7 MiB/233.2 MiB (66.0 MiB/s) with 2 file(s) remaining
Completed 205.9 MiB/233.2 MiB (66.0 MiB/s) with 2 file(s) remaining
Completed 206.2 MiB/233.2 MiB (66.1 MiB/s) with 2 file(s) remaining
Completed 206.4 MiB/233.2 MiB (66.1 MiB/s) with 2 file(s) remaining
Completed 206.7 MiB/233.2 MiB (66.1 MiB/s) with 2 file(s) remaining
Completed 206.9 MiB/233.2 MiB (66.1 MiB/s) with 2 file(s) remaining
Completed 207.2 MiB/233.2 MiB (66.1 MiB/s) with 2 file(s) remaining
Completed 207.4 MiB/233.2 MiB (65.2 MiB/s) with 2 file(s) remaining
Completed 207.7 MiB/233.2 MiB (65.2 MiB/s) with 2 file(s) remaining
Completed 207.9 MiB/233.2 MiB (65.3 MiB/s) with 2 file(s) remaining
Completed 208.2 MiB/233.2 MiB (65.3 MiB/s) with 2 file(s) remaining
Completed 208.4 MiB/233.2 MiB (65.2 MiB/s) with 2 file(s) remaining
Completed 208.7 MiB/233.2 MiB (65.2 MiB/s) with 2 file(s) remaining
Completed 208.9 MiB/233.2 MiB (65.2 MiB/s) with 2 file(s) remaining
Completed 209.2 MiB/233.2 MiB (65.2 MiB/s) with 2 file(s) remaining
Completed 209.4 MiB/233.2 MiB (65.1 MiB/s) with 2 file(s) remaining
Completed 209.7 MiB/233.2 MiB (65.1 MiB/s) with 2 file(s) remaining
Completed 209.9 MiB/233.2 MiB (65.1 MiB/s) with 2 file(s) remaining
Completed 210.2 MiB/233.2 MiB (65.1 MiB/s) with 2 file(s) remaining
Completed 210.4 MiB/233.2 MiB (65.1 MiB/s) with 2 file(s) remaining
Completed 210.7 MiB/233.2 MiB (65.1 MiB/s) with 2 file(s) remaining
Completed 210.9 MiB/233.2 MiB (65.1 MiB/s) with 2 file(s) remaining
Completed 211.2 MiB/233.2 MiB (65.1 MiB/s) with 2 file(s) remaining
Completed 211.4 MiB/233.2 MiB (65.1 MiB/s) with 2 file(s) remaining
Completed 211.7 MiB/233.2 MiB (65.1 MiB/s) with 2 file(s) remaining
Completed 211.9 MiB/233.2 MiB (65.2 MiB/s) with 2 file(s) remaining
Completed 212.2 MiB/233.2 MiB (65.2 MiB/s) with 2 file(s) remaining
Completed 212.4 MiB/233.2 MiB (65.2 MiB/s) with 2 file(s) remaining
Completed 212.7 MiB/233.2 MiB (65.2 MiB/s) with 2 file(s) remaining
Completed 212.9 MiB/233.2 MiB (65.2 MiB/s) with 2 file(s) remaining
Completed 213.2 MiB/233.2 MiB (65.2 MiB/s) with 2 file(s) remaining
Completed 213.4 MiB/233.2 MiB (65.2 MiB/s) with 2 file(s) remaining
Completed 213.7 MiB/233.2 MiB (65.2 MiB/s) with 2 file(s) remaining
Completed 213.9 MiB/233.2 MiB (65.2 MiB/s) with 2 file(s) remaining
Completed 214.2 MiB/233.2 MiB (65.3 MiB/s) with 2 file(s) remaining
Completed 214.4 MiB/233.2 MiB (65.3 MiB/s) with 2 file(s) remaining
Completed 214.7 MiB/233.2 MiB (65.3 MiB/s) with 2 file(s) remaining
Completed 214.9 MiB/233.2 MiB (65.3 MiB/s) with 2 file(s) remaining
Completed 215.2 MiB/233.2 MiB (65.4 MiB/s) with 2 file(s) remaining
Completed 215.4 MiB/233.2 MiB (63.6 MiB/s) with 2 file(s) remaining
Completed 215.7 MiB/233.2 MiB (63.6 MiB/s) with 2 file(s) remaining
Completed 215.9 MiB...Truncated

**Comment by minio-ops** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-compression-xl.sh | :heavy_check_mark: |
| mint-xl.sh | :heavy_check_mark: |
| mint-compression-dist-xl.sh | :heavy_check_mark: |
| mint-compression-fs.sh | :heavy_check_mark: |
| mint-worm.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :x: [more...](#297dc6dd-357d-4bee-8932-b87750cda222) |
| mint-dist-xl.sh | :x: [more...](#fc86f0e3-f5d6-4c73-8fb1-58bc02777a74) |
<a name="fc86f0e3-f5d6-4c73-8fb1-58bc02777a74"></a>
### 7960-99c94f8/mint-dist-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.57:32607
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 4eabfd691884:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... FAILED in 13 seconds
{
  "alert": "",
  "args": {
    "bucketName": "aws-sdk-go-test-ibbpsahvhc1nii",
    "expiry": 60000000000,
    "objectName": "presignedTest"
  },
  "duration": 12524,
  "error": "RequestError: send request failed\ncaused by: Put http://72.28.97.57:32607/aws-sdk-go-test-ibbpsahvhc1nii: dial tcp 72.28.97.57:32607: connect: no route to host",
  "function": "PresignedPut",
  "message": "AWS SDK Go CreateBucket Failed",
  "name": "aws-sdk-go",
  "status": "FAIL"
}

Executed 0 out of 14 tests successfully.
```
<a name="297dc6dd-357d-4bee-8932-b87750cda222"></a>
### 7960-99c94f8/mint-large-bucket.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.53:31423
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 0a5431623664:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 4 seconds
(2/14) Running aws-sdk-java tests ... done in 2 seconds
(3/14) Running aws-sdk-php tests ... done in 48 seconds
(4/14) Running aws-sdk-ruby tests ... done in 12 seconds
(5/14) Running awscli tests ... done in 2 minutes and 29 seconds
(6/14) Running healthcheck tests ... done in 0 seconds
(7/14) Running mc tests ... FAILED in 3 minutes and 4 seconds
{
  "name": "mc",
  "duration": "121535",
  "function": "test_mirror_list_objects_storage_class",
  "status": "FAIL",
  "error": "/mint/run/core/mc/mc --config-dir /tmp/.mc-2927 --quiet --no-color mirror --storage-class REDUCED_REDUNDANCY /mint/data myminio/mc-test-bucket-29319  >>> \n`/mint/data/datafile-1-MB` -> `myminio/mc-test-bucket-29319/datafile-1-MB`\n`/mint/data/datafile-1-kB` -> `myminio/mc-test-bucket-29319/datafile-1-kB`\n`/mint/data/datafile-0-b` -> `myminio/mc-test-bucket-29319/datafile-0-b`\n`/mint/data/datafile-1-b` -> `myminio/mc-test-bucket-29319/datafile-1-b`\n`/mint/data/datafile-10-MB` -> `myminio/mc-test-bucket-29319/datafile-10-MB`\n`/mint/data/datafile-100-kB` -> `myminio/mc-test-bucket-29319/datafile-100-kB`\n`/mint/data/datafile-10-kB` -> `myminio/mc-test-bucket-29319/datafile-10-kB`\n`/mint/data/datafile-1.03-MB` -> `myminio/mc-test-bucket-29319/datafile-1.03-MB`\n`/mint/data/datafile-11-MB` -> `myminio/mc-test-bucket-29319/datafile-11-MB`\n`/mint/data/datafile-129-MB` -> `myminio/mc-test-bucket-29319/datafile-129-MB`\n`/mint/data/datafile-33-kB` -> `myminio/mc-test-bucket-29319/datafile-33-kB`\n`/mint/data/datafile-5-MB` -> `myminio/mc-test-bucket-29319/datafile-5-MB`\n`/mint/data/datafile-5243880-b` -> `myminio/mc-test-bucket-29319/datafile-5243880-b`\n`/mint/data/datafile-6-MB` -> `myminio/mc-test-bucket-29319/datafile-6-MB`\n`/mint/data/datafile-65-MB` -> `myminio/mc-test-bucket-29319/datafile-65-MB`\nmc: <ERROR> Failed to copy `/mint/data/datafile-65-MB`. Please reduce your request\nmc: <ERROR> Failed to copy `/mint/data/datafile-129-MB`. Please reduce your request\nTotal: 233.17 MiB, Transferred: 552.93 MiB, Speed: 4.55 MiB/s"
}

Executed 6 out of 14 tests successfully.
```
