### PR TITLE
xl/bootup: Upon bootup handle errors loading bucket and event configs.

### LINKED ISSUE #3275: [distributed] Node fails to restart during round robin chaos test.
-  Under `exec-concurrent TestListPartiallyUploaded ` load at a concurrency of 5, one of the 7 nodes under chaos test fails to restart.
## Expected Behavior

- Gracefully restart during chaos test.
## Current Behavior

- Node6 fails to restart with the following error, 

```
time="2016-11-18T04:54:41Z" level=fatal msg="Unable to initialize event notification." cause="#has incomplete body" location="[routers.go]".

Nov 18 04:54:18 minio6.local.lan minio[7415]: time="2016-11-18T04:54:18Z" level=fatal msg="Unable to initialize event notification." cause="disk not found" location="

[routers.go:72:newObjectLayer()]" stack="xl-v1-utils.go:232:readXLMetaStat xl-v1-metadata.go:247:xlObjects.readXLMetaStat xl-v1-object.go:242:xlObjects.getObjectInfo xl-v1-object.go:232:xlObjects.GetObjectInfo <autogenerated>:861:(*xlObjects).GetObjectInfo event-

notifier.go:355:loadListenerConfig event-notifier.go:461:loadAllBucketNotifications event-notifier.go:628:initEventNotifier routers.go:71:newObjectLayer server-main.go:452:serverMain 

/root/work/src/github.com/minio/minio/vendor/github.com/minio/cli/command.go:117:github.com/minio/minio/vendor/github.com/minio/cli.Command.Run /root/work/src/github.com/minio/minio

/vendor/github.com/minio/cli/app.go:186:github.com/minio/minio/vendor/github.com/minio/cli.(*App).Run /root/work/src/github.com/minio/minio/vendor/github.com/minio

/cli/app.go:197:github.com/minio/minio/vendor/github.com/minio/cli.(*App).RunAndExitOnError main.go:225:Main /root/work/src/github.com/minio/minio/main.go:28:main.main /usr/local/go/src/runtime/proc.go:183:runtim
```
## Possible Solution

- Not sure.
## Steps to Reproduce (for bugs)

1. Run [Chaos test](https://github.com/minio/chaos). 
  ```sh
   ./master --endpoints="minio2:9997,minio3:9997,minio4:9997,minio5:9997,minio6:9997,minio7:9997,minio8:9997" -recover=1  -rounds=10 -minio-port=9199
   ```
2. Run [exec-concurrent TestListPartiallyUploaded](https://github.com/minio/perftest/tree/master/exec-concurrent) on the node1 (other 7 nodes are under round robin chaos test) at a CONCURRENCY of 5.

3. Go to each node and check `service minio status`

## Context

- Load test with nodes under chaos test.
## Your Environment

* Version used: Latest master at 05dc52a206a47abd71aa1d81e5eb3053285f034a .

### PR DESCRIPTION
**Pull request by harshavardhana**
## Description
In a situation when we have lots of buckets the bootup time
might have slowed down a bit but during this situation the
servers quickly going up and down would be an in-transit state.

Certain calls which do not use quorum like `readXLMetaStat`
might return an error saying `errDiskNotFound` this is returned
in place of expected `errFileNotFound` which leads to an issue
where server doesn't start.

To avoid this situation we need to ignore them as safe values
to be ignored, for the most part these are network related errors.

## Motivation and Context
Fixes #3275

## How Has This Been Tested?
Running through chaos test.

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by harshavardhana** [comment]
ping @hackintoshrao - we can test this patch. This should be fully ready for the behavior we have seen.

File: cmd/bucket-policy.go [hunk 1]
```diff
@@ -86,11 +85,15 @@ func loadAllBucketPolicies(objAPI ObjectLayer) (policies map[string]*bucketPolic
...
 		policy, pErr := readBucketPolicy(bucket.Name, objAPI)
 		if pErr != nil {
-			switch pErr.(type) {
-			case BucketPolicyNotFound:
-				continue
+			if !isErrIgnored(pErr, []error{
+				errDiskNotFound,
+			}) {
+				switch pErr.(type) {
+				case BucketPolicyNotFound:
```
Comment (donatello) [inline cmd/bucket-policy.go]: I think we can write a `isErrBucketPolicyNotFound()` like `isErrObjectNotFound()` and simplify this to remove the if and use just a switch statement.

File: cmd/net-rpc-client.go [hunk 2]
```diff
@@ -104,7 +115,12 @@ func (rpcClient *RPCClient) dialRPCClient() (*rpc.Client, error) {
 	if err == nil && resp.Status == "200 Connected to Go RPC" {
```
Comment (donatello) [inline cmd/net-rpc-client.go:115]: Ideally, we should restructure this part to be more idiomatic go - basically, filter out errors first and then process:

``` go
resp, err := http.ReadResponse(...)
if err != nil {
        // return error
}
if resp.Status != "200 ..." {
        // unexpected http status error
}
// now make and return rpc object.
```

It is better for readability, but it can be done later.

Comment (harshavardhana) [reply cmd/net-rpc-client.go:115]: The problem is conn.Close() cannot be handled properly.  This code is directly stolen from Go's own codebase.

File: cmd/bucket-policy.go (hunk 1 above)
Comment (harshavardhana) [reply cmd/bucket-policy.go]: Done

**Comment by harshavardhana** [comment]
Fixed and updated @donatello

**Comment by hackintoshrao** [comment]
Still 2 nodes failed with the following error, 
-  `time="2016-11-19T06:29:55Z" level=fatal msg="Unable to load all bucket policies." cause="dial-http minio8:9199 /minio/storage/tmp/rao2: dial tcp 147.75.203.123:9199: getsockopt: connection refused" location="[routers.go:68:newObjectLayer()]"
  Nov 19 06:29:55 minio6.local.lan systemd[1]: minio.service: Main process exited, code=exited, status=1/FAILURE`
- `Nov 19 06:29:53 minio4.local.lan minio[21076]: time="2016-11-19T06:29:53Z" level=fatal msg="Unable to initialize event notification." cause="dial-http minio7:9199 /minio/storage/tmp/rao2: dial tcp 147.75.201.49:9199: getsockopt: connection refused" location="[routers.go:72:newObjectLayer()]"
  Nov 19 06:29:53 minio4.local.lan systemd[1]: minio.service: Main process exited, code=exited, status=1/FAILURE`

**Comment by hackintoshrao** [comment]
the latest change has fixed the issue. LGTM.
