### PR TITLE
fix: can't get total disksize for `decom status`

### LINKED ISSUE #19545: First pool with minimal HA shows mc admin decommission status shows NaN
We have 2 pools in our minio cluster. 1 of these pools is added today. The main objective is to modernize the current cluster with higher spec VMs and more storage. So, we are planning to decommission the initial pool. However, when we run;
```shell
➜  ~ mc admin decommission status production
┌─────┬────────────────────────────────────────────────────────────────────┬──────────────────────┬────────┐
│ ID  │ Pools                                                              │ Raw Drives Usage     │ Status │
│ 1st │ https://pg-minio-2{0...3}.minio.mydomain.com:9000/minio/dat{1...1} │ NaN% (total: 0 B)    │ Active │
│ 2nd │ https://pg-minio-2{4...7}.minio.mydomain.com:9000/minio/dat{1...2} │ 0.7% (total: 26 TiB) │ Active │
└─────┴────────────────────────────────────────────────────────────────────┴──────────────────────┴────────┘
```
We see that the usage report for the first cluster is 0B. The cluster is up, running, and operational. The data is available. However, this wrong reporting in the status makes us worried to start the decommissioning.
## Expected Behavior
It should show around 5 TB of usage as it is visible in the UI;
Screenshot 2024-04-18 at 14 36 19

## Current Behavior
Showing NaN

## Steps to Reproduce (for bugs)

1. Initialize a cluster with single pool
2. Load some data
3. Add a new pool
4. Run `mc admin decommission status`

## Context
I will start decommissioning but I am worried that things will not go smooth.

## Your Environment

* Version used (`minio --version`): minio_20240406052602.0.0_amd64
* Server setup and configuration: 
```
➜  ~ mc admin info production
●  pg-minio-20.minio.mydomain.com:9000
   Uptime: 40 minutes
   Version: 2024-04-06T05:26:02Z
   Network: 8/8 OK
   Drives: 1/1 OK
   Pool: 1

●  pg-minio-21.minio.mydomain.com:9000
   Uptime: 40 minutes
   Version: 2024-04-06T05:26:02Z
   Network: 8/8 OK
   Drives: 1/1 OK
   Pool: 1

●  pg-minio-22.minio.mydomain.com:9000
   Uptime: 40 minutes
   Version: 2024-04-06T05:26:02Z
   Network: 8/8 OK
   Drives: 1/1 OK
   Pool: 1

●  pg-minio-23.minio.mydomain.com:9000
   Uptime: 40 minutes
   Version: 2024-04-06T05:26:02Z
   Network: 8/8 OK
   Drives: 1/1 OK
   Pool: 1

●  pg-minio-24.minio.mydomain.com:9000
   Uptime: 40 minutes
   Version: 2024-04-06T05:26:02Z
   Network: 8/8 OK
   Drives: 2/2 OK
   Pool: 2

●  pg-minio-25.minio.mydomain.com:9000
   Uptime: 40 minutes
   Version: 2024-04-06T05:26:02Z
   Network: 8/8 OK
   Drives: 2/2 OK
   Pool: 2

●  pg-minio-26.minio.mydomain.com:9000
   Uptime: 40 minutes
   Version: 2024-04-06T05:26:02Z
   Network: 8/8 OK
   Drives: 2/2 OK
   Pool: 2

●  pg-minio-27.minio.mydomain.com:9000
   Uptime: 40 minutes
   Version: 2024-04-06T05:26:02Z
   Network: 8/8 OK
   Drives: 2/2 OK
   Pool: 2

Pools:
   1st, Erasure sets: 1, Drives per erasure set: 4
   2nd, Erasure sets: 1, Drives per erasure set: 8

5.8 TiB Used, 67 Buckets, 66,463 Objects
12 drives online, 0 drives offline
```
* Operating System and version (`uname -a`): `Linux vm81gpeg 5.15.0-101-generic #111-Ubuntu SMP Tue Mar 5 20:16:58 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux`

### PR DESCRIPTION
**Pull request by jiuker**
```
		// Ignore parity disks
		if disk.DiskIndex < s.Backend.StandardSCData[disk.PoolIndex] {
			capacity += disk.TotalSpace
		}
```
Before this change. We use the latest pool parity. If we use `http://127.0.0.1:9000/workspace/go/src/minio/site/{1...4} http://127.0.0.1:9000/workspace/go/src/minio/site/{5...12}` to start minio.
 mc admin decommission status show a 0 totalSize.

```log
PS C:\workspace\go\src\minio> mc admin decommission status minio9000
┌─────┬────────────────────────────────────────────────────────────┬────────────────────────┬────────┐ 
│ ID  │ Pools                                                      │ Raw Drives Usage       │ Status │ 
│ 1st │ http://127.0.0.1:9000/workspace/go/src/minio/site/{1...4}  │ NaN% (total: 0 B)      │ Active │ 
│ 2nd │ http://127.0.0.1:9001/workspace/go/src/minio/site/{5...12} │ 34.1% (total: 1.9 TiB) │ Active │ 
└─────┴────────────────────────────────────────────────────────────┴────────────────────────┴────────┘ 
```

after this change 

```
PS C:\workspace\go\src\minio> mc admin decommission status minio9000       
┌─────┬────────────────────────────────────────────────────────────┬────────────────────────┬────────┐
│ ID  │ Pools                                                      │ Raw Drives Usage       │ Status │
│ 1st │ http://127.0.0.1:9000/workspace/go/src/minio/site/{1...4}  │ 34.2% (total: 953 GiB) │ Active │
│ 2nd │ http://127.0.0.1:9000/workspace/go/src/minio/site/{5...12} │ 34.2% (total: 2.8 TiB) │ Active │
└─────┴────────────────────────────────────────────────────────────┴────────────────────────┴────────┘
```

## Community Contribution License
All community contributions in this pull request are licensed to the project maintainers
under the terms of the [Apache 2 license](https://www.apache.org/licenses/LICENSE-2.0). 
By creating this pull request I represent that I have the right to license the 
contributions to the project maintainers under the Apache 2 license.

## Motivation and Context

fix https://github.com/minio/minio/issues/19545

## Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Optimization (provides speedup with no functional changes)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [ ] Fixes a regression (If yes, please add `commit-id` or `PR #` here)
- [ ] Unit tests added/updated
- [ ] Internal documentation updated
- [ ] Create a documentation update request [here](https://github.com/minio/docs/issues/new?label=doc-change,title=Doc+Updated+Needed+For+PR+github.com%2fminio%2fminio%2fpull%2fNNNNN)

### CODE REVIEW

File: cmd/config-current.go [hunk 1]
```diff
@@ -665,17 +665,16 @@ func applyDynamicConfigForSubSys(ctx context.Context, objAPI ObjectLayer, s conf
...
-		for i, setDriveCount := range setDriveCounts {
+		for _, setDriveCount := range setDriveCounts {
 			sc, err := storageclass.LookupConfig(s[config.StorageClassSubSys][config.Default], setDriveCount)
 			if err != nil {
 				configLogIf(ctx, fmt.Errorf("Unable to initialize storage class config: %w", err))
-				break
+			} else {
+				globalStorageClass.Update(sc)
 			}
 			// if we validated all setDriveCounts and it was successful
```
Comment (shtripat) [inline cmd/config-current.go]: This comment should move inside else part above?

**Review by harshavardhana — APPROVED** [review]

**Review by vadmeste — APPROVED** [review]
LGTM
