### PR TITLE
Fail to start server if detected cross-device mounts.

### LINKED ISSUE #4764: Exit during boot-up in case of cross device buckets
The issue is explained better in free form rather than issue template.

Currently if a bucket is a mount point, rename from `.minio.sys/tmp` to the bucket will fail with error EXDEV (Invalid cross-device link) Hence PutObject will fail during runtime.

Hence during bootup we should check if any of the bucket's `st_dev` obtained from the stat() syscall is different from the export directory. If any such bucket is found we should fail during the boot itself.

### PR DESCRIPTION
**Pull request by harshavardhana**
## Description
Fail to start server if detected cross-device mounts.

## Motivation and Context
Fixes #4764

## How Has This Been Tested?
Manually on both Linux and Windows.

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Review by krishnasrinivas — APPROVED** [review]

**Comment by krishnasrinivas** [comment]
Thinking more about the fix, it filters the bucket during list-buckets but does not do anything for other ops like putobject, newmultipart etc.

Better fix is we should show a user friendly message so that they can fix the problem themselves.

So better would be to show a message during bootup like:
`Ignoring bucket "soandso" because it is a mount point.`

**Comment by harshavardhana** [comment]
> Thinking more about the fix, it filters the bucket during list-buckets but does not do anything for other ops like putobject, newmultipart etc.
> 
> Better fix is we should show a user friendly message so that they can fix the problem themselves.
> 
> So better would be to show a message during bootup like:
> Ignoring bucket "soandso" because it is a mount point.

We had this messaging before about all ignored buckets but we couldn't arrive at a constructive sentence which would make sense and is actionable to the user.

**Comment by krishnasrinivas** [comment]
> We had this messaging before about all ignored buckets but we couldn't arrive at a constructive sentence which would make sense and is actionable to the user.

OK, we can discuss further on this issue with AB since just ignoring the buckets during list-buckets does not solve the problem i.e we don't give the user a message on what the problem is.

**Comment by harshavardhana** [comment]
Discussed this with @abperiasamy so we are going to refuse to start the server by detecting cross-device sub-mounts if they match with our export path.  Change the commit and have added code to look for this information. 

Please review @krishnasrinivas @vadmeste 

NOTE: Windows junction files are not supported yet. Haven't found an API to list and validate them just yet.

File: cmd/server-main.go [hunk 1]
```diff
@@ -223,8 +226,57 @@ func serverMain(ctx *cli.Context) {
...
+		// or minio has no permission to read it. In such cases
+		// we just treat it as success and hopefully report
+		// cross-device issues if any at a later stage.
+		if os.IsNotExist(err) || os.IsPermission(err) {
+			return nil, nil
+		}
+		return nil, err
+	}
+
+	var newMounts []mountinfo.MountPoint
```
Comment (vadmeste) [inline cmd/server-main.go]: @harshavardhana, you need to add the following code:
```
        prefix, err = filepath.Abs(prefix)
        if err != nil {
                return nil, err
        }
        prefix += string(filepath.Separator)
```

Using Abs() is more robust when comparing with mounted paths.

Besides, you need to add a separator because otherwise, the user cannot run 'minio server /tmp/fs' if there is another mounted directory which starts by fs, like /tmp/fsmount.

**Comment by vadmeste** [comment]
Isn't it an overkill to treat such case? I am in favor to add a FAQ in minio page which explains different errors that might be difficult to be understood by users.

File: cmd/server-main.go (hunk 1 above)
Comment (harshavardhana) [reply cmd/server-main.go]: Yes you are right. Let me add it.

**Comment by harshavardhana** [comment]
I think the reasoning is that it is perhaps better for us to detect these things since for the most part people do not read/understand Linux behavior and they deploy in remote instances where access to logging is hard to come by. If we indeed fail early on - mistakes can be avoided.

**Comment by vadmeste** [comment]
> I think the reasoning is that it is perhaps better for us to detect these things since for the most part people do not read/understand Linux behavior and they deploy in remote instances where access to logging is hard to come by. If we indeed fail early on - mistakes can be avoided.

Yeah, my point is that the code will become harder to read because it treats use cases that are not easy to understand in the first place.

**Comment by harshavardhana** [comment]
> Yeah, my point is that the code will become harder to read because it treats use cases that are not easy to understand in the first place.

which part is harder to read? you have to elaborate here so that it can be made easy on the eyes.

File: pkg/mountinfo/mountinfo.go [hunk 2]
```diff
@@ -0,0 +1,31 @@
...
+package mountinfo
+
+// MountPoint - This represents a single line in /proc/mounts.
+type MountPoint struct {
+	Device string
+	Path   string
+	Type   string
+	Opts   []string
+	Freq   int
+	Pass   int
```
Comment (balamurugana) [inline pkg/mountinfo/mountinfo.go]: You could keep freq and pass as string only to avoid parsing errors.  Let the consumer takes care of it.

File: pkg/mountinfo/mountinfo.go [hunk 3]
```diff
@@ -0,0 +1,31 @@
...
+ * distributed under the License is distributed on an "AS IS" BASIS,
+ * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
+ * See the License for the specific language governing permissions and
+ * limitations under the License.
+ */
+
+package mountinfo
+
+// MountPoint - This represents a single line in /proc/mounts.
+type MountPoint struct {
```
Comment (balamurugana) [inline pkg/mountinfo/mountinfo.go]: `MountInfo` is more appropriate than `MountInfo`

File: pkg/mountinfo/mountinfo.go [hunk 4]
```diff
@@ -0,0 +1,31 @@
...
+	Device string
+	Path   string
+	Type   string
```
Comment (balamurugana) [inline pkg/mountinfo/mountinfo.go]: `FSType` is more appropriate

File: pkg/mountinfo/mountinfo.go [hunk 5]
```diff
@@ -0,0 +1,31 @@
...
+	Opts   []string
```
Comment (balamurugana) [inline pkg/mountinfo/mountinfo.go]: You could expand the name to `Options`

File: pkg/mountinfo/mountinfo_linux.go [hunk 6]
```diff
@@ -0,0 +1,90 @@
...
+
+// MountInfo - returns a list of all mounted filesystems.
+func MountInfo() (mps []MountPoint, err error) {
+	err = readProcMounts(procMountsPath, &mps)
+	return mps, err
+}
+
+// readProcMounts reads the given mountFilePath (normally /proc/mounts) and produces a hash
+// of the contents.  If the out argument is not nil, this fills it with MountPoint structs.
+func readProcMounts(mountFilePath string, out *[]MountPoint) error {
```
Comment (balamurugana) [inline pkg/mountinfo/mountinfo_linux.go]: `readProcMounts()` returning `[]MountPoint` is much cleaner signature.

File: pkg/mountinfo/mountinfo_linux.go [hunk 7]
```diff
@@ -0,0 +1,90 @@
...
+	file, err := os.Open(mountFilePath)
+	if err != nil {
+		return err
+	}
+	defer file.Close()
+	return readProcMountsFrom(file, out)
+}
+
+func readProcMountsFrom(file io.Reader, out *[]MountPoint) error {
```
Comment (balamurugana) [inline pkg/mountinfo/mountinfo_linux.go]: You could name this function as `parseProcMounts()` and returning `[]MountPoint` is more appropriate

File: pkg/mountinfo/mountinfo_linux.go [hunk 8]
```diff
@@ -0,0 +1,90 @@
...
+		}
+		fields := strings.Fields(line)
+		if len(fields) != expectedNumFieldsPerLine {
+			return fmt.Errorf("wrong number of fields (expected %d, got %d): %s", expectedNumFieldsPerLine, len(fields), line)
+		}
+
+		if out != nil {
+			mp := MountPoint{
+				Device: fields[0],
+				Path:   fields[1] + "/",
```
Comment (balamurugana) [inline pkg/mountinfo/mountinfo_linux.go]: Appending `/` is unusual.

File: pkg/mountinfo/mountinfo_linux.go [hunk 9]
```diff
@@ -0,0 +1,90 @@
...
+
+const (
+	// Number of fields per line in /proc/mounts as per the fstab man page.
+	expectedNumFieldsPerLine = 6
+	// Location of the mount file to use
+	procMountsPath = "/proc/mounts"
+)
+
+// MountInfo - returns a list of all mounted filesystems.
+func MountInfo() (mps []MountPoint, err error) {
```
Comment (balamurugana) [inline pkg/mountinfo/mountinfo_linux.go]: `GetMountInfo()` is more cleaner.

File: cmd/server-main.go [hunk 10]
```diff
@@ -223,8 +226,57 @@ func serverMain(ctx *cli.Context) {
...
+			// if paths didn't match then we do have cross-device mount.
+			err = fmt.Errorf(msg, path, mounts)
+		}
+	}
+	return err
+}
+
 // Initialize object layer with the supplied disks, objectLayer is nil upon any error.
 func newObjectLayer(endpoints EndpointList) (newObject ObjectLayer, err error) {
+	for _, endpoint := range endpoints {
```
Comment (balamurugana) [inline cmd/server-main.go]: You could add this check to single endpoint creation ie `NewEndpoint()` should do this validation.

**Review by balamurugana — DISMISSED** [review]

**Comment by harshavardhana** [comment]
Addressed all your inquiries @balamurugana

File: pkg/mountinfo/mountinfo_linux.go [hunk 11]
```diff
@@ -0,0 +1,135 @@
...
+	// Number of fields per line in /proc/mounts as per the fstab man page.
+	expectedNumFieldsPerLine = 6
+	// Location of the mount file to use
+	procMountsPath = "/proc/mounts"
+)
+
+// List - returns a list of all mounted filesystems, if prefix
+// is provided all matching prefixes for your mounts are listed
+// instead.
+func List(prefix string) ([]MountInfo, error) {
```
Comment (krishnasrinivas) [inline pkg/mountinfo/mountinfo_linux.go]: doesn't seem to be used outside the package?

**Review by krishnasrinivas — COMMENTED** [review]
~~mountinfo.CheckCrossDevice does not seem to be there for non linux OSes?~~

File: pkg/mountinfo/mountinfo.go [hunk 12]
```diff
@@ -0,0 +1,31 @@
...
+ * Unless required by applicable law or agreed to in writing, software
+ * distributed under the License is distributed on an "AS IS" BASIS,
+ * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
+ * See the License for the specific language governing permissions and
+ * limitations under the License.
+ */
+
+package mountinfo
+
+// MountInfo - This represents a single line in /proc/mounts.
```
Comment (krishnasrinivas) [inline pkg/mountinfo/mountinfo.go]: does not seem to be used outside package?

File: pkg/mountinfo/mountinfo_linux.go (hunk 11 above)
Comment (harshavardhana) [reply pkg/mountinfo/mountinfo_linux.go]: This a mountinfo package so it implements basic things which can be useful in future.

File: pkg/mountinfo/mountinfo.go (hunk 12 above)
Comment (harshavardhana) [reply pkg/mountinfo/mountinfo.go]: It is exported because List() is exported.

**Comment by harshavardhana** [comment]
> mountinfo.CheckCrossDevice does not seem to be there for non linux OSes?

Yes its okay for now, we can catch up later @krishnasrinivas

File: pkg/mountinfo/mountinfo_linux.go (hunk 11 above)
Comment (krishnasrinivas) [reply pkg/mountinfo/mountinfo_linux.go]: better to keep code minimal and add it only when needed

Comment (harshavardhana) [reply pkg/mountinfo/mountinfo_linux.go]: Sure.. let me change.

File: pkg/mountinfo/mountinfo_linux.go [hunk 13]
```diff
@@ -0,0 +1,128 @@
...
+	mounts, err := readProcMounts(procMountsPath)
+	if err != nil {
+		return nil, err
+	}
+	var filteredMounts []mountInfo
+	for _, mount := range mounts {
+		// Add a separator to indicate that this is a proper directory/device.
+		// This is to avoid a situation where prefix is '/tmp/fsmount'
+		// and mount path is /tmp/fs. In-fact we need to check for `/tmp/fs/`
+		if strings.HasPrefix(strings.TrimSuffix(mount.Path, "/")+"/",
```
Comment (vadmeste) [inline pkg/mountinfo/mountinfo_linux.go]: path.Abs() is still needed here, otherwise sometimes a mounted dir inside the bucket won't be detected,

```
$ mkdir -b /tmp/fs/bucket
$ sudo mount /dev/your_disk /tmp/fs/bucket
$ cd /tmp/fs/
$ minio server .
```

Comment (harshavardhana) [reply pkg/mountinfo/mountinfo_linux.go]: Actually let me fail. if the path is absolute.

Comment (vadmeste) [reply pkg/mountinfo/mountinfo_linux.go]: > Actually let me fail. if the path is absolute.

Probably it is better if we change it to absolute in the beginning of the code path.

Comment (harshavardhana) [reply pkg/mountinfo/mountinfo_linux.go]: No that is callers responsibility. We don't want to mask usage bugs in that manner.

Comment (vadmeste) [reply pkg/mountinfo/mountinfo_linux.go]: yeah, I mean change it to absolute very early, probably when endpoints are prepared

Comment (harshavardhana) [reply pkg/mountinfo/mountinfo_linux.go]: I thought NewEndpoints already does that.

File: pkg/mountinfo/mountinfo_linux.go [hunk 14]
```diff
@@ -0,0 +1,132 @@
...
+func CheckCrossDevice(path string) error {
+	return checkCrossDeviceProcMounts(procMountsPath, path)
+}
+
+// internal function implements sthe same functionality to check if given path has multiple sub-mounts.
+func checkCrossDeviceProcMounts(procMountsPath, path string) error {
+	if !filepath.IsAbs(path) {
+		return fmt.Errorf("Invalid argument, path (%s) is expected to be absolute", path)
+	}
+	mounts, err := listProcMounts(procMountsPath, path)
```
Comment (balamurugana) [inline pkg/mountinfo/mountinfo_linux.go]: `/proc/mounts` is parsed every time `CheckCrossDevice()` called.  May be you could move this checker into endpoints.go.  This way you can call/get  []MountInfo once and reuse

Comment (harshavardhana) [reply pkg/mountinfo/mountinfo_linux.go]: Added a global instance.. and using that instead. @balamurugana

**Comment by harshavardhana** [comment]
@vadmeste @krishnasrinivas waiting on further reviews..

**Review by vadmeste — APPROVED** [review]
LGTM

**Comment by harshavardhana** [comment]
~~why is this blocked @deekoder ?~~

**Review by balamurugana — APPROVED** [review]

**Comment by krishnasrinivas** [comment]
>> better to keep code minimal and add it only when needed

> Sure.. let me change.

List and MountInfo are still exported @harshavardhana

File: pkg/mountinfo/mountinfo_linux.go [hunk 15]
```diff
@@ -0,0 +1,117 @@
...
+	procMountsPath = "/proc/mounts"
+)
+
+// List - lists all mounts.
+func List() (Mounts, error) {
+	return readProcMounts(procMountsPath)
+}
+
+// CheckCrossDevice - check if given path has any sub-mounts in the input mounts list.
+func (mts Mounts) CheckCrossDevice(path string) error {
```
Comment (krishnasrinivas) [inline pkg/mountinfo/mountinfo_linux.go]: if the signature of this function is:

```
CheckCrossDevice(paths []string) error
```

We can avoid exposing Mount (as this struct is not useful outside the package)

i.e the package can expose only one function

Comment (harshavardhana) [reply pkg/mountinfo/mountinfo_linux.go]: We did that to avoid doing parsing again and again. @krishnasrinivas

**Review by krishnasrinivas — APPROVED** [review]
