### PR TITLE
Check if SSL is configured to validate input arguments

### LINKED ISSUE #5251: Minio runs unencrypted when https URLs are used but certificates are not installed
## Expected Behavior
Minio should error out when listening on or connecting to remote hosts using https:// URLs.

## Current Behavior
It's possible to start a distributed minio cluster while specifying https URLs but which will not operate with TLS enabled.

## Steps to Reproduce
1. On 4 completely empty nodes, install minio.
2. On each machine run "minio server https://node1/data https://node2/data https://node3/data https://node4/data".

## Context
This caused me to incorrectly think minio was performing some sort of cross-node encryption even though it wasn't and was operating with no secure connectivity.

## Your Environment
* Version 2017-11-22T19:55:46Z
* Linux x64

### PR DESCRIPTION
**Pull request by harshavardhana**
## Description
This PR handles following situations

- secure endpoints provided, server should fail to start
  if TLS is not configured
- insecure endpoints provided, server starts ignoring
  if TLS is configured or not.

## Motivation and Context
Fixes #5251

## How Has This Been Tested?
Manually using `go test -v` and following script

```sh
#!/bin/bash

uuid1=$(uuid)
uuid2=$(uuid)
uuid3=$(uuid)
uuid4=$(uuid)

export MINIO_ACCESS_KEY="minio"
export MINIO_SECRET_KEY="minio123"

mkdir -p "/tmp/$uuid1" "/tmp/$uuid2" "/tmp/$uuid3" "/tmp/$uuid4"
echo "https://localhost:9001/tmp/${uuid1}" "https://localhost:9002/tmp/${uuid2}" "https://localhost:9003/tmp/${uuid3}" "https://localhost:9004/tmp/${uuid4}" >> /tmp/slots

minio server --address localhost:9001 "https://localhost:9001/tmp/${uuid1}" "https://localhost:9002/tmp/${uuid2}" "https://localhost:9003/tmp/${uuid3}" "https://localhost:9004/tmp/${uuid4}"&
minio server --address localhost:9002 "https://localhost:9001/tmp/${uuid1}" "https://localhost:9002/tmp/${uuid2}" "https://localhost:9003/tmp/${uuid3}" "https://localhost:9004/tmp/${uuid4}"&
minio server --address localhost:9003 "https://localhost:9001/tmp/${uuid1}" "https://localhost:9002/tmp/${uuid2}" "https://localhost:9003/tmp/${uuid3}" "https://localhost:9004/tmp/${uuid4}"&
minio server --address localhost:9004 "https://localhost:9001/tmp/${uuid1}" "https://localhost:9002/tmp/${uuid2}" "https://localhost:9003/tmp/${uuid3}" "https://localhost:9004/tmp/${uuid4}"
```

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have added unit tests to cover my changes.
- [ ] I have added/updated functional tests in [mint](https://github.com/minio/mint). (If yes, add `mint` PR # here: )
- [x] All new and existing tests passed.

### CODE REVIEW

File: cmd/endpoint.go [hunk 1]
```diff
@@ -235,6 +207,8 @@ func NewEndpointList(args ...string) (endpoints EndpointList, err error) {
 			return nil, fmt.Errorf("mixed style endpoints are not supported")
 		} else if endpoint.Scheme != scheme {
 			return nil, fmt.Errorf("mixed scheme is not supported")
+		} else if endpoint.Scheme == "https" && scheme == "https" && !globalIsSSL {
```
Comment (balamurugana) [inline cmd/endpoint.go]: endpoint should not worry about any globals.  This check should be outside of endpoint creation.

**Review by balamurugana — CHANGES_REQUESTED** [review]
The check should not be in endpoint creation

**Comment by harshavardhana** [comment]
Can you suggest where the check would be ideally ?

**Comment by harshavardhana** [comment]
> Can you suggest where the check would be ideally ?

No need moved the check into newStorageRPC() instead. @balamurugana PTAL

**Comment by balamurugana** [comment]
@harshavardhana 
> Can you suggest where the check would be ideally ?

Below is correct way to fit the fix
1. Add a method `IsSecure()` or `IsHTTPS()` to `EndpointList` and `Endpoint`
2. in `server-main.go` call `globalPublicCerts, globalRootCAs, globalTLSCertificate, globalIsSSL, err = getSSLConfig()` only if `globalEndpoints.IsSecure() == true`
3. modify `getSSLConfig()` to return `(x509Certs []*x509.Certificate, rootCAs *x509.CertPool, tlsCert *tls.Certificate, err error)` always i.e. it returns error if `getPublicCertFile()` and/or `getPrivateKeyFile()` missing.

**Comment by harshavardhana** [comment]
> Below is correct way to fit the fix
> 
> Add a method IsSecure() or IsHTTPS() to EndpointList and Endpoint
> in server-main.go call globalPublicCerts, globalRootCAs, globalTLSCertificate, globalIsSSL, err = getSSLConfig() only if globalEndpoints.IsSecure() == true
> modify getSSLConfig() to return (x509Certs []*x509.Certificate, rootCAs *x509.CertPool, tlsCert *tls.Certificate, err error) always i.e. it returns error if getPublicCertFile() and/or getPrivateKeyFile() missing.

Don't you think adding a check in newStorageRPC is a correct behavior for this? since that is where we perform an actual request eventually anyways?

It is sort of similar to how newPosix() would validate the disk.  Because the PR needs to address two cases not just TLS

Currently there are two bugs

- server is configured with TLS and insecure endpoints are provided.
- server is not configured with TLS and secure endpoints are provided. 

Doing the fix that you mentioned would not address the `first` case.

**Comment by harshavardhana** [comment]
> Add a method IsSecure() or IsHTTPS() to EndpointList and Endpoint
> in server-main.go call globalPublicCerts, globalRootCAs, globalTLSCertificate, globalIsSSL, err = getSSLConfig() only if globalEndpoints.IsSecure() == true
> modify getSSLConfig() to return (x509Certs []*x509.Certificate, rootCAs *x509.CertPool, tlsCert *tls.Certificate, err error) always i.e. it returns error if getPublicCertFile() and/or getPrivateKeyFile() missing.

Changed to this style @balamurugana PTAL

File: cmd/common-main.go [hunk 2]
```diff
@@ -123,3 +123,23 @@ func handleCommonEnvVars() {
...
+	if ssl := globalEndpoints.IsHTTPS(); ssl {
+		// Check and load SSL certificates under distributed mode.
+		var err error
+		globalPublicCerts, globalRootCAs, globalTLSCertificate, err = getSSLConfig()
+
+		// Set globalIsSSL to true only if certs can be loaded properly.
+		globalIsSSL = err == nil
+
+		// When not running in distributed mode, for example in gateway we ignore
+		// if we cannot load certs, reset the error as success.
```
Comment (balamurugana) [inline cmd/common-main.go]: Can't understand why.  Isn't it possible to run a insecure gateway with TLS backend? similarly secure gateway with insecure backend?

File: cmd/common-main.go [hunk 3]
```diff
@@ -123,3 +123,23 @@ func handleCommonEnvVars() {
 		globalIsEnvDomainName = true
 	}
 }
+
+func loadCerts() {
+	// Check for certificates only if endpoints are secure.
+	if ssl := globalEndpoints.IsHTTPS(); ssl {
```
Comment (balamurugana) [inline cmd/common-main.go]: actually `globalIsSSL = globalEndpoints.IsHTTPS()`.  If possible `globalIsSSL` can be removed.

File: cmd/endpoint.go [hunk 4]
```diff
@@ -65,18 +65,20 @@ func (endpoint Endpoint) Type() EndpointType {
...
 
-// SetHTTP - sets insecure http for URLEndpointType.
-func (endpoint Endpoint) SetHTTP() {
+// IsHTTP - returns true if insecure for URLEndpointType.
+func (endpoint Endpoint) IsHTTP() bool {
 	if endpoint.Host != "" {
-		endpoint.Scheme = "http"
+		return endpoint.Scheme == "http"
 	}
+	return false
```
Comment (balamurugana) [inline cmd/endpoint.go]: I see you are moving `SetHTTP()` and `SetHTTPS()` methods.  You can remove them completely and add only one method `IsHTTPS()` i.e. `IsHTTP()` is negative duplicate.

File: cmd/endpoint.go [hunk 5]
```diff
@@ -190,18 +192,22 @@ func (endpoints EndpointList) Less(i, j int) bool {
...
 }
 
-// SetHTTPS - sets secure http for URLEndpointType.
-func (endpoints EndpointList) SetHTTPS() {
+// IsHTTPS - returns true if secure for URLEndpointType.
+func (endpoints EndpointList) IsHTTPS() bool {
+	var ok = true
 	for i := range endpoints {
-		endpoints[i].SetHTTPS()
+		ok = ok && endpoints[i].IsHTTPS()
```
Comment (balamurugana) [inline cmd/endpoint.go]: Its not possible to have mixed scheme unless handcrafted `EndpointList`

File: cmd/common-main.go (hunk 2 above)
Comment (harshavardhana) [reply cmd/common-main.go]: Yes but we shouldn't fail. For gateway if do not add the check we will fail because globalEndpoints has the TLS backend. 

This code doesn't invalidate current behvaioe. It just relaxes secure gateway to be mandatory for secure backend.

File: cmd/common-main.go (hunk 3 above)
Comment (harshavardhana) [reply cmd/common-main.go]: No it's not true for gateway or FS or standalone Erasure.

**Comment by harshavardhana** [comment]
We needed to handle multiple situations here now it is handled properly @balamurugana @krishnasrinivas PTAL

 The situation is complex because gateway mode also re-purposes globalEndpoints for its remote as well.  This leads to a situation where certs check would fail since we changed the `getSSLConfig()` behavior. 

There is no change needed in getSSLConfig() in-fact the behavior doesn't need to change. We need to validate instead if distributed mode has incorrect arguments in accordance with the current environment.

File: cmd/endpoint.go [hunk 6]
```diff
@@ -190,18 +184,13 @@ func (endpoints EndpointList) Less(i, j int) bool {
...
-// SetHTTP - sets insecure http for URLEndpointType.
-func (endpoints EndpointList) SetHTTP() {
+// IsHTTPS - returns true if secure for URLEndpointType.
+func (endpoints EndpointList) IsHTTPS() bool {
+	var ok = true
 	for i := range endpoints {
-		endpoints[i].SetHTTP()
+		ok = ok && endpoints[i].IsHTTPS()
 	}
+	return ok
```
Comment (krishnasrinivas) [inline cmd/endpoint.go]: easier would be:
```
{
for i := range endpoints {
    if !endpoints[i].IsHTTPS() {
        return false
    }
return true
}
```

Comment (harshavardhana) [reply cmd/endpoint.go]: How is this easier ?

Comment (krishnasrinivas) [reply cmd/endpoint.go]: Second function is easier to read and also more efficient (since we return earlier):
```
func (endpoints EndpointList) IsHTTPS() bool {
        var ok = true
        for i := range endpoints {
                ok = ok && endpoints[i].IsHTTPS()
        }
        return ok
}
```

```
func (endpoints EndpointList) IsHTTPS() bool {
        for _, endpoint := range endpoints {
                if endpoint.IsHTTPS() == false {
                        return false
                }
        }
        return true
}
```

File: cmd/common-main.go [hunk 7]
```diff
@@ -123,3 +123,27 @@ func handleCommonEnvVars() {
 		globalIsEnvDomainName = true
 	}
 }
+
+func loadCerts() {
```
Comment (balamurugana) [inline cmd/common-main.go]: As gateway and server have different logic of handling TLS, this function is not required i.e. handle cases individually in gateway and server.

Comment (harshavardhana) [reply cmd/common-main.go]: Okay

File: cmd/endpoint.go [hunk 8]
```diff
@@ -65,18 +65,12 @@ func (endpoint Endpoint) Type() EndpointType {
...
 	if endpoint.Host != "" {
-		endpoint.Scheme = "https"
-	}
-}
-
-// SetHTTP - sets insecure http for URLEndpointType.
-func (endpoint Endpoint) SetHTTP() {
-	if endpoint.Host != "" {
-		endpoint.Scheme = "http"
+		return endpoint.Scheme == "https"
```
Comment (balamurugana) [inline cmd/endpoint.go]: No need to have `if`. Just have this one liner for any type of endpoint.

File: cmd/endpoint.go [hunk 9]
```diff
@@ -190,18 +184,14 @@ func (endpoints EndpointList) Less(i, j int) bool {
...
-
-// SetHTTP - sets insecure http for URLEndpointType.
-func (endpoints EndpointList) SetHTTP() {
-	for i := range endpoints {
-		endpoints[i].SetHTTP()
+		if !endpoints[i].IsHTTPS() {
+			return false
+		}
 	}
+	return true
```
Comment (balamurugana) [inline cmd/endpoint.go]: Just do one-liner `return endpoints[0].IsHTTPS()`

Comment (harshavardhana) [reply cmd/endpoint.go]: done

File: cmd/endpoint.go (hunk 8 above)
Comment (harshavardhana) [reply cmd/endpoint.go]: done

**Comment by harshavardhana** [comment]
Added all your recommendations @balamurugana

File: cmd/server-main.go [hunk 10]
```diff
@@ -183,8 +190,7 @@ func serverMain(ctx *cli.Context) {
 
 	// Configure server.
 	// Declare handler to avoid lint errors.
-	var handler http.Handler
-	handler, err = configureServerHandler(globalEndpoints)
+	handler, err := configureServerHandler(globalEndpoints)
```
Comment (balamurugana) [inline cmd/server-main.go]: why do you need to change this line? Is above comment not applicable anymore?

Comment (harshavardhana) [reply cmd/server-main.go]: I don't see any linter errors, it was changed because of loadCerts() since err moved into that function. I can change it back.

Comment (harshavardhana) [reply cmd/server-main.go]: if you see few lines below `newObject, err :=` so current master has this sort of frivolous comments IMO.

File: cmd/server-main.go [hunk 11]
```diff
@@ -158,6 +157,14 @@ func serverMain(ctx *cli.Context) {
 	globalPublicCerts, globalRootCAs, globalTLSCertificate, globalIsSSL, err = getSSLConfig()
 	fatalIf(err, "Invalid SSL certificate file")
 
+	// Check if certficates are available, and endpoints are secured as well. We
+	// should validate this only under distributed setup since distributed setup
+	// can have multiple secure endpoints. We shouldn't validate and fail for any
+	// other mode.
```
Comment (balamurugana) [inline cmd/server-main.go]: Below comment is good enough.
```
// In DistXL setup, error out if no certificate found for HTTPS endpoints.
```

File: cmd/server-main.go [hunk 12]
```diff
@@ -158,6 +157,14 @@ func serverMain(ctx *cli.Context) {
...
+	if !globalIsSSL && globalEndpoints.IsHTTPS() && globalIsDistXL {
```
Comment (balamurugana) [inline cmd/server-main.go]: You could change order conditions like `globalIsDistXL && globalEndpoints.IsHTTPS() && !globalIsSSL` to convey the flow.

File: cmd/server-main.go (hunk 11 above)
Comment (harshavardhana) [reply cmd/server-main.go]: Done

File: cmd/server-main.go (hunk 12 above)
Comment (harshavardhana) [reply cmd/server-main.go]: Done

File: cmd/server-main.go (hunk 10 above)
Comment (balamurugana) [reply cmd/server-main.go]: I explicitly added the comment to indicate `golint` error.  Later someone will fix/add the same.  Do you see any issue to left the line as is?

Comment (harshavardhana) [reply cmd/server-main.go]: No i can leave it as is, revert it back to how it was.

**Comment by harshavardhana** [comment]
Fixed @balamurugana

**Review by balamurugana — APPROVED** [review]
LGTM

**Review by krishnasrinivas — APPROVED** [review]
