### PR TITLE
Deprecate caching for erasure/distributed mode

### LINKED ISSUE #13907: Can't upload file when caching enabled
When cache enabled it's not possible to upload file to minio using Web UI or any S3 client - only download available. After disabling cache uploading works fine.

## Expected Behavior
Normal files upload and download with cache enabled

## Current Behavior
When cache enabled it's not possible to upload file to minio using Web UI or any S3 client - only download available.

## Steps to Reproduce (for bugs)
1. Setup minio.
2. Enable caching (I use separate ssd) in Web GUI at Settings -> Cache page.

## Context
I have 3 minio servers each with 4 disks running in cluster.

## Regression
No, previous September's version works fine.

## Your Environment
* Version used (`minio --version`): 2021-12-10T23:03:39Z
* Server setup and configuration: 3 servers with 4 disks each in cluster, each server have separate ssd disk fo caching
* Operating System and version (`uname -a`): Linux minio-1 5.4.0-91-generic #102-Ubuntu SMP Fri Nov 5 16:31:28 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

### PR DESCRIPTION
**Pull request by poornas**
Fixes: #13907

Also removing default value of `writethrough` for cache commit
which was interefering with cache_after setting

## Motivation and Context
caching not useful in dist/erasure mode.

## Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Optimization (provides speedup with no functional changes)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [ ] Fixes a regression (If yes, please add `commit-id` or `PR #` here)
- [ ] Documentation updated
- [ ] Unit tests added/updated

### CODE REVIEW

File: cmd/disk-cache.go [hunk 1]
```diff
@@ -706,7 +706,7 @@ func (c *cacheObjects) PutObject(ctx context.Context, bucket, object string, r *
 				oi, _, err := dcache.Stat(GlobalContext, bucket, object)
 				// avoid cache overwrite if another background routine filled cache
 				if err != nil || oi.ETag != bReader.ObjInfo.ETag {
-					dcache.Put(GlobalContext, bucket, object, bReader, bReader.ObjInfo.Size, nil, ObjectOptions{UserDefined: getMetadata(bReader.ObjInfo)}, false, true)
+					dcache.Put(GlobalContext, bucket, object, bReader, bReader.ObjInfo.Size, nil, ObjectOptions{UserDefined: getMetadata(bReader.ObjInfo)}, false, false)
```
Comment (harshavardhana) [inline cmd/disk-cache.go:709]: what is this for? @poornas

**Review by harshavardhana — CHANGES_REQUESTED** [review]

**Comment by minio-trusted** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-s3.sh | :heavy_check_mark: |
| mint-erasure.sh | :heavy_check_mark: |
| mint-dist-erasure.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-compress-encrypt-dist-erasure.sh | :heavy_check_mark: |
| mint-pools.sh | :heavy_check_mark: |
Deleting image on docker hub
Deleting image locally

File: cmd/disk-cache.go (hunk 1 above)
Comment (poornas) [reply cmd/disk-cache.go:709]: this flag controls setting internal metadata in writeback mode - this is unnecessarily set for non writeback here.

**Comment by minio-trusted** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-s3.sh | :heavy_check_mark: |
| mint-erasure.sh | :heavy_check_mark: |
| mint-dist-erasure.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-compress-encrypt-dist-erasure.sh | :heavy_check_mark: |
| mint-pools.sh | :heavy_check_mark: |
Deleting image on docker hub
Deleting image locally

File: cmd/server-main.go [hunk 2]
```diff
@@ -591,8 +591,8 @@ func serverMain(ctx *cli.Context) {
 		}
 	}
 
-	if globalCacheConfig.Enabled {
-		// initialize the new disk cache objects.
+	// initialize the new disk cache objects.
+	if globalCacheConfig.Enabled && !globalIsErasure {
```
Comment (harshavardhana) [inline cmd/server-main.go]: Let's complain about it here as a "WARNING" instead of removing it completely for now and lets take time to purge it.

Add deprecation notice to migrate to "gateway" based setups if disk cache is needed for both single drive and multi-drive.

**Review by harshavardhana — CHANGES_REQUESTED** [review]

**Comment by minio-trusted** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-s3.sh | :heavy_check_mark: |
| mint-erasure.sh | :heavy_check_mark: |
| mint-dist-erasure.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-compress-encrypt-dist-erasure.sh | :heavy_check_mark: |
| mint-pools.sh | :heavy_check_mark: |
Deleting image on docker hub
Deleting image locally

File: cmd/server-main.go [hunk 3]
```diff
@@ -591,8 +591,11 @@ func serverMain(ctx *cli.Context) {
 		}
 	}
 
+	// initialize the new disk cache objects.
 	if globalCacheConfig.Enabled {
-		// initialize the new disk cache objects.
+		if globalIsErasure {
+			logStartupMessage(color.Yellow("WARNING: Disk caching is deprecated for single/multi drive MinIO setups. Please migrate to using MinIO S3 gateway instead of disk caching"))
+		}
```
Comment (harshavardhana) [inline cmd/server-main.go]:
```suggestion
		logStartupMessage(color.Yellow("WARNING: Disk caching is deprecated for single/multi drive MinIO setups. Please migrate to using MinIO S3 gateway instead of disk caching"))
```

**Review by harshavardhana — CHANGES_REQUESTED** [review]

**Review by harshavardhana — APPROVED** [review]

**Comment by minio-trusted** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-s3.sh | :heavy_check_mark: |
| mint-erasure.sh | :heavy_check_mark: |
| mint-dist-erasure.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-compress-encrypt-dist-erasure.sh | :heavy_check_mark: |
| mint-pools.sh | :heavy_check_mark: |
Deleting image on docker hub
Deleting image locally
