### PR TITLE
Fix dynamic help vars for sub-commands

### LINKED ISSUE #7924: Help documentation for 'minio gateway s3' has unresolved variables.
Running `minio gateway s3 --help` has missing variables.

I'm receiving:
```
EXAMPLES:
  1. Start minio gateway server for AWS S3 backend.
      (.*)accesskey
      (.*)secretkey
      minio gateway s3

  2. Start minio gateway server for S3 backend on custom endpoint.
      (.*)Q3AM3UQ867SPQQA43P2F
      (.*)zuf+tfteSlswRu7BJ86wekitnifILbZam1KYY3TG
      minio gateway s3 https://play.min.io:9000

  3. Start minio gateway server for AWS S3 backend logging all requests to http endpoint.
      (.*)Q3AM3UQ867SPQQA43P2F
      (.*)zuf+tfteSlswRu7BJ86wekitnifILbZam1KYY3TG
      (.*)"http://localhost:8000/"
      minio gateway s3 https://play.min.io:9000

  4. Start minio gateway server for AWS S3 backend with edge caching enabled.
      (.*)accesskey
      (.*)secretkey
      (.*)"/mnt/drive1;/mnt/drive2;/mnt/drive3;/mnt/drive4"
      (.*)"bucket1/*;*.png"
      (.*)40
      (.*)80
      minio gateway s3

  4. Start minio gateway server for AWS S3 backend using AWS environment variables.
     NOTE: The access and secret key in this case will authenticate with MinIO instead
     of AWS and AWS envs will be used to authenticate to AWS S3.
      (.*)aws_access_key
      (.*)aws_secret_key
      (.*)accesskey
      (.*)secretkey
      minio gateway s3
```
There should be something in front of the (.*) parts of this (the code is showing some variables that should be resolved). I'm new to minio and GO, so I'm not sure what the output should look like or how to fix it. Just thought I'd bring it up.
```
VERSION:
  2019-07-10T00:34:56Z
```
Linux binary.

### PR DESCRIPTION
**Pull request by harshavardhana**
## Description
The fix in #7646 introduced a regression which
was left unnoticed, the fix didn't work for
sub-commands unfortunately. This fixes it
by moving v1.21.0 version of the minio/cli
package.

## Motivation and Context
Fixes #7924

## How to test this PR?
Just download the PR and build it check the output of `minio gateway s3 --help` v/s the released version.

## Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [x] Fixes a regression introduced from #7646 
- [ ] Documentation needed
- [ ] Unit tests needed
- [ ] Functional tests needed (If yes, add [mint](https://github.com/minio/mint) PR # here: )

### CODE REVIEW

**Comment by minio-ops** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-compression-xl.sh | :heavy_check_mark: |
| mint-xl.sh | :heavy_check_mark: |
| mint-compression-dist-xl.sh | :heavy_check_mark: |
| mint-compression-fs.sh | :heavy_check_mark: |
| mint-worm.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :x: [more...](#995bfa70-9dea-4630-9100-f6eee6ad86ea) |
| mint-dist-xl.sh | :x: [more...](#013c218d-73b2-461a-9aa4-b67a2263c2c3) |
<a name="995bfa70-9dea-4630-9100-f6eee6ad86ea"></a>
### 7925-90fe33f/mint-large-bucket.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.55:30848
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 5513f9b240f6:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 1 seconds
(2/14) Running aws-sdk-java tests ... done in 2 seconds
(3/14) Running aws-sdk-php tests ... done in 51 seconds
(4/14) Running aws-sdk-ruby tests ... done in 15 seconds
(5/14) Running awscli tests ... done in 1 minutes and 25 seconds
(6/14) Running healthcheck tests ... done in 0 seconds
(7/14) Running mc tests ... FAILED in 2 minutes and 38 seconds
{
  "name": "mc",
  "duration": "110464",
  "function": "test_mirror_list_objects_storage_class",
  "status": "FAIL",
  "error": "/mint/run/core/mc/mc --config-dir /tmp/.mc-21560 --quiet --no-color mirror --storage-class REDUCED_REDUNDANCY /mint/data myminio/mc-test-bucket-28520  >>> \n`/mint/data/datafile-1-MB` -> `myminio/mc-test-bucket-28520/datafile-1-MB`\n`/mint/data/datafile-0-b` -> `myminio/mc-test-bucket-28520/datafile-0-b`\n`/mint/data/datafile-1-kB` -> `myminio/mc-test-bucket-28520/datafile-1-kB`\n`/mint/data/datafile-1-b` -> `myminio/mc-test-bucket-28520/datafile-1-b`\n`/mint/data/datafile-10-MB` -> `myminio/mc-test-bucket-28520/datafile-10-MB`\n`/mint/data/datafile-1.03-MB` -> `myminio/mc-test-bucket-28520/datafile-1.03-MB`\n`/mint/data/datafile-100-kB` -> `myminio/mc-test-bucket-28520/datafile-100-kB`\n`/mint/data/datafile-10-kB` -> `myminio/mc-test-bucket-28520/datafile-10-kB`\n`/mint/data/datafile-11-MB` -> `myminio/mc-test-bucket-28520/datafile-11-MB`\n`/mint/data/datafile-129-MB` -> `myminio/mc-test-bucket-28520/datafile-129-MB`\n`/mint/data/datafile-5-MB` -> `myminio/mc-test-bucket-28520/datafile-5-MB`\n`/mint/data/datafile-33-kB` -> `myminio/mc-test-bucket-28520/datafile-33-kB`\n`/mint/data/datafile-5243880-b` -> `myminio/mc-test-bucket-28520/datafile-5243880-b`\n`/mint/data/datafile-6-MB` -> `myminio/mc-test-bucket-28520/datafile-6-MB`\n`/mint/data/datafile-65-MB` -> `myminio/mc-test-bucket-28520/datafile-65-MB`\nmc: <ERROR> Failed to copy `/mint/data/datafile-11-MB`. Please reduce your request\nmc: <ERROR> Failed to copy `/mint/data/datafile-65-MB`. Please reduce your request\nmc: <ERROR> Failed to copy `/mint/data/datafile-129-MB`. Please reduce your request\nTotal: 233.17 MiB, Transferred: 440.42 MiB, Speed: 3.99 MiB/s"
}

Executed 6 out of 14 tests successfully.
```
<a name="013c218d-73b2-461a-9aa4-b67a2263c2c3"></a>
### 7925-90fe33f/mint-dist-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.61:32273
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp dea81087d1a6:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 0 seconds
(2/14) Running aws-sdk-java tests ... done in 1 seconds
(3/14) Running aws-sdk-php tests ... done in 48 seconds
(4/14) Running aws-sdk-ruby tests ... done in 4 seconds
(5/14) Running awscli tests ... done in 2 minutes and 7 seconds
(6/14) Running healthcheck tests ... done in 0 seconds
(7/14) Running mc tests ... done in 1 minutes and 0 seconds
(8/14) Running minio-dotnet tests ... done in 38 seconds
(9/14) Running minio-go tests ... done in 58 seconds
(10/14) Running minio-java tests ... FAILED in 1 minutes and 14 seconds
{
  "name": "minio-java",
  "function": "removeIncompleteUpload(String bucketName, String objectName)",
  "duration": 1232,
  "status": "FAIL",
  "error": "error occurred\nErrorResponse(code=SlowDown, message=Please reduce your request, bucketName=minio-java-test-7kjr8f, objectName=minio-java-test-162a6sk, resource=/minio-java-test-7kjr8f/minio-java-test-162a6sk, requestId=15B0D67DA7DB6F49, hostId=72030a86-c9f6-4037-a3c2-87e131155375)\nrequest={method=DELETE, url=http://72.28.97.61:32273/minio-java-test-7kjr8f/minio-java-test-162a6sk?uploadId=982d6074-b23f-4e9a-9d11-b3ddf1f9e6fe, headers=Host: 72.28.97.61:32273\nUser-Agent: MinIO (amd64; amd64) minio-java/dev\nx-amz-content-sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855\nx-amz-date: 20190713T022825Z\nAuthorization: AWS4-HMAC-SHA256 Credential=*REDACTED*/20190713/us-east-1/s3/aws4_request, SignedHeaders=host;x-amz-content-sha256;x-amz-date, Signature=*REDACTED*\n}\nresponse={code=503, headers=Accept-Ranges: bytes\nContent-Length: 361\nContent-Security-Policy: block-all-mixed-content\nContent-Type: application/xml\nRetry-After: 120\nServer: MinIO/DEVELOPMENT.2019-07-13T02-08-34Z\nVary: Origin\nX-Amz-Request-Id: 15B0D67DA7DB6F49\nX-Xss-Protection: 1; mode=block\nDate: Sat, 13 Jul 2019 02:28:26 GMT\n}\n >>> [io.minio.MinioClient.executeReq(MinioClient.java:1204), io.minio.MinioClient.execute(MinioClient.java:1070), io.minio.MinioClient.executeDelete(MinioClient.java:1347), io.minio.MinioClient.abortMultipartUpload(MinioClient.java:5149), io.minio.MinioClient.putObject(MinioClient.java:4337), io.minio.MinioClient.putObject(MinioClient.java:4183), FunctionalTest.removeIncompleteUploads_test(FunctionalTest.java:1719), FunctionalTest.runTests(FunctionalTest.java:2992), FunctionalTest.main(FunctionalTest.java:3118)]"
}

Executed 9 out of 14 tests successfully.
```

File: cmd/gateway/s3/gateway-s3.go [hunk 1]
```diff
@@ -77,37 +77,37 @@ ENVIRONMENT VARIABLES:
 
 EXAMPLES:
   1. Start minio gateway server for AWS S3 backend.
-     {{.Prompt}} {{.EnvVarSetCommand}}(.*){{.AssignmentOperator}}accesskey
-     {{.Prompt}} {{.EnvVarSetCommand}}(.*){{.AssignmentOperator}}secretkey
+     {{.Prompt}} {{.EnvVarSetCommand}}MINIO_ACCESS_KEY{{.AssignmentOperator}}accesskey
```
Comment (kannappanr) [inline cmd/gateway/s3/gateway-s3.go]: `{{.Prompt}} {{.EnvVarSetCommand}}MINIO_ACCESS_KEY{{.AssignmentOperator}}` needs to be `{{.Prompt}} {{.EnvVarSetCommand}} MINIO_ACCESS_KEY{{.AssignmentOperator}}`

Comment (harshavardhana) [reply cmd/gateway/s3/gateway-s3.go]:
```suggestion
     {{.Prompt}} {{.EnvVarSetCommand}} MINIO_ACCESS_KEY{{.AssignmentOperator}}accesskey
```

File: cmd/gateway/s3/gateway-s3.go [hunk 2]
```diff
@@ -77,37 +77,37 @@ ENVIRONMENT VARIABLES:
 
 EXAMPLES:
   1. Start minio gateway server for AWS S3 backend.
-     {{.Prompt}} {{.EnvVarSetCommand}}(.*){{.AssignmentOperator}}accesskey
-     {{.Prompt}} {{.EnvVarSetCommand}}(.*){{.AssignmentOperator}}secretkey
+     {{.Prompt}} {{.EnvVarSetCommand}} MINIO_ACCESS_KEY{{.AssignmentOperator}}accesskey
+     {{.Prompt}} {{.EnvVarSetCommand}}MINIO_SECRET_KEY{{.AssignmentOperator}}secretkey
```
Comment (harshavardhana) [inline cmd/gateway/s3/gateway-s3.go]:
```suggestion
     {{.Prompt}} {{.EnvVarSetCommand}} MINIO_SECRET_KEY{{.AssignmentOperator}}secretkey
```

File: cmd/gateway/s3/gateway-s3.go [hunk 3]
```diff
@@ -77,37 +77,37 @@ ENVIRONMENT VARIABLES:
...
      {{.Prompt}} {{.HelpName}}
 
   2. Start minio gateway server for S3 backend on custom endpoint.
-     {{.Prompt}} {{.EnvVarSetCommand}}(.*){{.AssignmentOperator}}Q3AM3UQ867SPQQA43P2F
-     {{.Prompt}} {{.EnvVarSetCommand}}(.*){{.AssignmentOperator}}zuf+tfteSlswRu7BJ86wekitnifILbZam1KYY3TG
+     {{.Prompt}} {{.EnvVarSetCommand}}MINIO_ACCESS_KEY{{.AssignmentOperator}}Q3AM3UQ867SPQQA43P2F
```
Comment (harshavardhana) [inline cmd/gateway/s3/gateway-s3.go]:
```suggestion
     {{.Prompt}} {{.EnvVarSetCommand}} MINIO_ACCESS_KEY{{.AssignmentOperator}}Q3AM3UQ867SPQQA43P2F
```

File: cmd/gateway/s3/gateway-s3.go [hunk 4]
```diff
@@ -77,37 +77,37 @@ ENVIRONMENT VARIABLES:
...
+     {{.Prompt}} {{.EnvVarSetCommand}}MINIO_SECRET_KEY{{.AssignmentOperator}}zuf+tfteSlswRu7BJ86wekitnifILbZam1KYY3TG
```
Comment (harshavardhana) [inline cmd/gateway/s3/gateway-s3.go]:
```suggestion
     {{.Prompt}} {{.EnvVarSetCommand}} MINIO_SECRET_KEY{{.AssignmentOperator}}zuf+tfteSlswRu7BJ86wekitnifILbZam1KYY3TG
```

File: cmd/gateway/s3/gateway-s3.go [hunk 5]
```diff
@@ -77,37 +77,37 @@ ENVIRONMENT VARIABLES:
...
      {{.Prompt}} {{.HelpName}} https://play.min.io:9000
 
   3. Start minio gateway server for AWS S3 backend logging all requests to http endpoint.
-     {{.Prompt}} {{.EnvVarSetCommand}}(.*){{.AssignmentOperator}}Q3AM3UQ867SPQQA43P2F
-     {{.Prompt}} {{.EnvVarSetCommand}}(.*){{.AssignmentOperator}}zuf+tfteSlswRu7BJ86wekitnifILbZam1KYY3TG
-     {{.Prompt}} {{.EnvVarSetCommand}}(.*){{.AssignmentOperator}}"http://localhost:8000/"
+     {{.Prompt}} {{.EnvVarSetCommand}}MINIO_ACCESS_KEY{{.AssignmentOperator}}Q3AM3UQ867SPQQA43P2F
```
Comment (harshavardhana) [inline cmd/gateway/s3/gateway-s3.go]:
```suggestion
     {{.Prompt}} {{.EnvVarSetCommand}} MINIO_ACCESS_KEY{{.AssignmentOperator}}Q3AM3UQ867SPQQA43P2F
```

File: cmd/gateway/s3/gateway-s3.go [hunk 6]
```diff
@@ -77,37 +77,37 @@ ENVIRONMENT VARIABLES:
...
+     {{.Prompt}} {{.EnvVarSetCommand}}MINIO_SECRET_KEY{{.AssignmentOperator}}zuf+tfteSlswRu7BJ86wekitnifILbZam1KYY3TG
```
Comment (harshavardhana) [inline cmd/gateway/s3/gateway-s3.go]:
```suggestion
     {{.Prompt}} {{.EnvVarSetCommand}} MINIO_SECRET_KEY{{.AssignmentOperator}}zuf+tfteSlswRu7BJ86wekitnifILbZam1KYY3TG
```

File: cmd/gateway/s3/gateway-s3.go [hunk 7]
```diff
@@ -77,37 +77,37 @@ ENVIRONMENT VARIABLES:
...
+     {{.Prompt}} {{.EnvVarSetCommand}}MINIO_LOGGER_HTTP_ENDPOINT{{.AssignmentOperator}}"http://localhost:8000/"
```
Comment (harshavardhana) [inline cmd/gateway/s3/gateway-s3.go]:
```suggestion
     {{.Prompt}} {{.EnvVarSetCommand}} MINIO_LOGGER_HTTP_ENDPOINT{{.AssignmentOperator}}"http://localhost:8000/"
```

File: cmd/gateway/s3/gateway-s3.go [hunk 8]
```diff
@@ -77,37 +77,37 @@ ENVIRONMENT VARIABLES:
...
      {{.Prompt}} {{.HelpName}} https://play.min.io:9000
 
   4. Start minio gateway server for AWS S3 backend with edge caching enabled.
-     {{.Prompt}} {{.EnvVarSetCommand}}(.*){{.AssignmentOperator}}accesskey
-     {{.Prompt}} {{.EnvVarSetCommand}}(.*){{.AssignmentOperator}}secretkey
-     {{.Prompt}} {{.EnvVarSetCommand}}(.*){{.AssignmentOperator}}"/mnt/drive1;/mnt/drive2;/mnt/drive3;/mnt/drive4"
-     {{.Prompt}} {{.EnvVarSetCommand}}(.*){{.AssignmentOperator}}"bucket1/*;*.png"
-     {{.Prompt}} {{.EnvVarSetCommand}}(.*){{.AssignmentOperator}}40
-     {{.Prompt}} {{.EnvVarSetCommand}}(.*){{.AssignmentOperator}}80
+     {{.Prompt}} {{.EnvVarSetCommand}}MINIO_ACCESS_KEY{{.AssignmentOperator}}accesskey
```
Comment (harshavardhana) [inline cmd/gateway/s3/gateway-s3.go]:
```suggestion
     {{.Prompt}} {{.EnvVarSetCommand}} MINIO_ACCESS_KEY{{.AssignmentOperator}}accesskey
```

File: cmd/gateway/s3/gateway-s3.go [hunk 9]
```diff
@@ -77,37 +77,37 @@ ENVIRONMENT VARIABLES:
...
+     {{.Prompt}} {{.EnvVarSetCommand}}MINIO_SECRET_KEY{{.AssignmentOperator}}secretkey
+     {{.Prompt}} {{.EnvVarSetCommand}}MINIO_CACHE_DRIVES{{.AssignmentOperator}}"/mnt/drive1;/mnt/drive2;/mnt/drive3;/mnt/drive4"
```
Comment (harshavardhana) [inline cmd/gateway/s3/gateway-s3.go]:
```suggestion
     {{.Prompt}} {{.EnvVarSetCommand}} MINIO_CACHE_DRIVES{{.AssignmentOperator}}"/mnt/drive1;/mnt/drive2;/mnt/drive3;/mnt/drive4"
```

File: cmd/gateway/s3/gateway-s3.go [hunk 10]
```diff
@@ -77,37 +77,37 @@ ENVIRONMENT VARIABLES:
...
 
   4. Start minio gateway server for AWS S3 backend with edge caching enabled.
-     {{.Prompt}} {{.EnvVarSetCommand}}(.*){{.AssignmentOperator}}accesskey
-     {{.Prompt}} {{.EnvVarSetCommand}}(.*){{.AssignmentOperator}}secretkey
-     {{.Prompt}} {{.EnvVarSetCommand}}(.*){{.AssignmentOperator}}"/mnt/drive1;/mnt/drive2;/mnt/drive3;/mnt/drive4"
-     {{.Prompt}} {{.EnvVarSetCommand}}(.*){{.AssignmentOperator}}"bucket1/*;*.png"
-     {{.Prompt}} {{.EnvVarSetCommand}}(.*){{.AssignmentOperator}}40
-     {{.Prompt}} {{.EnvVarSetCommand}}(.*){{.AssignmentOperator}}80
+     {{.Prompt}} {{.EnvVarSetCommand}}MINIO_ACCESS_KEY{{.AssignmentOperator}}accesskey
+     {{.Prompt}} {{.EnvVarSetCommand}}MINIO_SECRET_KEY{{.AssignmentOperator}}secretkey
```
Comment (harshavardhana) [inline cmd/gateway/s3/gateway-s3.go]:
```suggestion
     {{.Prompt}} {{.EnvVarSetCommand}} MINIO_SECRET_KEY{{.AssignmentOperator}}secretkey
```

File: cmd/gateway/s3/gateway-s3.go [hunk 11]
```diff
@@ -77,37 +77,37 @@ ENVIRONMENT VARIABLES:
...
+     {{.Prompt}} {{.EnvVarSetCommand}}MINIO_CACHE_DRIVES{{.AssignmentOperator}}"/mnt/drive1;/mnt/drive2;/mnt/drive3;/mnt/drive4"
+     {{.Prompt}} {{.EnvVarSetCommand}}MINIO_CACHE_EXCLUDE{{.AssignmentOperator}}"bucket1/*;*.png"
```
Comment (harshavardhana) [inline cmd/gateway/s3/gateway-s3.go]:
```suggestion
     {{.Prompt}} {{.EnvVarSetCommand}} MINIO_CACHE_EXCLUDE{{.AssignmentOperator}}"bucket1/*;*.png"
```

File: cmd/gateway/s3/gateway-s3.go [hunk 12]
```diff
@@ -77,37 +77,37 @@ ENVIRONMENT VARIABLES:
...
+     {{.Prompt}} {{.EnvVarSetCommand}}MINIO_CACHE_EXPIRY{{.AssignmentOperator}}40
+     {{.Prompt}} {{.EnvVarSetCommand}}MINIO_CACHE_MAXUSE{{.AssignmentOperator}}80
```
Comment (harshavardhana) [inline cmd/gateway/s3/gateway-s3.go]:
```suggestion
     {{.Prompt}} {{.EnvVarSetCommand}} MINIO_CACHE_MAXUSE{{.AssignmentOperator}}80
```

File: cmd/gateway/s3/gateway-s3.go [hunk 13]
```diff
@@ -77,37 +77,37 @@ ENVIRONMENT VARIABLES:
...
-     {{.Prompt}} {{.EnvVarSetCommand}}(.*){{.AssignmentOperator}}secretkey
-     {{.Prompt}} {{.EnvVarSetCommand}}(.*){{.AssignmentOperator}}"/mnt/drive1;/mnt/drive2;/mnt/drive3;/mnt/drive4"
-     {{.Prompt}} {{.EnvVarSetCommand}}(.*){{.AssignmentOperator}}"bucket1/*;*.png"
-     {{.Prompt}} {{.EnvVarSetCommand}}(.*){{.AssignmentOperator}}40
-     {{.Prompt}} {{.EnvVarSetCommand}}(.*){{.AssignmentOperator}}80
+     {{.Prompt}} {{.EnvVarSetCommand}}MINIO_ACCESS_KEY{{.AssignmentOperator}}accesskey
+     {{.Prompt}} {{.EnvVarSetCommand}}MINIO_SECRET_KEY{{.AssignmentOperator}}secretkey
+     {{.Prompt}} {{.EnvVarSetCommand}}MINIO_CACHE_DRIVES{{.AssignmentOperator}}"/mnt/drive1;/mnt/drive2;/mnt/drive3;/mnt/drive4"
+     {{.Prompt}} {{.EnvVarSetCommand}}MINIO_CACHE_EXCLUDE{{.AssignmentOperator}}"bucket1/*;*.png"
+     {{.Prompt}} {{.EnvVarSetCommand}}MINIO_CACHE_EXPIRY{{.AssignmentOperator}}40
```
Comment (harshavardhana) [inline cmd/gateway/s3/gateway-s3.go]:
```suggestion
     {{.Prompt}} {{.EnvVarSetCommand}} MINIO_CACHE_EXPIRY{{.AssignmentOperator}}40
```

File: cmd/gateway/s3/gateway-s3.go [hunk 14]
```diff
@@ -77,37 +77,37 @@ ENVIRONMENT VARIABLES:
...
      {{.Prompt}} {{.HelpName}}
 
   4. Start minio gateway server for AWS S3 backend using AWS environment variables.
      NOTE: The access and secret key in this case will authenticate with MinIO instead
      of AWS and AWS envs will be used to authenticate to AWS S3.
-     {{.Prompt}} {{.EnvVarSetCommand}}(.*){{.AssignmentOperator}}aws_access_key
-     {{.Prompt}} {{.EnvVarSetCommand}}(.*){{.AssignmentOperator}}aws_secret_key
-     {{.Prompt}} {{.EnvVarSetCommand}}(.*){{.AssignmentOperator}}accesskey
-     {{.Prompt}} {{.EnvVarSetCommand}}(.*){{.AssignmentOperator}}secretkey
+     {{.Prompt}} {{.EnvVarSetCommand}}AWS_ACCESS_KEY_ID{{.AssignmentOperator}}aws_access_key
```
Comment (harshavardhana) [inline cmd/gateway/s3/gateway-s3.go]:
```suggestion
     {{.Prompt}} {{.EnvVarSetCommand}} AWS_ACCESS_KEY_ID{{.AssignmentOperator}}aws_access_key
```

File: cmd/gateway/s3/gateway-s3.go [hunk 15]
```diff
@@ -77,37 +77,37 @@ ENVIRONMENT VARIABLES:
...
+     {{.Prompt}} {{.EnvVarSetCommand}}AWS_SECRET_ACCESS_KEY{{.AssignmentOperator}}aws_secret_key
```
Comment (harshavardhana) [inline cmd/gateway/s3/gateway-s3.go]:
```suggestion
     {{.Prompt}} {{.EnvVarSetCommand}} AWS_SECRET_ACCESS_KEY{{.AssignmentOperator}}aws_secret_key
```

File: cmd/gateway/s3/gateway-s3.go [hunk 16]
```diff
@@ -77,37 +77,37 @@ ENVIRONMENT VARIABLES:
...
+     {{.Prompt}} {{.EnvVarSetCommand}}MINIO_ACCESS_KEY{{.AssignmentOperator}}accesskey
```
Comment (harshavardhana) [inline cmd/gateway/s3/gateway-s3.go]:
```suggestion
     {{.Prompt}} {{.EnvVarSetCommand}} MINIO_ACCESS_KEY{{.AssignmentOperator}}accesskey
```

File: cmd/gateway/s3/gateway-s3.go [hunk 17]
```diff
@@ -77,37 +77,37 @@ ENVIRONMENT VARIABLES:
...
+     {{.Prompt}} {{.EnvVarSetCommand}}MINIO_SECRET_KEY{{.AssignmentOperator}}secretkey
```
Comment (harshavardhana) [inline cmd/gateway/s3/gateway-s3.go]:
```suggestion
     {{.Prompt}} {{.EnvVarSetCommand}} MINIO_SECRET_KEY{{.AssignmentOperator}}secretkey
```

**Review by kannappanr — APPROVED** [review]
LGTM. Tested on Linux.

**Comment by minio-ops** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-compression-xl.sh | :heavy_check_mark: |
| mint-xl.sh | :heavy_check_mark: |
| mint-compression-dist-xl.sh | :heavy_check_mark: |
| mint-compression-fs.sh | :heavy_check_mark: |
| mint-worm.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :x: [more...](#ebd8dedb-fed2-4cf5-83c7-c83e8dd777f0) |
| mint-dist-xl.sh | :x: [more...](#f1f77a2b-facd-45a6-9b5b-daa9d221228b) |
<a name="f1f77a2b-facd-45a6-9b5b-daa9d221228b"></a>
### 7925-bfd57bb/mint-dist-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.59:30138
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp f2d5dac7d3e2:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 0 seconds
(2/14) Running aws-sdk-java tests ... done in 1 seconds
(3/14) Running aws-sdk-php tests ... done in 42 seconds
(4/14) Running aws-sdk-ruby tests ... done in 3 seconds
(5/14) Running awscli tests ... done in 2 minutes and 0 seconds
(6/14) Running healthcheck tests ... done in 0 seconds
(7/14) Running mc tests ... done in 52 seconds
(8/14) Running minio-dotnet tests ... done in 33 seconds
(9/14) Running minio-go tests ... done in 1 minutes and 1 seconds
(10/14) Running minio-java tests ... FAILED in 38 seconds
{
  "name": "minio-java",
  "function": "presignedPutObject(String bucketName, String objectName)",
  "duration": 16,
  "status": "FAIL",
  "error": "java.lang.Exception: failed to create object. Response: Response{protocol=http/1.1, code=503, message=Service Unavailable, url=http://72.28.97.59:30138/minio-java-test-tgk7tr/minio-java-test-1q21vib?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=minio%2F20190713%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20190713T050431Z&X-Amz-Expires=604800&X-Amz-SignedHeaders=host&X-Amz-Signature=31e3683514c5b53237566070f49804842befb41acceb53fe082f6f997090ce74}, Response body: <?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<Error><Code>SlowDown</Code><Message>Please reduce your request</Message><Key>minio-java-test-1q21vib</Key><BucketName>minio-java-test-tgk7tr</BucketName><Resource>/minio-java-test-tgk7tr/minio-java-test-1q21vib</Resource><RequestId>15B0DF0236EC16AB</RequestId><HostId>7ee8868d-0a00-49b6-af83-80b56ac97eff</HostId></Error> >>> [FunctionalTest.writeObject(FunctionalTest.java:236), FunctionalTest.presignedPutObject_test1(FunctionalTest.java:1871), FunctionalTest.runTests(FunctionalTest.java:2998), FunctionalTest.main(FunctionalTest.java:3118)]"
}

Executed 9 out of 14 tests successfully.
```
<a name="ebd8dedb-fed2-4cf5-83c7-c83e8dd777f0"></a>
### 7925-bfd57bb/mint-large-bucket.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.56:30519
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp d4a5040ba9a6:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 5 seconds
(2/14) Running aws-sdk-java tests ... done in 2 seconds
(3/14) Running aws-sdk-php tests ... done in 52 seconds
(4/14) Running aws-sdk-ruby tests ... done in 12 seconds
(5/14) Running awscli tests ... done in 1 minutes and 27 seconds
(6/14) Running healthcheck tests ... done in 1 seconds
(7/14) Running mc tests ... FAILED in 1 minutes and 22 seconds
{
  "name": "mc",
  "duration": "78395",
  "function": "test_put_object_with_storage_class",
  "status": "FAIL",
  "error": "/mint/run/core/mc/mc --config-dir /tmp/.mc-31103 --quiet --no-color cp --storage-class REDUCED_REDUNDANCY /mint/data/datafile-1-MB myminio/mc-test-bucket-18952/mc-test-object-9627  >>> \n`/mint/data/datafile-1-MB` -> `myminio/mc-test-bucket-18952/mc-test-object-9627`\nmc: <ERROR> Failed to copy `/mint/data/datafile-1-MB`. Please reduce your request\nmc: <ERROR> Session safely terminated. To resume session `mc session resume lKgzgHmr`"
}

Executed 6 out of 14 tests successfully.
```

**Review by nitisht — APPROVED** [review]

**Comment by minio-ops** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-compression-xl.sh | :heavy_check_mark: |
| mint-xl.sh | :heavy_check_mark: |
| mint-compression-dist-xl.sh | :heavy_check_mark: |
| mint-compression-fs.sh | :heavy_check_mark: |
| mint-worm.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :x: [more...](#7b3cbe21-7d7d-40b0-bf14-2f9f7ebb5043) |
| mint-dist-xl.sh | :x: [more...](#807885bf-d4bc-4c8f-85b8-bfc2deef6a0a) |
<a name="807885bf-d4bc-4c8f-85b8-bfc2deef6a0a"></a>
### 7925-515a09d/mint-dist-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.51:32201
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp f618959d69cc:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 1 seconds
(2/14) Running aws-sdk-java tests ... done in 1 seconds
(3/14) Running aws-sdk-php tests ... done in 44 seconds
(4/14) Running aws-sdk-ruby tests ... done in 3 seconds
(5/14) Running awscli tests ... done in 2 minutes and 8 seconds
(6/14) Running healthcheck tests ... done in 0 seconds
(7/14) Running mc tests ... done in 51 seconds
(8/14) Running minio-dotnet tests ... done in 43 seconds
(9/14) Running minio-go tests ... done in 1 minutes and 8 seconds
(10/14) Running minio-java tests ... FAILED in 1 minutes and 39 seconds
{
  "name": "minio-java",
  "function": "listIncompleteUploads(String bucketName, String prefix)",
  "duration": 587,
  "status": "FAIL",
  "error": "error occurred\nErrorResponse(code=SlowDown, message=Please reduce your request, bucketName=minio-java-test-2mi7l3i, objectName=minio-java-test-2lir1sk, resource=/minio-java-test-2mi7l3i/minio-java-test-2lir1sk, requestId=15B0E07486745073, hostId=4a14ac1f-9d87-4d48-8da0-0311279c350c)\nrequest={method=DELETE, url=http://72.28.97.51:32201/minio-java-test-2mi7l3i/minio-java-test-2lir1sk?uploadId=6101f14f-5bf3-4beb-a969-d06174a3aff9, headers=Host: 72.28.97.51:32201\nUser-Agent: MinIO (amd64; amd64) minio-java/dev\nx-amz-content-sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855\nx-amz-date: 20190713T053101Z\nAuthorization: AWS4-HMAC-SHA256 Credential=*REDACTED*/20190713/us-east-1/s3/aws4_request, SignedHeaders=host;x-amz-content-sha256;x-amz-date, Signature=*REDACTED*\n}\nresponse={code=503, headers=Accept-Ranges: bytes\nContent-Length: 363\nContent-Security-Policy: block-all-mixed-content\nContent-Type: application/xml\nRetry-After: 120\nServer: MinIO/DEVELOPMENT.2019-07-13T05-10-46Z\nVary: Origin\nX-Amz-Request-Id: 15B0E07486745073\nX-Xss-Protection: 1; mode=block\nDate: Sat, 13 Jul 2019 05:31:02 GMT\n}\n >>> [io.minio.MinioClient.executeReq(MinioClient.java:1204), io.minio.MinioClient.execute(MinioClient.java:1070), io.minio.MinioClient.executeDelete(MinioClient.java:1347), io.minio.MinioClient.abortMultipartUpload(MinioClient.java:5149), io.minio.MinioClient.putObject(MinioClient.java:4337), io.minio.MinioClient.putObject(MinioClient.java:4183), FunctionalTest.listIncompleteUploads_test2(FunctionalTest.java:1639), FunctionalTest.runTests(FunctionalTest.java:2989), FunctionalTest.main(FunctionalTest.java:3118)]"
}

Executed 9 out of 14 tests successfully.
```
<a name="7b3cbe21-7d7d-40b0-bf14-2f9f7ebb5043"></a>
### 7925-515a09d/mint-large-bucket.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.51:30668
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 8ef3fe47f186:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 4 seconds
(2/14) Running aws-sdk-java tests ... done in 2 seconds
(3/14) Running aws-sdk-php tests ... done in 52 seconds
(4/14) Running aws-sdk-ruby tests ... done in 17 seconds
(5/14) Running awscli tests ... done in 2 minutes and 23 seconds
(6/14) Running healthcheck tests ... done in 1 seconds
(7/14) Running mc tests ... FAILED in 2 minutes and 11 seconds
{
  "name": "mc",
  "duration": "98506",
  "function": "test_mirror_list_objects_storage_class",
  "status": "FAIL",
  "error": "/mint/run/core/mc/mc --config-dir /tmp/.mc-15849 --quiet --no-color mirror --storage-class REDUCED_REDUNDANCY /mint/data myminio/mc-test-bucket-29756  >>> \n`/mint/data/datafile-1-MB` -> `myminio/mc-test-bucket-29756/datafile-1-MB`\n`/mint/data/datafile-0-b` -> `myminio/mc-test-bucket-29756/datafile-0-b`\n`/mint/data/datafile-1-kB` -> `myminio/mc-test-bucket-29756/datafile-1-kB`\n`/mint/data/datafile-1-b` -> `myminio/mc-test-bucket-29756/datafile-1-b`\n`/mint/data/datafile-100-kB` -> `myminio/mc-test-bucket-29756/datafile-100-kB`\n`/mint/data/datafile-10-kB` -> `myminio/mc-test-bucket-29756/datafile-10-kB`\n`/mint/data/datafile-1.03-MB` -> `myminio/mc-test-bucket-29756/datafile-1.03-MB`\n`/mint/data/datafile-10-MB` -> `myminio/mc-test-bucket-29756/datafile-10-MB`\n`/mint/data/datafile-129-MB` -> `myminio/mc-test-bucket-29756/datafile-129-MB`\n`/mint/data/datafile-33-kB` -> `myminio/mc-test-bucket-29756/datafile-33-kB`\n`/mint/data/datafile-11-MB` -> `myminio/mc-test-bucket-29756/datafile-11-MB`\n`/mint/data/datafile-5-MB` -> `myminio/mc-test-bucket-29756/datafile-5-MB`\n`/mint/data/datafile-6-MB` -> `myminio/mc-test-bucket-29756/datafile-6-MB`\n`/mint/data/datafile-5243880-b` -> `myminio/mc-test-bucket-29756/datafile-5243880-b`\n`/mint/data/datafile-65-MB` -> `myminio/mc-test-bucket-29756/datafile-65-MB`\nmc: <ERROR> Failed to copy `/mint/data/datafile-11-MB`. Please reduce your request\nmc: <ERROR> Failed to copy `/mint/data/datafile-10-MB`. Please reduce your request\nmc: <ERROR> Failed to copy `/mint/data/datafile-65-MB`. Please reduce your request\nmc: <ERROR> Failed to copy `/mint/data/datafile-129-MB`. Please reduce your request\nTotal: 233.17 MiB, Transferred: 478.80 MiB, Speed: 4.86 MiB/s"
}

Executed 6 out of 14 tests successfully.
```
