### PR TITLE
Fixed race during parallel PutObjectPart requests

### LINKED ISSUE #1764: XL: CompleteMultipartUpload fails with InvalidPart with 'aws cli'
```
ERRO[3302] Unable to complete multipart upload.          cause=One or more of the specified parts could not be found sysInfo=map[host.name:command.local host.lang:go1.6 host.cpus:4 mem.heap.used:72MB host.os:darwin host.arch:amd64 mem.heap.total:144MB mem.used:72MB mem.total:154MB] type=main.InvalidPart
```

```
harsha@command:~/Repositories/minio-js (master)$ aws s3 cp ~/tests/bigfile s3://testbucket/test
upload failed: ../../tests/bigfile to s3://testbucket/test
A client error (InvalidPart) occurred when calling the CompleteMultipartUpload operation: One or more of the specified parts could not be found.
```

### PR DESCRIPTION
**Pull request by krisis**
The race is between two parallel PutObjectPart requests updating partsInfo in xl.json.
Previously, it was being updated under a RLock().

Closes #1764

### CODE REVIEW

File: xl-v1-multipart.go [hunk 1]
```diff
@@ -209,7 +210,6 @@ func (xl xlObjects) putObjectPartCommon(bucket string, object string, uploadID s
 		return "", toObjectErr(err, minioMetaBucket, partPath)
 	}
```
Comment (harshavardhana) [inline xl-v1-multipart.go:212]: Why was this comment removed ?

Comment (krisis) [inline xl-v1-multipart.go:212]: I thought that the comment doesn't add much after I moved `readXLMetadata` right after writing the part to the disks. Do you think we should add it back?

Comment (harshavardhana) [inline xl-v1-multipart.go:212]: > I thought that the comment doesn't add much after I moved readXLMetadata right after writing the part to the disks. Do you think we should add it back?

It is okay to keep it.
