### PR TITLE
fix: allow concurrent SFTP connections

### LINKED ISSUE #17914: SFTP server seems limited to one connection at a time.
## NOTE

Want to upload file into bucket using the SFTP capability of minio using FilleZilla.

## Expected Behavior
Upload succeeded

## Current Behavior
The first connection is ok, I can browse over buckets.
When I want to upload a file, FilleZilla open a new connection: waiting, timeout, waiting, timeout...
Connection with minio SFTP server will never get established.

## Steps to Reproduce (for bugs)
1. Connect to minio SFTP server with Fillzilla (using ROOT user in my case)
2. Browse to bucket
3. Upload a file

Or

1. Open two terminal
2. For each one connect to minio sftp server

## Your Environment
Linux: debian 11
Minio version: RELEASE.2023-08-23T10-07-06Z (go1.19.12 linux/amd64)

### PR DESCRIPTION
**Pull request by harshavardhana**
## Community Contribution License
All community contributions in this pull request are licensed to the project maintainers
under the terms of the [Apache 2 license] (https://www.apache.org/licenses/LICENSE-2.0). 
By creating this pull request I represent that I have the right to license the 
contributions to the project maintainers under the Apache 2 license.

## Description
fix: allow concurrent SFTP connections

## Motivation and Context
current implementation did not fully implement
the concurrent SFTP connection implementation,
This PR properly handles this.

fixes #17914

## How to test this PR?
Start a MinIO server with SFTP enabled

```
minio server ~/test --sftp="address=:8022" --sftp="ssh-private-key=${HOME}/.ssh/id_rsa"
```

First connection works
```
sftp -P 8022 minioadmin@localhost
```

Second connection hangs
```
sftp -P 8022 minioadmin@localhost
```

This PR fixes this behavior, can be reproduced with FileZilla as well

## Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Optimization (provides speedup with no functional changes)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [ ] Fixes a regression (If yes, please add `commit-id` or `PR #` here)
- [ ] Unit tests added/updated
- [ ] Internal documentation updated
- [ ] Create a documentation update request [here](https://github.com/minio/docs/issues/new?label=doc-change,title=Doc+Updated+Needed+For+PR+github.com%2fminio%2fminio%2fpull%2fNNNNN)

### CODE REVIEW

File: cmd/ftp-server.go [hunk 1]
```diff
@@ -176,54 +239,29 @@ func startSFTPServer(c *cli.Context) {
...
-
-			server := sftp.NewRequestServer(channel, NewSFTPDriver(sconn.Permissions))
-			if err := server.Serve(); err == io.EOF {
-				server.Close()
-			} else if err != nil {
-				logger.Fatal(err, "unable to start SFTP server")
+				if max := 1 * time.Second; tempDelay > max {
+					tempDelay = max
+				}
+				logger.LogOnceIf(context.Background(), fmt.Errorf("error while accepting connections: %w, retring in %s", err, tempDelay), "accept-limit-sftp")
```
Comment (poornas) [inline cmd/ftp-server.go:257]:
```suggestion
				logger.LogOnceIf(context.Background(), fmt.Errorf("error while accepting connections: %w, retrying in %s", err, tempDelay), "accept-limit-sftp")
```

Comment (poornas) [inline cmd/ftp-server.go:257]:
```suggestion
				logger.LogOnceIf(context.Background(), fmt.Errorf("error while accepting connections: %w, retrying in %s", err, tempDelay), "accept-limit-sftp")
```

Comment (poornas) [inline cmd/ftp-server.go]:
```suggestion
				logger.LogOnceIf(context.Background(), fmt.Errorf("error while accepting connections: %w, retrying in %s", err, tempDelay), "accept-limit-sftp")
```

**Review by poornas — CHANGES_REQUESTED** [review]

**Review by poornas — APPROVED** [review]
