### PR TITLE
gateway/azure: allow putObject to support block based upload

### LINKED ISSUE #6542: Minio using Azure Blob Storage Crashes after more than 1GB it's uploaded
Hi folks, 

I'm using Kubernetes in Azure AKS running a deployment with latest version of Minio
it connects fine, I'm able to login and no problem ... but when I'm trying to upload files which size is more than 1GB that container gets killed and I'm not able to see any kind of logs. 

After that, I thought it was an issue with Nginx ingress and I created and expose a service to access directly to Minio, instead via Nginx. 
I tried to upload same file and got that same error.

After that, just to be sure, I launched a Docker container with same version (latest one) in my local, export port 9000 and do the same that I mentioned above. 
And same happened. 

As mentioned, I can't get any kind of log and don't know why that container gets killed after almost upload that file. 

## Expected Behavior

Upload more than 1GB files 

## Current Behavior

It crashes after try to upload files more than 1GB

## Steps to Reproduce (for bugs)

1. Locally run minio latest docker image and with `gateway azure` CMD 
```
docker run -tid -p 9000:9000 --name azure-s3 \
 -e "MINIO_ACCESS_KEY=nameOfyourBlob" \
 -e "MINIO_SECRET_KEY=KEYOFYOURBLOB" \
 -e "MINIO_HTTP_TRACE=/tmp/minio.log" \
  -v ~/data:/data \
 -v ~/data/config:/root/.minio minio/minio gateway azure
```
2. Go to http://127.0.0.1:9000
3. Put your Azure Blob Storage credentials in there
4. Create a bucket
5. Upload a file with more that 1GB size within that bucket 

## Context

AKS Kubernetes
Locally Mac OS X Mojave

## Your Environment

* Version used: Latest docker image
* Environment name and version: No Nginx

### LINKED ISSUE #6550: minio + Azure + Arq: "sha1 of uploaded file does not match" error
## Expected Behavior
Arq should work through the minio Azure gateway. Since it looks from previous issues that Arq was tested with minio before, this might be specific to the Azure gateway. There is no error from the logs (see below), so it seems that there is something that Arq is not expecting, but unfortunately not logging.

Would appreciate your input @krishnasrinivas @sreitshamer; I know this is a corner case but fixing this would allow me to use Arq with Azure Storage. 

## Current Behavior
When adding a folder to backup, an error "sha1 of uploaded file does not match" is received when Arq creates the encryption file.

## Steps to Reproduce (for bugs)
Start a minio instance with `minio gateway azure`. Use the minio endpoint to configure Arq.

## Your Environment

minio version:

```
Version: 2018-09-25T21:34:43Z
Release-Tag: RELEASE.2018-09-25T21-34-43Z
Commit-ID: aa4e2b1542b98097e08680f21b790de0b776378c
```

minio gateway runs on a macOS 10.11 machine.

Arq logs:

```
2018/10/01 17:57:41:439  DETAIL [thread 183eb] creating directory /testminiotco-arq/C823368A-2017-4A7A-89A4-A4669AC094D2
2018/10/01 17:57:41:439  DETAIL [thread 183eb] creating directory s3:10.0.0.100:/testminiotco-arq/C823368A-2017-4A7A-89A4-A4669AC094D2
2018/10/01 17:57:41:443  DEBUG [thread 183eb] 0x7fa1f32379a0 RemoteFS.m:343 cache not loaded; getting items for parent dir of /testminiotco-arq/C823368A-2017-4A7A-89A4-A4669AC094D2/encryptionv3.dat
2018/10/01 17:57:41:443  DEBUG [thread 183eb] 0x7fa1f32379a0 RemoteFS.m:372 cachedItemsByNameForDirectory returned nil; error=Error Domain=ItemsDBErrorDomain Code=-31 "itemsByNameInDirectory: cache not loaded for directory /testminiotco-arq/C823368A-2017-4A7A-89A4-A4669AC094D2" UserInfo={NSLocalizedDescription=itemsByNameInDirectory: cache not loaded for directory /testminiotco-arq/C823368A-2017-4A7A-89A4-A4669AC094D2}
2018/10/01 17:57:41:443  DETAIL [thread 183eb] getting items in directory s3:10.0.0.100:/testminiotco-arq/C823368A-2017-4A7A-89A4-A4669AC094D2
2018/10/01 17:57:41:443  DEBUG [thread 183eb] 0x7fa1f3071710 URLConnection.m:46 GET http://10.0.0.100:9000/testminiotco-arq/?prefix=C823368A-2017-4A7A-89A4-A4669AC094D2/&delimiter=/&max-keys=500
2018/10/01 17:57:41:444  DEBUG [thread 183eb] 0x7fa1f3071710 URLConnection.m:147 NSURLConnection started with no request body
2018/10/01 17:57:41:606  DEBUG [thread 183eb] 0x7fa1f3071710 URLConnection.m:193 response: status = 200, Content-Length = (null), Transfer-Encoding = Identity
2018/10/01 17:57:41:606  DEBUG [thread 183eb] 0x7fa1f3071710 URLConnection.m:209 response body with no Transfer-Encoding; responseData is 302 bytes
2018/10/01 17:57:41:606  DEBUG [thread 183eb] 0x7fa1f2c048b0 S3Request.m:257 HTTP 200; returning response length=302
2018/10/01 17:57:41:607  DEBUG [thread 183eb] 0x7fa1f2d08ef0 TargetItemsDB.m:369 inserting 0 rows into the cache db for /testminiotco-arq/C823368A-2017-4A7A-89A4-A4669AC094D2
2018/10/01 17:57:41:608  DEBUG [thread 183eb] 0x7fa1f2d08ef0 TargetItemsDB.m:375 inserted 0 rows into the cache db for /testminiotco-arq/C823368A-2017-4A7A-89A4-A4669AC094D2
2018/10/01 17:57:41:609  DEBUG [thread 183eb] 0x7fa1f32379a0 RemoteFS.m:352 didn't find encryptionv3.dat in parent dir /testminiotco-arq/C823368A-2017-4A7A-89A4-A4669AC094D2
2018/10/01 17:57:41:609  DETAIL [thread 183eb] creating file s3:10.0.0.100:/testminiotco-arq/C823368A-2017-4A7A-89A4-A4669AC094D2/encryptionv3.dat
2018/10/01 17:57:41:609  DEBUG [thread 183eb] 0x7fa1f2fbc1e0 URLConnection.m:46 PUT http://10.0.0.100:9000/testminiotco-arq/C823368A-2017-4A7A-89A4-A4669AC094D2/encryptionv3.dat
2018/10/01 17:57:41:609  DEBUG [thread 183eb] 0x7fa1f2fbc1e0 URLConnection.m:145 NSURLConnection started with request body (180 bytes)
2018/10/01 17:57:41:689  DEBUG [thread 183eb] 0x7fa1f2fbc1e0 URLConnection.m:193 response: status = 200, Content-Length = 0, Transfer-Encoding = (null)
2018/10/01 17:57:41:689  DEBUG [thread 183eb] 0x7fa1f2fbc1e0 URLConnection.m:209 response body with no Transfer-Encoding; responseData is 0 bytes
2018/10/01 17:57:41:689  DEBUG [thread 183eb] 0x7fa1f337d4e0 S3Request.m:257 HTTP 200; returning response length=0
2018/10/01 17:57:41:689  DEBUG [thread 183eb] 0x7fa1f32e67d0 S3Service.m:354 uploaded 180 bytes to /testminiotco-arq/C823368A-2017-4A7A-89A4-A4669AC094D2/encryptionv3.dat in 0.1 seconds (2249 bytes/sec)
2018/10/01 17:57:41:690  DEBUG [thread 1afab] 0x7fa1f32e8f00 HTTPInputStream.m:30 deallocing HTTPInputStream 0x7fa1f32e8f00
```

Last entries from `minio.log`:

```
[REQUEST (objectAPIHandlers).PutObjectHandler-fm] [153840946.161095] [2018-10-01 17:57:41 +0200]
PUT /testminiotco-arq/C823368A-2017-4A7A-89A4-A4669AC094D2/encryptionv3.dat
Host: 10.0.0.100
Content-Length: 180
Authorization: AWS4-HMAC-SHA256 Credential=testminiotco/20181001/us-east-1/s3/aws4_request,SignedHeaders=content-length;host;x-amz-content-sha256;x-amz-date,Signature=75b7e4cba5fb8ed400cc18e84a33c0b6717a577cfd5a094fc6cf8e0248559689
User-Agent: Arq/5.14 CFNetwork/760.9 Darwin/15.6.0 (x86_64)
Connection: keep-alive
Accept: */*
Accept-Language: en-us
X-Amz-Date: 20181001T155741Z
Accept-Encoding: gzip, deflate
X-Amz-Content-Sha256: ecdc64e494481a868f469ebabdb7b9f0be8272b2b80a30d4de122ef5a6b2d54d

<BODY>

[RESPONSE] [153840946.161095] [2018-10-01 17:57:41 +0200]
200 OK
X-Xss-Protection: 1; mode=block
Content-Security-Policy: block-all-mixed-content
X-Amz-Request-Id: 1559874126681654
Etag: "0x8D627B69E804C5A-1"
Server: Minio/RELEASE.2018-09-25T21-34-43Z (darwin; amd64)
Accept-Ranges: bytes
Vary: Origin

<BODY>
```

### PR DESCRIPTION
**Pull request by harshavardhana**
## Description
Current implementation simply uses all the memory locally
and crashes when a large upload is initiated using Minio 
browser UI.

This PR uploads stream in blocks and finally commits the blocks
allowing for low memory footprint while uploading large objects
through Minio browser UI.

This PR also adds ETag compatibility for single PUT operations

## Motivation and Context
Fixes #6542
Fixes #6550

## Regression
No

## How Has This Been Tested?
Upload a large object using Minio browser UI, without this PR the upload will fail.  A large object here means > 256MiB 

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added unit tests to cover my changes.
- [ ] I have added/updated functional tests in [mint](https://github.com/minio/mint). (If yes, add `mint` PR # here: )
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by harshavardhana** [comment]
Ran mint tests locally in FULL mode runs fine, requesting reviewers please @nitisht @kannappanr

**Comment by harshavardhana** [comment]
updated the PR, this PR also resolves #6550 for single PUT operations we save ETag and it corresponds to md5sum of the object.

File: cmd/gateway/azure/gateway-azure.go [hunk 1]
```diff
@@ -685,10 +685,22 @@ func (a *azureObjects) GetObjectInfo(ctx context.Context, bucket, object string,
 		return objInfo, azureToObjectError(err, bucket, object)
 	}
 
+	etag := minio.ToS3ETag(blob.Properties.Etag)
```
Comment (vadmeste) [inline cmd/gateway/azure/gateway-azure.go:699]: This is not an obvious change @harshavardhana, let's do it in another PR

File: cmd/gateway/azure/gateway-azure.go [hunk 2]
```diff
@@ -700,15 +712,103 @@ func (a *azureObjects) GetObjectInfo(ctx context.Context, bucket, object string,
...
+
+	if err = objBlob.PutBlockList(blocks, nil); err != nil {
 		return objInfo, azureToObjectError(err, bucket, object)
 	}
+
+	if len(metadata) == 0 {
+		metadata = map[string]string{}
+	}
+	metadata["x-amz-meta-etag"] = hex.EncodeToString(data.MD5Current())
+	if len(metadata) > 0 {
```
Comment (vadmeste) [inline cmd/gateway/azure/gateway-azure.go]: it looks like metadata will never be empty in this stage (according to the previous line)

File: cmd/gateway/azure/gateway-azure.go [hunk 3]
```diff
@@ -685,10 +685,22 @@ func (a *azureObjects) GetObjectInfo(ctx context.Context, bucket, object string,
 		return objInfo, azureToObjectError(err, bucket, object)
 	}
 
+	etag := minio.ToS3ETag(blob.Properties.Etag)
+	switch {
+	case blob.Properties.ContentMD5 != "":
```
Comment (vadmeste) [inline cmd/gateway/azure/gateway-azure.go:701]: This looks like a breaking change, since it seems that we are now generating new ETag which are equal to md5sum in put object, I think then that the etag/md5sum problem will be fixed with new uploaded objects

**Review by vadmeste — COMMENTED** [review]
Some comments

File: cmd/gateway/azure/gateway-azure.go (hunk 3 above)
Comment (harshavardhana) [reply cmd/gateway/azure/gateway-azure.go:701]: It's not a breaking change.. it's simply a fix.

File: cmd/gateway/azure/gateway-azure.go (hunk 1 above)
Comment (harshavardhana) [reply cmd/gateway/azure/gateway-azure.go:699]: What is not obvious ? This refactor fixes this issue too.

File: cmd/gateway/azure/gateway-azure.go (hunk 2 above)
Comment (harshavardhana) [reply cmd/gateway/azure/gateway-azure.go]: Will fix

File: cmd/gateway/azure/gateway-azure.go (hunk 3 above)
Comment (vadmeste) [reply cmd/gateway/azure/gateway-azure.go:701]: > It's not a breaking change.

If I understood correctly, GetObjectInfo will return different ETag value for HEAD object when users update their Minio verion

Comment (harshavardhana) [reply cmd/gateway/azure/gateway-azure.go:701]: Yes but it's not something they are dependent on anyways, this simply addresses the fact that some applications are not working without this change.  HTTP reply wise its a breaking change yes but we have a broken implementation anyways so it is a fix for the broken implementation.

**Review by vadmeste — APPROVED** [review]
LGTM & tested

**Review by poornas — APPROVED** [review]
LGTM
