### PR TITLE
handlers: overhaul entire writErrorResponse, simplify.

### LINKED ISSUE #1451: xl:  'mc ls' results in 500 internal server error
- `mc mb myminio/test/` 
- `mc cp a.sh myminio/test/`

The XL setup has 5 data and parity disks 

Now deleting the folder corresponding to the file `a.sh` on disks containing the parity. 
- `rm -r /mnt/sd[g-k]1/ec-dir/test/a.sh/` (sdg1-sdk1 contains parity files)

Now do 
-  `mc ls myminio/test/`

It throws `500 internal server error` 

Here is something more interesting, 
Copy one more file to the same bucket. 
-  `mc cp b.sh myminio/test/`
  Now do 
-  `mc ls myminio/test/`
  This works and you get both the files 
  `a.sh`
  
  `b.sh` 

but if you try 
-  `mc ls myminio/test/a.sh`

It again throws `500 internal server error`. 

On trying 
- `mc cp -r myminio/smalltest/ /tmp/`

It fails with 
`mc: <ERROR> Failed to copy ‘http://localhost:9000/smalltest/a.sh’. The specified key does not exist.`

### PR DESCRIPTION
**Pull request by harshavardhana**

### CODE REVIEW

File: api-errors.go [hunk 1]
```diff
@@ -190,15 +190,15 @@ var errorCodeResponse = map[APIErrorCode]APIError{
...
 		HTTPStatusCode: http.StatusInternalServerError,
 	},
-	ErrInsufficientReadResources: {
-		Code:           "InternalError",
-		Description:    "We cannot satisfy sufficient read resources requested at this moment, please try again.",
-		HTTPStatusCode: http.StatusInternalServerError,
+	ErrReadQuorum: {
+		Code:           "ReadQuorum",
+		Description:    "We cannot satisfy sufficient read quorum for the requested resource at this moment, please try again.",
+		HTTPStatusCode: http.StatusServiceUnavailable,
```
Comment (abperiasamy) [inline api-errors.go:196]: Multiple disk failures. Unable to reconstruct data.

File: api-errors.go [hunk 2]
```diff
@@ -190,15 +190,15 @@ var errorCodeResponse = map[APIErrorCode]APIError{
...
 	},
-	ErrInsufficientWriteResources: {
-		Code:           "InternalError",
-		Description:    "We cannot satisfy sufficient write resources requested at this moment, please try again.",
-		HTTPStatusCode: http.StatusInternalServerError,
+	ErrWriteQuorum: {
+		Code:           "WriteQuorum",
+		Description:    "We cannot satisfy sufficient write quorum for the requested resource at this moment, please try again.",
+		HTTPStatusCode: http.StatusServiceUnavailable,
 	},
```
Comment (abperiasamy) [inline api-errors.go:202]: Multiple disk failures. Unable to write data.
