### PR TITLE
Ignore logging some tcp routine errors

### LINKED ISSUE #5096: Error log after accessing to Minio Browser using Chrome/Firefox when TLS is enabled
## Expected Behavior
No log since there is no error.

## Current Behavior
```
time="2017-10-21T11:26:33Z" level=error msg="Error in reading from new TLS connection 84.232.207.221:56911 at server 172.17.0.2:9000" cause=EOF source="[listener.go:188:github.com/minio/minio/pkg/http.(*httpListener).start.func2()]"
time="2017-10-21T11:26:33Z" level=error msg="Error in reading from new TLS connection 84.232.207.221:56910 at server 172.17.0.2:9000" cause=EOF source="[listener.go:188:github.com/minio/minio/pkg/http.(*httpListener).start.func2()]"
time="2017-10-21T11:26:33Z" level=error msg="Error in reading from new TLS connection 84.232.207.221:56913 at server 172.17.0.2:9000" cause=EOF source="[listener.go:188:github.com/minio/minio/pkg/http.(*httpListener).start.func2()]"
time="2017-10-21T11:26:33Z" level=error msg="Error in reading from new TLS connection 84.232.207.221:56912 at server 172.17.0.2:9000" cause=EOF source="[listener.go:188:github.com/minio/minio/pkg/http.(*httpListener).start.func2()]"
```

## Possible Solution
Disabling peeking after a successful handshake, browsers seem to open a TLS connection but doesn't really send any data 

## Steps to Reproduce (for bugs)
1. Configure a Minio server with TLS certificate
2. Open Minio Browser with Chrome or Firefox (and probably other browsers)

## Context
Fixing a bug

## Your Environment
* Version used (`minio version`): 65a817fe8c49564abf7662cc2cbc9e09009661c7
* Operating System and version (`uname -a`):  Ubuntu 16.04

### PR DESCRIPTION
**Pull request by vadmeste**
## Description
This will avoid printing non useful logs when browsers open connections
but doesn't send any data or prematurely close connections

## Motivation and Context
Fixes #5096 

## How Has This Been Tested?
go test + Manually

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

File: pkg/http/listener.go [hunk 1]
```diff
@@ -179,24 +179,8 @@ func (listener *httpListener) start() {
...
-				bufconn.Close()
-				return
-			}
-
-			// Return bufconn if read data is a valid HTTP method.
-			tokens := strings.SplitN(string(data), " ", 2)
-			if isHTTPMethod(tokens[0]) {
-				send(acceptResult{bufconn, nil}, doneCh)
-				return
-			}
```
Comment (harshavardhana) [inline pkg/http/listener.go]: This would be incorrect @vadmeste Peek is fine but we don't need to print for `io.EOF` that's all. Read the handleConn above..

```
  // Peek could fail legitimately when clients abruptly close
  // connection. E.g. Chrome browser opens connections speculatively to
  // speed up loading of a web page. Peek may also fail due to network
  // saturation on a transport with read timeout set. All other kind of
  // errors should be logged for further investigation. 
  if !ignoreErr(err) {
```

**Review by harshavardhana — CHANGES_REQUESTED** [review]

File: pkg/http/listener.go (hunk 1 above)
Comment (vadmeste) [reply pkg/http/listener.go]: We don't need peeking at this stage @harshavardhana, peeking is only to differentiate between TLS & plain HTTP, but here we are sure that this is a TLS connection because the handshake was already successful. Golang HTTP can handle HTTP errors already and we don't need to add our own code for that.

Comment (harshavardhana) [reply pkg/http/listener.go]: No it is on purpose @vadmeste we are also validating if the HTTP method sent is correct as well.

Comment (vadmeste) [reply pkg/http/listener.go]: > No it is on purpose @vadmeste we are also validating if the HTTP method sent is correct as well.

Won't golang http also validate that ?

Comment (harshavardhana) [reply pkg/http/listener.go]: We are not worried about that @vadmeste `pkg/http` is a lower level implementation with our own requirements.  It is because when you manage a `conn`  for HTTP you are supposed to handle everything related to HTTP at this level. Passing the issue to Go and expect it to fail in unexpected ways would be incosistent.  

`pkg/http` is not a thin layer implementation it is purposefully built to handle these conditions.

Comment (vadmeste) [reply pkg/http/listener.go]: > Passing the issue to Go and expect it to fail in unexpected ways would be incosistent.

Are you saying that pkg/http should validate all the http protocol ?

Comment (harshavardhana) [reply pkg/http/listener.go]: I mean the Conn validation. Not HTTP parsing. Simple fix is what I mentioned above. 

Removing method validation is incorrect.

**Comment by vadmeste** [comment]
PR updated.

File: pkg/http/listener.go [hunk 2]
```diff
@@ -89,13 +90,22 @@ type httpListener struct {
 	errorLogFunc           func(error, string, ...interface{}) // function to be called on errors.
 }
 
-// ignoreErr returns true if error is due to a network timeout or
+// isRoutineNetErr returns true if error is due to a network timeout or
 // io.EOF and false otherwise
-func ignoreErr(err error) bool {
+func isRoutineNetErr(err error) bool {
```
Comment (balamurugana) [inline pkg/http/listener.go]: I think you can retain the function name as `ignoreErr()`. It is clear enough I guess.

File: pkg/http/listener.go [hunk 3]
```diff
@@ -89,13 +90,22 @@ type httpListener struct {
...
+		if nErr.Timeout() {
+			return true
+		}
+		// Check if the error is a tcp connection reset
+		if syscallErr, ok := nErr.Err.(*os.SyscallError); ok {
+			if errno, ok := syscallErr.Err.(syscall.Errno); ok {
+				return errno == syscall.ECONNRESET
+			}
+		}
+		return false
```
Comment (balamurugana) [inline pkg/http/listener.go]: You could do `syscall.ECONNREST` first.  This return statement can be avoided

File: pkg/http/listener.go [hunk 4]
```diff
@@ -182,10 +192,12 @@ func (listener *httpListener) start() {
 			// Peek bytes of maximum length of all HTTP methods.
 			data, err := bufconn.Peek(methodMaxLen)
 			if err != nil {
-				if listener.errorLogFunc != nil {
-					listener.errorLogFunc(err,
-						"Error in reading from new TLS connection %s at server %s",
-						bufconn.RemoteAddr(), bufconn.LocalAddr())
+				if !isRoutineNetErr(err) {
+					if listener.errorLogFunc != nil {
```
Comment (balamurugana) [inline pkg/http/listener.go]: You could do `if listener.errorLogFunc != nil && !ignoreErr(err)` to avoid necessary nesting `if`

Comment (vadmeste) [reply pkg/http/listener.go]: Done

File: pkg/http/listener.go (hunk 2 above)
Comment (vadmeste) [reply pkg/http/listener.go]: Emm.. Actually ignoreErr() is too generic for me, isRoutineNetErr() is confusing ?

**Comment by nitisht** [comment]
Is this ready for review again @vadmeste

**Review by harshavardhana — CHANGES_REQUESTED** [review]
Looks like this PR has unexpected changes from other commits. @vadmeste

**Comment by harshavardhana** [comment]
Can you rebase this PR @vadmeste ?

**Comment by vadmeste** [comment]
PR updated.

**Review by harshavardhana — APPROVED** [review]

**Comment by harshavardhana** [comment]
@balamurugana can you take a look?

**Review by balamurugana — APPROVED** [review]
LGTM
