### PR TITLE
startup: do not fail for non-EADDRINUSE errors. Fixes #1234

### LINKED ISSUE #1234: Updated minio server fails to start on windows platform (windows 8 and 10)
**## updated minio server fails to start on windows10 and windows8,**
At the same time, older version runs perfectly on both platforms in the same port(http://127.0.0.1:9000)

`G:\minio\source\updated>minio version
Version: 2016-03-11T03:45:50Z
Release-Tag: RELEASE.2016-03-11T03-45-50Z
Commit-ID: b5c77b641de772c6abb223c80fdce2e00bdee7ca`

`G:\minio\source\updated>minio server c:\minioserver
time="2016-03-16T10:40:56+05:30" level=fatal msg="Unable to listen on IP 169.254.77.77, port 9000" error=
"listen tcp4 [169.254.77.77%Local Area Connection* 12]:9000: bind: The requested address is not valid in
its context." probe="{\"cause\":{\"Op\":\"listen\",\"Net\":\"tcp4\",\"Source\":null,\"Addr\":{\"IP\":\"16
9.254.77.77\",\"Port\":9000,\"Zone\":\"Local Area Connection* 12\"},\"Err\":{\"Syscall\":\"bind\",\"Err\"
:10049}},\"trace\":[{\"line\":302,\"file\":\"/home/builder/mygo/src/github.com/minio/minio/server-main.go
\",\"func\":\"main.checkPortAvailability\"}],\"sysinfo\":{\"host.arch\":\"amd64\",\"host.cpus\":\"4\",\"h
ost.lang\":\"go1.6\",\"host.name\":\"Jeyaprabu\",\"host.os\":\"windows\",\"mem.heap.total\":\"1.9MB\",\"m
em.heap.used\":\"963kB\",\"mem.total\":\"2.8MB\",\"mem.used\":\"963kB\"}}"
` 
using address flag doesn't solve the problem

`G:\minio\source\updated>minio --address 192.168.33.44:6000 server c:\minioserver
time="2016-03-16T10:41:40+05:30" level=fatal msg="Unable to listen on IP 169.254.77.77, port 6000" error=
"listen tcp4 [169.254.77.77%Local Area Connection* 12]:6000: bind: The requested address is not valid in
its context." probe="{\"cause\":{\"Op\":\"listen\",\"Net\":\"tcp4\",\"Source\":null,\"Addr\":{\"IP\":\"16
9.254.77.77\",\"Port\":6000,\"Zone\":\"Local Area Connection* 12\"},\"Err\":{\"Syscall\":\"bind\",\"Err\"
:10049}},\"trace\":[{\"line\":302,\"file\":\"/home/builder/mygo/src/github.com/minio/minio/server-main.go
\",\"func\":\"main.checkPortAvailability\"}],\"sysinfo\":{\"host.arch\":\"amd64\",\"host.cpus\":\"4\",\"h
ost.lang\":\"go1.6\",\"host.name\":\"Jeyaprabu\",\"host.os\":\"windows\",\"mem.heap.total\":\"1.9MB\",\"m
em.heap.used\":\"961kB\",\"mem.total\":\"2.8MB\",\"mem.used\":\"961kB\"}}"`

### PR DESCRIPTION
**Pull request by krishnasrinivas**
@harshavardhana not tested on windows yet.

### CODE REVIEW

File: server-main.go [hunk 1]
```diff
@@ -299,7 +300,25 @@ func checkPortAvailability(port int) {
 			tcpAddr := net.TCPAddr{IP: ip, Port: port, Zone: ifc.Name}
 			l, e := net.ListenTCP(network, &tcpAddr)
 			if e != nil {
-				fatalIf(probe.NewError(e), fmt.Sprintf("Unable to listen on IP %s, port %.d", tcpAddr.IP, tcpAddr.Port), nil)
+				// do not fail for non-EADDRINUSE errors
+				// EADDRINUSE is the system call error if another process is
+				// already listening at the specified port
+				neterr, ok := e.(*net.OpError)
+				if !ok {
```
Comment (harshavardhana) [inline server-main.go]: You can move this into a function like os.IsNotExist(), 'isAddrInUse(err)'
