### PR TITLE
fs: Enable returning ETag along with ListObjects()

### LINKED ISSUE #4028: api: AWS JDK objectSummary does not display the key's md5
## Expected Behavior

Return the md5 hash of the file. It works with AWS S3 and s3-compatible solutions.

## Current Behavior

The md5 returned is null

## Steps to Reproduce (for bugs)

Use the AWS JDK to try and view the object summary and extract the MD5
```
  for (S3ObjectSummary objectSummary : objectListing.getObjectSummaries()) {
                    if (process.contains("checkmd5")) {
                        if (objectSummary.getKey().contains(key)) {
                            objectlist = objectSummary.getETag();
                            break;
                        }
                    }
```

## Context

Important for backup and restore applications to verify if the data has changed

## Your Environment

./minio version
Version: 2017-02-16T01:47:30Z
Release-Tag: RELEASE.2017-02-16T01-47-30Z
Commit-ID: 3d98311d9f4ceb78dba996dcdc0751253241e697

### PR DESCRIPTION
**Pull request by harshavardhana**
## Description
This is to comply with S3 behavior, we previously removed
reading `fs.json` for optimization reasons but we have a
reason to believe that providing ETag and using gjson
provides needed benefit of not having to deal with
unmarshalling overhead of golang stdlib.

## Motivation and Context
Fixes #4028

## How Has This Been Tested?
Manually with benchmarks

With ETag
```
minio@minio3:~$ time mc ls -r test/dicom | wc -l 
230000

real    0m26.398s
user    0m15.928s
sys     0m2.196s
```

Without ETag
```
minio@minio3:~$ time mc ls -r test/dicom | wc -l 
230000

real    0m20.672s
user    0m17.100s
sys     0m2.548s
```

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by krishnasrinivas** [comment]
* what is the performance difference between gjson and json.Umnarshal?
* what is the performance difference if the following is replaced:
```
	fsMetaBuf, err := ioutil.ReadAll(rlk.LockedFile)
 +	if err != nil {
 +		// `fs.json` can be empty due to previously failed
 +		// PutObject() transaction, if we arrive at such
 +		// a situation we just ignore and continue.
 +		if errorCause(err) != io.EOF {
 +			return "", toObjectErr(err, bucket, entry)
 +		}
 +	}
 +
 +	fsMetaMap := parseFSMetaMap(fsMetaBuf)
```
by
fsMetaV1.ReadFrom() i.e will the extra work of doing parseFSVersion parseFSFormat parseFSParts parseFSRelease instead of just parseFSParts result in too much of performance hit?

**Comment by harshavardhana** [comment]
> what is the performance difference between gjson and json.Umnarshal?

json.Unmarshal is orders of magnitude slower than gjson and even uses lot of memory per operation,  this was already established when we moved our xl.json reading to gjson, we never did for `fs` because we had `fs.json` optional and it was kind of not necessary. But it is the right time to move as well since we heavily depend on it and it is not optional anymore. 

It is quite simple to see this with simple bench-marking. 

With json.Unmarshal
```
$ cat old.txt 
BenchmarkParseAll10-4      	   50000	     35084 ns/op	    3064 B/op	      68 allocs/op
BenchmarkParseAll100-4     	    5000	    235998 ns/op	   27368 B/op	     440 allocs/op
BenchmarkParseAll1000-4    	    1000	   2377073 ns/op	  227696 B/op	    4050 allocs/op
BenchmarkParseAll5000-4    	     100	  12691447 ns/op	 1130992 B/op	   20058 allocs/op
BenchmarkParseAll10000-4   	      50	  24660559 ns/op	 2434096 B/op	   40062 allocs/op
PASS
ok  	_/tmp/testing	8.428s
```

With gjson
```
$ cat new.txt 
BenchmarkParseAll10-4      	  100000	     14288 ns/op	    8096 B/op	      16 allocs/op
BenchmarkParseAll100-4     	   10000	    114355 ns/op	   65984 B/op	      19 allocs/op
BenchmarkParseAll1000-4    	    2000	   1056521 ns/op	  639936 B/op	      22 allocs/op
BenchmarkParseAll5000-4    	     300	   5869262 ns/op	 3769280 B/op	      29 allocs/op
BenchmarkParseAll10000-4   	     100	  12006275 ns/op	 7717824 B/op	      32 allocs/op
PASS
ok  	_/tmp/testing	8.550s
```

```
benchcmp old.txt new.txt 
benchmark                    old ns/op     new ns/op     delta
BenchmarkParseAll10-4        35084         14288         -59.27%
BenchmarkParseAll100-4       235998        114355        -51.54%
BenchmarkParseAll1000-4      2377073       1056521       -55.55%
BenchmarkParseAll5000-4      12691447      5869262       -53.75%
BenchmarkParseAll10000-4     24660559      12006275      -51.31%

benchmark                    old allocs     new allocs     delta
BenchmarkParseAll10-4        68             16             -76.47%
BenchmarkParseAll100-4       440            19             -95.68%
BenchmarkParseAll1000-4      4050           22             -99.46%
BenchmarkParseAll5000-4      20058          29             -99.86%
BenchmarkParseAll10000-4     40062          32             -99.92%
```

**Comment by harshavardhana** [comment]
Especially when it comes to parsing we don't need to parse the entire struct to get to the final value, so individually for example multipart can just use parseFSParts(). Also we already well understand its behavior due to our extensive usage in `XL` . 

To go back and see what was fixed is this https://github.com/minio/minio/issues/2208

**Comment by harshavardhana** [comment]
More benchmarks with some parallel testing as well. old is `json.Unmarshal` and new is `gjson` 

```
$ benchcmp old.txt new.txt 
benchmark                            old ns/op     new ns/op     delta
BenchmarkParseAllParallel100-4       110276        53857         -51.16%
BenchmarkParseAllParallel500-4       548201        281849        -48.59%
BenchmarkParseAllParallel1000-4      1137198       571913        -49.71%
BenchmarkParseAllParallel5000-4      5839622       2980803       -48.96%
BenchmarkParseAllParallel10000-4     12387503      6301408       -49.13%

benchmark                            old allocs     new allocs     delta
BenchmarkParseAllParallel100-4       440            19             -95.68%
BenchmarkParseAllParallel500-4       2048           21             -98.97%
BenchmarkParseAllParallel1000-4      4050           22             -99.46%
BenchmarkParseAllParallel5000-4      20058          29             -99.86%
BenchmarkParseAllParallel10000-4     40062          32             -99.92%
```

**Comment by harshavardhana** [comment]
For sample benchmarking code is here - https://gist.github.com/harshavardhana/a7c1773c00ab81e66b16403f12f9015b (credits to @hackintoshrao on previous implementation)

File: cmd/fs-v1.go [hunk 1]
```diff
@@ -731,14 +767,33 @@ func (fs fsObjects) ListObjects(bucket, prefix, marker, delimiter string, maxKey
 			objInfo.IsDir = true
 			return
 		}
+
+		objectLock := globalNSMutex.NewNSLock(bucket, entry)
+		objectLock.RLock()
+		var md5Sum string
+		md5Sum, err = fs.getObjectETag(bucket, entry)
```
Comment (krishnasrinivas) [inline cmd/fs-v1.go]: you can do RUnlock() here once.
Or move Lock/Unlock calls inside getObjectETag() function

Comment (harshavardhana) [reply cmd/fs-v1.go]: Doing outside is better.. for understanding.

**Review by krishnasrinivas — APPROVED** [review]
