### PR TITLE
Report correct error when O_DIRECT is not supported

### LINKED ISSUE #9537: Write permission error using docker image
The latest image produces a file permission error if used in a docker-compose file.

## Expected Behavior

Should have write permission to the data directory like the images before.

## Current Behavior

Given this `docker-compose.yaml`:
```yaml
services:
  minio:
    image: minio/minio
    volumes:
      - /tmp/minioData-1:/data1
    ports:
      - 9002:9000
    environment:
      MINIO_ACCESS_KEY: minio
      MINIO_SECRET_KEY: minio123
    command: server /data1
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3
```

produces the following error:

```yaml
 | ERROR Unable to initialize backend: Unable to write to the backend
 |       > Please ensure MinIO binary has write permissions for the backend
 |       HINT:
 |         Use 'sudo chown root /data1 && sudo chmod u+rxw /data1' to provide sufficient permissions.
```

Using
```yaml
    image: minio/minio:RELEASE.2020-05-01T22-19-14Z
```
works fine. The issue was introduced with `RELEASE.2020-05-06T23-23-25Z`.

Is there any update of the configuration required?

### PR DESCRIPTION
**Pull request by harshavardhana**
## Description
Report correct error when O_DIRECT is not supported

## Motivation and Context
fixes #9537

## How to test this PR?
Test as `minio server /dev/shm/test` v/s `minio server /tmp/test`

## Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [x] Fixes a regression perhaps we should report appropriate error
- [ ] Documentation needed
- [ ] Unit tests needed
- [ ] Functional tests needed (If yes, add [mint](https://github.com/minio/mint) PR # here: )

### CODE REVIEW

File: cmd/storage-rest-server.go [hunk 1]
```diff
@@ -738,6 +738,12 @@ func registerStorageRESTHandlers(router *mux.Router, endpointZones EndpointZones
 			}
 			storage, err := newPosix(endpoint.Path)
 			if err != nil {
+				if err == errMinDiskSize {
+					logger.Fatal(config.ErrUnableToWriteInBackend(err).Hint(err.Error()), "Unable to intialize backend")
```
Comment (poornas) [inline cmd/storage-rest-server.go]:
```suggestion
					logger.Fatal(config.ErrUnableToWriteInBackend(err).Hint(err.Error()), "Unable to initialize backend")
```

**Review by poornas — CHANGES_REQUESTED** [review]

**Review by kannappanr — APPROVED** [review]
LGTM

**Comment by minio-trusted** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-xl.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-dist-xl.sh | :heavy_check_mark: |
| mint-gateway-s3.sh | :x: [more...](#efc17ea1-aefa-47e0-ace1-759ef421cafa) |
| mint-gateway-azure.sh | :x: [more...](#76a1996d-1641-4887-bc97-2aa171f50a47) |
| mint-gateway-nas.sh | :x: [more...](#67d6695e-a9bf-4ae4-b51f-b33c30479093) |
<a name="76a1996d-1641-4887-bc97-2aa171f50a47"></a>
### 9545-1a09176/mint-gateway-azure.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-c3.minio.io:31406
ACCESS_KEY:           minioazure
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp b8dfbb79ba4c:/mint/log /tmp/mint-logs'

(1/15) Running aws-sdk-go tests ... done in 8 seconds
(2/15) Running aws-sdk-java tests ... done in 2 seconds
(3/15) Running aws-sdk-php tests ... done in 10 minutes and 51 seconds
(4/15) Running aws-sdk-ruby tests ... FAILED in 4 minutes and 3 seconds
{
  "name": "aws-sdk-ruby",
  "function": "listBuckets",
  "args": {},
  "duration": 242628.65,
  "error": "Net::ReadTimeout",
  "status": "FAIL"
}
(4/15) Running awscli tests ... FAILED in 49 seconds
{
  "name": "awscli",
  "duration": 3649,
  "function": "aws --endpoint-url http://minio-c3.minio.io:31406 s3api copy-object --bucket awscli-mint-test-bucket-23326 --storage-class REDUCED_REDUNDANCY --key datafile-1-kB-copy --copy-source awscli-mint-test-bucket-23326/datafile-1-kB\n",
  "status": "FAIL",
  "error": "An error occurred (NotImplemented) when calling the CopyObject operation: A header you provided implies functionality that is not implemented"
}
(4/15) Running healthcheck tests ... done in 0 seconds
(5/15) Running mc tests ... done in 3 minutes and 2 seconds
(6/15) Running minio-dotnet tests ... done in 3 minutes and 8 seconds
(7/15) Running minio-go tests ... FAILED in 4 minutes and 9 seconds
{}
(7/15) Running minio-java tests ... FAILED in 29 minutes and 20 seconds
{
  "name": "minio-java",
  "function": "enableObjectLegalHold(String bucketName, String objectName, String versionId)",
  "duration": 1720,
  "status": "FAIL",
  "error": "error occurred\nErrorResponse(code = InvalidRequest, message = Bucket is missing ObjectLockConfiguration, bucketName = minio-java-test-30dms1s, objectName = minio-java-test-c1hdqg, resource = /minio-java-test-30dms1s/minio-java-test-c1hdqg, requestId = 160CE050AEC63794, hostId = 570f6dca-dcf0-46bc-8bf3-476a3d57ac55)\nrequest={method=PUT, url=http://minio-c3.minio.io:31406/minio-java-test-30dms1s/minio-java-test-c1hdqg?legal-hold=, headers=Host: minio-c3.minio.io:31406\nAccept-Encoding: identity\nUser-Agent: MinIO (amd64; amd64) minio-java/dev\nContent-MD5: erOisiAmIIzsh/Ze2QqGXw==\nx-amz-content-sha256: 96b73c95a8d33e664ab2170e095025b47ebd55978bb71cebd6a51e394bf96722\nx-amz-date: 20200507T224325Z\nAuthorization: AWS4-HMAC-SHA256 Credential=*REDACTED*/20200507/us-east-1/s3/aws4_request, SignedHeaders=accept-encoding;content-md5;host;x-amz-content-sha256;x-amz-date, Signature=*REDACTED*\n}\nresponse={code=400, headers=Accept-Ranges: bytes\nContent-Length: 382\nContent-Security-Policy: block-all-mixed-content\nContent-Type: application/xml\nServer: MinIO/DEVELOPMENT.GOGET\nVary: Origin\nX-Amz-Request-Id: 160CE050AEC63794\nX-Xss-Protection: 1; mode=block\nDate: Thu, 07 May 2020 22:43:25 GMT\n}\n >>> [io.minio.MinioClient.execute(MinioClient.java:1211), io.minio.MinioClient.execute(MinioClient.java:1236), io.minio.MinioClient.executePut(MinioClient.java:1410), io.minio.MinioClient.executePut(MinioClient.java:1424), io.minio.MinioClient.enableObjectLegalHold(MinioClient.java:3568), FunctionalTest.enableObjectLegalHold_test(FunctionalTest.java:3303), FunctionalTest.runTests(FunctionalTest.java:4079), FunctionalTest.main(FunctionalTest.java:4192)]"
}
(7/15) Running minio-js tests ... FAILED in 8 minutes and 26 seconds
{
  "name": "minio-js",
  "function": "listObjectsV2WithMetadata(bucketName, prefix, recursive, startAfter)",
  "args": "bucketName:minio-js-test-3904cc73-e227-4b41-ba89-d3515e74624a, recursive:true",
  "duration": 213,
  "status": "FAIL",
  "error": "TypeError: Cannot read property '0' of undefined at /mint/run/core/minio-js/node_modules/minio/dist/main/xml-parsers.js:414:42 at Array.forEach (<anonymous>) at parseListObjectsV2WithMetadata (node_modules/minio/dist/main/xml-parsers.js:409:21) at DestroyableTransform._flush (node_modules/minio/dist/main/transformers.js:88:19) at DestroyableTransform.prefinish (node_modules/readable-stream/lib/_stream_transform.js:129:10) at prefinish (node_modules/readable-stream/lib/_stream_writable.js:611:14) at finishMaybe (node_modules/readable-stream/lib/_stream_writable.js:620:5) at endWritable (node_modules/readable-stream/lib/_stream_writable.js:643:3) at DestroyableTransform.Writable.end (node_modules/readable-stream/lib/_stream_writable.js:571:22) at IncomingMessage.onend (_stream_readable.js:673:10) at endReadableNT (_stream_readable.js:1201:12) at processTicksAndRejections (internal/process/task_queues.js:84:21)"
}
(7/15) Running minio-py tests ... done in 12 minutes and 50 seconds
(8/15) Running s3cmd tests ... FAILED in 1 minutes and 34 seconds
{
  "name": "s3cmd",
  "duration": "2955",
  "function": "test_copy_object",
  "status": "FAIL",
  "error": ""
}
(8/15) Running s3select tests ... done in 22 seconds
(9/15) Running security tests ... done in 0 seconds

Executed 9 out of 15 tests successfully.
```
<a name="67d6695e-a9bf-4ae4-b51f-b33c30479093"></a>
### 9545-1a09176/mint-gateway-nas.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-c3.minio.io:31700
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 67b91a2a646b:/mint/log /tmp/mint-logs'

(1/15) Running aws-sdk-go tests ... done in 0 seconds
(2/15) Running aws-sdk-java tests ... done in 2 seconds
(3/15) Running aws-sdk-php tests ... done in 41 seconds
(4/15) Running aws-sdk-ruby tests ... done in 1 seconds
(5/15) Running awscli tests ... done in 2 minutes and 5 seconds
(6/15) Running healthcheck tests ... done in 0 seconds
(7/15) Running mc tests ... done in 39 seconds
(8/15) Running minio-dotnet tests ... done in 30 seconds
(9/15) Running minio-go tests ... FAILED in 36 seconds
{}
(9/15) Running minio-java tests ... FAILED in 28 seconds
{
  "name": "minio-java",
  "function": "enableObjectLegalHold(String bucketName, String objectName, String versionId)",
  "duration": 33,
  "status": "FAIL",
  "error": "error occurred\nErrorResponse(code = InvalidRequest, message = Bucket is missing ObjectLockConfiguration, bucketName = minio-java-test-3cmkv6m, objectName = minio-java-test-1hotb9j, resource = /minio-java-test-3cmkv6m/minio-java-test-1hotb9j, requestId = 160CDD8F9928E6A9, hostId = 0d993935-0bec-4007-a2ab-e5aa69371e87)\nrequest={method=PUT, url=http://minio-c3.minio.io:31700/minio-java-test-3cmkv6m/minio-java-test-1hotb9j?legal-hold=, headers=Host: minio-c3.minio.io:31700\nAccept-Encoding: identity\nUser-Agent: MinIO (amd64; amd64) minio-java/dev\nContent-MD5: erOisiAmIIzsh/Ze2QqGXw==\nx-amz-content-sha256: 96b73c95a8d33e664ab2170e095025b47ebd55978bb71cebd6a51e394bf96722\nx-amz-date: 20200507T215257Z\nAuthorization: AWS4-HMAC-SHA256 Credential=*REDACTED*/20200507/us-east-1/s3/aws4_request, SignedHeaders=accept-encoding;content-md5;host;x-amz-content-sha256;x-amz-date, Signature=*REDACTED*\n}\nresponse={code=400, headers=Accept-Ranges: bytes\nContent-Length: 384\nContent-Security-Policy: block-all-mixed-content\nContent-Type: application/xml\nServer: MinIO/DEVELOPMENT.GOGET\nVary: Origin\nX-Amz-Request-Id: 160CDD8F9928E6A9\nX-Xss-Protection: 1; mode=block\nDate: Thu, 07 May 2020 21:52:57 GMT\n}\n >>> [io.minio.MinioClient.execute(MinioClient.java:1211), io.minio.MinioClient.execute(MinioClient.java:1236), io.minio.MinioClient.executePut(MinioClient.java:1410), io.minio.MinioClient.executePut(MinioClient.java:1424), io.minio.MinioClient.enableObjectLegalHold(MinioClient.java:3568), FunctionalTest.enableObjectLegalHold_test(FunctionalTest.java:3303), FunctionalTest.runTests(FunctionalTest.java:4079), FunctionalTest.main(FunctionalTest.java:4192)]"
}
(9/15) Running minio-js tests ... done in 36 seconds
(10/15) Running minio-py tests ... done in 53 seconds
(11/15) Running s3cmd tests ... done in 14 seconds
(12/15) Running s3select tests ... done in 1 seconds
(13/15) Running security tests ... done in 0 seconds

Executed 13 out of 15 tests successfully.
```
<a name="efc17ea1-aefa-47e0-ace1-759ef421cafa"></a>
### 9545-1a09176/mint-gateway-s3.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-dev7.minio.io:31021
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 6782cb374b64:/mint/log /tmp/mint-logs'

(1/15) Running aws-sdk-go tests ... done in 0 seconds
(2/15) Running aws-sdk-java tests ... done in 2 seconds
(3/15) Running aws-sdk-php tests ... done in 41 seconds
(4/15) Running aws-sdk-ruby tests ... done in 2 seconds
(5/15) Running awscli tests ... FAILED in 20 seconds
{
  "name": "awscli",
  "duration": 4313,
  "function": "aws --endpoint-url http://minio-dev7.minio.io:31021 s3api get-object --bucket awscli-mint-test-bucket-13465 --key awscli-mint-test-bucket-13465-object /tmp/datafile-0-b\n",
  "status": "FAIL",
  "error": "Etag mismatch for multipart 0 byte object"
}
(5/15) Running healthcheck tests ... done in 0 seconds
(6/15) Running mc tests ... done in 11 seconds
(7/15) Running minio-dotnet tests ... done in 28 seconds
(8/15) Running minio-go tests ... FAILED in 14 seconds
{}
(8/15) Running minio-java tests ... FAILED in 28 seconds
{
  "name": "minio-java",
  "function": "enableObjectLegalHold(String bucketName, String objectName, String versionId)",
  "duration": 43,
  "status": "FAIL",
  "error": "error occurred\nErrorResponse(code = InvalidRequest, message = Bucket is missing ObjectLockConfiguration, bucketName = minio-java-test-qscep7, objectName = minio-java-test-3gdd9aq, resource = /minio-java-test-qscep7/minio-java-test-3gdd9aq, requestId = 160CDD6B494B0B64, hostId = 8ee5bc0c-6e55-474f-b9fc-3d805f1aa8a1)\nrequest={method=PUT, url=http://minio-dev7.minio.io:31021/minio-java-test-qscep7/minio-java-test-3gdd9aq?legal-hold=, headers=Host: minio-dev7.minio.io:31021\nAccept-Encoding: identity\nUser-Agent: MinIO (amd64; amd64) minio-java/dev\nContent-MD5: erOisiAmIIzsh/Ze2QqGXw==\nx-amz-content-sha256: 96b73c95a8d33e664ab2170e095025b47ebd55978bb71cebd6a51e394bf96722\nx-amz-date: 20200507T215021Z\nAuthorization: AWS4-HMAC-SHA256 Credential=*REDACTED*/20200507/us-east-1/s3/aws4_request, SignedHeaders=accept-encoding;content-md5;host;x-amz-content-sha256;x-amz-date, Signature=*REDACTED*\n}\nresponse={code=400, headers=Accept-Ranges: bytes\nContent-Length: 382\nContent-Security-Policy: block-all-mixed-content\nContent-Type: application/xml\nServer: MinIO/DEVELOPMENT.GOGET\nVary: Origin\nX-Amz-Request-Id: 160CDD6B494B0B64\nX-Xss-Protection: 1; mode=block\nDate: Thu, 07 May 2020 21:50:21 GMT\n}\n >>> [io.minio.MinioClient.execute(MinioClient.java:1211), io.minio.MinioClient.execute(MinioClient.java:1236), io.minio.MinioClient.executePut(MinioClient.java:1410), io.minio.MinioClient.executePut(MinioClient.java:1424), io.minio.MinioClient.enableObjectLegalHold(MinioClient.java:3568), FunctionalTest.enableObjectLegalHold_test(FunctionalTest.java:3303), FunctionalTest.runTests(FunctionalTest.java:4079), FunctionalTest.main(FunctionalTest.java:4192)]"
}
(8/15) Running minio-js tests ... done in 29 seconds
(9/15) Running minio-py tests ... done in 55 seconds
(10/15) Running s3cmd tests ... done in 59 seconds
(11/15) Running s3select tests ... done in 2 seconds
(12/15) Running security tests ... done in 0 seconds

Executed 12 out of 15 tests successfully.
```
Deleting image on docker hub
Deleting image locally

**Comment by minio-trusted** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-xl.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-dist-xl.sh | :heavy_check_mark: |
| mint-gateway-s3.sh | :x: [more...](#03617c66-12a8-49e4-8df0-1c83c604b521) |
| mint-gateway-azure.sh | :x: [more...](#18a12f5e-b646-4e5b-a67a-2fa424bc480f) |
| mint-gateway-nas.sh | :x: [more...](#c43cd4b9-97e3-48ed-b6e2-6a85098f7fbf) |
<a name="03617c66-12a8-49e4-8df0-1c83c604b521"></a>
### 9545-4ef9634/mint-gateway-s3.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-dev6.minio.io:31537
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 551a2b8c057c:/mint/log /tmp/mint-logs'

(1/15) Running aws-sdk-go tests ... done in 0 seconds
(2/15) Running aws-sdk-java tests ... done in 2 seconds
(3/15) Running aws-sdk-php tests ... done in 41 seconds
(4/15) Running aws-sdk-ruby tests ... done in 1 seconds
(5/15) Running awscli tests ... FAILED in 21 seconds
{
  "name": "awscli",
  "duration": 4548,
  "function": "aws --endpoint-url http://minio-dev6.minio.io:31537 s3api get-object --bucket awscli-mint-test-bucket-7682 --key awscli-mint-test-bucket-7682-object /tmp/datafile-0-b\n",
  "status": "FAIL",
  "error": "Etag mismatch for multipart 0 byte object"
}
(5/15) Running healthcheck tests ... done in 0 seconds
(6/15) Running mc tests ... done in 17 seconds
(7/15) Running minio-dotnet tests ... done in 34 seconds
(8/15) Running minio-go tests ... FAILED in 20 seconds
{}
(8/15) Running minio-java tests ... FAILED in 21 seconds
{
  "name": "minio-java",
  "function": "enableObjectLegalHold(String bucketName, String objectName, String versionId)",
  "duration": 34,
  "status": "FAIL",
  "error": "error occurred\nErrorResponse(code = InvalidRequest, message = Bucket is missing ObjectLockConfiguration, bucketName = minio-java-test-qvlq8h, objectName = minio-java-test-194eht4, resource = /minio-java-test-qvlq8h/minio-java-test-194eht4, requestId = 160CE21592EBF19A, hostId = 29d50d21-9f9e-41d5-9a7e-be01bef561fd)\nrequest={method=PUT, url=http://minio-dev6.minio.io:31537/minio-java-test-qvlq8h/minio-java-test-194eht4?legal-hold=, headers=Host: minio-dev6.minio.io:31537\nAccept-Encoding: identity\nUser-Agent: MinIO (amd64; amd64) minio-java/dev\nContent-MD5: erOisiAmIIzsh/Ze2QqGXw==\nx-amz-content-sha256: 96b73c95a8d33e664ab2170e095025b47ebd55978bb71cebd6a51e394bf96722\nx-amz-date: 20200507T231550Z\nAuthorization: AWS4-HMAC-SHA256 Credential=*REDACTED*/20200507/us-east-1/s3/aws4_request, SignedHeaders=accept-encoding;content-md5;host;x-amz-content-sha256;x-amz-date, Signature=*REDACTED*\n}\nresponse={code=400, headers=Accept-Ranges: bytes\nContent-Length: 382\nContent-Security-Policy: block-all-mixed-content\nContent-Type: application/xml\nServer: MinIO/DEVELOPMENT.GOGET\nVary: Origin\nX-Amz-Request-Id: 160CE21592EBF19A\nX-Xss-Protection: 1; mode=block\nDate: Thu, 07 May 2020 23:15:50 GMT\n}\n >>> [io.minio.MinioClient.execute(MinioClient.java:1211), io.minio.MinioClient.execute(MinioClient.java:1236), io.minio.MinioClient.executePut(MinioClient.java:1410), io.minio.MinioClient.executePut(MinioClient.java:1424), io.minio.MinioClient.enableObjectLegalHold(MinioClient.java:3568), FunctionalTest.enableObjectLegalHold_test(FunctionalTest.java:3303), FunctionalTest.runTests(FunctionalTest.java:4079), FunctionalTest.main(FunctionalTest.java:4192)]"
}
(8/15) Running minio-js tests ... done in 30 seconds
(9/15) Running minio-py tests ... done in 1 minutes and 6 seconds
(10/15) Running s3cmd tests ... done in 1 minutes and 3 seconds
(11/15) Running s3select tests ... done in 1 seconds
(12/15) Running security tests ... done in 0 seconds

Executed 12 out of 15 tests successfully.
```
<a name="c43cd4b9-97e3-48ed-b6e2-6a85098f7fbf"></a>
### 9545-4ef9634/mint-gateway-nas.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-dev7.minio.io:31992
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp ce21472e7186:/mint/log /tmp/mint-logs'

(1/15) Running aws-sdk-go tests ... done in 0 seconds
(2/15) Running aws-sdk-java tests ... done in 1 seconds
(3/15) Running aws-sdk-php tests ... done in 41 seconds
(4/15) Running aws-sdk-ruby tests ... done in 2 seconds
(5/15) Running awscli tests ... done in 2 minutes and 1 seconds
(6/15) Running healthcheck tests ... done in 0 seconds
(7/15) Running mc tests ... done in 23 seconds
(8/15) Running minio-dotnet tests ... done in 30 seconds
(9/15) Running minio-go tests ... FAILED in 33 seconds
{}
(9/15) Running minio-java tests ... FAILED in 22 seconds
{
  "name": "minio-java",
  "function": "enableObjectLegalHold(String bucketName, String objectName, String versionId)",
  "duration": 23,
  "status": "FAIL",
  "error": "error occurred\nErrorResponse(code = InvalidRequest, message = Bucket is missing ObjectLockConfiguration, bucketName = minio-java-test-2oodrb9, objectName = minio-java-test-3r86r5d, resource = /minio-java-test-2oodrb9/minio-java-test-3r86r5d, requestId = 160CE230E96F74DD, hostId = 847ff76e-b837-4f9c-87ad-23fbc530f007)\nrequest={method=PUT, url=http://minio-dev7.minio.io:31992/minio-java-test-2oodrb9/minio-java-test-3r86r5d?legal-hold=, headers=Host: minio-dev7.minio.io:31992\nAccept-Encoding: identity\nUser-Agent: MinIO (amd64; amd64) minio-java/dev\nContent-MD5: erOisiAmIIzsh/Ze2QqGXw==\nx-amz-content-sha256: 96b73c95a8d33e664ab2170e095025b47ebd55978bb71cebd6a51e394bf96722\nx-amz-date: 20200507T231748Z\nAuthorization: AWS4-HMAC-SHA256 Credential=*REDACTED*/20200507/us-east-1/s3/aws4_request, SignedHeaders=accept-encoding;content-md5;host;x-amz-content-sha256;x-amz-date, Signature=*REDACTED*\n}\nresponse={code=400, headers=Accept-Ranges: bytes\nContent-Length: 384\nContent-Security-Policy: block-all-mixed-content\nContent-Type: application/xml\nServer: MinIO/DEVELOPMENT.GOGET\nVary: Origin\nX-Amz-Request-Id: 160CE230E96F74DD\nX-Xss-Protection: 1; mode=block\nDate: Thu, 07 May 2020 23:17:48 GMT\n}\n >>> [io.minio.MinioClient.execute(MinioClient.java:1211), io.minio.MinioClient.execute(MinioClient.java:1236), io.minio.MinioClient.executePut(MinioClient.java:1410), io.minio.MinioClient.executePut(MinioClient.java:1424), io.minio.MinioClient.enableObjectLegalHold(MinioClient.java:3568), FunctionalTest.enableObjectLegalHold_test(FunctionalTest.java:3303), FunctionalTest.runTests(FunctionalTest.java:4079), FunctionalTest.main(FunctionalTest.java:4192)]"
}
(9/15) Running minio-js tests ... done in 32 seconds
(10/15) Running minio-py tests ... done in 53 seconds
(11/15) Running s3cmd tests ... done in 16 seconds
(12/15) Running s3select tests ... done in 0 seconds
(13/15) Running security tests ... done in 0 seconds

Executed 13 out of 15 tests successfully.
```
<a name="18a12f5e-b646-4e5b-a67a-2fa424bc480f"></a>
### 9545-4ef9634/mint-gateway-azure.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-dev6.minio.io:31681
ACCESS_KEY:           minioazure
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp c513851b2eeb:/mint/log /tmp/mint-logs'

(1/15) Running aws-sdk-go tests ... done in 9 seconds
(2/15) Running aws-sdk-java tests ... done in 1 seconds
(3/15) Running aws-sdk-php tests ... done in 11 minutes and 8 seconds
(4/15) Running aws-sdk-ruby tests ... FAILED in 4 minutes and 4 seconds
{
  "name": "aws-sdk-ruby",
  "function": "listBuckets",
  "args": {},
  "duration": 242650.3,
  "error": "Net::ReadTimeout",
  "status": "FAIL"
}
(4/15) Running awscli tests ... FAILED in 50 seconds
{
  "name": "awscli",
  "duration": 3696,
  "function": "aws --endpoint-url http://minio-dev6.minio.io:31681 s3api copy-object --bucket awscli-mint-test-bucket-4329 --storage-class REDUCED_REDUNDANCY --key datafile-1-kB-copy --copy-source awscli-mint-test-bucket-4329/datafile-1-kB\n",
  "status": "FAIL",
  "error": "An error occurred (NotImplemented) when calling the CopyObject operation: A header you provided implies functionality that is not implemented"
}
(4/15) Running healthcheck tests ... done in 0 seconds
(5/15) Running mc tests ... done in 3 minutes and 29 seconds
(6/15) Running minio-dotnet tests ... done in 3 minutes and 15 seconds
(7/15) Running minio-go tests ... FAILED in 4 minutes and 42 seconds
{}
(7/15) Running minio-java tests ... FAILED in 29 minutes and 28 seconds
{
  "name": "minio-java",
  "function": "enableObjectLegalHold(String bucketName, String objectName, String versionId)",
  "duration": 1796,
  "status": "FAIL",
  "error": "error occurred\nErrorResponse(code = InvalidRequest, message = Bucket is missing ObjectLockConfiguration, bucketName = minio-java-test-9p78gu, objectName = minio-java-test-3nkuuqv, resource = /minio-java-test-9p78gu/minio-java-test-3nkuuqv, requestId = 160CE50EAE2A77E1, hostId = 5d5c9a1f-d445-499d-8401-11115f34fa10)\nrequest={method=PUT, url=http://minio-dev6.minio.io:31681/minio-java-test-9p78gu/minio-java-test-3nkuuqv?legal-hold=, headers=Host: minio-dev6.minio.io:31681\nAccept-Encoding: identity\nUser-Agent: MinIO (amd64; amd64) minio-java/dev\nContent-MD5: erOisiAmIIzsh/Ze2QqGXw==\nx-amz-content-sha256: 96b73c95a8d33e664ab2170e095025b47ebd55978bb71cebd6a51e394bf96722\nx-amz-date: 20200508T001019Z\nAuthorization: AWS4-HMAC-SHA256 Credential=*REDACTED*/20200508/us-east-1/s3/aws4_request, SignedHeaders=accept-encoding;content-md5;host;x-amz-content-sha256;x-amz-date, Signature=*REDACTED*\n}\nresponse={code=400, headers=Accept-Ranges: bytes\nContent-Length: 382\nContent-Security-Policy: block-all-mixed-content\nContent-Type: application/xml\nServer: MinIO/DEVELOPMENT.GOGET\nVary: Origin\nX-Amz-Request-Id: 160CE50EAE2A77E1\nX-Xss-Protection: 1; mode=block\nDate: Fri, 08 May 2020 00:10:19 GMT\n}\n >>> [io.minio.MinioClient.execute(MinioClient.java:1211), io.minio.MinioClient.execute(MinioClient.java:1236), io.minio.MinioClient.executePut(MinioClient.java:1410), io.minio.MinioClient.executePut(MinioClient.java:1424), io.minio.MinioClient.enableObjectLegalHold(MinioClient.java:3568), FunctionalTest.enableObjectLegalHold_test(FunctionalTest.java:3303), FunctionalTest.runTests(FunctionalTest.java:4079), FunctionalTest.main(FunctionalTest.java:4192)]"
}
(7/15) Running minio-js tests ... FAILED in 9 minutes and 16 seconds
{
  "name": "minio-js",
  "function": "listObjectsV2WithMetadata(bucketName, prefix, recursive, startAfter)",
  "args": "bucketName:minio-js-test-3a532a3a-5b08-4898-ae79-27a4df1fe263, recursive:true",
  "duration": 168,
  "status": "FAIL",
  "error": "TypeError: Cannot read property '0' of undefined at /mint/run/core/minio-js/node_modules/minio/dist/main/xml-parsers.js:414:42 at Array.forEach (<anonymous>) at parseListObjectsV2WithMetadata (node_modules/minio/dist/main/xml-parsers.js:409:21) at DestroyableTransform._flush (node_modules/minio/dist/main/transformers.js:88:19) at DestroyableTransform.prefinish (node_modules/readable-stream/lib/_stream_transform.js:129:10) at prefinish (node_modules/readable-stream/lib/_stream_writable.js:611:14) at finishMaybe (node_modules/readable-stream/lib/_stream_writable.js:620:5) at endWritable (node_modules/readable-stream/lib/_stream_writable.js:643:3) at DestroyableTransform.Writable.end (node_modules/readable-stream/lib/_stream_writable.js:571:22) at IncomingMessage.onend (_stream_readable.js:673:10) at endReadableNT (_stream_readable.js:1201:12) at processTicksAndRejections (internal/process/task_queues.js:84:21)"
}
(7/15) Running minio-py tests ... done in 13 minutes and 51 seconds
(8/15) Running s3cmd tests ... FAILED in 1 minutes and 0 seconds
{
  "name": "s3cmd",
  "duration": "2270",
  "function": "test_copy_object",
  "status": "FAIL",
  "error": ""
}
(8/15) Running s3select tests ... done in 22 seconds
(9/15) Running security tests ... done in 0 seconds

Executed 9 out of 15 tests successfully.
```
Deleting image on docker hub
Deleting image locally

**Comment by minio-trusted** [comment]
```
Error running mint automation
+ mkdir -p 9545-2815f8a/gopath/src/github.com/minio
+ git -C 9545-2815f8a/gopath/src/github.com/minio clone --quiet https://github.com/minio/minio.git
+ git -C 9545-2815f8a/gopath/src/github.com/minio/minio remote add minio https://github.com/minio/minio.git
+ git -C 9545-2815f8a/gopath/src/github.com/minio/minio fetch --quiet minio pull/9545/head:pr9545
+ git -C 9545-2815f8a/gopath/src/github.com/minio/minio checkout --quiet pr9545
+ GO111MODULE=on
+ GOPATH=/home/mint-auto/mint-auto/9545-2815f8a/gopath
+ make -C 9545-2815f8a/gopath/src/github.com/minio/minio --quiet
go: downloading github.com/Azure/azure-pipeline-go v0.2.1
go: downloading github.com/minio/sha256-simd v0.1.1
go: downloading github.com/minio/hdfs/v3 v3.0.1
go: downloading github.com/minio/minio-go/v6 v6.0.55-0.20200425081427-89eebdef2af0
go: downloading github.com/minio/cli v1.22.0
go: downloading github.com/minio/gokrb5/v7 v7.2.5
go: downloading github.com/shirou/gopsutil v2.20.3-0.20200314133625-53cec6b37e6a+incompatible
go: downloading github.com/gorilla/rpc v1.2.0
go: downloading github.com/cheggaaa/pb v1.0.28
go: downloading google.golang.org/api v0.5.0
go: downloading golang.org/x/crypto v0.0.0-20191117063200-497ca9f6d64f
go: downloading github.com/kurin/blazer v0.5.4-0.20200327014341-8f90a40f8af7
go: downloading github.com/djherbis/atime v1.0.0
go: downloading github.com/dgrijalva/jwt-go v3.2.0+incompatible
go: downloading github.com/klauspost/compress v1.10.3
go: downloading gopkg.in/ini.v1 v1.48.0
go: downloading github.com/klauspost/reedsolomon v1.9.3
go: downloading github.com/hashicorp/vault/api v1.0.4
go: downloading golang.org/x/net v0.0.0-20200324143707-d3edc9973b7e
go: downloading github.com/inconshreveable/go-update v0.0.0-20160112193335-8152e7eb6ccf
go: downloading github.com/hashicorp/hcl v1.0.0
go: downloading github.com/klauspost/cpuid v1.2.2
go: downloading github.com/coreos/etcd v3.3.12+incompatible
go: downloading github.com/gorilla/handlers v1.4.0
go: downloading github.com/rs/cors v1.6.0
go: downloading github.com/miekg/dns v1.1.8
go: downloading github.com/hashicorp/vault/sdk v0.1.13
go: downloading github.com/gorilla/mux v1.7.0
go: downloading github.com/cespare/xxhash/v2 v2.1.1
go: downloading github.com/minio/sio v0.2.0
go: downloading github.com/google/uuid v1.1.1
go: downloading github.com/prometheus/client_golang v0.9.3-0.20190127221311-3c4408c8b829
go: downloading github.com/Azure/azure-storage-blob-go v0.8.0
go: downloading github.com/fatih/color v1.7.0
go: downloading golang.org/x/sys v0.0.0-20200323222414-85ca7c5b95cd
go: downloading gopkg.in/ldap.v3 v3.0.3
go: downloading github.com/hashicorp/go-sockaddr v1.0.2
go: downloading github.com/json-iterator/go v1.1.9
go: downloading gopkg.in/asn1-ber.v1 v1.0.0-20181015200546-f715ec2f112d
go: downloading google.golang.org/grpc v1.22.0
go: downloading github.com/mattn/go-ieproxy v0.0.0-20190805055040-f9202b1cfdeb
go: downloading github.com/elazarl/go-bindata-assetfs v1.0.0
go: downloading golang.org/x/time v0.0.0-20190308202827-9d24e82272b4
go: downloading github.com/golang/protobuf v1.3.2
go: downloading github.com/fatih/structs v1.1.0
go: downloading github.com/dustin/go-humanize v1.0.0
go: downloading github.com/hashicorp/go-multierror v1.0.0
go: downloading github.com/gogo/protobuf v1.2.1
go: downloading github.com/pkg/errors v0.8.1
go: downloading github.com/prometheus/common v0.2.0
go: downloading github.com/hashicorp/go-cleanhttp v0.5.1
go: downloading github.com/modern-go/concurrent v0.0.0-20180306012644-bacd9c7ef1dd
go: downloading github.com/minio/lsync v1.0.1
go: downloading golang.org/x/text v0.3.2
go: downloading github.com/Shopify/sarama v1.24.1
go: downloading github.com/nats-io/nats.go v1.9.1
go: downloading github.com/ncw/directio v1.0.5
go: downloading github.com/valyala/tcplisten v0.0.0-20161114210144-ceec8f93295a
go: downloading github.com/beorn7/perks v0.0.0-20180321164747-3a771d992973
go: downloading github.com/eapache/go-resiliency v1.2.0
go: downloading github.com/rjeczalik/notify v0.9.2
go: downloading gopkg.in/olivere/elastic.v5 v5.0.80
go: downloading github.com/beevik/ntp v0.2.0
go: downloading github.com/nats-io/stan.go v0.4.5
go: downloading gopkg.in/jcmturner/gokrb5.v7 v7.2.3
go: downloading github.com/willf/bloom v2.0.3+incompatible
go: downloading github.com/nsqio/go-nsq v1.0.7
go: downloading github.com/rcrowley/go-metrics v0.0.0-20190704165056-9c2d0518ed81
go: downloading github.com/pierrec/lz4 v2.4.0+incompatible
go: downloading cloud.google.com/go v0.39.0
go: downloading github.com/hashicorp/errwrap v1.0.0
go: downloading github.com/eapache/go-xerial-snappy v0.0.0-20180814174437-776d5712da21
go: downloading github.com/streadway/amqp v0.0.0-20190404075320-75d898a42a94
go: downloading github.com/matttproud/golang_protobuf_extensions v1.0.1
go: downloading github.com/modern-go/reflect2 v1.0.1
go: downloading github.com/mitchellh/go-homedir v1.1.0
go: downloading github.com/coredns/coredns v1.4.0
go: downloading golang.org/x/oauth2 v0.0.0-20190402181905-9f3314589c9a
go: downloading github.com/mailru/easyjson v0.0.0-20180730094502-03f2033d19d5
go: downloading github.com/prometheus/client_model v0.0.0-20190129233127-fd36f4220a90
go: downloading github.com/spaolacci/murmur3 v1.1.0
go: downloading github.com/hashicorp/go-rootcerts v1.0.1
go: downloading github.com/mitchellh/mapstructure v1.1.2
go: downloading github.com/mattn/go-runewidth v0.0.4
go: downloading github.com/minio/highwayhash v1.0.0
go: downloading github.com/eapache/queue v1.1.0
go: downloading github.com/minio/simdjson-go v0.1.5-0.20200303142138-b17fe061ea37
go: downloading github.com/lib/pq v1.1.1
go: downloading github.com/secure-io/sio-go v0.3.0
go: downloading go.opencensus.io v0.21.0
go: downloading github.com/davecgh/go-spew v1.1.1
go: downloading github.com/tinylib/msgp v1.1.1
go: downloading google.golang.org/genproto v0.0.0-20190513181449-d00d292a067c
go: downloading github.com/hashicorp/golang-lru v0.5.1
go: downloading gopkg.in/yaml.v2 v2.2.4
go: downloading github.com/minio/parquet-go v0.0.0-20200414234858-838cfa8aae61
go: downloading github.com/ryanuber/go-glob v1.0.0
go: downloading github.com/googleapis/gax-go/v2 v2.0.4
go: downloading github.com/alecthomas/participle v0.2.1
go: downloading github.com/go-sql-driver/mysql v1.4.1
go: downloading github.com/bcicen/jstream v0.0.0-20190220045926-16c1f8af81c2
go: downloading github.com/xdg/scram v0.0.0-20180814205039-7eeb5667e42c
go: downloading github.com/gomodule/redigo v2.0.0+incompatible
go: downloading github.com/nats-io/nuid v1.0.1
go: downloading github.com/mattn/go-colorable v0.1.1
go: downloading github.com/nats-io/jwt v0.3.2
go: downloading gopkg.in/square/go-jose.v2 v2.3.1
go: downloading github.com/philhofer/fwd v1.0.0
go: downloading github.com/klauspost/readahead v1.3.1
go: downloading github.com/hashicorp/go-retryablehttp v0.5.4
go: downloading github.com/montanaflynn/stats v0.5.0
go: downloading github.com/mattn/go-isatty v0.0.7
go: downloading gopkg.in/jcmturner/dnsutils.v1 v1.0.1
go: downloading github.com/nats-io/nkeys v0.1.3
go: downloading github.com/eclipse/paho.mqtt.golang v1.2.0
go: downloading github.com/jcmturner/gofork v0.0.0-20190328161633-dc7c13fece03
go: downloading github.com/prometheus/procfs v0.0.0-20190117184657-bf6a532e95b1
go: downloading github.com/klauspost/pgzip v1.2.1
go: downloading git.apache.org/thrift.git v0.13.0
go: downloading github.com/hashicorp/go-uuid v1.0.1
go: downloading github.com/tidwall/gjson v1.3.5
go: downloading github.com/willf/bitset v1.1.10
go: downloading gopkg.in/jcmturner/rpc.v1 v1.1.0
go: downloading gopkg.in/jcmturner/aescts.v1 v1.0.1
go: downloading github.com/tidwall/sjson v1.0.4
go: downloading github.com/golang/snappy v0.0.1
go: downloading github.com/xdg/stringprep v1.0.0
go: downloading github.com/tidwall/match v1.0.1
go: downloading github.com/tidwall/pretty v1.0.0
go: downloading gopkg.in/jcmturner/goidentity.v3 v3.0.0
+ docker build --quiet --tag minio/minio:9545-2815f8a --file 9545-2815f8a/gopath/src/github.com/minio/minio/Dockerfile.dev 9545-2815f8a/gopath/src/github.com/minio/minio
+ docker push minio/minio:9545-2815f8a
+ docker build --quiet --tag minio/mint:edge --file 9545-2815f8a/gopath/src/github.com/minio/minio/Dockerfile.mint 9545-2815f8a/gopath/src/github.com/minio/minio
+ declare -A mint_jobs
+ for job in mint-*.sh
+ mint_jobs["$job"]=73307
+ for job in mint-*.sh
+ bash mint-dist-xl.sh
+ mint_jobs["$job"]=73308
+ for job in mint-*.sh
+ mint_jobs["$job"]=73309
+ for job in mint-*.sh
+ bash mint-fs.sh
+ mint_jobs["$job"]=73310
+ for job in mint-*.sh
+ bash mint-gateway-azure.sh
+ bash mint-gateway-nas.sh
+ mint_jobs["$job"]=73311
+ for job in mint-*.sh
+ bash mint-gateway-s3.sh
+ mint_jobs["$job"]=73312
+ for job in mint-*.sh
+ bash mint-large-bucket.sh
+ mint_jobs["$job"]=73313
+ wait 73313 73312 73308 73307 73311 73309 73310
+ bash mint-xl.sh
+ true
+ declare -a success_jobs
+ declare -a failed_jobs
+ for job in "${!mint_jobs[@]}"
+ wait 73313
+ success_jobs+=("$job")
+ for job in "${!mint_jobs[@]}"
+ wait 73312
+ success_jobs+=("$job")
+ for job in "${!mint_jobs[@]}"
+ wait 73308
+ success_jobs+=("$job")
+ for job in "${!mint_jobs[@]}"
+ wait 73307
+ success_jobs+=("$job")
+ for job in "${!mint_jobs[@]}"
+ wait 73311
+ failed_jobs+=("$job")
+ for job in "${!mint_jobs[@]}"
+ wait 73309
+ failed_jobs+=("$job")
+ for job in "${!mint_jobs[@]}"
+ wait 73310
+ failed_jobs+=("$job")
+ echo '## Mint Automation'
+ echo '| Test | Result |'
+ echo '|:--- |:--- |'
+ for job in "${success_jobs[@]}"
+ echo '| mint-xl.sh | :heavy_check_mark: |'
+ for job in "${success_jobs[@]}"
+ echo '| mint-large-bucket.sh | :heavy_check_mark: |'
+ for job in "${success_jobs[@]}"
+ echo '| mint-fs.sh | :heavy_check_mark: |'
+ for job in "${success_jobs[@]}"
+ echo '| mint-dist-xl.sh | :heavy_check_mark: |'
+ declare -A uuid_log_file_map
+ declare -A uuid_xtrace_map
+ for job in "${failed_jobs[@]}"
++ uuidgen
+ uuid=19e1b097-1d1d-455d-961d-e68087ffb3fe
+ '[' -s 9545-2815f8a/mint-gateway-s3.sh.log ']'
+ echo '| mint-gateway-s3.sh | :x: [more...](#19e1b097-1d1d-455d-961d-e68087ffb3fe) |'
+ uuid_log_file_map["$uuid"]=9545-2815f8a/mint-gateway-s3.sh.log
+ for job in "${failed_jobs[@]}"
++ uuidgen
+ uuid=1439deac-c2dd-42fb-9621-d56d094d0258
+ '[' -s 9545-2815f8a/mint-gateway-azure.sh.log ']'
+ echo '| mint-gateway-azure.sh | :x: [more...](#1439deac-c2dd-42fb-9621-d56d094d0258) |'
+ uuid_log_file_map["$uuid"]=9545-2815f8a/mint-gateway-azure.sh.log
+ for job in "${failed_jobs[@]}"
++ uuidgen
+ uuid=0b7eaa17-ef8c-4818-8326-4f390c6b33f6
+ '[' -s 9545-2815f8a/mint-gateway-nas.sh.log ']'
+ echo '| mint-gateway-nas.sh | :x: [more...](#0b7eaa17-ef8c-4818-8326-4f390c6b33f6) |'
+ uuid_log_file_map["$uuid"]=9545-2815f8a/mint-gateway-nas.sh.log
./auto.sh: line 64: syntax error near unexpected token `fi'

```
