### PR TITLE
gcs: Better parsing of address flag

### LINKED ISSUE #4706: [gcs] gcs startup message contains wrong port, different to the one specified with --address flag
## Expected Behavior
```
18:59 $ MINIO_ACCESS_KEY="minio" MINIO_SECRET_KEY="minio123" minio gateway --address ":9003" gcs  projectgcstest1

               *** Warning: Not Ready for Production ***

Endpoint:  http://192.168.1.2:9000  http://172.17.0.1:9000  http://172.18.0.1:9000  http://127.0.0.1:9000
AccessKey: minio 
SecretKey: minio123 

Browser Access:
   http://192.168.1.2:9000  http://172.17.0.1:9000  http://172.18.0.1:9000  http://127.0.0.1:9000

Command-line Access: https://docs.minio.io/docs/minio-client-quickstart-guide
   $ mc config host add mygcs http://192.168.1.2:9000 minio minio123

Object API (Amazon S3 compatible):
   Go:         https://docs.minio.io/docs/golang-client-quickstart-guide
   Java:       https://docs.minio.io/docs/java-client-quickstart-guide
   Python:     https://docs.minio.io/docs/python-client-quickstart-guide
   JavaScript: https://docs.minio.io/docs/javascript-client-quickstart-guide
   .NET:       https://docs.minio.io/docs/dotnet-client-quickstart-guide
```

Notice 9000 port in startup message though 9003 is specified

## Current Behavior
```
18:59 $ MINIO_ACCESS_KEY="minio" MINIO_SECRET_KEY="minio123" minio gateway --address ":9003" gcs  projectgcstest1

               *** Warning: Not Ready for Production ***

Endpoint:  http://192.168.1.2:9003  http://172.17.0.1:9003  http://172.18.0.1:9003  http://127.0.0.1:9003
AccessKey: minio 
SecretKey: minio123 

Browser Access:
   http://192.168.1.2:9003  http://172.17.0.1:9003  http://172.18.0.1:9003  http://127.0.0.1:9003

Command-line Access: https://docs.minio.io/docs/minio-client-quickstart-guide
   $ mc config host add mygcs http://192.168.1.2:9000 minio minio123

Object API (Amazon S3 compatible):
   Go:         https://docs.minio.io/docs/golang-client-quickstart-guide
   Java:       https://docs.minio.io/docs/java-client-quickstart-guide
   Python:     https://docs.minio.io/docs/python-client-quickstart-guide
   JavaScript: https://docs.minio.io/docs/javascript-client-quickstart-guide
   .NET:       https://docs.minio.io/docs/dotnet-client-quickstart-guide
```

## Possible Solution
Do not know

## Steps to Reproduce (for bugs)
See above

## Context
Testing

## Your Environment
All

### PR DESCRIPTION
**Pull request by vadmeste**
## Motivation and Context
Fixes #4706 

## How Has This Been Tested?
manually

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Review by poornas — APPROVED** [review]
Tested locally. LGTM

**Review by krishnasrinivas — APPROVED** [review]

File: cmd/gateway-main.go [hunk 1]
```diff
@@ -293,6 +293,12 @@ func gatewayMain(ctx *cli.Context, backendType gatewayBackend) {
 		log.EnableQuiet()
 	}
 
+	// Fetch address option
+	gatewayAddr := ctx.GlobalString("address")
+	if gatewayAddr == ":"+globalMinioPort {
```
Comment (harshavardhana) [inline cmd/gateway-main.go:298]: This fix can be made better.. @vadmeste we need to use just like `mc`

```
        Before: setGlobalsFromContext,
```

This would set the value properly and then use globalMinioAddr instead..  this style is little fishy and its also code without comment on the purpose of handling code for Global and Local flag in this manner.
