### PR TITLE
fix: re-use connections in webhook/elasticsearch

### LINKED ISSUE #9460: keep-alive does not reuse already established connections to webhook
Setuped a webhook to get notification for every PUT event, but keep-alived connections aren't re-used between minio and webhook, thousand of connections remain established and unused

## Expected Behavior
minio should re-use the TCP connection between webhook and minioserver when using isActive()
already discussed [here](https://github.com/adnanh/webhook/issues/414#issuecomment-619471421)

## Current Behavior
Minio [isActive()](https://github.com/minio/minio/blob/4843affd0eab28e14e89de3f4c9a040d3b2659ca/pkg/event/target/webhook.go#L164) opening a new connection before every new notification, without re-using the already keep-alived connections. After a few hours minio runs out from available net sockets:
```
Apr 24 12:03:09 minio minio[85021]: Time: 12:03:09 CEST 04/24/2020
Apr 24 12:03:09 minio minio[85021]: DeploymentID: 1ac20d02-a235-46ae-a796-f9fba18885ba
Apr 24 12:03:09 minio minio[85021]: Error: not connected to target server/service
Apr 24 12:03:09 minio minio[85021]:        targetID=webhook, EventName=s3:ObjectCreated:Put
Apr 24 12:03:09 minio minio[85021]:        3: github.com/minio/minio@/cmd/logger/logonce.go:52:logger.(*logOnceType).logOnceIf()
Apr 24 12:03:09 minio minio[85021]:        2: github.com/minio/minio@/cmd/logger/logonce.go:80:logger.LogOnceIf()
Apr 24 12:03:09 minio minio[85021]:        1: github.com/minio/minio@/cmd/notification.go:1291:cmd.sendEvent.func1()
```

## Steps to Reproduce (for bugs)

1. ./minioclient admin config set myminio notify_webhook:1 queue_limit="0" endpoint="http://localhost:999/hooks/minio-webhook" queue_dir=""
2. ./minioclient event add myminio/bigbucket arn:minio:sqs::1:webhook --event put
3. upload something

## Your Environment

* Version used (`minio version`):  minio version RELEASE.2020-04-23T00-58-49Z
* Environment name and version (e.g. nginx 1.9.1):
* Server type and version:
* Operating System and version (`uname -a`): Linux minio 4.19.0-8-amd64 #1 SMP Debian 4.19.98-1 (2020-01-26) x86_64 GNU/Linux
* Link to your project:

### PR DESCRIPTION
**Pull request by harshavardhana**
## Description
fix: re-use connections in webhook/elasticsearch

## Motivation and Context
- elasticsearch client should rely on the SDK helpers
  instead of pure HTTP calls.
- webhook shouldn't need to check for IsActive() for
  all notifications, failure should be delayed.
- Use DialHTTP with re-usable transport

Fixes #9460

## How to test this PR?
as mentioned in the #9460 issue

## Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [ ] Fixes a regression (If yes, please add `commit-id` or `PR #` here)
- [ ] Documentation needed
- [ ] Unit tests needed
- [ ] Functional tests needed (If yes, add [mint](https://github.com/minio/mint) PR # here: )

### CODE REVIEW

File: pkg/event/target/webhook.go [hunk 1]
```diff
@@ -94,29 +94,21 @@ func (target *WebhookTarget) HasQueueStore() bool {
...
-		return false, pErr
-	}
-	if dErr := u.DialHTTP(nil); dErr != nil {
-		if xnet.IsNetworkOrHostDown(dErr) {
-			return false, errNotConnected
-		}
-		return false, dErr
-	}
-	return true, nil
+	return target.httpClient != nil, nil
```
Comment (Praveenrajmani) [inline pkg/event/target/webhook.go]: the same here

File: pkg/event/target/elasticsearch.go [hunk 2]
```diff
@@ -98,25 +98,19 @@ func (target *ElasticsearchTarget) HasQueueStore() bool {
...
 // IsActive - Return true if target is up and active
 func (target *ElasticsearchTarget) IsActive() (bool, error) {
-	if dErr := target.args.URL.DialHTTP(nil); dErr != nil {
-		if xnet.IsNetworkOrHostDown(dErr) {
-			return false, errNotConnected
-		}
-		return false, dErr
-	}
-	return true, nil
+	return target.client != nil, nil
```
Comment (Praveenrajmani) [inline pkg/event/target/elasticsearch.go]: We need the connection information for functions like `getARNList` and `fetchLambdaInfo` etc. I think this will return `true, nil` in all the cases. 

IMO, We need dials/pings to provide instant info on target's connections

Comment (harshavardhana) [reply pkg/event/target/elasticsearch.go]: Hmm we can preserve them, but we should never use them internally. Because making such as hoc calls for each event is expensive operation.

Comment (Praveenrajmani) [reply pkg/event/target/elasticsearch.go]: Yeah, We can have the ping in IsActive() function and lets not use it in internal functions like Save(),Send() as this PR suggests

**Comment by minio-trusted** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-xl.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-dist-xl.sh | :heavy_check_mark: |
| mint-gateway-azure.sh | :x: [more...](#79dcb904-20a3-4718-a552-47ae2cc629a9) |
| mint-gateway-nas.sh | :x: [more...](#ef269005-b701-4604-98a6-69ff92a653e3) |
<a name="ef269005-b701-4604-98a6-69ff92a653e3"></a>
### 9461-d8f70d4/mint-gateway-nas.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-dev4.minio.io:32578
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 64e1a4ea2123:/mint/log /tmp/mint-logs'

(1/15) Running aws-sdk-go tests ... done in 0 seconds
(2/15) Running aws-sdk-java tests ... done in 1 seconds
(3/15) Running aws-sdk-php tests ... done in 43 seconds
(4/15) Running aws-sdk-ruby tests ... done in 2 seconds
(5/15) Running awscli tests ... done in 2 minutes and 5 seconds
(6/15) Running healthcheck tests ... done in 0 seconds
(7/15) Running mc tests ... done in 1 minutes and 8 seconds
(8/15) Running minio-dotnet tests ... done in 36 seconds
(9/15) Running minio-go tests ... FAILED in 1 minutes and 30 seconds
{}
(9/15) Running minio-java tests ... FAILED in 48 seconds
{
  "name": "minio-java",
  "function": "enableObjectLegalHold(String bucketName, String objectName, String versionId)",
  "duration": 52,
  "status": "FAIL",
  "error": "error occurred\nErrorResponse(code = InvalidRequest, message = Bucket is missing ObjectLockConfiguration, bucketName = minio-java-test-2ocego9, objectName = minio-java-test-5idd3s, resource = /minio-java-test-2ocego9/minio-java-test-5idd3s, requestId = 16099B2678D1CBC6, hostId = af0c1a48-0428-4bab-b344-98d72e5dd477)\nrequest={method=PUT, url=http://minio-dev4.minio.io:32578/minio-java-test-2ocego9/minio-java-test-5idd3s?legal-hold=, headers=Host: minio-dev4.minio.io:32578\nAccept-Encoding: identity\nUser-Agent: MinIO (amd64; amd64) minio-java/dev\nContent-MD5: erOisiAmIIzsh/Ze2QqGXw==\nx-amz-content-sha256: 96b73c95a8d33e664ab2170e095025b47ebd55978bb71cebd6a51e394bf96722\nx-amz-date: 20200427T070213Z\nAuthorization: AWS4-HMAC-SHA256 Credential=*REDACTED*/20200427/us-east-1/s3/aws4_request, SignedHeaders=accept-encoding;content-md5;host;x-amz-content-sha256;x-amz-date, Signature=*REDACTED*\n}\nresponse={code=400, headers=Accept-Ranges: bytes\nContent-Length: 382\nContent-Security-Policy: block-all-mixed-content\nContent-Type: application/xml\nServer: MinIO/DEVELOPMENT.GOGET\nVary: Origin\nX-Amz-Request-Id: 16099B2678D1CBC6\nX-Xss-Protection: 1; mode=block\nDate: Mon, 27 Apr 2020 07:02:13 GMT\n}\n >>> [io.minio.MinioClient.execute(MinioClient.java:1211), io.minio.MinioClient.execute(MinioClient.java:1236), io.minio.MinioClient.executePut(MinioClient.java:1410), io.minio.MinioClient.executePut(MinioClient.java:1424), io.minio.MinioClient.enableObjectLegalHold(MinioClient.java:3568), FunctionalTest.enableObjectLegalHold_test(FunctionalTest.java:3303), FunctionalTest.runTests(FunctionalTest.java:4079), FunctionalTest.main(FunctionalTest.java:4192)]"
}
(9/15) Running minio-js tests ... done in 41 seconds
(10/15) Running minio-py tests ... done in 1 minutes and 32 seconds
(11/15) Running s3cmd tests ... done in 21 seconds
(12/15) Running s3select tests ... done in 1 seconds
(13/15) Running security tests ... done in 0 seconds

Executed 13 out of 15 tests successfully.
```
<a name="79dcb904-20a3-4718-a552-47ae2cc629a9"></a>
### 9461-d8f70d4/mint-gateway-azure.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-dev7.minio.io:30212
ACCESS_KEY:           minioazure
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 104dad5417b0:/mint/log /tmp/mint-logs'

(1/15) Running aws-sdk-go tests ... done in 7 seconds
(2/15) Running aws-sdk-java tests ... done in 2 seconds
(3/15) Running aws-sdk-php tests ... done in 1 minutes and 49 seconds
(4/15) Running aws-sdk-ruby tests ... done in 14 seconds
(5/15) Running awscli tests ... FAILED in 47 seconds
{
  "name": "awscli",
  "duration": 3628,
  "function": "aws --endpoint-url http://minio-dev7.minio.io:30212 s3api copy-object --bucket awscli-mint-test-bucket-1390 --storage-class REDUCED_REDUNDANCY --key datafile-1-kB-copy --copy-source awscli-mint-test-bucket-1390/datafile-1-kB\n",
  "status": "FAIL",
  "error": "An error occurred (NotImplemented) when calling the CopyObject operation: A header you provided implies functionality that is not implemented"
}
(5/15) Running healthcheck tests ... done in 1 seconds
(6/15) Running mc tests ... done in 3 minutes and 7 seconds
(7/15) Running minio-dotnet tests ... done in 1 minutes and 25 seconds
(8/15) Running minio-go tests ... FAILED in 4 minutes and 46 seconds
{}
(8/15) Running minio-java tests ... FAILED in 26 minutes and 12 seconds
{
  "name": "minio-java",
  "function": "enableObjectLegalHold(String bucketName, String objectName, String versionId)",
  "duration": 1699,
  "status": "FAIL",
  "error": "error occurred\nErrorResponse(code = InvalidRequest, message = Bucket is missing ObjectLockConfiguration, bucketName = minio-java-test-2mipero, objectName = minio-java-test-13bqh28, resource = /minio-java-test-2mipero/minio-java-test-13bqh28, requestId = 16099CE0430C9160, hostId = fc036b86-3214-40cb-aa19-50b3323c31d3)\nrequest={method=PUT, url=http://minio-dev7.minio.io:30212/minio-java-test-2mipero/minio-java-test-13bqh28?legal-hold=, headers=Host: minio-dev7.minio.io:30212\nAccept-Encoding: identity\nUser-Agent: MinIO (amd64; amd64) minio-java/dev\nContent-MD5: erOisiAmIIzsh/Ze2QqGXw==\nx-amz-content-sha256: 96b73c95a8d33e664ab2170e095025b47ebd55978bb71cebd6a51e394bf96722\nx-amz-date: 20200427T073350Z\nAuthorization: AWS4-HMAC-SHA256 Credential=*REDACTED*/20200427/us-east-1/s3/aws4_request, SignedHeaders=accept-encoding;content-md5;host;x-amz-content-sha256;x-amz-date, Signature=*REDACTED*\n}\nresponse={code=400, headers=Accept-Ranges: bytes\nContent-Length: 384\nContent-Security-Policy: block-all-mixed-content\nContent-Type: application/xml\nServer: MinIO/DEVELOPMENT.GOGET\nVary: Origin\nX-Amz-Request-Id: 16099CE0430C9160\nX-Xss-Protection: 1; mode=block\nDate: Mon, 27 Apr 2020 07:33:50 GMT\n}\n >>> [io.minio.MinioClient.execute(MinioClient.java:1211), io.minio.MinioClient.execute(MinioClient.java:1236), io.minio.MinioClient.executePut(MinioClient.java:1410), io.minio.MinioClient.executePut(MinioClient.java:1424), io.minio.MinioClient.enableObjectLegalHold(MinioClient.java:3568), FunctionalTest.enableObjectLegalHold_test(FunctionalTest.java:3303), FunctionalTest.runTests(FunctionalTest.java:4079), FunctionalTest.main(FunctionalTest.java:4192)]"
}
(8/15) Running minio-js tests ... FAILED in 2 minutes and 11 seconds
{
  "name": "minio-js",
  "function": "listObjectsV2WithMetadata(bucketName, prefix, recursive, startAfter)",
  "args": "bucketName:minio-js-test-38e4fe8b-4569-400a-8520-5adf4453581a, recursive:true",
  "duration": 214,
  "status": "FAIL",
  "error": "TypeError: Cannot read property '0' of undefined at /mint/run/core/minio-js/node_modules/minio/dist/main/xml-parsers.js:414:42 at Array.forEach (<anonymous>) at parseListObjectsV2WithMetadata (node_modules/minio/dist/main/xml-parsers.js:409:21) at DestroyableTransform._flush (node_modules/minio/dist/main/transformers.js:88:19) at DestroyableTransform.prefinish (node_modules/readable-stream/lib/_stream_transform.js:129:10) at prefinish (node_modules/readable-stream/lib/_stream_writable.js:611:14) at finishMaybe (node_modules/readable-stream/lib/_stream_writable.js:620:5) at endWritable (node_modules/readable-stream/lib/_stream_writable.js:643:3) at DestroyableTransform.Writable.end (node_modules/readable-stream/lib/_stream_writable.js:571:22) at IncomingMessage.onend (_stream_readable.js:673:10) at endReadableNT (_stream_readable.js:1201:12) at processTicksAndRejections (internal/process/task_queues.js:84:21)"
}
(8/15) Running minio-py tests ... done in 9 minutes and 46 seconds
(9/15) Running s3cmd tests ... FAILED in 44 seconds
{
  "name": "s3cmd",
  "duration": "1735",
  "function": "test_copy_object",
  "status": "FAIL",
  "error": ""
}
(9/15) Running s3select tests ... done in 22 seconds
(10/15) Running security tests ... done in 0 seconds

Executed 10 out of 15 tests successfully.
```
Deleting image on docker hub
Deleting image locally

**Comment by harshavardhana** [comment]
PR updated @Praveenrajmani @vadmeste

File: pkg/event/target/elasticsearch.go [hunk 3]
```diff
@@ -235,26 +235,22 @@ func createIndex(client *elastic.Client, args ElasticsearchArgs) error {
...
 func newClient(args ElasticsearchArgs) (*elastic.Client, error) {
-	client, clientErr := elastic.NewClient(elastic.SetURL(args.URL.String()), elastic.SetSniff(false), elastic.SetMaxRetries(10))
-	if clientErr != nil {
-		if !(errors.Cause(clientErr) == elastic.ErrNoClient) {
-			return nil, clientErr
-		}
-	} else {
-		if err := createIndex(client, args); err != nil {
-			return nil, err
+	client, err := elastic.NewClient(elastic.SetURL(args.URL.String()), elastic.SetMaxRetries(10))
```
Comment (Praveenrajmani) [inline pkg/event/target/elasticsearch.go:238]: sniffer is set to True by default. There will be some sniffing happening in the background to discover nodes automatically in a running Elasticsearch instance. 

Do you think we need this?

Comment (harshavardhana) [reply pkg/event/target/elasticsearch.go:238]: Yes it is recommended setting for clients @Praveenrajmani we shouldn't turn it off.

**Comment by minio-trusted** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-xl.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-dist-xl.sh | :heavy_check_mark: |
| mint-gateway-azure.sh | :x: [more...](#0c6bb965-3522-446f-95fa-1b220229fe09) |
| mint-gateway-nas.sh | :x: [more...](#06df298d-5916-4fc7-bab8-4fd5636836e4) |
<a name="0c6bb965-3522-446f-95fa-1b220229fe09"></a>
### 9461-47a93a2/mint-gateway-azure.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-c4.minio.io:32097
ACCESS_KEY:           minioazure
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 5b1eb371dd98:/mint/log /tmp/mint-logs'

(1/15) Running aws-sdk-go tests ... done in 9 seconds
(2/15) Running aws-sdk-java tests ... done in 1 seconds
(3/15) Running aws-sdk-php tests ... done in 2 minutes and 0 seconds
(4/15) Running aws-sdk-ruby tests ... done in 14 seconds
(5/15) Running awscli tests ... FAILED in 47 seconds
{
  "name": "awscli",
  "duration": 3688,
  "function": "aws --endpoint-url http://minio-c4.minio.io:32097 s3api copy-object --bucket awscli-mint-test-bucket-3106 --storage-class REDUCED_REDUNDANCY --key datafile-1-kB-copy --copy-source awscli-mint-test-bucket-3106/datafile-1-kB\n",
  "status": "FAIL",
  "error": "An error occurred (NotImplemented) when calling the CopyObject operation: A header you provided implies functionality that is not implemented"
}
(5/15) Running healthcheck tests ... done in 0 seconds
(6/15) Running mc tests ... done in 3 minutes and 16 seconds
(7/15) Running minio-dotnet tests ... done in 1 minutes and 26 seconds
(8/15) Running minio-go tests ... FAILED in 4 minutes and 9 seconds
{}
(8/15) Running minio-java tests ... FAILED in 25 minutes and 39 seconds
{
  "name": "minio-java",
  "function": "enableObjectLegalHold(String bucketName, String objectName, String versionId)",
  "duration": 1722,
  "status": "FAIL",
  "error": "error occurred\nErrorResponse(code = InvalidRequest, message = Bucket is missing ObjectLockConfiguration, bucketName = minio-java-test-4t05u8, objectName = minio-java-test-389vlps, resource = /minio-java-test-4t05u8/minio-java-test-389vlps, requestId = 1609BC2F2709B9AC, hostId = 999e4612-4bcd-4d83-aab4-fca780cf6fb5)\nrequest={method=PUT, url=http://minio-c4.minio.io:32097/minio-java-test-4t05u8/minio-java-test-389vlps?legal-hold=, headers=Host: minio-c4.minio.io:32097\nAccept-Encoding: identity\nUser-Agent: MinIO (amd64; amd64) minio-java/dev\nContent-MD5: erOisiAmIIzsh/Ze2QqGXw==\nx-amz-content-sha256: 96b73c95a8d33e664ab2170e095025b47ebd55978bb71cebd6a51e394bf96722\nx-amz-date: 20200427T170734Z\nAuthorization: AWS4-HMAC-SHA256 Credential=*REDACTED*/20200427/us-east-1/s3/aws4_request, SignedHeaders=accept-encoding;content-md5;host;x-amz-content-sha256;x-amz-date, Signature=*REDACTED*\n}\nresponse={code=400, headers=Accept-Ranges: bytes\nContent-Length: 382\nContent-Security-Policy: block-all-mixed-content\nContent-Type: application/xml\nServer: MinIO/DEVELOPMENT.GOGET\nVary: Origin\nX-Amz-Request-Id: 1609BC2F2709B9AC\nX-Xss-Protection: 1; mode=block\nDate: Mon, 27 Apr 2020 17:07:34 GMT\n}\n >>> [io.minio.MinioClient.execute(MinioClient.java:1211), io.minio.MinioClient.execute(MinioClient.java:1236), io.minio.MinioClient.executePut(MinioClient.java:1410), io.minio.MinioClient.executePut(MinioClient.java:1424), io.minio.MinioClient.enableObjectLegalHold(MinioClient.java:3568), FunctionalTest.enableObjectLegalHold_test(FunctionalTest.java:3303), FunctionalTest.runTests(FunctionalTest.java:4079), FunctionalTest.main(FunctionalTest.java:4192)]"
}
(8/15) Running minio-js tests ... FAILED in 2 minutes and 9 seconds
{
  "name": "minio-js",
  "function": "listObjectsV2WithMetadata(bucketName, prefix, recursive, startAfter)",
  "args": "bucketName:minio-js-test-a6d2c2fd-9067-46ab-a4cf-5d54e6686090, recursive:true",
  "duration": 209,
  "status": "FAIL",
  "error": "TypeError: Cannot read property '0' of undefined at /mint/run/core/minio-js/node_modules/minio/dist/main/xml-parsers.js:414:42 at Array.forEach (<anonymous>) at parseListObjectsV2WithMetadata (node_modules/minio/dist/main/xml-parsers.js:409:21) at DestroyableTransform._flush (node_modules/minio/dist/main/transformers.js:88:19) at DestroyableTransform.prefinish (node_modules/readable-stream/lib/_stream_transform.js:129:10) at prefinish (node_modules/readable-stream/lib/_stream_writable.js:611:14) at finishMaybe (node_modules/readable-stream/lib/_stream_writable.js:620:5) at endWritable (node_modules/readable-stream/lib/_stream_writable.js:643:3) at DestroyableTransform.Writable.end (node_modules/readable-stream/lib/_stream_writable.js:571:22) at IncomingMessage.onend (_stream_readable.js:673:10) at endReadableNT (_stream_readable.js:1201:12) at processTicksAndRejections (internal/process/task_queues.js:84:21)"
}
(8/15) Running minio-py tests ... done in 10 minutes and 4 seconds
(9/15) Running s3cmd tests ... FAILED in 48 seconds
{
  "name": "s3cmd",
  "duration": "1897",
  "function": "test_copy_object",
  "status": "FAIL",
  "error": ""
}
(9/15) Running s3select tests ... done in 22 seconds
(10/15) Running security tests ... done in 0 seconds

Executed 10 out of 15 tests successfully.
```
<a name="06df298d-5916-4fc7-bab8-4fd5636836e4"></a>
### 9461-47a93a2/mint-gateway-nas.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-dev3.minio.io:32112
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp a1e109b1e811:/mint/log /tmp/mint-logs'

(1/15) Running aws-sdk-go tests ... done in 1 seconds
(2/15) Running aws-sdk-java tests ... done in 1 seconds
(3/15) Running aws-sdk-php tests ... done in 42 seconds
(4/15) Running aws-sdk-ruby tests ... done in 2 seconds
(5/15) Running awscli tests ... done in 1 minutes and 10 seconds
(6/15) Running healthcheck tests ... done in 0 seconds
(7/15) Running mc tests ... done in 35 seconds
(8/15) Running minio-dotnet tests ... done in 30 seconds
(9/15) Running minio-go tests ... FAILED in 1 minutes and 20 seconds
{}
(9/15) Running minio-java tests ... FAILED in 50 seconds
{
  "name": "minio-java",
  "function": "enableObjectLegalHold(String bucketName, String objectName, String versionId)",
  "duration": 53,
  "status": "FAIL",
  "error": "error occurred\nErrorResponse(code = InvalidRequest, message = Bucket is missing ObjectLockConfiguration, bucketName = minio-java-test-2i9ads1, objectName = minio-java-test-j8f7dt, resource = /minio-java-test-2i9ads1/minio-java-test-j8f7dt, requestId = 1609BA693488B9C4, hostId = b7787e84-5e33-4b9d-8066-78f9eb71c948)\nrequest={method=PUT, url=http://minio-dev3.minio.io:32112/minio-java-test-2i9ads1/minio-java-test-j8f7dt?legal-hold=, headers=Host: minio-dev3.minio.io:32112\nAccept-Encoding: identity\nUser-Agent: MinIO (amd64; amd64) minio-java/dev\nContent-MD5: erOisiAmIIzsh/Ze2QqGXw==\nx-amz-content-sha256: 96b73c95a8d33e664ab2170e095025b47ebd55978bb71cebd6a51e394bf96722\nx-amz-date: 20200427T163504Z\nAuthorization: AWS4-HMAC-SHA256 Credential=*REDACTED*/20200427/us-east-1/s3/aws4_request, SignedHeaders=accept-encoding;content-md5;host;x-amz-content-sha256;x-amz-date, Signature=*REDACTED*\n}\nresponse={code=400, headers=Accept-Ranges: bytes\nContent-Length: 382\nContent-Security-Policy: block-all-mixed-content\nContent-Type: application/xml\nServer: MinIO/DEVELOPMENT.GOGET\nVary: Origin\nX-Amz-Request-Id: 1609BA693488B9C4\nX-Xss-Protection: 1; mode=block\nDate: Mon, 27 Apr 2020 16:35:04 GMT\n}\n >>> [io.minio.MinioClient.execute(MinioClient.java:1211), io.minio.MinioClient.execute(MinioClient.java:1236), io.minio.MinioClient.executePut(MinioClient.java:1410), io.minio.MinioClient.executePut(MinioClient.java:1424), io.minio.MinioClient.enableObjectLegalHold(MinioClient.java:3568), FunctionalTest.enableObjectLegalHold_test(FunctionalTest.java:3303), FunctionalTest.runTests(FunctionalTest.java:4079), FunctionalTest.main(FunctionalTest.java:4192)]"
}
(9/15) Running minio-js tests ... done in 58 seconds
(10/15) Running minio-py tests ... done in 1 minutes and 24 seconds
(11/15) Running s3cmd tests ... done in 28 seconds
(12/15) Running s3select tests ... done in 1 seconds
(13/15) Running security tests ... done in 0 seconds

Executed 13 out of 15 tests successfully.
```
Deleting image on docker hub
Deleting image locally

**Review by Praveenrajmani — APPROVED** [review]
Tested and LGTM

**Comment by Praveenrajmani** [comment]
Can you check the CI failure @harshavardhana

**Comment by minio-trusted** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-xl.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-dist-xl.sh | :heavy_check_mark: |
| mint-gateway-azure.sh | :x: [more...](#433ea716-4152-4524-93b4-81fb127c1dde) |
| mint-gateway-nas.sh | :x: [more...](#b060a8f6-8fb4-4d93-b391-d13039739eba) |
<a name="b060a8f6-8fb4-4d93-b391-d13039739eba"></a>
### 9461-7e692eb/mint-gateway-nas.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-c3.minio.io:31077
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 2bc1e2b3f621:/mint/log /tmp/mint-logs'

(1/15) Running aws-sdk-go tests ... done in 0 seconds
(2/15) Running aws-sdk-java tests ... done in 2 seconds
(3/15) Running aws-sdk-php tests ... done in 41 seconds
(4/15) Running aws-sdk-ruby tests ... done in 3 seconds
(5/15) Running awscli tests ... done in 2 minutes and 4 seconds
(6/15) Running healthcheck tests ... done in 0 seconds
(7/15) Running mc tests ... done in 52 seconds
(8/15) Running minio-dotnet tests ... done in 31 seconds
(9/15) Running minio-go tests ... FAILED in 1 minutes and 10 seconds
{}
(9/15) Running minio-java tests ... FAILED in 47 seconds
{
  "name": "minio-java",
  "function": "enableObjectLegalHold(String bucketName, String objectName, String versionId)",
  "duration": 51,
  "status": "FAIL",
  "error": "error occurred\nErrorResponse(code = InvalidRequest, message = Bucket is missing ObjectLockConfiguration, bucketName = minio-java-test-2nntra6, objectName = minio-java-test-3rpe4nd, resource = /minio-java-test-2nntra6/minio-java-test-3rpe4nd, requestId = 1609C5052C468BB6, hostId = a2254c1e-efdb-4f72-a67a-70e3f69663a3)\nrequest={method=PUT, url=http://minio-c3.minio.io:31077/minio-java-test-2nntra6/minio-java-test-3rpe4nd?legal-hold=, headers=Host: minio-c3.minio.io:31077\nAccept-Encoding: identity\nUser-Agent: MinIO (amd64; amd64) minio-java/dev\nContent-MD5: erOisiAmIIzsh/Ze2QqGXw==\nx-amz-content-sha256: 96b73c95a8d33e664ab2170e095025b47ebd55978bb71cebd6a51e394bf96722\nx-amz-date: 20200427T194929Z\nAuthorization: AWS4-HMAC-SHA256 Credential=*REDACTED*/20200427/us-east-1/s3/aws4_request, SignedHeaders=accept-encoding;content-md5;host;x-amz-content-sha256;x-amz-date, Signature=*REDACTED*\n}\nresponse={code=400, headers=Accept-Ranges: bytes\nContent-Length: 384\nContent-Security-Policy: block-all-mixed-content\nContent-Type: application/xml\nServer: MinIO/DEVELOPMENT.GOGET\nVary: Origin\nX-Amz-Request-Id: 1609C5052C468BB6\nX-Xss-Protection: 1; mode=block\nDate: Mon, 27 Apr 2020 19:49:29 GMT\n}\n >>> [io.minio.MinioClient.execute(MinioClient.java:1211), io.minio.MinioClient.execute(MinioClient.java:1236), io.minio.MinioClient.executePut(MinioClient.java:1410), io.minio.MinioClient.executePut(MinioClient.java:1424), io.minio.MinioClient.enableObjectLegalHold(MinioClient.java:3568), FunctionalTest.enableObjectLegalHold_test(FunctionalTest.java:3303), FunctionalTest.runTests(FunctionalTest.java:4079), FunctionalTest.main(FunctionalTest.java:4192)]"
}
(9/15) Running minio-js tests ... done in 40 seconds
(10/15) Running minio-py tests ... done in 1 minutes and 27 seconds
(11/15) Running s3cmd tests ... done in 21 seconds
(12/15) Running s3select tests ... done in 1 seconds
(13/15) Running security tests ... done in 0 seconds

Executed 13 out of 15 tests successfully.
```
<a name="433ea716-4152-4524-93b4-81fb127c1dde"></a>
### 9461-7e692eb/mint-gateway-azure.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-dev6.minio.io:32057
ACCESS_KEY:           minioazure
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 6d8b59046927:/mint/log /tmp/mint-logs'

(1/15) Running aws-sdk-go tests ... done in 8 seconds
(2/15) Running aws-sdk-java tests ... done in 1 seconds
(3/15) Running aws-sdk-php tests ... done in 2 minutes and 3 seconds
(4/15) Running aws-sdk-ruby tests ... done in 14 seconds
(5/15) Running awscli tests ... FAILED in 48 seconds
{
  "name": "awscli",
  "duration": 3885,
  "function": "aws --endpoint-url http://minio-dev6.minio.io:32057 s3api copy-object --bucket awscli-mint-test-bucket-17530 --storage-class REDUCED_REDUNDANCY --key datafile-1-kB-copy --copy-source awscli-mint-test-bucket-17530/datafile-1-kB\n",
  "status": "FAIL",
  "error": "An error occurred (NotImplemented) when calling the CopyObject operation: A header you provided implies functionality that is not implemented"
}
(5/15) Running healthcheck tests ... done in 0 seconds
(6/15) Running mc tests ... done in 3 minutes and 43 seconds
(7/15) Running minio-dotnet tests ... done in 1 minutes and 27 seconds
(8/15) Running minio-go tests ... FAILED in 4 minutes and 45 seconds
{}
(8/15) Running minio-java tests ... FAILED in 25 minutes and 25 seconds
{
  "name": "minio-java",
  "function": "enableObjectLegalHold(String bucketName, String objectName, String versionId)",
  "duration": 1680,
  "status": "FAIL",
  "error": "error occurred\nErrorResponse(code = InvalidRequest, message = Bucket is missing ObjectLockConfiguration, bucketName = minio-java-test-2fgm84t, objectName = minio-java-test-1t82flj, resource = /minio-java-test-2fgm84t/minio-java-test-1t82flj, requestId = 1609C6C98032E282, hostId = df8af4f3-8554-493f-86d8-aa7a2d2d4498)\nrequest={method=PUT, url=http://minio-dev6.minio.io:32057/minio-java-test-2fgm84t/minio-java-test-1t82flj?legal-hold=, headers=Host: minio-dev6.minio.io:32057\nAccept-Encoding: identity\nUser-Agent: MinIO (amd64; amd64) minio-java/dev\nContent-MD5: erOisiAmIIzsh/Ze2QqGXw==\nx-amz-content-sha256: 96b73c95a8d33e664ab2170e095025b47ebd55978bb71cebd6a51e394bf96722\nx-amz-date: 20200427T202152Z\nAuthorization: AWS4-HMAC-SHA256 Credential=*REDACTED*/20200427/us-east-1/s3/aws4_request, SignedHeaders=accept-encoding;content-md5;host;x-amz-content-sha256;x-amz-date, Signature=*REDACTED*\n}\nresponse={code=400, headers=Accept-Ranges: bytes\nContent-Length: 384\nContent-Security-Policy: block-all-mixed-content\nContent-Type: application/xml\nServer: MinIO/DEVELOPMENT.GOGET\nVary: Origin\nX-Amz-Request-Id: 1609C6C98032E282\nX-Xss-Protection: 1; mode=block\nDate: Mon, 27 Apr 2020 20:21:52 GMT\n}\n >>> [io.minio.MinioClient.execute(MinioClient.java:1211), io.minio.MinioClient.execute(MinioClient.java:1236), io.minio.MinioClient.executePut(MinioClient.java:1410), io.minio.MinioClient.executePut(MinioClient.java:1424), io.minio.MinioClient.enableObjectLegalHold(MinioClient.java:3568), FunctionalTest.enableObjectLegalHold_test(FunctionalTest.java:3303), FunctionalTest.runTests(FunctionalTest.java:4079), FunctionalTest.main(FunctionalTest.java:4192)]"
}
(8/15) Running minio-js tests ... FAILED in 2 minutes and 13 seconds
{
  "name": "minio-js",
  "function": "listObjectsV2WithMetadata(bucketName, prefix, recursive, startAfter)",
  "args": "bucketName:minio-js-test-036b6ad1-0ef3-49bb-8cab-c963203d01a3, recursive:true",
  "duration": 208,
  "status": "FAIL",
  "error": "TypeError: Cannot read property '0' of undefined at /mint/run/core/minio-js/node_modules/minio/dist/main/xml-parsers.js:414:42 at Array.forEach (<anonymous>) at parseListObjectsV2WithMetadata (node_modules/minio/dist/main/xml-parsers.js:409:21) at DestroyableTransform._flush (node_modules/minio/dist/main/transformers.js:88:19) at DestroyableTransform.prefinish (node_modules/readable-stream/lib/_stream_transform.js:129:10) at prefinish (node_modules/readable-stream/lib/_stream_writable.js:611:14) at finishMaybe (node_modules/readable-stream/lib/_stream_writable.js:620:5) at endWritable (node_modules/readable-stream/lib/_stream_writable.js:643:3) at DestroyableTransform.Writable.end (node_modules/readable-stream/lib/_stream_writable.js:571:22) at IncomingMessage.onend (_stream_readable.js:673:10) at endReadableNT (_stream_readable.js:1201:12) at processTicksAndRejections (internal/process/task_queues.js:84:21)"
}
(8/15) Running minio-py tests ... done in 9 minutes and 44 seconds
(9/15) Running s3cmd tests ... FAILED in 48 seconds
{
  "name": "s3cmd",
  "duration": "2042",
  "function": "test_copy_object",
  "status": "FAIL",
  "error": ""
}
(9/15) Running s3select tests ... done in 21 seconds
(10/15) Running security tests ... done in 0 seconds

Executed 10 out of 15 tests successfully.
```
Deleting image on docker hub
Deleting image locally

**Comment by harshavardhana** [comment]
PTAL @vadmeste

File: pkg/event/target/webhook.go [hunk 4]
```diff
@@ -94,16 +95,27 @@ func (target *WebhookTarget) HasQueueStore() bool {
...
 func (target *WebhookTarget) IsActive() (bool, error) {
-	u, pErr := xnet.ParseHTTPURL(target.args.Endpoint.String())
-	if pErr != nil {
-		return false, pErr
+	ctx, cancel := context.WithTimeout(context.Background(), 5*time.Second)
+	defer cancel()
+
+	req, err := http.NewRequest(http.MethodHead, target.args.Endpoint.String(), nil)
+	if err != nil {
+		if xnet.IsNetworkOrHostDown(err) {
```
Comment (vadmeste) [inline pkg/event/target/webhook.go:103]: I don't think http.NewRequest() can return a network or host down error here

**Review by vadmeste — COMMENTED** [review]
One comment, LGTM otherwise

File: pkg/event/target/webhook.go (hunk 4 above)
Comment (harshavardhana) [reply pkg/event/target/webhook.go:103]: @vadmeste the error can be `url.Error` which is why we used IsNetworkOrHostDown() to indicate as not connected. because we have no other top-level handling for other errors.

**Review by vadmeste — APPROVED** [review]
LGTM
