### PR TITLE
Fix crash on Windows when crawling

### LINKED ISSUE #10384: [windows] Heal WalkVersions: Hard crash on error
(Windows only maybe) 

Latest master f04a1f220c6a9ffe80916029bdaffe1be45f06a6 

Testing bucket recreation I got a hard crash on all but one system. System running the scan reports:

```
folder-scanner: checking disappeared folder: mybucket/go_113

API: SYSTEM()
Time: 13:32:20 CEST 08/31/2020
DeploymentID: 9832089e-60a3-4880-9008-7269da05e632
Error: volume not found
       8: d:\minio\minio\cmd\erasure-sets.go:986:cmd.(*erasureSets).startMergeWalksVersionsN()
       7: d:\minio\minio\cmd\erasure-sets.go:968:cmd.(*erasureSets).startMergeWalksVersions()
       6: d:\minio\minio\cmd\erasure-zones.go:1881:cmd.(*erasureZones).HealObjects()
       5: d:\minio\minio\cmd\data-crawler.go:472:cmd.(*folderScanner).scanQueuedLevels()
       4: d:\minio\minio\cmd\data-crawler.go:212:cmd.crawlDataFolder()
       3: d:\minio\minio\cmd\xl-storage.go:361:cmd.(*xlStorage).CrawlAndGetDataUsage()
       2: d:\minio\minio\cmd\storage-rest-server.go:165:cmd.(*storageRESTServer).CrawlAndGetDataUsageHandler()
       1: net\http\server.go:2012:http.HandlerFunc.ServeHTTP()
```

This causes all other servers to die.

## Expected Behavior

Servers keep running.

## Current Behavior

All but the server initiating the scan crashes.

<details>
<summary>Console log: on one of the crashes servers (Click to expand)</summary>

```

d:\minio\minio (master -> origin)
λ crawl-debug.cmd

SET MINIO_DISK_USAGE_CRAWL_DELAY=0

SET MINIO_DISK_USAGE_CRAWL_DEBUG=on

d:\minio\minio (master -> origin)
λ run-dist-xl-nozone.cmd

del minio.exe

go build -v
github.com/minio/minio/pkg/madmin
github.com/minio/minio/cmd/config
github.com/minio/minio/cmd/config/storageclass
github.com/minio/minio/cmd/config/identity/openid
github.com/minio/minio/cmd
github.com/minio/minio/cmd/gateway/nas
github.com/minio/minio/cmd/gateway/azure
github.com/minio/minio/cmd/gateway/gcs
github.com/minio/minio/cmd/gateway/hdfs
github.com/minio/minio/cmd/gateway/s3
github.com/minio/minio/cmd/gateway
github.com/minio/minio

SET MINIO_KMS_MASTER_KEY=my-minio-key:6368616e676520746869732070617373776f726420746f206120736563726574

SET MINIO_KMS_AUTO_ENCRYPTION=on

SET MINIO_ACCESS_KEY=minio

SET MINIO_SECRET_KEY=minio123

SET DRIVESPEC=http://localhost:9001/data/mindev/data2/xl1 http://localhost:9002/data/mindev/data2/xl2 http://localhost:9003/data/mindev/data2/xl3 http://localhost:9004/data/mindev/data2/xl4

start minio server --address :9004 http://localhost:9001/data/mindev/data2/xl1 http://localhost:9002/data/mindev/data2/xl2 http://localhost:9003/data/mindev/data2/xl3 http://localhost:9004/data/mindev/data2/xl4

start minio server --address :9003 http://localhost:9001/data/mindev/data2/xl1 http://localhost:9002/data/mindev/data2/xl2 http://localhost:9003/data/mindev/data2/xl3 http://localhost:9004/data/mindev/data2/xl4

start minio server --address :9002 http://localhost:9001/data/mindev/data2/xl1 http://localhost:9002/data/mindev/data2/xl2 http://localhost:9003/data/mindev/data2/xl3 http://localhost:9004/data/mindev/data2/xl4

minio server --address :9001 http://localhost:9001/data/mindev/data2/xl1 http://localhost:9002/data/mindev/data2/xl2 http://localhost:9003/data/mindev/data2/xl3 http://localhost:9004/data/mindev/data2/xl4
Waiting for all MinIO sub-systems to be initialized.. lock acquired
All MinIO sub-systems initialized successfully
Waiting for all MinIO IAM sub-system to be initialized.. lock acquired
Status:         4 Online, 0 Offline.
Endpoint:  http://172.17.27.241:9001  http://169.254.130.217:9001  http://169.254.172.206:9001  http://169.254.213.188:9001  http://169.254.52.129:9001  http://100.72.217.108:9001  http://192.168.1.78:9001  http://169.254.140.7:9001  http://127.0.0.1:9001
AccessKey: minio
SecretKey: minio123

Browser Access:
   http://172.17.27.241:9001  http://169.254.130.217:9001  http://169.254.172.206:9001  http://169.254.213.188:9001  http://169.254.52.129:9001  http://100.72.217.108:9001  http://192.168.1.78:9001  http://169.254.140.7:9001  http://127.0.0.1:9001

Command-line Access: https://docs.min.io/docs/minio-client-quickstart-guide
   $ mc.exe alias set myminio http://172.17.27.241:9001 minio minio123

Object API (Amazon S3 compatible):
   Go:         https://docs.min.io/docs/golang-client-quickstart-guide
   Java:       https://docs.min.io/docs/java-client-quickstart-guide
   Python:     https://docs.min.io/docs/python-client-quickstart-guide
   JavaScript: https://docs.min.io/docs/javascript-client-quickstart-guide
   .NET:       https://docs.min.io/docs/dotnet-client-quickstart-guide
Exiting on signal: INTERRUPT
Terminate batch job (Y/N)?
d:\minio\minio (master -> origin)
λ run-dist-xl-nozone.cmd

del minio.exe

go build -v
github.com/minio/minio/cmd
github.com/minio/minio/cmd/gateway/nas
github.com/minio/minio/cmd/gateway/azure
github.com/minio/minio/cmd/gateway/gcs
github.com/minio/minio/cmd/gateway/hdfs
github.com/minio/minio/cmd/gateway/s3
github.com/minio/minio

SET MINIO_KMS_MASTER_KEY=my-minio-key:6368616e676520746869732070617373776f726420746f206120736563726574

SET MINIO_KMS_AUTO_ENCRYPTION=on

SET MINIO_ACCESS_KEY=minio

SET MINIO_SECRET_KEY=minio123

SET DRIVESPEC=http://localhost:9001/data/mindev/data2/xl1 http://localhost:9002/data/mindev/data2/xl2 http://localhost:9003/data/mindev/data2/xl3 http://localhost:9004/data/mindev/data2/xl4

start minio server --address :9004 http://localhost:9001/data/mindev/data2/xl1 http://localhost:9002/data/mindev/data2/xl2 http://localhost:9003/data/mindev/data2/xl3 http://localhost:9004/data/mindev/data2/xl4

start minio server --address :9003 http://localhost:9001/data/mindev/data2/xl1 http://localhost:9002/data/mindev/data2/xl2 http://localhost:9003/data/mindev/data2/xl3 http://localhost:9004/data/mindev/data2/xl4

start minio server --address :9002 http://localhost:9001/data/mindev/data2/xl1 http://localhost:9002/data/mindev/data2/xl2 http://localhost:9003/data/mindev/data2/xl3 http://localhost:9004/data/mindev/data2/xl4

minio server --address :9001 http://localhost:9001/data/mindev/data2/xl1 http://localhost:9002/data/mindev/data2/xl2 http://localhost:9003/data/mindev/data2/xl3 http://localhost:9004/data/mindev/data2/xl4
Waiting for all MinIO sub-systems to be initialized.. lock acquired
All MinIO sub-systems initialized successfully
Waiting for all MinIO IAM sub-system to be initialized.. lock acquired
Status:         4 Online, 0 Offline.
Endpoint:  http://172.17.27.241:9001  http://169.254.130.217:9001  http://169.254.172.206:9001  http://169.254.213.188:9001  http://169.254.52.129:9001  http://100.72.217.108:9001  http://192.168.1.78:9001  http://169.254.140.7:9001  http://127.0.0.1:9001
AccessKey: minio
SecretKey: minio123

Browser Access:
   http://172.17.27.241:9001  http://169.254.130.217:9001  http://169.254.172.206:9001  http://169.254.213.188:9001  http://169.254.52.129:9001  http://100.72.217.108:9001  http://192.168.1.78:9001  http://169.254.140.7:9001  http://127.0.0.1:9001

Command-line Access: https://docs.min.io/docs/minio-client-quickstart-guide
   $ mc.exe alias set myminio http://172.17.27.241:9001 minio minio123

Object API (Amazon S3 compatible):
   Go:         https://docs.min.io/docs/golang-client-quickstart-guide
   Java:       https://docs.min.io/docs/java-client-quickstart-guide
   Python:     https://docs.min.io/docs/python-client-quickstart-guide
   JavaScript: https://docs.min.io/docs/javascript-client-quickstart-guide
   .NET:       https://docs.min.io/docs/dotnet-client-quickstart-guide
dataUpdateTracker: cycle bloom filter: 11510 -> 11511
dataUpdateTracker: Saving: 45033 bytes, Current idx: 11511
dataUpdateTracker: cycle bloom filter: 11511 -> 11512
dataUpdateTracker: Saving: 45033 bytes, Current idx: 11512
dataUpdateTracker: cycle bloom filter: 11512 -> 11513
dataUpdateTracker: Saving: 45033 bytes, Current idx: 11513
dataUpdateTracker: cycle bloom filter: 11513 -> 11514
dataUpdateTracker: Saving: 45033 bytes, Current idx: 11514
dataUpdateTracker: cycle bloom filter: 11514 -> 11515
dataUpdateTracker: Saving: 45033 bytes, Current idx: 11515
dataUpdateTracker: cycle bloom filter: 11515 -> 11516
dataUpdateTracker: Saving: 45033 bytes, Current idx: 11516
dataUpdateTracker: cycle bloom filter: 11516 -> 11517
dataUpdateTracker: Saving: 45033 bytes, Current idx: 11517
dataUpdateTracker: cycle bloom filter: 11517 -> 11518
dataUpdateTracker: Saving: 45033 bytes, Current idx: 11518
dataUpdateTracker: cycle bloom filter: 11518 -> 11519
dataUpdateTracker: Saving: 45033 bytes, Current idx: 11519
dataUpdateTracker: cycle bloom filter: 11519 -> 11520
dataUpdateTracker: Saving: 45033 bytes, Current idx: 11520
data-usage: Start crawling. Bloom filter: true - d:\data\mindev\data2\xl1 + mybucket
data-usage: Cycle: 8886, Entries: 155 - d:\data\mindev\data2\xl1 + mybucket
data-usage: Level 0, scanning 1 directories. - d:\data\mindev\data2\xl1 + mybucket
folder-scanner: Skipping non-updated folder: mybucket
data-usage: Level 1, scanning 0 directories. - d:\data\mindev\data2\xl1 + mybucket
data-usage: New folders: [] - d:\data\mindev\data2\xl1 + mybucket
data-usage: Existing folders: 0 - d:\data\mindev\data2\xl1 + mybucket
data-usage: Finished crawl, 155 entries - d:\data\mindev\data2\xl1 + mybucket
data-usage:  Crawl time: 34.9985ms - d:\data\mindev\data2\xl1 + mybucket
dataUpdateTracker: cycle bloom filter: 11520 -> 11521
dataUpdateTracker: Saving: 45033 bytes, Current idx: 11521
dataUpdateTracker: cycle bloom filter: 11521 -> 11522
dataUpdateTracker: Saving: 45033 bytes, Current idx: 11522
dataUpdateTracker: cycle bloom filter: 11522 -> 11523
dataUpdateTracker: Saving: 45033 bytes, Current idx: 11523
dataUpdateTracker: cycle bloom filter: 11523 -> 11524
dataUpdateTracker: Saving: 45033 bytes, Current idx: 11524
dataUpdateTracker: cycle bloom filter: 11524 -> 11525
dataUpdateTracker: Saving: 45033 bytes, Current idx: 11525
dataUpdateTracker: cycle bloom filter: 11525 -> 11526
dataUpdateTracker: Saving: 45033 bytes, Current idx: 11526
data-usage: Start crawling. Bloom filter: true - d:\data\mindev\data2\xl1 + mybucket
data-usage: Cycle: 8892, Entries: 155 - d:\data\mindev\data2\xl1 + mybucket
data-usage: Level 0, scanning 1 directories. - d:\data\mindev\data2\xl1 + mybucket
folder-scanner: Skipping non-updated folder: mybucket
data-usage: Level 1, scanning 0 directories. - d:\data\mindev\data2\xl1 + mybucket
data-usage: New folders: [] - d:\data\mindev\data2\xl1 + mybucket
data-usage: Existing folders: 0 - d:\data\mindev\data2\xl1 + mybucket
data-usage: Finished crawl, 155 entries - d:\data\mindev\data2\xl1 + mybucket
data-usage:  Crawl time: 32.9991ms - d:\data\mindev\data2\xl1 + mybucket
dataUpdateTracker: cycle bloom filter: 11526 -> 11527
dataUpdateTracker: Saving: 45033 bytes, Current idx: 11527
dataUpdateTracker: cycle bloom filter: 11527 -> 11528
dataUpdateTracker: Saving: 45033 bytes, Current idx: 11528
dataUpdateTracker: cycle bloom filter: 11528 -> 11529
dataUpdateTracker: Saving: 45033 bytes, Current idx: 11529
dataUpdateTracker: cycle bloom filter: 11529 -> 11530
dataUpdateTracker: Saving: 45033 bytes, Current idx: 11530
dataUpdateTracker: cycle bloom filter: 11530 -> 11531
dataUpdateTracker: Saving: 45033 bytes, Current idx: 11531
data-usage: Start crawling. Bloom filter: true - d:\data\mindev\data2\xl1 + mybucket
data-usage: Cycle: 8897, Entries: 155 - d:\data\mindev\data2\xl1 + mybucket
data-usage: Level 0, scanning 1 directories. - d:\data\mindev\data2\xl1 + mybucket
folder-scanner: Skipping non-updated folder: mybucket
data-usage: Level 1, scanning 0 directories. - d:\data\mindev\data2\xl1 + mybucket
data-usage: New folders: [] - d:\data\mindev\data2\xl1 + mybucket
data-usage: Existing folders: 0 - d:\data\mindev\data2\xl1 + mybucket
data-usage: Finished crawl, 155 entries - d:\data\mindev\data2\xl1 + mybucket
data-usage:  Crawl time: 36.0003ms - d:\data\mindev\data2\xl1 + mybucket
dataUpdateTracker: cycle bloom filter: 11531 -> 11532
dataUpdateTracker: Saving: 45033 bytes, Current idx: 11532
dataUpdateTracker: cycle bloom filter: 11532 -> 11533
dataUpdateTracker: Saving: 45033 bytes, Current idx: 11533
dataUpdateTracker: cycle bloom filter: 11533 -> 11534
dataUpdateTracker: Saving: 45033 bytes, Current idx: 11534
dataUpdateTracker: cycle bloom filter: 11534 -> 11535
dataUpdateTracker: Saving: 45033 bytes, Current idx: 11535
data-usage: Start crawling. Bloom filter: true - d:\data\mindev\data2\xl1 + mybucket
data-usage: Cycle: 8901, Entries: 157 - d:\data\mindev\data2\xl1 + mybucket
data-usage: Level 0, scanning 1 directories. - d:\data\mindev\data2\xl1 + mybucket
data-usage: Level 1, scanning 6 directories. - d:\data\mindev\data2\xl1 + mybucket
folder-scanner: Skipping non-updated folder: mybucket/doc
folder-scanner: Skipping non-updated folder: mybucket/go_113
folder-scanner: Skipping non-updated folder: mybucket/internal
folder-scanner: Skipping non-updated folder: mybucket/mc
folder-scanner: Skipping non-updated folder: mybucket/src
data-usage: New folders: [] - d:\data\mindev\data2\xl1 + mybucket
data-usage: Existing folders: 1 - d:\data\mindev\data2\xl1 + mybucket
data-usage: Finished crawl, 157 entries - d:\data\mindev\data2\xl1 + mybucket
data-usage:  Crawl time: 49.9996ms - d:\data\mindev\data2\xl1 + mybucket
dataUpdateTracker: cycle bloom filter: 11535 -> 11536
dataUpdateTracker: Saving: 45033 bytes, Current idx: 11536
data-usage: Start crawling. Bloom filter: true - d:\data\mindev\data2\xl1 + mybucket
data-usage: Cycle: 8902, Entries: 157 - d:\data\mindev\data2\xl1 + mybucket
data-usage: Level 0, scanning 1 directories. - d:\data\mindev\data2\xl1 + mybucket
data-usage: Level 1, scanning 6 directories. - d:\data\mindev\data2\xl1 + mybucket
folder-scanner: Skipping non-updated folder: mybucket/doc
folder-scanner: Skipping non-updated folder: mybucket/go_113
folder-scanner: Skipping non-updated folder: mybucket/internal
folder-scanner: Skipping non-updated folder: mybucket/mc
folder-scanner: Skipping non-updated folder: mybucket/src
data-usage: New folders: [] - d:\data\mindev\data2\xl1 + mybucket
data-usage: Existing folders: 1 - d:\data\mindev\data2\xl1 + mybucket
data-usage: Skipping non-updated folder: {mybucket/mc.exe/abecc36b-4c5c-4ed8-be83-cba28f9ed20c 0xc001aa0090 1} - d:\data\mindev\data2\xl1 + mybucket
data-usage: Finished crawl, 157 entries - d:\data\mindev\data2\xl1 + mybucket
data-usage:  Crawl time: 57.9991ms - d:\data\mindev\data2\xl1 + mybucket
dataUpdateTracker: cycle bloom filter: 11536 -> 11537
dataUpdateTracker: Saving: 45033 bytes, Current idx: 11537
dataUpdateTracker: cycle bloom filter: 11537 -> 11538
dataUpdateTracker: Saving: 45033 bytes, Current idx: 11538
dataUpdateTracker: cycle bloom filter: 11538 -> 11539
dataUpdateTracker: Saving: 45033 bytes, Current idx: 11539
dataUpdateTracker: cycle bloom filter: 11539 -> 11540
dataUpdateTracker: Saving: 45033 bytes, Current idx: 11540
dataUpdateTracker: cycle bloom filter: 11540 -> 11541
dataUpdateTracker: Saving: 45033 bytes, Current idx: 11541
dataUpdateTracker: cycle bloom filter: 11541 -> 11542
dataUpdateTracker: Saving: 45033 bytes, Current idx: 11542
data-usage: Start crawling. Bloom filter: true - d:\data\mindev\data2\xl1 + mybucket
data-usage: Cycle: 8908, Entries: 157 - d:\data\mindev\data2\xl1 + mybucket
data-usage: Level 0, scanning 1 directories. - d:\data\mindev\data2\xl1 + mybucket
data-usage: Level 1, scanning 6 directories. - d:\data\mindev\data2\xl1 + mybucket
folder-scanner: Skipping non-updated folder: mybucket/doc
folder-scanner: Skipping non-updated folder: mybucket/go_113
folder-scanner: Skipping non-updated folder: mybucket/internal
folder-scanner: Skipping non-updated folder: mybucket/mc
folder-scanner: Skipping non-updated folder: mybucket/src
data-usage: New folders: [] - d:\data\mindev\data2\xl1 + mybucket
data-usage: Existing folders: 1 - d:\data\mindev\data2\xl1 + mybucket
data-usage: Finished crawl, 157 entries - d:\data\mindev\data2\xl1 + mybucket
data-usage:  Crawl time: 48.0018ms - d:\data\mindev\data2\xl1 + mybucket
dataUpdateTracker: cycle bloom filter: 11542 -> 11543
dataUpdateTracker: Saving: 45033 bytes, Current idx: 11543
Exception 0xc0000005 0x1 0x66c 0x7fff838db38d
PC=0x7fff838db38d

syscall.Syscall(0x7fff82a821c0, 0x2, 0x63c, 0xc002809070, 0x0, 0x0, 0x0, 0x0)
        c:/go/src/runtime/syscall_windows.go:188 +0xe9
syscall.findNextFile1(0x63c, 0xc002809070, 0x20, 0x203000a)
        c:/go/src/syscall/zsyscall_windows.go:392 +0x76
syscall.FindNextFile(0x63c, 0xc002809334, 0x0, 0x0)
        c:/go/src/syscall/syscall_windows.go:1052 +0x73
github.com/minio/minio/cmd.readDirN(0xc0028225c0, 0x39, 0xffffffffffffffff, 0x0, 0x0, 0x0, 0x0, 0x0)
        d:/minio/minio/cmd/os-readdir_windows.go:85 +0x16c
github.com/minio/minio/cmd.readDir(...)
        d:/minio/minio/cmd/os-readdir_windows.go:28
github.com/minio/minio/cmd.(*xlStorage).ListDir(0xc00011bee0, 0xc001c289f7, 0x8, 0xc000c89fc0, 0x17, 0xffffffffffffffff, 0x0, 0x0, 0x0, 0x0, ...)
        d:/minio/minio/cmd/xl-storage.go:1076 +0x3f8
github.com/minio/minio/cmd.(*xlStorage).WalkVersions.func2.1(0xc001c289f7, 0x8, 0xc000c89fc0, 0x17, 0x0, 0x0, 0x0, 0xc000286700, 0x1c0e58, 0x0, ...)
        d:/minio/minio/cmd/xl-storage.go:917 +0x85
github.com/minio/minio/cmd.doTreeWalk(0x213d9e0, 0xc0003ae180, 0xc001c289f7, 0x8, 0xc000c89fc0, 0x17, 0x0, 0x0, 0x0, 0x0, ...)
        d:/minio/minio/cmd/tree-walk.go:147 +0xd0
github.com/minio/minio/cmd.doTreeWalk(0x213d9e0, 0xc0003ae180, 0xc001c289f7, 0x8, 0xc001c295e0, 0xb, 0x0, 0x0, 0x0, 0x0, ...)
        d:/minio/minio/cmd/tree-walk.go:215 +0x4db
github.com/minio/minio/cmd.doTreeWalk(0x213d9e0, 0xc0003ae180, 0xc001c289f7, 0x8, 0xc001c28dd6, 0x7, 0x0, 0x0, 0x0, 0x0, ...)
        d:/minio/minio/cmd/tree-walk.go:215 +0x4db
github.com/minio/minio/cmd.doTreeWalk(0x213d9e0, 0xc0003ae180, 0xc001c289f7, 0x8, 0x0, 0x0, 0xc001c28a19, 0x6, 0xc001c28a30, 0x0, ...)
        d:/minio/minio/cmd/tree-walk.go:215 +0x4db
github.com/minio/minio/cmd.startTreeWalk.func1(0x213d9e0, 0xc0003ae180, 0xc001c289f7, 0x8, 0x0, 0x0, 0xc001c28a19, 0x6, 0xc001c28a30, 0x0, ...)
        d:/minio/minio/cmd/tree-walk.go:265 +0x111
created by github.com/minio/minio/cmd.startTreeWalk
        d:/minio/minio/cmd/tree-walk.go:263 +0x1cb

goroutine 1 [select, 3 minutes]:
github.com/minio/minio/cmd.handleSignals()
        d:/minio/minio/cmd/signals.go:73 +0x125
github.com/minio/minio/cmd.serverMain(0xc00014cd00)
        d:/minio/minio/cmd/server-main.go:555 +0xb16
github.com/minio/cli.HandleAction(0x19c43e0, 0x1dc6980, 0xc00014cd00, 0xc000192300, 0x0)
        e:/gopath/pkg/mod/github.com/minio/cli@v1.22.0/app.go:500 +0x83
github.com/minio/cli.Command.Run(0x1d2e2f1, 0x6, 0x0, 0x0, 0x0, 0x0, 0x0, 0x1d58e37, 0x1b, 0x0, ...)
        e:/gopath/pkg/mod/github.com/minio/cli@v1.22.0/command.go:225 +0x9ef
github.com/minio/cli.(*App).Run(0xc00014c340, 0xc00014a000, 0x8, 0x8, 0x0, 0x0)
        e:/gopath/pkg/mod/github.com/minio/cli@v1.22.0/app.go:261 +0x748
github.com/minio/minio/cmd.Main(0xc00014a000, 0x8, 0x8)
        d:/minio/minio/cmd/main.go:169 +0x90
main.main()
        d:/minio/minio/main.go:37 +0x4c

goroutine 19 [chan receive, 3 minutes]:
github.com/rjeczalik/notify.(*recursiveTree).dispatch(0xc0001687d0)
        e:/gopath/pkg/mod/github.com/rjeczalik/notify@v0.9.2/tree_recursive.go:125 +0xcb
created by github.com/rjeczalik/notify.newRecursiveTree
        e:/gopath/pkg/mod/github.com/rjeczalik/notify@v0.9.2/tree_recursive.go:119 +0x139

goroutine 20 [sleep, 3 minutes]:
time.Sleep(0x1a3185c5000)
        c:/go/src/runtime/time.go:188 +0xc8
github.com/minio/minio/cmd/logger.(*logOnceType).cleanupRoutine(0xc0001d42c0)
        d:/minio/minio/cmd/logger/logonce.go:63 +0x3d
created by github.com/minio/minio/cmd/logger.newLogOnceType
        d:/minio/minio/cmd/logger/logonce.go:70 +0x7e

goroutine 1298 [IO wait]:
internal/poll.runtime_pollWait(0x30110c48, 0x72, 0x21097a0)
        c:/go/src/runtime/netpoll.go:203 +0x5c
internal/poll.(*pollDesc).wait(0xc00037cbc8, 0x72, 0x2f69800, 0x0, 0x0)
        c:/go/src/internal/poll/fd_poll_runtime.go:87 +0x4c
internal/poll.(*ioSrv).ExecIO(0x353faa0, 0xc00037ca18, 0x1dc8ac0, 0x0, 0xc00037caf0, 0xc00037cb20)
        c:/go/src/internal/poll/fd_windows.go:228 +0x121
internal/poll.(*FD).Read(0xc00037ca00, 0xc001323000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
        c:/go/src/internal/poll/fd_windows.go:527 +0x2fc
net.(*netFD).Read(0xc00037ca00, 0xc001323000, 0x1000, 0x1000, 0xc00037ca00, 0x0, 0xc00037ca00)
        c:/go/src/net/fd_windows.go:152 +0x56
net.(*conn).Read(0xc001b88640, 0xc001323000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
        c:/go/src/net/net.go:184 +0x95
net/http.(*connReader).Read(0xc001379c80, 0xc001323000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
        c:/go/src/net/http/server.go:786 +0xfb
bufio.(*Reader).fill(0xc001a89500)
        c:/go/src/bufio/bufio.go:100 +0x10a
bufio.(*Reader).Peek(0xc001a89500, 0x4, 0x0, 0x0, 0x0, 0x0, 0x43b0f5)
        c:/go/src/bufio/bufio.go:138 +0x56
net/http.(*conn).readRequest(0xc000691400, 0x213d9e0, 0xc001896bc0, 0x0, 0x0, 0x0)
        c:/go/src/net/http/server.go:963 +0xc7d
net/http.(*conn).serve(0xc000691400, 0x213d9e0, 0xc001896bc0)
        c:/go/src/net/http/server.go:1822 +0x6db
created by net/http.(*Server).Serve
        c:/go/src/net/http/server.go:2933 +0x363

goroutine 69 [select]:
go.opencensus.io/stats/view.(*worker).start(0xc0001686e0)
        e:/gopath/pkg/mod/go.opencensus.io@v0.22.3/stats/view/worker.go:154 +0x107
created by go.opencensus.io/stats/view.init.0
        e:/gopath/pkg/mod/go.opencensus.io@v0.22.3/stats/view/worker.go:32 +0x5e

goroutine 70 [syscall, 3 minutes]:
os/signal.signal_recv(0x0)
        c:/go/src/runtime/sigqueue.go:147 +0xa3
os/signal.loop()
        c:/go/src/os/signal/signal_unix.go:23 +0x29
created by os/signal.Notify.func1
        c:/go/src/os/signal/signal.go:127 +0x4b

goroutine 97 [select, 3 minutes]:
github.com/minio/minio/cmd.(*allHealState).periodicHealSeqsClean(0xc00024ff80, 0x213d9e0, 0xc0003ae180)
        d:/minio/minio/cmd/admin-heal-ops.go:126 +0x218
created by github.com/minio/minio/cmd.newHealState
        d:/minio/minio/cmd/admin-heal-ops.go:101 +0x97

goroutine 98 [select, 3 minutes]:
github.com/minio/minio/cmd.(*allHealState).periodicHealSeqsClean(0xc00031e000, 0x213d9e0, 0xc0003ae180)
        d:/minio/minio/cmd/admin-heal-ops.go:126 +0x218
created by github.com/minio/minio/cmd.newHealState
        d:/minio/minio/cmd/admin-heal-ops.go:101 +0x97

goroutine 99 [sleep]:
time.Sleep(0xbb5282e8c)
        c:/go/src/runtime/time.go:188 +0xc8
github.com/minio/minio/cmd.startLockMaintenance(0x213d9e0, 0xc0003ae180)
        d:/minio/minio/cmd/lock-rest-server.go:334 +0x1f7
created by github.com/minio/minio/cmd.registerLockRESTHandlers
        d:/minio/minio/cmd/lock-rest-server.go:369 +0x1c2

goroutine 105 [select, 3 minutes]:
io.(*pipe).Read(0xc000ee8240, 0xc0005b1000, 0x1000, 0x1000, 0x0, 0xc0003ae100, 0x2030000)
        c:/go/src/io/pipe.go:57 +0xee
io.(*PipeReader).Read(0xc000141b28, 0xc0005b1000, 0x1000, 0x1000, 0x19caf20, 0x2030001, 0xc0005b1000)
        c:/go/src/io/pipe.go:134 +0x53
github.com/minio/minio/cmd.(*contextReader).Read(0xc0006a0020, 0xc0005b1000, 0x1000, 0x1000, 0x40d310, 0xc0006a0020, 0x20)
        d:/minio/minio/cmd/object-api-utils.go:893 +0xc5
bufio.(*Scanner).Scan(0xc000cf1f38, 0xc0006a0020)
        c:/go/src/bufio/scan.go:213 +0xab
github.com/minio/minio/cmd.serverMain.func2(0xc000141b28)
        d:/minio/minio/cmd/server-main.go:472 +0x16c
created by github.com/minio/minio/cmd.serverMain
        d:/minio/minio/cmd/server-main.go:469 +0x4ba

goroutine 106 [chan receive]:
github.com/minio/minio/cmd/http.(*httpListener).Accept(0xc0006a2090, 0xc000cf3e30, 0x18, 0xc000ed0900, 0x705ff3)
        d:/minio/minio/cmd/http/listener.go:111 +0x5e
net/http.(*Server).Serve(0xc000254c60, 0x2130b60, 0xc0006a2090, 0x0, 0x0)
        c:/go/src/net/http/server.go:2901 +0x264
github.com/minio/minio/cmd/http.(*Server).Start(0xc000254c60, 0x0, 0x0)
        d:/minio/minio/cmd/http/server.go:112 +0x246
github.com/minio/minio/cmd.serverMain.func4(0xc000254c60)
        d:/minio/minio/cmd/server-main.go:483 +0x32
created by github.com/minio/minio/cmd.serverMain
        d:/minio/minio/cmd/server-main.go:482 +0x63e

goroutine 114 [IO wait]:
internal/poll.runtime_pollWait(0x2d174bd8, 0x72, 0x21097a0)
        c:/go/src/runtime/netpoll.go:203 +0x5c
internal/poll.(*pollDesc).wait(0xc0006aa1c8, 0x72, 0x2f69800, 0x0, 0x0)
        c:/go/src/internal/poll/fd_poll_runtime.go:87 +0x4c
internal/poll.(*ioSrv).ExecIO(0x353faa0, 0xc0006aa018, 0xc001aa90e0, 0x1, 0x0, 0x654)
        c:/go/src/internal/poll/fd_windows.go:228 +0x121
internal/poll.(*FD).acceptOne(0xc0006aa000, 0x654, 0xc001a9c5a0, 0x2, 0x2, 0xc0006aa018, 0x98000004, 0xc000f03edc, 0xc, 0x0)
        c:/go/src/internal/poll/fd_windows.go:896 +0xa9
internal/poll.(*FD).Accept(0xc0006aa000, 0xc000f03ee0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        c:/go/src/internal/poll/fd_windows.go:930 +0x15f
net.(*netFD).accept(0xc0006aa000, 0x37e11d600, 0x0, 0x0)
        c:/go/src/net/fd_windows.go:193 +0x7b
net.(*TCPListener).accept(0xc0006a0060, 0xc000f03f88, 0xc000f03f90, 0x10)
        c:/go/src/net/tcpsock_posix.go:139 +0x39
net.(*TCPListener).AcceptTCP(0xc0006a0060, 0xc0006a6020, 0xc0002852d8, 0xc0006ae060)
        c:/go/src/net/tcpsock.go:248 +0x6c
github.com/minio/minio/cmd/http.(*httpListener).start.func3(0xc0006a0060, 0xc0006ae060)
        d:/minio/minio/cmd/http/listener.go:91 +0x48
created by github.com/minio/minio/cmd/http.(*httpListener).start
        d:/minio/minio/cmd/http/listener.go:105 +0x18c

goroutine 391 [select]:
github.com/minio/minio/cmd.(*erasureSets).monitorAndConnectEndpoints(0xc001522160, 0x213d9e0, 0xc0003ae180, 0x2540be400)
        d:/minio/minio/cmd/erasure-sets.go:251 +0x12c
created by github.com/minio/minio/cmd.newErasureSets
        d:/minio/minio/cmd/erasure-sets.go:372 +0xd29

goroutine 399 [select]:
github.com/minio/minio/cmd.(*dataUpdateTracker).startSaver(0xc00068f0a0, 0x213d9e0, 0xc0003ae180, 0x45d964b800, 0xc0010a3e80, 0x1, 0x1)
        d:/minio/minio/cmd/data-update-tracker.go:229 +0x1fa
created by github.com/minio/minio/cmd.(*dataUpdateTracker).start
        d:/minio/minio/cmd/data-update-tracker.go:183 +0x122

goroutine 42 [IO wait]:
internal/poll.runtime_pollWait(0x2d174858, 0x72, 0x21097a0)
        c:/go/src/runtime/netpoll.go:203 +0x5c
internal/poll.(*pollDesc).wait(0xc000f8c1c8, 0x72, 0x2f69800, 0x0, 0x0)
        c:/go/src/internal/poll/fd_poll_runtime.go:87 +0x4c
internal/poll.(*ioSrv).ExecIO(0x353faa0, 0xc000f8c018, 0x1dc8ac0, 0x0, 0xc000f8c0f0, 0xc000f8c120)
        c:/go/src/internal/poll/fd_windows.go:228 +0x121
internal/poll.(*FD).Read(0xc000f8c000, 0xc001010000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
        c:/go/src/internal/poll/fd_windows.go:527 +0x2fc
net.(*netFD).Read(0xc000f8c000, 0xc001010000, 0x1000, 0x1000, 0xc000f8c000, 0x0, 0xc000f8c000)
        c:/go/src/net/fd_windows.go:152 +0x56
net.(*conn).Read(0xc000141bd8, 0xc001010000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
        c:/go/src/net/net.go:184 +0x95
net/http.(*connReader).Read(0xc0002fe0c0, 0xc001010000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
        c:/go/src/net/http/server.go:786 +0xfb
bufio.(*Reader).fill(0xc001000180)
        c:/go/src/bufio/bufio.go:100 +0x10a
bufio.(*Reader).Peek(0xc001000180, 0x4, 0x0, 0x0, 0x0, 0x0, 0x43b0f5)
        c:/go/src/bufio/bufio.go:138 +0x56
net/http.(*conn).readRequest(0xc00100a0a0, 0x213d9e0, 0xc001004040, 0x0, 0x0, 0x0)
        c:/go/src/net/http/server.go:963 +0xc7d
net/http.(*conn).serve(0xc00100a0a0, 0x213d9e0, 0xc001004040)
        c:/go/src/net/http/server.go:1822 +0x6db
created by net/http.(*Server).Serve
        c:/go/src/net/http/server.go:2933 +0x363

goroutine 146 [IO wait]:
internal/poll.runtime_pollWait(0x2d174778, 0x72, 0x21097a0)
        c:/go/src/runtime/netpoll.go:203 +0x5c
internal/poll.(*pollDesc).wait(0xc0001c06c8, 0x72, 0x2f69800, 0x0, 0x0)
        c:/go/src/internal/poll/fd_poll_runtime.go:87 +0x4c
internal/poll.(*ioSrv).ExecIO(0x353faa0, 0xc0001c0518, 0x1dc8ac0, 0x0, 0xc0001c05f0, 0xc0001c0620)
        c:/go/src/internal/poll/fd_windows.go:228 +0x121
internal/poll.(*FD).Read(0xc0001c0500, 0xc000f8e000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
        c:/go/src/internal/poll/fd_windows.go:527 +0x2fc
net.(*netFD).Read(0xc0001c0500, 0xc000f8e000, 0x1000, 0x1000, 0xc0001c0500, 0x0, 0xc0001c0500)
        c:/go/src/net/fd_windows.go:152 +0x56
net.(*conn).Read(0xc0000069b0, 0xc000f8e000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
        c:/go/src/net/net.go:184 +0x95
net/http.(*connReader).Read(0xc00013a6f0, 0xc000f8e000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
        c:/go/src/net/http/server.go:786 +0xfb
bufio.(*Reader).fill(0xc0000b4180)
        c:/go/src/bufio/bufio.go:100 +0x10a
bufio.(*Reader).Peek(0xc0000b4180, 0x4, 0x0, 0x0, 0x0, 0x0, 0x43b0f5)
        c:/go/src/bufio/bufio.go:138 +0x56
net/http.(*conn).readRequest(0xc0006901e0, 0x213d9e0, 0xc000298100, 0x0, 0x0, 0x0)
        c:/go/src/net/http/server.go:963 +0xc7d
net/http.(*conn).serve(0xc0006901e0, 0x213d9e0, 0xc000298100)
        c:/go/src/net/http/server.go:1822 +0x6db
created by net/http.(*Server).Serve
        c:/go/src/net/http/server.go:2933 +0x363

goroutine 140 [IO wait]:
internal/poll.runtime_pollWait(0x2d174698, 0x72, 0x21097a0)
        c:/go/src/runtime/netpoll.go:203 +0x5c
internal/poll.(*pollDesc).wait(0xc0001435c8, 0x72, 0x2f69800, 0x0, 0x0)
        c:/go/src/internal/poll/fd_poll_runtime.go:87 +0x4c
internal/poll.(*ioSrv).ExecIO(0x353faa0, 0xc000143418, 0x1dc8ac0, 0x0, 0xc0001434f0, 0xc000143520)
        c:/go/src/internal/poll/fd_windows.go:228 +0x121
internal/poll.(*FD).Read(0xc000143400, 0xc000f50000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
        c:/go/src/internal/poll/fd_windows.go:527 +0x2fc
net.(*netFD).Read(0xc000143400, 0xc000f50000, 0x1000, 0x1000, 0xc000143400, 0x0, 0xc000143400)
        c:/go/src/net/fd_windows.go:152 +0x56
net.(*conn).Read(0xc001220020, 0xc000f50000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
        c:/go/src/net/net.go:184 +0x95
net/http.(*connReader).Read(0xc000e6a090, 0xc000f50000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
        c:/go/src/net/http/server.go:786 +0xfb
bufio.(*Reader).fill(0xc000e28000)
        c:/go/src/bufio/bufio.go:100 +0x10a
bufio.(*Reader).Peek(0xc000e28000, 0x4, 0x0, 0x0, 0x0, 0x0, 0x43b0f5)
        c:/go/src/bufio/bufio.go:138 +0x56
net/http.(*conn).readRequest(0xc0001f6140, 0x213d9e0, 0xc0003af1c0, 0x0, 0x0, 0x0)
        c:/go/src/net/http/server.go:963 +0xc7d
net/http.(*conn).serve(0xc0001f6140, 0x213d9e0, 0xc0003af1c0)
        c:/go/src/net/http/server.go:1822 +0x6db
created by net/http.(*Server).Serve
        c:/go/src/net/http/server.go:2933 +0x363

goroutine 398 [select]:
github.com/minio/minio/cmd.(*dataUpdateTracker).startCollector(0xc00068f0a0, 0x213d9e0, 0xc0003ae180)
        d:/minio/minio/cmd/data-update-tracker.go:439 +0xef
created by github.com/minio/minio/cmd.(*dataUpdateTracker).start
        d:/minio/minio/cmd/data-update-tracker.go:180 +0xaa

goroutine 4806 [select]:
net/http.(*persistConn).writeLoop(0xc0010030e0)
        c:/go/src/net/http/transport.go:2278 +0x123
created by net/http.(*Transport).dialConn
        c:/go/src/net/http/transport.go:1649 +0xc82

goroutine 395 [sleep, 2 minutes]:
time.Sleep(0x34630b8a000)
        c:/go/src/runtime/time.go:188 +0xc8
github.com/minio/minio/cmd.startBackgroundOps(0x213d9e0, 0xc0003ae180, 0x2181e00, 0xc000bfdce0)
        d:/minio/minio/cmd/server-main.go:375 +0xd5
created by github.com/minio/minio/cmd.serverMain
        d:/minio/minio/cmd/server-main.go:524 +0xa0c

goroutine 397 [select, 3 minutes]:
github.com/minio/minio/cmd.(*healSequence).healSequenceStart(0xc00137e780)
        d:/minio/minio/cmd/admin-heal-ops.go:604 +0x1b9
created by github.com/minio/minio/cmd.(*allHealState).LaunchNewHealSequence
        d:/minio/minio/cmd/admin-heal-ops.go:247 +0x58a

goroutine 4852 [select]:
net/http.(*persistConn).writeLoop(0xc0010837a0)
        c:/go/src/net/http/transport.go:2278 +0x123
created by net/http.(*Transport).dialConn
        c:/go/src/net/http/transport.go:1649 +0xc82

goroutine 396 [select]:
github.com/minio/minio/cmd.(*healRoutine).run(0xc001510c90, 0x213d9e0, 0xc0003ae180, 0x2181e00, 0xc000bfdce0)
        d:/minio/minio/cmd/background-heal-ops.go:79 +0x169
created by github.com/minio/minio/cmd.initBackgroundHealing
        d:/minio/minio/cmd/background-newdisks-heal-ops.go:116 +0xf9

goroutine 392 [chan receive]:
github.com/minio/minio/cmd.(*erasureSets).maintainMRFList(0xc001522160)
        d:/minio/minio/cmd/erasure-sets.go:1673 +0x113
created by github.com/minio/minio/cmd.newErasureSets
        d:/minio/minio/cmd/erasure-sets.go:373 +0xd4e

goroutine 4860 [select]:
net/http.(*persistConn).writeLoop(0xc000d018c0)
        c:/go/src/net/http/transport.go:2278 +0x123
created by net/http.(*Transport).dialConn
        c:/go/src/net/http/transport.go:1649 +0xc82

goroutine 5384 [chan receive]:
github.com/minio/minio/cmd.(*storageRESTServer).WalkVersionsHandler(0xc000006790, 0x2130be0, 0xc0007dca00, 0xc00280e000)
        d:/minio/minio/cmd/storage-rest-server.go:560 +0x3f3
net/http.HandlerFunc.ServeHTTP(...)
        c:/go/src/net/http/server.go:2012
github.com/minio/minio/cmd.httpTraceHdrs.func1(0x2130be0, 0xc0007dca00, 0xc00280e000)
        d:/minio/minio/cmd/handler-utils.go:362 +0x150
net/http.HandlerFunc.ServeHTTP(0xc00042fde0, 0x2130be0, 0xc0007dca00, 0xc00280e000)
        c:/go/src/net/http/server.go:2012 +0x4b
github.com/minio/minio/cmd.customHeaderHandler.ServeHTTP(0x21092c0, 0xc00042fde0, 0x2130ba0, 0xc001774ea0, 0xc00280e000)
        d:/minio/minio/cmd/generic-handlers.go:725 +0x169
github.com/minio/minio/cmd.securityHeaderHandler.ServeHTTP(0x21080a0, 0xc00176f490, 0x2130ba0, 0xc001774ea0, 0xc00280e000)
        d:/minio/minio/cmd/generic-handlers.go:740 +0x1dd
github.com/minio/minio/cmd.bucketForwardingHandler.ServeHTTP(0xc002804180, 0x2108200, 0xc00176f4a0, 0x2130ba0, 0xc001774ea0, 0xc00280e000)
        d:/minio/minio/cmd/generic-handlers.go:598 +0xd3
github.com/minio/minio/cmd.requestValidityHandler.ServeHTTP(0x2108000, 0xc001774e00, 0x2130ba0, 0xc001774ea0, 0xc00280e000)
        d:/minio/minio/cmd/generic-handlers.go:582 +0x428
github.com/minio/minio/cmd.httpStatsHandler.ServeHTTP(0x21081a0, 0xc00176f4d0, 0x2135520, 0xc0013bd960, 0xc00280e000)
        d:/minio/minio/cmd/generic-handlers.go:510 +0xeb
github.com/minio/minio/cmd.requestSizeLimitHandler.ServeHTTP(0x21080c0, 0xc00176f4e0, 0x50004000000, 0x2135520, 0xc0013bd960, 0xc00280e000)
        d:/minio/minio/cmd/generic-handlers.go:67 +0xd6
github.com/minio/minio/cmd.requestHeaderSizeLimitHandler.ServeHTTP(0x2108180, 0xc001774e20, 0x2135520, 0xc0013bd960, 0xc00280e000)
        d:/minio/minio/cmd/generic-handlers.go:92 +0x1ba
github.com/minio/minio/cmd.crossDomainPolicy.ServeHTTP(0x2108160, 0xc00176f4f0, 0x2135520, 0xc0013bd960, 0xc00280e000)
        d:/minio/minio/cmd/crossdomain-xml-handler.go:51 +0x88
github.com/minio/minio/cmd.redirectHandler.ServeHTTP(0x2108080, 0xc00176f500, 0x2135520, 0xc0013bd960, 0xc00280e000)
        d:/minio/minio/cmd/generic-handlers.go:250 +0x6f
github.com/minio/minio/cmd.minioReservedBucketHandler.ServeHTTP(0x2108140, 0xc00176f510, 0x2135520, 0xc0013bd960, 0xc00280e000)
        d:/minio/minio/cmd/generic-handlers.go:318 +0xb3
github.com/minio/minio/cmd.cacheControlHandler.ServeHTTP(0x2108100, 0xc00176f520, 0x2135520, 0xc0013bd960, 0xc00280e000)
        d:/minio/minio/cmd/generic-handlers.go:277 +0x86
github.com/minio/minio/cmd.timeValidityHandler.ServeHTTP(0x2108020, 0xc00176f530, 0x2135520, 0xc0013bd960, 0xc00280e000)
        d:/minio/minio/cmd/generic-handlers.go:388 +0x3bc
github.com/minio/minio/cmd.resourceHandler.ServeHTTP(0x2108240, 0xc00176f540, 0x2135520, 0xc0013bd960, 0xc00280e000)
        d:/minio/minio/cmd/generic-handlers.go:490 +0xac
github.com/minio/minio/cmd.authHandler.ServeHTTP(0x21081e0, 0xc00176f550, 0x2135520, 0xc0013bd960, 0xc00280e000)
        d:/minio/minio/cmd/auth-handler.go:471 +0x297
github.com/minio/minio/cmd.sseTLSHandler.ServeHTTP(0x2107fe0, 0xc00176f560, 0x2135520, 0xc0013bd960, 0xc00280e000)
        d:/minio/minio/cmd/generic-handlers.go:776 +0x2aa
github.com/minio/minio/cmd.reservedMetadataHandler.ServeHTTP(0x2108220, 0xc00176f570, 0x2135520, 0xc0013bd960, 0xc00280e000)
        d:/minio/minio/cmd/generic-handlers.go:138 +0x1ba
github.com/gorilla/mux.(*Router).ServeHTTP(0xc0008b0900, 0x2135520, 0xc0013bd960, 0xc001731e00)
        e:/gopath/pkg/mod/github.com/gorilla/mux@v1.8.0/mux.go:210 +0xe9
github.com/rs/cors.(*Cors).Handler.func1(0x2135520, 0xc0013bd960, 0xc001731e00)
        e:/gopath/pkg/mod/github.com/rs/cors@v1.7.0/cors.go:219 +0x1bf
net/http.HandlerFunc.ServeHTTP(0xc000edeac0, 0x2135520, 0xc0013bd960, 0xc001731e00)
        c:/go/src/net/http/server.go:2012 +0x4b
github.com/minio/minio/cmd.criticalErrorHandler.ServeHTTP(0x21092c0, 0xc000edeac0, 0x2135520, 0xc0013bd960, 0xc001731e00)
        d:/minio/minio/cmd/generic-handlers.go:758 +0x8c
github.com/minio/minio/cmd/http.(*Server).Start.func1(0x2135520, 0xc0013bd960, 0xc001731e00)
        d:/minio/minio/cmd/http/server.go:100 +0x25e
net/http.HandlerFunc.ServeHTTP(0xc0006a00a0, 0x2135520, 0xc0013bd960, 0xc001731e00)
        c:/go/src/net/http/server.go:2012 +0x4b
net/http.serverHandler.ServeHTTP(0xc000254c60, 0x2135520, 0xc0013bd960, 0xc001731e00)
        c:/go/src/net/http/server.go:2807 +0xaa
net/http.(*conn).serve(0xc0007dc8c0, 0x213d9e0, 0xc001c2e300)
        c:/go/src/net/http/server.go:1895 +0x873
created by net/http.(*Server).Serve
        c:/go/src/net/http/server.go:2933 +0x363

goroutine 4831 [IO wait]:
internal/poll.runtime_pollWait(0x2d174158, 0x72, 0x21097a0)
        c:/go/src/runtime/netpoll.go:203 +0x5c
internal/poll.(*pollDesc).wait(0xc000e7c1c8, 0x72, 0x2f69800, 0x0, 0x0)
        c:/go/src/internal/poll/fd_poll_runtime.go:87 +0x4c
internal/poll.(*ioSrv).ExecIO(0x353faa0, 0xc000e7c018, 0x1dc8ac0, 0x49f18d, 0x5f4cdf95, 0x207b8354f68b8)
        c:/go/src/internal/poll/fd_windows.go:228 +0x121
internal/poll.(*FD).Read(0xc000e7c000, 0xc00104a000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
        c:/go/src/internal/poll/fd_windows.go:527 +0x2fc
net.(*netFD).Read(0xc000e7c000, 0xc00104a000, 0x1000, 0x1000, 0xc000193e00, 0xc001399da8, 0xc001399c38)
        c:/go/src/net/fd_windows.go:152 +0x56
net.(*conn).Read(0xc000141ff0, 0xc00104a000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
        c:/go/src/net/net.go:184 +0x95
net/http.(*persistConn).Read(0xc000d6e5a0, 0xc00104a000, 0x1000, 0x1000, 0xc001399eb0, 0x467300, 0xc001399eb0)
        c:/go/src/net/http/transport.go:1826 +0x7c
bufio.(*Reader).fill(0xc001500240)
        c:/go/src/bufio/bufio.go:100 +0x10a
bufio.(*Reader).Peek(0xc001500240, 0x1, 0x2, 0x0, 0x0, 0xc000107600, 0x0)
        c:/go/src/bufio/bufio.go:138 +0x56
net/http.(*persistConn).readLoop(0xc000d6e5a0)
        c:/go/src/net/http/transport.go:1979 +0x1af
created by net/http.(*Transport).dialConn
        c:/go/src/net/http/transport.go:1648 +0xc5d

goroutine 393 [chan receive]:
github.com/minio/minio/cmd.(*erasureSets).healMRFRoutine(0xc001522160)
        d:/minio/minio/cmd/erasure-sets.go:1706 +0x276
created by github.com/minio/minio/cmd.newErasureSets
        d:/minio/minio/cmd/erasure-sets.go:374 +0xd73

goroutine 390 [select, 3 minutes]:
github.com/minio/minio/cmd.erasureObjects.cleanupStaleMultipartUploads(0xc000edfa00, 0xc000edfa20, 0xc000edfa40, 0xc000edf900, 0xc000edf920, 0xc001500a80, 0x213d9e0, 0xc0003ae180, 0x4e94914f0000, 0xebbdb3ed0000)
        d:/minio/minio/cmd/erasure-multipart.go:79 +0x139
created by github.com/minio/minio/cmd.newErasureSets
        d:/minio/minio/cmd/erasure-sets.go:367 +0xbf4

goroutine 425 [chan receive]:
github.com/minio/minio/cmd.(*erasureSets).maintainMRFList.func1(0xc00158ec60, 0xc001500a80, 0x0)
        d:/minio/minio/cmd/erasure-sets.go:1663 +0x6c
created by github.com/minio/minio/cmd.(*erasureSets).maintainMRFList
        d:/minio/minio/cmd/erasure-sets.go:1662 +0xaa

goroutine 4851 [IO wait]:
internal/poll.runtime_pollWait(0x2d1744d8, 0x72, 0x21097a0)
        c:/go/src/runtime/netpoll.go:203 +0x5c
internal/poll.(*pollDesc).wait(0xc000e5e448, 0x72, 0x2f69800, 0x0, 0x0)
        c:/go/src/internal/poll/fd_poll_runtime.go:87 +0x4c
internal/poll.(*ioSrv).ExecIO(0x353faa0, 0xc000e5e298, 0x1dc8ac0, 0x49f18d, 0x5f4cdf95, 0x207b835402de4)
        c:/go/src/internal/poll/fd_windows.go:228 +0x121
internal/poll.(*FD).Read(0xc000e5e280, 0xc000d38000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
        c:/go/src/internal/poll/fd_windows.go:527 +0x2fc
net.(*netFD).Read(0xc000e5e280, 0xc000d38000, 0x1000, 0x1000, 0xc0005c22a0, 0xc00022fda8, 0xc00022fc38)
        c:/go/src/net/fd_windows.go:152 +0x56
net.(*conn).Read(0xc0004ed390, 0xc000d38000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
        c:/go/src/net/net.go:184 +0x95
net/http.(*persistConn).Read(0xc0010837a0, 0xc000d38000, 0x1000, 0x1000, 0xc00022feb0, 0x467300, 0xc00022feb0)
        c:/go/src/net/http/transport.go:1826 +0x7c
bufio.(*Reader).fill(0xc001000f60)
        c:/go/src/bufio/bufio.go:100 +0x10a
bufio.(*Reader).Peek(0xc001000f60, 0x1, 0x2, 0x0, 0x0, 0xc004384500, 0x0)
        c:/go/src/bufio/bufio.go:138 +0x56
net/http.(*persistConn).readLoop(0xc0010837a0)
        c:/go/src/net/http/transport.go:1979 +0x1af
created by net/http.(*Transport).dialConn
        c:/go/src/net/http/transport.go:1648 +0xc5d

goroutine 426 [select]:
github.com/minio/minio/cmd.(*healSequence).healItemsFromSourceCh(0xc00137e780, 0x0, 0x469b31)
        d:/minio/minio/cmd/admin-heal-ops.go:711 +0x116
github.com/minio/minio/cmd.(*healSequence).healFromSourceCh(0xc00137e780)
        d:/minio/minio/cmd/admin-heal-ops.go:745 +0x32
created by github.com/minio/minio/cmd.(*healSequence).healSequenceStart
        d:/minio/minio/cmd/admin-heal-ops.go:601 +0x10a

goroutine 4805 [IO wait]:
internal/poll.runtime_pollWait(0x30110e08, 0x72, 0x21097a0)
        c:/go/src/runtime/netpoll.go:203 +0x5c
internal/poll.(*pollDesc).wait(0xc000b6fd48, 0x72, 0x2f69800, 0x0, 0x0)
        c:/go/src/internal/poll/fd_poll_runtime.go:87 +0x4c
internal/poll.(*ioSrv).ExecIO(0x353faa0, 0xc000b6fb98, 0x1dc8ac0, 0x49f18d, 0x5f4cdf95, 0x207b835402de4)
        c:/go/src/internal/poll/fd_windows.go:228 +0x121
internal/poll.(*FD).Read(0xc000b6fb80, 0xc000fb4000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
        c:/go/src/internal/poll/fd_windows.go:527 +0x2fc
net.(*netFD).Read(0xc000b6fb80, 0xc000fb4000, 0x1000, 0x1000, 0xc0005c22a0, 0xc0013abda8, 0xc0013abc38)
        c:/go/src/net/fd_windows.go:152 +0x56
net.(*conn).Read(0xc000141fc0, 0xc000fb4000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
        c:/go/src/net/net.go:184 +0x95
net/http.(*persistConn).Read(0xc0010030e0, 0xc000fb4000, 0x1000, 0x1000, 0xc0013abeb0, 0x467300, 0xc0013abeb0)
        c:/go/src/net/http/transport.go:1826 +0x7c
bufio.(*Reader).fill(0xc004232960)
        c:/go/src/bufio/bufio.go:100 +0x10a
bufio.(*Reader).Peek(0xc004232960, 0x1, 0x2, 0x0, 0x0, 0xc000107500, 0x0)
        c:/go/src/bufio/bufio.go:138 +0x56
net/http.(*persistConn).readLoop(0xc0010030e0)
        c:/go/src/net/http/transport.go:1979 +0x1af
created by net/http.(*Transport).dialConn
        c:/go/src/net/http/transport.go:1648 +0xc5d

goroutine 5386 [chan receive]:
github.com/minio/minio/cmd.(*xlStorage).WalkVersions.func2(0xc001221570, 0xc00011bee0, 0xc001c289f7, 0x8, 0xc001c28a19, 0x6, 0xc001c28a30, 0x0, 0x405301, 0xc0013f1e00, ...)
        d:/minio/minio/cmd/xl-storage.go:929 +0x210
created by github.com/minio/minio/cmd.(*xlStorage).WalkVersions
        d:/minio/minio/cmd/xl-storage.go:914 +0x497

goroutine 530 [select]:
github.com/minio/minio/cmd.monitorLocalDisksAndHeal(0x213d9e0, 0xc0003ae180, 0xc000bfdce0, 0x0, 0xc000de3b00, 0x1, 0x1, 0xc00137e780)
        d:/minio/minio/cmd/background-newdisks-heal-ops.go:127 +0x3e9
created by github.com/minio/minio/cmd.initAutoHeal
        d:/minio/minio/cmd/background-newdisks-heal-ops.go:70 +0x1ce

goroutine 4808 [IO wait]:
internal/poll.runtime_pollWait(0x30110a88, 0x72, 0x21097a0)
        c:/go/src/runtime/netpoll.go:203 +0x5c
internal/poll.(*pollDesc).wait(0xc000b395c8, 0x72, 0x2f69800, 0x0, 0x0)
        c:/go/src/internal/poll/fd_poll_runtime.go:87 +0x4c
internal/poll.(*ioSrv).ExecIO(0x353faa0, 0xc000b39418, 0x1dc8ac0, 0x49f18d, 0x5f4cdf95, 0x207b8354f68b8)
        c:/go/src/internal/poll/fd_windows.go:228 +0x121
internal/poll.(*FD).Read(0xc000b39400, 0xc000fb6000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
        c:/go/src/internal/poll/fd_windows.go:527 +0x2fc
net.(*netFD).Read(0xc000b39400, 0xc000fb6000, 0x1000, 0x1000, 0xc0005c22a0, 0xc001395da8, 0xc001395c38)
        c:/go/src/net/fd_windows.go:152 +0x56
net.(*conn).Read(0xc00181c930, 0xc000fb6000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
        c:/go/src/net/net.go:184 +0x95
net/http.(*persistConn).Read(0xc0010839e0, 0xc000fb6000, 0x1000, 0x1000, 0xc001395eb0, 0x467300, 0xc001395eb0)
        c:/go/src/net/http/transport.go:1826 +0x7c
bufio.(*Reader).fill(0xc004232a20)
        c:/go/src/bufio/bufio.go:100 +0x10a
bufio.(*Reader).Peek(0xc004232a20, 0x1, 0x2, 0x0, 0x0, 0xc000107900, 0x0)
        c:/go/src/bufio/bufio.go:138 +0x56
net/http.(*persistConn).readLoop(0xc0010839e0)
        c:/go/src/net/http/transport.go:1979 +0x1af
created by net/http.(*Transport).dialConn
        c:/go/src/net/http/transport.go:1648 +0xc5d

goroutine 1127 [chan receive, 3 minutes]:
github.com/minio/minio/cmd.(*NotificationSys).Init.func1(0xc00152a050)
        d:/minio/minio/cmd/notification.go:631 +0x7f
created by github.com/minio/minio/cmd.(*NotificationSys).Init
        d:/minio/minio/cmd/notification.go:630 +0x85

goroutine 1167 [select, 3 minutes]:
github.com/minio/minio/cmd.(*IAMObjectStore).watch(0xc001222b40, 0x213d9e0, 0xc0003ae180, 0xc001500ae0)
        d:/minio/minio/cmd/iam-object-store.go:625 +0x15b
created by github.com/minio/minio/cmd.(*IAMSys).Init
        d:/minio/minio/cmd/iam.go:512 +0x8f0

goroutine 1318 [IO wait]:
internal/poll.runtime_pollWait(0x30110b68, 0x72, 0x21097a0)
        c:/go/src/runtime/netpoll.go:203 +0x5c
internal/poll.(*pollDesc).wait(0xc0007141c8, 0x72, 0x2f69800, 0x0, 0x0)
        c:/go/src/internal/poll/fd_poll_runtime.go:87 +0x4c
internal/poll.(*ioSrv).ExecIO(0x353faa0, 0xc000714018, 0x1dc8ac0, 0x0, 0xc0007140f0, 0xc000714120)
        c:/go/src/internal/poll/fd_windows.go:228 +0x121
internal/poll.(*FD).Read(0xc000714000, 0xc001322000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
        c:/go/src/internal/poll/fd_windows.go:527 +0x2fc
net.(*netFD).Read(0xc000714000, 0xc001322000, 0x1000, 0x1000, 0xc000714000, 0x0, 0xc000714000)
        c:/go/src/net/fd_windows.go:152 +0x56
net.(*conn).Read(0xc0004ecf70, 0xc001322000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
        c:/go/src/net/net.go:184 +0x95
net/http.(*connReader).Read(0xc0012396b0, 0xc001322000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
        c:/go/src/net/http/server.go:786 +0xfb
bufio.(*Reader).fill(0xc00181a6c0)
        c:/go/src/bufio/bufio.go:100 +0x10a
bufio.(*Reader).Peek(0xc00181a6c0, 0x4, 0x0, 0x0, 0x0, 0x0, 0x43b0f5)
        c:/go/src/bufio/bufio.go:138 +0x56
net/http.(*conn).readRequest(0xc000836a00, 0x213d9e0, 0xc001b8e740, 0x0, 0x0, 0x0)
        c:/go/src/net/http/server.go:963 +0xc7d
net/http.(*conn).serve(0xc000836a00, 0x213d9e0, 0xc001b8e740)
        c:/go/src/net/http/server.go:1822 +0x6db
created by net/http.(*Server).Serve
        c:/go/src/net/http/server.go:2933 +0x363

goroutine 4859 [IO wait]:
internal/poll.runtime_pollWait(0x30110d28, 0x72, 0x21097a0)
        c:/go/src/runtime/netpoll.go:203 +0x5c
internal/poll.(*pollDesc).wait(0xc000e5e948, 0x72, 0x2f69800, 0x0, 0x0)
        c:/go/src/internal/poll/fd_poll_runtime.go:87 +0x4c
internal/poll.(*ioSrv).ExecIO(0x353faa0, 0xc000e5e798, 0x1dc8ac0, 0x49f18d, 0x5f4cdf95, 0x207b83530e690)
        c:/go/src/internal/poll/fd_windows.go:228 +0x121
internal/poll.(*FD).Read(0xc000e5e780, 0xc000d48000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
        c:/go/src/internal/poll/fd_windows.go:527 +0x2fc
net.(*netFD).Read(0xc000e5e780, 0xc000d48000, 0x1000, 0x1000, 0x43b1b3, 0xc002bc3b70, 0x466950)
        c:/go/src/net/fd_windows.go:152 +0x56
net.(*conn).Read(0xc0004ed3b8, 0xc000d48000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
        c:/go/src/net/net.go:184 +0x95
net/http.(*persistConn).Read(0xc000d018c0, 0xc000d48000, 0x1000, 0x1000, 0xc00124c900, 0xc002bc3c70, 0x405475)
        c:/go/src/net/http/transport.go:1826 +0x7c
bufio.(*Reader).fill(0xc001001620)
        c:/go/src/bufio/bufio.go:100 +0x10a
bufio.(*Reader).Peek(0xc001001620, 0x1, 0x0, 0x0, 0x1, 0xc00122fd00, 0x0)
        c:/go/src/bufio/bufio.go:138 +0x56
net/http.(*persistConn).readLoop(0xc000d018c0)
        c:/go/src/net/http/transport.go:1979 +0x1af
created by net/http.(*Transport).dialConn
        c:/go/src/net/http/transport.go:1648 +0xc5d

goroutine 5385 [IO wait]:
internal/poll.runtime_pollWait(0x2d1745b8, 0x72, 0x21097a0)
        c:/go/src/runtime/netpoll.go:203 +0x5c
internal/poll.(*pollDesc).wait(0xc001c8e448, 0x72, 0x2f69800, 0x0, 0x0)
        c:/go/src/internal/poll/fd_poll_runtime.go:87 +0x4c
internal/poll.(*ioSrv).ExecIO(0x353faa0, 0xc001c8e298, 0x1dc8ac0, 0x50, 0x50, 0x1bfebc0)
        c:/go/src/internal/poll/fd_windows.go:228 +0x121
internal/poll.(*FD).Read(0xc001c8e280, 0xc00176dfc1, 0x1, 0x1, 0x0, 0x0, 0x0)
        c:/go/src/internal/poll/fd_windows.go:527 +0x2fc
net.(*netFD).Read(0xc001c8e280, 0xc00176dfc1, 0x1, 0x1, 0xc001896c58, 0xc004225f68, 0x476703)
        c:/go/src/net/fd_windows.go:152 +0x56
net.(*conn).Read(0xc0002852d8, 0xc00176dfc1, 0x1, 0x1, 0x0, 0x0, 0x0)
        c:/go/src/net/net.go:184 +0x95
net/http.(*connReader).backgroundRead(0xc00176dfb0)
        c:/go/src/net/http/server.go:678 +0x5f
created by net/http.(*connReader).startBackgroundRead
        c:/go/src/net/http/server.go:674 +0xd7

goroutine 4832 [select]:
net/http.(*persistConn).writeLoop(0xc000d6e5a0)
        c:/go/src/net/http/transport.go:2278 +0x123
created by net/http.(*Transport).dialConn
        c:/go/src/net/http/transport.go:1649 +0xc82

goroutine 4809 [select]:
net/http.(*persistConn).writeLoop(0xc0010839e0)
        c:/go/src/net/http/transport.go:2278 +0x123
created by net/http.(*Transport).dialConn
        c:/go/src/net/http/transport.go:1649 +0xc82
rax     0x247000
rbx     0x63c
rcx     0x664
rdi     0x247000
rsi     0xc002809008
rbp     0xc002808fa8
rsp     0x2dadfd60
r8      0x0
r9      0x0
r10     0x2caf2a38
r11     0x30801326
r12     0x664
r13     0x0
r14     0xc002809070
r15     0x1
rip     0x7fff838db38d
rflags  0x10206
cs      0x33
fs      0x53
gs      0x2b

d:\minio\minio (master -> origin)
λ
```

</details>

## Steps to Reproduce (for bugs)

1. Start server in distrib mode
2. Delete a bucket on a disk
3. Wait for the bucket to be picked up by crawl
4.  All but the server that is missing the bucket data crash.

## Regression

Maybe

## Your Environment
* Version used (`minio --version`): master f04a1f220c6a9ffe80916029bdaffe1be45f06a6
* Server setup and configuration: `minio server --address :900X http://localhost:9001/data/mindev/data2/xl1 http://localhost:9002/data/mindev/data2/xl2 http://localhost:9003/data/mindev/data2/xl3 http://localhost:9004/data/mindev/data2/xl4`
* Operating System and version (`uname -a`): Win 10.

### PR DESCRIPTION
**Pull request by klauspost**
## Description

`syscall.FindNextFile` crashes if the handle is a file.

`errFileNotFound` matches 'unix' functionality: https://github.com/minio/minio/blob/d19b434ffceb005d0673c53bf28209559a536ed3/cmd/os-readdir_unix.go#L106

Fixes #10384

## How to test this PR?

See #10384

## Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)

### CODE REVIEW

**Comment by minio-trusted** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-s3.sh | :heavy_check_mark: |
| mint-erasure.sh | :heavy_check_mark: |
| mint-dist-erasure.sh | :heavy_check_mark: |
| mint-zoned.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-gateway-azure.sh | :x: [more...](#d01cd5bd-4abb-4bb0-9c8b-e47894cd4d9e) |
<a name="d01cd5bd-4abb-4bb0-9c8b-e47894cd4d9e"></a>
### 10385-0739687/mint-gateway-azure.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-dev6.minio.io:32369
ACCESS_KEY:           minioazure
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 017be39cbe9f:/mint/log /tmp/mint-logs'

(1/15) Running aws-sdk-go tests ... done in 8 seconds
(2/15) Running aws-sdk-java tests ... done in 1 seconds
(3/15) Running aws-sdk-php tests ... done in 6 minutes and 11 seconds
(4/15) Running aws-sdk-ruby tests ... done in 20 seconds
(5/15) Running awscli tests ... done in 2 minutes and 52 seconds
(6/15) Running healthcheck tests ... done in 1 seconds
(7/15) Running mc tests ... done in 3 minutes and 40 seconds
(8/15) Running minio-dotnet tests ... done in 1 minutes and 34 seconds
(9/15) Running minio-go tests ... FAILED in 1 minutes and 43 seconds
{
  "args": {
    "bucketName": "minio-go-test-vraywz32i4e2v036",
    "objectName": "test-object",
    "opts": "",
    "size": -1
  },
  "duration": 690,
  "function": "PutObject(bucketName, objectName, reader,size,opts)",
  "message": "Unexpected size",
  "name": "minio-go: testPutObjectStreaming",
  "status": "FAIL"
}
(9/15) Running minio-java tests ... done in 6 minutes and 6 seconds
(10/15) Running minio-js tests ... FAILED in 46 seconds
{
  "name": "minio-js",
  "function": "\"after all\" hook in \"functional tests\"",
  "duration": 79,
  "status": "FAIL",
  "error": "S3Error: The bucket you tried to delete is not empty at Object.parseError (node_modules/minio/dist/main/xml-parsers.js:86:11) at /mint/run/core/minio-js/node_modules/minio/dist/main/transformers.js:156:22 at DestroyableTransform._flush (node_modules/minio/dist/main/transformers.js:80:10) at DestroyableTransform.prefinish (node_modules/readable-stream/lib/_stream_transform.js:129:10) at prefinish (node_modules/readable-stream/lib/_stream_writable.js:611:14) at finishMaybe (node_modules/readable-stream/lib/_stream_writable.js:620:5) at endWritable (node_modules/readable-stream/lib/_stream_writable.js:643:3) at DestroyableTransform.Writable.end (node_modules/readable-stream/lib/_stream_writable.js:571:22) at IncomingMessage.onend (_stream_readable.js:678:10) at endReadableNT (_stream_readable.js:1244:12) at processTicksAndRejections (internal/process/task_queues.js:80:21)"
}
(10/15) Running minio-py tests ... done in 10 minutes and 21 seconds
(11/15) Running s3cmd tests ... done in 1 minutes and 29 seconds
(12/15) Running s3select tests ... done in 33 seconds
(13/15) Running security tests ... done in 0 seconds

Executed 13 out of 15 tests successfully.
```
Deleting image on docker hub
Deleting image locally
Error: No such image: minio/minio:10385-0739687

File: cmd/os-readdir_windows.go [hunk 1]
```diff
@@ -79,10 +80,19 @@ func readDirN(dirPath string, count int) (entries []string, err error) {
 	}
 	defer f.Close()
 
+	// Check if file or dir. This is the quickest way.
+	_, err = f.Seek(0, io.SeekStart)
+	if err == nil {
+		return nil, errFileNotFound
+	}
 	data := &syscall.Win32finddata{}
+	if count == 0 {
```
Comment (vadmeste) [inline cmd/os-readdir_windows.go]: This is probably redundant, we have `for count != 0 {` just few lines later.

**Review by vadmeste — COMMENTED** [review]
One comment, LGTM otherwise

**Review by harshavardhana — APPROVED** [review]

**Comment by klauspost** [comment]
@vadmeste

**Review by vadmeste — APPROVED** [review]
LGTM

**Comment by minio-trusted** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-s3.sh | :heavy_check_mark: |
| mint-dist-erasure.sh | :heavy_check_mark: |
| mint-zoned.sh | :heavy_check_mark: |
| mint-gateway-azure.sh | :x: [more...](#135b59f2-ae55-42aa-bbcb-9a209ff35b57) |
| mint-erasure.sh | :x: [more...](#78193faf-4d8e-4b84-a279-3163f11836c3) |
| mint-gateway-nas.sh | :x: [more...](#8ff816aa-e065-45c9-8dce-f52768d6eb5b) |
<a name="8ff816aa-e065-45c9-8dce-f52768d6eb5b"></a>
### 10385-b48f88f/mint-gateway-nas.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-dev7.minio.io:30198
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp ca56707092c8:/mint/log /tmp/mint-logs'

(1/15) Running aws-sdk-go tests ... done in 0 seconds
(2/15) Running aws-sdk-java tests ... done in 1 seconds
(3/15) Running aws-sdk-php tests ... done in 41 seconds
(4/15) Running aws-sdk-ruby tests ... done in 2 seconds
(5/15) Running awscli tests ... FAILED in 1 minutes and 52 seconds
{
  "name": "awscli",
  "duration": 62684,
  "function": "aws --endpoint-url http://minio-dev7.minio.io:30198 s3 sync --no-progress /mint/data s3://awscli-mint-test-bucket-23374/\n",
  "status": "FAIL",
  "error": "upload: ../../../data/datafile-0-b to s3://awscli-mint-test-bucket-23374/datafile-0-bupload: ../../../data/datafile-10-kB to s3://awscli-mint-test-bucket-23374/datafile-10-kBupload: ../../../data/datafile-1-b to s3://awscli-mint-test-bucket-23374/datafile-1-bupload: ../../../data/datafile-33-kB to s3://awscli-mint-test-bucket-23374/datafile-33-kBupload: ../../../data/datafile-100-kB to s3://awscli-mint-test-bucket-23374/datafile-100-kBupload: ../../../data/datafile-1.03-MB to s3://awscli-mint-test-bucket-23374/datafile-1.03-MBupload: ../../../data/datafile-1-MB to s3://awscli-mint-test-bucket-23374/datafile-1-MBupload: ../../../data/datafile-5-MB to s3://awscli-mint-test-bucket-23374/datafile-5-MBupload: ../../../data/datafile-5243880-b to s3://awscli-mint-test-bucket-23374/datafile-5243880-bupload: ../../../data/datafile-6-MB to s3://awscli-mint-test-bucket-23374/datafile-6-MBupload: ../../../data/datafile-10-MB to s3://awscli-mint-test-bucket-23374/datafile-10-MBupload: ../../../data/datafile-11-MB to s3://awscli-mint-test-bucket-23374/datafile-11-MBupload: ../../../data/datafile-65-MB to s3://awscli-mint-test-bucket-23374/datafile-65-MBupload: ../../../data/datafile-129-MB to s3://awscli-mint-test-bucket-23374/datafile-129-MBupload failed: ../../../data/datafile-1-kB to s3://awscli-mint-test-bucket-23374/datafile-1-kB An error occurred (NoSuchBucket) when calling the PutObject operation: The specified bucket does not exist"
}
(5/15) Running healthcheck tests ... done in 0 seconds
(6/15) Running mc tests ... done in 18 seconds
(7/15) Running minio-dotnet tests ... done in 29 seconds
(8/15) Running minio-go tests ... done in 54 seconds
(9/15) Running minio-java tests ... done in 12 seconds
(10/15) Running minio-js tests ... done in 36 seconds
(11/15) Running minio-py tests ... done in 1 minutes and 6 seconds
(12/15) Running s3cmd tests ... done in 17 seconds
(13/15) Running s3select tests ... done in 2 seconds
(14/15) Running security tests ... done in 0 seconds

Executed 14 out of 15 tests successfully.
```
<a name="78193faf-4d8e-4b84-a279-3163f11836c3"></a>
### 10385-b48f88f/mint-erasure.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-dev4.minio.io:31667
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 86b9e6fe0be3:/mint/log /tmp/mint-logs'

(1/15) Running aws-sdk-go tests ... done in 0 seconds
(2/15) Running aws-sdk-java tests ... done in 2 seconds
(3/15) Running aws-sdk-php tests ... done in 42 seconds
(4/15) Running aws-sdk-ruby tests ... done in 2 seconds
(5/15) Running awscli tests ... done in 1 minutes and 14 seconds
(6/15) Running healthcheck tests ... done in 0 seconds
(7/15) Running mc tests ... FAILED in 16 minutes and 0 seconds
{
  "name": "mc",
  "duration": "949408",
  "function": "test_mirror_list_objects_storage_class",
  "status": "FAIL",
  "error": "mirror and list differs"
}
(7/15) Running minio-dotnet tests ... done in 35 seconds
(8/15) Running minio-go tests ... done in 53 seconds
(9/15) Running minio-java tests ... done in 41 seconds
(10/15) Running minio-js tests ... done in 45 seconds
(11/15) Running minio-py tests ... done in 2 minutes and 2 seconds
(12/15) Running s3cmd tests ... done in 18 seconds
(13/15) Running s3select tests ... done in 3 seconds
(14/15) Running security tests ... done in 0 seconds

Executed 14 out of 15 tests successfully.
```
<a name="135b59f2-ae55-42aa-bbcb-9a209ff35b57"></a>
### 10385-b48f88f/mint-gateway-azure.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-c3.minio.io:31407
ACCESS_KEY:           minioazure
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp e3cdfd436c1c:/mint/log /tmp/mint-logs'

(1/15) Running aws-sdk-go tests ... done in 7 seconds
(2/15) Running aws-sdk-java tests ... done in 1 seconds
(3/15) Running aws-sdk-php tests ... done in 6 minutes and 22 seconds
(4/15) Running aws-sdk-ruby tests ... done in 17 seconds
(5/15) Running awscli tests ... done in 2 minutes and 39 seconds
(6/15) Running healthcheck tests ... done in 0 seconds
(7/15) Running mc tests ... done in 3 minutes and 9 seconds
(8/15) Running minio-dotnet tests ... done in 1 minutes and 34 seconds
(9/15) Running minio-go tests ... done in 6 minutes and 23 seconds
(10/15) Running minio-java tests ... done in 6 minutes and 5 seconds
(11/15) Running minio-js tests ... FAILED in 45 seconds
{
  "name": "minio-js",
  "function": "makeBucket(bucketName, region)",
  "args": "bucketName:minio-js-test-accd0383-1bb2-4f49-be68-e39108148e9f-region, region:us-east-1",
  "duration": 40307,
  "status": "FAIL",
  "error": "S3Error: The specified bucket does not exist at Object.parseError (node_modules/minio/dist/main/xml-parsers.js:86:11) at /mint/run/core/minio-js/node_modules/minio/dist/main/transformers.js:156:22 at DestroyableTransform._flush (node_modules/minio/dist/main/transformers.js:80:10) at DestroyableTransform.prefinish (node_modules/readable-stream/lib/_stream_transform.js:129:10) at prefinish (node_modules/readable-stream/lib/_stream_writable.js:611:14) at finishMaybe (node_modules/readable-stream/lib/_stream_writable.js:620:5) at endWritable (node_modules/readable-stream/lib/_stream_writable.js:643:3) at DestroyableTransform.Writable.end (node_modules/readable-stream/lib/_stream_writable.js:571:22) at IncomingMessage.onend (_stream_readable.js:678:10) at endReadableNT (_stream_readable.js:1244:12) at processTicksAndRejections (internal/process/task_queues.js:80:21)"
}
(11/15) Running minio-py tests ... done in 9 minutes and 56 seconds
(12/15) Running s3cmd tests ... done in 1 minutes and 21 seconds
(13/15) Running s3select tests ... done in 48 seconds
(14/15) Running security tests ... done in 0 seconds

Executed 14 out of 15 tests successfully.
```
Deleting image on docker hub
Deleting image locally
Error: No such image: minio/minio:10385-b48f88f
