### PR TITLE
Accept multipart checksums with part count

### LINKED ISSUE #19670: feat: Completing Multipart Uploads with Checksum That Contains Number of Parts Fails
## Expected Behavior
When completing multipart upload checksum in format `{checksum}-{numberOfParts}` should be supported.

## Current Behavior
When completing multipart upload checksum in format `{checksum}-{numberOfParts}`, `InvalidArgument: Invalid arguments provided for checksum-bug/minio-checksum-bug/2024-05-04T17:52:34.793Z.mp4: (invalid/unknown checksum sent: invalid checksum)` error is returned.

Various scenarios:
1. both s3 and minio allow completing without checksum 
2. both s3 and minio fail on invalid checkum
3. both s3 and minio allow completing with checksum that does not contain number of parts, eg. `ejt070PMd2pF/mFNTgP6LDtAo2px3L+i/l91VTgvRSc=`.
4. **only s3 allows completing when checkusm with number of parts as a suffix is provided, eg. `ejt070PMd2pF/mFNTgP6LDtAo2px3L+i/l91VTgvRSc=-2`.**

## Possible Solution
Fix somewhere in [erasure-multipart.go](https://github.com/minio/minio/blob/8ff70ea5a9210b545e3c95acb23b5a983b64da9c/cmd/erasure-multipart.go).

## Steps to Reproduce (for bugs)

1. Create multipart upload with `ChecksumAlgorithm: "SHA256"` (likely all other algorithms are also impacted)
5. Upload parts with checksum
6. Complete multipart upload with checksum combined with number of parts

<details>
<summary>Sample code (JS)</summary>

```javascript

// tested with node@20.12.2, minio version RELEASE.2024-05-01T01-11-10Z
// save as .mjs file
// set flowing env variables before starting or here:
// process.env.S3_BUCKET_NAME = "";
// process.env.AWS_REGION = ""; // only for s3
// process.env.AWS_ACCESS_KEY_ID = "";
// process.env.AWS_SECRET_ACCESS_KEY = "";
// process.env.AWS_ENDPOINT_URL = ""; // only for minio

import {
  CompleteMultipartUploadCommand,
  CreateMultipartUploadCommand,
  ListPartsCommand,
  S3Client,
  UploadPartCommand,
} from "@aws-sdk/client-s3"; // tested with version 3.569.0
import crypto from "node:crypto";

function getChecksum(buffer) {
  const hash = crypto.createHash("sha256");
  hash.update(new Uint8Array(buffer));
  return hash.digest();
}

const video = await fetch(
  "https://github.com/minio/minio/assets/610941/2653d680-2c87-42ea-98d0-8feab199d3ef"
).then((response) => response.arrayBuffer());

const s3 = new S3Client({
  forcePathStyle: !!process.env.AWS_ENDPOINT_URL,
});

const MB_5 = 5 * 1024 * 1024;
const KEY = `minio-checksum-bug/${new Date().toISOString()}.mp4`;
const PARTS = Math.ceil(video.byteLength / MB_5);

console.log({ KEY, PARTS });

const multipartUpload = await s3.send(
  new CreateMultipartUploadCommand({
    Bucket: process.env.S3_BUCKET_NAME,
    Key: KEY,
    ChecksumAlgorithm: "SHA256",
  })
);

const uploadId = multipartUpload.UploadId;

const checksums = [];

for (let i = 0; i < PARTS; i++) {
  const start = i * MB_5;
  const end = Math.min((i + 1) * MB_5, video.byteLength);
  const body = video.slice(start, end);
  const checksum = getChecksum(body);
  const checksumBase64 = checksum.toString("base64");
  checksums.push(checksum);
  console.log({ i, checksumBase64 });

  await s3.send(
    new UploadPartCommand({
      Bucket: process.env.S3_BUCKET_NAME,
      Key: KEY,
      UploadId: uploadId,
      PartNumber: i + 1,
      Body: body,
      ChecksumSHA256: checksum.toString("base64"),
    })
  );
}

const partsList = await s3.send(
  new ListPartsCommand({
    Bucket: process.env.S3_BUCKET_NAME,
    Key: KEY,
    UploadId: uploadId,
  })
);

const checksumTotal = getChecksum(Buffer.concat(checksums));
const checksumTotalBase64 = checksumTotal.toString("base64");
console.log({ checksumTotalBase64 });

await s3.send(
  new CompleteMultipartUploadCommand({
    Bucket: process.env.S3_BUCKET_NAME,
    Key: KEY,
    UploadId: uploadId,
    MultipartUpload: {
      Parts: partsList.Parts.map((part) => ({
        PartNumber: part.PartNumber,
        ETag: part.ETag,
        ChecksumSHA256: part.ChecksumSHA256,
      })),
    },
    ChecksumSHA256: "a" + checksumTotalBase64, // GOOD does not work in both s3 and minio
    ChecksumSHA256: checksumTotalBase64, // GOOD works in both s3 and minio
    ChecksumSHA256: `${checksumTotalBase64}-${PARTS}`, // BAD works in s3, does not work in minio
  })
);
```
</details>

<details>
<summary>Test file storage</summary>

https://github.com/minio/minio/assets/610941/2653d680-2c87-42ea-98d0-8feab199d3ef

</details>

## Context
Not a big deal for us at this point, we can remove part numbers from the checksum, but reporting this as a it is compatibility issue.

## Regression
Probably not.

## Your Environment
Testing locally on Windows WSL, not really relevant for this issue.
```
minio version RELEASE.2024-05-01T01-11-10Z (commit-id=7926401cbd5cceaacd9509f2e50e1f7d636c2eb8)
Runtime: go1.21.9 linux/amd64
License: GNU AGPLv3 <https://www.gnu.org/licenses/agpl-3.0.html>
Copyright: 2015-2024 MinIO, Inc.
```
```
Linux KUBA-PC 5.15.146.1-microsoft-standard-WSL2 #1 SMP Thu Jan 11 04:09:03 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux
```

### PR DESCRIPTION
**Pull request by klauspost**
## Description

Accept multipart uploads where the combined checksum provides expected part count.

Seems this was added by AWS to make the API more consistent even if the data is completely superfluous on multiple levels.

Fixes #19670

## Motivation and Context

Improve AWS S3 compatibility.

## How to test this PR?

See #19670

## Types of changes
- [x] New feature (non-breaking change which adds functionality)

### CODE REVIEW

**Review by harshavardhana — APPROVED** [review]

File: internal/hash/checksum.go [hunk 1]
```diff
@@ -325,12 +342,15 @@ func (c *Checksum) AppendTo(b []byte, parts []byte) []byte {
 	b = append(b, crc...)
 	if c.Type.Is(ChecksumMultipart) {
 		var checksums int
+		if c.WantParts > 0 && !c.Type.Is(ChecksumIncludesMultipart) {
```
Comment (vadmeste) [inline internal/hash/checksum.go:345]: it seems from the code that c.WantParts is always zero when AppendTo is called from erasure-multipart.go, not sure if I am missing something

Comment (klauspost) [reply internal/hash/checksum.go:345]: @vadmeste You are right. `WantParts` is only used transiently now (comes from request, validated against actual) and not stored. 

I just didn't want this to be "hanging" in case that was changed some day, so there is a way for it to be serialized in case we at some point need to send it in and RPC call or similar.

**Comment by klauspost** [comment]
~(draft while checking out some unexpected test results)~

Functionality verified by running mint with <details>
  <summary>this diff (click)</summary>

```
 api-put-object-multipart.go | 3 ++-
 1 file changed, 2 insertions(+), 1 deletion(-)

diff --git a/api-put-object-multipart.go b/api-put-object-multipart.go
index 5f117af..b913f7b 100644
--- a/api-put-object-multipart.go
+++ b/api-put-object-multipart.go
@@ -207,7 +207,8 @@ func (c *Client) putObjectMultipartNoStream(ctx context.Context, bucketName, obj
 		// Add hash of hashes.
 		crc.Reset()
 		crc.Write(crcBytes)
-		opts.UserMetadata = map[string]string{"X-Amz-Checksum-Crc32c": base64.StdEncoding.EncodeToString(crc.Sum(nil))}
+		hash := fmt.Sprintf("%s-%d", base64.StdEncoding.EncodeToString(crc.Sum(nil)), len(complMultipartUpload.Parts))
+		opts.UserMetadata = map[string]string{"X-Amz-Checksum-Crc32c": hash}
 	}
 	uploadInfo, err := c.completeMultipartUpload(ctx, bucketName, objectName, uploadID, complMultipartUpload, opts)
 	if err != nil {
 api-put-object-streaming.go | 9 ++++++---
 1 file changed, 6 insertions(+), 3 deletions(-)

diff --git a/api-put-object-streaming.go b/api-put-object-streaming.go
index 9182d4e..8f87df1 100644
--- a/api-put-object-streaming.go
+++ b/api-put-object-streaming.go
@@ -281,7 +281,8 @@ func (c *Client) putObjectMultipartStreamFromReadAt(ctx context.Context, bucketN
 				crc.Write(cs)
 			}
 		}
-		opts.UserMetadata = map[string]string{"X-Amz-Checksum-Crc32c": base64.StdEncoding.EncodeToString(crc.Sum(nil))}
+		hash := fmt.Sprintf("%s-%d", base64.StdEncoding.EncodeToString(crc.Sum(nil)), len(complMultipartUpload.Parts))
+		opts.UserMetadata = map[string]string{"X-Amz-Checksum-Crc32c": hash}
 	}
 
 	uploadInfo, err := c.completeMultipartUpload(ctx, bucketName, objectName, uploadID, complMultipartUpload, opts)
@@ -438,7 +439,8 @@ func (c *Client) putObjectMultipartStreamOptionalChecksum(ctx context.Context, b
 		// Add hash of hashes.
 		crc.Reset()
 		crc.Write(crcBytes)
-		opts.UserMetadata = map[string]string{"X-Amz-Checksum-Crc32c": base64.StdEncoding.EncodeToString(crc.Sum(nil))}
+		hash := fmt.Sprintf("%s-%d", base64.StdEncoding.EncodeToString(crc.Sum(nil)), len(complMultipartUpload.Parts))
+		opts.UserMetadata = map[string]string{"X-Amz-Checksum-Crc32c": hash}
 	}
 	uploadInfo, err := c.completeMultipartUpload(ctx, bucketName, objectName, uploadID, complMultipartUpload, opts)
 	if err != nil {
@@ -642,7 +644,8 @@ func (c *Client) putObjectMultipartStreamParallel(ctx context.Context, bucketNam
 		// Add hash of hashes.
 		crc.Reset()
 		crc.Write(crcBytes)
-		opts.UserMetadata = map[string]string{"X-Amz-Checksum-Crc32c": base64.StdEncoding.EncodeToString(crc.Sum(nil))}
+		hash := fmt.Sprintf("%s-%d", base64.StdEncoding.EncodeToString(crc.Sum(nil)), len(complMultipartUpload.Parts))
+		opts.UserMetadata = map[string]string{"X-Amz-Checksum-Crc32c": hash}
 	}
 	uploadInfo, err := c.completeMultipartUpload(ctx, bucketName, objectName, uploadID, complMultipartUpload, opts)
 	if err != nil {
 api-put-object.go | 3 ++-
 1 file changed, 2 insertions(+), 1 deletion(-)

diff --git a/api-put-object.go b/api-put-object.go
index 4dec604..ecc4201 100644
--- a/api-put-object.go
+++ b/api-put-object.go
@@ -461,7 +461,8 @@ func (c *Client) putObjectMultipartStreamNoLength(ctx context.Context, bucketNam
 		// Add hash of hashes.
 		crc.Reset()
 		crc.Write(crcBytes)
-		opts.UserMetadata = map[string]string{"X-Amz-Checksum-Crc32c": base64.StdEncoding.EncodeToString(crc.Sum(nil))}
+		hash := fmt.Sprintf("%s-%d", base64.StdEncoding.EncodeToString(crc.Sum(nil)), len(complMultipartUpload.Parts))
+		opts.UserMetadata = map[string]string{"X-Amz-Checksum-Crc32c": hash}
 	}
 	uploadInfo, err := c.completeMultipartUpload(ctx, bucketName, objectName, uploadID, complMultipartUpload, opts)
 	if err != nil {
 functional_tests.go | 2 +-
 1 file changed, 1 insertion(+), 1 deletion(-)
```
</details>

I will not change minio-go, since that would just break backcompat.

**Comment by harshavardhana** [comment]
> I will not change minio-go, since that would just break backcompat.

like? @klauspost

**Comment by klauspost** [comment]
@harshavardhana It would break checksums on older minio. AWS supports both.

**Comment by harshavardhana** [comment]
> @harshavardhana It would break checksums on older minio. AWS supports both.

wait are you saying that this PR will break clients?

**Comment by klauspost** [comment]
@harshavardhana No. This is not minio-go. This is the server. IF we changed minio-go, then it would break on older minio server versions.

**Comment by harshavardhana** [comment]
> @harshavardhana No. This is not minio-go. This is the server. IF we changed minio-go, then it would break on older minio server versions.

Oh I see so it is an option right?

**Comment by klauspost** [comment]
@harshavardhana Correct. And the server supports both variants  `xxxxxx` (original S3 implementation) and `xxxxx-2` (modified) - as it seems AWS does.

**Review by harshavardhana — APPROVED** [review]
