### PR TITLE
[PostgreSQL] Parse IPv6 hosts for postgres connections

### LINKED ISSUE #7145: Minio config cannot parse IPv6 address for PostgreSQL
As the title says, minio config cannot handle IPv6 addresses in the config file. I was following the instructions on [Minio Bucket Notification Guide](https://docs.minio.io/docs/minio-bucket-notification-guide.html) for enabling events in PostgreSQL.

I extracted the current config with `mc admin config get`, modified the relevant section for `postgresql` and tried to upload it but it was not accepted. If I set the `host` key as a pure IPv6 address (e.g. `fd12:3456:7890::1234`), the error is:

    mc: <ERROR> Cannot set server configuration file. scheme appears with empty host

And if I set it similar to how http handles it (e.g. `[fd12:3456:7890::1234]`), the error is:

    mc: <ERROR> Cannot set server configuration file. parse [fd12:3456:7890::1234]: first path segment in URL cannot contain colon

## Expected Behavior
I expected a pure IPv6 address to work as-is.

## Current Behavior
Neither IPv6 format is parsed correctly.

## Possible Solution
The error is somewhere in the URL parsing library. It should be improved to correctly handle IPv6 addresses in all situations. I think it does work fine for a regular http address, such as http://[fd12:3456::78]:9000/ but not for a lone IPv6 address. Or it should not even be parsed as a URL in the first place, since it can only be either a hostname, or an IP address, be that v4 or v6.

## Steps to Reproduce (for bugs)

1. Extract config with `mc admin config get somekey > myconfig.json`
2. Modify `postgresql` config and set host to an IPv6 address
3. Try uploading new config with `mc admin config set somekey < myconfig.json`
4. Fail!

## Context
As it it, I cannot use IPv6 addresses for host definition.

## Your Environment

* Version used (`minio version`):

    Version: 2019-01-23T23:18:58Z
    Release-Tag: RELEASE.2019-01-23T23-18-58Z
    Commit-ID: bd25f31100f44646cffae99dfec23179366593e2

* Operating System and version (`uname -a`):

    Linux my-host-name 4.4.0-141-generic #167-Ubuntu SMP Wed Dec 5 10:40:15 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

* Network: is entirely IPv6 only

### PR DESCRIPTION
**Pull request by Praveenrajmani**
## Description
Successfully parse the IPv6 hosts specified in the config

## Motivation and Context
The current json unmarshaller does not parse IPv6 hosts. It was pointing to `xnet.URL` which has to be `xnet.Host` since it parses the host and not the url.
Fixes #7145

## Regression
Maybe

## How Has This Been Tested?

Step 1 - Run postgres on IPv6  by adding `listen_addresses = '::'` in `postgresql.conf` and 
             `host    all        all             <IPv6_host>%wlp2s0/128         trust` in `pg_hba.conf`
Step 2 -  Set the host in the config as `"host": "[<IPv6_host>%wlp2s0]"`
Step 3 - Try setting the config by `mc config set`

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I have added unit tests to cover my changes.
- [ ] I have added/updated functional tests in [mint](https://github.com/minio/mint). (If yes, add `mint` PR # here: )
- [x] All new and existing tests passed.

### CODE REVIEW

File: pkg/event/target/postgresql.go [hunk 1]
```diff
@@ -80,15 +80,15 @@ const (
...
-	Port             string   `json:"port"`     // default: 5432
-	User             string   `json:"user"`     // default: user running minio
-	Password         string   `json:"password"` // default: no password
-	Database         string   `json:"database"` // default: same as user
+	Enable           bool      `json:"enable"`
+	Format           string    `json:"format"`
+	ConnectionString string    `json:"connectionString"`
+	Table            string    `json:"table"`
+	Host             xnet.Host `json:"host"`     // default: localhost
+	Port             string    `json:"port"`     // default: 5432
```
Comment (harshavardhana) [inline pkg/event/target/postgresql.go:88]: This can also be `xnet.Port`

**Comment by minio-ops** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-tls.sh | :heavy_check_mark: |
| mint-compression-xl.sh | :heavy_check_mark: |
| mint-xl.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-compression-fs.sh | :heavy_check_mark: |
| mint-worm.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-dist-xl.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :x: [more...](#c437eb71-446f-449a-a949-dbc631a38d8a) |
<a name="c437eb71-446f-449a-a949-dbc631a38d8a"></a>
### 7168-8568752/mint-large-bucket.sh.log:
```
Running with
SERVER_ENDPOINT:      minikube:30718
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 7ff1727daa3a:/mint/log /tmp/mint-logs'

(1/13) Running awscli tests ... done in 2 minutes and 35 seconds
(2/13) Running aws-sdk-go tests ... done in 2 seconds
(3/13) Running aws-sdk-java tests ... done in 4 seconds
(4/13) Running aws-sdk-php tests ... done in 1 minutes and 3 seconds
(5/13) Running aws-sdk-ruby tests ... done in 39 seconds
(6/13) Running mc tests ... done in 1 minutes and 54 seconds
(7/13) Running minio-dotnet tests ... FAILED in 4 minutes and 55 seconds

Unhandled Exception: System.AggregateException: One or more errors occurred. (One or more errors occurred. (Minio API responded with message=Multiple disks failures, unable to write data.) (Minio API responded with message=Multiple disks failures, unable to write data.) (Minio API responded with message=Multiple disks failures, unable to write data.) (Minio API responded with message=Multiple disks failures, unable to write data.) (Minio API responded with message=Multiple disks failures, unable to write data.) (Minio API responded with message=Multiple disks failures, unable to write data.) (Minio API responded with message=Multiple disks failures, unable to write data.)) ---> System.AggregateException: One or more errors occurred. (Minio API responded with message=Multiple disks failures, unable to write data.) (Minio API responded with message=Multiple disks failures, unable to write data.) (Minio API responded with message=Multiple disks failures, unable to write data.) (Minio API responded with message=Multiple disks failures, unable to write data.) (Minio API responded with message=Multiple disks failures, unable to write data.) (Minio API responded with message=Multiple disks failures, unable to write data.) (Minio API responded with message=Multiple disks failures, unable to write data.) ---> Minio.Exceptions.MinioException: Minio API responded with message=Multiple disks failures, unable to write data.
   at Minio.MinioClient.ParseError(IRestResponse response) in /q/.q/sources/minio-dotnet/Minio/MinioClient.cs:line 371
   at Minio.MinioClient.HandleIfErrorResponse(IRestResponse response, IEnumerable`1 handlers, DateTime startTime) in /q/.q/sources/minio-dotnet/Minio/MinioClient.cs:line 513
   at Minio.MinioClient.ExecuteTaskAsync(IEnumerable`1 errorHandlers, IRestRequest request, CancellationToken cancellationToken) in /q/.q/sources/minio-dotnet/Minio/MinioClient.cs:line 359
   at Minio.MinioClient.PutObjectAsync(String bucketName, String objectName, String uploadId, Int32 partNumber, Byte[] data, Dictionary`2 metaData, Dictionary`2 sseHeaders, CancellationToken cancellationToken) in /q/.q/sources/minio-dotnet/Minio/ApiEndpoints/ObjectOperations.cs:line 492
   at Minio.MinioClient.PutObjectAsync(String bucketName, String objectName, Stream data, Int64 size, String contentType, Dictionary`2 metaData, ServerSideEncryption sse, CancellationToken cancellationToken) in /q/.q/sources/minio-dotnet/Minio/ApiEndpoints/ObjectOperations.cs:line 254
   at Minio.Functional.Tests.FunctionalTest.PutObject_Task(MinioClient minio, String bucketName, String objectName, String fileName, String contentType, Int64 size, Dictionary`2 metaData, MemoryStream mstream) in /mint/run/core/minio-dotnet/FunctionalTest.cs:line 923
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.Wait()
   at Minio.Functional.Tests.FunctionalTest.RemoveObjects_Test2(MinioClient minio) in /mint/run/core/minio-dotnet/FunctionalTest.cs:line 2134
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.Wait()
   at Minio.Functional.Tests.FunctionalTest.Main(String[] args) in /mint/run/core/minio-dotnet/FunctionalTest.cs:line 221

Executed 6 out of 13 tests successfully.
```

File: pkg/net/host.go [hunk 2]
```diff
@@ -118,8 +118,7 @@ func ParseHost(s string) (*Host, error) {
 		if !strings.Contains(err.Error(), "missing port in address") {
 			return nil, err
 		}
-
-		host = s
+		host = normalizeHost(s)
```
Comment (balamurugana) [inline pkg/net/host.go]: You could do one liner `normalizeHost()` logic here.

File: pkg/net/host.go [hunk 3]
```diff
@@ -129,7 +128,12 @@ func ParseHost(s string) (*Host, error) {
 		isPortSet = true
 	}
 
+	// IPv6 requires a link-local address on every network interface.
+	// `%interface` should be preserved.
+	nHost := host
+
 	if i := strings.Index(host, "%"); i > -1 {
+		// `%interface` can be skipped for validity check though.
```
Comment (balamurugana) [inline pkg/net/host.go:143]: You are not using `host` below, hence you wouldn't need `nHost`

Comment (Praveenrajmani) [reply pkg/net/host.go:143]: done. modified

Comment (Praveenrajmani) [reply pkg/net/host.go:143]: done. modified this as discussed

File: pkg/event/target/postgresql.go (hunk 1 above)
Comment (Praveenrajmani) [reply pkg/event/target/postgresql.go:88]: yes done

**Comment by minio-ops** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-tls.sh | :x: [more...](#753b17c0-4263-4e1a-95f1-accd9edadc21) |
| mint-compression-xl.sh | :x: [more...](#0ec87472-e088-4547-a4e5-b8027a21dad1) |
| mint-xl.sh | :x: [more...](#51991555-6ce7-45cd-8124-5dc4a4333a06) |
| mint-large-bucket.sh | :x: [more...](#a97c4f01-22e1-445e-8275-583e00f1d733) |
| mint-compression-fs.sh | :x: [more...](#49ab0866-50d9-4bfe-9e39-c6c55c54d33b) |
| mint-worm.sh | :x: [more...](#bf730e33-30b9-4b77-afe8-4c0ff525fb37) |
| mint-fs.sh | :x: [more...](#4e113d8f-cc39-4dbf-acae-224e13595c7f) |
| mint-dist-xl.sh | :x: [more...](#49bae859-7adb-4f15-81b4-728e2f299f4b) |
<a name="a97c4f01-22e1-445e-8275-583e00f1d733"></a>
### 7168-bfe8005/mint-large-bucket.sh.log:
```
Running with
SERVER_ENDPOINT:      minikube:31702
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 0e12b69a17e2:/mint/log /tmp/mint-logs'

(1/13) Running awscli tests ... FAILED in 14 seconds
{
  "name": "awscli",
  "duration": 12592,
  "function": "make_bucket\n",
  "status": "FAIL",
  "error": "('Connection aborted.', ConnectionRefusedError(111, 'Connection refused'))"
}

Executed 0 out of 13 tests successfully.
```
<a name="bf730e33-30b9-4b77-afe8-4c0ff525fb37"></a>
### 7168-bfe8005/mint-worm.sh.log:
```
Running with
SERVER_ENDPOINT:      minikube:30199
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            worm
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp bca23227ef8b:/mint/log /tmp/mint-logs'

(1/1) Running worm tests ... FAILED in 4 seconds
{
  "alert": "",
  "args": {
    "bucketName": "bucket-bqpx4zwd4649z51mdm1cmjdjwoihcfrqq40gdb6lsjaecyqmjeavf0o",
    "expiry": 60000000000,
    "objectName": "testObject"
  },
  "duration": 4450,
  "error": "RequestError: send request failed\ncaused by: Put http://minikube:30199/bucket-bqpx4zwd4649z51mdm1cmjdjwoihcfrqq40gdb6lsjaecyqmjeavf0o: dial tcp 192.168.122.88:30199: connect: connection refused",
  "function": "PutAndDelete",
  "message": "WORM_MODE ON  - CreateBucket Failed",
  "name": "test worm mode",
  "status": "FAIL"
}

Executed 0 out of 1 tests successfully.
```
<a name="51991555-6ce7-45cd-8124-5dc4a4333a06"></a>
### 7168-bfe8005/mint-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      minikube:31683
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 9dd8c8221f51:/mint/log /tmp/mint-logs'

(1/13) Running awscli tests ... FAILED in 23 seconds
{
  "name": "awscli",
  "duration": 17530,
  "function": "make_bucket\n",
  "status": "FAIL",
  "error": "('Connection aborted.', ConnectionRefusedError(111, 'Connection refused'))"
}

Executed 0 out of 13 tests successfully.
```
<a name="0ec87472-e088-4547-a4e5-b8027a21dad1"></a>
### 7168-bfe8005/mint-compression-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      minikube:31332
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 6c5f2623c748:/mint/log /tmp/mint-logs'

(1/13) Running awscli tests ... FAILED in 21 seconds
{
  "name": "awscli",
  "duration": 15964,
  "function": "make_bucket\n",
  "status": "FAIL",
  "error": "('Connection aborted.', ConnectionRefusedError(111, 'Connection refused'))"
}

Executed 0 out of 13 tests successfully.
```
<a name="49bae859-7adb-4f15-81b4-728e2f299f4b"></a>
### 7168-bfe8005/mint-dist-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      minikube:30222
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 4d0286742c44:/mint/log /tmp/mint-logs'

(1/13) Running awscli tests ... FAILED in 8 seconds
{
  "name": "awscli",
  "duration": 6219,
  "function": "make_bucket\n",
  "status": "FAIL",
  "error": "An error occurred (XMinioServerNotInitialized) when calling the CreateBucket operation (reached max retries: 4): Server not initialized, please try again."
}

Executed 0 out of 13 tests successfully.
```
<a name="4e113d8f-cc39-4dbf-acae-224e13595c7f"></a>
### 7168-bfe8005/mint-fs.sh.log:
```
Running with
SERVER_ENDPOINT:      minikube:32758
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp d54c9a958316:/mint/log /tmp/mint-logs'

(1/13) Running awscli tests ... FAILED in 23 seconds
{
  "name": "awscli",
  "duration": 17624,
  "function": "make_bucket\n",
  "status": "FAIL",
  "error": "('Connection aborted.', ConnectionRefusedError(111, 'Connection refused'))"
}

Executed 0 out of 13 tests successfully.
```
<a name="49ab0866-50d9-4bfe-9e39-c6c55c54d33b"></a>
### 7168-bfe8005/mint-compression-fs.sh.log:
```
Running with
SERVER_ENDPOINT:      minikube:32460
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 05bc95609949:/mint/log /tmp/mint-logs'

(1/13) Running awscli tests ... FAILED in 18 seconds
{
  "name": "awscli",
  "duration": 12336,
  "function": "make_bucket\n",
  "status": "FAIL",
  "error": "('Connection aborted.', ConnectionRefusedError(111, 'Connection refused'))"
}

Executed 0 out of 13 tests successfully.
```
<a name="753b17c0-4263-4e1a-95f1-accd9edadc21"></a>
### 7168-bfe8005/mint-tls.sh.log:
```
Running with
SERVER_ENDPOINT:      192.168.39.88:9000
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         1
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 411d570fd64d:/mint/log /tmp/mint-logs'

```

**Comment by minio-ops** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-tls.sh | :x: [more...](#760f578e-6d25-4ba8-9090-205bda2fd721) |
| mint-compression-xl.sh | :x: [more...](#73f0ffcd-537d-4747-86ee-327659291d54) |
| mint-xl.sh | :x: [more...](#ab92ce4f-4cf1-492c-98d3-fa5c1cb7a964) |
| mint-large-bucket.sh | :x: [more...](#ad8d126e-5a4f-4db5-9147-52172de6f258) |
| mint-compression-fs.sh | :x: [more...](#b6784a57-e420-47a0-bd58-b63b3ebced30) |
| mint-worm.sh | :x: [more...](#3856a1da-0d3b-4c33-b553-6e8e42185795) |
| mint-fs.sh | :x: [more...](#7c947445-9c52-488e-ba19-2e7a0d90c5a5) |
| mint-dist-xl.sh | :x: [more...](#45a3323e-8a5d-4ab7-8b8b-480ce67fd419) |
<a name="3856a1da-0d3b-4c33-b553-6e8e42185795"></a>
### 7168-c55d6d0/mint-worm.sh.log:
```
Running with
SERVER_ENDPOINT:      minikube:30862
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            worm
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 846b6067dce7:/mint/log /tmp/mint-logs'

(1/1) Running worm tests ... FAILED in 4 seconds
{
  "alert": "",
  "args": {
    "bucketName": "bucket-r6ljwhysupgtyxnre7232jeyqc5wuttthd5gu2nxbi2ixq9c4jk1d94",
    "expiry": 60000000000,
    "objectName": "testObject"
  },
  "duration": 4509,
  "error": "RequestError: send request failed\ncaused by: Put http://minikube:30862/bucket-r6ljwhysupgtyxnre7232jeyqc5wuttthd5gu2nxbi2ixq9c4jk1d94: dial tcp 192.168.122.88:30862: connect: connection refused",
  "function": "PutAndDelete",
  "message": "WORM_MODE ON  - CreateBucket Failed",
  "name": "test worm mode",
  "status": "FAIL"
}

Executed 0 out of 1 tests successfully.
```
<a name="73f0ffcd-537d-4747-86ee-327659291d54"></a>
### 7168-c55d6d0/mint-compression-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      minikube:32494
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 40b7596cf794:/mint/log /tmp/mint-logs'

(1/13) Running awscli tests ... FAILED in 24 seconds
{
  "name": "awscli",
  "duration": 17514,
  "function": "make_bucket\n",
  "status": "FAIL",
  "error": "('Connection aborted.', ConnectionRefusedError(111, 'Connection refused'))"
}

Executed 0 out of 13 tests successfully.
```
<a name="ad8d126e-5a4f-4db5-9147-52172de6f258"></a>
### 7168-c55d6d0/mint-large-bucket.sh.log:
```
Running with
SERVER_ENDPOINT:      minikube:32608
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp e513319fc839:/mint/log /tmp/mint-logs'

(1/13) Running awscli tests ... FAILED in 12 seconds
{
  "name": "awscli",
  "duration": 8364,
  "function": "make_bucket\n",
  "status": "FAIL",
  "error": "('Connection aborted.', ConnectionRefusedError(111, 'Connection refused'))"
}

Executed 0 out of 13 tests successfully.
```
<a name="ab92ce4f-4cf1-492c-98d3-fa5c1cb7a964"></a>
### 7168-c55d6d0/mint-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      minikube:31500
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp c6f10c667332:/mint/log /tmp/mint-logs'

(1/13) Running awscli tests ... FAILED in 21 seconds
{
  "name": "awscli",
  "duration": 13979,
  "function": "make_bucket\n",
  "status": "FAIL",
  "error": "('Connection aborted.', ConnectionRefusedError(111, 'Connection refused'))"
}

Executed 0 out of 13 tests successfully.
```
<a name="45a3323e-8a5d-4ab7-8b8b-480ce67fd419"></a>
### 7168-c55d6d0/mint-dist-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      minikube:32457
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp c050b66127ef:/mint/log /tmp/mint-logs'

(1/13) Running awscli tests ... FAILED in 10 seconds
{
  "name": "awscli",
  "duration": 5648,
  "function": "make_bucket\n",
  "status": "FAIL",
  "error": "An error occurred (XMinioServerNotInitialized) when calling the CreateBucket operation (reached max retries: 4): Server not initialized, please try again."
}

Executed 0 out of 13 tests successfully.
```
<a name="760f578e-6d25-4ba8-9090-205bda2fd721"></a>
### 7168-c55d6d0/mint-tls.sh.log:
```
Running with
SERVER_ENDPOINT:      192.168.39.88:9000
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         1
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp c339d4d613de:/mint/log /tmp/mint-logs'

```
<a name="7c947445-9c52-488e-ba19-2e7a0d90c5a5"></a>
### 7168-c55d6d0/mint-fs.sh.log:
```
Running with
SERVER_ENDPOINT:      minikube:32373
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 508d359583d9:/mint/log /tmp/mint-logs'

(1/13) Running awscli tests ... FAILED in 23 seconds
{
  "name": "awscli",
  "duration": 14643,
  "function": "make_bucket\n",
  "status": "FAIL",
  "error": "('Connection aborted.', ConnectionRefusedError(111, 'Connection refused'))"
}

Executed 0 out of 13 tests successfully.
```
<a name="b6784a57-e420-47a0-bd58-b63b3ebced30"></a>
### 7168-c55d6d0/mint-compression-fs.sh.log:
```
Running with
SERVER_ENDPOINT:      minikube:31005
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 5341faef5b78:/mint/log /tmp/mint-logs'

(1/13) Running awscli tests ... FAILED in 23 seconds
{
  "name": "awscli",
  "duration": 15535,
  "function": "make_bucket\n",
  "status": "FAIL",
  "error": "('Connection aborted.', ConnectionRefusedError(111, 'Connection refused'))"
}

Executed 0 out of 13 tests successfully.
```

**Comment by minio-ops** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-tls.sh | :heavy_check_mark: |
| mint-compression-xl.sh | :heavy_check_mark: |
| mint-xl.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-compression-fs.sh | :heavy_check_mark: |
| mint-worm.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-dist-xl.sh | :heavy_check_mark: |

File: pkg/net/host.go [hunk 4]
```diff
@@ -129,11 +128,23 @@ func ParseHost(s string) (*Host, error) {
 		isPortSet = true
 	}
 
-	if i := strings.Index(host, "%"); i > -1 {
-		host = host[:i]
+	if host != "" {
+		host, err = normalizeIPv6(host)
```
Comment (balamurugana) [inline pkg/net/host.go]: There is no need to be `normalizeIPv6()` as separate function.  Is there any particular reason?

File: pkg/net/host.go [hunk 5]
```diff
@@ -129,11 +128,23 @@ func ParseHost(s string) (*Host, error) {
...
+		if err != nil {
+			return nil, err
+		}
+	}
+
+	// IPv6 requires a link-local address on every network interface.
+	// `%interface` should be preserved.
+	nHost := host
```
Comment (balamurugana) [inline pkg/net/host.go]: name `nHost` has `trimmedHost`

File: pkg/event/target/postgresql.go [hunk 6]
```diff
@@ -80,15 +79,15 @@ const (
...
-	Port             string   `json:"port"`     // default: 5432
-	User             string   `json:"user"`     // default: user running minio
-	Password         string   `json:"password"` // default: no password
-	Database         string   `json:"database"` // default: same as user
+	Enable           bool      `json:"enable"`
+	Format           string    `json:"format"`
+	ConnectionString string    `json:"connectionString"`
+	Table            string    `json:"table"`
+	Host             xnet.Host `json:"host"`     // default: localhost
+	Port             xnet.Port `json:"port"`     // default: 5432
```
Comment (balamurugana) [inline pkg/event/target/postgresql.go]: As `Host` may come with port, why do we need `Port`?

File: pkg/net/port.go [hunk 7]
```diff
@@ -29,9 +32,45 @@ func (p Port) String() string {
...
+	*port = p
+	return nil
+}
+
 // ParsePort - parses string into Port
 func ParsePort(s string) (p Port, err error) {
 	var i int
+
+	if s == "" {
+		return Port(0), nil
```
Comment (balamurugana) [inline pkg/net/port.go]: Have `s = "0"` then fall through remaining checks.

File: pkg/net/port.go [hunk 8]
```diff
@@ -42,3 +81,17 @@ func ParsePort(s string) (p Port, err error) {
 
 	return Port(i), nil
 }
+
+// ParsePort - parses uint16 into Port
+func ParsePortNumber(n uint16) (p Port, err error) {
```
Comment (balamurugana) [inline pkg/net/port.go]: `Port` in go internals is string.  This function is not needed.  Also please make necessary changes to the fix to have fewer diffs and avoid unnecessary changes.

File: pkg/net/port.go [hunk 9]
```diff
@@ -29,9 +32,45 @@ func (p Port) String() string {
 	return strconv.Itoa(int(p))
 }
 
+// IsEmpty - returns whether the port is empty or not.
+func (p Port) IsEmpty() bool {
```
Comment (balamurugana) [inline pkg/net/port.go]: This is not needed.

File: pkg/net/host_test.go [hunk 10]
```diff
@@ -137,6 +137,9 @@ func TestHostUnmarshalJSON(t *testing.T) {
 		{[]byte(`"12play"`), &Host{"12play", 0, false}, false},
 		{[]byte(`"play-minio-io"`), &Host{"play-minio-io", 0, false}, false},
 		{[]byte(`"play--minio.io"`), &Host{"play--minio.io", 0, false}, false},
+		{[]byte(`"[fe80::8097:76eb:b397:e067%wlp2s0]"`), &Host{"fe80::8097:76eb:b397:e067%wlp2s0", 0, false}, false},
+		{[]byte(`"[fe80::8097:76eb:b397:e067]:9000"`), &Host{"fe80::8097:76eb:b397:e067", 9000, true}, false},
+		{[]byte(`"fe80::8097:76eb:b397:e067%wlp2s0"`), nil, true},
```
Comment (balamurugana) [inline pkg/net/host_test.go:143]: 1. You told this is valid case.  Similarly `fe80::8097:76eb:b397:e067` is also valid ?!
2. Add  all negative test cases.

File: pkg/event/target/postgresql.go (hunk 6 above)
Comment (Praveenrajmani) [reply pkg/event/target/postgresql.go]: In config, we accept `Port` as a separate option in postgreSql.

File: pkg/net/host_test.go (hunk 10 above)
Comment (Praveenrajmani) [reply pkg/net/host_test.go]: With `%` it becomes invalid, will add some testcases for this as well.

Comment (Praveenrajmani) [reply pkg/net/host_test.go:143]: Yes, it becomes invalid if it is not enclosed by square brackets. we get `too many colons` error

File: pkg/net/host.go (hunk 4 above)
Comment (Praveenrajmani) [reply pkg/net/host.go]: normalizeIPv6 here is to strip the enclosing brackets

**Comment by Praveenrajmani** [comment]
I will add all the `xnet.Port` changes in a seperate PR. Will revert the corresponding changes

**Comment by Praveenrajmani** [comment]
The PR is ready for review. PTAL @balamurugana @sinhaashish

**Comment by minio-ops** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-tls.sh | :heavy_check_mark: |
| mint-xl.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-compression-fs.sh | :heavy_check_mark: |
| mint-worm.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-dist-xl.sh | :heavy_check_mark: |
| mint-compression-xl.sh | :x: [more...](#e79e1b6a-0aec-4b3c-9b35-c1eaf01c5154) |
<a name="e79e1b6a-0aec-4b3c-9b35-c1eaf01c5154"></a>
### 7168-f14f88d/mint-compression-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      minikube:30434
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 8675095157b9:/mint/log /tmp/mint-logs'

(1/13) Running awscli tests ... done in 3 minutes and 34 seconds
(2/13) Running aws-sdk-go tests ... done in 0 seconds
(3/13) Running aws-sdk-java tests ... done in 8 seconds
(4/13) Running aws-sdk-php tests ... done in 41 seconds
(5/13) Running aws-sdk-ruby tests ... done in 4 seconds
(6/13) Running mc tests ... done in 30 seconds
(7/13) Running minio-dotnet tests ... FAILED in 2 minutes and 51 seconds

Unhandled Exception: System.AggregateException: One or more errors occurred. (Assert.Fail failed. ) ---> Microsoft.VisualStudio.TestTools.UnitTesting.AssertFailedException: Assert.Fail failed. 
   at Microsoft.VisualStudio.TestTools.UnitTesting.Assert.HandleFail(String assertionName, String message, Object[] parameters)
   at Minio.Functional.Tests.FunctionalTest.<>c.<ListIncompleteUpload_Test2>b__92_1(Exception ex) in /mint/run/core/minio-dotnet/FunctionalTest.cs:line 2534
   at System.Reactive.AutoDetachObserver`1.OnErrorCore(Exception exception) in D:\a\1\s\Rx.NET\Source\src\System.Reactive\Internal\AutoDetachObserver.cs:line 76
   at System.Reactive.AnonymousSafeObserver`1.OnError(Exception error) in D:\a\1\s\Rx.NET\Source\src\System.Reactive\AnonymousSafeObserver.cs:line 62
   at System.Reactive.Linq.ObservableImpl.Throw`1._.Invoke() in D:\a\1\s\Rx.NET\Source\src\System.Reactive\Linq\Observable\Throw.cs:line 42
   at System.Reactive.Concurrency.Scheduler.Invoke(IScheduler scheduler, Action action) in D:\a\1\s\Rx.NET\Source\src\System.Reactive\Concurrency\Scheduler.Simple.cs:line 83
   at System.Reactive.Producer`2.SubscribeRaw(IObserver`1 observer, Boolean enableSafeguard) in D:\a\1\s\Rx.NET\Source\src\System.Reactive\Internal\Producer.cs:line 127
   at System.Reactive.Linq.QueryLanguage.<>c__DisplayClass330_0`1.<Create>b__0(IObserver`1 observer) in D:\a\1\s\Rx.NET\Source\src\System.Reactive\Linq\QueryLanguage.Creation.cs:line 46
   at System.Reactive.AnonymousObservable`1.SubscribeCore(IObserver`1 observer) in D:\a\1\s\Rx.NET\Source\src\System.Reactive\AnonymousObservable.cs:line 37
   at System.Reactive.ObservableBase`1.ScheduledSubscribe(IScheduler _, AutoDetachObserver`1 autoDetachObserver) in D:\a\1\s\Rx.NET\Source\src\System.Reactive\ObservableBase.cs:line 82
   at System.Reactive.Concurrency.CurrentThreadScheduler.Trampoline.Run(SchedulerQueue`1 queue) in D:\a\1\s\Rx.NET\Source\src\System.Reactive\Concurrency\CurrentThreadScheduler.cs:line 126
   at System.Reactive.Concurrency.CurrentThreadScheduler.Schedule[TState](TState state, TimeSpan dueTime, Func`3 action) in D:\a\1\s\Rx.NET\Source\src\System.Reactive\Concurrency\CurrentThreadScheduler.cs:line 94
   at System.Reactive.ObservableBase`1.Subscribe(IObserver`1 observer) in D:\a\1\s\Rx.NET\Source\src\System.Reactive\ObservableBase.cs:line 51
   at Minio.Functional.Tests.FunctionalTest.ListIncompleteUpload_Test2(MinioClient minio) in /mint/run/core/minio-dotnet/FunctionalTest.cs:line 2532
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.Wait()
   at Minio.Functional.Tests.FunctionalTest.Main(String[] args) in /mint/run/core/minio-dotnet/FunctionalTest.cs:line 244

Executed 6 out of 13 tests successfully.
```

**Comment by minio-ops** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-tls.sh | :heavy_check_mark: |
| mint-compression-xl.sh | :heavy_check_mark: |
| mint-xl.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-compression-fs.sh | :heavy_check_mark: |
| mint-worm.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-dist-xl.sh | :heavy_check_mark: |

**Comment by harshavardhana** [comment]
Is this PR ready ?

**Comment by Praveenrajmani** [comment]
yes. this PR is ready

**Comment by harshavardhana** [comment]
PTAL @balamurugana @sinhaashish

File: pkg/net/host.go [hunk 11]
```diff
@@ -143,3 +154,15 @@ func ParseHost(s string) (*Host, error) {
 		IsPortSet: isPortSet,
 	}, nil
 }
+
+// IPv6 can be embedded with square brackets.
+func trimIPv6(host string) (string, error) {
+	// `missing '[' in host` error is already handled in `SplitHostPort`
+	if host[len(host)-1] == ']' {
+		if host[0] != '[' {
```
Comment (sinhaashish) [inline pkg/net/host.go:162]: Isn't this a redundant check, if it is already covered in `SplitHostPort`

Comment (Praveenrajmani) [reply pkg/net/host.go:162]: The comment was misleading. It should have been `missing ']' in host error is already handled in SplitHostPort`. Changed it.

**Comment by minio-ops** [comment]
```
Error running mint automation
+ mkdir -p 7168-68d1263/gopath/src/github.com/minio
+ git -C 7168-68d1263/gopath/src/github.com/minio clone --quiet https://github.com/minio/minio.git
+ git -C 7168-68d1263/gopath/src/github.com/minio/minio remote add minio https://github.com/minio/minio.git
+ git -C 7168-68d1263/gopath/src/github.com/minio/minio fetch --quiet minio pull/7168/head:pr7168
+ git -C 7168-68d1263/gopath/src/github.com/minio/minio checkout --quiet pr7168
+ GO111MODULE=on
+ GOPATH=/mnt/nvme/mint-auto/7168-68d1263/gopath
+ make -C 7168-68d1263/gopath/src/github.com/minio/minio --quiet
go: creating new go.mod: module github.com/minio/minio
go: copying requirements from vendor/vendor.json
go: converting vendor/vendor.json: stat appengine_internal@: unrecognized import path "appengine_internal" (import path does not begin with hostname)
go: converting vendor/vendor.json: stat github.com/ryanuber/go-glob@f348177b5d55dbd38d039b814bf34cbc9cfc093b: unknown revision f348177b5d55dbd38d039b814bf34cbc9cfc093b
go: converting vendor/vendor.json: stat git.apache.org/thrift.git/lib/go/thrift@: unknown revision 
go: converting vendor/vendor.json: stat appengine@: unrecognized import path "appengine" (import path does not begin with hostname)
go: converting vendor/vendor.json: stat appengine_internal/base@: unrecognized import path "appengine_internal/base" (import path does not begin with hostname)
go: converting vendor/vendor.json: stat github.com/hashicorp/go-sockaddr@f348177b5d55dbd38d039b814bf34cbc9cfc093b: unknown revision f348177b5d55dbd38d039b814bf34cbc9cfc093b
go: finding github.com/cheggaaa/pb v0.0.0-20160713104425-73ae1d68fe0b
go: finding github.com/beorn7/perks v0.0.0-20180321164747-3a771d992973
go: finding github.com/satori/uuid v0.0.0-20170321230731-5bf94b69c6b6
go: finding github.com/go-ini/ini v1.27.0
go: finding github.com/aliyun/aliyun-oss-go-sdk v0.0.0-20170925032315-6fe16293d6b7
go: finding github.com/Azure/azure-sdk-for-go v0.0.0-20170922221532-21f5db4a3b31
go: finding github.com/coredns/coredns v0.0.0-20180121192821-d4bf076ccf4e
go: finding github.com/Azure/go-autorest v9.0.0+incompatible
go: finding github.com/nats-io/nuid v1.0.0
go: finding github.com/gorilla/handlers v0.0.0-20160410185317-66e6c6f01d8d
go: finding github.com/hashicorp/errwrap v0.0.0-20180715044906-d6c0cd880357
go: finding github.com/klauspost/reedsolomon v1.8.0
go: finding github.com/googleapis/gax-go v0.0.0-20170321005343-9af46dd5a171
go: finding github.com/rasky/go-lzo v0.0.0-20151023001055-affec0788321
go: finding github.com/prometheus/client_golang v0.0.0-20180416233856-82f5ff156b29
go: finding github.com/klauspost/crc32 v0.0.0-20161016154125-cb6bfca970f6
go: finding github.com/minio/mc v0.0.0-20160229164230-db6b4f13442b
go: finding github.com/lib/pq v0.0.0-20181016162627-9eb73efc1fcc
go: finding github.com/valyala/tcplisten v0.0.0-20161114210144-ceec8f93295a
go: finding github.com/pkg/profile v0.0.0-20180809112205-057bc52a47ec
go: finding github.com/hashicorp/go-version v0.0.0-20160119211326-7e3c02b30806
go: finding contrib.go.opencensus.io/exporter/stackdriver v0.0.0-20180919222851-d1e19f5c23e9
go: finding github.com/gogo/protobuf v0.0.0-20161220170212-84af2615df1b
go: finding github.com/golang/snappy v0.0.0-20180518054509-2e65f85255db
go: finding github.com/miekg/dns v0.0.0-20160726032027-db96a2b759cd
go: finding github.com/hashicorp/go-multierror v0.0.0-20180717150148-3d5d8f294aa0
go: finding github.com/davecgh/go-spew v1.1.0
go: finding github.com/hashicorp/vault v0.0.0-20181121181053-d4367e581fe1
go: finding github.com/eapache/queue v1.1.0
go: finding github.com/gorilla/mux v0.0.0-20160605233521-9fa818a44c2b
go: finding github.com/inconshreveable/go-update v0.0.0-20160112193335-8152e7eb6ccf
go: finding github.com/klauspost/cpuid v0.0.0-20160106104451-349c67577817
go: finding golang.org/x/text v0.0.0-20170427093521-470f45bf29f4
go: finding golang.org/x/text v0.3.0
go: finding golang.org/x/sys v0.0.0-20180430173509-4adea008a5e5
go: finding github.com/mitchellh/mapstructure v0.0.0-20150717051158-281073eb9eb0
go: finding github.com/skyrings/skyring-common v0.0.0-20160324141443-762fd2bfc12e
go: finding google.golang.org/appengine v0.0.0-20180516225643-b9aad5d628b2
go: finding github.com/dustin/go-humanize v0.0.0-20170228161531-259d2a102b87
go: finding golang.org/x/net v0.0.0-20180530234432-1e491301e022
go: finding golang.org/x/net v0.0.0-20190108225652-1e06a53dbb7e
go: finding github.com/minio/sio v0.0.0-20180315104056-b421622190be
go: finding github.com/streadway/amqp v0.0.0-20160311215503-2e25825abdbd
go: finding github.com/nats-io/nats v0.0.0-20160916181735-70b70be17b77
go: finding github.com/minio/minio-go v0.0.0-20190120100529-a42b0e14697f
go: finding github.com/coreos/go-systemd v0.0.0-20180525142239-a4887aeaa186
go: finding go.uber.org/multierr v0.0.0-20180122172545-ddea229ff1df
go: finding github.com/gorilla/context v0.0.0-20160525203319-aed02d124ae4
go: finding google.golang.org/appengine v1.0.0
go: finding github.com/prometheus/common v0.0.0-20180326160409-38c53a9f4bfc
go: finding github.com/mattn/go-isatty v0.0.0-20161123143637-30a891c33c7c
go: finding github.com/grpc-ecosystem/go-grpc-middleware v0.0.0-20180522105215-e9c5d9645c43
go: finding github.com/prometheus/client_model v0.0.0-20171117100541-99fa1f4be8e5
go: finding github.com/mattn/go-colorable v0.0.5
go: finding github.com/minio/highwayhash v0.0.0-20181220011308-93ed73d64169
go: finding golang.org/x/time v0.0.0-20170927054726-6dc17368e09b
go: finding github.com/minio/dsync v0.0.0-20190104003057-61c41ffdeea2
go: finding github.com/klauspost/compress v1.3.0
go: finding gopkg.in/yaml.v2 v2.0.0-20160928153709-a5b47d31c556
go: finding github.com/hashicorp/go-retryablehttp v0.0.0-20180718195005-e651d75abec6
go: finding github.com/golang/protobuf v1.1.0
go: finding golang.org/x/oauth2 v0.0.0-20180603041954-1e0a3fa8ba9a
go: finding golang.org/x/oauth2 v0.0.0-20180821212333-d2e6202438be
go: finding golang.org/x/crypto v0.0.0-20180430181235-ae8bce003081
go: finding github.com/fatih/color v0.0.0-20170113151612-42c364ba4900
go: finding github.com/minio/sha256-simd v0.0.0-20170828173933-43ed500fe4d4
go: finding github.com/xwb1989/sqlparser v0.0.0-20180606152119-120387863bf2
go: finding github.com/hashicorp/go-rootcerts v0.0.0-20160503143440-6bb64b370b90
go: finding github.com/nats-io/go-nats-streaming v0.0.0-20161216191029-077898146bfb
go: finding go.opencensus.io v0.15.0
go: finding gopkg.in/olivere/elastic.v5 v5.0.31
go: finding github.com/eapache/go-xerial-snappy v0.0.0-20160609142408-bb955e01b934
go: finding github.com/nats-io/go-nats v0.0.0-20161120202126-6b6bf392d34d
go: finding golang.org/x/sync v0.0.0-20180314180146-1d60e4601c6f
go: finding google.golang.org/api v0.0.0-20180603000442-8e296ef26005
go: finding github.com/minio/cli v0.0.0-20170227073228-b8ae5507c0ce
go: finding github.com/tidwall/match v0.0.0-20160830173930-173748da739a
go: finding github.com/rs/cors v0.0.0-20160617231935-a62a804a8a00
go: finding github.com/minio/parquet-go v0.0.0-20190114094357-1014bfb4d0e3
go: finding google.golang.org/genproto v0.0.0-20180601223552-81158efcc9f2
go: finding github.com/eclipse/paho.mqtt.golang v0.0.0-20181129145454-379fd9f99ba5
go: finding github.com/djherbis/atime v0.0.0-20170215084934-89517e96e10b
go: finding google.golang.org/genproto v0.0.0-20180918203901-c3f76f3b92d1
go: finding github.com/pierrec/lz4 v0.0.0-20180911175858-1f6e18d34f67
go: finding github.com/eapache/go-resiliency v0.0.0-20160104191539-b86b1ec0dd42
go: finding github.com/tidwall/sjson v1.0.0
go: finding go.uber.org/zap v0.0.0-20180627234335-7e7e266a8dbc
go: finding cloud.google.com/go v0.0.0-20180920172024-e0c17b1c932e
go: finding github.com/minio/lsync v0.0.0-20170809210826-2d7c40f41402
go: finding github.com/klauspost/pgzip v0.0.0-20180606150939-90b2c57fba35
go: finding github.com/rs/xhandler v0.0.0-20160618193221-ed27b6fd6521
go: finding github.com/dgrijalva/jwt-go v0.0.0-20160705203006-01aeca54ebda
go: finding go.opencensus.io v0.0.0-20180920172159-572ae0b6fd86
go: finding github.com/rjeczalik/notify v0.0.0-20180808203925-4e54e7fd043e
go: finding github.com/googleapis/gax-go v2.0.0+incompatible
go: finding golang.org/x/net v0.0.0-20180906233101-161cd47e91fd
go: finding github.com/howeyc/gopass v0.0.0-20170109162249-bf9dde6d0d2c
go: finding github.com/nsqio/go-nsq v0.0.0-20181028195256-0527e80f3ba5
go: finding github.com/garyburd/redigo v0.0.0-20170216214944-0d253a66e6e1
go: finding gopkg.in/Shopify/sarama.v1 v1.10.1
go: finding github.com/segmentio/go-prompt v0.0.0-20161017233205-f0d19b6901ad
go: finding github.com/go-sql-driver/mysql v0.0.0-20181218123637-c45f530f8e7f
go: finding github.com/pkg/profile v1.2.1
go: finding go.uber.org/atomic v1.1.0
go: finding github.com/prometheus/client_golang v0.8.0
go: finding github.com/mitchellh/go-homedir v0.0.0-20161203194507-b8bc1bf76747
go: finding github.com/golang/protobuf v1.2.0
go: finding git.apache.org/thrift.git v0.0.0-20180902110319-2566ecd5d999
go: finding github.com/openzipkin/zipkin-go v0.1.1
go: finding github.com/prometheus/procfs v0.0.0-20180408092902-8b1c2da0d56d
go: finding github.com/matttproud/golang_protobuf_extensions v1.0.1
go: finding google.golang.org/api v0.0.0-20180910000450-7ca32eb868bf
go: finding google.golang.org/api v0.0.0-20180916000451-19ff8768a5c0
go: finding github.com/prometheus/common v0.0.0-20180801064454-c7de2306084e
go: finding github.com/hashicorp/go-cleanhttp v0.0.0-20171218145408-d5fe4b57a186
go: finding github.com/google/go-cmp v0.2.0
go: finding google.golang.org/genproto v0.0.0-20180831171423-11092d34479b
go: finding github.com/coreos/etcd v0.0.0-20180703215944-e4425ee79f2f
go: finding github.com/gorilla/rpc v0.0.0-20160517062331-bd3317b8f670
go: finding google.golang.org/grpc v1.14.0
go: finding github.com/tidwall/gjson v1.1.4
go: finding github.com/elazarl/go-bindata-assetfs v0.0.0-20151224045452-57eb5e1fc594
go: finding cloud.google.com/go v0.23.0
go: finding google.golang.org/grpc v1.12.0
go: finding github.com/prometheus/procfs v0.0.0-20180725123919-05ee40e3a273
go: finding github.com/aws/aws-sdk-go v1.15.31
go: finding github.com/prometheus/client_model v0.0.0-20180712105110-5c3871d89910
go: finding google.golang.org/grpc v1.13.0
go: finding golang.org/x/sys v0.0.0-20180909124046-d0be0721c37e
go: finding github.com/go-ini/ini v1.25.4
go: finding github.com/jmespath/go-jmespath v0.0.0-20160202185014-0b12d6b521d8
go: downloading github.com/minio/mc v0.0.0-20160229164230-db6b4f13442b
go: downloading github.com/hashicorp/go-version v0.0.0-20160119211326-7e3c02b30806
go: downloading google.golang.org/api v0.0.0-20180916000451-19ff8768a5c0
go: downloading cloud.google.com/go v0.23.0
go: downloading github.com/minio/cli v0.0.0-20170227073228-b8ae5507c0ce
go: downloading github.com/minio/minio-go v0.0.0-20190120100529-a42b0e14697f
go: downloading github.com/Azure/azure-sdk-for-go v0.0.0-20170922221532-21f5db4a3b31
go: downloading github.com/Azure/go-autorest v9.0.0+incompatible
go: downloading github.com/segmentio/go-prompt v0.0.0-20161017233205-f0d19b6901ad
go: extracting github.com/hashicorp/go-version v0.0.0-20160119211326-7e3c02b30806
go: downloading github.com/mattn/go-isatty v0.0.0-20161123143637-30a891c33c7c
go: extracting github.com/segmentio/go-prompt v0.0.0-20161017233205-f0d19b6901ad
go: downloading github.com/djherbis/atime v0.0.0-20170215084934-89517e96e10b
go: extracting github.com/mattn/go-isatty v0.0.0-20161123143637-30a891c33c7c
go: downloading github.com/fatih/color v0.0.0-20170113151612-42c364ba4900
go: extracting github.com/djherbis/atime v0.0.0-20170215084934-89517e96e10b
go: downloading github.com/minio/lsync v0.0.0-20170809210826-2d7c40f41402
go: extracting github.com/fatih/color v0.0.0-20170113151612-42c364ba4900
go: downloading github.com/dgrijalva/jwt-go v0.0.0-20160705203006-01aeca54ebda
go: extracting github.com/minio/cli v0.0.0-20170227073228-b8ae5507c0ce
go: extracting github.com/minio/lsync v0.0.0-20170809210826-2d7c40f41402
go: downloading github.com/gorilla/rpc v0.0.0-20160517062331-bd3317b8f670
go: downloading github.com/golang/snappy v0.0.0-20180518054509-2e65f85255db
go: extracting github.com/dgrijalva/jwt-go v0.0.0-20160705203006-01aeca54ebda
go: downloading github.com/minio/sio v0.0.0-20180315104056-b421622190be
go: extracting github.com/Azure/go-autorest v9.0.0+incompatible
go: extracting github.com/gorilla/rpc v0.0.0-20160517062331-bd3317b8f670
go: downloading github.com/miekg/dns v0.0.0-20160726032027-db96a2b759cd
go: downloading github.com/tidwall/sjson v1.0.0
go: extracting github.com/golang/snappy v0.0.0-20180518054509-2e65f85255db
go: downloading github.com/elazarl/go-bindata-assetfs v0.0.0-20151224045452-57eb5e1fc594
go: extracting github.com/elazarl/go-bindata-assetfs v0.0.0-20151224045452-57eb5e1fc594
go: extracting github.com/tidwall/sjson v1.0.0
go: downloading github.com/aliyun/aliyun-oss-go-sdk v0.0.0-20170925032315-6fe16293d6b7
go: extracting github.com/minio/sio v0.0.0-20180315104056-b421622190be
go: downloading github.com/coreos/etcd v0.0.0-20180703215944-e4425ee79f2f
go: extracting github.com/minio/minio-go v0.0.0-20190120100529-a42b0e14697f
go: downloading golang.org/x/sys v0.0.0-20180909124046-d0be0721c37e
go: downloading github.com/inconshreveable/go-update v0.0.0-20160112193335-8152e7eb6ccf
go: downloading github.com/mitchellh/go-homedir v0.0.0-20161203194507-b8bc1bf76747
go: extracting github.com/miekg/dns v0.0.0-20160726032027-db96a2b759cd
go: extracting github.com/mitchellh/go-homedir v0.0.0-20161203194507-b8bc1bf76747
go: extracting github.com/inconshreveable/go-update v0.0.0-20160112193335-8152e7eb6ccf
go: downloading golang.org/x/time v0.0.0-20170927054726-6dc17368e09b
go: downloading go.uber.org/atomic v1.1.0
go: extracting github.com/minio/mc v0.0.0-20160229164230-db6b4f13442b
go: downloading golang.org/x/net v0.0.0-20190108225652-1e06a53dbb7e
go: extracting github.com/aliyun/aliyun-oss-go-sdk v0.0.0-20170925032315-6fe16293d6b7
go: downloading github.com/klauspost/reedsolomon v1.8.0
go: extracting golang.org/x/time v0.0.0-20170927054726-6dc17368e09b
go: downloading github.com/coredns/coredns v0.0.0-20180121192821-d4bf076ccf4e
go: extracting go.uber.org/atomic v1.1.0
go: downloading github.com/minio/highwayhash v0.0.0-20181220011308-93ed73d64169
go: extracting github.com/minio/highwayhash v0.0.0-20181220011308-93ed73d64169
go: downloading github.com/prometheus/client_golang v0.8.0
go: extracting github.com/klauspost/reedsolomon v1.8.0
go: extracting github.com/prometheus/client_golang v0.8.0
go: downloading github.com/klauspost/pgzip v0.0.0-20180606150939-90b2c57fba35
go: downloading github.com/klauspost/cpuid v0.0.0-20160106104451-349c67577817
go: extracting github.com/klauspost/pgzip v0.0.0-20180606150939-90b2c57fba35
go: downloading github.com/hashicorp/vault v0.0.0-20181121181053-d4367e581fe1
go: extracting github.com/klauspost/cpuid v0.0.0-20160106104451-349c67577817
go: downloading github.com/rs/cors v0.0.0-20160617231935-a62a804a8a00
go: extracting github.com/rs/cors v0.0.0-20160617231935-a62a804a8a00
go: extracting golang.org/x/net v0.0.0-20190108225652-1e06a53dbb7e
go: extracting golang.org/x/sys v0.0.0-20180909124046-d0be0721c37e
go: downloading github.com/minio/sha256-simd v0.0.0-20170828173933-43ed500fe4d4
go: downloading github.com/gorilla/handlers v0.0.0-20160410185317-66e6c6f01d8d
go: downloading github.com/gorilla/mux v0.0.0-20160605233521-9fa818a44c2b
go: extracting cloud.google.com/go v0.23.0
go: extracting github.com/gorilla/handlers v0.0.0-20160410185317-66e6c6f01d8d
go: downloading github.com/golang/protobuf v1.2.0
go: extracting github.com/minio/sha256-simd v0.0.0-20170828173933-43ed500fe4d4
go: extracting github.com/gorilla/mux v0.0.0-20160605233521-9fa818a44c2b
go: downloading github.com/go-ini/ini v1.27.0
go: downloading github.com/dustin/go-humanize v0.0.0-20170228161531-259d2a102b87
go: extracting github.com/Azure/azure-sdk-for-go v0.0.0-20170922221532-21f5db4a3b31
go: extracting github.com/dustin/go-humanize v0.0.0-20170228161531-259d2a102b87
go: downloading github.com/cheggaaa/pb v0.0.0-20160713104425-73ae1d68fe0b
go: extracting github.com/go-ini/ini v1.27.0
go: extracting github.com/cheggaaa/pb v0.0.0-20160713104425-73ae1d68fe0b
go: downloading golang.org/x/crypto v0.0.0-20180430181235-ae8bce003081
go: downloading github.com/klauspost/compress v1.3.0
go: downloading github.com/howeyc/gopass v0.0.0-20170109162249-bf9dde6d0d2c
go: extracting github.com/howeyc/gopass v0.0.0-20170109162249-bf9dde6d0d2c
go: downloading github.com/tidwall/gjson v1.1.4
go: extracting github.com/tidwall/gjson v1.1.4
go: downloading github.com/prometheus/common v0.0.0-20180801064454-c7de2306084e
go: extracting github.com/golang/protobuf v1.2.0
go: extracting github.com/prometheus/common v0.0.0-20180801064454-c7de2306084e
go: downloading google.golang.org/genproto v0.0.0-20180918203901-c3f76f3b92d1
go: downloading github.com/streadway/amqp v0.0.0-20160311215503-2e25825abdbd
go: extracting github.com/streadway/amqp v0.0.0-20160311215503-2e25825abdbd
go: downloading github.com/prometheus/procfs v0.0.0-20180725123919-05ee40e3a273
go: extracting github.com/prometheus/procfs v0.0.0-20180725123919-05ee40e3a273
go: downloading gopkg.in/olivere/elastic.v5 v5.0.31
go: extracting golang.org/x/crypto v0.0.0-20180430181235-ae8bce003081
go: downloading github.com/xwb1989/sqlparser v0.0.0-20180606152119-120387863bf2
go: extracting github.com/coredns/coredns v0.0.0-20180121192821-d4bf076ccf4e
go: downloading github.com/minio/dsync v0.0.0-20190104003057-61c41ffdeea2
go: extracting github.com/xwb1989/sqlparser v0.0.0-20180606152119-120387863bf2
go: extracting github.com/minio/dsync v0.0.0-20190104003057-61c41ffdeea2
go: downloading github.com/googleapis/gax-go v2.0.0+incompatible
go: downloading google.golang.org/grpc v1.14.0
go: extracting github.com/googleapis/gax-go v2.0.0+incompatible
go: downloading github.com/go-sql-driver/mysql v0.0.0-20181218123637-c45f530f8e7f
go: extracting github.com/go-sql-driver/mysql v0.0.0-20181218123637-c45f530f8e7f
go: downloading gopkg.in/Shopify/sarama.v1 v1.10.1
go: extracting gopkg.in/olivere/elastic.v5 v5.0.31
go: extracting gopkg.in/Shopify/sarama.v1 v1.10.1
go: downloading github.com/satori/uuid v0.0.0-20170321230731-5bf94b69c6b6
go: extracting github.com/satori/uuid v0.0.0-20170321230731-5bf94b69c6b6
go: downloading github.com/matttproud/golang_protobuf_extensions v1.0.1
go: extracting github.com/klauspost/compress v1.3.0
go: extracting github.com/matttproud/golang_protobuf_extensions v1.0.1
go: extracting google.golang.org/grpc v1.14.0
go: extracting github.com/coreos/etcd v0.0.0-20180703215944-e4425ee79f2f
go: downloading github.com/eapache/queue v1.1.0
go: downloading gopkg.in/yaml.v2 v2.0.0-20160928153709-a5b47d31c556
go: downloading github.com/klauspost/crc32 v0.0.0-20161016154125-cb6bfca970f6
go: extracting github.com/eapache/queue v1.1.0
go: downloading github.com/lib/pq v0.0.0-20181016162627-9eb73efc1fcc
go: extracting github.com/klauspost/crc32 v0.0.0-20161016154125-cb6bfca970f6
go: downloading github.com/eclipse/paho.mqtt.golang v0.0.0-20181129145454-379fd9f99ba5
go: downloading github.com/davecgh/go-spew v1.1.0
go: extracting github.com/davecgh/go-spew v1.1.0
go: extracting github.com/lib/pq v0.0.0-20181016162627-9eb73efc1fcc
go: downloading go.opencensus.io v0.15.0
go: extracting github.com/eclipse/paho.mqtt.golang v0.0.0-20181129145454-379fd9f99ba5
go: downloading github.com/nsqio/go-nsq v0.0.0-20181028195256-0527e80f3ba5
go: extracting github.com/nsqio/go-nsq v0.0.0-20181028195256-0527e80f3ba5
go: downloading github.com/nats-io/nats v0.0.0-20160916181735-70b70be17b77
go: downloading github.com/skyrings/skyring-common v0.0.0-20160324141443-762fd2bfc12e
go: extracting github.com/nats-io/nats v0.0.0-20160916181735-70b70be17b77
go: extracting gopkg.in/yaml.v2 v2.0.0-20160928153709-a5b47d31c556
go: downloading github.com/grpc-ecosystem/go-grpc-middleware v0.0.0-20180522105215-e9c5d9645c43
go: extracting github.com/grpc-ecosystem/go-grpc-middleware v0.0.0-20180522105215-e9c5d9645c43
go: extracting go.opencensus.io v0.15.0
go: downloading github.com/tidwall/match v0.0.0-20160830173930-173748da739a
go: extracting github.com/tidwall/match v0.0.0-20160830173930-173748da739a
go: downloading github.com/minio/parquet-go v0.0.0-20190114094357-1014bfb4d0e3
go: downloading github.com/valyala/tcplisten v0.0.0-20161114210144-ceec8f93295a
go: extracting github.com/valyala/tcplisten v0.0.0-20161114210144-ceec8f93295a
go: downloading github.com/rs/xhandler v0.0.0-20160618193221-ed27b6fd6521
go: extracting github.com/rs/xhandler v0.0.0-20160618193221-ed27b6fd6521
go: downloading go.uber.org/zap v0.0.0-20180627234335-7e7e266a8dbc
go: extracting github.com/minio/parquet-go v0.0.0-20190114094357-1014bfb4d0e3
go: downloading github.com/garyburd/redigo v0.0.0-20170216214944-0d253a66e6e1
go: finding github.com/fatih/structs v1.1.0
go: extracting github.com/garyburd/redigo v0.0.0-20170216214944-0d253a66e6e1
go: downloading golang.org/x/text v0.3.0
go: extracting go.uber.org/zap v0.0.0-20180627234335-7e7e266a8dbc
go: extracting google.golang.org/genproto v0.0.0-20180918203901-c3f76f3b92d1
go: downloading github.com/fatih/structs v1.1.0
go: downloading github.com/eapache/go-resiliency v0.0.0-20160104191539-b86b1ec0dd42
go: extracting github.com/fatih/structs v1.1.0
go: downloading github.com/prometheus/client_model v0.0.0-20180712105110-5c3871d89910
go: extracting github.com/eapache/go-resiliency v0.0.0-20160104191539-b86b1ec0dd42
go: downloading github.com/rjeczalik/notify v0.0.0-20180808203925-4e54e7fd043e
go: extracting github.com/prometheus/client_model v0.0.0-20180712105110-5c3871d89910
go: downloading github.com/beorn7/perks v0.0.0-20180321164747-3a771d992973
go: extracting github.com/rjeczalik/notify v0.0.0-20180808203925-4e54e7fd043e
go: downloading go.uber.org/multierr v0.0.0-20180122172545-ddea229ff1df
go: extracting github.com/beorn7/perks v0.0.0-20180321164747-3a771d992973
go: downloading github.com/mattn/go-colorable v0.0.5
go: extracting github.com/mattn/go-colorable v0.0.5
go: downloading github.com/nats-io/go-nats-streaming v0.0.0-20161216191029-077898146bfb
go: extracting github.com/nats-io/go-nats-streaming v0.0.0-20161216191029-077898146bfb
go: downloading github.com/coreos/go-systemd v0.0.0-20180525142239-a4887aeaa186
go: extracting go.uber.org/multierr v0.0.0-20180122172545-ddea229ff1df
go: downloading github.com/gogo/protobuf v0.0.0-20161220170212-84af2615df1b
go: extracting github.com/coreos/go-systemd v0.0.0-20180525142239-a4887aeaa186
go: downloading github.com/eapache/go-xerial-snappy v0.0.0-20160609142408-bb955e01b934
go: extracting github.com/eapache/go-xerial-snappy v0.0.0-20160609142408-bb955e01b934
go: extracting github.com/skyrings/skyring-common v0.0.0-20160324141443-762fd2bfc12e
go: extracting github.com/gogo/protobuf v0.0.0-20161220170212-84af2615df1b
go: downloading github.com/pkg/profile v1.2.1
go: extracting github.com/pkg/profile v1.2.1
go: downloading github.com/nats-io/go-nats v0.0.0-20161120202126-6b6bf392d34d
go: extracting github.com/nats-io/go-nats v0.0.0-20161120202126-6b6bf392d34d
go: downloading github.com/pierrec/lz4 v0.0.0-20180911175858-1f6e18d34f67
go: extracting github.com/pierrec/lz4 v0.0.0-20180911175858-1f6e18d34f67
go: downloading github.com/nats-io/nuid v1.0.0
go: extracting github.com/nats-io/nuid v1.0.0
go: extracting google.golang.org/api v0.0.0-20180916000451-19ff8768a5c0
go: extracting golang.org/x/text v0.3.0
go: extracting github.com/hashicorp/vault v0.0.0-20181121181053-d4367e581fe1
go: finding git.apache.org/thrift.git/lib/go/thrift latest
go: finding git.apache.org/thrift.git/lib/go latest
go: finding git.apache.org/thrift.git/lib latest
go: finding git.apache.org/thrift.git v0.12.0
go: downloading git.apache.org/thrift.git v0.12.0
go: downloading github.com/rasky/go-lzo v0.0.0-20151023001055-affec0788321
go: finding github.com/coreos/pkg/capnslog latest
go: downloading golang.org/x/oauth2 v0.0.0-20180821212333-d2e6202438be
go: downloading contrib.go.opencensus.io/exporter/stackdriver v0.0.0-20180919222851-d1e19f5c23e9
go: extracting golang.org/x/oauth2 v0.0.0-20180821212333-d2e6202438be
go: extracting github.com/rasky/go-lzo v0.0.0-20151023001055-affec0788321
go: finding github.com/coreos/pkg latest
go: downloading github.com/coreos/pkg v0.0.0-20180928190104-399ea9e2e55f
go: downloading github.com/hashicorp/go-cleanhttp v0.0.0-20171218145408-d5fe4b57a186
go: downloading github.com/mitchellh/mapstructure v0.0.0-20150717051158-281073eb9eb0
go: downloading github.com/hashicorp/errwrap v0.0.0-20180715044906-d6c0cd880357
go: downloading github.com/hashicorp/go-multierror v0.0.0-20180717150148-3d5d8f294aa0
go: downloading github.com/hashicorp/go-retryablehttp v0.0.0-20180718195005-e651d75abec6
go: extracting github.com/hashicorp/go-cleanhttp v0.0.0-20171218145408-d5fe4b57a186
go: extracting github.com/mitchellh/mapstructure v0.0.0-20150717051158-281073eb9eb0
go: extracting github.com/hashicorp/errwrap v0.0.0-20180715044906-d6c0cd880357
go: downloading github.com/hashicorp/go-rootcerts v0.0.0-20160503143440-6bb64b370b90
go: extracting github.com/hashicorp/go-retryablehttp v0.0.0-20180718195005-e651d75abec6
go: extracting github.com/hashicorp/go-multierror v0.0.0-20180717150148-3d5d8f294aa0
go: extracting github.com/coreos/pkg v0.0.0-20180928190104-399ea9e2e55f
go: extracting github.com/hashicorp/go-rootcerts v0.0.0-20160503143440-6bb64b370b90
go: finding github.com/ryanuber/go-glob v1.0.0
go: downloading github.com/ryanuber/go-glob v1.0.0
go: extracting github.com/ryanuber/go-glob v1.0.0
go: finding github.com/hashicorp/hcl v1.0.0
go: finding github.com/hashicorp/hcl/hcl/ast latest
go: finding github.com/hashicorp/go-sockaddr v1.0.2
go: downloading github.com/hashicorp/go-sockaddr v1.0.2
go: extracting github.com/hashicorp/go-sockaddr v1.0.2
go: downloading github.com/hashicorp/hcl v1.0.0
go: finding github.com/hashicorp/hcl/hcl latest
go: extracting github.com/hashicorp/hcl v1.0.0
go: extracting git.apache.org/thrift.git v0.12.0
go: extracting contrib.go.opencensus.io/exporter/stackdriver v0.0.0-20180919222851-d1e19f5c23e9
go: finding github.com/davecgh/go-spew v1.1.1
go: finding github.com/hashicorp/errwrap v1.0.0
go: finding github.com/mitchellh/go-wordwrap v1.0.0
go: finding github.com/ryanuber/columnize v2.1.0+incompatible
go: finding github.com/mitchellh/cli v1.0.0
go: finding github.com/fatih/color v1.7.0
go: finding github.com/mattn/go-colorable v0.0.9
go: finding github.com/hashicorp/go-multierror v1.0.0
go: finding golang.org/x/sys v0.0.0-20180823144017-11551d06cbcc
go: finding github.com/mattn/go-isatty v0.0.3
go: finding github.com/bgentry/speakeasy v0.1.0
go: finding github.com/armon/go-radix v0.0.0-20180808171621-7fddfc383310
go: finding github.com/posener/complete v1.1.1
go: downloading github.com/fatih/color v1.7.0
go: downloading github.com/mattn/go-colorable v0.0.9
go: extracting github.com/mattn/go-colorable v0.0.9
go: downloading github.com/mattn/go-isatty v0.0.3
go: downloading github.com/hashicorp/go-multierror v1.0.0
go: downloading github.com/hashicorp/errwrap v1.0.0
go: downloading github.com/davecgh/go-spew v1.1.1
go: extracting github.com/mattn/go-isatty v0.0.3
go: extracting github.com/hashicorp/errwrap v1.0.0
go: extracting github.com/hashicorp/go-multierror v1.0.0
go: extracting github.com/davecgh/go-spew v1.1.1
go: extracting github.com/fatih/color v1.7.0
# github.com/minio/minio/cmd
cmd/metrics.go:178:9: undefined: promhttp.InstrumentMetricHandler
cmd/namespace-lock.go:152:12: cannot use &lsync.LRWMutex literal (type *lsync.LRWMutex) as type RWLockerSync in return argument:
	*lsync.LRWMutex does not implement RWLockerSync (wrong type for GetLock method)
		have GetLock(time.Duration) bool
		want GetLock(string, string, time.Duration) bool
make: *** [build] Error 2

```

**Comment by minio-ops** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-compression-xl.sh | :heavy_check_mark: |
| mint-xl.sh | :heavy_check_mark: |
| mint-compression-dist-xl.sh | :heavy_check_mark: |
| mint-compression-fs.sh | :heavy_check_mark: |
| mint-worm.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :x: [more...](#90c55244-a819-445d-92b9-35b7dc0af330) |
| mint-dist-xl.sh | :x: [more...](#0d5f2bab-b5c7-4a81-8b3f-570cf23f2421) |
<a name="0d5f2bab-b5c7-4a81-8b3f-570cf23f2421"></a>
### 7168-614a4c8/mint-dist-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.61:31145
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 033049334ae0:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... FAILED in 6 minutes and 0 seconds
{
  "alert": "",
  "args": {
    "bucketName": "aws-sdk-go-test-smg5bn5tzaphal",
    "expiry": 60000000000,
    "objectName": "presignedTest"
  },
  "duration": 360009,
  "error": "XMinioServerNotInitialized: Server not initialized, please try again.\n\tstatus code: 503, request id: 1591E3548B5D8A2B, host id: ",
  "function": "PresignedPut",
  "message": "AWS SDK Go CreateBucket Failed",
  "name": "aws-sdk-go",
  "status": "FAIL"
}

Executed 0 out of 14 tests successfully.
```
<a name="90c55244-a819-445d-92b9-35b7dc0af330"></a>
### 7168-614a4c8/mint-large-bucket.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.59:32375
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 00633bf47e12:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... FAILED in 6 minutes and 0 seconds
{
  "alert": "",
  "args": {
    "bucketName": "aws-sdk-go-test-ljhwaifuzydeb6",
    "expiry": 60000000000,
    "objectName": "presignedTest"
  },
  "duration": 360009,
  "error": "XMinioServerNotInitialized: Server not initialized, please try again.\n\tstatus code: 503, request id: 1591E3548BCAD67B, host id: ",
  "function": "PresignedPut",
  "message": "AWS SDK Go CreateBucket Failed",
  "name": "aws-sdk-go",
  "status": "FAIL"
}

Executed 0 out of 14 tests successfully.
```

**Review by sinhaashish — DISMISSED** [review]
Tested & LGTM

**Comment by Praveenrajmani** [comment]
PTAL @balamurugana

**Comment by minio-ops** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-compression-xl.sh | :heavy_check_mark: |
| mint-xl.sh | :heavy_check_mark: |
| mint-compression-fs.sh | :heavy_check_mark: |
| mint-dist-xl.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :x: [more...](#d2cec708-cafb-4dce-bb7a-4a1335f798af) |
| mint-compression-dist-xl.sh | :x: [more...](#c0818203-aeeb-47a7-b234-98a4043b42b0) |
| mint-worm.sh | :x: [more...](#9541c797-6eb9-44bb-aad2-e2a133f5b42e) |
| mint-fs.sh | :x: [more...](#6a5de8b0-8d79-44bb-885a-a371ac787658) |
| mint-gateway-nas.sh | :x: [more...](#351ec098-bef2-4711-90a1-ab097903b295) |
<a name="6a5de8b0-8d79-44bb-885a-a371ac787658"></a>
### 7168-63a575b/mint-fs.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.56:30424
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp b196601450ab:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 0 seconds
(2/14) Running aws-sdk-java tests ... done in 1 seconds
(3/14) Running aws-sdk-php tests ... done in 41 seconds
(4/14) Running aws-sdk-ruby tests ... done in 2 seconds
(5/14) Running awscli tests ... done in 1 minutes and 46 seconds
(6/14) Running healthcheck tests ... done in 0 seconds
(7/14) Running mc tests ... done in 20 seconds
(8/14) Running minio-dotnet tests ... done in 24 seconds
(9/14) Running minio-go tests ... done in 27 seconds
(10/14) Running minio-java tests ... done in 1 minutes and 29 seconds
(11/14) Running minio-js tests ... done in 36 seconds
(12/14) Running minio-py tests ... FAILED in 2 minutes and 39 seconds
{
  "message": "AccessDenied: message: Access Denied",
  "duration": 69,
  "error": "Traceback (most recent call last):\n  File \"/mint/run/core/minio-py/tests.py\", line 1220, in test_presigned_get_object_expiry_5sec\n    object_name).get_exception()\nminio.error.AccessDenied: AccessDenied: message: Access Denied\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"/mint/run/core/minio-py/tests.py\", line 1885, in main\n    test_presigned_get_object_expiry_5sec(client, log_output)\n  File \"/mint/run/core/minio-py/tests.py\", line 1228, in test_presigned_get_object_expiry_5sec\n    raise Exception(err)\nException: AccessDenied: message: Access Denied\n",
  "args": {
    "object_name": "eb3109ea-536a-4f25-918d-025dae136b20",
    "bucket_name": "minio-py-test-8f4dcb90-5389-4799-a76a-8c88a38cf8d0"
  },
  "name": "minio-py:test_presigned_get_object_expiry_5sec",
  "status": "FAIL",
  "function": "presigned_get_object(bucket_name, object_name, expires, response_headers, request_date)"
}

Executed 11 out of 14 tests successfully.
```
<a name="c0818203-aeeb-47a7-b234-98a4043b42b0"></a>
### 7168-63a575b/mint-compression-dist-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.55:30936
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 3ea976ac36b0:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... FAILED in 6 minutes and 0 seconds
{
  "alert": "",
  "args": {
    "bucketName": "aws-sdk-go-test-g1o1omgc3ab4t9",
    "expiry": 60000000000,
    "objectName": "presignedTest"
  },
  "duration": 360007,
  "error": "XMinioServerNotInitialized: Server not initialized, please try again.\n\tstatus code: 503, request id: 1597BA025DF9ECA6, host id: ",
  "function": "PresignedPut",
  "message": "AWS SDK Go CreateBucket Failed",
  "name": "aws-sdk-go",
  "status": "FAIL"
}

Executed 0 out of 14 tests successfully.
```
<a name="351ec098-bef2-4711-90a1-ab097903b295"></a>
### 7168-63a575b/mint-gateway-nas.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.61:32313
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 36b8c3c3b2ea:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... FAILED in 0 seconds
{
  "alert": "",
  "args": {
    "bucketName": "aws-sdk-go-test-eaoatslhzcxbay",
    "expiry": 60000000000,
    "objectName": "presignedTest"
  },
  "duration": 314,
  "error": "RequestError: send request failed\ncaused by: Put http://72.28.97.61:32313/aws-sdk-go-test-eaoatslhzcxbay: dial tcp 72.28.97.61:32313: connect: connection refused",
  "function": "PresignedPut",
  "message": "AWS SDK Go CreateBucket Failed",
  "name": "aws-sdk-go",
  "status": "FAIL"
}

Executed 0 out of 14 tests successfully.
```
<a name="9541c797-6eb9-44bb-aad2-e2a133f5b42e"></a>
### 7168-63a575b/mint-worm.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.56:31167
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            worm
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp e236e949bc06:/mint/log /tmp/mint-logs'

(1/1) Running worm tests ... FAILED in 0 seconds
{
  "alert": "",
  "args": {
    "bucketName": "bucket-j5y9odet9iqcytsk3c92kw17w6o8k06wnkzt3yup0n1i4s8u682zdjq",
    "expiry": 60000000000,
    "objectName": "testObject"
  },
  "duration": 309,
  "error": "RequestError: send request failed\ncaused by: Put http://72.28.97.56:31167/bucket-j5y9odet9iqcytsk3c92kw17w6o8k06wnkzt3yup0n1i4s8u682zdjq: dial tcp 72.28.97.56:31167: connect: connection refused",
  "function": "PutAndDelete",
  "message": "WORM_MODE ON  - CreateBucket Failed",
  "name": "test worm mode",
  "status": "FAIL"
}

Executed 0 out of 1 tests successfully.
```
<a name="d2cec708-cafb-4dce-bb7a-4a1335f798af"></a>
### 7168-63a575b/mint-large-bucket.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.56:30987
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp d988cca50e7c:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... FAILED in 6 minutes and 0 seconds
{
  "alert": "",
  "args": {
    "bucketName": "aws-sdk-go-test-bzfqhmrctksmru",
    "expiry": 60000000000,
    "objectName": "presignedTest"
  },
  "duration": 360009,
  "error": "XMinioServerNotInitialized: Server not initialized, please try again.\n\tstatus code: 503, request id: 1597BA024F2D503E, host id: ",
  "function": "PresignedPut",
  "message": "AWS SDK Go CreateBucket Failed",
  "name": "aws-sdk-go",
  "status": "FAIL"
}

Executed 0 out of 14 tests successfully.
```

**Comment by Praveenrajmani** [comment]
Resolved the conflicts. Can i get some reviews @balamurugana @sinhaashish ?

**Review by balamurugana — APPROVED** [review]

**Review by sinhaashish — APPROVED** [review]

**Comment by minio-ops** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-compression-xl.sh | :heavy_check_mark: |
| mint-xl.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-compression-dist-xl.sh | :heavy_check_mark: |
| mint-compression-fs.sh | :heavy_check_mark: |
| mint-worm.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-dist-xl.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |

**Comment by harshavardhana** [comment]
A binary file was checked in this PR, let's verify once before merge to make sure that unexpected files are not merged - will be fixed here #7615
