### PR TITLE
In HDFS gateway fix non-empty folder behavior

### LINKED ISSUE #8143: HDFS gateway head request on existing folder in a bucket returns 200
When running `minio gateway hdfs`, a [`head-object`](https://docs.aws.amazon.com/cli/latest/reference/s3api/head-object.html) call against an existing directory in the bucket returns a 200 response code, instead of the expect 404.

## Expected Behavior
It should return 404, similar to S3 (directly), `gateway s3`, `gateway azure`, and `server ...`

```
$ aws --endpoint-url=http://localhost:9000 s3api head-object --bucket poc-bucket --key warehouse/dev

An error occurred (404) when calling the HeadObject operation: Not Found
```

## Current Behavior
It return a 200 response along with a response body:

```
$ aws --endpoint-url=http://localhost:9000 s3api head-object --bucket poc-bucket --key warehouse/dev
{
    "AcceptRanges": "bytes",
    "LastModified": "Tue, 27 Aug 2019 16:39:12 GMT",
    "ContentLength": 0,
    "Metadata": {}
}
```

## Steps to Reproduce (for bugs)
1. Run minio as hdfs gateway - `minio gateway hdfs hdfs://namenode:8020`
2. Create bucket `poc-bucket` on the local minio
3. Create directory `warehouse/dev` under the `poc-bucket`
4. Run the `aws --endpoint-url=http://localhost:9000 s3api head-object --bucket poc-bucket --key warehouse/dev`

## Context
We ran across this when attempting to run an [Apache Flink](https://flink.apache.org/)-based application generating data files for Hive.  We were testing the application using an `s3a://` location for the data files and using MinIO backed by S3, local-disk, and Azure.  When we attempted to use the HDFS gateway mode of MinIO, the `s3a` file system code in Hadoop/Hive fails because it interpreted the 200 response from MinIO when querying the directories as an indication that the path was an empty file.

## Regression
Unsure.  Based on #4434, it appears that the 200 response is not the expected behavior.

## Your Environment
* Version used (`minio version`):
latest Docker image

* Environment name and version (e.g. nginx 1.9.1):
MacOS X 10.14.6 running Minio & Hadoop in Docker

* Server type and version:
Docker 2.1.0.1

* Operating System and version (`uname -a`):
Darwin acourtnrownsmbp.notcharlie.com 18.7.0 Darwin Kernel Version 18.7.0: Thu Jun 20 18:42:21 PDT 2019; root:xnu-4903.270.47~4/RELEASE_X86_64 x86_64

* Link to your project:

### PR DESCRIPTION
**Pull request by harshavardhana**
## Description
To be compatible with our FS and Erasure coded
mode deployments, make sure that we do not send
200 OK for folders which have files inside.

## Motivation and Context
Fixes #8143

## How to test this PR?
You need a running HDFS cluster, follow Hadoop docs on setting it up. 

## Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [ ] Fixes a regression (If yes, please add `commit-id` or `PR #` here)
- [ ] Documentation needed
- [ ] Unit tests needed
- [ ] Functional tests needed (If yes, add [mint](https://github.com/minio/mint) PR # here: )

### CODE REVIEW

**Comment by minio-ops** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-compression-xl.sh | :heavy_check_mark: |
| mint-xl.sh | :heavy_check_mark: |
| mint-worm.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :x: [more...](#c73ad0b5-ca38-47c2-a4de-4fcab10a7f58) |
| mint-compression-dist-xl.sh | :x: [more...](#e5d84619-9ec8-429e-b739-260974547f1d) |
| mint-compression-fs.sh | :x: [more...](#1cdd5fb0-915b-42c7-93e2-3030cf3adb05) |
| mint-fs.sh | :x: [more...](#083fc52c-7809-4ca2-b147-ce6da7b8d829) |
| mint-dist-xl.sh | :x: [more...](#0af1ce4f-78b2-4caf-a98b-a4fdb8486830) |
<a name="1cdd5fb0-915b-42c7-93e2-3030cf3adb05"></a>
### 8254-a5761ff/mint-compression-fs.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.59:30898
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp c786c5bef1d3:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 0 seconds
(2/14) Running aws-sdk-java tests ... done in 1 seconds
(3/14) Running aws-sdk-php tests ... done in 41 seconds
(4/14) Running aws-sdk-ruby tests ... done in 1 seconds
(5/14) Running awscli tests ... done in 52 seconds
(6/14) Running healthcheck tests ... done in 0 seconds
(7/14) Running mc tests ... done in 26 seconds
(8/14) Running minio-dotnet tests ... done in 20 seconds
(9/14) Running minio-go tests ... done in 15 seconds
(10/14) Running minio-java tests ... done in 16 seconds
(11/14) Running minio-js tests ... FAILED in 16 seconds
{
  "name": "minio-js",
  "function": "fPutObject(bucketName, objectName, filePath, callback)",
  "args": "bucketName:minio-js-test-c5edcd25-029f-4045-a5e6-3e4fb3ef4992, objectName:datafile-65-MB, filePath:/tmp/datafile-65-MB",
  "duration": 3336,
  "status": "FAIL",
  "error": "Error: read ECONNRESET at exports._errnoException (util.js:1020:11) at TCP.onread (net.js:580:26)"
}

Executed 10 out of 14 tests successfully.
```
<a name="c73ad0b5-ca38-47c2-a4de-4fcab10a7f58"></a>
### 8254-a5761ff/mint-large-bucket.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.60:31108
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp b92a3645f2cd:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 5 minutes and 5 seconds
(2/14) Running aws-sdk-java tests ... done in 2 seconds
(3/14) Running aws-sdk-php tests ... done in 55 seconds
(4/14) Running aws-sdk-ruby tests ... done in 15 seconds
(5/14) Running awscli tests ... done in 2 minutes and 10 seconds
(6/14) Running healthcheck tests ... done in 0 seconds
(7/14) Running mc tests ... done in 1 minutes and 0 seconds
(8/14) Running minio-dotnet tests ... done in 1 minutes and 19 seconds
(9/14) Running minio-go tests ... FAILED in 3 minutes and 26 seconds
{
  "args": {},
  "duration": 64712,
  "error": "The specified key does not exist.",
  "function": "testStorageClassMetadataCopyObject()",
  "message": "Stat failed",
  "name": "minio-go: testStorageClassMetadataCopyObject",
  "status": "FAIL"
}

Executed 8 out of 14 tests successfully.
```
<a name="e5d84619-9ec8-429e-b739-260974547f1d"></a>
### 8254-a5761ff/mint-compression-dist-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.53:31464
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 670b3215a83a:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 1 seconds
(2/14) Running aws-sdk-java tests ... done in 1 seconds
(3/14) Running aws-sdk-php tests ... done in 47 seconds
(4/14) Running aws-sdk-ruby tests ... done in 4 seconds
(5/14) Running awscli tests ... FAILED in 1 minutes and 57 seconds
{
  "name": "awscli",
  "duration": 63421,
  "function": "aws --endpoint-url http://72.28.97.53:31464 s3 sync --no-progress /mint/data s3://awscli-mint-test-bucket-14709/\n",
  "status": "FAIL",
  "error": "upload: ../../../data/datafile-0-b to s3://awscli-mint-test-bucket-14709/datafile-0-bupload: ../../../data/datafile-100-kB to s3://awscli-mint-test-bucket-14709/datafile-100-kBupload: ../../../data/datafile-1-kB to s3://awscli-mint-test-bucket-14709/datafile-1-kBupload: ../../../data/datafile-1-b to s3://awscli-mint-test-bucket-14709/datafile-1-bupload: ../../../data/datafile-1-MB to s3://awscli-mint-test-bucket-14709/datafile-1-MBupload: ../../../data/datafile-1.03-MB to s3://awscli-mint-test-bucket-14709/datafile-1.03-MBupload: ../../../data/datafile-33-kB to s3://awscli-mint-test-bucket-14709/datafile-33-kBupload: ../../../data/datafile-5-MB to s3://awscli-mint-test-bucket-14709/datafile-5-MBupload: ../../../data/datafile-5243880-b to s3://awscli-mint-test-bucket-14709/datafile-5243880-bupload: ../../../data/datafile-6-MB to s3://awscli-mint-test-bucket-14709/datafile-6-MBupload: ../../../data/datafile-10-kB to s3://awscli-mint-test-bucket-14709/datafile-10-kBupload: ../../../data/datafile-10-MB to s3://awscli-mint-test-bucket-14709/datafile-10-MBupload: ../../../data/datafile-65-MB to s3://awscli-mint-test-bucket-14709/datafile-65-MBupload failed: ../../../data/datafile-129-MB to s3://awscli-mint-test-bucket-14709/datafile-129-MB An error occurred (InvalidPart) when calling the CompleteMultipartUpload operation: One or more of the specified parts could not be found.  The part may not have been uploaded, or the specified entity tag may not match the part's entity tag.upload: ../../../data/datafile-11-MB to s3://awscli-mint-test-bucket-14709/datafile-11-MB"
}

Executed 4 out of 14 tests successfully.
```
<a name="083fc52c-7809-4ca2-b147-ce6da7b8d829"></a>
### 8254-a5761ff/mint-fs.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.54:30419
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 04fad34dd859:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 0 seconds
(2/14) Running aws-sdk-java tests ... done in 1 seconds
(3/14) Running aws-sdk-php tests ... done in 42 seconds
(4/14) Running aws-sdk-ruby tests ... done in 2 seconds
(5/14) Running awscli tests ... done in 1 minutes and 51 seconds
(6/14) Running healthcheck tests ... done in 0 seconds
(7/14) Running mc tests ... done in 33 seconds
(8/14) Running minio-dotnet tests ... done in 26 seconds
(9/14) Running minio-go tests ... done in 42 seconds
(10/14) Running minio-java tests ... done in 45 seconds
(11/14) Running minio-js tests ... done in 43 seconds
(12/14) Running minio-py tests ... FAILED in 1 minutes and 56 seconds
{
  "duration": 57,
  "name": "minio-py:test_presigned_get_object_expiry_5sec",
  "function": "presigned_get_object(bucket_name, object_name, expires, response_headers, request_date)",
  "args": {
    "response._body": "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<Error><Code>AccessDenied</Code><Message>Request has expired</Message><Key>02521f9c-fbd9-441a-8e44-8214a10ad90b</Key><BucketName>minio-py-test-3a562915-7a47-411a-bd49-e341dc7deb7f</BucketName><Resource>/minio-py-test-3a562915-7a47-411a-bd49-e341dc7deb7f/02521f9c-fbd9-441a-8e44-8214a10ad90b</Resource><RequestId>15C52EF697F1EE75</RequestId><HostId>4b8c547d-1202-4c93-a889-fc7e1159a9ff</HostId></Error>",
    "bucket_name": "minio-py-test-3a562915-7a47-411a-bd49-e341dc7deb7f",
    "response.status": 403,
    "response.reason": "Forbidden",
    "response.headers": "{\"_container\": {\"accept-ranges\": [\"Accept-Ranges\", \"bytes\"], \"content-length\": [\"Content-Length\", \"440\"], \"content-security-policy\": [\"Content-Security-Policy\", \"block-all-mixed-content\"], \"content-type\": [\"Content-Type\", \"application/xml\"], \"server\": [\"Server\", \"MinIO/DEVELOPMENT.2019-09-17T08-54-07Z\"], \"vary\": [\"Vary\", \"Origin\"], \"x-amz-request-id\": [\"X-Amz-Request-Id\", \"15C52EF697F1EE75\"], \"x-xss-protection\": [\"X-Xss-Protection\", \"1; mode=block\"], \"date\": [\"Date\", \"Tue, 17 Sep 2019 09:14:41 GMT\"]}}",
    "presigned_get_object_url": "http://72.28.97.54:30419/minio-py-test-3a562915-7a47-411a-bd49-e341dc7deb7f/02521f9c-fbd9-441a-8e44-8214a10ad90b?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=minio%2F20190917%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20190917T091436Z&X-Amz-Expires=5&X-Amz-SignedHeaders=host&X-Amz-Signature=0870fcc62679fabb93e6a736c51c9236575d4e3ec19273be6b8fcfea6efcd71f",
    "object_name": "02521f9c-fbd9-441a-8e44-8214a10ad90b"
  },
  "message": "AccessDenied: message: Access Denied",
  "error": "Traceback (most recent call last):\n  File \"/mint/run/core/minio-py/tests.py\", line 1341, in test_presigned_get_object_expiry_5sec\n    object_name).get_exception()\nminio.error.AccessDenied: AccessDenied: message: Access Denied\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"/mint/run/core/minio-py/tests.py\", line 2036, in main\n    test_presigned_get_object_expiry_5sec(client, log_output)\n  File \"/mint/run/core/minio-py/tests.py\", line 1355, in test_presigned_get_object_expiry_5sec\n    raise Exception(err)\nException: AccessDenied: message: Access Denied\n",
  "status": "FAIL"
}

Executed 11 out of 14 tests successfully.
```
<a name="0af1ce4f-78b2-4caf-a98b-a4fdb8486830"></a>
### 8254-a5761ff/mint-dist-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.54:30697
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 931ad66bae65:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 3 seconds
(2/14) Running aws-sdk-java tests ... done in 1 seconds
(3/14) Running aws-sdk-php tests ... done in 44 seconds
(4/14) Running aws-sdk-ruby tests ... done in 5 seconds
(5/14) Running awscli tests ... done in 2 minutes and 4 seconds
(6/14) Running healthcheck tests ... done in 0 seconds
(7/14) Running mc tests ... done in 46 seconds
(8/14) Running minio-dotnet tests ... done in 52 seconds
(9/14) Running minio-go tests ... done in 1 minutes and 21 seconds
(10/14) Running minio-java tests ... done in 47 seconds
(11/14) Running minio-js tests ... done in 55 seconds
(12/14) Running minio-py tests ... FAILED in 1 minutes and 46 seconds
{
  "name": "minio-py:test_list_objects_with_1001_files",
  "duration": 80106,
  "function": "list_objects(bucket_name, prefix, recursive)",
  "status": "FAIL",
  "args": {
    "bucket_name": "minio-py-test-790c7f27-94fd-4ebe-a935-d7608412804b",
    "object_name": "d91ffce3-7cc6-4c8f-90df-28ddfd168223_0 ~ d91ffce3-7cc6-4c8f-90df-28ddfd168223_1000"
  },
  "message": "BucketNotEmpty: message: The bucket you tried to delete is not empty.",
  "error": "Traceback (most recent call last):\n  File \"/mint/run/core/minio-py/tests.py\", line 1168, in test_list_objects_with_1001_files\n    client.remove_bucket(bucket_name)\n  File \"/usr/local/lib/python3.5/dist-packages/minio/api.py\", line 417, in remove_bucket\n    self._url_open('DELETE', bucket_name=bucket_name)\n  File \"/usr/local/lib/python3.5/dist-packages/minio/api.py\", line 1952, in _url_open\n    object_name).get_exception()\nminio.error.BucketNotEmpty: BucketNotEmpty: message: The bucket you tried to delete is not empty.\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"/mint/run/core/minio-py/tests.py\", line 2024, in main\n    test_list_objects_with_1001_files(client, log_output)\n  File \"/mint/run/core/minio-py/tests.py\", line 1170, in test_list_objects_with_1001_files\n    raise Exception(err)\nException: BucketNotEmpty: message: The bucket you tried to delete is not empty.\n"
}

Executed 11 out of 14 tests successfully.
```

**Comment by minio-ops** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-compression-xl.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-worm.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-dist-xl.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-xl.sh | :x: [more...](#4202e1a7-df1e-4bb7-9659-aba6e7014e8c) |
| mint-compression-dist-xl.sh | :x: [more...](#c1ef4a56-0b12-49a8-b0b0-bda350348436) |
| mint-compression-fs.sh | :x: [more...](#08a1cef2-8947-4ef3-863f-45e06c9bf9fe) |
<a name="08a1cef2-8947-4ef3-863f-45e06c9bf9fe"></a>
### 8254-625c11d/mint-compression-fs.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.59:30222
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 670ef9b5d48a:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 0 seconds
(2/14) Running aws-sdk-java tests ... done in 1 seconds
(3/14) Running aws-sdk-php tests ... done in 42 seconds
(4/14) Running aws-sdk-ruby tests ... done in 2 seconds
(5/14) Running awscli tests ... done in 1 minutes and 51 seconds
(6/14) Running healthcheck tests ... done in 0 seconds
(7/14) Running mc tests ... done in 39 seconds
(8/14) Running minio-dotnet tests ... done in 25 seconds
(9/14) Running minio-go tests ... done in 45 seconds
(10/14) Running minio-java tests ... done in 53 seconds
(11/14) Running minio-js tests ... done in 52 seconds
(12/14) Running minio-py tests ... FAILED in 2 minutes and 19 seconds
{
  "args": {
    "response.reason": "Forbidden",
    "response._body": "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<Error><Code>AccessDenied</Code><Message>Request has expired</Message><Key>2ac31a1c-9b5a-4fc7-b360-9bb7005f617e</Key><BucketName>minio-py-test-d9ffb4cc-1fe8-4747-bf03-552b5cb19c04</BucketName><Resource>/minio-py-test-d9ffb4cc-1fe8-4747-bf03-552b5cb19c04/2ac31a1c-9b5a-4fc7-b360-9bb7005f617e</Resource><RequestId>15C5308FFACAC1A7</RequestId><HostId>547be6af-6fec-488f-a05d-d1e6bd8a0e40</HostId></Error>",
    "object_name": "2ac31a1c-9b5a-4fc7-b360-9bb7005f617e",
    "response.status": 403,
    "presigned_get_object_url": "http://72.28.97.59:30222/minio-py-test-d9ffb4cc-1fe8-4747-bf03-552b5cb19c04/2ac31a1c-9b5a-4fc7-b360-9bb7005f617e?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=minio%2F20190917%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20190917T094355Z&X-Amz-Expires=5&X-Amz-SignedHeaders=host&X-Amz-Signature=f0db24d8366924e8b226e87927f9dd66d69c1ca13c0359ba5935c691b34630c7",
    "bucket_name": "minio-py-test-d9ffb4cc-1fe8-4747-bf03-552b5cb19c04",
    "response.headers": "{\"_container\": {\"accept-ranges\": [\"Accept-Ranges\", \"bytes\"], \"content-length\": [\"Content-Length\", \"440\"], \"content-security-policy\": [\"Content-Security-Policy\", \"block-all-mixed-content\"], \"content-type\": [\"Content-Type\", \"application/xml\"], \"server\": [\"Server\", \"MinIO/DEVELOPMENT.2019-09-17T09-22-12Z\"], \"vary\": [\"Vary\", \"Origin\"], \"x-amz-request-id\": [\"X-Amz-Request-Id\", \"15C5308FFACAC1A7\"], \"x-xss-protection\": [\"X-Xss-Protection\", \"1; mode=block\"], \"date\": [\"Date\", \"Tue, 17 Sep 2019 09:44:00 GMT\"]}}"
  },
  "duration": 48,
  "function": "presigned_get_object(bucket_name, object_name, expires, response_headers, request_date)",
  "error": "Traceback (most recent call last):\n  File \"/mint/run/core/minio-py/tests.py\", line 1341, in test_presigned_get_object_expiry_5sec\n    object_name).get_exception()\nminio.error.AccessDenied: AccessDenied: message: Access Denied\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"/mint/run/core/minio-py/tests.py\", line 2036, in main\n    test_presigned_get_object_expiry_5sec(client, log_output)\n  File \"/mint/run/core/minio-py/tests.py\", line 1355, in test_presigned_get_object_expiry_5sec\n    raise Exception(err)\nException: AccessDenied: message: Access Denied\n",
  "status": "FAIL",
  "name": "minio-py:test_presigned_get_object_expiry_5sec",
  "message": "AccessDenied: message: Access Denied"
}

Executed 11 out of 14 tests successfully.
```
<a name="c1ef4a56-0b12-49a8-b0b0-bda350348436"></a>
### 8254-625c11d/mint-compression-dist-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.54:31359
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 77bb5c29c0db:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 1 seconds
(2/14) Running aws-sdk-java tests ... done in 1 seconds
(3/14) Running aws-sdk-php tests ... done in 43 seconds
(4/14) Running aws-sdk-ruby tests ... done in 2 seconds
(5/14) Running awscli tests ... done in 2 minutes and 5 seconds
(6/14) Running healthcheck tests ... done in 0 seconds
(7/14) Running mc tests ... done in 1 minutes and 0 seconds
(8/14) Running minio-dotnet tests ... done in 37 seconds
(9/14) Running minio-go tests ... done in 1 minutes and 15 seconds
(10/14) Running minio-java tests ... done in 50 seconds
(11/14) Running minio-js tests ... FAILED in 4 seconds
{
  "name": "minio-js",
  "function": "\"after all\" hook in \"functional tests\"",
  "duration": 13,
  "status": "FAIL",
  "error": "S3Error: The bucket you tried to delete is not empty at Object.parseError (node_modules/minio/dist/main/xml-parsers.js:83:11) at /mint/run/core/minio-js/node_modules/minio/dist/main/transformers.js:153:22 at DestroyableTransform._flush (node_modules/minio/dist/main/transformers.js:77:10) at DestroyableTransform.prefinish (node_modules/readable-stream/lib/_stream_transform.js:129:10) at prefinish (node_modules/readable-stream/lib/_stream_writable.js:607:14) at finishMaybe (node_modules/readable-stream/lib/_stream_writable.js:616:5) at endWritable (node_modules/readable-stream/lib/_stream_writable.js:629:3) at DestroyableTransform.Writable.end (node_modules/readable-stream/lib/_stream_writable.js:567:22) at IncomingMessage.onend (_stream_readable.js:514:10) at endReadableNT (_stream_readable.js:978:12) at _combinedTickCallback (internal/process/next_tick.js:80:11) at process._tickCallback (internal/process/next_tick.js:104:9)"
}

Executed 10 out of 14 tests successfully.
```
<a name="4202e1a7-df1e-4bb7-9659-aba6e7014e8c"></a>
### 8254-625c11d/mint-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.51:30895
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp dd43b0900cf5:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 0 seconds
(2/14) Running aws-sdk-java tests ... done in 1 seconds
(3/14) Running aws-sdk-php tests ... done in 41 seconds
(4/14) Running aws-sdk-ruby tests ... done in 2 seconds
(5/14) Running awscli tests ... done in 1 minutes and 1 seconds
(6/14) Running healthcheck tests ... done in 0 seconds
(7/14) Running mc tests ... done in 50 seconds
(8/14) Running minio-dotnet tests ... done in 25 seconds
(9/14) Running minio-go tests ... done in 1 minutes and 18 seconds
(10/14) Running minio-java tests ... done in 19 seconds
(11/14) Running minio-js tests ... FAILED in 17 seconds
{
  "name": "minio-js",
  "function": "\"after all\" hook in \"functional tests\"",
  "duration": 6,
  "status": "FAIL",
  "error": "S3Error: The bucket you tried to delete is not empty at Object.parseError (node_modules/minio/dist/main/xml-parsers.js:83:11) at /mint/run/core/minio-js/node_modules/minio/dist/main/transformers.js:153:22 at DestroyableTransform._flush (node_modules/minio/dist/main/transformers.js:77:10) at DestroyableTransform.prefinish (node_modules/readable-stream/lib/_stream_transform.js:129:10) at prefinish (node_modules/readable-stream/lib/_stream_writable.js:607:14) at finishMaybe (node_modules/readable-stream/lib/_stream_writable.js:616:5) at endWritable (node_modules/readable-stream/lib/_stream_writable.js:629:3) at DestroyableTransform.Writable.end (node_modules/readable-stream/lib/_stream_writable.js:567:22) at IncomingMessage.onend (_stream_readable.js:514:10) at endReadableNT (_stream_readable.js:978:12) at _combinedTickCallback (internal/process/next_tick.js:80:11) at process._tickCallback (internal/process/next_tick.js:104:9)"
}

Executed 10 out of 14 tests successfully.
```

File: cmd/gateway/hdfs/gateway-hdfs.go [hunk 1]
```diff
@@ -507,12 +507,29 @@ func (n *hdfsObjects) GetObject(ctx context.Context, bucket, key string, startOf
 	return hdfsToObjectErr(ctx, err, bucket, key)
 }
 
+func (n *hdfsObjects) isObjectDir(bucket, object string) bool {
```
Comment (kannappanr) [inline cmd/gateway/hdfs/gateway-hdfs.go]: Is `isObjectEmptyDir` a better name?

File: .travis.yml [hunk 2]
```diff
@@ -56,6 +56,3 @@ before_script:
 
 before_install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then nvm install 11.10.1 ; fi
-
-after_success:
```
Comment (vadmeste) [inline .travis.yml:60]: Just to make sure if this deletion is not a typo since you didn't mention it in the commit

File: cmd/gateway/hdfs/gateway-hdfs.go [hunk 3]
```diff
@@ -507,12 +507,29 @@ func (n *hdfsObjects) GetObject(ctx context.Context, bucket, key string, startOf
...
+	f, err := n.clnt.Open(minio.PathJoin(hdfsSeparator, bucket, object))
+	if err != nil {
```
Comment (vadmeste) [inline cmd/gateway/hdfs/gateway-hdfs.go:512]: I really see it is better if we return an error with the bool, and check the error to return a correct {true,false} with a nil error.

The reason is that we don't know what is the consequence (disastrous?) if we return "false" when there is a network error for example.

**Review by vadmeste — COMMENTED** [review]
Some comments

File: .travis.yml (hunk 2 above)
Comment (harshavardhana) [reply .travis.yml:60]: No officially removing codecov on purpose.

File: cmd/gateway/hdfs/gateway-hdfs.go (hunk 3 above)
Comment (harshavardhana) [reply cmd/gateway/hdfs/gateway-hdfs.go:512]: We don't need to be so conclusively sure.  We validate the bucket before already and it is highly unlikely that there will be a network issue as such.

File: cmd/gateway/hdfs/gateway-hdfs.go (hunk 1 above)
Comment (harshavardhana) [reply cmd/gateway/hdfs/gateway-hdfs.go]: No the idea is that it's a dir only if it is empty so calling it empty dir is not useful.

**Review by kannappanr — APPROVED** [review]
LGTM

File: cmd/gateway/hdfs/gateway-hdfs.go (hunk 3 above)
Comment (vadmeste) [reply cmd/gateway/hdfs/gateway-hdfs.go:512]: > We don't need to be so conclusively sure. We validate the bucket before already and it is highly unlikely that there will be a network issue as such.

Can we at least log this error when the error is unusual ? At least we can avoid rare issues that we don't understand in the future.

**Comment by minio-ops** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-compression-xl.sh | :heavy_check_mark: |
| mint-xl.sh | :heavy_check_mark: |
| mint-compression-dist-xl.sh | :heavy_check_mark: |
| mint-compression-fs.sh | :heavy_check_mark: |
| mint-worm.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :x: [more...](#9a9a9438-6e10-4d30-bef5-00e24db0864c) |
| mint-dist-xl.sh | :x: [more...](#79625b60-a2fb-400a-aed9-a6afa6da9c94) |
<a name="9a9a9438-6e10-4d30-bef5-00e24db0864c"></a>
### 8254-b1a7d24/mint-large-bucket.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.53:31580
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp c4605fa409fe:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 2 seconds
(2/14) Running aws-sdk-java tests ... done in 2 seconds
(3/14) Running aws-sdk-php tests ... done in 48 seconds
(4/14) Running aws-sdk-ruby tests ... done in 16 seconds
(5/14) Running awscli tests ... done in 1 minutes and 30 seconds
(6/14) Running healthcheck tests ... done in 0 seconds
(7/14) Running mc tests ... done in 1 minutes and 56 seconds
(8/14) Running minio-dotnet tests ... done in 1 minutes and 54 seconds
(9/14) Running minio-go tests ... FAILED in 8 minutes and 33 seconds
{
  "args": {},
  "duration": 73871,
  "error": "The specified key does not exist.",
  "function": "testStorageClassMetadataCopyObject()",
  "message": "Stat failed",
  "name": "minio-go: testStorageClassMetadataCopyObject",
  "status": "FAIL"
}

Executed 8 out of 14 tests successfully.
```
<a name="79625b60-a2fb-400a-aed9-a6afa6da9c94"></a>
### 8254-b1a7d24/mint-dist-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.51:31508
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 25bd942d030e:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 0 seconds
(2/14) Running aws-sdk-java tests ... done in 1 seconds
(3/14) Running aws-sdk-php tests ... done in 44 seconds
(4/14) Running aws-sdk-ruby tests ... done in 4 seconds
(5/14) Running awscli tests ... done in 2 minutes and 11 seconds
(6/14) Running healthcheck tests ... done in 0 seconds
(7/14) Running mc tests ... done in 1 minutes and 17 seconds
(8/14) Running minio-dotnet tests ... done in 42 seconds
(9/14) Running minio-go tests ... done in 1 minutes and 23 seconds
(10/14) Running minio-java tests ... done in 1 minutes and 55 seconds
(11/14) Running minio-js tests ... done in 57 seconds
(12/14) Running minio-py tests ... FAILED in 2 minutes and 55 seconds
{
  "duration": 94,
  "function": "presigned_get_object(bucket_name, object_name, expires, response_headers, request_date)",
  "status": "FAIL",
  "error": "Traceback (most recent call last):\n  File \"/mint/run/core/minio-py/tests.py\", line 1341, in test_presigned_get_object_expiry_5sec\n    object_name).get_exception()\nminio.error.AccessDenied: AccessDenied: message: Access Denied\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"/mint/run/core/minio-py/tests.py\", line 2036, in main\n    test_presigned_get_object_expiry_5sec(client, log_output)\n  File \"/mint/run/core/minio-py/tests.py\", line 1355, in test_presigned_get_object_expiry_5sec\n    raise Exception(err)\nException: AccessDenied: message: Access Denied\n",
  "message": "AccessDenied: message: Access Denied",
  "args": {
    "response.reason": "Forbidden",
    "response._body": "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<Error><Code>AccessDenied</Code><Message>Request has expired</Message><Key>bbe2e047-b548-4c1c-a4ea-46fe3c675d91</Key><BucketName>minio-py-test-7087518a-0ed2-4f3b-b0ea-85531eb9c280</BucketName><Resource>/minio-py-test-7087518a-0ed2-4f3b-b0ea-85531eb9c280/bbe2e047-b548-4c1c-a4ea-46fe3c675d91</Resource><RequestId>15C54A33CE3778A7</RequestId><HostId>9a349f4d-8549-4057-b052-c7ee43f2a762</HostId></Error>",
    "presigned_get_object_url": "http://72.28.97.51:31508/minio-py-test-7087518a-0ed2-4f3b-b0ea-85531eb9c280/bbe2e047-b548-4c1c-a4ea-46fe3c675d91?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=minio%2F20190917%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20190917T173346Z&X-Amz-Expires=5&X-Amz-SignedHeaders=host&X-Amz-Signature=c31384fbf217ed94259a2e9b6a75e652be0dd4981973fddce256ed2a801c84bb",
    "object_name": "bbe2e047-b548-4c1c-a4ea-46fe3c675d91",
    "response.headers": "{\"_container\": {\"accept-ranges\": [\"Accept-Ranges\", \"bytes\"], \"content-length\": [\"Content-Length\", \"440\"], \"content-security-policy\": [\"Content-Security-Policy\", \"block-all-mixed-content\"], \"content-type\": [\"Content-Type\", \"application/xml\"], \"server\": [\"Server\", \"MinIO/DEVELOPMENT.2019-09-17T17-08-45Z\"], \"vary\": [\"Vary\", \"Origin\"], \"x-amz-request-id\": [\"X-Amz-Request-Id\", \"15C54A33CE3778A7\"], \"x-xss-protection\": [\"X-Xss-Protection\", \"1; mode=block\"], \"date\": [\"Date\", \"Tue, 17 Sep 2019 17:33:51 GMT\"]}}",
    "response.status": 403,
    "bucket_name": "minio-py-test-7087518a-0ed2-4f3b-b0ea-85531eb9c280"
  },
  "name": "minio-py:test_presigned_get_object_expiry_5sec"
}

Executed 11 out of 14 tests successfully.
```

File: cmd/gateway/hdfs/gateway-hdfs.go (hunk 3 above)
Comment (harshavardhana) [reply cmd/gateway/hdfs/gateway-hdfs.go:512]: This is done

**Comment by harshavardhana** [comment]
ping @vadmeste

**Review by vadmeste — APPROVED** [review]
LGTM
