### PR TITLE
replication: Lock object while replicating

### LINKED ISSUE #13013: Server-Side Bucket Replication duplicates files on replica
Files uploaded to master node are twice as size on the disk on a replica node
## Expected Behavior

I expect that the file is replicated only once and is equal in total size on disk to the file on master
## Current Behavior

Uploaded to master file has duplicated size on disk on replica node. 

Master

du --time -sh /mnt/minio/data0/test/1gb/*
342M	2021-08-19 15:22	/mnt/minio/data0/test/1gb/08b78c82-683a-4fcc-90fd-4103b51c495a
4.0K	2021-08-19 15:22	/mnt/minio/data0/test/1gb/xl.meta

Replica

du --time -sh /mnt/minio/data0/test/1gb/*
342M	2021-08-19 15:22	/mnt/minio/data0/test/1gb/18d41f86-630d-4cbe-9151-10ff320acf65
342M	2021-08-19 15:22	/mnt/minio/data0/test/1gb/6e670fc8-95e6-4287-9df7-33e1414f5748
4.0K	2021-08-19 15:22	/mnt/minio/data0/test/1gb/xl.meta
## Possible Solution

none
## Steps to Reproduce (for bugs)

1. Upload file to master with replication enabled
2.  Check the minio datadir on replica

We've run tests with different size of files.

Each file we uploaded 1000 times to check for errors

Results

30mb file - no duplicates found 

40mb file - 1 duplicate

50mb file - 1 duplicate

60mb file - 5 duplicates

200mb file - 12 duplicates

1gb file - 98 duplicates

2gb file - 52 duplicates 

## Context

We can not properly esimate the required disk space
## Your Environment

* Version used (`minio --version`): RELEASE.2021-07-22T05-23-32Z
* Server setup and configuration: 
4 CPU 8gb RAM SSD disks 10Gib network
no bandwidth limitation on replication
* Operating System and version (`uname -a`): CentOS 8

### PR DESCRIPTION
**Pull request by klauspost**
## Description

Introduce a replication lock that will ensure that only one replication operation will run for any given object at any time.

Fixes #13013

Probably introduced after we only hold read locks on objects (which is correct).

## How to test this PR?

Upload big objects, observe destination replication.

## Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)

### CODE REVIEW

**Comment by minio-trusted** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-s3.sh | :heavy_check_mark: |
| mint-erasure.sh | :heavy_check_mark: |
| mint-dist-erasure.sh | :heavy_check_mark: |
| mint-zoned.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-compress-encrypt-dist-erasure.sh | :heavy_check_mark: |
Deleting image on docker hub
Deleting image locally

File: cmd/bucket-replication.go [hunk 1]
```diff
@@ -316,6 +316,28 @@ func replicateDelete(ctx context.Context, dobj DeletedObjectReplicationInfo, obj
 		return
 	}
 
+	// Lock the object name before starting replication operation.
+	// Use separate lock that doesn't collide with regular objects.
+	lk := objectAPI.NewNSLock(bucket, "/[replicate]/"+dobj.ObjectName)
```
Comment (harshavardhana) [inline cmd/bucket-replication.go:321]: This lock will collide with situations where some uploads this exact object name, to avoid this kind of abuse we should move the lock to `minioMetaBucket` instead

File: cmd/bucket-replication.go [hunk 2]
```diff
@@ -669,6 +691,24 @@ func replicateObject(ctx context.Context, ri ReplicateObjectInfo, objectAPI Obje
 		})
 		return
 	}
+
+	// Lock the object name before starting replication.
+	// Use separate lock that doesn't collide with regular objects.
+	lk := objectAPI.NewNSLock(bucket, "/[replicate]/"+object)
```
Comment (harshavardhana) [inline cmd/bucket-replication.go:697]: Same as above

**Review by harshavardhana — CHANGES_REQUESTED** [review]

File: cmd/bucket-replication.go (hunk 1 above)
Comment (klauspost) [reply cmd/bucket-replication.go:321]: @harshavardhana Objects cannot start with `/` which is why I choose this schema..

Comment (harshavardhana) [reply cmd/bucket-replication.go:321]: Yes perhaps we can live with it..

**Review by harshavardhana — APPROVED** [review]

**Review by poornas — APPROVED** [review]
