### PR TITLE
api: Handle content-length-range policy properly.

### LINKED ISSUE #3295: minio does not honor content range in presigned post policy
Below is the code snippet from minio-java functional test doing presigned post policy.  The code sets allowed content range from 1 MB to 4 MB and tries to upload 3 MB data using presigned post policy.

```java
  public static void presignedPostPolicy_test() throws Exception {
    System.out.println("Test: presignedPostPolicy(PostPolicy policy)");
    String fileName = createFile(3 * MB);
    PostPolicy policy = new PostPolicy(bucketName, fileName, DateTime.now().plusDays(7));
    policy.setContentRange(1 * MB, 4 * MB);
    Map<String, String> formData = client.presignedPostPolicy(policy);

    MultipartBuilder multipartBuilder = new MultipartBuilder();
    multipartBuilder.type(MultipartBuilder.FORM);
    for (Map.Entry<String, String> entry : formData.entrySet()) {
      multipartBuilder.addFormDataPart(entry.getKey(), entry.getValue());
    }
    multipartBuilder.addFormDataPart("file", fileName, RequestBody.create(null, new File(fileName)));

    Request.Builder requestBuilder = new Request.Builder();
    Request request = requestBuilder.url(endpoint + "/" + bucketName).post(multipartBuilder.build()).build();
    OkHttpClient transport = new OkHttpClient();
    Response response = transport.newCall(request).execute();

    if (response != null) {
      if (!response.isSuccessful()) {
        String errorXml = "";

        // read entire body stream to string.
        Scanner scanner = new java.util.Scanner(response.body().charStream()).useDelimiter("\\A");
        if (scanner.hasNext()) {
          errorXml = scanner.next();
        }

        throw new Exception("[FAILED] Test: presignedPostPolicy(PostPolicy policy)"
                            + ", Response: " + response
                            + ", Error: " + errorXml);
      }
    } else {
      throw new Exception("[FAILED] Test: presignedPostPolicy(PostPolicy policy)"
                          + ", Error: <No response from server>");
    }

    Files.delete(Paths.get(fileName));
    client.removeObject(bucketName, fileName);
  }
```

Below is request/response
```
Request{method=POST, url=http://192.168.1.107:9000/minio-java-test-2cvv5t6, tag=null}

Response{protocol=http/1.1, code=400, message=Bad Request, url=http://192.168.1.107:9000/minio-java-test-2cvv5t6}

<?xml version="1.0" encoding="UTF-8"?>
<Error><Code>EntityTooLarge</Code><Message>Your proposed upload exceeds the maximum allowed object size.</Message><Key></Key><BucketName></BucketName><Resource>/minio-java-test-2cvv5t6</Resource><RequestId>3L137</RequestId><HostId>3L137</HostId></Error>
	at FunctionalTest.presignedPostPolicy_test(FunctionalTest.java:711)
	at FunctionalTest.main(FunctionalTest.java:811)
```

## Expected Behavior
Content range should be honored

## Current Behavior
Returns `EntityTooLarge`

## Steps to Reproduce (for bugs)
1. start minio server
2. run minio-java functional test

## Your Environment
minio version
```
Version: 2016-11-20T17:56:32Z
Release-Tag: DEVELOPMENT.2016-11-20T17-56-32Z
Commit-ID: 2c3a2241e773b27862334441da44df983d1731da
```

### PR DESCRIPTION
**Pull request by harshavardhana**
## Description
content-length-range policy in postPolicy API was
not working properly handle it. The reflection
strategy used has changed in recent version of Go.
Any free form interface{} of any integer is treated
as `float64` this caused a bug where content-length-range
parsing failed to provide any value.

## Motivation and Context
Fixes #3295 

## How Has This Been Tested?
Using the following program

```go
package main

import (
	"bytes"
	"fmt"
	"io"
	"log"
	"mime/multipart"
	"net/http"
	"net/http/httputil"
	"os"
	"time"

	"github.com/minio/minio-go"
)

func main() {
	// Note: YOUR-ACCESSKEYID, YOUR-SECRETACCESSKEY, my-bucketname and my-objectname
	// are dummy values, please replace them with original values.

	// Requests are always secure (HTTPS) by default. Set secure=false to enable insecure (HTTP) access.
	// This boolean value is the last argument for New().

	// New returns an Amazon S3 compatible client object. API compatibility (v2 or v4) is automatically
	// determined based on the Endpoint value.
	s3Client, err := minio.New("localhost:9000", "USWUXHGYZQYFYFFIT3RE", "MOJRH0mkL1IPauahWITSVvyDrQbEEIwljvmxdq03", false)
	if err != nil {
		log.Fatalln(err)
	}

	policy := minio.NewPostPolicy()
	policy.SetBucket("testbucket")
	policy.SetKey("works/for/me")
	// Expires in 10 days.
	policy.SetExpires(time.Now().UTC().AddDate(0, 0, 10))
	policy.SetContentLengthRange(1*1024*1024, 4*1024*1024)

	// Returns form data for POST form request.
	url, formData, err := s3Client.PresignedPostPolicy(policy)
	if err != nil {
		log.Fatalln(err)
	}
	var buf bytes.Buffer
	writer := multipart.NewWriter(&buf)
	for k, v := range formData {
		writer.WriteField(k, v)
	}
	f, err := os.Open("/etc/issue")
	if err != nil {
		log.Fatalln(err)
	}
	defer f.Close()
	w, err := writer.CreateFormFile("file", "/etc/issue")
	if err != nil {
		log.Fatalln(err)
	}
	_, err = io.Copy(w, f)
	if err != nil {
		log.Fatalln(err)
	}
	writer.Close()

	res, err := http.Post(url.String(), writer.FormDataContentType(), bytes.NewReader(buf.Bytes()))
	if err != nil {
		log.Fatalln(err)
	}
	dresp, err := httputil.DumpResponse(res, true)
	if err != nil {
		log.Fatalln(err)
	}
	fmt.Println(string(dresp))
}
```

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Review by vadmeste — APPROVED** [review]

**Comment by harshavardhana** [comment]
ping @krishnasrinivas - can you review this?

**Comment by krishnasrinivas** [comment]
@harshavardhana checking

File: cmd/bucket-handlers.go [hunk 1]
```diff
@@ -489,6 +501,7 @@ func (api objectAPIHandlers) PostPolicyBucketHandler(w http.ResponseWriter, r *h
 	objInfo, err := objectAPI.PutObject(bucket, object, -1, fileBody, metadata, sha256sum)
 	if err != nil {
 		errorIf(err, "Unable to create object.")
+		err = errorCause(err)
```
Comment (krishnasrinivas) [inline cmd/bucket-handlers.go]: errorCause here is not needed as toAPIErrorCode does it automatically

Comment (harshavardhana) [reply cmd/bucket-handlers.go]: Done

File: cmd/object-utils.go [hunk 2]
```diff
@@ -163,28 +163,27 @@ func (d byBucketName) Len() int           { return len(d) }
...
-type limitedReader struct {
-	R io.Reader // underlying reader
-	M int64     // min bytes remaining
-	N int64     // max bytes remaining
+// rangeReader returns a Reader that reads from r
+// but returns error after Max bytes read as errDataTooLarge.
+// but returns error if reader exits before reading Min bytes
+// errDataTooSmall.
+type rangeReader struct {
+	bucket, object string
```
Comment (krishnasrinivas) [inline cmd/object-utils.go]: bucket, object here is not needed.

Because it is added (rightly) here:

```
                bytesWritten, err = fsCreateFile(fs.storage, teeReader, buf, minioMetaTmpBucket, tempOb\
j)                                                                                                      
                if err != nil {                                                                         
                        fs.storage.DeleteFile(minioMetaTmpBucket, tempObj)                              
                        errorIf(err, "Failed to create object %s/%s", bucket, object)                   
                        return ObjectInfo{}, toObjectErr(err, bucket, object)                           
                }
```

rangeReader can be a primitive without knowledge of bucket/object

File: cmd/object-utils.go [hunk 3]
```diff
@@ -163,28 +163,27 @@ func (d byBucketName) Len() int           { return len(d) }
...
-	l.M -= int64(n)
-	if l.N < 0 {
+func (l *rangeReader) Read(p []byte) (n int, err error) {
+	n, err = l.Reader.Read(p)
+	l.Max -= int64(n)
+	l.Min -= int64(n)
+	if l.Max < 0 {
 		// If more data is available than what is expected we return error.
-		return 0, errDataTooLarge
+		return 0, toObjectErr(errDataTooLarge, l.bucket, l.object)
```
Comment (krishnasrinivas) [inline cmd/object-utils.go]: just errDataTooLarge should be returned here (similar to how streaming v4 returns just errSignatureMismatch without bucket/object info) the object layer will take care of bucket/object related info

Comment (harshavardhana) [reply cmd/object-utils.go]: done

**Review by krishnasrinivas — APPROVED** [review]
