### PR TITLE
Fix regression from range GET proxying #14345

### LINKED ISSUE #14531: HeadObject causing RequestedRangeNotSatisfiable if key does not exist
As soon as replication on a bucket is enabled and a you try to perform a `HeadObject` a RequestedRangeNotSatisfiable error is returned if the key does not exist.

## Expected Behavior
```
{
  AcceptRanges: "bytes",
  CacheControl: "private",
  ContentLength: 0
} NotFound: Not Found
	status code: 404, request id: 16DB6D40A1E7D5BB, host id: 
```

## Current Behavior
```
{
  AcceptRanges: "bytes",
  ContentLength: 0
} RequestedRangeNotSatisfiable: Requested Range Not Satisfiable
	status code: 416, request id: 16DB6CB10E18FA61, host id: 
```

## Possible Solution
IDK

## Steps to Reproduce (for bugs)
1. Create 2 MinIO cluster in distributed mode
2. Create a bucket and enable versioning and replcation
3. Run the following code:
```
package main

import (
	"fmt"

	"github.com/aws/aws-sdk-go/aws"
	"github.com/aws/aws-sdk-go/aws/credentials"
	"github.com/aws/aws-sdk-go/aws/session"
	"github.com/aws/aws-sdk-go/service/s3"
)

func main() {
	sess := session.Must(session.NewSession())
	svc := s3.New(sess, &aws.Config{
		Endpoint:         aws.String("https://s3-minio"),
		Region:           aws.String("minio"),
		DisableSSL:       aws.Bool(true),
		S3ForcePathStyle: aws.Bool(true),
		Credentials:      credentials.NewStaticCredentials("minioadmin", "minioadmin", ""),
	})

	req := &s3.HeadObjectInput{
		Bucket: aws.String("test"),
		Key:    aws.String("//foo//bar"),
	}

	fmt.Println(svc.HeadObject(req))
}

```

## Context
This issue causes https://github.com/vmware-tanzu/velero/issues/4734

## Your Environment
* Version used (`minio --version`): RELEASE.2022-03-08T22-28-51Z
* Operating System and version (`uname -a`): Kubernetes v1.21.6+bb8d50a (OpenShift 4.8.28)

### PR DESCRIPTION
**Pull request by poornas**
Fixes: #14531

## How to test this PR?
As reported in issue above.

## Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Optimization (provides speedup with no functional changes)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [ ] Fixes a regression (If yes, please add `commit-id` or `PR #` here)
- [ ] Documentation updated
- [x] Unit tests added/updated

### CODE REVIEW

**Review by harshavardhana — APPROVED** [review]

**Comment by harshavardhana** [comment]
lets add a unit test here @poornas

**Comment by minio-trusted** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-s3.sh | :heavy_check_mark: |
| mint-erasure.sh | :heavy_check_mark: |
| mint-dist-erasure.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-compress-encrypt-dist-erasure.sh | :heavy_check_mark: |
| mint-pools.sh | :heavy_check_mark: |
Deleting image on docker hub
Deleting image locally

**Comment by minio-trusted** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-s3.sh | :heavy_check_mark: |
| mint-erasure.sh | :heavy_check_mark: |
| mint-dist-erasure.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-compress-encrypt-dist-erasure.sh | :heavy_check_mark: |
| mint-pools.sh | :heavy_check_mark: |
Deleting image on docker hub
Deleting image locally

**Comment by minio-trusted** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-s3.sh | :heavy_check_mark: |
| mint-erasure.sh | :heavy_check_mark: |
| mint-dist-erasure.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-compress-encrypt-dist-erasure.sh | :heavy_check_mark: |
| mint-pools.sh | :heavy_check_mark: |
Deleting image on docker hub
Deleting image locally

File: cmd/object-api-errors.go [hunk 1]
```diff
@@ -703,5 +703,6 @@ func isErrMethodNotAllowed(err error) bool {
 }
 
 func isErrInvalidRange(err error) bool {
-	return errors.As(err, &errInvalidRange)
+	_, ok := err.(InvalidRange)
```
Comment (snorwin) [inline cmd/object-api-errors.go:706]: @poornas would it be worth to refactor all `errors.As(err, ...)` using proper type casting in order to prevent similar issues in the future?

Comment (harshavardhana) [reply cmd/object-api-errors.go:706]: @snorwin - the regression is not because of incorrect usage of errors.As() but lack of unit tests - which is added in this PR.

Comment (snorwin) [reply cmd/object-api-errors.go:706]: thanks for the clarification
