### PR TITLE
XL: Remove usage of reduceErr and make it isQuorum verification.

### LINKED ISSUE #1908: reduceError() incorrect reduction
reduceErrors() returns nil when it should return an error.
For example: on 4x4 if fileNotFoundCount is 3 and diskNotFoundCount is 2, reduceError() should return `error` but it returns `nil`

### PR DESCRIPTION
**Pull request by harshavardhana**
Fixes #1908

### CODE REVIEW

File: xl-v1-utils.go [hunk 1]
```diff
@@ -24,6 +24,72 @@ import (
...
+	if fileNotFoundCount+diskNotFoundCount > len(errs)-quorumCount {
+		return errFileNotFound
+	} else if fileLongNameCount+diskNotFoundCount > len(errs)-quorumCount {
+		return errFileNameTooLong
+	} else if volumeNotFoundCount+diskNotFoundCount > len(errs)-quorumCount {
+		return errVolumeNotFound
+	} else if fileAccessDeniedCount+diskNotFoundCount > len(errs)-quorumCount {
+		return errFileAccessDenied
+	}
+	return nil
```
Comment (krishnasrinivas) [inline xl-v1-utils.go]: still does not cover all cases, for example in 4x4 if fileNotFoundCount is 3 and volumeNotFoundCount is 2, reduceError() should return error but it returns nil

File: posix.go [hunk 2]
```diff
@@ -458,11 +458,9 @@ func (s posix) AppendFile(volume, path string, buf []byte) (n int64, err error)
 		}
 		return 0, err
 	}
-	if err = checkDiskFree(s.diskPath, s.minFreeDisk); err != nil {
-		return 0, err
-	}
```
Comment (krishnasrinivas) [inline posix.go:463]: checkDiskFree() check is not necessary?

File: posix.go [hunk 3]
```diff
@@ -458,11 +458,9 @@ func (s posix) AppendFile(volume, path string, buf []byte) (n int64, err error)
...
 	filePath := pathJoin(volumeDir, path)
-	if err = checkPathLength(filePath); err != nil {
+	err = checkPathLength(filePath)
+	if err != nil {
 		return 0, err
```
Comment (krishnasrinivas) [inline posix.go:463]: how come you broke `if err = checkPathLength(filePath); err != nil {}` style to this style? does it give any advantage?

File: xl-v1-healing.go [hunk 4]
```diff
@@ -7,8 +23,7 @@ import (
 )
 
 // Get the highest integer from a given integer slice.
-func highestInt(intSlice []int64) (highestInteger int64) {
-	highestInteger = int64(1)
+func highestInt(intSlice []int64, highestInt int64) (highestInteger int64) {
```
Comment (krishnasrinivas) [inline xl-v1-healing.go:26]: `highestInt int64` is not getting used in the function?

**Comment by harshavardhana** [comment]
> how come you broke if err = checkPathLength(filePath); err != nil {} style to this style? does it give any advantage?

Ah must be related to some debugging which i was doing, will need to revert it back.

**Comment by harshavardhana** [comment]
> checkDiskFree() check is not necessary?

Nope looks like it was already there, it was redundant.

**Comment by harshavardhana** [comment]
@krishnasrinivas were you able to review?

**Comment by krishnasrinivas** [comment]
> @krishnasrinivas were you able to review?

will review now

File: xl-v1-utils.go [hunk 5]
```diff
@@ -24,6 +24,33 @@ import (
...
+		if err == errDiskNotFound {
+			diskNotFoundCount++
+		}
+	}
+	if diskNotFoundCount > len(errs)-minQuorumCount {
+		return false
+	}
+	return true
+}
+
```
Comment (krishnasrinivas) [inline xl-v1-utils.go:38]: logic based on diskFoundCount instead of diskNotFoundCount is more readable, like:

```
func isQuorum(errs []error, minQuorumCount int) bool {
        var diskFoundCount int
        for _, err := range errs {
                if err != errDiskNotFound {
                        diskFoundCount++
                }
        }
        return diskFoundCount >= minQuorumCount
}
```

File: xl-v1-bucket.go [hunk 6]
```diff
@@ -63,27 +79,16 @@ func (xl xlObjects) MakeBucket(bucket string) error {
...
-	if volumeExistsErrCnt > len(xl.storageDisks)-xl.readQuorum {
-		return toObjectErr(errVolumeExists, bucket)
-	} else if createVolErr > len(xl.storageDisks)-xl.writeQuorum {
-		// Return errXLWriteQuorum if errors were more than allowed write quorum.
-		return toObjectErr(errXLWriteQuorum, bucket)
+	for _, err := range dErrs {
+		if err != nil && err != errDiskNotFound {
+			xl.undoMakeBucket(bucket)
+			return toObjectErr(err, bucket)
+		}
```
Comment (krishnasrinivas) [inline xl-v1-bucket.go:79]: this has undesired consequence:
1) `mc mb myminio/newbucket` - creates newbucket
2) again do `mc mb myminio/newbucket` - deletes the bucket created in step-1

File: xl-v1-metadata.go [hunk 7]
```diff
@@ -259,39 +282,18 @@ func (xl xlObjects) renameXLMetadata(srcBucket, srcPrefix, dstBucket, dstPrefix
...
-	var errCount = 0
-	for _, err := range mErrs {
-		if err == nil {
-			continue
+	if !isQuorum(mErrs, xl.writeQuorum) {
+		if isQuorum(mErrs, xl.readQuorum) {
+			return nil
 		}
-		errCount++
+		xl.undoRenameXLMetadata(srcBucket, srcPrefix, dstBucket, dstPrefix, mErrs)
```
Comment (krishnasrinivas) [inline xl-v1-metadata.go]: `renameXLMetadata()` source is always a tmp location so undoRenameXLMetadata to rename it back to a tmp file will not be useful

File: xl-v1-metadata.go [hunk 8]
```diff
@@ -259,39 +282,18 @@ func (xl xlObjects) renameXLMetadata(srcBucket, srcPrefix, dstBucket, dstPrefix
...
-			go func(index int, disk StorageAPI) {
-				defer wg.Done()
-				if mErrs[index] != nil {
-					return
-				}
-				_ = disk.RenameFile(dstBucket, dstJSONFile, srcBucket, srcJSONFile)
-			}(index, disk)
+	for _, err := range mErrs {
+		if err != nil && err != errDiskNotFound {
+			xl.undoRenameXLMetadata(srcBucket, srcPrefix, dstBucket, dstPrefix, mErrs)
```
Comment (krishnasrinivas) [inline xl-v1-metadata.go]: doing undoRenameXLMetadata during complete-multipart-upload will be harmful because it will remove xl.json from the .minio/multipart/object/ directory

File: xl-v1-metadata.go [hunk 9]
```diff
@@ -259,39 +282,18 @@ func (xl xlObjects) renameXLMetadata(srcBucket, srcPrefix, dstBucket, dstPrefix
...
+			return err
```
Comment (krishnasrinivas) [inline xl-v1-metadata.go]: returning `err` without doing `undoRenameXLMetadata()` would be good

File: xl-v1-metadata.go [hunk 10]
```diff
@@ -352,38 +375,23 @@ func (xl xlObjects) writeUniqueXLMetadata(bucket, prefix string, xlMetas []xlMet
...
-			}(index, disk)
-		}
-		wg.Wait()
+		xl.deleteAllXLMetadata(bucket, prefix, mErrs)
 		return errXLWriteQuorum
 	}
+
+	for _, err := range mErrs {
+		if err != nil && err != errDiskNotFound {
+			xl.deleteAllXLMetadata(bucket, prefix, mErrs)
```
Comment (krishnasrinivas) [inline xl-v1-metadata.go]: since `writeUniqueXLMetadata` writes to the tmp location doing `xl.deleteAllXLMetadata` is not needed

File: xl-v1-metadata.go [hunk 11]
```diff
@@ -417,37 +425,21 @@ func (xl xlObjects) writeSameXLMetadata(bucket, prefix string, xlMeta xlMetaV1)
...
```
Comment (krishnasrinivas) [inline xl-v1-metadata.go]: since `writeUniqueXLMetadata` writes to the tmp location doing `xl.deleteAllXLMetadata` is not needed

BTW is writeSameXLMetadata needed? we can use writeUniqueXLMetadata right?

**Comment by harshavardhana** [comment]
> 2) again do mc mb myminio/newbucket - deletes the bucket created in step-1

Ah yes need to ignore 'errVolumeExists'

File: xl-v1-metadata.go (hunk 10 above)
Comment (harshavardhana) [inline xl-v1-metadata.go]: > since writeUniqueXLMetadata writes to the tmp location doing xl.deleteAllXLMetadata is not needed

The function itself has no such awareness of tmp location so that is why it is done this way.

**Comment by harshavardhana** [comment]
> BTW is writeSameXLMetadata needed? we can use writeUniqueXLMetadata right?

Both have different purpose, in one case xlMetaV1 is different for each index whereas writeSameXL writes same xlMetaV1 across all disks.

File: xl-v1-utils.go (hunk 5 above)
Comment (harshavardhana) [inline xl-v1-utils.go:38]: > logic based on diskFoundCount instead of diskNotFoundCount is more readable, like:
> 
> func isQuorum(errs []error, minQuorumCount int) bool {
>         var diskFoundCount int
>         for _, err := range errs {
>                 if err != errDiskNotFound {
>                         diskFoundCount++
>                 }
>         }
>         return diskFoundCount >= minQuorumCount
> }

Makes sense.

File: xl-v1-metadata.go (hunk 7 above)
Comment (harshavardhana) [inline xl-v1-metadata.go]: > renameXLMetadata() source is always a tmp location so undoRenameXLMetadata to rename it back to a tmp file will not be useful

It would be since 'tmp/' location can be cleaned naturally without issues, any dangling files would be an issue to detect and cleanup later.

**Comment by harshavardhana** [comment]
> doing undoRenameXLMetadata during complete-multipart-upload will be harmful because it will remove xl.json from the .minio/multipart/object/ directory

This is only on error when it is necessary, it will only remove the dangling ones since other operations would have naturally failed.

**Comment by harshavardhana** [comment]
> returning err without doing undoRenameXLMetadata() would be good

That would still leave dangling files, since all this operation is based on tmp path. we can't have dangling files on actual namespace. it is okay to rename them back to tmp so that upon server restart atleast we can clean them up.

**Comment by harshavardhana** [comment]
@krishnasrinivas - updated with new changes.

**Comment by krishnasrinivas** [comment]
> @krishnasrinivas - updated with new changes.

checking...

**Comment by krishnasrinivas** [comment]
> > doing undoRenameXLMetadata during complete-multipart-upload will be harmful because it will remove xl.json from the .minio/multipart/object/ directory
> 
> This is only on error when it is necessary, it will only remove the dangling ones since other operations would have naturally failed.

No, here's the situation,
CompleteMultipart would call:
rErr := xl.renameXLMetadata(minioMetaBucket, tempUploadIDPath, minioMetaBucket, uploadIDPath)

here we would already have `uploadIDPath/xl.json` which will be replaced by `tempUploadIDPath/xl.json` but for some reason we do `undoRenameXLMetadata()` it would mean that `uploadIDPath` will not have xl.json at all (the original xl.json would have been replaced)

**Comment by harshavardhana** [comment]
> No, here's the situation,
> CompleteMultipart would call:
> rErr := xl.renameXLMetadata(minioMetaBucket, tempUploadIDPath, minioMetaBucket, uploadIDPath)
> 
> here we would already have uploadIDPath/xl.json which will be replaced by tempUploadIDPath/xl.json but for some reason we do undoRenameXLMetadata() it would mean that uploadIDPath will not have xl.json at all (the original xl.json would have been replaced)

It is a tricky case i agree but leaving a dangling / improper `xl.json` during a quorum failure would be hard to detect, in updated patch renameXLMetadata undo'es the operation only during quorum failure. Any other errors are returned as is.

**Comment by krishnasrinivas** [comment]
> It is a tricky case i agree but leaving a dangling / improper xl.json

it's not dangling right? it would have just replaced previous xl.json

**Comment by harshavardhana** [comment]
> it's not dangling right? it would have just replaced previous xl.json

Now i see, since this renameXL is not used elsewhere this logic doesn't make sense. `xl.json` wouldn't be a dangling one.

**Comment by harshavardhana** [comment]
> Now i see, since this renameXL is not used elsewhere this logic doesn't make sense. xl.json wouldn't be a dangling one.

Also it is not appropriate name for the function, moving it to xl-multipart-common.go

**Comment by harshavardhana** [comment]
Done updated!

**Comment by krishnasrinivas** [comment]
looks good
