### PR TITLE
Fix cache objects on downloads

### LINKED ISSUE #6817: Azure gateway disk cache by download not storing file in cache folder
Setup Azure gateway and disk cache environment attrs. 
Only uploading file will be stored in cache folder. Downloading file won't be stored in cache folder.

## Expected Behavior
Expect doing download on Azure's file will be cached in the cache folder.

## Current Behavior
Upload file will be cached in cache folder.
Download file won't be cached in cache folder.

## Possible Solution
No idea.

## Steps to Reproduce (for bugs)

1. Setup Azure gateway, disk cache mode(A cache folder).
2. Start the server.
3. Download a file from Azure server minio browser.
4. The cache file is not store in the cache folder.

## Context
We are comparing Minio file cache versus ours project.

## Regression
 As @poorna said, seems yes. But I don't have the details.

## Your Environment
Minio RELEASE.2018-11-06T01-01-02Z
OS: Windows 7 x64

### PR DESCRIPTION
**Pull request by poornas**
fixes #6817

## Description

When edge caching is enabled, objects should be cached on Get if not already present. 
## Motivation and Context

fixes #6817 

## Regression
  Yes

Commit e71ef905f9547514d1f2ebf1732be8f2a6e094f7 for PR #6192 
## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added unit tests to cover my changes.
- [ ] I have added/updated functional tests in [mint](https://github.com/minio/mint). (If yes, add `mint` PR # here: )
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by minio-ops** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-tls.sh | :heavy_check_mark: |
| mint-compression-xl.sh | :heavy_check_mark: |
| mint-xl.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-compression-fs.sh | :heavy_check_mark: |
| mint-worm.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-dist-xl.sh | :heavy_check_mark: |

**Review by harshavardhana — APPROVED** [review]

**Comment by vadmeste** [comment]
@poornas can we add a new unit test to detect this regression in the future ? if you don't have any unit tests for caching, let's open a new issue for this so it can be done one time.

**Review by vadmeste — COMMENTED** [review]
I am not sure what I am missing, but *without* this commit, downloading a file from Azure in Minio gateway mode already works as expected, do this deal with a special use case ?

**Comment by harshavardhana** [comment]
The case this PR tries to handle is when length == -1 , this is when downloading from Minio browser.

File: cmd/disk-cache.go [hunk 1]
```diff
@@ -303,7 +303,7 @@ func (c cacheObjects) GetObject(ctx context.Context, bucket, object string, star
 		}
 		dcache.Delete(ctx, bucket, object)
 	}
-	if startOffset != 0 || length != objInfo.Size {
+	if startOffset != 0 || (length > 0 && length != objInfo.Size) {
```
Comment (vadmeste) [inline cmd/disk-cache.go:306]: I think it is just easier if it is this way:
```
if startOffset != 0 || length == -1 || length != objInfo.Size {
```

**Review by vadmeste — COMMENTED** [review]
One comment

File: cmd/disk-cache.go (hunk 1 above)
Comment (harshavardhana) [reply cmd/disk-cache.go:306]: Actually we need to cache when length == -1 and startOffset == 0

Comment (vadmeste) [reply cmd/disk-cache.go:306]: > Actually we need to cache when length == -1 and startOffset == 0

yes right

**Review by vadmeste — APPROVED** [review]
LGTM & tested

**Comment by poornas** [comment]
@vadmeste, created an issue in mint repo to add tests

**Comment by vadmeste** [comment]
> @vadmeste, created an issue in mint repo to add tests

Thanks.
