### PR TITLE
Put an upper limit on walk pool sizes

### LINKED ISSUE #9835: Excessive memory allocations on ListObjects
On `RELEASE.2020-06-03T22-13-49Z`

## Expected Behavior

Server uses a reasonable amount for ListObject calls.

## Current Behavior

Server Uses 27GB of RAM for ListObjects calls.

image

## Steps to Reproduce (for bugs)

Memory trace supplied.

## Context

Investigate if we can make this scale better.

## Regression

Yes - likely #9697

### PR DESCRIPTION
**Pull request by klauspost**
## Motivation and Context

Fixes potentially infinite allocations, especially in FS mode, since lookups live up to 30 minutes.

Limit walk pool sizes to 50 max parameter entries and 4 concurrent operations with the same parameters.

Fixes #9835

Performance shouldn't be affected in other than extreme cases.

## How to test this PR?

Start excessive number of ListObjects requests.

## Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)

### CODE REVIEW

**Comment by minio-trusted** [comment]
```
Error running mint automation
+ mkdir -p 9848-c02f9ba/gopath/src/github.com/minio
+ git -C 9848-c02f9ba/gopath/src/github.com/minio clone --quiet https://github.com/minio/minio.git
+ git -C 9848-c02f9ba/gopath/src/github.com/minio/minio remote add minio https://github.com/minio/minio.git
+ git -C 9848-c02f9ba/gopath/src/github.com/minio/minio fetch --quiet minio pull/9848/head:pr9848
+ git -C 9848-c02f9ba/gopath/src/github.com/minio/minio checkout --quiet pr9848
+ GO111MODULE=on
+ GOPATH=/home/mint-auto/mint-auto/9848-c02f9ba/gopath
+ make -C 9848-c02f9ba/gopath/src/github.com/minio/minio --quiet
go: downloading cloud.google.com/go v0.39.0
go: downloading gopkg.in/jcmturner/gokrb5.v7 v7.3.0
go: downloading github.com/minio/cli v1.22.0
go: downloading github.com/minio/minio-go/v6 v6.0.58-0.20200612001654-a57fec8037ec
go: downloading github.com/Azure/azure-pipeline-go v0.2.1
go: downloading google.golang.org/api v0.5.0
go: downloading github.com/Azure/azure-storage-blob-go v0.8.0
go: downloading github.com/montanaflynn/stats v0.5.0
go: downloading github.com/gorilla/mux v1.7.0
go: downloading github.com/gorilla/handlers v1.4.0
go: extracting github.com/gorilla/mux v1.7.0
go: extracting github.com/gorilla/handlers v1.4.0
go: extracting github.com/Azure/azure-pipeline-go v0.2.1
go: downloading github.com/coreos/etcd v3.3.12+incompatible
go: downloading github.com/dgrijalva/jwt-go v3.2.0+incompatible
go: downloading github.com/mitchellh/go-homedir v1.1.0
go: extracting github.com/montanaflynn/stats v0.5.0
go: extracting github.com/minio/cli v1.22.0
go: extracting github.com/Azure/azure-storage-blob-go v0.8.0
go: downloading github.com/prometheus/client_golang v0.9.3
go: extracting github.com/mitchellh/go-homedir v1.1.0
go: downloading github.com/djherbis/atime v1.0.0
go: downloading github.com/klauspost/compress v1.10.3
go: extracting github.com/minio/minio-go/v6 v6.0.58-0.20200612001654-a57fec8037ec
go: downloading github.com/tinylib/msgp v1.1.1
go: extracting github.com/dgrijalva/jwt-go v3.2.0+incompatible
go: extracting github.com/prometheus/client_golang v0.9.3
go: downloading github.com/shirou/gopsutil v2.20.3-0.20200314133625-53cec6b37e6a+incompatible
go: downloading github.com/cheggaaa/pb v1.0.28
go: extracting github.com/djherbis/atime v1.0.0
go: downloading github.com/gorilla/rpc v1.2.0
go: extracting github.com/tinylib/msgp v1.1.1
go: extracting github.com/coreos/etcd v3.3.12+incompatible
go: extracting github.com/cheggaaa/pb v1.0.28
go: downloading github.com/mattn/go-runewidth v0.0.4
go: extracting github.com/gorilla/rpc v1.2.0
go: downloading github.com/mattn/go-ieproxy v0.0.0-20190805055040-f9202b1cfdeb
go: downloading github.com/dustin/go-humanize v1.0.0
go: extracting github.com/shirou/gopsutil v2.20.3-0.20200314133625-53cec6b37e6a+incompatible
go: extracting github.com/mattn/go-runewidth v0.0.4
go: downloading github.com/philhofer/fwd v1.0.0
go: downloading github.com/colinmarc/hdfs/v2 v2.1.1
go: extracting github.com/philhofer/fwd v1.0.0
go: extracting github.com/dustin/go-humanize v1.0.0
go: downloading golang.org/x/crypto v0.0.0-20200604202706-70a84ac30bf9
go: downloading github.com/elazarl/go-bindata-assetfs v1.0.0
go: extracting cloud.google.com/go v0.39.0
go: extracting github.com/mattn/go-ieproxy v0.0.0-20190805055040-f9202b1cfdeb
go: downloading github.com/json-iterator/go v1.1.10
go: extracting github.com/colinmarc/hdfs/v2 v2.1.1
go: downloading github.com/minio/sio v0.2.0
go: downloading github.com/prometheus/common v0.4.0
go: extracting github.com/elazarl/go-bindata-assetfs v1.0.0
go: extracting github.com/json-iterator/go v1.1.10
go: extracting github.com/minio/sio v0.2.0
go: downloading github.com/coredns/coredns v1.4.0
go: extracting github.com/prometheus/common v0.4.0
go: downloading github.com/prometheus/client_model v0.0.0-20190129233127-fd36f4220a90
go: extracting golang.org/x/crypto v0.0.0-20200604202706-70a84ac30bf9
go: downloading github.com/minio/sha256-simd v0.1.1
go: downloading github.com/modern-go/concurrent v0.0.0-20180306012644-bacd9c7ef1dd
go: extracting github.com/prometheus/client_model v0.0.0-20190129233127-fd36f4220a90
go: downloading gopkg.in/olivere/elastic.v5 v5.0.80
go: extracting github.com/minio/sha256-simd v0.1.1
go: downloading github.com/willf/bloom v2.0.3+incompatible
go: extracting github.com/modern-go/concurrent v0.0.0-20180306012644-bacd9c7ef1dd
go: downloading github.com/go-sql-driver/mysql v1.5.0
go: extracting github.com/willf/bloom v2.0.3+incompatible
go: downloading google.golang.org/grpc v1.22.0
go: extracting gopkg.in/olivere/elastic.v5 v5.0.80
go: extracting github.com/go-sql-driver/mysql v1.5.0
go: downloading github.com/streadway/amqp v0.0.0-20190404075320-75d898a42a94
go: extracting github.com/coredns/coredns v1.4.0
go: extracting github.com/streadway/amqp v0.0.0-20190404075320-75d898a42a94
go: downloading github.com/miekg/dns v1.1.8
go: downloading github.com/willf/bitset v1.1.10
go: extracting github.com/miekg/dns v1.1.8
go: downloading github.com/modern-go/reflect2 v1.0.1
go: extracting github.com/willf/bitset v1.1.10
go: downloading github.com/mailru/easyjson v0.0.0-20180730094502-03f2033d19d5
go: extracting github.com/modern-go/reflect2 v1.0.1
go: downloading golang.org/x/sys v0.0.0-20200610111108-226ff32320da
go: extracting github.com/mailru/easyjson v0.0.0-20180730094502-03f2033d19d5
go: downloading github.com/matttproud/golang_protobuf_extensions v1.0.1
go: extracting github.com/matttproud/golang_protobuf_extensions v1.0.1
go: extracting google.golang.org/grpc v1.22.0
go: downloading github.com/valyala/tcplisten v0.0.0-20161114210144-ceec8f93295a
go: downloading github.com/ncw/directio v1.0.5
go: downloading github.com/Shopify/sarama v1.24.1
go: extracting github.com/klauspost/compress v1.10.3
go: downloading github.com/nats-io/stan.go v0.4.5
go: downloading github.com/googleapis/gax-go/v2 v2.0.4
go: extracting github.com/ncw/directio v1.0.5
go: extracting github.com/valyala/tcplisten v0.0.0-20161114210144-ceec8f93295a
go: downloading google.golang.org/genproto v0.0.0-20190513181449-d00d292a067c
go: downloading github.com/inconshreveable/go-update v0.0.0-20160112193335-8152e7eb6ccf
go: extracting github.com/nats-io/stan.go v0.4.5
go: downloading github.com/golang/protobuf v1.3.2
go: extracting golang.org/x/sys v0.0.0-20200610111108-226ff32320da
go: extracting github.com/googleapis/gax-go/v2 v2.0.4
go: downloading github.com/xdg/scram v0.0.0-20180814205039-7eeb5667e42c
go: extracting github.com/inconshreveable/go-update v0.0.0-20160112193335-8152e7eb6ccf
go: downloading github.com/nats-io/nuid v1.0.1
go: extracting github.com/Shopify/sarama v1.24.1
go: downloading github.com/fatih/structs v1.1.0
go: downloading github.com/klauspost/reedsolomon v1.9.9
go: extracting github.com/nats-io/nuid v1.0.1
go: extracting github.com/xdg/scram v0.0.0-20180814205039-7eeb5667e42c
go: downloading github.com/rs/cors v1.7.0
go: extracting github.com/fatih/structs v1.1.0
go: downloading github.com/minio/simdjson-go v0.1.5-0.20200303142138-b17fe061ea37
go: extracting github.com/golang/protobuf v1.3.2
go: downloading github.com/alecthomas/participle v0.2.1
go: extracting github.com/rs/cors v1.7.0
go: downloading github.com/pkg/errors v0.8.1
go: extracting github.com/alecthomas/participle v0.2.1
go: downloading github.com/klauspost/pgzip v1.2.1
go: extracting github.com/minio/simdjson-go v0.1.5-0.20200303142138-b17fe061ea37
go: extracting github.com/klauspost/reedsolomon v1.9.9
go: downloading github.com/gomodule/redigo v2.0.0+incompatible
go: extracting github.com/pkg/errors v0.8.1
go: extracting github.com/klauspost/pgzip v1.2.1
go: downloading github.com/klauspost/readahead v1.3.1
go: extracting github.com/klauspost/readahead v1.3.1
go: downloading github.com/minio/highwayhash v1.0.0
go: extracting github.com/gomodule/redigo v2.0.0+incompatible
go: downloading github.com/gogo/protobuf v1.2.1
go: extracting github.com/minio/highwayhash v1.0.0
go: downloading golang.org/x/net v0.0.0-20200602114024-627f9648deb9
go: extracting google.golang.org/genproto v0.0.0-20190513181449-d00d292a067c
go: downloading github.com/spaolacci/murmur3 v1.1.0
go: downloading github.com/google/uuid v1.1.1
go: extracting golang.org/x/net v0.0.0-20200602114024-627f9648deb9
go: downloading gopkg.in/ini.v1 v1.57.0
go: extracting github.com/spaolacci/murmur3 v1.1.0
go: extracting github.com/google/uuid v1.1.1
go: downloading github.com/nsqio/go-nsq v1.0.7
go: downloading github.com/mattn/go-isatty v0.0.8
go: extracting gopkg.in/ini.v1 v1.57.0
go: downloading github.com/bcicen/jstream v0.0.0-20190220045926-16c1f8af81c2
go: extracting github.com/nsqio/go-nsq v1.0.7
go: extracting github.com/mattn/go-isatty v0.0.8
go: downloading github.com/fatih/color v1.7.0
go: downloading github.com/golang/snappy v0.0.1
go: extracting github.com/bcicen/jstream v0.0.0-20190220045926-16c1f8af81c2
go: downloading github.com/mattn/go-colorable v0.1.4
go: extracting github.com/fatih/color v1.7.0
go: downloading github.com/lib/pq v1.1.1
go: extracting github.com/mattn/go-colorable v0.1.4
go: extracting github.com/golang/snappy v0.0.1
go: downloading github.com/beevik/ntp v0.2.0
go: extracting github.com/gogo/protobuf v1.2.1
go: extracting github.com/lib/pq v1.1.1
go: extracting github.com/beevik/ntp v0.2.0
go: extracting gopkg.in/jcmturner/gokrb5.v7 v7.3.0
go: downloading github.com/minio/parquet-go v0.0.0-20200414234858-838cfa8aae61
go: downloading github.com/hashicorp/vault/api v1.0.4
go: downloading github.com/hashicorp/go-uuid v1.0.1
go: downloading go.opencensus.io v0.21.0
go: downloading github.com/klauspost/cpuid v1.3.0
go: downloading github.com/minio/md5-simd v1.1.0
go: downloading github.com/nats-io/nats.go v1.9.1
go: extracting github.com/minio/parquet-go v0.0.0-20200414234858-838cfa8aae61
go: extracting github.com/hashicorp/go-uuid v1.0.1
go: extracting google.golang.org/api v0.5.0
go: downloading github.com/beorn7/perks v1.0.0
go: extracting github.com/hashicorp/vault/api v1.0.4
go: downloading github.com/hashicorp/vault/sdk v0.1.13
go: extracting github.com/nats-io/nats.go v1.9.1
go: extracting github.com/minio/md5-simd v1.1.0
go: downloading github.com/rcrowley/go-metrics v0.0.0-20190704165056-9c2d0518ed81
go: downloading github.com/hashicorp/errwrap v1.0.0
go: extracting github.com/beorn7/perks v1.0.0
go: downloading github.com/cespare/xxhash v1.1.0
go: extracting github.com/klauspost/cpuid v1.3.0
go: extracting github.com/rcrowley/go-metrics v0.0.0-20190704165056-9c2d0518ed81
go: downloading github.com/eapache/go-resiliency v1.2.0
go: extracting github.com/hashicorp/vault/sdk v0.1.13
go: extracting github.com/hashicorp/errwrap v1.0.0
go: extracting github.com/cespare/xxhash v1.1.0
go: downloading github.com/eclipse/paho.mqtt.golang v1.2.0
go: downloading github.com/cespare/xxhash/v2 v2.1.1
go: downloading github.com/jcmturner/gofork v0.0.0-20190328161633-dc7c13fece03
go: extracting go.opencensus.io v0.21.0
go: extracting github.com/eapache/go-resiliency v1.2.0
go: downloading gopkg.in/jcmturner/goidentity.v3 v3.0.0
go: downloading github.com/mitchellh/mapstructure v1.1.2
go: extracting github.com/cespare/xxhash/v2 v2.1.1
go: downloading github.com/hashicorp/go-cleanhttp v0.5.1
go: extracting github.com/eclipse/paho.mqtt.golang v1.2.0
go: extracting github.com/jcmturner/gofork v0.0.0-20190328161633-dc7c13fece03
go: downloading github.com/eapache/go-xerial-snappy v0.0.0-20180814174437-776d5712da21
go: downloading github.com/pierrec/lz4 v2.4.0+incompatible
go: extracting gopkg.in/jcmturner/goidentity.v3 v3.0.0
go: downloading github.com/prometheus/procfs v0.0.0-20190507164030-5867b95ac084
go: extracting github.com/mitchellh/mapstructure v1.1.2
go: downloading github.com/hashicorp/hcl v1.0.0
go: extracting github.com/hashicorp/go-cleanhttp v0.5.1
go: downloading github.com/hashicorp/go-multierror v1.0.0
go: extracting github.com/eapache/go-xerial-snappy v0.0.0-20180814174437-776d5712da21
go: downloading golang.org/x/text v0.3.2
go: extracting github.com/prometheus/procfs v0.0.0-20190507164030-5867b95ac084
go: extracting github.com/hashicorp/hcl v1.0.0
go: downloading github.com/hashicorp/go-retryablehttp v0.5.4
go: downloading github.com/hashicorp/golang-lru v0.5.1
go: downloading github.com/nats-io/jwt v0.3.2
go: downloading github.com/nats-io/nkeys v0.1.3
go: downloading github.com/davecgh/go-spew v1.1.1
go: downloading git.apache.org/thrift.git v0.13.0
go: downloading gopkg.in/jcmturner/dnsutils.v1 v1.0.1
go: extracting github.com/hashicorp/golang-lru v0.5.1
go: extracting github.com/hashicorp/go-retryablehttp v0.5.4
go: downloading golang.org/x/oauth2 v0.0.0-20190402181905-9f3314589c9a
go: downloading github.com/hashicorp/go-rootcerts v1.0.1
go: extracting gopkg.in/jcmturner/dnsutils.v1 v1.0.1
go: downloading github.com/xdg/stringprep v1.0.0
go: extracting github.com/hashicorp/go-rootcerts v1.0.1
go: extracting golang.org/x/oauth2 v0.0.0-20190402181905-9f3314589c9a
go: downloading gopkg.in/ldap.v3 v3.0.3
go: extracting github.com/xdg/stringprep v1.0.0
go: downloading gopkg.in/square/go-jose.v2 v2.3.1
go: extracting gopkg.in/ldap.v3 v3.0.3
go: downloading gopkg.in/yaml.v2 v2.2.8
go: extracting github.com/nats-io/nkeys v0.1.3
go: extracting github.com/nats-io/jwt v0.3.2
go: extracting github.com/davecgh/go-spew v1.1.1
go: downloading github.com/eapache/queue v1.1.0
go: downloading github.com/rjeczalik/notify v0.9.2
go: extracting gopkg.in/yaml.v2 v2.2.8
go: downloading gopkg.in/asn1-ber.v1 v1.0.0-20181015200546-f715ec2f112d
go: extracting github.com/eapache/queue v1.1.0
go: extracting github.com/hashicorp/go-multierror v1.0.0
go: downloading github.com/hashicorp/go-sockaddr v1.0.2
go: downloading github.com/tidwall/gjson v1.3.5
go: extracting github.com/rjeczalik/notify v0.9.2
go: extracting gopkg.in/square/go-jose.v2 v2.3.1
go: extracting gopkg.in/asn1-ber.v1 v1.0.0-20181015200546-f715ec2f112d
go: downloading gopkg.in/jcmturner/aescts.v1 v1.0.1
go: downloading github.com/ryanuber/go-glob v1.0.0
go: downloading github.com/tidwall/sjson v1.0.4
go: extracting gopkg.in/jcmturner/aescts.v1 v1.0.1
go: extracting github.com/hashicorp/go-sockaddr v1.0.2
go: extracting github.com/tidwall/gjson v1.3.5
go: downloading gopkg.in/jcmturner/rpc.v1 v1.1.0
go: downloading github.com/secure-io/sio-go v0.3.0
go: extracting github.com/ryanuber/go-glob v1.0.0
go: downloading golang.org/x/time v0.0.0-20190308202827-9d24e82272b4
go: downloading github.com/tidwall/pretty v1.0.0
go: extracting github.com/tidwall/sjson v1.0.4
go: downloading github.com/tidwall/match v1.0.1
go: extracting gopkg.in/jcmturner/rpc.v1 v1.1.0
go: extracting git.apache.org/thrift.git v0.13.0
go: extracting golang.org/x/time v0.0.0-20190308202827-9d24e82272b4
go: extracting github.com/secure-io/sio-go v0.3.0
go: extracting github.com/tidwall/match v1.0.1
go: extracting github.com/tidwall/pretty v1.0.0
go: extracting golang.org/x/text v0.3.2
go: extracting github.com/pierrec/lz4 v2.4.0+incompatible
go: finding github.com/colinmarc/hdfs/v2 v2.1.1
go: finding gopkg.in/jcmturner/gokrb5.v7 v7.3.0
go: finding github.com/minio/cli v1.22.0
go: finding github.com/minio/minio-go/v6 v6.0.58-0.20200612001654-a57fec8037ec
go: finding github.com/Azure/azure-pipeline-go v0.2.1
go: finding github.com/minio/sha256-simd v0.1.1
go: finding google.golang.org/api v0.5.0
go: finding github.com/dustin/go-humanize v1.0.0
go: finding cloud.google.com/go v0.39.0
go: finding github.com/json-iterator/go v1.1.10
go: finding github.com/minio/highwayhash v1.0.0
go: finding github.com/fatih/color v1.7.0
go: finding github.com/Azure/azure-storage-blob-go v0.8.0
go: finding github.com/dgrijalva/jwt-go v3.2.0+incompatible
go: finding github.com/mattn/go-isatty v0.0.8
go: finding github.com/mattn/go-colorable v0.1.4
go: finding github.com/gorilla/mux v1.7.0
go: finding github.com/montanaflynn/stats v0.5.0
go: finding github.com/valyala/tcplisten v0.0.0-20161114210144-ceec8f93295a
go: finding github.com/rjeczalik/notify v0.9.2
go: finding github.com/secure-io/sio-go v0.3.0
go: finding github.com/shirou/gopsutil v2.20.3-0.20200314133625-53cec6b37e6a+incompatible
go: finding golang.org/x/crypto v0.0.0-20200604202706-70a84ac30bf9
go: finding golang.org/x/net v0.0.0-20200602114024-627f9648deb9
go: finding github.com/ncw/directio v1.0.5
go: finding github.com/golang/protobuf v1.3.2
go: finding github.com/coreos/etcd v3.3.12+incompatible
go: finding github.com/cespare/xxhash/v2 v2.1.1
go: finding github.com/elazarl/go-bindata-assetfs v1.0.0
go: finding golang.org/x/sys v0.0.0-20200610111108-226ff32320da
go: finding github.com/djherbis/atime v1.0.0
go: finding github.com/cheggaaa/pb v1.0.28
go: finding github.com/google/uuid v1.1.1
go: finding github.com/gorilla/handlers v1.4.0
go: finding github.com/gorilla/rpc v1.2.0
go: finding github.com/hashicorp/go-uuid v1.0.1
go: finding github.com/klauspost/readahead v1.3.1
go: finding github.com/jcmturner/gofork v0.0.0-20190328161633-dc7c13fece03
go: finding github.com/klauspost/compress v1.10.3
go: finding github.com/inconshreveable/go-update v0.0.0-20160112193335-8152e7eb6ccf
go: finding gopkg.in/jcmturner/dnsutils.v1 v1.0.1
go: finding gopkg.in/jcmturner/goidentity.v3 v3.0.0
go: finding github.com/klauspost/reedsolomon v1.9.9
go: finding github.com/mitchellh/go-homedir v1.1.0
go: finding gopkg.in/ini.v1 v1.57.0
go: finding github.com/minio/md5-simd v1.1.0
go: finding gopkg.in/jcmturner/aescts.v1 v1.0.1
go: finding github.com/mattn/go-ieproxy v0.0.0-20190805055040-f9202b1cfdeb
go: finding github.com/coredns/coredns v1.4.0
go: finding golang.org/x/oauth2 v0.0.0-20190402181905-9f3314589c9a
go: finding github.com/miekg/dns v1.1.8
go: finding gopkg.in/ldap.v3 v3.0.3
go: finding google.golang.org/grpc v1.22.0
go: finding google.golang.org/genproto v0.0.0-20190513181449-d00d292a067c
go: finding github.com/googleapis/gax-go/v2 v2.0.4
go: finding go.opencensus.io v0.21.0
go: finding github.com/modern-go/concurrent v0.0.0-20180306012644-bacd9c7ef1dd
go: finding github.com/modern-go/reflect2 v1.0.1
go: finding github.com/hashicorp/vault/api v1.0.4
go: finding github.com/beevik/ntp v0.2.0
go: finding github.com/Shopify/sarama v1.24.1
go: finding github.com/minio/sio v0.2.0
go: finding github.com/go-sql-driver/mysql v1.5.0
go: finding gopkg.in/jcmturner/rpc.v1 v1.1.0
go: finding github.com/eclipse/paho.mqtt.golang v1.2.0
go: finding github.com/gomodule/redigo v2.0.0+incompatible
go: finding github.com/lib/pq v1.1.1
go: finding golang.org/x/text v0.3.2
go: finding github.com/nats-io/nats.go v1.9.1
go: finding github.com/gogo/protobuf v1.2.1
go: finding github.com/nats-io/stan.go v0.4.5
go: finding github.com/pkg/errors v0.8.1
go: finding github.com/nsqio/go-nsq v1.0.7
go: finding github.com/xdg/scram v0.0.0-20180814205039-7eeb5667e42c
go: finding github.com/fatih/structs v1.1.0
go: finding github.com/streadway/amqp v0.0.0-20190404075320-75d898a42a94
go: finding github.com/mattn/go-runewidth v0.0.4
go: finding gopkg.in/yaml.v2 v2.2.8
go: finding github.com/klauspost/pgzip v1.2.1
go: finding github.com/prometheus/client_golang v0.9.3
go: finding github.com/rs/cors v1.7.0
go: finding github.com/bcicen/jstream v0.0.0-20190220045926-16c1f8af81c2
go: finding github.com/willf/bloom v2.0.3+incompatible
go: finding github.com/tinylib/msgp v1.1.1
go: finding github.com/minio/parquet-go v0.0.0-20200414234858-838cfa8aae61
go: finding github.com/minio/simdjson-go v0.1.5-0.20200303142138-b17fe061ea37
go: finding github.com/alecthomas/participle v0.2.1
go: finding github.com/klauspost/cpuid v1.3.0
go: finding gopkg.in/asn1-ber.v1 v1.0.0-20181015200546-f715ec2f112d
go: finding gopkg.in/olivere/elastic.v5 v5.0.80
go: finding github.com/hashicorp/golang-lru v0.5.1
go: finding github.com/hashicorp/errwrap v1.0.0
go: finding github.com/hashicorp/go-retryablehttp v0.5.4
go: finding github.com/hashicorp/go-cleanhttp v0.5.1
go: finding github.com/hashicorp/vault/sdk v0.1.13
go: finding github.com/hashicorp/hcl v1.0.0
go: finding golang.org/x/time v0.0.0-20190308202827-9d24e82272b4
go: finding github.com/hashicorp/go-multierror v1.0.0
go: finding github.com/hashicorp/go-rootcerts v1.0.1
go: finding github.com/mitchellh/mapstructure v1.1.2
go: finding gopkg.in/square/go-jose.v2 v2.3.1
go: finding github.com/eapache/go-xerial-snappy v0.0.0-20180814174437-776d5712da21
go: finding github.com/eapache/queue v1.1.0
go: finding github.com/eapache/go-resiliency v1.2.0
go: finding github.com/pierrec/lz4 v2.4.0+incompatible
go: finding github.com/rcrowley/go-metrics v0.0.0-20190704165056-9c2d0518ed81
go: finding github.com/davecgh/go-spew v1.1.1
go: finding github.com/nats-io/nuid v1.0.1
go: finding github.com/nats-io/nkeys v0.1.3
go: finding github.com/nats-io/jwt v0.3.2
go: finding github.com/golang/snappy v0.0.1
go: finding github.com/xdg/stringprep v1.0.0
go: finding github.com/prometheus/client_model v0.0.0-20190129233127-fd36f4220a90
go: finding github.com/beorn7/perks v1.0.0
go: finding github.com/prometheus/common v0.4.0
go: finding github.com/prometheus/procfs v0.0.0-20190507164030-5867b95ac084
go: finding github.com/spaolacci/murmur3 v1.1.0
go: finding github.com/willf/bitset v1.1.10
go: finding github.com/philhofer/fwd v1.0.0
go: finding github.com/tidwall/sjson v1.0.4
go: finding github.com/tidwall/gjson v1.3.5
go: finding git.apache.org/thrift.git v0.13.0
go: finding github.com/mailru/easyjson v0.0.0-20180730094502-03f2033d19d5
go: finding github.com/ryanuber/go-glob v1.0.0
go: finding github.com/hashicorp/go-sockaddr v1.0.2
go: finding github.com/matttproud/golang_protobuf_extensions v1.0.1
go: finding github.com/tidwall/match v1.0.1
go: finding github.com/tidwall/pretty v1.0.0
# github.com/minio/minio/cmd
cmd/bucket-handlers.go:993:36: undefined: getBucketVersioningResponse
make: *** [build] Error 2

```

**Comment by klauspost** [comment]
Getting `
cmd/bucket-handlers.go:993:36: undefined: getBucketVersioningResponse` locally as well. Broken?

**Comment by harshavardhana** [comment]
> Getting ` cmd/bucket-handlers.go:993:36: undefined: getBucketVersioningResponse` locally as well. Broken?

It is better to submit to master and we cherry-pick if needed for release @klauspost

**Comment by harshavardhana** [comment]
> Getting ` cmd/bucket-handlers.go:993:36: undefined: getBucketVersioningResponse` locally as well. Broken?

Will check if release branch broke something when cherry-picked.

**Comment by klauspost** [comment]
@harshavardhana Seems release has changes not in master :/

**Comment by harshavardhana** [comment]
> @harshavardhana Seems release has changes not in master :/

I just pushed the fix @klauspost

**Review by harshavardhana — APPROVED** [review]

**Comment by minio-trusted** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-s3.sh | :heavy_check_mark: |
| mint-gateway-azure.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-xl.sh | :x: [more...](#d19fd8d8-4f28-4696-bdf0-777a502e13fa) |
| mint-large-bucket.sh | :x: [more...](#f6455a7e-cfce-417d-9462-b775a5cecef8) |
| mint-dist-xl.sh | :x: [more...](#03ddb174-1680-494d-8e50-d17ba9ea0684) |
<a name="03ddb174-1680-494d-8e50-d17ba9ea0684"></a>
### 9848-5a4c917/mint-dist-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-dev4.minio.io:32012
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 1470cda8cb2d:/mint/log /tmp/mint-logs'

(1/15) Running aws-sdk-go tests ... done in 1 seconds
(2/15) Running aws-sdk-java tests ... done in 2 seconds
(3/15) Running aws-sdk-php tests ... done in 42 seconds
(4/15) Running aws-sdk-ruby tests ... done in 4 seconds
(5/15) Running awscli tests ... done in 1 minutes and 27 seconds
(6/15) Running healthcheck tests ... done in 0 seconds
(7/15) Running mc tests ... done in 41 seconds
(8/15) Running minio-dotnet tests ... done in 57 seconds
(9/15) Running minio-go tests ... FAILED in 1 minutes and 26 seconds
{
  "args": {
    "bucketName": "minio-go-test-05nou15rs102662m",
    "objectName": "vjzhhtxim64mk2zr2bqkoe3shk26rg",
    "objectPrefix": "",
    "recursive": "true"
  },
  "duration": 8408,
  "error": "The bucket you tried to delete is not empty. You must delete all versions in the bucket.",
  "function": "RemoveObjectsWithOptions(bucketName, objectsCh, opts)",
  "message": "Cleanup failed",
  "name": "minio-go: testRemoveObjectsWithOptions",
  "status": "FAIL"
}
(9/15) Running minio-java tests ... FAILED in 2 minutes and 30 seconds
{
  "name": "minio-java",
  "function": "enableObjectLegalHold(String bucketName, String objectName, String versionId)",
  "duration": 287,
  "status": "FAIL",
  "error": "error occurred\nErrorResponse(code = BucketNotEmpty, message = The bucket you tried to delete is not empty. You must delete all versions in the bucket., bucketName = minio-java-test-2mujjq0, objectName = null, resource = /minio-java-test-2mujjq0, requestId = 161913E3C342FCD1, hostId = 4d6dc833-7b76-4bef-a7dc-01dc1ccee64a)\nrequest={method=DELETE, url=http://minio-dev4.minio.io:32012/minio-java-test-2mujjq0, headers=Host: minio-dev4.minio.io:32012\nAccept-Encoding: identity\nUser-Agent: MinIO (amd64; amd64) minio-java/dev\nContent-MD5: 1B2M2Y8AsgTpgAmY7PhCfg==\nx-amz-content-sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855\nx-amz-date: 20200616T164332Z\nAuthorization: AWS4-HMAC-SHA256 Credential=*REDACTED*/20200616/us-east-1/s3/aws4_request, SignedHeaders=accept-encoding;content-md5;host;x-amz-content-sha256;x-amz-date, Signature=*REDACTED*\n}\nresponse={code=409, headers=Accept-Ranges: bytes\nContent-Length: 373\nContent-Security-Policy: block-all-mixed-content\nContent-Type: application/xml\nServer: MinIO/DEVELOPMENT.2020-06-16T16-29-48Z\nVary: Origin\nX-Amz-Request-Id: 161913E3C342FCD1\nX-Xss-Protection: 1; mode=block\nDate: Tue, 16 Jun 2020 16:43:32 GMT\n}\n >>> [io.minio.MinioClient.execute(MinioClient.java:1211), io.minio.MinioClient.execute(MinioClient.java:1236), io.minio.MinioClient.executeDelete(MinioClient.java:1366), io.minio.MinioClient.removeBucket(MinioClient.java:3686), FunctionalTest.enableObjectLegalHold_test(FunctionalTest.java:3314), FunctionalTest.runTests(FunctionalTest.java:4079), FunctionalTest.main(FunctionalTest.java:4192)]"
}
(9/15) Running minio-js tests ... done in 51 seconds
(10/15) Running minio-py tests ... done in 1 minutes and 50 seconds
(11/15) Running s3cmd tests ... done in 27 seconds
(12/15) Running s3select tests ... done in 7 seconds
(13/15) Running security tests ... done in 0 seconds

Executed 13 out of 15 tests successfully.
```
<a name="d19fd8d8-4f28-4696-bdf0-777a502e13fa"></a>
### 9848-5a4c917/mint-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-c3.minio.io:32676
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp cf05fe450991:/mint/log /tmp/mint-logs'

(1/15) Running aws-sdk-go tests ... done in 1 seconds
(2/15) Running aws-sdk-java tests ... done in 1 seconds
(3/15) Running aws-sdk-php tests ... done in 41 seconds
(4/15) Running aws-sdk-ruby tests ... done in 3 seconds
(5/15) Running awscli tests ... done in 1 minutes and 20 seconds
(6/15) Running healthcheck tests ... done in 0 seconds
(7/15) Running mc tests ... done in 30 seconds
(8/15) Running minio-dotnet tests ... done in 33 seconds
(9/15) Running minio-go tests ... FAILED in 52 seconds
{
  "args": {
    "bucketName": "minio-go-test-blzxsdfykqd1a2or",
    "objectName": "ie4o5uf4jshuuchy9gmthk60fhxn2l",
    "objectPrefix": "",
    "recursive": "true"
  },
  "duration": 4690,
  "error": "The bucket you tried to delete is not empty. You must delete all versions in the bucket.",
  "function": "RemoveObjectsWithOptions(bucketName, objectsCh, opts)",
  "message": "Cleanup failed",
  "name": "minio-go: testRemoveObjectsWithOptions",
  "status": "FAIL"
}
(9/15) Running minio-java tests ... FAILED in 55 seconds
{
  "name": "minio-java",
  "function": "enableObjectLegalHold(String bucketName, String objectName, String versionId)",
  "duration": 129,
  "status": "FAIL",
  "error": "error occurred\nErrorResponse(code = BucketNotEmpty, message = The bucket you tried to delete is not empty. You must delete all versions in the bucket., bucketName = minio-java-test-9jir30, objectName = null, resource = /minio-java-test-9jir30, requestId = 161913BAF88E5D3A, hostId = 1066928a-2939-40b4-a0f4-fe259249de0c)\nrequest={method=DELETE, url=http://minio-c3.minio.io:32676/minio-java-test-9jir30, headers=Host: minio-c3.minio.io:32676\nAccept-Encoding: identity\nUser-Agent: MinIO (amd64; amd64) minio-java/dev\nContent-MD5: 1B2M2Y8AsgTpgAmY7PhCfg==\nx-amz-content-sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855\nx-amz-date: 20200616T164037Z\nAuthorization: AWS4-HMAC-SHA256 Credential=*REDACTED*/20200616/us-east-1/s3/aws4_request, SignedHeaders=accept-encoding;content-md5;host;x-amz-content-sha256;x-amz-date, Signature=*REDACTED*\n}\nresponse={code=409, headers=Accept-Ranges: bytes\nContent-Length: 371\nContent-Security-Policy: block-all-mixed-content\nContent-Type: application/xml\nServer: MinIO/DEVELOPMENT.2020-06-16T16-29-48Z\nVary: Origin\nX-Amz-Request-Id: 161913BAF88E5D3A\nX-Xss-Protection: 1; mode=block\nDate: Tue, 16 Jun 2020 16:40:37 GMT\n}\n >>> [io.minio.MinioClient.execute(MinioClient.java:1211), io.minio.MinioClient.execute(MinioClient.java:1236), io.minio.MinioClient.executeDelete(MinioClient.java:1366), io.minio.MinioClient.removeBucket(MinioClient.java:3686), FunctionalTest.enableObjectLegalHold_test(FunctionalTest.java:3314), FunctionalTest.runTests(FunctionalTest.java:4079), FunctionalTest.main(FunctionalTest.java:4192)]"
}
(9/15) Running minio-js tests ... done in 56 seconds
(10/15) Running minio-py tests ... done in 1 minutes and 20 seconds
(11/15) Running s3cmd tests ... done in 19 seconds
(12/15) Running s3select tests ... done in 3 seconds
(13/15) Running security tests ... done in 0 seconds

Executed 13 out of 15 tests successfully.
```
<a name="f6455a7e-cfce-417d-9462-b775a5cecef8"></a>
### 9848-5a4c917/mint-large-bucket.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-dev7.minio.io:31425
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 22fe6593b7df:/mint/log /tmp/mint-logs'

(1/15) Running aws-sdk-go tests ... done in 5 seconds
(2/15) Running aws-sdk-java tests ... done in 2 seconds
(3/15) Running aws-sdk-php tests ... done in 46 seconds
(4/15) Running aws-sdk-ruby tests ... done in 10 seconds
(5/15) Running awscli tests ... done in 2 minutes and 32 seconds
(6/15) Running healthcheck tests ... done in 0 seconds
(7/15) Running mc tests ... done in 55 seconds
(8/15) Running minio-dotnet tests ... done in 1 minutes and 4 seconds
(9/15) Running minio-go tests ... FAILED in 1 minutes and 49 seconds
{
  "args": {
    "bucketName": "minio-go-test-kii5bp6vl313iyo0",
    "objectName": "y3ytzob0oktwi0jk3xv2ccxud2vue2",
    "objectPrefix": "",
    "recursive": "true"
  },
  "duration": 4126,
  "error": "The bucket you tried to delete is not empty. You must delete all versions in the bucket.",
  "function": "RemoveObjectsWithOptions(bucketName, objectsCh, opts)",
  "message": "Cleanup failed",
  "name": "minio-go: testRemoveObjectsWithOptions",
  "status": "FAIL"
}
(9/15) Running minio-java tests ... FAILED in 6 minutes and 21 seconds
{
  "name": "minio-java",
  "function": "enableObjectLegalHold(String bucketName, String objectName, String versionId)",
  "duration": 1065,
  "status": "FAIL",
  "error": "error occurred\nErrorResponse(code = BucketNotEmpty, message = The bucket you tried to delete is not empty. You must delete all versions in the bucket., bucketName = minio-java-test-2llnpf7, objectName = null, resource = /minio-java-test-2llnpf7, requestId = 1619143634F8F668, hostId = 5509e216-105c-40b4-955e-4e7dd844e0c1)\nrequest={method=DELETE, url=http://minio-dev7.minio.io:31425/minio-java-test-2llnpf7, headers=Host: minio-dev7.minio.io:31425\nAccept-Encoding: identity\nUser-Agent: MinIO (amd64; amd64) minio-java/dev\nContent-MD5: 1B2M2Y8AsgTpgAmY7PhCfg==\nx-amz-content-sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855\nx-amz-date: 20200616T164926Z\nAuthorization: AWS4-HMAC-SHA256 Credential=*REDACTED*/20200616/us-east-1/s3/aws4_request, SignedHeaders=accept-encoding;content-md5;host;x-amz-content-sha256;x-amz-date, Signature=*REDACTED*\n}\nresponse={code=409, headers=Accept-Ranges: bytes\nContent-Length: 373\nContent-Security-Policy: block-all-mixed-content\nContent-Type: application/xml\nServer: MinIO/DEVELOPMENT.2020-06-16T16-29-48Z\nVary: Origin\nX-Amz-Request-Id: 1619143634F8F668\nX-Xss-Protection: 1; mode=block\nDate: Tue, 16 Jun 2020 16:49:26 GMT\n}\n >>> [io.minio.MinioClient.execute(MinioClient.java:1211), io.minio.MinioClient.execute(MinioClient.java:1236), io.minio.MinioClient.executeDelete(MinioClient.java:1366), io.minio.MinioClient.removeBucket(MinioClient.java:3686), FunctionalTest.enableObjectLegalHold_test(FunctionalTest.java:3314), FunctionalTest.runTests(FunctionalTest.java:4079), FunctionalTest.main(FunctionalTest.java:4192)]"
}
(9/15) Running minio-js tests ... done in 54 seconds
(10/15) Running minio-py tests ... done in 5 minutes and 39 seconds
(11/15) Running s3cmd tests ... done in 25 seconds
(12/15) Running s3select tests ... done in 15 seconds
(13/15) Running security tests ... done in 0 seconds

Executed 13 out of 15 tests successfully.
```
Deleting image on docker hub
Deleting image locally

File: cmd/tree-walk-pool.go [hunk 1]
```diff
@@ -25,7 +25,9 @@ import (
 
 // Global lookup timeout.
 const (
-	globalLookupTimeout = time.Minute * 30 // 30minutes.
+	globalLookupTimeout    = time.Minute * 30 // 30minutes.
+	treeWalkEntryLimit     = 50
```
Comment (vadmeste) [inline cmd/tree-walk-pool.go:29]: Does this mean that we only cache 50 parallel listing in maximum ? isn't this a bit low ?

File: cmd/merge-walk-pool.go [hunk 2]
```diff
@@ -195,17 +197,53 @@ func (t *MergeWalkPool) Set(params listParams, resultChs []FileInfoCh, endWalkCh
...
+	// If we are above the limit delete at least one entry from the pool.
+	if len(t.pool) > treeWalkEntryLimit {
+		age := time.Now()
+		var oldest listParams
+		for k, v := range t.pool {
+			if len(v) == 0 {
+				delete(t.pool, k)
+				continue
+			}
+			if v[0].added.Before(age) {
```
Comment (vadmeste) [inline cmd/merge-walk-pool.go:210]: Let's add one comment here, v[0] is always the oldest element in v list

File: cmd/tree-walk-pool.go [hunk 3]
```diff
@@ -100,22 +104,58 @@ func (t *TreeWalkPool) Release(params listParams) (resultCh chan TreeWalkResult,
...
+	// If we are above the limit delete at least one entry from the pool.
+	if len(t.pool) > treeWalkEntryLimit {
+		age := time.Now()
+		var oldest listParams
+		for k, v := range t.pool {
+			if len(v) == 0 {
+				delete(t.pool, k)
+				continue
+			}
+			if v[0].added.Before(age) {
```
Comment (vadmeste) [inline cmd/tree-walk-pool.go:124]: Let's add a comment here: v[0] is the oldest element in v list

**Review by vadmeste — COMMENTED** [review]
Some comments, LGTM otherwise

File: cmd/tree-walk-pool.go (hunk 1 above)
Comment (klauspost) [reply cmd/tree-walk-pool.go:29]: It is 50 *ongoing* with different params.  So we can have 50*4 in theory. Each being ~1.1MB, total max ~220MB.

I think that is a very reasonable number. The worst thing that will happen is that some of them will be a bit slow.

Comment (klauspost) [reply cmd/tree-walk-pool.go:29]: If it is too slow, then don't hammer the servers.

**Comment by minio-trusted** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-s3.sh | :heavy_check_mark: |
| mint-gateway-azure.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-xl.sh | :x: [more...](#21dd94dd-c01d-486f-992b-c13b83f87881) |
| mint-large-bucket.sh | :x: [more...](#d4257e55-50db-4eed-b960-3203bd27453b) |
| mint-dist-xl.sh | :x: [more...](#548fd3c0-517b-4a48-b007-26c7f50716ca) |
<a name="548fd3c0-517b-4a48-b007-26c7f50716ca"></a>
### 9848-c57cf20/mint-dist-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-dev7.minio.io:30828
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 530941459f29:/mint/log /tmp/mint-logs'

(1/15) Running aws-sdk-go tests ... done in 1 seconds
(2/15) Running aws-sdk-java tests ... done in 2 seconds
(3/15) Running aws-sdk-php tests ... done in 42 seconds
(4/15) Running aws-sdk-ruby tests ... done in 4 seconds
(5/15) Running awscli tests ... done in 2 minutes and 22 seconds
(6/15) Running healthcheck tests ... done in 0 seconds
(7/15) Running mc tests ... done in 56 seconds
(8/15) Running minio-dotnet tests ... done in 43 seconds
(9/15) Running minio-go tests ... FAILED in 1 minutes and 7 seconds
{
  "args": {
    "bucketName": "minio-go-test-5qwyh3z2sr4qrpjc",
    "objectName": "pkfbn445mwwypqnwuyo30hui11mdo5",
    "objectPrefix": "",
    "recursive": "true"
  },
  "duration": 3554,
  "error": "The bucket you tried to delete is not empty. You must delete all versions in the bucket.",
  "function": "RemoveObjectsWithOptions(bucketName, objectsCh, opts)",
  "message": "Cleanup failed",
  "name": "minio-go: testRemoveObjectsWithOptions",
  "status": "FAIL"
}
(9/15) Running minio-java tests ... FAILED in 2 minutes and 29 seconds
{
  "name": "minio-java",
  "function": "enableObjectLegalHold(String bucketName, String objectName, String versionId)",
  "duration": 238,
  "status": "FAIL",
  "error": "error occurred\nErrorResponse(code = BucketNotEmpty, message = The bucket you tried to delete is not empty. You must delete all versions in the bucket., bucketName = minio-java-test-qrumkg, objectName = null, resource = /minio-java-test-qrumkg, requestId = 16195EF306888FF2, hostId = 7b4f7f30-248a-494b-9cf8-3c5d93228b0c)\nrequest={method=DELETE, url=http://minio-dev7.minio.io:30828/minio-java-test-qrumkg, headers=Host: minio-dev7.minio.io:30828\nAccept-Encoding: identity\nUser-Agent: MinIO (amd64; amd64) minio-java/dev\nContent-MD5: 1B2M2Y8AsgTpgAmY7PhCfg==\nx-amz-content-sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855\nx-amz-date: 20200617T153901Z\nAuthorization: AWS4-HMAC-SHA256 Credential=*REDACTED*/20200617/us-east-1/s3/aws4_request, SignedHeaders=accept-encoding;content-md5;host;x-amz-content-sha256;x-amz-date, Signature=*REDACTED*\n}\nresponse={code=409, headers=Accept-Ranges: bytes\nContent-Length: 371\nContent-Security-Policy: block-all-mixed-content\nContent-Type: application/xml\nServer: MinIO/DEVELOPMENT.2020-06-17T15-24-44Z\nVary: Origin\nX-Amz-Request-Id: 16195EF306888FF2\nX-Xss-Protection: 1; mode=block\nDate: Wed, 17 Jun 2020 15:39:01 GMT\n}\n >>> [io.minio.MinioClient.execute(MinioClient.java:1211), io.minio.MinioClient.execute(MinioClient.java:1236), io.minio.MinioClient.executeDelete(MinioClient.java:1366), io.minio.MinioClient.removeBucket(MinioClient.java:3686), FunctionalTest.enableObjectLegalHold_test(FunctionalTest.java:3314), FunctionalTest.runTests(FunctionalTest.java:4079), FunctionalTest.main(FunctionalTest.java:4192)]"
}
(9/15) Running minio-js tests ... done in 47 seconds
(10/15) Running minio-py tests ... done in 1 minutes and 39 seconds
(11/15) Running s3cmd tests ... done in 21 seconds
(12/15) Running s3select tests ... done in 5 seconds
(13/15) Running security tests ... done in 0 seconds

Executed 13 out of 15 tests successfully.
```
<a name="d4257e55-50db-4eed-b960-3203bd27453b"></a>
### 9848-c57cf20/mint-large-bucket.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-dev6.minio.io:31693
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp b40b963093bc:/mint/log /tmp/mint-logs'

(1/15) Running aws-sdk-go tests ... done in 5 seconds
(2/15) Running aws-sdk-java tests ... done in 2 seconds
(3/15) Running aws-sdk-php tests ... done in 47 seconds
(4/15) Running aws-sdk-ruby tests ... done in 9 seconds
(5/15) Running awscli tests ... done in 2 minutes and 39 seconds
(6/15) Running healthcheck tests ... done in 0 seconds
(7/15) Running mc tests ... done in 52 seconds
(8/15) Running minio-dotnet tests ... done in 1 minutes and 12 seconds
(9/15) Running minio-go tests ... FAILED in 2 minutes and 9 seconds
{
  "args": {
    "bucketName": "minio-go-test-e56m5z5sjfz5b2jo",
    "objectName": "niuqcjiyalffqtboxnvzecjtfs406p",
    "objectPrefix": "",
    "recursive": "true"
  },
  "duration": 5249,
  "error": "The bucket you tried to delete is not empty. You must delete all versions in the bucket.",
  "function": "RemoveObjectsWithOptions(bucketName, objectsCh, opts)",
  "message": "Cleanup failed",
  "name": "minio-go: testRemoveObjectsWithOptions",
  "status": "FAIL"
}
(9/15) Running minio-java tests ... FAILED in 6 minutes and 36 seconds
{
  "name": "minio-java",
  "function": "enableObjectLegalHold(String bucketName, String objectName, String versionId)",
  "duration": 989,
  "status": "FAIL",
  "error": "error occurred\nErrorResponse(code = BucketNotEmpty, message = The bucket you tried to delete is not empty. You must delete all versions in the bucket., bucketName = minio-java-test-4eqrmh, objectName = null, resource = /minio-java-test-4eqrmh, requestId = 16195F480CA59969, hostId = 10cc116a-dee4-4d93-9743-7d4513f671fd)\nrequest={method=DELETE, url=http://minio-dev6.minio.io:31693/minio-java-test-4eqrmh, headers=Host: minio-dev6.minio.io:31693\nAccept-Encoding: identity\nUser-Agent: MinIO (amd64; amd64) minio-java/dev\nContent-MD5: 1B2M2Y8AsgTpgAmY7PhCfg==\nx-amz-content-sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855\nx-amz-date: 20200617T154506Z\nAuthorization: AWS4-HMAC-SHA256 Credential=*REDACTED*/20200617/us-east-1/s3/aws4_request, SignedHeaders=accept-encoding;content-md5;host;x-amz-content-sha256;x-amz-date, Signature=*REDACTED*\n}\nresponse={code=409, headers=Accept-Ranges: bytes\nContent-Length: 371\nContent-Security-Policy: block-all-mixed-content\nContent-Type: application/xml\nServer: MinIO/DEVELOPMENT.2020-06-17T15-24-44Z\nVary: Origin\nX-Amz-Request-Id: 16195F480CA59969\nX-Xss-Protection: 1; mode=block\nDate: Wed, 17 Jun 2020 15:45:06 GMT\n}\n >>> [io.minio.MinioClient.execute(MinioClient.java:1211), io.minio.MinioClient.execute(MinioClient.java:1236), io.minio.MinioClient.executeDelete(MinioClient.java:1366), io.minio.MinioClient.removeBucket(MinioClient.java:3686), FunctionalTest.enableObjectLegalHold_test(FunctionalTest.java:3314), FunctionalTest.runTests(FunctionalTest.java:4079), FunctionalTest.main(FunctionalTest.java:4192)]"
}
(9/15) Running minio-js tests ... done in 59 seconds
(10/15) Running minio-py tests ... done in 5 minutes and 43 seconds
(11/15) Running s3cmd tests ... done in 28 seconds
(12/15) Running s3select tests ... done in 15 seconds
(13/15) Running security tests ... done in 0 seconds

Executed 13 out of 15 tests successfully.
```
<a name="21dd94dd-c01d-486f-992b-c13b83f87881"></a>
### 9848-c57cf20/mint-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-dev3.minio.io:32394
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 6899cef52b13:/mint/log /tmp/mint-logs'

(1/15) Running aws-sdk-go tests ... done in 1 seconds
(2/15) Running aws-sdk-java tests ... done in 1 seconds
(3/15) Running aws-sdk-php tests ... done in 42 seconds
(4/15) Running aws-sdk-ruby tests ... done in 2 seconds
(5/15) Running awscli tests ... done in 1 minutes and 17 seconds
(6/15) Running healthcheck tests ... done in 1 seconds
(7/15) Running mc tests ... done in 28 seconds
(8/15) Running minio-dotnet tests ... done in 31 seconds
(9/15) Running minio-go tests ... FAILED in 1 minutes and 14 seconds
{
  "args": {
    "bucketName": "minio-go-test-grvlp9q161coxzv4",
    "objectName": "5bxqceqtgwvrei55k66uc63mnlp9k1",
    "objectPrefix": "",
    "recursive": "true"
  },
  "duration": 4839,
  "error": "The bucket you tried to delete is not empty. You must delete all versions in the bucket.",
  "function": "RemoveObjectsWithOptions(bucketName, objectsCh, opts)",
  "message": "Cleanup failed",
  "name": "minio-go: testRemoveObjectsWithOptions",
  "status": "FAIL"
}
(9/15) Running minio-java tests ... FAILED in 52 seconds
{
  "name": "minio-java",
  "function": "enableObjectLegalHold(String bucketName, String objectName, String versionId)",
  "duration": 114,
  "status": "FAIL",
  "error": "error occurred\nErrorResponse(code = BucketNotEmpty, message = The bucket you tried to delete is not empty. You must delete all versions in the bucket., bucketName = minio-java-test-if84jk, objectName = null, resource = /minio-java-test-if84jk, requestId = 16195EC5185C4631, hostId = df1713bf-5245-4e2e-a48f-ed56b4892b79)\nrequest={method=DELETE, url=http://minio-dev3.minio.io:32394/minio-java-test-if84jk, headers=Host: minio-dev3.minio.io:32394\nAccept-Encoding: identity\nUser-Agent: MinIO (amd64; amd64) minio-java/dev\nContent-MD5: 1B2M2Y8AsgTpgAmY7PhCfg==\nx-amz-content-sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855\nx-amz-date: 20200617T153543Z\nAuthorization: AWS4-HMAC-SHA256 Credential=*REDACTED*/20200617/us-east-1/s3/aws4_request, SignedHeaders=accept-encoding;content-md5;host;x-amz-content-sha256;x-amz-date, Signature=*REDACTED*\n}\nresponse={code=409, headers=Accept-Ranges: bytes\nContent-Length: 371\nContent-Security-Policy: block-all-mixed-content\nContent-Type: application/xml\nServer: MinIO/DEVELOPMENT.2020-06-17T15-24-44Z\nVary: Origin\nX-Amz-Request-Id: 16195EC5185C4631\nX-Xss-Protection: 1; mode=block\nDate: Wed, 17 Jun 2020 15:35:43 GMT\n}\n >>> [io.minio.MinioClient.execute(MinioClient.java:1211), io.minio.MinioClient.execute(MinioClient.java:1236), io.minio.MinioClient.executeDelete(MinioClient.java:1366), io.minio.MinioClient.removeBucket(MinioClient.java:3686), FunctionalTest.enableObjectLegalHold_test(FunctionalTest.java:3314), FunctionalTest.runTests(FunctionalTest.java:4079), FunctionalTest.main(FunctionalTest.java:4192)]"
}
(9/15) Running minio-js tests ... done in 51 seconds
(10/15) Running minio-py tests ... done in 1 minutes and 24 seconds
(11/15) Running s3cmd tests ... done in 23 seconds
(12/15) Running s3select tests ... done in 2 seconds
(13/15) Running security tests ... done in 1 seconds

Executed 13 out of 15 tests successfully.
```
Deleting image on docker hub
Deleting image locally

**Review by vadmeste — APPROVED** [review]
LGTM
